### ISSUE TITLE
Add programmatic method of showing DatePicker errors on form validation

### ISSUE THREAD

**Issue by lorejoh12** [microsoft/fluentui#10026]
#### Describe the feature that you would like added

We've gotten several feature requests about form validation on the DatePicker component. There's a couple of validations that currently exist- checking that the date range is valid and that the date is included if required.

However, the checks only run on text field blur. Basically, require the user to interact with the component before showing any errors. This make sure the page doesn't initialize with a bunch of errors on it.

However, if the user tries to submit a form without picking a required date, we need the component to be able to display the error message without that interaction.

One way is to add an imperative method to run the validation. A more React-ful way of doing it is maybe add a new prop for "runValidationOnMount" that can be toggled on for when the form submits, for example.

#### What component or utility would this be added to

DatePicker

**Comment by marygans** [comment]
Hi @lorejoh12 ! Thanks for submitting this feature request. It looks like your team will is considering adding this feature. Do you think this a feature will need further backlog review/discussion with @micahgodbolt?
