### ISSUE TITLE
FocusZone: Focus should wrap consistently with ms-wide defined behaviors

### ISSUE THREAD

**Issue by jspurlin** [microsoft/fluentui#10133]
### Environment Information

- **Package version(s)**: 7.22.2

### Please provide a reproduction of the bug in a codepen:

Load the following codepens (resize the window so that you have multiple rows of controls, if needed) and either put focus on the first row or last row and press up/down arrow (relatively speaking).  

Base FocusZonePen:
https://codepen.io/jspurlin/pen/xxKbGVR?&editable=true

FocusZone with `data-no-vertical-wrap={true}`:
https://codepen.io/jspurlin/pen/QWLwELj?&editable=true

 
#### Actual behavior:
* In the first codepen focus stays in the current row and jumps to the prev/next element until it wraps.
* In the second codepen the focus wraps to the very last/first item in the FocusZone

#### Expected behavior:
Focus behavior align with the Microsoft-wide guidelines for navigating rows/columns of content:

* Right/Left arrows wrap to the next/prev row, regardless of number of cells
* Down/Up arrows wrap to the next/prev column, regardless of number of cells
* If the last row/cell is reached and Right arrow is pressed, nav goes back to the first row/cell, and vice versa
* If last column/cell is reached and Down arrow is pressed, nav goes back to first column/cell, and vice versa.

I thought https://github.com/OfficeDev/office-ui-fabric-react/pull/9534 was going to improve this experience, but that was not the case.

The proper fix here is probably going to be somewhat involved because it's changing the core behavior of FocusZone

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Normal

Products/sites affected: Office Online

**Comment by JasonGore** [comment]
To clarify, both CodePens have an issue with columnar navigation. Row major keyboard navigation is fine in both cases, but the columnar navigation is incorrect in both cases. This diagram helped me understand the disparity in behavior between row and column navigation:

![image](https://user-images.githubusercontent.com/26070760/62899080-dc4f8680-bd0b-11e9-8093-dfca34be1ac3.png)

**Comment by JasonGore** [comment]
A fix for this issue should also address #10145.

**Comment by jspurlin** [comment]
@JasonGore / @dzearing any update on this work?

**Comment by smhigley** [comment]
I just took a look at both codepens, and the behavior is super weird. My own expectation would be to either treat a set as linear (so both left & up are the same, and right & down are the same), or two-dimensional, where arrow keys do not wrap to a different row/column (and items wouldn't reflow to different rows/columns).

My understanding of the linked UWP keyboard page supports that view -- those graphics of the row wrapping behavior and column wrapping behavior are both for linear sets, and they are mutually exclusive. That is, if a set were to have items added first horizontally and wrapping to new rows, then arrow keys would follow the same path. If a set were to have items added first vertically and then wrapping to new columns, arrow keys would follow that path. Both docs examples do not show true table/grid relationships, and should not have two-dimensional keyboard navigation.

The linked codepens also show a layout that should not have two-dimensional navigation. Up/down arrows in those examples should perform the same actions as left/right, and there should be no column navigation at all.

An actual grid should not let right/left arrows wrap to new rows, or up/down arrows wrap to new columns. Does that sound like what you would expect for keyboard behavior? Also paging @betrue-final-final in case he has more context on the UWP page :)
