### ISSUE TITLE
[FocusZone] Bidirectional: U/D Arrow key navigation bug when hitting grid edge

### ISSUE THREAD

**Issue by sophieH29** [microsoft/fluentui#10145]
### Describe the issue:

When navigating UP and I reach the end of the grid, the focus moves LEFT as expected (same behavior with DOWN moving RIGHT). However, after reaching the edge of the grid and UP causes me to navigate further LEFT, behavior of the DOWN key is wrong. I do not end up one space below my current position. Instead, I end up one space down from the last valid UP movement.

### Please provide a reproduction of the issue:

Can be reproduced in calendar or other grid-like components:
https://developer.microsoft.com/en-us/fabric#/controls/web/calendar

### Steps
1. Refer to below keypad grid. Start at 8, UP UP UP (LEFT) to end up at 1. 
2. Press DOWN. Expect to land on 4. Land on 5 instead.

1 2 3
4 5 6
7 8 9
\* 0 #

#### Actual behavior:
DOWN key after series of UP keys lands focus immediately below the result of the last valid UP movement.

#### Expected behavior:
DOWN key after series of UP keys should land focus immediately below current focus.

**Comment by JasonGore** [comment]
I see the behavior you describe. This is somewhat related to #10133 and a fix should address both issues. The issue here is just different enough from #10133 that I will leave both open for resolution.

**Comment by sophieH29** [comment]
@JasonGore we use `FocusZone` for [Stardust](https://github.com/stardust-ui/react) Microsoft library. I debugged the issue and found out that left alignment is not updated in a case when pressing the UP button on the edge and focus moves to the left (same when pressing DOWN and focus moves to the right). I introduced the fix on our side in this PR https://github.com/stardust-ui/react/pull/1794
