### ISSUE TITLE
Add clear button to TextField; add "clearable" to TextField and SearchBox

### ISSUE THREAD

**Issue by ethanroday** [microsoft/fluentui#10160]
#### Describe the feature that you would like added
Two closely related requests (I can create a separate issue if desired):
1. Like `SearchBox`, it would be great if `TextField` had a clear button (that only showed up when there was text in the box). It could potentially take precedence over `iconProps` or maybe just show up to the right of the icon if it's there.
2. The clear button should be optional on `SearchBox` and `TextField`. One way to do this would just be to add a `clearable` prop to both. If true, the clear button shows. If false, it does not.

#### What component or utility would this be added to
`TextField`/`SearchBox`

#### Have you discussed this feature with our team, and if so, who
No

#### Additional context/screenshots
Similar to #662, but that conversation seems to have gone in another direction.

**Comment by JasonGore** [comment]
Regarding point 1, an `input` only has a clearable indicator when its `type` is `search`. I think in this case `TextField` is analogous to a `text` input. `SearchBox` is more analogous to an `input of `type` `search`. I think in special cases where an input with a clear button is desired, `SearchBox` should be used, or a simple composed component making use of `TextField` could add clearable.

I see you have a PR to address point 2. Thanks!

**Comment by j-te** [comment]
If devs want a simple _clearButton_ prop then it may be ok to conditionally create a component but this edges away from keeping TextField component simple. 

It's [not difficult](https://github.com/OfficeDev/office-ui-fabric-react/issues/2725#issuecomment-521959206) to add a clear button yourself using `onRenderSuffix`, maybe an example in docs would help. 

If anything should change in regard to this, it's removing the default grey background styling when using `onRenderSuffix` prop.

**Comment by JasonGore** [comment]
You should be able to control the suffix background styling via TextField's `suffix` style property.

**Comment by blachawk** [comment]
@ecraig12345 any update on this process?

**Comment by lzl124631x** [comment]
To hide the clearButton in SearchBox, you can add `styles={{ clearButton: { display: "none" } }}` to it.
