### ISSUE TITLE
Support `loading` on <Image />

### ISSUE THREAD

**Issue by richardtagger** [microsoft/fluentui#10181]
#### Describe the feature that you would like added

Google have shipped [loading](https://github.com/scott-little/lazyload) for `img` in Chrome 76. Firefox have an [open issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1542784) tracking it. 

#### What component or utility would this be added to

Image

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

https://medium.com/bbc-design-engineering/native-lazy-loading-has-arrived-c37a165d70a5

**Comment by kenotron** [comment]
Looks like this is tied to the interface from `@types/react` for their img attributes:

```ts
interface ImgHTMLAttributes<T> extends HTMLAttributes<T> {
        alt?: string;
        crossOrigin?: "anonymous" | "use-credentials" | "";
        decoding?: "async" | "auto" | "sync";
        height?: number | string;
        sizes?: string;
        src?: string;
        srcSet?: string;
        useMap?: string;
        width?: number | string;
    }
```

We will have to update the `utilities/properties.ts` it looks like. I'm leaving this note because this is not widely implemented just yet:

https://caniuse.com/#search=img%20loading

**Comment by BrendanMcK** [comment]
Any chance of reconsidering this? Support for this is currently reasonable - Chrome, Edge, Firefox, Opera - though notably not yet Safari. Still would be useful to be able to take advantage of this where available, as a form of progressive enhancement. Right now Fabric is blocking us from using this outright - should there perhaps be some general 'escape' mechanism to allow experimental properties to be passed-through as needed?

**Comment by richardtagger** [comment]
Yeah support in Chrome/Edge/FF and Safari has this feature behind a preview flag so I'd assume it's coming soon.

@micahgodbolt @kenotron happy to help here, we can probably submit a PR to support this, what do you think?

**Comment by paulgildea** [comment]
@dzearing Thoughts?

**Comment by JustSlone** [comment]
@richardtagger, @BrendanMcK  we'd be happy to take a contribution here to add support for this if you're still up to it, let us know

**Comment by hantatsang** [comment]
@JustSlone This has already been added here: https://github.com/microsoft/fluentui/pull/16609

**Comment by JustSlone** [comment]
Thanks, closing as duplicate
