### ISSUE TITLE
Segmented Control (more compact choice-group; group of buttons)

### ISSUE THREAD

**Issue by HarryGifford** [microsoft/fluentui#10275]
#### Describe the feature that you would like added

I would like a segmented button like [this in iOS](https://developer.apple.com/design/human-interface-guidelines/ios/controls/segmented-controls/) or [this](https://docs.sencha.com/extjs/6.7.0/classic/Ext.button.Segmented.html) in ExtJS.

This input is the same as a [ChoiceGroup](https://developer.microsoft.com/en-us/fabric#/controls/web/choicegroup) in terms of functionality, but the design is different. It can be substituted with a [Dropdown](https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown) but it's harder to use.

#### What component or utility would this be added to

Either a new component, or part of the ChoiceGroup.

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

Here's how we'd want to use it:
![image](https://user-images.githubusercontent.com/21968002/63731021-b1dced80-c822-11e9-9daf-c4448d0bd16a.png)
Here's an example from the American Airlines website:
![image](https://user-images.githubusercontent.com/21968002/63730804-ad640500-c821-11e9-9a49-d785c1b97f21.png)
And an example in iOS:
![image](https://user-images.githubusercontent.com/21968002/63730788-96bdae00-c821-11e9-84c5-a84eab2b4296.png)

**Comment by ecraig12345** [comment]
If anyone would like to make something like this with custom styling in the meantime, you can use this codepen as a starting point. (thanks to @micahgodbolt for an earlier version of this codepen!)
https://codepen.io/ecraig12345/pen/BaaywqL?editors=0011

**Comment by JustSlone** [comment]
Keeping this open for future consideration, but making it clear it's not currently on our [roadmap](https://github.com/microsoft/fluentui/wiki/Fluent-UI-React-Roadmap)
