### ISSUE TITLE
Merge-styles auto-rtl does not RTL-ify translate/translateX

### ISSUE THREAD

**Issue by cliffkoh** [microsoft/fluentui#10317]
### Environment Information

- **Package version(s)**: 7.28.2

### Please provide a reproduction of the bug in a codepen:

Codepen repro: https://codepen.io/pen?template=rEjZeV

#### Actual behavior:

![image](https://user-images.githubusercontent.com/1003246/63994093-2eccc900-caa8-11e9-9c7f-6c9e162218fd.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/1003246/63994085-27a5bb00-caa8-11e9-9a1c-7d6c4262357b.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)
Workaround is for users to call getRTL() manually: https://github.com/OfficeDev/office-ui-fabric-react/blob/899983a2838318f02d45ef2d92c03cb188b736bd/packages/office-ui-fabric-react/src/components/Slider/Slider.styles.ts#L182

cc @dzearing not sure if you see this as a bug or feature request

**Comment by maxwellred** [comment]
Thanks @cliffkoh I'll reach out to David in regards to this!

**Comment by dzearing** [comment]
I think this is a non trivial scenario. Lots of edge cases.

```
transform: translate(X, Y), translateX(X), rotate(12deg);
```

1. Need to handle comma delimited values;
2. Need to handle translate specially (or expand to translateX and translateY separate values.)
3. Need to handle translateX specifically
4. Need to handle rotation (I think...)
5. Need a !noflip opt out to avoid

Missing any?

**Comment by cliffkoh** [comment]
OK tagging this as a feature request for the backlog and leaving this issue here as a record.
