### ISSUE TITLE
[Icon Tool] Keyword search needs improving

### ISSUE THREAD

**Issue by carlyareeves** [microsoft/fluentui#10332]
### Describe the issue:

Attempting to search the available icon set using the Office UI Fabric Icons tool - finding that naming conventions of Friendly Name are inconsistent and not always representative of the icon (subjective). Needs much better support for keyword search of icons, not just relying on Friendly Name.

#### Actual behavior:

Icon results returned only if entered keyword is part of Friendly Name resulting in a lot of guessing and wasted time, e.g. 'file' and 'document' currently returning different icons that are very similar in appearance.

#### Expected behavior:

Icon results returned for similar terms, e.g. 'file' vs 'document'. Icons tagged with multiple variations of terms to support subjective interpretation of appearance of the icon, including abstract representations, e.g. Chart/E999 would be displayed for 'chart' or 'graph' or 'growth' keywords.

**Comment by KevinTCoughlin** [comment]
@Jahnp, do you have any plans for expanding search grammar for the icon tool as suggested above?

**Comment by Jahnp** [comment]
Thanks for the question and suggestion, @carlyareeves . We know the search behavior isn't ideal today—searching purely by friendly name and unicode is super limited, especially when the names don't match expectations!

I have some bad news and good news. The bad news is that I don't plan on adding this feature in the short term. The Fabric icons tool takes a dependency on a Microsoft-internal team and tool to generate its base font and icon name + unicode map, and adds a bunch of functionality on top of it. The team that owns that tool hasn't exposed additional tagging/names that I as a tool owner can use, and I don't have the resources to stand up this functionality myself.

However, the good news is that that team has been working hard on a new icons tool that has *much* better search behavior—it actually uses ML to refine the search behavior—and I'm partnering with them to either
1. Bring the key Fabric-specific functionality of the Fabric icons tool to their new tool when it goes public (it's internal-only right now), or 
2. Incorporate features from their tool into the Fabric icons tool

I'm actually meeting with that team today, and though I may not have immediate news to share, I *definitely* want to see this happen. Stay tuned.
