### ISSUE TITLE
Feature: improve documentation of onDismiss method on BasePicker

### ISSUE THREAD

**Issue by kharenzze** [microsoft/fluentui#10340]
#### Describe the feature that you would like added

Improve documentation of onDismiss on BasePicker, or change method's signature

#### What component or utility would this be added to

BasePicker

#### Additional context/screenshots

Inside IBasePickerProps you can find this: 
```
  /**
   * A callback to override the default behavior of adding the selected suggestion on dismiss.
   */
  onDismiss?: (ev?: any, selectedItem?: T) => void;
```

I found that if you want to avoid the selection triggered by this method, you need to modify the 'selectedItem' arg this way: 

```
  const onDismiss = (evt, selectedItem) => {
    if (selectedItem) {
      selectedItem.key = ''
      selectedItem.name = ''
    }
  }
```

I think this is not consistent with other methods in the same file. For instance, to achieve the same behaviour on `onItemSelected`, you just need to return null. 

I suggest 2 different solutions:
* Allow returning null on `onDismiss` method.
* Advise that you need to mutate the 'selectedItem' parameter.

In my opinion, I would go for the first one if it's possible. 

prioritymatrix.com
Appfluence Inc

**Comment by KevinTCoughlin** [comment]
I'd like to get @joschect's opinion on the above API requests once he returns from OOF just in case there is an alternative way to achieve the desired outcome.

**Comment by kharenzze** [comment]
Any news here?

**Comment by joschect** [comment]
@kharenzze Thanks for bumping this! The best way to do this currently is to call prevent default on the event that's passed into the callback. Here's a [codepen](https://codepen.io/slimemold/pen/LYpGBqP?editors=0010) where you can see that working.

**Comment by kharenzze** [comment]
Thanks @joschect ! This looks cleaner compared to my workaround

[prioritymatrix.com](prioritymatrix.com)
Appfluence Inc
