### ISSUE TITLE
The Announced component is not working

### ISSUE THREAD

**Issue by flyingbee2012** [microsoft/fluentui#10348]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

Browser: Chrome, Version 76.0.3809.132

Edition: Windows 10 Home (Windows 10 Enterprise with the same Version and OS build not working as well)
Version: 1903
OS build: 18362.295

### Describe the issue:
The sample code on your official website (https://developer.microsoft.com/en-us/fabric#/controls/web/announced/quickactions) is not working. Narrator doesn't read "Item deleted" when I delete a message.

#### Actual behavior:
Narrator doesn't read "Item deleted" when a message is deleted from the dropdown

#### Expected behavior:
Narrator should read "Item deleted" when a message is deleted from the dropdown

### If applicable, please provide a codepen repro:
https://developer.microsoft.com/en-us/fabric#/controls/web/announced/quickactions

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)
High
Products/sites affected: (if applicable)
OWA

**Comment by KevinTCoughlin** [comment]
@flyingbee2012, what browser did you report with version `76.0.3809.132`? cc: @natalieethell

**Comment by flyingbee2012** [comment]
> @flyingbee2012, what browser did you report with version `76.0.3809.132`? cc: @natalieethell

It is Chrome, I updated the issue as well.

**Comment by natalieethell** [comment]
Hey @flyingbee2012 - unfortunately, Narrator + Chrome is not a combination that works very reliably. I would recommend sticking to NVDA or JAWS to get read-out on Chrome and Windows 10 Narrator on Edge. 

Regarding the new Chromium-based Edge, there should be a special UIA (UI Automation) implementation. The Narrator/Edge team did some extra work there to ensure that Narrator works properly with the browser.

We had someone open a similar issue for Narrator + Chrome, where I describe what I said above in slightly more detail. The thread is here if you're curious: https://github.com/OfficeDev/office-ui-fabric-react/issues/9055. 

Let me know if that answers your question.

**Comment by flyingbee2012** [comment]
@natalieethell I used Edge and it has been verified that it is working now. Moreover, I am wondering if the Announced component only works when there is a change? I noticed in the example code of the “Quick action” that the announced is set to undefined after 2000 ms in the componentDidUpdate, and if I removed this, the Narrator won't read. In the "Search Results" example, if I modify the method _renderAnnounced to have it always return Announced component with the same message, the Narrator won't read either. So I am wondering if there is a way for us to have this component update itself automatically so that it can still work no matter if there is a change on its state?

**Comment by natalieethell** [comment]
@flyingbee2012 Great! Yes, Narrator will only read out the same `aria-live` region again if the text has changed. However, I can see the appeal of not having to reset the Announced element on your own. Let me chat with the team about this and I'll get back to you!

**Comment by martellaj** [comment]
@natalieethell Hi! Are you creating an issue or taking on the work to modify the component so it'll read messages that are the same? I'm doing this locally in our app (OWA), but it really should be done in the component so I came here to make an issue.

**Comment by martellaj** [comment]
@natalieethell Any update?
