### ISSUE TITLE
Performance: ShimmerDetailList.base.tsx always force DetailList to re-render  due to newlistProps

### ISSUE THREAD

**Issue by LiangMingChen** [microsoft/fluentui#10351]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

https://github.com/OfficeDev/office-ui-fabric-react/blob/9815afa49eee84bf4973716d20b37b97f6fc9e14/packages/office-ui-fabric-react/src/components/DetailsList/ShimmeredDetailsList.base.tsx#L67

(at line 52, regardless it is render or not, it always generate a new object.)

The problem is that since newListProps is always a new object (even though it is always 
{
 className: undefined
}
which trigger DetailList to regenerate the _adjustColumns thus force it to rerender.

![image](https://user-images.githubusercontent.com/3789716/64229160-da598d00-ce9d-11e9-8809-7ca3566a3154.png)

#### Expected behavior:

ShimmerDetailList should memoizeOne base on the className

https://github.com/OfficeDev/office-ui-fabric-react/blob/9815afa49eee84bf4973716d20b37b97f6fc9e14/packages/office-ui-fabric-react/src/components/DetailsList/ShimmeredDetailsList.base.tsx#L56

Rather than force DetailsList to force render thus cause DetailsListBase._adjustColumns to call and pass a new Columns array into the DetailListHeader (that force it to rerender as well ) and c

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by KevinTCoughlin** [comment]
Thanks @LiangMingChen, I'll take a look in the morning at applying your recommended fix. At a glance it seems correct and patch-able. cc: @Vitalius1
