### ISSUE TITLE
Choice column with "Checkboxes (allow multiple selections)" is unable to show entire text

### ISSUE THREAD

**Issue by alinsirbu** [microsoft/fluentui#10362]
### Environment Information

- **Package version(s)**: 
    "office-ui-fabric-core": "9.6.1-fluent2",
    "office-ui-fabric-react": "6.201.1"

- **Browser and OS versions**: Any version

### Please provide a reproduction of the bug in a codepen:

https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown 
Change one of the options to a long text, and the display only shows part of the text.
Text used : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt​"

#### Actual behavior:

Text is cut off

#### Expected behavior:

The whole text to be visible.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: SPO

**Comment by KevinTCoughlin** [comment]
@alinsirbu, can you kindly re-create this issue using our issue template so that it is more actionable?

**Comment by KevinTCoughlin** [comment]
Awaiting package version(s) and browser version(s) impacted.
