### ISSUE TITLE
Give option to remove font dependency on https://static2.sharepointonline.com/files/fabric/assets/

### ISSUE THREAD

**Issue by hustonapps** [microsoft/fluentui#10363]
#### Describe the feature that you would like added
As done with icons in a previous bug report (https://github.com/OfficeDev/office-ui-fabric-react/issues/2784) would it be possible to allow for the option to not depend on the sharepoint CDN for fonts, especially when not using any of those fonts?

#### What component or utility would this be added to
@uifabric/fonts or @uifabric/styling perhaps? Similar to:
```
import { registerIcons } from '@uifabric/styling';
```

#### Have you discussed this feature with our team, and if so, who

No discussion so far.

#### Additional context/screenshots

I love the Fabric React ecosystem and champion it for a lot of my clients. One of my clients has extensive business in China and a strict requirement that we minimize all outgoing asset requests and self-host many, if not all, of our assets. The ability to self-host and replace the icons was great. I was hoping to have this feature for fonts as well. Thank you!

![image](https://user-images.githubusercontent.com/1869516/64299098-20adfb00-cf35-11e9-868a-88e8ce7012a0.png)

**Comment by KevinTCoughlin** [comment]
@hustonapps, does the following guidance in our wiki of using a custom CDN url when calling `initializeIcons` work for you?

https://github.com/OfficeDev/office-ui-fabric-react/wiki/Using-icons#alternative-cdn-options

**Comment by hustonapps** [comment]
@KevinTCoughlin That works great for the icons and removed the sharepointonline reference but instead now points to spoprod-a.akamaihd.net and still references some fabric assets

![image](https://user-images.githubusercontent.com/1869516/64301483-7e921100-cf3c-11e9-9dfe-65268d56c12c.png)

![image](https://user-images.githubusercontent.com/1869516/64301493-8c479680-cf3c-11e9-9b1d-a0c01850e26b.png)

**Comment by ThreadPitt** [comment]
> @hustonapps, does the following guidance in our wiki of using a custom CDN url when calling `initializeIcons` work for you?
> 
> https://github.com/OfficeDev/office-ui-fabric-react/wiki/Using-icons#alternative-cdn-options

Unfortunately, that doesn't work for us ("office-ui-fabric-react": "^7.34.0").
In the network panel of Chrome, I still see it being loaded from https://static2.sharepointonline.com/....

Also, the doc doesn't state if "initializeIcons(/* optional base url */);" base url has to be a fully qualified url or if it can be a server relative url like "/content/fonts/"?

Thanks!

**Comment by chce** [comment]
We are using initialiseIcons with a server relative url with success in 7.5.0, but if we try to upgrade to the latest (7.51.0), it will load fabricmdl2icons from sharepointonline

**Comment by ecraig12345** [comment]
Reopening since this is still an issue and fairly important to resolve.

**Comment by ecraig12345** [comment]
Looked into it and we do already have some potential options to address this. I've outlined the options for customizing both text fonts and icon fonts below, and this codesandbox gives full examples. https://codesandbox.io/s/customizing-fabric-icons-and-fonts-bveg8

(@chce If you're still having the issue with relative URLs, please file a separate issue.)

### Use default text font (Segoe) from a different CDN

You can use a global variable `FabricConfig.fontBaseUrl` to set an alternative location for text fonts such as Segoe. More details on this [new wiki page](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Customizing-fonts#changing-the-cdn), but basically: `window.FabricConfig = { fontBaseUrl: 'https://your-url-here' };`

#### Caveats

- **This global MUST be set before anything is imported from Fabric!**
- #3881 tracks adding a way to do this without a global.
- The alternative location is assumed to follow the same file structure (relative to `fontBaseUrl`) as the default CDN. We don't currently have a great solution for how to set that up.

### Change the default text font

You can change the default text font using theming. In some browsers, this unfortunately may not prevent the Segoe `@font-face`s from being downloaded. More details in [this new wiki page](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Customizing-fonts#changing-the-default-text-font), but basically:

```ts
import { createTheme, Customizations } from 'office-ui-fabric-react';
const theme = createTheme({ defaultFontStyle: { fontFamily: 'Comic Sans MS' } });
Customizations.applySettings({ theme });
```

Note that this was added more recently and will not work in Fabric 5 or 6.

### Use default icon font from a different CDN

At the top level of your app, call `initializeIcons('https://your-url-here/')`. This should ideally be called before any components render, not from inside a component lifecycle. [Details here.](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Using-icons#alternative-cdn-options) 

### Use alternative icons definitions

If you want to define your own icons, you can do that by calling `registerIcons` at the top level of your app. Then if you never call `initializeIcons()`, that should prevent the icon font from being loaded. [Details here.](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Using-icons#registering-custom-icons)

### Icon font loading: caveats

If you're using the pre-bundled JS file of `office-ui-fabric-react` (for example from a CDN, or by manually including `office-ui-fabric-react/dist/office-ui-fabric-react.js`), the bundle includes a call to `initializeIcons()` with the default URL. But that setup generally isn't recommended anyway--it's good for codepen and other prototyping environments, but in a production app, you should be depending on the `office-ui-fabric-react` npm package and using webpack or another bundler to include only the parts you need with your app.

**Comment by hustonapps** [comment]
@ecraig12345 I will give your suggestions a try! Thank you!

**Comment by alex3683** [comment]
@ecraig12345 Sorry for highjacking this issue, but I think this fits the context and might help others: From where can I get the font packages in the form that office ui expects? And does it have to be a fully qualified url? Since our app can be installed on-premise at different customer sites with limited internet access, I cannot define that url in advance. We always need to deliver all assets bundled with the software.

**Comment by ecraig12345** [comment]
@alex3683 That's a good question which @Jahnp might be able to help with--is there some way we can provide a zip file for people to download with all of our font assets (in the expected structure), especially for cases where they need to ship with an on-premise app that can't use our CDNs?

**Comment by ankursmooth** [comment]
One more case: in electron application with no server and cdn, hence fontBaseUrl change method will not work, hence a way to load offline packaged fonts is also required.

**Comment by omarsourour** [comment]
@ecraig12345 
Can you help me with this issue: We need to support private deployments in our website that uses Fabric. In order to do that, any calls to fetch icons or fonts need to access private CDNs that we custom made.

For icons, its simple. You simple copy the files from `@uifabric/icons/fonts` to your CDN in build step. For fonts however, its a different story. There are many supported font files (Segoe Ui, semibold, Georgian, bold, etc.) and they all exist on the `static2.sharepointonline.com` CDN. However, I don't have a listing of these files so that I can download them to my CDN in a build step. I can't list them from my browser as well.

How do I get the list of fonts supported by Office Fabric so that I can download the files from the Fabric CDN to my custom CDN?

**Comment by alex3683** [comment]
@ecraig12345 Any news on where to get a download bundle, especially for the `@uifabric/file-type-icons`?

**Comment by ecraig12345** [comment]
Sorry for the delay here. I think it should be possible to add a zip file with all the assets as part of the regular CDN deployment, but that may take some time to set up (especially with people being out for the holidays).

In the meantime, here's a zip file with the latest version of all the assets: 
https://fabricweb.blob.core.windows.net/fabric/assets_20201117.001.zip

**Comment by alex3683** [comment]
Thanks a lot. That will already help us quite well.
Good idea to provide the zip file via CDN. I guess there are more people like me having the same issue with files ;-)

**Comment by JonathanTurnock** [comment]
I Have an Offline first app, I would like to not have outbound requests even attempted, I have changed the default font like so ensuring the system font is being used, likewise I've been playing with changing the font to a bundled font i.e. from npm like https://www.npmjs.com/package/typeface-questrial

My Webpack Config Gets the Icon files from `node_modules` which works a treat.

```typescript
loadTheme({
  defaultFontStyle: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
    fontWeight: "regular",
  },
})

initializeIcons("static/media/")
```

But I still get outbound requests to sharepoint cdn.
![image](https://user-images.githubusercontent.com/16135506/106365347-dfd63380-632c-11eb-821e-ef163701d01f.png)

I have disabled these using a CSP
```html
...
  <meta http-equiv="Content-Security-Policy"
        content="default-src 'none';
...
            font-src 'self';
...
  >
...
```

Is there no way to outright disable the dependency on the CDN for Fonts?

**Comment by omarsourour** [comment]
In our product it is important to have the font files since I want to make sure that it looks the same on different operating systems that might not natively have Segoe installed.

What I do is run a PS1 script at build time that pulls all the font files from the Fabric CDNs into the project folder (whether it be a web app, native app, etc.) and then serve those font files from the local path that I created. That way I make no external calls to any CDNs.

**Comment by jtbandes** [comment]
I found that setting `fontBaseUrl` to an empty string `""` will prevent any fonts from being automatically loaded.
