### ISSUE TITLE
Change headerButtonProps type signature to allow setting style

### ISSUE THREAD

**Issue by brokenthorn** [microsoft/fluentui#10369]
#### Describe the feature that you would like added

I would like `PivotItem`'s `headerButtonProps` signature to add an alternative type `{[key: string]: number | string}`, effectively becoming:

```ts
headerButtonProps?: {
    [key: string]: string | number | boolean | | { [cssKey: string]: string | number };
} | undefined
```
thus allowing the styling of the header button, for example to display a `disabled` header:

```ts
{headers.map((h) => (
    <PivotItem
        key={h.key}
        headerText={h.name}
        itemKey={h.key}
        itemIcon={h.icon}
        headerButtonProps={{
            "data-order": h.order,
            "data-title": h.title,
            disabled: h.disabled,
            style: { color: h.disabled ? "grey" : "unset" }
        }}
    />
))}
```

#### What component or utility would this be added to

`PivotItem`

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

None.

**Comment by KevinTCoughlin** [comment]
If `headerButtonProps`'s extended `React.HTMLAttributes` then we'd get this for "free". I'll take a look to see how possible it is to extend the type.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/25731aaec086c61117b4bd66b38cf034453db013/types/react/index.d.ts#L1628

**Comment by brokenthorn** [comment]
Sorry, I'm new to this library. I think we need `IStyle` here, not my initial suggestion of `{ [cssKey: string]: string | number }`. Am I right?

**Comment by KevinTCoughlin** [comment]
If you are using our library's CSS-in-JS approach (which it looks like based on the example in https://github.com/OfficeDev/office-ui-fabric-react/issues/10369#issuecomment-528551776) then the type will need to be `IStyle`.

In the original example with `style` you are using React's DOM `style` type which emulates in-line styles and has a different type.

Thanks, the above was helpful. We'll see if we can expose individual styling here one way or the other.
