### ISSUE TITLE
Pickers should have `itemType`s for options lists

### ISSUE THREAD

**Issue by myokha** [microsoft/fluentui#10375]
#### Describe the feature that you would like added

I can add an `itemType` property to the `Dropdown` options which helps to categorize the list of options there.
It would be super useful if I could do the same thing with suggestions in a `Picker`.

#### What component or utility would this be added to

Pickers

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

This is the example of how I can render my Picker now
![image](https://user-images.githubusercontent.com/26174943/64419423-8c16da80-d0a5-11e9-98e9-2313feb618f9.png)

And this how **Fruits** and **Vegs** are categorized in a `Dropdown` (the feature I need):
![image](https://user-images.githubusercontent.com/26174943/64419929-a7ceb080-d0a6-11e9-866f-317ed1353bba.png)

**Comment by KevinTCoughlin** [comment]
Interesting, the request seems more than reasonable. However, it might require someone more familiar with the Picker code to implement well cc: @joschect for his expertise.

**Comment by joschect** [comment]
@KevinTCoughlin and @dzearing This can be done already by extending the base picker. However it makes sense that more people would want to use it. I won't add it to the basepickers capabilities but I'll extend it again and have a new composite component that allows consumers to have a menu like that.

**Comment by JustSlone** [comment]
Keeping this open for future consideration. However Picker work is not currently on our [roadmap](https://github.com/microsoft/fluentui/wiki/Fluent-UI-React-Roadmap) so it may be some time before we get to this:
