### ISSUE TITLE
Narrator does not announce the multiselected options of dropdown

### ISSUE THREAD

**Issue by irinatarn** [microsoft/fluentui#10400]
### Environment Information

- 7.31.1: (fill this out)
- Edge, Chrome: (fill this out if relevant)

### Describe the issue:

Go to the office fabric page with dropdown examples.
Start Narrator.
Start tabbing with your keyboard till you find the example with multi-select Dropdown.
See what is announced by the Narrator - it announces the label of it but not the preselected options.

#### Actual behavior:
Go to the office fabric page with dropdown examples.
Start Narrator.
Start tabbing with your keyboard till you find the example with multi-select Dropdown.
See what is announced by the Narrator - it announces the label of it but not the preselected options.

#### Expected behavior:

I expect the Narrator to say which items are selected.

**Comment by natalieethell** [comment]
Thanks for reporting this, @irinatarn! I'm able to repro what you're seeing and agree that something more should be read out for multi-select dropdowns. We'll investigate.
