### ISSUE TITLE
New component: Horizontal multilevel menu/nav/navbar

### ISSUE THREAD

**Issue by hamedy** [microsoft/fluentui#10416]
Wondering if there are any components for rendering a horizontal top menu with possibility of having links on root elements and a chevron button to expand submenu items. Like if Nav component had a horizontal layout option. 

If not, I wonder if there's a reason for it like if you think it's bad practice or something. We need this functionality for many of our customers and I wanted to ask here before I code something myself. 

Thanks, 
Hamed

**Comment by natalieethell** [comment]
Hey @hamedy thanks for opening an issue! We actually don't have a control like this yet, but I'll add this to the backlog to kick off a discussion.

**Comment by farzer** [comment]
awesome feature, marked

**Comment by xugao** [comment]
@hamedy - do you have a UX design for what you are looking for here? It seems to me what you needed here is `CommandBar`. An example [here](https://codepen.io/xugao/pen/XWJQqRq?editable=true)

**Comment by hamedy** [comment]
> @hamedy - do you have a UX design for what you are looking for here? It seems to me what you needed here is `CommandBar`. An example [here](https://codepen.io/xugao/pen/XWJQqRq?editable=true)

Imagine if in your CommandBar example, New was a link itself but also had submenuitems. An example would be in an Intranet top navigation, you'd have Management as a link to a overview page and then items under it which would take you to pages for different departments of Management. Right now Fabric has no component for this. You can't have a link at the top level with sub items which are also links.

**Comment by kamil7x** [comment]
It would need also something like Nav's `selectedKey`. I am trying to do top-level menu (without submenus) as CommandBar, but missing `selectedKey` creates little problems
