### ISSUE TITLE
Reexport functions / types from @uifabric/utilities in @uifabric/styling

### ISSUE THREAD

**Issue by nappy** [microsoft/fluentui#10458]
Currently I am using both `@uifabric/utilities` and `@uifabric/styling` in my imports and `package.json`, even though `@uifabric/utilities` is already a dependency of `@uifabric/styling`.

The following functions / types  in particular are not reexported in `@uifabric/styling`:

- `IStyleFunctionOrObject`
- `IStyleFunction`
- `classNamesFunction`
- `styled`

**Comment by aneeshack4** [comment]
@dzearing thoughts on reexporting these functions in styling so that only the utilities library needs to be imported?
