### ISSUE TITLE
onItemClick not invoked on split buttons

### ISSUE THREAD

**Issue by briunsilo** [microsoft/fluentui#10453]
In the SplitButton example, a generic onClick is used, which is not that useful unless you can get a reference to the item clicked.
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Button/examples/Button.Split.Example.tsx

Replacing the generic onClick with specific onItemClick handlers seems obvious, but they do not seem to get invoked when clicking the items?

const menuProps: IContextualMenuProps = {
  items: [
    {
      key: 'emailMessage',
      text: 'Email message',
      iconProps: { iconName: 'Mail' },
      onItemClick: function() {
        console.log('clicked!')
      }
    }
  ]
};

&lt;DefaultButton
        text="Standard"
        split
        menuProps={menuProps}
      /&gt;

**Comment by aneeshack4** [comment]
@briunsilo I made a Codepen with the scenario you described: https://codepen.io/aneeshack4/pen/mdbGOPr and I'm able to repro this - onItemClick doesn't get invoked when the items are clicked. In the ContextualMenu.types.ts the [documentation](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts#L160) says onItemClick should be invoked if onClick isn't passed for individual contextual menu item. Thanks for reporting this! I'll investigate further & report back.

**Comment by nbaolong48** [comment]
I'm using version 7.48.0 and the same thing happen. onItemClick doesn't get invoked at all.

**Comment by DigitalMystery** [comment]
@aneeshack4 @briunsilo  Is there currently a workaround for the above scenario?  I am encountering the same issue.

**Comment by vaibhav21791** [comment]
I am also facing the same issue.

**Comment by unowiz** [comment]
I am facing the same issue with the button in split mode.  onItemClick doesn't work and none of the examples cover the scenario where a menu item is clicked.
I find it strange that the issue reported in sep last year remains open.

**Comment by unowiz** [comment]
Hi @vaibhav21791  @nbaolong48 @briunsilo, 
 
**OnClick works!** onItemClick doesn't! See the usage below.
`const menuProps: IContextualMenuProps = {
  items: [
    {
      key: 'emailMessage',
      text: 'Email message',
      iconProps: { iconName: 'Mail' },
      onItemClick: () => {
        alert('clicked mail!'); // Doesn't work
      },
      onClick: (ev) => alert("email")  //works
    },`

**Comment by vaibhav21791** [comment]
> Hi @vaibhav21791 @nbaolong48 @briunsilo,
> 
> **OnClick works!** onItemClick doesn't! See the usage below.
> `const menuProps: IContextualMenuProps = { items: [ { key: 'emailMessage', text: 'Email message', iconProps: { iconName: 'Mail' }, onItemClick: () => { alert('clicked mail!'); // Doesn't work }, onClick: (ev) => alert("email") //works },`

Thanks, @unowiz onClick is working.
