### ISSUE TITLE
Make SwatchColorPicker properly controllable

### ISSUE THREAD

**Issue by whykushal93** [microsoft/fluentui#10516]
#### Describe the feature that you would like added
Currently, to make the `SwatchColorPicker` fully controllable we need to use a prop `isControlled`. This prop was added temporarily so that we do not introduce breaking changes. 

But when we next do a major update, we should properly fix up the `SwatchColorPicker` code so that it is consistent with how other components allow themselves to be fully controlled. 

The mechanism suggested by @ecraig12345 is to have a prop called `defaultSelectedId` which would be mutually exclusive in usage to `selectedId` prop. When the user uses the `defaultSelectedId`, we would make the component uncontrolled. Otherwise it will be fully controlled. 

#### What component or utility would this be added to
SwatchColorPicker

#### Have you discussed this feature with our team, and if so, who
Discussed the implementation with @ecraig12345. I can take up the work when we start doing work for the next upgrade.

**Comment by whykushal93** [comment]
This will be a breaking change and will need to done when moving to the next major version.

**Comment by aneeshack4** [comment]
@whykushal93 Thanks for discussing this with a team member already! I'll reassign this to you since you're planning on taking this up for the next major release.

**Comment by ecraig12345** [comment]
@czearing Here's the whole process for fixing SwatchColorPicker controlled behavior:
- [ ] Deprecate `isControlled`, with a runtime warning that you should just provide `selectedId` instead (and ignore the `isControlled` value)
- [ ] Add a prop `defaultSelectedId`
- [ ] Add a prop `onChange?: (event?: /*type*/, id?: string, color?: string)` and deprecate `onColorChanged`
  - [ ] The actual click/change handler should call both `onChange` and `onColorChanged`
- [ ] Add a runtime controlled usage warning (`useWarnings` `controlledUsage` option)
- [ ] Use the `useControllableValue` hook for proper controlled behavior (and probably call `useMemo` on the result to map from `selectedId` to `selectedIndex`)
- [ ] Document the change in the release notes:
  - If they only want to set the initial value and don't need manual updates, use `defaultSelectedId`
  - If they want to make manual updates there are 2 options:
    - Provide `selectedId` and `onChange`, and manually update `selectedId` whenever `onChange` is called
    - Provide `defaultSelectedId` and the built-in `key` prop (set to some arbitrary value). When the color must be manually updated, change `key` to re-create the component.
  - `isControlled` is now ignored, and inferred from presence of `selectedId`/`defaultSelectedId`
  - `onColorChanged` is deprecated in favor of `onChange`

**Comment by ecraig12345** [comment]
This should be fixed in version 8.
