### ISSUE TITLE
submenuIconProps has no effect for ICommandBarItemProps

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#10569]
### Environment Information

- **Package version(s)**: 7.31.0
- **Browser and OS versions**: Edge 78.0.276.2 dev

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/xinychen/pen/rNBoPWz

#### Actual behavior:
![image](https://user-images.githubusercontent.com/50703224/65405302-3d3fa380-de0e-11e9-8f11-b42ef20d5475.png)

`CommandBar.props.items` and `CommandBar.props.farItems` are of type [`ICommandBarItemProps`\[\]](https://github.com/OfficeDev/office-ui-fabric-react/blob/eea10b5d208cbde8b0fa1bf83c28b78dce60aab3/packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.types.ts#L129) (extends `IContextualMenuItem`). It has a [`submenuIconProps`](https://github.com/OfficeDev/office-ui-fabric-react/blob/eea10b5d208cbde8b0fa1bf83c28b78dce60aab3/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts#L315) property that I think can be used to customize the dropdown icon. However, it has no use on `CommandBarButton`. Instead, if I specify `menuIconProps`, which does not exist in the type defintion of `ICommandBarItemProps` but exists in `IButtonProps`, the dropdown icon is changed as expected.

Also, there seems to be an inconsistency of name-casing for "subMenu" between `IContextualMenuItem.subMenuProps` and `IContextualMenuItem.submenuIconProps`.

#### Expected behavior:
I think I should have a consistent way for customizing the dropdown icon. Either it be "menuIconProps" or "submenuIconProps", the type definition of `ICommandBarItemProps` should have this field.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: N/A

**Comment by joschect** [comment]
@chenxinyanc This is pretty confusing and we should standardize it. I think that we should move towards menuIconProps. @micahgodbolt what do you think about deprecating the contextualmenu submenuIconProps and making menuIconProps standard?

**Comment by chenxinyanc** [comment]
Ping. I would be glad to propose a PR on this, but I need a decision first 😄

**Comment by micahgodbolt** [comment]
Sorry, totally didn't comment on these. I agree that `menuIconProps` is the prop name we're most commonly using.  @chenxinyanc are you interested in writing a PR for this? Just make sure it's backwards compat.
