### ISSUE TITLE
In <GroupedList/>, a group with no items can't be selected

### ISSUE THREAD

**Issue by mshindal** [microsoft/fluentui#10635]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/mshindal/pen/NWKmpKv

#### Actual behavior:

Group with no items is not selectable

#### Expected behavior:

Group with no items is selectable

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: N/A

**Comment by joschect** [comment]
@mshindal I can see that the group with no items is not selectable. @dzearing or @micahgodbolt do you know if this is expected behavior?

**Comment by xugao** [comment]
this must be a bug. from the user experience, the un-checkable checkbox looks clickable just like any others

**Comment by joschect** [comment]
@xugao is the but that the checkbox appears? Or that it's unclickable?

**Comment by Link631** [comment]
why should an empty group be selectable? A group groups listitems. The selection of a group selects the groups listItems not the group itself. The group itself does not represent an item, it is only a logical unit around list items. Or did I miss something?
