### ISSUE TITLE
Add [propertyName: string]: any to IBreadcrumbItem

### ISSUE THREAD

**Issue by wudicheng123** [microsoft/fluentui#10631]
#### Describe the feature that you would like added

Currently IBreadcrumbItem does not have property of [propertyName: string]: any, it would be nice to have it in order to to add various aria attributes such as aria-posinset and aria-setsize otherwise all these attributes have to be inserted during run-time. 

#### What component or utility would this be added to

To make a11y easier

#### Have you discussed this feature with our team, and if so, who

no

#### Additional context/screenshots

no

**Comment by joschect** [comment]
@wudicheng123 I think that seems like reasonable idea. @jdhuntington does that seem okay to you? if so I'll make a pr to get it added.

**Comment by dan-lai** [comment]
I also need an custom property to set the autofocus for the first element.  Do you have any workaround for this issue for now?
