### ISSUE TITLE
Possible to add "data-automation-id" prop to every component?

### ISSUE THREAD

**Issue by thoo1** [microsoft/fluentui#10642]
#### Describe the feature that you would like added

Is it possible to add "data-automation-id" prop to every component? This would greatly add automated testing so we can attach data-automation-id to any ui fabric component. Currently it is only accepted on a few components.

#### What component or utility would this be added to

Every if possible :D

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Just a pain having to figure out which component I can attach this to. Our team is using office ui fabric heavily and want one single way to select components and test.

**Comment by thoo1** [comment]
I found: https://github.com/OfficeDev/office-ui-fabric-react/issues/4094, looks like it is being added on an ad hoc basis? Or is there a reason why only certain components get this prop?

**Comment by cliffkoh** [comment]
I don't think there are any concerns with this. But as far as I know, most if not all of the components should be able to take in data-* since they extend `HTMLProps`...

**Comment by micahgodbolt** [comment]
Our plan for future controls is to support data attributes on practically every part (slot) of a control. This is certainly not the case with our existing controls, and while we aren't going to manually add support to every existing control, if you find a control that is lacking that ability, it's something we can add on a case by case basis.

**Comment by thoo1** [comment]
fair enough. Also forgot about the fact that react 16 allows custom html attributes to pass through, whoops
Closing :)

**Comment by dzearing** [comment]
I had discussed with @joschect to just add a test case to conformance tests for this and fix inconsistencies.
