### ISSUE TITLE
Why there is no BaseComponentStyleProps like BaseComponent<T,S> base type?

### ISSUE THREAD

**Issue by AlokBisht** [microsoft/fluentui#10648]
Why Fabric doesn't have any BaseComponentStyleProps like BaseComponent<T,S>?

Are there any reasons why it's never created or the idea was rejected? 

What I meant was if you go through the office-ui-fabric-react components, in most types ( {ComponentName}StyleProps) the props like theme, className are common, so why not to have a base type with it that {ComponentName}StyleProps inherit from? it's this just repeating the code? wouldn't it increase the overhead of future modification in future in any basic common prop needs to be tweaked or reduced the effort if any common prop needs to be added?

**Comment by joschect** [comment]
@AlokBisht There's already React.HTMLAttributes and React.HtmlProps which both provide a good baseline for props to be inherited from. We could potentially have our own base props, but then what gets included in there? We'd likely wind up with a set somewhat similar to React.HtmlProps. 

@dzearing or @micahgodbolt Might have other opinions.

**Comment by AlokBisht** [comment]
Yes,just like React.HtmlProps is a good baseline for the component props ( though the BaseComponent introduces the IBaseProps any many of the office components are build on it, this is topic of it's own), we can have the basestyleprops in the framework.

ex.

interface IBaseStyleProps{
 theme?: ITheme;
className?: string;
.....
may be disabled?: boolean;
}

more style/animation rated props depending upon which direction fabric takes in future, but looking at the types currently theme, className props are the most commonly used props in all fabric {ComponentName}StyleProps types, so they seems good candidate to put in the base Type.

This idea can be pretty much the same for the BaseStyles type:

Interface IBaseStyle{
root: IStyle;
}

Now this can be controversial to say that everything is not going to have a root, but here I just meant root=something. If someone is using the Styles to define there must be something to style. the actual class names can be totally controlled here from the displayName props. so users shouldn't of the types shouldn't have the problem with the prop name "root" itself or it can be changed to much more subtle prop name.

**Comment by AlokBisht** [comment]
@dzearing @micahgodbolt, what are your views?
