### ISSUE TITLE
Ability to enable/disable fluent animations using theme object

### ISSUE THREAD

**Issue by cikuITreti** [microsoft/fluentui#10678]
#### Describe the feature that you would like added

We use UI Fabric components in our product and we would like to offer users an option for enabling/disabling animations as desired. Some users might find animations a bit annoying and perceive the UI as less responsive.

We currently achieve this by overriding some global style. The approach however is cumbersome and it would be best to be able to specify this when providing a custom theme. Ideally, this could just be another option in the Theme object that consumers of this library can customize as needed.

#### What component or utility would this be added to

Every components, but we are mostly targeting Callout animations.

#### Have you discussed this feature with our team, and if so, who

I briefly discussed this with Micah Godbolt and he mentioned this is something that could be taken into account for the next round of improvements around theming.

**Comment by khmakoto** [comment]
Hi @cikuITreti, thanks for filing this issue! It seems like this is a feature request around theming and some discussion needs to happen around it.

CC'ing relevant people: @micahgodbolt, @dzearing, @jdhuntington

**Comment by rodrigoaliste** [comment]
I'm particularly interested into disabling and/or customizing Panel animations.
