### ISSUE TITLE
LinkButton component that will render a link styled as a Button

### ISSUE THREAD

**Issue by iwasn** [microsoft/fluentui#10676]
#### Describe the feature that you would like added

We would like to have the option for the fabric Button component so that we can render an anchor element instead of a button element depending if we want to use the component for navigation. We have been passing a Link component as a children of the Button component, which results in an accessibility bug in which we have conflicting aria roles nesting within each other. A workaround has been to re-skin the the style of a Link element to match that of the office fabric button.

We would like a feature resembling the LinkButton component implemented by Material UI.

#### What component or utility would this be added to

Button components

**Comment by khmakoto** [comment]
Hi @iwasn, the `Button` component has an `href` prop that makes it behave like a link while still being styled as button, have you tried using this approach?

**Comment by iwasn** [comment]
Oh ok. To clarify, we actually have a dependency on React Router, so when we nest Link component from React Router we render an anchor tag inside the button, which causes the double nested aria role.

But thinking more about it, I am not sure how the button would detect passing in react router component to render a single anchor tag, without re-skinning it. I guess now I want to change the question of this thread to: Do you have any good suggestions on how do we make button component play nice with React Router?

Sorry for the confusion :)

**Comment by khmakoto** [comment]
@iwasn I've created [this codepen](https://codepen.io/khmakoto/pen/jONgOKP) as a playing ground to test things but I wanted to corroborate some things first. Does that codepen look like a good example to replicate the scenario you're facing? If that's the case, is the thing you want for the `Button` to just render the anchor tag instead of rendering it as a child? The answer to these questions will help me a lot to know what to do moving forward.

**Comment by iwasn** [comment]
Yup A link lives inside a button, so that we create a nested focus that is not ideal for accessibility. So only one anchor tag without a button gets rendered, like you said exactly. Let me know your thoughts :)

**Comment by khmakoto** [comment]
If it's only an issue with focus you could try adding `tabIndex=-1` to the `Link` and then triggering the `onClick` event programatically. I've done this in the codepen above. While not great, I can't see a way of this working any better with the link as a child of the button.

If we wanted to have the `Button` render as a `ReactRouter.Link` that would require some feature work from our side and some refactoring of `Button` code. While certainly possible to do, I don't know whether we'd do immediately or whether it'd go into the backlog. Anyway, please let me know if this helps. If you really want the scenario below we can tag this as a Feature request afterwards.

**Comment by iwasn** [comment]
We've reimplemented the css to style our React router links as Office fabric buttons, so this isn't too much of a priority. We appreciate this discussion however. Please keep this in a backlog

**Comment by khmakoto** [comment]
Perfect, thanks for understanding @iwasn, I'll add this to the backlog.
