### ISSUE TITLE
[DetailsList] Column reordering is not working on Microsoft teams tabs

### ISSUE THREAD

**Issue by hauvubhtech** [microsoft/fluentui#10685]
### Environment Information

- **Package version(s)**: 6.157.0
- **Browser and OS versions**: Chrome on Window 10

#### Actual behavior:

I created a web part by using sharepoint framework, and I used office ui fabric react as a user interface library. I created a details list in this web part and the column reorder function works when adding this webpart to sharepoint tenant. But when adding to Microsoft teams tabs as a tab, the column reorder function didn't work (the onColumnDrop or handleColumnReorder function could not be triggered). I tried to upgrade office ui fabric react to latest 6 version (6.204.4) but it still didn't work

#### Expected behavior:

Column reorder function should works when a details list is viewed on a web part that adding as a tab in Microsoft teams tabs

#### Image preview (can not dropping to change column order)

![1](https://user-images.githubusercontent.com/26866060/66023745-428ea380-e51c-11e9-9ca0-203f917a9e3d.png)

**Comment by khmakoto** [comment]
Hi @hauvubhtech, thanks for filing this issue! Unfortunately I don't know of a good way of testing things inside of a Microsoft Teams tab. Do you have any guidance that could help me repro the problem? Thanks!

**Comment by hauvubhtech** [comment]
![test-Google-Chrome-2019-10-03-09-00-58](https://user-images.githubusercontent.com/26866060/66094214-5f2ee800-e5bd-11e9-81e2-cb37bbeeb6b2.gif)
I made a gif here to discribe error, this 2 tabs get from shared web part but one worked, and one didn't.

**Comment by hauvubhtech** [comment]
I tried to debug many times and I found that on MS teams tabs, it didn't jump to handleColumnReorder function or onColumnDrop function when dragging and dropping

**Comment by KevinTCoughlin** [comment]
@hauvubhtech, it appears that some global listener is not being registered or the event is being stopped. What's the easiest way to repro this? Can you provide a sample SPFx webpart? I can talk to the team about how to install it.

**Comment by hauvubhtech** [comment]
I created a simple SPFx webpart and use a details list with column reorder function here
[detailslist.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/3684900/detailslist.zip)

**Comment by hauvubhtech** [comment]
@KevinTCoughlin Could you reproduce this on microsoft teams tabs?
