### ISSUE TITLE
Performance: why does List force layout/reflow (getBoundingClient) in componentDidMount?

### ISSUE THREAD

**Issue by LiangMingChen** [microsoft/fluentui#10787]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

Force render is know bad performance 
Paul Irish (Chrome Dev Lead) have what force render 
https://gist.github.com/paulirish/5d52fb081b3570c81e3a

Specific getBoundingClientRect()
Given Grid have a lot of Div, and should avoid that till Rendering engine have got the information on it. Then render.
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

Specifically, ComponentDidMount is call right after render() is call and React just commit the Element into the DOM.  It is the worse time to force render.

Yet, list always called at getBoundRect at ComponetDidMount.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/3789716/66611193-92034e00-eb72-11e9-922a-eca54b484f1d.png)

#### Expected behavior:

Should wait till requestAnimation or resizeObserver call back  (or alternative.)
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver
https://www.npmjs.com/package/react-resize-detector
Rather then force redner.

https://github.com/OfficeDev/office-ui-fabric-react/blob/7a766b0ccd4a5d63a88d730fd81ae87f947acf4f/packages/office-ui-fabric-react/src/components/List/List.tsx#L303

https://github.com/OfficeDev/office-ui-fabric-react/blob/7a766b0ccd4a5d63a88d730fd81ae87f947acf4f/packages/office-ui-fabric-react/src/components/List/List.tsx#L57

(Hmm, the ui doesn't allow me to attach the chrome profile data.)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
@soettl and @ThomasMichon are currently working on a new List implementation which should be much more performant, so I'm hesitant to invest much in the existing List right now. Do either of you have an idea of when the new lists will be available?

**Comment by chce** [comment]
Probably related to #8740

**Comment by brandonthomas** [comment]
@ecraig12345we any update on a new generic virtualizing list?

**Comment by ecraig12345** [comment]
Not really. The people mentioned above are still working on one and plan to contribute it back at some point once it's done, but I don't know any timelines for that.

**Comment by brandonthomas** [comment]
@soettl  and @ThomasMichon any update on the list components mentioned above?
