### ISSUE TITLE
ComboBox more sophisticated autoComplete feature

### ISSUE THREAD

**Issue by yueou1995** [microsoft/fluentui#10794]
#### Describe the feature that you would like added

I'd like to see ComboBox supporting more sophisticated autoComplete. It'd be great if I can keep ComboBox dropdown open as user is tying. Also it'd be great if ComboBox supports wildcard search / substring autoComplete.

#### What component or utility would this be added to

ComboBox

#### Have you discussed this feature with our team, and if so, who

I haven't.

#### Additional context/screenshots
I attached my custom implementation of the features I need. I hope that ComboBox can support these in the future too so that I can use ComboBox directly!

[LOCAL MRO - Release Explorer - Google Chrome 2019-10-11 11-02-41.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/3719136/LOCAL.MRO.-.Release.Explorer.-.Google.Chrome.2019-10-11.11-02-41.zip)

**Comment by ecraig12345** [comment]
I agree that these would be nice features, but it's not something we're likely to get to any time soon, especially the wildcard search. The idea of keeping the dropdown open while typing is interesting, and maybe something for @joschect to keep in mind when working on the new ComboBox (though you'd have to check with the designers and make sure that aligns with their idea of how the control should behave).

**Comment by volfpeter** [comment]
Hi,

Actually it would be nice if developers could plug their own matching / sorting logic into the combo box (something like `match-sorter` for example). This way the component wouldn't be opinionated and developers would be free and able to remain consistent throughout the application. After having a glance at the code, this version also looks easier to implement than the originally suggested solution.

Br,
Peter

**Comment by joschect** [comment]
@volfpeter I think that's a great point and a good suggestion.

**Comment by volfpeter** [comment]
@joschect Thanks. Is there a chance that this feature gets implemented in the not too distant future?

**Comment by joschect** [comment]
@volfpeter We currently don't have a lot of extra manpower to get a feature like this going. It might be a little bit. We are always open to help facilitate a pr if someone wanted to help out!

**Comment by volfpeter** [comment]
Thanks, I understand. I also don't have the spare time right now to implement the PR, but I will keep the issue in mind and give it a go if the situation changes. Thank!

**Comment by connorjohnmelnick** [comment]
Out of curiosity, is there a reason the autocomplete prop takes in a string of 'on' or 'off' instead of a boolean value?

**Comment by ecraig12345** [comment]
It's to mirror the built-in `autocomplete` attribute on `<input>` elements. https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by connorjohnmelnick** [comment]
Makes total sense, thank you!
