### ISSUE TITLE
Website: Better search result for TagPicker

### ISSUE THREAD

**Issue by xugao** [microsoft/fluentui#10801]
instead of showing this after search {tagpicker} -> select from navigation bar -> show reference
<img width="627" alt="Screen Shot 2019-10-13 at 2 30 23 PM" src="https://user-images.githubusercontent.com/1207059/66722713-0d107280-edc6-11e9-8cac-e2f242bc6b73.png">

i think it's better if the search result is the control:
![image](https://user-images.githubusercontent.com/1207059/66722720-29141400-edc6-11e9-9a8e-77c0f9be7b12.png)

**Suggestion**: break down controls/pickers to individual picker and combine reference & control to one page

**Comment by marygans** [comment]
Hi @xugao thank you for submitting this issue! This is a good point and something to keep in mind as there is current work being done to improve the current POV of the website -  @ecraig12345 and @Jahnp FYI.

**Comment by ecraig12345** [comment]
I'm reassigning this to myself because it was an issue Xu and I talked about. It's not likely to be fixed right away but I wanted an issue open for tracking.
