### ISSUE TITLE
Website nav disappears on small screens

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#10809]
On a small screen, you can access the top nav of [the website](https://developer.microsoft.com/en-us/fabric#/controls/web), but there's no way to access the more detailed section nav.

Small screen (this is just the links from the UHF top nav):
<img src="https://user-images.githubusercontent.com/5864305/66786910-dd7d6b00-ee96-11e9-8980-7a4da2639254.png" width="50%"/>

Desktop:
<img src="https://user-images.githubusercontent.com/5864305/66786887-cc345e80-ee96-11e9-9355-fb23186354fe.png" width="50%"/>

**Comment by ecraig12345** [comment]
@marygans I mainly filed this for tracking purposes, but if you and @Jahnp can think of a good way to implement it and you have time, that would be awesome.

**Comment by marygans** [comment]
Thanks for tracking this @ecraig12345! I agree this is a serious issue. At first glance, I'm thinking the chevron up/down might work as a toggle to expand the sub navigation elements, similar to the existing chevron in your screenshot. I'll further discuss with Peter on approach!
![image](https://user-images.githubusercontent.com/38991459/66850831-6d222880-ef2e-11e9-862b-c4f5d8427a28.png)

**Comment by ecraig12345** [comment]
We unfortunately don't have very direct control over the chevron menu--it's provided as part of the UHF header and link updates have to be checked into some separate repo. So as sad as it would be to add a *third* menu-opener element, we might be stuck doing that.

**Comment by ecraig12345** [comment]
Maybe we can hide their chevron menu and make our own?
