### ISSUE TITLE
Primary Button label missing in fluent theme with strong scheme

### ISSUE THREAD

**Issue by JaneyJiang** [microsoft/fluentui#10863]
### Environment Information

- **Package version(s)**: (6.207.0)
- **Browser and OS versions**: (tested in Edge/Chrome)

### Please provide a reproduction of the bug in a codepen:
It can be reproduced in https://fabricweb.azurewebsites.net/oufr/
for v6 and v7
for v6:
 choose version higher than (6.207.0) and select button, set Split Button by
Theme: fluent, Scheme: strong
![image](https://user-images.githubusercontent.com/2927081/66880765-dd947c80-eff6-11e9-8479-6daaaf399421.png)

for v7: 
  for the v7 support fluent theme, just the same step as v6.
  for the v7 not support fluent theme, set Split Button by Theme: MDL2, Scheme: strong.
![image](https://user-images.githubusercontent.com/2927081/66880768-e38a5d80-eff6-11e9-8437-972901ca0103.png)

#### Actual behavior:
We can just see the button without text in disable mode

#### Expected behavior:
We can see button and text in disable mode.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable) SPDF as the fluent flight is on.

**Comment by wemmaling** [comment]
Hi @marygans, I encountered the same issue. I'd like to know why didn't this issue continue to be fixed?
