### ISSUE TITLE
Header and footer with Picker suggestions.

### ISSUE THREAD

**Issue by onlyann** [microsoft/fluentui#10894]
#### Describe the feature that you would like added

At the moment, the suggestions footer rendering is driven by the internal state of the `BasePicker` parent component. 
While `Suggestions` exposes `resultsFooterFull ` and `resultsFooter`, it only  conditionally renders them once _Get More_ has been clicked.
As for the header, it is always rendered but only accepts a `headerText` string.

This doesn't make it possible to add a custom header and footer in a controlled manner.

Real-world examples :
- action in the footer to add a new suggestion,
- show the total number of results.

#### What component or utility would this be added to

`Suggestions` component could accept optional render props for both the header and footer. 
The header render prop could be an alternative to `headerText` while the footer render prop would
be an extra footer section that is unconditionally rendered.
Somewhat related, `searchForMore` could also have an optional render function.

#### Have you discussed this feature with our team, and if so, who
Nope.

**Comment by marygans** [comment]
Hi @onlyann thanks for submitting this feature request! Adding PM @paulgildea for visibility.

**Comment by JustSlone** [comment]
Keeping this open for future consideration, but making it clear it's not currently on our [roadmap](https://github.com/microsoft/fluentui/wiki/Fluent-UI-React-Roadmap)
