### ISSUE TITLE
DetailsList selection prop doesn't creates a new object on re render. Also, onSelectionChanged doesn't have access to latest state

### ISSUE THREAD

**Issue by shachau** [microsoft/fluentui#10912]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "^7.47.0"
- **Browser and OS versions**: (Chromium - Windows 10 Enterprise 1903)

### Please provide a reproduction of the bug in a codepen:

CodePen:  https://codepen.io/akoltz/pen/MWWjoyW?editors=1111

#### Actual behavior:

1) DetailsList selection prop onSelectionChanged() doesn't have access to latest state.
I have been using latest state in functional component using  useSelector() but looks like when onSelectionChanged() is called it uses the initial value of state when store was created, inspite the state updated multiple times.
2) DetailsList selection prop doesn't creates a new object on re render. I have shown this as example in codepen.

#### Expected behavior:

1) DetailsList selection prop onSelectionChanged() should use the latest local state value like any other object. Right now as a workaround i am using store.getState().
2)  DetailsList selection prop should create a new object every time on render.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Low)

Products/sites affected: (if applicable)

**Comment by marygans** [comment]
Hi @shachau, thanks for submitting this issue!

I spoke to @KevinTCoughlin offline and he mentioned that every time a new object is created, components dependent on it will re-render as well. He is investigating what would be the best approach for this issue and will get back to you. 

Thanks!

**Comment by faustAbc** [comment]
Any news about it?

**Comment by nightzsze** [comment]
Facing same issues now, any news?

**Comment by shachau** [comment]
I am not working on this project anymore so not sure. Closing this issue.
