### ISSUE TITLE
Toggle: Pointer styling area does not match clickable area

### ISSUE THREAD

**Issue by Oluchukwu96** [microsoft/fluentui#11098]
### Environment Information

- **Package version(s)**: 7.31.2
- **Browser and OS versions**: Chrome

### Describe the Issue
Hovering over the toggle label doesn't display a cursor pointer even tho it triggers the component when clicked.

### Please provide a reproduction of the bug in a codepen:
The issue can be reproduced on the documentation site :  https://developer.microsoft.com/en-us/fabric#/controls/web/toggle

#### Actual behavior:

Hovering over the toggle label doesn't display the cursor pointer but clicking it triggers the toggle component

#### Expected behavior:

The toggle label should either display the pointer cursor on hover or it shouldn't be clickable

**Comment by angallison** [comment]
Here's the design intent for the Toggle.

![Toggle](https://user-images.githubusercontent.com/14059817/68503280-53b38a00-0217-11ea-92b5-e3ac1bc1cd37.JPG)

- Labels shouldn't be actionable
- Focus should around the toggle and string
- The hand icon should appear for the string as well

**Comment by allenlai18** [comment]
i looked into this a bit. it seems like there is dispatchInteractiveEvent on the click event listener on the Label
![Screen Shot 2019-12-28 at 1 27 17 PM](https://user-images.githubusercontent.com/7275313/71549659-e4842780-2975-11ea-8573-2d8ec59d02f8.png)

for the focus to be around both the toggle and stateLabel. we need to add a tabIndex to the div.

**Comment by lzl124631x** [comment]
+1. If the label is also clickable (I expect this), the cursor should be a pointer for the labels as well.
