### ISSUE TITLE
Ability to open command bar menu item's context menu programmatically

### ISSUE THREAD

**Issue by sayali26** [microsoft/fluentui#11161]
#### Describe the feature that you would like added
Add ability to open command bar menu items pro-grammatically so that keyboard users can use commands using shortcut keys.

#### What component or utility would this be added to
CommandBar / CommandBarMenuItem

#### Have you discussed this feature with our team, and if so, who
Discussed on Teams channel

**Comment by kenotron** [comment]
Was there a person you were chatting with, Sayali? It would help to give more concrete API request.

**Comment by sayali26** [comment]
I think Micah Godbolt had a comment that this feature does not exist and its something he had thougth about. I had only put a question on the Teams React Channel which lot of people are part of :)

**Comment by kenotron** [comment]
Found it! there's a discussion on 10/7 about shortcut keys opening the commandbar items...
