### ISSUE TITLE
ComboBox text value not displaying while ComboBox menu is open

### ISSUE THREAD

**Issue by Lachlan24** [microsoft/fluentui#11169]
#### Actual behavior:
If a ComboBox is selected by a user and multiselect = true, the ComboBox opens its menu as expected, although the ComboBox text becomes either "" or the current value of the placeholder text

#### Expected behavior:
I would assume the correct expected behaviour would be for the ComboBox text value to remain the same regardless of whether the ComboBox menu is open.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by kenotron** [comment]
This is a small feature, and I have a PR - but I want to have someone who owns this component review this as well as creating a good example / test for this before merging!

**Comment by kenotron** [comment]
@joschect - FYI... it seems your'e already marked codeowner so you're on the PR reviewers list :)

**Comment by kenotron** [comment]
@joschect - can you speak to whether this is the correct behavior?

**Comment by joschect** [comment]
@kenotron and @Lachlan24 This is intentional. The combobox clears out the multiple selections so that you can type and select another one. There would need to be some changes made to the way that multiple selections are displayed to enable this change. It's definitely a feature.

**Comment by JustSlone** [comment]
Looks like this is by design, and an old issue, if there is a good reason to change the design here feel free to reopen this issue with more info
