### ISSUE TITLE
scrollSelectedToTop={true} not working in virtualized combobox

### ISSUE THREAD

**Issue by lzl124631x** [microsoft/fluentui#11214]
### Environment Information

- **Package version(s)**: 7.61.0
- **Browser and OS versions**: Chrome Version 78.0.3904.97 (Official Build) (64-bit) + Windows 10

#### Actual behavior:

https://codepen.io/lzl124631x/pen/ZEEqZjm?editors=0010

When clicking the comboxBox, the selected item doesn't appear at the top with `scrollSelectedToTop={true}`

#### Expected behavior:

When clicking the comboxBox, the selected item should appear at the top with `scrollSelectedToTop={true}`

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
This feature works in the non virtualized Combobox. @abettadapur did the virtualized variant. Alex, do you know if scrollSelectedToTop is possible to support with a virtualized combobox? Is this an issue you can take over?
