### ISSUE TITLE
Add TagItem to documentation

### ISSUE THREAD

**Issue by eszychli** [microsoft/fluentui#11234]
#### Describe the feature that you would like added

Please document "TagItem" as a standalone component (currently supported only as a part of a picker under "Pickers"). Exists in the code, just not visible.

#### What component or utility would this be added to

Items & Lists

#### Have you discussed this feature with our team, and if so, who

Not before this time

#### Additional context/screenshots
![image](https://user-images.githubusercontent.com/52629249/69007883-772fb080-094c-11ea-8211-3bca581415cf.png)

https://codepen.io/eszychli/pen/zYYyxzL?editors=0010
![image](https://user-images.githubusercontent.com/52629249/69007908-d097df80-094c-11ea-8980-823600633e7c.png)

Thank you,
Eshchar

**Comment by aneeshack4** [comment]
I see that TagItem does seem to be a standalone component in code @joschect is there any reason we don't have separate documentation for it?
