### ISSUE TITLE
Theming functions needs to be resilient across versions

### ISSUE THREAD

**Issue by phkuo** [microsoft/fluentui#11289]
We've historically had this issue come up several times now.

First example:

- The page is running Fabric v7.
- A component on the page loads Fabric v5.
- The component calls loadTheme(), creating a v5-style pre-Fluent theme without the `effects` prop.
- v7 components on the page break because they can't find `effects`.

Second example:

- The page is running Fabric v7.
- A component on the page incorrectly loads a copy of Fabric v7.
- The page sets the theme via `loadTheme()`.
- The component calls `getTheme()` but gets the wrong theme, because it's calling into a different copy of theming than the page.

While both of these are slightly in the realm of "stop doing that", Fabric should still be resilient against it, and can throw a console warning if it detects these issues.

Suggested fix: Add a version number to theme.ts. When the file loads, if the version number is the highest, register the functions to the global context. Instead of e.g. `loadTheme()` calling the code directly, it calls the version that is registered to the global context. If a second registration is detected, log a console warning.
This would need to be backported to several major versions of Fabric.

This would have been nice to have 2 years ago. Now we're just trying to find a workaround for Example 1.

**Comment by KevinTCoughlin** [comment]
Related to Fabric supporting multiple instances https://github.com/OfficeDev/office-ui-fabric-react/issues/11266

**Comment by aneeshack4** [comment]
I recently checked in a change adding [`applyTheme` and `applyThemeToBody`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Fabric/Fabric.types.ts#L9) to the `Fabric` component - can y'all try using that instead of `loadTheme`?

**Comment by aneeshack4** [comment]
I do think that doing something regarding versioning in `theme.ts` could be helpful though. @jdhuntington @dzearing what do y'all think?

**Comment by KevinTCoughlin** [comment]
I agree that Fabric's `loadTheme` needs to be resilient to calls made from other versions of Fabric on a page e.g. the SPFx WebPart scenario. If it is a documented public API, then it will get misused and should be robust.

In the meantime, we _must_ update our Theming documentation to not refer devs to the `loadTheme` function:

![image](https://user-images.githubusercontent.com/706967/69585747-6d81fa80-0f95-11ea-869c-d2aaffc9c9cd.png)

https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/index.html

The majority of developers visit the above page looking for a theme snippet to paste into their code. Some of whom are SPFx developers. Copy and pasting the above code into their WebPart can result in run-time exceptions thrown in SPO.

cc: @patmill @aditima

**Comment by phkuo** [comment]
This is not fixed yet, theming APIs still need to be made resilient across multiple Fabric versions.
