### ISSUE TITLE
ISelection doesn't append newly selected items to end

### ISSUE THREAD

**Issue by isabelacmor** [microsoft/fluentui#11398]
### Environment Information

- **Package version(s)**: 7.64.1

#### Description:

I'm using Selection with DetailsList, with multi-select enabled. When I click a row to select it, that object gets added to the Selection array in the order it appears in my DetailsList.

For example, if I have a DetailsList with the data `Item A, Item B, Item C` and I select `ItemA`, then `Item C`, then `Item B`, I would expect my `this.selectedDataItems.getSelection()` to be `Item A, Item C, Item B`. However, the selection data is actually `Item A, Item B, Item C`. Each selected item is added to the selection data list in the same order it appears in the DetailsList, rather than in the order it's selected in.

It's useful to capture information about what order data is selected in, especially in the case of multi-select, and I would expect Selection to work in that way. I was surprised to see it wasn't after spending time digging into why my selected items weren't being listed in order.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

**Comment by micahgodbolt** [comment]
Is it possible to repro this in a codepen? It would help us triage and ensure that we've solved this issue. You can create a DetailsList Codepen by clicking 'export to codepen' from the Details List page: https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist

**Comment by joschect** [comment]
@isabelacmor Thanks for submitting this. I believe that the decision was made to do things this way because implementing select for large lists is easier when using a map. It's currently working as intended. It might be helpful if we clarified in the docs the way in which this selection works to help reduce confusion. 

In the meantime you could pass your own selection that manages selection state for you. I know that's not ideal, so here is a [codpen](https://codepen.io/slimemold/pen/dyPMzbN?editors=1010) with a modified selection class that does return an array of items in selected order to help out.

**Comment by isabelacmor** [comment]
Thanks for this! I was able to get this working with your Codepen except for toggling select/unselect all. In that case, `this._selection.getSelection()` is an empty array, although I do see that `_updateCount` shows the correct length (of all the items or zero items). Then if I'm in the state where all items were selected through `toggleAllSelected` and click an item to unselect it, it gets added to `this._selection.getSelection()`. 

I'm trying to debug this locally while also comparing it to the [original class](https://github.com/OfficeDev/office-ui-fabric-react/blob/495d5291eed73e6578a8b62129b032bed61fc9b3/packages/utilities/src/selection/Selection.ts), but if you have an idea (maybe you're able to spot it quicker than I am), I'd love to hear it :)

Thanks again - I appreciate your help and do think that calling this out in the docs would help with any confusion.

**Comment by joschect** [comment]
Yeah, you'd have to make sure that either props are changed when going into the details list, or call force update. 

I'll add this to the backlog to update the docs!
