### ISSUE TITLE
Exclude example code and Markdown files from published office-ui-fabric-react tarball

### ISSUE THREAD

**Issue by KevinTCoughlin** [microsoft/fluentui#11421]
Raising an issue to track after discussing this ask internally with @ecraig12345 and @dzearing.

Currently, the `office-ui-fabric-react` tarball published to NPM includes example code and Markdown files per component per module type output, see:

![image](https://user-images.githubusercontent.com/706967/70572057-dfd90a00-1b53-11ea-898d-edec088ed07b.png)

By removing the above, the size of `office-ui-fabric-react`'s tarball would reduce by a non-negligible amount (MBs). This would improve install times for developers and reduce bandwidth usage. No one should be taking a dependency on these files, so it should be safe to make in a non-major release.

SharePoint Framework and its community are interested in this improvement as we work to improve our own npm install footprint.

**Note:** @Vitalius1 mentioned that the docs build pipeline may need to be modified as part of this change to avoid breakage at https://github.com/MicrosoftDocs/oufr-dev-docs/blob/master/config/azure-pipelines/update-docs.yaml.

cc: @patmill @VesaJuvonen

**Comment by ecraig12345** [comment]
This was done at some point in the past year when we moved these things to the react-examples package.
