### ISSUE TITLE
Focus order is not updated for selected tab in PivotItem when you reset selectedKey through programming

### ISSUE THREAD

**Issue by HarkeshS** [microsoft/fluentui#11427]
### Environment Information
"react": "16.8.6",
"react-dom": "16.8.6",
OS: Win 10
Browser:  Edge/Chrome

### Describe the issue:

Focus order is not updated for selected tab in PivotItem when you reset selectedKey through programming. 
When you change selectedKey through any action then pivotItem is selected as per selectedKey value but tab order remains unchanged. So it will create problem when you navigate through keyboard.

### Please provide a reproduction of the issue in a codepen:
Code pen link for repro
https://codepen.io/Harkesh/pen/NWPNyNP?&editable=true

#### Actual behavior:

Focus order is not updated for selected tab in PivotItem when you reset selectedKey through programming. 

#### Expected behavior:

Focus order should also updated for selected tab in PivotItem when you reset selectedKey through programming.

**Comment by joschect** [comment]
@HarkeshS Thanks for submitting this. Currently there is not a way to have focusZone change the "activeElement" (the element that will get focus when focus returns) without having an explicit focus call. There will need to be some discussion and design about the proper way to allow this to happen. We'll get it added to our backlog. 

@dzearing do you have any ideas?

**Comment by xugao** [comment]
@HarkeshS - i cannot repro this issue . can you check again?

**Comment by humaagarwal** [comment]
Is there any workaround for this issue?
