### ISSUE TITLE
Theme designer/createTheme doesn't generate correct error text color

### ISSUE THREAD

**Issue by HarryGifford** [microsoft/fluentui#11420]
### Environment Information

- **Package version(s)**: `office-ui-fabric-react@7.70.0`
- **Browser and OS versions**: Any

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/hegi/pen/zYxqZmN

- Generated a theme from https://aka.ms/themedesigner. Set the following:

  | Attribute | Value |
  | ---- | ---- |
  | Primary color | `#4fb3ff` |
  | Text color | `#f8f8f8` |
  | Background color | `#2e2e2e` |
- Click "Export theme".
- Paste the theme into the codepen above.

#### Actual behavior:

`theme.semanticColors.errorText` is `#a4262c`. This `errorText` color doesn't change based on the values of the other colors. This causes the error dialog to look like:
![image](https://user-images.githubusercontent.com/21968002/70568126-20348a00-1b4c-11ea-8250-303e0b16fae5.png)

Additionally, the Theme Designer doesn't detect that `errorText` is not accessible:
![image](https://user-images.githubusercontent.com/21968002/70568832-85d54600-1b4d-11ea-82d0-3bfd1ed68623.png)

#### Expected behavior:

`createTheme` should automatically assign an accessible color to `errorText`, or at least the Theme Designer website should detect that the error color must be set manually. This can be changed manually, but it may not be obvious that it needs to be set.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: Dynamics 365

**Comment by aneeshack4** [comment]
Spoke with @joschect offline about this - `errorText` is not included in the theme designer so this isn't a theme designer bug. It could be a feature request for when we take a look at what to include in the future but as of now, it's working as intended.
