### ISSUE TITLE
classNamesFunction: Fails in jest tests

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#11450]
### Environment Information

- **Package version(s)**: 7.71.0
- **Browser and OS versions**: n/a

### Please provide a reproduction of the bug in a codepen:

I was working with @brandonthomas on an issue they were having with a jest failure and found what appears to be a bug in the Fabric utilities `classNamesFunction` and `getRTL`.

The jest error is `Cannot read property 'getAttribute' of undefined` when `classNamesFunction` is called.

The root cause appears to be in [`getRTL`](https://github.com/OfficeDev/office-ui-fabric-react/blob/2150212f54760164dd08b3781f80c3ecfad6ca14/packages/utilities/src/rtl.ts#L25)which was added in (#8036) combined with a [call to `getRTL` that was added to `classNamesFunction`](https://github.com/OfficeDev/office-ui-fabric-react/blob/2150212f54760164dd08b3781f80c3ecfad6ca14/packages/utilities/src/classNamesFunction.ts#L61)  (#10359).

Not sure what the best fix is. Fabric components themselves don't fail when using `classNamesFunction`, so it's possible that RTL is being initialized indirectly for most uses of `classNamesFunction`. The fix may be in `getRTL` or in adding missing initialization (assuming it makes sense to expect jest tests to trigger such init.) 

In any case, it probably makes sense to add some type of guard in `getRTL`, such as making sure `doc.body.getAttribute` exists.

#### Actual behavior:

`classNamesFunction` has a runtime failure in jest scenarios.

#### Expected behavior:

`classNamesFunction` should not have runtime failures in jest scenarios.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
@JasonGore  are you looking into a fix?

**Comment by JasonGore** [comment]
No, I don't think this requires codeowner expertise and the underlying code has multiple hands in it.

**Comment by brandonthomas** [comment]
Here's a quick reduction of the unit test we had that was failing. Note this is a jsx test not tsx. Our components use styled() HOC and most of the same patterns as other Fabric components. I can share that source if needed as well.

``` import * as React from 'react';
import { FeatureExplorerTitle } from './examples/FeatureExampleTitle/FeatureExplorerTitle';
import { shallow } from 'enzyme';
import { TitleColumnGridBase, validateMinMaxValues, defaultTitleColumnGridItemsWidth } from './TitleColumnGrid.base';

const classNamesStub = {
  root: 'root',
  titleColumn: 'titleColumn',
  itemGroup: 'itemGroup',
  item: 'item'
};

const title = 'title';
const first = 'first';
const second = 'second';

describe('TitleColumnGrid', () => {
  test('Puts the children into the right containers', () => {
    const wrapper = shallow(
      <TitleColumnGridBase onRenderTitle={<>{title}</>} styles={classNamesStub}>
        <>{first}</>
        <>{second}</>
      </TitleColumnGridBase>
    );

    expect(wrapper.find('.root').children()).toHaveLength(2);
    expect(wrapper.find('.titleColumn').children()).toHaveLength(1);
    expect(wrapper.find('.titleColumn').contains(title)).toBe(true);
    expect(wrapper.find('.itemGroup').children()).toHaveLength(2);

    expect(wrapper.find('.itemGroup').contains(first)).toBe(true);
    expect(wrapper.find('.itemGroup').contains(second)).toBe(true);
  });
});

```

**Comment by jdhuntington** [comment]
@brandonthomas Are you able to share a bit more code in order to generate a repro? 

I have this as a test locally which passes; not sure which part is causing the issue (or if this issue has been mitigated in the meantime).

```tsx
import * as React from 'react';
import { shallow } from 'enzyme';
import { styled, classNamesFunction } from '../src/index';

const getClassNames = classNamesFunction<{}, {}>();
const BaseComponent: React.FunctionComponent<{}> = props => {
  console.log(getClassNames(() => {}));
  return <div>hi</div>;
};

const Component = styled(BaseComponent, {});

describe('getClassNames', () => {
  it('works', () => {
    expect(() => {
      shallow(<Component />);
    }).not.toThrow();
  });
});
```
