### ISSUE TITLE
Sticky header is jumping

### ISSUE THREAD

**Issue by Kesshi** [microsoft/fluentui#11492]
### Environment Information

- **Package version(s)**: 7.73.0
- **Browser and OS versions**: Latest Edge and Firefox, Windows 10 

### Please provide a reproduction of the bug in a codepen:

DetailsList Locked Header demo:
https://developer.microsoft.com/en-us/fabric#/controls/web/scrollablepane

#### Actual behavior:

In Edge and Firefox (not in Chrome) the sticky header of ScrollablePane is jumping when you start scrolling.

![edge_sticky](https://user-images.githubusercontent.com/15049407/70974132-5c656e80-20a7-11ea-9fe3-67ab862bfa4c.gif)
 

#### Expected behavior:

Sticky header should not jump.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by micahgodbolt** [comment]
In edge it's really really subtle. Firefox is even moreso. Is this showing up in production? Curious if its noticeable or if it's just our examples.

**Comment by Kesshi** [comment]
For us its showing up in production and one of our users complained about that.

**Comment by micahgodbolt** [comment]
@leddie24 is this an issue you can look into in the new year?

**Comment by ColinKrist** [comment]
@micahgodbolt this is happening for me in Chrome too. Just tried it out on the demo page today.
