### ISSUE TITLE
File(s) upload control

### ISSUE THREAD

**Issue by chaitanyasandeep** [microsoft/fluentui#11516]
I dont see a control that can be used to upload a single file or multiple files that can be readily used in the react components.

**Comment by ecraig12345** [comment]
Something similar was requested in #2012 and #4733 but both of those times was determined to be out of scope for Fabric. I'll ask some other team members to confirm, but the answer is probably still the same. If you need a React upload control, there are various small libraries you can find on npm dedicated to that purpose.

**Comment by ecraig12345** [comment]
Discussed with the team and I'm going to leave this request open, though I can't provide any guarantees about if/when we'll get to it. 

Before implementing, we'd need further discussion to figure out specs for behavior and visuals (if any).

**Comment by pl4nty** [comment]
+1, Teams has implemented https://assignments.onenote.com/classes/{id}/assignment/{id}/resource-picker and I was looking to reuse it for consistency.
