### ISSUE TITLE
Documentation for Label `htmlFor`

### ISSUE THREAD

**Issue by LukeOwlclaw** [microsoft/fluentui#11517]
I just learned that [`Label` has a property `htmlFor`](https://github.com/OfficeDev/office-ui-fabric-react/issues/11480#event-2885588433). Where is it documented? What does it exactly do?

It is not (directly) listed on the [Label doc page](https://developer.microsoft.com/en-us/fabric#/controls/web/label). But there is the hint "Extends  React.LabelHTMLAttributes<HTMLLabelElement>", so where would I find the documentation for `LabelHTMLAttributes`? Shouldn't it be linked on the Label doc page?

Thanks!

**Comment by ecraig12345** [comment]
`htmlFor` is the [React equivalent of HTML's `for`](https://reactjs.org/docs/dom-elements.html#htmlfor). That same page has a partial list of supported native props, but it doesn't list which ones apply to which native elements.

The actual definition of `LabelHTMLAttributes` is in the [React types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/db3ff1623a6e13332198fb71d6534a70ad7e56c8/types/react/index.d.ts#L2019). In theory we could add a link to that page, but to link to the specific line containing the interface definition, we'd have to tie the link to a particular commit, which means it could be slightly wrong if your local version is earlier/later than the one the link points to. We could also link to [the top of the file at the latest version](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts), but that's less convenient for the user (they have to search within the page) and there's still the possibility of a mismatch.

The most reliable way to find the exact current definition of `LabelHTMLAttributes` is using "go to definition" in VS Code (or similar functionality in other editors), but that doesn't help on the website.

Then there's the issue that the React typings don't actually include info on what most of the props do. For that, you have to look at [MDN `<label>` docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) (or another HTML reference)--in combination with the React doc page linked above to check for any naming or behavior changes.

Given all that complexity and cross-referencing, maybe the best documentation approach would be to make a wiki page with the info I explained above, and link the React interface names on the website there?

**Comment by ecraig12345** [comment]
Closing in favor of all-up tracking issue for inherited props, #12043.
