### ISSUE TITLE
Recommendation for Customizer Wiki Update 

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#11547]
This was a blog post I wrote to help out the M365 team, hopefully others externally will find it helpful....

## Customizing global component styles with Fabric and The Customizer

If you haven't spent much time with Fabric's Styled Higher Order Component, I highly recommend you spend some time getting to know it a [little better](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Component-Styling#creating-a-styleable-component). But one of it's more nuanced features is it's ability to distribute component styles. But for quick review, the Styled HOC:

*   Grabs theme from context and injects it into our component giving us some sweet colors and fonts
*   Separates our concerns by putting styling logic in YourComponent.styles.ts and keeping business logic firmly in YourComponent.base.tsx.
*   Merges any custom, inline styles with YourComponent.styles.ts and turns it all into into css, returning it to the component.

One of the more nuanced, but HUGLEY POWERFUL, capabilities of the Styled HOC is it's ability to grab styles out of the Customizer context and apply it intelligently to the correct components. Several libraries built on Fabric use this extensively in cases where they want  their system to deviate from Fabric's for one reason or another. Sometimes it's to fix a bug that they don't want to contribute back to Fabric, sometimes it's to account for one of their themes, and sometimes it's simply because their designers want to deviate from Fabric ever so slightly.  

The linchpin in the system is the YourLibraryStyles.ts file, which is painfully simple:  

```
export const YourStyles: any = { 
  Check: { styles: CheckStyles },
  Checkbox: { styles: CheckboxStyles }, 
  ChoiceGroupOption: { styles: ChoiceGroupOptionStyles },
  MessageBar: { styles: MessageBarStyles }, 
  Panel: { styles: PanelStyles }, 
  Overlay: { styles: OverlayStyles }, 
  PrimaryButton: { styles: PrimaryButtonStyles }, 
  Spinner: { styles: SpinnerStyles } 
  // more as needed
}
  ```

The left hand side of each style is the scope name we're trying to target. Notice how every Fabric component declares their scope?

```
export const Check: React.FunctionComponent<ICheckProps> = styled<ICheckProps, ICheckStyleProps, ICheckStyles>(
  CheckBase,
  getStyles,
  undefined,
  { scope: 'Check'},
  true
);
```

This is the key that the Customizer uses to assign the right style to YourComponent. Let's look at our CheckStyles function signature real quick:

```
export const CheckStyles = (props: ICheckProps): Partial<ICheckStyles> => {
```

Oh - look at that, the Styled HOC will pass the ComponentProps into our function so we can action off that if we need to. You could also pass in ComponentStyle props if you wanted - just depends on which props you want to action on. Handy! We're also returning a `Partial<ICheckStyles>` which means we only have to tweak the style properties we want, rather than the whole object. Clean!  

We **highly** recommend you look at the base Fabric style as your starting point for what ever component you're trying to fiddle with.  

Let's look at an example really quickly. Let's say we wanted to remove the borders from Fabric's primary buttons:

```
// PrimaryButtonStyles.ts
import  {  IButtonStyles,  IButtonProps }  from  'office-ui-fabric-react';

export  const  PrimaryButtonStyles  =  (props:  IButtonProps):  Partial<IButtonStyles>  =>  {
  return  {
    root:  {
	border:  'none'
    },
    rootHovered:  {
	border:  'none'
    },
    rootPressed:  {
	border:  'none'
    },
    rootChecked:  {
	border:  'none'
    }
  };
};
```

You can consume that style a number of ways. If you want to take all the styles wholesale:

``` 
// app.tsx 
import { YourStyles} from 'YourStyles'; 

<Customizer scopedsettings="{ YourStyles}">
  // My app JSX
 <Customizer> 
  ```

Alternatively, if you just wanted to take one style at a time, you could recreate that style list object.

```
// app.tsx 
import { MessageBarStyles } from 'YourStyles/MessageBarStyles'; 

<Customizer scopedsettings="{{MessageBar: {styles: MessageBarStyles}}}">
  // My app JSX
</Customizer> 
```

This ability isn't limited to Fabric components either. It will work with any component written with the Styled Higher Order Component that assigns a scope, so feel free to roll your own. Enjoy this new found super power, but remember it comes with great responsibility. There are many subtle accessibility fixes in Fabric that you'll want to include, and every matching component within the Customizer's context will receive those styles.

**Comment by mltejera** [comment]
#5610 @JasonGore

**Comment by micahgodbolt** [comment]
Was the blog post external? Is it possible to provide a link to it from our wiki page?

**Comment by mltejera** [comment]
Regrettably it was internal only.

**Comment by xugao** [comment]
@mltejera - thank you for writing this up!!

We have [this wiki](https://github.com/microsoft/fluentui/wiki/How-to-apply-theme-to-Fluent-UI-React-components) here which describes `ThemeProvider`, which is a newly introduced component in version 8 to help with contextual theming and it's also designed to replace `Customizer` and `Fabric`. Could you give a read and let me know if you have any questions or feedback?

In general, I also agree with having better documentation. I will think a bit more on what we wrote down in #5610 and make up what's missing in our public doc.

**Comment by mltejera** [comment]
@xugao Awesome!

I'll be following up, especially with #5610. Admin-controls does make heavy use of the customizer, especially with regards to styling overrides.

Once our consumers get 'moving to 8' on their road maps, we'll dig into the new theme provider. Happy to share up any documentation we build out.

**Comment by mltejera** [comment]
Just gave the new wiki page a read through. A few topics which could be added:
- How can you extend the theme to have more semantic slots?
- How can you remap palette -> semantic slots?
- We use the customizer to apply style overrides. I imagine that process is supported/similair?

These are things we're doing with 7, and I'm happy to do the write up for that as well.

**Comment by xugao** [comment]
@mltejera, great questions!
>How can you extend the theme to have more semantic slots?
Right now `theme` prop in `ThemeProvider` is strongly typed to `PartialTheme`. But the use case you brought up here is valid, and I think we should support. I will work on that.

>How can you remap palette -> semantic slots?
Could you elaborate this one by giving me a brief example? thanks!

>We use the customizer to apply style overrides. I imagine that process is supported/similar?
Yes. The way to migrate is documented [here](https://github.com/microsoft/fluentui/blob/master/packages/react-theme-provider/README.md#how-does-this-change-other-existing-ways-of-theming-fluent-ui-components).
