### ISSUE TITLE
All properties for calendarProps in DatePicker should be optional

### ISSUE THREAD

**Issue by alex3683** [microsoft/fluentui#11600]
### Environment Information

- **Package version(s)**: office-ui-fabric-react: 7.71.0

#### Actual behavior:

When using a DatePicker and wanting to modify some items of the `calendarProps`, the `strings` property is required due to its definition in the `ICalendarProps` interface. This doesn't make sense here, since the strings are already provided to the date picker and should be used from there.

#### Expected behavior:

When providing properties of the `ICalendarProps` interface through the `calendarProps` of a DatePicker, everything should be optional and provided properties should only overwrite the defaults. So probably `calendarProps` should be defined as `Partial<ICalendarProps>`.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: none

**Comment by jdhuntington** [comment]
Thanks @alex3683 - this makes sense.
