### ISSUE TITLE
Multi-select with buttons

### ISSUE THREAD

**Issue by Anschur** [microsoft/fluentui#11602]
#### Describe the feature that you would like added

I came across this very nice article on [accessibility testing of comboboxes](https://www.24a11y.com/2019/select-your-poison-part-2/) by @smhigley . In their testing they found that having selected options as buttons above the combobox instead of using comma separated values (like in the current [Fabric combobox](https://developer.microsoft.com/en-us/fabric#/controls/web/combobox#ComboBox1260-label)) worked better. Is this pattern something that could be considered used for the Fabric combobox?

#### What component or utility would this be added to

Combobox

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/38563783/71722857-c7929d00-2e2a-11ea-8abf-ab992e05a3cb.png)

**Comment by jdhuntington** [comment]
This is a good suggestion. I will mark this as a feature request for now, and will make sure that it is brought up in planning for iterations to the combobox control.

@joschect - do you know if this is a design that has been considered previously?

**Comment by cliffkoh** [comment]
It's funny that the comma version is more standard, but I don't think it makes for great UI :| At the same time, if you do that, what purpose does the combobox really serve? (i.e. could we just remove everything related to the dropdown?)

**Comment by joschect** [comment]
@jdhuntington Yes, there are plans to redo the combobox in a manner more similar to this when the rewrite occurs. Realistically it's a combination of two separate controls. 1. The combobox, which handles selecting an item from a list, and 2. The already selected items list where the selected items from 1 are placed.

**Comment by smhigley** [comment]
I'm happy to help with this, or share more specifics of the usability study around the multiselect interactions, if either would be helpful :)
