### ISSUE TITLE
Indeterminate state for combobox with multiselect check boxes not supported

### ISSUE THREAD

**Issue by chsach2050** [microsoft/fluentui#11640]
### Environment Information

- **Package version(s)**: 6.x
- **Browser and OS versions**: Chrome/Edge/Firefox on Windows

### Please provide a reproduction of the bug in a codepen:
If multiselect combobox is being used  and for instance we are implementing the "select all" options, where in "select all" must go to indeterminate state if no. of options selected at any point in time if != all options or 0.

#### Actual behavior:
checkbox checked and unchecked is only available. No way to reach the indeterminate state of this check box.

#### Expected behavior:
Indeterminate state must be reflected on UI per scenario basis.

### Priorities and help requested:

Are you willing to submit a PR to fix? NO
Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by xugao** [comment]
@chsach2050 - i don't have a short term solution for you at the moment. what you asked is related this #3726 request and you can get some context/decisions there. We are doing some work now which can eventually lead to a proper solution for this. But this work can go on quite long (something like 6+ months). May i ask if such timeline's acceptable to you?

**Comment by xugao** [comment]
the ask here is actually support checkbox to have indeterminate, so reopening this since this is not really dup.
