### ISSUE TITLE
Website: does not navigate properly to Web controls

### ISSUE THREAD

**Issue by cliffkoh** [microsoft/fluentui#11755]
### Environment Information

Website, with Chromium Edge

### Please provide a reproduction of the bug in a codepen:

1) go to https://developer.microsoft.com/en-us/fabric#/
2) click on controls (under ios)
![image](https://user-images.githubusercontent.com/1003246/72847460-74588100-3c57-11ea-9deb-55cc8fa9b9b5.png)

3) click on back
4) click on controls ( under web)
![image](https://user-images.githubusercontent.com/1003246/72847475-77ec0800-3c57-11ea-8912-7f8ec53c1477.png)

#### Actual behavior:

![image](https://user-images.githubusercontent.com/1003246/72847486-80444300-3c57-11ea-8b27-8b465b2071a2.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/1003246/72847502-89351480-3c57-11ea-8d86-62d2af33e342.png)

**Comment by ecraig12345** [comment]
This is probably due to some overcomplicated and unreliable logic in Site.tsx for determining and storing the current platform.

**Comment by ecraig12345** [comment]
Also, while this *should* work properly, I wouldn't consider it a super high priority if the investigation or fix turns out to be nontrivial--it's a pretty specific scenario which may not be particularly common, and is easily recoverable using the platform picker at the top of the left nav.
