### ISSUE TITLE
PivotItems with tooltips

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#11753]
### Environment Information

- **Package version(s)**: 7.83.2
- **Browser and OS versions**: Windows 10 version 1903, All browser combinations

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/khmakoto/pen/RwNEgRX?editors=1010

#### Actual behavior:

When you render a `PivotItem` with a `Tooltip` via `onRenderItemLink` you get the `Tooltip` on hover but not on focus because the focus goes to an outside button and not to the link.

#### Expected behavior:

Either the `Tooltip` should be rendered on the focus stop or the focus stop should be different.

**Comment by khmakoto** [comment]
@jdhuntington since you are the code owner, what do you think about this issue?

**Comment by jdhuntington** [comment]
Good question; I agree that there should be a keyboard-based way to activate the tooltip, but I don't have any creative solutions for how to implement this without a breaking change. Ultimately it feels like `onRenderItemLink` should render the whole container and not just the contents of the button.

**Comment by khmakoto** [comment]
@jdhuntington but that would also be a breaking change wouldn't it?

**Comment by jdhuntington** [comment]
Exactly; not sure how to fix this in the current release.

**Comment by khmakoto** [comment]
Moving to the backlog for now.

**Comment by Fadi2019** [comment]
was this handled? (I see that it is still opened)
if yes, was it released?

**Comment by khmakoto** [comment]
@Fadi2019 we haven't made any efforts to fix this since we can't do it at least until the next major release because of the constraints in design mentioned above.

**Comment by behowell** [comment]
We'll be considering this when we make further updates to the Pivot (Tabs) and Tooltip components. There's definitely room for improvement to make it easier to add tooltips to tab items.
