### ISSUE TITLE
Persona component tool-tip

### ISSUE THREAD

**Issue by baoduy** [microsoft/fluentui#11774]
Just a recommendation on the Tool-tip of Pesona component should allow to customize via title of the item. The _getText() only pickup if the title is not provided. So it will provide flexibility to the developer to customize the tool-tip.

**Comment by khmakoto** [comment]
Hi @baoudy, I'm not sure I understood you completely, what do you mean by the `Tooltip` being able to be customized via the title of the item?

**Comment by dospolov** [comment]
for those who are looking for disabling the tooltip:
don't use `text={text}` field, use `onRenderPrimaryText={() => text}`

**Comment by baoduy** [comment]
Hi @khmakoto 
With current logic, the Tooltip will display exactly the same with primary text. However, in some cases, I would like to display the tooltip differently. But able to customize it. So to allow to customize the Tooltip should look for the value from title property and if it is not provided then pick primary text.

**Comment by khmakoto** [comment]
I understand your request, though I'm unsure if using `title` is the best option here, I'll make a proposal in a PR as soon as I can. Thanks!

**Comment by khmakoto** [comment]
Actually, this might be something that requires help from Design in determining what the best approach to follow is. @paulgildea what do you think about this?

**Comment by shahid-mehmood** [comment]
I am a beginner level fluent UI user, can someone help me how to enable tooltip on Persona? My Persona Component does not show anything on Hover/Click.
