### ISSUE TITLE
[Website][High contrast] button styles are broken

### ISSUE THREAD

**Issue by xugao** [microsoft/fluentui#11781]
### Describe the issue:
In Edge + HC mode, button styles are broken in our doc site due to css set by the host site.

#### Repro:
1. Go to https://developer.microsoft.com/en-us/fabric#/controls/web/button
2. Here is what it looks like:
![image](https://user-images.githubusercontent.com/1207059/73032112-f630e180-3df2-11ea-9abe-c0f07e2454fe.png)

The reason this is happening is because the host site is dropping css like:
![image](https://user-images.githubusercontent.com/1207059/73032172-2bd5ca80-3df3-11ea-9485-abc023015ac1.png)

#### Actual behavior:
Turn on HC, go to https://developer.microsoft.com/en-us/fabric#/controls/web/button

#### Expected behavior:
Turn on HC, go to https://codepen.io/xugao/pen/abzXrBN?editable=true

**Comment by khmakoto** [comment]
FYI @xugao #10911.

**Comment by xugao** [comment]
Update: issue was reported and ack'ed by UHF team. here is the bug to track on their side: https://microsoft.visualstudio.com/DefaultCollection/OSGS/_workitems/edit/24744387
