### ISSUE TITLE
InvalidStateError with "time" type TextField  on Microsoft Edge and iOS safari

### ISSUE THREAD

**Issue by nbertol15** [microsoft/fluentui#11790]
### Environment Information

- **Package version(s)**:  7.73.0
- **Browser and OS versions**: Windows 10 pro with Microsoft Edge 44.18362

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/nbertol15/pen/LYEaZoq

#### Actual behavior:
 Only on Microsoft Edge, when a TextField have "time" as type, an error occurs (InvalidStateError) and the browser displays a blank page.

![image001](https://user-images.githubusercontent.com/21018355/73084894-14b7db00-3ece-11ea-9f74-a7f4e5e83e49.jpeg)
![Image002](https://user-images.githubusercontent.com/21018355/73084895-14b7db00-3ece-11ea-92c8-d5379bf95223.jpeg)
#### Expected behavior:
The Texfield with "time" type should works fine like on Chrome or Firefox

### Priorities and help requested:

Are you willing to submit a PR to fix?  No

Requested priority: Normal

Products/sites affected: it can be reproduced in https://developer.microsoft.com/en-us/fabric#/controls/web/textfield

**Comment by khmakoto** [comment]
Hi @nbertol15, thanks for filing this issue! I can reproduce the behavior described above.

I'm not entirely sure if this is because of something we're doing or if it is Edge's fault instead. Before investigating more deeply, however, @ecraig12345 do you know what is our support for non-text type inputs via the `TextField` component?

**Comment by nbertol15** [comment]
Hi, after some test I think it's more Edge fault. At the begining of our projet it works fine even on Edge but since maybe 1 or 2 weeks it's not. Probably due to an update of Edge by Windows Update ? 
But it' weird, an input with "type=time" works on Edge, and the TextField component  with "type=time" works on other browser.
