### ISSUE TITLE
Unregistering SLR icons does not work as expected

### ISSUE THREAD

**Issue by AsraniShikha** [microsoft/fluentui#11829]
### Please provide a reproduction of the bug in a codepen:

no visual repro as workarounds have been checked- in already.

#### Actual behavior:

Unregistering an icon doesn’t make sure we don’t get this unregistered definition when fetching icon of this name.(because this icon definition is cached). For dynamic menus(like cell/table styles) it is highly likely to unregister the old definition of say icon ‘Style_1’ and register a new definition under the same name ‘Style_1’ as the definition of Style_1 changed on server. Both the menus are using a workaround right now to avoid this. With the workaround, they now register icons as Style_1_0 and when replacing the icon definition, make it Style_1_1(last digit is version). Both have around 60 icons in the gallery , every time icons are to be replaced in a session we will have 60 more icons generated. This should bloat up the cache considerably.
 

#### Expected behavior:

unregistering icon should remove the definition from cache or the caching should be optional so that dynamic menu(like cell/table styles) can opt out of caching. 

### Priorities and help requested:

Are you willing to submit a PR to fix? ( No)

Requested priority: (Normal)

@ecraig12345

**Comment by khmakoto** [comment]
Hi @AsraniShikha, thanks for filing this issue! I understand that this is a valid concern.

@ecraig12345 @dzearing should we provide an opt-out option on caching so that the icons are not continuously generated and eating cache?

**Comment by ecraig12345** [comment]
Probably adding an opt-out prop on Icon would be easier, but I like the idea of having a way to clear the memoized icon cache if it's feasible. Trouble with clearing the cache is that with the current memoize approach, it would be hard to clear the cache for just a particular function, so it would probably end up having to clear the cache for *everything* memoized on the page, which would also cause a perf hit.

**Comment by AsraniShikha** [comment]
@VarshaRaoB

**Comment by dzearing** [comment]
I could use a bit more explanation; there is `unregisterIcons`, which will delete icons from the cache.

Which cache is not being cleaned up? Is the expectation that an Icon component rendering the "style_1" icon would be re-rendered with nothing if "style_1" were unregistered?

**Comment by AsraniShikha** [comment]
by cache, I meant the memoization function - getIconContent memoizing the result of GetIcon which might be stale in our case.

the expectation is that if I change definition of style_1(unregister style_1 and register again with a new definition) -  getIconContent should result in new definition and not old(memoized from the previous result of getIcon).
