### ISSUE TITLE
Icon: new Icon requests

### ISSUE THREAD

**Issue by xugao** [microsoft/fluentui#11886]
This issue is to track all new icon requests made by users:
~Project: #11371~
~Social (e.g. Facebook, LinkedIn, etc.): #10634~
- [ ] Shapes: #11478
- [ ] Edge Chromium: #11874

**Comment by LukeOwlclaw** [comment]
Another icon request:
![image](https://user-images.githubusercontent.com/2737900/74240189-b9615780-4cd9-11ea-99ce-de32ce946946.png)
For showing as sorting button a new icon `SortLinesDesc` would be useful.

**Comment by ecraig12345** [comment]
@Jahnp can confirm, but I don't think we're allowed to distribute social icons (which are mostly of other companies' products) for licensing/legal reasons. So that should probably be removed from the list.

**Comment by Jahnp** [comment]
Thanks @ecraig12345! Agreed that 10634 should be removed.

Also, @LukeOwlclaw , apologies for missing your request re: `SortLinesDesc` until just now. While #12088 addresses two of the issues above, this one won't make the cut. I'll open a request now, and hopefully it'll be available in the Fabric icons tool in a week or so.

**Comment by Jahnp** [comment]
@LukeOwlclaw , FYI `SortLinesAscending` is now available in the Fabric Icons tool:
![image](https://user-images.githubusercontent.com/307118/75715632-93005d80-5c82-11ea-8e22-81695a7af48e.png)

**Comment by joshjcarrier** [comment]
Is this the right thread to request brand new icons, e.g. a solid fill of a celebration: 🎉 , to be used in places where `LikeSolid` and `HeartFill` are also appropriate?
