### ISSUE TITLE
Request for a standard Emoji picker 

### ISSUE THREAD

**Issue by ashbadami** [microsoft/fluentui#11946]
#### Describe the feature that you would like added
Most text input need emoji picker. The most popular emoji mart seems to have lot of issues esp with edge browser. It will be very helpful to have a fabric control for emojis that ties in with the other fabric controls.

#### What component or utility would this be added to
Picker

#### Have you discussed this feature with our team, and if so, who
no

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/17021104/74474463-6a8efb80-4e5a-11ea-9245-93fcd2749fee.png)

**Comment by xugao** [comment]
@ashbadami - thanks for your suggestion! We have never received request for such control before. 
This is certainly something we won't support any time soon. I will mark this as feature request and we can revisit this whenever our team is ready to support new components.
