### ISSUE TITLE
Break up the `utilities` packages

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#11947]
# Problem

The `@uifabric/utilities` package has a ton of utilities. Some should be deprecated. Some have React dependencies, which makes them awkward to use when building other versions, and as such should be split out into their own packages.

We also don't want to break partners. We need the package to stay API compatible.
We want to separate react-specific utilities from non.

I've done an initial pass of what's been accumulated. 

Here's my breakdown about how to break up utilities into more granular packages:

# Proposed packages

`@uifabric/utilities` will export all of these in addition to deprecated utilities. This is to preserve binary compatibility.

# Utility collection packages

| Name | Content |
|-|-|
| @fluentui/react-customizations | all things customizations |
| @fluentui/browser-utilities | A set of browser utilities, rtl/language |
| @fluentui/array-utilities | 
| @fluentui/math-utilities | A set of math utilities
| @fluentui/react-utilities | A set of react utilities |
| @fluentui/object-utilities | A set of object utilities (Rectangle, merge) |
| @fluentui/keyboard-utilities | Helpers to parse key codes
| @fluentui/storage-utilities | local/session storage helpers |

# Individual utilities (Should these be split?)
|Name|Content|
|-|-| 
| @fluentui/react-delayed | DelayedRender |
| @fluentui/selection | Helpers for managing selection |
| @fluentui/append-function |
| @fluentui/autoscroll 
| @fluentui/merge-styles-classnames
| @fluentui/detection | ie11Detector, mobileDetector, osDetector |
| @fluentui/get-native-attributes | Helper to filter native attributes given an element type and prop bag |
| @fluentui/rtl-utilities |
| @fluentui/react-styled | Might be deprecated |
| @fluentui/warn-utilities | Set of utilities to warn deprecated usage

# Proposed deprecations

No direct references in current code should point to existing `@uifabric/utilities` package but instead to individual to existing utilities package.

All code which should not be used should be staged in @fluentui/deprecated-utilities

aria.ts
asAsync.ts
BaseComponent.ts - avoid BaseComponent
controlled.ts - ?
createRef.ts - use React createRef
css.ts - use classnames instead
EventGroup.ts - use 
extendComponent.ts
hoist.ts
hoistStatics.ts
safeRequestAnimationFrame.ts
safeSetTimeout.ts
scroll.ts - depends on mergestyles, eventgroup, window
setFocusVisibility.ts - can we just use which-input?
string.ts - use tilde strings for formatting

# Workitems

* Move [isFocusEnabled] selectors to [data-which-input]

**Comment by johannes-z** [comment]
@dzearing May I ask why `BaseComponent` should be avoided? (as per "BaseComponent.ts - avoid BaseComponent"). The more complex components heavily rely on `BaseComponent`, especially on `__async`, `__events` and `__disposables`.

Regarding `Customizations`: As of now, they (`mergeSettings.ts` and `Customizations.ts`) can be used without `react`. Moving them into a package `@fluentui/react-customizations` which most likely would have a react dependency is counter-productive in my opinion. Sounds to me `@fluentui/react-customizations` could be a potential package for `BaseComponent`.
