### ISSUE TITLE
CommandBarItem's onRender should have a defaultRender parameter

### ISSUE THREAD

**Issue by vzam** [microsoft/fluentui#12035]
#### Describe the feature that you would like added

I would like to have a `defaultRender` parameter for the `onRender` function of the `CommandBarItem` like many other components do. The default render is very complex and wrapping it is a real pain because most of the default functionality is lost and has to be copy-pasted from the source.

#### What component or utility would this be added to

CommandBarItem.onRender

#### Have you discussed this feature with our team, and if so, who

no

#### Additional context/screenshots

none

**Comment by khmakoto** [comment]
Hi @vzam, thanks for filing this issue! This seems like a fair ask.

@joschect @micahgodbolt what do you think about this?

**Comment by micahgodbolt** [comment]
No complaints, its just a bit complicated to add. We currently share an interface between buttons and contextual menu items, so changing the onRender means changing the ContextualMenuItem's onRender: https://github.com/OfficeDev/office-ui-fabric-react/blob/0afa4fab0b43f3449398c63862370d55f70cb760/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts#L456-L457

**Comment by vzam** [comment]
Maybe the CommandBarItem rendering is complex enough to put it in a separate component? This wouldn't force us to change that interface.

**Comment by micahgodbolt** [comment]
One reason the default render isn't super necessary is that the CommandBar button is a standalone component (not some internal render function). You should be able to import the CommandBarButton and re-render it on your own.

**Comment by joschect** [comment]
@vzam and @micahgodbolt What about using `commandBarButtonAs`? It ensures that you'll get all the props and styling and you can import and use the CommandBarButton as a default on your on per @micahgodbolt.
