### ISSUE TITLE
Grouped List: Possible to have colums for group headers ?

### ISSUE THREAD

**Issue by raj-crec** [microsoft/fluentui#12098]
Possible to add items to group-headers too ? like adding multiple columns, and then adding a radiobutton in one cell, a drop-down in another etc. !

**Comment by aneeshack4** [comment]
Hi @raj-crec, thanks for reaching out to us. Are you asking for two separate things - (1) multiple columns to GroupedList (2) multiple types of elements in the cells of the same GroupedList? 

We'll take this feature request into consideration in the future but for now, we're not adding any more things to our List offering as it's quite bloated/high coverage for lots of scenarios already.

**Comment by raj-crec** [comment]
Hi @aneeshack4 , yes you are correct. Thanks for letting me know. Is it possible to do the same in 'DetailsList' or 'Basic List' at least ?

One more thing; is it possible for the developer to remove multi-row selection in grouped list, i.e. if I select one row by clicking on the checkbox, the previously selected row remains selected. How can I remove this feature if I don't want ? Possible to remove the check box itself ?

**Comment by raj-crec** [comment]
Basically, what I needed was this. https://www.ag-grid.com/example.php. When user clicks on any cell, either a text input, or a drop-down is displayed for user to enter or select a new value.

**Comment by raj-crec** [comment]
an example grid is attached below:
![image](https://user-images.githubusercontent.com/35066704/75544688-842f6600-5a4a-11ea-91ab-01e56225e00e.png)

If user double-clicks inside the first cell in any row, a text input is displayed.
![image](https://user-images.githubusercontent.com/35066704/75544771-a628e880-5a4a-11ea-871d-6350f7601c4b.png)

If user doublec-clicks inside the 2nd cell, a drop-down is displayed.
![image](https://user-images.githubusercontent.com/35066704/75544825-bf319980-5a4a-11ea-9b73-fff5fac57de7.png)

I need a similar UI with fabric-react.

If it's not available directly, I think it should be possible to handle double-click for a cell, and then pass back a CUSTOM CONTROL ( text-box or drop-down in this case ) ?

**Comment by aneeshack4** [comment]
@raj-crec Apologies for the delay. I believe you can create your own custom columns and set that in state the same way `_buildColumns` is done here in the Custom Item Columns example: https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/customitemcolumns. For now, we don't plan on adding this as a feature but we'll be sure to consider this feature request as we iterate on DetailsList.

**Comment by raj-crec** [comment]
Hi @aneeshack4 . I am currently trying out the detailed list as you have suggested above. However, I have one issue. If I click on any row, _onItemInvoked() gets called. I can get to know which row ( item ) has been clicked, but I can't find which exact column cell has been clicked. Is it possible to know the same ? Without that, I won't be able to use the list, as I need to deal with each cell type separately.
