### ISSUE TITLE
Fluent UI button sizes values are not properly scaled

### ISSUE THREAD

**Issue by davyrwoo** [microsoft/fluentui#12167]
### Environment Information

- **Package version(s)**: 0.45.0

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluent-ui-example-cn5ib?fontsize=14&hidenavigation=1&theme=dark

#### Actual behavior:
The size prop for Button doesn't seem to properly scale the button's size.

Only the Small and Medium sizes are distinct. The scaling for Smaller and Smallest aren't properly scaled to be smaller than Small, likewise for the larger sizes

#### Expected behavior:

Sizing of buttons should be appropriately scaled from the given props

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by aneeshack4** [comment]
Hi @davyrwoo, thanks for reaching out to us! I see this repro on the examples page. Trying to figure out if this is a regression - the most recent change to this code seems to be [this one](https://github.com/microsoft/fluent-ui-react/commit/a4d68f5cf57f65f2f2151dd159768bec600667fb), will dig more to see if it regressed this behaviour.

**Comment by notandrew** [comment]
It's likely a bug in the example page that there's anything except small and default. I don't recall a spec showing anything else.

**Comment by xugao** [comment]
@jurokapsiar - looks like some v0 bugs need future triage. i'm assigning you on these

**Comment by layershifter** [comment]
As @notandrew pointed only default (i.e. `medium`) and `small` sizes are implemented. My proposal is to restrict `size` prop on `Button` to highlight this and update examples in docs.

**Comment by notandrew** [comment]
How about this:
![image](https://user-images.githubusercontent.com/6237759/104066245-f0740d80-51b5-11eb-84bb-3f8f2cf95ce2.png)
