### ISSUE TITLE
onResolveOptions callback function gets hit even when button is disabled

### ISSUE THREAD

**Issue by sushmithaGayam** [microsoft/fluentui#12173]
### Environment Information

- **Package version(s)**: offfice-ui-fabric- 7.98.3
- **Browser and OS versions**:  browser-->chrome,   OS-->windows 10 enterprise

#### Actual behavior:

codepen link: https://codepen.io/susmithagayam/pen/zYGdJGR
#### Expected behavior:
onResolveOptions shouldnt be triggered when combobox is disabled

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking)

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
Hi @sushmithaGayam, thanks for reaching out to us & providing the codepen - I see the repro. I believe we can disable this - let me look into this more and report back.
