### ISSUE TITLE
Formatting icon & link text color along with hover for specific Nav items

### ISSUE THREAD

**Issue by schemburkar** [microsoft/fluentui#12184]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@7
- **Browser and OS versions**: any
- **Component**: nav

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/shubhan/pen/NWqaWwZ?editors=1010

#### Actual behavior:
No way to style icon and link text color for a specific Nav link along with hover.
![image](https://user-images.githubusercontent.com/3159347/75895300-74a18a00-5e5b-11ea-9e32-f239c49c8ee9.png)

#### Expected behavior:
Style should be honored for hover for nav link and nav text.
It is expected that only some Nav link should be styled differently.

Any help would be appreciated.

**Comment by aneeshack4** [comment]
@schemburkar Thanks for making the codepen - I see your issue. I think the styles should be honored also - let me find out some more info and get back to you.

**Comment by aneeshack4** [comment]
@schemburkar Circling back to this - I don't see anything wrong with how iconProps are being set inside Nav's Link code: https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/Nav/Nav.base.tsx#L118. @jdhuntington Any ideas on what could be eating the `styles` given to `iconProps` in his codepen?

**Comment by schemburkar** [comment]
@aneeshack4 I agree, something is a miss. 

Also it's not just the iconprops but also the color of link text (with and without hover) when not using a custom renderer.

Do you think that should also work seamlessly?

**Comment by hemakiran214** [comment]
@aneeshack4 HI Aneesha, I wanna request you for one functionality for the same issue Schemburkar had faced, As per my requirement I need to customize the selected link/ Expanded Link in the Nav Component, If you are aware I haven't seen a prop like "linkIsSelected" like in Pivot -IPivotStyles  for customization in "Partial<INavStyles>" for expanded Navlink/Selected NavLink for Nav Component. Finally As of dead line rush I need to end up modifying "**ms-Button ms-Button--action ms-Button--command ms-Nav-link link-233**" for my own requirement. If you could include that in next stable release of Fluent UI it will be helpful.

**Comment by schemburkar** [comment]
@aneeshack4 Did some digging, found this:

![image](https://user-images.githubusercontent.com/3159347/80916939-72837b00-8d79-11ea-987f-3041772cd9c0.png)

In Nav.base.tsx files _renderNavLink method it generates the ActionButton with predefined styles.
Even additional props from INavlink are not passed in so that the styles can be overridden.

One option is to replace the ActionButton with a component passed as 'LinkAs', however thats for all Nav links at Nav component level, there is no possibility to do this conditionally for specific items.

thoughts?

**Comment by Dan86de** [comment]
Is there any way to change icon name on hover? I dont wanna render two IconButtons i wanna have one which is changing icon name on hover. Below screenshot :

![image](https://user-images.githubusercontent.com/23312063/105675380-574d3280-5ee9-11eb-9ab4-bb90f05d0189.png)

I wanna change 'Lock' icon when whole row is on hover to 'More' icon. Any ideas how to get this done?

**Comment by schemburkar** [comment]
> I wanna change 'Lock' icon when whole row is on hover to 'More' icon

@Dan86de  Your requirements seem to be unrelated to the styling issues. In any case, would something below work for you? 

https://codepen.io/shubhan/pen/WNGqZOy

```
const [icon, setIcon] = React.useState('Lock');
  const addFriendIcon :IIconProps   = { iconName: icon };  
  return ( 
    <ActionButton iconProps={addFriendIcon} onMouseOver={()=> setIcon('More')} onMouseLeave={() => setIcon('AddFriend')} allowDisabledFocus disabled={disabled} checked={checked}>
      Lock Menu
    </ActionButton>
  );
```

**Comment by Dan86de** [comment]
This one can work. Thank you.

**Comment by Dan86de** [comment]
Another stuff related to this button on hover change. Our problem is IconButton is rendered insire DetailsRow component is there any way to tell IconButton component that DetailsRow in which he is sitting is hovered?

**Comment by schemburkar** [comment]
> Another stuff related to this button on hover change. Our problem is IconButton is rendered inside DetailsRow component is there any way to tell IconButton component that DetailsRow in which he is sitting is hovered?
> 

Just set your events up on the row and set state on children components.

**Comment by Dan86de** [comment]
Yep but then whole table is triggering rerender. With a lot of data its useless...

**Comment by cabillin** [comment]
I ran into a similar issue which I think has the same root cause: https://codepen.io/KnetTravlr/pen/jOVVarQ?editors=0010

**Comment by aidanDGI** [comment]
Hi, stupid question from a mainly c++ programmer; until this is fixed, could I somehow use css !important to override the hover color for the Navitem icon? thx.
