### ISSUE TITLE
[Panel] The rest of the page jumps with the Panel opens

### ISSUE THREAD

**Issue by lynamemi** [microsoft/fluentui#12188]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)
Reproed on both Chrome and chromium Edge. I'm on a Mac. We noticed this in product then also reproed on the Fabric website.

### Please provide a reproduction of the bug in a codepen:
This is reproducible on the website: 
https://developer.microsoft.com/en-us/fabric#/controls/web/panel

#### Actual behavior:

![Panel page jump](https://user-images.githubusercontent.com/16619843/75905312-7f2b3780-5df9-11ea-829b-e965854111fd.gif)

#### Expected behavior:

I'd expect the rest of the page to stay static.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Maybe, but I don't have bandwidth to troubleshoot at the moment.

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
SharePoint

**Comment by aneeshack4** [comment]
Hi @lynamemi thanks for reporting this! I am able to repro this and I see that it's doing something similar with Modal too. Will investigate.

**Comment by lynamemi** [comment]
@aneeshack4 did you have a chance to look into this bug? Should I find a codeowner to ping?

**Comment by levymsft** [comment]
This also happens with DetailPanelV2

**Comment by levymsft** [comment]
It was not fixed @lynamemi can we re-open it?

**Comment by lynamemi** [comment]
@levymsft Yeah I still repro this, I can reopen it.
