### ISSUE TITLE
Panel: 7.98.1 regressed position of close button for panels with no header text

### ISSUE THREAD

**Issue by dbjorge** [microsoft/fluentui#12195]
## Environment Information

- **Package version(s)**: 7.98.1 is the first affected version
- **Browser and OS versions**: new Edge stable Version 80.0.361.66 (Official build) (64-bit)

### Please provide a reproduction of the bug in a codepen:

(these are just the results of exporting-to-codepen the "Basic" [panel example](https://developer.microsoft.com/en-us/fabric#/controls/web/panel), removing the headerText prop from the panel, and updating the fabric version)

* [Repro in 7.98.1](https://codepen.io/dbjorge/pen/ExjwgEp) (note the panel's close button appearing at top left instead of top right)
* [No repro in 7.98.0](https://codepen.io/dbjorge/pen/BaNwLxK) (note the panel's close button appearing in top right)

#### Actual behavior:

Panel's close button appears at the top-left, like this:
![screenshot of close button at top-left in v7.98.1](https://user-images.githubusercontent.com/376284/75931608-3fc90f00-5e2a-11ea-9d19-a7f22b9b3a98.png)

#### Expected behavior:

Panel's close button should appear at the top-right, like this:
![screenshot of close button at top-right in v7.98.0](https://user-images.githubusercontent.com/376284/75931582-33dd4d00-5e2a-11ea-957d-99416f345f24.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High (visual regression in patch release)

Products/sites affected: [Accessibility Insights for Web](https://github.com/microsoft/accessibility-insights-web)'s help content panels:

![screenshot of misplaced close button in Accessibility Insights](https://user-images.githubusercontent.com/376284/75931681-6d15bd00-5e2a-11ea-9952-b5782ea67ad8.png)

**Comment by dbjorge** [comment]
I think this regression was introduced in #12025 (fixing #12020) - the issue is that the container for the close button was updated to use `justify-content: space-between` without considering that there aren't always 2 flex items in the container

**Comment by aneeshack4** [comment]
@phkuo looks like our approach to doing `justify-content: space-between` breaks closeButton's styling when the headerText is removed...

**Comment by mltejera** [comment]
We noticed this as well, glad it's getting worked on! 👍
