### ISSUE TITLE
DetailsList Component: dragDropEvents  do not work correctly on Groups

### ISSUE THREAD

**Issue by sachinma** [microsoft/fluentui#12218]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:

Code Pen: https://codepen.io/sachinma/pen/NWqwKeM

#### Actual behavior:

Groups do not become draggable
OnDragEnter, OnDrag does not work correctly on Groups

#### Expected behavior:
They work correctly

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable) MS

**Comment by aneeshack4** [comment]
@sachinma thanks for reporting this & for opening an PR already!
