### ISSUE TITLE
There seems to be some line-height inconsistency with the checkbox label 

### ISSUE THREAD

**Issue by bansalrachita** [microsoft/fluentui#12229]
### Environment Information

- **Package version(s)**: ^0.44.0

![image](https://user-images.githubusercontent.com/10090750/76123043-7cbd0f00-5fac-11ea-85ae-7b2689824674.png)

#### Actual behavior:

My colleague Huy Cao found this issue where the label content doesn't seem to be placed correctly in the center, vertically aligned with the checkbox, in `<Checkbox>` component (no extra styles are applied) Line height seems to be the issue here.

#### Expected behavior:

The text of label should vertically center aligned with the checkbox.

https://codesandbox.io/s/fluent-ui-example-jxi4u
Requested priority: Low

**Comment by aneeshack4** [comment]
@bansalrachita it seems like this is because you set "at start" to a different size than "at end" if you set them both to the same size it's fine: 
![image](https://user-images.githubusercontent.com/4161791/76129604-58bdf580-5fcd-11ea-81da-1c4b9d84e660.png)

**Comment by bansalrachita** [comment]
@aneeshack4  It was my intention to show the use-case where different sizes of the label text show different alignment behavior. The small text is aligned in the middle while the normal text is aligned to the end of the checkbox. It should center align in both cases.

Even the image that you show above above seems misaligned. The text is not exactly aligned in the center. The checkbox should be vertically center aligned with the Capitalized letter of the text to make it appear exactly in the center but it looks like the line height assumes the size of the un-capitalized letters.

![image](https://user-images.githubusercontent.com/10090750/76134566-0fbd6f80-5fd4-11ea-8708-a3dc5ef3fe8b.png)

**Comment by jurokapsiar** [comment]
Tracking Reference: 6653

**Comment by jurokapsiar** [comment]
Fixed in https://github.com/microsoft/fluentui/pull/12590
