### ISSUE TITLE
AutomationId for auto testing is not sets

### ISSUE THREAD

**Issue by Koniksan** [microsoft/fluentui#12248]
There are properties for INavLink interface `automationId: string`  that  do nothing if we use default Office UI Fabric render method
![image](https://user-images.githubusercontent.com/15952613/76313498-19054f80-62e6-11ea-9bf7-4d2d28292ccb.png)

After some investigation in source code I saw this hard code

![image](https://user-images.githubusercontent.com/15952613/76313646-6bdf0700-62e6-11ea-9dea-4ba0d8acd031.png)

Maybe we should put there our automationId from props 
For example 
`data-automationid={this.props.automationid ? this.props.automationid : 'splitbuttonprimary'}`

Thanks !

**Comment by aneeshack4** [comment]
@Koniksan Thanks for reaching out to us. Is this a question? Or did you find a bug? It's unclear... which files are you referring to with this screenshots? I tried to find the exact ones in the screenshots but there are a lot of similar ones. Can you be very clear as to what it is you need? Which component is at question, what's the problem exactly, repro steps, codepen, etc...? Please fill out the template - that will help us be actionable.

**Comment by Koniksan** [comment]
Hello, sorry for not complete bug report
Here is my example code according to your documentation
https://codepen.io/Koniksan/pen/KKpQqYJ?editors=1010

I`m trying to add `automationId `property to link 
![image](https://user-images.githubusercontent.com/15952613/76427137-ff830700-63bc-11ea-8965-a0b144f36261.png)

and get default value in DOM tree 
![image](https://user-images.githubusercontent.com/15952613/76427255-23464d00-63bd-11ea-8989-fb9bc072f7fb.png)

I checked source code `BaseButton.tsx` and at line 299 saw this :
![image](https://user-images.githubusercontent.com/15952613/76427825-e3339a00-63bd-11ea-932d-28e728315ea2.png)
So I made an assumption that we do nothing with `automationId` property and should fix this moment for example like this 
![image](https://user-images.githubusercontent.com/15952613/76428155-589f6a80-63be-11ea-818b-7a85760d77c3.png)

1. Which Fabric component and which version of the Fabric component is causing the issue
   `<Nav />` component , Fabric version `7.90.0`

2. What behaviors and attributes are missing or incorrect
   property `automationId ` in INavLink interface

3. What you expected and what is actually happening
   Expectation: sets `data-automation` attribute for link
   Actual result: `data-automation` is sets to DOM element 

4. Confirmation that the problem reproduces in isolation
https://codepen.io/Koniksan/pen/KKpQqYJ?editors=1010

**Comment by aneeshack4** [comment]
@Koniksan Thanks for the actionable info and apologies for the delay. The only mention of these props I see in the Nav code is in a snapshot and in the types file, no where in the actual logic (base file) which makes me think this is just the default behavior - I ping'd the component owner to double check and will follow up when I hear back from them.

**Comment by aneeshack4** [comment]
@jdhuntington the component author made this to unblock you for now @Koniksan  https://codepen.io/jdh-msft/pen/mdJQrLZ?editors=0010. AutomationId needs to be deprecated though - further work on Nav is not likely to happen at the moment.

**Comment by Koniksan** [comment]
@aneeshack4  

> @jdhuntington the component author made this to unblock you for now @Koniksan https://codepen.io/jdh-msft/pen/mdJQrLZ?editors=0010. AutomationId needs to be deprecated though - further work on Nav is not likely to happen at the moment.

That`s how I`am doing it right now =) Just hoped to use default props of the component 
Any way thanks for the replying 👍
