### ISSUE TITLE
Icons set aria-label on generic role

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#12256]
### Environment Information

- **Package version(s)**: latest / 7.101
- **Browser and OS versions**: all

### Describe the issue:

The suggested way to label non-presentational icons is with `aria-label`, but that is currently applied to an `<i>` element without a role. That element maps to a generic role / no role by default, and does not support having an accessible name (https://w3c.github.io/aria/#namefromprohibited).

Image icons with an alt but no aria-label also have an issue -- they're hidden by default even with the `alt`, since `aria-hidden` is applied to its parent.

### Please provide a reproduction of the issue in a codepen:

On the demo page, add `aria-label` to any of the examples: https://fabricweb.z5.web.core.windows.net/oufr/7.101.0/#/examples/icon

#### Actual behavior:

Non-presentational icons do not expose the `img` role, and the name is not consistently announced (or supported by the ARIA spec).

ImageIcons with an `alt` are not exposed

#### Expected behavior:

Meaningful icons are exposed as graphics / `img`'s, with a name defined

### Documentation describing expected behavior

Role mapping for `<i>`: https://w3c.github.io/html-aam/#el-i
Roles supporting name from author: https://w3c.github.io/aria/#namefromauthor

My suggested fixes would be:
- adding `role="img"` to non-presentational icons (and dropping `role="presentation"`, since it does nothing when combined with `aria-hidden`)
- for image icons, dropping `aria-hidden` entirely, and relying on the image `alt` attribute

**Comment by smhigley** [comment]
Got a PR just about ready that would solve this, I'd love to hear what you think!

**Comment by betrue-final-final** [comment]
@joschect, can you take a look at @smhigley's PR?
