### ISSUE TITLE
Tooltip for <Text /> component that is truncated in Fluent-ui

### ISSUE THREAD

**Issue by bansalrachita** [microsoft/fluentui#12263]
#### Describe the feature that you would like added

Looking for a tooltip to be added on the `<Text />` component to show full text where the content string is too long and is truncated. 

The component should not expose it through a prop but hide that piece of detail from the user by showing the tooltip by-default whenever the text is set to`overflow` & `ellipsize`

#### What component or utility would this be added to

Primarily requesting it for the `<Text />` control in the fluent-ui library.

#### Have you discussed this feature with our team, and if so, who

Discussed this in meeting with @aneeshack4 

#### Additional context/screenshots

Example usage and screenshot below:

```
const TextExampleTruncatedToolTip = () => (
  <div style={{ overflow: 'hidden', textOverflow: 'ellipsis' }}>
    <Text truncated content="Some long text here that will be truncated when truncated prop is set to 
  true" />
  </div>
);
```

<img width="795" alt="Screen Shot 2020-03-11 at 1 24 39 AM" src="https://user-images.githubusercontent.com/10090750/76396808-2139ab00-6337-11ea-9983-5b6e46a95a2d.png">

**Comment by jurokapsiar** [comment]
@bansalrachita this can be achieved by wrapping the Text inside of the Tooltip, see https://codesandbox.io/s/m0fxt?module=/example.js

We are not going to add this to the Text component itself as that would have quite bad downside for our ability to tree shake. Since Text is used in a lot of components, all of them would be pulling Tooltip, popper and other utilities.

A conveniece component can be created on the partner's (your) side to wrap the Text and add the Tooltip. Please let me know if this works for you.

**Comment by bansalrachita** [comment]
@jurokapsiar 

We can just utilize the HTML element attribute `title` in the case where the text is `truncated` && `overflowing`. This would also avoid having to pull other utils like Popper.js etc.

Styling the title as per the `fluent-ui`'s theme would be good to have.

**Comment by jurokapsiar** [comment]
It is not planned to change the behavior of the `title` prop.
It is not possible to style `title`, styling can be only achieved by using Tooltip - which has drawbacks that I described in my original response.

**Comment by bansalrachita** [comment]
Apologies for not conveying properly. 

What I meant was for having a prop which enables the `title` attribute for `<Text />` component. 

I do know fluent-ui lets users pass in native HTML attributes, but enabling a title attribute via a boolean prop like `useTitle` will help the users expand the truncated text,  w/o changing the behavior of title prop and in cases where Tooltip is sort of an overkill. 

#### Sample snippet:
```
<Text useTitle truncated content="...long text" /> 
``` 

This will also avoid the tree shaking issue, as you mentioned w.r.t `Tooltip` and let users who would like to conditionally have the title based tooltip for longer text, reap its benefits.


#### Use-case
Below is my use-case where it will be helpful for me:

I have a list of E-mail IDs inside a fixed width modal. These IDs can be long and need to be shown. Using a Tooltip here is an overkill due to space and I enabled an HTML attribute `title` manually in my application to achieve the results. 

![image](https://user-images.githubusercontent.com/10090750/76710042-3d37a680-66c1-11ea-820d-2d9dcf74df54.png)


Final thoughts?

**Comment by aneeshack4** [comment]
@jurokapsiar gentle reminder - looks like the author had some follow up

**Comment by jurokapsiar** [comment]
sorry for the delay, I thought I replied to this, but it probably failed to send the comment.

I understand the use case but still think that it can be easily achieved on the consumer (your side).
The type of the `content` prop is not only string, it can accept React elements as well, which are not directly usable as `title`.

So my advice is to add `title` to the Text on your side if needed.
