### ISSUE TITLE
DatePicker value/state is cleared on re-render

### ISSUE THREAD

**Issue by teemohteekoh** [microsoft/fluentui#12276]
### Environment Information

- **Package version(s)**: 7.90.0 (reproduces on latest)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/teemohteekoh/pen/rNVJqJp

#### Actual behavior:

DatePicker elements lose their displayed value when they are re-rendered, eg. due to a state change.

#### Expected behavior:

The DatePicker should retain its value, similarly to TextField and other controls.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, if necessary

Requested priority: Normal (Not sure if this is a regression)

Products/sites affected: Internal web tool.

**Comment by aneeshack4** [comment]
I think this might be related to #7289 - seems like this has been an issue for a while & not a regression. Looks like there's a workaround described in [this comment](https://github.com/OfficeDev/office-ui-fabric-react/issues/7289#issuecomment-443876201). @lorejoh12 what do you think about this - should there be a change made to the DatePicker re-render & state logic to permanently fix this?

**Comment by teemohteekoh** [comment]
Ah, thanks very much for linking that, I had tried to do the appropriate searching for similar issues but it looks like I missed it!

Personally, I think the DatePicker should maintain its displayed value if no value is passed in, if just for ease of use (not having to maintain the value in the parent component).

**Comment by justinnp** [comment]
Currently experiencing the same behavior. 
Has there been further consideration into logic change or are there any updates on this particular issue?
