### ISSUE TITLE
Tooltip cannot be interacted with when displayed on pressed button

### ISSUE THREAD

**Issue by joshjcarrier** [microsoft/fluentui#12285]
### Environment Information

- **Package version(s)**: 7.83.0
- **Browser and OS versions**: Chrome Version 80.0.3987.132 (Official Build) (64-bit)/MacOS Mojave 10.14.6

### Please provide a reproduction of the bug in a codepen:

1. click on the [Click me first] button
    (due to mouse hover, a tooltip appears)
3. mouse over to the [Mouse over on me second] button in the tooltip
4. primary click the [Mouse over on me second] button

https://codepen.io/joshjcarrier/pen/mdJXGpK

#### Actual behavior:

The mouse click down on [Mouse over on me second?] button does not activate the button, and causes the tooltip to dismiss.

![fabric_actual](https://user-images.githubusercontent.com/526858/76555766-8a174500-6455-11ea-84e9-21b6a85df32b.gif)

#### Expected behavior:

The mouse click down on [Mouse over on me second?] button should activate the button, and prevent the tooltip from dismissing.

![fabric_expected](https://user-images.githubusercontent.com/526858/76555772-8edbf900-6455-11ea-919d-dbb9681fa4a1.gif)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: n/a

**Comment by aneeshack4** [comment]
@joshjcarrier Thanks for reaching out to us. I'm double checking with the component owner but I believe Tooltips aren't meant to have interact-able elements in them like buttons... for that perhaps use Callout: https://developer.microsoft.com/en-us/fabric#/controls/web/callout

**Comment by joshjcarrier** [comment]
Having interactive components in the tooltip exaggerates the issue, as having any content in the tooltip becomes no longer focusable.

Below, I can normally click the div to select text, but after pressing the host button the same issue repros. 
![fabric_focus](https://user-images.githubusercontent.com/526858/76581817-e6985580-6491-11ea-9e5d-3f91face4f3c.gif)

`<Callout>` may be have potential, but in supporting hover capabilities it seems like I'd eventually rebuild `<Tooltip>`, since it is also based on `<Callout>`:

[office-ui-fabric-react/packages/office-ui-fabric-react/src/components/Tooltip/Tooltip.base.tsx](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Tooltip/Tooltip.base.tsx#L49)
```ts
return (
      <Callout
```

**Comment by joshjcarrier** [comment]
I think I've found a solution to this issue, by preventing mouse down event propagation on any clicks occurring in the tooltip content container. 

https://codepen.io/joshjcarrier/pen/eYNrbWo
