### ISSUE TITLE
No visible focus when button programmatically focused

### ISSUE THREAD

**Issue by onlyann** [microsoft/fluentui#12291]
### Environment Information

- **Package version(s)**: 7.102.0
- **Browser and OS versions**: tested with Chrome and Firefox.

### Describe the issue:

When a button takes focus programmatically, it doesn't display a visible outline.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/onlyann/pen/poJLRrV

#### Actual behavior:

No outline for the focused button

![image](https://user-images.githubusercontent.com/1916218/76596112-0f2f5680-6549-11ea-9aa9-941e4fbfcf75.png)

#### Expected behavior:

An outline similarly to what is visible when it receives focus with tab

![image](https://user-images.githubusercontent.com/1916218/76596143-1e160900-6549-11ea-89e5-d2e5ce1e417f.png)

### Documentation describing expected behavior

None

**Comment by aneeshack4** [comment]
@onlyann Thanks for reaching out to us - I believe this is because your `standardRef.current` is null. When I did `console.log(standardRef.current);` in the `onClick` it printed out null....

**Comment by onlyann** [comment]
> @onlyann Thanks for reaching out to us - I believe this is because your `standardRef.current` is null. When I did `console.log(standardRef.current);` in the `onClick` it printed out null....

Codepen automatically sets initial focus on the code editor.
You need to click on the default button "Give focus".
I have added a console log to prove that the primary button effectively is focused.

**Comment by aneeshack4** [comment]
@onlyann Apologies for the late response. I can see that when I put tab focus, the ::after gets applied that doesn't happen in the programmatic case which doesn't make any sense to me. I've pinged the component author and will let you know when I hear back.
![image](https://user-images.githubusercontent.com/4161791/77592480-3c242780-6ec0-11ea-8235-812bc300488d.png)

**Comment by kestill** [comment]
Hello, was there any resolution on this issue? I am seeing the same problem. 

Is there a way to disable the "::after" pseudo-element so that we can use our own focus styles instead?
