### ISSUE TITLE
@fluentui/react A searchable and clearable Dropdown has a X button which is not keyboard accessible  

### ISSUE THREAD

**Issue by sushruth** [microsoft/fluentui#12297]
### Environment Information

- **Package version(s)**: 0.46.0
- **Browser and OS versions**: Edge Win10

### Describe the issue:

Clear button on a searchable dropdown is not focussible by keyboard

#### Actual behavior:

clear button is not focusable

#### Expected behavior:

clear button should be focusable

### If applicable, please provide a codepen repro:

https://fluentsite.z22.web.core.windows.net/components/dropdown/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#types-search-multiple

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: NA

**Comment by silviuavram** [comment]
Why do you expect it to be clearable? If you have an `<input type="search" ...>` the icon there is not accessible by keyboard either. The content can be cleared by Escape.

**Comment by sushruth** [comment]
@silviuavram there is definitely a way to do the same thing without having to use the button. But, since there is a button, and it is clickable, it would be nice if people who depend on keyboard could do the same as well. What do you say?

**Comment by jurokapsiar** [comment]
Hi @sushruth, the user can press ESC to clear the value in a searchable clearable dropdown. This is consistent with the clearable `Input` as well as with accessibility speicfication. x button is not focusable by design.
