### ISSUE TITLE
Dialog with Tooltip opens tooltip behind the dialog

### ISSUE THREAD

**Issue by bansalrachita** [microsoft/fluentui#12305]
Dialog with Tooltip opens the `Tooltip` behind the dialog. 

P.S: The example & `EmailList` component has been simplified in-order to demonstrate the error!

### Environment Information

- **Package version(s)**: ^0.46.0
- **Browser and OS versions**: macOS 10.15.3/Chrome 80.0.3987.132

### Reproduction of the bug in a codepen:
https://codesandbox.io/s/fluent-ui-example-m6z6g

#### Example snip
```
const Example2 = () => (
  <Dialog trigger={<Button content="open" />} content={<DialogBody />} />
);

const DialogBody = () => (
  <Flex>
    <Flex style={{ width: "50%" }}>Panel</Flex>
    <Flex style={{ width: "50%" }} column>
      <EmailList />
    </Flex>
  </Flex>
);

const EmailList = () => {
  const emails = Array.from({ length: 5 });

  return (
    emails &&
    emails.map((_, index) => {
      return (
        <Tooltip
          key={`tooltip-${index}`}
          trigger={
            <Text styles={{ width: "50px" }} truncated content={email(5)} />
          }
          content="Generate feed"
        />
      );
    })
  );
};
```

#### Actual behavior:
The tooltip content is behind the `Dialog` as seen in the screenshot. 

codepen output: https://m6z6g.csb.app/

![image](https://user-images.githubusercontent.com/10090750/76709852-50e20d80-66bf-11ea-9f53-3d29328a7bd7.png)

#### Expected behavior:
The `Tooltip` needs to be above the Dialog z-index and should be visible. 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/sites affected: None

**Comment by aneeshack4** [comment]
Thanks for reporting this @bansalrachita! This is another bug that the Fluent team will triage as part of all the bugs labeled Fluent UI v0 - tagging @jurokapsiar for visibility.

**Comment by jurokapsiar** [comment]
Tracking Reference: 6652

**Comment by layershifter** [comment]
Was fixed in #12572.

**Comment by bansalrachita** [comment]
@layershifter Which release version should we expect this to be out in?

**Comment by layershifter** [comment]
@bansalrachita I expect that it will be released as a part of `@fluentui/react-northstar@0.48.0`
