### ISSUE TITLE
Dropdown  - first option automatically selected on click of the control

### ISSUE THREAD

**Issue by Sendil85** [microsoft/fluentui#12304]
When clicking on the control, first option automatically selected and onchange even got fired, its forcibly setting first option, if we intend to select other option, onchange event is getting fired twice.

### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@Sendil85 Thanks for reaching out to us. This doesn't repro - right now on the latest master https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown, on click, there is not automatic selection. You can use `defaultSelectedKeys` to set dropdown items that you want to be default selected (for example in the multiselect example, this prop is set if you look in the show code button) but other than that, there's no automatic selection. In the future, to help us be actionable further, make sure to provide a codepen with repro steps on an isolated Fabric/Fluent component - fill out the template.

**Comment by silviuavram** [comment]
Provide clear repro steps, expected result, actual result, codesandbox with an example that reproduces the bug. Thanks!

**Comment by silviuavram** [comment]
While working on Dropdown issues I found one that is probably related to this ticket. No idea exactly, based on the fact that I don't have repro steps for this issue, but it's just a hunch.

I will create a PR for this and 2 other issues and we will see if it solves your bug.
