### ISSUE TITLE
onSearchQueryChange not called when the user clears the Dropdown

### ISSUE THREAD

**Issue by MonicaDumencu** [microsoft/fluentui#12314]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:
In the Dropdown component, with a onSearchQueryChange function assigned and the clearable option set to true. After making a dropdown selection, if the user click on the x button.

#### Actual behavior:

onSearchQueryChange doesn't get called.

#### Expected behavior:

onSearchQueryChange should get called with null value.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@MonicaDumencu Thanks for reaching out to us. Please provide a codepen with an isolated repro on the Fabric component so that this is actionable for us.
