### ISSUE TITLE
Tool tip present with 'Hover over me' button does not gets close by pressing esc key.

### ISSUE THREAD

**Issue by mohitrock1** [microsoft/fluentui#12317]
**User Experience:**
If tool tip present with the buttons are not gets closed by pressing esc key and always appears with the control then it might confuse the user about functionality of the control.

**Test Environment:**
#URL:https://codepen.io/
Tools: Accessibility insight tool

![image](https://user-images.githubusercontent.com/29257206/76759955-c084f500-67b2-11ea-8838-875670f9cfae.png)

**Note:** User credentials should NOT be included in the bug.

**Repro Steps:**

1. Open Url https://developer.microsoft.com/en-us/fabric#/controls/web/tooltip
2. Navigate to Export to CodePen.
3. Navigate to Hang over me button.
4. Verify the issue.

**Actual Results:**
Tool tip present with 'Hang over me' button does not gets close by pressing esc key.

**Expected Result:**
After pressing esc key tool tip present with 'Hang over me' button should be closed.

**MAS Reference:**
MAS 1.4.13 - Content on Hover or Focus

**Reference Links:**
Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**Comment by aneeshack4** [comment]
@mohitrock1 I don't repro this - when I press ESC the tooltip dismisses. Which browser and OS are you reproing this on? Also are you making sure to use the latest version of Fabric/browser?
