### ISSUE TITLE
TeachingBubble has extra bottom padding if there is no primary or secondary button

### ISSUE THREAD

**Issue by k-mehta** [microsoft/fluentui#12329]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@k-mehta Please provide more actionable information. A codepen repro on the isolated Fabric component and repro steps at a minimum.

**Comment by k-mehta** [comment]
Which Fabric component and which version of the Fabric component is causing the issue
**TeachingBubble**
What behaviors and attributes are missing or incorrect
**primaryButtonProps, secondaryButtonProps**
What you expected and what is actually happening
**When primaryButtonProps/secondaryButtonProps are not set, there shouldn't be extra padding below the body content. See attached screenshot of the sample from the fabric UI website.**
Confirmation that the problem reproduces in isolation
**
Yes
**

![image](https://user-images.githubusercontent.com/17470208/77130696-3210ad80-6a16-11ea-9cea-506998d5daf8.png)

**Comment by aneeshack4** [comment]
@k-mehta I'm speaking with the component owner on what would be a good fix.
