### ISSUE TITLE
Cannot access ambient const enums when the '--isolatedModules' flag is provided

### ISSUE THREAD

**Issue by ImVeryLost** [microsoft/fluentui#12328]
### Environment Information

- **Package version(s)**: 7.104.0

same as in the bug report #7110, i cant use const enums with the --isolatedModules. I thought this was resolved? using office-ui-fabric-react at the latest version - 7.104..0

**Comment by ImVeryLost** [comment]
Ah, apparently it only happens if i import the SearchBox directly, from "office-ui-fabric-react" and not "office-ui-fabric-react/lib/SearchBox". i thought the latter was an unusual way to import, is it a workaround? never the less, i suppose its good enough.

**Comment by ImVeryLost** [comment]
![image](https://user-images.githubusercontent.com/61872067/76828548-e5687f00-6829-11ea-86f6-b82a9db55ee4.png)

**Comment by aneeshack4** [comment]
Thanks for reporting this @ImVeryLost. I believe this hasn't been touched in a while so not sure why this would regress... let me look into this more and get back to you.

**Comment by aneeshack4** [comment]
@ImVeryLost IconNames has been [deprecated](https://github.com/microsoft/fluentui/blob/master/packages/icons/src/IconNames.ts#L2) as we don't encourage `const enum` usage. Please use the Fabric (Fluent) [Icon component](https://developer.microsoft.com/en-us/fabric#/controls/web/icon). This page has code samples on how to use the Icon component - if you can provide me with more context of how you're using IconNames, I can help you transition to the Icon component.

**Comment by ImVeryLost** [comment]
I dont want to use icons directly, i want to use the SearchBox component. Sadly, to use it i need to call the initiate icons command, which throws the error mentioned above.

**Comment by aneeshack4** [comment]
@ImVeryLost That doesn't make any sense because SearchBox code uses the Icon component not the deprecated IconNames. If you look at where this [iconName in SearchBox](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.base.tsx#L106) comes from (first of all you can it's used in `<Icon>`, it's [here](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/Icon/Icon.types.ts#L44) in Icon.types.ts (again not the deprecated IconNames).

**Comment by ImVeryLost** [comment]
And yet here i am.
Im importing initializeIcons from uifabric/icons and SearchBox from
office-ui-fabric-react/lib/Searchbox as per documentation.

**Comment by aneeshack4** [comment]
@ImVeryLost You do not have to import initializeIcons - as you can see in the documentation, just use an iconName https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox
![image](https://user-images.githubusercontent.com/4161791/78091804-937c3900-7393-11ea-9479-db9f02cfc137.png)

**Comment by ImVeryLost** [comment]
Except, if you do that, the icon is not visible.
And if you view the same example on codepen, it uses the initializeIcons
with the comment "initialize icons in case this example uses them".
This wiki also says im to use the command if i want to to view icons.
https://github.com/microsoft/fluentui/wiki/using-icons

**Comment by aneeshack4** [comment]
@ImVeryLost I see - yes Codepen does have initializeIcons but as you can see also in the Codepen, the icons are rendering correctly. Can you repro the error you're having with initializeIcons in a Codepen? I can't really help without seeing a repro. Please also make sure you have all the latest versions in your dependencies and you're synced with latest master.

**Comment by dennispg** [comment]
Here's what I did to repro:
1. I started from using the dotnet core template, `dotnet new reactredux`.
2. I updated all the packges in ClientApp/ to latest versions
3. `npm install @fluentui/react`
4. add `import {DefaultButton} from 'office-ui-fabric-react'` (I am doing this only to repro, if I do something like `import { DefaultButton } from 'office-ui-fabric-react/lib/Button';` instead it works)

I notice `office-ui-fabric-react/src/index.ts` references an `Icons.ts` in addition to `Icon.ts`, which in turn references `@uifabric/icons` and I believe this is where it all breaks down.
https://github.com/microsoft/fluentui/blob/9e53b82fcc814a0ec53e34a77ed25bcebb256d19/packages/office-ui-fabric-react/src/Icons.ts#L1

my package.json:
```
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@fluentui/react": "^7.110.1",
    "@uifabric/icons": "^7.3.33",
    "bootstrap": "^4.4.1",
    "connected-react-router": "^6.8.0",
    "history": "4.10.1",
    "jquery": "^3.5.0",
    "merge": "1.2.1",
    "node-sass": "^4.14.0",
    "office-ui-fabric-react": "^7.110.1",
    "popper.js": "^1.16.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-redux": "^7.2.0",
    "react-router": "5.1.2",
    "react-router-dom": "5.1.2",
    "react-scripts": "^3.4.1",
    "redux": "^4.0.5",
    "redux-thunk": "2.3.0",
    "svgo": "^1.3.2"
  },
  "devDependencies": {
    "@types/history": "^4.7.5",
    "@types/jest": "^25.2.1",
    "@types/node": "^13.13.4",
    "@types/react": "^16.9.34",
    "@types/react-dom": "^16.9.7",
    "@types/react-redux": "^7.1.7",
    "@types/react-router": "^5.1.7",
    "@types/react-router-dom": "^5.1.5",
    "@types/reactstrap": "^8.4.2",
    "@typescript-eslint/parser": "^2.30.0",
    "cross-env": "^7.0.2",
    "eslint": "^6.8.0",
    "eslint-plugin-flowtype": "^4.7.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-react": "^7.19.0",
    "reactstrap": "^8.4.1",
    "typescript": "^3.8.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "cross-env CI=true react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "lint": "eslint ./src/**/*.ts ./src/**/*.tsx"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```

**Comment by andyrooger** [comment]
I also have this issue after updating from TS 3.3.4000 to 3.9.2. I've made a repro that works from 3.3 onwards though so I'm not sure how it didn't appear before.

CodePen won't repro because you need --isolatedModules to trigger the error.

My repro

```json
// package.json
{
  "name": "repro",
  "version": "0.0.0",
  "description": "",
  "scripts": {
    "build": "tsc"
  },
  "dependencies": {
    "@fluentui/react": "^7.113.2",
    "@types/react": "^16.9.35",
    "@types/react-dom": "^16.9.8",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "typescript": "^3.3.4000"
  },
  "devDependencies": {}
}
```

```json
// tsconfig
{
  "compilerOptions": {
    "isolatedModules": true,
    "jsx": "react",
    "target": "es6",
    "moduleResolution": "Node"
  },
  "include": [
    "index.ts"
  ],
}
```

```ts
// index.ts
import { initializeIcons } from '@fluentui/react/lib/Icons';
// these break too
//import { initializeIcons } from 'office-ui-fabric-react/lib/Icons';
//import { initializeIcons } from '@uifabric/icons';
//import { initializeIcons } from '@uifabric/icons/lib/index';

initializeIcons();
```

@aneeshack4 Does this or the repro from @dennispg count as actionable feedback to reopen with?

**Comment by andyrooger** [comment]
FWIW - This issue has disappeared in the codebase I care about now, though not in the repro.

The following worked around it in the repro

- `skipLibCheck: false` - Weakens type checking across everything
- `isolatedModules: false` - Weakens type checking across everything (but only relevant for transpileOnly compilations)
- Replacing import with `const initializeIcons = require('@fluentui/react/lib/Icons').initializeIcons`
    - Keeps types intact but no compiler issues. Not sure why.
    - Needs webpack to rewrite the require

It would be handy, even if temporarily to move `initializeIcons` into a completely separate file we can import directly that doesn't contain `IconNames`
