### ISSUE TITLE
MenuButton doesn't display the popup menu on top inside a table column 

### ISSUE THREAD

**Issue by bansalrachita** [microsoft/fluentui#12343]
`MenuButton`'s menu popup displays content behind the table column element.

The example has been simplified using the native HTML `<table/>` component with a caveat that we don't control the table styling and overriding the styles is not an option in our case.

By doing some casual debugging, the issue seems to be occurring because the popup menu is applied inline with its parent element instead of the being applied to the body.

![image](https://user-images.githubusercontent.com/10090750/76917294-330fd680-6880-11ea-8174-aa4c163f2707.png)

### Environment Information

- **Package version(s)**: ^0.44.0
- **Browser and OS versions**: Windows 10 / Chrome 80.0.3987.132

### Example reproduction of the bug in a codepen:

~~https://codesandbox.io/s/fluent-ui-example-c1nnp~~

Edit:

Updated link below:
https://codesandbox.io/s/fluent-ui-example-61x54?file=/index.js

#### Actual behavior:

Popup menu gets chopped off when used inside table. We are currently unable to use `MenuButton` inside of a "complex" parent component where changing styles of the parent is not an option.

#### Expected behavior:

Popup menu display behavior inside the `MenuButton` component should always make it appear at the top _Or_  should be enabled as an optional `prop` for the user to be able to decide if this component should be applied `inline` to the parent or to the root.

### Priorities and help requested:

Requested priority: Normal

**Comment by jurokapsiar** [comment]
Tracking Reference: 6480

**Comment by DaleyKD** [comment]
Is there any update on this?  I'm trying to use the MenuButton inside of a Table, and this is an issue.
