### ISSUE TITLE
  npm install is not downloads the dependency package of office fabric in package-lock.json

### ISSUE THREAD

**Issue by v-jashr** [microsoft/fluentui#12348]
Currently 
when we are performing npm install operation we are not able to get office-ui-fabric-react dependency in **package-lock.json** 

Expected 
npm install should installed the dependency package of office fabric in package JSON.

**Comment by aneeshack4** [comment]
@v-jashr Can you provide us more actionable details such as the error output? You should be able to install office-ui-fabric-react with any package manager.
