### ISSUE TITLE
DatePicker: Add event parameter to onSelectDate

### ISSUE THREAD

**Issue by jtreebo** [microsoft/fluentui#12345]
#### Describe the feature that you would like added

Include (event: React.FormEvent<HTMLInputElement>) as callback parameter of onSelectDate

#### What component or utility would this be added to

DatePicker

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

The new Callback issued when a date is selected will be

(date: Date | null | undefined,
**event: React.FormEvent<HTMLInputElement> | null**
) => void

This way a common callback method can be used for forms with multiple DatePicker controls. Ex

handleDateChange = (date: Date | null | undefined, event: React.FormEvent<HTMLInputElement> | null): void => {
    
     // Validations here

     let data = this.state.data;
    data[event.target.id] = date;
    this.setState({data: data});
    
  };

**Comment by aneeshack4** [comment]
Hi @jtreebo, thanks for reaching out to us. Just to understand your feature request further, are you using DatePicker in conjunction with TextFields or some other native form controls? I was looking through https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls#Common_attributes and thought date pickers aren't listed there, I can see the argument for why they would be form controls. The team has discussed adding support for form controls in our overall component library but not specifically DatePicker - tagging component owner @lorejoh12, what do you think about this ask?

**Comment by jtreebo** [comment]
Please refer to this documentation - https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker#implementation

Name: onSelectDate
Type: (date: Date | null | undefined) => void
Description: Callback issued when a date is selected

The request parameter does not have to be an event, it could be the ID of the element. As I mentioned above, ID will be used in a common callback function to update the data object.

**Comment by Birtija** [comment]
Hi @aneeshack4 , @lorejoh12 

Do you have an estimate when this feature will be available?

Thank you.
