### ISSUE TITLE
Screen Reader is reading values two times of DatePicker grid

### ISSUE THREAD

**Issue by v-ajrai** [microsoft/fluentui#12354]
Screen Reader is reading values two times of DatePicker grid. Once date picker opens to select any date, Screen reader reads date picker enabled items two times.

### Environment Information

OS: Win 10 Enterprise N
Browser:  Edge + Narrator

### Describe the issue:

Screen Reader is reading values two times of DatePicker grid. Once date picker opens to select any date, Screen reader reads date picker enabled items two times.

### Please provide a reproduction of the issue in a codepen:
See first sample in below link
https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker

#### Actual behavior:

Screen Reader is reading values two times of DatePicker grid. Once date picker opens to select any date, Screen reader reads date picker enabled items two times.

#### Expected behavior:

Once date picker opens to select any date, Screen reader reads date picker enabled items one time.

**Comment by aneeshack4** [comment]
Hi @v-ajrai this doesn't repro for me.
![image](https://user-images.githubusercontent.com/4161791/77121781-3bd7e800-69f9-11ea-837e-73cab46d3e18.png)
Please make sure you're on the latest version of fabric and Narrator without scan mode.
