### ISSUE TITLE
ContextualMenu for IconButton in SVG not correctly positioned

### ISSUE THREAD

**Issue by joosttk** [microsoft/fluentui#12356]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "^7.76.2"
- **Browser and OS versions**: Win10, Edge broser (dev build)

#### Actual behavior:

ContextualMenu from an IconButton is placed in the wrong position. The IconButton is wrapped in a <foreignObject> within an <svg> canvas. This causes the position of the ContextualMenu to be off.

https://codepen.io/joosttk/pen/gOpjbww

#### Expected behavior:
Have the ContextualMenu positioned in the same way if this was not wrapped in a SVG and ForeignObject.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

**Comment by aneeshack4** [comment]
@joosttk Thanks for reaching out to us! Are you saying that the contexual menu should show up outside the SVG?

**Comment by joosttk** [comment]
No, it should show up within the SVG, but right under the IconButton (if not specifying a different DirectionalHint). I have not been able to figure out exactly how it is positioned now. It's not as there is a standard offset or anything.

I updated the codepen:
![image](https://user-images.githubusercontent.com/45209216/77116898-401ff780-6a31-11ea-9804-0b103cf904da.png)

![image](https://user-images.githubusercontent.com/45209216/77116920-4910c900-6a31-11ea-9c22-ddf9fb970c69.png)

I would expect the same behavior as the first screenshot (without an SVG)

**Comment by aneeshack4** [comment]
It's showing up the same for me in both scenarios:
![image](https://user-images.githubusercontent.com/4161791/77120441-e1458880-6a06-11ea-9920-93b318723c50.png)
![image](https://user-images.githubusercontent.com/4161791/77120453-e86c9680-6a06-11ea-831f-e4bfa67d44ee.png)

**Comment by joosttk** [comment]
That us super strange.. in what browser? I checked in both Edge (Version 82.0.453.2 (Official build) dev (64-bit)) and Chrome (Version 80.0.3987.149 (Official Build) (64-bit)). 

I have the same issue in both.

**Comment by aneeshack4** [comment]
This is yeah very strange - it's only reproing for me on Chrome - Windows. Doesn't repro on Chrome - Mac or Edge - Windows.
