### ISSUE TITLE
Button focus border style is unclear in MDL2 theme

### ISSUE THREAD

**Issue by zeedomD** [microsoft/fluentui#12357]
### Environment Information

- **Package version(s)**: 7.105.0
- **Browser and OS versions**: windows X64, Chrome

### Describe the issue:
When using keyboard to access the button in MDL2 mode, the button will show a white border. From customer side, the button is just a slight small one instead of a showing a focus border.
Instead of style in MDL2, in the normal theme, border will have a gap to the boundary of the button.

### Please provide a reproduction of the issue in a codepen:

1. Open UI Fabric React Examples, https://fabricweb.z5.web.core.windows.net/oufr/7.105.0/#/examples/button
2. In Default button example, change the theme to MDL2
3. Use Keyboard to access the Primary Button, focus on it.

#### Actual behavior:

We can hardly distinguish the focus border.
![image](https://user-images.githubusercontent.com/20253660/77068278-45754600-6a21-11ea-8b65-a5192b465412.png)

#### Expected behavior:

The border is obviously since there is a gap.
![image](https://user-images.githubusercontent.com/20253660/77068777-1dd2ad80-6a22-11ea-99e9-b64bbc5aec82.png)

**Comment by aneeshack4** [comment]
@zeedomD I can see this repro in the MDL2 theme - but I don't see a separate Button.styles.ts file in the that package so let me ask my team and get back to you.

**Comment by aneeshack4** [comment]
@zeedomD I spoke with this package owner @Vitalius1 - looks like the MDL2 package's [PrimaryButton.styles.ts](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/mdl2-theme/src/mdl2/styles/PrimaryButton.styles.ts) and [DefaultButton.styles.ts](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/mdl2-theme/src/mdl2/styles/DefaultButton.styles.ts) have some gaps in styling & needed to updated to reflect Fabric 6's styles like in [BaseButton](https://github.com/OfficeDev/office-ui-fabric-react/blob/6.0/packages/office-ui-fabric-react/src/components/Button/BaseButton.styles.ts#L42). I'll try to get to this soon.

**Comment by zeedomD** [comment]
@aneeshack4 , Thank you for you quick response. Do we have a timeline for this fix? Is that possible we get this issue fixed before the end of this month?

**Comment by Vitalius1** [comment]
@zeedomD @aneeshack4 I have a PR up to fix this so as soon as it's checked in and the package publishes all you need is to bump the version and the focus styles should look right. Honestly this package was not planned to be in use for such a long time and the main purpose was to serve as a quick transitional helper.
