### ISSUE TITLE
Use of Rating component auto-focuses to the component, thereby scrolling to it on page load

### ISSUE THREAD

**Issue by k-mehta** [microsoft/fluentui#12376]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "^7.79.1"
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a codepen:
Repro with readOnly=false: https://codepen.io/k-mehta/full/RwPBeeM
The behavior does not repro if readOnly=true: https://codepen.io/k-mehta/full/QWbBZmo

#### Actual behavior:

A web page scrolls to the Rating component on load (and subsequent reloads) if the component is not read-only.

#### Expected behavior:

The web page should not scroll to the component.

**Comment by aneeshack4** [comment]
@k-mehta thanks for reaching out to us! Ah so if it's readOnly, it doesn't scroll straight to the Rating component upon load. So even if it isn't readOnly (editable) it should not pull focus and scroll down. I see that the stars are wrapped in a FocusZone so I think that's related - also this line setting allowFocusOnRoot to true in the readOnlyProps: https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/Rating/Rating.base.tsx#L143. Would like to get some input from component owner @jdhuntington - what do you think?

**Comment by Terverok** [comment]
bumping it up... I've this problem also. Can someone look into this, please? It is an issue since almost a year.
