### ISSUE TITLE
office-ui-fabric-react/lib/DetailsList"' has no exported member 'IDetailsColumnRenderTooltipProps'.

### ISSUE THREAD

**Issue by Harshagracy** [microsoft/fluentui#12372]
#### Behavior:

Error: ../../office-ui-fabric-react/lib/DetailsList"' has no exported member 'IDetailsColumnRenderTooltipProps'.
<img width="549" alt="Screenshot_2" src="https://user-images.githubusercontent.com/14230498/77159070-a442ca00-6aca-11ea-923c-fdbe83cfe8a3.png">

I am trying this component -**DetailsList Locked Header** from Office Ui fabric component
https://developer.microsoft.com/en-us/fabric#/controls/web/scrollablepane
### version
"office-ui-fabric-react": "6.189.2"
### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Blocking)

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@Harshagracy Can you please provide more details? An isolated repro on a Codepen would be most helpful. I don't see this error at all in the codebase on latest master:
![image](https://user-images.githubusercontent.com/4161791/77208984-1f0be500-6acb-11ea-9cb7-e730216fdf7c.png)

**Comment by Harshagracy** [comment]
Hi, 

In my SPFx(version 10.0.0) project, I am trying to implement the example of this component - DetailsList Locked Header from this link -
https://developer.microsoft.com/en-us/fabric#/controls/web/scrollablepane.

And I am getting this error that  

> ../../office-ui-fabric-react/lib/DetailsList"' has no exported member 'IDetailsColumnRenderTooltipProps'.
Line: `import { IDetailsColumnRenderTooltipProps } from 'office-ui-fabric-react/lib/DetailsList';`


I don't get any error from code pen. Only in the SPFx project, I am getting an error. I am assuming that the path might be different from the example one. Could you please help me with the exact path?

these are the dependencies in my spfx project with their version:
```
 "dependencies": {
    "react": "16.8.5",
    "react-dom": "16.8.5",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "office-ui-fabric-react": "6.189.2",
    "@microsoft/sp-core-library": "1.10.0",
    "@microsoft/sp-property-pane": "1.10.0",
    "@microsoft/sp-webpart-base": "1.10.0",
    "@microsoft/sp-lodash-subset": "1.10.0",
    "@microsoft/sp-office-ui-fabric-core": "1.10.0",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  },
  "resolutions": {
    "@types/react": "16.8.8"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.10.0",
    "@microsoft/sp-tslint-rules": "1.10.0",
    "@microsoft/sp-module-interfaces": "1.10.0",
    "@microsoft/sp-webpart-workbench": "1.10.0",
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
```

**Comment by aneeshack4** [comment]
@Harshagracy It's related to the SPFx project then - this is not reproing on the latest fabric master when used on their own like with the example code - I'd suggest reaching out to that project owners. Going to close this now as resolution is external.
