### ISSUE TITLE
Where can I find an Example for using DetailsList with react hooks 

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft/fluentui#12387]
All the examples in https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist are using react classes and setState.

When I convert to use hooks I have const [items,setItems] = React.UseState([]);

But in the _onColumnClick function, instead of "const { columns, items } = this.state; " 
items should have what I added with setItems (the list is showing ) but it is 0 items array. 
So _copyAndSort(**items**, currColumn.fieldName!, currColumn.isSortedDescending); 
Items is empty and the list does not show anymore.

Any help is welcome, thank you.

**Comment by aneeshack4** [comment]
@Ofer-Gal Can you please provide a codepen showing what you're trying to do?
