### ISSUE TITLE
Let tooltipHostProps take a React.ReactNode for content

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#12393]
#### Describe the feature that you would like added
tooltipHostProps.content is a string | JSX.Element | JSX.Element[].

We're trying to move as many things as we can to use React.ReactNodes. Is it possible to expand tooltipHost.content to take that as well?

#### What component or utility would this be added to
TooltipHost

#### Have you discussed this feature with our team, and if so, who
Negative

**Comment by aneeshack4** [comment]
Hi @mltejera thanks for reaching out to us! I looked up cases where ReactNode is [appropriate](https://stackoverflow.com/questions/58123398/when-to-use-jsx-element-vs-reactnode-vs-reactelement) and don't see why `content` can't accept ReactNode as a type too. Tagging component owner @micahgodbolt - perhaps I'm not seeing something. The only thing I can think of is if we introduce this pattern, maybe we should be careful to introduce it everywhere for consistency sake.

**Comment by olemp** [comment]
@aneeshack4 I'm trying to add my custom component to the `content` of the `TooltipHost` but I'm getting the following error/warning:

```
react_devtools_backend.js:6 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by ProjectColumnTooltip)
    in div (created by ProjectColumnTooltip)
```

Is there any way to avoid `p` being rendered as the root element?

**Comment by j-te** [comment]
@aneeshack4 FYI

Using `<p>` severely limits what content can be used: [html spec](https://html.spec.whatwg.org/#phrasing-content-2).

This also relates to: #9852.

I think there should be a check on the input prop type if you are adamant that `<p>` should be utilised if a string. However, consider if ReactDOMServer is used. I would just change `<p>` to `<div>`.

Additionally, I may have found another issue: `onRenderContent` has no effect. I thought this may help solve @olemp's issue but the prop seems to be removed from code, but remains in documentation. May relate to #2192. I will raise a new issue if someone confirms it is one.
