### ISSUE TITLE
'Alt-down' is required to open a submenu of a commandbar item instead of 'down'

### ISSUE THREAD

**Issue by getroyer** [microsoft/fluentui#12394]
### Environment Information

- **Package version(s)**:  "office-ui-fabric-react": "7.105.0"
- **Browser and OS versions**:  Edge, Windows 10

### Describe the issue:

We received an accessibility bug because the testers could not discover that 'alt-down' would open a submenu of a CommandBar item. They expected 'down' to open the submenu for keyboard users. Why isn't down arrow supported?

I see this was discussed in this issue: [https://github.com/microsoft/fluentui/issues/6642](https://github.com/microsoft/fluentui/issues/6642). But I do not see why it was decided that down arrow should not be the default keyboard shortcut.

**Comment by aneeshack4** [comment]
@getroyer Thanks for reaching out to us! I think it's because of conflicts with FocusZone - what David said in this [comment](https://github.com/microsoft/fluentui/issues/6642#issuecomment-463431647) applies to CommandBar too I believe. Are you using splitbuttons as the submenus in the CommandBar or just the default Fabric CommandBar?

**Comment by getroyer** [comment]
We are using a split button with as a CommandBarItem and it contains a subMenu. So pressing down to open a submenu would conflict with trying to get to something below the currently active item in a focus zone?

**Comment by aneeshack4** [comment]
Why not use just the default Fabric CommandBarButtons? They solve the case of having a dropdown within each button and have built in keyboarding support - I think your problem is you're trying to mix SplitButtons with CommandBar.

**Comment by getroyer** [comment]
Using a normal button is a possibility.

**Comment by aneeshack4** [comment]
Cool going to close this then!
