### ISSUE TITLE
Missing bold font-face declaration

### ISSUE THREAD

**Issue by swese44** [microsoft/fluentui#12391]
`_registerFontFaceSet()` does not add a declaration for `bold`, only `light`, `semilight`, `regular` and `semibold`:

https://github.com/microsoft/fluentui/blob/f9ca45d012d2e77eea728e19651b144452562004/packages/styling/src/styles/DefaultFontStyles.ts#L27

### Environment Information

- **Package version(s)**: 7.105.2
- **Browser and OS versions**: Chrome 80.0.3987.149, Mac OSX Catalina

### Please provide a reproduction of the bug in a codepen:
```ts
let { 
  Fabric 
} = window.Fabric;

const Content = () => {
  return (
    <Fabric>
      <div style={{fontWeight: 100}}>
        Hello World
      </div>
      <div style={{fontWeight: 300}}>
        Hello World
      </div>
      <div style={{fontWeight: 400}}>
        Hello World
      </div>
      <div style={{fontWeight: 600}}>
        Hello World
      </div>
      <div style={{fontWeight: 700}}>
        Hello World
      </div>
    </Fabric>
  );
};

ReactDOM.render(
  <Content />, 
  document.getElementById("content")
);

```

#### Actual behavior:
Bold (700) font weight looks the same as semibold (600), at least in the Chrome browser. IE11 might be stretching the semibold font to render it more bold.

#### Expected behavior:

Bold 700 font-weight renders the correct weight.

### Priorities and help requested:

Are you willing to submit a PR to fix? Maybe

Requested priority: Normal

Products/sites affected: Any web app that does not separately include Fabric CSS with additional font overrides.
https://www.yammer.com
https://fabricweb.z5.web.core.windows.net/oufr/7.105.2/

**Comment by aneeshack4** [comment]
@swese44 Thanks for reaching out to us. semibold and bold don't look the same on the Fluent [website](https://developer.microsoft.com/en-us/fabric#/styles/web/typography).
![image](https://user-images.githubusercontent.com/4161791/77369754-57aaf900-6d2d-11ea-8d43-c7b590119fdb.png)

**Comment by swese44** [comment]
Thanks @aneeshack4. The Fluent site separately includes the `office-ui-fabric-core` CSS which includes its own font-face declaration to map the bold font file to font-weight 700:
https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/sass/mixins/_Font.Mixins.scss

Hey @dzearing, it looks like your initial removal of the Fabric Core CSS in 2017 left out the bold font-face declaration, was this intentional or is this a bug? Thanks!
https://github.com/microsoft/fluentui/commit/3a198d4811b76f491acce31efa358c9c95740a63#diff-c203434e02759d25a4b011e094cc2f89R166

**Comment by swese44** [comment]
Here's a fix. Note that we may need to treat this as a breaking change in case consumers are not expecting their bold fonts to become more bold.
https://github.com/microsoft/fluentui/pull/12401

**Comment by aneeshack4** [comment]
Thanks @swese44 for making a PR for this! Another PR #12398 has been opened to address this.
