### ISSUE TITLE
Text and icon alignment is not correct in ChoiceGroup in case of line-height is increased from default i.e. 20px

### ISSUE THREAD

**Issue by v-ajrai** [microsoft/fluentui#12400]
Text and icon alignment is not correct in ChoiceGroup in case of line-height is increased from default i.e. 20px

### Environment Information

OS: Win 10

Browser: Chrome, Edge

### Describe the issue:

Text and icon alignment is not correct in ChoiceGroup in case of line-height is increased from default i.e. 20px

### Please provide a reproduction of the issue in a codepen:

You can see issue in below code pen link
https://codepen.io/ajeetkumarrai/pen/qBdyPYr

#### Actual behavior:

Text and icon alignment is not correct in ChoiceGroup in case of line-height is increased from default i.e. 20px

#### Expected behavior:

Text and icon alignment should be top aligned in ChoiceGroup in case of line-height is increased from default i.e. 20px to higher

**Comment by aneeshack4** [comment]
@v-ajrai I don't see this reproing on the Controlled example codepen from the Fluent site: https://codepen.io/aneeshack4/pen/mdJzxOx?editors=0010 and don't see a 20px override setting in your codepen either... how are you producing the misalignment?

**Comment by v-ajrai** [comment]
If you change line height of div which embedded ChoiceGroup control, then you can repro it, as you can see in our shared code pen example where we changed the line height of div in HTML code
https://codepen.io/ajeetkumarrai/pen/qBdyPYr

**Comment by aneeshack4** [comment]
@v-ajrai I modified the Codepen from the ChoiceGroup examples page to use your code and this doesn't repro: https://codepen.io/aneeshack4/pen/abOxzbo?editors=0010 I'm really stumped - I have no idea why you're getting this misalignment but you can use this Codepen to not have it.
