### ISSUE TITLE
Modal dialog overriding text direction

### ISSUE THREAD

**Issue by taurheim** [microsoft/fluentui#12410]
### Environment Information

- **Package version(s)**: 7.105.2
- **Browser and OS versions**:  Edge Chromium/ Win10

#### Actual behavior:

dir="ltr" tag added to layer in modal:
![image](https://user-images.githubusercontent.com/5691564/77480924-df514000-6ddf-11ea-8af4-365c081d5a42.png)
See pen: https://codepen.io/taurheim/pen/eYNPKaq?editable=true (taken directly from [docs](https://developer.microsoft.com/en-us/fabric#/controls/web/modal))

#### Expected behavior:

In 7.61.1:
![image](https://user-images.githubusercontent.com/5691564/77480999-fbed7800-6ddf-11ea-9973-e6523276d279.png)
https://codepen.io/taurheim/pen/VwLEdOp?editable=true

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes if someone can help identify root cause

Requested priority: High (this seriously affects any non-RTL languages in pages that control their own ltr/rtl through html tags)

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@taurheim thanks for reaching out to us. I do see this repro: 
![image](https://user-images.githubusercontent.com/4161791/77489256-9613e700-6e05-11ea-88f3-bdfb50920bae.png)
However there's no `dir` setting anywhere in the Modal or Layer code... so I'm really confused as to why it's defaulting to `ltr`. @JasonGore any ideas? Is there a way for users to pass in their own setting for this? I attempted [passing](https://codepen.io/aneeshack4/pen/WNvagXG?editors=1010) in `dir` but seems Modal doesn't take it. This might be related to #11808 but in that only a few `dir` settings were removed from Modal snapshots.

**Comment by JasonGore** [comment]
@micahgodbolt may know more, he did some work with rtl recently.

**Comment by taurheim** [comment]
Hi, pinging this again as it is blocking us from upgrading to the latest Fabric UI version.

@micahgodbolt @JasonGore

**Comment by micahgodbolt** [comment]
Hah...I actually fixed this recently. The Fabric control was printing "LTR" regardless of if it was needed or not. Current release is fixed:

![image](https://user-images.githubusercontent.com/1434956/79617348-1a335480-80bc-11ea-91db-c3413344a50e.png)

https://github.com/microsoft/fluentui/releases/tag/office-ui-fabric-react_v7.105.12
https://github.com/microsoft/fluentui/pull/11808

**Comment by taurheim** [comment]
Awesome, thank you - fix works on our side :)
