### ISSUE TITLE
Commandbar: use fluentui/react-northstar or fluentui/react?

### ISSUE THREAD

**Issue by spotnick** [microsoft/fluentui#12416]
Hi everybody,

I´m encountering a Bug(?) while using FluentUI. I´m currently developing an MS Teams Application with personal tabs and want to use a Commandbar like it´s every native Teams App. 

I´m using React to program the application. 

First I´m using most of the time @fluentui/react-northstar since it gives a perfect native feeling to the user and has already themes for teams build in. Since react-northstar does not offer a commandbar component I tried to use [this](https://developer.microsoft.com/en-us/fabric#/controls/web/commandbar). Since I´m using JS and not Typescript I had to do some adjustments which seem not load the Icons correctly. 

![image](https://user-images.githubusercontent.com/10115809/77518406-0d855d00-6e7e-11ea-8b8e-ff353cc91710.png)

After that I tried to use the Menu component of northstar but it looks less native and kind of clunky to me. 

![image](https://user-images.githubusercontent.com/10115809/77518591-5a693380-6e7e-11ea-8974-d7c4c0906d67.png)

I´m not sure if a bug submission is right for this. Do you have any ideas how I can achieve something like this?

![image](https://user-images.githubusercontent.com/10115809/77518701-808ed380-6e7e-11ea-9632-76ae9e552de9.png)

Thanks a lot!

Best, 
Thomas

**Comment by aneeshack4** [comment]
@spotnick For this OneDrive command bar, you should be able to just use the https://developer.microsoft.com/en-us/fabric#/controls/web/commandbar - you can use these Icons https://developer.microsoft.com/en-us/fabric#/styles/web/office-brand-icons (see that OneDrive is in this set) and there are more for the individual buttons here: https://developer.microsoft.com/en-us/fabric#/styles/web/icons

**Comment by spotnick** [comment]
@aneeshack4  Thats what I tried. After diging around fore 4 hours I found out that office-ui-react and @fluentui/react-northstar  seem not to be compatible to each other. Commandbar is using icons which themes from @fluentui/react-northstar cannot render. Even though I provide icons which can be rendered by the theme they will not be shown because I think Commandbar cannot handle them...

For best Teams Support, which package should we use? I´d rather take @fluentui/react-northstar  because it has integrated themes for teams and is really handy. Otherwise it does not provide DetailsListShimmer and a commandbar which is necessary but it seems that the themes are compatible to.

Some advice?

Thanks!

**Comment by aneeshack4** [comment]
@spotnick I see - I understand your scenario now. Are you trying to build a CommandBar with the Teams theme or the OneDrive one? Because the OneDrive icons are available with office-ui-fabric-react so OneDrive shouldn't be a problem at all. I haven't tried to build a Teams-themed CommandBar using the Fabric one but I think it should be doable also... I will ask my team but first I'd like to clarify that you're trying to build a Teams themed CommandBar, not OneDrive.

**Comment by spotnick** [comment]
@aneeshack4  Well it doesnt matter for me to build that exact onedrive commandbar. I just want to build an teams application and give the user maximum of nativ expirience. Which library should I use? react-northstar? Fluent UI? What about theming? Those libraries are not compatible to each other and I need some guidance or advice on how to fix it. 

Thanks!

**Comment by jurokapsiar** [comment]
Hi @spotnick, in the react-native package, you can use a Toolbar component to build "native" toolbar for Teams application. It unfortunatelly does not support having text in the buttons yet directly, but you can always  put text and icons to the children of the toolbar item. Please look at the documentation for [Toolbar](https://fluentsite.z22.web.core.windows.net/components/toolbar/definition)

**Comment by aneeshack4** [comment]
@spotnick For best teams support at the moment, please use react-northstar. We're working on unifying across the board.

**Comment by spotnick** [comment]
@aneeshack4 yeah that´s what I figured out in the first place. But react-northstar does not provide all the necessary components needed. E.g. a Detailslist is also missing next to the commandbar. So I´m just going to use FluentUI itself and make CSS also by myself since there is no solution for my problem.
