### ISSUE TITLE
Modal default styles are broken for scrollable content

### ISSUE THREAD

**Issue by OEvgeny** [microsoft/fluentui#12420]
### Environment Information

- **Package version(s)**: `office-ui-fabric-react@^7.105.2`
- **Browser and OS versions**: Any, tested on Chrome 80.0.3987.149

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/OEvgeny/pen/yLNRwxN?editors=1010

The issue appeared after migration from v6 to v7.

In order to make Modal to display scrollable content properly developers have to define a class for Modal `containerClassName` prop. The content container should be flexy for ScrollableAre to fill the area of Modal correctly, otherwise it overflows the modal and we have two scrollbars instead of one.

#### Actual behaviour:
Modal has two scrollbars when `containerClassName` is not set to class with `display: flex` prop.

#### Expected behaviour:
Modal should have only one scrollbar when content is scrollable by default. without the need of defining and passing in the class.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: (if applicable): not yet.

### Notes

The problem appears because scrollable area max-height is set to `100vh`, and the Modal area height is less:  something like `100% - 32px`. 

We have the following ways to fix the problem:
- Add `display: flex` to Modal content container (used in documentation)
- Set `max-width` for scrollable area to the same width as in Modal (`100% - 32px`)
- Something else? Setting `overflow: hidden`  also helps, but I think the two ways above are preferable ones.

**Comment by aneeshack4** [comment]
@OEvgeny Thanks for reaching out to us and providing a codepen - what are the repro steps to see these 2 scrollbars you speak of? I only see one on the right know when I minimize and scroll in the modal.

**Comment by OEvgeny** [comment]
@aneeshack4 you basically need to click on Open Modal button.
Here is what I'm seeing:
![image](https://user-images.githubusercontent.com/2841858/77621739-147ba080-6f4e-11ea-99a3-7ca44743796e.png)

Chrome 80/Window 10

**Comment by aneeshack4** [comment]
@OEvgeny I finally got a repro - seems it doesn't repro on Mac (Chrome) but it does both on Edge Chromium and regular Chrome on Windows. which is really strange. When I inspect the DOM in both the non-repro case on Chrome-Mac and the repro-cases on Windows, I don't see a difference - right click inspect on scrollbar takes me to the same `iframe` in the DOM in both cases and I don't see the 2 different scrollbars reflected in the DOM. So I'm pretty stumped here @JasonGore - any ideas?

**Comment by OEvgeny** [comment]
It's weird that it doesn't repro on Chrome/Mac. It actually is kinda expected to me as scroll-area `max-height` is greater than modal root `height`, so when content makes scroll-area to grow it becomes higher than root container and additional scroll appears.

**Comment by cobyrne09** [comment]
@OEvgeny @aneeshack4 It reproduced on mac/chrome for me, albeit not with two scroll bars. Once I hit the end of one scroll (inner scroll?), I can initiate another scroll to scroll further scroll the outer scroll. It all displays as one scroll bar, however.

**Comment by OEvgeny** [comment]
Not something I was expected as a resolution for this :)

**Comment by khmakoto** [comment]
Sorry @OEvgeny, would you want this to be reopened? We enabled this rule to get rid of old, non-relevant issues anymore, but if this is still relevant we can reopen 😄

**Comment by OEvgeny** [comment]
@khamudom yes please. I updated the repro, so it works for me and the bug is still in the latest UiFabric release.

https://codepen.io/OEvgeny/pen/yLNRwxN?editors=1010

**Comment by khmakoto** [comment]
I've reopened the issue for now.

**Comment by ishaisagi** [comment]
I have the same problem in SharePoint, showing a dialog where content overflows, we get two scrollbars. 

The dialog components looks something like this:
 var feedbackDialogProps: IDialogContentProps = {
            showCloseButton: true,
            title: "Comment on " + this.props.DisplayName,
            type: DialogType.close,
        };
var modalProps: IModalProps = {
    containerClassName: Styles.ModalContainer,
    styles: { main: { maxWidth: '80% !important', width: '80% !important' } },
    responsiveMode: ResponsiveMode.large,   
}
 <Dialog dialogContentProps={feedbackDialogProps}
                    modalProps={modalProps}
                    onDismiss={() => { this.setState({ showCommentBox: false }) }}
                >
                    <DialogContent>
 </DialogContent>
                    <DialogFooter>

                    </DialogFooter>
 </Dialog>

Debugging it, the problem seems to be that "ms-Modal-scrollableContent scrollableContent-538"  classes are added by the Dialog component root - **around the child components** (content and footer). These cause the double scroll bars. If I remove these classes, or set the element to remove overflow-y:auto, the extra scrollbar disappears.

I would have expected the "scrollablecontent" classes to be added to the DialogContent element instead of around the header...but if I do that manually it also results in double scrollbars.

**Comment by OEvgeny** [comment]
An "official" solution from Fluent UI team used in docs:

```ts

  container: {
    display: 'flex',
    flexFlow: 'column nowrap',
    alignItems: 'stretch',
  },

      <Modal
        containerClassName={contentStyles.container}
      />
```
