### ISSUE TITLE
Adding @fluentui/react to a Parcel app breaks the bundle

### ISSUE THREAD

**Issue by sid-maddy** [microsoft/fluentui#12421]
### Environment Information

- **Package version(s)**: ^7
- **Browser and OS versions**: Not relevant

### Please provide a reproduction of the bug in a codepen:
1. Fork this CodeSandbox: https://codesandbox.io/s/sample-parcel-fluentui-react-app-z9757
2. Download the project
3. Install the packages
4. Run the start script

#### Actual behavior:
![Actual behavior](https://user-images.githubusercontent.com/10049286/77550470-2bcb7700-6ed7-11ea-9090-b46b0586bfbc.png)

#### Expected behavior:
![Expected behavior](https://user-images.githubusercontent.com/10049286/77550598-51f11700-6ed7-11ea-964d-d842178c205d.png)

### Priorities and help requested:
Are you willing to submit a PR to fix? Yes
Requested priority: Normal
Products/sites affected: NA

**Comment by aneeshack4** [comment]
@sid-maddy Thanks for reaching out to us. Your codesandbox with the fluent code runs fine for me: 
![image](https://user-images.githubusercontent.com/4161791/77593969-409e0f80-6ec3-11ea-8826-3a51fa6c2d83.png) so I don't see a repro... also what is Parcel? Have you considered that there's something on Parcel's end that is incompatible with Fluent?

**Comment by sid-maddy** [comment]
> Your codesandbox with the fluent code runs fine for me

Yes, the code works on CodeSandbox, but not locally

> [...] what is Parcel? Have you considered that there's something on Parcel's end that is incompatible with Fluent?

[Parcel](https://parceljs.org/) is a bundler like Webpack.
There have been previous issues with Parcel and this library (#7728, #9231, and #11534)
It seems that it is caused by a similar issue -- something is exported twice

In my case, it is the `IsFocusVisibleClassName` constant
![image](https://user-images.githubusercontent.com/10049286/77608664-e5603180-6f43-11ea-9c88-bc39d378f874.png)

**Comment by sid-maddy** [comment]
@aneeshack4, it is confirmed as a bug in the Parcel bundler (see parcel-bundler/parcel#4399).
For posterity's sake, referring to the type of duplicate exports like the ones I mentioned previously,

> This is allowed by the spec, as long as the exports of the same name actually refer to the same export.

Shall I close this issue?

**Comment by aneeshack4** [comment]
Thanks I'll close it.
