### ISSUE TITLE
Line chart hover state position while tabbing

### ISSUE THREAD

**Issue by kadio1** [microsoft/fluentui#12426]
### Environment Information

- **Package version(s)**: (fill this out) PR #12384
- **Browser and OS versions**: (fill this out) Edge

### Describe the issue:

The hover state should appear near the focus indicator while arrowing through the data viz.

### Please provide a reproduction of the issue in a codepen:

-->

#### Actual behavior:

Hover states currently appears in the top left corner of the page.

#### Expected behavior:

over the focus indicator of the arrow position.

### Documentation describing expected behavior

https://www.figma.com/file/HEQiS2rKRQWT7Ph81keQcvv9/Accessibility-Guidance?node-id=982%3A519
![FocusStatesHoverLineChart](https://user-images.githubusercontent.com/41807199/77591753-e050a300-6ead-11ea-9ae5-6197a4ed6883.png)

**Comment by aneeshack4** [comment]
Hi @kadio1, thanks for reporting this! I confirm repro. `DirectionalHint` is set to `topAutoEdge` in [this line](https://github.com/microsoft/fluentui/blob/master/packages/charting/src/components/LineChart/LineChart.base.tsx#L166) and the `refSelected` is set to mouseEvent in this [`_handleHover`](https://github.com/microsoft/fluentui/blob/master/packages/charting/src/components/LineChart/LineChart.base.tsx#L460) and those two together I believe are used to set where the Callout appears on tab focus. I stepped through this code in the Debugger: 
![image](https://user-images.githubusercontent.com/4161791/77666067-7936fb00-6f4e-11ea-9364-1ad0da21ba70.png)
And it looks like mouseEvent has the right value and `target = this.state.refSelected` is resolving properly so not sure why this is being sent constantly to the top left corner...
![image](https://user-images.githubusercontent.com/4161791/77666390-e3e83680-6f4e-11ea-9117-f1265b8bc468.png)
@Raghurk do you know who on your team can answer further questions about this?
