### ISSUE TITLE
ContextualMenu shows up in the wrong spot when the ref is on the Link component.

### ISSUE THREAD

**Issue by myermian** [microsoft/fluentui#12429]
### Environment Information
- **Package version(s)**: 7.105.2
- **Browser and OS versions**: Microsoft Edge (Chromium) Version 80.0.361.69 (Official build) (64-bit)

https://codepen.io/myermian/pen/BaNGLwa

#### Actual behavior:
The context menu does not use the location of the link when displaying, instead the top/left are based on the top-left corner of the page.

#### Expected behavior:
The context menu should, as it does for other controls, display below the component with which it has a ref.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Low
Products/sites affected: None

**Comment by aneeshack4** [comment]
@myermian Thanks for reporting this. I confirm repro. I started stepping through the code where the target and DirectionalHint get set for the Callout inside ContextualMenu: 
![image](https://user-images.githubusercontent.com/4161791/77705963-144fc500-6f8f-11ea-9a6d-628dbdaabde1.png)
Looks like the DirectionalHint's value is 7 which is bottomAutoEdge and the target looks properly set to the link so I'm not sure why this is defaulting to top left corner... @joschect any ideas?

**Comment by joschect** [comment]
Links ref doesn't actually point to a valid dom element. Instead it points to a react component ref. All the positioning is based off of being able to get the elements width, height, and position, and it can't do that with a react element. You can see if you use an id instead it works as expected. https://codepen.io/slimemold/pen/KKpbmGQ . I should probably add an explicit console warning about this.

It looks like the `Link` component doesn't provide a way of getting access to the dom element iself.

**Comment by aneeshack4** [comment]
@myermian Can you use an id instead as Jon suggested and shows in his codepen?

**Comment by myermian** [comment]
> @myermian Can you use an id instead as Jon suggested and shows in his codepen?

Yes, that worked. I gave thumbs up on the answer as well.
