### ISSUE TITLE
Unnecessary tab stop on legend for data viz.

### ISSUE THREAD

**Issue by kadio1** [microsoft/fluentui#12428]
http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/12384/merge/charting/dist/index.html#/examples/Donutchart

### Environment Information

- **Package version(s)**:  PR #12384
- **Browser and OS versions**: Edge

### Describe the issue:

The legend should not be a tab stop. Skip all legends in data viz as it is confusing to non sighted users as they have just gone through the data viz.

#### Actual behavior:

users tab to the first data point, arrow through each entry, then tabs to legend that solos entry points again. 

#### Expected behavior:
User tabs to first entry point of data vis, the hover states appears over the focus indicator as they arrow through all of the entry points, then tab to the next thing, be it buttons or ellipses, skipping the legend. 

### Documentation describing expected behavior
https://www.figma.com/file/HEQiS2rKRQWT7Ph81keQcvv9/Accessibility-Guidance?node-id=982%3A519
![legends1](https://user-images.githubusercontent.com/41807199/77592279-15112a00-6eaf-11ea-8167-1eb373802fe6.png)
![tab stops2](https://user-images.githubusercontent.com/41807199/77592280-15112a00-6eaf-11ea-9be9-7e147747d41a.png)

**Comment by aneeshack4** [comment]
@kadio1 Thanks for reaching out to us. The legend here also acts as a way to highlight each part of the donut but I understand how that's not useful to sighted users. @Raghurk is the charting library owner - what do you think Raghu?

**Comment by Raghurk** [comment]
This is by design. I will follow up with Karina and Jonah the PM and designer to understand if we need to consider this.

**Comment by Raghurk** [comment]
ok

**Comment by Raghurk** [comment]
I have opened a bug to track this. Will be fixing this.

**Comment by Raghurk** [comment]
This has been rejected as an issue by the accessability team internally. So we will support tabbing on legend
