### ISSUE TITLE
https://uifabricicons.azurewebsites.net/ Down

### ISSUE THREAD

**Issue by dustybrenning** [microsoft/fluentui#12438]
I'm sorry if this is not the place to report this but https://uifabricicons.azurewebsites.net/ is down. It was working yesterday but seems to be returning a 500 error today. Thanks in advance.

**Comment by aneeshack4** [comment]
@dustybrenning Thanks for reporting this. I see it's down too - let me ask the right people and get back to you.

**Comment by aneeshack4** [comment]
@dustybrenning Just an update - seems like the memory for this app is exhausted. The website owner is currently if changing the configuration by switching from the current 32 bit node to 64 bit node will fix this.

**Comment by dustybrenning** [comment]
Thanks for the update.

**Comment by aneeshack4** [comment]
It works now! @dustybrenning

**Comment by dustybrenning** [comment]
Thanks @aneeshack4 .
