### ISSUE TITLE
Card component has outline focus state

### ISSUE THREAD

**Issue by isabelacmor** [microsoft/fluentui#12442]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

Can repro in the docs: https://developer.microsoft.com/en-us/fabric#/controls/web/card

#### Actual behavior:

When the Card component itself is clicked, it gets a focus outline, even if there are not input/interactive elements inside the card.

#### Expected behavior:

The Card component shouldn't have any focus state itself. Rather, focus should be on elements within the card that semantically require focus.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: all using Cards

**Comment by aneeshack4** [comment]
@isabelacmor Thanks for reaching out to us! Where's the guidance that says Card component shouldn't get focus on the outer Card itself? I think this is by design... I've asked the component owner to double check.

**Comment by aneeshack4** [comment]
@isabelacmor I've spoken with the component owner & he actually thinks it's a styling bug. I'm waiting to hear back on what the appropriate fix would be here - I believe it will most likely involve adding a selector for focus to `Card.styles.ts` that will exclude Cards without any interact-able elements. @khmakoto
