### ISSUE TITLE
[Outlook] Add-in pane within Outlook now incorrectly scrolling

### ISSUE THREAD

**Issue by davidfishlock** [microsoft/fluentui#12449]
### Environment Information
- Browser and OS versions: Any browser, any OS

### Please provide a reproduction of the bug in a codepen:
- Open any Addin in Outlook OWA of type MessageReadCommandSurface

#### Actual behavior:
- There is an unnecessary vertical scrollbar because a div with class "ms-Panel-commands" now has a top margin of 18px, this causes unnecessary vertical scrolling within the div of class "ms-Panel-scrollableContent".

![image](https://user-images.githubusercontent.com/42198746/77711395-94703c00-701c-11ea-880e-509a7dce72d8.png)

#### Expected behavior:
A scrollable region isn't shown when it isn't required

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: (if applicable)
All Outlook addins using MessageReadCommandSurface and probably MessageComposeCommandSurface

**Comment by aneeshack4** [comment]
@davidfishlock This is not the Outlook repo. Provide a codepen with steps to produce an isolated repro on the Fabric component alone.

**Comment by davidfishlock** [comment]
@aneeshack4 The bug appears to be a result of the Outlook team's usage of the Fabric UI Panel component. Do you know anywhere this could be reported as this is affecting all Outlook addins.

**Comment by aneeshack4** [comment]
@davidfishlock Please create a codepen with steps to get an isolated repro on the Panel component, as is stated in the template above. Here's an example to get you started: https://codepen.io/aneeshack4/pen/yLNGgOG?editable=true

**Comment by davidfishlock** [comment]
Will raise this to Outlook team
