### ISSUE TITLE
MAS 4.1.1,MAS 4.1.2: Ensures ARIA attributes are allowed for an element's role (.ms-CommandBar-primaryCommand)

### ISSUE THREAD

**Issue by gb2793** [microsoft/fluentui#12455]
### Environment Information

- **Package version(s)**: 7.39.1
- **Browser and OS versions**: Chrome Version 80.0.3987.122 (Official Build) (64-bit)

### Describe the issue:

Ensures ARIA attributes are allowed for an element's role (aria-allowed-attr)

Element path
.ms-CommandBar-primaryCommand
Snippet
<div aria-orientation="horizontal" class="ms-OverflowSet ms-CommandBar-primaryCommand primarySet-466" role="presentation">

How to fix
Fix any of the following:
- ARIA attribute is not allowed: aria-orientation="horizontal"
Environment
Chrome version 80.0.3987.122 This accessibility issue was found using Accessibility Insights for Web 2.14.1 (axe-core 3.3.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at.

#### Actual behavior:

Unallowed ARIA attribute aria-orientation="horizontal" used

#### Expected behavior:

Use allowed aria attributes.

### Documentation describing expected behavior

MAS References:
MAS 4.1.1: https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={2e2a1540-aaf7-48a0-a53e-8f10cf309999}
MAS 4.1.2: https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730}

**Comment by aneeshack4** [comment]
@gb2793 Thanks for reaching out to us. I ran Keros on the CommandBar examples and don't see this error reproing - where are you seeing this? which part of the CommandBar? More details would be great, thanks.
![image](https://user-images.githubusercontent.com/4161791/77807029-84744e80-7054-11ea-83bf-7560d2567a4c.png)

**Comment by gb2793** [comment]
+@Mahadev<mailto:v-maarw@microsoft.com>

Can you please share the screenshots of our page and the DOM here?

//gauraba

**Comment by gb2793** [comment]
Hello Team,

Please find below screenshot of control and DOM for keros issue.

[cid:image001.png@01D60835.D3471BF0]

[cid:image002.png@01D60835.D3471BF0]

Thanks,
Mahadev
From: Gaurav Babbar <gauraba@microsoft.com>
Sent: 01 April 2020 14:43
To: microsoft/fluentui <reply@reply.github.com>; microsoft/fluentui <fluentui@noreply.github.com>; Mahadev Arwat (Tata Consultancy Services Ltd) <v-maarw@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [microsoft/fluentui] MAS 4.1.1,MAS 4.1.2: Ensures ARIA attributes are allowed for an element's role (.ms-CommandBar-primaryCommand) (#12455)

+@Mahadev<mailto:v-maarw@microsoft.com>

Can you please share the screenshots of our page and the DOM here?

//gauraba

**Comment by aneeshack4** [comment]
@gb2793 These screenshots are not viewable....

**Comment by gb2793** [comment]
Attached the screenshots here:

![CommandBarKerosIssue](https://user-images.githubusercontent.com/62755132/78219578-72276400-74dd-11ea-9fd5-677f81161fce.png)
![CommandBarKerosIssueDOM](https://user-images.githubusercontent.com/62755132/78219585-73589100-74dd-11ea-92f2-15d0e5ca32b0.png)

**Comment by aneeshack4** [comment]
@gb2793 You're gonna have to show that repros on the Fabric component isolated on its own instead of used in another environment - the bug is probably in how it's being used, not in the component itself since Keros doesn't show this error when run on the examples page with CommandBars on their own.
