### ISSUE TITLE
Using @fluentui not possible without office-ui-fabric-react

### ISSUE THREAD

**Issue by MichaelRoger** [microsoft/fluentui#12468]
Hi,
i have installed @fluentui/react and in favour of fluentui i tryed to uninstall office-ui-fabric-react

but all the styles still refer to office-ui-fabric-react
for example:
\node_modules\@uifabric\fluent-theme\lib\fluent\styles\Persona.styles.js

`import { sizeBoolean } from 'office-ui-fabric-react/lib/Persona';`

and then i tried 
> npm install @fluentui/fluent-theme
but it turns out, i does not exist...

```
"dependencies": {
    "@fluentui/react": "^7.105.5",
    "@types/jest": "24.0.12",
    "@types/node": "11.13.8",
    "@types/react": "16.8.15",
    "@types/react-dom": "16.8.4",
    "@uifabric/fluent-theme": "^0.16.21",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.0",
    "typescript": "3.4.5"
  }
```

**Comment by aneeshack4** [comment]
@MichaelRoger Thanks for reaching out to us! If you're going to use the office-ui-fabric-react Persona component, then yes the styles in that component will refer to office-ui-fabric-react. Are you trying to use the office-ui-fabric-react Persona with the fluent-theme?

**Comment by MichaelRoger** [comment]
hi, thanks for yout answer. Yes, i applied the fluent-theme, which does not exist in @fluentui. it is still placed in @uifabric/fluent-theme and it needs the office-ui-fabric-react package to read css-files specific to the component. i think it should be mooved and readressed.

**Comment by aneeshack4** [comment]
@MichaelRoger `fluentui/react` currently just re-exports everything from `office-ui-fabric-react` (OUFR), so it's normal that OUFR is still in the import statements of `@uifabric/fluent-theme`. I spoke with my teammate who looked at your dependencies - you need to update the fluent-theme version to latest, 7.1.46.

**Comment by MichaelRoger** [comment]
ok, i updated the package. As it turned out, the starter app https://github.com/microsoft/fluentui/wiki/Getting-Started-with-UI-Fabric#create-react-app uses a configuration https://github.com/kenotron/create-react-app-uifabric/blob/master/package.json that would not update to an higher version. i just replaced the versions to latest in my project. maybe the starter apps should be updated as well. 

i do not see any changes of my behaviour in version 7.1.46 of @uifabric/fluent-theme

**Comment by aneeshack4** [comment]
@MichaelRoger we'll take that into consideration as do future work on this package.

**Comment by dzearing** [comment]
@MichaelRoger 

You should not need to use `@uifabric/fluent-theme` if you're using `@fluentui/react` or even `office-ui-fabric-react@7`.

You also should not need to uninstall `office-ui-fabric-react`. You can certainly replace it in your package.json dependencies, and you can update your imports to pull from the new package. Even top level imports such as `@fluentui/react/lib/Persona` should continue to work. If you're finding otherwise, let us know!
