### ISSUE TITLE
fluent "lib-commonjs" export from fabric "lib"

### ISSUE THREAD

**Issue by itslooklike** [microsoft/fluentui#12464]
Hello 👋

i use `import { PrimaryButton } from '@fluentui/react/lib-commonjs/Button';` in nextjs
and got error `SyntaxError: Unexpected token 'export'`

i open `node_modules/@fluentui/react/lib-commonjs/Button.js` and saw, what hi require `office-ui-fabric-react/lib/Button` (`lib` not `lib-commonjs`)

is it wrong export? (i check only `PrimaryButton` component, maybe this problem in another components too)

![image](https://user-images.githubusercontent.com/17547664/77857528-b5948080-7206-11ea-82a9-63d1d0b854db.png)

### Environment Information

- "@fluentui/react": "^7.105.5"

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

**Comment by aneeshack4** [comment]
@itslooklike Are you trying to use this PrimaryButton? https://developer.microsoft.com/en-us/fluentui#/controls/web/button or this one? https://fluentsite.z22.web.core.windows.net/components/button/definition

**Comment by itslooklike** [comment]
@aneeshack4 to be honest, I don't know which button I'm trying to use
I just want to use any button, and try example from `readme.md` and get error

https://github.com/microsoft/fluentui#integrating-in-your-project

![image](https://user-images.githubusercontent.com/17547664/78005244-f514b700-7343-11ea-9582-0a5f249f4805.png)

**Comment by aneeshack4** [comment]
@itslooklike I believe that should say: `import { PrimaryButton } from 'office-ui-fabric-react/lib/Button';`
I'll fix that documentation. Thanks for showing it.

**Comment by aneeshack4** [comment]
@itslooklike Actually wait why don't use `import { PrimaryButton } from '@fluentui/react/lib/Button';` - as in use `lib` instead of `lib-common`. I think that should work you - let me know.

**Comment by itslooklike** [comment]
@aneeshack4 i need use `lib-commonjs` version of module, because i need SSR
i think problem is what `lib-commonjs` version module have wrong export
It export `ESM` module, but must export `CommonJS`

i create a codesanbox, if it can help https://codesandbox.io/s/fluent-cjcm4

**Comment by itslooklike** [comment]
well, i solve my problem, by use `import { PrimaryButton } from "@fluentui/react`
so its wrong build process for common-js modules, or confusing documentation

**Comment by aneeshack4** [comment]
@itslooklike Glad you were able to fix the problem. I'm not sure if the documentation stating the `import { PrimaryButton } from '@fluentui/react/lib/Button';` is correct. I do know `office-ui-fabric-react` has been re-exported but maybe the `lib` part isn't correct. I believe @ecraig12345 recently made this change in PR #12378 - Elizabeth do you think this needs to be changed?

**Comment by ecraig12345** [comment]
This is interesting--the checked in code using `lib` paths is correct, but I think we need to add a post-build step to `@fluentui/react` which converts `lib` imports in the commonjs build output to `lib-commonjs`. @kenotron added code for a step like this in the past, but I'm not sure if we ever enabled it.

**Comment by ecraig12345** [comment]
This was fixed at some point in the past year by adding a postprocessing step. If anyone notices it break again, feel free to file a new issue.
