### ISSUE TITLE
[Combobox] - Add a new prop for onCombobox Click

### ISSUE THREAD

**Issue by tabansal** [microsoft/fluentui#12477]
#### Describe the feature that you would like added

Currently, we have  onItemClick as a prop, we need onComboboxClick prop as well, which should be called as soon as user click insides the comboBox input.

#### What component or utility would this be added to

Combobox

**Comment by aneeshack4** [comment]
@tabansal I believe you're looking for `onFocus` look at the example code on the example page and you'll see how `onFocus` can be used to dictate what happens when the ComboBox is clicked.

**Comment by tabansal** [comment]
@aneeshack4 there's no prop onFocus in documentation. Is it newly added or documentation is out of date?

**Comment by aneeshack4** [comment]
@tabansal You can example usage of it in the link as I explained above.
![image](https://user-images.githubusercontent.com/4161791/77970489-ee3d6400-72b1-11ea-81be-fa1d09c575fe.png)

**Comment by tabansal** [comment]
@aneeshack4 onFocus is also triggered for keyboard focus or if user clicks on caret icon inside textbox.
Another thing is if focus is already inside textbox, it doesn't get triggered. I'm looking for a callback for  when user clicks inside textbox.

**Comment by aneeshack4** [comment]
@tabansal Ok I'm going to add this to the backlog for review since it's looking like a feature request.
