### ISSUE TITLE
Copy to Clipboard prototype is jumping when tooltip is shown

### ISSUE THREAD

**Issue by pompomon** [microsoft/fluentui#12476]
### Environment Information

- **Package version(s)**: 0.47
- **Edge Chromium and MacOS Mojave 10**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
Open https://fluentsite.z22.web.core.windows.net/prototype-copy-to-clipboard 
Scroll to the bottom of the page 
Click on the "Attached" example button and wait until the tooltip is shown
Then hover over the button in "Not Attached" example 

#### Actual behavior:

Something changes in the spacing in the bottom of the page and the whole content of the page moves down (see the video below)
[CopyToClipboardBug.zip](https://github.com/microsoft/fluentui/files/4404126/CopyToClipboardBug.zip)

#### Expected behavior:

Page shouldn't move at all

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

**Comment by layershifter** [comment]
@pompomon cannot repro this anymore, we fixed this in #14737 as I remember.
