### ISSUE TITLE
DetailsList : Need feature to hide/unhide a row when needed

### ISSUE THREAD

**Issue by raj-crec** [microsoft/fluentui#12472]
#### Describe the feature that you would like added

Need to Hide/Unhide rows in a details list, as needed.

#### What component or utility would this be added to

details list; can be added to grouped-list as well.

#### Have you discussed this feature with our team, and if so, who

Nope.

**Comment by aneeshack4** [comment]
@raj-crec We have this already with [Grouped DetailsList ](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/grouped)and [GroupedList](https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist) both can both expand and collapse each row independently. Are you talking about individuals rows within each group? Why not create each of those as separate groups then? Please provide more details about your use case.

**Comment by raj-crec** [comment]
@aneeshack4 ... I am talking about hiding individual rows in a detailsList. I could not find a way to do that in documentation. Can you help me here ?

**Comment by aneeshack4** [comment]
@raj-crec The way to do this is by using Grouped DetailsList or GroupedList - just create each row as a separate group.

**Comment by raj-crec** [comment]
Hey Thanks @aneeshack4 .. I'll try with a grouped detailslist. One doubt there though. Is it possible to have a grouped details list with multiple nesting levels ? As of now we can't use a groupedlist for some reason.

**Comment by aneeshack4** [comment]
@raj-crec Yes nesting is possible - please see the documentation there are nested examples.
