### ISSUE TITLE
O365-Application-Layout

### ISSUE THREAD

**Issue by MichaelRoger** [microsoft/fluentui#12470]
Hi,
i am searching for the component which is still used by Microsoft in it's O365-WebApps.

It seems, that Microsoft has managed a good way to build WebApps (like Outlook or Excel) and reuses it's components. What i really need:

**The Header-Bar**: so i can integrate in the look-and-feel of O365
**The App-Layout of Outlook**: This is way cool, because you got an fixed header, a navbar on the left and a scrollcontainer on the right for content. Additionally it has a second level-navigation.

Perhaps i just missed how to recreate this elements on my own.

**Comment by aneeshack4** [comment]
HI @MichaelRoger, I believe the [CommandBar](https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar) should help you recreate the header look of O365. The Nav component can be used the for the left navbar. We have several scrollable surfaces for the right - are you referring to the mail read view in the middle or the Panel that pops on the right for things like settings?

**Comment by MichaelRoger** [comment]
this could be possible. but i still think it would be awesome to have a component that allready sticks these together. perhaps it should just be called **Applicationlayout**.
if i create such a component is it possible to put it into this project?

**Comment by aneeshack4** [comment]
@MichaelRoger This is really a higher order component that's very specific so it doesn't really belong in the component library. We do welcome contributions from you and we want to empower to make and share such HOCs but I'm not sure about adding them back to our component library offering. @dzearing what do you think?
