### ISSUE TITLE
Font and Icon-Font alternative for non-office-related applications

### ISSUE THREAD

**Issue by lukasbash** [microsoft/fluentui#12488]
According to the Assets License, the available MS fonts and icon fonts are only allowed in association with office products or office product integrations.
The licensed fonts and icons are matching the whole UI framework in a decent way. Do you recommend a proper font and icon font as an alternative to the licensed ones?
I know that it is possible to inject custom fonts or icons, but honestly material or font awesome icons do not really reflect the style of an application using this framework.

Any input on this?

**Comment by aneeshack4** [comment]
@lukasbash thanks for reaching out to us. What is it you're trying to do exactly? Please give us more details about your use case - are you trying to make a M365 themed app/website or are you trying use custom icons with Fluent UI components? There is guidance regarding all of this on https://developer.microsoft.com/en-us/fluentui#/styles/web/icons

**Comment by lukasbash** [comment]
@aneeshack4 sorry for the late reply. I am working on an application that simply has a microsoft themed design. The application has nothing to do (or at least not directly) with any office products, applications or plugins.
The license agreement for the assets license says that I am not allowed to use i.e. the default font and icon font.
Of course I am using a custom font and icon font right now. I was just asking, if you (as the development team behind this framework) have a free-to-use alternative font and icon font that also matches the microsoft theme. In my opinion, using e.g. Font Awesome or Material icons just does not fit the style of your components. Do you understand what I mean?

**Comment by ecraig12345** [comment]
Also note that in the latest [assets license agreement](https://aka.ms/fluentui-assets-license) it says that you can use the fonts if you're interacting with any Microsoft service, not just Office. But that obviously won't help in all cases.

**Comment by fromberg100** [comment]
I am also willing to use Fluent UI for an ERP webapplication.  It is a ASP.NET Core web application and will be deployed to Azure virtual machine. Am I allowed to use the Fluent UI font and icons for this purpose?

**Comment by ecraig12345** [comment]
@fromberg100 Per the assets license linked above, you're allowed to use the fonts:

> a. In connection with the use of a Microsoft API within the development of a software
application, website, or product you create or a service you offer designed to provide access
or interact with a Microsoft service or application (“Application”)
> b. To illustrate that Application integrates with one or more Microsoft products and services. 

If you work somewhere with lawyers, further interpretation of exactly how this applies to your scenario is best left up to them. (Sorry to not be more helpful, but I'm not qualified to give legal advice and don't want to say something incorrect.)

**Comment by kakone** [comment]
This licensing problem is annoying. We can't use this great collection of icons in some websites, or even [Uno Platform](https://platform.uno/) applications.
We can now also found [another collection of Fluent UI Icons](https://www.figma.com/community/file/836835755999342788) under [Creative Commons license](https://creativecommons.org/licenses/by/4.0/), so we are a little lost. Will these new icons be included in the [Fabric Icons page](https://uifabricicons.azurewebsites.net/) ? And will the license of the Fabric Icons page be changed so we can use it in a website or application without using a Microsoft API ?

**Comment by paulgildea** [comment]
@lukasbash @fromberg100 @kakone First off, Thank you! This is all great feedback! This gives our team a lot of insight on how you all would like to leverage icons in your solutions. I really appreciate it.

I'm starting a dialog with the teams that manage the [Fluent Icons](https://www.figma.com/community/file/836835755999342788) and [Fabric Icons](https://fabricicons.azurewebsites.net/) to provide some clarity in the short term as well as a long term solution moving forward across all our Fluent UI (Web/React Native, iOS+macOS, Android) control libraries. So bear with us.

In the meantime - I'd like to ask you folks on the types of formats you'd like to use to consume icons? 

1. Font hosted on a CDN?
2. Updated Font creator tool (like the Fabric Icon tool) that you can use to bundle in a custom font?
3. SVG assets that you can bundle in?
4. Other ways or formats you've used to include icons into your experiences?

Thanks again!

**Comment by kakone** [comment]
> In the meantime - I'd like to ask you folks on the types of formats you'd like to use to consume icons?
In priority 4 - With a package manager (npm, ...). The package would contain the SVG assets and the web fonts in various formats (ttf, woff, woff2).
But I think the CDN option is needed too .
I also like the Font creator tool to embed just the icons I need in my application, but it is less necessary than 4 and 1 (I can do custom own font with the SVG assets from the npm package).

**Comment by fromberg100** [comment]
I would go for 2. (Font creator) or 3 (SVG assets) with the purpose my application only uses icons needed.

**Comment by lukasbash** [comment]
For me it would be 4 - web fonts (at least for me there is no need to do this via package manager; I'd simply need the different files).
Still, in my opinion the standard that are used within your framework make such a big part of the design of the framework. There is an open source replacement for the normal font already (Segoe UI -> Selawik), but for me it is actually a show stopper that there is still no "matching" icon font that we can use without interacting with any MS service.

There are a lot of companies and customers that simply want microsoft themed applications, regardless if they use a microsoft service in the background or not. This is also the case for me. No interactions with any service and people keep asking: "Are these the microsoft icons? They look different than the ones on Teams or Dynamics, or ...".

**Comment by paulgildea** [comment]
@lukasbash This is great feedback - I was unaware what [Selawik](https://docs.microsoft.com/en-us/typography/font-list/selawik) existed. Thanks for pointing that out! I'll continue to route this feedback back to the teams. We'll definitely be investigating in this space on delivering a less restrictive solution for icons for web applications. Any more feedback just let us know!

**Comment by kakone** [comment]
For few icons, the alternative was the (ugly) [Symbols web font](https://github.com/Microsoft/fonts).

**Comment by paulgildea** [comment]
@kakone I do have some context around that Symbol font :-) (I worked on WinJS at one point) and yes those icons were designed with a different design language in mind. This is all great context everyone thank you!

**Comment by villuv** [comment]
Would it be possible to separate icons directly related to Microsoft products (file types, office icons etc) and keep them under the asset license and by default include "stardust" icon package that was originally under CC license? 
Main idea is that if a developer follows "getting started" guide, nothing that requires a special license is pulled in behind the scenes. It has to be a conscious decision to include licensed components.

**Comment by paulgildea** [comment]
@villuv This is good feedback. We're investigating a series of solutions here - both short term and long term. I'm following up with the teams that created the original asset license and as a short term solution - determine if we can make any adjustments. 

Long term, the dev experience you call out is what I believe most folks want - we will need to do more coordination with other teams to make that a reality :-).

But what I'm hearing is this folks would like a:
1. UI font with an open license (folks correct me here because we've mainly been talking about icons)
2. Icon solution with an open license (could be a font, could be SVG, could be CDN hosted, could be bundled in, could only include the icons you want)
3. UI font and Icon solutions should be matching/cohesive from a design perspective
4. Getting started should only be pulling in dependencies that have open licenses. Any special licenses should be an explicit opt-in

@lukasbash @kakone @fromberg100 @villuv - Does that sound right? Thumbs up works too :-)

**Comment by kakone** [comment]
It sounds perfect !

**Comment by CodeTao** [comment]
@paulgildea At the very least please provide very clear guidance for how to use Fluent in a way that doesn't risk falling foul of the asset license agreement. Right now it is far from obvious that using the project in its standard configuration may be breaking a license agreement.

**Comment by sgreinert** [comment]
We are also developing a micrsoft ecosystem independent solution (web and client based, client via electron) and thought of fluent UI as the absolute best platform to develop the user experience. But: without fonts and icons, fluent UI won't make sense for us. And unless we will be absolutely safe on using the framework without breaching the license agreement rules, we will have to move on to other frameworks, unfortunately...

**Comment by sgreinert** [comment]
@paulgildea is there a new status on the topic?

**Comment by prajaybasu** [comment]
If Microsoft truly wants to make their Fluent UI design an alternative to Material UI or other design frameworks that are completely open source, then this licensing issue needs to be answered in a proper FAQ document (mentioned in the main README file, preferably at the top) and the package/repository descriptions across the web need to be updated to reflect that Fabric UI is a general purpose UI framework for all React apps, like Material UI and not just for creating Office 365 experiences.

It is not easy to explain to higher ups that the MIT license "should" allow me to use the JS and CSS (without the font/icons) in my application (unrelated to Microsoft or any Microsoft services).

Even if my application is hosted in Azure App Service (completely unrelated app to MS still), I still feel uncomfortable using any fonts or iconography despite @ecraig12345's reply (that doesn't assure legality in any way).

**Comment by sgreinert** [comment]
I suppose we will have to move on to blueprint.js (runner up react framework in our evaluation).

**Comment by GurliGebis** [comment]
Is it safe to assume, that this has gone stale, and nothing will come from it, since no updates has been given for 2 months?
It is a shame if so, if needed, maybe move the Microsoft product icons and what else is IP out into a separate package, that is not included by default maybe?

**Comment by duke7553** [comment]
Google allows their material design icons to be used anywhere. Why can't Microsoft do the same?

**Comment by gautamsi** [comment]
No matter how many name you change for the product it is not going to be adopted widely unless you change the terms of the license (fabric/fluentui asset license). see hoe vscode is being used. You can alternatively provide some home grown open font instead of licensed font, I have had numerous use of this and I come to this repo every few month to check if the license has been relaxed. 

at least create a build process to use some other icon provider with name mapping in a json file with popular library like 

```json
{
 "GlobalNavButton": "FaBars",
"Forward": "FaArrowRight",
}
```
same with a default font, I can use Roboto font, obviously it is not going to fit in overall UX but you are choosing to make it difficult.
this way someone can use

**Comment by paulgildea** [comment]
Thanks for enduring with us folks. 

We've been working internally with our legal team and we've recently published our [quarterly OKRs](https://github.com/microsoft/fluentui/wiki/Fluent-UI-Objectives) on our wiki to begin to be more transparent on what our team is focused on a quarterly basis.

[This quarter](https://github.com/microsoft/fluentui/wiki/Fluent-UI-React-OKRs-Q4-2020) we are focused providing an open source version of our MDL2. I can't guarantee that we'll hit that timeline since we've been really focused on shipping a [Version 8 release
](https://github.com/microsoft/fluentui/issues/12770).

I want to say thanks again for the constructive feedback and our team is learning and improving as we start to become a better run open source project.

**Comment by villuv** [comment]
Might this be related? https://github.com/microsoft/fluentui-system-icons

**Comment by rizkyramadhan** [comment]
> Might this be related? https://github.com/microsoft/fluentui-system-icons

Wow, those are MIT Licensed, how come @fluentui/react doesn't use that by default ?

**Comment by GurliGebis** [comment]
Is there a specific reason for two separate repositories containing icons?

**Comment by rizkyramadhan** [comment]
> Is there a specific reason for two separate repositories containing icons?

I don't know, maybe different teams work on different project producing same sets of icon ?

**Comment by sprocketc** [comment]
It looks like there are two different fluentui mdl2 icon packages
[@fluentui/react-icons-mdl2
](https://github.com/microsoft/fluentui/tree/master/packages/react-icons-mdl2)[@fluentui/react-icons-mdl2-branded](https://github.com/microsoft/fluentui/tree/master/packages/react-icons-mdl2-branded)

The branded package is clearly subject to [Microsoft Fabric Assets License](https://github.com/microsoft/fluentui/blob/master/packages/react-icons-mdl2-branded/LICENSE) according to the README.
The non-branded package does not include this statement and has a different ([MIT](https://github.com/microsoft/fluentui/blob/master/packages/react-icons-mdl2/LICENSE)) license included.

Is it safe to assume that only the branded icons are published under the Microsoft Fabric Assets License?
Protecting their branded icons this way makes sense, but I think we need some clarification about the license of the non-branded set.

**Comment by GurliGebis** [comment]
> 
> 
> It looks like there are two different fluentui mdl2 icon packages
> [@fluentui/react-icons-mdl2 ](https://github.com/microsoft/fluentui/tree/master/packages/react-icons-mdl2)[@fluentui/react-icons-mdl2-branded](https://github.com/microsoft/fluentui/tree/master/packages/react-icons-mdl2-branded)
> 
> The branded package is clearly subject to [Microsoft Fabric Assets License](https://github.com/microsoft/fluentui/blob/master/packages/react-icons-mdl2-branded/LICENSE) according to the README.
> The non-branded package does not include this statement and has a different ([MIT](https://github.com/microsoft/fluentui/blob/master/packages/react-icons-mdl2/LICENSE)) license included.
> 
> Is it safe to assume that only the branded icons are published under the Microsoft Fabric Assets License?
> Protecting their branded icons this way makes sense, but I think we need some clarification about the license of the non-branded set, that contains the following note
> `Usage of the fonts and icons referenced in Fluent UI React is subject to the terms listed at https://aka.ms/fluentui-assets-license`

Since the license state MIT, it would be safe to assume that is what license it uses. (If not, then there would never be a way to trust licenses, if the license file is misleading).
https://github.com/microsoft/fluentui/blob/master/packages/react-icons-mdl2/LICENSE

**Comment by sprocketc** [comment]
> > It looks like there are two different fluentui mdl2 icon packages
> > [@fluentui/react-icons-mdl2 ](https://github.com/microsoft/fluentui/tree/master/packages/react-icons-mdl2)[@fluentui/react-icons-mdl2-branded](https://github.com/microsoft/fluentui/tree/master/packages/react-icons-mdl2-branded)
> > The branded package is clearly subject to [Microsoft Fabric Assets License](https://github.com/microsoft/fluentui/blob/master/packages/react-icons-mdl2-branded/LICENSE) according to the README.
> > The non-branded package does not include this statement and has a different ([MIT](https://github.com/microsoft/fluentui/blob/master/packages/react-icons-mdl2/LICENSE)) license included.
> > Is it safe to assume that only the branded icons are published under the Microsoft Fabric Assets License?
> > Protecting their branded icons this way makes sense, but I think we need some clarification about the license of the non-branded set, that contains the following note
> > `Usage of the fonts and icons referenced in Fluent UI React is subject to the terms listed at https://aka.ms/fluentui-assets-license`
> 
> Since the license state MIT, it would be safe to assume that is what license it uses. (If not, then there would never be a way to trust licenses, if the license file is misleading).
> https://github.com/microsoft/fluentui/blob/master/packages/react-icons-mdl2/LICENSE

The added note at the bottom the license is what makes me uncomfortable. This note is part of the license file, which means that the included icons might still be subject to different terms, despite the fact that the rest of the code is MIT.

**Comment by ecraig12345** [comment]
@sprocketc You're correct, the `@fluentui/react-icons-mdl2` package of SVG icons is fully MIT licensed. There's a [note on the website](https://developer.microsoft.com/en-us/fluentui#/styles/web/icons#fluent-ui-react-svg-based-icons) clarifying this now.

The branded SVG icons are available from `@fluentui/react-icons-mdl2-branded` which is still subject to the [assets license](https://aka.ms/fabric-assets-license). @tomi-msft we should add a note about the branded package on the website.

**Comment by DL444** [comment]
> @sprocketc You're correct, the `@fluentui/react-icons-mdl2` package of SVG icons is fully MIT licensed. There's a [note on the website](https://developer.microsoft.com/en-us/fluentui#/styles/web/icons#fluent-ui-react-svg-based-icons) clarifying this now.
> 
> The branded SVG icons are available from `@fluentui/react-icons-mdl2-branded` which is still subject to the [assets license](https://aka.ms/fabric-assets-license). @tomi-msft we should add a note about the branded package on the website.

If the SVG icons are fully MIT licensed, then we should probably remove the last line of that license that states:

> Note: Usage of the fonts and icons referenced in Fluent UI React is subject to the terms listed at https://aka.ms/fluentui-assets-license

I agree with @sprocketc that this added note is confusing, and it is arguable whether a modified MIT is still MIT at all.

**Comment by sprocketc** [comment]
@ecraig12345 Thanks for the clarification!

Although this is good news, people still face a lot of font related issues when they try to use this framework
- The document [here](https://developer.microsoft.com/en-us/fluentui#/styles/web/icons) states that the Fluent UI font-based icon set is released under the Microsoft Fabric Assets License. Since the documentation suggests using the `iconName` property, it looks like we either need a new icon font based on `@fluentui/react-icons-mdl2` or the license of the icon font needs to be changed.
- Some of the icons listed on the [Fluent UI Icons tool](https://uifabricicons.azurewebsites.net/) are missing from some packages. All of the monoline icons should be available to all icon packages.
- Without modifications, the framework is trying to load Segoe UI and the icon font if you call the `initializeIcons` method. As a result, users might end up violating the license without even noticing. Loading the fonts from a cdn by default, is also questionable, but probably not within the scope of this discussion.
- As @DL444 said, the license file should be updated. The license of the package supersedes our discussion, and the ambiguous note is still there.

In general, the default behavior should be modified to conform with the ΜΙΤ license, or an alternative build process should be provided, like @gautamsi suggested.

As much as I love this framework, the truth is that you made it hard for us to choose fluentui. 
People have to spend too much time just to figure out if they are allowed to use fluentui, which defeats the core purpose of a framework.

**Comment by MichielDeMey** [comment]
> > @sprocketc You're correct, the `@fluentui/react-icons-mdl2` package of SVG icons is fully MIT licensed. There's a [note on the website](https://developer.microsoft.com/en-us/fluentui#/styles/web/icons#fluent-ui-react-svg-based-icons) clarifying this now.
> > The branded SVG icons are available from `@fluentui/react-icons-mdl2-branded` which is still subject to the [assets license](https://aka.ms/fabric-assets-license). @tomi-msft we should add a note about the branded package on the website.
> 
> If the SVG icons are fully MIT licensed, then we should probably remove the last line of that license that states:
> 
> > Note: Usage of the fonts and icons referenced in Fluent UI React is subject to the terms listed at [aka.ms/fluentui-assets-license](https://aka.ms/fluentui-assets-license)
> 
> I agree with @sprocketc that this added note is confusing, and it is arguable whether a modified MIT is still MIT at all.

We're currently in the same situation. The Note in the MIT license for the SVG icons is really concerning.

Have we gotten any clarification on this?   
Ideally, the note should just be removed since any and all icons in the package are MIT licensed?

The note however still makes sense for the branded icons.

**Comment by tomi-msft** [comment]
I have removed the mention of the Fabric Assets License from the react-icons-mdl2 LICENSE file

**Comment by GurliGebis** [comment]
How do we go about the normal font? It is still restricted, so out of the box, the Segoe UI font still prevents usage from how I can understand it?

**Comment by GurliGebis** [comment]
Please reopen this one - it has not been solved yet

**Comment by Owez** [comment]
Whats the current state of this issue?

I can't use fluent if a ton of the assets are behind a legal wall and I don't want to use iffy workarounds. 2 years.

**Comment by GurliGebis** [comment]
I think the safe bet is to stay away, until Microsoft decides it is time fix this.
But after this long, I don't think it will be fixed

**Comment by GurliGebis** [comment]
And again, please reopen.
This has not been resolved yet.

**Comment by khmakoto** [comment]
@GurliGebis reopening

**Comment by Owez** [comment]
Please reopen again

**Comment by gautamsi** [comment]
it is not solved, please reopen

Please provide instruction on how to use this without being restricted or change license from MIT to some proprietary license which extends MIT with restriction you are proposing. That will at least turn away anyone who innocently used this thinking it is MIT licensed.

**Comment by khmakoto** [comment]
Reopening

**Comment by GurliGebis** [comment]
Still an issue, but does it make sense to keep reopening it?
It seems pretty clear, that this is an issue that won't get fixed.

**Comment by gautamsi** [comment]
I believe after the v9, if you use `@fluentui/react-icons` this is MIT but if you use any of the MDL2 package it will be fabric assets. 

This is the time where Microsoft should publish a clear Guide that if you include xxxx packages you are governed by the Fabric asset license and not MIT. 
Other problem is that they never make it separable? hope they have clear guide soon,.
