### ISSUE TITLE
Fabric Stack component bug

### ISSUE THREAD

**Issue by dhruv93** [microsoft/fluentui#12480]
### Environment Information

- **Package version(s)**: 7.98.3
- **Browser and OS versions**: Microsoft Edge 80.0.361.69 / Windows 10 10.0.18363 Build 18363

#### Repro Steps:
1. Go to https://beta.support.xbox.com/
2. Sign-In with valid credentials
3. Click on "More" button in the action item notifications section of Home page
4. Click "F12" to open the developer tools. Ensure it is aligned right of the window (not at the bottom of the page)
5. Enable Device toolbar
6. Close the F12 developer tools widow
7. Observe the action item notifications got aligned improperly

![ezgif com-optimize](https://user-images.githubusercontent.com/905630/77964575-233abe00-7294-11ea-96ee-b521c23acea1.gif)

#### Actual behavior:

Card's content not aligned properly when we open and close the device toolbar.
The horizontal prop doesn’t seem to always change whenever the value is updated. The value is a Boolean which checks if screen width is greater than a fixed width or not. 

#### Expected behavior:

Card's content should align properly

**Comment by aneeshack4** [comment]
@dhruv93 This is not the xbox repo or support endpoint. This is not actionable for us. As the issue template says, you must create a Codepen to repro any bug on an isolated Fluent component alone.
