### ISSUE TITLE
Please reopen issue #12424

### ISSUE THREAD

**Issue by achang0406** [microsoft/fluentui#12491]
@aneeshack4 closed the #12424 when its not fully addressed. Please reopen.

Just to clarify, when an option has been selected in a dropdown and when a user focuses on the dropdown (while its collapsed). The narrator will fail to read the selected item.

Please see below for a reference of the issue #12424 
------------------

Environment Information
Package version(s): Office-ui-fabric-react ^7.0.0
Browser and OS versions: chromium Edge Version 80.0.361.69
Describe the issue:
Using the CommandButton component to create a dropdown. When a value is selected for the dropdown, the narrator will read "selection contains 0 items" even though an item is selected.

turn on narrator
focus on dropdown
select a value in the dropdown
refocus on the dropdown while its collapsed
observe
Please provide a reproduction of the issue in a codepen:
https://codepen.io/NomNoms/pen/PoqywVG

Actual behavior:
the narrator reads "selection contains 0 items" even though an item has been selected.

Expected behavior:
narrator should acknowledge there are items selected in the dropdown component.

Documentation describing expected behavior
A11Y MAS guideline
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7b54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7d&cid=d3faf69f-e509-48bc-9833-b320268ef176

@jgage176

**Comment by aneeshack4** [comment]
@achang0406 I believe this is the correct behavior to only announced selection when expanded... because by definition, when collapsed the items inside the dropdown are not selected. I looked at the MAS guidance you linked and it doesn't anything substantial about this... do you have any other guidance that states this behavior should be otherwise?

**Comment by aneeshack4** [comment]
Just reopened the original so we can keep discussing this there so we have continuity.
