### ISSUE TITLE
[List] Is there a better estimation than _estimatedPageHeight in _updateRenderRects?

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#12490]
### Environment Information

- **Package version(s)**: 7.88.1
- **Browser and OS versions**: Chrome 80.0.3987.149

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/xinychen/pen/xxGBVKX

* Scroll the scrollbar (slowly) to the bottom and see what happens.
* Note that I've set `getPageSpecification` property.

#### Actual behavior:
Note there is a tall item with 10000px height. Scroll to the next page, but the page is not triggered to render.
![test](https://user-images.githubusercontent.com/50703224/78038296-44d49c00-739f-11ea-90d8-12a65cdbe87c.gif)

#### Expected behavior:
Change the tall item into 2000px height, and you can see the items in the next pages.
![test](https://user-images.githubusercontent.com/50703224/78038010-df80ab00-739e-11ea-9bef-3e3f9cf2fc0c.gif)

I think the following estimation is causing page rendering not triggered when it supposed to. This issue can be prominent if the height of pages are dramatically different from each other. My suggestion is that perhaps we can use some height related to viewport (such as `this._allowedRect`) that won't be affected by the items in the list.

https://github.com/microsoft/fluentui/blob/ee761dace1bb944941eb0ca3500f4cbee7f9b49c/packages/office-ui-fabric-react/src/components/List/List.tsx#L1022

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@chenxinyanc Thanks for reaching out to us with a codepen and repro steps and possible fix! I'm having trouble understanding the issue though - is it that when you scroll to the bottom, you are seeing a blank and not the smaller green rows? Because I don't repro this:
![image](https://user-images.githubusercontent.com/4161791/78093951-f02e2280-7398-11ea-9413-18fd26da8552.png)

**Comment by chenxinyanc** [comment]
Sure. There are items after the 10000px-item. If you scroll just pass the 10000px one, you should be seeing blank space when you are supposed to see the following items.

I'm not sure but from your screenshot, you seems to keep staying before the 10000px item. Have you dragged the scroll bar (slowly) pass this item?

I'm reproducing this on Chrome and FF on Windows 10.

**Comment by aneeshack4** [comment]
@chenxinyanc That was meant to be a video recording showing that I scrolled all the way to the bottom - not just before the 10000px item and reached the green boxes with no problem (dragging it slowly). Here it is: https://im5.ezgif.com/tmp/ezgif-5-88c5238f3020.mov

**Comment by chenxinyanc** [comment]
I think there is one second there is nothing rendered after this tall item. I'm not sure but what if you just stay there and do not scroll down anymore? To make this bug easier to reproduce, I've reduced the items after the tall item and perhaps you can try the codepen again.

![image](https://user-images.githubusercontent.com/50703224/78209730-6a19f500-74da-11ea-89d3-018b441beba7.png)

The tricky part is that if you scroll down really fast across the second page, it will trigger render anyway (I'm not sure how this difference can happen, for now,).
![test](https://user-images.githubusercontent.com/50703224/78210038-7783af00-74db-11ea-9483-9273818b0044.gif)

**Comment by aneeshack4** [comment]
@chenxinyanc With your changed code, I don't see the green rows now at all - even if I scroll really fast. This seems really intermittent/trivial/very specific conditions needed to be perfectly honest. Also changing that estimation might break a lot of other things and we're currently pausing further development on List. So I don't think we can address this.
