### ISSUE TITLE
I build a starter for admin application

### ISSUE THREAD

**Issue by siminture** [microsoft/fluentui#12511]
I like this set of components and styles very much, but they're really not very friendly in terms of using introductions and samples.

The  [official starter](https://github.com/microsoft/create-react-app-uifabric.git)  looks too simple and does not contain any features, so i build a starter for admin application.

https://github.com/siminture/fluentui-starter

**Features**
- Configurable Route based on react-router-dom
- Authentication Component and Login Page based on react-hook-form
- Sidebar Layout, the nav items read from routeConfig

**Comment by siminture** [comment]
Here is a screenshot.
![Dashboard Dark](https://github.com/siminture/fluentui-starter/blob/master/screenshots/dashboard_dark.PNG)

**Comment by aneeshack4** [comment]
@siminture Thanks for reaching out to us with this feedback. Are you looking to contribute this template back into our repo? If so, we don't currently have a place for templates (in the create-react-app starter or somewhere else afaik) but let me talk with my team and see what our plans are for something like that. Or were you thinking of doing something else with this?

**Comment by siminture** [comment]
@aneeshack4 Thank you for your reply, I would like to contribute to this stater to developers using FluentUI
