### ISSUE TITLE
When entering space in date picker, date defaults to previously selected date but still shows date as invalid

### ISSUE THREAD

**Issue by abigaelonchiri-msft** [microsoft/fluentui#12518]
### Environment Information

- **Package version(s)**: fabric version 7.39
- **Browser and OS versions**: all browsers

### Please provide a reproduction of the bug in a codepen:

Code Pen: https://codepen.io/pen/?&editable=true

#### Actual behavior:

When we set DatePicker to allow text input. If user enters space as the date, the date picker defaults to the previously selected date but still shows the Date as Invalid

#### Expected behavior:

When entering space in date picker, it defaults to the previously selected date but shows the date picker as invalid

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@abigaelonchiri-msft This doesn't repro: https://codepen.io/aneeshack4/pen/jOPoxee
Type space, press enter -> it shows previously selected date, nothing about invalid.

**Comment by abigaelonchiri-msft** [comment]
@aneeshack4 Thanks for the quick reply, to repro: Type space and click outside checkbox, enter works but clicking outside doesn't.

**Comment by aneeshack4** [comment]
@abigaelonchiri-msft space and click outside also doesn't show anything about invalid.
