### ISSUE TITLE
Narrator reads page's title before Dropdown's contents

### ISSUE THREAD

**Issue by v-aavega** [microsoft/fluentui#12525]
### Environment Information

- **Package version(s)**:  7.105.7
- **Browser and OS versions**:  Chrome, Windows 10

### Bug reproduction:
- Go to https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown
- Open narrator app in Windows
- Tab until you get to a drop down:
![image](https://user-images.githubusercontent.com/63079579/78312182-d19a6980-7507-11ea-8e51-c7507d448be4.png)
- Open drop down using space or enter before narrator finishes

### Actual behavior:
- Before narrator reads contents of drop down, it reads the page's title contents "Home - Fluent UI"

### Expected behavior:
- Narrator should not read page's title contents.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Manage payments (in AMC and North Star).

**Comment by aneeshack4** [comment]
@v-aavega This is not a bug - Narrator, on any page, will read out page's title contents first before reading thing it's currently focused on (but in subsequent, as in if you keep tabbing to the next control, it won't re-read which is correct behavior). If you don't like that, contact Narrator with feedback not this repo - this is not the Narrator repo.

**Comment by aneeshack4** [comment]
More proof of no repro:
![image](https://user-images.githubusercontent.com/4161791/78416882-54dbbe00-75e1-11ea-80ff-5b53c0a54090.png)
