### ISSUE TITLE
seeing errors when changing dropdown box selection

### ISSUE THREAD

**Issue by lzl124631x** [microsoft/fluentui#12524]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^7.105.8",
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
![image](https://user-images.githubusercontent.com/5824517/78312017-4620d880-7507-11ea-8ef5-45432f11b337.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@lzl124631x We can't do anything with just a screenshot of the error message - you need to follow the issue template and actually provide a codepen with an isolated repro on the component by itself and detailed repro steps.

**Comment by lzl124631x** [comment]
@aneeshack4  The errors/warnings are just telling us don't use those deprecated APIs. 

https://github.com/microsoft/fluentui/search?q=UNSAFE_componentWillReceiveProps&unscoped_q=UNSAFE_componentWillReceiveProps

seems you are migrating those APIs. Maybe just need some time.

And these are just warnings and should be fine for now.
