### ISSUE TITLE
How can I change the color of the separator control?

### ISSUE THREAD

**Issue by sergiosanchezd** [microsoft/fluentui#12534]
Hi,

I want to change the color of the separator control (https://developer.microsoft.com/en-us/fabric#/controls/web/separator) but everything that I'm trying doesn't work.
Thanks in advance!

**Comment by aneeshack4** [comment]
@sergiosanchezd I've tried several things to set the color of the line in [this codepen](https://codepen.io/aneeshack4/pen/QWbRrRJ) but no luck. I did have luck when I hardcoded a color in the Separator.styles.file [on this line](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/Separator/Separator.styles.ts#L57).
![image](https://user-images.githubusercontent.com/4161791/78401167-bdb13f00-75bd-11ea-9c68-9ff2a99c29b3.png)
In this line, `backgroundColor` of the `::before` is set to `theme.palette.neutralLighter`. You can use our theming utility `Customizations.applySettings' and pass in a custom color to `neutralLighter` like I did in [this codepen](https://codepen.io/aneeshack4/pen/JjdqZbE) to set the Separator line to red. (which is from our theme designer site https://aka.ms/themedesigner).

**Comment by sergiosanchezd** [comment]
Thanks! Nice examples and documentation! I suggest to include these examples on the documentation.
