### ISSUE TITLE
Dropdown list doesn't account for Loading message when some items are present

### ISSUE THREAD

**Issue by pompomon** [microsoft/fluentui#12538]
### Environment Information

- **Package version(s)**: 0.47.
- **Browser and OS versions**: Edge Chromium and MacOS Mojave 10

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/fluent-ui-example-nnvm7

Video in the attachment
[DropdownLoadingBug.zip](https://github.com/microsoft/fluentui/files/4428659/DropdownLoadingBug.zip)

Repro:
  * Open codesandbox link https://codesandbox.io/s/fluent-ui-example-nnvm7
  * Navigate to dropdown using keyboard navigation
  * Open the list and navigate to the bottom using down arrow

#### Actual behavior:
Dropdown size doesn't account for loading message element in the list

#### Expected behavior:

Dropdown size should account for loading message

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by jurokapsiar** [comment]
Tracking Reference: 7401 (used for team planning)
