### ISSUE TITLE
Command bar doesn't resize properly when on a flex child with flex-grow

### ISSUE THREAD

**Issue by PatoBeltran** [microsoft/fluentui#12540]
# Environment Information

- **Package version(s)**: 7.76.2

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/PatoBeltran/pen/GRJaBGg?editors=0110

#### Actual behavior:

When the command bar has a bunch of items and also some  overflow items, if the command bar is inside an element that is size using a `flex-grow: 1` (basically taking the whole space available), when resizing, the command bar doesn't resize properly.

If you resize the screen in the codepen provided you will see that a scroll bar appears, if I set the container to overflow hidden, the command bar will just be cutout.

#### Expected behavior:

The command bar should resize properly and put items in overflow when there's not enough space to render them.

### Priorities and help requested:

Requested priority: High

Products/sites affected: IoT Central

**Comment by aneeshack4** [comment]
@PatoBeltran Thanks for reaching out to us. I see this reproing but I believe this is because of how you're using flexbox - flex-grow is just really weird as explained in [this post](https://css-tricks.com/flex-grow-is-weird/): "A flex container distributes free space to its items (proportionally to their flex grow factor) to fill the containers, or shrinks them (proportionally to their flex shrink factor) to prevent overflow." You'll have to mess around with flexbox but there should be another way to set the parent child relationship between the container and content such that it doesn't mess with the overflow.

**Comment by PatoBeltran** [comment]
hey @aneeshack4, thanks for your answer... while I agree with you about this behavior of flex-grow, I find it a bit weird that the component knows to resize a couple of times but then stops. If the issue was purely how flex-box handles sizing, wouldn't the action bar component never put element's in overflow because the size would never be smaller than all the items?

**Comment by PatoBeltran** [comment]
Also, I noticed that the `ms-OverflowSet ms-CommandBar-primaryCommand` is using this same technique to size it's content... therefore if this is the issue, that container should also include a `min-width: 0` to make sure flex is not making this container bigger than it should.

**Comment by aneeshack4** [comment]
Tagging component owners @micahgodbolt @joschect - y'all have any ideas on if `min-width: 0` is appropriate here of if there's another workaround or fix?

**Comment by micahgodbolt** [comment]
anything inside of a resize group needs to be block level....if it shrinks to fit the given space, the resize group will keep it shrunk.

**Comment by JustSlone** [comment]
@PatoBeltran, does this answer your question, are you unblocked here?

**Comment by PatoBeltran** [comment]
@micahgodbolt this doesn't talk about children of the resize group, but when the resize group itself is a children of a flex item. The `min-width: 0` approach that @aneeshack4 suggests seems to fix the issue in the codepen, but it doesn't work on our page.

Our site is a bit more complex than that so I'm working on getting a consistent repro that showcases the issue we are facing.

**Comment by behowell** [comment]
Hi @PatoBeltran, it looks like this issue has been stale for a few months. It appears that it might be possible to fix the issue on your end, based on micahgodbolt and aneeshack4's comments. I'm going to close this issue, but if you feel there's still a product bug and have a new repro where the workaround doesn't work, feel free to re-open. Thanks!
