### ISSUE TITLE
DX: office-ui-fabric-react/src/components import not published modules

### ISSUE THREAD

**Issue by NikitaIT** [microsoft/fluentui#12544]
#### Describe the feature that you would like added
Add `office-ui-fabric-react/src/components/*.ts` to npm.
Types in `node_modules/office-ui-fabric-react/src/components/**/*.types.ts` like `node_modules/office-ui-fabric-react/src/components/SearchBox/SearchBox.types.ts` import `import { IButtonProps } from '../../Button';` but `../../Button`  not published.

#### What component or utility would this be added to

To npm.

#### Additional context/screenshots

If go to impl like:
![image](https://user-images.githubusercontent.com/16810067/78451468-8ced0a80-768e-11ea-8541-1606ad7db6a7.png)
File `node_modules/office-ui-fabric-react/src/components/SearchBox/SearchBox.types.ts` opened.
But IButtonProps not exists.

**Comment by joschect** [comment]
@NikitaIT Could you provide a little bit more information about what you're trying to do? What does your configuration look like right now?

**Comment by NikitaIT** [comment]
@joschect 
Setup:
```bash
npm install @fluentui/react
```

Create .tsx like this:

```ts
import {
  TagPicker,
} from '@fluentui/react';
export const exemple: any = () => <TagPicker onResolveSuggestions={() => []} />;
```
If I `ctrl+click`(go to definition) on `onResolveSuggestions`, definition is `src\components\pickers\BasePicker.types.ts` as expected.
But:
![image](https://user-images.githubusercontent.com/16810067/78924221-142cea80-7aa2-11ea-8a84-c8ecfb202eb0.png)

This is due to the absence of files .ts at this level in npm:
![image](https://user-images.githubusercontent.com/16810067/78924751-062b9980-7aa3-11ea-8f96-8d36cd9b47d6.png)

It would be great if all src files were available in npm as is. Each time to find out how to use it, need to check the github repository or less often the documentation to find out how to use the library.

**Comment by joschect** [comment]
@NikitaIT Thanks for clarifying! I built a react app using create-react-app and having a template set to `typescript` then I installed fluentui as you mentioned above. I did need to do `yarn` and `yarn build` but I am unable to reproduce the same behavior that you're seeing. I don't see any red lines and I can navigate between type files. 

What version of typescript are you using? Maybe there is a difference in version that's impacting this.

![image](https://user-images.githubusercontent.com/20801176/78947568-92759680-7a7a-11ea-9d46-c8982440b263.png)

![image](https://user-images.githubusercontent.com/20801176/78947584-9f928580-7a7a-11ea-80b0-780e3a55878f.png)

![image](https://user-images.githubusercontent.com/20801176/78947590-a4573980-7a7a-11ea-8bc0-80f8c2970f96.png)

**Comment by NikitaIT** [comment]
@joschect My typescript version is 3.8.3. My monorepo was at 3.7.5, but in this version there is a bug with recursive types, which is why the ui-fabric generated a lot of compilation errors. 
Maybe I will check the build on an empty project, but not now, for now I will close it issue.

**Comment by NikitaIT** [comment]
@joschect 
Here is a toy configuration in which I run into this problem too. https://github.com/NikitaIT/boilerplate/tree/sort-ui
`$ lerna bootstrap` and go to `node_modules/office-ui-fabric-react/src/components/SearchBox/SearchBox.types.ts`
