### ISSUE TITLE
JAWS reads entire dialog content thrice on Chrome browser.

### ISSUE THREAD

**Issue by anusm14** [microsoft/fluentui#12541]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

#### Actual behavior:
Start JAWS screen reader.
Focus on Dialog component in browser - chrome.
Observe the announcement, along with header, other components are read thrice.

#### Expected behavior:
Everything on dialog should be read once

**Comment by aneeshack4** [comment]
@anusm14 This doesn't repro on Narrator & I don't have access to JAWS - but since it doesn't repro on one AT, it's probably an issue with the other not the actual Fabric component especially because we're following the ARIA spec. Please reach out to JAWS.
