### ISSUE TITLE
TagPicker remove selected item

### ISSUE THREAD

**Issue by jedmonsanto** [microsoft/fluentui#12545]
how to remove selected item in TagPicker? tried some of remove in BasePicker but no luck of removing the selected items

**Comment by joschect** [comment]
@jedmonsanto  I'm a little confused by your question, how are you trying to remove the selected items? could you provide a codepen example? Here's a [starter pen](https://codepen.io/slimemold/pen/BaNXLMZ?editable=true) to help you get started.

**Comment by jedmonsanto** [comment]
@joschect imagine you have the items Member where you store your selected items 
![image](https://user-images.githubusercontent.com/23548643/80303174-0df87700-87e1-11ea-9080-e7edcc90bbe4.png)

My question is do you have a direct a specific Member to remove the 'black' from the snip above, i can't find any Member in the implementation that could trigger an event to update my items. I expect maybe you have something like onRemoveItem Member that i can manipulate...

As of this moment, i used the Members below to my TagPicker
![image](https://user-images.githubusercontent.com/23548643/80303345-5a908200-87e2-11ea-9334-e24bd803e4a9.png)
