### ISSUE TITLE
Dialogs/Modal can move off-screen via keyboard

### ISSUE THREAD

**Issue by SavannahBourgeois** [microsoft/fluentui#12565]
### Environment Information

- **Package version(s)**: All
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:
Using the Blocking Dialog example on your test page (https://developer.microsoft.com/en-us/fluentui/#/controls/web/dialog). If you check the IsBlocking box and open the dialog, you can open the keyboard only menu using Ctrl+Alt+Space (you can see this implemented in the underlying Modal code). If you select "move" from those options you can then use the arrow keys to move the dialog. 

#### Actual behavior:

There is nothing stopping a user from moving a dialog completely offscreen. The user could then exit keyboard move and not be able to see any of the content and become lost.

#### Expected behavior:

We restrict moving the dialog off screen.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority:  Normal

Products/sites affected: Office Online

**Comment by joschect** [comment]
@SavannahBourgeois Thanks for the submission! I am having a little trouble bringing up the keyboard only menu, could you confirm the operating system and browser that you're using?

**Comment by SavannahBourgeois** [comment]
@joschect yeah it is a little tricky since all of the buttons execute on "space" and dismiss the dialog. The best way I've been able to bring it up is to:
1. ensure that the IsDraggable checkbox is checked 
2. use the Blocking Dialog example 
3. open the dialog via keyboard 
4. hold down ctrl+alt and then tap space
Then you should be able to see the menu in the top left of the dialog. I don't think the OS or browser should make a difference otherwise there is a bigger bug in the dialog/modal code to not bring up a menu required for accessibility but just in case, I am using 
Chrome: Version 80.0.3987.163 
Windows: 10 version 1909 OS Build 18363.720

**Comment by joschect** [comment]
@SavannahBourgeois Thanks for clarifying! I can see that behavior that you're talking about. I am unable to reproduce it using ctrl + alt and space, but I can get close by just dragging and dropping towards the edge. It's clear there is no protection for moving the dialog outside of the visible area.

I am not sure if this is a bug or expected behavior. @jspurlin do you know how it's expected to behave?

**Comment by jspurlin** [comment]
@joschect, dialogs should not be allowed to be moved off screen. That creates a poor user experience and we should make sure it doesn't happen

**Comment by joschect** [comment]
Great! I'll mark this as a bug and we can start working on a fix.

**Comment by Dalimil** [comment]
@joschect Any updates on this? We would need to limit our users from moving dialogs off-screen.
