### ISSUE TITLE
Facepile showing fullname if single persona

### ISSUE THREAD

**Issue by vikramdadwal** [microsoft/fluentui#12564]
### Environment Information
Latest version
- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

When providing only single persona value the name is appearing on the right side 

#### Expected behavior:

Only persona icon should be displayed 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by joschect** [comment]
Hi @vikramdadwal could you add a codepen as to where you're seeing this? I don't see it reproduced in the examples. Here's a [codepen](https://codepen.io/slimemold/pen/BaNXwMO?editable=true) to get you started
![image](https://user-images.githubusercontent.com/20801176/78617237-a2e40200-782b-11ea-8d8b-7ba4c9aa4f27.png)
