### ISSUE TITLE
Unable to render js styles in App component

### ISSUE THREAD

**Issue by vsheshag** [microsoft/fluentui#12570]
export const appComponentStyles = {
    "button, input, optgroup, select, textarea": {
        fontFamily: FontFamily.fontFamilyNormal,
        lineHeight: "20px",
    },
    "html": {
        "boxSizing": "border-box",
        "height": "100%",
        "backgroundColor": Color.colorAppBackground,
        "fontFamily": FontFamily.fontFamilyNormal,

        "body": {
            color: Color.colorBody,
            height: "100%",
            overflow: "hidden",
            display: "flex",
            flexDirection: "column",
            fontSize: FontSize.fontSizeS,
            lineHeight: "20px",
            letterSpacing: "0",
            ...msLayer,
            ...msMessageBar,
        },
   },
};

const App = () =>
    <Customizer
        scopedSettings={{
            App: { styles: appComponentStyles },
        }}
    >
        <HashRouter>
            <Provider store={store}>
                    <ShellContainer />
            </Provider>
        </HashRouter>
    </Customizer>;

The styles are not rendered as defined in js files in App component.

**Comment by joschect** [comment]
Hey @vsheshag could you confirm that you're using the App from examples-app-base? And if possible, please make a codepen or codesandbox to help us track down the problem.

**Comment by vsheshag** [comment]
Yeah, Somewhat similar. But the styling for html and body tag differ. Let me use same body tag styling like **':global(body)':**. Thanks for letting me know this App example from  examples-app-base. Let me give a try to render html and body tag css elements in App.tsx file in my project.

Question: There is no root css class in my existing App.tsx for rendering, where in I can embed html and body tags as selectors. How can we apply all styles of App.styles.ts to App.tsx without reference to any classNames. Here is the example link for reference. I gave a try on this approach but it did not work . https://github.com/microsoft/fluentui/issues/11547

![image](https://user-images.githubusercontent.com/3715520/78859564-5415b280-7a4d-11ea-8212-c1fcae2c3669.png)

**Comment by joschect** [comment]
@vsheshag Let me see if I understand, are you trying to place styles on body and html? Or is there another problem? For targeting specific components you can use customizer. Here is an [example](https://codepen.io/slimemold/pen/VwvwdLo?editors=0010)
