### ISSUE TITLE
Hosted Panel animation jank when headerText is present

### ISSUE THREAD

**Issue by agg23** [microsoft/fluentui#12585]
### Environment Information

- **Package version(s)**: 7.105.6 and prior. 7.105.7 introduced a regression that causes the animation issues regardless of the presence of `headerText`

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/agg23/pen/LYVwavB

#### Actual behavior:

With version 7.105.6 and prior, a hosted panel (`hostId` passed to the Panel's Layer) pushes the entire body of the page to the left while animating in. This appears to be tied to the scrolling functionality of the body, but shouldn't happen regardless, particularly if the Panel is anchored in a non-scrolling parent.

In 7.105.7, #12195 was fixed, which causes this issue to occur persistently.

#10918 discussed this issue inherently, but no resolution was found at the time.

#### Expected behavior:

We should expect that the animation handles smoothly regardless of the hosting div, within reason. In this scenario in particular, where the host div is static, I would expect no changes in scrollbars whatsoever.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by joschect** [comment]
@agg23 Thanks for submitting this issue and including the codepen! I can see the behavior that you're experiencing. We'll look into a bug fix!

**Comment by lidermanrony** [comment]
I'm seeing the same issue. Is there any ETA for a fix?

**Comment by agg23** [comment]
Checking in, as this is blocking several `Panel` scenarios.

**Comment by levymsft** [comment]
This also happens with DetailPanelV2
