### ISSUE TITLE
StackItem does not use its `padding` token

### ISSUE THREAD

**Issue by louiebert** [microsoft/fluentui#12592]
### Environment Information

- **Package version(s)**:  office-ui-fabric-react v7.105.11

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/louiebert/pen/zYvOvKK

#### Actual behavior:

StackItem does not render its padding provided in `tokens` prop.

#### Expected behavior:

StackItem does render its padding provided in `tokens` prop.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

### Likely fix

Add a new line for `padding` just below `margin` in [StackItem.styles.ts:23](https://github.com/microsoft/fluentui/blob/c17546f70711f4f2926fc3ab47b6a8c70cfdbf59/packages/office-ui-fabric-react/src/components/Stack/StackItem/StackItem.styles.ts#L23)

**Comment by joschect** [comment]
@louiebert Thanks for submitting this as an issue and including that codepen. This is definitely reproducible and is a bug. We'll get this fixed!

**Comment by stratospheres** [comment]
@joschect - any update on this? We might have a workaround, but it's fairly ugly. We'd love to get this fix...
