### ISSUE TITLE
Top level export positioning utilities

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#12591]
### Environment Information

- **Package version(s)**: ^7.105.7
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

Looks like I have to reference the full file path to use some of the positioning utilities. This is inconsistent with the way I'm used to importing stuff from Fabric.

![image](https://user-images.githubusercontent.com/17346018/78704260-73cba000-78c0-11ea-8055-a7e646a6dc2b.png)

#### Expected behavior:

I should be able to import these from the top level 'office-ui-fabric-react';

### Priorities and help requested:

Are you willing to submit a PR to fix? No.

Requested priority: Normal

Products/sites affected: M365 Admin Controls

**Comment by dzearing** [comment]
Please do not import internal details with full paths. This is not supported. 

However, I am seeing that `Callout.ts` is missing an export of these utilities.

```tsx
export * from './utilities/positioning/index';
```

@joschect Should this be exported? Or is it exported somewhere else?

**Comment by joschect** [comment]
@dzearing Looks like it was just missed. That should probably be exported from the index in src.

**Comment by southpolesteve** [comment]
Just ran into this as well when migrating from the old package to the new @fluentui/react package. `Position` is no longer exported from the top level, but is used in props. SpinButton for example.

**Comment by ecraig12345** [comment]
This was fixed at some point during the version 8 release prep. In both v7 and v8, you can now do `import { Position } from '@fluentui/react'` or `import { Position } from '@fluentui/react/lib/Positioning'` (also works with `office-ui-fabric-react` in v7).
