### ISSUE TITLE
Getting error while running /apps/fabric-website

### ISSUE THREAD

**Issue by jurijsk** [microsoft/fluentui#12609]
I'm getting some errors from `sass` regarding missing files on the freshly cloned repo, while following instructions from [~/apps/fabric-website](https://github.com/microsoft/fluentui/tree/0b0df50c68ee6996f39470c308af8a0eb9b24f81/apps/fabric-website).

After some poking around and running `yarn builddemo` on the root I got an error regarding missing `@uifabric/experiments` and after `yarn build  @uifabric/experiments` or maybe just `yarn build` everything finally worked.

I can either suggest to include `yarn build` to building instructions or update build script to make everything run smoothly.

### Environment Information

- **Package version(s)**: 7.0.0.0 according to package.json but more likely 7.105.13

#### Actual behavior:

error on `yarn start`
```
PS ~\fluentui\apps\fabric-website> yarn start
yarn run v1.22.0
$ just-scripts dev
 ■ started 'dev'
 ■ started 'clean'
 ■ Removing [lib, temp, dist, lib-amd, lib-commonjs, lib-es2015, coverage, src\**\*.scss.ts]
 ■ finished 'clean' in 0.01s
 ■ started 'copy'
 ■ Copying [index.html] to 'C:\Projects\fluentui\apps\fabric-website\dist'
 ■ Copying [src\**\*.json] to 'C:\Projects\fluentui\apps\fabric-website\lib'
 ■ finished 'copy' in 0.17s
 ■ started 'sass'
 x Error detected while running 'sass'
 x ------------------------------------
 x src\components\Table\Table.module.scss: Error: File to import not found or unreadable: ../../dist/sass/References.
 x ------------------------------------
 x finished 'dev' in 1.67s with errors
```

#### Expected behavior:

no error would be nice

### Priorities and help requested:

Are you willing to submit a PR to fix?
Yes, if some one can provide directions on how to approach the fix.

Requested priority: Minor

**Comment by joschect** [comment]
@jkovzels Thanks for the submission! We made some changes to our build system and it's likely that we'll need to update the instructions on the apps/fabric-website information. 

Just to confirm it sounds like you got things working by running  `yarn build` at the root. Is that the case?

**Comment by jkovzels** [comment]
@joschect Thanks for replying. I think both `yarn build` and `yarn build @uifabric/experiments` are required to make it work.

**Comment by joschect** [comment]
Good to know! Thanks @jkovzels

**Comment by ecraig12345** [comment]
Closing since a lot of build things have changed and this is probably no longer relevant.
