### ISSUE TITLE
Optional chaining not working with esnext

### ISSUE THREAD

**Issue by patrickgalbraith** [microsoft/fluentui#12601]
### Environment Information

- **Package version(s)**: 7.105.11
- **Node version**: 12.16.0
- **Browser and OS versions**: n/a

#### Actual behavior:

The default option for `tsconfig.json` is for the `target` option to be set to `esnext`. 

```
{
  "compilerOptions": {
    "target": "esnext",
    ...
  }
}
```

Optional chaining was added in ES2020. So if your 'target' compile option is ES2020 or ESNext, then typescript compiler will see an optional chaining operator and leave it alone. If your target is ES2019 or further back then typescript will transpile the feature.

So when transpiling using `esnext` you get this error:

```
Module parse failed: Unexpected token
```

It might be worth defaulting the `target` option to `es2019`.

#### Workaround:

Set target in `tsconfig.json` to something less than es2020/esnext, like es2019, es2015, etc...

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

**Comment by joschect** [comment]
@patrickgalbraith Thanks for the submission! Which tsconfig.json are you referring to? Just the general one in office-ui-fabric-react? Is there a way that I can reproduce this and see it locally to test it out?

@kenotron and @dzearing for visibility.

**Comment by patrickgalbraith** [comment]
Hi @joschect 

If you create a new app using `npm init uifabric` then add some code to `src/App.tsx` that uses optional chaining (something like below):

```
const test: string[] | null = null;
test?.map(() => {});
```

Now usually this should fall-through to babel and if using `@babel/plugin-proposal-optional-chaining` it should work, but it doesn't seem to work when I use it and I haven't dug into how you have it all configured to know what is going on exactly.

**Comment by patrickgalbraith** [comment]
As to which `tsconfig` I'm not sure. It is the one that is placed in the root of the app when using `npm init uifabric`.

**Comment by joschect** [comment]
@patrickgalbraith Thanks for clarifying! We've actually recently started to move away from npm init uifabric and have started moving towards using react-create-app instead. You can see this [pr here](https://github.com/microsoft/fluentui/pull/12465) has started moving us in that direction. There is a recent task to update the quickstart guide so that we can have consistent guidance across our repo.
