### ISSUE TITLE
On focus, only input part should be selected in case of TextField with suffix.

### ISSUE THREAD

**Issue by Harkesh030679** [microsoft/fluentui#12605]
On focus, only input part should be slected in case of TextField with suffix.

### Environment Information

OS : Windows 10 
Browser: Chrome.

### Describe the issue:

On focus, only input part should be selected in case of TextField with suffix.

### Please provide a reproduction of the issue in a codepen:
Pls see in prefix and suffix example
https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield
You can see in below link
https://codepen.io/anubhutisaini/pen/oNjvERY?editable=true

#### Actual behavior:

On focus, input part and suffix part are selected in case of TextField with suffix. Means , suffix part also selected(displayed border) on focus.

#### Expected behavior:

On focus, only input part should be selected in case of TextField with suffix. suffix part should not be highlighted on focus.

**Comment by xugao** [comment]
We had a similar issue: #7935. The right experience might be not including the suffix inside the focus border since the suffix is technically not getting any focus. we should ping @betrue-final-final to confirm. 

@Harkesh030679 -  may I ask why you raised this issue? what confusion is it bringing to your users?

**Comment by betrue-final-final** [comment]
I don't find this to be a usability issue, and it is coded to the original design.

**Comment by Harkesh030679** [comment]
No other issue, This is similar to #7935, you can close my issue.
