### ISSUE TITLE
Command bar button selection status not exposed via aria, or visible in HC mode

### ISSUE THREAD

**Issue by BrendanMcK** [microsoft/fluentui#12606]
### Environment Information

- **Package version(s)**: 7.105.11
- **Browser and OS versions**: any (inc. current EDGE on Windows)

### Describe the issue:

Checkable buttons in commandbars - those with canCheck=true and checked=true/false - show visually with a hightlight, but:
* don't have expected role of menucheckboxitem or have aria-checked attribute
* don't have selection visuals in High Contrast mode
* have very light selection state - perhaps should be more visually distinct?

### Please provide a reproduction of the issue in a codepen:

codepen repro:

https://codepen.io/brendanmckeon/pen/abvoYvZ

Visuals:
![image](https://user-images.githubusercontent.com/1754373/78781300-d66e7b80-7954-11ea-97e7-7da994abbac3.png)

DOM ends up containing:
```
<button type="button" role="menuitem" class="ms-Button ms-Button--commandBar is-checked ms-CommandBarItem-link root-58" aria-label="Bold" data-is-focusable="true" tabindex="0">
```

Expect this to have `role="menubaritemcheckbox" aria-checked="true"`.

#### Actual behavior:

Command Bar items with checked=true do appear visually distinct from those without this, but don't expose expected a11y semantics.

#### Expected behavior:

Expect correct aria role, aria-selection value, and High Contrast behaivior

### Documentation describing expected behavior

https://www.w3.org/TR/wai-aria-practices/#menu

**Comment by joschect** [comment]
@BrendanMcK Thanks for the submission! Regarding the first problem of aria-checked not being added properly, that is due to "checked" being used for styles for the underlying button, rather than explicitly for being "checked". That is exceedingly confusing as it's not documented anywhere and I'll be making a change to the docs to clarify.

The underlying button will have the appropriate aria-checked property if you pass through either "checkbox" or "menuitemcheckbox" via role. You can see that working in this modified version of the [codepen](https://codepen.io/slimemold/pen/YzyKmVB) that you made. 

Regarding the high contrast styles, that is a bug and there will need to be a fix put in for that.

**Comment by BrendanMcK** [comment]
Thanks!

Re:

> The underlying button will have the appropriate aria-checked property if you pass through either "checkbox" or "menuitemcheckbox" via role.

Could the control be updated so that it sets the role itself based on `canCheck`?

Typical pattern for accessibility is that either:

* the calling code sets higher-level semantic properties on the control (eg `checked`, `canCheck`), and then the control manages all its own ARIA HTML attributes,

or

* the calling code passes in all the necessary low-level ARIA attributes and the control just passes them through as-is.

It would seem somewhat unusual/nonstandard to split the responsibility here, so that setting `role` then indirectly causes `aria-checked` to start working. It's usually expected that if some piece of code sets `role`, it has to supply the related `aria-` attributes at the same time.

**Comment by joschect** [comment]
@BrendanMcK that's not a bad idea. I think it wouldn't be too bad of a fix to have that happen automatically in the commandbar. 

@micahgodbolt Do you have any objections to have canCheck automatically add the menuItemCheckbox role to the button in commandbar?

**Comment by micahgodbolt** [comment]
its a reasonable change, i don't think it'd have much negative effect.

**Comment by ramdmeno** [comment]
When can we expect a fix for this ?
