### ISSUE TITLE
Why we set the min-width of DetailsList to the calculated row width?

### ISSUE THREAD

**Issue by nodew** [microsoft/fluentui#12607]
https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx#L107

I try to put the DetailsList into a flexbox, when the width grows, it works well, but when the width of container decrease, it will break the flexbox because it set the min-width to the realwidth of current container.

**Comment by joschect** [comment]
@nodew thank you for the submission. That particular line does not appear to set the min-width, the totalwidth is memoized and returned and it's possible that stays static as your container changes size. Could you provide a codepen to help me see the problem? Here's a [codepen](https://codepen.io/slimemold/pen/OJyLKWL?editable=true) to help you get started.

**Comment by nodew** [comment]
Here is an [examle](https://codepen.io/sirqiao/pen/zYvYvYx), try to click the toggle button multiple times.

**Comment by joschect** [comment]
@nodew Awesome! Thanks for the codepen. That really clarifies the problem. I can see the behavior that you're experiencing and that does seem like a bug. I'll investigate why we do that and see if there is some kind of fix.

**Comment by savkelita** [comment]
We have the same problem here. @nodew Did you find any temporary solution for this ? @joschect When are you planning to fix this? Thanks!
