### ISSUE TITLE
PeoplePicker: Not resolving suggestions on initial run when seeded with suggestion text

### ISSUE THREAD

**Issue by ernadeau** [microsoft/fluentui#12612]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "^7.70.0",
- **Browser and OS versions**: Microsoft Edge Version 83.0.474.0 (Official build) dev (64-bit)

### Please provide a reproduction of the bug in a codepen:

We are using PeoplePicker component via `NormalPeoplePickerBase`. With our scenario, we want to pre-populate the picker with a text string, using the `inputProps.defaultVisibleValue` parameter. When doing this, our `onResolveSuggestions` callback is not called until a key press happens. If the PeoplePicker is seeded with an initial value, I would expect `onResolveSuggestions` to be called on initial use (similar to how `onEmptyResolveSuggestions` is called if the initial configuration is empty). Furthermore, `onEmptyResolveSuggestions` is not called if `inputProps.defaultVisibleValue` is set.

Note -- I'm not quite sure if this is a bug, or a feature request.

#### Actual behavior:

With PeoplePicker component,  `onResolveSuggestions` callback is not called when an initial value is provided using the `inputProps.defaultVisibleValue` parameter.

#### Expected behavior:

With PeoplePicker component,  `onResolveSuggestions` callback should be called initially when an initial value is provided using the `inputProps.defaultVisibleValue` parameter.

### Priorities and help requested:

Are you willing to submit a PR to fix? Maybe, depending on the nature of the fix

Requested priority: Normal (I'm not sure what these priorities are defined as, but this is blocking our team's feature)

**Comment by joschect** [comment]
@ernadeau This is a known issue. It's something that we've thought about adding more support for but haven't had the time to expand. It's probably time to look at refactoring how suggestions get pulled in for the picker. I'm going to make this the issue that we work through and close the other older dupe.

**Comment by ernadeau** [comment]
Awesome - Thank you for all your help here Jon! Great to see this fix checked in, looking forward to trying it out in Fluid!

________________________________
