### ISSUE TITLE
Label using color, content and Icon: Warning: Failed prop type: Invalid prop `styles` supplied to `Icon`

### ISSUE THREAD

**Issue by jacargentina** [microsoft/fluentui#12619]
Repro here: https://github.com/jacargentina/my-app.git
Clone, then `yarn install && yarn start`

Got this:

```
Warning: Failed prop type: Invalid prop `styles` supplied to `Icon`.
    in Icon (created by Label)
    in Label (at App.js:8)
    in div (created by Provider)
    in ThemeProvider (created by Provider)
    in RendererProvider (created by Provider)
    in Provider (at App.js:7)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)
```

**Comment by joschect** [comment]
@jacargentina Thanks for submission. To help us understand, could you provide a few more details about the particular set of instructions that you were following?

**Comment by jacargentina** [comment]
@joschect I don't quite understand what u are asking me; if you are talking about the documentation I've followed, is this one https://fluentsite.z22.web.core.windows.net/components/label/definition

**Comment by joschect** [comment]
Here's a [codesandbox](https://codesandbox.io/s/fluent-ui-example-y824n?file=/example.js) which I think demonstrates the problem. "Exit" isn't an icon. For a list of available icons go to [here](https://fluentsite.z22.web.core.windows.net/components/icon/definition)

**Comment by jacargentina** [comment]
@joschect I'm not using "Exit"; but "error", which IS a valid icon; please look again!

**Comment by joschect** [comment]
@jacargentina My mistake. I cloned your repo, built it, and everything works as expected 
![image](https://user-images.githubusercontent.com/20801176/78948343-ca7dd900-7a7c-11ea-9c55-06a2e4836336.png) . All I did after cloning was run `yarn && yarn build && yarn start `

**Comment by jacargentina** [comment]
It works yes, but the warning is on the console, the issue is about that warning

**Comment by joschect** [comment]
@jacargentina Thanks for bearing with me. I understand. The issue is in labelStyles (see screenshot of the code). It's returning false.

Fluent v0 is still iterating quickly and it's already been fixed and changed. You can see this [pr](https://github.com/microsoft/fluentui/pull/12549) for more information. If you update versions and change the way that you're passing the icon in it should work as expected.
![image](https://user-images.githubusercontent.com/20801176/79013355-68c17b80-7b1d-11ea-9d33-4485fcb96f75.png)

**Comment by jacargentina** [comment]
@joschect how do I ** If you update versions**

**Comment by joschect** [comment]
@jacargentina Once a new version of React-Northstar is published you should be able to run `yarn upgrade --latest` and it will update the versions. You can check for new releases [here](https://github.com/microsoft/fluentui/releases). 

In the short term if you just want the warning to go away you can do something like `<Label icon={{name='error', onClick={()=>{}}/>` That will force Label to pass a correct style object down to icon. 

You can also ignore the warning for right now as well. From what I can tell all styling should work as expected until you're able to upgrade.

**Comment by jacargentina** [comment]
`<Label icon={{name: 'error', onClick: {()=>{}} />` produces warning too; but I think I can close this now as I've got it: it just works, but produces a warning.
