### ISSUE TITLE
onSelectionChanged should provide exact changes as arguments

### ISSUE THREAD

**Issue by lukasbash** [microsoft/fluentui#12627]
#### Describe the feature that you would like added

The `onSelectionChanged` callback of the Selection class should provide detailed changes for the actual trigger of the event. It makes sense to get a "diff" of the current to the previous selection.
If I want to track the state for e.g. other components, ajax requests, and many more, I always have to compare (or at least clean) my current set and apply all current selected items by using the `getSeletion` method of the selection model.
To avoid this I would expect changes for selected/unselected items to be passed as an argument.

The interface could look like:

```ts
interface IChanges {
  selected: Item[];
  unselected: Item[];
}

...

onSelectionChanged: ({ selected, unselected }) => {
  // sync my local/global state stuff, but avoid iterating over everything
}
```

#### What component or utility would this be added to

Selection

**Comment by joschect** [comment]
@lukasbash Thanks for the suggestion. I believe that selection is supposed to serve as it's own "source of truth" to help prevent there from being multiple places that selection state is kept. That said I know we have gotten at least one similar request to this before so it might be time to start branching out with selection. @dzearing might be able to chime in again.
