### ISSUE TITLE
[SelectionZone] Prevent selection for all clickable components

### ISSUE THREAD

**Issue by lukasbash** [microsoft/fluentui#12621]
#### Describe the feature that you would like added

Prevent the selection for all clickable components that are rendered in a selection zone.
Currently there is a flag that only works based on a [check for HTML tags](https://github.com/microsoft/fluentui/blob/920722dbeecc26fbab35dd48f477bc71cc282c10/packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx#L322).
If I render e.g. a Dropdown, the selection is still triggered.

It could be possible to implement this by using either the tab-index property of the node.
I discovered this by using a DetailsList with a Dropdown in a column.

It is really important to get this done, because otherwise I cannot render any custom control inside a table column.

#### What component or utility would this be added to

SelectionZone

**Comment by joschect** [comment]
Hi @lukasbash you should already be able to do this! There is a data-selection-disabled which will prevent selectionzone from interacting with any element. Here's an [example codepen](https://codepen.io/slimemold/pen/MWaWXZz) that I think demonstrates what you want!

**Comment by lukasbash** [comment]
@joschect Thank you for your fast reply!

I saw this attribute already on your documentation page with all the DetailsList variations.
This flag also disables the actual selection, right? Because the use-case is to only disable a selection when clicking on a component. Clicking on plain text, as well as on the checkbox should still select the row.

Am I right here, that this is probably a missing feature? Why would you then implement the mentioned code to check for actual HTML elements?

**Comment by joschect** [comment]
@lukasbash I'm a little confused as to what you're looking to do. Based on the initial question it seems like you want to disable selection only for the dropdown so when it's clicked, selection does not occur but that selection will still occur if other parts of the row are selected. 

`data-selection-disabled` disables selection when clicking on a component, you can still select the entire row. To clarify a bit more, it only disables selection for the specified component and its contents. So in [the codepen I linked](https://codepen.io/slimemold/pen/MWaWXZz) you can see that clicking on the dropdown with `data-selection-disabled` does not select the entire row, while clicking on the other not. Additionally you can still select the entire row by clicking on the checkbox or on other non-dropdown elements.

If it's not working as you'd expect still could you make or modify the codepen to help illustrate what you're trying to achieve?

**Comment by lukasbash** [comment]
@joschect Okay, I actually think your codepen clarified the situation for me, I did not understand that the HTML attribute has to be set on a per component basis, I thought it happens for the whole row.
Thank you for the clarification!
