### ISSUE TITLE
Northstar's Dropdown does not stop propagation of the ESC key and arrow keys

### ISSUE THREAD

**Issue by davyrwoo** [microsoft/fluentui#12634]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.47.0

### Describe the issue:

When typing in a searchable Dropdown, clicking the ESC key should clear the search (which it does).

However, if the Dropdown is a child to a component that also has ESC key behavior, the ESC key event bubbles to the parent component. For example, if the Dropdown is in a Dialog, the ESC key clears the Dropdown and closes the Dialog.

Also, when Dropdown is child of Accordion, arrow keys keydown events propagation cause the accordion panels to switch.

### Please provide a reproduction of the issue in a codepen:

https://codesandbox.io/s/fluent-ui-example-z43bn

1. Click 'Open a dialog'
2. Start typing in the dropdown search
3. Press the ESC key

#### Actual behavior:

The Dropdown clears and the Dialog closes

#### Expected behavior:

The dropdown should clear without the Dialog closing

**Comment by jurokapsiar** [comment]
updated title and description to reflect propagation problem with arrow keys as well

**Comment by jurokapsiar** [comment]
Tracking Reference: 7399 (used for team planning)
