### ISSUE TITLE
Narrator reads page's title before Dropdown's contents while opening

### ISSUE THREAD

**Issue by v-aavega** [microsoft/fluentui#12632]
### Environment Information
- **Package version(s)**:  7.105.7
- **Browser and OS versions**: Chrome, Windows 10

### Bug reproduction
- Go to https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown
- Open narrator app in Windows
- Tab until you get to a drop down:
![image](https://user-images.githubusercontent.com/63079579/78932135-d86f3200-7a5b-11ea-8f7b-00074626197c.png)
- Open drop down using space or enter before narrator finishes

#### Actual behavior:
- Before narrator reads contents of drop down, it reads the page's title contents "Home - Fluent UI"

#### Expected behavior:
- Narrator should not read page's title contents.

### Priorities and help requested:
Are you willing to submit a PR to fix? No
Requested priority:  High
Products/sites affected: North Star/Manage Payments

**Comment by joschect** [comment]
@v-aavega Thanks for submitting this! I can reproduce this. We'll get this added as a bug and I'll start working on a fix.
