### ISSUE TITLE
Nav does not select the correct option according to the current url

### ISSUE THREAD

**Issue by TonyTroeff** [microsoft/fluentui#12633]
I have the following basic nav where 'Category' is the default selected option:
![image](https://user-images.githubusercontent.com/33567383/78937649-85c46300-7ab9-11ea-9598-a073462791d2.png)

This is the code for configuring the two options:
```Typescript
{
    key: 'categories',
    name: 'Categories',
    icon: 'AllApps',
    url: '/Categories'
},
{
    key: 'tags',
    name: 'Tags',
    icon: 'Tag',
    url: '/Tags'
}
```

However, whenever the url is 'localhost/Tags', nothing happens.
![image](https://user-images.githubusercontent.com/33567383/78938007-1dc24c80-7aba-11ea-9444-7e4f8e95b4f1.png)

If I remove the `initialSelectedKey`, it works but only if the url is exactly the same.
![image](https://user-images.githubusercontent.com/33567383/78938056-3b8fb180-7aba-11ea-81c8-6415c4ac3ee5.png)

You can see that if 'tags' starts with a lower letter, no option is selected.
![image](https://user-images.githubusercontent.com/33567383/78938109-52ce9f00-7aba-11ea-8a31-7f339a29011f.png)

### Environment Information

- **Package version(s)**: 7.106.0
- **Browser and OS versions**: Photos are taken in Brave but this is tested on Chrome and Firefox as well. Windows 10

#### Expected behavior:

Case-insensitive url comparison (or at least an option through which this can be configurable).
Option to capture all urls that start with the provided one. For eexample - 'tags/123', 'tags/create', 'tags/delete' and so on.

**Comment by joschect** [comment]
@TonyTroeff Thanks for the submission! I can see that being confusing. I can also see in the code that it does only do a case sensitive comparison. We could maybe add a callback to allow the user to pass in a comparison function that will handle the `isLinkSelected` behavior. This would also allow the user to handle more complicated cases. @dzearing do you have any thoughts about this?

In the short term you can control the selected nav item with `selectedKey` and you could probably write a small wrapper that will control the nav and ensure that you can use any method you want to get the currently selected key based on the url
