### ISSUE TITLE
Wrong gaps between Stack items in RTL mode

### ISSUE THREAD

**Issue by kamil7x** [microsoft/fluentui#12644]
### Environment Information

- **Package version(s)**: "@fluentui/react": "7.106.0"

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/kamil7x/pen/rNOaNEe

#### Actual behavior:

When in RTL mode, margins set by `childrenGap` does not mirror, so first item does not have any margin, but is rendered as right-most item and stick to second item.

#### Expected behavior:

Stack should not only reverse display order, but also mirror values for `childrenGap` property

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

**Comment by dzearing** [comment]
This seems like a legit bug. Adding @khmakoto
