### ISSUE TITLE
TextField: Need a way to bind extra data to a textField element.

### ISSUE THREAD

**Issue by raj-crec** [microsoft/fluentui#12640]
#### Describe the feature that you would like added

Need a way to bind data to a textfield element ( e.g. column index of a text field in a details-list ). Can't use state for the same, as state is for the entire detailsList.

#### What component or utility would this be added to

TextField

#### Have you discussed this feature with our team, and if so, who

Nope

#### Additional context/screenshots
Textfield is one of the cells of a details-list. Once user modifies value inside the textfield, I need to know which column the textField lies in.

**Comment by joschect** [comment]
@raj-crec thanks for the question! There are already several ways that you can do this. One way you can use the column renderer as in [this example](https://codepen.io/slimemold/pen/XWmJpBb?editors=0011). You could also data-attribute down to the textfield and include the index there.

**Comment by raj-crec** [comment]
Hi @joschect ... I had tried using the data-attribute within textfield like this: <TextField ... data={index} .../>, and tried getting the same in the onBlur() handler, using 'event.target.data', and event.target.getAttributeNames/getAttributeNodes('data'). However, these values were undefined. Finally, I put the index in class-name ( works but not correct, I know ), and then extracting the same from event.target.className. Was I using 'data' in a wrong manner ?

**Comment by raj-crec** [comment]
I also tried event.target.getAttribute('data'), but what I got was null.

**Comment by joschect** [comment]
It should be fine to use event.target.getAttribute(<attributeName>) if you want. It might have been that we only allow through `data-<other text>` named attributes. I've modified the [codepen](https://codepen.io/slimemold/pen/XWmJpBb?editors=0011) to have an example that uses a `data-attribute-id` and gets that via target.

**Comment by raj-crec** [comment]
Thanks @joschect ! This worked for me !
