### ISSUE TITLE
DetailsRow - cellStyleProps prop now passed to getClassNames

### ISSUE THREAD

**Issue by sgbdev** [microsoft/fluentui#12648]
### Environment Information

- **Package version(s)**:  office-ui-fabric-react 7.105.12
- **Browser and OS versions**: Chrome: Version 80.0.3987.163 (Official Build) (64-bit), Microsoft Windows Version 1903 Build 18362.657

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/sgbdev/pen/zYvxKYo

#### Actual behavior:
When passing cellStyleProps to DetailsList, list cells still have default padding, while column headers use padding from cellStyleProps.

Column Header Padding
![image](https://user-images.githubusercontent.com/34309778/79007890-323e2d80-7b2a-11ea-9227-f9f52531ae7d.png)

DetailsRow Padding
![image](https://user-images.githubusercontent.com/34309778/79008008-73ced880-7b2a-11ea-9951-f3146e8257e2.png)

After doing some digging it looks like the DetailsRow.base.render method does not pass cellStyleProps to the getClassnames function. cellStyleProps is being passed to DetailsRow from the DetailsList.base._onRenderCell method.

#### Expected behavior:
DetailsRow should pass cellStyleProps to getClassNames function like it is in DetailsColumn.

### Priorities and help requested:

Are you willing to submit a PR to fix? Maybe?

Requested priority: Normal

Products/sites affected: None known

**Comment by joschect** [comment]
@sgbdev Thanks for the submission! I see the behavior you're talking about. I believe you're correct that the issue is in DetailsRow.base. It certainly gets the correct styles passed to it, but the styles are then never passed down to the `DetailsRowFields` component. One example of that lack of data being passed down are [these lines](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx#L246-L255)

@KevinTCoughlin I think it should be fine to pass the styles down. It's clear that `DetailsRowFields` is expecting those styles.

**Comment by KevinTCoughlin** [comment]
> @sgbdev Thanks for the submission! I see the behavior you're talking about. I believe you're correct that the issue is in DetailsRow.base. It certainly gets the correct styles passed to it, but the styles are then never passed down to the `DetailsRowFields` component. One example of that lack of data being passed down are [these lines](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx#L246-L255)
> 
> @KevinTCoughlin I think it should be fine to pass the styles down. It's clear that `DetailsRowFields` is expecting those styles.

Seems like a legitimate bug with a straightforward fix. I don't expect a problem so long as the styles do not mutate unnecessary across renders.

https://github.com/microsoft/fluentui/blob/9e3c7c7d4b92e132820cdbcd61a667829c712ecb/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowFields.tsx#L31

**Comment by joschect** [comment]
@KevinTCoughlin Sounds good. I'll add this to our list to get it queued up for a fix.

**Comment by sgbdev** [comment]
@joschect I would be happy to submit a PR for this, if it would expedite it?

**Comment by KevinTCoughlin** [comment]
Strange the bot didn't autoclose this

**Comment by cliffkoh** [comment]
The closure of issues after a PR that fixes the issue is merged is handled by GitHub. GitHub didn't kick in here because the PR in question did not use a closing keyword properly (it explicitly hyperlinked to this issue rather than just # reference the issue number).
