### ISSUE TITLE
Wiki homepage has a dead link

### ISSUE THREAD

**Issue by mic-max** [microsoft/fluentui#12658]
### Environment Information

- **Package version(s)**: master branch
- **Browser and OS versions**: Edge 83.0.461.1

Wiki page: https://github.com/microsoft/fluentui/wiki
#### Actual behavior:
Links to `https://github.com/microsot/fluentui/blob/master/README.md#using-fabric-react`

#### Expected behavior:
Links to `https://github.com/microsoft/fluentui/blob/master/README.md#using-fabric-react`

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, I just couldn't find where the source of the wiki pages is located in the repository 😔

Requested priority: Low

Products/sites affected: I think just the github wiki, unless that markdown is being published elsewhere too..

**Comment by dzearing** [comment]
Thank you, fixed!
