### ISSUE TITLE
Fluent Nav Styles - classNames does not exist and causes issues

### ISSUE THREAD

**Issue by ParadimeWeb** [microsoft/fluentui#12659]
### Environment Information

- **Package version(s)**: current
- **Browser and OS versions**: IE 11

### Please provide a reproduction of the bug in a codepen:
in the nav style here:
https://github.com/microsoft/fluentui/blob/master/packages/fluent-theme/src/fluent/styles/Nav.styles.ts

Look at line 15:
'.${classNames.compositeLink}:hover &': {

There is a variable, classNames, that is used but it does not exist. Strangely enough, it only affects IE 11. It ends up added this style: :hover link-123 which puts a background color on all links.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
Looking through some old Nav issues and cleaning things up a bit--it's not clear to me from the description what the repro steps are for this issue. If this is still an issue for you, could you provide detailed repro steps and a repro link either on our website or in a codepen? (Although the codepen site doesn't work in IE 11, there's a backdoor way to test codepens there: write the codepen in another browser, switch to debug view, copy the URL, and paste that in IE 11.)
