### ISSUE TITLE
CommandBar visibility:hidden on SSR

### ISSUE THREAD

**Issue by ksjogo** [microsoft/fluentui#12654]
### Environment Information

- **Package version(s)**: "@fluentui/react": "~7.106.0",

- **Browser and OS versions**: Firefox 75

#### Actual behavior:
Rendering a CommandBar on the server side (with gatsby in this case) leaves `<div style="position:fixed;visibility:hidden" data-automation-id="visibleContent"></div>` around the output. Resulting with a flicker when the browser rerenders.

#### Expected behavior:

CommandBar renders visibly on server side.

---

Looking further into this, it seems that the ResizeGroup is not supporting SSR.

**Comment by joschect** [comment]
@ksjogo Thanks for the submission! Could you confirm that you're seeing the CommandBar renderer briefly before it correctly hides? Or that the CommandBar flickers before it is visible on the page?

**Comment by ksjogo** [comment]
It flickers before it is visible/it flickers in and has no visible output while JS is loading/disabled.
I assume there needs to be some flicker due to the overflow calculations happening, but the generel appearance seems a bit off.

**Comment by joschect** [comment]
@ksjogo Thanks for the confirmation! I reproduced this apparent behavior using next. It's a pretty odd because I can see that the command bar is briefly visible even though it apparently has those styles added. We can look into improving the functionality of SSR for commandbar.

![image](https://user-images.githubusercontent.com/20801176/79513165-03c3c500-7ff8-11ea-88e5-3a90b779a9b6.png)

**Comment by alehuo** [comment]
Facing the same issue. I'm serving an SSR app to the users, and during testing we noticed that the CommandBar is hidden if its rendered server-side.

**Comment by ksjogo** [comment]
I did spin up a [dummy blog](http://johnny.kronberger-spiele.de/) if you want to see the issue happening on page load.

**Comment by ksjogo** [comment]
The issue is still as it is.
