### ISSUE TITLE
Theme.Effects default values need to be updated to Fluent values

### ISSUE THREAD

**Issue by phkuo** [microsoft/fluentui#12650]
The values here: https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/common/_effects.scss
are the incorrect defaults. Now that we're on Fluent, it should be updated to the Fluent values. (Right now it is using MDL2 values.)

**Comment by joschect** [comment]
@phkuo Thanks! We'll get to updating this!
