### ISSUE TITLE
Northstar's Dropdown cannot receive programmatic focus

### ISSUE THREAD

**Issue by davyrwoo** [microsoft/fluentui#12665]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.47.0

### Describe the issue:

Using Northstar's Ref component, we are able to get programmatic focus for components like Button. However, using this method for programmatic focus on the Dropdown component doesn't work, and is needed for accessibility in cases where focus needs to be forced to the component.

### Please provide a reproduction of the issue in a codepen:
https://codesandbox.io/s/fluent-ui-example-7ruk1?file=/example.js

#### Actual behavior:

Focus is not on the Dropdown when the component mounts.

#### Expected behavior:

Focus should be on the Dropdown when the component mounts. In this case, since the Dropdown is searchable, focus should be inside the search.

**Comment by jurokapsiar** [comment]
It is unfortunately not straighforward and related to the render structure of the Dropdown. You need to get a reference of the `input` slot of the `Input` component in the `searchInput` slot :(

```
        <Dropdown
          search
          searchInput={{ input: { children: (C, p) => <Ref innerRef={this.createdRef}><C {...p} /></Ref> } }}
          items={this.inputItems}
          placeholder="Start typing a name"
          noResultsMessage="We couldn't find any matches."
          getA11ySelectionMessage={{
            onAdd: item => `${item} has been selected.`
          }}
```

**Comment by jurokapsiar** [comment]
Verified in codesandbox and it works. Closing, please reopen if you need further clarification.
