### ISSUE TITLE
Screen reader is not reading count of menu items of commandBar in Edge browser

### ISSUE THREAD

**Issue by Harkesh030679** [microsoft/fluentui#12661]
Screen reader is not reading count of menu items of commandBar in Edge browser, working fine in chrome browser.

### Environment Information
OS: Win 10
Browser:  Edge
### Describe the issue:

Screen reader is not reading count of menu items of commandBar in Edge browser, working fine in chrome browser like one of four, two of four, three of four...….

### Please provide a reproduction of the issue in a codepen:

Office fabric link
https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar
Code Pen link
https://codepen.io/Harkesh/pen/XWmbqMd?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

#### Actual behavior:

Screen reader is not reading count of menu items of commandBar in Edge browser, working fine in chrome browser like one of four, two of four, three of four...….

#### Expected behavior:

Screen reader should reading count of menu items of commandBar in Edge browser similar as, working fine in chrome browser like one of four, two of four, three of four...….

**Comment by joschect** [comment]
@Harkesh030679 Thanks for the submission! I checked commandbar and I hear it reading out `one of four` correctly. Could you confirm this is still happening? If it is, could you include what version of windows 10 and edge are you using?

**Comment by Harkesh030679** [comment]
It is working fine in edge latest version i.e.  81.0.416.53 (Official build) (64-bit). Issue exist in lower version of this in edge

**Comment by joschect** [comment]
@Harkesh030679 Thanks for confirming! Given that this is working in a later version of Edge seems likely that this was an edge bug and was unrelated to fabric.
