### ISSUE TITLE
Ref is not pointing to correct component while using styled method

### ISSUE THREAD

**Issue by kangka29** [microsoft/fluentui#12671]
I am using a ref on the wrapper of a connected component where the wrapped component is a styled component using this package.

The ref should point to wrapped instance. However, it is pointing to an element created as an output of the styled method.

### Environment Information

**Package version(s)**:
- react - 16.13.1
- react-redux - 16.13.1
- react-redux - 7.2.0
- redux - 4.0.5
- office-ui-fabric-react - 7.106.0

### Please provide a reproduction of the bug in a codepen:

I have replicated the issue in stackblitz instead of codepen 
Link [here](https://stackblitz.com/edit/ref-styled-component)

#### Actual behavior:

Output of styled method is available in ref.

#### Expected behavior:

The Wrapped component should be available in ref.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: NA

**Comment by joschect** [comment]
@kangka29 Thanks for the submission! 

Unfortunately, for right now at least, this is working as designed. When we first implemented styled the expectation was that another prop would be passed down in place of ref and would be non-framework specific. Internally and on our components we used `componentRef` to ensure that the ref callback made its way to the correct element or component. 

This is something that we should consider changing and we'll get it added to our feature backlog! @dzearing can chime in if he has any immediate ideas.

**Comment by kangka29** [comment]
@joschect 
> Internally and on our components we used `componentRef` to ensure that the ref callback made its way to the correct element or component.

Can you please provide an example for the same?

**Comment by kangka29** [comment]
@joschect 

> Internally and on our components we used `componentRef` to ensure that the ref callback made its way to the correct element or component.

Can you provide an example which matches this scenario?

Thanks in advance.

**Comment by joschect** [comment]
@kangka29 Sure! We actually do provide a utility to help with this if you want to stick with the name `component ref` I modified [your example](https://stackblitz.com/edit/ref-styled-component-jgl6g2) and now it appears to work as you'd expect!

**Comment by kangka29** [comment]
@joschect Thanks a lot. I will check it out, will get back in case of any query.

**Comment by JustSlone** [comment]
Looks like this issue is resolved, if there are any more questions feel free to reopen
