### ISSUE TITLE
Screen reader is reading commandBar options again and again in scan mode in chrome browser.

### ISSUE THREAD

**Issue by Harkesh030679** [microsoft/fluentui#12679]
Screen reader is reading commandBar options again and again in scan mode in chrome browser.

### Environment Information
OS: Win 10
Browser:  Chrome 

### Describe the issue:

Screen reader is reading commandBar options again and again in scan mode in chrome browser.

### Please provide a reproduction of the issue in a codepen:
Pre requisite
1. On narrator(cntr+win+enter)
2. Start scan mode (Capslock+spacebar)
LInk
https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar
Snap
![1760179_Ext](https://user-images.githubusercontent.com/62233836/79206880-98de8680-7e5d-11ea-8425-0c2c9610df1d.png)

Video

[Video Zip.zip](https://github.com/microsoft/fluentui/files/4474318/Video.Zip.zip)

#### Actual behavior:

Screen reader is reading commandBar options again and again in scan mode in chrome browser.

#### Expected behavior:

Screen reader should read commandBar options only once in scan mode in chrome browser.

**Comment by joschect** [comment]
@Harkesh030679 Thanks for the submission! I cannot reproduce this currently. Could you confirm what version of windows and edge you're using?

**Comment by Harkesh030679** [comment]
Please check it in chrome browser. It is working fine in Edge

**Comment by joschect** [comment]
@Harkesh030679 Thanks for clarifying! That was my mistake. I am also not able to reproduce this in Chrome. Could you confirm the version of Chrome that you're on? This is likely a chrome problem

**Comment by Harkesh030679** [comment]
Chrome version is -Version 81.0.4044.113 (Official Build) (64-bit)
Sorry for delay response

**Comment by joschect** [comment]
@Harkesh030679 I just updated to Chrome 81.0.4044.112 and I am still unable to reproduce this. It seems that this is a chrome related problem and is unrelated to fabric.
