### ISSUE TITLE
[Panel] Allow to decide on the direction of the panel

### ISSUE THREAD

**Issue by nirtz89** [microsoft/fluentui#12680]
#### Describe the feature that you would like added

Add a prop that allows you to choose the direction of the panel (left / right).
Should not only be dependent on isRTL.

#### What component or utility would this be added to

Panel

#### Have you discussed this feature with our team, and if so, who

Nope

**Comment by joschect** [comment]
@nirtz89 Thanks for submitting this issue! This is a feature that we could add in the future. For now there are several methods that you can use to achieve the behavior you're looking for.  Recently we added the ability to change RTL through theme which allows you to, through customizer, supply a callback which can let you set RTL via theme. You could use it to move the panel, although you'd also need to wrap the panel content as well so it still appears ltr.

You can also use customNear as the panel type and supply your own width to have the panel appear to the left. Here's a [codepen](https://codepen.io/slimemold/pen/JjYGvmR?editors=0010) with some examples of a near panel.

**Comment by nirtz89** [comment]
> @nirtz89 Thanks for submitting this issue! This is a feature that we could add in the future. For now there are several methods that you can use to achieve the behavior you're looking for. Recently we added the ability to change RTL through theme which allows you to, through customizer, supply a callback which can let you set RTL via theme. You could use it to move the panel, although you'd also need to wrap the panel content as well so it still appears ltr.
> 
> You can also use customNear as the panel type and supply your own width to have the panel appear to the left. Here's a [codepen](https://codepen.io/slimemold/pen/JjYGvmR?editors=0010) with some examples of a near panel.

Thanks! It'll solve the problem for now, but seems like a workaround way of handling it (especially with the need to set the inside of the panel to `ltr` at the end).
I still think it's a needed feature.

**Comment by imcvakt** [comment]
It would be great if that pannel appears from bottom... :)
