### ISSUE TITLE
Invalid value for prop `navigate`

### ISSUE THREAD

**Issue by kamil7x** [microsoft/fluentui#12685]
### Environment Information

- **Package version(s)**: "@fluentui/react": "7.106.0"

### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/kamil7x/pen/mdeewvW
(Codepen's console shows a little different message "Warning: Invalid value for prop %s on <%s> tag.")

#### Actual behavior:

When using Fabric's `<Link>` component as a component for React Router `<Link>`, there is an error in console: 
"Warning: Invalid value for prop `navigate` on <a> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior".

Based on https://github.com/ReactTraining/react-router/issues/6962 it looks like Fabric's `<Link>` passes all (or most of) props to underlying components, like `<a>`.

#### Expected behavior:

There should be no error. 

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by joschect** [comment]
@kamil7x Thanks for the submission! This does look like a problem. Most of our components call `getNativeProps` and use that to help filter out unnecessary props so they don't wind up on native component. 

We'll get this added to our backlog and file it as a bug!

**Comment by ecraig12345** [comment]
Looking back through some old Link bugs--I just tried the codepen and can no longer repro this, so I'm going to resolve the issue.
