### ISSUE TITLE
Underlined/Borderless option for Dropdown (and possibly other inputs as well)

### ISSUE THREAD

**Issue by lukasbash** [microsoft/fluentui#12696]
#### Describe the feature that you would like added

I would like to request two options for the Dropdown component:
- borderless
- underlined

The should make it look the same style as the TextField with these properties.

#### What component or utility would this be added to

Dropdown

#### Additional context/screenshots

Does it make sense to make a "general" underlined/borderless option for all input components?
Like Searchbar, Datepicker, SpinButton, etc.? I actually think so. What is you opinion?

**Comment by joschect** [comment]
@lukasbash Thanks for the submission! This is a feature ask that we've had before. I'm going to close in favor of #10694 and bump that one.
