### ISSUE TITLE
Mirrored Icons in RTL mode

### ISSUE THREAD

**Issue by kamil7x** [microsoft/fluentui#12697]
#### Describe the feature that you would like added

Localization documentation (https://developer.microsoft.com/en-us/fluentui#/styles/web/localization) says that in Fabric Core some icons are mirrored in RTL mode. It would be nice to have same functionality in React components

#### What component or utility would this be added to

Icon, everything that has `iconProps` prop

#### Have you discussed this feature with our team, and if so, who

No, I didn't

#### Additional context/screenshots

Current behavior:

LTR mode:
![image](https://user-images.githubusercontent.com/7629808/79307553-5bc6d280-7ef7-11ea-803b-f67cbdbb01c9.png)

RTL mode:
![image](https://user-images.githubusercontent.com/7629808/79307603-726d2980-7ef7-11ea-831c-3b427d6f9f87.png)

**Comment by joschect** [comment]
@kamil7x Thanks for the submission! This is an interesting feature request. It makes sense that if we know about a specific reverse icon that we could reverse it for you. However, right now our icons are at least somewhat decoupled from their loading, and it would impose a cost, albeit small, to have to load and keep track of all the mirrored icons. 

@ecraig12345 might be able to chime in about possibly supporting this in the future.

**Comment by kamil7x** [comment]
Actually i think it would be simple mapping, like:
```const rtlIcons = {
  arrowDownRight8: "arrowDownRightMirrored8",
  arrowDownRightMirrored8: "arrowDownRight8",
  chevronLeft: "chevronRight",
  chevronRight: "chevronLeft"
  ...
}```

and then inside Icon component:
```getRTL() && rtlIcons[iconName] ? rtlIcons[iconName]: iconName```

**Comment by ecraig12345** [comment]
I'm not really the person to ask here--this is kind of more of a design question. @dzearing do you know the history of why we support auto-mirroring in core but not react? (would ask @Jahnp but I think he's still out)
