### ISSUE TITLE
Allow passing FocusTrapZoneProps to TeachingBubbleProps

### ISSUE THREAD

**Issue by orokanasaru** [microsoft/fluentui#12692]
#### Describe the feature that you would like added

Add IFocusTrapZoneProps.

#### What component or utility would this be added to

TeachingBubbleProps.

#### Have you discussed this feature with our team, and if so, who

Nope.

#### Additional context/screenshots

We are dynamically displaying `TeachingBubble`s based on events in edit heavy scenarios, where the users will not tolerate losing focus while typing. We can already pass `calloutProps` to tweak the focus behavior, but the `FocusTrapZone` will still forcibly steal focus on display. Enabling the callers to pass props through to it will enable is to use this without resorting to unreliable hacks.

**Comment by joschect** [comment]
@orokanasaru Thanks for submitting the issue and creating a fix so quickly! That's really awesome. We'll get that merged.
