### ISSUE TITLE
StackItem does not accept a flexBasis prop

### ISSUE THREAD

**Issue by swese44** [microsoft/fluentui#12694]
#### Describe the feature that you would like added

From the component docs: `A Stack is a container-type component that abstracts the implementation of a flexbox in order to define the layout of its children components.`

For the most part we can use Stack/StackItem without CSS. But if I want 2 columns of differing content width to grow or shrink at the same rate and at the same width, and they have different content, I have to add my own CSS rule with an equal `flexBasis` value to those columns. I would expect StackItem to accept a `flexBasis` prop, or some other abstraction that lets me specify columns that should be equal width.

#### What component or utility would this be added to

StackItem

#### Have you discussed this feature with our team, and if so, who

No

**Comment by joschect** [comment]
@swese44 Thanks for the suggestion! That seems like a good idea and something that won't be difficult to add. We'll get it added to the backlog!

**Comment by divyanshumehta** [comment]
@joschect  any update when this is coming as it seems to a very handy thing.
