### ISSUE TITLE
Sizes for toggle button

### ISSUE THREAD

**Issue by lukasbash** [microsoft/fluentui#12699]
#### Describe the feature that you would like added

I would like to request a property for controlling the size of a Toggle.
I think at least `small`, `medium` and `large` make sense.
Currently the Toggle can only have one size and if I want to control it, I have to override several styles in a hacky way.

#### What component or utility would this be added to

Toggle

**Comment by joschect** [comment]
@lukasbash Thanks for the suggestion! This is a good idea. I know we have discussed possibly adding sizes to Buttons overall and it would make sense that we would want to add size to toggle as well. I believe that is still in the design phase right now. We'll make sure to have toggle get size too!

**Comment by JustSlone** [comment]
This has been addressed in the new ToggleButton component see here: https://react.fluentui.dev/?path=/docs/components-button-togglebutton--default

closing this, thanks for the feedback!
