### ISSUE TITLE
Migration guide from @fluentui/react 0.44 to 7

### ISSUE THREAD

**Issue by hisuwh** [microsoft/fluentui#12707]
#### Describe the feature that you would like added

It seems suddeny FluentUI react and UI Fabric (whatever that is) have merged and the versions jumped from 0.44 to 7.  With this a bunch of components seem to have disappeared:
- Flex
- Box
- Header
- Loader
- Form
- Segment

Plus a bunch of interfaces leading to a number of build errors if I try to upgrade.  There does not seem to be a migration guide at all for how to replace these missing components.

#### What component or utility would this be added to

Wiki/documentation

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/4470351/79367025-0f09e880-7f45-11ea-97f8-bedc0ffec718.png)

**Comment by joschect** [comment]
@hisuwh Thanks for the submission! Sorry for the confusion. We announced the merger [here](https://developer.microsoft.com/en-us/office/blogs/ui-fabric-is-evolving-into-fluent-ui/) but we don't have links to it on our github yet! I'll get those added.

in the meantime, you don't need to switch immediately, this is a long term plan and Fluent is still in the V0 stage. You don't need to migrate from fluent to fabric if you're not ready. We are planning more down the road and aim to have migration tools to help assist the migration in the future!

If you have any suggestions or comments there is this issue [here](https://github.com/microsoft/fluentui/issues/12288) to help us keep track!

**Comment by dzearing** [comment]
We have continued the `@fluentui/react` v0 work under the package name `@fluentui/react-northstar`. While it is still a v0 and will still undergo breaking changes, you're welcome to switch imports to that. We are working to convert v0 and v7 code in future releases.

**Comment by hisuwh** [comment]
I've got dependabot set up on my repo so I've got a failing PR for this 😆 But I will hold off updating then.  Are those components likely to be ported across at some point then?

Can I access the original fluent-ui documentation anywhere?

**Comment by dzearing** [comment]
Yes you can access the docs for northstar components: https://aka.ms/fluent-ui . Also sorry for the inconvenience here. Trying to consolidate is hard and a bit awkward, but it's the right thing to do. We want a unified effort to make great component story. :)

I've made sure to update the README as well to add the link.
