### ISSUE TITLE
MenuItems Trigger Updates on any ContextualMenu Update

### ISSUE THREAD

**Issue by tabrumle** [microsoft/fluentui#12705]
### Describe the issue:
OnRenderMenuList and RenderSectionItem in ContextualMenu.base.tsx make calls to _renderMenuItem and modify the contextualMenuItem they are using to render ContextualMenuButtons. This causes all ContextualMenuButtons to rerender as they detect a diff in the item prop they are passed in. This is causing perf regressions in persisted contextual menu subsequent showings. 

Proposed change is to alter the signature of _renderMenuItem to take in the fields we modify as parameters instead. The change would be scoped to the calls to _renderMenuItem made within OnRenderMenuList and RenderSectionItem. Will not change behavior as we are still wiring the same values to the menu item components. We just won't be passing them through the item object.

#### Actual behavior:
Passing in the same list of items to contextual menu is causing Contextual Menu Buttons to update

#### Expected behavior:
Passing in the same list of items should not trigger updates for Contextual Menu Buttons

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: Office online

**Comment by joschect** [comment]
@tabrumle Thanks for submitting this and making such a quick fix!
