### ISSUE TITLE
Clearly state somewhere where to look for docs

### ISSUE THREAD

**Issue by jacargentina** [microsoft/fluentui#12713]
I was starting with @fluentui/react-northstar, was using this a the docs source:

https://fluentsite.z22.web.core.windows.net

Now updating to v0.48, where do i have the docs about Icons in @fluentui/react-icons-northstar ?

**Comment by joschect** [comment]
@jacargentina Thanks for the submission and suggestion! Northstar is still in V0 and we're rapidly iterating on it. We could definitely have some more guidance on it.

**Comment by x73x63** [comment]
https://fluentsite.z22.web.core.windows.net/icon-viewer
