### ISSUE TITLE
Attachment with icon and given size, not applied

### ISSUE THREAD

**Issue by jacargentina** [microsoft/fluentui#12714]
react-northstar v0.48

```
              <Attachment
                header="My file"
                icon={<FilesEmptyIcon size="small" />}
              />
```

The files empty icon is not small

**Comment by jurokapsiar** [comment]
Teams Themes by design do not support different sizes of icon instead of the Avatar. You can either create your own theme that supports it or just put an override on the icon:
```
      <Attachment
        icon={<TableIcon styles={{ maxHeight: '1rem'  }} />}
        ...
````
