### ISSUE TITLE
404 Not Found: @fluentui/react-icons@^0.1.0

### ISSUE THREAD

**Issue by somsharp** [microsoft/fluentui#12729]
http fetch GET 404 https://microsoftit.pkgs.visualstudio.com/OneITVSO/_packaging/BusinessApplicationServices/npm/registry/@fluentui%2freact-icons 270ms
silly fetchPackageMetaData error for @fluentui/react-icons@^0.1.0 404 Not Found: @fluentui/react-icons@^0.1.0

**Comment by dzearing** [comment]
This has since been resolved. There was an issue with the package not marked as public. We're going to fix the tooling to catch this before things get published in this bug: https://github.com/microsoft/beachball/issues/321
