### ISSUE TITLE
Context Menu [Power Automate]: Narrator doesn't announce any information about ContextualMenuItemType.Header

### ISSUE THREAD

**Issue by Puyush6889** [microsoft/fluentui#12721]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Microsoft Edge, Windows

### Describe the issue:

When we turn on the Narrator in Edge and Open the Context Menu. The issue is Context Menu Header are not being announced. Anything Under that Context Menu Header should either reference that Header they are in when using the Narrator.

ex. When tabbing with the Narrator, The Narrator Skips the "Navigation" header and doesn't announce anything regarding that.
![image](https://user-images.githubusercontent.com/14367457/79400691-c7cb2a00-7f3b-11ea-88ac-c989801912bb.png)

### Please provide a reproduction of the issue in a codepen:
(ContextualMenu with header)
https://fabricweb.z5.web.core.windows.net/oufr/7.106.0/#/examples/contextualmenu

https://codepen.io/sdasdasdas/pen/rNOxvZa

#### Actual behavior:

When tabbing with the Narrator, The Narrator Skips the "Navigation" header and doesn't announce anything regarding that.

#### Expected behavior:

When tabbing with the Narrator, The Narrator should announce "Navigation" header or anything below that header should reference that we are under the "Navigation" header.

**Comment by joschect** [comment]
@Puyush6889 Thanks for the submission! I can see that the header isn't read out. We recently added sections to address this without breaking previous behavior. I modified your [codepen](https://codepen.io/slimemold/pen/rNOeGVV?editors=0010) here to demonstrate how that works. We need to make sure to add additional guidance in our docs so this i more visible!

**Comment by Puyush6889** [comment]
Hey I looked at the updated Codepen link that you posted. I ran Narrator, but the issue that we reported regarding narrator doesn't announce any information about the "Actions" or "Navigation" So it's still hard for the user to know that some items are under action or Naviagation. if they are only relying on the Narrator.
