### ISSUE TITLE
npm Error@uifabric/set-version@^7.0.10 not found 

### ISSUE THREAD

**Issue by EmadKhella** [microsoft/fluentui#12725]
I  was using  office-ui-fabric-react@7.98.1
it was working correctly till last week .
today I am trying to install same version on another machine with same node and npm versions and i got this error 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @uifabric/set-version@^7.0.10
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@uifabric/icons'
npm ERR! notarget

I checked  @uifabric/set-version@ and found that version 7.0.10 is not there last version became 7.0.9
How can I fix that . ?

**Comment by ayayalar** [comment]
I have the same problem. As of this afternoon

**Comment by brycepolly** [comment]
Same here, they must have pulled the version?  This was working fine a few hours ago.

**Comment by ayayalar** [comment]
As of this afternoon. I couldn’t install @fluentui/react or any version specific package. Frustrating thinking that I must’ve broken something until I found this issue. I hope it gets fixed asap.

**Comment by kbaird5** [comment]
Same

**Comment by ayayalar** [comment]
The issue has been resolved now

**Comment by dzearing** [comment]
This has been resolved. The core issue is being tracked and resolved here:

https://github.com/microsoft/beachball/issues/322
