### ISSUE TITLE
 @uifabric/set-version: No matching version found for @uifabric/set-version@^7.0.10.

### ISSUE THREAD

**Issue by WilsonReddy** [microsoft/fluentui#12724]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "^7.106.0"

### Describe the issue:

npm install task in azure devops build pipeline is failing with below error. This issue started on 4/15/2020 4PM PST.

5183 verbose stack @uifabric/set-version: No matching version found for @uifabric/set-version@^7.0.10.
5183 verbose stack     at pickManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-pick-manifest\index.js:122:13)
5183 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:24:14
5183 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
5183 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
5183 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
5183 verbose stack     at Promise._settlePromiseCtx (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:611:10)
5183 verbose stack     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:142:12)
5183 verbose stack     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
5183 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
5183 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
5183 verbose stack     at processImmediate (internal/timers.js:456:21)
5184 verbose cwd D:\a\1\s\Supplierweb

**Comment by moizgh** [comment]
Failing for multiple packages
`ERROR  No matching version found for @uifabric/styling@>=7.11.3 <8.0.0`
`ERROR  No matching version found for @uifabric/react-hooks@>=7.1.3 <8.0.0`

**Comment by dzearing** [comment]
This has been resolved. Core issue being tracked here: https://github.com/microsoft/beachball/issues/322
