### ISSUE TITLE
Overlay Utility is rendering with blue background for dark and light mode on  website

### ISSUE THREAD

**Issue by mic-max** [microsoft/fluentui#12720]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Win10, Edge + Chrome

### Please provide a reproduction of the bug in a codepen:

This webpage: https://developer.microsoft.com/en-us/fluentui#/controls/web/overlay

#### Actual behavior:

![image](https://user-images.githubusercontent.com/15165028/79400503-42477a00-7f3b-11ea-8e16-9462d73d0811.png)

#### Expected behavior:

Light to have a light background and dark to have a dark one.
They should be different.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: https://developer.microsoft.com/en-us/fluentui#/controls/web/overlay

**Comment by joschect** [comment]
@mic-max Thanks for the submission! I can see that really clearly. Looks like the website is setting those colors and we should be able to remove them. We'll get this fixed!
