### ISSUE TITLE
Examples need to use theme color for Dark Theme to work

### ISSUE THREAD

**Issue by Vitalius1** [microsoft/fluentui#12746]
## Bug

On the website you now have the switcher to a dark theme but some example for demo purposes are using regular html elements that have no `theme.palette` colors/backgrounds applied to them making it so when switch to dark theme look not so good.
Here is just one example I found with `Callout`'s first example but an audit of all examples would be recommended as it gives users navigating the docs think of something broken.

![image](https://user-images.githubusercontent.com/29514833/79484993-618ce880-7fc9-11ea-9fc1-8dd2c8856857.png)

#### Actual behavior:

Dark theme does not get applied to non fabric elements in the example.

#### Expected behavior:

Examples should demo how dark theme changes the coloring palette and a bonus would be comments on why use the palette object so users don't do the same mistake in their apps.

### Priorities and help requested:

Are you willing to submit a PR to fix? **No**

Requested priority: **Normal** (the longer users see this broken state the more questions and doubts about the theming pattern will pop up)

Products/sites affected: Main Fluent UI website.

**Comment by joschect** [comment]
@Vitalius1 Thanks for pointing this out! I'll take a look and we'll start looking towards a fix.
