### ISSUE TITLE
DetailsList onRenderItemColumn not possible to tab between cells

### ISSUE THREAD

**Issue by FanningProducts** [microsoft/fluentui#12758]
### Environment Information

- **Package version(s)**: 7.106.4
- **Browser and OS versions**: Win10, Chrome, Edge

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/ChristianFanning/pen/JjYXNNN?editors=0010
I modified the code sample from developer.microsoft.com a liggle to replicate the error.
Notice the:
function _renderItemColumn(item: IExampleItem, index: number, column: IColumn) {
  const fieldContent = item[column.fieldName as keyof IExampleItem] as string;
  return <input tabIndex={1*index} type='text' name='title' value={fieldContent} />;
}
is rendered as <input tabIndex="-1" ...>

I have tried many other combinations of tabindex.

#### Actual behavior:

It is not possible to tab between cells with the tab button.

#### Expected behavior:
Have an easy way to navigate between cells.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) - I don't think i am skilled enough to submit a PR in your code.

Requested priority: (Blocking, High, Normal, Low)
This is a Blocking issue as the customer will not accept a solution where you have to click with the mouse each time you go to a new cell.

Products/sites affected: (if applicable)
5000 users, 2 products

**Comment by FlyingChrizz** [comment]
Not sure if I need to do something now, please let me know?

**Comment by joschect** [comment]
@FlyingChrizz Thanks for the submission and for including the codepen as well. That's helpful! This is currently working as intended. The details list was made to work somewhat like a grid in that you should only need to use the arrow keys to navigate. We could potentially add a feature to allow users to pass through properties to the focus zone, which would enable you to pass through `handleTabKey` which I believe would allow the behavior that you want. 

For an immediate workaround, depending on the features that you need, you could use a [list instead](https://codepen.io/slimemold/pen/zYvKJee?editors=0010).

**Comment by ilbrando** [comment]
I am implementing edit-feature in my DetailsList and could use this too. Is there a work around for DetailsList?

**Comment by scottdurow** [comment]
Any news on this? Being able to tab between columns is important when you have editable cells.
