### ISSUE TITLE
SearchBox icon does not respect custom theme.

### ISSUE THREAD

**Issue by ImVeryLost** [microsoft/fluentui#12760]
### Environment Information

- **Package version(s)**: 6.141.0
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
```
import { SearchBox, createTheme } from "office-ui-fabric-react";
import { initializeIcons } from "@uifabric/icons";
 initializeIcons();
....
  <SearchBox          theme={createTheme(#some custom theme properties#)}        />
```

#### Actual behavior:
When using a custom theme with custom color pallete, the search icon at first appears in the correct custom color, but goes back to default blue on hover. image can be seen here: https://imgur.com/a/eBfwL0z

#### Expected behavior:
The color to stay in custom color.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by joschect** [comment]
@ImVeryLost Thanks for the question! This is happening because the colors your providing to create theme, only override some of the icon's various colors, rather than all of theme. Here is a [codepen](https://codepen.io/slimemold/pen/gOawdVg?editors=0010) with the icon working as expected!

**Comment by joschect** [comment]
You should be able to use [the theme designer](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/index.html) to help you make a complete theme with all the overrides you'll need.

**Comment by ImVeryLost** [comment]
my bad, thanks for the help.
