### ISSUE TITLE
Tab crashes when viewing Web Control code

### ISSUE THREAD

**Issue by matthew-t-johnson** [microsoft/fluentui#12767]
Browser: Microsoft Edge - Version 81.0.416.53 (Official build) (64-bit)

I noticed earlier this morning that there are some unresolved errors hanging up the browser tab after showing Web Control code. 

Specifically, in the GroupedList control I am getting numerous "Minified React error #290" causing the entire tab to hang up, and it doesn't even close when clicking the close icon on the tab itself.

I'm not sure if I'm using the wrong page (https://developer.microsoft.com/en-us/fluentui#/controls/web) but I've been using this link reliably for awhile and did not notice any such problems before this.

**Comment by joschect** [comment]
@matthew-t-johnson Thanks for the submission! This currently a known problem that we're investigating. I'm going to close this issue as we are tracking the problem primarily in #12754
