### ISSUE TITLE
NVDA narrator reads selected dropdown option text 3 times if using arrow keys to change selection when list is collapsed

### ISSUE THREAD

**Issue by chihch** [microsoft/fluentui#12771]
### Environment Information

- **Package version(s)**: 7.94.0
- **Browser and OS versions**: windows 10

### Describe the issue:

Create a simple dropdown with options, turn on NVDA narrator and use tab navigation to land on the dropdown control. When dropdown list is collapsed use **Up** or **Down** arrow key to change selection. The narrator would read out new selected option 3 times instead of just 1.

repro steps:
1. Keep the NVDA Screen reader running 
2. Use Tab key to select the dropdown control
3. Use up or down arrow key to change options with list collapsed (try to change at least one option)
4. observe

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/chihch/pen/abvZoov

#### Actual behavior:

There are two versions NVDA will read out.
1. In my own application, where simply use a <Dropdown> control without any modification, NVDA screen reader reads out 
<selected item text> -> <dropdown label text> + <selected item text> -> <selected item text>

2. In codepen, NVDA reads out
<selected item text> -> <selected item text> -> <selected item text>

#### Expected behavior:

NVDA only reads out selected item text once.

**Comment by joschect** [comment]
@chihch thanks for submitting this! I can reproduce this issue both with NVDA and Narrator in edge. I suspect that this is an interaction between the aria-live region and aria-labelledby that were initially put on the dropdown to ensure that changes in the selected option were read out. I wonder if narrator/edge have been updated to better handle that scenario, we might be able to remove the live region now. We'll get this fixed

**Comment by nirbaligar** [comment]
ARIA Live is not needed for listbox design pattern. Here's the ARIA recommendation for listbox - https://www.w3.org/TR/wai-aria-practices-1.1/#Listbox
As listbox is a basic component, double/triple reading is going to significantly affect the user experience.

**Comment by AndrewCraswell** [comment]
My team has hit this issue as well during an accessibility review before release.

If someone wants to troubleshoot, the issue that the HCL team logged in our ADO has screenshots, video clip, and repro steps of the issue.
https://worldwidelearning.visualstudio.com/Common/_workitems/edit/1081455

**Comment by chihch** [comment]
can we reopen this item? This is an accessibility issue. thanks so much.
