### ISSUE TITLE
when specifying "CalloutMaxHeight" property, scroll not behaving as expected

### ISSUE THREAD

**Issue by irakaundal98** [microsoft/fluentui#12778]
### Environment Information

- **Package version(s)**: office-ui-fabric-react 7.105.0

### Please provide a reproduction of the bug in a codepen:

Use 'v' as the search query to see the issue clearly.
Codepen link: https://codepen.io/irakaundal/pen/jObroaJ

#### Actual behavior:

First time scroll is abrupt and doesn't scroll to the end of the suggestions and height is wrong. After waiting for the scroll bar to hide, if you scroll again the height would be correct. Waiting for it hide and scrolling again would cause the cycle to repeat.

Also, after the second scroll, when the height is correct, the scroll bar goes behind the styles (background colour) of the focused/hovered item.

#### Expected behavior:

Scrolling should be smooth and the height of scroll bar should not change.

The scroll bar should always be on top of focused/hovered item styles.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected:

**Comment by joschect** [comment]
@irakaundal98  thanks for the question! I believe that this is working as intended. The callout is housing the entirety of suggestions, so when you add a max height, there is the external scroll bar. The inner scroll bar is part of suggestions and the goal with that is so the title `suggested people` stays visible even as you scroll.

Here's a modified version of your [codepen](https://codepen.io/slimemold/pen/qBOaJqO?editors=0010) that I believe works as intended. If you add ```styles: {
    suggestionsContainer: {
    maxHeight: '150px'
  }} ``` to suggestionProps, I believe this will work as intended

**Comment by irakaundal98** [comment]
Thanks. I tried this and it works fine. However, styles property is not exposed by the IBasePickerSuggestionsProps and hence throws a Typescript error.
Also, I wanted to use FloatingPeoplePicker but the IBaseFloatingPickerSuggestionProps type does not have an underlying styles property.

**Comment by irakaundal98** [comment]
using the `suggestionsClassName` prop from `IBasePickerSuggestionsProps` works for the normal people pickers. 

But for FloatingPeoplePicker, it only exposes four props and from looking at the code it appears that there is no override property for suggestionsContainer. 

see line 138: fluentui/packages/office-ui-fabric-react/src/components/FloatingPicker/Suggestions/SuggestionsCore.tsx

**Comment by joschect** [comment]
I think you might be looking to use the `pickerSuggestionsProps: {className: 'name'}` instead. That goes to the corresponding container.

**Comment by irakaundal98** [comment]
Sorry for not being clear. We have exposed below props for pickerSuggestionProps in FloatingPicker and we haven't exposed className.

`export type IBaseFloatingPickerSuggestionProps = Pick<
  ISuggestionsControlProps<any>,
  'shouldSelectFirstItem' | 'headerItemsProps' | 'footerItemsProps' | 'showRemoveButtons' >;`

Also, I don't think the className property is being applied at the correct level. I had tried to use it.
I believe it should be applied at [https://github.com/microsoft/fluentui/blob/b8b675cf78bb832befffc6ff3c3087318f2f5873/packages/office-ui-fabric-react/src/components/FloatingPicker/Suggestions/SuggestionsCore.tsx#L138](url)

 it is currently being applied at [https://github.com/microsoft/fluentui/blob/b8b675cf78bb832befffc6ff3c3087318f2f5873/packages/office-ui-fabric-react/src/components/FloatingPicker/Suggestions/SuggestionsControl.tsx#L109](url)

**Comment by irakaundal98** [comment]
Hi, is there any update on this? Apart from this, can we also expose some more props which can be overridden from `IBaseFloatingPickerSuggestionProps` like `suggestionsItemClassName`

**Comment by joschect** [comment]
@irakaundal98 That makes sense, we can add this to our backlog and might be able to expose more properties from the floating picker.
