### ISSUE TITLE
Panel open and dismiss is causing the background DetailsList - Basic/Other columns moving

### ISSUE THREAD

**Issue by hemakiran214** [microsoft/fluentui#12788]
## Actual behavior:
- The Details list Grid in combination with Custom Panel is causing the UI issue. when Panel is  opened on top of the DetailsList Basic or anytype, from Second Column it is getting padded to left when opened/ On Closed this will get back to normal state.
#### Expected behavior:
Behind Columns in DetailsList When we open Custom Panel toggle/ movement Should not Happen on Details List

### Priorities and help requested:
Even this is happening in the microsoft documentation page at
https://developer.microsoft.com/en-us/fluentui#/controls/web/panel
1 Navigate to 
![image](https://user-images.githubusercontent.com/20403567/79827300-962ee480-83bb-11ea-85dd-7706a514227f.png)
Open panel then you will come to know about the column displacement.
Are you willing to submit a PR to fix? (No)

Requested priority: (Normal, Low)

Products/sites affected: (if applicable)

**Comment by joschect** [comment]
@hemakiran214 Thanks for the submission! I am unable to reproduce this but I have a suspicion that it's related to the fact that I'm testing on a Mac. Could you confirm that you are on windows? Also just to confirm this only happening with custom panel and not any type of panels, correct?

**Comment by hemakiran214** [comment]
HI @joschect, Here This is happening in Windows While opening in Chrome, This is happening with all type of panels that we develop. I hope this is not a priority show breaker but with related to UI. While I'm opening I'm getting a Jerk like displacement on Columns in Details if i open a Panel on top of it. Ping me on v-heputt@microsoft.com to connect with me

**Comment by jdhuntington** [comment]
Hi @hemakiran214 - Afraid I am unable to reproduce this issue. Are you willing to share which css attributes are causing the shift? Have tried on multiple OSes and browsers and am unable to find any issues.
