### ISSUE TITLE
Unable to find Editor Component

### ISSUE THREAD

**Issue by ashitkvora** [microsoft/fluentui#12780]
I saw an Editor component in the old repo - https://github.com/microsoft/fluent-ui-react/blob/master/docs/src/components/Editor/Editor.tsx
But can not find it in the new repo.

Is this component removed?
Is there a replacement for that?
Is there any build-in component similar to AceEditor?

Thanks!

**Comment by joschect** [comment]
@ashitkvora Thanks for the question! It looks like this was removed. @miroslavstastny  or @jurokapsiar might be able to give some insight about what happened to it.

**Comment by jurokapsiar** [comment]
It is still part of the docs, as it is used there. https://github.com/microsoft/fluentui/blob/master/packages/fluentui/docs/src/components/Editor/Editor.tsx

As far as I remember, it was never exported as Fluent UI component, it is just used internally in the documentation page.

**Comment by x73x63** [comment]
You can use draftjs
