### ISSUE TITLE
react-northstar  Prop `className` did not match. Server:

### ISSUE THREAD

**Issue by zerofront** [microsoft/fluentui#12782]
I use @fluentui/react-northstar in next.js 9.3 

But I found this warning 

index.js:1 Warning: Prop `className` did not match. Server: "ui-provider a b c d e f g h i j k l m" Client: "ui-provider a b c d e f g h i j k l m n o p q r s t u v w x y z ab ac ae af ag ah ai aj ak"
    in div (created by Provider)
    in ThemeProvider (created by Provider)
    in RendererProvider (created by Provider)
    in Provider (created by MyApp)
    in I18nextProvider (created by MyApp)
    in MyApp
    in Container (created by AppContainer)
    in AppContainer

does @fluentui/react-northstar support ssr? Or does it require additional configuration?

**Comment by zerofront** [comment]
![image](https://user-images.githubusercontent.com/19327366/80191224-fb970580-8647-11ea-832a-17bd2508b927.png)

I use createRenderer instead of felaRenderer in mergeProviderContext.ts, problem solved

**Comment by paulgildea** [comment]
@jurokapsiar Does northstar support this scenario?
