### ISSUE TITLE
FabricAzureTheme - TextField: Input Box has Two Border Color when Showing Error Message

### ISSUE THREAD

**Issue by Lijing29** [microsoft/fluentui#12781]
### Environment Information

- **Package version(s)**: (fill this out) latest
- **Browser and OS versions**: (fill this out if relevant) Chrome

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/lijinglin29/pen/oNjzLOQ

#### Actual behavior:

![image](https://user-images.githubusercontent.com/50400285/79734224-ef9a0380-8328-11ea-91c4-252d6b7c1645.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/50400285/79734306-148e7680-8329-11ea-8ae1-09df604c31b6.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking)

Products/sites affected: (if applicable)

**Comment by joschect** [comment]
@Lijing29 Thanks for submitting this issue! I can definitely see the problem that you're experiencing. I took a look at this and I suspect that the theme is being applied incorrectly even in the basic theme. I'm having trouble tracking it down but even with the root theme, it appears that there is another outline with a black color applied. @xugao Do you have any ideas?

**Comment by ecraig12345** [comment]
I'm not seeing this in the latest version. Feel free to file a new issue if the problem comes back.
