### ISSUE TITLE
Command bar - How to Reset focus on first items on every visit to command bar using keyboard

### ISSUE THREAD

**Issue by MdAmeerMind** [microsoft/fluentui#12796]
**Actual Behavior**
Command bar set focus on last visited item 

**Expected Behavior**
Command bar should set focus on first item if visited again by using keyboard.

**Repro:**
https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar

**Repro Step:**
Visit above link,  reach to Command bar using keyboard and navigate to items using arrow keys. Now press tab, focus move to other component/control of page. 
Now press Shift+Tab, observe that focus is set to Command bar's item which was last visited.

How to set focus on first item always if user visited command bar again?

**Comment by joschect** [comment]
@MdAmeerMind Thanks for the question! This behavior is driven by the underlying focus zone which command bar relies on. Currently there isn't a way to customize the focus zone, it's possible that we could add a way to pass those props through and I believe that would allow you to force focus to the start of the commandbar every time. @micahgodbolt do you know of any other way to achieve this?
