### ISSUE TITLE
Make Persona tabIndex set to -1 and it doesn't get focused.

### ISSUE THREAD

**Issue by dhivyavk** [microsoft/fluentui#12804]
I am using Persona inside an element which has aria-hidden set to true. 
On keyboard navigation I see tabIndex for Persona element gets set to 0 and it gets focused. 

Is there a property I can pass to set tab Index value correctly?

**Comment by joschect** [comment]
@dhivyavk Thanks for your question! Could you make a codepen to help me understand the problem? Here is a basic [persona](https://codepen.io/slimemold/pen/abvpBEg?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui) codepen to help out
