### ISSUE TITLE
Timepicker Component Required

### ISSUE THREAD

**Issue by agnihotriketan** [microsoft/fluentui#12813]
I am using web version of Fluent UI react version 7 in my web application.

I am not able to find time picker control. Could you please help me to get time picker control ?

**Comment by joschect** [comment]
@agnihotriketan I noticed that you commented in several places. Thanks for your enthusiasm! We'll be tracking the work in #9545 so I'll close this as a dupe.

**Comment by agnihotriketan** [comment]
Thanks for the update. We seriously in need of this control. We moved our application to fluent UI from material design. It makes everyone of us desperate to have it in fluent UI too. Otherwise we have to use timepicker only from some other framework :( & it will not be consistent in look and feel
