### ISSUE TITLE
Tooltip of Close button of panel should visible while user navigate close button using keyboard tabbing

### ISSUE THREAD

**Issue by Harkesh030679** [microsoft/fluentui#12810]
Tooltip of Close button of panel should visible while user navigate close button using keyboard tabbing

### Environment Information

OS: Win 10
Browser: Edge

### Describe the issue:
Tooltip of Close button of panel should visible while user navigate close button using keyboard tabbing

### Please provide a reproduction of the issue in a codepen:

https://developer.microsoft.com/en-us/fluentui#/controls/web/panel
![PanelTooltipIssue](https://user-images.githubusercontent.com/62233836/79964662-a7a1ea80-84a8-11ea-8764-a83cfbaa1dd9.png)

#### Actual behavior:

Tooltip of Close button of panel is not visible while user navigate close button using keyboard tabbing, tooltip is visible once user hover on Close button through mouse

#### Expected behavior:

Tooltip of Close button of panel should visible while user navigate close button using keyboard tabbing

**Comment by joschect** [comment]
@Harkesh030679  Thanks for the submission! I believe that currently everything is working as expected. The close button correctly has a 'title' placed on it. If you look at a standard html button with a title, the [tooltip does not appear on hover](https://codepen.io/slimemold/pen/BaopQxw).

Is there a specific use case that you feel is missing?

**Comment by Harkesh030679** [comment]
Tooltip should be opened on tabbing through keyboard, This is our expectation. Which is not happening on panel close button

**Comment by joschect** [comment]
@Harkesh030679 You can use the `onRenderNavigationContent` to supply your own close button and you should be able to wrap it in `<TooltipHost/>` to achieve this behavior.

**Comment by Harkesh030679** [comment]
@joschect .. Thanks
