### ISSUE TITLE
Add Spinner support for FloatingPeoplePicker

### ISSUE THREAD

**Issue by irakaundal98** [microsoft/fluentui#12818]
#### Describe the feature that you would like added

Currently, we are not showing any spinner when the picker is loading suggestions

#### What component or utility would this be added to

FloatingPeoplePicker

#### Have you discussed this feature with our team, and if so, who

have not discussed this

**Comment by joschect** [comment]
@irakaundal98 Thanks for the submission! This is a reasonable feature request. We'll get this added to the backlog.
