### ISSUE TITLE
Time Picker NEEDED!!!

### ISSUE THREAD

**Issue by j3rrym0use** [microsoft/fluentui#12811]
#### Describe the feature that you would like added

a Time Picker, to pick hours and minutes.

#### What component or utility would this be added to

Time Picker should be a individual component and goes to Galleries and Pickers category.

#### Have you discussed this feature with our team, and if so, who

no

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/18551802/79966013-62d57e00-84bf-11ea-8d82-9504ad5c3a3d.png)

**Comment by agnihotriketan** [comment]
I am using web version of Fluent UI react version 7 in my web application.

I am not able to find time picker control. This is important control & it is missing

**Comment by joschect** [comment]
Closing this as a dupe #9545. Please respond to that issue as that is where we will track work and interest.
