### ISSUE TITLE
Facepile Descriptive Overflow Text Outside of Button

### ISSUE THREAD

**Issue by tabrumle** [microsoft/fluentui#12827]
https://codepen.io/The_Golden_Goose/pen/dyYNXKZ

#### Actual behavior:

Facepile descriptive overflow persona count text can surpass the button's bounds

#### Expected behavior:

Facepile descriptive overflow should truncate at some number to avoid spilling out of its bounds.

### Priorities and help requested:

Change descriptive overflow logic to return 99+ whenever we reach 100 overflow personas or add some way to add custom descriptive

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: (if applicable) Office Online

**Comment by joschect** [comment]
@tabrumle That's a good catch! I think your solution to limiting the maximum number of personas makes a good fix. @betrue-final-final or @dzearing do you have any design opinions about this?
