### ISSUE TITLE
Year only in Calendar component

### ISSUE THREAD

**Issue by Abrissirba** [microsoft/fluentui#12825]
#### Describe the feature that you would like added
It would be nice if the Calendar component could be extended so that you can select year only. I'm thinking something like in the current calendar component where you can show a month only calendar. 

One could argue that it is easier to just have a select with years but then your would need to know how many years to render beforehand. What I like with the current year selector is that it dynamically renders a year range so that you don't have to know the range beforehande.

#### What component or utility would this be added to
Calendar

**Comment by joschect** [comment]
@Abrissirba Thanks for your submission. This sounds like a feature request. We'll get it added to the backlog and review it!
