### ISSUE TITLE
Callout text has low contrast when using DarkCustomizations

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui#12826]
### Environment Information

- **Package version(s)**: 7.107.3
- **Browser and OS versions**: Microsoft Edge Beta - Version 81.0.416.60

### Please provide a reproduction of the bug in a codepen:
Issue is easily reproduced on the Fluent UI control website - https://developer.microsoft.com/en-us/fluentui#/controls/web/callout

![Callout issue](https://user-images.githubusercontent.com/33229964/80028090-74a42a80-8499-11ea-822e-3dd5da2fb153.gif)

#### Actual behavior:
The text does not meet the default contrast ratios

#### Expected behavior:
The text should meet the default contrast ratios

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High - High visibility 

Products/sites affected: Fluent UI Control Website: https://developer.microsoft.com/en-us/fluentui#/controls/web/callout

**Comment by joschect** [comment]
@paulgildea Thanks for noticing this! There seems to be a problem where we don't properly set the color of the text within the callout in the example. We'll get this fixed.

**Comment by ecraig12345** [comment]
Looks like this is fixed.
