### ISSUE TITLE
[Image] with 100% height and 100% width will have outline when zoom screen.

### ISSUE THREAD

**Issue by KeiraYang** [microsoft/fluentui#12832]
### Environment Information

- **Package version(s)**:   Latest and previous versions
- **Browser and OS versions**: Edge Chromium, Chrome, Firefox (Didn't test in IE)

### Describe the issue:
[Image component] When set a Image component with 100% width and 100% height, zoom the page. Under some specific zoom percentage, there will be outline as the image is not width & height is not actually 100% placed. This might because the browser calculation issue under this transform style.

#### Actual behavior:

Image with 100% height and 100% width will have outline show up when zoom page.
Here's the example with 125% zoom in my codepen:
![image](https://user-images.githubusercontent.com/28148759/80084849-04c19d00-858a-11ea-8a1d-edd1526c04e3.png)

#### Expected behavior:

There should not have outline when zoom page with 100% height and 100% width Image.

### If applicable, please provide a codepen repro:

https://codepen.io/keirayang/pen/yLYgPjL

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No
I think it could be fixed with the below style settings under 100% height and 100% width scenario. But not sure if a best fix and covers all the scenarios.
Here's the screenshot:
![image](https://user-images.githubusercontent.com/28148759/80085156-6eda4200-858a-11ea-9949-df50d5d9b05d.png)

Requested priority: High

Products/sites affected: Users will see the outline when zoom the page.

**Comment by joschect** [comment]
@KeiraYang Thanks for the submission! I'm able to see what you're talking about. It does seem like this might be a browser transform problem. And your solution seems like a simple fix! @dzearing would know more about the specifics of the image component.

**Comment by KeiraYang** [comment]
Hi @joschect. Thank you for confirmation. Is there ETA on the bug fix?

**Comment by KeiraYang** [comment]
Hi @joschect . Is there update on this bug which need be fixed? Thanks for the info.

**Comment by KeiraYang** [comment]
Hi team and @joschect . Is there update on this bug? The bug is easy to repro and make not good user experience. A fix would be great. Thanks!
