### ISSUE TITLE
Combox rendered in Dialog. Dropdown is not scrollable with touch.

### ISSUE THREAD

**Issue by staylo8** [microsoft/fluentui#12845]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/staylo/pen/LYpxoBY?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

#### Actual behavior:
Dropdown menu in ComboBox cannot be scrolled via touch. This can be repro'd using Chrome's Decive emulator.

#### Expected behavior:
Dropdown menu in ComboBox should be scrollable by a touch and drag. This can be down with a ComboBox NOT rendered in a Dialog.

### Priorities and help requested:

Are you willing to submit a PR to fix?
No

Requested priority: 
Normal

Products/sites affected: 
FindTime (Part of outlook.com)

**Comment by joschect** [comment]
@staylo8 thanks for the submission! This is happening because in IOS we had an issue where scrolling using your finger would cause overscroll. There was a work around put in #11339 that you can enable by using it like shown in [this codepen](https://codepen.io/slimemold/pen/BaoWoOq?editors=0010)

**Comment by staylo8** [comment]
Thanks @joschect! That worked like a charm :)
