### ISSUE TITLE
textfield: Need to be able to modify the borderless prop dynamically.

### ISSUE THREAD

**Issue by raj-crec** [microsoft/fluentui#12841]
#### Describe the feature that you would like added

To be able to modify the borderless prop dynamically. Initially, I set borderless prop as true for my textfield, but if user clicks on the same, I need him to see it highlighted, for which the borderless prop needs to be changed to false. 

I try the same in onClick(event) handler for the text field, by using event.target.setAttribute('borderless', 'false'). However, this doesn't work. How else can I achieve this ?

#### What component or utility would this be added to

TextField

#### Have you discussed this feature with our team, and if so, who

Nope

#### Additional context/screenshots

Have explained the same above.

**Comment by joschect** [comment]
@raj-crec Thanks for the submission! You can already achieve a border for textfield when the user clicks. you can see that in [this codepen](https://codepen.io/slimemold/pen/qBORemo?editors=0010)

**Comment by raj-crec** [comment]
Can we specify arrow functions in styles ?? Didn't know that. Is it possible for you to explain the piece of code below ? I tried to use the same directly inside my textfield styles property. However, it is erroneous in my case.

 (props)=> {
      const {focused} = props;
      {return {fieldGroup: [
          focused && {
          border: '2px solid',
            borderColor: 'pink'
    }]}}}}

**Comment by joschect** [comment]
@raj-crec Some of our components take in a function for styles, but not all. The code below is called whenever the component is rerendered in a different state. I believe that it's also memoized to help prevent expensive calls internally. It should work the same as passing in a style object but gives you access to whatever is passed into the styles props. You can see it in the props that the textfield accepts either in code (this github) or on our [homepage](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield)

![image](https://user-images.githubusercontent.com/20801176/80662755-e99dd400-8a46-11ea-966f-12794e217069.png)
