### ISSUE TITLE
Incorrect documentation for Dropdown component

### ISSUE THREAD

**Issue by hecerinc** [microsoft/fluentui#12848]
The current documentation on the Dropdown component says it expects to receive `selectedKeys`, but when trying to use that it didn't do anything. It's only until I saw the example for the controlled dropdown that I realised the expected prop is `selectedKey` (singular) and expects a single key.

![image](https://user-images.githubusercontent.com/7988472/80153084-bd2f1700-8571-11ea-9346-402ebb2272da.png)

### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: 

- aka.ms/HIG 
- https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown#implementation

**Comment by joschect** [comment]
@hecerinc Thanks for the submission! The dropdown specification is definitely incorrect. It's pulling another set of props from the `ISelectableDroppableTextProps` interface that is definitely muddying the waters. This is really confusing. We'll get this clarified and fixed!

**Comment by ecraig12345** [comment]
`selectedKeys` ought to work with Dropdown, though ideally the documentation should be clearer about what to use when. If you can make a codepen starting from one of the examples on the Dropdown page, that could help figure out why it's not working in your case.

**Comment by hecerinc** [comment]
So I was making the CodePen when in my console popped this messsage: 

![image](https://user-images.githubusercontent.com/7988472/83602991-6f221180-a528-11ea-9487-8bc998807b6c.png)

Except this is never mentioned in the docs, and moreover the `selectedKey` prop is *not* in the attributes list, which is where the confusion comes from.

**Comment by ecraig12345** [comment]
`selectedKey` is part of [`ISelectableDroppableTextProps`](https://developer.microsoft.com/en-us/fluentui#/controls/web/references/iselectabledroppabletextprops#ISelectableDroppableTextProps) (which `IDropdownProps` extends) as noted/linked here: 
![image](https://user-images.githubusercontent.com/5864305/83660288-7d4c4e00-a579-11ea-918d-342192365195.png)

However I agree this is not at all obvious, and we have an open issue #12043 about improving that.

**Comment by ecraig12345** [comment]
I'm going to close this since we have the other issue tracking the overall problem (and in this case there's at least the console warning to help point in the right direction).

**Comment by ecraig12345** [comment]
Good point...naturally that was the only prop of the four which didn't have some comment like that. 🙄
