### ISSUE TITLE
License of northstar

### ISSUE THREAD

**Issue by nosaku** [microsoft/fluentui#12855]
What is the license of @fluentui/react-northstar? Is the license same a new @fluentui/react? Why am I asking is that, in the react-northstar I see some theming, menus, Flex etc. which I can't find at all in @fluentui/react.

**Comment by jurokapsiar** [comment]
Hi, the licence is the same - MIT for both @fluentui/react as well as @fluentui/react-northstar. See our README or #12288 for some details around repo and package structure.

**Comment by nosaku** [comment]
> 
> 
> Hi, the licence is the same - MIT for both @fluentui/react as well as @fluentui/react-northstar. See our README or #12288 for some details around repo and package structure.

Thank you! I will close the issue.
