### ISSUE TITLE
Voice over announces Title and one more item when dialog opens

### ISSUE THREAD

**Issue by sindujaramaraj** [microsoft/fluentui#12850]
### Environment Information

- **Package version(s)**: "@fluentui/react": "0.44.0"
- **Browser and OS versions**: Safari on Mac OS

### Describe the issue:

With voiceover on, when a dialog is focused, voiceover announces extra information along with title. "{Title} and one more item" instead of just "{Title}". Same issue can be reproduced with the samples here: https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog

#### Actual behavior:

Voice over announces: "{Title} and one more item"

#### Expected behavior:

Voice over not announcing extra information like just "{Title}"

**Comment by aneeshack4** [comment]
I don't see this reproing on Narrator so it's like an issue with the AT VoiceOver, not with the component itself. This isn't a breaking issue for Dialog and the team's currently heads down, focused on big changes with performance improvements and convergence so we're not going to fix this VoiceOver specific scenarios right now - I'm going to close this but when we do future work on Dialog, we'll be sure to consider this. Thanks for reaching out to us!
