### ISSUE TITLE
 CoachMark is not smart enough to include image in teachingBubbleContent, instead, it only calculates the text div height and set it. Additionally, the height/styles props to override height is not working.

### ISSUE THREAD

**Issue by chaofeng2014** [microsoft/fluentui#12868]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:
I find the style of coachMark is not smart enough to include image in teachingBubbleContent, instead, it only calculate the text div height and set it. 
![image](https://user-images.githubusercontent.com/6550896/80260900-cab1d300-863d-11ea-9ebd-f99592dac682.png)

![image](https://user-images.githubusercontent.com/6550896/80260915-d7362b80-863d-11ea-9acd-bd9f237bb502.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/6550896/80261031-3300b480-863e-11ea-8cf9-2d78d8ad7d26.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by chaofeng2014** [comment]
we need override the css style manually in our product, which may be broke by fabric update that include className change or some other changes.

**Comment by aneeshack4** [comment]
We're currently focusing on improvements to performance and coherence, as you can see in #12770 detailing our v8 plans so going to close this issue but when we get a chance to work on Coachmark in the future, this will be taken into consideration. Thank you for reaching out to us.
