### ISSUE TITLE
Avoid Commandbar overflow items

### ISSUE THREAD

**Issue by jedmonsanto** [microsoft/fluentui#12864]
Is there any way to Avoid Commandbar overflow items, i want my buttons to display without overflow items: 
![image](https://user-images.githubusercontent.com/23548643/80245440-42fbb100-869d-11ea-967b-b958c9fe6bc5.png)

I've check some issues but no chance of finding solution

**Comment by aneeshack4** [comment]
It seems you have to actually pass in the overflow items into `overflowItems` prop - they don't get default added otherwise.
