### ISSUE TITLE
Need a way to get currently selected row in details list

### ISSUE THREAD

**Issue by raj-crec** [microsoft/fluentui#12873]
#### Describe the feature that you would like added

Need a way to get the currently selected row index in details list. Currently, I am using 'onActiveItemChanged()' to set a variable for the current row selection. Problem is, if I then do some operation to modify the list, can I be sure that they same row will remain selected ? 

#### What component or utility would this be added to

Details List

#### Have you discussed this feature with our team, and if so, who

Nope

#### Additional context/screenshots
Explained above.

**Comment by aneeshack4** [comment]
I see there's a `setIndexSelected` and a `toggleIndexSelected` in the Selection API and it can be used in DetailList.
