### ISSUE TITLE
DetailsList Control : Windows Narrator focus is getting changed to after pressing enter on the DetailsList control column headers

### ISSUE THREAD

**Issue by v-sagsah** [microsoft/fluentui#12881]
**Browser Details:​**
Microsoft Edge 81.0.416.64

**Issue:**
Windows Narrator focus is getting changed to _**Filter By Name**_, TextField after pressing enter on the DetailsList column headers. Due to this reason the Narrator is reading the value present in the the _**Filter By Name**_, TextField.

**Repro Steps :**
1. Start Narrator. Hit the URL "https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist".
2. Tab till any column header in the table in _**‘DetailsList with 500 documents, sorting, filtering, marquee selection, justified columns’**_ section and press enter.
3. Verify the focus is getting changed after pressing enter on column header and reads value of the text field.

Below is a snapshot of the issue where focus got changed from **_Name_** column header to _**Filter By Name**_, TextField, upon pressing enter on the column header.
![image](https://user-images.githubusercontent.com/64409491/80364431-8889cb00-88a3-11ea-99e8-b4edebffb4e9.png)

**Actual Result:**
1. Focus is getting changed after pressing enter on column header.
2. Screen reader is reading focused values at the end, after pressing enter on any column header in the DetailsList control.

**Expected Result:**
1. Focus should not get changed after pressing enter on column header of DataList control.
2. Screen reader should not read any unwanted information other than focused control or performed action.

**Comment by aneeshack4** [comment]
I see this repro when I run Narrator but only on Edge, not Chrome so I believe this is a browser difference. And I don't see anything wrong with the ARIA labels so this is most likely not a problem with the component itself. I'm going to mark this as won't fix for now and close it. We're not focused on making changes to DetailsList currently but when we do in the future, we'll be sure to look at this.
