### ISSUE TITLE
Problem with your DetailedList tests: https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.test.tsx

### ISSUE THREAD

**Issue by Link631** [microsoft/fluentui#12889]
Hello,

I am testing a component which uses a DetailedList.
Problem:

The run order of my tests are influencing the snapshots.

Then i wanted to check how you are testing this component with the hope to make my tests equals to yours.

For testing purpose, I have copied your tests from here into my project and let them run in different orders. 
https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.test.tsx

I encountered exaclty the same problem.

Assertions are falling because of following content (see screenshot)
aria-labelledby="header0-value-name" vs
aria-labelledby="header9-value-name"
 and:
 aria-labelledby="header0-key-name" vs
 aria-labelledby="header9-key-name"

I get exactly the same conflicts with your tests from this repository.

To reporduce I do:
1. npm test
2 go to your testfile, right click in one of the tests in the middle of the file and select run, so that only this single test runs.
3. As a result, i get conflicting snapshots with the described aria-labelledby and id

Results with your test can be seen in my screen shot.

Can you reproduce this problem? Do you have any ideas, how to avoid creating different ids for same snapshots regardless of test run order?

I need to write those tests due to custom onRender logic.

![testrunWithFluentUiTest](https://user-images.githubusercontent.com/54800010/80426847-e12e8780-88e6-11ea-8985-f845dc8fb497.png)

**Comment by joschect** [comment]
@Link631 You should be able to avoid this by adding importing `resetIds` from utilities and adding

```
  beforeEach(() => {
    resetIds();
  });
```

**Comment by Link631** [comment]
I forgot to answer... yes... resetIndex was the solution. It works fine with it:)

Thanks!
