### ISSUE TITLE
Is it possible to vertically align Cancel and Confirm buttons inside a Dialog? Is yes then how?

### ISSUE THREAD

**Issue by mayank2013** [microsoft/fluentui#12880]
I am using Stardust JS library in my project. I have a requirement to align Confirm and Cancel buttons vertically inside a Dialog. Please suggest a way to that if it is possible.
Following is sandbox url for code: https://codesandbox.io/s/3u6kv?module=/example.js

**Comment by jurokapsiar** [comment]
Teams theme only has horizontal alignment of buttons in the dialog. You could either create your own theme that supports this, or override the Teams theme and tweak it to look as desired. `Dialog` renders a `Flex` in the `action` slot, so for example adding a `Provider` to your render tree and using `componentStyles` in it allows you to target it as follows:

```
import { Button, Dialog, Provider } from '@fluentui/react-northstar';
import React from 'react';

const DialogExample = () => (
  
  <Provider
    theme={{
      componentStyles: {
        'Dialog': {
          'actions': { '& .ui-flex':  { flexDirection: 'column' } },
        },
      },
    }}
  >

    <Dialog
      cancelButton="Cancel"
      confirmButton="Confirm"
      header="Action confirmation"
      trigger={<Button content="Open a dialog" />}
    />
  </Provider>
);

export default DialogExample;
```

You will need to tweak it further to align the buttons and add a gap between them.
