### ISSUE TITLE
In DetailsList component, the narrator focus moves out of the web application while navigating in reverse order using “Caps + left arrow” key.

### ISSUE THREAD

**Issue by Deena-the-coder** [microsoft/fluentui#12892]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (Edge Chromium & Windows)

### Describe the issue:

Hi Team, i am working on a bug where the focus order behaves weirdly while traversing the elements in reverse direction using capslock+left arrow key. At some point the focus is going out of the app.Here is the bug for your reference https://alexanderplatz.visualstudio.com/To-Do/_queries/edit/34489/?triage=true . We have analysed it and found the issue is happening in one of the Fluent UI component we use.We are using "DetailsRow" component imported from "office-ui-fabric-react/lib/DetailsList".The RCA is because one of the column in DetailsRow contains "textarea" which is a non native html element and browser doesn't support tab order naturally for this.So i inspected the page and explicitly set tabindex=0 for a div that holds the textarea.I tested the focus order post that using capslock+left arrow key and it behaved as expected.So i thought of setting the tabindex as a property of the column which renders textarea in our code.But it looks like DetailsRow columns doesn't expose tabindex property to be set.Can someone please help me how can we pass tabindex to the columns in DetailRow?

### Please provide a reproduction of the issue in a codepen:

**Pre-requisite Steps: -**
Go to the link https://beta.to-do.microsoft.com/.
Turn on the narrator.

**Repro Steps:** 
1.Open Left pane navigation and navigate to the task and lists.
2.Now open the task and navigate to the Add step button and 3-4 steps.
3.Now in “Reverse” order use “Caps + right arrow” key to navigate steps.
4.Observe the Narrator focus.

**Expected Result:**
The narrator focus should go through all the steps properly in an order and should not move out.

**Actual Result:**
The narrator focus moves out of the web application while navigating in reverse order using “Caps + right arrow” key.

**Comment by joschect** [comment]
@Deena-the-coder Hey! Thanks for the submission. I'm a little confused about the exact nature of the problem that you're experiencing. Is the issue that focus goes out of the details list? Or is the issue that the editable div is not focused at all? 

One of the features of details list is that it relies on FocusZone which is supposed to take care of most keyboard focus. To make an element in a FocusZone automatically focusable you'd add the data-attribute `data-is-focusable` and then FocusZone should handle that. I am a uncertain if that will help with the caps arrow key movement you're describing.

Additionally you can set a tabindex on any elements within a details list using the custom renderers for any given cell. I made a [codepen here](https://codepen.io/slimemold/pen/abvwrmL?editors=0010) that has an example of an editable div that is focusable via `data-is-focusable` and one that has a tabindex. I tested it out and it seems that focus does move to those editable divs correctly.

**Comment by Deena-the-coder** [comment]
@joschect Thanks for your reply.

Is the issue that focus goes out of the details list? Or is the issue that the editable div is not focused at all?
The issue is that focus goes out of the details list when we are navigating the columns of details list in reverse order starting from the last column.P lease see here  https://alexanderplatz.visualstudio.com/To-Do/_queries/edit/34489/?triage=true where it contains the video explaining the issue.We have three columns for every row. The first column is checkbox and second column is textarea and third column is delete button. If u see in the video, when we are navigating in reverse order starting from delete button and when we try to move to checkbox column from textarea column the narrator focus goes out of details list. https://outlookweb.visualstudio.com/Outlook%20Web/_git/to-do-web?path=%2Fpackages%2Ftodo-client%2Fsrc%2Fviews%2Fdetails%2FStep%2Fdefault%2FStep.tsx contains the complete code.

**Comment by Deena-the-coder** [comment]
Any update on this?

**Comment by ecraig12345** [comment]
In the future, please don't post internal-only links (such as ADO) or links to unreleased products, since this is a public forum. If you need to share that info, you can message the assigned owner after the issue is created.

We also very much appreciate if you can share a minimal isolated repro of the issue (you can start from one of our [examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist) or https://aka.ms/fluentpen), not a repro in an app. If the repro is within an app, it's harder to debug and harder to know whether the issue is within Fluent UI itself or something with how the app is using it.

Those issues aside for now, I tried to follow the repro steps within the app and can't get the issue to repro--focus always stays within the item list for me. I also can't repro it with this isolated example which seems similar to what you have. https://codepen.io/ecraig12345/pen/gOaBOWp
