### ISSUE TITLE
How to use Fluent UI fonts in React

### ISSUE THREAD

**Issue by Githamza** [microsoft/fluentui#12905]
I would like to apply `Segeo` font to my application.

in documentation https://developer.microsoft.com/en-us/fluentui#/styles/web/typography

I don't found how to apply for example `Segeo`

Any Idea ?

**Comment by joschect** [comment]
@Githamza Thanks for the question! `Segeo` should already be the default font used for fabric. You can see it being used on the page that you linked. (See screenshot) Additionally you should be able to override that font as given in the example on that page or by passing the font via most styles properties.

```loadTheme({
  defaultFontStyle: { fontFamily: 'Segoe UI, fontWeight: 'regular' },
  fonts: {
    small: {
      fontSize: '11px',
    },
    medium: {
      fontSize: '13px',
    },
    large: {
      fontSize: '20px',
      fontWeight: 'semibold',
    },
    xLarge: {
      fontSize: '22px',
      fontWeight: 'semibold',
    },
  },
});```

**Comment by dzearing** [comment]
I believe if you just wrap your app in the `Fabric` component, you should be good to go.

https://codesandbox.io/s/mystifying-currying-3qinn?file=/src/App.js

Is this what you're looking for?
