### ISSUE TITLE
TextField: onBlur() handler should also work when user presses 'Enter' to submit value

### ISSUE THREAD

**Issue by raj-crec** [microsoft/fluentui#12904]
#### Describe the feature that you would like added

onBlur() handler should also work when user presses 'Enter' to submit value

#### What component or utility would this be added to

TextField
#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

I currently have a onBlur() handler for a text-field. The problem is, when user enters a value and submits it by pressing 'Enter', I need the onBlur handler to get called. Should it not ? What otherwise is the way to handle submit using 'Enter' key ?

**Comment by joschect** [comment]
@raj-crec You can add your own key handler to the text-field. [Here is a codepen](https://codepen.io/slimemold/pen/zYvdZNY?editors=0011) where I add onKeyDown and programatically move focus when enter key is pressed.

**Comment by raj-crec** [comment]
Thanks a lot @joschect . This worked for me !
