### ISSUE TITLE
DetailsList: Need to select a table row dynamically

### ISSUE THREAD

**Issue by raj-crec** [microsoft/fluentui#12901]
#### Describe the feature that you would like added
To be able to select a 'details-list' row dynamically.

#### What component or utility would this be added to

DetailsList

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Need to enable few buttons on the page depending on the selected row. Hence, need to be able to select the first row dynamically if user clicks outside the details-list.

**Comment by aneeshack4** [comment]
@raj-crec You can use the Selection API's setIndexSelected method - I clarified in this comment on your other issue: https://github.com/microsoft/fluentui/issues/12873#issuecomment-620244681.
