### ISSUE TITLE
Dropdown: onRenderContainer and onRenderList need the default onRenderItem function 

### ISSUE THREAD

**Issue by agg23** [microsoft/fluentui#12919]
#### Describe the feature that you would like added

Identical to #3050 and #12209, Dropdown needs the same treatment Combobox received. Without providing `onRenderItem`, it's not cleanly possible to preserve item rendering but render a custom list, such as providing virtualization as is done in `VirtualizedCombobox`.

**Comment by aneeshack4** [comment]
@agg23 Thanks for reaching out to us. If you're just looking for virtualization, you can use ComboBox. I'll mark this as a feature request and add it to our backlog but we're likely not going to get to it for a while as we're currently focused on larger coherence work items and enhancements to our performance.
