### ISSUE TITLE
Slider label not accepting JSX.Element

### ISSUE THREAD

**Issue by mizeljko** [microsoft/fluentui#12924]
Currently Slider label only accepts string. We need it to accept JSX.Element. Since it is currently just rendering what is passed in the label, as a workaround we are passing JSX.Element as "any" object but we would like be able to pass directly.

The reason we need it is for adding an info icon next to the label that explains the purpose of the slider.

Code Pen example: https://codepen.io/mizeljko/pen/RwNVEKv

#### What component or utility would this be added to

Slider

#### Have you discussed this feature with our team, and if so, who

Not discussed earlier.

**Comment by joschect** [comment]
@mizeljko Thanks for the submission! We'll mark this as a feature request and add it to our backlog. we're likely not going to get to it for a while as we're currently focused on larger coherence work items and enhancements to our performance.
