### ISSUE TITLE
Docs: UI Controls demo, eye medicine and example look improvements suggestion.

### ISSUE THREAD

**Issue by MairwunNx** [microsoft/fluentui#12922]
I know that this does not fall under the bug category, but I did not find the demo site repository.

I noticed a not very beautiful thing in the examples, and wanted to suggest a fix for this.

Go to `Surfaces` then `Panel` then `Panel - Custom Navigation` then click the `Open panel` button and look at the panel =).

I propose changes to the elements in this panel so that the example looks beautiful.

`ms-Panel-navigation navigation-572` margin top to `10px`
`ms-SearchBox root-574` margin left to `24px`
`ms-Panel-contentInner contentInner-494` margin top to `5px`

#### After (beautiful 🥰)
![image](https://user-images.githubusercontent.com/39625750/80626224-c67b2080-8a56-11ea-9a19-5fdb029fb5e5.png)

#### Before (ugly 😐)
![image](https://user-images.githubusercontent.com/39625750/80626614-633dbe00-8a57-11ea-8d55-56f16262cd38.png)

**Comment by aneeshack4** [comment]
I believe this is the result of some flexbox changes to Panel.styles.ts that were recently made to Panel in PR #11391. This is a good first issue if you'd like to take a stab at it! We'll likely get to it but not for a while as it's low impact.

**Comment by ecraig12345** [comment]
I just looked at the toolkit and the way this looks currently is actually by design.

![image](https://user-images.githubusercontent.com/5864305/82498221-79fa9200-9aa4-11ea-8d7b-f7a8d4eb7a53.png)

If you prefer different styling, you can customize that in your application using `IPanelProps.styles.commands`.
