### ISSUE TITLE
Add support for 8 Digit Hex on Color Picker

### ISSUE THREAD

**Issue by rwilson504** [microsoft/fluentui#12929]
#### Describe the feature that you would like added

On the color picker control can you add the capability for 8 digit hex values which include the transparency/opacity value as the last two characters.  If the transparency or alpha sliders are shown then the hex box would allow 8 characters.

#### What component or utility would this be added to

ColorPicker

#### Have you discussed this feature with our team, and if so, who

no

**Comment by aneeshack4** [comment]
@rwilson504 Thanks for reaching out to us. I've added this to our backlog for review but it's low on our priority list - especially since you can currently change transparency with the alpha box.

**Comment by rwilson504** [comment]
Thanks for the feedback.  Yes you can change the transparency with the alpha box the only problem with that though is it currently only updates the RGB values with transparency.  It would be nice if that transparency value could be added to the hex color too.

![image](https://user-images.githubusercontent.com/7444929/80752910-60e07000-8afa-11ea-8ab2-0342e58b7960.png)
