### ISSUE TITLE
Content Security Policy: style-src errors due to inline-styling of components

### ISSUE THREAD

**Issue by jjfeng520** [microsoft/fluentui#12925]
### Environment Information
**Package version(s):** office-ui-fabric-react ^7.69.1
**Browser and OS versions:** Chrome

### Describe the issue:
Our team is using some of the React components with the "styles" property.

E.g., `<Nav styles={{root: { width: 120 }, link: {background: '#eaeaea'}}} />`
 
We're hitting CSP errors ("Refused to apply inline style because it violates the following Content Security Policy directive"), and it's preventing those components from rendering because of possible inline-styling in ***.chunk.js/Stylesheet.ts**. Specifically at these two lines:

![image](https://user-images.githubusercontent.com/16367211/80628790-c05d5380-8a06-11ea-9ab5-42c996e9c967.png)

Is there a fix/workaround for this? I haven't seen any similar posts about this issue, so I'm wondering what we could be missing.

Thank you!

**Comment by joschect** [comment]
@jjfeng520 Thanks for the submission! Fabric uses CSS in JS so almost all of the styling is done through the insertion of style sheets which happens at a variety of points during render and loading. Are you only seeing this issue when you're adding styles to nav? Or are you seeing it any time the component is loaded?

@dzearing might be able to chime in.

**Comment by jjfeng520** [comment]
Hi @joschect , it's only happening when we add "styles" to the component. If it's just the component itself, then there's no CSP errors.

**Comment by joschect** [comment]
@jjfeng520 That's an interesting issue. I don't believe that we currently allow for a way for styles to be precomputed and inserted. It might be possible to do what you want without triggering this policy by making a new `styled` component as that happens at first run and is how most of our styles props are applied. [This codepen](https://codepen.io/slimemold/pen/zYvpKwm?editors=0010) is an example.

I think the only other alternative is to remove the inline csp directive.

@dzearing Might have another idea though.
