### ISSUE TITLE
Combobox Menu placement not underneath

### ISSUE THREAD

**Issue by boomgetchopped** [microsoft/fluentui#12934]
First off great library!  My team was struggling with material ui for react but this library has helped a lot.

We're having an issue with the combobox.  The menu doesn't stay underneath the field but displays off to the side:
![image](https://user-images.githubusercontent.com/5420943/80659203-448af780-8a56-11ea-8f08-8fa94a65094d.png)

Is there a way to ensure the position always uses the available space below the field, and scrolls if needed?

**Comment by joschect** [comment]
@boomgetchopped Thanks for the question! Yes you can. That's part of the default behavior of the callout, it will attempt to position wherever it has room if no room is available. You can force it to appear below the combobox by giving the underlying callout `directionlHintFixed: true`. You can see that in [this codepen](https://codepen.io/slimemold/pen/QWjMeqV)

```
<ComboBox
        componentRef={comboBoxRef}
        defaultSelectedKey="C"
        label="Basic ComboBox"
        allowFreeform
        autoComplete="on"
        options={comboBoxBasicOptions}
        calloutProps={{directionalHintFixed: true}}
      />
```

**Comment by boomgetchopped** [comment]
Works perfect!  Thank you!
