### ISSUE TITLE
Why are ref callbacks not working on Box component

### ISSUE THREAD

**Issue by mayank2013** [microsoft/fluentui#12935]
Ref callbacks are not invoked when used on Box component. Following is sandbox url: https://codesandbox.io/s/i48u9?module=/example.js&file=/example.js

**Comment by jurokapsiar** [comment]
[Box](https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-northstar/src/components/Box/Box.tsx) component in master is already using `compose` util which has forwardRef integrated. Until this is released, you can use [Ref](https://fluentsite.z22.web.core.windows.net/components/ref/definition) component to get the reference to the rendered DOM element.
