### ISSUE TITLE
Support onRenderItemText for the contextual menu items

### ISSUE THREAD

**Issue by AbdelrhmanMagdy** [microsoft/fluentui#12947]
#### Describe the feature that you would like added

Adding onRenderItemText to the IContextualMenuItem to override the rendering of the text in the item.

#### What component or utility would this be added to

Contextual menu item

#### Additional context/screenshots
![image](https://user-images.githubusercontent.com/21978934/80730071-6a250900-8b09-11ea-91d1-af60ebff9710.png)
I want to override the New text and replace it with styled html spans

**Comment by aneeshack4** [comment]
@AbdelrhmanMagdy so you want to override the text and render non-text elements into the ContextualMenu?

**Comment by joschect** [comment]
@AbdelrhmanMagdy You can do this already, see [this codepen](https://codepen.io/slimemold/pen/ZEbXYRd?editors=0010) for an example.

**Comment by AbdelrhmanMagdy** [comment]
Oh, It's my mistake.
It works fine, I'll close this issue.
Thank you!
