### ISSUE TITLE
DetailsList columns are not auto adjusting when I toggle my application's side menu bar in IE and Microsoft Edge.

### ISSUE THREAD

**Issue by gopiinno** [microsoft/fluentui#12940]
I have used fabric react UI DetailsList component to create infinite scrollable table. In my application I have side menu bar which toggles and changes the width of DetailsList. When I do this in Chrome and Mozilla the width of the details list gets auto adjusted and the UI looks good. But in the case of IE and Microsoft edge browser the width is not getting auto adjusted instead we are getting a horizontal scrollbar to navigate to all the columns. I debugged a bit and found that on toggle of my side menu component none of the events of DetailsList component is fired like onRenderItemColumn, onRenderRow and onRenderDetailsHeader etc, but the former mentioned events are fired in chrome and Mozilla browsers. I am not sure is this could be the reason why the columns are not auto adjusted in IE and Edge. Could the team help on this.

**Comment by aneeshack4** [comment]
@gopiinno Please provide a codepen with detailed steps to get an isolated repro on Fabric components alone. There's documentation on the [DetailsList page of our site](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist) to help with re-rendering in virtualized cases: 
![image](https://user-images.githubusercontent.com/4161791/80730849-b7848480-8acf-11ea-8e86-5c56214525ba.png)
But we can't help you if you don't provide a Codepen with this repro.
