### ISSUE TITLE
Custom palette / semantic color slots

### ISSUE THREAD

**Issue by hbnrmx** [microsoft/fluentui#12941]
Hi all,

our project has grown to the size where we need more colors than 
`ITheme.semanticColors` and `ITheme.palette` can provide.
We used up all colors in the palette and are now abusing semanticColors which don't appear
in the fabric components we use to get in a few more additional colors for our own use.

We could make a separate object for all the colors that didn't fit, which completely bypasses `registerTheme` logic but this feels like an inelegant option.

#### Describe the feature that you would like added

a `customColors` property on ITheme

#### What component or utility would this be added to

ITheme

#### Have you discussed this feature with our team, and if so, who

\-

#### Additional context/screenshots

![Screenshot 2020-04-30 at 11 40 11 AM](https://user-images.githubusercontent.com/46070579/80696207-5eb8ea00-8ad7-11ea-8836-79ced86c80e1.png)

Thank you!

**Comment by aneeshack4** [comment]
@hbnrmx We're working on the next iteration of our colors and theming utilities and will take this into consideration. Thanks for reaching out to us!
