### ISSUE TITLE
Split button not working

### ISSUE THREAD

**Issue by renszzzzzzz** [microsoft/fluentui#12959]
# Environment Information

- **Package version(s)**: "office-ui-fabric-react": "^7.105.3"
- **Browser and OS versions**: Version 84.0.488.1 (Official build) dev (64-bit)

### Please provide a reproduction of the bug in a codepen:
`
import { PrimaryButton, DefaultButton, IContextualMenuProps, IIconProps, Stack } from 'office-ui-fabric-react';

menuProps = {
        items: [
          {
            key: 'emailMessage',
            text: 'Email message',
            iconProps: { iconName: 'Mail' }
          },
          {
            key: 'calendarEvent',
            text: 'Calendar event',
            iconProps: { iconName: 'Calendar' }
          }
        ]
      };

<DefaultButton
                            text="Primary"
                            primary
                            split
                            splitButtonAriaLabel="See 2 options"
                            aria-roledescription="split button"
                            menuProps={this.menuProps}
                        />`

#### Actual behavior:

Instead of the split button I am getting the " Contextual Menu Button".
![image](https://user-images.githubusercontent.com/2360975/80784605-796c7c80-8b32-11ea-8867-048b2a046aea.png)

#### Expected behavior:

Expected to get the split button from the tutorial: https://uifabric.azurewebsites.net/#/controls/web/button

![image](https://user-images.githubusercontent.com/2360975/80784627-91440080-8b32-11ea-880d-3d81fcf06ef7.png)

### Priorities and help requested:

Requested priority: Normal

Products/sites affected: Internal application delay.

**Comment by aneeshack4** [comment]
@renszzzzzzz If you're using the right example from the SplitButton section of https://developer.microsoft.com/en-us/fluentui#/controls/web/button, then you'll see this [CodePen](https://codepen.io/aneeshack4/pen/NWGawEp) which will get you the right SplitButton - our SplitButton's menu is a ContextualMenu by default. If you don't want that, you can use the `menuAs` prop to render a custom menu which is also given in the props list on that same documentation page.
