### ISSUE TITLE
peoplePicker onEmptyInputFocus allow duplicates

### ISSUE THREAD

**Issue by darkdubdeep** [microsoft/fluentui#12960]
### Environment Information

- **Package version(s)**: react: 16.8.5, office-ui-fabric-react: 6.189.2,

#### Actual behavior:
Hi! 
When you click on peoplePicker https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker (on any of the examples) you can choose a person from a suggestion list. But, after you pick one person, and click to the peoplePicker again, this person will still exist on the suggestion list. And, if you chose this person again, it will be duplicated in the selected people area and when you will open suggestion list for the third time, this person will disappear. 

I think, that the problem is in the function returnMostRecentlyUsed which updates mostRecentlyUsed with  setMostRecentlyUsed hook but the same time returns mostRecentlyUsed in the previous condition.

The same problem can be if you would like for example implement filter user functionality on the server. The onFilterChanged function will update filtered users to the hooks state (if you will define it) but will return old version of it to the NormalPeoplePicker component in the onResolveSuggestions parameter

#### Expected behavior:
returnMostRecentlyUsed should return relevant/current version of mostRecentlyUsed from useState hook. 

### Priorities and help requested:

Are you willing to submit a PR to fix?  No

Requested priority: High

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@darkdubdeep Thanks for reporting this - I see the same issue. It's curious that there's a `removeDuplicates` in the example code that's being called in `returnMostRecentlyUsed` so this should've been taken care of:
`  const returnMostRecentlyUsed = (currentPersonas: IPersonaProps[]): IPersonaProps[] | Promise<IPersonaProps[]> => {
    setMostRecentlyUsed(removeDuplicates(mostRecentlyUsed, currentPersonas));
    return filterPromise(mostRecentlyUsed);
  };`
If you're able to dig deeper into this and raise a PR, we welcome it. We're currently focused on larger worker items, around performance and coherence for V8 (see pinned issue on repo) so we'll likely not get to this for a while. Thank you for your patience.
