### ISSUE TITLE
FocusTrapZone gets confused with visibility:hidden elements

### ISSUE THREAD

**Issue by Dalimil** [microsoft/fluentui#12970]
When I create a FocusTrapZone and set some of the elements to visibility:hidden, focus trap zone will still try to focus them and then often accidentally *jump out* of the trap zone. For display:none, it works correctly, but for visibility hidden things go wrong because of this code:

https://github.com/microsoft/fluentui/blob/aed9231bbd2438be8bd76ae12a64e829d8838cb8/packages/fluentui/react-bindings/src/FocusZone/focusUtilities.ts#L321

For display none you indeed get 0 height, but for visibility hidden you still get both height and element parent.

Repro in this Pen: https://codepen.io/dahajek/pen/qBOPygw?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

**Comment by Dalimil** [comment]
I can submit a PR for this - although the only way to check the visibility:hidden property of an arbitrary element would require me to call `getComputedStyle` - something like this: https://stackoverflow.com/a/32429346

**Comment by aneeshack4** [comment]
@Dalimil thakns for reaching out to us! 

@khmakoto Do you know what the intended behavior is here? And `getComputedStyle` might be an expensive call.

**Comment by khmakoto** [comment]
@Dalimil we have a data attribute we check for when determining this, you can pass `data-is-visible={false}` to indicate that the element is not visible. Let me know if this solves the problems you're having.

**Comment by Dalimil** [comment]
@khmakoto We are consuming code from another library so trying to add this to their component is a bit of a hack for us.
Is this attribute used exclusively in the focus trap zone?

**Comment by khmakoto** [comment]
@Dalimil unless they are doing something very nasty with their typings, data attributes are accepted in jsx invariably, so I don't think you would have any problem. It is used for both `FocusZone` and `FocusTrapZone`.

**Comment by Dalimil** [comment]
@khmakoto I meant we are not able to set this property on the component because it's a internal private component that they are dynamically creating. We don't really have a control over it unless we somehow to try find it in the DOM and add the data attribute.

**Comment by khmakoto** [comment]
@Dalimil can you explain to me the process of how this is being done? I think there are some workarounds that we could try depending on how the components are being dynamically created and how you're consuming them.

**Comment by Dalimil** [comment]
We are consuming a toolbar component that has the ability to create a
popup. We want to trap our focus inside this toolbar so we create a focus
trap zone around this component that we are importing from their library.
Now everything seems fine, except they don't have display none on their
hidden popup and instead choose to keep it with visibility hidden when it's
not showing.

We have no control over their popup obviously, that's their internal stuff.
Maybe the idea of us trying to put a focus trap zone around a foreign
component was wrong in the first place. We are likely going to attempt to
contribute to their library to fix this issue, but there might be similar
cases like this with the visibility.

I understand that checking for this is expensive in terms of performance,
so I'm okay with a won't fix resolution. But the limitation should be
clearly stated in the focus trap zone documentation page...

**Comment by khmakoto** [comment]
We're discussing offline about our options here. I'll update the thread once we reach an agreement.
