### ISSUE TITLE
Include 'effects' and potentially other slots in code generated by ThemeDesigner

### ISSUE THREAD

**Issue by roeap** [microsoft/fluentui#12987]
#### Describe the feature that you would like added

When creating a theme using the Theme Designer, the generated code includes only values for the color theme slots. For instance effects do not get updated, but rely on the coloring as well to work with the updated color scheme. As such, could the Theme Designer generate code that includes updated values for `effects.elevation*` etc..

#### What component or utility would this be added to

[ThemeDesigner](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/index.html)

#### Have you discussed this feature with our team, and if so, who

no.

#### Additional context/screenshots

n.a.

**Comment by aneeshack4** [comment]
@roeap Thanks for reaching out to us. We have plans on extending the theme designer to include things like effects and other slots but no timeline/ETA yet. Please watch our website for new developments like this.
