### ISSUE TITLE
Getting error while using people picker control

### ISSUE THREAD

**Issue by jitendra09090909** [microsoft/fluentui#12980]
I am not able to resolve bellow issue which are relate to people picker control.

onResolveSuggestions={onFilterChanged}
onEmptyInputFocus={returnMostRecentlyUsed}

![image](https://user-images.githubusercontent.com/39937232/80936430-c9776780-8dee-11ea-98d2-b8e0e0aa5f6f.png)

A callback for what should happen when a person types text into the input. Returns the already selected items so the resolver can filter them out. If used in conjunction with resolveDelay this will only kick off after the delay throttle.

Type '(filterText: string, currentPersonas: IPersonaProps[], limitResults?: number | undefined) => IPersonaProps[] | Promise<IPersonaProps[]>' is not assignable to type '(filter: string, selectedItems?: IPersonaProps[] | undefined) => IPersonaProps[] | PromiseLike<IPersonaProps[]>'.
  Types of parameters 'currentPersonas' and 'selectedItems' are incompatible.
    Type 'IPersonaProps[] | undefined' is not assignable to type 'IPersonaProps[]'.
      Type 'undefined' is not assignable to type 'IPersonaProps[]'.ts(2322)
BasePicker.types.d.ts(53, 5): The expected type comes from property 'onResolveSuggestions' which is declared here on type 'IntrinsicAttributes & IPeoplePickerProps & { children?: ReactNode; }'

**Comment by aneeshack4** [comment]
@jitendra09090909 Thanks for reaching out to us. Please make a codepen where we can see your issue repro - otherwise it's not actionable for us.
