### ISSUE TITLE
overflow hidden on the button makes the text chop off

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#12998]
### Environment Information

- **Package version(s)**: 7.28.0
- **Browser and OS versions**: all browser

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/ssarapu/pen/xxwpXEG?editors=0010

#### Actual behavior:

when we provide `overflow:hidden` on the `label` of the button, the text is getting choped off

#### Expected behavior:

when we provide `overflow:hidden` on the `label` of the button, the text should't get choped off

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (Normal)

Products/sites affected: office 365 site

`overflow:hidden` property is useful to hide when button text is large and not fitting in the button.
this property can also be used in conjunction  with `text-overflow` and `whit-space` to make `....` at the end of text is large. button width is fixed.

i argue that this is happening due to [`lineHegiht:'100%'`](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/Button/BaseButton.styles.ts#L116),

 we should not provide `line-height` to the `label` of the button, because height depends on the font-size.  removing line-height would solve the problem

**Comment by aneeshack4** [comment]
@shivasai09 Thanks for reporting this. @khmakoto do you agree with what Shiva said about `lineHeight` in this case? If not, is there a workaround or another way to fix this?

**Comment by khmakoto** [comment]
@shivasai09 @aneeshack4 I think that if you unset the `lineHeight` the text will not get caught off, however, I worry that there might be other repercussions from doing this. @shivasai09 would you be willing to send a PR to fix this? We can take a look at screener results there to see if everything still looks as expected and decide on that.

**Comment by ecraig12345** [comment]
When I tried setting the lineHeight to initial in codepen, it looked like it caused the text position to change. So this is probably not something we should change without more input from design.

**Comment by shivasai09** [comment]
I believe line-height is something that  change should according to the font-size. because it add space above and below the text, also each character is provided with one em square and certain character will bleed out of that, because of the typography, to avoid it wee need proper line height  .. [see here](https://www.w3.org/TR/CSS21/fonts.html#font-size-props)

 so when the button have default font-size of  `14px`,  setting `line-height:100%` wouldn't make sense, as it will not add any  space above and below the text, .see the image. below.. this is when the `overflow:hidden` is **not  added**
![image](https://user-images.githubusercontent.com/33802398/81255935-a0eca900-904c-11ea-91dc-666a2ba19b07.png)

suggestion. adding `line-height:normal` would fix the issue and will also not cause any change in the text position

@ecraig12345  @khmakoto  any suggestions.

**Comment by khmakoto** [comment]
@shivasai09 like @ecraig12345 said, we probably need more input from design here.
