### ISSUE TITLE
[Accessibility] : Narrator/NVDA is reading the placeholder text for TagPicker field multiple times

### ISSUE THREAD

**Issue by v-sagsah** [microsoft/fluentui#12999]
**Browser Details: ​**
**OS:** Windows 10 (Version 1903, Build: 18362.175)
**Chromium Edge** Version 81.0.416.68 (Official build) (64-bit)
**Google Chrome** Version 80.0.3987.149

**Issue :**
 Screen Reader [Narrator + Chromium Edge / NVDA + Google Chrome] is reading the placeholder text for TagPicker field multiple times.

Please find the sample code example for reference
https://codepen.io/sagsah/pen/RwWxxpw?editors=0010

**Expected Result: ​**
 Screen Reader should read the placeholder text for ‘TagPicker’ field only once.

**User Impact: ​**
Screen reader users will find difficulty in understanding if screen reader is reading the place holder text multiple times.

**Comment by aneeshack4** [comment]
![image](https://user-images.githubusercontent.com/4161791/81083676-7ec32180-8eba-11ea-9d98-47e5c51aad5c.png)
@v-sagsah thanks for reporting this. I see it repro-ing....
