### ISSUE TITLE
Coachmark/TeachingBubble does not appear

### ISSUE THREAD

**Issue by vikramdadwal** [microsoft/fluentui#13009]
### Environment Information

-"office-ui-fabric-react": "^7.106.3"
- Chrome Latest

### Describe the issue:

Trying to use the Coachmark, but it does not appear on the UI. Though I can see in Chrome React Component extension that the component do load. Please check the following recording:

![coach_issue](https://user-images.githubusercontent.com/10174566/81108996-44637f80-8ece-11ea-8660-eac0a50c555f.gif)

#### Actual behavior:

The coachmark does not appear on UI

#### Expected behavior:

The coachmark should appear on UI

### If applicable, please provide a codepen repro:

NA

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
Thanks for filing this, but you'll need to add a CodePen repro before we can help. You can start from one of the [coachmark examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/coachmark) (click "Export to CodePen") or https://aka.ms/fluentpen.
