### ISSUE TITLE
TextField type="number" is not taking negative values and min property doesn't seem to work 

### ISSUE THREAD

**Issue by VasudhaAvuthu** [microsoft/fluentui#13015]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
Thanks for filing this, but you'll need to add a CodePen repro before we can help. You can start from one of the [TextField examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield) (click "Export to CodePen") or https://aka.ms/fluentpen.
