### ISSUE TITLE
Tracking: investigate severities of Chromium Edge High Contrast regression

### ISSUE THREAD

**Issue by czearing** [microsoft/fluentui#13012]
Background:

The Edge update broke existing high contrast selectors. We need to do a pass to understand the full impact across all components.

Original issue is here: https://github.com/microsoft/fluentui/issues/11742

I will go down the list below, investigate Edge old vs Edge new, and fill out Severity and Notes columns.

This list is starting from the top level exports of office-ui-fabric-react, and will be reduced/expanded depending on the components (if any) exported from the export.

| Priority | Meaning |
| -|-|
| n/a | Visually the same |
| 2 | Minor differences but completely usable |
| 1 | Major changes and some features hard to see |
| 0 | Unusable |

Things to try:
* Pressed states
* Hover states
* Focus (tabbing) differences
* Disabled states if applicable
* Are interactive links indecernable?

| Component | Priority | Notes |
|-|-|-|
| Breadcrumb |  2 | Old Edge: Focus and hover caused text to go black making it unreadable. New Edge: Now readable. (Better) |
| Button | 1 | Old Edge: shows disabled button and icon. New Edge: disabled buttons aren't noticeable and icons are cut off.  |
| Calendar | 1.5 | Old Edge: Initial selection and week selection visible. New Edge:  Initial selection doesn't show up and week selection is not visible. |
| Callout | n/a | Callout box shows no visible changes. |
| Card | 2 | Old Edge: highlight around card is visible. New Edge:  highlight isn't visible. |
| ~~Checkbox~~ | ~~0~~ | Fixed by #13035 ~~Old Edge: Disabled checkbox visible and checked boxes are visible. New Edge:  Disabled buttons aren't visible and the user is unable see the boxes that they check.~~ |
| ~~ChoiceGroup~~ | ~~1~~ | Fixed by #13846 ~~Old Edge: disabled items visible. New Edge:  disabled items not visible.~~ |
| Coachmark | 2 | Old Edge: Ripple effect is blue. New Edge : Ripple effect is white |
| ColorPicker | 1.5 | It works fine but the preview box doesn't work in old or new edge.  |
| ~~ComboBox~~ | ~~2~~ | Fixed by #14273 ~~Old Edge: No lines separating items in box. New Edge: Lines separate items in the box~~ |
| CommandBar | 1.5 | Old Edge: Selected icons are green and items have hover effect. New Edge: No hover effect and icons are yellow. |
| ~~ContextualMenu~~ | ~~1~~  | Fixed by #13870 ~~Old Edge:  Disabled items are visible. New Edge: Disabled items aren't visible.~~ |
| DatePicker | 1.5 | Old Edge: Initial selection, week selection, and disabled visible. New Edge:  Initial selection doesn't show up and week selection is not visible.  Also disabled DatePickers aren't visibly different. |
| DetailsList | 2 | Old Edge: Rows with name values are yellow. New Edge: Rows with name values remain white.  |
| Dialog | 2 | Old Edge: Clips with header text and button highlight is blue. New Edge: doesn't clip with header text and button highlights have changed to white. |
| DocumentCard | n/a | DocumentCard shows no visible changes. |
| ~~Dropdown~~ | ~~1.5~~ | Fixed by #14273 ~~Old Edge: Disabled is visible and no lines separating items in box New Edge: Disabled items are not visibly different and lines separate items within the box.~~ |
| Facepile | n/a |  Facepile shows no visible changes. |
| ~~FocusTrapZone~~ |  ~~.5~~  | Fixed in #14408 ~~Both versions show the trap zone even when disabled.~~ |
| FocusZone | n/a | FocusZone shows no visible changes.  |
| GroupedList | n/a | GroupedList shows no visible changes. |
| HoverCard | n/a | HoverCard shows no visible changes. |
| Icon | n/a | Icon shows no visible changes. |
| Image | n/a | Image shows no visible changes. |
| Keytip | n/a | Keytip shows no visible changes. |
| ~~Label~~ | ~~1~~ |  Fixed by #13844 ~~Old Edge:  Disabled label is visible and colored green New Edge: Disabled items are not visibly different and are colored white.~~ |
| Layer | n/a | Layer shows no visible differences. |
| Link | 1 | Old Edge: Links with and without an href are visibly different with yellow text. Disabled links aren't visibly different New Edge: Links with an href are visible and use yellow text. Links without an href  and ones that are disabled aren't visibly different. |
| MarqueeSelection | n/a | MarqueeSelection shows no visible difference |
| ~~MessageBar~~ | ~~1~~ | Fixed by #13034 ~~Old Edge:  MessageBar's content had a background color (green for success, red for an error, etc...). New Edge:  Backgrounds are all black and white.~~ |
| Modal | n/a | Modal shows no visible differences. |
| ~~Nav~~ | ~~1.5~~ | Fixed by #13850 ~~Old Edge: Selected items are visible and no lines separating items in box. New Edge: Selected items aren't visible and lines separate the items in box.~~|
| OverflowSet | 2 | Old Edge: Disabled overflow items are visibly different. New Edge: Disabled overflow items aren't visibly different |
| Overlay | 1 | Both old and new edge do not show overlay. |
| Panel | n/a | Panel shows no visible differences. |
| People Picker| n/a | People Picker shows no visible differences. |
| Persona | n/a | Persona shows no visible differences. |
| Pickers | 2 | Old Edge: Disabled boxes are green and the custom picker doesn't look visually different when disabled. New Edge: Disabled boxes darken and the custom picker looks visually different when disabled. |
| Pivot | 1 | Old Edge: Highlighted and selected items are visibly different. New Edge: Highlighted items aren't visibly different and the selected items only have bold text (There is no color difference or underline) |
| ProgressIndicator | 1 | Old Edge: Blue overlay to show progress. New Edge: Black overlay to show progress making it hard to see. |
| Rating | 1.5 | Old Edge: Rating stars are blue and half stars are visible. New Edge: Stars are white and half stars aren't visible. |
| ResizeGroup | n/a | ResizeGroup shows no visible differences. |
| ScrollablePane | n/a | ScrollablePane shows no visible differences. |
| SearchBox | 1.5 | Old Edge: Highlighted boxes are blue and disabled boxes are green. New Edge: Highlighted boxes are bold and disabled boxes show no visible differences. |
| Selection | n/a | Selection shows no visible difference. |
| ~~Shimmer~~ | ~~0.5~~ | Fixed by #13073 ~~Old Edge:  Gradient transition to white. New Edge: No gradient, transition from black to white (Both examples don't look right)~~|
| ~~Slider~~ | ~~0.5~~ | Fixed by #13952 ~~Old Edge: Disabled slider is green, highlight is blue, ticks are visible, and the selected value is white. New Edge: Disabled slider is not visibly different, the highlight is not visible, ticks aren't visible, and the selected value is not visible.~~ |
| SpinButton | 1.5 | Old Edge: Disabled buttons are green and there is a hover effect New Edge: Disabled buttons value is green but the button is not. The highlight also doesn't work|
| ~~Spinner~~ |~~.5~~ | Fixed by #14372 ~~Old Edge: The spinner is blue. New Edge: The spinner is white and nearly invisible.~~ |
| SwatchColorPicker | n/a | SwatchColorPicker doesn't show any visible changes. |
| TeachingBubble | n/a | TeachingBubble doesn't show any visible changes. |
| Text | n/a | Text doesn't show any visible changes. |
| ~~TextField~~ | ~~1.5~~ | Fixed by #13844 ~~Old Edge: Disabled boxes and text are green New Edge: Disabled boxes are white and text are green.~~ |
| ~~Toggle~~ | ~~1~~ | Fixed by #14316 ~~Old Edge: Disabled toggle is green and checked is white New Edge: Disabled toggle is green and white. When toggle is checked it doesn't change colors.~~ |
| Tooltip | n/a | Tooltip shows no visible difference. |

### ActivityItem
![image](https://user-images.githubusercontent.com/7192338/81114908-b8eeec00-8ed7-11ea-9f7f-b0ef4493f948.png)

### Button
Old 
![image](https://user-images.githubusercontent.com/7192338/81116238-dd4bc800-8ed9-11ea-83c9-f5d72c4440da.png)

New
![image](https://user-images.githubusercontent.com/7192338/81116397-23089080-8eda-11ea-8a2c-3fcd9905170a.png)

### Image
Old
![image](https://user-images.githubusercontent.com/7192338/81117314-babaae80-8edb-11ea-8da1-ec4662cfab90.png)

New (Some selected items are not visible)
![image](https://user-images.githubusercontent.com/7192338/81117388-dcb43100-8edb-11ea-9b38-40b9d4554fbf.png)

### Callout
Old
![image](https://user-images.githubusercontent.com/7192338/81118569-01a9a380-8ede-11ea-811e-f9918b4b1417.png)

New
![image](https://user-images.githubusercontent.com/7192338/81118590-0c643880-8ede-11ea-98f4-c910a36f3bb5.png)

### Card 
Old
![image](https://user-images.githubusercontent.com/7192338/81119005-cd82b280-8ede-11ea-8b5c-bfe5abb98697.png)

New
![image](https://user-images.githubusercontent.com/7192338/81119033-d70c1a80-8ede-11ea-86f8-16365a6be45a.png)

### Checkbox 
Old
![image](https://user-images.githubusercontent.com/7192338/81118385-96f86800-8edd-11ea-9cb8-282d5a3bb6b6.png)

New
![image](https://user-images.githubusercontent.com/7192338/81118401-9eb80c80-8edd-11ea-8b63-be391addfee9.png)

### ChoiceGroup
Old
![image](https://user-images.githubusercontent.com/7192338/81119458-a7114700-8edf-11ea-9f5f-a2bdd1ede0bc.png)

New
![image](https://user-images.githubusercontent.com/7192338/81119360-73ceb800-8edf-11ea-8e01-68e349ccc5f5.png)

### Coachmark
Old
![image](https://user-images.githubusercontent.com/7192338/81119718-361e5f00-8ee0-11ea-8150-48024cad95bf.png)

New
![image](https://user-images.githubusercontent.com/7192338/81119770-4e8e7980-8ee0-11ea-878d-fd6bb1c26ad1.png)

### ColorPicker
Old
![image](https://user-images.githubusercontent.com/7192338/81120059-c6f53a80-8ee0-11ea-999f-9a653317064c.png)

New
![image](https://user-images.githubusercontent.com/7192338/81120102-dd9b9180-8ee0-11ea-8e9b-d1cc10de4e0f.png)

### Combo Box
Old
![image](https://user-images.githubusercontent.com/7192338/81120432-8c3fd200-8ee1-11ea-8b92-94d26d59990d.png)

New
![image](https://user-images.githubusercontent.com/7192338/81120402-7df1b600-8ee1-11ea-8ad1-629b11e5c70d.png)

### Command Bar
Old
![image](https://user-images.githubusercontent.com/7192338/81120851-5e0ec200-8ee2-11ea-9172-9533f2a8d400.png)

New
![image](https://user-images.githubusercontent.com/7192338/81120906-7ed71780-8ee2-11ea-911d-f1092d3d60e4.png)

### ContextualMenu
Old
![image](https://user-images.githubusercontent.com/7192338/81121188-fad15f80-8ee2-11ea-9646-4d491cee289b.png)

New
![image](https://user-images.githubusercontent.com/7192338/81121145-e4c39f00-8ee2-11ea-8bcd-7d1f78200904.png)

### Date Picker
Old 
![image](https://user-images.githubusercontent.com/7192338/81121406-864af080-8ee3-11ea-9f0e-1d3c50a2eac6.png)

New
![image](https://user-images.githubusercontent.com/7192338/81121449-a7134600-8ee3-11ea-8ca9-88ba6d5d9a17.png)

#### Disabled Difference In Date Picker
Old
![image](https://user-images.githubusercontent.com/7192338/81121502-c01bf700-8ee3-11ea-95ab-32c2ca785862.png)

New
![image](https://user-images.githubusercontent.com/7192338/81121522-c9a55f00-8ee3-11ea-9d23-8a40bd0801a3.png)

### Details List
Old (Drag & Drop Example)
![image](https://user-images.githubusercontent.com/7192338/81122351-9368df00-8ee5-11ea-801b-101f15661eb1.png)

New (Drag & Drop Example)
![image](https://user-images.githubusercontent.com/7192338/81122314-82b86900-8ee5-11ea-8538-c0f3e4d16918.png)

### Dialog
Old
![image](https://user-images.githubusercontent.com/7192338/81122586-06725580-8ee6-11ea-8f6e-a8f0add4287f.png)

New
![image](https://user-images.githubusercontent.com/7192338/81122601-0f632700-8ee6-11ea-9574-6f6fc0f45501.png)

### Document Card
Old
![image](https://user-images.githubusercontent.com/7192338/81122750-7680db80-8ee6-11ea-99c3-feb8b55e3a77.png)

New
![image](https://user-images.githubusercontent.com/7192338/81122772-81d40700-8ee6-11ea-8ed1-b256472ecc91.png)

### Dropdown
Old
![image](https://user-images.githubusercontent.com/7192338/81124128-851cc200-8ee9-11ea-8662-7cc47ee7c329.png)

New
![image](https://user-images.githubusercontent.com/7192338/81124167-9e257300-8ee9-11ea-9fd9-3775ced28573.png)

### Facepile
Old
![image](https://user-images.githubusercontent.com/7192338/81124996-bf875e80-8eeb-11ea-9875-d85e533988db.png)

New
![image](https://user-images.githubusercontent.com/7192338/81125007-c8783000-8eeb-11ea-8ae2-184384b90c99.png)

### FocusTrapZone
- The trap zone is disabled and should be hidden in this example.
![image](https://user-images.githubusercontent.com/7192338/81125373-cebadc00-8eec-11ea-900a-40d58a92f0cd.png)

### FocusZone
Old
![image](https://user-images.githubusercontent.com/7192338/81125136-33c20200-8eec-11ea-9054-d8d6c0392f85.png)

New
![image](https://user-images.githubusercontent.com/7192338/81125131-2c9af400-8eec-11ea-8235-155c2e2a08a6.png)

### GroupedList
![image](https://user-images.githubusercontent.com/7192338/81129044-e2b80b00-8ef7-11ea-9a50-7bf35aa9a3f1.png)

### HoverCard
![image](https://user-images.githubusercontent.com/7192338/81129150-4cd0b000-8ef8-11ea-9bc0-4bcb151ecc34.png)

### Icon
![image](https://user-images.githubusercontent.com/7192338/81129228-8bff0100-8ef8-11ea-89dc-ce163e720217.png)

### Image
![image](https://user-images.githubusercontent.com/7192338/81129310-c2d51700-8ef8-11ea-9504-325d6ecd42a8.png)

### Keytip
![image](https://user-images.githubusercontent.com/7192338/81129727-2449b580-8efa-11ea-8182-f5d282a605a3.png)

### Label
Old
![image](https://user-images.githubusercontent.com/7192338/81129838-85718900-8efa-11ea-99c9-e0fb9ba57973.png)

New
![image](https://user-images.githubusercontent.com/7192338/81129853-8e625a80-8efa-11ea-8211-a087d3316ad5.png)

### Layer
![image](https://user-images.githubusercontent.com/7192338/81129983-fadd5980-8efa-11ea-92ba-046c17b51173.png)

### Link

Old
![image](https://user-images.githubusercontent.com/7192338/81130184-ad152100-8efb-11ea-9f8f-142bb0e8ae3d.png)

New
![image](https://user-images.githubusercontent.com/7192338/81130197-b69e8900-8efb-11ea-8640-92439df7a237.png)

Chrome (for reference)
![image](https://user-images.githubusercontent.com/7192338/81130210-c027f100-8efb-11ea-85b5-1d1b728e74d0.png)

### MarqueeSelection
![image](https://user-images.githubusercontent.com/7192338/81130443-a33fed80-8efc-11ea-92c3-c52e110b84e3.png)

### MessageBar

Fixed by #13034

~~Old~~
![image](https://user-images.githubusercontent.com/7192338/81130634-57417880-8efd-11ea-838a-8addde1a83fe.png)

~~New~~
![image](https://user-images.githubusercontent.com/7192338/81130651-6294a400-8efd-11ea-9545-c7a7acfa326d.png)

### Model
![image](https://user-images.githubusercontent.com/7192338/81130743-b4d5c500-8efd-11ea-9295-d5d7c43883a6.png)

### Nav
Old
![image](https://user-images.githubusercontent.com/7192338/81230963-45b4ab00-8fa7-11ea-9cd2-4a2dcf0e3315.png)

New
![image](https://user-images.githubusercontent.com/7192338/81230980-4cdbb900-8fa7-11ea-85e0-6d9d8d14efb4.png)

### OverflowSet
Old
![image](https://user-images.githubusercontent.com/7192338/81231235-ae038c80-8fa7-11ea-865c-c24431a237fd.png)

New
![image](https://user-images.githubusercontent.com/7192338/81231288-c1aef300-8fa7-11ea-85ab-bcb9b1f676fb.png)

### Overlay (Both examples have the overlay open)
Old
![image](https://user-images.githubusercontent.com/7192338/81231533-2ec28880-8fa8-11ea-979d-bfb589f68864.png)

New
![image](https://user-images.githubusercontent.com/7192338/81231624-4dc11a80-8fa8-11ea-992d-b536cdbd2979.png)

### Panel
![image](https://user-images.githubusercontent.com/7192338/81231759-92e54c80-8fa8-11ea-8ebc-d6a0db6379df.png)

### PeoplePicker
![image](https://user-images.githubusercontent.com/7192338/81232007-fa9b9780-8fa8-11ea-81d0-59115f5f9ff3.png)

### Persona
![image](https://user-images.githubusercontent.com/7192338/81232048-0b4c0d80-8fa9-11ea-864a-23f13bf681bc.png)

### Picker
Old
Disabled Tag Picker
![image](https://user-images.githubusercontent.com/7192338/81232501-e2784800-8fa9-11ea-8a62-75d13cdb5b53.png)

Enabled Tag Picker
![image](https://user-images.githubusercontent.com/7192338/81232681-279c7a00-8faa-11ea-9daf-c5b589d743d6.png)

New (Disabled is checked in both examples)
Disabled Tag Picker
![image](https://user-images.githubusercontent.com/7192338/81232629-15224080-8faa-11ea-9136-63f35f90134f.png)

Enabled Tag Picker
![image](https://user-images.githubusercontent.com/7192338/81232705-34b96900-8faa-11ea-8f1c-59f69de4aa1d.png)

### Pivot
Old (There is a hover effect)
![image](https://user-images.githubusercontent.com/7192338/81233409-7e568380-8fab-11ea-9c23-9bd70d8da337.png)

New (There is no hover effect)
![image](https://user-images.githubusercontent.com/7192338/81233435-88788200-8fab-11ea-8b15-115a6ca5dc7e.png)

### Progress Indicator
Old
![image](https://user-images.githubusercontent.com/7192338/81233704-15234000-8fac-11ea-8730-1c484a5608b1.png)

New
![image](https://user-images.githubusercontent.com/7192338/81233717-1eaca800-8fac-11ea-9b21-d55a2de5e231.png)

### Rating
Old
![image](https://user-images.githubusercontent.com/7192338/81233894-882cb680-8fac-11ea-8b22-45471cd6be29.png)

New
![image](https://user-images.githubusercontent.com/7192338/81233920-91b61e80-8fac-11ea-92b9-ff2b13087978.png)

### ResizeGroup
![image](https://user-images.githubusercontent.com/7192338/81234110-fa050000-8fac-11ea-9709-a8d7a943a970.png)

### ScrollablePane
![image](https://user-images.githubusercontent.com/7192338/81234215-30db1600-8fad-11ea-9cf4-f18e3f2d1d37.png)

### SearchBox
Old
![image](https://user-images.githubusercontent.com/7192338/81234463-a646e680-8fad-11ea-83d2-21b3c901e9fd.png)

New
![image](https://user-images.githubusercontent.com/7192338/81234494-b4950280-8fad-11ea-92ef-27846832bf3e.png)

### Selection
![image](https://user-images.githubusercontent.com/7192338/81234788-53216380-8fae-11ea-9319-603a08ddda1b.png)

### Shimmer
Old
![image](https://user-images.githubusercontent.com/7192338/81235267-5f59f080-8faf-11ea-9945-5e2aeb0e1819.png)

New
![image](https://user-images.githubusercontent.com/7192338/81235296-6e40a300-8faf-11ea-986c-d9a15d4fbc7e.png)

Chrome
![image](https://user-images.githubusercontent.com/7192338/81235330-7b5d9200-8faf-11ea-9b70-44fb08bca19f.png)

### Slider
Old
![image](https://user-images.githubusercontent.com/7192338/81235610-3b4adf00-8fb0-11ea-99ee-2d6a26e63519.png)

New
![image](https://user-images.githubusercontent.com/7192338/81235620-430a8380-8fb0-11ea-8af6-b8ec96986803.png)

### SpinButton
Old
![image](https://user-images.githubusercontent.com/7192338/81235873-d0e66e80-8fb0-11ea-9758-2ce98ab8663b.png)

New (The Decimal SpinButton is selected but the highlight is not visible)
![image](https://user-images.githubusercontent.com/7192338/81235972-fd01ef80-8fb0-11ea-9aec-e9c7c7cbcb11.png)

### Spinner
Old
![image](https://user-images.githubusercontent.com/7192338/81236162-6eda3900-8fb1-11ea-86b9-973ef02bee6a.png)

New
![image](https://user-images.githubusercontent.com/7192338/81236179-74d01a00-8fb1-11ea-88ab-7539a4b3004b.png)

### SwatchColorPicker
![image](https://user-images.githubusercontent.com/7192338/81236364-e1e3af80-8fb1-11ea-904c-a53e25cd5227.png)

### TeachingBubble
![image](https://user-images.githubusercontent.com/7192338/81236446-19eaf280-8fb2-11ea-8f08-4318bed1bb52.png)

### Text
![image](https://user-images.githubusercontent.com/7192338/81236537-4737a080-8fb2-11ea-8a88-564808461fb2.png)

### Textfield
Old
![image](https://user-images.githubusercontent.com/7192338/81236683-9978c180-8fb2-11ea-82ad-43c27595718f.png)

New
![image](https://user-images.githubusercontent.com/7192338/81236698-a1d0fc80-8fb2-11ea-8c0c-97e793c17539.png)

### Toggle 
Old 
![image](https://user-images.githubusercontent.com/7192338/81237017-579c4b00-8fb3-11ea-9017-9ad2cc6ea36e.png)

New
![image](https://user-images.githubusercontent.com/7192338/81237025-5ff48600-8fb3-11ea-9930-62d2b0820f2a.png)

### Tooltip
![image](https://user-images.githubusercontent.com/7192338/81237120-a34ef480-8fb3-11ea-9a83-df8f4d7364da.png)

**Comment by doim-microsoft** [comment]
I was wondering if a link not changing its color to Yellow in the High Contrast is part of this regression. In Office Online, if a business bar has a link, it does not change its color to Yellow in the High Contrast, but it remains in blue. I have tested it in Internet Explorer, it does work as expected. Only in Chrome and Edge, the color is not updating.

Please let me know if you need more details.

**Comment by ecraig12345** [comment]
Most or all of these should be resolved now. If anyone finds additional problems, please file a new issue.

(I spoke with @doim-microsoft separately and we're working on tracking down what happened; it seems to be specific to an old version or a bad interaction with other components/styles)

**Comment by ecraig12345** [comment]
Additional related PRs: #16595, #16957, #16848, #16924, #16951
