### ISSUE TITLE
Tooltip of clear/cross button of searchBox is not defined

### ISSUE THREAD

**Issue by Harkesh030679** [microsoft/fluentui#13022]
Tooltip of clear/cross button of searchBox is not defined, Once we search any text in search box, Clear/cross button is displayed, Tooltip of that clear/cross button should be defined

### Environment Information

OS: Win 10
Browser: Edge

### Describe the issue:

Tooltip of clear/cross button of searchBox is not defined, Once we search any text in search box, Clear/cross button is displayed, Tooltip of that clear/cross button should be defined

### Please provide a reproduction of the issue in a codepen:
Please see below searchBox(SearchBox with fixed width and custom event handling)
https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox

![1809446](https://user-images.githubusercontent.com/62233836/81171955-f6787580-8fba-11ea-9d65-c05cc53aa06b.png)

#### Actual behavior:

Tooltip of clear/cross button of searchBox is not defined, 

#### Expected behavior:

Tooltip of clear/cross button of searchBox should be defined, Once we search any text in search box, Clear/cross button is displayed, Tooltip of that clear/cross button should be defined

**Comment by aneeshack4** [comment]
@Harkesh030679 Thanks for reaching out to us. Standard HTML clear or close buttons on most components don't have tooltips. I couldn't find any reference examples of SearchBox that has a tooltip on its close/clear button. If you'd like you can wrap the `IconButton` that is this close/clear button with a `<TooltipHost/>` to achieve this behavior. This isn't something we're planning to bake into the component though.

**Comment by Harkesh030679** [comment]
@aneeshack4 .. Thanks
Agree your thoughts but this icon is part of searchBox control of app fabric then how can we change this Icon to IconButton?

**Comment by ecraig12345** [comment]
You can defined a custom tooltip for the SearchBox by using `clearButtonProps.title`:
```tsx
<SearchBox clearButtonProps={{ title: 'Clear' }} />
```
Full example:
https://codepen.io/ecraig12345/pen/gOaeOPe

**Comment by Harkesh030679** [comment]
Thanks for solution.
