### ISSUE TITLE
SubwayNav is not scaling properly in IE11

### ISSUE THREAD

**Issue by KPechetti** [microsoft/fluentui#13033]
SubwayNav SVG tag is not scaling properly in IE11 with viewBox (working well in all other browsers).
It is working well if I set height and width instead of viewBox.

**Interface:** ISubwayNavNodeStyles
iconContainer: IStyle

**Scaling problem with viewBox**
 svg xmlns="http://www.w3.org/2000/svg" class="iconContainer-717" viewBox="0 0 16 16" focusable="false" xmlns="http://www.w3.org/2000/svg">
	<circle class="iconBackPlate-719" cx="50%" cy="50%" r="43%" />
	<text class="icon-728" text-anchor="middle" x="50%" y="50%" dy="0.5em"></text>
	<circle class="iconRing-720" cx="50%" cy="50%" r="43%" />
svg

Setting height ="16", width ="16" is resolving the issue.

Could you please help me if there is any hack to override the styles of this svg subcomponent in ISubwayNavNodeStyles

### Environment Information

- **Package version(s)**: (latest)
- **Browser and OS versions**: (IE11)

#### Actual behavior:
![image](https://user-images.githubusercontent.com/47015541/81237799-5409c380-8fb5-11ea-8a03-4faf79075a74.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/47015541/81237776-47856b00-8fb5-11ea-9c5a-c2ddde800a30.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
We don't have a component called SubwayNav. Which library is this component coming from?

**Comment by KPechetti** [comment]
> We don't have a component called SubwayNav. Which library is this component coming from?
This is coming from the below file:
packages/dashboard/src/components/SubwayNav/SubwayNode.styles.ts

**Comment by ecraig12345** [comment]
Those components are owned by a different team and were moved to a separate repo last year. So you'll need to contact the owners for support.
