### ISSUE TITLE
Modal control renders with a white rectangle when opened

### ISSUE THREAD

**Issue by alinconstantin** [microsoft/fluentui#13039]
Hi,

The Modal control when opened, renders with a white rectangle, because the Dialog control used internally by it has a default minWidth/minHeight of 288x176 and a white background

https://codepen.io/alinconstantin/pen/QWjQJgX

![ModalBug](https://user-images.githubusercontent.com/19560379/81270894-3ca3f800-9000-11ea-9b6e-5cf649b99b5f.png)

#### Actual behavior:

A white rectangle is opened in center of screen, over the darker opacity layer

#### Expected behavior:

No white rectangle

### Priorities and help requested:

Are you willing to submit a PR to fix? No, not familiar with code.
Requested priority: Normal
Products/sites affected: Microsoft 365 Admin Center (during domain verification/configuration)

**Comment by ecraig12345** [comment]
Thanks for filing an issue, but I'm having trouble understanding what the problem is here. Modal is meant as a "building block" component which you restyle to have the size and contents needed for your scenario. You also shouldn't be setting `isOpen` to `true` until you're actually ready to display the Modal including your custom content. So I think the behavior here is as expected.

**Comment by alinconstantin** [comment]
You could have reached me internally at alinc@ alias if you needed more information...
We use Modal component to show opacity mask and block user interaction with the website/window's content while we open a separate window for login to a 3rd party provider - the user has to perform actions on that site before returning to Microsoft Admin center. And we use Modal without any content, there is nothing to show within the modal in this case, hence <Modal isOpen='true'/> while the user interacts with the 3rd party website.
Fwiw, just <Overlay> is not suitable in this case, as that applies opacity mask and block interaction only with the control displaying the overlay, not the whole window.
The fact that now the Dialog control used internally by Modal has a minwidth/minheight is a change from previous experience, resulting in this white rectangle. To me this looks more like an unwanted consequence of someone applying min size for <Dialog> controls than a 'by design' experience for <Modal>s.
Anyway, I was able to workaround this by styling the modal and overriding your the min size on the IModalStyles.main subcomponent, but I really think you should revisit this...

**Comment by ecraig12345** [comment]
If you wrap the Overlay in a Layer, that will likely give the behavior you want (that's [what Modal does internally](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx#L261:L277)). Overlay+Layer is the intended component combination for your scenario; Modal is meant for when you want to display content.
