### ISSUE TITLE
TooltipHostBase component hide tip when move cursor from Tooltip to TooltipHostBase

### ISSUE THREAD

**Issue by bobogogo1990** [microsoft/fluentui#13037]
### Environment Information

- **Package version(s)**: (7.0.0)
- **Browser and OS versions**: (chrome ( 81.0.4044.113) surface)

### Please provide a reproduction of the bug in a codepen:
[https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.base.tsx](url)

#### Actual behavior:

when move cursor from Tooptip to TooltipHostBase, the Tooltip component doesn't show

#### Expected behavior:

when cursor is on TooltipHostBase, show the Tooltip

### Priorities and help requested:

Are you willing to submit a PR to fix? ( No)

Requested priority: (Normal,)

**Comment by ecraig12345** [comment]
Thanks for filing this, but you'll need to add a CodePen repro before we can help. You can start from one of the [Tooltip examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip) (click "Export to CodePen") or https://aka.ms/fluentpen.
