### ISSUE TITLE
The Callout onDismiss handler is not triggered when clicking a different iframe

### ISSUE THREAD

**Issue by rochaudh** [microsoft/fluentui#13036]
### Environment Information

- **Package version(s)**: `"office-ui-fabric-react": ""^7.93.0"`, but it was reproducible on the latest version as well.

- **Browser and OS versions**: `Chrome/81.0.4044.129`

### Please provide a reproduction of the bug in a codepen:

**Steps:**
1. Open codepen: https://codepen.io/rochaudh/pen/yLYvjZv
2. Press the show callout button. A callout should appear.
3. Click the square box (iframe). Notice that the callout does not disappear and onDismiss handler is not called. 

![image](https://user-images.githubusercontent.com/57733756/81246924-a1922a80-8fcd-11ea-8cea-97fa96a1f04d.png)

#### Actual behavior:

When clicking inside an iframe (but outside of the callout), the callout is not dismissed.

#### Expected behavior:

When clicking outside the callout, the onDismiss handler should be triggered, and the callout should disappear. 

### Priorities and help requested:

Are you willing to submit a PR to fix? `No`

Requested priority:  `Low`

Products/sites affected: `Dynamics 365`

**Comment by ecraig12345** [comment]
Sorry for the delayed response! We discussed this a bit internally but couldn't immediately come up with a good solution. I'll leave this open for now--if it becomes a more significant problem for anyone, please comment and we can further investigate potential fixes.

**Comment by jodom** [comment]
This causes a bug in Fluid embedded experience ( https://fluid.microsoft.com ). I'm curious, what potential solutions have been discussed before?

**Comment by jodom** [comment]
Raised [a PR](https://github.com/microsoft/fluentui/pull/14363) against this issue. Thanks for reviews 👍

**Comment by jodom** [comment]
Following up here, the fix proposed and merged as #14363  does not resolve this issue for chromium browsers. These browsers don't seem to be blurring the main window as expected when an iframe is focused
