### ISSUE TITLE
Dropdown "noResultsMessage" is ignored

### ISSUE THREAD

**Issue by 96andrei** [microsoft/fluentui#13042]
v0.47 and higher

#### Actual behavior:

When selecting all the items in a multi selection dropdown, the expanded dropdown renders a white bar.

![image](https://user-images.githubusercontent.com/12568550/81279680-bfa46d00-9057-11ea-9e3b-0b59f276201d.png)

#### Expected behavior:

It should render the content of "noResultsMessage" property.

**Comment by jurokapsiar** [comment]
Tracking Reference: 7398 (used for team planning)
