### ISSUE TITLE
[Nav] How to render a button inside of link with onRenderLink

### ISSUE THREAD

**Issue by yalian-icom** [microsoft/fluentui#13049]
I try to put a button inside of link but of course, you can't put a button inside another button, please any idea?

**Comment by ecraig12345** [comment]
Thanks for filing an issue, but you'll need to add a CodePen repro before we can help. You can start from one of the [examples](https://developer.microsoft.com/en-us/fluentui#/controls/web) (go to a component's page and click "Export to CodePen" by an example) or https://aka.ms/fluentpen.

**Comment by yalian-icom** [comment]
Here the example, My question is: Is there a way to render an element side by side instead of inside, in order to separate the link's logic to button's logic?
https://codepen.io/yalian-icom/pen/vYNRmjX?editors=0010


![Immagine](https://user-images.githubusercontent.com/59922213/81379769-f8048380-9109-11ea-9512-7af0a70f6f06.png)

**Comment by ecraig12345** [comment]
You can do this by calling `event.preventDefault()` in the custom button's `onClick` callback.
```tsx
<ActionButton 
  onClick={event => {
    alert('I want to stay here');
    event.preventDefault();
  }}
/>
```

**Comment by yalian-icom** [comment]
I have been able to stop the propagation of the parent button with e.stopPropagation, but render a button inside of another button is not pretty, and I looking linkAs props, thanks anyway
