### ISSUE TITLE
A real Rich Text control.

### ISSUE THREAD

**Issue by drgnbear** [microsoft/fluentui#13055]
#### Describe the feature that you would like added

A true rich text control that allows you to add images and full html. There are plenty of rich text editors like CK editor that could be integrated.

#### What component or utility would this be added to

in page modern web parts. the current rich text control is woefully insufficient. If you want SharePoint to really be a CMS you need to provide CMS controls. All I can find is old RTF controls from 2017 that no longer work, and very little information on how to build one that actually works.

#### Have you discussed this feature with our team, and if so, who

no.

#### Additional context/screenshots

There is no way to put an image with a block of text side by side on a page without using a list to generate it. That just won't be good enough. Either allow us to use layout parts inside layout parts or make some controls that we can use to build a page without a data list behind it...

**Comment by aneeshack4** [comment]
@drgnbear Thanks for reaching out to us. I’ll mark this as a feature request and add it to our backlog but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance (see pinned issue on repo).

**Comment by ecraig12345** [comment]
Closing because this is definitely not something we plan to implement as part of the core library due to the level of complexity.
