### ISSUE TITLE
Panel: add way to disable show/hide animation

### ISSUE THREAD

**Issue by a-ivanov81** [microsoft/fluentui#13051]
Please add property for allow disable slideIn/slideOut animation or customize it.

**Comment by aneeshack4** [comment]
@a-ivanov81 Thanks for reaching out to us. I’ll mark this as a feature request and add it to our backlog but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. In the future, please don't blank the template provide - it's most actionable when you fill out our template with details of your request.

**Comment by MagtheRag** [comment]
One extra vote for this one. Being able to change the way they animate would be a really good feature.

**Comment by mltejera** [comment]
+1 here

**Comment by MagtheRag** [comment]
Actually I found out if you pass :
 styles={{
          main: {
            animation: 'none',
          },
        }
      }
as a parameter it works. The animation is gone. There you are also able to point to your own animations if you wish

**Comment by JustSlone** [comment]
Looks like there is a reasonable solution through the styling API here, closing this issue out. If there is reason for a more involved solution, feel free to reopen this with more information
