### ISSUE TITLE
@fluentui/react-northstar: Spacebar not detected in custom RadioGroup input

### ISSUE THREAD

**Issue by Akaprog** [microsoft/fluentui#13065]
### Environment Information

- **Package version(s)**: react-northstar 0.48.0

### Describe the issue:
Spacebar not detected in custom RadioGroup input, reprodicuble even within docs 

#### Actual behavior:
When you try to input text in custom field spacebar does not causes change to input field

#### Expected behavior:
Of course one should be able to input custom text in custom field

### If applicable, please provide a codepen repro:
https://fluentsite.z22.web.core.windows.net/components/radio-group/definition?showCode=false&showRtl=false&showTransparent=false&showVariables=false#types-radio-group

https://codesandbox.io/s/6yuww?module=/example.js

### Priorities and help requested (not applicable if asking question):

Requested priority: ( Normal)

**Comment by Akaprog** [comment]
Additional info:

That might be accessibility related problem due to the fact that also, in current implementation, using arrows in that custom field leads to change in the RadioGroup selected state and all together loss of custom input field value.

**Comment by Akaprog** [comment]
Is this abandoned?

Issue still reproducable in current version.

**Comment by layershifter** [comment]
@Akaprog thanks for reporting, will be fixed in #14717 👍
