### ISSUE TITLE
`getKey` props causes crash when using in ShimmeredDetailsList

### ISSUE THREAD

**Issue by baurine** [microsoft/fluentui#13060]
### Environment Information

- **Package version(s)**: 7.105.3
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

Codepen example: https://codepen.io/baurine/pen/qBOoqJd?editors=0011

The origin code is exported from: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/shimmer

I just add a new line code in line 82:

```
getKey={(row, idx) => `${row.id}_${idx}`}
```

#### Actual behavior:

Nothing display, and you can see the crash log in the console:

```
Uncaught TypeError: Cannot read property 'id' of undefined 
 at pen.js:104
```

#### Expected behavior:

Works normally as before.

#### Reason

The ShimmeredDetailsList creates some null/undefined items inside it in https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/ShimmeredDetailsList.base.tsx#L24

```
export class ShimmeredDetailsListBase extends React.Component<IShimmeredDetailsListProps, {}> {
  private _shimmerItems: null[];
  private _classNames: IProcessedStyleSet<IShimmeredDetailsListStyles>;

  constructor(props: IShimmeredDetailsListProps) {
    super(props);

    this._shimmerItems = props.shimmerLines ? new Array(props.shimmerLines) : new Array(SHIMMER_INITIAL_ITEMS);
  }
```

But we don't judge whether the item is null or undefine before calling `getKey()` in https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/List/List.tsx#L549

```
let itemKey = this.props.getKey ? this.props.getKey(item, index) : item && (item as any).key;
```

Actually we did that before but don't why the logic is removed in the master branch: https://github.com/microsoft/fluentui/pull/1347/files/c1fc1449ae064802e967b36022349179dbabb8b2#diff-92617c3c9fecec754c52f44e7204cec2R321 

```
let itemKey =
        item &&
        (this.props.getKey ? this.props.getKey(item, defaultKey) : item.key);
```

#### Workaround

```
getKey={(row, idx) => `${row?.id}_${idx}`}
```

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes if the old logic is accepted

Requested priority: (Blocking, High, Normal, Low) Low

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@baurine Thanks for reaching out to us. I looked at the List.tsx git history - these lines haven't been changed in [more than a year](https://github.com/microsoft/fluentui/blame/156c760b3320f32bae20f4955f97269536d10372/packages/office-ui-fabric-react/src/components/List/List.tsx#L549)... this is a low pri issue for us and we likely won't address it anytime soon so if you'd like, feel free to raise a PR with your workaround - as long as it doesn't break anything else, it should be ok.
