### ISSUE TITLE
High contrast issue with scroll-able panel control

### ISSUE THREAD

**Issue by v-abkhot** [microsoft/fluentui#13066]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

### Describe the issue:

In scroll-able-panel  we can focus on every item which is visible in normal mode.
but it is not visible in highcontrast mode

#### Actual behavior:
In scroll-able-panel  we can focus on every item which is visible in normal mode.
but it is not visible in high-contrast mode

#### Expected behavior:
In scroll-able-panel  we can focus on every item which is visible in normal mode.
but it should visible in high-contrast mode

**Comment by ecraig12345** [comment]
Thanks for filing this, but you'll need to add a CodePen repro before we can help. You can start from one of the [examples](https://developer.microsoft.com/en-us/fluentui#/controls/web) (go to an example for a component and click "Export to CodePen") or https://aka.ms/fluentpen.

**Comment by v-abkhot** [comment]
please find the codepen link 
https://codepen.io/v-abkhot/pen/yLYjvaz

**Comment by v-abkhot** [comment]
when can i expect the fix ?

**Comment by ecraig12345** [comment]
Thanks for the codepen but I still don't understand what the repro steps are. Can you provide specific steps? 

Also which browser are you using?

**Comment by v-abkhot** [comment]
steps are as follows : - open code pen go to scrollable panel -> hover the list items those will get highlighted -> now turn on highcontrast mode -> go to scrollable panel hover on item list you will found that items are not getting highlighted on mouse hover on items. 

these are the steps to repro.

**Comment by v-abkhot** [comment]
so are those steps helpful to repro the issue ?

**Comment by v-abkhot** [comment]
is some one looking into this issue ?

**Comment by v-abkhot** [comment]
is any one looking into this issue ?

**Comment by ecraig12345** [comment]
This is an issue with DetailsList, not ScrollablePane. Someone recently filed a similar issue with a clearer repro under #13177, so I'm going to close this one and track the issue there. As mentioned on the other issue, I need to discuss this with some team members to determine what the right behavior is.
