### ISSUE TITLE
Tooltip of Persona has different display in Chrome and IE11.

### ISSUE THREAD

**Issue by neil-ji** [microsoft/fluentui#13087]
### Environment Information

- **Package version(s)**: 7.77
- **Browser and OS versions**: IE11.0.9600.19678

#### Actual behavior:
Chrome: Every thing is OK.
IE11: When the mouse pointer moves over the `Persona` in `Suggestion`, `Tooltip` does not display if the text is overflowed. The selected `Persona` in the input box is sometimes displayed when the text does not overflow and sometimes it does not (I guess it depends on the length of the text, but the calculation is wrong in IE11).

#### Expected behavior:
Chrome and IE11: When the mouse pointer moves over the `Persona` in `Suggestion`, `ToolTip` is displayed if the text overflows, otherwise ToolTip is not displayed, and the selected `Persona` in the input box should have the same performance.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

**Comment by ecraig12345** [comment]
Thanks for filing this, but you'll need to add a CodePen repro before we can help. You can start from one of the [examples](https://developer.microsoft.com/en-us/fluentui#/controls/web) (go to a control's page, scroll to the examples, and click "Export to CodePen") or https://aka.ms/fluentpen.

**Comment by LiuBaiX** [comment]
Code Pen does not work in IE11, and fluent ui document site can not access in IE11 either. I'm trying other ways to show you a demo. If you have a way to create a share link under IE11, please let me know. If there is no good way, I will provide you with an IP address for the demonstration later.

**Comment by ecraig12345** [comment]
You can make a codepen in another browser, open it in debug mode (last option shown in the screenshot), copy the link, and use the debug mode link in IE 11. 
<img src="https://user-images.githubusercontent.com/5864305/81743953-62455d00-9457-11ea-8125-ae8d36f8ad17.png" width=352/>
(Note that the debug mode option only shows up if you're logged into codepen. But once you create the debug mode link you don't have to be logged in to use it.)

I'm not sure what you mean about the Fluent UI doc site not working in IE 11--I just checked it now and it works for me.

**Comment by LiuBaiX** [comment]
Thanks for your patience. I Shared a codepen link.

Edit View Link: [https://codepen.io/liubaix/pen/PoPBGLV](url)
Debug View Link: [https://cdpn.io/liubaix/debug/PoPBGLV/wQrPozDZdGQM](url)

Bugs in IE11:

1. In the input box, persona text does not overflow but Tooltip appears(Test the string 'Neil Neil').
2. In suggestion, persona does not show any tooltips, even if text is overflowed.

**Comment by ecraig12345** [comment]
Sorry for the delay. Comparing the behavior in Chrome and IE 11, I can see the second issue you mentioned but not the first one. Can you share a screenshot of the first issue?

In either case, this is not likely to be high-priority for us to fix since IE 11 is nearing end of support and Edge Chromium is now available for all Windows versions.

**Comment by LiuBaiX** [comment]
Well, if you think so, I need to think of other ways to solve the problem.
This is a screenshot of the first issue, test string is `Neil Neil Neil`.
![Tooltip bugs](https://user-images.githubusercontent.com/45644652/83470259-60017c00-a4b4-11ea-8930-5476361d2997.gif)

**Comment by ecraig12345** [comment]
Ah, I'm guessing that one is by design. The computation of whether the text has overflowed may be a bit expensive or hard to time, and there's no harm in showing the tooltip even when it's not strictly needed.

**Comment by LiuBaiX** [comment]
Okay, but we felt that this inconsistency in behavior might confuse the user. I'd appreciate it if you could give me some advice to solve it.
