### ISSUE TITLE
[Accessibility] : NVDA is reading all the controls at once when the callout button clicked with set as role="dialog"

### ISSUE THREAD

**Issue by v-sagsah** [microsoft/fluentui#13089]
**Browser Details: ​**
OS: Windows 10 (Version 1903, Build: 18362.175)
Google Chrome Version 80.0.3987.149

**Issue:**
[Accessibility] : NVDA is reading all the controls at once when the callout button clicked with set as role="dialog".

Please repro the same in the below code pen link 
https://codepen.io/sagsah/pen/abvKvor?editors=0010

**Note :** In code pen code, the callout contains 2 button controls and one link. Upon clicking on the "Show Callout", NVDA is reading all the controls label at once, even though the focus is not been set.

_**Issue not found with Narrator +Chromium Edge.**_

**Expected Result: ​**
NVDA should not read all the controls information at once when callout field button is opened. It should read only the information of the controls on which the focus is present.

**User Impact: ​**
Screen reader users will get confused if narrator reading all the information at once.

**Comment by aneeshack4** [comment]
@v-sagsah Thanks for reaching out to us. I tested this on Narrator and don't repro:
![image](https://user-images.githubusercontent.com/4161791/81579943-69466f80-9372-11ea-8080-399110ae72eb.png) 
I don't see anything wrong with this component's ARIA and I ran the Accessibility Insights tool on your codepen using our components and there were no errors so it looks like the spec is being followed. As a result this isn't actionable on our end and looks to be a NVDA specific bug - I suggest you file an issue on their repo: https://github.com/nvaccess/nvda
![image](https://user-images.githubusercontent.com/4161791/81579306-a2321480-9371-11ea-984c-c9c7aa3d3bf0.png).
