### ISSUE TITLE
Not able to define tooltip of clear button of messageBar(Error messageBar)

### ISSUE THREAD

**Issue by Harkesh030679** [microsoft/fluentui#13113]
Not able to define tooltip of clear button of messageBar(Error messageBar)

### Environment Information

OS: Win10
Browser: Edge

### Describe the issue:

Not able to define tooltip of clear button of messageBar(Error messageBar)

### Please provide a reproduction of the issue in a codepen:
https://developer.microsoft.com/en-us/fluentui#/controls/web/messagebar
Code pen link(Error messageBar)
https://codepen.io/Harkesh/pen/LYprqEr?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

#### Actual behavior:

Not able to define tooltip of clear button of messageBar(Error messageBar)

#### Expected behavior:

Should able to define tooltip of clear button of messageBar(Error messageBar)

**Comment by aneeshack4** [comment]
@Harkesh030679 Please provide clear repro steps - I don't understand what it is I'm supposed to do once I go to the Codepen - all the tooltips are working fine: 
![image](https://user-images.githubusercontent.com/4161791/81715312-b2afc100-943d-11ea-81ed-5d73fa0d55d9.png)

**Comment by ecraig12345** [comment]
I think what they mean is that if you hover over the X there's no tooltip, and no way to define one.

An easy fix for this which follows the pattern of other components would be to modify MessageBar to use the `dismissButtonAriaLabel` as the dismiss IconButton's `title` as well.
```tsx
        <IconButton
          disabled={false}
          className={this._classNames.dismissal}
          onClick={onDismiss}
          iconProps={dismissIconProps || { iconName: 'Clear' }}
          title={this.props.dismissButtonAriaLabel}
          ariaLabel={this.props.dismissButtonAriaLabel}
        />
```

**Comment by Harkesh030679** [comment]
Thanks @ecraig12345  to explaining the bug.
