### ISSUE TITLE
SpinButton: Component not allowing to set empty value while initializing

### ISSUE THREAD

**Issue by ankitsaini90** [microsoft/fluentui#13119]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

When I pass empty string as value in the props the first time, it shows the minimum value in the field, but when empty string is passed as value after the component has mounted, it behaves correctly and shows empty value in the field.

#### Expected behavior:
When I pass empty string in the props as value the first time, it should show whatever the value is passed.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Maybe

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/sites affected: (if applicable) Microsoft Powerpoint web

**Comment by ecraig12345** [comment]
Thanks for reporting this! The issue is that the way SpinButton is checking for whether `props.value` is provided initially incorrectly handles falsey values.
```
    const value = props.value || props.defaultValue || String(props.min) || '0';
```
