### ISSUE TITLE
Option to not have anything selected in the Nav component

### ISSUE THREAD

**Issue by paperbackdragon** [microsoft/fluentui#13129]
#### Describe the feature that you would like added

I'd like to be able to explicitly pass something like `undefined` to the `selectedKey` prop in a `Nav` component, to tell the component to not show any items as selected.

My use case is that we have a secondary nav component that, when the user clicks on one of those, we want to have the main nav be still visible but un-selected, and the secondary nav selected instead.

#### What component or utility would this be added to

Nav

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

--

**Comment by ecraig12345** [comment]
Thanks for submitting a PR for this! I'd suggest a slightly different approach, but we can discuss that on the PR.

**Comment by ecraig12345** [comment]
Closing per discussion on the PR.
