### ISSUE TITLE
[experiments] Sidebar defaultCollapsed prop so collapsed state can be set on first render

### ISSUE THREAD

**Issue by aappddeevv** [microsoft/fluentui#13122]
The only way to the collapsed state is through the ISidebar interface which can be obtained through a ref. But you cannot set the initial collapsed state for the first render.

The request is to have a prop member that sets the defaultCollapsed value.

**Comment by aneeshack4** [comment]
@aappddeevv Please fill out the full feature request template - don't blank it out.

**Comment by aappddeevv** [comment]
Which Fluent UI component is causing the issue: @uifabric/experiments: Sidebar
Which package name and version the component is from 7.23.26
What behaviors and attributes are missing or incorrect: `defaultCollapsed`
What you expected and what is actually happening: 

* Expectations: At mount time, specify the collapsed state via a controlled component property.
* Actual: There is no `defaultCollapsed` setting. You have to set the setting by obtaining a ref then using `ISidebar.setCollapsed` however, by then you have had the flicker of it being open.

Confirmation that the problem reproduces in isolation: Yes

**Comment by ecraig12345** [comment]
Thanks for the details! I'll mark this as a feature request, but it's not something we're likely to get to any time soon--we're currently focusing on improvements to performance and coherence (as you can see in our pinned issue on the repo detailing our v8 plans) and not actively working on experiments components such as Sidebar.

However, I'm guessing this would be pretty easy to implement if you'd like to take a stab at it.

**Comment by aappddeevv** [comment]
I did make the change, it was 2 lines:

Enhance props:

```
interface SidebarProps...
   defaultCollapsed?: boolean
```

And in Sidebar.tsx:

```
constructor(..) { 
   ...
          isCollapsed: props.defaultCollapsed ? props.defaultCollapsed : false,
   ...
}
```

**Comment by ecraig12345** [comment]
That should be fine, thanks!
