### ISSUE TITLE
Is there a way to access the theme palette color in scss class?

### ISSUE THREAD

**Issue by jithendramani** [microsoft/fluentui#13121]
Hello,
I can use colors in my custom style definitions as below 
.myStyleForSomething {
background-color: $ms-color-themePrimary;
}
it totally works fine. 
But when I use custom palette using **loadTheme**. are there variables for the palette colors I can use in place of the background color above.?

**Comment by jithendramani** [comment]
Btw. I am using **office-fabric-ui-react** package. is there something I can import from this package in the scss file to get the variables. Thanks in advance :)

**Comment by aneeshack4** [comment]
@jithendramani Thanks for reaching out to us. We have semantic colors that are more descriptive and build off palette colors. Is this what you're looking for? https://github.com/microsoft/fluentui/blob/c6b49b998d3914ee1547d67543c276af925a6186/packages/styling/src/styles/theme.ts#L172 

You can use aka.ms/themedesigner - it has a visualization for palette and semantic color and the export to codepen has an example of how to use createTheme with those values - you can use loadTheme similarly.

**Comment by jithendramani** [comment]
@aneeshack4  Thanks for reaching out. But, this is not helpful. I am talking about writing css (in this case SCSS as we need to make use of fabric ui variables) for third party controls which fabric ui does not offer. For example a calendar control like 'fullcalendar'. if I have to make the buttons of such third party controls look similar to fabric ui buttons and inherit the theme of **loadTheme**. Is there a way? I don't see any documentation yet. Thanks!

**Comment by jithendramani** [comment]
@aneeshack4  additional comments. See this demo -> https://fullcalendar.io/#demos This calendar has buttons, I want to make it look like fabric ui buttons and it should inherit the theme so that when my application changes themes using loadTheme method. These buttons should respond. Please let me know if you need additional information.  I achieved the result somehow.. but I need a cleaner solution for my product

**Comment by jithendramani** [comment]
The whole point is, there should be variables for palette colors just like the variables you have for primary colors and all(eg:- $ms-color-themePrimary). And these variable should respond to the theme changes(color changes). Does that make sense?

**Comment by ecraig12345** [comment]
If you're customizing the theme, I'm not sure how the palette scss variables would update since those are hard-coded within office-ui-fabric-react or office-ui-fabric-core. @dzearing or @phkuo please correct me if I'm wrong there.

**Comment by phkuo** [comment]
I don't understand, are these insufficient?
https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/common/_themeOverrides.scss
These SASS variables are designed to change when the theme does. Our theming system calls into legacyLoadTheme() which scans CSS to change any theming variables.
The big caveat is that you have to load your CSS through that legacyLoadTheme system. See the readme for instructions:
https://github.com/MBSilverstein/load-themed-styles

**Comment by jithendramani** [comment]
@phkuo I think [this](https://github.com/MBSilverstein/load-themed-styles) is what I was looking for.  Let me try this one. Thanks!
