### ISSUE TITLE
Combo-box: Disable combobox is focusable using tab

### ISSUE THREAD

**Issue by MdAmeerMind** [microsoft/fluentui#13137]
Actual behavior:
Focus is still going to combo box

Expected behavior:
As per accessibility, focus should not move to disable component

Repro
https://codepen.io/mdameer/pen/zYvLwPR?editors=0010

**Comment by aneeshack4** [comment]
@MdAmeerMind Thanks for reaching out to us. I repro this and I checked the history on the ComboBox.tsx - don't see anything that would've regressed this recently. @joschect was this intended behavior?

**Comment by ecraig12345** [comment]
On the later issue #13685 @JustSlone proposed a fix of adding `tabIndex={-1}` on the ComboBox's input element when it's disabled. That seems reasonable and would be a good contribution candidate if someone wants to help with this.

Also, here's an updated codepen that works around the current bug (on codepen's side) which is breaking a lot of old repro pens. https://codepen.io/ecraig12345/pen/dypdzmR
