### ISSUE TITLE
themes.teamsDark no longer matches Teams dark theme color

### ISSUE THREAD

**Issue by karthigb** [microsoft/fluentui#13147]
Fluent's Team's dark theme does not match the client's dark theme color.
![image](https://user-images.githubusercontent.com/2610557/81840581-126da100-94fe-11ea-9ea4-a9fc1448361a.png)

Furthermore, the <Provider> object should be able to inherit the theme from the Teams client. I should n't have to specify dark or light. I can get the user's theme from the Team's user context, but loads after <App/> gets rendered.

**Comment by aneeshack4** [comment]
@karthigb are you using Fluent v0 components? And if so, which ones?
