### ISSUE TITLE
calendar display issue not only on small screen

### ISSUE THREAD

**Issue by am-mcrae** [microsoft/fluentui#13150]
There is a similar issue that has been reported for small screens but I wanted to make it known that this issue is not limited to small screens.

### Environment Information

- **Package version(s)**: 7.107.1
- **Browser and OS versions**: Google Chrome Version  81.0.4044.138 

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/am-mcrae/pen/YzyjdbL
![image](https://user-images.githubusercontent.com/65312204/81864333-558d3b80-9521-11ea-89c3-66f324f3869e.png)

#### Actual behavior:

'Go to today' displays behind days

#### Expected behavior:

'Go to today' should display on the right hand side underneath the months

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: in-house microsoft application

**Comment by aneeshack4** [comment]
@am-mcrae Thanks for reaching out to us. I'm trying to find the related issue - do you know which one it is? I've found other issues with 'Go to today' but not about the display, more about focus and most of those are closed. I looked at your codepen - I think you adding the Clear Dates button pushed the 'Go to today' up behind the calendar itself. I'm not sure if this control was intended to have buttons like that added inside it... you could use the boolean prop `showGoToToday` to hide it if you feel you need to keep the Clear Dates button inside this DatePicker. Tagging @lorejoh12, component owner - perhaps Jon has additional input into this.

**Comment by am-mcrae** [comment]
@aneeshack4 Thank you for the quick response! I tried removing the button and the 'Go to today' portion was still behind the days.
![image](https://user-images.githubusercontent.com/65312204/81992181-c141d800-95f7-11ea-9d1a-45ec6659dbd3.png)

 I have updated the codepen to show that. The similar issue I was referring to was https://github.com/microsoft/fluentui/pull/9554 . 

I will be hiding the 'Go to today' feature for a current fix.

**Comment by ecraig12345** [comment]
The "Go to today" button is a built-in feature of the calendar, so if it's displaying incorrectly we should fix it.

This is what it's supposed to look like (the screenshot is [with Fabric 6](https://codepen.io/ecraig12345/pen/rNOqVYW) which has the correct styling): 
![image](https://user-images.githubusercontent.com/5864305/82097905-b0a56680-96b8-11ea-9c4f-38f33bbd148a.png)

@lorejoh12 Is this something you can help with?

**Comment by ecraig12345** [comment]
Actually I misunderstood, that screenshot is of the DatePicker not the Calendar. But "Go to today" is supposed to be built in to Calendar as well. Let me take another look...

**Comment by ecraig12345** [comment]
Looking at it more, I'm a bit confused--it looks like you've copied most of the implementation of the Fluent UI DatePicker. Is there a reason you can't just use the Fluent UI DatePicker directly, since that's styled correctly to begin with?
