### ISSUE TITLE
Nav: when focus Jumps on Nav item ... After reading At the End it Reads 0%  Vertically Scroll

### ISSUE THREAD

**Issue by v-jashr** [microsoft/fluentui#13161]
Nav Component: when focus Jumps on Nav item ... After reading At the End it Reads 0%  Vertically Scroll
Browser
Edge Chromium (any)

Screen Reader
Narrator

Expected Result
It should only convey message about  Nav item selected/not selected when focus land on it.

Actual Result
It is reading extra string as  0%  Vertically Scroll

![image](https://user-images.githubusercontent.com/50479173/81933624-54d0d400-960b-11ea-8ba7-ca8a4a1a87f0.png)

**Comment by aneeshack4** [comment]
@v-jashr I don't repro this "0% vertically scroll". Reading at the end of what specifically? Just the selected item?

**Comment by v-jashr** [comment]
Can you please Check with Edge Chromium  Browser with Narrator. I am able to repro on official web site of Office fabric it self 

https://developer.microsoft.com/en-us/fluentui#/controls/web/nav

![image](https://user-images.githubusercontent.com/50479173/82016976-b80c4600-969f-11ea-95ac-e57533eb14e4.png)

**Comment by ecraig12345** [comment]
What are the specific steps you're following to get this behavior? (This is why our template asks for specific repro steps.)

**Comment by v-jashr** [comment]
Step to Repro

1. Open **Edge Chromium** Browser
2.  Go to on this Link
https://developer.microsoft.com/en-us/fluentui#/controls/web/nav

3.  Scroll down till you find the "Nav with Custom Group Header" [refer Screenshot.]

4.   **Turn ON** the windows narrator tool, Traverse using tab till you reach "Activity" link "Nav with Custom Group Header".

5. Listen narrator reads 0% Vertically Scroll

![image](https://user-images.githubusercontent.com/50479173/82019206-70d48400-96a4-11ea-9362-99de6bae2785.png)

**Comment by aneeshack4** [comment]
I still don't see this 0% vertically scroll at all... 
![image](https://user-images.githubusercontent.com/4161791/82350983-9d98dc00-99c1-11ea-8fde-442e677b036f.png)

**Comment by v-jashr** [comment]
is the screenshot is of  **Edge Chromium** Browser and **Narrator**

Go to on this Link
https://developer.microsoft.com/en-us/fluentui#/controls/web/nav
@aneeshack4  
if yes can you please provide the version name of Browser in which it is working fine 

As  we are using  following version 
Microsoft Edge is up to date.
Version 81.0.416.77 (Official build) (64-bit)

**Comment by aneeshack4** [comment]
@v-jashr You can see in the screenshot that it's Edge Chromium on Windows and it's Narrator Buddy output on the right.
