### ISSUE TITLE
Picker components use transparent background which conflicts with TextField - Fluent V7

### ISSUE THREAD

**Issue by dsosby** [microsoft/fluentui#13166]
### Environment Information

- **Package version(s)**: 7.113.1
- **Browser and OS versions**: Chrome, Edge, Firefox latest, Win10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/dsosby/pen/pojOwow

#### Actual behavior:

TextField has a backing field (ms-TextField-fieldGroup) that uses themed color (e.g. white)
Picker does not leverage this and thus renders transparently.

#### Expected behavior:

Picker, as it is also a Text Input, to have same behavior as TextField.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Microsoft Admin Center

**Comment by dsosby** [comment]
This appears to be a regression. Will see if I can track this down.
This behavior becomes very apparent when a picker is used within a DetailsList component as a focused or selected row has a non-default background color.

**Comment by dsosby** [comment]
Version 6 does not have this behavior. Pickers are opaque
https://codepen.io/dsosby/pen/XWmPeEa

**Comment by dsosby** [comment]
Maybe this one.... https://github.com/microsoft/fluentui/pull/10420

**Comment by ecraig12345** [comment]
Thanks for reporting this and for the investigation! I agree, transparent background is not the right way to fix the border issue from #10153. From [this codepen](https://codepen.io/ecraig12345/pen/MWaqMrQ) I made based on yours (screenshot below), it looks like setting the background on `styles.text` works better than setting it on `styles.input`. @joschect Does that sound right to you?

If you're willing to submit a fix, that would be great! Note that while I used hardcoded `white` in the codepen, you should use `semanticColors.inputBackground` in the real code.

(Note that the TextField bottom border is not actually clipped, it just got clipped in the screenshot.)
<img src="https://user-images.githubusercontent.com/5864305/82073187-bfc2ef00-968d-11ea-960f-c06339793b8e.png" width=399/>

**Comment by dsosby** [comment]
Thanks! I'm also using a workaround of setting text to inputBackground in my project now with success. I can offer this as a PR here, and will double-check the original bug fix does not regress
