### ISSUE TITLE
several cross origin and js errors on the Fluent UI Components website

### ISSUE THREAD

**Issue by ChristianHohlfeld** [microsoft/fluentui#13164]
Several javascript issues on components demonstration page:
e.g. https://developer.microsoft.com/en-us/fluentui#/controls/web/overflowset

Thank you, Fluent UI looks promising so far!

**Comment by aneeshack4** [comment]
@ChristianHohlfeld Thanks for reaching out to us! Can you be more specific as to what the errors are exactly? So that this is actionable for us.

**Comment by ecraig12345** [comment]
Adding on to what Aneesha said--there are various other frameworks besides our code being loaded on the website, and those may be causing errors which are out of our control. Also, fixing any console errors will be pretty low-priority unless they're causing actual visible issues with the website.
