### ISSUE TITLE
Migrate e2e / accessibility tests to Playwright 

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/fluentui#13191]
Currently Puppeteer will be used to perform basic e2e and accessibility tests which is based on Chromium. What about migrating it over to [Playwright](https://github.com/microsoft/playwright) which supports Chromium / WebKit / Firefox and running / checking it with all of them in a row?

I already played a bit around with the [e2e tests](https://github.com/microsoft/fluentui/tree/master/packages/fluentui/e2e/tests) locally and these tests are working mostly almost directly. But I wanted to ask first, what you think about it. I'm open to contribute to it.

**Comment by ecraig12345** [comment]
Interesting idea--@layershifter or @kenotron do you have any thoughts on this, or any experience with Playwright?

(Assigning to @jurokapsiar as I think this primarily affects v0.)

**Comment by ecraig12345** [comment]
Going to close this since although it's an interesting idea, as far as I'm aware it's not something we plan to change at this time.
