### ISSUE TITLE
Not able to navigate input cursor with arrows inside TextField placed inside DetailsList 

### ISSUE THREAD

**Issue by SuperCiacho** [microsoft/fluentui#13210]
### Environment Information
- **Package version(s)**: 7.107.3 <
- **Browser and OS versions**: (fill this out if relevant)

**Example:** https://codepen.io/Code-Artist/pen/KKdrmxK

Since version 7.107.4 our users are not able to use arrow keys to navigate an input cursor inside TextField placed inside DetailsList row.

I found out that the root of this problem is **preventDefaultWhenHandled** property recently added to FocusZone component (PR #12636). 
Same issue exists on your FocusZone example (https://developer.microsoft.com/en-us/fluentui#/controls/web/focuszone#usage -> _Nesting FocusZones in list rows_)

#### Actual behavior:

User is not able to use left and right arrow keys to change position of input cursor.

#### Expected behavior:

User is able to use left and right arrow keys to change position of input cursor.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: yes

**Comment by aneeshack4** [comment]
@SuperCiacho Thanks for reporting this and digging to find when the regression happened. @khmakoto is a fix appropriate here or is there a workaround you'd suggest?
