### ISSUE TITLE
Theming documentation: Usage of the Customizer component

### ISSUE THREAD

**Issue by marygans** [microsoft/fluentui#13225]
#### Describe the feature that you would like added
There is currently no documentation surrounding how to use the Customizer component to apply built in themes and styles like Dark, Azure, MDL2 themes, etc. The only guidance on theming is [here](https://github.com/microsoft/fluentui/wiki/Theming) and maybe should be updated to reflect  additional theming options (Customizer, Provider, etc).

#### What component or utility would this be added to

No component updates needed, just github documentation

#### Have you discussed this feature with our team, and if so, who

No, but Im glad to help here.

**Comment by aneeshack4** [comment]
@paulgildea and @micahgodbolt are starting to plan for content on guiding devs on using Customizer. Watch this space for more updates :)

**Comment by paulgildea** [comment]
What kind of documentation would you like to see? Just wiki content? Website examples? Video? 

If you had a magic wand ✨ - How would you want to learn about Customizer?

**Comment by marygans** [comment]
It would be nice to have wiki and website documentation and on usage and examples would be nice! Somewhat like what Micah put together in the [Frontend bootcamp](https://microsoft.github.io/frontend-bootcamp/step2-03/demo/). I personally think that would be most helpful. I've also got feedback from designers that's it's difficult to tell developers how to implement theming.

**Comment by ecraig12345** [comment]
I actually think we should leave this open since it's something other people may want as well, and to document that we're working on it. I'll assign to Micah and Paul and then the issue can be linked and closed when a PR adding the docs is submitted.

**Comment by micahgodbolt** [comment]
We could consider adding sections to the left nav of the getting started page

![image](https://user-images.githubusercontent.com/1434956/82383417-9c2bdb80-99e2-11ea-928d-6f159beaaf6a.png)

**Comment by paulgildea** [comment]
@micahgodbolt @marygans Love the ideas folks! We’re going to be experimenting soon on creating more documentation and different formats.

**Comment by ecraig12345** [comment]
@micahgodbolt We should definitely follow that exact design including the..."font"...for the link. 😆

**Comment by micahgodbolt** [comment]
that font is copyrighted (by me)....gonna have to pay up to use it
