### ISSUE TITLE
DetailsList: Navigating in scan mode of narrator it announce on every separation as Blank .

### ISSUE THREAD

**Issue by zhr1130** [microsoft/fluentui#13222]
### Environment Information

- **Package version(s)**: 7.104.0
- **Browser and OS versions**: Edge chromium(Version 83.0.461.1 (Official build) dev (64-bit)).

### Describe the issue:

Narrator is reading "blank" in scan mode and it's not going to header of the list. 

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/pen/?&editable=true=https%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

Repro steps:
1. Go to above codepen.
2. Turn Narrator and focus on "Filter by name" input.
3. Click down arrow is not going to header and narrator keeps reading "Blank" (It worked well on version 6.131.0)

#### Actual behavior:
Narrator is not switching to header section and keeps reading "Blank" when press down arrow.
![narrator](https://user-images.githubusercontent.com/18317674/82272001-41d14300-992e-11ea-8c27-d51564742370.png)

#### Expected behavior:

Narrator should not read blank and goes to header.

### Documentation describing expected behavior

https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7b54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7d

**Comment by aneeshack4** [comment]
@zhr1130 Thanks for reaching out to us! This doesn't repro for me in scan mode and when scan is off:
![image](https://user-images.githubusercontent.com/4161791/82346636-522fff00-99bc-11ea-9f0b-e12adee9b1a0.png)
I use tab though, not down arrow - tab is the expected key here.

**Comment by zhr1130** [comment]
Thanks @aneeshack4 , tab works for me and I confirmed with tester
