### ISSUE TITLE
Narrator is reading as ‘No item in view’ and then reading the control information at some fields while navigating through the interactive controls.

### ISSUE THREAD

**Issue by v-kusudh** [microsoft/fluentui#13243]
Screen Reader: Narrator

Browser Details: ​
**OS: Windows 10 (Version 1909, Build: 18363.778)
Microsoft Edge Dev Version 84.0.495.2 (Official build) dev (64-bit)
Office-ui-fabric-react : "~6.162.1"**

While navigating through tab(couple of times), Narrator is reading as  ‘No item in view’

Actual Result: ​
**Narrator is reading as ‘No item in view’ and then reading the control information at some fields while navigating through the interactive controls.**

 
Expected Result: ​
Screen reader should not read as ‘No item in view’ when focused on a control. It should clearly read the information about focused control.

**Comment by aneeshack4** [comment]
@v-kusudh Which Fluent control are you referring to? Please fill out the complete issue template - otherwise it's not actionable for us. You must provide a codepen with an isolated repro on the Fluent component and detailed repro steps.
