### ISSUE TITLE
Dropdown: support controlled `isOpen` state

### ISSUE THREAD

**Issue by ArashMotamedi** [microsoft/fluentui#13259]
#### Describe the feature that you would like added

The `Dropdown` component automatically opens and closes based on mouse/touch/keyboard events. Desire to control the `open` state. 

```jsx
const [dropdownOpen, setDropdownOpen] = useState(true);

<Dropdown 
   isOpen={dropdownOpen} 
   onOpen={() => setDropdownOpen(true)}
   onClose={() => setDropdownOpen(false)} />
```

#### What component or utility would this be added to

Dropdown

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Would like the ability to programmatically open (expand) or close (collapse) the callout portion of Dropdown component. Use cases: 

1. Ability to close a multi-select dropdown a few seconds after options are selected, or `onMouseLeave`, etc.

**Comment by ecraig12345** [comment]
Thanks for filing this! I'll mark it as a feature request and add it to our backlog,  but we're likely not going to get to it for a while as we're currently focused on larger coherence work items and enhancements to our performance.

I'd also caution against the specific use cases you described--closing after a few seconds or onMouseLeave would both be pretty bad for accessibility, specifically for users with reduced coordination.
