### ISSUE TITLE
Internationalization/localization with Fluent

### ISSUE THREAD

**Issue by ayushgp** [microsoft/fluentui#13251]
Is there an opinionated way to do internationalization/localization in Fluent UI? Or would anyone using it need to use 3rd party react internationalization libraries like https://github.com/i18next/react-i18next to achieve this?

I couldn't find anything mentioned about internationalization/localization in the docs except RTL support.

**Comment by ecraig12345** [comment]
You'll have to use a 3rd-party library. Internally at Microsoft teams have various ways of handling localization, but nothing I'm aware of offhand that's public/reusable, and we don't really have plans of adding anything like that into Fluent UI at the moment (would be nice but we're working on a lot of other things already).
