### ISSUE TITLE
"Checked" icon on the right of menu item is not centered in Toolbar

### ISSUE THREAD

**Issue by sophieH29** [microsoft/fluentui#13265]
### Environment Information

- **Package version(s)**: 

### Describe the issue:

"Checked" icon is not well centered for menu item in Toolbar component

#### Actual behavior:
Screenshot from Fluent:
![image](https://user-images.githubusercontent.com/8460706/82551472-8d6b3300-9b60-11ea-8f7f-8d47c3681fbc.png)

### Priorities and help requested (not applicable if asking question):

Requested priority: Normal

Products/sites affected: Teams meetings (ubar)

**Comment by jakubbrindza** [comment]
Package version: "@fluentui/react": "~0.43.2"

Seems like for us the icon is shifted a but upwards from the centre instead of downwards
<img width="238" alt="Screenshot 2020-05-21 at 13 11 24" src="https://user-images.githubusercontent.com/2866323/82553621-ad9cf100-9b64-11ea-8faf-87463e8cb0f6.png">

**Comment by assuncaocharles** [comment]
Fixed in the latest version.
