### ISSUE TITLE
allowDisabledFocus false not working on split CommandBarButton

### ISSUE THREAD

**Issue by hollymitchie** [microsoft/fluentui#13269]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "7.110.1"
- **Browser and OS versions**: 

### Describe the issue:

I am trying to use the allowDisabledFocus (setting it to false) for a CommandBarButton that I have, which is a split button. However, it's not making data-is-focusable false when the button is disabled.

#### Actual behavior:

data-is-focusable is true on the dom element for the disabled button.

#### Expected behavior:

data-is-focusable should be false.

### If applicable, please provide a codepen repro:

https://codepen.io/hollymitchie/pen/zYveZby
Here, I have allowDisabledFocus={false} and am still seeing data-is-focusable="true" on the element in the dom. I have also tried setting data-is-focusable={false} but am still getting true in the dom.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Potentially yes if a small amount of work and I have the time.

Requested priority: High/blocking. I have an accessibility bug open on me that a disabled button is still getting focus. This attribute would fix the issue. I'm not sure how else to disable the focus.

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
Thanks for reporting this @hollymitchie! I see the repro: 
![image](https://user-images.githubusercontent.com/4161791/82685313-9c61ec00-9c19-11ea-9bc0-170d99900617.png)
Weirdly enough, when I keyboard (tab) the disabled CommandBarButton doesn't get focus... also I noticed the Codepen is using just a regular SplitButton - here's a split CommandBarButton: https://codepen.io/aneeshack4/pen/zYvegKp. Though I notice that the `data-is-focusable` is also true on this disabled split CommandBarButton which is strange... 
![image](https://user-images.githubusercontent.com/4161791/82685990-b4863b00-9c1a-11ea-83ef-dd873d82085f.png)
Tagging @ecraig12345 as she might have more insights into this.
