### ISSUE TITLE
Fortify flagging XSS issue with Nav.base.tsx

### ISSUE THREAD

**Issue by geoffgass** [microsoft/fluentui#13267]
Fortify code scanner is flagging an XSS issue with Nav.base.tsx in the function _isLinkSelected

Line numbers from current master branch are 375-377.

The issue is that location.hash is susceptible to XSS attacks.  I think this is a false positive, but could still be remediated as the code isn't really necessary.

Fortify complains because on line 375 location.hash.substring(1) is set into _urlResolver.href, which is then compared to target on 377.  There appears to be no reason to set location.hash.substring(1) into _urlResolver.href.  377 could directly compare target to location.hash.substring(1).

Again, this is really a false positive because the output of location.hash is only compared, it is never returned, but because _urlResolver is scoped to the entire class (though also not returned in the DOM), the issue is flagged.

**Comment by ecraig12345** [comment]
Thanks for reporting! I agree that this is a false positive, but unfortunately I suspect the logic in question is necessary for certain scenarios and shouldn't be removed.
