### ISSUE TITLE
Selected date in DatePicker on ui fabric is not visible on high contrast mode.

### ISSUE THREAD

**Issue by v-ajrai** [microsoft/fluentui#13282]
Once the Datepicker is launched in high contrast mode ,selected date is not visible.

### Environment Information

OS: Win10
Browser: Edge

### Describe the issue:
Selected Datepickers date should be visible in high contrast mode.Selected date in DatePicker on ui fabric is not visible on high contrast mode.

### Please provide a reproduction of the issue in a codepen:
https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker
![datepicker_external](https://user-images.githubusercontent.com/62233982/82633616-2a89a280-9c19-11ea-9f8e-12ccf6f471d8.png)

#### Actual behavior:

Observed that selected date in DatePicker is not visible on high contrast mode.

#### Expected behavior:

Selected date  in DatePicker should be visible in HC mode

**Comment by aneeshack4** [comment]
@v-ajrai This doesn't repro on Edge Chromium... I don't have Edge on my machine so I can't try this on there. I'd suggest you use the latest browser.
![image](https://user-images.githubusercontent.com/4161791/82689167-ab4b9d00-9c1f-11ea-8e30-0c7f24b28902.png)

**Comment by v-ajrai** [comment]
Hello Aneesha ,

We are now as of latest using Edge[edge-Microsoft Edge 44.18362.449.0] and not chromium version of edge. The issue is repro on office  ui fabric(DatePicker).I would request you to check it on the above  mentioned  browser and not chromium.

Thanks
Ajeet  Kumar rai

________________________________

**Comment by ecraig12345** [comment]
I don't have legacy Edge available for testing, but this works fine in IE11 for me (and they generally use similar high contrast rendering). Since legacy Edge has been replaced by Chromium Edge, and Chromium Edge is available on all Windows versions, even if there is a bug specific to legacy Edge it won't be high-priority for us to fix.
