### ISSUE TITLE
lodash is referenced in charting package but isn't a dep

### ISSUE THREAD

**Issue by brandonthomas** [microsoft/fluentui#13294]
# Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: Windows 10

### Please provide a reproduction of the bug in a codepen:
Pull latest charting package, ensure your package doesn't have a lodash dep in it, and try to build. Build will barf on charting because there are references to it but no dependency listed.

Can work around by adding a dev dep in the consuming application but that's not a real fix.

#### Actual behavior:
Build breaks without consuming app adding dev dep on lodash

#### Expected behavior:
Build works without consumer including lodash if they don't actually require it directly.

### Priorities and help requested:

Are you willing to submit a PR to fix? I can if required

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
I noticed this recently too while working on migrating to eslint including adding a rule to detect unlisted deps. 🙄 Was going to fix it with that change but it's also worth doing separately. Made #13295 with the fix since I'd already implemented it locally.
