### ISSUE TITLE
How could I change the whole theme(default/dark) by using a toggle.

### ISSUE THREAD

**Issue by Mermaid-Liu** [microsoft/fluentui#13307]
### Environment Information

- I have installed FluentUI and my project is based on react.

### Describe the issue:
I want to put a toggle on the head of the platform to change the whole theme(default theme<->dark theme). However, I have no idea to get started.
Whether or not I use the theme control or use the theme slots in the style?

I am looking forward to hearing from you soon ~

**Comment by aneeshack4** [comment]
Hi @Mermaid-Liu, have you checked out aka.ms/themedesigner? You can use the code provided in the export to codepen. Create another theme object (which you can also generate by going back to the theme designer and choose a dark colors in the left) and implement a toggle that applies `Customizations.applySettings({ theme: secondTheme });`
