### ISSUE TITLE
DatePicker  

### ISSUE THREAD

**Issue by DimuthuRoshan** [microsoft/fluentui#13314]
I am using [office-ui-fabric](https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker) in my project for the UI part. 
[office-ui-fabric] has **DatePicker** but it's only supported for the date not for time position. 
I would like to is there a way to get time information also using **DatePicker** component or is there any other component that supports for time?

 **DatePicker** 
![image](https://user-images.githubusercontent.com/40156079/82858990-14d6ee80-9f33-11ea-9a38-1d257ec3f4ec.png)

**Comment by aneeshack4** [comment]
@DimuthuRoshan Hi, thanks for reaching out to us. Time all the way down to the hour and minute is not in scope for the DatePicker. Correct me if I'm wrong @lorejoh12... this could be a feature request though I'm not sure if there are future plans for this component in terms of adding features like this - @lorejoh12 could clarify this.

**Comment by DimuthuRoshan** [comment]
Hi, @lorejoh12 do we have a plan to add this feature in future releases?
