### ISSUE TITLE
Divider: No spaces between the lines and content in RTL context

### ISSUE THREAD

**Issue by abdullahsalem** [microsoft/fluentui#13337]
### Environment Information

- **Package version(s)**: 0.49.0
- **Browser and OS versions**: Not relevant

#### Sandbox: 
https://codesandbox.io/s/divider-content-rtl-jzwql
#### Screenshot:
![Divider with RTL content issue](https://user-images.githubusercontent.com/177020/82986282-4072db00-9ffe-11ea-8703-b84f5e5f59a4.png)

#### Actual behavior:
No spaces between the lines and the content

#### Expected behavior:
There should be spaces between the lines and the content (as the same of LTR context)

### Priorities and help requested:

Are you willing to submit a PR to fix? **Yes**

**Comment by abdullahsalem** [comment]
I've done further tests on that case, and found out that the issue is NOT ONLY related to the RTL context! Therefore, it could also happen in LTR context.

Before I get into the detail of results, I would like to list these factors:
- Fluent UI changes the context by using the native HTML attribute `dir`
- `dir` basically changes the flow direction of document/sub-tree
- The **pseudo-elements** `::before` and `::after` are apart of the [originating-element](https://www.w3.org/TR/selectors-4/#originating-element)'s content
- If the [originating-element](https://www.w3.org/TR/selectors-4/#originating-element)'s content starts with LTR-based language, so the `::before` will be placed on`left` and the `::after` on `right`, but if that content starts with RTL-based language, then the position of `::before` is `right` and `::after` on `left`. Thus, `::before` and `::after` are not always on the same `right/left` position because they depend on the direction of the written language NOT the document/sub-tree's flow direction

#### All tests on Sandbox:
https://codesandbox.io/s/divider-content-rtl-jzwql

#### Screenshot:
![divider-content-issue](https://user-images.githubusercontent.com/177020/83068890-b19fa600-a071-11ea-8b2b-c85260bc1b6d.png)

#### Conclusion:
Such the following CSS rules that predict the positions of `::before` and `::after` would not be applicable to all the scenarios:
https://github.com/microsoft/fluentui/blob/841a10671ccbb61d7803e2931f257c0c6393623b/packages/fluentui/react-northstar/src/themes/teams/components/Divider/dividerStyles.ts#L43

https://github.com/microsoft/fluentui/blob/841a10671ccbb61d7803e2931f257c0c6393623b/packages/fluentui/react-northstar/src/themes/teams/components/Divider/dividerStyles.ts#L47

**Comment by abdullahsalem** [comment]
I've just noticed that **Divider** has `auto` as a value of it's `dir`:
![divider-dir-auto](https://user-images.githubusercontent.com/177020/83072812-1827c280-a078-11ea-9fb6-c5a5ea1a3287.png)

So in this case, the positions of the Content Pseudo-elements  `::before` and `::after` (left and right lines) will be set depending on the content-direction NOT the document/sub-tree's flow direction!

**LTR-language content**: `::before` on ` left` and `::after` on `right`
**RTL-language content**: `::before` on ` right` and `::after` on `left`

Therefore, such of the following CSS rules that predict the positions of `::before` and `::after` would not be applicable to all the scenarios: 
https://github.com/microsoft/fluentui/blob/841a10671ccbb61d7803e2931f257c0c6393623b/packages/fluentui/react-northstar/src/themes/teams/components/Divider/dividerStyles.ts#L43

https://github.com/microsoft/fluentui/blob/841a10671ccbb61d7803e2931f257c0c6393623b/packages/fluentui/react-northstar/src/themes/teams/components/Divider/dividerStyles.ts#L47

#### Tests
Sandbox: 
https://codesandbox.io/s/divider-content-rtl-jzwql

Screenshot:
![divider-content-issue](https://user-images.githubusercontent.com/177020/83074462-e2d0a400-a07a-11ea-9d77-7c0ff0f7b8fd.png)

**Comment by assuncaocharles** [comment]
Hey @abdullahsalem 

RTL content works as expected inside a `<Provider rtl >` and LTR content works as expect in the ltr context. Not sure if LTR text should be working normally inside RTL context. 

Any thoughts? @mnajdova @layershifter @jurokapsiar
