### ISSUE TITLE
Dialog footer buttons vertically misaligned when icon is present

### ISSUE THREAD

**Issue by danmarshall** [microsoft/fluentui#13336]
### Environment Information

- **Package version(s)**: 7.111.0
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/danmar/pen/abvrwwo

#### Actual behavior:

In a DialogFooter, when a button has an icon, it causes vertical misalignment with buttons 
![image](https://user-images.githubusercontent.com/11507384/82978645-ec360f80-9f99-11ea-84e0-cf1839cc4bd4.png)

#### Expected behavior:

Buttons to be aligned whether icons are present or not.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal)

Products/sites affected: Next version of SandDance https://sanddance.js.org/app

**Comment by ecraig12345** [comment]
This actually happens with buttons even outside dialogs. Looks like it's an issue with the icon's taller line-height, but if you add `vertical-align: middle` to both `<button>` elements it's fixed.

@khmakoto Does that fix seem safe to you? And where should it be added? (I see a lot of button styles files.)

**Comment by khmakoto** [comment]
I think that fix is safe, it should probably be added on `BaseButton.styles.ts`.

**Comment by ecraig12345** [comment]
@danmarshall Would you be willing to submit a PR for this?

Whenever this does get fixed, there should definitely be a screener story (visual test) added to cover this scenario (just two buttons, no dialog)--that will go in `apps/vr-tests/src/stories/Button.stories.tsx`.

@khmakoto Are there any other button variants where we should add this? (react-button, react-next, experiments?)

**Comment by khmakoto** [comment]
I'd say probably `react-button`. `react-next` is only exporting `oufr` at the moment and `experiments` is not being worked on.

**Comment by danmarshall** [comment]
@ecraig12345 sure, can you let me know what to change and where?

**Comment by ecraig12345** [comment]
Still an issue. https://codepen.io/ecraig12345/pen/jOBwarE?editors=0010
