### ISSUE TITLE
Can't load Fluent UI CSS to iframe

### ISSUE THREAD

**Issue by nirtz89** [microsoft/fluentui#13344]
### Environment Information

Fluent UI React

- **Package version(s)**: 7.75.0
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

I'm Trying to use React.Portal to render a fabric ui component inside an iframe, the component gets rendered with the correct Fluent UIs classes, but has no Fluent UI CSS.

#### Expected behavior:

Fluent components inside iframe should have Fluents CSS.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by aneeshack4** [comment]
@nirtz89 Please make a codepen and give detailed steps to repro so this is actionable for us.
