### ISSUE TITLE
Can't deselect an item by clicking it in detailslist

### ISSUE THREAD

**Issue by JoshuaLamusga** [microsoft/fluentui#13353]
### Environment Information
**Repros here**
https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic

#### Actual behavior:
Clicking on a selected item in the detailslist doesn't deselect it. Referring to clicking on the row itself, not the checkbox for de/selecting that row.

#### Expected behavior:
If clicking on an item in the detailslist selects it, clicking on it again should deselect it. Also curious why it's set to work this way, if it's a design decision.

### Priorities and help requested:
Are you willing to submit a PR to fix? (Yes, No) **No**

Requested priority: (Blocking, High, Normal, Low) **Low**

**Comment by aneeshack4** [comment]
@JoshuaLamusga I believe this is by design. When we consider a redesign in this component in the future, we'll consider your feedback so thanks for reaching out to us. :)
