### ISSUE TITLE
Pressed state of buttons doesn't clear with focus shift

### ISSUE THREAD

**Issue by JoshuaLamusga** [microsoft/fluentui#13364]
### Please provide a reproduction of the bug in a codepen:
https://developer.microsoft.com/en-us/fluentui#/controls/web/button

Steps:
1. Tab to a button, hold down space and while holding space, tab away
2. Observe the button retains its pressed state

#### Actual behavior:
The button retains its pressed state

#### Expected behavior:
The button should change to its idle state once focus changes

### Priorities and help requested:
Are you willing to submit a PR to fix? (Yes, No) No
Requested priority: (Blocking, High, Normal, Low) Low

### Screenshots
From the Fabric site, I've managed to get most buttons in a "pressed down" state this way.
![image](https://user-images.githubusercontent.com/30244654/83078051-85facc80-a02d-11ea-9c40-5b6f3f5284c1.png)

**Comment by aneeshack4** [comment]
@JoshuaLamusga Thanks for reaching out to us. I do repro this on button. On checkbox, when I press space I see that it doesn't get checked (pressed) until after I release the space key which is I think what button needs to do as well. Like you said, this might be low pri - tagging component owner @khmakoto to assess the priority level further.

**Comment by khmakoto** [comment]
@JoshuaLamusga @aneeshack4 I've made [this codepen](https://codepen.io/khmakoto/pen/abvgEGp) where I can reproduce this behavior in regular HTML buttons so I think this is more on the browser and there shouldn't be an expectation for our buttons to behave differently here.

![image](https://user-images.githubusercontent.com/7798177/83184262-0c6ee700-a0de-11ea-8dbf-639e6adca895.png)

**Comment by JoshuaLamusga** [comment]
What an interesting twist of fate! Didn't expect it would be a browser behavior.
