### ISSUE TITLE
fluentui react-northstar exports FocusZone component which should be internal

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#13375]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar 0.49
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/c34m8?module=/example.js
#### Actual behavior:

fluentui react-northstar exports FocusZone component which should be internal

#### Expected behavior:

FocusZone and FocusTrapZone should not be exported, the functionality should be exposed through semantic components.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by mnajdova** [comment]
These components are already used on client’s side, is there some migration plan for them?

**Comment by assuncaocharles** [comment]
It will be fixed by removing components (`FocusZone` and `FocusTrapZone`) from `react-bindings` once `FocusZone` will be in sync.
