### ISSUE TITLE
Guided Tours

### ISSUE THREAD

**Issue by dwootton** [microsoft/fluentui#13379]
#### Describe the feature that you would like added

We’re seeking the ability to build out a guided tour through our UI. Ideally, this would have some form of visual indicator (ie a beacon) and text (ie a description of what the beacon does). Additionally, it would be great to allow you to continue to interact with the ui element that has the beacon on it (ie if you're explaining what a button does, you can still allow for a user to click it and then advance to the next stage of the tour).  Currently, we are using [react joyride](https://github.com/gilbarbara/react-joyride) for this, but we're hoping to stay within the fluent system. 

#### What component or utility would this be added to

Fluent UI coachmarks/teaching bubbles.

#### Have you discussed this feature with our team, and if so, who

Yes, Paul Gildea.

**Comment by ecraig12345** [comment]
We already have a [Coachmark](https://developer.microsoft.com/en-us/fluentui#/controls/web/coachmark) and [TeachingBubble](https://developer.microsoft.com/en-us/fluentui#/controls/web/teachingbubble). If you need help using them you can ask in "Fluent UI Community" ("Fluent UI React" channel) on Teams.

@paulgildea FYI

**Comment by dwootton** [comment]
Thanks Elizabeth. I think I wasn't super clear in my initial request. Our team is looking for  functionality to be built into the coachmark and teaching bubbles allowing for them to become sequential. Currently, the dev will have to handle all of the logic for controlling the current step being displayed. It seems like this could either be it's own component or maybe a prop setting set on coachmarks. In the example provided by react joyride, this is often a multistep process (ie click here, click here, do this) with each step being associated with it's own teaching bubble/coachmark. It seems like dev's would be putting in a lot of time to handle this logic it could probably be handled inside of some internal component.

**Comment by ecraig12345** [comment]
Ah okay, got it. I'll put this on our backlog but it's not something we're likely to get to any time soon since we're currently focusing on larger work items around performance and coherence. Though if this is something you'd be interested in building we'd welcome the contribution. (For reference, we have an example of something similar on the TeachingBubble page.)

**Comment by paulgildea** [comment]
Thanks! 

@ecraig12345 - @dwootton and I chatted earlier this week and he was looking for a full solution. I asked him to file a feature request so we wouldn’t loose it 😁. 

I know there was some interest from design looking at a point of view on tour like experiences. Nothing firm though.

**Comment by Alex1100** [comment]
I am currently building this out for my team at Microsoft. If you're part of the FluentUI core team at Microsoft, please message me on Teams at Alexander Aleksanyan.

I'd be glad to help the team contribute however I can.

@ecraig12345

**Comment by spsme** [comment]
@ecraig12345 @Alex1100 we are currently developing a SPFx solution utilizing Fluent UI and would like to implement a Guided Tour for certain aspects of the solution. Has there been any progress on this? We would like to stay away from adding in third party solutions such as react joyride if at all possible. Thanks in advance!

**Comment by paulgildea** [comment]
@PMcGown - @Alex1100 and I have connected. We need to do another follow on our end. We're trying to reshape some of our contribution model and make this repository more focused on primitive components, but we're doing it incrementally.

**Comment by Alex1100** [comment]
@paulgildea @PMcGown Sorry, The Customer Insights (Engagement Insights & Audience Insights) team(s) are launching on Oct 30th and we are heads down trying to meet deadlines around the board. I will resume work on this feature in November when things cool down.

It is definitely still a work in progress at the moment.
