### ISSUE TITLE
Github releases authors are broken

### ISSUE THREAD

**Issue by yordis** [microsoft/fluentui#13376]
Hey folks, I noticed that your releases are not printing the correct authors names.

### Environment Information

- **Package version(s)**: none
- **Browser and OS versions**: none

### Please provide a reproduction of the bug in a codepen:

Visit the release page: https://github.com/microsoft/fluentui/releases

Notice the author's names.

#### Actual behavior:
`[object Object]` is being printed.

Example:

```
Add autoCapitalize property (PR #13335 by [object Object])
```

#### Expected behavior:

The author name should appear instead of `[object Object]`

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
Thanks for reporting this--thought someone was going to fix it earlier this month but I guess we never got around to it. I'll work on a fix.

**Comment by ecraig12345** [comment]
Fixed all the existing releases and opening a PR to check in the fixed code.
