### ISSUE TITLE
Add onRenderBody for DetailsList

### ISSUE THREAD

**Issue by mdanielcristian** [microsoft/fluentui#13378]
#### Describe the feature that you would like added

We currenty have a few onRender overrides in the DetailsList control (for Row, Header, Item) and they are very usefull, but it would be great if we would also have an onRenderBody override, similar to the one that exists in the Panel component.

This would allow us to wrap the whole body in a component, for example my scenario is to wrap it in the PerfectScrollbar component to offer a great scrolling experience (hidden scroll until hover) and to also have a sticky table header, since only the body would be wrapped in the scroll bar.

#### What component or utility would this be added to

[DetailsList ](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist)

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Example of panel with onRenderBody overwritten. Would be great if we could do the same thing in the DetailsList
![image](https://user-images.githubusercontent.com/30260770/83146869-8a8fb580-a0ff-11ea-8a94-7fc438e52841.png)

**Comment by aneeshack4** [comment]
I’ll mark this as a feature request and add it to our backlog for review. Just to set expectations, we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.

**Comment by mdanielcristian** [comment]
Thanks, no issue, this is not blocking in any way. Good to know that it's in the backlog and it will be here at some point.
