### ISSUE TITLE
Update repo readme with info about @fluentui/react vs. @fluentui/react-northstar

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#13381]
It's not clear looking at the repo readme why we have two package ecosystems in the same repo. We need to add a section (near the top) clarifying this, telling what to use when (including that northstar has less API stability), and mentioning that we eventually intend to converge them.

We should ideally also add a list of the packages contained within the repo and which ones belong to which ecosystem.

This is how I explained it in https://github.com/microsoft/fluentui/issues/13200#issuecomment-635456850:
> `@fluentui/react` version 7 is what used to be known as Office UI Fabric React. It's widely used in Microsoft products and some outside. `@fluentui/react-northstar` (sometimes also called Fluent UI React v0) is what used to be known as Stardust and is mostly used by Microsoft Teams and Teams add-ins. They're in the same repo because we're working on converging them. [More on that here.](https://developer.microsoft.com/en-us/office/blogs/ui-fabric-is-evolving-into-fluent-ui/)<br/><br/>If you're wondering which one to use, the short answer right now is that unless you're developing for Teams (or making a chat/video-centric experience) you should use `@fluentui/react`, due to its more stable API (`@fluentui/react-northstar` due to being v0 may have API breaks in monthly minor releases) and wide usage.

**Comment by abdullahsalem** [comment]
ASAP, please!
👍

**Comment by JustSlone** [comment]
Readme is updated: https://github.com/microsoft/fluentui/blob/master/README.md
We also have a wiki article walking through packages: https://github.com/microsoft/fluentui/wiki/Fluent-UI-React-Repo-Structure
