### ISSUE TITLE
ComboBox: onPendingValueChanged function prop: issue with filtering the options on keyboard input

### ISSUE THREAD

**Issue by sarahkang58** [microsoft/fluentui#13388]
### Environment Information

- **Package version(s)**: ^7.90.1
- **Browser and OS versions**: NA

### Please provide a reproduction of the bug in a codepen:

Sorry, I couldn't figure out how to repro my issue in a codepen, so here are snippets of code:

```
const sample = [{key: "1", text: "1"}, {key: "2", text: "2"}, {key: "3", text: "3"}, {key: "4", text: "4"}, {key: "5", text: "5"}, {key: "10", text: "10"}, {key: "11", text: "11"}, {key: "12", text: "12"}, {key: "90", text: "90"}];

const [ numberOptions, setNumberOptions ] = React.useState<IComboBoxOption[]>(sample);
const handleNumberChange = (option?: IComboBoxOption, index?: number, value?: string): void => {
    window.console.log("val",value);
    window.console.log("opt",option);
    if (value === "") {
        setNumberOptions(sample);
    }
    if (!value || option) {
        return;
    }
    const filteredNumbers: IComboBoxOption[] = sample.filter((num: IComboBoxOption) => {
        return value ? num.text.trim().indexOf(value.trim()) > -1 : false;
    });
    setNumberOptions(filteredNumbers);
};

return (
        <ComboBox
            options = { numberOptions}
            onPendingValueChanged = { handleNumberChange }
        />
    );
```

#### Actual behavior:

In my ComboBox, I would like the options to filter based on the keyboard input. So in my onPendingValueChanged prop, set to the function handleNumberChange, I am filtering based on the value parameter.

However, I noticed when I log "value" and "option" each time the I change the input via keyboard, "value" is undefined for the inputs that equate to actual options, while it is defined for the inputs that don't equate to actual options

So when I type in "9", the options filter correctly (only shows "90" in the dropdown list). This is because "value" is "9", which is what I expected. (Note that there isn't an option "9").

But when I type in "1", the options still show all of the numbers, including 2, 3, 4, 5, and 90. I'm expecting the options to only contain 1, 10, 11, and 12. But it isn't doing that because "value" is weirdly "undefined" (while "option" is {key: '1', text: '1'}).

#### Expected behavior:

Shouldn't "value" always match the current input? Why would "value" be undefined when I clearly have something in the input? Even if "value" matches an existing option, then shouldn't both "value" and "option" be defined? Else, I'm not sure how to filter the options properly...

Also, for a description with some screenshots, please refer to my SO post here: https://stackoverflow.com/questions/61474203/combobox-onpendingvaluechanged-function-prop-issue-with-filtering-the-options

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

**Comment by aneeshack4** [comment]
@sarahkang58 I believe using onPendingValueChanged to filter options by value is a feature request, not behaviour currently possible fully. It has been requested before in #12011 and is being tracked in #6030 so I'll go ahead and close this. We're going through our backlog reviewing feature requests like this so you can check #6030 for an ETA - right now for the next 2 releases we're focused on building primitives that are coherent across Fluent UI and performant so it will like take a while before we address this, just setting expectations. Thank you for reaching out to us!
