### ISSUE TITLE
Move @uifabric packages under @fluentui scope

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#13384]
Part 3/4 in a series of changes that must happen in master *after* v7 development moves to a branch, but *before* beta publishing:
1. #15152 OUFR/react-next merge 
2. #14679 Move date-time components
3. (this) #13384 uifabric/fluentui package renames
4. #14689 set up beta releases

As part of version 8, we'd like to rename our `@uifabric` packages to `@fluentui` (or in a few cases, delete unneeded packages going forward).

~~For packages which are used by the suite, we'll add `@uifabric` aliases (which re-export the `@fluentui` version) so that partners who depend on multiple suite versions won't get multiple versions of all the dependency packages. (Creation of the alias packages will be done at a slightly later point after the renames, but before release--tracked by #15150.)~~

**EDIT:** Trying to handle package renames and getting rid of major-lockstep at the same time turned out to be too complex, so we will be continuing with major-lockstep for now and **NOT** making any alias packages. However, we will likely provide a codemod to help with renames (see #15661).

In some cases, we're changing the names of the `@fluentui` versions of the packages to better match current naming conventions, or to reserve `@fluentui` names for future use.

### Packages to rename (final list)

The table below has been updated with the final list of new package names/scopes.

 | Old name (under `@uifabric`)   | New name (under `@fluentui`) | PR     |
| ------------------------------ | ---------------------------- | ------ |
| `api-docs`                     | same                         | #15617 |
| `azure-themes`                 | same                         | #15454 |
| `charting`                     | `react-charting`             | #15564 |
| `date-time`                    | `react-date-time`            | #15659 |
| `example-app-base`             | `react-docsite-components`   | #15617 |
| `example-data`                 | same                         | #15618 |
| `experiments`                  | `react-experiments`          | #15566 |
| `fabric-website`               | `public-docsite`             | #15439 |
| `fabric-website-resources`     | `public-docsite-resources`   | #15439 |
| `file-type-icons`              | `file-type-icons`            | #15626 |
| `foundation`                   | `foundation-legacy`          | #15595 |
| `icons`                        | `font-icons-mdl2`            | #15603 |
| `@fluentui/react-icons`        | `react-icons-mdl2`           | #15599 |
| `jest-serializer-merge-styles` | same                         | #15615 |
| `mdl2-theme`                   | remove                       | done   |
| `merge-styles`                 | same                         | #15627 |
| `monaco-editor`                | same                         | #15617 |
| `react-cards`                  | same                         | #15586 |
| `react-hooks`                  | same                         | #15629 |
| `set-version`                  | same                         | #15616 |
| `styling`                      | `style-utilities`            | #15567 |
| `test-utilities`               | same                         | #15615 |
| `theme-samples`                | same                         | #15454 |
| `tsx-editor`                   | `react-monaco-editor`        | #15617 |
| `utilities`                    | same                         | #15629 |
| `variants`                     | `scheme-utilities`           | #15598 |
| `webpack-utils`                | `webpack-utilities`          | #15615 |

### Deleted

- `@uifabric/fluent-theme` (variables moved to `@fluentui/theme`; styling is now the default)
- `@uifabric/mdl2-theme` (deprecated styles; can continue using version 7 if needed)
- `@uifabric/lists` (no plan to release in current form)
- `@uifabric/migration` (changing approach)

### Rename script

For later reference, here's a link to the script I wrote to help with the renames https://github.com/microsoft/fluentui/blob/c838c580546dffb42b3eda95f55899c93c14b396/scripts/rename-package.ts

**Comment by xugao** [comment]
@attiqeurrehman - yes, current plan is to rename `@uifabric/variants` to `@fluentui/variants`

**Comment by ecraig12345** [comment]
FYI for anyone subscribed: we've made some changes to the original plan, and the issue description has been updated to reflect those changes (including the final list of new package names).
