### ISSUE TITLE
Add note about grid vs Stack to layout styles page on website

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#13380]
On the Layout page of the website's Styles section (https://developer.microsoft.com/en-us/fluentui#/styles/web/layout), we should add a note that grid styles are not available in Fabric React (only with Fabric Core), and that while you can use Fabric Core with Fabric React, we recommend trying Stack first.

**Comment by kevinvangelder** [comment]
I'm having a hard time understanding how Stack is sufficient to replace Grid in a responsive project, so some documentation around how you would go about implementing normal Grid scenarios in Stack would be very helpful.

For example, I need to know how I would go about having a page laid out like this:
| 2 | 1 |
| 3 | 4 |

Reflow correctly on mobile:
| 1 |
| 2 |
| 3 |
| 4 |

I know how to achieve this with Grid but am having difficulty wrapping my mind around a possible implementation using Stack.

**Comment by ecraig12345** [comment]
Stack doesn't fully replace Fabric Core's grid CSS classes, but it's probably still worth mentioning on the Layout page since it will help in some cases.

The real solution will eventually be a component abstracting [CSS grid](https://css-tricks.com/snippets/css/complete-guide-grid/)--we've wanted to do this for awhile (see #5418) but just haven't had time due to a lot of other work on our plate and limited resources.

In the meantime, it's still be possible to use Fabric Core together with Fluent UI (Fabric) React if you want grid styles but don't want to manually use CSS grid.
