### ISSUE TITLE
MSAL library accessTokenSilent returns ClientAuthError in Firefox

### ISSUE THREAD

**Issue by malvica** [microsoft/fluentui#13391]
Hello,
My team has developed an office add-in for Outlook online and are using **MSAL** library **acquireTokenSilent** to get the token.
Using outlook online in **Firefox browser**, creating a new message in Pop-out window, user clicks on our add-in we make a call to acquireTokenSilent which returns **ClientAuthError: User Login is required.**
The same works when a new message is opened in in-line mode inside Outlook online in Firefox.
All other browsers work fine as well, the issue is only seen in Firefox.

Thanks

**Comment by ecraig12345** [comment]
This sounds like an issue with Outlook online, not Fabric. You'll need to get support from them instead.
