### ISSUE TITLE
Accessibility : After pressing enter on 'Load All Results' button in Tag Picker auto suggestion dropdown, focus is going on to top option in the dropdown

### ISSUE THREAD

**Issue by v-sagsah** [microsoft/fluentui#13396]
**Browser Details: ​**
OS: Windows 10 (Version 1909, Build: 18363.778)
Microsoft Edge Dev Version 84.0.502.0 (Official build) dev (64-bit)
Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Issue:**
**Accessibility :** After pressing enter on **'Load All Results'** button in Tag Picker auto suggestion dropdown, focus is going on to top option in the dropdown.

**Repro Steps:**
1. Go to code pen url https://codepen.io/sagsah/full/dyYBgVg
2. Turn on the screen reader tool, and tab till the textfield.
3. Enter **'a'**, after which a list of 5 names will be populated with **'Load All Results'** button as shown below.
![Screenshot (2)](https://user-images.githubusercontent.com/64409491/83224483-1dc9f900-a19b-11ea-8945-a9948fb5cef3.png)

4. Navitage to  **'Load All Results'** button, and hit enter.
5. Verify where focus is going after pressing enter. It is moving to 1st option.

**Actual Result: ​**
After pressing enter on **'Load All Results'** button in auto suggestion dropdown, focus is going on to top option in the dropdown.

**Expected Result: ​**
Focus should go on to the revealed content which is generated after pressing enter on **'Load All Results'** button i.e. in this case the focus to go to the 6th option.

**User Impact: ​**
Keyboard users may find it difficult to navigate again from 1st option in the dropdown after pressing enter on **'Load All Results'** button.

**Comment by aneeshack4** [comment]
@v-sagsah Thanks for reporting this. I repro this, even without the screenreader. Though it might be by design... tagging @joschect, the component owner to double check - Jon is this intended behavior for the focus to go to the first item upon loading all results? I'm guessing a new list gets placed with all of the results in place of the old one and that's why it's going to the first item.

**Comment by v-sagsah** [comment]
@joschect could you please provide your comments on the same.

**Comment by v-sagsah** [comment]
@joschect  could you please let us know if this is by design or a bug. We are currently blocked due to this issue, on our end, as we have planned release on 1st week of next month.

I would be grateful for your prompt reply.
