### ISSUE TITLE
How to delete that remove button in PeoplePicker? I do not need it

### ISSUE THREAD

**Issue by ManuRodgers** [microsoft/fluentui#13395]
![image](https://user-images.githubusercontent.com/33333844/83209540-f9225100-a19b-11ea-8cd8-839411799876.png)

**Comment by ManuRodgers** [comment]
say I do not need that remove function, so if there is a remove button, it is kind of misleading the end users

**Comment by aneeshack4** [comment]
Hi @ManuRodgers, there's a `showRemoveButtons` prop. Please read the documentation and take a look at our examples with sample code and you'll find how to use this. https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker
