### ISSUE TITLE
  window.addEventListener('resize', this._fitParentContainer) causes missing clientrectangle error

### ISSUE THREAD

**Issue by reijam** [microsoft/fluentui#13404]
### Environment Information

- all versions that I am aware of in the OUIR Charting LineChart module
 
#### Actual behavior:

 `  window.addEventListener('resize', this._fitParentContainer) `

is a line in  **componentDidMount** and the removal is in  **componentWillUnmount**.

 
If the **window.Eventlistener** returns and the component no longer exists  the call to  **_fitParentContainer**   fails spectacularly

Trying to use **window.addEventListener**  is understandable (it is a hard problem to solve)  but   regrettably react does not give us much control over when a component is removed and when the event fires.  For that reason it cannot be relied upon to set  values within a component. 
 
Please remove this line from the repo. Or if you are brave and really clever figure out how to handle async cleanup in react and share it with us mere mortals.

Thanks

**Comment by jdhuntington** [comment]
Hi @reijam - thanks for the report. Are you willing to submit a pull request that removes this line?

**Comment by reijam** [comment]
Yes in theory. I just downloaded the latest master and am having trouble getting the charting module to work stand alone.  The entire OUIR with the 8+ options version from about a month ago works fine but the most recent has some node / yarn issues (I did not bother to post a report about it because it is fairly obvious there is a problem)  
If you can help me get a version of the charting package working i will gladly post it. On the other hand it is just one line and if you have a version yourself working it might be faster to have you do it.

**Comment by shivasai09** [comment]
@reijam  if possible could paste the screenshot of the error??

**Comment by Raghurk** [comment]
@reijam Thank you very much for brining this issue up and for your patience as we worked through this issue. This is now fixed we have removed the event listener.
