### ISSUE TITLE
Request for Resizable Split Container Control

### ISSUE THREAD

**Issue by OceanAirdrop** [microsoft/fluentui#13414]
Hi,

I have looked at the list of controls available but can not find a Resizable Split Container Control.

This would be similar to the Winforms SplitContainer control consisting of a movable bar that divides a container's display area into two re-sizable panels.

Using the latest version of Outlook for the web I can see you have implemented a similar control but I cant see this available in the list of <a href="https://developer.microsoft.com/en-us/fluentui#/controls/web">Fluent UI Web controls.</a>

**Comment by jdhuntington** [comment]
Thanks for the request. You're correct that we don't have this control already.

I will add this as a feature request. Unfortunately it is unlikely that we will be able to provide this control in the near term.

**Comment by OceanAirdrop** [comment]
Hi @jdhuntington. Thanks for the reply and yes, I understand.
