### ISSUE TITLE
Screen reader: tip text present inside Callout is read twice.

### ISSUE THREAD

**Issue by v-kusudh** [microsoft/fluentui#13413]
**Screen Reader: Narrator**

**Repro Link** : https://codepen.io/kusudh/pen/pojMayJ?editors=0010

**Browser Details: ​**
OS: Windows 10 (Version 1909, Build: 18363.778)
Microsoft Edge Dev Version 84.0.495.2 (Official build) dev (64-bit)

**Repro Steps: ​**

1. Start Narrator and navigate to https://codepen.io/kusudh/pen/pojMayJ?editors=0010
2. Tab till "Show FocusTrapCallout" button and then press Enter.
3. Wait until narrator finishes to read the information.

**Actual Result: ​**
Narrator is reading tool-tip details twice.

**Expected Result: ​**
Narrator should reading tool-tip details once.

**Please note :**

1. This issue is not repro with NVDA - chrome.
2. If the tip-text is less( which contain less than 2 points/sentences, then narrator reads the tip text info only once.

**Comment by jdhuntington** [comment]
Hi @v-kusudh - thanks for reporting this issue. 

Unfortunately this looks like an issue with narrator and items with a `tabindex`. I've verified that removing `tabindex` from the `div` causes this control to work as expected, though it has the drawback of not reading the callout immediately. 

I'll file a bug with narrator to get this improved, but in the meantime are you able to implement a workaround? Causing a div to be shown outside the callout might be a reasonable alternative.
