### ISSUE TITLE
Selection constructor gives issue when used in a hook with generic type

### ISSUE THREAD

**Issue by schemburkar** [microsoft/fluentui#13411]
I'm trying to create a hook for using Selections provided by DetailsList.

Short summary of the issue:

```
export function useSelections3<T>() {
    
    type Test:{};

    const selectionComponent1= new Selection<T>({}); // This line gives error : Argument of type '[{}]' is not assignable to parameter of type 'T extends IObjectWithKey ? [] | [ISelectionOptions<T>] : [ISelectionOptionsWithRequiredGetKey<T>]'.ts(2345)

    const selectionComponent2= new Selection<Test>({});
    
}
```
**Actual Details**

I expect something like below to work, but is does not
```
export function useSelections<T>(): [ISelection<T>] {
    
    const selectionComponent: ISelection<T> = new Selection<T>({
        onSelectionChanged: () => {
            //Do something here
        }
    });
    return [selectionComponent];
}

```

It would give the following error:
![image](https://user-images.githubusercontent.com/3159347/83332180-9625dc80-a2b7-11ea-8528-27b4f85ec1de.png)

If I use the non generic version or local type, it works for some reason.

```
export function useSelections1<T>(): [ISelection] {
    
    const selectionComponent: ISelection = new Selection({
        onSelectionChanged: () => {
            //Do something here
        }
    });
    return [selectionComponent];
}


type Test={}
export function useSelections2(): [ISelection<Test>] {
    
    const selectionComponent: ISelection<Test> = new Selection<Test>({
        onSelectionChanged: () => {
            //Do something here
        }
    });
    return [selectionComponent];
}

```

I would expect the first version to work. Does the constructor on Selection need a explicit type rather than a ternary operator ?

Component: Selection
Version: 7.110.5

**Comment by ecraig12345** [comment]
I think it should work if you do `T extends IObjectWithKey`.

The types for the constructor should be correct--they're just unfortunately rather hard to read because we couldn't find a better way to express the constraints we wanted. It's explained in the comments on the constructor (copied below) but basically the types are that way to ensure that you either provide items with a key, or provide options with a getKey function.
```ts
  /**
   * Create a new Selection. If `TItem` does not have a `key` property, you must provide an options
   * object with a `getKey` implementation. Providing options is optional otherwise.
   * (At most one `options` object is accepted.)
   */
  constructor(
    ...options: TItem extends IObjectWithKey // If the item type has a built-in key...
      ? [] | [ISelectionOptions<TItem>] // Then the arguments can be empty or have the options without `getKey`
      : [ISelectionOptionsWithRequiredGetKey<TItem>] // Otherwise, arguments require options with `getKey`.
  )
```

**Comment by schemburkar** [comment]
@ecraig12345 I've tried setting T​ ​extends​ ​IObjectWithKey on the hook. Error remains same, hence I was confused.

**Comment by ecraig12345** [comment]
I messed with this some too and confirmed that it continues to give an error even if T is explicitly declared as `T extends IObjectWithKey`--and I have no idea why. It almost seems as if having 2 layers of generics messes up the type inference somehow? @ThomasMichon any ideas?

**Comment by ecraig12345** [comment]
This is the code I used ([playground link](https://www.typescriptlang.org/play/index.html#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQHkAjAK2GxgHUEYALAaWAE84BvAKDjgGsWB+AFxwAzjCjIA5nAA+cJAFcAtsTQBuDgF8OHUJFiIUaLLgIBlYABsKMBBCSEwt+yIA8AFXyolcALwESckoaeiZmAD52Ljh7C2tKOyQAYTpMJElgABMhOAAKAEo-SIA3CARMjW4AegAqGrgkhTEIH0sISQRsOBgIOAykNExURG9eFhEAOjgAJWAARwUEKCzEdDgAA09vdbhMiGAReQh4VOK8TA2+Zh2wKAgwNBhmKZqq6IyYMJzc2mAlYS2fwANIZMqAcooVGhCr5ImIJOlZPJlKooJU4Ng0nEbF4-t9fv84IClCDkGCQBCUdCinBiBAINY0uiCSIcsSANoAXQ02l04Gg8CeD3MVhsiUcziQIhCdFmCyWWQA4sBPiwPLilJF-PhsQl7BLEm5iZEAGTROWLZaZVwABU6PFcOtFeocTkN6u84RBAHIPmFveFwho+fp4NhLJgRIddZKPX8-AEyDYZWFIpxqnVonB6kllkNzvJgAB3OAxxJTfBrTYanZ7A5HE6YM5wC7rK43O4PWDMEHMCAKOBKJrwW4QYrlc5IGJulxZ+oQJOUOBF2h0FsbP0sHYIJRgaxKYAoIbluA2u7jzJSaeSw4IQ73SWYSwxehoFciYATOd5ACC8CUEBiDEAwbA+ho7AuQTwHeLbYLgThZBM+Rzm83DYC44gKJQ0C5FmcATARYEuACGpwKAqBIJkhxEIu1CrmEcBVFUBBrK+IzxkKeCpIcFzEIslgwAAtMgYzPAReHcPwcBcki7JOvEkoGi4caapyjHMe4dCHt0WktlAkjKIeMCHJiU6qGRu5PDEUBwKceBsURUrLqu-bwOsm7XBJcDCHJZb6jOUoyhaCqZMqqrMCp4RqUxcCEK+UDvsAIKYPphkoIcyzyss16Gs59AbiqYTrF+3CFOmcDaLyegCnA6AKEgLpwE0wB+VKHhkSAFFUYmUEpiw4QFFE3CcUSBzwP4bCaMG1TMWgdxQIc6DQLSxxrhArFaR+0ToVK8AfgpiQAIwJgMJatR4A2Tfk6I7UBjkiAATAmk0ttRrVKYFq7BVaYVhBdN0YaIzqSk9-inaWwOJBduT3Q913bYD90AMzPZor0igd-k3gDu1A5jSAo2DxYQ-j0PI-D0QxUW0A8CICO4-tYr2AALCdxPne4Y2XZo8OaEAA)):
```ts
export function useSelections<T extends IObjectWithKey>() {
  type Test = {};

  // errors for both of these
  const selection1 = new Selection<T>({});
  const options2 = {} as ISelectionOptionsWithRequiredGetKey<T>;
  const selection2 = new Selection<T>(options2);
  const options3 = {} as ISelectionOptions;
  const selection3 = new Selection<T>(options3);

  // works
  const selection4 = new Selection<Test>({});
}
```

**Comment by ecraig12345** [comment]
I talked about this with Thomas and I'm not sure how much we'll be able to do here.

At first we thought the fact that `IObjectWithKey.key` is optional was the problem (it should probably be required, but we can't change that outside a major version), but even [making it required doesn't fix the problem](https://www.typescriptlang.org/play/index.html?ssl=47&ssc=2&pln=32&pc=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQHkAjAK2GxgHUEYALAJWAEcBXBKYAEwGlgBPOAG8AUHDgBrAQC44AZxhRkAczgAfOElYBbYmgDcIgL4iRoSLEQo0WXAQDKwADYUYCCEkJg3HuQB4AFXxUbTgAXgISckoaeiY2Dm4+fgA+YTE4D0cXSnckAGE6TCRlbgB+WQAKAEpwtIA3CAQuQ3EAegAqDrh81gUIUKcIZQRsOBgIOFKkNExURBDJATkAOjh49k4uRHQ4AAMgkL24LghgOU0IeCL6vEx9qX5jsCgIMDQYfjWOtozSmGSFTglVowG0skOYIANFYuKAgVpdGhamE0golCV1JodHooIYTGZwNB4J93g5nK48l4fEg5LFGCxNtwAOLAAECQLBMFpCL4bKUjzUvL+SHaNIAMgyG0SXD8AAVRhI-HyKblBd5hZyQikYQByf7JXUpFKGQkWeDYJyYOQXflqpBasHhSJkVz06VbZJpUTtLoZODdfKcOZ3TTAADucDtNLW+F2By52mOp3Ol2umFucHue0ez1e71g-Bh-AgrDg2j68BeEHqzTuSEyGt8-u6EFdlDg4dodCz+wNAmOCG0YBc2mAKDmeTWcteta4KkbNIuCAubxpmCcmXoaC7cmAKxbwIAgvBtBAFJkZvs18Ljm3ovAV1nsLhvNwVtUW79xNhfIpWJQ0CVP6cArGBN6+BCiZwKAqBIFwFxEO21Ddh6SQCHAbRtAQuzbgsTqkngRQXPcxDsE4MAALTIEsXxgSB4hlHAADaAC6WLMSqOQ0kKviOmK7FYXAAR0OO4yiVmUDKDo44wBc2DFHAegwcOnyZFAcA3HgeEQbSnbdqW8B7P2TwMXAsicdGVJNrS7qMjKrLsvw-EpIJ2GENuUC7sAMKYFJMkoBcnAJJwi7Cvp9B9myyR7Ae4i1D6cAmAShHCec8AREIRiGEJch0KWTjbFpMFQK8UAiL+tLwHu3F5AE6XOjMkZWR4gTpSklRZdUprmMScDoKwSD2nAfTAC1tIAHIQMkgQdQlGS5flrCFZpGZ4GgZVyBklUXjVApIAAjI1EZRqqNKzZ1Rjddtf7yGdeQAEzHc192tQEHVZVmiHjbxtKzddC3YXlBXbMpEASJg-A3VVd21R4ADMz2nXDDrvZdX3kijv10qh9lbI5M3vQDBK9ZYA1DTSI17uNOP0ITMEgHBCEug+dkhehqQ1Ok7RA0tK1gxDUM-rde32kdERNcj+0XV1rRwDt1WvUgT0Syd40y0YGNcft2P-XLCuw-tiOqy9KMa1rP02bTDLs1wBMckT+JAA).

What we really want to express is something like this for the type of the Selection class constructor, except TS doesn't currently allow type parameters inline for the constructor.
```ts
class Selection<TItem = IObjectWithKey> {
  // NOT SUPPORTED BY TS
  constructor<T extends Required<IObjectWithKey>>(options?: ISelectionOptions<T>): Selection<T>;
  constructor<T>(options: ISelectionOptionsWithRequiredGetKey<T>): Selection<T>;
  // + implementation...
}
``` 

One workaround (which would have the desired results for enforcing types) is [something like this](https://www.typescriptlang.org/play/index.html#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQHkAjAK2GxgHUEYALAaWAE84BvAKDjgGsWB+AFxwAzjCjIA5nAA+cJAFcAtsTQBuDgF8OHUJFiIUaLLgIBlYABsKMBBCSEwt+yIA8AFXyolcALwESckoaeiZmAD52Ljh7C2tKOyQAYTpMJElgABMhOAAKAEo-SIA3CARMjW4AegAqGrgkhTEIH0sISQRsOBgIOAykNExURG9eFhEAOjgAJWAARwUEKCzEdDgAA09vdbhMiGAReQh4VOK8TA2+Zh2wKAgwNBhmKZqq6IyYMJzc2mAlYS2fwANIZMqAcooVGhCr5ImIJOlZPJlKooBptLpwNB4E8HuYrDZEo5nEgRCE6LMFkssgBxYCfFgeLx-SL+fBxQn2YmJNyApSRABk0Upi2WmVcAAVOjxXOyCQkuU4eUzvOEQQByD5hdXhcIaTH6eDYSyYESHAD6HIVSBVfz8ATINnJYUinGqdWicHqSWWQ3O8mAAHc4FaSVN8GtNsylDs9gcjidMGc4Bd1lcbncHrBmCDmBAFHAlE14LcIMVyuckDElS5PfUII7KHBA7Q6CmNlqWDsEEowNYlMAUENElMJXdy5kpNWSYcEId7iTMJYYvQ0C2RMAJnW8gBBeBKCBiGIDDYLnk7BtBeBzlPYXBOLITfJ1t7cbAucQKSjQXKeuATACzxcAFozgUBUCQTJDhFalxSIRtqFbF04CqKoCDWVcRjtXE8FSQ4LmIRZLBgABaZAxmeAC-24fg4AAbQAXSROi5XiEluRcW1+SY1C4HcOhB26ASUygSRlEHGBDmwNI4FUMDeyeGIoDgU48EwoDSWbVt83gdZO2uai4GEFjQyJGtSXJGCxTpBlmC48IeLQwhVygddgBBTBRPElBDmWKllmnHktPoDt6TCdYt24Qo3TgbQMT0bFDFQDAcDwVjOWSD8oC-HplJigZgw8MCQAgqCZnmUUsllQInSQlhdVyDSRBydLrQ40kPHCfJhEteUSU6yoA0K9xwka8yRGEVr2PGyyKtgmywk67q4F6tjEgGrQdASgx31JeBTPse1VoylNDimxIkiynLoH1HC+IOeB-DYTQNF4kQ6HzSxMhUpM8DQO4oA4Xajw3Nb7HcB77QKkM+vWiGxFG578n1bb4HQBQkGtOAmmAA7SQAOQgRaRoKKJqjQ97Pu+1SwKgAGRGiYH4FBjKAEYoaDGGwZtEmkcGpnRFh+wACYOeDPHOtyZ7Tvxbn2t5Lr9XJ0QPoUL7ZLwCAeEwZhGY-QXuYAZjFrmMsl6XTVljL5dm-zaTCxkRuRnR4qxAx0cxklsY3PGyVbdql2J4rSrOmrgjqiJSZit7VfVmn-ugBm331lnrXZ-xoYl3nNGd5O9oNjLRYzzms8RzQZfOxUZyWpWUIp2PvrkrWdb1-PU5JY3i-FoWebLiu8Zt1srPt2ya82g1Eo9rGcd951HeDwcyuHuCw8Q0J6tG6LohjqmNZibXdbzkGe-TobTetc2c-5lOe6Ls-S6l8vLcrhxxrHo-mZ7zv757y-+57we9Bl4LUdorLQQA):
```ts
interface ISelectionConstructor {
  new <T extends Required<IObjectWithKey>>(options?: ISelectionOptions<T>): Selection<T>;
  new <T>(options: ISelectionOptionsWithRequiredGetKey<T>): Selection<T>;
}

export class _Selection<TItem = IObjectWithKey> {
  /* ... current Selection implementation ... */
}

export const Selection = _Selection as ISelectionConstructor;
export type Selection = typeof _Selection;
```

However this has some major downsides:
- It's generally convoluted
- It would be hard to get the documentation to show up in a clear/helpful way on our [documentation site](https://developer.microsoft.com/en-us/fluentui#/controls/web/references/selection)
- I'm not entirely sure what the implications (if any) would be for consumers.

**Comment by schemburkar** [comment]
Thanks @ecraig12345 and @ThomasMichon for the analysis. Appreciated! 

I agree with you that the solution is not straightforward and that is fine. One thing to note is that the syntax of `Selection<T>`is also broken anyways for generic types. 

A suggestion: can we have a simpler, clearer solution if we go for a breaking change targeted for a major release?

I would rather have this fixed in the best way than a complex fix or open issue.

**Comment by ecraig12345** [comment]
Unfortunately I'm not sure a clean solution exists with current TS features, since what we need for a clean solution is type parameter inference in the constructor (I suspect someone has filed an issue with TS about this but am having trouble finding it).

Not sure what you mean by this?
> One thing to note is that the syntax of `Selection<T>`is also broken anyways for generic types.

**Comment by schemburkar** [comment]
@ecraig12345 sorry if I wasn't that clear. What I meant was anyone wanting to use the `Selection` api in generic form, like your example gives errors


Generic usage:
```
export​ ​function​ ​useSelections​<​T​ ​extends​ ​IObjectWithKey​>​(​)​ ​{​
  ​// errors 
  ​const​ ​selection1​ ​=​ ​new​ ​Selection​<​T​>​(​{​}​)​;​
​}
```

Even if we don't have a clean solution, something like above needs to work. 

So I think the Selection code base can be refactored so that it's usage works, even if it could mean relaxing certain annotations on the constructor. Something like:

```
constructor​(​
    ...​options​: ​ ​{} | ​​ISelectionOptions​<​TItem​>​ ​|
      ISelectionOptionsWithRequiredGetKey​<​TItem​>​ | undefined 
  ​)
```

However any of this would need a breaking change in a major version. I'm open to further discussions.

**Comment by nlips** [comment]
In my opinion the typescript compiler has a bug concerning constraints on type parameters.

I want to be able to define a generic hook associated to a type that does not implement `IObjectWithKey` :

```typescript
import * as UI from 'office-ui-fabric-react';

interface IObjectWithId {
    readonly Id: string;
}

export function useSingleSelection<TItem extends IObjectWithId>() {
    const selectionOptions: UI.ISelectionOptionsWithRequiredGetKey<TItem> = {
        getKey(item: TItem, index?: number): string | number {
            return item.Id;
        },
        selectionMode: UI.SelectionMode.single
    };
    const selection = new UI.Selection<TItem>(selectionOptions);
    ...
}

```

`selectionOptions` is not accepted in the `UI.Selection constructor`

> Argument of type '[ISelectionOptionsWithRequiredGetKey<TItem>]' is not assignable to parameter of type 'TItem extends IObjectWithKey ? [] | [ISelectionOptions<TItem>] : [ISelectionOptionsWithRequiredGetKey<TItem>]'.  TS2345

The workaround is to use `any` instead of `TItem` in `selectionOptions` declaration and cast the selection object.

```typescript
export function useSingleSelection<TItem extends IObjectWithId>() {
    const selectionOptions: UI.ISelectionOptionsWithRequiredGetKey<any> = {
        getKey(item: TItem, index?: number): string | number {
            return item.Id;
        },
        selectionMode: UI.SelectionMode.single
    };
    const selection = new UI.Selection<any>(selectionOptions) as UI.ISelection<TItem>;
    ...
}
```
