### ISSUE TITLE
Investigate if Pivot should use onKeyDown instead of onKeyPress

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#13429]
From feedback on PR #13370, need to fix up key handling for Pivot

>> is it intentional to use onKeyPress instead of onKeyDown which is typically used for keyboard handling?

_Originally posted by @jurokapsiar in https://github.com/microsoft/fluentui/pull/13370_

**Comment by jurokapsiar** [comment]
Keypress is deprecated: https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event
