### ISSUE TITLE
ComboBox does not properly highlight the selected option when the context menu is open

### ISSUE THREAD

**Issue by kopgenorth** [microsoft/fluentui#13423]
### Environment Information

- **Package version(s)**: 7.18.0
- **Browser and OS versions**: Chrome, Windows 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/kiaser90/pen/eYJOGQg

#### Actual behavior:

The selected option is not highlighted in the option context menu.

#### Expected behavior:

The selected option should be highlighted in the option context menu (different background)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)

**Comment by jdhuntington** [comment]
Relevant thread: https://github.com/microsoft/fluentui/pull/11900

**Comment by jdhuntington** [comment]
@betrue-final-final This seems like a reasonable request. Can you please comment on how this should look?
