### ISSUE TITLE
isBeakVisible has no effect on IContextualMenuItem object

### ISSUE THREAD

**Issue by bbung** [microsoft/fluentui#13455]
### Environment Information

- **Package version(s)**: please see codepen, i used the example from docs and just added this prop
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/bbung/pen/rNxNoob?editors=0010

#### Actual behavior:

Beak is still visible.

#### Expected behavior:

Beak should Not be visible

### Priorities and help requested:

Are you willing to submit a PR to fix? Not yet

Requested priority: 
Products

**Comment by jdhuntington** [comment]
Thanks for the report @bbung . Unfortunately I don't see the beak visible in the example you've posted. Mind highlighting the area in a screenshot? Also would be great to know what os/browser you are using.

**Comment by bbung** [comment]
Hey @jdhuntington thanks for looking into it.

I am using the lasted versions of chrome, edge and fireforx, all show the beak. Maybe i missunderstood what the beak is?! Here is a screenshot with the beak showing.

![beakShouldNotBeVisible](https://user-images.githubusercontent.com/1083986/83730964-15196d00-a64a-11ea-9d93-7d61b2ba3d39.PNG)


Thanks and kind regards

Chrome: 83.0.4103.61 (Official Build) (64-bit)
Edge: 83.0.478.44 (Official build) (64-bit)

**Comment by bbung** [comment]
Ok, i misunderstood what the beak is. Sorry for that. 

Closing this issue. If you could tell me if it is possible to hide the beak i pointed out that would be much appreciated.
