### ISSUE TITLE
Dialog with no title and with close option is misaligned

### ISSUE THREAD

**Issue by LALCO1011** [microsoft/fluentui#13458]
### Environment Information

- **Package version(s)**: 7.86.0
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/LALCO1011/pen/RwrwmyQ

#### Actual behavior:
![image](https://user-images.githubusercontent.com/66398558/83708023-35a4e100-a5d0-11ea-9947-f54c20b245a3.png)![image](https://user-images.githubusercontent.com/66398558/83708266-b5cb4680-a5d0-11ea-9107-36d7eefa456a.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/66398558/83708090-43f2fd00-a5d0-11ea-8eb9-d9f542a1b755.png)

With or without the subject title, the "X" should be aligned with header, not the subtext.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Microsoft PowerApps

**Comment by paulgildea** [comment]
Please determine if there was a recent regression.
