### ISSUE TITLE
VerticalStackedBarChart : X axis point text getting overlapped

### ISSUE THREAD

**Issue by bhaveshbhati** [microsoft/fluentui#13460]
### Environment Information

- **Package version(s)**: 2.2.27
- **Browser and OS versions**: Chrome, Windows 10
#### Actual behavior:
![image](https://user-images.githubusercontent.com/1016447/83714917-c79d0000-a649-11ea-88bf-a2afc82d08c5.png)

X axis point text getting overlapped.

#### Expected behavior:

X axis point text should not get overlapped.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable) M365 Security & Compliance Center

**Comment by paulgildea** [comment]
@bhaveshbhati is it possible to provide @Raghurk a link to a repro. From the screenshot it looks like it's an issue.
