### ISSUE TITLE
VerticalStackedBarChart renders chart that extends beyond given width & height dimensions

### ISSUE THREAD

**Issue by tusharjape-msft** [microsoft/fluentui#13463]
### Environment Information

- **Package version(s)**: @uifabric/charting v2.2.21
- **Browser and OS versions**: All browsers

#### Actual behavior:
![image](https://user-images.githubusercontent.com/66400291/83722082-fde27b80-a659-11ea-9a04-46745c1c161e.png)
Chart extends beyond its dimensions

#### Expected behavior:
![image](https://user-images.githubusercontent.com/66400291/83722132-16eb2c80-a65a-11ea-8155-443878da0da0.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@Raghurk looks another issue with truncation - can you have someone take a look at this issue?
