### ISSUE TITLE
Missing childrenGap type for Stack 

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/fluentui#13470]
### Environment Information

- **Package version(s)**: 7.117.1
- **Browser and OS versions**: NA

### Please provide a reproduction of the bug in a codepen:

NA

#### Actual behavior:

The `gap` property for `<Stack>` throws a deprecation warning and to use `childrenGap` instead, but this property is missing from the TypeScript definitions.

#### Expected behavior:

A childrenGap property exists for the `<Stack>` component

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes - but I'm very busy so if someone else would like to before I can please do!

Requested priority: Normal

Products/sites affected: NA

**Comment by paulgildea** [comment]
Thanks for the feedback. 

It looks like `childrenGap` needs to be passed in through the `tokens` prop:
```ts
const containerStackTokens: IStackTokens = { childrenGap: 5 };
```
@khmakoto does that sound right? I'd recommend we update depreciation warning to be more clear on how they move from the `gap` prop to using the `IStackTokens` interface

**Comment by khmakoto** [comment]
@paulgildea That is correct. Our message does say that it is a token, but I'll update it to make explicit reference to `IStackTokens`.

**Comment by Ethan-Arrowood** [comment]
Thank you for the quick turn around on this ❤️
