### ISSUE TITLE
ChoiceGroup focus issue IE11

### ISSUE THREAD

**Issue by eskaarup** [microsoft/fluentui#13475]
The ChoiceGroup rendering for focus on items is  not working 100% for Internet Explorer 11

This problem can actually be replicated  directly on :
https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup

Using IE11 and moving the mouse over the options will fire focus event and trigger the black background element, however the elements are not always cleared after focus on the option.

![image](https://user-images.githubusercontent.com/22221000/83795818-550b3f00-a6a0-11ea-9c3b-4941af79ebe8.png)

Works perfect in Chrome, Edge, Edge Dev

**Comment by paulgildea** [comment]
@eikawata Thanks for the feedback. We weren't able to get a consistent repro of the issue it happened intermittently. We found that if you simplify moved the mouse over the options again it would correct itself. Meaning a customer could get out of that state and the UI wasn't stuck in that state.

This is a won't fix for now based on the impact on our initial findings. 

If you would like to submit a PR for a fix we'd happily take a look at it.

Thanks!

**Comment by eikawata** [comment]
@paulgildea Np. Did you perhaps reply to me by mistake? I believe @eskaarup opened this issue.

**Comment by paulgildea** [comment]
@eikawata Sorry about that!
