### ISSUE TITLE
Legend Duplication in VerticalBarChart

### ISSUE THREAD

**Issue by tusharjape-msft** [microsoft/fluentui#13498]
### Environment Information

- **Package version(s)**: @uifabric/charting 1.1.0
- **Browser and OS versions**: All browsers

#### Actual behavior:

![legend-duplication](https://user-images.githubusercontent.com/66400291/83946991-df36dd00-a831-11ea-93e8-5ec164646a0c.PNG)
Legend duplication (see first legend)

#### Expected behavior:

![no-legend-duplication](https://user-images.githubusercontent.com/66400291/83947004-f5dd3400-a831-11ea-98ad-ea4dfb4f592e.PNG)
No legend duplication (see first legend)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/sites affected: (if applicable)

**Comment by tusharjape-msft** [comment]
Submitted PR for this #13499

**Comment by paulgildea** [comment]
@Raghurk Please take a look at this PR 😄 . Thanks!
