### ISSUE TITLE
License refers to non-existent document

### ISSUE THREAD

**Issue by dmitriyyepishin** [microsoft/fluentui#13494]
The license file refers to https://aka.ms/fluentui-assets-license, which refers to Microsoft Developer Agreement which is linked to https://docs.microsoft.com/en-us/legal/mdsa?redirectedfrom=MSDN and this link points to a non-existing document (404).

Please update whatever needs to be updated so that we can obtain all the licences related to this project. Without this our legal department will not allow us to use this library.

Requested priority: Blocking

**Comment by paulgildea** [comment]
@dmitriyyepishin Thanks for finding that issue! 

We've contacted the folks that created the original license to include the updated link.

**Comment by Jahnp** [comment]
This looks like the result of a faulty find & replace from this PR; see [this diff](https://github.com/microsoft/fluentui/commit/0b0df50c68ee6996f39470c308af8a0eb9b24f81#diff-9879d6db96fd29134fc802214163b95a). The original link should be https://aka.ms/fabric-assets-license. I think a new aka.ms link would need to be created to point to the original document.

cc @micahgodbolt

**Comment by dmitriyyepishin** [comment]
The two short links you mentioned redirect to the same document: https://static2.sharepointonline.com/files/fabric/assets/microsoft_fabric_assets_license_agreement_nov_2019.pdf
The issue is the link in the pdf points to "https://docs.microsoft.com/en-us/legal/mdsa?redirectedfrom=MSDN" resulting in 404-Page not found

**Comment by Jahnp** [comment]
Oops—so sorry. Looks like I misread the original issue. My bad. Indeed, @paulgildea is following up internally on this.
