### ISSUE TITLE
Clicking Dropdown in ComboBox when openOnKeyboardFocus = true opens and then closes the dropdown

### ISSUE THREAD

**Issue by Ashwin-Nikam** [microsoft/fluentui#13495]
### Environment Information

- **Package version(s)**: 7.116.1
- **Browser and OS versions**: Chrome, Windows 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/ashwin-7/pen/ZEQGYvx?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

#### Actual behavior:
When we click the ComboBox for the first time the dropdown opens and closes. I think this is an issue which was already reported and resolved so maybe there is some regression.

Here's the previous issue link: https://github.com/microsoft/fluentui/issues/10747
Here's the previous PR: https://github.com/microsoft/fluentui/pull/10748

#### Expected behavior:

Clicking Dropdown with openOnKeyboardFocus true opens the dropdown

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OWA

**Comment by paulgildea** [comment]
@Ashwin-Nikam Thanks for the links to the previous issues!

@joschect - is this a regression?
