### ISSUE TITLE
SpinButton value not updating as I type real time when the value prop is passed

### ISSUE THREAD

**Issue by Ashwin-Nikam** [microsoft/fluentui#13538]
### Environment Information

- **Package version(s)**:  7.116.1
- **Browser and OS versions**: Chrome, Windows

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/ashwin-7/pen/ZEQQWBo?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

Please note in codepen the value prop is passed as a constant so even when I type something and press enter it won't change but the main issue is I can't see what I'm typing. Also I changed the fabric version in codepen to point to 7.116.1 to replicate this.

#### Actual behavior:
Whenever we type a value in SpinButton we can't see what we're typing. The SpinButton still shows whatever was the value prop passed at the start. Once we click anywhere else the SpinButton loses focus as expected and the new typed value is seen inside the SpinButton. I noticed this behavior only when the value prop is passed to the SpinButton. Also I noticed this regression once we updated 

office-ui-fabric-react": "^7.105.0   =>  "office-ui-fabric-react": "^7.116.1"

#### Expected behavior:
Whenever we type a value in SpinButton the input field inside the SpinButton should show what we're typing. Once we click anywhere outside or press enter the value of the SpinButton is updated to what we typed.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OWA

**Comment by jdhuntington** [comment]
Good question. 

Either method should work. However, the first method you mentioned is (in my opinion) more idiomatic in React and would be easier to understand for anyone new to the system.

I would prefer an implementation like https://codepen.io/jdh-msft/pen/yLeeZaz?editors=1010

However, the second method is completely legitimate as well. In the end it is a question of what you prefer in your codebase.
