### ISSUE TITLE
Build error when turning on the `composite` flag in tsconfig.json file

### ISSUE THREAD

**Issue by dotnetjunky** [microsoft/fluentui#13535]
### Environment Information

- **Package version(s)**: 7.118.1
- **Browser and OS versions**: Edge on MacOS (I don't think the specific version of OS matters)

### Please provide a reproduction of the bug in a codepen:

In my `tsconfig.json` file, if I set the `composite` flag to `true`, I'l get this compiler error: 

```
[1:39:40 PM] x ../../node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(27,11): error TS2313: Type parameter 'P' has a circular constraint.
../../node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(27,11): error TS2313: Type parameter 'P' has a circular constraint.
../../node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(30,15): error TS2313: Type parameter 'P' has a circular constraint.
```
Here's my entire `tsconfig.json` file:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "jsx": "react",
    "declaration": true,
    "outDir": "./lib",
    "strict": true,
    "moduleResolution": "node",
    "declarationMap": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "composite": true,
    "rootDir": "src",
    "typeRoots": ["node_modules/@types", "../../node_modules/@types"]
  },
  "include": ["src/**/*"]
}
```

My TS version is 3.9. If I set `composite` to `false`, the error goes away.

#### Actual behavior:

Build error above occurs.

#### Expected behavior:

No build error.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: http://aks.ms/fontpicker

**Comment by dotnetjunky** [comment]
@dzearing FYI, this is yet another TS build error in the `merge-styles` package.

**Comment by jdhuntington** [comment]
Thanks for the report.

As an FYI, there are some pretty serious negative side effects caused by TS3.9 as it relates to bundle size, so we're not prioritizing compatibility at the moment.

**Comment by jdhuntington** [comment]
This looks like a legit issue, though the fix is not clear. Appears to be a result of more exhaustive type checks in 3.9.

**Comment by micahgodbolt** [comment]
I've run into this issue as well, but for some reason, only with @fluentui/react and not OUFR

**Comment by dotnetjunky** [comment]
I tried upgrading to Typescript 4.0.0-beta and miraculously, it built successfully without this error. So this bug seems to be specific to version 3.9. :-/

**Comment by curtisman** [comment]
This also repros on Typescript 3.7.5
