### ISSUE TITLE
onResolveOptions is not working with selectedKey

### ISSUE THREAD

**Issue by lzl124631x** [microsoft/fluentui#13554]
### Environment Information

- **Package version(s)**: 
The one used in the fluentui examples
```
<script src="//unpkg.com/office-ui-fabric-react@7/dist/office-ui-fabric-react.js"></script>
<script src="//unpkg.com/@uifabric/react-hooks@7/dist/react-hooks.js"></script>
```
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/lzl124631x/pen/PoZZLYm?editors=0110

#### Actual behavior:
the selectedKey is not selected

#### Expected behavior:
It should be seleted.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by jdhuntington** [comment]
Hi @lzl124631x - thanks for the report. Afraid I don't see `selectedKey` anywhere in the codepen; would you mind double checking the link?

**Comment by lzl124631x** [comment]
It's at line 23 in the JS part 
![image](https://user-images.githubusercontent.com/5824517/84455835-37dfee80-ac13-11ea-94b2-bb2cc434a97a.png)

**Comment by jdhuntington** [comment]
Oh wow, sorry I missed it! 

You're right that the option is not selected. At a minimum it would be required to pass in some set of `options` to use for the first rendering. 

However, when I do provide that, I see the selected key ignored as soon as `onResolveOptions` is invoked. This definitely is not expected; I will continue investigating.

**Comment by pelizza** [comment]
Hi @jdhuntington, have you got any updates? We are just facing this issue as well...
Thank you.
