### ISSUE TITLE
<div> not allowed as child of element <span> when having CommandBarButton with PersonaCoin in onRenderIcon

### ISSUE THREAD

**Issue by chihch** [microsoft/fluentui#13556]
### Environment Information

- **Package version(s)**: v7.94.0
- **Browser and OS versions**: windows 10 PC

### Describe the issue:

Accessibility issue: `<div>` not allowed as child of element `<span>` when having CommandBarButton with PersonaCoin in onRenderIcon

#### Actual behavior:
If using a PersonaCoin in onRenderIcon of CommandBarButton, it raises an accessibility issue saying that `<div>` not allowed as child of element `<span>`. By reading the DOM render tree from codepen sample project you can see the issue I described. I checked the implementation of the BaseButton and see that <span> element is used in the render tree. This could be bigger problem because any view/element pass in through onRenderIcon of CommandBarButton will have this accessibility issue. 

#### Expected behavior:

Expect to be able to pass in any element through onRenderIcon property without the stated accessibility issue.

**Comment by paulgildea** [comment]
This might be a difficult issue to address because folks may have taken a dependency on the internal DOM when styling this component

**Comment by jdhuntington** [comment]
@chihch - is there are specific accessibility issue that this DOM structure is causing? Would like to understand the issue before recommending any fixes.

**Comment by chihch** [comment]
thanks for getting back to me @paulgildea  @jdhuntington . If you look at the codepen sample I put up and open the developer tool to see DOM tree. You will see the `<div>` is a child of element `<span>`, and this is the error message we get too. thanks!

**Comment by jdhuntington** [comment]
Thanks @chihch -- What is the accessibility issue this causes? Trying to figure out what kinds of users are impacted by this DOM. Thanks!

**Comment by nirbaligar** [comment]
This issue is basically caught by Accessibility Insights manual assessment. This WCAG 2.1 compliant tool has a requirement to run the plugin - https://validator.w3.org/nu/ and the error was caught by this plugin. This issue might not directly create screen reader issues but it needs to be fixed from Compliance standpoint.

**Comment by chihch** [comment]
friendly ping.. @jdhuntington @paulgildea

**Comment by paulgildea** [comment]
Thanks for the impact @nirbaligar !

Sounds like we should add this to our list of WCAG 2.1 issues to address. I still believe this would be a breaking change so this might be something that goes into v8.
