### ISSUE TITLE
Touchmove events bubble even when the inner element has allowScrollOnElement called on it

### ISSUE THREAD

**Issue by thepelkus-too** [microsoft/fluentui#13555]
### Environment Information

- **Package version(s)**: 7.109
- **Browser and OS versions**: Chrome 83 / Android 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/kai-substantial/pen/WNrrPex

#### Actual behavior:

Dragging (i.e. applying a touchmove event to) the internal scrollable (the red area in the codepen) to the bottom, then starting a new drag to take it further bubbles the event to the containing scrollable, even though the inner scrollable has allowScrollOnElement applied to it, which should detect that the inner scroll is at the bottom and call preventDefault.

(This is because scrollTop can be a float on some devices, and some combinations of element sizes will bork the downward scroll math in allowScrollOnElement. [Wrapping scrollTop in a ceil call here](https://github.com/microsoft/fluentui/blob/master/packages/utilities/src/scroll.ts#L72) fixes things.)

#### Expected behavior:

Dragging on a scrollable in another scrollable when the inner scrollable has allowScrollOnElement applied to it should not scroll the outer container when the inner scrollable has reached its limit and a new drag is started that would take it past that limit.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
None at the moment (I've duplicated the function in my own code with slight modifications to make it work)

**Comment by jdhuntington** [comment]
Thanks for the report! A PR to fix this would be much appreciated. Will leave this open to track for now.

**Comment by thepelkus-too** [comment]
@jdhuntington that file doesn't have any tests around it, and the change I'm making doesn't seem to bubble out to anything that is tested. Should I take a stab at backfilling tests for scroll.js while I'm at it?
