### ISSUE TITLE
Search multiple selection dropdown switching to VPC upon selection

### ISSUE THREAD

**Issue by adamsamec** [microsoft/fluentui#13566]
#### Affected component
Search multiselect dropdown component example on this URL: https://fluentsite.z22.web.core.windows.net/components/dropdown/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#types-search-multiple

#### Actual behavior:

1. With JAWS or NVDA, open the dropdown.
2. Using the arrow keys, select and item and ad it by pressing the Enter key.
3. Now the dropdown closes and the screen reader disables the forms mode and switches to the virtual PC mode.

#### Expected behavior:

The screen reader should not automatically disable the forms mode upon the adding of an item, so that user can immediately use the Left or Right arrow keys to select added items.

**Comment by paulgildea** [comment]
@adamsamec could you provide a codepen, video, screenshot to help us understand what the actual issue is?

Thanks for the help! 😄

**Comment by adamsamec** [comment]
#### Affected component
Search multiselect dropdown component example on this URL: https://fluentsite.z22.web.core.windows.net/components/dropdown/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#types-search-multiple

#### Actual behavior:

1. With JAWS or NVDA, open the dropdown.
2. Using the arrow keys, select and item and ad it by pressing the Enter key.
3. Now the dropdown closes and the screen reader disables the forms mode and switches to the virtual PC mode.

#### Expected behavior:

The screen reader should not automatically disable the forms mode upon the adding of an item, so that user can immediately use the Left or Right arrow keys to select added items.

**Comment by paulgildea** [comment]
@jurokapsiar Misunderstood - looks like this is a v0 Issue - mind taking a look?

**Comment by kolaps33** [comment]
so far two approaching are considering:
https://github.com/microsoft/fluentui/pull/13796
https://github.com/microsoft/fluentui/pull/13797

**Comment by paulgildea** [comment]
@miroslavstastny Bringing this one back.
