### ISSUE TITLE
Text field with rich text support

### ISSUE THREAD

**Issue by pixels89** [microsoft/fluentui#13561]
#### Describe the feature that you would like added

Textfield with rich text support

#### What component or utility would this be added to

A new component called RichTextField

#### Have you discussed this feature with our team, and if so, who

NO, i haven't.

#### Additional context/screenshots

I have been using TextField in my project. But, now I need href support in it.

e.g. if the text contains a http link it should work as a link when clicked.

similarly for hash tags and emails.

**Comment by paulgildea** [comment]
Thanks for the feedback and suggestion!

We're near term we're focusing on improvements to performance and coherence, as you can see in our pinned issue on the repo detailing our v8 plans. 

This is great suggestion currently we don't have plans in the near future to build out this type of component.

**Comment by pixels89** [comment]
@paulgildea  Thanks for accepting this request. Can you provide an appx estimate on this so that we can plan accordingly on our side?
