### ISSUE TITLE
GridCells always have aria-readonly set on them

### ISSUE THREAD

**Issue by SavannahBourgeois** [microsoft/fluentui#13573]
### Environment Information

- **Package version(s)**: all
- **Browser and OS versions**: all

### Describe the issue:

When using a Fabric grid, aria-readonly is being set on all gridcell items. This means when the user navigates with a screen reader in a component like a gallery, it will announce the item name and then announce "read only" which is not applicable to the item.

### Please provide a reproduction of the issue in a codepen:

You can see this reproducing on all of the examples in this fabric demo page by opening the chrome dev-tools and seeing that read-only is set on the items in the accessibility tab or you can use a screen reader to hear it. 
https://developer.microsoft.com/en-us/fluentui#/controls/web/swatchcolorpicker
https://codepen.io/pen/?&editable=true=https%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui
#### Actual behavior:

Aria-readonly is being set.

#### Expected behavior:

Aria-readonly should not be set unless specified.

**Comment by prashanth-kalaga** [comment]
i cannot repro this in Chrome (82+) and Firefox latest version. Can you please specify the browser version @SavannahBourgeois

**Comment by SavannahBourgeois** [comment]
I can repro this in Chromium Edge with Narrator (Version 83.0.478.45 (Official build) (64-bit)) using the codepen you sent. When I test with legacy edge and narrator, I hear "editable" after every cell color.

Also with Chrome (Version 83.0.4103.97 (Official Build) (64-bit)) I can see the role being set in the accessibility tab of the dev tools of your codepen. See screenshot. 
![gridcell](https://user-images.githubusercontent.com/42548121/84511189-069b0900-ac7b-11ea-90b5-f788e5ac928b.PNG)

However, your codepen does not use any Fabric controls so I would have to agree that I should probably reach out to Chromium Edge and report the bug there. Thanks for the help!
