### ISSUE TITLE
donut chart legends should have the ability to wrap

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#13578]
#### Describe the feature that you would like added

the legends of all the chart have the ability to wrap to the next line except the donut chart. it would be better if we provide that feature.

#### What component or utility would this be added to

Donut Chart

#### Have you discussed this feature with our team, and if so, who
no

#### Additional context/screenshots

**actual behavior.**

![image](https://user-images.githubusercontent.com/33802398/84463553-c8f4ab00-ac8f-11ea-82c7-8fdc10cec213.png)

**expected behavior**
![image](https://user-images.githubusercontent.com/33802398/84463602-e75aa680-ac8f-11ea-92a7-e58bdf7b59ea.png)

**Comment by paulgildea** [comment]
@Raghurk Consideration for the circle chart.
