### ISSUE TITLE
LineChart.base.tsx handleFocus method is pointing to the outer not inner array

### ISSUE THREAD

**Issue by reijam** [microsoft/fluentui#13572]
### Environment Information

the most recent release of react-charts lineChart.base.tsx
I just npm'd it to fix another bug but when i tried to tab around in the chart I run into another bug.

 
this code is pointing to the wrong level ... 
   `const found = this._calloutPoints.find`
it should be pointing to :
`   const found = this._calloutPoints[0].find`

In the last method of the class:
```

  private _handleFocus = (
    keyVal: string,
    x: number | Date,
    y: number | string,
    lineColor: string,
    xAxisCalloutData: string,
    circleId: string,
  ) => {
    const formattedData = x instanceof Date ? x.toLocaleDateString() : x;
    const found = this._calloutPoints.find((element: { x: string | number }) => element.x === formattedData);
    const _this = this;
    d3Select('#' + circleId)
      .attr('fill', '#fff')
      .attr('r', 8);
    d3Select('.verticalLine')
      .attr('transform', () => `translate(${_this._xAxisScale(x)}, 0)`)
      .attr('visibility', 'visibility');
    this.state.refArray.map((obj: IRefArrayData) => {
      if (obj.index === keyVal) {
        this.setState({
          isCalloutVisible: true,
          refSelected: obj.refElement,
          hoverXValue: xAxisCalloutData ? xAxisCalloutData : '' + formattedData,
          hoverYValue: y,
          YValueHover: found.values,
          lineColor: lineColor,
        });
      }
    });
  };
```
If you go into the debugger and look at it you will see that there is one item in the array but the subarray has many.

This is a show stopper for me to get through accessibility so i hope someone can jump on it asap.

thanks

**Comment by paulgildea** [comment]
@Raghurk mind taking a look at this one?
