### ISSUE TITLE
Button does not show 'clicked' animation when pressing Enter

### ISSUE THREAD

**Issue by prashanth-kalaga** [microsoft/fluentui#13582]
### Environment Information

- **Package version(s)**:  7+ ( even most recent version also has this)
- **Browser and OS versions**:  tested on Edge, Chrome and FireFox

### Describe the issue:
When the user focuses on DefaultButton or PrimaryButton and click enter, it doesn't show the click animation, and hence loses out on visual feedback that button is pressed. It feels like the button didnot respond for Enter key. 

For SpaceBar, the button shows the clicked effect.

#### Actual behavior:
as described above, button doesnot behave the same for spacebar and enter key.

#### Expected behavior:
expect the same behavior when i press 'spacebar' to happen with 'enter' as well - i.e show clicked animation and call the onClick from props.

### If applicable, please provide a codepen repro:

[Buttons; on Focus+Enter does not animate; but spacebar works](https://codepen.io/custformatter/pen/KKVzoeb)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) SharePoint Online

**Comment by jdhuntington** [comment]
Hi @prashanth-kalaga - thanks for the report.

Unfortunately this is not something the button components provide. In this instance, it's merely reflecting the behavior of the underlying native `button` element, which exhibits the same behavior.

**Comment by prashanth-kalaga** [comment]
@jdhuntington , thanks for looking into this.
I understand that this is the behavior of underlying html button element,  but can this change and have consistent behavior for pressing Enter and Space on the Button that fabric provides? - both actually do call the event handler for button click, but have different visual behavior.
I hope this will change as this is a confusing.
