### ISSUE TITLE
Grid Responsive issue in @fluentui/react-northstar@0.49.0

### ISSUE THREAD

**Issue by Vigneshramkumar** [microsoft/fluentui#13583]
Hello Team,

We are creating a Teams tab application and as suggested by Microsoft we are using @fluentui/react-northstar@0.49.0 for UI controls.
But there is no option for providing responsiveness in the Grid or pther layouts for making controls adjusting itslef based on the screen size (like different screen sizes, tablet and mobile).
Kindly let me know whether any option is available in that component or else we need to use any CSS framework outside for that purpose. Thanks in advance for your response.

**Comment by paulgildea** [comment]
@jurokapsiar Any suggestions here?

**Comment by jurokapsiar** [comment]
Hi,

I would suggest using the `Grid` component. You can add `gridTemplateColumn` or other grid css roles using the `styles` prop. See for example https://codesandbox.io/s/8wcmk?module=/example.js

Also please note that CSS grid does not work out of the box on IE11 and you might need to use for example https://autoprefixer.github.io/ to generate the styles for it - they can then also be applied using `styles` prop on the components.

Another thing to think about is accessibility as `Grid` is just layout component and as such does not represent any semantic meaning. You might need to provide appropriate `role` for the grid as well as for the items and choose from available behaviors.

Closing the issue, please reopen if further clarification is needed.
