### ISSUE TITLE
text on y-axis and x-axis is not visible properly

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#13581]
### Environment Information

- **Package version(s)**: (all)
- **Browser and OS versions**: (all)

we are using stroke:theme.color to color the text for both y-axis and x-axis, see the below images.
instead we need to use `fill`

also we need to remove `opacity` on the `text` and use the proper theme color .. `bodySubText` should be fine.. in this way we can remove the `opacity` on the `text`
![image](https://user-images.githubusercontent.com/33802398/84474739-fd289580-aca8-11ea-9323-9e0ed5535f3b.png)

![image](https://user-images.githubusercontent.com/33802398/84474686-e2eeb780-aca8-11ea-8135-146287c8ff69.png)

NOTE:- with `stroke` we are not able to see the text properly.. see the image below
![image](https://user-images.githubusercontent.com/33802398/84475019-73c59300-aca9-11ea-9662-6abf84c5af92.png)

Are you willing to submit a PR to fix? maybe

Requested priority: Low

**Comment by jameelakowsar** [comment]
PR raised 
https://github.com/microsoft/fluentui/pull/13584

**Comment by paulgildea** [comment]
@Raghurk Another issue for consideration.
