### ISSUE TITLE
Hover bug in line charts

### ISSUE THREAD

**Issue by reijam** [microsoft/fluentui#13586]
This is another bug related to the most recent (this week) release.

When you do not have a hover callback or hover data hovering over the line graph generates an error.

When I look at the code one thought comes to mind... D3 is the real culprit.

Most of the issues I have seen with line charts and OUIFR charting in general relate to dependency on d3.  

Several years ago I too was encircled with d3 issues and decided to write to native svg instead.

Once you get the hang of it it is much less troublesome than d3.  

The problem with d3 is that their code is so tightly bound into how they process that it is really difficult to extract and even more difficult to manage events or chase bizarre bugs.

If someone wants to contact me I will gladly share the code that I have already written for complex point, spark , pie, bar and other graphs. (Some is react-based and  some was for HTML components )

No matter what you should really consider removing d3 from your code base. You will not regret it.

**Comment by paulgildea** [comment]
@Raghurk Might be a good learning opportunity get feedback from @reijam on their experience with d3.

**Comment by reijam** [comment]
Feel free to have anyone contact me I will gladly walk you through how to extricate yourself if you are so inclined... btw as a reference point... I was able to create an no d3 line chart that worked for my purposes... It is not abstracted to handle all cases but it works.  let me know if you want a copy (you can use it as a starting point should you choose to dump d3).
