### ISSUE TITLE
rename props of line chart

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#13580]
### Environment Information

- **Package version(s)**: (all)
- **Browser and OS versions**: (all)

#### Actual behavior:
line chart has the props height and width, which are not used to calculate the height and width but used for detection of the  resize of the window.. we should change the name of those props or we should introduce other prop.

![image](https://user-images.githubusercontent.com/33802398/84472206-7a054080-aca4-11ea-8fd6-46ad6be90af8.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? maybe

Requested priority: ( Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@Raghurk Mind taking a look at this one?
