### ISSUE TITLE
Picker result items clipping on iOS when scrolling

### ISSUE THREAD

**Issue by gringocl** [microsoft/fluentui#13590]
### Environment Information

- **Package version(s)**: (7.109.0)
- **Browser and OS versions**: (Safari iOS 13.4)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/gringocl/pen/jOWqjjd

#### Actual behavior:

When scrolling through suggestion list items on ios they begin to appear blank or unrendered.  This seems to be caused by the two scrollable containers, calloutMain and suggestionsList and the bounce / elastic scroll getting them out sync.  If these two containers have the same height the content remains rendered whenever scrolling.

#### Expected behavior:

When scrolling through suggestion list items the results are always visible.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
None at the moment.

**Comment by paulgildea** [comment]
@gringocl Thanks for the info! Would you like to put together a PR and work wit @jdhuntington on getting it submitted?
