### ISSUE TITLE
CommandBar: Action tooltip shown for split button

### ISSUE THREAD

**Issue by LukeOwlclaw** [microsoft/fluentui#13598]
### Environment Information

- **Package version(s)**: 7.120.0

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/LukeO/pen/bGEeydX

#### Actual behavior:

When using `CommandBar` with `split:true` and `iconOnly: true`, the tooltip stretches over the whole component including the split icon:

![image](https://user-images.githubusercontent.com/2737900/84621759-ae167680-aedb-11ea-97e6-f7a378099891.png)

#### Expected behavior:

The split button action is different from the action of the main button (on the left), they should thus not share the same tooltip. Using the given tooltip only for the action button would be what I expect.

**Comment by paulgildea** [comment]
@jdhuntington - is it possible to pass tooltip positions hints as a work around?
