### ISSUE TITLE
Module not found: Can't resolve '@uifabric/icons' 

### ISSUE THREAD

**Issue by cmitides89** [microsoft/fluentui#13596]
I used npm to install the @fluentui/react in my reactJS application, by following the instructions in the documentation. I receive the following error:
```
Failed to compile.

.../node_modules/office-ui-fabric-react/lib/Icons.js
Module not found: Can't resolve '@uifabric/icons' in '...\node_modules\office-ui-fabric-react\lib'
```
If I open the listed directory in Windows Explorer the Icons.js file is there. I have seen similar issues posted and I have followed the suggested fixes but they do not seem to work for me. I have also tried uninstalling and reinstalling fluentui. 
### Environment Information

- **Package version(s)**: 

> "@fluentui/react": "^7.120.0",
> "office-ui-fabric-react": "^7.120.0",

- **Browser and OS versions**: Microsoft Edge 83.0.478.45 on Windows 1010.0.19014

### Please provide a reproduction of the bug in a codepen:

I cannot reproduce these errors on codepen

#### Actual behavior:

Failed to Compile, ReactJS does not find the module @uifabric/icons and it is looking in the directory `node_modules/office-ui-fabric-react/lib`, this error crashes the reactJS application.

#### Expected behavior:

Expected to load the imported components and run without crashing (currently I am just testing with primary button component.)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes
Requested priority: (Blocking, High, Normal, Low)
High
Products/sites affected: (if applicable)
N/A

**Comment by cmitides89** [comment]
**Update**
I had to upgrade nodejs to version (12.18.0) I was on version (12.16.3), doing so let me use fluentui without crashing

**Comment by paulgildea** [comment]
Thanks for the update @cmitides89.

I'm curious why upgrading your node version solved the issue. @jdhuntington do we have any hard  dependencies on what version of node you need?

**Comment by voidsteed** [comment]
I have the issue on both node 10 and 12:
error An unexpected error occurred: "https://registry.yarnpkg.com/@fluentui/react-icons/-/react-icons-0.1.31.tgz: ESOCKETTIMEDOUT".

**Comment by cmitides89** [comment]
I had too many issues with uifluent the documentation is extremely confusing. Everything still references office-ui-fabric-react. Its unclear how to import the components I need. Do I need to import them from office-ui-fabric-react? If that is the case then perhaps hold off on telling people to install fluentui. None of the components can be found when trying to import from fluentui. If I try to import components from fluentui the modules are not found. It's really unfortunate because I would love to use fluentui. I think it's really clean and simple, perfect for what I am looking to build, unfortunately I had to switch to material ui (which I dont like at all to be honest) in order to move forward with my project because it seems like this not ready for use.
