### ISSUE TITLE
DatePicker onFocus event issue

### ISSUE THREAD

**Issue by llynxs** [microsoft/fluentui#13603]
### Describe the issue:

The error message does not disappear when input is being focused second time.
These attributes should be added to DatePicker:
`
disableAutoFocus={true}
isRequired={true}
`

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/_ololo_/pen/oNbjRgR

#### Actual behavior:
When input was unfocused and no data in there the error message appears under the input it disappers only if user enter some value or clicks to the date picker icon.

#### Expected behavior:
If no data and error message is present, when user clicks input and it becomes focused - error mesage should be hidden and to be appeard only if no data entered.

**Comment by paulgildea** [comment]
@lorejoh12 - is there someone we can follow up with on design that understand what the default behavior is for date input validation and focus?

**Comment by llynxs** [comment]
@paulgildea hi, are there any changes regarding the status of the issue?
