### ISSUE TITLE
Using UNSAFE_componentWillReceiveProps in strict mode is not recommended 

### ISSUE THREAD

**Issue by reijam** [microsoft/fluentui#13613]
This might be the most extraordinary bug i have encountered so far with office-ui-fabric-react code.

here is the text of the message

```
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: ImageBase, PersonaCoinBase, ResizeGroupBase, SearchBoxBase
```
  
these are my package.json dependencies

```
  "dependencies": {
    "@cseo/controls": "^1.0.16",
    "@cseo/styles": "^1.0.3",
    "@microsoft/applicationinsights-web": "^2.5.5",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "moment": "^2.26.0",
    "msal": "^1.3.2",
    "office-ui-fabric-react": "^7.120.0",
    "react": "^16.13.1",
    "react-adal": "^0.5.0",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1"
  },
```
 The bug appears to be happening in a call somewhere between CoherenceHeader and the underlying components .

I have eliminated most of the possible items that could cause it...   

This could be a coherence issue (but i think that searchbox is an office component as are the others).

Also the message is complaining about using UNSafe_componentwillupdate... which when i search only hits on OUIFR code.

It only happens when i load the header and the nav button...and while i am still fetching

It just started popping up as I started moving more of my code to individual modules so that they can be unit tested... 

Never seen anything like it before.

**Comment by paulgildea** [comment]
@reijam Thanks for the feedback.

Moving to strict mode is part of our [v8 roadmap](https://github.com/microsoft/fluentui/issues/12770)

And here's our current progress on that specific work: https://github.com/microsoft/fluentui/projects/35

In the meantime the workaround is to not run in strict mode - we can't include this in the current v7 codebase because it's a breaking change.

**Comment by reijam** [comment]
Great thanks for the feedback.
As an fyi to all the others that might run into this issue When you npx create-react-app to generate your initial repo (and then add OUIFR afterward)  CRA now defaults to the following in the index.js file

```
ReactDOM.render(
<React.strictMode>
    <App />
</React.strictMode>
  ,
  document.getElementById('root')
)

```
instead of 

```
 ReactDOM.render(
    <App />
  ,  document.getElementById('root')
)
```

And if you try to add a React Error Component it does not catch it anywhere. (This is how I discovered the problem because i could not trap it in any of my our OUIFR code).

Why CRA defaults to this all of a sudden is a bit of a mystery.
