### ISSUE TITLE
Grouped vertical bar chart y axis tick values should customize to SI units

### ISSUE THREAD

**Issue by jameelakowsar** [microsoft/fluentui#13614]
**Environment Information**

- Package version(s): (all)
- Browser and OS versions: (all)

#### Describe the feature that you would like added

In grouped vertical bar chart, Y axis tick values getting truncated if we gave large number. Need to customize to SI units like, K,M,G,T

#### Additional context/screenshots
Current behaviour

![image](https://user-images.githubusercontent.com/20105532/84742235-d41c4380-afcd-11ea-8bf8-4b2111cb28af.png)

Need to be updated like below.
![image](https://user-images.githubusercontent.com/20105532/84741977-74259d00-afcd-11ea-8611-11e4469817c1.png)

**Comment by jameelakowsar** [comment]
PR raised https://github.com/microsoft/fluentui/pull/13617

**Comment by paulgildea** [comment]
@Raghurk mind taking a look at this PR? Thanks!

**Comment by jameelakowsar** [comment]
#PRComplete
https://github.com/microsoft/fluentui/pull/13617
