### ISSUE TITLE
DatePicker mergeStyleSets Type Error

### ISSUE THREAD

**Issue by kevinvangelder** [microsoft/fluentui#13632]
### Environment Information

- **Package version(s)**: 7.115.2
- **Browser and OS versions**: Firefox 78.0b1 & macOS 10.15.2 (19C57)

### Please provide a reproduction of the bug in a codepen: 
https://codepen.io/kevinvangelder/pen/BajQBXy?editable=true

#### Actual behavior:
Type error:
```js
Type 'IProcessedStyleSet<any>' is not assignable to type 'IStyleFunction<IDatePickerStyleProps, IDatePickerStyles> | DeepPartial<IDatePickerStyles> | undefined'.
  Type 'IProcessedStyleSet<any>' has no properties in common with type 'DeepPartial<IDatePickerStyles>'.ts(2322)
DatePicker.types.d.ts(30, 5): The expected type comes from property 'styles' which is declared here on type 'IntrinsicAttributes & IDatePickerProps & { children?: ReactNode; }'
```

#### Expected behavior:
Types for DatePickerStyles should accept output from `mergeStyleSets`. This pattern works with other field styles.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/sites affected: Learn Student Ambassadors

**Comment by paulgildea** [comment]
@dzearing is this an issue with mergeStyles or the DatePicker definition?
