### ISSUE TITLE
Calendar: onBlur callback is fired on every date click

### ISSUE THREAD

**Issue by pragya91** [microsoft/fluentui#13633]
### Environment Information

- **Package version(s)**: 7.120.2 
- **Browser versions**: Chrome Version 83.x (or any browser)
- **OS versions**: Windows 10 (or any OS)

### Codepen example:
https://codepen.io/pragya91/pen/NWxRZJa

#### Actual behavior:

**onBlur** event gets fired whenever a new date is focused. If a user keeps clicking on dates or uses tab to navigate within the Calendar component, then onBlur event gets called.
#### Expected behavior:

Ideally, since the user is still within the bounds of calendar, onBlur even should not get fired.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: https://fluidpreview.office.net/

**Comment by paulgildea** [comment]
@pragya91 Thanks for the issue!

@lorejoh12 is this expected behavior

@JustSlone if we were to change this behavior this might be a breaking behavior change... I don't know if folks have taken a dependency on the eventing order or if we guarantee that behavior across versions.

**Comment by xugao** [comment]
This is a bug. Will working on a fix
