### ISSUE TITLE
IVerticalBarChartProps `data` is incorrectly IDataPoint instead of IVerticalBarChartDataPoint

### ISSUE THREAD

**Issue by zackseuberling** [microsoft/fluentui#13648]
### Environment Information

- **Package version(s)**: 
  - `@uifabric/charting` 2.2.35
  - `office-ui-fabric-react` 7.121.0
 
- **Browser and OS versions**: 
  - MacOS 10.15.4 (19E287)
  - Firefox 77.0.1 (64-bit)

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/vigilant-bash-jf96v?file=/src/App.tsx:508-510

#### Actual behavior:

The interface for vertical bar chart props `IVerticalBarChartProps` currently expects `data` to be an array of `IDataPoint` 

#### Expected behavior:

The interface for vertical bar chart props `IVerticalBarChartProps` should expect `data` to be an array of `IVerticalBarChartDataPoint` 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: m365 admin charting demo site ([aka.ms/admincharting](http://aka.ms/admincharting))

**Comment by Raghurk** [comment]
Opening a bug on this locally to address this
