### ISSUE TITLE
Requesting a pill/chip set of components for Azure portal filter patterns

### ISSUE THREAD

**Issue by DavidParks8** [microsoft/fluentui#13653]
#### Describe the feature that you would like added

We need support for a pill filter experience for new react-based blades in the Azure portal. This would entail some sort of pill/chip component, as well as a pill/chip group component to display the chosen pill filters. This would eventually be used by nearly every team in the Azure portal as they migrate their blades to react. My team just happens to be the first that I'm aware of trying to implement a new grid blade via react (the ability to write in react in the Azure portal was just released and is intended to be the next evolution of all blades).

#### What component or utility would this be added to

We will defer to the expertise of the fluentui devs.

#### Have you discussed this feature with our team, and if so, who

No, this issue is the beginning of the discussion.

#### Additional context/screenshots

The full filtering design spec for the Azure portal can be viewed at https://github.com/Azure/portaldocs/blob/d2d164db30647308788333635f59115116ec6fdc/portal-sdk/generated/design-patterns-page-filtering.md

**Comment by khmakoto** [comment]
Thanks for reaching out to us! I'll mark this as a feature request and add it to our backlog, but we're likely not going to get to it for a while as we're currently focused on larger coherence work items and enhancements to our performance.
