### ISSUE TITLE
How to migrate to v0.50 @fluentui/react-northstar

### ISSUE THREAD

**Issue by jacargentina** [microsoft/fluentui#13657]
On previous version i had this:

 ```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider, mergeThemes, teamsTheme } from '@fluentui/react-northstar';

const theme = {
  componentVariables: {
    Menu: {
      backgroundColorHover: '#222331',
      backgroundColorActive: '#1e1e29',
      colorHover: '#000',
      color: '#fff',
      wrapperColorActive: '#fff'
    }
  }
};
<Provider theme={mergeThemes(teamsTheme, theme)}>
  { ... }
</Provider>
```

With v0.50 the variables are not applied (my colors are wrong)

How to i migrate to new version?

**Comment by assuncaocharles** [comment]
Hi @jacargentina 

In the PR #13117 we introduced `MenuItemWrapper` so I could achieve the same you are trying to achieve by using it:

```javascript
const theme = {
  componentVariables: {
    Menu: {
      color: '#fff',
    },
    MenuItemWrapper: {
      wrapperColorActive: '#fff',
      backgroundColorHover: '#222331',
      backgroundColorActive: '#1e1e29',
    },
    MenuItem: {      
      colorHover: '#000',
    },
  }
};
```
See example here: https://codesandbox.io/s/pedantic-hill-7ok3u?file=/example.js:121-405

**Comment by jacargentina** [comment]
Thanks a lot @assuncaocharles!

Would be nice to have some migration guides, but i know the development is going faster now and it is hard to document things which will certainly change soon
