### ISSUE TITLE
Pivot: [Accessibility][Screen Reader]: 'My Files/Recent/Shared with me' tab items are getting read twice.

### ISSUE THREAD

**Issue by AbhijitUI** [microsoft/fluentui#13663]
### Environment:

Browser - Edge Version 83.0.478.50 (Official build) (64-bit)

### Describe the issue:

Pivot- Tab Item when traversed through On-Screen Keyboard reads the 'My Files/Recent/Shared with me' tab item twice.

#### Actual behavior:

Pivot- Tab Item when traversed through On-Screen Keyboard reads the 'My Files/Recent/Shared with me' tab item twice.

#### Expected behavior:

It should only read the content once.

### If applicable, please provide a codepen repro:

https://codepen.io/abhijitui/pen/KKVNEjZ

Can be replicated on all the codepens available in the documentation maitained over here.
https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot

![image](https://user-images.githubusercontent.com/16835753/85005489-7d9e3900-b176-11ea-93d2-6d7ebe382092.png)

![image](https://user-images.githubusercontent.com/16835753/85005695-c81fb580-b176-11ea-9e1a-f60efea17a77.png)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? - No

Requested priority: (Blocking, High, Normal, Low) - Normal

Products/sites affected: (if applicable) - N/A

**Comment by AbhijitUI** [comment]
Hi @khmakoto, thank you for reviewing the issue & apologies for the delay in response!
Please find a video depicting the behavior on the CodePen, Thanks!

[GitHub Issue Video.zip](https://github.com/microsoft/fluentui/files/4811753/GitHub.Issue.Video.zip)

**Comment by paulgildea** [comment]
@mnajdova - This might need to be repro'ed to see if this is actually an issue.

**Comment by paulgildea** [comment]
Reassigning to get some more traction on this.

@xugao this one needs investigation so bringing this over.

**Comment by xugao** [comment]
@AbhijitUI - i can't repro with Edge Version 83.0.478.64 (Official build) (64-bit) and Narrator. can you confirm you are using Narrator and not other type of screen readers
