### ISSUE TITLE
@fluentui/react-button: `onClick` on `content` slot does not work

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#13668]
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.3.2

```tsx
<Button
  content={{
    children: "Foo",
    onClick: () => {
      console.log(222);
    }
  }}
/>
```

https://codesandbox.io/s/affectionate-shape-zgrcq?file=/src/App.js

#### Actual behavior:

`onClick` is not called on `content` slot.

#### Expected behavior:

Callbacks on slots should work.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by dzearing** [comment]
We debugged this; it's working from a composition perspective. This is a styling bug; the focus rectangle is not set to `pointer-events: none`.

https://codesandbox.io/s/crimson-fog-rkkg5?file=/src/App.js
