### ISSUE TITLE
VerticalStackedBarChart: Should support X-axis and Y-axis title

### ISSUE THREAD

**Issue by tusharjape-msft** [microsoft/fluentui#13669]
#### Describe the feature that you would like added

VerticalStackedBarChart show display x-axis and y-axis titles.

#### What component or utility would this be added to

VerticalStackedBarChart (@uifabric/charting)

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

![x-axis and y-axis title column chart](https://user-images.githubusercontent.com/66400291/85011456-2bade100-b17f-11ea-804d-18aa5cd2194b.PNG)

**Comment by khmakoto** [comment]
Assigning `charting` package owner @Raghurk as their team made this component. @Raghurk, if you think this is a high pri issue, please suggest a fix/raise a PR. If it is not high pri or behaving as intended or not aligned with your plans for this component, please feel free to close.
