### ISSUE TITLE
@fluentui/react-button: throws a React warning with render props in shorthands

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#13666]
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.3.2

```tsx
<Button
  content={{
    children: (Component, props) => <Component {...props}>Button</Component>,
    style: { border: "2px solid red" }
  }}
/>
```

https://codesandbox.io/s/suspicious-sid-vdmn6?file=/src/App.js:146-353

#### Actual behavior:

```
Warning: Invalid prop `style` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
    in Fragment (created by Button)
    in Button (at App.js:7)
    in div (at App.js:6)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)
```

#### Expected behavior:

Renders without warnings.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by dzearing** [comment]
I'll take this.

**Comment by dzearing** [comment]
This now works:
https://codesandbox.io/s/condescending-shamir-tf3ns?file=/src/App.js
