### ISSUE TITLE
@fluentui/react-button: no way to force set props for slots

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#13677]
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.3.2

```tsx
const Composed = compose(
  Button,
  {
    slotProps: () => ({
      root: {
        id: "button4"
      }
    })
  }
);
```

```tsx
<Composed
  id="m"
  content={{ children: "Composed" }}
  onClick={() => console.log("Clicked inline")}
/>
```

https://codesandbox.io/s/eloquent-benz-uhm0u?file=/src/App.js:196-235

#### Actual behavior:

`id` equals `m`.

#### Expected behavior:

Sometimes there is a case where definitions from `slotProps` should always win (i.e. `id` should be equal to `button4`). Currently there is no way to do it.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by dzearing** [comment]
Interesting scenario, and I don't think is an edge case. `slotProps` is currently acting as default settings, not overrides. But we need an additional mechanism to force overrides where we're handling it. This commonly occurs with events which should be attached to sub slots, where we take care to call the user's override.

We probably need a proposal here. I can try and put something together.

**Comment by layershifter** [comment]
As this was related to `compose()` - closing it.
