### ISSUE TITLE
@fluentui/react-button: `onClick` is not called on `Space` when `as` prop is used

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#13673]
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.3.2

```tsx
<Button
  as="div"
  content="Foo"
  onClick={() => console.log("333")}
  tabIndex={0}
/>
```

https://codesandbox.io/s/silly-violet-yemtb?file=/src/App.js:146-271

1. Move focus to a button.
2. Press `Space` key

#### Actual behavior:

`onClick` is not called.

#### Expected behavior:

`onClick` is called.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by dzearing** [comment]
Closing as dupe of #13671.
