### ISSUE TITLE
VerticalStackedBarChart: hideLegend should be available for individual legends

### ISSUE THREAD

**Issue by tusharjape-msft** [microsoft/fluentui#13672]
#### Describe the feature that you would like added

User should be able to configure show/hide setting for each legend

#### What component or utility would this be added to

VerticalStackedBarChart (@uifabric/charting)

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

![showInLegend column chart](https://user-images.githubusercontent.com/66400291/85013180-c5768d80-b181-11ea-9803-c5f95bfc4628.PNG)

Only 2 of the 3 legends are being shown here.

**Comment by khmakoto** [comment]
Assigning `charting` owner @Raghurk as their team made this component. @Raghurk, if you think this is a high pri issue, please suggest a fix/raise a PR. If it is not high pri or behaving as intended or not aligned with your plans for this component, please feel free to close.
