### ISSUE TITLE
@fluentui/react-button: handlers in `compose()` are not merged

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#13676]
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.3.2

```tsx
const Composed = compose(
  Button,
  {
    slotProps: () => ({
      root: {
        onClick: () => console.log("Button 3")
      }
    })
  }
);
```

```tsx
<Composed
  content={{ children: "Composed" }}
  onClick={() => console.log("Clicked inline")}
/>
```

https://codesandbox.io/s/wonderful-hill-3hnrl?file=/src/App.js

#### Actual behavior:

A single handler is called.

#### Expected behavior:

All handlers should be called.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by dzearing** [comment]
This is similar to the last one about overriding values. In some cases you want to override, while in others you want merges. I'll take a look but may close one of these once I make sure they're effectively the same issue.

**Comment by dzearing** [comment]
I think this would have worked:

```tsx
const Composed = compose(
  Button,
  {
    slotProps: (props) => ({
      root: {
        onClick: (ev) => {
           console.log("Button 3")
            // call user's onClick.
            props.onClick?(ev)
        }
      }
    }),
    handledProps: ['onClick'] // don't mix in user's onClick.
  }
);
```

**Comment by dzearing** [comment]
We dug in here and believe that slotProps should have precedence over the user's opinions. 

I will change this and see how this works; I'll include a description in the README on state and slotProps distribution order.

**Comment by layershifter** [comment]
> This works:
> 
> https://codesandbox.io/s/awesome-tharp-1h83q?file=/src/App.js
> 
> ```tsx
> const Composed = compose(
>   Button,
>   {
>     slotProps: (props) => ({
>       root: {
>         onClick: (ev) => {
>            console.log("Button 3")
>             // call user's onClick.
>             props.onClick?(ev)
>         }
>       }
>     }),
>     handledProps: ['onClick'] // don't mix in user's onClick.
>   }
> );
> ```

How this will work with components that are composed multiple times?

**Comment by dzearing** [comment]
Yeah that's an issue. I updated the PR with use case. Will dig in with some ideas

**Comment by dzearing** [comment]
No longer applicable - in the hooks model, the caller has the ability to call the parent and/or replace the call on the draft state.
