### ISSUE TITLE
VerticalStackedBarChart: Formatting should be supported for y-axis values

### ISSUE THREAD

**Issue by tusharjape-msft** [microsoft/fluentui#13670]
#### Describe the feature that you would like added

User should be able to format y-axis labels in VerticalStackedBarChart

#### What component or utility would this be added to

VerticalStackedBarChart (@uifabric/charting)

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

![y-axis formatting column chart](https://user-images.githubusercontent.com/66400291/85012011-0372b200-b180-11ea-8370-4ed4d6b10d23.PNG)

For eg., in this chart, y-axis labels are formatted as -> y-axis value+"%"

**Comment by khmakoto** [comment]
Assigning `charting` package owner @Raghurk as their team made this component. @Raghurk, if you think this is a high pri issue, please suggest a fix/raise a PR. If it is not high pri or behaving as intended or not aligned with your plans for this component, please feel free to close.
