### ISSUE TITLE
@fluentui/react-button: `style` values for slots in `compose()` are not passed to `root`

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#13675]
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.3.2

```tsx
const Composed = compose(
  Button,
  {
    slotProps: () => ({
      root: {
        id: "button2",
        style: { background: "red" }
      }
    })
  }
);
```

```tsx
<Composed content={{ children: "Composed" }} />
```

https://codesandbox.io/s/divine-fast-uf8bi?file=/src/App.js:363-411

#### Actual behavior:

`style` values are passed.

#### Expected behavior:

`style` values are not passed.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by dzearing** [comment]
This one I think is a bug in useButton.
