### ISSUE TITLE
@fluentui/react-button: `state` allows to pass unhandled props

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#13679]
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.3.2

```tsx
const Composed = compose(
 Button,
  {
    displayName: "Button6",
    state: ({ ...props }) => ({
      ...props,
      root: { id: "button6" }
    })
  }
);
```

```tsx
<Composed content="button6" />
```

https://codesandbox.io/s/vigilant-sunset-lqwt7?file=/src/App.js

#### Actual behavior:

![image](https://user-images.githubusercontent.com/14183168/85014651-f1d0e080-b166-11ea-99f1-5f277dddbad0.png)

#### Expected behavior:

`root` should not be passed to an element.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by dzearing** [comment]
I can take a look.

**Comment by dzearing** [comment]
This is no longer applicable.
