### ISSUE TITLE
@fluentui/react-button: `style` values for slots in `compose()` are not merged

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#13674]
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.3.2

```tsx
const Composed = compose(
  Button,
  {
    slotProps: () => ({
      content: {
        style: { color: "red" }
      }
    })
  }
);
```

```tsx
<Composed content={{ children: "Composed", style: { background: "yellow" } }} />
```

https://codesandbox.io/s/awesome-shadow-0le2g?file=/src/App.js:128-433

#### Actual behavior:

`style` values are not merged.

#### Expected behavior:

`style` values are merged.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by dzearing** [comment]
This should be a special case in resolveSlotProps.

**Comment by dzearing** [comment]
Styles are now merged with `mergeProps`.
