### ISSUE TITLE
@fluentui/react-button: props.content is required to render a slot

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#13678]
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.3.2

```tsx
const Composed = compose(
  Button,
  {
    slotProps: () => ({
      content: {
        children: () => <span>button5</span>
      }
    })
  }
);
```

```tsx
<Composed onClick={() => console.log("Clicked inline")} />
```

https://codesandbox.io/s/icy-snow-psco4?file=/src/App.js:346-410

#### Actual behavior:

Content is missing.

#### Expected behavior:

Content equals to `button5`.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by dzearing** [comment]
That's an interesting one!

**Comment by layershifter** [comment]
We don't use `compose()` anymore and agreed on hooks approach, closing this.
