### ISSUE TITLE
Warning: Cannot update a component MenuItem while rendering a different component ContextSelector.Provider

### ISSUE THREAD

**Issue by jacargentina** [microsoft/fluentui#13684]
By the stack trace, it seems my own components are not related to the problem. Appears on v0.50, was working before just fine.

<img width="1515" alt="Captura de Pantalla 2020-06-18 a la(s) 13 04 12" src="https://user-images.githubusercontent.com/517228/85045144-f85e5880-b164-11ea-9a3a-70da67302acc.png">

**Comment by layershifter** [comment]
> Based on internal agreement we decided to keep existing warning to avoid different code for development and production.
>
> React will continue to raise this warning, but everything will continue work as it is. Once it will be possible to provide a proper fix, we will do it.

https://github.com/microsoft/fluentui/pull/14009#issuecomment-662353294
