### ISSUE TITLE
@fluentui/react-button: merging in `state` is not done

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#13680]
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.3.2

```tsx
const Composed = compose(
  Button,
  {
    displayName: "Button6",
    state: (props) => ({
      ...props,
      content: { id: "button7" }
    })
  }
);
```

```tsx
 <Composed content="button7" />
```

https://codesandbox.io/s/zen-bash-6g7re?file=/src/App.js

#### Actual behavior:

Content is empty.

#### Expected behavior:

Content should be rendered.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by dzearing** [comment]
@khmakoto please take a look

**Comment by khmakoto** [comment]
I wonder if this is something that should be done automatically or not and how we'd do it.

In this scenario you are explicitly replacing the values of the `content` in your `state` hook. I'd expect something like:

```tsx
const Composed = compose(
  Button,
  {
    displayName: "Button6",
    state: props => ({
      ...props,
      content: { ...props.content, id: "button7" }
    })
  }
);
```

**Comment by dzearing** [comment]
This no longer applies.
