### ISSUE TITLE
the description of onResolveOptions is not clear

### ISSUE THREAD

**Issue by lzl124631x** [microsoft/fluentui#13693]
```
onResolveOptions

(options: IComboBoxOption[]) => IComboBoxOption[] | PromiseLike<IComboBoxOption[]>

Callback issued when the options should be resolved, if they have been updated or if they need to be passed in the first time
```

It's not clear how to use this property along with options.

----

https://codepen.io/lzl124631x/pen/pogREVx?editors=1010

On initial load, click the chevron, I see two "resolve" in the console. Why is it triggered twice?

After switching from another tab to this codePen, I see one more "resolved" in the console. Why?

Clicking the chevron to close the dropdown menu, I see two "resolved". Why?

What's the meaning of the input parameter? By looking at the code I can see it's `currentOptions`, but I'm not sure what's the expected usage of it.

Why not just fire `onResolveOptions` when needed and let the client code to update the `options` prop? The current implementation is setting the internal state of `currentOptions`. Do we really need this internal state? What if `currentOptions` is out of sync with `props.Options`? If they never stay out of sync, why do we need to use this mirror state?

**Comment by paulgildea** [comment]
@joschect Is this the expected behavior of onResolveOptions? If so, sounds like we should update the documentation for that, if this is a bug then we should consider fixing this when we get to refreshing the ComboBox

**Comment by lzl124631x** [comment]
ping
