### ISSUE TITLE
Property 'as' does not exist on type 'IntrinsicAttributes & ...' on Provider when wrapping in another component

### ISSUE THREAD

**Issue by sushruth** [microsoft/fluentui#13716]
### Environment Information

- **Package version(s)**: 0.50.0
- **Browser and OS versions**: Edge Chromium on Windows 10

### Please provide a reproduction of the bug in a codepen:

the `as` prop does not seem to be typed properly when Provider is customized via another component

![image](https://user-images.githubusercontent.com/2114206/85178737-22cb1700-b234-11ea-8f0f-f74b009aaf06.png)

Repro this issue at - https://codesandbox.io/s/fluentui-provider-as-prop-issue-bznso?file=/src/App.tsx

#### Actual behavior:

`as` prop isnt recognized in types

#### Expected behavior:

`as` prop should be recognized in types

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: NA

**Comment by assuncaocharles** [comment]
Hey @sushruth 

The proper usage would be replacing `React.FC<>` by `ComponentWithAs`...

```jsx
import * as React from "react";
import {
  Provider,
  ComponentWithAs,
  ProviderProps
} from "@fluentui/react-northstar";

const StyledProvider: ComponentWithAs<"main", ProviderProps> = props => (
  <Provider {...props} />
);

export default function App() {
  return (
    <Provider as="main">
      <div className="App">
        <h1>Hello CodeSandbox</h1>
        <h2>Start editing to see some magic happen!</h2>
      </div>
    </Provider>
  );
}
```

**Comment by sushruth** [comment]
There seems to be another issue with that usage - 

![image](https://user-images.githubusercontent.com/2114206/87084161-9ed8cf00-c1e2-11ea-8b99-2da1a5dd4c83.png)

```
Property 'styles' does not exist on type 'ComponentWithAs<ElementType<any>, ProviderProps> & { children?: ReactNode; }'.ts(2339)
```

**Comment by sushruth** [comment]
Probably good to document it somewhere?
