### ISSUE TITLE
Checkbox: Add "required" property to Checkbox component

### ISSUE THREAD

**Issue by MichielDeMey** [microsoft/fluentui#13710]
#### Describe the feature that you would like added

I believe it would be beneficial to add a "required" property to the Checkbox component to indicate that it's mandatory to check the checkbox.

A use-case here is for example an "agree to terms and conditions" checkbox during registration.
Usually, these checkboxes are mandatory before you are able to continue the registration process.

#### What component or utility would this be added to

Checkbox

#### Have you discussed this feature with our team, and if so, who

Not yet discussed, feel free!

#### Additional context/screenshots

The HTML specification allows the `required` attribute on the checkbox input, which will indicate that the checkbox is mandatory.
<img width="636" alt="Screenshot 2020-06-19 at 14 14 19" src="https://user-images.githubusercontent.com/793406/85131533-46dc2780-b237-11ea-9e1e-f46136a2a12e.png">

**Comment by paulgildea** [comment]
@MichielDeMey Thanks for feedback looks like we have something similar on `TextField`

Would you be willing to make this change?

If so - we'll
1. Follow up with design on the default visual treatment
2. Write down the desire behavior of the `required` property (answer questions like is it just the same as `TextField`
3. Close on behavior and decide on the potential fix

Thanks for the feedback!

**Comment by dmp569** [comment]
Any update on this? Having aria-required or required attribute able to be specified on any form element in Fluent seems like a requirement not a nice to have for MAS compliance. Thanks!

**Comment by JustSlone** [comment]
@dmp569 hey, this should be released in @fluentui/react version 8 on Monday evening. Keep an eye on #17392 for the particular release version.

**Comment by dmp569** [comment]
Thanks! Will let the team know

Sent from my iPhone

On Mar 14, 2021, at 1:27 PM, Justin Slone ***@***.***> wrote:

﻿

@dmp569<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdmp569&data=04%7C01%7C%7C0b98d940fe8e4bb2b40a08d8e70e782b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637513396616753260%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lxKgZCVgzPJXDbbw1qNh5WYWCdI2%2B861WH6u3f6lLAE%3D&reserved=0> hey, this should be released in @fluentui/react version 8 on Monday evening. Keep an eye on #17392<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Ffluentui%2Fpull%2F17392&data=04%7C01%7C%7C0b98d940fe8e4bb2b40a08d8e70e782b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637513396616763217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=d%2FfzdOwn3p037cqomaYrOCuPpLQlHnBMfu8US1Vc8KQ%3D&reserved=0> for the particular release version.
