### ISSUE TITLE
Checkbox - passed tabIndex property is not being added to <input> element

### ISSUE THREAD

**Issue by wuwei8372** [microsoft/fluentui#13722]
### Environment Information

- **Package version(s)**: 6.211.6
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/wwuei8372/pen/MWKJZzZ

#### Actual behavior:

Passed tabIndex is not inherited and added to <input> element of Checkbox.

Code is shown below:
![image](https://user-images.githubusercontent.com/17853354/85184389-8a895e00-b244-11ea-8830-4b5e891bdeeb.png)

Generated html elements are shown below (no tabIndex for <input> element):
![image](https://user-images.githubusercontent.com/17853354/85184636-4ba7d800-b245-11ea-97dc-ce676c37d218.png) 

#### Expected behavior:

Generated <input> element should inherit tabIndex and set tabIndex to the passed value:
![image](https://user-images.githubusercontent.com/17853354/85184685-89a4fc00-b245-11ea-8e4c-6434c40a33de.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (High)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
Thanks for the issue!
