### ISSUE TITLE
GroupedList item's onClick event cannot be trigger by keyboard 'enter'

### ISSUE THREAD

**Issue by chihch** [microsoft/fluentui#13720]
### Environment Information

- **Package version(s)**: 7.94.0
- **Browser and OS versions**: Windows 10 PC

### Describe the issue:

We are using Panel component and put a GroupedList in panel body. Everything works fine except that the onClick handler of groupdedList item is not called if we using keyboard navigation and click enter key to try to trigger the onClick handler. Our groupedList item is basically like this `<div tabIndex={0} role={'gridcell'} onClick={() => something}>`. It works well using mouse click. 
I double checked with every onClick handler of item's children, and made sure no one traps the event. 

I created a simple Codepen project to show the issue. This is simply exported from an example in GroupedList fluend ui documentation site and I only change a little bit in onRenderCell to reflect our div there. I didn't even put this groupedList inside a panel body, but I can still reproduce this bug.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/chihch/pen/ZEQLQMZ

#### Actual behavior:

onCLick handler of groupedList item isn't called when 'enter'/space key is clicked. 

#### Expected behavior:

onClick handler of the groupedList item should be called when 'enter' key is clicked

**Comment by JustSlone** [comment]
So the onClick handler in this case is the standard handler that only responds to mouse clicks. If you want to also respond to key presses you can add an onKeyPress handler and test for the keycode. 

Something like this. (I updated your codePen here: https://codepen.io/justslone-the-encoder/pen/RwrVeQp?editors=1010)
```jsx
<div role="gridcell" tabIndex={0} className={classNames.name}
        onClick={() =>{
          alert('notification item clicked');
        }}
        onKeyPress={(event) =>{
          var code = event.keyCode || event.which;
          if(code === 13) {
            alert('notification item enter pressed');
          }
        }}
      > 
        {item.name}
      </div>
```

This should give the behavior you want, let us know if this works.

**Comment by chihch** [comment]
thanks! This is working.
