### ISSUE TITLE
The toggle should be rendered as inline-block instead of block

### ISSUE THREAD

**Issue by lzl124631x** [microsoft/fluentui#13721]
### Environment Information

- **Package version(s)**: https://developer.microsoft.com/en-us/fluentui#/controls/web/toggle
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

![image](https://user-images.githubusercontent.com/5824517/85184928-adb50d00-b246-11ea-94e7-75ecf79d72df.png)

In the above screenshot, the red lines are clickable and will toggle the toggle, which is unexpected and inconsistent because the green lines are not clickable.

Accidentally clicking on those red lines causing unexpected toggling is very annoying.

#### Expected behavior:

![image](https://user-images.githubusercontent.com/5824517/85184978-e228c900-b246-11ea-88a2-3b3d406ad8a1.png)

only these green areas should be clickable

### Priorities and help requested:

Are you willing to submit a PR to fix? YES

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by lzl124631x** [comment]
ping

**Comment by paulgildea** [comment]
@xugao Do you think making this fix will break existing customers?

If @xugao confirms that this is a safe fix @lzl124631x  feel free to submit a PR

**Comment by xugao** [comment]
@lzl124631x - i believe the right fix should be to `preventDefault` on `Label` click:
https://github.com/microsoft/fluentui/blob/785bb938355c341229996fcd3c6e51445de5d336/packages/office-ui-fabric-react/src/components/Toggle/Toggle.base.tsx#L154
So we need to add `onClick` on this line and add `ev.preventDefault` logic

**Comment by qianghuang94** [comment]
What's the ETA for this bug?

**Comment by zeedomD** [comment]
Any updates on this issue? Thanks.

**Comment by xugao** [comment]
@qianghuang94 , @zeedomD - sorry for the delay. I will take a look at this
