### ISSUE TITLE
can we hide the close icon in react dialog ?

### ISSUE THREAD

**Issue by nmaitreyi** [microsoft/fluentui#13728]
` <Dialog
                        title="Dialog Title"
                        
                        onClose={this.handleClose}
                        buttons={
                            [{
                                text: "Close",
                                onClick: () => this.handleClose()
                            }]
                        }>
                        <h1>Dialog Content</h1>
                        <p>More Content. Anything goes here</p>
                    </Dialog>`

**Comment by jedmonsanto** [comment]
@nmaitreyi i added this property `dialogContentProps` and no close button appears in my dialog
![image](https://user-images.githubusercontent.com/23548643/85224083-4a6bdc00-b3fa-11ea-84ac-b02a777a8600.png)

it replaces the border top blue when added the property
![image](https://user-images.githubusercontent.com/23548643/85224139-aafb1900-b3fa-11ea-9f8b-f98706e2d7af.png)

i wonder why i can't find any in the documentation but works in my end.

**Comment by nmaitreyi** [comment]
thank you so much this solved my issue.
