### ISSUE TITLE
Most toggled components hides on scroll

### ISSUE THREAD

**Issue by git-ced** [microsoft/fluentui#13730]
**Note:** Not sure if this is a bug or its part of the design.

#### Actual behavior:

Most components that are toggled (pickers, dropdown, combobox, etc.) hides/dismiss on scroll. I often found it a bad user experience when i accidentally scroll, or wants to scroll to look for more details.

#### Expected behavior:

The toggled components will retain its visibility state on scroll.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by paulgildea** [comment]
I'll follow up to see if this is by Design.

**Comment by vamshi9666** [comment]
any update  ? @paulgildea
