### ISSUE TITLE
IconButton triggering onDismiss as soon as the menu is launched on iPhone

### ISSUE THREAD

**Issue by rameshmaganti** [microsoft/fluentui#13746]
### Environment Information

- **Package version(s)**: ^7.105.9
- **Browser and OS versions**: Safari Browser and iOS 13.x

#### Actual behavior:

1. Go to URL: https://support.xbox.com/
2. Login to the application with live account
3. Tap on "me control" under header section
4. Tap on "More Options" Icon
5. Observe the More Options menu is not opened
6. Tap around the button other than the Icon and see the More Options menu is opend

We are seeing a strange phenomenon with “Icon button” placed with in “FocusTrapCallout” component in iPhone.  If we tap right on the Icon ‘…’ the flyout closes as soon as it is opened.  However it works fine, if we tap around the Icon symbol and show the context menu with additional links.  PFA the video with screen capture.
 
When we tap on the icon symbol, onMenuClick is triggered and immediately onDismiss is triggered.  Please see the attached video for more details.
 

#### Expected behavior:

"More Options" Menu is opened on tapping any where on the icon button.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: https://support.xbox.com

[IphoneIconButonIssue.zip](https://github.com/microsoft/fluentui/files/4816083/IphoneIconButonIssue.zip)

**Comment by idolize** [comment]
I was able to come up with a temporary fix for Safari by disabling 'resize' dismiss events. Currently, in Safari, it seems to trigger a resize whenever the menu popup opens (thus instantly closing it), so turning this off is a workaround:

```jsx
    <IconButton
      menuProps={{
        items: menuItems,
        calloutProps: {
          // !! Needed to fix issue in Safari
          preventDismissOnEvent: (e) => e.type === 'resize',
        },
      }}
      role="menuitem"
      title="More options"
    />
```

I also had to do this in my Callout menus as well:

```jsx
        <Callout
          onDismiss={handleClose}
          // !! Needed to fix issue in Safari
          preventDismissOnEvent={(e) => e.type === 'resize'}
        >
```
