### ISSUE TITLE
Dropdown select item by pressing the first chars in his title

### ISSUE THREAD

**Issue by Dangerous-Mind** [microsoft/fluentui#13757]
#### Describe the feature that you would like added
On the normal HTML Dropdowns, on modern browsers, if you press the first letter you are selecting the first item with that letters you pressed. This doesn't happen in the Fluent UI dropdown.

There are other options that use a similar usability of this feature, like the Combobox, Virtualized Combobox or Tag Picker. But it's not the same thing as the old Dropdown.

Can you add this feature to Fluent UI Dropdowns?
#### What component or utility would this be added to
Dropdown

**Comment by paulgildea** [comment]
@Dangerous-Mind good suggestion!

We're currently focusing on improvements to performance and coherence, as you can see in our pinned issue on the repo detailing our [v8 plans](https://github.com/microsoft/fluentui/issues/12770). 

So while we don't plan to address this right now, we will take it into consideration when we schedule future work for `Dropdown`. Thank you for reaching out to us.

@JustSlone this might be a good first contribution suggestion.
