### ISSUE TITLE
Panel Header text and Close button on top are not inline they render differently when compared to the sample shown.

### ISSUE THREAD

**Issue by KalapJo1** [microsoft/fluentui#13756]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

Close button and header text should be in same div, In the sample, they are present under panel navigation div. But when I use in SPFX  and on serve it, header text is present in contentInner div  but not panel command>navigation 

#### Expected behavior:
Close button and header text should be in same line or same div when rendered similar to the sample shown in document.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@KalapJo1 could you provide a little more info to the issue that you are running into?

Could you possibly link to a example of the issue to help narrow this down? Possibly the package versions to help us understand if this is a recent regression or not?

**Comment by KalapJo1** [comment]
I moved the application from "office-ui-fabric-react": "6.189.2" to "@fluentui/react": "^7.121.2". I recently added this panel component to the application and found the difference from that in the documentation. Please find the attached Image for the UI issue and the component props in the render method mentioned below.

Browser: MS Edge Version 83.0.478.54 (Official build) (64-bit)

render method
<Panel isOpen={isOpen}
        headerText = "View"
        hasCloseButton={true}
        closeButtonAriaLabel="Close"
        type={PanelType.medium}
        onRenderFooterContent={this._onRenderFooterContent}>
</Panel>

![image](https://user-images.githubusercontent.com/67148110/85740325-29b7c500-b71f-11ea-8194-86762d94ad7b.png)

**Comment by KalapJo1** [comment]
SPFX setup installs "office-ui-fabric-react": "6.189.2" on setup and when latest "@fluentui/react": "^7.121.2". is installed it does not remove the old package caused the issue.
