### ISSUE TITLE
Site/Docs not loading in North America

### ISSUE THREAD

**Issue by ianchursky** [microsoft/fluentui#13762]
Your site https://developer.microsoft.com/en-us/fluentui is not loading in North America. However, we have a colleague in India for whom it does load.

There are 404s on 2 scripts.

**Comment by rchandu** [comment]
I'm in India and it doesn't load here currently. 

PFA error in console:
<img width="676" alt="Screenshot 2020-06-23 at 8 58 46 PM" src="https://user-images.githubusercontent.com/6855103/85423634-905ca780-b594-11ea-9eda-82274bcb06f1.png">

Error as text:
`GET https://fabricweb.azureedge.net/fabric-website/v7_20200623.1/fabric-sitev5.min.js net::ERR_ABORTED 404`

`GET https://fabricweb.azureedge.net/fabric-website/v7_20200623.1/fabric-sitev5.js net::ERR_ABORTED 404`

**Comment by ianchursky** [comment]
The site seems to be loading fine now so I'll go ahead and close this one out.
