### ISSUE TITLE
GroupedVerticalBarChart: The second bar chart disappear when the number of GroupedVerticalBarChart is greater than 2 in one page

### ISSUE THREAD

**Issue by luckyrass** [microsoft/fluentui#13774]
### Environment Information

- **Package version(s)**: (@uifabric/charting_v2.3.3)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

The second bar chart disappear when the number of GroupedVerticalBarChart is greater than 2 in one page.

How to repo it?
Add one more GroupedVerticalBarChart in fluentui\packages\charting\src\components\GroupedVerticalBarChart\examples\GroupedVerticalBarChart.Basic.Example.tsx file
```
    return (
      <div className={mergeStyles(rootStyle)}>
        <GroupedVerticalBarChart data={data} height={400} width={650} showYAxisGridLines />
        <GroupedVerticalBarChart data={data} height={400} width={650} showYAxisGridLines />
      </div>
    );
```

#### Actual behavior:

![image](https://user-images.githubusercontent.com/12230173/85533921-834ac180-b643-11ea-9d1f-db1b444c0b5f.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/12230173/85534132-aa08f800-b643-11ea-8f17-c6230eac508d.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (High)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@Raghurk Is this a known issue?

**Comment by jameelakowsar** [comment]
#IssueFIxed 
https://github.com/microsoft/fluentui/pull/13781
