### ISSUE TITLE
Old version of @fluentui/react-icons-northstar was pushed to npm as the latest version

### ISSUE THREAD

**Issue by erdomke** [microsoft/fluentui#13778]
It appears that an old version of the `@fluentui/react-icons-northstar` (`0.47.6`) was pushed to npm as the latest package which is causing issues with using this package at the correct latest version (`0.50.0`). 

![image](https://user-images.githubusercontent.com/4406364/85564582-63dc7600-b5fc-11ea-8512-9f6361bb0fab.png)

**Comment by layershifter** [comment]
@erdomke thanks for reporting 👍 

***

![image](https://user-images.githubusercontent.com/14183168/85567004-cc454a80-b630-11ea-9d1b-2d763a19ced6.png)

Fixed and sorry for inconvenience 🐱

**Comment by paulgildea** [comment]
Thanks @layershifter!
