### ISSUE TITLE
Simple grouped DetailsList: [Enhancement Request] [Accessibility]: Feasibility to add aria-label as a prop for the grouped details list. 

### ISSUE THREAD

**Issue by AbhijitUI** [microsoft/fluentui#13782]
#### Describe the feature that you would like added

As of today, if we verify this component [Simple Grouped DetailsList](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/grouped), we don't have an option/way to pass custom aria labels depending upon the business need, we are requesting inclusion of a prop for aria-label which can be passed to the component.

#### What component or utility would this be added to

We need it to review historical data for one of our components, this component is a vital piece for displaying information to end users.

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

<img width="956" alt="Github Issue Akshay" src="https://user-images.githubusercontent.com/16835753/85576326-efcebc00-b655-11ea-8068-48bf59ccb2da.png">

**Comment by paulgildea** [comment]
@AbhijitUI Thanks for the feedback. We'll consider it as we start to converge our components for v8.

@xugao Do you happen to know if we don't support this today? I'm assuming we don't.
