### ISSUE TITLE
callout non focusable text is not getting read by the screen reader

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#13788]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: edge+Nvda

### Describe the issue:

accoriding to the https://developer.microsoft.com/en-us/fluentui#/controls/web/callout , there is a example for (Non-focusable Callout with accessible text), it only works fine when there is onClick on the button. if we change the onClick -> onFocus the screen reader is not reading the text inside it.

### Please provide a reproduction of the issue in a codepen:

here is a reproduction link
https://codepen.io/ssarapu/pen/ExPXKra

#### Actual behavior:

screen reader is not reading the accessible  text when we replace onClick-> onFocus for the button in the above example

#### Expected behavior:

screen reader should read the accessible  text when we replace onClick-> onFocus for the button in the above example

**Comment by shivasai09** [comment]
can anyone triage this issue

**Comment by paulgildea** [comment]
@joschect Do you know if this the expected behavior for this specific example of `Button`? or is this a fundamental `Announced` issue?
