### ISSUE TITLE
CheckBox: HTML validator error - div inside label

### ISSUE THREAD

**Issue by eivindland** [microsoft/fluentui#13799]
### Environment Information

- **Package version(s)**: Fluent webside

#### Actual behavior:

The div inside a Checkbox' label is not valid. If you put the outputted code from as list of checkboxes into HTML validator: https://validator.w3.org/nu/#textarea the result is: 

"Element div not allowed as child of element label in this context"

#### Expected behavior:

Expects valid HTML, ie span inside label.

### Priorities and help requested:

Requested priority: (Blocking, High, Normal, Low)

Normal

Products/sites affected: (if applicable)

Not known

**Comment by paulgildea** [comment]
@eivindland Thanks for the issue!

We probably won't address this issue in the current version as folks have taken dependencies on internal structure of components in the past; however, we can take this into consideration as we converge our components in the v8 code base.

@joschect - This would be considered a breaking change correct?

**Comment by curtisj44** [comment]
FWIW, this issue with the Checkbox component causes a failure in the "Parsing" check of [Accessibility Insights](https://accessibilityinsights.io/). That step relies on the [Nu HTML Checker](https://validator.w3.org/nu/) to check for "WCAG 2.0 parsing compliance", which includes improperly nested elements (this issue).

![Accessibility Insights Parsing screen](https://user-images.githubusercontent.com/810231/92806846-35ef0e00-f36f-11ea-8358-a0d97ce0932b.png)
