### ISSUE TITLE
Incorrect button colors in Azure Theme Dark

### ISSUE THREAD

**Issue by Agalin** [microsoft/fluentui#13819]
After theme updates in 7.1 disabled buttons in dark Azure theme are no longer dark. Background and text color have been changed to those of the light theme. Additionally icon for disabled ActionButton is basically invisible with new colors used.

Those colors make it more visible that ActionButton without an icon is higher than the one with it. Is it intentional?

### Environment Information

- **Package version(s)**:  azure-themes 7.1.30 (latest)
- **Browser and OS versions**: Windows 10, tested Edge and Firefox

#### Actual behavior:

How buttons look in 7.1:
https://codepen.io/agalin/pen/JjGyoWp

#### Expected behavior:

How buttons looked in 7.0:
https://codepen.io/agalin/pen/OJMjPgK

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Low

Products/sites affected: (if applicable) N/A

**Comment by paulgildea** [comment]
@Agalin Thanks for the issue.

There's been some codeowner changes in this area - and we'll track down an individual to take a look at this area.

Thanks!

@micahgodbolt @JustSlone - FYI

**Comment by Agalin** [comment]
Seems to be fixed in 7.6.2, not sure in which version between 7.1 and 7.6 tho.
