### ISSUE TITLE
Multi Select combo box , UI Fabric , stop working in SPFX Control

### ISSUE THREAD

**Issue by Sachindagar** [microsoft/fluentui#13815]
Multi Select combo box , UI Fabric , stop working in SPFX Control.
We are using Multi Select Combo box. It was working till yesterday however sudden its stop working. Whenever we are trying to select multiple values, the values are not selected.

Post selection, the values are not populated in the combobox

https://user-images.githubusercontent.com/26018001/85387276-f5f66700-b587-11ea-9281-3a23ac41e0ca.png

### Environment Information

- **Package version(s)**:  office-ui-fabric-react": "^6.214.0, "@microsoft/sp-office-ui-fabric-core": "1.10.0",
- **Browser and OS versions**: IE Edge, Chrome & Mozilla 

<ComboBox 

                        placeholder="Select" id="ddlCode" label="Code"
                        options={this.state.CodeOptions}  
                        multiSelect
                        autoComplete={ "on" }
                        onMenuDismissed={this._OnChangeCode.bind(this)}
                     
          />

#### Actual behavior:

Multi Select is not working. When we are trying to select then its not selected from mouse click. 

#### Expected behavior:

Multi select option should be selected.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

**Comment by Sachindagar** [comment]
We are using this with SPFX

**Comment by paulgildea** [comment]
@Sachindagar Thanks for the version information of both SPFX and Fluent.

**Comment by ecraig12345** [comment]
Are you still having this issue? If so, we'll need a codepen repro to help debug. You can start from https://aka.ms/fluentpen or "Export to CodePen" on one of the ComboBox examples on the website. https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox
