### ISSUE TITLE
The ability to configure the close button in the Dialog and Panel components

### ISSUE THREAD

**Issue by jacksonv1lle** [microsoft/fluentui#13823]
#### Describe the feature that you would like added
I would like to be able to configure the IButtonProps of the close button in both the Dialog and Panel components however there is currently no way to do this using the IDialogProps or IPanelProps

#### What component or utility would this be added to

Panel
Dialog

#### Have you discussed this feature with our team, and if so, who

No

**Comment by paulgildea** [comment]
@jacksonv1lle Thanks for the feature request.

What exactly are you trying to achieve? There may be a workaround if you are trying to make a targeted change.

**Comment by jacksonv1lle** [comment]
Hi @paulgildea. Thanks for the reply. I'd like to be able to change the icon of the close button in these components

**Comment by dvd73** [comment]
Hi
I have the same problem: is it possible to apply a new icon to the Close button?

**Comment by khmakoto** [comment]
Hi @dvd73 and @jacksonv1lle, I'm afraid it's not currently possible to change the close icon in dialog or panel since the icon name is hardcoded. However, we are planning to refresh these components in the future, we'll track this request as part of that work.
