### ISSUE TITLE
Masked Input Cursor Behaviour

### ISSUE THREAD

**Issue by dynamite-ready** [microsoft/fluentui#13820]
### Environment Information

- **Package version(s)**: office-ui-fabric-react 7.121.2

#### Actual behavior:

Quoting @micahgodbolt from #11323:

> "put focus in masked text field, press 'g' twice, return focus, press 'backspace' twice"... When I dug into the bug: Keystrokes that don't change the input eventually stop causing an onchange and browser moves focus to the end of the input.

![image](https://user-images.githubusercontent.com/1434956/69746739-cb2f5780-10f9-11ea-85d8-b844bc16734f.gif)

#### Expected behavior:

Predictable cursor behaviour, when editing a `MaskedTextField` input component

**Comment by paulgildea** [comment]
@dynamite-ready Thanks for the repo of the issue and version information!
