### ISSUE TITLE
Component rendered outside Provider throws

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#13836]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.50.0

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/button-without-provider-error-gbcyr?file=/src/App.tsx

Render a component out of a `Provider`.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/9615899/85979650-32d7b900-b9e1-11ea-9bb2-b9f1011f3386.png)

#### Expected behavior:

No error thrown.

**Comment by mnajdova** [comment]
The reason for this is that in all components we use:
```tsx
const context = React.useContext(ThemeContext); // imported from react-fela`
```

First of all we want to get rid of this dependency to react-fela and create our own context. 

In the meantime what do you think of these changes:

```diff
// export this under the @fluentui/styles package
+ const useTheme = (): ProviderContextPrepared => {
+  const context = React.useContext(ThemeContext);
+  return context || {
+    rtl: false,
+    disableAnimations: false,
+    performance: {
+      enableSanitizeCssPlugin: false,
+      enableStylesCaching: false,
+      enableVariablesCaching: false,
+      enableBooleanVariablesCaching: false,
+    },
+    renderer: noopRenderer,
+    theme: emptyTheme,
+  };
+ };

// go over all components and do this change
- const context: ProviderContextPrepared = React.useContext(ThemeContext);
+ const context = useTheme(); 
```

Anyway, I would say that this is not a big issue in this moment, and we already have plans for getting rid of the `ThemeContext` from `react-fela`, so I would propose let's hold off with this changes and fix it once we are going to handle this.

**Comment by layershifter** [comment]
We can make a step forward and use own React Context for this and get rid of dependency on `react-fela` there.
