### ISSUE TITLE
Date picker year defaulting to 2001 rather than current year

### ISSUE THREAD

**Issue by jtripathi226** [microsoft/fluentui#13834]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

When user types in just the date and month in a date picker, the picker defaults the year to 2001 rather than current year

#### Actual behavior:

Year defaults to 2001

#### Expected behavior:

Year should default to current year

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
Teams meeting scheduler

**Comment by paulgildea** [comment]
@jtripathi226 Could you provide which version of the library you are using and possibly a codepen repo? That will help us understand if this a regression.

Thanks!

**Comment by jtripathi226** [comment]
Here is the codepen: https://codepen.io/pen/?&editable=true=https%3A%2F%2Ffabricweb.z5.web.core.windows.net%2Fpr-deploy-site%2Frefs%2Fheads%2Fmaster%2Ffabric-website-resources%2Fdist%2Findex.html
Version: office-ui-fabric-react": "^6.213.0
Repro steps:

  1.  Edit date picker to enter date and month (6/12)
  2.  Date defaults the year to 2001 instead of current year 2020


Let me know if more information is required.

Regards,
Jyoti Tripathi

**Comment by jtripathi226** [comment]
Apologies the codepen shared isn’t accurate, there seems to be some problem in generating codepen, you can test it out here for reference: https://docs.microsoft.com/en-us/javascript/api/examples/datepicker?view=office-ui-fabric-react-latest

**Comment by paulgildea** [comment]
@jtripathi226 Thanks for the update. We really appreciate it!

**Comment by paulgildea** [comment]
@mnajdova - This would be another good one to take a look at. If you have questions ping @lorejoh12

**Comment by mnajdova** [comment]
@jtripathi226 can you please share the actual example you are trying? What kind of date formatting you are using. When I try to enter only the date & month I am getting Invalid date format error on the example there. If I choose those from the opened popup, the year is correct. Thanks in advance

**Comment by jtripathi226** [comment]
I am trying to input 06/05 it translates to 5th June 2001 where as it should have defaulted the year to 2020. I do not see any invalid date format error. https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker - Here I am trying with “datepicker allows input date string”.

**Comment by mnajdova** [comment]
Thanks for the clarification @jtripathi226 I could repro it now. Taking a look on it

**Comment by mnajdova** [comment]
I dig a bit deeper into the issue and it seems like this is the chrome's behavior on `new Date()`. If no year is specified it defaults for some reason to 2001. @lorejoh12 can you suggest what would be the best fix for this?
