### ISSUE TITLE
Overriding is-selected for NavLinks

### ISSUE THREAD

**Issue by ayushgp** [microsoft/fluentui#13854]
I'm trying to mark a link as selected if the base URL matches. For example, I have a link `/contacts` which automatically get marked as active/selected when I navigate to that route. But in cases where I have a link like `/contacts/204` I'm trying to manually mark it as selected using the following. But this class gets added to the inner link but not the outer CompositeLink.

```
const onRenderLink = (props: ILinkProps) => {
    const path = window.location.pathname;
    return (
        <NavLink
            className={`${props.className} ${path.startsWith(props.href || '') ? 'is-selected' : ''}`}
            to={props.href!}
        >
            <span>
                <Icon style={{ margin: '0 4px' }} {...props.iconProps} />
                {props.children}
            </span>
        </NavLink>
    );
};
```

My Nav Component:
```
export const SideBar: React.FC<Props> = ({ onLinkClick }: Props) => {
    const { t } = useTranslation();

    return (
        <div>
            <Nav
                linkAs={onRenderLink}
                onLinkClick={onLinkClick}
                onRenderGroupHeader={_onRenderGroupHeader}
                groups={_sidebarGroups}
            />
        </div>
    );
};

function _onRenderGroupHeader(group: IRenderGroupHeaderProps | undefined) {
    return <h3>{group?.name}</h3>;
}

const _sidebarGroups = (): INavLinkGroup[] => [...]
```
In normal `/contacts` cases:
![image](https://user-images.githubusercontent.com/7992943/86093181-28461e00-bacc-11ea-9b95-4918427a3c61.png)

In `/contact/:id` cases:
![image](https://user-images.githubusercontent.com/7992943/86092782-9e965080-bacb-11ea-8722-3c1c574bf765.png)

Is there a way to mark the link as active in such cases? Not sure if this is expected or a bug.

**Comment by paulgildea** [comment]
@ecraig12345 - Is this the expected behavior or is there a way through CSSinJSS to supply an active link styling?

**Comment by ecraig12345** [comment]
I think the most idiomatic solution here is to track the selected route outside of where you're rendering the Nav, and then update the Nav's `selectedKey` to reflect the currently navigated URL.
