### ISSUE TITLE
@fluentui/date-time-utilities tests do not run on Windows.

### ISSUE THREAD

**Issue by rymeskar** [microsoft/fluentui#13858]
### Environment Information

- **Package version(s)**: 7.1.2
- **Browser and OS versions**: Windows build machine

### Please provide a reproduction of the bug in a codepen:

Relates to build so the codepen is irrelevant.

#### Actual behavior:

`process.env.TZ = 'UTC';` jest [setup](https://github.com/microsoft/fluentui/blob/6525619bf5e6c844406ed3cb9ad3103237eff89f/packages/date-time-utilities/config/timezone-setup.js#L2) does not work on Windows. There are nodejs issues ([1](https://github.com/nodejs/node/issues/4230), [2](https://github.com/nodejs/node/issues/31478)) explaining why this is the case. 

#### Expected behavior:

The [following tests](https://github.com/microsoft/fluentui/blob/6525619bf5e6c844406ed3cb9ad3103237eff89f/packages/date-time-utilities/src/dateGrid/getDayGrid.test.ts#L21) should succeed on all types of build machines.

**Comment by paulgildea** [comment]
@rymeskar Thanks for the issue!

@lorejoh12 - Not sure if this is specific to the date-time package or if this is an infrastructure issue.

@ecraig12345 as FYI.

**Comment by ecraig12345** [comment]
@pompomon Can you help fix this since it looks like you introduced that setup file?
