### ISSUE TITLE
tooltipHostProps.content is not applied for CommandBar button with iconOnly=false

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#13877]
We are using TooltipHost to keep the tooltip accessible (user can see tooltip when focusing on a button with keyboard instead of mouse) and consistent across the browsers, but we are blocked on the CommandBar.

### Environment Information

- **Package version(s)**: 7.121.6
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/xinychen/pen/JjGOJWg

#### Actual behavior:
Hover on "Download" button, you can see the tooltip rendered by ToolTipHost (you can also see the one rendered by browser).
![image](https://user-images.githubusercontent.com/50703224/86200836-60169980-bb90-11ea-9bbb-ed1eece25052.png)

Whereas hovering on other buttons with `iconOnly: false` (e.g. "Share"), ToolTip is not rendered by ToolTipHost and you can only see the one rendered by browser.
![image](https://user-images.githubusercontent.com/50703224/86200849-660c7a80-bb90-11ea-97f8-f78bb6ef74ac.png)

#### Expected behavior:
I should see the tooltip rendered by ToolTipHost, as I've set `tooltipHostProps`.

### Priorities and help requested:

Are you willing to submit a PR to fix? Maybe later.

Requested priority: Normal

Products/sites affected: Synapse Studio

**Comment by paulgildea** [comment]
Thanks for the repo @chenxinyanc !
