### ISSUE TITLE
Basic DetailsList spacing accessibility bug

### ISSUE THREAD

**Issue by woofton** [microsoft/fluentui#13872]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: Edge

### Describe the issue:

Use [text spacing bookmarklet](https://nam06.safelinks.protection.outlook.com/?url=https://www.html5accessibility.com/tests/tsbookmarklet.html&data=02%7c01%7cv-asng%40microsoft.com%7ce2a5a71675ca46961a1e08d740227601%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637048389059544081&sdata=fVc3ZNdxlVTpIO0j5ccUshHzTwlt4Nbx124TkkYo9a0%3D&reserved=0) to apply the text spacing

When you run the text spacing against: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic the selection column spacing is off.

MAS 1.4.12 - Text Spacing

### Please provide a reproduction of the issue in a codepen:

Tried codepen but the text spacing tool doesn't seem to be working.

https://aka.ms/fluentdemo is broken by the way.

So, when you run the text spacing against: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic the selection column spacing is off.

#### Actual behavior:

The selected column spacing is off.

![image](https://user-images.githubusercontent.com/11826995/86180143-69482d80-bae0-11ea-9f15-74c48f29797f.png)

#### Expected behavior:

Expect the selected column image to align up properly.

### Documentation describing expected behavior

MAS 1.4.12 - Text Spacing

**Comment by paulgildea** [comment]
@woofton - looking at the repo the bookmarklet it says that's it's experimental.

Is this a testing tool or a supported feature for user to change text spacing?
