### ISSUE TITLE
ComboBox: Add onRenderTitle option for comboBox

### ISSUE THREAD

**Issue by Meher-Prabhu** [microsoft/fluentui#13881]
#### Describe the feature that you would like added

ComboBox has an option to custom render options (using onRenderOption) but if we want the same rendering style for the selected option in the input, we can't do that. 

This is something which is available in dropdown. In dropdown, we can use onRenderOption for the option and onRenderTitle for the selected option. 

Given comboBox is a superset of dropdown, it'd be great if such an option is available for comboBox too. 

I've implemented this using dropdown and attached a screenshot of what I've implemented. I want to do something similar with a comboBox.

#### What component or utility would this be added to

ComboBox

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/6253862/86241497-9b30c100-bbc0-11ea-9752-c56ef1026004.png)

**Comment by paulgildea** [comment]
@Meher-Prabhu Thanks for the feature request.

We're currently focusing on improvements to performance and coherence, as you can see in our pinned issue on the repo detailing our [v8 plans](https://github.com/microsoft/fluentui/issues/12770). So while we don't plan to address this right now, we will take it into consideration when we schedule future work for `ComboBox`. 

Thank you for reaching out to us.

@dzearing @joschect - I like this proposal, however I know that ComboBox allows the user to type in content and so I would believe the API contract would be a little more complex that what Dropdown has today.
