### ISSUE TITLE
LineChart: Keyboard navigation does not transition between different legend lines in a chart

### ISSUE THREAD

**Issue by tusharjape-msft** [microsoft/fluentui#13895]
### Environment Information

- **Package version(s)**: @uifabrc/charting
- **Browser and OS versions**: All

### Describe the issue:

In line chart while using keyboard navigation, the navigation does not transition between legend lines. If a particular line is selected by cursor arrow keys help navigate only on that line. After the last point on the line it should move to the next legend line.

#### Actual behavior:
In line chart while using keyboard navigation, the navigation does not transition between legend lines. If a particular line is selected by cursor arrow keys help navigate only on that line. 

#### Expected behavior:
After the last point on the line it should move to the next legend line.

**Comment by paulgildea** [comment]
@Raghurk - Mind taking a look at this one too? 👍
