### ISSUE TITLE
Missing splitButtonMenuButtonHovered property from IButtonStyles

### ISSUE THREAD

**Issue by benceczeili** [microsoft/fluentui#13899]
### Environment Information

- **Package version(s)**: office-ui-fabric-react
- **Browser and OS versions**:  All

### Please provide a reproduction of the bug in a codepen:

I would like to create a customized ****CommandBarButton**** with split option, by override the all of default styles.
But the IButtonStyle interface doesn't has splitButtonMenuButtonHovered property.

It has:
  -  ```typescript
      /**
      \* Style override for the SplitButton menu button
      */
      splitButtonMenuButton?: IStyle;
     ```
  - ```typescript 
     /**
     \* Style override for the SplitButton menu button element in a disabled state.
     */
     splitButtonMenuButtonDisabled?: IStyle;
     ```
   - ```typescript
     /**
     \* Style override for the SplitButton menu button element in a checked state
     */
     splitButtonMenuButtonChecked?: IStyle;
     ```
   - ```typescript
     /**
     \* Style override for the SplitButton menu button element in an expanded state
     */
     splitButtonMenuButtonExpanded?: IStyle;
     ```

But I cannot set style to the hovered action.
If I use the splitButtonContainerHovered property it just set the bottom level style.
![styles](https://user-images.githubusercontent.com/32644851/86355724-6d548680-bc6b-11ea-8026-c3f6f8ca2280.png)

Default, disabled (and others) work properly, but when I move mouse to MenuButton change the color to default grey color.
![button](https://user-images.githubusercontent.com/32644851/86355738-70e80d80-bc6b-11ea-872b-56d65c553baf.png)

Maybe useful, when I tested with normal CommandButton the splitButtonContainerHovered property changed the color, but not how I wanted, so that also not a solution.
 
#### Actual behavior:

Missing splitButtonMenuButtonHovered property from IButtonStyles 

#### Expected behavior:

I could set the hovered property:
![expected](https://user-images.githubusercontent.com/32644851/86356164-1307f580-bc6c-11ea-99c3-361987081d4b.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No ☹

Requested priority: Normal

**Comment by mnajdova** [comment]
Hi @benceczeili, for the hover state, why are you not using the `selectors`? You can use something like:

```
splitButtonMenuButton: {
  selectors: {
    ':hover': {
      backgroundColor: p.neutralLighter,
      color: p.neutralDark,
      selectors: {
        [`.${ButtonGlobalClassNames.msButtonIcon}`]: {
          color: p.neutralPrimary,
        },
      },
    },
  },
}
```

or if you want to capture the root's hover, then accordingly you can add the styles on the root style object:
```
root: {
  selectors: {
    ':hover': {
      backgroundColor: p.neutralLighter,
      color: p.neutralDark,
      selectors: {
        [`.${ButtonGlobalClassNames.msButtonIcon}`]: { // you can use subselectors for targeting specific parts of the split button
          color: p.neutralPrimary,
        },
      },
    },
  },
}
```

**Comment by benceczeili** [comment]
Hi @mnajdova,
That's good for me, thank you for your answer!
