### ISSUE TITLE
Bug: Selection states with multi-row select in DetailsList not as straightforward

### ISSUE THREAD

**Issue by mryanlo** [microsoft/fluentui#13905]
I was playing around with multi-selection of the rows in DetailsList grid and noticed that selection is not as intuitive as I thought it would be. When the user clicks a row's checkbox, it will toggle that row's selection state as expected. But when you do things like shift select to select or deselect multiple options, then it seems fairly inconsistent. 

For example:
To start, I selected items 3 and 2 in that order: 
![image](https://user-images.githubusercontent.com/55516393/86402309-7855e980-bc60-11ea-9137-091da0005118.png)
I then try to shift select by clicking item 0. 
**Expected**: items 0 to 3 are selected. Basically, selection state should retain what already was selected.
**Actual**: only items 0 to 2 are selected with item 3 deselected: 
![image](https://user-images.githubusercontent.com/55516393/86402622-fdd99980-bc60-11ea-9386-20a28ffbb4a2.png)

We also noticed that selection behavior when (de)selecting items by clicking on the checkbox differ from clicking on the row itself. 

For example:
To start, I have all five items in view here selected:
![image](https://user-images.githubusercontent.com/55516393/86402823-5741c880-bc61-11ea-94c4-8be911ac9daf.png)
I want to deselect item 0. Clicking on the checkbox does the desired behavior:
![image](https://user-images.githubusercontent.com/55516393/86402875-72acd380-bc61-11ea-8416-1355746541c5.png)
But clicking on the row for item 0 itself (ie: somewhere in middle somewhere away from the row's checkbox) has different results:
**Expected**: same behavior as the image above (deselcting item 0 by clicking on the row's checkbox) and item 0 should be toggled off while rest still are selected.
**Actual**: Item 0 is selected but rest aren't.
![image](https://user-images.githubusercontent.com/55516393/86403013-b4d61500-bc61-11ea-97b6-d702414b499c.png)

Here's a codepen from one of the fabric developers that uses DetailsList (and only adds a few callback features to print to console, nothing more) that one can play with DetailsList in. The issues reproduce in this codepen as well. https://codepen.io/kevintcoughlin/pen/wOxGjO?editors=1010

Any help would be greatly appreciated. Thanks!

**Comment by paulgildea** [comment]
Thanks for the screenshots.

@mryanlo are you asking a how to question or do you think you found a specific bug?

**Comment by mryanlo** [comment]
@paulgildea  thank you for the response. I think I found a specific bug. The DetailsList selection state doesn't seem to do what most users would think would happen when dealing with multi-row selection, as described in the scenarios above, most notably shift-selecting.

**Comment by mryanlo** [comment]
Synced with another Microsoft employee. This selection behavior is default Microsoft-wide behavior and we shouldn't change this pattern. Was thinking how other products that use a "straightforward" selection behavior was more "intuitive"; whereas this behavior is normal behavior but I just wasn't used to it. Will close since this isn't a bug
