### ISSUE TITLE
[DatePicker] JAWS reads pickerAriaLabel information twice  

### ISSUE THREAD

**Issue by chtoosha** [microsoft/fluentui#13907]
### Environment Information

- **Package version(s)**: 7.110.5
- **Browser and OS versions**: WIN 10 + Chrome, Win 10 + Electron

### Describe the issue:

JAWS reader reads pickerAriaLabel twice

#### Actual behavior:

JAWS reader reads pickerAriaLabel twice.

#### Expected behavior:

JAWS reader  should read pickerAriaLabel once

### If applicable, please provide a codepen repro:

It is enough just to specify pickerAriaLabel for any type of date picker.
https://codepen.io/aleksandra-potapova/pen/KKVZqre

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) 
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)

**Comment by lorejoh12** [comment]
I don't have a JAWS license so I'm not able to test this with JAWS.

However, I tested this with Win10 + Edge + Narrator, and it does not repro using your codepen.
I also tested this with Win10 + NVDA + Edge and Chrome, and it does not repro in either of those.

If it does repro in JAWS, it's probably a screen reader bug.

**Comment by chtoosha** [comment]
@lorejoh12  Wondering if you, as a component owner, can open the bug on JAWS? 
I think that is the plase to files issues on JAWS?
https://github.com/FreedomScientific/VFO-standards-support/issues

**Comment by lorejoh12** [comment]
Given that I'm not able to repro the bug, since I don't have a JAWS licence, I won't be able to provide any additional details or information on the bug, and so don't feel I am the best to file it.

Closing this issue regardless since the resolution will be external and it does not repro in the above tested accessibility scenarios.
