### ISSUE TITLE
ShimmeredDetailsList does not have an option to style the Shimmer part of it

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#13909]
There is no prop in `ShimmeredDetailsList` to style the `Shimmer`. This can be seen [in this line](https://github.com/microsoft/fluentui/blob/d55eecf434dfe269ecbf6f412dcde73a13dace3e/packages/office-ui-fabric-react/src/components/DetailsList/ShimmeredDetailsList.base.tsx#L83) from `ShimmeredDetailsList.base.tsx` where no information about styling is being passed to the `Shimmer` element.

**Comment by khmakoto** [comment]
@Fadi2019 fyi.

**Comment by willchavez** [comment]
+1 for this issue
