### ISSUE TITLE
react-cards

### ISSUE THREAD

**Issue by diabhoil** [microsoft/fluentui#13918]
Hey I am building a webpage with react, typescript and parcel using fluentui. Everything is working fine but when using the "react-cards" library the browser will show this error:
![grafik](https://user-images.githubusercontent.com/42711805/86462182-79078200-bd2b-11ea-8086-e9310ee20ac8.png)

Had this error several times and fixed it by just importing the actual component like this:
`import { ITheme } from 'office-ui-fabric-react/lib/Styling';`
instead of the wrong way:
`import { Stack } from 'office-ui-fabric-react';`

But in this case the imports on these files [Card.view.tsx](https://github.com/microsoft/fluentui/blob/master/packages/react-cards/src/components/Card/Card.view.tsx), [CardSection.view.tsx](https://github.com/microsoft/fluentui/blob/master/packages/react-cards/src/components/Card/CardSection/CardSection.view.tsx) or for example here [CardItem.view.tsx](https://github.com/microsoft/fluentui/blob/master/packages/react-cards/src/components/Card/CardItem/CardItem.view.tsx) are causing the error. 

Any chance that someone might fix this or is there a reason why the imports in these files are handled like this?

### Environment Information

- **Package version(s)**: @uifabric/react-cards: 0.109.107

#### Actual behavior:

Code will not load with the Card component included and showing the error in the browser

#### Expected behavior:

Code will load without errors

### Priorities and help requested:

Are you willing to submit a PR to fix? guess its easier if someone working at react-cards could change it. If not..any chance that if I commit code, they will change it?

Requested priority: Blocking

**Comment by paulgildea** [comment]
@khmakoto / @dzearing - Is this a supported package or is this the card package that is released in `react-next` ?

**Comment by khmakoto** [comment]
Hi @diabhoil, feel free to make PR to fix this, we appreciate outside contributions! I'll be sure to review it if you do.

@paulgildea this is a package that was created for our earlier efforts into developing a `Card` component. It was planned to be supported but because of circular dependency issues we never got around to officially publish a major version bump. The `Card` planned for `react-next` is a different story.

**Comment by khmakoto** [comment]
Since we're moving forward with our new approach and since those components are deemed experimental I don't think it's worth it focusing on this issue right now.
