### ISSUE TITLE
React is listed as a direct dep in @fluentui/styles@0.50.0

### ISSUE THREAD

**Issue by tobiasviehweger** [microsoft/fluentui#13921]
### Environment Information

- **Package version(s)**: @fluentui/styles@0.50.0
- **Browser and OS versions**: Chrome @ stable

### Description

The lib includes a copy of React as a direct dependency (react@16.8.6), rather than a peerDep. This leads to this bug: https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react, as we are using React 16.12.

#### Actual behavior:

Using the Provider component from @fluentui/react-northstar@0.50.0 leads to our app not working at all, because two versions of React are bundled. 

#### Expected behavior:

Please consider using a peerDep instead.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by paulgildea** [comment]
@jurokapsiar - Is this a `northstar` issue? I couldn't tell from the package import.
