### ISSUE TITLE
Dropdown - first option automatically selected on click of the control

### ISSUE THREAD

**Issue by sunnyEspireGit** [microsoft/fluentui#13927]
Steps to Repro :
1. Create a dropdown
2. Add few options in that dropdown
3. when you open that dropdown in workbench to select on of the value, you will notice that just while opening it selects the first item and fires onChange event, even if you want to select different item.
4. Then when you will select other item it will fire onChange again.

**Comment by paulgildea** [comment]
@sunnyEspireGit - Thanks for the issue. Could you update your issuing using the bug template we provide and a link to a codepen so that we can reproduce the issue? That would be super helpful.

Thanks!

**Comment by sunnyEspireGit** [comment]
- Which Fluent UI component is causing the issue -> Dropdown
- Which package name and version the component is from ->  "office-ui-fabric-react": "6.189.2"
- Specific, complete steps to reproduce the issue :-
1. Create a dropdown
2. Add few options in that dropdown
3. when you open that dropdown in workbench to select on of the value, you will notice that just while opening it selects the first item and fires onChange event, even if you want to select different item.
4. Then when you will select other item it will fire onChange again.

- What behaviors and attributes are missing or incorrect -> "first option automatically selected on click of the control, and onChange event fired without even selected any value"
- What you expected and what is actually happening ->"there should be smooth transition, onChange event shouldn't fired when we click on dropdown to select any value"
- Confirmation that the problem reproduces in isolation -> Yes

**Comment by paulgildea** [comment]
Bringing attention to this one.

**Comment by xugao** [comment]
@sunnyEspireGit - I cannot repro with latest V6 Fabric: https://codepen.io/xugao/pen/ExPevpQ

Feel free to modify the codepen to share me the repro if mine is incorrect

**Comment by sunnyEspireGit** [comment]
is anything needed from my end for this issue ??

**Comment by paulgildea** [comment]
@sunnyEspireGit Could you see if you are still seeing the NVDA issue with the codepen that @xugao shared?

@xugao wasn't able to repro the issue in the latest version of the v6 package of Fabric. The fix might be address in a new version.

**Comment by sunnyEspireGit** [comment]
i don't see that issue in the provided code, but i am also using version  "office-ui-fabric-react": "6.189.2"........
Can i share my code which i am using in SPFx with react, so that you can help to fix that ?

**Comment by xugao** [comment]
@sunnyEspireGit - if you can provide a minimal repro, I can help look. But before that, i'd suggest to you upgrade to latest 6.* version (6.214.1) and see if you still have this issue.

**Comment by sunnyEspireGit** [comment]
can you please help with the steps to upgrade my solution from  "office-ui-fabric-react": "6.189.2" to version (6.214.1), 
so that my project will not break from wrong steps.

**Comment by xugao** [comment]
@sunnyEspireGit - I think that's a question for SPFx team. I'm not sure what the process is there. This [doc](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components#appendix-upgrading-office-ui-fabric-react-versions) doesn't seem to explain how to use latest v6 version of Fabric.

**Comment by sunnyEspireGit** [comment]
@xugao : how can i reach them to get the required steps to upgrade the version.....if you can mark them in this thread.

**Comment by xugao** [comment]
@sunnyEspireGit - you can open an issue in their github repo [here](https://github.com/SharePoint/sp-dev-docs/issues).
