### ISSUE TITLE
Fabric Core Icons are being rendered instead of Fluent UI Icons

### ISSUE THREAD

**Issue by GuiCavi** [microsoft/fluentui#13922]
### Environment Information

- **Package version(s)**:
```json
{
    "dependencies": {
        "@fluentui/react": "^7.114.0",
        "@uifabric/file-type-icons": "^7.3.13",
        "@uifabric/react-cards": "^0.109.81",
    }
}
```

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/GuiCavi/pen/ExPozOo?editors=0010

#### Actual behavior:

Looks like some *Logo icons are being rendered as Fabric Core Icons instead of Fluent UI React. (haven't loaded the Fabric Core stylesheet)

```tsx
<Icon
    iconName="OneNoteLogo"
    className={classNames.cardIcon}
    style={{ color: theme.palette.themePrimary }}
/>
```
![actual behavior (custom example)](https://user-images.githubusercontent.com/7794819/86498934-9a359600-bd5e-11ea-9a96-792e4fab91ca.png)

#### Expected behavior:

If not loaded the Fabric Core stylesheet, should render the Fabric UI React Icons

```tsx
<Icon
    iconName="OneNoteLogo"
/>
```
![expected behavior (print from available icons in doc)](https://user-images.githubusercontent.com/7794819/86498961-cea95200-bd5e-11ea-89db-b7c3271a6369.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No, I don't know the where is the problem

Requested priority: Normal?

Products/sites affected: Fluent UI React

**Comment by GuiCavi** [comment]
BTW, just found something weird.

I went into [DocumentCard docs](https://developer.microsoft.com/en-us/fluentui#/controls/web/documentcard) and the first image was loaded.

![image](https://user-images.githubusercontent.com/7794819/86499042-4a0b0380-bd5f-11ea-9ffd-4111816bbdc1.png)

---
After, navigate to [Icon docs](https://developer.microsoft.com/en-us/fluentui#/controls/web/icon) and clicked [on this link](https://developer.microsoft.com/en-us/fluentui#/styles/web/icons): `For a list of icons, visit our icon documentation.`

Navigate back to Icon docs (by history.back, not redirecting), and to DocumentCard docs. This way, I got the second image.

![image](https://user-images.githubusercontent.com/7794819/86499060-60b15a80-bd5f-11ea-9a03-56b0091d35ae.png)

**Comment by paulgildea** [comment]
@GuiCavi - Can you file a separate issue for the website issue you found? That would be helpful for making traction on both issues.

@dzearing / @JustSlone - We don't have icon owner - so I'm bring this to your attention

**Comment by GuiCavi** [comment]
@paulgildea sure. I thought they were related... I'll fill another then. Thanks for the reply

**Comment by Vivihung** [comment]
I have the same icon issues, too.
These are the icon I got
![image](https://user-images.githubusercontent.com/4814277/87999659-6a9dc200-cab0-11ea-9ae3-f9f81b18f9a7.png)
But I was expecting this type of MS brand icons
![image](https://user-images.githubusercontent.com/4814277/87999705-899c5400-cab0-11ea-80f3-62fc1196dc69.png)

My package.json
```
        "@fluentui/react": "7.105.10",
        "@fluentui/styles": "0.47.0",
```

React code example (same as @GuiCavi )
```
<Icon
    iconName="OneNoteLogo"
/>
```

**Comment by paulgildea** [comment]
Putting this back for investigation.

**Comment by xugao** [comment]
@GuiCavi - Currently [brand icons](https://developer.microsoft.com/en-us/fluentui#/styles/web/office-brand-icons) are not supported by rendering using `Icon` component.

There are 2 ways you can use brand icon in your app:
you can do
```
<link
  rel="stylesheet"
  href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css"
/>

<div class="ms-BrandIcon--icon96 ms-BrandIcon--word" />
```

or

```
<img src="https://static2.sharepointonline.com/files/fabric/assets/brand-icons/product/svg/word_48x1.svg" alt="Word product icon" />
```

**Comment by Vivihung** [comment]
Thanks for the dispatch, @paulgildea and the investigation, @xugao .
I will move my code to use the CDN image path.

By the wan, the documentation of the fluent UI really need some update in the brand icon section.

**Comment by GuiCavi** [comment]
Oh okay, got it for the brand icons. The fact is that i wasn't trying to use brand icons. As you can see in the image below, there is an "brand icon" for OneNote.

![image](https://user-images.githubusercontent.com/7794819/89365028-2e6e8200-d6aa-11ea-956a-822d0e6ad2da.png)

**Comment by JustSlone** [comment]
@Vivihung, agreed on the brand Icon page needing an update! I'll spin up a quick fix to the example on the page based on @xugao's suggested fix here.

@GuiCavi, actually (and it took me an embarrassingly long time to realize this) I'm pretty sure these are the monochrome version of the *new* Office icons! (https://news.microsoft.com/europe/2018/11/29/say-hello-to-microsofts-new-office-icons/)

There is clearly a bug in the website showing the old icons, but https://uifabricicons.azurewebsites.net/ and Fluent UI React seem correct here.

**Comment by GuiCavi** [comment]
@JustSlone thanks for the reply.

Got it. So, just for resuming the issue: The icons that Fluent UI React is showing when we use it are the right ones and the icon doc is the one that needs some kind of fix, right? 😄

**Comment by JustSlone** [comment]
@GuiCavi that is my understanding. I'll check with some folks tomorrow to confirm.

**Comment by GuiCavi** [comment]
@JustSlone so, it kills my question. Feel free to leave this issue as open till the fix is done or you can close it. Thanks for the attention to all of the team! 😄

**Comment by JustSlone** [comment]
@GuiCavi thank you for the report! Can you open the separate issue for the website showing the old (or just inconsistent) monochrome brand icons? Then I can close this one out.

**Comment by JustSlone** [comment]
I've confirmed these are in-fact the monochrome versions of the new icons, closing this issue. Thanks!

**Comment by GuiCavi** [comment]
>Can you open the separate issue for the website showing the old (or just inconsistent) monochrome brand icons?

@JustSlone, still needed to open another issue as you asked? Or you guys already aware of it? I can do it without problem.
