### ISSUE TITLE
ContextualMenu doesn't honor "focusProps" sub property

### ISSUE THREAD

**Issue by dotnetjunky** [microsoft/fluentui#13923]
The `ContextualMenu` component provides the `focusProps` sub prop, which can be used to override the default behavior of the inner `FocusZone` component. However, internally, it hard-codes a few properties, one of which is the `isCircularNavigation` prop. As a result, there's no way to set `isCircularNavigation` to `false` for a `ContextualMenu` component. 

### Environment Information

- **Package version(s)**:7.121.1
- **Browser and OS versions**: All browsers and OSes

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/dotnetjunky/pen/WNrMrbM

#### Actual behavior:

The contextual menu has circular navigation.

#### Expected behavior:

The contextual menu should NOT have circular navigation.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: (Not applicable)

**Comment by paulgildea** [comment]
@joschect - Might taking a look at this PR?
