### ISSUE TITLE
can't render In SSR? Fluent UI v0 / northstar

### ISSUE THREAD

**Issue by zerofront** [microsoft/fluentui#13925]
### Environment Information

- **Package version(s)**:  react-northstar 0.50.0
- **Browser and OS versions**:  macOS

I use Next.js as ssr render solution, When the server receives the request, it renders the required component(s) into an HTML string, and then sends it as a response to the client. From that point on, the client takes over rendering duties. 

But it's important to provide the page with the required CSS, otherwise the page will render with just the HTML then wait for the CSS to be injected by the client, causing it to flicker (FOUC).

I didn't find any API in React-Northstar to render CSS in server side and pass the css along to the client.

How Can I do for in northstar like https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing#nextjs-setup  or https://github.com/vercel/styled-jsx#styled-jsxserver

**Comment by paulgildea** [comment]
@jurokapsiar - Not sure if this is a supported scenario in v0, sending over your way 👍

**Comment by mosesoak** [comment]
@jurokapsiar @paulgildea 

We are just on the cusp of picking Fluent for our project but we are using NextJS and right now the methodology shown at [the fabric docs](https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing#nextjs-setup) is no longer up to date with how Next works.

I'm currently working on a solve here, if anyone wants to collaborate: https://github.com/vercel/vercel/discussions/4839
