### ISSUE TITLE
LineChart: Tooltip does not display when mouse over on data points(occurs when data points dense) and getting random points in graph

### ISSUE THREAD

**Issue by jameelakowsar** [microsoft/fluentui#13932]
### Environment Information

- **Package version(s)**: All versions
- **Browser and OS versions**: All browsers

#### Actual behavior:
![image](https://user-images.githubusercontent.com/20105532/86789690-32948900-c085-11ea-9503-fb5ad3c7dce9.png)

#### Expected behavior:

There should be no extra dots and all data points need to be display tooltip
Please prefer below screenshot.
![image](https://user-images.githubusercontent.com/20105532/86789834-61aafa80-c085-11ea-9010-905e8e49d0b7.png)

**Comment by paulgildea** [comment]
@Raghurk - Mind taking a look at this issue? 👍

**Comment by jameelakowsar** [comment]
Code merged to master
https://github.com/microsoft/fluentui/pull/13933
