### ISSUE TITLE
DetailsList not using Fluent UI checkbox

### ISSUE THREAD

**Issue by Jacqueline-ms** [microsoft/fluentui#13936]
### Environment Information

- **Package version(s)**: All versions
- **Browser and OS versions**: All browsers

### Describe the issue:

DetailsList component utilizing a custom checkbox instead of Fluent UI checkbox component. Azure theme requires the Fluent checkbox and this cannot be accomplished through theming alone. A good solution would be to use Fluent checkbox within the DetailsList component for accessibility and design alignment purposes. 

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/pen/?&editable=true=https%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

#### Actual behavior:
![image](https://user-images.githubusercontent.com/30805892/86812325-be7dc500-c033-11ea-8001-acdc4a2b333c.png)

#### Expected behavior:
Should be using these checkboxes
![image](https://user-images.githubusercontent.com/30805892/86812407-d7867600-c033-11ea-9aa9-61dac0bf5a98.png)

**Comment by paulgildea** [comment]
Thanks for the issue @Jacqueline-ms !

@dzearing - I'm assuming this won't be an easy fix - is there a work around to allow a "custom" icon be passed that is our default checkbox?
