### ISSUE TITLE
Figma plug-in link broken

### ISSUE THREAD

**Issue by middiu** [microsoft/fluentui#13943]
Hello, 

From FluentUI design webpage it seems that the link to "Figma plug-in" is broken, see "Download Figma plug-in":
https://www.microsoft.com/design/fluent/#/web

I believe this can be categorised as documentation issue.

this seems to be the md file related
https://github.com/microsoft/fluentui/blob/7a613256ef792c037702a47fa07713cecacbc755/apps/fabric-website/src/pages/Overviews/ResourcesPage/docs/default/ResourcesDesignResources.md

Cheers

**Comment by paulgildea** [comment]
@middiu Thanks for the issue!

I tried clicking the links you outlined but I'm able to see the following: 
![image](https://user-images.githubusercontent.com/33229964/86942279-cc961900-c0f9-11ea-9187-f776365cf03b.png)

Is this link working for you?
https://www.figma.com/community/plugin/794492287931420611/Fluent-Theme-Designer

**Comment by middiu** [comment]
Hi @paulgildea 

I'm getting a 404 error, see below.

I tried with different browsers but no luck... 
Also, if I search for "Fluent" in the Figma plugin page I don't find anything (see the second screenshot)

really strange...

![image](https://user-images.githubusercontent.com/428032/86974479-bfd8fa00-c1b9-11ea-95fb-6edd78577bd9.png)

![image](https://user-images.githubusercontent.com/428032/86974630-04649580-c1ba-11ea-9d13-e90d76c13759.png)

**Comment by middiu** [comment]
Also, if I try to browse all the available plugins sorted by name I don't see the Fluent plugin

https://www.figma.com/community/plugin/all?sort=name

![image](https://user-images.githubusercontent.com/428032/86980798-29f89b80-c1c8-11ea-9700-488e0de64dfd.png)

**Comment by paulgildea** [comment]
Interesting. I haven't seen that issue before.

@middiu  I'm following up - is this still an issue for you?

**Comment by middiu** [comment]
yes still the same problem.

**Comment by corganfuzz** [comment]
Same issue here. saw this 404 message a couple of weeks ago

**Comment by middiu** [comment]
yeah I also tried using a VPN to simulate different client locations, but still the same error

**Comment by middiu** [comment]
any update guys? 
Cheers
