### ISSUE TITLE
Dropdowns (incl menu button) may not be accessible within modal/panel on iOS/Mac due to use of aria-modal - spec unclear?

### ISSUE THREAD

**Issue by BrendanMcK** [microsoft/fluentui#13945]
- **Package version(s)**: office-ui-fabric-react@7.121.10
- **Browser and OS versions**:  Current safari on Mac, current safari on iOS, both with VoiceOver

### Describe the issue:

Popups (Dropdown control, Button with attached menu) don't work when in a Modal or Panel on iOS or Mac. Unclear from ARIA docs who's at fault here, so starting here to get input from Fluent team.

### Please provide a reproduction of the issue in a codepen:

Codepen: https://codepen.io/brendanmckeon/full/qBboNqy

Issue is that controls like Modal, Dialog and Panel all use `aria-modal="true"` on their frame element, which is expected. This essentially tells screenreaders to ignore anything outside the modal.

However, popup elements in Fluent are implemented as `div`s in a different part of the DOM, outside the modal. This appears to cause some screenreaders to ignore them, making it impossible to navigate to them, or track focus when navigating through them.

Some browser scenarios tried:
* Windows 10: Edge+Narrator: all works fine. (Edge classic, not Edge chromium tried here.)
* Mac OSX: Safari + VoiceOver: the items outside the modal track fine, but can't access content in the dropdowns inside the modal.
* iOS: Safari + VoiceOver: similar behavior to Mac; dropdowns within the modal can't be accessed.
* Android: Chrome + TalkBack: Tracking works fine - though there's other (unrelated) issues navigating to items in the dropdown

WAI docs are somewhat ambiguous re what should happen here: On the one hand, the doc for [aria-modal](https://www.w3.org/TR/wai-aria-1.1/#aria-modal) say:

>  If focus moves to an element outside the modal element, assistive technologies SHOULD NOT limit navigation to the modal element.

This suggests that VoiceOver is at fault here - at least for not tracking focus to these items. (Though it would still prevent navigating to those items w/o them first receiving focus.)

However, the doc then goes on to say:

> When a modal element is displayed, authors MUST ensure the interface can be controlled using only descendants of the modal element

Is the drop-down part of a Dropdown or menubutton considered to be something that 'controls' the UI? If so, it suggests that a best practice is to ensure that all relevant UI elements are within the aria-modal element.

While Windows w/ Narrator is not impacted in this specific instance, we'd still like to ensure that Fluent is using ARIA correctly here - if we can determine that, we may then want to follow up w/ Apple re VO's handling of aria-modal.

**Comment by paulgildea** [comment]
@BrendanMcK Thank you for the thorough investigation and write up. This is greatly appreciated and helpful.

I'm marking as needs discussion and I'm going to try and pull in some folks that have more in-depth knowledge ARIA

**Comment by xugao** [comment]
@BrendanMcK - Could you check if your issue is same as #11858? Seem to be the case to me. I believe this is a VoiceOver issue and looks like this will be fixed in iOS 14

**Comment by BrendanMcK** [comment]
@xugao  - not clear that this is the same issue. The issue in #11858 has to do with focus getting left outside the modal after the modal opens, perhaps due to a timing issue. In this case, focus is inside the modal just fine - it's not an issue with opening the modal. Instead the issue here is that items in the popup are (per Fabric implementation) existing outside of the Modal's DOM subtree, and iOS can't navigate to them.

(Also, I looked at the [bug that you opened](https://dev.azure.com/Office/APEX/_workitems/edit/3942374) for that issue - it doesn't seem to capture the reported issue correctly; the modal does open; the issue is that focus / navigation isn't handled correctly.)

**Comment by BrendanMcK** [comment]
Some additional thoughts on this: even if VO were to track keyboard focus outside of the modal, that might not be enough for this to be accessible. That approach assumes a specific type of user interaction: where the user is using a *keyboard*, and can drive focus using that (typically via arrow keys), with the screenreader passively reporting wherever the focus ends up.

This is not, however, not the only interaction model that's important for accessibility: non-keyboard users, particularly on mobile, rely on being able to navigate to elements before they can interact with them. Users who are sighted but using voice input for commanding (eg via Dragon or similar apps) also rely on their app being able to enumerate all candidate UI so that they can offer an appropriate selection list of targets to the user. If UI elements are outside of the modal, then per the rules of `aria-modal`, those elements would not be accessible to these users.

Could this be addressed by either having popups within a modal be contained within the modal's DOM tree? Or could `aria-owns` be used to get a semantically equivalent effect? (No idea what support for aria-owns is or whether it's reliable enough for something like this, though. Allowing modals to expose a popup host to their descendants via a context might be the most robust approach here.)

**Comment by paulgildea** [comment]
@smhigley as FYI.

**Comment by smhigley** [comment]
Thanks for the FYI! This is a known behavior with VoiceOver -- of all the screen readers, VO is by far the most picky about aria-modal use.

I can't currently think of a good way around it with the current portal implementation, but I'll play around with a few things :). I'm also going to make a quick PR to add a `role="document"` role to the child of the dialog/aria-modal to fix a separate (much easier) VO issue with arrow/swipe navigation within the dialog
