### ISSUE TITLE
Card component does not get focus when traversing using keyboard tab / shift + tab keys

### ISSUE THREAD

**Issue by nli8n** [microsoft/fluentui#13947]
Card component does not get focus when traversing using keyboard tab / shift + tab keys

**Comment by paulgildea** [comment]
Thanks for the feedback @nli8n can you please update this issue with our bug template and a repo to help us better make traction on it?

Thanks!

**Comment by nli8n** [comment]
Which Fluent UI component is causing the issue : Card 
Which package name and version the component is from :   "@uifabric/react-cards": "^0.109.1"
Specific, complete steps to reproduce the issue :
 1. add this dependency in package.json :   "@uifabric/react-cards": "^0.109.1" 
 2. import card component  :- import { Card } from '@uifabric/react-cards'
 3. render this card component.
 4. start the server & in the browser you should be able to see the card rendered
 5. on the browser screen press "TAB" keyboard key. 
 6. Notice that focus is not coming on the card component on hitting TAB key.
What behaviors and attributes are missing or incorrect : focus is not coming on the card component on hitting TAB key.
What you expected and what is actually happening : focus is not coming on the card component on hitting TAB key, while the expected behavior is to show the card component highlighted, like any other have like a "button"
Confirmation that the problem reproduces in isolation : yes it does reproduce in isolation

**Comment by khmakoto** [comment]
Hi @nli8n, I can confirm that I can repro this. I should have a fix relatively soon. Thanks for filing this issue!
