### ISSUE TITLE
ICSSDisplayRule should include MS prefixed values

### ISSUE THREAD

**Issue by brandonthomas** [microsoft/fluentui#13942]
#### Describe the feature that you would like added
Due to the increased type safety lately, we're getting some typing errors when using valid display rules that are browser specific. We should add these to the type def so that TS can infer the type of IStyle successfully without a cast.

#### What component or utility would this be added to

ICSSDisplayRule 

#### Have you discussed this feature with our team, and if so, who

dzearing

**Comment by paulgildea** [comment]
@brandonthomas - You willing to submit a PR? 😄
