### ISSUE TITLE
SpinButton styles spinButtonWrapperFocused prop doesn't accept class names

### ISSUE THREAD

**Issue by Ashwin-Nikam** [microsoft/fluentui#13955]
### Environment Information

- **Package version(s)**: 7.120.0
- **Browser and OS versions**: Windows Chrome

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/ashwin-7/pen/abdGpKY

#### Actual behavior:

When trying to apply custom styling to SpinButton on focus, the spinButtonWrapperFocused prop in styles doesn't accept class names. It only works when we pass actual styles object.

#### Expected behavior:

Passing classnames to spinButtonWrapperFocused should work as it does for spinButtonWrapper or input.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@khmakoto - is passing classNames through the IStyle interface supported? Looking at the `IStyle` I see it accepts a string, but I would be expecting a string literal for the style definition, not necessarily a className.

**Comment by ecraig12345** [comment]
This will be fixed in version 8, where SpinButton's `styles` prop has been updated to use the more standard pattern which also accepts class names.
