### ISSUE TITLE
How to access the latest CSS style sheets, Icons & Java scripts for HTML web development

### ISSUE THREAD

**Issue by Frankd4** [microsoft/fluentui#13951]
Hello Team,

How  can I download or use CDN for latest CSS style sheet for **icons**, framework & Java scripts for HTML web development.
Also, is it possible to use the Icons for Winform development, please guide me.

This link for Fabric core does not work when using icons :(
https://developer.microsoft.com/en-us/fluentui#/get-started/web#fabric-core

Thanks,
Frank

**Comment by paulgildea** [comment]
@Frankd4 If you are looking for guidance and usage for `Fabric Core` I recommend filing this issue over at the respective repository - https://github.com/OfficeDev/office-ui-fabric-core

I know it's a little confusing (we're working on it) but this library is specifically for React JS based components.

Let me know if you have any other questions.

Thanks!

**Comment by Frankd4** [comment]
Hi Paul,

I'm really confused, on one hand Microsoft says we want to improve and remove the confusion and introduce the Fluent UI ..., you now say X needs to to Y as this is not an issue. I just need your help to answer a simple question. 
How can I download or use CDN for latest CSS style sheet for icons for HTML web development.
