### ISSUE TITLE
Bug: ShimmeredDetailsList shimmer rows will remain if given defined key, even if enableShimmer prop is falsy

### ISSUE THREAD

**Issue by mryanlo** [microsoft/fluentui#13954]
I was playing with ShimmeredDetailsList and using it so that the shimmer rows will be present if i'm still loading data, and removed once data is loaded and we'll display the info in the grid. 

However, once the data loaded, I found that the shimmer rows didn't remove even if `enableShimmer` was false/undefined/falsy. 

I have discovered the issue was because I used ShimmeredDetailsList's `getKey` function prop gives the shimmer rows a defined key. I was trying to define `getKey` to be: 
```
getKey: item => `${item.id}-${item.name}`
``` 
to further differentiate my rows of items (any id can appear in multiple rows but have different display names). It turns out shimmer rows have `item` be undefined and so it'll return a key of `-`. The issue was fixed when I changed `getKey` to be
```
item => item && `${item.id}-${item.name}`
```
I would like to request the fluent UI react team to please look into this and if possible fix this issue. If not, i would like to understand why this issue happens and if it's intended behavior or not.

Here's a codepen of the issue. To see the error, click the toggle button to load the content and you'll see the shimmer rows above the items loaded. I have commented `// Here is the issue` to mark where this line of code is causing the issue
https://codepen.io/mryanlo/pen/xxZjRyg?editors=0010

Screenshots:
1. Default loading state when switch is in off position:
![image](https://user-images.githubusercontent.com/55516393/86965019-c9ac2000-c11b-11ea-9566-8dcd4ff2c844.png)

2. Toggle the switch to on position:
Expected:
![image](https://user-images.githubusercontent.com/55516393/86965292-290a3000-c11c-11ea-8e01-c01e30d922ba.png)
Actual (scrolled down a bit to get the error itself):
![image](https://user-images.githubusercontent.com/55516393/86965120-e7798500-c11b-11ea-8c55-a52d6e612c03.png)

Thank you!

**Comment by paulgildea** [comment]
Thanks for the repo @mryanlo it's super helpful.

@dzearing - I noticed that the sample on the main website doesn't use the `getkey` function prop. Is this expected behavior or the expected approach for giving rows unique identifiers? (@mryanlo correct me if I didn't capture your intent correctly).

**Comment by mryanlo** [comment]
@paulgildea i'm not sure if the main site not having `getKey` is related, but I encountered this issue whenever I used getKey for shimmered details list.
