### ISSUE TITLE
Docs need a Switching Themes page

### ISSUE THREAD

**Issue by mosesoak** [microsoft/fluentui#13977]
#### Describe the feature that you would like added

Below [Theme Slots](https://developer.microsoft.com/en-us/fluentui#/styles/web/colors/theme-slots) in the docs, a page should be created that explains that themes such as light and dark can be switched using `Customizations.applySettings()`.

At time of writing this, this key piece of information is _really hard to discover online_, and switching between light & dark themes is a highly desirable bit of functionality when vetting UI systems.

Example: Currently, typing the word 'dark' into the 'search styles' bar draws a blank. By way of contrast, typing 'dark' into Material UI's search bar yields a top result called ["Dark Mode"](https://material-ui.com/customization/palette/#dark-mode) and they also have a toggle at the top of the page that switches to dark mode. 

Thanks for considering this addition! I'd offer a PR if I were experienced enough with Fluent UI to write it myself. 😀

**Comment by paulgildea** [comment]
@mosesoak Thanks for the feedback.

I'll mark this as a feature request and add it to our backlog, but we're likely not going to get to it for a while as we're currently focused on larger coherence work items and enhancements to our performance, but I agree this is super great feature. 

Thanks for offering for a PR if you were more experienced we appreciate the intent!

**Comment by mosesoak** [comment]
It seems that another way to do theme switching is
```js
    <Customizer settings={{ theme: isLight ? theme : darkTheme }}>
      <Fabric applyTheme>
        <Component {...pageProps} />
      </Fabric>
    </Customizer>
```
and that there may be an upcoming `ThemeProvider` package, although that currently doesn't work SSR and looks pretty green still. Would be great to document all of this stuff somewhere clearly. Thanks again.

**Comment by mosesoak** [comment]
I'm using NextJS and have found a good way to switch themes using Context. I posted this at the issue relating to SSR warnings here https://github.com/microsoft/fluentui/issues/3692 and think it might be helpful for others so I'll repost it here:

```js
import { createTheme, Customizer, Fabric } from '@fluentui/react';
import { AppProps } from 'next/app';
import Head from 'next/head';
import React, { createContext, useState } from 'react';

const baseTheme = {
  defaultFontStyle: { fontFamily: "'Inter', Helvetica, sans-serif" },
  fonts: {
    medium: { fontSize: 30 },
  },
};

const lightTheme = createTheme({
  ...baseTheme,
  palette: {
  },
});
const darkTheme = createTheme({
  ...baseTheme,
  palette: {
    themePrimary: 'lightgray',
  },
});

export const IsDarkModeContext = createContext<
  [boolean, (value: boolean) => void]
>([false, () => {}]);

function MyApp({ Component, pageProps }: AppProps) {
  const [isDarkMode, setIsDarkMode] = useState(false);

  return (
    <>
      <Head>
        <title>My NextJS App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IsDarkModeContext.Provider value={[isDarkMode, setIsDarkMode]}>
        <Customizer settings={{ theme: isDarkMode ? darkTheme : lightTheme }}>
          <Fabric applyTheme>
            <Component {...pageProps} />
          </Fabric>
        </Customizer>
      </IsDarkModeContext.Provider>

      <style jsx global>
        {`
          html,
          body {
            padding: 0;
            margin: 0;
            font-family: 'Inter', Helvetica, sans-serif;
            font-style: normal;
          }

          * {
            box-sizing: border-box;
          }
        `}
      </style>
    </>
  );
}

export default MyApp;

```
