### ISSUE TITLE
ContextualMenu control hard-codes the role of internal List element

### ISSUE THREAD

**Issue by dotnetjunky** [microsoft/fluentui#13971]
#### Describe the feature that you would like added

Currently, the `ContextualMenu` control hard-codes the `role` attribute of the internal `List` as `menu`. In my usage, I want to set a different role, specifically `grid`. There's currently no way to achieve this.

I propose adding a `role` property to to the `IContextualMenuListProps` type so that the default List renderer knows what role it should set on the List element. If this property is undefined, we fall back to `menu`, which preserves the existing behavior.

I have submitted a [PR](https://github.com/microsoft/fluentui/pull/13908) for this.

#### What component or utility would this be added to

**ContextualMenu**

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

In the `ContextualMenu.base.tsx` file, the `_onRenderMenuList()` function renders a `<ul>` element as:

```ts
 <ul className={this._classNames.list} onKeyDown={this._onKeyDown} onKeyUp={this._onKeyUp} role="menu">
```

Notice that it hard codes the role as `menu`.

**Comment by paulgildea** [comment]
@joschect - Any objections to this change?
