### ISSUE TITLE
Textfield- Narrator is reading placeholder of textfield with multiline multiple times

### ISSUE THREAD

**Issue by sailakshmi1711558** [microsoft/fluentui#13983]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:
Created code pen here , where narrator is reading placeholder multiple times
https://codepen.io/sailakshmi1711558/pen/dyGKYVe
https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield

#### Actual behavior:
Narrator is reading  placeholder multiple times 

#### Expected behavior:
Narrator should read placeholder once only

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)
![image](https://user-images.githubusercontent.com/66770444/87139233-3c083600-c2bd-11ea-9875-e6885f9773cc.png)

**Comment by paulgildea** [comment]
@xugao - Please test in Edge Chromium and the latest to see if this repos. Thanks!

**Comment by xugao** [comment]
@sailakshmi1711558 - this is a bug with Narrator. Filed bug to Narrator team [here](https://microsoft.visualstudio.com/OS/_workitems/edit/27625771)

You can find a simple repro here with plain html: https://codepen.io/xugao/pen/ExPpGQE
