### ISSUE TITLE
DetailsRow requires a selection when selectionMode=SelectionMode.none

### ISSUE THREAD

**Issue by known-as-bmf** [microsoft/fluentui#13984]
When using a `GroupedList`, you can disable the selection of `GroupedListSection` by setting `selectionMode` to `SelectionMode.none`.

When doing this, you can also omit the `selection` prop (so you dont have to provide a "useless" `Selection` instance).

You can disable selection on a `DetailsRow` the same way (`selectionMode={SelectionMode.none}`) but the component still requires a valid `Selection` instance in the `selection` prop.

Here is why:

The event subscription is conditional in `GroupedListSection`
https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx#L152

but not in `DetailsRow`
https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx#L87

### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: any

### Please provide a reproduction of the bug in a codepen:

N/A

#### Actual behavior:

A console error when `DetailsRow` do not have a `selection` prop (`Uncaught TypeError: target is undefined`) even if `selectionMode={SelectionMode.none}`.

#### Expected behavior:

`selection` prop optional in `DetailsRow` if `selectionMode={SelectionMode.none}`.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: N/A

**Comment by xugao** [comment]
@known-as-bmf - I can't seem to repro the error [here](https://codepen.io/xugao/pen/oNbMJmV), which i don't have `selection` prop passed and SelectionMode is set to none. could you provide a pen for the repro?

**Comment by known-as-bmf** [comment]
Forked from the GroupedList first example:

https://codepen.io/known-as-bmf/pen/PoZyOVe?editors=1011

the error: 

![image](https://user-images.githubusercontent.com/11721166/87697754-cf94a780-c792-11ea-9fa5-c02d1157f409.png)
