### ISSUE TITLE
DefaultButton with primary:true styling for azure-theme

### ISSUE THREAD

**Issue by Jacqueline-ms** [microsoft/fluentui#13997]
#### Describe the feature that you would like added

Would like to add 'primary" to list of known properties, in type 'Partial < IButtonStyles > ' so azure-theme can update styles to components such as < DefaultButton primary / >. Current work around is just to use < PrimaryButton / >

This would address the following bug
![image](https://user-images.githubusercontent.com/30805892/87255298-6a614f00-c43e-11ea-8d83-ecf291fcdda1.png)

### Desired result
![image](https://user-images.githubusercontent.com/30805892/87255080-88c64b00-c43c-11ea-96f2-ba7c49c1dd6e.png)

#### What component or utility would this be added to

DefaultButton

#### Have you discussed this feature with our team, and if so, who

No, this is first instance & creating an issue for tracking purposes.

**Comment by paulgildea** [comment]
@Jacqueline-ms I'm assuming you'd like to contribute this change? 😄 

@dzearing / @khmakoto - any objections for adding this change to the `DefaultButton` component?

**Comment by khmakoto** [comment]
@paulgildea I'm guessing this would go into the Azure customizations? If that's the case and it's not polluting the component itself I'm fine with it.

**Comment by khmakoto** [comment]
@Jacqueline-ms I see that today this is what's being done in `AzureStyleSettings` inside of `AzureCustomizations` is

```ts
DefaultButton: {
  styles: DefaultButtonStyles(theme),
}
```

with `DefaultButtonStyles` being a `style` definition based on the `theme`.

I think what you could do at this level is target the specific `classname` in that styles definition, which is `.ms-Button--primary`.

Let me know if that helps.

**Comment by Jacqueline-ms** [comment]
Addressed [here](https://github.com/microsoft/fluentui/pull/14459/commits/b4449068683d165b575f1a267c26794583d8d760) - thank you for the suggestion! Closing issue.
