### ISSUE TITLE
Selected & hovered nav items overlap the scrollbar

### ISSUE THREAD

**Issue by mintxtinm** [microsoft/fluentui#13995]
### Environment Information

- **Package version(s)**: 7.10.8
- **Browser and OS versions**: Safari 13.1.1, macOS 10.15.1

### Reproduction:

https://codepen.io/mint1tinm/pen/WNryzJN

#### Actual behavior:

Selected & hovered nav items overlap macOS scrollbar

<img width="282" alt="2020-07-11 13 54 02" src="https://user-images.githubusercontent.com/12014428/87217986-7d621980-c381-11ea-9c5f-72fcc3427aea.png">
#### Expected behavior:

Selected & hovered nav items should have lower z-index (No issue on Chrome)
<img width="250" alt="2020-07-11 14 22 10" src="https://user-images.githubusercontent.com/12014428/87218067-1133e580-c382-11ea-8cae-84597580c21e.png">

### Priorities and help requested:

Are you willing to submit a PR to fix? No, haven't figured out yet.😤

Requested priority: Normal

**Comment by paulgildea** [comment]
@mintxtinm Thanks for the issue.

My hunch is that has to do with overflow styling, as I can't scroll the same menu in Chromium. 

Either this isn't the behavior we want for Nav when all items are visible.

**Comment by philipbel** [comment]
Issue is still present.

<img width="300" src="https://user-images.githubusercontent.com/145237/141704089-9e4424c6-d750-403b-b04a-efbfa12a49ad.png">

**Comment by BboyAkers** [comment]
I can try to take a look at this! 🙂
