### ISSUE TITLE
"Go to today" overlapped when there are 6 weeks visible.

### ISSUE THREAD

**Issue by stevenpicard** [microsoft/fluentui#13991]
#### Actual behavior:

When the "Go to today" text displayed it is overlapped when there are 6 weeks visible. Reproduction is easy.  Go to your DatePicker site([https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker]) and in the first usage example click "Export to CodePen". You need to test it in CodePen because it appears your example is using version 6 and the problem occurs in version 7 (which is what the CodePen uses). This is because the "Go to today" was in the months display panel in version 6 but is now (in version 7) in the weeks display panel.

#### Expected behavior:

The "Go to today" text is always visible without other text overlapping it.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

I have temporarily turned off the display of this functionality but would like it working when we move to production with this next month (CRM web site.)

**Comment by paulgildea** [comment]
@stevenpicard Thanks for the issue.

Indeed I was able to repo this issue: 
![image](https://user-images.githubusercontent.com/33229964/87330009-c682ac80-c4ec-11ea-8830-c42004339eee.png)

This is against the latest.

**Comment by hrc7505** [comment]
Facing the same issue,

![image](https://user-images.githubusercontent.com/17545364/105283449-80fb1680-5bd6-11eb-91c5-f9d844d9a2cc.png)

**Comment by vputsenko** [comment]
Still repro..

**Comment by neil-ji** [comment]
Same issue on small-scrren devices.

![Bug](https://user-images.githubusercontent.com/45644652/111131427-32a13d00-85b3-11eb-89d3-d4b80f83c6b3.png)
