### ISSUE TITLE
Does not work with a TS & HTML

### ISSUE THREAD

**Issue by ProCode-Software** [microsoft/fluentui#13999]
I'm using Fabric Core (HTML and TS files) for a nav and VSCode finds 27 errors. Also, it does not work.

**Comment by paulgildea** [comment]
@ProCode-Software Thanks for the issue. This repository is focused on the React implementation while Fabric Core is a CSS framework.

If you have any issues with Fabric Core specifically you can file them on their respective repo: https://github.com/OfficeDev/office-ui-fabric-core/issues

Hope that helps.
