### ISSUE TITLE
Controls available for Fabric Core

### ISSUE THREAD

**Issue by ProCode-Software** [microsoft/fluentui#14000]
#### Fluent UI Controls

I'm not using React and I'm using Fabric Core and the controls aren't avalible.

**Comment by paulgildea** [comment]
@ProCode-Software Thanks for the issue. This repository is focused on the React implementation while Fabric Core is a CSS framework.

If you have any feature requests for Fabric Core specifically you can file them on their respective repo: https://github.com/OfficeDev/office-ui-fabric-core/issues

Hope that helps.
