### ISSUE TITLE
[Linechart, VerticalBarChart, VerticalStackedBarChart, GroupedVerticalBarChart] Fit parent container when windows size changes

### ISSUE THREAD

**Issue by luckyrass** [microsoft/fluentui#14002]
#### We hope the following components could fit parent container when windows size changes

- Linechart
- VerticalBarChart
- VerticalStackedBarChart
- GroupedVerticalBarChart

#### What component or utility would this be added to
Fit parent container when windows size changes for the following components
- Linechart
- VerticalBarChart
- VerticalStackedBarChart
- GroupedVerticalBarChart

A workaround is: When parent div values changed, send those values to the chart as prop values, Based on those values graph will be updated. But we hope to integrate this functionality into component instead of adding extra code to update the chart properties.

#### Have you discussed this feature with our team, and if so, who
No

#### Additional context/screenshots

Actual behavior

When we change the screen size, the linechart, VerticalBarChart, VerticalStackedBarChart, GroupedVerticalBarChart will be cut off.
![image](https://user-images.githubusercontent.com/12230173/87277044-16289e80-c514-11ea-9b71-417fcc602836.png)

Expected behavior
![image](https://user-images.githubusercontent.com/12230173/87276939-eb3e4a80-c513-11ea-8983-aaea9f6999f4.png)

**Comment by Raghurk** [comment]
Will take a look

**Comment by Raghurk** [comment]
The current behavior is expected, I don't want chart to be too smart in identifying various times when you want to fit the parent. As the consumer you are aware of when you want to change and you have to send the new size down to chart.
This behavior is by design
