### ISSUE TITLE
Linechart: vertical line doesn't show up when the mouse over the datapoint 

### ISSUE THREAD

**Issue by luckyrass** [microsoft/fluentui#14001]
### Environment Information

- **Package version(s)**: (@uifabric/charting 2.5.0)
- **Browser and OS versions**: (Microsoft Edge 42.17134.1098.0)

### Please provide a reproduction of the bug in a codepen:

Vertical line doesn't show up when the mouse over the datapoint in linechart

#### Actual behavior:

![image](https://user-images.githubusercontent.com/12230173/87274739-0d819980-c50f-11ea-8f5f-420c7248beb4.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/12230173/87274792-2c802b80-c50f-11ea-8d2b-86739446c0e4.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Normal)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@Raghurk - Something for you to look at 😄 .

**Comment by Raghurk** [comment]
Thanks! Looking at these
