### ISSUE TITLE
ContextualMenu submenu and Button submenu hover state flicker on open

### ISSUE THREAD

**Issue by CampbellOwen** [microsoft/fluentui#14017]
### Environment Information

- **Package version(s)**: 7.122.0
- **Browser and OS versions**: Chromium Edge: Version 83.0.478.61 (Official build) (64-bit)

### Please provide a reproduction of the bug in a codepen:
Repros on https://fabricweb.z5.web.core.windows.net/oufr/7.122.0/#/examples/contextualmenu `ContextualMenu with checkable menu items and toggleable split button` example

I've also recorded a video showing this: https://microsoft-my.sharepoint-df.com/:v:/p/owcampbe/EQrBDkNaPDJBr8yHmYOe__cBHV7u54d4NOO9IbbV-1m5LQ?e=HeXj5Z

#### Actual behavior:

Hovering over the right edge of the submenu button causes the newly opened submenu to receive hover states for a short time before returning to the submenu button.

This also repros using an `IconButton` that has a submenu

#### Expected behavior:

Submenu opens with no hover states if the mouse isn't over it.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by paulgildea** [comment]
@CampbellOwen Thanks for the video repo! That was super helpful. I am able to repo the issue with the latest.

We would appreciate a PR if you are willing to put one together.

Let's us know if you'd like to put one together and I'll assign this issue to you. 

@joschect - as FYI for any sign off for `ContextMenu`

**Comment by CampbellOwen** [comment]
Hey @paulgildea , thanks for confirming. I'd definitely be willing to work on a PR, but I have no idea what's causing this issue. If I could get help with the investigation, I don't mind being the one to actually implement the fix.

**Comment by paulgildea** [comment]
I'll mark this as needs investigate to see if we can get some traction on a potential fix.

**Comment by xugao** [comment]
@CampbellOwen - I believe this is by-design and the code which adds the delay is [here](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx#L23)

I think this is so that the hover effect shows up the same time as the menu.

**Comment by dotnetjunky** [comment]
@xugao I'm not sure I understand the design here. It shows the hover state and immediately resets back to rest state. Are you saying we intentionally shows the hover effect on the first item when the contextual menu opens?

**Comment by CampbellOwen** [comment]
On top of what @dotnetjunky said, the issue isn't the delay in hover states, it's the fact that they're applied and then unapplied milliseconds later when my cursor never went over the submenu. If you move your mouse in a perfectly straight vertical line down the right side of the button, you'll see hover styles in the submenu be applied for a split second. 

Doing some investigation, the submenu is receiving `mouseOver` and `mouseOut` events in quick succession. I'm not sure what's triggering this as my mouse never actually touches the submenu. Is this a browser level issue?

**Comment by xugao** [comment]
@CampbellOwen, @dotnetjunky - sorry about that, i misunderstand the bug here. Now i get the issue. i don't have a good idea what's causing this. If you can spend some more time digging, I would suggest you to dig further on why the event fired unexpectedly. My gut feeling towards `createPortal` in `Layer` and could very much be a React bug.

**Comment by CampbellOwen** [comment]
I looked at it a bit more, I've at least verified that it really is erroneously calling `mouseOver`. Here's a log showing two consecutive `mouseOver` events: The first being the `IconButton` hosting the context menu, and the second being the `ContextualMenuItem` that should not be receiving `mouseOver`:
![image](https://user-images.githubusercontent.com/7470459/87608491-ebc21700-c6b4-11ea-8e07-6290a3d3e36b.png)
Notice the `x` coordinate does not change between the two events even though the submenu item does not overlap the `IconButton` at all.

I also tried giving the `Callout` the `doNotLayer` prop, but this did not change the behaviour at all. I'm not sure if this implies anything about your theory about `createPortal` in `Layer`. 

At this point I don't think I'm familiar enough with neither `createPortal` nor `Layer` or `ContextualMenu` to be able to find the root cause without more effort than it's worth. Is there anyone more familiar with these areas that can take a look?

**Comment by xugao** [comment]
@CampbellOwen - i can help dig a bit more but given this is a low impact bug please expect some delays. 

Tagging @joschect here in case he knows anything.

**Comment by CampbellOwen** [comment]
Hi, has there been any update or progress on this issue?

**Comment by dotnetjunky** [comment]
Ping on this issue. This is quite an annoying behavior bug that I think it's more that just a Fit and Finish bug.
