### ISSUE TITLE
Resource leak in FocusZone

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#14025]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.50.0

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/v050-focus-zone-resource-leak-31gpt

#### Repro steps
1. Have a component with two sibling `FocusZone` components:
```jsx
<FocusZone>first</FocusZone>
<FocusZone>second</FocusZone>
```
2. Mount and unmount the component 5 times.
3. Check keydown event listeners on html node.

#### Actual behavior:

After the last unmount, there are 5 keydown event listeners in FocusZone:
![image](https://user-images.githubusercontent.com/9615899/87433524-af75b480-c5e9-11ea-8378-49dcc8e7e971.png)

#### Expected behavior:

After the last unmount, there should be NO event listeners in FocusZone.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) **High**

Products/sites affected: (if applicable)

**Comment by miroslavstastny** [comment]
`FocusZone` uses ref counting for the keydown event listener to be added only once in `componentDidMount`:
https://github.com/microsoft/fluentui/blob/ac395c5e30b21081b49166ccfc02177f777df7c6/packages/fluentui/react-bindings/src/FocusZone/FocusZone.tsx#L165-L167

And the same logic for removing the event listener in `componentWillUnmount`:
https://github.com/microsoft/fluentui/blob/ac395c5e30b21081b49166ccfc02177f777df7c6/packages/fluentui/react-bindings/src/FocusZone/FocusZone.tsx#L218-L220

If you have two siblings in a React tree, they are unmounted in the same order they were added (not in a reverse order):
![image](https://user-images.githubusercontent.com/9615899/87434037-4a6e8e80-c5ea-11ea-900b-b81665162a3e.png)

That means that in the `FocusZone` case, having two sibling `FocusZone`s, the `componentWillUnmount` of a different class instance tries to remove the event listener.
 
As the `_onKeyDownCapture` is an **arrow function, it is not referentially equal across the class instances**, the function passed in `removeEventListener` does not equal the one passed in `addEventListener` and `removeEventListener` does not remove anything:
![image](https://user-images.githubusercontent.com/9615899/87434260-86a1ef00-c5ea-11ea-8da7-0894b414e902.png)

**Comment by miroslavstastny** [comment]
@dzearing There is the same problem in `@fluentui/react-focus@7.12.19` -> Fabric is also affected.

**Comment by dzearing** [comment]
@miroslavstastny Thank you! Makes sense.

@khmakoto It seems we have the exact same code in `react-focus` package, and it needs to be fixed on line 493 in there. Is there a plan to dedupe? I thought we were going to remove the duplicate copies and use the converged FocusZone.

**Comment by khmakoto** [comment]
Updating the thread here. @miroslavstastny has included the `react-focus` version in his PR fix.

@dzearing and I are talking offline about what happened with dedupe's plans.
