### ISSUE TITLE
Menu should be closed, when popup dialog appears 

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#14022]
Issue reported by user testing.

### Environment Information
Win10
Chrome Version 83.0.4103.116

### Describe the issue:
 I activate More button to open the menu. Then I activate ‘Open Popup’ item to open the dialog. When the dialog opens the menu should be closed. I don’t expect that the menu remains opened. When I close the dialog I expect that the focus returns to More button on the toolbar and not in the menu. This is a standard behavior in native Windows applications. 

###  Reproduction of the issue 
1. open  https://fluentsite.z22.web.core.windows.net/components/toolbar/definition
2. navigate to the "Popup with an action, in Menu" example
3.  open menu
4. from menu open popup

#### Actual behavior:
menu is not closed

#### Expected behavior:
menu should be closed when popup appear and focus is in popup 
dismissing the dialog/popup, focus returns to the parent item

**Comment by paulgildea** [comment]
@jurokapsiar - Sending this one over to you 👍 .
