### ISSUE TITLE
date-time package's Inline Calendar variant using Chromium Edge + Narrator:  when switching to from Dec 2020 to Jan 20201, the accessible name of the "2021" button is read out by screen reader

### ISSUE THREAD

**Issue by meghanking** [microsoft/fluentui#14036]
### Environment Information

http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/14008/merge/date-time/dist/index.html#/examples/calendar

### Describe the issue:

When using the "Next month" button to switch to a month in a different year (say Dec 2020 to Jan 2021), the accessible name of the "20201 switch to select year button" is announced by screen reader out of context

This information read out of context as a live region in this scenario, could lead a screen reader user to think that selecting will change the right hand pane to select years instead of months, but however they are still focused on the "Next month" button

### Please provide a reproduction of the issue in a codepen:

http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/14008/merge/date-time/dist/index.html#/examples/calendar

#### Actual behavior:

When "Next month" button switches from Dec 2020 to Jan 2021, the screen reader reads out the following information in order
- next month February 20201 button
- January 2021
- 2021 select to change the year

#### Expected behavior:

When "Next month" button switches from Dec 2020 to Jan 2021, the screen reader reads out the following information
- next month February 20201 button
- January 2021

**Comment by paulgildea** [comment]
@lorejoh12 FYI.

**Comment by xugao** [comment]
@lorejoh12 - I'm not sure why the year button needs to be set with aria-live. Seems to be that setting that on "monthAndYear" button alone is sufficient. Could you confirm and make a fix for this?
