### ISSUE TITLE
Card vs AdaptiveCards?

### ISSUE THREAD

**Issue by dawwa** [microsoft/fluentui#14035]
Hi, we're wondering the roadmap of [Card](https://developer.microsoft.com/en-us/fluentui#/controls/web/card) and relationship with [AdaptiveCards](https://github.com/microsoft/AdaptiveCards), are we going to align the design and experience since they both seem the major UX efforts going on. Would someone please help clarify?

**Comment by paulgildea** [comment]
@dawwa Thanks for the question. 

Fluent UI React and Adaptive Cards are trying to meet different needs for developers. Adaptive Cards is full solution that provides Card experiences leveraging a tech agnostic schema that allows you to define a card semantically and then it can render appropriately on the various platforms that is supports. However, that schema is limited in what UI designs it can achieve, but that limitation is there to ensure predictability and consistency of the Card UI across the various platforms. To me Adaptive Cards is full end to end solution (front end and back end) that allows developers to build Card-like experiences across a number of different platforms.

Our current Card component (which is experimental right now) is purely UI element that can allow a front end web developer using React to build a Card experience. It's just the UI layer and it's up to developer to determine things like what the design of the Card is, what data goes in, how that data goes in, etc. 

In terms of roadmap of design - I think there are opportunities to provide more visual alignment but there aren't any specific plans at this time. Both of our teams are in contact with each other however.

Hope that helps with the relationship between the two technologies and the near term roadmap.
