### ISSUE TITLE
Callback when dialog disappears

### ISSUE THREAD

**Issue by aykutkilic** [microsoft/fluentui#14047]
#### Describe the feature that you would like added

I need an event like onDialogDisappeared which is trigger when the dialog is off the view and faded away. I've put a form inside a dialog and reset the form when user confirms or cancels. If I reset the form immediately after hidden is set to true then the user can see the reset of the form which look imo ugly. I put a fixed delay time to ensure it fades away but it would be better to have a legit callback.

#### What component or utility would this be added to

Dialog or anything that visually fades away.

#### Have you discussed this feature with our team, and if so, who

No.

**Comment by xugao** [comment]
@aykutkilic - can you use `onDismiss` prop?

**Comment by aykutkilic** [comment]
Hello, `onDismissed={()=>reset()}` does what I want. Thanks!
