### ISSUE TITLE
@uifabric/react-hooks: useMergedRefs() behaves differently than native refs

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#14041]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/bold-montalcini-gwzgo

1. Open CSB
2. Click a rerender button

An implementation of `useForkRef()` handles referential equality so it behaves like native refs.

#### Actual behavior:

Only `Button BUTTON` was logged.

#### Expected behavior:

`Button BUTTON` and `Button DIV` & `MergedButton div DIV` should be logged.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Requested priority: Normal
Products/sites affected: (if applicable)

**Comment by xugao** [comment]
@layershifter - this is indeed a bug. i can get a fix going

**Comment by MLoughry** [comment]
The purpose of a ref callback is to give you the reference to a rendered React node. If the ref callback doesn't change and the underlying node doesn't mount/unmount, React doesn't invoke the callback. 

Ref callbacks are not intended as notifications for rerenders.

**Comment by layershifter** [comment]
> If the ref callback doesn't change and the underlying node doesn't mount/unmount, React doesn't invoke the callback.

It's fully correct, but closures like `el => console.log("MergedButton", tag, el?.tagName)` will always return a new reference on each render.
