### ISSUE TITLE
Screen Reader is not working properly with the up and down button in the edge browser.

### ISSUE THREAD

**Issue by muagar** [microsoft/fluentui#14046]
I have tried the https://developer.microsoft.com/en-us/fluentui page both in chrome and edge browser.
In the Chrome browser in screen reader mode up and down button works properly and iterate through all the buttons and links.
The same thing I am trying in the edge browser its not working properly with the up and down buttons.

**Comment by xugao** [comment]
@muagar - are you using Narrator (supported screen reader) on Edge ?
I can't repro this with Narrator + Edge Chromium
