### ISSUE TITLE
In scan mode, screen reader focus is moving out of panel in backward navigation

### ISSUE THREAD

**Issue by SyedRehmanRazvi** [microsoft/fluentui#14057]
User Experience: 
Users who rely on Screen reader for navigating between elements are getting affected as screen reader focus is moving out of "Panel" in backward navigation. User will be confused if the screen reader focus moves to background elements and announcing inappropriate information.

Test Environment:
OS: Win 10 
OS Version: 1909 (OS Build 18363.778) 
Browser: Edge - Dev (Version 84.0.488.1)
URL: https://fabricweb.z5.web.core.windows.net/oufr/7.78.2/#/examples/panel
Screen reader : Narrator

Repro Steps:
Step 1: Turn on Narrator and open above URL using Edge Browser.
Step 2: Navigate to "Open Panel" button and activate using keyboard
Step 3: Now "Sample Panel" dialog will be opened
Step 4: In scan mode, verify screen reader focus is moving out of panel in backward navigation

Actual:
In scan mode, screen reader focus is moving out of "Panel" in backward navigation

Expected:
In scan mode, screen reader focus should not move out of "Panel" in backward navigation

Tracking of Focus and Selection Attributes
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7BB24201D1-2276-4471-8183-E1E5353031AD%7D&file=MAS%204.2.10%20%E2%80%93%20Tracking%20of%20Focus%20and%20Selection%20Attributes.docx&action=default&mobileredirect=true
![image](https://user-images.githubusercontent.com/53210862/87658307-a4ea2500-c779-11ea-9db9-aa44dd8e6a8d.png)

**Comment by xugao** [comment]
@SyedRehmanRazvi - this is a known issue and it's a suitable for screen reader to address this. here is [the reason](https://github.com/microsoft/fluentui/issues/11241#issuecomment-558393305).
