### ISSUE TITLE
VoiceOver narrates "1" when menuitemcheckbox is checked, used in menu in toolbar

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#14064]
### Environment Information
VoiceOver 
Chrome 83.04103.116
macOS Catalina 10.15.5

Repro steps:
1. open the page: https://fluentsite.z22.web.core.windows.net/components/toolbar/definition
2. navigate into the toolbar example: Toolbar can contain a radio group in a menu
3. navigate to the menu which has already any item checked 

#### Actual behavior:
VoiceOver narrate:
1, [name of the item], ticked, menu item

<img width="720" alt="Screenshot 2020-07-16 at 3 08 21 PM" src="https://user-images.githubusercontent.com/22620150/87675571-d3ff9700-c777-11ea-8473-cb4c547991d0.png">

#### Expected behavior:
"1" should not be narrated

**Comment by carmacleod** [comment]
In case it's helpful, I have the same problem. Happens in both Safari and Chrome, so probably a VoiceOver bug.
Also happens for menuitemradio.

I reported it to Apple using [Feedback Assistant](https://developer.apple.com/bug-reporting/) in macOS, and I opened an [Open Radar](http://www.openradar.me/radar?id=4960010555621376) as well.
Would be great if you could report to Apple, too, and if possible, link in the Open Radar. Feel free to add comments there.

**Comment by YuanboXue-Amber** [comment]
> In case it's helpful, I have the same problem. Happens in both Safari and Chrome, so probably a VoiceOver bug.
> Also happens for menuitemradio.
> 
> I reported it to Apple using [Feedback Assistant](https://developer.apple.com/bug-reporting/) in macOS, and I opened an [Open Radar](http://www.openradar.me/radar?id=4960010555621376) as well.
> Would be great if you could report to Apple, too, and if possible, link in the Open Radar. Feel free to add comments there.

I think too this is a VoiceOver bug. I tried on this example
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-2/menubar-2.html
And also got '1' narrated.
<img width="914" alt="Screenshot 2020-09-22 at 11 38 10" src="https://user-images.githubusercontent.com/28751745/93866636-3325de80-fcc8-11ea-91ce-e6ca9b102d1f.png">
