### ISSUE TITLE
Icons re-registering multiple times, causing them to be corrupted

### ISSUE THREAD

**Issue by ajain17** [microsoft/fluentui#14068]
We are using Fluent UI in our application and only call initializeIcons at the root of our application

`
import { initializeIcons } from "@uifabric/icons"; 
initializeIcons();
`

We use some other components like LPC (Persona card) that also have calls to initialize Icons. In my understanding this is causing them to be registered multiple times. We randomly see our icons start to look like this:
![image](https://user-images.githubusercontent.com/5581487/87707726-71e26a00-c756-11ea-8646-8fe9f4761f93.png)

Where as they actually look like these:
![image](https://user-images.githubusercontent.com/5581487/87707847-9e968180-c756-11ea-88d4-0936d5a70b30.png)

The console shows these warnings:
![image](https://user-images.githubusercontent.com/5581487/87707761-832b7680-c756-11ea-8f85-cb50052b172c.png)

Is there a way to ensure that they don't get registered again if they have already been registered once? Or are you aware of any other issue that might be causing this behavior? Thanks in advance.

**Comment by ajain17** [comment]
This happens very intermittently. We use LPC in our list views and when we hover over LPC persona icons I see a lot of such warnings in console
![image](https://user-images.githubusercontent.com/5581487/87820134-5e9cd080-c822-11ea-94cd-45e3e143b2b7.png)

After this, it sometimes changes all icons to random characters and gets resolved on refresh. I do not have a consistent repro but we observe this behavior every couple of days.

**Comment by xugao** [comment]
@ajain17 - couple things:
1) I think both your app and LPC calls `initializeIcon`. That's what's causing the warning. You should reach out to LPC to see how to handle this. They might have a way to configure not calling it again in LPC code
2) I am not sure if this is what corrupted the icon. But you should try #1 first to see if that avoids the issue.

We can only warn about this but there is not much we can do to help you fix.
