### ISSUE TITLE
@fluentui/react-button: MW scenario does not work

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#14065]
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.7.2
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/amazing-gauss-y1uql?file=/src/App.js

#### Actual behavior:

No styles 😭 

#### Expected behavior:

Styles are present 🎉 

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal
Products/sites affected: (if applicable)

**Comment by layershifter** [comment]
Still broken for latest betas 😭
https://codesandbox.io/s/goofy-fire-rfvpy?file=/src/App.js

I also tried to specify `window` for `WindowProvider`, but it has no effect:

```tsx
<WindowProvider window={document.defaultView}>
  <StylesheetProvider target={document}>
    <h1>Hello </h1>
    <Button>A button</Button>
  </StylesheetProvider>
</WindowProvider>
```

**Comment by khmakoto** [comment]
Closing since this is no longer relevant.
