### ISSUE TITLE
paddlePosition and navigationPoistion doesn't on Carousel 

### ISSUE THREAD

**Issue by assuncaocharles** [microsoft/fluentui#14079]
### Environment Information

- **Package version(s)**: @fluentui/react-northstart@0.50

### Please provide a reproduction of the bug in a codesandbox: 

https://codesandbox.io/s/y1sen?module=/example.js&file=/example.js

#### Actual behavior:

`paddlePosition` and `navigationPosition` should change the paddle and the navigation position in the `Carousel`

#### Expected behavior:

Nothing happens

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by martysupple** [comment]
I apologize if this is not the right place to ask this question, but is there a workaround to this? I cannot get the paddles to position properly for just basic <Text /> content. Docs do not seem to help.

**Comment by rekpatel** [comment]
@martysupple, Can you please share more details?  Are the paddles not centered, not overlaying content, does the content height vary, etc.?

**Comment by martysupple** [comment]
Just using the example given above: https://codesandbox.io/s/y1sen?module=/example.js&file=/example.js
I get the same behavior where the paddles have a top positions of -166rem so they are way above the carousel. I had add:
                    paddleNext={{ styles: { top: "-4.75rem;" }}}
                    paddlePrevious={{ styles: { top: "-4.75rem;" }}}
To my Carousel jsx to get it to render more centered with the carousel items.
