### ISSUE TITLE
Support for lazy-loading attribute in Image props

### ISSUE THREAD

**Issue by cronin101** [microsoft/fluentui#14086]
This would have the huge benefit of cutting down network requests for off-screen content.

#### Describe the feature that you would like added

The ability to access [the lazy-loading attribute](https://web.dev/native-lazy-loading/) when using an `Image` element.

#### What component or utility would this be added to

`Image`

**Comment by paulgildea** [comment]
Thanks for the feedback @cronin101 !

Is this a feature addition that you would be interested in contributing to the `Image` component?
