### ISSUE TITLE
Menus of the dropdown misplaced from their position after zoom property sets to 80%.

### ISSUE THREAD

**Issue by farooqiazam** [microsoft/fluentui#14081]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "6.112.0"
- **Browser and OS versions**: Version 84.0.4147.89 (Official Build) (64-bit) and Windows 10 pro version:1803

#### Actual behavior:

For some small screen sizes, we have to make a zoom size reduced to 80 % using CSS. After zooming, all components are working fine except dropdowns. Menus of dropdowns got displaced from their positions. I have applied this CSS property on Fabric UI official website and all menus of dropdowns are got displaced.  I have attached some screenshots for this. 

##### Steps to reproduce:
you can simply add CSS property 'zoom: 80%' to the body of the HTML of the fabric UI website in control sections. 

![Screenshot (22)](https://user-images.githubusercontent.com/28789260/87766108-184f6d80-c832-11ea-9bab-c3d00acfd45d.png)
![Screenshot (23)](https://user-images.githubusercontent.com/28789260/87766114-1ab1c780-c832-11ea-88e5-42d65fa898a7.png)
![Screenshot (24)](https://user-images.githubusercontent.com/28789260/87766125-1f767b80-c832-11ea-89c7-32d54ba11a33.png)

#### Expected behavior:

Dropdowns should work exactly the same as they are working on 100% zooming. 

### Priorities and help requested:

Requested priority: (Blocking)

**Comment by xugao** [comment]
@farooqiazam - I can't seem to repro in Edge and using our document site:
![image](https://user-images.githubusercontent.com/1207059/87813913-a79b5780-c817-11ea-9fe5-1a11752cc5d7.png)

**Comment by farooqiazam** [comment]
@xugao Thanks for the quick response.
Browser zoom facility and CSS zoom property do not work exactly the same. The issue arises when we add CSS property 'zoom : 80%' to the body of the page. 

without this zoom property, dropdowns are working fine.
![Screenshot (28)](https://user-images.githubusercontent.com/28789260/87877542-66ae6900-c9f8-11ea-9158-4143e22670ab.png)

but with this property menus got displaced.
![Screenshot (29)](https://user-images.githubusercontent.com/28789260/87877552-77f77580-c9f8-11ea-8ea3-72c7119614d1.png)

Also here is the screenshot for The Edge browser.
![Screenshot (30)](https://user-images.githubusercontent.com/28789260/87877697-30251e00-c9f9-11ea-9493-58733a6aba23.png)
 

Note: I was using this property in a media query for the smaller screens, All other components are working absolutely fine, but Dropdowns are causing issues.

**Comment by paulgildea** [comment]
@xugao - This might have to do with the position logic not taking into account the CSS property sizing. 

@joschect Thoughts on this one? I don't know if we explicitly support the `zoom` CSS property in our position logic?

**Comment by xugao** [comment]
@farooqiazam - `zoom` css is [non-standard](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom), therefore we don't support

**Comment by farooqiazam** [comment]
@xugao I can understand your concern but this problem arises with other CSS properties as well. For example 'transform: scale(0.8)'.
If I try to reduce my screen size to 80% using transform property then menus got displaced again. 
![Screenshot (31)](https://user-images.githubusercontent.com/28789260/88023548-aab18300-cb4a-11ea-9ffb-2549b39ed78e.png)

**Comment by xugao** [comment]
@farooqiazam - got it. agree this is a bug.

**Comment by farooqiazam** [comment]
@xugao Acknowledged! I hope you guys will figure out the solution soon, As dropdown is causing issues in all of our applications.
Thanks

**Comment by farooqiazam** [comment]
@xugao @paulgildea  Hi! Hopefully, you guys are doing great. Do we have any update regarding this bug?

**Comment by paulgildea** [comment]
I've added the component owner. But I don't have any timelines to share at this time. Thanks!

**Comment by farooqiazam** [comment]
@paulgildea thanks for the update.

**Comment by farooqiazam** [comment]
@paulgildea @joschect Hi guys! Hopefully, you guys are doing fine. Do we have any progress regarding this issue

**Comment by farooqiazam** [comment]
@paulgildea @joschect Hello guys, Do we have an update on it?

**Comment by farooqiazam** [comment]
Can anyone please share, if there is any progress?? @paulgildea @joschect
