### ISSUE TITLE
react-northstar: changing items in a selectable <List> component produces console error.

### ISSUE THREAD

**Issue by astegmaier** [microsoft/fluentui#14091]
### Environment Information

- **Package version**: @fluentui/react-northstar 0.5.0
- **Browser and OS versions**: Edge 83.0.478.64 / OS X 10.15.5

### Please provide a reproduction of the bug in a codepen:

Create an app with a `List` component with the `selectable` property set to "true". For example:

```tsx
import { List } from "@fluentui/react-northstar";

const items = [
  {
    key: "irving",
    header: "Irving Kuhic",
    content: "Program the sensor to the SAS alarm through the haptic SQL card!"
  },
  {
    key: "dante",
    header: "Dante Schneider",
    content: "The GB pixel is down, navigate the virtual interface!"
  }
];

const ListExampleSelectable = () => (
  <List selectable defaultSelectedIndex={0} items={items} />
);
```
To repro, see:
 - [this codesandbox demo](https://codesandbox.io/s/gracious-lamport-fmj2d?file=/example.js)
 - [this github repo](https://github.com/astegmaier/fluentui-list-bug)

#### Actual behavior:

When you select a different item in the list, you see this error in the console:

```
index.js:27 Warning: Cannot update a component (`ListItem`) while rendering a different component (`ContextSelector.Provider`). To locate the bad setState() call inside `ContextSelector.Provider`, follow the stack trace as described in https://fb.me/setstate-in-render
    in ContextSelector.Provider (created by List)
    in ul (created by FocusZone)
    in FocusZone (created by List)
    in List (at example.js:22)
    in ListExampleSelectable (at index.js:13)
    in div (created by SandboxApp)
    in KnobProvider (created by SandboxApp)
    in div (created by Provider)
    in ThemeProvider (created by Provider)
    in RendererProvider (created by Provider)
    in Provider (created by Provider)
    in Provider (created by SandboxApp)
    in SandboxApp (at index.js:12)
```

#### Expected behavior:

No error

### Priorities and help requested:

Are you willing to submit a PR to fix? No - happy to help debug, but I don't have the time / background knowledge to do a full PR

Requested priority: Normal

**Comment by layershifter** [comment]
Thanks for reporting, but it's a duplicate #13684. There is no easy way to fix this warning, however components will still work properly.
