### ISSUE TITLE
@fluentui/react-next: Popup binds an event handler to a wrong window

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#14108]
### Environment Information

- **Package version(s)**: @fluentui/react-next@8.0.0-alpha.63
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/affectionate-water-b2wis

1. Open CSB
2. Focus on the main window, not inside the iframe
3. Press `Escape`, it should **not** log `onDismiss`

The issue in this line:
https://github.com/microsoft/fluentui/blob/561bb587ebba766eb0cec41533aaf9ebd576e150/packages/react-next/src/components/Popup/Popup.tsx#L138

- `root.current` is `null` during the first render
- `getWindow(null)` will return the main `window`

#### Actual behavior:

A handler is always belongs to the main `window` object.

#### Expected behavior:

A handler is pointed to a proper window.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal
Products/sites affected: N/A

**Comment by paulgildea** [comment]
@dzearing Since this is in `react-next` I'm assuming this is specific to the new convergence work?
