### ISSUE TITLE
Clarify and unify instruction message for the user cards 

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#14106]
This ticket is output of the user testing. 

**Please consider the following ticket will influence creating label for screen reader:**
https://github.com/microsoft/fluentui/issues/14110

**Example: Cards with actionable children in navigable grid**

Currently when user enters cards example reader narrates instruction message:
" Press arrow keys to navigate between cards"

Suggestion from testing (adding instruction about Enter/Escape):
"Press arrow keys to navigate between cards"
"To interact with the card press Enter"
"To stop the interaction with the card press Escape"

**Example: Selectable cards in a navigable grid**
Currently we are not providing any instruction.
Suggestion:
"press spacebar to select or unselect"

Comment: we should as well consider navigation instruction message "Press arrow keys to navigate between cards"

**Comment by rekpatel** [comment]
Use these placeholder strings.  Feature teams should be able to change the strings per their needs.  

"Press arrow keys to navigate cards"
"Press enter to interact within each card"
"Escape to exit card"
