### ISSUE TITLE
DetailList - First item stays selected when using ARROWDOWN key

### ISSUE THREAD

**Issue by Deepindera** [microsoft/fluentui#14102]
Arrow keys on DetailList select first element in the list (actually checking and adding it to the selection) . 
There has been a related bug raised before to it which was closed without proper resolution. 
Here it is 
https://github.com/microsoft/fluentui/issues/9011

Meaning of terms i am using here (just in case)
selected :  when row /item is selected - means the the item is in getSelection()
focussed:  item row is highlighted by not selected

Why i said "not proper resolution" ?
The problem reported there was that using arrow keys , the items in the detail list should not be selected. 
The solution was provided to be the following code
selectionZoneProps={{ selection: this._selection, isSelectedOnFocus: false }}

This code has partially worked.  All the rows except the first one does not get selected (and only get focussed) on when navigating using arrow keys. So for other rows it is fine but the first row is the problem or the bug. 

To replicate the problem , you can just use the existing codepen related to previous bug https://github.com/microsoft/fluentui/issues/9011.  The codepen shortcut https://codepen.io/kevintcoughlin/pen/XQPmBG?editors=0010

### Environment Information

- **Package version(s)**:  see the codepen version or mine local is  "7.123.3",
- **Browser and OS versions**:  Chrome Version 84.0.4147.89 on Windows 10 

### Please provide a reproduction of the bug in a codepen:

Steps to replicate

1) open the codepen  https://codepen.io/kevintcoughlin/pen/XQPmBG?editors=0010
2) Click on filter textbox (that has label Filter with name:)
3) Now press TAB , it will bring focus to the radio/input in the header column / which is used to select all 
4) Now press down arrow key and the focus will go on first row in the detail grid list . 
5) Press down arrow key again to reach second row but you will see the first row is actually selected now

Strange: That instead of arrow down key if you use TAB then the above bug behaviour does not happen

#### Actual behavior:
The first element gets selected when navigate from Select ALL radio/icon .

#### Expected behavior:
The first element should gain focus when moving from Select All radio in Detail List but should not be selected or stay selected when you move to second row using arrow down key

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)
![x](https://user-images.githubusercontent.com/853091/87902984-54870600-ca9e-11ea-82b8-ff42c6ffbecf.png)

**Comment by paulgildea** [comment]
@xugao Can you try and investigate the work around called out there. It's strange that it works for every other element except the first one.

@Deepindera - We're minimizing the amount of changes to the `DetailsList` at this time because of the complexity of the code base so I'm just setting expectations here. We'll try to see if we can find a good work around - but either way this might just be resolved as by design for now, until we focus our efforts on a converged `List` like solution in the future.

Hope that helps.

**Comment by xugao** [comment]
@KevinTCoughlin - could you shine some light here on why first row was selected on focus?
