### ISSUE TITLE
Search functionality in fluent UI  dropdown.

### ISSUE THREAD

**Issue by sunnyEspireGit** [microsoft/fluentui#14128]
#### Describe the feature that you would like added

Search functionality in fluent UI  dropdown.

#### What component or utility would this be added to

fluent UI  dropdown.

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

So basically when we are using fluent UI  dropdown if there are many options, instead of scrolling all options can we type and search for that option ? like we have in Jquery2 dropdown or react sementic UI dropdown.

**Comment by paulgildea** [comment]
@sunnyEspireGit Thanks for the feedback.

I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. But as we start to converge our `Dropdown` component we'll take this into consideration.

Thanks!

**Comment by sunnyEspireGit** [comment]
can you please suggest which control i can use as of now so that i get search functionality feature in dropdown as it is one of the requirement in our project.

**Comment by LukeOwlclaw** [comment]
@sunnyEspireGit We need the same thing (in the future). What should work is to customize the group header. [This pen](https://codepen.io/LukeO/pen/WNrPmBE) should get you started. The search functionality needs to be added. When you came up with something working, it would be awesome if you could share it. Thanks!

**Comment by sunnyEspireGit** [comment]
I have used react-sementic dropdown and it works awesome.....just sometimes dependency issue arrives.
