### ISSUE TITLE
HoverCard: items rendered with the onRenderExpandedCard function are not displayed

### ISSUE THREAD

**Issue by clavx** [microsoft/fluentui#14129]
In the HoverCard component, items are not displayed from the middle of the screen when using the List component with the onRenderExpandedCard function.

### Environment Information

- **Package version(s)**: 7.123.4
- **Browser and OS versions**: Windows 10 + Edge, Firefox

#### Actual behavior:

<img src="https://user-images.githubusercontent.com/58804032/88022209-d5f79a80-cb69-11ea-9342-fdc14207ff13.gif" width="600">

To reproduce this, replace `createListItems(10)` with `createListItems(50)` on line 27 of the "Example 1" code.

#### Expected behavior:

All list items are displayed.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
N/A

**Comment by paulgildea** [comment]
@xugao This is a tough one. Try to see if it's a sample issue - It's unclear to me whether this is a supported scenario if there are nested scrollers.

**Comment by paulgildea** [comment]
@clavx Thanks for the detailed repro GIF they are super helpful!

**Comment by xugao** [comment]
@clavx - looks like there is a bug using our `List`/`DetailsList` control inside `HoverCard`. JFYI- If i change the list to a plain html implementation [here](https://codepen.io/xugao/pen/xxZMzyP), it's working correctly.

**Comment by clavx** [comment]
Thank you for your response!

For now, I'll try to work around it by not using the List component.
