### ISSUE TITLE
Toolbar > submenu in a menu is not recognizable and improving tooltip example

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#14134]
This ticket is as output of user testing. 

It contains 2 issues:

1.
Missing instructions for the navigation of submenus 
Description: When staying on a menu item containing a submenu, instructions should be provided describing that the user is staying on an item with a submenu and explaining how the screen reader user can navigate the submenu using keyboard, that is, that one can use the Right arrow key to expand the menu and the left arrow key to collapse it. 
Severity: hihgh. 

**Solution: add "aria-haspopup=true" on the menu item which triggers submenu...**

2.
Toolbar with tooltips 
Suggestion for a better example 
The following is rather a suggestion for the choice of this paarticular example than an accessibility issue. The toolbar example should not contain only buttons with icons and no text, but, to demonstrate the use of a tooltip also for the screen reader users, the toolbar should contain also some button with some text, e.g., :Italic: and a tooltip associated with this textual button, e.g. “Switches the formatting to italic”. 

**Solution: Just to change example, that it will be more clear that tooltip is different from label of the button. I suggest to add button with text.**

**Comment by rekpatel** [comment]
Add aria-haspopup but instructions of using arrow will make it verbose.  This is a well understood keyboard pattern.
