### ISSUE TITLE
Sticky overflow:'hidden' hides box-shadow

### ISSUE THREAD

**Issue by b-juhi** [microsoft/fluentui#14142]
I'm investigating a bug where the overflow:'hidden' property of Sticky is hiding the box-shadow set for the component. Here's the snippet of code I found that's setting overflow:
```
Sticky.prototype._getContentStyles = function (isSticky) {
        return {
            backgroundColor: this.props.stickyBackgroundColor || this._getBackground(),
            overflow: isSticky ? 'hidden' : '',
        };
    };
```

And this function is being called to set the style of one of the div components in the render function:
`style: this._getContentStyles(isStickyTop || isStickyBottom)`

I currently don't see an option to override this setting from the parent component.
Can we add an optional prop to the Sticky component that can let us override the overflow property? 

Codepen example: https://codepen.io/b-juhi/pen/YzwByBy
To reproduce:
1. Scroll down the panel
2. Observe that the shadow in the sticky header is no longer visible

### Environment Information

- **Package version(s)**: 7.1.110
- **Browser and OS versions**: All browsers

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected:

**Comment by paulgildea** [comment]
@b-juhi Could you provide codepen or codesanbox of a reduced repro demonstrating the issue? That would help troubleshoot this issue. Thanks!

**Comment by b-juhi** [comment]
Codepen example: https://codepen.io/b-juhi/pen/YzwByBy

**Comment by xugao** [comment]
Agree this is a bug - i am not sure why `overflow: isSticky ? 'hidden' : '',` was added in first place.
