### ISSUE TITLE
CommandBar with sub menus do not render correctly in overflow panel  

### ISSUE THREAD

**Issue by anjumsaif** [microsoft/fluentui#14158]
If we have subitems in our menu it works perfectly alright. However, while attempting to make it responsive menu items are pushed to the ellipsis.. /overflow section. All works well until click on the submenu... for some reason it focuses just the first submenu...

**Comment by anjumsaif** [comment]
We developed a custom navigation using Office UI fabric command bar which seems to be working well until it is rendered on mobile devices and items are moved under ellipsis/ overflow area.

**Comment by anjumsaif** [comment]
![65488FD8-4A07-4B50-88FC-AD256D2C7C9B](https://user-images.githubusercontent.com/48895112/88466286-61399e80-ce90-11ea-947c-eb2228cfc441.png)

**Comment by xugao** [comment]
@anjumsaif - I'm afraid this is still not enough info for me to help you here. please provide a simple repro using codepen (or similar tool which can help us see the code).
