### ISSUE TITLE
No way to use brand (O365) multi-color icons

### ISSUE THREAD

**Issue by ChrisAckermanMS** [microsoft/fluentui#14151]
### Environment Information

- **Package version(s)**: Latest (7)
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/ChrisAckermanMS/pen/eYJxJjO

#### Actual behavior:

There appears to be no way to show one of the O365 multi-color brand icons mentioned here: https://developer.microsoft.com/en-us/fluentui#/styles/web/office-brand-icons#branded-icon-library

#### Expected behavior:

I would expect the `<Icon>` component to be able to show the O365 multi-color brand icons if given the correct `iconName` property value.

### Priorities and help requested:

Are you willing to submit a PR to fix? Maybe

Requested priority: Normal

Products/sites affected: https://myaccount.microsoft.com (localization settings).

**Comment by xugao** [comment]
@Jahnp - could you help answer this one? thanks!

**Comment by Jahnp** [comment]
Thanks for flagging @xugao .

This is super valid feedback, and this functionality has been desired for some time, but unfortuately there is currently no first-class support for the multi-color brand icons with the `<Icon>` component. There would probably need to be custom icon registrations for each brand/size/image type (SVG or PNG).

We'd considered adding a `<BrandIcon>` component in the past to support the unique needs of the branded assets, but that idea never got far. `<Icon>` could probably be extended as well.

As is, I'd consider this a feature request that needs more investigation and a design proposal. Adding @micahgodbolt for visibility as I'm not sure who'd be the next best general icons contact.
