### ISSUE TITLE
Chrome > VoiceOver > incorrect state of the card is narrated 

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#14165]
This ticket is output of user testing.

Env:
MacOS Catalina 10.15.5
Chrome 83.0.4103.116
VoiceOver

Description: When selecting a card using VO + spacebar, the screen reader first narrates the previous state of the card and then the actual state of the card. 

Repro steps

1. open URL https://fluentsite.z22.web.core.windows.net/components/card/definition
2. Navigate with VoiceOver keys into the example Selectable cards in a navigable grid
3. on the card press VO keys + space
Observe narration

Actual: “press {label} **not selected**, user card" 
“selected" 
Expected: it should narrate **selected** state 

Safari it narrates like:
“press {label} **selected**, user card" 
“selected" 
From this comparison with Safari it looks like some Chromium issue.

**Comment by paulgildea** [comment]
@smhigley FYI - note this is for the northstar package. See the [FAQ](https://github.com/microsoft/fluentui/wiki/FAQ---Fabric-and-Stardust-to-Fluent-UI#what-package-should-i-use-to-build-a-new-application) for the package descriptions.
