### ISSUE TITLE
Fluent v0 [Carousel] Paddles are not centered when content varies in height 

### ISSUE THREAD

**Issue by rekpatel** [microsoft/fluentui#14168]
Environment - https://fluentsite.z22.web.core.windows.net/components/carousel/definition

When carousel content height varies, the paddle navigation are not centered.  

#### Actual behavior:

![image](https://user-images.githubusercontent.com/49993085/88228721-6beffb80-cc24-11ea-8948-14b20a9f560f.png)

**Comment by susanshen96** [comment]
@rekpatel What is the status on this bug? We've received a couple bugs on Teams regarding this carousel issue and would like to provide an ETA on the fix. Thanks!
