### ISSUE TITLE
MessageBar - Link have an left padding that break alignment 

### ISSUE THREAD

**Issue by janjachacz** [microsoft/fluentui#14163]
### Environment Information

- **Package version(s)**:  v7.123.6
- **Browser and OS versions**: Edge, Edge Legacy, IE11, etc

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/janjachacz/pen/JjGxPKy

#### Actual behavior:
Link inside a MessageBar have a `padding-left: 4px;`.
When `isMultiline` property is set to `true` and the Link is the first element of the line, the alignment on the left side is broken.

#### Expected behavior:
Link shouldn't have a left padding.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Power Apps

![image](https://user-images.githubusercontent.com/6408904/88164999-48718480-cc15-11ea-9176-9fd9ffd477ae.png)

**Comment by paulgildea** [comment]
@janjachacz Thanks for the issue. Is it possible for your to override the styles of the Link component to get the desired padding?

@xugao I'm going to mark this as investigation, but if there's a work around that is just overriding styles I'm less inclined to take a fix here. l

**Comment by xugao** [comment]
@janjachacz - You will need to set custom styles to change the padding. see `messageBarStyles` I added in [your codepen](https://codepen.io/xugao/pen/QWyYxmW)

**Comment by janjachacz** [comment]
@xugao thx for the example but that removes the extra separation from the rest of the text, which I guess was the purpose of the padding in the first place. Also note that the fixed width of 660px in CodePen was just to illustrate the case when the Link is positioned at the beginning of a line.
