### ISSUE TITLE
Date Picker - Range mode

### ISSUE THREAD

**Issue by murbanowicz** [microsoft/fluentui#14175]
#### Describe the feature that you would like added

It would be great to have possibility to use DatePicker in Range mode, so user can select start and end date.

#### What component or utility would this be added to

DatePicker

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/9385106/88251733-06475200-ccac-11ea-8ed4-918adfc38ed3.png)

**Comment by paulgildea** [comment]
Thanks for the feature request @murbanowicz !

I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. However, when we start looking at converging the `DatePicker` we'll take this feature request into consideration.

@lorejoh12 Just FYI.

Thanks!

**Comment by volfpeter** [comment]
Hi @paulgildea 
Is there any update on this issue? Maybe a tentative decision date?

**Comment by gadusumi** [comment]
Hi @paulgildea  , Do we have tentative date at this moment for this to be in?
