### ISSUE TITLE
Type for Async.debounce does not account for arguments

### ISSUE THREAD

**Issue by SpencerLynn** [microsoft/fluentui#14188]
### Environment Information

- **Package version(s)**: 7.123.8
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:
It looks like the types for Async.debounce does not account for the arguments of the Function.

https://codesandbox.io/s/elastic-swartz-6vrpj?file=/src/App.tsx

Here is the raw TS also.
```
import { Async } from "office-ui-fabric-react/lib/Utilities";

function printAddOne(num: number): void {
  console.log(num + 1);
}

const async = new Async();
const debounced = async.debounce(printAddOne, 500);
const debounced2 = async.debounce<(n: number) => void>(printAddOne, 500);

debounced(300);
debounced2(300);
```

Here is the signature of debounce:
```
public debounce<T extends Function>(
    func: T,
    wait?: number,
    options?: {
      leading?: boolean;
      maxWait?: number;
      trailing?: boolean;
    },
  ): ICancelable<T> & (() => void) {
```

The issue is the last `() => void)`, which means the function can only ever be argument-less and void according to TypeScript.

#### Actual behavior:

Cannot call a Async.debounce function with an argument

#### Expected behavior:

No TypeScript error occurs when calling the debounced function with expected arguments.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: N/A

**Comment by paulgildea** [comment]
Thanks for the issue @SpencerLynn !

**Comment by xugao** [comment]
@SpencerLynn - agreed this is a bug. please go ahead submit a PR. thank you!

**Comment by SpencerLynn** [comment]
Thanks! I'm looking into a PR now, but running into weirdness with a potential type fix :)
