### ISSUE TITLE
To add the option of 'Select all' checkbox in the multi-select Dropdown component

### ISSUE THREAD

**Issue by Saloni268** [microsoft/fluentui#14182]
#### Describe the feature that you would like added

We would like to have a 'Select all' option in the multi-select Dropdown component such that when a user selects it, all the options in the dropdown are selected and when the user deselects it, all the options in the dropdown are deselected.

#### What component or utility would this be added to

Dropdown component

#### Have you discussed this feature with our team, and if so, who

NA

#### Additional context/screenshots

The UI for 'Select all' option, 

- when it is selected 
![image](https://user-images.githubusercontent.com/38312563/88329833-2a587100-cd48-11ea-918b-9cc9c7c12d7b.png)

- when it is deselected
![image](https://user-images.githubusercontent.com/38312563/88330153-9b982400-cd48-11ea-85d0-57ab40ddd79d.png)

The rest of the checkboxes should have the normal out of box UI,

- when it is selected
![image](https://user-images.githubusercontent.com/38312563/88330384-f2056280-cd48-11ea-9043-c3804fde8bd9.png)

- when it is deselected
![image](https://user-images.githubusercontent.com/38312563/88330443-06495f80-cd49-11ea-8472-d6625f5b31ca.png)

If in case this feature request will take time to be implemented, can you please suggest how can we customise the code to get the similar behaviour, especially how to align the UI differently for 'Select all' checkbox and keep the UI for the other checkboxes in the dropdown option as it is out of box.

**Comment by paulgildea** [comment]
Thanks for the feedback @Saloni268 !

I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance, however when we start to converge `Dropdown` we'll take this feedback into consideration.

In the meantime you might be able to add this functionality with a work around today by leveraging the `onRender` functions of the `Dropdown` to provide custom UI for a header that provides a "select all" like experience.

**Comment by xugao** [comment]
@paulgildea @Saloni268 - same request is already tracked here: #3726
