### ISSUE TITLE
Using theme variables in SCSS with the new @fluentui/react

### ISSUE THREAD

**Issue by Rafaelki** [microsoft/fluentui#14186]
I have replaced the "office-ui-fabric-react" package with "@fluentui/react" and I am trying to migrate my code.

In the SCSS file I had this import:
`@import '~office-ui-fabric-react/dist/sass/References.scss';` 
to use the SCSS variables like `$ms-color-themePrimary` or `$ms-font-size-xs`

Now that office-ui-fabric-react doesn't exist in my node_modules, what is the new way to do this?

**Comment by xugao** [comment]
@Rafaelki - thanks for reporting! you should be able to do `@import '~@fluentui/react/dist/sass/References.scss';` but looks like we have a bug and sass folder is missing from `@fluentui/react` pacakge.

**Comment by Rafaelki** [comment]
Thanks, @xugao, for your quick response :)

**Comment by Rafaelki** [comment]
Thanks
