### ISSUE TITLE
The dropdown, split button and combo box menus have too many lines in high contrast, making it hard to see focus or read

### ISSUE THREAD

**Issue by betrue-final-final** [microsoft/fluentui#14183]
### Environment Information

Edge + Windows 10

### Describe the issue:

Go to the sample page for dropdown, combobox, or split button
Turn on High Contrast
Click the control

Result: Menu is a mess of noise, making it difficult to see options and the focused option
![image](https://user-images.githubusercontent.com/20363037/88331570-0b26f880-cce2-11ea-8ecb-28bb0250d37d.png)

Expect: Should look like Contextual Menu
![image](https://user-images.githubusercontent.com/20363037/88331735-4aede000-cce2-11ea-8ead-387914b5c0f4.png)

**Comment by paulgildea** [comment]
@betrue-final-final Thanks for the screen shots!

@smhigley - FYI

**Comment by paulgildea** [comment]
Adding to #11742
