### ISSUE TITLE
Choice Group , option item not getting focus ring

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#14191]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: all browsers

### Describe the issue:

In ChoiceGroup there is public Focus Method to focus the selected option. This is useful when we want to externally focus the option.

When we focus the option using this method. the focus ring on the selected option wont appear.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/ssarapu/pen/xxZBXQL?editors=0010

#### Actual behavior:

When we focus the option in the choice group using public `focus` method. the focus ring on the selected option wont appear.

#### Expected behavior:

When we focus the option in the choice group using public `focus` method. the focus ring on the selected option  should appear.

**Comment by Raghurk** [comment]
Any update on this?

**Comment by xugao** [comment]
@TristanWatanabe  will work on a fix :)
