### ISSUE TITLE
Ability to override Remove icon 

### ISSUE THREAD

**Issue by fhdsouza** [microsoft/fluentui#14199]
#### Describe the feature that you would like added

Currently the Picker component only allows for whether the Remove button is visible or not; however, it cannot be overridden to supply a different icon.

#### What component or utility would this be added to

Picker Component

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

<img width="555" alt="Screen Shot 2020-07-24 at 10 27 52 AM" src="https://user-images.githubusercontent.com/25765551/88418432-64e9fa00-cd98-11ea-8e82-0a34cf4292c4.png">

**Comment by xugao** [comment]
@paulgildea - this is currently supported. i will let you triage further

**Comment by paulgildea** [comment]
Thanks for the feedback @fhdsouza !

I'll mark this as a feature request and add it to our backlog, but we're likely not going to get to it for a while as we're currently focused on larger coherence work items and enhancements to our performance, but we'll take it into consideration as we converge our `Pickers`

@joschect - Thoughts on a workaround if possible?

**Comment by JustSlone** [comment]
As long as the implementation here does not change the default behavior for existing customers, this is a fine fix to take. Tagging this with Help Wanted and inviting a community contribution here

**Comment by Augani** [comment]
@JustSlone I have looked into this and think this can be achieved by adding a prop that when given an icon name, will be used instead of the default "cancel". When no prop is given for that, the default is used.
If you can assign it to me, will send a pull request asap.

**Comment by Augani** [comment]
Alright, will submit the RFC

**Comment by JustSlone** [comment]
@Augani are you still planning on working on this issue?

**Comment by shujathkhan** [comment]
@JustSlone First time contributor here. I can look into this issue, if its still up for grabs. I feel to provide more support for this component, we can approach this in two ways,
- Expose an optional prop for the iconName in the PickerComponent as @Augani mentioned.
- Expose the icon as a optional component prop, as developers might want to hook up the component with third-party icons as well and might want some synthetic events to be triggered.

Please let me know what would be the best approach, open to suggestions.

**Comment by JustSlone** [comment]
Awesome @shujathkhan! 

Since there is already a means to provide custom icons via [`registerIcons`](https://github.com/microsoft/fluentui/wiki/Using-icons#registering-custom-icons) let's go with smaller change to provide an iconName other than 'Cancel'.

**Comment by shujathkhan** [comment]
Thanks @JustSlone I am ready with a PR, I wanted to confirm whether this change would also be made towards the PeoplePicker component and also, whether the Tag Picker and the People Picker have a story describing this prop ?

**Comment by behowell** [comment]
Hi @shujathkhan, thanks for submitting the PR. I added some comments there, but just to answer your questions:

> * Should this change would also include the PeoplePicker and Suggestions component ?

It looks like you added it to those in the PR -- that's great, thanks.

> * Should I include separate sub-stories for each component within their stories ?

I don't think it's necessary to have stories for this new prop.

> * What should the name of the prop be? I am currently assuming `iconName`.

I mentioned this in the PR, but to answer here: `removeButtonIconProps`

> * Should most of the modifications be made under [packages/react](https://github.com/microsoft/fluentui/tree/master/packages/react) ?

Yes. (The other react-* packages are for the next version of the library, which will have a different way of overriding icons like this.)
