### ISSUE TITLE
Dropdown option does not show ellipsis in option

### ISSUE THREAD

**Issue by shrallap** [microsoft/fluentui#14200]
Dropdown options does not show elipsis when the option is too long for dropdown

https://codepen.io/shrallap/pen/WNrYwxr?editable=true%3Dhttps://developer.microsoft.com/en-us/fluentui

**Comment by xugao** [comment]
@shrallap - thanks for reporting! I can confirm this is a bug

**Comment by nafisabarlaskar** [comment]
Hello @xugao ,
I am also not able to view the ellipsis. When I added the following CSS (shown in the image) in the class="ms-Button-flexContainer flexContainer-323"  in the browser's Inspect Element for the option which was having longer text, it came. Can you help in which element we need to add the CSS to make the ellipsis work?
![image](https://user-images.githubusercontent.com/6859513/100420408-6875f080-30ac-11eb-8c78-7bfb68bde397.png)
