### ISSUE TITLE
I would love to have this in Vue

### ISSUE THREAD

**Issue by donPuerto** [microsoft/fluentui#14207]
Is there a chance on Vue JS framework

**Comment by paulgildea** [comment]
Thanks for the feedback @donPuerto !

 Currently we are focused on building out a React offering for this repo at this time.

We like to hear this type of feedback from the the community and we are always evaluating what libraries to support for the Fluent Design Language in the future. 

But currently there is no plans to build out a VueJS specific solution at this time.

Thanks!
