### ISSUE TITLE
Getting accessibility issue for Dropdown component

### ISSUE THREAD

**Issue by Github307** [microsoft/fluentui#14214]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "7.115.3"
- **Browser and OS versions**: Chrome, Windows 10

### Describe the issue:

Multi-select Dropdown component is giving the following accessibility issues:

1.  'aria-required-children: Ensures elements with an ARIA role that require child roles contain them'

This is coming for the complete dropdown callout section. In the how to fix section, it is mentioned,

- Required ARIA child role not present: option

2. 'aria-allowed-attr: Ensures ARIA attributes are allowed for an element's role'

This is coming for each option in the dropdown. In the how to fix section, it is mentioned,

- ARIA attributes are not allowed: aria-posinset="1", aria-setsize="20"

- ARIA attributes are not allowed: aria-posinset="2", aria-setsize="20"

- ARIA attributes are not allowed: aria-posinset="3", aria-setsize="20"

This is our code snippet from where multi-select Dropdown is created,

`<Dropdown
            label='Label'
            id="multiselect-filter-dropdown"
            placeholder='Select a value'
            selectedKeys={this.getSelectedKeysMethod}
            multiSelect
            options={this.getOptionsMethod}
            styles={styles}
            responsiveMode={ResponsiveMode.large}
            onChange={this.onChangeMethod}
            onRenderTitle={this.onRenderTitleMethod}
          />`

#### Actual behavior:

We have not assigned any ARIA attributes to the components, still it showing accessibility issues. We are not sure how to fix this or provide/remove ARIA attributes explicitly from within the component.

#### Expected behavior:

No accessibility issues should come up.

**Comment by paulgildea** [comment]
@smhigley FYI

**Comment by Saloni268** [comment]
Any updates on this?

**Comment by Github307** [comment]
Hi @paulgildea @smhigley, any update on this bug?

**Comment by levymsft** [comment]
@Github307 I was having the same issues and got it sorted updating to the latest version.

**Comment by paulgildea** [comment]
Thanks for the update @levymsft. 

I'll closed this as fixed in the latest issue as no repo. Thanks!
