### ISSUE TITLE
Virtualized Combo to support full text search and inline item filtering

### ISSUE THREAD

**Issue by WillFrasier** [microsoft/fluentui#14212]
#### Describe the feature that you would like added

Today, the virtualized combo box simple auto completes the items in the list. However this is limiting when we want to search for partial matches. Ie. consider the text "This is an item". We can obviously type "This is..." and get a match, but it would be so much more handy to be able to type any part of the word and get a filtered list of matches in the drop down. So if I typed "match", it would filter the list of available options in the drop down in real time and limit to just those items which had the word "match". 

Along with full text search it would be great if the combo box could filter items in the list as the user types, to effectively show the search results. Here's an example from npm of another control that does the same thing:

https://www.npmjs.com/package/bootstrap-select

If there's a way to do this already, that would be fantastic! I have a list with almost 40k items that I'm looking to filter on, hence the VirtualizedComboBox. Please post a live code sample if so. 

Thanks again!

#### What component or utility would this be added to

virtualized combo box 

#### Have you discussed this feature with our team, and if so, who

Nope

#### Additional context/screenshots

This is a feature request to make it look like this: https://user-images.githubusercontent.com/2874325/38997831-97e12bbe-43ab-11e8-85f5-b8c05d91c7b1.gif

**Comment by paulgildea** [comment]
Thanks for the feedback @WillFrasier 

We are currently looking into this type of functionality for our `Dropdown` component as we've gotten a few more requests for this type of behavior. So it's becoming higher on our planning list.

To set expectations - I don't have any timelines to share at this time - but we are trying to determine when we could resource a feature like this. 

I'm going to mark this on backlog for now so that we don't lose it.

Thanks!

**Comment by WillFrasier** [comment]
Yes, please do. We're forced to use a third party control or build our own and we would love to continue using the Office Fluent UI web tools. Are there any work arounds within the Office Fluent UI toolkit?
