### ISSUE TITLE
My gulp serve is not displaying my spfx web part 

### ISSUE THREAD

**Issue by nmaitreyi** [microsoft/fluentui#14211]
i installed some react controls packages before that my gulp serve was working fine but after i installed react controls package my gulp serve was not rendering my webpart in the sharepoint work bench. i have tried to clear the temp data and uninstalled and again re installed node and all the packages .

please let me know what else i can do to solve this issue.

**Comment by paulgildea** [comment]
Thanks for the feedback @nmaitreyi 

However, with little much to go on or at least a repo of the issue we don't have enough to determine if there is a fundamental issue with our library when used with gulp.

You can use one of our templates to help fill out the necessary information.
