### ISSUE TITLE
@fluentui/react-northstar/dist/es\"' has no exported member 'themes'

### ISSUE THREAD

**Issue by Easystep2** [microsoft/fluentui#14221]
### Environment Information

- **Package version(s)**: (
- Browser : Chrome Version 84.0.4147.105 (Official Build) (64-bit)
- OS : Windows 10 Pro 20H2
- NodeJS v12.18.3
- NPM v6.14.7

[npm-shrinkwrap.txt](https://github.com/microsoft/fluentui/files/4986582/npm-shrinkwrap.txt)

### Problem

I've followed the package from git [->] (https://medium.com/swlh/building-a-ms-teams-app-using-react-fluentui-82a78b3a7de7)

used:

npm i @types/react-router-dom 
npm i @microsoft/teams-js 
npm i @fluentui/react-northstar 
npm i adal-angular

npm update

npm run-script build

and I received the message:

<img width="634" alt="error" src="https://user-images.githubusercontent.com/17320737/88632526-f9fc3400-d0b3-11ea-885c-fea320983593.png">

It seems the reference to themes is missing, when i look into the different documentation it also shows **"import { ThemePrepared, themes } from '@fluentui/react-northstar';"**

What am i missing?

**Comment by Easystep2** [comment]
any news on this topic?

**Comment by Easystep2** [comment]
Any news?

**Comment by tobiasviehweger** [comment]
Not related to the team, but I think it was renamed at some point.
![image](https://user-images.githubusercontent.com/2111803/89776943-1adc7480-db0b-11ea-90d3-8deae4631943.png)

**Comment by layershifter** [comment]
@Easystep2 this was a breaking change in `@fluentui/react-northstar@0.50.0`, themes are exported separately now. Please check a PR for the migration steps https://github.com/microsoft/fluentui/pull/13268.
