### ISSUE TITLE
Dismissing a panel, dismisses all panels that are currently shown

### ISSUE THREAD

**Issue by arvind1234** [microsoft/fluentui#14227]
### Environment Information

- **Package version(s)**: `office-ui-fabric-react@7`
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/arvind1234/pen/OJMYavq?editors=0010

#### Actual behavior:

* Have code that shows multiple panels on screen
* Close the top most panel using the close button
* All the panels are closed

#### Expected behavior:
* Only the top most panel should be closed

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@aneeshack4 - Do you know if `Panel` supports a stacking context similar to `Menu` so that you can have multiple panels over top of eachother?

@arvind1234 Thanks for the feedback. This one might be by design but we'll investigate a little bit. My initial assumption is that the `Panel` experience is a full page experience and only supports one to be shown at one time.

**Comment by arvind1234** [comment]
@paulgildea Thanks for getting back. 
>My initial assumption is that the Panel experience is a full page experience and only supports one to be shown at one time.
That was my initial thought too, but wanted to get the fluent teams' guidance before - I go about changing things on my side.

Also FWIW, I was able to workaround the issue by passing in an `noop`  function for  `onOuterClick` prop.

From whatever little, I looked at - passing in `onOuterClick` prop trigger this [line 433](https://github.com/microsoft/fluentui/blob/f9ca45d012d2e77eea728e19651b144452562004/packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx#L433) as opposed calling the `dismiss` method on [line 436](https://github.com/microsoft/fluentui/blob/f9ca45d012d2e77eea728e19651b144452562004/packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx#L436)

**Comment by xugao** [comment]
@arvind1234 @paulgildea - i don't think this is a bug. we wouldn't know when it's a valid/invalid outer click. It's based on app scenario. I would suggest a better way to fix it is to pass `onDismiss` to Panel 1 and based on the `event` to determine whether to dismiss Panel 1.

**Comment by arvind1234** [comment]
@xugao Thanks for getting back. I am curious as to why should outer click matter if light dismiss is false?

**Comment by arvind1234** [comment]
Also, regarding
> I would suggest a better way to fix it is to pass onDismiss to Panel 1 and based on the event to determine whether to dismiss Panel 1

Is there an easy way to identify the panel on which the dismiss happened? The event happens on the icon button and there is no way to easily identify the panel
