### ISSUE TITLE
APIs to implement infinite scrolling for DetailsList

### ISSUE THREAD

**Issue by hwkd** [microsoft/fluentui#14242]
#### Describe the feature that you would like added

Provide APIs to implement infinite scrolling for DetailsList. Perhaps a prop that accepts a function that gets called when the user reaches the bottom of the list?

#### What component or utility would this be added to

**DetailsList**

#### Have you discussed this feature with our team, and if so, who

No, the only channel I have is the github issues to reach any member of your team.

#### Additional context/screenshots

I have a list that can grow infinitely long over time, so I would like to implement the infinite scroll using the DetailedList component for my app but I don't think there are relevant APIs provided in order for me to extend it.

I mean, I can achieve this by attaching the scroll event listener and determining if the user has touched the bottom, but I believe that providing a convenient prop would make it a better experience from the component user's perspective.

**Comment by paulgildea** [comment]
Thanks for the feedback @hwkd !

I'll mark this as a feature request and add it to our backlog, but we're likely not going to get to it for a while as we're currently focused on larger coherence work items and enhancements to our performance.

Also to set expectations we are limiting the amount of new functionality being added to the `DetailsList` component as it's become overly complex and difficult to maintain. So we probably won't be adding this feature in the future until we decide on new listing scenarios.

**Comment by hwkd** [comment]
I see, I would also consider it a low priority feature. I will instead wrap in with my own component that does this for my app. Thanks for the quick response.
