### ISSUE TITLE
[charting] Legends pass the active status in properties

### ISSUE THREAD

**Issue by NewFuture** [microsoft/fluentui#14246]
#### Describe the feature that you would like added

control the status of the legend and allow multi-selection in `<Legends/>`.

#### What component or utility would this be added to

two ways:

1. add the  `active` property to  `ILegend` 

```js
 {
        title: 'Legend 1',
        color: DefaultPalette.yellow,
        shape: 'triangle',
        active: true,
 }
```
2. or add  the `activeLegends`  property to the `<Legends />`

```
<Legends  legends={legends} activeLegends={[]}>
```

**Comment by paulgildea** [comment]
@Raghurk - I'll let you take this one 😄 .
