### ISSUE TITLE
[VerticalStackedBarChart] The x-axis text is on the top in IE browser

### ISSUE THREAD

**Issue by luckyrass** [microsoft/fluentui#14243]
### Environment Information

- **Package version(s)**: (@uifabric/charting_v2.7.6)
- **Browser and OS versions**: (IE11)

### Please provide a reproduction of the bug in a codepen:

The x-axis descriptor is on the top in IE browser

#### Actual behavior:
![image](https://user-images.githubusercontent.com/12230173/88877234-990d6100-d257-11ea-99be-fe5fdfc36a02.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/12230173/88877331-c78b3c00-d257-11ea-9371-c54a952592d8.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking)

Products/sites affected: (https://admin-ignite.microsoft.com/adminportal/#/reportsUsage/LicenseActivity)

**Comment by paulgildea** [comment]
@Raghurk - We've changed triage a little bit. This has been marked as investigation. If you find that it's an actual reproducible issue please remove the Needs: Investigation tag with Type: Bug tag. Thanks!

**Comment by xugao** [comment]
@Raghurk - gentle ping on getting the issue triaged. thank you!

**Comment by Raghurk** [comment]
Opened a bug locally
