### ISSUE TITLE
LineChart: yMaxValue and yMinValue given, but not applicable to line chart y axis.

### ISSUE THREAD

**Issue by jameelakowsar** [microsoft/fluentui#14258]
### Environment Information
- **Browser and OS versions**: All Browsers

#### Actual behavior:
![image](https://user-images.githubusercontent.com/20105532/88925914-db07c880-d292-11ea-93a9-3b6e004ae7a0.png)

#### Expected behavior:
If yMaxValue and yMinValue given, yAxis need to draw between these lines.
Like below graph
![image](https://user-images.githubusercontent.com/20105532/88926182-35a12480-d293-11ea-8122-5ac4b907ae74.png)

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@Raghurk FYI

**Comment by jameelakowsar** [comment]
PR Raised
https://github.com/microsoft/fluentui/pull/14256
