### ISSUE TITLE
[Feature Request] use <picture> element to wrap <img> element, provide page load speed optimization. (support webp)

### ISSUE THREAD

**Issue by cubesky** [microsoft/fluentui#14251]
#### Describe the feature that you would like added

Use `<picture>` tag to wrap `<img>` tag and provide alternative load source, this can tell browser to load suitable picture when browser support such as `image/webp` image.

```html
<picture>
  <source type="image/webp" srcset="example.webp">
  <source media="(min-width:650px)" srcset="example-min.jpg">
  <img src="example.png" alt="Example" style="width:auto;">
</picture>
```

This can make browser which doesn't support webp image to load png (Such as Safari), browser has webp image support will load webp image to improve page load speed(Such as Chrome). And it also can query media to show different image with different min-width max-width.

![image](https://user-images.githubusercontent.com/8038511/88906375-f4584700-d289-11ea-9ba1-ddd104108be5.png)

If browser doesn't support <picture> tag, it will ignore this tag, so it shouldn't has any compatibility issue.

#### What component or utility would this be added to

This will affect all component which has `<img>` tag in it.

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

No

**Comment by cubesky** [comment]
> Thanks for the feedback @cubesky !
> 
> Is this a browser request to support the `<picture/>` element or is this a request to create a new React JS `<Picture />` component that exhibits the behavior you call out?

I think add an optional attribute to all component which contain <img> is better, such as `DocumentCardPreview` `DocumentCardImage` `Image` etc... 

I think we can add an attribute called srcSet which contain `type` `media` `src` to generate `<picture>` element for that component. For an example, if `Image` component doesn't have `srcSet` attribute, it doesn't change any behavior, if it contains `srcSet` then generate `<picture>` and `<source>` element from `srcSet` attribute to wrap <img> element.

**Comment by cubesky** [comment]
> Thanks for the feedback @cubesky !
> 
> Is this a browser request to support the `<picture/>` element or is this a request to create a new React JS `<Picture />` component that exhibits the behavior you call out?

I create this feature request due to `Google PageSpeed Insight` told me to use `webp` image to improve page load speed, but I have an static generated blog with `Gatsby` and a theme written by me using this ui framework, so I can't do any server side optimization, but html has this element to make possible to load suitable image on a large set of browser.

**Comment by paulgildea** [comment]
@cubesky I think I understand now. It a feature request mostly to support `webp` as a first class image source. I'm going to change the title to reflect that.

I'll add this to our backlog - but to set expectations we're focused on converging components across our two react packages. However, we'll take this into account as we work on the fundamental `Image` component. I don't have any specific timelines to share at this time unfortunately.

As a potential workaround you might be able to custom render or replace the image sub component with your own HTML definition - however I that would be specific to the component's interface that would allow that type of rendering.

Hope that helps.

Thanks!

**Comment by cubesky** [comment]
Thanks!
