### ISSUE TITLE
Unable to set styles for dropdown menu items using rootHovered and rootPressed 

### ISSUE THREAD

**Issue by yanbxice** [microsoft/fluentui#14266]
### Environment Information

- **Package version(s)**: 7

### Please provide a reproduction of the bug in a codepen:
I'm currently using subMenuProps.items in ICommandBarItemProps to show a dropdown menu. I want to set different colors when each item is hovered and pressed. I found that the style of dropdown items is type IContextualMenuItemStyles, and IContextualMenuItemStyles extends IButtonStyles. But rootHovered, rootPressed from IButtonStyles seem like not working for these them.

https://codepen.io/yanbxice/pen/ExPEpav?editable=true%3Dhttps%3A%2F%2Ffabricweb.z5.web.core.windows.net%2Foufr%2F7.121.4%2F

#### Actual behavior:

Unable to set styles for hovered and pressed state of dropdown menu items

#### Expected behavior:

should be able to set styles for hovered and pressed state of dropdown menu items

### Priorities and help requested:

Requested priority: Normal

**Comment by paulgildea** [comment]
@joschect - Any idea if these styles are actually exposed? I wasn't able to find any source code examples in the component where we set those in CSSinJS.

**Comment by xugao** [comment]
@yanbxice - this is a bug on our side not respecting `rootHovered` and `rootPressed` fields.
You can use `root` with `selectors` to work around the issue, see demo [codepen](https://codepen.io/xugao/pen/KKVONzX)
