### ISSUE TITLE
ComboBox RTL

### ISSUE THREAD

**Issue by Moiahbabi** [microsoft/fluentui#14264]
### Environment Information

- **Package version(s)**: "^7.123.9"
- **Browser and OS versions**: Chrome: 84.0.4147.105, Win 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/moiahbabi/pen/yLedRrZ

#### Actual behavior:

when setting `document.dir = 'ltr'`, the ComboBox  layout switches as expected, but the caretDownButton shifts outside the wrapper.

![arComboBox](https://user-images.githubusercontent.com/26636470/88952863-13b29c80-d2a9-11ea-9090-5185d68a0839.jpg)

#### Expected behavior:
padding for caretDownButton and wrapper text is reveresed when rtl is applied.
![arComboBox_Fix](https://user-images.githubusercontent.com/26636470/88953142-84f24f80-d2a9-11ea-9ec9-d6374ea60453.jpg)

the issue can be solved with the following styles added to the ComboBox:

```
const comboBox = {
  root: {
    ...
    paddingInlineStart: "9px",
    paddingInlineEnd: "32px",
    ...
  }
};
```
but this won't work with IE.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Above my skills level, sorry.)

Requested priority: (Normal) 

Products/sites affected: (if applicable)

**Comment by dzearing** [comment]
1. Use the `setRTL` helper to programatically set it; otherwise code which needs to flip rules can't execute. Example: https://codepen.io/dzearing/pen/PoZrrVX
2. Render your page with the dir set before rendering. The components will respect the initial state.

**Comment by dzearing** [comment]
Hope this resolves your issue! Let us know if you run into any issues.

**Comment by Moiahbabi** [comment]
Tried it in my project, it works as intended. Thank you.
