### ISSUE TITLE
Document Card OnLoad Method does not work in the Microsoft Teams App

### ISSUE THREAD

**Issue by ravi16a87** [microsoft/fluentui#14276]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:
Used DocumentCard control in SPFx webpart and deployed it as a Tab in Microsoft Teams.
<DocumentCard onLoad={()=> this.testMethod()}>, testMethod it works fine in Microsoft Teams browser but the same **doesn't** get invoked in the **Microsoft Teams App** 

#### Expected behavior:

onLoad should be consistent and  should work fine in both Microsoft Teams browser & Microsoft Teams App 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) : No

Requested priority: (Blocking, High, Normal, Low) : Normal

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
Thanks for the feedback @ravi16a87 

Is it possible to give us an idea of what package versions you are using and a possible codepen or repro that we can use to debug the specific issue? That would help us get more traction on this specific issue.

Thanks!

**Comment by ravi16a87** [comment]
Hello ,

My apology for replying on this late. 
Below are the details about the packages:
"@fluentui/react": "^7.122.0",
    "@microsoft/sp-core-library": "1.10.0",
    "@microsoft/sp-lodash-subset": "1.10.0",
    "@microsoft/sp-office-ui-fabric-core": "1.10.0",
    "@microsoft/sp-property-pane": "1.10.0",
    "@microsoft/sp-webpart-base": "1.10.0",
    "@microsoft/teams-js": "^1.7.0",
    "@pnp/graph": "^2.0.6",
    "@pnp/odata": "^2.0.6",
    "@pnp/sp": "^2.0.6",
    "@pnp/spfx-controls-react": "^1.19.0",    
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/webpack-env": "1.13.1",
    "@uifabric/react-cards": "^0.109.114",  
    "npm": "^6.14.6",
    "office-ui-fabric-react": "6.189.2",
    "react": "16.8.5",
    "spfx-uifabric-themes": "^0.8.0",

Unfortunately i wont be able to give you a codepen link, but you can try simple below piece of code :
  
1. import {
  DocumentCard,
  DocumentCardActions,
  DocumentCardActivity,
  DocumentCardLocation,
  DocumentCardPreview,
  DocumentCardTitle,
  IDocumentCardPreviewProps,
  DocumentCardDetails,
} from 'office-ui-fabric-react/lib/DocumentCard';

2. Create one test method 
3. Call this method like <DocumentCard onLoad={testmethod}/>

this will work in Teams Tab in the browser but this onLoad doesnt trigger in the Teams App tab

Let me know if you have any queries.

**Comment by xugao** [comment]
@ravi16a87 - in order for us to help you, you would need to provide us a simpler repro that's independent from the (Teams) app. A codepen with repro is the most preferred.

**Comment by ravi16a87** [comment]
Dear @xugao,

Like i said this issue is working fine on browser and in the codepen as well. This is specific to Teams App and i wont be able to repro it anywhere else. In case you wont be able to proceed with this info you can close this issue.

**Comment by behowell** [comment]
Hi @ravi16a87, since it's been a few months without any activity on this bug, I'm going to assume that you've found a workaround or otherwise resolved this issue. Feel free to re-open if it's not resolved, and you have repro steps that we can use to investigate the issue. Thanks.
