### ISSUE TITLE
Keyboard navigation is not working When GroupedList is inside a Focuzone

### ISSUE THREAD

**Issue by smandava** [microsoft/fluentui#14279]
### Environment Information

- **Package version(s)**: //unpkg.com/office-ui-fabric-react@7/dist/office-ui-fabric-react.js
- **Browser and OS versions**: Chrome/Any OS

### Describe the issue:

Keyboard navigation is not working When GroupedList is inside a Focuzone

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/sateeshm/pen/OJMKMXY

#### Actual behavior:

Press down arrow key in TextField, and nothing happens.

#### Expected behavior:

Press down arrow key in TextField, first group header in the GroupedList should be selected. [This Codepen](https://codepen.io/sateeshm/pen/gOPVPRJ) using the Basic [List](https://developer.microsoft.com/en-us/fluentui#/controls/web/list) control works as expected.

**Comment by paulgildea** [comment]
Thanks for the feedback @smandava !

**Comment by xugao** [comment]
issue is regression from #11494: see [repro](https://codesandbox.io/s/thirsty-ptolemy-r8y2t)

**Comment by xugao** [comment]
@smandava - we recently made a change related to focus management inside `GroupedList`, which is by-design. Regarding your scenario, I would recommend you remove the `FocusZone` which wraps the `GroupedList` and let user **tab** onto `GroupedList` from `TextField`. here is the [codepen](https://codepen.io/xugao/pen/BaKBwPQ)

**Comment by smandava** [comment]
The proposed solution was what I ended up using in my project. I had opened this issue thinking it could be a bug in one of the two components. Thanks for taking your time to look into the issue.
