### ISSUE TITLE
DetialsList: onActiveItemChanged does not invoke when groups is set

### ISSUE THREAD

**Issue by ngyukman** [microsoft/fluentui#14275]
### Environment Information

- **Package version(s)**: 7.124.0
- **Browser and OS versions**: chrome

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/ngyukman/pen/JjGQgVe?editors=1010

in 7.121.11 it is working as expected

#### Actual behavior:

onActiveItemChanged is no longer invoked once groups is set

#### Expected behavior:

it should work the same with or without groupings

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes, depends if I could find a solution

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
Thanks for reaching out @ngyukman ! And that's for giving us the two versions you've noticed the behavior between. That's super helpful.

@xugao - Can we determine if there was a recent check that may have caused this regression?

**Comment by xugao** [comment]
looks like this regressed from #11494. will look into a fix

**Comment by ngyukman** [comment]
Thanks, the fix is quick 👍
