### ISSUE TITLE
In multi-select drop down screen readers are not announcing the position of selected option and total number of options.

### ISSUE THREAD

**Issue by crazyLayne** [microsoft/fluentui#14300]
### Environment Information

Browser and OS versions: Chrome, Edge

### Describe the issue:

In multi-select drop down, screen readers are not announcing the position of selected option and total number of options.
It works fine in single select drop down. I have found the same issue here https://github.com/microsoft/fluentui/issues/12151. But the issue has been closed and I still can repro it.

### Please provide a reproduction of the issue in a codepen:

https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown

#### Actual behavior:

screen readers are not announcing the position of selected option and total number of options.

#### Expected behavior:

screen readers announce the position of selected option and total number of options, same as single-select drop down.

**Comment by paulgildea** [comment]
@crazyLayne Thanks for feedback!

@smhigley - FYI

**Comment by khmakoto** [comment]
@crazyLayne I can confirm that this is happening, I'll work on a solution as soon as possible, thanks!
