### ISSUE TITLE
CommandBar does not render tooltipHostProps.content with iconOnly mode as true

### ISSUE THREAD

**Issue by pranitha-surya** [microsoft/fluentui#14310]
CommandBar does not render tooltipHostProps.content with iconOnly=true, when text/name is not available in props

### Environment Information

- **Package version(s)**: 7.123.3
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/pranithasurya/pen/MWKLgqJ

#### Actual behavior:

When you hover on the share icon, the tooltip content is not shown even when the iconOnly mode is true. The reason is because the text/name prop is not available. 

#### Expected behavior:

The tooltip content rendering should only depend on iconOnly prop and not on text/name prop.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: All fluentui dependent websites

**Comment by paulgildea** [comment]
@khmakoto - Just incase this wasn't picked up.
