### ISSUE TITLE
Allow PositioningContainer to take in a list of allowedDirections for alignment

### ISSUE THREAD

**Issue by sachin9996** [microsoft/fluentui#14314]
#### Describe the feature that you would like added

Allow the PositioningContainer to take (as a prop) a list of allowedDirections to specify the allowed ways the element can be positioned.

Currently the PositioningContainer takes in a directionalHint prop of type DirectionalHint as a suggestion for which edge to align the element against. But the list of directions eventually tried is the entire DirectionalHint enum. It would be useful to have the allowed directions be restricted to some subset of this. A use case is provided below.

#### What component or utility would this be added to

PositioningContainer

#### Have you discussed this feature with our team, and if so, who

Nope

#### Additional context/screenshots

I have a dialog with a grid that renders some suggestions for cell values as a callout. I need to decide to position these suggestions above or below the cell depending on where it is positioned to minimize dialog overhang:

(Below cell)
![image](https://user-images.githubusercontent.com/11214177/89221692-9167f800-d588-11ea-9ecb-c5fc06bf2b40.png)

(Above cell)
![image](https://user-images.githubusercontent.com/11214177/89222067-3b478480-d589-11ea-9092-fde68810e5d0.png)

However these are the only two alignments I want to have; I don't want the suggestions to appear on the left or right of the cell. One way to achieve this would be to restrict the directions that are allowed for positioning the suggestions box.

**Comment by khmakoto** [comment]
Hi @sachin9996, thanks for filing this issue! I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.
