### ISSUE TITLE
DragDropHelper: strict mode compliance (findDOMNode)

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#14321]
DragDropHelper uses [`ReactDOM.findDOMNode`](https://reactjs.org/docs/react-dom.html#finddomnode) which is now discouraged for various reasons and [deprecated in strict mode](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage).

It will continue to work as long as the parent and child for every drag/drop operation are class components (despite causing warnings in strict mode), but once something is converted to a function component, per the docs it sounds like the `findDOMNode` call will no longer work. So long-term we'll need to find another way to handle this scenario, even if we choose not to fix the warning right now.

**Comment by MLoughry** [comment]
The only way to fix this is to fix all components it's applied to to either
* be a ref-forwarding functional component with a ref that extends `HTMLElement`
* implement an interface that exposes some sort of `ref` property (eg., `domRef`) that returns an `HTMLElement`

**Comment by ecraig12345** [comment]
Thinking about it more (and in comparison with the `withResponsiveMode` issue), for this one I'm not sure even adding a forwarded ref or `domRef` everywhere would fix it, since the `DragDropHelper` doesn't create the components it's operating on. Unless I'm missing something, I think you'd need a public member (or imperative handle for function components?) to get the root element.

Also, the only part of DragDropHelper that uses `findDOMNode` is determining whether there's a nested drop target. Not sure if there's any alternative way to do that?

@dzearing Do you have any ideas here? Or @layershifter is this something you've dealt with in v0?

**Comment by MLoughry** [comment]
Looking more closely at it, there's absolutely no reason to even use `findDOMNode` in this case. PR out shortly...
