### ISSUE TITLE
withResponsiveMode: strict mode compliance (findDOMNode)

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#14320]
`withResponsiveMode` uses [`ReactDOM.findDOMNode`](https://reactjs.org/docs/react-dom.html#finddomnode) which is now discouraged for various reasons and [deprecated in strict mode](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage).

While this is less likely to present a practical problem in this case, since by definition a decorator like `withResponsiveMode` must wrap a class component, it will probably still trigger warnings in strict mode and we should try to remove it.

**Comment by MLoughry** [comment]
The only way to fix this is to fix all components it's applied to to either
* be a ref-forwarding functional component with a ref that extends `HTMLElement`
* implement an interface that exposes some sort of `ref` property (eg., `domRef`) that returns an `HTMLElement`

**Comment by ecraig12345** [comment]
That's what I was afraid of. Do you think it would be worth reopening your old PR #11945 to add `domRef` help fix this, at least for the things which are still class components? (Sorry for not being more helpful with that PR before.) Or would it be better to just live with the warning for now?

**Comment by ecraig12345** [comment]
I'd potentially be okay with allowing the warning to stay in this case since as mentioned in my initial comment it shouldn't be a functionality issue (any function components would not be using this decorator).

**Comment by MLoughry** [comment]
If the goal is for v8 to be StrictMode-compliant, there's no way around it; we can't live with the warning.

Redoing the whole `domRef` change is possible, but it would mean that we would have this extra prop that's redundant for functional components. We could maybe implement it just for the affected OUFR components, though.

**Comment by ecraig12345** [comment]
@czearing I don't think your `useResponsiveMode` PR means work is complete on this. Unless everything gets converted to function components before v8, which isn't going to happen, we still need to fix the decorator too.

**Comment by ecraig12345** [comment]
I think @dzearing suggested something like wrapping the `useResponsiveMode` hook in a component updating `withResponsiveMode` to use that--not sure of the details, and I couldn't immediately figure out how to make it work in a quick experiment (but it might be possible).

While doing this, I think we should also either export `useResponsiveMode` from the root OR move it (and the utilities) to react-hooks.

**Comment by MLoughry** [comment]
`useResponsiveMode` requires a DOM ref, which leaves us back at the same situation we were before: either the component needs to provide us this DOM ref, or use `findDOMNode` 😔
