### ISSUE TITLE
Adding help to Builder "Alpha"

### ISSUE THREAD

**Issue by jadocoder** [microsoft/fluentui#14337]
#### Describe the feature that you would like added

Adding help or instructions on how to use the FluentUI Builder

#### What component or utility would this be added to
https://fluentsite.z22.web.core.windows.net/builder

#### Have you discussed this feature with our team, and if so, who

 no, not yet

#### Additional context/screenshots

![fluentUI Builder](https://user-images.githubusercontent.com/67600175/89327136-09015a00-d651-11ea-8182-c32428fbb7f5.PNG)

**Comment by khmakoto** [comment]
@miroslavstastny FYI.
