### ISSUE TITLE
Charting: X axis lables getting overlapper with another when we have more length strings

### ISSUE THREAD

**Issue by jameelakowsar** [microsoft/fluentui#14333]
# Environment Information
- **Package version(s)**: All versions
- **Browser and OS versions**: All Browsers

#### Actual behavior:
X axis lables are wrapping when string have more length
![image](https://user-images.githubusercontent.com/20105532/89296753-6b258380-d680-11ea-8401-6ea2297cb7c8.png)

#### Expected behavior:
Labels should not overlap on each other.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
@Raghurk FYI
