### ISSUE TITLE
Cannot apply ":before" and ":after" pseudo selectors

### ISSUE THREAD

**Issue by nagisa1993** [microsoft/fluentui#14330]
### Environment Information

- **Package version(s)**: 7.8.1
- **Browser and OS versions**: new Edge, 84.0.522.52

### Describe the issue:

Cannot apply ":before" and ":after" pseudo selectors
Here is part of my code which uses selectors:
```
{
...
selectors: {
      ':before': {
        content: '',
        position: 'absolute',
        height: '119px',
        width: '40px',
        left: '-40px',
        backgroundImage: `linear-gradient(to right, red, blue)`
      },
      ':after': {
        content: '',
        position: 'absolute',
        height: '119px',
        width: '40px',
        right: '-40px',
        backgroundImage: `linear-gradient(to left, red, blue)`
      }
    }
}
```

#### Actual behavior:

no before and after pseudo selectors was applied

#### Expected behavior:

before and after pseudo selectors should be applied

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by brandonthomas** [comment]
@nagisa1993 did you try doing `content: '""'` instead?

**Comment by nagisa1993** [comment]
oh yeah, it worked! Thanks! @brandonthomas 

> @nagisa1993 did you try doing `content: '""'` instead?
