### ISSUE TITLE
Proposal: Update web-components package to use the @fluentui/ namespace

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fluentui#14343]
Currently the web components package is under the global `@microsoft/` namespace with a package name of `@microsoft/fast-components-msft`. Aside from the obvious of not sharing the existing `@fluentui/` namespace, there are also publishing considerations that updating the package name will resolve. This package was previously published using lerna, which would rev the package version, create a changelog, fire off tags and force push a publish commit to master. I don't think that is a wise publishing method to inject into the workflow here. Additionally, there are permissions issues with that approach.

It seems that the fastest and safest way to address this issue would be to update the namespace and include the Web Components package as part of the publish process.

Proposed package name: `@fluentui/web-components`. Ideally, I like the concept of simply calling these "components" rather than specifying web components, but I understand with existing conventions that could cause confusion. :)

**Comment by dzearing** [comment]
Totally support @fluentui namespace rename, asap.

I would prefer to keep the package `web-components`, too many frameworks call things components and that at least spells  out what's going on.

**Comment by awentzel** [comment]
I think we should retain `@microsoft/` as the prefixed namespace, though I am checking with the OSS team to get guidance here.  My recommendation would be to retain the complete brand as `@microsoft/fluentui-web-components`

**Comment by EisenbergEffect** [comment]
If Fluent UI has been publishing under `@fluentui`, then I think we should make the change. @chrisdholt We'll want to coordinate the first publish under this name with an update to our fast site documentation. I can prepare those changes, given a day or so notice.

**Comment by chrisdholt** [comment]
@EisenbergEffect I think we'll move quickly here and per @dzearing the publish happens nightly. If you'd like, I can do a pass on our end to wrap this work and coordinate since it's getting later in the day where you're at.
