### ISSUE TITLE
Border Appearing Around DefaultButton Components

### ISSUE THREAD

**Issue by rmbw74** [microsoft/fluentui#14359]
### Environment Information

- **Package version(s)**: office-ui-fabric-react": "6.189.2"
- **Browser and OS versions**: 

### Please provide a reproduction of the bug in a codepen:
Here is the markup being used: 
`<DefaultButton className={styles.adminPanel_button} onClick={this._showPanel} text="Admin Access" />`

![2020-08-05 07_20_47-Window](https://user-images.githubusercontent.com/15833201/89414270-bf1b8100-d6ef-11ea-84bd-8df8eee6bc99.jpg)

#### Actual behavior:

Default Button Components used in SPFx 1.10 solution have started showing borders around them Tuesday 8/4/2020, this has been happening in some of our Older SPFx 1.4.1 solutions since May, and was originall reported on the SPFx teams gitHub,
[Button Elements appearing in panel with borders](https://github.com/SharePoint/sp-dev-docs/issues/5764)

#### Expected behavior:

Button Components should not be showing borders around them unless it is specified in CSS

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: SharePoint Online

**Comment by khmakoto** [comment]
Hi @rmbw74, is there any way to get a minimal repro of this behavior? Thanks!

**Comment by rmbw74** [comment]
> Hi @rmbw74, is there any way to get a minimal repro of this behavior? Thanks!

Ill see what I can do!
