### ISSUE TITLE
The parsing of HEX color for transparent in IE fails for color picker

### ISSUE THREAD

**Issue by aletodericiu** [microsoft/fluentui#14356]
### Describe the issue:

When we provide #ffffff00 as a transparent color for the color picker, IE11 fails to parse the hex, therefore the color picker popup doesn't load.

#### Actual behavior:

The popup for color picker fails to open in IE11 due to the parsing of the hex for transparent color.

#### Expected behavior:

The popup for color picker should open and the parsing of the hex color for transparent should be successful.

### Priorities and help requested (not applicable if asking question):

Requested priority: High

**Comment by khmakoto** [comment]
Hi @aletodericiu, do you have a minimal repro of this issue? I tried to repro it locally but I wasn't able to, with the `ColorPicker` rendering in IE11 every time.
