### ISSUE TITLE
Debug panel does not show any styles if cache is used

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#14358]
### Environment Information

- **Package version(s)**: 0.51.0

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/debug-styles-cache-r5fbs

#### Actual behavior:

Have two identical `Button`s rendered side by side. Use FUI's CSSInJS debug tool to inspect styles of the two components.
One of them does not show any styles:
![image](https://user-images.githubusercontent.com/9615899/89417582-26a4f100-d72f-11ea-80c6-3411139fb9fb.png)

#### Expected behavior:

Both components show used styles

**Comment by paulgildea** [comment]
@miroslavstastny Bringing this one back.
