### ISSUE TITLE
The axis of the charts needs to support RTL

### ISSUE THREAD

**Issue by cariceli** [microsoft/fluentui#14352]
### Environment Information

- **Package version(s)**: @uifabric/charting v2.5.0
- **Browser and OS versions**: All

### Describe the issue:

The axis of the charts needs to support RTL

#### Actual behavior:
![image](https://user-images.githubusercontent.com/42231272/89368318-cfdaef80-d70d-11ea-9146-6a3e67627465.png)
![image](https://user-images.githubusercontent.com/42231272/89368520-5263af00-d70e-11ea-8738-91f4ffb1fa11.png)
![image](https://user-images.githubusercontent.com/42231272/89368529-5a235380-d70e-11ea-8e3e-92bdc49aa961.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/42231272/89368461-306a2c80-d70e-11ea-8a8f-a38414e4d63e.png)

**Comment by khmakoto** [comment]
@Raghurk FYI

**Comment by Raghurk** [comment]
Opened a bug

**Comment by shivasai09** [comment]
@paulgildea, i Think this is more of a feature request then a bug.
