### ISSUE TITLE
[DetailsRow] Custom props for rowFieldsAs component

### ISSUE THREAD

**Issue by known-as-bmf** [microsoft/fluentui#14368]
#### Describe the feature that you would like added

When using `rowFieldsAs` in a `DetailsRow`, I would like to be able to pass additional custom props to my custom component.

For example, `DetailsRow` could have a `rowFieldsProps` prop, or something similar, that would be spread [here](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx#L249).

It may be hard to properly type this prop but maybe `any` could be enough for now.

#### What component or utility would this be added to

[`DetailsRow`](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx)

#### Have you discussed this feature with our team, and if so, who

Nope

#### Additional context/screenshots

N/A

**Comment by known-as-bmf** [comment]
This is an easy feature to implement and I don't think it can cause regressions.

I would really appreciate if you reconsider adding it.

**Comment by khmakoto** [comment]
@known-as-bmf I think just on the fact that there is no defined typings we would apply to it is enough to warrant not taking this in. `any` is fragile but I'm all ears if you have a suggestion on what the typings could be.

**Comment by known-as-bmf** [comment]
I agree that `any` is not ideal.

However, the [`item`](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.types.ts#L97) prop (which is user data) is already typed as `any`. It's not far fetched to consider `rowFieldsProps` as user data as well since it will be applied on a user provided component (the developper using this will know what additionnal props are needed for this specific component overload).

Typing this properly would probably require a generic type on the interface (for the custom component props) and something along the lines of `Omit<TCustomComponentProps, keyof IDetailsRowFieldsProps>`.
