### ISSUE TITLE
@fluentui/react-northstar package builds with a different version of Typescript than @uifabric/build

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fluentui#14371]
### Overview
The build gate began failing in the react-northstar project with type errors, and upon investigation @dzearing and @ecraig12345 found that a different version of typescript (3.9.x) was being used to build the package. @ecraig12345 submitted a PR to fix nohoist settings for yarn workspaces assuming that may have been the issue, but the break persisted. After trying several different fixes, I had the idea to add The 3.7.2 version of typescript to the package, and it built successfully. That was addressed in this PR - https://github.com/microsoft/fluentui/pull/14362. 

### Repro steps
As an FYI, only some people were having this repro, but not everyone - similarly, @ecraig12345's PR passed the build, while others have not. 

- Drop TS as a dev dependency from React Northstar + others
- Do a fresh yarn install after clean
- run `yarn buildto @fluentui/react-northstar`
- (hopefully) See the error.

### Environment Information
- **Browser and OS versions**: OS is macOS Catalina

Node Versions tried:

10.20.x
12.12.x
13.x.x

### Priorities and help requested:

*Are you willing to submit a PR to fix? (Yes, No)*
PR noted above - this requires more investigation

*Requested priority: (Blocking, High, Normal, Low)*
I'll leave this to the team to decide, no longer blocking as we've merged a workaround.

**Comment by khmakoto** [comment]
Co-assigning @ecraig12345

**Comment by ecraig12345** [comment]
I completely do not understand yarn's linking strategy here...after trying to remove the overrides and encountering weird behavior, I realized I could do `ls -l node_modules/.bin/tsc`.  The result, with my local changes for the TS upgrade PR (which involved changing some hoisting settings): `../../packages/web-components/node_modules/@microsoft/api-extractor/node_modules/typescript/bin/tsc` 😵😵😵😵😵😵😵 

Workaround is to add a dependency on typescript in the root package.json. This must be done for **any** dep which is invoked via the command line and multiple versions may exist. So a good argument for being quite aggressive about keeping versions in sync and minimizing duplication in yarn.lock.
