### ISSUE TITLE
I can't install @fluentui/react

### ISSUE THREAD

**Issue by gsantosgo** [microsoft/fluentui#14383]
I am trying to install with npm the @fluentui/react package, but I can't install it 

`npm install @fluentui/react`

Result: 

C:\sources\PlantillaSharePoint-ReactApp>npm install @fluentui/react
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@uifabric%2fset-version
- Not found
npm ERR! 404
npm ERR! 404  '@uifabric/set-version@^7.0.19' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404 It was specified as a dependency of '@fluentui/react'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pepe\AppData\Roaming\npm-cache\_logs\2020-08
-06T10_51_29_169Z-debug.log

**Comment by known-as-bmf** [comment]
This is an ongoing issue with scoped packages install on npm side.

**Comment by mahendrakulkarni177** [comment]
kind of the same issue
'@uifabric/react-cards@0.108.1' is not in the npm registry.
any hotfix.

**Comment by xavisegura** [comment]
Same issue here. Do you know where we can follow the npm scoped packages ongoing issue resolution? Thanks!

**Comment by known-as-bmf** [comment]
https://status.npmjs.org/

**Comment by gsantosgo** [comment]
Thanks!! It's already working

**Comment by khmakoto** [comment]
Hey @gsantosgo, thanks for filing this! If it's already working, would you mind closing the issue? Thanks!

**Comment by gsantosgo** [comment]
Done
