### ISSUE TITLE
ContextualMenu - onClick on first layer of menu item

### ISSUE THREAD

**Issue by Lilian1331** [microsoft/fluentui#14380]
### Environment Information

- **Package version(s)**:  Latest
- **Browser and OS versions**: Chrome [Latest Version]

### Describe the issue:

`onClick` is not working on the first layer of menu item once it got the `subMenuProps`.

### Please provide a reproduction of the issue in a codepen:

```
const menuWithOnClickSubMenuProps = [{
	key: 'header1',
	text: 'Menu Item 1',
	onClick: () => alert('parent click'),
	subMenuProps: {
	  items: Array.from({ length: 10 }).map((_, idx) => ({
		key: `item-${idx}`,
		text: `Sub Item ${idx}`,
		data: {
		  index: idx,
		}
	  })),
	  onItemClick: (e, item) => alert(JSON.stringify(item.data))
	}}, 
	{
	key: 'header2',
	text: 'Menu Item 2',
	onClick: () => alert('parent click'),
  }
]

```

![image](https://user-images.githubusercontent.com/23545532/89492468-36cad800-d7e4-11ea-9f19-dc9078dad6fc.png)

#### Actual behavior:

`onClick`not taking effect when I click on the first layer of menu item `Menu Item 1`. 

#### Expected behavior:

`onClick` can adopt to any items of in the Contextual Menu

**Comment by khmakoto** [comment]
Hi @Lilian1331 is my understanding correct in saying that you would want clicking `Menu Item 1` to trigger a call despite it having a submenu?

Thanks!

**Comment by Lilian1331** [comment]
> Hi @Lilian1331 is my understanding correct in saying that you would want clicking `Menu Item 1` to trigger a call despite it having a submenu?
> 
> Thanks!

Ys! @khmakoto May i know is it feasible now?

**Comment by khmakoto** [comment]
I think that we don't allow that kind of behavior by default. @joschect could you confirm this?

**Comment by joschect** [comment]
@khmakoto That is correct. It's not clear in the props but submenu's prevent onclick from being called and this is intended behavior. We do provide an escape hatch/workaround with onMouseDown as seen here in this example https://codepen.io/slimemold/pen/MWyaQMj?editors=0011. Since that is called first you can still handle the click event. @Lilian1331 hopefully that works for your use case!

**Comment by Lilian1331** [comment]
> @khmakoto That is correct. It's not clear in the props but submenu's prevent onclick from being called and this is intended behavior. We do provide an escape hatch/workaround with onMouseDown as seen here in this example https://codepen.io/slimemold/pen/MWyaQMj?editors=0011. Since that is called first you can still handle the click event. @Lilian1331 hopefully that works for your use case!

Ys! It works for me! Thanks!
