### ISSUE TITLE
Required dropdown does not validate when empty

### ISSUE THREAD

**Issue by petriteeri** [microsoft/fluentui#14403]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^7.121.1",
- **Browser and OS versions**: Chrome 84 on macOS (Catalina)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/petriteeri/pen/abNzqKY

Using example code for required dropdown and added a simple form element with a submit button.

#### Actual behavior:

Without selecting an option from the required dropdown the user can submit the form.

#### Expected behavior:

When trying to submit a form without selecting an option in the required dropdown the user should be prompted to select an option and cannot submit the form unless doing so. Similar to other required input elements:

![required](https://user-images.githubusercontent.com/54141349/89642540-4b76a100-d8b4-11ea-801a-fe769f44f005.png)

**Comment by khmakoto** [comment]
@dzearing @joschect what's our story with the `required` property and forms? I think we're not doing anything particular to prevent form submission and we leave that up to the user, right?

**Comment by isabelacmor** [comment]
Another codepen for reference: https://codepen.io/isabelacmor/pen/yLOeJQX

As an end user, Dropdown's required prop should work the same as TextField, ChoiceGroup, etc. None of those component's require additional work on the developer to prevent form submission - they simply block it at the form validation level.

**Comment by khmakoto** [comment]
Ok, so, I think this is happening because the `Dropdown` does not have an input element to which the `required` field is applied. @joschect do you think it would be a good approach to conditionally render an input element that is behind the `Dropdown` when `required` is provided to allow for these scenarios?

**Comment by joschect** [comment]
@khmakoto I'm not sure if it should have an input, but it should definitely have some logic to support the required field being actually required. As for the specifics of a fix this might be a place where @ecraig12345 knows more.

**Comment by ecraig12345** [comment]
I'm not really familiar with this type of issue, sorry.

**Comment by tobybaratta** [comment]
+1 to this issue overall being quite annoying to work around; the errorMessage behavior not being the same for the Dropdown versus the TextField is really annoying to handle and requires some reworking of validation to actually handle whether or not to show the error message. If there is an isRequired, it should be enforced -- or it shouldn't be there at all.
