### ISSUE TITLE
Close button of Messagebar notification is not centrally aligned on focus in IE 11 in normal mode and high contrast mode both .

### ISSUE THREAD

**Issue by v-ajrai** [microsoft/fluentui#14402]
Once we focus on close button of Messagebar notification in IE-11 in high normal mode and high contrast mode,close button is not centrally aligned.

### Environment Information

OS: Win 10
Browser: IE11

### Describe the issue:

Close button of Messagebar notification  should be centrally aligned on focus in IE 11 in normal mode and high contrast mode both .

### Please provide a reproduction of the issue in a codepen:
https://developer.microsoft.com/en-us/fluentui#/controls/web/messagebar
![external 2](https://user-images.githubusercontent.com/62233982/89609811-88339f80-d896-11ea-8bfd-e3a776e6cf40.png)
![external](https://user-images.githubusercontent.com/62233982/89609815-8c5fbd00-d896-11ea-9cbb-2894882f6b20.png)

#### Actual behavior:

Close button of notification is not centrally aligned on focus in IE 11 in normal mode and high contrast mode both

#### Expected behavior:

Close button of Messagebar notification  should be centrally aligned on focus in IE 11 in normal mode and high contrast mode both

**Comment by khmakoto** [comment]
Hi @v-ajrai, thanks for filing this issue! This doesn’t repro on the new Edge Chromium. You can provide your own styling specific to IE 11 to work around this. Since this isn’t a breaking issue for IE 11 and it’s only a minor scenario, we’re not going to address this right now.
