### ISSUE TITLE
DetailsList does not apply onDragEnter styles

### ISSUE THREAD

**Issue by dmitriyyepishin** [microsoft/fluentui#14413]
### Please provide a reproduction of the bug in a codepen:

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/draganddrop

#### Actual behavior:

Styles provided in onDragEnter are not applied in the example on the above page.

**Comment by khmakoto** [comment]
Hi @dmitriyyepishin, I can confirm this is happening.

@cschlechty I've tried to pin down why this is happening with no luck, could you help me a little bit here?
