### ISSUE TITLE
Support Pivot that overflows container

### ISSUE THREAD

**Issue by badsyntax** [microsoft/fluentui#14429]
#### Describe the feature that you would like added

Make the pivot component horizontally scrollable, similar to the DetailsList component. Also, automatically scroll the selected pivot item in view. Here's an example of how it should work:

<img src="https://user-images.githubusercontent.com/102141/89740731-47e54480-da83-11ea-90e9-86cf4c7618df.gif" width="400" />

#### What component or utility would this be added to

[Pivot](https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot)

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Looking at the examples [on this page](https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot), when you make the browser window small, the pivot items are cut off:

<img width="615" alt="Screenshot 2020-08-09 at 20 51 54" src="https://user-images.githubusercontent.com/102141/89740620-3d767b00-da82-11ea-9bb0-3d1065be7ee4.png">

**Comment by paulgildea** [comment]
Thanks for the feedback @badsyntax !

We'll take this feedback into consideration when we start to converge the Pivot control across our two react packages.

Thanks!

**Comment by behowell** [comment]
Hi @badsyntax, the next major release (v8) will have support for a Pivot overflow menu (see #4066). The updated Pivot is also available now in a standalone package `@fluentui/react-tabs`, if you want to try it before v8 is released.

We're also considering adding other types of overflow support including scrolling like you suggested, but they're not planned for the v8 release.

Here's a demo of the overflow functionality: https://codesandbox.io/s/pivot-overflow-menu-demo-grrgg

**Comment by badsyntax** [comment]
Great news, thanks! It looks great. Should this be closed?

**Comment by behowell** [comment]
Yup! I wanted to make sure that the new behavior worked for your needs, since it's different from what you proposed. It sounds like that's the case, so I'll close this.
