### ISSUE TITLE
RadioGroupItem indicator conflicting with the default

### ISSUE THREAD

**Issue by assuncaocharles** [microsoft/fluentui#14434]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.50.0
- **Browser and OS versions**: Chrome

Please provide a reproduction of the bug in a CodeSandBox: https://codesandbox.io/s/goofy-silence-jk6q9?file=/example.js:83-147

#### Actual behavior:

Passing indicator for `RadioGroupItem` both, the default indicator and the custom one, are being shown.

#### Expected behavior:

Only the indicator passed as prop should be rendered. 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by jurokapsiar** [comment]
@assuncaocharles would this work for you? https://codesandbox.io/s/crazy-wilson-o660h?file=/example.js

**Comment by assuncaocharles** [comment]
@jurokapsiar That can works, I just wonder if shouldn't work directly with`indicator: <MyIcon />`
