### ISSUE TITLE
ComboBox responsive mode

### ISSUE THREAD

**Issue by badsyntax** [microsoft/fluentui#14430]
#### Describe the feature that you would like added

I'd like for the ComboBox dropdown to behave like a normal DropDown, in that the dropdown should be a Panel on small screens. (See `responsiveMode` in [DropDown](https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown).) I feel like these two components should be rendered in a consistent way. 

#### What component or utility would this be added to

[ComboBox](https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox)

#### Have you discussed this feature with our team, and if so, who

No

**Comment by paulgildea** [comment]
Thanks for the feedback @badsyntax !

Same as the last feature request you sent in. We'll take this under consideration when we converge our component libraries. I currently don't have any concrete timelines to share, but I'm collecting feedback like this to be leveraged when we start to focus on these components.

Thanks!
