### ISSUE TITLE
UX message style guide for Fluent

### ISSUE THREAD

**Issue by anindyo** [microsoft/fluentui#14444]
#### Describe the feature that you would like added

Currently, there's no UI/UX message style guide available with Fluent to provide clarity on capitalization, spelling etc.

#### What component or utility would this be added to

Web > Styles

#### Have you discussed this feature with our team, and if so, who

No.

**Comment by paulgildea** [comment]
Thanks for the feedback @anindyo !

I've give this feedback back to the design and content team.

**Comment by anindyo** [comment]
Thanks @paulgildea

**Comment by paulgildea** [comment]
I followed up with the design and content team and while we don't have a holistic solution in Fluent today, you can leverage our current guidance here: https://docs.microsoft.com/en-us/style-guide/capitalization

It provides examples of capitalization and casing.

Hope that helps!

**Comment by anindyo** [comment]
Thanks @paulgildea. If Microsoft Style Guide becomes the guiding force for the Fluent UI text and messages, then we can consider this request addressed.....
