### ISSUE TITLE
Way to disable selection of some people in drop-down menu and make them read-only in peoplepicker component

### ISSUE THREAD

**Issue by dikshantbansal98** [microsoft/fluentui#14447]
Thanks for contacting us! We're here to help.

Before you report an issue, check if it's been reported before:

  * Search: https://github.com/microsoft/fluentui/search?type=Issues
  * Search by area or component: https://github.com/microsoft/fluentui/issues/labels

Note that if you do not provide enough information to reproduce the issue, we may not be able to take action on your report.
-->

### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
Hi @dikshantbansal98, it seems like you forgot to fill in our issue template, please fill it in so we can help you!

**Comment by dikshantbansal98** [comment]
There is a peoplePicker component. In the dropdown menu, i want some personas to be read only and not to be able to be selected.
Is there any option to make this happen?
In my drop-down menu, I need some personas not be able to be selected with some information present in the secondaryText like why it can't be selected.

**Comment by joschect** [comment]
@dikshantbansal98 I think that this isn't a bad idea. You can achieve this right now by using the picker as a controlled component where you pass the actual selected items in. That's an extra layer though and it might be nice if we provided a way to do it natively.

**Comment by dikshantbansal98** [comment]
Adding extra layer is not helping at all. Can i know the time by which this feature will be incorporated?

**Comment by nanivijay** [comment]
+1 for the requirement
