### ISSUE TITLE
support hydrate for CSS render

### ISSUE THREAD

**Issue by NewFuture** [microsoft/fluentui#14442]
#### Describe the feature that you would like added

When a  prerendered (or SSRed) webpage renders with `fluent-ui`, the StyleSheets may conflict. 

#### What component or utility would this be added to

`@uifabric/merge-styles`

Supports `hydrate`,  to rehydrate the cache from prerendered CSS (or server-rendered `<style>` elements).

Related link https://fela.js.org/docs/api/fela-dom/rehydrate.html

**Comment by paulgildea** [comment]
Thanks for the feedback @NewFuture !

I'll add this to our backlog. Quick clarification, the link to fela - that is just a reference link as example behavior or is it to support that specific feature of fela?

**Comment by NewFuture** [comment]
@paulgildea
that link is just an example behavior to render with the cache from existing `<style>` elements.
