### ISSUE TITLE
Custom Layout for ContextualMenuItem

### ISSUE THREAD

**Issue by 6etacat** [microsoft/fluentui#14457]
#### Describe the feature that you would like added

Refactor ContextualMenu and add an optional boolean prop to provide a top-down style of the label text and the secondary text to preserve horizontal space. This is needed in the ODSP sharing dialog. 

If an alternative design is not desirable for the component, a refactoring of the component will give us the freedom to modify CSS to achieve our needs. 

#### What component or utility would this be added to

ContextualMenu

#### Have you discussed this feature with our team, and if so, who

I went through it with Jon Schectman but did not go into detail. I will schedule a meeting discussing this on Teams. 

#### Additional context/screenshots

Target looks (achieved modifying ContextualMenu):
![Screenshot_2020-08-08_22-00-04](https://user-images.githubusercontent.com/15188392/89846021-184f3e80-db4e-11ea-8355-36cbede5a57f.png)

Looks after refactoring:
![Screenshot from 2020-08-10 21-13-33](https://user-images.githubusercontent.com/15188392/89846145-68c69c00-db4e-11ea-8599-b1c00f683056.png)

**Comment by paulgildea** [comment]
@joschect - Please ensure that this addition is a non-breaking change for customers
