### ISSUE TITLE
Accessibility Issue with Tooltip ESC key press propagation

### ISSUE THREAD

**Issue by shzalah** [microsoft/fluentui#14465]
### Environment Information

- **Package version(s)**: 16.12.0
- **Browser and OS versions**: Edge, Chrom

### Describe the issue:
When pressing the 'ESC' key in a focused tooltip, that is located in a Dialog, the whole dialog is closed.
The expected behavior is to only close the tooltip (propagate the key press) and close the Dialog on the next 'ESC' key press.

### Please provide a reproduction of the issue in a codepen:
https://codesandbox.io/s/strange-frog-eb6ed?file=/src/App.tsx

#### Actual behavior:
After pressing 'ESC' key to close tool tip, the whole dialog gets closed.

#### Expected behavior:
After pressing 'ESC' key - close the tooltip, and close the Dialog on the next 'ESC' key press.

**Comment by khmakoto** [comment]
Hi @shzalah, thanks for filing this issue! I think this is indeed a bug that we need to fix. I'll try to spin up a PR as soon as possible!
