### ISSUE TITLE
Add a new prop to control the the dismissal of the Dropdown menu

### ISSUE THREAD

**Issue by Github307** [microsoft/fluentui#14468]
#### Describe the feature that you would like added

We are using the multi-select Dropdown component in an iframe embedded in a page. The height of the iframe may vary depending on the values currently selected in the multi-select Dropdown menu. When the multi-select Dropdown menu is open, and due to some selection, the iframe height is resized (similar to window being resized), the Dropdown menu collapses. This does not give a good user experience, since the Dropdown menu collapses every time user makes a selection from the menu, and he has to expand the menu again to make more selections. We would like a new property to be exposed for the Dropdown component through which we can control when to dismiss the Dropdown menu, i.e. the menu should be dismissed when user clicks anywhere outside the menu area.

#### What component or utility would this be added to

Dropdown component

#### Have you discussed this feature with our team, and if so, who

Discussed in ticket [14257](https://github.com/microsoft/fluentui/issues/14257)

**Comment by paulgildea** [comment]
Thanks for the feature request @Github307 !

As stated in the other issue - this will be added to the backlog but I don't have any timelines to share when we'll get to this specific feedback.

@joschect - Do you have any ideas for a workaround?

**Comment by Github307** [comment]
Hi @paulgildea @joschect, are there any updates on this feature request?
