### ISSUE TITLE
icon not visible

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#14502]
### Environment Information

- **Package version(s)**: all
- **Browser and OS versions**:all

### Describe the issue:

the icon `ProtectionCenterLogo32`, when it's font-size is `16px` it not visible properly in dark mode

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/ssarapu/pen/rNexWvO
#### Actual behavior:

the icon is not visible in dark mode properly

#### Expected behavior:

the icon should be visible in dark mode properly

**Comment by paulgildea** [comment]
Thanks for the feedback @shivasai09 !

Visually is this what you are seeing?
![image](https://user-images.githubusercontent.com/33229964/90162729-ef939880-dd49-11ea-9cf9-1b0112a6b7e5.png)

And what version of the library are you using? This is will help us understand if a regression was introduced.

**Comment by shivasai09** [comment]
hi @paulgildea . 
visually i am seeing this
![image](https://user-images.githubusercontent.com/33802398/90211473-65613800-de0e-11ea-8df4-5649ce48c454.png)

the image which you are showing it has larger font-size.

and we are using OFUR pacakage `7.121.2`..

but the codepen which i have provided used the version `7.0.0`

**Comment by khmakoto** [comment]
@shivasai09 can you tell me what the problem is? I don't really gather it from the info that's been provided so far.

**Comment by shivasai09** [comment]
@khmakoto what i am saying is if the icon is 16px in font-size and in dark mode, the icon is not visible properly. but if you increase the font-size like something to 32px then icon is clearly visible. please open the codepen to verify

**Comment by khmakoto** [comment]
A couple of questions:
- Is my understanding correct that you want the default 16px size but that it doesn't look correctly?
- If so, can you define why do you think it is not properly visible? I'm having trouble seeing what's wrong here since the icon seems ok to me.

**Comment by shivasai09** [comment]
@khmakoto 
> Is my understanding correct that you want the default 16px size but that it doesn't look correctly
 
 yes you are correct.

>If so, can you define why do you think it is not properly visible? I'm having trouble seeing what's wrong here since the icon seems ok to me.

the problem is in 16px.  `lock`  symbol  don't have clear  border. it seems to be blurry. if you increase the since the the `lock` symbol look perfect with clear  neat borders

you can close if it is by design. but i feel it shouldn't be. not only this icon, but any icon which have this  type background of color, and if there is something on top of that background that thing is not clearly visible in `16px`. in `dark mode`

**Comment by khmakoto** [comment]
I think this really is by design since you are effectively styling the color of the icon and if you use different colors, like red for example, the lock is clearly visible. This seems to be an issue with color contrast on the user's part more than anything else.
