### ISSUE TITLE
Capability for limited items view in BasePicker with a 'see more' or '...' option

### ISSUE THREAD

**Issue by vishriv** [microsoft/fluentui#14504]
### Environment Information

- **Package version(s)**: 7.24.0
- **Browser and OS versions**: For all browsers and OS

### Describe the issue:

If there are lot of items to show in basepicker, do we have the capability to show 'show more' or '...' after N items(say 20) ? Because if there are around  100+ terms, it will look flooded. ShowMore will load N more items and it will start appearing after those newly loaded items. Or if there is any prop to do that than please correct me

#### Actual behavior:

Currently there is no such prop to handle this. The picker is showing all the items which makes it look pretty crowded

#### Expected behavior:

showmore or .... should appear after configurable number of items(say N). Clicking on that will show N more items and 'showMore' will appear after newly loaded items.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: NA

**Comment by paulgildea** [comment]
Thanks for the feedback @vishriv !

This sounds like more of a feature request than a bug for `Picker` components with lots of entries.

I'll add this to our backlog and we'll use this as input as to start to converge `Picker` experiences across our two libraries. I don't have any timelines to share at this time when we'll get to this work item to set expectations.

Thanks!

**Comment by vishriv** [comment]
Thanks for the update @paulgildea

**Comment by atrex9** [comment]
Hello @paulgildea, is there any update on this? Thank you!
