### ISSUE TITLE
useAutoControlled: when function is passed wrong value will be used

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#14509]
### Environment Information

- **Package version(s)**: `@fluentui/react-bindings`
- **Browser and OS versions**: N/A

CodeSandbox: https://codesandbox.io/s/sharp-resonance-iqyjk?file=/src/App.js

1. Open a CodeSandbox example and open browser's console
2. Click on a header multiple times

#### Actual behavior:

```
App:onClick {prevStateValue: "foo11", value: "bar11"}
App:onClick {prevStateValue: "foo111", value: "bar111"}
```

```jsx
const [value, setValue] = useAutoControlled({
  defaultValue: props.defaultValue,
  value: props.value,

  initialValue: "foo"
});
```

When a function is passed to `setValue()` like in `React.useState`:

```js
setState(prevValue => prevValue + 1)
```

`prevValue` will equal to the `initialValue` 💣 

#### Expected behavior:

```
App:onClick {prevStateValue: "bar11", value: "bar11"}
App:onClick {prevStateValue: "bar111", value: "bar111"}
```

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High
Products/sites affected: N/A

**Comment by paulgildea** [comment]
You've got this one @layershifter ?
