### ISSUE TITLE
Popup with autofocus jumps window scroll

### ISSUE THREAD

**Issue by pompomon** [microsoft/fluentui#14511]
- **Package version(s)**: 0.48+

#### Actual behavior:

Create a Popup with autoFocus content
Open the popup
See window scroll jumps
![PopupJump](https://user-images.githubusercontent.com/2802155/90145475-3dc38e80-dd80-11ea-8cf7-a87fe859fe7d.gif)

#### Expected behavior:

Window scroll doesn't jump

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

### Notes

0.47.3 version is working correctly https://codesandbox.io/s/eloquent-mendeleev-s7b3e
0.48.0 version is not working correctly https://codesandbox.io/s/jolly-dijkstra-2mvw7

**Comment by khmakoto** [comment]
@jurokapsiar fyi

**Comment by pompomon** [comment]
Unfortunately, `autoFocus` is handled by React and triggers before any Popper modifiers (see https://github.com/microsoft/fluentui/pull/14737/files for more context), thus it's not currently possible to prevent those jumps via modifiers. 
Suggested solution is to use `Ref` and set focus explicitly when needed.
