### ISSUE TITLE
Accessibility MacOS - Nested table with Accordion element not getting focus when Mac VO enabled.

### ISSUE THREAD

**Issue by logan12dec** [microsoft/fluentui#14510]
### Environment Information

- **Mac OS Version-10.15.2
- **Safari version-13.0.4

### Describe the issue:

We have a similar table structure as below. When we enabled Mac Safari with VO commands like Ctrl + Option + right /down arrow , able to navigate till thead labels after that entire Anchor tag is skipped and focus goes out of the table.
Example:
<table role="table">
<thead><tr role="row"><th role="columnheader" scope="col">header1</th><th role="columnheader" scope="col">header2</th></tr><thead>
<tbody><a role="presentation "class="expand-collapse">Accordion lable> <table role="presentation"><tbody><tr role="row"><td role="cell">value1</td>
<td role="cell">value2</td></tr></tbody></table></a></table>

#### Actual behavior:

We have a similar table structure as below. When we enabled Mac Safari with VO commands like Ctrl + Option + right /down arrow , able to navigate till thead labels after that entire Anchor tag is skipped and focus goes out of the table.

#### Expected behavior:
Focus should go to the Anchor tag.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@logan12dec Thanks for the issue.

It would be helpful to provide a codesandbox or codepen of your issue to help the team make traction on the issue.

Also could you indicate which version of the component library you are using to help understand to ensure the isn't a regression in the product. 

Thanks!

**Comment by logan12dec** [comment]
Hi Team,

Sorry for the late response. 

Which Fluent UI component is causing the issue - 
Which package name and version the component is from - Using Standard Data table along with react-boostrap Panel component of version 0.31.5 
Specific, complete steps to reproduce the issue - Given in codepen
What behaviors and attributes are missing or incorrect - when Voice over enabled in Mac Safari browser, the accordion is getting skipped when we use ctrl + option + right arrow but the same is working fine when we use Tab/Arrow navigation.
What you expected and what is actually happening - Focus should goto Panel header but currently it is getting skipped.
Confirmation that the problem reproduces in isolation - NA

Code Pen URL::  https://codepen.io/logan12dec/pen/OJNXJBG

Let me know if you need any further information.

Thanks,
Logan

**Comment by jurokapsiar** [comment]
@logan12dec In your codepen you are not using any of the Fluent UI components. Can you please create a sandbox or at least provide code in the comment so that we can see what is implemented? Thanks.

**Comment by jurokapsiar** [comment]
@paulgildea do you know which library/version does this relate to? This does not seem to be known to me: "Using Standard Data table along with react-boostrap Panel component of version 0.31.5"

**Comment by behowell** [comment]
Hi @logan12dec, it looks like @jurokapsiar needs some more info from you to investigate this, could you reply to his earlier comment? Thanks!
