### ISSUE TITLE
Screen reader didn't read out 2 of 5 when focus on each item in DetailsList

### ISSUE THREAD

**Issue by KeiraYang** [microsoft/fluentui#14524]
Repro page:
https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemcolumns

Expected: When focus on each item, screen reader such as Narrator should read out "Row 2 of 5" etc to indicate current item order.

Example which works good:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Grid_Role

**Comment by paulgildea** [comment]
Thanks for the feedback @KeiraYang !

I'm assuming this is for the latest version of the library. Please let us know if it's a different version you are seeing the behavior on. Also which browser are you seeing the behavior in?

This helps us understand if there was recent regression or not.

**Comment by KeiraYang** [comment]
Hi @paulgildea . Sorry for the late response. I'm using the fluentui example page to test which should be the lastest version. As I know, this issue should be there for a long time. Last time I test it at least 1 month ago, I can repro it.

I'm using Edge Chromium + Narrator for testing.

**Comment by khmakoto** [comment]
Related to #15355, so closing this one in favor of that one.
