### ISSUE TITLE
Charting: Area chart Y axis values are not appropriate.

### ISSUE THREAD

**Issue by jameelakowsar** [microsoft/fluentui#14520]
### Environment Information

- **Package version(s)**: Above 2.7.7
- **Browser and OS versions**: All browsers

#### Actual behavior:

Area stacked chart: Chart y axis values are not appropriate with the data given. Y axis range is smaller than total no of y points.
![image](https://user-images.githubusercontent.com/20105532/90220392-bd576900-de25-11ea-8383-de5fdb413a22.png)

### Priorities and help requested:

Requested priority: ( High)

**Comment by paulgildea** [comment]
@Raghurk FYI
