### ISSUE TITLE
Calendar underflow to year -500 and below, engine crash

### ISSUE THREAD

**Issue by LorenzoDeMarco** [microsoft/fluentui#14541]
### Environment Information

- **Package version(s)**: not applicable
- **Browser and OS versions**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.108 Safari/537.36 (Vivaldi Browser)

### Please provide a reproduction of the bug in a codepen:

See https://developer.microsoft.com/en-us/fluentui#/controls/web/calendar

#### Actual behavior:

1. Scroll to the "calendar with year picker" demo
2. Enter the year selection screen
3. Keep clicking ↑ until you see the years go negative
4. Click any year
5. Month view is filled with "NaN" days and the JS engine crashes
![image](https://user-images.githubusercontent.com/33262919/90294098-ec052c00-de85-11ea-9770-f2b9fc073ee2.png)

#### Expected behavior:

Year selection screen should not allow negative years to be selected.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: Any React app using the Calendar control and internal products.

**Comment by khmakoto** [comment]
Hi @LorenzoDeMarco, thanks for filing this! I can confirm the this is indeed happening.

@lorejoh12 what do you think should be the correct thing to do here?

**Comment by lorejoh12** [comment]
I... don't think this is a very common issue. How does someone even find this?

But it's definitely a bug. At worst, even if the rendering is broken and we're showing negative dates, we shouldn't crash on selection. Probably a date math issue happening, so a patch will need to be made for it.

**Comment by LorenzoDeMarco** [comment]
I know this is a very rare edge case and almost no one is going to ever encounter this issue, but I thought it was worth reporting the bug because of the subsequent crash. This may be the sign of a more important bug, maybe (I hope not) hidden deep in the codebase.
