### ISSUE TITLE
need to customize the y-axis descriptor in VerticalBarChart, VerticalStackedBarChart, GroupedVerticalBarChart

### ISSUE THREAD

**Issue by luckyrass** [microsoft/fluentui#14555]
We need a property to customize y-axis descriptor in VerticalBarChart, VerticalStackedBarChart, GroupedVerticalBarChart

#### What component or utility would this be added to

customize y-axis descriptor like what we have in linechart
- VerticalBarChart
- VerticalStackedBarChart
- GroupedVerticalBarChart

  /**
   * this prop takes values that you want the line chart to render on x-axis
   * This is a optional parameter if not specified D3 will decide which values appear on the x-axis for you
   * Please look at https://github.com/d3/d3-scale for more information on how D3 decides what data to appear on the axis of chart
   */
  tickValues?: number[] | Date[];

#### Have you discussed this feature with our team, and if so, who
No

#### Additional context/screenshots
![image](https://user-images.githubusercontent.com/12230173/90383831-459e6e00-e0b3-11ea-82f6-75c9e922149a.png)

**Comment by paulgildea** [comment]
@Raghurk FYI

**Comment by Raghurk** [comment]
I have a bug for this and will triage it
