### ISSUE TITLE
Office ui fabric react button contextual menu item is not dismissed even after item is clicked and user is redirected to href

### ISSUE THREAD

**Issue by mohandivraniya** [microsoft/fluentui#14559]
### Environment Information

- **Package version(s)**: 7.39.2
- **Browser and OS versions**: Windows 10 and Windows server 2016, Chrome 84.0.4147.125 (64 Bit)

### Please provide a reproduction of the bug in a codepen:
Used following example from codepen. However, the issue is: if menu is dismissed, user is not redirected to the url mentioned in href.
https://codepen.io/LukeO/pen/yLYWpMy

#### Actual behavior:

User clicks on the menu item and is redirected to the url mentioned in href. However, the menu is not dismissed and stays open. Menu is dismissed if item doesn't have an href., basically it works if the item click does nothing. 

#### Expected behavior:

When user clicks on the menu item it should be redirected to the url mentioned in href and menu should be dismissed.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low)
High
Products/sites affected: (if applicable)
Multiple solutions and sites

**Comment by paulgildea** [comment]
Thanks for the feedback @mohandivraniya !

**Comment by verdeterrejim** [comment]
I'm experiencing the same issue.  Have worked around it for now by using "document.body.click()" in the onItemClicked event for the menu item.  That will cause the menu callouts to be dismissed.

**Comment by khmakoto** [comment]
@joschect what do you think is happening here?

**Comment by joschect** [comment]
It looks like this is intentional. We updated our docs to make it clear that this does not work if dismissing from a button or command bar: 
![image](https://user-images.githubusercontent.com/20801176/111829811-6a0d3380-88aa-11eb-9ef2-87310c56e876.png)
