### ISSUE TITLE
Tooltip component does not resize when the window becomes smaller

### ISSUE THREAD

**Issue by DaniloAG** [microsoft/fluentui#14575]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: Edge Chromium and Windows 10 Version 1909

### Please provide a reproduction of the bug in a codepen:
[https://codepen.io/daniloag/pen/XWdKzVK](https://codepen.io/daniloag/pen/XWdKzVK)

- Change the editor layout view to either view that sets the text editors vertically.
- Drag the text editors in the direction that will make the button smaller.
- Hover over the button and observe tooltip not resizing.

#### Actual behavior:

The tooltip does not resize, so it spills outside of the window.

#### Expected behavior:

The tooltip to resize so we could see all the content.

**Comment by khmakoto** [comment]
Hi @DaniloAG, thanks for filing this issue! I can confirm that this is happening and will look into a solution as soon as possible.
