### ISSUE TITLE
Please add an option to choose the tag of button

### ISSUE THREAD

**Issue by hrazmsft** [microsoft/fluentui#14588]
#### Describe the feature that you would like added

Allowing the developer to choose the buttons tag. 

#### What component or utility would this be added to

DefaultButton, PrimaryButton

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Currently buttons renders as `button` or `a` (if `href` prop is defined). Sometimes it needed to be set as different type like `span`. Like when the button should act like a label, for example:

```
<input
  className={classes.displayNone}
  id='upload-button-file'
  type='file'
  />
<label htmlFor='upload-button-file'>
  <DefaultButton>Upload</DefaultButton>
</label>
```

**Comment by khmakoto** [comment]
Hi @hraz-msft, thanks for filing this issue! We're currently on the process of revamping our button and this is one of the things that we're looking into. I'll add it into the backlog for now but do know that we're looking into this.

**Comment by hrazmsft** [comment]
@khmakoto why this item has closed?

**Comment by khmakoto** [comment]
@hrazmsft like the bot says in the comment above, the issue was closed because it hasn't had any activity for over 150 days for house-keeping purposes. Feel free to re-open the issue with up-to date details though!

**Comment by hrazmsft** [comment]
@khmakoto I thought this item is in your backlog and you are going to implement it... I've been waiting for the implementation...

**Comment by khmakoto** [comment]
@hrazmsft I can assure you that we've been working on something to alleviate this issue, so it's not fallen of the sidelines. The bot rules, however, have closed this issue because of the reasons stated above. As said before, feel free to re-open the issue.

Thanks!

**Comment by hrazmsft** [comment]
@khmakoto it seems that I can't reopen it unless I recreate it (maybe you can reopen).

I hope to see this feature implement soon!

Thabk you!

**Comment by khmakoto** [comment]
@hrazmsft I've reopened the issue for now. Hopefully that helps! Thanks!
