### ISSUE TITLE
DatePicker hides GoToToday when start of week is Monday or Sunday

### ISSUE THREAD

**Issue by magnusdanielson** [microsoft/fluentui#14583]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Chrome 84 Windows 10 

### Please provide a reproduction of the bug in a codepen: 
https://codepen.io/magnusdanielson/pen/gOrMQRK?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

#### Actual behavior:

When Monday or Sunday is selected as start of the week the GoTo today button is behind the calendar table

#### Expected behavior:

When any day is selected as start of the week, the GoTo today button should be clearly visible

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Customer applications

**Comment by khmakoto** [comment]
Hi @magnusdanielson, thanks for filing this issue! I can confirm that this is indeed happening! I want to note though that this happens not because you select `Sunday` or `Monday` at the start of the week but because the month spans 6 weeks in the calendar due to that choice.

**Comment by khmakoto** [comment]
@lorejoh12 FYI.

**Comment by magnusdanielson** [comment]
Any news on this?

If I add below css it looks ok.

  ```
 /* add room for GoToday-button */
 .ms-DatePicker-wrap
   {
      min-height: 245px !important;
   }

/* make sure the button is aligned to bottom */
   .ms-DatePicker-goToday
   {
     top: auto;
   }
```
