### ISSUE TITLE
Theme Designer is broken in Fluent UI and Office UI Fabric 6 for SharePoint

### ISSUE THREAD

**Issue by StfBauer** [microsoft/fluentui#14581]
### Environment Information
All of them

### Description
[Theme Designer for Office UI Fabric 5](https://developer.microsoft.com/en-us/fluentui#/styles/themegenerator#Overview) supports background color through the property `primaryBackground`. This theme generator is used to provide custom themes in SharePoint Online.

```powershell
@{
"themePrimary" = "#0078d4";
"themeLighterAlt" = "#eff6fc";
"themeLighter" = "#deecf9";
"themeLight" = "#c7e0f4";
"themeTertiary" = "#71afe5";
"themeSecondary" = "#2b88d8";
"themeDarkAlt" = "#106ebe";
"themeDark" = "#005a9e";
"themeDarker" = "#004578";
"neutralLighterAlt" = "#f8f8f8";
"neutralLighter" = "#f4f4f4";
"neutralLight" = "#eaeaea";
"neutralQuaternaryAlt" = "#dadada";
"neutralQuaternary" = "#d0d0d0";
"neutralTertiaryAlt" = "#c8c8c8";
"neutralTertiary" = "#c2c2c2";
"neutralSecondary" = "#858585";
"neutralPrimaryAlt" = "#4b4b4b";
"neutralPrimary" = "#333333";
"neutralDark" = "#272727";
"black" = "#1d1d1d";
"white" = "#ffffff";
"primaryBackground" = "#ffffff";
"primaryText" = "#333333";
"bodyBackground" = "#ffffff";
"bodyText" = "#333333";
"disabledBackground" = "#f4f4f4";
"disabledText" = "#c8c8c8";
}
```

In newer versions [Office UI Fabric 6 and Fluent UI](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/index.html) some of the required properties do not exist anymore. Especially the bodyBackground don't allow the customer to define a specific background for the overall page.

```powershell
@{
"themePrimary" = "#0078d4";
"themeLighterAlt" = "#eff6fc";
"themeLighter" = "#deecf9";
"themeLight" = "#c7e0f4";
"themeTertiary" = "#71afe5";
"themeSecondary" = "#2b88d8";
"themeDarkAlt" = "#106ebe";
"themeDark" = "#005a9e";
"themeDarker" = "#004578";
"neutralLighterAlt" = "#00f800";
"neutralLighter" = "#00f400";
"neutralLight" = "#00ea00";
"neutralQuaternaryAlt" = "#00da00";
"neutralQuaternary" = "#00d000";
"neutralTertiaryAlt" = "#00c800";
"neutralTertiary" = "#a19f9d";
"neutralSecondary" = "#605e5c";
"neutralPrimaryAlt" = "#3b3a39";
"neutralPrimary" = "#323130";
"neutralDark" = "#201f1e";
"black" = "#000000";
"white" = "#00ff00";
}
```

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: SharePoint in General

**Comment by khmakoto** [comment]
Hi @StfBauer, while `bodyBackground` does not exist as a `palette` color anymore, it does exist as a `semanticColor` that you can also access via the theme:

https://github.com/microsoft/fluentui/blob/ab168f6af25c5fd601671ef93d95e89084f16e32/packages/styling/src/interfaces/ISemanticColors.ts#L73

**Comment by StfBauer** [comment]
As if SharePoint would care what you define in the semanticColor slot. You break an existing and working system just because you can? Really? Not that the theme designer only allows picking three colours.

<img width="425" alt="Screenshot 2020-08-19 at 11 26 23" src="https://user-images.githubusercontent.com/5503835/90617436-f8cfaa00-e20e-11ea-8d89-668bb82eed6a.png">

How do you think it would be possible to have a background color otherwise? I need to write an override with CSS through and deploy it to SharePoint in a way like this?

```css
body{
   background-color: magenta;
} 
```

**Comment by khmakoto** [comment]
From what I can see in the theme designer, the `white` value in the palette is what's taking the value of the background color you choose there: 

![image](https://user-images.githubusercontent.com/7798177/90677513-51547680-e212-11ea-932b-400ee6410bd5.png)

I hope that helps with your issue!

**Comment by StfBauer** [comment]
Not really cause with a background applied to SharePoint it completely mess up the design of SharePoint like this.
<img width="1418" alt="Screenshot 2020-08-19 at 12 02 37 copy" src="https://user-images.githubusercontent.com/5503835/90681623-f9def680-e263-11ea-9a77-7a080b921f24.png">

and that is just an extreme case but it doesn't work when for example a light blue gets added as a background.

**Comment by khmakoto** [comment]
Cc'ing @aneeshack4 since she worked on the Theme Designer to see if she can help here.

**Comment by aneeshack4** [comment]
@StfBauer What exactly are you trying to do? Can you please describe your use case for the theme designer clearly? Repro steps will help us.

**Comment by StfBauer** [comment]
1. Create a theme that can be used in SharePoint Online - Fails
2. Create a theme that uses a custom background color that only affects the background in a defined slot for SharePoint Online because it should only affect the background - Fails
3. Steps to reproduce
* https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview

**Comment by khmakoto** [comment]
@aneeshack4 gentle ping here since @StfBauer replied to your question.

**Comment by khmakoto** [comment]
Related to #15355, so closing this one in favor of that one.
