### ISSUE TITLE
[GroupedList] Expand / collapse on sub-groups not working anymore

### ISSUE THREAD

**Issue by known-as-bmf** [microsoft/fluentui#14589]
### Environment Information

- **Package version(s)**: latest (7.128.3)
- **Browser and OS versions**: -

### Please provide a reproduction of the bug in a codepen:

The official examples showcase the bug https://developer.microsoft.com/fr-fr/fluentui#/controls/web/groupedlist

#### Actual behavior:

In the basic example, when trying to collapse a "sub-group" (e.g. `group 0-0`), the styles of the header are updated properly but the group isn't actually collapsed.

The issue is not present on the "root" groups (e.g. `group 0`).

#### Expected behavior:

Be able to collapse / expand all groups, regardless of their nesting.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: -

**Comment by khmakoto** [comment]
Hi @known-as-bmf, thanks for filing this issue! I can confirm that this is indeed happening and will look into it as soon as possible.

**Comment by DavidUM** [comment]
Hi @khmakoto  
I am also facing this issue. More preciously it is working slowly. Very slowly.
Collapsing or Expanding action occurs after 10 or more seconds.

**Comment by JustSlone** [comment]
Btw, here's a repro for folks to see the issues. For me the UI never updated even if I waited a very long time. I'm guessing the 10 second delay is to some other render occurring, for instance a page scroll will cause the update. 

![groupListRepro](https://user-images.githubusercontent.com/40304143/93631753-fe044e00-f9a0-11ea-855c-78330e797ca4.gif)

**Comment by dzearing** [comment]
7.124.3 is the last build to work, and was introduced in 7.125.0.

@micahgodbolt might have been introduced in this PR:

https://github.com/microsoft/fluentui/pull/14283/files

**Comment by khmakoto** [comment]
I think the culprit might be [this other PR](https://github.com/microsoft/fluentui/pull/14342/files) actually.

**Comment by micahgodbolt** [comment]
oh yeah...now I remember this issue....it WAS the string refs


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
