### ISSUE TITLE
Deprecate useConstCallback

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#14580]
`useConstCallback` in `@uifabric/react-hooks` was intended for creating callbacks which have no dependencies, and therefore never need to change. It works fine if everyone using it is extremely mindful of how closures work...but that's not a good assumption, so in practice you can easily end up doing things like unintentionally capturing the first value of a prop and not respecting updates (where updates should be respected). There have already been bugs of this type in some function component conversions, so best to deprecate it now so we don't keep hitting this.

cc @dzearing

**Comment by dzearing** [comment]
Agree; it's too easy to abuse. Thanks for doing this!
