### ISSUE TITLE
Provide control on animation speed of the Loader component

### ISSUE THREAD

**Issue by bansalrachita** [microsoft/fluentui#14595]
#### Describe the feature that you would like added

Loader component should have way to control (reduce) the speed of the spinner. 

Allows the developer control over visual feel of the loader, helps in creating loader with more subtle and less busy animation -
useful when the page takes a long time to load/perform an action and the spinner exists for a long time in the visual sight of the user.

#### What component or utility would this be added to

Fluenui/northstar Loader component.

#### Have you discussed this feature with our team, and if so, who

N/A

**Comment by jurokapsiar** [comment]
Discussed with design team who owns the theme - it is not intended to allow changing the loader speed in the theme. You can always check the theming guides in the documentation and provide style overrides to modify the theme.
