### ISSUE TITLE
Consider recategorizing packages for @uifabric/react-cards

### ISSUE THREAD

**Issue by MichaelRechenberg** [microsoft/fluentui#14605]
#### Describe the feature that you would like added

I'm asking the Fabric team to consider the following changes/questions for dependencies in the @uifabric/react-cards package.

- Move `office-ui-fabric-react` to a peerDependency.  This can help us have just one version of Fabric in our project
- If we're already importing office-ui-fabric-react in @uifabric/react-cards then can some of the @uifabric/* imports be replaced with imports from the fabric directly, so we can further reduce the dependencies?
- Can @uifabric/azure-themes and @uifabric/theme-samples be removed as dependencies (maybe put in optional or dev dependencies instead?) As far as I know they are used only a demo capacity

#### What component or utility would this be added to

@uifabric/react-cards package

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

N/A

**Comment by paulgildea** [comment]
@MichaelRechenberg Thanks for the feature request.

@dzearing as FYI.

We are updating our package structure for the next release. While we might not cover these specific refactorings we're opting to allow developers more granular choices on package imports. I don't have any specific timelines to share at this time, but we'll take this into consideration during restructuring.

I'm going to resolve this issue as a non-issue, but here's a link to some of the work we're planning in the packaging space
https://github.com/microsoft/fluentui/projects/36#column-10399097

Hope that helps.

**Comment by dzearing** [comment]
@khmakoto can you look at these?

**Comment by dzearing** [comment]
I think these are great points and mostly easy to tweak.

**Comment by khmakoto** [comment]
@dzearing Yeah, I think these should be easy.

**Comment by khmakoto** [comment]
Hi @MichaelRechenberg. I've done the changes in the PR above. However, I've backed off of moving `office-ui-fabric-react` to `peerDependencies` since we don't do that for any other package. If it's causing duplicated versions for you there should be a way to resolve it by fiddling with your dependency versions. Could you provide me more details on the issue you're facing and the versions of `office-ui-fabric-react` and `@uifabric/react-cards` that you use?
