### ISSUE TITLE
Example from GroupedList document cannot be compiled

### ISSUE THREAD

**Issue by ytingyeu** [microsoft/fluentui#14604]
### Environment Information

- **Package version(s)**: "
"@fluentui/react": "^7.128.1
"typescript": "~3.7.2"

### Please provide a reproduction of the bug in a codepen:
[exmpale](https://codepen.io/ytingyeu/pen/rNeMOWN)
Note: this example is taken from [documentation](https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist)

The error is not visible on codepen. One has to test this locally where typescript strictFunctionTypes is applied

#### Actual behavior:
Typescript compiler argues a type error. Set tsconfig `strictFunctionTypes` to false can bypass this error

```
Type '(nestingDepth: number, item: IExampleItem, itemIndex: number) => JSX.Element' is not assignable to type '(nestingDepth?: number | undefined, item?: any, index?: number | undefined) => ReactNode'.
  Types of parameters 'nestingDepth' and 'nestingDepth' are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.ts(2322)
GroupedList.types.d.ts(77, 5): The expected type comes from property 'onRenderCell' which is declared here on type 'IntrinsicAttributes & IGroupedListProps & { children?: ReactNode; }'
```

#### Expected behavior:
Should have no error

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by paulgildea** [comment]
@ytingyeu Thanks for the issue!

Sounds like the this only happens with a specific `tsconfig`

@khmakoto - Will be interesting to see if we've supported this config in the past or if this is a recent regression.

**Comment by khmakoto** [comment]
I talked with Elizabeth, we have not supported that in the past, though it does not seem that hard to fix. I'll check it out.

**Comment by khmakoto** [comment]
@ytingyeu I've sent a PR addressing the issues pertaining the examples specifically.
