### ISSUE TITLE
Inaccessible split button menu via keyboard 

### ISSUE THREAD

**Issue by ipip2005** [microsoft/fluentui#14602]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: chrome. Window 10.

### Describe the issue:

The split sub button cannot be focused when it's in command bar making the options in split button menu inaccessible.

1. Go to Button demo page, go to Split Button section.
2. Focus on any split button
3. Try to open the menu

#### Actual behavior:
Cannot open the menu. Press enter will trigger the button behavior
#### Expected behavior:
Either I can focus on the split button and press enter to trigger the menu, or have some other ways to open it like down arrow key.

### Priorities and help requested (not applicable if asking question):

Requested priority: Normal

Products/sites affected: SharePoint modern page authoring.

**Comment by khmakoto** [comment]
Hi @ipip2005, this is by design. You can trigger the `SplitButton` menu by doing the aria expected keyboard combination `Alt + Down`.
