### ISSUE TITLE
No overflow mechanism for MessageBar with buttons

### ISSUE THREAD

**Issue by anzaremb** [microsoft/fluentui#14609]
### Environment Information

- **Package version(s)**: (?)
- **Browser and OS versions**: (Chrome on Windows)

### Describe the issue:

Version of the MessageBar with buttons doesn't have an overflow mechanism in zoom scenarios / small responsive breakpoints. 

#### Actual behavior:

Text is cut by the buttons. Example: success message on this page

#### Expected behavior:

There is an overflow button as in other types of MessageBars

### Documentation describing expected behavior

Refer to the example of blocked message example that has the overflow button: https://developer.microsoft.com/en-us/fluentui#/controls/web/messagebar

**Comment by paulgildea** [comment]
@anzaremb Thanks for the feedback!

I'm inclined to resolve this as by Design as we don't provide overflow by default.

@khmakoto - Do you have any suggestions for a workaround that allow customization for overflow?

**Comment by anzaremb** [comment]
Hello Paul,

Thanks for getting back to me.
we have spec proposal for button reflow so they would be a part of the content in an overflow scenario:

[cid:a2aeb34e-891a-4bfd-b5bb-2749701ac994]

Is that something we could implement as a solution to this?

Thanks,
Anna
________________________________

**Comment by khmakoto** [comment]
Hi @anzaremb, you can always set the `isMultiline` prop to `true` so that text is not truncated. Let me know if this helps you!

**Comment by anzaremb** [comment]
hey Makoto,

Thanks for the answer.

We are only implementing the truncated version for all message bars so it doesn't overtake the screen in zoomed scenarios. That is why we need the truncated version for both buttons and text only scenarios.


Anna

________________________________
