### ISSUE TITLE
DatePicker - No proper state is announced for the current day

### ISSUE THREAD

**Issue by yanbxice** [microsoft/fluentui#14611]
### Environment Information

- **Package version(s)**: 7.121.4
- **Browser and OS versions**: Edge

### Describe the issue:

When screen reader users navigate to the present day, visually it is displayed using the background color but the same information is not conveyed to the screen reader users.

### Please provide a reproduction of the issue in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/7.121.4/#/examples/datepicker

#### Actual behavior:

screen reader reads the current date the same as the other dates.

#### Expected behavior:

screen reader should convey the information to users that it is the current day.

**Comment by paulgildea** [comment]
@smhigley FYI.

@lorejoh12 FYI - Not sure if this has addressed in other patterns.

**Comment by smhigley** [comment]
Could be solved with `aria-current="date"` on the button

**Comment by yanbxice** [comment]
@smhigley which button do you mean to add aria-current attribute? Looks like I can't access any button in datepicker.
