### ISSUE TITLE
Add yAxisTickFormat to VerticalStackedBarChart

### ISSUE THREAD

**Issue by mbest** [microsoft/fluentui#14618]
#### Describe the feature that you would like added

We need to be able to format the y-axis data. In our case, the data is minutes, which we'll format as something like "1 h 10 min". This should also format the value in the call-out.

#### What component or utility would this be added to

VerticalStackedBarChart

**Comment by khmakoto** [comment]
@Raghurk FYI

**Comment by mbest** [comment]
Fixed in #14830
