### ISSUE TITLE
Charting: Overlapping of x axis labels in vertical bar chart and stacked vertical bar chart.

### ISSUE THREAD

**Issue by jameelakowsar** [microsoft/fluentui#14619]
### Environment Information

- **Package version(s)**: All versions
- **Browser and OS versions**: All browsers

#### Expected behavior:

When we have large test at  axis tick values, all those values are overlapping with another. 
These values need to truncated and need to show a tooltip to display whole word. 
Otherwise, We need to show whole tick value by wrapping the word.

This issue repro'ing in all other cartesian charts.

**Comment by khmakoto** [comment]
@Raghurk FYI
