### ISSUE TITLE
CI: build should be stopped/cancelled on task fail

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#14627]
Build: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=110641&view=logs&jobId=258ec178-2d8b-5611-7b9b-60c5c95dae55&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=3dbc0aa8-94d2-5f1a-6c00-c4086d74d6b7

For some reason "do syncpack and no-tslint checks" stage fails build but next steps are still running:
![image](https://user-images.githubusercontent.com/14183168/90769241-32c4ad00-e2f0-11ea-9b8e-1f636f600f05.png)

@ecraig12345 @kenotron Can we cancel build if "do syncpack and no-tslint checks" step failed?

**Comment by ecraig12345** [comment]
There's probably a way to configure this in the pipeline yaml definition, but I don't remember what it is offhand.
