### ISSUE TITLE
"is exported at top-level" in sharedIsConformant test is failing when checkout folder is in `src` folder

### ISSUE THREAD

**Issue by pompomon** [microsoft/fluentui#14623]
### Environment Information

- **Package version(s)**: recent `master`, 0.51. FluentUI v0
- **Browser and OS versions**: MacOS 10.15.6

### Please provide a reproduction of the bug in a codepen:

Checkout repo to a folder with has `/src/` in the path, e.g. /Users/rs/src/fluentui/
Run `yarn` and `yarn build`
then
Go to `/packages/fluentui/react-northstar/`
Run `yarn test`
or 
Go to `/packages/office-ui-fabric-react/`
Run `yarn test`
#### Actual behavior:

``` FAIL  test/specs/components/Menu/MenuItem-test.tsx (11.944s)
  ● MenuItem › is exported at top-level

    Cannot find module '/Users/rs/src/index' from 'defaultTests.tsx'

      83 |         const { displayName, componentPath, Component } = testInfo;
      84 |         const rootPath = componentPath.replace(/[\\/]src[\\/].*/, '');
    > 85 |         const indexFile = require(path.join(rootPath, 'src', 'index'));
         |                           ^
      86 | 
      87 |         expect(indexFile[displayName]).toBe(Component);
      88 |       });

      at Resolver.resolveModule (../../../node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (../../react-conformance/src/defaultTests.tsx:85:27)
```

or

```● Slider › has corresponding top-level file 'package/src/Component'

    Cannot find module '/Users/rs/src/Slider' from 'defaultTests.js'

       96 |         const { displayName, componentPath, Component } = testInfo;
       97 |         const rootPath = componentPath.replace(/[\\/]src[\\/].*/, '');
    >  98 |         const topLevelFile = require(path.join(rootPath, 'src', displayName));
          |                              ^
       99 | 
      100 |         expect(topLevelFile[displayName]).toBe(Component);
      101 |       });

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (../react-conformance/src/defaultTests.tsx:98:30)
```

#### Expected behavior:

isSharedConformant test passes

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

**Comment by pompomon** [comment]
@ecraig12345 , please I believe the issue happens because we are doing `replace` in `packages/react-conformance/src/defaultTests.tsx:'exported-top-level'`, based on "/src/" string
```  'exported-top-level': (componentInfo: ComponentDoc, testInfo: IsConformantOptions) => {
    if (!testInfo.isInternal) {
      it(`is exported at top-level`, () => {
        const { displayName, componentPath, Component } = testInfo;
        const rootPath = componentPath.replace(/[\\/]src[\\/].*/, '');
        const indexFile = require(path.join(rootPath, 'src', 'index'));

        expect(indexFile[displayName]).toBe(Component);
      });
    }
  },
```

**Comment by ecraig12345** [comment]
When we wrote that code we didn't expect that people would call their Git repo parent folder `src`. If you don't want to rename the folder, we could potentially change the regex to only match the last instance of `src`, but I'm not sure offhand how to make a regex do that.

**Comment by ecraig12345** [comment]
This would work, but it's convoluted and I'd really rather not have to modify the regex this way. `/(?:[\\/]src[\\/].*?)?([\\/]src[\\/].*)$/`

Another possible approach might be to split up the path based on the Git repo root, and only replace src in the root-relative part, but that would also be more convoluted.

**Comment by pompomon** [comment]
Yeah, I'll probably just rename my path for now :) 
I'll try to think of some other ways to solve that as well and maybe ping you later :) 
Thanks for the quick response @ecraig12345 !
