### ISSUE TITLE
Charting: X axis labels wrapping not supporting to the IE11

### ISSUE THREAD

**Issue by jameelakowsar** [microsoft/fluentui#14626]
# Environment Information

- **Package version(s)**: Above 3.0.7
- **Browser and OS versions**: IE browser

#### Actual behavior:

In IE11 - when grouped vertical bar chart page opened, page getting crashed. X axis labels wrap is not working.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
@Raghurk FYI
