### ISSUE TITLE
Element couldn't set scroll in Modal

### ISSUE THREAD

**Issue by Lijiaoa** [microsoft/fluentui#14635]
I use fabric version as `"office-ui-fabric-react": "^7.78.0",`. When I use `Modal` component, I find that when I set Modal width is `50%`，The width of the element in Modal is more than 50%! I add scroll bar but it doesn't help. 

expected: could set scroll bar for element in Modal.

**Comment by paulgildea** [comment]
@Lijiaoa Thanks for the feedback.

Could you supply a codepen that replicates the issue you are seeing because that will help us determine if it's a recent regression or not. 

Thanks!

**Comment by Lijiaoa** [comment]
> @Lijiaoa Thanks for the feedback.
> 
> Could you supply a codepen that replicates the issue you are seeing because that will help us determine if it's a recent regression or not.
> 
> Thanks!

Ok. will update late.

**Comment by paulgildea** [comment]
Waiting on codepen.
