### ISSUE TITLE
CI: should run Prettier to detect formatting issues

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#14632]
Currently there is no job that will run prettier formatting in CI. 

This allows files with broken formatting (as an example https://github.com/microsoft/fluentui/pull/14625) to pass CI checks and then these changes will come to `master`. Once anyone will merge with `master` there will be unrelated formatting changes (https://github.com/microsoft/fluentui/pull/14441#discussion_r467878616).

**Comment by paulgildea** [comment]
@ecraig12345 FYI

**Comment by ecraig12345** [comment]
I agree this would be nice, though the trick is we should ideally only run prettier on files that are modified in the PR. I'm sure there's a way to detect that but not sure what it is offhand.

**Comment by Hotell** [comment]
From my experience, having fundamental things like automated formatting and checks on ci is a must. I'd suggest to start simple

- add `prettier --check` on whole repo 
  - > whoa that is gonna be slow ! Not really prettier is extremely fast. it took up to 5 seconds on 5k+ js modules in my previous project.
- run those checks only on affected project ( no idea if lage is able to do that )
- provide opt in functionality to be able to run those checks only on touched files

**Comment by Hotell** [comment]
Resolved by #16446 #16476

**Comment by layershifter** [comment]
@Hotell this does not work, I just merged `master` in 34d9e960a344a59f4551b8c68d94427481a31935, now I have changes in `rfcs/converged-implementation-patterns.md`, see #16964.

**Comment by Hotell** [comment]
TBH this is not a very helpful  "issue report". Can you be more specific next time please ?

I investigated what might have happened and it indeed DOES work. 

Overall problem is with lot of unnecessary abstraction that we use for fundamental stuff (like running prettier). In this case process will not exit properly (which would if we ran `prettier` directly).

https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=184417&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=072a33dd-3583-57e6-ff95-c892c0923c97
![image](https://user-images.githubusercontent.com/1223799/107933245-c5cc6000-6f7e-11eb-9b67-6064b0a709b9.png)

PRs are welcome.

thx

**Comment by Hotell** [comment]
unhandled rejection Fixed by https://github.com/microsoft/fluentui/pull/17009

**Comment by ecraig12345** [comment]
> Overall problem is with lot of unnecessary abstraction that we use for fundamental stuff (like running prettier).

Maybe true in some cases but not this one: as far as I can tell, prettier doesn't provide an out of box option to run only on files that changed in the current branch. And running prettier on all the files is unnecessarily time-consuming (3 minutes on my computer, which isn't the exact same as CI but gives a general idea).

**Comment by Hotell** [comment]
> And running prettier on all the files is unnecessarily time-consuming 

This repo has far more concerning issues than running prettier on whole codebase
