### ISSUE TITLE
Add compat docs to website

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#14638]
We need to add a section in the website's controls list for compat controls.

Easiest approach is probably to do it based on a set of new `{@docCategory}` tags, like `{@docCategory CompatButton}`, and update `apps/fabric-website/src/SiteDefinition/SiteDefinition.pages/Controls/web.tsx` to group those in a "Compat" section.

We should also consider how to explain the purpose of the compat controls, differences/similarities with regular ones (code and visual), etc.

**Comment by ecraig12345** [comment]
Realized we'll also need compat docs for Calendar and DatePicker, since we'll be exporting the date-time ones by default and moving the OUFR ones under compat.

**Comment by khmakoto** [comment]
Closing since compat docs are no longer the approach we're taking for now.
