### ISSUE TITLE
Narrator: Dialog close button not localized in Simplified Chinese

### ISSUE THREAD

**Issue by shahzebasif** [microsoft/fluentui#14646]
#### Repro:

https://codepen.io/shahzebasif/pen/BaKQLKM

#### Actual behavior:

Narrator says "close" in English even if the Windows language is Simplified Chinese.

#### Expected behavior:

Narrator should localize the close button to the system language.

**Comment by khmakoto** [comment]
Hi @shahzebasif, the `aria-label` provided by default is not localized as we do not ensure localization ourselves, that's up to the users of our components. You can customize this behavior by using the `closeButtonAriaLabel` prop inside `dialogContentProps` as shown [in this codepen](https://codepen.io/khmakoto/pen/oNYKvQy?editors=0010).

Let us know if there is anything else we can do to help!
