### ISSUE TITLE
ThemeProvider work for v8 release

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#14661]
(copied from v8 scope doc--edit as needed)

- [x] support passing through v7 theme
- [x] v7 -> v8 theme conversion for button
- [x] support scoped customizations - theme.scopedSettings or theme.components is forwarded to Customizer scoped settings
- [x] support `applyToBody`
~~- [ ] support passing through v0 theme~~(de-prioritize: not needed for V8 release)

Post-snap/pre-beta work: #14740

**Comment by xugao** [comment]
closing this one and tracking the remaining work in #14740
