### ISSUE TITLE
Flight button in Ribbon

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#14666]
Remainders for Ribbon work:

- [ ] Enable flight in dogfood
- [ ] Test high contrast mode changes we made
- [ ] Integrate latest bits after IE11 changes are in
- [ ] Add back KeyTips and Tooltips support
- [x] MLR styling

In parallel we are also adding flamegrill tests for Ribbon with both old and new button

**Comment by dzearing** [comment]
PR is currently being driven on WAC side.

**Comment by dzearing** [comment]
All merged, waiting on deployment with Excel.

**Comment by khmakoto** [comment]
Folding into #16746.
