### ISSUE TITLE
Implement commandbar button

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#14672]
Need to implement CommandBarButton in react-button package

- [ ] Change styling to use css variables
- [ ] Use CommandBarButton from react-button in CommandBar

**Comment by ecraig12345** [comment]
@tomi-msft Reminder to fill in details for this issue

**Comment by hadnet** [comment]
Any update on this?

**Comment by tomi-msft** [comment]
We have decided to implement the Commandbar Button using Ghost Button variants instead
