### ISSUE TITLE
Verify all changes to OUFR have been ported to react-next

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#14675]
- [ ] For converted function components, look at:
  - When it was copied to react-next
  - Whether any changes were made to the component in OUFR since then
  - If so, ensure the changes are included in react-next FC version
- [x] Ensure doc text changes have been ported, OR just delete the react-next copies (this refers to `react-next/src/components/<Component>/docs/*.md`)

**Comment by czearing** [comment]
I created a HackMD with a list of react-next components and the possible changes that will need to be ported from office-ui-fabric-react: https://hackmd.io/LQEZYG2cSoGYgm9u-wvDag?both

**Comment by JustSlone** [comment]
Nice, thanks @czearing!

Are you on point to port these changes over to react-next?

**Comment by czearing** [comment]
Yes, I am currently working on making sure everything is ported over. I will keep the hack md updated to track progress.

**Comment by ecraig12345** [comment]
Thanks for looking through that! I should have mentioned before, it would probably also be good to check for changes made within the couple weeks *before* the copy date of a component. In a few cases the PRs were open for awhile and some changes may have been made after the initial copy the PR was based on, but before merge.
