### ISSUE TITLE
Use new button in existing use cases within our repo (e.g. commandbar)

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#14673]
Below is the list I have of components that use old button, and need to be replaced with new button. This is just components for now, but will add examples as well later on.

- [x] Breadcrumb
- [ ] ComboBox
- [ ] CommandBar
- [x] DialogContent
- [ ] Dropdown (react-northstar)
- [x] Nav
- [x] Pivot
- [x] Searchbox
- [x] SpinButton

This is made more difficult because several components also expose `IButtonProps` in their types (so switching to new Button would be a breaking API change):
- Breadcrumb
- ComboBox
- CommandBar
- Dialog
- DialogContent
- DocumentCardActions
- Facepile
- Nav
- PivotItem
- SearchBox
- SpinButton
- TeachingBubble

HackMD keeping track of the components and the way they use Button: https://hackmd.io/836e7v9oReGWP6I_Y7CVXg

**Comment by khmakoto** [comment]
Folding into #16746.
