### ISSUE TITLE
[post-snap] Merge OUFR and react-next into react

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#14688]
(from @ecraig12345)

Part 1/4 in a series of changes that must happen in master *after* v7 development moves to a branch, but *before* beta publishing:
1. (this) #14688 OUFR/react-next merge 
2. #14679 Move date-time components
3. #13384 uifabric/fluentui package renames
4. #14689 set up beta releases

For version 8, we plan to merge `office-ui-fabric-react` (current code) and `@fluentui/react-next` (function component conversions and other breaking changes) into `@fluentui/react`. There will be no version 8 of `office-ui-fabric-react`, and no `packages/office-ui-fabric-react` in the master branch of the repo. (It will of course stay around in the 5/6/7 branches.)

The changes below may be done in multiple PRs to a staging branch.

- [ ] Merge OUFR into react
- [ ] Merge react-next into react (last chance to review FC changes)
- [ ] Delete OUFR
- [ ] Make react-next be a pure re-export package from react (and bump version to 9-alpha)
- [ ] Update gitignore so that removed files don't come back in a bad merge
- [ ] Update code references to OUFR or react-next (enough to build)

**Comment by ecraig12345** [comment]
Closing in favor of #14789
