### ISSUE TITLE
Update makeStyles to use useTheme

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#14699]
David added `makeStyles` for V7 users in #14641.
For V8, we should update it to use `useTheme` instead of `useCustomizationSettings`

**Comment by ecraig12345** [comment]
@xugao Reminder to update this with more details.

**Comment by xugao** [comment]
this is updated: https://github.com/microsoft/fluentui/blob/master/packages/react-theme-provider/src/makeStyles.ts#L57
