### ISSUE TITLE
Text cleanup pass for old names

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#14690]
(from @ecraig12345)

After packages are renamed (#14688 and #13384), we need to remove references to Fabric, `office-ui-fabric-react`, `oufr`, `OUFR`, `OUIFR`, `@uifabric`, etc from text in various places:
- [ ] Files in the repo
  - `oufrVersion`/`oufr-version` references in the release pipeline should probably stay since they'll cause a cascading effect with other pipelines
  - Similar if we rename fabric-website or fabric-website-resources
- [ ] Wiki (some may have to wait until after release)
- [ ] aka.ms/fabricdemo
- [ ] Other?

**Comment by layershifter** [comment]
@JustSlone @ecraig12345 is it still a thing? ⌚

**Comment by JustSlone** [comment]
Closing out, this isn't important to tackle at this time. If this becomes important, feel free to reopen or file a new issue. I did a quick scan of our wiki it looks like the references to OUFR, etc are correct.
