### ISSUE TITLE
zoom icons are needed for Teams

### ISSUE THREAD

**Issue by fealkhou** [microsoft/fluentui#14704]
#### Describe the feature that you would like added

Teams' lightbox needs to display zoom in/out/fit icons, we don't have these icons yet in react-icons-northstar. These icons are copied as is from react-icons

#### What component or utility would this be added to

react-icons-northstar

#### Have you discussed this feature with our team, and if so, who

No

**Comment by paulgildea** [comment]
@jurokapsiar FYI on the PR 😄
