### ISSUE TITLE
CommandBarButton menuProps data-automation-id

### ISSUE THREAD

**Issue by mizeljko** [microsoft/fluentui#14701]
Is there a value that can be changed in CommandBarButton menuProps so that each of the items has data-automation-id value?

**Comment by behowell** [comment]
Hi @mizeljko, you should be able to set the `'data-automation-id'` property directly on each of the items. Take a look at the example on the CommandBar documentation page to see how to do it (click View Code on the first example; it's on line 33): https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar

 If that's not working for you, can you post a CodePen or CodeSandbox showing what you tried and didn't work as expected?
