### ISSUE TITLE
Carousel css not working in sharepoint spfx environment 

### ISSUE THREAD

**Issue by prerak13** [microsoft/fluentui#14713]
### Environment Information

- **Package version(s)**: (fill this out) 0.51
- **Browser and OS versions**: (fill this out if relevant) Windows10, Chrome

#### Actual behavior:
Please refer screen shot

#### Expected behavior:
https://fluentsite.z22.web.core.windows.net/components/carousel/definition#variations-carousel-thumbnails-example

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes
Requested priority: (Blocking, High, Normal, Low)
Blocking, High

Products/sites affected: (if applicable)
![WhatsApp Image 2020-08-21 at 5 41 42 PM](https://user-images.githubusercontent.com/25548089/91032831-273ef200-e620-11ea-8485-c7aab334099c.jpeg)
![WhatsApp Image 2020-08-21 at 5 41 19 PM](https://user-images.githubusercontent.com/25548089/91032842-29a14c00-e620-11ea-99ad-c3a984ca1908.jpeg)

**Comment by prerak13** [comment]
I am using @fluentui/react-northstar carousal component [link](https://fluentsite.z22.web.core.windows.net/components/carousel/definition?showCode=false&showRtl=false&showTransparent=false&showVariables=false#variations-carousel-thumbnails-example). it seems solution for my problem, but while loading it in spfx its not taking any default css or such. My webpart is simply showing images in vertical manner instead of showing proper carousel. Please find my code [here](https://github.com/prerak13/SPFX)

**Comment by paulgildea** [comment]
@prerak13 Thanks for the feedback!

**Comment by jurokapsiar** [comment]
Hi, thank you for reaching to us. Looks like in your code you are missing <Provider /> component which is used to inject styles. Please follow [quick start guide](https://fluentsite.z22.web.core.windows.net/quick-start), that should fix your problem.
