### ISSUE TITLE
Typescript 4.0 Error: Type 'ITextFieldStyles' recursively references itself as a base type.

### ISSUE THREAD

**Issue by Kesshi** [microsoft/fluentui#14711]
### Environment Information

- **Package version(s)**: 7.130.0

#### Actual behavior:

I just tried to upgrade my project to use Typescript 4.0 but i get the following compile error:

```
ERROR in [at-loader] ./node_modules/office-ui-fabric-react/lib/components/TextField/TextField.types.d.ts:267:18
    TS2310: Type 'ITextFieldStyles' recursively references itself as a base type.
``` 
With Typescript 3.9 there is no error.

#### Expected behavior:

It should compile without errors using Typescript 4.0.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by dotnetjunky** [comment]
I had the same problem. The fix is to change `ITextFieldStyles` to _not_ inherit from `IStyleSet<ITextFieldStyles>`. It's redundant. Everything still builds fine without it.

**Comment by paulgildea** [comment]
@Kesshi Thanks for the feedback.

@dotnetjunky Thanks for the workaround

@khmakoto / @dzearing  What's our current Typescript we support right now - Let's follow up on how we can list out our current dependencies to help set expectations if folks decide to take dependencies on libraries that we don't officially support yet. I looked at the yarn.lock file it said 3.9.7

**Comment by dzearing** [comment]
TypeScript 3.7 and above is our current support matrix. 4.0 just released and it sounds like once again the TS changes are exposing new problems, which overall is a good thing but is certainly disruptive for all. 

We should jump on this one and remove the extends, as @dotnetjunky suggested. There's no reason I see as to why this was there.

**Comment by dzearing** [comment]
At one point I believe we had validation that would validate the current version against multiple versions of TypeScript, but I don't know what happened to this or where errors are reported. Will ping some folks why we're not seeing these sooner.

**Comment by dotnetjunky** [comment]
Is someone already working on this bug?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by khmakoto** [comment]
Hey @dotnetjunky yes, I'll have a PR out soon.
