### ISSUE TITLE
Need visual affordance for clickable header in Calendar

### ISSUE THREAD

**Issue by naveedahmed** [microsoft/fluentui#14712]
#### Describe the feature that you would like added

The header (that is used to change the year) in the calendar picker is clickable but it does not have any affordance to show that it is clickable. There should be some sort of an icon (or something) that tells the user without interacting with the component that the header is clickable.

#### What component or utility would this be added to

Calendar

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/1306590/91031460-3755d200-e61e-11ea-96c2-8973587eff31.png)

**Comment by paulgildea** [comment]
@naveedahmed Thanks for the feedback.

I'm going to add this to our backlog but to set expectations we are converging our component libraries and I don't have any timelines to share when we will be focusing on DateTime. We will take this feedback as input when we provide updates.

Thanks!

**Comment by paulgildea** [comment]
@lorejoh12 as FYI
