### ISSUE TITLE
onRestoreFocus override does not work when focus is on ContextualMenu container

### ISSUE THREAD

**Issue by maidang** [microsoft/fluentui#14722]
### Environment Information

- **Package version(s)**: All
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen: 
https://codepen.io/mdster90/pen/yLOaNMj

Following up on the recent [onRestoreFocus ](https://github.com/microsoft/fluentui/pull/14351) override change, I've observed that even when this override is set, it does not reset focus in the ContextualMenu when shouldFocusOnContainer=true. When a user reopens a menu and hits tab, the last previously focused menu item receives focus again.

#### Actual behavior:

When menu is closed and reopened, tabbing sets focus to the previously focused menu item.

#### Expected behavior:

When menu is closed and reopened, tabbing should reset focus to the first menu item.

(@SavannahBourgeois for awareness)

**Comment by joschect** [comment]
@maidang I think that onRestoreFocus's documentation might be a little off. Its main purpose is to restore focus to an element on the page that _had_ focus when the menu was opened, not to restore focus within the contextualMenu. 

This has been a behavior that the focus zone has done for a while. @dzearing might have some thoughts as to if it's time to add a prop to the focus zone to reset the "next" active element when the focus zone loses focus.

**Comment by paulgildea** [comment]
@maidang Thanks for the feedback!

@joschect Thanks for the context.

@dzearing is this expected behavior or do we need to make an update?

**Comment by dzearing** [comment]
I don't believe `FocusZone` should have a flag to reset the active element on losing focus.

On the `IFocusZone` imperative api surface, the `focus` method takes a boolean to restore focus to the first element. I believe `ContextualMenu` could manage calling this when hidden transitions from true to false. That would ensure that scenarios where the menu is preserved but simply hidden would set the reset the focus on showing.

@joschect what do you think?

**Comment by joschect** [comment]
@dzearing, I think that we could add that. This could be a good community contribution as it shouldn't be hard to add.
