### ISSUE TITLE
Ability to have consistent tests for Dropdown items

### ISSUE THREAD

**Issue by mizeljko** [microsoft/fluentui#14744]
Is it possible to have some property passed to Dropdown options in order to be able to select each option? Right now IDropDownOption contains id, but changing it is not reflected in the html produced:
https://codepen.io/mizeljko/pen/xxVqYXY

Would it be possible to have some property (ideally data-automation-id) specified for each of the options?

**Comment by paulgildea** [comment]
@mizeljko Could you provide a little more context on the solution you are building out? 

Is it that you want to create automated tests that can automate selection of items in a `Dropdown` ?

**Comment by mizeljko** [comment]
Yes. I have a Dropdown element that I need to test by firstst clicking to open the list, and then clicking again on a particular item on the list. I am currently doing this by specifying id for DropDown and then clicking the list itself and each of the items using that id and suffixes ("-option" or "-list0").

However I would like have a way that will not be dependent on order or text of each option. So, for example I specify data-automation-id for list and each of the items, and I can test clicking on them even if someone changes text or inserts a new option for example.

**Comment by khmakoto** [comment]
Hi @mizeljko, thanks for filing this issue. I wanted to make sure you knew that a `data` prop exist on the `IDropdownOption` type that is typed as `any` so you can potentially do what you want here with that. Let me know if that helps!
