### ISSUE TITLE
onClick not working for commandbar buttons

### ISSUE THREAD

**Issue by yanbxice** [microsoft/fluentui#14775]
### Environment Information

- **Package version(s)**: office-ui-fabric-react 7.125.0
- **Browser and OS versions**: Chrome, Edge

### Please provide a reproduction of the bug in a codepen:

I'm using ICommandBarItemProps to create command bar buttons. ICommandBarItemProps extends IContextualMenuItem which has an onClick event handler exposed. I'm trying to do something when the command bar button is clicked. I noticed that if it has subMenuProps, onClick() is never triggered. But for buttons without sub menus, it works as expected.

https://codepen.io/yanbxice/pen/XWdRKYy?editable=true%3Dhttps%3A%2F%2Ffabricweb.z5.web.core.windows.net%2Foufr%2F7.121.4%2F

#### Actual behavior:

onClick() is not triggered when the button is clicked.

#### Expected behavior:

onClick() should be triggered when the button is clicked.

### Priorities and help requested:

Requested priority: Normal

**Comment by khmakoto** [comment]
@dzearing can comment on this one but I think this is by design since the button is already triggering the menu open action on click.
