### ISSUE TITLE
A11y_FSM-BookingStatusControl_BookingStatusControl_Screenreader : The screen reader focus moves to the top on accessing "Booking Status" control.

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/fluentui#14779]
**"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-manai%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847260936&sdata=T26HQfSGOlnuRQdX%2ByXk%2B2bxqgwFvCIVfuboZUWidYY%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”**

### Environment Details:
Application Name: Field Service Mobile - Booking Status Control
Server version: 9.1.0000.19712, Client version: 1.4.892-master
Operating system: iOS 13.5.1 (iPhone)
Screen Reader: VoiceOver

### Repro Steps:
1. Launch D365: Field Service Mobile (FSM) Application and then login with the given credentials.
2. From the list of Apps select "Field Service Mobile" and activate it.
3. The "Bookings" screen will appear and activate "New" control.
4. The "New Booking" screen will appear then start screen reader.
5. Navigate to the "Booking Status" control and activate it then select an option.
6. Observe if the screen reader's focus remains on the control or not.

### Actual:
When screen reader users navigate and activate the "Booking Status" control then select any of the options. The screen reader focus moves to the top of the screen instead of remaining on the control itself. 

### Expected: 
For screen reader users on accessing any of the options from the "Booking Status" control the screen reader focus should remain on the control itself.

### User Impact:
If the screen reader focus moves to somewhere else on the screen after accessing the control then the screen reader users will have difficulty in understanding what action has taken place and this will lead to confusion.

### Attachment:
[A11y_FSM-BookingStatusControl_BookingStatusControl_Screenreader The screen reader focus moves to the top on accessing Booking Status control..zip](https://github.com/microsoft/fluentui/files/5135684/A11y_FSM-BookingStatusControl_BookingStatusControl_Screenreader.The.screen.reader.focus.moves.to.the.top.on.accessing.Booking.Status.control.zip)

**Comment by paulgildea** [comment]
@MayuriNaik Thanks for the feedback.

Do you happen to have a reduced reproduction that doesn't require Field Service Mobile application? For example can this behavior be reproduced in a webpage that just contains the singular control? This will help us reduce the debugging complexity to understand if this is an fundamental control issue or focus management on the app side.

Thanks!

**Comment by paulgildea** [comment]
Also any specific versions of the library so that we can understand if there was a recent regression.
