### ISSUE TITLE
GroupedList items should show a tooltip on hover/focus when truncated

### ISSUE THREAD

**Issue by bcoard** [microsoft/fluentui#14793]
### Environment Information

- **Browser and OS versions**: All browsers/Windows (presumably all platforms)

### Describe the issue:

Grouped list items can truncate themselves when in confined widths with scrolling disabled. In these cases the control should show a tooltip on hover/focus so the user can get all the information they need about the list item. Currently the user doesn't not get this experience and information can be lost due to text being cut off.

#### Actual behavior:

List items truncate and the user does not get a tooltip on hover/focus.

#### Expected behavior:

List items truncate and the user does get a tooltip on hover/focus.

**Comment by khmakoto** [comment]
Related to #14760

**Comment by JustSlone** [comment]
This is covered by #14760 (I added a note about the request for GroupedList there)
Also see that issue for a workaround.
