### ISSUE TITLE
onRenderSubMenu doesn't work for first level menu

### ISSUE THREAD

**Issue by emkessle** [microsoft/fluentui#14802]
### Environment Information

- **Package version(s)**: 
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/jdh-msft/pen/PMRZmZ?editors=0011

#### Actual behavior:
"render sub menu 0" never prints 

#### Expected behavior:
"render sub menu 0" prints when the submenu is opened

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

**Comment by paulgildea** [comment]
@emkessle Thanks for the feedback. Could you provide a little more context on what you are trying to achieve? I'm assuming that you want to pass a fully custom `ContextMenu` to the CommandBar? Is there something that's not meeting your needs outside of the level of customization from the API today?

@joschect - If you have any ideas here.

**Comment by miroslavstastny** [comment]
`CommandBar` uses `ContextualMenu` component to render any menus.

If you need to customize the first level menu, you can use `onRenderMenuList` prop (see [`ContextualMenu` docs and examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu) for details):

```jsx
<CommandBar
  items={[
    {
      key: 'New',
      text: 'New',
      subMenuProps: {
        items: [{ key: 'Mail', text: 'Mail' }],
        onRenderMenuList: (props, defaultRenderer) => {
          console.log('render sub menu 0');
          return defaultRenderer!(props);
        },
      },
    },
  ]}
/>
```

**Comment by emkessle** [comment]
I'm trying to find a way to close any open sub menus when another event is triggered. I want to use the menuAs function but that doesn't work here and if I try onRenderMenuList, I need to pass in a target for the command bar item but that keeps coming back undefined.
