### ISSUE TITLE
Importing bootstrap breaks ChoiceGroup with image.

### ISSUE THREAD

**Issue by davvit** [microsoft/fluentui#14808]
### Environment Information

- **Package version(s)**: 
    "@fluentui/react": "^7.132.0",
    "@uifabric/example-data": "^7.1.3",
    "@uifabric/react-cards": "^0.111.4",
    "react": "^16.8.6",
- **Browser and OS versions**: 
   "electron": "^9.2.0",

### Please provide a reproduction of the bug in a codepen:
Importing bootstrap breaks ChoiceGroup css. 
Upon selection flicker happens, also the box does not hold its size.

https://codepen.io/davvit/pen/MWyojZd

![2020-08-28_17-50-12](https://user-images.githubusercontent.com/4433698/91622261-dc90e300-e95b-11ea-8ace-82ed1a0f5fa2.gif)

#### Actual behavior:
Flicker happens when clicking  ChoiceGroup with image source.

#### Expected behavior:
No flicker and same sizing for the selection options

### Priorities and help requested:

Requested priority: (Blocking, High, Normal, Low)
Normal

**Comment by paulgildea** [comment]
@davvit Thanks for the feedback. Just to double check - this behavior only happens when Bootstrap is included in your project as well? 

@dzearing - Have we made any historical statements of support of having both Fluent UI React and Bootstrap being used together?

My hunch is that when Bootstrap is included it's overriding styles on primitive HTML elements which the component might not expect.

@khmakoto - Try to determine if there is a simple fix/workaround here - This might be a by design especially if styles are being redefined as this might be difficult to support holistically.

**Comment by dzearing** [comment]
Here's what's happening:

bootstrap defines this:

```css
*, ::after, ::before {
    box-sizing: border-box;
}
```

This affects everything on the page. I might argue that's a bad pattern to apply page-wide resets, but I would also argue that box-sizing being anything besides border-box is just as terrible as Times New Roman being the default font family.

The particular ChoiceGroup variant doesn't play well with this reset. Recommend that we clean up the css here in ChoiceGroup. try to be surgical to avoid breaks, but it seems the original author of the styles was using both flexbox AND paddings to align things centered, which is the first problem. Centering with fixed padding does not play with with box-sizing resets. If we leverage flexbox for centering, box sizing matters less.

I'm also not seeing any sort of min widths defined, which is really confusing. We should at least be defining a min width.

**Comment by davvit** [comment]
@paulgildea yes it only happens when i added bootstrap. box-sizing from bootstrap is the issue as @dzearing stated. 

I completely understand the css clash when multiple libraries are in use. I thought maybe adding !important to known problem properties like box-sizing could fix it here in fluent.

@dzearing i like the sticking to flexbox idea.

**Comment by dzearing** [comment]
@khmakoto Were you already in progress of fixing this one?

**Comment by khmakoto** [comment]
@dzearing I hadn't really started.

**Comment by miroslavstastny** [comment]
@davvit as a workaround you can set box-sizing for the `ms-ChoiceField-innerField`:

```css
.ms-ChoiceField-innerField {
    box-sizing: content-box;
}
```
