### ISSUE TITLE
Value of the `fluent-text-field` custom element

### ISSUE THREAD

**Issue by arshia11d** [microsoft/fluentui#14812]
### Actual behavior
Setting `value` attribute of the `fluent-text-field` web component does not set the `value` property of the component object.

### Expected behavior:
It should react to attribute changes and map the `value` attribute to its backing JS property.

### Priorities and help requested:
Are you willing to submit a PR to fix? No
Requested priority: High

### Products affected
**Fluent Web Component** and integration with Blazor, as Blazor's `@bind` attribute sets the attributes of the HTML Element.

### [Codepen](https://codepen.io/arshia11d/pen/GRZEvwv)

**Comment by paulgildea** [comment]
@arshia11d Thanks for the feedback.

@chrisdholt FYI 👍

**Comment by chrisdholt** [comment]
Thanks @arshia11d - I believe this was fixed with this commit: https://github.com/microsoft/fast/commit/ccba229c6c1133485d0fac92eae88cb3a6369495#diff-681a29d04cd982801e4204cc22bc7360

FAST just had a new release last week - we'll get the packages updated and we can see if the issue still persists.

**Comment by arshia11d** [comment]
Thanks @chrisdholt
Excited to play around with new versions and test furthur possibilities with fast Web Components and their integration with Blazor

**Comment by chrisdholt** [comment]
@arshia11d The new packages have been published (v1.8.0) which updates the dependencies for the WC's and should *hopefully* resolve the value issue you were seeing. Please let me know if this is still an issue after updating :)

**Comment by arshia11d** [comment]
Yes, All fixed!
