### ISSUE TITLE
Recent charting change formats single digits as x.x

### ISSUE THREAD

**Issue by mbest** [microsoft/fluentui#14811]
### Environment Information

charting 3.1.4

### Please provide a reproduction of the bug in a codepen:

sample groupedverticalbarchart--grouped-vertical-bar-chart-styled-example is a good one

![image](https://user-images.githubusercontent.com/1230364/91627949-2f749580-e970-11ea-9dbc-3efc32d05285.png)

#### Actual behavior:

Single digit y-axis values formatted as x.x

#### Expected behavior:

Single digits are formatted as x.

**Comment by mbest** [comment]
See https://github.com/microsoft/fluentui/pull/14657#issuecomment-683183146

**Comment by paulgildea** [comment]
@mbest Thanks for the feedback.

@Raghurk FYI 👍

**Comment by Raghurk** [comment]
unfortunately this is a behavior from D3. We cannot control this. I am open to see if you have a work around

**Comment by mbest** [comment]
If all charts allow configuring the format, this would be okay. #14830 adds support for configuring the format for `VerticalStackedBarChart`, but not all charts support it yet.
