### ISSUE TITLE
<Fabric> component does not apply custom root styles

### ISSUE THREAD

**Issue by Gerhut** [microsoft/fluentui#14819]
### Environment Information

- **Package version(s)**: 7.132.0
- **Browser and OS versions**: Edge 85.0.564.41 / Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/Gerhut/pen/YzqxwMp?editors=0010

#### Actual behavior:

White background

#### Expected behavior:

Red background

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/sites affected: Bing platform internal portals

**Comment by dzearing** [comment]
This is a very simple bug. I see Fabric.base is passing in the getStyles function into getClassNames. This should be `props.styles`.
