### ISSUE TITLE
Fabric version updation.

### ISSUE THREAD

**Issue by Faisal-developer** [microsoft/fluentui#14814]
I am using office-ui-fabric-react": "6.112.0" and now I want to upgrade it to latest version. Now its renamed to FluentUI.

Questions: 
1) Which one to use now ? Should I update  "office-ui-fabric-react"  to latest version (7.130.0) or use FluentUI?

2)What if I update "office-ui-fabric-react" to latest version instead of using FluentUI? Will you be giving updated on "office-ui-fabric-react"?

**Comment by paulgildea** [comment]
@Faisal-developer Thanks for the feedback!

You can check out the FAQ on the package naming: https://github.com/microsoft/fluentui/wiki/FAQ---Fabric-and-Stardust-to-Fluent-UI

> Our primary package was renamed to @fluentui/react, but this package simply exports bits from the office-ui-fabric-react package. This ensures no partners are broken, they still receives fixes, but you can upgrade your package name at your leisure.

If you can move the the new package name for your project at this time I'd recommend moving to the new package name: @fluentui/react. This will help with migrating in the future. If it's not possible to update your imports, then you can continue to use the `office-ui-fabric-react` package at this time and select the version number you wish to upgrade to.

If you are moving from v6 release to v7 release, here are the release notes: https://github.com/microsoft/fluentui/wiki/Fabric-7

You can also check out the [Version 8 project](https://github.com/microsoft/fluentui/projects/36) to get some insight on our progress.

Hope that helps!
