### ISSUE TITLE
Disappearing Dropdown when using next.js production build

### ISSUE THREAD

**Issue by roeap** [microsoft/fluentui#14832]
### Environment Information

- **Package version(s)**: 7.133.0
- **Browser and OS versions**: Win 10, Firefox 80.0

### Please provide a reproduction of the bug in a codepen:

Unfortunately I don't see a straight forward way to reproduce the issue, but will certainly try if I can be provided with some guidance on how.

#### Actual behavior:
We are using Fluent UI with next.js and followed the instructions provided in the wiki. When running the website in dev mode, everything works fine, but when next.js compiles a production build, we observe that ContextualMenus seem to disappear, when rendered to the side of a component. This true, when using ContextualMenu directly, but also for Dropdowns etc. When a dropdown opens and has enough space to render below the element, it works as expected. When decreasing the screen size, such that the dropdown renders beside the control, it shows up for a split second, before disappearing. We observe the same behavior using plain ContextualMenus that are supposed to show up on hover over certain components.

#### Expected behavior:

ContextualMenu should stay visible also in production mode. 

### Priorities and help requested:

Any guidance on how to resolve or even to debug the issue is greatly appreciated.

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@roeap Thanks for the feedback!

@dzearing adding for next.js supports
@joschect for `ContextMenu`

**Comment by dzearing** [comment]
@roeap would it be possible for you to gather up a repro project setup ? That'd really help to investigate and make sure we're hitting what you are.

**Comment by roeap** [comment]
@dzearing I created a minimal example [repo](https://github.com/roeap/fluentui-nextjs-repro), which reproduces the issue. I used the basic nextjs app via `yarn create next-app` and added the code for nextjs from the wiki. Then simply adding enough elements to the dropdown, such that it will render to the side of the component. Running this with `yarn dev` works fine. Building it, and then running the optimized build leads to the described behaviour - at least on my machine :). 

Thanks for your help on this, and thanks for this excellent library.

**Comment by dzearing** [comment]
Confirmed the behavior:

When running `yarn dev` (dev loop), the dropdown content shows fine.

When running `yarn build` (build prod build) and then `yarn start` (host it), dropping the dropdown briefly shows the content to the right of it, and then immediately dismisses it.

@joschect Do you have ideas here? I thought it was possibly something like the page is scrolling which causes it to dismiss imediately, but I forced overflow hidden on body, and it still repros.

**Comment by dzearing** [comment]
We found it. It's a race of imports.

In your pages/_document.ts, change it to this:

```
// Import the styling directly.
import { Stylesheet, InjectionMode } from "@uifabric/merge-styles";
import { resetIds } from "@uifabric/utilities";

// Do this in file scope to initialize the stylesheet before oufr is imported.
const stylesheet = Stylesheet.getInstance();

// Set the config.
stylesheet.setConfig({
  injectionMode: InjectionMode.none,
  namespace: "server",
});

// Now set up the document, and just reset the stylesheet.
export default class MyDocument extends Document {
  static getInitialProps({ renderPage }) {
    stylesheet.reset();
    resetIds();

    const page = renderPage((App) => (props) => <App {...props} />);

    // etc

**Comment by dzearing** [comment]
Let us know if that resolves it for you!

**Comment by roeap** [comment]
That was quick, and yes, this resolves the issue!

Should we close this, or do you want to attach it to the wiki update PR?

Thanks for the very quick help!

**Comment by dzearing** [comment]
I will close but let me update the wiki.

**Comment by dzearing** [comment]
I've updated. Thanks for calling it out, happy to help.
