### ISSUE TITLE
DetailList : Focus is visible on non-interactive Column Header

### ISSUE THREAD

**Issue by rajnish07** [microsoft/fluentui#14857]
### Environment Information

#url: https://codepen.io/rajnish07/pen/OJNxRdp?editors=0010
- **Browser and OS versions**: 
       Windows Version - Win10 
       Chromium Edge Version: 85.0.552.1 (Official build) dev (64-bit)
       Chrome Version: 83.0.4103.116 (Official Build) (64-bit)
### Please provide a reproduction of the issue in a codepen:
https://codepen.io/rajnish07/pen/OJNxRdp?editors=0010

#### Repro Steps:
         1. Go to https://codepen.io/rajnish07/pen/OJNxRdp?editors=0010 for a starter codepen.
         2. Tab till the Header of the detail list.
         3. Check if focus is visible on non-interactive column header.

#### Actual behavior:

Focus is visible on column header 'Name' which is a non-interactive field. As it does not support any operation focus should not be visible.

#### Expected behavior:

Focus should not be visible on non-interactive column header.
![image](https://user-images.githubusercontent.com/40293642/91944576-ed56a580-ed1b-11ea-8fcd-d0df8aa32ac4.png)

**Comment by paulgildea** [comment]
@rajnish07 Thanks for the feedback and detailed repo! Super helpful.

**Comment by rajnish07** [comment]
adding the property {columnActionsMode : ColumnActionsMode.disabled} to the column makes it non-focusable.
And this resolves the issue.
