### ISSUE TITLE
DatePicker will automatically popup calendar if it's in a showCloseButton = false Dialog

### ISSUE THREAD

**Issue by nagisa1993** [microsoft/fluentui#14850]
### Environment Information

- **Package version(s)**: 7.69.0
- **Browser and OS versions**: new Edge Version 85.0.564.41 (Official build) (64-bit)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@nagisa1993 Thanks for the feedback!

Looking at the documentation, the `showCloseButton` only controls the visibility of the `DatePicker` close button. I do not believe it controls its default opening behavior.

@lorejoh12 - Could you take a look at the repo to see if what's expected?

**Comment by nagisa1993** [comment]
any updates?

**Comment by JustSlone** [comment]
@nagisa1993 you can use the prop `disableAutoFocus={true}` on DatePicker to disable this behavior (Props are documented down in the [Implementation section](https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker#implementation))

See this fixed codePen: https://codepen.io/justslone-the-encoder/pen/GRjKzPa?editors=0010

```
        <DatePicker
          disableAutoFocus={true} //<---- added prop
          className={controlClass.control}
          placeholder="Select a date..."
          ariaLabel="Select a date"
        />
```
