### ISSUE TITLE
Checkbox: indeterminate state, and theme-able checkmark color & background

### ISSUE THREAD

**Issue by thure** [microsoft/fluentui#14863]
#### Describe the feature that you would like added

It is not currently possible to implement certain features without overriding Checkbox's `backgroundImage` to display the same indeterminate state SVG as used in TreeItem. It’s also not currently possible to adjust the colors of the `backgroundImage` for hover and focus states (it can only be overridden in the normal state). These colors need to be adjusted at least for selectable table rows in the high-contrast color palette.

If Checkbox supported variables for the colors used in its `backgroundImage` (including for hover and focus), as well as an indeterminate state version in addition to the usual checked-determinate state, this would allow for a truer implementation.

#### What component or utility would this be added to

`Checkbox` in `@fluentui/react-northstar`

#### Have you discussed this feature with our team, and if so, who

I raised the question in a chat including @levithomason, who has helped me with related issues before. Rekha Patel mentioned the indeterminate state is tracked (please DM for that item), though theming the checkbox colors is probably not within-scope of that item.

#### Additional context/screenshots

Please message me on Teams as needed: v-wishow@microsoft.com.

**Comment by paulgildea** [comment]
@jurokapsiar Bubbling this one up.

@miroslavstastny FYI

**Comment by jurokapsiar** [comment]
@thure indeterminate state was merged to master - #16081

Can you provide visuals for the hover/focus state so that we can advise on how to theme it?
