### ISSUE TITLE
Wrapping pivot *tabs only* in a '<nav>' landmark

### ISSUE THREAD

**Issue by michaeltreynolds** [microsoft/fluentui#14870]
https://github.com/microsoft/fluentui/blob/12e72defeec4e1c2a6c7326c9cef670f6c2b2a55/packages/office-ui-fabric-react/src/components/Pivot/Pivot.base.tsx#L143

Would like to use an accessibility landmark `<nav>` for just the tab names. I do not want to wrap the whole thing as a visually impaired (but partially seeing) user would see a giant box drawn for the navigation landmark. Do you think it makes sense to add this option?

**Comment by paulgildea** [comment]
@michaeltreynolds Could you add some more details on what you are experience you are trying to achieve? Im curious why you are only using the `Pivot` tabs and not using `Pivot` items as well.

@smhigley FYI
