### ISSUE TITLE
react-northstar/TextArea readOnly attribute does not let user select and copy content

### ISSUE THREAD

**Issue by latonita** [microsoft/fluentui#14879]
#### Describe the feature that you would like added

Existing northstart TextArea has readOnly attribute, as it inherits all `<textarea />` attributes, but when used it doesn't let user select/copy content. This works with html textarea.

#### What component or utility would this be added to

fluentui/react-northstar/src/components/TextArea/TextArea.tsx

#### Have you discussed this feature with our team, and if so, who

not yet

#### Additional context/screenshots

I expect readOnly mode will let user select and copy text from the control if needed.

**Comment by paulgildea** [comment]
@jurokapsiar FYI

**Comment by jurokapsiar** [comment]
`readOnly` is supported as we by default spread all unhandled props to the root slot element. However, as opposed to pure html `<textarea />` for some reason selection and copying does not work, so keeping this open. I will also modify the issue to reflect that.

**Comment by vyhnalekl** [comment]
@latonita Could you explain the problem and the environment a bit more? I tried replicating this issue but it works for me - https://codesandbox.io/s/sleepy-fast-3oed6?file=/example.js

**Comment by jurokapsiar** [comment]
closing as we are not able to repro
