### ISSUE TITLE
deprecate prop showYAxisGridLines in AreaChart

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#14873]
in the pr
https://github.com/microsoft/fluentui/pull/14781/files we have removed the prop `showYAxisGridLines`, instead of making it deprecated.

now we need to raise the pr by introducing the same prop and deprecating it

**Comment by paulgildea** [comment]
@Raghurk FYI

**Comment by shivasai09** [comment]
fixed in #14597
