### ISSUE TITLE
No announcement about 'Today's' date or selected date in the Calendar picker of Date filter is made by narrator.

### ISSUE THREAD

**Issue by gopalgoel19** [microsoft/fluentui#14898]
### Environment Information

- **Package version(s)**: "^7.90.0"
- **Browser and OS versions**: Microsoft Edge on Windows

#### Actual behavior:

Actual Results:
No announcement about 'Today's' date or selected date in the Calendar picker of Date filter is made by narrator. Narrator announces both the dates like other non selected dates as <DD MM YYYY, column header, row index, column index>.

#### Expected behavior:

Expected Results:
 'Today's' date or selected date in the Calendar picker of Date filter should be explicitly specified by narrator as <DD MM YYYY, column header, row index, column index, button, selected/Today>

### Documentation describing expected behavior

Visually impaired users who rely on screen readers will not be able to know about the current date/ selected date(until they close the picker) if not specified by narrator.

**Comment by paulgildea** [comment]
@gopalgoel19 Thanks for the feedback!

@lorejoh12  - This I think is being addressed by this #14806 fix right?

@smhigley FYI

**Comment by miroslavstastny** [comment]
@paulgildea After #14806, `aria-current="date"` is correctly added to the current day element.

As a result, it is correctly narrated as "current date" by Safari/VoiceOver and Chrome/NVDA.
But it does not narrate in Edge/Narrator.
[Reportedly](https://a11ysupport.io/tests/tech__aria__aria_current) `aria-current` is not supported by Narrator.

FYI @kolaps33

**Comment by JustSlone** [comment]
Closing as this is fixed, and it doesn't seem reasonable to workaround Narrator's lack of support for aria-current
