### ISSUE TITLE
the mouse position line chart hover Callout

### ISSUE THREAD

**Issue by NewFuture** [microsoft/fluentui#14897]
### Environment Information

- **Package version(s)**:  @uifabric/charting: 3.4.0
- **Browser and OS versions**: any

### Please provide a reproduction of the bug :

http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/14758/merge/charting/dist/index.html#/examples/linechart

hover the mouse in the line chart near the **LEFT** of a point (say B), the left point (say A) will active.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/6290356/92217620-80cdd900-eeca-11ea-84d4-44cdba4c8d40.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/6290356/92216510-f769d700-eec8-11ea-8204-71e9708368af.png)

When mouse in the red area (Xb-1/2, Xb+1/2), display the callout of B. 
When mouse in the black area (Xa-1/2, Xa+1/2), display the callout of A.

**Comment by paulgildea** [comment]
@Raghurk FYI
