### ISSUE TITLE
The CompactPeoplePicker field shrinks in height a bit when a Persona is selected. 

### ISSUE THREAD

**Issue by belozerovany** [microsoft/fluentui#14904]
### Environment Information

- **Package version(s)**: (7.0.1)
- **Browser and OS versions**: (all)

### Please provide a reproduction of the bug in a codepen:

codepen: https://codepen.io/belozerovany/pen/LYNzRvY?editors=0010
#### Actual behavior:

The CompactPeoplePicker field shrinks in height a bit when a Persona is selected. 

Problem is in {itemLimit=1}. When we set this property div(.ms-BasePicker-text) change own height by a child element. When we do not use itemLimit div`s height depend on the supplementary element "input" wish added for the next select.

#### Expected behavior:

The CompactPeoplePicker field should not shrinks in height a bit when a Persona is selected.

### Priorities and help requested:

Are you willing to submit a PR to fix?  No

Requested priority: High

Products/sites affected: Products

**Comment by paulgildea** [comment]
@belozerovany Thanks for the feedback!

@miroslavstastny - Determine if this repo-ing in the latest version. We may have already fixed this.

**Comment by miroslavstastny** [comment]
@paulgildea I can repro with the latest `office-ui-fabric-react@7.136.0`. Will debug more.

**Comment by miroslavstastny** [comment]
Reassigning to @joschect.

The problem occurs not only when `itemLimit=1` but whenever the limit is reached. This also affects cases when the input is multiline. The following example is with `itemLimit=3`:
![output](https://user-images.githubusercontent.com/9615899/94248539-e8ea6a80-ff1e-11ea-8a8f-107cabe99da7.gif)
