### ISSUE TITLE
Dropdown/Safari: Scrollbar in input of searchable variants

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#14918]
### Environment Information

- **Package version(s)**: 0.51
- **Browser and OS versions**: Safari

### Please provide a reproduction of the bug in a codepen:
https://fluentsite.z22.web.core.windows.net/components/dropdown/definition

#### Actual behavior:
After selection, vertical scrollbar appears in searchable variants:
<img width="448" alt="Screenshot 2020-09-07 at 10 53 29" src="https://user-images.githubusercontent.com/13742664/92368717-60836180-f0f8-11ea-9cbf-657b7876c36f.png">

#### Expected behavior:
no scrollbar

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by miroslavstastny** [comment]
In the rendered dropdown, there is an `<input class="ui-dropdown__searchinput__input">` inside a `div`.
There is `height` of `29.96875px` set on the `input`.
The wrapping `div` does not have any height set and is supposed to resize to fit the `input`.

This works as expected in Chrome.

In Safari if the height of the inner input is a decimal number, it is floored - in that case the height of the `input` is bigger than the height of the `div` and therefore the `div` renders a scrollbar.

What is interesting is that if the `input` is replaced by a `div`, the height is correct.

### Chrome

![image](https://user-images.githubusercontent.com/9615899/92489004-8dff0680-f1ef-11ea-9fcc-bef2e621faf8.png)

### Safari

![image](https://user-images.githubusercontent.com/9615899/92488954-7de72700-f1ef-11ea-991d-644937ddf016.png)

Testing codesandbox: https://codesandbox.io/s/input-height-safari-dfs0o?file=/example.js

**Comment by assuncaocharles** [comment]
This is fixed in Safari Version 14.0 (15610.1.28.1.9, 15610)

<img width="418" alt="Screen Shot 2020-09-18 at 09 13 35" src="https://user-images.githubusercontent.com/8545105/93567643-40249400-f98f-11ea-87ab-c6fc7fc3fc4c.png">

**Comment by paulgildea** [comment]
Closing as no repo. If folks think they want to bring this back feel free 👍
