### ISSUE TITLE
What are primarySet and secondarySet under ICommandBarStyles and how to use them?

### ISSUE THREAD

**Issue by abmis-mi** [microsoft/fluentui#14928]
What are primarySet and secondarySet under ICommandBarStyles and how to use them?

**Comment by miroslavstastny** [comment]
[`CommandBar`](https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar) component renders `items` aligned to the start of the `CommandBar`. Besides the required `items` it can also render `farItems` which are aligned to the end.

See the following screenshot, the red rectangle shows `items`, blue one shows `farItems`:
![image](https://user-images.githubusercontent.com/9615899/92479654-1d062180-f1e4-11ea-917c-4c26b57bc0b0.png)

By altering `primarySet` in `ICommandBarStyles` you modify styles for the `items` container.
By altering `secondarySet` you modify styles for `farItems` container.

The following code was used to render the screenshot:

```jsx
<CommandBar
  ...
  styles={{
    primarySet: {outline: '2px solid red'},
    secondarySet: {outline: '2px solid blue'}
  }}
/>
```
codepen: https://codepen.io/mstastny/pen/bGpLRpL

**Comment by abmis-mi** [comment]
Thanks a lot Miroslav! Wanted to create a control and set default styles as per our project. Was a little confused with the names. But, now it is clear.
