### ISSUE TITLE
DetailsRowFields cells have read only attribute for textfields

### ISSUE THREAD

**Issue by emokeeff** [microsoft/fluentui#14920]
### Environment Information

- **Package version(s)**: office-ui-fabric-react - 7.127.1
- **Browser and OS versions**: Edge

### Describe the issue:

Aria-read only attribute on DetailsRowFields which causes Narrator in scan mode to define cells as read only before reading out the cell value. This should only be used in text fields (inputs) that are read only.

Link to aria read-only attribute in the code - https://github.com/microsoft/fluentui/blob/f9ca45d012d2e77eea728e19651b144452562004/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowFields.tsx#L84

### Please provide a reproduction of the issue in a codepen:

Codepen link of isolated example: https://codepen.io/Emmaok123/pen/NWNXEQV

Zip of Video of issue occuring in 7.127.1 fluentdemo DetailsList example attached.
[Fluent UI React Readonly Attribute.zip](https://github.com/microsoft/fluentui/files/5182551/Fluent.UI.React.Readonly.Attribute.zip)

#### Actual behavior:
With Scan mode on using Narrator in Edge, Navigate to cell with text. Narrator prefaces text cell value with readonly.

#### Expected behavior:
Text cells are not prefaced with readonly.

### Documentation describing expected behavior

https://html.spec.whatwg.org/multipage/input.html#attr-input-readonly

**Comment by paulgildea** [comment]
@emokeeff Thanks for the feedback and repo steps. This is super helpful for our team!

**Comment by miroslavstastny** [comment]
The `aria-readonly` was explicitly added in #11447 which fixed #11312.
@khmakoto could you please check this?

**Comment by emokeeff** [comment]
Hi there I am just wondering if there has been any update regarding this bug?
