### ISSUE TITLE
Adjustable width of ListPeoplePicker suggestions

### ISSUE THREAD

**Issue by abmis-mi** [microsoft/fluentui#14929]
Is there a property that we can set to ensure the width of the suggestions box is same as the input box width? Combo Box seems to have a property useComboBoxAsMenuWidth but not ListPeoplePicker.

![image](https://user-images.githubusercontent.com/66029786/92408101-23e85200-f15a-11ea-884f-130e3509820f.png)

**Comment by paulgildea** [comment]
@abmis-mi Thanks for the feedback!

I’ll mark this as a feature request and add it to our backlog, but to set expectations - we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. We'll take this into consideration when we converge the `ListPeoplePicker` component across our two React packages.

@joschect - Do you know if there are any workaround to achieve this desired behavior outside of adding a new prop like `useComboBoxAsMenuWidth` to the `ListPeoplePicker` ?

**Comment by abmis-mi** [comment]
@paulgildea Thanks for the update. And yes, a workaround would be great to have as this cant be fixed for some time now.

**Comment by bhubanmm** [comment]
@paulgildea @abmis-mi Did you figure out any workaround or SCSS / CSS fix for this?

**Comment by paulgildea** [comment]
@joschect Thoughts?

**Comment by joschect** [comment]
@paulgildea and @bhubanmm you can use the calloutWidth prop to set a custom width of your choosing. The combobox and dropdown both actually set the width of the callout based some internal measuring. Here is an example of where you set the width to something custom in a [codepen](https://codepen.io/slimemold/pen/yLJVaXv?editors=0010)
