### ISSUE TITLE
Add compat exports to v7

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#14939]
To help partners with migration, we can introduce compat Button export files within v7: `packages/react/src/compat/Button`. It will only be added to `@fluentui/react` (not `office-ui-fabric-react`) to help encourage migration.

**Comment by JustSlone** [comment]
If it's reasonable, we should only export the compat export from @fluentui/react not office-ui-fabric-react to help encourage folks to move forward (which they need to for v8 anyway)

**Comment by JustSlone** [comment]
Also, we need to provide the codemod to do the rename too. (CC @joschect)

**Comment by ecraig12345** [comment]
Just realized we're also going to need compat exports for DatePicker and Calendar (because we'll be exporting the date-time ones by default). This should be done at the same time.
