### ISSUE TITLE
DetailsList onItemInvoked callback should be called when pressing Enter.

### ISSUE THREAD

**Issue by miegir** [microsoft/fluentui#14947]
In documentation it is said that onItemInvoked is a "Callback for when a given row has been invoked (by pressing enter while it is selected.)" But in reality onItemInvoked is invoked only when the item is double clicked but not when Enter key is pressed. The callback should be invoked when Enter key is pressed (or consider making another callback that is invoked by Enter key).

**Comment by paulgildea** [comment]
@miegir Thanks for the feedback.

Can you provide a codepen or code example of the experience you are seeing because this can help us understand if a regression was introduced.

Thanks!

**Comment by miegir** [comment]
@paulgildea, I do not think that it is regression, maybe the feature was never in the DetailsList (or SelectionZone that it uses internally). The example can be seen directly in the documentation page at https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist in the Usage section. There is a DetailsList with onItemInvoked handler, but that handler is invoked only when the item double clicked by mouse but not when item is selected and Enter pressed on the keyboard. The onItemInvoked documentation I cited eralier is on the same page and states that onItemInvoked handler should be invoked when enter is pressed.

**Comment by brandonthomas** [comment]
@paulgildea this is a regression. We're getting pinged on this now as well in admin-controls. I went back to some of our older demo site versions that were built on older versions of OUFR and enter to invoke works fine. Please prioritize this fix.

Works in OUFR versions: 7.93.1, 7.116.0 and 7.124.0. So this is a super recent regression

**Comment by brandonthomas** [comment]
Does not work in 7.126.1 so somewhere between 7.124.0 and 7.126.1 is when this broke.

**Comment by brandonthomas** [comment]
!14283 potential suspect?

**Comment by paulgildea** [comment]
@brandonthomas Thanks for the deep analysis! Super helpful.

@dzearing / @xugao - Just bubbling this up as Invoke is pretty core to the DetailsList.

**Comment by dzearing** [comment]
Justin and I were discussing this one, and there's a similar bug in GroupedList. I'm looking at a fix as Micah is oof, so I'll steal this bug.

**Comment by paulgildea** [comment]
@dzearing Thanks!
