### ISSUE TITLE
DataPicker textfield does not preserve input value on error

### ISSUE THREAD

**Issue by trsvax** [microsoft/fluentui#14960]
### Environment Information

- **Package version(s)**: 7.135
- **Browser and OS versions**: any

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/pen/?&editable=true=https%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

#### Actual behavior:

type 'aa' in textfield, tab, error is displayed but 'aa' is gone or replaced by previous value

#### Expected behavior:

'aa' should remain in textfield on error

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Low

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@trsvax Thanks for the feedback.

Did you mean the `DatePicker` Component and could you provide a repro of the issue? The link provided seemed to be empty.

This might be by design - but we'll look into it after we have some more information.

Thanks!

**Comment by trsvax** [comment]
Oops copy/paste problem 

https://codepen.io/trsvax/pen/LYNdJNx?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

**Comment by trsvax** [comment]
I believe the root issue here is the value for DatePicker is a Date. If I type something like "aa" in the textfield that can't be passed to DatePicker as the value

**Comment by behowell** [comment]
It looks like the current behavior is by design; @paulgildea or @miroslavstastny can you confirm? If there's invalid input in DatePicker, it resets to the last valid entry (which might be blank if there was never a valid entry, as is the case in this issue).
