### ISSUE TITLE
multi selection of legends for the line chart is not resizing now

### ISSUE THREAD

**Issue by NewFuture** [microsoft/fluentui#14966]
when the multi-selection of legends are changed in the line-chart, the chart is not resizing now.

### Environment Information

- **Package version(s)**:  "@uifabric/charting": "3.6.2",
- **Browser and OS versions**:  any

### Please provide a reproduction of the bug in a codepen:

https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/charting/dist/index.html#/examples/linechart

Multiple Line chart

#### Actual behavior:

![image](https://user-images.githubusercontent.com/6290356/92680963-e0126a00-f35e-11ea-822a-aa524bae5a50.png)
![image](https://user-images.githubusercontent.com/6290356/92680975-ec96c280-f35e-11ea-9837-8dfeb7db7fb1.png)

#### Expected behavior:

As PR #14758 does   http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/14758/merge/charting/dist/index.html#/examples/linechart

![image](https://user-images.githubusercontent.com/6290356/92680662-008df480-f35e-11ea-88d5-55e8f85100f6.png)
![image](https://user-images.githubusercontent.com/6290356/92680719-303cfc80-f35e-11ea-92b5-f9cc8e44386d.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: High

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@Raghurk FYI

**Comment by NewFuture** [comment]
fixed in PR #15117
