### ISSUE TITLE
menu-item component does not append ellipsis when overflown

### ISSUE THREAD

**Issue by paucortescosta** [microsoft/fluentui#14988]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: any

### Please provide a reproduction of the bug in a codepen:
Navigate to:
https://www.fast.design/docs/components/menu

Update any menu item long enough to overflow, you'll notice the grid column template is not respected and no ellipsis is being appended to the content slot when overflowing.

#### Expected behavior:
The content should not overflow to the next grid slot, and should also have ellipsis when overflowing.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

**Comment by chrisdholt** [comment]
Thanks @paucortescosta - let me get some insight from design on this and I'll circle back with a recommendation, then you can submit a PR :).

**Comment by bheston** [comment]
Generally we should avoid ellipsis for accessibility and readability concerns. I see that the demo has a max-width style applied, which I'm not sure the significance of, so my first suggestion would be to remove that and allow the menu to grow with the item content. In a hopefully rare case where there is no possibility of shortening the text, to fully support reflow accessibility requirements we should wrap the contents instead of truncate in any form. This is consistent with the design for tree view items as well.

**Comment by paucortescosta** [comment]
I think you're right for most cases where we could let the menu grow as needed, however in narrower screens, that could pose the issue I'm describing above. In regards to accessibility, being able to pass a title/aria-label values would probably resolve it. Also, looking at the menu item implementation looks like truncating was the original goal, but it's just not working.

**Comment by chrisdholt** [comment]
@paucortescosta can you link to this portion of the implementation and we can take a look?

> Also, looking at the menu item implementation looks like truncating was the original goal, but it's just not working.

**Comment by paucortescosta** [comment]
hey @chrisdholt, this is what I'm referring to:

`    .content {
        grid-column-start: 2;
        justify-self: start;
        overflow: hidden;
        text-overflow: ellipsis;
    }
`

from the menu-item.styles.ts:
https://github.com/microsoft/fluentui/blob/master/packages/web-components/src/menu-item/menu-item.styles.ts

**Comment by paucortescosta** [comment]
hey @chrisdholt, have you had a chance to look at this?

**Comment by chrisdholt** [comment]
@paucortescosta Yes, sorry - I'm trying to determine whether we should drop the ellipsis here based on @bheston's feedback considering his feedback and what that would mean to wrap to two lines.
