### ISSUE TITLE
Role on DetailsList

### ISSUE THREAD

**Issue by castrodd** [microsoft/fluentui#15004]
We are using the DetailsList component to display a list of values. However, the component is creating this div:

`<div role="grid" aria-rowcount="15" aria-colcount="2" aria-readonly="true">`

This div is causing screen readers to announce table mark-up (eg, row and column numbers). We want to change the role to "list" in order to prevent those announcements. 

Is it possible to change the role? If so, what is the best way to do so?

**Comment by paulgildea** [comment]
@castrodd Thanks for the feedback.

@dzearing - I don't know if there is a way to specifically change the role attribute directly on the `DetailsList` any insights?

As a work around you may be able to use the `List` component - https://developer.microsoft.com/en-us/fluentui#/controls/web/list it the component creates an HTML tree with `role=list`. Not sure if it will work for your scenario but it might be worth a try.

Hope that helps.

**Comment by dzearing** [comment]
It is not currently possible to change this role. I am not sure if that would cause additional issues either. Adding @cschlechty who may be able to confirm if this is something we'd want to allow.

**Comment by dzearing** [comment]
Also cc @ThomasMichon .

**Comment by cschlechty** [comment]
there need to be additional plumbing to change all of the children to match the roles. Using DetailsList is probably not the best choice to begin with. Is there a reason that List (as suggested above) doesn't work?

**Comment by castrodd** [comment]
Closing this issue as we found a workaround. @cschlechty List would work for us, but since we are within Azure DevOps there are certain constraints on the components that we have access to/are allowed to use. Thanks!
