### ISSUE TITLE
Add pattern as parameter to TextField... but without requirement of submit 

### ISSUE THREAD

**Issue by reijam** [microsoft/fluentui#15001]
I am just implementing a very simple pattern error call but it seems to me that it could just a easily be part of the TextField spec without requiring an error message.

Fairly simple change just create a Pattern parameter which is passed a regex (the  HTML input field already has a "pattern"  param that triggers on submit but who uses submit anymore?)   and then underline the text if it is incorrect.

For example  
` <TextField  onGetErrorMessage ={ v=> new RegExp ( "^[a-zA-Z ]*$").test(v) ? '' : 'Error:  Please learn your alphabet'  }    />  `

would become

` <TextField  Pattern={  "^[a-zA-Z ]*$" } />  `

And the result would be a squiggly red line instead of a smarty pants error message

**Comment by paulgildea** [comment]
@reijam Thanks for the feedback.

We've gotten similar feedback on this type of form validation scenario. It's a known missing feature we have. To set expectations it is something we're looking at implementing specifically for `Form` scenarios in the future, but I don't have any specific timelines to share at this time. 

Hope that helps. Looks like you are already familiar with the `onGetErrorMessage` API where you can provide your own validation logic, but yes having some shorthands for similar scenarios would be helpful.

**Comment by reijam** [comment]
Not a form based issue. And please don't make it one... 

If anything it should be a simple mod to the component independent of  whether it is part of a form or not

 async fetch is much easier to control than forms (  i cannot remember the last time I  used a form for anything). 
 
This could be no more than  or 4 LOC as a new parameter and would be very useful.

No need to make it a big deal... small but useful

**Comment by paulgildea** [comment]
@reijam Thanks for the clarification of this being a targeted feature on `TextField`

@JustSlone FYI

**Comment by davvit** [comment]
I would be happy to see something like this.

```
           <TextField
             label="Username"  required
             pattern="[A-Za-z]"
             patternError="Only letters please"
             value={this.state.username}
             onChange={(_) => { this.setState({ username: _.target.value }) }} />
             
            //If possible - ability to use of some pre defined patterns would be nice  
            
             <TextField  
             label="Username"  required
             pattern={Pattern.Alpha || Pattern.Numeric || Pattern.Email ||  Pattern.USPhone}
             patternError=" only  .....  allowed"
             value={this.state.username}
             onChange={(_) => { this.setState({ username: _.target.value }) }} />
          
```
thanks.
