### ISSUE TITLE
Northstar's Menu border is overlayed on the right side when Menu size fits content

### ISSUE THREAD

**Issue by davyrwoo** [microsoft/fluentui#15006]
### Environment Information

- **Package version(s)**: 0.51.0

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/optimistic-lamarr-yvqmu?file=/example.js

#### Actual behavior:

The ride side of the border is overlayed with a second border. This also is present when the Menu has the `pointing` prop.

This example is from [Fluent UI Northstar's Menu page](https://fluentsite.z22.web.core.windows.net/components/menu/definition):
![Menu Border](https://user-images.githubusercontent.com/56053686/92980865-6e184e80-f44c-11ea-9e74-bd4c9764c6e7.PNG)
 

#### Expected behavior:

Border on the right side should not be overlayed and the border should be equal to rest of the menu borders when the menu style fits content. Alternatively, having a prop that fits the menu size to the content, and have the proper behavior there. 

### Priorities and help requested:

Requested priority: Normal

**Comment by miroslavstastny** [comment]
Menu currently does not support `compact` layout.

It's not only about the double border, the border also does not match the border-radius of the container and background on hover overlaps:
![image](https://user-images.githubusercontent.com/9615899/93489962-2ee47480-f908-11ea-8a99-78ffe8c42631.png)
