### ISSUE TITLE
Datepicker does not allow the use of an input mask. Masked input does not allow the use DatePicker

### ISSUE THREAD

**Issue by wojciek** [microsoft/fluentui#15014]
### Environment Information

- **Package version(s)**: 7.137.0
- **Browser and OS versions**: Chrome 85.0.4183.102

### Describe the issue:

Standard Datepicker does not allow the use of an input mask. There is no way to make MaskedInput with datepicker and DatePicker with just Input mask. In this props interfaces there is no props to make this case. 

#### Actual behavior:

```
<DatePicker className={controlClass.control} placeholder="Select a date..." ariaLabel="Select a date" />
    
<MaskedTextField
    componentRef={inputRef}
    borderless
    onChange={inputHandler}
    value={value}
    placeholder={''}
    required
    mask="****-**-**"
    maskFormat={maskFormat}
    maskChar="_"
/>
```

#### Expected behavior:

Masked input allowing for simple implementation of the control with the possibility of datepicker or DatePicker with possibility for simple implementation of input mask (For example "****-**-**")

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@wojciek Thanks for the feedback.

I’ll mark this as a feature request and add it to our backlog, but to set expectations - we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. We'll take this into consideration when we converge the `DatePicker` and `Input` component across our two React packages.

In the mean time, @lorejoh12 do you have any ideas for a work around?

Thanks

**Comment by wojciek** [comment]
Great! 
The best solution for this input  control will be something like this - put MaskedInput into Picker: 
`                <DatePicker
                    aria-describedby={`tableTooltip${props.column.getColId()}`}
                    allowTextInput={true}
                    strings={DayPickerStrings}
                    disableAutoFocus={true}
                    componentRef={inputRef}
                    className={controlClass.control}
                    styles={pickerStyles}
                    maskedTextField={{
                        mask: '****-**-**',
                        maskFormat: {maskFormat},
                        maskChar: '_',
                    }}
                    placeholder="select date..."
                    ariaLabel="Select date"
                    value={moment(value, props.timeZone).toDate()}
                    onSelectDate={date => inputHandler(date)}
                    formatDate={(date: Date | undefined) => moment(date).format('yyyy-MM-dd'), props.timeZone)}
                />`
I don't want to just install another package to handle my input mask.
