### ISSUE TITLE
A Filepicker component  is needed

### ISSUE THREAD

**Issue by tiyee** [microsoft/fluentui#15011]
#### Describe the feature that you would like added

The Filepicker component is used to select one or multiple files from the file system.

**Comment by paulgildea** [comment]
@tiyee Thanks for the feedback.

I’ll mark this as a feature request and add it to our backlog, but to set expectations - we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. We'll take this into consideration when we converge the `FilePicker` component across our two React packages. I don't have any immediate timelines to share at this moment. 

As a workaround components like the `DetailsList` and `List` components provide a lot of fundamental building blocks to compose a FilePicker and tailor the experience specific to developers' application needs.

Hope that helps.

**Comment by jurokapsiar** [comment]
@tiyee can you please provide details on what is needed? As far as I know, it is only possible to open a default system open dialog (https://stackoverflow.com/questions/2048026/open-file-dialog-box-in-javascript) or add drag and drop functionality. I don't think this would be in the scope of a UI component library. But maybe I do not understand the requirement correctly, can you please be more specific?

**Comment by tiyee** [comment]
> @tiyee can you please provide details on what is needed? As far as I know, it is only possible to open a default system open dialog (https://stackoverflow.com/questions/2048026/open-file-dialog-box-in-javascript) or add drag and drop functionality. I don't think this would be in the scope of a UI component library. But maybe I do not understand the requirement correctly, can you please be more specific?

Provide a consistent visual experience as same as other components. We also need some hooks when opening file or finished uploading the file.
