### ISSUE TITLE
SpinButton's onBlur event does not receive the validated value

### ISSUE THREAD

**Issue by jayantdhawan** [microsoft/fluentui#15012]
### Environment Information

- **Package version(s)**: 7.105.12
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:
1. Go to the codepen linked above.
2. See that the bounds of the spin button are set as 0 and 50.
3. Enter a value greater than 50.
4. The spin button resets the value to 50, but the onBlur event receives the original value (through the event parameter).

#### Expected behavior:
SpinButton's `_defaultOnValidate` (or `props.onValidate`, if it is defined) is only called when the user focuses out of the button input area. Immediately after that, the code calls the `onBlur` event, if it is defined. If the validation updates the value to something other than what the user entered (as in this case, to the max value), then the onBlur event should receive the updated value, and not the original value.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: NA

**Comment by paulgildea** [comment]
@jayantdhawan Thanks for the feedback.

@khmakoto as FYI on the expected behavior.

**Comment by miroslavstastny** [comment]
In v0, callbacks pass back the original event and patched component props. In v7 only the original event is passed to the callback.

Technically, this can be a simple fix - in `_onBlur`
https://github.com/microsoft/fluentui/blob/e7b119a05ef8a4aa254df00320f3672298617ade/packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx#L325-L331

the event can just be patched with the last valid value:
```js
if (this.props.onBlur) {
  ev.target.value = this._lastValidValue;
  this.props.onBlur(ev);
}
```

Before doing that I would like to know @dzearing opinion on what the correct approach in v7 is.

**Comment by ecraig12345** [comment]
Once an `onChange` callback is added to SpinButton in version 8 (currently in PR, see #16137), you'll be able to use that to access the new value after validate, increment, or decrement. This doesn't solve the specific issue you mentioned with onBlur, but might help depending on your overall scenario (you could check `event.type` if you specifically care about blur events).
