### ISSUE TITLE
ODLink(E4BB) &ODLink12(E4BC) icons missing in fabric 

### ISSUE THREAD

**Issue by chaofeng2014** [microsoft/fluentui#15026]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

We need these 2 existing icons `ODLink(E4BB) & ODLink12(E4BC)` in https://uifabricicons.azurewebsites.net/
![image](https://user-images.githubusercontent.com/6550896/93137314-1b2fd880-f692-11ea-97a6-6e94e8f6faa9.png)
but when we check the fabric icons, they are not existed. https://developer.microsoft.com/en-us/fluentui#/styles/web/icons
![image](https://user-images.githubusercontent.com/6550896/93137270-0b17f900-f692-11ea-95f8-e8432736bf74.png)

Can you guys add these 2 icons in fabric so we can consume these 2 icons with 
import { Icon } from 'office-ui-fabric-react/lib/Icon';
<Icon iconName={'ODLink'} className=<test_ODLink> />

I tried consume these 2 icons with <Icon iconName={'ODLink'} className=<test_ODLink> /> in codepen, not working.

Alternatively, you can also use https://aka.ms/fluentdemo to get permanent repro links if the repro occurs with an example.
(A permanent link is preferable to "use the website" as the website can change.)
-->

#### Actual behavior:

icons `ODLink(E4BB) & ODLink12(E4BC)` in https://uifabricicons.azurewebsites.net/
![image](https://user-images.githubusercontent.com/6550896/93137314-1b2fd880-f692-11ea-97a6-6e94e8f6faa9.png)
but missing in farbic:
https://developer.microsoft.com/en-us/fluentui#/styles/web/icons
![image](https://user-images.githubusercontent.com/6550896/93137270-0b17f900-f692-11ea-95f8-e8432736bf74.png)

#### Expected behavior:

We want to add these 2 icons in fabric. 

### Priorities and help requested:
We are using this icon in A2OD feature that is going to show in ignite and release this year. Currently we are using another icon instead, but design want us show these link icons asap if possible. 

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: High

Products/sites affected: ODSP

**Comment by paulgildea** [comment]
@chaofeng2014 Thanks for the feedback.

@dzearing - Has the process changed between what's available between the site and what's in the library?

**Comment by dzearing** [comment]
@chaofeng2014 don't you have a custom font generated from the aka.ms/fabric-icons tool? You should be able to generate a custom slimmed down one including the extra icons.

AFAIK we have not regenerated the official icon font due to constant bundle size increases (and also due to designers working on the new icon set.)

**Comment by chaofeng2014** [comment]
@dzearing @paulgildea thank you for looking into this. 
I checked with Peter Jahn and found we were using custom subset in odsp, but the recent itemsScope revert back to using default fabric set. I will check with someone in odsp and close this if I make sure custom subset is still the way we should go.

**Comment by chaofeng2014** [comment]
Checked with Pat and we are going to use custom subset of fabric icons, so this is not necessary. Closing this bug. Thanks.
