### ISSUE TITLE
Version 7+ of @uifabric/icons causes an UI bug in our searchbox component. When a tile is clicked, the searchbox loses its styling. 

### ISSUE THREAD

**Issue by lserry** [microsoft/fluentui#15023]
### Environment Information

- **Package version(s)**: Version 7+ of @uifabric/icons
- **Browser and OS versions**: IE 11 in win32 dialog

Version 7+ of @uifabric/icons causes an UI bug in our win32 dialog in Office. Example Dialog Entry point: 
win32 ppt: Insert -> Pictures -> stock images.  When a search suggestion is clicked, the searchbox loses its styling and causes the entire dialog to shift up, showing new whitespace at the bottom.

Downgrading to  version 6 fixes this issue for now. It only happens on the Win32 dialog, which is running IE 11. However, it does not repro on standalone IE, only in the Win32 dialog.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/71286981/93124956-4826c000-f67f-11ea-8b45-5ddc8691cf63.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/71286981/93125017-612f7100-f67f-11ea-9b8c-eb7ad9164ac4.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) - Normal

Products/sites affected: (if applicable): win32 stock images Dialog

**Comment by paulgildea** [comment]
@lserry Thanks for the feedback.

@JustSlone - Is there someone on the Office team we can partner with on this issue?

**Comment by JustSlone** [comment]
Confirmed repro (see gif below).

@lserry it seems strange that the icons package would cause this though, it doesn't seem like the repro has any interaction with icons, it's with the suggestions below the search box. Do you have more details on why the icons package is causing an issue here?

![PP-style-repro](https://user-images.githubusercontent.com/40304143/93620616-22572f00-f98f-11ea-8839-96a13bafd8ec.gif)
