### ISSUE TITLE
24px icons missing from 20200727

### ISSUE THREAD

**Issue by hjonasson** [microsoft/fluentui#15034]
### Environment Information

- **Package version(s)**: 20200727.001

### Describe the issue:

Icons of size 24px don't seem to be on the CDN for this package version, as can be verified on this link for example
https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20200727.001/assets/item-types/24/pptx.svg

Change the 24 to other supported sizes like 20, 16, or 96
https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20200727.001/assets/item-types/96/pptx.svg
You get the icon.

Are you willing to submit a PR to fix? (Yes, No)

I assume this is a matter of uploading resources to a cdn which I probably can't do. If I can help however please let me know.

Requested priority: (Blocking, High, Normal, Low)

Not low as this is in production for us.

Products/sites affected: (if applicable)

OneDrive

**Comment by paulgildea** [comment]
@hjonasson Thanks for the feedback.

@miroslavstastny - You might have to follow up with @dzearing to understand who to contact about the CDN ownership now.

**Comment by dzearing** [comment]
@bigbadcapers and @ThomasMichon would be able to help with filetype icon assets.

**Comment by hjonasson** [comment]
Has anybody managed to look at this?

**Comment by paulgildea** [comment]
@hjonasson Thanks for staying with us.

@bigbadcapers / @ThomasMichon - Is there someone else we should follow up with?

**Comment by bigbadcapers** [comment]
@paulgildea Any mention of the FabricCDN should get updated to refer to version 20200921.001 -- that is the latest one and has all the freshest filetype icons. There shouldnt be sizes missing, eg https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20200921.001/assets/item-types/24/pptx.svg works.

**Comment by hjonasson** [comment]
Thanks for looking into it. I will forward this suggestion :D

**Comment by bigbadcapers** [comment]
Hello @hjonasson can we close this issue?

**Comment by hjonasson** [comment]
Please do. Thanks a lot.

Þann lau., 3. okt. 2020, 01:18 C. Perez skrifaði <notifications@github.com>:
