### ISSUE TITLE
Keyboard navigation stops working in CommandBar when ComboBox is used onRender

### ISSUE THREAD

**Issue by ArpithaMurthy** [microsoft/fluentui#15036]
### Environment Information

- **Package version(s)**: 7.137.1
- **Browser and OS versions**: Issue seen in Chrome: Version 85.0.4183.102 (Official Build) (64-bit)
                                                                        Edge: Version 85.0.564.51 (Official build) (64-bit)

### Describe the issue:
Once keyboard focus enter **ComboBox** within **Commandbar**,  arrow key will not work for navigation to other elements
This happens only when allowFreeform prop is false(which is by default false, so if we don't set bug happens by default)

#### Actual behavior:
In CommandBar when ComboBox is used onRender keyboard focus gets traped inside combobox and arrowkeys will not work for navigation 

#### Expected behavior:
All components inside Commandbar should be navigable from keyboard

### If applicable, please provide a codepen repro: https://codepen.io/arpithadmurthy/pen/bGpKqPz
Try navigation using tab then right arrow to move to next element focus gets trapped inside combobox

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
I can try, need to look into code 

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (https://workplaceanalytics-ppe-staging.office.com/en-us/Plans/Manage)

**Comment by ArpithaMurthy** [comment]
If Dropdown is used within CommandBar this problem is not present, codepen: https://codepen.io/arpithadmurthy/pen/RwaYboj
Is Dropdown will be depreciated in FluentUI or is it going to stay?

**Comment by paulgildea** [comment]
@ArpithaMurthy Thanks for the feedback.

Both the `Dropdown` and `ComboBox` are supported components. `ComboBox` allows user content to select the options where the `Dropdown does not - so this issue might be by design.

@joschect - Thoughts on the the difference in the default behavior here with `ComboBox` and `Dropdown`

**Comment by miroslavstastny** [comment]
With `allowFreeform=false` (and `autoComplete === 'on'`) `ComboBox` stops propagation of keyboard events.
In that case `FocusZone` in `CommandBar` does not receive the event to set focus to next/previous CommandBar item.

https://github.com/microsoft/fluentui/blob/a89efd72e645e6e20869d6f33717f11554a8711a/packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx#L2010-L2020
