### ISSUE TITLE
Screen reader(narrator) should read deleted letter in edit text field.

### ISSUE THREAD

**Issue by ArpithaMurthy** [microsoft/fluentui#15037]
### Environment Information

- **Package version(s)**: 7.137.1
- **Browser and OS versions**: Edge: Version 85.0.564.51 (Official build) (64-bit)

### Describe the issue:

Screen reader is not reading deleted letter in edit text field. This is happening only in Edge browser, in chrome it is working as expected

### Please provide a reproduction of the issue in a codepen: 
FluentUI CodePen: [Textfield Example](https://codepen.io/arpithadmurthy/pen/WNwyqZR)
React CodePen: [ReactTextField](https://codepen.io/gaearon/pen/VmmPgp?editors=0010)
It works as expected in chrome browser Version 85.0.4183.102 (Official Build) (64-bit) and Mozilla Firefox 80.0.1 (64-bit), Problem is with Edge. I tested react text filed also there is same problem, so I am suspecting issue is not with fluentUi but with Edge browser

#### Actual behavior:

Currently screen reader(narrator) is reading letters only when they are typed not when deleted.

#### Expected behavior:

Screen reader(narrator) should read deleted letter in text edit field.

### Documentation describing expected behavior
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Comment by smhigley** [comment]
It repros in Edge v85 but not Edge v87 (the canary build, currently) for me, so I'm guessing they've already fixed it :)

**Comment by miroslavstastny** [comment]
Confirming what @smhigley wrote - broken in Edge 85, works in Edge 87, closing
