### ISSUE TITLE
DetailsList render on resize delayed

### ISSUE THREAD

**Issue by andreibsk** [microsoft/fluentui#15045]
I'm experiencing an unusual/unexpected behavior while resizing lists build with the `DetailsList` component. I'm not sure if this behavior is intentional (perhaps for performance reasons), but given that other components on the page render "normally", the following delay tends to stand out as being non "fluent" or choppy.
The following issue might be relevant: #6567

### Environment Information
- **Package version(s)**: tested with 7.121.10, 7.137.1
- **Browser and OS versions**: Windows 10 (Version 2004), tested with Chrome 85.0.4183.102 (Official Build) (64-bit) and Firefox 79.0

### Please provide a reproduction of the bug in a codepen:
[https://codepen.io/andreibsk/pen/abNjZXP](https://codepen.io/andreibsk/pen/abNjZXP)
[Gif animation resizing the above example](https://user-images.githubusercontent.com/3344848/93225482-f06d7f00-f77a-11ea-89ab-1b085203d45e.gif)
Codepen created from the [DetailsList - Basic](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic) usage example.
Can be reproduced by horizontally resizing the rendered page container while having the code files to the side. Having all items in the list checked helps visualizing.

#### Actual behavior:
Rendering of the list seems to be temporarily disabled or delayed until after the horizontal resize movement has stopped (+ after a seemingly fixed time span has passed).

#### Expected behavior:
The rendering of the list should continue even while resizing is taking place (as most components do). As far as I can tell the Basic List / `List` component renders as expected.

### Priorities and help requested:
Are you willing to submit a PR to fix? No
Requested priority: Normal
Products/sites affected: fluentui/DetailsList component

**Comment by paulgildea** [comment]
@andreibsk Thanks for the feedback.

@miroslavstastny you might have to partner with @dzearing on this one.

**Comment by dzearing** [comment]
This is by design, though not ideal and there's always room for tweaks. When rendering many columns and rows, performance of resizing can be pretty penalizing, so there's a debounce happening on resize.

I believe the debounce could be changed to a RAF to improve this without freezing the browser.
