### ISSUE TITLE
Add multi select support for Tree as a list 

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#15041]
#### Describe the feature that you would like added
Curently Fluent UI has Tree variant "As a list"
https://fluentsite.z22.web.core.windows.net/components/tree/definition#usage-tree-as-list-example
which purpose is to use it on the MAC for the accessibility reason. (as VoiceOver doesn't support tree properly) 

We would need to add similar "As a list" for the "multi selectable" tree. 

#### What component or utility would this be added to
I tried it very rafly in this PR:
https://github.com/microsoft/fluentui/pull/15035/files
and tested the concept on MAC with VoiceOver and it was reasonable. 

#### Have you discussed this feature with our team, and if so, who
No discussion with the team.

**Comment by paulgildea** [comment]
@miroslavstastny Do we just need sign off for @kolaps33 PR? Marking as feature.
