### ISSUE TITLE
SearchBox focus() does not set focus to input

### ISSUE THREAD

**Issue by trsvax** [microsoft/fluentui#15076]
### Environment Information

- **Package version(s)**: 7.137
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/trsvax/pen/XWdPJjy

#### Actual behavior:

example with ref does not set the focus. Example with ref2 does in my code but not completely in codepen. I think it's also messing with focus

#### Expected behavior:

calling focus() on the ref should set the focus.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Low

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@trsvax Thanks for the feedback and codepen. It's appreciated!

**Comment by miroslavstastny** [comment]
You should not call `setState` on the `componentRef`.

Once you call `focus()`, the search box is focused but the `hasFocus` is set asynchronously (it is a regular React state) - that's why you still see `false` immediately after calling `focus()`. If you need to perform an action when the SearchBox is focused, you can use `onFocus` prop.

This code works as expected:

```jsx
/* eslint-disable react/jsx-no-bind */
const SearchBoxFullSizeExample = () => {
  const ref = React.useRef(null);

  React.useEffect(() => {
    ref.current.focus();
    console.log('Setting focus')
    console.log("hasFocus should be still false: ", ref.current.state);
    setTimeout(() => {
          console.log("hasFocus after timeout should be true: ", ref.current.state);

    }, 0)
  }, []);
  
  const onFocus = React.useCallback(() => {
    console.log('Focus received');
  }, []);
  
  return (
      <SearchBox placeholder="Search" componentRef={ref} onFocus={onFocus} />
  );
};
```

And logs following output:
```
Focus received

Setting focus

hasFocus should be still false:  Object {
  hasFocus: false,
  value: ""
}

hasFocus after timeout should be true:  Object {
  hasFocus: true,
  value: ""
}
```
