### ISSUE TITLE
DetailsList multi selection using keyboard

### ISSUE THREAD

**Issue by shaikshavalis** [microsoft/fluentui#15073]
### Environment Information

- **Package version(s)**: not specific to version, latest version can be used
- **Browser and OS versions**:  NA

### Please provide a reproduction of the bug in a codepen:

![image](https://user-images.githubusercontent.com/9265381/93382476-cbaeff80-f87f-11ea-8877-cb410509e0fe.png)

#### Actual behavior:
I was able do multi selection as shown in above with mouse but when we use keyboard it's not working. ctrl + enter key is selecting the current item and remaining items are unchecked. 

#### Expected behavior:

ctrl+enter should retain other rows check/uncheck status and should only change current item check/uncheck state.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Bing webmasters

**Comment by paulgildea** [comment]
@shaikshavalis Thanks for the feedback.

@dzearing Is this one by design? When I have `selectionMode={SelectionMode.multiple}` I can only select multiple items with  when holding down `Shift` and arrowing.  Even when I removed `MarqueeSelection` it still had that same behavior.

**Comment by dawolff-ms** [comment]
@paulgildea we just received an A11Y bug for this issue. Has this been resolved?

**Comment by Alex1100** [comment]
This is also an issue when we click on the item row. It seems like unless you specifically click on the checkbox this will cause all other selected items to be unchecked.

Could we please not have that be the case. If we jus enable the inverse to be the default behavior it will fix the A11y issue and the onClick issue that I am sure many others such as myself face quite often.

**Comment by gladyswng** [comment]
Wondering if the issue above has been fixed, it seems like it remains the same with the version I'm using, it's easier if the selected items remains checked when click on other item row.

**Comment by paivybhav99** [comment]
Hey guys, I have received an a11y bug for unable to select multiple items from drop down via keyboard. 
Any update on this issue?

**Comment by spmonahan** [comment]
Multiple items can be selected via the keyboard using `ctrl + space` to toggle selection and `ctrl + arrow up/down` to navigate the list. [The `DetailsList` documentation was recently updated to include a list of supported keyboard shortcuts](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist#keyboard--hotkeys).
