### ISSUE TITLE
Radio Group with long labels cause radio circles to distort

### ISSUE THREAD

**Issue by brycepolly** [microsoft/fluentui#15080]
### Environment Information

- **Package version(s)**:  0.51
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a codepen: 
https://codesandbox.io/s/eiinc?module=/example.js

#### Actual behavior:

![image](https://user-images.githubusercontent.com/61526364/93397855-4c91db00-f82f-11ea-9477-ab7796511bd7.png)

#### Expected behavior:

Radio circles do not change

### Priorities and help requested:

Are you willing to submit a PR to fix? ( No)

Requested priority: (Normal)

Products/sites affected: react-northstar

**Comment by miroslavstastny** [comment]
Confirming, `radiogroup__item__indicator` should have `flex-shrink: 0`.

**Comment by YuanboXue-Amber** [comment]
Hi @brycepolly, this issue is addressed by PR #14895 , where the `RadioGroupItem` indicator is done by an icon instead of 50% border radius. May I close this issue?
