### ISSUE TITLE
multiSelect prop documentation missing on ComboBox Interface

### ISSUE THREAD

**Issue by rhuanbarreto** [microsoft/fluentui#15088]
On the page https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox it's missing the `multiSelect` prop for the ComboBox component.

**Comment by paulgildea** [comment]
@rhuanbarreto Good find! Thanks for the feedback.

**Comment by miroslavstastny** [comment]
The same applies to `Dropdown`
