### ISSUE TITLE
Make the chart title customizable for MultiStackedBarChart 

### ISSUE THREAD

**Issue by progvasu** [microsoft/fluentui#15090]
#### Describe the feature that you would like added

Right now we can just define a string that gets placed on the top of the bar like below
![image](https://user-images.githubusercontent.com/9596649/93475714-943f6200-f916-11ea-8bca-cdbc2ff8cd78.png)
 
I am suggesting adding one more string placeholder on the right side of the title as below, it can help give out (explain) more details on what sort of metric is being used for the numbers being displayed in the chart. For the particular use case I am interested in I want to display that the below numbers are percentages instead of whole counts.
![image](https://user-images.githubusercontent.com/9596649/93475610-7245df80-f916-11ea-9964-04954365e52c.png)

#### What component or utility would this be added to

MultiStackedBarChart in the charting package.

#### Have you discussed this feature with our team, and if so, who

No, not yet. It would be great if I could connect to someone.

**Comment by paulgildea** [comment]
@progvasu Thanks for the feedback.

@Raghurk FYI

**Comment by progvasu** [comment]
Having a second title on the right will make it hard for screen readers to interpret the title. Closing the issue.
