### ISSUE TITLE
Checkbox: passing role as a prop is not assigning role to the Checkbox

### ISSUE THREAD

**Issue by gopalgoel19** [microsoft/fluentui#15092]
### Describe the issue:

When passing role as a prop to Checkbox component, it is not having any effect and the HTML remains the same with and without the assigned role.

I am working on a scenario where I have a `List` of `Checkbox` in a dropdown. I am thinking of following `menu`/`menuitemcheckbox` roles pattern. Here the `List` would have a role of `menu` and individual `Checkbox` would have a role `menuitemcheckbox`.

### Please provide a reproduction of the issue in a codepen:

Codepen: https://codepen.io/gopalgoel19/pen/MWyqrPP

In https://github.com/microsoft/fluentui/issues/13483 I see @jurokapsiar talking about a multi-select scenario which is what I am looking for. If `listbox`/`option` pattern fits best in the above-mentioned scenario, then we should have an option of overriding the default behaviour using the `role` prop.

**Comment by paulgildea** [comment]
@gopalgoel19 Thanks for the feedback. Out of curiosity, it sounds like you wanted to build a `Dropdown` experience that contains checkboxes? If your desired experience is to build a multi-select `Dropdown` have you looked at the `Dropdown` example: https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown
![image](https://user-images.githubusercontent.com/33229964/93634716-e9768480-f9a5-11ea-8b3f-0223b48e977e.png)

@dzearing - This seems more like an API model question all up between passing HTML atrributes as props. Or could @gopalgoel19 use `inputProps` to pass the `role` attribute?

**Comment by gopalgoel19** [comment]
@paulgildea yes I have checked that but it felt like it doesn't work for my case because I want additional controls in the dropdown. 
I tried your `inputProps` suggestion and it works for me. I am able to pass role which is getting assigned correctly.
