### ISSUE TITLE
When narrator is ON, user is not able to expand combobox

### ISSUE THREAD

**Issue by NandhiniSrinivasaSubramanian** [microsoft/fluentui#15139]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Edge + Narrator on Windows devices

### Describe the issue:
1. Turn narrator ON.
2. Swipe to combo box
3. Double tap to expand.

### Please provide a reproduction of the issue in a codepen:
https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox 
https://codepen.io/nandhinisrinivasasubramanian/pen/eYZQvrM

#### Actual behavior:
The combo box does not expand to show all options.

#### Expected behavior:
The combo box should expand

Similar issue in Android and iOS devices: https://github.com/microsoft/fluentui/issues/14370

**Comment by paulgildea** [comment]
@NandhiniSrinivasaSubramanian Thanks for the feedback.

@joschect / @betrue-final-final - Is this by design? I understand the difference between `Dropdown` and `ComboBox` is that the `ComboBox` allows free form content to be inputed by the user and not immediately select pre-defined options from a menu.

@smhigley - FYI on the a11y pattern.

**Comment by suchk** [comment]
I can confirm the same behavior for my team. In our case, we're setting autocomplete to on, and allowfreeform to false.

@paulgildea has there been any traction on this?

**Comment by paulgildea** [comment]
@joschect ping. 

@suchk / @NandhiniSrinivasaSubramanian Can the user expand the `ComboBox` with additional steps? or are they completely blocked from expanding the `ComboBox`?

**Comment by suchk** [comment]
@paulgildea Turning off scan mode will allow the user to expand the combobox, and select options using the up/down arrow keys. Not ideal, but at least it's not totally hosed.
