### ISSUE TITLE
Selectable Tree should have hover background for items

### ISSUE THREAD

**Issue by assuncaocharles** [microsoft/fluentui#15135]
### Environment Information

- **Package version(s): @fluentui/react-northstar@0.51.0
- **Browser and OS versions: Chrome Version 85.0.4183.102

#### Actual behavior:

Hovering items as no style change or indicator. 

#### Expected behavior:

As per spec, item should have background to indicate ( Similar to selectable list ).

<img width="283" alt="Screen Shot 2020-09-19 at 13 17 18" src="https://user-images.githubusercontent.com/8545105/93665986-eb5e4780-fa7a-11ea-9973-0b1a233d8072.png">

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by paulgildea** [comment]
@assuncaocharles Thanks for the feedback. Once @miroslavstastny can root cause the issue I would love to welcome you to submit a PR the for fix.

Thanks!
