### ISSUE TITLE
Left Arrow doesn't work on last level of expanded Tree

### ISSUE THREAD

**Issue by assuncaocharles** [microsoft/fluentui#15134]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.51.0
- **Browser and OS versions**: Chrome Version 85.0.4183.102 

### Please provide a reproduction of the bug in a CodeSandbox: https://codesandbox.io/s/4or8j?module=/example.js

The bug seems to be on the `TreeTitle` component behaving different from `TreeItem` since in the last level the focusable element is the `TreeTitle`. ( Maybe it's a good opportunity to merge both components in one and simplify it ) 

#### Actual behavior:

Using keyboard, focus first level and press right arrow to expand and reach the last level then press arrow left, it stuck in the last level. 

#### Expected behavior:

When focus in the last level and pressing left arrow focus should go to parent and subsequent arrow left press should collapse parent. 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

**Comment by paulgildea** [comment]
@assuncaocharles Thanks for the feedback. Sorry I had a bug in my main triage query omitted issues already tagged with northstar.
