### ISSUE TITLE
DialogType.normal behaves as DialogType.close

### ISSUE THREAD

**Issue by DiegoGorgazzi** [microsoft/fluentui#15130]
### Environment Information

- **Package version(s)**:  7.126.1
- **Browser and OS versions**:  Chrome 85.0.4183.102 , Edge  85.0.564.51

### Please provide a reproduction of the bug in a codepen:

https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog

#### Actual behavior:
DialogType.normal shows "X" at top right corner:

![image](https://user-images.githubusercontent.com/44508750/93648189-05d2eb00-f9bf-11ea-90ed-0b5064bb1d6e.png)

#### Expected behavior:

No "X" should show on top right corner:

![image](https://user-images.githubusercontent.com/44508750/93648249-2602aa00-f9bf-11ea-9e42-d87641e5156f.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: HIGH

Products/sites affected: All Microsoft sites using UI Fabric and UI Fluent

**Comment by paulgildea** [comment]
@DiegoGorgazzi Thanks for the feedback.

**Comment by DiegoGorgazzi** [comment]
> @DiegoGorgazzi Thanks for the feedback.
> 
> @joschect Do you know if this is by design? The blocking `Dialog` does respond to `DialogType.largeHeader` so this leads me to believe that this may be an issue. But I could see this as by design in that it allows a user to effectively escape a blocking dialog without having to make a specific choice.

I should say this issue also applies to Modeless Dialog, not just the blocking type, so I don't believe it is by design.

There are many situations where you do not want the user to escape a dialog, for example, when accepting terms of service.
