### ISSUE TITLE
Documentation issue on https://developer.microsoft.com/en-us/fluentui#/controls/web/callout

### ISSUE THREAD

**Issue by timothyhoffmann** [microsoft/fluentui#15145]
### Environment Information
https://developer.microsoft.com/en-us/fluentui#/controls/web/callout

### Describe the issue:
The sample code does not appear to be functioning correctly. 

#### Actual behavior:
If one clicks the `Show Callout` button in the `Callout that covers the target element` section the callout appears up on the top of the page in the `Default Callout` section.  Ditto all the other Show buttons below the Default section.

#### Expected behavior:

I would expect the Callout to display near the Show button in the section where the button displays.

### If applicable, please provide a codepen repro:
N/A

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) Low

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@timothyhoffmann Thanks for the feedback.

I noticed a weird inconsistency. I can repo your issue that you call out above. However, when I press the `Show Code` tab, and then click the `Show Callout` button again it behaves as expected.

@miroslavstastny - Please determine if this is a sample issue or a component issue.

@joschect FYI

**Comment by miroslavstastny** [comment]
This is just an issue with the samples. They all use classname as `target`:
```jsx
target={`.${styles.buttonArea}`}
```
The classname form buttonArea is not unique per example, all examples end up using the same classname.

(The reason why it works for an example which is being edited is that for that one a different classname for buttonArea is used.
