### ISSUE TITLE
After expanding combobox, swipe takes the focus to next actionable item instead of the combo box list items

### ISSUE THREAD

**Issue by NandhiniSrinivasaSubramanian** [microsoft/fluentui#15141]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Safari and iOS devices version 13.3.1 with VoiceOver

### Describe the issue:
1. Turn VoiceOver On.
2. Swipe to the combo box.
3. Double tap to expand the combo box
4. Swipe again

### Please provide a reproduction of the issue in a codepen:

https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox

#### Actual behavior:
The focus goes to the next actionable item like button

#### Expected behavior:
The focus should go to the combo box option list items

**Comment by paulgildea** [comment]
@NandhiniSrinivasaSubramanian Thanks for the feedback.

@joschect / @betrue-final-final - Is this one by design as well like #15139 ?

@smhigley FYI
