### ISSUE TITLE
Need a prop in Callout component to prevent dismiss upon window changed

### ISSUE THREAD

**Issue by romanisa** [microsoft/fluentui#15156]
#### Describe the feature that you would like added

Commit https://github.com/microsoft/fluentui/pull/14363 in Callout component has introduced a regression in scenarios where the callout needs to be kept open even when window is changed. In scenarios where customer has entered some data on the callout form and is in middle of saving it, if user changes window or browser tab then user loses all the information entered. 

Hence we need a prop on the Callout component something like 'preventDismissOnWindowChanged' to prevent this. 

#### What component or utility would this be added to

Callout component

#### Have you discussed this feature with our team, and if so, who

Filing this issue as per suggestion from ecraig12345 in this commit thread: https://github.com/microsoft/fluentui/pull/14363

**Comment by jodom** [comment]
@romanisa have you tried using `preventDismissOnLostFocus` ?

**Comment by romanisa** [comment]
preventDismissOnLostFocus is slightly different. We do not want to prevent dismiss when focus is changed to another component on the same document. For eg: if user intentionally clicks outside the callout, we do want to dismiss the callout.

**Comment by paulgildea** [comment]
@romanisa Thanks for filing this issue.

@ecraig12345 is this being addressed by this PR? #15161 ?

**Comment by ecraig12345** [comment]
No, #15161 is just porting #14363 to react-next. We should get @joschect's input on this, but from what I can tell it might be necessary to add a new prop to disable the new dismiss on blur behavior (since it's desirable in some cases but not others).
