### ISSUE TITLE
TeachingBubble long button strings do not render nicely

### ISSUE THREAD

**Issue by richardtagger** [microsoft/fluentui#15158]
When text provided to teaching bubble buttons is long the wrapping looks buggy. We do not really have control over the length of text as some languages are more verbose and will have copy that exceeds the English so this control should accommodate text getting reasonably long.

### Environment Information

- **Package version(s)**:  office-ui-fabric-react "7.121.5"

### Please provide a reproduction of the bug in a codepen:

![image](https://user-images.githubusercontent.com/692240/93823801-47f66980-fc17-11ea-9995-19907582e927.png)
https://codepen.io/richardtagger/pen/YzqRJJp

#### Actual behavior:

Buttons wrap is ugly

#### Expected behavior:

Button wrap looks less buggy

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: yammer.com

**Comment by paulgildea** [comment]
@richardtagger Thanks for the feedback.

@betrue-final-final Do we designs defined for primary and secondary buttons that have large strings? I would expect that the bottoms stack vertically, and are bottom, end (logical)/right (physical) aligned.

**Comment by richardtagger** [comment]
Bump @paulgildea is there any update on when a fix might be prioritized for this?
