### ISSUE TITLE
A proposal for having a photo picker component

### ISSUE THREAD

**Issue by irakaundal98** [microsoft/fluentui#15179]
### Description

Our team owns a profile photo picker component that allows the user to upload an image, drag the image in the frame, and allows zooming in/out. The user has options to Apply/Cancel/Remove the image. We have exposed it both as a modal and an inline option. We display the user initials in case the user hasn't uploaded any picture.

### Which product teams/scenarios need this control

We already have many teams consuming this control and hence thought it would be a good idea to convert it to a fluent component.

### Design assets

![image](https://user-images.githubusercontent.com/52814187/93978595-d8f54e00-fd99-11ea-8f94-4734761ffe59.png)

### Component ownership

I own the component in my team so I can help maintain this component. I can request for more support from my team.

### Imports/Dependencies

Only needs components/methods from fluent UI library:

- Buttons
- getInitials, getRTL, getPersonaInitialsColor
- MessageBar (for displaying messages like: Uploaded image is too small)
- Slider

### Exports/Component breakdown

- Header (Title and dismiss)
- InfoBar (MessageBar)
- EditCanvas (canvas + slider)
- Footer (end actions: Apply/Cancel/Remove)

### Intended package/s

Prototype component

## Component code

I can give the code reference of our component if you find this to be a valid proposal.

### Example code

```

```

### Public methods

| Name  | Type       | Description               |
| ----- | ---------- | ------------------------- |
| focus | () => void | Sets focus on the control |

### Slots

| Name | Type | Description           |
| ---- | ---- | --------------------- |
| root | div  | The outermost element |

### Tokens

| Name      | Type  | Default Value | Description                |
| --------- | ----- | ------------- | -------------------------- |
| textColor | color | theme.white   | text color for the control |

### Props

| Name      | Type   | Default Value | Description                                 |
| --------- | ------ | ------------- | ------------------------------------------- |
| className | string |               | Optional class name to be added to the root |

### Todos

- [ ] Add Todos

### Steps

- [ ] Themable
- [ ] Unit tests
- [ ] Visual tests
- [ ] Documentation and examples
- [ ] Keyboard Accessible
- [ ] High Constrast Support
- [ ] RTL Support
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by paulgildea** [comment]
@JustSlone Let's discuss this proposal to see if this is a good candidate as a community component.

@irakaundal98 Interesting component! Thanks for providing proposal! 

We're going to discuss this and see where the best place to put this type of component. I love that it's using the Fluent UI primitive components and this type of scenario is super useful. We're in the early stages of bootstrapping the best place for these types of components that the community builds so if you are up for some trailblazing this might be a great opportunity to help us define that pattern so that other contributors can follow for these types of controls in the future.

So let us know if you are interested in that too.

**Comment by irakaundal98** [comment]
@paulgildea great to know you find this component a good fit! I'll be glad to take up this opportunity to define the pattern. Please let me know post your discussion, whether we are good to move forward with this feature request so that I can internally discuss it with my team.

**Comment by powerchelle** [comment]
Would this replace the component in 1JS? https://dev.azure.com/office/Office/_git/1JS?path=/midgard/packages/photo-picker
AMC would be interested in using and/or contributing to a common component that could be shared across Microsoft.

**Comment by irakaundal** [comment]
@powerchelle Yes, that's the idea. According to the last update, the process for enabling community modules was being worked on. @paulgildea, @JustSlone are we in a state now to work on implementation?

**Comment by JustSlone** [comment]
@irakaundal, @powerchelle (CC @paulgildea) 
In my opinion now is a good time to explore this, though it would involve a little trail blazing. 

Do you have someone from Design that could collaborate with Fluent UI Designers on a design spec for this component?
