### ISSUE TITLE
TypeError: e.toLocaleLowerCase is not a function

### ISSUE THREAD

**Issue by xuke444** [microsoft/fluentui#15178]
### Environment Information

- **Package version(s)**: (fill this out) 7.117.0
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:
When use combox, 
sometimes autofill.js will throw error on toLocaleLowerCase 
TypeError: e.toLocaleLowerCase is not a function
    at toLocaleLowerCase (../../../node_modules/office-ui-fabric-react/lib/components/Autofill/Autofill.js:348:16)
    at _doesTextStartWith (../../../node_modules/office-ui-fabric-react/lib/components/Autofill/Autofill.js:336:52)
    at _getDisplayValue (../../../node_modules/office-ui-fabric-react/lib/components/Autofill/Autofill.js:211:31)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes)

Requested priority: (High)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@xuke444 Thanks for the feedback. It would be super helpful if you could provide an isolated codepen because that will help us reproduce the issue you are seeing. Thanks!

**Comment by xuke444** [comment]
I don't have repo :(
This shows up in our log, 1 case a while, probably after hundred of thousands usage.
But based on the code, that particular line of autofill, is it possible to add a checking there? My assumption is that either text or startWith (suggest value/input value) have different type than string. Having an extra check of type could mitigate the issue.

**Comment by paulgildea** [comment]
@xuke444 No worries. Would you be willing to submit a PR with some error checking to see if that helps at least catch the exception?

@JustSlone FYI

**Comment by xuke444** [comment]
sure, if above proposal is ok to your team, there should be only few lines change. I can probably submit a pr next week.

**Comment by JustSlone** [comment]
@xuke444, we're in the middle of a large scale move of packages in the repo, so to spare you a lot of merge conflicts we'll need to wait until after 10/19 to make a fix.

@joschect, can you confirm there aren't dragons here? seems like the fix as simple as adding a null check?

**Comment by JustSlone** [comment]
Bot pinged the wrong person :(
Summoning @joschect to check for Dragons!

> joschect, can you confirm there aren't dragons here? seems like the fix as simple as adding a null check?

**Comment by joschect** [comment]
@JustSlone We can definitely just add null check! I think that's a simple fix that is worthwhile.

**Comment by JustSlone** [comment]
@xuke444 if you are still available to make a fix, looks like we're good to go with this change!

If you want to the fix soon you'll want to make it the v7.0 branch so it goes out as an update to v7, then you can work with us to cherry pick it over to master so it ships in v8 as well. 

Here's some info on working the 7.0 branch. https://github.com/microsoft/fluentui/wiki/Contributing-to-the-7.0-branch

**Comment by hantatsang** [comment]
@JustSlone I inspected the code but cannot see what could have caused this error. There are already falsy checks in `_doesTextStartWith` to deal with `null`. I can add a try-catch in there but I'm not sure if it's worth opening a PR for this?

**Comment by JustSlone** [comment]
So, without having a live repro it's hard to know for sure, but I would say my best guess here is that the current check falsey values is insufficient here. 

https://github.com/microsoft/fluentui/blob/1020e8c78a40a77d10c7f498731cf3f51f7c76b9/packages/react-internal/src/components/Autofill/Autofill.tsx#L353-L358

Tried this out in a codepen and it seems like this theory is plausible. If for whatever reason a non-string item gets passed into `_doesTextStartWith` then we'll see error `TypeError: e.toLocaleLowerCase is not a function`. 
See codepen: https://codepen.io/justslone-the-encoder/pen/PoGgvXx?editors=1011

Now this probably shouldn't happen, and perhaps this is a sign of a bug in the client application. So I'm a little nervous fixing this, but at the same time we do sanitize the input and could fairly easily check to make sure we actually get a string here. 


If others have thoughts, welcome to hear them

**Comment by hantatsang** [comment]
I'd like to have a go at a PR for this, but I'm having trouble setting up `fluentui` on my local machine. Following the contribution guides doesn't work. Will update.

**Comment by JustSlone** [comment]
Ok, talked about this with some folks. 

The use of _doesTextStartWith here is likely on value, inputValue, or suggestedDisplayValue, all of these are typed as strings and should be strings. 

Something that is not null or undefined but also not a string is being passed in here (probably a non-zero number). This is likely an application bug. 

So, rather than adding a check or converting the number to a string which would add runtime cost and probably mask an application bug. We should add a check that throws a more descriptive error message when not running in production mode. 

```typescript
if(process.env.NODE_ENV !== 'production'){
 // check and throw
}
```

Things to consider with the fix:
- Be descriptive in the message to help applications debug the issue.
- See if we can add a test to confirm the behavior
- Ensure the check and throw does not occur in production mode
