### ISSUE TITLE
Narrator is reading the place holder text, when navigated to first option in expanded auto suggestions TagPicker

### ISSUE THREAD

**Issue by shchitg** [microsoft/fluentui#15182]
**Browser Details: ​**
OS: Windows 10 (Version 1909, Build: 18363.778)
Microsoft Edge Dev Version 84.0.502.0 (Official build) dev (64-bit)
Chrome Version 81.0.4044.138 (Official Build) (64-bit)

Issue:
Narrator is reading the place holder text, when navigated to first option in expanded auto suggestions TagPicker

Please find the below code pen link to repro the issue:

https://codepen.io/shchitg/pen/PoNXdVw?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

Note : this issue is observed in Edge +Narrator

Actual Result: ​​
When navigated to first option in expanded auto suggestions dropdown field, screen reader is reading the place holder text.

Expected Result:
Screen reader should read about only the focused first option in expanded auto suggestions dropdown. It should not read about the placeholder text when navigated to options.

**Comment by paulgildea** [comment]
@shchitg Thanks for filing an issue!
