### ISSUE TITLE
Heat map implementation

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#15187]
should include the new chart (Heat Map in the charting library)

figma for design:-https://www.figma.com/file/BJaI0aMC0jXuwsJaGofqM7/Visualizations-(PS-%2B-CFR)?node-id=1%3A2

figma for accessibility:- https://www.figma.com/file/BJaI0aMC0jXuwsJaGofqM7/Visualizations-(PS-%2B-CFR)?node-id=1159%3A737

**Comment by paulgildea** [comment]
@Raghurk FYI
