### ISSUE TITLE
@uifabric-charting | StackedBarChart | onClick action of ChartDataPoint not being called

### ISSUE THREAD

**Issue by xrayburst** [microsoft/fluentui#15183]
### Environment Information

- **Package version(s)**: latest

#### Actual behavior:

Not sure if this is the intended behavior or not.

Currently the ChartDataPoint provides the ability to register a custom callback for onClick, however the actual implementation seems to be overriding this with redirecting to Url.

From StackedBarChart.base.tsx:
onClick={this._redirectToUrl.bind(this, href)}

Am i missing something here ? 
Is this by design ?

### Priorities and help requested:

Are you willing to submit a PR to fix? - Yes.

Requested priority: Blocking

**Comment by paulgildea** [comment]
@xrayburst Thanks for the issue.

@Raghurk FYI

**Comment by vreddi** [comment]
@paulgildea Any updates? `onClick` still seems to be broken for `IChartDataPoint`

**Comment by scharde** [comment]
@xrayburst  If you provide href link, that link will be used for all the bar click events.  But if want to use individual data point onClick event, then don't pass href link, it's an either-or condition. 

![image](https://user-images.githubusercontent.com/29042635/128327813-73aa0078-20f2-4f2c-9e69-ad110640b264.png)


Please find the example in[ link](https://codesandbox.io/s/onclickforchartdatapoint-6cdiy)
Here I have provided both the examples, with href and with data point onClick event.

**Comment by xrayburst** [comment]
@scharde this is because this issue [was fixed](https://github.com/microsoft/fluentui/pull/18369) 2 month ago.
