### ISSUE TITLE
Rich Text support 

### ISSUE THREAD

**Issue by dharnen** [microsoft/fluentui#15198]
#### Describe the feature that you would like added

Support rich text in some compacity. Bold, italic, underline, bullets, colors... Ultimately it would be amazing if a mention type capability could be configured as well. I know there are other packages out there, like "quill" that offer this but it seems weird that it rich text wouldn't be a default part of the built in components.  

#### What component or utility would this be added to

TextField

#### Have you discussed this feature with our team, and if so, who

First time bringing it up.

**Comment by cameronbraid** [comment]
Some pretty nice functionality in the following
https://www.slatejs.org
https://github.com/udecode/slate-plugins

**Comment by paulgildea** [comment]
@dharnen @cameronbraid Thanks for the feature request.

I’ll mark this as a feature request and add it to our backlog, but to set expectations - we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. We'll take this into consideration when we converge the `TextField` component across our two React packages.

@JustSlone FYI

Also this might be a good example of a community led component as I imagine the Rich Text domain can be fairly complex when you start to layer on things like spell checking, dictionary look up, markdown support, etc. 😊  So this might not be something that the core Fluent UI libraries provide.

**Comment by thekeviv** [comment]
@JustSlone @paulgildea If no one is working on this issue, can you assign it to me for me to give it a try. I want to start contributing to FluentUI.

I looked at what Microsoft has in this regard and landed on [RoosterJS](https://github.com/microsoft/roosterjs). [DraftJS](https://draftjs.org/) from Facebook also is quite popular. Do you have a preference for reusing the Microsoft one or I can do some research myself? Is there a process within the FluentUI team in the way you evaluate these tools?

**Comment by JustSlone** [comment]
@thekeviv This is an interesting idea. It will be a large undertaking, but potentially valuable. 

I'll do a little research internally on what might have already been used in various products here, that should give us some pointers on possible future solutions.

**Comment by thekeviv** [comment]
@JustSlone Thank you! Please keep me posted and I would love to work on this!

**Comment by smmatte** [comment]
@thekeviv our team tried implementing roosterjs rich text editor, however we were facing issues to render the content dynamically. We are now implementing rich text editor using alternate package React Draft Wysiwyg, which is based on DraftJS.

**Comment by thekeviv** [comment]
Thanks for letting me know @smmatte. Since there's already some work going on in the area, I think I will start looking into some other issues. Please let me know if you have any in mind where I can help.

**Comment by JustSlone** [comment]
I did some research here, and there is actually a set of react components built on roosterJS using @fluentui/react@v7. https://github.com/microsoft/roosterjs-react 

This might be interesting for folks looking for a solution here.

@thekeviv if you are looking to help out, check out issues labeled with ["Good First Issue"](https://github.com/microsoft/fluentui/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue+%F0%9F%8F%86%22) or ["Help Wanted"](https://github.com/microsoft/fluentui/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted+%E2%9C%A8%22). Those are good places to start, and thank you for looking to help!

**Comment by thekeviv** [comment]
Will do, thanks @JustSlone

**Comment by JustSlone** [comment]
Closing given the existence of roosterJS

**Comment by dps88** [comment]
@JustSlone and any internet historians [roosterjs-react isn't being actively maintained](https://github.com/microsoft/roosterjs-react/issues/108#issuecomment-821549401), so if you want updated Fluent controls you may be out of luck. 

We have built a wrapper using [roosterjs ](https://github.com/microsoft/roosterjs) as suggested, but that's a bit of a pain.  In the future, there may still be some value in an official Fluent UI solution given how often this request pops up.
