### ISSUE TITLE
[HorizontalBarChart] Customize the format of chart data in the upper right

### ISSUE THREAD

**Issue by luckyrass** [microsoft/fluentui#15191]
#### Describe the feature that you would like added
Customize the format of chart data in HorizontalBarChart

#### What component or utility would this be added to
HorizontalBarChart
Customize the format of the number in the upper right. It should be counted in K, G, T units.
![image](https://user-images.githubusercontent.com/12230173/94038459-0ae9cd00-fdf9-11ea-875f-789f0dcc7e81.png)

#### Have you discussed this feature with our team, and if so, who
Not yet. But we have this feature in the figma design.

**Comment by paulgildea** [comment]
@luckyrass Thanks for the feedback!

**Comment by Raghurk** [comment]
I will follow up on this

**Comment by jameelakowsar** [comment]
This issue fixed and released version @uifabric/charting@v4.14.0
