### ISSUE TITLE
Narrator does not announce descriptively when focus is on breadcrumb

### ISSUE THREAD

**Issue by yueou1995** [microsoft/fluentui#15195]
### Environment Information

- Windows Version - Win10
- Chromium Edge - Version 85.0.564.51 (Official build) (64-bit)

### Describe the issue:

Narrator does not announce descriptively when focus is on breadcrumb. 

#### Actual behavior:

Narrator is not announcing descriptively when focus is on breadcrumb

#### Expected behavior:

Narrator should announce descriptively when focus is on breadcrumb

### Documentation describing expected behavior

https://www.w3.org/TR/wai-aria-practices-1.1/examples/breadcrumb/index.html

**Comment by paulgildea** [comment]
@yueou1995 Thanks for the feedback.

Could you send a pointer to a codepen or let us know the version number of the Fluent UI React library because that will help us understand if a regression was introduced.
