### ISSUE TITLE
When zoomed to 200%, 'show more' button is not completely visible in expanded auto suggestions dropdown.

### ISSUE THREAD

**Issue by shchitg** [microsoft/fluentui#15208]
Browser Details: ​
OS: Windows 10 (Version 1909, Build: 18363.778)
Microsoft Edge Dev Version 84.0.502.0 (Official build) dev (64-bit)

Issue:
When zoomed to 200%, 'show more' button is not completely visible in expanded auto suggestions dropdown.

Please find the below code pen link to repro the issue:

https://codepen.io/sagsah/pen/RwWxxpw?editors=1010

Actual:
When zoomed to 200%, 'show more' button is not completely visible in expanded auto suggestions dropdown.

Expected:
When zoomed to 200%, all the controls should be clearly visible and accessible. 'Show more' button should be visible completely when navigated to it using keyboard. arrow buttons.

**Comment by paulgildea** [comment]
@shchitg Thanks for the issue.
