### ISSUE TITLE
Make charting resizable

### ISSUE THREAD

**Issue by NewFuture** [microsoft/fluentui#15202]
#### Describe the feature that you would like added

Set the `viewBox` of the SVG instead of the `width` and `height` to Make the chartting image resizable/scalable.

#### What component or utility would this be added to

charting

#### Additional context/screenshots

current svg
```svg
<svg focusable="false" style="display: block;"  width="800" height="500">
...
</svg>
```
to be
```svg
<svg focusable="false" style="display: block;"  viewBox="0 0 800 500">
...
</svg>
```

In this way, this svg can auto resize based on the height/width of parent div or using percent/rem as length.

**Comment by paulgildea** [comment]
@NewFuture Thanks for the feature request.

@Raghurk FYI
