### ISSUE TITLE
A11y_With Narrator ON, focus order is not proper while toggling checkboxes in multi-select combo box.

### ISSUE THREAD

**Issue by AdilMah** [microsoft/fluentui#15204]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Edge and Windows Devices, with Narrator ON. Similar issue on iPad with VoiceOver.

### Describe the issue:
This issue is with multiselect Combo Box. When narrator is ON, for the first time when only two options are checked, and one of them is unchecked, the focus jumps to the only option which is checked. This behavior is unexpected.

Steps:
1. Head over to the multiselect combo box.
2. Turn on narrator and check any two checkboxes by swiping and toggling on.
3. Sometimes, when you toggle off one of the checkbox, the focus jumps to the other checkbox checked.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/AdilMah/pen/LYNqxay?editors=1010

#### Actual behavior:

On toggling off a checkbox, the focus should remain on the current checkbox.

#### Expected behavior:

On toggling off a checkbox, the focus jumps to the only checkbox currently checked.

**Comment by paulgildea** [comment]
@AdilMah Thanks for the codepen it's really appreciated!
