### ISSUE TITLE
React-Theme-Provider Storybook broken

### ISSUE THREAD

**Issue by tylergibson** [microsoft/fluentui#15212]
### Environment Information

- **Package version(s)**: 0.14.0
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

git clone https://github.com/microsoft/fluentui.git
cd fluentui/packages/react-theme-provider
yarn
yarn run start

#### Actual behavior:

![image](https://user-images.githubusercontent.com/1085397/94171366-0992c180-fe46-11ea-9794-ea2e51d6b48b.png)

#### Expected behavior:

To not have property undefined errors on Storybook run

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@tylergibson Thanks for the feedback!

**Comment by ecraig12345** [comment]
@xugao FYI (also @khmakoto but it looks like this was broken before the examples move)

**Comment by xugao** [comment]
I will take a look!
