### ISSUE TITLE
Selectable Tree ( diff from multi-selectable tree ) 

### ISSUE THREAD

**Issue by assuncaocharles** [microsoft/fluentui#15233]
#### Describe the feature that you would like added

Following the design spec we need to add `single select` state for the `Tree`, we currently have the tree not selectable and "multi-selectable". The design spec also describe a single selected `Tree` where only 1 item should be selected and it's shown by the background as select and not with a checkbox in the item.

#### What component or utility would this be added to

`Tree`

#### Have you discussed this feature with our team, and if so, who

Yes, discussed with the entire V0 team 

#### Additional context/screenshots

<img width="548" alt="Screen Shot 2020-09-25 at 07 21 18" src="https://user-images.githubusercontent.com/8545105/94229416-be3ce980-feff-11ea-879f-1a7380089ff5.png">

**Comment by paulgildea** [comment]
@assuncaocharles Thanks for the issue.

@jurokapsiar Since it sounds like this was discussed with the team, should I assign this to @assuncaocharles to start working on the fix?
