### ISSUE TITLE
Expandable indicator ( chevron ) should be present by default

### ISSUE THREAD

**Issue by assuncaocharles** [microsoft/fluentui#15232]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.51.1
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a CodeSandbox:

https://codesandbox.io/s/9xglr?module=/example.js

#### Actual behavior:

We need to use `renderItemTitle` to have the chevron icon and control it from outside the `Tree`

#### Expected behavior:

Based on the design spec the expandable indicator ( chevron )  should always be rendered by default if item is expandable. 

My proposal is to have `expandableIndicator` and `expandedIndicator` slot in the `TreeItem` component and having `<TriangleEndIcon />` and `<TriangleDownIcon />` as respectively default icons 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

**Comment by paulgildea** [comment]
@assuncaocharles Thanks for the issue. Once @miroslavstastny comes back with a recommendation on a potential fix - we would love for you to submit a PR. Thanks!
