### ISSUE TITLE
Selected ChoiceGroup button  does not appear clearly  in high contrast on mouse hover.

### ISSUE THREAD

**Issue by v-ajrai** [microsoft/fluentui#15237]
Selected ChoiceGroup buttons  does not appear clearly  in high contrast on mouse hover.

### Environment Information

OS: Win 10
Browser: Edge

### Describe the issue:
Selected ChoiceGroup button  does not appear clearly  in high contrast on mouse hover.

###  Reproduction of the issue:
https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup.
![external_choice_group](https://user-images.githubusercontent.com/62233982/94238459-0d017800-ff2e-11ea-85f1-30f609037ce1.png)

#### Actual behavior:

Selected ChoiceGroup button  does not appear clearly  in high contrast on mouse hover.

#### Expected behavior:

Selected ChoiceGroup button  should appear clearly  in high contrast on mouse hover.

**Comment by paulgildea** [comment]
@v-ajrai Thanks for the issue.

@xugao FYI
