### ISSUE TITLE
Selectable Indicator should be Icon passed as prop to avoid style override

### ISSUE THREAD

**Issue by assuncaocharles** [microsoft/fluentui#15234]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.51.1
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a CodeSandbox:

https://codesandbox.io/s/i4trp?module=/example.js&file=/example.js

#### Actual behavior:

The current implementation is using styles by default to change the selection indicator state ( checked or not ), we already had several issues with this approach and this also overcomplicates for user having to use children api for set the selection indicator as in the  following snippet:

```javascript
          {
            id: '4',
            title: 'Cersei',
            selectionIndicator: {
              children: (Component, { selected, onClick, ...props }) => {
                return (
                  <Component {...props}>
                    <input
                      data-is-focusable={false}
                      type="checkbox"
                      checked={selected}
                      onClick={onClick}
                      onChange={() => {}}
                    />
                  </Component>
                )
              },
            },
          },
```

#### Expected behavior:

We should implement `selectIndicator` and `selectedIndicator` slot for `TreeItem` and have icons as default values to allow usage like this:

```javascript
          {
            id: '4',
            title: 'Cersei',
            selectIndicator: < NotCheckedIcon />,
            selectedIndicator: < CheckedIcon />
          },
```

This will also prevent styles conflicts that we already faced with the current approach 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by paulgildea** [comment]
@assuncaocharles Thanks for the issue.

**Comment by YuanboXue-Amber** [comment]
Adding to this point:
When I was making PR #16158, I realize it's difficult to write UT for selectable tree, because the selection state is reflected by style :( It would be so much easier if it were icons
