### ISSUE TITLE
Toggle styling doesn't address the `On` state background color

### ISSUE THREAD

**Issue by DavidIsrawi** [microsoft/fluentui#15256]
**Issue**

I am trying to change the color of the On state of the Toggle control but the stylings doesn't seem to differentiate between the On and Off states' background color.

![bluetoggle](https://user-images.githubusercontent.com/13784628/94324939-059f9600-ff51-11ea-8c7e-e7d0a65aa1e3.PNG)

I tried to add the following style to the control

```
const toggleStyle = {
    pill: {
      background: 'blue'
    }
};
```

But this style changes the background color or both the Off and On states

**Actual**

![uglytoggle](https://user-images.githubusercontent.com/13784628/94325117-b9088a80-ff51-11ea-9b3e-2939f1856ae9.PNG)

**Expected**

![expectedtoggle](https://user-images.githubusercontent.com/13784628/94325150-e48b7500-ff51-11ea-902e-7339cce321de.PNG)

**Environment Information**

- Package version: "office-ui-fabric-react": "^7.68.0"
- Browser: Edge v87

**Priorities and help requested:**

Are you willing to submit a PR to fix? No (unless needed)
Requested priority: Normal
Products/sites affected: Excel

**Comment by JustSlone** [comment]
@DavidIsrawi , you should be able to use a customizer and the semanticColors bodyBackground and inputBackgroundChecked to control the colors here. [For more info on sematic colors see this page](https://developer.microsoft.com/en-us/fluentui#/controls/web/references/isemanticcolors)

Here's the lines that control the colors here. 
https://github.com/microsoft/fluentui/blob/a05ade31605674221b203425570078b2227973b8/packages/office-ui-fabric-react/src/components/Toggle/Toggle.styles.ts#L17-L19

Let us know if this works for you or if you hit other issues.

**Comment by DavidIsrawi** [comment]
That worked @JustSlone - thank you!

**Comment by DavidIsrawi** [comment]
@JustSlone seems like inputBackgroundCheckedHovered is missing on the implementation of the Toggle style.

Should I open a different issue or could we discuss that in this one?

**Comment by JustSlone** [comment]
@DavidIsrawi If it's not too much trouble a fresh issue would be best, thanks!

**Comment by DavidIsrawi** [comment]
There seems to be a TODO item in the file you shared regarding this. Is there an issue to keep track of it? My team's feature needs access to both **pillCheckedBackground** and **pillCheckedHoveredBackground**
