### ISSUE TITLE
@uifabric/foundation removal plan

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#15252]
Since we decided to go with a different approach for component creation and composition, we should probably delete the `@uifabric/foundation` code from `master` after `7.0` forks. But that means we have to figure out what to do about the components still using it.

|Component|Plan|
|-|-|
|Stack|?|
|Text|?|
|Accordion (experiments)|?|
|Button (experiments)|Delete?|
|CollapsibleSection (experiments)|?|
|MicroFeedback (experiments)|?|
|Persona components (experiments)|?|
|Toggle (experiments)|Delete?|
|`factoryComponents` (experiments)|?|

For Stack and Text, we should consider whether it's possible to quickly convert them to another pattern (either plain components or using new compose).

Experimental Button and Toggle have been replaced by new implementations, so we may just want to delete them from `master`.

For the other experimental components, one possibility is to have these components in `master` depend on `@uifabric/foundation@7` from npm (published out of the `7.0` branch). It will make fixes awkward, but it's been pretty uncommon for fixes to be needed in that package.

**Comment by xugao** [comment]
One idea would be renaming to `@fluentui/foundation-deprecated` or something alone that line

**Comment by khmakoto** [comment]
We have Esteban's work on `Flex` and Shift's work on `Text` so I think it should be possible to quickly convert them.

**Comment by xugao** [comment]
for now, we renamed `@uifabric/foundation` to `@fluentui/foundation-legacy` starting from `@fluentui/react` version 8 release
