### ISSUE TITLE
Node_Modules missing

### ISSUE THREAD

**Issue by Faisal-developer** [microsoft/fluentui#15263]
I have updated "@fluentui/react": "7.133.1" in package.json but after executing npm install.
Following folders are missing in node_modules
node_modules@fluentui\react\lib\utilities
PS: There are no folder on the following path "node_modules@fluentui\react\lib"

Please let me know if you need  more details.

**Comment by paulgildea** [comment]
@Faisal-developer Thanks for the issue.

@khmakoto FYI since you've been working on packaging

**Comment by khmakoto** [comment]
Hi @Faisal-developer, thanks for filing this issue! Do you have a repo I could clone to test this? I haven't been able to replicate it in my local workspace.
