### ISSUE TITLE
A11y_ With narrator ON, Swiping takes one extra swipe at each list item present in multi-select combo box

### ISSUE THREAD

**Issue by rishabhsharma0** [microsoft/fluentui#15275]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Microsoft Edge 85.0.564.63 (Official build) dev (64-bit), similar issue on dynamics 365 app

### Describe the issue:

The issue is coming in multiselect ComboBox. When narrator is ON, on swiping, taking one extra swipe at each list item present in multi-select ComboBox.

Steps:
1.Turn on narrator 
2. Head over to the multiselect combo box and Double tap to expand the combo box
3.Swipe and verify narrator is taking one extra swipe at each list item present in multi-select combo box in Edge Browser  and Dynamics 365 app.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/rishabhsharma0/pen/yLOrXpq

#### Actual behavior:

When narrator is ON, on swiping, taking one extra swipe at each list item present in multi-select combo box​
![image](https://user-images.githubusercontent.com/71834383/94427422-ab9b0c80-01ac-11eb-9dbf-a435c0bba545.png)
{extra swipe}
=>![image](https://user-images.githubusercontent.com/71834383/94427652-10566700-01ad-11eb-8cfe-bb53d062672c.png)
![image](https://user-images.githubusercontent.com/71834383/94427566-ec932100-01ac-11eb-924c-8af7124e5c80.png)

taking 3 swipes to go from 1 list items to another while swiping, should take 2

#### Expected behavior:

When narrator is ON, on swiping, it should not take any extra swipes at each list item present in multi-select combo box​

**Comment by paulgildea** [comment]
@rishabhsharma0 Thanks for the issue.

@smhigley FYI on the pattern.

@betrue-final-final - Also on the desired behavior.
