### ISSUE TITLE
The input value cannot be saved  in the Controlled ComboBox

### ISSUE THREAD

**Issue by lizimeow** [microsoft/fluentui#15273]
### Environment Information

- **Package version(s)**: 7.141.0

### This is your official demo in a codepen:
https://codepen.io/pen/?&editable=true=https%3A%2F%2Fdeveloper.microsoft.com%2F

#### Actual behavior:

The input value cannot be saved.

#### Expected behavior:

The input value can be saved.

**Comment by paulgildea** [comment]
@lizimeow Thanks for the issue.

Unfortunately the codepen is empty. Could you provide a functional codepen of the issue you are seeing?
