### ISSUE TITLE
inputBackgroundCheckedHovered is not implemented for Toggle style

### ISSUE THREAD

**Issue by DavidIsrawi** [microsoft/fluentui#15286]
**Issue**

I am trying to change the color of the On state of the Toggle control when hovered

I tried to add the following semantic color to my theme

```
  const toggleTheme: ITheme = createTheme({
    semanticColors: {
      inputBackgroundChecked: '#217346',
      inputBackgroundCheckedHovered: '#0e5c2f'
    }
  });
```

But inputBackgroundCheckedHovered is not being recognized by Toggle.styles.ts

**Actual when applying the theme above**

![togglehoverwrong](https://user-images.githubusercontent.com/13784628/94489866-21e24380-019a-11eb-8d16-630239418c03.PNG)

**Expected when applying the theme above**

![togglehoverright](https://user-images.githubusercontent.com/13784628/94489869-2575ca80-019a-11eb-9861-cce3460abd20.PNG)

**Environment Information**

- Package version: "office-ui-fabric-react": "^7.68.0"
- Browser: Edge v87

**Priorities and help requested:**

Are you willing to submit a PR to fix? No (unless needed)
Requested priority: Normal
Products/sites affected: Excel

There seems to be a TODO item in the file you shared regarding this in Toggle.styles.ts. 
https://github.com/microsoft/fluentui/blob/a05ade31605674221b203425570078b2227973b8/packages/office-ui-fabric-react/src/components/Toggle/Toggle.styles.ts#L20-L21

**Comment by DavidIsrawi** [comment]
@JustSlone FYI

**Comment by JustSlone** [comment]
Thanks @DavidIsrawi! @miroslavstastny is going to take point on following up regarding the work on mapping inputBackgrounedCheckedHovered, it's actually mentioned in several places so we'll probably fix them all in one go.

**Comment by DavidIsrawi** [comment]
Hi @JustSlone @miroslavstastny, has this issue been fixed by the issue mentioned above? I looked at the PR and the answer wasn't trivial, but I believe it wasn't addressed in it.

**Comment by DavidIsrawi** [comment]
Hi @JustSlone @miroslavstastny - checking in to see if there're any updates with this bug.

**Comment by JustSlone** [comment]
@xugao, did https://github.com/microsoft/fluentui/pull/15452 fix the issue with toggle mentioned here?

**Comment by DavidIsrawi** [comment]
I downloaded the latest version and still continued to repro the bug. @xugao could you confirm if the fix above addresses this bug?

**Comment by DavidIsrawi** [comment]
Is there any available update with this bug? We are releasing to prod at the end of this month and would love to have this hopefully fixed by release @JustSlone @xugao

**Comment by xugao** [comment]
@DavidIsrawi - your issue is actually unrelated to #15280. Apologize I missed yours.

The root cause for what you saw is `inputBackgroundCheckedHovered` actually does not control the background color on hover. Instead it's currently controlled by `palette.themeDark` (see code here: https://github.com/microsoft/fluentui/blob/master/packages/react-toggle/src/components/Toggle/Toggle.styles.ts#L21)

I will make a PR to fix this and have toggle to use `inputBackgroundCheckedHovered` instead of `themeDark`

**Comment by DavidIsrawi** [comment]
Thank you! @xugao

**Comment by xugao** [comment]
@DavidIsrawi - NP! The fix is merged. package with the fix should be published tonight
