### ISSUE TITLE
react-theme-provider does not style Fluent UI components correctly with imported theme

### ISSUE THREAD

**Issue by wsfuller** [microsoft/fluentui#15280]
### Environment Information

- **Package version(s)**: 
```
  "@fluentui/react": "^7.142.0",
  "@fluentui/react-theme-provider": "^0.14.2",
  "@uifabric/fluent-theme": "^7.1.91",
  "@uifabric/icons": "^7.3.48",
  "@uifabric/react-hooks": "^7.13.5",
```
- **Browser and OS versions**: n/a

### Please provide a reproduction of the bug in a codepen:

**codepen example below wasn't loading**

#### Creating a theme using the [Fluent UI Theme Designer](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/index.html)

```
/src/themes.js

export const lightTheme = {
  palette: {
    themePrimary: '#148214',
    themeLighterAlt: '#f2faf2',
    themeLighter: '#cbebcb',
    themeLight: '#a2daa2',
    themeTertiary: '#58b458',
    themeSecondary: '#259125',
    themeDarkAlt: '#127512',
    themeDark: '#0f630f',
    themeDarker: '#0b490b',
    neutralLighterAlt: '#faf9f8',
    neutralLighter: '#f3f2f1',
    neutralLight: '#edebe9',
    neutralQuaternaryAlt: '#e1dfdd',
    neutralQuaternary: '#d0d0d0',
    neutralTertiaryAlt: '#c8c6c4',
    neutralTertiary: '#a19f9d',
    neutralSecondary: '#605e5c',
    neutralPrimaryAlt: '#3b3a39',
    neutralPrimary: '#323130',
    neutralDark: '#201f1e',
    black: '#000000',
    white: '#ffffff',
  }
}
```
#### Using [@fluentui/react-theme-provider](https://www.npmjs.com/package/@fluentui/react-theme-provider)

```
/src/index.jsx

...import statements...

import { ThemeProvider } from '@fluentui/react-theme-provider'; 

import { lightTheme } from './themes';

ReactDOM.render(
    <ThemeProvider theme={lightTheme}>
        <App />
    </ThemeProvider>,
  document.getElementById('root')
```

#### Import Fluent Component

```
/src/components/App.jsx

import { PrimaryButton } from '@fluentui/react';

function App() {
  return <PrimaryButton text="Standard" />;
}
```

#### Actual behavior:

Using Fluent UI components do not get styled correctly according the theme palette object provided. When using `Fabric` and `loadTheme` all components were adhering to the provided custom theme. 

<img width="596" alt="Screen Shot 2020-09-28 at 10 07 27 AM" src="https://user-images.githubusercontent.com/3144419/94464062-c81a5300-0172-11eb-8ffa-654116708845.png">

#### Expected behavior:

Fluent UI components should be styled according to exported palette object from the Fluent UI Theme Designer. I have noticed that some elements are using the theme provided but not in a complete "across the board" manner as shown in the Toggle gif below.

<img width="639" alt="Screen Shot 2020-09-28 at 10 09 02 AM" src="https://user-images.githubusercontent.com/3144419/94464268-1b8ca100-0173-11eb-8f22-696d69c33630.png">

In this example the [Fluent UI Toggle](https://developer.microsoft.com/en-us/fluentui#/controls/web/toggle) is filled with blue when activated. However on hover instead of going to a darker blue hue it turns green with is indicative of the theme being loaded in. The fill for this toggle when activated should be green, and when hovered a darker green should render. Note the icon should also be green and not blue

![fluent-theme-toggle](https://user-images.githubusercontent.com/3144419/94465304-8be7f200-0174-11eb-97f6-fee3783f45f0.gif)

### Priorities and help requested:

Are you willing to submit a PR to fix? I'm willing to help work on documentation. imo the documentation is difficult to follow and the examples are lacking completeness. 

Requested priority: High

Products/sites affected: (if applicable)

------

_Also reading the documentation, `createTheme` is imported but never used in the example of applying component-level styles._

<img width="799" alt="Screen Shot 2020-09-28 at 10 00 42 AM" src="https://user-images.githubusercontent.com/3144419/94463648-1b3fd600-0172-11eb-8cf8-ed017b3d8f86.png">

**Comment by miroslavstastny** [comment]
The `lightTheme` created by Theme Designer is only a partial theme. In order to create a fully defined theme, you call `createTheme` on the partial theme. You can pass the result to `ThemeProvider`:

```jsx
import { ThemeProvider, createTheme } from '@fluentui/react-theme-provider'; 

import { lightTheme } from './themes';

const fullLightTheme = createTheme(lightTheme);

ReactDOM.render(
    <ThemeProvider theme={fullLightTheme}>
        <App />
    </ThemeProvider>,
  document.getElementById('root')
);
```

Please check this [working code example](https://codesandbox.io/s/themeprovider-0tt3d?file=/src/App.tsx).

@dzearing - `ThemeProvider` accepts both `PartialTheme` and `Theme`. Could you please help me clarify what are the valid usecases for passing in the `PartialTheme`?

For the issue with `Toggle`, this is caused by some theme variables not correctly used in Toggle styles, see related bug #15286.

**Comment by dzearing** [comment]
@xugao as well.

That's a great point; it really should only accept `Theme` unless it internally is expanding it. What do you think @xugao ?

**Comment by xugao** [comment]
@dzearing - We do support passing `PartialTheme`. Here is what's happening:
in `createTheme`, we do this:
```
  const newSemanticColors = {
    ...makeSemanticColors(newPalette, newEffects, theme.semanticColors, !!theme.isInverted, depComments),
    ...theme.semanticColors,
  };
```
in `ThemeProvider`, we simply all `mergeThemes` without re-mapping `palette` to `semanticColors` every time theme changes. 

The fix here is we should call `makeSemanticColors` in `ThemeProvider` when we merge the parent theme with user theme.
I will fix
