### ISSUE TITLE
DetailsList: Uncaught TypeError: Cannot add property calculatedWidth, object is not extensible

### ISSUE THREAD

**Issue by vincenzocaruso** [microsoft/fluentui#15291]
### Environment Information

- **Package version(s)**: 7.123.9
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

Shimmered list with minWidth and maxWidth set per columns and the layoutMode={​​​​​​​​DetailsListLayoutMode.justified}​​​​​​​​
Trying to resize a column dragging the | with the cursor

#### Actual behavior:
Console error : DetailsList.base.js:578 Uncaught TypeError: Cannot add property calculatedWidth, object is not extensible

![image](https://user-images.githubusercontent.com/7630308/94501618-1b15f980-01b7-11eb-9934-b52583644aac.png)

#### Expected behavior:
No console error

### Priorities and help requested:
Requested priority: High

Products/sites affected: Azure IoT Central

**Comment by miroslavstastny** [comment]
Unfortunately I was not able to reproduce the issue. Could you please provide us with a codepen reproducing the issue?
