### ISSUE TITLE
grouped datalist example from docs giving error

### ISSUE THREAD

**Issue by bsdis** [microsoft/fluentui#15310]
Hi, I copied this example here: https://developer.microsoft.com/de-de/fluentui#/controls/web/detailslist/grouped  to my local machine (this code) https://dpaste.org/rJ8k  and I am getting errors in L. 150 and 154 even though i did not change anything. 
The errors are:
```
Type '(props: IDetailsHeaderProps, _defaultRender?: IRenderFunction<IDetailsHeaderProps> | undefined) => Element' is not assignable to type 'IRenderFunction<IDetailsHeaderProps>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'IDetailsHeaderProps | undefined' is not assignable to type 'IDetailsHeaderProps'.
      Type 'undefined' is not assignable to type 'IDetailsHeaderProps'
The expected type comes from property 'onRenderDetailsHeader' which is declared here on type 'IntrinsicAttributes & IDetailsListProps & { children?: ReactNode; }'
```

and 

```
Type '(item: IDetailsListGroupedExampleItem, index: number, column: IColumn) => Element' is not assignable to type '(item?: any, index?: number | undefined, column?: IColumn | undefined) => ReactNode'.
  Types of parameters 'index' and 'index' are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'
The expected type comes from property 'onRenderItemColumn' which is declared here on type 'IntrinsicAttributes & IDetailsListProps & { children?: ReactNode; }'
```

I am using TS version 3.7.5 and react 16.13.1 - created using CRA. 
Is it possibly because of strict null types in application while fluentUI was not built with strict null types?

**Comment by paulgildea** [comment]
@bsdis Thanks for the feedback.

I'm not too familiar with dpaste.org, are you seeing this issue just within that web app?

@JustSlone Any thoughts here if this is an issue with the library or just interaction with the web app?

**Comment by phoenixGeek** [comment]
I converted class component which was described in here:  https://developer.microsoft.com/de-de/fluentui#/controls/web/detailslist/grouped  into functional component
But when render DetailsList the following issue was appeared and need help
Type '(props: IDetailsHeaderProps, _defaultRender?: IRenderFunction<IDetailsHeaderProps> | undefined) => JSX.Element' is not assignable to type 'IRenderFunction<IDetailsHeaderProps>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'IDetailsHeaderProps | undefined' is not assignable to type 'IDetailsHeaderProps'.
      Type 'undefined' is not assignable to type 'IDetailsHeaderProps'.  TS2322

**Comment by bsdis** [comment]
@paulgildea dpaste is just a pasting service.....not running any code.
The problem appeared when running the demo locally using create-react-app. 
Further comments from @phoenixGeek also indicates that there are issues with this example.

Any chance the devs of fluentUI could try to run this example locally using create-react-app and verify that it still works?
