### ISSUE TITLE
For the DetailsList, the luminosity ratio for the delimiter between rows is less than 3:1

### ISSUE THREAD

**Issue by cnamal-msft** [microsoft/fluentui#15314]
### Environment Information

- **Package version(s)**: 7.143.0
- **Browser and OS versions**: All

### Describe the issue:

For the DetailsList, the luminosity ratio for the delimiter between rows is less than 3:1

### Please provide a reproduction of the issue in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/7.143.0/#/examples/detailslist

#### Actual behavior:

![image](https://user-images.githubusercontent.com/53378748/94666168-66422080-030d-11eb-9ef8-efdc4d2797ad.png)

#### Expected behavior:

Luminosity ratio for the delimiter between rows must be greater than 3:1

### Documentation describing expected behavior

MAS 1.4.11 – Non-text Contrast
WCAG 1.4.11: https://w3c.github.io/wcag21/understanding/non-text-contrast.html

**Comment by paulgildea** [comment]
@cnamal-msft Thanks for the issue.

@miroslavstastny I'll follow up for the right design contact to help define the color value.
