### ISSUE TITLE
Dialog close animation breaks when container makes continuous use of setState

### ISSUE THREAD

**Issue by Jamie0** [microsoft/fluentui#15318]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@7.144.0
- **Browser and OS versions**: Tested on macOS Firefox and Chrome

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/Jamie0/pen/gOrJQVg

#### Actual behavior:

The dialog does not close, as setState is called multiple times, with an interval period shorter than the overall animation length. If a long running action is taking place in a component (for example, a file download), which is making use of setState to show some relevant data, this can block the application entirely as there is no other way to dismiss the dialog until that action finishes. 

#### Expected behavior:

The dialog should just close, instead of resetting the close animation. 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes (when, however, is time dependant!) 

Requested priority: Blocking

Products/sites affected: Fluent UI React Components

**Comment by paulgildea** [comment]
@Jamie0 Thanks for the issue.

We'll take a look at this issue - it seems a little complex so we won't have something right away. 

In the meantime, have you tried any workarounds? For example if your long running task interval is more than the animation timing does unblock you in the meantime?

@joschect FYI

**Comment by Jamie0** [comment]
By far the easiest workaround is simply removing the Dialog instead of setting its visibility prop. Of course, then you lose the animations. 

I've applied a very temporary fix, which stops dialogs/modals from blocking the rest of the app in this case. The animation doesn't complete, but the dialog does close.

**Comment by mbest** [comment]
I think the problem is this code, which doesn't check if `isOpen` is still false in the new props:

https://github.com/microsoft/fluentui/blob/0094b6560331f0ec957948cb44c453eb03c56c79/packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx#L149-L154
