### ISSUE TITLE
CompoundButton loses child control alignments when clicked.

### ISSUE THREAD

**Issue by davvit** [microsoft/fluentui#15329]
![ZV60qK90MZ](https://user-images.githubusercontent.com/4433698/94760240-90283100-0367-11eb-91c8-38cfa023ffa2.gif)
### Environment Information
Electron, TS

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/davvit/pen/dyMBovJ

#### Actual behavior:

the      ` textAlign: '-webkit-center', ` in the button styling seems to be reset after clicking the button

#### Expected behavior:

Alignment should not change

Requested priority: (Blocking, High, Normal, Low)
Normal

**Comment by paulgildea** [comment]
@davvit Thanks for the issue and the repo!
