### ISSUE TITLE
Non-text contrast ratio of the chevron down icon in the DetailsList column header is less than the minimum requirement of 3:1

### ISSUE THREAD

**Issue by hpanwar35** [microsoft/fluentui#15324]
### Environment Information

- **Package version(s)**: 7.137.0
- **Browser and OS versions**: Edge(chromium) 85.0.564.63, Windows 10 Enterprise 10.0.19042 Build 19042

### Describe the issue:

Non-text contrast ratio of the 'Expand' chevron icons beside each column header is less than the minimum requirement of 3:1.(2:1)

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/hpanwar35/pen/VwaJZjy

#### Actual behavior:
![image](https://user-images.githubusercontent.com/2060775/94740981-51bf5180-0328-11eb-9669-cddb8ecc1b6e.png)

Visually impaired or color blind users who rely on color contrast will not be able to view the chevron icons beside column headers which indicate their expandable property and hence might miss out on the expand functionality of the header buttons.

![image](https://user-images.githubusercontent.com/2060775/94740910-38b6a080-0328-11eb-8a33-7181aed3faf5.png)

#### Expected behavior:

Non-text contrast ratio of the 'Expand' chevron icons beside each column header should not be less than the minimum requirement of 3:1.

### Documentation describing expected behavior
MAS Link: [MAS 1.4.11 - Non-text Contrast](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7b6CA3BF14-2635-434A-832C-28DD9A18B9FC%7d&file=MAS%201.4.11%20%E2%80%93%20Non-text%20Contrast.docx&action=default&mobileredirect=true)

**Comment by paulgildea** [comment]
@hpanwar35 Thanks for the issue.

@miroslavstastny We'll need to follow up with Design on the correct value.
