### ISSUE TITLE
Add Reveal Password button to TextField

### ISSUE THREAD

**Issue by hutchcodes** [microsoft/fluentui#15333]
#### Describe the feature that you would like added

Add a button to reveal the password similar to the one that exists in Edge/Chromium Edge and IE.

#### What component or utility would this be added to

Office-UI-Fabric-React TextField

#### Have you discussed this feature with our team, and if so, who

David Zearing

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/4989220/94826929-d6b47480-03d5-11eb-9e02-dcf6a0700020.png)

**Comment by paulgildea** [comment]
@hutchcodes Thanks for the contribution!

@dzearing / @JustSlone FYI
