### ISSUE TITLE
Docs: README.md duplicated link to /packages/react

### ISSUE THREAD

**Issue by sharechiwai** [microsoft/fluentui#15357]
On README.md there are duplicated link to /packages/react
![image](https://user-images.githubusercontent.com/843624/95016630-bfe87900-0686-11eb-8d11-dd185f2712e0.png)

**Comment by sharechiwai** [comment]
I have added the following commit, when I tried to create pull request, it recommend me to wait until 12 Oct.
https://github.com/sharechiwai/fluentui/commit/4df1a55a72f7a732005a72eb42ee84a6f6112b12

**Comment by paulgildea** [comment]
@sharechiwai Thanks for the issue and the PR. Yes we are snapping for a new release (see #15222) so contributions are going to be a little slow for the next couple of weeks.

Thanks!

**Comment by layershifter** [comment]
@sharechiwai would you like to create a PR that targets `master` branch with your change? 😺
