### ISSUE TITLE
Roadmap for new components addition 

### ISSUE THREAD

**Issue by singharpit94** [microsoft/fluentui#15360]
Hi Team,

We have been evaluating  fluent-ui react package to be used as base library for our web platform and have been really impressed with the design language and current set of controls/components and styles provided by fluent-ui. Though our requirements are more than what is currently available.

Can you please share some info regarding the future plan or roadmap of fluent-ui? As of now there are some components which are required for our use case but currently they are not present in the package. So having some idea regarding the future plans will help us in taking a decision here.

Thanks

**Comment by paulgildea** [comment]
@singharpit94 Thanks for filing this issue.

We're definitely working on putting together a clearer roadmap that helps consumers and contributors better understand how we're converging the `react` and `northstar` packages and the components within them. I don't have any timelines to share at this time, but we will let folks know once we have something to share.

Thanks!

**Comment by rdweaver** [comment]
Do you have any updates on converging the `react` and `northstar` packages and components? Do you have any timelines? Where should I go to get the latest information regarding the future plans?

**Comment by JustSlone** [comment]
Hey all, we just posted our 2021 roadmap here: https://github.com/microsoft/fluentui/wiki/Fluent-UI-React-Roadmap

It's basic for now, we'll continue to add more detail over time. check it out
