### ISSUE TITLE
Screen reader announces "Selected" for unselected menu items when using Button as drop down menu

### ISSUE THREAD

**Issue by jon-msft** [microsoft/fluentui#15363]
### Environment Information

- Repros on the Fluent v7 lib consumed by the codepen example below
- Edge 85.0.564.63 Windows 10 19041.508

### Describe the issue:

I am using an IconButton with menu items with logic to use it as a drop down selection:
![image](https://user-images.githubusercontent.com/63806783/95107821-446ee200-06ef-11eb-8b37-0809a14b0f01.png)

The problem is that the unchecked menu item is announced as "selected" even when it is not checked. In our code we had added an `aria-selected` property to each IContextualMenuItem to address that issue, but it seems that is no longer working, perhaps when we updated to a newer version of the library.

Note, the `role` of each menu item is changed from default to `option` as the default narrator behavior of saying "Checkbox checked/unchecked" was dinged during an accessibility test pass - it should say "Selected" instead.

There does not seem to be a way to achieve the desired behavior with the current Fluent library.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/Jonotrono/pen/PoNrEBO?editors=1111

#### Actual behavior:

When using narrator for navigating through the menu items, narrator says "selected" for each menu item, even though only one of them is selected.

#### Expected behavior:

Narrator should say "selected" only for the selected menu item with the check next to it.

**Comment by tomi-msft** [comment]
@jon-msft Thanks for the issue! We'll look into this more.

**Comment by jon-msft** [comment]
Any update on this issue? We just got dinged again on an accessibility pass. Thanks!
