### ISSUE TITLE
SpinButton is not inheriting Fabric default fontFamily

### ISSUE THREAD

**Issue by jacklovett** [microsoft/fluentui#15362]
### Environment Information

"office-ui-fabric-react": "^7.144.2",

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/jacklovett/pen/bGebNPa

#### Actual behavior:

Since office-ui-fabric-react-7.140.0 when font-family: inherit was added to a number of input components here: https://github.com/microsoft/fluentui/pull/15172, SpinButton now displays as "Times" instead of the Fabric default font value. 

#### Expected behavior:

Expected behaviour is that SpinButton components would inherit the default Fabric font styles

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (Low)

**Comment by paulgildea** [comment]
@jacklovett Thanks for the issue! We'll look into this one.
