### ISSUE TITLE
ContextualMenu dismisses on window resize even with "calloutProps={{ preventDismissOnResize: true }}" set

### ISSUE THREAD

**Issue by kestill** [microsoft/fluentui#15369]
ContextualMenu dismisses on window resize even with `calloutProps={{ preventDismissOnResize: true }}` set

### Environment Information

- **Package version(s)**: ^7.135.0

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/kestill/pen/wvWwdEE

#### Actual behavior:

ContextualMenu will be dismissed when the window is resized

#### Expected behavior:

ContextualMenu should stay open when the window is resized

### Priorities and help requested:

Had a chat with @joschect, seems like the props are being passed to the underlying Callout as expected, but the ContextualMenu has a resize event of its own that is still dismissing the menu on window resize.

**Comment by tomi-msft** [comment]
@kestill Thanks for the issue! We will investigate more.
