### ISSUE TITLE
Combobox - allowfreeform is false and disabled is false the input element becomes readonly although we can choose from dropdown 

### ISSUE THREAD

**Issue by ashik-microsoft** [microsoft/fluentui#15406]
**Environment Information**
**Package version(s)**: 7.68.0
**Browser and OS versions:** Edge Version 85.0.564.68 (Official build) (64-bit) / Windows 10

**Describe the issue:**
Incorrect narration by screen reader i.e. read only is announced on combo box even if we are able to select options from combobox

[Codepen](https://codepen.io/ashik-microsoft/pen/ZEOYmoY?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F)

```
const { IComboBoxOption, IComboBoxStyles, VirtualizedComboBox, Fabric, initializeIcons } = window.Fabric;

// Initialize icons in case this example uses them
initializeIcons();

const comboBoxOption: IComboBoxOption[] = Array.from({ length: 1000 }).map((x, i) => ({
  key: `${i}`,
  text: `Option ${i}`,
}));

const comboBoxStyles: Partial<IComboBoxStyles> = { root: { maxWidth: '300px' } };

const ComboBoxVirtualizedExample: React.FC = () => (
  <Fabric className="ms-ComboBoxExample">
    <VirtualizedComboBox
      styles={comboBoxStyles}
      defaultSelectedKey="547"
      label="Scaled/virtualized example with 1000 items"
      allowFreeform={false}
      autoComplete="on"
      options={comboBoxOption}
      dropdownMaxWidth={200}
      useComboBoxAsMenuWidth
    />
  </Fabric>
);

const ComboBoxVirtualizedExampleWrapper = () => <Fabric><ComboBoxVirtualizedExample /></Fabric>;
ReactDOM.render(<ComboBoxVirtualizedExampleWrapper />, document.getElementById('content'))
```

Just check the combox input element by inspecting it and yo will see it as **readonly**.

![fabric](https://user-images.githubusercontent.com/72515761/95624636-d3d01880-0a94-11eb-9651-06f12368d601.png)

**Actual behavior:**
The narrator narrates incorrect information i.e. 'Read Only' when the focus lands on combo box.

**Expected behavior:**
The narrator shouldn't narrates 'Read only' with the correct information. It misguide the user's to use the functionality of the control.

**Comment by paulgildea** [comment]
@ashik-microsoft Thanks for the issue!

If you could provide a link to a codepen with the current issue that would be super helpful for our team to trouble shoot this issue to ensure we didn't introduce any regressions. Thanks!

**Comment by ashik-microsoft** [comment]
I have updated the description please check. @paulgildea

**Comment by paulgildea** [comment]
@ashik-microsoft Sorry for the late response. Updating to get this back in the triage queue. Thanks!

**Comment by ashik-microsoft** [comment]
HI @tomi-msft  any update on this ?

**Comment by tomi-msft** [comment]
Hi @ashik-microsoft thanks for the issue! It looks like setting allowFreeForm to false sets the readonly prop to true, which is causing the issue. I have submitted a fix which removes the check for allowFreeForm in v8, and will submit the same fix in v7, and it should resolve your issue.
