### ISSUE TITLE
Accessible label for SwatchColorPicker

### ISSUE THREAD

**Issue by MBSilverstein** [microsoft/fluentui#15418]
### Environment Information

- **Package version(s)**: ^7.132.0
- **Browser and OS versions**: Edge Version 85.0.564.68 (Official build) (64-bit) / Windows 10

### Describe the issue:

When a user navigates into a SwatchColorPicker using the keyboard, Narrator reads the color but doesn't provide information about the context (e.g. "main color" vs. "accent color").

### Please provide a reproduction of the issue in a codepen:

On the documentation site, any of the examples will demonstrate this issue. Narrator will read the color name but won't provide any information about how the color will be used.

https://fabricweb.z5.web.core.windows.net/oufr/7.145.0/#/examples/swatchcolorpicker

#### Actual behavior:

Narrator reads the color name (and position in a picker with multiple rows), but there isn't a good way to provide information about where the color will be used.

#### Expected behavior:

The SwatchColorPicker control should provide a way to specify an aria-label or aria-labeledby that will be read by Narrator when the control receives focus. It doesn't need to read that label while navigating between choices within a SwatchColorPicker, only when entering one from another control.

Related issue requesting a visible label: #11480.

Ideally a fix for this issue would be compatible with a fix for the color label including "read only" #15413.

### Documentation describing expected behavior

https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}

**Comment by paulgildea** [comment]
@MBSilverstein Thanks!

@smhigley FYI

**Comment by jamesedjac** [comment]
In taking a look a this it might be a good idea to change the semantics for the swatches to the [Radio Group semantics](https://www.w3.org/TR/wai-aria-practices-1.1/#radiobutton) instead of the grid semantics. 

A swatch picker is essentially a single choice selection group, just like a radio group, and is semantically simpler than a grid with selectable options. Plus more screen reader users will be familiar with the radio group design pattern than a selectable grid. But more importantly for this particular bug, Radio groups have a more established design pattern for dealing with this issue (an aria-label or aria-labelledby on the radiogroup element

**Comment by jamesedjac** [comment]
@tomi-msft and @paulgildea can we get un update on if this will be fixed?

**Comment by smhigley** [comment]
I definitely agree that a radiogroup seems like a better semantic choice for this control than grid, except for when colors are arranged in columns and rows by hue and lightness. I have no idea how feasible this is, but to me it would make sense to have two variations of the SwatchColorPicker, one with radios (which all current examples fit into), and one with grid for UI like this:

![grid of colors with hues in columns and lightness decreasing by row](https://user-images.githubusercontent.com/3819570/109730942-34a8dc00-7b6f-11eb-8a13-84ee56df25d5.png)

In the meantime, if you add an `aria-label` to the component, it adds it to the grid element. Narrator will read the name on a verbosity setting of 3 or higher. NVDA and JAWS read a grid's name on default settings as well.

i.e. something like this in the short term:
```
<SwatchColorPicker
   columnCount={5}
   colorCells={data}
   aria-label="Accent color"
/>
```

**Comment by dewcatpaint1** [comment]
Can we get an update on this item? Has the fix been scheduled? @smhigley @tomi-msft @paulgildea This item has had no update since March.

**Comment by zoarif** [comment]
I am also using this control and seeing the same issue. Is there an update on this?

**Comment by MBSilverstein** [comment]
@smhigley When I apply an aria-label or aria-labelledby to the SwatchColorPicker, the attribute gets applied to the table element rather than the FocusZone that surrounds it. If I manually apply the attribute the the FocusZone's div, I get a much better experience in Narrator. Would it be possible to get a smaller fix that lets us specify an "aria-labelledby" attribute value for the FocusZone?
