### ISSUE TITLE
Padding and margin ignore `!important`

### ISSUE THREAD

**Issue by hraz-msft** [microsoft/fluentui#15424]
### Environment Information

- **Package version(s)**: 0.14.4
- **Browser and OS versions**: Windows 10, Chrome, Edge

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluent-ui-themeprovider-and-makestyles-example-forked-9kjcv

#### Actual behavior:

The style
```
padding: "0 !important",
margin: "0 !important",
```
is been ignored because Fluent split it up without the `!important` flag.

![image](https://user-images.githubusercontent.com/66222191/95448094-712f2d80-096b-11eb-9194-7b9edf8416a3.png)

#### Expected behavior:

The padding and the margin will be zero (with `!important`).

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Internal Microsoft Product

**Comment by hraz-msft** [comment]
@paulgildea @tomi-msft can you assist please?

**Comment by paulgildea** [comment]
@hraz-msft Sorry for the late response. Thanks for the update on the package that you found the issue!

@xugao as FYI

**Comment by hraz-msft** [comment]
@paulgildea @xugao can you please assist? 

BTW, the issue still marked as `react-northstar` - I've never used the northstar theme

**Comment by hraz-msft** [comment]
@paulgildea @xugao @tomi-msft @dzearing ping...

**Comment by dzearing** [comment]
Just saw this. This is an issue in mergeStyles expandQuads logic. Essentially if the originating value has !important, the expanded values should carry it over.

The workaround is to expand it yourself:

```
paddingLeft: '0 !important',
paddingRight: '0 !important'
```

**Comment by dzearing** [comment]
If you have scenarios where it's not an antipattern, it would be good to understand, maybe there's a better solution.

**Comment by hraz-msft** [comment]
@dzearing sorry for the delay. Yes there are some cases. I use also 3rd-party UI libs that have no styling configuration, and I use the `makeStyles` hook factory or the `merge-styles` for CSS-in-JS.

The classes that are generated by those methods are just one level classes like `.root-37`. The 3rd party libs are using more specific then that like `.lib-root .lib-header`. 

And if the DOM is:
```
<div class="lib-root">
    <div class="lib-header root-37">
        ....
     </div>
</div>
```

They beats my style. So, instead of hardcoded the lib hierarchy in my CSS, I use `important` to beat their style definition

**Comment by dzearing** [comment]
@hraz-msft One alternative is to make your rules a little more specific. Example:

```
const useStyles = makeStyles({
  root: {
    '.myApp &': { // 2 levels of specificity, or use additional consecutive ampersands `&&&&` to raise it further.
       background: 'red' 
    }
  }
});
```

**Comment by hraz-msft** [comment]
Thank you! It is a cool work around, but I don't know if it better than `important` :) . 

Anyway, the original bug is when you add `important` Fluent doesn't always do it. This, I believe, should be fixed. But thanks for the work around, I will use it for our product.

**Comment by dzearing** [comment]
I think you're right @hraz-msft . Not necessarily better, just a different approach.

@behowell will help resolve this.
