### ISSUE TITLE
Groups of DetailsList not collapsing/expanding correctly - list not rerending

### ISSUE THREAD

**Issue by rickhellenthal** [microsoft/fluentui#15427]
### Environment Information

- **Package version(s)**: office-ui-fabric-react v7.142.1
- **Browser and OS versions**: Windows 10, Chrome, Edge

Behavior found in custom webpart running inside the spfx framework in SharePoint online.

#### Actual behavior:
Using the [DetailsList - Grouped](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/grouped) example from the docs, the list doesn't update when collapsing/expanding a group. Only after a different event the data of the column is shown/hidden accordingly.

using the `onDidUpdate` function of the DetailsList with a simple console log you can see that the list actually updates when collapsing/expanding, however, the data is not shown/hidden.

![bug_example](https://user-images.githubusercontent.com/15320967/95452095-08df4c80-0969-11eb-9f37-47885466a8dd.gif)

The code used in the gif above:
```
import { DetailsList } from "office-ui-fabric-react/lib/components/DetailsList/DetailsList";
import * as React from "react";

export const TestComponent = () => {
	const items = [
		{ key: "a", name: "a", color: "red" },
		{ key: "b", name: "b", color: "red" },
		{ key: "c", name: "c", color: "blue" },
		{ key: "d", name: "d", color: "blue" },
		{ key: "e", name: "e", color: "blue" },
	];

	const groups = [
		{ key: "groupred0", name: 'Color: "red"', startIndex: 0, count: 2, level: 0 },
		{ key: "groupgreen2", name: 'Color: "green"', startIndex: 2, count: 0, level: 0 },
		{ key: "groupblue2", name: 'Color: "blue"', startIndex: 2, count: 3, level: 0 },
	];

	const columns = [
		{ key: "name", name: "Name", fieldName: "name", minWidth: 100, maxWidth: 200, isResizable: true },
		{ key: "color", name: "Color", fieldName: "color", minWidth: 100, maxWidth: 200 },
	];

	return (
		<div>
			<DetailsList items={items} groups={groups} columns={columns} />
		</div>
	);
};
```

#### Expected behavior:
The expected behavior would be that the groups could be collapsed/expanded just like in [the example in the docs](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/grouped).

### Workaround
By adding a useState hook with some arbitrary value, and setting this to a different value using the `onToggleCollapse` function in the `groupProps` of the DetailsList we can trigger a rerender, this causes the group to exapand/collapse as expected.
Doing the same for the `onToggleCollapseAll` function allows the 'collapse all' button to work as expected as well.

I also noticed that it's necessary to have the column definition inside the component, I put it above the component at first, but this also breaks it.

![bug_example_fixed](https://user-images.githubusercontent.com/15320967/95455329-fca9be00-096d-11eb-87fc-a49b14534ca8.gif)

Code used in the gif above:
```
import { DetailsList } from "office-ui-fabric-react/lib/components/DetailsList/DetailsList";
import * as React from "react";

export const TestComponent = () => {
	const [someState, setSomeState] = React.useState(false);

	const items = [
		{ key: "a", name: "a", color: "red" },
		{ key: "b", name: "b", color: "red" },
		{ key: "c", name: "c", color: "blue" },
		{ key: "d", name: "d", color: "blue" },
		{ key: "e", name: "e", color: "blue" },
	];

	const groups = [
		{ key: "groupred0", name: 'Color: "red"', startIndex: 0, count: 2, level: 0 },
		{ key: "groupgreen2", name: 'Color: "green"', startIndex: 2, count: 0, level: 0 },
		{ key: "groupblue2", name: 'Color: "blue"', startIndex: 2, count: 3, level: 0 },
	];

	const columns = [
		{ key: "name", name: "Name", fieldName: "name", minWidth: 100, maxWidth: 200, isResizable: true },
		{ key: "color", name: "Color", fieldName: "color", minWidth: 100, maxWidth: 200 },
	];

	return (
		<div>
			<DetailsList
				items={items}
				groups={groups}
				columns={columns}
				groupProps={{
					headerProps: {
						onToggleCollapse: () => setSomeState(!someState),
					},
					onToggleCollapseAll: () => setSomeState(!someState),
				}}
			/>
		</div>
	);
};
 
```

### Priorities and help requested:
Requested priority: (~~Blocking, High, Normal,~~ Low)
Low because it can be fixed by using a workaroud.

**Comment by paulgildea** [comment]
@rickhellenthal Thanks for filing the issue and providing the workaround!
