### ISSUE TITLE
makeStyle regression

### ISSUE THREAD

**Issue by hraz-msft** [microsoft/fluentui#15423]
### Environment Information

- **Package version(s)**: 0.14.4
- **Browser and OS versions**: Windows 10, Chrome, Edge

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluent-ui-themeprovider-and-makestyles-example-forked-hg3sm

#### Actual behavior:

The classes are undefined when there is no ThemProvider. This is a regression from version 0.9.0.

#### Expected behavior:

In 0.9.0 the default Fluent theme was applied automatically if the ThemeProvider wasn't defined.
https://codesandbox.io/s/fluent-ui-themeprovider-and-makestyles-example-forked-xuvyj

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Internal Microsoft Products

**Comment by hraz-msft** [comment]
Tagging @dzearing for awareness (https://github.com/microsoft/fluentui/issues/14622)

**Comment by dzearing** [comment]
Yup known limitation, and being resolved shortly. We abstracted the css renderer in an interface, and make ThemeProvider provide a default, so when ThemeProvider is missing, the renderer is missing. We did this to abstract the dependency on merge-styles; however, it's going to cause a lot of headache, so I'm going to move the default fallback lower into the hook, which will resolve

**Comment by paulgildea** [comment]
@hraz-msft / @dzearing Thanks for coordinating on this folks!

**Comment by dzearing** [comment]
https://codesandbox.io/s/fluent-ui-themeprovider-and-makestyles-example-forked-c059c?file=/src/App.tsx

This has been resolved in the latest releases.
