### ISSUE TITLE
DatePicker incorrect placement of calendar icon in RTL mode

### ISSUE THREAD

**Issue by dev-a11y** [microsoft/fluentui#15426]
### Environment Information

- **Package version(s)**: 7.144.3

#### Actual behavior:

Calendar icon remains on the right side for both LTR and RTL mode.
![image](https://user-images.githubusercontent.com/59690753/95454135-5315fd00-096c-11eb-97ed-95a2860d1918.png)

#### Expected behavior:

In RTL mode icon should be on the left (as it would not overlap placeholder text).

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: [demo site](https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker)

**Comment by paulgildea** [comment]
@dev-a11y Thanks for filing an issue!
