### ISSUE TITLE
Overflow set : Icons not appearing in overflow items 

### ISSUE THREAD

**Issue by riya332** [microsoft/fluentui#15422]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@riya332 Please provide more information about this issue. Thanks.
