### ISSUE TITLE
Callouts, such as context menus, render twice

### ISSUE THREAD

**Issue by paperbackdragon** [microsoft/fluentui#15437]
### Environment Information

- **Package version(s)**: 7.145.0
- **Browser and OS versions**: Edge 80.0.3987.0

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/heatherhb/pen/VwjYPXr?editable=true%3Dhttps%3A%2F%2Ffabricweb.z5.web.core.windows.net%2Foufr%2F7.145.0%2F

I can't see the React profiler trace in this since my browser seems to not detect React 16.5+ being used, but it should reproduce with any context menu (and possibly other callouts).

Picture of the multiple renders in the profiler:
![2020-10-08 17_29_08-Modern File Explorer app - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/899430/95528055-e7438c80-098b-11eb-9d9f-6b5a34401d1c.png)

#### Actual behavior:

The context menu seems to render twice. In our puppeteer tests, puppeteer detects that the element exists and is visible and immediately tries to click an option in the context menu. When that occurs, another render happens, which means the click never actually clicks anything. To work around this we've had to put delays in our functional tests before clicking any context menu items. This wasn't an issue until we specifically upgraded Fabric.

#### Expected behavior:

Once the context menu renders once, it won't re-render unless some visual aspect of it changes.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, but I might need some help to understand where the problem would be

Requested priority: High

Products/sites affected: N/A - just a problem in our functional tests right now.

**Comment by taenri** [comment]
To elaborate on this issue: We originally thought it was only affecting the functional tests for one part of our repo, but in reality it is causing the entirety of our repo's BVTs to fail as well.

**Comment by paulgildea** [comment]
@paperbackdragon Thanks for filing this issue and doing some perf analysis.

@tomi-msft / @joschect Can you two try to coordinate and see if we can verify the root cause and provide @paperbackdragon any help to contribute a fix?

**Comment by joschect** [comment]
@paperbackdragon I believe that this is intended behavior. In order to position itself properly, the callout must first render itself once, hidden, then measure itself since its size is determined by the position/size of its contents. Then it must position itself again with all the positioning information correct.

**Comment by paperbackdragon** [comment]
@joschect I'll see if I can confirm that it's hidden first -- at least with the test frameworks we're using (two different ones), it seems to think the callout is visible the first time. Is it possible that's happening?

**Comment by joschect** [comment]
@paperbackdragon What do you mean by "visible" ? It is present and on the page, it's just not positioned properly. I believe it's opacity is set to 0 rather than the hidden attribute being set.

**Comment by paperbackdragon** [comment]
Oh interesting, yeah I was referring to the hidden attribute. I think the fact that it's not hidden is what's causing the issues in our UI tests. What was the reason behind using opacity rather than hidden/visible?
