### ISSUE TITLE
No Time input (with switch buttons too)

### ISSUE THREAD

**Issue by wojciek** [microsoft/fluentui#15444]
#### Describe the feature that you would like added

Actual package doesnt have any way to implement input type="time" or something like this. The need is that thie time input with spinbuttons which will change the value depending on the cursor position. It is also necessary to enter the hours/minutes manually on such a mask "__:__"

#### What component or utility would this be added to

<SpinButton
type="time"
maxHour="50"
minHour="00"
maxMin="99"
minMin="00"
manualInput="true"
customIncrementIcon={.......}
customDecrementIcon={........}
handleOnIncrement={() => ...}
handleOnDecrement={() => ......}
.... the other options like in SpinButton and TextInput
/>

This is soooo necessary 👍

**Comment by paulgildea** [comment]
@wojciek Thanks for filing this feature request.

I’ll mark this as a feature request and add it to our backlog, but to set expectations - we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. We'll take this into consideration when we address Time based scenarios across our two React packages.

Thanks!

**Comment by paulgildea** [comment]
Also you might be able to provide a workaround experience by providing a `mask` on the `TextField` component. While this won't provide you the developer experience you outlined previously, you may be able to provide a rudimentary user experience for time input.
