### ISSUE TITLE
Charting: Vertical stacked bar chart, on click of bars, 'uncaught type error' showing in consol.

### ISSUE THREAD

**Issue by jameelakowsar** [microsoft/fluentui#15465]
### Environment Information

- **Package version(s)**: 4.2.0
- **Browser and OS versions**: All browsers

### Please provide a reproduction of the bug in a codepen:
When click on vertical stacked bar chart bars, getting below error in console.

![image](https://user-images.githubusercontent.com/20105532/95719442-6e934780-0c8d-11eb-8e19-107462bc965c.png)

**Comment by paulgildea** [comment]
@Raghurk FYI

**Comment by jameelakowsar** [comment]
FIxed
