### ISSUE TITLE
Support Yarn 2

### ISSUE THREAD

**Issue by rizkyramadhan** [microsoft/fluentui#15466]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@rizkyramadhan Thanks for the issue.

@ecraig12345 just as FYI

Thanks for the suggestion, we do believe investing in our build infrastructure to enable more contributors to provide fixes and enhancements to the code base. We'll take this under consideration when we believe we need to upgrade our build tools. Unfortunately, I don't have any timelines to share at this time when we will address it - I'm going to close this issue in the meantime.

Thanks!
