### ISSUE TITLE
@fluentui/react-button has no styles since 0.12.5

### ISSUE THREAD

**Issue by Gerhut** [microsoft/fluentui#15460]
### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluent-ui-button-forked-hiu31?file=/src/App.js

Free to change the version of @fluentui/react-button, between 0.12.4 and 0.12.5

#### Actual behavior:

No styles since 0.12.5

#### Expected behavior:

Some styles applied before 0.12.4 (inclusive)

**Comment by paulgildea** [comment]
@Gerhut Thanks for filing this issue! We'll look into it.

@miroslavstastny FYI

**Comment by khmakoto** [comment]
@dzearing @xugao could this be because of the dependency it had on `ThemeProvider`?

**Comment by dzearing** [comment]
This is because the style renderer does not have a default without ThemeProvider defining it.

I'm changing the hook to default to mergeStyles. I think it's a requirement here.

(The workaround for now is use ThemeProvider.)

**Comment by dzearing** [comment]
Is being resolved in this PR: #15433

**Comment by paulgildea** [comment]
@dzearing Thanks for the quick response!

**Comment by Gerhut** [comment]
> (The workaround for now is use ThemeProvider.)

Works well, thanks!

**Comment by hadnet** [comment]
I'm trying to use ```js import {Button} from '@fluentui/react-button'``` with Next.js without luck. I can't get the styles for the Button using this packages and even if I use ThemeProvider:

```json
    "@fluentui/merge-styles": "^8.0.0-beta.0",
    "@fluentui/react": "^8.0.0-beta.6",
    "@fluentui/react-button": "^0.17.2",
    "@fluentui/react-theme-provider": "^0.16.3",
    "@fluentui/utilities": "^8.0.0-beta.3",
```

but using ```jsimport {PrimaryButton} from '@fluentui/react/lib-commonjs/compat/Button'``` I get the styles.

**Comment by layershifter** [comment]
As issue was solved, closing this for housekeeping 🏡
