### ISSUE TITLE
Theme related cleanup work

### ISSUE THREAD

**Issue by xugao** [microsoft/fluentui#15475]
Related issue: #14740

Changes which should be made when `ThemeProvider` is officially released:
- [ ] Replace `Customizer` and `Fabric` everywhere in our code.
- [x] Update https://aka.ms/themedesigner to point back to `master` pr-deploy site.

**Comment by ecraig12345** [comment]
@xugao Is this actually in progress or should it be moved back to "to do"?

**Comment by ecraig12345** [comment]
Closing since this probably won't be a priority right away, and we can make a new tracking item when we come back to it.
