### ISSUE TITLE
Body scrolls with allowTouchBodyScroll={true}

### ISSUE THREAD

**Issue by Joebob12** [microsoft/fluentui#15476]
#### Actual behavior:

The body of an overlay/modal scrolls:
https://codepen.io/joenied/pen/mdEedQq

This seems like allowTouchBodyScroll was known when the prop was introduced here:
https://github.com/microsoft/fluentui/pull/11339#discussion_r354572316

Creating a bug report for tracking purposes

#### Expected behavior:

Allow touch and zoom within a modal without body scroll

### Priorities and help requested:

Are you willing to submit a PR to fix? no
Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@Joebob12 Thanks for filing this issue!
