### ISSUE TITLE
@uifabric/foundation withSlots traverses React.Children even if already provided via parent component e.g. StackView

### ISSUE THREAD

**Issue by KevinTCoughlin** [microsoft/fluentui#15473]
Follow-up of https://github.com/microsoft/fluentui/pull/15462. `withSlots` should re-use `children` without having to recursively traverse the component tree (expensive). There are TODO comments mentioning this inefficiency. It appears that the method signature can be reworked to avoid having the re-flatten the `React.Children` to an array. See the "blue" and "red" outlined call stacks below.

![image](https://user-images.githubusercontent.com/706967/95779991-f5412800-0c7f-11eb-80f7-c5baf1e4f635.png)

https://github.com/microsoft/fluentui/blob/e915a1926c9b821f9f0d75e88445d1c431a284fc/packages/foundation/src/slots.tsx#L57

Can we re-use `...children: React.ReactNode[]` already traversed via `map` in `StackView` and passed into `withSlots`? This would eliminate the red call stack entirely.

`React.Children` traversal can be a performance bottleneck for wrapper components if the component sub-tree is large.

### Environment Information

- **Package version(s)**: `@uifabric/foundation` and dependents
- **Browser and OS versions**: ALL

### Please provide a reproduction of the bug in a codepen:

Profile this page using the browser's performance profiler to observe the performance bug: https://cdpn.io/kevintcoughlin/debug/gOMaYYV.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OneDrive & SharePoint

**Comment by paulgildea** [comment]
@KevinTCoughlin Thanks!

@dzearing - FYI

**Comment by dzearing** [comment]
Yup! Talked with Kevin about it a couple days ago. Great find.

I did a search of Children.count usage in the repo:

![image](https://user-images.githubusercontent.com/1110944/96021356-2480a200-0e04-11eb-80c5-611efccea349.png)

@khmakoto I see some usage in Card that seems unnecessary. That should be fixed.

The Text component is being redone in the `@fluentui/react-text` package, and does not have the reference.

The `LayoutGroup` component in the experimental package should be deleted; in fact we should be deleting all of the dusty components we know aren't used in ODSP, and any we do know should be moved out of experiments into their own package (Tile, TileView)
