### ISSUE TITLE
Usage information missing for DetailsList - Shimmer 

### ISSUE THREAD

**Issue by nairmanu** [microsoft/fluentui#15479]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Chrome/macOS

#### Actual behavior:
Error while accessing documentation in Chrome
![image](https://user-images.githubusercontent.com/17596471/95786886-4ad00180-0c8d-11eb-8972-fcf37c217d2e.png)

#### Expected behavior:
Documentation should list details of how to implement the component along with available properties and interfaces

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@nairmanu Thanks for the issue!
