### ISSUE TITLE
Add type for data property on ISelectableOption 

### ISSUE THREAD

**Issue by ashwinGokhale** [microsoft/fluentui#15487]
#### Describe the feature that you would like added
I would like to be able to provide my own type to the data property on the ISelectableOption interface

#### What component or utility would this be added to
The  ISelectableOption interface in packages\react-internal\src\utilities\selectableOption\SelectableOption.types.ts

#### Have you discussed this feature with our team, and if so, who
No

**Comment by paulgildea** [comment]
@ashwinGokhale Thanks for filing an issue!

@dzearing / @JustSlone as FYI for this contribution

**Comment by JustSlone** [comment]
@ashwinGokhale Can you elaborate on the motivation or problem this would solve? Are there any trade offs that are worth mentioning or alternative solutions to consider?

**Comment by ashwinGokhale** [comment]
@JustSlone 

We have an internal UI framework based on fluent and we have a certain component based on the fluent dropdown. When we provide `options` to our custom dropdown, we need to use the `data` property, but since we use Typescript, we would also like to strongly type the `data` property. The props in our custom component extends from `IDropdownOption`, which extends from `ISelectableOption`. In order to do this, we can pass a generic type from 
`ICustomDropdownOption<T = any> extends IDropdownOption<T>` --> `IDropdownOption<T = any> extends ISelectableOption<T>` --> `ISelectableOption<T = any>`. 
I think by keeping the default value of the generic as `any`, we can avoid breaking changes while also providing the option to strongly type the dropdown options.

**Comment by JustSlone** [comment]
Thanks for the explanation 
Tagging and assigning to @joschect to look into feasibility here. 

@ashwinGokhale if the proposed change looks reasonable, are you willing to submit at PR for it?

**Comment by joschect** [comment]
@JustSlone and @ashwinGokhale I think that we can make this happen. Having `IDropdownOption<T = any>` is a great solution to preserve backwards compatibility while still allowing it to be typed.

**Comment by ashwinGokhale** [comment]
Hi @joschect and @JustSlone I have created a PR for this last week: https://github.com/microsoft/fluentui/pull/15488. Please take a look when you get a chance.
