### ISSUE TITLE
Space at the end of DetailsList

### ISSUE THREAD

**Issue by hraz-msft** [microsoft/fluentui#15492]
### Environment Information

- **Package version(s)**: 7.77.0
- **Browser and OS versions**: Windows 10, Edge, Chrome

### Please provide a reproduction of the bug in a codepen:

This is not deterministic issue.

#### Actual behavior:

Sometimes DetailsList generates a page with hardcoded height at the end of the list:
![image](https://user-images.githubusercontent.com/66222191/95866227-55af9280-0d70-11eb-977f-58eda7286675.png)

#### Expected behavior:

No unnecessary spaces will be generated.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Internal

**Comment by paulgildea** [comment]
@hraz-msft I know that it's not deterministic, but do you have a codepen that we can take a look at?

@dzearing / @joschect FYI - not sure if this extra space is part of UI virtualization to make space for more items.

**Comment by rhalaly** [comment]
I tried to create a repro, but it doesn't repro in CodePen (maybe it something in our configuration, because I see more weird issues with the DetailsList). I will continue to try to create a repro / fix our issues. Sorry for the delay....

BTW, if I don't need the virtualization, can I turn it off?

**Comment by rhalaly** [comment]
Hmm, I tried to create a repro in CodeSandbox: https://codesandbox.io/s/detailslist-5t0gt 
Although, it is not very deterministic issue, you can see that something with the rendering is not very good. The code demostrate our layout (with all the flex, some have side panels and headers), and for some reason the DetailsList not working smoothly.

The space issue not happening all the time and I'm still trying to find the root cause of the issue. 
But you can see that it has other rendering issue - it is not very responsive - if the window grows the columns grow with it, but if the window shrinks the the columns are **not** shrink with it.

![image](https://user-images.githubusercontent.com/8597700/96120749-b2898500-0ef7-11eb-8791-5af86c695556.png)

We had a custom made list in our web and everything was good before the DetailsList...

**Comment by rhalaly** [comment]
It seems that the space issue is not really a space issue - but it doesn't render existing items. I mean, some items are been replaced by "nothing".

**Comment by hraz-msft** [comment]
I think that I found a solution for the spacing. It was an issue with the `data-is-scrollable`, so I believe it couldn't listen to the scroll event correctly. 

Now my biggest issue is the responsiveness - for some reason under those flex the columns are not responsive when the window shrink.

**Comment by hraz-msft** [comment]
@paulgildea who can assists with the responsiveness issue? I sent my repro 11 days ago...

**Comment by varshajawale** [comment]
@hraz-msft even I am facing this issue. What is the solution that you found for this?

**Comment by hraz-msft** [comment]
For the space at the bottom - my issue was with the `data-is-scrollable` attribute. It didn't work well with the custom scrollbars library that I used.

For the responsiveness - I don't have  a solution yet. @paulgildea @dzearing can you assist please?

**Comment by varshajawale** [comment]
@hraz-msft did you set data-is-scrollable to false?

**Comment by hraz-msft** [comment]
`data-is-scrollable={true}` to the container with the scroll. Now I don't use any custom scrollbars library because I didn't find any library that working correctly with the scroll events for the DetailsList

**Comment by varshajawale** [comment]
@hraz-msft I have given data-is-scrollable=true to the controller still there is an empty space in the bottom

**Comment by hraz-msft** [comment]
You need to add it to the right element in the DOM. Can you please provide a sample code in CodeSandbox?

**Comment by dzearing** [comment]
@hraz-msft Why are you using display flex that way? It will fight with the column resizing. Comment out all your custom styling and it works as expected when you resize.

I still haven't seen a repro of the "blank space" at the end, but I do think as you mentioned, that this probably was caused by a custom scroll div not having the `data-is-scrollable` attribute on it, which would have meant the list can't pick up the right scroll events.

**Comment by hraz-msft** [comment]
@dzearing The `data-is-scrollable` didn't work well with custom scrollbars libraries...

About the Flex, it is our page layout. We have some menus, banners, panels, etc. The DetailsList is the main content of the page, inside all these flexes. Note that we used a 3rd-party list component and it worked well in this layout. The issue started when we replaced list to DetailsList.

**Comment by Teddy1313** [comment]
Any ETA on fix? Thank you

**Comment by hraz-msft** [comment]
@dzearing ping

**Comment by dzearing** [comment]
I don't really see how a fix could be made, without having a clear repro and understanding the unique set of circumstances where blank space situation occurs. It could be browser specific, or data set specific, customer row rendering specific, page layout specific. A flexbox or UI elements above or around the list may be pushing things around, where the virtualized list believes that page is not on screen when it actually is.

Paging @ThomasMichon here, as he may have ideas or theories here.

The reason for a blank page circumstance like that is that the list thinks that that page is not visible. It could have been that it didn't get a scroll event to recompute visible items, or that something above the list moved it up in the scroll window to bring that last page into view without a scroll event. It's clear it thinks its not visible, when it is. So I'm wondering why, and when this occurs, and factors which might contribute to that.

If your list of items is short enough, one workaround would be to disable virtualization; that would prevent this situation:

```tsx
<DetailsList columns={columns} items={items} onShouldVirtualize={ ()=>false} />
```

**Comment by hraz-msft** [comment]
@dzearing what about the irresponsiveness? Do you want me to create a separate bug for it?

**Comment by dzearing** [comment]
@hraz-msft What do you mean by irresponsiveness?

**Comment by hraz-msft** [comment]
This comment: https://github.com/microsoft/fluentui/issues/15492#issuecomment-709249117

The DetailsList does not shrink inside flex layout. Do you prefer to track it in a different issue thread?

**Comment by dzearing** [comment]
I am still having trouble given the complexity of the codesandbox. Could you isolate and say what was expected and what was resulted? Sorry, there's a number of flexboxes in there and I don't understand what the expectation is that's not happening.
