### ISSUE TITLE
Dropdown items are truncated in reflow mode with no way to determine the full value on Mobile Safari

### ISSUE THREAD

**Issue by sewatson** [microsoft/fluentui#15498]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: iOS Safari 14.0.1

### Please provide a reproduction of the bug in a codepen:

1. Navigate to https://codepen.io/sewatson/pen/mdEeLrx on iOS Safari
1. Select the dropdown
1. See the items opened in a panel

#### Actual behavior:

Items are rendered truncated with no way to view full value

#### Expected behavior:

Items are rendered truncated with a way to view full value

### Priorities and help requested:

Are you willing to submit a PR to fix? 
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
https://portal.azure.com

**Comment by paulgildea** [comment]
@sewatson Thanks for the issue!

**Comment by sewatson** [comment]
Bumping
