### ISSUE TITLE
RFC: component hooks should only return state, not render function.

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#15497]
## Proposal

Currently component hook pattern will export render function and state:

```tsx
import { useButton } from '@fluentui/react-button';

export const Button = (props) => {
  const { render, state } = useButton();
  return render(state);
```

Propose that it only returns state and we export the render function separately:

```tsx
import { useButton, renderButton } from '@fluentui/react-button';

export const Button = (props) => {
  const state = useButton();
  
return renderButton(state);
```

## Why

* If you provide your own render function, you don't download the original just to use the hook
* Separation of concerns - they don't necessarily need to be used together all the time

**Comment by dzearing** [comment]
We will go ahead with this improvement, after talking to a number of folks internally. Just makes sense.

**Comment by JustSlone** [comment]
I agree with this change. Thanks to @soettl for pointing this out.
