### ISSUE TITLE
SSR failed in DropDown

### ISSUE THREAD

**Issue by Gerhut** [microsoft/fluentui#15491]
### Environment Information

- **Package version(s)**: @fluent-ui/react-next@v8.0.0-alpha.126
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/summer-rain-olru7?file=/pages/index.js

#### Actual behavior:

Server Error
ReferenceError: window is not defined

#### Expected behavior:

No errors

### Priorities and help requested:

Seems https://github.com/microsoft/fluentui/pull/15401/files#diff-b2dc1893abb30d29e76641c03a5b993bb38567433e0e8bf7839c921474496641L18-R20 may fix this issue, will it be merged back to 7.0 which seems be published to npm?

**Comment by paulgildea** [comment]
@Gerhut Thanks for filing this issue! 

@dzearing Thanks for the impact of the issue.

**Comment by dzearing** [comment]
@joschect will make a fix.

**Comment by joschect** [comment]
Yep! Can do!

**Comment by layershifter** [comment]
@Gerhut thanks for the report 👍 

---

In #16239 `@fluentui/react-next` package was removed, now we are using `@fluentui/react` as the main packages, beta releases are available there.

I followed [Server Side Rendering guide](https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing) and created sandboxes for v7 and v8 beta (both based on your example):
- 8.0.0-beta.32 https://codesandbox.io/s/ssr-issue-in-dropdown-15491-zd6ju
- 7.155.3 https://codesandbox.io/s/ssr-issue-in-dropdown-15491-v7-6i4sj

In both cases it works like a charm 💎 Please let me know if I missed something.
