### ISSUE TITLE
Blocking Dialog/Modal always gets assigned role "alertdialog" when IsBlocking is true

### ISSUE THREAD

**Issue by jongonzamsft** [microsoft/fluentui#15499]
### Environment Information

- **Package version(s)**: 7.128.1
- **Browser and OS versions**: Edge 86.0.622.38 Windows 10 Enterprise

### Describe the issue:

The Modal component always sets the role of the dialog to "alertdialog" when "isBlocking" is set to true. The example given for a modal dialog [here](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html) shows 

#### Actual behavior:

Setting a dialog/modal to "IsBlocking" always set the role to "alertdialog"

#### Expected behavior:

The role of the dialog shouldn't be exclusively determined by the "IsBlocking" flag. 

### Documentation describing expected behavior

https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html
https://www.w3.org/TR/wai-aria-1.1/#alertdialog
https://www.w3.org/TR/wai-aria-1.1/#alert

**Comment by paulgildea** [comment]
@jongonzamsft Thanks for filing the issue!

@smhigley - FYI on the model here. Thanks!

**Comment by ryperl** [comment]
Is there any response to a timeline to fix this issue, I am also facing this issue using the code from the documentation here - https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog

Also seeing that if you set the property to show the showCloseButton, the Close button (X) is not being displayed in the upper corner.
