### ISSUE TITLE
Control type of CommandBar item is not correct

### ISSUE THREAD

**Issue by SerhiiYatsenko** [microsoft/fluentui#15493]
### Environment Information

- **Package version(s)**: (7.0.1)
- **Browser and OS versions**: (all browser and Windows 10)

### Describe the issue:
The [CommandBar](https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar) item looks like a button but [Accessibility Insights for Web ](https://accessibilityinsights.io/docs/en/web/overview/) detects it as MenuItem so screen reader users will receive the wrong information and thus use the wrong keys to access it.

![Screenshot_229](https://user-images.githubusercontent.com/16796085/95871022-da50df80-0d75-11eb-90d5-958d20d7f4f4.png)

### Please provide a reproduction of the issue in a codepen:
[Codepen](https://codepen.io/pen/?&editable=true=https%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui)

#### Actual behavior:
Control type of CommandBar item is MenuItem.

#### Expected behavior:
Control type of CommandBar item is Button.

**Comment by paulgildea** [comment]
@SerhiiYatsenko Thanks for the issue!

@smhigley - Is this related to #14805 ?
