### ISSUE TITLE
add line to the vertical bar chart

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#15506]
#### Describe the feature that you would like added

according to the figma https://www.figma.com/file/sRqcZakGJ4VpXFWOwBftSU/Apps-health?node-id=30%3A78
we should add line to the vertical bar chart

for more info refer
https://office.visualstudio.com/OC/_workitems/edit/4461315

#### What component or utility would this be added to

vertical bar chart

#### Have you discussed this feature with our team, and if so, who
yes

**Comment by paulgildea** [comment]
@Raghurk FYI 👍
