### ISSUE TITLE
Allow ariaDescription as a prop on IContextualMenuItem 

### ISSUE THREAD

**Issue by SavannahBourgeois** [microsoft/fluentui#15510]
### Environment Information

- **Package version(s)**: all
- **Browser and OS versions**: all

### Describe the issue:

In office, we set the aria-description directly instead of using aria-describedBy for our tooltips. Can we get support for an ariaDescription optional prop on IContextualMenuItem  so that we can set the aria-label to be the menu item label and the aria-description to be the custom tooltip content? That way it would match the way we set things for all of our buttons throughout the product.

### Please provide a reproduction of the issue in a codepen:
Here is a codepen that's not very helpful but you can see there isn't a prop to set ariaDescription on a menu item.
https://codepen.io/savannahbourgeois/pen/jOrWMMJ

#### Actual behavior:
No prop for setting ariaDescription.

#### Expected behavior:
There is an ariaDescription prop in the same way there is ariaLabel

### Documentation describing expected behavior
Allow users a secondary way to set aria-description directly. Feel free to @ me if you need more info but since buttons already support an ariaDescription prop, it would be great if menu items did as well.

**Comment by paulgildea** [comment]
@SavannahBourgeois Thanks for the feedback. Is this something you'd be willing to contribute a change?

**Comment by SavannahBourgeois** [comment]
@paulgildea I don't have time currently but I can try in a few weeks if needed and no one on Fluent has time. We have an accessibility bug on it which needs to be fixed in 60 days and I will have to do additional work on our side once this support is in.
