### ISSUE TITLE
Nuget package to generate the image as either a bitmap or a base 64 encoded string

### ISSUE THREAD

**Issue by digit01Wave** [microsoft/fluentui#15514]
#### Describe the feature that you would like added

Nuget package to generate the image as either a bitmap or a base 64 encoded string

#### What component or utility would this be added to

We generate emails in our backend to send to our customers. We would like to use the package to generate the same initials image used by Fabric UI instead of our own custom code (uses System.Drawing to pick the color and draw the text).

#### Have you discussed this feature with our team, and if so, who

Discussed briefly with elcraig@microsoft.com

#### Additional context/screenshots
Here is an example of what it looks like in our email.
![image](https://user-images.githubusercontent.com/4121745/96046330-29574d00-0e28-11eb-9eff-11d0ab661d63.png)

I am willing to also assist in the effort if needed (also a Microsoft employee - alias (jehoang)

**Comment by paulgildea** [comment]
@digit01Wave Thanks for the feature request and the opportunity to contribute to Fluent UI.

Let's continue the dialog to see where we can find a place for this type of utility. Love the idea for generating server side - the interesting thing will be the implementation details. Since you mention Nuget and System.Drawing, I'm assuming you use C# for your backend so I'm also curious on your frontend end usage.

I'll follow up with jehoang too.

**Comment by paulgildea** [comment]
@JustSlone - FYI

**Comment by JustSlone** [comment]
Interesting idea. Though it sounds like this proposal is to create a second implementation of the code in C#. I would worry about maintaining two implementations here. @digit01Wave Is it possible to use Typescript/NPM instead here?

**Comment by digit01Wave** [comment]
Yes. This code will be used in C#, which means that there will probably be two implementations here.

**Comment by sukotekar** [comment]
Do we have anything planned around this new feature? I wanted to use this feature in our project. 
So wanted to know if we have any timeline decided for Nuget package release?

**Comment by JustSlone** [comment]
@digit01Wave and @sukotekar we don't have expertise or the build system to ship C# nuget packages in this repo, it's purely TypeScript. We'd be happy to help someone else open source the C# implementation (to the best of our ability).

Going to close this issue out given this it out of scope for this project, sorry we can't be more helpful ☹
