### ISSUE TITLE
When ToolTipHost is wrapping a button's context menu items, a tool tip is not always shown

### ISSUE THREAD

**Issue by izikl** [microsoft/fluentui#15512]
When wrapping a button's sub items with ToolTipHost no tool tip is shown when changing focus with the keyboard and also when hovering over the first context item for the first time. 

### Environment Information

- **Package version(s)**: 7.93.0 and 7.142.1
- **Browser and OS versions**:  Edge 86

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/izlisbon/pen/zYBrByg

#### Actual behavior:

- ToolTip is not shown on first hover 
- ToolTip is not shown when changing focus with keyboard

#### Expected behavior:

- Tooltip should always be shown on hover. 
- Tooltip should show when changing focus with keyboard (This is an accessibility requirement and it works fine on the button itself)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) - No

Requested priority: (Blocking, High, Normal, Low) - High just because most accessibility bugs are high. 

Products/sites affected: (if applicable)
https://dataexplorer.azure.com/clusters/help/databases/Samples?query=H4sIAAAAAAAAA3POL8tMMbSMT8tJLOGqUShJzE5VMDQAAEp2jSoWAAAA

Click run and then open the Expand View button:
![image](https://user-images.githubusercontent.com/8294298/96034657-b396b580-0e16-11eb-8024-c6f944471b6a.png)

**Comment by paulgildea** [comment]
@izikl Thanks for the filing this issue!
