### ISSUE TITLE
Rendering more than 1000 items in the dropdowns is pretty slow

### ISSUE THREAD

**Issue by AbdelrhmanMagdy** [microsoft/fluentui#15525]
Are there any plans to support items virtualization in the dropdowns? if not, do you have any suggestions to tackle this problem?

Please check this [code snippet](https://codepen.io/abdelrhmanmagdy/pen/bGeEvar?editors=1010)

**Comment by paulgildea** [comment]
@AbdelrhmanMagdy Thanks for the issue.

@joschect / @dzearing - (Please correct me if I'm wrong here)

Currently this is a known limitation of the `Dropdown` component, in that it does not provide a UI virtualization. A potential work around is to leverage the `ComboBox` component: https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox

Hope this helps.
