### ISSUE TITLE
there is no overlay property on overflow in IRawStyleBase

### ISSUE THREAD

**Issue by iqbal99** [microsoft/fluentui#15524]
i want to use overflow in stack element, but there is no overlay property on overflow in IRawStyleBase.
IRawStyleBase.overflow?: "initial" | "inherit" | "unset" | "auto" | "hidden" | "scroll" | "visible"

please add this if possible.

**Comment by paulgildea** [comment]
@iqbal99 Thanks for the issue.

@tomi-msft / @khmakoto - is there a work around that would allow direct CSS access or does this need to be a property addition?

**Comment by iqbal99** [comment]
yes it can be handeld with css, but it doesn't give flexibility in javascript and you  have to go long way to handle it. it would be helpfull if you can provide direct property.
