### ISSUE TITLE
Virtualized tree prototype does not retain focus after siblings expanded by '*' key

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/fluentui#15529]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar 0.51.0
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

1. Navigate to https://fluentsite.z22.web.core.windows.net/virtualized-tree
2. Using keyboard, focus on the tree, and pick any tree item to focus
3. Press '*' key when focus is on a treeItem

Result: siblings of this tree item is expanded as expected. But the position of the focus did not move. Therefore the focus became another tree item.

For example in the gif below: `tree-item-6` is focused, and after '*' key is pressed, focus became `tree-item-0-5`:

![f5qgp9JDgg](https://user-images.githubusercontent.com/28751745/96147782-e8366a00-0f07-11eb-8049-3c57533814ca.gif)

#### Actual behavior:

When '*' key is used for expanding siblings on a tree item, focus is shifted to another tree item 

#### Expected behavior:

Focus should retain on the tree item after '*' was pressed.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Maybe :) if I finish my work now. But I'm willing to help whoever wants to

Requested priority: (Blocking, High, Normal, Low) Low

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@jurokapsiar FYI

**Comment by YuanboXue-Amber** [comment]
Addressed by PR #16080
