### ISSUE TITLE
Some labels in Northstar don't have the correct label color and text color

### ISSUE THREAD

**Issue by TaylorWebb** [microsoft/fluentui#15538]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar 0.51.0
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug:
1. Go to https://fluentsite.z22.web.core.windows.net/components/label/definition#variations-color to see where all the label colors are.
2. Change between light mode, dark mode, and high-constrast mode to see the text colors.

#### Actual behavior:
These would also be accessibility issues I guess. Depending on the label `color` and the theme, the text does not have the proper color. More specifically:

In light mode:
1. The text for `color="orange"` is invisible.
2. The text for `color="green"` does not have enough contrast.
3. The text for `color="yellow"` does not have enough contrast.
![image](https://user-images.githubusercontent.com/12616647/96209511-50646a80-0f5f-11eb-8e6c-14133b6767d2.png)

In dark mode:
1. The text for `color="brand"` white and the label color is lighter than it is in light mode.
2. The text for `color="orange"` is invisible.
3. The text for `color="green"` is invisible.
4. The text for `color="yellow"` does not have enough contrast.
![image](https://user-images.githubusercontent.com/12616647/96209548-6540fe00-0f5f-11eb-98d6-a167398d2b55.png)

In high-contrast mode:
1. The text for `color="orange"` is invisible.
2. The text for `color="green"` is invisible.
3. The text for `color="yellow"` is invisible.
4. The label colors are inconsistent, as some are white, one is yellow, and one is black.
![image](https://user-images.githubusercontent.com/12616647/96209559-6d993900-0f5f-11eb-8aa8-46a65028ed53.png)

#### Expected behavior:
In light mode:
1. The text for `color="orange"` should be visible.
2. The text for `color="green"` should have more contrast.
3. The text for `color="yellow"` should have more contrast.

In dark mode:
1. I thought the label and text color would match the color of a `primary` button. If the label color is to remain the same, then I guess the text color should be changed to black.
2. The text for `color="orange"` should be visible.
3. The text for `color="green"` should be visible.
4. The text for `color="yellow"` should have more contrast.

In high-contrast mode:
1. The text for `color="orange"` should be visible.
2. The text for `color="green"` should be visible.
3. The text for `color="yellow"` should be visible.
4. I'm not sure what the expected behavior _should_ be, but I'm guessing they shouldn't all be white and only one yellow and one black.

### Priorities and help requested:

Are you willing to submit a PR to fix? Not at the moment.

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@TaylorWebb Thanks for filing this issue!

@jurokapsiar FYI

**Comment by TanelVari** [comment]
resolved in https://github.com/microsoft/fluentui/pull/16160/
