### ISSUE TITLE
FocusTrapZone does not tab properly when using preact

### ISSUE THREAD

**Issue by taurheim** [microsoft/fluentui#15530]
### Environment Information

- **Package version(s)**: 7.107.0
- **Browser and OS versions**: Edge Dev, Windows 10

### Please provide a reproduction of the bug in a codepen:

https://924v8.csb.app/

Due to this requiring specific setup (using preact instead of react) I have reproed using CodeSandbox instead of CodePen

#### Actual behavior:

Pressing tab while focusing the last element in the modal keeps tab focus at the last item

#### Expected behavior:

Pressing tab while focusing the last element should focus the first tabbable element in the window

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: M365 in-app purchase (Dime)

**Comment by taurheim** [comment]
I did some digging and it seems related to the fact that preact does not bubble focus events (https://github.com/preactjs/preact/issues/1621). I am happy to submit a fix that would bring the FocusTrapZone onFocusCapture inline with onFocus which I believe would solve this.

**Comment by paulgildea** [comment]
@taurheim Thanks for filing the issue and proposing a fix!

@tomi-msft / @JustSlone - Please work coordinate with @taurheim to make sure they are able to get a PR going.

Thanks for contributing!

**Comment by JustSlone** [comment]
@taurheim can you share a description of the suggested fix (or maybe just want to draft up a PR to show the fix)? 

Happy to take a contribution here, we just need to be careful not to regress existing behaviors of FocusTrapZone.

**Comment by taurheim** [comment]
The primary issue is that with preact, onFocus does not bubble, which means that functionality between [onRootFocus](https://github.com/microsoft/fluentui/blob/1020e8c78a40a77d10c7f498731cf3f51f7c76b9/packages/react-internal/src/components/FocusTrapZone/FocusTrapZone.tsx#L166) does not get called, but [onRootFocusCapture](https://github.com/microsoft/fluentui/blob/1020e8c78a40a77d10c7f498731cf3f51f7c76b9/packages/react-internal/src/components/FocusTrapZone/FocusTrapZone.tsx#L193) does.

The root of the issue (I think) is that `internalState.hasFocus` gets set to true in `onRootFocus` but not in `onRootFocusCapture`.

This means that when [onBumperFocus](https://github.com/microsoft/fluentui/blob/1020e8c78a40a77d10c7f498731cf3f51f7c76b9/packages/react-internal/src/components/FocusTrapZone/FocusTrapZone.tsx#L148) gets (correctly) called when tab is pressed while focused on the last element in the zone, `isFirstBumper === internalState.hasFocus` resolves to `false === false`, so it keeps focus on the last element.

The fix I'd propose is just to add `internalState.hasFocus = true` to `onRootFocusCapture`, but I'm not sure if there could be regressions due to that?

**Comment by JustSlone** [comment]
@khmakoto can you weigh in on the proposed fix here? Looks like taurheim is willing to contribute a fix, I just want to make sure it's not likely to introduce regressions.

**Comment by khmakoto** [comment]
I think it seems like a harmless fix and I would be amazed if it caused regressions in our components. I think @dzearing would have a better idea about how it would impact partners using `FocuzTrapZone` however.
