### ISSUE TITLE
Multi Select Dropdown : On reset form or changing to initial values , NVDA/Narrator is reading the place holder text in multi select dropdown.

### ISSUE THREAD

**Issue by Sandhya-aluri** [microsoft/fluentui#15548]
### Environment Information

- **Package version(s)**:  "@fluentui/react": "^7.126.0",
- **Browser and OS versions**: Chrome , windows 10

#### Actual behavior:
On reset form or clearing the  values to initial values on button click, NVDA/Narrator is reading the place holder text in multi select dropdown.

#### Expected behavior:
On reset form or clearing the  values to initial values on button click, NVDA/Narrator should not read the place holder text in multi select dropdown.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@Sandhya-aluri Thanks for filing the issue. Can you provide a code repo of the issue so that we can determine if this is a recent regression.

@smhigley FYI

**Comment by Sandhya-aluri** [comment]
@paulgildea  Hi, the issue is we have a fabric dropdown which is multi select and a link button, on click of link button the selected value in dropdown is cleared. once it is cleared we have kept a message as "all fields cleared" , so NVDA screen reader while reading the message also reading the place holder of dropdown. 

Fluent UI component : Dropdown with multiselect true.
Fluent version : "@fluentui/react": "^7.126.0". 

Please find the sandbox link to repro the issue.
https://codesandbox.io/s/unruffled-jones-sqeeq?file=/src/MultiSelectExample.js

**Comment by paulgildea** [comment]
@Sandhya-aluri Awesome. Thanks for the link!

**Comment by Sandhya-aluri** [comment]
@paulgildea : hi paul , Also one more thing, not only on form/page reset even if multi select dropdown is reloading on any other control change/click , NVDA/Narrator is reading the place holder text in multi select dropdown.
