### ISSUE TITLE
Context menu loses focus after last item when navigating with keyboard

### ISSUE THREAD

**Issue by paperbackdragon** [microsoft/fluentui#15556]
### Environment Information

- **Package version(s)**: 7.145.0
- **Browser and OS versions**: Edge 86.0.622.43

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/heatherhb/pen/MWeyELm

#### Actual behavior:

After navigating through the contextual menu with Ctrl + Right Arrow, the menu loses focus and the next item in the DOM is focused on.

#### Expected behavior:

It would be better for accessibility for focus to stay in the menu and for Narrator to say "No next item" at the end of the menu instead.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OneDrive Web

**Comment by paulgildea** [comment]
@paperbackdragon Thanks for filing this issue.

@smhigley FYI

**Comment by paperbackdragon** [comment]
@paulgildea @smhigley - Would it be reasonable to fix this by changing the callout in `ContextualMenu.base.tsx` to be a `FocusTrapCallout`, or wrap the `Callout` in there with a `FocusTrapZone`?

**Comment by paulgildea** [comment]
@paperbackdragon Good question!

@tomi-msft / @joschect could you coordinate with @paperbackdragon on the best approach on how to address this issue?

@JustSlone FYI
