### ISSUE TITLE
add complex combo chart

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#15550]
we need to add the new chart which is 

complex combo chart

below is the figma
https://www.figma.com/file/BJaI0aMC0jXuwsJaGofqM7/Visualizations-(PS-%2B-CFR)?node-id=112%3A4903

This is nothing but adding lines in the vertical stacked bar chart

for more info please refer
https://office.visualstudio.com/OC/_queries/edit/4461315/

**Comment by paulgildea** [comment]
@Raghurk FYI
