### ISSUE TITLE
Menu opening from MenuButton has role="complementary" 

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#15552]
Repro steps:
1. Navigate to the https://fluentsite.z22.web.core.windows.net/components/menu-button/definition
2. open menu from the menuButton
3. Verify "role/s" on the elements parent/s of the menu
Expected: elements has no additional roles 
Actual: some element above the menu has role="complementary"

Comment:
this role coming from `popupBehavior`  
@jurokapsiar proposal was fix it in popupBehavior and apply the role only when `inline` prop is false
the same fix should be done as well for `aria-modal` attribute

![image](https://user-images.githubusercontent.com/22620150/96270379-d9b18680-0fcb-11eb-8592-da37f6cd1510.png)

**Comment by paulgildea** [comment]
@kolaps33 Thanks for filing the issue.

@jurokapsiar FYI
