### ISSUE TITLE
Add sort-by-dragging support to Pivot

### ISSUE THREAD

**Issue by izikl** [microsoft/fluentui#15559]
#### Describe the feature that you would like added

Add Pivot a built in support for sorting the tabs/PivotItems by dragging. 

#### What component or utility would this be added to

[Pivot](https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot) (I have also seen [React-Tabs](https://github.com/microsoft/fluentui/tree/261dea7a150115ce904768724cbeac80ded20382/packages/react-tabs), which sounds like the next version of Pivot) 

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

I have tried [react-sortable-hoc](https://clauderic.github.io/react-sortable-hoc/#/basic-configuration/horizontal?_k=vufhyf) but since, Pivot requires PivotItem as a direct child it doesn't work, since `react-sortable-hoc` is using a higher order component (`SortableElement`) to wrap the child items - PivotItem in this case. 

If Fluent UI can add a built-in support for dragging/sorting tabs that will be the best
Otherwise if Fluent UI can expose a renderer to the button component in PivotItem that allows wrapping it with `SortableElement` it will be just as good.

**Comment by paulgildea** [comment]
@izikl Thanks for reaching out.

I’ll mark this as a feature request and add it to our backlog, but to set expectations - we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. We'll take this into consideration when we converge the `Tab` component across our two React packages.

Let us know if you'd be interested in contributing this to the library as well!
