### ISSUE TITLE
Charting: Unit test cases to the charts.

### ISSUE THREAD

**Issue by jameelakowsar** [microsoft/fluentui#15577]
### Environment Information

- **Package version(s)**: All versions

#### Unit test cases need to be add for below charts
1. Stacked bar chart
2. Multi Stacked bar chart
3. Donut chart
4. Horizontal bar chart
5. Pie chart
6. Grouped vertical bar chart
7. Heat map

**Comment by paulgildea** [comment]
@Raghurk FYI

**Comment by jameelakowsar** [comment]
For above mentioned charts, basic level test cases and snapshot test cases added
