### ISSUE TITLE
Clear Picker Selections

### ISSUE THREAD

**Issue by PathToSharePoint** [microsoft/fluentui#15570]
#### Describe the feature that you would like added

I'd like to have the ability to programmatically clear selections in pickers. Currently I don't see a way to reset the picker:
`componentRef` only gives me access to the input, not the already selected items.
`selectedItems={[]}` allows me to clear the selection, but then the picker behaves as a controlled component.

My use case: I have cascading selections, and I need to reset the picker (child) whenever the value of the parent changes.

#### What component or utility would this be added to

All pickers, and in particular PeoplePicker.

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker
https://developer.microsoft.com/en-us/fluentui#/controls/web/pickers

**Comment by paulgildea** [comment]
@PathToSharePoint Thanks for filing this issue.

Is this something you'd be interested in contributing to the `Picker` component?

In the meantime, I’ll mark this as a feature request and add it to our backlog, but to set expectations - we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. We'll take this into consideration when we converge the `Picker` component across our two React packages.

@joschect If you have any workarounds you can think of in the short term.

**Comment by PathToSharePoint** [comment]
Thank you for the reply. I'll definitely take a look at the code but my TS/React skills might not be up to the task.

You say you are focused on coherence, is control clear/reset already implemented on some components? And do you have a specific terminology for that?
