### ISSUE TITLE
updated code syntax to make various modules less murky

### ISSUE THREAD

**Issue by velociwabbit** [microsoft/fluentui#15575]
#### Minimalist Code if only as documentation

It has been my personal experience that writing code minimally (the fewest syntax items as possible) can offer 10 fold quality and time to deliver improvements.  While i understand why an MS repo would look like C#  there still can be value in providing (if only as documentation) a minimalist version of the same code.

For example The Stylesheet.ts module is fairly simple once you understand it but really complex looking at first glance.  More importantly the clearer Stylesheet is, the easier it is to understand the overall css / merge styles architecture which i think is really cool (but hard to grok).

I just spent the last hour or so rewriting it minimally to make sure I was not missing anything.    (Below)
 
I dont want to debate the value of various code styles ... horses for courses... but clarity is always better if only as an aid.

If  users will find it worthwhile I will gladly copy other modules as I rewrite them.
```

import { IStyle } from './IStyle'

export const InjectionMode = { 
        none: 0 as 0,  
        insertNode: 1 as 1,  
        appendChild: 2 as 2,
}
export type InjectionMode =   typeof InjectionMode[keyof typeof InjectionMode]

export interface ICSPSettings {  nonce?: string;}

export interface IStyleSheetConfig  {  
        injectionMode?: InjectionMode;  
        defaultPrefix?: string;  
        rtl?: boolean;  
        namespace?: string;  
        cspSettings?: ICSPSettings; 
        onInsertRule?: (rule: string) => void;  
        classNameCache?: { [key: string]: string };
}
  
let _global: { [key: string]: any } = {} 

try {  _global = window; } catch {}

let _stylesheet: Stylesheet

export class Stylesheet {
  private _lastStyleElement?: HTMLStyleElement
  private _styleElement ?: HTMLStyleElement
  private _rules: string[] = []
  private _preservedRules: string[] = []
  private _config: IStyleSheetConfig
  private _rulesToInsert: string[] = []
  private _counter = 0
  private _keyToClassName: { [key: string]: string } = {}
  private _onResetCallbacks: (() => void)[] = []
  private _classNameToArgs: { [key: string]: { args: any; rules: string[] } } = {}


  public static getInstance = (): Stylesheet =>

    _stylesheet =  _global.__stylesheet__ = 
        ! _global.__stylesheet__   ||  (_global.__stylesheet__._lastStyleElement  &&  _global.__stylesheet__._lastStyleElement.ownerDocument !== document  )  
        ?   new Stylesheet( _global.FabricConfig  ?   _global.fabricConfig.mergeStyles : undefined ) 
        :   _global.__stylesheet__


  constructor(config?: IStyleSheetConfig) {

    this._config = {   injectionMode: InjectionMode.insertNode,   defaultPrefix: 'css',   namespace: undefined,    cspSettings: undefined,   ...config  }
    this._keyToClassName = this._config.classNameCache || {}
  }


  public cacheClassName = (className: string, key: string, args: IStyle[], rules: string[]): void =>   
 
        this._classNameToArgs[( this._keyToClassName[key] = className)   ] = {  args,  rules, } 


  public getClassName = (displayName?: string): string            => 

        `${this._config.namespace ? this._config.namespace + '-' : ''}${  ( displayName || this._config.defaultPrefix)  }-${this._counter++}`


  public setConfig = (config?: IStyleSheetConfig): void        => 

        this._config = {   ...this._config,   ...config,    } 


  public onReset = (callback: () => void): void => 

        this._onResetCallbacks.push(callback)

  public classNameFromKey = (key: string): string | undefined => 

        this._keyToClassName[key]

  public getClassNameCache = (): { [key: string]: string } => 

        this._keyToClassName


  public argsFromClassName = (className: string): IStyle[] | undefined => 

        this._classNameToArgs[className] && this._classNameToArgs[className].args


  public insertedRulesFromClassName = (className: string): string[] | undefined => 

        this._classNameToArgs[className] && this._classNameToArgs[className].rules


  public getRules = (includePreservedRules?: boolean): string => 

        includePreservedRules ? this._preservedRules.join('') : '') + this._rules.join('') + this._rulesToInsert.join('')


  public resetKeys = (): void => 

        this._keyToClassName = {}


  private _getStyleElement = (): HTMLStyleElement | undefined => 

        this._styleElement   =  this._styleElement || typeof document  === 'undefined'     
            ?  this._styleElement     :  ( typeof navigator === 'undefined' || ! /rv:11.0/.test(navigator.userAgent) ) 
            ?  undefined 
            :  this._createStyleElement()
 

  public insertRule = (rule: string, preserve?: boolean): void =>{

        const element = this._config.injectionMode !== InjectionMode.none ? this._getStyleElement() : undefined
        try { 
            preserve &&  this._preservedRules.push(rule) 
          ! element  &&  this._rules.push(rule)
            element  &&  this._config.injectionMode === 2 && element.appendChild(document.createTextNode(rule))
            element  &&  this._config.injectionMode === 1 && element.sheet && element.sheet.insertRule(rule, (element.sheet  as CSSStyleSheet).cssRules.length)  
            this._config.onInsertRule &&   this._config.onInsertRule(rule) 
        }catch(e){}
  }
 

  public reset = () => {

        this._rules = this._rulesToInsert = []
        this._counter = 0
        this._classNameToArgs =   this._keyToClassName = {}
        this._onResetCallbacks.forEach((callback: () => void) => callback())
  }
 

  private _createStyleElement(): HTMLStyleElement {

        const styleElement = document.createElement('style')
        styleElement.setAttribute('data-merge-styles', 'true')
        this._config.cspSettings  && this._config.cspSettings.nonce  && styleElement.setAttribute('nonce', cspSettings.nonce)
        document.head!.insertBefore(styleElement,  
                this._lastStyleElement 
                ?  this._lastStyleElement.nextElementSibling 
                :  document.head.querySelector('style[data-merge-styles]') || document.head.childNodes[0] ) 
        return  this._lastStyleElement = styleElement
   }
 
}

```

**Comment by paulgildea** [comment]
@velociwabbit Thanks for filing this issue.

Is this something you are looking to contribute to the library? If so, it might be interesting to see this as a PR to understand what the diff's are. Also interested to understand if there are any other benefits (bundle size, performance, etc.) of the proposed change. 

@dzearing / @JustSlone FYI - Not sure how to proceed here with understanding the cost/benefit/risk associated with "rewriting" a core module like `Stylesheet.`

**Comment by velociwabbit** [comment]
I would be more than willing to contribute to fluent... I have not yet debugged the stylesheet module (i just did it because i find reading typescript to be only slightly less tortuous than reading my own handwriting.  )  but over time if you are open to the idea i would gladly contribute my reductionist versions  to the code base.  

Re advantages... there are a number of them when coding this way.

1 - by ignoring lint rules and using spacing correctly you can line up assignment and other statements which provides many of the same benefits as typescript... in other words it provides guardrails for coders who invert letters  and phrases such as yours truly.   

Here is an example  from charts (slightly modified):
```

let circle = { 
    key :  circleId 
    id :  circleId 
    cx :  xScale(singlePoint.xVal) 
    cy :  yScale(singlePoint.values[1]) 
    r :  this.state.activeCircleId ::: circleId ? 8 : 0.01 
    stroke :  lineColor 
    strokeWidth :  3
    visibility :  this._getOpacityOfCircle(this._points[index].legend) 
    fill :  this._updateCircleFillColor(circleId, lineColor) 
    ref : (e: SVGCircleElement | null) :> 
        this._refCallback(e!, circleId);
    
    onMouseOver :  this._handleMouseHover.bind(this, xLineVal, singlePoint.xVal, circleId, xAxisCalloutData) 
    onMouseOut :  this._mouseOutAction 
    onFocus :  this._handleOnFocus.bind(this, xLineVal, singlePoint.xVal, circleId, xAxisCalloutData) 
    onBlur :  this._mouseOutAction 
    onClick : 
        this._onDataPointClick.bind(
            this,
            this._points[index].data[pointIndex].onDataPointClick!,
            circleId,
            lineColor,
    )
}
```


As opposed to this:
 ```

 let circle = {  r :  this.state.activeCircleId === circleId ? 8 : 0.01 
                id :  circleId 
                cx :  xScale(singlePoint.xVal) 
                cy :  yScale(singlePoint.values[1]) 
               ref :  (e: SVGCircleElement | null) => this._refCallback(e!, circleId); 
               key :  circleId 
              fill :  this._updateCircleFillColor(circleId, lineColor) 
            stroke :  lineColor 
            onBlur :  this._mouseOutAction 
           onFocus :  this._handleOnFocus.bind(this, xLineVal, singlePoint.xVal, circleId, xAxisCalloutData) 
           onClick :  this._onDataPointClick.bind(this,this._points[index].data[pointIndex].onDataPointClick!,circleId,lineColor )
        onMouseOut :  this._mouseOutAction 
        visibility :  this._getOpacityOfCircle(this._points[index].legend) 
       strokeWidth :  3
       onMouseOver :  this._handleMouseHover.bind(this, xLineVal, singlePoint.xVal, circleId, xAxisCalloutData) 
 }
```
I understand why linting is the way that it is but there is no other profession (and that includes being a 5th grader or above as a student) that would think that what appears to be sloppy formatting (the lint type that makes computer debugging slightly more convenient) is better than organized, well spaced and legible code.   ( This is one issue that confounds me to no end)
 

1.b Another advantage of lining up code  is that it affords the user the ability to recognize patterns in the code that are similar which makes understanding the code much easier. 

2 - From a performance perspective the code size is much smaller and most of the time the path length is shorter (although not always)

3 - From a maintenance perspective  this is the really cool part... I can look at my code from 5 years ago and just by the shape of the code on the paper I can figure out what is going on...  removing extra stuff and spacing things to look line  powerpoint (ish)   layouts affords the coder with the ability to learn visually (as opposed to by reading the comments etc)  in order to understand what the code is doing.

**Comment by velociwabbit** [comment]
I will take closed with no comment as an acknowledgement that what i am saying makes sense but not actionable given the current coding culture and the desire to convert the world to typescript :)

**Comment by JustSlone** [comment]
@velociwabbit yeah, thanks for the input, but it's not really actionable, especially in a large codebase with many contributors. We use prettier for formatting for the very reason that it's very difficult to agree on formatting preferences between a large number of engineers. What makes great sense to one person, doesn't make sense to another. Prettier solves this by being a "good enough" solution that gets applied automatically. Which has the effect of ending a lot of largely unnecessary discussions (or arguments) about code formatting. 

Cheers!

**Comment by velociwabbit** [comment]
While i am a big believer in open source, and the wisdom of the crowd... sometimes the crowd sinks to the lowest common denominator.... and i fear that in this circumstance 5th grade teachers are correct and we all should have to write on the chalk boards "I will make my code legible" 500 times (a la bart simpson)
