### ISSUE TITLE
Improvment for react-hook `useBoolean`

### ISSUE THREAD

**Issue by FuJuntao** [microsoft/fluentui#15582]
https://github.com/microsoft/fluentui/blob/3346b09e82b41f6b5b96fe1a94c8d122b3a4625b/packages/react-hooks/src/useBoolean.ts#L21-L38

We have a ref to store the boolean value, but what if we write it this way :

```js
export function useBoolean(initialState: boolean): [boolean, IUseBooleanCallbacks] {
  const [value, setValue] = React.useState(initialState);

  const setTrue = useConst(() => () => {
    setValue(true);
  });
  const setFalse = useConst(() => () => {
    setValue(false);
  });
  const toggle = useConst(() => () => {
    setValue((value) => !value)
  });

  return [value, { setTrue, setFalse, toggle }];
}
```

It ensures `toggle` has a constant reference, and without having to store boolean value in a ref.

**Comment by paulgildea** [comment]
@FuJuntao Thanks for filing this. Is this something you'd be willing to contribute?

@tomi-msft - Coordinate with @FuJuntao if this is something they want to spin up a PR for.

**Comment by paulgildea** [comment]
@JustSlone / @dzearing FYI

**Comment by dzearing** [comment]
This is a simple improvement, feel free to submit a PR. 

Minor thought, but just my 2c. I would love if the `toggle` function output took an optional argument to force it to a value. Call toggle with no arguments to toggle, or toggle(true) to force it to a state. That way we don't have to fumble with multiple functions.

**Comment by FuJuntao** [comment]
Thank you all for the replies, a PR is coming right away

**Comment by FuJuntao** [comment]
I have submitted the PR (#15607), but it seems that I'm not allowed to link it with this issue.

Anyway, it's ready for some reviews 💖
