### ISSUE TITLE
VerticalBarChart styles not working

### ISSUE THREAD

**Issue by RafikAlhallak** [microsoft/fluentui#15580]
hello i use your example code on
   http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/12384/merge/charting/dist/index.html#/examples/verticalbarchart

but the styles are not working like:
   xAxisText: {
                    transform: 'rotateZ(-40deg)',
                    textAnchor: 'end',
                    ...tTextStyle,
                  },

my completed code is:

       private renderBarChart = (): JSX.Element | undefined => {
        if (this.props.chartData == null)
            return undefined;

            let tTheme = getTheme();
            const tPoints: IDataPoint[] = this.props.chartData?.map((pItem) => { return { x: pItem.key, y: pItem.count } as IDataPoint });

            const tAxisStyle = {
                stroke: tTheme.palette.orange,
              };
              
              const tTextStyle = {
                fill:  tTheme.palette.orangeLight,
                fontSize: '12px',
              };

              const tCustomStyles = () => {
                return {
                  chart: {
                    paddingBottom: '45px',
                  },
                  chartLabel: {
                    color:  tTheme.palette.orange,
                    ...DefaultFontStyles.large,
                  },
                  xAxisDomain: tAxisStyle,
                  xAxisTicks: tAxisStyle,
                  xAxisText: {
                    transform: 'rotateZ(-40deg)',
                    textAnchor: 'end',
                    ...tTextStyle,
                  },
                  yAxisDomain: tAxisStyle,
                  yAxisTicks: tAxisStyle,
                  yAxisText: tAxisStyle
                };
              };

        const tElement =
            <VerticalBarChart
            data={tPoints}
            width={800}
            height={400}
            barWidth={10}
            yAxisTickCount={10}
            styles={tCustomStyles}
            legendProps={{ legends: [] }}
            />;

        return tElement;
    }

**Comment by paulgildea** [comment]
@RafikAlhallak Thanks for filing this issue!

@Raghurk FYI
