### ISSUE TITLE
IE11 polyfill should recommend conditionally loading the script

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#15591]
Currently the IE11 polyfill package recommends in the README to import the script. This will add the content to the bundle for every browser, which is an unnecessary performance penalty.

We need to address these things:

1. Produce a bundle (get webpack config, edit package.json to add bundle script, run `yarn bundle`)
2. Update README to recommend the conditional load, not the import.
3. Figure out how to get the script to the CDN (talk with Elizabeth) and update README to point to that location.

**Comment by layershifter** [comment]
@dzearing as I know we decided to not use that polyfill. Can be this issue closed?
