### ISSUE TITLE
Animation not working in Pivot control

### ISSUE THREAD

**Issue by bhanuchintha** [microsoft/fluentui#15608]
Hello Team,

I see that the hover animation is not working in Pivot control for all of the styles - Default Pivot/Links of tab style etc..

You can also experience this when you go for show code and see the animation on hover when clicking on other tabs -

https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot

Can you please let us know if this a known issue that you are working on - If so, when can we expect the fix.

Thanks & Regards,
Bhanu
![Pivot Animation Issue](https://user-images.githubusercontent.com/19674673/96545813-bc7c0100-12c6-11eb-9c30-a1bb11c939f3.JPG)

**Comment by paulgildea** [comment]
@bhanuchintha Thanks for filing this issue!
