### ISSUE TITLE
Pressing up/down in the dropdown menu triggers onChange before Enter

### ISSUE THREAD

**Issue by shuotli** [microsoft/fluentui#15604]
### Describe the issue:

Pressing up and down on the dropdown menu triggers the `onChange` callback before pressing Enter. If one of the options triggers a Callout, the user will see the Callout shown immediately after navigating to that option without pressing Enter.

#### Actual behavior:

`onChange` is triggered before pressing Enter.

#### Expected behavior:

`onChange` is triggered after pressing Enter.

**Comment by paulgildea** [comment]
@shuotli Thanks for the issue. Could you please provide a link to an isolated codepen so that I we can determine if this is a recent regression or by design?

Thanks!
