### ISSUE TITLE
Cursor navigation is not working in Chrome

### ISSUE THREAD

**Issue by james-bond-021719** [microsoft/fluentui#15610]
I’ve created PCF control and used Fluent UI components, particularly the DetailList and Textfield, see below screenshot.
![image](https://user-images.githubusercontent.com/61274359/96587429-e65c1480-1314-11eb-8bc9-8f5755f5f5f8.png)
However, the cursor navigation to go to the next cell, specifically the right arrow key, to move on the next cell/input element does NOT work in Chrome.
**NOTE**
- Left arrow key, to move from cell/input element from right to left, is working.

- Both left and right cursor arrows are working using IE/Edge browser.

Any thoughts on how we can make the cursor navigation to work in Chrome?
[office-ui-fabric][fluentui-react]

**Comment by paulgildea** [comment]
@james-bond-021719 Thanks for filing an issue.

This might be a question better suited for the StackOverflow community. As it sounds like you've build a more custom component. So I'm going to mark this issue this way.

However, if you've found an isolated issue specifically with the DetailsList and keyboarding please feel free to update this issue with an isolated codepen demonstrating the issue would be super helpful!

Thanks!
