### ISSUE TITLE
CommandBar split sub buttons are not keyboard accessible

### ISSUE THREAD

**Issue by shuotli** [microsoft/fluentui#15638]
Actual Behavior
Focus is on the whole button.

Expected Behavior
Focus should be on each of the sub buttons.

Repro:
https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar

Repro Step:
Visit above link, reach to Command bar fourth category, **CommandBar with split and disabled buttons**
. Now press tab and navigate to the first example, focus is on the whole button instead of either sub buttons.

The users cannot use the keyboard to access the sub buttons. This can be an issue when the sub buttons have different functions.

**Comment by paulgildea** [comment]
@shuotli Thanks for the feedback!

**Comment by tomi-msft** [comment]
Hi @shuotli thanks for filing the issue. We have decided that SplitButton is only one-tabbable, so the component is working as expected in this regard. I believe you can use alt + down arrow to open the dropdown.
