### ISSUE TITLE
Dropdown - single select search does not display defaultValue text in input

### ISSUE THREAD

**Issue by JamyDev** [microsoft/fluentui#15630]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.51.2
- **Browser and OS versions**: N/A (New Edge 86, Windows 10 19042)

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluentui-northstar-dropdown-single-default-x2c95?file=/example.js

#### Actual behavior:

A Dropdown, set to search with a `defaultValue` set, does not set the input text to the specified value, but does indicate that a value has been selected. This only happens for single selection, multiselect properly renders the selected items.

#### Expected behavior:

The input text field has the `defaultValue` header text, just like it would when selected manually. (See codesandbox for more details)

### Priorities and help requested:

Are you willing to submit a PR to fix? Depending on time commitment, yes.

Requested priority: Low, found a workaround by setting `defaultSearchQuery` to this value as well.

Products/sites affected: N/A, workaround found

**Comment by paulgildea** [comment]
@JamyDev Thanks for the issue!

@jurokapsiar FYI
