### ISSUE TITLE
Split Button  - outline overflow

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#15641]
Environment:
https://fluentsite.z22.web.core.windows.net/components/split-button/definition
production version of 0.51.2

Component:
SplitButton 

Steps:
- navigate to the split button with TAB 

Expected: outline is around the splitButton
Actual: outline overflow the splitButton and width is for the whole container
Please see screenshot: 

![image](https://user-images.githubusercontent.com/22620150/96898121-a66d6c80-148f-11eb-8262-0f627e042583.png)

**Comment by paulgildea** [comment]
@kolaps33 Thanks!

@jurokapsiar FYI
