### ISSUE TITLE
DatePicker: fix screener tests for hovering days in RTL

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#15657]
When working on exporting the date-time DatePicker from `@fluentui/react` in #15644 we hit screener failures for all tests involving hovering over days in RTL (the hover styling doesn't show up in the screener state).

If you try [this demo](https://codepen.io/ecraig12345/pen/VwjmOwv?editors=0010) which uses RTL (the extra props are to make it more like the screener setup), hover styling of days works fine. So it seems to be a screener-specific issue. It's also specific to RTL (hovering days in LTR was fine).

My guess is that this may have to do with CalendarDayGrid's reliance on mouseIn events to add a class and apply hover styling (rather than applying it normally based on `:hover`), so maybe in RTL screener doesn't simulate this properly?

**Comment by paulgildea** [comment]
@ecraig12345 Thanks for capturing this one too.

@lorejoh12 FYI
