### ISSUE TITLE
Calendar/DatePicker "Go to today" padding

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#15651]
The date-time version of Calendar/DatePicker has less bottom padding around the "Go to today" button compared to the old OUFR version. The left/right padding may also be a tiny bit different. Not a functionality issue but it doesn't look so great. (I found this while looking at screener results for #15644.) cc @lorejoh12 

Compare the first [DatePicker example from OUFR](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/7.0/fabric-website-resources/dist/index.html#/examples/datepicker):
![image](https://user-images.githubusercontent.com/5864305/96929419-f12abc80-146e-11eb-98fa-6edd88760f29.png)

With the first [DatePicker example from date-time](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/date-time/demo/index.html#/examples/datepicker)
![image](https://user-images.githubusercontent.com/5864305/96929404-ebcd7200-146e-11eb-9f22-231b07ee4036.png)

**Comment by paulgildea** [comment]
@ecraig12345 Thanks for finding this! 

Is this something that recently changed or is there another root cause that adjusted the padding on other components as well?
