### ISSUE TITLE
Expand fluentui web-components components availability

### ISSUE THREAD

**Issue by MeikTranel** [microsoft/fluentui#15669]
#### Describe the feature that you would like added

Currently only very few of the controls/components listed in the web section of the fluentui site, are actually available as web components. For those of us who have to realize that adding react to our current stack would probably push us over into framework hell web components looks to be the standardized way out of this scenario.

#### What component or utility would this be added to

Priority for me would be navigational components because they help most in establishing the fluent design language besides the basic controls already available as well the availability of the theme constants themselves.

- [ ] Pivot
- [ ] Breadcrumb
- [ ] CommandBar

Other:
- [ ] Dropdown (this one is actually dearly missed - we ended up implementing an MVP ourselves)
- [ ] ChoiceGroup

**Comment by paulgildea** [comment]
@MeikTranel Thanks for filing this issue and your preference in priority.

@chrisdholt as FYI.

I don't have any timelines to share at the moment, but our teams are working together to provide a consistent control offering across our various web control libraries. 

Thanks for the feedback and please do keep checking back with the project as we progress!

**Comment by chrisdholt** [comment]
Thanks @paulgildea - @MeikTranel gave me a heads up and I'll take a look, triage, and respond.

**Comment by sonntag-philipp** [comment]
Are there any updates on this?

**Comment by chrisdholt** [comment]
> Are there any updates on this?

There are some naming differences as well as differences in implementation, but we do have some coverage here from a primitive component standpoint:

[x] Pivot - *See "tabs"*
[x] Breadcrumb
[ ] CommandBar - Dependent on "toolbar" (https://github.com/microsoft/fast/blob/master/specs/toolbar.md)

[x] Dropdown - *See "select". Initial work for a basic select is complete and work on a robust combobox is underway.*
[x] ChoiceGroup - *See Radio + RadioGroup*

Examples here: https://codesandbox.io/s/fluent-examples-forked-kktg2?file=/index.html

**Comment by timker** [comment]
it would be great to have a list
like they have in mwc components:

https://github.com/material-components/material-components-web-components
