### ISSUE TITLE
Update to React 17

### ISSUE THREAD

**Issue by rizkyramadhan** [microsoft/fluentui#15685]
Since react 17 has released, it will be nice if @fluentui/react upgraded to react 17.

**Comment by paulgildea** [comment]
@rizkyramadhan Thanks for the suggestion!

Currently, we are planning to scout out our beta release to make sure it's functional with React 17, but we don't have any plans that would require that React 17 would be the minimum version needed for the library.

You can check out our [Quarterly OKRs](https://github.com/microsoft/fluentui/wiki/Fluent-UI-Objectives) for more clarity on what the team is focused on in the current quarter and for any future plans we have for the project.

Thanks!

@JustSlone FYI and if you wanted to add anything

**Comment by JustSlone** [comment]
Bot is so grumpy sometimes. 

We haven't done extensive tests of React 17, but we will officially support it with the upcoming Version 8 release of @fluentui/react, things should just work, 17 has very few breaks in it. If you hit any issues feel free to file them.

**Comment by rizkyramadhan** [comment]
Yes, I have been using fluent v8 for a while. One thing that I would like to suggest is to upgrade react dependencies to 17 instead of > 16 & < 17.

That would silence yarn complaining about react version mismatch.
