### ISSUE TITLE
In your default example, Dialog ejects narrator from current browser window

### ISSUE THREAD

**Issue by chuanqisun** [microsoft/fluentui#15698]
### Environment Information

- **Package version(s)**: @7.148.0
- **Browser and OS versions**: Edge 86.0.622.51 on PC
![image](https://user-images.githubusercontent.com/1895289/97222960-58f14800-178c-11eb-84b3-fe6e4e0d1e98.png)

### Describe the issue:

After opening the dialog with Narrator (controlled by keyboard), narrator first reads the content of the dialog, then reads the content from other windows that are currently open on your desktop. The browser loses focus.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/chuanqisun/pen/OJXpaRv (exported your web site example without any modification)

Ctrl + win + enter to start narrator
Use tab to cycle focus onto the "Open Dialog" button
Hit enter, listen, and observe the blue focus ring

#### Actual behavior:

![repro](https://user-images.githubusercontent.com/1895289/97220115-36f5c680-1788-11eb-971b-e15fea0d1450.gif)

After announcing the content, narrator went ahead and focused on the previously focused window.

#### Expected behavior:

The dialog should trap focus

### Documentation describing expected behavior

Try this dialog. It successfully traps focus with the same browser + screen reader pairing.
https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html

**Comment by paulgildea** [comment]
@chuanqisun Thanks for the issue and the awesome screen capture. That's really helpful for the team!

@smhigley FYI on the model

**Comment by SFM61319** [comment]
@chuanqisun not really related to this issue but what software did you use to create that gif? I wanted to open an issue in which i wanted to paste a gif of my screen but i didnt know what software to use...

**Comment by chuanqisun** [comment]
@SFM61319, check out [ScreenToGif](https://www.screentogif.com/)

**Comment by SFM61319** [comment]
Thank you!
