### ISSUE TITLE
Calling StopPropagation() during onDismiss() in IContextualMenuProps doesn't stop the propagation

### ISSUE THREAD

**Issue by MediocreRyan** [microsoft/fluentui#15690]
### Environment Information

- **Package version(s)**: (7.132.0)
- **Browser and OS versions**: (Windows 10 enterprise 19042.572 , google chrome 86.0.4240.75  )

### Please provide a reproduction of the bug in a codepen:
reproducing whole thing will be difficult since it involves multiple components.
Although I have just written how I am using the CommandButton and IContextualMenu component as an example:
https://codepen.io/MediocreRyan/pen/qBNrWBG?editors=1112 (Sorry, it is not very helpful, but I am just showing the usage)

#### Actual behavior:

Component hierarchy : 
OuterComponent
  CommandButton
    IContextualMenuProps

I have a CommandButton component inside another component that closes on pressing escape as default and excepted behavior.
When the contextualMenu is opened through CommandButton and is focussed, the escape should close only the menu and should spare theouter component( as requirement).
To do this, I am using 'onDismiss' prop (part of IContextualMenuProps), where IContextualMenuProps is used as 'menuProp'
inside CommandButton(check codepen) and calling event.StopPropagation() inside it.
But the propagation is still happening and it is closing the outer component as well.

Debugger is hitting that event.StopPropagation() but it doesn't work.

When I press 'Alt', it works properly(closing only the menu and not the outer component).

I am also using event.PreventDefault() to just check whether it works or not, it works for Alt but not for escape.

More findings: For Alt button, the call comes through ContextualMenu.Base.Tsx.KeyHandler() which calls event.stopPropagation() while for escape the call comes through CallOutComponent.Base.Tsx._dismissOnLostFocus() which doesn't call stopPropagation()

Let me know if 'onDismiss' is the correct prop to use for this requirement or there is another way to sopPropagation for escape press.

#### Expected behavior:

When menu is opened and focus is on menu, escape should only close the menu and not the OuterComponent, just like Alt.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (High)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@MediocreRyan Thanks for the detailed investigation and filing this issue.

@tomi-msft Try to see if you can get a repro going for the issue, sounds like this one might be a complex on. Adding @joschect for any insight on `CommandBar` and `ContextMenu`

**Comment by joschect** [comment]
@MediocreRyan Sorry you're experiencing some problems! I modified the [codepen](https://codepen.io/slimemold/pen/RwRpBoL?editors=0011) you sent and do not quite see the behavior that you're talkinig about. I created an outer div that listens to keyPress as well and it actually doesn't seem to get hit at all since the contextualmenu is not directly part of the component dom hierarchy it won't receive the keypress event. How is your outer component listening to the keydown event?

**Comment by MediocreRyan** [comment]
Hello @joschect  : you are right. your codepen example surely proved that its escape was working fine. 
Unfortunately my outer component resides in some other repo, but probably it is listening to all the escape event, even if the propagation is stopped and closing itself. And it couldn't be the case for Alt, which created confusion in mind.

Sorry for the inconvenience caused. Let me know if I can go ahead and close the issue.
