### ISSUE TITLE
Northstar's Dropdown does not truncate on overflow

### ISSUE THREAD

**Issue by davyrwoo** [microsoft/fluentui#15719]
Dropdown has rendering bugs on both the Dropdown and DropdownItems components when used as a multiple selection Dropdown (`multiple` prop) with the `inline` or `fluid` props in a container (e.g. Flex) that is shorter than the selected item.

### Environment Information

- **Package version(s)**: 0.51.2

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/thirsty-currying-f7sc4

1. Select any item in the Dropdown selection
2. Continue to select items in the Dropdown
![Dropdown bug](https://user-images.githubusercontent.com/56053686/97340922-9fed4500-1841-11eb-9d3a-db01c6bdce13.PNG)

#### Actual behavior:

- DropdownItem's text overflows around the bounds of the item
- Dropdown continues to grow vertically as more items are selected

#### Expected behavior:

- Overflowing DropdownItems get horizontally truncated within the dropdown (like how fixed width Input fields behave with overflowing text), and users can arrow navigate to shift focus to items that aren't currently visible.

**Comment by paulgildea** [comment]
@davyrwoo Thanks for filing this issue!

@jurokapsiar FYI

**Comment by davyrwoo** [comment]
@assuncaocharles does also address the issue where the Dropdown continues to grow vertically as more items are selected? If not, should I create another ticket, or should this be reopened? Thanks!

**Comment by assuncaocharles** [comment]
Hi @davyrwoo 

I am not sure if that is a bug, `Dropdown` has a `max-height` specified and it will grow to max till reach it, what would you expect?

**Comment by davyrwoo** [comment]
@assuncaocharles the current behavior of the `Dropdown `is that it grows past the specified `max-height` as you add items. The desired behavior I'm thinking of is similar to how overflow in `Input` fields works.

**Comment by assuncaocharles** [comment]
> @assuncaocharles the current behavior of the `Dropdown `is that it grows past the specified `max-height` as you add items (for example, if you make `max-height: '32px'` ) . The desired behavior I'm thinking of is similar to how overflow in `Input` fields works.

In your example dropdown is correctly growing to the max-height of `selectedItemsMaxHeight` variable ( 82px ). 

<img width="477" alt="Screen Shot 2020-11-24 at 7 30 18" src="https://user-images.githubusercontent.com/8545105/100082462-06f12000-2e27-11eb-9ba4-a4bcb08b4b1b.png">


In this case it would be just a matter of changing the variable value

**Comment by davyrwoo** [comment]
@assuncaocharles if the `selectedItemsMaxHeight` is less than `82px`, it seems like the dropdown grows to be too large. I've added that variable value to `32px` in my example.

**Comment by assuncaocharles** [comment]
> @assuncaocharles if the `selectedItemsMaxHeight` is less than `82px`, it seems like the dropdown grows to be too large. I've added that variable value to `32px` in my example.

@davyrwoo Setting the variable to `32px` I am getting max height of `32px` as you can see here: https://codesandbox.io/s/quirky-https-x8711?file=/example.js

<img width="337" alt="Screen Shot 2020-11-30 at 22 44 29" src="https://user-images.githubusercontent.com/8545105/100686746-bb2a0380-335d-11eb-97fb-2c009f6c1839.png">
