### ISSUE TITLE
FocusTrapZone not retaining focus within itself in Android Chrome browsers while using Talkback

### ISSUE THREAD

**Issue by nairmanu** [microsoft/fluentui#15726]
### Environment Information

- **Package version(s)**: 7.129.0
- **Browser and OS versions**: Android OS 11, Pixel 2/Chrome Browser 86.0.4240.110

### Describe the issue:
FocusTrapZone is not trapping the focus within itself Android Chrome browsers while using Talkback. I'm able to navigate to elements outside of the FocusTrapZone.

#### Actual behavior:

Focus is moving to elements outside of FocusTrapZone.

#### Expected behavior:

Focus should remain within elements inside of FocusTrapZone.

### Documentation describing expected behavior
https://developer.microsoft.com/en-us/fluentui#/controls/web/focustrapzone

**Comment by paulgildea** [comment]
@nairmanu Thanks for filing this issue!

@smhigley FYI

@khmakoto This sounds familiar... But is specific to Android, let @tomi-msft know if you've addressed this issue before.
