### ISSUE TITLE
fluent ui input with canRevealPassword will trigger post if it's in a form

### ISSUE THREAD

**Issue by msmenti** [microsoft/fluentui#15729]
### Environment Information

- **Package version(s)**: (7.147.1)
- **Browser and OS versions**: (win 10)

#### Actual behavior:

when input control is used in a form, the 'eye ball' to reveal password, which is turned on by adding canRevealPassword, will listen to the submit event of the form and trigger post

#### Expected behavior:

'eye ball' will not listen to submit event.

### Priorities and help requested: medium, I can walk around using keypress event

Are you willing to submit a PR to fix? (Yes, No) Yes, if guidance is provided

Requested priority: (Blocking, High, Normal, Low) normal

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@msmenti Thanks for the issue. Can you provide a codepen replicating the issue? Also thank you for offering to submit a PR!

@tomi-msft See if you can repo the issue with the website, try to determine the root cause, and coordinate with @msmenti on getting a PR together.

Thanks!

**Comment by msmenti** [comment]
Thanks Paul, Tomi, here is the pen: https://codepen.io/sdusttm/pen/ExyEYdV 
to repro, type anything in input, hit enter, it will do a form post.

Thanks,
Meng

**Comment by zemirco** [comment]
Great issue! I've got the same problem. Luckily it's an easy fix. The button `type` isn't set and therefore defaults to `submit`.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

> The button submits the form data to the server. This is the default if the attribute is not specified for buttons associated with a form, or if the attribute is an empty or invalid value.

If you set the `type` to `button` it will work.

![Screenshot 2020-11-16 094836](https://user-images.githubusercontent.com/1132354/99233629-c9bbdb00-27f3-11eb-828e-44e2135a29aa.png)

**Comment by msmenti** [comment]
Great! thank you for the quick fix!

**Comment by mohdmusthafa** [comment]
Hi, When will this be available on the stable version, is this issue will be fixed in version 8

**Comment by ecraig12345** [comment]
@mohamedmansour I just made a PR #16294 cherry-picking the fix to version 7 since it's a pretty bad issue.
