### ISSUE TITLE
[Callout] On dismiss narrators reads redundant "Main Region" in the main example page

### ISSUE THREAD

**Issue by chtoosha** [microsoft/fluentui#15735]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Chrome, Edge

### Describe the issue:

Screen reader ( NVDA, JAWS win Narrator) reads  redundant "main region" once the user dismisses the callout 

### Please provide a reproduction of the issue in a codepen:
The issue repros in the main page ( but not in the code pen) the https://developer.microsoft.com/en-us/fluentui#/controls/web/callout but does not repros ib the codepen examples

#### Actual behavior:
Narrators( JAWS, NVDA, NArrator) read "Main Region Button." once callout is dismissed

#### Expected behavior:
Narrator should not read "Main Region"

**Comment by paulgildea** [comment]
@chtoosha Thanks for filing the issue.

@tomi-msft Can you determine if this is an issue with the sample or the `Callout` component since it doesn't repo in other examples.

**Comment by tomi-msft** [comment]
Hi @chtoosha, I'm having trouble reproing this issue. Can you provide more details on how to repro it?

**Comment by chtoosha** [comment]
sure. 
Issue does not repo in code pen, it repros strate in the example page: https://developer.microsoft.com/en-us/fluentui#/controls/web/callout

To repro it:
- open https://developer.microsoft.com/en-us/fluentui#/controls/web/callout 
- start your JAWS narrator and navigate to the fist example
- click button, observe the callout dialog and dismiss it
- listen to what narrator reads.
