### ISSUE TITLE
missing semantic color for menuItemTextPressed

### ISSUE THREAD

**Issue by Link631** [microsoft/fluentui#15734]
Given is following button with menuProps:

` <DefaultButton
        text="Click for ContextualMenu"
        menuProps={{
          items: [
            {
              key: "1",
              text: "menu 1"
            },
            {
              key: "2",
              text: "menu 2",
              subMenuProps: {
                items: [
                  {
                    key: "2.1",
                    text: "menu 2.1"
                  },
                  {
                    key: "2.2",
                    text: "menu 2.2"
                  }
                ]
              }
            },
            {
              key: "3",
              text: "menu 3"
            }
          ]
        }}
      />`

and a theme as followed:

`
{
   "semanticColors": {
      "menuItemBackgroundHovered": "#0272a3",
      "menuItemBackgroundPressed": "#0272a3",
            "menuItemTextHovered": "white"
     
   }
}
`
When clicking the button for the contextual menu, then all menus have a blue background with white text.

When i expand the menu 2 and move with mouse over menu 2.1 then I want that the textcolor of menu 2 stays white.

Steps to fix:
Introduce and support the missing property menuItemTextPressed in the same way as you did with menuItemBackgroundPressed.

**Comment by Link631** [comment]
In addition you could also move some textColors, which are still in ISemanticColors instead of ISemanticTextColors to ISemanticTextColors, or you move all ISemanticTextColors to ISemanticColors, which could also make sense.

The Interface ISemanticColors exports all colors, no matter where they are defined. On the other hand you also do not have an ISemanticBackgroundColor Interface...

This move should not be a breaking change, but you would need to update some documentation.

regards....

**Comment by Link631** [comment]
while trying to understand this Issue I found out, that:

` rootExpanded: {
        backgroundColor: ContextualMenuItemBackgroundSelectedColor,
        color: semanticColors.bodyTextChecked,....`

and:

` rootPressed: {
        backgroundColor: ContextualMenuItemBackgroundSelectedColor,
        selectors: {
          '.ms-ContextualMenu-icon': {
            color: palette.themeDark,
          },
          '.ms-ContextualMenu-submenuIcon': {
            color: palette.neutralPrimary,
          },
        },`


I am about to change it like so:


` 
...

const ContextualMenuItemBackgroundSelectedColor = semanticColors.menuItemBackgroundPressed;
const ContextualMenuItemTextSelectedColor = semanticColors.menuItemTextPressed;
...


rootPressed: {
        backgroundColor: ContextualMenuItemBackgroundSelectedColor,
        selectors: {
          '.ms-ContextualMenu-icon': {
            color: ContextualMenuItemTextSelectedColor,
          },
          '.ms-ContextualMenu-submenuIcon': {
            color: ContextualMenuItemTextSelectedColor,
          },
        },
        ...getItemHighContrastStyles(),
      },
      rootExpanded: {
        backgroundColor: ContextualMenuItemBackgroundSelectedColor,
        color: ContextualMenuItemTextSelectedColor,
        ...getItemHighContrastStyles(),
      },`

In my opinion it would make more sense. But I am not sure, why you did set it to bodyTextChecked? 
And due to the fact, that the color will only be taken from the Palette it is obvious now that the Palette will define the pressed color and not the semantic slot.

For the consumer this could be a breaking change, because the theme may suddenly behave different. 

What about first checking, if the palette Value was given, then use the palette value and otherwhise use the semantic slot?
But I asume, that default values are always set so this might not be possible.


Any suggestions how to deal with that?

Thanks

**Comment by Link631** [comment]
current checkins are buggy, because the test shows this:

 &:active:hover {
                            background-color: #edebe9;
    -                       color: #323130;
    +                       color: #edebe9;
                            text-decoration: none;

Background-color and color may never be equal :-)... 

But some advices how to handle it in general would be nice.

**Comment by paulgildea** [comment]
@Link631 Thanks for the filing this issue.

@tomi-msft can you work with @Link631 if they are interested in submitting a PR to make this update.

@dzearing FYI because it deals with `SemanticColors`

**Comment by Link631** [comment]
I have moved the variables with textColor to the text color interface, added the missing one... but i guess i still have missed to adjust some places, because for now in default theme loading, background and font color are the same. Thats where I could need some support. I did not have time to find out where this comes from.

You can see it in the snapshot result, which is defently wrong:-)

Maybe I will find some time later to investigate a bit more...

My goal would be to have all semantic textColors covered equivalent to semanticBackgrounds...
