### ISSUE TITLE
Test against React 17

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#15732]
Our minimum supported React version for `@fluentui/react` 8 will remain at 16.8, but we should also investigate adding `|| ^17.0.0` to our peer dependency range.

**Comment by ecraig12345** [comment]
@xugao started testing this out in #15796 but we ran into some test issues due to lack of React 17 support in Enzyme (https://github.com/enzymejs/enzyme/issues/2429). So this is on hold (hopefully not for too long) until we can actually run our tests. There were also some concerning initial perf results.

**Comment by xugao** [comment]
Quick update:
For unit test, I tried updating the code to use `@wojtekmaj/enzyme-adapter-react-17`. some tests need to wrap `act` when `unmount` to pass; some tests failed which appeared to be `focus` is not working on native element, which i have not root caused yet. See [commit](https://github.com/microsoft/fluentui/pull/15796/commits/7df6cdae53695ae67f4f562d04096b6b7883c55e).

**Comment by trueadm** [comment]
>  some tests failed which appeared to be `focus` is not working on native element, which i have not root caused yet. 

You'll likely need to use `focusin` rather than `focus`. You'll also need to use `focusout` rather than `blur`. This is because React now uses these native events under the hood.

**Comment by ecraig12345** [comment]
> > some tests failed which appeared to be `focus` is not working on native element, which i have not root caused yet.
> 
> You'll likely need to use `focusin` rather than `focus`. You'll also need to use `focusout` rather than `blur`. This is because React now uses these native events under the hood.

@trueadm Do you mean in tests, or in real code? I think the tests in question are calling `focus()` on a native element, not listening for events.

**Comment by MwSpaceLLC** [comment]
😍 Hi guys, 
I just wanted to know when it will be available for our dash project with react "17.0.1".
I ask this question so I can move the team to other parts of development

**Comment by ecraig12345** [comment]
@MwSpaceLLC It's available in the version 8 beta currently.

**Comment by MwSpaceLLC** [comment]
Tnks @ecraig12345! So u have any date for use it on production? Or we can try to use it in production? Sorry my question 😢

**Comment by ecraig12345** [comment]
@MwSpaceLLC Version 8 (non-beta) was released today. If you find any issues with it using React 17, please file an issue and we'll fix it.

**Comment by AlexFsmn** [comment]
@ecraig12345 
I've been waiting a month for this to be fixed:
https://github.com/microsoft/fluentui/issues/17313

**Comment by ecraig12345** [comment]
Closing in favor of #20145.
