### ISSUE TITLE
NVDA/Narrator is not reading place holder/aria label in fabric combo box

### ISSUE THREAD

**Issue by Sandhya-aluri** [microsoft/fluentui#15739]
### Environment Information

- **Package version(s)**:  "@fluentui/react": "^7.126.0",
- **Browser and OS versions**: Chrome and Windows 10

### Describe the issue:
NVDA/Narrator is not reading the place holder text of combo box. so we have given aria label, still it is not reading the aria label text.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/sandhya-aluri/pen/pobdjRw?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F

#### Actual behavior:
NVDA/Narrator is not reading place holder/aria label text in fabric combo box.

#### Expected behavior:
NVDA/Narrator should read place holder/aria label text in fabric combo box

**Comment by paulgildea** [comment]
@Sandhya-aluri Thanks for filing this issue!

@smhigley FYI

@tomi-msft Can you determine if this repos in the latest version?

**Comment by tomi-msft** [comment]
Hi @Sandhya-aluri I was unable to repro this using the codepen that you provided. Could you provide some additional info to how to repro the bug?

**Comment by Sandhya-aluri** [comment]
@tomi-msft : Yes this issue exists in latest version as well. Please open the code pen link and NVDA screen reader , once the focus lands on combo box control , it is not reading place holder text. It is just reading the label but not the place holder text.

**Comment by tomi-msft** [comment]
Hi @Sandhya-aluri! I am unable to recreate the issue with Narrator, but I was able to recreate the issue with NVDA screen reader. For a quick workaround, you can add the prop `aria-placeholder` and that should get NVDA to read the place holder.

**Comment by Sandhya-aluri** [comment]
hi @tomi-msft  : Adding aria-placeholder dint work for me with NVDA screen reader. combo box is not reading placeholder with NVDA.
