### ISSUE TITLE
@uifabric/date-time DatePicker clears formatted date on dismiss without date selection

### ISSUE THREAD

**Issue by alex3683** [microsoft/fluentui#15743]
### Environment Information

- **Package version(s)**: 
  - office-ui-fabric-react: 7.148.1
  - @uifabric/date-time: 7.17.30
- **Browser and OS versions**: WIndows 10, Chrome 86.0.4240.111

#### Actual behavior:

- DatePicker has a value set
- Open Calendar Callout by clicking it
- Click somewhere outside of the callout
- The `onSelectDate` callback is called with `undefined` and the formatted value is set to an empty text

(This behavior may be the same as for the current @fluentui/react-date-time v8 betas)

#### Expected behavior:

- DatePicker has a value set
- Open Calendar Callout by clicking it
- Click somewhere outside of the callout
- The `onSelectDate` callback is **not** called and the formatted value remains as it was before opening the callout

( This behavior is the same as in the DatePicker component of the main office-ui-fabric-react package)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@alex3683 Thanks for filing this issue!

@lorejoh12 FYI on the behavior - just including you to understand if this is by design or not.

@tomi-msft Can you verify the behavior in the latest beta release?

**Comment by ecraig12345** [comment]
Sorry for the late follow-up here. @alex3683 can you please provide a codepen with a repro of this behavior? You can use this one as a starting point, and add a DatePicker that's set up similarly to how you're actually using it. https://codepen.io/ecraig12345/pen/dypajWx

**Comment by alex3683** [comment]
It's a long time (at least for my brain 😅) ago since I had that problem and filed the issue. I cannot find the spot in our application anymore, that exposed this behavior and I'm not able to reproduce it in a codepen. So maybe it has already been fixed in the meantime.
So feel free to close this issue and thanks for reaching out!
