### ISSUE TITLE
TagPicker/TagItem: The contrast ratio is less than 3:1 between the close button focus border style and the selected tag color

### ISSUE THREAD

**Issue by SunleoSun** [microsoft/fluentui#15740]
### Description
The contrast ratio is less than 3:1 for a tag item close button border focus style and a selected tag color when user uses keyboard to navigate.

The user isn't able to see a focus border for a close button on a tag if there is a contrast less than 3:1.
![image](https://user-images.githubusercontent.com/6238426/97411832-739cfb80-1909-11eb-8dfb-1400028c0964.png)

### Code pen example
https://codepen.io/sunleosun/pen/MWeoQPQ

### Suggested fix
The close button focused state border may be the same as for the whole tag item focused state border:
![image](https://user-images.githubusercontent.com/6238426/97412330-16ee1080-190a-11eb-844b-f17cb2177267.png)

**Comment by paulgildea** [comment]
@SunleoSun Thanks for filing this issue!

@tomi-msft I'll follow up with the design team on what the color value needs to be updated to.
