### ISSUE TITLE
date picker accessibility: Focus lands twice on dates while navigating in JAWS/NVDA virtual cursor mode

### ISSUE THREAD

**Issue by Fadi2019** [microsoft/fluentui#15744]
### Environment Information

- **Package version(s)**: all
- **Browser and OS versions**: chrome

### Describe the issue:

Narrator/nvda pronounces the date twice when landing on the a date

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/fadielias/pen/MWeQwax?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F

#### Actual behavior:
nvda pronounces the date twice when landing on the date

#### Expected behavior:
nvda should pronounce the date once

**Comment by paulgildea** [comment]
@Fadi2019 Thanks for filing this issue!

@smhigley / @lorejoh12 FYI

@tomi-msft Please make sure there is a repo in the latest 7 version
