### ISSUE TITLE
ContextualMenu accessibility in internal item role

### ISSUE THREAD

**Issue by Fadi2019** [microsoft/fluentui#15742]
### Environment Information

- **Package version(s)**:  7.67.0 and up (all versions)
- **Browser and OS versions**: all (tested on chrome)

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/fadielias/pen/BazJXjz?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F

const { ContextualMenuItemType, IContextualMenuProps, DefaultButton, Fabric, initializeIcons } = window.Fabric;
const { useConst } = window.FabricReactHooks;

// Initialize icons in case this example uses them
initializeIcons();

const ContextualMenuDefaultExample: React.FunctionComponent = () => {
  const menuProps = useConst<IContextualMenuProps>(() => ({
    shouldFocusOnMount: true,
    items: [
      {
        key: 'linkWithOnClick',
        name: 'Link click',
        href: 'http://bing.com',
        role: 'link',
        onClick: (ev: React.MouseEvent<HTMLAnchorElement | HTMLButtonElement>) => {
          alert('Link clicked');
          ev.preventDefault();
        },
        target: '_blank',
      },
    ],
  }));

  return <DefaultButton text="Click for ContextualMenu" menuProps={menuProps} />;
};

const ContextualMenuDefaultExampleWrapper = () => <Fabric><ContextualMenuDefaultExample /></Fabric>;
ReactDOM.render(<ContextualMenuDefaultExampleWrapper />, document.getElementById('content'))

#### Actual behavior:

the role link did not affect the element inside the dom

#### Expected behavior:

the role should affect the internal item

**Comment by paulgildea** [comment]
@Fadi2019 Thanks for filing this issue!

@tomi-msft Determine if this repos with the latest version of the library

@smhigley FYI.
