### ISSUE TITLE
details list is not providing sorting information

### ISSUE THREAD

**Issue by Fadi2019** [microsoft/fluentui#15746]
# Environment Information

- **Package version(s)**: all
- **Browser and OS versions**: chrome

### Describe the issue:

1) Details list is not providing sorting information when landing on the header column (if it is sorted or not and is it sorting descending and ascending)
2) Details list is not providing sorting information when using the keyboard navigation when pressing space, the nvda should announce the sorting is changed  (from ascending to descending).

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/fadielias/pen/bGeLEpB?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F

#### Actual behavior:

Sorting information is not announced

#### Expected behavior:

Sorting information should be announced when landing on the column header using keyboard navigation
When pressing on the space to change the sorting , the new sorting is not announced.

**Comment by paulgildea** [comment]
@Fadi2019 Thanks for filing this issue!

@smhigley FYI on the model

**Comment by tomi-msft** [comment]
Hi @Fadi2019 I am having trouble reproing the bug with NVDA. When I press spacebar after I've tabbed to the arrow, NVDA announces whether the file type is sorted ascending or descending. Could you provide more info on how to repro the bug? Thanks!

**Comment by Fadi2019** [comment]
as you see in the code a component called <announced ...> is added in the code.
In my opinion this component should be integrated inside the details list, and not added externally
