### ISSUE TITLE
Consume ThemeProvider in TMP

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#15749]
## Goals
- We need to be able to use converged components along side v0 or v7 components without too much hassle
- Replace northstar Button with `react-button` implementation along with `ThemeProvider` in TMP

### P0
- [ ] Migration story for northstar theme to v8 theme
  - [ ] map `siteVariables` and `componentVariables` (in northstar theme) to tokens and variants (in v8 theme)
  - [ ] re-write `componentStyles` to `componentVariables` / `variants` in `theme` or use `makeStyles`
  - [ ] can register font faces and animations #15155
  
### P1
- [ ] Proper child window support: right now TMP already have style projection logic for `merge-styles`, so technically we are not blocked. But we should properly handle this internally. 

### Not required
- Support emotion / fela renderer: Converge to single renderer (merge-styles?) in the long term; It's okay to have different renderers between `Provider` and `ThemeProvider` in the short term.

**Comment by xugao** [comment]
We are now tracking latest tasks using #16372 instead. closing this one for now
