### ISSUE TITLE
Produce set of new Fluent UI icons (svg)

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#15758]
-  [x] Tomi: Write a script to consume svg icons and make them into React components (essentially
  get react-icons package working with old implementation of icon)
- [x] Spencer: Use script and established pipeline to publish react-icons package as a prerelease
- [x] David/Tomi/Justin: Finalize details on Icon convergence
- [x] [Tomi: Incorporate changes to Icon component](https://github.com/microsoft/fluentui/pull/16519)
- [x] All: [Update Icon documentation with info on new packages and usage](https://github.com/microsoft/fluentui/pull/16354)

- A comparison between the usage of the old font based FluentUI Icons and the new svg based Icons can he found [here](https://hackmd.io/iDxKqaOPTKqBecH3APxCog?view)

- As part of shipping the new SVG icons, there are use cases where it is necessary to be able to override the default icons. More info about the implementation can be found [here](https://hackmd.io/ezboSQ8BSUaOdmb8h7sHcw?view)

**Comment by mdtauk** [comment]
Please can you submit the icons you design for Office and as part of the Fluent UI project - to the actual **fluentui-system-icons** repo, so that can be a central repository for all Fluent icons

**Comment by JustSlone** [comment]
@mdtauk, we will be producing the Fluent UI icons we use in our Fluent UI React library from the fluentui-system-icons repo (@tomi-msft is doing work here: https://github.com/microsoft/fluentui-system-icons/pull/126) 

That repo is for the new Fluent UI icon set though, we won't be porting the MDL2 icons into that repo if that's what you're asking about. The path going forward should be to use the new icons (there will be of course a transition period as folks update to the new icons)

**Comment by mdtauk** [comment]
No no, MDL2 is done with.  I only wanted to make sure either the new Fluent settled icons you make, go back into the Fluent system icons repo for all to use.  So that repo is the central place to see all the icons.  And that you use the existing icons from that repo, for this one

**Comment by JustSlone** [comment]
Yep! that's the plan 

Actually the way it'll work is that `fluentui-system-icons` is the source of truth for the icons, then scripts run in that repo to produce the icon sets for all platforms. Tomi is doing the work right now to add scripts and setup npm publishing so that the set of react components (that wrap the SVG) will be published from that repo to `@fluentui/react-icons`. 

This means that whenever a new icon is added it will automatically show up in all the platforms including as React Components for use with Fluent UI React.

**Comment by JustSlone** [comment]
Update:
- ThemeProvider doesn't override the rendering the way we need it to for Icons

Next Steps:
- Release the new set and have customers using register icons to override icons
- @tomi-msft to write up details on plan for how to use new icons with register icons

**Comment by JustSlone** [comment]
Jan Update:
- Waiting on new packages to be published
- Icon provider for overrides is in PR, need to move to system-icons repo

TODO (new Feb Project)
- Migration guide
