### ISSUE TITLE
The component miss the CLEARABLE feature. There isn't any way to clear the field.

### ISSUE THREAD

**Issue by bluego78** [microsoft/fluentui#15766]
#### Describe the feature that you would like added

The component miss the CLEARABLE feature. There isn't any way to clear the field.

#### What component or utility would this be added to

TextBox & Searchable

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

-

**Comment by paulgildea** [comment]
@bluego78 Thanks for reaching out. It's a little unclear on what the ask is here so I'm going to go ahead and close this issue. Feel free to submit another issue using our template to help out the team make progress on your request.
