### ISSUE TITLE
fluent ui icons not showing

### ISSUE THREAD

**Issue by ramya298** [microsoft/fluentui#15767]
Hi ,

I am using  "@fluentui/react": "^7.147.1" and node v12.19.0 in my application .
i am trying to use basic control like DropDown  and icons , i dont see the icons . where as the space and placeholder is seen 

#### Actual behavior:

 icons does not display ( i am running my app on local host)
#### Expected behavior:

icons should display 

and my package.json looks like this
"dependencies": {
    "@fluentui/react": "^7.147.1",
    "axios": "^0.21.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-redux": "^7.2.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.3",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3"
  },

**Comment by paulgildea** [comment]
@ramya298 Thanks for filing this issue. Usually we would recommend these types of questions be asked on StackOverflow.

In the mean time have you tried calling `initializeIcons();` in your application to register the icons for the rest of the controls?

**Comment by fayismahmood** [comment]
> @ramya298 Thanks for filing this issue. Usually we would recommend these types of questions be asked on StackOverflow.
> 
> In the mean time have you tried calling `initializeIcons();` in your application to register the icons for the rest of the controls?



> Hi ,
> 
> I am using "@fluentui/react": "^7.147.1" and node v12.19.0 in my application .
> i am trying to use basic control like DropDown and icons , i dont see the icons . where as the space and placeholder is seen
> 
> #### Actual behavior:
> icons does not display ( i am running my app on local host)
> 
> #### Expected behavior:
> icons should display
> 
> and my package.json looks like this
> "dependencies": {
> "@fluentui/react": "^7.147.1",
> "axios": "^0.21.0",
> "react": "^16.13.1",
> "react-dom": "^16.13.1",
> "react-redux": "^7.2.1",
> "react-router-dom": "^5.2.0",
> "react-scripts": "3.4.3",
> "redux": "^4.0.5",
> "redux-saga": "^1.1.3"
> },



> @ramya298 Thanks for filing this issue. Usually we would recommend these types of questions be asked on StackOverflow.
> 
> In the mean time have you tried calling `initializeIcons();` in your application to register the icons for the rest of the controls?

Thanks its working well

**Comment by fayismahmood** [comment]
> @ramya298 Thanks for filing this issue. Usually we would recommend these types of questions be asked on StackOverflow.
> 
> In the mean time have you tried calling `initializeIcons();` in your application to register the icons for the rest of the controls?

Thanks its working well...

**Comment by tomi-msft** [comment]
closing cause this seems to be resolved
