### ISSUE TITLE
Teams logo: Need updated teams logo.

### ISSUE THREAD

**Issue by jameelakowsar** [microsoft/fluentui#15760]
Can we have updated teams logo as below mentioned.

### Environment Information

- **Package version(s)**: Office ui fabric - 7.135.0
- **Browser and OS versions**: All browsers

We found teams (as below image) icon from #### [https://uifabricicons.azurewebsites.net/](https://uifabricicons.azurewebsites.net/) 
![image](https://user-images.githubusercontent.com/20105532/97880924-c0d4ff00-1d47-11eb-9470-7b93ba8459cc.png)

If we add any color to it, it will display like this (Present teams logo)
![image](https://user-images.githubusercontent.com/20105532/97536513-46248080-19e3-11eb-9209-1c1ea664d97f.png)

We need updated teams logo (below image).

#### updated teams logo
![image](https://user-images.githubusercontent.com/20105532/97536472-36a53780-19e3-11eb-8b3b-83b9f4f405b4.png)

All these icons are accessible by 'Icon names', Can we have updated teams logo icon name?

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: blocking

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@jameelakowsar Thanks for filing this. Could you provide a little more context. Especially what package version you are using or would like the change in?
