### ISSUE TITLE
[ISSUE] Page Visibility issues with Fluent UI Theme Designer

### ISSUE THREAD

**Issue by SFM61319** [microsoft/fluentui#15768]
### Environment Information

- **Package version(s)**: Whatever [Fluent UI Theme Designer](https://aka.ms/ThemeDesigner) uses
- **Browser and OS versions**: Not relevant

### Please provide a reproduction of the bug in a codepen:
Visit [Fluent UI Theme Designer](https://aka.ms/ThemeDesigner)

#### Actual behavior:

Page isn't completely visible. Right part of the page is outside the viewport. Some elements are being cut out.

#### Expected behavior:

Page should be completely visible and all contents must be inside the viewport.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, if guidance is provided

Requested priority: Blocking

Products/sites affected: [Fluent UI Theme Designer](https://aka.ms/ThemeDesigner)

Issue:
![Viewport issue](https://user-images.githubusercontent.com/45308169/97576214-e1cde500-1a13-11eb-9f51-d1b49237d196.png)

**Comment by SFM61319** [comment]
As you can see, the color codes for `Background` are not visible.  
  
Even the right part of the horizontal scrollbar (at the bottom) is not visible (forget scrolling through that part)

**Comment by paulgildea** [comment]
@SFM61319 Thanks for filing this issue.

@tomi-msft / @JustSlone Who can we help coordinate a fix with @SFM61319 to submit a PR with for the ThemeDesigner update?

**Comment by JustSlone** [comment]
Strange, I'm seeing this below which is different. 
@SFM61319 could this perhaps be specific to a certain browser or version?

![image](https://user-images.githubusercontent.com/40304143/97759005-5741c000-1abd-11eb-877a-e47e2a292d94.png)

**Comment by SFM61319** [comment]
> Strange, I'm seeing this below which is different (this is in Edge/Chromium Version 86.0.622.38 (Official build) beta (64-bit))
> @SFM61319 could this perhaps be specific to a certain browser or version?
> 
> ![image](https://user-images.githubusercontent.com/40304143/97759005-5741c000-1abd-11eb-877a-e47e2a292d94.png)
> 

I don't know myself tbh. I'll try to open [the site](https://aka.ms/ThemeDesigner) on my phone to check. (I have the latest stable edgium if that helps, and this didn't happen on any other, not at least to me)

**Comment by SFM61319** [comment]
Update: yep checked on both potrait and landscape modes and it's (probably) a bug in the designer's code. (GitHub for Android won't let me upload PNG screenshots for some reason)

**Comment by SFM61319** [comment]
I'm not on pc right now but I'll see if visiting the site on chrome and Firefox changes anything

**Comment by SFM61319** [comment]
@JustSlone I think it's because of the static width values? Because one thing I observed on pc and mobile was the width of the (idk what it's called) color input area (on the left side of the screen) was the same, like I think no media queries (or any other similar queries/rules) are used in that site's stylesheet(s).  
  
What are your PC's areal dimensions and resolution?

**Comment by SFM61319** [comment]
Woah @JustSlone this is weird it is working differently on different browsers  on the same win10 pc (all have been zoomed to 100% - the default value - but still..)  
- ###### *Firefox Developer Edition*  
![Firefox](https://user-images.githubusercontent.com/45308169/97780410-7c602c80-1baa-11eb-899f-282f05beccc8.png)  
  
- ###### *Chrome Stable*  
![Chrome](https://user-images.githubusercontent.com/45308169/97780467-dd880000-1baa-11eb-8052-4ec2e231bb2c.png)

**Comment by JustSlone** [comment]
Hmm, that is interesting. Though both those screenshots look correct, right? The hex values are not cut off.

**Comment by SFM61319** [comment]
Yea. The site works/looks fine but different on chrome and firefox but not on edge. All browsers have been zoomed to 100%. Which is weird.  
  
I tried different window sizes on edge (not just maximized) and also `F12`/`Ctrl + Shift + I` and I'm pretty sure it has to be because of static width values and no media queries (I haven't looked at the source), because the width is constant and the more you reduce the document width, the more elements get hidden.
  
Also, I checked for any warnings and errors and found a *lot* of warnings from `warn.ts` and a few errors. And those errors and warnings change almost everytime you refresh your page (most of them aren't really related to the width issue, but still).

**Comment by JustSlone** [comment]
Ahh, now I see, you're talking about the older Edge not the new chromium based one. Got it, I can repro now. 

If you feel comfortable diving into the ThemeDesigner and proposing a fix we'd be happy to take it!

**Comment by SFM61319** [comment]
> Ahh, now I see, you're talking about the older Edge not the new chromium based one. Got it, I can repro now.
> 
> If you feel comfortable diving into the ThemeDesigner and proposing a fix we'd be happy to take it!

@JustSlone oh no i meant chromium edge (also called "edgium"), not legacy edge. you can see edgium in the original issue screenshot.  
  
i can check the site on legacy edge too. will update in a few

**Comment by SFM61319** [comment]
welp, its opening edgium instead of legacy edge ("Ledge") even though i clicked on legacy edge and not chromium edge  
![legacy edge button](https://user-images.githubusercontent.com/45308169/99522549-cffcb380-29bb-11eb-8bf7-3a1de4a15b56.png)
