### ISSUE TITLE
ContextualMenu on mobile Chrome (Android): not possible to prevent dismiss on resize

### ISSUE THREAD

**Issue by sadomovalex** [microsoft/fluentui#15765]
### Environment Information

- **Package version(s)**: sp-office-ui-fabric-core v.1.11.0
- **Browser and OS versions**: mobile Chrome on Android

### Describe the issue:

If we add contextual menu to DefaultButton and add input fields into this contextual menu (textboxes, people pickers, calendar, dropdowns, etc):
```
<DefaultButton
	...
	menuProps={{ items: menuItems }}
/>
```
then on mobile browser it is not possible to specify input values for textboxes and people pickers (for calendars, drop downs and choice fields it works): when you tap textbox/people picker mobile keyboard appears in bottom part of the phone screen. It generates "resize" event which in turn causes dismiss of contextual menu.

There is similar issue here about callouts: [Chrome android: keyboard focus in Callout causes scroll from keyboard, which dismisses Callouts](https://github.com/microsoft/fluentui/issues/6864). But provided solution doesn't work for ContextualMenu: if we try to specify calloutProps like this:

```
<DefaultButton
	...
	menuProps={{ items: menuItems, calloutProps: { preventDismissOnResize: true, preventDismissOnScroll: true }  }}
/>
```
menu still dismisses when you tab textbox or people picker. We also tried to prevent dismiss on resize like that: specify handler for onDismiss event in DefaultButton:
```
<DefaultButton
	...
	menuProps={{ items: menuItems, onDismiss: this._onDismiss.bind(this)  }}
/>

private _onDismiss(ev?: React.MouseEvent | React.KeyboardEvent) {
	const isMobileDevice = this.isMobileDevice();
	if (ev && isMobileDevice && (ev.type === "resize" || ev.type === "scroll")) {
		ev.stopPropagation();
		ev.preventDefault();
		return false;
	} else {
		// should dismiss
		this._dismissMenu();
	}
}
```

But it also didn't help. Is there any other way to prevent dismiss of contextual menu on mobile browser?

#### Actual behavior:

On Android Chrome contextual menu dismisses when you tap on textbox or people picker (so they got focus) located on this contextual menu.

#### Expected behavior:

Contextual menu doesn't dismisses when you tap on textbox or people picker.

**Comment by paulgildea** [comment]
@sadomovalex Thanks for filing this issue!

@joschect Any ideas here on a workaround the meantime?

@tomi-msft See you can get a repo with the latest v7 and the website
