### ISSUE TITLE
Initial focus on components do not show focus styling in Northstar

### ISSUE THREAD

**Issue by davyrwoo** [microsoft/fluentui#15781]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@ 0.51.2

### Describe the issue:

When putting initial focus on a component, the focus styling (focus border) is not applied. 
When clicking tab to focus on the next element, the focus styling appears for the next element, so it seems like the focus suddenly appears in the middle of the screen

### Please provide a reproduction of the issue in a codepen:

https://codesandbox.io/s/sleepy-mcclintock-1zzqw?file=/example.js

Click "Open in a New Window" in the browser view on the right side of the codesandbox.

#### Actual behavior:

1. Observe that there is no focus on "Focus Button"
2. Click "Tab" to see that focus goes to "Second Button", meaning that focus was previously on "Focus Button", but it had no styling.

#### Expected behavior:

Focus should appear on the focused element. Could be related to the "initial" focus from "data-whatinput"
![Initial Focus Bug](https://user-images.githubusercontent.com/56053686/97643830-f4412200-1a05-11eb-8507-9d2ba370c9f9.PNG)

### Documentation describing expected behavior

Internal MSFT a11y pass, can give more details in ADO if requested.

**Comment by paulgildea** [comment]
@davyrwoo Thanks for filing this issue!

@jurokapsiar FYI

**Comment by jurokapsiar** [comment]
This is by design, focus ring appears only when keyboard triggered the move of the focus. If you want to explicitly change the state, you can use
```
setWhatInputSource(document, "keyboard")
```

`setWhatInputSource` can be imported from `@fluentui/react-northstar`
