### ISSUE TITLE
X-axis descriptor have duplicated value in AreaChart

### ISSUE THREAD

**Issue by luckyrass** [microsoft/fluentui#15788]
### Environment Information

- **Package version(s)**: (5.0.0-beta.7)
- **Browser and OS versions**: (All)

### Please provide a reproduction of the bug in a codepen:

X-axis descriptor have duplicated value in AreaChart. Such as Jan appears 4 times in X-axis. 

#### Actual behavior:

![image](https://user-images.githubusercontent.com/12230173/97705926-d2bc6500-1aef-11eb-9599-6620c2eacdc9.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/12230173/97706042-fc758c00-1aef-11eb-8ea5-4264959c2b71.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@luckyrass Thanks for filing this issue!

@Raghurk FYI

**Comment by shivasai09** [comment]
@luckyrass  could you please provide the data you passed in, or steps to repro.

Thanks, 
siva

**Comment by luckyrass** [comment]
We can repro with the following code. Thanks.

```
import * as React from 'react';
import { AreaChart } from '@fluentui/react-charting';
import { ILineChartProps } from '@fluentui/react-charting';
import { DefaultPalette } from '@fluentui/react/lib/Styling';

interface IAreaChartBasicState {
  width: number;
  height: number;
}

export class AreaChartStyledExample extends React.Component<{}, IAreaChartBasicState> {
  constructor(props: ILineChartProps) {
    super(props);
    this.state = {
      width: 700,
      height: 300,
    };
  }

  public render(): JSX.Element {
    return <div>{this._basicExample()}</div>;
  }

  private _onWidthChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    this.setState({ width: parseInt(e.target.value, 10) });
  };
  private _onHeightChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    console.log('height change');
    this.setState({ height: parseInt(e.target.value, 10) });
  };

  private _basicExample(): JSX.Element {
    const chart1Points = [
      {
        x: new Date('2018/01/06'),
        y: 5,
      },
      {
        x: new Date('2018/01/08'),
        y: 16,
      },
      {
        x: new Date('2018/01/16'),
        y: 6,
      },
      {
        x: new Date('2018/02/06'),
        y: 30,
      },
      {
        x: new Date('2018/02/16'),
        y: 10,
      },
    ];

    const chart2Points = [
      {
        x: new Date('2018/01/06'),
        y: 10,
      },
      {
        x: new Date('2018/01/08'),
        y: 33,
      },
      {
        x: new Date('2018/01/16'),
        y: 21,
      },
      {
        x: new Date('2018/02/06'),
        y: 44,
      },
      {
        x: new Date('2018/02/16'),
        y: 22,
      },
    ];

    const chartPoints = [
      {
        legend: 'legend1',
        data: chart1Points,
        color: DefaultPalette.accent,
      },
      {
        legend: 'legend2',
        data: chart2Points,
        color: DefaultPalette.blueLight,
      },
    ];

    const chartData = {
      chartTitle: 'Area chart styled example',
      lineChartData: chartPoints,
    };

    const rootStyle = { width: `${this.state.width}px`, height: `${this.state.height}px` };

    return (
      <>
        <label>change Width:</label>
        <input type="range" value={this.state.width} min={200} max={1000} onChange={this._onWidthChange} />
        <label>change Height:</label>
        <input type="range" value={this.state.height} min={200} max={1000} onChange={this._onHeightChange} />
        <div style={rootStyle}>
          <AreaChart
            height={this.state.height}
            width={this.state.width}
            data={chartData}
            showYAxisGridLines={false}
            tickFormat="%b"
          />
        </div>
      </>
    );
  }
}

```

**Comment by shivasai09** [comment]
@luckyrass  i see that in your code `tickFormat` is `%b` that is why you are seeing only month name. i belive if you add  some more string specifires like `%b%j` then i think issue will be resolved..  could you please try to update and see? let us know if it works properly

please refer to  https://github.com/d3/d3-time-format for more time specifiers

**Comment by luckyrass** [comment]
@shivasai09 I'm trying to keep it the same as the figma design. In the design, the tickFormat should be %b. 
![image](https://user-images.githubusercontent.com/12230173/98072223-82068c80-1ea0-11eb-8b69-91542ccf118c.png)

**Comment by shivasai09** [comment]
@luckyrass  all the dates given in data are different , it's not duplicate. it's because of tickFormat it appears like duplicate. but it's not, i feel this is not an issue.

please try to add the dates you want to show in the prop `tickValues` i think that will achieve your figma

**Comment by luckyrass** [comment]
Yes. It is helpful. Thanks shivasai09 for the suggestion.
