### ISSUE TITLE
Narrator Scan Mode has a blank stop on arrow down after Input Box

### ISSUE THREAD

**Issue by Dalimil** [microsoft/fluentui#15792]
### Describe the issue:
Narrator Scan Mode has a blank stop on arrow down after the input box. So it announces 'blank'.

#### Actual behavior:

It announces 'blank' as the next stop in scan mode.

#### Expected behavior:

Doesn't announce anything and goes directly to next element.

### If applicable, please provide a codepen repro:
https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? YES

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable) ALL

![image](https://user-images.githubusercontent.com/4202539/97744773-0d4ce000-1aa5-11eb-854a-b6badc21a9d2.png)
^^^ this error element needs to have aria-hidden=true when empty

**Comment by paulgildea** [comment]
@Dalimil Thanks for filing this issue and submitting a PR!

@smhigley FYI 

@tomi-msft / @JustSlone let's coordinate on this PR please. Thanks!

**Comment by JustSlone** [comment]
PR Looks good to me. I'd like @joschect to take a quick look and confirm though.
