### ISSUE TITLE
Typing does not help to select dropdown item

### ISSUE THREAD

**Issue by msmenti** [microsoft/fluentui#15793]
### Environment Information

- **Package version(s)**: (7.147.1)
- **Browser and OS versions**: (Windows 10)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/sdusttm/pen/YzWavzX

#### Actual behavior:

For the dropdown component, when user expand the dropdown and type on keyboard, the corresponding option is not select, like I type 'c', I would expect CN to be heighlighted and ready to be selected

#### Expected behavior:

in this experience: https://signup.microsoft.com/create-account/signup?culture=en-us&country=US&products=cfq7ttc0k59j:0009&ali=1
go to the step that has dropdown, and type and see hightlights.

### Priorities and help requested: this is affecting multiple services in office commercial domain and is getting a lot of feedback from PMs

Are you willing to submit a PR to fix? (Yes, No) yes if guidance is provided

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: Microsoft commercial new react signup, commercial purchase, commercial payment form, office admin center, etc

**Comment by paulgildea** [comment]
@msmenti Thanks for filing this issue and with any help on contributing a fix.

@tomi-msft / @JustSlone can we coordinate here if we think we can get this in a state where this could be added to the Dropdown in a non-breaking way?

**Comment by tomi-msft** [comment]
Hi @msmenti there is currently no support for this feature in Dropdown. This is by design, and we have created Combobox to address this. I would recommend using Combobox for this feature!

**Comment by msmenti** [comment]
Hi Tomi,

I just give combo box a try, but it is still not the optimal solution, for is example, in a dropdown with USSSSSA, USSSSSSB, USSSSSSC

If I want to choose USSSSSSC, if the feature is implemented in dropdown, I can type U and got to highlight USSSSSA, then use keyboard to go down 2 and get USSSSSSC.

With combo box, if I type U, USSSSSA will be auto completed but I won’t be able to see other options and have to type in the whole USSSSSSC.

I feel this should be a feature planned for maybe future, as I have seen a lot of PM complaint. My msft alias is menti, I can provide more details if needed.

Meng

**Comment by Harshagracy** [comment]
I agree with @msmenti . This feature is a must.
