### ISSUE TITLE
CommandBarItem does not show `checked: true` styling when item is rendered in overflow menu

### ISSUE THREAD

**Issue by MichaelRechenberg** [microsoft/fluentui#15805]
### Environment Information

- **Package version(s)**: (fill this out)
Fabric version 7.149.3
- **Browser and OS versions**: (fill this out if relevant)
Verified on Edge, runnin on Windows

### Please provide a reproduction of the bug in a codepen:

Repro CodePen: https://codepen.io/michaelrechenberg/pen/rNLKBNd?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F

The repro CodePen is almost identical to the first pen in the portfolio for CommandBar => https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar.  The only difference is that menu item specifies the property `checked: true`...a property of `IContextualMenuItem`

#### Actual behavior:

When the menu item is rendered in the overflow menu, the checked styling that's present when the item is rendered regularly is not present

Share item rendered "regularly".  Note the gray background color.
![image](https://user-images.githubusercontent.com/13754529/97923392-c2380480-1d12-11eb-93bd-d1b28e29fbf6.png)

Share item rendered in overflow menu.  Note the lack of gray background color.
![image](https://user-images.githubusercontent.com/13754529/97923460-dd0a7900-1d12-11eb-8da9-5071cfb19071.png)

#### Expected behavior:

I expect the menu item, when rendering functions are not defined, to have the same default styling when it's rendered in an overflow menu vs "regularly"

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)

**Comment by MichaelRechenberg** [comment]
I could not see from documentation that such a styling difference would happen

**Comment by paulgildea** [comment]
@MichaelRechenberg Thanks for filing this issue! This issue behavior might be by design.

@joschect / @micahgodbolt If you have any insights on the design of the `ContextualMenu` styling. My hunch is that the `CommandBar` does not provide checked styling in the overflow menu. 

@behowell If it comes back as by design please resolve as such.
