### ISSUE TITLE
password eye icon is not shown in chromium edge

### ISSUE THREAD

**Issue by msmenti** [microsoft/fluentui#15808]
### Environment Information

- **Package version(s)**: (windows 10)
- **Browser and OS versions**: (edge  87.0.658.0 )

#### Actual behavior:

eye icon is not shown

#### Expected behavior:

eye icon is shown. same pen opened in chrome will work.

### Priorities and help requested: medium

Are you willing to submit a PR to fix? (Yes, No) no

Requested priority: (Blocking, High, Normal, Low) normal

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@msmenti Thanks for filing this issue!

**Comment by JustSlone** [comment]
This is expected. Chromium edge does not need the password reveal button, it automatically shows it for password fields.

Reference:
https://9to5google.com/2019/08/28/microsoft-developed-reveal-password-edge-chrome/

Code:
https://github.com/microsoft/fluentui/blob/117d6ff2a1def8d26e93822c1baf05fbf4f7e865/packages/react-internal/src/components/TextField/TextField.base.tsx#L626-L640
