### ISSUE TITLE
Dropdown value resets to the default value provided in defaultSelectedKey(s) prop when component re-renders

### ISSUE THREAD

**Issue by olivertylsar** [microsoft/fluentui#15803]
### Environment Information

- **Package version(s)**: 7.149.2

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/olivertylsar/pen/zYBWQXY

#### Actual behavior:

When re-render happens, Dropdown component resets its value to defaultSelectedKey(s) if this prop was provided. I tested it without passing the prop and it worked well, the value stay there.

For example, if form is submitted and state is changed within the submit handler, component re-renders and value in the Dropdown component resets to the default value, which was provided by the props defaultSelectedKey or defaultSelectedKeys if multiSelect={true}.

#### Expected behavior:
Dropdown should behave exactly as TextField or Toggle (see codepen) or any other FluentUI component, that means keep its current values even if re-render happens. I believe it's a bug. Dropdown component should preserve its value during re-render and should only reset to default value provided only on mount.

Thanks for looking into this issue.

**Comment by olivertylsar** [comment]
I was investivating a bit further, passed a ref to the component and inspected it when rerender happened and I could see the default values on the ref.current.selectedOptions array even though I changed the selection. There is also some kind of "inner state" I guess of the selections under ref.current.state.selectedIndices, which seems like indexes of the selected options and those seem alright. But I wasn't looking into the code so I'm not sure if it's relevant.

Anyway I can now confirm that this only happens when using the uncontrolled approach. Using the controlled one and setting the state of selectedKeys on every change manually is working just fine. Anyway it would still be worth it to be looked at. Thanks.

**Comment by paulgildea** [comment]
@olivertylsar Thanks for filing this issue and digging into it a bit more. That's super helpful. So are you unblocked in that you can use the controlled version in the meantime?

@joschect FYI if you think this is by design or if we need to address the uncontrolled case.

**Comment by olivertylsar** [comment]
@paulgildea No problem, thanks. Yes, I'm fine with with the controlled approach. I just use React Hook Form library for managing forms and it's easier to integrate it with uncontrolled components. But in this case the only extra portion of work is having to sync the values of the form control manually on every change of the component's state, which actually controls the component's value (selected items). So, it's not a big deal for me personally to work around it this way.
