### ISSUE TITLE
The x-axis labels of VerticalStackedBarChart is cut off when showXAxisLablesTooltip is set as true

### ISSUE THREAD

**Issue by cariceli** [microsoft/fluentui#15819]
### Environment Information

- **Package version(s)**: 4.9.0
- **Browser and OS versions**: Chrome

#### Actual behavior:

The x-axis labels of VerticalBarChart is cut off when showXAxisLablesTooltip is set as true
![image](https://user-images.githubusercontent.com/42231272/97970724-ef60e180-1dfc-11eb-90c0-57f8d1315d3f.png)

#### Expected behavior:

Display entire x-axis labels

**Comment by jameelakowsar** [comment]
Hi @cariceli,

Can you please add tickPadding={5} prop to the chart and check if this works?

Note: Here, tickPadding Default value is 10.
Based on graph we can customize the space between scale and tick values.

I think this will helpful, feel free to reach us out if you have any questions.
Thank you!
