### ISSUE TITLE
The x-axis labels of VerticalBarChart is cut off when showXAxisLablesTooltip is set as true

### ISSUE THREAD

**Issue by cariceli** [microsoft/fluentui#15818]
### Environment Information

- **Package version(s)**: 4.9.0
- **Browser and OS versions**: Chrome

#### Actual behavior:

The x-axis labels of VerticalBarChart is cut off when showXAxisLablesTooltip is set as true
![image](https://user-images.githubusercontent.com/42231272/97970043-e1f72780-1dfb-11eb-899b-da887aac245c.png)

#### Expected behavior:

Display entire x-axis labels

**Comment by Raghurk** [comment]
Will look into these

**Comment by jameelakowsar** [comment]
Hi @cariceli,

Can you please add `tickPadding={5}` prop to the chart and check if this works?

Note: Here, `tickPadding` Default value is 10. 
Based on graph we can customize the space between scale and tick values.

I think this will helpful, feel free to reach us out if you have any questions.
Thank you!

**Comment by cariceli** [comment]
Hi @jameelakowsar ,
It works, thank you.
But the tooltip doesn't show up when hovering on the folded x-axis labels of VerticalBarChart & VerticalStackedBarChart.
Can these two charts display the tooltip like the GroupedVerticalBarChart?
![image](https://user-images.githubusercontent.com/42231272/99511454-3cc77c00-29c3-11eb-9c55-ea4e04ee0702.png)
