### ISSUE TITLE
MaskedTextField doesn't work correctly when using autocomplete

### ISSUE THREAD

**Issue by ChristopherHaws** [microsoft/fluentui#15813]
### Environment Information

- **Package version(s)**: 7.149.3 and 8.0.0.beta.7
- **Browser and OS versions**: Chrome and Edge Dev

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/phone-number-field-repro-f4jzv?file=/src/index.tsx

#### Actual behavior:
Using autocomplete to select a Phone Number in chrome fills out 1 of the 10 numbers and leaves the rest blank.

#### Expected behavior:
It should work similar to if you passed a value in using state. In this scenario, it formats correctly.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low)
Low
Products/sites affected: (if applicable)
Internal

**Comment by paulgildea** [comment]
@ChristopherHaws Thanks for filing this issue! We'll take a look at it.
