### ISSUE TITLE
--webkit-scrollbar interferes with other styles

### ISSUE THREAD

**Issue by DaleyKD** [microsoft/fluentui#15821]
### Environment Information

- **Package version(s)**: "@fluentui/react-northstar": "^0.51.2"

### Please provide a reproduction of the bug in a codepen:
I'm not sure how to do this with react-northstar

#### Actual behavior:
The --webkit-scrollbar width and height that is being generated by https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-northstar/src/themes/teams/components/Provider/providerStyles.ts interferes with the width of cells in a KendoReact grid. While this may appear to be an issue with KendoReact, it wouldn't be an issue if I could simply get rid of the CSS that northstar is setting.

I have tried setting width and height to 0 !important, but after reading more about this particular psuedo-element, it's just not possible to override it.

I tried to remove the actual CSS rule via JavaScript, and that worked when I was in Fela Debug mode.  Once I went into Fela Production, any northstar controls stopped rendering properly.

This is a screenshot of what it looks like in Microsoft Teams.
![image](https://user-images.githubusercontent.com/7206282/98029909-dbee5000-1dd5-11eb-8597-500b4b1e3457.png)

#### Expected behavior:
I'd like to have a way to override the --webkit-scrollbar CSS styles that are being set by https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-northstar/src/themes/teams/components/Provider/providerStyles.ts.

### Priorities and help requested:

Are you willing to submit a PR to fix? I don't know enough about React to be able to.

Requested priority: High

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@DaleyKD Thanks for filing this issue. We'll look into it.

@behowell Could you also look to see if there is a workaround that @DaleyKD could provide as well as determine if this is an issue with `northstar`

@jurokapsiar Could you coordinate with @behowell on who would could help out on the `northstar` side?

**Comment by behowell** [comment]
Hi @DaleyKD, I'll need to be able to repro this to be able to help further. Ideally you could create a small example demonstrating the issue in [CodeSandbox](https://codesandbox.io/) or [CodePen](https://codepen.io/). You can start with one of the [examples from the documentation site](https://fluentsite.z22.web.core.windows.net/0.51.2/components/provider/definition) and export it to CodeSandbox, where you can edit it to repro this issue.

There's a button on each example to export it to CodeSandbox:
[![image](https://user-images.githubusercontent.com/48106640/98188932-cefe5900-1ec8-11eb-9408-8a0a76536573.png)](https://fluentsite.z22.web.core.windows.net/0.51.2/components/provider/definition)

Documentation site for react-northstar: https://fluentsite.z22.web.core.windows.net/

**Comment by jurokapsiar** [comment]
Hi, there is unfortunately currently no way to remove keys from the component style objects.

You can either create your own theme that does not contain the scrollbars, or try to modify existing one, similar to: https://codesandbox.io/s/clever-wind-tf9nv?file=/example.js

**Comment by DaleyKD** [comment]
@jurokapsiar : This is the information I needed.  I should've known a simple `delete` would've sufficed. I had hoped maybe setting it to `null` would work.  Derp.

Thank you.
