### ISSUE TITLE
Enum for staus prop on avatar component

### ISSUE THREAD

**Issue by rdweaver** [microsoft/fluentui#15822]
#### Describe the feature that you would like added

I would like the status prop on the avatar component to be an enum

#### What component or utility would this be added to

avatar component

#### Have you discussed this feature with our team, and if so, who

no

#### Additional context/screenshots

For example of how this should work is the persona component has a PersonaPresence enum. https://developer.microsoft.com/en-us/fluentui#/controls/web/persona#PersonaPresence. In addition, setting the PersonaPresence will update the PersonaPresence with the presence data icon (i.e. the check mark or minus icon) that matches what MS Teams uses.  
When you set the status prop on the avatar component, it does not put a data icon on the status, that has to be done in code.

**Comment by paulgildea** [comment]
@rdweaver Thanks for the feature request! 

I'm assuming you are asking for this feature request in the `northstar` package. Please correct me if I'm wrong.

We are working a converged `Avatar` component so I'll will flag this as feedback for the folks that are working on that component. You can see the in progress work here: https://github.com/microsoft/fluentui/tree/master/packages/react-avatar note this isn't a production ready component at this time.

@JustSlone / @dzearing FYI on the feedback for the API - and feel free to resolve this once we officially release the new component and we've addressed the feedback.
