### ISSUE TITLE
StackedBarChart does not announce number of items when click the item keys under the bar

### ISSUE THREAD

**Issue by alton-browsing** [microsoft/fluentui#15837]
### Environment Information

- **Package version(s)**: 2.8.1
- Edge Version: Version 86.0.622.48 (Official build) (64-bit)
- URL: https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/charting/dist/index.html#/examples/stackedbarchart#Overview

### Describe the issue:

Narrator doesn't announce the respective count of the items upon selecting the list items under the bar graphs.

Users who rely on screen reader will not know the respective count of the devices until unless user cross check by navigating to the graph.

Per PWD user feedback, it is good to have an announcement immediately on selecting the list item even though user understand by navigating to the bar graph.

### Please provide a reproduction of the issue in a codepen:
Can repro using examples of Stacked bar chart

1. Open URL https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/charting/dist/index.html#/examples/stackedbarchart#Overview
2. Open narrator
3. Navigate to any Stacked bar chart image and click any of the item keys under the bar chart.

#### Actual behavior:

It says the name of that key item followed by its position like 2 of 4, followed by selected.

#### Expected behavior:

Should include the current actual behavior as well as the respective count of that key item. Name of that key item followed by its position like 2 of 4, followed by selected, followed by count of that key item.

**Comment by paulgildea** [comment]
@alton-browsing Thanks for filing this issue!

@Raghurk
