### ISSUE TITLE
NVDA/Narrator is not reading the aria label of fabric text field control.

### ISSUE THREAD

**Issue by Sandhya-aluri** [microsoft/fluentui#15839]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^7.123.4",
- **Browser and OS versions**: chrome and windows 11

### Describe the issue:
NVDA/Narrator is not reading the aria label of fabric text field control.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/sandhya-aluri/pen/WNxKZXR?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F

#### Actual behavior:
NVDA/Narrator is not reading the aria label provided of fabric text field control.

#### Expected behavior:
NVDA/Narrator should read the aria label provided of fabric text field control.

**Comment by paulgildea** [comment]
@Sandhya-aluri Thanks for filing this issue! We'll look into it.

@behowell This seems like it could be a regression... however, I'm unclear if we've changed anything in. `TextField` recently.

**Comment by paulgildea** [comment]
@Sandhya-aluri Did you mean Windows 10?

**Comment by Sandhya-aluri** [comment]
@paulgildea : yes windows 10. Chrome + NVDA and EDGE + Narrator.
