### ISSUE TITLE
Tag picker Zoom issue : The text typed in the fabric Tag picker control is not visible as it is covered by the autosuggestion dropdown when the page is zoomed to 400%.

### ISSUE THREAD

**Issue by Sandhya-aluri** [microsoft/fluentui#15840]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^7.123.4",
- **Browser and OS versions**: chrome and windows 11

### Describe the issue:
The text typed in the fabric Tag picker control is not visible as it is covered by the autosuggestion dropdown when the page is zoomed to 400%.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/sandhya-aluri/pen/KKMBXxX?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F

#### Actual behavior:
The text typed in the fabric Tag picker control is not visible as it is covered by the autosuggestion dropdown when the page is zoomed to 400%.

#### Expected behavior:
The text typed in the fabric Tag picker control should be visible when the page is zoomed to 400%.

**Comment by paulgildea** [comment]
@Sandhya-aluri Thanks for filing this issue. Also do you mean Windows 10 as the OS platform?

@behowell Please investigate and try to determine the scope of the fix - It's unclear to me how difficult it will be to ensure there is usable experience at 400%.

**Comment by Sandhya-aluri** [comment]
@paulgildea : yes windows 10.
