### ISSUE TITLE
Narrator not announce when toggle DetailsList header sorting order 

### ISSUE THREAD

**Issue by shuotli** [microsoft/fluentui#15849]
### Environment Information

- **Package version(s)**: v0.7.1
- **Browser and OS versions**: Edge chromium / windows

### Describe the issue:

When toggling the header to change the sorting ascending/descending, the Narrator doesn't announce the new sorting order.

### Please provide a reproduction of the issue in a codepen:

We can simple use the exmaple in https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist

#### Actual behavior:

When toggling the header to change the sorting ascending/descending, the Narrator should announce the new sorting order.

#### Expected behavior:

When toggling the header to change the sorting ascending/descending, the Narrator doesn't announce the new sorting order.

**Comment by paulgildea** [comment]
@shuotli Thanks for the filing this issue!

@behowell This sounds similar to #15841 or might be related. Please determine if this is a fundamental issue with the DetailsList or an issue with the sample itself.

**Comment by shuotli** [comment]
> @shuotli Thanks for the filing this issue!
> 
> @behowell This sounds similar to #15841 or might be related. Please determine if this is a fundamental issue with the DetailsList or an issue with the sample itself.

Thank you for your response. This is an issue with Narrator not announce information so it is a different issue from #15841.
I believe this is not just with the sample because we experience the same issue on our side.

**Comment by dawolff-ms** [comment]
@paulgildea do you have any updates on this issue? Our team has gotten an MAS A11Y bug for this, and MAS won't close until this bug is resolved.
