### ISSUE TITLE
Screen Reader : On narrator keyboard not toggle the expand/collapse all button of DetailsList - Grouped

### ISSUE THREAD

**Issue by nupur120983** [microsoft/fluentui#15841]
### Environment Information

Package version(s): "@fluentui/react": "^7.123.4",
Browser and OS versions: chrome and windows 10

### Describe the issue:
![narratornottoggle](https://user-images.githubusercontent.com/50817032/98236424-557a6f80-1f89-11eb-8df8-14821e629ed1.gif)

#### Actual behavior:

On narrator keyboard not toggle the expand/collapse button of DetailsList - Grouped

#### Expected behavior:

On narrator keyboard its should toggle the expand/collapse button of DetailsList - Grouped on enter

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@nupur120983 Thanks for filing this issue and providing a video of the issue. This is very helpful for our team to diagnose the issue. Also did you mean Window 10 for the platform?

@behowell This looks like a straightforward repo on the website. Also please determine if it's inherent to the DetailsList or if it's a sample issue that needs to be fixed.
