### ISSUE TITLE
`mergeStyles()` doesn't parse `calc()` for padding/margin shorthands

### ISSUE THREAD

**Issue by mrnateriver** [microsoft/fluentui#15842]
Terribly sorry for filing a bug without proper template, but the issue is utterly straightforward:
https://github.com/microsoft/fluentui/blob/34ec543117e6bf63461b26ea610fa750a45b4927/packages/merge-styles/src/styleToClassName.ts#L160-L167

Function that splits `padding`/`margin` CSS shorthand into four separate properties does not take `calc()` values into account, which results in invalid values for those props.

To reproduce, just create a style like the following:
```javascript
const styles = mergeStyles({
  padding: 'calc(24px / 2) 0',
});
```

Present in `master` branch.

**Comment by paulgildea** [comment]
@mrnateriver Thanks for filing this issue and providing enough detail that we can take action on the issue.

@dzearing - FYI Not sure if this is something that can be added in a non-breaking way. Also just curious if this is being taken into account for the new styling utilities that are in preview. 

@behowell Please coordinate with @dzearing on the approach for this issue. Thanks!

**Comment by behowell** [comment]
Should be possible to split the string while ignoring spaces within parentheses. I'll make a PR with a fix.
