### ISSUE TITLE
Remove composition utilities from release notes

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#15845]
**UPDATE: Now the utilities aren't being released in v8, so we need to remove this from the release notes.**

~~We mention the composition utilities in the [release notes](https://github.com/microsoft/fluentui/wiki/Version-8%3A-Release-notes#in-preview-composition-utilities) but no details on how to try them out.~~

~~We should put the documentation somewhere (not in the release notes file itself) and link to it from the release notes. (Or if they're no longer "composition" utilities we should update that wording in the release notes as well as documenting.)~~

Should also update the v8 announcement issue (#12770) if we decide to remove the composition utilities part.

**Comment by dzearing** [comment]
I am updating the wording on release notes.
