### ISSUE TITLE
Certain interfaces and components are not exported, yet essential

### ISSUE THREAD

**Issue by Dalimil** [microsoft/fluentui#15853]
1) The only way to import `CalloutContentBase` is like this:
`import { CalloutContentBase } from 'office-ui-fabric-react/lib/components/Callout/CalloutContent.base';`
2) The only way to import `PanelBase` is like this:
`import { PanelBase } from 'office-ui-fabric-react/lib/components/Panel/Panel.base';`
3) Same for `IButtonClassNames`
4) Same for `IContextualMenuClassNames`
5) Same for `IMenuItemClassNames`
6) Same for test utilities `expectOne` and `expectMissing`

All of these should properly export these, otherwise deep imports (officially unsupported) are unavoidable.
This blocks transition from office-online-fabric-react to fluentui/react

**Comment by ecraig12345** [comment]
If you need the test utilities, those should probably be added to `@fluentui/test-utilities` and exported from there. (Not sure why that wasn't done to begin with.)

**Comment by paulgildea** [comment]
@Dalimil Thanks for filing this issue.

@behowell / @JustSlone Can we coordinate with @Dalimil to understand their deep import needs and determine the best way forward. I noticed a some dependencies on base components, which leads me to believe that the components `Panel` and `Callout` might be missing something. If so let's see if we can contribute something in.

**Comment by ecraig12345** [comment]
@Dalimil already submitted a PR fixing most of these (thanks!) and we're discussing there.
