### ISSUE TITLE
Unable to Navigate Picker Suggestions in Narrator Scan Mode

### ISSUE THREAD

**Issue by mrkushjain** [microsoft/fluentui#15866]
### Environment Information

- **Package version(s)**: Current (seen on Fabric Picker component homepage on 11/9/2020 )
- **Browser and OS versions**: Microsoft Edge Version 86.0.622.63 (Official build) (64-bit)

### Describe the issue:
##See attachment for screen recording
[issue video.zip](https://github.com/microsoft/fluentui/files/5509097/issue.video.zip)

0. Turn on narrator in scan mode (by pressing CAPS+SPACE)
1. Go to https://developer.microsoft.com/en-us/fluentui#/controls/web/pickers#ISuggestionsProps
2. In the first picker type b
3. Suggestions will appear
4. Press Down arrow key

#### Actual behavior:
5. Focus does not move down always to the next suggestion

#### Expected behavior:
5. Focus should move to the next suggestion

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Low

Products/sites affected: (if applicable) all
[issue video.zip](https://github.com/microsoft/fluentui/files/5509088/issue.video.zip)

**Comment by paulgildea** [comment]
@mrkushjain Thanks for filing this issue. We'll take a look.

@smhigley FYI.
