### ISSUE TITLE
Toolbar menu has incorrect styles in Fluent UI react-northstar

### ISSUE THREAD

**Issue by codepretty** [microsoft/fluentui#15877]
Toolbar submenu has incorrect design
![image](https://user-images.githubusercontent.com/828692/98584176-5a396f00-227a-11eb-87eb-cb68ed3587fa.png)

Issues with toolbar menu are
1. Menu item height is 38px in toolbar, should be 32px and match menu item height
2. Icon is aligned incorrectly, should be aligned to top line or centered with only 1 line
3. Menu width is restricted

You can see the difference between menu items and toolbar menu items here - https://codesandbox.io/s/fluent-ui-example-forked-gowb3?file=/example.js

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Normal)

Products/sites affected: (TMP CMD)

**Comment by jurokapsiar** [comment]
@codepretty thanks for reporting - would you or your team be able to look into these?
