### ISSUE TITLE
getInitials should strip [xyz] (angled braces) just like it strips (xyz)

### ISSUE THREAD

**Issue by philipzloh** [microsoft/fluentui#15878]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

RegEx for the code today in
```
const UNWANTED_CHARS_REGEX: RegExp = /\([^)]*\)|[\0-\u001F\!-/:-@\[-`\{-\u00BF\u0250-\u036F\uD800-\uFFFF]/g;

function cleanupDisplayName(displayName: string): string {
  displayName = displayName.replace(UNWANTED_CHARS_REGEX, '');
  displayName = displayName.replace(MULTIPLE_WHITESPACES_REGEX, ' ');
  displayName = displayName.trim();

  return displayName;
}
```

Takes `Kevin Andersen (EEE)` and turns it into `Kevin Andersen` but takes `Kevin Andersen [EEE]` and turns it into `Kevin Andersen EEE` resulting in initials of `KE` in the latter case (undesired).

#### Expected behavior:

Strip the content of [xyz] just like we strip the content of (xyz)
Probably should do the same thing for the curly braces too

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by philipzloh** [comment]
Plan is to change
```
const UNWANTED_CHARS_REGEX: RegExp = /\([^)]*\)|[\0-\u001F\!-/:-@\[-`\{-\u00BF\u0250-\u036F\uD800-\uFFFF]/g;
```
to
```
const UNWANTED_CHARS_REGEX: RegExp = /[\(\[\{][^\)\]\}]*[\)\]\}]|[\0-\u001F\!-/:-@\[-`\{-\u00BF\u0250-\u036F\uD800-\uFFFF]/g;
```

**Comment by paulgildea** [comment]
@philipzloh Thanks for filing this issue proposing changes.

@JustSlone for review and @behowell please coordinate on the PR.
