### ISSUE TITLE
Fluent UI - React Northstar. Menu component throws exception

### ISSUE THREAD

**Issue by AndreyButyrchik** [microsoft/fluentui#15871]
### Environment Information

- @fluentui/react-northstar - 0.51.2
- Google Chrome Version 86.0.4240.183

### Reproduction of the bug:

- Add Menu component
- Try click on menu item

#### Actual behavior:

Menu component throws next error in console:

```
Warning: Cannot update a component (`MenuItem`) while rendering a different component (`ContextSelector.Provider`). To locate the bad setState() call inside `ContextSelector.Provider`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at ContextSelector.Provider (https://g38l5.csb.app/node_modules/@fluentui/react-context-selector/dist/es/createContext.js:13:27)
    at ul
    at FocusZone (https://g38l5.csb.app/node_modules/@fluentui/react-bindings/dist/es/FocusZone/FocusZone.js:53:30)
    at Menu (https://g38l5.csb.app/node_modules/@fluentui/react-compose/lib/compose.js:16:27)
    at App
```

#### Expected behavior:

No errors

**Comment by paulgildea** [comment]
@AndreyButyrchik Thanks for filing this issue. Would you mind adding a codepen or codesandbox of the issue so that we make faster traction debugging this issue?

Thanks!

**Comment by AndreyButyrchik** [comment]
@paulgildea Sorry for late answer. You can use this one https://codesandbox.io/s/vigilant-sound-g38l5?file=/src/App.js

**Comment by DaleyKD** [comment]
+1

@paulgildea : Would you please reopen this issue? I'm getting it, too.
