### ISSUE TITLE
Breadcrumb provides onRender for items but doesn't respect it for overflow items

### ISSUE THREAD

**Issue by PatoBeltran** [microsoft/fluentui#15881]
### Environment Information

- **Package version(s)**: 7.123.9

### Please provide a reproduction of the bug in a codepen:

The breadcrumb component provides a `onRenderItem` that you can use to render custom content on the item itself, but as soon as the item goes in the overflow menu the `onRenderItem` is not respected. I would expect that either the same method is used for rendering the overflow items or the API should provide an `onRenderOverflownItem` to be able to do this.

In our app we use React-router, and therefore we need to use their custom `Link` component for internal navigation, so in this case the overflow items are not aware of the router and reload the whole page. Apart from this, the styling needs to be written twice (for items and overflown items) and the focus-visible doesn't respect styles for non-href items (The same way that the mouse provides styles for)

### Priorities and help requested:

Are you willing to submit a PR to fix? **Yes**

Requested priority: High

Products/sites affected: Azure IoT Central

**Comment by paulgildea** [comment]
@PatoBeltran Thanks for filing this issue. Sounds like this is more a feature request to provide a custom rendering mechanism for items that are overflowed into the `ContextualMenu`. Is this something you are willing to contribute a fix for?

@JustSlone FYI as this is might be adding an additional API surface area to `Breadcrumb`.

To set expectations, we are focused on converging component across our libraries and we'll take this into consideration as we converge the `Breadcrumb` component. But I don't have any timelines to share at this point on when we will get to that component.

**Comment by PatoBeltran** [comment]
@paulgildea Thanks for your response. The reason why I think this is a bug and not a feature is because the Breadcrumb already provides the API to render custom components for the item, but as soon as the items are overflown then that API is 100% ignored. I understand that the overflow component is a different one, but as an API surface I would expect the items to work in the same way.

To consider contributing for this, what would be the expected change be? Does the overflow component already support this feature or I would need to add support to that component as well? would it be a matter of reusing the `onItemRender` or adding a new API?

**Comment by PatoBeltran** [comment]
@paulgildea I noticed this same problem exists in the `CommandBar` component. That one does provide a way to render custom submenu items when the submenu is in one of the command bar items, but as soon as it overflows, there's no way to render custom overflow menu items (or have it respect my custom command bar item render)
