### ISSUE TITLE
Focus is not going to multi select dropdown selected options in windows high contrast white mode. Only single line border  is available on selected items.

### ISSUE THREAD

**Issue by Sandhya-aluri** [microsoft/fluentui#15887]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^7.126.0",
- **Browser and OS versions**: Chrome and Windows 10

### Describe the issue:
Complete Focus is not going to multi select dropdown selected  ptions in windows high contrast white mode. Only single line border is available on selected items.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/sandhya-aluri/pen/OJXBKVg?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F

#### Actual behavior:
Focus is not going to multi select dropdown selected  options in windows high contrast white mode. Only single line border  is available on selected items.

#### Expected behavior:
Complete focus should be visible in multi select dropdown selected options in windows high contrast white mode.

**Comment by paulgildea** [comment]
@Sandhya-aluri Thanks for filing this issue. We'll take a look.

@xugao FYI on High Contrast
