### ISSUE TITLE
Details List - When column reorder is enabled, icon is displayed on column headers

### ISSUE THREAD

**Issue by SteveJerbs** [microsoft/fluentui#15896]
### Environment Information

- **Package version(s)**: Office-UI-Fabric 7
- **Browser and OS versions**: Edge on Windows 10

### Please provide a reproduction of the bug in a codepen:
[CodePen](https://codepen.io/connormel/pen/BazGzRj?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F)
When using the code pen referenced by the Fluent Team in the docs for the DetailsList component, if you toggle 'Enable Column Reorder' radio button to enabled an icon is displayed on hover of the column headers.  

**Side note:** In our production app, this is happening all the time (not just on hover).  

#### Actual behavior:
1.  Enable 'Enable Column Reorder'
2.  Hover mouse over column header in grid
3.  Observe icon that is displayed on hover

![image](https://user-images.githubusercontent.com/57688062/98687753-19079480-2338-11eb-81d7-41c8357cae9a.png)

#### Expected behavior:

No icon should be displayed when hovering over column headers

### Priorities and help requested:

Are you willing to submit a PR to fix? With some guidance I would be willing to take a look.  I'm having trouble narrowing down the issue.  It looks like some custom CSS is being used on the Docs page to prevent the issue but I am not positive.

Requested priority: Normal

Products/sites affected:

**Comment by paulgildea** [comment]
@SteveJerbs Thanks for filing this issue. I'm just a little bit unclear. Is it issue is that you are seeing icon when re-order is enabled? If that's the case I believe that's by design.

@dzearing / @behowell Is there a workaround in styling to hide those icons if that's the desired experience for @SteveJerbs

**Comment by SteveJerbs** [comment]
@paulgildea - Thank you for the quick response.  You are exactly right!  We would like to hide these icons. I think a more meaningful behavior would be to have the cursor icon switch to a hand when hovering over draggable column headers.  The small icon doesn't provide much context to the user in my opinion.  

I also noticed that the icons are hidden on the documentation pages ([linked here](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/draganddrop).

**Comment by wfbcargo** [comment]
@paulgildea @SteveJerbs I noticed a similar issue when using the [Fabric Core](https://developer.microsoft.com/en-us/fluentui#/get-started#fabric-core) css library. It appears that the icon persists due to

`.ms-Icon {
    display: inline-block;
    font-family: FabricMDL2Icons;
    font-style: normal;
    font-weight: 400;
    speak: none;
}`

Removing this dependency / overriding the display style to hidden, did resolve the issue.

**Comment by behowell** [comment]
@SteveJerbs it doesn't look like DetailsList supports removing the gripper icon when the column is draggable, but you could modify the style of the gripper using the `gripperBarVerticalStyle` property of the column's `style`.

Here's a quick and somewhat hacky modification to the DetailsList example that hides the icons, by setting the gripper's display to none for each column. Hopefully it demonstrates the idea, and you can write a better version for your app.
```tsx
      columns: buildColumns(items, true).map(column => ({
        ...column,
        styles: { gripperBarVerticalStyle: { display: 'none !important' } },
      })),
```

https://codepen.io/behowell/pen/NWRWKzW

Let me know if this works for you.
