### ISSUE TITLE
Publish new Fluent Icons in our repo

### ISSUE THREAD

**Issue by tomi-msft** [microsoft/fluentui#15899]
# Publish new Fluent Icons in our repo

## Problem
We have a new fluentui icon set that we want folks to begin adopting, and we need to publish it to npm. It is an svg icon set, so we need to consume the raw svg assets and transform them into a form usable in our repo. 
## Solution
- Write a script that consumes the raw svg assets and wraps them in a React element wrapper.
- Use the `createSvgIcon` method as a scaffold
- Spencer Nelson will take script and publish the new icons in the `fluentui-system-icons` repo as a prerelease
## Added Context

The raw svg assets are released with the sizes shipped separately  and the filled and outline states shipped separately.

**Comment by mdtauk** [comment]
**fluentui-system-icons** Does include a webfont now as part of it's build process.

Couldn't FluentUI take a dependency on the icon repo, maybe work with them to include a package that this repo can injest.

Rather than duplicating the icons and potentially causing mis matches and inconsistencies?

**Comment by tomi-msft** [comment]
I think that is the plan

**Comment by tomi-msft** [comment]
Reopening this issue to add more specifics for releasing the new icons

**Comment by tomi-msft** [comment]
Marking as resolved: New fluentui vNext components use @fluentui/react-icons
