### ISSUE TITLE
ComboBox feature request: data virtualization

### ISSUE THREAD

**Issue by savkelita** [microsoft/fluentui#15892]
#### Describe the feature that you would like added

Why does **ComboBox Component** not have props like _pickerSuggestionsProps/onResolveSuggestions/onGetMoreResults_? The main issue is how to handle 1K+ items received from API. In that case Pagination can be the solution and the props mentioned above would allow us implementation like the one inside of BasePicker Component.

Thanks.

#### What component or utility would this be added to

ComboBox

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

No.

**Comment by paulgildea** [comment]
@savkelita Thanks for the filing this issue.

This seems more like question rather than a request, so I'll mark as such for now.

Have you looked the "VirtualizedComboBox" to sample to handle UI virtualization for large sets of data returned and does that address your scenario?

**Comment by savkelita** [comment]
Hi @paulgildea thank you for suggestion.

We are trying to avoid HTTP responses over 1K rows on a single request, based on that VirtualizedComboBox is not a solution. We built a custom component like this one https://codepen.io/vitalius1/pen/BvOojj to be as much as possible like ComboBox. Selected value is separated from input field and it looks "ugly" on small resolutions:

https://ibb.co/HTyWxCf

It would be great to keep selected and input value together.

**Comment by behowell** [comment]
Hi @savkelita, to make sure I understand the request: it sounds like you're asking for data virtualization support for VirtualComboBox (which currently only supports UI virtualization)? Specifically, allowing auto-complete to search within the virtualized data, presumably by making a server request in an "onResolveSuggestions"-type handler?

We can consider data virtualization support for future updates to ComboBox, but we don't have any immediate plans to implement it at the moment.

**Comment by savkelita** [comment]
@behowell You are right, that's what i'm looking for. We hope it will come in some future versions. Thank you!
