### ISSUE TITLE
Multiple Selection dropdown has additional space after selection list

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#15893]
After the PR
https://github.com/microsoft/fluentui/pull/14864/files#diff-0dfcfdca092d43b516fbc6007112238d042697c91fdced73011fa22d664d65f2R773-R777

Dropdown has additional space after user selection list:
![image](https://user-images.githubusercontent.com/22620150/98678043-3ea79480-235e-11eb-92aa-68e726db2333.png)

Before there was no additional space: 

![image](https://user-images.githubusercontent.com/22620150/98678395-c5f50800-235e-11eb-8d8a-d08cbbe8a895.png)

As @assuncaocharles  correctly figured out it is cause by adding "listbox" which is followed by "dropdown" button itself. 
We need to add there "listbox" because of accessibility.

**Comment by paulgildea** [comment]
@kolaps33 👍
