### ISSUE TITLE
[CommandBar] IButtonProps.menuProps.contextualMenuItemAs does not work when provided via ICommandBarProps.overflowButtonProps

### ISSUE THREAD

**Issue by Wezea** [microsoft/fluentui#15895]
### Environment Information

- **Package version(s)**: office-ui-fabric-react": "7.149.4,
- **Browser and OS versions**:  Chrome: "Version 86.0.4240.183 (Offizieller Build) (64-Bit)", Windows 10 2004

### Please provide a reproduction of the bug in a codepen:

This bug is reproducable with the example "_CommandBar custom buttons and overflow menu_" provided on the official dev page.

https://developer.microsoft.com/de-DE/fluentui#/controls/web/commandbar#implementation

#### Actual behavior:

The overflow menu renders all menu items as  `CustomButton`.

#### Expected behavior:

The overflow menu renders `CustomMenuItem` provided via `contextualMenuItemAs`.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: ( Normal )

**Comment by paulgildea** [comment]
@Wezea Thanks for filing this issue.

@micahgodbolt / @joschect / @JustSlone Is this by design?

**Comment by JustSlone** [comment]
@Wezea, I'm not sure I follow the issue here. 

`contextualMenuItemAs` is used to determine the element to be used to render the MenuItems inside the ContextMenu. It appears the example is infact doing that.

In this pen i've replaced the ContextMenuItem with a Label and we can clearly see it's being used when the menu is expanded. 
https://codepen.io/justslone-the-encoder/pen/qBNwVGV?editors=0010

**Comment by Wezea** [comment]
@JustSlone Thank you for responding to that issue. 

The problem is probably more related to the component  `ContextMenuItem`.

In the component `CustomMenuItem` [here](https://developer.microsoft.com/de-DE/fluentui#/controls/web/commandbar) it doesn't render its given properties. E.g. the `onClick` override is not working.

**Comment by behowell** [comment]
Hi @Wezea, it looks like this is a bug in the example on the website. ContextMenuItem doesn't support the onClick property. The click handler is specified on the CommandBar item instead (defined in the _overflowItems array in the example). I suppose you could wrap the ContextualMenuItem with a span that has an onClick handler if you needed:

```tsx
const CustomMenuItem: React.FunctionComponent<IContextualMenuItemProps> = props => {
  const buttonOnMouseClick = () => alert(`${props.item.text} clicked`);
  return (
    <span onClick={buttonOnMouseClick}>
      <ContextualMenuItem {...props} />
    </span>
  );
};
```

**Comment by micahgodbolt** [comment]
It looks like the 'onClick' for the IContextualMenuItem is on the "item" prop of the ContextualMenuItem. I agree that it's some odd nesting, but I think it's better than adding a wrapping div.

https://github.com/microsoft/fluentui/blob/4270b4a2054bd89419dec726d6c6871b21f1e97b/packages/react-internal/src/components/ContextualMenu/ContextualMenuItem.types.ts#L57
