### ISSUE TITLE
Narrator does not read deleted letters in TextField Component

### ISSUE THREAD

**Issue by khaled-elgendy** [microsoft/fluentui#15919]
### Environment Information

- **Package version(s)**: (fluent 0.16.9)
- **Browser**: (Version 86.0.622.63)
- **OS versions**: (Windows 10.0.19042 Build 19042)

### Describe the issue:
For accessibility purposes a deleted letter in a text field should be announced when it is deleted. In Edge while using the narrator this does not occur. 

### Repro the issue:

1. Go to https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield
2. Turn on Narrator
3. Enter text into the Standard Field. Example below
![image](https://user-images.githubusercontent.com/74328000/98870597-5f3c2100-2428-11eb-9c8c-63a7f98c0dbc.png)
4. Press backspace to delete a letter. The narrator does not announce the letter.
![image](https://user-images.githubusercontent.com/74328000/98870685-8266d080-2428-11eb-9643-078c3a982ad8.png)

#### Actual behavior:

 The narrator does not read aloud a deleted letter in a TextField when backspace is used. When it does it does so randomly.

#### Expected behavior:

When using the narrator, the narrator should read aloud the deleted letter when backspace is used to delete a letter

### MAS Reference
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Comment by paulgildea** [comment]
@khaled-elgendy Thanks for filing this issue. Quick question, you reference a version number of the package that could be the `northstar` codebase as opposed to the `react` codebase. Can you clarify? The screen shots you reference are from the `react` codebase.

@behowell See if you can repo with the current version of `react` unless noted otherwise. Thanks!

**Comment by khaled-elgendy** [comment]
@paulgildea   I think the bug is in northstar, but it's on an internal Microsoft product so I didn't want to post pics and links, but the bug is the same as the react one I posted.
