### ISSUE TITLE
Modal | Expose a ref to the div that holds the modal

### ISSUE THREAD

**Issue by katiearriagam** [microsoft/fluentui#15927]
#### Describe the feature that you would like added

- HTML div element component ref in the modal to access the component's CSS properties
- Currently dialogs provide no way to access the modal's `offsetHeight` property.

#### What component or utility would this be added to

Modal/Dialog

#### Have you discussed this feature with our team, and if so, who

Not yet. I was told to open an issue here.

#### Additional context/screenshots

When setting the `IModal` componentRef, there is no property that provides access to the div that contains the modal.
`{props: {…}, context: {…}, refs: {…}, updater: {…}, _focusTrapZone: {…}, …}componentDidMount: ƒ ()componentDidUpdate: ƒ ()componentWillUnmount: ƒ ()context: {}props: {responsiveMode: 2, theme: {…}, enableAriaHiddenSiblings: undefined, elementToFocusOnDismiss: undefined, firstFocusableSelector: "primaryDialogButton", …}refs: {}state: {id: "Modal744", isOpen: true, isVisible: true, hasBeenOpened: true, x: 0, …}updater: {isMounted: ƒ, enqueueSetState: ƒ, enqueueReplaceState: ƒ, enqueueForceUpdate: ƒ}_allowScrollOnModal: ƒ (elt)_allowTouchBodyScroll: false_async: Async {_timeoutIds: null, _immediateIds: null, _intervalIds: null, _animationFrameIds: null, _isDisposed: false, …}_events: EventGroup {_id: 331, _parent: ModalBase, _eventRecords: Array(3)}_focusTrapZone: {current: FocusTrapZone}_hasRegisteredKeyUp: true_lastSetX: 0_lastSetY: 0_onDrag: ƒ (_, ui)_onDragStart: ƒ ()_onDragStop: ƒ ()_onEnterKeyboardMoveMode: ƒ ()_onExitKeyboardMoveMode: ƒ ()_onKeyDown: ƒ (event)_onKeyUp: ƒ (event)_onModalClose: ƒ ()_onModalContextMenuClose: ƒ ()_reactInternalFiber: FiberNode {tag: 1, key: null, stateNode: ModalBase, elementType: ƒ, type: ƒ, …}_reactInternalInstance: {_processChildContext: ƒ}_registerForKeyUp: ƒ ()_registerInitialModalPosition: ƒ ()_scrollableContent: div.ms-Modal-scrollableContent.scrollableContent-261isMounted: (...)replaceState: (...)__proto__: Component`

**Comment by katiearriagam** [comment]
@ecraig12345 @joschect: can you take a look at this feature request? I'm happy to create a PR for it but modalProps used to have a ref that later got removed, so I would like to make sure that readding this is the right way to go.

**Comment by paulgildea** [comment]
@katiearriagam Thanks for filing this issue and offering to contribute a PR!

@JustSlone FYI 

@behowell Once we come back with a solid approach, please coordinate with @katiearriagam on getting PR together.

**Comment by joschect** [comment]
@katiearriagam Could you provide a little more information as to your use case? Why do you need access to the offsetHeight? Are you looking to modify it or just to know where it is on the page?

**Comment by katiearriagam** [comment]
Sure. The use case is that we need to center dialogs vertically while the `topOffsetFixed` prop is set to `true`. To do this, we need to set the `top` property, which is set on the [Modal.styles.ts file](https://github.com/microsoft/fluentui/blob/cbc0b9a2f9b569eeabd7bba3812002edcca948e8/packages/react-internal/src/components/Modal/Modal.styles.ts):
```ts
 topOffsetFixed &&
        hasBeenOpened && {
          top: modalRectangleTop, // we need to override this property
        },
```

We need to access the `offsetHeight` to get the height of the modal after it is rendered, so we can calculate where it should be pinned to remain centered. [This PR contains a detailed explanation of the issue and the proposed solution](https://office.visualstudio.com/OC/_git/office-online-ui/pullrequest/602551).

Currently, we can access this property through class names as you can see in the PR, but we would like to be able to use a ref or something more specific.

**Comment by joschect** [comment]
@katiearriagam I believe that you can achieve the same styling that you want without needing a ref, at least I think, by doing something like I do in [this codepen](https://codepen.io/slimemold/pen/GRqzWxq?editors=0010). If that's not accurate please let me know!

**Comment by katiearriagam** [comment]
Hey @joschect - do you mind highlighting here or in the CodePen (with comments), which parts do you think should achieve this behaviour? I would like to make sure I don't miss anything.

**Comment by joschect** [comment]
@katiearriagam I have added a comment to the codepen highlighting the bit. It's this style block
```js
styles={{
          main: {
            overflow: "unset"
          },
          scrollableContent: {
            position: "absolute",
            backgroundColor: "inherit",
            minWidth: "288px",
            left: "0px",
            top: "0px"
          }
        }}
```

**Comment by katiearriagam** [comment]
While the proposed solution works under normal conditions, it doesn't cover all the scenarios that need to be supported by the web apps. I still need access to the modal, which we can get through the classNames today, but we want something more specific (such as an id or a ref).

**Comment by ecraig12345** [comment]
After thinking about this more, here's what I would propose.

In version 8, move `IModalProps.ref` from the actual root DOM element (a Layer) to the root of the content (a FocusTrapZone). Technically this violates the pattern (which we're trying pretty hard to standardize) of having `IFooProps.ref` always point to the root DOM element, but I think in cases where a Layer is involved, having it point to the content rather than the Layer makes more sense and is more likely to match user expectations. (Also, if somebody wanted a ref to the Layer, they could pass `IModalProps.layerProps.ref`.) [Current code for reference.](https://github.com/microsoft/fluentui/blob/master/packages/react-internal/src/components/Modal/Modal.base.tsx#L401)

Since @katiearriagam's team will need this fix sooner than they'll be able to finish picking up version 8, we'll also need a solution that works in v7. The pattern we've been using for this is adding and immediately deprecating `IModalProps.elementRef` in the v7 component, with the same behavior as `IModalProps.ref` in v8.

**Comment by ecraig12345** [comment]
I'd also propose that we standardize on this pattern for all/most components that use a Layer wrapping their actual content: `IFooProps.ref` points to the **actual content** not the Layer. (Will need to update the ref conformance test to handle this.)

**Comment by JustSlone** [comment]
@ecraig12345 can you write this down in a quick RFC proposing the standard going forward? Then we can gather feedback and record it for our future selves.
