### ISSUE TITLE
In table mode(Details list), Narrator's focus not in sync with keyboard focus

### ISSUE THREAD

**Issue by nupur120983** [microsoft/fluentui#15923]
### Describe the issue:

In table mode, Narrator's focus not in sync with keyboard focus

#### Actual behavior:

Narrator's focus not in sync with keyboard focus

#### Expected behavior:

Narrator's focus should sync with keyboard focus

![image](https://user-images.githubusercontent.com/50817032/98932343-3b024200-2505-11eb-8516-f9d3d6a04365.png)

Requested priority: High

**Comment by paulgildea** [comment]
@nupur120983 Thanks for filing this issue. Can you please provide what OS platform version you are using because that can help us determine if there are any known Narrator issues.

Thanks!
