### ISSUE TITLE
Stackedbar chart unnecessary focusable bars

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#15921]
In the stacked bar chart if the user wishes to hide the callout and also he don't have the url to navigate to the other page,
then we need to make the bars non-focusable.

**Comment by shivasai09** [comment]
currently we need to keep this on hold, because the question arises here is why do we have to show the visualization if we are hiding tooltip in first place.

it need investigation

**Comment by paulgildea** [comment]
@shivasai09 Sounds good. I'll mark as investigate. Thanks!
