### ISSUE TITLE
When using onSelectDate, the value in the field does not update

### ISSUE THREAD

**Issue by bluego78** [microsoft/fluentui#15924]
Looks like the issue has been resolved now, thanks! 👍

_Originally posted by @WesselKuipers in https://github.com/microsoft/fluentui/issues/1274#issuecomment-295207645_

How did you resolved? I still have this issue.... When using onSelectDate, the value in the field does not updates...

**Comment by paulgildea** [comment]
@bluego78 Thanks for filing this. Can you help me out a little more with the issue you are having? Can you provide a codepen that is replicating the issue that you are seeing?

**Comment by bluego78** [comment]
Sorry i've tried to create the same environment on codepen but I can't.

I'm using:

- "@fluentui/react": "^7.150.0",
- "react": "^16.14.0"
- "react-dom": "^16.14.0"

`<DatePicker
                        id="MyField"
                        placeholder="Select a date..."
                        ariaLabel="Date"
                        label="Date"
                        onSelectDate={(date) =>
                            console.log(date)
                        }
                    />`

If you remove the "onSelectDate" the date will appears in the field after selecting from calendar.
If "onSelectDate" is in place, the date doesn't appears.

**Comment by behowell** [comment]
@bluego78 I tried pasting your example into a CodePen, and it seems to work correctly. The date is updated on selection:
https://codepen.io/behowell/pen/OJXdmao

I'm going to close this as Can't Repro for now. Please reopen if you can provide a CodePen that reproduces the problem you're seeing. The easiest way to create a CodePen is to start from an example from the documentation, and click Export to CodePen: https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker
