### ISSUE TITLE
Cannot dismiss FocusTrapCallout when click outside of the callout

### ISSUE THREAD

**Issue by KeiraYang** [microsoft/fluentui#15922]
# Environment Information 

- **Package version(s)**: master branch
- **Browser and OS versions**:Windows + Edge Chromium
- **Component**: FocusTrapCallout

### Please provide a reproduction of the bug in a codepen:

https://developer.microsoft.com/en-us/fluentui#/controls/web/callout
Click "Show FocusTrapCallout" -> callout is opened, then click outside. Observe the issue. I didn't set any interface related to it to prevent the dismiss when click outside. So by default it should be dismissed as the interface description:
    /**
     * If true then the callout will not dismiss when it loses focus
     * @defaultvalue false
     * @deprecated use preventDismissOnEvent callback instead
     */
    preventDismissOnLostFocus?: boolean;
    /**
     * If defined, then takes priority over preventDismissOnLostFocus, preventDismissOnResize,
     * and preventDismissOnScroll.
     * If it returns true, then callout will not dismiss for this event.
     * If not defined or returns false, callout can dismiss for this event.
     */
    preventDismissOnEvent?: (ev: Event | React.FocusEvent | React.KeyboardEvent | React.MouseEvent) => boolean;

#### Actual behavior:

The callout cannot be dismissed when click outside of FocusTrapcallout

#### Expected behavior:

The callout should be dismissed when click outside of FocusTrapcallout

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@KeiraYang Thanks for filing this issue. We'll take a look!

@behowell I noticed that the `Callout` examples on the site is only opening one `Callout` always anchoring to the first example. So there might be a regression here.

**Comment by KeiraYang** [comment]
Thank you @paulgildea. Is there ETA for the fix?

**Comment by kemusag** [comment]
I also ran into this issue. After a short investigation I tried these props:
focusTrapProps={{
        isClickableOutsideFocusTrap: true
}}

That seems to work for me :)

**Comment by behowell** [comment]
Thanks for the suggestion @kemusag. @KeiraYang does that suggestion solve this issue for you?
