### ISSUE TITLE
No accessible name and description for charting components

### ISSUE THREAD

**Issue by shandysulen** [microsoft/fluentui#15925]
### Environment Information

- **Package version(s)**: @fluentui/react-charting v5.0.0-beta.0
- **Browser and OS versions**: Microsoft Edge v86.0.622.68, Windows 10 Enterprise 20H2
- **Assistive Technologies**: Narrator

### Describe the issue:

Although the `VerticalStackedBarChart` component will be used as the example, this issue applies to all exported charting components in `@fluentui/react-charting` from what I can tell. The top-level rendered `<svg>` should support ARIA attributes, namely `aria-labelledby` and `aria-describedby`. Screen reader users in Scan Mode with Windows Narrator receive no context that they're jumping into a chart. After the screen reader announces "graphic" or "image" (to represent the `svg`), the screen reader jumps to the next plaintext in the DOM, which in the linked example are the x-axis values. It's difficult to understand what's going on from the perspective of the screen reader user. An accessible name and description would go a long way in making these components more accessible and intelligible for vision-impaired users. 

### Please provide a reproduction of the issue:

1. Go to the demo at https://codesandbox.io/s/fluentuireact-charting-a11y-bug-no-accessible-name-demo-dbr6x?file=/src/Chart.tsx:2035-2038
2. Turn on Narrator (<kbd>Ctrl</kbd> + <kbd>Win</kbd> + <kbd>Enter</kbd>) and enable Read All Document (<kbd>Narrator</kbd> + <kbd>↓</kbd>)
3. Listen to the lack of 1. context of what the chart is all about and 2. how to navigate around the chart

#### Actual behavior:

There is no `aria-labelledby` or other semantic ARIA attribute on the rendered `<svg>` element, nor is there a `<title>` and/or `<desc>` element within the `<svg>`.

#### Expected behavior:

By providing the appropriate prop(s) to the `VerticalStackedBarChart` component, the `VerticalStackedBarChart` should follow the guidance from the resources posted below:
1. Include `<title>` and `<desc>` as direct first children of `<svg>`
2. For better support, attach `id`s to `<title>` and `<desc>` and link them to `<svg>` via `aria-labelledby`

These props don't seem to exist yet for `@fluentui/react-charting` components and thus is preventing the shipping of our app.

### Documentation describing expected behavior

- [CSS Tricks's Accessible SVG's](https://css-tricks.com/accessible-svgs/#2-inline-svg)
- [A11y 101's Accessible SVGs](https://a11y-101.com/development/svg)

> For SVGs needing more descriptive alternative content, pattern 11 <svg> + role="img" + <title> + \<desc> + aria-labelledby="[ID]" was the most reliable choice for the different browser and screen readers that were tested. - _[Deque](https://www.deque.com/blog/creating-accessible-svgs/)_

**Comment by paulgildea** [comment]
@shandysulen Thanks for filing this issue.

@smhigley FYI

@Raghurk FYI

**Comment by shandysulen** [comment]
Hello all, I wanted to mention that I've been playing around in the repo for the last two days, and I have local changes that fix this issue. The solution entails adding `<title>` and `<desc>` as the first children under the top-level `<svg>` and linking them to the `<svg>` via `aria-labelledby`. This ensures that these pieces of text are always read out even, although in some cases, they may be read out twice, depending on the screen reader.

How should I proceed?

**Comment by mbest** [comment]
This was fixed with #16828
