### ISSUE TITLE
First focused bar's callout metadata read multiple times

### ISSUE THREAD

**Issue by shandysulen** [microsoft/fluentui#15938]
### Environment Information

- **Package version(s)**: @fluentui/react-charting v5.0.0-beta.0
- **Browser and OS versions**: Microsoft Edge v86.0.622.68, Windows 10 Enterprise 20H2
- **Assistive Technologies**: Narrator

### Describe the issue:

I am experiencing this issue specifically with the `VerticalStackedBarChart` component although I imagine it occurs for every component that derives from the `CartesianChart` common component.

When Narrator is in Focus Mode, the `aria-label` passed to the Callout and the role of "group" is read multiple times before the content of the callout is read.

### Please provide a reproduction of the issue:

1. Go to https://codesandbox.io/s/fluentuireact-charting-a11y-bug-i1hxd?file=/src/Chart.tsx
2. Turn on Narrator (<kbd>Ctrl</kbd> + <kbd>Win</kbd> + <kbd>Enter</kbd>) and enable Focus Mode (<kbd>Narrator</kbd> + <kbd>Space</kbd>)
3. Press <kbd>Tab</kbd> to focus on the chart's first bar
4. Listen to redundant `aria-label` and "group" read out before the callout's content is read out

#### Actual behavior:

The `aria-label` and "group" is read out **multiple times** before the callout's content is read out.

#### Expected behavior:

The `aria-label` and "group" should be read out **once** before the callout's content is read out.

**Comment by paulgildea** [comment]
@shandysulen Thanks for filing this charting issue!

**Comment by shandysulen** [comment]
I was able to fix this issue by passing `role: "status"` within the `calloutProps` prop. I don't understand how it fixes the issue exactly, so it might be worth digging into it a little more.

**Comment by mbest** [comment]
Do we need to do anything else for this?
