### ISSUE TITLE
Is there a CDN link to the latest fabric icon set css file?

### ISSUE THREAD

**Issue by TheInvoker** [microsoft/fluentui#15939]
#### Describe the feature that you would like added

A cdn to the latest fabric icon set css file.

#### What component or utility would this be added to

I am trying load the office fabric UI icons on my page through css, but I am noticing that some icons do not appear. For example if you go here https://codepen.io/joshmcrty/pen/GOBWeV and put in `AcceptMedium`  into the icon name and click "render font icon", you will see the image has "none" in it. It is also using the css file https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css. 

However if you go to https://uifabricicons.azurewebsites.net/ and search for `AcceptMedium`, the icon does come up.

Is there a newer css reference file to the latest font definition?

**Comment by paulgildea** [comment]
@TheInvoker Thanks for filing this issue and providing a codepen. It's really appreciated.

@behowell Can you follow up to determine if this is latest CDN? @dzearing might have more context here or the right contacts on who would have the most up to date knowledge of the CDN location. 

@JustSlone FYI

**Comment by TheInvoker** [comment]
Thanks. Ultimately I'm just trying to generate an image format of any icon. The current technique i'm using is load it in a canvas and extract the data url from it. But wondering if there is any link where i can just pull the png or something directly?
