### ISSUE TITLE
Support option for x-axis and y-axis to have aria-hidden="true"

### ISSUE THREAD

**Issue by shandysulen** [microsoft/fluentui#15935]
### Environment Information

- **Package version(s)**: @fluentui/react-charting v5.0.0-beta.0
- **Browser and OS versions**: Microsoft Edge v86.0.622.68, Windows 10 Enterprise 20H2
- **Assistive Technologies**: Narrator

### Describe the issue:

I am experiencing this issue specifically with the `VerticalStackedBarChart` component although I imagine it occurs for every component that derives from the `CartesianChart` common component.

When Narrator is in Scan Mode and is reading the whole document (<kbd>Narrator + ↓</kbd>), the screen reader first announces the x-axis tick values, then the y-axis tick values, and then the bars. Since the callouts of the bars can hold the x-axis data point and the y-axis data point, I see little need to announce the tick values beforehand as it would only confuse the blind screen reader user as to what the numbers mean. The callouts alone seem to provide all the value the chart offers to blind users.

If it's decided that this shouldn't be default behavior, there could instead be a prop exposed to allow consumers to apply `aria-hidden="true"` to the the first two `<g>`s within the top-level rendered `<svg>`, which represent the x-axis and y-axis respectively.

![image](https://user-images.githubusercontent.com/15238391/99110148-c845a500-259e-11eb-9c74-77737f6d1ee9.png)

### Please provide a reproduction:

1. Head over to the `VerticalStackedBarChart` example [here](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/charting/dist/index.html#/examples/VerticalStackedBarChart)
2. Turn on Scan Mode, and begin reading the whole document: <kbd>Narrator</kbd> + <kbd>↓</kbd>.
3. Listen to the tick values read out before any meaningful values

#### Actual behavior:

The screen reader reads out all x-axis tick values and then all y-axis tick values.

#### Expected behavior:

The screen reader skips reading out the x-axis tick values and then all y-axis tick values.

**Comment by paulgildea** [comment]
@shandysulen Thanks for filing this issue! We'll look into it.
