### ISSUE TITLE
Cannot set callouted dropdown position only on top and bottom from input

### ISSUE THREAD

**Issue by wojciek** [microsoft/fluentui#15950]
#### Describe the feature that you would like added

Current Dropdown component only have the responsiveMode props which decides in what shape it is presented the toggled dropdown. If i have for example 500 elements in dropdown then the list always is showing in right side of input control. I want to decide about this. Now i need to set toggling only top and bottom dropdown list. I present my proposal with is keeping the settings for responsive props.

#### What component or utility would this be added to

```
<Dropdown
...props
calloutMode={CalloutMode.TopAndBottom}
/>

export enum CalloutMode {
FullResponsive= 'FullResponsive',
TopAndBottom = 'TopAndBottom',
Top = 'Top',
Bottom = 'Bottom',
Left='Left',
Right = 'Right',
}
```

#### Additional context/screenshots
![image](https://user-images.githubusercontent.com/27847393/99282163-a31d9480-2833-11eb-8e45-f3f415f1fa0b.png)
![image](https://user-images.githubusercontent.com/27847393/99282658-466ea980-2834-11eb-8dfb-e7d90a87d456.png)

**Comment by paulgildea** [comment]
@wojciek Thanks for filing this issue.

I’ll mark this as a feature request and add it to our backlog, but to set expectations - we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. We'll take this into consideration when we converge the `Dropdown` component across our two React packages.

Just to ensure I got the request, you'd like to be able to provide positional hints to where the `ContextualMenu` of the `Dropdown` is positioned?
