### ISSUE TITLE
A11y insights: Required ARIA children, parent role not present in command bar

### ISSUE THREAD

**Issue by herambmathkar** [microsoft/fluentui#15969]
### Environment Information

- **Package version(s)**: 7.121.7
- **Browser and OS versions**: Chrome, MacOS Catalina 10.15.6

### Describe the issue:
 When the accessibility insights tool is run on the page with fabric command bar it shows error that ARIA children, parent role are not present in command bar

### Please provide a reproduction of the issue in a codepen:
Got to fabric portal for the given package version
Go to Command bar examples
Run a11y insights

#### Actual behaviour:
A11y insights shows errors in command bar

#### Expected behaviour:
A11y insights shows no errors in command bar

**Comment by paulgildea** [comment]
Dupe of #14805, Fixed in #15535
