### ISSUE TITLE
React-Northstar: Panel Control

### ISSUE THREAD

**Issue by DaleyKD** [microsoft/fluentui#15960]
#### Describe the feature that you would like added
Currently trying to write a Teams app, and needing a Panel control, just like in Fluent UI.

https://developer.microsoft.com/en-us/fluentui#/controls/web/panel

#### What component or utility would this be added to
The entire React Northstar suite.

#### Have you discussed this feature with our team, and if so, who
No

**Comment by paulgildea** [comment]
@DaleyKD Thanks for filling this issue.

@jurokapsiar / @JustSlone FYI.

**Comment by DaleyKD** [comment]
I appreciate it.  If I knew how to write React components, especially like yours, I'd try to help out, especially since it looks like it'd a modification of the Portal and/or Dialog.

For TODAY'S needs, I'm kinda hackin' away at using some bits and pieces from both a Portal and Dialog.  It's rough, but it'll suffice until an official control is released.

**Comment by DaleyKD** [comment]
I was able to piecemeal parts from the Portal examples and the Dialog source code (ish) to come up with a very rudimentary (and not very reusable) control for our needs.  This is an example:
![image](https://user-images.githubusercontent.com/7206282/99688089-03d2ea00-2a4b-11eb-836b-e6acaf0a2733.png)

**Comment by DaleyKD** [comment]
I mean... this issue shouldn't be closed.  Can we reopen it?
