### ISSUE TITLE
Date picker not honoring aria label provided

### ISSUE THREAD

**Issue by lju** [microsoft/fluentui#15978]
### Environment Information

- **Package version(s)**: All
- **Browser and OS versions**: Windows 10, all browsers

### Describe the issue:

Title / aria labels on the due date picker month header button and days on the calendar aren't showing up on hover.

### Please provide a reproduction of the issue in a codepen:

Reproes in the example on the fluent site: https://developer.microsoft.com/en-us/fluentui#/controls/web/calendar

#### Actual behavior:

No label on the button
![image](https://user-images.githubusercontent.com/3344951/99588740-e72da800-299f-11eb-851e-3d58774bb02d.png)

Other buttons have labels
![image](https://user-images.githubusercontent.com/3344951/99588685-d41ad800-299f-11eb-8fd8-935af369e80a.png)

#### Expected behavior:

Expect the given label to show up on hover.

**Comment by paulgildea** [comment]
@lju Thanks for the filing this issue.

I just checked the Inline Calendar with overlaid month picker when header is clicked sample from the [documentation](https://developer.microsoft.com/en-us/fluentui#/controls/web/calendar): 
![image](https://user-images.githubusercontent.com/33229964/99839289-4ebe3180-2b1f-11eb-94b3-08688f7ad47c.png)

And it appears that setting the aria-label when the header is a button

One thing I've noticed it that it's not using the defined string.

@behowell can you work with @lorejoh12 to determine is this is an issue?
