### ISSUE TITLE
Tooltiphost keeps getting dismissed when hovering over tooltip and back to button

### ISSUE THREAD

**Issue by Gustavogbs** [microsoft/fluentui#15975]
### Environment Information

- **Package version(s)**: 7.146.0
- **Browser and OS versions**:  Chrome/Win 10

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/tooltiphost-test-forked-5xsbj?file=/src/App.tsx

#### Actual behavior:

 Tooltip host keeps getting dismissed when mouse goes over host and element that triggers the host. This happens when isBeakVisible is false. There is something transparent that is rendered and covers my button, making the actions/styles of the button also messed up

#### Expected behavior:

Mousing over element and tooltip should never dismiss tooltip

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
OWA

**Comment by paulgildea** [comment]
@Gustavogbs Thanks filing an issue and providing a repo. We really appreciate it. We'll take a look.
