### ISSUE TITLE
Details Pane tabs are not getting activated through keyboard with narrator.

### ISSUE THREAD

**Issue by irumgodil** [microsoft/fluentui#15989]
### Environment Information

- **Package version(s)**: 

 "name": "office-ui-fabric-react",
  "version": "7.135.0",
- **Browser and OS versions**: Chrome/Windows

### Describe the issue:

In using MACDetailPanelV2Wrapper, when tabbing through pivots and pressing enter, it works fine to open the new tab. however, when narrator is open and user tabs and presses enter, nothing happens. 

This is because the role for tab = 'tab' instead of 'button'. 

I have tried overriding this issue by providing custom role: button below, but this property is not getting picked up, even when the arialabel is picked up

  pivotItemProps: {
        headerButtonProps: {
          role: 'button',
          ariaLabel: 'hello'
        }

#### Actual behavior:

Tabbing on pivots with narrator is not working
#### Expected behavior:

Tabbing on pivots with narrator should work.

**Comment by paulgildea** [comment]
@irumgodil Thanks for filing this issue. Our library does not provide a `MACDetailPanelV2Wrapper` component. 

Feel free to reach out to me on Teams if you need more help tracking down this component.

**Comment by irumgodil** [comment]
Ultimately it is details pane v2 that is used underneath. So, the problem is there mainly.

Thanks.

Sent from my iPhone

On Nov 20, 2020, at 3:38 PM, Paul Gildea <notifications@github.com> wrote:

﻿

@irumgodil<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Firumgodil&data=04%7C01%7Cigodil%40microsoft.com%7C94d9d320ba4f4be5fec808d88d8bda77%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637414979098710166%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6VIzO106eXhVaKP7meYYqwGUujBj4JlvqaZlnEU5bPk%3D&reserved=0> Thanks for filing this issue. Our library does not provide a MACDetailPanelV2Wrapper component.

Feel free to reach out to me on Teams if you need more help tracking down this component.

**Comment by irumgodil** [comment]
+ Mason – it went to wrong alias.

Thanks.
