### ISSUE TITLE
Documentation: CommandBar has wrong example code

### ISSUE THREAD

**Issue by martin-braun** [microsoft/fluentui#15988]
The documentation shows wrong examples for [Web -> CommandBar](https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar). In those examples the deprecated `text` prop is still used, but the text need to be put in the `name` prop instead, see https://github.com/microsoft/fluentui/issues/5602#issuecomment-426588133.

**Comment by paulgildea** [comment]
@martin-braun Thanks for filing this issue. We'll take a look.

**Comment by ecraig12345** [comment]
@martin-braun Which package version are you using? `text` is the correct prop name in 6, 7, and 8. `name` only appears to be used in version 5.

If you're using an older version of the package, you should be sure to look at the corresponding version of the doc site--there's a version switcher on the homepage.
![image](https://user-images.githubusercontent.com/5864305/100034658-8512df80-2db1-11eb-9a38-b618ebfeebf1.png)

**Comment by martin-braun** [comment]
Hi @ecraig12345, thank you, you are right, I was looking at the wrong version of the documentation.
