### ISSUE TITLE
NVDA/Jaws is not reading the suggested tags text after opening the tag picker control.

### ISSUE THREAD

**Issue by Sandhya-aluri** [microsoft/fluentui#15995]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^7.126.0",
- **Browser and OS versions**: Chrome and EDGE , Windows 10

### Describe the issue:
On opening the tag picker , nvda/jaws is not reading the suggested tags on the top.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/sandhya-aluri/pen/MWeqYgd?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F

#### Actual behavior:
On opening the tag picker , nvda/jaws is not reading the suggested tags on the top.

#### Expected behavior:
On opening the tag picker , nvda/jaws should read the suggested tags on the top without the focus
<img width="411" alt="tagpicker1" src="https://user-images.githubusercontent.com/48669559/99645277-04807600-2a75-11eb-8167-6871f767cb23.PNG">
.

**Comment by paulgildea** [comment]
@Sandhya-aluri Thanks for filing this issue.

@smhigley FYI.
