### ISSUE TITLE
Office Fabric UI in angular

### ISSUE THREAD

**Issue by Shraddha-113** [microsoft/fluentui#15996]
Hi,

we are developing web application with angular language and we want to use fluent UI/Office fabric UI in that to get CRM like look. We check on internet but we are not getting any official site for same.

Below are the link that show office fabric UI in angular

https://bettersolutions.com/javascript/fluent-ui/components-angularjs.htm
https://www.concurrency.com/blog/august-2016/custom-sharepoint-form-using-office-ui-fabric-and
https://embed.plnkr.co/qmKcnS/

Can anyone suggest me some site or way for same.

Thanks

**Comment by paulgildea** [comment]
@Shraddha-113 Thanks for filing this issue.

Currently we do not provide a fully supported version of Fluent UI with Angular. To set expectations, it is not on our roadmap at this time as our main focus of this library is to converge on a common UI library for React customers.

Sorry I can't be of anymore help at this time. Thanks!
