### ISSUE TITLE
Card in @fluentui/react/lib/next default styling is not rendering

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui#16010]
### Environment Information

- **Package version(s)**: @fluentui/react-cards@1.0.0-beta.17
- **Browser and OS versions**: Edge

#### Actual behavior:

The following code sample:
```
import { Card, CardProps, CardHeader, CardBody, CardFooter } from '@fluentui/react-cards/lib/next';

...

return (
    <ThemeProvider>
      <Card size="medium">
        <CardHeader>Header</CardHeader>
        <CardBody>Card Body</CardBody>
        <CardFooter>Footer</CardFooter>
      </Card>
    </ThemeProvider>
  );
```

Renders the following:
![image](https://user-images.githubusercontent.com/33229964/99732370-3f35de80-2a74-11eb-90ec-1d1be3353088.png)

#### Expected behavior:

Card is rendered with default styling.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
This is going to be folded into a general `Card` convergence issue.
