### ISSUE TITLE
[v8] [Regression] SearchBox maximum call stack size on keydown

### ISSUE THREAD

**Issue by richardkooiman** [microsoft/fluentui#16027]
### Environment Information

- **Package version(s)**: @fluentui/react 8.0.0-beta.17

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/searchbox-maximum-call-stack-size-on-keydown-odjc7
1. Type something in the search box.
2. The error occurs.

#### Actual behavior:
- An error occurs on typing in the search box.
Error: Maximum call stack size because of function calling itself.
Cause: Recent refactoring of the Searchbox component when it got moved to the @fluentui/react-internal library. (https://github.com/microsoft/fluentui/commit/6a007733fedfc986e81993cba67418e1b62db8a0#diff-edf3df7a05914bc2ed8ef8e588c4c835115f7751c82b0fce09ab73a4eeee8419L198-R143)

#### Expected behavior:
- No error occurs.
- Passed onKeyDown callback runs on keyDown event.

### Priorities and help requested:

Are you willing to submit a PR to fix? **Yes**

Requested priority: **Blocking** (for v8 official release)

Products/sites affected: **Test environment of a new product** (no rush)

**Comment by paulgildea** [comment]
@richardkooiman Thanks for filing this issue!

@behowell Please coordinate on the PR. Thanks!
