### ISSUE TITLE
Inline Calendar Narrator Issue

### ISSUE THREAD

**Issue by lju** [microsoft/fluentui#16030]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: Edge and Windows

### Describe the issue:

While navigating through the inline calendar using caps +arrow keys, narrator is announcing all the dates twice as the keyboard & narrator focus is not in sync

### Please provide a reproduction of the issue in a codepen:

Reproes in the example on the fluent website.

#### Actual behavior:

While navigating through the inline calendar using caps +arrow keys, narrator is announcing all the dates twice as the keyboard & narrator focus is not in sync

#### Expected behavior:

Narrator & keyboard focus should be in sync and the dates should be announced once on while navigating through it using caps+arrow keys

**Comment by paulgildea** [comment]
@lju Thanks for filing this issue.

@behowell Please follow up with @lorejoh12 to see if this is a known issue or a Narrator issue. Thanks!
