### ISSUE TITLE
IconButton/ CommandButton menus do not close when invoked twice in safari

### ISSUE THREAD

**Issue by annajo1** [microsoft/fluentui#16031]
### Environment Information

- **Package version(s)**: 7.146.0, 7.152.1, (that I checked)
- **Browser and OS versions**: Safari version 14

### Repro:
**In safari,** 
1. click the IconButton or the CommandButton
2. click the button again

[link to demo](**https://fabricweb.z5.web.core.windows.net/oufr/7.152.1/#/examples/button**) https://fabricweb.z5.web.core.windows.net/oufr/7.152.1/#/examples/button

#### Actual behavior:
The button re-opens the menu on the second click

#### Expected behavior:
The button should close the menu on the second click

### Priorities and help requested:

Are you willing to submit a PR to fix?  No

Requested priority:Normal

Products/sites affected: OWA

**Comment by paulgildea** [comment]
@annajo1 Thanks for filing this issue.
