### ISSUE TITLE
onMouseDown property of IContextualMenuItem has wrong method signature

### ISSUE THREAD

**Issue by ehmPlankje** [microsoft/fluentui#16039]
### Environment Information
- **Package version(s)**: @fluentui/react@7.150.1
- **Browser and OS versions**: Windows 10 Pro 2004

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/ehmplankje/pen/dyXBmjO

#### Actual behavior:
The `onMouseDown` property only contains 1 function argument, which is an event of type  `React.MouseEvent<HTMLElement>`.

#### Expected behavior:
According to the documentation of `IContextualMenuItem` the property `onMouseDown` should provide 2 arguments: `item: IContextualMenuItem, event: React.MouseEvent<HTMLElement>`

Screenshot from https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu
![image](https://user-images.githubusercontent.com/3234834/99883122-8b745080-2c25-11eb-8686-8df79ce7fdb7.png)

### Priorities and help requested:
Are you willing to submit a PR to fix? Yes
Requested priority: Low
Products/sites affected: Fabric UI React

**Comment by paulgildea** [comment]
@ehmPlankje Thanks for filing this issue, providing a codepen, and contributing the fix.

@behowell Please coordinate with @joschect and @ehmPlankje on submitting a PR for this issue.
