### ISSUE TITLE
Choice group focus jump over options in Narrator scan mode

### ISSUE THREAD

**Issue by ipip2005** [microsoft/fluentui#16038]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: Edge chromium + Windows 10

### Describe the issue:

In Narrator scan mode + Edge, press down arrow key will move 2 options instead of 1, screen reader user might miss options during navigation.

### Please provide a reproduction of the issue in a codepen:

This repros with Fabric demo page https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup
1. Find the control in below screenshot
![image](https://user-images.githubusercontent.com/7711735/99862717-9f4d8300-2b4f-11eb-9b67-b7932bcc152c.png)

2. Focus on the "Show code" button.
3. Turn on scan mode of Narrator using Caps + spacebar until "scan" is announced. (It reads "scan off" if scan mode is turned off)
4. Press down arrow key to focus on the first option in the choice group
5. Press down arrow key again.

#### Actual behavior:

Focus jump to 3rd option

#### Expected behavior:

Focus jump to 2nd option

### Documentation describing expected behavior

MAS Reference:
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={b24201d1-2276-4471-8183-e1e5353031ad}

**Comment by paulgildea** [comment]
@ipip2005 Thanks for filling this issue and providing great repo steps. We'll take a look.

**Comment by ipip2005** [comment]
Hi, just check-in to see the progress/schedule so we can update ETA in our internal backlog.

**Comment by ipip2005** [comment]
@paulgildea Is there any updates?

**Comment by behowell** [comment]
Hi @ipip2005, I just took a look into this.

It appears that is happening because the item's icon sets `aria-hidden="true"`. If I delete that prop, then narrator works properly in this scenario. I'm not sure why aria-hidden would cause Narrator to skip over the next item after it, but it seems like it could be a bug in Narrator...

As a possible workaround, I tried adding `'aria-hidden': false` to the items' `iconProps` in the example code, and it seems to fix this bug:
```ts
const options: IChoiceGroupOption[] = [
  { key: 'day', text: 'Day', iconProps: { iconName: 'CalendarDay', 'aria-hidden': false } },
  { key: 'week', text: 'Week', iconProps: { iconName: 'CalendarWeek', 'aria-hidden': false } },
  { key: 'month', text: 'Month', iconProps: { iconName: 'Calendar', 'aria-hidden': false }, disabled: true },
];
```

I don't think that is the correct long term solution, but you could try adding `'aria-hidden': false` as a temporary workaround for now. Let me know if it works for you.

Meanwhile I'll follow up with the Narrator team to see if this is in fact a bug in Narrator.

**Comment by ipip2005** [comment]
@behowell Thanks for providing the workaround, it looks like after adding `'aria-hidden': false` the issue goes away. Not sure if it will cause any new a11y issues since icons are supposed to be hidden from screen reader? But I'll try this workaround on our side.

**Comment by smhigley** [comment]
I took a deeper look at this, both the browser accessibility tree and the UIA representation. It's not as straightforward as an issue with `aria-hidden`: for example, the "Show Code" button the same page presents with the same issue in scan mode caret navigation. Additionally, Narrator + Edge 89 (Canary, currently) has an entirely different Narrator bug on the same control.

I couldn't find any issues in either the HTML or UIA, and it seems increasingly likely this is a Narrator bug. I'm currently working on creating a repro outside of Fluent that can be submitted to Narrator. The Fluent control itself does not appear to have any semantic issues related to the icon or this Narrator behavior.
