### ISSUE TITLE
Data-interception="off" attributes not applies to <a> tags with target="_blank"

### ISSUE THREAD

**Issue by TheInvoker** [microsoft/fluentui#16041]
I noticed this on the nav element (https://developer.microsoft.com/en-us/fluentui#/controls/web/nav), but this probably applies to all components. But basically as we all know in SP Online, when you add anchor tags, it does fast navigation style loading. Even if you put target="_blank". Problem is with all these controls, even when I pass in { target: "_blank" }, it will apply that to the tag fine, but logically it should also put the data-interception="off" too to complete it, but it does not, and this causes issues. It doesn't even give me a way to put in custom attributes. 

I currently have to wait till it renders in the DOM and the manually update it with javascript which is not a very clean approach.

Why we need this:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking

**Comment by JustSlone** [comment]
Like a seems reasonable request 

@ecraig12345, seems like we have a few choices, which do you think fits best with the purpose/use of Nav?

1. Add a field to NavLink to allow folks to specify a value for data-interception
2. Automatically add data-interception when target="_blank" (not sure I like this option, magic leads to issues/bugs)
3. The other option would be to open up the ability to add arbitrary data attributes to the link
4. Or can we use getNativeProps to allow passing through arbitrary data-* and other attributes through to the link?

**Comment by TheInvoker** [comment]
I was able to solve this using the linkAs property from the nav component. But it meant that I had to rebuild the whole <a> tag from the properties object, all just so that I could add in that custom attribute. Seems rather unnecessary. Personally I would love either option 1 or 3.

PS: if you do this, you also need to execute the provided onClick event on the click event that you have to set a handler on the <a> tag too.
