### ISSUE TITLE
Nav LinkAs not being passed the link data

### ISSUE THREAD

**Issue by TheInvoker** [microsoft/fluentui#16042]
For the nav component  https://developer.microsoft.com/en-us/fluentui#/controls/web/nav when I use the "linkAs" I expect to change the whole default button into something custom. I noticed that it only passes in the ButtonProps data, but I also need the item data for each link. This way I can get access to the url, title, name, target, etc... Is there a way to get this data?

**Comment by ecraig12345** [comment]
From the code, it looks like all the properties you mentioned are being passed in the props to the custom component. Is there something else that you want to be passed through which isn't currently?
https://github.com/microsoft/fluentui/blob/ca4ec134424fbd53ecc726b965d6dbff1fc12bf6/packages/react-internal/src/components/Nav/Nav.base.tsx#L124-L142

**Comment by TheInvoker** [comment]
Thanks, I was now able to figure it out.
