### ISSUE TITLE
Fluent UI v8 compatible issue with Nextjs 10

### ISSUE THREAD

**Issue by oliver-au** [microsoft/fluentui#16044]
### Environment Information

- **Package version(s)**:  `"@fluentui/react": "^8.0.0-beta.18"`, `"@fluentui/merge-styles": "^8.0.0-beta.0"`, `"next": "10.0.2"`
- **Browser and OS versions**: Edge

#### Actual behavior:

1. I create customizing component  with `mergeStyleSets` from `@fluentui/merge-styles`, the css of this component isn't loaded with `npm run dev`, However It's loaded with `npm run start`. The same code with `"@fluentui/react": "^7.150.1"` and `"@uifabric/merge-styles": "^7.19.1"` in `"next": "10.0.2"` works.
Here is the details: [MyStyledComponent](https://github.com/oliver-au/fluent-ui-8-nextjs/blob/master/src/components/MyStyledComponent.tsx)

2. I try to use any fluent UI component in `"@fluentui/react": "^8.0.0-beta.18"`, it'll throw an `TypeError: Cannot read property 'semanticColors' of undefined` error in `_document.tsx`. And it works well in `"@fluentui/react": "^7.150.1"`, `"@uifabric/merge-styles": "^7.19.1"` and `"@uifabric/utilities": "^7.33.2"`.

```
../../pages/_document.tsx (90:33) @ Function.getInitialProps

  88 |     }
  89 | 
> 90 |     const { html, head } = await ctx.renderPage({ enhanceApp })
     |                                 ^
  91 |     const styles = [...flush()]
  92 |     return { html, head, styles }
  93 |   }
```

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: [fluent-ui-8-nextjs](https://github.com/oliver-au/fluent-ui-8-nextjs)

**Comment by JustSlone** [comment]
@oliver-au thanks for pointing this out!

@behowell let's dig into what's going on here. This might be an issue in Version 8, so let's investigate soon

**Comment by xugao** [comment]
@oliver-au - the issue is caused by multiple versions of `@fluentui/utilities` are installed and used in different places of the call stack. You can resolve it by removing `"@fluentui/utilities": "^8.0.0-beta.0",` from your package.json or upgrade it to use `@fluentui/utilities": "^8.0.0-beta.6"`.
