### ISSUE TITLE
Documentation: TextField missing onChanged event

### ISSUE THREAD

**Issue by martin-braun** [microsoft/fluentui#16048]
The documentation of the [TextField web component](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield) has an outdated member list:

- The _onChange_ event has only one argument, the _newValue_ argument is not passed, anymore. In fact, this event is never called and should be removed from the member list, maybe.
- The _onChanged_ event is not listed, it will be called when the value has been changed, instead. It passes only one argument, which is _newValue_.

**Comment by ecraig12345** [comment]
When you say "web component" do you mean the TextField exported from `@fluentui/web-components`, or `@fluentui/react`? The documentation you linked is specific to `@fluentui/react` and is correct as of version 7.

**Comment by martin-braun** [comment]
> When you say "web component" do you mean the TextField exported from `@fluentui/web-components`, or `@fluentui/react`? The documentation you linked is specific to `@fluentui/react` and is correct as of version 7.

Hi @ecraig12345, thank you for investigating, it seems I was in the wrong version of the documentation, since I'm building an SPFX WebPart targeting SP2016. I apologize.
