### ISSUE TITLE
Type definition for component variables

### ISSUE THREAD

**Issue by spjtls9** [microsoft/fluentui#16047]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.51.2

Code sandbox: https://codesandbox.io/s/vibrant-khorana-q76v0?file=/src/App.tsx

The official document states to prefer `variables` over `styles`. In my project we tried to follow that and found that isn't so easy given that there is no strong type definition for each component's variable slot. 

In the above codesandbox, I added `variable={{ color : "purple" }}` to a `Text` component. `TextVariables` doesn't have `color` variable; however, there is no compiler error/warning to note that. I'd expect that each `variable` slot has type defined in the `d.ts` file, so the compiler knows which `variables` are allowed for the component.

I also saw that the interface for each variable's component are defined in `theme` folder. As a temporary workaround for my project, I've added `patch-package` to set `variable` definition to the respective type, and export the type, to support use cases like this:

```
import { Segment, SegmentStylesProps, SegmentVariables, SiteVariablesPrepared, Text } from "@fluentui/react-northstar";

const variables = ({ colorScheme }: SiteVariablesPrepared): Partial<SegmentVariables> => ({
            backgroundColor: colorScheme.brand.background1
        });

        return (
            <Segment
                variables={variables}
            >
                <Text weight={"semibold"}>
                    {this.props.children}
                </Text>
            </Segment>
        );
```

### Priorities and help requested:

I am willing to submit a PR - I also want to know if these are intentionally left out and if there is any historical context.

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@jurokapsiar gentle ping and updating the status :-)

**Comment by spjtls9** [comment]
Any updates on this? We want to update to the newer version however we have not yet since  that will break the patch file (it requires another manual update to the patch)

**Comment by Zenulous** [comment]
I agree with the reasoning behind this issue. The current state of affairs makes it demotivating to use variables compared to styles (especially when starting out, since the difference is quite ambiguous without typings...). Plus, as mentioned here, a lot of types have already been worked on in the themes themselves (`I also saw that the interface for each variable's component are defined in theme folder`).

**Comment by spjtls9** [comment]
With the patch file applied, this is what `<Text />` component looks like.

```
import { TextVariables } from '../../themes/teams/components/Text/textVariables';

export interface TextProps
  extends UIComponentProps,
    ContentComponentProps,
    ChildrenComponentProps,
    ColorComponentProps {
  /**
   * Accessibility behavior if overridden by the user.
   */
  accessibility?: Accessibility<never>;

  /** At mentions can be formatted to draw users' attention. Mentions for "me" can be formatted to appear differently. */
  atMention?: boolean | 'me';

  /** Set as disabled Text component */
  disabled?: boolean;

.
.
.

  /** Set as timestamp Text component */
  timestamp?: boolean;

  /** Truncates text as needed */
  truncated?: boolean;

  variables?: TextVariables;
}
```

Note `variables` type is overwriting the inherited one (`ComponentVariablesInput`).

The new version  (0.54.0) has fixes that we want for accessibility and menu indicator icon, so we are considering updating the version and manually updating the patch. Nonetheless, this is a temporary fix and I do not wish to continue this cycle every time we update the package.

If I publish a PR with these for all the components, will it be accepted? 

From a brief look, it looks like changing the type of `variables` in `StyledComponentProps` could work as well.

```
export interface StyledComponentProps<P = any, V = any> {
  /** Additional CSS styles to apply to the component instance.  */
  styles?: ComponentSlotStyle<P, V>;

  /** Override for theme site variables to allow modifications of component styling via themes. */
  variables?: V // changed from ComponentVariablesInput;
}
``` 

It would be awesome to get some guidance here.

**Comment by jurokapsiar** [comment]
Hi,

this is currently not in scope as variabels are designed to be dynamic (users can build theme layers that merge). I understand that the typings might be useful for basic scenarios - even if not ideal, you could add the typings using patches, for example using patch-package in your local environment.
