### ISSUE TITLE
Docs enhancement request for PeoplePicker

### ISSUE THREAD

**Issue by priyankark** [microsoft/fluentui#16056]
#### Describe the feature that you would like added

This is more of a request based on my experience as a beginner. Please feel free to close this issue if it isn't going to be a priority and apologies for that.

It would be really useful if there was a template in the doc that you could just copy paste over which had an example for how to fetch the people details using a network call and map results to the needed persona props. The current examples use the person details from examples and the example code seemed pretty convoluted. It required a lot of editing to get something like this working. I saw there was a past issue where someone else had a similar request but it was closed by them without a reply.  [Similar Issue](https://github.com/microsoft/fluentui/issues/948)

Also some things like how do you have handlers for adding and removing people (using onChange vs onItemSelected) weren't really clear from the docs and had to rely on past Github issues to know what to use where.

#### What component or utility would this be added to

PeoplePicker

#### Have you discussed this feature with our team, and if so, who

Not yet

**Comment by JustSlone** [comment]
@priyankark thanks for the feedback! 
You are absolutely right that an example showing how people picker connects to a network call would be valuable. This traditionally has been beyond the scope of Fluent UI React documentation, but this may change in the future. I don't think we'll get time to jump on this soon though ☹️. 

If you have a good example for how to do this that you'd like to contribute we'd be happy to review it and that would be a great thing to add to the documentation. The same goes for clearing up the confusion you had around onChange vs onItemSelected.

**Comment by priyankark** [comment]
@JustSlone Thanks a lot for your response! I would love to be able to contribute! Will try to raise a PR soon.

**Comment by JustSlone** [comment]
Simple instructions to run the website are (CC: @ecraig12345 incase she has better instructions): 
- build using `yarn build` in `/`
- run `yarn start` in `/apps/public-docsite/` 
- editing files in `/react-examples/src/react/Pickers/` should modify the examples/docs

If you hit an issues let us know

**Comment by ecraig12345** [comment]
While I agree this could be a good example to have, there are some issues to work through for practically how to demonstrate it within our current website.
- Where should the data be fetched from? We certainly don't want to add a real server and API somewhere just for this example. Some ideas:
  - Add a JSON file somewhere (there are a couple ways we could pretty easily do this) and fetch the file. Downside is that's less realistic.
  - Look for a service which provides an API for fetching fake people names and images, then convert that to the format expected by the people picker. Downside is this is more complex and adds a dependency on a 3rd-party service which might change or stop working at any time.
- How should the data be fetched? I'd probably suggest the built-in `fetch` API, just be sure to include a comment in the code that this method requires a polyfill in IE 11. (We happen to already include a general polyfill in our doc site which will handle this.)

For development, you should be able to work on the example the standard way in storybook starting out, without a full build. Copy and rename one of the existing example files under `packages/react-examples/src/react/PeoplePicker`, then run (from the repo root) `yarn` followed by `yarn start` and choose `@fluentui/react`.

To get the example to actually show up on the website, you'll need to add it in `packages/react-examples/src/react/PeoplePicker/PeoplePicker.doc.tsx`. To test that you can run (from the repo root) `yarn start` and choose either `@fluentui/public-docsite-resources` (the legacy demo app) or `@fluentui/public-docsite` (the full website).

**Comment by priyankark** [comment]
@ecraig12345 Thanks a lot for your suggestions!
In our codebase we are using the JSON file approach for development purposes and a mock server which serves the JSON files (we are using a simple express server but there are vs code extensions that can serve the JSON files over localhost). That's one idea but it will still require some setup from the user end. The second approach as you rightly mentioned will create an unnecessary dependency on a third party service.

I had a different suggestion in mind for the sake of documentation. My thought was to create a small utility which would mimic fetch's spec and serve sample JSON (similar to [fetch mock](https://www.npmjs.com/package/fetch-mock)) It won't really be making a network call but users making API calls using fetch should be able to copy the example over and get making API calls working with minimal edits. Do let me know your thoughts if this makes sense!
