### ISSUE TITLE
React Northstar: Add Labelling to Dropdown 

### ISSUE THREAD

**Issue by marwalsch** [microsoft/fluentui#16068]
#### Describe the feature that you would like added

Give the Dropdown component the same or similar labelling options as the Input component might be helpful.

A Dropdown might be used as a more restrictive Input field but is hard to align properly if actual input fields are labelled (specifically when using `labelPosition="inside"`. 

Desired behaviour:

```
    <Dropdown
        label="Pick a Day"
        labelPosition="inside"
        (...)
     />
```
Would result in a slightly thicker Dropdown field as it does with the input fields in below screenshot

#### What component or utility would this be added to

`<Dropdown>`

#### Additional context/screenshots

![Screenshot 2020-11-25 103731](https://user-images.githubusercontent.com/72074423/100210931-d0d99c00-2f0b-11eb-8381-a7f50f6c8298.jpg)
Above property calls should display "Pick a Day" above the date.

**Comment by jurokapsiar** [comment]
Hi, Form.Dropdown is meant for that - it combines label and a dropdown. Currently, only two-line design is supported and we will be adding inline soon.

https://fluentsite.z22.web.core.windows.net/0.51.4/components/form/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#variants-components

(see #16468)
