### ISSUE TITLE
Coherence across different platform for fluent UI controls

### ISSUE THREAD

**Issue by atishayv** [microsoft/fluentui#16069]
#### Describe the feature that you would like added
The fluent ui controls across different platform are not exactly the same. For ex : If you look at **Basic Inputs supported in Android** by fluent ui 
![image](https://user-images.githubusercontent.com/13940020/100209575-0e502080-2f30-11eb-9c9e-c5ab8fae69c7.png)
 which is a **lot less when compared with Web** : 
![image](https://user-images.githubusercontent.com/13940020/100210122-9fbf9280-2f30-11eb-9464-4e507deefa9a.png)

Is there a plan to make all controls same across different platforms ? 

Also, I see there is a "Cross platform" control added in fluent ui. Is it a step towards the same ?
![image](https://user-images.githubusercontent.com/13940020/100210505-13619f80-2f31-11eb-8273-7eb552162aee.png)

#### What component or utility would this be added to
Not applicable

#### Have you discussed this feature with our team, and if so, who
No

**Comment by atishayv** [comment]
CC : @jaisanth, @dclaux

**Comment by JustSlone** [comment]
The short answer is yes this is something we're working towards. For the long answer I'll hand off to @paulgildea (also we might want to convert this to a discussion).

**Comment by atishayv** [comment]
@JustSlone Thanks for the update. When you say were working towards it, does it mean that we are creating all these elements for other platforms or we are going with cross platform react native approach ? 
Also, I know its a big task, but can you give me an idea on whats the timeline for the same ?

**Comment by JustSlone** [comment]
Fluent UI has a goal of enabling customers to build using whatever platform they need. So this means iOS, Android, Web Components, React, and React Native. 

Some platforms overlap, such as iOS/Android, with React Native as well as React and Web Components. That being said there are valid reasons to choose one platform or approach over the other, we see real reasons in the apps we build and others see the same. So we don't prescribe one platform over another and instead are working to bring Fluent UI to all the relevant platforms letting folks choose the best platform for their needs.

I hope that adequately answers your question, also this doesn't speak to broader strategy beyond Fluent UI. 

As for timeline, I don't have anything available offhand, it might be best to ask about android over here: https://github.com/microsoft/fluentui-android

**Comment by atishayv** [comment]
Thanks for the info @JustSlone

**Comment by paulgildea** [comment]
@atishayv Just wanted to touch base here to see if we've answered some of your questions.

**Comment by atishayv** [comment]
Yes.. Thanks for the information.

**Comment by JustSlone** [comment]
Closing out, cheers!
