### ISSUE TITLE
Northstar Menu: Coupled Pane to MenuItem

### ISSUE THREAD

**Issue by DaleyKD** [microsoft/fluentui#16065]
#### Describe the feature that you would like added
Similar to the Pivot for Fluent UI (or the Tabs for Bootstrap), when using the Menu as tabs, it'd be a lot easier if we could couple/marry the MenuItem to a Pane, just like Pivot does (see context below).  This would alleviate the pain of us manually hoking into the onActiveIndexChange and trying to do a `switch` ourselves.

#### What component or utility would this be added to
Menu (https://fluentsite.z22.web.core.windows.net/0.51.3/components/menu/definition)

#### Have you discussed this feature with our team, and if so, who
No

#### Additional context/screenshots
https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot
```jsx
export const PivotBasicExample: React.FunctionComponent = () => {
  return (
    <Pivot aria-label="Basic Pivot Example">
      <PivotItem
        headerText="My Files"
        headerButtonProps={{
          'data-order': 1,
          'data-title': 'My Files Title',
        }}
      >
        <Label styles={labelStyles}>Pivot #1</Label>
      </PivotItem>
      <PivotItem headerText="Recent">
        <Label styles={labelStyles}>Pivot #2</Label>
      </PivotItem>
      <PivotItem headerText="Shared with me">
        <Label styles={labelStyles}>Pivot #3</Label>
      </PivotItem>
    </Pivot>
  );
};
```

**Comment by jurokapsiar** [comment]
Hi, this is not planned as the scope of Menu is too big already. You can achieve similar behavior by combining other components.

**Comment by DaleyKD** [comment]
That's a shame. I was really hoping we were going to try and improve upon the Northstar library and make it more similar to the Fluent UI.  At this point, it's a small subset of Fluent UI and just not there yet.
