### ISSUE TITLE
Detail list is not working when zoom level is 80%, and user tries to scroll to the bottom of the list

### ISSUE THREAD

**Issue by kamal-pandey** [microsoft/fluentui#16070]
Environment Information

- **Browser and OS versions**: Chrome all versions

#### Actual behavior:

We have created a PCF Control using detail list, we have used sticky to freeze the header and footer(for navigation and Pagination)... When zoom level of browser is 80% and we scroll in the grid towards the end, screen goes blank and we get the below error.

![error description](https://user-images.githubusercontent.com/11170597/100228500-cb4e7700-2f48-11eb-9dc6-3eb39206926b.jpg)

![Issues with PCF Control](https://user-images.githubusercontent.com/11170597/100228186-4f542f00-2f48-11eb-8f84-a886cf57cac3.jpg)

Below is the error Text: 

invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

#### Expected behavior:

Grid should work for all browser zoom levels.

Requested priority: Normal

Products/sites affected: Dynamics 365 Custom Controls Using fluent UI

**Comment by JustSlone** [comment]
@kamal-pandey hmm, I can't repro this our DetailsList examples here: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist

Can you share a repro CodePen that repros this with DetailsList?

CC: @ThomasMichon
