### ISSUE TITLE
Details Pane tabbing not working.

### ISSUE THREAD

**Issue by irumgodil** [microsoft/fluentui#16094]
Hi,

I am reactivating this issue as the problem really is in DetailPaneV2, which is under fluent_ui. Please let me know if you need more info. 

Thanks.

_Originally posted by @irumgodil in https://github.com/microsoft/fluentui/issues/15989#issuecomment-731379754_

**Comment by JustSlone** [comment]
@irumgodil thanks for reaching out!

Actually I'm pretty sure DetailPaneV2 is provided from the Admin controls set of components. You can find more info and a link to the repo over here: https://aka.ms/admincontrols

Thanks!

**Comment by irumgodil** [comment]
Thanks.
