### ISSUE TITLE
linechart hover callout data not correct calloutData

### ISSUE THREAD

**Issue by FdjNL** [microsoft/fluentui#16091]
### Environment Information

- **Package version(s)**: "@fluentui/react-charting": "^5.0.0-beta.0"
- **Browser and OS versions**: all
#### Actual behavior:

callout data title is incorrect on last data point 
if the xAxisCalloutData is set the last datapoint renders the title of the one before

Edited the linechartBasicExample and set a custom xAxisCalloutData for each datapoint
` {
              x: new Date('2020-03-08T00:00:00.000Z'),
              y: 300000,
              xAxisCalloutData: "not the last data point",
              onDataPointClick: () => alert('click on 300000'),
            },
            {
              x: new Date('2020-03-09T00:00:00.000Z'),
              y: 218000,
              xAxisCalloutData: "last data point",
              onDataPointClick: () => alert('click on 218000'),
            },`

![Screenshot 2020-11-30 121927](https://user-images.githubusercontent.com/12933575/100612657-9d37b100-3313-11eb-9a5c-2cb17a734944.png)
![Screenshot 2020-11-30 122027](https://user-images.githubusercontent.com/12933575/100612661-9dd04780-3313-11eb-8de6-baf8997d8305.png)

#### Expected behavior:

Rendering of the set xAxisCalloutData when hovering last data point

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: @fluentui/react-charting

**Comment by JustSlone** [comment]
@FdjNL thanks for the issue! Can you throw together a quick CodePen with the repro? It makes it much easier to confirm repro if so. 

@Raghurk FYI there might be an issue in react-charting 5.0.0-beta

**Comment by FdjNL** [comment]
@JustSlone  @Raghurk 
made a CodePen that reproduces the bug 


https://codepen.io/fdjnl/pen/rNMxBKg

**Comment by VasudhaAvuthu** [comment]
@JustSlone , I also encountered this issue today. Is any PR raised fixing this bug?

**Comment by JustSlone** [comment]
I reached out to @Raghurk to see if he's available to take a look at this. Otherwise, I would guess that this issue is probably some kind of off by one error and wouldn't be too difficult to fix. If someone wants to dive into the code and see if a fix is straightforward that would help get this fixed sooner.

**Comment by Raghurk** [comment]
Thank you for reporting, we will be taking a look at this.

**Comment by Raghurk** [comment]
Issue is fixed, please test it with the latest package

**Comment by VasudhaAvuthu** [comment]
Thanks for the quick fix @Raghurk.
