### ISSUE TITLE
Documentation: Include Fabric component in all examples

### ISSUE THREAD

**Issue by trung2012** [microsoft/fluentui#16110]
Hello,

I ran into a problem where an element in focus does not show an outline, causing an accessibility bug. I found out later that I needed to use the Fabric component. I saw that https://github.com/microsoft/fluentui/issues/1450 and https://github.com/microsoft/fluentui/issues/351 were opened for this problem. However, they were both closed on the same day without any action taken. I could not find this information on the official docs, still. Could someone please add documentation for the Fabric component? Quoting https://github.com/dzearing below:

> We should have documentation for the Fabric component which will:
> 
> Ensure DIR attribute is populated
> Add ms-Fabric-isFocusVisible classname
> We should make is super clear to the user that it is a requirement that they use the Fabric wrapper, or that at minimum they have DIR populated, because otherwise components will look broken when they first try it.

```
const App = () => (
<Fabric>
  { children }
</Fabric>
);
```

Thanks!

**Comment by JustSlone** [comment]
@trung2012, thanks for the feedback. Yes that is a good point about documenting <Fabric/>

The tricky thing here is that I'm not sure where to put it to let folks know that it's important. We could just add a Fabric component to the documentation, but I'm guessing a lot of folks would miss it. 

Where would you expect to have seen this documentation about the <Fabric/> component?

**Comment by ecraig12345** [comment]
The other issue at the moment is that we're attempting to replace Fabric with ThemeProvider starting in version 8. ThemeProvider is also not on the website yet, but you can read about it (and how it replaces Fabric) [here](https://github.com/microsoft/fluentui/blob/master/packages/react-theme-provider/README.md#fabric-component). cc @xugao

**Comment by trung2012** [comment]
Thank you for the responses!

@JustSlone I think most people will go to Getting Started, so having a note there, which says something like "You need to wrap things with the Fabric component..." along with a link to that component's separate documentation, would be helpful. You could also include the Fabric component in the examples of other components with a link. Or maybe have it in its own category with some kind of highlight.

@ecraig12345 If that's the case then I guess it would be your call if this is worth the effort. But it was pretty frustrating for me since I could not find anything related to the issues I had on the docs .

@xugao I was using ChoiceGroup with custom option rendering. I found that I could focus the options, but the outline never showed because the body did not have a ms-Fabric-isFocusVisible added to it when I focus.
