### ISSUE TITLE
Carousel: onActiveIndexChange callback does not provide current active

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#16116]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@jurokapsiar gentle ping on this one. Updating labels.

**Comment by assuncaocharles** [comment]
Fixed by: #16118
