### ISSUE TITLE
Date picker icon and dropdown icon are not properly aligned

### ISSUE THREAD

**Issue by lennertVanSever** [microsoft/fluentui#16127]
### Environment Information

- **Package version(s)**: 4.0.3
- **Browser and OS versions**: Chrome, MacOS Catelina version 10.15 but reproducible on other browsers like Edge Microsoft, Safari, Firefox...

### Please provide a reproduction of the bug in a codepen:

[https://codepen.io/lennertvansever/pen/xxEwvaQ](https://codepen.io/lennertvansever/pen/xxEwvaQ)

#### Actual behavior:

![Screenshot 2020-12-03 at 11 34 04](https://user-images.githubusercontent.com/23064517/100998168-7966ac00-355b-11eb-84a5-511cfc5f7c0b.png)

As you can see from the screenshot ☝️, the datepicker icon and drop down icon are not properly aligned

#### Expected behavior:

![Screenshot 2020-12-03 at 11 38 38](https://user-images.githubusercontent.com/23064517/100998704-25a89280-355c-11eb-8c67-fb3937da7bbd.png)

---

![Screenshot 2020-12-03 at 11 38 31](https://user-images.githubusercontent.com/23064517/100998706-26d9bf80-355c-11eb-8c31-d9213c34152a.png)

By resizing and playing with the margins, the icons can be properly aligned on both sides

I can make a PR if needed

#### Requested priority: (Blocking, High, Normal, Low)

Normal, not urgent

####  Products/sites affected: (if applicable)

all using the date picker/dropdown combination

**Comment by JustSlone** [comment]
@lennertVanSever yep, that's definitely not aligned! Thanks for raising this

I'll reach out to our designers to get a sense for which icon/direction we think we should adjust. This will be a little lower priority and unfortunately would churn a lot of existing UI. We will probably look to fix this in a future design refresh.
