### ISSUE TITLE
FluentButton ARIA property updates not reflected in internal button

### ISSUE THREAD

**Issue by squinto** [microsoft/fluentui#16121]
### Environment Information

- **Package version(s)**: latest

### Describe the issue:

When any ARIA properties are updated in `<fluent-button>`, the internal button does not reflect it. For example, running Storybook and using DevTools to change the `<fluent-button>`'s `aria-label` below:
![image](https://user-images.githubusercontent.com/28632942/100936374-44e4e880-34a6-11eb-84ba-300cb6a26e0e.png)
It can be observed that the internal button doesn't change. Screen readers (tested with Narrator) reads ARIA properties from the internal button. This is a problem when passing in `aria-pressed` or `aria-expanded` properties, since updates on the `<fluent-button>` are not reflected in the internal button, causing incorrect screen readouts for state.

#### Actual behavior:

Internal button's ARIA properties stay the same even with changes to `<fluent-button>`'s ARIA properties.

#### Expected behavior:

Updates to `<fluent-button>`'s ARIA properties should be enumerated on the internal button.

**Comment by EisenbergEffect** [comment]
Some research shows that this is an issue in fast-foundation. I'll be submitting a PR to fix it there shortly.

**Comment by EisenbergEffect** [comment]
This can be closed as fixed in fast-foundation. @chrisdholt
Pending release.
