### ISSUE TITLE
Commandbar menu items appear as normal text in high contrast mode

### ISSUE THREAD

**Issue by Leiquan-Pan** [microsoft/fluentui#16134]
### Environment Information

- **Package version(s)**: office-ui-fabric-react": "7.149.4,
- **Browser and OS versions**: Chrome: "Version 86.0.4240.198 (Official Build) (32-bit)", Windows 10

### Describe the issue:

This bug is reproducable with the example "CommandBar with overflowing menu items" provided on the official dev page.

https://developer.microsoft.com/de-DE/fluentui#/controls/web/commandbar#implementation

#### Actual behavior:

![image](https://user-images.githubusercontent.com/62626336/101103173-fe62bd00-357d-11eb-9482-39a2aeb9d0b6.png)

The menu items' text appear as normal text, which makes it harder to recognize in high contrast mode

#### Expected behavior:

On applying high contrast the buttons like menu items should not appear as normal texts.

### Documentation describing expected behavior

Are you willing to submit a PR to fix? (No)
Requested priority: ( Normal )

**Comment by JustSlone** [comment]
@Leiquan-Pan thanks for filing this issue, but I'm not seeing repro on a [CodePen here](https://codepen.io/justslone-the-encoder/debug/RwGaZrY?editors=0010). There might be some styles on the website referenced above that are causing the 

Here's the codepen:
![image](https://user-images.githubusercontent.com/40304143/101266632-832c1300-3705-11eb-871d-26cd25bc0fb3.png)


Here's the website:
![image](https://user-images.githubusercontent.com/40304143/101266626-73143380-3705-11eb-9a8e-f62919068c03.png)

**Comment by Leiquan-Pan** [comment]
Thank you so much for responding. I think it's not repro on my end now. I will close this issue
