### ISSUE TITLE
Button disabled background & text color properties do not take effect

### ISSUE THREAD

**Issue by idigra** [microsoft/fluentui#16156]
### Environment Information

- **Package version(s)**: 7
- **Browser and OS versions**: Edge Chromium

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/idigra/pen/GRjZXeb

#### Actual behavior:

When disabled, buttons background color is set to the default background color of disabled button.

#### Expected behavior:

When disabled, buttons background color is expected to be set to the color passed to loadTheme function in properties semanticColors.buttonBackgroundDisabled and semanticColors.primaryButtonBackgroundDisabled.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Excel

### Comments:

1. I found an issue that might be related. It doesn't seem like duplication as this issue is much simpler and deals with the classic case of disabled buttons (I just used the demo sample from the site with minimal modifications to demonstrate use of buttonBackgroundDisabled properties) - not like the other bug which is specific to high contrast mode:
https://github.com/microsoft/fluentui/issues/16125
2. I used the definition of semantic overrides as defined here: https://docs.microsoft.com/en-us/javascript/api/theme/isemanticcolors?view=office-ui-fabric-react-latest#primaryButtonBackgroundDisabled
3. The issue occurs also for primaryButtonTextDisabled.

**Comment by paulgildea** [comment]
@idigra Thanks for filling this issue and finding other potential issues as well. That's super helpful.

@ecraig12345 Let's root cause this issue. Thanks!

**Comment by idigra** [comment]
I found that the issue occurs also for primaryButtonTextDisabled - I editted the issue accordingly.
I'll be grateful to know if there's a plan to fix (or investigate) the issue?

**Comment by KalapJo1** [comment]
Even I found the same issue with disabled selector styles on the button in high-contrast and normal modes. Is there any fix?

**Comment by idigra** [comment]
I worked around by setting the colors manually when disabled.
(It's not ideal as it requires changing all buttons in the system (in case we don't have infra button and we're using FluentUI button directly). Also, the performance might be sub optimal. Thus I'm still waiting for the issue to be resolved).

**Comment by ecraig12345** [comment]
Here's an updated codepen that works around an ongoing issue on codepen's side preventing the original one from rendering: https://codepen.io/ecraig12345/pen/gOwKxOp?editors=0010

It looks like the issue is in [ButtonThemes.ts](https://github.com/microsoft/fluentui/blob/master/packages/react-internal/src/compat/components/Button/ButtonThemes.ts)--for some reason `buttonBackgroundDisabled` and `primaryButtonBackgroundDisabled` are only used for SplitButton. This seems wrong to me but I'd like @khmakoto to confirm once he's back from vacation next week.

**Comment by idigra** [comment]
Thanks. Can you recheck the link to the codepen with workaround? It seems to not be solved (e.g. the standard disabled button should be yellow but it still has the default disabled color).

**Comment by ecraig12345** [comment]
The codepen is a repro of the problem, not a solution yet.

**Comment by khmakoto** [comment]
@ecraig12345 I think that is precisely the problem and we need to update `ButtonThemes.ts`.

**Comment by codechef97** [comment]
any update?

**Comment by ecraig12345** [comment]
@andrefcdias Would you be willing to help with this one? If you need more info on how to approach it, let me or @khmakoto know.

**Comment by andrefcdias** [comment]
Investigating this now.
