### ISSUE TITLE
Support for input type="hidden"

### ISSUE THREAD

**Issue by DanielFuchs98** [microsoft/fluentui#16154]
#### Describe the feature that you would like added

When the type is equals to "hidden", the component should not be visible. See https://www.w3schools.com/tags/att_input_type_hidden.asp

#### What component or utility would this be added to

TextField

#### Additional context/screenshots
![image](https://user-images.githubusercontent.com/28670365/101283053-a1167800-37d8-11eb-8a59-d66aabd21f0a.png)

**Comment by paulgildea** [comment]
@DanielFuchs98 Thanks for filing this issue. 

I’ll mark this as a feature request and add it to our backlog, but to set expectations - we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. We'll take this into consideration when we converge the `TextField` component across our two React packages.

Also let me know if you are interested in submitting a PR.

As a work around you might be able to override it's visibility - while not ideal, it might provide you the experience you are looking for.

**Comment by ecraig12345** [comment]
In this case, couldn't you just use a standard `<input type="hidden" />`? A large part of the point of using the TextField would be for the nicer styling, but that's not really relevant if it's not shown.

**Comment by DanielFuchs98** [comment]
> In this case, couldn't you just use a standard `<input type="hidden" />`? A large part of the point of using the TextField would be for the nicer styling, but that's not really relevant if it's not shown.

Yes, thats the way I implemented this requirement at the moment.

**Comment by ecraig12345** [comment]
Closing this since it's not something we're likely to implement (at least in the current version of TextField), and there's an easy workaround of using the built-in `<input type="hidden" />`.
