### ISSUE TITLE
ContextualMenu cannot use Link as target

### ISSUE THREAD

**Issue by hraz-msft** [microsoft/fluentui#16155]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: Chrome, Edge

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/hraz/pen/yLaOqdL

#### Actual behavior:

`ContextualMenu` open at (0,0) instead of near to the link.
In you basic example here: https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu you use `a` element. Changing that to `Link` component break the example.

#### Expected behavior:

`ContextualMenu` open near to the Link. Same behavior as your basic example https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Internal Microsoft Product

**Comment by paulgildea** [comment]
@hraz-msft Thanks for filing this issue.

@ecraig12345 This one is a good one to root cause.

**Comment by ecraig12345** [comment]
This is more of an issue with the codepen, not Link or ContextualMenu themselves. For a ref to work as ContextualMenu's `target`, it must point to a DOM element. But `componentRef` points to the component's public API, not the DOM.

In version 7, Link unfortunately doesn't implement `ref` or another prop to get a DOM reference. So instead you have to give the link an ID and set `target='#your-id-here'` on the ContextualMenu.

In version 8 (releasing soon), we added a `ref` prop to Link which will give you a DOM reference and works as ContextualMenu's `target`.

This codepen shows how to do link targeting in both v7 and v8: https://codepen.io/ecraig12345/pen/xxEEGrz

**Comment by hraz-msft** [comment]
Thanks! I think that `Link unfortunately doesn't implement ref or another prop to get a DOM reference` is considered an issue... But at least it solved in Fluent 8.
