### ISSUE TITLE
Narrator does not  dropdown   

### ISSUE THREAD

**Issue by nadavWeisler** [microsoft/fluentui#16162]
### Environment Information

- **Package version(s)**: 7.115.1
- **Browser and OS versions**: Edge chromium Version 86.0.601.1 (Official build) dev (64-bit).

### Describe the issue:

Users who rely on screen reader will not be able to identify and interact with the elements properly if its focus moves somewhere else and does not give the information about disabled items due to which end-users will not be able to differentiate between disabled/enabled controls. 
### Please provide a reproduction of the issue in a codepen:

https://codepen.io/nadavWeisler/pen/BaLzoBZ

#### Actual behavior:

Disabled control the narrator focus moves out of the dropdown and screen reader announces the dropdown only and gives no other information.

#### Expected behavior:

Disabled control the narrator focus moves out of the dropdown and screen reader announces the dropdown disable.

### Documentation describing expected behavior

https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7bb24201d1-2276-4471-8183-e1e5353031ad%7d

**Comment by paulgildea** [comment]
@nadavWeisler Thanks for filing this issue.

@ecraig12345 Please try to determine if you can find a root cause for this issue.

**Comment by paulgildea** [comment]
@smhigley FY as always

**Comment by ecraig12345** [comment]
@nadavWeisler From your issue description, I'm not clear on what the repro steps are. Can you provide a detailed list of steps?

**Comment by nadavWeisler** [comment]
The issue is that screen reader does not announce if drop down is disabled.

**Comment by ecraig12345** [comment]
@nadavWeisler That's still not a list of steps. After loading a page with a dropdown, which exact steps are you following to navigate to the dropdown, and at what point would you expect something to be announced?

**Comment by nadavWeisler** [comment]
After loading the page, I'm turning on screen reader and navigate to the drop down, on crossing over the drop down there is no announcement that one of the options is disabled, what make me think I can choose it.

**Comment by ecraig12345** [comment]
I still can't repro this. Here are the specific steps I'm following. If this is not what you're doing, please let me know specifically which steps are different.
1. Open the codepen link in Edge with Narrator turned on
2. Tab to the dropdown to focus it
3. Open the dropdown (using enter, space, or down arrow)
4. Use the arrow keys to navigate through the options.

The disabled option ("Orange") is not read, which to me seems as expected.

**Comment by ecraig12345** [comment]
I forgot one step: the behavior I described is with scan mode is turned off. If scan mode is on, "Orange" is included when arrowing through the options, but it's correctly indicated as disabled.
