### ISSUE TITLE
Unable to focus outside modeless modal

### ISSUE THREAD

**Issue by cnamal-msft** [microsoft/fluentui#16179]
### Environment Information

- **Package version(s)**: 7.123.5 and Latest version
- **Browser and OS versions**: Firefox/Edgemium on Windows

### Describe the issue:

Go to the Modal documentation [page](https://developer.microsoft.com/en-us/fluentui#/controls/web/modal)
Click on _Open Modal_ for the modeless modal
Hit **Tab** key multiple times

#### Actual behavior:

Focus stays on close button

#### Expected behavior:

Focus goes to the close button once, and then goes to the background content.

### Documentation describing expected behavior

Maybe I misunderstood the documentation of the `isModeless` prop:

>Whether the dialog should be modeless (e.g. not dismiss when focusing/clicking outside of the dialog). if true: isBlocking is ignored, there will be no overlay (isDarkOverlay is ignored), isClickableOutsideFocusTrap is true, and <ins>forceFocusInsideTrap is false</ins>

**Comment by paulgildea** [comment]
@cnamal-msft Thanks for filing this issue.

I was able to repo your experience. 

@joschect - Is this by design. The documentation says that `forceFocusInsideTrap` is `false` leading me to believe that you should be able to escape the Modal with keyboard.

**Comment by joschect** [comment]
@paulgildea I don't believe that this is by design. It's pretty clear that when `modeless` is true the the contained focustrapzone should have `forceFocusInsideTrap` set to false, which should allow focus to escape. I'm not sure if something is wrong with modal or focustrapzone at this time.

**Comment by ecraig12345** [comment]
Using the [modal examples on fabricdemo](https://fabricweb.z5.web.core.windows.net/oufr/7.155.3/#/examples/modal) and the [React dev tools extension](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi), I confirmed that `forceFocusInsideTrap` is false for the modeless modal. So maybe this is an issue with FocusTrapZone?
![image](https://user-images.githubusercontent.com/5864305/104256651-726f6b00-5430-11eb-908b-7c47b702432b.png)

**Comment by ecraig12345** [comment]
Also confirmed it's still broken in [v8 beta](https://fabricweb.z5.web.core.windows.net/oufr/8.0.0-beta.34/#/examples/modal).
