### ISSUE TITLE
onClick-function of Northstar's Table is not triggered 

### ISSUE THREAD

**Issue by marwalsch** [microsoft/fluentui#16176]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.51.3;
- **Browser and OS versions**: - Chrome and Firefox on Windows 10;
                                             - as a tab in the MS Teams desktop-client;  

### Please provide a reproduction of the bug in a codepen:

Can be reproduced on the Web-Page of Fluent UI. Refer to the[ table with nested navigation](https://fluentsite.z22.web.core.windows.net/0.51.3/components/table/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#usage-navigable) and try to click row.

#### Actual behavior:

`onClick `is practically never triggered when clicking a row, only when marking cell content prior to releasing the click. and even then the `onClick `is not guaranteed to trigger.

![Screenshot 2020-12-08 120746](https://user-images.githubusercontent.com/72074423/101477987-4acc4500-3950-11eb-8478-9190a0fca4a3.jpg)

Note how the cell content has been marked to trigger the `onClick`.

#### Expected behavior:

`onClick` should be triggered by simply clicking anywhere in the row.

### Priorities and help requested:

Are you willing to submit a PR to fix? **No**

Requested priority: **High**

Products/sites affected: **Fluent Ui's own homepage**

**Comment by leeford** [comment]
I also am seeing this issue.

**Comment by paulgildea** [comment]
@marwalsch Thanks for filing this issue. We'll take a look.

@jurokapsiar FYI

**Comment by benjaminhuanghuang** [comment]
in file packages/fluentui/react-northstar/src/components/Table/TableRow.tsx, Line 107, there is a condition checking  if (e.currentTarget === e.target). Maybe that is the reason.

**Comment by layershifter** [comment]
Hey folks!

This issue was fixed in #16264 and released in `@fluentui/react-northstar@0.51.4`. You can use linked CodeSandboxes to verify:
- 0.51.3 (bug exists): https://codesandbox.io/s/fluent-ui-example-forked-99krc
- 0.51.4 (bug fixed): https://codesandbox.io/s/2fnbu
