### ISSUE TITLE
Huge white area below last DetailsList row 

### ISSUE THREAD

**Issue by Martype** [microsoft/fluentui#16178]
We are using the DetailsList with custom value rendering (onRenderItemColumn) and a footer row (onRenderDetailsFooter). By the time the total number of rows is 63 or more the DataList starts rendering a big white area under the last row. The footer row still gets rendered, but it is far down below the last DetailsList row.

![image](https://user-images.githubusercontent.com/1420317/101484211-8c152280-3959-11eb-90f9-b36bdd270b78.png)

That white area becomes a little bit bigger with each added row.

With only 62 rows that white area does not appear:

![image](https://user-images.githubusercontent.com/1420317/101484618-33925500-395a-11eb-9eee-6347c0b5d2b4.png)

Obviously the DetailsList renders seperate div-Containers with CSS class "ms-List-page" for each ten rows. Depending on the scroll position, one of theses containers gets a fixed height. When I scroll down to the bottom and remove the height of the last "ms-List-page" container using the browser's Developer Tools, then the white area disappears. It also doesn't come cack when scrolling up and down.

![image](https://user-images.githubusercontent.com/1420317/101485394-6557eb80-395b-11eb-9054-7c65726acf06.png)

The issue occurs in Chrome and Edge. Surprisingly in IE 11 there is no such white area, but I'd guess its only because some script fails or at least does some kind of fallback.

**Comment by Martype** [comment]
Meanwhile I found out that the 'white area' acutually is a 'rows are missing' or a 'rows are not beeing rendered'. 62 rows is the maximum amount of rows beeing rendered and it breaks having 63 or more rows.

**Comment by Martype** [comment]
One more finding: The magic number actually is 60 and not 62. Since I have some filtering in the DetailsList 2 entries always got excluded from the total amount of record, which is why I came to this wrong number. 
So the problem starts when having 61 or more records or in other words: starting with the 7th "ms-List-Page" div-Container, which unfortunately only renders emptiness instead of more rows.

**Comment by paulgildea** [comment]
@Martype Thanks for filing and following up on this issue. This seems similar to #15492, however it doesn't look like that issues was resolved with a fix.

Do you have a reduced repo that our team could take a look at to further troubleshoot this issue? Also do you know what version of the library at you are using?

**Comment by Martype** [comment]
> Thanks for taking the time to enter an issue. However, it seems that there aren't enough details here for this issue to be actionable.
> 
> When issues are created, we need details such as:
> 
> 1. Which Fluent UI component is causing the issue
> 2. Which package name and version the component is from
> 3. Specific, complete steps to reproduce the issue
> 4. What behaviors and attributes are missing or incorrect
> 5. What you expected and what is actually happening
> 6. Confirmation that the problem reproduces in isolation
> 
> Without a clear understanding of these details, it's not possible to take clear action on issues. We are unable to meet your expectations, properly address the root cause, and make changes without affecting the expectations of other consumers.
> 
> Please provide these additional details as you are able. The default issue template provides an outline of these details and is viewable when creating a new issue. Additionally, if this is an accessibility issue, please see [Accessibility Troubleshooting](https://github.com/microsoft/fluentui/wiki/Accessibility-Troubleshooting) in our wiki for more guidance. If these details cannot be provided, please kindly close the issue.
> 
> Thank you for your patience.

1. DetailsList
2. We are using pcf-scripts@1.3.6 and @fluentui/react@7.109.1
3. Add more than 60 records to the DataList, implementing custom field rendering (onRenderItemColumn) and adding footer row (onRenderDetailsFooter) might be necessary 
4. A white area is rendered instead of showing record 61 and all following records
5. Show the expected records instead of an white area
6. not yet

**Comment by Martype** [comment]
> @Martype Thanks for filing and following up on this issue. This seems similar to #15492, however it doesn't look like that issues was resolved with a fix.
> 
> Do you have a reduced repo that our team could take a look at to further troubleshoot this issue? Also do you know what version of the library at you are using?

@paulgildea We could have a screen-sharing session to avoid the overhead of setting up a reduced/isolated repo. I'll send you my business email via pm. Please send a Teams meeting invitation.

**Comment by Martype** [comment]
Regarding isolation: I packed my moc data provider with 500+ items and tested our DetailsList in the local PCF Control Sandbox. The issue does not occur there. So it seems like the integration as a PCF control causes the issue. We set our PCF Control as Control for a View and also fur subgrids on a form. In both scenarios we get that white area.

**Comment by Martype** [comment]
I also implemented https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemcolumns 1:1 into my application and there the issue occurs, too. 

Both my custom DetailsList and the one from the example do not show a scrollbar inside D365:

![image](https://user-images.githubusercontent.com/1420317/102076063-709d9200-3e07-11eb-90ab-740264a23e43.png)

After setting the height of DetailsList to 500px we get a huge white area at the bottom and most of the 500 entries are not beeing renedered.

![image](https://user-images.githubusercontent.com/1420317/102077061-ff5ede80-3e08-11eb-8d14-9e14b303b554.png)

![image](https://user-images.githubusercontent.com/1420317/102075039-ef91cb00-3e05-11eb-859e-c8effa2a761b.png)

I then set the height to 700px und suddenly more rows popped up. I then played around with the height, but 80 was the maximum amount of items beeing rendered.
So I think it has something to do with the height of DetailsList or the container. So maybe there is something special about implementing the DetailsList into D365? What is the best/recommended approach to get the DetailsList beeing scrollable inside a PCF container?

**Comment by Dangerous-Mind** [comment]
Hi @ecraig12345, any news on this issue?

I also have the same issue on one of my projects already on production. Some of the items are not rendered randomly through the list (randomly but in a block of items).

If I resize the width of the screen they are rendered and another gap appears somewhere else. Some of the times there are two or more gaps in the same list.

![image](https://user-images.githubusercontent.com/31196073/103557377-0084a800-4eab-11eb-901b-8c5098a2f0b4.png)

**Comment by Martype** [comment]
@Dangerous-Mind I was able to fix it by wrapping a ScrollablePane around my DetailsList.
I basically implemented the DetailsList example from the official documentation: https://developer.microsoft.com/en-us/fluentui#/controls/web/scrollablepane

Hope this helps you, too!

**Comment by Dangerous-Mind** [comment]
Hi @Martype ,

Your workaround worked fine but we can't have a max-height on the DetailsList or it wont work.

Thanks for your help.
