### ISSUE TITLE
Dropdown issue in IE11 - fluentui/react-northstar@0.51.3 

### ISSUE THREAD

**Issue by gpaniagua013** [microsoft/fluentui#16175]
Dropdown list in IE11 is not displayed correctly in IE11

### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.51.3
- **Browser and OS versions**: IE11

#### Actual behavior:

![image](https://user-images.githubusercontent.com/7999793/101460836-662c5580-393a-11eb-8ad4-c218768ed3b3.png)

Requested priority: (Normal)

**Comment by paulgildea** [comment]
@gpaniagua013 Thanks for filing this issue.

@jurokapsiar FYI

**Comment by layershifter** [comment]
@gpaniagua013 thanks for reporting. I think that we need more details there 💭 

I tried to repro it on CodeSandbox:
- CodeSandbox: https://codesandbox.io/s/fluent-ui-issue-16175-s2dm7
- Deployed app (works in IE11): https://csb-s2dm7-ewkzdqkah.vercel.app/

And it works as expected:
![image](https://user-images.githubusercontent.com/14183168/104010105-4e9bf300-51ac-11eb-9710-a649f4520262.png)

Can you please provide a repro case or modify my example?
