### ISSUE TITLE
Link on tooltip is not working consistently 

### ISSUE THREAD

**Issue by mudit-mittal** [microsoft/fluentui#16173]
**Issue:-** When you click on the anywhere else on the tooltip and then click on learn more link, the tooltip closes and learn more does not open.

![image](https://user-images.githubusercontent.com/44024159/101441445-1ac87600-393f-11eb-98dd-0b4d52ccc0ce.png)

**Comment by paulgildea** [comment]
@mudit-mittal Thanks for filing this issue. It would be super helpful for our team to troubleshoot this issue if you could provide a codepen of your issue.

In the meantime, take a look at the "Tooltip with custom content" sample on using a custom rendering function: https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip

**Comment by mudit-mittal** [comment]
@paulgildea Thank u for considering this issue on priority. Here providing CodePen of my issue

const { DefaultButton, Link, TooltipHost, ITooltipHostStyles, Fabric, initializeIcons } = window.Fabric;
const { useId } = window.FabricReactHooks;

// Initialize icons in case this example uses them
initializeIcons();

const calloutProps = { gapSpace: 0 };
// The TooltipHost root uses display: inline by default.
// If that's causing sizing issues or tooltip positioning issues, try overriding to inline-block.
const hostStyles: Partial<ITooltipHostStyles> = { root: { display: 'inline-block' } };

const TooltipBasicExample: React.FunctionComponent = () => {
  // Use useId() to ensure that the ID is unique on the page.
  // (It's also okay to use a plain string and manually ensure uniqueness.)
  const tooltipId = useId('tooltip');

  return (
    <div>
      <TooltipHost
        content={<>This is tooltip content <Link target='blank' href='https://developer.microsoft.com/'>LearnMore</Link></>}
        // This id is used on the tooltip itself, not the host
        // (so an element with this id only exists when the tooltip is shown)
        id={tooltipId}
        calloutProps={calloutProps}
        styles={hostStyles}
      >
        <DefaultButton aria-describedby={tooltipId}>Hover over me</DefaultButton>
      </TooltipHost>
    </div>
  );
};

const TooltipBasicExampleWrapper = () => <Fabric><TooltipBasicExample /></Fabric>;
ReactDOM.render(<TooltipBasicExampleWrapper />, document.getElementById('content'))

**Comment by ecraig12345** [comment]
Thanks for the code, though in the future could you please save the codepen and share a link to that instead? That way it's easier to test live. Also, if you're posting React code in a github comment, it's best to wrap the code block in triple backticks like this (otherwise github will try to render it as HTML).
````
```
// code here
```
````

For this time, I made a codepen with your code (https://codepen.io/ecraig12345/pen/PoGbKGE) and was able to repro the issue. I'll try and look into it more sometime in the next few days.
