### ISSUE TITLE
Narrator doesn't announce the Dropdown's collapsed state

### ISSUE THREAD

**Issue by sergul** [microsoft/fluentui#16186]
### Environment Information

- **Package version(s)**: office-ui-fabric-react 7.123.1
- **Browser and OS versions**: Chromium Edge 87.0.664.57 and Windows 10

### Describe the issue:

Narrator doesn't announce a single select Dropdown's collapsed state.
At the same time I see that Narrator does read the collapsed state for multiselect Dropdown. Why not having the same role="button" for a single select Dropdown to keep the consistency ? plus it will solve this issue of having the single select Dropdown having its collapsed state announced 😊

### Please provide a reproduction of the issue in a codepen:

1. Go to https://codepen.io/sergulo/pen/wvzzvrP
2. Turn on Narrator and tab onto "Controlled example" Dropdown

Once Narrator focused the Dropdown you can hear that it doesn't announce the collapsed state

#### Actual behavior:

Narrator doesn't announce the collapsed state of a single select Dropdown element

#### Expected behavior:

Narrator should announce the collapsed state of a single select Dropdown element

### Documentation describing expected behavior

https://microsoft.sharepoint.com/:w:/r/teams/msenable/Documents/LCA/MAS%20-%20July%201,%202017%20Release/MAS%204.1.2%20%E2%80%93%20Name,%20Role,%20Value.docx?d=w248054a65e6847719e1e242fb5025730&csf=1&web=1&e=nih5W8

**Comment by gouttierre** [comment]
@sergul  - thank you for your input. into the issue.

@khmakoto  - Can you determine if this is a regression or if this behavior is an issue? cc @smhigley
