### ISSUE TITLE
Bot is not auto labeling and auto assigning new issues

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui#16180]
### Environment Information

- **Package version(s)**: N/A
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:
N/A

#### Actual behavior:
The bot seems to stop auto labeling and auto assigning new issues for triage. Seems to have been around the time the bot address updated.

#### Expected behavior:
The bot should apply the Needs: Triage label and auto assign to the individual who is on shield.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

**Comment by xugao** [comment]
@paulgildea - this is known issue. the bot team is helping to mitigate. ETA: end of today (12/8)

**Comment by xugao** [comment]
This is fixed now
