### ISSUE TITLE
Accessibility: Focus trap zone is not properly setting focus for lazy loaded components

### ISSUE THREAD

**Issue by haojia321** [microsoft/fluentui#16182]
This is a copy over from https://github.com/microsoft/fluent-ui-react/issues/1429 with an updated code snippet. The issue is closed but we found it is not fixed.

Bug Report
Focus trap zone is not properly setting focus for lazy loaded components. It looks like the focus trap zone currently only sets focus on componentDidMount, should it also do this in componentDidUpdate?

Steps
The attached codepen opens a popup with a spinner and simulates lazy loading the popup content. Note that even though we are using the popupFocusTrapBehavior, the first time you click on the "Click Me!" button, the button inside the popup will not have focus. It works the second time once the content is loaded.

Repro steps (in codepen):

Click on the "Click Me!" button
Hit Enter key
Expected Result
Should get an alert with the message "I was clicked"
Actual Result
The popup closes

Version
0.31.1

Testcase
https://codesandbox.io/s/stardust-ui-example-forked-44rxm

**Comment by paulgildea** [comment]
@haojia321 Thanks for filing this issue and providing background links. Truly appreciated!

**Comment by layershifter** [comment]
@haojia321 thanks for bringing this up 👍

From Stardust 0.31.1 a lot of things changes, one of them is that in 0.35.0 we removed `popupFocusTrapBehavior` (https://github.com/microsoft/fluent-ui-react/pull/1565), they were replaced with `autoFocus` and `trapFocus` props.

`FocusTrapZone` also supports forcing focus via `forceFocusInsideTrapOnOutsideFocus` prop that can be specified for `Popup`:

```tsx
<Popup
  trigger={<Button content="Click Me!" primary />}
  content={{ content }}
  trapFocus={{ forceFocusInsideTrapOnOutsideFocus: content !== loader }}
/>
```

![Popup traps focus via trapFocus prop](https://user-images.githubusercontent.com/14183168/104468028-4500f980-55b7-11eb-8cfa-928fa4502aa9.gif)

I modified Codesandbox example to reflect this: https://codesandbox.io/s/stardust-ui-example-forked-lih51?file=/example.js
Please let me know if it works for you 🙏
