### ISSUE TITLE
separated TreeItem and TreeTitle may not be as good as a merged TreeItem 

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/fluentui#16191]
In Fluent UI team, there's discussion of whether it makes sense to keep `TreeItem` and `TreeTitle` separated. We have been seeing some cases, where a merged component produces cleaner code.

I'm opening this issue to register these scenarios. If the merging does happen, these scenarios under this issue should be re-written in a cleaner way.

**Comment by YuanboXue-Amber** [comment]
Currently, when a tree node is clicked, the conditions below in [treeItem](https://github.com/microsoft/fluentui/blob/3a921f8b41f6628efa77d1cf8fbf7d2ecb1bf9b9/packages/fluentui/react-northstar/src/components/Tree/TreeItem.tsx#L228) are checked for: whether an expand/collapse should happen, or select/unselect should happen:
```ts
  const handleTitleClick = e => {
    if (hasSubtree && e.target === e.currentTarget) {
      toggleItemActive(e, id);
    } else if (selectable) {
      toggleItemSelect(e, id);
    }
    _.invoke(props, 'onTitleClick', e, props);
  };
```

In the above code, `e.target === e.currentTarget` condition is to check for if the click happens on the treeTitle, or the checkbox(selectionIndicator). If the user click on the checkbox, we'd like to do select/unselect rather than expand/collapse.

Obviously this condition doesn't work in all cases. When treeTitle has children component, this check will fail. 

The better solution would be listening to click event on the selectionIndicator itself.
When I was trying to implement such change, I find it hard to do because treeItem/treeTitle is separated. The reason is following:
- selectionIndicator is in TreeTitle
- an `id` is needed to select/unselect 
- TreeTitle does not have an id

Currently we could get around it by passing id to treeTitle, or a `onSelectionIndicatorClick` function to treeTitle. But this could be solved more elegantly if treeItem/treeTitle are merged.

**Comment by gouttierre** [comment]
@YuanboXue-Amber  - Thanks for the feedback and providing your investigation results. 

@khmakoto  - Would you be able to determine if this is a regression or if this behavior is an issue? Going on what use cases were identified, along with the proposed solution. 

To set expectations - Due to the complexity and dependencies of our List components, we are actively trying to minimize risk of regressions. We may not be able to fix this issue with a low risk solution. if a reasonable workaround is available.
