### ISSUE TITLE
Popper: throws an error in dev check

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#16192]
```
TypeError
Cannot read property 'pendingProps' of undefined
    at hasAutofocusProp (https://1xhm3.csb.app/node_modules/
fluentui/react-northstar/dist/es/utils/positioner/Popper.js:31:165
    at Object.hasAutofocusFilter [as acceptNode] (https://1xhm3.csb.app/node_modules/
fluentui/react-northstar/dist/es/utils/positioner/Popper.js:34:10
    at eval (https://1xhm3.csb.app/node_modules/
fluentui/react-northstar/dist/es/utils/positioner/Popper.js:46:27
```

### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.51.3 & react@17
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

Open a CodeSandbox: https://codesandbox.io/s/dry-hooks-1xhm3
Click on an input.

#### Actual behavior:
Throws an error.

#### Expected behavior:
Opens a Datepicker.

**Comment by sushruth** [comment]
Currently this is affecting unit tests on apps using @fluentui/react-northstar and react 17. A milestone to look forward to will be much appreciated
