### ISSUE TITLE
Accessibility - Focus comes out of dropdown list when swiping on a touch screen

### ISSUE THREAD

**Issue by yanbxice** [microsoft/fluentui#16204]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@7
- **Browser and OS versions**: Edge + Narrator

### Describe the issue:

On command bar with a dropdown, if a touch screen device is used, the focus goes out of the dropdown modal onto the next DOM element, after swiping from the last option. The behavior is similar to navigating the options using arrow keys. 

### Please provide a reproduction of the issue in a codepen:

https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar

#### Actual behavior:

Focus comes out of dropdown modal

#### Expected behavior:

Focus should keep inside the dropdown while navigating inside with swiping. Otherwise, customers won't know if the next item announced is an option or not.

**Comment by gouttierre** [comment]
@yanbxice  - Thanks for the feedback!
 
@khmakoto  - Would you be able to determine if this is a regression or if this behavior is an issue? cc @smhigley
