### ISSUE TITLE
menu spec link broken (web component)

### ISSUE THREAD

**Issue by vamshi9666** [microsoft/fluentui#16200]
link in  [readme](https://github.com/microsoft/fluentui/blob/master/packages/web-components/src/menu/README.md) intended for component spec is broken.

**Comment by gouttierre** [comment]
@vamshi9666 - we appreciate your feedback. Sadly, the information you provided on the follow up links do not work - as I get a 404 error.

```
The menu is a widget that offers a list of choices to the user, such as a set of actions or functions.
For more information view the [component specification](https://github.com/microsoft/fluentui/blob/master/packages/fast-foundation/src/menu/menu.spec.md).

```
If you could provide more information or be willing to submit more details (such as, repo, or PR) we will gladly take a look. Right now, there is not enough information.

**Comment by chrisdholt** [comment]
@eljefe223 can you update the spec link for the `menu` web component?
