### ISSUE TITLE
modifying 'height' of dropdown.

### ISSUE THREAD

**Issue by bharath3719** [microsoft/fluentui#16202]
### Describe the issue:

On changing 'height' of the dropdown control, the selected item/option is not center-aligned.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/19222968/101810881-52057580-3b3f-11eb-9a40-3972218acc8c.png)

#### Expected behavior:

Selected item should be center aligned as it happens in searchbox control.

![image](https://user-images.githubusercontent.com/19222968/101811025-88db8b80-3b3f-11eb-918d-a581a86b77a9.png)

**Comment by ecraig12345** [comment]
For future issues, please provide a codepen repro of the issue (as requested in the template) to make it easier to investigate. You can start from https://aka.ms/fluentpen or the "Export to CodePen" link on one of the [website examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown).

I don't think that automatic center alignment of a custom-height dropdown is something that we intend to support out of the box (and the fact that SearchBox supports this is probably a coincidence). However, there should be a way to make it work with style overrides.
