### ISSUE TITLE
Transition for color of *Button components is delayed

### ISSUE THREAD

**Issue by lesomnus** [microsoft/fluentui#16201]
### Environment Information

- **Package version(s)**: 7.153.2
- **Browser and OS versions**: Chrome (latest) and Edge (dev on ubuntu)

#### Actual behavior:

Transition for color of *Button components is delayed

[This](https://stackoverflow.com/questions/39600138/how-to-simultaneously-transition-colour-of-nested-children) shows exactly what happend.

Assume:
```css
* {
	transition: color 0.2s
}
```
```jsx
<CommandBarButton
	iconProps={{ iconName: 'Upload' }}
	text="Upload"
	disabled={this.state.readonly} />
```

When `state.readonly` become `true`, both color of `text` and icon become gray, but transition for color of `text` is delayed than icon.

#### Expected behavior:

Transition for color of *Button components is **not** delayed

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, **No**): Sorry it's very hard to understand how `styles` property works. It would be nice tell me where the document is.

Requested priority: (Blocking, High, Normal, **Low**)

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
Thanks for filing this, but could you please provide a repro of what you've tried so far in a codepen? You can start from https://aka.ms/fluentpen or "Export to CodePen" on one of the [button examples on the website](https://developer.microsoft.com/en-us/fluentui#/controls/web/button).

**Comment by lesomnus** [comment]
https://codepen.io/lesomnus/pen/ExgJzKV

I realized  that I was using the selector incorrectly. But it still hard to make them (icon and text) transition. I tried button selector but only the text is in transition.
