### ISSUE TITLE
onClick not firing in calendar

### ISSUE THREAD

**Issue by PathToSharePoint** [microsoft/fluentui#16212]
### Environment Information

- **Package version(s)**: "@fluentui/react": "7.153.4"
- **Browser and OS versions**: Edge 87

### Please provide a reproduction of the bug in a codepen:

Unfortunately the default calendar doesn't offer the "Export to Codepen" feature, but the code is straightforward:
<Calendar
     onPointerDown={()=>console.log("onPointerDown")}
     onClick={() => console.log("onClick")}
     onSelectDate={() => console.log("onSelectDate")}
     ... />

#### Actual behavior:

On calendar click, the console displays "onPointerDown" and "onSelectDate".

#### Expected behavior:

I would expect all 3 events to be triggered: "onPointerDown", "onClick" and "onSelectDate".
onSelectDate is not enough for my case because I need the event target, not just the date value.

### Priorities and help requested:

Are you willing to submit a PR to fix? No (not knowledgeable enough)

**Comment by ecraig12345** [comment]
I think this is actually behaving as expected. While the OUFR v7 Calendar technically accepts and applies all native props, by default it applies them to the root element, not to child elements. And the date button elements define their own `onClick` internally which handles date selection.

Notice that in [this codepen](https://codepen.io/ecraig12345/pen/YzGMdvW), if you click an area of the calendar that's *not* a button, the root `onClick` is actually called.

(Also just so you know for future issues, if there's no export to codepen button you can start from https://aka.ms/fluentpen and copy some example code in.)

**Comment by PathToSharePoint** [comment]
@ecraig12345 ,

First, thank you for the sample and codepen tip!

I get your point. I think what confused me was that onPointerDown was triggered and not onClick. The v8 behavior where none is triggered is more consistent. Also, I am used to event delegation on calendars and the choice made for Fluent UI is different from what I've seen in other libraries.

Would you have an ETA for v8? And would you have a snippet to share on handling the buttons' onClick? Or point me to the github file to get me started?

**Comment by ecraig12345** [comment]
At the moment I don't think we have a direct way to customize the date buttons' `onClick` or access the click event. Specifically what did you want to do that doesn't work with `onSelectDate`?

We hope to release version 8 in mid-February, working on figuring out a specific date now. In the meantime, if you want you can switch to using the DatePicker from `@uifabric/date-time` version 7--we're switching to exporting that version by default in version 8, so the version 7 behavior and API will be more similar.

**Comment by PathToSharePoint** [comment]
I had a couple scenarios in mind:
- multiple date selection (for booking), but not a range
- multiple button states, for example unselected / full day / morning / afternoon

I am not really surprised that there is no direct access to button click. It confirms what I mentioned earlier, that such cases are usually handled by delegation. Wouldn't onSelectDate be able to pass the event target?

Thanks for the replies, I think they address my questions.

**Comment by ecraig12345** [comment]
We could potentially add an event argument to `onSelectDate`, but I suspect proper handling for the scenarios you mentioned would require substantial changes to DatePicker/Calendar internals (which is not something we're likely to get to any time soon unfortunately).

**Comment by PathToSharePoint** [comment]
The event argument would be a nice addition, and I'd say it is common practice in event handlers.

Understood about my scenarios, especially I don't expect the second one to be a standard request. I am sure I can work it out with the event handler.

Thanks!

**Comment by ecraig12345** [comment]
It looks like someone filed a feature request for adding an event parameter in #12345. Unfortunately I can't guarantee that we'll get to it any time soon given other priorities.
