### ISSUE TITLE
[Android - Accessibility] People Picker - Talkback focus moves to "<person>" item twice on suggestions list

### ISSUE THREAD

**Issue by lutorre** [microsoft/fluentui#16211]
### Environment Information

- **Package version(s)**: @fluentui/react 7.129.0
- **Browser and OS versions**: Android 11.0

### Describe the issue:

Talkback focus moves to "<person>" item twice on suggestions list

#### Actual behavior:

When TalkBack is enabled the focus moves twice to the same item in the people picker suggestions list.  

Steps to reproduce:
1- Enable TalkBack
2- Tap on a people picker component and enter a letter to load the suggestions list
3- Once the suggestions list is visible and focused swipe right to select the next element in the list
4- TalkBack focuses and reads the already selected element

#### Expected behavior:

TalkBack should  focus and read the next element in the list.

### If applicable, please provide a codepen repro:

This can be reproduced by enabling TalkBack and trying on the people picker Fluent [example](https://fabricweb.z5.web.core.windows.net/oufr/7.153.2/#/examples/peoplepicker)

**Comment by gouttierre** [comment]
@lutorre - Thanks for the feedback.

@khmakoto  - Would you be able to determine if this is a regression or if this behavior is an issue? The issues was identified on android os.  cc. @smhigley
