### ISSUE TITLE
Keyboard focus is lost after an onChange event in Dropdown/Combobox

### ISSUE THREAD

**Issue by Teja-Git** [microsoft/fluentui#16217]
### Environment Information

- Package version(s): 7.107.0
- Browser and OS versions: Chrome - 87.0.4280.88 (Official Build) (64-bit)

**Which Fluent UI component is causing the issue**
   DropDown + DetailsList

**Which package name and version the component is from**
  "office-ui-fabric-react": "^7.107.0",

**Specific, complete steps to reproduce the issue**
   In our web app, we have a dropdown that has sorting order as values in it. Onchange of that dropdown value triggers an api call and the grid reloads after that. The focus is lost after the grid reload and not visible until the user presses tab key.

**What** behaviors and attributes are missing or incorrect
   In our web app, we have a dropdown that has sorting order as values in it. Onchange of that dropdown value triggers an api call and the grid reloads after that. The focus is lost after the grid reload and not visible until the user presses tab key.

**What you expected and what is actually happening**

- Actual behavior:
   The focus is lost after the grid reload and not visible until the user presses tab key.

- Expected behavior:
   The focus should still be present on the dropdown

- Confirmation that the problem reproduces in isolation
  Yes

- Are you willing to submit a PR to fix? (Yes, No)
   No

- Requested priority: (Blocking, High, Normal, Low)
    High

- Products/sites` affected: (if applicable)
   Microsoft's Internal site in Volume Licensing

**Comment by ecraig12345** [comment]
Sorry for the delay in getting to this. Without a live repro, it's hard to understand exactly how you're using the Dropdown or debug what might be going wrong. Easiest way to start is by clicking "Export to CodePen" on one of the [Dropdown examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown). For demo purposes, you could simulate the async update after an API call using `setTimeout`.
