### ISSUE TITLE
 onRenderMissingItem is always triggered without scrolling to the last row

### ISSUE THREAD

**Issue by joaojmendes** [microsoft/fluentui#16233]
Hi, sorry to reopen this issue but I face to a similar problem and I don't find a lot of doc about this. 

@aditima  I have followed the mentionned strategy but I face to a problem. The onRenderMissingItem is always triggered even if I don't scroll to the last row. 

I also took a look at the advanced example but it seems that the "null" row had been forgotten. When we take a look at the prototype _onRenderCell, it seems that a "null" row is absolutely needed in order to trigger the onRenderMissingItem. 

I have more followed the strategy [https://codepen.io/dzearing/pen/EgqMZq](here) but unlike what happen in this example, I have the onRenderMissingItem which is automatically triggered. 

Any idea ? How to trigger the next call when we scroll down and not automatically ?

_Originally posted by @sirius210 in https://github.com/microsoft/fluentui/issues/4050#issuecomment-415031252_

**Comment by gouttierre** [comment]
@joaojmendes -Thanks for the input. What version of fluent are you using?

@khmakoto  - Would you be able to determine if the issue stated with the onRenderMissingItem is a regression or if this behavior is an issue in our latest version?
