### ISSUE TITLE
DetailsList - onRenderMissingItem - Please give more details how to use and sample how to implement  get more items

### ISSUE THREAD

**Issue by joaojmendes** [microsoft/fluentui#16231]
Please, give more information how to use  onRenderMissingItem,  and how to use to implement to load more page of data.

Thank you.

**Comment by ecraig12345** [comment]
The ["variable row heights" DetailsList example](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/variablerowheights) includes a basic implementation of `onRenderMissingItem`.
