### ISSUE TITLE
Select option using enter key from keyboard is not working on multiselect dropdown

### ISSUE THREAD

**Issue by Abidsp** [microsoft/fluentui#16244]
While trying to select options in multiselect dropdown using enter key from keyboard, it is not working. This is working fine for single select dropdown.

**Comment by benjaminhuanghuang** [comment]
To the multiselect dropdown, the options in the dropdown were rendered as  Checkbox component. Currently the Checkbox component does NOT repose to "Enter" key press.  That is why user can not select options in multiselect dropdown. 
The issue of CheckBox  can be reproduced in storybook "@fluentui/react"

Is there a bug reported for Checkbox component?

**Comment by gouttierre** [comment]
@Abidsp - Have you managed to follow up the suggestion that @benjaminhuanghuang mentioned?

**Comment by ecraig12345** [comment]
Currently the expected way to select options in a multi-select dropdown is using the space bar, not enter, so this is by design.
