### ISSUE TITLE
Unable to add @fluentui/jest-serializer-merge-styles as snapshot serializer within storyshot

### ISSUE THREAD

**Issue by fhdsouza** [microsoft/fluentui#16249]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

Im trying to have storyshots included within storybook with our fluentUI components. I need to enable snapshotSerializer as a fluent provided serializer but I get the error: **Type 'string' is not assignable to type 'Plugin'** below. As per storyshot documentation, Im supposed to add it here as it is ignored if added in the jest.config file. 

Im using:
```
"@fluentui/jest-serializer-merge-styles": "^8.0.0-beta.0",
 "@fluentui/react": "~7.121.11",
```

Here's my setup file:

```
initStoryshots({
configPath: 'src/storybook',
framework: 'react',
test: multiSnapshotWithOptions({}),
stories2snapsConverter: new Stories2SnapsConverter({
snapshotsDirName: '../../../tests/snapshots/'
}),
snapshotSerializers: [
"@fluentui/jest-serializer-merge-styles"
]
});
```

#### Expected behavior:

Shouldnt throw this error

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
Based on both the type error and the [storyshots plugin documentation](https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core#snapshotserializers), it looks like you need to pass a serializer plugin object (not the name of a serializer plugin) in this context.

```ts
import * as jestSerializerMergeStyles from '@fluentui/jest-serializer-merge-styles';
// ...
initStoryshots({
  snapshotSerializers: [jestSerializerMergeStyles],
  // ...
});
```
