### ISSUE TITLE
Q1 2021 component convergence planning

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#16254]
Open issues:
- We need Callout for Dropdown and Menu right?

Components
- Separator - Josche
- Link - Josche
- Avatar - Ben
- Callout - Ling
- Text - Shift+Miro
- Menu - Ling
- Icon - Tomi
- FocusZone - Mak? - Should we just use ability helpers?
- Dropdown - Ben 
- Image - Shift+Miro
- Badge - Ling
- Card - Mak
- Button - Mak
- ThemeProvider - Xu
- OverflowSet - ??

Utilities:
- makeStyles
- AbilityHelpers
- ThemeProvider
- Telemetry
   - Optional, for apps, track prop usage

**Comment by layershifter** [comment]
@JustSlone this issue looks slightly outdated so I am closing it for housekeeping 🏡 Feel free to re-open it if it's needed.
