### ISSUE TITLE
StackItem does not apply data- properties to the rendered <div> element

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#16263]
### Environment Information

- **Package version(s)**: latest (7.155.2)
- **Browser and OS versions**: Edge 89.0.731.0

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/xinychen/pen/GRjmaKr

#### Actual behavior:
![image](https://user-images.githubusercontent.com/50703224/102515398-b177fe00-40c8-11eb-9e2f-18c1771da4d1.png)

#### Expected behavior:
`<div>` elements rendered by `StackItem` should also have `data-automation-id` attribute.

### Priorities and help requested:

Are you willing to submit a PR to fix? Not yet

Requested priority: Normal

Products/sites affected: N/A

**Comment by ecraig12345** [comment]
@khmakoto should confirm but I think this is behaving as expected/documented right now: based on the prop types, I don't think `StackItem` allows arbitrary props such as `data-*`, and I don't see any handling for native props in `StackItem`. However, it's definitely something we could consider adding in the future.

**Comment by ecraig12345** [comment]
@chenxinyanc If you're willing to consider submitting a PR to add this feature, it would be pretty straightforward. I'm also going to mark this as a contribution candidate/good first issue in case anyone else is interested.

What you'd do is make a set of changes to `StackItem`-related files which is similar to a pattern you can already see in `Stack`:
* In `packages/react-internal/src/components/Stack/StackItem/StackItem.types.ts`, make `IStackItemProps` extend `React.HTMLAttributes<HTMLElement>`, similar to this: https://github.com/microsoft/fluentui/blob/859fe008176c28a86b24d02e2d1bc1fe3d918752/packages/react-internal/src/components/Stack/Stack.types.ts#L69-L72
* In `packages/react-internal/src/components/Stack/StackItem/StackItem.tsx`, add lines to `StackItemView`:
  * Get native props, similar to this: https://github.com/microsoft/fluentui/blob/859fe008176c28a86b24d02e2d1bc1fe3d918752/packages/react-internal/src/components/Stack/Stack.tsx#L42
  * Spread the native props on the root element, similar to this: https://github.com/microsoft/fluentui/blob/859fe008176c28a86b24d02e2d1bc1fe3d918752/packages/react-internal/src/components/Stack/Stack.tsx#L51

**Comment by khmakoto** [comment]
@ecraig12345 yeah, I think this should be a pretty straightforward and harmless contribution.
