### ISSUE TITLE
ComboBox: the 'newPendingValue' cannot be assigned in function '_notifyPendingValueChanged'

### ISSUE THREAD

**Issue by xinlongpan** [microsoft/fluentui#16261]
The code in 'ComboBox.prototype._notifyPendingValueChanged' below: 

```ts
if (currentPendingValueValidIndexOnHover !== prevState.currentPendingValueValidIndexOnHover &&
                        this._indexWithinBounds(currentOptions, currentPendingValueValidIndexOnHover)) {
                       // Set new pending index if hover index was changed
1                     newPendingIndex = currentPendingValueValidIndexOnHover;
        }
        else if (currentPendingValueValidIndex !== prevState.currentPendingValueValidIndex &&
                      this._indexWithinBounds(currentOptions, currentPendingValueValidIndex)) {
                    // Set new pending index if currentPendingValueValidIndex was changed
2                   newPendingIndex = currentPendingValueValidIndex;
        }
        else if (currentPendingValue !== prevState.currentPendingValue) {
                      // Set pendingValue in the case it was changed and no index was changed
 3                  newPendingValue = currentPendingValue;
        }
```

if the 'newPendingIndex' be set a value in step 1 or step 2, the 'newPendingValue' cannot be assigned a value in step 3.

**Comment by ecraig12345** [comment]
Thanks for filing this and doing some investigation, but it's not clear from the description what consuming code or user interaction leads into this error case (or what the user impact is). Could you please provide a codepen and repro steps? You can start from "Export to CodePen" on one of the [ComboBox examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox).

**Comment by xinlongpan** [comment]
I share an example in https://codepen.io/kevin0521/pen/OJRjpbL.
If I input 'kevin1' or 'kevin10' in the comboBox, that can't search any matching value.
