### ISSUE TITLE
Dialog triggered from within MenuButton's menu item closes immediately after opening

### ISSUE THREAD

**Issue by thure** [microsoft/fluentui#16275]
### Environment Information

- **Package version(s)**: `react-northstar@0.51.3`
- **Browser and OS versions**: Chrome 87 in macOS 11.1

#### Actual behavior:

Clicking 'open dialog' from within menu triggered by 'open menu' opens a dialog, which appears for an instant, then immediately closes.

#### Expected behavior:

Dialog should remain open.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, but I'd need help from Fluent UI engineers.

Requested priority: This is necessary for `@fluentui/react-teams`, OfficeDev/microsoft-teams-ui-component-library#31

Products/sites affected: MS Teams ecosystem

**Comment by thure** [comment]
This problem does not occur if using the following configuration, which seems like it should be equivalent:
https://codesandbox.io/s/busy-lichterman-uy7l0
```tsx
<Popup
        trigger={<Button content="open menu" />}
        content={<Dialog
          cancelButton="Cancel"
          confirmButton="Confirm"
          header="Action confirmation"
          trigger={<MenuItem vertical content="open dialog" />}
        />}
      />
```

**Comment by jurokapsiar** [comment]
This is expected as the MenuItems are rendered only when the menu is opened. If you need to open a dialog based on an event in menu, you need to move it up in the react tree and take over the control: https://fluentsite.z22.web.core.windows.net/0.51.4/components/dialog/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#usage-callbacks
