### ISSUE TITLE
[web-components] Improve focus styles for lightweight Fluent Button

### ISSUE THREAD

**Issue by litteredwitherrors** [microsoft/fluentui#16271]
#### Describe the feature that you would like added

Add visually noticeable focus styles for `fluent-buttons` that are set to `appearance="lightweight"`
Providing a visual focus cue would benefit accessibility.

**Comment by gouttierre** [comment]
@litteredwitherrors  - thank you for the suggestion. 

 I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. However, you wish to contribute and submit a PR for this feature request, we would love to see it!

**Comment by chrisdholt** [comment]
@gouttierre this is for the web components and it's higher on our backlog - thanks :)

**Comment by chrisdholt** [comment]
@litteredwitherrors I *think* this appears to have been resolved. Please let me know if the latest version doesn't show the added focus styles for you. Thanks!

**Comment by litteredwitherrors** [comment]
@chrisdholt I see that `lightweight` buttons have been updated to show an active state; however, I'm not seeing an active state on `neutral` buttons now. Can you confirm?

**Comment by chrisdholt** [comment]
> @chrisdholt I see that `lightweight` buttons have been updated to show an focus state; however, I'm not seeing an focus state on `neutral` buttons now. Can you confirm?

Confirmed this is resolved and was due to a prettier issue which has now been resolved
