### ISSUE TITLE
Modal Flyout Issue (using PanelWizard)

### ISSUE THREAD

**Issue by arahuul95** [microsoft/fluentui#16278]
I am facing an issue while using PanelWizard from @m365-admin/wizard library. Please watch the 1:30 minute recording attached for the problem description. Hoping that I get some help. Thanks in advance.

https://user-images.githubusercontent.com/76421751/102745805-d4353b80-4382-11eb-97b7-ecc1260c3775.mp4

**Comment by ecraig12345** [comment]
This is the public repo for `@fluentui/react` (`office-ui-fabric-react`) and we can't provide support for the private M365 Adin Controls library. You should email the address listed in the Git repo readme for help. (message me on Teams if you can't find this)

Also, please remember that GitHub is a public forum, so you shouldn't share images of internals of Microsoft products here.

**Comment by ecraig12345** [comment]
One clarification, by "email the address listed in the Git repo readme" I meant the M365 Admin Controls repo. Again you can message me if you need help finding this.
