### ISSUE TITLE
React-Northstar: Need a SpinButton

### ISSUE THREAD

**Issue by DaleyKD** [microsoft/fluentui#16273]
#### Describe the feature that you would like added
React-Northstar has no numeric input for integer or decimals.  In the Fluent UI suite, you call it a SpinButton.

#### What component or utility would this be added to
This would be added to the React-Northstar suite.

#### Have you discussed this feature with our team, and if so, who
No.

#### Additional context/screenshots
https://developer.microsoft.com/en-us/fluentui#/controls/web/spinbutton

You guys told us to use React-Northstar if we're doing Teams development work.  I'm trying, but keep finding a lot of shortcomings and have to shim it with something like Telerik Kendo.

**Comment by gouttierre** [comment]
@DaleyKD - Thank you for input and apologies on the short comings with the available components within our `React-Northstar`.

Please, know we are working tirelessly towards aligning our components across our platforms. I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. However, if you are wish to contribute a [RFC](https://github.com/microsoft/fluentui/tree/master/rfcs)  for this new feature request, we would love to see it! Thanks and regards
