### ISSUE TITLE
React-Northstar: TextArea Disabled Style and Other Lacking Features

### ISSUE THREAD

**Issue by DaleyKD** [microsoft/fluentui#16274]
### Environment Information

- **Package version(s)**: **"@fluentui/react-northstar": "^0.51.3"**
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:
When you disable the `TextArea`, it's look does not match `Input`.
![image](https://user-images.githubusercontent.com/7206282/102662912-66500080-4145-11eb-927c-e8bf5e7bf6be.png)

**MAJOR side note** (and if I need to submit another issue, then I will): the `TextArea` control is SEVERELY lacking.  I can't use it in a `Form` control alongside `Form.Input` or `Form.Dropdown` because you don't support `required` or `errorMessage`, etc.  I worked all day trying to mimic something just so I could click the label and have the `for=""` tag work with the `<textarea />`.

#### Expected behavior:
It'd be nice if the controls had the same look and feel and were usable in a `Form.`

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Requested priority: (**Blocking**, High, Normal, Low)
Products/sites affected: (if applicable)

Because of this being as blocking as it is (not just the styling, but the lack of Form/validation support), I have to use Telerik's Kendo.  I'd rather use your controls to make it feel like my Teams app belongs in Teams.

**Comment by jurokapsiar** [comment]
I have scheduled this for upcoming sprint (Jan 11 to Jan 24)

**Comment by DaleyKD** [comment]
Thank you!

Since this was a blocking issue, we had to move to the use of KendoReact for our input controls.  That takes the priority of this issue down for us.

In the future, perhaps when northstar (or whatever it'll be called then) is a bit more mature, we can move the input/form controls away from Kendo back to northstar.
