### ISSUE TITLE
Support title in the middle of CommandBar

### ISSUE THREAD

**Issue by Chinkaimu** [microsoft/fluentui#16299]
#### Describe the feature that you would like added

Could you please support title in the middle command bar, such as following image
![image](https://user-images.githubusercontent.com/12783937/103126383-0c14e980-46c9-11eb-89a1-5077d0485ace.png)

#### What component or utility would this be added to

Current command bar in web only support add commands in the left (primary items) or right (secondary items). It hasn't support add title or commands in the middle. It only support overwrite the overflow button(use overflowButtonAs) or all command items(use buttonAs), make it very difficult to add tittle in the middle.

#### Have you discussed this feature with our team, and if so, who
Not yet.

**Comment by joschect** [comment]
@Chinkaimu Hey! could you provide a few more details? 
* Where does the title need to go? IE. Always after the overflow item set?
* How should the title collapse when overflow happens?
* Should the title fill the rest of the space?

And would you be willing to submit a feature for this? I suspect that this might take a bit of work. We have not yet discussed a middle section and I think we would need a PM to help drive it.

**Comment by Chinkaimu** [comment]
@joschect Hey! Our PM Belle have sent the email to you. She helped answer the question, hope that email reaches you well and healthy.

1.	Where does the title need to go? IE. Always after the overflow item set?
Belle: This is centered and always after the overflow.

2.	How should the title collapse when overflow happens?
Belle: As users minimize window to certain width, title should become invisible. 

3.	Should the title fill the rest of the space?
Belle: No. It is limited to certain # of chars. We will truncate with trailing string once # of chars hits that limit.

You mentioned we might need to submit a feature for this. How can we do that?

**Comment by joschect** [comment]
@Chinkaimu Hey! Sorry for my slow reply.

You can submit a feature to this by submitting a pull request to this github. This [section of the readme](https://github.com/microsoft/fluentui/blob/master/packages/react/README.md#building-the-repo) provides some good getting started information! Additionally we are certainly here to help.

As for the right fix, I think that adding a third middle section might not be the best idea for right now. I believe the best possibility is to add an `onRenderOverflowButton` property to the commandbar. This would make it easier to move the overflow button. It seems like the title should be part of the `near`  commandbar item set, just placed after the overflow.

**Comment by gouttierre** [comment]
@Chinkaimu  -  I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.

In the meantime, if you wish to submit a feature to this by submitting a pull request to this github. This [section ](https://github.com/microsoft/fluentui/blob/master/packages/react/README.md#building-the-repo) of the readme provides some good getting started information! Additionally we are certainly here to help.

**Comment by Chinkaimu** [comment]
@gouttierre Thanks for your reply. Could I know how is the feature going? Is there any plan for it?

**Comment by Chinkaimu** [comment]
Hi @gouttierre  I have submit a pull request for this issue. Please kindly ask someone to help review whether the implementation is OK. I don't know if we need include designer or PM to confirm the behavior.
