### ISSUE TITLE
Support for providing custom role in DetailsList

### ISSUE THREAD

**Issue by vishakha116** [microsoft/fluentui#16292]
#### Describe the feature that you would like added

As of now, role="grid" is hard-coded for Details List. Support to specify the role of DetailsList by the user should be provided.
We need to create a tree-like structure for which  the role should be "tree" and the role of children items should be "treeitem". But as of now role is restricted to "grid" only.

#### What component or utility would this be added to

DetailsList

#### Have you discussed this feature with our team, and if so, who

No

**Comment by sachinma** [comment]
@ecraig12345 can you look at this, triage and find the right owner.

**Comment by ecraig12345** [comment]
This seems like a reasonable request and should be fairly straightforward to implement, but we’re not currently working on DetailsList and therefore not likely to get to this any time soon. If you're interested in contributing this feature, I could provide some more detailed guidance and help review a PR. Sorry I don't have a better answer right now.

**Comment by tanisha2710** [comment]
@ecraig12345 can I contribute to this issue, let me know if is open to contribute, I am actively looking for some issues to contribute to as a first time contributor to OSS

**Comment by ecraig12345** [comment]
@tanisha2710 Thanks for the interest! Unless this is something your team needs, it's pretty low priority, so there are probably some better issues for you to start on.
