### ISSUE TITLE
Error messages don't meet the color contrast standard in dark theme

### ISSUE THREAD

**Issue by devrsi0n** [microsoft/fluentui#16295]
### Environment Information

- **Package version(s)**: 7.154.0
- **Browser and OS versions**: Chrome(87.0.4280.88) macOS(11.1)

### Describe the issue:

Error messages don't meet the color contrast standard.
![image](https://user-images.githubusercontent.com/7880675/103063755-3d1fec00-45ed-11eb-81df-f7ef704a6b29.png)

### Please provide a reproduction of the issue in a codepen:

https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield

- Select `Theme: Dark`
- Open the devtools
- Observe the issue

#### Actual behavior:

The error message color contrast is 2.39

#### Expected behavior:

The error message color contrast is at least 4.5

### Documentation describing expected behavior

https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

> A contrast ratio of 3:1 is the minimum level recommended by [[ISO-9241-3]] and [[ANSI-HFES-100-1988]] for standard text and vision. The 4.5:1 ratio is used in this provision to account for the loss in contrast that results from moderately low visual acuity, congenital or acquired color deficiencies, or the loss of contrast sensitivity that typically accompanies aging.

> The rationale is based on a) adoption of the 3:1 contrast ratio for minimum acceptable contrast for normal observers, in the ANSI standard, and b) the empirical finding that in the population, visual acuity of 20/40 is associated with a contrast sensitivity loss of roughly 1.5 [[ARDITI-FAYE]]. A user with 20/40 would thus require a contrast ratio of 3 * 1.5 = 4.5 to 1. Following analogous empirical findings and the same logic, the user with 20/80 visual acuity would require contrast of about 7:1.

> The contrast ratio of 4.5:1 was chosen for level AA because it compensated for the loss in contrast sensitivity usually experienced by users with vision loss equivalent to approximately 20/40 vision. (20/40 calculates to approximately 4.5:1.) 20/40 is commonly reported as typical visual acuity of elders at roughly age 80. [[GITTINGS-FOZARD]]

**Comment by ecraig12345** [comment]
Thanks for reporting this. I think we'll need design input to figure out what other color would be appropriate here, then update `semanticColors.errorText` within the dark theme so that it fixes all instances of the issue across components.
