### ISSUE TITLE
When using null as the last item in a ShimmeredDetailsList, Selection includes that null item when all items are selected using the select all check

### ISSUE THREAD

**Issue by brandonthomas** [microsoft/fluentui#16296]
### Environment Information

- **Package version(s)**: 7.155.1
- **Browser and OS versions**: Edge/Windows

https://codepen.io/brandonthomas/pen/RwGLzNo

1. Open codepen above
2. Click toggle to load content
3. While content is loading, hit select all check mark
4. View console

Expected: Selected list doesn't include null items
Actual: Selection returns null items as selected.

Overall, I understand why we might, in some cases, want to represent or virtualize the data for items yet to be loaded but it can also cause some issues. Is this the expected behavior? It's easy enough on the feature side to filter out the list to exclude null items but if we multiply that work across all partners that's a lot of work. Can we at least create something like getSelectionWithoutNull or similar? This way it's not a breaking change and solves the issue.

### Priorities and help requested:

Are you willing to submit a PR to fix? Sure?

Requested priority: Normal

Products/sites affected: Any using Selection or DetailsList.

**Comment by ecraig12345** [comment]
Thanks for reporting this and for the codepen. I'm honestly not sure what the original expected behavior was here (or if anybody thought through this case), but at this point I'm very hesitant to change the behavior due to risk of regression for partners, especially since there's a straightforward workaround.
