### ISSUE TITLE
Coachmark is not working in dialog w/ React 17

### ISSUE THREAD

**Issue by t-w-in** [microsoft/fluentui#16290]
#### Actual behavior:

**In Dialog**:
Teaching bubble does not show up when mouse is over Coachmark. 

#### Expected behavior:

**In Dialog**:
Teaching bubble should show up when mouse is over Coachmark. 

### Priorities and help requested:

Are you willing to submit a PR to fix? 
No

Requested priority: Normal

Codepen: https://codepen.io/twin/pen/GRjMMQq

**Comment by t-w-in** [comment]
Still not working. Can you please look into it? @ecraig12345 
Thank you.

**Comment by ecraig12345** [comment]
We don't officially support React 17 yet. We hope to include that as part of version 8 but got hung up on some issues with automated tests--see #15732 for progress.

**Comment by t-w-in** [comment]
Does work now. Thank you. Closing.

**Comment by t-w-in** [comment]
I could have sworn that this did work 2 weeks ago, but it does not now (again?) :(
