### ISSUE TITLE
Accessibility type requires a prop

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#16303]
### Environment Information

- **latest, 0.51.x**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

Currently the [Accessibility type](https://github.com/microsoft/fluentui/blob/6d2b06ccbf54d0cce96d3bf53f9c403e2db88609/packages/fluentui/accessibility/src/types.ts#L177) requires a prop to be passed to the function. 

This poses a problem for behaviours that do not require props which are then typed with `never` such as [GridBehaviorProps](https://github.com/microsoft/fluentui/blob/6d2b06ccbf54d0cce96d3bf53f9c403e2db88609/packages/fluentui/accessibility/src/behaviors/Grid/gridBehavior.ts#L20). It can be tricky to extend these behaviours such as the following example:

```typescript
const customGridBehavior: Accessibility<GridBehaviorProps> = props => {
   ...stuff
};

// TS error: requires an argument
customGridBehavior()
// TS error: nothing will ever coerce to  `never`
customGridBehavior(null)
```

#### Expected behavior:

A few options exist from top of mind:
* Type behavior props different to `never`
* Modify the `Accessibility` type to also include functions without arguments

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Low)

Products/sites affected: (if applicable)
Teams/TMP

**Comment by layershifter** [comment]
### Why `never` was used?

TypeScript handles `{}` as `any`:

```tsx
function A(props: { a: boolean }) {}
function B(props: {}) {}
function C(props: never) {}

//

A({ a: true })
B({ b: true })
C({ c: true })
```

[TypeScript playground](https://www.typescriptlang.org/play?ts=4.1.3#code/GYVwdgxgLglg9mABAQQBQAcBOd0GcBciA3ogIaEBGccANgKalIC+AlMUwLABQoksCiAEIZseQkVbtuvaPCQBhETgKIwdAG51MbCd24B6fXq5oS5RFEwg6iVt2EkKhS9dstuikhGdWbrIA)

While `never` works as an expected in this case. However, `never` is not assignable to any type 😿 I've seen a proposed solution in #16322, but we try to use `null` instead?

```tsx
type GridBehaviorProps = null

// ---

const customBehavior = Accessibility<GridBehaviorProps> = props => {
   ...stuff
};
```

**Comment by ling1726** [comment]
I don't get the point of always requiring a prop, especially when it's not required. From a consumer point of view it IMO this would always raise my eyebrow if I see this

```typescript
// error: expect argument
behaviour()

// error: argument cannot coerce with null
behaviour({})

// this works ???!!!???
behaviour(null)
```

The only consistent thing would be the below example, but still seems kinda unnecessary

```typescript
type GridBehaviorProps = null | undefined | {}
```
