### ISSUE TITLE
Add comma to numbers under fraction mode in HorizontalBarChart

### ISSUE THREAD

**Issue by cariceli** [microsoft/fluentui#16320]
#### Describe the feature that you would like added

Add comma to numbers under fraction mode in HorizontalBarChart

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots
Actual:
![image](https://user-images.githubusercontent.com/42231272/103334465-583aa200-4aac-11eb-92db-f45d21e27554.png)

Expected:
![image](https://user-images.githubusercontent.com/42231272/103334335-db0f2d00-4aab-11eb-8454-6b2fc7b9cd5f.png)

**Comment by ecraig12345** [comment]
@Raghurk's team owns HorizontalBarChart, so he or a team member would need to consider this request.
