### ISSUE TITLE
☂ Menu: Issues to consider in converged approach

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#16334]
This is an epic issue to track the open issues to consider in the converged approach:

Active issues that need investigation:
- #7162

Open issues that need fixing:
- ...

Other related issues:
- ...

**Comment by layershifter** [comment]
Do we have a spec for `Menu` component?

---

## Shorthand API

Linking a comment in another issue: https://github.com/microsoft/fluentui/issues/15929#issuecomment-754001698. As it's important to have an agreement about API as this component can easily become a pattern.

With @assuncaocharles we spent some time trying to prototype an API that can easily scale with infinite amount of nested menus:

```tsx
<Menu>
  <MenuTrigger>
    <div>Open Menu</div>
  </MenuTrigger>
  <MenuList>
    <MenuItem index={1}>Item 1</MenuItem>
    <MenuItem index={2}>Item 2</MenuItem>
    <MenuItem index={3}>Item 3</MenuItem>
    <MenuItem index={4}>Item 4</MenuItem>
  </MenuList>
</Menu>
```

A real life example is under prototypes in Fluent Northstar:
https://github.com/microsoft/fluentui/blob/5902550fbcf3c281d9ab6e01f3002dc85b710531/packages/fluentui/react-northstar-prototypes/src/prototypes/MenuList/MenuButton.tsx#L23-L26

## What is `Menu`?

![A menu in Semantic UI](https://user-images.githubusercontent.com/14183168/103547234-6d487400-4ea4-11eb-881d-bbb5c2518654.png)

![A menu in Fluent UI Northstar](https://user-images.githubusercontent.com/14183168/103547305-851ff800-4ea4-11eb-991a-8c90e2e6fb20.png)

vs.

![A menu in Reach UI](https://user-images.githubusercontent.com/14183168/103547366-9bc64f00-4ea4-11eb-8e0d-65c33b8d2ea7.png)

![A menu in Adobe Spectrum](https://user-images.githubusercontent.com/14183168/103547403-a54fb700-4ea4-11eb-8d0e-c39067b4678f.png)

For me, it's an interesting piece as these components actually behave differently (I mean red & green boxes):

![A menu with a sub menu in Northstar](https://user-images.githubusercontent.com/14183168/103547766-2018d200-4ea5-11eb-8406-fa814f49a17c.png)

What is actually `Menu` in this case?

**Comment by ling1726** [comment]
closing since there is only one linked issue in the description which I replied to and the spec for the `Menu` is already reviewed and maintained in the repo
