### ISSUE TITLE
Pivot Overflow Menu + headerOnly issue

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/fluentui#16342]
### Environment Information

- **Package version(s)**: 8.0.0-beta.32
- **Browser and OS versions**: Edge Version 87.0.664.66

### Please provide a reproduction of the bug in a codepen:  
https://codepen.io/LeSchmoo/pen/XWjELra

#### Actual behavior:

Overflow menu appears behind the "tab" body (pink in this example with opacity = 50%):
![image](https://user-images.githubusercontent.com/966863/103536548-a4119080-4e8a-11eb-8369-f6c4fab3513b.png)

#### Expected behavior:

Overflow menu to appear on top of "tab" body

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by layershifter** [comment]
@GordonSmith thanks for reporting, this looks like a valid issue 💭 

I checked and a proper `zIndex` on Callout or layers should solve the issue, however as I see `doNotLayer` is used intentionally:

https://github.com/microsoft/fluentui/blob/20f3d664a36c93174dc32786a9d465dd343dabe5/packages/react-tabs/src/components/Pivot/Pivot.base.tsx#L226

@behowell can you please suggest a proper workaround or a fix for this case?

**Comment by behowell** [comment]
It looks like removing `doNotLayer` will work. I think I originally added it to work around another bug, but the overflow seems to be working fine without it now.
