### ISSUE TITLE
itemLimit attr on ListPeoplePicker doesn't work

### ISSUE THREAD

**Issue by allensu0314** [microsoft/fluentui#16367]
### Environment Information

- **Package version(s)**: Latest version. The bug can repro using demo code in fluent official website at codepen.
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

codepen : https://codepen.io/allensu0314/pen/mdrLMxR.
I added `itemLimit={2}` in `ListPeoplePicker`, but doesn't work.
#### Actual behavior:
ListPeoplePicker can select all items over I expected.

#### Expected behavior:
ListPeoplePicker should only select  the pescibed number of items as `itemLimit` shows.

**Comment by layershifter** [comment]
@Chen-Su thanks for reaching us 👍 

@joschect I briefly checked the implementation of `ListPeoplePicker` that extends `BasePickerListBelow` and it does not seem that anything related to `itemLimit` is implemented there. Can you please elaborate?

**Comment by joschect** [comment]
@layershifter That's correct! I think that it just didn't get implemented. I'll see if I can get that added quickly. Thanks for the investigation!
