### ISSUE TITLE
Looking forward to Fluent UI based on Vue.js

### ISSUE THREAD

**Issue by yn-tadpole** [microsoft/fluentui#16389]
#### Looking forward to Fluent UI based on Vue.js.

Vue.js Compared with react, it should be a more potential framework. I hope the project team can consider the development of Vue.js Version of.

**Comment by layershifter** [comment]
@yn-tadpole it's a duplicate of https://github.com/microsoft/fluentui/issues/14334. @paulgildea have already provided there a great reply: https://github.com/microsoft/fluentui/issues/14334#issuecomment-671592447.
