### ISSUE TITLE
When page is resized to 400% zoom mode, controls are not visible/missing in the page

### ISSUE THREAD

**Issue by lipalath-ms** [microsoft/fluentui#16380]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^7.123.4"
- **Browser and OS versions**: chrome and windows 11

### Describe the issue:

When page is resized to 400% zoom mode, controls are not visible/missing in the page. Placeholder in textbox gets truncated.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/lipalath/pen/NBVZWJ

#### Actual behavior:

![image](https://user-images.githubusercontent.com/6519992/103708842-35a20080-4f66-11eb-829b-c16cc52b4597.png)

#### Expected behavior:

All the controls should be visible and not truncated when the page is zoomed to 400%.

**Comment by ecraig12345** [comment]
This looks like an issue with a product page overall, not with specific Fluent UI controls. For each Fluent UI control which you think has a problem, please file a separate issue with an isolated CodePen repro. You can either start from the "Export to CodePen" button available on most of our [control examples](https://developer.microsoft.com/en-us/fluentui#/controls/web), or from https://aka.ms/fluentpen.
