### ISSUE TITLE
Unselected Pivot items are not focusable

### ISSUE THREAD

**Issue by lutorre** [microsoft/fluentui#16384]
### Environment Information

- **Package version(s)**: @fluentui/react 7.129.0
- **Browser and OS versions**: Windows 10, Microsoft Edge 87.0.664.66 (Official build) (64-bit)

### Describe the issue:

Unselected pivot items are not focusable.
Example:
1- Open a Pivot item in the browser and select the first one
2- Use the TAB key to traverse the components until the first Pivot item is focused
3 - Use TAB key again and observe the result

### Please provide a reproduction of the issue in a codepen:
This issue can be reproduced using the Pivot examples provided in the [Fluent UI documentation](https://fabricweb.z5.web.core.windows.net/oufr/7.153.2/#/examples/pivot)

#### Actual behavior:

The second and third Pivot items are skipped 

#### Expected behavior:

The second Pivot item is focused so it cab be selected using the keyboard

**Comment by layershifter** [comment]
@lutorre thanks for reaching us.

> Once you tab into the pivot, you can use the arrow keys to select the other pivot items.

https://github.com/microsoft/fluentui/issues/13170#issuecomment-629359547

![Using keyboard to navigate through items](https://user-images.githubusercontent.com/14183168/104911051-8e23c580-598a-11eb-86c8-2d940dfe8df4.gif)

I am missing something?
