### ISSUE TITLE
When user try to close the combo boxes by escape key in Panel control, entire Panel is closing

### ISSUE THREAD

**Issue by prademi** [microsoft/fluentui#16390]
**Test Environment:**

- OS : Win 10 1909 (OS Build 18363.476)
- Browser : Chrome (78.0.3904.70), Edge (44.18362.449.0)

**Actual Result:**
-- Combobox control added in Panel Control.
-- One of the combobox expanded.
-- On click of escape. complete Panel control is getting closed.

**Expected Result:**

-- Combobox control added in Panel Control.
-- One of the combobox expanded.
-- On click of escape. complete Panel control is getting closed.
-- By pressing Escape key to close the below combo boxes entire Panel should not be closed.

**WCAG Reference:**

https://www.w3.org/WAI/WCAG21/Understanding/on-focus

 
![image](https://user-images.githubusercontent.com/65328772/103749474-8def0600-502b-11eb-9a7c-feabc91fe88e.png)

**Comment by gouttierre** [comment]
@prademi  - thanks for the feedback.

Please, can you provide more details into the issue. What version of fluent lib are you using? Do you have a codepen sample that we can analysis and repo the problem stated? Thanks and regards
