### ISSUE TITLE
Add onRenderHeaderContent to Panel component

### ISSUE THREAD

**Issue by AbdouMoumen** [microsoft/fluentui#16404]
#### Describe the feature that you would like added

The `Panel` component supports customizing the footer through an `onRenderFooterContent` prop, but the same isn't available for header. It is possible to provide an `onRenderHeader` prop, but it means losing the default rendering logic/styles.

#### What component or utility would this be added to

Panel

#### Have you discussed this feature with our team, and if so, who

No

**Comment by layershifter** [comment]
@AbdouMoumen thanks for creating an issue 👍 

Can you please clarify your use case? As I see `headerText` does pretty the same thing as `onRenderFooterContent()`:

https://github.com/microsoft/fluentui/blob/ef6b2396fc17e9f9c3d7746121b4b632a37fb3d8/packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx#L375

https://github.com/microsoft/fluentui/blob/ef6b2396fc17e9f9c3d7746121b4b632a37fb3d8/packages/office-ui-fabric-react/src/components/Panel/Panel.types.ts#L80

The single problem that I see is that `headerText` has `string` type and it's impossible to pass JSX elements there. Is it an issue that you're expiriencing?

**Comment by AbdouMoumen** [comment]
@layershifter yes, that is precisely the issue we ran into. We need more customization than just setting the text of the header.
