### ISSUE TITLE
Line chart should show the latest data when switching data range after selecting multiple legends

### ISSUE THREAD

**Issue by cariceli** [microsoft/fluentui#16406]
### Environment Information

- **Package version(s)**:  4.11.0
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/stupefied-germain-pbp96?file=/src/Chart.tsx

#### Actual behavior:

steps:
1. Select data range as data1, and select multi legends:
![image](https://user-images.githubusercontent.com/42231272/104152665-2a921900-541b-11eb-99e1-646d19ee8fa9.png)

2. then you select data range as data2, the line chart still show old data:
![image](https://user-images.githubusercontent.com/42231272/104152679-38479e80-541b-11eb-91c4-c9e58edac6c2.png)

#### Expected behavior:

After selecting multi legends, the line chart should show the latest data when you switch data range
![image](https://user-images.githubusercontent.com/42231272/104152699-45fd2400-541b-11eb-9b95-375febab7c7f.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by Raghurk** [comment]
Thanks for reporting. I will follow up on this.

**Comment by cariceli** [comment]
It can be fixed by adding a key to lineChart.
