### ISSUE TITLE
Expose "imageRole" on the IPersonaSharedProps in order to define a custom role to the underlying image

### ISSUE THREAD

**Issue by cristighr1995** [microsoft/fluentui#16400]
#### Describe the feature that you would like added

I would really like to have an `imageRole` attribute exposed on the IPersonaSharedProps since I needed to override / set the role of the underlying PersonaCoin image to 'presentation'. I couldn't to that very easy and I needed to pass a custom render function for the image itself.

I didn't want to replace the whole image with my own custom control, but only set the role of the underlying image. My custom render function is almost 100% the same implementation as the default one so I guess it makes sense to expose this attribute as optional so that others can simply set it in case they want a custom role.

#### What component or utility would this be added to

Persona Component

**Comment by layershifter** [comment]
Hey @cristighr1995!

Can you please clarify on which element you would like to override `role`?

```html
<div class="ms-Persona ms-Persona--size48 root-100">
  <div role="presentation" class="ms-Persona-coin ms-Persona--size48 coin-50">
    <div role="presentation" class="ms-Persona-imageArea imageArea-101">
      <div
        class="ms-Image ms-Persona-image image-104"
        style="width: 48px; height: 48px;"
      >
        <img
          class="ms-Image-image is-loaded ms-Image-image--cover ms-Image-image--portrait is-fadeIn image-99"
          src="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/persona-female.png"
          alt=""
        />
      </div>
    </div>
  </div>
</div>
```

It's possible to override `ms-Persona-coin` & `ms-Persona-imageArea`:

```jsx
<Persona
  imageUrl={TestImages.personaFemale}
  imageInitials="AL"
  coinProps={{
    role: "FOO",
    coinProps: { role: "BAR" }
  }}
/>
```

```html
<div class="ms-Persona ms-Persona--size48 root-100">
  <div role="FOO" class="ms-Persona-coin ms-Persona--size48 coin-50">
    <div role="BAR" class="ms-Persona-imageArea imageArea-101">
      <div
        class="ms-Image ms-Persona-image image-104"
        style="width: 48px; height: 48px;"
      >
        <img
          class="ms-Image-image is-loaded ms-Image-image--cover ms-Image-image--portrait is-fadeIn image-99"
          src="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/persona-female.png"
          alt=""
        />
      </div>
    </div>
  </div>
</div>
```

---

Please let me know if it works for you.
