### ISSUE TITLE
Make Fluent UI more consistent with Windows UI library

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/fluentui#16421]
I love a lot of things that are unique in WinUI and would like to see them in Fluent UI as well. Some are hard in a web browser but at least some level of consistency can be achieved. Someone has created [wincss](https://github.com/Tropix126/wincss) with some Windows-like style which you could check out and decide.

**Comment by Tropix126** [comment]
> Someone has created wincss with some Windows-like style which you could check out and decide.

I might note that these styles are still under very heavy development, as I only started them yesterday. It would be nice to see some consitency between the XAML controls and these react components, as they currently feel like two completely different design languages at the moment.

**Comment by tafen** [comment]
Hi @Jaiganeshkumaran, are there specific examples of items from WinUI that you find useful to be included in Fluent UI? We do actively work with our Windows counterparts on aligning our design language directions, so definitely in the works!
