### ISSUE TITLE
Calendar auto-opens when user uses shift+tab to move focus back into the datepicker

### ISSUE THREAD

**Issue by sachinmrao** [microsoft/fluentui#16435]
### Environment Information

- **Package version(s)**: "7.147.1", "7.155.3"
- **Browser and OS versions**: Chrome, Edge on Win 10

### Describe the issue:

On non-editable datepicker, the calendar auto-opens when user uses shift+tab to move focus back into the datepicker.
This is reproducible on the demo site here - https://developer.microsoft.com/en-us/fluentui?fabricVer=7#/controls/web/datepicker
[Attached video]

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/sachinmrao/pen/NWRLmVb

#### Actual behavior:
Calendar auto opens on receiving focus in textbox, when user uses shift+tab to focus on the datepicker

#### Expected behavior:
Calendar should not auto open
![a11y datepicker](https://user-images.githubusercontent.com/41659738/104250729-0fc3a280-5423-11eb-8655-3785ec5c59bf.gif)

**Comment by gouttierre** [comment]
@sachinmrao - Thanks for the feedback. 

@khmakoto  - Would you be able to determine if this is a regression or if this behavior is an issue for the DatePicker?

**Comment by khmakoto** [comment]
Hi @sachinmrao, this is expected behavior in the `DatePicker`. If you don't want the `Calendar` to open up just pass the `disableAutoFocus` prop to the `DatePicker`.
