### ISSUE TITLE
Support stop-color with IStyle + Styled HOC

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#16437]
#### Describe the feature that you would like added

We have some svg stops that we're styling as part of a styled HOC.

Because stopColor isn't part of the IStyle interface, I have to assign their colors in the base component like a caveman, rather than the styles file.

#### What component or utility would this be added to

IRawStyleBase (I think)

#### Have you discussed this feature with our team, and if so, who

Negative.

#### Additional context/screenshots

We're currently depending on ^7.135.0, so I'm not sure if this has been fixed in V8.

**Comment by gouttierre** [comment]
@mltejera thanks for the query.

This has not been prioritized as if yet for v8 but will be added to the backlog. We’re currently focusing on improvements to performance and coherence, as you can see in our pinned issue on the repo detailing our [v8 plans](https://github.com/microsoft/fluentui/issues/12770).  Though. we don’t plan to address this right now, we will take it into consideration when we schedule future work for extending our styles base. Thank you for reaching out to us.
