### ISSUE TITLE
Caret position moves on changing input type and focusing on it

### ISSUE THREAD

**Issue by faizal3199** [microsoft/fluentui#16457]
### Environment Information

- **Package version(s)**: Tested on 7.155.1
- **Browser and OS versions**: Edge (New), Chrome on Windows 10

### Details

When an following two actions happen simultaneously then caret position/selection moves to the start.
1. Focusing on input
2. Changing the input field's type.

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/faizal-hasanwala/pen/XWKpmNK?editors=0010

#### Actual behavior:

The caret position moves to the start.

#### Expected behavior:

The caret position or selection should retain original position/selection.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Blocking

Products/sites affected: Excel Online

**Comment by faizal3199** [comment]
Can we extend the logic to retain selection to type change scenarios too? Currently, it is only for input to text area and vice versa scenarios.
CC: @ecraig12345

**Comment by layershifter** [comment]
@faizal3199 thanks for reporting, but I don't think that it's a library issue 🤔

---

I created a CodeSandbox with native elements (https://codesandbox.io/s/cool-bush-z8ow2?file=/src/App.js) to check browsers/React behavior and it behaves in the same way. I also performed tests with keyboard to understand focus behavior:

![Focus native inputs via Tab](https://user-images.githubusercontent.com/14183168/104456134-86d67380-55a8-11eb-929f-155865cb4c42.gif)

For me it looks that browsers don't keep caret position in inputs by default. 

---

To workaround this, you can manage caret position manually via `selectionStart`/`selectionEnd`, it will do what is expected in this case:

```tsx
React.useEffect(() => {
  inputRef.current.focus();

  inputRef.current.selectionStart = inputCaretPosition.current.caretStart;
  inputRef.current.selectionEnd = inputCaretPosition.current.caretEnd;
}, [type]);
```

⚠️ Manage both `selectionStart` and `selectionEnd` is important as you can have a selection in your input. Another important thing is too listen for `onSelect` event:

![Using selectionStart and selectionEnd with onSelect handler](https://user-images.githubusercontent.com/14183168/104458125-3ca2c180-55ab-11eb-95f5-fc0304ab75b5.gif)

A ready to go snippet is there: https://codesandbox.io/s/sharp-cori-2msl1?file=/src/App.js

The similar problems were also discussed in React issue, leaving it there for reference https://github.com/facebook/react/issues/955.

---

Please let me know if it works for you 👍

**Comment by faizal3199** [comment]
Thanks @layershifter
