### ISSUE TITLE
In a Grouped List, number of children aren't being announced by Narrator

### ISSUE THREAD

**Issue by bcoard** [microsoft/fluentui#16471]
### Environment Information

- **Package version(s)**: ^7.155.1
- **Browser and OS versions**: Chromium Edge; OS Version 1903/18362.10000

### Describe the issue:

When navigating through a grouped list with Narrator, the user should know how many children any given group header has. The number is displayed for visual users but is never announced for Narrator users. This also repros in a Grouped Details List.

The Group List document page could be used as a repro: https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist

### Please provide a reproduction of the issue in a codepen:

1. Turn Narrator on.
2. Using keyboard commands navigate to a group header item (in a Grouped List).

#### Actual behavior:

Narrator doesn't announce the number of children a Grouped List has.

#### Expected behavior:

Narrator should announce the number of children a Grouped List has.

**Comment by kolaps33** [comment]
The accessibility role used in the component is "treegrid" and we have been looking into it on aria example page:
**https://www.w3.org/TR/wai-aria-practices-1.1/examples/treegrid/treegrid-1.html**

and there is no narration of "number of children" for JAWS, NVDA and Narrator as well. 

Please could you specify source of the requirement? thank you.

**Comment by bcoard** [comment]
Thanks for the feedback @kolaps33! That's a fair point. This change might not be needed satisfy an accessibility role requirement but this change should improve the accessible usability for users. From a visual POV, users are shown a grouped list with a parent/child relationship and each parent that has children (group headers) also includes the number of children in the header string. For non-sighted users, since the title/name of the group header doesn't include the same number that sighted people see, they are missing out on valuable information. Using the most appropriate Aria property to announce the number of children should help alleviate this delta.

**Comment by layershifter** [comment]
@bcoard thanks for the clarification, I will open a PR to update `aria-label` shortly ⌛

**Comment by bcoard** [comment]
@layershifter someone else ran in to another issue in a similar area today. Is the below issue at all related? If the correct role as a child was set, would screen readers automatically read the number of children?

![image](https://user-images.githubusercontent.com/16261692/105409159-e3f3aa00-5be4-11eb-9cae-8da93d749f98.png)

**Comment by layershifter** [comment]
> someone else ran in to another issue in a similar area today. Is the below issue at all related?

This looks like a completely separate issue, feel free to report it 👍

> If the correct role as a child was set, would screen readers automatically read the number of children?

A title that screen readers will use is defined by `aria-label`, I don't see how role change fix it :(

**Comment by smhigley** [comment]
Fixed in #15809
