### ISSUE TITLE
I cannot find typical Tab component on the website?

### ISSUE THREAD

**Issue by kaushalyap** [microsoft/fluentui#16489]
I am evaluating Fluent UI for a project but I cannot find the tab and pagination components. Is it there?

**Comment by layershifter** [comment]
> The Pivot control and related tabs pattern are used for navigating frequently accessed, distinct content categories.

@kaushalyap I think that you're looking for Pivot component: https://developer.microsoft.com/ru-ru/fluentui#/controls/web/pivot

---

`Pagination` component is available under [`@fluentui/react-expirements`](https://github.com/microsoft/fluentui/tree/master/packages/react-experiments) package, but it seems that it's in stale state (see #7254 for tracking the progress)
