### ISSUE TITLE
Keyboard navigation not working for farItems(right side component) in CommandBar

### ISSUE THREAD

**Issue by SummerCat200** [microsoft/fluentui#16501]
### Environment Information

- **Package version(s)**: 7.149.4
- **Browser and OS versions**: Edge

### Describe the issue:

We can't use keyboard to navigate to right side buttons in CommandBar
### Please provide a reproduction of the issue in a codepen:
Used same code as shown in doc site(https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar)

#### Actual behavior:
Right side buttons are not accessible with keyboard

#### Expected behavior:
Right side buttons should be accessible with keyboard

**Comment by SummerCat200** [comment]
any updates?

**Comment by layershifter** [comment]
@SummerCat200 can you please post detailed repro steps and a Codepen example?

I checked it in latest Chrome and Edge, it works as expected 💭 

![Navigation with keys in CommandBar](https://user-images.githubusercontent.com/14183168/105193981-6e7ecf80-5b39-11eb-8ce9-baff8479f11a.gif)

**Comment by SummerCat200** [comment]
> @SummerCat200 can you please post detailed repro steps and a Codepen example?
> 
> I checked it in latest Chrome and Edge, it works as expected 💭
> 
> ![Navigation with keys in CommandBar](https://user-images.githubusercontent.com/14183168/105193981-6e7ecf80-5b39-11eb-8ce9-baff8479f11a.gif)

Thanks @layershifter It works fine if we use arraw keys to navigate, but can we only use tab to move between buttons? or is it by design that we should only use arrow keys to navigate?

**Comment by SummerCat200** [comment]
@layershifter Another question is if we have `SearchBox` or `TextField` in items or faritems, using arrow keys to navigate seems a little weird, because arrow keys are used to navigate between the characters, and they are also used to move between controls. Do we have a better solution for that?

**Comment by layershifter** [comment]
> or is it by design that we should only use arrow keys to navigate?

It's by design, `Pivot` implements `role="menubar"`, according to https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html:



|Key | Function |
| -- | -- |
| <kbd>Right Arrow</kbd> | Moves focus to the next item in the menubar. If focus is on the last item, moves focus to the first item. |
| <kbd>Left Arrow</kbd> | Moves focus to the previous item in the menubar. If focus is on the first item, moves focus to the last item. |
