### ISSUE TITLE
updating react-northstar docs for Provider

### ISSUE THREAD

**Issue by zcaudate** [microsoft/fluentui#16506]
There current examples for theming are outdated:

https://fluentsite.z22.web.core.windows.net/0.51.4/theming

I was struggling with just changing the `brand` color and found another with the same issue https://stackoverflow.com/questions/64916099/custom-teams-theming-with-fluentui-react-northstar

by luck, the method I tried worked so I was able to provide an answer but  the current documentation needs to be updated and a couple more examples added.

**Comment by gouttierre** [comment]
@zcaudate  - thanks for pointing this out. 
I’ll mark this as a document request and add it to our backlog, but we’re likely not going to get to it right away, but will be updating our documentation in parallel as we focus on the larger coherence efforts and enhancements to our overall performance.
