### ISSUE TITLE
ALT attribute is not defined for the info icon Present in "MessageBar" control

### ISSUE THREAD

**Issue by prademi** [microsoft/fluentui#16511]
**Impact:​**

Users who rely on screen readers will find difficult to understand the context of the image, if 'Alt' attribute is not defined for info icon in MessageBar control

**Test Environment:​**

OS : Win 10 1909 (OS Build 18363.476)

Browser : Chrome (78.0.3904.70), Edge (44.18362.449.0)

Tools used: NVDA 2019.2.1, JAWS 2019.1909.28, Narrator

 
**Actual Result:**

Alt' attribute is not defined for the info icon image present in MessageBar control. Also Screen reader(NVDA/JAWS/Narrator focus does not moves to the info icon.

 

**Expected Result:**

'Alt' attribute should be defined for the 'info icon image present in MessageBar control.

Ex: alt="information"

Also Ensure that Screen reader(NVDA/JAWS/Narrator) focus should move to the ‘info icon' image present in MessageBar control " 

Also on pressing Graphic keystroke(G), Screen reader(NVDA/JAWS/Narrator) should identify the ‘info icon' image and narrate its alt value.

![image](https://user-images.githubusercontent.com/65328772/104911502-f4bbda00-59b0-11eb-8d10-71f2aa3d4b59.png)

**Comment by layershifter** [comment]
I believe that we are talking about this example:

```tsx
<MessageBar messageBarType={MessageBarType.warning} isMultiline={false}>
  Warning MessageBar content.
  <Link href="www.bing.com" target="_blank">
    Visit our website.
  </Link>
</MessageBar>
```

https://codesandbox.io/s/cranky-jackson-x8z5l

---

It will produce the following simplified HTML:

```html
<div class="ms-MessageBar ">
  <div class="ms-MessageBar-content">
    <div class="ms-MessageBar-icon" aria-hidden="true">
      <i aria-hidden="true"></i>
    </div>
    <div role="status" aria-live="polite">
      <span class="ms-MessageBar-innerText">
        <span>Warning MessageBar content.</span>
      </span>
    </div>
  </div>
</div>
```

An icon is hidden there intentionally as is used as a decorative content:

> Adding aria-hidden="true" to an element removes that element and all of its children from the accessibility tree. This can improve the experience for assistive technology users by hiding:
> - purely decorative content, such as icons or images

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute
