### ISSUE TITLE
TooltipHost warnings in console

### ISSUE THREAD

**Issue by 4Lexs4nder** [microsoft/fluentui#16520]
### Environment Information

- **Package version(s)**: 
` "dependencies": {
    "@fluentui/react": "^7.155.4",
    "@fluentui/theme": "^1.7.1",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.3",
    "@testing-library/user-event": "^12.6.0",
    "@types/jest": "^26.0.20",
    "@types/node": "^12.19.14",
    "@types/react": "^16.14.2",
    "@types/react-dom": "^16.9.10",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1",
    "typescript": "^4.1.3",
    "web-vitals": "^0.2.4"
  },`

### Describe the issue:
In console these errors appear:

```
Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.
* Move code with side effects to componentDidMount, and set initial state in the constructor.
Please update the following components: CalloutContentBase, Popup
```

```
Warning: Using UNSAFE_componentWillUpdate in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.
* Move data fetching code or side effects to componentDidUpdate.
Please update the following components: CalloutContentBase
```

#### Expected behavior:
To work without warnings.

**Comment by layershifter** [comment]
@4Lexs4nder thanks for reporting, fixes to be compliant with React's Strict Mode were done in v8, https://github.com/microsoft/fluentui/issues/12770#user-content-react-strict-mode-support.

@ecraig12345 can correct me, but I don't think that we plan to backport them to v7.

**Comment by ecraig12345** [comment]
@layershifter is correct, we don't plan to back-port strict mode fixes to version 7.
