### ISSUE TITLE
Support for RTL at component level.

### ISSUE THREAD

**Issue by abhishekdgeek** [microsoft/fluentui#16521]
### Environment Information

- **Package version(s)**: 7.147.0

### Describe the issue:

Support for RTL/LTR at component level and not just at document level. As per my understanging, currently office-ui-fabric-react only support handling of RTL layouts (style translations via mergeStyles) on basis of document's direction.

In world of collaboration this may not fit all scenarios and there can be components that are LTR while some are RTL in same document. Ask here is to provide support for RTL/LTR at component level.

#### Actual behavior:

mergeStyles determines whether page is LTR or RTL.

#### Expected behavior:

mergeStyles determines whether component is LTR or RTL.

### If applicable, please provide a codepen repro:
N/A

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Maybe

Requested priority: Normal

Products/sites affected: None, as I am conditionally inversing the styles manually before feeding them to mergeStyles.

**Comment by dzearing** [comment]
`mergeStyles` does not know about components, so it is impossible for that layer to do what you're asking.

However, above that layer, it's perfectly feasible. In fact, using 7.147.0, you can do that today:

```tsx
<Fabric dir="ltr">
  <TextField placeholder="I'm LTR"/>
  <Fabric dir="rtl">
     <TextField placeholder="I'm RTL" />
   </Fabric>
</Fabric>
```

Example sandbox here: https://codesandbox.io/s/nested-rtl-x3ce6?file=/src/App.tsx

Note: In future releases the Fabric component will be replaced by `ThemeProvider` component, which also has the `dir` attribute.
