### ISSUE TITLE
itemLimit doesn't work in ListPeoplePicker

### ISSUE THREAD

**Issue by llloadinglll** [microsoft/fluentui#16531]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: chrome

### Please provide a reproduction of the bug in a codepen:

itemLimit doesn't work in ListPeoplePicker

https://codepen.io/lloadingll/pen/BaLbKey
I added itemLimit={1} at line 112

some other types of  peoplepicker can work correctly

### Priorities and help requested:

Requested priority: Blocking

Products/sites affected: Microsoft SCC. work in progress

**Comment by layershifter** [comment]
Duplicate of #16367.
