### ISSUE TITLE
Fluent UI - React Northstar. Dialog component doesn't support scroll on touch event

### ISSUE THREAD

**Issue by AndreyButyrchik** [microsoft/fluentui#16530]
### Environment Information

- @fluentui/react-northstar - 0.51.2
- Google Chrome Version 86.0.4240.183

### Please provide a reproduction of the bug in a codepen:

Cannot scroll content inside dialog on mobile devices. `touchmove` event fires but `scroll` event doesn't fire for some reason.
https://codesandbox.io/s/stoic-moore-nxvjx?file=/src/index.tsx

#### Actual behavior:

Cannot scroll content inside dialog on mobile device

#### Expected behavior:

Can scroll content inside dialog on mobile device

**Comment by ling1726** [comment]
@assuncaocharles  once the nightly build for your PR goes in can you please post a working codesandbox of the original issue ?
