### ISSUE TITLE
react-northstar error: Warning: Cannot update a component (`MenuItem`) while rendering a different component

### ISSUE THREAD

**Issue by zcaudate** [microsoft/fluentui#16569]
I'm not sure why this is happening. I'm using the HashRouter with Menu and it's giving this error whenever the link changes. The error is really cryptic and I'm wondering why it may be happening. If necessary, I can provide a simple example repo.

```
react-dom.development.js:88 Warning: Cannot update a component (`MenuItem`) while rendering a different component (`ContextSelector.Provider`). To locate the bad setState() call inside `ContextSelector.Provider`, follow the stack trace as described in https://fb.me/setstate-in-render
    in ContextSelector.Provider (created by Menu)
    in ul (created by FocusZone)
    in FocusZone (created by Menu)
    in Menu (at frame.jsx:36)
    in div (created by Flex)
    in Flex (at frame.jsx:35)
    in FrameHeader (at frame.jsx:101)
    in div (at frame.jsx:95)
    in div (created by Provider)
    in RendererProvider (created by Provider)
    in Provider (created by Provider)
    in Provider (at frame.jsx:94)
    in Router (created by HashRouter)
    in HashRouter (at frame.jsx:93)
    in FrameLayout (at App.jsx:57)
    in App (at main-inner.jsx:9)
```

**Comment by zcaudate** [comment]
@layershifter: I've uploaded a repo you can play with [here](https://github.com/zcaudate/play.bug-fluentui-menu):

<img width="934" alt="Screen Shot 2021-01-22 at 3 19 49 am" src="https://user-images.githubusercontent.com/1455572/105402311-3c1cc180-5c62-11eb-86b3-6d3bda68cca2.png">

**Comment by jurokapsiar** [comment]
we will take this in the current sprint (Jan 25 to Feb 7). Thanks for reporting @zcaudate

**Comment by layershifter** [comment]
We actually need to port latest changes from https://github.com/dai-shi/use-context-selector:

> Prior to v1.3, it uses changedBits=0 feature to stop propagation, v1.3 no longer depends on this undocumented feature.

**Comment by zcaudate** [comment]
I'm still getting an error  using v0.52.0, react 17.0.1

----

the repo is here: https://github.com/zcaudate/play.bug-fluentui-menu

<img width="1215" alt="Screen Shot 2021-02-16 at 2 15 34 pm" src="https://user-images.githubusercontent.com/1455572/108025491-862a7480-7061-11eb-80a1-c52369309a31.png">

**Comment by zcaudate** [comment]
![Uploading Screen Shot 2021-02-16 at 2.15.34 pm.png…]()

**Comment by assuncaocharles** [comment]
Hey @zcaudate 

The change is yet not released

**Comment by zcaudate** [comment]
@assuncaocharles: sweet, can you ping me when it has?
