### ISSUE TITLE
React-button font size to be adjustable

### ISSUE THREAD

**Issue by imdavidmin** [microsoft/fluentui#16562]
#### Describe the feature that you would like added

Since we are able to adjust the size of the button with enums (and iconSize in ButtonTokens), would be good to also have same way to adjust the size of font inside the button. Otherwise you could have a small button with a huge text. Preferably having this accessible through the ButtonToken as well.

#### What component or utility would this be added to

React-button (v8)

#### Have you discussed this feature with our team, and if so, who

No

**Comment by gouttierre** [comment]
@imdavidmin - thanks for the feedback and suggestion. We have flag this in #16819 epic for future development on the button. 
In the mean time, I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.

**Comment by khmakoto** [comment]
This should be adjustable by passing a classname to the component now according to our new approach.

@imdavidmin let me know if you want more information, otherwise closing this.
