### ISSUE TITLE
Searchable Dropdown

### ISSUE THREAD

**Issue by Shraddha-113** [microsoft/fluentui#16566]
We have requirement for searchable dropdown. Can you provide option for search in dropdown? We tried comboBox also. It doesn't work and UI gets disturbed. So, we want dropdown enhancement. Can you provide it? Or can you suggest some other options?

**Comment by gouttierre** [comment]
@Shraddha-113 - Thanks for reaching out. Yes, this a popular request, and is on our radar. Another similar request is #14128. Where the user tried the react-sementic dropdown as a work around.

But I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. But as we start to converge our `Dropdown `component we'll take this into consideration.

**Comment by Fuzkin** [comment]
@gouttierre I understand the need for enhancing performance BUT fluent ui in this state is so lacking that it is hard to recommend it to anyone. It looks and feels great but these issues like searchable dropdown or ChoiceGroup not having the errorMessage and all other missing features just makes all the development hard.

**Comment by Rafaelki** [comment]
I have the same request from several clients. 
I have implemented the idea of @LukeOwlclaw in #14128 (replace an option with a search box) in this code pen: https://codepen.io/rafaelki/pen/VwpQoBr?editors=0010 - test writing "ap".
It doesn't look as neat as react-sementic or react-select but it seems to work.
I am having an issue with the focus when I have an option selected. While writing in the search box, I sometimes lose the focus, that goes to the selected item. Anybody can help with this focus issue?

**Comment by Greg-Hitchon** [comment]
@Rafaelki Thanks for the pen! Yeah we also have that issue and without actually testing it looks like it is from the `onPositioned` event within the callout:
![image](https://user-images.githubusercontent.com/3837138/124803320-f2314a80-df26-11eb-917e-abbd6dfab913.png)

As a workaround we just added `responsiveMode={ResponsiveMode.small}` as a workaround which uses the panel instead and avoids the issue. Obviously not ideal, but better than the alternatives (debounce onChange, use onSearch, others?)

See [here](https://codepen.io/Greg-Hitchon/pen/ZEKWqbg).

Let me know if you found a better workaround in the meantime!!
