### ISSUE TITLE
Semantic colors not respected by checked Toggle react-buttons

### ISSUE THREAD

**Issue by imdavidmin** [microsoft/fluentui#16563]
### Environment Information

- **Package version(s)**: 
```
    "@fluentui/react": "8.0.0-beta.33",
    "@fluentui/react-button": "^0.19.0",
    "@fluentui/react-hooks": "^8.0.0-beta.0",
    "@fluentui/react-theme-provider": "^0.18.1",
```

### Please provide a reproduction of the bug in a codepen:
```
import { ThemeProvider, PartialTheme } from '@fluentui/react-theme-provider';
import { ToggleButton } from '@fluentui/react-button';

export default function Dev() {
    const customTheme: PartialTheme = {
        palette: {
            themePrimary: '#00b929',
        },
        semanticColors: {
            buttonBackground: '#ff0000',
            buttonBackgroundHovered: '#ffff00',
            buttonBackgroundChecked: '#ff0000',
            buttonBackgroundCheckedHovered: '#ff0000',
            primaryButtonBackgroundHovered: '#ff0000',
        }
    }
    return (
        <ThemeProvider theme={customTheme}>
            <ToggleButton checked={false} >Works</ToggleButton>
            <ToggleButton checked={true} >Broken</ToggleButton>
            <ToggleButton checked={true} primary>Broken</ToggleButton>
            <ToggleButton checked={false} primary>Works</ToggleButton>
        </ThemeProvider>
    )
}
```

#### Actual behavior:

![image](https://user-images.githubusercontent.com/48481563/105360176-3a1a1a80-5bf0-11eb-8780-f8efcf2d9948.png)

#### Expected behavior:
Styled "Broken" buttons in Red. 
There's also no option to style Primary button in checked state, either normal or hovered.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by imdavidmin** [comment]
May have something similar with #16156

**Comment by ecraig12345** [comment]
#16156 is about the old button, not the react-buttons package. @khmakoto are the new buttons expected to work with semantic colors?

**Comment by khmakoto** [comment]
They are, however I was incorrectly using `buttonBackgroundPressed` instead of `buttonBackgroundChecked`. I'll fix this issue.

**Comment by imdavidmin** [comment]
@khmakoto is there a similar issue for styling toggle primary? Or is there planned support at all?

Thanks for quick replies guys

**Comment by khmakoto** [comment]
@imdavidmin Yeah, same issue there, I'll also fix it in the same PR.
