### ISSUE TITLE
 options for dev:storyboard not working in latest release

### ISSUE THREAD

**Issue by velociwabbit** [microsoft/fluentui#16598]
### Environment Information

- **Package version(s)**:   "fluent-ui-react-repo"  "version": "1.0.0" 
- **Browser and OS versions**:  Windows 10 Pro 2004 build 19041.746 both chrome and Edge

I downloaded the latest zipped version of OUIFR and yarn, yarns start... (I also tried with npm and npm start)
I also tried with node versions  14.0, 15.6.0, 14.3.1 all have same result

When I start up the npm start which collects info on the options the ONLY package that works (instantiates a full storyboard web page) is the web Components option... all the others load up the page and then freeze on the left panel shimmer.

This is a recent phenomena but it happened about 9 months ago as well

 

#### Actual behavior:

 Only the "web-components" package instantiates in the browser correctly

#### Expected behavior:

Each of the OUIFR dev:storyboard options instantiate fully in the browser

 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes  If i can figure out how to fix it. This repo is a bit of a hodge podge of different packages and it is very hard to trace through how things are generated. If there is a map of how things are processed before loading up the packages that would be very helpful (at least for me in order to debug the scripts)

Requested priority: (Blocking but only for demos )

Products/sites affected: OUIFR

**Comment by ecraig12345** [comment]
Downloading a zip file is really only meant for browsing the code, not for using local demo apps or contributing. As such, we unfortunately can't afford to invest time in making that experience work nicely. 

Even if you're not comfortable with using Git, there are many tutorials online that should be able to help get you far enough to follow our [standard getting started instructions](https://github.com/microsoft/fluentui/wiki/Setup) for downloading the repo using Git. Or if you prefer a GUI, you could download [GitHub Desktop](https://desktop.github.com/) and use the "Open with GitHub Desktop" option.

![image](https://user-images.githubusercontent.com/5864305/105773173-55e72e80-5f18-11eb-8191-f9c9f16a9a2e.png)

**Comment by velociwabbit** [comment]
Good to know.

I like downloading the zip because it  is so simple and such a great user experience... download unzip and npm i.
 
I still do not know why there is not a "git zip" that is identical to a "git pull" (or is it fetch?)  only from the browser? 

Don't get me started about the Visual studio version.   

While i have  used git many times... i think i am git dyslexic ( gitslexic? )   to me source is where the water comes from in a river  (which is not how git is architected).  I mess up more with git than i do with any software i  have ever used.

Reminds me of MFC macros for message pumping :)

If i had time (or someone paying me ) I would build a Browser based git interface that would make more sense to mere mortals such as yours truly.   I think the best way to do it would be using three.js and then dragging and dropping back and forth with visual cues on how to do things like merge, rebase, fetch, pull, sit, rollover and play dead :)
