### ISSUE TITLE
Context menu is not showing when MenuButton clicked

### ISSUE THREAD

**Issue by FeodorFitsner** [microsoft/fluentui#16607]
### Environment Information

- **Package version(s)**: @fluentui/react@8.0.0-beta.41, @fluentui/react-button@1.0.0-beta.23
- **Browser and OS versions**: Latest Chromium Edge

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/align-buttons-middle-forked-tww0y?file=/src/App.tsx

#### Actual behavior:

Context menu is not showing when button clicked.

#### Expected behavior:

Context menu is shown.

**Comment by mkharibalaji** [comment]
Hi @FeodorFitsner ,

Try adding ContextualMenu 

        <MenuButton ghost transparent menu={<ContextualMenu {...menu} />}>Menu button</MenuButton>

https://codesandbox.io/s/align-buttons-middle-forked-tvs55

You can find more example here,

https://github.com/microsoft/fluentui/blob/48d30d84067583480c05c690d842c79a4ee9f87d/packages/react-examples/src/react-button/MenuButton/MenuButton.stories.tsx

But still one thing that doesn't work is after clicking the MenuButton is not dismissing !!!!

**Comment by FeodorFitsner** [comment]
Thank you @mkharibalaji I've been able to make it working!

MenuButton sample in [react-button/README.md](https://github.com/microsoft/fluentui/blob/master/packages/react-button/README.md#menu-buttons) is misleading by suggesting `{ items: ... }` can be used as a menu source while in reality `{<ContextualMenu ... />}` is expected and [MenuButton.stories.tsx](https://github.com/microsoft/fluentui/blob/48d30d84067583480c05c690d842c79a4ee9f87d/packages/react-examples/src/react-button/MenuButton/MenuButton.stories.tsx) proves that. It could be worth fixing readme to close this issue.

Popup menu is not dismissing, though. I'm watching https://github.com/microsoft/fluentui/issues/16610 now.

**Comment by mkharibalaji** [comment]
Thats true....Documentation needs to be updated.

**Comment by gouttierre** [comment]
@FeodorFitsner - thanks for filling this originally and glad to see you had some success since then.

@khmakoto - Can you double check the `MenuButton ` sample in [react-button/README.md](https://github.com/microsoft/fluentui/blob/master/packages/react-button/README.md#menu-buttons) is meant to be `{<ContextualMenu ... />} ` instead of '{ items: ... }' as it is currently stated? - Thank you

**Comment by khmakoto** [comment]
This is not an issue from a component standpoint. I've linked the PR that fixes the documentation.
