### ISSUE TITLE
Adding FocusIndex to IGroupedList to dynamically change selected row

### ISSUE THREAD

**Issue by alnasar** [microsoft/fluentui#16605]
#### Describe the feature that you would like added

I am using GroupedList component, and i want to be able to focus on item index using the component ref (like the detailslist)

#### What component or utility would this be added to

GroupedList 

#### Have you discussed this feature with our team, and if so, who

No

**Comment by alnasar** [comment]
is the current only option if doing this is to support selection property and add a ref to grouped list. 
using the groupedList.current.props.selection?.selectToIndex ??

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [GroupedList
][https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist] examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
