### ISSUE TITLE
[@uifabric/example-app-base] Narrator is not reading "Expand all" column header appearing below the interface section 

### ISSUE THREAD

**Issue by lucas-stanford** [microsoft/fluentui#16612]
**Environment Information**
Version:  2004 (OS Build: 20236.1005)
Browser: Edge chromium 
Tool: Developer tool
Bug id: 8759558 

**Describe the issue:**
In the package `@uifabric/example-app-base` the interfaces section's "Expand all" column header appearing below the Interface section text is not announcing 'expand all' and is announcing "group expanded" only.

**Please provide a reproduction of the issue in a codepen:**
Unable to use codepen as the issue is located in @uifabric/example-app-base

**Actual Result:**
The screen reader is announcing "group expanded" only.

**Expected Result:**
The screenreader should announce "Expand all".

**Documentation describing expected behavior**
N/A

![MAS4 1 2](https://user-images.githubusercontent.com/3011776/105760948-50351d00-5f07-11eb-988d-39a64469787f.png)

**Comment by gouttierre** [comment]
@lucas-stanford - Thank you for the feedback into the issue you are experiencing 

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley
