### ISSUE TITLE
Set column width in DetailsList

### ISSUE THREAD

**Issue by FeodorFitsner** [microsoft/fluentui#16620]
#### Describe the feature that you would like added

Being able to programmatically set column width in DetailsList to preserve control state between refreshes.
Something like `IColumn.defaultWidth`.

#### What component or utility would this be added to

DetailsList

#### Have you discussed this feature with our team, and if so, who

No, but there is https://github.com/microsoft/fluentui/issues/9287 which was closed as "Won't fix"?

#### Additional context/screenshots

N/A

**Comment by gouttierre** [comment]
@FeodorFitsner - thanks for the feedback and reaching out. To confirm, our updated docs for the `DataList` v8 can be found [here](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/detailslist)

@khmakoto  - Can you share the best practices in setting the default width for columns during rendering? Thank you

**Comment by khmakoto** [comment]
@gouttierre I think the recommendation in #9287 about using `minWidth` and `maxWidth` still holds true here. Is that not enough for your scenario @FeodorFitsner?

**Comment by FeodorFitsner** [comment]
It doesn't feel right to set `minWidth` and `maxWidth` for initial column width because that prevents column resizing? The idea is to set initial column width when DataList is first rendered and then allow it to be resized between minWidth/maxWidth.

**Comment by khmakoto** [comment]
@FeodorFitsner what happens if you just set `width` instead of `minWidth` and `maxWidth`?

**Comment by FeodorFitsner** [comment]
There is no `width` property on [IColumn](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/DetailsList/DetailsList.types.ts) unless I'm missing something.

**Comment by khmakoto** [comment]
Oh, right, you meant passing `minWidth` and `maxWidth` as part of `IColumn`. I was thinking about passing those values via the `styles` prop, in which case you should be able to pass `width`. Could you try that?
