### ISSUE TITLE
ThemeProvider remove the root div

### ISSUE THREAD

**Issue by NewFuture** [microsoft/fluentui#16633]
#### Describe the feature that you would like added

ThemeProvider renders without additional root dom.

#### What component or utility would this be added to

`@fluentui/react-theme-provider`

#### Additional context/screenshots

* now using ThemeProvider 
```jsx
<ThemeProvider theme={theme}><a>Content</a></ThemeProvider >
```
renders  result
```html
<div className="root-xxx"><a>Content</a></div>
```

* while, using Fabric
```jsx
<Customizer settings={{ theme }}>Content</Customizer >
```
renders  result
```html
<a>Content</a>
```

Is there any way to remove the root `div` of ThemeProvider?
I  try with `as={React.Fragment}`, but it shows some errors.

**Comment by gouttierre** [comment]
@NewFuture - Thanks for the feedback!

@khmakoto  - Would you be able to determine if there any way to remove the root div of ThemeProvider?

**Comment by khmakoto** [comment]
@gouttierre I think this goes straightly into the realm of Feature requests so I'll tag the issue as such and add it to the backlog. Thanks for filing the issue @NewFuture!

**Comment by qxg** [comment]
`<ThemeProvider as={React.Fragment}` works for me.

This is really boring if ThemeProvider is not always used in top level.

**Comment by NewFuture** [comment]
@qxg it will show this warining:
```
Warning: Invalid prop `theme` supplied to `React.Fragment`. 
React.Fragment can only have `key` and `children` props.
```

**Comment by DigitalMystery** [comment]
@NewFuture @khmakoto is the warning an issue or just ignore it for now?

**Comment by sysofwan** [comment]
+1 we need this to migrate to v8. Otherwise, adding replacing `Customizer` with `ThemeProvider` breaks our styles (it changes the DOM structure).

**Comment by NewFuture** [comment]
Our  Current workaround
```tsx

/**
 * render an empty root
 * @see https://github.com/microsoft/fluentui/issues/16633
 */
class RootFragment extends React.PureComponent {
  public render() {
    return <>{this.props.children}</>;
  }
}

/// then
<ThemeProvider as={React.Fragment} /></ThemeProvider>
```
It works, **but may have some unknown side effects**.

**Comment by MSpake** [comment]
Also hitting issues with this effecting the dom structure of our app. 
Will try the workaround suggested however, (especially since the workaround might have side-effects) it would be great to see this fixed.
