### ISSUE TITLE
TypeError: Cannot read property 'disabled' of undefined on Dropdown Change when changing several times

### ISSUE THREAD

**Issue by BrunoAlmeidaKotesky** [microsoft/fluentui#16649]
#### Actual behavior:
 If you start changing a controlled Dropdown component several times which has a **disabled** property, at some point the application crashes (not sure if it happen's on production build, using create-react-development template).

![image](https://user-images.githubusercontent.com/41238306/105897851-7934db00-5ff7-11eb-9a18-f0d639a0d520.png)

#### Code Example:
```tsx
const disableFilial = useMemo(() => readonly === true ? true : 
     (filiais?.length === 0 && !(selected?.filial?.Id)) ? true : false, 
   [filiais, selected, readonly]);
/**Some specific stuff*/
<Dropdown
      onChange={(ev, opt) => onUnidadeChange(opt, 'Filial')}
      className={'...'}
      placeholder='Placeholder'
      label='AnyLabel'
      disabled={disableFilial}
      options={filiais}/>
```

#### Expected behavior:
Not to throw errors on  dropdown component change event.

#### Are you willing to submit a PR to fix? 
Maybe implemeting this simple validation could fix, not sure. 
`if (selectedIndices && selectedIndices[0] && !this?.props?.options[selectedIndices[0]]?.disabled)`

#### Requested priority: Normal

**Comment by vaibhav6233m** [comment]
I was able to fix it with `selectedKey={selectedKey? selectedKey.key : undefined}` prop

Code Example:
```
<Dropdown
  placeholder={`Select `}
  options={dropdownOptions}
  styles={baseDropdownStyles}
  selectedKey={selectedKey? selectedKey.key : undefined}
  onChange={handleOnChange}
/>
```
handled Onchange like this

```
  function handleOnChangeRisk(
    _e: FormEvent<HTMLDivElement>,
    option: IDropdown
  ) {
    setSelectedKey(option);
  }
```

**Comment by gouttierre** [comment]
@BrunoAlmeidaKotesky - thanks for filing this item. Did you have a chance to review the suggested posted? 
Code Example:
```
<Dropdown
  placeholder={`Select `}
  options={dropdownOptions}
  styles={baseDropdownStyles}
  selectedKey={selectedKey? selectedKey.key : undefined}
  onChange={handleOnChange}
/>
```
handled Onchange like this
```
  function handleOnChangeRisk(
    _e: FormEvent<HTMLDivElement>,
    option: IDropdown
  ) {
    setSelectedKey(option);
  }
```

if you are still experiencing problems, please let us know, and add a CodePen repro so we can better help. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
