### ISSUE TITLE
TextField with multiline and autoAdjustHeight unexpectedly scrolls when line added or deleted

### ISSUE THREAD

**Issue by amygl** [microsoft/fluentui#16653]
### Environment Information

- **Package version(s)**: Detected in 7.84.1. Still repros against 7.157.0

- **Browser and OS versions**: Edge, Chrome, IE (doesn't seem relevant)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/amygl/pen/MWjNVMe
https://fabricweb.z5.web.core.windows.net/oufr/7.157.0/#/examples/textfield

#### Actual behavior:
- Text field with multiline and autoAdjustHeight.
- When adding a new line, or deleting a line from text field, it scrolls unexpectedly
![textFieldScrollOnAdjustHeight](https://user-images.githubusercontent.com/10605976/105923107-b9dd2600-5ff0-11eb-9a25-88dd073de151.gif)

#### Expected behavior:
- Shouldn't scroll

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes
The root cause is in TextField.base.tsx. When the height is set to "", the scroll position on outer container goes to top. And then when it is set to the scroll height, the scroll position on outer container goes to the cursor position.

``` typescript
private _adjustInputHeight(): void {
    if (this._textElement.current && this.props.autoAdjustHeight && this.props.multiline) {
      const textField = this._textElement.current;
      textField.style.height = '';
      textField.style.height = textField.scrollHeight + 'px';
    }
  }
```

2 different proposed fixes:
1. Add on `onAdjustInputHeight` callback. Consumers who hit this issue can save the container's scrollTop in `onChange` callback and then reset it in `onAdjustInputHeight`
2. Add optional prop that holds `scrollableContainerRef` then update to:
``` typescript
private _adjustInputHeight(): void {
    if (this._textElement.current && this.props.autoAdjustHeight && this.props.multiline) {
      const containerScrollTop = this.props.scrollableContainerRef?.scrollTop;
      const textField = this._textElement.current;
      textField.style.height = '';
      textField.style.height = textField.scrollHeight + 'px';
      if (this.props.scrollableContainerRef){
         this.props.scrollableContainerRef.scrollTop = containerScrollTop;
      }
    }
  }
```

Requested priority: Normal

Products/sites affected: Microsoft Planner

**Comment by gouttierre** [comment]
@amygl  - Thank you for the feedback. I had a look at this one against our latest version (TextField)(https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield) and the issue looks resolved.

**Comment by amygl** [comment]
@gouttierre, I just tried again and the text still unexpectedly jumps when inserting a newline or deleting a line. https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield

This is on the multi-line text field with auto-adjusting height.

**Comment by gouttierre** [comment]
@amygl  - thanks for confirming. 

@tomi-msft - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by ecraig12345** [comment]
The `onAdjustInputHeight` approach seems less risky than messing with the parent's DOM. I'm not thrilled about adding even more API surface to TextField, but this does seem like a legitimate use case and at least with an initial search I can't find any other way to handle it (since setting the height to `''` is necessary to make the field shrink when text is deleted).

This is not something the team is likely to get to any time soon, but I'd be happy to review a PR if anyone else is interested in implementing it.

**Comment by heptapod42** [comment]
@ecraig12345 @amygl I'd like to work on the PR if that's okay with you

**Comment by ecraig12345** [comment]
@heptapod42 Sure that's fine. As mentioned above I think the `onAdjustInputHeight` approach is better, and it looks like you'd need to call it after the height has been adjusted.

**Comment by heptapod42** [comment]
Working example for using the onAdjustHeight callback to fix the container scroll movement in CodeSandbox
https://codesandbox.io/s/textfield-onadjustheight-example-g3kvp?file=/src/index.tsx

**Comment by heptapod42** [comment]
@ecraig12345 I've raised a [PR](https://github.com/microsoft/fluentui/pull/19163) for this issue. Would you be able to review it?
