### ISSUE TITLE
Will Vue.js be supported? 

### ISSUE THREAD

**Issue by sbrian26** [microsoft/fluentui#16650]
Will Vue.js be supported? - Are there any efforts ongoing to port the #fluentui for direct use within vue.js projects?
[office-ui-fabric][fluentui-react] [fluentui](https://stackoverflow.com/questions/tagged/office-ui-fabric).

**Comment by gouttierre** [comment]
@sbrian26  - thanks for filling this query with us. I doubt we have upcoming plans to support Vue.js any time soon as we’re currently focused on larger coherence work items and enhancements to our performance. But let me loop in our senior pm to double check.

@paulgildea - could you confirm with the project roadmap for 2021, if we have plans to support Vue.js?
