### ISSUE TITLE
PivotItem ignoring HTMLAttributes

### ISSUE THREAD

**Issue by cabillin** [microsoft/fluentui#16651]
### Environment Information

- **Package version(s)**: 7.137.2
- **Browser and OS versions**: Edge Dev, Edge, Chrome

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/KnetTravlr/pen/ExgqQqj

#### Actual behavior:

className, styles, etc. passed into PivotItem do not appear in the generated DOM

#### Expected behavior:

className, styles, etc. should be applied to the top-level button element of the generated DOM
![image](https://user-images.githubusercontent.com/71525014/105916818-61089000-5fe6-11eb-9183-42db65ee6e68.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: internal Microsoft website

**Comment by gouttierre** [comment]
@cabillin - thank you for the feedback. I see you are willing to submit a PR for the fix - if you have one to share we would love to see it?
