### ISSUE TITLE
FluentUI: Teams v2 Theme Menu - No Selected Color

### ISSUE THREAD

**Issue by DaleyKD** [microsoft/fluentui#16669]
### Environment Information

- **Package version(s)**: 0.52.0

### Please provide a reproduction of the bug in a codepen:
https://fluentsite.z22.web.core.windows.net/0.52.0/components/menu/definition

If you use the theme switcher, and under VARIATIONS, look at the Vertical example, all themes except Teams v2 has a proper selected color.

#### Expected behavior:
I suspect it should be a similar gray to the original Teams theme.

**Comment by gouttierre** [comment]
@DaleyKD - Thanks for reaching out and pointing this out.

@tomi-msft  - Would you be able to confirm the selected color (gray scale) for Teams v2 and original Teams?  And if this is by design or an issue?

**Comment by DaleyKD** [comment]
Still an issue in 0.53.0.  Thanks for checking on this.

**Comment by gouttierre** [comment]
@DaleyKD - thanks for confirming with the later version - this item is queued within the team and we will get to it as soon as bandwidth allows.
