### ISSUE TITLE
Narrator reads invalid information when selecting months in the DatePicker 

### ISSUE THREAD

**Issue by lucas-stanford** [microsoft/fluentui#16673]
### Environment Information

Version:  2004 (OS Build: 20236.1005)
Browser: Edge chromium 
Screen Reader: Narrator
Bug id: 8787914

### Describe the issue:
Narrator is announcing **readonly** while navigating on "Jan" button of Calendar pop up.

### Please provide a reproduction of the issue in a codepen:
Reproable here: https://fabricweb.z5.web.core.windows.net/oufr/7.157.1/#/examples/datepicker

#### Actual behavior:
Narrator is announcing "January 2020 **readonly** column 1 row 1 item" while navigating on "Jan" button of Calendar pop up.

#### Expected behavior:
Narrator is announcing "January 2020 column 1 row 1 item" while navigating on "Jan" button of Calendar pop up.

### Documentation describing expected behavior
N/A

![image](https://user-images.githubusercontent.com/3011776/106051807-c23f6a80-609d-11eb-86e3-36aeb1d423ba.png)

**Comment by gouttierre** [comment]
@lucas-stanford - thanks for reporting this issue. I followed your guidelines in the problem specified but was unable to repo your results. The expected behavior was reproduced without a problem. Could you confirm, if you are still experiencing the problem?
