### ISSUE TITLE
IStackTokens not able to use 'padding' property

### ISSUE THREAD

**Issue by brandonMetro** [microsoft/fluentui#16672]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react@6.214.0",
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

The link to Stack https://developer.microsoft.com/en-us/fluentui#/controls/web/stack

#### Actual behavior:

Re-using Vertical Stack code from this site and receiving this error:

Type '{ childrenGap: number; padding: number; }' is not assignable to type 'IStackTokens'.
  Object literal may only specify known properties, and 'padding' does not exist in type 'IStackTokens'

#### Expected behavior:

Either padding needs to be added or documentation fixed.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: (Fluent UI)

**Comment by brandonMetro** [comment]
I was able to fix this by using the import for '@fluentui/react'
The documentation here https://developer.microsoft.com/en-us/fluentui#/controls/web/stack
needs to be updated accordingly as it's still using office-ui-fabric-react/lib/Stack

**Comment by gouttierre** [comment]
@brandonMetro - thanks for the feedback. I tested this on our latest version and the issue didn't arise asking for the additional import. However, I’ll mark this request and add it to our backlog to be done with our documentation alignment. Thank you!
