### ISSUE TITLE
ARIA attributes not allowed for an element's role

### ISSUE THREAD

**Issue by svirga** [microsoft/fluentui#16683]
### Environment Information

- **Package version(s)**: 7.153.2 +
- **Browser and OS versions**: Edge 88.0.705.50

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/svirga/pen/mdObmWV

#### Actual behavior:

Invalid ARIA attribute is defined for the controls under "div[aria-label="Color\:\ \"red\""]", "div[aria-label="Color\:\ \"green\""]", and "div[aria-label="Color\:\ \"blue\""]"
![image](https://user-images.githubusercontent.com/24298160/106077383-4a396a80-60c6-11eb-94a9-6a85b088aad1.png)
![image](https://user-images.githubusercontent.com/24298160/106077543-997f9b00-60c6-11eb-8de0-dacb8a762a61.png)

#### Expected behavior:
ARIA attributes should be defined for the controls under "div[aria-label="Color\:\ \"red\""]", "div[aria-label="Color\:\ \"green\""]", and "div[aria-label="Color\:\ \"blue\""]"

### Documentation describing expected behavior
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7b248054a6-5e68-4771-9e1e-242fb5025730%7d&cid=3ce860c9-077c-47a7-8384-048ad7a99492

**Comment by gouttierre** [comment]
@svirga - Thank you for the feedback. I took a look and was unbale to repro your reported problem. Please, can you recheck using our latest public release, and confirm if your still experiencing the issue.. Thanks
