### ISSUE TITLE
npm install @fulentui/react-northstar take about 11s, any solution to reduce the time?

### ISSUE THREAD

**Issue by weny-tang** [microsoft/fluentui#16682]
For _how-to_ questions and other non-bugs, please use StackOverflow instead of Github issues. You can tag your questions with [office-ui-fabric][fluentui-react] [fluentui](https://stackoverflow.com/questions/tagged/office-ui-fabric).

If you are a Microsoft employee you can also join the "Fluent UI Community" Teams channel.
hi, I use fluentui/react-northstar in my project, but i just use button style.
when I run npm install, this dependency takes about 11s with a lot of small file. 
how to reduce the time?

**Comment by gouttierre** [comment]
@weny-tang - thank you for reaching out and highlighting the build time duration. There is plans to improve general areas of our packages as we are focusing on the larger coherence work items and enhancements to our performance.
