### ISSUE TITLE
I must really say the documentation is too verbose and not clear. what does a data list do and how to use it and its props not filling it with hundreds of data 

### ISSUE THREAD

**Issue by princewhyte2** [microsoft/fluentui#16704]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

**Comment by gouttierre** [comment]
@princewhyte2 - thanks for reaching out. What is the unclear with our docs - mind sharing more information to what is vague?
A link to our docs for DetailsList: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist

If you have a snippet to share please add a CodePen repro before we can help further. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by princewhyte2** [comment]
thanks alot
