### ISSUE TITLE
Can we prevent not to load GroupedListSection on collapse? Can we make behaviour like hide and show?

### ISSUE THREAD

**Issue by chntn** [microsoft/fluentui#16731]
**Environment Information**
Package version(s) :  Office UI Fabric React 6.189.2
Browser: Chrome 

**Describe the issue:**

I want to trigger Grouped List Section on expand of Group Header click.

When Group Header is expand Group Section node available in DOM.

![Expand](https://user-images.githubusercontent.com/4496711/106494455-7139d700-64e0-11eb-980b-b594dc0d71b8.png)

When Group Header is collapsed Group Section node removed form DOM.

![Collapse](https://user-images.githubusercontent.com/4496711/106494459-726b0400-64e0-11eb-9fdf-799fb525f1e0.png)
 
Could we change this behaviour to display block and none property?
I want to trigger the Group section items on expand, since node is removed on collapse, so not able to perform the action.

**Comment by joschect** [comment]
@chntn Thanks for the question! This sounds like a feature request and I believe is something that we could enable. If you wanted to submit a change that adds this feature behind prop we always welcome more help.
