### ISSUE TITLE
TextField reveal password button is missing discernible text

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#16756]
### Environment Information

- **Package version(s)**: `@fluentui/react` 8, recent versions of 7
- **Browser and OS versions**: non-IE/Edge (built-in reveal button is used in those cases)

### Describe the issue:

We recently added an optional reveal password button to the TextField, but it doesn't have a tooltip explaining what the button does (and we didn't provide a way to add a tooltip). Accessibility Insights correctly flags this as a violation.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/ecraig12345/full/poEBNOJ

Run the Accessibility Insights extension on this codepen (ignoring any errors from the codepen frame).

#### Actual behavior:

A button-name violation is flagged

#### Expected behavior:

No violations

### Proposed fixes

There are three main possible fixes here, and I'd appreciate input from @JustSlone and @smhigley (or anybody else) about what to do.

#### Option A: Hide the button

Mark the reveal button as `aria-hidden` and `tabIndex={-1}`. This is by far the easiest but doesn't provide a way to solve the issue that it might be unclear even to sighted users what the button is for.

#### Option B: Add props for only the tooltip and apply using `title`

Add these two props to `ITextFieldProps`, then apply them using `<button title={isRevealingPassword ? hidePasswordTitle : revealPasswordTitle>`. 

This is by far the simplest, but given the discussion I recently had with @JustSlone about `title` I'm not sure it's the right thing to do. :( In this situation we can't use TooltipHost because the bundle size hit to TextField would be unacceptable.

```ts
interface ITextFieldProps {
  // ...

  /**
   * If `canRevealPassword` is true, tooltip for the reveal password button while the password is hidden
   * (example value: "Show password"). Note that this will NOT be used in browsers known to have a 
   * built-in reveal password button for password inputs (Edge, IE).
   */
  revealPasswordTitle?: string;

  /**
   * If `canRevealPassword` is true, tooltip for the reveal password button while the password is hidden
   * (example value: "Hide password"). Note that this will NOT be used in browsers known to have a 
   * built-in reveal password button for password inputs (Edge, IE).
   */
  hidePasswordTitle?: string;
}
```

#### Option C: Add a custom renderer prop for the reveal button

This would allow wrapping the button in a TooltipHost, but is more complicated. Also, a custom renderer alone doesn't fully solve the problem if we intend for the reveal button to be focusable: in that case we'd need additional props for the button's aria-label in each state.

```ts
interface ITextFieldProps {
  // ...

  /**
   * If `canRevealPassword` is true, custom renderer for the reveal password button (mainly intended
   * for wrapping the button in a TooltipHost). Note that this will NOT be used in browsers known 
   * to have a built-in reveal password button for password inputs (Edge, IE).
   */
  onRenderRevealPassword?: IRenderFunction<ITextFieldRevealPasswordProps>;

  /**
   * If `canRevealPassword` is true, aria label for the reveal password button while the password
   * is hidden (example value: "Show password"). Note that this will NOT be used in browsers known 
   * to have a built-in reveal password button for password inputs (Edge, IE).
   */
  revealPasswordAriaLabel?: string;

  /**
   * If `canRevealPassword` is true, aria label for the reveal password button while the password
   * is hidden (example value: "Hide password"). Note that this will NOT be used in browsers known 
   * to have a built-in reveal password button for password inputs (Edge, IE).
   */
  hidePasswordAriaLabel?: string;
}

/**
 * Props for custom rendering the TextField's reveal password button.
 * {@docCategory TextField}
 */
export interface ITextFieldRevealPasswordProps extends ITextFieldProps {
  isRevealingPassword: boolean;
}
```

### Other minor fixes to make regardless :)

Regardless of the main fix we choose, I noticed a some other problems while trying things out, which should be fixed regardless:

- The button is missing a focus outline (since it's a manually styled `button` for bundle size reasons). Assuming we want the button to be focusable at all, I think we can add this with the `getFocusOutlineStyle` utility with the same options as Button uses. If it shouldn't be focusable, add `tabIndex={-1}` instead.
- Update `ITextFieldProps.canRevealPassword` docs as follows:
```
  /**
   * Whether to show the reveal password button for input type `'password'`. This will be ignored
   * if the `type` prop is not set to `'password'`, or if the browser is known to have a built-in
   * reveal button for password inputs (Edge, IE).
   */
```
- In `TextField.base.tsx` inside `_browserNeedsRevealButton`, update the `isEdge` regular expression to `/^Edg/`

**Comment by JustSlone** [comment]
As per the requirement that the icon have a tooltip. I think this particular icon falls under the case of "common enough of an icon that doesn't require a tooltip".

Some clear known examples of icons that do not require tooltips (despite what accessibility insights or various rules say)
- Hamburger Menu
- Settings Gear
- Close icon 

For comparison the built-in implementation in the Edge browser of password reveal also does not have a tooltip. In the case of edge we don't render the iconbutton, because edge has it's own reveal functionality. (Can't see the cursor, but I promise I'm hovering over it 😄)
![image](https://user-images.githubusercontent.com/40304143/106551816-e6021680-64ca-11eb-8dd8-867b2dcbbcf3.png)

As for the accessibility insights error. I think adding an `aria-label` attribute would fix it, and I agree that this icon should probably have an aria-label.
![image](https://user-images.githubusercontent.com/40304143/106551706-a9361f80-64ca-11eb-9258-fd8f525dd9f4.png)

**Comment by ecraig12345** [comment]
Thanks for the feedback! In that case we should probably just add a prop `revealAriaLabel?: string` (in addition to the minor fixes listed above). That simpler version could be a good candidate for someone new to work on.

**Comment by hantatsang** [comment]
I'm having a go at this. However, having the focus outline on the "Reveal Password" button looks a bit weird as it clashes with the TextField input's focus outline (which is grey in the GIF):

![password reveal button outline](https://user-images.githubusercontent.com/11912225/107865754-25af0200-6ebe-11eb-9b98-0964e601c773.gif)

Do you think styling it with a background just like the existing `:hover` styling implementation will look better? I'm hovering the mouse over the "Reveal password" button here to show the `:hover` styling:

![2021-02-14 12_15_28-TextField - Text Field Basic Example ⋅ Storybook](https://user-images.githubusercontent.com/11912225/107865786-5ee77200-6ebe-11eb-9f60-e8b591251251.png)

**Comment by ecraig12345** [comment]
@smhigley I feel like we discussed this internally and decided that the reveal password button actually should *not* be focusable? Or am I mixing this up with something else?

**Comment by JustSlone** [comment]
Nudging @smhigley would love to get this figured out and unblock the fix
