### ISSUE TITLE
User cannot navigate across the stars using up/down arrow keys.

### ISSUE THREAD

**Issue by amitroy-790** [microsoft/fluentui#16768]
### Environment Information

- **Package version(s)**: 7
- **Browser and OS versions**: Edge & Windows 10

### Describe the issue:

User cannot navigate across the rating stars using up/down arrow keys.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/amitroy-790/pen/yLVNQBo

#### Actual behavior:

User cannot navigate across the rating stars using up/down arrow keys.

#### Expected behavior:

User Should be able to navigate across the rating stars using up/down arrow keys.

**Comment by joschect** [comment]
@amitroy-790 Thanks for the submission! The user can navigate across the stars using the left and right keys, are you wanting to add additional movement for the up and down keys as well?

**Comment by amitroy-790** [comment]
Yes @joschect. The navigation should work with both the ways, using left/right arrow keys as well as up/down arrow key.

**Example :** https://www.w3.org/WAI/tutorials/forms/custom-controls/#a-star-rating
