### ISSUE TITLE
Export Fluent UI messaging colors

### ISSUE THREAD

**Issue by holylander** [microsoft/fluentui#16761]
#### Describe the feature that you would like added

Export the [`messaging` fluent UI colors ](https://developer.microsoft.com/en-us/fluentui#/styles/web/colors/messaging) as a typescript or similar.

#### What component or utility would this be added to

[`messaging` fluent UI colors ](https://developer.microsoft.com/en-us/fluentui#/styles/web/colors/messaging)

#### Additional context/screenshots

Current page doesnt tells any method to import these colours to your project
![imagen](https://user-images.githubusercontent.com/2032683/106582232-0cb06380-6544-11eb-9cf6-7ebe463ed0d5.png)

However, other colours set methods are described
![imagen](https://user-images.githubusercontent.com/2032683/106582315-25b91480-6544-11eb-9af5-a4a90146fe4e.png)

**Comment by joschect** [comment]
@holylander That's a really good point! This si a pretty confusing section and we can certainly clarify this.

**Comment by holylander** [comment]
Thats cool!
As a temp solution, I using the colors from `FluentTheme.semanticColors.errorText`, like below:
```
import { FluentTheme } from '@fluentui/theme';

export const ErrorLabel: FC = () => {
  return <span style={{ color:  FluentTheme.semanticColors.errorText }}>{strings.ErrorLabel}</span>;
};
```
