### ISSUE TITLE
When there is only one point, the callout doesn't show up when you hover on it.

### ISSUE THREAD

**Issue by cariceli** [microsoft/fluentui#16784]
### Environment Information

- **Package version(s)**: 4.11.0
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/the-callout-doesnt-show-up-when-hovering-rttx1?file=/src/Chart.tsx

#### Actual behavior:

When there is only one point, the callout doesn't show up when you hover on it. 
![image](https://user-images.githubusercontent.com/42231272/106713348-48772600-6635-11eb-951b-c3c80011791f.png)

#### Expected behavior:
 display the callout.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@cariceli - thanks for reaching out.

@khmakoto - Would you be able to confirm if the callout is a regression, or if this behavior is an issue?

**Comment by shivasai09** [comment]
this is fixed in https://github.com/microsoft/fluentui/pull/17312

we need to use package `@uifabric/charting@v4.15.5`  to fix

**Comment by jameelakowsar** [comment]
@cariceli ,

Can you please check this fix and can you close this bug?
