### ISSUE TITLE
Persona doesn't generate correct initials 

### ISSUE THREAD

**Issue by qianghuang94** [microsoft/fluentui#16783]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: Not browser specific

### Describe the issue:

![image](https://user-images.githubusercontent.com/15025186/106701204-41deb380-6621-11eb-9130-bcf639227cd0.png)

We received a customer ticket that saying the initials that generated from persona is not correct if the name contains `[]` 

They think `OnlineUser2 Test [HK-IST]` should be `OT` instead of `OH`

#### Actual behavior:
Initials to be`OH`

#### Expected behavior:
Initials to be `OT`

### If applicable, please provide a codepen repro:
<Persona {...examplePersona} text="OnlineUser1 Test (HK-IST)" size={PersonaSize.size24} />
<Persona {...examplePersona} text="OnlineUser2 Test [HK-IST]" size={PersonaSize.size24} />

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: SharePoint Online

**Comment by joschect** [comment]
@qianghuang94 Thanks for the submission! Would you mind taking another look at this? I'm not able to repro this in a [codepen](https://codepen.io/slimemold/pen/QWGvXqM?editors=0010) and I wonder if it might be working now.

**Comment by qianghuang94** [comment]
I tested, looks someone already fixed the issue, thanks! I can't reproduce it also.
