### ISSUE TITLE
Keytip Overflow demo not working correctly

### ISSUE THREAD

**Issue by kelseyyoung** [microsoft/fluentui#16798]
### Environment Information

- **Package version(s)**: Current
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:

Bug can be seen on the keytip demo page https://developer.microsoft.com/en-us/fluentui#/controls/web/keytips specifically in the Keytips in an OverflowWell demo

#### Actual behavior:

Two issues are happening:

1. Pressing Alt-Win, R should show two keytips in the menu, but none are shown

![image](https://user-images.githubusercontent.com/4252452/106792453-ff11e100-660a-11eb-9642-0ed94c1b18cb.png)

2. Pressing Alt-Win, Y should open two menus, but nothing happens

#### Expected behavior:

1. After pressing R, keytips T and Y should show up in the menu corresponding to Overflow Link 1 and Overflow Link 2
2. After pressing Y, two menus should open like below and a keytip H should be shown on Overflow Submenu Item 1

![image](https://user-images.githubusercontent.com/4252452/106792831-852e2780-660b-11eb-8253-2719da0b85e2.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, I'm currently investigating the issue now and Xu is aware of the issues as well

Requested priority: Normal

Products/sites affected: Office Online for some reason is only affected by issue 2, issue 1 doesn't repro

**Comment by joschect** [comment]
@kelseyyoung Thanks for submitting this issue and submitting a fix! That's awesome.
