### ISSUE TITLE
CommandBar items are not rendering properly when screen is set back to normal state after minimizing

### ISSUE THREAD

**Issue by Arsasana** [microsoft/fluentui#16790]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by Arsasana** [comment]
Do we have any update on this issue?

**Comment by joschect** [comment]
@Arsasana Sorry for the slow response! Thanks for the submission. I'm having some trouble reproducing the issue, it looks like the commandbar items [render appropriately in this codepen](https://codepen.io/slimemold/pen/BaQRgrW) are there some customizations that you could add to demonstrate what you're seeing?

**Comment by Arsasana** [comment]
Hi Jon,

I couldn’t repro this issue anymore, I assume it’s fixed.

Issue I was facing previously: When the page is zoomed in, overflow button gets added automatically and items are getting rendered inside it and the actual state isn’t getting preserved even after resetting zoom as in below image
[cid:image003.png@01D7061A.1FF44EE0]

Thanks,
Arpitha

**Comment by dps88** [comment]
@joschect, @Arsasana   I have had similar issues if the command bar is in a div with flex on it.  Here's a codepen in a [related issue](https://github.com/microsoft/fluentui/issues/16268#issuecomment-749868695)
