### ISSUE TITLE
Focus borders not fully visible for multiselect dropdown items

### ISSUE THREAD

**Issue by evlevy** [microsoft/fluentui#16800]
### Environment Information

- **Package version(s)**: @fluentui/react 8.0.0-beta.48
- **Browser and OS versions**: Edge 88.0.705.56

### Describe the issue:

Multiselect items in a dropdown do not have fully visible focus borders.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/evlevy/pen/XWNmVqW

#### Actual behavior:

Dropdown items left/right borders are missing, and top/bottom border are missing in outmost items.

#### Expected behavior:

Top/bottom/let/right borders should be visible for all items.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by joschect** [comment]
@evlevy Thanks for submitting this issue and submitting a fix! We really appreciate the help. We'll get this merged and checked in!
