### ISSUE TITLE
Layer's div element is not removed from body

### ISSUE THREAD

**Issue by FeodorFitsner** [microsoft/fluentui#16808]
### Environment Information

- **Package version(s)**: @fluentui/react@8.0.0-beta.44
- **Browser and OS versions**: Chromium Edge

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/dialog-leaving-layer-element-q1di0?file=/src/DialogSample.tsx

#### Actual behavior:

After opening/closing a dialog for multiple times `<body>` element (or, presumably, a custom layer host element if specified) is littered with multiple `<div class="ms-Layer ms-Layer--fixed root-X" data-portal-element="true"></div>` elements:

![image](https://user-images.githubusercontent.com/5041459/106829643-65195b00-6641-11eb-9d89-518ece567f06.png)

CodePen sample from the [current Fluent UI docs](https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog) works without that issue, so it could be 8.x regression. I feel something's wrong in [LayerBase class](https://github.com/microsoft/fluentui/blob/master/packages/react-internal/src/components/Layer/Layer.base.tsx), but I'm still new to Fluent internals.

#### Expected behavior:

Layer element is properly removed from a layer host element.

### Priorities and help requested:

Are you willing to submit a PR to fix? Maybe, if there is a guide for setting up Fluent dev environment.

Requested priority: Normal

Implemented workaround:

Removing empty divs on `onLayerWillUnmount` event:

```javascript
const props: IPanelProps = {
    ...
    layerProps: {
        onLayerWillUnmount: () => {
            const layers = document.body.getElementsByClassName("ms-Layer--fixed")
            for (let i = 0; i < layers.length; i++) {
                let layer: Element = layers[i];
                if (!layer.hasChildNodes()) {
                    document.body.removeChild(layer);
                }
            }
        }
    }, 
```

**Comment by joschect** [comment]
@FeodorFitsner Thanks for submitting this issue and submitting a fix. I've added some eyes to the pr and we'll get it looked at.
