### ISSUE TITLE
Remove all v0/v8 dependencies in react-button

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#16818]
Right now `react-button` has the following dependencies that we need to talk about if we can keep them or if we should replace them going forward:
- `@fluentui/react-hooks`
- `@fluentui/style-utilities`

**Comment by xugao** [comment]
My main concern for no shared dep would be bundle size increase for apps that use more both converged and v0/v8

**Comment by khmakoto** [comment]
These dependencies have been removed now, so closing this issue.
