### ISSUE TITLE
[charting] various API names have typos

### ISSUE THREAD

**Issue by mbest** [microsoft/fluentui#16829]
### Environment Information

- **Package version(s)**: @uifabric/charting 4.12.8

#### Actual behavior:

There are typos in the names of props, especially ones that were added recently. In some cases, a word is spelled incorrectly. In other cases, two words aren't separated (using camelCase conventions).

#### Expected behavior:

Exported interfaces includes names with correct spelling.

**Comment by mbest** [comment]
Here are the spelling errors I found (errors highlighted):

- showXAxis**Lables**Tooltip
- wrapXAxis**Lables**
- **silce**OrAppendToArray
- _removalValueForText**Tuncate**
- **seleceted**LegendInHoverCard
- onRenderCalloutPer**Horizonal**Bar

These have merged words (highlighted word should be capitalized):

- xAxis**tick**Size
- callout**legend**Text
- get**margins**
- bar**width**
- IBase**state**
- horizontalBarChart**data**
- tooltipOfXAxis**labels**
-

**Comment by joschect** [comment]
@mbest Thanks for submitting this! We'll get it assigned to the charting folks and looked at.

**Comment by mbest** [comment]
reopened as #21616
