### ISSUE TITLE
React Tabs beta issue on spfx

### ISSUE THREAD

**Issue by jonathanhotono** [microsoft/fluentui#16838]
### Environment Information

- **Package version(s)**: 1.0.0-beta.25

On Windows 10, SharePoint Framework v1.11, TypeScript 3.3 (Rush Stack Compiler 3.3).

### Please provide a reproduction of the bug in a codepen:

I'm importing Fluent UI React Tabs 1.0.0-beta.25 which was **already working** on my SPFx v1.11 solution. It stops working just a few days ago in my release pipelines because it's running npm install on the project again. I also tried to reinstall the node modules on my local dev machine and able produce the exact same problem.

The errors are mostly came from `node_modules/@fluentui/react-internal/lib/components/Slider/useSlider.d.ts`
![image](https://user-images.githubusercontent.com/6864547/106977061-b47c9a00-67ad-11eb-9073-e9984ef7aef9.png)

Has there been any changes to the typescript version requirements? 

Requested priority: Medium

Products/sites affected: Fluent UI React Tabs
https://www.npmjs.com/package/@fluentui/react-tabs

**Comment by joschect** [comment]
@jonathanhotono Thanks for the submission! We've been undergoing some package restructuring as we continue to prepare for v8. I suspect that some of this may have broken parts of the beta branch. We will keep problems like this as we continue our restructuring. @ecraig12345 for visibility.

**Comment by jonathanhotono** [comment]
Thanks @joschect @ecraig12345 
Is there anything I can do to fix this issue on my spfx project?

**Comment by ecraig12345** [comment]
@jonathanhotono Are you using the Tabs component, or Pivot? Tabs is still in development and not yet recommended for use. (Sometime soon we'll be adding badges to the package readmes to help clarify status.)

If you're using Pivot, as of the most recent beta version, it's actually been moved back to `@fluentui/react`. So you should update to the latest version and import Pivot from `@fluentui/react` rather than `@fluentui/react-tabs`.

**Comment by jonathanhotono** [comment]
@ecraig12345 I'm using tab component since it has better mobile view feature. Does Pivot support better mobile view like tabs component as well?

**Comment by ecraig12345** [comment]
@behowell would have a better idea of whether we plan to support this for Pivot. Regardless, we strongly recommend against using Tabs at the moment since it's under active development and we can't provide any guarantee of API stability between beta versions.

**Comment by behowell** [comment]
You should use `Pivot`. As of right now, `Tabs` is just a renamed copy of `Pivot`, and is not supported or ready for use yet. Its API will be changing significantly in the future.

I'm curious what you mean by having a better mobile view feature? If you're referring to the overflow menu when not all tabs fit onscreen, that is supported by `Pivot` from the latest version 8 beta of `@fluentui/react`.

**Comment by jonathanhotono** [comment]
Thanks @ecraig12345 @behowell 

I just tried to use normal Pivot as well using latest beta `8.0.0-beta.53` on my sharepoint framework project:

`import { Pivot, PivotItem } from "@fluentui/react";`

And same error messages displayed.. 
![image](https://user-images.githubusercontent.com/6864547/107596529-1afd2e80-6c6c-11eb-9077-175082a4fb0d.png)

**Comment by natpdeee** [comment]
Hi, 
I got the same issue and error message. I am trying to incorporate the ``Pivot`` component with the overflow feature. 
I am using ``fluentui/react`` version ``8.0.0-beta.53``

**Comment by ecraig12345** [comment]
@natpdeee Are you also using SPFx or a different setup?

@jonathanhotono Can you post a screenshot with the beginning of that list of errors? (Usually it's the first one that's messing up everything else.) Also what typescript version does your project use?

**Comment by jonathanhotono** [comment]
@ecraig12345 screenshot below, I'm using typescript 3.3 that came from Spfx v1.11 (Rush Stack Compiler 3.3)
![image](https://user-images.githubusercontent.com/6864547/107896291-eea62280-6f89-11eb-9735-312f76f8bc41.png)

**Comment by ecraig12345** [comment]
@jonathanhotono The minimum supported typescript version for `@fluentui/react` version 8 is 3.7.

**Comment by jonathanhotono** [comment]
@ecraig12345 thanks, I just updated my project typescript version to 3.7 and it works fine. What is the plan for fluentui v8 final version of typescript required? Will it stays at minimum of version 3.7 or there will be another change/cutover to would only support version greater than 3.7? e.g v4.1..

**Comment by ecraig12345** [comment]
@jonathanhotono We're planning to stay with minimum of 3.7 for the duration of version 8. I just clarified this in the [migration guide](https://github.com/microsoft/fluentui/wiki/Version-8%3A-Migration-guide)--thanks for the reminder.

**Comment by ecraig12345** [comment]
For anyone hitting a similar issue compiling against version 8 beta packages, the solution is to upgrade to typescript >= 3.7 since this is the [minimum supported for `@fluentui/react` 8](https://github.com/microsoft/fluentui/wiki/Version-8-migration-guide#supported-dependency-versions). So I'll go ahead and close this.
