### ISSUE TITLE
Largest font size in Text in Northstar

### ISSUE THREAD

**Issue by PathToSharePoint** [microsoft/fluentui#16840]
### Environment Information

- **Package version(s)**: Northstar latest
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluent-ui-example-forked-ezceo

#### Actual behavior:

The size prop is of type SizeValue. size="largest" renders the text in small font.

![image](https://user-images.githubusercontent.com/40323257/106987170-bc8ef800-6721-11eb-814b-89079b276773.png)

#### Expected behavior:

I would expect largest to be the largest font.

### Priorities and help requested:

Are you willing to submit a PR to fix? No, I am not sure what exact size is expected.

**Comment by PathToSharePoint** [comment]
I just got another similar issue with the Card component. The size prop is of type SizeValue, but smaller and smallest are larger than small.

**Comment by joschect** [comment]
@PathToSharePoint Thanks for submitting this and including your codesandbox! I can see that this repros readily. I believe that this is a bug and we will go ahead and get this fixed.
