### ISSUE TITLE
Move custom screener integration to shared locations

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#16850]
@layershifter made a custom screener/github integration that gets rid of the unreliable ngrok dependency for detecting build completion (and helps us have separate screener checks for v0/v8). https://github.com/layershifter/screener-proxy

Primarily in the interest of having proper shared access/ownership, we should:

- Move source code to a shared repo, either on github (`fluentui-screener-proxy`?) or private uifabric ADO
- Make the service run on the UI Fabric Azure instance instead of Vercel

This could potentially be addressed either before or after #16851, whichever way makes the most sense.

**Comment by ecraig12345** [comment]
@andrefcdias Can you work with @layershifter to get an estimate of how long this would take? Then we can use that info to help decide how to prioritize the work.

**Comment by JustSlone** [comment]
Update:
- PR is ported to express / azure
- Added layer of security to webhooks

Next:
- Integrate into our CI deployment

**Comment by JustSlone** [comment]
Update:
- No progress 😦 
- Moving from monorepo to ADO repo

In progress
- Working on build pipeline

**Comment by JustSlone** [comment]
Update:
- App in azure
- Slowly disabling old app to not catch everything on fire
- Moving forward looking good

**Comment by andrefcdias** [comment]
Migration was finished last week and has shown no problems. Marking this as closed.
