### ISSUE TITLE
defaultSelectedIndex is not selected on Pivot load

### ISSUE THREAD

**Issue by davvit** [microsoft/fluentui#16856]
### Environment Information

- **Package version(s)**: Chrome, Msft Edge, React app

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/davvit/pen/RwoaPpj

#### Actual behavior:

3rd PivotItem is not selected on load.

#### Expected behavior:

the third index PivotItem should be selected

### Priorities and help requested:

No

Requested priority:  Blocking

Products/sites affected: (if applicable)

**Comment by joschect** [comment]
@davvit Thanks for the submission! DefaultSelectedIndex has been deprecated for a while and it's being removed in this latest version of fluent. It looks like `defaultSelectedKey` works exactly as you want and it will be the correct property moving forward. Sorry for the confusion! Here is a [codepen](https://codepen.io/slimemold/pen/OJbRRzy?editors=0010) with this property in use.
