### ISSUE TITLE
[DetailsList] While zooming in the page, columns in the right will disappear. And there is no scroll bar in the footer.

### ISSUE THREAD

**Issue by Phoebe-0319** [microsoft/fluentui#16857]
### Environment Information

- **Package version(s)**: 7.158.1
- **Browser and OS versions**: Chrome, Edge

### Describe the issue:

**While zooming in the page, columns in the right will disappear. And there is no scroll bar in the footer.**

### Please provide a reproduction of the issue in a codepen:
https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist

#### Actual behavior:

**[100%]**
![image](https://user-images.githubusercontent.com/60056296/107139144-ec254680-6953-11eb-94bf-0c053c32ca52.png)

**[200%]**
![image](https://user-images.githubusercontent.com/60056296/107139095-79b46680-6953-11eb-8925-3d04b5beaf00.png)

**[250%]**
![image](https://user-images.githubusercontent.com/60056296/107139052-44a81400-6953-11eb-98a8-b1a47573cea1.png)

#### Expected behavior:
While zooming in the page, pull the scroll bar in the footer to see the missing columns.

**Comment by joschect** [comment]
@Phoebe-0319 Thanks for the submission! This is intended behavior that depends on the properties passed into the details list. The details list currently has 2 modes `fixedColumns` and `justified` which can get passed into the details list via the `layoutMode` property. If it is set to `justified` it will automatically attempt to resize to keep the user from seeing too much data for the screen size. If it is set to `fixedColumns` it should work exactly how you want and will not remove columns as the screen size changes. You can see it working in this [codepen](https://codepen.io/slimemold/pen/bGBwwRp?editors=0010)
