### ISSUE TITLE
Rendering html content inside a Card.Section

### ISSUE THREAD

**Issue by Diwakar8** [microsoft/fluentui#16858]
Need support or guidance on rendering html content inside a Card.Section. I am returning rich text from my code and want to render it as is.
Thanks!

**Comment by JustSlone** [comment]
@Diwakar8 thanks for the reaching out, but we really need more information here in order to reproduce your issue

**Comment by Diwakar8** [comment]
Which Fluent UI component is causing the issue -- we are using card. https://developer.microsoft.com/en-us/fluentui#/controls/web/card#implementation
Which package name and version the component is from -- Please see above.
Specific, complete steps to reproduce the issue. -- Try to render rich text within the card.
What behaviors and attributes are missing or incorrect. -- Not getting any documentation to render html tags within the card.
What you expected and what is actually happening -- we expected a property to be set so that html tags can be rendered without any issues.
Confirmation that the problem reproduces in isolation. - Yes, we are asking for a capability which we are not able to find in fluent UI Card.

**Comment by JustSlone** [comment]
Got it, thanks for the feedback @Diwakar8. Card being a React component supports rendering html (or other React components) inside it. It doesn't support rich text directly, you'll need to convert your rich text into html. 

Also, React Card is an experimental component that actually isn't under development anymore, we likely will deprecate this implementation soon. Sorry for the inconvenience.

**Comment by Diwakar8** [comment]
thanks @JustSlone for your response!
