### ISSUE TITLE
Disabled property is missing on a Button when disabled and loading props are both true

### ISSUE THREAD

**Issue by sushruth** [microsoft/fluentui#16853]
Disabled loading buttons (like below) do not render html `<button>` with `disabled` property.

```tsx
<Button disabled loading content="loading" />
```

### Environment Information

- **Package version(s)**: `@fluentui/react-northstar` at `0.52.0`
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/q083f?module=/example.js&file=/example.js

#### Actual behavior:

The rendered `<button>` element does not have `disabled` property

#### Expected behavior:

The rendered `<button>` element should have `disabled` property

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: NA

**Comment by joschect** [comment]
@sushruth Thanks for the submission! This looks like a bug. We'll get it added to our backlog.
