### ISSUE TITLE
Not able to pass title for IconButton in MS Office Fabric Modal component.

### ISSUE THREAD

**Issue by KishorePatel2005** [microsoft/fluentui#16864]
Environment Information
Package version(s): 7.155.4
Browser and OS versions: 87.0.4280.141 Windows 10 Enterprise 20H2

Actual behavior:
There will be no title related prop provided for Close Icon Button in Modal. Which should be pass as prop.

Expected behavior:
There should be title related prop provided for Close Icon Button in Modal. Which should be pass as prop.

Priorities and help requested:
Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by joschect** [comment]
@KishorePatel2005 Thanks for your submission! I think you might be talking about the Dialog component as the modal does not have a built in close button. The good news is that you can pass in a property to add a title, `closeButtonAriaLabel` is used as the close button's title. Here is a [codepen](https://codepen.io/slimemold/pen/WNoGGrr?editors=0010) with it working as you want!
