### ISSUE TITLE
Is there a way to show Coachmark and teaching bubble only to first few visits of a website user?

### ISSUE THREAD

**Issue by aravindkk** [microsoft/fluentui#16882]
We are working on the admin portal for M365 admins and hoping to use the teaching bubble to help tour the features of the portal. Is there a way to limit showing the coachmark and the teaching bubble to first few visits of the user only, rather than each visit of the user, as this can become irritating/burdening over time to user.

**Comment by joschect** [comment]
@aravindkk Thanks for your question! There is nothing built in to FluentUI that will allow you to do that by default. Instead, you can add or remove the TeachingBubble element with something like `{ someproperty && <TeachingBubble...`} where `someproperty` is a boolean value calculated by whatever surrounding code you have.

**Comment by ecraig12345** [comment]
@dwootton's answer is correct, this is something you'd need to implement using localStorage (though be careful about compliance requirements) or by storing a value on your server somehow. Closing as external since this is out of scope for Fluent UI to implement as something built-in.
