### ISSUE TITLE
There is a text collision on the datepicker component when certain months are selected.

### ISSUE THREAD

**Issue by RobertPakkoMSFT** [microsoft/fluentui#16898]
### Environment Information

- **Package version(s)**: 7.158.3
- **Browser and OS versions**: Reproducible in both Chrome (88.0.4324.150) and Edge (88.0.705.63)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/robertpakkomsft/pen/XWNjXZq

Note: This was created by just pressing the "export to codepen" button on the first datepicker example in the docs

#### Actual behavior:

No divider is present. When May 2021 or Oct 2021 are selected, dates overlap with "Go to today" button.

#### Expected behavior:

Divider is present. Dates do not overlap with "Go to today" button regardless of selection

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No): No

Requested priority: (Blocking, High, Normal, Low): Normal

Products/sites affected: (if applicable): MILA Portal

**Comment by joschect** [comment]
@RobertPakkoMSFT Thanks for the submission! I see what you're talking about. This is definitely a bug

![image](https://user-images.githubusercontent.com/20801176/108892711-0d796a00-75c5-11eb-8bf8-384c6f7e7e6a.png)

**Comment by joschect** [comment]
We'll get this added to our backlog and looked at!

**Comment by RobertPakkoMSFT** [comment]
Thank you for the update. In the meantime, do you have a workaround for this bug? I noticed that it does not appear on your documentation pages, which makes me think there is something I can do to mitigate this issue while it is in your backlog.

**Comment by tobybaratta** [comment]
+1 to this bug; we haven't found a workaround for it and have just turned off the "goToToday" option entirely. From looking at the elements panel, I'd guess that it's because of the flexbox setup?

Not real names of relevant classes, but the flexbox containing the elements of the DatePicker/Calendar): ?
```
<DatePickerFlexbox> 
    <DayPicker/>
    <Divider/>
    <MonthPicker/>
    <GoToToday/> (with position: !absolute)
</DatePickerFlexbox>
```

I think it should be part of the Month Picker for the DatePicker, maybe? 

Seems to be the same issue as #9544 #15651 and #13991 ?
