### ISSUE TITLE
"Go to today" and "Go to next year" in calendar are getting truncated when browser zoom is set to 400% for the date picker.

### ISSUE THREAD

**Issue by VardhanAkula97** [microsoft/fluentui#16896]
### Environment Information
 OS: Win 10
Browser: Chrome

### Describe the issue:

"Go to today" and "Go to next year" in calendar are getting truncated when browser zoom is set to 400% for the date picker

### Please provide a reproduction of the issue in a codepen:
- Set the zoom at 400%
- Open fluent UI controls
- Navigate to the calendar  (“From: Select a date” or “To: Select a date”) in the  default date picker (Link: https://developer.microsoft.com/en-us/fluentui/#/controls/web/datepicker) 
- Invoke the calendar and observe that the month picker is truncated and "Go to current date" and "Go to next year" are not clearly visible.
<img width="1656" alt="Screenshot 2021-02-09 at 6 23 31 PM" src="https://user-images.githubusercontent.com/78815662/107406885-f6e80300-6b2e-11eb-8fac-0d0b674cd387.png">
 

#### Actual behavior:

On Invoking the ‘Date’ button and navigating to calendar few months,  "Go to next year" and "Go to today" buttons are truncated.

#### Expected behavior:

All the content should be clearly visible without any overlapping or truncation when browser zoom is set to 400%.

### Documentation describing expected behavior

MAS 1.4.10 – Reflow

**Comment by joschect** [comment]
@VardhanAkula97 Thanks for the submission! I can see what you're experiencing. This is currently being logged and tracked in [this issue](https://github.com/microsoft/fluentui/issues/12863). I've added @lorejoh12 and @ecraig12345 for visibility but per the comments on that issue it looks like we are planning to meet the zoom requirement in the future. For now I'm closing this as a duplicate.

**Comment by VardhanAkula97** [comment]
Thanks  a lot for the reply
