### ISSUE TITLE
dangerouslySetInnerHTML does not work for the Text component

### ISSUE THREAD

**Issue by ashwinGokhale** [microsoft/fluentui#16900]
### Environment Information

- **Package version(s)**: 7.153.4
- **Browser and OS versions**: Chrome/Windows

#### Actual behavior:

I don't want to create a codepen account so here is the code copied and pasted from codepen at https://aka.ms/fluentpen:

```tsx
let { 
  Text
} = window.Fabric;

const Content = () => {
  return (
    <div>
      <Text dangerouslySetInnerHTML={{
            __html: '<p>This should display</p>'
          }}></Text>
    </div>
  );
};

ReactDOM.render(
  <Content />, 
  document.getElementById("content")
);
```

The content of the `<Text/>` component is an empty `div`.

#### Expected behavior:

The content of the `<Text/>` component should be `<p>This should display</p>`.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No) I'm not familiar with how Fluent UI works internally, so I don't think I could fix it myself.

Requested priority: (Low)

**Comment by joschect** [comment]
@ashwinGokhale Thanks for the question! I don't believe that we actually support that particular html property, but it is inherited from React.AllHTMLAttributes. We'll need to add an omission for it since it's not used. @ecraig12345 might have more specific comments about the text field, but for now I believe that it's intentional that we don't support it.

**Comment by ecraig12345** [comment]
This is for Text, not TextField. But I'm not sure `dangerouslySetInnerHTML` is ever expected to work on things besides built-in elements.

**Comment by ashwinGokhale** [comment]
Based on my understanding, I thought the Text component was supposed to be a decorated native span element that is connected to Fluent styling. I'm treating it as a native span, but you're saying I shouldn't do that?

**Comment by ecraig12345** [comment]
@ashwinGokhale Yeah if what you're interested in is `__dangerouslySetInnerHTML`, I think it's best to just use native elements. (Or put a native element inside the Text if you want the styling.)

**Comment by ashwinGokhale** [comment]
Thank you! I will stick to using the native span element.
