### ISSUE TITLE
Feature request / clarification on use with SVG elements

### ISSUE THREAD

**Issue by PathToSharePoint** [microsoft/fluentui#16928]
#### Describe the feature that you would like added

Compatibility with SVG elements.

#### What component or utility would this be added to

Tooltips and other context components.

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

The Northstar documentation says that components such as tooltips work on DOM elements:

> it is possible to provide any DOM element as tooltip's target.

However I haven't been able to use the tooltip on SVG elements such as circle.

I'd be happy to do more testing, but first I'd like to confirm the expected behavior. When the documentation says "DOM element", does this include SVG?

Thanks!

**Comment by gouttierre** [comment]
@PathToSharePoint : Thank you for filling this feature request. If you have a PR pertaining to this feature request - we would live for you to submit it! 
However, for now,  I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it right away, as we’re currently focused on larger coherence work items and enhancements to our performance. Thanks!

**Comment by PathToSharePoint** [comment]
Thank you for the update. And sorry, when it comes to React PRs are out of my league. I can definitely help with the docs and provide feedback on the components. I can understand the priority on coherence, as I have tried to mix Northstar with regular Fluent UI React, the Microsoft Graph Toolkit, and the SharePoint Framework in SharePoint and Teams.
