### ISSUE TITLE
IE11: Toggle has no focus state

### ISSUE THREAD

**Issue by taurheim** [microsoft/fluentui#16938]
### Environment Information

- **Package version(s)**: 7.156.0
- **Browser and OS versions**: Internet Explorer, Win10

### Please provide a reproduction of the bug in a codepen:
https://fabricweb.z5.web.core.windows.net/oufr/7.159.0/#/examples/toggle

#### Actual behavior:
Tabbing to toggle shows no outline

#### Expected behavior:
Tabbing to toggle shows outline (can be seen in other browsers)

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Any products using toggle

**Comment by gouttierre** [comment]
@taurheim - Thanks for submitting this issue. I tried to replicate the issue and didn't have the same issue.
`I used IE11`
![image](https://user-images.githubusercontent.com/78806055/110645152-056d1d00-81b6-11eb-9698-4325e06ae896.png)
`Managed to toggle and see the square outline.`
![image](https://user-images.githubusercontent.com/78806055/110645394-364d5200-81b6-11eb-8fb4-4560af579d4d.png)

However, I see you have a PR you willing to submit for this issue. Could you share it with us?

**Comment by taurheim** [comment]
Hi @gouttierre,

The image you linked is not the toggle - it is further down the page. Try tabbing to this control:
![image](https://user-images.githubusercontent.com/5691564/110683838-561e4f00-8191-11eb-8a34-0aa5cb26ed8c.png)
(in this image I have the top toggle focused)

In chrome it looks like this:
![image](https://user-images.githubusercontent.com/5691564/110683960-71895a00-8191-11eb-8da2-02247fe948ad.png)

I do not currently have a PR fix for it but I am willing to submit one. Can you confirm that you are able to repro?

**Comment by taurheim** [comment]
This still repros. Since this topic has gone quiet and I haven't received a response I'll submit a PR to fix the issue

**Comment by khmakoto** [comment]
@taurheim that sounds awesome, thank you! I'll reopen the issue for you to match your PR against.

**Comment by ayonix** [comment]
Would this also help with the keyboard focus issues in dropdowns?
When selecting items in dropdowns/comboboxes no black border is rendered in IE whereas they're rendered in Chrome/Firefox.

**Comment by taurheim** [comment]
@ayonix the fix could be related - see my PR above that only fixes the issue for toggles but it could be the same root cause!

**Comment by ayonix** [comment]
By adding `overflow: visible` to the parent elements via the DOM-explorer the problem is fixed for the ComboBox/Dropdown-menus. I don't have time to setup the build environment for this project though, could I ask you to have a look into it?
