### ISSUE TITLE
Resolve active dependabot issues

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#16933]
https://github.com/microsoft/fluentui/security/dependabot

There are a set of new dependabot issues that need resolving. We should get on this soon. 

@joschect agreed to pick this up as part of shield duties. 

For each issue we should pick a course of action. The default should be to update, but for low severity ones we can discuss alternatives (as long as we're not impacted by the issue).

**Comment by JustSlone** [comment]
Update:
- Resolved a few

Next:
- Main focus this week is resolving the rest

**Comment by joschect** [comment]
- [ ] PrismJS - Resolved, Dependabot states that it is no longer vulnerable (see screenshot) ![image](https://user-images.githubusercontent.com/20801176/109710246-49c34200-7b52-11eb-9215-026727012151.png)
- [ ] Highlight.js
- [ ] Marked - Resolved, no longer vulnerable ![image](https://user-images.githubusercontent.com/20801176/109710403-79724a00-7b52-11eb-964c-2ef76a2f243e.png)
- [ ] Node-Notifier
- [ ] Yargs-Parser
- [ ] kind-of - Resolved, no longer vulnerable ![image](https://user-images.githubusercontent.com/20801176/109710537-a1fa4400-7b52-11eb-854e-48dad9a7b782.png)
- [ ] dot-prop - Resolved - upgraded lerna to version that no longer relies on vulnerable dot-prop version.
