### ISSUE TITLE
Screen reader announced incorrect column header position

### ISSUE THREAD

**Issue by svirga** [microsoft/fluentui#16977]
### Environment Information

- **Package version(s)**: 7.153.2 +
- **Browser and OS versions**: Edge 88.0.705.50

### Describe the issue:

Screen reader/JAWS reads the incorrect column header position in a cell when visually it appears to be different. In the example it announces the thumbnail column as being column 3 when visually, in the cell, it appears as column 2.

### Please provide a reproduction of the issue in a codepen:
This is reproducible on the Fluent UI site.
https://codepen.io/svirga/pen/YzpNXJy

#### Actual behavior:
In a cell it will read "triangle selected column 8".

#### Expected behavior:

This instead should read, "triangle selected column 7" since visually there are 7 columns of content in the cell. 

### Documentation describing expected behavior

https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7b54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7d&cid=d49909c3-2916-42ec-bd26-70db64408264

**Comment by joschect** [comment]
@svirga thanks for the submission! I think that this is because the collapse all is marked as a column header as you can see below. We'll need to investigate more and get a fix in!
![image](https://user-images.githubusercontent.com/20801176/108921477-43c9e000-75eb-11eb-8e10-6d1ea980e1b9.png)
