### ISSUE TITLE
@fluentui/react-button beta 31 with type={"button"} not working

### ISSUE THREAD

**Issue by mkharibalaji** [microsoft/fluentui#16974]
### Environment Information

  "@fluentui/react": "8.0.0-beta.54",
    "@fluentui/react-button": "1.0.0-beta.31",
    "@fluentui/react-theme-provider": "1.0.0-beta.23",

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/align-buttons-middle-forked-o2cxk

#### Actual behavior:

react button was working with type={"button"} prop and after this beta update its throwing error,

Type '{ children: string; type: string; }' is not assignable to type 'IntrinsicAttributes & ComponentProps & HTMLAttributes<HTMLElement> & { icon?: ShorthandProps<{}>; ... 18 more ...; tokens?: RecursivePartial<...> | undefined; } & RefAttributes<...>'.
  Property 'type' does not exist on type 'IntrinsicAttributes & ComponentProps & HTMLAttributes<HTMLElement> & { icon?: ShorthandProps<{}>; ... 18 more ...; tokens?: RecursivePartial<...> | undefined; } & RefAttributes<...>'.ts(2322)

#### Expected behavior:

This should work as part of
interface ButtonHTMLAttributes<T> extends HTMLAttributes<T> {
        autoFocus?: boolean;
        disabled?: boolean;
        form?: string;
        formAction?: string;
        formEncType?: string;
        formMethod?: string;
        formNoValidate?: boolean;
        formTarget?: string;
        name?: string;
        **type?: 'submit' | 'reset' | 'button';**
        value?: string | ReadonlyArray<string> | number;
    }

Let me know if this is how the button is intended to work or is it a bug ? because we are not able to submit forms and react hook form library as one example.

**Comment by JustSlone** [comment]
@mkharibalaji thanks for brining this to our attention. react-button is still un-released and under active development. I would hold off using it in production until we release a final release. It will go through a few more iterations soon, then hopefully stabilize, but even then it will still be pre-release for some time. 

@khmakoto Is this break to button intentional? Is there an easy change that can be made to resolve the error?

**Comment by khmakoto** [comment]
This is something that broke after some changes fixing types in `@fluentui/react-compose`. I've integrated a simple fix into another change that's linked above.
