### ISSUE TITLE
Update/improve scaffolding tools

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/fluentui#16971]
#### Describe the feature that you would like added

The current scaffolding tools are not 100% updated. 
The idea is to update the scaffolding scripts to follow [implementation patterns](https://github.com/microsoft/fluentui/blob/master/rfcs/converged-implementation-patterns.md) that are being designed.

#### Have you discussed this feature with our team, and if so, who

@jurokapsiar , @ling1726

**Comment by JustSlone** [comment]
Update:
- Waiting on PR review
