### ISSUE TITLE
UNchecking checkbox still return 'on' for the control

### ISSUE THREAD

**Issue by davvit** [microsoft/fluentui#16986]
### Environment Information

Chrome, Edge , React

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/davvit/pen/dyONQOG

#### Actual behavior:

unchecking a checked checkbox returns ON

#### Expected behavior:

unchecking a checkbox should return empty string 

### Priorities and help requested:

Requested priority: (Blocking, High, Normal, Low) 
Blocking,  High

Products/sites affected: (if applicable)
dev app.

**Comment by davvit** [comment]
Looking for update on this...its basic functionality of the control

**Comment by davvit** [comment]
hi @joschect any update on this?

**Comment by gouttierre** [comment]
@davvit : thank you for the feedback and repo steps shared.

@khmakoto - Would you be able to if this is a regression or -  if this behavior is an issue?

**Comment by lsurma** [comment]
Hi,

@davvit in case you didn't resolve your issue already, here is link to codepen with working example of checkbox checked state: https://codepen.io/lsurma/pen/eYvqNWw
It is based on your code.

According to docs: https://developer.microsoft.com/en-us/fluentui#/controls/web/checkbox
In onChange callback, there is a second value passed down to your function. You can use it for determining if the input is currently checked or not.
