### ISSUE TITLE
Is there any way to skip the count of ContextualMenuItem and render custom button?

### ISSUE THREAD

**Issue by v-vibsingh** [microsoft/fluentui#16990]
Hi,

Is there any way to skip the count of ContextualMenuItem and render customize button?

**Sample Code:**

      [...listItems, {
        key: 'buttons',
        onRender: () => {
          return (
            <div className='custom-class-container'>
              <ActionButton text='FILTER CLEAR' onClick={() => this.clearFilter()} />
              <div className='custom-class-button'>
                <PrimaryButton
                  id='apply-button'
                  text='FILTER APPLY'
                  onClick={() => {
                    this.submit();
                    this.close();
                  }}
                />
                <DefaultButton text='FILTER CANCEL' onClick={this.close()} />
              </div>
            </div>
          );
        }
      }]

With above code rendered element have <code>aria-setsize="13"</code> (if the length of listItems is 12) on second last element of <code>li > button</code> but in last element of <code>li > button</code> doesn't have <code>aria-setsize</code> attribute.

**Desired output:**

Rendered element should have <code>aria-setsize="12"</code> (if the length of listItems is 12) on second last element of <code>li > button</code> and last element of <code>li > button</code> doesn't required to have <code>aria-setsize</code> attribute.

![image](https://user-images.githubusercontent.com/76475047/107936880-312b2780-6fa9-11eb-94d2-505b0fa41159.png)

**Note:** https://stackoverflow.com/questions/66207229/is-there-any-way-to-skip-the-count-of-contextualmenuitem-and-render-custom-butto

**Comment by v-vibsingh** [comment]
@joschect 
Could you please look into this issue.?

**Comment by gouttierre** [comment]
@v-vibsingh - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [ContextualMenu](https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by v-vibsingh** [comment]
Yes we are working on it. Will provide link of CodePen soon.

**Comment by v-vibsingh** [comment]
@gouttierre

Please find the requested code by accessing below mention URL:
 **CodePen**: https://codepen.io/v-vibsingh/pen/QWddzWK
 **Git gist**: https://gist.github.com/v-vibsingh/fdd55a52d332451ae1a4be9e670a6cd6

**Comment by v-vibsingh** [comment]
@joschect @gouttierre 
Any update on this issue?

**Comment by gouttierre** [comment]
@v-vibsingh - thank you for providing the CodePens - this will help with the investigations. 

@tomi-msft  - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by v-ajrai** [comment]
Any ETA when we could get fix for this ?

**Comment by v-vibsingh** [comment]
Hi @behowell 
When we expect an update on this issue?
