### ISSUE TITLE
VerticalBarChart: Cannot read property 'x' of undefined error if empty data provided

### ISSUE THREAD

**Issue by FeodorFitsner** [microsoft/fluentui#17000]
### Environment Information

- **Package version(s)**: @fluentui/react-charting@5.0.0-beta.55
- **Browser and OS versions**: Chromium Edge

### Please provide a reproduction of the bug in a codepen:

No codepen required as the issue clearly noticable at this line: https://github.com/microsoft/fluentui/blob/master/packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx#L88

#### Actual behavior:

`Cannot read property 'x' of undefined` JavaScript error.

#### Expected behavior:

No error

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: https://pglet.io

**Comment by gouttierre** [comment]
@FeodorFitsner - thank you for your patience and I see the PR is in progress but perhaps delayed for a reason. 
I have pinging those folks on issue #17003. To get this unblocked and moving. 

cc:  @khmakoto - I am looping you in for visibility.
