### ISSUE TITLE
Ability to stack image on top of each other

### ISSUE THREAD

**Issue by tanisha2710** [microsoft/fluentui#17022]
#### Describe the feature that you would like added

the Facepile component places the personas side by side is there a way to stack them on top of each other

#### Additional context/screenshots

some thing like in the screenshot attached
<img width="546" alt="Screenshot 2021-02-17 at 1 08 42 AM" src="https://user-images.githubusercontent.com/35432621/108165119-0dd2ba80-7118-11eb-8e97-38270aa5c127.png">

**Comment by tanisha2710** [comment]
could some one assist me and let me know if it is possible with the available props or not

**Comment by gouttierre** [comment]
@tanisha2710 - thanks for your reaching out. When there is a need to show the face pile expanded into a vertical list, include a downward chevron button. Selecting the chevron opens a standard list view of people. For more information - visit our 
[facepile docs](https://developer.microsoft.com/en-us/fluentui#/controls/web/facepile). 

In the future, please add a CodePen repro before so we can better help. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
Please submit a codepen in the furutre if you have questions.
