### ISSUE TITLE
Submenu of contextual menu captures the focus when mouse hover

### ISSUE THREAD

**Issue by lijunle** [microsoft/fluentui#17035]
### Environment Information

- **Package version(s)**: Fabric-react@7
- **Browser and OS versions**: Chrome/Edge/all browsers

### Describe the issue:

- **Component**: contextual menu

When mouse hover on the contextual menu items, the item will capture the focus and make the currently focusing element blur.

1. Demo codepen: https://codepen.io/lijunle/pen/BaQRbpL?editors=1010
2. The currently focusing element will be shown in the output box.
3. After the menu is open, mouse hover on the menu item.
4. As you can see, the hovering item gets the focus even I did not click it.

![ContextualMenu-HoverCaptureFocus](https://user-images.githubusercontent.com/1296500/108255225-d4e31780-7110-11eb-8e63-5f20f19eeaab.gif)

#### Expected behavior:

Mouse actions without clicks should not affects the currently focusing element.

**Comment by joschect** [comment]
@lijunle Thanks for the submission! This is intentional behavior as the expectation is that the contextualmenu's should work like their client counter parts. You can set `delayUpdateFocusOnHover` to true and that will ensure that the contextualmenu doesn't steal focus until it is explicitly focused by something like keyboarding into ti.

**Comment by lijunle** [comment]
Hi, @joschect Thanks for your reply! Is it possible to provide an option to complete skip the force logic?

My scenario is making a people picker inside a contextual menu as you see in the GIF. When the picker drop down is open and mouse move on the menu item, the menu item drags the focus and cause the picker drop down dismissed.

![FocusRace-DismissPeoplePicker](https://user-images.githubusercontent.com/1296500/108287928-7df53680-7140-11eb-9ef2-2888fc0519c7.gif)

**Comment by lijunle** [comment]
@joschect I tried to add a prop but figure out the logic is too complicated. Besides, we have V7/V8 divorce. I have another discussion with designer. We are going to solve this issue on our side - when the dropdown is open, pass `disable:true` menu item to avoid focus race.
