### ISSUE TITLE
Northstar: Excessive margin of Dialogs in small devices

### ISSUE THREAD

**Issue by sr258** [microsoft/fluentui#17046]
### Environment Information

- **Package version(s)**: Northstar 0.52.0

#### Actual behavior:

In devices (or windows) with small screen sizes, dialogs have a big margin to the left and right. This makes them nearly unusable. See this example:

![Screenshot_20210218_070744](https://user-images.githubusercontent.com/15268740/108313252-52ae2e00-71b8-11eb-806c-8bb3b5b28711.png)

#### Expected behavior:

The Dialog component uses the available space.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by gouttierre** [comment]
@sr258 - thanks for filing this request with us.  but you’ll need to add a CodePen repro before we can help. You can start from one of the [dialog](https://fluentsite.z22.web.core.windows.net/0.52.2/components/dialog/definition?showCode=false&showRtl=true&showTransparent=false&showVariables=false#types-dialog)
