### ISSUE TITLE
Date Picker - selected date got reset after clicking outside of calendar

### ISSUE THREAD

**Issue by FeodorFitsner** [microsoft/fluentui#17045]
### Environment Information

- **Package version(s)**: @fluentui/react@8.0.0-beta.55
- **Browser and OS versions**: Chromium Edge

### Please provide a reproduction of the bug in a codepen:

The issue is best described with the following screen capture:

![2021-02-17_20h06_42](https://user-images.githubusercontent.com/5041459/108304334-abe87400-715c-11eb-9d0b-0cb7c53b2f69.gif)

#### Actual behavior:

The selected date got reset.

#### Expected behavior:

Selected state should stay intact. Fluent UI v7 doesn't have this issue, so it looks like a regression in v8.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: https://pglet.io

**Comment by joschect** [comment]
@FeodorFitsner Thanks for submitting this issue and submitting a fix! We'll get this looked at.
