### ISSUE TITLE
<TextField type="number" /> behaviour like <input type="number" />

### ISSUE THREAD

**Issue by timgerhard** [microsoft/fluentui#17055]
#### Describe the feature that you would like added

As of now it seems possible to assign a type to the TextField component like this: `<TextField type="number" />` but it doesn't seem to have any effect. 
It would be nice to have a `<TextField type="number" />` component with similar behaviour like `<input type="number" />` (min, max, step and only allow numbers).

**Comment by joschect** [comment]
@timgerhard Thanks for the question! I believe that we do already have a component that fits your need. Have you taken a look at SpinButton? The name isn't the best but it has the exact properties that you've mentioned. Here is [a codepen](https://codepen.io/slimemold/pen/OJbgQYL?editors=0010) with it as an example!

**Comment by timgerhard** [comment]
@joschect Thanks! Seems like that's exactly what I was looking for. 
Why would you make a seperate component for that though? Wouldn't it make far more sense if it was part of the `<TextField>` component?
