### ISSUE TITLE
OUIFR has left the building (circa 1976)

### ISSUE THREAD

**Issue by velociwabbit** [microsoft/fluentui#17068]
I have been working on a new  info based web product using OIUFR and fluent as the primary library for components.  When i finished the first alpha version the package weighed in at a hefty 1.8mb.

To make a long story short by replacing all the ouifr components with other alternatives I was able to reduce the footprint down to < 500k (before zipping and preact).  

I am now able to port to preact which should cut the bundle down to about 300k before gzip and about 70k afterward.  This is a big big big difference and reduces load time by 90 %.

I am reporting this because I really like the OUIFR library but when i go through the individual components they are 1970's elvis- like and I am thinking that this will be a problem for others as well.

To that end I have cobbled together a  ~400 loc version of mergeStyles all in one file which seemed to cut out a great deal of bloat for some reason.

I also have made some custom components that are also much smaller (at a tradeoff of rtl and some accessibility and uber typescript)

OUIFR is a bit of a frankenrepo in that there are so many options and permutations that are combined together.

My guess is that others are also struggling with this fact.

I am calling this a bug because i had to do a work around by rewriting all the ouifr components in order  to get it to work reasonably.

I suggest that there be a set of more focused repos that  address this issue.   

It will require going through and paring down the layers and will sacrifice that illusive and not necessarily wise goal of perfect refactoring so that there there will be some code replication (which ironically will make it smaller).

Let me know how i can help

**Comment by JustSlone** [comment]
This isn't a constructive issue, I'm going to close it, hope you understand. 

To touch on your question briefly, we are, actually, working on refreshing and updating the components overall. Focusing on improving both bundle size and render perf. see: https://github.com/microsoft/fluentui/blob/master/rfcs/convergence/focus-and-iteration-towers-2.0.md

**Comment by velociwabbit** [comment]
I realize that it is not  directly actionable but it is something that I noticed that was a big problem.  I really like OUIFR and code size / number of layers of modules / engineering theatre to make things more formal have a real consequence and will ultimately reduce use of the library. Perhaps IT applications that are used by a few hundred people can afford this luxury but even yesterday I was speaking to a few developers who  have also come to the conclusion that libraries and npm modules should be avoided as much as possible due to this (and related issues).

**Comment by JustSlone** [comment]
Yep, there is a balance between feature rich and streamlined for sure. We are refreshing the component architecture, which will clean things up. Things will be messy as we refresh components, but they will settle down in the end.

Btw, based on what you've looked at, and your application. What would bundle size would you expect a feature rich React component library to come in at (minified+gzip)

**Comment by velociwabbit** [comment]
Apologies on the title... i thought it was funny but in hindsight a bit sophomoric .  :)    

Regarding bundle size... There is a big difference between  400k+  and  < 200k in terms of load time.  

I also think that the mergeStyles concept is spectacular but the getStyles baseComponent MergeStyleSets combination creates a bit more complexity and bulk than necessary. 

I have been looking at the recent updates to the charting modules which used to use d3 heavily and have changed to a direct svg model that appears to be flatter, faster and more robust (nice work team) .  They are going in the right direction.

I think part of the problem is that OUIFR is serving two masters... the IT c#.net to React full stack for internal corporate use and the wild wild west of apps running on the net.

For example as much as I love using stack... it is a convenience function that can be replaced in most situations by a simple div flex pattern... not universally but if you are trying to be a cowboy (keeping with the wild west metaphor) a lot better than 500 dense lines of code combined with some very sophisticated object creation.

Another example is the date time set... it is decomposable into many individual components all which have their own code base but because if the complexity in how it is constructed there is no shift mouse, or alt mouse or ctrl mouse multi select patterns.  Only by number of days. I looked into this awhile back  and even wrote a solution to the problem but integrating it into the ts module set was daunting.

Perhaps every major component in addition to a base component could have a "flat" component that is, not intended to be universally applicable without direct customization.  (in other words the user copies the source and modifieds it directly instead of depending upon parameters.)

I realize that such an approach will cause a bit of angst with some people (it is not how  teachers taught them in school ) but it will have the merits of better performance, smaller footprint, less complexity, easier to identify and fix when bugs occur  and able to be modified specifically).

The downside is that it in effect creates a mini-fork of the component every time it is used...   

The argument against that issue is that javascript is different from other languages such as csharp etc.  One does not maintain javascript code (in general) it is usually faster and more reliable just to rewrite it .

Food for thought
