### ISSUE TITLE
Spfx office UI fabric Panel not closing on server

### ISSUE THREAD

**Issue by fanago** [microsoft/fluentui#17062]
### Environment Information
Sharepoint 2016
SPfx with react js
- **Package version(s)**: (fill this out)

    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/webpack-env": "1.13.1",
    "formik": "^2.1.4",
    "markdown-loader": "^5.1.0",
    "office-ui-fabric-react-pagination": "0.0.8",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
- **Browser and OS versions**: (fill this out if relevant)
Both in Chrome and edge
### Describe the issue:
I am using office-ui-fabric Panel component. The panel open and closes with out any issue in local host(http://localhost:4321/temp/workbench.html), However, when I used the workbench with the server url (https://(siteUrl)/_layouts/15/workbench.aspx), the panel will not close.

 
         <Panel
         isOpen={true}
         type={PanelType.medium}
         headerText="Add New Contract"
         closeButtonAriaLabel='Close'
         onDismiss={this.onPanelClosed.bind(this)}>
        <TextField
                type="text"
                name="Title"
                onChanged={this.handleTitle}
                label="Title"
              /></Panel>

 
This is the method to close the panel
 ` onPanelClosed() {
    this.setState({
      show: false
    });
  }`

#### Actual behavior:

  Panel not closing 

#### Expected behavior:

 Panel should close 

### If applicable, please provide a codepen repro:
I tried to reproduce but I am using class component and the codepen is treating it as an error.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
 no
Requested priority: (Blocking, High, Normal, Low)
Normal 
Products/sites affected: (if applicable)
Local development App

**Comment by fanago** [comment]
Thank you! I just updated the request now, I accidently submitted without detail. Please let me know if you want any more information

**Comment by fanago** [comment]
![expected Panel to close](https://user-images.githubusercontent.com/73078218/108419590-b3f9ef80-7200-11eb-92f7-a8ebac9d4f2a.gif)
![actual behavior](https://user-images.githubusercontent.com/73078218/108419794-f8858b00-7200-11eb-96d8-b8a211bdca2d.gif)

**Comment by fanago** [comment]
Any updates?

**Comment by JustSlone** [comment]
@fanago, sorry this issue is fairly complex. It's going to be pretty hard to investigate this without a repro.

Some questions and thoughts:
- What version of office-ui-fabric-react are you using, I'm guessing it's provided by SPFX right?
- React 15.4 is fairly old, it's unlikely, but perhaps we are hitting issues due to the old version of React.
