### ISSUE TITLE
Breadcrumb: collapse menu overflow when item text is long

### ISSUE THREAD

**Issue by kidokidozh** [microsoft/fluentui#17071]
### Please provide a reproduction of the bug in a codepen:
https://codepen.io/kidokidozh/pen/XWNgozv

#### Actual behavior:
Left side of menu is hidden
![image](https://user-images.githubusercontent.com/58833558/108463488-760cd200-72b9-11eb-8aca-0a47243420b6.png)

#### Expected behavior:
Menu is fully displayed, while long item text is truncated

**Comment by gouttierre** [comment]
@kidokidozh  - thank you for the feedback.

@khmakoto - Would you be able to determine if this is a regression or - if this behavior is an issue?

**Comment by marksoper** [comment]
We have another repro of this bug in the Azure Machine Learning UI. It is present in production and impacting customers. @khmakoto could we work with you to get this fixed ASAP?
