### ISSUE TITLE
Removing an element from People Picker requires two backspaces instead of one

### ISSUE THREAD

**Issue by lutorre** [microsoft/fluentui#17081]
### Environment Information

- **Package version(s)**: @fluentui/react 7.129.0
- **Browser and OS versions**: Windows Edge, Safari iOS, Chrome

### Please provide a reproduction of the bug in a codepen:

1- Select 4-5 items from the people picker
2- Select the people picker using the computer mouse
3- Try to remove the selected contacts one by one using the backspace key from the keyboard.

Expected result:

#### Actual behavior:

It requires to type the backspace key twice to remove an element

#### Expected behavior:

The last added item should be removed after using the backspace key

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: (Microsoft Teams)

**Comment by gouttierre** [comment]
@lutorre , thank you for the input. 

@khmakoto - Can you determine if this is a regression or if this behavior is an issue? 
- I had a look at the repo of the issues stated,. Noticed that the fifth element added is removed with a single backspace, while the others require 2 selects before removing the preceding elements.

**Comment by khmakoto** [comment]
@lutorre @gouttierre I can confirm this still happens in the latest v7 and v8 versions and it does seem like an unintended issue.
