### ISSUE TITLE
No way of using breakpoints in JSS

### ISSUE THREAD

**Issue by eszychli** [microsoft/fluentui#17096]
#### Describe the feature that you would like added

JSS breakpoints classes. Currently, these exist in [CSS only](https://developer.microsoft.com/en-us/fluentui#/styles/web/layout)

#### What component or utility would this be added to

Fluent styles.

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

Thanks

**Comment by gouttierre** [comment]
@eszychli - Thank you for submitting this request. if you have an idea or a PR you wish to contribute towards this feature, please share it with us! 
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.

**Comment by eszychli** [comment]
Got it, thanks for updating!
________________________________

**Comment by JustSlone** [comment]
@eszychli is there a reason that CSS Grid doesn't meet your needs here?

**Comment by eszychli** [comment]
Hey thanks for getting back, the issue is that I have to had Fluent breakpoints explicitly when using JSS styles. For CSS, there are pre-made classes for achieving it.
Example for usage currently:

**CSS**
hiddenLgDown (pre-made class)

**JSS**
'@media (max-width: 1023px)': {
            display: 'none',
        },

**Comment by eszychli** [comment]
We’re working with JSS styles (makeStyles), so this is not relevant. Would be great to have this as other JSS classes are available (fonts, colors etc)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
