### ISSUE TITLE
[web-components] update accentForegroundCut recipe to favor white when both white and black meet contrast requirements

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fluentui#17111]
There are certain colors where when used as a background, both black and white foreground text would meet 4.5:1 contrast. Currently, in scenarios like this we default to using black text. There are several requests from teams to instead prefer white text. This issue exists to track an update to prefer white text in cases where both white and black pass contrast requirements.

**Comment by gouttierre** [comment]
@chrisdholt - thank you for the input.  If you have a proposal on the approach to be taken for this change, we would like to see the PR as contributions are always welcomed. For now,  I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items for V8 and enhancements to our performance.

**Comment by chrisdholt** [comment]
> @chrisdholt - thank you for the input. If you have a proposal on the approach to be taken for this change, we would like to see the PR as contributions are always welcomed. For now, I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items for V8 and enhancements to our performance.

@gouttierre I think there was some confusion; this issues serves to track this request for the web-component package. No action is requested from the broader team on this.

**Comment by chrisdholt** [comment]
This has been updated and addressed with the move to Recipes as tokens. This can now be accomplished via the Adaptive UI v2 API in Fluent ^1.0.0
