### ISSUE TITLE
Screen readers skip reading the content/header on opening the teaching bubble and only reads about close/next/previous buttons.

### ISSUE THREAD

**Issue by HimanathD** [microsoft/fluentui#17126]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

**Comment by HimanathD** [comment]
Repro steps :  

- Open nvda
- In browser edge,  click on any  show teaching bubble example  @ https://developer.microsoft.com/en-us/fluentui#/controls/web/teachingbubble

Expected: screen reader to read the title/content of the bubble. 
Actual: it simply reads about close or any other button which have focus and ignore the content. User will not have any context what these buttons are with out reading the content.

**Comment by gouttierre** [comment]
@HimanathD - thanks for filing this item and sharing the steps for the repro. I see how the behavior differs on edge.

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue with Edge browsers?
cc @smhigley

**Comment by rwedoff** [comment]
I believe this is fixed now with this PR
https://github.com/microsoft/fluentui/pull/19788
