### ISSUE TITLE
Need an option to Search and Create New in the Combo Box

### ISSUE THREAD

**Issue by abmis-mi** [microsoft/fluentui#17132]
#### Describe the feature that you would like added

We need a feature like this in the Combox Box, where a user can search for an item by typing the search text in the combo box (internallyl calling an api), and if not found in the list the can see a button to create a new item with the text. And option should be there to make it multiselect or select only one.
![image](https://user-images.githubusercontent.com/66029786/108835479-8a243c80-75f5-11eb-91c4-f9ba86190f67.png)

#### What component or utility would this be added to

ComboBox

#### Have you discussed this feature with our team, and if so, who

Not yet

**Comment by abmis-mi** [comment]
Any pointers to achieve this with current combobox by overriding some properties/adding custom code over the current component is also welcome.

**Comment by gouttierre** [comment]
@abmis-mi : Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

Have you taken a look at our documentation for the [Controlled ComboBox](https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox)? See if that suites your current needs. If not, please feel free to submit a PR for the feature request you would want to see added.
