### ISSUE TITLE
Passing aria-live prop directly to Callout component results in nested aria-live regions

### ISSUE THREAD

**Issue by cabillin** [microsoft/fluentui#17151]
### Environment Information

- **Package version(s)**: @fluentui/react: "7.137.2"
- **Browser and OS versions**: Edge Dev (90.0.803.0) + Narrator

### Describe the issue:

Following "Non-focusable Callout with accessible text" example results in nested aria-live regions & the content being read twice by Narrator
![image](https://user-images.githubusercontent.com/71525014/108928640-59450700-75f7-11eb-8a07-b7670f7cf807.png)

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/KnetTravlr/pen/Vwmrwmx

#### Actual behavior:
both callout root & container of passed in content have aria-live resulting in nested aria-live regions (bad practice to my knowledge)
contents of callout is read twice by Narrator

#### Expected behavior:

only container of passed in callout content have aria-live
contents of callout is only read once by Narrator

### Documentation describing expected behavior

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

**Comment by gouttierre** [comment]
@cabillin - Thanks for filling this item with us. I did see your repro as its is described in the issue. 

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue with the callout?
cc @smhigley
