### ISSUE TITLE
Where to find documentation for v6

### ISSUE THREAD

**Issue by aslanovsergey** [microsoft/fluentui#17174]
Hello!

How can I find documentation for version 6? https://developer.microsoft.com/en-us/fluentui gives only v7 docs

**Comment by ecraig12345** [comment]
If you scroll down on the homepage, there's a dropdown that lets you select the version. We'll also be adding a version selector to individual control pages soon.

![image](https://user-images.githubusercontent.com/5864305/109246893-e58e3000-7797-11eb-90a1-286b73dffa33.png)

**Comment by aslanovsergey** [comment]
Thank you! It’s very helpful

Sergey
