### ISSUE TITLE
Unnecessary whitespace at the bottom and double vertical scrollbar in Panel containing Announced component

### ISSUE THREAD

**Issue by aditya-mandavi** [microsoft/fluentui#17173]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: Edge, Chrome

#### Actual behavior:
1. If a Panel contains an Announced component, unnecessary whitespace appears at the bottom of Panel under footer.
2. Also, two vertical scrollbars appear.

![Panel-containing-announced](https://user-images.githubusercontent.com/79637185/109143336-ec13ac00-7785-11eb-9599-0017482345a7.png)

#### Expected behavior:
1. There should not be any whitespace at the bottom of Panel under footer.
2. Only one vertical scrollbar should appear.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@aditya-mandavi - thank you for reaching out and providing the necessary information. I see the repro as stated in the issue. 

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue?
