### ISSUE TITLE
Facepile: Overflow number not properly visible in high contrast mode

### ISSUE THREAD

**Issue by prmutha** [microsoft/fluentui#17182]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "^7.158.0",
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

This issue also repros on Fluent documentation -https://developer.microsoft.com/en-us/fluentui#/controls/web/facepile
Repro steps:
1. Set the facepile- overflow button type = descriptive
2. Turn on high contrast mode
3. Check the number displayed in the overflow button. eg "+5"

#### Actual behavior:

The text color for "+5" is not properly visible

#### Expected behavior:

The text color for "+5" is properly visible

### If applicable, please provide a codepen repro:

You can use the cope example for "Facepile with overflow buttons" from here - https://developer.microsoft.com/en-us/fluentui#/controls/web/facepile

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by bmeersma** [comment]
@paulgildea what accessibility tags should we add to help this be prioritized?

**Comment by joschect** [comment]
@bmeersma Thanks for submitting this! I'm fairly certain that this is happening because we're passing the color "transparent" through to the initials, although I'm not quite sure why we are doing that. I see the exact same behavior with the down arrow which passes the same "transparent color through". I'll get this marked as a bug.

**Comment by bmeersma** [comment]
@joschect thank you. Can you please let us know the ETA? This is a blocker for us to rollout a new feature.
