### ISSUE TITLE
CommandBar doesn't get focus visibility for first time if inside an iframe

### ISSUE THREAD

**Issue by abithap** [microsoft/fluentui#17201]
### Environment Information

- **Package version(s)**: 7.155.0
- **Browser and OS versions**: Chrome/Edge and Windows 10

### Describe the issue:

When CommandBar component is the first element in an iframe, keyboard tabbing through the elements from outside the iframe to inside, doesn't set focus visibility correctly on the first item of commandbar. 
But once the next element to commandBar gets the focus it sets the class "ms-Fabric--isFocusVisible", subsequent keyboard access to commandBar starts working fine.

This is because the first time "ms-Fabric--isFocusVisible" is not set correctly and it was still showing "ms-Fabric--isFocusHidden".

### Please provide a reproduction of the issue in a codepen:

Couldn't codepen since its a component issue inside an iframe

#### Actual behavior:

Keyboard focus is not visible when its focused the first time.

#### Expected behavior:

Keyboard focus visibility should start working when its focused the first time.

### Documentation describing expected behavior
MAS references as supplied by trusted tester:

MAS 2.4.7
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7b3b98b04f-4fab-4d3e-81af-a0906a34849c%7d

**Comment by joschect** [comment]
@abithap Thanks for the submission! Thanks for doing the research into this! I'm not sure that there is a way around this at least for right now. We only set the focusable class when focus has been initiated via keyboarding. I believe that iframes do 
not pass events directly through to the components explicitly and so there is no way that class can get set. If you have control over the contents of the iframe you can call `setFocusVisibility(true)` to force it to be enabled when the iframe receives focus. 

You should be able to see how it's applied if you don't click into the window with [this codepen](https://codepen.io/slimemold/pen/xxRjLzr?editors=0010)
