### ISSUE TITLE
@uifabric/date-time DatePicker swallowing esc behavior for parent Callout

### ISSUE THREAD

**Issue by ameliabateman** [microsoft/fluentui#17204]
### Environment Information

- **Package version(s)**: @uifabric/date-time v7.19.21
- **Browser and OS versions**: Win10 and Chrome, presumed irrelevant

### Describe the issue:

We have a DatePicker inside of a Callout (with numerous other editable fields). While focus is on the DatePicker, 'Enter' pulls up the calendar and 'Escape' minimizes it, but a further 'Escape' does not close the Callout. 'Escape' while focused on any other non-DatePicker field closes the Callout as expected. If the DatePicker is imported from office-ui-fabric-react, the bug does not repro, but the DatePicker found in @uifabric/date-time does exhibit the bug!

#### Actual behavior:

'Escape' while focused on DatePicker [with calendar picker closed] does nothing.

#### Expected behavior:

'Escape' while focused on DatePicker [with calendar picker closed] closes the parent Callout.

### If applicable, please provide a codepen repro:
Here is [the bug **not** reproing](https://codepen.io/ambatema/pen/XWNRNee) because the import is from office-ui-fabric-react. If you take this same exact code and get the import from @uifabric/date-time (which I couldn't figure out in Codepen), esc will no longer close the Callout.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OWA search accessibility bug

**Comment by joschect** [comment]
@ameliabateman  Thanks for the submission! This is interesting, I suspect that it might be happening because the focus isn't returning back to the original callout. I am unsure as to why this behavior might differ between oufr and the date-time package. I don't see any differences but @lorejoh12 might know more.

**Comment by ecraig12345** [comment]
Note that in version 8, the date-time DatePicker is exported from `@fluentui/react` by default, which makes this higher priority to investigate/fix.

**Comment by gouttierre** [comment]
@ameliabateman - Thanks for filing this. 

@khmakoto - Would you be able to investigate/fix why focus isn't returning back to the original callout?
