### ISSUE TITLE
Could not load version 8 component API docs

### ISSUE THREAD

**Issue by andrew-hwahin** [microsoft/fluentui#17208]
### Environment Information

- **Package version(s)**: 8.1.0
- **Browser and OS versions**: Google Chrome 88.0.4324.190 (Official Build) (64-bit) Windows 10 Pro 2004

#### Actual behavior: 
![image](https://user-images.githubusercontent.com/61768800/109443846-a2251180-7a76-11eb-8b93-298b54700948.png)

#### Expected behavior: 
The page should not be blanked

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes)

Requested priority: (High)

Products/sites affected: (if applicable)

**Comment by JustSlone** [comment]
Thanks @andrew-hwahin, I am able to repro the issue as well. 

Looks like the last version 8 of the docs that are available are: https://fabricweb.z5.web.core.windows.net/oufr/8.0.0-beta.43/ from end of January. 

@ecraig12345 will be able to figure out what went wrong

**Comment by ecraig12345** [comment]
Sorry about that, and I'll work on a fix ASAP. In the meantime, you can view the latest docs for version 8 on [this page](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/public-docsite-resources/demo/index.html).

**Comment by ecraig12345** [comment]
I bet this is the same root cause as #17213, likely something to do with @dzearing's webpack 5 changes given the timing.

**Comment by ecraig12345** [comment]
I've also removed all the broken versions from fluentdemo, so it's a bit out of date but at least not entirely broken.
