### ISSUE TITLE
After Callout comes, Focus is going to start of the page

### ISSUE THREAD

**Issue by srkaliva** [microsoft/fluentui#17216]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: All

### Describe the issue:

I have added a callout to a button. When we tried to click on that button callout comes up and when on pressing tab, focus was going to start of the page. Which was not expected.

### Please provide a reproduction of the issue in a codepen:
Checked the same scenario on the callout web page of fluent UI. Issue happing there too

#### Actual behavior:

Focus going to start of the page

#### Expected behavior:

Focus should stay there

**Comment by gouttierre** [comment]
@srkaliva - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
