### ISSUE TITLE
Make progress on accessibility

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#17221]
This is a general issue to track making progress burning down accessibility bugs in March for Fluent UI.

The goal is to get a handle on the backlog of accessibility issues, so we can stay on top of incoming bugs.

Areas of focus include:
- DetailsList
- Pickers
- Calendar/DatePicker
- ContextualMenu

**Comment by JustSlone** [comment]
Update:
- Easy stuff done 🎉 
- Harder issues in progress - DetailsList 🐘

**Comment by JustSlone** [comment]
Update:
- Making progress on "the Hard stuff" - PeoplePicker, DetailsList
- Connected with Design on input for Accessibility issues (unblocked)

**Comment by JustSlone** [comment]
@smhigley can we close out this issue from the March cycle?

**Comment by smhigley** [comment]
Yup!
