### ISSUE TITLE
Template for creating custom components

### ISSUE THREAD

**Issue by blendsdk** [microsoft/fluentui#17239]
Hi,

Is there a template or a tutorial explaining how to build a custom component with FluentUI?
I am using `@fluentui/react` and would like to create a `CollapsibleSection` component just like in DevOps.
Unfortunately I could not find a common way of implementing my custom component by looking (and cannibalizing) the existing components in the repo. I am particularly I am interested in how the `styles` property should be designed and implemented for a component.

Any advice is greatly appreciated.

Thanks.

**Comment by gouttierre** [comment]
@blendsdk - Thanks for filing this, but you’ll need to add a CodePen repro before we can help by seeing your custom component and logic. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen. Our docs fluent web [documentation ](https://developer.microsoft.com/en-us/fluentui#/controls/web)
