### ISSUE TITLE
Integrate new Fluent Icons in our repo

### ISSUE THREAD

**Issue by tomi-msft** [microsoft/fluentui#17238]
As part of icon convergence, we need to integrate the new Fluent UI Icons into our repo.

- [ ] Integrate icons into our repo
- [ ] Integrate icons into a partner's repo
- [ ] Update migration guide and move to inside react-icons package

**Comment by layershifter** [comment]
@tomi-msft is it still a thing? Should be this issue closed?

**Comment by tomi-msft** [comment]
No this is done, I can close it!
