### ISSUE TITLE
Fallback styles

### ISSUE THREAD

**Issue by daewigma** [microsoft/fluentui#17230]
#### Describe the feature that you would like added

The ability to specify multiple versions of a css rule, similar to [This in JSS](https://cssinjs.org/jss-syntax?v=v10.5.1#fallbacks)
This will allow for better support of older browsers (having backup rules for when things like `calc` isn't supported by older browsers)

#### What component or utility would this be added to

@fluentui/merge-styles 

#### Have you discussed this feature with our team, and if so, who

no

**Comment by gouttierre** [comment]
@daewigma - thank you for your suggestion. If you are willing to contribute and submit a PR to  help out- it could speed up the process for this enhancement. 
For now,, I have marked this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.
