### ISSUE TITLE
Setting no default selected tab for Pivot

### ISSUE THREAD

**Issue by eleung83** [microsoft/fluentui#17241]
### Environment Information
- Windows 10
- Node 12.20.4
- npm 6.13.7

### Describe the issue:
Previously, using the Pivot and PivotItems from the office-ui-fabric-react package (currently using latest from NPM), it's possible to set no default selected tab by setting the **"selectedkey={null}"** attribute on the Pivot

e.g. <Pivot aria-label="Basic Pivot Example" **selectedKey={null}**>

This can be replicated by adding this attribute on any codepen or code samples for the Pivot @ [Office UI Fabric pivot docs](https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot)

Applying this same attribute on any codepen or code samples for the FluentUI/React version of the Pivot @ [FluentUI/React pivot docs](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/public-docsite-resources/demo/index.html#/examples/pivot]) no longer applies the same function.

### Please provide a reproduction of the bug in a codepen:
Can just be replicated by using existing codepens from Office UI Fabric docs and FluentUI/React docs

#### Actual behavior:

Setting the selectedKey to null on a Pivot no longer sets no default selected tab for the Pivot in FluentUI/React, but does set a default in OfficeUIFabricReact

#### Expected behavior:

Both packages to operate the same, or new mechanism in FluentUI/React to be able to not set the default

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal)

**Comment by gouttierre** [comment]
@eleung83 - thanks for filling this items with us, I see the differences in the behavior between the versions for Pivot.

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue with Pivot? 
And if possible -  guidance on not setting the defaults for Pivot @[ FluentUI/React pivot doc](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/public-docsite-resources/demo/index.html#/examples/pivot%5D)

**Comment by khmakoto** [comment]
Hi @eleung83, I can't seem to repro this issue in the latest 7 version as can be seen in [this codepen](https://codepen.io/khmakoto/pen/QWGeWRO?editors=1010). Could you take a look again and see if you're still having this issue?

**Comment by khmakoto** [comment]
Hi @eleung83, I can repro this issue on 8 while it didn't happen in v7. This seems to have happened on the conversion to a function component and how our hooks work.

@behowell what do you think about this issue? Should we support not rendering any `PivotItem` via `null` or via another way? Or is this by design?

**Comment by behowell** [comment]
Yes, it appears this was a regression when Pivot was converted to a function component. It looks like it should be easy to fix.
