### ISSUE TITLE
peopicker when resolveDelay = 1000 is used, the callout will be closed again after 1000ms

### ISSUE THREAD

**Issue by IProbably** [microsoft/fluentui#17258]
![MyHub](https://user-images.githubusercontent.com/42802184/109747551-4a231200-7c12-11eb-96c6-c3de36fedf7f.gif)

**Comment by gouttierre** [comment]
@IProbably - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
