### ISSUE TITLE
MessageBox does not dismiss

### ISSUE THREAD

**Issue by davvit** [microsoft/fluentui#17253]
### Environment Information

- **Package version(s)**: (fill this out)    
latest
- **Browser and OS versions**: (fill this out if relevant)     
Chrome, Edge

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/davvit/pen/jOVxgYj

#### Actual behavior:

MessageBox does not dismiss

#### Expected behavior:

Should dismiss

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)

**Comment by davvit** [comment]
hi @khmakoto are you looking at this anytime soon?

**Comment by khmakoto** [comment]
Hi @davvit, this is happening because you're not specifying how the `MessageBar` should dismiss within the `onDismiss` callback. [Here is a codepen](https://codepen.io/khmakoto/pen/WNoaKax) with a very simple implementation of this working.

Let us know if there is anything else we can do to help!
