### ISSUE TITLE
Can't assign VerticalDivider to ICommandBarItemProps.commandBarButtonAs in V8

### ISSUE THREAD

**Issue by qxg** [microsoft/fluentui#17257]
### Environment Information

- **Package version(s)**: 8.1.2
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
In v7, I used a VerticalDivider as divider in CommandBar. https://codepen.io/9x9/pen/JjbZYWQ?editors=1010. However it can't build in v8. 
Code snippet
```
import { ICommandBarItemProps, VerticalDivider } from '@fluentui/react';

const _items: ICommandBarItemProps[] = [
  {
    key: 'divider',
    commandBarButtonAs: VerticalDivider
  },
```

#### Actual behavior:
build error
> Type 'FunctionComponent<IVerticalDividerProps>' is not assignable to type 'IComponentAs<ICommandBarItemProps> | undefined'.
>   Type 'FunctionComponent<IVerticalDividerProps>' is not assignable to type 'FunctionComponent<IComponentAsProps<ICommandBarItemProps>>'.
>     Types of property 'propTypes' are incompatible.
>       Type 'WeakValidationMap<IVerticalDividerProps> | undefined' is not assignable to type 'WeakValidationMap<IComponentAsProps<ICommandBarItemProps>> | undefined'.
>         Type 'WeakValidationMap<IVerticalDividerProps>' is not assignable to type 'WeakValidationMap<IComponentAsProps<ICommandBarItemProps>>'.
>           Types of property 'key' are incompatible.
>             Type 'Validator<Key | null | undefined> | undefined' is not assignable to type 'Validator<string> | undefined'.
>               Type 'Validator<Key | null | undefined>' is not assignable to type 'Validator<string>'.
>                 Type 'Key | null | undefined' is not assignable to type 'string'.
>                   Type 'undefined' is not assignable to type 'string'.  TS2322

#### Expected behavior:

No build error.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal
workaround: 
```
onRender: () => <VerticalDivider />
```

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@qxg  - thank you for pointing this out.

@khmakoto - Would you be able to assist into why there are type build issues? Are there a migration steps needed to port from v7 - v8?
