### ISSUE TITLE
Datetime Picker - Feature request

### ISSUE THREAD

**Issue by abdelbari-talbi** [microsoft/fluentui#17262]
#### Describe the feature that you would like added

I'm working on a lot of projects where I need to specify not only the date but also the time (example: 2021-03-03 **15:00**)

#### What component or utility would this be added to

DatePicker

#### Have you discussed this feature with our team, and if so, who

no

**Comment by gouttierre** [comment]
Thanks @abdelbari-talbi for your request. 
 
I’ll mark this as a feature request and add it to our backlog, but to set expectations - we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.

**Comment by triforce4392** [comment]
Our team could really use this control as well, following for updates.

Mockup image:
![image](https://user-images.githubusercontent.com/3867952/110048948-b92d6300-7d05-11eb-87be-daa3e9ebf18c.png)

**Comment by timothyhoffmann** [comment]
As a workaround I'm using these npm packages:
```
    "react-date-picker": "^8.1.1",
    "react-datetime-picker": "^3.2.0",
```
But having a combined FluentUI widget would be great.
