### ISSUE TITLE
Add conformance test to confirm component event behavior follows HTML platform

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#17265]
This particular issue came from the discussion of how `Button` behaves. 

Turns out `button` (the HTML button) when pressing enter, fires onClick many times. While when pressing space it does not fire onClick, until space is released. 

So given this, our desired state would be for our `Button` to follow this same behavior. Now, we might choose to make an exception, but first we need a conformance test that takes our converged components and compares the eventing behavior with the platform. 

v0 might have something already, @levithomason is the main contact for more context. 

This is the overall spec for this test:
1. Have the ability to compare a component with an HTML equivalent, so `Button` tests would compare with `button`
2. Fire a set of events against `button`, record the results (TODO: figure out the set of events we want to use)
3. Fire the same set of events against `Button`, record the results
4. Compare the results and flag differences
5. We may also need the ability to flag a difference as "OK"

**Comment by ecraig12345** [comment]
@JustSlone Do we still need this?
