### ISSUE TITLE
Page Analyzer Run Complete: [Platform][Keyboard Navigation - Overview]: Tooltip 'Simulated users 125' of the simulated user slider is not getting closed by pressing 'Esc' key.

### ISSUE THREAD

**Issue by Shubham786786** [microsoft/fluentui#17269]
User Experience:
If the content is not operated through a keyboard or keyboard interface, it would not be operable by people with no vision, Some people with hand tremors find using a mouse very difficult , as well as by people who must use alternate keyboards or input devices that act as keyboard emulators. Individuals with low vision would also find it difficult to control it from the keyboard.

Test Environment:
OS build Version 2004 (OS Build 20270.1)
Browser Version: Microsoft Edge Dev Version 89.0.723.0
Screen Reader: NVDA 2020.2
URL: [https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/charting/dist/index.html#/examples/stackedbarchart](url)

Repro steps:
1. Open above URL on Anaheim Dev Browser and login with valid credentials.
2. Navigate to the 'Overview' tab by left arrow key and select it.
3. Navigate to graphic Slider below 'Simulation Coverage' <h2>
4. Verify that Hoverable data is getting collapsed by the 'esc' key or not.

Actual Result:
Tooltip 'Simulated users 125' of the simulated user slider is not getting closed by pressing 'Esc' key.

Expected Result:
Tooltip 'Simulated users 125' of the simulated user slider should get closed by pressing 'Esc' key.

Note: 
1. Same issue repro throughout 'Overview' tab page.

MAS Reference:
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7B60121EB2-D1C5-4525-931F-322A940799EF%7D&file=MAS%201.4.13%20%E2%80%93%20Content%20on%20Hover%20or%20Focus.docx&action=default&mobileredirect=true&cid=f3f626ba-ebbd-425f-be23-74fad12915c8](url)

Attachment:
[MAS1.4.13- Tooltips are not getting closed by esc key.zip](https://github.com/microsoft/fluentui/files/6081576/MAS1.4.13-.Tooltips.are.not.getting.closed.by.esc.key.zip)

**Comment by gouttierre** [comment]
@Shubham786786  - Thank you for the feedback into the issue you are experiencing 

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue? 
cc @smhigley
