### ISSUE TITLE
Bring bottom navigation bar to Web Controls and others

### ISSUE THREAD

**Issue by hmheng** [microsoft/fluentui#17268]
Bring bottom navigation bar to Web Controls and others as it is important for web especially we need to standardize it across different screen sizes.

https://developer.microsoft.com/en-us/fluentui#/controls/android/bottomnavigation

**Comment by gouttierre** [comment]
@hmheng : thank you for the suggestion. If you are will to submit a PR for this feature request, please, do not hesitate to do so.

For now,  I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.

**Comment by JustSlone** [comment]
Thanks for the input, we are in the process of proving out a new component model for Fluent UI React, so we're not going to be adding many new controls right now. If someone is really excited to do the work to contribute this, let us know and we can consider it.
