### ISSUE TITLE
Dropdown responsiveMode prop doesn't work in version 8

### ISSUE THREAD

**Issue by vitkon** [microsoft/fluentui#17288]
### Environment Information

- **Package version(s)**: 8.1.4
- **Browser and OS versions**: MacOS BigSur

### Please provide a reproduction of the bug in a codepen:

cannot reproduce in codepen as I'm opening an Office Add-in in Office365
steps to repro:

- created a boilerplate of office add-in https://github.com/OfficeDev/generator-office
- update to latest fluent ui
- added Dropdown

```
          <Dropdown
              placeholder="Select an option"
              options={captureOptions}
              responsiveMode={ResponsiveMode.large}
              id="capture-mode"
          />
```

#### Actual behavior:

Dropdown always shows Panel even when `responsiveMode` is set to `ResponsiveMode.large`

#### Expected behavior:

Dropdown shows Callout when `responsiveMode` is set to `ResponsiveMode.large`

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) internal

**Comment by vitkon** [comment]
UPD: Managed to reproduce on web too: https://codesandbox.io/s/mystifying-brahmagupta-3kqi4

**Comment by webartoli** [comment]
We found the same issue on fluentui/react 8.4
On: Windows 10, Chrome
On: Windows 10, Office Addin - Excel

**Comment by gouttierre** [comment]
@vitkon - thank you for filing this issue with us. 

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue with fluentui/react v8?

**Comment by gokcan** [comment]
@khmakoto @gouttierre 

I've opened a PR to fix this issue: https://github.com/microsoft/fluentui/pull/17526

**Comment by u-can-miracle** [comment]
Hello @khmakoto could you clarify is this issue in progress? I see it has been opened 3 weeks ago

**Comment by khmakoto** [comment]
Hi @u-can-miracle, the PR seems to still be in progress!

**Comment by markdon** [comment]
Thanks everyone involved. I appreciate your work!
