### ISSUE TITLE
Some component input fields do not specify `font-family: inherit`

### ISSUE THREAD

**Issue by andrewhwng** [microsoft/fluentui#17285]
### Environment Information

- **Package version(s)**: 7.158.3
- **Browser and OS versions**: Chrome - Windows 10 v19042.804

### Please provide a reproduction of the bug in a codepen:

[codepen example](https://codepen.io/anhw/pen/rNWrzJB)

We noticed some of the input components don't have `font-family: inherit` specified, so those fall back onto Arial instead of Segoe. The two we noticed that are impacted are the `Autofill` & `FloatingPeoplePicker` components.

#### Actual behavior:

- font for some components is not inherited by default, so it falls back to Arial. In the codepen, the button inherits the Segoe font while the Autofill component falls back onto Arial.

#### Expected behavior:

Autofill component inherits the font.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OWA - some pickers are a different font family

**Comment by gouttierre** [comment]
@andrewhwng - Thanks for providing the information and codepen for replication. I noticed the behavior you reported.

@khmakoto - Would you be able to confirm if the font inheritance is a regression, or if this behavior is an issue?

**Comment by khmakoto** [comment]
I just sent a PR to fix this issue!
