### ISSUE TITLE
Cursor jumps to the end when typing in freeform ComboBox

### ISSUE THREAD

**Issue by MLoughry** [microsoft/fluentui#17301]
### Environment Information

- **Package version(s)**: 8.1.4
- **Browser and OS versions**: Edge Chromium/ Firefox

### Please provide a reproduction of the bug in a codepen:

The bug is reproducible in the existing Storybook story at `packages/react-examples/src/react/ComboBox/ComboBox.Controlled.Example.tsx`

#### Actual behavior:

When typing or deleting any character in a freeform Combobox, the cursor immediately jumps to the end of the input

#### Expected behavior:

The cursor does not jump around

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes in theory, but I've not been able to track down why this is happening.

Requested priority: Blocking from integrating Fabric v8 into OWA

Products/sites affected: Outlook Web

**Comment by MLoughry** [comment]
It looks like this issue may be the result of the underlying `Autofill` component.

**Comment by MLoughry** [comment]
Here's a CodePen with a minimal repro with `Autofill`: https://codepen.io/MLoughry/pen/QWGZBVE

**Comment by joschect** [comment]
Yep! I'm still validating the fix but I think it should be ready sometime today.

**Comment by gouttierre** [comment]
@joschect  - Do you perhaps have any updates on this one? I see there was a mention of a fix in the works?

cc @khmakoto
