### ISSUE TITLE
Click + drag selection not working in TeachingBubble component

### ISSUE THREAD

**Issue by riosn-n** [microsoft/fluentui#17306]
### Please provide a reproduction of the bug in a codepen:

https://codepen.io/riosn/pen/NWbLRBz

#### Actual behavior:

Click + drag selection works in the Callout component but not in the TeachingBubble (which uses a Callout). This occurs only the primary button is shown.

![image](https://user-images.githubusercontent.com/33673026/110199881-7eafed00-7e0f-11eb-9f46-f814d2678dae.png)

#### Expected behavior:

User should be able to select a specific piece of text inside the TeachingBubble.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

Power Apps, Power Automate, Dynamics CRM.

**Comment by gouttierre** [comment]
@riosn-n - thanks for filing this issue with us.  
@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue with the TeachingBubble implementation?
