### ISSUE TITLE
Crash when upgrading to react 17

### ISSUE THREAD

**Issue by AlexFsmn** [microsoft/fluentui#17313]
### Environment Information

- **Package version(s)**:
fluentui/react 8.1.6
react: 17.0.1
typescript: 4.1.2
- **Browser and OS versions**:
Windows 10
Chrome

#### Actual behavior:
Cannot upgrade project to latest version:
![image](https://user-images.githubusercontent.com/11557675/110311949-c0ee4f80-8004-11eb-9058-58e7cdf20576.png)

#### Expected behavior:
No crash on startup :)

### Additional information:
Cannot upgrade project to the latest version.
However, flunetui/react version 8.1.6 using react 16.8.5 still works.
So this seems to be strictly related to react 17.0.1

**Comment by gouttierre** [comment]
@AlexFsmn - thanks for your feedback and details around the issue experienced. 

@khmakoto - Would you be able to provide guidelines on the upgrade process? And If possible - investigate why this happens when moving to React 17.0.1?

**Comment by AlexFsmn** [comment]
Any update on this issue?
@khmakoto @gouttierre

**Comment by JamesBurnside** [comment]
(Hi, just a random passerby) I've had this error before when I had incorrect peerDependencies listed in a dependency package.json that caused my application to be using two different versions of react.
I used `npx check-peer-dependencies` to find the conflicting react version and ensure all my application and all dependencies were using the same version of react.

For investigating these issues its useful to post a minimal repro to understand what might be going on, if that's not possible are you able to post your lockfile (in a [github gist](https://gist.github.com/)) and package.json(s) of your project to check if there are conflicting react versions?

**Comment by ecraig12345** [comment]
@AlexFsmn Can you please provide more repro details, ideally a codesandbox (start from https://aka.ms/fluentsandbox)? There's currently not enough information provided to troubleshoot.

**Comment by AlexFsmn** [comment]
@ecraig12345 Thank you for handling this case. I've been pretty busy the past couple of days and the solution I'm working on is quite large which makes it time consuming to create a smaller sample of the code that doesn't work.
However, I did manage to recreate a smaller scenario that generated a different but hopefully related problem.
So basically I got the error when using older imports: "office-ui-fabric-react/lib" and "office-ui-fabric-react".

I managed to resolve the error by changing these to the following:
```
office-ui-fabric-react/lib => @fluentui/react/lib
office-ui-fabric-react => @fluentui
```

I haven't seen any migration guide that mentions this but I'm happy to be proven wrong.
I will try to get more details about the error but in the meantime maybe you have any comment about the imports?

**Comment by ecraig12345** [comment]
Changing your imports from `office-ui-fabric-react` to `@fluentui/react` (or `office-ui-fabric-react/lib/Whatever` to `@fluentui/react/lib/Whatever`) is one of the steps in an upgrade to version 8, mentioned in the [release notes](https://github.com/microsoft/fluentui/wiki/Version-8-release-notes#breaking-package-renaming-office-ui-fabric-react-to-fluentuireact).

Once you're on version 8, imports of `office-ui-fabric-react` shouldn't work any more--so if they were appearing to work, that means you may have accidentally ended up with an old `office-ui-fabric-react` version installed somehow. Depending on your package manager you can check this with `npm ls office-ui-fabric-react` or `yarn why office-ui-fabric-react`.
