### ISSUE TITLE
utilities: resolve ts-ignore pragmas to make the package strict mode compliant

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#17331]
#### Actual behavior:

We [turned on TS strict mode for `@fluentui/utilities`](https://github.com/microsoft/fluentui/pull/17161) and as a temporary workaround we added `@ts-ignore` in `packages/utilities/src/EventGroup.ts` to be handled in different PR.

- ![image](https://user-images.githubusercontent.com/1223799/110459219-ffe7d800-80cc-11eb-9789-29cdfc70979f.png)
- ![image](https://user-images.githubusercontent.com/1223799/110459240-070ee600-80cd-11eb-9222-a51de4ac564b.png)
- ![image](https://user-images.githubusercontent.com/1223799/110459253-0bd39a00-80cd-11eb-86fa-8450d292011f.png)

#### Expected behavior:

No use of `@ts-ignore`

### Priorities and help requested:

Requested priority: Normal

**Comment by gouttierre** [comment]
@tomi-msft - Would you be able to investigate this? As I see issue #17161 was merged. Thanks

**Comment by Hotell** [comment]
this hasn't been fixed  - reopening
