### ISSUE TITLE
Northstar's Table/Row behaviors stops arrow keys from working inside an Input

### ISSUE THREAD

**Issue by davyrwoo** [microsoft/fluentui#17337]
### Environment Information

- **Package version(s)**: 0.51.2

### Describe the issue:

Using Northstar's Input within a Table cell does not allow left/right arrow keys to move the cursor that is within the Input. 

The behaviors used are gridNestedBehavior for the Table, gridRowNestedBehavior for the Row, and gridCellMultipleFocusableBehavior for the Cell. These behaviors are used so that the user can have arrow key navigation among the table cells, but use enter on cells to interact with controls within the cells.

### Please provide a reproduction of the issue in a codepen:

https://codesandbox.io/s/fluent-ui-example-forked-q3emg?file=/example.js

1. Click the input field
2. Use right/left arrow keys

Alternatively, if you want to recreate the full keyboard navigation experience:

1. Tab to the Table
2. Use up/down arrows to navigate to a row
3. Use right arrow to enter cell selection
4. Click enter on cell with Input
5. Use right/left arrow when focus is within the input field

#### Actual behavior:

Arrow keys do not move the cursor within the input field

#### Expected behavior:

Arrow keys should move the cursor within the input field

**Comment by gouttierre** [comment]
@davyrwoo : thank you for filling this issue. I noticed the behavior mentioned in your repo where the arrow keys do not move the cursor within the input field region.

@khmakoto -> Would you be able to confirm if this is a regression, or if the recorded behavior is an issue? Thanks

**Comment by jurokapsiar** [comment]
Hi @davyrwoo, you will need to stop propagation of keydown event so that it is only handled by the input: https://codesandbox.io/s/fluent-ui-example-forked-q3emg?file=/example.js

Please also note:
- you might want to allow Esc to be propagated so that user can get out of the cell
- setting `value` on Input makes it constant, you can use `defaultValue` for just setting the initial state.
