### ISSUE TITLE
Dialog with top offset fixed enabled does not re-center when the window is resized

### ISSUE THREAD

**Issue by katiearriagam** [microsoft/fluentui#17345]
### Environment Information

- **Package version(s)**: ^7.162.0
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen: 
The bug can repro in the demo page: https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog

1. Open the `Dialog with Top Offset Fixed` example.
2. Resize the browser window and observe that the dialog is not re-centered.
3. Open the `Default dialog` example.
4. Do step 2 again but observe that this time the dialog is re-centered. This is the expected behavior.

#### Actual behavior:
- Dialog does not re-center when screen is resized. This is what happens in the `Dialog with Top Offset Fixed` example.

#### Expected behavior:

- Dialog should re-center when screen is resized. This is what happens in the `Default dialog` example.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Office Online

**Comment by katiearriagam** [comment]
This GIF shows a repro of the issue in the live demo page

![fluent-dialog-topoffsetfixed-notcentering](https://user-images.githubusercontent.com/14140121/110556401-494b1e00-80f3-11eb-9275-85f6729438cf.gif)

**Comment by katiearriagam** [comment]
@khmakoto what do you think?

**Comment by khmakoto** [comment]
@katiearriagam I think this is to be expected since the `topOffsetFixed` prop, as its name indicates, fixes the distance from the top of the frame when opening the `Modal`. You can actually see this by opening the `Dialog` in small screen and maximizing it afterwards where it will re-center horizontally but won't change the top offset.
