### ISSUE TITLE
GroupHeader with no column headers has large empty spacer

### ISSUE THREAD

**Issue by molinger** [microsoft/fluentui#17348]
### Environment Information

- **Package version(s)**: @fluentui/react@8.1.7

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/molinger/pen/poNQdvz

#### Actual behavior:

There are two versions of @fluentui/react referenced in the codepen. In the later version, there is a large margin to the left of the group header.

![image](https://user-images.githubusercontent.com/3746165/110563810-b74a1200-8100-11eb-89a6-73f1ccc9e2d5.png)

#### Expected behavior:

In the earlier version, the margin is not visible.

![image](https://user-images.githubusercontent.com/3746165/110563866-c761f180-8100-11eb-8ab0-b6340dd4ef65.png)

### Additional information

This was found when trying to update to a newer version of @fluentui/react and is related to the fix for #16120. A hard-coded indentWidth was added to the spacer that fills in for the checkbox when it is not visible. This is to ensure that columns are aligned correctly. In our case though, we don't want the checkbox and don't have column headers. We just want the expand button to be close to the left edge.

**Comment by gouttierre** [comment]
@molinger - thank you for reaching out to us. I had a look at your issue and was not able to repro it. The margin seems good:
![image](https://user-images.githubusercontent.com/78806055/112469400-bbfdff80-8d69-11eb-8c21-6428fd50a995.png)
Could you please recheck and let us know. ~ Thanks!

**Comment by molinger** [comment]
@gouttierre I have two versions of fluent ui in the codepen to show the regression. When you open it, it uses an older version that the does not repro the bug. There is a new version that is commented out. If you switch the version, then it should repro.
