### ISSUE TITLE
Fluent UI website is not working

### ISSUE THREAD

**Issue by renatoromao** [microsoft/fluentui#17357]
Hi,

I'm trying to see the Fluent UI Components on the official website and I can't.

https://developer.microsoft.com/en-us/fluentui#/get-started/web
![image](https://user-images.githubusercontent.com/25510818/110635470-e3f63c00-8189-11eb-9668-14f8572e4c75.png)

_Sorry if I'm posting in the wrong community._

**Comment by eduardocp** [comment]
It's happening to me since yesterday.

**Comment by rdgomt** [comment]
Same here.

**Comment by renatoromao** [comment]
It's working @eduardocp  / @rdgomt ! :)
