### ISSUE TITLE
alt missing in icon image 

### ISSUE THREAD

**Issue by abidkh** [microsoft/fluentui#17358]
There is an accessibilty issue with image-alt. This is not coming while using Icon for image rendering.

![image](https://user-images.githubusercontent.com/41537394/110649458-9e645e00-81df-11eb-990a-debc2de7a015.png)

**Comment by gouttierre** [comment]
@abidkh - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen. Or provide more information pertaining to the screenshot, please. Thank you.
