### ISSUE TITLE
Review of treeAsListBehavior for Tree component

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#17353]
If the tree cannot be displayed as "Tree" on MACOS then we recommend to use:

`Use `treeAsListBehavior` for `Tree` component, and `treeAsListboxBehavior` for Multi-select `Tree` component, when `Tree` is displayed for macOS.`

  `treeAsListBehavior` behavior rewrites Tree roles into List/Listitem roles. 

But in real usage List/Listitem should not carry, contains actionable elements and list should be used only for displaying information. Generally using the List/Listitem is not specified well by aria. 

Example "As a List" url:
https://fluentsite.z22.web.core.windows.net/0.52.1/components/tree/definition#usage-tree-as-list-example

We need to reconsider if we still should use List/Listitem roles as alternative for tree on MACOS.

**Comment by gouttierre** [comment]
@kolaps33 - thank you for the information provided.

@jurokapsiar - i will tag this for further discussions - could you review with your team the suggestion posted for the [Tree ](https://fluentsite.z22.web.core.windows.net/0.52.1/components/tree/definition#usage-tree-as-list-example)Component.?
