### ISSUE TITLE
add active style when dropdown is opened

### ISSUE THREAD

**Issue by Teleology** [microsoft/fluentui#17368]
#### Describe the feature that you would like added

currently, the dropdown doesn't expose the styles for the open state. I prefer it to have something like below so I can customize the UI when the dropdown is in a different state:

```
export interface IDropdownStyles {
    root: IStyle;
   rootPressed: IStyle;
   rootChecked: IStyle;
   rootFocused: IStyle;
}
```

I want to highlight the box but didn't find a field such as rootOpened, so I use CSS and directly override it.
![image](https://user-images.githubusercontent.com/25185373/110693057-e19cdd80-819b-11eb-8ee5-b6778b436bab.png)

#### What component or utility would this be added to

IDropdownStyles

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

No

**Comment by gouttierre** [comment]
@Teleology - Thanks for filling this enhancement for the IDropdownStyles. If you have a suggestion or would like to contribute towards this - please share a PR with us!  For now,  I’ll mark this as a feature request and add it to our backlog for the Dropdown Comps, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.

**Comment by JustSlone** [comment]
Linking to our epic issue for Dropdown - #6030
