### ISSUE TITLE
[Panel] [Accessibility] Ensures aria-hidden elements do not contain focusable elements

### ISSUE THREAD

**Issue by vidyabhavani-d** [microsoft/fluentui#17375]
### Describe the issue: https://developer.microsoft.com/en-us/fluentui#/controls/web/panel

Pre Requisite : Download and install "Axe" plug in in "Chrome/Edge Chromium browsers.
Link to download Axe Tool : https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd

1. Open the URL "https://developer.microsoft.com/en-us/fluentui#/controls/web/panel" in chrome or Edge chromium browsers.
2. Navigate to any of the "Open Panel" button and invoke.
3. once the panel is opened, run the axe tool and verify the issue "ARIA hidden element must not contain focusable elements"

#### Actual behavior:
All the panels have an empty div with the below properties.
i.e. aria-hidden=true; tab-index=0
![image](https://user-images.githubusercontent.com/80450575/110757887-e16f1180-8271-11eb-965b-daee491cefbb.png)
![image](https://user-images.githubusercontent.com/80450575/110758050-124f4680-8272-11eb-9908-b51c1c7b54fa.png)

#### Expected behavior:
There should not be defined "tab-index=0" when "aria-hidden=true" which is contradicting.

### Documentation describing expected behavior
Help URL : https://dequeuniversity.com/rules/axe/3.3/aria-hidden-focus?application=axeAPI

**Comment by gouttierre** [comment]
@vidyabhavani-d - Thank you for filling this issue you picked up. I managed to reproduce your findings.

![image](https://user-images.githubusercontent.com/78806055/111169580-64aaa300-85a3-11eb-8ac1-92ec4895c22e.png)

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue with the component?
cc @smhigley

**Comment by smhigley** [comment]
This is a false positive -- we use bumpers for trapping focus, so those need to be tabbable but also hidden, so they aren't exposed as empty clickable elements to screen readers.

Since focus never actually lands on those elements it's not a real accessibility issue, just a limitation in the automated testing.
