### ISSUE TITLE
Resize details list column in RTL cause the column width to change in the opposite direction

### ISSUE THREAD

**Issue by easy0924** [microsoft/fluentui#17389]
### Environment Information

- **Package version(s)**: (fill this out) current
- **Browser and OS versions**: (fill this out if relevant) chrome, windows

#### Actual behavior:

When details list is rendered in RTL languages (dir="rtl"), resize the column header causes the column size change in the opposite way.

I.e.
If you resize and move mouse to the left, the left column will become bigger, and the right column will become smaller, which is counter intuitive.

You can reproduce with FluentUI documentation examples, where the details list column can be resized

#### Expected behavior:
In the above case, the left column should shrink, and right column should grow

### Priorities and help requested:
The resize function is unusable in RTL 

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
NA

**Comment by gouttierre** [comment]
@easy0924 - thanks for filing this item , I see that the moving the causes the left column to shrink while the right column simply shifts-moves (without resizing) for the [details list](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist) .

@tomi-msft - Would you be able to confirm if this is a regression, or if this behavior is an issue?
