### ISSUE TITLE
Northstar Dropdown multiple item clear button gets smaller the longer the item's text is

### ISSUE THREAD

**Issue by JamyDev** [microsoft/fluentui#17386]
### Environment Information

- **Package version(s)**: 0.52.2
- **Browser and OS versions**: N/A (Windows 10, Edge 89)

### Please provide a reproduction of the bug in a codepen:

[Codepen example](https://codesandbox.io/s/fluent-ui-n-dropdown-item-len-bug-ewhft?file=/example.js)

#### Actual behavior:

Items with long text get stripped to about 15 characters to render them nicely in the multiple select bubbles. At that length there is plenty of space for the ... and the X (clear) button. However, with text lengths longer than about 20 characters the cross button gets smaller even though no extra text is rendered. With long enough text the button is so small it's invisible, and unselectable.

The codepen example has multiple lengths of text, on the last item it's impossible to clear the item as the hit target is too small to select. 

#### Expected behavior:

Cross button on individual items with text length > ~25  is the same size it would be on an item with text length < 10. Items are clearable regardless of text length.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal/High

**Comment by gouttierre** [comment]
@JamyDev - thanks for filing this issue and the CodePen shared., I saw the problem you are experiencing. 

@tomi-msft - Could you investigate and verify if this is a regression, or if this behavior is an issue with `text length > ~25`?

**Comment by JamyDev** [comment]
@gouttierre Seems like this was fixed in 0.54.0 as I can not repro it anymore with that version: https://codesandbox.io/s/fluent-ui-example-forked-lxgcw
