### ISSUE TITLE
DetailsList : List not getting updated when the items are updated, it gets updated only when user scroll

### ISSUE THREAD

**Issue by sangitapujara512** [microsoft/fluentui#17394]
We have a situation where
1)Initially we are showing DetailList from response - with four columns , one column being blank
2)Based on event like select date , calculation is done so that data added for the blank column also
3) This updated data is given as items to the DetailList.

Actual: The blank column for which data is available now does not get updated, it gets updated only when user scrolls.
(even though latest data is available in DetailList component)
Expected: as soon as items is updated for DetailList it should be re-rendered.

**Comment by vivekksc** [comment]
@khmakoto Appreciate any update on this issue.

**Comment by gouttierre** [comment]
@sangitapujara512  - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the[ Detail List examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist) (click “Export to CodePen”) or https://aka.ms/fluentpen.
