### ISSUE TITLE
VirtualizedComboBox with multiSelect not showing selected items

### ISSUE THREAD

**Issue by c2r0b** [microsoft/fluentui#17408]
### Environment Information

- **Package version(s)**: 8.2.1
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

When some items of the `options` prop are set as `selected` the item is not shown as checked in the list of the combobox options. All the options checkboxes are blank. It worked fine in version 7 of the package.

#### Expected behavior:

If an item in the `options` array is marked as `selected`, it should be seen as checked in the list.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: (if applicable)

**Comment by c2r0b** [comment]
Any update on this?

**Comment by gouttierre** [comment]
@c2r0b  - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [ComboBox](https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
