### ISSUE TITLE
ColorPicker: add HSL mode

### ISSUE THREAD

**Issue by soryy708** [microsoft/fluentui#17404]
#### Describe the feature that you would like added

I'd like to be able to change the ColorPicker's mode from RGB to HSL (perhaps through a prop).
This would require modifying the `strings` prop as well.

#### What component or utility would this be added to

ColorPicker

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

ColorPicker currently works only in RGB space. It's very widespread and is a standard way of representing color in electronics.
For some uses (like picking color harmonies) a HSL (Hue, Saturation, Lightness) space is more convenient than RGB.

**Comment by soryy708** [comment]
Here's a MIT-licensed TypeScript implementation of conversion from RGB to HSL and back: https://github.com/soryy708/Palette/blob/master/src/app/color.ts
It has some unit tests: https://github.com/soryy708/Palette/blob/master/src/app/color.unit.test.ts

**Comment by gouttierre** [comment]
@soryy708  - Thanks for reaching out. I’ll mark this as a feature to extend support for HSL (hue, saturation, and lightness) which will go to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.. But If you have a PR for a solution, please do share it with us!
