### ISSUE TITLE
position of the teaching bubble not changes

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#17409]
### Environment Information

- **Package version(s)**: latest version
- **Browser and OS versions**: all browsers

### Please provide a reproduction of the bug in a codepen:

1. go to link https://codesandbox.io/s/brave-blackwell-yvzhf
2. try to scroll
3. see if the position of the bubble changes?

#### Actual behavior:

when you scroll, the position of the bubble is in not sync with button

#### Expected behavior:

when you scroll, the position of the bubble should be in sync with button

### Priorities and help requested:

Are you willing to submit a PR to fix?  No

Requested priority: Normal

Products/sites affected: (if applicable)
https://office.visualstudio.com/OC/_queries/edit/4634323/

**Comment by shivasai09** [comment]
@khmakoto  please let me if it is something by design

**Comment by shivasai09** [comment]
@khmakoto could you give  any update

FYI
@Raghurk , @ecraig12345

**Comment by gouttierre** [comment]
@shivasai09 - Thank you for filing this problem with us. I see the repro as stated on the issue. 
`Before scrolling`
![image](https://user-images.githubusercontent.com/78806055/112035932-5a0e8180-8b40-11eb-8f02-c8e72793de27.png)
`After scrolling down`
![image](https://user-images.githubusercontent.com/78806055/112036032-77435000-8b40-11eb-874c-f2a10278f97d.png)

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley

**Comment by jamesdeancalhoun** [comment]
PowerApps is also affected by this issue. Any update would be appreciated.
