### ISSUE TITLE
Add styles prop to List

### ISSUE THREAD

**Issue by daniel-hauser** [microsoft/fluentui#17406]
#### Describe the feature that you would like added

Unlike some other components, the `List` component uses no `styles` object but only a `className` prop for the list root.

This makes it hard to style the inner component like adding `marginBlockEnd` after every cell for example.

(the `getPageStyle` prop cant help here since it adds style to the page and not a class name - so I cant style the children)

Of course i can use the already existing hardcoded classes like `ms-List-cell` but using a `styles` object will be way more cleaner and safer.

#### What component or utility would this be added to

packages/react/src/components/List/List.tsx

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

N/A

**Comment by gouttierre** [comment]
@daniel-hauser - Thank you for reaching and the feature request. I’ve added this to our backlog for review but it’s low on our priority list for us right now. Therefore we’re likely not going to get to it immediately as we’re currently focused on larger coherence work items and enhancements to our performance. thanks and regards

**Comment by Kitwradr** [comment]
Is there any other way to style the cells? @gouttierre
