### ISSUE TITLE
Not able to give styles for checkbox in disabled state

### ISSUE THREAD

**Issue by venkateshgottimukkula** [microsoft/fluentui#17411]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@venkateshgottimukkula -  Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [ComboBox](https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
