### ISSUE TITLE
textField type="number" maxLength not working

### ISSUE THREAD

**Issue by SvampK** [microsoft/fluentui#17417]
![image](https://user-images.githubusercontent.com/44005569/111189094-0804b380-85b6-11eb-9e4a-1265cf6aec1c.png)
when I have type="number" in textField 
the maxLength is not controll the input
### Environment Information

- **Package version(s)**: (fill this out) "office-ui-fabric-react": "7.59.0",
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

textField type="number" maxLength not working

#### Expected behavior:

can use number type and maxLegth controll the length of input

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@SvampK : Thanks for reaching out. Have you read our documentation for styling the the text field? [ITextFieldStyles](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield#ITextFieldStyles). Perhaps that would help with your issue.
i.e.
```
 <TextField
        label="Controlled TextField limiting length of value to 5"
        value={secondTextFieldValue}
        onChange={onChangeSecondTextFieldValue}
        type="number"        
        styles={narrowTextFieldStyles}
      />
```
If you still run into issues, please provide us a CodePen and we will gladly help. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
