### ISSUE TITLE
Providing IModalStyles margin triggers unexpected animation-like effect when dialog is launched.

### ISSUE THREAD

**Issue by katiearriagam** [microsoft/fluentui#17432]
### Environment Information

- **Package version(s)**: v7 
- **Browser and OS versions**: n/a

### Please provide a reproduction of the bug in a codepen: 
https://codepen.io/katiearriagam/pen/ExNJNGO

Observe the behavior here when opening the dialog multiple times:
![dialog-margin-animation](https://user-images.githubusercontent.com/14140121/111247551-70a75c80-85c5-11eb-91be-a4b062d5f432.gif)

**I only repro this issue when topOffsetFixed is true.**

#### Actual behavior:

Unexpected animation comes up when launching the dialog when margins are provided. Regardless of the position of the dialog, we probably do not want visible repositioning when launching the dialog.

#### Expected behavior:

The dialog should not display any animation when the consumer provides initial styling

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Office Online

**Comment by katiearriagam** [comment]
@khmakoto, @joschect: given that #17345 was rejected - could we consider fixing this instead? It's a different issue, but still preventing us from providing a solution on our own repo.

**Comment by gouttierre** [comment]
@katiearriagam - could you recheck this issue? As I was unable to repro it on my side - and please let us know if you are still experiencing the problem. Thank you
