### ISSUE TITLE
SwatchColorPicker cell moves text below it

### ISSUE THREAD

**Issue by bhavinkotak07** [microsoft/fluentui#17444]
### Environment Information

- **Package version(s)**: (fill this out) latest version
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://developer.microsoft.com/en-us/fluentui#/controls/web/swatchcolorpicker

#### Actual behavior:

On hovering a color cell or any color cell in selected state , moves the text below it.
This can be reproduced in the fluentui official site, in controls for SwatchColorPicker "Usage" section.

#### Expected behavior:

Content below should not be affected.
### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low)
Normal
Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@bhavinkotak07 - Thank you for filing this with us.

@khmakoto -I noticed that when you hover back and forth on the color state - the bottom seems to shift by a few pixels. 
![image](https://user-images.githubusercontent.com/78806055/111986885-cb354100-8b0e-11eb-992c-69dbabb4cd7f.png)
On however the elements shift down.
![image](https://user-images.githubusercontent.com/78806055/111986807-b3f65380-8b0e-11eb-8d08-b1f1262696b7.png)
Can you investigate further? cc @smhigley
