### ISSUE TITLE
Open Fluent Panel using another component

### ISSUE THREAD

**Issue by mpgr04** [microsoft/fluentui#17447]
I am currently working with FluentUI's controls for React and have built in a details list as well as a panel.
As I have seen in the code, there is the following code in the panel:

```typescript
 const [isOpen, { setTrue: openPanel, setFalse: dismissPanel }] = useBoolean(false);

    return (
        <div>
            <DefaultButton text="Open panel" onClick={openPanel} />
            <Panel
                headerText="Sample panel"
                isOpen={isOpen}
                type={PanelType.large}
                onDismiss={dismissPanel}
                closeButtonAriaLabel="Close"
            >
                <ServiceActionBar></ServiceActionBar>
            </Panel>
        </div >
);
```
Now I have the question how to display this panel when I invoke an item in a DetailsList, because the OpenPanel function is assigned to the button, which is returned in this case in the panel component.

Thanks in advance!

**Comment by gouttierre** [comment]
@mpgr04 - Thanks for filing this request, but in-order to assist you further - you’ll need to add a CodePen repro before we can help. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
