### ISSUE TITLE
Dropdown - VoiceOver - focus return to input while navigating into the selected users listbox

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#17446]
Repro steps:
VoiceOver is on
1. Navigate to the URL: https://b50wj.csb.app/
2. select at least 2 users from dropdown 
3. navigate by left arrow key to the selected user

Expected: focus moves to on selected user pill
Actual: focus moves on selected user but then is stolen back to the input

Usually it happens for first time when users are added, later when it started work, then I was not able to reproduce. 

Reproduced with Chrome/VoiceOver
Chrome 88.0.4324.192 + Catalina 10.15.7

**Comment by jurokapsiar** [comment]
I was not able to repro it, might this be related to the old version of Mac OS that you are using?

**Comment by gouttierre** [comment]
@kolaps33 - thanks for submitting this issue. Could you confirm the version you were using at the time?
