### ISSUE TITLE
`IContextualMenuItem`'s `itemProps` has `rootHovered` and `rootExpandedHovered` but it is not working.

### ISSUE THREAD

**Issue by gencer** [microsoft/fluentui#17461]
### Environment Information

- **Package version(s)**: 8.2.1
- **Browser and OS versions**: Edge 89 on Windows 10 20H2

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/gencer-the-typescripter/pen/dyOEPpW

CodePen based on v7 but its applicable on v8 too. (Same behavior)

I have a ContextualMenu within a button. I want to change each items (button or root in this case) default background and hover background when user hover it. It seems FluentUI is by default has its own background (white) hover and pressed backgrounds. Either I am trying to do this in wrong section or it just doesn't work out as expected.

#### Actual behavior:

No custom set hover background on items:

![actual](https://user-images.githubusercontent.com/1711576/111407293-ad1daa00-86e4-11eb-8cab-6db91cd61701.gif)

#### Expected behavior:

When I hover on a ContextualMenuItem, background should change according to my config: (neither root nor rootHovered/rootExpandedHovered changes in this case)

![expected](https://user-images.githubusercontent.com/1711576/111407303-af800400-86e4-11eb-999b-092ae2e62b5d.gif)

Am I trying to configure this behavior in a wrong way?

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No.

Requested priority: (Blocking, High, Normal, Low) High.

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@gencer  - thank you for reaching out. I tried to have a look at your issue but your CodePen does not seem to be working. Can you review your [CodePen ](https://codepen.io/gencer-the-typescripter/pen/dyOEPpW) so it functions as you stated in the issue. Thank you in advance.

**Comment by gencer** [comment]
> @gencer - thank you for reaching out. I tried to have a look at your issue but your CodePen does not seem to be working. Can you review your [CodePen ](https://codepen.io/gencer-the-typescripter/pen/dyOEPpW) so it functions as you stated in the issue. Thank you in advance.

Hi @gouttierre. Pen is Fixed. Please have a look (same link): https://codepen.io/gencer-the-typescripter/pen/dyOEPpW
