### ISSUE TITLE
Basic List

### ISSUE THREAD

**Issue by NewReactUser28** [microsoft/fluentui#17466]
### Environment Information

- **Package version(s)**: 7.154.0
- **Browser and OS versions**: Microsoft Edge

### Describe the issue:

I am trying to using a Basic List control for displaying items in a dropdown. And I am facing issues with accessing the list items through TAB.
Though the items have tabIndex enabled, always the default selected item remains as the only focussable element. The u selected items are by default rendered with TabIndex value as -1.
This is used to work fine until a couple of weeks ago and has now stopped working.

Any insights on why this is occurring?

**Comment by JustSlone** [comment]
Hi @NewReactUser28 can you provide a codepen/codesandbox repro of the issue you're seeing?
