### ISSUE TITLE
Northstar: multiple instances are causing collisions on the same page

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#17463]
### Environment Information

- **Package version(s)**: `@fluentui/react-northstar`
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug

https://github.com/layershifter/fluentui-injection

- Clone the repo
- `yarn`
- `yarn build`
- `yarn serve` (open a served web-page)

#### Actual behavior:

![A screenshot with wrong styles produced by multiple instances on N*](https://user-images.githubusercontent.com/14183168/111460431-41efca00-871c-11eb-8b55-c1115748288f.png)

#### Expected behavior:

![A screenshot of properly applied styles with a single instance](https://user-images.githubusercontent.com/14183168/111460607-76638600-871c-11eb-958b-1e9b224faddf.png)

Styles should be applied properly.

### Details

The demo application contains three apps:

- `app-a` & `app-b` are small apps that contain few Northstar components
- `main-app` is a host app without N\*

`app-a` & `app-b` are exposing `render()` functions that accept HTML elements where React tree will be mounted. Components will be rendered in the same HTML tree (if iframes will be used - there will be no collisions). Both `app-a` and `app-b` contain Fluent UI N\* in their bundles.

_What happens?_ In N\* we have checks that should prevent such issues:

https://github.com/microsoft/fluentui/blob/4503e2d3f62f785363b5937bfb5ce278c27ab0fe/packages/fluentui/react-northstar/src/utils/mergeProviderContexts.ts#L13-L15

But these checks does not work in this case as each app bundle will contain an own Fluent instance thus `Provider` will create an own renderer for each app and this causes collisions.

#### Lifecycle

- `app-a` is mounted and renders: classes by Fela are non-deterministic, `.c { color: red }` was generated and inserted to based on order of components
- `app-b` is mounted and renders: classes by Fela are non-deterministic, `.c { display: grid }` was generated and inserted to based on order of components
- `.c` has now duplicate definitions in DOM 💣

### Possible solutions

- Make `registeredRenderers` a global. Can cause issues related to different versions of Fluent used on the page:

```diff
-const registeredRenderers = new WeakMap<Document | typeof defaultDocument, Renderer>();
+window.registeredRenderers = new WeakMap<Document | typeof defaultDocument, Renderer>();
```

- Allow to configure `className`s prefixes like in Fela. Each app in this case will have different classes that will not collide. Requires configuration on client side, is more harmful for performance and resources.

```tsx
<RendererContext.Provider value={createFelaRenderer({ selectorPrefix: 'appA-' })} />
```

- Disallow multiple versions of Fluent on a page and throw like React does

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes
Requested priority: Normal/High
Products/sites affected: PowerApps

**Comment by layershifter** [comment]
Some issues that could be useful:

https://github.com/styled-components/styled-components/pull/1102
https://github.com/styled-components/styled-components/issues/1011
https://github.com/styled-components/styled-components/pull/1632

**Comment by mgwojciech** [comment]
I have the same problem. Is there some work-around we could apply

**Comment by mpowney** [comment]
In the [docs quick-start page](https://fluentsite.z22.web.core.windows.net/0.56.0/quick-start), there's a note about React Context is used to provide the style renderer.

> Fluent UI components are styled using CSS in JS. This technique requires a style renderer to render JavaScript objects to CSS. React Context  is used to provide the style renderer and theme to components.

Without knowing a lot about React Context and its usage, is it possible to 'get' the context from one solution, and pass it to another solution?

**Comment by layershifter** [comment]
> I have the same problem. Is there some work-around we could apply

Yes, can you please try to use Emotion renderer? As it generates deterministic classes even if they are inserted twice they will not collide.

```tsx
import { RendererContext, Provider } from "@fluentui/react-northstar";
import { createEmotionRenderer } from "@fluentui/react-northstar-emotion-renderer";

function App() {
  return (
    <RendererContext.Provider value={createEmotionRenderer()}>
      <Provider>
        {/* your components */}
        <div />
      </Provider>
    </RendererContext.Provider>
  );
}
```

**Comment by mgwojciech** [comment]
@layershifter - thank You so much.
I'm on 0.51.4 and I had to use 
<RendererContext.Provider value={() => createEmotionRenderer(document)}> but works as expected

**Comment by layershifter** [comment]
> @layershifter - thank You so much.
> I'm on 0.51.4 and I had to use
> <RendererContext.Provider value={() => createEmotionRenderer(document)}> but works as expected

@mgwojciech On 0.51.4 you can use just `<RendererContext.Provider value={createEmotionRenderer}>` 😉

**Comment by mgwojciech** [comment]
Good point :D
