### ISSUE TITLE
compareDatePart returning incorrect amount of days/ unclear value representation

### ISSUE THREAD

**Issue by BrianDeJesus** [microsoft/fluentui#17478]
### Environment Information

- **Package version(s)**: (8.1.6)

### Function test:

```javascript 
import { compareDatePart } from '@fluentui/date-time-utilities';

const start = "2021-03-01T07:00:00Z";
test('get days difference 1', () => {
	
	const end =  "2021-04-30T07:00:00Z";

	const comparison1 = compareDatePart(new Date(end), new Date(start));
	expect(comparison1).toBe(60);

});

test('get days difference 2', () => {

	const end2 = "2021-05-01T07:00:00Z";

	const comparison2 = compareDatePart(new Date(end2), new Date(start));

	expect(comparison2).toBe(61);
});

```

The tests both fail even though they shouldn't, assuming the number returned is difference in days.

#### Actual behavior:

compareDatePart does not return the correct amount of days in the difference between the two dates. If the two dates are in a different month, the return value will be around 1 - 4 days off. I know the [documentation](https://docs.microsoft.com/en-us/javascript/api/date-time-utilities?view=office-ui-fabric-react-latest#compareDatePart_date1__date2_) does not say it returns the amount of days but I feel like many people will assume this.

#### Expected behavior:

compareDatePart would helpfully return the exact amount of days between two dates OR this [documentation](https://docs.microsoft.com/en-us/javascript/api/date-time-utilities?view=office-ui-fabric-react-latest#compareDatePart_date1__date2_) could be worded better to clarify what the number it returns does not represent or whether or not it's talking about such as the amount of groups of 24 hours between, weekdays, or months etc.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: Normal n

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@BrianDeJesus - thank you for submitting this issue and I see you are will do submit a PR - that is great news!
-  Could you share it with us? We would appreciate the contribution. Thanks in advance.
