### ISSUE TITLE
Combobox known issues

### ISSUE THREAD

**Issue by joschect** [microsoft/fluentui#17474]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
See #17301 for original version of this problem
[ ] Deleting the first character in a combobox moves the cursor to the end.
[ ] Basic Combobox is unable to begin typing even though full option appears to be selected after choice is initially selected
### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
Reopening since I think both of these issues are still present in the [PR deploy demo](https://fluentuipr.z22.web.core.windows.net/pull/19008/public-docsite-resources/demo/index.html#/examples/ComboBox) of #19008.
