### ISSUE TITLE
Fluent UI E2E tests randomly fail

### ISSUE THREAD

**Issue by vejrj** [microsoft/fluentui#17484]
### Please provide a reproduction of the bug in a codepen:
Cypress E2E randomly fail. A problem was observed only in Dialog tests.

<img width="860" alt="Screenshot 2021-03-18 at 13 08 53" src="https://user-images.githubusercontent.com/77059398/111624071-80a08580-87eb-11eb-8939-baf4f685d2a0.png">

The problem occurs randomly in the pipeline or during locally run tests.

Possible way how to solve it: 
- create a separate PR:
- disable all steps except E2E
- enable screenshots and videos in this branch, store artifacts somewhere
- discover a problem in this PR and fix it, remove other changes
- (optional) discuss should we enable screenshots and videos permanently

#### Actual behavior:

E2E tests are randomly failing.

#### Expected behavior:

E2E tests doesn't fail + Dialog tests are enabled again

**Comment by gouttierre** [comment]
@vejrj - Thanks for reaching out and your suggestions posted. If you have an idea how to remedy this with a PR - we would love to see it.

@khmakoto - Would you be able to verify why the tests are failing for Dialog Comp?
