### ISSUE TITLE
Fluent Contextual Menu with multiselect dropdown is hiding when the other event is triggering.

### ISSUE THREAD

**Issue by surya1227** [microsoft/fluentui#17481]
Hi Team,

I am using fluent contextual menu with fluent multi select drop downs (Filter component) when i am trying select checkbox at the same time triggering a new event for **Ag-grid expand & collapse** that time fluent multi select drop downs are automatically closing so is there any way to so the dropdown popup until user trying to closing the same. Please do the needfull.
![Menu](https://user-images.githubusercontent.com/7038360/111586859-767c8800-87e7-11eb-8329-57ecc2bd6d6f.JPG)

Thanks in advance.

**Comment by gouttierre** [comment]
@surya1227 - Thanks for filing this, but I am battling to follow your instructions into what your are trying to achieve, could you add a CodePen repro so we can better help you out? You can start from one of the [ContextualMenu ](https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
