### ISSUE TITLE
how to do something like bootstrap responsive layout

### ISSUE THREAD

**Issue by quantrpeter** [microsoft/fluentui#17498]
Hi
  how to do something like bootstrap responsive layout? i am using fluentui in ms teams dev.
Thanks
Peter

**Comment by gouttierre** [comment]
@quantrpeter - Thanks for filing this item with us.  Have you tried looking at the [Flex and Grid ](https://fluentsite.z22.web.core.windows.net/0.52.2/layout) components?
cc @kolaps33   - could you be of an assistance? Thanks
