### ISSUE TITLE
Missing Slider Animation

### ISSUE THREAD

**Issue by edsulaiman** [microsoft/fluentui#17501]
### Environment Information

- **Package version(s)**: @fluentui/react 8.5.0
- **Browser and OS versions**: Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)

#### Actual behavior:

Slider not showing any animation

#### Expected behavior:

Slider will show smooth animation like in example [Fluent UI Web](https://developer.microsoft.com/en-us/fluentui#/controls/web/slider)

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

**Comment by gouttierre** [comment]
@edsulaiman - thanks for the feedback. I had a look at 8.5.0 and 8.5.1 - however, I was unable to repro your logged issue where the animation is not being done smoothly. 
Could you provide more information or add a CodePen repro? You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen. Thanks

**Comment by edsulaiman** [comment]
@gouttierre - sorry I can't make a codepen repro, because of the difference in `fabric` and `fluent` packages, which in my opinion there is a bug in the fluent package
.
This is the screenshot I can provide
### office-ui-fabric-react slider
![fabric-slider](https://user-images.githubusercontent.com/52323183/112712134-09ac7080-8f00-11eb-960e-7d703e95f304.gif)

### @fluentui/react slider
![fluent-slider](https://user-images.githubusercontent.com/52323183/112712137-0c0eca80-8f00-11eb-9e70-4b47017c6878.gif)
