### ISSUE TITLE
Facepile: When using TooltipHost, the default tooltip also renders causing 2 tooltips to be displayed for single coin

### ISSUE THREAD

**Issue by prmutha** [microsoft/fluentui#17503]
### Environment Information

- **Package version(s)**: ^7.162.1
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/facepile-tooltip-onfocus-dhkee?file=/src/App.tsx

#### Actual behavior:

2 tooltips are rendered

#### Expected behavior:

If TooltipHost is present, then do not render default tooltip - single tooltip is rendered

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
I tried to enlist, but faced issues, so No.

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
Fluid integration in Teams

**Comment by gouttierre** [comment]
@prmutha - thank you for filing this, I do see the repro as stated in the issue. I read you tried to enlist to submit a PR?  What was the issue, if I may ask? Do you have a proposed fix for the issue?
 
@tomi-msft - could you have a look at this one, and see if it is a regression or a if the behavior is an issue? Thank you

**Comment by tomi-msft** [comment]
Hi @prmutha, could you share some more information about the specific use case where this is an issue? When will you need to specifically render a TooltipHost in the FacePile component, when it has a default ToolTip when rendered?

**Comment by tomi-msft** [comment]
Reopening to address issue after author feedback
