### ISSUE TITLE
DatePicker selectedDate does not update Input display

### ISSUE THREAD

**Issue by brycepolly** [microsoft/fluentui#17505]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.53.0
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/fluent-ui-example-forked-y59my?file=/example.js

#### Actual behavior:

selectedDate property does not update the displayed date on the input box of the DatePicker control

#### Expected behavior:

Controlling the value of selectedDate should update the displayed value in the input box.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (High)

Products/sites affected: (Polly on Teams)

**Comment by gouttierre** [comment]
@brycepolly - I did notice the behavior reported in the issue with the repro.

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue with the component?

**Comment by jurokapsiar** [comment]
I was able to repro it, we will take a look
