### ISSUE TITLE
Problem in DetailList with nested Object 

### ISSUE THREAD

**Issue by sandeepsbhat46** [microsoft/fluentui#17512]
Hi Team,

### Describe the issue:

Using DetailList for displaying nested JSON data I tried, with reference of FiledName as well as onRender method but, here I am  not getting accepted output. 

 Sample data and output mentioned below:

{
  "message": "Hello world",
  "success": "true",
  "itemDetails": [
    {
      "item": "item115",
      "stockDetails": [
        {
          "batchNo": null,
          "serialNo": null,
          "lotNo": null,
          "openingStock": 10,
          "saleQuantity": 6,
          "purchaseQuantity": 7,
          "saleReturnQuantity": 9,
          "purchaseReturnQuantity": 0,
          "supplyAdjustmentQuantity": 0,
          "multiples": null
        },
        {
          "batchNo": "GP-25",
          "serialNo": null,
          "lotNo": null,
          "openingStock": 0,
          "saleQuantity": 20,
          "purchaseQuantity": 32,
          "saleReturnQuantity": 88,
          "purchaseReturnQuantity": 0,
          "supplyAdjustmentQuantity": 0,
          "multiples": null
        }
      ]
    }
  ]
}

I am not able find any solution for display the data as user request, for sample requested output mentioned below.

[](url)
![image](https://user-images.githubusercontent.com/75310190/111976661-dea0d600-8b27-11eb-9f20-28807f226e45.png)
Expected Output:

ITEM      | Batch-NO | Opening Stock | Sale Quantity | saleReturnQuantity
item115 | null           | 10                     | 6                    | 9
item115 | GP-25       | 0                       | 20                  | 88

#### Actual behavior:

ITEM      | Batch-NO | Opening Stock | Sale Quantity | saleReturnQuantity
item115 | null           | 10                     | 6                    | 9
               GP-25          0                        20                    88

Above output will come in single row but, we need to display the 2nd data in separate row like below. but, here we can display the multiple child data in single row.
 
#### Expected behavior:
1)Parent value should be display with child 
2) Each time data should be display in separate row not in single row .

ITEM      | Batch-NO | Opening Stock | Sale Quantity | saleReturnQuantity
item115 | null           | 10                     | 6                    | 9
item115 | GP-25       | 0                       | 20                  | 88

Can you please show the demo example for above issue.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) - No

Requested priority: (Blocking, High, Normal, Low) - High

Products/sites affected: (if applicable) - Yes

Please look into the above issue.

Thanks & Reagards,
Sandeep

**Comment by sandeepsbhat46** [comment]
Accepted Output:

ITEM | Batch-NO | Opening Stock | Sale Quantity | saleReturnQuantity
-- | -- | -- | -- | --
item115 | null | 10 | 6 | 9
item115 | GP-25 | 0 | 20 | 88



Actual Output:
![image](https://user-images.githubusercontent.com/75310190/111980061-cc289b80-8b2b-11eb-840f-06f2e6fc64d4.png)

**Comment by sandeepsbhat46** [comment]
Any Update?

**Comment by gouttierre** [comment]
@sandeepsbhat46 - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the[ Details List](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
