### ISSUE TITLE
Dynamically rendered textField controls don't hold the values correctly

### ISSUE THREAD

**Issue by kkazala** [microsoft/fluentui#17518]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@7

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/kkazala/pen/qBRBvrP

#### Actual behavior:
Dropdown selection generates a field in the form. When the option is unselected, the field is removed 
Steps: 
1. Select "Apple" and "Banana" : two textfields are rendered correctly
2. Type "apple" in the "Apple" field, and "banana" in the "Banana" field
3. Unselect "Apple" 
4. Only "Banana" text field is displayed now, but with value "apple"

#### Expected behavior:
1. Select "Apple" and "Banana" : two textfields are rendered correctly
2. Type "apple" in the "Apple" field, and "banana" in the "Banana" field
3. Unselect "Apple" 
4. "Banana" text field has correct value "banana"

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by gouttierre** [comment]
@kkazala - thank you for the feedback - I see the repro as stated in the issue.
![image](https://user-images.githubusercontent.com/78806055/112482027-eb1b6d80-8d77-11eb-9117-6e1249784ae0.png)

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue with the DropDown?
