### ISSUE TITLE
How to open dialog in another control?

### ISSUE THREAD

**Issue by leonardjohn** [microsoft/fluentui#17511]
Dear guys,
just want to know how to open custom dialog in another component control?
e.g.:
ParentComponent.tsx:
import CustomDialog from "CustomDialog"
export class ParentComponent {
...
public render() {
return (
<Button onClick={()=>{this.showDialog()}}
);
}
public showDialog() {
**//How to show/hide dialog here?**
}
...
}

CustomDialog.tsx:
import Dialog from "@fluentui/react-northstar"

export class CustomDialog {
public async componentWillMount() {
  this.setState({open:false})
}
public setOpen() {
 if (!this.state.open)
  this.setState({open:true});
 else
  this.setState({open:false});
}
public render() {
return (
<Dialog open={this.state.open} .../>
);
}
}
export default CustomDialog

thanks in advance

**Comment by gouttierre** [comment]
@leonardjohn - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by leonardjohn** [comment]
@gouttierre many thanks for your update.
please find the source code on CodeSandbox here:[https://codesandbox.io/s/stoic-nash-df2e8](https://codesandbox.io/s/stoic-nash-df2e8)
two problems here:
1. how to open dialog "CommonDialog" when i click "Open Dialog" button in App.js?
2. How can I use "Form" tag to generate dialog content, instead of <div>?
i tried to find the doc here:https://fluentsite.z22.web.core.windows.net/0.51.7/components/form/definition but it cannot meet my  requirement 
req: how to render an input and a dropdown inside an readonly input?

thanks in advance.

**Comment by leonardjohn** [comment]
any update?
