### ISSUE TITLE
Add accessibility header tag option for Pivots

### ISSUE THREAD

**Issue by wrathofdon** [microsoft/fluentui#17519]
#### Describe the feature that you would like added

https://accessibilityinsights.io/en/downloads/

Accessibility insights requires that all pages have a header using header tags.  When you select a pivot, the selected pivot is underlined, but there is no header tag.  In order to meet accessibility requirements, the header must be displayed twice:  Once on the pivot tab, and a second time separately with the header tag.

It would be nice if users had the option to tell the code to simply wrap header tags around the current selected pivot, so that the accessibility tab would be able to read it as a header if the user chooses.

#### What component or utility would this be added to

https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot

#### Have you discussed this feature with our team, and if so, who

My team has discussed manually adding additional headers for each pivot in order to meet accessibility requirements, but I wanted to see if there could be a more elegant solution.

**Comment by gouttierre** [comment]
@wrathofdon - thank for the suggestion. I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
