### ISSUE TITLE
Commandbar menu does not hide when clicking on iframe

### ISSUE THREAD

**Issue by mbedeker** [microsoft/fluentui#17510]
When a menu item of an Commandbar is expanded, clicking anywhere else on the page will hide that sub menu. This behavior is not present when the user clicks on an iframe on the page.

### Environment Information

- **Package version(s)**: 8.3.0
- **Browser and OS versions**: Chrome and Firefox (both latest version)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/mbedeker/pen/NWdKrNP

I used the Commandbar example from the fluent UI documentation page (https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar), and added an iframe to the output. the "New" menu expands the "Email/Calender" submenu. clicking on the iframe does not hide the submenu, clicking outside of the iframe hides the submenu.

#### Actual behavior:

Submenu stays on the page

#### Expected behavior:

Submenu should also be hidden

**Comment by mbedeker** [comment]
Any update on this one?

**Comment by gouttierre** [comment]
@mbedeker - thank you for filing this item. I do see the repro as stated in your issue.

@tomi-msft - Would you be able to confirm if this is a regression, or if this behavior is an issue when the user clicks outside the iframe?

**Comment by mbedeker** [comment]
any update on this?
