### ISSUE TITLE
Event for outer clicks of the FocusTrapZone

### ISSUE THREAD

**Issue by hohenp** [microsoft/fluentui#17529]
#### Describe the feature that you would like added

Would be nice to have an event when someone clicks outside of a FocusTrapZone.
In the moment, when I am using the FocusTrapZone sometimes the user clicks outside and wonders that the clicks dont work.
If I would have an event aka "onOuterClick" (as the Panel has) I could trigger a UI message and explain why that happens...

#### What component or utility would this be added to

FocusTrapZone

#### Have you discussed this feature with our team, and if so, who

no, not yet.

#### Additional context/screenshots

none

**Comment by gouttierre** [comment]
@hohenp - thanks for the suggestion, have you an idea on the implementation? If so, we would appreciate if you could share it with us. 
In the meantime, I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.
