### ISSUE TITLE
Teaching Bubble actions and footer content don't reflow gracefully and aren't configurable

### ISSUE THREAD

**Issue by hoovercj** [microsoft/fluentui#17530]
### Please provide a reproduction of the bug in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/8.5.1/#/examples/teachingbubble

#### Actual behavior:

![image](https://user-images.githubusercontent.com/2957173/112203667-133d8c00-8c13-11eb-9cd7-85dcba12640b.png)

#### Expected behavior:

There are a few expectations here:

1) If the buttons reflow, they reflow such that they are either left aligned with each other (notice the padding to the left of the second button) or right aligned
2) It would be good if the component allowed applying styles to these "stack items" but there are no style slots available. This means that rather than supplying class names to apply to those items or applying CSS in JS, we have to reference `ms-Stack` and `ms-StackItem` in our styles which we would prefer not to do. Below are a few screenshots of some work-in-progress reflow behavior that we have added to make the bottom more responsive. We understand that this behavior may not be what the fluent team wants out of the box which is why we are asking to be able to provide classes or style props.

* When the footer content is too long, reflow the buttons below it
![image](https://user-images.githubusercontent.com/2957173/112204315-cefebb80-8c13-11eb-90a6-99fb199d1088.png)

* When the buttons also don't fit side-by-side, stack them vertically and left-aligned
![image](https://user-images.githubusercontent.com/2957173/112204531-11c09380-8c14-11eb-8a56-e5d5a1905c53.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes if some redlines/UX guidance is provided

Requested priority: (Blocking, High, Normal, Low) Normal

**Comment by gouttierre** [comment]
@hoovercj - Thanks for filing this item with us and sharing your findings. I see you are willing to contribute to this issue? That is great to see - let me try get you UX guidance to require. 

@TristanWatanabe / @ecraig12345 - Would either of you be able to provide the redlines/UX guidance?
