### ISSUE TITLE
Making multiline TextField occupy all parent's vertical space.

### ISSUE THREAD

**Issue by jurijsk** [microsoft/fluentui#17531]
New to FluentUI but not sure if it is a bug or not, it looks like one.

I'm trying to make multiline input field to occupy 100% of parents space `<TextField styles={styles} multiline borderless={true} resizable={false}></TextField>`.

If is set `styles` to:

```
const styles: IStyleFunctionOrObject<ITextFieldStyleProps, ITextFieldStyles> = {
  root: {
	  height: '100%'
  },
};
```

it will change the height of wrapping `div` but not the size of the underlying `textarea. The workaround is add 

```
  field: {
	  height: '100%'
  }
```

as well, but I wonder if it should behave this day by default? Thank you!

**Comment by ecraig12345** [comment]
Thanks for filing this, and sorry nobody got to it sooner. The current default height of the multiline text field was specified by our designers, so unfortunately this isn't something we intend to change.
