### ISSUE TITLE
azure-themes high contrast dark default background is incorrect color

### ISSUE THREAD

**Issue by DavidParks8** [microsoft/fluentui#17535]
PLEASE NOTE:

Do not link to, screenshot or reference a Microsoft product in this description. -> OK, I'll try my best 

### Environment Information

- **Package version(s)**: (7 & 8)

### Describe the issue:

high contrast dark default background color should be rgb(0,0,0).

#### Actual behavior:

high contrast dark background color is defaulting to rgba(0,0,0,0) which is rendered lighter and does not produce as much contrast. Contact me (daparks) on teams for a repro.

### Documentation describing expected behavior

Not possible without referencing a product.

**Comment by gouttierre** [comment]
@DavidParks8 - thank you for filing this item. 

@tomi-msft  - Can you contact (daparks) on teams for a repro for the high contrast? Thank you
