### ISSUE TITLE
Date Picker has bug when show close button is enabled then closing the dialog causes issue, also when added the IDatePickerStrings the Picker fails to open

### ISSUE THREAD

**Issue by AshwinKheta** [microsoft/fluentui#17546]
### Environment Information

- **Package version(s)**: 
"@microsoft/sp-core-library": "1.11.0",
"@microsoft/sp-lodash-subset": "1.11.0",
"@microsoft/sp-office-ui-fabric-core": "1.11.0",
"@microsoft/sp-property-pane": "1.11.0",
"@microsoft/sp-webpart-base": "1.11.0",
"@fluentui/react": "8.1.7",
"@pnp/sp": "1.3.11",
"@pnp/spfx-controls-react": "2.5.0",
"@pnp/spfx-property-controls": "2.5.0-beta.f943b70",
"office-ui-fabric-react": "6.214.0",
"react": "16.8.5",
"react-dom": "16.8.5",
"@microsoft/rush-stack-compiler-3.3": "0.3.5",
"@microsoft/sp-build-web": "1.11.0",
"@microsoft/sp-module-interfaces": "1.11.0",
"@microsoft/sp-tslint-rules": "1.11.0",
"@microsoft/sp-webpart-workbench": "1.11.0",
"@pnp/common": "1.3.11",
"@pnp/logging": "1.3.11",
"@pnp/odata": "1.3.11",
"@pnp/sp-clientsvc": "1.3.11",
"@pnp/sp-taxonomy": "1.3.11",
"@types/chai": "3.4.34",
"@types/es6-promise": "0.0.33",
"@types/mocha": "2.2.38",
"@types/react": "16.8.8",
"@types/react-dom": "16.8.3",
"@types/webpack-env": "1.13.1",
"ajv": "^6.9.1",
"gulp": "~3.9.1"
- **Browser and OS versions**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

### Please provide a reproduction of the bug in a codepen:

Simply used Date Picker on an SPFx Form the field was required so could not show the error message when kept required but no date was selected.
Also enabled Close button on the Date Picker Dialog but this also caused to fail the date picker.

#### Actual behavior:

Complete Form gets blank and some site navigation settings is opened.

#### Expected behavior:

Should work when close button when clicked but gets fails.

### Priorities and help requested:

Let us know the process of adding date picker with error messages and required field not filled message and how to focus on to date picker if it has error.

**Comment by AshwinKheta** [comment]
`<DatePicker
    className={styles.fieldStyle}
    // componentRef={(input) => this.fieldProDT = input}
    isRequired={true}
    strings={DayPickerStrings}
    label="Date of Program"
    minDate={new Date()}
    placeholder="Select a date"
    onSelectDate={((dt) => { dt ? this.setState({ F03ProDT: dt }) : console.log("invalid date selection"); }).bind(this)}
    // showCloseButton={true}
    // strings={{ isRequiredErrorMessage: "This field is Required", invalidInputErrorMessage: this.state.E03ProDT, } as IDatePickerStrings}
    value={this.state.F03ProDT}
/>`

**Comment by AshwinKheta** [comment]
<DatePicker
              className={styles.fieldStyle}
              // componentRef={(input) => this.fieldProDT = input}
              isRequired={true}
              strings={DayPickerStrings}
              label="Date of Program"
              minDate={new Date()}
              placeholder="Select a date"
              onSelectDate={((dt) => { dt ? this.setState({ F03ProDT: dt }) : console.log("invalid date selection"); }).bind(this)}
              // showCloseButton={true}
              // strings={{ isRequiredErrorMessage: "This field is Required", invalidInputErrorMessage: this.state.E03ProDT, } as IDatePickerStrings}
              value={this.state.F03ProDT}
            />

**Comment by AshwinKheta** [comment]
The field value is to be stored in a state (here F03ProDT) hence added the "value" and "onSelectDate" properties to the date picker this is causing the error to be shown on the new form.
can the issue be resolved with only validating when Date Picker loses focus and not before.

**Comment by ecraig12345** [comment]
Thanks for reporting this, but to investigate this issue we'll need an isolated repro. You can start by clicking "Export to CodePen" on one of the [DatePicker examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker), and edit it to be similar to your scenario.
