### ISSUE TITLE
[web-components] Add appearance behaviors for inputs and form controls

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fluentui#17558]
We recently added an appearance behavior to conditionally load stylesheets for various button appearances: https://github.com/microsoft/fluentui/pull/17516/files. There are several other controls which also have appearances where this behavior should be included as well.

This issue exists to track the addition of appearance behaviors for:
- text field
- text area
- number field
- select
- combobox

**Comment by Jassi10000** [comment]
Is this related to form valdations  ?

**Comment by chrisdholt** [comment]
> Is this related to form valdations ?

Not yet! This is in regards to the existing visual appearances (outline, filled) and improved performance. Behaviors allow us to include or exclude styles conditionally. In this work, we're conditionally including and attaching an adopted stylesheet when a given appearance exists. This way, if you don't use the "filled" appearance, it's not rendered into the document as an adopted stylesheet.

**Comment by Jassi10000** [comment]
Ohh , that's something interesting to know, thanks for info
