### ISSUE TITLE
Charting: Callout is not dismissed on pressing Esc

### ISSUE THREAD

**Issue by mbest** [microsoft/fluentui#17551]
### Environment Information

- **Package version(s)**: 4.13.7
- **Browser and OS versions**: Chrome, Windows 10

#### Actual behavior:

When focusing the chart through keyboard, Escape isn't dismissing the tooltips on charting.
Issue reproducing in most charts (except Line and Donut).

#### Expected behavior:

Escape key should close the tooltip

**Comment by mbest** [comment]
This was previously opened as #16422, but that bug was closed without fixing the problem for all charts. 
@Raghurk @jameelakowsar

**Comment by gouttierre** [comment]
@mbest - thanks for filing this item. It should be corrected in the latest version. Please, do try it out and let us know.
