### ISSUE TITLE
Modal announce the button text twice when use voiceOver

### ISSUE THREAD

**Issue by MSYuanMei** [microsoft/fluentui#17560]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@7
- **Browser and OS versions**: Edge/Chrome MacOs
### Describe the issue:
It announces the buttons inside the modal twice when using voiceOver on Mac
<img width="1221" alt="Screen Shot 2021-03-24 at 1 27 33 PM" src="https://user-images.githubusercontent.com/42685233/112378998-db7f2480-8ca4-11eb-8ca6-4e708c65ef16.png">

#### Actual behavior:

It announces the buttons inside the modal twice when using voiceOver on Mac

#### Expected behavior:

It should only announce the buttons once

### Documentation describing the expected behavior

Here is the repo, it announces "Close popup modal" twice
https://codepen.io/ymei/pen/yLgYONo

**Comment by gouttierre** [comment]
@MSYuanMei - thanks for filing this item. 

@tomi-msft - Would you be able to confirm if this is a regression, or if this behavior is an issue using voiceOver on Mac? I tested it with Windows and Chrome and narrator to see if it repro across the platforms and it seemed okay.  cc @smhigley
