### ISSUE TITLE
dialog bug

### ISSUE THREAD

**Issue by oo-long** [microsoft/fluentui#17567]
### Environment Information

- **Package version(s)**: (@fluentui/react 8.6.0)
- **Browser and OS versions**: (Chrome version  89.0.4389.90)

#### Actual behavior:

When draggable property is on, dragging out the screen, the mouseup event respense failure.
#### Expected behavior:

mouseup event respense well.
### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: ( Low)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@oo-long - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [Dialog ](https://fabricweb.z5.web.core.windows.net/oufr/8.9.4/#/examples/dialog) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
