### ISSUE TITLE
TooltipHost content read twice when using narrator

### ISSUE THREAD

**Issue by RongqiZ** [microsoft/fluentui#17569]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

### Describe the issue:

reproduce steps:
Using narrator scan-off mode, focus on one button.
Using the keyboard to change focus position quickly, (if you do this very fast, there is no tooltip that occurs).
Turn on scan mode, use arrow keys to change the narrator read position.
You will find you can navigate to the placehoder item.

For the tooltip host, there is a default delay of 300ms. So after the button been focused, it will immediately render an aria placeholder (as the image shows) there is a timer to show tooltip and hide button aria placeholder. But after the focus moves out of the button very soon, the timer will be canceled. So the tooltip will not show and it will not hide the aria placeholder.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/AlmondShell/pen/WNRQdje

#### Actual behavior:

aria place holder is not removed 

#### Expected behavior:

aria place holder should removed, so that it will not been read by narrator

**Comment by gouttierre** [comment]
@RongqiZ - thank you for the feedback and repro steps. I also noticed different behavior from the browsers. In Edge I noticed the focus was correctly placed when navigating. 
![image](https://user-images.githubusercontent.com/78806055/112492444-8d8c1e80-8d81-11eb-90bd-5cd1344d3cb1.png)
While in Chrome the focus is off the actual component.
![image](https://user-images.githubusercontent.com/78806055/112492331-764d3100-8d81-11eb-9d86-f432022a7fc8.png)

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley
