### ISSUE TITLE
FluentUI React List doesn't seem to support selection, even though documentation mentions it

### ISSUE THREAD

**Issue by harlankoehn** [microsoft/fluentui#17575]
#### Describe the feature that you would like added
It would be nice if the FluentUI Basic List component supported selection. The documentation states: "List items are composed of selection, icon, and name columns at minimum." But the rest of the documentation and examples do not show how to use selection.

#### What component or utility would this be added to
FluentUI List (called Basic List in documentation)

#### Have you discussed this feature with our team, and if so, who
No

**Comment by gouttierre** [comment]
@harlankoehn - thanks for reaching out. Have you taken a look at our documentation for the basic [DetailsList](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic)? You can start from one of the examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by harlankoehn** [comment]
Yes, I'm fully aware of the DetailsList. My issue still stands. How come the Basic List implies selection but doesn't actually support it? Also wondering why I had to wait two months for an unhelpful response like this.

**Comment by strwase** [comment]
I'm very much wondering the same this as @harlankoehn. It is specifically mentioned in the documentation, but there does not seem to be any support of actual selection. Northstar on the other hand does have a selectable list component.
