### ISSUE TITLE
Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by davvit** [microsoft/fluentui#17588]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)
![image](https://user-images.githubusercontent.com/4433698/112668032-f8922f80-8e2b-11eb-873e-8c31e6aa4534.png)

### Please provide a reproduction of the bug in a codepen:
https://stackblitz.com/edit/react-7ju8uf?file=src/App.js

#### Actual behavior:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
The above error occurred in the <Stack> component:

at Stack (https://react-7ju8uf.stackblitz.io/turbo_modules/****@uifabric/foundation@7.9.26/lib-commonjs/createComponent.js:33:70)****
at div
at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```
![image](https://user-images.githubusercontent.com/4433698/112669108-4ce9df00-8e2d-11eb-9a85-898b51c8d12b.png)

#### Expected behavior:

no errors compiling...

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
Hi @davvit, I think it's because you have both the `office-ui-fabric-react` and `@fluentui/react` dependencies. If you restrict to only use the `@fluentui/react` dependency as in [here](https://stackblitz.com/edit/react-i4j6ku?file=src/App.js) you can see that it works correctly.

![image](https://user-images.githubusercontent.com/7798177/115095082-c036bc00-9ed4-11eb-8b50-4d039a2f4f1f.png)
