### ISSUE TITLE
SearchBox onChange handler called twice

### ISSUE THREAD

**Issue by FeodorFitsner** [microsoft/fluentui#17587]
### Environment Information

- **Package version(s)**: @fluentui/react@8.6.1
- **Browser and OS versions**: Chromium Edge

#### Actual behavior:

`onChange` handler is called twice on every input box change.

#### Expected behavior:

`onChange` handler is called once on every input box change.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by gouttierre** [comment]
@FeodorFitsner - Thank you for filing this item. I see you are willing to file a PR for this fix which is great to see - please do share it with us.

**Comment by FeodorFitsner** [comment]
@gouttierre There was a PR that didn't pass a review and got closed as stale: https://github.com/microsoft/fluentui/pull/17589
Honestly, at this point I'm not sure what would be the acceptable way to fix that issue.

**Comment by shepparddean** [comment]
The handler gets called twice, and the event object is not sent into the handler.

**Comment by prram** [comment]
any update on this?

**Comment by jmagaram** [comment]
I’ve lost hours trying to figure out why this is happening to me. Thought it was a React strict mode thing but nope. Tried preventaDefault and other approaches. Then eventually found this issue. I hope someone fixes it.
