### ISSUE TITLE
Menu: `vertical` prop is not passed through `MenuContext`

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#17585]
@fluentui/react-northstar@0.53.0

`vertical` prop is not passed to `Menu.ItemContent` through `MenuContext`. As a result, when Children API is used, it is necessary to explicitly set `vertical` on all items in vertical menu:
```jsx
<Menu vertical>
  <MenuItem>
    <MenuItemContent vertical /> {/* !!! */}
  <MenuItem />
</Menu>
```

Without that, the styles do not match Shorthand API - width of the menu is different:
https://fluentsite.z22.web.core.windows.net/0.53.0/components/menu/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#variations-vertical-pointing

Only some props are passed from `Menu` to its items through `MenuContext`:
https://github.com/microsoft/fluentui/blob/5ea6c17c7d159e450fed338da142b8181852be56/packages/fluentui/react-northstar/src/components/Menu/Menu.tsx#L299-L318

How have we selected the props to propagate? How do we test all necessary props are propagated?

**Comment by gouttierre** [comment]
@miroslavstastny - Thank you for filing this item and the context into the issue.
@kolaps33 - Would you be able to confirm if this is a regression, or if this behavior is an issue?
