### ISSUE TITLE
Slider: select a range by providing two thumbs (knobs)

### ISSUE THREAD

**Issue by ts-00** [microsoft/fluentui#17598]
#### Describe the feature that you would like added

I would like to see the following options for the component https://developer.microsoft.com/de-de/fluentui#/controls/web/slider:

- useRangeSlider: if true, provides two knobs, instead of one (for selecting a range)
- minValue: minimum selected value
- maxValue: maximum selected value

#### What component or utility would this be added to

https://developer.microsoft.com/de-de/fluentui#/controls/web/slider

#### Additional context/screenshots

Look at https://material-ui.com/components/slider/ (Range Slider) for inspiration.

**Comment by JustSlone** [comment]
@ts-00, actually we have this already documented here: https://developer.microsoft.com/de-de/fluentui#/controls/web/slider

codepen: https://codepen.io/justslone-the-encoder/pen/eYvYabR
