### ISSUE TITLE
Calendar: provide properties for selecting a range

### ISSUE THREAD

**Issue by ts-00** [microsoft/fluentui#17599]
#### Describe the feature that you would like added

I would like to see the following properties for https://developer.microsoft.com/de-de/fluentui#/controls/web/calendar:

- useRange: if true, a range can be selected (consisting of minSelectedValue and maxSelectedValue)
- minSelectedValue: the minimum date selected
- maxSelectedValue: the maximum date selected

#### What component or utility would this be added to

https://developer.microsoft.com/de-de/fluentui#/controls/web/calendar

**Comment by gouttierre** [comment]
@ts-00 - Thanks for the item and suggestion. Have you reviewed our implementation API's for the [Calendar](https://developer.microsoft.com/de-de/fluentui#/controls/web/calendar)? There are similar properties, such as:
`dateRangeType` - The date range type indicating how many days should be selected as the user selects days.
`maxDate `- If set the Calendar will not allow navigation to or selection of a date later than this value.
`minDate `- If set the Calendar will not allow navigation to or selection of a date earlier than this value.
