### ISSUE TITLE
Lock and unlock icons

### ISSUE THREAD

**Issue by amommy** [microsoft/fluentui#17604]
#### Describe the feature that you would like added

Is there a way to change, or add another, unlock icon to an actual unlocked padlock with the shackle in the other direction. or make the opening wider. used in in an app and looks just like it does on powerapps solution page but users say difficult to distinguish between the two locked/unlocked. Looking a them they are a little difficult to distinguish at first glance

#### What component or utility would this be added to

Icon 

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/200803/112764310-eb18a900-8fd5-11eb-900e-9d38dfc6d243.png)
![image](https://user-images.githubusercontent.com/200803/112764791-2fa54400-8fd8-11eb-8341-c33dcb3cd20c.png)
![image](https://user-images.githubusercontent.com/200803/112765008-21a3f300-8fd9-11eb-8052-2a612d920967.png)

**Comment by gouttierre** [comment]
@amommy - thanks for reaching out. Have you looked at our latest [Icons ](https://fabricweb.z5.web.core.windows.net/oufr/8.9.4/#/examples/icon) as we do have those variants. 
![image](https://user-images.githubusercontent.com/78806055/114414499-265ad080-9baf-11eb-86e4-b0d823a694c0.png)
