### ISSUE TITLE
Button component does not display tooltip when disabled

### ISSUE THREAD

**Issue by benkaiser** [microsoft/fluentui#17606]
### Environment Information

- **Package version(s)**: 7.160.3
- **Browser and OS versions**: Chrome 90 on Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/benkaiser/pen/vYgKMGX

- Hover over the disabled buttons, see they do not show the title tooltip (since the pointer events are set to "none" in the css properties)

This was [discussed in a previously closed issue](https://github.com/microsoft/fluentui/issues/12673), however I believe the conclusion was incorrect since [HTML buttons **do** show tooltips even when disabled](https://codepen.io/benkaiser/pen/WNRxWRJ).

#### Actual behavior:

Button does not show "title" attribute since pointer events are disabled.

#### Expected behavior:

Button should show the "title" tooltip.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: SharePoint feature development

### Notes

I can try and work around this behavior by applying custom styles to re-instate the pointer events, however it would be great if we could fix this in Fluent UI.

**Comment by khmakoto** [comment]
Hi @benkaiser, thanks for filing this issue! How would you feel about using our `TooltipHost` component to alleviate this problem? That works on our disabled buttons and is more visually consistent with the Fluent design language as can be seen in [this codepen](https://codepen.io/khmakoto/pen/ExZwRWb?editors=0010).

**Comment by benkaiser** [comment]
The TooltipHost does indeed work around the problem, however it's a rather costly overhead (extra react component, more DOM nodes) for the many places we render these disabled buttons.

Is there a reason we can't re-enable pointer-events on disabled buttons?

Or can we bake in TooltipHost to Button when `title` is passed in if that is the recommended pattern?

**Comment by khmakoto** [comment]
@benkaiser I think the recommended thing would still be to use `TooltipHost`. However, upon further inspection of the code, I see no apparent reason not to remove the `pointerEvents: 'none'` styling. Would you be willing to spin up a PR?
