### ISSUE TITLE
DetailsList sorting in Function Component always returns null in the items and columns

### ISSUE THREAD

**Issue by abhishek-raj** [microsoft/fluentui#17612]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@7
- **Browser and OS versions**: Windows 10, Edge(Chromium Based) and Firefox

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/rajabhishek/pen/PoWGKPW

#### Actual behavior:
I had adapted the example provided in the DetailsList for sorting a column to function component.
But in function component the onColumnClick function has empty values for items and columns.

#### Expected behavior:
The rows should get filtered column wise.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Low)

**Comment by gouttierre** [comment]
@abhishek-raj - Thank you for filing this item and wanting to submit a PR for the fix. Please do share it with us and the team will review it when possible. Thank you

**Comment by abhishek-raj** [comment]
Okay. I will work on a PR. Thanks.
