### ISSUE TITLE
Need the ability to have the whole iTag, not just the x, receive focus and then remove the tag upon hitting enter or space keys.

### ISSUE THREAD

**Issue by tdempsey2** [microsoft/fluentui#17614]
### Environment Information

- **Package version(s)**: 7.0.24
- **Browser and OS versions**: MacOS/Windows 10 Edge, Chrome

### Describe the issue:

Need to allow keyboard users to have 1 less keyboard action to remove tags

#### Actual behavior:

User can only remove a tag by clicking x 

#### Expected behavior:

Allow the user to remove a tag by focusing on the whole tag and clicking.

**Comment by tdempsey2** [comment]
Is there a way to resolve this already?

**Comment by ecraig12345** [comment]
To investigate this we'll need a codepen repro of the issue, as requested in the issue template. You can start from https://aka.ms/fluentpen, or by clicking "Export to CodePen" on a component example from [our website](https://developer.microsoft.com/en-us/fluentui#/controls/web).
