### ISSUE TITLE
'content' property is not getting picked by mergeStyles()

### ISSUE THREAD

**Issue by pragya91** [microsoft/fluentui#17615]
### Environment Information

- **Package version(s)**: 7.x.x and 8.x.x
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/pragya91/pen/VwPKQRB

#### Actual behavior:

'content' property in pseudo selectors is not getting picked up by mergeStyles

#### Expected behavior:

'content' property should get picked up just like other properties by mergeStyles

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

**Comment by gouttierre** [comment]
@pragya91  - Thank you for filing this item and the issue details.
@TristanWatanabe - Would you be able to confirm if this is a regression, or if this behavior is an issue with mergeStyles()?

**Comment by pragya91** [comment]
@gouttierre I did not try this behavior with a previous versions, so I don't have enough data to comment on whether it is a regression or a behavior issue.

**Comment by khmakoto** [comment]
Try using `'"1234"'` instead of only `'1234'`, it should work. This is a quirk in how `mergeStyles` expects that string to be passed in but it is neither a true bug nor a regression.

**Comment by pragya91** [comment]
Thanks for the update. '"1234"' did work. Thanks.
