### ISSUE TITLE
VerticalStackedBarChart should have the option to disable clicking of legend

### ISSUE THREAD

**Issue by sthigale-m** [microsoft/fluentui#17638]
#### Describe the feature that you would like added

VerticalStackedBarChart should have the option to disable clicking of legend. See the image below. We should be able to disable the options "Any Xbox device name", "Any phone device name", "Any mobile device name" so that the user cannot click on it.

![image](https://user-images.githubusercontent.com/73924391/113103301-bc404400-921c-11eb-965b-88f813ddca2c.png)

#### What component or utility would this be added to

VerticalStackedBarChart

**Comment by Raghurk** [comment]
I am following up with design team on this.

**Comment by gouttierre** [comment]
@Raghurk - have you gotten any updates on this yet? thanks in advance.

**Comment by Raghurk** [comment]
Sorry for the delayed response. The design team has not yet gotten back to us.

**Comment by Raghurk** [comment]
We are still working on this
