### ISSUE TITLE
ComboBox: Clicking outside input reset value to previous one for free form input

### ISSUE THREAD

**Issue by dantist1122** [microsoft/fluentui#17630]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "7.165.1"
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a codepen:
1. enter some value 
2. click outside to save it
3. click arrow to open dropdown
4. while dropdown is open modify the value
5. click outside dropdown
![github issue](https://user-images.githubusercontent.com/44105538/113051878-563fb800-915b-11eb-86fb-3e3ebbed0bce.gif)

#### Actual behavior:

value resets to previous one

#### Expected behavior:

if we modify that we need to keep value we modified

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@dantist1122 - Thank you for filing this item. I had a look at our updated docs for the [combobox](https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox). I was unable to repro the problem - could you confirm you are still experiencing the problem?
