### ISSUE TITLE
Fluent Message Bar Guidance

### ISSUE THREAD

**Issue by ziabella** [microsoft/fluentui#17659]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:
When I land on the message bar guidance located at https://developer.microsoft.com/en-us/fluentui#/controls/web/messagebar, none of the message bar types are visible making it hard to quickly share this information with PM and Devs.

#### Actual behavior:
None of the message bar types are visible

#### Expected behavior:
Show all should be selected by default so that I can easily see all the message bar options.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
We had to hide the MessageBars by default because otherwise they would all be announced on page load for screen reader users, though I agree this isn't ideal for sighted users. If you want to see all of them, you can click the last option.
