### ISSUE TITLE
Breadcrumb name not properly visible on small screens or 200% zoom

### ISSUE THREAD

**Issue by mharnetiaux** [microsoft/fluentui#17652]
### Environment Information

- All Browsers

### Describe the issue:

This was called out in a HCL review.

1. Open a example Breadcrumb in Fluentui.
3. Open dev tools and dock inspector to right side.
4. Drag screen below 360px.
5. Update a Breadcrumb item with long text, such as "Diversity inclusion and being an ally across cultures"
6.  Notice dialog is not properly visible.

#### Actual behavior:

Breadcrumb item is not properly visible on small screens with long names.

#### Expected behavior:

Breadcrumb item is properly visible on small screens with long names.

**Comment by gouttierre** [comment]
@mharnetiaux  - thanks for reaching out. 

@miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley

**Comment by miroslavstastny** [comment]
Not a regression, I see the same behavior in OUIFR 7.155.3:
![image](https://user-images.githubusercontent.com/9615899/121905020-fef8bf00-cd29-11eb-94db-480be37173a7.png)

The same behavior is in `ContextualMenu` which is used inside `Breadcrumb` - there is neither `width` nor `min-width` defined on the popover, therefore the menu items expand to fit their content.

For `ContextualMenu` it is possible to explicitly set the `max-width` using `calloutProps: {calloutMaxWidth: 300}`, but
1. the value can only be in `px`,
2. it is not possible to pass it from `Breadcrumb`.
