### ISSUE TITLE
Charting: Library does not supports duplicates

### ISSUE THREAD

**Issue by ms-khgo** [microsoft/fluentui#17662]
### Environment Information

- **Package version(s)**:  4.13.7
- **Browser and OS versions**: Chrome, Windows 10

#### Actual behavior:

In `VerticalStackedBarChart`, we are using shortest day names(Su, Mo, Tu, We, Th, Fr, Sa) as x-axis legends. But in other languages, we get duplicate shortest day names for different days which confuses the charting library and gives a bad UI experience.

An example in Portugal language.
![image](https://user-images.githubusercontent.com/81736144/113251702-5e753000-92e0-11eb-849d-049142f2da7f.png)

#### Expected behavior:

Charting library should support duplicate names.

An example in English language.
![image](https://user-images.githubusercontent.com/81736144/113251680-53220480-92e0-11eb-9ab1-b1c5aa8ef0d4.png)

**Comment by Raghurk** [comment]
The charting library has no idea on your x-axis value. This is a prop that you pass to define the content, it is your responsibility to prevent duplication.

**Comment by ms-khgo** [comment]
@Raghurk Actually we want the x-axis to support duplicate values.
