### ISSUE TITLE
Tooltip of VerticalStackedBarChart's Legend is not going off as long as the scroll is going.

### ISSUE THREAD

**Issue by yakkala1** [microsoft/fluentui#17671]
Checkout this video:
https://user-images.githubusercontent.com/32043510/113337362-4daad580-9345-11eb-9493-2a2a2e38acec.mp4

### Environment Information
- Observed this in Windows 10 Chrome, Windows 10 Edge and One Plus 8 chrome browser.

#### Actual behavior:
Tooltip is not going away until the scroll stops.

#### Expected behavior:
Tooltip should be going away once the scrolling starts or beyond a limit of scroll.

### Priorities and help requested:
Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

**Comment by Raghurk** [comment]
I will look into this

**Comment by gouttierre** [comment]
@yakkala1 - thanks for reaching out

@Raghurk - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by Raghurk** [comment]
We are investigating this.
