### ISSUE TITLE
LineChart: 12 points or more on 12 lines or more causes duplicated line and circle keys, causes rendering issue when selecting legends

### ISSUE THREAD

**Issue by cgaryet** [microsoft/fluentui#17686]
### Environment Information

- **Package version(s)**: fluentui/react-charting@5.0.22
- **Browser and OS versions**: Chrome 89.0.4389.9, Windows 10

### Please provide a reproduction of the bug in a codepen:

1. Create a 12x12 set of data for a LineChart:
```
let chartData = { lineChartData: [] };
for(let x = 0; x < 12; x++) {
    let chartPoints = [];
    for(let y = 0; y < 12; y++) {
        chartPoints.push({
            x: y,
            y: (y * x),
        });	
    }
    chartData.lineChartData.push({
        color: 'black',
        data: chartPoints,
        legend: `${x}`
    });
}
```

2. Add that data to a chart:
`<LineChart data={chartData}/>`

This seems to only reproduce if there specifically are 12 points or more on 12 lines or more.
For example, 1 line with 200 points is fine. 11 lines with 11 points are fine. 11 lines with 200 points are fine.

Apologies for the lack of a codepen, I was having a hard time srcing the LineChart library.

#### Actual behavior:

1. Open the dev console, notice warnings:
```
index.js:1 Warning: Encountered two children with the same key, `circle316111`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at g
    at g
    at svg
    at div
    at FocusZone (http://localhost:3000/static/js/11.chunk.js:16357:24)
    at div
    at CartesianChartBase (http://localhost:3000/static/js/11.chunk.js:6906:24)
    at http://localhost:3000/static/js/11.chunk.js:48614:62
    at LineChartBase (http://localhost:3000/static/js/11.chunk.js:10468:26)
    at http://localhost:3000/static/js/11.chunk.js:48614:62
    at div
```
2. Click on any of the legend items, notice lines with duplicated IDs being selected.
![image](https://user-images.githubusercontent.com/7631262/113451218-24cb2480-93c7-11eb-9ada-828f59823aae.png)

#### Expected behavior:

Line IDs should not be duplicated.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by Raghurk** [comment]
This is by design, We don't expect to have line charts with more than 8 data points. Please reach out to Jonah Lu if you have any concern

**Comment by cgaryet** [comment]
I dug into the source for this. In LineChart.base.tsx line 501/502, simply adding an underscore to the id completely mitigates the issue, where this repro'd before with 12 points or more because i==11 & j == 1 and i==1 and j==11 generate the same line and circle id keys.
```
const lineId = `${this._lineId}${i}_${j}`;
const circleId = `${this._circleId}${i}_${j}`;
```

Is this by design for performance reasons, or was there some underlying thing I missed?
