### ISSUE TITLE
Northstar's Dropdown renders a scrollbar even when text does not overflow

### ISSUE THREAD

**Issue by davyrwoo** [microsoft/fluentui#17692]
### Environment Information

- **Package version(s)**: 0.53.0
- **Browser and OS versions**: Version 89.0.4389.90

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluent-ui-example-forked-bji4b?file=/example.js

Using Dropdown with fluid and adjusting the width to be less than 100px, the Dropdown seems to always render a scrollbar, even though the content should not need to overflow.

#### Actual behavior:

Scrollbar is visible in the Dropdown

#### Expected behavior:

Scrollbar should not be visible

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by gouttierre** [comment]
@davyrwoo - Thank you for filing this item and sharing background context into the problem.
@kolaps33 -  Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by davyrwoo** [comment]
Any updates on this issue?
