### ISSUE TITLE
Northstar's Divider is not visible when used inside a Table cell

### ISSUE THREAD

**Issue by davyrwoo** [microsoft/fluentui#17691]
### Environment Information

- **Package version(s)**: 0.53.0
- **Browser and OS versions**: Version 89.0.4389.90

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluent-ui-example-forked-864wt

#### Actual behavior:

Divider is not visible when used within the cell

#### Expected behavior:

Divider should be visible between the two rendered Text 

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by gouttierre** [comment]
@davyrwoo - thanks for reaching out.  I was unable to confirm your issue. I se the divider between the rows in each of the themed states. 
![image](https://user-images.githubusercontent.com/78806055/119486825-f891ab80-bd58-11eb-8431-945f3aaf463d.png)
![image](https://user-images.githubusercontent.com/78806055/119486892-06473100-bd59-11eb-8e0e-10a4cc416d34.png)
![image](https://user-images.githubusercontent.com/78806055/119486911-0ba47b80-bd59-11eb-8652-f35f45398aeb.png)

Could you confirm you still having an issue? Thank you

**Comment by assuncaocharles** [comment]
I don't think it's actually an issue, adding specific height to the divider or to the parent ( the `Flex` in the example ) will do the work. The problem here is actually the divider has height 100% but no reference of height in the parent.
