### ISSUE TITLE
TooltipHost : <div> cannot appear as a descendant of <p> 

### ISSUE THREAD

**Issue by vorobievik** [microsoft/fluentui#17696]
Hi. in my case the TooltipHost is a child of the paragraph (I am using the wysiwyg editor), so I have an error in the console.  ``<div> cannot appear as a descendant of <p>``  , how this can be fixed? Is there any means to change div tag for TooltipHost
Actual behavior:
https://codepen.io/vorobievik/pen/LYxLMmd
we have an error in the console

**Comment by ecraig12345** [comment]
Right now there's not a way to customize which element the TooltipHost renders as, but I can see how that might be helpful in certain situations. One approach would be adding a prop `as?: 'div' | 'span'` (and possibly other elements if they make sense). Or it might be possible to change it to use a `<span>` by default, but that would require more investigation to verify it wouldn't break anything else.
