### ISSUE TITLE
fluentui 8 compatibility issues with Next 10

### ISSUE THREAD

**Issue by DayZeroLLC** [microsoft/fluentui#17695]
### Environment Information
    "@fluentui/react": "^8.5.0",
    "@fluentui/react-theme-provider": "^0.18.5",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "next": "^10.1.3",
    "office-ui-fabric-react": "^7.165.2",    

### Describe the issue:
Usage of 'office-ui-fabric-react/lib/Dropdown' fails in next 10 environments.

#### Actual behavior:
```
import { Dropdown, DropdownMenuItemType, IDropdownStyles, IDropdownOption } from 'office-ui-fabric-react/lib/Dropdown';
```

```
/Users/chad/Documents/git/FUI/fluent-ui-app/bm-marketplace/node_modules/office-ui-fabric-react/lib/Dropdown.js:1
export * from './components/Dropdown/index';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at eval (webpack-internal:///office-ui-fabric-react/lib/Dropdown:1:18)
```

#### Expected behavior:
working import of Dropdown interfaces/classes.

### If applicable, please provide a codepen repro:

environment setup:
npx create-react-app bm-marketplace --template typescript
cd bm-marketplace
yarn add @fluentui/react @fluentui/react-theme-provider
yarn add office-ui-fabric-react _This isn't needed in a regular react project, but tried in troubleshooting_
yarn add next react react-dom

Edit index.tsx to contain "import { Dropdown, DropdownMenuItemType, IDropdownStyles, IDropdownOption } from 'office-ui-fabric-react/lib/Dropdown';"

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No clue how to resolve.

Requested priority: (Blocking, High, Normal, Low) I assume Normal, would be nice to get initial response if FluentUI is designed to work with NextJS or not. I see another issue for this months ago that was auto-closed to submitter not responding to comments.

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
It looks like something in your setup isn't handling ES Module syntax. Without seeing more details, it's hard to say exactly which part is the issue. Can you try forking and editing this codesandbox to repro the issue? https://codesandbox.io/s/issue-17695-vc3k1

Also, you shouldn't be using `office-ui-fabric-react` and `@fluentui/react@8` together, since that will give you a huge amount of duplicated code. New apps should be using `@fluentui/react` only.

**Comment by DayZeroLLC** [comment]
> It looks like something in your setup isn't handling ES Module syntax. Without seeing more details, it's hard to say exactly which part is the issue. Can you try forking and editing this codesandbox to repro the issue? https://codesandbox.io/s/issue-17695-vc3k1
> 
> Also, you shouldn't be using `office-ui-fabric-react` and `@fluentui/react@8` together, since that will give you a huge amount of duplicated code. New apps should be using `@fluentui/react` only.

I will test with that repo. Perhaps we can add some guidance to the fluentui samples at https://developer.microsoft.com/en-us/fluentui#/ to make that point clear.

**Comment by ecraig12345** [comment]
What I meant was that you should fork the codesandbox (within the codesandbox web UI) and make modifications there to resemble your setup, not try to download it locally.

**Comment by DayZeroLLC** [comment]
Hi Elizabeth, I got the intent to use codesandbox to more clearly demonstrate the issue, but when using codesandbox try to spin up that code it fails (prior to forking it and making any changes on my side). See link below. (https://u.pcloud.link/publink/show?code=XZ61JsXZmuG7Apj9UfYgYnOwSYfnG4iK7Rgk)]

**Comment by gouttierre** [comment]
@DayZeroLLC - thanks for sharing the code sandbox [url ](https://u.pcloud.link/publink/show?code=XZ61JsXZmuG7Apj9UfYgYnOwSYfnG4iK7Rgk). 

@miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @ecraig12345

**Comment by miroslavstastny** [comment]
I see the same problem in both v7 and v8. Next v10 compilation fails whenever deep imports are used:
```
export * from './components/Dropdown/index';
^^^^^^

SyntaxError: Unexpected token 'export'
```

But that's what docs recommend: https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing.

I propose to update the documentation to import directly from `office-ui-fabric-react` (v7) or `@fluentui/react` (v8). @ecraig12345, @layershifter would you agree?

**Comment by layershifter** [comment]
Deep imports are not compatible with Next.js because Next.js will run code in Node environment for SSR while `/lib/**/*` files contain only ESM. I see multiple options to solve "deep imports" problem:

#### Option 1

Is to configure something like [`babel-plugin-transform-imports`](https://www.npmjs.com/package/babel-plugin-transform-imports) directly on Webpack loader in `next.config.js`: it will transform normal imports to deep ones but I never tried such setup.

#### **Option 2**

Use [`next-transpile-modules`](https://github.com/martpie/next-transpile-modules), it should work out of the box:

> code transpilation from NPM modules using ES6 imports (e.g lodash-es)

Can you please try it @miroslavstastny?

**Comment by kidlj** [comment]
I have met the same `SyntaxError export...` issue with next.js 11 and fluentui/react 8 while following fluentui demos.
```
/home/lijian/Code/metaphor/frontend/fluentui-demo/node_modules/@fluentui/react/lib/Stack.js:1
export * from './components/Stack/index';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.@fluentui/react/lib/Stack (/home/lijian/Code/metaphor/frontend/fluentui-demo/.next/server/pages/stack/basic.js:33:18)
    at __webpack_require__ (/home/lijian/Code/metaphor/frontend/fluentui-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/stack/basic.tsx:6:83)
```

The fluentui/react [demo code from documentation](https://developer.microsoft.com/en-us/fluentui#/controls/web/stack) site has imports like the following:
```javascript
import * as React from 'react';
import { Stack, IStackStyles, IStackTokens, IStackItemStyles } from '@fluentui/react/lib/Stack';
import { DefaultPalette } from '@fluentui/react/lib/Styling';
```

After changing the imports to this:
```javascript
import * as React from 'react';
import { Stack, IStackStyles, IStackTokens, IStackItemStyles } from '@fluentui/react';
import { DefaultPalette } from '@fluentui/react';
```

then the issue has gone.

Maybe we should update the demo code from documentation site?
