### ISSUE TITLE
IFontWeight not compatible with @types/react (internally csstype)

### ISSUE THREAD

**Issue by villasv** [microsoft/fluentui#17700]
#### Describe the feature that you would like added

I'm trying to do some basic styling:
```tsx
<h1 style={{ fontSize: FontSizes.superLarge, fontWeight: FontWeights.light }}>Welcome</h1>
```

But I'm getting `Type '"100"' is not assignable to type 'FontWeight | undefined'.` because `IFontWeight` is not compatible with `@types/react`'s interface `FontWeight`.

I've opened an issue with csstypes (https://github.com/frenic/csstype/issues/125) asking for the addition of string numerals, though if these are not really used in the @fluentui/theme lib, might as well just make the adjustment on this side by narrowing the `IFontWeight` interface to exclude them.

#### What component or utility would this be added to

`@fluentui/themes` (or `@fluentui/merged-styles`?)

**Comment by frenic** [comment]
Union string (`... | string`) is needed to make this work today and is avoided whenever possible. To solve this we first need to implement a TS4.1 alternative and use `` number | `${number}` `` to make `100` and `"100"` work, but not e.g. `"lihgter"`.

**Comment by ecraig12345** [comment]
Sorry for the delayed response. Which specific versions of `@types/react` and `@fluentui/merge-styles` are you using? (Depending on your package manager, you can find this by doing `npm ls @types/react` or `yarn why @types/react`, and similar for merge-styles.)

**Comment by villasv** [comment]
Uhh, it was latest on both, at least at the time of opening this issue. I'll have to check again if it's still the case with current version.

**Comment by villasv** [comment]
Yep, still happening.

`@types/react`: 17.0.5
`@fluentui/merge-styles`: 8.1.0

**Comment by WillemSleegers** [comment]
I am having the same issue.

**Comment by frenic** [comment]
In `csstype@3.0.10` union `string` is now also applied wherever union `number` or number literal is applied. So upgrading should solve this issue.

**Comment by ecraig12345** [comment]
Confirmed this is fixed in the latest `csstype`.
