### ISSUE TITLE
MultiStackedBarChart - screen reader reads wrong data on tab key press when setting hideTooltip: true prop

### ISSUE THREAD

**Issue by noasilberstein** [microsoft/fluentui#17728]
### Environment Information

- **Package version(s)**: 3.3.1. Also happens in 4.15.13
- **Browser and OS versions**: Chrome 89.0.4389.114, Mac OS 10.15.7

### Describe the issue:

When hideTooltip prop is set to true, MultiStackedBarChart Callout object does not contain the relevant information for screen reader.

Example:

Create MultiStackedBarChart, without setting the hideTooltip prop
```
import * as React from "react";
import { MultiStackedBarChart } from '@uifabric/charting';

export class PlaceholderBarChartExample extends React.Component {
  render(): JSX.Element {
    const chartPoints = [
      { legend: 'Malware', data: 40, color: '#00AE56' },
      { data: 87, placeHolder: true },
    ];

    const data = [
      {
        chartTitle: 'Test',
        chartData: chartPoints,
      },
    ];

    return (
    <MultiStackedBarChart
        data={data}
        width={600}
    />
    );
  }
}

```

you can see the callout object created in the DOM contains the relevant chart data (malware, 40):
![image](https://user-images.githubusercontent.com/79595481/113849016-b957cd00-97a1-11eb-9a09-40ecf74878a4.png)

Now add the hideTooltip prop:
```
import * as React from "react";
import { MultiStackedBarChart } from '@uifabric/charting';

export class PlaceholderBarChartExample extends React.Component {
  render(): JSX.Element {
    const chartPoints = [
      { legend: 'Malware', data: 40, color: '#00AE56' },
      { data: 87, placeHolder: true },
    ];

    const data = [
      {
        chartTitle: 'Test',
        chartData: chartPoints,
      },
    ];

    return (
    <MultiStackedBarChart
        data={data}
        hideTooltip
        width={600}
    />
    );
  }
}

```

And look again, the callout object doesn't show any data, and as a result, the screen reader reads "group, 0"

![image](https://user-images.githubusercontent.com/79595481/113849321-0c318480-97a2-11eb-964a-6bdbc0c5eee9.png)

#### Actual behavior:

screen reader reads "group, 0" when focusing on the chart element using tab key
#### Expected behavior:

screen reader should read "Malware, 40" when focusing on the chart element using tab key, as it does when tooltip exists.

**Comment by Raghurk** [comment]
I will look into this

**Comment by gouttierre** [comment]
@noasilberstein  - thanks for reaching out.

@Raghurk - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by Raghurk** [comment]
We are investigating this.

**Comment by Raghurk** [comment]
This is now fixed, Please update to the latest package.
