### ISSUE TITLE
Bug in Wiki page: Server side rendering and browserless testing

### ISSUE THREAD

**Issue by zmarty** [microsoft/fluentui#17720]
Page: https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing

Under the code block which starts with "Create a _document.js file under your pages folder with the following content" there is a small bug:

Incorrect:
```
// Fluent UI React (Fabric) 7 or earlier
import { Stylesheet, InjectionMode } from "@uifabric/merge-styles";
import { resetIds } from "@uifabric/utilities";
// Fluent UI React 8+
// import { Stylesheet, InjectionMode } from "@uifabric/merge-styles";
// import { resetIds } from "@uifabric/utilities";
```

Correct:
<pre>
// Fluent UI React (Fabric) 7 or earlier
import { Stylesheet, InjectionMode } from "@uifabric/merge-styles";
import { resetIds } from "@uifabric/utilities";
// Fluent UI React 8+
// import { Stylesheet, InjectionMode } from "@<b>fluentui</b>/merge-styles";
// import { resetIds } from "@<b>fluentui</b>/utilities";
</pre>

**Comment by ecraig12345** [comment]
Fixed, thanks!
