### ISSUE TITLE
Slider onChanged not triggered by home/end key

### ISSUE THREAD

**Issue by DanqingFu** [microsoft/fluentui#17734]
### Environment Information

- **Package version(s)**: 7.84.0
- **Browser and OS versions**: (Microsoft Edge Version 89.0.774.68 (Official build) (64-bit))

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/danqing-fu/pen/dyNVmaM

#### Actual behavior:
navigate to the slider bug, using left/right arrow key to change the value, the console will log the event, but if we press Home/End key, onchange event will trigger, we can see the value change, but onChanged won't, we cann't see any log in console.

#### Expected behavior:
onChnaged Event should been triggered for Home/End key too

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: (if applicable)

**Comment by tomi-msft** [comment]
Hi @DanqingFu, thanks for submitting the issue. I can confirm that this is a bug, and am working on putting out a fix!
