### ISSUE TITLE
Focusable items after an IFRAME in a Modal or FocusTrapZone are not reachable by tabbing

### ISSUE THREAD

**Issue by BrendanMcK** [microsoft/fluentui#17747]
### Environment Information

- **Package version(s)**: 7.164.0
- **Browser and OS versions**: Any

### Describe the issue:

If a Modal (or FocusTrapZone) contains an IFRAME, any links or other focusable items following the IFRAME cannot be reached by tabbing.

Codepen repro with Modal here: https://codepen.io/brendanmckeon/pen/GRrOvgm

Codepen repro with plain FocusTrapZone here: https://codepen.io/brendanmckeon/pen/bGgvqNe

Click the button to open the modal, then tab through the items: once focus reaches the last item in the nested IFRAME, it loops back to the first item in the modal instead of continuing to the items after.

Expect that tabbing would continue through to the links after the IFRAME.

A similar issue happens with shift-tabbing, except focus jumps from the first item in the IFRAME to the first link after the IFRAME in the modal, skipping all other focusable items in the modal.

Suspect this is due to the code in Modal that's managing focus - FocusTrapZone? (Edit - confirmed, and added codepen for that also.) - it may be treating focus coming out of the IFRAME as though it were re-entering the modal outright, so is forcibly setting focus to the first item.

**Comment by gouttierre** [comment]
@BrendanMcK - thank you for sharing the information into the issue you are experiencing. 

@miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley
