### ISSUE TITLE
Color Formatting issues

### ISSUE THREAD

**Issue by FairyTail2000** [microsoft/fluentui#17742]
### Environment Information

- **Package version(s)**: (fill this out) Irrelevant
- **Browser and OS versions**: (fill this out if relevant) Vivaldi 3.7.2218.52 (Stable channel) (64-Bit) Windows 10 Version 10.0.19042 Build 19042

### Please provide a reproduction of the bug in a codepen:

Go to https://developer.microsoft.com/en-us/fluentui?fabricVer=6#/controls/web/messagebar
Press show code

#### Actual behavior:
Wrong Color Formatting

#### Expected behavior:

Correct Color Formatting

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No, because I don't know how to fix it

Requested priority: (Blocking, High, Normal, Low) Low

Products/sites affected: (if applicable)

https://developer.microsoft.com/en-us/fluentui?fabricVer=6#/controls/web/messagebar

![image](https://user-images.githubusercontent.com/22645621/114008309-685bdd80-9862-11eb-82b2-6369f5622a61.png)

**Comment by ecraig12345** [comment]
The issue here is that the formatter we're using on the version 6 website doesn't properly handle JSX/TSX syntax. Unfortunately, since that version of the site is very old, it's not something we're going to fix at this point.
