### ISSUE TITLE
Dropdown component's Search Selection in controlled mode has issue with typing in language using certain IME

### ISSUE THREAD

**Issue by spidershark** [microsoft/fluentui#17760]
### Environment Information

- **Package version(s)**: 0.54.0
- **Browser and OS versions**: any

### Describe the issue:

The Dropdown component's Search Selection in controlled mode has issue with typing in language that relies on IME where composition completes with more than one letter, like Korean. Currently if user types 'r' and 'k' with Korean Microsoft IME, it shows ㄱ가 which is 'r' followed by 'rk'. But the correct character it enters should be only 가 which is 'rk'.

I think the problem is that the Dropdown component is firing the `onSearchQueryChange` before the composition is complete. Or alternatively, it should return the [KeyboardEvent.isComposing](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing) so consumer can detect that composition is not complete and not save the value to state.

#### Actual behavior:

Presses keys 'r' and 'k' in Korean currently shows ㄱ가, which is 'r' followed by 'rk'.

#### Expected behavior:

Presses keys 'r' and 'k' in Korean should show 가, which is 'rk'.

### If applicable, please provide a codepen repro:

1. Go to https://codesandbox.io/s/fluent-ui-example-forked-d9zms?file=/example.js:0-889
2. Switch to Korean Microsoft IME, and in the dropdown search input, type 'r' and 'k'.
3. If you comment out the line `searchQuery={localSearchQuery}` (so it's not in controlled mode), then it works correctly.

Here is the source code for the sandbox
```
import React from "react";
import { Dropdown } from "@fluentui/react-northstar";

const inputItems = [
  "Robert Tolbert",
  "Wanda Howard",
  "Tim Deboer",
  "Amanda Brady",
  "Ashley McCarthy",
  "Cameron Evans",
  "Carlos Slattery",
  "Carole Poland",
  "Robin Counts"
];

const DropdownExampleSearch = () => {
  const [localSearchQuery, setLocalSearchQuery] = React.useState("a");
  const onSearchQueryChange = (_: any, data: any) => {
    setLocalSearchQuery(data?.searchQuery || "");
  };

  return (
    <Dropdown
      search
      searchQuery={localSearchQuery}
      onSearchQueryChange={onSearchQueryChange}
      items={inputItems}
      placeholder="Start typing a name"
      noResultsMessage="We couldn't find any matches."
      getA11ySelectionMessage={{
        onAdd: (item) => `${item} has been selected.`
      }}
    />
  );
};

export default DropdownExampleSearch;

```

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: https://teams.microsoft.com/share, although we have a work around for now, which is to not use controlled mode.

**Comment by gouttierre** [comment]
@spidershark - Thank you filing this issue. 
@kolaps33 - Would you be able to confirm if this is a regression, or if this behavior is an issue? I see it is mentioned in the PR #18165. 
cc @TristanWatanabe

**Comment by YuanboXue-Amber** [comment]
Hi, I tried to reproduce it but it works for me.
Here's a screen recording with example source code:
https://recordit.co/JxMVhvSbk9
Let me know if I missed anything :)
