### ISSUE TITLE
DetailsList component not working

### ISSUE THREAD

**Issue by AdamSchinzel** [microsoft/fluentui#17773]
### Environment Information

- **Package version(s)**: 8.8.0

#### Actual behavior:

I'm building a react web app and when I wanted to use any type of DetailsList component, it is not working.

Link to component: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic

I found that the component is render on the Fluent UI website but when I hit show code and just click inside the code, after few seconds it shows this error:

![Screenshot 2021-04-10 at 6 29 14 AM](https://user-images.githubusercontent.com/66002635/114258566-a1619280-99c7-11eb-985d-1211570c8899.png)

#### Expected behavior:

Component is fully useable in my app and also render without any problems on the fluent-controls website.

### Priorities and help requested:

Requested priority: High

Could you solve this bug. I'm not 100% sure but I think it is on your side. But if not, can you send some snippet that I can use and help me, please. Thanks

**Comment by tomi-msft** [comment]
Hi @AdamSchinzel, thanks for submitting this issue. I am unable to repro the issue in the site. Can you provide more info, and a working codepen example? Thanks! You can use this codepen for a base: https://codepen.io/tomi-msft/pen/qBRLaRd
