### ISSUE TITLE
Datetime: up-arrow should increment year

### ISSUE THREAD

**Issue by wesleyhodgson** [microsoft/fluentui#17785]
#### Describe the feature that you would like added

This is more of a bit of usability feedback, rather than a feature request. I was surprised when I hit the "up" arrow that it decremented the year. It seems as though you've decided that down = next, which may make sense in some situations, but not when interacting with numbers. If you used left/right arrows, where right=next, it would make more sense (at least in my locale), but not up/down.

#### What component or utility would this be added to

The Datetime Picker

#### Have you discussed this feature with our team, and if so, who

No

**Comment by tobybaratta** [comment]
I totally agree with you, but I think the up/down behavior might be something to do with a11y standards of keyboard navigation? https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html - shift and down arrow seem to be used to go to the next year by default

but +1 on it being left and right arrows and not up and down arrows.
