### ISSUE TITLE
Add name optional property to ITheme

### ISSUE THREAD

**Issue by ashwinGokhale** [microsoft/fluentui#17788]
#### Describe the feature that you would like added
I would like to add an optional `name` property to the `Theme` interface. This way we can provide a user defined identifier for each theme.

#### What component or utility would this be added to
This would add an additional `name` property to the [Theme](https://github.com/microsoft/fluentui/blob/master/packages/theme/src/types/Theme.ts) interface.

#### Have you discussed this feature with our team, and if so, who

No.

#### Proposed change:

Before:
```typescript
/**
 * {@docCategory Theme}
 * A prepared (fully expanded) theme object.
 */
export interface Theme extends IScheme {
  /**
   * Component-level styles and token set.
   * This is still in an experimental phase and is only applied by `ThemeProvider`.
   */
  components?: ComponentsStyles;

  /**
   * @internal
   * Id of the theme. This is for internal use only.
   */
  id?: string;

  /**
   * @internal
   * The schemes property is still in an experimental phase. The intent is to have it work
   * in conjunction with new 'schemes' prop that any component making use of Foundation can use.
   * Alternative themes that can be referred to by name.
   */
  schemes?: { [P in ISchemeNames]?: IScheme };
}
```

After:
```typescript
/**
 * {@docCategory Theme}
 * A prepared (fully expanded) theme object.
 */
export interface Theme extends IScheme {
  /**
   * Component-level styles and token set.
   * This is still in an experimental phase and is only applied by `ThemeProvider`.
   */
  components?: ComponentsStyles;

  /**
   * User defined identifier for the theme.
   */
  name?: string;

  /**
   * @internal
   * Id of the theme. This is for internal use only.
   */
  id?: string;

  /**
   * @internal
   * The schemes property is still in an experimental phase. The intent is to have it work
   * in conjunction with new 'schemes' prop that any component making use of Foundation can use.
   * Alternative themes that can be referred to by name.
   */
  schemes?: { [P in ISchemeNames]?: IScheme };
}
```

**Comment by jacksonv1lle** [comment]
@ashwinGokhale What would be the benefit of having a name property? Could you not use the id instead?

**Comment by ashwinGokhale** [comment]
The `id` field specifically says "This is for internal use only." and is not meant to be human readable. As a user, I would like to be able to provide my own name for my themes, like "solarized", "monokai", etc.

**Comment by tomi-msft** [comment]
Hi @ashwinGokhale thanks for submitting the issue! I was wondering if you could provide more information on what the specific use case you would like to use the `name` prop for. My thoughts are that if the name is going to be added to the theme, it should have a programmatic or runtime purpose, and I want to get a better idea of what that is. For instance if it's used to select the theme, wouldn't it be better for there to be a map of themes by name?

**Comment by ashwinGokhale** [comment]
One use case would be for tracking theme usage across an app. For example, the theme selector in ADO:

![image](https://user-images.githubusercontent.com/21692499/116173484-85e1d180-a6c1-11eb-90c6-dc3fdf8de594.png)

Tracking theme usage could look something like this:
```typescript
const theme = useTheme();

useEffect(() => {
    appInsights.trackEvent({
      name: 'themeChange',
      properties: {
        themeName: theme.name
      }
    })

  }, [theme])
```

In this case, you are given a theme and want to get the name from it, so maintaining a map of theme name --> theme would not be very helpful. 

I can create a PR for this feature if it's something you want to go forward with.

**Comment by tomi-msft** [comment]
That makes sense to me, we welcome your contribution!

**Comment by ashwinGokhale** [comment]
@tomi-msft I have created a PR: #18028
