### ISSUE TITLE
@fluentui/react-icons@1.1.118 do not inherit color correctly

### ISSUE THREAD

**Issue by JamesBurnside** [microsoft/fluentui#17804]
The new major version `@fluentui/react-icons` do not color themselves correctly. This is because they use `fill` to set the color instead of `color` and `fill` is not set by theme providers or, for example, buttons.

### Environment Information

- **Package version(s)**: `@fluentui/react-icons@1.1.118`, `@fluentui/react@7.166.2`, `@fluentui/react-theme-provider@0.18.5`

### Please provide a reproduction of the bug in a codepen:

Github repo with working, minimal example code: https://github.com/JamesBurnside/FluentIconColorBug
See https://github.com/JamesBurnside/FluentIconColorBug/blob/main/src/App.tsx for icon usage

#### Actual vs Expected:

Actual Inherited Color (always black) | Expected Inherited Color (matches text color)
-- | --
![image](https://user-images.githubusercontent.com/2684369/114587582-aa0dcf00-9c3a-11eb-9c0a-b07434d0d1b2.png) | ![image](https://user-images.githubusercontent.com/2684369/114587602-af6b1980-9c3a-11eb-93bc-decaf5a40b3c.png)
See the icon is incorrectly always black | See the icon changes based on theme, button being disabled, button being a primary button etc.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected:
* https://github.com/Azure-Samples/communication-services-web-chat-hero
* https://github.com/Azure-Samples/communication-services-web-calling-hero

**Comment by JamesBurnside** [comment]
cc: @tomi-msft

**Comment by anjulgarg** [comment]
Any updates on this ?

**Comment by tomi-msft** [comment]
For now, you can add `primaryFill='currentColor'` to any icons you want to inherit the container color, and that should fix the inheritance problem. I will make an update to the api to have it default to currentColor as a more permanent fix.

**Comment by JamesBurnside** [comment]
> For now, you can add `primaryFill='currentColor'` to any icons you want to inherit the container color, and that should fix the inheritance problem. I will make an update to the api to have it default to currentColor as a more permanent fix.

Thanks @tomi-msft! Confirmed this works as an interim fix:

<table>
<tr>
<td> Code updated with `primaryFill='currentColor'`</td> <td> Result </td>
</tr>
<tr>
<td>

```javascript
// Examples using @fluentui/react-icons v.1.1.118
const NewIconWithText = (): JSX.Element => (
  <div>
    Text before icon&nbsp;
    <Video20Filled primaryFill='currentColor' />
    &nbsp;Text after icon
  </div>
)

const NewIconInPrimaryButton = (): JSX.Element =>
  <PrimaryButton>
    <Video20Filled primaryFill='currentColor' />
    &nbsp;Start Call
  </PrimaryButton>

const NewIconInDisabledButton = (): JSX.Element =>
  <DefaultButton disabled={true}>
    <Video20Filled primaryFill='currentColor' />
    &nbsp;Start Call
  </DefaultButton>
```

</td>
<td>

![image](https://user-images.githubusercontent.com/2684369/118006616-41c91080-b300-11eb-94f4-d06e18ead998.png)

</td>
</tr>
</table>

**Comment by JamesBurnside** [comment]
@tomi-msft several icon components seem to pass the primaryFill prop directly onto html elements like `span` causing react to spew errors:
![image](https://user-images.githubusercontent.com/2684369/125488525-a64b63ec-9ca4-4967-a207-a56094801d1d.png)
![image](https://user-images.githubusercontent.com/2684369/125489267-6f002a0c-da69-4854-864f-7881791523aa.png)

Is there any work for a fix without having to use `primaryFill='currentColor'` here?

Further details:
rendered dom:
![image](https://user-images.githubusercontent.com/2684369/125489505-a0dc2a9d-f67c-4a8a-8ce7-ee3f3c6f83cc.png)
code snippet:
![image](https://user-images.githubusercontent.com/2684369/125489656-e43316a0-d767-452f-837d-bdc465244149.png)

**Comment by JamesBurnside** [comment]
Wondering if there is any update on this?

**Comment by tomi-msft** [comment]
This issue should be addressed in the latest update of the react-icons package

**Comment by JamesBurnside** [comment]
Oh nice! Looks like the package hasn't been published with the change yet - do you know when the next package release is?

**Comment by tomi-msft** [comment]
It should be published tomorrow
