### ISSUE TITLE
Possibility to enable drag&drop in PeoplePicker to allow to change the order of the contacts.

### ISSUE THREAD

**Issue by murcinar** [microsoft/fluentui#17816]
#### Describe the feature that you would like added
Possibility to enable drag&drop in PeoplePicker to allow to change the order of the contacts.

#### What component or utility would this be added to
PeoplePicker

**Comment by tomi-msft** [comment]
Hello @murcinar, thanks for filing the issue! I think we spoke about this, were you able to come up with something that works for you?

**Comment by murcinar** [comment]
Hi @tomi-msft, not the drag&drop functionality to reorder items. It would be great if drag&drop can be enabled on people picker controls.
