### ISSUE TITLE
Fluent UI React Icons Tab Focus

### ISSUE THREAD

**Issue by marc-hayek** [microsoft/fluentui#17861]
### Environment Information

- **Package version(s)**: "@fluentui/react-icons-mdl2": "^1.0.3",
- **Browser and OS versions**: IE10 and IE11

### Describe the issue:

The SVG icons in the react-icons-mdl2 package don't have the "focusable" attribute set to false, which causes the tab focus to jump to the icons on IE10 and IE11 and confusing keyboard users.

Just as example of the UI, this link won't open on IE10 or IE11
https://codesandbox.io/s/microsoftfluentui-codesandbox-react-template-forked-ierof?file=/src/index.tsx

On IE10 and IE11, if you tab through the items, it will focus on button1->icon->button2 instead of button1->button2 as expected and how it works on newer browsers.

#### Actual behavior:

SVG Icons get selected on Tab

#### Expected behavior:

SVG Icons should be skipped when tabbing through the document by having the "focuasble" attribute set to "false"

### Documentation describing expected behavior
https://stackoverflow.com/questions/18646111/disable-onfocus-event-for-svg-element

**Comment by marc-hayek** [comment]
Hi, is there any progress on this? We have an app that we need to deploy in the next few weeks and this is an accessibility blocker. The fix is pretty simple, which is just adding that attribute to the SVG elements. I assume there's a generator somewhere for creating all the icons and it wouldn't have to be done manually for all the files correct? If yes, I can submit a PR to fix the issue if you can point me in the right direction.

Thanks

**Comment by tomi-msft** [comment]
Hi @marc-hayek, apologies for the late reply. Unfortunately there isn't a generator for the svg files. They were probably pulled from IconCloud , and then wrapped in the react function component that are used in the react-icons-mdl2 package. 

There is a tool called svgr that can be used to add and remove attributes from svgs, but that work would entail redownloading all the svgs, running the raw svgs through svgr, then recreating the react-icons-mdl2 package with the new svgs.

Probably the best solution is to manually set the `focusable` attribute to false for all the Icons in that package. I will work on a script that can automate the switch, and get a PR out

**Comment by marc-hayek** [comment]
That would be great, thanks a lot!
