### ISSUE TITLE
mergeStyleSets are not working with Next.js SSR

### ISSUE THREAD

**Issue by sarioglu** [microsoft/fluentui#17871]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^8.11.1"

### Please provide a reproduction of the bug in a codepen:
Refer to https://github.com/sarioglu/fluentui-ssr-example for an example reproduction.

Here are the other related issues:
https://github.com/microsoft/fluentui/issues/16044
https://github.com/microsoft/fluentui/issues/11411
https://github.com/microsoft/fluentui/issues/3692

#### Actual behavior:
I have followed the instructions given at https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing to support server-side rendering using fluent-ui. It could gather the default styles and the ones that I've created manually but not the ones created using `mergeStyleSets`.

#### Expected behavior:
All the styles should be in SSR output.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

<img width="574" alt="image" src="https://user-images.githubusercontent.com/7019371/115429786-699aec00-a20c-11eb-8819-d7f3f60a1b07.png">

**Comment by ecraig12345** [comment]
@dzearing any ideas here?

**Comment by gouttierre** [comment]
@sarioglu - thanks for reaching out and the background context around the issue. 

@dzearing - any updates on this one?
cc @miroslavstastny

**Comment by sarioglu** [comment]
@gouttierre , @dzearing thank you for your response. To solve that, I've started to call `mergeStyleSets` in render function as it is advised here: https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/README.md#optimizing-for-performance But I'm still not sure if calling it on every render is the correct way.
