### ISSUE TITLE
'Export to CodePen' are not working properly on fluentui#/controls/web 

### ISSUE THREAD

**Issue by neinatu** [microsoft/fluentui#17909]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
Open [fluentui#/controls/web/button](https://developer.microsoft.com/en-us/fluentui#/controls/web/button) and click any 'Export to CodePen' link, a new CodePen tab opens but always fails to render.
![Screen Shot 2021-04-21 at 6 37 02 PM](https://user-images.githubusercontent.com/5346292/115598691-96b1d200-a2d2-11eb-86c8-e15620653a46.png)

#### Actual behavior:

Blank page rendered in codepen

#### Expected behavior:

Fluent UI controls render in codepen

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: https://developer.microsoft.com/en-us/fluentui#/controls/web

**Comment by tomi-msft** [comment]
Hi @neinatu, thanks for filing the issue. This issue was because we were still exporting fluent v7 and react-hooks v7 for our v8 component examples. It was fixed in this PR: https://github.com/microsoft/fluentui/pull/17929
