### ISSUE TITLE
In DatePicker, Tooltip of previous and next month buttons gets disappeared on receiving key focus hover.

### ISSUE THREAD

**Issue by llcdefgab** [microsoft/fluentui#17919]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

![image](https://user-images.githubusercontent.com/6523853/115718438-b0741780-a3ad-11eb-85e5-5a35af13542b.png)

#### Expected behavior:

The tooltip is better to use fluent ui tooltip:
https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip
Then mouse can move to the tooltip, and the tooltip can also show when use keyboard navigation

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by llcdefgab** [comment]
@tomi-msft Could you please help to take a look at this bug? Is there any plan to fix the issue? Thank you

**Comment by tomi-msft** [comment]
Hi @llcdefgab, thanks for filing the issue! I do see that a Tooltip is not rendered when using keyboard navigation. My concern with adding a custom tooltip to the navigation is it would potentially be a situation where adding a custom tooltip with keyboard support would solve one issue, but many people are still going to be left out.

There's pretty much no way to create tooltips that support people who rely on voice control, eye gaze, a switch emulating a mouse, or someone on a touchscreen. 

That being said, we absolutely welcome contributions to the repo, and would be more than happy to hear any ideas you have that would solve this issue!
