### ISSUE TITLE
onDismiss of Panel is still being invoked when panel is dismissed and using isHiddenOnDismiss=true

### ISSUE THREAD

**Issue by MichaelRechenberg** [microsoft/fluentui#17931]
### Environment Information

- **Package version(s)**: (8.11.2)
- **Browser and OS versions**: (Edge 90.0.818.41, Windows 10)

### Please provide a reproduction of the bug in a codepen:

I don't have a CodePen account, but I reproduced this on the Fluent website https://developer.microsoft.com/en-us/fluentui#/controls/web/panel.  I used the "Hidden on dismiss" example and only edited the onDismiss function to have a console.log

```
onDismiss={
    () => {
         console.log("onDismiss called");
         dismissPanel();
    }
}
```

#### Actual behavior:

When the panel is dismissed (and hidden) and I hit the Escape key, the onDismiss callback is still invoked.  In my example, the string is logged to the console

#### Expected behavior:

Since the panel is not visible on the screen anymore, hitting Escape should not be invoking any callback I've defined on the panel.

If isHiddenOnDismiss=false, this does NOT reproduce.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: (if applicable)

**Comment by MichaelRechenberg** [comment]
I'd also ask that if this bug is triaged and devs are assigned to it, that any bugfix be put on the v7.x release as well

**Comment by tomi-msft** [comment]
Hi @MichaelRechenberg ,thanks for submitting the issue. I can confirm that this is a bug and am putting out a fix. I will also make sure to cherrypick this into v7.
