### ISSUE TITLE
dependency issues with quickstart init

### ISSUE THREAD

**Issue by Ray-B** [microsoft/fluentui#17945]
Hi, following the quickstart guide for the recently released v8.x of fluent-ui I noticed there are a number of dependency warnings, including 4 security vulnerabilities (low) for the just-scripts version utilized:

![not_quite3](https://user-images.githubusercontent.com/1775483/115940950-9a735f00-a460-11eb-84e6-0fb4112aa8f3.jpg)

I also found that the quickstart init seems to completely fall over on Node Current, which I documented below in case it is useful. I understand the doc says LTS, but it would be nice if this wasn't stuck on LTS because of dependencies (FWIW I did not test on 15.x)

Under Node 16:

Following the guide: https://github.com/microsoft/fluentui/blob/master/apps/public-docsite/src/pages/Overviews/GetStartedPage/docs/web/GetStartedDevelopSimple.md

and running: 
`npm init uifabric` 

Causes an incomplete / non-functional install when python 2 is missing:

![kaboom](https://user-images.githubusercontent.com/1775483/115940084-88dc8800-a45d-11eb-9aac-34f5d49f7eef.jpg)

This looks like it might be a result of a dependency of node-sass which relies on node-gyp which relies on python2, which, if not installed (why would it be?), will cause an incomplete install. 

Additionally, _just_ appears to also incorrectly report the init to have _succeeded_: 

![not_quite1](https://user-images.githubusercontent.com/1775483/115940105-972aa400-a45d-11eb-969a-603025c82503.jpg)

but it appears to be incomplete

![not_quite2](https://user-images.githubusercontent.com/1775483/115940296-2d5eca00-a45e-11eb-8325-5f5343add8d3.jpg)

### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**:  N/A

### Please provide a reproduction of the bug in a codepen:

N/A

#### Actual behavior:

See above.

#### Expected behavior:

- Mandatory extraneous dependencies should be documented
- _Just_-based init script should signal to a consumer in scenarios where npm dependency installs fail.
- No python dependency would be preferable.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Sure?

Requested priority: (Blocking, High, Normal, Low)

Normal. Doesn't seem desirable for init process to be lagging with its deps and only working with LTS (if that is in fact the case)

Products/sites affected: (if applicable)

N/A

**Comment by ecraig12345** [comment]
That template isn't being maintained, so we need to remove it from the website. The best way to get started right now is using our Create React App template: `npx create-react-app my-app --template @fluentui/cra-template`.
