### ISSUE TITLE
Controls in react northstar  fluent ui show  blue border

### ISSUE THREAD

**Issue by harshdamaniahd** [microsoft/fluentui#17946]
Hi,
I have created an SPFX webpart using react northstar and deployed it to teams app store.
I am using react northstar library and for all controls I am seeing  this blue order in  android and ios phones.
![Image (1)](https://user-images.githubusercontent.com/11780473/115961718-e6cda600-a517-11eb-81ef-acba1edaeb52.jpeg)
![Image](https://user-images.githubusercontent.com/11780473/115961719-e7fed300-a517-11eb-85d0-efb1177c194b.jpeg)

**Comment by jurokapsiar** [comment]
Hi @harshdamaniahd can you please provide codesandbox that replicates the problem or point us to what class is being applied? There might be some global focus higlighter in your environment.

**Comment by harshdamaniahd** [comment]
I have deployed it as microsoft teams app, its inside microsoft teams application in anroid and ios. It works fine in web, but not working in android and ios

**Comment by gouttierre** [comment]
@harshdamaniahd - Are you still facing this problem? If so, you’ll need to add a CodePen repro before we can help further. Thanks!
