### ISSUE TITLE
Card component in northstar is styled with height:100% 

### ISSUE THREAD

**Issue by hund030** [microsoft/fluentui#17952]
### Environment Information

- **Package version(s)**: "@fluentui/react-northstar": "^0.54.0",
- **Browser and OS versions**: Microsoft Edge Version 90.0.818.41 (Official build) (64-bit), 

#### Actual behavior:

Add below codes in my app the Card component is added a class `ea` by default, which force the card to keep its height with the browser size.
```
 <Card aria-roledescription="card with avatar, image and action buttons">
          <Card.Header>
            <Skeleton animation="wave">
              <Flex gap="gap.small">
                <Skeleton.Shape round width="32px" height="32px" />
                <div>
                  <Skeleton.Line width="200px" />
                  <Skeleton.Line width="150px" />
                </div>
              </Flex>
            </Skeleton>
          </Card.Header>
        </Card>
```
![image](https://user-images.githubusercontent.com/26134943/116053491-54f7a180-a6ad-11eb-905d-e8a0714f4eaf.png)
![image](https://user-images.githubusercontent.com/26134943/116053521-5de87300-a6ad-11eb-9114-bfb09cfd3bc3.png)
So long it is!
![image](https://user-images.githubusercontent.com/26134943/116053404-3abdc380-a6ad-11eb-8f3d-0a2052fa93d5.png)

#### Expected behavior:

Expected it looks like what [tutorial ](https://fluentsite.z22.web.core.windows.net/0.54.0/components/skeleton/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#usage-card)shows.
![image](https://user-images.githubusercontent.com/26134943/116053956-c899ae80-a6ad-11eb-96f9-efc2bbfa59e0.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low
I can workaround by adding extra css to limit the height, but I hope you can fix it if it's a bug.

**Comment by gouttierre** [comment]
@hund030 - Thank you for the information to the issue you are experiencing.
@kolaps33 - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by axhl** [comment]
Any progress on this? I'm experiencing the same `height: 100%`-issue when using `<Card>` in `0.56.0` in Chrome. Thank you for investigating.
