### ISSUE TITLE
VerticalStackedBarChart- Callout is appearing on alternate bars using arrow keys

### ISSUE THREAD

**Issue by ms-khgo** [microsoft/fluentui#17953]
### Environment Information

- **Package version(s)**: 4.15.16
- **Browser and OS versions**: Microsoft Edge, Windows 10

#### Actual behavior:

On using left and right arrow keys on VerticalStackedBarChart, the callout is appearing on alternate bars.

https://user-images.githubusercontent.com/81736144/116053709-9a5da400-a698-11eb-894a-4ee47c1a93a5.mp4

#### Expected behavior:

The callout should appear on every bar on VerticalStackedBarChart by using left or right arrow keys.

https://user-images.githubusercontent.com/81736144/116053755-a6e1fc80-a698-11eb-9a98-f6e3a5de34f7.mp4

**Comment by gouttierre** [comment]
@ms-khgo - thanks for reaching out.

@Raghurk - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by mbest** [comment]
It is a regression. The "before:" above is using version 4.13.0

**Comment by Raghurk** [comment]
Will look into this.

**Comment by mbest** [comment]
@Raghurk Is it fixed with #19178?

**Comment by Raghurk** [comment]
Yes
