### ISSUE TITLE
Semantic colors not respected by checked Toggle react-buttons

### ISSUE THREAD

**Issue by imdavidmin** [microsoft/fluentui#17988]
### Environment Information

- **Package version(s)**: 8 (react-button 0.19.6)

### Please provide a reproduction of the bug in a codepen:

```
const btnGroupTheme: PartialTheme = {
    semanticColors: {
        primaryButtonBackgroundHovered: 'pink',
        primaryButtonBackgroundChecked: 'green',
        primaryButtonBackgroundPressed: 'red',
        buttonBackgroundCheckedHovered: 'cyan',
        buttonBackgroundHovered: 'purple',
        buttonBackgroundChecked: 'green',
        buttonBackgroundPressed: 'red'
    }
}
...
                    <ToggleButton checked={false} >testing</ToggleButton>
                    <ToggleButton checked={true} >testing</ToggleButton>
                    <ToggleButton checked={false} primary>testing</ToggleButton>
                    <ToggleButton checked={true} primary>testing</ToggleButton>

```
#### Actual behavior:
![image](https://user-images.githubusercontent.com/48481563/116434420-4e4e6300-a842-11eb-9a03-aed697edb340.png)

#### Expected behavior:
Checked vs Pressed -> currently for both primary and regular, the checked state takes pressed value. 
CheckedHovered not implemented and PressedHovered doesn't exist.

This issue was previously fixed in #16597, but the affected file was since removed.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by ecraig12345** [comment]
For various reasons, `@fluentui/react-button` has been moved back to "dev" status and is not included in the version 8 release or officially supported for the moment. This is mentioned in the latest [release notes](https://github.com/microsoft/fluentui/wiki/Version-8-release-notes#in-preview-improved-button), with a few more details explained [here](https://github.com/microsoft/fluentui/issues/12770#issuecomment-776389207). So unfortunately we're not going to fix this right now.

**Comment by imdavidmin** [comment]
What does being in dev status mean? I was wondering about the future for the package [here](https://github.com/microsoft/fluentui/discussions/17949)

**Comment by ecraig12345** [comment]
Basically that it's gone back to alpha (or pre-alpha) status and shouldn't be used externally. Sorry nobody has gotten back to you on that discussion question; I'll get someone to follow up there and provide more details.
