### ISSUE TITLE
Broken link: IStyle

### ISSUE THREAD

**Issue by sthigale-m** [microsoft/fluentui#17995]
### Please provide a reproduction of the bug in a codepen:
Go to this page: https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker#IDatePickerStyles

![image](https://user-images.githubusercontent.com/73924391/116546816-b5861900-a90f-11eb-92f2-105b3a5d96a6.png)

Click on the IStyle link. It tries to open https://developer.microsoft.com/en-us/fluentui#/controls/web/references/istyle#IStyle, but its broken.

![image](https://user-images.githubusercontent.com/73924391/116546926-dc444f80-a90f-11eb-99f6-870567b804e2.png)

**Comment by ecraig12345** [comment]
Thanks for reporting this! IStyle is supposed to be under a "References" section, which has gone missing from the version 8 website. I'll look into why that happened.
