### ISSUE TITLE
Slider control is not following 'Pointer Cancellation' guideline

### ISSUE THREAD

**Issue by Oluchukwu96** [microsoft/fluentui#17999]
### Environment Information

- **Package version(s)**: 7.168.2
- **Browser and OS versions**: Chrome

### Describe the issue:

The slider value can be adjusted even when the mouse pointer is not hovering over it.

### Please provide a reproduction of the issue in a codepen:

The issue can be reproduced in the slider demo
[fluent ui slider demo](https://developer.microsoft.com/en-us/fluentui#/controls/web/slider)

#### Actual behavior:

The slider value continues to be updated when the mouse pointer is drag out of focus of the slider component. 

#### Expected behavior:

The slider value should not be updated when the pointer goes out of focus from the slider component.

### Documentation describing expected behavior

 [Exploring WCAG 2.1 — 2.5.2 Pointer Cancellation – Knowbility](https://knowbility.org/blog/2018/WCAG21-252PointerCancellation/?gclid=EAIaIQobChMI-Ku18qqk8AIV8QWICR1UjgcoEAAYASAAEgLutvD_BwE)

**Comment by JustSlone** [comment]
As I recall this is intentional as the target area of the slider is too small and this would lead to a very frustrating control to use. I will defer to @smhigley for an expert opinion though.
