### ISSUE TITLE
Cannot change background color of DatePicker

### ISSUE THREAD

**Issue by sthigale-m** [microsoft/fluentui#18003]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
`<DatePicker styles={{callout: {backgroundColor: "#ff0000"}}} placeholder="Select a date..." ariaLabel="Select a date" />`

Note that background color does not change of the callout
![image](https://user-images.githubusercontent.com/73924391/116671450-92667280-a9be-11eb-9fec-102d25084a1c.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: yes

**Comment by JustSlone** [comment]
If you use calloutProps passed into DatePicker you can set the style for calloutMain which controls the background of the callout.

Here's an example: https://codepen.io/justslone-the-encoder/pen/WNpNBwq?editors=1010

```jsx
const calloutProps: ICalloutProps = {
  styles: {
    calloutMain: {
      backgroundColor: "#ff0000"
    }
  }
};

<DatePicker
  firstDayOfWeek={firstDayOfWeek}
  calloutProps={calloutProps}
  placeholder="Select a date..."
  ariaLabel="Select a date"
/>
```
