### ISSUE TITLE
React-button aria labels for accessibility.

### ISSUE THREAD

**Issue by imdavidmin** [microsoft/fluentui#18019]
#### Describe the feature that you would like added

The ability to add an aria label to buttons, either through ButtonProps or passed as a token (ButtonToken type)

#### What component or utility would this be added to

react-button

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Would not pass accessibility rules otherwise, not aware of a present way to do this. This is present in the old button, as iButtonProps

**Comment by ecraig12345** [comment]
As mentioned in #17988, the version of react-button you're using is no longer supported, and we're entirely rewriting it with a different approach moving forward. For now you should continue to use the old Button.
