### ISSUE TITLE
SearchBox return `undefined` as the underlying input event

### ISSUE THREAD

**Issue by chuanqisun** [microsoft/fluentui#18021]
### Environment Information

- **Package version(s)**: lastest v8 from unpkg
- **Browser and OS versions**: edge

#### Actual behavior:

`undefined` was returned as the parameter of the `onChange` callback
![image](https://user-images.githubusercontent.com/1895289/116941308-4caae380-ac24-11eb-9812-e39515a1183b.png)

#### Expected behavior:

the underlying input event should be returned

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking (this is a regression because it previously worked)

Products/sites affected: https://hits.microsoft.com

**Comment by ecraig12345** [comment]
Thanks for reporting this and for the repro! We'll investigate this and get a fix out soon.
