### ISSUE TITLE
Option to handle nav state

### ISSUE THREAD

**Issue by ankitakash2007** [microsoft/fluentui#18035]
#### Describe the feature that you would like added

In nav there is no way to change current state to expanded or collapsed state. Can we add a prop that controls isExpanded for the overall navgroup.

#### What component or utility would this be added to

Nav - Web

#### Additional context/screenshots

![8aa70ed4-1c41-4213-9ba6-cd179fa497fd](https://user-images.githubusercontent.com/6673219/116987699-01a8d300-aced-11eb-88fc-d4849a60845a.jpg)

We have a use case where we have a list of staff (in a sidebar) as a nav and we have to code the behavior that clicking search when a list is collapsed, should expand the nav, in case its already expanded it should remain expanded. For this either we have to programmatically control nav's expanded state or get a way to access its current state.

**Comment by ecraig12345** [comment]
Do you mean the Nav from `@fluentui/react`, or a different package? `INavLinkGroup` from `@fluentui/react` already has a prop `collapseByDefault` which sort of handles this, though I agree the naming could be better.

**Comment by ankitakash2007** [comment]
Yeah, I am referring to the nav from @fluentui/react only. But Elizabeth, collapseByDefault only sets the initial state. This wont serve the purpose. We need a way to trigger the menu to move away from collapsed whenever search is clicked.

**Comment by TristanWatanabe** [comment]
@ankitakash2007: Unless I'm just not understanding the use case you're describing; it seems like you can use `collapseByDefault` prop to continually manipulate the collapsed/expanded state of the `Nav`. Here's a codepen that demonstrates this: https://codepen.io/tristanwatanabe/pen/qBrXZad

**Comment by ecraig12345** [comment]
It's very weird (and arguably wrong) that changes to `collapseByDefault` are respected. I also noticed that it stops working if you manually expand or collapse the group. This is what the code is currently doing:
https://github.com/microsoft/fluentui/blob/918d2a8403d0bcb969aaec1eaffd87e031102efb/packages/react/src/components/Nav/Nav.base.tsx#L388-L394

It might make sense to add a property `isCollapsed` to `INavLinkGroup` which takes precedence over either of the conditions above. This would put the expanded/collapsed state in a "controlled" mode where the component consumer would also have to manually handle updates by implementing `INavLinkGroup.onHeaderClick`. (Controlled/uncontrolled is a standard React pattern--I tried to explain it in [this gist](https://gist.github.com/ecraig12345/1ea4566ce171b844a0af5a3366d3473f) but you can also find other explanations online.)

**Comment by smhigley** [comment]
@ecraig12345 I just took a trip down the Nav rabbit hole, and it gets even weirder. For the expanded state on `INavLink` (not `INavGroupLink`), we're actually _directly mutating isExpanded on the groups object passed in through props_ 😱:
https://github.com/microsoft/fluentui/blob/918d2a8403d0bcb969aaec1eaffd87e031102efb/packages/react/src/components/Nav/Nav.base.tsx#L301-L305

So the component is always internally fighting the author for control over a link's expanded state. An author can prevent us from mutating that object by calling `event.preventDefault()` in the click handler and then update the groups object themselves, but it still seems super shady :P

**Comment by livthomas** [comment]
I would also appreciate this feature. My use case is very simple. When a group is expanded, I need to collapse all other groups.
