### ISSUE TITLE
SPFX React Control- FilePicker

### ISSUE THREAD

**Issue by Abhijeet1719** [microsoft/fluentui#18030]
I want to add Custom Link  in File Picker control (using spfx react) in SharePoint Modern Ui. Now we are able to see below options
"Recent files - tab allows selecting a file from recently modified files based on the search results.
Web search - tab uses Bing cognitive services to look for a file. (Only images)
OneDrive - tab allows selecting a file from the user's One Drive.
Site document libraries - tab allows selecting a file from the existing site document libraries.
Upload - tab allows uploading a file from a local drive.
From a link - tab allows pasting a link to the document."
Is it possible to add subsite name in above navigation.

![image](https://user-images.githubusercontent.com/65273665/116968229-b33a0b00-acd1-11eb-96b0-d4df4d6ca00a.png)

**Comment by ecraig12345** [comment]
This sounds like a problem with SPFx, not Fluent UI. You can try asking at https://github.com/SharePoint/sp-dev-docs instead.

**Comment by Abhijeet1719** [comment]
This is not an issue. I want to develop custom solution for this where I want to add some custom link in that SharePoint FIle Picker control

**Comment by ecraig12345** [comment]
Either way, this is not the right place to ask for help with that scenario. Please try the SPFx repo I linked above or some other SPFx forum.
