### ISSUE TITLE
Dropdown scrolls if cursor moves around either end of the menu

### ISSUE THREAD

**Issue by MSJohnnyLee** [microsoft/fluentui#18047]
### Environment Information

- **Package version(s)**: 7.110.5 but reproduces with the latest version as well

### Describe the issue:

When the Dropdown component is scrollable, the menu will begin to scroll if the user moves their cursor near the vertical extremities of the menu. Please contact me on Teams if you need additional clarification, thanks!

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluent-ui-demo-forked-8z4ml?file=/src/App.js

#### Actual behavior:

https://media.giphy.com/media/PG5tm1waZtoDcCk1PG/giphy.gif

#### Expected behavior:

The menu should not scroll when the user moves their cursor near either ends of the menu.

**Comment by hetanthakkar1** [comment]
@TristanWatanabe @ecraig12345 I want to work on this

**Comment by kpasagada** [comment]
I am able to see this behavior with Fluent dropdowns. Is there an ETA for this fix? Also, is there a workaround for this issue?

**Comment by ecraig12345** [comment]
I'm pretty sure this is intentional, to mimic the built-in scrolling behavior of dropdowns and menus. It's behaved this way even back to Fabric 6, and the built-in select element has a similar behavior.
https://codepen.io/ecraig12345/pen/VwWpBpx?editors=0010

**Comment by kpasagada** [comment]
I am not sure why this was closed - I still see this issue in Fluent UI v7 dropdowns.

**Comment by sapang007** [comment]
following

**Comment by ecraig12345** [comment]
@kpasagada It's intentional. Please see my comment above.

**Comment by kpasagada** [comment]
@ecraig12345 I understand the auto scroll behavior is expected when I move my mouse to either ends of the dropdown menu.
However, there are times when the dropdown scrolls randomly and jumps all over the place even though I have not moved my mouse to either end of the dropdown menu. Refer to the video below to observe this behavior.

Also, I do not observe this behavior in HTML dropdowns (using <select>/<option> in the same codepen - https://codepen.io/ecraig12345/pen/VwWpBpx?editors=0010).

https://user-images.githubusercontent.com/42693353/135371652-9175dfec-29f7-4e84-9cd3-81c03491db0a.mp4
