### ISSUE TITLE
The ability to specify ID's to children components within the Dialog Component

### ISSUE THREAD

**Issue by charlyecastro** [microsoft/fluentui#18045]
#### Describe the feature that you would like added

A prop or the ability to add specific ID's to the confirm button and cancel button within the Dialog Component

#### What component or utility would this be added to

Dialog

#### Have you discussed this feature with our team, and if so, who

Nope

#### Additional context/screenshots

I am writing E2E tests and we need some form of id property to add to the elements in order to automate interaction with the dialog and its children components. Currently, **confirmButton** and **cancelButton** only take Strings and we would like to add more than that. Thanks!

![image](https://user-images.githubusercontent.com/24886389/117070201-45e2a600-ace2-11eb-9ff5-7350a9159f2f.png)

**Comment by charlyecastro** [comment]
@TristanWatanabe: this would be for `@fluentui/react-northstar`

**Comment by jurokapsiar** [comment]
Hi, this is possible using shorthand props: https://fluentsite.z22.web.core.windows.net/0.55.0/shorthand-props

```
  <Dialog
    cancelButton={{ content: "Cancel", id: "cancel-id" }}
```
