### ISSUE TITLE
Code for prototype

### ISSUE THREAD

**Issue by 1nfinite** [microsoft/fluentui#18054]
I would like to have code for prototype. Where can i find that?

https://fluentsite.z22.web.core.windows.net/0.54.0/prototype-table

**Comment by ecraig12345** [comment]
The code is here: https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-northstar-prototypes/src/prototypes/table

In general, if you want to find a particular file in a repo, some ways to do this are:
- Navigate to the repo homepage, press `T`, and start typing parts of the filename
- Use the search box in the top left
