### ISSUE TITLE
User can navigate from MenuButton inside of a table cell to other cells without closing the menu

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#18067]
### Environment Information

- **Package version(s)**: 0.54
- **Browser and OS versions**: all

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/fluent-ui-example-forked-836py?file=/example.js
(without usage of ignoreArrowKeys)

#### Actual behavior:

When menu is open, user can navigate to other cells by pressing left/right arrow keys
#### Expected behavior:

Left/right arrows do not have any effect (unless there is a submenu)

### Priorities and help requested:

Are you willing to submit a PR to fix?

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by jurokapsiar** [comment]
to verify after implementing a fix: user need to be able to  use left/right arrows to go to a different column in the table row after the menu close is closed.

**Comment by hetanthakkar1** [comment]
@jurokapsiar Working on it! Will soon make a PR
