### ISSUE TITLE
React-northstar Datepicker - current day indicator contrast

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#18077]
Contrast of the datepicker today indicator is insufficient:
![image](https://user-images.githubusercontent.com/13742664/117249254-8f95d280-ae41-11eb-83f4-99dfd99dadb4.png)

update the background color of the circle to Brand Background.

![image](https://user-images.githubusercontent.com/13742664/117249319-adfbce00-ae41-11eb-88b6-e8182a677454.png)

### Environment Information

- **Package version(s)**: 0.55
- **Browser and OS versions**: all

**Comment by gouttierre** [comment]
@kolaps33 - Would you be able to confirm if we are using Brand Background color for the indicator?
