### ISSUE TITLE
Ambiguous thrown error `componentRef` of undefined

### ISSUE THREAD

**Issue by islegare** [microsoft/fluentui#18084]
### Environment Information

- **Package version(s)**: 7.117.0
- **Browser and OS versions**: 

### Please provide a reproduction of the bug in a codepen:
Can't reproduce exception.

#### Actual behavior:

The following error occurs very infrequently in our production systems: 

TypeError: Cannot read property 'componentRef' of undefined
    at componentRef (../../src/initializeComponentRef.ts:24:16)
    at ../../src/appendFunction.ts:13:48
    at forEach (../../src/appendFunction.ts:13:14)
    at componentDidUpdate (../../../node_modules/react-dom/cjs/react-dom.production.min.js:251:462)
    at b (../../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js:18:436)
    at Lf (../../../node_modules/react-dom/cjs/react-dom.production.min.js:120:324)
    at fg (../../../node_modules/react-dom/cjs/react-dom.production.min.js:244:436)
    at Yj (../../../node_modules/react-dom/cjs/react-dom.production.min.js:223:419)
    at ../../../node_modules/react-dom/cjs/react-dom.production.min.js:121:114

#### Expected behavior:

An avoidance of the error, or some way to better root cause the issue.  

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

On the page in which this error occurs we have various fabric components in use, this makes it very difficult to root cause the underlying issue. Having some way to identify the component in question, or some way of having an idea in which we can more easily root cause the issue would greatly be appreciated.  In our investigation we looked through the components that we use componentRef's with (ComboBox, and TooltipHost).  Neither of which seemed to have an example in which the `props` would be undefined to trigger this failure.

**Comment by TristanWatanabe** [comment]
@islegare: Can you please provide more repro details, ideally a codesandbox (start from https://aka.ms/fluentsandbox)? There's currently not enough information provided to troubleshoot.

**Comment by islegare** [comment]
@TristanWatanbe , that's really the root of the issue.  I'm unable to reproduce, and based solely on the error messages am unable to determine which of the various components are causing this error.  I think my main ask would be to improve error handling in initializeComponentRef.ts, so that in the future if it reoccurs I can better tell where the error came from.

**Comment by islegare** [comment]
@TristanWatanabe , any opinion on the handling of the exception to make it easier to determine which component the error traces to?

**Comment by wamoha** [comment]
It seems the `componentRef `isn't set and the `_onMount `is invoked on `initializeComponentRef`.

Am not sure about the error handling patterns in your code base, but I think something like below would be helpful for troubleshooting runtime errors.

```
function _onMount() {
    if (!this.props.componentRef) {
        throw new Error('... error details and stack trace');
    }
    _setComponentRef(this.props.componentRef, this);
}
```

**Comment by ecraig12345** [comment]
The issue appears to be that `this.props` is undefined, not that `this.props.componentRef` is undefined. You might be able to do something like this:

```ts
if (!this.props) {
  throw new Error(`this.props is undefined in initializeComponentRef for ${this.displayName || this.name}`)
}
```

**Comment by TristanWatanabe** [comment]
The fix didn't work out like we intended due to various issues that would have resulted in an unhelpful error message at the end. Any other alternative would cause too drastic of a change to the codebase so unfortunately we've decided not to move forward with that and just close this instead.
