### ISSUE TITLE
How to  show ColorPicker on click of SwatchColorPicker

### ISSUE THREAD

**Issue by Shraddha-113** [microsoft/fluentui#18089]
In our code, we are using multiple SwatchColorPicker. And I want to open ColorPicker by clicking on particular SwatchColorPicker and also want to set color as respected  to SwatchColorPicker. How can I achieve this for multiple SwatchColorPicker???
![colorpicker](https://user-images.githubusercontent.com/74581836/117352840-15129480-aecd-11eb-999b-88e785f83300.png)

**Comment by TristanWatanabe** [comment]
Closing this as it's not an issue. Please make use of the Discussions section for questions like these.
