### ISSUE TITLE
'OnFocusedCell' event in SwatchColorPicker working frequently

### ISSUE THREAD

**Issue by Shraddha-113** [microsoft/fluentui#18090]
I am using multiple SwatchColorPicker in Code. By clicking on SwatchColorPicker, I am trying to open ColorPicker and set the color as respective to selected SwatchColorPicker. But somehow 'onFocusedCell' event is not working properly. 

When I clicked on SwatchColorPicker for first time ColorPicker blink i.e. it get opened and disappears within a second. Then I again trying to clicked on the same doesn't happens anything. After clicking SwatchColorPicker, sometimes shows ColorPicker and sometime doesn't.

By reviewing above issue, is there any issue in SwatchColorPicker or in Code?
![swatchcolor](https://user-images.githubusercontent.com/74581836/117355583-6a03da00-aed0-11eb-8738-2b14f846cc43.png)

**Comment by TristanWatanabe** [comment]
@Shraddha-113: Can you provide a codepen/codesandbox repro of the issue you're seeing?
