### ISSUE TITLE
DatePicker: Theme not applied to Focus Outline Border Color

### ISSUE THREAD

**Issue by swasun99** [microsoft/fluentui#18109]
### Environment Information

- **Package version(s)**: 8.14.4
- **Browser and OS versions**: New Edge

Hi Fluent Team

We use the DatePicker control in our application and we pass a theme as to the control to be able to style it as per our application theme, however we notice the below behavior that is unexpected.

#### Actual behavior:

When a theme is passed to the DatePicker, the border outline color on focus (after a date is selected in the calendar and collapsed) still stays blue.

#### Expected behavior:

The theme color should be applied to the border outline color on focus for the DatePicker

**Comment by TristanWatanabe** [comment]
@swasun99: I’m not super familiar with this myself but from looking at it, the focus border style is determined by the ‘TextField’ component. ‘DatePicker’ accepts a ‘textField’ prop that you can use to pass in your own custom ‘theme’ for your application. In theory, this should give you the custom border outline that you are looking for.

**Comment by swasun99** [comment]
Thats right, have tried the same using the below snippet. Have tried to set the color on focus, however, it doesn't work. It doesn't let the color to be overridden, while it does allow the background color to be changed.

const datePickerStyles: Partial<IDatePickerStyles> = {
  textField: {
    selectors: {
      input: { backgroundColor: "white", borderColor: "red" },
      label: { backgroundColor: "lightblue", fontSize: 30 },
      focus: { backgroundColor: "red", borderColor: "green" }
    }
  }
};

**Comment by TristanWatanabe** [comment]
Hey @swasun99, I've made a quick codepen that demonstrates how you can customize the `TextField`'s focus border by using the `textField` prop that you can pass to `DatePicker` and passing a `styles` override to it. Check it out here: https://codepen.io/tristanwatanabe/pen/vYxyBVB

**Comment by swasun99** [comment]
Thank you for the codepen, I will try it and get back if need be.
