### ISSUE TITLE
Deployment blocking bug in Planner - Modal - SHIFT + TAB does not go to end of dialog

### ISSUE THREAD

**Issue by daweffe** [microsoft/fluentui#18108]
I updated Planner to 7.188.0 of fluentui/react.  Our task editor dialog uses the Modal component. After the upgrade, SHIFT + TAB no longer cycles to the end of the dialog. If you are at the end of the dialog, TAB still puts focus at the top of the dialog.  I need help diagnosing and addressing this issue please.

Steps to reproduce:
1) Log into tasks.officeppe.com with your microsoft email address.
2) navigate to a plan or create a new one
3) create a new task (optional if the plan has tasks already)
4) click a task card to open the task editor dialog
5) Use TAB and SHIFT + TAB to navigate through the dialog and test the FocusTrapZone wrap around behavior.
 - TAB will let you wrap around going forwards throug hthe tab stops. SHIFT + TAB will keep you on the first tab stop in the dialog and not wrap around to the last tab stop.

**Comment by TristanWatanabe** [comment]
Hey @daweffe, can you provide an isolated codepen/codesandbox that demonstrates the behavior? I've checked using the latest versions of v7 and v8 and I was unable to repro the behavior shown in Planner.
