### ISSUE TITLE
Not able to define tooltip on overflow button in MessageBar component when truncated is enabled.

### ISSUE THREAD

**Issue by chnldw** [microsoft/fluentui#18110]
### Environment Information

- **Package version(s)**: any version
- **Browser and OS versions**: Chrome 90, Win10

### Describe the issue:

Not able to define tooltip on overflow button in MessageBar component when truncated is enabled.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/chnldw/pen/XWMJBBB

#### Actual behavior:

It could define `aria-label` but not `title`. Actually `title` is a better choice for screen reader than `aria-label` for `button`.

#### Expected behavior:

Provide an interface like `overflowButtonTitle` or `overflowButtonIconProps` to allow user customize title on overflow button.

### Documentation describing expected behavior

N/A

**Comment by chnldw** [comment]
Any update on this issue? Thanks

**Comment by yongjiaaaa** [comment]
Are there any update on this https://github.com/microsoft/fluentui/pull/18166? I'm seeing it still not merged.
