### ISSUE TITLE
dropdownWidth: 'auto' is not working

### ISSUE THREAD

**Issue by pskushw** [microsoft/fluentui#18125]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

dropdownWidth property excepting only numbers. Getting an error "Type 'string' is not assignable to type 'number'".

#### Expected behavior:
dropdownWidth : 'auto' should work as described in https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown.
### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by hetanthakkar1** [comment]
@pskushw Can you please provide a sandbox or codepen link. I can't reproduce this issue. I checked the code but I don't seem to find any issue in the code regarding what you mentioned. @ecraig12345 Can you please look into this
