### ISSUE TITLE
Date Picker Selection Colors Are Confusing

### ISSUE THREAD

**Issue by krissygonzal** [microsoft/fluentui#18134]
#### Describe the feature that you would like added

currently (if we interpret correctly), the blue circle on the date picker is used to indicate the current date (<TODAY>). the grey box is used to indicate your selection. this puts the highest emphases on which day is TODAY vs which date you are actually picking. We are requesting that this behavior is swapped -- so that the blue circle indicates "your selection" and the grey box is used to indicate "<TODAY>".
every user that has interacted with the component in our app has been confused by the current behavior.
For example, when they make a selection and then re-open the calendar to pick a date, the impression is that they picked "today" since it is prominently highlighted in bright blue vs their actual selection in a light grey box.

#### What component or utility would this be added to

date picker (https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker)

**Comment by hetanthakkar1** [comment]
@krissygonzal  This is the change you expected right!: https://github.com/microsoft/fluentui/pull/18205#issuecomment-841732308

**Comment by krissygonzal** [comment]
yes this is it! thank you!

**Comment by TristanWatanabe** [comment]
Hey @krissygonzal: with the PR being put on hold, I've mocked up a quick codepen that demonstrates how you can customize the Calendar day's styling to your preferences by using `DatePicker`'s `calendarProps` which contains a `calendarDayProps` with a `styles` prop added to it. Check it out here: https://codepen.io/tristanwatanabe/pen/OJpRKee?editors=1010

**Comment by ecraig12345** [comment]
I talked with one of the designers who worked on DatePicker/Calendar and they said the current colors are intentional for the following reasons:

> - We'd like to have the consistent color scheme for the interaction states across the system, which shows the gray background on selection in Fluent currently (and it's lighter theme color in Outlook)
> - Showing the bold color on the selection is too strong and distracting in the Outlook calendar surface, especially in Week view
