### ISSUE TITLE
Render rating with 0.5 accuracy

### ISSUE THREAD

**Issue by vinod148** [microsoft/fluentui#18141]
#### Describe the feature that you would like added

It will be great if Ratings get rendered at least with 0.5 accuracy. Currently its 1.0.

#### Additional context/screenshots

https://cpb-us-w2.wpmucdn.com/blogs.baylor.edu/dist/5/6712/files/2015/04/3-5-stars-2bmbspe.png
https://growchurch.net/wp-content/uploads/2014/04/3.5stars.jpg
http://www.clker.com/cliparts/D/b/7/N/5/U/3-5-star-rating-hi.png

**Comment by ecraig12345** [comment]
Rating is already able to render with half-star accuracy, it's just hard to see at the moment (see #18178). The contrast issue should be fixed by #18197.
