### ISSUE TITLE
makeStyles types does not satisfy IXXXStyles

### ISSUE THREAD

**Issue by NewFuture** [microsoft/fluentui#18145]
### Environment Information

- **Package version(s)**: 8.14.5

#### Actual behavior:
```ts
import { IImageStyles, makeStyles} from "@fluentui/react";
makeStyles<IImageStyles>({});
```
```
Type 'IImageStyles' does not satisfy the constraint '{ [key: string]: IStyle; }'.
  Index signature is missing in type 'IImageStyles'
```

**Comment by TristanWatanabe** [comment]
@NewFuture : can you please provide us with an isolated repro starting from https://aka.ms/fluentsandbox or https://aka.ms/fluentpen?

**Comment by NewFuture** [comment]
https://codesandbox.io/s/condescending-smoke-b4z6z?file=/src/index.tsx
@TristanWatanabe  please look at the type error
