### ISSUE TITLE
Textfield placeholder does not respect font size

### ISSUE THREAD

**Issue by victor-meng** [microsoft/fluentui#18167]
### Environment Information

- **Package version(s)**: 8.14.3
- **Browser and OS versions**: Google Chrome Version 90.0.4430.212

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/victormeng/pen/xxqZJgq
I exported the code from the fluent UI examples: https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield. I added `style={{ fontSize: 20 }}` to the textfield with placeholder and you can clearly see that the placeholder is still using the default font size (14).

#### Actual behavior:
The textfield placeholder does not respect the font size.

#### Expected behavior:
The font size of the textfield should apply to the placeholder.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Azure Cosmos DB

**Comment by hetanthakkar1** [comment]
@victor-meng I can clearly increase the fontSize in your codepen example. The fontSize gets applied to the text you write and not to the placeholder label text

**Comment by victor-meng** [comment]
@hetanthakkar1 Why does the font size not apply to the placeholder text? If I set the font size in an HTML input, it applies to both the text and the placeholder. Does it make sense for the text to be 20px and the placeholder to be 14px?

Also, I have not found anyway to configure the font size of the placeholder. I tried adding the font size in every single property under `styles` but none applied to the placeholder text.

I can't think of any use case where the developer actually would actually want the user input text to be a different font size than the placeholder text. The expected behavior here is that setting the `fontSize` property should apply to both user input text as well as the placeholder text.

**Comment by TristanWatanabe** [comment]
Hey @victor-meng - making use of `TextField`'s `styles` prop should do the trick here. I've created a codepen where custom font size for both the input text and the placeholder are applied to the component. Just needed to add the pseudo selector `::placeholder` to make it happen. Check it out here: https://codepen.io/tristanwatanabe/pen/vYxXeVE

**Comment by victor-meng** [comment]
Thanks @TristanWatanabe ! I just tried it in our code and it worked. I found that someone else also reported the same issue 2 years ago: https://github.com/microsoft/fluentui/issues/9181. It looks like @kenotron already fixed this issue. Do you know why it came back? Just like what SudharsanSukumar said in the thread, we also use textfields a lot in our product so having to add this work-around everywhere is not ideal.

**Comment by Sylvenas** [comment]
When I try to remove the `.field-59` (or `.field-xx`) class from the input element, the placeholder is displayed at the expected font-size, however `.field-59` does not have `:placeholder`.

**Comment by ecraig12345** [comment]
I looked at this a little and I can't tell from the history where the change from #9181 went--it just seems to be totally gone (not reverted), so it must have gotten lost in merges around the time of a major release.

Removing `fonts.medium` here seems like a reasonable change; we'd just have to verify that it doesn't cause the placeholder to revert to the page's default font.
https://github.com/microsoft/fluentui/blob/63d19651900129f420cd2f1aae4c7da49f1e017a/packages/react/src/components/TextField/TextField.styles.tsx#L109-L110
