### ISSUE TITLE
[ResizeGroup] Watch container resize instead of window resize for growing/reducing data

### ISSUE THREAD

**Issue by hatpick** [microsoft/fluentui#18164]
#### Describe the feature that you would like added

Currently ResizeGroup, use by many other component, is watching window resize event for reducing/growing data. Instead it should be watching its container width changes via https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

#### What component or utility would this be added to

primary ResizeGroup
secondary Pivot, CommandBar, Breadcrumb

**Comment by gouttierre** [comment]
@hatpick  - thanks for reaching out. I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
