### ISSUE TITLE
Tests failing due to @fluentui Northstar Library  (v0.54 and v0.55)

### ISSUE THREAD

**Issue by avbhardwaj** [microsoft/fluentui#18162]
### Environment Information

- **Package version(s)**: (fill this out) 
- 0.54, 0.55
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:
We recently tried to bump the Northstar package to  v0.55, once we updated it, some of our tests started to fail in the ProviderConsumer.js file from the northstar library. 

![image](https://user-images.githubusercontent.com/21962284/118025241-734bd700-b314-11eb-9653-e01902a48f64.png)

#### Actual behavior:
Not sure if this is configuration issue in our project or something that's coming from the Library. Need appropriate guidance :-)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@avbhardwaj - Thank you for filing this item. Are you still experiencing the problem?
cc @kolaps33

**Comment by avbhardwaj** [comment]
@gouttierre : This issue has been resolved, thank you :-)
