### ISSUE TITLE
ThemeProvider documentation is missing from website

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#18185]
We need to add the information on this page to the website somewhere so that people can actually find it. Right now it's linked from the wiki and release notes, but that's not at all obvious.

https://github.com/microsoft/fluentui/blob/master/packages/react/src/utilities/ThemeProvider/README.md

(@TristanWatanabe If you're interested/have time to work on this I can give you some pointers; otherwise we can add it to the backlog.)

**Comment by gouttierre** [comment]
@ecraig12345 - adding this to the backlog unless you or Tristan want to pick it up for the next months planning? 

cc @miroslavstastny
