### ISSUE TITLE
The documentation for the Component Design has an incorrect code example

### ISSUE THREAD

**Issue by jacksonv1lle** [microsoft/fluentui#18190]
In the documentation for [Component Design](https://github.com/microsoft/fluentui/wiki/Component-Design#adding-the-option-to-override-the-root-dom-element), I have noticed a problem with this example code relating to the section about override the root DOM element: 

    function MyLink({ as = 'a', text = 'Hello' }) {
      return (
        <props.a></props.a>
      );
    }

The `props` object would not be defined as it is already destructured within the parenthesis.

I think it should be something like this:
 
    function MyLink({ as:Root = 'a', text = 'Hello' }) {
      return (
        <Root></Root>
      );
    }

**Comment by ecraig12345** [comment]
Fixed, thanks!
