### ISSUE TITLE
@fluentui/react - Slider - onChanged is not working as expected

### ISSUE THREAD

**Issue by sivapalaniappan** [microsoft/fluentui#18203]
### Environment Information

- **Package version(s)**: @fluentui/react - 7.165.2
- **Browser and OS versions**: Edge v90.0.818.62 and Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/sivasingaravelu/pen/MWpyRLE

#### Actual behavior:

The handlerFn passed to `onChanged`  is called with the value that was present when the change had actually started.

#### Expected behavior:

The handlerFn passed to `onChanged`  should be called with the value when the change had actually ended.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Blocking

Products/sites affected: Whiteboard Web

**Comment by sivapalaniappan** [comment]
tagging @ecraig12345

**Comment by TristanWatanabe** [comment]
Can confirm that this is a bug and it's also a regression as this worked in v7. Will work on a fix.

**Comment by Layne101** [comment]
I've met the same issue here. Also, the onChanged method doesn't support range value.

**Comment by Layne101** [comment]
Another thing is that when I slide to the same value in succession, it still will trigger the onChanged function. I don't think it's an expected behavior.
