### ISSUE TITLE
[ChoiceGroup] - Focus order is not consistent when defaultSelectedKey is not provided

### ISSUE THREAD

**Issue by anowduru** [microsoft/fluentui#18207]
### Environment Information

- **Package version(s)**: 8.14.8
- **Browser and OS versions**: Microsoft Edge, Windows 10

### Describe the issue:
Focus order is not consistent when defaultSelectedKey is not provided. Assuming four options A,B,C,D exist, in forward navigation, if option A is focused and tab out of choice group. On back navigation, the focus is shifted to Option D

#### Actual behavior:

https://user-images.githubusercontent.com/18456231/118403578-a8498800-b68c-11eb-9da5-deafb16aa2ce.mp4

#### Expected behavior:

On back navigation, focus should be retained to last focus

### If applicable, please provide a codepen repro:

https://codepen.io/anowduru-the-lessful/pen/jOBrKWm

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (High)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@anowduru - Thanks for providing details into the issue you are experiencing.  

@miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley

**Comment by miroslavstastny** [comment]
The behavior is consistent between v8 and v7 (7.170.3) - when no option is selected, forward navigation focuses the first enabled option, backward navigation focuses the last enabled option.

This is expected behavior.

**Comment by miroslavstastny** [comment]
Also consistent with native `<input>`.

**Comment by anowduru** [comment]
> @anowduru - Thanks for providing details into the issue you are experiencing.
> 
> @miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue?
> cc @smhigley

This is not part of regression, We found it in accessibility testing.
