### ISSUE TITLE
Panel component will not show when * CSS sets position: relative

### ISSUE THREAD

**Issue by imdavidmin** [microsoft/fluentui#18212]
### Environment Information

- **Package version(s)**: 8.12.0
- **Browser and OS versions**: Edge

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/imdavidmin-the-flexboxer/pen/BaWLBzj

#### Actual behavior:

2 child divs in the Panel container div need to have 'position: static' applied for the Panel to show, or apply the root IStyle as
`<Panel ...otherProps styles={{root: {position: 'fixed'}} />` 
![image](https://user-images.githubusercontent.com/48481563/118472295-93a6d780-b700-11eb-842a-72e522399ffb.png)

#### Expected behavior:

Set the position properties by default to avoid being overriden by page level CSS

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by ecraig12345** [comment]
Thanks for filing an issue, but unfortunately this is not something we're likely to fix. Instead I'd recommend more tightly scoping the styling somehow. Setting *all* elements to `position: relative` by default is not likely to work well when you're building a page using a complex component library, and it's not something we can realistically support in all of our components.
