### ISSUE TITLE
Screen reader doesn't notify whether the search box is cleared or not, while clicking on ‘clear’ button.

### ISSUE THREAD

**Issue by Prudhvikoganti** [microsoft/fluentui#18218]
### Environment Information

Windows Version - Win10
Chromium Edge - Version 92.0.884.2 (Official build) dev (64-bit)

### Describe the issue:
Screen reader doesn't notify whether the search box is cleared or not, while clicking on ‘clear’ button.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/prudhvikoganti/pen/XWMjXxg

#### Actual behavior:

Screen reader doesn't notify whether the search box is cleared or not, while clicking on ‘clear’ button.

#### Expected behavior:

The screen reader should notify after clicking the close button.

### Documentation describing expected behavior

https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7BEEE97BBD-9990-48A0-8B03-6EA775581AA8%7D&file=MAS%204.2.1%20%E2%80%93%20Object%20Information.docx&wdLOR=cBC823FF2-F30B-4029-A49F-90FCC0AB9FEB&action=default&mobileredirect=true&cid=3474f307-dd35-4666-ac35-dfe465a76905

**Comment by gouttierre** [comment]
@Prudhvikoganti - thank you for filing this issue and providing the required repro information into the problem.

@miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley

**Comment by smhigley** [comment]
This exact issue has been discussed a number of times between different accessibility specialists and screen reader users, and the conclusion was to not create custom announcements for actions that take place immediately and are predictable based on the context and names of controls.

This scenario (a clear button that immediately deletes an input's text) falls into the category of things that should not get a live region. Unless new user research finds a clear benefit to a custom announcement, the current behavior is correct.

Closing this, but feel free to re-open or comment if you have more questions!
