### ISSUE TITLE
Fluent UI List - onRenderCell change does not cause re-render and update

### ISSUE THREAD

**Issue by tipantaz** [microsoft/fluentui#18216]
### Environment Information
Chrome and new Edge.

### Describe the issue:

The List component can use onRenderCell in order to customize how to render a cell. 
This cell rendering might need information that are not related to the item that gets passed by default that comes from the item list.
The state might change which will cause the onRenderCell to change but that will not cause the list to render again, using the old onRenderCell.

A workaround will be to be passing something like this [..items] or items.slice(0, items.length). This will cause an update.

#### Actual behavior:
You can check the behavior in the codepen bellow.
Start typing in the text box.
This updates the value that is used in the onRenderCell.
When that happens the list does not update even though the onRenderCell changes. 
If you uncomment line 15, and set the list again then this will re render because the items change.

If you also instead do in line 15
   setItems(items);
the list of items basically stays the same so no re render will happen.

#### Expected behavior:

When the onRenderCell changes the list gets re rendered.

### If applicable, please provide a codepen repro:

https://codepen.io/tipantaz/pen/MWpjWZN

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by ecraig12345** [comment]
List is a very old, touchy component, and adding another condition which causes it to re-render could have a lot of negative perf implications. This is especially true if it's being used from within a function component where it's easy to accidentally re-create callback functions on every render.

As a workaround, I'd recommend using `IListProps.version` to force an update only when needed. Here's an example: https://codepen.io/ecraig12345/pen/wvJoNRG?editors=0010
https://github.com/microsoft/fluentui/blob/630b71c415cd40ed0e36773eab99d62cd02a30fb/packages/react/src/components/List/List.types.ts#L255-L258

Currently the type of `version` is `{}`, but based on the usage (search for `.version` [here](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/List/List.tsx)) I think it would be appropriate to change its type to `any` and update the doc comment to reflect that it doesn't need to be an object.

**Comment by tipantaz** [comment]
Thanks @ecraig12345 !
Like I said, I was able to find a workaround. I think your idea might make more sense. So you can pass whatever you want in the version like {value1, function1, etc}.

Updating the documentation would make sense. Also to reflect this issue with the list so developer will not lose time.

Thanks a lot!
