### ISSUE TITLE
Fluent Ui Tree equivalent to the northstar Tree

### ISSUE THREAD

**Issue by Link631** [microsoft/fluentui#18220]
I found out that the north star project has a tree component while in fluent ui it is said, that we should use a grouped list.

While it is much pain to generate out of a recursive structure a plain list together with a second list describing start index and count for the groups, this is quite easy solved in north star.

Will there be a comparable component in fluent ui?

In addition: The grouped list could be also solved easier by providing a helper, which creates groups out of a flat list which has a recursive structure with parent references. 

It is said, that we should use north star for team projects. Is it recommended to use it also for none team projects just with the purpose to use this tree?

**Comment by gouttierre** [comment]
@Link631 - thanks for suggesting this request to add a Tree component  to the stack.  We have no immediate plans to implement this as yet - But I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.
I

**Comment by Link631** [comment]
Maybe it would be a good Idea to encapsulate the tree szenario and use under the hood the current grouped list... 
Thats what I will start doing for now for my current Project I think.
