### ISSUE TITLE
Sample images in documentation are broken

### ISSUE THREAD

**Issue by wdamien** [microsoft/fluentui#18225]
Seen on https://developer.microsoft.com/en-us/fluentui#/controls/web/list

All the images on that page use a third party service, placehold.it. For example: https://placehold.it/166x166. Their certificate has now expired, so all the images are failing to load. They've since updated to be https://placeholder.com/ so this url works: https://via.placeholder.com/166x166. Although it seems odd to me those images are not using a Microsoft CDN. There are currently 346 "Failed to load resource: net::ERR_CERT_DATE_INVALID" errors just on the list page alone, so definitely makes those docs feel broken.

**Comment by hetanthakkar1** [comment]
I will replace placeholder.it with via.placeholder.com. Is this the right thing to do!?
