### ISSUE TITLE
TeachingBubble callout remains in view even if target element (anchor) is out of view because of scrolling

### ISSUE THREAD

**Issue by Ashwin-Nikam** [microsoft/fluentui#18222]
### Environment Information

- **Package version(s)**: 8.10.0
- **Browser and OS versions**: (fill this out if relevant)

#### Expected behavior:
The teaching bubble should also be scrolled with respect to the target div it has been anchored to.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Outlook web

**Comment by Ashwin-Nikam** [comment]
@TristanWatanabe do we have any updates? Is this expected behavior or a recent regression?

**Comment by gouttierre** [comment]
@Ashwin-Nikam - thanks for filing this issue and sharing the details into the problem.
 
@miroslavstastny / @smhigley - Would you be able to confirm if this is a regression, or if this behavior is an issue? Thanks

**Comment by Ashwin-Nikam** [comment]
@gouttierre @miroslavstastny @smhigley Do we have any updates on this? Please let me know if this is the expected behavior and there is a workaround for this or if its a regression. Thank you.

**Comment by ling1726** [comment]
@Ashwin-Nikam  the v8 callout does not support repositioning on scroll by default, this is something that you need to handle yourself. Here is a codepen with a possible way of doing it.

https://codepen.io/ling1726/pen/XWRpWxj

**Comment by Ashwin-Nikam** [comment]
@ling1726 Thanks for the suggestion. Looks like every time we scroll, we need to re-render the TeachingBubble which determines if its correctly anchored or not and if not then does so. The count useState in the codepen does exactly that. I tried it and works like a charm. Closing this issue 👍🙂
