### ISSUE TITLE
Can ComboBox support contains when in allowFreeForm model?

### ISSUE THREAD

**Issue by RichardSunMS** [microsoft/fluentui#18250]
#### Describe the feature that you would like added

When set AllowFreeForm for Combobox, can it support below requirements:
1. Auto popup the drowdown menu when get focused, which can help the users easy to see the possible options to select.
2. When type the words in the input, can it support contains and filter the dropdown options instead of startswith.

#### What component or utility would this be added to

ComboBox

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

https://www.screencast.com/t/yaRK6FRylrf

**Comment by gouttierre** [comment]
@RichardSunMS - thank you for reaching out. Have you taken a look at our documentation for the [ComboBox](https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox). See if that works for you? Else - feel free to reach out to us again, providing you supply a CodePen with your question.

**Comment by RichardSunMS** [comment]
@gouttierre , didn't pay attention to my mailbox so didn't see your ask 10 days ago.
Yes, I checked the doc of ComboBox, but didn't find a good way to implement my requirement. Can you suggest?
