### ISSUE TITLE
Custom choice group cannot click on the customed content

### ISSUE THREAD

**Issue by ZhehooMorgen** [microsoft/fluentui#18253]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: chrome 90, win10 21h1

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/ProtonEffect/pen/gOmLWwN

#### Actual behavior:
Cannot click or do other things of customized part of ChoiceGroup item

#### Expected behavior:
Can click or do other interaction

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes
Requested priority: (Blocking, High, Normal, Low)
High
Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@ZhehooMorgen  - thank you for reaching out and providing details into the problem you are facing. Also, thanks for showing a willingness to submit a PR for this fix. Would you mind sharing it with us?

cc @miroslavstastny
