### ISSUE TITLE
[TeachingBubble] Long titles are not cropped properly

### ISSUE THREAD

**Issue by lucas-stanford** [microsoft/fluentui#18261]
### Environment Information

- **Package version(s)**: 8.14.11
- **Browser and OS versions**: Chrome/Windows

### Describe the issue:
Teach bubbles titles that are long should be truncated and maybe have a title attr added

![image](https://user-images.githubusercontent.com/3011776/118908986-30bb6900-b8d7-11eb-884c-9202d7d6e01e.png)

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/fordfordford/pen/QWpGPVX

#### Actual behavior:
Content is not visible when title is a long string

#### Expected behavior:
Ellipsis should be shown at minimum to indicate there is additional text. 

### Documentation describing expected behavior
n/a

**Comment by gouttierre** [comment]
@lucas-stanford - thanks for reaching out and I see  PR #18267 will help sort this out. We will keep this open until the linked PR is completed.

**Comment by nancy2681** [comment]
@ecraig12345 Can you please review my PR?

**Comment by ecraig12345** [comment]
@lucas-stanford Just FYI in case this comes up again, in most cases you can manually add a style override setting `overflowWrap: 'break-word'` if it's not already present. In this case it would go under `ITeachingBubbleProps.styles.headline`. https://codepen.io/ecraig12345/pen/OJpYGax?editors=0010
