### ISSUE TITLE
When dialogcontentprops.titleprops.id is set to undefined, no id is set (not even the default)

### ISSUE THREAD

**Issue by cabillin** [microsoft/fluentui#18288]
### Environment Information

- **Package version(s)**: repros in @fluentui/react@8, but we are using ^7.137.2
- **Browser and OS versions**: edge dev (but browser agnostic)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/KnetTravlr/pen/QWppjGd

#### Actual behavior:

No id is set for title element when dialogcontentprops.titleprops.id is set to undefined
![image](https://user-images.githubusercontent.com/71525014/119189194-9a02bf80-ba30-11eb-9b71-47e9301c46a3.png)

#### Expected behavior:

Expect behavior to match the behavior when the dialogcontentprops.titleprops.id is not set
![image](https://user-images.githubusercontent.com/71525014/119189612-1eedd900-ba31-11eb-8a5b-9c034f396464.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? Depends on complexity of fix

Requested priority: Normal

Products/sites affected: internal Microsoft website

**Comment by gouttierre** [comment]
@cabillin - Thank you for filing this item and sharing the codepen with repro details.
@miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by smhigley** [comment]
@cabillin my concern with this is that using `id: undefined` to restore the default would mean that there's no clear way to actually remove the `id` prop, and anyone currently using `id: undefined` to remove it would suddenly have that behavior change.

I do see the convenience in being able to do something like this, though:
```js
dialogContentProps={{
  titleProps: {
    id: hasId ? titleId : undefined
  }
}
```

I'm curious whether other people think supporting the relative ease of that usage is worth taking away the mechanism to remove the `id` prop from the Dialog title. @ecraig12345 (or anyone from @microsoft/cxe-red), any opinions?

**Comment by ecraig12345** [comment]
@khmakoto That's a good point. @cabillin Could you explain more about why you need to explicitly provide `undefined` (as opposed to not setting the prop at all)? While this isn't something we typically spec out or test for, the typical behavior is that explicitly setting something to `undefined` would override the default.
