### ISSUE TITLE
Safari: Button styles not updated when changing from disabled to enabled or vice versa

### ISSUE THREAD

**Issue by kemusag** [microsoft/fluentui#18280]
### Environment Information

- **Package version(s)**: tested on 7.105.7 and 7.170.01
- **Browser and OS versions**: Safari 14.1

### Please provide a reproduction of the bug in a codepen:

1.  Go to https://developer.microsoft.com/en-us/fluentui?fabricVer=7#/controls/web/button 
2. Make sure you select the correct Version (7.x)
3. Use the "Disable buttons" toggle twice to swap to disabled and back to enabled
4. --> Button text colors are still the ones from disabled state

![image](https://user-images.githubusercontent.com/77784146/119137518-2ae19700-ba41-11eb-9ff5-778d920a3a6f.png)

The button styling should be updated correctly.

### Notes

- This issue does not occur in version 8 anymore. I couldn't find an issue describing this that was already created.
- Hovering the buttons solves it most of time (probably triggers a rerender?)

**Comment by gouttierre** [comment]
@kemusag - thanks for reaching out - i retested this issue on v7 and was not able to [repro](https://developer.microsoft.com/en-us/fluentui?fabricVer=7#/controls/web/button).
![image](https://user-images.githubusercontent.com/78806055/122079368-a1ce3d80-cdfd-11eb-9d7c-87345ffc5c1c.png)
 
cc. @miroslavstastny

**Comment by kemusag** [comment]
@gouttierre Thanks for retesting. Strange! I can still easily reproduce it by simply going to the button demo page, disable the buttons and then enable them again:
![image](https://user-images.githubusercontent.com/77784146/122168395-82c2c080-ce7c-11eb-8778-8100fb97b054.png)

I am now on Safari 14.1.1
However, I just noticed that the devtools are showing the color correctly. It seems like the color is set correctly to rgb(255, 255, 255) but somehow Safari doesn't seem to render it. 
![image](https://user-images.githubusercontent.com/77784146/122174832-5d858080-ce83-11eb-88f3-4b394825cce2.png)

**Comment by odhanson** [comment]
Hi. This is also affecting our product. It seems to have happened since we upgraded MacOS to 11.4

**Comment by behowell** [comment]
This appears to be a bug in Safari, which happens when the button sets the `pointer-events: none` style. The v7 button has `pointer-events: none` when it is disabled, but the v8 button does not.

This codepen demonstrates the bug without involving FluentUI or React: https://codepen.io/behowell/pen/vYmGKaB
In Safari, the second button doesn't change text color when its class changes, but in Chrome it does.

We may be able to work around this issue by removing `pointer-events: none` in v7 as well.

**Comment by behowell** [comment]
I've reported this issue to Safari via https://www.apple.com/feedback/safari.html

**Comment by odhanson** [comment]
Thanks @behowell . So are we planning to create a fix for v7 based on your suggested workaround?

**Comment by behowell** [comment]
@odhanson Yes we're going to cherry-pick the change that removed `pointer-events: none` from v8 into v7.

**Comment by odhanson** [comment]
Great thanks !

**Comment by kemusag** [comment]
Thanks so much @behowell
Glad you were able to find a fix for it :)
