### ISSUE TITLE
ContextualMenu wont close on button click

### ISSUE THREAD

**Issue by kennyoctopus** [microsoft/fluentui#18285]
Reproductible in your live examples:

https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu

Click to open the menu then click to close it. It should close but it closes and reopen.

The problem is that onDismiss is called first, the onClick event on the button that update de visibility state of the menu is then called with the updated state to false (updated in the previous render by onDismiss), so it toggle it back to true.

**Comment by khmakoto** [comment]
@kennyoctopus I think #18274 has fixed this and it no longer reproduces. Can you double check again? Thanks!
