### ISSUE TITLE
https://uifabricicons.azurewebsites.net/ is down

### ISSUE THREAD

**Issue by asell22** [microsoft/fluentui#18287]
I apologize in advance if this is not where I should be reporting this but  [https://uifabricicons.azurewebsites.net/](https://uifabricicons.azurewebsites.net/) is currently down. 

Here's the error I see in the dev console:
<img width="1437" alt="Screen Shot 2021-05-21 at 10 15 58 AM" src="https://user-images.githubusercontent.com/9015024/119175711-05439600-ba1f-11eb-81e8-f33f3ec3284f.png">

**Comment by ecraig12345** [comment]
@tomi-msft Can you work with the current owners of the icons site to make sure this gets fixed?

**Comment by TristanWatanabe** [comment]
Website is back up - will close this issue now.
