### ISSUE TITLE
Add fabric react coachmark/Teaching Bubble in Excel web addin ribbon

### ISSUE THREAD

**Issue by arshadshibli** [microsoft/fluentui#18286]
I am using Fabric react components CoachMark and Teaching Bubble to guide user through my excel web addin. 

https://developer.microsoft.com/en-us/fluentui#/controls/web/teachingbubble
https://developer.microsoft.com/en-us/fluentui#/controls/web/coachmark
I was able to successfully add coachmark and teaching bubble in panels and dialogues. But I also need to have such coachmark/teaching bubble in addin ribbon. But I could not find any documentation for that.

I can see Microsoft is using it in ribbon as shown in the following image.
![image](https://user-images.githubusercontent.com/36449762/119170921-8d5a8780-ba81-11eb-9181-f7bb26eb0851.png)

I am looking for something similar to this . The question is how to use CoachMark/Teaching Bubble in ribbon without opening a panel/dialogue. Any guidance will be appreciated.

 #office-ui-fabric, #fluentui-react, #fluentui

**Comment by arshadshibli** [comment]
Any updates on this please

**Comment by gouttierre** [comment]
@arshadshibli - thank you for reaching out and your question. 

@miroslavstastny - I know you were working recently with Coachmark - would you able to share any guidance in utilizing a ribbon without opening a panel/dialogue
