### ISSUE TITLE
Pivot/Tabs in @fluentui/react-northstar

### ISSUE THREAD

**Issue by birla** [microsoft/fluentui#18291]
#### Describe the feature that you would like added

Pivot in N* repo

#### What component or utility would this be added to

Same functionality as in @fluentui/react

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-basic-ui-components#pivot

This page links to https://fluentsite.z22.web.core.windows.net/0.56.0 however many of the components shown in the docs as "basic ui components" and in the figma toolkit aren't implemented in N* nor in `@fluentui/react-teams`. What is the best practice to implement these components in teams applications? We are a Microsoft Gold Partner Vendor.

**Comment by gouttierre** [comment]
@birla- Thank you for filing this suggestion. I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. What is the priority level for this request? 

@jurokapsiar - Would you know by chance if there are any immediate plans to support Pivot within North-star?

**Comment by birla** [comment]
@gouttierre That's great! We had a call with Microsoft a few weeks back where they asked us to use the Figma Teams UI Toolkit to design solutions for our customers. My company has multiple ongoing projects, app/bots for Teams, in nascent stages where we are deciding the react libraries to use. So we are in immediate need some direction from Microsoft to understand the libraries to use which are stable and have implemented the components shown in the Figma Toolkit.

**Comment by jurokapsiar** [comment]
Hi, please check "Menu as tab list" example: https://fluentsite.z22.web.core.windows.net/0.56.0/components/menu/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#usage-tab-list
