### ISSUE TITLE
[Label]Screen reader doesn't provide required field on label

### ISSUE THREAD

**Issue by zhr1130** [microsoft/fluentui#18294]
### Environment Information

- **Package version(s)**: 8.14.13
- **Browser and OS versions**: Windows 10 with Narrator

### Describe the issue:

We are using a label for a required numeric input, however screen reader doesn't provide required field while reading.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/zhr1130/pen/PopmPzM

#### Actual behavior:

Screen reader doesn't provide required field.

#### Expected behavior:

Screen reader should provide required field for label with "required" property.

### Documentation describing expected behavior

MAS Reference:
MAS 1.3.1 - Info and Relationships

**Comment by ecraig12345** [comment]
Typically the recommended pattern in `@fluentui/react` is to use TextField's `label` prop, like this ([full example](https://codepen.io/ecraig12345/pen/PopyEKY)):
```jsx
<TextField id={textFieldId} required label="A Label for An Input" />
```

If you need to further customize how the label is rendered, you can use TextField's `onRenderLabel` prop.
