### ISSUE TITLE
Fluent UI React detaillist bug in selection when filtering

### ISSUE THREAD

**Issue by G00golplex** [microsoft/fluentui#18306]
### Environment Information
https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic#feedback

#### Actual behavior:

If you select an item from the list and try to search for another item, your previous selection is lost. That cannot be the intention?

#### Expected behavior:
You check the checkbox from the desired item, you search for another and add that one to your selection and you do NOT loose your selection after every search. This is easy to test on the Fluent UI react website as showed above.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes)

Requested priority: ( Normal)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@G00golplex - thank you for reaching out and showing a willingness to submit a fix for the PR. Are you aware of a solution at hand? if so, could you share it with us or you can submit a PR for our team to review? Thank you
