### ISSUE TITLE
"+" missing in Fabric UI icon AddFavoriteFill

### ISSUE THREAD

**Issue by LukeOwlclaw** [microsoft/fluentui#18320]
There seem to be missing a "+" on the filled version of AddFavoriteFill F0C9.

#### Actual behavior:

AddFavoriteFill is missing "+":
![image](https://user-images.githubusercontent.com/2737900/119482382-19a3cd80-bd54-11eb-9945-8e00e599276e.png)

#### Expected behavior:

"+" should be visible

### Steps to reproduce:

Go to https://developer.microsoft.com/en-us/fluentui?fabricVer=7#/styles/web/icons
scroll and down type "AddFav"

---

Original issue: https://github.com/microsoft/fluentui/issues/9938

**Comment by nancy2681** [comment]
@TristanWatanabe I need an svg for the correct icon. So that we can replace that in AddFavoriteFillIcon.tsx

**Comment by ecraig12345** [comment]
@tomi-msft Can you help find the right person from design to look into fixing this issue? (it's an MDL2 font icon)

**Comment by gouttierre** [comment]
@LukeOwlclaw - thanks for filing this request. 
@tomi-msft - do you have any updates on this particular item? Thanks in advance.
