### ISSUE TITLE
Dropdown callout positions next to select

### ISSUE THREAD

**Issue by reposman33** [microsoft/fluentui#18340]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "7.100.0",
- **Browser and OS versions**: Firefox 88.0.1 (64-bit) Windows 10 Home v 20H2

### Please provide a reproduction of the bug in a codepen:
see attached screenshot below

#### Actual behavior:
When clicking a Dropdown component, if the callout (the list of options) is taller than the available space below it _and_ taller than the available space above it, it is displayed to the right of the Dropdown component.

#### Expected behavior:
When clicking a Dropdown component, the callout (the list of options) should open _below_ the component. If there are more options than can be displayed, a scrollbar is displayed to scroll the list of options. The callout should be displayed _below_ or _above_ the Dropdown component but not to the left or to the right.

To reproduce:
- go to the usage section of the fluent ui dropdown page: https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown#usage
- scroll to the first example Usage => Basic Dropdowns => Basic uncontrolled example
- resize the browser window height so that just the dropdown is displayed with titletext "Basic Dropdowns"
- click the Dropdown. The list of options is displayed to the right of the component, not below or above it.

### Priorities and help requested:
This is a bug since I have a Dropdown containing over 40 options. There is no way all these options can be displayed in a browser with a viewport high enough to display the list _without_ a scrollbar

Are you willing to submit a PR to fix? (No)

Requested priority: (High)

Products/sites affected: (if applicable)
Dropdown component from office-ui-fabric-react

![image](https://user-images.githubusercontent.com/3200870/119669280-3a455380-be38-11eb-9a02-9108bf9420f1.png)
reproduced example on developer.microsoft.com/

![image](https://user-images.githubusercontent.com/3200870/119670693-64e3dc00-be39-11eb-9804-01fe3c5ae7d9.png)
actual project using a fluent-ui Dropdown component with lots of items.

**Comment by hetanthakkar1** [comment]
@TristanWatanabe @ecraig12345 How about removing this part from Dropdown.base.tsx( Line 589-600)

isSmall ? (
      <Panel
        isOpen={true}
        isLightDismiss={true}
        onDismiss={this._onDismiss}
        hasCloseButton={false}
        styles={panelStyles}
        {...panelProps}
      >
        {this._renderFocusableList(props)}
      </Panel>
    ) :

**Comment by ecraig12345** [comment]
@hetanthakkar1 No, that's the code used to render the options inside a panel on small screens.

This behavior is actually by design right now. If you want the callout to always display beneath the dropdown, you can set `IDropdownProps.calloutProps.directionalHintFixed` to `true` as shown here. https://codepen.io/ecraig12345/pen/mdWMWNE?editors=0010

**Comment by reposman33** [comment]
@ecraig12345 Thanx, that's what I was looking for :)
