### ISSUE TITLE
Typings for callbacks on Fabric components posit that the component may omit them when invoking the callback

### ISSUE THREAD

**Issue by dmichon-msft** [microsoft/fluentui#18350]
### Environment Information

- **Package version(s)**: 7.0 latest
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

This issue occurs for nearly every callback in the repository, but to use a specific example, the DetailsList `onRenderItemColumn` callback typings (https://github.com/microsoft/fluentui/blob/7.0/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts#L192) specify:
```typescript
  onRenderItemColumn?: (item?: any, index?: number, column?: IColumn) => React.ReactNode;
```

Under what circumstances should we expect the DetailsList component to invoke `onRenderItemColumn(/* no arguments */)`?
Or, for that matter, to pass `undefined` as `index` and/or `column`?

#### Actual behavior:

```typescript
const props: IDetailsListProps = {
  // ...
  onRenderItemColumn: (item: any, index: number, column: IColumn) => { return null; }
};
```
Does not compile because argument of type `number | undefined` is not assignable to parameter of type `number` and argument of type `IColumn | undefined` is not assignable to parameter of type `IColumn`.

#### Expected behavior:

```typescript
  // item, index, and column will always be passed by DetailsList
  onRenderItemColumn(item: any, index: number, column: IColumn) => React.ReactNode;
```

Note that:
```typescript
const onRenderItemColumn: (item: any, index: number, column: IColumn) => React.ReactNode = () => { return null; };
```
Compiles fine under all `strict` flags. 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Can be worked around with a large number of type assertions, non-null assertions, if checks, or by disabling `strictNullChecks`, but is a significant nuisance to efficient development.

Products/sites affected: Anyone consuming Fabric with `strictNullChecks` enabled.

**Comment by ecraig12345** [comment]
In general the most common reason for this to happen was if params were added to a callback within a major version. I'm not sure why that particular callback would have the params as optional though, since it seems like they should all have been present from the start (blind pattern-following maybe?). 

Unfortunately we probably won't be able to fix this outside of a major version, because I'm pretty sure that would break people who use certain strict options and currently have the params marked as optional or aren't providing them.

**Comment by gouttierre** [comment]
This issue will be scheduled for a review at a later stage.
