### ISSUE TITLE
Playground for documentation website

### ISSUE THREAD

**Issue by hetanthakkar1** [microsoft/fluentui#18354]
#### Describe the feature that you would like added

It would be a great feature to implement a playground where you can tweak the code for the components(more specifically the props) and see the desired output on the website. I have worked on a similar kind of project in the past and I would be more than happy to work on this feature. I have researched the implementation detail for this feature and  I am ready to finish this functionality (if permitted) by the end. I know this is not a simple feature but I am idle for few months and I can contribute significant time to this feature. @arpitBhalla @nancy2681 can also help me in this project. I do feel that this would be a great feature as fluent UI is not just used by Microsoft apps but also in other projects

**Comment by arpitBhalla** [comment]
@hetanthakkar1 That's a great idea, I am in

**Comment by hetanthakkar1** [comment]
@TristanWatanabe @ecraig12345 What do you think!?

**Comment by ecraig12345** [comment]
Sorry for the delayed response, I was on vacation. We really appreciate your interest and willingness to help, but unfortunately this isn't good timing for adding that specific feature. There's work ongoing internally to replace the current website, and I think a playground like that is actually one of the features they're planning to include. 

(On a related note, in case you weren't aware, it's actually possible to edit the code for the examples on the current website--just click "Show code" and then start editing. We added that feature a couple years ago but never really advertised it much, and didn't have time to get it to a completely finished/polished state.)

If you want, I can think about other features that might be a better fit, and get back to you.

**Comment by gouttierre** [comment]
This issue will go to the backlog.

**Comment by hetanthakkar1** [comment]
No thank you!
