### ISSUE TITLE
TagPicker suggestions/item long text.. default tooltip text not showing up on hovering on ellipsis

### ISSUE THREAD

**Issue by sankarkumar23** [microsoft/fluentui#18355]
The default tooltip is not showing up on hovering on ellipsis if content is tool long. Ex: Selected a long text item in TagPicker. I do see tooltip in codepen samples of TagPicker. I am using Panel control and on top of it I added TagPicker. It seems tooltip is not working on any of the controls with long text. Any tips on how to troubleshoot this?

**Comment by sankarkumar23** [comment]
I figured out when you have title attribute tooltip will show up.. but for me title is not being added automatically. I am using version 1.11.0

**Comment by sankarkumar23** [comment]
Issue resolved for SelectedItem(s) after upgrading to version 1.12.1. Can we have tooltip text in suggested items drop down too? I have multiple long texts in suggested items having same value expect the ending part.. so its difficult to choose the correct item.

**Comment by gouttierre** [comment]
@sankarkumar23  - thank you for reaching out - I see the issue resolved for SelectedItem(s) after upgrading to version 1.12.1. 
For your request on having a tooltip text in suggested items drop down too - this will have to be reviewed at a later stage as we’re currently focused on larger coherence work items and enhancements to our performance. Unless, you have an idea on the implementations for the request and would like to submit a PR.
