### ISSUE TITLE
Menu: remove confusing `menuPopup` slot

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#18359]
## Current problem

Styling the popup that displays an opened menu is not very intuitive because it must be done through a `menuPopup` slot. This was done because the `Menu` does not actually render any DOM so the decision was made to use the slot instead.

```tsx
// ⚠⚠⚠ This will not work because `Menu` does not actually render DOM and does not spread props
<Menu className="popup-styles">
  <MenuTrigger>
     <button>Open menu</button>
  </MenuTrigger>

  <MenuList>
    {menuitems}
  </MenuList>
</Menu>

// Should be done using the `menuPopup` slot
<Menu menuPopup={{className="popup-styles"}}>
  <MenuTrigger>
     <button>Open menu</button>
  </MenuTrigger>

  <MenuList>
    {menuitems}
  </MenuList>
</Menu>
```

## Proposal 1 - `Menu` should just represent the popup as a root slot

Even though the `Menu` does not actually render any DOM, it should still be the spread DOM attributes to the popup:

```tsx
// ✅✅✅ This will now work
<Menu className="popup-styles">
  <MenuTrigger>
     <button>Open menu</button>
  </MenuTrigger>

  <MenuList>
    {menuitems}
  </MenuList>
</Menu>
```

⚠⚠ This would have consequences for `Popover` which should be refactored to be consistent

```tsx
<Popover classnName="popover-styles"> // Represents the positioned element
  <PopoverTrigger>
     <button>Open popover</button>
  </PopoverTrigger>

  <PopoverContent className="popup-styles"> // Represents the content container
    {content}
  </PopoverContent>
</Popover >
```

## Proposal 2 - Separate `MenuPopup` component similar to `Popover` API

The `menuPopup` slot was originally created because we wanted `MenuList` to be usable by consumers in their own surfaces without being coupled to our positioning logic. However since `Popover` makes no sense to have this dual-purpose it has a more logical API:

```tsx
<Popover>
  <PopoverTrigger>
     <button>Open popover</button>
  </PopoverTrigger>

  <PopoverContent className="popup-styles">
    {content}
  </PopoverContent>
</Popover >
```

We can create a new `MenuPopup` component to do this, this component _could_ leverage `Popover` internally but that is an implem detail for the scope of the problem
```tsx
// ✅✅✅ This will now work
<Menu>
  <MenuTrigger>
     <button>Open menu</button>
  </MenuTrigger>

  <MenuPopup className="popup-styles">
    <MenuList>
      {menuitems}
    </MenuList>
  </MenuPopup>
</Menu>
```

## Pros/Cons

`Proposal 1` would allow a way for both `Popover` and `Menu` to access the positioned div independently of a content. However whether the content container is necessary for `Popover` is debatable.

`Proposal 2` seems more logical IMO, since the actual `Popover` or `Menu` components themselves rendering DOM seems strange in the context of also rendering a `Trigger` component

**Comment by ling1726** [comment]
@miroslavstastny @levithomason  any thoughts here from your experience in MeControl ?

**Comment by miroslavstastny** [comment]
Both proposal look better than the current state :+1:
I would vote for Proposal 2 - even though there is more to type, the JSX better represents the logical structure of the component, there are less surprises and being aligned with `Popover` is a great additional benefit.
