### ISSUE TITLE
Display label to the left of a TextField component

### ISSUE THREAD

**Issue by reposman33** [microsoft/fluentui#18358]
I have a Textinput and Dropdown component. Both components have a label that is shown _above_ the component. I want the label to be displayed to the _left_ of the component.

Not sure how to do this.
- ```Dropdown.onRenderLabel``` allows me to return JSX that can contain the label but I cannot change the position using css
- the components style property allows me to assign css to the input component, not to the parent component that contains both the label and the input component itself.

What I would like to do is assign a style to the componoent that wraps _both_ the label and the input but I can't see how.
The style applied to the .ms-Dropdown-container element below gives me what I want:
```
<div class="ms-Dropdown-container" style="flex-direction: row;display: flex;padding: 1rem;align-items: center;">
  <div class="css-165" style="margin-right: 15px;">Type</div>
  <div data-is-focusable="true" id="Dropdown19" tabindex="0" role="listbox" aria-haspopup="listbox" aria-expanded="false" aria-labelledby="Dropdown19-label Dropdown19-option" aria-disabled="false" class="ms-Dropdown dropdown-149">
    <span id="Dropdown19-option" class="ms-Dropdown-title title-150" aria-live="polite" aria-atomic="true" aria-invalid="false" role="option" aria-setsize="11" aria-posinset="1" aria-selected="true">Paragraph</span>
    <span class="ms-Dropdown-caretDownWrapper caretDownWrapper-151">
      <i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Dropdown-caretDown caretDown-166"></i>
    </span>
  </div>
</div>
```

Is there a way to accomplish this?

**Comment by gouttierre** [comment]
@reposman33 - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [TextField ](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
