### ISSUE TITLE
Accessibility issue when embeeding <SwatchColorPicker> into <ContextualMenu>

### ISSUE THREAD

**Issue by HugoRomat** [microsoft/fluentui#18360]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "^7.168.2",
- **Browser and OS versions**: Edge / Windows

### Describe the issue:

Impossible to navigate from the color Picker to the other items. 
My goal was to navigate within the color using the arrows. And navigate between the menu items using the Tab key. 
However, it doesn't work at all.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/HugoLasticot/pen/dyvNpKz?editors=1010

#### Actual behavior:

Can't navigate using tab

#### Expected behavior:

Navigation using tab

### Documentation describing expected behavior

My guess is because there is two focus zone imbricated, but shouldn't behave like that

**Comment by smhigley** [comment]
@HugoRomat it looks like you may want a Callout, not a ContextualMenu to contain the color picker.

Aside from the keyboard interaction, a ContextualMenu has `role="menu"` on it, and can only contain children with a role of `menuitem`, `menuitemcheckbox`, or `menuitemradio`. Callout is a more general-purpose popup, can contain any children, and does not manage focus between its descendants in the way that ContextualMenu does.

Let me know if you have any questions about Callout, or why ContextualMenu works the way it does :)

**Comment by HugoRomat** [comment]
Thanks a lot! It works :)
