### ISSUE TITLE
Dialog has too much white space below footer if no subText

### ISSUE THREAD

**Issue by timothyhoffmann** [microsoft/fluentui#18377]
#### Describe the feature that you would like added

If a Dialog does not have a subText string then the white space below the DialogFooter is a bit too large.

#### What component or utility would this be added to

Dialog

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots
Dialog with text in the body of the dialog but no subtext
![image](https://user-images.githubusercontent.com/28546239/120043026-37359900-bfd9-11eb-8c00-ae6975839bed.png)

Same dialog but with subText
![image](https://user-images.githubusercontent.com/28546239/120043207-8976ba00-bfd9-11eb-8212-867b5dc093ee.png)

**Comment by nancy2681** [comment]
I am working on this.

**Comment by gouttierre** [comment]
@timothyhoffmann - thanks for filing this request. I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
