### ISSUE TITLE
[Web components] Tree view item icon is rotated 45 degrees counter-clockwise more than it should be

### ISSUE THREAD

**Issue by winston-de** [microsoft/fluentui#18370]
### Environment Information

- **Package version(s)**: @fluentui/web-components from UnPackage (0.21.2 I suppose)
- **Browser and OS versions**: Chromium Edge

#### Actual behavior:
Icon is rotated 45 degrees counter clockwise, so that it points north-east when collapsed and east when expanded.

Expanded state:
![image](https://user-images.githubusercontent.com/59544401/119910753-ad1ffe80-bf0c-11eb-9b4f-85fc5d1bc7f1.png)

Collapsed:
![image](https://user-images.githubusercontent.com/59544401/119910776-ba3ced80-bf0c-11eb-9ca8-8289ba9cf7b5.png)

#### Expected behavior:
Icon points east when collapsed and south-east when expanded.

Expanded state:
![image](https://user-images.githubusercontent.com/59544401/119910646-70540780-bf0c-11eb-8c42-18c20e4b3321.png)

Collapsed state:
![image](https://user-images.githubusercontent.com/59544401/119910672-7cd86000-bf0c-11eb-9bbd-b8e01404d1f7.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: low

Products/sites affected: (if applicable)

**Comment by chrisdholt** [comment]
Thanks @TristanWatanabe for the issue - I believe we’ve addressed this in our feature branch for cNext which should be releasing in the next week or so. If you can wait for that, awesome! If not, we’d be happy to take a PR or prioritize it into a release prior to v1.
