### ISSUE TITLE
React northstar Embed component does not render PDF except demo site

### ISSUE THREAD

**Issue by IshamMohamed** [microsoft/fluentui#18375]
React northstar version: 0.56.0

I tried the following code in the demo [site](https://fluentsite.z22.web.core.windows.net/0.56.0/components/embed/definition).
```
import React from 'react'
import { Embed, Flex, Text } from '@fluentui/react-northstar'

// Get PDF file from Logic App
const PdfLocation = 'https://prod-10.southeastasia.logic.azure.com/workflows/[rest-of-the-hidden-part]';

const EmbedExamplePDF = () => (
  <Flex column>
    <Embed
      iframe={{
        src: PdfLocation,
        frameBorder: 0,
        height: '400px',
        width: '711.11px',
      }}
      title="Look ma!"
      variables={{
        height: '400px',
        width: '711.11px',
      }}
    />
    <Text>(c) copyright 2020, Microsoft</Text>
  </Flex>
)

export default EmbedExamplePDF
```
This works nicely in the demo site:
![image](https://user-images.githubusercontent.com/2231923/120012321-ee4e0680-c011-11eb-8c87-7c14290c048a.png)

However the same code does not show the PDF in Teams client. Why is this behavior?

Additionally, the Embed component displays a play button by default, how to disable it?

**Comment by gouttierre** [comment]
@IshamMohamed - thanks for reaching out.

@kolaps33 - Would you be able to confirm if this is a regression, or if this behavior is an issue?
