### ISSUE TITLE
Carousel: No animation in controlled mode

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#18386]
Changing activeIndex in carousel switches the slides, but does not cause the slides to be animated.

### Environment Information

- **Package version(s)**: 0.56
- **Browser and OS versions**: all

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluent-ui-example-forked-d5gn6?file=/example.js

**Comment by gouttierre** [comment]
@kolaps33 - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by assuncaocharles** [comment]
Can't reproduce it, animation happens when activeIndex is controlled changed.
