### ISSUE TITLE
Callout: maxHeigth cannot be set by the user if !important is not set when using directionalHintFixed

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#18381]
When using `directinalHintFixed` on a `Callout` the `maxHeight` is overridden even if the user is setting it, either through `styles`, `classname` or via the `calloutMaxHeight` prop.

**Comment by hetanthakkar1** [comment]
@ecraig12345 @khmakoto Will removing this line work!?: https://github.com/microsoft/fluentui/blob/25079ca410f149bb05f776112e827b60183de70f/packages/react/src/components/Callout/CalloutContent.base.tsx#L143
