### ISSUE TITLE
[DetailList]: Screen reader doesn't associates the cell value with it's column header

### ISSUE THREAD

**Issue by zhr1130** [microsoft/fluentui#18384]
### Environment Information

- **Package version(s)**: 8.15.1
- **Browser and OS versions**: Windows 10 with Narrator

### Describe the issue:

Screen reader doesn't associates the cell value with it's column header

### Please provide a reproduction of the issue in a codepen:

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/compact

#### Actual behavior:

Screen reader doesn't associates the cell value with it's column header

#### Expected behavior:

Screen reader should associates the cell value with it's column header

### Documentation describing expected behavior

MAS 4.2.3 - Row, Column, and Headers (33C)

**Comment by gouttierre** [comment]
@zhr1130  - thanks for filing this issue. 

@smhigley - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @miroslavstastny

**Comment by smhigley** [comment]
@zhr1130 I can't reproduce with either NVDA or Narrator in Firefox, Chrome, or Edge. The column headers are read correctly for me in the linked example when navigating with standard table navigation.

Could you provide information on what commands you're using to navigate the table, and what output you're getting? Windows lets you record screen reader audio through the game bar if a video would be easier.

Thanks!
