### ISSUE TITLE
ChoiceGroup doesn't look consistent with WinUI RadioButton

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/fluentui#18387]
Seems like ChoiceGroup is using the old design where the circle was inside the border which isn't consistent with WinUI's RadioButton control.

Fluent UI React CheckGroup:
![image](https://user-images.githubusercontent.com/45227503/120165542-4f93f680-c219-11eb-813a-8937bad0f290.png)

WinUI RadioButton:
![image](https://user-images.githubusercontent.com/45227503/120165584-59b5f500-c219-11eb-8feb-e56c39c31ebf.png)
**Ignore the colour difference, that's just because of my system accent colour.**

**Comment by ecraig12345** [comment]
This is a duplicate of #16258.
