### ISSUE TITLE
Breadcrumb: issue in opening the collapsed menu when it renders inside other react portal component (e.g. modal)

### ISSUE THREAD

**Issue by pankaj-ch** [microsoft/fluentui#18398]
### Environment Information

- **Package version(s)**: 8.16.0
- **Browser and OS versions**: All latest browsers (Chrome, chromium based Edge, firefox)

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluentui-breadcrumb-inside-modal-issue-9sr50

#### Actual behavior:

![Bug-breadcrumb_inside_modal](https://user-images.githubusercontent.com/37103845/120283483-dc51b980-c2d8-11eb-96b8-b060af126650.gif)

#### Expected behavior:

The collapsed menu should open up inside the portal based components (e.g. MaterialUI Dialog/Modal component)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes

Requested priority: (Blocking, High, Normal, Low)
Normal

**Comment by gouttierre** [comment]
@pankaj-ch - Thank you for reaching out and submitting this issue with the detailed repro. I see you are willing to submit a PR for this fix? If you have a solution in mind would you mind sharing it with us? Thanks in advance.

cc @miroslavstastny
