### ISSUE TITLE
Scrollable details list 

### ISSUE THREAD

**Issue by ZhehooMorgen** [microsoft/fluentui#18413]
#### Describe the feature that you would like added

Make details list scrollable when having too many items while leaving the header and footer position fixed.

#### What component or utility would this be added to

details list 

#### Have you discussed this feature with our team, and if so, who

no

#### Additional context/screenshots

no

**Comment by ecraig12345** [comment]
This is already possible with existing props and some custom styling. There's an open PR #18249 adding an example of this to the website, and you can see a simplified live example here: https://codesandbox.io/s/18413-detailslist-scrollable-with-fixed-headers-fdepm?file=/src/index.tsx
