### ISSUE TITLE
Customize the time delay between user stop input and call onGetErrorMessage of textfield or other components

### ISSUE THREAD

**Issue by ZhehooMorgen** [microsoft/fluentui#18412]
#### Describe the feature that you would like added

Customize the time delay between user stop input and call onGetErrorMessage of textfield or other components

#### What component or utility would this be added to

Text field

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

No

**Comment by ecraig12345** [comment]
Have you tried using TextField's `deferredValidationTime` prop?

**Comment by ZhehooMorgen** [comment]
Sorry, missed this prop
