### ISSUE TITLE
Load data to item list when scroll is happened

### ISSUE THREAD

**Issue by piyumi25** [microsoft/fluentui#18416]
I am using Basic DetailList to show search results for an Outlook Addin. I need to load data to the list when scrolling. I went through the documentation and I found that data list is re-rendering when scrolling but we have to load data initially. Is there a way to fulfill my requirement using DetailList? 
https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic

**Comment by gouttierre** [comment]
@piyumi25  - Thanks for reach out to us. 
Have you taken a look at our [FAQ's ](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist) section that talks about scrollable content? i.e.
`My scrollable content isn't updating on scroll. What should I do?`

Also, we recommend you review our implementation API for the DetailsList and if you still need assistance - please reach out to us again and make sure to add a CodePen with your request so our team can help you further. 
You can start from one of the [DetailsList](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
