### ISSUE TITLE
targetWidthProportion on DetailsList is not properly working

### ISSUE THREAD

**Issue by tomsato-ms** [microsoft/fluentui#18425]
### Environment Information

- **Package version(s)**: latest version
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/tomothehiro/pen/mdWXKev

#### Actual behavior:

targetWidthProportion is not taken into consideration when generating the width.

#### Expected behavior:

targetWidthProportion should distribute the width of the column in proportion to the number given as described [here](https://github.com/microsoft/fluentui/blob/d85af4b0eb272cadeb80a9ac71e0552d14653e4e/packages/react/src/components/DetailsList/DetailsList.types.ts#L369-L375)

Please refer to the codepen above, but when same minWidth and targetWidthProportion are given to all 4 columns, it does not distribute the column width equally. Instead, it seems like width of 70 is given to the last 3 columns, and all the remaining width is given to the first column
```
        minWidth: 70,
        targetWidthProportion: 1,
```
![image](https://user-images.githubusercontent.com/74430582/120539340-57c86f00-c39c-11eb-98ef-68ad041ff166.png)

I don't think minWidth should be a required field, but instead have users be able to provide either the minWidth or the targetWidthProportion to determine the column width.

### Priorities and help requested:

Are you willing to submit a PR to fix?  (No)

Requested priority: (High)

Products/sites affected: (Azure Portal)

**Comment by tomsato-ms** [comment]
Also, documentation has a typo in line 372, it should be `3/4` not `2/4`
```
   * have widths of 1 and 3, they will respectively occupy (1/4) = 25% and (2/4) = 75% of the remaining space. Note that
```

**Comment by gouttierre** [comment]
@tomsato-ms - thanks for filing this issue and providing the details for the repro. 

@miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue? Also, could we confirm the documentations is correct as pointed out by @tomsato-ms. Thanks

**Comment by BerserkerDotNet** [comment]
@tomsato-ms @gouttierre @miroslavstastny, Looking at the [PR that introduced this change](https://github.com/microsoft/fluentui/pull/16874/files) I can see that `targetWidthProportion` is not used, instead there is `flexGrow` with exactly the same comment (without a typo ;)) and it works as expected if layout mode is set to fixed columns. `layoutMode={DetailsListLayoutMode.fixedColumns}`

Additionally, `DetailsListProportionalColumnsProps` is also not used anywhere, that is why there is no entry in the examples for this feature.

**Comment by ling1726** [comment]
@tomsato-ms  Does the property proposed by @BerserkerDotNet mitigate your issue ?

**Comment by tomsato-ms** [comment]
@ling1726 `flexGrow` does not mitigate the issue. I tested the property on my CodePen, but same issue is still happening where width are not distributed equally to all columns. It's still giving minWidth to the last 3 columns, and all the rest of the width to the 1st column.
https://codepen.io/tomothehiro/pen/mdWXKev
![image](https://user-images.githubusercontent.com/74430582/126710441-6115113c-b63e-471e-941d-752a24eac4a7.png)

**Comment by BerserkerDotNet** [comment]
@tomsato-ms, change the layoutMode from justified to fixedColumns. flexGrow does not work with justified layout.

**Comment by tomsato-ms** [comment]
I see, it does work with the `layoutMode: fixedColumns` and `flexGrow`
Thanks, I will close the issue.

**Comment by BerserkerDotNet** [comment]
@tomsato-ms glad I could help.

@ling1726 I still thin k there are things to fix as part of this issue:
1. Remove `targetWidthProportion` field as it is not used and misleading
2. Update the docs and include samples for the `flexGrow` as they are not currently listen in the samples website
