### ISSUE TITLE
Not getting type checking or autocomplete for makeStyles in VS Code

### ISSUE THREAD

**Issue by jtbandes** [microsoft/fluentui#18423]
### Environment Information

- **Package version(s)**: `@fluentui/react`: 8.16.0
- **Browser and OS versions**: macOS 11.4, VS Code 1.56.2

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/goofy-microservice-2yftg?file=/src/index.tsx

I'm not getting autocomplete options for CSS keys or values inside of makeStyles:
<img width="363" alt="image" src="https://user-images.githubusercontent.com/14237/120536184-8f74ee00-c37f-11eb-9cd2-2e52f0c909b8.png">
<img width="382" alt="image" src="https://user-images.githubusercontent.com/14237/120536403-c9de8b00-c37f-11eb-9685-b2fdbf4d5645.png">

I suspect the behavior changed with https://github.com/microsoft/fluentui/pull/18376 since with older dependencies on codesandbox, I do see some working autocomplete.

Note that you can work around the problem with explicit typing:

```ts
// autocomplete works now
const useStyles = makeStyles<{ [key in "foo"]: IStyle }>(...)
```

#### Actual behavior:

VS Code / TS doesn't understand the set of available keys or values for those keys

#### Expected behavior:

I should get autocomplete for CSS property names. I might also expect to get type **errors** when invalid values are used, but I see that IRawStyleBase has `string` as a fallback for many types?

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
Hi @jtbandes, I can see now why the autocomplete would break if you don't pass any type as the generic, I'll open a PR shortly to address the issue.

We do have `string` as a fallback for many CSS property values, I would suggest opening another issue for that problem though, as that is not exactly related to the other issue you are describing here.

**Comment by jtbandes** [comment]
Filed https://github.com/microsoft/fluentui/issues/18426 to discuss stricter CSS property typing
