### ISSUE TITLE
Stricter CSS typing for IStyle/IRawStyleBase

### ISSUE THREAD

**Issue by jtbandes** [microsoft/fluentui#18426]
#### Describe the feature that you would like added

As a user of the component/style libraries, I would hope that any invalid CSS values would be caught by the TS compiler, meaning that IStyle should have stricter type annotations.

I also want the values to show up in intellisense/autocomplete suggestions by VS Code, which requires that the known values be included in the type, even if the type also has a `string` or `number` fallback.

Currently the CSS property types in IStyle are quite permissive, for instance:

```ts
const style: IStyle = {
  display: 'this is invalid' // no type error
}
```

I'm sure there are some potential negative or overly-restrictive impacts of this change but I think it's worth discussing.

#### What component or utility would this be added to

style-utilities

#### Have you discussed this feature with our team, and if so, who

https://github.com/microsoft/fluentui/issues/18423#issuecomment-853320085

**Comment by ecraig12345** [comment]
We actually used to have stricter type checking here, but it was removed sometime in the past year or so for reasons I don't recall. @dzearing could probably provide more details.

**Comment by gouttierre** [comment]
@jtbandes - thanks for filing this request. I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.

@dzearing - Do you have any information you could possibly share? Thank you

**Comment by dzearing** [comment]
The issue is that the css objects can contain selectors:

```
mergeStyles({
 background: 'red',
 ':hover': {
    background: 'blue'
 }
});
```

...which means that in order to satisfy typings, the key must be `[key: string]: IRawStyle`.

I believe that there are types that say "background should be a string", so providing a number gives you an error. But that's the background.

**Comment by dzearing** [comment]
FWIW we started the API off by grouping selectors under a `selectors` property, which allowed for more typing strictness. Unfortunately this is different than every other styling library which allow for selectors within the object, and adds typing friction and bundle bloat.
