### ISSUE TITLE
Fluent Desktop Icon font or SVG  not available for designer

### ISSUE THREAD

**Issue by Prasanthnb78** [microsoft/fluentui#18438]
Fluent desktop icon font or SVG  not available for designers using Figma or Adobe software.

**Comment by Prasanthnb78** [comment]
Any updates?

**Comment by gouttierre** [comment]
@Prasanthnb78 -  thanks for filing this request. 

I’ve flagged this as "requires design" but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. However, if you have a proposal on the solution design and would like to contribute please do so and submit a PR for our team to review.
