### ISSUE TITLE
Incorrect control type "group" is provided to all the check boxes present in the "DropDown" control in fabric when multiselect select dropdown expanded pop up

### ISSUE THREAD

**Issue by Renuka8796** [microsoft/fluentui#18436]
**Environment Information:**
Package version(s): "@fluentui/react": "^7.126.0",
Browser and OS versions: chrome and Windows 10
**Describe the issue:**
Incorrect control type "group" is provided to all the check boxes present in the "DropDown" control in fabric when multiselect select dropdown expanded pop up

Please provide a reproduction of the issue in a codepen: https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown

**Actual behavior:**
Incorrect control type "group" is provided to all the check boxes present in the "Dropdown" expanded pop up.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/51446798/120604964-28ccfe80-c46b-11eb-8038-4020f74ad8dc.png)

**Expected:**
Incorrect control type "check box" should be provided to all the check boxes present in the "Dropdown" expanded pop up.

**Comment by gouttierre** [comment]
@Renuka8796 - thanks for filing this issue with us and providing background context. 

@ling1726 -  Would you be able to confirm if this is a regression, or if this behavior is an issue?
