### ISSUE TITLE
Add a test to ensure compatibility with TS 3.9

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#18440]
Since our consumer TS min bar is 3.9 for `@fluentui/react` version 8, but our repo is compiling with TS 4.1, we need to ensure we don't introduce any TS 3.9-incompatible public APIs or .d.ts.

A "good enough" approach (may not catch all cases but is easy to implement):
- In a temp directory, scaffold a basic package with TS 3.9 and relevant fluentui deps (gzipped local versions, similar to projects-test)
- Make an index file with does `export * from /*all the fluentui deps*/` -- basically just something to get TS to parse all the .d.ts files for exported stuff
- Attempt to compile

OPEN QUESTION: what's the consumer TS minbar for converged? Does it need to be included in this test?

**Comment by TristanWatanabe** [comment]
TS minbar test package for react-components merged with #20406
