### ISSUE TITLE
Create definition files for Fluent UI web components

### ISSUE THREAD

**Issue by janechu** [microsoft/fluentui#18463]
### Describe the issue:

To leverage intellisense and other tooling that might take advantage of this information, the VS Code custom data format should be used to create `.json` files for each web components. This will allow users using the VS Code editor to gain intellisense of the web components and for other tooling, especially the tooling created by the FAST project, to generate UI for editing components.

The JSON files should be created for each component then exported from another file so that they can be bundled together.

Examples of how to leverage VS Code custom data format can be found in the FAST repository:
https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/src/anchor/anchor.vscode.definition.json

It would also be beneficial to add a JSON Schema validation step to these JSON files, however this issue only pertains to the JSON files themselves.

Requested priority: Blocking

Products/sites affected: create.fast.design

**Comment by gouttierre** [comment]
@janechu - Thanks for filing this issue with us. 
@chrisdholt - Would you be able to able to review this issue and provide any updates when possible?

**Comment by chrisdholt** [comment]
> @janechu - Thanks for filing this issue with us.
> @chrisdholt - Would you be able to able to review this issue and provide any updates when possible?

Yep, @janechu and I are on the same internal team - I'll be picking this up after we merge our vNext branch.
