### ISSUE TITLE
in DetailsList - Custom Item Columns, the function _renderItemColumn does'nt support in react typescript

### ISSUE THREAD

**Issue by racheliWeiss** [microsoft/fluentui#18465]
i am copying this code to react typescript and the function renderItemColumn  been red 

Type '(item: IExampleItem, index: number, column: any) => Element' is not assignable to type '(item?: any, index?: number | undefined, column?: any[] | IColumn | undefined) => ReactNode'.
  Types of parameters 'index' and 'index' are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.ts(2322)
DetailsList.types.d.ts(143, 5): The expected type comes from

**Comment by racheliWeiss** [comment]
this code in fluent UI
https://developer.microsoft.com/de-de/fluentui#/controls/web/detailslist/customitemcolumns

**Comment by racheliWeiss** [comment]
I am sorry 
i am Begins employee  that new  in web 
i am found a solution  to my problem
https://codepen.io/atneik/pen/EGwLWM

**Comment by racheliWeiss** [comment]
hi 
I don't succeed to  fix the bug 
I need that see as in the example
![table](https://user-images.githubusercontent.com/75696575/121160215-8e96fd00-c854-11eb-9ac5-a0c19c34c146.png)

I copy the code from fluent UI https://developer.microsoft.com/de-de/fluentui#/controls/web/detailslist/customitemcolumns
![bug in list](https://user-images.githubusercontent.com/75696575/121161064-4cba8680-c855-11eb-9fb6-72aaf5fdb044.png)

but this in give bug in onrenderItem because the declared columns
![i an try to fix](https://user-images.githubusercontent.com/75696575/121161084-50e6a400-c855-11eb-9ca0-21b82bef1a3d.png)
i try this but have  bug
![io](https://user-images.githubusercontent.com/75696575/121162123-50024200-c856-11eb-86a6-d10ed8c36e3a.png)

**Comment by racheliWeiss** [comment]
hi
I don't succeed to fix the bug
I need that see as in the example
![table24](https://user-images.githubusercontent.com/75696575/121167340-83df6680-c85a-11eb-90f6-6983079c9514.png)
I copy the code from fluent UI https://developer.microsoft.com/de-de/fluentui#/controls/web/detailslist/customitemcolumns
![bug in list](https://user-images.githubusercontent.com/75696575/121167389-9063bf00-c85a-11eb-970d-f1f04561a81a.png)

but this in give bug in onrenderItem because the declared columns
![Uploading i an try to fix.png…]()

i try this but have bug
![io](https://user-images.githubusercontent.com/75696575/121167429-99ed2700-c85a-11eb-9884-3a3413674fbd.png)

**Comment by racheliWeiss** [comment]
this code with bug
https://codesandbox.io/s/rough-cache-vgl3p?file=/src/DetailList.tsx

**Comment by gouttierre** [comment]
@racheliWeiss - Thanks for filing this issue with us and actively providing more information with the necessary CodePens for your problem. 

@ling1726 -  Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by ling1726** [comment]
@racheliWeiss the issue here is that the declared types for those callbacks use optional arguments. Therefore to make the types match you should also use optional types and add appropriate guards.

I've forked your sandbox and fixed TS issues by using [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) but I would recommend that you refactor your logic based on the presence of the optional values: https://codesandbox.io/s/fluent-ui-detailslist-forked-x741j?file=/src/DetailList.tsx

**Comment by racheliWeiss** [comment]
Thank you!
This very helped me.
