### ISSUE TITLE
TooltipHost: add prop for setting the overflowing element

### ISSUE THREAD

**Issue by mwangi-njuguna** [microsoft/fluentui#18477]
#### Describe the feature that you would like added
Currently TooltipHost component exposes an overflowMode prop which accepts either `Self` or `Parent` mode. While this is sufficient for most use-cases, there is scenario where the 'overflowing' element is nested in another element i.e is a child element.
This presents some problems: 
- One needs to hover on the exact overflowing element instead of the parent to trigger the tooltip .
- The tooltip doesn't get triggered on keyboard navigation due to the nesting.

![image](https://user-images.githubusercontent.com/36155862/121172160-10d8ee80-c860-11eb-9219-ee0ea7ee0917.png)

It would be great to expose an `overflowElement: HTMLElement` prop and maybe add another `overflowMode` to allow consumers to define the overflowing element.

Maybe something like: 

```
// Show Tooltip 
private _onTooltipMouseEnter = (ev: any): void => {
    ...
    if(overflowMode !== undefined){
        const targetElement = this._targetElement();
        const hasNoOverflow = (overflowElement && !hasOverflow(overflowElement)) || (targetElement && !hasOveflow(targetElement))
        if(hasNoOverflow){
            return;
         }
    }
    ...
}
```
Something am wary about is the probable confusion on the positioning of the tooltip by other users.

#### What component or utility would this be added to
TooltipHost 

#### Have you discussed this feature with our team, and if so, who

NA

#### Additional context/screenshots

NA

**Comment by gouttierre** [comment]
@mwangi-njuguna - Thanks for reaching out. I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. If you come up with a solution in the interim please, feel free to submit a PR for the feature.
