### ISSUE TITLE
Multiselect drop down retrieves incorrect selection in onChange

### ISSUE THREAD

**Issue by WieserSoftware** [microsoft/fluentui#18476]
### Environment Information

- **Package version(s)**: 8.1.7
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/WieserSoftware/pen/yLMqBLZ?editors=1111

#### Actual behavior:

The selections retrieved in onChange are out of date compared to what the change was.

#### Expected behavior:

The selectedOptions should represent the latest change.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No.

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by WieserSoftware** [comment]
This worked correctly in office-fabric-react/7, and is a consequence of using hooks, I believe.

**Comment by gouttierre** [comment]
@WieserSoftware - thanks for filing this issue and providing the repro - I see your problem.

@ling1726 -  Would you be able to confirm if this is a regression, or if this behavior is an issue? The issue apparently does not repro in v7.

**Comment by ling1726** [comment]
@WieserSoftware  Thanks for the repro this is definitely a bug. From what I can see it occurs here:
https://github.com/microsoft/fluentui/blob/91e053b6cfb80ed71f99957fc1e6b92f67920ab3/packages/react/src/components/Dropdown/Dropdown.base.tsx#L458-L459

The `onChange` callback should be called from within the `setState` call. The state simply hasn't updated when the `onChange` callback is invoked.

This is a pretty bad bug, marking as hipri.

@gouttierre can you find someone in the v8 team to address this ?
