### ISSUE TITLE
Convert to hooks

### ISSUE THREAD

**Issue by cbirts** [microsoft/fluentui#18486]
#### Describe the feature that you would like added

Details List Compact Example

#### What component or utility would this be added to

When will this example be converted to a function using hooks?

#### Have you discussed this feature with our team, and if so, who

no

**Comment by ecraig12345** [comment]
This is not something our team plans to address in the near future due to other priorities. But if you'd like to submit a PR converting this example to use hooks, we'd be happy to review it.

**Comment by hetanthakkar1** [comment]
@ecraig12345 I am on it

**Comment by cbirts** [comment]
Thank you.

**Comment by cbirts** [comment]
I am requesting that this issue be closed. Looking for an alternate route and examples.
