### ISSUE TITLE
The role prop for button is assigned to <button> element and its wrapper

### ISSUE THREAD

**Issue by lijunle** [microsoft/fluentui#18484]
### Environment Information

- **Package version(s)**: @fluentui/react 8.17.1
- **Browser and OS versions**: All Browser

### Describe the issue:

***Update:*** Sorry, I figured out, the `role` attribute is actually assigned with props spread here:

https://github.com/microsoft/fluentui/blob/e81620081c85eaf0224b3bc290bf15f589ca7281/packages/react/src/components/Button/BaseButton.tsx#L328

However, it is an issue that, the `role` is assigned twice on the wrapper and the <button> element. See my [this reply](https://github.com/microsoft/fluentui/issues/18484#issuecomment-858140241) for details.

---

<del>The `props.role` for `Button` is not assigned correctly on the `<button>` element. Instead, it is assigned to `SplitButtonContent` here: </del>

<del>https://github.com/microsoft/fluentui/blob/e81620081c85eaf0224b3bc290bf15f589ca7281/packages/react/src/components/Button/BaseButton.tsx#L618</del>

<del>We want to assign the `role=none` to a disabled button. But it is not working so it causes a accessibility issue.</del>

#### <del>Expected behavior:</del>

<del>The `role` prop should be assigned on the `<button>` element here:</del>

<del>https://github.com/microsoft/fluentui/blob/e81620081c85eaf0224b3bc290bf15f589ca7281/packages/react/src/components/Button/BaseButton.tsx#L225</del>

### <del>Documentation describing expected behavior</del>

<del>https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role</del>

**Comment by paul-otten** [comment]
I wanted to call out that I am also seeing this issue with CommandBarButton (which renders a BaseButton) despite setting role="none".

**Comment by lijunle** [comment]
There is another side of this issue. If the button is a split button, the `role` props is assigned twice - on the `div` wrapper element and the `button` element.

Repro here: https://codepen.io/lijunle/pen/BaWOjKj?editors=1010

![image](https://user-images.githubusercontent.com/1296500/121436923-46500b80-c936-11eb-965f-b05c14aee1a7.png)

It causes the issue that, the inner `role=menuitem` is not host under `role=menubar` or `role=menu`. The accessibility check will fail.

**Comment by miroslavstastny** [comment]
>  If the button is a split button, the role props is assigned twice - on the div wrapper element and the button element.

After testing and talking to @lijunle, this is the issue.
Repros both in 7.170.3 and 8.17.4.

@smhigley could you please check and share your opinion?

**Comment by smhigley** [comment]
Yup, the nested `menuitem` roles is a known issue with SplitButton that we can't really fix without introducing breaking changes (a lot of the discussion around the keyboard behavior and structure of vNext SplitButton was to fix this problem there).

The incorrect nested button/menuitem roles on SplitButton are tied to the current keyboard behavior, which treats it as a single tab stop, but it still has two nested interactive items. The nested roles enable a passable screen reader experience using both tabbing and virtual cursor. We can't change the roles without splitting it into two tab stops, but we can't do that in v8.

Right now we're pretty much just focused on mitigating any screen reader issues with the non-standard structure of this control, and vNext will address the underlying issue.

**Comment by benkaiser** [comment]
@smhigley are you sure this cannot be fixed in a backwards-compatible way? Could we add an additional prop to override the nested roles?

It's important that we fix this issue for v7 (which we consume) rather than resorting to hacky workarounds.

**Comment by lijunle** [comment]
@smhigley @benkaiser

While I am making the changes, I do think this is **not** a breaking change. The change only touches the split button and nobody could *expect* there are two roles in a split button. We should consider this as a patch fix instead of a breaking change.

Here are the PR to fix the issues in v7 and v8.

- v8: https://github.com/microsoft/fluentui/pull/18697
- v7: https://github.com/microsoft/fluentui/pull/18696

**Comment by smhigley** [comment]
The backwards-compat issue is with changing the keyboard behavior, not with changing the roles. However, we can't get rid of the wrapper's role without changing the keyboard behavior, since that's the element that actually gets focus.

The only thing we could feasibly do is make both inner elements presentational/not menuitems, but that is actually likely to degrade the experience with virtual cursor and touch exploration. The solution is to completely get rid of the parent menuitem and have the splitbutton be two tab stops (or arrow stops, in a menubar), but that's where we run into the backwards compat issue.

**Comment by lijunle** [comment]
Had a discussion with @smhigley 

See this comment for details: https://github.com/microsoft/fluentui/pull/18697#discussion_r662652772

I am closing this bug and looking forward to next major version with split button improvements.
