### ISSUE TITLE
Integrate babel-make-styles  to CI tests

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/fluentui#18489]
PR #18481 has disabled `babel-make-styles` plugin from VR tests due to untracked errors that were being emitted.

#### Describe the feature that you would like added

Re-integrate `babel-make-styles` plugin into the CI tests to ensure we're shipping it tested.

**Comment by layershifter** [comment]
I debugged the problem, it's related to a fact that we evaluating too much code. The minimal repro is:

```tsx
import { makeStyles } from '@fluentui/react-make-styles';
import { storiesOf } from '@storybook/react';

export const useStyles = makeStyles({
  container: theme => {
    return { color: 'red' };
  },
});

storiesOf('FOO', module).addStory('BAR', () => null);
```

```
TypeError: office-ui-fabric-react\packages\babel-make-styles\__fixtures__\test\code.tsx: (0 , _react.storiesOf)(...).addStory is not a function office-ui-fabric-react\packages\babel-make-styles\__fixtures__\test\code.tsx:24
    (0, _react.storiesOf)('FOO', module).addStory('BAR', function () {
                                         ^

    TypeError: (0 , _react.storiesOf)(...).addStory is not a function

      at __fixtures__/test/code.tsx:24:38
      at __fixtures__/test/code.tsx:43:3
      at Module.evaluate (../../node_modules/@linaria/babel/src/module.ts:310:12)
      at evaluate (src/utils/evaluatePathsInVM.ts:43:7)
```

And it's valid because `storiesOf` contains only:

```js
{
  kind: 'MakeStyles',
  add: [Function],
  addDecorator: [Function],
  addParameters: [Function]
}
```

---

We should integrate `@linaria/shaker` to improve performance and avoid such issues.

**Comment by layershifter** [comment]
#18680 solved the issue described above (https://github.com/microsoft/fluentui/issues/18489#issuecomment-866764198), but unfortunately it's not the last problem related to enabling plugin.

---

- I reverted locally change from #18481 (i.e. enabled plugin back)
- Removed `apps/vr-tests/node_modules/.cache/storybook` (to ensure that cache for `babel-loader` is clear)
- Removed `packages/react-tabster/lib` (this package contains reusable styles that are used other packages)
- Ran `yarn workspace vr-tests start`

This leads to the failure and broken stories:

```
WARNING in ./src/stories/MakeStyles.stories.tsx
Module build failed (from office-ui-fabric-react/node_modules/babel-loader/lib/index.js):
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '@fluentui/react-theme-provider'
Require stack:
- office-ui-fabric-react\packages\react-provider\lib-commonjs\components\FluentProvider\renderFluentProvider.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._resolveFilename (office-ui-fabric-react\node_modules\@linaria\babel\lib\module.js:323:60)
    at Module.resolve (office-ui-fabric-react\node_modules\@linaria\babel\lib\module.js:119:23)
    at Module.Object.assign.ensure (office-ui-fabric-react\node_modules\@linaria\babel\lib\module.js:143:29)
    at office-ui-fabric-react\packages\react-provider\lib-commonjs\components\FluentProvider\renderFluentProvider.js:14:30
    at office-ui-fabric-react\packages\react-provider\lib-commonjs\components\FluentProvider\renderFluentProvider.js:42:3
    at Script.runInContext (vm.js:127:20)
    at Module.evaluate (office-ui-fabric-react\node_modules\@linaria\babel\lib\module.js:284:12)
    at Module.Object.assign.ensure (office-ui-fabric-react\node_modules\@linaria\babel\lib\module.js:188:15)
    at office-ui-fabric-react\packages\react-provider\lib-commonjs\components\FluentProvider\FluentProvider.js:12:30
    at office-ui-fabric-react\packages\react-provider\lib-commonjs\components\FluentProvider\FluentProvider.js:19:3
    at Script.runInContext (vm.js:127:20)
```

It happens then Babel plugin evaluates code in Node environment:

https://github.com/microsoft/fluentui/blob/c939e67b1840a9eb5f7706afcda8c14df8f18d33/packages/babel-make-styles/src/utils/evaluatePathsInVM.ts#L33-L35

But it does not know about Webpack aliases 💣 To solve this issue Linaria (we are using evaluation part from `@linaria/shaker` & `@linaria/babel`) has Webpack loaders:

https://github.com/callstack/linaria/blob/e92bcd93ed51b847cab0c9e3fa7c578328c1ddaf/packages/webpack5-loader/src/index.ts#L87-L96

---

To solve this issue I will work on Webpack loader, initially it will only pass down aliases to the plugin.

**Comment by layershifter** [comment]
Closing in favor of #18936.
