### ISSUE TITLE
Detailslist: Can't select text on multiple selection mode

### ISSUE THREAD

**Issue by davidmualem77** [microsoft/fluentui#18491]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**:NA

### Please provide a reproduction of the bug in a codepen:

When configuring the Multi Select in the following demo: https://fabricweb.z5.web.core.windows.net/oufr/8.17.2/#/examples/detailslist/variablerowheights,
then the text in all of the cells isn't selectable and can't be copied.

#### Actual behavior:

Text can't be selected / copied.

#### Expected behavior:

The same behavior as in Single Select or None configuration

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by ecraig12345** [comment]
This is a duplicate of #16174 and currently by design; see https://github.com/microsoft/fluentui/issues/16174#issuecomment-749685645 for a workaround and more details on the reasoning behind the current behavior.

**Comment by davidmualem77** [comment]
Thanks for the help!
