### ISSUE TITLE
createTheme() and a following loadTheme should not resiult in warnings

### ISSUE THREAD

**Issue by Link631** [microsoft/fluentui#18510]
I am using latest react with latest fluent ui.

#### Actual behavior:
const theme = createTheme();
loadTheme(theme);

result in log:
couple of warnings, telling that theming values are not provided telling, that they will use a fallback.

#### Expected behavior:
When i create a theme via createTheme and then load this theme, there should no warnings be written into the log, even not when it is within a debug build.

I started a discussion here, but after debugging, I found out that the createTheme provides me a theme with sematic colors set.
https://github.com/microsoft/fluentui/discussions/18508

**Comment by gouttierre** [comment]
@Link631  - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
