### ISSUE TITLE
[fluentui/react-icons-northstar] filled EmojiIcon is actually EmojiSurprisedIcon

### ISSUE THREAD

**Issue by Hirse** [microsoft/fluentui#18522]
### Environment Information

- **Package version(s)**: `"@fluentui/react-icons-northstar": "0.56.0"`
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:
![Comparison of EmojiIcon and EmojiSurprisedIcon](https://user-images.githubusercontent.com/2564094/121631375-d922a000-ca33-11eb-9507-0621bc1b973f.png)

https://codesandbox.io/s/fluent-ui-0560-emojiicon-k3h8e

#### Actual behavior:
`EmojiIcon` in filled (i.e. without `outline` prop) looks like `EmojiSurprisedIcon`.

#### Expected behavior:
`EmojiIcon` in filled (i.e. without `outline` prop) looks like a filled version of the outline version of `EmojiIcon`.

### Priorities and help requested:

Are you willing to submit a PR to fix? No, this probably requires the SVG of the correct icon.

Requested priority: Low

Products/sites affected: Demo site

**Comment by gouttierre** [comment]
@Hirse - Thanks for filing this issue with us.

@kolaps33 - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by FxWxP** [comment]
Although it was closed automatically it is a bug and we would kind of need this to work properly. Is there any chance this might get fixed, or do we need to start looking for a workaround?
