### ISSUE TITLE
ThemeProvider from react-theme-provider: Object is not a function

### ISSUE THREAD

**Issue by lynamemi** [microsoft/fluentui#18531]
### Environment Information

- **Package version(s)**: @fluentui/react-theme-provider 0.18.7
- **Browser and OS versions**: Mac Big Sur, Edge chromium

#### Actual behavior:

I've been testing `ThemeProvider` from `@fluentui/react-theme-provider` in product. It seems to work seamlessly in one repo, but in another repo, I consistently get this error regardless of where or how I'm using it:

![Screen Shot 2021-06-11 at 11 48 29 AM](https://user-images.githubusercontent.com/16619843/121737194-68b86500-caad-11eb-89a4-a594737d7650.png)

![Screen Shot 2021-06-10 at 3 15 48 PM](https://user-images.githubusercontent.com/16619843/121737218-6fdf7300-caad-11eb-99c8-7da3601e2fdf.png)

I don't notice any meaningful package versions differences in the repo that works and the one that doesn't, but there could be if I knew what to look for.

Here is an example of how I am replacing `Customizer`:
```tsx
// <Customizer settings={{ theme }}>
<ThemeProvider theme={theme}>
```

#### Expected behavior:

I would expect to be able to follow the docs for ThemeProvider implementation and not get an error.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) OneDrive & SharePoint

**Comment by ecraig12345** [comment]
What versions of `@fluentui/react-theme-provider` and `@fluentui/react` (or `office-ui-fabric-react`) are you using in the repo where you see this error?

**Comment by ecraig12345** [comment]
Also note that if you're using `@fluentui/react` version 8, you should be importing ThemeProvider directly from `@fluentui/react` and **not** using `@fluentui/react-theme-provider`. This happened because of some direction changes between when we initially introduced the package and when we released version 8. I know that's confusing and way less than ideal, so we really ought to update `office-ui-fabric-react` version 7 to export ThemeProvider the same way version 8 does.

**Comment by lynamemi** [comment]
Thank you for the response @ecraig12345! We are on: `"office-ui-fabric-react": "7.165.1"` and so that's why I was testing out importing `@fluentui/react-theme-provider`. Admittedly the multiple ThemeProviders is a little confusing but we're starting to make sense of it all!

Both projects, the one where ThemeProvider throws an error and the one that doesn't, use the same `office-ui-fabric-react` version and `@fluentui/react-theme-provider` version.

**Comment by gouttierre** [comment]
@lynamemi - Thank you for the information shared - would you be able to share a CodePen for this to further help the engineering team?
 
@ling1726 - Providing the issue context is sufficient for you to resume investigation - would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by ecraig12345** [comment]
A codesandbox would actually be more helpful here (aka.ms/fabric7sandbox) since multiple packages are involved and it's easier to see the dependency versions on codesandbox.

**Comment by ecraig12345** [comment]
Also, I think the "right" solution here is to update `office-ui-fabric-react` in the `7.0` branch to re-export ThemeProvider, so it can just be imported from there which guarantees the correct version. This would also be more consistent with what people need to do in version 8, reducing confusion.

**Comment by ling1726** [comment]
@lynamemi Sorry but there is no way for us know what role Fluent has in this issue unless we have a more precise repro.

**Comment by lynamemi** [comment]
Our repo is too complex, I can't get it to repro in a code pen. We're likely just going to have to use `Customizer` instead of `ThemeProvider`, which should be fine for us for now until we start adapting @fluentui/react-components.

**Comment by lynamemi** [comment]
@ling1726 I sent our lockfile to @ecraig12345 a bit ago. Elizabeth, let me know if you need anything else from me.

**Comment by layershifter** [comment]
@lynamemi `@fluentui/react-theme-provider` was removed some time ago (#18710). Please consider to use the latest version of `@fluentui/react-components` and let us know if you will have any issues 🙏
