### ISSUE TITLE
Tooltip - Scrollbar inside tooltip is not draggable via mouse whereas content inside tooltip is scrollable using touchpad and mousewheel

### ISSUE THREAD

**Issue by Manjunatha123** [microsoft/fluentui#18547]
### Environment Information

- **Package version(s)**: ( "office-ui-fabric-react": "^6.189.2")
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

Hi,
We are using "office-ui-fabric-react": "^6.189.2" in our project. We have tooltips that have content of more than a paragraph like >30 lines. When the content overflows it is scrollable via touchpad. If mouse is connected content is scrollable through the scroll wheel. If the user is using the scrollbar to scroll the content using mouse the content is not draggable through the scroll bar that is present. We also tried with the demo code present [here](https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip) thinking it may be fixed in latest versions, we did not see the scroll bar working here as well.
 

#### Actual behavior:

Content is not scrollable when scrollbar is tried to drag via mouse. Whereas the content is scrollable via touchpad scroll(drag two fingers together) and content is scrollable via scroll wheel

#### Expected behavior:

If the content inside the tooltip overflows it should be scrollable via touchpad, scrollwheel, and also using the scroll bar drag

### If applicable, please provide a codepen repro:

Here is the [code pen](https://codepen.io/manjunatha123/pen/vYxQdjL) sample of what we have done in our project.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@Manjunatha123 - thanks for filing this item and I looked at the later version and I see that I was unable to scroll.

@ling1726 -  Would you be able to confirm if this is a regression, or if this behavior is an issue when scrolling overflowed content within the tooltips? Thanks

**Comment by ling1726** [comment]
From what I can see, the issue seems to be with the `beakCurtain` which actually overlays the callout element in the tooltip, so you're not clicking on the scrollbar, you're clicking on another div:

![image](https://user-images.githubusercontent.com/20744592/126653024-1a9a4fbf-c1f7-4a2f-bdbc-f5b4b35efd93.png)

In devtools if you set the `ms-Callout-main` div to `position: absolute` you will be able to break the stacking context and click on the scrollbar. There might be other ways to achieve this though.

**Comment by ling1726** [comment]
Triaging as low priority, since this is a fairly rare edge case, because a tooltip with such a large overflow that requires scrolling is not a normal usage for the component
