### ISSUE TITLE
react-northstar published package is missing a readme

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#18546]
`@fluentui/react-northstar` as published to npm has no readme. 😢  https://www.npmjs.com/package/@fluentui/react-northstar

There's a readme under https://github.com/microsoft/fluentui/blob/master/packages/fluentui/README.md so maybe that could be moved to the northstar package, or copied in pre-publish or something?

**Comment by hetanthakkar1** [comment]
@ecraig12345 Can i add the readme!?

**Comment by ecraig12345** [comment]
@hetanthakkar1 Thanks but it's probably best to let @miroslavstastny or another member of the northstar team handle this, since they'll have a better idea of what content should be there.

**Comment by gouttierre** [comment]
@ecraig12345 - I will assign this item to @kolaps33.
