### ISSUE TITLE
Modal ignoreExternalFocusing prop doesn't work (round 2)

### ISSUE THREAD

**Issue by samlh** [microsoft/fluentui#18564]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^8.15.0",
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

```tsx
<script src="//unpkg.com/react@16/umd/react.development.js"></script>
<script src="//unpkg.com/react-dom@16/umd/react-dom.development.js"></script>

<script src="//unpkg.com/@fluentui/react/dist/fluentui-react.js"></script>

<div id='content'></div>
```

```tsx
const { DefaultButton, ThemeProvider, Modal } = window.FluentUIReact;

const Content = () => {
  const [isOpen, setIsOpen] = React.useState(false);
  // NOTE: This template uses @fluentui/react version 8.
  // To use version 7, start from https://aka.ms/fabric7pen
  return (
    <ThemeProvider>
      <DefaultButton onClick={() => setIsOpen((isOpen) => !isOpen)}>
        Hello World
      </DefaultButton>
      <Modal
        isOpen={isOpen}
        ignoreExternalFocusing
        isBlocking={false}
        onDismiss={() => {
          setIsOpen(false);
          // Note: is true
          console.error("onDismiss", document.activeElement == document.body);
        }}
        onDismissed={() => {
          // Note: is true
          console.error("onDismissed", document.activeElement == document.body);
          setTimeout(() => {
            // Note: should be true, but is false (because focus was reset to the Hello World button)
            console.error(
              "onDismissed setTimeout",
              document.activeElement == document.body
            );
          }, 0);
        }}
      >
        Modal content
      </Modal>
    </ThemeProvider>
  );
};

ReactDOM.render(<Content />, document.getElementById("content"));
```

#### Actual behavior:

Focus is reset to the previously focused element, even with ignoreExternalFocusing set

Note: This appears to be caused by Popup completely ignoring shouldRestoreFocus.

#### Expected behavior:

Focus should not be reset to the previously focused element

### Priorities and help requested:

Are you willing to submit a PR to fix? Not sure

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by samlh** [comment]
A previously reported bug with the same symptom: https://github.com/microsoft/fluentui/issues/11514

Unfortunately, it looks like the fix from that bug has regressed.

**Comment by gouttierre** [comment]
@samlh - thank you for filing this issue with us and sharing your findings.

@ling1726 -  Would you be able to confirm if this is a regression, or if this behavior is an issue? Not sure if you will need to revisit #11514. 
cc @ecraig12345

**Comment by ling1726** [comment]
I can confirm this behaviour even on the examples on the public docsite. According #11514 a fix was applied so this should be a regression in v8.

FYI @ecraig12345

**Comment by samlh** [comment]
?

**Comment by samlh** [comment]
Will double-check, but I think this is still an issue.

**Comment by khmakoto** [comment]
@samlh let us know if it is, happy to reopen the issue if that's the case
