### ISSUE TITLE
From peoplepicker which user is removed on click of remove (X) icon after selection of user

### ISSUE THREAD

**Issue by sailakshmi1711558** [microsoft/fluentui#18572]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:
From peoplepicker which user is removed on click of remove (X) icon after selection of user
![image](https://user-images.githubusercontent.com/66770444/122095470-0d7acf80-ce2b-11eb-902a-027efd805700.png)

#### Expected behavior:

On click of remove button need to get the user details
### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@sailakshmi1711558 - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. 
You can start from one of the [PeoplePicker ](https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker) examples (click “Export to CodePen”) or https://aka.ms/fluentpen. Always try to provide us with as much information to assist you, such as the version etc. Thank you.

**Comment by joshmccall221** [comment]
> @sailakshmi1711558 - Thanks for filing this, but you’ll need to add a CodePen repro before we can help.
> You can start from one of the [PeoplePicker ](https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker) examples (click “Export to CodePen”) or https://aka.ms/fluentpen. Always try to provide us with as much information to assist you, such as the version etc. Thank you.

screenshot is from demo/doc site:
https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker

@sailakshmi1711558, looks like it has been addressed in v8.23.7
