### ISSUE TITLE
Focus Restore call on previous Focused element from ContextualMenu/SubMenus is not correct

### ISSUE THREAD

**Issue by pagaur** [microsoft/fluentui#18574]
### Environment Information

- **Package version(s)**: V8

### Please provide a reproduction of the bug in a codepen:
a) https://codepen.io/pagaur/pen/NWpMGbb
    
b) **WithoutSubMenu:** https://codepen.io/pagaur/pen/rNyvzPa

#### Actual behavior:
I see two issues here:
1) In #a and #b after click on submenu item 'move focus on click', I see focus call happening on SearchBox in _tryFocusPreviousActiveElement  but failing in the example. If the focus call has succeeded it will steal the focus from the input box next to SearchBox.

We have observed that happening in office apps. VSO:4848946 which we trying to fix with[ PR](https://office.visualstudio.com/OC/_git/office-online-ui/pullrequest/705463)
I see IPopupRestoreFocusParams as {containsFocus:true, documentContainsFocus:true, originalElement: SearchBox} o.previosActiveElement:SearchBox
I think containsFocus (which I assume states if the contextual menu contains the focus or not) should come false here we might be checking containsFocus flag as we were doing in V7 code of contextualMenu.Base.tsx. BTW/FYI we observe this issue with V7 code as well.
![image](https://user-images.githubusercontent.com/13493382/122093093-8ba18c80-cdbf-11eb-9ca5-050d9b255b9f.png)
![image](https://user-images.githubusercontent.com/13493382/122096247-349db680-cdc3-11eb-8d0c-d2c1fca1c878.png)

2). In above codepen #a) focus is getting lost when the menu item 'should restore focus on click' is clicked which should restore back the focus to previous original element ie. SearchBox. I see focus call happening on SearchBox in _tryFocusPreviousActiveElement but seems failing.
![image](https://user-images.githubusercontent.com/13493382/122089937-1e402c80-cdbc-11eb-9858-334ab31de657.png)
I see IPopupRestoreFocusParams as {containsFocus:true, documentContainsFocus:true, originalElement: SearchBox} o.previosActiveElement:SearchBox
These prams looks fine to me, **please Ignore this issue** if it's example only issue.

#### Expected behavior:
1. clicking 'move focus on click' should not invoke focus call on SearchBox (even if it fails in the example). If we let caller of contextual menu to override the behavior we should introduce one more argument in IPopupRestoreFocusParams to convey this information that popup has lost focus, so caller can avoid restorefocus to happen.
2. clicking should restore focus should restore back focus in SearchBox.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: Excel Online office app

**Comment by pagaur** [comment]
FYI @ecraig12345

**Comment by gouttierre** [comment]
@pagaur - thank you for filing this issue and providing the CodePens.

@ling1726 -  Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by ling1726** [comment]
Sorry @pagaur  I don't entirely get 1)
> In #a and #b after click on submenu item 'move focus on click', I see focus call happening on SearchBox in _tryFocusPreviousActiveElement but failing in the example. If the focus call has succeeded it will steal the focus from the input box next to SearchBox.

When I click `move focus on click` the next input is focused, is that what you expect from the behaviour ?

2) The issue is that the search box is not focused after clicking on `restore focus` right ? 

I would also recommend you to split these two problems into separate issues, so it's easier to track

**Comment by pagaur** [comment]
for #1. yes, I expect the focus to get moved to the input control next to it, which is happening in the example as one can expect; But when you do a closer look we call to restore focus back to the original searchbox inside _tryFocusPreviousActiveElement, which failed in the example. In case the focus call got succeeded it would have steal the focus back from the next input box.

The expectation here is to add logic in _tryFocusPreviousActiveElement to avoid restore focus call back to the original search box in case the focus in not contained within the menu. I think the containsFocus flag should be false in this case.
![image](https://user-images.githubusercontent.com/13493382/126807791-ff6569e9-6579-4efe-9e75-26a2e269ad7a.png).


Please feel free to separate out issue#2, I see the restore call happening as expected in this case, but why it failed in the example is what that issue covers. In actual product I don't see the same to be happening; thus that issue is of lower priority.

**Comment by pagaur** [comment]
@ling1726 BTW the [issue #1](https://office.visualstudio.com/OC/_workitems/edit/4848946/) reproduces in Excel-online app.
