### ISSUE TITLE
Add `"sideEffects": false` for `@fluentui/react-icons`. Reduced our build time from 78s to 17s

### ISSUE THREAD

**Issue by JamesBurnside** [microsoft/fluentui#18573]
#### Describe the feature that you would like added

Add `"sideEffects": false` to the react-icons package.json
![image](https://user-images.githubusercontent.com/2684369/122095361-226f4880-cdc2-11eb-81d4-8efc5e539c42.png)

#### Why

This tells bundlers&transpilers that they can ignore non-imported modules
https://webpack.js.org/configuration/optimization/#optimizationsideeffects

I believe this to be OK for this package as each icon is a totally isolated module with no side effects on other icons.

#### What component or utility would this be added to

`@fluentui/react-icons` package

#### Additional context

Adding this manually to the package.json in the node modules MASSIVELY helped our `tsc` build times, from 78s to 17s

| Without sideEffects: false | With sideEffects: false |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/2684369/122095815-b2ad8d80-cdc2-11eb-83d2-93a41845e487.png) | ![image](https://user-images.githubusercontent.com/2684369/122095889-c5c05d80-cdc2-11eb-9f49-3bc6b7ef1333.png) |

From the output (crucially IO read time and parse time) it indicates tsc is no longer having to load and parse the 7000+ icon files

**Comment by tomi-msft** [comment]
PR in fluent-system-icons repo that adds this flag: https://github.com/microsoft/fluentui-system-icons/pull/282
