### ISSUE TITLE
DatePicker should have ability to show in UTC time or other time zones

### ISSUE THREAD

**Issue by Shannon-Ke** [microsoft/fluentui#18576]
#### Describe the feature that you would like added

There should be a control where developers can set a DatePicker to show dates in different timezones.

#### What component or utility would this be added to

This would probably be a prop on the DatePicker where we could set a timezone type.

**Comment by ecraig12345** [comment]
You can already customize the date display using DatePicker's `formatDate` and `dateTimeFormatter` props. Implementing more detailed time zone handling is highly complex, so it's not something we plan to support in the library itself.
