### ISSUE TITLE
Textfield with Type Time not working on Safari

### ISSUE THREAD

**Issue by shockoe-hatch** [microsoft/fluentui#18588]
There seems to be an issue with Textfield with type Time in safari. 

### Environment Information

- **Package version(s)**:  v7.146.2
- **Browser and OS versions**: Safari v14.1

Isolated issue
```
const { 
  DefaultButton,
  ThemeProvider,
  TextField
} = window.FluentUIReact;

const Content = () => {
  return (
    <ThemeProvider>
     <TextField
        type={'time'}
      />
      <DefaultButton 
        onClick={() => alert("hello")}
      >
        Hello World
      </DefaultButton>
    </ThemeProvider>
  );
};

ReactDOM.render(
  <Content />, 
  document.getElementById("content")
);
```

#### Actual behavior:
This is the error I get in code pen
``
"The above error occurred in the <t> component:
    in t (created by Styledt)
    in Styledt (created by Content)
    in div (created by ThemeProvider)
    in ThemeProvider (created by Content)
    in Content
"
``

#### Expected behavior:

Expected to be able to use text field with type time in safari.

### Priorities and help requested:

Requested priority: Normal

**Comment by gouttierre** [comment]
@shockoe-hatch - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [TextField ](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
