### ISSUE TITLE
https://developer.microsoft.com/en-us/fluentui#/controls/web is not loading

### ISSUE THREAD

**Issue by Promhize** [microsoft/fluentui#18595]
### Environment Information

- **Package version(s)**: (https://developer.microsoft.com/en-us/fluentui#/controls/web)
- **Browser and OS versions**: (Brave 1.25.70 and Edge 91.0.864.37)

#### Actual behavior:

  * Go to https://developer.microsoft.com/en-us/fluentui#/controls/web
  * Documentation does not load

**Comment by ecraig12345** [comment]
Can you try loading it again? It's working for me now, so maybe it was an intermittent issue.

If it's still not working for you, can you check the console for any script or network errors?
