### ISSUE TITLE
Navigation not working in DatePicker using preact.

### ISSUE THREAD

**Issue by huxiasusan1989** [microsoft/fluentui#18596]
### Environment Information

- **Package version(s)**:  FluentUI 8
- **Browser and OS versions**: Any
- **framework**: preact

### Describe the issue:

Navigation not working in DatePicker using preact.

### Please provide a reproduction of the issue in a codepen:

In preact framework, include datepicker on page, navigation not work.

#### Actual behavior:

Navigation not working using left/right/up/down key.

#### Expected behavior:

Navigation should work.

### Documentation describing expected behavior
This issue is caused by following two functionalities not supported in preact.
1. In preact, the focus event is not bubbled to parent element(in current case, FocusZone does not get this event to set ActiveElement), so use addEventListener in FocusZone.js to capture this bubble event should solve this. Code is like "this._root.current && this._root.current.addEventListener('focus', this._onFocus, true);"
2. In preact, if the attribute value is boolean false, it will be ignored when rendering the element(in current case, the attribute is data-is-focusable in CalendarGridDayCell.js) which will cause the element can be focusable which should not, so converting false to "false" can fix this issue. Code is like this " var isFocusable = !ariaHidden && (allFocusable || (day.isInBounds ? true : undefined)); isFocusable = typeof(isFocusable) === "boolean" ? isFocusable.toString() : isFocusable;"

**Comment by ecraig12345** [comment]
We don't officially support Preact, so unfortunately we can't invest in fixing this issue. And even if there was a feasible fix and someone was willing to contribute it, there would be no guarantee that it would continue working in the future since we don't test against Preact. Sorry we can't be more helpful with this.
