### ISSUE TITLE
Dropdown component: ARIA attribute element ID does not exist on the page: aria-labelledby="downshift-6-label" error

### ISSUE THREAD

**Issue by aubreyquinn** [microsoft/fluentui#18598]
```
    "dependencies": {
        "@fluentui/react-northstar": "^0.53.0",
        "@fluentui/react-northstar-emotion-renderer": "^0.53.0",
        "@microsoft/teams-js": "^1.8.0",
        "@uifabric/merge-styles": "7.19.1",
        "date-fns": "2.19.0",
        "dompurify": "^2.2.6",
        "react": "^16.13.1",
        "react-dom": "^16.13.1"
    },
```

I am using the Dropdown component in my project: [Fluent UI - Dropdown (windows.net)](https://fluentsite.z22.web.core.windows.net/0.53.0/components/dropdown/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#types-search-multiple)

I want to use the component for searching and selecting out of multiple items.
I tried to use the example provided:
```
import React from 'react'
import { Dropdown } from '@fluentui/react-northstar'

const inputItems = [
  'Robert Tolbert',
  'Wanda Howard',
  'Tim Deboer',
  'Amanda Brady',
  'Ashley McCarthy',
  'Cameron Evans',
  'Carlos Slattery',
  'Carole Poland',
  'Robin Counts',
]

const DropdownExampleSearchMultiple = () => (
  <Dropdown
    search
    multiple
    items={inputItems}
    placeholder="Start typing a name"
    getA11ySelectionMessage={getA11ySelectionMessage}
    noResultsMessage="We couldn't find any matches."
    a11ySelectedItemsMessage="Press Delete or Backspace to remove"
  />
)

const getA11ySelectionMessage = {
  onAdd: item => `${item} selected. Press left or right arrow keys to navigate selected items.`,
  onRemove: item => `${item} has been removed.`,
}
export default DropdownExampleSearchMultiple
```

When I run Storybook though, it does not pass all the accessibility tests:
<img width="1920" alt="Issue" src="https://user-images.githubusercontent.com/80953505/122413721-7faff900-cf7e-11eb-8112-0e6b49c3c19d.PNG">

I think this could be an issue with the Dropdown component.

**Comment by kolaps33** [comment]
I was investigating it and it appears as well on our fluent ui doc site.
Duplicate bug was reported here:
https://github.com/microsoft/fluentui/issues/18703

But as there is placeholder then screen reader narrate properly the placeholder. 

So definitely it is bug which we should fix, but I wouldn't consider it as high priority.

**Comment by gouttierre** [comment]
@aubreyquinn - Thanks for reach out. 

@kolaps33 - I see you were investigating this issue - thanks for that. I will assign the issue to you and update the labels.
