### ISSUE TITLE
SSR keyframe names clash with animation name on production builds

### ISSUE THREAD

**Issue by PatoBeltran** [microsoft/fluentui#18608]
### Environment Information

- **Package version(s)**:  FluentUI React latest (8.19.1)

### Please provide a reproduction of the bug in a codepen:

I was able to create a new nextjs app to repro this issue. Our product  currently doesn't use nextjs and it's getting the same behavior, so it's not an issue with the framework (we use plain node/express setup for our SSR, nextjs was used here for convenience of creating the repro).

https://github.com/PatoBeltran/fluent-ssr-test

#### Actual behavior:

When opening a callout (like the one used by the overflow menu on an action bar) on 400% zoom on production builds of products using SSR, the callout flashes and disappears. This doesn't happen on dev builds on the same product.

The theory of what's going on here is that the CSS keyframes are being registered on file import, instead of being registered lazily on getters. This causes the keyframes to not be correctly namespaced in the server side generated stylesheet and thus clashing with the client styles. On development build this seems to work just because the resulting client keyframes name match exactly the ones generated by the server side, but on production build tree shaking or other optimization causes file loading to be different and thus making these keyframes names not match.

#### Expected behavior:

The expected behavior should be to have the callout showing correctly and letting the user interact with them on both dev and production builds in the same way. As I understand the internals of the library, the server side generated styles should not clash with client side styles and keyframes should be correctly namespaced.

cc\ @khmakoto

**Comment by gouttierre** [comment]
@PatoBeltran - Thank you for filing this issue with us. 

@ling1726 - would you be able to take a look at this one? 
cc @khmakoto

**Comment by ling1726** [comment]
I can repro this issue, thanks for the great repro @PatoBeltran, interestingly if you increase zoom even more past 400% it starts to work, but the positioning is questionable

**Comment by ling1726** [comment]
@khmakoto since you were mentioned in the issue, have you worked in SSR for v8 before ?

**Comment by varholak-peter** [comment]
@PatoBeltran apologies for the lack of transparency on this. The fix introduced a new mechanism for style rehydration on client-side which resolve the issue. It's not enabled by default as that would be a breaking change and it depends on end-user framework.

In order to enable this, follow the updated Wiki entry here: [Server side rendering and browserless testing · microsoft/fluentui Wiki (github.com)](https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing#nextjs-setup)

Here is an example implementation of `_document.js` that enables this functionality.

```js
import * as React from 'react';
import Document, { Head, Html, Main, NextScript } from 'next/document';
import { Stylesheet, resetIds } from '@fluentui/react';

// Do this in file scope to initialize the stylesheet before Fluent UI React components are imported.
const stylesheet = Stylesheet.getInstance();

// Now set up the document, and just reset the stylesheet.
export default class MyDocument extends Document {
  static getInitialProps({ renderPage }) {
    resetIds();

    const page = renderPage(function AppRenderer(App) {
        return function ComponentRenderer(props) {
            return <App {...props} />
        }
    });

    return { ...page, styleTags: stylesheet.getRules(true), serializedStylesheet: stylesheet.serialize() };
  }

  render() {
    return (
      <Html>
        <Head>
          <style type="text/css" dangerouslySetInnerHTML={{ __html: this.props.styleTags }} />
          <script type="text/javascript" dangerouslySetInnerHTML={{ __html: `
            window.FabricConfig = window.FabricConfig || {};
            window.FabricConfig.serializedStylesheet = ${this.props.serializedStylesheet};
          ` }} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```
