### ISSUE TITLE
Search dropdown with duplicated items

### ISSUE THREAD

**Issue by grnkvch** [microsoft/fluentui#18617]
If pass to search dropdown multiple same values it breakes dropdown list behavior, duing the search.

![image](https://user-images.githubusercontent.com/43145804/122528140-afb1d780-d024-11eb-957d-d68edb21bdbe.png)

![image](https://user-images.githubusercontent.com/43145804/122528430-fc95ae00-d024-11eb-811f-9accaaf8e134.png)
![image](https://user-images.githubusercontent.com/43145804/122528483-0d462400-d025-11eb-8730-e7502245e1b9.png)

Actual behavior: 
If in item's list occurs duplicated item it leads to adding extra duplicated item to list of results with every typed symbol.
Extra items do not desappear after search query cleared.
Expected  behavior:
In result list actual count of duplicated items displayed.
Extra items desappear after search query cleared.

Link to codesandbox repo 
https://codesandbox.io/s/m4xz7?module=/example.js&file=/example.js

**Comment by hetanthakkar1** [comment]
I am trying to solve this

**Comment by grnkvch** [comment]
The problem can be solved by specifying `renderItem` prop, and explicitly pass some unique `key` prop for dropDownItem, but I think it's too mach hacky way to handle such simple case

**Comment by hetanthakkar1** [comment]
> The problem can be solved by specifying `renderItem` prop, and explicitly pass some unique `key` prop for dropDownItem, but I think it's too mach hacky way to handle such simple case

@ecraig12345 What do you think about this approach

**Comment by gouttierre** [comment]
@grnkvch - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [Dropdown ](https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by ecraig12345** [comment]
From the screenshot it looks like this is an issue with northstar, so you'll need to use codesandbox for a repro.

**Comment by grnkvch** [comment]
> From the screenshot it looks like this is an issue with northstar, so you'll need to use codesandbox for a repro.

https://codesandbox.io/s/m4xz7?module=/example.js&file=/example.js

**Comment by grnkvch** [comment]
> The problem can be solved by specifying `renderItem` prop, and explicitly pass some unique `key` prop for dropDownItem, but I think it's too mach hacky way to handle such simple case
 Repo with such work around 
 https://codesandbox.io/s/fluent-ui-example-forked-ujm4i?file=/example.js
