### ISSUE TITLE
Center DirectionalHint renders TeachingBubble too far to one side

### ISSUE THREAD

**Issue by shandysulen** [microsoft/fluentui#18629]
### Environment Information

- **Package version(s)**: >= 8
- **Browser and OS versions**: Windows 10 Version 21H1 (OS Build 19043.1052), Edge Version 91.0.864.48

### Repro:

It looks like I can reproduce this with any of the Fluent UI 8 package versions, including the [8.20.0 demo site](https://fabricweb.z5.web.core.windows.net/oufr/8.20.0/).

1. Scroll down to the _Coachmark position_ dropdown and select _Bottom center_
2. Click the _Show coachmark_ button
3. Hover over the coachmark and notice that the teaching bubble is not centered with the button.
4. If you click anywhere on the page or resize the window, the teaching bubble becomes centered.

![image](https://user-images.githubusercontent.com/15238391/122599241-e129a380-d022-11eb-986f-06d0f8e8ab47.png)

This can be reproduced with any of the center positions.

An interesting thing I found is that I was unable to reproduce this on my Surface Book 3 laptop, yet I was consistently able to repro this on my larger, secondary Dell monitor...My first thought was it must be dependent on viewport width, but interestingly enough, I'm unable to repro on my laptop screen even if I make the viewport width that of the secondary monitor, and I'm consistently able to repro on the secondary monitor even if I set the viewport width to that of my laptop screen.

#### Actual behavior:

The teaching bubble is not centered with the button.

#### Expected behavior:

In Fluent UI 7 demo sites, the teaching bubble is centered. I expect the teaching bubble to grow "around" the beak so the beak still stays center on the target element.

### Priorities and help requested:

Are you willing to submit a PR to fix? Not enough time on my hands unfortunately

Requested priority: Normal

**Comment by gouttierre** [comment]
@shandysulen - thanks for filing this issue with us and providing the information around the problem.

@smhigley -  Would you be able to confirm if this is a regression, or if this behavior is an issue with the centering of the teaching bubble?

**Comment by smhigley** [comment]
I wonder if this is related to #18767, it seems that TeachingBubble has a number of issues with positioning 😬

**Comment by smhigley** [comment]
Also: #18227
