### ISSUE TITLE
tools: nx migration generator creates `start` npm script that doesn't work

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#18622]
# Bug report

#### Actual behavior:

After running nx migration generator on converged package via `yarn nx workspace-generator migrate-converged-pkg --name='@fluentui/<package-name>'` -> executing `yarn workspace @fluentui/<package-name> start` will throw error

#### Expected behavior:

`start` should work

#### Fix

`start` needs to include `yarn storybook` to properly call local `storybook` npm task

**Comment by khmakoto** [comment]
Fixed in #18768.
