### ISSUE TITLE
React 18 Readiness for fluentui renderStatic

### ISSUE THREAD

**Issue by khowling** [microsoft/fluentui#18634]
#### Describe the feature that you would like added

React18 is getting SSR & Suspense support, ```ReactDOM.renderToString``` is changing to the stream-based response ```pipeToNodeWritable``` [here](https://github.com/reactwg/react-18/discussions/22). Its very early alpha, but is it possible to provide any guidance (or an alternative API) to use fluentui ```renderStatic``` with the new ```pipeToNodeWritable``` API to avoid fluentui components rendering without css classes before hydration.

#### What component or utility would this be added to

Be great to add any guidance to this excellent wiki [here](https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing)

#### Have you discussed this feature with our team, and if so, who

no

#### Additional context/screenshots

n/a

**Comment by gouttierre** [comment]
@khowling - Thanks for filing this issue with us.

@smhigley and @ecraig12345 can we discuss this one internally in shield on the next steps? Thanks

**Comment by smhigley** [comment]
@khmakoto since you spent some time on SSR bugs, do you have any opinions on how we handle the React change?
