### ISSUE TITLE
Re-introduce old Card package

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#18648]
Since the removal of the experimental Card (formerly from `@uifabric/react-cards`)  in version 8 was pretty sudden and some teams are still using it, we're going to re-introduce it as deprecated to avoid breaking people.

(Each of the top-level items should be a separate PR.)

- [x] Rename converged-WIP Card implementation to `@fluentui/react-card` (singular)
  - Done #18690
- [ ] Add back package contents from version 7 under `@fluentui/react-cards`
  - [ ] Copy code and examples in from v7
  - [ ] Update imports
  - [ ] Update package name
  - [ ] Update version

**Comment by Hotell** [comment]
why is this assigned to v-build project ?

**Comment by ecraig12345** [comment]
> why is this assigned to v-build project ?

It seemed somewhat build-related, but I guess that's not entirely accurate. I moved it.
