### ISSUE TITLE
Contents inside DocumentCardTitle is getting overlapped or clipped after applying the text spacing in the page.

### ISSUE THREAD

**Issue by inateeg** [microsoft/fluentui#18650]
![textspaceOnDocumentCard](https://user-images.githubusercontent.com/20802350/123039770-95bb2080-d3a7-11eb-8a25-5e5fd8be2feb.JPG)
If one use Fabric DocumentCardTile to render the card title values inside the DocumentCard, it renders fine in normal mode but if apply text spacing on the page, the title area height may fix 2 lines of text anymore.  Should fabric component either use ellipse to shorten it to single line when there is not enough area to render in text spacing mode or support different heights? I understand that caller may set the container height.  Is there a way for either height grow in this mode or if not enough to hold two lines, shorten the text so that one line is rendered?

**Comment by nancy2681** [comment]
@inateeg Can you please provide codepen link or screenshot

**Comment by inateeg** [comment]
if you go to DocumentCard sample page, toggle on text spacing you can see some of those view messed up.  Also in Email card case all depend on title text lenght or truncate or not.

**Comment by gouttierre** [comment]
@inateeg - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the DocumentCard examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
