### ISSUE TITLE
CRA template is broken with npm 7

### ISSUE THREAD

**Issue by beckerrobin** [microsoft/fluentui#18662]
When executing the create-react-app npx command with the [fluentui-template ](https://www.npmjs.com/package/@fluentui/cra-template) per the [Microsoft official documentation](https://developer.microsoft.com/en-us/fluentui#/get-started/web#fluent-ui-react) npx shows an "unable to resolve dependency tree"-error:

`npm ERR! code ERESOLVE

npm ERR! ERESOLVE unable to resolve dependency tree

npm ERR!

npm ERR! While resolving: fluent-ui-react@0.1.0

npm ERR! Found: @types/react@17.0.11

npm ERR! node_modules/@types/react

npm ERR!   @types/react@"^17.0.0" from the root project

npm ERR!

npm ERR! Could not resolve dependency:

npm ERR! peer @types/react@">=16.8.0 <17.0.0" from @fluentui/react@7.172.0

npm ERR! node_modules/@fluentui/react

npm ERR!   @fluentui/react@"^7.155.3" from the root project`

**Comment by ecraig12345** [comment]
What's the specific command that you ran, and the full output? I just tried `npx create-react-app my-app --template @fluentui/cra-template` and it works fine for me.

**Comment by beckerrobin** [comment]
That's the exact command I used.

tis 22 juni 2021 kl. 17:43 skrev Elizabeth Craig ***@***.***>:

**Comment by ecraig12345** [comment]
That's very strange. Can you paste the full output?

Also, what Node and npm versions are you using?

**Comment by beckerrobin** [comment]
Currently using LTS (node@14.17.1 and npm@7.18.1) but tried it with the latest branch as well. 

Full log attached.

> c:\dev\learn>npx create-react-app react-fluentui-cra --template @fluentui/cra-template
> 
> Creating a new React app in c:\dev\learn\react-fluentui-cra.
> 
> Installing packages. This might take a couple of minutes.
> Installing react, react-dom, and react-scripts with @fluentui/cra-template...
> 
> 
> added 1918 packages, and audited 1919 packages in 50s
> 
> 145 packages are looking for funding
>   run `npm fund` for details
> 
> 22 vulnerabilities (9 moderate, 13 high)
> 
> To address all issues, run:
>   npm audit fix
> 
> Run `npm audit` for details.
> 
> Initialized a git repository.
> 
> Installing template dependencies using npm...
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: react-fluentui-cra@0.1.0
> npm ERR! Found: @types/react@17.0.11
> npm ERR! node_modules/@types/react
> npm ERR!   @types/react@"^17.0.0" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @types/react@">=16.8.0 <17.0.0" from @fluentui/react@7.172.1
> npm ERR! node_modules/@fluentui/react
> npm ERR!   @fluentui/react@"^7.155.3" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependenc
[2021-06-23T07_16_06_211Z-debug.log](https://github.com/microsoft/fluentui/files/6699806/2021-06-23T07_16_06_211Z-debug.log)
y conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\X\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\X\AppData\Local\npm-cache\_logs\2021-06-23T07_16_06_211Z-debug.log
> `npm install --save @fluentui/react@^7.155.3 @testing-library/j
> [2021-06-23T07_16_06_211Z-debug.log](https://github.com/microsoft/fluentui/files/6699800/2021-06-23T07_16_06_211Z-debug.log)
> est-dom@^5.11.4 @testing-library/react@^11.1.0 @testing-library/user-event@^12.1.10 @types/node@^12.0.0 @types/react@^17.0.0 @types/react-dom@^17.0.0 @types/jest@^26.0.15 typescript@^4.1.2 web-vitals@^1.0.1` failed

**Comment by ecraig12345** [comment]
The root cause is that the template is still using `@fluentui/react` version 7 (which specifies a dep on `@types/react` < 17), when it should be using version 8.

In the meantime, as a workaround you could create a generic app and add `@fluentui/react` as a dep. Or run the template creation command with npm 6 or yarn, and then update the version of `@fluentui/react` in the generated package.json to `^8.0.0`.
