### ISSUE TITLE
NormalPeoplePicker with itemLimit = 1 causes a focus bug

### ISSUE THREAD

**Issue by sushruth** [microsoft/fluentui#18676]
### Environment Information

- **Package version(s)**: 7.172.1
- **Browser and OS versions**: Edge Canary on Windows 10
### Please provide a reproduction of the issue in a codepen:

https://codepen.io/sushruthsastry/pen/poeXRNy

When `itemLimit={1}` is used on a `NormalPeoplePicker` component, selecting a user and then clicking away from the field does not seem to remove the blue outline on it - causing confusion on which field is focused visually.

Repro steps using above codepen -

1. Select a user in the picker
2. Click away

#### Actual behavior:

Clicking away does not lose blue border on the picker

#### Expected behavior:

Clicking away should lose blue border on the picker

**Comment by hetanthakkar1** [comment]
@ecraig12345 Should I solve this issue or you'll first have to confirm from design team regarding this

**Comment by ecraig12345** [comment]
@hetanthakkar1 Thanks for checking and sorry for the delayed response! You can go ahead with this one, since it's definitely not intentional. (I don't have a good idea offhand about why it might be happening.)

**Comment by gouttierre** [comment]
@sushruth - Thanks for filing this issue with us.

@hetanthakkar1 - Thank you for the willingness to look into a fix. We are looking forward to your suggested solution!

**Comment by ecraig12345** [comment]
This seems to be fixed in version 8, likely thanks to some of the work @smhigley has done on accessibility in that component. At this point we won't be able to prioritize fixing it in version 7, though if someone else wants to submit a fix, someone from the team could review it.
https://codepen.io/ecraig12345/pen/qBmLzQo?editors=0010
