### ISSUE TITLE
Focus not visible in checkbox when used inside shadow dom.

### ISSUE THREAD

**Issue by Gargi1810** [microsoft/fluentui#18677]
### Environment Information

- **Package version(s)**: "7.117.4"
- **Browser **: Chrome

### Describe the issue:
Focus not visible in checkbox when used inside shadow dom. Without shadow dom it is working though.
When tabbing to the checkbox the focus/focus-visible classes are not working and there is no focus indication.

#### Actual behavior:

Focus is not visible on tabbing.

#### Expected behavior:

Focus should be visible on tabbing.

**Comment by gouttierre** [comment]
@Gargi1810  - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the checkbox examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
