### ISSUE TITLE
tools: after nx migration build:local does not work

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#18675]
### Repro steps

- clone #18673 or run `yarn nx workspace-generator migrate-converged-pkg --name='@fluentui/make-styles'` (in a case of command please modify `tsconfig.json` as in PR)
- it will add `build:local` to `packages/make-styles/package.json#scripts`
- try to run `yarn workspace @fluentui/make-styles build:local`, a command will fail ❌

```
$ tsc -p . --module esnext --emitDeclarationOnly && node ../../scripts/typescript/normalize-import --output dist/make-styles/src && yarn docs
office-ui-fabric-react\scripts\typescript\normalize-import.js:40
    throw new Error(`${sourceDir} doesn't exist`);
    ^

Error: office-ui-fabric-react\packages\make-styles\dist\make-styles\src doesn't exist
    at main (office-ui-fabric-react\scripts\typescript\normalize-import.js:40:11)
    at Object.<anonymous> (office-ui-fabric-react\scripts\typescript\normalize-import.js:18:1)
```

- notice that for other packages, for example `react-image` it's passing ✅

---

Looks that it's related to a generated structure after the build command and a fact that `@fluentui/make-styles` does not have dependencies from a repo that results in different output in `/dist`:

#### `yarn workspace @fluentui/react-image tsc -p . --module esnext --emitDeclarationOnly`

![image](https://user-images.githubusercontent.com/14183168/123075850-df901f00-d418-11eb-823b-133fd7c906b5.png)

#### `yarn workspace @fluentui/make-styles tsc -p . --module esnext --emitDeclarationOnly`

![image](https://user-images.githubusercontent.com/14183168/123075773-d010d600-d418-11eb-84b2-5ad941959ebd.png)

**Comment by Hotell** [comment]
thanks for excellent report! you find one corner case we didn't think of when implementing hehe


> Looks that it's related to a generated structure after the build command and a fact that @fluentui/make-styles does not have dependencies from a repo that results in different output in /dist:

yeah that's the reason. All of this will be mitigated once we start building  into root `/dist` within monorepo

**Comment by layershifter** [comment]
@Hotell thanks for suggestions, I applied them in #18673 🚀
