### ISSUE TITLE
How to show all the directional icons in rtl?

### ISSUE THREAD

**Issue by libjosep** [microsoft/fluentui#18683]
I am using fluentui react. If my page uses rtl direction, how can I show all the directional icons in the page in rtl form? I see that fabric core automatically do this(https://developer.microsoft.com/en-us/fluentui#/styles/web/localization). Is it possible in fluentui-react?
CodePen: https://codepen.io/libinpjoseph/pen/yLMdveZ?editors=0010

**Comment by gouttierre** [comment]
@libjosep - Thanks for reaching out to us with your question. We added your request to be scheduled for feedback and one of our engineers will get back to you.
