### ISSUE TITLE
Controlled DatePicker with nullish initial value

### ISSUE THREAD

**Issue by aplum** [microsoft/fluentui#18688]
### Environment Information

- **Package version**: @fluentui/react@8.20.2
- **Browser and OS versions**: Not relevant

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/_aplum/pen/gOmNOYZ

#### Actual behavior:

When using DatePicker as a controlled component (i.e. providing the `value` prop), using a nullish initial value doesn't seem to be fully supported.

If the initial value is `undefined` the DatePicker behaves partially as though it's uncontrolled. When `value` is changed via external controls, the DatePicker's text field will update, but its calendar will not.

If the initial value is `null` the DatePicker seems to behave correctly, but according to its [types](https://github.com/microsoft/fluentui/blob/%40fluentui/react_v8.20.2/packages/react/src/components/DatePicker/DatePicker.types.ts#L150) `null` is not valid.

#### Expected behavior:

DatePicker should be usable as a controlled component with a nullish initial value. I'm not sure what "nullish" should mean exactly though (allow `null`? Change the current behaviour with `undefined`?).

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal/Low

Products/sites affected: N/A

**Comment by gouttierre** [comment]
@aplum - thank you for filing this issue with us.

@ling1726 -  Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by ling1726** [comment]
The root cause of this issue is the same as #18575 with the `useControllableValue` hook.

However, the typings should also be fixed to allow `null` as a value

**Comment by aplum** [comment]
This is still relevant, but I'm not going to bother creating a new issue for it right now. Hopefully work related to the aforementioned #18575 will address it 🤷‍♂️.

**Comment by khmakoto** [comment]
@aplum, do you want me to reopen this issue? Happy to if it is still relevant as you suggest 😄

**Comment by aplum** [comment]
@khmakoto Yes please! Thanks!
