### ISSUE TITLE
tools: options in jest.config.js should be added on demand

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#18706]
Currently `migrate-converged-pkg` adds `snapshotSerializers` & `setupFilesAfterEnv` to `jest.config.js`: 

https://github.com/microsoft/fluentui/blob/8e98ad375d22628a00a2f0c0916d657dcfe7f831/tools/generators/migrate-converged-pkg/index.ts#L132-L133

As was discovered in #18673 these options may be redundant for some packages.

### `snapshotSerializers`

This option should be added only if `@fluentui/react-make-styles` is present in `package.json#dependencies`.

### `setupFilesAfterEnv`

This option should be added always. If `./config/tests.js` is missing it should be created with following content:

```js
/** Jest test setup file. */
```

**Comment by Hotell** [comment]
> snapshotSerializers -This option IMO should be added only if @fluentui/react-make-styles is present in package.json#dependencies.

Agreed

> setupFilesAfterEnv -I propose to add this setting based on presence of ./config/tests.js, it is missing this option should not be added.

That makes sense as well. Although I'd like us to have consistent setting within all packages. Meaning if someone wan't to set this up, one will know where it should be done as that scaffolding is already created. WDYT?

**Comment by layershifter** [comment]
> That makes sense as well. Although I'd like us to have consistent setting within all packages. Meaning if someone wan't to set this up, one will know where it should be done as that scaffolding is already created. WDYT?

So always have `setupFilesAfterEnv` and create `./config/tests.js` if it is missing, is my understanding correct?

**Comment by Hotell** [comment]
> > That makes sense as well. Although I'd like us to have consistent setting within all packages. Meaning if someone wan't to set this up, one will know where it should be done as that scaffolding is already created. WDYT?
> 
> So always have `setupFilesAfterEnv` and create `./config/tests.js` if it is missing, is my understanding correct?

yesir 🙌

**Comment by layershifter** [comment]
> > > That makes sense as well. Although I'd like us to have consistent setting within all packages. Meaning if someone wan't to set this up, one will know where it should be done as that scaffolding is already created. WDYT?
> > 
> > 
> > So always have `setupFilesAfterEnv` and create `./config/tests.js` if it is missing, is my understanding correct?
> 
> yesir 🙌

Cool, I updated the issue 👍
