### ISSUE TITLE
DatePicker placeholder text appears disabled in High contrast mode

### ISSUE THREAD

**Issue by RishabhPokharna** [microsoft/fluentui#18707]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Microsoft Edge (Chromium based), OS: Windows 10
- **Tool**: High contrast mode in Windows 10

### Describe the issue:
The Placeholder text in DatePicker component suggests that the field is disabled in High contrast mode. In normal mode, it has the same color as any date value (after date selection). In High contrast mode, the color changes.

### Please provide a reproduction of the issue in a codepen:
1. Render the component at https://codepen.io/rishabhpokharna/pen/rNyEXjv
2. Enable High Contrast Mode (Shortcut: Left SHIFT + Left ALT + Print Screen key)

The issue can also be found in the documentation examples directly:
https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker

#### Actual behavior:
The Placeholder text color in High Contrast mode suggests that it is disabled.
![image](https://user-images.githubusercontent.com/86398881/123262397-76420600-d515-11eb-9b6c-d898aedcfd0f.png)

#### Expected behavior:
Placeholder text should remain consistent (enabled in both or disabled in both modes).

### Documentation describing expected behavior
1. [MAS 4.3.1 – No Disruption of Accessibility Features](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7B672c8a8b-ed4f-463f-868f-e8131caf9b74%7D)
2. https://www.w3.org/WAI/tutorials/forms/instructions/#placeholder-text

**Comment by gouttierre** [comment]
@RishabhPokharna - thank you for fling this issue with us. 

@ling1726 -  Would you be able to confirm if this is a regression, or if this behavior is an issue where text appears disabled in high contrast mode?

**Comment by RishabhPokharna** [comment]
+cc: @Ramesh ***@***.***>, @Vibhor ***@***.***>, @Anupam ***@***.***>
________________________________

**Comment by ling1726** [comment]
This should not be an a11y bug, the native HTML `<input />` has the exact same styling, the indication that the component is disabled is on the outline of the input itself not the placeholder. Fluent does not custom style the placeholder in any way
