### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by soryy708** [microsoft/fluentui#18712]
#### Describe the feature that you would like added

The Windows 11 announcement brings rounded corners to elements of its user interface, which implies that rounded corners become a thing in it's design language (Fluent). Are there plans for Fluent UI to support rounded corners?

#### What component or utility would this be added to

A lot of them, probably through styling.

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

![Pic1](https://c.s-microsoft.com/he-il/CMSImages/1920_Panel08_Picture_Content.jpg?version=e3368c23-e930-eeab-acc7-f86165c062a1)

**Comment by justinforlenza** [comment]
Looks like the new "2020" Fluent UI elements are in the northstar package, which is still a beta product. 

You can check it out here [./packages/fluentui/react-northstar](https://github.com/microsoft/fluentui/tree/master/packages/fluentui)

**Comment by ecraig12345** [comment]
@justinforlenza `@fluentui/react-northstar` is a separate older library used primarily in Teams. We're currently working on a "converged" library `@fluentui/react-components` which incorporates learnings from both `@fluentui/react` and `@fluentui/react-northstar`, as well as design updates including rounded corners. 

You can see a demo of the components that we have so far at https://aka.ms/fluentui-storybook, though note that the components are still in alpha and APIs may change significantly before release. We'll also be updating our documentation in the next couple months with more info about the new components, and better disambiguation between the libraries.

**Comment by justinforlenza** [comment]
Ah okay, thanks for the clarification, it was the only thing I could find with something that resembled rounded styling.

**Comment by ecraig12345** [comment]
It's okay, I agree that our documentation in this area needs a lot of clarification/expansion, it's just been hard to find the time.
