### ISSUE TITLE
XAML Styles for Teams Fluent Theme

### ISSUE THREAD

**Issue by xperiandri** [microsoft/fluentui#18724]
#### Describe the feature that you would like added

I want to build my Teams app using Uno Platform which is UWP code running on WASM.
So that I need UWP XAML Styles of Teams Fuent Theme to make the same look and feel.

Are they available?
Can you make such styles?

**Comment by gouttierre** [comment]
@xperiandri - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
