### ISSUE TITLE
Datepicker crashes after selecting first day of the week

### ISSUE THREAD

**Issue by pedroldk** [microsoft/fluentui#18736]
### Environment Information

- **Package version(s)**: The one used on the Fluent UI website
- **Browser and OS versions**: Edge, Chrome, Firefox (latest versions)

#### Actual behavior:
Cannot test the datepicker, it crashes when selecting the first day of the week. Can see that there is something wrong on that page in the console.

![Animation](https://user-images.githubusercontent.com/480413/123505723-9f1ee400-d658-11eb-915d-332b1c3f1281.gif)

![image](https://user-images.githubusercontent.com/480413/123505563-bdd0ab00-d657-11eb-902d-68a0a6cf3d8b.png)

#### Expected behavior:

Being able to use the datepicker correctly and select the first day of the week.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal (it might be bad for new users to have the example page blowing up.

Products/sites affected: https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker

**Comment by hetanthakkar1** [comment]
@pedroldk Can i work on this or you're working on it currently?

**Comment by pedroldk** [comment]
> @pedroldk Can i work on this or you're working on it currently?

I won't be able to pick it up until tomorrow so please go ahead :)

**Comment by hetanthakkar1** [comment]
@pedroldk Thanks I am on it

**Comment by hetanthakkar1** [comment]
@pedroldk Not only datepicker but the whole website crashes
