### ISSUE TITLE
onScroll event of ScrollablePane is not fired while running on react version 17.0.2

### ISSUE THREAD

**Issue by arunvenu87** [microsoft/fluentui#18744]
### Environment Information

- **Package version(s)**: 8.20.2
- **react**: 17.0.2

#### Actual behavior:

The `onScroll` event of  `ScrollablePane` is not fired while using `react` version 17 .

#### Expected behavior:

The `onScroll` event of  `ScrollablePane` should be fired.

### If applicable, please provide a codepen repro:
It is working when `react` version 16.8.6 is used
https://codepen.io/arunvenu87/pen/gOWOPpq

It is **not** working when `react` version 17.0.2 is used
https://codepen.io/arunvenu87/pen/YzVzwPj

### Priorities and help requested :

Are you willing to submit a PR to fix? No

Requested priority: High

**Comment by arunvenu87** [comment]
This behavior might be related to [this ](https://github.com/facebook/react/pull/19464)breaking change.

**Comment by gouttierre** [comment]
@arunvenu87 - Thanks for filing this issue with us.

 @smhigley - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by bsunderhus** [comment]
Here's a better to change version example: https://codesandbox.io/s/onscroll-event-of-scrollablepane-is-not-fired-while-running-on-react-version-dq9un

**Comment by bsunderhus** [comment]
Seems like the `onScroll` method from the root element in `ScrollablePane` is not being invoked on v17.0.2 I'll be proposing a PR for  a fix

**Comment by piedras77** [comment]
@bsunderhus any updates on when the pull request fixing this will be merged? Thanks

**Comment by Wezea** [comment]
Unfortunately, the PR expired and has been closed. 

We would highly appreciate to get this merge, as this is currently blocking us to migrate to React v17.
