### ISSUE TITLE
migration(babel-make-styles): after migrating via nx generator, tests don't work

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#18757]
### Describe the issue:

After migrating `babel-make-styles` to new dx via `nx workspace-generator migrate-converged-pkg`, tests will fail to pass.

**Issue:** Looks like code within `__fixtures__` is not being transpiled, thus throwing an error:

![2021-06-29 at 16 58](https://user-images.githubusercontent.com/1223799/123820961-48850480-d8fb-11eb-8712-8538405d41b8.png)

Previously it relied on running `build` prior to running tests

```sh
build => lib/__fixtures__/....compiled_code_to_common_js => run test => test consume `lib/*` instead of `src/*` 
```

**Repro:**

```
yarn nx workspace-generator migrate-converged-pkg --name='@fluentui/babel-make-styles'

rm -rf packages/babel-make-styles/.storybook

```

update `tsconfig.json` to keep the original target/lib

```json
{
  "extends": "../../tsconfig.base.json",
  "include": ["__fixtures__/**/code.ts", "src"],
  "compilerOptions": {
    "target": "ES2015",
    "module": "CommonJS",
    "lib": ["ES2017","DOM"],
    "jsx": "react",
    "outDir": "dist",
    "declaration": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "noUnusedLocals": true,
    "preserveConstEnums": true,
    "types": ["jest", "custom-global", "inline-style-expand-shorthand", "node", "babel-helper-plugin-utils"]
  }
}
```

execute

```sh
yarn workspace @fluentui/babel-make-styles test --no-cache
```

**Comment by layershifter** [comment]
`babel-make-styles` uses [`babel-plugin-tester`](https://github.com/babel-utils/babel-plugin-tester), unfortunately it does not have any filters to run a single fixture 😥

- I went to `packages/babel-make-styles/__fixtures__` and deleted all folders except
- `yarn workspace @fluentui/babel-make-styles test --no-cache`, errors now are less cryptic:

```
 FAIL   babel-make-styles  src/plugin.test.ts (10.134s)
  @fluentui/babel-make-styles fixtures
    × object variables (1038ms)

  ● @fluentui/babel-make-styles fixtures › object variables

    office-ui-fabric-react\packages\babel-make-styles\__fixtures__\object-variables\code.ts: Cannot find module './modules-by-versions' from 'get-modules-list-for-target-version.js'

    However, Jest was able to find:
        './modules-by-versions.json'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'tsx', 'js', 'jsx'].
```

In previous config we had `json` in `moduleFileExtensions`:

https://github.com/microsoft/fluentui/blob/35e244ed457284f24aab445da2cc556fa827a79a/scripts/jest/index.js#L8

I added `json` to `/jest.preset.js`:

```diff
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
- moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
+ moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  testPathIgnorePatterns: ['/node_modules/', '/lib/', '/lib-commonjs/', '/dist/'],
```

And restored deleted files, tests are passing 🎉

```
Test Suites: 1 passed, 1 total
Tests:       21 passed, 21 total
Snapshots:   0 total
Time:        14.561s
```

---

Overall is makes sense, but I don't understand how it's related to the initially reported error 🤨
