### ISSUE TITLE
NVDA is not announcing Selected state for the option from drop down 

### ISSUE THREAD

**Issue by PoojaOtari** [microsoft/fluentui#18753]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

**Comment by gouttierre** [comment]
@PoojaOtari - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [dropdown ](https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
