### ISSUE TITLE
TeachingBubble beak doesn't align correctly when zoomed

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#18767]
### Describe the issue:
This repros on the main docs site: https://developer.microsoft.com/en-us/fluentui#/controls/web/teachingbubble

When you zoom to 200% or more, the beak points off to the left instead of up at the trigger (assuming the bubble was opened below the button).

![screenshot showing the beak pointing to the left at high zoom](https://user-images.githubusercontent.com/3819570/123872975-a2c99980-d8ea-11eb-801d-ee0d481b0d0d.png)

(linked to [12466](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/12466))

**Comment by czearing** [comment]
I am curious if this may have to do with TeachingBubble's wrapper Callout. The [Directional Example](https://developer.microsoft.com/en-us/fluentui#/controls/web/callout) interestingly shows some similar behavior with the beak:
 
![Callout bug](https://user-images.githubusercontent.com/7192338/124634156-dd778880-de3a-11eb-8f38-cc78f84fe97c.gif)
