### ISSUE TITLE
babel-make-styles is being used in co-located storybooks

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#18775]
### Environment Information

- **Package version(s)**:  vNext DX packages

### Describe the issue:

The babel-make-styles plugin should not be used in storybook since it requires the package to be rebuilt (#18357). The migration to new colocated storybooks will always use the `babelrc.json` in vNext packages which which will run the plugin. This was not  a problem with the old DX since the main storybook config was not colocated to packages (i.e. no babelrc.json file)

`babel-loader` will load the `babelrc.json` file in the current package if it exists, there is no way to stop this from happening by configuring babel or storybook configs. [Where this happens in babel-loader](https://github.com/babel/babel-loader/blob/7fdf6f4ca85d4f7c25ca7952b6ec51f5cb059762/src/index.js#L164).

#### Actual behavior:

Babel plugin is being when running `yarn storybook` or `yarn start` -> kills no-rebuild DX because styles won't be rebuilt

#### Expected behavior:

Stories should not be using built time transform styles. However, `yarn build` should still use the `babel-make-styles`

### Repro:

* Run `yarn storybook` in `packages/react-menu`
* Open browser devtools
* find `useMenuPopoverStyles` in the `sources` tab
* Look at unmapped src:
![image](https://user-images.githubusercontent.com/20744592/123960585-c0ad0200-d9af-11eb-99d5-41241586f2fa.png)

* See that built styles are being used:
![image](https://user-images.githubusercontent.com/20744592/123960494-a4a96080-d9af-11eb-909d-40bcbe944a54.png)

#### Customize `babel-loader` plugin

[babel-loader can be customized with a loader builder](https://github.com/babel/babel-loader/blob/7fdf6f4ca85d4f7c25ca7952b6ec51f5cb059762/src/index.js#L164). We can create a custom loader that will remove every babel-plugin called `babel-make-styles` in the storybook webpack config in `main.js`.

```js
// .storybook/main.js
module.exports = /** @type {Pick<import('../../../.storybook/main').StorybookConfig,'addons'|'stories'|'webpackFinal'>} */ ({
  // ...
  webpackFinal: (config, options) => {
    const localConfig = { ...rootMain.webpackFinal(config, options) };
    // can use a cleaner way of finding the loader
    localConfig.module.rules[0].use[0].options.customize = path.resolve(__dirname, './customize.js');
    return localConfig;
  },
  // ...
});

// .storybook/customize.js
module.exports = () => {
  return {
    config(cfg) {
      const plugins = cfg.options.plugins.filter(plugin => {
        return plugin.file.request !== 'module:@fluentui/babel-make-styles';
      });

      cfg.options.plugins = plugins;
      return cfg.options;
    },
  };
};
```

#### Use env settings in `.babelrc.json`
 ```json
{
  "env": {
    "production": {
      "plugins": [
        "module:@fluentui/babel-make-styles",
        "annotate-pure-calls",
        "@babel/transform-react-pure-annotations"
      ]
    }
  }
}
```

#### Use `babel.config.js` instead of `.babelrc.json`
```js
module.exports = api => {
  const plugins = ['annotate-pure-calls', '@babel/transform-react-pure-annotations'];

  // doesn't need to be caller, can be anything that distinguishes dev loop from CI loop
  const isStorybook = api.caller(caller => caller && caller.name === 'babel-loader');
  if (isStorybook) {
    return {
      plugins,
    };
  }

  return {
    plugins: [...plugins, 'module:@fluentui/babel-make-styles'],
  };
};
```

**Comment by Hotell** [comment]
the proposed solution is not necessary IMO, we can use what SB suggests

![2021-06-30 at 15 01](https://user-images.githubusercontent.com/1223799/123964847-2c916980-d9b4-11eb-96bf-de827811c2dc.png)

thus overriding babel config for particular context -> in our case storybook

**Comment by ling1726** [comment]
@Hotell  we tried what is [described in docs](https://storybook.js.org/docs/riot/configure/babel)

Adding a custom .babelrc.json without babel-make-styles
```json
{
  "plugins": ["module:@fluentui/babel-make-styles", "annotate-pure-calls", "@babel/transform-react-pure-annotations"]
}
```

Got these kinds of errors:
```
WARNING in ./src/Menu.stories.tsx
Module build failed (from /home/lingga/fluenui/node_modules/babel-loader/lib/index.js):
SyntaxError: /home/lingga/fluenui/packages/react-menu/src/Menu.stories.tsx: Unexpected token, expected "," (28:29)
```

Seems like the custom babel config needs to contain all the presets

**Comment by Hotell** [comment]
> Seems like the custom babel config needs to contain all the presets

right it won't merge, doesn't work if `overrides` are used as well ( I guess it works only if babelrc is a js file )....

**Comment by ling1726** [comment]
We also tried to create `babel.config.js` using [storybook's default config](https://github.com/storybookjs/storybook/blob/e31c79277b55fb62cbccff4b80cb2b1fb59746ed/lib/core-common/src/utils/babel.ts#L50)

The result was:

![image](https://user-images.githubusercontent.com/20744592/123968475-89daea00-d9b7-11eb-8b40-e32a4bade1d1.png)

It is still looking for the babel-make-styles plugin.

<details>

<summary>
attempted `babel.config.js` in `.storybook`
</summary>

```js
const plugins = [
  require.resolve('@babel/plugin-transform-shorthand-properties'),
  require.resolve('@babel/plugin-transform-block-scoping'),
  /*
   * Added for TypeScript experimental decorator support
   * https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options
   */
  [require.resolve('@babel/plugin-proposal-decorators'), { legacy: true }],
  [require.resolve('@babel/plugin-proposal-class-properties'), { loose: true }],
  [require.resolve('@babel/plugin-proposal-private-methods'), { loose: true }],
  require.resolve('@babel/plugin-proposal-export-default-from'),
  require.resolve('@babel/plugin-syntax-dynamic-import'),
  [
    require.resolve('@babel/plugin-proposal-object-rest-spread'),
    { loose: true, useBuiltIns: true },
  ],
  require.resolve('@babel/plugin-transform-classes'),
  require.resolve('@babel/plugin-transform-arrow-functions'),
  require.resolve('@babel/plugin-transform-parameters'),
  require.resolve('@babel/plugin-transform-destructuring'),
  require.resolve('@babel/plugin-transform-spread'),
  require.resolve('@babel/plugin-transform-for-of'),
  require.resolve('babel-plugin-macros'),
  /*
   * Optional chaining and nullish coalescing are supported in
   * @babel/preset-env, but not yet supported in Webpack due to support
   * missing from acorn. These can be removed once Webpack has support.
   * See https://github.com/facebook/create-react-app/issues/8445#issuecomment-588512250
   */
  require.resolve('@babel/plugin-proposal-optional-chaining'),
  require.resolve('@babel/plugin-proposal-nullish-coalescing-operator'),
  [
    require.resolve('babel-plugin-polyfill-corejs3'),
    {
      method: 'usage-global',
      absoluteImports: require.resolve('core-js'),
      // eslint-disable-next-line global-require
      version: require('core-js/package.json').version,
    },
  ],
];

const presets = [
  [require.resolve('@babel/preset-env'), { shippedProposals: true }],
  require.resolve('@babel/preset-typescript'),
];

module.exports = () => {
  return {
    sourceType: 'unambiguous',
    presets: [...presets],
    plugins: [...plugins],
  };
};
```

</details>

**Comment by Hotell** [comment]
as I mentioned I'd prefer to use instead environment configuration. Why do we need to exec all these babel optimizations for dev anyways?

**Comment by Hotell** [comment]
> babel.config.js

that config file should be used solely for monorepo root

**Comment by ling1726** [comment]
There is already a [babel.config.js file in the monorepo root](https://github.com/microsoft/fluentui/blob/master/babel.config.js) which does not include the babel-make-styles plugin. I'm not sure what I should be doing here ?

would you like me to try the default storybook `babel.config.js` in root .storybook folder ?

**Comment by ling1726** [comment]
@Hotell  Added extra solutions, reflects your suggestion of using environment configs
