### ISSUE TITLE
Please add native support for ASP.Net

### ISSUE THREAD

**Issue by MahmudX** [microsoft/fluentui#18777]
#### Describe the feature that you would like added

Native support for Asp.net

#### What component or utility would this be added to

All of it.

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

FluentUI is one of the great UI sets out there, but sadly there is no native support for Microsoft's own ASP.NET and Blazor, as well as Xamarin/MAUI. To use FluentUI with Blazor or ASP.NET, we use Syncfusion or other third-party libraries or some magical npm stuff which is not very easy but very difficult from a non-JS developer's endpoint (I'm a pure C# dev and don't want to deal with npm. I want things to be as smooth as possible.). It would be great if you guys release some sort of NuGet package or CSS lib or anything to use FluentUI natively with ASP.NET and Blazor (and Xamarin/MAUI too). 

Some of you may suggest using [FabricJS](https://developer.microsoft.com/en-us/fabric-js) or [Fabric CSS](https://developer.microsoft.com/en-us/fluentui#/get-started#fabric-core), but let me tell you, they are not up to date as well as lakes a lot of features and support for customization.

Also, I have seen that FluentUI has also an icon library for React but we ASP.NET developers don't have it. I don't get why Microsoft does not release this stuff for their own products.

[Edit: There is a lib for [Blazor](https://github.com/microsoft/fast-blazor)]

**Comment by gouttierre** [comment]
@MahmudX - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.

**Comment by chrisdholt** [comment]
The latest version of .NET is shipping with support for Blazor-wrapped Fluent UI Web Components. Closing this issue as that is the official Fluent UI approach for .Net. https://github.com/microsoft/fast-blazor

Thanks!

**Comment by MahmudX** [comment]
@chrisdholt will this work with ASP.NET MVC projects?
