### ISSUE TITLE
CDN of fluentui-react or npm package for office plugins

### ISSUE THREAD

**Issue by sumitmodi84** [microsoft/fluentui#18774]
I am developing a plugin for outlook js addin, where i have included fluentui-react via npm package. I am assuming that office js, itself uses the fluentui. So, i should not be shipping the fluent ui with my addin. rather refer to the location of CDN which office js uses. This will help in loading the page much faster as the js will be already loaded by outlook.
I could not find any documentation related to it. Can you please share the best practices to include the fluentui-react in the package.

**Comment by ecraig12345** [comment]
Office and Outlook use Webpack to bundle only the parts of Fluent UI that they use, so it's unfortunately not set up for add-ins to consume the same copy.
