### ISSUE TITLE
AreaChart: Support finer date time granularity

### ISSUE THREAD

**Issue by Agalin** [microsoft/fluentui#18784]
#### Describe the feature that you would like added

Currently AreaChart converts dates on the x axis to locale date string. It means that it's unsupported to chart data with finer time granularity. If you try you'll end with an ugly error about value at index being undefined.

This limitation seems to be completely arbitrary and this view is supported by chart working perfectly fine if date's `toLocaleDateString` is overwritten with something providing higher precision, e.g. `toLocaleString`.

Would be great for AreaChart to support finer granularity dates. If not then at least document somewhere in the component that it doesn't support that - the crash is completely ambiguous and nothing suggests that it's an issue with "two points in the same day".

#### What component or utility would this be added to

`@fluentui/react-charting/AreaChart`

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

[How it works now](https://codepen.io/agalin/pen/NWjPEBB) (crashes). Change second date to a next day for chart to render properly.

[How it works with an overwritten `toLocaleDateString`](https://codepen.io/agalin/pen/GRmgwwO).

**Comment by gouttierre** [comment]
@Agalin - thanks for filing this issue with us.

@Raghurk - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by dggsax** [comment]
Running into this bug right now and it's blocking our use of the AreaChart component. Ideally, inside `AreaChart.base.tsx` it would do `tempArr[0].x.toLocaleString()` instead of `tempArr[0].x.toLocaleDateString()`, and then give the user of the component an `xAxisFormat` props where they can control how the date is presented (e.g. ticks only show the days, or it shows it in hours, etc.)

Do you have any updates on this? @Raghurk

**Comment by Agalin** [comment]
@dggsax ticks should already show configurable date values - see `tickFormat` parameter. For `toLocaleDateString` there is only the hacky workaround of overwriting it as of now but it shouldn't affect rendering ticks on the chart.

**Comment by dggsax** [comment]
Thanks for pointing that out @Agalin! That's good to know for once the base issue that we're dealing with regarding `toLocaleDateString()` gets resolved.
