### ISSUE TITLE
LineChart: support more than 11 points for 12+ series chart or document the limitation

### ISSUE THREAD

**Issue by Agalin** [microsoft/fluentui#18786]
#### Describe the feature that you would like added

As described in #17686 LineChart doesn't work well when there are more than 11 series with more than 11 points each. Reportedly it's a design choice not to support more than 8 data points per series.

This arbitrary limitation should either be dropped (seems to only need a few lines changed with no functional difference) or documented in the LineChart as currently you can end with literally hundreds of duplicate key errors in the console for longer series and the only way to identify the issue is to check the `react-charting` source code.

Also note that LineChart examples used up to 11 points per series until #17127 and the second top result (first being an unrelated issue) of the Google search for `fluent ui line chart example` is still a [link to an outdated deployment of the `@uifabric/charting`](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/charting/dist/index.html) which doesn't have this change yet.

#### What component or utility would this be added to

`@fluentui/react-charting/LineChart`

#### Have you discussed this feature with our team, and if so, who

No, but there is a closed existing issue with some unanswered questions and a solution proposal.

**Comment by gouttierre** [comment]
@Agalin - thanks for reaching out to us. 

@Raghurk - Would you be able to confirm if this is a regression, or if this behavior is an issue? Thanks

**Comment by Raghurk** [comment]
Thanks @Agalin will look into this. At this point of time, it is by design.
