### ISSUE TITLE
[Menu Button] - focus does not return to the trigger button after a selection has been made

### ISSUE THREAD

**Issue by aubreyquinn** [microsoft/fluentui#18797]
I am using Fluent UI @ 0.54.0.

Here is the code sandbox: https://codesandbox.io/s/jk3pb?module=/example.js

Bug: the tab focus does not return to the trigger button after a selection has been made.

Steps to reproduce:

1. Tab to the trigger button, click the enter key.
2. Use the up/down arrow keys to navigate through the drop down list.
3. Make a selection and press the enter key.
4. Notice that the tab focus has been lost.

**Comment by jurokapsiar** [comment]
This is by design - MenuButton is meant to execute an action and it is consumer's responsibility to place focus accordingly depending on what the user would need to interact with after the action has been executed.
