### ISSUE TITLE
DetailsList in Dialog - Not virtual scrolling 

### ISSUE THREAD

**Issue by justinlee12** [microsoft/fluentui#18799]
### Environment Information

- **Package version(s)**: FluentUI/react 8.22.0
- **Browser and OS versions**: Tested with Chrome on Windows 10.

CodePen:  [codepen](https://codepen.io/plieqawn-the-bold/pen/bGWdWgV)

If you put a DetailsList with a set height in a Dialog, the virtual scrolling does not work. When you scroll down, it only shows the initial set of rows, with white space below.  (see codepen)

#### Actual behavior:

Rows are not rendered as you scroll down. 

#### Expected behavior:

All rows should be rendered as you scroll down.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

**Comment by gouttierre** [comment]
@justinlee12 - thanks for filing this issue and sharing the repro for confirmation.

@smhigley -  Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by smhigley** [comment]
@justinlee12 this is actually unrelated to it being within a dialog, and has to do with the element that has `overflow: scroll/auto` on it.

If you check the [DetailsList docs page](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist), it has this in the FAQ, about exactly this issue:
> **My scrollable content isn't updating on scroll. What should I do?**
  Add the data-is-scrollable="true" attribute to your scrollable element containing the DetailsList.
> 
> By default, the List used within DetailsList will use the body element as the scrollable element. If you contain the List within a scrollable div using overflow: auto or scroll, the List needs to listen for scroll events on that element instead. On initialization, the List will traverse up the DOM looking for the first element with the data-is-scrollable attribute to know which element to listen to for knowing when to re-evaulate the visible window.

In your codepen, you have a `<div style={{ height:200, overflowY: "auto"}} >` wrapping the detailslist. If you update that to be `<div data-is-scrollable="true" style={{ height:200, overflowY: "auto"}} >` it works. It also works if you remove that `<div>` entirely, and rely on the Dialog's own scrolling.

Hope that helps!

**Comment by justinlee12** [comment]
Awesome - thank you!
