### ISSUE TITLE
Button menu flyout goes exceeds screen width and cannot be used if text is too long

### ISSUE THREAD

**Issue by JamesBurnside** [microsoft/fluentui#18835]
### Environment Information

- **Package version(s)**: "@fluentui/react": "~8.17.2",
- **Browser and OS versions**: Chrome 91.0.4472.124, Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/jaburnsi/pen/bGWpdjP

#### Actual behavior:

Button menu goes out of the screen if text is too long:
![image](https://user-images.githubusercontent.com/2684369/124653932-c349a480-de52-11eb-97ba-ef8b5866beb2.png)

#### Expected behavior:

Text should wrap (e.g. setting the callout to have `max-width: 100%`):
![image](https://user-images.githubusercontent.com/2684369/124653978-d197c080-de52-11eb-88d0-b0b15a944bae.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: https://aka.ms/acscalldev

**Comment by ling1726** [comment]
Assining @khmakoto who actively works on button scenarios. 

However it seems to me that this is normal since by default none of the elements in the menuitem or the menu itself has a constrained width when setting `width: 100%`.  `text-overflow: "ellipsis"` needs a coinstrained width to work.

**Comment by JamesBurnside** [comment]
Is there any update on this? This impacts customers using the [Azure Communication Services - UI Library](https://github.com/Azure/communication-ui-library)

**Comment by ling1726** [comment]
I'm not entirely sure what can be done on Fluent to resolve this. `text-overflow` will only have effect when a constrained width is applied to an element.

**Comment by JamesBurnside** [comment]
I would expect either:

1. The default styling of the callout to have something like `max-width: 100%` so that the text-overflow property will be applied and the menu does not escape the bounds of the screen by default
2. There is a way in the button API (or `IContextualMenuProps`) to ensure the menu is confined within its host element.

    If I set `menuProps = { ...otherProps, styles: { root: { maxWidth: '100%' } } }` this doesn't work because that css is applied to a div too far down in the tree. It would need the `ms-Callout` div to have maxWidth applied to it. 

    I also tried `menuProps = { ...otherProps, bounds: {height: window.innerHeight, width: window.innerWidth, top: 0, left: 0}}` in the codepen above but this made the flyout not appear

    Perhaps there is another way I do not see however to acheive this through the IContextualMenuProps?

**Comment by JamesBurnside** [comment]
@ling1726 found a great workaround to make this work:

```js
const menuProps: IContextualMenuProps = { calloutProps: { styles: { root: { maxWidth: '100%' }}}}
```

I think by default (i.e. without this workaround) the flyout should still be constrained with parent element bounds (or at least the screen bounds) but given this workaround is sufficient and within the API feel free to close this issue 👍
