### ISSUE TITLE
DatePicker styling TextField applies styles to incorrect HTML element

### ISSUE THREAD

**Issue by byronwjones** [microsoft/fluentui#18849]
### Environment Information

- **Package version(s)**: 7.170.1
- **Browser and OS versions**: Chrome (Windows 10)

### Please provide a reproduction of the bug in a codepen:

[https://codepen.io/byronwjones/pen/LYyNrGx](https://codepen.io/byronwjones/pen/LYyNrGx)

#### Actual behavior:

Top border of text field component of DatePicker should be red

#### Expected behavior:

Style is applied to the parent element of the label and text field.  Incidentally, there is no API to style the DatePicker label (also a bug).

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

**Comment by ling1726** [comment]
@smhigley as you're heading up the v8 a11y effort, appreciate if you could take a look at this, and let me know if I should adjust the priority accordingly with your expertise :). I've went with the requested priority for now

**Comment by smhigley** [comment]
This seems to be caused by us putting the `textField` className directly on the TextField component, and not on the input within it in DatePicker.

That said, this isn't an a11y issue, and I don't really feel familiar enough with the style authoring experience in v8 to comment on the severity of this one.

**Comment by byronwjones** [comment]
Hello @ling1726, have you identified the appropriate person to address this issue?  What is the estimated time for completion?

**Comment by ling1726** [comment]
@byronwjones  you can style the `TextField` with selectors, here is an example: https://codepen.io/ling1726/pen/VwbbZKg

**Comment by byronwjones** [comment]
Thanks, @ling1726  but unfortunately this is not a viable solution - notice that in your example here are now *two* borders around the text field - one black, the other red.  An API user wants to be able to control the appearance of the black border, not add another one

**Comment by ling1726** [comment]
@byronwjones  in that case you can use the `textField` prop in the component and pass whatever props you want there:

I've modified the original codepen: https://codepen.io/ling1726/pen/VwbbZKg?editors=0010
