### ISSUE TITLE
Teaching bubble fail to find target and showing a diamond shaped beak

### ISSUE THREAD

**Issue by arshadshibli** [microsoft/fluentui#18843]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fabric-react-typescript-template-forked-lbyoq

#### Actual behavior:
Teaching bubble failing to find the target element where it is supposed to point.
I have a sequence of teaching bubbles that start with a coach mark. The first teaching bubble point to a list and is followed by two teaching bubbles which point to the icon button and search bar as shown in the image.
This works fine when the list is small. But it fails while I expand the list before clicking on coach mark.

#### Expected behavior:

The teaching bubble should point to the element by finding the element using the target property.
Please find the attached image to see both behaviors

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes
Requested priority: (Blocking, High, Normal, Low)
Blocking
Products/sites affected: (if applicable)
![teachingbubbleerror (2)](https://user-images.githubusercontent.com/36449762/124725469-84871d80-df2a-11eb-95c4-bfbaa1d7a802.png)

**Comment by ling1726** [comment]
The screenshot and descriptions are great, but for a problem related to positioning it can be hard to look into without code. Please provide a code example or a minimal repro on codepen or codesandbox so we can identify if/where the issue is in fluent.

**Comment by arshadshibli** [comment]
@ling1726 
I could reproduce a similar bu in code sandbox
Here is the link - [https://codesandbox.io/s/fabric-react-typescript-template-forked-lbyoq](url)

Click coach mark without expanding Nav. It will work fine
![image](https://user-images.githubusercontent.com/36449762/124797721-372d9f00-df70-11eb-8fe4-ba84e6460a72.png)

**Click coach mark only after fully expanding Nav in such a way that nav overflow the page and scrollbar appear**. You can see the teaching bubble fails.
![image](https://user-images.githubusercontent.com/36449762/124797917-70fea580-df70-11eb-96dc-52157416d073.png)

**Comment by hetanthakkar1** [comment]
@ling1726 Can I take this issue

**Comment by arshadshibli** [comment]
@hetanthakkar1
Hi, Any updates on this

**Comment by ecraig12345** [comment]
@hetanthakkar1 Sure, go ahead. It might be a bug in the positioning logic, but I'm not familiar enough with that to provide further suggestions offhand.

**Comment by hetanthakkar1** [comment]
> @hetanthakkar1
> Hi, Any updates on this

If you want to take it you can start working on it but it will take me around a week to solve
