### ISSUE TITLE
Allow Dynamic Scaling on MessageBar

### ISSUE THREAD

**Issue by tabrumle** [microsoft/fluentui#18850]
#### Describe the feature that you would like added
Message bar currently requires the user to specify whether or not the messagebar in a singleline or multiline variant. This causes an issue when strings vary by localization. Users have to either have some message bars with double the height from being multiline when unneeded, or have text cut off in a single line message bar when either the text is too long, or the screen is too small.

The ask here is to make message bar know when it needs to convert to multi or single line based on the size of the text instead of manually specifying.

#### What component or utility would this be added to

MessageBar

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots
This shows how single line message bars will have truncated text. The ask here is to have message bar know that the text is truncated and convert itself to a multiline message bar.
![image](https://user-images.githubusercontent.com/42159057/124787468-5b03cd00-defd-11eb-8575-deb384ac3e1a.png)

**Comment by ling1726** [comment]
@behowell could you take a look at this and plan some time for discussion with the v8 core members in your crew ?
