### ISSUE TITLE
[Dialog] Narrator issue with Dialog when <Image> provided as title with alt

### ISSUE THREAD

**Issue by sthigale-m** [microsoft/fluentui#18860]
Narrator issue with Dialog when <Image> provided as title with alt. Narrator keeps repeating the alt of image indefinitely.

https://user-images.githubusercontent.com/73924391/124874712-abeef080-dfe5-11eb-8504-78587449dcd1.mp4

### Environment Information

- **Package version(s)**: 8.22.1
- **Browser and OS versions**: Edge, Windows 10

### Describe the issue:

Narrator issue with Dialog when <Image> provided as title with alt. Narrator keeps repeating the alt of image indefinitely.

**Comment by ling1726** [comment]
@sthigale-m I can't repro this issue in the docsite or this minimal repro: https://codesandbox.io/s/pedantic-frost-th0tl?file=/src/App.js:542-611

Can you just check if you have the same issue on that codesandbox ?

**Comment by sthigale-m** [comment]
I can repro with your code. See: 

https://user-images.githubusercontent.com/73924391/129006732-e7f1756d-40cc-448c-a0d5-9688dcb261dd.mp4
