### ISSUE TITLE
no keyboard option for show/hide password on string input

### ISSUE THREAD

**Issue by theboyknowsclass** [microsoft/fluentui#18864]
Hi, when navigating via keyboard i can't seem to select the show/hide password box - nor can i find a documented shortcut key to toggle this without using a mouse.

### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

**Comment by theboyknowsclass** [comment]
apologies, i thought it referenced the control already... 

it's the TextField control

this behaviour can be evidenced in the web control demo -> https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield in the "Password with reveal button" control

**Comment by ling1726** [comment]
Next tab from the input will actually focus on the eye icon, which allows you to press `Enter` or  `Space` to hide/reveal the password.

However, there is no indication that the eye icon button actually has focus, this is a a but, I will close this issue and create a new one for that
