### ISSUE TITLE
Input listen to clearable, reset the value on click X icon

### ISSUE THREAD

**Issue by UMAMAHESHWARIG** [microsoft/fluentui#18878]
### Environment Information

- **Package version(s)**: (@fluentui/react-northstar@0.56.0)
- **Browser and OS versions**: (91.0.4472.124 ()

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by ling1726** [comment]
Please create a new issue or reopen this one with more details and repro steps. Is this a bug or a feature request ?
