### ISSUE TITLE
Using Icon with custom iconName doesn't pass along aria-label or role

### ISSUE THREAD

**Issue by isabelacmor** [microsoft/fluentui#18870]
### Environment Information

- **Package version(s)**: ^7.158.1
- **Browser and OS versions**: Anaheim 91.0.864.64 

### Describe the issue:

We're using Icon like:
![image](https://user-images.githubusercontent.com/4714094/124993094-bb2b6980-dff8-11eb-89fc-e7097baef26b.png)

which renders:
![image](https://user-images.githubusercontent.com/4714094/124993138-c9798580-dff8-11eb-88bd-0bf1d200e38e.png)

According to the Fluent docs, 
> Provide an aria-label (and set role="img") for screen reader users if the icon is not accompanied by text that conveys the same meaning.

However, the role and aria-label aren't passed down to the `<img>`, causing an error in Accessibility Insights. 
![image](https://user-images.githubusercontent.com/4714094/124993242-f5950680-dff8-11eb-9d60-4621000a7db3.png)

I've also tried passing `aria-hidden` and `role="presentation"` to `<Icon>` but it doesn't propagate down properly and still causes an accessibility error.

I've also tried to pass along `imageProps` like:
![image](https://user-images.githubusercontent.com/4714094/124994136-3d685d80-dffa-11eb-916a-90fb153855eb.png)

but I end up with no icon being rendered:
![image](https://user-images.githubusercontent.com/4714094/124994660-08103f80-dffb-11eb-9032-ab8ee9faa78a.png)

**Comment by ling1726** [comment]
This issue no longer repros with the latest v7 patch: ^7.172.4. It is recommended you get to the latest patch since it is non-breaking

You can try it on the docsite: https://developer.microsoft.com/en-us/fluentui?fabricVer=7#/controls/web/icon

**Comment by isabelacmor** [comment]
@ling1726 - our codebase updated to "@fluentui/react": "^8.15.1" and we're still seeing the same repro. Note that this only happens with custom iconNames.

It look like there might be a bug in `IconBase.prototype.render = function () {` where `containerProps` that holds `aria-label`. When I include `aria-label` and `role`, I get the nested `<i>`s and the `role` and `aria-label` aren't passed down to the `<img>`. When I don't include `aria-label` and `role`, I see `aria-hidden="true"` for the outermost `<i>`, but not the inner `<i>` or `<img>`.

**Comment by ling1726** [comment]
@behowell  is there anyone on the v8 team to check if this is a valid usage of `Icon` ? 

It seems that image icons should be used with either `ImageIcon` component or `Icon` with the appropriate `IconType` prop.

@isabelacmor here is an example of an image icon that correctly passes the aria-label and role: https://codesandbox.io/s/wild-moon-6bnsh?file=/src/App.js, I'm not quite sure how you're ending up with that DOM result you posted in the issue

**Comment by ling1726** [comment]
Keeping as lopri for now until we can determine if this is correct usage or not

**Comment by ecraig12345** [comment]
@isabelacmor Can you please provide a codepen or codesandbox repro that shows this issue? You can either start from the codesandbox @ling1726 linked above, or https://aka.ms/fluentpen.
