### ISSUE TITLE
(Callout) - Does not revaluate directionalHint modifications in V8

### ISSUE THREAD

**Issue by czearing** [microsoft/fluentui#18883]
### Environment Information

- **Package version(s)**: V8

### Please provide a reproduction of the bug in a codepen:

V8 `Callout` does not update the **directionalHint** when state is changed:
https://codesandbox.io/s/directional-hint-example-v8-rfigk?file=/src/App.tsx

V7 (expected behavior): https://codesandbox.io/s/directional-hint-example-v7-6rs34

#### Actual behavior:
When updating the  **directionalHint** it does not change.

#### Expected behavior:
When updating the  **directionalHint** it should change.

**Comment by modern-dev-dude** [comment]
@czearing 
The issue is when you override the style prop it messes with the positioning. 

https://codesandbox.io/embed/directional-hint-example-forked-oq2ji?fontsize=14&hidenavigation=1&theme=dark

Try this 
```
<CalloutContent
    directionalHint={directionalHint}
    // Notice here I am not using the "style" prop, but the "styles" prop witch fits into the Fluent UI theme and styling guidelines. 
    styles={{root:{width:200, height:100}}}
    target="#foo"
>
```
