### ISSUE TITLE
Figma plugin - link broken

### ISSUE THREAD

**Issue by Architecd** [microsoft/fluentui#18897]
Hi, 

unfortunately the link to the figma plugin is broken on my end. 
I'm just getting a 404 page, regardless of which browser I use and it doesn't show up within figma either.
https://www.figma.com/community/plugin/794492287931420611/Fluent-Theme-Designer

It's pretty much the same issue as #13943, which got closed unresolved a few days back. 

Does anyone have an idea how I might get the plugin to work anyways?
I'd love to give fluent UI a shot especially because of this plugin :)

thanks a lot, 
Dominik

**Comment by ling1726** [comment]
@paulgildea This link also directs to a 404 for me, has there been any follow up from the previously closed issue #13943 ?

**Comment by ling1726** [comment]
Triaging hipri since this is on the official docsite for customers

**Comment by GeoffCoxMSFT** [comment]
@Architecd @paulgildea I followed the link and the Figma plugin page rendered.  I installed the plug-in and it appeared when I went to a figma.  It took me through the introduction and the tool window appears to work.  Closing this issue. Please re-open if you still get a 404.
