### ISSUE TITLE
onItemDeselected   : Missed this event.  

### ISSUE THREAD

**Issue by molyom** [microsoft/fluentui#18899]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

There is no Event for Deselect. If I use OnChage it gives me all present Items and I dont know what is the deselected Item. 

#### Actual behavior:

With onChange I get an array. It is good Idea if in OnChange it return the name of action : like Select or Deselect

#### Expected behavior:

in OnDeselectedItem it has to give me the Deselected Item Key and Name. 

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (High)

Products/sites affected: (PCF for Dynamics 365)

**Comment by ling1726** [comment]
@molyom can you please include in the issue description the component that you are talking about here ?

**Comment by ling1726** [comment]
If you are talking about some sort of dropdown/selectable, natively there is no `onItemDeselected`. The correct way to do this in web is to get all the selected options. Here is an example with the native HTML select: https://codesandbox.io/s/epic-bose-0i6n8?file=/src/App.js:138-139

If you include the component you're referring to here, this can be considered a feature request

**Comment by molyom** [comment]
Hi, I need to detect the item that removed from the Selected tags. 
If I use OnChange, after every change all of I get all Remain Items.  

For Example: If I have these tags: RED, BLUE, BLACK. 
Then I Remove BLACK, In OnChange Event I will have an array with BLUE and RED. 

The expected is when we remove an item, we can find the data of removed item data.

**Comment by molyom** [comment]
Im talking about this: 
https://developer.microsoft.com/en-us/fluentui#/controls/web/pickers

**Comment by ling1726** [comment]
@molyom  Here is an example where you can achieve what you want using the `onRenderItem` callback: https://codesandbox.io/s/rough-sunset-xf4r6?file=/src/App.js

I've marked this issue as a feature request @gouttierre can you add this item to the v8 backlog ?

**Comment by molyom** [comment]
Thanks a lot, dear @ling1726 .  the last example helps me to find a quick solution,
I insist that it's better way if there is an event for Deselect items. But your Example is good for me in this case. 
Kind regards
