### ISSUE TITLE
DetailsList: use the same width for each column

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/fluentui#18914]
#### Describe the feature that you would like added

The auto-adjustment for column width seems to be difficult, but how about just using the same width for each column? Can we have a setting to let the component calculate an average value of each column's width by the total width and columns count?

#### What component or utility would this be added to

DetailsList

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

None

**Comment by ling1726** [comment]
Natively sizing table columns is not easy, and adding extra logic to calculate width is not as straightforward as you might think since it would also depend on viewport size and zoom.

Could you please give more detail to your request ? such as API suggestions for instance

**Comment by AkiraVoid** [comment]
I don't know what effect you want. For me, the DetailsList's column width seems same on both large screen and small screen devices, the only difference is on small screen I will get a horizontal scroll bar. It should be possible to get the container's width, and then we just need the columns count which is actually `props.columns.length` to calculate the width of each column. The user can set a column's width by setting the `IColumn.minWidth` and `IColumn.maxWidth` to same value. So what about add a property which can specific using average width or not? If this property was set to `true`, we just ignore the `IColumn.minWidth` , `IColumn.maxWidth` and `IColumn.isResizable` in every specified `IColumn` object. Yes, there are some problems can be seen, like the long text in header will be overflow, but we have no necessary to care about this, this is a risk the programmers should care about.

Sorry, I haven't seen the source code and don't know how you design this component. I don't know whether this solution helpful or not. If this is too difficult to achieve on this huge component, I will see if I can design a table component by myself. Anyway, thanks for this discussion.

**Comment by ling1726** [comment]
@ecraig12345  do you know anyone in the v8 team who has more context on the `DetailsList` internals to help out here ?

**Comment by ecraig12345** [comment]
I'm not very familiar with DetailsList either, so my best suggestion is to look at [how the layout is handled for fixed and justified columns](https://github.com/microsoft/fluentui/blob/6d75fc293e876c681f94aabb89000cabd631942d/packages/react/src/components/DetailsList/DetailsList.base.tsx#L1168) and add a new method using similar logic. Due to other priorities, this isn't something that anyone from the team will work on, but I could help review a PR if someone else wants to make one.
