### ISSUE TITLE
[accessibility][Keyboard navigation]: Keyboard focus lands on wrong cells when navigating using arrow keys in List

### ISSUE THREAD

**Issue by g-akshay** [microsoft/fluentui#18929]
### Environment Information

- **Package version(s)**: Office UI Fabric React 
(Based on version https://github.com/microsoft/fluentui/tree/67d167f3d9400b3f38c0106a78f91a67a6eabb5e)
- **Browser and OS versions**: 
Platform: Web-Chrome
OS Version: 2004(OS Build 21287.1004)
Chrome Version: 89.0.4389.90(64-bit)

#### Actual behavior:
Within the list component,  navigation using arrow keys is not consistent. When the user navigates using the down arrow key, the navigation focus moves only to the first cell on each row, but when using up navigation, the focus moves to other cells which are not in the same column.

#### Expected behavior:
When using the up and down arrow key, the focussed cell needs to be consistent and within the same column.
if we move to the different column using the right/left arrow key, then up and down arrow keys should focus cells in that column. 

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: https://admin.teams.microsoft.com/teams/manage

**Comment by ling1726** [comment]
@g-akshay  are you sure the version you posted is correct, the commit suggests that you are still using v4 which is about 4 years old already

**Comment by g-akshay** [comment]
yes!!! thats true :(
