### ISSUE TITLE
Accessibility Insights for any !isModeless Modal Section 508 502.3.10: (document '') An element of the given ControlType must support the Text pattern.

### ISSUE THREAD

**Issue by shufan** [microsoft/fluentui#18947]
Any usage of the fluentui Modal component where isModeless is false results in this issue showing up in Accessibility Insights. I filed this issue when running Accessibility Insights on the modal shown for the non-Modeless Modal here: https://developer.microsoft.com/en-us/fluentui#/controls/web/modal

![image](https://user-images.githubusercontent.com/1192397/125709951-e0c03c96-3bf7-4957-8d11-1a5192d10916.png)

**Element path:** document ''

**Issue Details:** An element of the given ControlType must support the Text pattern. [Section 508 502.3.10](https://www.access-board.gov/ict/#502-interoperability-assistive-technology)

**How To Fix:** 1. Make sure the element has the appropriate ControlType property for its function.
2. If the current ControlType is correct, modify the element to support the Text pattern.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by gouttierre** [comment]
@shufan - Thank you filing this issue with the details and a suggested fix. Please feel free to submit a PR for the fix and our team will gladly review it.

@smhigley  - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by smhigley** [comment]
This doesn't look like a real bug. We have a `<div role="document">` inside the modal element, which is a valid role on a `<div>` (incidentally, it's present to fix a modal bug in VoiceOver). Narrator works just fine with the modal, so there doesn't seem to be a real problem with the UIA mappings.

I'd say this is a false positive from accessibility insights for desktop. Just as an FYI, testing web apps with the desktop version of accessibility insights will result in a high incidence of false positives (and false negatives), so it isn't recommended.
