### ISSUE TITLE
Add vNext conformance test ensuring user's className always win

### ISSUE THREAD

**Issue by levithomason** [microsoft/fluentui#18943]
The user's className passed through hooks as state.className must always be merged last in mergeClasses. Otherwise, some of the user's css properties will not be applied.

This issue is present in alpha.60 in PopoverSurface:

```
const useStyles = makeStyles({ root: { paddingRight: '0px' } })
const styles = useStyles()
<PopoverSurface className={styles.root} />

Incoming state.className not present in result (lost):
  fifp7yv  : padding-right: 0px;

Resulting state.className not present in incoming (new):
  fpnz0vo  : background-color: var(--alias-color-neutral-neutralBackground1);
  f1gbmcue : padding-right: 16px;
  fqag9an  : padding-top: 16px;
  fp67ikv  : padding-bottom: 16px;
  f1rh9g5y : padding-left: 16px;
```

This issue seems to be resolved in master (https://github.com/microsoft/fluentui/pull/18759) at the time of writing but we need to ensure it never happens on any component in the future.

The conformance test should ideally test all CSS properties using the public API including all slots. We could also consider a lint rule that ensures user's classNames are always merged last.

**Comment by ecraig12345** [comment]
I thought we already had this in a conformance test for this? https://github.com/microsoft/fluentui/blob/6d75fc293e876c681f94aabb89000cabd631942d/packages/react-conformance/src/defaultTests.tsx#L157
