### ISSUE TITLE
[JPN] Entered letters gets doubled on iOS while in Japanese keyboard mode in Autofill textbox

### ISSUE THREAD

**Issue by eylult** [microsoft/fluentui#18945]
### Environment Information

- **Package version(s)**: Current - Fluent V8

- **Browser and OS versions**:
-   - iPad 13.5, 13.6, 14.2
  - Safari, Chrome
- ・macOS10.12.6 / Safari 12.1.2
・macOS10.14.6 / Safari 14.0.3
・macOS10.15.7 / Safari14.0.2
・macOS11 / Safari14.0.3

#### Actual behavior:

Type a japanese character in an autofill text box (e.g. OWA recipient well)
Observe if it's being duplicated. If not, type another character and see if it's being duplicated. 

This is easy to repro, but not consistent. The most consistent repro I got was typing a second character and seeing the first character being duplicated.

#### Expected behavior:

No extra characters should be added to the text the user types. 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: High

**Comment by litong2** [comment]
codepen demo https://codepen.io/litong2/pen/JjNWeLG

**Comment by ling1726** [comment]
@litong2 Thanks for contributing a fix, really appreciated.

Can confirm that this also repro on Windows japanese IME

**Comment by ecraig12345** [comment]
@litong2 Can you confirm whether this ended up being fixed by the PR or not?
