### ISSUE TITLE
Add multi-language support to DatePicker

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/fluentui#18954]
#### Describe the feature that you would like added

The `DatePicker` has some strings that cannot be customized, they are all in English. I hope there can be a way to change the language of this component.

#### What component or utility would this be added to

DatePicker

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

None

**Comment by AkiraVoid** [comment]
I can offer the Chinese translation and a little bit Japanese translation.

**Comment by ecraig12345** [comment]
Which package are you using the DatePicker from, and what are the specific hardcoded strings?

**Comment by AkiraVoid** [comment]
I'm using Fluent UI React in my web project. The `DatePicker` can only display each month in English, and also the `Go to today` at the bottom right is in English. The name of each day-of-week is displayed as the first letter of its word in English.

**Comment by AkiraVoid** [comment]
And my web has already specified the language by setting the property like: `<html lang="zh">`.

**Comment by AkiraVoid** [comment]
If you specified `isRequired=true`, when the date haven't been picked, the tip `Field is required` is also in English.

**Comment by ling1726** [comment]
@AkiraVoid  here is an example of how to localize the required string, there are more localization options in the props. I advise you take a deeper look at the documentation and what options are available for localization. Fluent does not store any locale strings apart from english default. If you want localized datepicker options, you need to provide those strings in your own code

https://codepen.io/ling1726/pen/RwVVNwx

**Comment by AkiraVoid** [comment]
Oh, I see. I suggest you update the doc and add a localization guide into the introduction of DatePicker.
