### ISSUE TITLE
openOnKeyboardFocus breaks keyboard navigation in Dropdown

### ISSUE THREAD

**Issue by fgnass** [microsoft/fluentui#18951]
### Environment Information

- **Package version(s)**: @fluentui/react@8.23.3

### Reproduction

Here is a codepen based on the _Basic Dropdowns_ example with the `openOnKeyboardFocus` option added: https://codepen.io/fgnass/pen/MWmpEYo

#### Actual behavior:

Hitting tab when the dropdown is open briefly closes the options and immediately opens them again, leaving the user trapped.

#### Expected behavior:

Hitting tab closes the dropdown and moves the focus to the next focusable element.

**Comment by ling1726** [comment]
@fgnass Thanks for the reprop, this looks like a pretty nasty bug, other behaviours I noticed that seemed quite bad:

* `Escape` to close the dropdown also gets stuck in an endless cycle
* Clicking outside the dropdown while it is open also gets stuck in an endless cycle

**Comment by ling1726** [comment]
@gouttierre this looks like a pretty serious bug, can you get one of the v8 team to prioritize investigating this ?
