### ISSUE TITLE
Support dual-screen for positioning in converged components

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#18975]
#### Describe the feature that you would like added

We support dual-screen mode in v8, this was added in #12785. But as we are using Popper.js via `@fluentui/react-positioning` in converged components, we support have also support there.

#### What component or utility would this be added to

- `@fluentui/react-positioning` via custom modifier
- add support to Popper.js itself

#### Additional context/screenshots

- `getWindowSegments()` API https://docs.microsoft.com/en-us/dual-screen/web/javascript-getwindowsegments
- #12785 implementation details in v8
- Using dual-screen in WebTools https://docs.microsoft.com/en-us/dual-screen/web/desktop-developer-tools

**Comment by miroslavstastny** [comment]
No dual screen devices to support right now, closing
