### ISSUE TITLE
Web components are missing a component definition file

### ISSUE THREAD

**Issue by janechu** [microsoft/fluentui#18987]
A missing import is present in the `component-definitions.ts` file, the component definition for `toolbar`, the file does not exist yet it is being imported and exported which causes build errors when attempting to use the file.

### Environment Information

- **Package version(s)**: @fluentui/web-components@1.2.1

### Actual behavior:

Error when building a package importing the component-definitions file.

### Expected behavior:

No build errors.

### Suggested fix

I suggest this is removed or if the code is ready to go, add the toolbar and its definition to the package.

### Priorities and help requested:

I have made @chrisdholt  aware of the issue.

Requested priority: Blocking

Products/sites affected: FAST Creator

**Comment by chrisdholt** [comment]
Fixed by #19087
