### ISSUE TITLE
Text Field Error Message does not wrap around using the length of the TextField when the textfield is rendered as part of a DetailsList

### ISSUE THREAD

**Issue by Benard-Ngaruiya** [microsoft/fluentui#18990]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Microsoft Edge

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable) Azure Communication Services portal resource

**Comment by ling1726** [comment]
@Benard-Ngaruiya  here is an example where you can style the `TextField` error message to wrap. By default the styling is designed to overflow using ellipsis.

However, from what i see it seems to just overflow from the `DetailsList` column without ellipsis, that actually might be a bug/issue of its own.
