### ISSUE TITLE
Give DetailsList ability to lock a column in place

### ISSUE THREAD

**Issue by Shannon-Ke** [microsoft/fluentui#19003]
#### Describe the feature that you would like added

Give details list ability to put action buttons per row that stick to the right side of each row. Useful for adding action buttons to the table rows such as 'edit row' or 'delete row'. (preferred)

OR

Give the details list the ability to lock a column in place regardless of the horizontal scroll. For example, allow the last column of a table that might have 100 columns stay stuck to the right side of the screen, or specify a prop for StickyColumn that takes columns that can stick to the screen.

#### Additional context/screenshots

Action button per row example. The triple dot menu on the right hovers over each row and sticks to the ends.
![image](https://user-images.githubusercontent.com/23206010/126215124-76010ee1-701f-4741-b8b2-e80af10ffa3b.png)

OR for column lock

For example, the sticky column on the right always shows up no matter where the horizontal scroll is located. 
![image](https://user-images.githubusercontent.com/23206010/126214201-9e2249b0-2fae-4601-9360-8fc69b5eac08.png)

**Comment by ling1726** [comment]
@Shannon-Ke  Thanks for the feature request, we generally do not have enough effort allocated for `DetailsList` features unless they are required by a large number of partners. However if this is something you'd like to contribute, we'd be happy to review any PRs.

**Comment by Shannon-Ke** [comment]
I see. Thank you for your quick response.
