### ISSUE TITLE
Release of v9: check versions on NPM for each package

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#19000]
_This issue is a prerequisite for vNext release._

Some packages may be already released on NPM as `9.0.0` please check it first. This already happened with `@fluentui/make-styles-webpack-loader`, see the thread: https://github.com/microsoft/fluentui/pull/18992#discussion_r672300566

`@fluentui/make-styles-webpack-loader@9.0.0` was unpublished from NPM:

```
npm info @fluentui/make-styles-webpack-loader
npm ERR! code E404
npm ERR! 404 Unpublished by layershifter on 2021-07-19T13:36:31.697Z
```

But even then I am not sure that we will be able to release `@fluentui/make-styles-webpack-loader@9.0.0`.

---

Consider to release `9.0.1` as a first release, for example.

**Comment by ling1726** [comment]
According to this, it's not possible to republish the same name and version number again 

https://docs.npmjs.com/cli/v7/commands/npm-unpublish#description

**Comment by ling1726** [comment]
Keep this closed, I verified all available package versions the only exception was @fluentui/make-styles-webpack-loader which is no longer going to be released
