### ISSUE TITLE
Ensures elements with an ARIA role that require child roles contain them

### ISSUE THREAD

**Issue by Renuka8796** [microsoft/fluentui#19014]
**Environment Information:**
Package version(s): "@fluentui/react": "^8.23.5",
Browser and OS versions: chrome and Windows 10

Expectation: Ensures elements with an ARIA role that require child roles contain them.

Actual: Elements with an ARIA role that requires child roles do not contain them.

![image](https://user-images.githubusercontent.com/51446798/126294909-2cde7131-405e-45ab-adfe-5aae19bf5cc3.png)

Please provide a reproduction of the issue in a codepen : https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker

This issue already addressed  https://github.com/dequelabs/axe-core/issues/2478 and the axe core is updated to 4.3 and fixed but still issue is there in fabric ui site.

.

**Comment by smhigley** [comment]
@Renuka8796 when I run axe-core v4.3 on that control, I don't get an aria-required-children error. I'm guessing Accessibility Insights hasn't updated to the latest version of axe yet, and when they do it should go away. If you want to verify it in the meantime, you can use the axe devtools extension directly.

I'm closing this issue for now, but feel free to comment or re-open if you still see a required-children error with axe-core 4.3+.

**Comment by Renuka8796** [comment]
@smhigley  Could you please request for Accessibility Insights team to get update on the axe-core, I am not sure how to raise for that team. Thanks in advance.
