### ISSUE TITLE
Moving through Basic List with Narrator in Scan Mode causes list items to lose focus

### ISSUE THREAD

**Issue by ltackett** [microsoft/fluentui#19030]
### Environment Information

- **Package version(s)**: 8.23.5
- **Browser and OS versions**: Windows, version 10.0.19043 Build 19043. Chrome, version 91.0.4472.124.

### Describe the issue:

Given that:
 * A List component has rendered many variable-height elements, and
 * Windows 10 Narrator is on, and
 * Narrator is in Scan Mode, and
 * a list item has focus...
 
 ... scrolling quickly through list items can unintentionally move focus from the list items to elements outside of the list.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/ltackett/pen/PommKPe

#### Screen recording:

https://user-images.githubusercontent.com/12592/126395847-6ea52be3-4876-4e38-9965-c96417aa7d9e.mp4

#### Actual behavior:

The List component does not render new list pages quickly enough, and the narrator focuses on items outside of the list.

#### Expected behavior:

That you will be able to scroll through all of the list items until the end of the list.

### Documentation describing expected behavior

I don't know where I would find this.

**Comment by ling1726** [comment]
Thanks for the repro and description 👍

However in this case I'm not sure if this is a bug or if we can do anything about it. @smhigley could you lend your expertise here ?

**Comment by smhigley** [comment]
@ltackett could you clarify how you're interacting with the page, and where the interaction expectations are coming from? From the video alone, it looks like you're first setting Narrator's virtual cursor within the scroll area, then scrolling with the mouse, then switching back to Narrator. I'd expect that series of interactions to potentially cause issues even outside of a virtualization scenario.

If a Narrator user is using their cursor to scroll the page, I'd expect them to then also use their moues cursor to set Narrator's virtual cursor. If a user is controlling Narrator through the keyboard, I would not expect them to be scrolling with their mouse. Mixing the two in this way isn't supported by Narrator, independent of Fluent.

**Comment by ltackett** [comment]
@smhigley in my example, clicking with the mouse is a shortcut to tabbing through the UI of Codepen (since it loads the example in an iframe). The behavior persists if I use tab and the arrow keys to navigate to/through the list.

**Comment by smhigley** [comment]
@ltackett to clarify, is the bug that Narrator's scan mode cursor jumps to a random element after the list when you scroll, or that moving the virtual cursor doesn't actually scroll the page, and therefor doesn't load additional items?

The first one I can't reproduce, and the second one is a known current limitation of most SR virtual cursor modes. To use a component that loads items on scroll, someone using a screen reader would need to navigate by moving focus (i.e. not in scan mode).
