### ISSUE TITLE
react-northstar FormTextArea is missing `required` prop

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/fluentui#19033]
#### Describe the feature that you would like added

The FormTextArea component should render an `*` just like the FormInput component does.

The component currently does not error when you add the `required` prop since it extends from the `TextareaHTMLAttributes` type, and it does correctly forward it to the underlying `textarea` element. But there is no UI indicator for it.

#### What component or utility would this be added to

https://github.com/microsoft/fluentui/blob/dab45a2afe609709735b9b6e604a1af40d50e809/packages/fluentui/react-northstar/src/components/Form/FormTextArea.tsx

#### Have you discussed this feature with our team, and if so, who

Nope but happy to do so 😄

**Comment by ling1726** [comment]
@Ethan-Arrowood  Thanks for the, we will discuss internally and prioritize this feature request.

**Comment by ling1726** [comment]
It seems like this is a bug, the `FormTexArea` does not have the star: https://codesandbox.io/s/fluent-ui-example-forked-behqd?file=/example.js

This should be fixed as high priority

**Comment by jurokapsiar** [comment]
This is a valid bug, thanks for reporting, we will fix it in the next sprint (within next 3 weeks)
