### ISSUE TITLE
String misspelling 

### ISSUE THREAD

**Issue by MichaelEclavea** [microsoft/fluentui#19031]
I have attached an image showing the error. 

Here is the link to the page with the error: https://developer.microsoft.com/en-us/fluentui#/styles/web/colors/theme-slots

<img width="1180" alt="Screen Shot 2021-07-20 at 9 18 14 AM" src="https://user-images.githubusercontent.com/68795830/126402380-13cb09fe-7422-412e-b920-9adea1bcbba7.png">

### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by ling1726** [comment]
@MichaelEclavea  thanks for the issue!
