### ISSUE TITLE
Add x-axis tick mark with no associated y-axis data in Heatmap component

### ISSUE THREAD

**Issue by dggsax** [microsoft/fluentui#19032]
#### Describe the feature that you would like added
Right now, it looks like the `<Heatmap />` component uses `d3-scale` to generate the x-axis ticks based on the data. For our usage of the HeatMap, we're generating data where the X-Axis points are `Date` strings, but in some cases we filter out data points because they don't have any instances or they have a percentage of 0.0%. 

For example, I may have data binned in 6 hour windows that I want to present to the user at "00:00pm", "8:00pm", and "16:00pm". Right now, if I present just those three data points, the rendered squares will be right next to each other with no spacing between them to indicate there was data filtered out in the "04:00pm" and "12:00pm" bins.

It would be cool to be able to say "render the x-axis tick marks for 4 o'clock and 12 o'clock but then have empty space so the user can still distinguish how the rendered data points relate to each other". Is such a thing possible? In the "Additional context" section I break down what I've tried so far.

#### What component or utility would this be added to
 - Heatmap from the `react-charting` package

#### Have you discussed this feature with our team, and if so, who
 - I have not, I would love to be in touch with whoever's working on the `react-charting` component as we're beginning to utilize them pretty heavily 😁

#### Additional context/screenshots
What I've tried so far is to put in data points and for the `value` property of `IHeatMapChartDataPoint` I've provided `undefined as unknown as number`. Could we perhaps make it so that `IHeatMapChartDataPoint` has a property like `isVisible` or `display` so that I could be responsible for providing the data point and then the Heatmap component knows it doesn't need to render anything?

![image](https://user-images.githubusercontent.com/13513445/126404298-d60c96ed-d2e5-46c3-87f0-a75e00198cee.png)

Curious to hear y'all's thoughts on this. Please let me know if I can elaborate further anywhere.

**Comment by ling1726** [comment]
@Raghurk could you take a look at this feature request for charting ?

**Comment by Raghurk** [comment]
Thanks for the request. I will follow up on this and get back to this thread.

**Comment by dggsax** [comment]
Hi @Raghurk are there any updates on this request? Thank you in advance 🙂

**Comment by dggsax** [comment]
Any updates?
