### ISSUE TITLE
[Slider] Cannot disable Slider receiving focus in FocusZone

### ISSUE THREAD

**Issue by statm** [microsoft/fluentui#19055]
### Environment Information

- **Package version(s)**: v8

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/statm/pen/eYWGddb

#### Actual behavior:

When using left/right keys to move focus inside the focus zone, the slider will always receive focus, even though `data-is-focusable` is set to false on it.

#### Expected behavior:

The slider should pass `data-is-focusable` to its inner `.ms-Slider-slideBox`, and disable its focus when necessary.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OOUI

**Comment by ling1726** [comment]
There seems to be no way to spread props to any of the slots in Slider, and for this usage it's hard to find a good workaround: Here is something you could do that is ref based: https://codepen.io/ling1726/pen/KKmXQyP

`FocusZone` doesn't have much help either for this, there is `shouldReceiveFocus` callback but that will just stop the keyboard navigation at the slider.
