### ISSUE TITLE
Microfeedback component is not available. 

### ISSUE THREAD

**Issue by lakshmi9414** [microsoft/fluentui#19067]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by ling1726** [comment]
@lakshmi9414 Please provide more details of the issue and code repro

**Comment by ecraig12345** [comment]
Microfeedback is found in `@fluentui/react-experiments` (version 8) or `@uifabric/experiments` (version 7).
