### ISSUE TITLE
Difference between onLayerDidMount from v7 to v8

### ISSUE THREAD

**Issue by kelseyyoung** [microsoft/fluentui#19077]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^8.23.5"
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:

Codepen highlighting v7 behavior: https://codepen.io/kelseyyoung/pen/MWmERbX
Codepen highlighting v8 behavior: https://codepen.io/kelseyyoung/pen/ZEKXZeM

#### Actual behavior:

In the V8 example, in the console you will see "is Dialog DOM available false". This is from the onLayerDidMount callback in layerProps, showing that the DOM of the dialog is not queryable at this stage

The code in question is in packages\react\src\components\Layer\Layer.base.tsx. The code looks like:

```
// If a doc or host exists, it will remove and update layer parentNodes.
    const createLayerElement = () => {
      const host = getHost();

      if (!doc || !host) {
        return;
      }

      // Remove and re-create any previous existing layer elements.
      removeLayerElement();

      const el: HTMLDivElement = doc.createElement('div');

      el.className = classNames.root!;
      setPortalAttribute(el);
      setVirtualParent(el, rootRef.current!);

      insertFirst ? host.insertBefore(el, host.firstChild) : host.appendChild(el);

      setLayerElement(el);

      onLayerMounted?.();
      onLayerDidMount?.();
    };

    // eslint-disable-next-line no-restricted-properties
    React.useLayoutEffect(() => {
      createLayerElement();
      // Check if the user provided a hostId prop and register the layer with the ID.
      if (hostId) {
        registerLayer(hostId, createLayerElement);
      }

      return () => {
        removeLayerElement();

        if (hostId) {
          unregisterLayer(hostId, createLayerElement);
        }
      };
      // eslint-disable-next-line react-hooks/exhaustive-deps -- should run if the hostId updates.
    }, [hostId]);
```

#### Expected behavior:

In the V7 example, in the console you will see "is Dialog DOM available true". This is from the onLayerDidMount callback in layerProps, showing that the DOM of the dialog is queryable at this stage

The code used to look like:

```
  public componentDidMount(): void {
    const { hostId } = this.props;

    this._createLayerElement();

    if (hostId) {
      registerLayer(hostId, this._createLayerElement);
    }
  }

...

private _createLayerElement = () => {
    const { hostId } = this.props;

    const doc = getDocument(this._rootRef.current);
    const host = this._getHost();

    if (!doc || !host) {
      return;
    }

    // If one was already existing, remove.
    this._removeLayerElement();

    const layerElement = doc.createElement('div');
    const classNames = this._getClassNames();

    layerElement.className = classNames.root!;
    setPortalAttribute(layerElement);
    setVirtualParent(layerElement, this._rootRef.current!);

    this.props.insertFirst ? host.insertBefore(layerElement, host.firstChild) : host.appendChild(layerElement);

    this.setState(
      {
        hostId,
        layerElement,
      },
      () => {
        // eslint-disable-next-line deprecation/deprecation
        const { onLayerDidMount, onLayerMounted } = this.props;
        if (onLayerMounted) {
          onLayerMounted();
        }

        if (onLayerDidMount) {
          onLayerDidMount();
        }
      },
    );
  };
```

It appears the conversion to addLayoutEffect did not completely replicate the behavior of V7

### Priorities and help requested:

Are you willing to submit a PR to fix? Unsure what the fix would be

Requested priority: High

Products/sites affected: We discovered this while upgrading Office Online to v8, we are able to get around it so it's non-blocking to ship with v8 but blocks another feature that was utilizing this code

**Comment by katiearriagam** [comment]
@ling1726 - can you help triage this bug?

**Comment by gouttierre** [comment]
@kelseyyoung - thanks for reaching out to us and filing this issue / question.

@smhigley - Would you be able to confirm if this is a regression, or if this behavior is an issue between v7 and v8's?
