### ISSUE TITLE
Monaco Icons are not correctly initialized for monaco editor on official example page.

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/fluentui#19088]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
1. go to page https://developer.microsoft.com/en-us/fluentui#/controls/web/stack
2. click "show code"
3. press "ctrl + F" to search

#### Actual behavior:
![image](https://user-images.githubusercontent.com/28779355/126745432-9ca71c8f-4ea5-4712-93f1-9dc420ab47d7.png)

#### Expected behavior:
should be the same with vscode, I guess.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes. And it would be sweet to point out roughly where is the web page project or which component I might need to change.

Requested priority: (Blocking, High, Normal, Low)
Low

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
The editor code is in these two packages:
https://github.com/microsoft/fluentui/tree/master/packages/monaco-editor
https://github.com/microsoft/fluentui/tree/master/packages/react-monaco-editor

It looks like a variant of this issue, though I'm not sure offhand what the appropriate fix would be with our editor setup.
https://github.com/microsoft/monaco-editor/issues/1949
