### ISSUE TITLE
[Card] Incorrect HC theme on hover

### ISSUE THREAD

**Issue by petrjaros** [microsoft/fluentui#19089]
### Environment Information

- **Package version(s)**: 0.56.0

### Please provide a reproduction of the bug in a codepen:

1. Open https://fluentsite.z22.web.core.windows.net/0.56.0/components/card/definition
2. Change theme to High Contrast
3. Hover over any card

#### Actual behavior:

Font color stays white, the text is barely readable:
![image](https://user-images.githubusercontent.com/465984/126750484-0f87951c-9a4c-4666-80fb-57938fe2e621.png)

#### Expected behavior:

Font color should be clearly readable when hovering over a Card component.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Teams, Breakout Rooms Pre-meeting management

**Comment by gouttierre** [comment]
@petrjaros - thanks for filing this issue with us. 

@jurokapsiar -  Would your team be able to confirm if this is a regression, or if this behavior is an issue?
