### ISSUE TITLE
Northstar FormButton cannot be configured as `type='submit'`

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/fluentui#19081]
### Environment Information

- **Package version(s)**: fluent-ui/react-northstar 0.57.0

#### Actual behavior:

Passing `type='submit'` to `FormButton` throughs type error:

```ts
<FormButton type="submit" />
```

```
Type '{ id: string; "data-testid": string; content: string; disabled: boolean; type: string; }' is not assignable to type 'IntrinsicAttributes & Omit<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, "as" | keyof FormButtonProps> & { ...; } & FormButtonProps & Pick<...>'.
  Property 'type' does not exist on type 'IntrinsicAttributes & Omit<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, "as" | keyof FormButtonProps> & { ...; } & FormButtonProps & Pick<...>'.ts(2322)
```

#### Expected behavior:

No type error

### Priorities and help requested:

No, no capacity at the immediate moment

Requested priority: (High)

**Comment by ling1726** [comment]
@Ethan-Arrowood Thanks for submitting the issue, here is a codesandbox repro: https://codesandbox.io/s/vigilant-morse-g7pim?file=/src/App.tsx

In this case, it is a bug in our typings, but hopefully should have low impact since by `type="submit"` is the default behaviour in any `button` element that is associtated in a `form`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by ling1726** [comment]
@Ethan-Arrowood  we have moved this to our next sprint and will fix accordingly, if you would like to make a contribution please feel free to do so and we will review.

**Comment by ling1726** [comment]
> Due to this bug I can't make non-submit buttons in my form (for other UI controls)

That seems like a bigger issue, yeah. Apologies, I understood that your issue was with typings when trying to use `type="submit"`
