### ISSUE TITLE
Verify icons story

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#19093]
- are icons part of the release
- do we have a docsite for icons
- static classnames for outline/filled - who is reviewing icons repo PRs?
- how styles are applied (multi window support)

**Comment by tomi-msft** [comment]
RFC for vNext Icon: #19623

**Comment by tomi-msft** [comment]
Updates:

- [PR](https://github.com/microsoft/fluentui-system-icons/pull/325) to update vNext icons to be resizeable following [this](https://hackmd.io/QE1m_xJPSVuIZnNsizFT2w?view) proposal
- Updated icon package can be used in beta components, using newly simplified leaf node imports to speed up rendering time

Work to complete
- Update fluent wiki icon page with both icon packages
- Create a webpage to view icons: [This](https://github.com/microsoft/fluentui/pull/16580) PR was created earlier, but drastically increased page load time so was scrapped. Will revisit with newer package with easier leaf node imports, should drastically reduce page load time

**Comment by layershifter** [comment]
Once we will merge https://github.com/microsoft/fluentui-system-icons/pull/369 we can close this. @tomi-msft is there something else to fix?

**Comment by tomi-msft** [comment]
Icons story is relatively stable, there will not be any breaking changes before release.
