### ISSUE TITLE
Menu: in v9 an icon in "checkbox" is misaligned

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#19102]
### Environment Information

- **Package version(s)**: `@fluentui/react-menu@9.0.0-alpha.53`
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

"Aligning With Selectable Items" example in Storybook.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/14183168/126779538-a1e92198-b091-45c4-9b12-eb0d4c83bfdb.png)

An icon in `checkmark` slot has a strange alignment as each slot has own width:
- `checkmark` has `16px`
- `icon` has `20px`

#### Expected behavior:

![image](https://user-images.githubusercontent.com/14183168/126779764-167bebeb-bc89-4c54-a97d-fdc87f6a7fa3.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal
Products/sites affected: Teams

**Comment by ling1726** [comment]
Need to follow up with design about this, the current spec indicates different sizes for the checkmark icon and foreground icon. It's not a clean fix as long as these icons have different sizes
