### ISSUE TITLE
Proper changelogs for releases

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#19105]
We should have proper changelogs for converged components - customers should be able easily understand what was released and when to perform upgrades even within beta releases.
 
- 👍👍👍 https://github.com/mui-org/material-ui/releases
- 👍 https://github.com/babel/babel/releases
- 👎 https://github.com/microsoft/fluentui/releases

**Comment by JustSlone** [comment]
This is big, maybe after beta? ☹️

**Comment by Hotell** [comment]
we should adopt a known/common OSS industry solution

An excellent candidate:
- https://github.com/atlassian/changesets

**Comment by levithomason** [comment]
Related: I've worked up a crude concatenated changelog for beta use for now. This was based on team feedback that we should try a short-term middle ground solution to solve the issue consumers are having with changelogs during beta. It is throw away code once we get proper changelogs.

https://github.com/microsoft/fluentui/pull/19349

**Comment by miroslavstastny** [comment]
Closing this one, continues by RFC in #20881.
