### ISSUE TITLE
react-components documentation

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#19113]
- Component descriptions
- ~~Dos and Don’ts~~ Best practices - who does own the content? Design spec? per component or per example?
  - will we have dedicated content writers?
- Discuss A11y section usefulness (Elizabeth, Sarah)
- Props tables
- CI deployment to a meaningful URL
- Version switch

keep @ecraig12345  in the loop

**Comment by PeterDraex** [comment]
Progress is tracked in project react-components docs:
https://github.com/microsoft/fluentui/projects/51

**Comment by JustSlone** [comment]
Moving to Priority 2 as this does not block cutting a beta release. Still important for beta and customers
