### ISSUE TITLE
Definition of Done for v9 beta components

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#19119]
- DOD for beta
- Paul's list of tasks ?

**Comment by gouttierre** [comment]
### DoD for BETA

1. **Design Spec:**
	- [ ]  a) Signed Off.
2. Engineering Spec: 
	- [ ]  a) Signed Off
3. **Individual component package is tagged:**
	- [ ]  a) Has the "beta" tag on it (or the correct semver thing on it)
4. **Component must be in the suite package:**
	- [ ]  a) i.e.  @fluentui/react-components  
5. **Component must have a Storybook story that includes at least the following:** 
	- [ ]  a) Component name and description
	- [ ]  b) At least one code example - Code example should include all a11y/aria props if needed. In the past, our fluent examples  didn't set things like aria-label etc. So, if there are a11y patterns, we would want folks to copy and paste from our examples that should be in.
6. **Output of the API:**
	- [ ]  a) Should be easily done with the Control Add-in - Engineering to confirm
	- [ ]  b) [Optional] A link that points to known issues or bugs with the component on GitHub.
7. **Passes all conformance tests:** 
	- [ ]  a) Passes all the current/required testing: i.e. Regression, bundling, unit tests, ..
8. Component has been tested. against our Browser Matrix: 
	- [ ]  a) See issue #19117
9. **Supports a11y:** 
	- [ ]  a) High Contrast Mode 
	- [ ]  b) Narrator - As defined by our AT/Browser Matrix (#19117)
	- [ ]  c) Keyboarding
	- [ ]  d) Trusted Tester Verified? - A persons usually supplied by the E+D a11y testing team  
10. **Supports Design Tokens/Theming:** 
	- [ ]  a) Light Mode
	- [ ]  b) Dark Mode
	- [ ]  c) Supports all current out of the box Themes
11. **Supports Build-time CSS optimizations:**
	- [ ] a) What re the current CSS optimizations we have in Fluent - Engineering to confirm 
23. **Supports SSR:** 
	- [ ] a)  What are the current SSR test we have in place  - Engineering to confirm

**Comment by gouttierre** [comment]
FYI: I have moved the BETA talks started to this issue. cc: @Hotell , @miroslavstastny, @behowell, @levithomason, @JustSlone , @paulgildea

**Comment by gouttierre** [comment]
@smhigley could you help us out with point 9.  @paulgildea mentioned we will need to get your input expertise's on point 9. Would these sub-points be a sufficient requirement for a stable Beta release?

@layershifter for point 11 would this be around makestyles?

**Comment by JustSlone** [comment]
> Component has been tested. against our Browser Matrix:
 a) See issue Browser support matrix for v9 #19117

> Browser | Supported | Not supported
-- | -- | --
Microsoft Edge Chromium | X |  
Microsoft Edge Legacy | X |  
Internet Explorer 11 |   | X
Internet Explorer 10 |   | X
Internet Explorer 9 |   | X
Google Chrome (latest 2 versions) | X |  
Mozilla Firefox (latest 2 versions) | X |  
Apple Safari (latest 2 versions) | X |  
iOS Safari (latest 2 versions) | X |  
Android Safari (latest 2 versions) | X |  

I suggest that we do not need to test against last 2 versions during initial release of a component, testing against current should be sufficient. If it doesn't work in the prior version, and it works in current, it likely was a bug and was fixed, and there will be a new version soon, leaving the last version to fall out of support quickly.

**Comment by JustSlone** [comment]
>  d) Trusted Tester Verified? - A persons usually supplied by the E+D a11y testing team

This shouldn't be part of "done" it will likely happen async to beta and should not block beta. In-fact our list of "done" components will likely feed into trusted tester scheduling.
