### ISSUE TITLE
Next.js / SSR rendering issue with Stylesheet.getInstance()

### ISSUE THREAD

**Issue by imdavidmin** [microsoft/fluentui#19112]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^8.23.8", "next": "11.0.1"

### Reproduction
https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing

Using the official wiki guide doesn't work, as the line
 `import { Stylesheet, InjectionMode, resetIds } from '@fluentui/react/lib/Utilities';` 
doesn't seem to work properly. 

#### Actual behavior:
Results in the following error: `TypeError: Cannot read property 'getInstance' of undefined`

### Fix: 
Changing the import to `import { Stylesheet, InjectionMode } from '@fluentui/merge-styles'` currently works. (v8.1.3)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

**Comment by ling1726** [comment]
@ecraig12345  is this a documentation update that's needed or an bug in the exports of v8 ?

**Comment by imdavidmin** [comment]
FYI all three are exported from @fluentui/react

**Comment by dzearing** [comment]
Looks like the docs were updated to `@fluentui/react` which exports all 3 in both v7 and v8. Sorry for the trouble. Closing.
