### ISSUE TITLE
What components should be released as v9Beta?

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#19116]
**Currently in `react-components`:**
- accordion
- avatar
- badge
- button
- divider
- image
- label
- link
- menu
- popover
- portal
- provider
- tooltip

**Beta quality controls required (in `@fluentui/react-components`)** 
(Phase 1 & 2)
- [x] `Accordion` 
- [x] `Avatar` 
- [x] `Badge`
- [x] `Button` (and variants `MenuButton `, `ToggleButton`)
- [ ] `Icon` 
- [x] `Link` 
- [x] `Divider` 
- [x] `FluentProvider` 
- [x] `Menu` 
- [x] `Popover` 
- [ ] `Text` 
- [x] `Tooltip` 

Additional to include in the BETA release if ready before release.
(Phase 3 - Control candidates to consider by the team)
- [ ] `Label`
- [ ] `Checkbox`

**Comment by gouttierre** [comment]
**Beta Quality Controls required (in `@fluentui/react-components`)** 
- [ ] Accordion 
- [ ] Avatar 
- [ ] Badge
- [ ] Button (and variants) 
- [ ] Icon, 
- [ ] Link 
- [ ] Divider 
- [ ] FluentProvider 
- [ ] Menu 
- [ ] Popover 
- [ ] Text 
- [ ] Tooltip

**Comment by behowell** [comment]
We may want to consider `Label` and `Checkbox` as well; those are close to Beta quality at this point.

**Comment by gouttierre** [comment]
@paulgildea can we include `Label `and `Checkbox` - even though they are Phase 3?

**Comment by paulgildea** [comment]
Yeah totally! At a minimum we need Phase 1 and 2, if we can pull in anything more from Phase 3 that's close let's do it!

**Comment by layershifter** [comment]
`@fluentui/react-components@9-beta` was released sometime ago. Closing this for housekeeping 🏡
