### ISSUE TITLE
Browser support matrix for v9

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#19117]
v9 does not support IE11 -> the browser support matrix will be different compared to v8.

Followup work (fixes, tests) is After BETA

**Comment by gouttierre** [comment]
<html>
<body>
<h1 style="box-sizing: border-box; font-size: 2em; margin-top: 0px !important; margin-right: 0px; margin-bottom: 16px; margin-left: 0px; font-weight: 600; line-height: 1.25; border-bottom: 1px solid var(--color-border-secondary); padding-bottom: 0.3em; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Browser support</h1><p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Fluent UI React supports many commonly used web browsers such as  Google Chrome, Mozilla Firefox, Apple Safari, and Microsoft Edge. For browsers outside of this matrix, proper behavior of the components may be correct but it is not guaranteed.</p>

Browser | Supported | Not supported
-- | -- | --
Microsoft Edge Chromium | X |  
Microsoft Edge Legacy | X |  
Internet Explorer 11 |   |X
Internet Explorer 10 |   | X
Internet Explorer 9 |   | X
Google Chrome (latest 2 versions) | X |  
Mozilla Firefox (latest 2 versions) | X |  
Apple Safari (latest 2 versions) | X |

**Comment by gouttierre** [comment]
@behowell , @miroslavstastny , @Hotell -  I would like to get your thoughts on the support matrix for v9. The one that could be a challenge could be `Safari `support.

cc. @paulgildea , @levithomason

**Comment by paulgildea** [comment]
What is our current test coverage of these browsers? Just to help set expectations with customers. Meaning we actively test our components in Browser X, and we smoke test in Browser Y for example?

**Comment by gouttierre** [comment]
@ecraig12345 , @khmakoto , @Hotell  Do you know what is our current test coverage of these browsers?

**Comment by ling1726** [comment]
@gouttierre  is it possible to get some background into why legacy edge is supported, windows updates past 20H2 should permanently remove the ability to support it. 

Is it for on-prem customers that manage their own devices ? even then I think there's some limitations to them holding back windows updates

**Comment by JustSlone** [comment]
Should there be a Mobile split to this matrix? If we're going to support iOS and Android, we will also support Chrome and Edge on Mobile.

I would suggest that if we do this, we optimize the test matrix and not constantly run through every-single permutation. Remember, the support matrix and test matrix are not exactly the same, we will support more than we necessarily must actively test on a regular basis. 

i.e.

Browser | Supported | Not supported
-- | -- | --
Microsoft Edge Chromium | X |  
Microsoft Edge Legacy | X |  
Internet Explorer 11 |   | X
Internet Explorer 10 |   | X
Internet Explorer 9 |   | X
Google Chrome (latest 2 versions) | X |  
Mozilla Firefox (latest 2 versions) | X |  
Apple Safari (latest 2 versions) | X |  
**Mobile**|
Edge Chromium on Mobile | X |  
Google Chrome on Mobile | X |
iOS Safari (latest 2 versions) | X |  
Android Safari (latest 2 versions) | X |

**Comment by Hotell** [comment]
> @ecraig12345 , @khmakoto , @Hotell Do you know what is our current test coverage of these browsers?

we test only against headless chrome for vNext (if package has e2e tests), besides that tests are executed agains JSDOM (which is not a real browser engine) - so the test coverage is not ideal one lets say.

What helps a lot is that Edge/Chrome/Brave use same engine so there shouldn't be significant deviations (need to test against )

It would make sense to incorporate at least 1 Gecko/Webkit based browsers (note: this would slow down our CI)

**Comment by gouttierre** [comment]
> @gouttierre is it possible to get some background into why legacy edge is supported, windows updates past 20H2 should permanently remove the ability to use it. https://techcommunity.microsoft.com/t5/microsoft-365-blog/new-microsoft-edge-to-replace-microsoft-edge-legacy-with-april-s/ba-p/2114224
> 
> Is it for on-prem customers that manage their own devices ? even then I think there's some limitations to them holding back windows updates
> 
> It will be difficult for even the dev team to install the legacy browser for testing and the support metrics for JS features is fuzzy now that most support tables all use chromium edge

@paulgildea , @levithomason , @JustSlone - would you be able to provide some background context?

**Comment by gouttierre** [comment]
Support for `Legacy Edge ` is out for v9 but it will  be confirmed by @miroslavstastny before closing.
