### ISSUE TITLE
Review component APIs to ensure overall consistency

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#19115]
@ecraig12345 to potentially start the discussion

[days for audit, weeks for impl]

**Comment by JustSlone** [comment]
Need an owner for this item, @ecraig12345 for context and @behowell to find a driver

**Comment by ecraig12345** [comment]
Potentially relevant: #19458 adds `*.page.json` generation for react-components (by request from @paulgildea). These files are used to power the API reference tables on the v8 doc site and might be used on the new doc site too, hence the request to add them for converged.

A variant of this processing *might* also be useful for generating API comparison tables, but it doesn't currently support expanding extends or unions (and I'm not sure how hard that would be to add). Our fork of `react-docgen-typescript` under `scripts/gulp/plugins/util/docgen.ts` *does* support those things, so getting that working against converged is probably a better path for API comparison purposes.

**Comment by JustSlone** [comment]
@GeoffCoxMSFT to take point on generate a list of API names for comparison

**Comment by GeoffCoxMSFT** [comment]
PR to add comments to is here: https://github.com/microsoft/fluentui/pull/19775

**Comment by GeoffCoxMSFT** [comment]
Created work items:

- https://github.com/microsoft/fluentui/issues/19823
- https://github.com/microsoft/fluentui/issues/19824
- https://github.com/microsoft/fluentui/issues/19825
- https://github.com/microsoft/fluentui/issues/19826
