### ISSUE TITLE
Detail list filter problem in documentation

### ISSUE THREAD

**Issue by Crossmax14** [microsoft/fluentui#19128]
#### Describe the feature that you would like added

**I'm not entirely sure which category this should fall into, a bug or a feature request.**

The problem is in the detail list (in the documentation), when trying to filter, it does not behave as the user expects.
Going to the page https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist, some examples have an input field with the text "Filter by name", and entering there for example "lorem" everything works good, but already entering "Lorem" - does not return any option. 

The problem is in the implementation of the _onChangeText method in the first example (line 265).
You are convert the element names from the table to lower case, and do not convert the variable "text" to lower case - and a logical error occurs. 
But since this is a separate (_onChangeText) method, everyone who wants to change it can do it. However, this is a bug in the documentation and can be a little confusing for newbies. **Therefore, this is more of a documentation bug.**

#### What component or utility would this be added to

Detail list documentation - https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist
(and if the _onChangeText method is used in the other components - in those places too, I have not yet found such)

#### Have you discussed this feature with our team, and if so, who

Did not discuss

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/34413296/126914589-0aaa6caa-9be5-45c4-8a61-f9684efad136.png)

![image](https://user-images.githubusercontent.com/34413296/126914592-2a2ad55d-445e-4cd0-9020-e9d258eff7bf.png)

![image](https://user-images.githubusercontent.com/34413296/126914594-58f89f18-4af4-4eca-8b89-0c310286cb53.png)

**Comment by smhigley** [comment]
@Crossmax14 thanks for the bug and the thorough investigation! Is this something you would be interested in creating a PR to fix?

**Comment by Crossmax14** [comment]
@smhigley Hi, sorry for the late reply, I made the above change and can do a PR. How can I make a commit? At the moment I don't have the right to commit or PR.
