### ISSUE TITLE
onMenuDismissed gets called twice when sub-menu gets dismissed

### ISSUE THREAD

**Issue by makopch-ms** [microsoft/fluentui#19123]
Providing “onMenuDismissed” for a submenu actually calls the method twice. 

Here’s a codepen: https://codepen.io/kelseyyoung/pen/poPddXw
 
onMenuDismissed is provided for the “New Item” submenu, the method just logs “test” in the console. Repro steps:

Open dev console
Click “Click for Contextual Menu” to open the menu
Hover over “New Item”, sub menu opens
Hover over “Share”, observe that “test” is logged twice in the console

#### Actual behavior:

onMenuDismissed gets called twice.

In a production app like office online, we are seeing the closing of the sub-menu also close the main menu

#### Expected behavior:

onMenuDismiss only gets called once

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Blocking

Products/sites affected: Office-Online

**Comment by ling1726** [comment]
Thanks for the issue and repro @makopch-ms.

> In a production app like office online, we are seeing the closing of the sub-menu also close the main menu

This seems like a separate issue, from the way you describe it, is it linked to `onMenuDismissed` ?

**Comment by makopch-ms** [comment]
> Thanks for the issue and repro @makopch-ms.
> 
> > In a production app like office online, we are seeing the closing of the sub-menu also close the main menu
> 
> This seems like a separate issue, from the way you describe it, is it linked to `onMenuDismissed` ?

I was just stating the behavior that we are seeing in our app.  @kelseyyoung  and I believe this should fix the issue.

**Comment by behowell** [comment]
It looks like PR #14513 added a call to `useEffect` that invokes `onMenuDismissed` when the menu is unmounted, but didn't remove the call in `componentWillUnmount`, so now it's called in two places. Removing the `onMenuDismissed` call from `componentWillUnmount` should solve the issue. I'll publish a PR.
