### ISSUE TITLE
GroupedList should support filtering

### ISSUE THREAD

**Issue by mwiemer-microsoft** [microsoft/fluentui#19125]
#### Describe the feature that you would like added

Currently, the GroupedList component requires a tree structure (`groups`) and a backing flat list (`items`). If it's ever valuable to filter those items, the logic to filter is a bit complex, since both data structures need to be updated.

It would be great if `GroupedList` accepted a `filter: (item: any) => boolean` prop that updated the rendered `groups` and `items` to only show `items` where `filter(item) === true`.

Right now, I imagine there are many projects that use Fluent UI that are writing their own sorting logic, even though that logic is nearly identical for all of them.

#### What component or utility would this be added to

GroupedList

#### Have you discussed this feature with our team, and if so, who

No, I have not discussed the feature

#### Additional context/screenshots

None

**Comment by ling1726** [comment]
@mwiemer-microsoft Thanks for the the feature request, I've added it to the backlog for the v8 team to prioritize
