### ISSUE TITLE
Rendering Adaptive Card on Hover Card

### ISSUE THREAD

**Issue by shia940** [microsoft/fluentui#19142]
### Environment Information

- **Package version(s)**: Latest Package
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

I have attached hover card to some url in outlook mail. Hover Card renders adaptive card inside it. My adaptive card contains a list of choices from which a user can select any choice (Input.ChoiceSet in adaptive card). But, when I hover on any of the choices, the dismiss view of Hover Card is called and the Hover card gets dismissed (due to mouseleave event). So, user is not able to select any choice. 

#### Expected behavior:

Hover card should not get dismissed when user is hovering on the choices present in the card.  

### Priorities and help requested:

Please help me with the fix for this issue or any resolution that already exist for this.

Are you willing to submit a PR to fix? No, I am just using Hover Card component.

Requested priority: Medium

Products/sites affected: (if applicable)

**Comment by ling1726** [comment]
@shia940  Could you please provide a code repro so that we can investigate easier and also determine that there is no app specific code that needs to be in this repro ?
