### ISSUE TITLE
Dialog looses state on resize

### ISSUE THREAD

**Issue by MKHSKY** [microsoft/fluentui#19143]
### Environment Information
- **Package version(s)**: Latest on developer.microsoft.com
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
![ezgif-7-e30058ab4484](https://user-images.githubusercontent.com/42220355/127118737-f9cc45ee-e05d-4b3e-bf6b-90117e2ca1cb.gif)

#### Actual behavior:
Im checking a checkbox, on resize, the checkbox is unchecked, this 

#### Expected behavior:
The state should remain, maybe its because of a remount or something?

### Priorities and help requested:
No

Requested priority: Normal - High

**Comment by ling1726** [comment]
@MKHSKY  thanks for the issue, from what I've seen, the state is persisted, it seems to be rather the selected option styles are removed.

I added a `console.log()` to `onChange` and noticed that it was never called, even when the choice group selected indicator disappeared. 

This is most likely a bug

**Comment by fitzmill** [comment]
@ling1726 I've noticed this issue and my investigations show that the components inside the dialog get unmounted and remounted when the window gets resized. Not sure if this will help, but here's a stack trace taken from my browser when I set a breakpoint inside of a `componentWillUnmount` hook.
![image](https://user-images.githubusercontent.com/21179656/142487369-75c298ff-7af2-43a4-a3a5-838c10fc7687.png)
