### ISSUE TITLE
No error message animations for Dropdown Input

### ISSUE THREAD

**Issue by japamatSynapse** [microsoft/fluentui#19141]
### Environment Information

- **Package version(s)**: `"@fluentui/react": "^8.13.0",`
- **Browser and OS versions**: `"5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
`

### Reproduction of the bug in a codepen
[reproduction](https://codepen.io/japamat/pen/YzVePyB)

i can work around like this:
```ts
export const getDropdownStyles: IStyleFunctionOrObject<
  IDropdownStyleProps,
  IDropdownStyles
> = () => {
  return {
    errorMessage: {
      animationName: 'css-0, css-13',
      animationDuration: '0.367s',
      animationTimingFunction: 'cubic-bezier(0.1, 0.9, 0.2, 1)',
      animationFillMode: 'both',
    },
  };
};
```

This workaround feels brittle against any styling/animation name changes made to the package.

#### Actual behavior:

Error message just shows up

#### Expected behavior:

Error message should animate in like other input field `errorMessage` values.

### Priorities and help requested:

Are you willing to submit a PR to fix: No

Requested priority: Low

**Comment by ling1726** [comment]
Thanks for the issue and the great example @japamatSynapse , we'd be happy to review any contributions to Fluent too if you' like to check in this feature yourself

**Comment by japamatSynapse** [comment]
I found a stable workaround I feel comfortable deploying, just use the same animation fluent does for other inputs: 

```ts
import { AnimationStyles } from '@fluentui/theme';

export const getDropdownStyles: IStyleFunctionOrObject<
  IDropdownStyleProps,
  IDropdownStyles
> = () => {
  return {
    errorMessage: {
      ...AnimationStyles.slideDownIn20,
    },
  };
};
```

I have no idea on how to contribute to this project, let alone be able to test to see if the solution works, but id guess on your end its adding something like this to somewhere in [this file](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Dropdown/Dropdown.styles.ts#L348):

```tsx
import { AnimationClassNames } from '../../Styling';

export const getStyles(props) => {
  
  // ...code in between here
  return {
    
    // ... other IDropdownStyleProps here...
    errorMessage {
      // ... existing styles,
      AnimationClassNames.slideDownIn20,
    }
  }

}
```

at least that's how it [looks like its added to the TextField component](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/TextField/TextField.styles.tsx#L406-L408):


Hope this helps, cheers!
