### ISSUE TITLE
Base64 Format Support For Persona imageUrl

### ISSUE THREAD

**Issue by shariquekhan1997** [microsoft/fluentui#19146]
#### Describe the feature that you would like added

Persona component supports jpg png SVG and gif format in ImageUrl.
But it doesn't support the base64 format which we usually get in Dynamics CRM 365.

#### Additional context/Screenshots

![image](https://user-images.githubusercontent.com/36981186/127133843-19dfbc82-f9fe-4e9c-bd47-ed0e55a15531.png)

#### Question
Is there a way I can get my bas64 format image in Persona?

**Comment by ling1726** [comment]
@ecraig12345 do you know anything about image support here ?

**Comment by ecraig12345** [comment]
I'm able to create a Persona, PersonaCoin, or Image with a base64 data-url and it works fine: https://codepen.io/ecraig12345/pen/YzVLzBE

@shariquekhan1997 If you've seen this not working in some other case, can you make a modified copy of the codepen showing that?

**Comment by shariquekhan1997** [comment]
Ok I got the point, actually I don’t know beforehand if it will be png or jpg so wasn’t adding the first few characters.
data:image/png;base64
