### ISSUE TITLE
DetailsList header text supporting JSX Element instead of only string

### ISSUE THREAD

**Issue by haugerbr** [microsoft/fluentui#19154]
#### Describe the feature that you would like added

I wanted to add tooltips to headers and the only way to do it that didn't destroy custom styling was to cast the header text to **any** and pass it a JSX element. This also made sure the sorting and filter icons that are built in still work. Since this already works, it would be nice to see the typing changed to JSX element. I understand accessibility could be a potential issue in doing that though.  

#### What component or utility would this be added to

DetailsList

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/660975/127206164-9113f4d9-b6cf-4bf9-9095-f2b3474cf933.png)

**Comment by ling1726** [comment]
@haugerbr  thanks for the feature request. I've put it in the backlog, but unfortuantely `DetailsList` features are not cheap to implement, so it might take some time for us to get onto it.

If you would like to contribute this feature feel free to drop a PR and we can help you review it.
