### ISSUE TITLE
FocusTrapZone's focusAsync (from component mount) firing after child's async function

### ISSUE THREAD

**Issue by makopch-ms** [microsoft/fluentui#19157]
### Environment Information

- **Package version(s)**: Fluent v8 (latest)
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:
v7: https://codepen.io/makopch/pen/eYWVPNj
v8: https://codepen.io/makopch/pen/ZEKrqYR

#### Actual behavior:

Focus goes to the first button in the panel

#### Expected behavior:

Focus goes to the second button which the panel content sets

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) yes, but unsure what the fix is

Requested priority: (Blocking, High, Normal, Low): Blocking

Products/sites affected: Office Online

useLayoutEffect fixes the issue vs. useEffect but we are using class components in our code not functional.  If this is by design, please help provide an alternative.

**Comment by behowell** [comment]
I tried removing `requestAnimationFrame` from the example using v8, and it works: the second button is focused when the panel opens. Is that a viable workaround? I'm not sure why `requestAnimationFrame` was there in the first place?
https://codepen.io/behowell/pen/oNWEaqj

**Comment by makopch-ms** [comment]
We are using requestAnimationFrame for performance purposes so that we can push actions off so we can render faster / avoid long frames.

Is there a reason for the timing difference, in that both v7 and v8 both are doing this in focusAsync but v8 seems to be happening later?
