### ISSUE TITLE
ChoiceGroup sample onchange Type Error

### ISSUE THREAD

**Issue by Yongjun042** [microsoft/fluentui#19161]
### Environment Information

- **Package version(s)**: react 17.0.2 @fluentui/react 8.23.10 typescript 4.1.2
- **Browser and OS versions**: Firefox Windows10

### Please provide a reproduction of the bug in a codepen:

https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup
Copy Basic ChoiceGroup and Controlled ChoiceGroup sample code.

https://codesandbox.io/s/choicegrouponchangeerror-topf3?file=/src/choice.tsx

#### Actual behavior:

Basic ChoiceGroup 
```

Type '(ev: FormEvent<HTMLInputElement>, option: IChoiceGroupOption) => void' is not assignable to type '(ev?: FormEvent<HTMLElement | HTMLInputElement> | undefined, option?: IChoiceGroupOption | undefined) => void'.
  Types of parameters 'ev' and 'ev' are incompatible.
    Type 'FormEvent<HTMLElement | HTMLInputElement> | undefined' is not assignable to type 'FormEvent<HTMLInputElement>'.
      Type 'undefined' is not assignable to type 'FormEvent<HTMLInputElement>'.ts(2322)
ChoiceGroup.types.d.ts(44, 5): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & IChoiceGroupProps & { children?: ReactNode; }'

```

Controlled ChoiceGroup 

```
Type '(ev: React.SyntheticEvent<HTMLElement>, option: IChoiceGroupOption) => void' is not assignable to type '(ev?: FormEvent<HTMLElement | HTMLInputElement> | undefined, option?: IChoiceGroupOption | undefined) => void'.
  Types of parameters 'ev' and 'ev' are incompatible.
    Type 'FormEvent<HTMLElement | HTMLInputElement> | undefined' is not assignable to type 'SyntheticEvent<HTMLElement, Event>'.
      Type 'undefined' is not assignable to type 'SyntheticEvent<HTMLElement, Event>'.ts(2322)
ChoiceGroup.types.d.ts(44, 5): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & IChoiceGroupProps & { children?: ReactNode; }'
```

#### Expected behavior:

No error.

### Priorities and help requested:

No

Requested priority: (Blocking, High, Normal, Low)

Normal

Products/sites affected: (if applicable)

**Comment by ling1726** [comment]
@Yongjun042  thanks for the great code repro. Unfortunately the typings can all be `undefined` so you'll need to type them as such and add guards for usage. I forked your sandbox and fixed these issues here: https://codesandbox.io/s/choicegrouponchangeerror-forked-gyf7x?file=/src/control.tsx

@ecraig12345  are these aggressive `undefined` types by design ?

**Comment by Yongjun042** [comment]
> 
> 
> @Yongjun042 thanks for the great code repro. Unfortunately the typings can all be `undefined` so you'll need to type them as such and add guards for usage. I forked your sandbox and fixed these issues here: https://codesandbox.io/s/choicegrouponchangeerror-forked-gyf7x?file=/src/control.tsx
> 
> @ecraig12345 are these aggressive `undefined` types by design ?

Thank you for answer!

**Comment by ecraig12345** [comment]
> @ecraig12345 are these aggressive `undefined` types by design ?

Probably not, but unfortunately we can't change it to make them required outside a major release because that would be a breaking change.
