### ISSUE TITLE
@fluentui/react - Warning on conflicting exports

### ISSUE THREAD

**Issue by sivapalaniappan** [microsoft/fluentui#19177]
### Environment Information

- **Package version(s)**: 8.23.10
- **Browser and OS versions**: Edge - 92.0.902.55 and Win 10 Enterprise

### Please provide a reproduction of the bug in a codepen:

1. `npm install @fluentui/react`
2. Import any utility/component and use it in your js file.
3. Run webpack-dev-server

#### Actual behavior:

`
WARNING in ./node_modules/@fluentui/react/lib/index.js 84:0-24
The requested module './Theme' contains conflicting star exports for the names 'AnimationStyles', 'AnimationVariables', 'DefaultEffects', 'DefaultFontStyles', 'DefaultPalette', 'FontSizes', 'FontWeights', 'IconFontSizes', 'createFontStyles', 'createTheme', 'registerDefaultFontFaces' with the previous requested module './Styling'
 @ ./src/components/WhiteboardingInProgress/WhiteboardingInProgress.tsx 3:0-40 18:32-37
`

#### Expected behavior:

The warning shouldn't appear

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) NO

Requested priority: (Blocking, High, Normal, Low) HIGH

Products/sites affected: (if applicable) whiteboard.microsoft.com

**Comment by ling1726** [comment]
@sivapalaniappan  thanks for the repro steps

Possible conflicting exports should be handled ASAP, assigning high priority for someone in the v8 team to investigate further.

**Comment by bryanchen-d** [comment]
Any updates on this? 

I am hitting the same issue but it is an error to me:
> ERROR in ./node_modules/@fluentui/react/lib/index.js 84:0-24
The requested module './Theme' contains conflicting star exports for the names 'AnimationStyles', 'AnimationVariables', 'DefaultEffects', 'DefaultFontStyles', 'DefaultPalette', 'FontSizes', 'FontWeights', 'IconFontSizes', 'createFontStyles', 'createTheme', 'registerDefaultFontFaces' with the previous requested module './Styling'

Also wondering how should I turn it into a warning for workaround?

**Comment by robcecil** [comment]
Getting this error today.

**Comment by KHeavyy** [comment]
+1. Issue is only happening after upgrading webpack (from 4.41.31 to 5.28.0) and webpack-dev-server (from 3.11.6 to 4.1.0).

**Comment by layershifter** [comment]
We are tracking this under #20178, but #20665 should already solve all issues (?). If there is still something, please follow up in #20178.
