### ISSUE TITLE
Object.assign not polyfilled in Pivot component which breaks the experience in IE11

### ISSUE THREAD

**Issue by dinoilic** [microsoft/fluentui#19181]
### Environment Information

- **Package version(s)**:
```
"@fluentui/font-icons-mdl2": "^8.1.1",
"@fluentui/merge-styles": "^8.1.1",
"@fluentui/react": "^8.15.1",
"@fluentui/react-experiments": "^8.1.17",
"@fluentui/react-file-type-icons": "^8.1.1",
"@fluentui/set-version": "^8.1.1",
"@fluentui/style-utilities": "^8.1.1",
"@fluentui/utilities": "^8.1.1",
```
- **Browser and OS versions**: Internet Explorer 11

### Please provide a reproduction of the bug in a codepen:
Unfortunately there is no possible repro on CodePen since CodePen does not support IE11. If you can create a small application and try using the `<Pivot>` component and load the page in IE11. You should get this error:

`Object doesn't support property or method 'assign'`

Here are the results of my investigation:

1. `Pivot` [component](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Pivot/Pivot.base.tsx) uses `useOverflow` hook.
2. `useOverflow` [hook](https://github.com/microsoft/fluentui/blob/792c8704a51393fae9d727ad39323dd157251956/packages/react-tabs/src/utilities/useOverflow.ts#L54) uses `useRefEffect` hook
3. `useRefEffect` [hook](https://github.com/microsoft/fluentui/blob/792c8704a51393fae9d727ad39323dd157251956/packages/react-hooks/src/useRefEffect.ts#L32) uses `Object.assign` which is not polyfilled

#### Actual behavior:

- App crashes with the above error since `Pivot` component can't render

#### Expected behavior:

- App works as expected with either correct polyfills in place or not using `Object.assign` in general.

### Priorities and help requested:

Are you willing to submit a PR to fix? **Yes, if we have a clear guidance from fluent team on how to best proceed**

Requested priority: **Blocking - this is blocking several M365 products from shipping new versions**

Products/sites affected: **SharePoint, Office.com, and any other place using `Pivot` in IE11**

**Comment by ling1726** [comment]
@dinoilic  thanks for the great issue, marking as high priority since v8 should support IE11

**Comment by dinoilic** [comment]
Thanks @ling1726 - I encountered another issue which started appearing after our migration to v8, however I think we would need to investigate further since it's only reproducible in one specific case related to SharePoint. Is there any way I can share more details about this?

**Comment by dinoilic** [comment]
@ling1726 Yeah, I understand that a code repro would be the best, however it's very difficult since it's related to IE11 and the only place where I can reproduce is in SharePoint, so opening a new issue would be pointless without a proper repro.

**Comment by ling1726** [comment]
@dinoilic  please create a new issue anyway, let's keep this issue focused to a problem we **do** know about
