### ISSUE TITLE
FocusTrapZone not working with content that have IFrame only

### ISSUE THREAD

**Issue by QuangThuanDinh** [microsoft/fluentui#19191]
### Environment Information

- **Package version(s)**: 7.173.1
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

This issue can repro in this codepen example: https://codepen.io/qthuan/pen/NWjYaav
- 
#### Actual behavior:

If the content of FocusTrapZone have only IFrame:
- The circle focus is not working: When stay in the first element within the IFrame, press Shift + Tab, the tab focus is navigate out of FocusTrapZone (the same with stay in the last Element and press Tab)
- The API ref.current.focus() is not working

#### Expected behavior:

- FocusTrapZone should keep the focus inside, if stay in the last element of the IFrame and press Tab keyboard, it should stay within iFrame
- the API ref.current.focus() should work and navigate the focus to iFrame content (iframe.contentWindow.focus() )

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable) PowerApp

**Comment by gouttierre** [comment]
@QuangThuanDinh - thank you for filing this issue and providing the codepen.

@smhigley - Would you be able to confirm if this is a regression, or if this behavior is an issue with the API ref.current.focus() ?
