### ISSUE TITLE
Request to add a new optional props shouldEscClearsSelection to SelectionZone.tsx

### ISSUE THREAD

**Issue by eloisepeng** [microsoft/fluentui#19205]
#### Describe the feature that you would like added

M365 Content Picker is using SelectionZone component. and we found that when there's any content selected, if a user press the "Esc" key, it will deselect all content and then one more press on "Esc" key will close the dialog. But we actually want to close the dialog immediately when the user press the "Esc" key whether there's any selected items. It will be great to add a new optional props shouldEscClearsSelection to SelectionZone.tsx, so that the M365 Content Picker can turn it off. 

#### What component or utility would this be added to

SelectionZone.tsx

#### Have you discussed this feature with our team, and if so, who

N/A

#### How to test it

What it does now: 
Open any Office WXP, Insert -> Picture -> Stock Images, select any content. Pressing "Esc" 1st time will deselect all content, and 2nd press will close the dialog. 

What we want:
Open any Office WXP, Insert -> Picture -> Bing Pictures, select any content. Pressing "Esc" will close the dialog immediately

###

**Comment by smhigley** [comment]
I'd be in favor of adding an `onKeyDown` prop to SelectionZone to give flexibility to handle this, or any other custom keyboard behaviors.

In this case, you could then do something like this:
```js
<SelectionZone onKeyDown={() => {
  this.closeDialog();
  return false;
}}>
```

@eloisepeng would that solve your use case?

**Comment by eloisepeng** [comment]
Hi @smhigley, `onKeyDown` works as long as it allows us to custimize to close the dialog with 'esc' key. Thanks

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.
