### ISSUE TITLE
@fluentui/e2e: yarn test does not work on Windows

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#19217]
### Environment Information

- **Package version(s)**: `master`
- **Browser and OS versions**: Windows 10

### Please provide a reproduction of the bug in a codepen:

- jump to E2E directory, `cd packages/fluentui/e2e`
- run `yarn test`

It looks that command should contain be escaped:

https://github.com/microsoft/fluentui/blob/147ad1114e2e9261aae0908b98b7244a8b8997a7/scripts/gulp/plugins/gulp-cypress.ts#L19

```diff
-  const command = `./node_modules/.bin/cypress run --config ${configArguments.join(',')}`;
+  const command = `"./node_modules/.bin/cypress" run --config ${configArguments.join(',')}`;
```

Then it works 😄

#### Actual behavior:

```
[14:43:06] Requiring external module @fluentui/scripts/babel/register
[14:43:11] Using gulpfile ~\WebstormProjects\office-ui-fabric-react\packages\fluentui\e2e\gulpfile.ts
[14:43:11] Starting 'test:e2e:run'...
./node_modules/.bin/cypress run --config baseUrl=http://localhost:8082,integrationFolder=C:\office-ui-fabric-react\packages\fluentui\e2e\tests
'.' is not recognized as an internal or external command,operable program or batch file.
```

#### Expected behavior:

Test will run.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by ecraig12345** [comment]
@layershifter Do you know if it's still an issue?

**Comment by layershifter** [comment]
I checked it around a month ago and it was still a thing.
