### ISSUE TITLE
Basic DetailsList spacing accessibility bug (website-specific)

### ISSUE THREAD

**Issue by LucyLiYY** [microsoft/fluentui#19213]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: Edge

### Describe the issue:

Use text spacing bookmarklet to apply the text spacing

When you run the text spacing against: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic the selection column spacing is off.

#### Actual behavior:

The selected column spacing is off
![image](https://user-images.githubusercontent.com/17995942/127731984-f0ea4dd0-f831-4329-a61a-0c159198aada.png)

#### Expected behavior:

Expect the selected column image to align up properly.

### Documentation describing expected behavior

MAS 1.4.12 - Text Spacing

**Comment by gouttierre** [comment]
@LucyLiYY - thanks for filing this issue with us.

@smhigley - would you be able to review the behavior and triage it accordingly for Shield? Thanks

**Comment by smhigley** [comment]
This looks like a docsite bug, since it doesn't reproduce in storybook. It's caused by this style in a minified stylesheet inserted into the docs site:
```css
.ms-Icon {
  display: inline-block;
}
```

It's overriding the `display: inline-flex` style that was originally written to fix this bug.
