### ISSUE TITLE
[web-components] Tooltip: position relative to anchor is incorrect

### ISSUE THREAD

**Issue by dmoncada** [microsoft/fluentui#19221]
I wanted to leverage the `Tooltip` component from the FluentUI web components package in my app. However, I'm noticing the tooltip is not positioning itself correctly relative to the provided anchor; Consider the following minimal html:

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <script type="module" src="https://unpkg.com/@fluentui/web-components"></script>
</head>

<body>
  <fluent-button id="my-button" style="margin: 20px 0 0 20px;">I'm a button</fluent-button>
  <fluent-tooltip anchor="my-button" position="right">I'm a tooltip</fluent-tooltip>
</body>

</html>
```

**Expected:**
Hovering over the button should show a tooltip to the right of the button.

**Actual:**
The tooltip: 1) is shown below the button, and 2) is not aligned to the center of the button.

![image](https://user-images.githubusercontent.com/26721319/127916340-88c18792-f65d-4027-ad66-e9598c2490a6.png)

I'm also able to repro by pulling the `npm` package for the web components via `npm install` and then referencing the script (both minified and non-minified versions of the script) by replacing line 5 in the above html with:

```html
<script type="module" src="node_modules/@fluentui/web-components/dist/web-components.min.js"></script>
```

If I'm misconfiguring the tooltip please let me know (the documentation around the FluentUI web components is a bit scarce unfortunately 😔)

### Environment Information

- **Package version**: `1.3.1` (installed from CDN)
- **Browser version:** Microsoft Edge, `92.0.902.62` (Official build) (64-bit)

**Comment by chrisdholt** [comment]
@scomea Can you take a look and advise if this is a bug or implementation issue?

**Comment by scomea** [comment]
Looks like the tooltip template is generating malformed html, missing a space after the tag name.  Investigating.

![image](https://user-images.githubusercontent.com/7649425/127931644-25d36fa0-53e0-4777-bd3f-9ea41deeca8f.png)

**Comment by scomea** [comment]
Space is also missing in the menu item template between the generated tag and the first prop/attribute:  

![image](https://user-images.githubusercontent.com/7649425/127934338-31627e43-7578-4669-809c-c69b765a082d.png)

The source template looks like so:
![image](https://user-images.githubusercontent.com/7649425/127934437-8318d307-9a1d-4818-b2b6-9e75e31a3c68.png)

**Comment by scomea** [comment]
I'm wondering if ```${context.tagFor(AnchoredRegion)}``` in the templates should be wrapped in quotes ```"${context.tagFor(AnchoredRegion)}"```  @EisenbergEffect thoughts?

**Comment by dmoncada** [comment]
I updated the issue description above, as I'm able to repro using 1) the script from a CDN, and 2) the script from the `npm` package (both min and non-min versions)...

Playing a bit with the source delivered via `npm`, it seems like the issue is resolved by just adding the missing space after `context.tagFor()` like Stephane mentioned:

![image](https://user-images.githubusercontent.com/26721319/127939216-3a9a6f46-25b7-452e-be42-29117e3d4eef.png)

![image](https://user-images.githubusercontent.com/26721319/127939156-9c59c865-2b00-401a-8add-236afb387470.png)

**Comment by EisenbergEffect** [comment]
Not quotes, but definitely needs a space, since that API returns the element name.

**Comment by chrisdholt** [comment]
> Not quotes, but definitely needs a space, since that API returns the element name.

I think we need to investigate here as the spaces appear to exist in the templates and this *only* exists from what I can tell in the rollup instances getting generated...my initial reaction given the growing evidence is that we need to check on how we're transforming the HTML fragments of the template literals and see if this is a case we haven't addressed yet.

**Comment by EisenbergEffect** [comment]
If it's only in the rollup bundles, then maybe there's a plugin configured that's trying to minify the html...incorrectly.

**Comment by chrisdholt** [comment]
> If it's only in the rollup bundles, then maybe there's a plugin configured that's trying to minify the html...incorrectly.

Yeah, this is my guess and we own the rollup plugins on our end. I'm going to put a question out to @radium-v when he's back online and see if he can take a look. My *hunch* is that it's related to that - though I could be wrong.

**Comment by nicholasrice** [comment]
There is a bug filed on FAST that sounds related: https://github.com/microsoft/fast/issues/4692

**Comment by dmoncada** [comment]
Hello! Just wanted to ask real quick, are there any updates for this issue?

**Comment by scomea** [comment]
I believe this should have been resolved with https://github.com/microsoft/fast/pull/5038
Please let us know if this is not the case.

**Comment by dmoncada** [comment]
@scomea I'm sorry, do you mean the issue that you reference has been resolved? For the fluent tooltip, I'm still seeing the exact same behavior (space between tag and prop is still missing), I just repro'd using the same html that I posted in the description up above, using both a CDN and the `npm` package. Package version is `1.3.5`.

**Comment by radium-v** [comment]
It looks like the fix in `@microsoft/fast-components` wasn't applied on the fluent side and will need to be brought up to date here.

**Comment by chrisdholt** [comment]
> It looks like the fix in `@microsoft/fast-components` wasn't applied on the fluent side and will need to be brought up to date here.

Reopening the issue based on this and the fact that the transform script is unique to each instance.

**Comment by chrisdholt** [comment]
Working on this and will see if we can get it in by EOD for the nightly publish.
