### ISSUE TITLE
[react-northstar] TypeError: Cannot read property 'document' of null

### ISSUE THREAD

**Issue by creage** [microsoft/fluentui#19233]
### Environment Information

- **Package version(s)**: 0.57.0
- **Browser and OS versions**: Chrome, Win10

The `doUpdate()` call of `whatInput` utility expects a `view` to be always defined on `event` parameter, and does not validate if it is `null` or not
https://github.com/microsoft/fluentui/blob/31f949a20e204a266fc3849b128ea0be083c1dda/packages/fluentui/react-northstar/src/utils/whatInput.ts#L125

when trying to test FluentUI component using `react-testing-library`, extended with [`user-event`](https://github.com/testing-library/user-event), something like:

```js
import React from 'react';
import { FormInput } from '@fluentui/react-northstar';

import {render, screen} from '@testing-library/react';
import userEvent from '@testing-library/user-event';

test('type in form input', () => {
  render(
    <FormInput label="Test" placeholder="welcome" />
  );

  userEvent.type(screen.getByPlaceholderText('welcome'), 'hello');

  expect(screen.getByDisplayValue('hello')).toBeInTheDocument();
});
```
The test is always failing on `userEvent.type` call. Apparently, `user-event` does not generate proper UIEvent, and the `view` property of it is always null.

But FluentUI code should still survive unexpected parameters, I believe.

**Comment by gouttierre** [comment]
@creage - thanks for filing this issue with us.

@jurokapsiar  -  Would your team be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by Ethan-Arrowood** [comment]
I believe this is also an issue with the DOM that Jest provides for testing (JSDom iirc). Any updates from the northstar folks on this? It is prevent us from testing our application
