### ISSUE TITLE
OverflowSet does not support custom icon

### ISSUE THREAD

**Issue by flyingbee2012** [microsoft/fluentui#19269]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/flyingbee2012/pen/rNmZKqm
please see line 50 where I use src='url of the custom icon', but it doesn't show anything

#### Actual behavior:

The OverflowSet component doesn't support custom icons, but only support existing icons (e.g.  setting icon: 'Upload' )

#### Expected behavior:

We expect that the OverflowSet component would allow us to display custom icons by specifying the url of the icon

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Outlook on the web

**Comment by gouttierre** [comment]
@flyingbee2012 - Thanks for filing this issue with us. Our team will have a look but to set expectations, we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items.

@bsunderhus - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by bsunderhus** [comment]
Hey @flyingbee2012 , `OverflowSet` does support custom icons by the usage of the method `onRender`, which you can use to declare a custom rendering for the item, as you can verify in the following example on [codesandbox](https://codesandbox.io/s/overflowset-does-not-support-custom-icon-nkk96?file=/src/index.tsx)

![image](https://user-images.githubusercontent.com/5483269/136226014-c52dfa21-a458-4367-a6f6-921223c9f403.png)
