### ISSUE TITLE
PrimaryButton turns primary color on hover in Azure light theme

### ISSUE THREAD

**Issue by raharri** [microsoft/fluentui#19265]
### Environment Information

- **Package version(s)**: azure-themes 8.1.16
- **Browser and OS versions**: Windows Chrome 92.0.4515.107

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/raharri/pen/qBmMxdj

#### Actual behavior:

![2021-08-04 primary button bug](https://user-images.githubusercontent.com/57734445/128246671-0cfd7fbf-5571-4103-9bdb-4be2f4b78263.gif)

#### Expected behavior:

The disabled button should not change color when hovered over (just as the default button doesn't). Customers may be confused if a disabled button appears to be clickable.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Azure IoT Hub and probably other Azure sites

**Comment by ecraig12345** [comment]
@Jacqueline-ms Can you help with this since it's specific to the Azure theme?

**Comment by Jacqueline-ms** [comment]
@ecraig12345 thanks for passing this along. One of our recent PRs addressed this issue in both 7.0 and main branches, but I can't find the specific PR. I just built both branches and this bug no longer exists. @raharri - which version are you using?

**Comment by Jacqueline-ms** [comment]
Here's the fix: https://github.com/microsoft/fluentui/pull/19015
