### ISSUE TITLE
Weird name of an icon

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/fluentui#19278]
#### Describe the feature that you would like added

An icon named "Error" is now presented as an exclamatory mark with a circle outside. This graphic does not remind me an error but something lower than an error. I think it should be renamed as "Alert" or else, and then rename the icon "ErrorBadge" to "Error".

#### What component or utility would this be added to

Icon

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

![Icon "Error"](https://user-images.githubusercontent.com/21080720/128371222-b232ad09-0c21-4071-b20c-3cd77cd5fa3b.png)
![Icon "ErrorBadge"](https://user-images.githubusercontent.com/21080720/128371556-4a253551-9b31-40d4-835f-f41892c26d0f.png)

**Comment by gouttierre** [comment]
@AkiraVoid - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
