### ISSUE TITLE
Allow user to edit value directly with a TextField in Slider component

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#19289]
#### Describe the feature that you would like added

We'd like user to be able to edit the value of the slider directly, instead of dragging the thumb button.

#### What component or utility would this be added to

Slider component

#### Have you discussed this feature with our team, and if so, who

None.

#### Additional context/screenshots

Our current implementation looks as follows. It would be great if fluentui provides standard implementation.

![Animation](https://user-images.githubusercontent.com/50703224/128474798-c0b3a06f-5c41-4d99-92cc-8b61c186b72a.gif)

![Animation](https://user-images.githubusercontent.com/50703224/128475178-e722e822-1c19-4d1c-83e3-73d79b20c719.gif)

**Comment by gouttierre** [comment]
@chenxinyanc - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. However, If you come up with a solution for the feature and would like to submit a PR for this request, we would love to see it!

**Comment by etheodoridou** [comment]
Thank you for adding this control!
