### ISSUE TITLE
northstar FormDropdown throws StrictMode error

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/fluentui#19286]
### Environment Information

- **Package version(s)**: northstar 0.57.0

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/black-framework-1w095?file=/src/App.js

#### Actual behavior:

Works okay but warns long StrictMode error in console

#### Expected behavior:

Since this is supposed to be the next iteration of Fluent UI I'd expect it to also support StrictMode (https://github.com/microsoft/fluentui/wiki/Version-8-release-notes#react-strict-mode-support)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Internal project

**Comment by gouttierre** [comment]
@Ethan-Arrowood  - thanks for filing this issue with us.

@jurokapsiar  -  Would your team be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by layershifter** [comment]
> Since this is supposed to be the next iteration of Fluent UI I'd expect it to also support StrictMode (https://github.com/microsoft/fluentui/wiki/Version-8-release-notes#react-strict-mode-support)

_Small comment_: v8 is not next iteration of `@fluentui/react-northstar`, these libraries are two separate solutions.

---

Our team currently actively works on native ref forwarding (#20812, #20813, #20814, etc.) in Northstar components. Once it will be done we plan to get rid of `ReactDOM.findDOMNode()` (i.e. `Ref`) calls at all.

It should not be a problem for usage with React 16/17 and warnings in production are removed.

**Comment by carocao-msft** [comment]
@layershifter Hi, I am wondering if the PRs you mentioned have solved this issue completely, or are there extra updates needed? We currently have a customer issue regarding StrictMode error and we are wondering if the latest version has resolved this issue already :)
