### ISSUE TITLE
Can't select text in monaco editor inside panel/dialog

### ISSUE THREAD

**Issue by wamoha** [microsoft/fluentui#19299]
### Environment Information

- **Package version(s)**: 
- @fluentui/react - 8.13.1
- @fluentui/react-hooks - 8.1.3
- monaco-editor - 0.22.3
- **Browser and OS versions**:
- Chrome : 91.0.4472.124 (Official Build) (32-bit)

### Please provide a reproduction of the bug in a codepen:

When rendering monaco editor inside a Panel/Dialog component, the text cannot be selected. However, if it's rendered in a separate div, the content can be selected with mouse.  Here's a code example:
`
import React from "react";
import * as Monaco from "monaco-editor";
import { Panel, Dialog } from "office-ui-fabric-react";

export const JsonPanel: React.FunctionComponent = () => {
  const sampleJson =
    '{\n    "Id": "f726dad1-75ef-482c-9682-7e8a76264edf",\n    "Uuid": "2abe6abe-e8a3-4bfd-bbac-f074578ef8d2",\n    "parentUuid": null,\n    "rootUuid": "2abe6abe-e8a3-4bfd-bbac-f074578ef8d2",\n    "target": "sdk",\n    "status": "Completed",\n    "parentId": null,\n    "createdTimeUtc": "2019-10-01T20:56:59.6064455+00:00",\n    "startTimeUtc": "2019-10-01T20:56:59.915Z",\n    "endTimeUtc": "2019-10-01T20:57:11.730Z",\n ';

  React.useEffect(() => {
    import("monaco-editor").then(monaco => {
      monaco.editor.create(document.getElementById("monacoPanel") as HTMLElement, {
        value: sampleJson,
        language: "json",
        readOnly: true,
        wordWrap: "on",
        renderLineHighlight: "none",
        folding: false,
        scrollBeyondLastLine: false
      });
    });
  }, []);

  return ( 
\<Dialog hidden={false}>
      <div id="monacoPanel" style={{ width: "100%", height: "100vh", overflow: "hidden", clear: "both" }}></div>
    \</Dialog>
  );
};`

#### Actual behavior:

The monaco editor renders in the panel/dialog, however the content cannot be selected with mouse. If the same component is not rendered in a dialog/panel, the content can be selected.
The way codepen renders the content in an iframe may not be the right repro in this case. Also, monaco uses workers behind the scenes, so the right repro could be setting up in local environment.

#### Expected behavior:

Content should be selecteable in the editor.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@wamoha - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by wamoha** [comment]
[frontend-bootcamp.zip](https://github.com/microsoft/fluentui/files/6992177/frontend-bootcamp.zip)

The attached zip has a repro. It's forked from [bootcamp](https://github.com/Microsoft/frontend-bootcamp). I've added monaco-editor package and related webpack plugin. The changes needed to test can be found [here](http://localhost:8080/step2-02/demo/).
To run in local - 

- npm install
- npm start

There's no issue with the below react configuration - 
"react": "^16.8.3",
"react-dom": "^16.8.3"

**The issue is reproducible with** 
"react": "^17.0.2",
"react-dom": "^17.0.2"

**Comment by wamoha** [comment]
Any update on this issue?

**Comment by AlexandreGarino** [comment]
I've got the same issue. The Monaco editor is rendered inside a Layer component.

Package version(s):
react - 17.0.2
@fluentui/react - 8.30.0

**Comment by AlexandreGarino** [comment]
I guess this issue is related to this breaking change: https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation

I downgraded React to 16.14 on my project. I am still using FluentUI 8.x.

**Comment by spmonahan** [comment]
@AlexandreGarino I believe you are correct that this issue is related to the event delegation changes in React 17.

If you're using `Layer` directly you can pass `true` to the [eventBubblingEnabled](https://developer.microsoft.com/en-us/fluentui#/controls/web/layer#implementation) prop to allow events to bubble up from `Layer`. Based on my investigation in #20009 this should also Monaco to work in a `Layer` as it did in React 16.

**Comment by spmonahan** [comment]
@wamoha Looking at your example, I believe if you change `<Dialog ...` to

```
<Dialog
  modalProps={{
    layerProps: {
      eventBubblingEnabled: true
    }
  }
 ...
```

text selection should work with Monaco editor.
