### ISSUE TITLE
Button - Split mode - Cannot tab to the split button when the primary button is enabled

### ISSUE THREAD

**Issue by jwenger100** [microsoft/fluentui#19294]
### Environment Information

- "@fluentui/react": "^7.127.0",
- Microsoft Edge
Version 91.0.864.71
Windows 10 Enterprise
OS Build: 19043.1110

### Describe the issue:

When tabbing on my webpage using the Fluent UI DefaultButton Control, I am passing the split property in and when I tab, it tabs to the button but not to the split button with the Chevron. An A11y user would not be able to discover the options in the split button with keyboard control.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/jwenger100/pen/xxdyzOE

#### Actual behavior:

When tabbing, the split button is never reached.

#### Expected behavior:

The split button should be reached so that a user with keyboard controls can select the options.

### Documentation describing expected behavior

N/A

**Comment by khmakoto** [comment]
Hi @jwenger100, this behavior is by design. The focus target is on the entire button and the split button controls are keyboard accessible via the standard ALT+Down keyboard command for menu interactions.

**Comment by jwenger100** [comment]
Thanks for the response!
