### ISSUE TITLE
Strange behavior of password TextField

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/fluentui#19295]
### Environment Information

- **Package version(s)**: Fluent UI React 8.23.5
- **Browser and OS versions**: Microsoft Edge 92.0.902.67 (x64, I have already removed all extensions) on Windows 10 19042.1110
- **React Version**: 17.0.2

### Please provide a reproduction of the bug in a codepen:

[Demo on CodePen](https://codepen.io/AkiraVoid/pen/eYWPKvN)

#### Actual behavior:

When specified `canRevealPassword` attribute on a TextField which's type is `password`, an eye icon will be rendered at the end of the component. But if we type something in the block, another eye icon with different style will be displayed. This icon will just be displayed once in one type period, that's to say, this icon won't be shown after the TextField lost focus first time unless we delete all what we typed and re-type. And even we specified `canRevealPassword=false | undefined`, this icon will still be shown, and it just can make password be displayed as plaintext.

Actually, I think this is not a bug of Fluent UI but of browser. I have tested this on FireFox, Chrome, Microsoft Edge and Microsoft Edge for Android, it seems only works on Microsoft Edge. I don't know it's actually a feature or a bug of Edge, and this icon isn't shown when I type my password in other websites which are not using Fluent UI.

#### Expected behavior:

Only one icon should be rendered, and it must have correct behavior.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

- No(Cause I haven't look at the source code of the library).

Requested priority: High

Products/sites affected: [Official docs of Fluent UI](https://developer.microsoft.com/en-US/fluentui#/controls/web/textfield)

**Comment by AkiraVoid** [comment]
![The normal icon](https://user-images.githubusercontent.com/21080720/128523046-62535a6a-bfa3-436e-b17d-cc296417ca64.png)
This is what we should see.
![image](https://user-images.githubusercontent.com/21080720/128523210-4bbca680-0a55-4959-99ff-715f54338b3d.png)
Now we have the icon with strange behavior.

**Comment by ecraig12345** [comment]
Edge has its own reveal password feature, so TextField's custom reveal password feature is supposed to be automatically disabled there. This is done by checking the user agent, but it looks like the check is wrong right now--it should probably be `/\bEdg/` instead of `/^Edg/`.
https://github.com/microsoft/fluentui/blob/ecc79efaeaf9bf8b3164d64eaf3610918c4e8624/packages/react/src/components/TextField/TextField.base.tsx#L650

(The fact that you can find the same icon in Fluent UI icons doesn't really mean anything in this case, it's just because we share the same set of icons across the company.)

**Comment by AkiraVoid** [comment]
But in fact, TextFeild's reveal icon is more useful than Edge's. As I said, Edge's reveal icon only shows at the first time user input or re-focus. Is there anyway to disable Edge's default behavior?

**Comment by ecraig12345** [comment]
I'm not sure if it's possible to disable the built-in behavior. It's kind of debatable what the "right" thing is to do here: use the browser behavior for consistency with what the user may be accustomed to across websites, or use our behavior which is more persistent.

**Comment by AkiraVoid** [comment]
But other websites which are not using fluent ui in Edge don't have this icon in their password inputs. They also use:
```html
<input type="password" />
```
