### ISSUE TITLE
Invalid horizontal gap between Stack children for RTL

### ISSUE THREAD

**Issue by rubo** [microsoft/fluentui#19301]
### Environment Information

- **Package version(s)**: @fluentui/react v8.27.0

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/rubs00/pen/OJgWVgo

#### Actual behavior:

The Stack component sets `childrenGap` on the wrong side in RTL mode. It sets the margin on the left side of the child.

#### Expected behavior:

It should set the margin on the right side of the child for RTL.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

I've seen similar issues already closed but the problem still exists for @fluentui/react and it makes the component virtually unusable for RTL languages.

**Comment by rubo** [comment]
It turned out I need to use `rtl: true` for the `theme` property instead of the `dir` attribute of `ThemeProvider`. Can anyone confirm that's the way to go and where can I read more about it?

**Comment by gouttierre** [comment]
@rubo - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [stack ](https://developer.microsoft.com/en-us/fluentui#/controls/web/stack) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by rubo** [comment]
@gouttierre I updated my initial post with the [link](https://codepen.io/rubs00/pen/OJgWVgo) to repro in CodePen. Please take a look.
In a nutshell, the problem appears with
```javascript
<ThemeProvider dir="rtl">
```
while it's gone with
```javascript
<ThemeProvider theme={mergeThemes(theme, { rtl: true })}>
```
