### ISSUE TITLE
vNext button styling details 

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#19303]
### Environment Information

- **Package version(s)**: https://aka.ms/fluentui-storybook

#### Actual behavior:

![image](https://user-images.githubusercontent.com/48726002/128580622-92f76a68-a783-41f6-93ef-b74dfe99e716.png)

#### Expected behavior:

**1)** 
Font family should be Segoe UI (Base)

@medium size: 
Font size should be 14 (Font size base.300)
Font weight should be Semibold

**2)** 
Icons not using the Fluent icons
https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md

**3)** 
Shadow should be off by default. 
Investigate shadow prop on post beta

Design for reference: https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?node-id=4428%3A13409

**Comment by notandrew** [comment]
Should it be Segoe? (It should probably not be defined here)

**Comment by khmakoto** [comment]
#2 shouldn't be an issue now.
