### ISSUE TITLE
Typing long RTL text in a LTR Text Field doesn't scroll with the text like if you typed LTR text

### ISSUE THREAD

**Issue by makopch-ms** [microsoft/fluentui#19304]
1. go to https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield
2. type a long sentence in English, observe that as you run out of room and continue typing, the text field will scroll with you as you type
3. Now switch your keyboard to an RTL language such as Arabic
4. Type a long string of characters in the text field

#### Actual behavior:

The text box does not scroll as the user runs out of visible space

#### Expected behavior:

Expected the text box does scroll as the user keep typing.

Is it possible to detect if the user is writing in an RTL language and switch on the fly?

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low): Normal
Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
This sounds more likely to be an issue with the browser, not Fluent, since I don't think we have any special handling for scrolling as the user types. @makopch-ms Can you compare the behavior of a built-in `<input type="text"/>` in this scenario? And is it consistent across browsers?
