### ISSUE TITLE
Migrate conformance package to latest react-docgen

### ISSUE THREAD

**Issue by TristanWatanabe** [microsoft/fluentui#19329]
**I'd suggest following action:**
- lets use that temporary yarn resolutions field as a quick fix
- lets keep this issue open to track when it will be resolved in both react-docgen and storybook (then we can update versions - remove resolutions and close this)
- create issue to migrate conformance package to latest react-docgen

_Originally posted by @Hotell in https://github.com/microsoft/fluentui/issues/19292#issuecomment-895057713_

**Comment by ecraig12345** [comment]
react-docgen-typescript 2 depends on typescript 4.3, so this is blocked until we upgrade to 4.3 or there's a fix in the library re-enabling older typescript

**Comment by ecraig12345** [comment]
Will be fixed by #20909
