### ISSUE TITLE
Legends hover card not hides on page scroll 

### ISSUE THREAD

**Issue by scharde** [microsoft/fluentui#19337]
**Checkout this video:**
https://user-images.githubusercontent.com/32043510/113337362-4daad580-9345-11eb-9493-2a2a2e38acec.mp4

### Environment Information

- **Package version(s)**: latest (@react-charting:4.16.5)
- **Browser and OS versions**: Crome/Edge

### codepen :
https://codepen.io/scharde/pen/VwbqBey

#### Actual behavior:

Tooltip is not going away until the scroll stops.

#### Expected behavior:

Tooltip should be going away once the scrolling starts or beyond a limit of scroll.

As observed, onCardHide callback not receiving to legends.base.tsx file from HoverCard.base.tsx on page scroll. 
**Card hide event callback should be provided by HoverCard**

This issue is reference to [existing issue](https://github.com/microsoft/fluentui/issues/17671)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@scharde - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@Raghurk - Would you be able to confirm if this is a regression, or if this behavior is an issue?
