### ISSUE TITLE
Slider snapToStep prop is not working correctly

### ISSUE THREAD

**Issue by Aidam1** [microsoft/fluentui#19358]
### Environment Information

- **Package version(s)**: 8.27.2
- **Browser and OS versions**: Chrome, Win 10

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/agitated-microservice-4i9ig?file=/src/App.tsx

#### Actual behavior:

The snapToStep prop seems to be always turned on. Currently the behavior with this prop turned off is the same as with it turned on.

#### Expected behavior:
When snapToStep is false, it should drag the slider smoothly. It used to work correctly on fluent v7.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

**Comment by gouttierre** [comment]
@Aidam1 - thank you for filing this issue with us.

@smhigley  -  Would you be able to confirm if this is a regression, or if this behavior is an issue with the slider in v8?
