### ISSUE TITLE
Styling system doesn't support React Fast Refresh

### ISSUE THREAD

**Issue by xiluo58** [microsoft/fluentui#19361]
### Environment Information

- **Package version(s)**: (fill this out) @fluentui/react@8.27.2
- **Browser and OS versions**: (fill this out if relevant) 

Browser:
Microsoft Edge
Version 92.0.902.67 (Official build) (64-bit)

OS:
Edition	Windows 10 Enterprise
Version	21H1
Installed on	‎7/‎19/‎2021
OS build	19043.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0

### Please provide a reproduction of the bug in a codepen:
It's a dev experience issue not reproducible on codepen so I created a git repo https://github.com/xiluo58/fluentui-fast-refresh by executing `npx create-react-app my-fluentui-app --template @fluentui/cra-template` and create a component View under src/View,  following https://github.com/microsoft/fluentui/wiki/Component-Styling

Steps to reproduce:
1. Clone the repo
2. run `yarn install`
2. run `yarn start`, wait until the web app is loaded in browser.
3.  remember current color of last line. Open src/View/View.styles.ts, change the color

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) No

**Comment by xiluo58** [comment]
root cause:
https://github.com/microsoft/fluentui/blob/master/packages/utilities/src/styled.tsx#L99
`if (!styles.current || customizedStyles !== cache[1] || props.styles !== cache[2]) {`  
hot reload works if this line is changed to 
`if (!styles.current || baseStyles !== cache[0] || customizedStyles !== cache[1] || props.styles !== cache[2]) {`

In prod baseStyles never changes but in dev it may change

**Comment by gouttierre** [comment]
@xiluo58 - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@bsunderhus -  Would you be able to confirm if this is a regression, or if this behavior is an issue with styling?
