### ISSUE TITLE
'Offline' icon line weight different from other Presence Badges (converged)

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#19388]
### Environment Information
- **Package version(s)**: https://aka.ms/fluentui-storybook

#### Actual behavior:

![image](https://user-images.githubusercontent.com/48726002/129233616-016d990c-ea61-4a7c-8f7e-aa251cbdaa1f.png)

#### Expected behavior:
icon line weight should match
![image](https://user-images.githubusercontent.com/48726002/129234111-0716ca89-5943-4c18-bd1d-3dc857e92a72.png)

might be this icon?
![image](https://user-images.githubusercontent.com/48726002/129234044-ca090c9c-6f1d-4ad3-af70-45e285a21518.png)

**Comment by gouttierre** [comment]
@paulgildea - these are the ones you requested to be logged. I will add this to the beta release project sprint

**Comment by bsunderhus** [comment]
@daisygeng, seems to be fine now on https://aka.ms/fluentui-storybook

![image](https://user-images.githubusercontent.com/5483269/144213823-2708c854-65c6-403d-bc0e-b5062e012d40.png)

**Comment by ling1726** [comment]
Closing since this should be fixed in: #20630

**Comment by daisygeng** [comment]
Thank you!!
