### ISSUE TITLE
Plan for (P1): Generate SASS files for tokens. SASS is needed by various partners (P2)

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#19385]
Generate SASS files for tokens. SASS is needed by various partners

**Comment by JustSlone** [comment]
Needed by partners for their build system (per @levithomason)

For Beta:
- Once we change the theme shape we have a plan for how we'll do this
- And a solution for hashing classnames

Todo: Work with Partners

Token pipeline is not merged to main, blocking this week. 

This is generally valuable for any customer
