### ISSUE TITLE
Update documentation for Beta components

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#19389]
This issue tracks that all components included in beta have had their documentation updated to conform to the standards listed here: https://github.com/microsoft/fluentui/blob/master/rfcs/convergence/authoring-stories.md

- [x] Accordion - #19769
- [ ] Avatar
- [x] Badge - #19571
- [x] Button - #19298
- [ ] CompundButton
- [ ] Divider
- [ ] FluentProvider
- [ ] Icon - #19283
- [ ] Link
- [x] Menu - #19616
- [ ] MenuButton
- [x] Popover - #19634
- [x] Text - #19773
- [ ] ToggleButton
- [ ] Tooltip
- [x] Image - #19687

**Comment by layershifter** [comment]
@behowell is it still a thing? Can be this closed?

**Comment by layershifter** [comment]
As beta was released and there was also done a ton of work on improving docs 👉 closing this.
_We only don't have docs for icons, but it's tracked in the separate issue._

Feel free to reopen if there is need.
