### ISSUE TITLE
Image by default should be shadow off (converged)

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#19391]
### Environment Information
- **Package version(s)**: https://aka.ms/fluentui-storybook

#### Actual behavior:
![image](https://user-images.githubusercontent.com/48726002/129234777-71803119-338b-4ec6-804f-6f8d6fd12556.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/48726002/129235085-d3611e24-f407-489e-b537-ac15273c4e8b.png)

shadow should be an optional prop
![image](https://user-images.githubusercontent.com/48726002/129235164-4ef7e9ae-6533-4f12-bac1-067f80906c77.png)

**Comment by gouttierre** [comment]
@paulgildea - these are the ones you requested to be logged. I will add this to the beta release project sprint
