### ISSUE TITLE
Docs: Introduction of vNext concepts

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#19390]
Topics include:
- [x] Quick Start
- [x] #22358
  * What is a "theme"? (i.e. tokens)
  * Light/Dark/Contrast
  * Applying & switching themes
  * Custom brand color
  * Nested Themes
- [X] Styling
- [x] Slots @GeoffCoxMSFT 
  * why/what are slots?
  * how I can styles slots?
  * how I can customize slots?
- [ ] Component Architecture
  * useComponent
  * useComponentState
  * useComponentStyles
  * useComponentContextValues? (see MenuList)
  * renderComponent
- [ ] Accessible by default

Learn More:
- [ ] Benefits of vNext
- [ ] Why vNext instead of incremental update to Fabric or Northstar
- [ ] Describe naming, vNext/Converged/Fluent/etc.

-------- 

How do I:

- [ ] Extend/compose an existing component?
- [ ] Create my own Theme?
- [ ] Layout my components using CSS since `Stack` is not part of v9?

-------- 

Migration

- [ ] How do I do X in vNext when I used to do Y in v0/v7/v8
  * Theme overrides
  * names of components
  * etc

--------

Contributing

- [ ] How do I build a Fluent vNext Component?

Does anyone have any more?

**Comment by GeoffCoxMSFT** [comment]
I think we can close this as we shipped v9.
