### ISSUE TITLE
[web-components] Radio: label height is larger than slotted components

### ISSUE THREAD

**Issue by SethDonohue** [microsoft/fluentui#19396]
### Environment Information

- **Package version(s)**: 2.5.7
- **Browser and OS versions**: Edge and Chrome

### Please provide a reproduction of the bug in a codepen:
Stackblitz:
https://typescript-zws6h6.stackblitz.io

*Inspect the heights of the labels and overall component in the repro*

#### Actual behavior:
The Radio's *Label* seems to add extra height to the Radio component when something other than text is slotted into the default slot of Radio, causing the Radio to be slightly larger than its children actually are. This can add unnecessary height  to components that use Radio.

Here is the current behavior with the *label* having `display: block`:
<img width="210" alt="Screen Shot 2021-08-12 at 4 20 17 PM" src="https://user-images.githubusercontent.com/31681651/129282197-a1c4f805-7d33-4a99-8011-c63ddaaef1dd.png">

Current Fluent Radio:
<img width="256" alt="Screen Shot 2021-08-12 at 4 23 58 PM" src="https://user-images.githubusercontent.com/31681651/129282379-ca74a97c-3d6c-476a-ac76-35ad1cf158f2.png">

#### Expected behavior:
The *label* of Radio should only be as tall as its slotted content.

Here is the proposed/expected style with the *label* having `display: inline-flex` or `display: flex`:
<img width="210" alt="Screen Shot 2021-08-12 at 4 19 51 PM" src="https://user-images.githubusercontent.com/31681651/129282219-662b08d4-8002-40d7-bb8b-1097093a2c4b.png">

Proposed/Expected Fluent Radio:
<img width="256" alt="Screen Shot 2021-08-12 at 4 24 11 PM" src="https://user-images.githubusercontent.com/31681651/129282365-c368ab2d-431e-49ab-bd34-18a3be152589.png">

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/sites affected: (if applicable)

**Comment by chrisdholt** [comment]
@SethDonohue go ahead and pick this up when you can :)
