### ISSUE TITLE
Label should not include a background color (converged)

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#19392]
### Environment Information
- **Package version(s)**: https://aka.ms/fluentui-storybook

#### Actual behavior:
![image](https://user-images.githubusercontent.com/48726002/129235503-b36d925f-f8c9-44df-8111-e7e52a9e0471.png)

#### Expected behavior:
Does the label actually include the grey background here? I was expecting the label background to be transparent so then we can use this across various background colors (grey and white)
 
![image](https://user-images.githubusercontent.com/48726002/129235956-f2c10692-3fc2-4036-b1ee-5775393a4490.png)

**Comment by gouttierre** [comment]
@paulgildea - these are the ones you requested to be logged. I will add this to the beta release project sprint

**Comment by bsunderhus** [comment]
@daisygeng, seems to be fine now on https://aka.ms/fluentui-storybook

![image](https://user-images.githubusercontent.com/5483269/144215436-b86619d5-54bb-422e-930d-9edc61051abd.png)
