### ISSUE TITLE
makeStyles: expansion of shorthands does not work sometimes

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#19402]
### Intro

> When using a library that generates Atomic CSS such as Fela or Styletron, one can run into an issue where mixed shorthand and longhand properties are applied in an unexpected way due to the rendering order of CSS classes.
>
> This packages helps to prevent those issues by always expanding shorthand values so that no conflicts occur at all.
>
> https://github.com/robinweser/inline-style-expand-shorthand

As `makeStyles()` also uses Atomic CSS we have the same problem and we are using the same package to expand shorthands:

```tsx
import { expandProperty } from "inline-style-expand-shorthand";

const longhands = expandProperty("padding", "10px 15px 5px");

// longhands === output
const output = {
  paddingTop: "10px",
  paddingRight: "15px",
  paddingBottom: "5px",
  paddingLeft: "15px"
};
```

### Problem

It was not a big problem in Fluent N\* as we don't use there CSS variables, with `makeStyles()` we have a problem there.

#### CSS variables cannot be expanded

There are cases when CSS variables cannot be expanded, for example `background`:

```js
// Input:
const input = { padding: "var(--foo)" };
// Output
const output = {
  paddingTop: "var(--foo)",
  paddingRight: "var(--foo)",
  paddingBottom: "var(--foo)",
  paddingLeft: "var(--foo)"
};
```

This behavior is questionable as `-foo` can have different values:

```css
--foo: 5px; /* can be expanded */
--foo: 5px 10px; /* cannot be expanded */
```

https://codesandbox.io/s/dank-hooks-r7jmr?file=/src/App.js

#### Not all shorthands are expanded

A list of shorthands supported by [`inline-style-expand-shorthand`](https://github.com/robinweser/inline-style-expand-shorthand) is very limited.

[Complete list of shorthands based on MDN data](https://csstree.github.io/docs/syntax/#report&noedit&title=CSS%20shorthand%20properties%20by%20MDN%20data&q=JGlzQXJyYXk6ID0%2BICQgIT0gKCQgKyAnJyk7Cm1kbi5wcm9wZXJ0aWVzLmVudHJpZXMoKS4oeyBpZHgsIG5hbWU6IGtleSwgLi4uKHZhbHVlIHwgeyBjb21wdXRlZCwgc3ludGF4IH0pIH0pLltjb21wdXRlZC4kaXNBcnJheSgpXQ%3D%3D&v=ewogICAgdmlldzogJ3RhYmxlJywKICAgIGNvbHM6IHsKICAgICAgICBpZHg6ICd0ZXh0OiMuaW5kZXggKyAxJywKICAgICAgICBjb21wdXRlZDogewogICAgICAgICAgICBoZWFkZXI6ICdwcm9wcycsCiAgICAgICAgICAgIGNvbnRlbnQ6ICd1bDpjb21wdXRlZCcKICAgICAgICB9CiAgICB9LAogICAgbGltaXQ6IGZhbHNlCn0%3D)

For example, `background` is not supported (https://github.com/robinweser/inline-style-expand-shorthand/issues/5):

```js
// Input
const input = { background: "var(--foo)" };
// Output
const output = { background: "var(--foo)" };
```

https://codesandbox.io/s/silent-flower-txe4u?file=/src/App.js

#### Some shorthands are not properly expanded

For example, `flex`, see https://github.com/robinweser/inline-style-expand-shorthand/issues/14.

**Comment by bsunderhus** [comment]
This issue should be solve by https://github.com/microsoft/fluentui/pull/20573 RFC, Next steps is implementing the RFC
