### ISSUE TITLE
PreventDismissOnEvent Does Not Fire in v8

### ISSUE THREAD

**Issue by tabrumle** [microsoft/fluentui#19407]
### Environment Information

- **Package version(s)**: v8

### Please provide a reproduction of the bug in a codepen:

[v7 where it works](https://codepen.io/The_Golden_Goose/pen/bGWyEbQ)
[v8 where it doesn't work](https://codepen.io/The_Golden_Goose/pen/PomvZYa)

#### Actual behavior:

We don't fire off the preventDismissOnEvent handler

#### Expected behavior:

We fire off the preventDismissOnEvent handler

**Comment by ecraig12345** [comment]
I think this may have been fixed by a recent PR. Can you check again?

**Comment by tabrumle** [comment]
This is fixed. Thank you!
