### ISSUE TITLE
Icon: The ContentSettings Icon is missing

### ISSUE THREAD

**Issue by dcowen91** [microsoft/fluentui#19411]
### Environment Information

- **Package version(s)**: latest 8.28.2
- **Browser and OS versions**: Edge and chrome latest

### Please provide a reproduction of the bug in a codepen:
The fluent Icon "ContentSettings" is not registered in the @fluentui/react package.
https://uifabricicons.azurewebsites.net/
![image](https://user-images.githubusercontent.com/6540263/129634109-35db58e1-de36-426d-a9f1-45389536b4a1.png)
https://codepen.io/dcowen/pen/PomvWyE

#### Actual behavior:

"The icon 'contentsettings' was used but not registered. See https://github.com/microsoft/fluentui/wiki/Using-icons for more information."

#### Expected behavior:

The icon is rendered

### Priorities and help requested:

Are you willing to submit a PR to fix?
No
Requested priority:
Normal
Products/sites affected:

**Comment by gouttierre** [comment]
@dcowen91 - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@bsunderhus -  Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by edemen** [comment]
I am experiencing the same problem with icon 'CloudEdit'
