### ISSUE TITLE
[Accessibility] [Talkback]: Talkback reads 'disabled' after every date

### ISSUE THREAD

**Issue by ankeshanku** [microsoft/fluentui#19430]
### Environment Information

- **Package version(s)**: FluentUI 7.** and FluentUI 8.**
- **Browser and OS versions**: Chrome, Android 11

### Please provide a reproduction of the issue in a codepen:

1. Go to [FluentUI Calendar](https://developer.microsoft.com/en-us/fluentui#/controls/web/calendar) or any Calender codepen exports.
2. Turn talkback on.
3. Move to any date field of the calendar (say, 18/08/2021).
4. Notice talkback reads 'disabled' after 18 August 2021 and before Wednesday.
Complete sentence used 
    > 18 August 2021 disabled wednesday

#### Expected behavior:

Talkback should read 'disabled' only for those dates which are disabled from selection (like days outOfBounds, disabled weekends)

**Comment by gouttierre** [comment]
@ankeshanku - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@bsunderhus -  Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley
