### ISSUE TITLE
Bug: First list item gets hidden under header when an spfx extension is loaded.

### ISSUE THREAD

**Issue by vincepunkrock** [microsoft/fluentui#19435]
### Environment Information

- **Package version(s)**: 8.26.2
- **Browser and OS versions**: 
- I tested multiple browsers and the problem happens on all of them
    - Chrome 92.0.4515.131
    - Brave Version 1.28.105 Chromium: 92.0.4515.131
    - Firefox 90.0.2
    - Edge Version 92.0.902.73

#### Actual behavior:
The first item of the list gets hidden by the header. It happens when an SPFX extension is installed. Or as soon as it is loaded in debug mode using gulp serve. Note the the list is not scrolled. The first item simply gets hidden by the header.

![image](https://user-images.githubusercontent.com/9620524/129908373-8d509a41-2512-447d-bafb-669e4b82bc24.png)

#### Expected behavior:

The list is displayed correctly when the spfx is not installed (or not loaded in debug mode).

![image](https://user-images.githubusercontent.com/9620524/129908763-dc86a1e5-fc9c-45b8-8bd8-ed9d4735393f.png)

I couldn't find any other issue mentioning this. 
It's quite blocking.

**Comment by vincepunkrock** [comment]
If it can help resolution: the problem goes away if I manually remove the set height
![image](https://user-images.githubusercontent.com/9620524/130820726-2c40506b-2b1c-4be8-8adb-fb0c0351ae20.png)

**Comment by ecraig12345** [comment]
This looks like an issue with SharePoint components, not anything in Fluent UI itself. So unfortunately we can't help with that here.
