### ISSUE TITLE
[TextField] in ipad, the behavior of three period is the same as the behavior of one period. 

### ISSUE THREAD

**Issue by yxl64** [microsoft/fluentui#19447]
### Environment Information

- **Package version(s)**: 8.14.0
- **Browser and OS versions**: 14.6

### Please provide a reproduction of the bug in a codepen:
it exist in fluent UI web. When open https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield in ipad, select one TextField, input three period, and then delete one period, then all the three period will be deleted. 
This is the video in my ipad:
https://msit.microsoftstream.com/video/4db40840-98dc-981d-a4fd-f1ec00bce7b5?list=studio

#### Actual behavior:
all the three period are deleted when delete one period

#### Expected behavior:
one period should be deleted, rather than all the three period

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
in our product, only one period is allowed, more than one period are not allowed, we use RegEx to check it. 
But when user input three period in the TextField, it should not be allowed, but the string is handled as one period, then it pass our RegEx. It causes some problem for us.

**Comment by ecraig12345** [comment]
This is a built-in behavior of iOS and not something that we're going to build in code to modify, especially because preventing entry of multiple periods isn't desirable in all circumstances. 

If you want to do this in your own code, you can use a controlled TextField like this: https://codepen.io/ecraig12345/pen/rNwLywV?editors=0010
