### ISSUE TITLE
Spinner does not respond to Large Text changes

### ISSUE THREAD

**Issue by daneuber** [microsoft/fluentui#19446]
### Environment Information

- **Package version(s)**: any
- **Browser and OS versions**: any

### Describe the issue:

When users change font size via browser appearance settings to increase size for accessibility reasons, the Spinner does not change.

### Please provide a reproduction of the issue in a codepen:

1. Open a page with the Spinner control loaded. For repro purposes I'll describe using Edge Chromium.
2. Go to browser settings > Appearance > Fonts section and increase font size
3. Flip back to the Spinner. Notice no change

#### Actual behavior:

Spinner does not respond to font size changes; accessibility issue

#### Expected behavior:

Spinner should use rem instead of px and adjust to user font size changes so users can see loading status

**Comment by gouttierre** [comment]
@daneuber - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@bsunderhus -  Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley
