### ISSUE TITLE
Initials is not align with other Microsoft Products

### ISSUE THREAD

**Issue by qianghuang94** [microsoft/fluentui#19460]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/qihuang01/pen/VwboMvQ

![image](https://user-images.githubusercontent.com/15025186/130168732-c9938863-1367-4915-9fef-dca1562c7b0d.png)

Customer complains about this two initials is not generated correct, especially they are different from other Microsoft Products.
![image](https://user-images.githubusercontent.com/15025186/130168822-bdd1bbec-2f41-423f-bb60-4283027246a4.png)

#### Actual behavior:
Dr. TestFirst Last => DT

#### Expected behavior:
Dr. TestFirst Last => TL

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: Normal

Products/sites affected: SharePoint

**Comment by gouttierre** [comment]
@qianghuang94 - thanks for filing this issue with us. I see your point to your issue. 

@smhigley -  Would you be able to confirm if this is a regression, or if this behavior is an issue with setting the initials?

**Comment by smhigley** [comment]
It looks like our auto-generated initials always take the first letter of the first word and the first letter of the last one, and it doesn't do anything particular around names with commas or titles. Based on the specific examples here, we probably need to check for commas or pipes and split + reverse the array, and then also check for a period after the first word and discard the title. To be thorough, we could also reach out to the other team managing initial generation and see if we can make our logic exactly match theirs.

@qianghuang94 as a workaround, the `imageInitials` prop will allow you to implement your own name-to-initials logic and specify exactly what initials you want displayed for any given persona.
