### ISSUE TITLE
@fluentui/react-icons-mdl2 forcing icons to be max 1rem by inserting a class to override user classes

### ISSUE THREAD

**Issue by fergusmeiklejohn** [microsoft/fluentui#19463]
### Environment Information

- **Package version(s)**: @fluentui/react-icons-mdl2 1.1.8

#### Actual behavior:

I'm using Tailwind CSS with fluentui icons. No matter what classes I add to the icon component, it seems to generate it's own class which limits size to 1rem. Is this expected behaviour?

```
.root_0ceaf432 {
	display: inline-block;
	vertical-align: middle;
	speak: none;
	width: 1em;
	height: 1em;
}
```

#### Expected behavior:

I don't expect the icon component to insert size classes, I expect to control that myself

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: (if applicable)

**Comment by alina-zaieva** [comment]
Encountered the same problem, as a workaround you can set size via font size in your class instead of width/height as `em` depends on font size property.

**Comment by fergusmeiklejohn** [comment]
I can also solve this by marking my css width and height as !important

**Comment by gouttierre** [comment]
@fergusmeiklejohn - Thanks for reaching out to us. I’ve added this to our backlog for review but it’s low on our priority list - especially since you all have shared a work around in the interim which is greatly appreciated!
