### ISSUE TITLE
fluentui/react-northstar server side rendering question

### ISSUE THREAD

**Issue by cubesky** [microsoft/fluentui#19476]
Hello, I just using `@fluentui/react-northstar` with `gatsby` ssr feature.

I following this [wiki](https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing) to setup ssr with `gatsby-ssr.js`.

But using 

```javascript
import { renderStatic } from '@fluentui/merge-styles/lib/server'
```

or 

```javascript
import { renderStatic } from '@uifabric/merge-styles/lib/server'
```

can not generate css.

```javascript
const { html, css } = renderStatic(() => {
    return renderToString(bodyComponent)
}, 'server')
```

returns css with empty string. How can I use `@fluentui/react-northstar` with SSR?

It works great in real-time render mode with `gatsby develop`, but server side rendering with `gatsby build` can not generate css.

* `@fluentui/react-northstar` `^0.57.0`
* `@uifabric/merge-styles` `7.19.2`
* `@uifabric/utilities` `7.32.3`
* `gatsby` `^3.11.1`

Thanks.

---

gatsby-ssr.js

```javascript
import React from 'react'
import { renderStatic } from "@uifabric/merge-styles/lib/server"
// import { renderStatic } from "@fluentui/merge-styles/lib/server"
import { renderToString } from "react-dom/server"

export const replaceRenderer = ({
  bodyComponent,
  replaceBodyHTMLString,
  setHeadComponents,
}) => {
  
  const { html, css } = renderStatic(() => {
    return renderToString(bodyComponent)
  }, 'server')
  
  replaceBodyHTMLString(html)

  setHeadComponents([<style dangerouslySetInnerHTML={{ __html: css }} />])
}
```

**Comment by cubesky** [comment]
I found that `@fluentui/react-northstar` seens to use `react-flex`, but I can not find where is style rules of northstar.

**Comment by gouttierre** [comment]
@jurokapsiar - would your team be able to assist here? Thanks

**Comment by cubesky** [comment]
Hi, I create a repository to reproduce this issue. 

[fluentui-northstar-issue-19476](https://github.com/cubesky/fluentui-northstar-issue-19476)

Clone it and run `yarn install` to install dependeny.

Run Gatsby in develop mode `yarn run develop` and open `http://localhost:8000`. Everything is correct.

Run Gatsby after build, `yarn run build` and `yarn run serve` and open `http://localhost:9000`. You can see `<style class="ssr-css">` tag in `<head>` is empty. This tag is filled by `gatsby-ssr.js`.

**Comment by cubesky** [comment]
`yarn run develop`
![image](https://user-images.githubusercontent.com/8038511/130527712-0de45f26-7b30-43a1-82b7-da0a0661a0c0.png)


`yarn run build` and then `yarn run serve`

![image](https://user-images.githubusercontent.com/8038511/130527678-3d110def-f679-4cd6-8389-53b32b1eb2e1.png)

**Comment by cubesky** [comment]
It seems `fela` is used by `@fluentui/react-northstar`, wiki only contains document for `@fluentui/react`.

I try to use [Fela offical server side renderer config](https://fela.js.org/docs/latest/advanced/server-rendering), but it need css rules.

I found this image for northstar how to merge styles.

![](https://fabricweb.azureedge.net/fabric-website/assets/images/merge-themes.png)

on fluentui northstar document [debugging](https://fluentsite.z22.web.core.windows.net/0.57.0/debugging) page.

I try to use `createFelaRenderer` from `@fluentui/react-northstar-fela-renderer` to create fela renderer context, and then I found it returns a custom object without fela renderer itself, this object contains `renderRules` and `renderFonts`, but it need rules in ICSSInJS type, I can not find a way to get this CSSInJS component. 

Use `fela` method `renderToStatic` can also successfully render html, but using `renderToMarkup` is empty too. 

Is there any document for `@fluentui/react-northstar` to do SSR render? Everything in wiki is for `@fluentui/react` version 7 and 8, not for northstar. @gouttierre  @jurokapsiar

**Comment by cubesky** [comment]
I only found an issue #13925 to talk about SSR render for northstar.And it Soft Closed by Bot without any solution. Is there any update for this?

**Comment by LeonYasoon** [comment]
Hey @cubesky, i managed to get SSR with react-northstar working by patching the react-northstar-fela-renderer and react-northstar packages. 

northstar patch:
`diff --git a/node_modules/@fluentui/react-northstar/dist/commonjs/utils/index.js b/node_modules/@fluentui/react-northstar/dist/commonjs/utils/index.js
index 10b0a47..e06c8f0 100644
--- a/node_modules/@fluentui/react-northstar/dist/commonjs/utils/index.js
+++ b/node_modules/@fluentui/react-northstar/dist/commonjs/utils/index.js
@@ -51,6 +51,7 @@ Object.keys(_factories).forEach(function (key) {
 var _mergeProviderContexts = require("./mergeProviderContexts");
 
 exports.mergeProviderContexts = _mergeProviderContexts.mergeProviderContexts;
+exports.getFelaRenderer = _mergeProviderContexts.getRenderer;
 
 var _renderComponent = require("./renderComponent");
 
`

Fela renderer patch: 
`diff --git a/node_modules/@fluentui/react-northstar-fela-renderer/dist/commonjs/createFelaRenderer.js b/node_modules/@fluentui/react-northstar-fela-renderer/dist/commonjs/createFelaRenderer.js
index ecfc952..08736d0 100644
--- a/node_modules/@fluentui/react-northstar-fela-renderer/dist/commonjs/createFelaRenderer.js
+++ b/node_modules/@fluentui/react-northstar-fela-renderer/dist/commonjs/createFelaRenderer.js
@@ -119,10 +119,6 @@ var createFelaRenderer = function createFelaRenderer(target) {
     },
     // getOriginalRenderer() is implemented only for tests to be compatible with jest-react-fela expectations.
     getOriginalRenderer: function getOriginalRenderer() {
-      if (process.env.NODE_ENV !== 'test') {
-        throw new Error('This method implements private API and can be used only in tests');
-      }
-
       return felaRenderer;
     },
     Provider: Provider
diff --git a/node_modules/@fluentui/react-northstar-fela-renderer/dist/es/createFelaRenderer.js b/node_modules/@fluentui/react-northstar-fela-renderer/dist/es/createFelaRenderer.js
index ad47f52..4df0726 100644
--- a/node_modules/@fluentui/react-northstar-fela-renderer/dist/es/createFelaRenderer.js
+++ b/node_modules/@fluentui/react-northstar-fela-renderer/dist/es/createFelaRenderer.js
@@ -93,10 +93,6 @@ export var createFelaRenderer = function createFelaRenderer(target) {
     },
     // getOriginalRenderer() is implemented only for tests to be compatible with jest-react-fela expectations.
     getOriginalRenderer: function getOriginalRenderer() {
-      if (process.env.NODE_ENV !== 'test') {
-        throw new Error('This method implements private API and can be used only in tests');
-      }
-
       return felaRenderer;
     },
     Provider: Provider
`

Afterwards i just served the SSR'd northstar components like this:

`
        import { getFelaRenderer } from '@fluentui/react-northstar';   // You need to ts-ignore the import or fix it in a patch (index.d.ts)
        ...
        const html = ReactDOMServer.renderToString(React.createElement(ChatComponent));
        const renderer = getFelaRenderer();
        const originalRenderer = renderer.getOriginalRenderer();
        const markup = renderToMarkup(originalRenderer);

        return (
            `<!DOCTYPE html>` +
            `<html>` +
            `<head>` +
            `<title>Server side rendering test</title>` +
            `<style>${markup}</style>` +
            `</head>` +
            `<body>` +
            `<div id='ssr'>${html}</div>` +
            `</body></html>`
        );
`

**Comment by cubesky** [comment]
@LeonYasoon 
I'm so happy to see there is a solution for fluentui/northstar work with SSR. This solution need to apply patch every time when using CI.

**Comment by iammathew** [comment]
Seeing an official guide on how to do SSR for Northstar would really help :)
Especially with the rise of Next.js and Remix, I feel this is needed.

**Comment by marwan38** [comment]
@LeonYasoon I got it working using your method, although, I'm not sure of any repercussions of this. Seems like it should be ok.

If the devs can give some guidance on whether or not that solution should be implemented OR a new renderer is put into place; I could help write up a PR for it. @gouttierre @jurokapsiar.

**Comment by marwan38** [comment]
Update:

I've further modified the patch to also include body styles during SSR. Previously, the body styles were not being registered into the renderer, so they would only get applied after hydration. The patch is in this gist. Hopefully I can get the time to make a PR that I may perhaps get the attention of the devs. 

[Gist for the patches](https://gist.github.com/marwan38/3843fe60cd1be4b5585d11932daf62cf)

@LeonYasoon FYI.
