### ISSUE TITLE
Ensures elements with an ARIA role that require child roles contain them.

### ISSUE THREAD

**Issue by huangzumeihan** [microsoft/fluentui#19494]
https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown

Actual Result:
Elements with an ARIA role not contain require child roles.

Expected Result:
Ensures elements with an ARIA role that require child roles contain them.

![image](https://user-images.githubusercontent.com/31198399/130566614-d4a225f6-ff1c-426e-a1e4-bd6440501920.png)
![image](https://user-images.githubusercontent.com/31198399/130566601-d0d04ec3-9fa7-4fb2-960b-198615da4cf5.png)

**Comment by gouttierre** [comment]
@huangzumeihan  - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@bsunderhus -  Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley

**Comment by smhigley** [comment]
This was a long-standing false positive in accessibility insights that has now actually been fixed. In the latest version of accessibility insights (v2.28, using axe-core 4.3.2), you can see the errors no longer show up.
