### ISSUE TITLE
Keyboard focus doesn't land on the selected tab item after selecting the tab controls in more tab flyout

### ISSUE THREAD

**Issue by huangzumeihan** [microsoft/fluentui#19493]
https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot

Actual Result:
Keyboard focus does not land on the Selected tab item after selecting from the more tabs button flyout. Focus remains on the 'more tabs' flyout controls.

Expected Result:
When user select tab item from more tabs' flyout, keyboard focus should land on the selected tab item which is expected focused control.

![image](https://user-images.githubusercontent.com/31198399/130564907-33ac707b-b925-457f-93c9-0411c168e10e.png)
![image](https://user-images.githubusercontent.com/31198399/130564942-5386ca3e-a0a6-4520-8ebe-7e23d4aaa06a.png)

**Comment by gouttierre** [comment]
@huangzumeihan  - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@bsunderhus -  Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley
