### ISSUE TITLE
async.requestAnimationFrame() in ResizeGroup.base.tsx doesn't pass in element object

### ISSUE THREAD

**Issue by JiuqingSong** [microsoft/fluentui#19508]
See here: https://github.com/microsoft/fluentui/blob/e6ee3ff194c59ee27e853387fad06f161e63652c/packages/react/src/components/ResizeGroup/ResizeGroup.base.tsx#L402

According the definition of Async.requestAnimationFrame(), there should be a 2nd parameter to specify an element in the window so that it can use the correct window to call requestAnimationFrame(). However, here the 2nd parameter is missed. That causes when we render a CommandingBar in a projection popout window which is already maximized, the main window won't trigger any animation frame, so that the callback of Async.requestAnimationFrame() won't trigger. Finally the commanding bar is not visible.

We see this issue in OWA, and I have tried with a local change in ResizeGroup.base.js to make it work:

```javascript
    React.useEffect(function () {
        async.requestAnimationFrame(function () {

console.log('[MYDEBUG] requestAnimationFrame');

            var containerDimension = undefined;
            if (stateRef.current.measureContainer && rootRef.current) {
                var boundingRect = rootRef.current.getBoundingClientRect();
                containerDimension =
                    props.direction === ResizeGroupDirection.vertical ? boundingRect.height : boundingRect.width;
            }
            var nextState = nextResizeGroupStateProvider.getNextState(props, stateRef.current, function () {
                var refToMeasure = !hasRenderedContent.current ? initialHiddenDiv : updateHiddenDiv;
                if (!refToMeasure.current) {
                    return 0;
                }
                return props.direction === ResizeGroupDirection.vertical
                    ? refToMeasure.current.scrollHeight
                    : refToMeasure.current.scrollWidth;
            }, containerDimension);
            updateResizeState(nextState);
        }, rootRef.current);  // !!!!Here is my change!!!!
    });
```

**Comment by gouttierre** [comment]
@JiuqingSong  - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@bsunderhus -  Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by JiuqingSong** [comment]
Thanks @gouttierre 
This issue causes a bug in OWA that the commanding bar won't show in a special scenario. I have tried to make the change locally as I described above and it can fix the bug.

**Comment by romanisa** [comment]
@bsunderhus I wanted to check on the status of the PR for this issue. Is there an ETA when the PR will be committed and the fix will be available? OWA has an issue as described above and it is impacted users WW.
