### ISSUE TITLE
Chart

### ISSUE THREAD

**Issue by RasheshJagad** [microsoft/fluentui#19510]
#### Describe the feature that you would like added

Couple of Chart like Bar Chart, Pie Chart etc.

#### What component or utility would this be added to

This will help in displaying the graphical representation of the summery, and help developers to show graphical view without Powerbi

#### Have you discussed this feature with our team, and if so, who

No

**Comment by ecraig12345** [comment]
This already exists under `@fluentui/react-charting`. You can see a demo here: https://fluentuipr.z22.web.core.windows.net/heads/master/react-charting/demo/index.html

Also in the future, please be a bit more detailed in the issue title so it's easier us to triage and more helpful to others looking through issues in the future.
