### ISSUE TITLE
Provide X-Axis and Y axis labels to LineChart.

### ISSUE THREAD

**Issue by Utsav37** [microsoft/fluentui#19516]
#### Describe the feature that you would like added
Provide X-Axis and Y axis labels to LineChart.

#### What component or utility would this be added to

LineChart

#### Have you discussed this feature with our team, and if so, who

No one

#### Additional context/screenshots

Just a basic feature where we can provide lables to x-axis and y-axis.
![image](https://user-images.githubusercontent.com/25278093/130768119-524e65ed-b865-477c-bd84-e65a8a18e633.png)

**Comment by gouttierre** [comment]
@Utsav37 - thanks for filing this issue with us.

@Raghurk - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by Utsav37** [comment]
@ecraig12345  @Raghurk  @smhigley  Will there be any update on this? I think this should be a pretty basic feature for any chart. (To label X and Y Axis)

**Comment by AtishayMsft** [comment]
X and Y axis labels have been added in version [5.17.0](https://github.com/microsoft/fluentui/tree/@fluentui/react-charting_v5.17.0) of the charting library.
