### ISSUE TITLE
DetailsList - With SelectionMode.multiple, Clicking row text selects single item

### ISSUE THREAD

**Issue by Marjinas** [microsoft/fluentui#19511]
<!--
### Environment Information

Package version(s): 7.19.0

### Describe the issue:

With SelectionMode.multiple, Clicking row text selects single item where as onclick on checkboxes it selects multiple items.

This is verified all examples of Detailed list.

https://fabricweb.z5.web.core.windows.net/oufr/7.19.1/#/examples/detailslist/basic

#### Actual behavior:

https://fabricweb.z5.web.core.windows.net/oufr/7.19.1/#/examples/detailslist/basic

#### Expected behavior:

On click of Row text, Multiple selection should be applicable.

**Comment by gouttierre** [comment]
@Marjinas - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [DetailsList ](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/detailslist) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
