### ISSUE TITLE
Datepicker: Exposing former isDatePickerShown state through ComponentRef (IDatePickerProps)

### ISSUE THREAD

**Issue by mlp73** [microsoft/fluentui#19512]
#### Describe the feature that you would like added
After upgrading to v8 and the major change from class-components to functional-components, we are having issue reimplementing a feature that we used to make possible through accessing class components state.
That feature was based on knowing wether the Datepicker is shown or not, that we previously got by accessing state.isDatePickerShown using componentRef)
Is there any suggested workaround for now? If not, could you consider exposing that state?

As documented in the migration guide:
https://github-wiki-see.page/m/microsoft/fluentui/wiki/Version-8-migration-guide#function-component-conversions
"If you need a former state property which is not included in the relevant IComponentName interface, please file an issue and we can consider adding it."

#### What component or utility would this be added to
Datepicker
interfaces IDatePicker / IDatePickerProps

#### Have you discussed this feature with our team, and if so, who
No.

#### Additional context/screenshots

export interface IDatePickerProps extends IBaseProps<IDatePicker>, React.HTMLAttributes<HTMLElement>, React.RefAttributes<HTMLDivElement> {
    /**
     * Optional callback to access the IDatePicker interface. Use this instead of ref for accessing
     * the public methods and properties of the component.
     */
    componentRef?: IRefObject<IDatePicker>;

    ...
    }
    
    /**
 * {@docCategory DatePicker}
 */
export interface IDatePicker {
    /** Sets focus to the text field */
    focus(): void;
    /** Reset the state of the picker to the default */
    reset(): void;
    /** Open the datepicker callout */
    showDatePickerPopup(): void;
   // Would that make sense to expose that state here?
}

**Comment by gouttierre** [comment]
@mlp73 - I’ve added this to our backlog for review but it’s not high on our priority list therefore we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. 

cc @GeoffCoxMSFT
