### ISSUE TITLE
Providing shouldFocusOnContainer to the BaseButton menuProps has no effect

### ISSUE THREAD

**Issue by jacksonv1lle** [microsoft/fluentui#19529]
### Environment Information

- **Package version(s)**: All
- **Browser and OS versions**: All

### Describe the issue:

When you provide `menuProps` to the `BaseButton` component with the `shouldFocusOnContainer` set to `false`. The value is ignored.

Looking at the `_onMenuClick` function in the `BaseButton.tsx` file, I can see that the value is defined as follows:

    const shouldFocusOnContainer =
        ev.nativeEvent.detail !== 0 || (ev.nativeEvent as PointerEvent).pointerType === 'mouse';

#### Actual behavior:

Providing `shouldFocusOnContainer: false` to the BaseButton menuProps has no effect and the menu container will receive focus regardless

#### Expected behavior:

The menu container should not receive focus if the provided property for `shouldFocusOnContainer` is set to `false`

#### Codepen Example:
[Codepen](https://codepen.io/ijackson/pen/VwWLwgG?editors=0010)

**Comment by gouttierre** [comment]
@jacksonv1lle - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@bsunderhus -  Would you be able to confirm if this is a regression, or if this behavior is an issue?
