### ISSUE TITLE
Fluent ui Northstart dropdown Add a loader.

### ISSUE THREAD

**Issue by UmamaheshwariGolla** [microsoft/fluentui#19520]
Fluent ui Nortstar dropdown how to add a spinner 

`<Dropdown
    items={inputItems}
    loading={true}
    loadingMessage="loading the data"
    placeholder="Select your hero"
    checkable
    getA11ySelectionMessage={{
      onAdd: item => `${item} has been selected.`,
    }}
  />`

requirement is to add a spinner is it possible to add

**Comment by gouttierre** [comment]
@UmamaheshwariGolla - thank you for filing this issue with us. 

@jurokapsiar -  Would your team be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by jurokapsiar** [comment]
Please check https://codesandbox.io/s/myjuw?module=/example.js
