### ISSUE TITLE
Why persona's defaultRender is undefined

### ISSUE THREAD

**Issue by IProbably** [microsoft/fluentui#19530]
![image](https://user-images.githubusercontent.com/42802184/130934059-16e0846d-71e5-4309-aa99-e41080f82adb.png)

**Comment by gouttierre** [comment]
@IProbably - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [Persona ](https://developer.microsoft.com/en-us/fluentui#/controls/web/persona) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by IProbably** [comment]
https://codepen.io/iprobably/pen/LYLxLzJ?editors=0010
