### ISSUE TITLE
On activating text spacing on DetailsList, the checkbox gets disoriented.

### ISSUE THREAD

**Issue by yupasz** [microsoft/fluentui#19531]
### Environment Information

- **Package version(s)**: Fluent UI React 8.29.2
- **Browser and OS versions**:
  Environment : Edge + Narrator.​
  OS: Window 10
  OS version: 2004
  Build version: 19640.1
  Microsoft Edge (Anaheim) Version 85.0.531.1 (Official build) dev (64-bit)
### Describe the issue:

On activating text spacing on DetailsList, the checkbox gets disoriented.

### Please provide a reproduction of the issue in a codepen:
https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/detailslist/basic

#### Actual behavior:

![image](https://user-images.githubusercontent.com/69033452/130933370-753e21a4-e3a0-494b-a933-edc2523eeeb2.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/69033452/130933806-8066815d-002e-4d97-b6b8-ad8f8ca91119.png)

### Documentation describing expected behavior
https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html

**Comment by gouttierre** [comment]
@yupasz - Thanks for filing this issue. However, I am unable to repro your problem. Please can you retest and confirm the problem persists? Thank you

**Comment by yupasz** [comment]
To enable text spacing:
1. Save this script as a bookmark: `javascript:(function(){var d=document,s=d.createElement(%27style%27);s.appendChild(d.createTextNode(%27* { line-height: 1.5 !important; letter-spacing: 0.12em !important; word-spacing: 0.16em !important; } p{ margin-bottom: 2em !important; }%27));d.getElementsByTagName(%27head%27)[0].appendChild(s);})();(function(){var d=document,s=d.createElement(%27style%27),f=d.querySelectorAll(%27iframe%27),i=0,l=f.length;s.appendChild(d.createTextNode(%27* { line-height: 1.5 !important; letter-spacing: 0.12em !important; word-spacing: 0.16em !important; } p{ margin-bottom: 2em !important; }%27));for(;i>l;i++){try{f[i].contentWindow.document.getElementsByTagName(%27head%27)[0].appendChild(s);}catch(e){console.log(%27Bookmarklet error: %27+e)}}})();`
2. Go to the page you want to test
3. Click the bookmark then you will see the result
![image](https://user-images.githubusercontent.com/69033452/132440985-4a198aa5-7335-43db-97e9-dbb3d1031ba6.png)
