### ISSUE TITLE
Tall Dialog being clipped - not able to scroll to content in top and headers in dialog

### ISSUE THREAD

**Issue by tnsholding** [microsoft/fluentui#19535]
### Environment Information

@fluentui/react-northstar v 0.57.0

### Please provide a reproduction of the bug in a codepen:

Reproduction in codesandbox:

https://codesandbox.io/s/fluent-ui-example-forked-rdfdv?file=/example.js

#### Actual behavior:

If dialog is taller than viewport then the vertical scrollbar does not allow to view top content of dialog (or headers incl. header actions).

#### Expected behavior:

Vertical scrollbar lets user scroll to the top of the dialog to view all content including header.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@tnsholding - thanks for filing this issue.

@jurokapsiar -  Would your team be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by tnsholding** [comment]
Any news on this one?
