### ISSUE TITLE
DefaultRenderer is not passed to onRenderIcon of IContextualMenuItem

### ISSUE THREAD

**Issue by dgrechka** [microsoft/fluentui#19545]
### Environment Information

- **Package version(s)**: "@fluentui/react": "8.29.2"
- **Browser and OS versions**: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/dgrechka/pen/jOwPvmV

#### Actual behavior:

The defaultRenderer parameters is not passed to the onRenderIcon callback.

If it is by design, please describe it in the docs of onRenderIcon.

#### Expected behavior:

The defaultRenderer parameter is passed to the onRenderIcon callback. The icon of the first context menu icon is rendered.

### Considerations:

I suppose the place where the parameter pass is missing is here https://github.com/microsoft/fluentui/blob/a3478be57b4ac7115c86e6687645d304a440b615/packages/react/src/components/ContextualMenu/ContextualMenuItem.base.tsx#L17

E.g. The same code renders the icon in CommandBar case, when the onRenderIcon is set for CommandBar item.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority:  Normal

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@dgrechka - Thanks for filing this issue with us. I see you are willing to submit a PR for this request change which is great to see!
Would you mind sharing it with us?

**Comment by dgrechka** [comment]
@gouttierre , I've created a PR #19760
