### ISSUE TITLE
Will Teams Theme update?

### ISSUE THREAD

**Issue by NewFuture** [microsoft/fluentui#19543]
## Component details

The Teams Theme in `@fluentui/theme-samples  seems out of date.

It's there any new new Teams theme based on `@fluentui/react`

**Comment by ecraig12345** [comment]
A theme for this exists internally (I'll send you a link on Teams) but there hasn't been any work on making it public. We might be able to make it public if there's enough interest, though that work would have to be balanced with other priorities.

**Comment by ecraig12345** [comment]
@gouttierre I won't be working on this any time soon, and I don't think anyone else plans to either. I've moved it to "needs backlog review."

**Comment by NewFuture** [comment]
thank you 😸
