### ISSUE TITLE
Allow giving default value to TimePicker

### ISSUE THREAD

**Issue by daniharo** [microsoft/fluentui#19554]
#### Describe the feature that you would like added

Now there is no possibility to give the new TimePicker component a default value, or to control its value: it's uncontrolled.
If it had a `value: Date` prop (as [DatePicker](https://developer.microsoft.com/es-ES/fluentui#/controls/web/datepicker) has) it could be controlled from outside.
In addition, an `onSelectTime: (time: Date) => void` prop would be welcomed too, to avoid parsing a formatted '6:00 a.m.' string in onChange function.

#### What component or utility would this be added to

TimePicker component

#### Have you discussed this feature with our team, and if so, who

@ecraig12345 has mentioned this several times: https://github.com/microsoft/fluentui/pull/18556#discussion_r655793805. Quoted below.

#### Additional context/screenshots

Original feedback from @ecraig12345:

> Something to consider for the future: right now it looks like the time picker is always completely uncontrolled (and doesn't even support passing a default value), but for some scenarios the consumer may want to pass a default value or manually control the value. 
> 
> In the interest of not complicating this PR even more, I think it's fine to wait on that feature until somebody requests it. But if/when you get around to implementing it, you'll need to ensure it implements the controlled/uncontrolled pattern properly--[here's an explanation I wrote](https://gist.github.com/ecraig12345/1ea4566ce171b844a0af5a3366d3473f), or you can find many other explanations online if that doesn't make sense. We also have a hook `useControllableValue` to help with implementing it properly.

**Comment by ecraig12345** [comment]
This isn't something the core team is likely to have time to work on any time soon. @CheerfulSatchel or @rockcs1992 do you have any plans to work on this or other TimePicker feature additions?

**Comment by skypyxis** [comment]
Without this capability the use cases where this component can be used is severely impacted, I believe.
I which I knew this was not possible before I started adopting it :( I never imagined we could not provide a value to an input control like this.

**Comment by MeijerM1** [comment]
I agree with @skypyxis, without the ability to control the component it is unusable in a lot of cases.
It's really hard to imagine the reasoning behind releasing a component that is clearly unfinished. Setting state must be one of the primary requirements I would think.

**Comment by gouttierre** [comment]
@daniharo  - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.

Unless, @CheerfulSatchel or @rockcs1992 can provide any updates or plans to work on these enhancements in the interim.

**Comment by CheerfulSatchel** [comment]
Hello everybody, apologies for the delay! I have added a PR that hopefully addresses this issue here: #20805
Please feel free to take a peek if you are interested. Thank you!!
