### ISSUE TITLE
Command Bar role should be defined as Menu instead of group

### ISSUE THREAD

**Issue by vidyasiva** [microsoft/fluentui#19574]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "7.121.7",
- **Browser and OS versions**: 
Browser - Chrome - Version 92.0.4515.131 
OS - Mac OS Big Sur - Version 11.4

### Describe the issue:

In the Command Bar, i have defined items(4) and far items(1)
When the voiceover reader focuses the command bar, it announces the top level items as 2 which is expected.
However, there is no separate provision between these two menus. Because of this user getting confused on the overall menu items count. So instead of 2, they expect it should be 5(which is the overall count)

### Please provide a reproduction of the issue in a codepen:

In Command Bar create some left items and right items
use VoiceOver to choose the command bar, it announces the overall count as 2, even though we could have more menu items

#### Actual behavior:

There is no boundary between these two items

#### Expected behavior:

Need a boundary

#### Suggested solution:

To overcome this, if we define the role as 'menu' instead of group, we can clearly define the boundary between these left and right items, also when the focus shifts between these menu, it properly reads as 4 items in menu 1 and 1 item in menu 2

By doing this, we will clearly get the boundary and Voice over reads the menu separately which is the expected end result

**Comment by gouttierre** [comment]
@vidyasiva - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [CommandBar](https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by vidyasiva** [comment]
Hello Team,

Will add the required codepen details within this week.

Thanks for the reminder.

Regards,
Vidya
