### ISSUE TITLE
BasicList unable to scroll

### ISSUE THREAD

**Issue by dslg604t** [microsoft/fluentui#19587]
### Environment Information

- **Package version(s)**: @fluentui 6.14.13
- **Browser and OS versions**: Google Chrome Version 92.0.4515.107, Microsoft Edge Version 92.0.902.84

### Please provide a reproduction of the bug in a codepen:
Code I used is in this codepen but error does not occur in the sandbow:
https://codepen.io/dslg604t/pen/ExXKgNN

#### Actual behavior:

Loading the component does not allow you to scroll up and down the list unless you change the zoom level on the page (either in or out).

I've tried adding the attribute data-is-scrollable="true" as per the page FAQ to no success.

#### Expected behavior:

Can scroll the list by default.

### Priorities and help requested:

Are you willing to submit a PR to fix? Maybe

Requested priority: Low

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@dslg604t - Thanks for filing this issue with us. I had a look at the repro you provide and was unable to produce the same results. The repro shared is v8 but the issue states v6. Could you confirm the issue again, please? Thanks

**Comment by dslg604t** [comment]
Hey @gouttierre , looks like the issue is due to putting it inside another component (react-bootstrap/tab in my case).

I'm happy for you to close it if this is expected functionality when used with other components.

**Comment by gouttierre** [comment]
Closing the issue - not on the roadmap for now.
