### ISSUE TITLE
Breadcrumb visibility:hidden on SSR

### ISSUE THREAD

**Issue by khowling** [microsoft/fluentui#19581]
### Environment Information

- **Package version(s)**: "~8.17.1"
- **Browser and OS versions**: Microsoft Edge 92.0.902.84

#### Actual behaviour:

Rendering a Breadcrumb on the server side leaves <div style="position:fixed;visibility:hidden" data-automation-id="visibleContent"></div> around the output. Resulting with a flicker when the browser rerenders.

#### Expected behavior:

Breadcrumb renders visibly on server side.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by khowling** [comment]
same as 
#12654

**Comment by gouttierre** [comment]
@khowling - Thanks for filing this item with us. I see you willing to submit a PR for this request. Would you mind sharing it with us?
