### ISSUE TITLE
Compact Chat fail in Teams App

### ISSUE THREAD

**Issue by t-lji** [microsoft/fluentui#19615]
![Snipaste_2021-09-02_11-37-10](https://user-images.githubusercontent.com/87359629/131777961-89da2648-be3b-44e0-a1c5-5ff37eb723ba.png)

Hi, I tried Compact Chat in my Teams App but it didn't work. I copied example code from [fluentui-chat](https://fluentsite.z22.web.core.windows.net/0.57.0/components/chat/definition) to my project.

You may try fork [chat-example](https://github.com/t-lji/chat-example.git) in vs-code plug-in Teams Toolkit and press F5 to debug it.

Thanks, look forward for you reply!

**Comment by gouttierre** [comment]
@t-lji - thanks for filing this issue with us.

@jurokapsiar -  Would your team be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by jurokapsiar** [comment]
Looks like you are using an older version of fluent ui in https://github.com/t-lji/chat-example/blob/main/tabs/package.json. Please use 0.57 or above to use compact chat.

**Comment by t-lji** [comment]
Thanks for your reply. I will try to update it.
