### ISSUE TITLE
react-conformance: find a way to have typed "testOptions" with "extraTests"

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#19618]
#19500 introduced new test conformance test, but it's used as extra test:

```tsx
isConformant({
    extraTests: makeStylesTests,
})
```

This works nice, but there is a small problem. The test has custom options (`callCount`) and they cannot be specified (produces TS error) as they no way to extend `TestOption` type:

https://github.com/microsoft/fluentui/blob/7d1896d9a205eee055d3a2ccdb21710ca397271d/packages/react-conformance/src/types.ts#L11-L15

**Comment by layershifter** [comment]
FYI @ecraig12345

**Comment by ecraig12345** [comment]
@layershifter Good catch, do you have ideas for how to extend this, or a different approach?

**Comment by ecraig12345** [comment]
Per @layershifter's suggestion I'm planning on changing the isConformant API to be more like babel's API:
```ts
isConformant({
  componentPath: '',
  presets: [ // or "rules"
    basePreset({ /* strict config options */ }),
    griffelPreset(),
  ],
});
```

**Comment by ecraig12345** [comment]
Tracked by #21665  instead.
