### ISSUE TITLE
onScroll typings for Callout in BasePicker are wrong

### ISSUE THREAD

**Issue by ivbylink** [microsoft/fluentui#19632]
### Environment Information

- **Package version(s)**: 7.1.2

### Please provide a reproduction of the bug in a codepen:

Quick mock up: https://codepen.io/ivbylink/pen/ExXyXxd

#### Actual behavior:

I have a need to hook into the onScroll event of the Callout in the BasePicker, which is actually allowed and doable. Unfortunately it seems like the typings for that onScroll event are just: `onScroll: () => void;` but there is actually a SyntheticEvent passed in to the onScroll that I need to access for our use case. The event is there, but I have to hack the typings in order to make BasePicker typings happy when I pass in onScroll to pickerCalloutProps.

#### Expected behavior:

Really just needs an update to the Callout typings so that onScroll actually acknowledges that there is an event passed in and allows it to be used.

### Priorities and help requested:

Are you willing to submit a PR to fix?
Yes

Requested priority:
Normal

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@ivbylink - thank you for filing this issue with us. I see you are willing to submit a PR for this request? That is great to see, if you have the solution ready, would you mind sharing it it with us?

**Comment by ivbylink** [comment]
@gouttierre I apologize for the delay in responding, I was on vacation when you commented and only got back.

The only change required here would be to change the line located here: https://github.com/microsoft/fluentui/blob/6d3408ab7a96381825b2925f64dbb388811bd36d/packages/react/src/components/Callout/Callout.types.ts#L238

It currently shows the onScroll type as: `onScroll?: () => void;` but there is actually a `SyntheticEvent` being passed into that function.
Since it's already being passed in and would be useful to have I would make the type: 
`onScroll?: (scrollEvent: SyntheticEvent) => void;` possibly with the added type if its constant (`SyntheticEvent<HTMLDivElement>`)
