### ISSUE TITLE
Combox with allowfreeform: dropdown is not functional when using windows narrator in scan mode

### ISSUE THREAD

**Issue by dcowen91** [microsoft/fluentui#19647]
### Environment Information

- **Package version(s)**: 8.30.3 latest
- **Browser and OS versions**: latest chrome and edge

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/dcowen/pen/oNwzvZd

#### Actual behavior:

when focused on combobox with narrator running in scan mode, down arrow does nothing. Enter does open the dropdown, but then down arrow does not navigate to the next item.

#### Expected behavior:

1. Have Narrator running in "scan mode" (caps lock + space to toggle scan mode)
2. Use tab key to navigate to the combobox
3. Use arrow keys/enter to attempt to navigate the combobox dropdown and select an item
4. Down arrow should expand the dropdown and cycle through options

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Microsoft Workplace Analytics

**Comment by gouttierre** [comment]
@dcowen91 - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@bsunderhus -  Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley

**Comment by smhigley** [comment]
Comboboxes and text inputs generally do not work in scan mode; needing to be in forms/application mode is a widely understood interaction requirement for this type of control. You can observe this with the native <select> element -- it has some pretty buggy behavior in scan mode, and it doesn't even have a freeform text input.
