### ISSUE TITLE
Datepicker with required field has validation which is always active, not validation on focus loss as described in the docs

### ISSUE THREAD

**Issue by RobertPakkoMSFT** [microsoft/fluentui#19645]
### Environment Information

- **Package version(s)**: 8.29.2
- **Browser and OS versions**: Edge, Windows 11

### Please provide a reproduction of the bug in a codepen:

No need, the issue is visible on the fluent docs (Heading: DatePicker with required field):
https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker

#### Actual behavior:

Validation is active on page load

#### Expected behavior:

Validation is only active on focus loss (this would be more consistent with other components and with how the datepicker behaved in previous versions of Fluent.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No): Sure

Requested priority: (Blocking, High, Normal, Low): Normal

Products/sites affected: (if applicable): MSFT Internal Tools

**Comment by gouttierre** [comment]
@RobertPakkoMSFT - Thanks for filing this issue with us. I see you are willing to submit a PR for this request - that is great to see! Would you mind sharing it with us? 

cc @bsunderhus
