### ISSUE TITLE
fluent ui/Nortstar add a loader when fetching the data from the api

### ISSUE THREAD

**Issue by sonatadevuser11** [microsoft/fluentui#19641]
how to add a loader when loading the data in fluent ui/northstar search able dropdown

**Comment by gouttierre** [comment]
@sonatadevuser11 - Thanks for reaching out to us. 

@jurokapsiar -  Would your team be able to add this request to your backlog.

**Comment by sonatadevuser11** [comment]
wanted to know is it possible

**Comment by jurokapsiar** [comment]
Hi, yes, this is possible. Check the "Loading" example in https://fluentsite.z22.web.core.windows.net/0.59.0/components/dropdown/definition?showCode=false&showRtl=false&showTransparent=false&showVariables=false#state-loading

This shows how the loading message can be customized to show a loader: https://codesandbox.io/s/myjuw?module=/example.js
