### ISSUE TITLE
[Bug] Panel - isFooterAtBottom prop has stopped working

### ISSUE THREAD

**Issue by stefan-burdy** [microsoft/fluentui#19653]
### Environment Information

- **Package version(s)**: from 8.30.1
- **Browser and OS versions**: Probably any

### Please provide a reproduction of the bug in a codepen:
You can view the codepen directly on the official website.
https://developer.microsoft.com/en-us/fluentui#/controls/web/panel. Expected to have footer at the bottom of the panel (as was before 8.30.1)

#### Actual behavior:

![image](https://user-images.githubusercontent.com/84866199/132140295-c0872bbc-d724-4d87-a533-8cccb0f35e1c.png)

#### Expected behavior:

Expected to have footer at the bottom.

![image](https://user-images.githubusercontent.com/84866199/132140290-dc0eea7e-1e16-4b86-b12a-b2412d3c082f.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: New FluentUI-based CMS (WIP) :-)

**Comment by lucas-stanford** [comment]
@TristanWatanabe  looks like your change here: https://github.com/microsoft/fluentui/pull/19547 caused this.

**Comment by JustSlone** [comment]
Seems like we have a missing VR test here as well for the panel sample that regressed
