### ISSUE TITLE
Modal is rendering inside WebPart screen context

### ISSUE THREAD

**Issue by Suresh-Lakum** [microsoft/fluentui#19666]
- SharePoint Online

- sp-office-ui-fabric-core (1.9.1)
- Windows 10 (Google Chrome)

### Describe the issue:

I have SPFx webpart, deployed on SharePoint online. I have dialog implemented inside it.
Dialog height is bigger then my WebPart height. When opening dialog, opens up inside webpart height.
I am assuming it should adjust according to height of page, instead of webpart height.

### Please provide a reproduction of the issue in a codepen:

I can't provide codepen, as it's working fine with debug mode.
When I deploy it to Sharepoint online, issue is reproducable.
![ss_issue](https://user-images.githubusercontent.com/8993338/132377419-5d288acb-8819-42c5-806b-a4665b1bc645.png)

#### Actual behavior:

It should adjust modal context according to SharePoint page height, instead of webpart height.

#### Expected behavior:

I am assuming it should adjust according to height of page, instead of webpart height.

**Comment by gouttierre** [comment]
Would you be able to share the code with our developers

**Comment by gouttierre** [comment]
@Suresh-Lakum - thank you for filing this issue with us. I see you are unable to share the code with us. If it is required, our developers will need to work with you in reviewing the issue during at run time. To set expectation our team will have a look at the issue but only once capacity allows.

@bsunderhus -  Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by Suresh-Lakum** [comment]
Hi, In order to reproduce this issue. You can create one button and apply large modal in webpart.
Now try to open Modal from webpart in live and see it's behavior.

Let me know if you need screen sharing or anything, I will be happy to do so.

**Comment by Suresh-Lakum** [comment]
You guys want me to develop same webpart code base and send it to you guys?
