### ISSUE TITLE
ShimmeredDetailsList first column fluctuating width 

### ISSUE THREAD

**Issue by mankumar66** [microsoft/fluentui#19673]
[screen-capture.zip](https://github.com/microsoft/fluentui/files/7126055/screen-capture.zip)
Hi Team,
I can see a visible shift in the first column of  DetailsList after the shimmer effect ends.
Could you please correct this behavior.

**Comment by GeoffCoxMSFT** [comment]
@mankumar66 I think this PR fixed the issue. https://github.com/microsoft/fluentui/pull/19774
