### ISSUE TITLE
@fluentui/react-slider: use simplified prop merging

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#19685]
### Migrate to use simplified prop merging

All components in `@fluentui/react-slider` should be migrated. See #18844 for additional details.

### Checklist

- [ ] Remove `defaultProps` in `useCOMPONENT`
- [ ] Remove `mergeProps`
- [ ] Define type for slots
- [ ] (optionally) Define `COMPONENTCommons` type
- [ ] Update types for a component
- [ ] Update `getSlots()`
- [ ] Update `useCOMPONENTStyles()`

**Comment by czearing** [comment]
The issue is addressed by https://github.com/microsoft/fluentui/pull/19652.
