### ISSUE TITLE
@fluentui/detaillist:  Detail List Justified layout needs to use horizontal scroll to show vertical scrollbar

### ISSUE THREAD

**Issue by rajeshpatil74** [microsoft/fluentui#19692]
When detail list have justfied layout, resizing column adjust other columns to fix. 

But to display vertical scrollbar , one need to scroll a bit on right side using horizontal scrollbar.

https://codepen.io/rajeshpatil74/pen/rNwjqOX

Expected behaviour - the vertical scrollbar should be visible without need of using horizontal scroll.

![image](https://user-images.githubusercontent.com/4305331/132547602-5ce9442d-8932-4c5d-921b-10d71b8a9ba8.png)

**Comment by gouttierre** [comment]
@rajeshpatil74 - Thanks for filing this issue with us and sharing the repro steps into the problem. To set expectation our team will have a look at the issue but only once capacity allows.

@bsunderhus - Would you be able to confirm if this is a regression, or if this behavior is an issue with the scrolling?
