### ISSUE TITLE
Persisted Menus Are Not Being Repositioned

### ISSUE THREAD

**Issue by tabrumle** [microsoft/fluentui#19728]
### Environment Information

- **Package version(s)**: V8

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/The_Golden_Goose/pen/PomvZYa

Steps:
1. Open Menu
2. Resize window to a smaller width
3. Open Menu
4. Observe that we never reposition the callout

#### Actual behavior:

Opening a persisted menu does not resize to fit itself onto the screen

#### Expected behavior:

Opening a peristed menu will always try to reposition the menu on its target onscreen.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: O365

**Comment by jspurlin** [comment]
@GeoffCoxMSFT, I see this is assigned to you. I was just made aware of this issue, we're (office online) seeing this in our menus after upgrading to V8. It results in incorrect menu positioning (potentially being cut off at the edge of the window, or floating seeming orphaned from the target). Mind taking a look?

**Comment by khmakoto** [comment]
@smhigley made a bunch of positioning fixes in #19472 that merged this Monday. I'm not sure if they would fix this type of scenarios but might be worth double-checking.

**Comment by GeoffCoxMSFT** [comment]
I can reproduce this in the lasted pull from master so I don't think the positioning PR fixed this.
