### ISSUE TITLE
npm package @uifabric/charting depends on office-ui-fabric-react but does not declare dependency

### ISSUE THREAD

**Issue by ZhehooMorgen** [microsoft/fluentui#19743]
### Environment Information

- **Package version(s)**: 4.17.2
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
   This bug is about the package it self

#### Actual behavior:
Run:
    npm i @uifabric/charting
To add the package to your project.
Do some coding
Then: 
    npm run build
You can see lots of errors like this:
![image](https://user-images.githubusercontent.com/22492020/132806091-53a769d7-b32d-4f0c-bc52-b9760884d52c.png)
After I installed office-ui-fabric-react, these errors are gone.

#### Expected behavior:
Modules of this package should be resolved, instead of having so many errors.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low)
Normal
Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@ZhehooMorgen - Thanks for filing this issue. 

@Raghurk - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by AtishayMsft** [comment]
Reopening this issue.
