### ISSUE TITLE
Project: Prepare Tooltip & Avatar for beta

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#19778]
# Project: Prepare Tooltip & Avatar for beta

### Problem
Tooltip and Avatar are in the Beta release, and need to be updated for the beta release.

### Appetite
2 weeks

### Solution
* Implement simplified prop merging
    * Avatar: https://github.com/microsoft/fluentui/pull/19449
    * Tooltip: https://github.com/microsoft/fluentui/pull/19428
* Update any APIs based on the API survey
* Update Avatar's slot shorthand based on RFC: https://github.com/microsoft/fluentui/pull/19527

### Risks (Rabbit holes)
N/A

### Out of scope (No-gos)
N/A

**Comment by khmakoto** [comment]
Since all the steps in the solution are implemented this should be ready to be closed.
