### ISSUE TITLE
Icon with iconName 'AltText' not rendered.

### ISSUE THREAD

**Issue by nviolero** [microsoft/fluentui#19772]
### Environment Information

- **Package version(s)**: v7.176.0

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/nviolerocp/pen/WNOOYxa

#### Actual behavior:

When you specify the icon name 'AltText' in any fluent ui compoentnt with the iconName property, is not being rendered.

#### Expected behavior:

The icon with name 'AltText' should be shown as it exists in the fabric icon library https://uifabricicons.azurewebsites.net/. The icon code is supposed to be E397 but I can not find any icon with that code in the font-icons-mdl2 package.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by gouttierre** [comment]
@nviolero - Thanks for filing this issue with us and showing interest in submitting a fix for this problem. 
Would you mind sharing it with us?

**Comment by nviolero** [comment]
Thanks for your answer. As I mentioned, the AltText icon is not working. Here is the icon in the uifabric icons web page:
![image](https://user-images.githubusercontent.com/79575927/136007396-7d832241-8041-407c-bd5b-4b55ad980cb1.png)

And here is the codepen example
https://codepen.io/nviolerocp/pen/WNOOYxa

As you can see, the icon is not being rendered.

Regards.

**Comment by nviolero** [comment]
Sorry any comments about this issue?

Regards.
