### ISSUE TITLE
Project: Manual accessibility review for vNext Beta/RC

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#19779]
## Problem
Fluent vNext components could use an accessibility review before we release them in Beta, just to catch any potential issues while they're still easy to change.

## Appetite
2 weeks

## Solution
Review components that have UI and are included in the initial beta release, and raise any necessary issues
- [x] Accordion #21101
- [x] Avatar #21102
- [x] Badge (includes CounterBadge and PresenceBadge) #21103
- [x] Button (includes CompoundButton, MenuButton, SplitButton, and ToggleButton) #20917
- [ ] Card #21104
- [x] Divider #21105
- [x] Link #19926 
- [x] Menu #21106
- [x] Popover #21107
- [x] Tooltip #21108

## Risks (Rabbit holes)
N/A

##  Out of scope (No-gos)
N/A

**Comment by jurokapsiar** [comment]
it would be good to include VoiceOver+Chrome as well - as a lot of apps are chromium based.

**Comment by smhigley** [comment]
@jurokapsiar I had the same thought, it's included in the RFC + checklist 😊

**Comment by smhigley** [comment]
## End of month retrospective (November)

### What was achieved?
- RFC for manual a11y review checklist: https://github.com/microsoft/fluentui/issues/20916, https://gist.github.com/smhigley/0f08c38758359e62f06d692a23860e63

### What did we miss?
- Components themselves still need a11y reviews, apart from link

### What went well?
I'm happy with the checklist itself, and setting up a better process for delegating a11y review steps.

### What could have gone better?
It would've been good to get the checklist done sooner, so there's less of a time crunch before RC

### What changed from initial expectations?
The scope of the a11y review probably expanded a bit since writing the proposal (since originally I planned to do the reviews myself). It's now a somewhat longer review, with more coordination between myself and component authors needed.

**Comment by miroslavstastny** [comment]
@behowell are we closing this one in favour of #21099?

**Comment by smhigley** [comment]
Let's actually close #21099 and keep this one -- I'll copy over the description with the links

**Comment by smhigley** [comment]
Closing, since all initial RC components were tested. Ongoing component testing is tracked in #21984
