### ISSUE TITLE
`getNativeElementProps` does not propagate `as` prop

### ISSUE THREAD

**Issue by andrefcdias** [microsoft/fluentui#19785]
### Reproduction

Given a hook like so:

```ts
// useText.ts
export const useText = (props: TextProps, ref: React.Ref<HTMLElement>): TextState => {
  return {
    {...}

    components: { root: 'span' },

    root: getNativeElementProps(props.as ?? 'span', {
      ref,
      ...props,
    }),
  };
};
```

With `getNativeElementProps`, our state.root consists of:
```
{
  ref,
  className,
  children
}
```

Which means that, when rendering the slot:

```tsx
// renderText.ts
export const renderText = (state: TextState) => {
  const { slots, slotProps } = getSlots<TextSlots>(state, ['root']);

  return <slots.root {...slotProps.root} />;
};
```
`slots.root` == 'span' as state.root has no information of what to render it as.

#### Actual behavior:

`getSlots` doesn't get the required information to render slots when using `getNativeElementProps`.

#### Expected behavior:

Slot is rendered with the element provided with the `as` prop

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: 
- react-text
- react-link

**Comment by khmakoto** [comment]
I had this same problem with `Link` and had to spread `as` separately so we should definitely fix this.

**Comment by bsunderhus** [comment]
The idea would be to stop using `getNativeElementProps`. The ideal would be to have conformance test + (perhaps) some eslint rulings to ensure that the slots are being declared and properties are being properly filtered without the need of this specific method, but this will take time and discussion, I guess for the moment we can simply include `as` prop as an exception in `getNativeElementProps`
