### ISSUE TITLE
Unable to type into font name text box on ribbon menu using multi-byte language IME

### ISSUE THREAD

**Issue by 2009xiaoqi** [microsoft/fluentui#19791]
### Environment Information

- **Package version(s)**: web fluent combobox
- **Browser and OS versions**: chrome, window 11

### Please provide a reproduction of the bug in a codepen:
-This is not Word specific issue. It is also reproducible in Excel, PowerPoint web app.
-Office client works well.
-If we only use English IME, the issue would not occur. However, once we switch to multi-byte language IME and try to type in that language, issue repro and will persist even if we switch back to English IME.
-Tested Japanese IME, Chinese IME, Korean IME. All repro.

Repro steps:
I first typed 'times' using English IME and got correct output (non-repro)
Then I switched to Japanese and typed 'tesuto' that supposed to get 'てすと', but got corrupt output.
At the end, I switched back to English IME and typed 'times' again. This time I got 'imest'.

#### Actual behavior:

User got corrupt font name by typing. Please refer to this bug https://office.visualstudio.com/OC/_workitems/edit/5415172 with the repro video to see result

#### Expected behavior:

Expected behavior is once user select a different language, it should type and get the right output

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable) Customer affected

**Comment by gouttierre** [comment]
@2009xiaoqi - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.

@bsunderhus -  Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @GeoffCoxMSFT
