### ISSUE TITLE
Comment on Pivot breaking changes

### ISSUE THREAD

**Issue by allsvieira** [microsoft/fluentui#19819]
@ecraig12345 This was not a breaking change because the values of the enum were changed to be the same strings. It works fine to write either `linkSize="large"` or `linkSize={PivotLinkSize.large}` (the latter evaluates to the string "large"). See the usage of the PivotLinkSize enum in [apps/vr-tests/src/stories/Pivot.stories.tsx](https://github.com/microsoft/fluentui/blob/cbc0b9a2f9b569eeabd7bba3812002edcca948e8/apps/vr-tests/src/stories/Pivot.stories.tsx)

_Originally posted by @behowell in https://github.com/microsoft/fluentui/issues/15384#issuecomment-705266844_

**Comment by allsvieira** [comment]
{PivotLinkSize.large}

PivotLinkSize enum

Package:

@fluentui/react
 
Warning

This API is now obsolete.

Use strings 'normal' or 'large' instead of this enum.

https://docs.microsoft.com/en-us/javascript/api/react/pivotlinksize?view=office-ui-fabric-react-latest

**Comment by ecraig12345** [comment]
@allsvieira I'm not sure what your question is here?
