### ISSUE TITLE
Grouped DetailsList will rerender on row click if items are updated after load.

### ISSUE THREAD

**Issue by upanshed** [microsoft/fluentui#19839]
When clicking on a row of a detailslist that has groupings the onRender fires again for every row. This is causing a performance issue for me because im trying to show a callout on click. The re-render is causing a 2 second delay. Is there a work around for this?
I created a codepen of the issue
https://codepen.io/upanshed/pen/OJgzoQv

open the codepen, let it render, then open the console, when you click on the row that says 'Click WILL cause rerender' you will hit the break point. 
This does not happen on the one that didnt get the new items after render

Thanks

**Comment by gouttierre** [comment]
@upanshed - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@GeoffCoxMSFT  -  Would you be able to confirm if this is a regression, or if this behavior is an issue?
