### ISSUE TITLE
Dropdown has Y overflow by default

### ISSUE THREAD

**Issue by chadsowald** [microsoft/fluentui#19857]
### Environment Information

- **Package version(s)**: 7.170.3
- **Browser and OS versions**:  Not relevant

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/chmsft/pen/ZEyrwrQ

#### Actual behavior:

There is a 1px vertical overflow as the dropdown caret has both 'top: 1px" and height: 32px, but the containing box is 32px.

#### Expected behavior:

There should be no vertical overflow by default.  I assume the intention was to vertically center the caret in the dropdown.  The CodePen has 2 potential fixes that maintain that intention.

### Priorities and help requested:

Are you willing to submit a PR to fix? No, but the CodePen has 2 potential fixes.

Requested priority: (Blocking, High, Normal, Low): Normal

**Comment by khmakoto** [comment]
Hi @chadsowald, I can confirm this is happening and we should fix it.

@gouttierre and anyone else that takes a look at this, fyi this can be seen when zooming in to the component

![image](https://user-images.githubusercontent.com/7798177/142093291-4f561913-bd01-45cf-be8c-39296962e378.png)
