### ISSUE TITLE
[Combobox] - When trying to type Japanese in combobox fields, it returns wrong string on the screen

### ISSUE THREAD

**Issue by tabansal** [microsoft/fluentui#19869]
Hello Team,

When user tries to type japanese in combobox, the input letters gets rearranged and some of them get duplicated. For instance when I try to type 時間 (meaning "hour"), the input is "jikan", which should be returned as "じかん" but it gets returned as "じかｎｎｋｊ“ . Can someone please look into this on urgent basis since this is impacting is since this is impacting our live product?

Issue is reproducible on https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox. 

![image](https://user-images.githubusercontent.com/49181832/134082234-78204488-e1e5-43ab-86a6-cfda23e8a8f3.png)

Regards,
Tapas Bansal

**Comment by DingpingZhang** [comment]
This issue also occurs in Chinese input, which seems to be related to the IME (Microsoft Pinyin), and should be a issue for any language that requires text to be entered from the alternative box.

**Comment by tahoon-ms** [comment]
This might be the same issue as #18165. I am not able to repro with Japanese IME on Windows 11.

**Comment by khmakoto** [comment]
Hey @tabansal, this doesn't seem to be an issue for me as can be seen in the screenshot below:

![image](https://user-images.githubusercontent.com/7798177/142108044-91c2418c-e3a2-457d-a171-8489dd42e015.png)

Would you mind checking again to see if the issue still reproes with the latest version of Fluent? Thanks!
