### ISSUE TITLE
Users navigating to next item in StackedBarChart using caps+arrow keys, the previously focused item is also announced. 

### ISSUE THREAD

**Issue by emokeeff** [microsoft/fluentui#19885]
### Environment Information

- **Package version(s)**: @uifabric/charting - 4.16.5
- **Browser and OS versions**: Chrome Version 93.0.4577.82 && Edge 93.0.946.1 (Official build) dev (64-bit) on Windows 10

### Describe the issue:

Users navigating to next item in stacked bar chart using caps+arrow keys, the previously focused item is also announced. 

### Please provide a reproduction of the issue in a codepen:
The issue repros on Fluent UI Charting Example [site](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/charting/dist/index.html#/examples/stackedbarchart)

Go to the given URL : [https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/charting/dist/index.html#/examples/stackedbarchart](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/charting/dist/index.html#/examples/stackedbarchart)
Navigate to ‘Stacked bar chart 2nd example’ group.
Navigate inside the group using caps+arrow keys and observe that when users navigates to next item, first the previously focus item is announced and then the currently focused item is announced.

#### Actual behavior:

In 'Stacked bar chart 2nd example' and other StackedBarChart groups when users navigates to next item using caps+arrow keys , first the previously focused item is announced and then the currently focused item is announced.

#### Expected behavior:

In 'Stacked bar chart 2nd example' and other StackedBarChart groups when users navigates to next item using caps+arrow keys, only the currently focused item info should be announced.

### Documentation describing expected behavior

Users with visual impairments who rely on screen readers will get confused and misguided if narrator announces the previously focused device build first and then the currently focused device build.

**Comment by gouttierre** [comment]
@emokeeff  - thanks for filing this issue. 

@Raghurk - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by AtishayMsft** [comment]
Reopening this issue.
