### ISSUE TITLE
Button documentation: provide example of wizard buttons

### ISSUE THREAD

**Issue by mcshaz** [microsoft/fluentui#19896]
#### Describe the feature that you would like added

This is a documentation request, not the library itself.

The documentation for fluent UI (which is great BTW) includes the Best Practices statement for the `Button` control:

> - For dialog boxes and panels, where people are moving through a sequence of screens, right-align buttons with the container.
> - Always place the primary button on the left, the secondary button just to the right of it.
> - Don't use a button to navigate to another place; use a link instead. The exception is in a wizard where "Back" and "Next" buttons may be used.

It would be great if you could add an example of how the wizard "Back" and "Next" buttons should look, in order to address:
1. For left to right reading cultures, the "Next" button would be to the right of the "Back" button, yet the "Next" button would seem the `primary` button.
2. Right align both the "Back" and "Next" buttons, or only the "Next" button (and the "Back" button left aligned in the container)?
3. Include `RightChevron` or similar icon to the right of the "Next" button text (and `LeftChevron` to the left of "Back")? Or is the best practice guideline indicating "Back" and "Next" buttons should be text only?

#### What component or utility would this be added to
fluent UI `Button` documented examples
#### Have you discussed this feature with our team, and if so, who

No

**Comment by gouttierre** [comment]
@mcshaz - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.

@GeoffCoxMSFT - After confirming this request - perhaps, we address this for v8 and vNext (Storybook) docs?
cc @khmakoto

**Comment by gouttierre** [comment]
Documentation has been overhauled for the latest version. Reference [Button ](https://react.fluentui.dev/?path=/docs/components-button-button--default)
