### ISSUE TITLE
concatStyleSets returns array for sub component styles rather than merging them

### ISSUE THREAD

**Issue by haperr** [microsoft/fluentui#19898]
### Environment Information

- **Package version(s)**: 8.32.0
- **Browser and OS versions**: Not relevant

### Please provide a reproduction of the bug in a codepen:

When using `concatStyleSets()` with style sets that contain sub-component styles, it returns an array rather than merging the styles.

An example style set that doesn't work is something like:
```
interface IFooStyles {
  button: IButtonStyles;
  picture: IImageStyles;
}
```

Instead of receiving merged `IButtonStyles` and merged `IImageStyles` `concatStyleSets()` returns an array of `IButtonStyles` and an array of `IImageStyles`

https://codesandbox.io/s/divine-meadow-2gg4j?file=/src/App.tsx

#### Actual behavior:

`concatStyleSets()` returns an array of styles for style sets rather than merging them. Example returned object is of the format:
```
{
  button: [
    root: { color: 'red' },
    root: { backgroundColor: 'blue' },
  ],
  picture: [
    image: { margin: 0 },
    image: { padding: 0 },
  ],
}
```

#### Expected behavior:

`concatStyleSets()` should merge the styles so that the returned style set is same format (in this case `IFooStyles`)
```
{
  button: {
    root: { 
      color: 'red',
      backgroundColor: 'blue',
    }
  },
  picture: {
    image: {
      margin: 0,
      padding: 0,
    },
  },
}
```

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Fluid Framework

**Comment by kestill** [comment]
Hello, just wanted to check in on this bug since it hasn't been updated in a few months. This is still an issue for us on the Fluid Framework/FFX/Loop team.
