### ISSUE TITLE
React-charting DonutChart valueInsideDonut text does not change to light color font in dark mode theme

### ISSUE THREAD

**Issue by JuliusShanMS** [microsoft/fluentui#19906]
### Environment Information

- **Package version(s)**: @fluentui/react-charting": "^5.3.42"
- **Browser and OS versions**: Microsoft Edge
Version 93.0.961.47 (Official build) (64-bit)

### Describe the issue:

The DonutChart control from @fluentui/react-charting does not change its text color when the theme is changed from Light mode to Dark mode. This is visible in the charting demo (https://admincontrolsdemoapps.blob.core.windows.net/release/charting-demo/3.0.6/index.html#/examples/DonutCharts) as well as when running the localhost Azure portal and flipping the  theme from the default light theme in Azure Portal to dark mode. 

#### Actual behavior:

ValueInsideDonut text does not change to light color font when theme is changed to dark mode. 

#### Expected behavior:

ValueInsideDonut text is changed to light/white color font in dark mode, so that it's actually readable. 

### Documentation describing expected behavior

Change theme on a Azure Portal or in charting demo to dark mode. Note that the valueInsideDonut does not change to a light color font. Instead, the font stays dark and is basically unreadable. 

![image](https://user-images.githubusercontent.com/78509861/134392555-cbd08f5d-9871-4838-9e44-33d96b588195.png)
![image](https://user-images.githubusercontent.com/78509861/134392622-acd40854-6227-4ef8-8f66-9e94d4e4abc8.png)

**Comment by gouttierre** [comment]
@JuliusShanMS - thanks for filing this issue with us.

@Raghurk - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by AtishayMsft** [comment]
Closing this issue.
