### ISSUE TITLE
[Dropdown] Headers and dividers marked as hidden, are still shown

### ISSUE THREAD

**Issue by chadsowald** [microsoft/fluentui#19909]
### Environment Information

- **Package version(s)**: 7.170.3
- **Browser and OS versions**: Not relevant

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/chmsft/pen/XWgBgmW

#### Actual behavior:

Marking dropdown items as hidden only works for normal items.  Headers and Dividers are not hidden, even though the prop is valid for them and documentation doesn't say they shouldn't be hidden.  

#### Expected behavior:

If I mark an item (regardless of type) as 'hidden=true', it should be hidden.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by khmakoto** [comment]
Hi @chadsowald and @gouttierre, I can confirm that this is indeed happening. We'll make a fix once capacity allows.
