### ISSUE TITLE
Update ColorPicker validation to show error information onInput

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#19911]
### Describe the issue:

The current error handling in the ColorPicker happens on blur, and auto-changes invalid r/g/b/a values to the closest valid value. This causes issue for screen reader and magnifier users, since they're much more likely to miss the change in the input value.

The suggested fix is to validate as the user types, and if they type an out-of-bounds value, to display a tooltip + live region with the input requirements (e.g. "Red values must be between 0 and 255"). We then keep the change-on-blur behavior.

Fixes [11964](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/11964)

**Comment by ecraig12345** [comment]
This could make sense. What's the behavior if they delete the field contents?
