### ISSUE TITLE
Missing documentation for onFocus in Dropdown component

### ISSUE THREAD

**Issue by KatieProchilo** [microsoft/fluentui#19914]
#### Describe the feature that you would like added

Need documentation for the `onFocus` prop for the `Dropdown` component.

#### What component or utility would this be added to

`Dropdown`

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

https://fluentsite.z22.web.core.windows.net/0.59.0/components/dropdown/props

**Comment by gouttierre** [comment]
@KatieProchilo  - Thanks for filing this issue with us.

@jurokapsiar - Could your team confirm the documentation?
