### ISSUE TITLE
Object.assign returns undefined in mergeClasses 

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#19927]
### Environment Information

- **Package version(s)**: `@fluentui/react-make-styles`
- **Browser and OS versions**: FF (14 versions behind) and Chrome (49 and 50 versions behind)

#### Encountered behavior:

A partner team has reported a crash in the aforementioned browsers complaining in `mergeClasses` with the following message:

> TypeError: Cannot read property 'apply' of undefined

After investigating we have found that the error comes from [this section of the code](https://github.com/microsoft/fluentui/blob/c845a5045c99d8d83b2584cee016b1701cd3de57/packages/make-styles/src/mergeClasses.ts#:~:text=//%20eslint-disable-next-line%20prefer-spread,).

#### What to do moving forward?

We should look at our browser support matrix and those of our partners and see how we move forward since this is affecting very old versions of the browsers as can be seen [here](https://caniuse.com/?search=object.assign). If found to be blocking we can start discussions on a fix or workaround.

**Comment by ecraig12345** [comment]
Actually `target` as well...a browser that doesn't support Object.assign will definitely not like ES2019 syntax. So this definitely seems to indicate a mismatch between our expectations and partners' for browser support.

**Comment by layershifter** [comment]
> * **Browser and OS versions**: FF (14 versions behind) and Chrome (49 and 50 versions behind)

@khmakoto @ecraig12345 As I remember we agreed to not support such old browsers.
Should be this closed?

**Comment by khmakoto** [comment]
IIRC that was what we agreed on. Unless @ecraig12345 says differently I think we should close this.

**Comment by ecraig12345** [comment]
Yeah we don't intend to support anything that old.
