### ISSUE TITLE
Failure in set custom CSS to Popup by className

### ISSUE THREAD

**Issue by ttao0807** [microsoft/fluentui#19931]
### Environment Information

- **Package version(s)**: (fill this out) 0.56.0
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/fluent-ui-example-forked-2lc2k?file=/example.js

#### Actual behavior:

Customized className does not bring about any CSS property to Popup as described in [doc](https://fluentsite.z22.web.core.windows.net/0.56.0/components/popup/props).

#### Expected behavior:

Customized className popupOpacity add additional opacity = 0.5 to rendered Popup element.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/sites affected: (if applicable)

**Comment by layershifter** [comment]
As in Northstar we use CSS-in-JS you can apply `opacity` to content via `styles`:

```tsx
  <Popup
    trigger={<Button icon={<MoreIcon />} title="Show popup" />}
    content={{ content: "Hello from popup!", styles: { opactity: '0.5' }}
  />
```

If you want to use plain CSS, you should pass it to `content` slot:

```tsx
  <Popup
    trigger={<Button icon={<MoreIcon />} title="Show popup" />}
    content={{ content: "Hello from popup!", className: styles.popupOpacity }}
  />
```

[🗃️ CodeSandbox](https://codesandbox.io/s/fluent-ui-example-forked-xhi09?file=/example.js:237-393)

---

`className` prop on `Popup` ~~does not exist~~ is not handled, I will create a PR to remove it. Thanks for reaching us 👍
