### ISSUE TITLE
Typehints missing in codesandbox for react-components

### ISSUE THREAD

**Issue by tomi-msft** [microsoft/fluentui#19939]
### Environment Information

- **Package version(s)**: 9.0.0-alpha.112
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

#19415 has been addressed, and codesandbox is working now with react-components, but typehints are now missing

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by tomi-msft** [comment]
Will be addressed after the major bumped react-icons package is merged: https://github.com/microsoft/fluentui/pull/20563

**Comment by bsunderhus** [comment]
Has this issue been resolved by https://github.com/microsoft/fluentui/pull/20563 ? @tomi-msft

**Comment by tomi-msft** [comment]
Yep, closing this issue now @bsunderhus
