### ISSUE TITLE
v9: Each component should have classname?

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#19937]
Currently each component & slot in Fluent N* has own classname.

- v8 follows `ms-Text`
- v0 follows `ui-text`

Do we want to have the same in v9?

_Should be covered with conformance test (similar to N*)._

### Motivation

- allows to build selectors for component parts (`:hover`)
- simplifies understanding of DOM tree

### Components to review post decision
- react-card - https://github.com/microsoft/fluentui/pull/20030

**Comment by andrefcdias** [comment]
Given that this is still pending discussion, I went with `fluentui-react-<component>` for react-card.(https://github.com/microsoft/fluentui/pull/20030).
Linking the PR here and changing the description for tracking purposes once we come to a consensus.
https://github.com/microsoft/fluentui/pull/20030

**Comment by layershifter** [comment]
> Didn't realize this during the discussion, but I think we should include "r" (for react) in the prefix as well to avoid collision with other fluent UI libraries such as web components.

As I know the single other web flavor is web-components, but there classes are non-sense as HTML is rendered inside shadow DOM:

![image](https://user-images.githubusercontent.com/14183168/139843886-2efcece9-4801-4035-b365-d8b6c445cd95.png)

This looks to me like a premature change.
