### ISSUE TITLE
Remove FocusZone from BasePicker in office-ui-fabric-react too

### ISSUE THREAD

**Issue by vkohade99** [microsoft/fluentui#19948]
### Environment Information

- **Package version(s)**: (7.176.1)
- **Browser and OS versions**: (Edge/Chrome(atleast) Windows10)

### Describe the issue:

It seems, focuszone has been removed from basepicker in latest fluentui while it is still there in office-ui-fabric-react. Request is to give the same changes in office-ui-fabric-react also. The issue is we were implementing a basepicker inside a details row which itself is a part of focuszone. So using arrow key navigation we weren't able to go inside the basepicker or get suggestions. The issue was fixed when we used latest fluentui. But to make that library change in a very large repo is difficult. Hence, please remove the focuszone in basepicker of office-ui-fabric-react too.

**Comment by ecraig12345** [comment]
Unfortunately this change is too high risk/potentially breaking for us to make in version 7 at this point (it's basically our "long-term support" branch). If you'd like the pickers without a FocusZone, you'll need to upgrade to version 8.
