### ISSUE TITLE
TeachingBubble's close icon button does not show tooltip in focus

### ISSUE THREAD

**Issue by RYTHAM** [microsoft/fluentui#19949]
Link to old related issue- https://github.com/microsoft/fluentui/issues/10010

I am facing same issue. No tooltip is shown for close button when focused. This above github issue is in resolved state but I can repro it on fluent UI documentation site- https://developer.microsoft.com/en-us/fluentui#/controls/web/teachingbubble
I tried with different browsers including Edge.

###  Issue:
No tooltip shows for close button and this seems to be an accessibility bug. For any icon button without visible label when in focus, it should show a tooltip with its title/tooltip text.

#### Actual behavior:
![image](https://user-images.githubusercontent.com/17340665/134632333-b3201607-1ea2-4af9-93fb-9ca1d14334ea.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/17340665/134632276-b84d5bdc-491e-4c92-a407-f7c5444bc896.png)

Describing expected behavior
When Icon button without no visible label is in focus, tooltip should appear with title/aria-label of button.

**Comment by gouttierre** [comment]
@RYTHAM - Thanks for filing this issue with us.

@bsunderhus - Would you be able to confirm if this is a regression, or if this behavior is an issue with tooltips? 
cc @GeoffCoxMSFT
