### ISSUE TITLE
CopyableLabels similar to ko.js

### ISSUE THREAD

**Issue by atasims07** [microsoft/fluentui#19951]
#### Describe the feature that you would like added

Like we have copyable labels for knockout controls, can we have similar fluentUi controls?
These controls give an easier experience for customers when they have copy something from the portal for e.g., in the attached image below user can easily copy the mount command and paste it in his command prompt in order to mount to the particular resource.

#### What component or utility would this be added to

CopyAbleLabel. Has to be a new FluentUI control

#### Have you discussed this feature with our team, and if so, who

Yes have discussed this with my manager.

#### Additional context/screenshots

Behaviour in knockout controls:
![image](https://user-images.githubusercontent.com/75667107/134640536-ee7f5c13-823e-4b51-8848-1f9d305a7925.png)

**Comment by gouttierre** [comment]
@atasims07 - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
