### ISSUE TITLE
Panel Footer is getting misaligned during overflow.

### ISSUE THREAD

**Issue by PraveenVerma17** [microsoft/fluentui#19961]
### Environment Information

- **Package version(s)**:  8.34.1
- **Browser and OS versions**: Edge, Chrome

#### Actual behavior:

Panel footer is totally getting misaligned in 8.34.1 when we have overflow data. 

#### Expected behavior:

Panel footer should be visible at all the the time, even we have overflow data. 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
High

Products/sites affected: (if applicable)

**Comment by PraveenVerma17** [comment]
Just to let you know panel works fine with version 8.20.1

**Comment by PraveenVerma17** [comment]
here is code pen example, i just added paragraphs to overflow content. after overflow i juts scroll and this happened. 
https://codepen.io/princeindia/pen/QWgZjym

**Comment by ecraig12345** [comment]
@TristanWatanabe Can you help with this since it's a regression from your PR #19811?

**Comment by PraveenVerma17** [comment]
@ecraig12345  @TristanWatanabe 
Is there any update on this ?

**Comment by lucas-stanford** [comment]
I believe it's fixed with this PR: https://github.com/microsoft/fluentui/issues/20135

**Comment by ecraig12345** [comment]
Yes, this is fixed now. You can verify by opening the codepen link (which will use the latest version by default).
