### ISSUE TITLE
consistent-callback-args throws an error when given a value with a tuple type

### ISSUE THREAD

**Issue by czearing** [microsoft/fluentui#19978]
### Summary

When using isConformant:

```jsx
  isConformant({
    Component: MyComponent,
    displayName: 'MyComponent',
  });
```

An error is thrown by the `consistent-callback-args` test when it receives a value containing a tuple type:

### Example
This works:

```jsx
  onChange?: (
    ev: React.PointerEvent<HTMLDivElement> | React.KeyboardEvent<HTMLDivElement>,
    data: { value: number[] },
  ) => void;
```

![image](https://user-images.githubusercontent.com/7192338/134748848-da6d8d2d-2a19-4090-9f06-56fc92b95b5f.png)

However this throws an error:

```jsx
  onChange?: (
    ev: React.PointerEvent<HTMLDivElement> | React.KeyboardEvent<HTMLDivElement>,
    data: { value: [number, number] },
  ) => void;
```

![image](https://user-images.githubusercontent.com/7192338/134748895-ad8d6a36-3b45-44f7-8553-f01d19bf10c3.png)

**Comment by layershifter** [comment]
This happens because [`getCallbackArguments()`](https://github.com/microsoft/fluentui/blob/341b9334e4354f666c5d3bf1000a7a5305ce021a/packages/react-conformance/src/utils/getCallbackArguments.ts) does not handle tuples.
