### ISSUE TITLE
FluentUI Panel - Allow option for "non-sticky" Pivot/Panel Header 

### ISSUE THREAD

**Issue by PeterWCox** [microsoft/fluentui#19986]
#### Describe the feature that you would like added

Add option to turn off "Sticky Header"

#### What component or utility would this be added to

Panel 

#### Have you discussed this feature with our team, and if so, who

No 

#### Additional context/screenshots

IMO we should be able to turn off the sticky header especially when we are using custom content like in the below screenshot. 

![image](https://user-images.githubusercontent.com/51972024/134788509-b86951b1-c3ef-40a0-931f-30d3db67cb58.png)

I am able to disable it in the chrome devtools as below 

![image](https://user-images.githubusercontent.com/51972024/134788531-b74204e7-8d8c-4b8f-8333-6b790181f75d.png)

I'm sure its possible to change this using the IPanelStyles property but am struggling to find a way to do it as the "stickyness" comes from a frustrating media query 

Any help would be appreciated - by the way thanks for making such an awesome and easy to use front-end framework.

**Comment by PeterWCox** [comment]
I eventually managed to fix the issue using some very ugly CSS - hopefully someone finds it useful or at least solves their problem!

![image](https://user-images.githubusercontent.com/51972024/134788768-fe8547cc-5887-404e-84cd-1a86e72f8f43.png)

**Comment by gouttierre** [comment]
@PeterWCox - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
However, If you come up with a solution in the interim and would like to submit a PR for this request - our team will gladly review it!

**Comment by PeterWCox** [comment]
@gouttierre thank you - I will see what I can do this week to help out

**Comment by mbest** [comment]
Additionally, the sticky header doesn't set a `z-index`, so the body content shows up over it. It also doesn't use the background color of the main panel (set using `main.backgroundColor`). Thus we get something like this:

![image](https://user-images.githubusercontent.com/1230364/140438775-ac694ed2-4e04-40a8-8f19-5e3ce0565e6c.png)

**Comment by bablu-joshi** [comment]
```
*.ms-Panel-commands{
    z-index: 1;
}
```

This worked for me .!!

**Comment by tudorpopams** [comment]
@bablu-joshi , @PeterWCox do you consider this to be fixed on your side based on the discussion? Can we close this issue?
