### ISSUE TITLE
Dropdown: support customization of Element-type error message

### ISSUE THREAD

**Issue by yangjocy** [microsoft/fluentui#19989]
#### Describe the feature that you would like added

Just like `onGetErrorMessage` of `TextField`, consumer could define their own JSX Elements for error message.
Currently, Dropdown only supports a string-type prop `errorMessage`.

#### What component or utility would this be added to

Dropdown

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Customization example:
![image](https://user-images.githubusercontent.com/11807272/134862358-cd713661-12d6-460c-a36e-fa5bcdfc1d4e.png)

**Comment by DrSammyD** [comment]
I'm designing a component for the Portal framework that generates validations with links for partners to use. It would be great if all controls with validations could have a unified errorMessage typing so these errors can be displayed correctly.

**Comment by omerdolev-ms** [comment]
We're also interested in this feature for inputs other then TextField (dropdown, toggle, combo, choice etc..)
We are using an icon inside our error messages and would like to have all the defaults used by fluent without writing a custom component for it.

**Comment by JustSlone** [comment]
This is not something the core team is working on now, but this is a good opportunity for a contribution and something we'd love to collaborate on.
