### ISSUE TITLE
useCSS missing from @fluentui/react-northstar package

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/fluentui#19994]
Attempting to use `useCSS` as described here: https://fluentsite.z22.web.core.windows.net/0.52.1/styles-overrides

But the latest `@fluentui/react-northstar` has no exported member matching that.

**Comment by gouttierre** [comment]
@Ethan-Arrowood - thanks for filing this issue.

@jurokapsiar -  Would your team be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by jurokapsiar** [comment]
Hi, useCSS was deprecated in #17520 and removed in #18139

Please see #17520 for migration instructions.
