### ISSUE TITLE
Teaching bubble misses the ability to style beak

### ISSUE THREAD

**Issue by IAmJulianAcosta** [microsoft/fluentui#19998]
#### Describe the feature that you would like added

- Teaching bubble component doesn't expose any way to style it (change the background). Background can be modified by using bodyContent styles, but beak background will still be blue

#### What component or utility would this be added to

Teaching bubble

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/1844640/134992495-00955e7a-59ce-4847-8bf1-dc8b65a1f391.jpeg)

**Comment by ecraig12345** [comment]
This is already possible with `ICalloutProps.styles.subComponentStyles.callout.beak`. 
https://codepen.io/ecraig12345/pen/zYzyZqO?editors=0010
```tsx
const calloutStyles: ICalloutProps['styles'] = {
  beak: { 
    background: 'red'
  }
};
const teachingBubbleStyles: ITeachingBubbleProps['styles'] = {
  bodyContent: {
    background: 'red'
  },
  subComponentStyles: {
    callout: calloutStyles
  }
};

<TeachingBubble styles={teachingBubbleStyles} ... />
```

**Comment by IAmJulianAcosta** [comment]
Hi @ecraig12345 , thank you so much! 

I think that this should be a good thing to have in the TeachingBubble docs
