### ISSUE TITLE
Some icons are not cropped properly

### ISSUE THREAD

**Issue by mturoci** [microsoft/fluentui#20025]
### Environment Information

- **Package version(s)**: ^7.175.2 (I believe latest v8 as well)
- **Browser and OS versions**: Chrome Version 93.0.4577.82 (Official Build) (x86_64), but I think it is browser-independent

### Please provide a reproduction of the bug in a codepen:

Codepen: https://codepen.io/mturoci/pen/bGRzRWe?editors=0010

#### Actual behavior:

Currently, some icons are not cropped properly which makes it impossible to render perfectly centered icons.
![Screen Shot 2021-09-29 at 10 53 15 AM](https://user-images.githubusercontent.com/64769322/135236736-acfde5d7-a891-4eab-af11-4d7671852090.png)

#### Expected behavior:

All icons should be cropped to the edge so that perfect centering is possible.
![Screen Shot 2021-09-29 at 10 55 56 AM](https://user-images.githubusercontent.com/64769322/135236744-19a42c5e-4ddb-424e-9376-2312f3bf6588.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: All MS products using Fluent I believe + our product - https://github.com/h2oai/wave

**Comment by gouttierre** [comment]
@mturoci - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.

@bsunderhus - Would you be able to confirm if this is a regression, or if this behavior is an issue with Icons?
cc @tomi-msft

**Comment by khmakoto** [comment]
@gouttierre I think this requires input from design to look at this issue.

@mturoci do you have a list of which icons you've found exhibit this issue?

**Comment by mturoci** [comment]
@khmakoto unfortunately I didn't have time to make a curated list of all the problematic icons.

**Comment by khmakoto** [comment]
@mturoci no worries, thanks for filing the issue either way! 😄

**Comment by mturoci** [comment]
Update: We switched to [svg icons](https://www.npmjs.com/package/@fluentui/react-icons-mdl2) and the problem persists.

**Comment by micahgodbolt** [comment]
MDL2 icon support is highly limited right now, as we are all migrating over to a new, unified set of system icons (https://github.com/microsoft/fluentui-system-icons/tree/main/packages/react-icons)

I believe that even if we could make these changes, the disruption of icons shifting around would not be worth it.
