### ISSUE TITLE
DetailsList Grouped: Allow showing cumulative data (e.g. sum) in nested group header

### ISSUE THREAD

**Issue by harshika-kashyap** [microsoft/fluentui#20027]
#### Describe the feature that you would like added

We need to show cumulative data (e.g. sum, average, etc.) in our nested group header, which should be aligned with the columns. 
Please see the example below:

![image](https://user-images.githubusercontent.com/26279056/135250214-38ae688f-3bfc-47b3-8b15-3945414aabdd.png)

Is there any way I can show the same using DetailsList Grouped control? Right now, I suppose only title is allowed in the group header, like below:

![image](https://user-images.githubusercontent.com/26279056/135252427-4c38e27a-45cd-4740-83ef-2392e3fa4a33.png)

#### What component or utility would this be added to

DetailsList Grouped

**Comment by Ducki** [comment]
You could hook into the headers via the [onRenderDetailsHeader callback](https://docs.microsoft.com/en-us/javascript/api/react/idetailslistprops?view=office-ui-fabric-react-latest#onRenderDetailsHeader). There you could calculate the sums and display them.

**Comment by gouttierre** [comment]
@harshika-kashyap -I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. However, If you come up with a solution in the interim and would like to submit a PR for this request - our team will gladly review it!

**Comment by tonyhallett** [comment]
Hacky - https://codepen.io/TonyH/pen/ZEreEqp?editors=1111

**Comment by tonyhallett** [comment]
Styling needs to be resolved.
https://codepen.io/TonyH/pen/vYdZRpm

Once https://github.com/microsoft/fluentui/issues/23114 has been resolved the overrides fixing group nesting levels will not be required
