### ISSUE TITLE
Focus sometimes not going into Menu upon opening with virtual cursor

### ISSUE THREAD

**Issue by adamsamec** [microsoft/fluentui#20047]
### Description

When the Menu is opened using the screen reader from the virtual cursor mode, the focus sometimes does not move into the menu, and therefore the screen reader does not switch to the forms mode automatically.

### Repro steps

1. Turn on the screen reader (either JAWS or NVDA).
2. Ensure the screen reader is in the virtual cursor mode (by pressing JAWSkey + Z in case of JAWS or NVDA + spacebar in case of NVDA).
3. Using the Down arrow, navigate to the button for opening the Menu and activate it with spacebar.
4. Use the Down arrow key to navigate the Menu.

#### Actual behavior

Sometimes, the keyboard focus does not get into the Menu and the screen reader does not get switched to the forms mode automatically and stays in the virtual cursor mode instead.

#### Expected behavior

The keyboard focus should always move into the Menu upon opening and the screen reader should always get switched to the forms mode afterwards, so that the Menu items could be navigated in cycle, and that the "X of Y" is announced when navigated from one Menu item to another using the Down or Up arrow keys.

**Comment by smhigley** [comment]
We do have an issue like this for v8 as well, which currently has a PR open. I noticed the v8 code had some conditional logic for mouse vs. keyboard opening with different focus targets for each, which is being removed. We should make sure we don't do the same in v9, and that initial focus is not dependent on the event that triggered the menu.

**Comment by ling1726** [comment]
@smhigley do you have a recommendation of focus target for menu open ?

**Comment by ling1726** [comment]
To maintain consistency, the focus should always be on the first menu item, changing this to a bug
