### ISSUE TITLE
Storybook: Fix links between Button docs

### ISSUE THREAD

**Issue by PeterDraex** [microsoft/fluentui#20045]
Button documentation contains links to related components:

> See also: [MenuButton](https://fluentuipr.z22.web.core.windows.net/pull/19983/react-components/storybook/iframe.html?path=/?path=/docs/components-menubutton--menu-button-playground), [ToggleButton](https://fluentuipr.z22.web.core.windows.net/pull/19983/react-components/storybook/iframe.html?path=/?path=/docs/components-togglebutton--toggle-button-playground), [CompoundButton](https://fluentuipr.z22.web.core.windows.net/pull/19983/react-components/storybook/iframe.html?path=/?path=/docs/components-compoundbutton--compound-button-playground)

These links are currently dead. They need to be fixed so they’d lead to the correct component.

**Comment by micahgodbolt** [comment]
tried this quickly, and it seems that linking between stories is better supported in mdx, making this difficult
