### ISSUE TITLE
mousemove event is not fire when <Modal /> is open with React 17

### ISSUE THREAD

**Issue by nancyz1031** [microsoft/fluentui#20073]
### Environment Information

- **Package version(s)**:  FluentUI 8.0.0,  React version 17.0.0
- **Browser and OS versions**: All browsers, all OS

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/NanZhang/pen/WNOWRdv

#### Actual behavior:

please check the codepen link here:
[mousemove event is not fire when Modal is open with React 17](https://codepen.io/NanZhang/pen/WNOWRdv)

#### Expected behavior:

[mousemove event is fire when Modal is open](https://codepen.io/NanZhang/pen/oNwOBPa) (React 16)

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: High
Products/sites affected: Yes
Please contact me at nancyz@microsoft.com. I'd like to provide more information and clarification if needed.

### Potential reason form my investigation
 - The FluentUI Modal component implementation may registered mousemove and called e.stopPropagation() in event handler.
 - In React 16 and earlier, the following document listeners would still receive them even e.stopPropagation() been called, this is the React previous design.
```document.addEventListener("mousemove", (event: Event) => {... });```
 - In React 17, the propagation would stop when e.stopPropagation() been called. See this doc for more details: https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation

In the same ReactJS doc, React team also suggested that pass `{ capture: true }` as the third argument to document.addEventListener, which can fix the issue in the above repo link. However, our team can't use `{ capture: true }`, since our code need call `e.stopPropagation()` in other place of our code. The `{ capture: true }` make all those `stopPropagation()` not working.

**Comment by nancyz1031** [comment]
@bsunderhus , @gouttierre , is there any updates? Please let me know if anything I can help with.

**Comment by maheshkumawat24** [comment]
Facing the same kind of problem, Doing some mouse event operations on a third-party component (Syncfusion react tree view) that is integrated with fluent UI Panel. The fluent UI panel affects the document events which will prevent mouse event operations.
This started failing after upgrade to react 17.

**Comment by ksmadhukar** [comment]
I'm facing the same problem. I'm using React v16 with Plotly.js table inside FluentUI Modal but the mouse event like shuffling of table columns is not working. But It works fine when not using Modal.

Please check the link here:
https://codesandbox.io/s/relaxed-kare-e6irs

**Comment by tMathaiou** [comment]
Guys I just had the same issue I fixed by adding `layerProps={{ eventBubblingEnabled: true }}` on Modal element

```
<Modal
    layerProps={{ eventBubblingEnabled: true }}
    isOpen={isModalOpen}
    onDismiss={hideModal}
    isBlocking={false}
></Modal>
```

**Comment by vkoman** [comment]
I have faced the same issue, `@microsoft/applicationinsights-clickanalytics-js` does not work, events are not logged because this plugin is listening to `mousedown` and `keydown` events, but if the event is from `Panel` or `Callout` or `Modal`  they are not raised
`layerProps={{ eventBubblingEnabled: true }}` helps, but is it a final solution?

**Comment by bsunderhus** [comment]
@nancyz1031 does this https://github.com/microsoft/fluentui/issues/20073#issuecomment-1067878030, solve your issue?

**Comment by spmonahan** [comment]
Related: #19299

**Comment by spmonahan** [comment]
> I have faced the same issue, `@microsoft/applicationinsights-clickanalytics-js` does not work, events are not logged because this plugin is listening to `mousedown` and `keydown` events, but if the event is from `Panel` or `Callout` or `Modal` they are not raised `layerProps={{ eventBubblingEnabled: true }}` helps, but is it a final solution?

Glad this helps but it sounds like it doesn't completely resolve your issue. What else do you need for your library to function properly in this case?
