### ISSUE TITLE
Adjust Converged Components signature to use ForwardRefComponent

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/fluentui#20079]
Following up https://github.com/microsoft/fluentui/pull/19923 , every Converged Component should use `ForwardRefComponent`, to avoid type leaking https://github.com/microsoft/fluentui/issues/20071 and to ensure we have a pattern to be followed.

- [x] `@fluentui/react-accordion` https://github.com/microsoft/fluentui/pull/20080
- [x] `@fluentui/react-avatar` https://github.com/microsoft/fluentui/pull/20081
- [x] `@fluentui/react-badge` https://github.com/microsoft/fluentui/pull/20082
- [x] `@fluentui/react-button` https://github.com/microsoft/fluentui/pull/20083
- [x] `@fluentui/react-divider` https://github.com/microsoft/fluentui/pull/20084
- [x] `@fluentui/react-image` https://github.com/microsoft/fluentui/pull/20085
- [x] `@fluentui/react-label` https://github.com/microsoft/fluentui/pull/20086
- [x] `@fluentui/react-link` https://github.com/microsoft/fluentui/pull/19923
- [x] `@fluentui/react-menu` https://github.com/microsoft/fluentui/pull/20087
- [x] `@fluentui/react-popover` https://github.com/microsoft/fluentui/pull/20088
- [x] `@fluentui/react-portal`
- [x] `@fluentui/react-text` https://github.com/microsoft/fluentui/pull/19923
- [x] `@fluentui/react-tooltip` https://github.com/microsoft/fluentui/pull/20089
- [x] `@fluentui/react-input` https://github.com/microsoft/fluentui/pull/19923
- [x] `@fluentui/react-card` https://github.com/microsoft/fluentui/pull/20090
- [x] `@fluentui/react-slider` https://github.com/microsoft/fluentui/pull/20091
- [x] `@fluentui/react-checkbox` https://github.com/microsoft/fluentui/pull/20092
- [x] `@fluentui/react-switch` https://github.com/microsoft/fluentui/pull/20093

**Comment by layershifter** [comment]
All PRs are merged. @bsunderhus can be this closed?
