### ISSUE TITLE
Popup cannot be dismissed if ESC was used to close the tooltip

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#20070]
When tooltip is inside of the Popup, ESC only closes the tooltip but does not close the popup after second keypress.

Repro steps:
1. open https://codesandbox.io/s/8ikyx?module=/example.js
2. navigate to button with focus trap, press enter
3. navigate to Click here using Tab
4. Press esc to dismiss tooltip
5. Press esc to dismiss popup

Expected: after 4, tooltip closes, after 5 popup closes
Actual: after 4, tooltip closes, after 5 popup stays open

**Comment by gouttierre** [comment]
@jurokapsiar -  Would your team be able to confirm if this is a regression, or if this behavior is an issue?
