### ISSUE TITLE
Search Box: Allowing link inside search box

### ISSUE THREAD

**Issue by harshika-kashyap** [microsoft/fluentui#20100]
#### Describe the feature that you would like added

Is there any way, we can achieve this?
![image](https://user-images.githubusercontent.com/26279056/135904534-fea18da9-afe1-4a6a-8a5f-9fdc96bc7f34.png)

#### What component or utility would this be added to

Fluent UI SearchBox

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
