### ISSUE TITLE
Iframes inside FocusTrapZone do not follow sequential focus order

### ISSUE THREAD

**Issue by taurheim** [microsoft/fluentui#20116]
### Environment Information

- **Package version(s)**: 8.36.1
- **Browser and OS versions**: Win10, Edge

### Describe the issue:

When there is an iframe within a FocusTrapZone, focus enters the iframe normally, but upon exit the FocusTrapZone resets focus.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/taurheim/pen/VwWJvGX

1. Turn on the trap zone
2. Tab through the iframe until the last element ("Rerun")
3. Press tab again

#### Actual behavior:
Focus goes back to the start of the focus trap

#### Expected behavior:
Focus should go to "Hyperlink inside trap zone"

### Documentation describing expected behavior
See https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html as one example (this issue repros in the Dialog component). See also https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html

**Comment by gouttierre** [comment]
@taurheim  - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@khmakoto  - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley

**Comment by khmakoto** [comment]
Hi @gouttierre @taurheim, this happens because we do not have support for iframe related content in the `FocusTrapZone` component. Adding such a support would be a feature that would require some time investment on our part so I am not sure when we will get to it given other priorities we have at the moment.

**Comment by taurheim** [comment]
@khmakoto Is this documented somewhere? Do you have an idea of what approach would be best to tackle this if our team were to attempt to fix this?
