### ISSUE TITLE
Tooltip always labels the component that triggered it

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#20115]
The `Tooltip` component is, by default, applying its content as the `aria-label` of its trigger. This should not happen by default and be opt-in functionality.

**Comment by jurokapsiar** [comment]
@behowell, @khmakoto I think this should be closed as 'by design'. Do you think it should be changed?

**Comment by behowell** [comment]
@khmakoto I'm going to close this as by design, per @jurokapsiar's comments. Let me know if you disagree.
