### ISSUE TITLE
vNext beta bug bash: Menu

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#20129]
## Bug Bash
- Reviewed storybook UI for menu for visual appearance and behavior
- Reviewed storybook documentation
- Experimented with storybook controls 

## Issues Found

- Docs:
- [ ]  Typo:  Don't use verbose secondary content for menuitems. => menu items.

Default story: 
- [ ] Nit: Button named 'Toggle Menu' could be confusing with people familiar with the Toggle control in v8.  Consider 'Menu'
- [ ] Nit: Default vs Interaction seem extra vs. the default showing the actions happen when menu items are clicked

Groupping Items:
- [ ] Typo: Should be Grouping Items

Controlled Checkbox Items, Controlled Radio Items, Nested Submenus Controlled:
- [ ] Nit: Can't really tell they are controlled the way you can with 'Controlling Open and Close'

Anchor to Custom Target:
- [ ] Idea: Something other than a button as the custom target.
 
Custom Trigger, Render Function Trigger:
- [ ] Unclear what is being demonstrated here

Memoized Menu Items:
- [ ] Nit: Can't tell what is being memoized.  Consider something like a timer that is updating menu items and an on/off of memoization.

Trying out via StoryBook controls:
- [ ] Once user tries out the 'open' option, then later the openOnContext and openOnHover options won't work even when the 'open' option is set back to false.  
- [ ] When using openOnHover, hover button => menu opens, then move mouse off button => menu closes.  However if hover button => menu opens then move mouse over menu item then move mouse off of menu item => menu does not close.  
- [ ] When using openOnContext the menu is positioned relative to where the mouse clicked.  This should follow the positioning behavior.
- [ ] Consider renaming hoverDelay to openOnHoverDelay - to associate the delay with that particular hover setting.  Could be confused with a hover delay to open submenus? (do submenus have their own delay setting?)
- [ ] The hoverDelay default value needs to be documented.  The storybook control defaults to zero, but when adjusting to 1 and back to 0 the default delay goes away and the hover to open is instant.
			
Accessibility:
- [ ] When clicking to open menu, then down arrow => nothing happens (or page scrolls slightly), 2nd down arrow selects first menu item.  Bug?
- [ ] Question: When position is above, only the down arrow opens the menu.  Should this ever allow for up arrow to open the menu?  What about left/right arrows?

**Comment by gouttierre** [comment]
@miroslavstastny - I moved this menu bug to your backlog according to the focus areas ownership.
