### ISSUE TITLE
Can't find the SharePoint icon in react-northstar

### ISSUE THREAD

**Issue by plamber** [microsoft/fluentui#20125]
Hello,
I was looking through the icons of react-northstar and I was not able to locate the icon for SharePoint. I was able to find multiple product icons such as Teams, OneDrive or Outlook but not SharePoint.

Could somebody guide me to the right path? Has this icon been forgotten?

Thank you,
Patrick

**Comment by plamber** [comment]
@notandrew: thank you for the feedback. I am wondering were we could get the office icons in future? There are applications that need to reference to other Office "services". Having icons would help

Thank you for your feedback

**Comment by notandrew** [comment]
@plamber I wish I had better news, but it looks like there's currently nothing available. This is all that I could find, and it doesn't appear to be helpful:
https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks

**Comment by plamber** [comment]
I see, thank you.

**Comment by plamber** [comment]
Hi @notandrew,
this page says that we can use these https://developer.microsoft.com/en-us/fluentui#/styles/web/office-brand-icons. Not sure if I am misinterpreting it.

Thank you for your feedback,
Patrick

**Comment by notandrew** [comment]
I haven't seen that - I'll investigate. Thanks!

**Comment by notandrew** [comment]
🤷‍♂️
