### ISSUE TITLE
react-tooltip: Cannot focus interactible elements within Tooltips

### ISSUE THREAD

**Issue by varholak-peter** [microsoft/fluentui#20127]
### Environment Information

- **Package version(s)**: `@fluentui/react-tooltip@9.0.0-beta.1
- **Browser and OS versions**: Edge v94, MacOS

### Describe the issue:

Although the dedicated component for displaying interactible elements is supposed to be `react-popover`, the `react-tooltip` component allows rendering of any custom content, therefore we should ensure that content rendered this way is keyboard accessible to users.

#### Example
Content for the tooltip is provided via CMS and user enters a link as part of the content, however this link won't be accessible for a keyboard only user as the Tooltip does not stay open while focus is within the rendered content.

### Please provide a reproduction of the issue in a codepen:

I created a CodeSandbox link instead of Codepen because I didn't know better. ¯\\\_(ツ)_/¯

https://codesandbox.io/s/quirky-parm-7suoe?file=/src/App.js

#### Actual behavior:

Tooltip content disappears once interactible element within Tooltip content gets focused.

#### Expected behavior:

Tooltip should stay open if the focus is within the content rendered by Tooltip.

**Comment by jurokapsiar** [comment]
as per ARIA practices (https://www.w3.org/TR/wai-aria-practices-1.2/#tooltip) 

> Tooltip widgets do not receive focus. A hover that contains focusable elements can be made using a non-modal dialog.

So we can either make Tooltip component really smart and handle this case, or we can have a note in the docs that if anything focusable needs to be inside, Popover should be used.

**Comment by kidokidozh** [comment]
Having same issue here. Is there any suggestion on a workaround?

**Comment by scottaohara** [comment]
fwiw @jurokapsiar, would agree that documentation be provided that a tooltip is not expected to have nested interactive content, and if that's what the situation calls for, then a tooltip is likely not the correct component to be using.

**Comment by smhigley** [comment]
I think it'd be a good call to have our docs for Tooltip explicitly recommend a dedicated expand/collapse button + popover in cases where long, structured, or interactive content is used within a tooltip-like thing.
