### ISSUE TITLE
vNext beta bug bash: Avatar

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#20130]
## Bug Bash
- Reviewed storybook UI for menu for visual appearance and behavior
- Reviewed storybook documentation

## Issues 

Default:
- [ ] Should the initials be user selectable?  It changes the cursor to text insertion caret when hovering.
Shape:
- [x] Nit: The other examples show initials, icon, and photo.  Photo isn't included in the shape permutations

Badges:
- [x] Nit: The away X is super light (low contrast) on the badge

Robot Examples:
- [x] Unclear why this story is here.  Custom SVG icon?

Docs:
- [x] No storybook controls in table of properties
- [x] getInitials - is there a default implementation that uses first letter of words/capitalization?
- [x] image - 'The Avatar's image. Cannot be typed as a normal slot since it should not accept any children but can accept a children render function.'.  =>  The 'since it should not accept' is a confusing.
- [x]  No stories for label
- [ ] Is there a common scenario for when callers want the avatar to be slotted as the content for a button?

**Comment by miroslavstastny** [comment]
v9: potential API change, to be reviewed this week
