### ISSUE TITLE
vNext Design Bug Bash: Label vNext bug bash

### ISSUE THREAD

**Issue by yvonne-chien-ms** [microsoft/fluentui#20139]
#### Current
Red required asterisk uses `colorPaletteRedForeground3`. The dark theme color could become problematic quickly since the red doesn't have much contrast against dark backgrounds.

#### Requested update
Use `colorPaletteRedForeground1` for red required asterisk for higher contrast in both light and dark themes.

#### Priority
Normal

**Comment by behowell** [comment]
Split into separate issues. The second half was split to: #20591

**Comment by bsunderhus** [comment]
@behowell , can this be closed?

**Comment by behowell** [comment]
@bsunderhus This is assigned to @tomi-msft and he just opened a PR to fix it.

**Comment by tomi-msft** [comment]
See #20906
