### ISSUE TITLE
Tooltip position relative to mouse position

### ISSUE THREAD

**Issue by vkoman** [microsoft/fluentui#20147]
#### Describe the feature that you would like added

I'm using a `<Text>` component wrapped in `<TooltipHost>`. And when I hover over a text, the tooltip position by default is the top-center of the screen.

Is it possible to have some tooltip `auto` position detecting by the mouse cursor?

So to show the tooltip in the positions where I hover a mouse (same as browser tooltip has).

The current behavior looks good for long text (I mean to show a tooltip at the middle of the screen), but for the short tests, it looks not good.

#### What component or utility would this be added to

`<TooltipHost>`

#### Have you discussed this feature with our team, and if so, who

no

#### Additional context/screenshots
![image](https://user-images.githubusercontent.com/8247394/136408849-77664db0-dbe8-4f17-8a55-1de82ffbd88d.png)

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
