### ISSUE TITLE
Project: Finish Input implementation

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#20159]
### Problem

Input (text input), Checkbox, Switch, and Slider have been written to varying degrees but are not yet included in the v9 beta.

### Appetite

November

### Solution

- [x] Primary slot prop splitting helper
- [ ] Finish Input implementation
  - [x] update spec #20035
  - [x] update implementation so far based on spec #20036
  - [x] ~~bookends~~ deferred
  - [x] focus/hover styling #20648
  - [x] primary slot #20863
  - [ ] review with design
  - [x] general code/patterns review
  - [ ] docs

Other input components are tracked by separate issues:
- [x] #20589
- [ ] #20590
- [ ] #20562

### Risks (Rabbit holes)

RangedSlider may require additional work (compared to the other listed components) to get ready for beta. It can probably be cut from the scope if needed unless there's immediate demand from a partner.

Other risks TBD

### Out of scope (No-gos)

Aside from the specific Input features listed above, this project does NOT include implementing additional features in any of the components.

Related components/patterns that are in progress in November but NOT covered in this proposal and probably not expected to be ready for beta by end of month:
- Field
- Radio
- Dropdown

**Comment by behowell** [comment]
@ecraig12345 I've split this into separate issues for each component, and scoped this issue to track only the input work. This way each issue has a single owner and tracks a single component.

**Comment by ecraig12345** [comment]
### What was achieved?
- Add interaction styling
- Change `fieldSize` prop name back to `size` (so we have the same prop name across components)
- Add screener tests
- PR for primary slot and `onChange`

### What did we miss?
- Merging PR for primary slot and onChange
- Add stories

### What went well?
- The styles are finally updated!
- We decided on a consistent name for "visual size" prop across components

### What could have gone better?
- Didn't get as much done due to non-work obligations, getting sick, and build fires
- Some rabbit holes of making fixes to vr-tests infrastructure

### What changed from initial expectations?
- Non-work obligations this month took longer than expected, taking away from this project
