### ISSUE TITLE
NPM feed down?

### ISSUE THREAD

**Issue by jef1771** [microsoft/fluentui#20150]
### Environment Information

- **Package version(s)**: all versions
- **Browser and OS versions**: all browsers

### Describe the issue:

NPM feed is not showing, errors when trying to npm install

#### Actual behavior:

errors when trying to install

#### Expected behavior:

no errors, and ability to access npm page

Requested priority: High

Products/sites affected: (if applicable)
https://www.npmjs.com/search?q=fluentui

**Comment by khmakoto** [comment]
@jef1771 I don't think this is an issue anymore, could you double-check?
