### ISSUE TITLE
[Dropdown] defaultHighlightedIndex prop works only upon first opening

### ISSUE THREAD

**Issue by petrjaros** [microsoft/fluentui#20154]
### Environment Information

- **Package version(s)**: 0.59.0
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluent-ui-example-forked-chfl9?file=/example.js:356-379

#### Actual behavior:

1. Open the dropdown -> the item is correctly highlighted
2. Close the dropdown
3. Open the dropdown -> the item is not highlighted

#### Expected behavior:

The item from defaultHighlightedIndex should be highlighted no matter how many times user opens the dropdown.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@jurokapsiar- Would your team be able to confirm if this is a regression, or if this behavior is an issue?
