### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by t-lji** [microsoft/fluentui#20164]
Duplicated "a"

https://github.com/microsoft/fluentui/blob/dab45a2afe609709735b9b6e604a1af40d50e809/packages/fluentui/react-northstar/src/components/Breadcrumb/Breadcrumb.tsx#L46

https://fluentsite.z22.web.core.windows.net/0.59.0/components/breadcrumb/definition

**Comment by tinatae** [comment]
Hello, I'd like to contribute to this repo but in the spirit of doing things correctly, I was wondering if I could take this issue to practice? I see this is already assigned to someone but.. it seems like every issue is assigned to the same person so I just thought I'd ask.

**Comment by tinatae** [comment]
@khmakoto Awesome! Thank you!
