### ISSUE TITLE
vNext: Button w/ icon, icon before sitting 1px high for Medium Variant

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#20174]
**Current:**
![image](https://user-images.githubusercontent.com/48726002/136628289-9b1afdc0-fa75-445e-a1e5-96c6a7f18cf4.png)
![image](https://user-images.githubusercontent.com/48726002/136628423-06daef06-a745-4669-8847-6ed4f7e90af7.png)

**Environment:**
https://fluentuipr.z22.web.core.windows.net/heads/master/react-components/storybook/index.html?path=/story/components-togglebutton--toggle-button-playground

-------

**Change Request:** 
Icon before shift down by 1 px for Medium Variant
![image](https://user-images.githubusercontent.com/48726002/136628618-1533a2d7-7d02-40dd-9ab8-9603ee6ca8f7.png)

**Comment by khmakoto** [comment]
Confimed with @daisygeng that this is not an issue anymore, closing.
