### ISSUE TITLE
vNext Medium and Small Variant button Icon:before size too large

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#20175]
**Current**
![image](https://user-images.githubusercontent.com/48726002/136628927-dfe69daf-1238-46e7-9e38-381fee2054c7.png)
Environment: https://fluentuipr.z22.web.core.windows.net/heads/master/react-components/storybook/index.html?path=/story/components-button--button-size

**Change Request**
Medium and Small Variant button should use "**(Icon name) 20_regular**" 
![image](https://user-images.githubusercontent.com/48726002/136629617-24412d38-abfd-4f90-8685-691ef48ed15d.png) 
![image](https://user-images.githubusercontent.com/48726002/136629655-08a2e702-112c-469b-86ae-0b5ebc2a5073.png)

Referencing this for icon naming convention:
https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md

**Comment by khmakoto** [comment]
This has already been fixed, closing.
