### ISSUE TITLE
Badge border-colors on tint variation are incorrect

### ISSUE THREAD

**Issue by kaylieghdavis** [microsoft/fluentui#20188]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen: 

https://codesandbox.io/s/39lxv?file=/example.tsx

#### Actual behavior:

Tint colors are much darker than the expected styles on borders - mainly Brand, Danger, 

#### Expected behavior:

Tint colors should map to the correct tokens in the design spec, which are much lighter visually than the ones currently in build

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@miroslavstastny - these are related to vNext controls that Design is verifying. I added these to the `react-components v9` project for now

**Comment by ling1726** [comment]
@kaylieghdavis I've managed to use to correct the `brand` border colour design token for the `tint` variation in #20693.

However, The `danger` border colour with `tint` seems to be what is specced which is `red background 2`. The actual colour for that border in figma, is not present in any design token: `#F1BBBD`

![image](https://user-images.githubusercontent.com/20744592/142835827-c5ca87e7-917f-403e-a36b-ea003b4948a7.png)

**Comment by daisygeng** [comment]
Design would like to request adding a token to achieve intended visual effect here (@miroslavstastny)

Adding "<Shared color> Border 1"
![image](https://user-images.githubusercontent.com/48726002/144312550-2d90a1cc-a761-4ea3-aec9-6154f284db95.png)

In badge spec, border could point to that 
![image](https://user-images.githubusercontent.com/48726002/144312507-e9192edc-fb33-4b85-bb10-2de2283328c7.png)
