### ISSUE TITLE
Badge spacing is inconsistent for icon only and text only badges with 1 or more characters

### ISSUE THREAD

**Issue by kaylieghdavis** [microsoft/fluentui#20189]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/k74qf?file=/example.tsx

#### Actual behavior:

Icon only and single digit text strings display wider than specified

#### Expected behavior:

Icon only and single digit text strings should have an equal height x width size so that the badge renders as a square or circle and not as a rectangle. Refer to badge spec for min-width and height sizing and spacing guidance

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: high

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@miroslavstastny - these are related to vNext controls that Design is verifying. I added these to the `react-components v9` project for now
