### ISSUE TITLE
React fluent UI - Teams App Theme

### ISSUE THREAD

**Issue by AmNeeraj** [microsoft/fluentui#20185]
### **The following Issue we have faced when tried applying Teams Theme change related changes with fluentui/react component**   

 in a  Microsoft Teams App we tried to implement Theme handling for react fluent component in teams (default/dark/contrast). But this theme change is not applying for fluent components.
We are following this documentation How to apply theme to Fluent UI React components · 
[https://github.com/microsoft/fluentui/wiki/How-to-apply-theme-to-Fluent-UI-React-components#themeprovider-in-preview](url)

we have used Theme Designer [https://fluentuipr.z22.web.core.windows.net/heads/master/theming-designer/index.html](url) to generate Palettes 

 Package version 
"react": "^16.11.0",
"@fluentui": "^8.19.1",

Code Snippet
```ts
import { ThemeProvider, PartialTheme } from '@fluentui/react';

const contrastTheme: PartialTheme = {
  palette: {
    themePrimary: '#ffff01',
    ..
}
}
const darkTheme: PartialTheme = {
  palette: {
    themePrimary: '#9ea2ff,

    ..
}
}
 <ThemeProvider applyTo="body" theme={theme === 'dark' ? darkTheme : (theme==="contrast" ? contrastTheme: lightTheme)} >
```

<DetailsList></DetailsList>

</ThmemeProvider>

Please Provide suggestion for React fluent Teams Theme Handling.

**Comment by gouttierre** [comment]
@AmNeeraj  - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows and the developer might need to pair with you on problem depending on the outcome. 

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue? You might need to get InTouch with AmNeeraj from the Microsoft Teams App to debug the code.

**Comment by khmakoto** [comment]
Hi @AmNeeraj, this should be working, do you have a minimal repro in a codepen or codesandbox I could look at with the issue? I've been unable to replicate this in my local environment unfortunately.
