### ISSUE TITLE
PowerBILogo in FluentUI library needs to be updated to the latest

### ISSUE THREAD

**Issue by ni-micro** [microsoft/fluentui#20184]
Current icon that shows up:
![image](https://user-images.githubusercontent.com/92031326/136735824-38b814cb-63b0-4e18-bb8d-50e5b2488710.png)

We should be using:
![image](https://user-images.githubusercontent.com/92031326/136735791-216b615a-7810-4294-afe8-dddf5405a12d.png)

**Comment by gouttierre** [comment]
@ni-micro - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. 

@khmakoto - Would you be able to review and confirm the icons used for PowerBI?
cc @tomi-msft

**Comment by ni-micro** [comment]
My understanding from [Peter's reply](https://github.com/microsoft/fluentui/pull/12088#issuecomment-621505621) is that we are not actively adding new icons to Fluent UI, but we should at least maintain the latest on any updated icons.
