### ISSUE TITLE
counterBadge doesn't require full set of colors from baseBadge

### ISSUE THREAD

**Issue by kaylieghdavis** [microsoft/fluentui#20192]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/92wvz?file=/example.tsx

#### Actual behavior:

counterBadge includes all color variants in it's examples - some of those examples are also incorrect. i.e. Warning uses red bgColor and darkGray foreground color 

#### Expected behavior:

counterBadge should only include color variants for brand, danger, important and informative
### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@miroslavstastny - these are related to vNext controls that Design is verifying. I added these to the `react-components v9` project for now
