### ISSUE TITLE
Incorrect icons being used in presence badges

### ISSUE THREAD

**Issue by kaylieghdavis** [microsoft/fluentui#20191]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/o4uko?file=/example.tsx

#### Actual behavior:

Some of the icons - Offline in particular seems to be using an incorrect glyph for presence

#### Expected behavior:

Badge should be using the new Fluent icons - size 10 in this example

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: High

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@miroslavstastny - these are related to vNext controls that Design is verifying. I added these to the `react-components v9` project for now
