### ISSUE TITLE
 Fluent UI React detaillist bug in selection when filtering #18306  closed without solution

### ISSUE THREAD

**Issue by G00golplex** [microsoft/fluentui#20209]
### Environment Information

- **Package version(s)**: Fluent UI React
- **Browser and OS versions**: Web controls

### Please provide a reproduction of the bug in a codepen:
this is not necessary. Just go to this URL:

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic

and try to select items with the help of the search option
 I already posted this but somebody asked if I had a solution? I thought that the developers who create such code examples are the ones who should solve it? After that reply, the GitHub bot was very quick with closing the issue. Is this the way that bug reporting is handled? Or

#### Actual behavior:
If you clear the search bar, the selection is cleared. and if have selected a property it is checked as the first item. If your other search query is on the first position, you can deselect the item from last search and only select the first item again. So there is no use in the search console only if you want to select one property.

#### Expected behavior:
That I can search for an item, check the checkbox, clean the search bar, search another item and add it to the selection

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking,

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@G00golplex - Thanks for filing this issue with us and sorry about the frustration caused. The team will investigate this issue but to set expectations the developers will only review this issue once capacity allows. 

@khmakoto  - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by G00golplex** [comment]
Dear,

thanks for your reply. I hope there will be some resources to correct the
bug.

kind regards,
