### ISSUE TITLE
v8 upgrade script randomly nuked that contents of ~24 files in our repo.

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#20206]
We ran the code mods to upgrade admin-controls to v8 ([per instructions in the migration guide](https://github.com/microsoft/fluentui/wiki/Version-8-migration-guide#using-codemods)).

It destroyed the contents of a bunch of files with no rhyme or reason.

I was on Windows 10 when running the script. Node v14.17.5

Since this is an internal repo, I can't provide the link here, but am happy to via internal channels.

**Comment by JustSlone** [comment]
@GeoffCox, I assigned this to you to either address in term of migration, or close out as not relevant. Feel free to reach out to Mason for more information.

**Comment by GeoffCoxMSFT** [comment]
Asked Mason and it maybe have been specific to his machine setup at the time.  I didn't have issues when running code mods across odsp-web, so I'm going to close this for now.  It can be reopened if another partner encounters it.
