### ISSUE TITLE
Using keyboard navigation in Pivot's overflow menu shows UI artifacts

### ISSUE THREAD

**Issue by jayantdhawan** [microsoft/fluentui#20218]
### Environment Information

- **Package version(s)**: Fluent 8
- **Browser and OS versions**: Microsoft Edge, Windows 11

### Please provide a reproduction of the bug in a codepen:
1. Use the 'Export to CodePen' option on the Pivot control's example on using the overflow menu. 
2. Resize the browser so that multiple items move into the overflow menu.
3. Use the keyboard to navigate through the Pivot tabs inside the menu.

#### Actual behavior:
Focusing on a tab item inside the menu shows some UI artifact that looks like a tooltip.
![image](https://user-images.githubusercontent.com/8561626/137418913-e0ec770b-1191-4d23-a6d5-41ddc3278937.png)

#### Expected behavior:

Navigation should work without the UI artifacts. 

### Priorities and help requested:

Are you willing to submit a PR to fix? Sorry, not at this time.

Requested priority: Normal

Products/sites affected: NA

**Comment by jayantdhawan** [comment]
@bsunderhus Checking in to see if this will be taken up anytime soon?

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [Pivot](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/pivot) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
