### ISSUE TITLE
Facepile - Tooltip does not render on KeyboardFocus

### ISSUE THREAD

**Issue by QSim28** [microsoft/fluentui#20215]
### Environment Information

- **Package version(s)**: ^7.174.0
- **Browser and OS versions**: Chrome (v 94.0.4606.81), Firefox (v 93.0), Edge (v 94.0.992.47)

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/facepile-tooltip-onfocus-forked-5ysxv?file=/src/App.tsx
https://codepen.io/QSim282/pen/xxLVoJL

#### Actual behavior:

Using `Tab` to focus wont cause Facepile tooltip to render (in Chrome and Firefox)
Arrow keys may not be used to iterate focus through Personas in Facepile
#### Expected behavior:
Using `Tab` will cause Facepile tooltips to render (and the Overflow icon!).
Using `Ctrl` will dismiss the tooltip
Support for arrow keys to iterate focus through all Personas in Facepile

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)
Blocking (A11Y Issue)

Products/sites affected: (if applicable)
Fluid integration in Teams

This issue has been reported before here: https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/11656.
It was marked as fixed, and this seems to be the case for the Edge browser, but Chrome and Firefox still have this issue.
We should test and ensure this and future bugfixes works for all browsers 

Additional Notes: Notice we override the default Tooltip provided by Facepile, opting for our own custom tooltip that is implemented by a `TooltipHost`. We would like to ensure any fix will be applicable to this scenario as well.

**Comment by gouttierre** [comment]
@QSim28 - thanks for filing this issue. This was fixed in v8 by #19137.
Please use the later version.
