### ISSUE TITLE
v9 codemods should be in a separate package

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#20222]
Recently some v9 codemods were added to the v8 `@fluentui/codemods` package. This seems likely to create all kinds of problems (it already created a problem with releases), so really it would be better to have v9 mods in a separate package. The infrastructure could potentially just be duplicated for now since we'll probably want to rewrite it in the future anyway.

**Comment by TristanWatanabe** [comment]
Looks like there's no more v9 specific codemods present in this package - It was removed by #21201
