### ISSUE TITLE
Tooltip may trigger unexpected scroll bar

### ISSUE THREAD

**Issue by Jing29** [microsoft/fluentui#20250]
### Environment Information

- **Package version(s)**: latest one
- **Browser and OS versions**: chrome latest

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/herbix/pen/JjyKYqM

#### Actual behavior: Hover on the tooltip, unexpected scroll bar is shown
![image](https://user-images.githubusercontent.com/19400548/137874329-8d85462f-9404-42e7-a75a-10440e0e2378.png)

![scroll-bar-issue-1019-fluent-ui](https://user-images.githubusercontent.com/19400548/137873724-4edd9b92-9da2-45c6-abd5-9706e2d58f73.gif)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
High

Products/sites affected: (if applicable)
[Azure Synapse Analytics](https://azure.microsoft.com/en-us/services/synapse-analytics/#overview)

**Comment by els-ts** [comment]
@gouttierre @bsunderhus - any updates on this one? We're experiencing similar issue within our application 😞

**Comment by Rafaelki** [comment]
Setting the position of the parent component (to the TooltipHost) to relative didn't exactly work for me by itselft.
I had to put a div wrapping the TooltipHost with position relative and then set the position absolute and top=0 to the TooltipHost:
`const styles: Partial<ITooltipHostStyles> = { root: { position: 'absolute', top: 0 } };`
