### ISSUE TITLE
Tokens parameter not found on Stack in 8.37.0

### ISSUE THREAD

**Issue by mkholt** [microsoft/fluentui#20277]
### Environment Information

- **Package version(s)**: 8.37.0
- **Browser and OS versions**: All

#### Actual behavior:
Attempting to add the `tokens` parameter to a `Stack` component results in the following compile-time error:
`Property 'tokens' does not exist on type 'IntrinsicAttributes & IStackProps & { children?: ReactNode; }`

The error does not occur on version 8.36.5

#### Expected behavior:
The `tokens` parameter should still be available to the `Stack` component

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: N/A

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [Stack ](https://developer.microsoft.com/en-us/fluentui#/controls/web/stack) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
