### ISSUE TITLE
DetailsList can still be selected in SelectionMode.None via keyboard

### ISSUE THREAD

**Issue by brandonthomas** [microsoft/fluentui#20272]
### Environment Information

- **Package version(s)**: Seems to be in v7 and v8

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/brandonthomas/pen/RwZRYjO
- Open pen
- Go to the configure menu, select none for selection mode.
- Tab until you are focused on the header
- Press arrow down

Expected: Focus is on the first row but no selection
Actual: Focus is on the first row AND it's selected.

This also might be an accessibility bug since it is only reachable via keyboard.

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by gouttierre** [comment]
@brandonthomas - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. 

@khmakoto  - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley
