### ISSUE TITLE
Same commit hash and PR link being used for all changes in changelogs/release notes

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#20288]
In the notes for github releases ([example](https://github.com/microsoft/fluentui/releases/tag/%40fluentui%2Freact-components_v9.0.0-alpha.115)) it's using the same PR number for all the changes. Not sure if this is just for grouped release notes or in all cases. EDIT: this is also an issue in changelogs
![duplicates in release notes](https://user-images.githubusercontent.com/5864305/138317914-8ac9f09f-8c17-47f6-bf29-fadcb9834d4b.png)

**Comment by ecraig12345** [comment]
Actually it's a beachball bug, very likely specific to grouped changelogs :(
![image](https://user-images.githubusercontent.com/5864305/138319340-3a61592e-f146-452e-b658-dcc83c6b79d7.png)

**Comment by ling1726** [comment]
@ecraig12345  this is a duplicate of #19932

**Comment by ecraig12345** [comment]
@ling1726 Oh sorry, I thought I'd seen an issue for this but it didn't come up with any search I did
