### ISSUE TITLE
minimize build output

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#20287]
review our current packages (react-components) and create a list of tasks + priorities for RC and after

**Comment by miroslavstastny** [comment]
Will break deep imports. That should not be a breaking change as we do NOT support partners to use deep imports on v9.

**Comment by layershifter** [comment]
We have recent experience with Rollup in Tabster repo. There was again chunk of code that Terser can't remove properly. That cost us 2KB gzipped in terms of bundle size, that is actually 10%.

The "fix that fixed it" was absolutely unobvious: https://github.com/microsoft/tabster/pull/96

**Comment by ecraig12345** [comment]
I'm not convinced that we need to bundle to a single file, and certainly not convinced that we need to prioritize it. There are a lot of challenges related to tree shaking which would require both initial investment and continuous monitoring to ensure we didn't introduce any new non-tree-shakeable code. I think it's also a relatively uncommon setup for a library of our size/complexity (though that would need more research to confirm).

What we should definitely do (which I'm guessing was the original intent of this issue) is look at which files are included in the packages, and verify that it's the minimal set of files needed. We should be at a pretty good state with this after various updates to .npmrc files, but it's worth checking again before release.

**Comment by Hotell** [comment]
single file rollup is the common approach of core frameworks and libraries which comes with important features like:

- not exposing private API's
- faster installs
- faster processing in user tooling

I did thorough research on this topic, as from experience doing decisions based on feelings/opinions is usually the wrong approach.

Here are the results: https://github.com/Hotell/fluentui/blob/hotell/experiments/bundling-bench/packages/react-menu/BUNDLE-BENCH.md

## summary: 

at the moment we will not bundle production code within packages. but should definitely re-evaluate as tree shaking and tools will become more mature.

What we should do is:

- ship only rolluped types
- enable downleveling of types with proper window support clearly communicated to consumers


TODO: spin new issues for those outcomes and after that close this one
