### ISSUE TITLE
In Concepts/ Developers/ Positions, the example doesn't layout properly when in the docs section.

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#20293]

**Comment by GeoffCoxMSFT** [comment]
![image](https://user-images.githubusercontent.com/28762486/138360705-9b66dd9b-4601-46b4-b44c-2b968652eefa.png)

**Comment by layershifter** [comment]
I checked recent deployment and it works perfectly even on small screens (due scroll on horizontal axis):

![image](https://user-images.githubusercontent.com/14183168/144082382-cb8bde2a-6bf1-444e-874d-ee4d9a0ae8b0.png)

---

Closing for now, but feel free to reopen if I missed something.
