### ISSUE TITLE
root .storybook/babel.plugin.js deletion breaks VR tests

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#20309]
hmm looks like I'm running into same issue like Peter (https://github.com/microsoft/fluentui/pull/20126) - (VR tests are filing) when deleting the `babel.plugin.js` file, meaning it is still probably being used somehow, although based on Peter comment it's not 
> This is a left-over file which is not being used. Instead, we use the (same) plugin which is being exported from storybook-addon-export-to-codesandbox, here:
https://github.com/microsoft/fluentui/pull/19583/files#diff-cafe2123a72c4ce3a9f7e9ee4b0e188256eb02d7ec1e54fa2cadfac99b22f92bR62

We'll need to do more investigation to resolve the issue.

>  ![2021-10-21 at 18 29](https://user-images.githubusercontent.com/1223799/138319295-0e60cd6e-179c-4b00-b907-c63e346447d0.png)

_Originally posted by @Hotell in https://github.com/microsoft/fluentui/issues/20283#issuecomment-948781075_

**Comment by layershifter** [comment]
Just CI flakiness, original PR (#20126) was merged.
