### ISSUE TITLE
fluentui-react Allow us to disable animations on the nav

### ISSUE THREAD

**Issue by Pixelatex** [microsoft/fluentui#20310]
#### Describe the feature that you would like added

We simply don't want the navbar to slide in. We would just like it to there, no animation
Some option to disable animation via props or via the styles would be nice..

#### What component or utility would this be added to

<Nav />

#### Have you discussed this feature with our team, and if so, who

no

**Comment by philpoore** [comment]
@Pixelatex I found that adding the following groupContent style to `Nav` component solved the issue for me:
```jsx
<Nav groups={groups} styles={{ groupContent: { animation: 'none' } }} />
```

**Comment by AkiraVoid** [comment]
> `<Nav groups={groups} styles={{ groupContent: { animation: 'none' } }} />`

@philpoore this has no effect when using SSR (**probably** a SSR issue).

**Comment by tudorpopams** [comment]
@AkiraVoid  Have you tried the `renderStatic` method [specified in the docs](https://github.com/microsoft/fluentui/tree/master/packages/merge-styles#server-side-rendering) to get it working in SSR? We also have some documentation on SSR in the Wiki: https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing

**Comment by AkiraVoid** [comment]
@tudorpopams I guess I have, I always follow the guides or docs when I am building something. But it's a long time, and I'm now currently using v9, so I'm not sure.
