### ISSUE TITLE
[GroupedVerticalBarChart] Customize the tooltip of the GroupedVerticalBarChart

### ISSUE THREAD

**Issue by luckyrass** [microsoft/fluentui#20313]
#### Describe the feature that you would like added

We need to customize the tooltip of the GroupedVerticalBarChart with multiple values

![image](https://user-images.githubusercontent.com/12230173/138467359-8a16fc72-ab75-4b80-b2cb-a855a353e590.png)

#### What component or utility would this be added to

GroupedVerticalBarChart

#### Have you discussed this feature with our team, and if so, who

no

**Comment by AtishayMsft** [comment]
This issue has been fixed with [this PR](https://github.com/microsoft/fluentui/pull/20537).
