### ISSUE TITLE
ToolTipHost: clicking on a link inside Tooltip after clicking somewhere inside the Tooltip does not take user to redirection page 

### ISSUE THREAD

**Issue by iron-man14** [microsoft/fluentui#20320]
### Issue
When I hover on a React component, the Tooltip component will appear that has an \<a href={link}\> tag inside it. Before I click on the link, if I click somewhere inside the Tooltip area and then click on the link, the Tooltip disappear and does not take me to the redirection page in another tab.

### Codepen
Here is the link to the codepen for example: https://codepen.io/harryhtet/pen/KKvNMJY

### Example 
Here is a link to the thread in Teams channel that contains gif of what the issue is: https://teams.microsoft.com/l/message/19:86b094239256467da9dfa96ba0897ca2@thread.skype/1634915662909?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=ffe264f2-14d0-48b5-9384-64f808b81294&parentMessageId=1634845213327&teamName=Fluent%20Community&channelName=Fluent%20UI%20React%20(Web)&createdTime=1634915662909

**Comment by khmakoto** [comment]
Hi @gouttierre and @iron-man14, I can confirm that I see this happening.

Hi @hetanthakkar1, feel free to take this one!

**Comment by gouttierre** [comment]
@hetanthakkar1- thank you for your willingness to contribute to this issue. When you have the solution at hand and would like to submit a PR, please, let us know and our team will review it.

**Comment by rohitk2497** [comment]
Any update here, also seeing this issue
