### ISSUE TITLE
[Panel] Form elements in panel contents are rendered over header when scrolled

### ISSUE THREAD

**Issue by gmantri** [microsoft/fluentui#20326]
### Environment Information

- **Package version(s)**: @fluentui/react version 8.37.1
- **Browser and OS versions**: Safari (v15.0), macOS

### Please provide a reproduction of the bug in a codepen:

Please take a look at the code below. I simply took the code from https://developer.microsoft.com/en-us/fluentui#/controls/web/panel (Panel Footer example) and added a `TextField` component to it.

```
import * as React from 'react';
import { DefaultButton, PrimaryButton, TextField } from '@fluentui/react/lib/Button';
import { Panel } from '@fluentui/react/lib/Panel';
import { useBoolean } from '@fluentui/react-hooks';

const buttonStyles = { root: { marginRight: 8 } };

export const PanelFooterExample: React.FunctionComponent = () => {
  const [isOpen, { setTrue: openPanel, setFalse: dismissPanel }] = useBoolean(false);

  // This panel doesn't actually save anything; the buttons are just an example of what
  // someone might want to render in a panel footer.
  const onRenderFooterContent = React.useCallback(
    () => (
      <div>
        <PrimaryButton onClick={dismissPanel} styles={buttonStyles}>
          Save
        </PrimaryButton>
        <DefaultButton onClick={dismissPanel}>Cancel</DefaultButton>
      </div>
    ),
    [dismissPanel],
  );

  return (
    <div>
      <DefaultButton text="Open panel" onClick={openPanel} />
      <Panel
        isOpen={isOpen}
        onDismiss={dismissPanel}
        headerText="Panel with footer at bottom"
        closeButtonAriaLabel="Close"
        onRenderFooterContent={onRenderFooterContent}
        // Stretch panel content to fill the available height so the footer is positioned
        // at the bottom of the page
        isFooterAtBottom={true}
      >
        <p>Content goes here.</p>
        <p><TextField/></p>
        <p>Content goes here.</p>
      </Panel>
    </div>
  );
};
```

#### Actual behavior:

If a panel component contains form elements (e.g. input boxes etc.), when the content is scroller the input elements are rendered over the header. Please see the screenshots below for example:

![Screenshot 2021-10-24 at 11 31 10 AM](https://user-images.githubusercontent.com/79372564/138582876-aa6bd50b-5804-416e-b06d-c7d8af76a7f9.png)

![Screenshot 2021-10-24 at 11 32 09 AM](https://user-images.githubusercontent.com/79372564/138582886-0dbb5a73-8e94-4a4d-a8c6-329ef349d6c8.png)

#### Expected behavior:

The input controls should not be displayed over the header text.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No.

Requested priority: (Blocking, High, Normal, Low)
High

Products/sites affected: (if applicable)
N/A

**Comment by Sinled** [comment]
Also have this issue,
if anything in content has `position:relative` it will be on top of header, problem exists not only in safari but in chrome too

**Comment by gouttierre** [comment]
@gmantri - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. 

@khmakoto  - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by Sinled** [comment]
Any updates on this?

**Comment by khmakoto** [comment]
Hi @gmantri, I don't see this happening in the latest version of the library. Can you confirm if this is still an issue for you?
