### ISSUE TITLE
Component onClick methods periodically not triggered until cursor move

### ISSUE THREAD

**Issue by chochstedler** [microsoft/fluentui#20332]
### Environment Information

- **Package version(s)**: Fluent UI React 8.37.2, Fluent UI React Northstar 0.59.0
- **Browser and OS versions**: Google Chrome 95.0.4638.54, Electron 15.3.0, Mac OSX 11.2.3

#### Actual behavior:

Often when clicking on a component, its onClick method will not be called until the cursor is moved after the click. I first noticed the behavior in an electron project, but a quick check revealed it is also present on the webpage for both Fluent UI and Northstar.

It is very easy to reproduce. https://developer.microsoft.com/en-us/fluentui#/controls/web/button 
The primary compound button is easiest to test for visibility, though the issue affects all components, even the dropdown menu. Click the button at 1 second intervals without moving the cursor. With every click, the button darkens, wait for it to stay dark after a click. Once this happens, a simple move of the cursor releases the state. It's not just a visual issue, the onClick method is not getting called until the cursor moves.

I tested the onClick method of a div in the same scenario and could not reproduce it.

#### Expected behavior:

onClick method is called immediately when component is clicked.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
All

EDIT
Just checked MS Teams and was also able to reproduce the issue there.

**Comment by gouttierre** [comment]
@chochstedler  - Would you kindly create separate issues with their associated repro's (codepens). i.e. One issue for `Fluent UI React Northstar 0.59.0` and another for `Fluent UI React 8.37.2`. We have separate teams for each lib and for us to assist you further you will need to provide this information. Thank you for your understanding.
