### ISSUE TITLE
Panel blocks 3rd party component dropdown function.

### ISSUE THREAD

**Issue by iamchangming** [microsoft/fluentui#20339]
### Environment Information

- **Package version(s)**: 
"office-ui-fabric-react": "7.177.2"
"ckeditor4-react": "2.0.1"
- 
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

I met issue to add the ckeditor4-react package to codepen, but I have setup a very simple one with codesandbox.

https://codesandbox.io/s/ckeditor4-0dojn?file=/src/App.js

#### Actual behavior:

The dropdowns, "Styles", "Normal", does not work if shown in the Panel.
But works without the Panel.

#### Expected behavior:

Should work with AND without the panel.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking)

Products/sites affected: (if applicable)
Microsoft internal UCM site. https://ucm.ads.microsoft.com/
We are building a Panel with CKEditor to edit notes.

**Comment by gouttierre** [comment]
@iamchangming -Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@layershifter - Would you be able to confirm if this is a regression, or if this behavior is an issue when using 3rd party component? Note, the issue was reported by a partner in v7, I will add it to the LP Shield board.

**Comment by layershifter** [comment]
Clearly, it's not a regression. TL;DR use `baseFloatZIndex` higher than in Fabric:

```tsx
<CKEditor config={{ baseFloatZIndex: 1000000000 }} />
```

https://codesandbox.io/s/ckeditor4-forked-cx6ld?file=/src/App.js

----

`Layer` in Fabric has really high `zIndex` value:

https://github.com/microsoft/fluentui/blob/a00fc291f6ffac69ad73907e886ef2d14c48a110/packages/style-utilities/src/styles/zIndexes.ts#L9

As it's higher than value in CKEditor 4 ([cfg#baseFloatZIndex](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-baseFloatZIndex)) all menus will be rendered under the panel.
