### ISSUE TITLE
There is no option to override ClearButton Icon color

### ISSUE THREAD

**Issue by IliaGalperin** [microsoft/fluentui#20345]
### Environment Information

- **Package version(s)**: Fluent UI React 8.37.2

Code:

```
_

> const X_BUTTON = {
>   iconProps: {
>     iconName: 'Clear',
>     styles: {
>       root: {
>         color: 'red',
>       },
>     },
>   },
> };
> 
> <SearchBox
>     ...
>     clearButtonProps={X_BUTTON}
>      ...
> />

_
```

#### Actual behavior:

![image](https://user-images.githubusercontent.com/93191515/138856270-1a394bba-7bb7-4d82-b4df-a16994e8b792.png)

There is no option to override ClearButton Icon color in SearchBox because of default style property:

```
> _.clearButton-___ .ms-Button-icon {
>     color: rgb(96, 94, 92);
> }_
```

![image](https://user-images.githubusercontent.com/93191515/138855331-308be11e-1985-42c1-8a00-7276462c4453.png)

#### Expected behavior:

The user should be able to change Icon Color in ClearButton.

### Priorities and help requested:

Requested priority: (Blocking, High, Normal, Low) Normal

**Comment by gouttierre** [comment]
@liaGalperin  - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [SearchBox](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/searchbox) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by IliaGalperin** [comment]
@gouttierre Here is a link to codeopen
[](https://codepen.io/Galilia/pen/ExvLvmj)
