### ISSUE TITLE
[Dropdown] Keyboard focus does not retain on last selected item when title width is not constant.

### ISSUE THREAD

**Issue by NadRose** [microsoft/fluentui#20354]
### Environment Information

- **Package version(s)**: Fluent UI React 8.37.3
- **Browser and OS versions**: Microsoft Edge Version 95.0.1020.30 (64-bit) + Chrome on Windows 10 OS

### Describe the issue:

When setting the dropdown title width to be adjustable (fit content or max content), item focus jumps to first item selected and does not retain on the current item.

Note: the problem is not with the callout width, this can be fixed, but with the focus of the selected items.

User Experience:
Users who rely on Keyboard will be impacted if focus does not retain on the same control on selecting any item from the dropdown.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/nadavrosenthal/pen/ExvmKMo?editors=1010

Repro steps: When selecting "Banana" from the item list using keyboard, and then selecting "Orange", focus jumps back to "Banana".

#### Actual behavior:

After selecting items from the list items using spacebar keyboard focus is landing on the first selected item instead of present selected grade.

#### Expected behavior:

Keyboard focus should retain on the present selected item instead of previously selected items from the dropdown.

### Documentation describing expected behavior

MAS Reference:
[MAS 2.4.3 – Focus Order](https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7b54673D5E-1EBB-47DA-988B-52B4BF912771%7d&file=MAS%202.4.3%20%E2%80%93%20Focus%20Order%20.docx&wdLOR=c4DFF4A95-9900-4BC2-848B-25C9BCAB4FB7&action=default&mobileredirect=true)

**Comment by gouttierre** [comment]
@NadRose - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. 

@khmakoto  - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley
