### ISSUE TITLE
v9: prerelease versions match the nightly prerelease version

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#20355]
[Semver spec](https://semver.org) states that:

> Identifiers with letters or hyphens are compared lexically in ASCII
order

This means that `^9.0.0-alpha` will always match with `9.0.0-nightly`.
Releasing `0.0.0-nightly` ensures that no other prerelease version
should ever match with a nightly version when resolving dependencies.

**Comment by miroslavstastny** [comment]
Done in #20353
