### ISSUE TITLE
Storybook `show code` collapsible does not show the entire story

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#20367]
When clicking on the `shoe code` button, only the exported function is displayed in the collapsible. With more complex examples like [nested menus](https://github.com/microsoft/fluentui/blob/master/packages/react-menu/src/stories/MenuNestedSubmenus.stories.tsx) it does not reflect how to use the component in that scenario. Especially in cases where components should be used alongside other code as a best practice

![image](https://user-images.githubusercontent.com/20744592/138934198-f9d9ce90-e430-4b1c-9dc3-6cb6ff905e95.png)

**Comment by PeterDraex** [comment]
Workaround: https://github.com/microsoft/fluentui/pull/19583#discussion_r711365371
