### ISSUE TITLE
vNext Button: Inverted variants for Subtle, Default, and Primary

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#20368]
#### Describe the feature that you would like added

Inverted variants for Subtle, Default, and Primary to support the brand colored teaching UI in Office.com. Other products will likely have the same scenarios as our design for teaching ui across products usually uses the brand color. Inverted will also be helpful for the Toasts scenario (where the toast is on a dark background color in light theme) and buttons are commonly asked for inside the Toast.

#### What component or utility would this be added to
 
vNext Button (https://aka.ms/fluentui-storybook)

#### Have you discussed this feature with our team, and if so, who

Yes, @khmakoto and @paulgildea 

#### Additional context/screenshots
Default Inverted: https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?node-id=9242%3A24202
Primary Inverted: https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?node-id=9242%3A20933
Subtle Inverted: https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?node-id=9242%3A22518

![image](https://user-images.githubusercontent.com/48726002/138962335-ca58b22c-18ab-4387-ad6c-8fc8a6727f4a.png)

**Comment by khmakoto** [comment]
Closing in favor of #22553
