### ISSUE TITLE
Impossible to set default value for the time picker

### ISSUE THREAD

**Issue by manishvicky** [microsoft/fluentui#20379]

**Comment by gouttierre** [comment]
@manishvicky - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. 

@lorejoh12  - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @khmakoto

**Comment by daniharo** [comment]
Duplicate of #19554, probably solved by #20805

**Comment by CheerfulSatchel** [comment]
@daniharo Thank you for linking the PR to this!

**Comment by smhigley** [comment]
This was fixed in the linked PR, I verified that it is possible to set a default value now.
