### ISSUE TITLE
`onRestoreFocus` Callout property, does not prevent focus to be restored automatically.

### ISSUE THREAD

**Issue by gbahamondezc** [microsoft/fluentui#20370]
### Environment Information

- **Package version(s)**:  8.37.3
- **Browser and OS versions**: Microsoft Edge v95.0.1020.30

### Please provide a reproduction of the bug in a codepen: 

(https://codepen.io/gbahamondezc/pen/GRvmMOw

It looks like, by default, the `Callout` component  (used by the `TeachingBubble` component) restores the focus on the last previously focused element when unmounting it, 

[Callout docs](https://developer.microsoft.com/en-us/fluentui#/controls/web/callout) points out that there is an `onRestoreFocus` property that _If this is provided, the focus will not be restored automatically_

The `onRestoreFocus` is being triggered correctly, but it is not preventing the default behavior.

#### Actual behavior:
It automatically keeps restoring the last focus when unmounting the component even if we pass a noop `onRestoreFocus` callback.

#### Expected behavior:
It should not restore the focus automatically anymore when `onRestoreFocus` unless we implement the same behavior inside the callback calling `params.originalElement.focus()`

**Comment by gouttierre** [comment]
@gbahamondezc - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. 

@khmakoto  - Would you be able to confirm if this is a regression, or if this behavior is an issue?
