### ISSUE TITLE
ctrl+option+space does single selection in Chrome/Edge on mac

### ISSUE THREAD

**Issue by sonxu2011** [microsoft/fluentui#20375]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@7.176.1_f6d26faa8b9c16b6115a7b7908b3aa6c; [uifabric+utilities@7.33.5_f6d26faa8b9c16b6115a7b7908b3aa6c/lib](url)
- **Browser and OS versions**: Edge (95.0.1020.30)/Chrome (94.0.4606.71) on mac (macBig Sur 11.6)

### Describe the issue:
In Edge/Chrome on mac, turn on VoiceOver. ctrl+option+space causes a single selection.

### Please provide a reproduction of the issue in a codepen:
Call stacks attached 
For recording, https://office.visualstudio.com/OC/_workitems/edit/5477128

Repro steps:
1.https://hubblecontent.osi.office.net/contentsvc/m365contentpicker/index.html?initpivot=stockimages
Or 
-go to sharedpoint e.g., https://microsoft.sharepoint-df.com/teams/gfx/Shared%20Documents/Forms/AllItems.aspx
-open a slide in ppt online
-insert/pictures/stock images
2.turn on voiceover
3.move focus to the 1st image in the dialog and press space key to select it
4.press arrow right to move to the 2nd image
5.press ctrl+option+space to select the 2nd image

#### Actual behavior:

The 1st image is unselected and the 2nd image is selected. I.e., ctrl+option+space results in a single selection.

#### Expected behavior:

The 1st image should remain selected and the 2nd image is selected. I.e., ctrl+option+space should not unselect the previous selection.

### Documentation describing expected behavior

call stack (step3)
Selection.setIndexSelected (Selection.js:251)
Selection.toggleIndexSelected (Selection.js:291)
SelectionZone._onToggleClick (SelectionZone.js:384)
SelectionZone._this._onKeyDown (SelectionZone.js:298)

call stack (step5)
Selection.setAllSelected (Selection.js:210)
SelectionZone._clearAndSelectIndex (SelectionZone.js:470)
SelectionZone._onInvokeMouseDown (SelectionZone.js:440)
SelectionZone._this._onMouseDown (SelectionZone.js:129)

In step5: the 1st image (index=0) is selected in step 3; when press ctrl+option+space to select the 2nd image: 
in Selection.setAllSelected (Selection.js:210), this._exemptedIndices is reset. in Selection.prototype.getSelection(), this.isIndexSelected(0) returns false (unselected) and only this.isIndexSelected(1) returns true (selected). See mac_ctrloptionspace.mp4, 55s: the 1st image should remain selected but it becomes unselected.

**Comment by gouttierre** [comment]
> @bsunderhus 1.can you access \osan\ogx\public? I cannot attach the videos to this ticket. 2.selctionmode is 2 (multi). The issue is similar (Selection.setAllSelected is called and this._exemptedIndices is reset) to #16410 but in multi selection mode

@sonxu2011 - could you have a look a the response posted?

**Comment by sonxu2011** [comment]
Gogomes,

Which response need I look at?

***@***.***<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbsunderhus&data=04%7C01%7CSongyan.Xu%40microsoft.com%7C370bcc75aeba406ece5008d9a386083b%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637720618383868873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nHHSF%2FbR5BoKU5VSi18Lp%2BjEXvGIzlgKvWOSWt7o%2FVM%3D&reserved=0> 1.can you access \osan\ogx\public? I cannot attach the videos to this ticket. 2.selctionmode is 2 (multi). The issue is similar (Selection.setAllSelected is called and this._exemptedIndices is reset) to #16410<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Ffluentui%2Fissues%2F16410&data=04%7C01%7CSongyan.Xu%40microsoft.com%7C370bcc75aeba406ece5008d9a386083b%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637720618383878835%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5LKaUpk5woN5EmmIbejHHwlaPLWle%2FFBpIqFre7POsE%3D&reserved=0> but in multi selection mode" was posted by me. I cannot attach the screen recording to this issue so I asked @busnderhus if can access a vso bug to get more details about this issue.

BTW, my alias is sonxu. You can reach me via teams.

Thanks,
Songyan


________________________________

**Comment by sonxu2011** [comment]
To whom it may concern,

I will be on vacation from 11/30/2021 to Jan 3, 2022.

Please let me know any info I need to provide now. During my vacation, please contact my colleague Bobby Damore and manager Jie Li, if needed. Thanks.

VSO Bug 5477128: [Narration] [M365 Content Picker] in Mac Edge with VoiceOver, Control-Option-Space does single select action - Boards (visualstudio.com)<https://office.visualstudio.com/OC/_workitems/edit/5477128> has more details and screen recordings.

Regards,
Songyan
________________________________
