### ISSUE TITLE
a11y: Dropdown headers are not navigatable via "H" in scan mode

### ISSUE THREAD

**Issue by jgage176** [microsoft/fluentui#20390]
### Environment Information

- **Package version(s)**: 8.37.4
- **Browser and OS versions**:  Win10, edge: 94.0.982.2

### Describe the issue:

The dropdown list does not jump to headers (or treat the groups as headers at all) when in scan mode.

### Please provide a reproduction of the issue in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/8.37.4/#/examples/dropdown

1. Expand a dropdown (such as uncontrolled) with the keyboard so it has focus
2. Run Narrator in scan mode(Caps+Space) press "H" and check if the heading are getting announced.

#### Actual behavior:

When H is pressed it jumps to a header outside of the dropdown instead of jumping to headers in the dropdown.

#### Expected behavior:

Jump through headings in the dropdown

### Documentation describing expected behavior

MAS 1.3.1 – Info and Relationships: https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7b97358E88-4367-4121-BF9D-F0C6597D03B7%7d&file=MAS%201.3.1%20%E2%80%93%20Info%20and%20Relationships%20.docx&wdLOR=cC67AE285-FA8E-4A9C-8615-42813289BF4A&action=default&mobileredirect=true

**Comment by gouttierre** [comment]
@jgage176 - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. 

@khmakoto  - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley - I am not sure if this is the same issue you resolved with screen reader and datepicker recently.
