### ISSUE TITLE
[Dropdown] Dropdown height doesn't get updated

### ISSUE THREAD

**Issue by necoh** [microsoft/fluentui#20395]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

I try to change the dropdown height using this syntax, but it doesn't get updated-

const dropdownStyles: Partial<IDropdownStyles> = {
  dropdown: { width: 300, height: 20 },
};

#### Expected behavior:

The Dropdown height should be changed.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@necoh - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [Dropdown](https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by necoh** [comment]
> @necoh - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [Dropdown](https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

Hi,
Attaching here the codepen- https://codepen.io/netaCode/pen/gOxBMQJ

As you can see the outer height doesn't get updated, or I'm doing things wrong.
Is there another property that I should set up to control the dropdown height?

**Comment by necoh** [comment]
> Gentle ping that this issue needs attention.

Waiting for response

**Comment by necoh** [comment]
Waiting for response

**Comment by abmis-mi** [comment]
@necoh 
If you want to adjust the height of the dropdown items container (or wrapper) you can use `dropdownItemsWrapper` property as below:
const dropdownStyles: Partial<IDropdownStyles> = {​​​​​​​
  dropdown: {​​​​​​​ width: 300 }​​​​​​​,
  dropdownItemsWrapper : {​​​​​​​ maxHeight: 150 }​​​​​​​
}​​​​​​​;
