### ISSUE TITLE
[Panel] has an unnecessary scroll bar when isFooterAtBottom is set to true

### ISSUE THREAD

**Issue by lucas-stanford** [microsoft/fluentui#20416]
![image](https://user-images.githubusercontent.com/3011776/139513280-f1f2f084-bcb3-4e9d-b352-c5efd2c5308c.png)

### Environment Information

- **Package version(s)**: 8.37.6
- **Browser and OS versions**: I tested in edge, chromium. Probably all browsers though.

### Please provide a reproduction of the bug in a codepen:
https://fabricweb.z5.web.core.windows.net/oufr/8.37.6/#/examples/panel repro's here under the heading `Panel - Footer`

#### Actual behavior:

There is a scrollbar.

#### Expected behavior:

No scrollbar.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)

High

Products/sites affected: (if applicable)
All sites using panel with `isFooterAtBottom` with content that does not take up the entire panel height.

**Comment by gouttierre** [comment]
Worked on in  #20467
