### ISSUE TITLE
Split button menu is not accessible by keyboard

### ISSUE THREAD

**Issue by chris-morgan** [microsoft/fluentui#20417]
https://developer.microsoft.com/en-us/fluentui#/controls/web/button, split button example: use Tab to cycle through everything on the page, and the split button arrow isn’t part of it; and no key that I’ve tried (Space, Enter, all arrows, +) triggers the menu when the button is focused. (This includes the “main action disabled” button—pressing Enter or Space does nothing, rather than opening the menu as I’d *especially* expect in that case.)

**Comment by gouttierre** [comment]
@chris-morgan - Thanks for filing this issue with us. I was unable to reproduce the issue on my side. Could you retest the scenario and let us know the outcome along with the repro steps taken.

**Comment by chris-morgan** [comment]
It’s exactly as I describe, still reproducible, in both Firefox and Chromium.

**Comment by gouttierre** [comment]
@chris-morgan - I reproduced the issue on a `Firefox` browser. Thank you for confirming. 
![image](https://user-images.githubusercontent.com/78806055/146035826-e7c0a030-22ce-4533-b478-ad0bbafb8753.png)
Yes, I see that the downward arrow on the split-button does not get focus. To set expectations, the developers will review this issue once capacity allows. 

@layershifter - Would you be able to confirm if this is a regression, or if this behavior is an issue?
