### ISSUE TITLE
aria-labelledby on span element in detailslist leads to inconsistent a11y

### ISSUE THREAD

**Issue by joshualamusga1** [microsoft/fluentui#20415]
### Environment Information
- **Package version(s)**: Fluent UI 8.7.36 (demo site)
- **Browser and OS versions**: Edge Chromium on Windows 10 64-bit Enterprise

### Describe the issue:
Headers on the detailslist component have a span element with aria-labelledby and no role set, which screen readers will treat differently.

### Please provide a reproduction of the issue in a codepen:
All versions of Fabric including the demo site

1. [Go to the detailslist page here](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist)
2. Scroll down the page to the first detailslist
3. Open F12 devtools and select the Inspect Element tool in the top-left corner
4. Select the text of the Name column
5. Observe the parent node in the DOM tree of the selected element. It has aria-labelledby set and is a span element

#### Actual behavior:
A span element exists with aria-labelledby set. Screen readers will treat this differently.

#### Expected behavior:
The span element should use an alternative to aria-labelledby, or have a role set to ensure consistent accessibility.

### Documentation describing expected behavior
https://dequeuniversity.com/rules/axe/4.3/aria-allowed-attr?application=AxeEdge

**Comment by gouttierre** [comment]
@joshualamusga1 - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@layershifter - Would you be able to confirm if this is a regression, or if this behavior is an issue? 
cc @smhigley
