### ISSUE TITLE
No OnBlur for Slider (Dismissing Slider gets stuck).

### ISSUE THREAD

**Issue by seniroberts** [microsoft/fluentui#20425]
Removing focus from the slider is extremely tricky. A user has to tab away multiple times to remove focus from the active slider. 

### Environment Information

- **Package version(s)**:  7.170.2 and demo site version
- **Browser and OS versions**: Chrome, Edge

#### Actual behavior:

User has to tab away multiple times or use <shift + tab + Space> to dismiss the slider

#### Expected behavior:

Tabbing away should remove focus and dismiss the  slider.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
Hi @seniroberts, I don't think I am able to reproduce this on the demo site, do you have a codepen I could look at or a GIF that shows what you're seeing?
