### ISSUE TITLE
[SearchBox] State changes for Value field don't reflect in the SearchBox

### ISSUE THREAD

**Issue by MightySameerDesai** [microsoft/fluentui#20424]
### Environment Information

- **Package version(s)**:  "^8.29.1"
- **Browser and OS versions**: (fill this out if relevant) Edge 95, Win 11

#### Actual behavior:
I have a contextual menu in React|TS where one of the menu items is a combination of search box and items (custom rendered menu item). When I dismiss the menu, the search text wouldn't clear out. Since the value field in searchbox is managed by a state variable, I assumed that state updates to searchText (state variable), will result in the same being seen in the searchBox. It is not the case. The SearchBox doesn't update to show the latest string. 

#### Expected behavior:
On setstate, SearchBox should display the right text in the searchbox.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High. 
For now, I have a workaround, where I trigger a keyboard event with "Esc" key, which causes the searchBox to clear out.

Products/sites affected: (if applicable)
Excel for Web

**Comment by khmakoto** [comment]
Hi @MightySameerDesai could you provide a codepen or codesandbox that reproduces the behavior you describe?
