### ISSUE TITLE
Import package build error

### ISSUE THREAD

**Issue by lll19920323outlook** [microsoft/fluentui#20457]
A compilation error occurred while introducing the package into the webpart component of the SPFx project, When run command ‘gulp serve’
![微信图片_20211102235647](https://user-images.githubusercontent.com/85143324/139888806-972bd4cb-b216-482c-9c90-0f31cfedb1c2.png)

**Comment by khmakoto** [comment]
Hi @lll19920323outlook, is there a way I could repro this locally?
