### ISSUE TITLE
Dialog: Unable to set the localized title for default close button on top and `closeButtonAriaLabel` prop is not populating in DOM

### ISSUE THREAD

**Issue by VenkateshChunchu** [microsoft/fluentui#20463]
### Describe the issue:

In Dialog component, there is no property to set the close button title and setting the `closeButtonAriaLabel` prop, it's not populating in DOM

**Comment by khmakoto** [comment]
Hi @VenkateshChunchu, which component is this affecting? Do you have a repro I could look at?

**Comment by venk120soft** [comment]
Sorry, I thought, it's linked to the component I was referring to. It's Dialog component. I was unable to set the custom text to the close button title.

**Comment by VenkateshChunchu** [comment]
Sorry, I thought it's linked to component I was referring to. It's Dialog component
