### ISSUE TITLE
Microsoft Lists branded icon

### ISSUE THREAD

**Issue by redlab-chris** [microsoft/fluentui#20476]
#### Describe the feature that you would like added

A Microsoft Lists branded icon added to the branded icon collection

#### What component or utility would this be added to

Branded Icons
https://developer.microsoft.com/en-us/fluentui#/styles/web/office-brand-icons

#### Have you discussed this feature with our team, and if so, who

no

#### Additional context/screenshots

n.a.

**Comment by khmakoto** [comment]
Hi @redlab-chris, thanks for filing this issue. we will take it into account going forward. Our icons story is deeply integrated with design so I don't know how long it's going to take to have this conversation but we'll keep you posted, thanks!
