### ISSUE TITLE
FocusTrapCallout with scrollable radio list: cannot select some of the items

### ISSUE THREAD

**Issue by dkozar** [microsoft/fluentui#20472]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^7.176.3",
- **Browser and OS versions**: (Chrome, Windows 10)

### Please provide a reproduction of the bug in a codepen:

Codepen: https://codepen.io/dkozarms/pen/LYjeRrJ?editors=1010

When having scrollable content in _FocusTrapCallout_, and _scrollTop > 0_, clicking the inner controls (radio buttons, checkboxes) scrolls the content to top. This makes **impossible to select the desired values**.

This seems to be the _FocusTrapCallout / FocusZone / focusUtilities_ problem.

#### Actual behavior:

Scroll to the last item in popup and try to select it:

![image](https://user-images.githubusercontent.com/1078403/140049269-db40809a-9f07-4e51-b715-83e49c4b33ca.png)

The scrollbar will scroll all to the top, with the wrong item being selected:

![image](https://user-images.githubusercontent.com/1078403/140049286-e9a252c8-f831-45cd-97ef-6afb0eba00a1.png)

Same happens when the user clicks - not on the radio button - but the Callout "chrome", or clicks outside the Callout altogether.

It happens with checkboxes too:

https://codepen.io/dkozarms/pen/oNepYBr?editors=1010

![image](https://user-images.githubusercontent.com/1078403/140050698-2da19c76-756c-4522-bb12-ba47e2427a06.png)

#### Expected behavior:

The clicked radio button / checkbox would be selected, and scrolling to top shouldn't happen.

#### Temporary fix

We realized that, if there is an additional focusable element before the scrollable list, then this doesn't happen:

https://codepen.io/dkozarms/pen/mdMXbdN?editors=1010

So for now, we've added a small invisible (_visibility: hidden_) text field which - conveniently - doesn't seem to get focus when tabbing, but it seems to be focused by FocusZone programmatically:

![image](https://user-images.githubusercontent.com/1078403/140050803-2cceecbb-5d31-4aab-96fb-76c10cb8de75.png)

By looking at Fluent UI source, it seems related to [focusUtilities/focusAsync](https://github.com/microsoft/fluentui/blob/e5acabf449dde42659a3eb71819ccccc8571cfed/packages/fluentui/react-bindings/src/FocusZone/focusUtilities.ts#L394
).

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

No

Requested priority: (Blocking, High, Normal, Low)

Normal

Products/sites affected: (if applicable)

All the products that use FocusTrapCallout in combination with scrollable list of radio buttons or checkboxes.

**Comment by dkozar** [comment]
This looks related to https://github.com/microsoft/fluentui/issues/7891 which seems to be resolved 2 years ago (?).

**Comment by dkozar** [comment]
I created another, related bug report: https://github.com/microsoft/fluentui/issues/20496

**Comment by gouttierre** [comment]
@dkozar Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@layershifter - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by layershifter** [comment]
I've managed to create more simple repro for this using only `FocusTrapZone`: https://codesandbox.io/s/spring-dew-mo5c7?file=/src/App.js

Repro steps:
- Open CodeSandbox
- Click "Show callout" button
- Scroll to bottom
- Click on the last item
- Click outside scrollable area
- Focus goes to the first item, list scrolls💥

![ftz-jump](https://user-images.githubusercontent.com/14183168/146362555-592e7a2a-a3c9-4a07-b960-41f9735ffd25.gif)

---

According to docs there is `focusPreviouslyFocusedInnerElement` on `FocusTrapZone` that restores focus to previously focused item. For `FocusTrapCallout` it could be set via `focusTrapProps`:

```tsx
<FocusTrapCallout
  focusTrapProps={{ focusPreviouslyFocusedInnerElement: true }}
/>
```

I've modified your Codepen (https://codepen.io/layershifter/pen/qBPrLzJ?editors=1010) and it seems that it works. Can you please confirm?

**Comment by dkozar** [comment]
As I mentioned [here](https://github.com/microsoft/fluentui/issues/20496#issuecomment-995990892), this doesn't solve my issue, as:

- I'd still need a Callout wrapper and not only a list
- I don't need the first item to be focused on click outside, but the callout to be closed
- I'd need the labels of radio buttons to be clickable, without the scroll jumping around

**Comment by layershifter** [comment]
@dkozar should be this also closed https://github.com/microsoft/fluentui/issues/20496#issuecomment-997378275?

**Comment by dkozar** [comment]
Yes, let's just copy the solution over:

```js
<FocusTrapCallout
  focusTrapProps={{
    forceFocusInsideTrap: false,
    isClickableOutsideFocusTrap: true
  }}
/>
```
