### ISSUE TITLE
"Jumping" (auto-scrolling) dropdown when callout maxHeight is set

### ISSUE THREAD

**Issue by swiecaJS** [microsoft/fluentui#20477]
### Environment Information

- **Package version(s)**: Latest (example created from your documentation)
- **Browser and OS versions**: Latest chrome

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/khazarr/pen/rNzpmzZ

#### Actual behavior:

When the mouse enters the callout the dropdown position jumps. I am not using scroll in the video at all, just moving the mouse
https://user-images.githubusercontent.com/12431424/140080290-557b737a-47b0-4a0a-87f6-4412c7f85a4c.mp4

#### Expected behavior:
I can enter the callout from any direction and just the mouse enter/mouse move won't trigger any scrolling

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@swiecaJS - Thanks for filing this issue with us.  I was unable to reproduce your issue  in the shared CodePen. Would you kindly retest the scenario and let us know if you are still experiencing the same issue, along with the repro information. Thank you
