### ISSUE TITLE
Unannounced breaking change in details list

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#20485]
Someone added a 'disabled' prop to IDetailsRowStyleProps in this change:

https://github.com/microsoft/fluentui/commit/c4e88d96d13b1b1bcbf6db2bfd4d98d83ca84c07

That tripped us up in our v8 beta branch. It was then cherry-picked into the v7 branch in v 7.180.0, which broke our environment.

We've got a fix so it's no longer blocking us, but figured it'd be good to tell ya'll about it just in case others run into the issue 😊

**Comment by khmakoto** [comment]
Hi @mltejera, can you tell us how it broke you? Adding a `prop` is normally not a breaking change as it is most of the times backwards compatible.

**Comment by mltejera** [comment]
Sure  @khmakoto - it's not breaking if the prop is optional as it is on IDetailsRowBaseProps.

However it was added as required on IDetailsRowStyleProps, meaning we now have to add it to all the places we don't have Partial<IDetailsRowStyleProps>.

**Comment by khmakoto** [comment]
@mltejera I see... I think that was an oversight and not what we would want. I'll send PRs to update that to be optional in both v7 and v8. Sorry about the trouble this caused.

**Comment by mltejera** [comment]
No worries - it happens :-) Thanks for taking this on and fixing it! 🙏
