### ISSUE TITLE
Localization review

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#20481]
- localized font-face in theme?
  - how font is loaded? is it tokens driven?

- localized icons
  - v0 in RTL flips some icons, some remain the same, some have a different glyph
  - what do we have in v8?
  - what is the requirement for v9?

**Comment by GeoffCoxMSFT** [comment]
In v8, RTL will automatically flip:
- Alignment styles such as Stack horizontalAlign="start"
- Border styles such as borderRight: '1px solid green' (through makeStyles)
- Mirrored icons such as DoubleChevronLeftMed and DoubleChevronLeftMedMirrored when used as direct imports and when used in Icon or IconButton.

v8 does not flip any of the standard, non-mirrored icons.
dir can be applied at the index.html `<html>` element, on the ThemeProvider, or on any div.

**Comment by GeoffCoxMSFT** [comment]
No traction on this and a11y work will cover string localization.  This will come up again if it proves important.
