### ISSUE TITLE
Embed Behavior adds contraindicated attributes

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#20499]
EmbedBehavior
https://fluentsite.z22.web.core.windows.net/0.59.0/components/embed/accessibility

Adds in the same time 
role=presentation 
and 
tabIndex=0 
to root slot.

What is not correct, because if the element is focusable, should not be extracted from accessibility tree. (what basically role=presentation does)

**Comment by gouttierre** [comment]
@jurokapsiar- Would your team be able to confirm if this is a regression, or if this behavior is an issue?
