### ISSUE TITLE
Breadcrumb not visible in High contrast black mode

### ISSUE THREAD

**Issue by hpanwar35** [microsoft/fluentui#20490]
### Environment Information

- **Package version(s)**: "fluentui/react": "8.36.0",
- **Browser and OS versions**: Chromium Edge Version 95.0.1020.30 (Official build) (64-bit), Windows 10

### Describe the issue:
Breadcrumb is not visible in High contrast mode.

Pre Requisites :
   Turn on Highcontrast (Settings->Ease of Access->Turn on High contrast black)

Here is a screenshot of the issue from the Breadcrumb examples page
![image](https://user-images.githubusercontent.com/2060775/140245431-db699d82-cd65-4eea-8304-d6137dd34fae.png)

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/hpanwar35/pen/GRvyPGL

#### Actual behavior:
Breadcrumb is not visible in High contrast mode

#### Expected behavior:
Breadcrumb is visible in High contrast mode

### Documentation describing expected behavior
Users with vision impairment who rely on high contrast will face challenges in accessing the button name.

MAS Link: [04.03.01: No Disruption of Accessibility Features](https://liquid.microsoft.com/Web/Views/View/410874#Zrex-3A-2F-2Fms-2Eaccessibility-2FRequirements-2F04-2E03-2E01-2F)

**Comment by gouttierre** [comment]
@hpanwar35  - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. 

@khmakoto  - Would you be able to confirm if this is a regression, or if this behavior is an issue with high contract mode?

**Comment by spmonahan** [comment]
Hi @hpanwar35 I believe this issue has already been fixed and release in version [8.37.3](https://github.com/microsoft/fluentui/blob/master/packages/react/CHANGELOG.md#8373).

I verified this by forking your codepen and updating the Fluent UI script to v8.37.3: https://codepen.io/seanms/pen/oNePXKp

![breadcrumbs_8-37-3](https://user-images.githubusercontent.com/93940821/141368332-b8137b4b-1f73-44fe-ad28-4a276d068647.png)

Updating to the latest 8.x version of Fluent UI React ([8.41.4](https://codepen.io/seanms/pen/oNePXKp) at the time of this writing) should fix this breadcrumb issue for you.

**Comment by hpanwar35** [comment]
@khmakoto Thanks for the update.

**Comment by khmakoto** [comment]
No worries, thank @spmonahan, he did all the good work checking this! 😄
