### ISSUE TITLE
Charting Vertical Bar: not correct tick values on Y Axis

### ISSUE THREAD

**Issue by Utsav37** [microsoft/fluentui#20491]
![image](https://user-images.githubusercontent.com/25278093/140255959-8bb508fb-f2ac-450e-bd3a-8f04fac9995e.png)

### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

Vertical Bar graph is NOT displaying correct height of bar .

#### Expected behavior:

Vertical Bar graph should display correct height of bar .

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/sites affected: (if applicable) All Vertical Bar Graphs

**Comment by gouttierre** [comment]
@Raghurk - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by AtishayMsft** [comment]
Closing this issue.
