### ISSUE TITLE
FocusTrapCallout UX concern: Focuses first input on mouse-down

### ISSUE THREAD

**Issue by dkozar** [microsoft/fluentui#20496]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/dkozarms/pen/mdMXbdN?editors=1010

#### Actual behavior:

Whenever the user mouse-downs some of the callout child inputs, the first input gets focused ("Search" field in the example). When the user releases a mouse, only then the clicked item is in focus. This is not right, might confuse the user, and looks "unstable" or "glitchy".

The same happens on clicking the callout "chrome", or outside the callout.

Mouse-down:

![image](https://user-images.githubusercontent.com/1078403/140300316-8139483e-9462-4b30-b6ee-0719f38824a9.png)

Mouse-up:

![image](https://user-images.githubusercontent.com/1078403/140300341-3a7162a0-10fa-4179-86b5-d5d703fcdfbb.png)

#### Expected behavior:

The clicked component should immediately receive the focus (on mouse-down), or (at least) another component shouldn't receive it instead.

I understand this is done so to prevent losing focus, however I think the current behavior is not fully expected, and it also introduces different issues: https://github.com/microsoft/fluentui/issues/20472.

Additionally, I think that _FocusTrapCallout_ should only care for trapping the focus when keyboard is used (tabbing); when the user clicks outside, the callout should close. Or it should probably have a switch - _closeOnClickOutside_ (boolean). Currently the user has to write additional (complex) logic for processing "click outside" in order to close the callout.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

No.

Requested priority: (Blocking, High, Normal, Low)

Normal.

Products/sites affected: (if applicable)

All the products that use _FocusTrapCallout_ in combination with inputs (radio buttons, checkboxes, etc.).

This is related to https://github.com/microsoft/fluentui/issues/20472.

**Comment by gouttierre** [comment]
@dkozar Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@layershifter - Would you be able to confirm if this is a regression, or if this behavior is an issue? Note, could be related to #20472

**Comment by layershifter** [comment]
Hey @dkozar!

As there are two similar issues (#20472), I am a bit confused with the problem there.

> Additionally, I think that _FocusTrapCallout_ should only care for trapping the focus when keyboard is used (tabbing); when the user clicks outside, the callout should close. Or it should probably have a switch - _closeOnClickOutside_ (boolean). Currently the user has to write additional (complex) logic for processing "click outside" in order to close the callout.

Do you I correctly understand that there are two issues? 👇

- Strange focus behavior (#20472) solvable with https://github.com/microsoft/fluentui/issues/20472#issuecomment-995703797
- It's impossible to actually close a callout on click outside without additional logic

I checked props of `FocusTrapZone` and it seems that `isClickableOutsideFocusTrap` is does exactly that you expect. Combining it with `focusPreviouslyFocusedInnerElement` should solve the issue:

```tsx
<FocusTrapCallout
  focusTrapProps={{ isClickableOutsideFocusTrap: true, focusPreviouslyFocusedInnerElement: true }}
/>
```

https://codepen.io/layershifter/pen/GRMWzgR?editors=1010

---

Can you please confirm if it solves your problem?

**Comment by dkozar** [comment]
https://codepen.io/layershifter/pen/GRMWzgR?editors=1010 - doesn't seem to work when clicking labels (one must click strictly the radio circles).

https://codesandbox.io/s/spring-dew-mo5c7?file=/src/App.js - seems to work. Let me test it a bit more.

**Comment by layershifter** [comment]
> https://codesandbox.io/s/spring-dew-mo5c7?file=/src/App.js - selection seems to work. But it doesn't auto close on click outside. And the callout (chrome) isn't shown, just the radio list.

Because it's `FocusTrapZone`, not `Callout`.

----

> https://codepen.io/layershifter/pen/GRMWzgR?editors=1010 - doesn't seem to work when clicking labels (one must click strictly the radio circles). Closes properly on click outside.

Yeah, I see there is an issue with scroll jump in that case:

![callout-jump](https://user-images.githubusercontent.com/14183168/146428892-9b82652c-b42b-4c96-a819-5b5f3ae124dc.gif)

I left only `focusTrapProps={{ isClickableOutsideFocusTrap: true }}`: https://codepen.io/layershifter/pen/GRMWzgR?editors=1010. I don't see such jumps anymore, but focus still jumps between search and radios.

Can you please check?

**Comment by layershifter** [comment]
The working combination is:

```tsx
<FocusTrapCallout
  focusTrapProps={{
    forceFocusInsideTrap: false,
    isClickableOutsideFocusTrap: true
  }}
/>
```

https://codesandbox.io/s/exciting-bhabha-jk3z1?file=/src/App.js:1495-1577

---

Without `forceFocusInsideTrap: false` `FocusTrapZone` tries to keep focus inside itself always via triggering `.focus()` on the focusable element (eighter first focusable or based on props).

Why it's a problem for `label`? There is difference in handling of `input` & `label` clicks:
- for `input` focus immediately goes to `input`
- for `label` on mouse down focus goes to `body` and on mouse up to `input`

![label-focus](https://user-images.githubusercontent.com/14183168/146571096-c3a3c3e3-10a6-4b7a-a5da-aa0b6b66ec7b.gif)

**Comment by dkozar** [comment]
> The working combination is:
> 
> ```tsx
> <FocusTrapCallout
>   focusTrapProps={{
>     forceFocusInsideTrap: false,
>     isClickableOutsideFocusTrap: true
>   }}
> />
> ```

Thanks for the great analysis!

This one seems to work (https://codesandbox.io/s/exciting-bhabha-jk3z1?file=/src/App.js:1495-1577), as the previous one (https://codepen.io/layershifter/pen/GRMWzgR?editors=1010) was still focusing the search field on radio button mouse down (and un-focusing on mouse up).
