### ISSUE TITLE
Project: Upgrade v8 to React 17

### ISSUE THREAD

**Issue by TristanWatanabe** [microsoft/fluentui#20507]
## Problem

Since we’re looking into upgrading our whole repo to React 17, this project specifically focuses on how upgrading to React 17 will affect v8.

Related to: #16886, #17050, #20145

## Appetite

Weeks

## Solution

Upgrade to react 17 and see what breaks. How tests are handled may need to be changed as well since Enzyme does not officially support react 17 yet, however, there is an unofficial adapter that could be used. 

## Risks (Rabbit holes)

With build work, it could be anything! Also, the unofficial adapter may not fully work for all tests.

## Out of scope (No-gos)

Implementation will be done but may not be merged until upgrading north-star and v9 are ready.

**Comment by ecraig12345** [comment]
Should we close this and I can make a new one now that I'm working on this instead?
