### ISSUE TITLE
Project: burn down a11y bugs in v8

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#20511]
## Problem

We need to continue work on accessibility bugs in our current framework version

## Appetite

Weeks: 2 (depending on the incoming issues)

## Solution

This is primarily a continuing maintenance project, though part of this is continuing to gather data and feedback on the a11y bugs logged on us to improve our bug > triage > fix process.

## Risks (Rabbit holes)

- unexpected bugs with longer investigation and fix times

## Out of scope (No-gos)

N/A

**Comment by smhigley** [comment]
## End of month retrospective

### What was achieved?
- C&AI partner bug triage, removed almost all partner bugs, and the remaining ones are in PR
- Sev 3 bug triage (down from ~70 to 38, currently)
- Focused on other bugs as requested from partners

### What did we miss?
- Currently back to having bugs out of SLA (though somewhat planned for)

### What went well?
- A number of team members picked up a11y bugs this month 😊
- Gave a presentation to testers on what types of bugs tend to be misfiled
- It was good to reduce some of the Sev 3 bugs, since those have been neglected since they stopped counting against grading

### What could have gone better?
- There are always more bugs, triage is often still the biggest time suck

### What changed from initial expectations?
- Went more or less as expected, generally

**Comment by smhigley** [comment]
Moving to December (ongoing issue).

Goal for December: keep high-priority partner issues down, while allowing some of the other issues build up. Intentionally devoting less time to v8 a11y in December, to focus on vNext a11y and Combobox.

**Comment by GeoffCoxMSFT** [comment]
Sarah did it! 

Closing in favor of specific issues that have lists of the important bugs to fix per sprint.
