### ISSUE TITLE
Callout positioning: add calloutMinHeight prop to override directionalHintFixed

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#20516]
#### Describe the feature that you would like added

currently `directionalHintFixed` as specc'd will force a callout to stay on a specific side of a target, even if that side has no screen space at all. There's currently no way to request a callout to pin to a specific target size until it reaches some minimum height, and then flip to fit.

If we add a `calloutMinHeight` (to mirror `calloutMinWidth`), we could add that logic to the positioning utility.

Related to #20460 and #20514

cc/ @dotnetjunky for more info if needed :)

**Comment by dotnetjunky** [comment]
Thanks for opening this work.
