### ISSUE TITLE
React rating control, unable to set to zero initially

### ISSUE THREAD

**Issue by craigomatic** [microsoft/fluentui#20520]
### Environment Information

- **Package version(s)**: 8.41.0
- **Browser and OS versions**: Edge, Windows 11

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/craigomatic/pen/PoKQJEZ

#### Actual behavior:

Setting defaultRating={0} results in one star being rendered active in the control:

![image](https://user-images.githubusercontent.com/146438/140437002-12381137-b356-4930-a8e9-d24cda1ff904.png)

#### Expected behavior:

No stars should be rendered active in the control

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

No

Requested priority: (Blocking, High, Normal, Low)

Normal

Products/sites affected: (if applicable)

**Comment by dqhoang** [comment]
In the example codepen, you should use `allowZeroStars` not `allowZero`

**Comment by craigomatic** [comment]
Ah you're right! Works as expected with the correct attribute, closing :)
