### ISSUE TITLE
Backdrop blur filter on callout only works on second activation

### ISSUE THREAD

**Issue by imdavidmin** [microsoft/fluentui#20534]
### Environment Information

- **Package version(s)**: 8.27.0
- **Browser and OS versions**: Edge Chromium - Windows 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/imdavidmin-the-flexboxer/pen/yLoKZZo?editors=1010

#### Actual behavior:
Backdrop blur filter does not get applied, regardless of where the property is added (root, calloutMain, or container)
The filter does work after going into dev tools to untoggle the blur filter, then toggle it on again.

#### Expected behavior:
Blur filter to apply as soon as Callout becomes visible.

### Priorities and help requested:

Are you willing to submit a PR to fix? **No**

Requested priority: **Normal**

**Comment by imdavidmin** [comment]
May be the same issue as #10938. If the conclusion is the same then I can try a workaround.

**Comment by khmakoto** [comment]
Hi @imdavidmin, I think the workaround should work correctly with `onPositioned` and `onLayerMounted` and I would say that would be my recommendation in this scenario. If there is any specific change you think we could do in `Callout` to make this better let me know.

**Comment by imdavidmin** [comment]
@khmakoto Hi, ideally a workaround is not needed. I'm not sure what is the reason behind the blur filter not applying, possibly down to how DOM elements are created for the callout. If this can be fixed structurally that would be best.
