### ISSUE TITLE
ICalloutProps interface gapSpace documentation description is missing units

### ISSUE THREAD

**Issue by natejcho** [microsoft/fluentui#20549]
### Environment Information

- **Package version(s)**:  8.41.2
- **Browser and OS versions**: chrome, windows 10

### Describe the issue:

https://developer.microsoft.com/en-us/fluentui#/controls/web/callout

gapSpace is described as "The gap between the Callout and the target". What is the unit of this gap number? does it accept a negative value?

**Comment by khmakoto** [comment]
Hi @natejcho, I'll make a PR clarifying this in our docs. Just for your information, the gap unit is pixels and it does accept a negative value. Thanks!
