### ISSUE TITLE
ContextualMenu accessibility issue when navigating menu

### ISSUE THREAD

**Issue by alton-browsing** [microsoft/fluentui#20545]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

### Describe the issue:

I filed the same bug awhile ago and someone was able to reproduce the issue and based on the previous issue post, it never got resolved or looked at so reopening bug.

Old post: https://github.com/microsoft/fluentui/issues/15755

**Comment by gouttierre** [comment]
@alton-browsing - Thanks for reaching out to us. I reviewed the previous issue #15755 as reference but the codepen seems invalid. Would you mind retesting this scenario using our latest fluent version (v8) and if the issue persists, please submit a new issue with the repro steps.
