### ISSUE TITLE
Sub-menu items steal focus from searchbox on hover

### ISSUE THREAD

**Issue by makopch-ms** [microsoft/fluentui#20552]
### Environment Information

- **Package version(s)**: Fabric-react@8
- **Browser and OS versions**: Chrome/Edge/all browsers

### Please provide a reproduction of the bug in a codepen:
Code Pen: https://codepen.io/makopch/pen/vYJjPgB

#### Actual behavior:
When the user clicks in a SearchBox in a menu, focus goes to the search box and they can start typing.  As they are typing search results will update as menu items below the searchbox.  If the user hovers over one of them, focus will leave the searchbox rather then letting them continue typing if they need to.

I start with this: https://github.com/microsoft/fluentui/issues/17035 but passing shouldFocusOnMouse: false, and delayUpdateFocusHover: true doesn't do anything

Are these properties working as expected for the contextual menu items?  Is there another way to achieve this?

**Comment by smhigley** [comment]
I've always been of the opinion that we should not be setting focus from hover, ever. If we can't change that in v7 or v8, I'd be in favor of setting a prop to opt out, and recommending people set it to true in our docs.

**Comment by eylult** [comment]
Thank you @smhigley! Will you be creating a property for us to override to address the usability issue we are having in Outlook?

**Comment by JustSlone** [comment]
@TristanWatanabe was this fixed by the linked PR? if so let's close this issue out

**Comment by TristanWatanabe** [comment]
Fixed by #21528
