### ISSUE TITLE
onDismiss vs hidden ICalloutProps interface documentation clarification

### ISSUE THREAD

**Issue by natejcho** [microsoft/fluentui#20550]
### Environment Information

- **Package version(s)**: 8.41.2
- **Browser and OS versions**: chrome, windows 10

### Describe the issue:

documentation for onDismiss description states, "Callback when the Callout tries to close". This documentation should be more specific, does this callback run when the component unmounts? What about when the component is in hidden state? furthermore can we get some examples in the documentation utilizing the hidden prop. The documentation mentions that hidden improves performance vs unmounting, yet all the examples unmount the component rather than utilizing the hidden prop.

**Comment by gouttierre** [comment]
@natejcho - Thanks for filing this issue with us. To set expectations, the developers will review your question as soon as capacity allows.

@layershifter - Would you be able to assist with answering the questions and updating any missing [Callout](https://developer.microsoft.com/en-us/fluentui#/controls/web/callout) documentation. Thank you.
