### ISSUE TITLE
Can we get Windows11/WinUI3 style design in FluentUI React?

### ISSUE THREAD

**Issue by vivaanmathur** [microsoft/fluentui#20567]
#### Describe the feature that you would like added

Is it possible to bring Windows 11 / WinUI3 style design to Fluent UI Web Components?

#### What component or utility would this be added to

All components can be updated as per the new design guidelines.

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/42546935/141063874-7e99f109-50dc-4fba-bce4-22707baf9048.png)

**Comment by khmakoto** [comment]
Hi @vivaanmathur, thanks for filing this issue. This is something that is actively being looked at for the next major version of the library.

Feel free to keep this open for tracking or close it if you feel like your question has been answered!

**Comment by vivaanmathur** [comment]
Okay, that's great. The reason I created this issue is, it is important because Microsoft is actively pushing Edge WebView2, but to use that, there should be a web-based library that allows us to add components consistent with the design language of the operating system.

**Comment by vivaanmathur** [comment]
Is there any update on this?

**Comment by vivaanmathur** [comment]
@khmakoto @msft-fluent-ui-bot Is there any update on this?

**Comment by JustSlone** [comment]
@vivaanmathur this work is currently on-hold, it's something we would like to achieve in the future but is not currently funded due to competing priorities.

**Comment by vivaanmathur** [comment]
> @vivaanmathur this work is currently on-hold, it's something we would like to achieve in the future but is not currently funded due to competing priorities. 

You have already started with Fluent UI v9, which I believe is very similar.
