### ISSUE TITLE
Fallback CSS values

### ISSUE THREAD

**Issue by kroudams** [microsoft/fluentui#20566]
I'm trying to declare CSS fallback values using FluentUI but I don't seem to find any way to do this. I thought that array approach would work but it doesn't.

CSS that I'm trying to achieve
```css
.myElem {
  max-width: '100%',
  max-width: "min(100%, 5vw)",
}
```
FluentUI
```javascript
root: {
 maxWidth: ['100%', "min(100%, 5vw)"], // doesn't work
}
```

Is there a chance you could add a way / fix it so it would be possible to declare CSS fallback values?
As of right, there is no way to do this. The array approach doesn't seem to work at all.

### Environment Information

- **Package version(s)**: 8.9.0
- **Browser and OS versions**: Any browser, OS - Windows 10

**Comment by khmakoto** [comment]
Hi @kroudams, as you said, this is something that is not possible right now as we only accept one value per property. I don't know if/when we will get to this though since priorities will prevent us from doing any immediate work in this area.

**Comment by kroudams** [comment]
@khmakoto thank you for you answer. I've been a bit shocked when I realized that FluentUI doesn't provide this basic behaviour which for me is quite obvious. Not sure why it still hasn't been implemented.
