### ISSUE TITLE
Combobox doesn't clear the selectedIndex when user types an entry not in the combobox options

### ISSUE THREAD

**Issue by makopch-ms** [microsoft/fluentui#20576]
### Environment Information

- **Package version(s)**: Fluentui/react v8
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/makopch/pen/qBXyXzZ

#### Actual behavior:
1. Have Combobox w/ AllowFreeForm = true
2. Type a custom entry and hit Enter.  Example: In the code pen, type "4" in the combobox
3. Open the combobox menu to see the options
Notice that `C` is still selected
4. Try and select `C`
 
User cannot select it because the combobox still thinks it is the selected Key even though we pass undefined.

#### Expected behavior:
Because `4` is not an option in the combobox, we should clear out the selected index so that the user could then go back and select this.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, if fix is agreed on

Requested priority: Normal

Products/sites affected: Office Online -  Our Font Size and Zoom comboboxes allow the user to select custom values so we need the selected index to be cleared out.

I believe the fix would be to add something like the following as it appears we only update the indices if there is a selectedKey
https://github.com/microsoft/fluentui/blob/fbae36b19be65e9be5715d74279d03f8b7b1dc04/packages/react/src/components/ComboBox/ComboBox.tsx#L140
```
  React.useEffect(() => {
    if (selectedKey !== undefined) {
      const selectedKeys: string[] | number[] = buildSelectedKeys(selectedKey);
      const indices: number[] = getSelectedIndices(options, selectedKeys);

      setSelectedIndices(indices);
    } else {
      **setSelectedIndicies(undefined)**
   }
    setCurrentOptions(options);
  }, [options, selectedKey]);
```

**Comment by khmakoto** [comment]
@makopch-ms thanks for filing this issue, I can confirm that this is indeed the case and we should fix it.

**Comment by statm** [comment]
@khmakoto I gave it a try with @makopch-ms's fix, but it broke too many tests.

**Comment by statm** [comment]
Ping - this is affecting all WAC apps
