### ISSUE TITLE
RTL css flipping is broken for `boxShadow` tokens

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#20572]
In [this codesandbox](https://codesandbox.io/s/nifty-wozniak-hpkkd?file=/example.tsx) you can see that box shadow is broken in RTL mode. This happens in `makeStyles` during [the RTL transform](https://github.com/microsoft/fluentui/blob/6f0dce27ac6e0a85be34b0a12a1c20aa90deae8c/packages/make-styles/src/runtime/resolveStyleRules.ts#L74).

```css
var(--shadow16) /* ltr */
var(--shadow-16) /* rtl */ 🚨🚨🚨
```

This transform is actually done by the [rtl-css-js](https://github.com/kentcdodds/rtl-css-js) package.  An issue (and fix potentially) should be made in that library to correctly handle css variables

**Comment by layershifter** [comment]
It's 99% caused by a regex there: https://github.com/kentcdodds/rtl-css-js/blob/76be2582888884beef054d80049b482fa4d8897a/src/internal/property-value-converters.js#L20
