### ISSUE TITLE
Using React.Fragment to encapsulate StackItems breaks the Stack element behavior.

### ISSUE THREAD

**Issue by An631** [microsoft/fluentui#20586]
Using a React fragment to encapsulate StackItems breaks the default behavior or the Stack due to an if check that verifies if the children prop of ```<Stack>``` contains a ```<StackItem>``` or not. 

```typescript
const StackBug = () => {
  const stackItems = () => (
     <>
        <StackItem>A</StackItem>
        <StackItem>B</StackItem>
     </>
  )
  
  return (
    <Stack>
       { stackItems() }
    </Stack>
  )
}
```

The React.Fragment component should be ignored by the Stack component when doing this check.

https://github.com/microsoft/fluentui/blob/fe9829e4818f9bb7206df37747d5da332706ae4b/packages/react/src/components/Stack/Stack.tsx#L28

**Comment by khmakoto** [comment]
Hi @An631, thanks for filing this issue, this is indeed the case. Would you be willing to make a contribution to fix this issue?

**Comment by An631** [comment]
Sure, although I would need to add the package [react-is](https://www.npmjs.com/package/react-is) to correctly identify the fragment components if that is ok.

**Comment by khmakoto** [comment]
@An631 I don't think that's necessary, you can use `item.type === React.Fragment` to check for this.
