### ISSUE TITLE
node globals leaking within vNext via `process.env`

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#20602]
With Solution TS Configs we will have properly separated environments, so globals wont leak, meaning `types` field will be set accordingly per environment ( tests/node or web ).

After we executed initial migration on `react-card` our pipeline failed. 

> Failed pipeline:
![2021-11-12 at 17 22](https://user-images.githubusercontent.com/1223799/141499759-56a045bd-b645-46b8-8deb-e96ec356b7b4.png)

It turns out there are several usages of `process.env` within implementation code in following packages:
> Example:
> ![2021-11-12 at 17 23](https://user-images.githubusercontent.com/1223799/141499929-31e460d0-8e04-4c72-88dc-3611da2f8c01.png)

- react-utilities
- make-styles
- react-make-styles

### Why is this happening:

- with TS solution config, web/implementation code of our packages has no sense of `NodeJs` environment.
- because we use TS path aliases tsc checks implementation rather than just declaration files (which would not contain `process.env` reference

#### 1. hot fix via local environments.ts and `@ts-ignore`

we can abstract `process.env` access to one module in each package called `environments.ts`, with one `@ts-ignore`

```ts
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
const nodeEnv = process.env.NODE_ENV;

export const isProd = nodeEnv === 'production';
export const isDev = nodeEnv === 'development';
export const isTest = nodeEnv === 'test';
``` 

Now in source we will use:

```diff
+ import {isTest} from './environments';

-if (process.env.NODE_ENV === 'test') {
+if (isTest) {
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    return () => {};
}
```

**Pros:**
- more DRY approach than having globals references in multiple places
- consolidated ts-ignore at one well defined place, which will cause no harm to DX nor to consumers

**Cons:**
- duplication of `environments.ts` in every package

#### 2. creating `environments` package

Similar like solution 1, but extracting those into separate package to keep things DRY

Now in source we will use:

```diff
+ import {isTest} from '@fluentui/environments';

-if (process.env.NODE_ENV === 'test') {
+if (isTest) {
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    return () => {};
}
```

**Pros:**
- DRY 
- no duplication

**Cons:**
- extra package to depend on. 
  - Although when we start rolluping files for production this would be rather mitigated as we can configure it to emit inline - which will be removed in runtime )

#### 3. defining Node globals inline per package

We can declare global variable `process` per package to make `tsc` understand `process.env`

```ts
@filename <package-name/src/globals.d.ts
declare namespace NodeJS {
  interface Process {
    env: {
      NODE_ENV: 'production' | 'development' | 'test';
    };
  }
}

declare const process: NodeJS.Process;
```

**Pros:**
- minimal code changes to existing v9 packages
- no need for "new" environments module pattern ( I consider this a con )

**Cons:**
- allowing to use globals all over the place / inline
- allowing to use non existent browser APIs in browser implementation
- as `tsc -b` will type check storybook and its configs as well, all `process` types would need to be defined per package
  - ![2021-11-15 at 15 34](https://user-images.githubusercontent.com/1223799/141799776-207104e1-463b-4449-8f9d-e2e0cfc09343.png)
  - following declaration would be required:  ![2021-11-15 at 16 03](https://user-images.githubusercontent.com/1223799/141804539-84a3557e-102f-452a-8685-7511b142afbe.png)

#### 4. defining Node globals as separate "global" package within `/typings`

more DRY approach based on no.3

```ts
@filename typings/environments/index.d.ts
declare namespace NodeJS {
  interface Process {
    env: {
      NODE_ENV: 'production' | 'development' | 'test';
    };
  }
}

declare const process: NodeJS.Process;
```

then every package would need to explicitly define globals

```diff
@filename <react-package>/tsconfig.lib.json

{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    ....
-    "types": ["static-assets", "inline-style-expand-shorthand"]
+    "types": ["static-assets", "inline-style-expand-shorthand", "environments"]
  },
  "exclude": [...],
  "include": [...]
}
```

```diff
@filename <react-package>/.storybook/tsconfig.json

{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    ....
    "allowJs": true,
    "checkJs": true,
-    "types": ["static-assets", "inline-style-expand-shorthand", "storybook__addons"],
+    "types": ["static-assets", "inline-style-expand-shorthand", "storybook__addons", "environments"]  
  },
  "exclude": [...],
  "include": [...]
}
```

**Comment by layershifter** [comment]
- We have custom typings in our repo
- We _will_ have separate TS configs for each

Can be there a third option? "Create custom typings for `process.env.NODE_ENV`". This will not require any modifications in code and will not introduce any patterns.

```tsx
declare var process : {
  env: {
    NODE_ENV: 'production' | 'development' | 'test'
  }
}
```

**Comment by Hotell** [comment]
TBH I was thinking about that as well. Having environments in one place is from my experience better approach of "encapsulation" rather than using globals all over the place. 

As a follow-up we can/should introduce following rule https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-process-env.md

**Comment by Hotell** [comment]
I'll add it as solution #3 and we can discuss it on tech sync. thanks

**Comment by Hotell** [comment]
added solution 4 as well. 

Based on extended testing we discovered that webpack + terser are unable to tree shake process.env.NODE_ENV references in code if they are abstracted away (Solution 1 and 2)
