### ISSUE TITLE
When Split button has focus, can't use mouse to choose the dropdown

### ISSUE THREAD

**Issue by jmagaram** [microsoft/fluentui#20608]
### Environment Information

- **Package version(s)**: 8.41.4
- **Browser and OS versions**: Chrome and Edge on Windows 10

### Please provide a reproduction of the bug in a codepen:

https://developer.microsoft.com/en-us/fluentui#/controls/web/button

Scroll down to the "Split Button" examples. Click "Primary" to get the focus there. Then Shift+Tab to move focus to "Standard". Now, with the mouse, attempt to click on the down/chevron to pop open the menu. Notice how the button is pressed but the menu won't pop open.

#### Actual behavior:

Clicking with mouse on the down/chevron causes default button behavior to happen.

#### Expected behavior:

Should always be able to click on the down/chevron regardless of whether the split button has the focus.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

### Notes

I am going to have to abandon usage of the split button because of this. I put the default focus there so the user can quickly click Enter to make the action happen. But I want the user to be able to choose the alternate options from the split. Using Alt+Downarrow works but many people won't know about this. I expect users to use the mouse but there is no way to make the split open unless the button does NOT have the focus.

**Comment by gouttierre** [comment]
@jmagaram - thanks for filing this issue. I was unable to reproduce your stated problem in the issue. 
Please, could you confirm the issue persists? Thank you

**Comment by jmagaram** [comment]
Please try to repro again. I just reprod this bug in Edge AND Firefox on Windows 11. On Edge, after the split button has the focus, when you move the mouse over the split button part it does NOT get highlighted/register when the pointer is in the middle of the target. Only when the pointer is at the edge of the target. On Firefox you have to click twice on the split button part for it to work. I tried making a video but it is too small.

**Comment by sanjeewajayasinghe** [comment]
I have a repro for this issue in the official page https://developer.microsoft.com/en-us/fluentui#/controls/web/button

![SplitButtonIssueWhenFocused](https://user-images.githubusercontent.com/4142777/174137505-92252b4a-2ab9-4384-9418-8f72b0a304ac.gif)

Any updates?

**Comment by gouttierre** [comment]
This issue has been queued for upcoming investigations. To set expectations the developers will review this issue once capacity allows and all updates will be posted on the issue accordingly.

**Comment by miroslavstastny** [comment]
This seems to be a bug in the focus ring element capturing mouse events.

`SplitButton` renders two `button` elements inside a `div`:
```html
div
  button
  button
```

When the `SplitButton` is focused, `:after` pseudoelement is added to the wrapping `div` to display a focus ring around both buttons - this now captures all the events:
- when hovered, arrow mouse cursor is used instead of the pointer
- it is not possible to click the secondary button

**Comment by hoovercj** [comment]
@jmagaram @emkessle I was able to mitigate the issue by adding `pointerEvents: "none"` as a style using code similar to this (or in a css/scss file via a class name):

```typescript
<PrimaryButton
    split
    styles={{
        splitButtonContainer: {
            ":focus:after": {
                pointerEvents: "none",
            },
        },
    }}
/>
```

I hope that helps!

**Comment by miroslavstastny** [comment]
@khmakoto - could you please check the related PR #25088
