### ISSUE TITLE
TextField input doesn't clear when value set to undefined

### ISSUE THREAD

**Issue by v-dhampton** [microsoft/fluentui#20616]
When a controlled TextField value is set to undefined, when it was another non-null value, the displayed value is resetting to a previously entered value instead of empty as is expected.

Note: Within the app this problem was found, setting the value to null also caused the issue but it does not appear to do so in the codepen.

### Environment Information

- **Package version(s)**: "@fluentui/react": "^7.172.0"
- **Browser and OS versions**: Microsoft Edge Version 95.0.1020.44 (Official build) (64-bit)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/v-dhampton/pen/VwzVMEK

#### Actual behavior:

When the controlled value of a TextField input is set to undefined from another value, the displayed value is a previously entered value.

#### Expected behavior:

When the controlled value of a TextField input is set to undefined from another value, the displayed value should be empty.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: (if applicable)
https://aka.ms/mc

**Comment by gokul-369** [comment]
You are facing this issue because the TextField value prop is out of Sync with your current value, I would suggest that You pass a state variable to the value prop and along with that you should also have an onChange() function where you can modify the value of the state, otherwise your TextField will only be read only.

**Comment by gouttierre** [comment]
2v-dhampton - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows. I see the repro in the codepen. When the controlled value of a TextField input is set to undefined from another value, it retains 1st character of value is a previously entered value, and if repeated it appends the single character to the previous one.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by srgudipuMS** [comment]
Is there a workaround for this issue? We are seeing this as well ( azure portal).

**Comment by bsunderhus** [comment]
Perhaps using an empty string instead of undefined for the empty state should resolve as workaround. The problem using `undefined` as controlled value is that it actually conflicts with the way React operates between controlled and uncontrolled states.

**Comment by micahgodbolt** [comment]
setting the value to an empty string is the correct approach as that is what you would need to do to properly empty out a <input />
