### ISSUE TITLE
<DatePicker> Need a way to have a default date in focus but not selected

### ISSUE THREAD

**Issue by yzheng72** [microsoft/fluentui#20623]
Currently when we pass in the "value" parameter for Calendar, it will have that date rendered as selected (applying both background highlight and focus).
In our use case, we'd like to pass in a date as a suggestion so that the date cell can be focused by default, but not applying the background highlight since user hasn't explictly selected the date yet.
From what I can tell, there is no existing props can do that. Is this something can be added as we have a valid use case in Fluid(Loop)?

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [DatePicker](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/datepicker) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by yzheng72** [comment]
This can be observed with the DatePicker examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

For example:
This is what the picker looks like where there is no date be selected yet. And date 13th has both border and background color added by default.
<img width="413" alt="image" src="https://user-images.githubusercontent.com/6943276/149398048-052ab62f-34d6-4a4c-8b22-1a56dadb0305.png">

Once I select a date, 15th for example, the UI looks like this:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/6943276/149398212-8cf794c8-dd29-4a96-b83a-7f5db35e4b7b.png">

Notice that the UI treatment is identical to the previous picture. We got feedback that this can be confusing as user can be unsure if a date has been selected or not.
