### ISSUE TITLE
ContextMenu _adjustedFocusZoneProps cannot be overwritten.

### ISSUE THREAD

**Issue by KristapsLeitens** [microsoft/fluentui#20620]
### Environment Information

- **Package version(s)**:  8.42.0
- **Browser and OS versions**: Windows 10 and Google Chrome

### Describe the issue:

When using Fluent UI library in other projects we need to disable tabKey handling.
Currently it's not possible because in UIContextualBase.tsx file _adjustedFocusZoneProps property that is being overwritten.

#### Actual behavior:

Setting custom FocusZone properties for ContextMenu and they are being ignored.
const adjustedFocusZoneProps = {
      ...focusZoneProps,
    className: classNames.root,
    isCircularNavigation: true,
    handleTabKey: FocusZoneTabbableElements.all,
    direction: props.focusZoneProps?.direction ?? FocusZoneDirection.vertical,
  };

#### Expected behavior:

Setting custom FocusZone properties for ContextMenu and they are used.
const adjustedFocusZoneProps = {
  className: classNames.root,
  isCircularNavigation: true,
  handleTabKey: FocusZoneTabbableElements.all,
  direction: props.focusZoneProps?.direction ?? FocusZoneDirection.vertical,
    ...focusZoneProps
};

Priorities and help requested:
Are you willing to submit a PR to fix? no

Requested priority: Medium

**Comment by khmakoto** [comment]
Hi @KristapsLeitens, I can confirm that this is indeed happening and that I'm working on a PR to fix this.
