### ISSUE TITLE
Potential Memory Leak on ContextualMenu

### ISSUE THREAD

**Issue by gingeroun** [microsoft/fluentui#20633]
### Environment Information

Package version(s): "@fluentui/react": "^8.15.1"
Browser and OS versions: Edge/Chrome, Windows

### Please provide a reproduction of the bug:
You can reproduce the memory leak with the control available in the documentation: https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu
Make sure you select one of the options, like shown below:
![image](https://user-images.githubusercontent.com/22574161/142065849-25aad8e9-b537-44ea-b3e4-cc60fd411ce6.png)

#### Actual behavior:
I want to use the contextualmenu for implementing a new feature for Microsoft Teams.
<br>But while checking for memory leaks I noticed that the control stays in memory after GC
![image](https://user-images.githubusercontent.com/22574161/142061876-80e25724-7bda-484d-8f90-6c97126b7d02.png)

And If I keep clicking it's growing. (The picture is after I clicked on GC)
![image](https://user-images.githubusercontent.com/22574161/142063726-e707257b-1d3f-4fe6-b5ac-a0a5b70d74ca.png)

This is what I get from the Heap Snapshot after GC
![image](https://user-images.githubusercontent.com/22574161/142064256-50819d69-2700-4299-b3c1-07f48bcee70d.png)

I also tried to completely isolate the specific control on a testpage by keeping only the mandatory properties (I have even removed clickHandlers and text):

 
```
import React from 'react';

import {  IContextualMenuProps } from '@fluentui/react/lib/ContextualMenu';

import { DefaultButton } from '@fluentui/react/lib/Button';

export const App: React.FunctionComponent = () => {

  const menuProps: IContextualMenuProps = {

    items: [{ key: 'newItem' }],

  };

  return (

    <DefaultButton menuProps={menuProps}/>

  );

};

```

 and I was still getting the same result (the control stayed in memory).
 
![image](https://user-images.githubusercontent.com/22574161/142064671-0136f9a9-1595-467f-8f81-5442e83a3b32.png)

#### Expected behavior:

The control shouldn't bloat/leak memory by holding onto references

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High)

Products/sites affected: Teams, Live Persona Card

**Comment by gouttierre** [comment]
@gingeroun - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression issue?
