### ISSUE TITLE
[Panel] Header has a background color (but only when the screen size is larger)

### ISSUE THREAD

**Issue by lucas-stanford** [microsoft/fluentui#20643]
![panel header changes background color](https://user-images.githubusercontent.com/3011776/142332181-3b41ef95-fc18-4f4f-a825-7dc57edd4d02.gif)

The color is causing problems to people who have set the background of their panel. If we keep it like this when someone wants to change the background of the panel you will need to know to change it in two spots. (and if the screen is small they might not notice there is a problem on larger screens)

### Environment Information

- **Package version(s)**: 8.30.1 -> 8.41.4 (current as of this writing)
- **Browser and OS versions**: chrome

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/fordfordford/pen/KKvJdBE

#### Actual behavior:
The header has a background color when the screen is larger, but doesn't when it's smaller. 

The background of the header was added in 8.30.1, previously there was not a background color.

#### Expected behavior:
Prefer if the header never had a background color. So when you set a background color to main style it was respected. 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) no

Requested priority: (Blocking, High, Normal, Low) Normal

**Comment by gouttierre** [comment]
@lucas-stanford  - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@TristanWatanabe - I see you have assigned this item to yourself. It has been added to the Shield project board.
