### ISSUE TITLE
Can not change DetailsRow's font color when use onRenderRow in DetailList

### ISSUE THREAD

**Issue by it950** [microsoft/fluentui#20647]
### Environment Information

- **Package version(s)**: (fluentui/react ^8.29.1)
- **Browser and OS versions**: (Edge latest version)

My project has been updated from OfficeUI Fabric 7(v7) to FluentUI/react 8(v8), 
use onRenderRow in DetailList to override the default row rendering, 
the row' font color can be changed when pass a color to styles props of DetailsRow  in v7, 
but it can not take affect in v8.

How to change the row's font color by row's field value?

Thanks.

``` javascript 
const _onRenderRow = React.useCallback(
    (props) => {
      if (props) {
        const { item } = props;
        const displayValue = onDisplay && onDisplay(item);
        if (displayValue) {
          const {  color} = displayValue;
          return <DetailsRow {...props} styles={{ root: {  color } }} />;
        }

        return <DetailsRow {...props} />;
      }

      return null;
    },
    [onDisplay]
  );
```

**Comment by gouttierre** [comment]
@it950 - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [DetailsList ](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by it950** [comment]
@gouttierre Thanks for your reply, I found the reason is that the return value of onRenderItemColumn will override onRenderRow,
CodePen example: 
https://codepen.io/it950/pen/mdBGgYK?editors=1010
