### ISSUE TITLE
Dropdown Callout incorrectly resizes when width set to "fit-content"

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#20655]
### Environment Information

- **Package version(s)**: 8.34.4
- **Browser and OS versions**: Windows 11, Edge 95.0.1020.53, Chrome 96.0.4664.45, Firefox 94.0.1

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/nadavrosenthal/pen/ExvmKMo?editors=1010

Use the keyboard or Narrator to navigate the list, selecting and unselecting items.

#### Actual behavior:

The Dropdown list adjusts its width. I believe this is due to width being set to "fit-content" on the Dropdown.

![dropdown_fitcontent](https://user-images.githubusercontent.com/93940821/142472414-5484ebab-e873-45f8-9d5a-9660ab4e4713.png)

#### Expected behavior:

My feeling is that it's okay that the Callout dynamically resizes but the content in the Callout should never be clipped.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal or Low

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@spmonahan - I see there was a merged #20656 for this issue?

**Comment by spmonahan** [comment]
@gouttierre I opened this issue when working on the PR for the merged issue. This issue is still present in v8.

**Comment by gouttierre** [comment]
Closing issue. Please resubmit if the issue persists. Thanks
