### ISSUE TITLE
Document has active elements with the same id attribute: Pivot995-Tab7 in Pivot overflow

### ISSUE THREAD

**Issue by linazar** [microsoft/fluentui#20663]
### Environment Information

- **Package version(s)**: Fluent React 8.42.3
- **Browser and OS versions**: Edge 95.0.1020.44 ; Windows 11 Enterprise

### Describe the issue:

Document has active elements with the same id attribute: Pivot995-Tab7

#### Actual behavior:

Document has active elements with the same id attribute: Pivot995-Tab7

#### Expected behavior:

Ensure tabs in overflow menu have unique id attributes

### If applicable, please provide a codepen repro:

1) Navigate to https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/pivot, make sure 8.42.3 is selected

2) scroll all the way to Pivot with overflow menu

3) (This is critical step!) Click on the three dots, so that "The Last Tab" shows up. 

4) Run FastPass - make sure (this is critical!) that the "The Last Tab" is still visible.

**Comment by gouttierre** [comment]
@linazar - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows. Thank you for the repro steps and I do see the mentioned problem. 

![image](https://user-images.githubusercontent.com/78806055/148246827-d20a8756-a32a-4609-bbf9-6463dfdfa195.png)

@spmonahan / @smhigley - would either of you be able to review this issue?
