### ISSUE TITLE
not working in angular 13

### ISSUE THREAD

**Issue by gyansoft786** [microsoft/fluentui#20669]
to reproduce, clone following repo : [https://github.com/gyansoft786/angular-fluent-webcomponets.git](https://github.com/gyansoft786/angular-fluent-webcomponets.git)

looks like some typing issue . when i run ng serve command, i got following result

`

> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:246:26 - error TS2320: Interface 'Anchor' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIALink'.
>   Named property 'ariaAtomic' of types 'FoundationElement' and 'DelegatesARIALink' are not identical.
> 
> 246 export declare interface Anchor extends StartEnd, DelegatesARIALink {
>                              ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:246:26 - error TS2320: Interface 'Anchor' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIALink'.
>   Named property 'ariaBusy' of types 'FoundationElement' and 'DelegatesARIALink' are not identical.
> 
> 246 export declare interface Anchor extends StartEnd, DelegatesARIALink {
>                              ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:246:26 - error TS2320: Interface 'Anchor' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIALink'.
>   Named property 'ariaDisabled' of types 'FoundationElement' and 'DelegatesARIALink' are not identical.
> 
> 246 export declare interface Anchor extends StartEnd, DelegatesARIALink {
>                              ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:246:26 - error TS2320: Interface 'Anchor' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIALink'.
>   Named property 'ariaExpanded' of types 'FoundationElement' and 'DelegatesARIALink' are not identical.
> 
> 246 export declare interface Anchor extends StartEnd, DelegatesARIALink {
>                              ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:246:26 - error TS2320: Interface 'Anchor' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIALink'.
>   Named property 'ariaHidden' of types 'FoundationElement' and 'DelegatesARIALink' are not identical.
> 
> 246 export declare interface Anchor extends StartEnd, DelegatesARIALink {
>                              ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:246:26 - error TS2320: Interface 'Anchor' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIALink'.
>   Named property 'ariaLive' of types 'FoundationElement' and 'DelegatesARIALink' are not identical.
> 
> 246 export declare interface Anchor extends StartEnd, DelegatesARIALink {
>                              ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1033:26 - error TS2320: Interface 'BreadcrumbItem' cannot simultaneously extend types 'Anchor' and 'DelegatesARIALink'.
>   Named property 'ariaAtomic' of types 'Anchor' and 'DelegatesARIALink' are not identical.
> 
> 1033 export declare interface BreadcrumbItem extends StartEnd, DelegatesARIALink {
>                               ~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1033:26 - error TS2320: Interface 'BreadcrumbItem' cannot simultaneously extend types 'Anchor' and 'DelegatesARIALink'.
>   Named property 'ariaBusy' of types 'Anchor' and 'DelegatesARIALink' are not identical.
> 
> 1033 export declare interface BreadcrumbItem extends StartEnd, DelegatesARIALink {
>                               ~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1033:26 - error TS2320: Interface 'BreadcrumbItem' cannot simultaneously extend types 'Anchor' and 'DelegatesARIALink'.
>   Named property 'ariaDisabled' of types 'Anchor' and 'DelegatesARIALink' are not identical.
> 
> 1033 export declare interface BreadcrumbItem extends StartEnd, DelegatesARIALink {
>                               ~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1033:26 - error TS2320: Interface 'BreadcrumbItem' cannot simultaneously extend types 'Anchor' and 'DelegatesARIALink'.
>   Named property 'ariaExpanded' of types 'Anchor' and 'DelegatesARIALink' are not identical.
> 
> 1033 export declare interface BreadcrumbItem extends StartEnd, DelegatesARIALink {
>                               ~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1033:26 - error TS2320: Interface 'BreadcrumbItem' cannot simultaneously extend types 'Anchor' and 'DelegatesARIALink'.
>   Named property 'ariaHidden' of types 'Anchor' and 'DelegatesARIALink' are not identical.
> 
> 1033 export declare interface BreadcrumbItem extends StartEnd, DelegatesARIALink {
>                               ~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1033:26 - error TS2320: Interface 'BreadcrumbItem' cannot simultaneously extend types 'Anchor' and 'DelegatesARIALink'.
>   Named property 'ariaLive' of types 'Anchor' and 'DelegatesARIALink' are not identical.
> 
> 1033 export declare interface BreadcrumbItem extends StartEnd, DelegatesARIALink {
>                               ~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1168:26 - error TS2320: Interface 'Button' cannot simultaneously extend types 'FormAssociatedButton' and 'DelegatesARIAButton'.
>   Named property 'ariaAtomic' of types 'FormAssociatedButton' and 'DelegatesARIAButton' are not identical.
> 
> 1168 export declare interface Button extends StartEnd, DelegatesARIAButton {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1168:26 - error TS2320: Interface 'Button' cannot simultaneously extend types 'FormAssociatedButton' and 'DelegatesARIAButton'.
>   Named property 'ariaBusy' of types 'FormAssociatedButton' and 'DelegatesARIAButton' are not identical.
> 
> 1168 export declare interface Button extends StartEnd, DelegatesARIAButton {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1168:26 - error TS2320: Interface 'Button' cannot simultaneously extend types 'FormAssociatedButton' and 'DelegatesARIAButton'.
>   Named property 'ariaDisabled' of types 'FormAssociatedButton' and 'DelegatesARIAButton' are not identical.
> 
> 1168 export declare interface Button extends StartEnd, DelegatesARIAButton {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1168:26 - error TS2320: Interface 'Button' cannot simultaneously extend types 'FormAssociatedButton' and 'DelegatesARIAButton'.
>   Named property 'ariaExpanded' of types 'FormAssociatedButton' and 'DelegatesARIAButton' are not identical.
> 
> 7m1168 export declare interface Button extends StartEnd, DelegatesARIAButton {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1168:26 - error TS2320: Interface 'Button' cannot simultaneously extend types 'FormAssociatedButton' and 'DelegatesARIAButton'.
>   Named property 'ariaHidden' of types 'FormAssociatedButton' and 'DelegatesARIAButton' are not identical.
> 
> 1168 export declare interface Button extends StartEnd, DelegatesARIAButton {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1168:26 - error TS2320: Interface 'Button' cannot simultaneously extend types 'FormAssociatedButton' and 'DelegatesARIAButton'.
>   Named property 'ariaLive' of types 'FormAssociatedButton' and 'DelegatesARIAButton' are not identical.
> 
> 1168 export declare interface Button extends StartEnd, DelegatesARIAButton {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1168:26 - error TS2320: Interface 'Button' cannot simultaneously extend types 'FormAssociatedButton' and 'DelegatesARIAButton'.
>   Named property 'ariaPressed' of types 'FormAssociatedButton' and 'DelegatesARIAButton' are not identical.
> 
> 1168 export declare interface Button extends StartEnd, DelegatesARIAButton {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1806:26 - error TS2320: Interface 'Combobox' cannot simultaneously extend types 'FormAssociatedCombobox' and 'DelegatesARIACombobox'.
>   Named property 'ariaAtomic' of types 'FormAssociatedCombobox' and 'DelegatesARIACombobox' are not identical.
> 
> 1806 export declare interface Combobox extends StartEnd, DelegatesARIACombobox {
>                               ~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1806:26 - error TS2320: Interface 'Combobox' cannot simultaneously extend types 'FormAssociatedCombobox' and 'DelegatesARIACombobox'.
>   Named property 'ariaBusy' of types 'FormAssociatedCombobox' and 'DelegatesARIACombobox' are not identical.
> 
> 1806 export declare interface Combobox extends StartEnd, DelegatesARIACombobox {
>                               ~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1806:26 - error TS2320: Interface 'Combobox' cannot simultaneously extend types 'FormAssociatedCombobox' and 'DelegatesARIACombobox'.
>   Named property 'ariaDisabled' of types 'FormAssociatedCombobox' and 'DelegatesARIACombobox' are not identical.
> 
> 1806 export declare interface Combobox extends StartEnd, DelegatesARIACombobox {
>                               ~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1806:26 - error TS2320: Interface 'Combobox' cannot simultaneously extend types 'FormAssociatedCombobox' and 'DelegatesARIACombobox'.
>   Named property 'ariaHidden' of types 'FormAssociatedCombobox' and 'DelegatesARIACombobox' are not identical.
> 
> 1806 export declare interface Combobox extends StartEnd, DelegatesARIACombobox {
>                               ~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:1806:26 - error TS2320: Interface 'Combobox' cannot simultaneously extend types 'FormAssociatedCombobox' and 'DelegatesARIACombobox'.
>   Named property 'ariaLive' of types 'FormAssociatedCombobox' and 'DelegatesARIACombobox' are not identical.
> 
> 1806 export declare interface Combobox extends StartEnd, DelegatesARIACombobox {
>                               ~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:4626:26 - error TS2320: Interface 'Listbox' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIAListbox'.
>   Named property 'ariaAtomic' of types 'FoundationElement' and 'DelegatesARIAListbox' are not identical.
> 
> 4626 export declare interface Listbox extends DelegatesARIAListbox {
>                               ~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:4626:26 - error TS2320: Interface 'Listbox' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIAListbox'.
>   Named property 'ariaBusy' of types 'FoundationElement' and 'DelegatesARIAListbox' are not identical.
> 
> 4626 export declare interface Listbox extends DelegatesARIAListbox {
>                               ~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:4626:26 - error TS2320: Interface 'Listbox' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIAListbox'.
>   Named property 'ariaDisabled' of types 'FoundationElement' and 'DelegatesARIAListbox' are not identical.
> 
> 4626 export declare interface Listbox extends DelegatesARIAListbox {
>                               ~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:4626:26 - error TS2320: Interface 'Listbox' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIAListbox'.
>   Named property 'ariaExpanded' of types 'FoundationElement' and 'DelegatesARIAListbox' are not identical.
> 
> 4626 export declare interface Listbox extends DelegatesARIAListbox {
>                               ~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:4626:26 - error TS2320: Interface 'Listbox' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIAListbox'.
>   Named property 'ariaHidden' of types 'FoundationElement' and 'DelegatesARIAListbox' are not identical.
> 
> 4626 export declare interface Listbox extends DelegatesARIAListbox {
>                               ~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:4626:26 - error TS2320: Interface 'Listbox' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIAListbox'.
>   Named property 'ariaLive' of types 'FoundationElement' and 'DelegatesARIAListbox' are not identical.
> 
> 4626 export declare interface Listbox extends DelegatesARIAListbox {
>                               ~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:5325:26 - error TS2320: Interface 'NumberField' cannot simultaneously extend types 'FormAssociatedNumberField' and 'DelegatesARIATextbox'.
>   Named property 'ariaAtomic' of types 'FormAssociatedNumberField' and 'DelegatesARIATextbox' are not identical.
> 
> 5325 export declare interface NumberField extends StartEnd, DelegatesARIATextbox {
>                               ~~~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:5325:26 - error TS2320: Interface 'NumberField' cannot simultaneously extend types 'FormAssociatedNumberField' and 'DelegatesARIATextbox'.
>   Named property 'ariaBusy' of types 'FormAssociatedNumberField' and 'DelegatesARIATextbox' are not identical.
> 
> 5325 export declare interface NumberField extends StartEnd, DelegatesARIATextbox {
>                               ~~~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:5325:26 - error TS2320: Interface 'NumberField' cannot simultaneously extend types 'FormAssociatedNumberField' and 'DelegatesARIATextbox'.
>   Named property 'ariaDisabled' of types 'FormAssociatedNumberField' and 'DelegatesARIATextbox' are not identical.
> 
> 5325 export declare interface NumberField extends StartEnd, DelegatesARIATextbox {
>                               ~~~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:5325:26 - error TS2320: Interface 'NumberField' cannot simultaneously extend types 'FormAssociatedNumberField' and 'DelegatesARIATextbox'.
>   Named property 'ariaHidden' of types 'FormAssociatedNumberField' and 'DelegatesARIATextbox' are not identical.
> 
> 5325 export declare interface NumberField extends StartEnd, DelegatesARIATextbox {
>                               ~~~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:5325:26 - error TS2320: Interface 'NumberField' cannot simultaneously extend types 'FormAssociatedNumberField' and 'DelegatesARIATextbox'.
>   Named property 'ariaLive' of types 'FormAssociatedNumberField' and 'DelegatesARIATextbox' are not identical.
> 
> 5325 export declare interface NumberField extends StartEnd, DelegatesARIATextbox {
>                               ~~~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:6567:26 - error TS2320: Interface 'Search' cannot simultaneously extend types 'FormAssociatedSearch' and 'DelegatesARIASearch'.
>   Named property 'ariaAtomic' of types 'FormAssociatedSearch' and 'DelegatesARIASearch' are not identical.
> 
> 6567 export declare interface Search extends StartEnd, DelegatesARIASearch {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:6567:26 - error TS2320: Interface 'Search' cannot simultaneously extend types 'FormAssociatedSearch' and 'DelegatesARIASearch'.
>   Named property 'ariaBusy' of types 'FormAssociatedSearch' and 'DelegatesARIASearch' are not identical.
> 
> 6567 export declare interface Search extends StartEnd, DelegatesARIASearch {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:6567:26 - error TS2320: Interface 'Search' cannot simultaneously extend types 'FormAssociatedSearch' and 'DelegatesARIASearch'.
>   Named property 'ariaDisabled' of types 'FormAssociatedSearch' and 'DelegatesARIASearch' are not identical.
> 
> 6567 export declare interface Search extends StartEnd, DelegatesARIASearch {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:6567:26 - error TS2320: Interface 'Search' cannot simultaneously extend types 'FormAssociatedSearch' and 'DelegatesARIASearch'.
>   Named property 'ariaHidden' of types 'FormAssociatedSearch' and 'DelegatesARIASearch' are not identical.
> 
> 6567 export declare interface Search extends StartEnd, DelegatesARIASearch {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:6567:26 - error TS2320: Interface 'Search' cannot simultaneously extend types 'FormAssociatedSearch' and 'DelegatesARIASearch'.
>   Named property 'ariaLive' of types 'FormAssociatedSearch' and 'DelegatesARIASearch' are not identical.
> 
> 6567 export declare interface Search extends StartEnd, DelegatesARIASearch {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:6735:26 - error TS2320: Interface 'Select' cannot simultaneously extend types 'FormAssociatedSelect' and 'DelegatesARIASelect'.
>   Named property 'ariaAtomic' of types 'FormAssociatedSelect' and 'DelegatesARIASelect' are not identical.
> 
> 6735 export declare interface Select extends StartEnd, DelegatesARIASelect {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:6735:26 - error TS2320: Interface 'Select' cannot simultaneously extend types 'FormAssociatedSelect' and 'DelegatesARIASelect'.
>   Named property 'ariaBusy' of types 'FormAssociatedSelect' and 'DelegatesARIASelect' are not identical.
> 
> 6735 export declare interface Select extends StartEnd, DelegatesARIASelect {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:6735:26 - error TS2320: Interface 'Select' cannot simultaneously extend types 'FormAssociatedSelect' and 'DelegatesARIASelect'.
>   Named property 'ariaDisabled' of types 'FormAssociatedSelect' and 'DelegatesARIASelect' are not identical.
> 
> 6735 export declare interface Select extends StartEnd, DelegatesARIASelect {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:6735:26 - error TS2320: Interface 'Select' cannot simultaneously extend types 'FormAssociatedSelect' and 'DelegatesARIASelect'.
>   Named property 'ariaExpanded' of types 'FormAssociatedSelect' and 'DelegatesARIASelect' are not identical.
> 
> 6735 export declare interface Select extends StartEnd, DelegatesARIASelect {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:6735:26 - error TS2320: Interface 'Select' cannot simultaneously extend types 'FormAssociatedSelect' and 'DelegatesARIASelect'.
>   Named property 'ariaHidden' of types 'FormAssociatedSelect' and 'DelegatesARIASelect' are not identical.
> 
> 6735 export declare interface Select extends StartEnd, DelegatesARIASelect {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:6735:26 - error TS2320: Interface 'Select' cannot simultaneously extend types 'FormAssociatedSelect' and 'DelegatesARIASelect'.
>   Named property 'ariaLive' of types 'FormAssociatedSelect' and 'DelegatesARIASelect' are not identical.
> 
> 6735 export declare interface Select extends StartEnd, DelegatesARIASelect {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:6735:26 - error TS2320: Interface 'Select' cannot simultaneously extend types 'FormAssociatedSelect' and 'DelegatesARIASelect'.
>   Named property 'ariaPressed' of types 'FormAssociatedSelect' and 'DelegatesARIASelect' are not identical.
> 
> 6735 export declare interface Select extends StartEnd, DelegatesARIASelect {
>                               ~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7636:26 - error TS2320: Interface 'TextArea' cannot simultaneously extend types 'FormAssociatedTextArea' and 'DelegatesARIATextbox'.
>   Named property 'ariaAtomic' of types 'FormAssociatedTextArea' and 'DelegatesARIATextbox' are not identical.
> 
> 7636 export declare interface TextArea extends DelegatesARIATextbox {
>                               ~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7636:26 - error TS2320: Interface 'TextArea' cannot simultaneously extend types 'FormAssociatedTextArea' and 'DelegatesARIATextbox'.
>   Named property 'ariaBusy' of types 'FormAssociatedTextArea' and 'DelegatesARIATextbox' are not identical.
> 
> 7636 export declare interface TextArea extends DelegatesARIATextbox {
>                               ~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7636:26 - error TS2320: Interface 'TextArea' cannot simultaneously extend types 'FormAssociatedTextArea' and 'DelegatesARIATextbox'.
>   Named property 'ariaDisabled' of types 'FormAssociatedTextArea' and 'DelegatesARIATextbox' are not identical.
> 
> 7636 export declare interface TextArea extends DelegatesARIATextbox {
>                               ~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7636:26 - error TS2320: Interface 'TextArea' cannot simultaneously extend types 'FormAssociatedTextArea' and 'DelegatesARIATextbox'.
>   Named property 'ariaHidden' of types 'FormAssociatedTextArea' and 'DelegatesARIATextbox' are not identical.
> 
> 7636 export declare interface TextArea extends DelegatesARIATextbox {
>                               ~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7636:26 - error TS2320: Interface 'TextArea' cannot simultaneously extend types 'FormAssociatedTextArea' and 'DelegatesARIATextbox'.
>   Named property 'ariaLive' of types 'FormAssociatedTextArea' and 'DelegatesARIATextbox' are not identical.
> 
> 7636 export declare interface TextArea extends DelegatesARIATextbox {
>                               ~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7798:26 - error TS2320: Interface 'TextField' cannot simultaneously extend types 'FormAssociatedTextField' and 'DelegatesARIATextbox'.
>   Named property 'ariaAtomic' of types 'FormAssociatedTextField' and 'DelegatesARIATextbox' are not identical.
> 
> 7798 export declare interface TextField extends StartEnd, DelegatesARIATextbox {
>                               ~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7798:26 - error TS2320: Interface 'TextField' cannot simultaneously extend types 'FormAssociatedTextField' and 'DelegatesARIATextbox'.
>   Named property 'ariaBusy' of types 'FormAssociatedTextField' and 'DelegatesARIATextbox' are not identical.
> 
> 7798 export declare interface TextField extends StartEnd, DelegatesARIATextbox {
>                               ~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7798:26 - error TS2320: Interface 'TextField' cannot simultaneously extend types 'FormAssociatedTextField' and 'DelegatesARIATextbox'.
>   Named property 'ariaDisabled' of types 'FormAssociatedTextField' and 'DelegatesARIATextbox' are not identical.
> 
> 7798 export declare interface TextField extends StartEnd, DelegatesARIATextbox {
>                               ~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7798:26 - error TS2320: Interface 'TextField' cannot simultaneously extend types 'FormAssociatedTextField' and 'DelegatesARIATextbox'.
>   Named property 'ariaHidden' of types 'FormAssociatedTextField' and 'DelegatesARIATextbox' are not identical.
> 
> 7798 export declare interface TextField extends StartEnd, DelegatesARIATextbox {
>                               ~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7798:26 - error TS2320: Interface 'TextField' cannot simultaneously extend types 'FormAssociatedTextField' and 'DelegatesARIATextbox'.
>   Named property 'ariaLive' of types 'FormAssociatedTextField' and 'DelegatesARIATextbox' are not identical.
> 
> 7798 export declare interface TextField extends StartEnd, DelegatesARIATextbox {
>                               ~~~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7965:26 - error TS2320: Interface 'Toolbar' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIAToolbar'.
>   Named property 'ariaAtomic' of types 'FoundationElement' and 'DelegatesARIAToolbar' are not identical.
> 
> 7965 export declare interface Toolbar extends StartEnd, DelegatesARIAToolbar {
>                               ~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7965:26 - error TS2320: Interface 'Toolbar' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIAToolbar'.
>   Named property 'ariaBusy' of types 'FoundationElement' and 'DelegatesARIAToolbar' are not identical.
> 
> 7965 export declare interface Toolbar extends StartEnd, DelegatesARIAToolbar {
>                               ~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7965:26 - error TS2320: Interface 'Toolbar' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIAToolbar'.
>   Named property 'ariaDisabled' of types 'FoundationElement' and 'DelegatesARIAToolbar' are not identical.
> 
> 7965 export declare interface Toolbar extends StartEnd, DelegatesARIAToolbar {
>                               ~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7965:26 - error TS2320: Interface 'Toolbar' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIAToolbar'.
>   Named property 'ariaHidden' of types 'FoundationElement' and 'DelegatesARIAToolbar' are not identical.
> 
> 7965 export declare interface Toolbar extends StartEnd, DelegatesARIAToolbar {
>                               ~~~~~~~
> 
> 
> Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:7965:26 - error TS2320: Interface 'Toolbar' cannot simultaneously extend types 'FoundationElement' and 'DelegatesARIAToolbar'.
>   Named property 'ariaLive' of types 'FoundationElement' and 'DelegatesARIAToolbar' are not identical.
> 
> 7965 export declare interface Toolbar extends StartEnd, DelegatesARIAToolbar {
>                               ~~~~~~~
> 
> 
> 
> 
> ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
> 
> 
> × Failed to compile.

`

**Comment by gyansoft786** [comment]
**Update** : fluent web components are working perfectly with angular 12. 
Thanks

**Comment by gyansoft786** [comment]
any update on this ??
Please!

**Comment by Ionaru** [comment]
See https://github.com/microsoft/fast/issues/5198

**Comment by gouttierre** [comment]
@gyansoft786 - thanks for filing this issue with us. Please, can you review microsoft/fast#5198 to confirm if that solves your problem. Thanks
