### ISSUE TITLE
Required ARIA children role not present in Pivot overflow 

### ISSUE THREAD

**Issue by linazar** [microsoft/fluentui#20661]
### Environment Information

- **Package version(s)**: Fluent React 8.42.3
- **Browser and OS versions**: Edge 95.0.1020.44 ; Windows 11 Enterprise

### Describe the issue:

Required ARIA children role not present in Pivot overflow 

#### Actual behavior:

Required ARIA children role not present:

#### Expected behavior:

Add ARIA children role to overflow menu: group, menuitemradio, menuitem, menuitemcheckbox

### If applicable, please provide a codepen repro:

1) Navigate to https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/pivot, make sure 8.42.3 is selected

2) scroll all the way to Pivot with overflow menu

3) (This is critical step!) Click on the three dots, so that "The Last Tab" shows up. 

4) Run FastPass - make sure (this is critical!) that the "The Last Tab" is still visible.

**Comment by gouttierre** [comment]
@linazar - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows. Thank you for the repro steps and I do see the mentioned problem. 

![image](https://user-images.githubusercontent.com/78806055/148245506-21f2b272-6088-46f3-88ec-b7c34eb93743.png)

@spmonahan / @smhigley - would either of you be able to review this issue?

**Comment by gouttierre** [comment]
Issue related #20662

**Comment by spmonahan** [comment]
This is an issue in `Pivot`. It looks like we need to update the rendering case for overflow items to include necessary ARIA attributes.
