### ISSUE TITLE
Required ARIA parent role not present in Pivot overflow

### ISSUE THREAD

**Issue by linazar** [microsoft/fluentui#20662]
### Environment Information

- **Package version(s)**: Fluent React 8.42.3
- **Browser and OS versions**: Edge 95.0.1020.44 ; Windows 11 Enterprise

### Describe the issue:

Required ARIA parent role not present in Pivot overflow 

#### Actual behavior:

Required ARIA parent role not present: tablist

#### Expected behavior:

Add required ARIA parent role to Pivot overflow: tablist

### If applicable, please provide a codepen repro:

1) Navigate to https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/pivot, make sure 8.42.3 is selected

2) scroll all the way to Pivot with overflow menu

3) (This is critical step!) Click on the three dots, so that "The Last Tab" shows up. 

4) Run FastPass - make sure (this is critical!) that the "The Last Tab" is still visible.

**Comment by gouttierre** [comment]
@linazar - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows. Thank you for the repro steps and I do see the mentioned problem. 

![image](https://user-images.githubusercontent.com/78806055/148245506-21f2b272-6088-46f3-88ec-b7c34eb93743.png)

@spmonahan / @smhigley - would either of you be able to review this issue?

**Comment by gouttierre** [comment]
@linazar - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows. Thank you for the repro steps and I do see the mentioned problem. 

![image](https://user-images.githubusercontent.com/78806055/148246435-b807b64f-5904-41ec-b537-2217613fce05.png)

@spmonahan / @smhigley - would either of you be able to review this issue?

**Comment by gouttierre** [comment]
Related issue #20663

**Comment by smhigley** [comment]
I no longer see this issue in the overflow popup -- it looks like the roles were updated to be menu/menuitem.

There's now a separate automated issue around allowed attributes that I'll make a PR for, but I'm closing this issue since it looks like it was fixed.
