### ISSUE TITLE
Layout component is missing

### ISSUE THREAD

**Issue by DanaCoding** [microsoft/fluentui#20690]
#### Describe the feature that you would like added

Layout is an essential component in UI development and the cornerstone of all applications but I did not see it in the official documentation.

#### What component or utility would this be added to

Layout

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/93444868/142778797-10101a85-f2e1-42f1-a5f3-8795a83f8c56.png)

**Comment by gouttierre** [comment]
@DanaCoding -  Thanks for filing this suggestion. I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
