### ISSUE TITLE
Button styles secondaryText ignored

### ISSUE THREAD

**Issue by LukeOwlclaw** [microsoft/fluentui#20701]
I want to left align the secondary text of a split button:

![image](https://user-images.githubusercontent.com/2737900/142863701-7a37bbe6-668d-4b8c-952f-e0b741aac55f.png)

But the styles for the secondary text are not being applied. 

It seems that secondary text was initially not designed to be used for split buttons. See "Description of the action this button takes. Only used for compound buttons. " for ``secondaryText: string``. And also "Style for the description text if applicable (for compound buttons). " for ``secondaryText: IStyle``.

However, when secondary text works for split buttons, also its styling should be applied, right?

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/LukeO_/pen/gOxyyRX

#### Actual behavior:

The secondary text does not change its text size, background color, nor position.

#### Expected behavior:

Secondary text should use styles configured via 

    <DefaultButton
       styles={{ secondaryText: {textAlign: "left !important", flexGrow: 999, backgroundColor: "red", fontSize: '77px' } }}

**Comment by gouttierre** [comment]
@LukeOwlclaw  - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm this issue?

**Comment by khmakoto** [comment]
Hi @LukeOwlclaw, this is happening because the `secondaryText` styles that you are targeting are the ones in `Button` vs the ones in `ContextualMenuItem` that you should be targeting. Here's [a modified version of your codepen](https://codepen.io/khmakoto/pen/KKQbEOX) that achieves this.
