### ISSUE TITLE
Swatch color picker using High Contrast mode

### ISSUE THREAD

**Issue by ilanbd** [microsoft/fluentui#20708]
https://codepen.io/ilanbd/pen/bGomVbp

repro steps:
1. enable High contrast mode
2.open the code pen
3. see the bug: the black color is not visible since it doens't have a border.

My advise would be to add a white border to the black color (in the same way that the white color has a black border)

**Comment by ilanbd** [comment]
any update on this?

**Comment by ilanbd** [comment]
Hi @khmakoto , any update on this issue?

**Comment by gouttierre** [comment]
@ilanbd - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [SwatchColor](https://developer.microsoft.com/en-us/fluentui#/controls/web/swatchcolorpicker) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by ilanbd** [comment]
Any update on this?
