### ISSUE TITLE
Indeterminate checkbox do not consistently expose mixed state across browsers

### ISSUE THREAD

**Issue by scottaohara** [microsoft/fluentui#20717]
The [fluent UI indeterminate checkboxes](https://developer.microsoft.com/en-us/fluentui#/controls/web/checkbox) presently rely on `aria-checked=mixed` to convey their mixed state.  However, this state is not exposed in Safari or Firefox.  They are actually correct in not exposing this state, as the native `checked` attribute, or the element's dirty checked state is supposed to override the `aria-checked` attribute.  

These mixed-state checkboxes should instead use the `indetermindate` IDL attribute to communicate their mixed state.  Doing so would allow the mixed state to be exposed properly with Firefox, would maintain current support with Chromium browsers, and pending [Webkit's bugfix](https://bugs.webkit.org/show_bug.cgi?id=231760) for properly exposing the IDL attribute, would then allow these checkboxes to be correctly exposed in Safari as well.

**Comment by gouttierre** [comment]
@scottaohara - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by smhigley** [comment]
This has always been an issue -- we do a super weird thing in `Checkbox.base.tsx` where we fake `get indeterminate` on the component ref instead of actually setting indeterminate on the ref instead.
