### ISSUE TITLE
migrate-converged-pkg: creates unnecessary .storybook folder 

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#20724]
I am migrating `@fluentui/react-shared-contexts` via:

```bash
yarn nx workspace-generator migrate-converged-pkg --name='@fluentui/react-shared-contexts'
```

During migration the generator creates `.storybook` that is not necessary for this package:

```
CREATE packages/react-shared-contexts/.storybook/tsconfig.json
CREATE packages/react-shared-contexts/.storybook/main.js
CREATE packages/react-shared-contexts/.storybook/preview.js
```

**Comment by layershifter** [comment]
@Hotell I am not sure that it's solvable as I don't see any logical condition for this, but if you have ideas it will be awesome to solve this.

**Comment by layershifter** [comment]
`@fluentui/react-context-selector` (#20741) has the same problem.

**Comment by layershifter** [comment]
For `@fluentui/babel-make-styles` (#20744) it's different: `.storybook` folder was not created, but scripts were added to `package.json`.

**Comment by Hotell** [comment]
> 

right, adding this "via context" is tricky in general. I was thinking about a flag for user

```sh
nx workspace-generator migrate-converged-package --name=@fluentui/react-zzz --init-storybook
```

so the logic would be something like:
- if there is existing storybook , update the setup
- if there is no existing storybook, do nothing, unless user provided `--init-storybook`

WDYT?

**Comment by layershifter** [comment]
> WDYT?

I like the flag idea, but I think that it should be opposite: `--disable-storybook`
As generally we create components, not utility packages ¯\_(ツ)_/¯
