### ISSUE TITLE
migrate-converged-pkg: adds @fluentui/babel-make-styles and causes circular deps

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#20727]
I ran migration for `@fluentui/react-make-styles` and the generator adds `@fluentui/babel-make-styles` as a dependency:

![image](https://user-images.githubusercontent.com/14183168/143070746-1b6474cb-3100-4bcf-8d9b-7fb8d86c7b95.png)

This causes a circular dependency:

![image](https://user-images.githubusercontent.com/14183168/143070807-9fcde881-5156-4a1e-9cda-1fa20ba8bb41.png)

**Comment by layershifter** [comment]
It also adds `module:@fluentui/babel-make-styles` to `.babelrc` that is also incorrect:

![image](https://user-images.githubusercontent.com/14183168/143070923-00b1b96b-8533-4223-88f2-c5f9a886051e.png)

**Comment by Hotell** [comment]
hmm can you think a generic rule to avoid this?

current logic that adds those is following

```
const shouldAddMakeStylesPlugin =
    pkgJson.dependencies[`${currentProjectNpmScope}/react-make-styles`] ||
    pkgJson.dependencies[`${currentProjectNpmScope}/make-styles`];
  const extraPlugins = shouldAddMakeStylesPlugin ? ['module:@fluentui/babel-make-styles'] : [];
```

**Comment by layershifter** [comment]
Do not add it to anything that contains `make-styles` in the name? 😅

Ideally deps tree should be traversed to ensure that circular will not happen. This is somehow handled in `lage` so we probably could reuse it if it's under [`workspace-tools`](https://www.npmjs.com/package/workspace-tools)

**Comment by Hotell** [comment]
> Do not add it to anything that contains make-styles in the name? 😅

to give you better context, this behaviour was added to make pipelines work, as lage would not build `@fluentui/babel-make-styles` prior to execute `build` tasks on packages that use it in their babel configs, thus causing pipeline failures.

Regarding the rule: So would it make sense to not add this plugin/dependency only to packages that contain `make-styles` in their name?

> Ideally deps tree should be traversed to ensure that circular will not happen. This is somehow handled in lage so we probably could reuse it if it's under 
AFAIK it is not handled by lage - it checks package.json not real AST ( nx does that for example ).

**Comment by layershifter** [comment]
> * **Regarding the rule:** So would it make sense to not add this plugin/dependency only to packages that contain `make-styles` in their name?

We could try to do this for now. At least currently it was a single case.
