### ISSUE TITLE
Detail List drag & drop does not auto-scroll

### ISSUE THREAD

**Issue by Power-Maverick** [microsoft/fluentui#20721]
### Environment Information

- **Package version(s)**: 8.42.5
- **Browser and OS versions**: Chrome/Edge, Win10/11

#### Actual behavior:

Drag & Drop with Sticky header does not auto-scroll if the drop target is either above or below the display.

#### Expected behavior:

Drag & Drop should auto-scroll to appropriate target

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Maybe (time-permitting)

Requested priority: (Blocking, High, Normal, Low) Blocking

#### Issue Reproducing GIFs:

![IssueWithAutoScrollInDetailList-FluentUI](https://user-images.githubusercontent.com/36135520/143058257-c8f2e7d0-aa0c-4e24-b9dc-8ef8fbaebf76.gif)

![IssueWithAutoScrollInDetailList-FluentUI-1](https://user-images.githubusercontent.com/36135520/143058266-3c201b4e-6728-4bd4-8d49-ecb3cce29cc1.gif)

**Comment by gouttierre** [comment]
@Power-Maverick - Thanks for filing this issue with us. To set expectations, the developers will review the issue once capacity allows.  I see you are "maybe" willing to contribute. If you have come up with a solution and would like to submit a PR for this, please, do so and our team will gladly review it.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue?
