### ISSUE TITLE
migrate-converged-pkg: removes --passWithNoTests

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#20740]
I ran generator for ` @fluentui/react-shared-contexts` and it removed `--passWithNoTests` in `package.json#scripts` that caused CI failure.

![image](https://user-images.githubusercontent.com/14183168/143220006-29a4cce0-daf9-4c71-96d9-c0c9204554e0.png)

IMO there is sense to enable this option in all Jest configs.

**Comment by Hotell** [comment]
> IMO there is sense to enable this option in all Jest configs.

as a temporary unification/workaround I agree. thanks for reporting!

**Comment by Hotell** [comment]
for contributors: the fix is to add `"test": "jest --passWithNoTests"` to migrated package `package.json`

```diff
// @filename packages/<package-folder-name>/package.json
"scripts": {
-  "test": "jest",
+  "test": "jest --passWithNoTests" 
}
```
