### ISSUE TITLE
migrate-converged-pkg: adds "module:@fluentui/babel-make-styles" to `@fluentui/babel-make-styles`

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#20743]
I ran generator for `@fluentui/babel-make-styles` and it adds Babel plugin to Babel plugin ( •_•)>⌐■-■

![image](https://user-images.githubusercontent.com/14183168/143225033-478b246b-2c21-4dd3-9722-9e3afa0227ed.png)

The same happens in `pachage.json`:

![image](https://user-images.githubusercontent.com/14183168/143225068-0f6b52d7-5d05-4efb-9ed9-a718523688f6.png)

**Comment by Hotell** [comment]
this is bug indeed. thanks for report!

for contributors:

generator should:
- not add `@fluentui/babel-make-styles` as a dependency to package.json if the package name is the same as dependency being added ( this can/should be generalized )
- not add `module:@fluentui/babel-make-styles` to babel plugins field if the package name is the same as the plugin being added
