### ISSUE TITLE
migrate-converged-pkg: adds Storybook scripts for Node packages

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#20745]
I ran generator for `@fluentui/babel-make-styles` and `@fluentui/jest-serializer-make-styles`. In both cases generator adds new scripts to `package.json#scripts`.

![image](https://user-images.githubusercontent.com/14183168/143227716-fbd0b7db-37ff-4c07-b1a2-2cd0373305be.png)

This should not be a thing 😯

**Comment by Hotell** [comment]
yup this is indeed a bug. thanks for reporting !

**Comment by Hotell** [comment]
for contributors:

if package is a `node` package generator should remove following scripts:

```diff
// @filename packages/<package-folder-name>/package.json
"scripts": {
-  "start": "storybook",
-  "storybook": "start storybook" 
}
```
