### ISSUE TITLE
migrate-converged-pkg: generator considers react-components as JS project

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#20748]
I ran generator for `@fluentui/react-components` and `yarn build` fails then:

![image](https://user-images.githubusercontent.com/14183168/143232717-491816d4-52f1-4af1-b5c6-0d41a58229be.png)

This happens because TS emits nothing. I checked configs and generator for unknown reason considers this project as JS only and generates wrong configs:

![image](https://user-images.githubusercontent.com/14183168/143232869-9fb07577-5fd9-449d-a9d2-b56e52edec9e.png)

**Comment by layershifter** [comment]
I digged a bit more into it: generator currently considers that there can be only JS or TS project, not mixed.

https://github.com/microsoft/fluentui/blob/66670cf47c716e284c7ac7ae5f25d1f77f3aced3/tools/generators/migrate-converged-pkg/index.ts#L594-L596

^ this results in complete override by JS globs

**Comment by Hotell** [comment]
mixed support was not intended yet. 

there was a bug in how we check for js files presence within `src`. thanks for report !
