### ISSUE TITLE
Placeholder text in dropdown is not visible in high contrast theme

### ISSUE THREAD

**Issue by nawadih** [microsoft/fluentui#20766]
### Environment Information
- **Package version(s)**:  "@fluentui/react": "^7.177.3",
- **Browser and OS versions**: Windows 10, Edge Version 95.0.1020.53 (Official build) (64-bit)

### Describe the issue:
In high contrast theme, placeholder text of dropdown is not visible when hovered, active or focused
![image](https://user-images.githubusercontent.com/49041826/143303868-6922c954-c773-4993-8a4c-b69c6d1eb5be.png)
![image](https://user-images.githubusercontent.com/49041826/143303942-3707ba8d-3122-4124-983a-cab7174f44e9.png)

When tabbing over to the dropdown the placeholder text is not visible. Have not been able to override the styling to make it visible, it seems like this black color is coming from the fluent ui component

#### Actual behavior:

placeholder text becomes black

#### Expected behavior:

placeholder text should be visible

### If applicable, please provide a codepen repro:
Nor sure how to apply a high contrast theme in a code pen sample

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
Teams - Approvals

**Comment by nawadih** [comment]
thanks! @layershifter any update on the above?

**Comment by layershifter** [comment]
@nawadih sorry, but I was not able to look into it during my Shield duties 😥  @spmonahan can you please this issue?

**Comment by nawadih** [comment]
Thanks! @spmonahan have you had chance to look at the above issue?

**Comment by spmonahan** [comment]
@nawadih How are you enabling the high contrast theme in your app? On Windows 10 I've enabled the "High Contrast Black" theme via Windows Settings and placeholder text is visible for me with the v7 Dropdown.

**Comment by nawadih** [comment]
@spmonahan thanks for verifying, the theme is coming from Teams platform, however I actually re-tested this today and the issue is no longer occurring so there must have been a fix on their end, going to close this out now. Thanks!
