### ISSUE TITLE
"@rnx-kit/eslint-plugin" is breaking lint pipelines

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#20774]
### Describe the issue:

`yarn workspace nx-workspace-tools lint`

throws error 

![2021-11-25 at 10 25](https://user-images.githubusercontent.com/1223799/143414991-182196b3-fec0-4279-9d58-e727afb0ed2f.png)

Caused by https://github.com/microsoft/fluentui/pull/20665/files#diff-691525462f8b4cac47c3c2e0e2668606f539ed0b3f62f8f6b79dffe7ef38bd9dR15

- this is caused as that plugin ships non transpiled code -> optional chaining operator

**Comment by Hotell** [comment]
this will pass on CI, because we already bumped to node 14 - https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=227889&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=36b30cb7-e32b-56ae-15b9-bd436e45f939

curios when did this happened @ling1726 @ecraig12345  ?

**Comment by ling1726** [comment]
@hotell it seems node was bumped in #20732
