### ISSUE TITLE
DatePicker: title of week header is duplicated if the day is first day of month

### ISSUE THREAD

**Issue by kidokidozh** [microsoft/fluentui#20770]
### Environment Information

- **Package version(s)**: 8.29.1

### Please provide a reproduction of the bug in a codepen:

Can reproduce in https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker

#### Actual behavior:
Title of weekday header will have an extra short label.
This happens if the day is first weekday of month, so the duplicate one in each month is different.
![image](https://user-images.githubusercontent.com/58833558/143387203-2d6865be-1397-4a60-8494-d5ba0816a5a6.png)
![image](https://user-images.githubusercontent.com/58833558/149049131-98eb6f65-a9d5-43fc-8fdc-0b91d701215b.png)

**Comment by kidokidozh** [comment]
I found the root cause is this line: https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/CalendarDayGrid/CalendarMonthHeaderRow.tsx#L28

The short day label is appended to title, when the weekday is the first of month. But what is the purpose of doing so?

**Comment by gouttierre** [comment]
@kidokidozh  - Thanks for filing this issue with us. Please, could you retest this issue as I was unable to reproduce it and there have been new updates released since then.

**Comment by kidokidozh** [comment]
@gouttierre This issue still exist in  https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker
This issue only happens when the day is first weekday of month. For example, as the image show below, Jan 1st is Saturday, so the title of Saturday header becomes "Saturday S", while other weekdays are correct.
![image](https://user-images.githubusercontent.com/58833558/149049131-98eb6f65-a9d5-43fc-8fdc-0b91d701215b.png)
