### ISSUE TITLE
[v9] ToggleButton does not properly support controlled mode

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#20789]
It is currently not possible to use ToggleButton in controlled mode and be aware of its state:
- defaultChecked prop is not documented in the generated props list in https://6002298f95a00c00213f4d55-vwsflwcaij.chromatic.com/?path=/docs/components-togglebutton--default - it is only mentioned in the description of checked prop
- onChange callback is missing. This callback should provide the new state, so that the consumer could use it to change the parent state. Tooltip visible / onVisibleChange are good example for a controlled state.

Note: onClick exists, but it would not be expected to get the new state in the onClick event.

### Environment Information

- **Package version(s)**: v9 beta 3
- **Browser and OS versions**: all

**Comment by khmakoto** [comment]
This is no longer an issue, closing.
