### ISSUE TITLE
dependencies: use single version policy for axe-core

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#20799]
Hope you don't mind, I pushed an update merging with master and de-duping `axe-core` versions (and some other modified deps) as much as possible.

`react-builder` still references `axe-core` 3, and ideally that should be updated as well, but it looks like some additional work would be required.

_Originally posted by @ecraig12345 in https://github.com/microsoft/fluentui/issues/20609#issuecomment-974473317_

**Comment by ecraig12345** [comment]
This will probably need to be addressed by someone from the northstar team who's familiar with react-builder.
