### ISSUE TITLE
8.43.0 -> 8.44.0 - Undocumented Breaking Change. NeutralColors is no longer exported.

### ISSUE THREAD

**Issue by jj05y** [microsoft/fluentui#20822]
### Environment Information
- **Package version(s)**: "8.44.0"
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
Broken with **8.44.0**: https://codepen.io/jj05y/pen/zYEOVYr 
Working with **8.43.0**: https://codepen.io/jj05y/pen/BawBgaO

#### Actual behavior:

NeutralColors is no longer exported

#### Expected behavior:

NeutralColors should be exported

### Priorities and help requested:

Are you willing to submit a PR to fix? I would but it's not clear what removed this

Requested priority: (Blocking)

**Comment by layershifter** [comment]
Hey @jj05y, thanks for reporting. I was able to reproduce it 👍

I guess that it's happened in #20665. I will check and submit a fix 😉

**Comment by layershifter** [comment]
@jj05y fix is available in #20824 🚀

**Comment by ecraig12345** [comment]
This was probably from @dzearing's updates to remove `export *`.

**Comment by dzearing** [comment]
Probably, though I'm curious if they were recently added, or if there is a bug in the lint rule fixer.

At least now these will be locked down with api extractor rather than implicitly exported.

**Comment by ecraig12345** [comment]
They've existed for a long time, so probably a bug with the fixer.
