### ISSUE TITLE
Project: Upgrade guide (part 1)

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#20830]
## Problem

Customers have significant investment in Fluent v8 and Northstar v0. We want them to upgrade their applications to Fluent v9. Early upgraders to the v9 RC can give us valuable feedback. 

While v9 has many advantages over previous versions, upgrading has significant costs. 
- There is not a 1:1 mapping of components, requiring refactoring or substitution work.
- v9 deliberately omits the Stack component which is heavily used in layout. Upgrade will require either writing flex/grid CSS or leveraging a transition Stack component.
- Many components are not yet available in v9, requiring side-by-side usage of v8/v0 and v9. This will affect bundle size.
- v9 has a different approach to styling and theming, requiring transition theming to provide v8/v0 or v9 style consistently across all components.
- v9 provides slots as the way to fully customize parts of a component while v8/v0 limit callers to custom CSS styles. Customers who have done extensive customization will need refactor to use slots.

Currently WISE (OOUI), Microsoft Teams, Admin Controls, and OWA are investigating and prototyping upgrading to v9. We will need to capture their challenges/solutions for other customers and partners.

While we have some migration information and FAQ, customers will need a comprehensive guide that demonstrates the upgrade process, how to overcome common challenges, and how to manage the upgrade before, during, and after adopting v9 components. We will need to be able to demonstrate the upgrade process with a sample reference application.

For the short December sprint, we should begin building the sample application for v8. The app should be primarily focused on the usage of components with limited data model and business logic. 

## Appetite

2 weeks (Dec)

## Solution

- [ ] Build an application to demonstrate the upgrade story.

  - Demonstrate each control similar to storybook (but without storybook.js dependency)
  - Upgrade steps and scripts can be applied to the application to move to v9 wholesale or gradually
  - Controls can included/excluded to measure bundle size
  - Controls can be v8 (before upgrade), v9 (after upgrade), or a mixture (during upgrade) 
  - No backend business logic, data layer, or complex layout.

- [ ] Begin authoring an upgrade guide document

  - Motivation to upgrade (briefly)
  - Guidance on the phases of upgrade
  - Key partner scenarios and pain points
  - Control v8 -> v9 mapping (extracted from planning docs)
  - Control v8 -> v9 props mappings (extracted from specs)

## Risks (Rabbit holes)

- v9 is still a moving target which can cause rework of upgrade guidance.
- Making side-by-side too easy may reduce the incentive to  upgrade to v9.

## Out of scope (Future work)

- Author code mods for upgrade
- Author transition components such as TransitionStack, TransitionThemeProvider (make v8 look like v9 or make v9 look like v8), and props adapters (implement Button v8 using Button v9)
- Create an inspector/linter for upgrade
- Guidance on using bundle size measurement tools
- Optimize bundle size when using v8 and v9 side-by-side.

## Out of scope (No-go)
- v0 upgrade scenario (handled by Prague as part of working with Teams through upgrade)

**Comment by shayc** [comment]
Hi, @GeoffCoxMSFT 

I'm trying to find an explanation/document about the changes to styles in v9.
What does it mean exactly?
