### ISSUE TITLE
Update repo to node 14

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#20834]
The repo is running on Node 12. Let's get it at least on 14, ideally 16 (LTS).

Right now, bumping to 14 breaks the release CI with a callstack exception thrown from the typescript compiler building production assets for the `react-icons-mdl2` package. Updating TS to 4.3+ fixes it.

**Comment by ecraig12345** [comment]
Typescript 4.3 upgrade is tracked by #19507

**Comment by ecraig12345** [comment]
This is unblocked now that we're on 4.3.
