### ISSUE TITLE
[Performance] Tooltip On-Hover Rendering Entire Page

### ISSUE THREAD

**Issue by lekevin-microsoft** [microsoft/fluentui#20847]
### Environment Information

- **Package version(s)**: @fluentui/react@8.36.0
- **Browser and OS versions**: Any, though I'm using Edge + Windows 11, and have tested this on Windows 10 and Chrome.

### Please provide a reproduction of the bug in a codepen:
Bug can be seen on the official FluentUI Tooltip demo page here: [https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip](https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip). 

#### Actual behavior:
In F12 devtools, go to "Rendering", and then click "Paint flashing". Then, hover over a control with a tooltip in the demo page listed above, and you'll notice that the entire screen flashes when the tooltip appears. 

Additionally, in F12 devtools, you can go to "Performance" and click "Enable advanced paint instrumentation" and then hit "Record". Then, hover over a tooltip a few times, and then click stop to stop the recording. 

In the performance log, you can see that every time a tooltip shows, the "Paint" sequence will actually paint the entire screen again. Going to "Paint Profiler" and dragging will show this. Below is a screenshot showing this occurring.
![image](https://user-images.githubusercontent.com/57237883/144067365-0dbc107c-f30b-4a00-8d92-29cc2434ed48.png)

#### Expected behavior:
My expected outcome is that we don't repaint the entire screen. I may be wrong and perhaps this is a necessity, but wanted to start the conversation here. 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) - Yes.

Requested priority: (Blocking, High, Normal, Low) - **Normal / High**. Currently working on Outlook Web and we're focusing heavily on performance right now, and we're auditing our app to discover and fix any unnecessary renders as we've been receiving a large influx of feedback regarding the application's performance being too slow. 

Products/sites affected: (if applicable) - Outlook Web, Word/Excel/Powerpoint Web

Caveat: This may be by-design or impossible to work around, but in case no one has looked at this before, I wanted to make this issue to bring it up just in case. Is there a tooltip engineer who could help weigh in if this is a necessary full-page rerender?

**Comment by layershifter** [comment]
> * **Package version(s)**: Current

@lekevin-microsoft can you please clarify what is current? Is it `@fluentui/react@8.45.0`?

**Comment by lekevin-microsoft** [comment]
Sorry about that, let me paste.

For Outlook Web: `"@fluentui/react": "^8.36.0"`.

**Comment by layershifter** [comment]
> Sorry about that, let me paste.
> 
> I believe for Outlook Web: `"@fluentui/react": "^8.36.0"`, found via package.json at root for the repo. If there's a different way to find out fluentui version, please let me know.

That's enough, thanks 👍

**Comment by eylult** [comment]
Hello @gouttierre, without the Tooltips commanding of the app is not accessible and hard to use. However, with Tooltips, the performance issue makes the whole app unusable. Can this issue be prioritized accordingly?
