### ISSUE TITLE
Enable @fluentui/react-storybook-addon in react-components

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#20896]
We should find a way to enable the addon again without breaking buildless experience (#20886).

**Comment by Hotell** [comment]
I cannot repro the issue with addon itself - as you described, the only issue is with not having `babel-make-styles` plugin build. Addon buildless experience works as expected.

- no build artifacts present ( dependencies of addon package )
![2022-01-11 at 10 22](https://user-images.githubusercontent.com/1223799/148915727-7592ac4c-a6d8-4df3-9c08-f6c91c26c6f2.png)

- build artifact present ( babel-make-styles ) 
![2022-01-11 at 10 23](https://user-images.githubusercontent.com/1223799/148915866-9b0507a5-598b-4168-8a05-b9fc35f12ecc.png)

- executing `storybook` on react-components works. also theming works again
![2022-01-11 at 10 24](https://user-images.githubusercontent.com/1223799/148916166-132f0752-1673-4699-8238-d24b38d5eae3.png)

**Comment by layershifter** [comment]
@Hotell it happens with Storybook manager, run it without cache:

- Enable addon in `packages/react-components/.storybook/main.js`
- `yarn workspace @fluentui/react-provider clean`
- `yarn workspace @fluentui/react-theme clean`
- `yarn workspace @fluentui/react-components start --no-manager-cache`

![image](https://user-images.githubusercontent.com/14183168/148917273-0602366e-8e37-4773-a41f-85c6307b036d.png)

**Comment by Hotell** [comment]
hmm I was able to repro it when running in docs mode:

`yarn workspace @fluentui/react-components storybook:docs`

![2022-01-11 at 10 34](https://user-images.githubusercontent.com/1223799/148917558-a55c09e8-434c-4378-b770-96d086502ab6.png)

**Comment by Hotell** [comment]
our custom addon is enabled without buildless experience atm, thus I'm keeping this issue open

**Comment by Hotell** [comment]
fixed by https://github.com/microsoft/fluentui/pull/24168
