### ISSUE TITLE
Menu: use `aria-haspopup` and change usage pattern for `aria-expanded`

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#20898]
Based on feedback from @adamsamec 

### Environment Information

- **Package version(s)**: 9

#### Actual behavior:

Currently `MenuTrigger` only applies `aria-expanded="true"` and `aria-expanded="false"`. when open and closed respectively

#### Expected behavior:

`MenuTrigger` should always apply `aria-haspopup="menu"`

`MenuTrigger` should apply only `aria-expanded="true"` when a root trigger opens a menu. Submenu triggers should apply both  `aria-expanded="true"` and `aria-expanded="false"`

**Comment by layershifter** [comment]
Linking ARIA spec for context https://www.w3.org/TR/wai-aria/#aria-haspopup.
