### ISSUE TITLE
Ability to close a PivotItem

### ISSUE THREAD

**Issue by davidmualem77** [microsoft/fluentui#20899]
#### Describe the feature that you would like added

Add the ability to close a pivot item.

#### What component or utility would this be added to

Pivot

#### Have you discussed this feature with our team, and if so, who

no

#### Additional context/screenshots

Saw that a request for this was opened a few years back but was closed- https://github.com/microsoft/fluentui/issues/7437
Not sure what is the status of this or if this is somewhere in the backlog, but it would really be helpful to allow closing tabs.

If it's not something that can't be supported, is there a way for a workaround with current implementation?

**Comment by davidmualem77** [comment]
Kindly ping where does this stand.

**Comment by gouttierre** [comment]
@davidmualem77 - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.
