### ISSUE TITLE
Are there any updates coming to the Fluent Web kit for Figma?

### ISSUE THREAD

**Issue by mrmeku** [microsoft/fluentui#20913]
#### Describe the feature that you would like added

The current Figma file provided by the fluent UI team hasn't been updated since early 2020 and has, in many ways, fallen out of date with @fluentui/react and modern day figma practices in general. It would be great if that file could be updated to match the improvements that have been made to the react library over the past year and a half.

#### What component or utility would this be added to

N/A

#### Have you discussed this feature with our team, and if so, who

N/A

#### Additional context/screenshots

N/A

**Comment by gouttierre** [comment]
@mrmeku - Thank you for reaching out to us. Yes, there are plans in the works to get our design system UI kits up to date.

@paulgildea - Would you be able to shed some light on the future plans?

**Comment by tebinraouf** [comment]
Hi @gouttierre , @paulgildea  

Has there been any progress about this? Could you please provide an update? Thanks.

**Comment by shalom-ormsby** [comment]
Another gentle ping that updating the Figma resource would be so very helpful and so greatly appreciated by those who are using it, including our design team. Can anyone at Microsoft provide an update about when this may be released, and brought into sync with Fluent UI React v9? Thanks in advance!

**Comment by cnqdztp** [comment]
It would be very helpful to hear about further plan on updating the figma design kit! Thanks!

**Comment by javiersuzuki-oobe** [comment]
Hi @mrmeku  and @paulgildea 
Is there any update on when the Figma UI kit will be up to date with Fluent UI React v9?
I'd appreciate any news about it.
Thanks!

**Comment by micahgodbolt** [comment]
There are no current plans for the v9 Figma files. We will make an announcement if/when we are able to publish them.
