### ISSUE TITLE
FluentUI Icons, wrong endpoint in documentation

### ISSUE THREAD

**Issue by sirdawidd** [microsoft/fluentui#20920]
In Microsoft documentation I see
`By default, the icon fonts for the default set of icons will be pulled from the SharePoint CDN. The default endpoint is spoprod-a.akamaihd.net`
where I whitelisted that endpoint in Content Security Policy (CSP) I see that the endpoint is different ***.azureedge.net**
Someone please fix that documentation and list all cdn's

https://github.com/microsoft/fluentui/wiki/Using-icons

Thanks

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to review the documentation and list all cdn's? Thanks
cc @tomi-msft
