### ISSUE TITLE
v9 Splitbutton documentation is missing important information

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#20958]
v9 Splitbutton documentation is missing important information:
- how to attach click handler to the primary button
- that secondary button needs to be labelled

**Comment by WillemSleegers** [comment]
Is there an example of how to attach a click handler yet? I'm struggling to make it work.

**Comment by khmakoto** [comment]
The first point is addressed in #29334.

The second point is no longer relevant since we now label the secondary button if the user did not label them themselves.
