### ISSUE TITLE
SearchBox clear button doesn't give hover feedback in high contrast mode

### ISSUE THREAD

**Issue by molinger** [microsoft/fluentui#20965]
### Environment Information

- **Package version(s)**: 8.46.2
- **Browser and OS versions**: Edge 96.0.1054.43, Windows 11 (22000.318)

### Please provide a reproduction of the bug in a codepen:

1. Enable high contrast mode. I used the default Night Sky theme.
2. Go to https://codepen.io/molinger/pen/eYGZypx
3. Hover over the clear button in the search box.

#### Actual behavior:

No feedback is given.

#### Expected behavior:

Some feedback is given (e.g. button has outline or color changes).

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by molinger** [comment]
This also impacts the expand buttons on GroupedList. Let me know if I should file a separate issue for that.

**Comment by gouttierre** [comment]
@molinger - I’ve added this to our projects for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
However, I see you are willing to submit a PR for this fix. If you have the solution at hand, would you mind sharing it with us? Thanks.
