### ISSUE TITLE
GroupedList scroll bar jumps when trying to virtualize items

### ISSUE THREAD

**Issue by molinger** [microsoft/fluentui#20978]
### Environment Information

- **Package version(s)**: 8.46.3
- **Browser and OS versions**: Windows 10, Edge 96.0.1054.43

### Describe the issue:

When using a GroupedList, the scroll bar will jump around with certain configurations of items. When debugging, it appears that when you try to scroll to the bottom, the List attempts to virtualize items that are out of view. It tries to create a spacer that is the height of these virtualized items but its height isn't correct. This can lead to either the scroll bar jumping back up preventing you from getting to the bottom of the list. It might also cause the items to get stuck in a loop where they virtualize and unvirtualize causing the scroll bar to grow and shrink rapidly.

https://user-images.githubusercontent.com/3746165/145318461-4bf1d9f8-0471-46eb-8627-8900cb774e7d.mp4

This video shows the second behavior.

#### Actual behavior:

Scroll bar has weird behavior.

#### Expected behavior:

Scroll bar should be stable and user should be able to scroll to bottom of list.

### If applicable, please provide a codepen repro:

This repro is super dependent on the height of the viewport. I didn't measure the size of the window in the attached video but I did a second repro with the window's innerHeight at 491px that wasn't captured on video.

1. Open this codepen: https://codepen.io/molinger/pen/GRMqWxm
2. Collapse the last group with items.
3. Scroll up and back to the bottom.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by gouttierre** [comment]
@molinger - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue? Thanks

**Comment by spmonahan** [comment]
This is an issue and I've gotten several related support requests internally that are related. I'm still investigating but I believe this is due to how row and page heights are calculated when virtualizing lists.

Other related issues on Github:
- #20825
- #20037
