### ISSUE TITLE
Narrator does not announce last button in Dialog

### ISSUE THREAD

**Issue by Antonstockmarr** [microsoft/fluentui#20988]
### Environment Information

- **Package version(s)**: FluentUI/react 8.45
- **Browser and OS versions**: Windows 11 v10.0.22000, Edge version 96.0.1054.41 (Official build) (64-bit)

### Describe the issue:
When opening a dialog with buttons while the Microsoft Narrator is enabled and in scan mode, the narrator reads the content of the dialog except for the last button in the DialogFooter. If there are two buttons the narrator will only announce the first. If there are three buttons the narrator will announce the two first, and so forth. This means that the user may not know that the last button is present in the Dialog.

### Please provide a reproduction of the issue in a codepen:
Issue is reproducible in example from the docs. On this page: https://fabricweb.z5.web.core.windows.net/oufr/8.47.1/#/examples/dialog
Go to the first Variant.
Enable Narrator.
Click "Open Dialog".
Observe that the button labeled "Don't Send" is not announced.

Alternatively, perform the same steps in this codepen:
https://codepen.io/AntonStockmarr/pen/zYEKwdv

#### Actual behavior:
The narrator reads from the dialog, but stops before reaching the last button in the DialogFooter.

#### Expected behavior:
The narrator should announce all buttons in the dialog.

**Comment by gouttierre** [comment]
@Antonstockmarr - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue? 
cc @smhigley
