### ISSUE TITLE
Old react dependencies for: file-type-icons, theme , utilities

### ISSUE THREAD

**Issue by sirdawidd** [microsoft/fluentui#20997]
Some packages are still require react in version 16. Because of that i see a lot of warnings on my build pipeline.

npm WARN @uifabric/file-type-icons@7.8.5 requires a peer of @types/react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.       
npm WARN @fluentui/theme@1.7.4 requires a peer of @types/react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.33.5 requires a peer of react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by layershifter** [comment]
@sirdawidd it's not related to React itself, you don't have installed `@types/react` which are our `peerDependency`.

**Comment by sirdawidd** [comment]
I don't want to install anything, I just said that on build pipeline I'm getting a lot of warning's from FluentUI, and what Microsoft should do is update the dependencies on their side.

**Comment by layershifter** [comment]
@sirdawidd Sorry, I overlooked that there is `<17.0.0` on `@types/react` (you did not provide the version of Fluent UI that you're using). It's not requiring `react@16`, just types. At least from the warning that you provided.

---

`@fluentui/react@8` has support for React 17 and proper `peerDependencies`:

https://github.com/microsoft/fluentui/wiki/Version-8-migration-guide#supported-dependency-versions

https://github.com/microsoft/fluentui/blob/b8ca4b3642b752e506fc6617c13c2568867c5464/packages/react/package.json#L70-L72

---

While `office-ui-fabric-react` has no official support for React 17:

https://github.com/microsoft/fluentui/blob/7b743875f960bd19342c08c81c6edc92e5ca1d8e/packages/office-ui-fabric-react/package.json#L83-L87

**Comment by sirdawidd** [comment]
Sorry I forgot to add that I'm using latest version "@fluentui/react": "^8.47.1",

And you san see version is old   
https://github.com/microsoft/fluentui/blob/7b743875f960bd19342c08c81c6edc92e5ca1d8e/packages/theme/package.json
or
https://github.com/microsoft/fluentui/blob/7b743875f960bd19342c08c81c6edc92e5ca1d8e/packages/utilities/package.json

**Comment by layershifter** [comment]
@sirdawidd thanks for the input, I will check one more time all deps in the tree.

**Comment by layershifter** [comment]
I just installed `@fluentui/react@8.47.1`, it installs `@fluentui/theme@^2.4.4`:

![image](https://user-images.githubusercontent.com/14183168/145840478-958567b4-eac6-4d3d-9f1e-0c5dadc6b192.png)

And it has proper `peerDependencies`:

https://github.com/microsoft/fluentui/blob/b8ca4b3642b752e506fc6617c13c2568867c5464/packages/theme/package.json#L42-L45

---

You referenced `@fluentui/theme@1.7.4` & `@uifabric/utilities@7.33.5` - both are v7 packages 🙄 Can you please check your dependencies? What installs these packages?
