### ISSUE TITLE
ICalendarStyles interface is not found

### ISSUE THREAD

**Issue by reddem-anu** [microsoft/fluentui#20996]
### Environment Information
Package version(s):"@fluentui/react": "~7.121.11",
Actual behavior:
Im trying to customize the style of goTodayButton in the Calendar component. Doing so in the following manner:
const hostStyles: ICalendarStyles = { goTodayButton: { display: 'inline-block'}};

<Calendar
style={.merge(.cloneDeep(hostStyles), props.style)}
However, Im not able to import ICalendarStyles.

Expected behavior:
This compile error shouldn't occur.

![image](https://user-images.githubusercontent.com/90713746/145689623-b4b4acb4-fa09-4d41-bbc0-30bfd051d3b4.png)

Here's the link to the CodePen
[CodePen](https://codepen.io/reddem-anu/pen/abLBoGN?editors=1111)

![image](https://user-images.githubusercontent.com/90713746/145689873-941bc4ff-8ebc-4ef5-94f7-b1be46eaaf74.png)

 [Link to Documentation](https://developer.microsoft.com/en-us/fluentui#/controls/web/calendar#ICalendarStyles)

**Comment by layershifter** [comment]
> Package version(s):"@fluentui/react": "~7.121.11",

Hey, are you sure that you are using v7?

As I see that type is available only in v8: https://developer.microsoft.com/en-us/fluentui?fabricVer=7#/controls/web/calendar
Codepen also uses v8.

Please check and let us know.

**Comment by reddem-anu** [comment]
I am using version 7 in my package. Guess we can't update the package version. But Codepen is using version 8 but ICalendarStyles is undefined. Why is that?

**Comment by layershifter** [comment]
> But Codepen is using version 8 but ICalendarStyles is undefined. Why is that?

Well, `interface`s and `type`s should be `undefined` as they don't exist in JavaScript (compiled code):

```ts
interface Foo {}

// 🚨 'Foo' only refers to a type, but is being used as a value here.
console.log(Foo)
```

[TypeScript Playground](https://www.typescriptlang.org/play?ssl=3&ssc=17&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgGIHt3IN4F8CwAUEQuiAM7oA2EAdFegOYAUG6AlEA)

---

I checked and `ICalendarStyles` is exported in `@fluentui/react@8.47.2` (latest release):

```tsx
import { ICalendarStyles } from "@fluentui/react";

const styles: Partial<ICalendarStyles> = {
  root: {
    color: "red"
  }
};
```

https://codesandbox.io/s/great-cdn-hjdkt?file=/src/App.tsx:52-128

**Comment by layershifter** [comment]
As we figure it out, it's not neither bug or regression. Unfortunately v7 is currently in maintenance cycle, we don't implement improvements it.

Please consider update to v8 to get all newest improvements 🙏
