### ISSUE TITLE
Checkbox API review: should `circular` prop be changed to a `shape` enum?

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#20993]
Do you think we'll have any other shapes in the future?  Square, rounded? If so, then we should use a discriminated union rather than a boolean.

_Originally posted by @GeoffCoxMSFT in https://github.com/microsoft/fluentui/pull/20904#discussion_r766807552_

**Comment by khmakoto** [comment]
`Button` already has a `shape` prop. My vote is to change this in `Checkbox` for the sake of consistency.
