### ISSUE TITLE
Additional call to onPendingValueChanged callback after focus change

### ISSUE THREAD

**Issue by dengeorge** [microsoft/fluentui#20999]
Multiple calls are fired to onPendingValueChanged callback when typing into the input in AppComboBox (in specific scenarios). 

### Please provide a reproduction of the bug in a codepen:

[Simple Scenario](https://codepen.io/dengeorge/details/OJxbZPJ)

Steps:

1. Open console
2. Click on input
3. Type 'a'
4. Notice two calls in the console:- one with 'undefined','undefined','a' and one with 'undefined','undefined,'undefined'
5. Type more characters. (On subsequent calls, this issue is not observed in this example)
6. Focus out of ComboBox input.
7. Focus back in to ComboBox input.
8. Type 'b'
9. Notice the two calls once again.

I've provided a sample of the scenario I'm trying to execute as well. Here the issue occurs more frequently. I'm trying to filter the ComboBox options as the user types into the ComboBox. I'm keeping track of the full list of options at the higher level component and passing the filtered options to the ComboBox. Here, on every character change the two calls are triggered.

[Actual Scenario - Filter ComboBox options](https://codepen.io/dengeorge/pen/BawQxyy)

P.S. Menu will disappear after you type the first character in the input, since all subsequent character entries will have two calls and the last one will always be with text undefined. So none of the options will match. Can't go with a top level guard condition either, since the same ComboBox element is also used in cases where we want to preview and revert previews when the user hovers in/out of an option. For the latter, this callback gets triggered with all parameters as undefined.

#### Actual behavior:

Multiple calls triggered for onPendingValueChanged when typing freeform text in certain scenarios (detailed above)

#### Expected behavior:

Single call should take place with only last parameter defined with the value of the text in the input element.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, investigated the ComboBox code but not sure what's causing the issue

Requested priority: High

**Comment by gouttierre** [comment]
@dengeorge - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue? Thanks
