### ISSUE TITLE
Screen reader announces ChoiceGroup Options as invalid

### ISSUE THREAD

**Issue by melb47** [microsoft/fluentui#20992]
### Environment Information

- Fluent UI React 8.47.1
- Windows 11, Microsoft Edge 96

### Describe the issue:

When arrowing down through choice group options, when none have been selected, Narrator announces each option as invalid.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/melaphyre/pen/jOGMGdg

#### Actual behavior:

Narrator reads the first option as "Option A, radio button, non-selected, required, invalid, 1 of 4."

#### Expected behavior:

Narrator should read "Option A, radio button, non-selected, required, 1 of 4."

### Documentation describing expected behavior

https://www.tpgi.com/required-attribute-requirements/
https://www.w3.org/TR/wai-aria-1.1/#aria-invalid

https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships
https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions

Information from the accessibility team on how to fix: 

> aria-invalid=false would need to be specified either on the specific input type=radio, or on an ancestor role=radiogroup which had an aria-required=true
>  
> e.g.,
>  
> ```
> <div role=radiogroup aria-invalid="true|false" aria-labelledby=f aria-required=true>
>    <el id=f>group's name</el>
>  
>    
> </div>
> ```
> 
> side note though, Narrator won't announce a radiogroup as being required per my above markup... NVDA does, correctly.  So that's a Narrator gap. The alternative to work around the Narrator gap is to use the required attribute on the individual radio button.  and in that case you would have to use aria-invalid="true|false" on the radio button as well

**Comment by smhigley** [comment]
@melb47 you can set `aria-invalid` (or any other native prop) on the radio inputs by specifying it in the `options` array:

```js
const options: IChoiceGroupOption[] = [
  { key: 'A', text: 'Option A', 'aria-invalid': 'false' },
  { key: 'B', text: 'Option B', 'aria-invalid': 'false' },
  { key: 'C', text: 'Option C', 'aria-invalid': 'false' },
  { key: 'D', text: 'Option D', 'aria-invalid': 'false' },
];

<ChoiceGroup options={options}>
```

I don't think this would be something handled internally by Fluent, since we don't override the default required/invalid browser behavior on any other form components.
