### ISSUE TITLE
Checkbox API review: should `indicator` slot be renamed to `checkmark`?

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#20994]
Consider if the indicator slot should be called checkmark as that is how the comment describes it.

_Originally posted by @GeoffCoxMSFT in https://github.com/microsoft/fluentui/pull/20904#discussion_r766813144_

**Comment by khmakoto** [comment]
I think at first glance it makes sense to change that to checkmark, the only weird thing about that is what happens then with the indeterminate state indicator, or what happens if you replace that slot with something that isn't a checkmark (an "x" for example).

**Comment by behowell** [comment]
I'm inclined to leave this named indicator for the following reasons:
* The slot is the entire box plus checkmark inside, and the slot is always rendered even if unchecked and there's no checkmark.
* Like @khmakoto said, the indicator could be something other than a checkmark (e.g. the square for mixed, or an "x" or something).
* The OpenUI Editor's Draft uses `indicator`: https://open-ui.org/components/checkbox
* `RadioItem` has a very similar anatomy to `Checkbox`, and it would be nice if they had the same name for this slot: `indicator` makes sense in both cases, but `checkmark` doesn't. (This is less important, but a nice-to-have)

WDYT @GeoffCoxMSFT ?

**Comment by GeoffCoxMSFT** [comment]
Sounds good to me.  I named it selectionIndicator in react-tabs because there wasn't a better word that was too specific to the current visual underline.  `indicator` is pretty generic (say vs.  checkedIndicator), but since it is in a checkbox I think people will figure it out :)
