### ISSUE TITLE
PeoplePicker item removed event get removed object item

### ISSUE THREAD

**Issue by molyom** [microsoft/fluentui#21015]
#### Describe the feature that you would like added
Evey time that I added an item to the People Picker, it backs all added Items and I need to compare them with other object list People selected to do my action with the removed Item.
Is there any possibility to add an event to the event lists that we can call when we add an Item (just the added item) and also other event for remove item (just back the removed item) ?

#### What component or utility would this be added to
PeoplePicker Miscrosoft Fluent UI

#### Additional context/screenshots
Is there any trick that gives me just a Removed item (and Added item)?

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [PeoplePicker](https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by molyom** [comment]
Hi, I achieve the solution for it. 
Below I share my code:



  return (
        <PeoplePickerItem {...props} onRemoveItem={onRemoveItem}>
          {props.item.text}</PeoplePickerItem>

      );
    }

    return (
      <div >
        <NormalPeoplePicker
          styles={boxStyles}
          onResolveSuggestions={this._onFilterChanged}
          onEmptyInputFocus={this._returnMostRecentlyUsed}
          getTextFromItem={this._getTextFromItem}
          pickerSuggestionsProps={suggestionProps}
          // className={'ms-PeoplePicker'}
          key={'normal'}
          onRemoveSuggestion={this._onRemoveSuggestion}
          onValidateInput={this._validateInput}
          removeButtonAriaLabel={'Remove'}
          defaultSelectedItems={this.props.preselectedpeople}
          onItemSelected={this._onItemSelected}
          onRenderItem={_onRemoveItemFunction}
          // inputProps={{
          //   onBlur: (ev: React.FocusEvent<HTMLInputElement>) => {
          //   },
          //   onFocus: (ev: React.FocusEvent<HTMLInputElement>) => {
          //   },
          //   'aria-label': 'People Picker', 
          // }}
          inputProps={this.props.preselectedpeople.length == 0 ? { placeholder: '---' } : { placeholder: '' }}
          componentRef={this._picker}
          onInputChange={this._onInputChange}
          resolveDelay={300}
          disabled={this.props.isPickerDisabled}

          onChange={() => {
            this.handleChange()
          }}

**Comment by molyom** [comment]
Thanks, I confirm that you can close this issue. I could find the reason and fix it in my code. 
Kind regards
