### ISSUE TITLE
Icon Button with tooltip - Screen reader not reading content in tooltip component

### ISSUE THREAD

**Issue by kejatura** [microsoft/fluentui#21027]
### Environment Information

- **Package version(s)**: 8.47.2
- **Browser and OS versions**: Windows - Edge chromium

### Describe the issue:

In the code example for "Icon Button with tooltip" - https://developer.microsoft.com/en-us/fluentui#/controls/web/button, the `title` attribute is used w/ fluent's tooltip component (Side note: not sure why both are added as demo, as these both serve the same purpose). The `title` value is read out by the screen readers, but the actual `content` in Fluent's tooltip component isn't.

Tested this with JAWS 2020, Narrator (Windows 11), and NVDA and none were able to read the content provided in the tooltip component.
 

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/kejatura/pen/eYEEyVL
- On hover, you should see different messages.

#### Actual behavior:
The default browser tooltips are being read by the screen readers, but the content within the tooltip component is not.

#### Expected behavior:

Should be able to read the content within the tooltip component.

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue? 
cc @smhigley
