### ISSUE TITLE
Exposing IPersonaPresenceProps to define custom styling on presenceIcon

### ISSUE THREAD

**Issue by kevincolour** [microsoft/fluentui#21031]
#### Describe the feature that you would like added

I'm trying to add custom styling directly on the presence icon that is rendered for the `Persona` component. Currently, there is no way to access the styling of the presence icon on the `Persona` component. I need `IPersonaPresenceProps` to be exposed on `IPersonaProps` or `IPersonaSharedProps` 
#### What component or utility would this be added to
Persona Component

**Comment by gouttierre** [comment]
@kevincolour - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
