### ISSUE TITLE
Menu option does not close on clicking on it again with touch on iOS Safari browser

### ISSUE THREAD

**Issue by gurssingh** [microsoft/fluentui#21064]
Observation: Both onMenuDismissed, onMenuOpened called respectively passed via menuProps in IconButton when re-clicking on menu option on iOS  15.1 Safari

Actual behavior:
Menu option does not close on clicking on it again with touch on iOS Safari browser

Expected behavior:
Menu option should close on clicking on it again with touch on iOS Safari browser.

**Comment by layershifter** [comment]
@gurssingh can you please fill the issue template fully and provide reproduction steps?
