### ISSUE TITLE
Project (January): Screener improvements

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#21070]
## Problem

As we've added more tests for converged components, we've been hitting a hardcoded [30-minute timeout in `screener-runner`](https://github.com/screener-io/screener-runner/blob/ad615d12691c52ac13d069df960f204725486cfd/src/runner.js#L13). This makes the build fail even if the screener run eventually succeeds.

There are also a couple screener-related backlog items we need to address at some point:
- Investigate switching to Chromatic (or another platform?)
  - Chromatic is missing built-in interaction testing support, but can we find a workaround?
  - Are there any other testing platforms worth considering?
- Migrate screener stories to component story format instead of `storiesOf` (`storiesOf` will be removed in storybook 7)

## Appetite

1 week if only splitting v8/converged runs, or up to 4 weeks if addressing more items

### Split v8/converged screener runs

At minimum, we need to split v8 and converged visual tests into separate screener runs.

We'll use our custom screener proxy (currently being used for northstar) to run at least the converged tests. TBD whether any work will be needed inside the screener proxy to support an additional target.

For v8, we could either switch to the custom proxy or stick with screener-runner. Getting rid of the ngrok dependency (inside screener-runner) would be nice, so I'd like to switch to the custom proxy if it's not too much work.

### (scope TBD) Investigate screener alternatives

- Investigate chromatic:
  - set it up with a small demo storybook: https://www.chromatic.com/docs/storybook
  - try to get interaction testing working:
    - the suggestion to [trigger CSS states via props](https://www.chromatic.com/docs/hoverfocus#trigger-css-states-via-props) will not work (we're not going to add `hover` props to all our components...)
    - maybe it would be possible to make a wrapper component which does interactions in an effect and take snapshots [on a delay](https://www.chromatic.com/docs/delay)?
     - is this useful? https://storybook.js.org/blog/interaction-testing-sneak-peek/
- Ask around if anyone knows of options besides chromatic

### (scope TBD) Move to component story format

Storybook has a migration for `storiesOf` to CSF: `npx sb migrate storiesof-to-csf --glob "**/*.stories.js"`
https://storybook.js.org/blog/component-story-format/

This doesn't quite work out of box on our stories, but if we make the following manual modifications it will get us a lot of the way there:
- Find/replace `addStory` => `add` (so the mod will recognize it; leaving the extra parameters for now is fine)
- For anything with multiple `storiesOf` calls in the same file (at least with the same name), split it into multiple files

The migration more or less works after that (based on a small test). We'll still have to figure out how to restore the functionality of auto-added stories for RTL and different themes (that's what the `addStory` API did) but there should be some way to do it.

## Risks (Rabbit holes)

The big unknown for splitting runs is the amount of work (if any) required in the custom screener proxy to support another target besides northstar.

## Out of scope (No-gos)

If we decide to only address the immediate issue of splitting v8/converged runs, any changes to the story format are out of scope.

**Comment by ling1726** [comment]
Custom screener proxy currently only supports a one to one mapping between screener project and github check. It's fairly easy to split out the actual storybook projects and deploy separately.

The hard part is to update and redeploy the screener proxy to handle multi maps to create multiple github checks

**Comment by ecraig12345** [comment]
Made #21779 to track removing storiesOf
