### ISSUE TITLE
IGroupHeaderStyles.expand style not getting triggered 

### ISSUE THREAD

**Issue by raspour** [microsoft/fluentui#21084]
hi,
I'm trying to add some  animation style  to expand GroupHeaderProps without any success. 
not sure about the reason but-to me- it seems like IGroupHeaderStyles.expand style not getting triggered.
any clue of how possibly the animation can be added will be highly appreciated.
thanks

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [GroupedList](https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
