### ISSUE TITLE
Checkbox component - tick mark present for unchecked checkbox

### ISSUE THREAD

**Issue by kbalakumar1** [microsoft/fluentui#21087]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

This is regarding the checkbox component. If we check, and uncheck the checkbox in safari (Mac) and hover over the checkbox, there is a tick mark that appears in the checkbox (the solid selected color goes away though). In safari (mobile), if we check and uncheck the checkbox, the tick mark stays until we tap on the screen. In order to select the checkbox, tapping / clicking anywhere close by (like the text for it) also selects the checkbox. Are these two expected behaviors of the checkbox component? 

#### Expected behavior:

When the checkbox is in the unchecked state, the tick mark should not appear when we hover over it. Similarly, the tick mark in mobile should disappear without the user having to tap on the screen.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) **Yes**

Requested priority: (Blocking, High, Normal, Low) **Normal**

Products/sites affected: (if applicable)

**Comment by kbalakumar1** [comment]
@layershifter : Hello Oleksandr, I just wanted to do a quick check up on this issue and if you need any additional information from my end to help you triage this issue. Thank you.

**Comment by JustSlone** [comment]
@kbalakumar1 can you share a code pen demonstrating the repro (or does it simply repro on the example here: https://developer.microsoft.com/en-us/fluentui#/controls/web/checkbox)

**Comment by kbalakumar1** [comment]
@JustSlone It does repro on the checkbox component in the fluent UI website provided by you. Basically, if you uncheck a checkbox, then the solid color goes away but on hovering over the checkbox, there is a tick mark displayed that could be kind of misleading to the user. Whereas in mobile browser, the tick mark for the unchecked checkbox only goes away when you tap on the screen. Let me know if you have any questions. Thank you.

**Comment by kbalakumar1** [comment]
Yes, exactly!! You got it right. We are importing this checkbox component from the fluent UI and using it in our website. We were thinking along the lines where if this is the case, then it could possibly confuse the users when they uncheck the checkbox and still see the tick mark in it (when you hover over it). 
Is it possible to modify the component in such a way that for unchecked checkboxes, a tick mark isn't visible?

**Comment by spmonahan** [comment]
@kbalakumar1 `Checkbox` doesn't accept user-supplied class names and the `style` prop won't work in this case as you need to use the `:hover` pseudo class. In this case you'll need to write some CSS and add it to your site with either a `<style>` block or an external stylesheet.

[This Codepen is an example of how you can style the checkmark](https://codepen.io/seanms/pen/QWqYLXX?editors=0100).
