### ISSUE TITLE
Focus is lost when navigating away from input element with Narrator Scan Mode

### ISSUE THREAD

**Issue by capucat** [microsoft/fluentui#21083]
### Environment Information

- **Package version(s)**: Version 7
- **Browser and OS versions**: Edge, Windows 11

### Describe the issue:

Our product has an a11y issue involving components that contain an input element. In our case we are using a ComboBox inside of a fluent Modal, but we are seeing somewhat similar behavior to what is described here. When narrator is in scan mode, trying to navigate away from any element that contains an input element will cause narrator to lose focus. This can cause a few different things when arrowing down: 
1) Focus is trapped to the ComboBox when trying to navigate away (currently the main issue)
2) Narrator will completely lose focus to outside of the Modal
3) Narrator focus remains in modal, but announces page information and not element. Next arrow down will behave as expected.

This behavior is very specific to scan mode. Tabbing and having scan mode off behaves as expected.
The above behaviors are very difficult to reproduce in a codepen, so i've just described some similar behavior below that might help to solve the issue.
#### Actual behavior:

Using Arrow down after any component containing an input element, narrator announces ''scan off', blank, scan', and does not focus on the expected next element. After another arrow down, it will focus on the expected element.

#### Expected behavior:
Using arrow down after an input element should focus on the next element.

### If applicable, please provide a codepen repro:

Some examples from fluentUI website:
https://developer.microsoft.com/en-us/fluentui?fabricVer=7#/controls/web/focustrapzone
- Simple Box example: navigating from input to hyperlink

https://codepen.io/capucat/pen/GRMmJxZ
- This is a more isolated version of the basic TextField example

https://codepen.io/capucat/pen/LYzyPKE
- TextField and simple div with text in Fluent dialog example

**Comment by gouttierre** [comment]
@capucat  - I’ve added this to our contributor backlog for review for later investigation/ contribution but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.

cc @smhigley
