### ISSUE TITLE
Screen reader issue with a radiogroup rendered inside a CommandBar- button

### ISSUE THREAD

**Issue by ilanbd** [microsoft/fluentui#21094]
### Environment Information

- **Package version(s)**:8.46.3
- **Browser and OS versions**:  96.0.1054.62 + Win 11

### Describe the issue:
When using the CommandBar with a menu-button and rendering inside it a checkbox and a radiog group we have a bug with the narator.

when activating the checkbox, the narator reads out also the info of the Radio group.
This is not hapenning when rendering only these component without the CommandBar

### Please provide a reproduction of the issue in a codepen:

1. Open https://codepen.io/ilanbd/pen/XWegaQR?editors=1111
2. Activate narator
3. Navigate to the button labeled as 'options'
4. Press Space to open the menu
5. Use tab to reach the Checkbox
6. Press Space to check/uncheck the checkbox
7. Observe the bug

#### Actual behavior:

The Narator should annouce only : checked/unchecked

#### Expected behavior:

The Narator annouce checked/unchecked and then annouce info about the Radio Group that is below the checkbox

**Comment by ilanbd** [comment]
Hi @layershifter :), any update on this?

**Comment by gouttierre** [comment]
@ilanbd - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue? 
cc @smhigley

**Comment by ilanbd** [comment]
Hi @gouttierre :) any update on this?

**Comment by smhigley** [comment]
CommandBar is semantically an element with `role="menu"`, and as such it can only accept interactive children that have a role of `menuitem | menuitemcheckbox | menuitemradio`. The items in CommandBar have a `menuitem` role by default. If you override the render of CommandBar items, they absolutely must be singular interactive elements with a `menuitem`/`menuitemcheckbox`/`menuitemradio` role. Standard HTML checkboxes and radios are not supported, and will cause problems for screen reader users.
