### ISSUE TITLE
Basic List control breaks severely on grid example when using fixed size elements

### ISSUE THREAD

**Issue by gremlin529** [microsoft/fluentui#21098]
### Environment Information

- **Package version(s)**: (fill this out) Using latest master branch of ppux code base
- **Browser and OS versions**: (fill this out if relevant)
- Both Edge and Chrome latest released version

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/gremlin529/pen/xxXdGMo

![ScrollBugInCodePen](https://user-images.githubusercontent.com/56889386/146820138-324e08fb-b9e7-4979-a81b-4b77b21a6b95.gif)

The change in this code pen is simple, I simply changed three lines in onRenderCell to render a fixed size instead of realtively sized cell

```
const onRenderCell = React.useCallback((item: IExampleItem, index: number | undefined) => {
    return (
      <div
        className={classNames.listGridExampleTile}
        data-is-focusable
        style={{
          width: 270,
          marginRight:10,
          marginTop:10
        }}

```

#### Actual behavior:

You will see blank pages, and the scrolling will hop around unpredictably

#### Expected behavior:

Smooth functioning scrolling

### Priorities and help requested:

I can't seem to find the source code to debug so some help is requested.

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

In addition to this bug, I also have found the grid list sample code a little confusing due to the manner in which the two callbacks are computed 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/ramans/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/ramans/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/ramans/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in;word-wrap:
break-word'>

<p class=xmsonormal style='margin:0in'><b><span style='font-size:14.0pt'>Separate
comments on the sample</span></b><o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>A separate note I think the example is
not very clear in what it’s doing W.R.T. to the values being computed just in
how it does it.<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>Here’s the docs I’ve been looking at: <a
href="https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffabricweb.z5.web.core.windows.net%2Foufr%2F8.34.1%2F%23%2Fexamples%2Flist&amp;data=04%7C01%7Craman%40xbox.com%7Ce7b83ab92ee144b0a1af08d9c0de70dc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637752883898357554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp;sdata=4n%2Foweq2kAANlWyEAc4DrlUtDJN4JmqkPL0Fx83Ow8o%3D&amp;reserved=0">Fluent
UI React Examples (windows.net)</a><o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>Using the very first example which is
what I’m trying to do (List of 5000 grid items) &nbsp;I’m super confused about
some of the values the sample is showing<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>Here’s the docs:<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

getItemCountForPage | (itemIndex?:   number, visibleRect?: IRectangle) => number | Method   called by the list to get how many items to render per page from specified   index. In general, use getPageSpecification instead.
-- | -- | --
getPageHeight | (itemIndex?:   number, visibleRect?: IRectangle, itemCount?:   number) => number | Method   called by the list to get the pixel height for a given page. By default, we   measure the first page's height and default all other pages to that height   when calculating the surface space. It is ideal to be able to adequately   predict page heights in order to keep the surface space from jumping in   pixels, which has been seen to cause browser performance issues. In general,   use getPageSpecification instead.

<p class=xmsonormal style='margin:0in'><span style='color:white'>&nbsp;</span><o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>The way I read the above is getItemCount
is the number of items shown on a page (I assume a page is what is showing on
screen) so this ought to be something like <o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin:0in;text-indent:.5in'>(screenWidth/itemWidth)*(screenHeight/itemHeight)
i.e. number of columns * number of rows displayed<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>getPageHeight says pixel height for a
given page which should be <o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
rowsPerPage*itemHeight&nbsp; &nbsp;(although I’m not entirely sure why it’s not
just the visibleRect.Height passed in on getItemCountForPage, those should be
close)<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>Now some code from the example<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin-top:0in;margin-right:0in;margin-bottom:0in;
margin-left:.5in'><span style='font-family:"Cascadia Mono"'>&nbsp; const
getItemCountForPage = React.useCallback((itemIndex: number, surfaceRect:
IRectangle) =&gt; {</span><o:p></o:p></p>

<p class=xmsonormal style='margin-top:0in;margin-right:0in;margin-bottom:0in;
margin-left:.5in'><span style='font-family:"Cascadia Mono"'>&nbsp;&nbsp;&nbsp;
if (itemIndex === 0) {</span><o:p></o:p></p>

<p class=xmsonormal style='margin-top:0in;margin-right:0in;margin-bottom:0in;
margin-left:.5in'><span style='font-family:"Cascadia Mono"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
columnCount.current = Math.ceil(surfaceRect.width / MAX_ROW_HEIGHT);</span><o:p></o:p></p>

<p class=xmsonormal style='margin-top:0in;margin-right:0in;margin-bottom:0in;
margin-left:.5in'><span style='font-family:"Cascadia Mono"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
rowHeight.current = Math.floor(surfaceRect.width / columnCount.current);</span><o:p></o:p></p>

<p class=xmsonormal style='margin-top:0in;margin-right:0in;margin-bottom:0in;
margin-left:.5in'><span style='font-family:"Cascadia Mono"'>&nbsp;&nbsp;&nbsp;
}</span><o:p></o:p></p>

<p class=xmsonormal style='margin-top:0in;margin-right:0in;margin-bottom:0in;
margin-left:.5in'><span style='font-family:"Cascadia Mono"'>&nbsp;&nbsp;&nbsp;
return columnCount.current * ROWS_PER_PAGE;</span><o:p></o:p></p>

<p class=xmsonormal style='margin-top:0in;margin-right:0in;margin-bottom:0in;
margin-left:.5in'><span style='font-family:"Cascadia Mono"'>&nbsp;}, []);</span><o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>From what I can determine this is doing
something weird<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
columnCount.current instead of being screenWidth/itemWidth is
screenWidth/itemHeight, let’s ignore this though since maybe the items are
square so that seems okay<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
rowHeight seems more problematic it’s looking like it’s actually computing the
width/columnCount which is actually pixelWidth of an item, so that could be
okay maybe if again the items are square<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
but it returns cols*ROWS_PER_PAGE which is hard coded to 4, which seems weird,
but okay<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>Now looking at the next function<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin-top:0in;margin-right:0in;margin-bottom:0in;
margin-left:.5in'><span style='font-family:"Cascadia Mono"'>const getPageHeight
= React.useCallback((): number =&gt; {</span><o:p></o:p></p>

<p class=xmsonormal style='margin-top:0in;margin-right:0in;margin-bottom:0in;
margin-left:.5in'><span style='font-family:"Cascadia Mono"'>&nbsp;&nbsp; return
rowHeight.current * ROWS_PER_PAGE;</span><o:p></o:p></p>

<p class=xmsonormal style='margin-top:0in;margin-right:0in;margin-bottom:0in;
margin-left:.5in'><span style='font-family:"Cascadia Mono"'>&nbsp; }, []);</span><o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>&nbsp;<o:p></o:p></p>

<p class=xmsonormal style='margin:0in'>This is supposed to return the height of
the page in pixels and again assuming the items are square I think it does
this. <o:p></o:p></p>

</body>

</html>

**Comment by gremlin529** [comment]
Forgot to mention that this is a blocking issue for Power Cards

**Comment by JustSlone** [comment]
Thanks @gremlin529 for the investigation. Lots of folks are out so it might take some time to get ahold of someone familiar with this particular code. 

There is a pretty clear repro there though. Actually, I'm able to repro just by changing the # of items in the grid example from 5000 to 500 (I think it might even repro with 5000 just lest frequent or harder to repro).

Btw, the code is here: https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/List/List.tsx if someone is able to dig in further. 

You can also repro/debug this in the official examples

> clone repo
> yarn install
> yarn start
> Choose @fluentui/react 
> Once storybook runs, browse to the list grid example
> edit List.Grid.Example.tsx to change `createListItems(5000)` -> `createListItems(500)`
> Now you can debug in the browser and edit the component code and storybook will reload it

**Comment by JustSlone** [comment]
Some observations regarding the scroll bar bouncing back and forth issue:

* This appears to be due to a spacer being added and removed by the async idle code. Which results in a loop of adding/removing the spacer causing the content and the scrollbar to jump
* The best repro I found is to scroll to 1/4 of the way down the page fairly quickly, then stop scrolling when you see the scrollbar jump. If i scroll slowly the issue does not repro.
* I tried converting the example back to a class component it see if the other issue with class components and List was affecting this, it did still repros when using List from a class component
* Reducing `IDLE_DEBOUNCE_DELAY` significantly makes this very hard to repro, perhaps eliminating the issue, but that's a pretty poor bandaid
* The real fix is probably digging into the virtualization code and correcting the calculations to not have this add/remove behavior for spacers
* Note: the code also does not access scrollTop correctly and it appears to be always zero, I fixed that locally, but it had no affect on the issue at hand.

**Comment by gremlin529** [comment]
Thank you @JustSlone  hopefully someone can tackle this when they return for the new year.

**Comment by JustSlone** [comment]
Yep, @spmonahan is looking into it, and reaching out to folks

**Comment by spmonahan** [comment]
After spending some time digging into this I agree that the code that controls the spacer height is most likely the cause of this issue. I will follow up with more info when I have it.

**Comment by spmonahan** [comment]
Hi @gremlin529 After looking at this a bit and talking with some folks internally I think the answer is to use the `TilesList` component in the `react-experiments` package. While this is in the experiments package this particular component is used heavily in production apps at Microsoft so I feel comfortable recommending it. Under the hood `TilesList` uses `List` and it provides some nice features for aligning items to a grid.

- `TilesList` source: https://github.com/microsoft/fluentui/tree/master/packages/react-experiments/src/components/TilesList
- `TilesList` examples: https://github.com/microsoft/fluentui/tree/master/packages/react-examples/src/react-experiments/TilesList
  - These can be run locally by cloning the repo locally and running `yarn start` from the repo root and then selecting the react-experiments project from the list that appears
- [Codesandbox Example of TilesList](https://codesandbox.io/s/tileslist-basic-example-ms44x)
  - A live example that you can play with

---

While I feel that `TilesList` is likely to be your best bet I worked on the example you shared a bit more to produce a working solution with the `List` component that is provided as part of `@fluentui/react`.

[Codesandbox Example with List and Flexbox Layout](https://codesandbox.io/s/list-with-flexbox-layout-led82?file=/src/ListExample.tsx)

The core issue with the example you provided is that the tiles had `float: left` applied which collapsed their parent `div`s making height calculations with those `div`s inaccurate which created the observed problem. This may be solvable by inserting a clearfix into page styles but I opted for a flexbox approach. The key is to ensure the values produced by `getPageHeight()` and `getItemCountForPage()` are aligned (that is, that `getPageHeight()` is the height, in pixels, for the item count returned from `getItemCountForPage()`).

**Comment by gremlin529** [comment]
bumping to keep alive
