### ISSUE TITLE
 Request to change the behavior on MouseOver event for CommandBarButton and Callout

### ISSUE THREAD

**Issue by qaehtesh** [microsoft/fluentui#21100]
### Environment Information

Current version
Any browser on Windows10

#### Actual behavior:
The list of "Likes" disappears when the mouse pointer overs on top of Outlook on the web which uses the same fluentui code

CommandBarButton and Callout
https://github.com/microsoft/fluentui/blob/dab45a2afe609709735b9b6e604a1af40d50e809/packages/react-examples/src/react/CommandBar/CommandBar.ButtonAs.Example.tsx
fluentui/packages/react-examples/src/react/CommandBar/CommandBar.ButtonAs.Example.tsx

Although the feature works fine, it's just a little subtle to make it work and not consistent

#### Expected behavior:

The mouse should not disappear when hovering on the The list of "Likes" 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
