### ISSUE TITLE
[v9] Accordion indicator and icon do not have sufficient contrast in forced colors mode (Windows HC theme)

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#21118]
### Environment Information

- **Package version(s)**: @fluentui/react-components v9 beta
- **Browser and OS versions**: all

### Describe the issue:

Accordion indicator and icon do not have sufficient contrast in forced colors mode (Windows HC theme)

![image](https://user-images.githubusercontent.com/13742664/147253733-86da2324-309f-4bf3-aafe-799056427c8c.png)

1. Open storybook Accordion story
2. Switch Windows theme to HC
3. Observe example with Icon

#### Actual behavior:

![image](https://user-images.githubusercontent.com/13742664/147253733-86da2324-309f-4bf3-aafe-799056427c8c.png)

#### Expected behavior:

Icon and the indicator have correct color (same as accoridon panel text)

**Comment by bsunderhus** [comment]
I couldn't reproduce this @jurokapsiar, seems to be fine on our documentation

![image](https://github.com/microsoft/fluentui/assets/5483269/9bafad50-2067-448b-b457-a423c7476cfa)
