### ISSUE TITLE
fluentui for other platforms (flutter, react-native, angular, svelte)

### ISSUE THREAD

**Issue by bharadwajduggaraju** [microsoft/fluentui#21111]
#### Describe the feature that you would like added

any chance we will see any sort of implementation in the future in frameworks like flutter, or react-native, even other web frameworks like angular and svelte. this seems cool if I could use it in any sort of react-native mobile app.

**Comment by gouttierre** [comment]
@bharadwajduggaraju - Thanks for filing this question with us. 

@ejlayne - Would you mind chiming in about our  `FluentUI` and `react-native` support? Thanks
