### ISSUE TITLE
[v9] Accordion active panel button is marked as disabled

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#21121]
### Environment Information

- **Package version(s)**: @fluentui/react-components v9 beta
- **Browser and OS versions**: all

### Describe the issue:

Expanded panel buttons are marked as disabled:
![image](https://user-images.githubusercontent.com/13742664/147257025-8950ae6e-f8da-4b82-9237-fbf5b4b997b3.png)

### Please provide a reproduction of the issue in a codepen:

1. Open v9 storybook, navigate to Accordion examples
2. Open one of the pannels
3. Observe aria attributes on the button

This is causing the screen readers to read "disabled" or "not available" when navigating to the button.

#### Actual behavior:

Button has aria-disabled set to true

#### Expected behavior:

Aria disabled is not present

### Documentation describing expected behavior

https://w3c.github.io/aria-practices/examples/accordion/accordion.html

**Comment by bsunderhus** [comment]
I believe this is expected behavior @jurokapsiar on the WAI-ARIA documentation, if a panel cannot be collapsed than it should have it's header marked as `aria-disabled`, is that the case?

> If the accordion panel associated with an accordion header is visible, and if the accordion does not permit the panel to be collapsed, the header button element has aria-disabled set to true.
> [WAI-ARIA Roles, States, and Properties](https://www.w3.org/TR/wai-aria-practices/#wai-aria-roles-states-and-properties)
