### ISSUE TITLE
[v9] Accordion documentation lacks information about the necessity of providing matching heading level

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#21120]
### Environment Information

- **Package version(s)**: @fluentui/react-components v9 beta
- **Browser and OS versions**: all

### Describe the issue:

Accordion renders a heading for each category. This is expected and conformant with ARIA pattern. However, we do not highlight in the documentation that the heading level needs to be provided.

**Comment by bsunderhus** [comment]
One question regarding this behavior @jurokapsiar : should we generate some warning if neither a semantic element or the proper `aria` attribute is provided by the user?
