### ISSUE TITLE
Panel with footer hides content in Firefox when overflowing

### ISSUE THREAD

**Issue by jasmcn** [microsoft/fluentui#21131]
### Environment Information

- **Package version(s)**: Latest V8 (8.48.1 at time of writing)
- **Browser and OS versions**: Firefox 95.0.2, Windows 11 (Not an issue in Chromium Edge or Chrome)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/jasmcn/pen/BawJeym

You should see that the last row of content "LAST CONTENT NOT VISIBLE" is not visible. If onRenderFooterContent is not provided, the last row of content is visible.

#### Actual behavior:

When a panel overflows with a footer, a certain amount of content is cut off and not visible to the user. If you resize the browser window vertically, the content will become visible.

#### Expected behavior:

All content should be shown when a panel overflows when using the footer props without resizing the browser window.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

**Comment by spmonahan** [comment]
Thanks for providing the example @jasmcn !

I can confirm the issue in Firefox 95 on Windows 11 and that both Edge and Chrome work as expected.
NOTE: I did have to view the example in ["full" view on Codepen](https://codepen.io/jasmcn/full/BawJeym) to repro the issue in Firefox. The issue did not repro in Codepen's editor view.

Tagged to investigate further.

**Comment by spmonahan** [comment]
Not exactly the same scenario but it looks like Firefox has issues with Flexbox and sticky children: https://bugzilla.mozilla.org/show_bug.cgi?id=1488080

`Panel` is a flex container and the footer is made sticky with `position: sticky`. When inspecting the elements in Firefox devtools the panel footer overlaps the panel content. When inspecting the same elements in Edge they stack as expected for flex elements. Triggering a window resize in Firefox as noted in the initial issue causes Firefox's layout to match that of Edge but scrolling the panel content will again trigger the issue. Seems related to the Firefox bug linked above.

One workaround for this is to apply additional padding to the bottom of the panel content element.

**Comment by v-pasha2** [comment]
any expected ETA to fix this bug ?
