### ISSUE TITLE
Dropdown should show tooltips for options only when needed

### ISSUE THREAD

**Issue by avenezia** [microsoft/fluentui#21147]
### Environment Information

- **Package version(s)**: 8.29.2
- **Browser and OS versions**: Edge 97.0.1072.41 on Windows 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/avenezia/pen/abLGbKp

#### Actual behavior:

Dropdown shows native tooltips only for options having a title. Considering that the tooltips should be shown only for truncated options, this means that the user has to either:
- provide a title for any option, meaning that a tooltip would be shown also for options that do not require it because they are not truncated
- put in place a logic that determines if the option is truncated, and add a title only in this case

#### Expected behavior:

Dropdown should determine if an option is truncated, and show a tooltip only in this case (potentially without the need to provide a title).
In the referenced codepen, this would mean showing a tooltip only for the last two options. 

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Power Query

**Comment by gouttierre** [comment]
@avenezia - thank you for filing this issue with us and I reproduced the stated behavior you mentioned. To set expectations, the developers will review this issue once capacity allows as we’re currently focused on larger coherence work items.

@TristanWatanabe - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by JustSlone** [comment]
Echoing what @khmakoto said here, open to collaborating on a contribution here, but this is not something we'll be able to add given overall priorities. Marking Help Wanted.
