### ISSUE TITLE
Motion presets missing from @fluentui/react package

### ISSUE THREAD

**Issue by AndrewCraswell** [microsoft/fluentui#21146]
### Environment Information

- **Package version(s)**: ^8.48.1
- **Browser and OS versions**: Windows 10, Chrome

#### Actual behavior:

The `MotionAnimations`, `MotionDurations`, and `MotionTimings` exist in the `@fluentui/theme` package, and were being re-exported from the `@fluentui/react` package like this:

```
// @fluentui/react/src/Theme.ts
export * from "@fluentui/theme"
```

However, it looks like on Nov 22nd the [`Theme.ts`](https://github.com/microsoft/fluentui/blob/master/packages/react/src/Theme.ts) file was refactored to not do a global export, and to selectively export a few things. In this process, the items mentioned are now missing. This means the Fluent UI docs are now out of sync, since they reference presets that don't exist:

https://developer.microsoft.com/en-us/fluentui#/styles/web/motion

#### Expected behavior:

My thought is that `MotionAnimations`, `MotionDurations`, and `MotionTimings` should be added back in. For now, my workaround is to just import them directly from the `@fluentui/theme` package. I'm wondering though if this was an intentional change, and if consumers are not meant to use these primitives anymore. Seems like the `AnimationStyles`, and `AnimationVariables` presets are being exported, and I hadn't seen them before. But on inspection, it seems like maybe they are based on the same primitives, but assemble the animation type, duration, and timings into complete styles that closely map to the Fluent Design Language. If this is the case, then maybe it's just the docs that are out of date, and I've been using lower-level primitives, which makes it harder to adhere to Fluent Design.

Are you willing to submit a PR to fix? (Yes, No)

Yes, if it's just a matter of exporting the items again.

Requested priority: (Blocking, High, Normal, Low)

Normal. Workaround exists.

Products/sites affected: (if applicable)

Career Coach

**Comment by spmonahan** [comment]
Thanks for reporting the issue @AndrewCraswell !

Can you [create a Codepen using our template](https://aka.ms/fluentpen) demonstrating how the primitives worked before the version in question?

**Comment by AndrewCraswell** [comment]
Hey @spmonahan, this Codesandbox will show the issue. Just update the `@fluentui/react` dependency to latest version to hit the issue.
https://codesandbox.io/s/reverent-saha-o6s2m?file=/src/BrokenCard.tsx
