### ISSUE TITLE
Readonly component properties and types, in particular for List items

### ISSUE THREAD

**Issue by beark** [microsoft/fluentui#21141]
#### Describe the feature that you would like added

React properties are meant to be treated as immutable/readonly. In many projects -- including one I'm currently working on -- it is therefore considered best practice to mark them so in the code. When passing them down to Fluent, however, I've been forced to assert some of them as non-readonly. Specifically, I was passing items to a `List` and had to do something like:
```ts
<List
  ...
  items={props.items as ItemType[]}
  ...>
```
since on our side, they were typed as `items: readonly ItemType[]`. This seems less than ideal, and made me worry that Fluent was actually mutating its `items` prop behind the scenes. I've reviewed the code and it doesn't seem like it is, so it seems like an obvious improvement to Fluent to use readonly types (including arrays) whenever possible. After all, writeable types can be assigned to readonly types, so it shouldn't actually break user code in most cases.

Only breakage that comes immediately to mind is if there are callbacks that are invoked Fluent side with things that should be readonly, but currently are typed as mutable. If you change the type in those callbacks too, there's bound to be a lot of breakage as I'm sure there are users who added explicit type signatures to their callbacks.

In our particular case, it would be enough for now if only the property types were changed, callback types could be later (whenever there is naturally a breaking version update) or even never.

#### What component or utility would this be added to

Probably most/all components have _some_ non-primitive property that would benefit from being readonly. But _we_ are primarily dealing with `List`.

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

Almost exactly this request has been previously discussed in #9427, but that was closed due to inactivity. It seemed like people were on board that it was a worthwhile change though.

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
