### ISSUE TITLE
dropdown callout scrolls randomly on mouse enter/leave

### ISSUE THREAD

**Issue by Jing29** [microsoft/fluentui#21167]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: chrome latest version

### Please provide a reproduction of the bug in a codepen: https://codepen.io/lijinglin29/pen/poWKgwg

The mouse only tries to move out the dropdown without scrolling the scrollbar, while the scrollbar in the dropdown moves automatically.

![fabric-ui-dropdown](https://user-images.githubusercontent.com/19400548/148171161-7f522ea0-edf6-46ca-a7ae-f10960e5f01f.gif)

#### Actual behavior:

When the mouse tries to move out/into the dropdown without scrolling the scrollbar, the scrollbar in the dropdown moves automatically.

#### Expected behavior:

When the mouse tries to move out/into the dropdown without scrolling the scrollbar, the scrollbar in the dropdown should not move.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: [Azure Synapse Analytics](https://azure.microsoft.com/en-us/services/synapse-analytics/#overview)

**Comment by gouttierre** [comment]
@Jing29 - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows as we’re currently focused on larger coherence work items. Also, I noticed you are using an older version on Fluent UI, would you mind utilizing our latest version as most of the fixes and enhancements are added to the later versions.  Thanks
