### ISSUE TITLE
SearchBox focus() does not set focus to input when inside ContextualMenu

### ISSUE THREAD

**Issue by tanisha2710** [microsoft/fluentui#21168]
Environment Information
Package version(s): 7.137
Browser and OS versions: (fill this out if relevant)
Please provide a reproduction of the bug in a codepen:
https://codepen.io/tanisha2710/pen/MWEXbdP

Actual behavior:
example with ref does not set the focus. Added some console statements as well which is clearly showing that the focus is not getting set 

Expected behavior:
calling focus() on the ref should set the focus.

Priorities and help requested:
Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low)Normal

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations, the developers will pick up this issue once capacity allows as we’re currently focused on larger coherence work items.
