### ISSUE TITLE
Input component padding right for the error indicator doesn't go away

### ISSUE THREAD

**Issue by boraunlu** [microsoft/fluentui#21178]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

In the Input component, if the errorIndicator is toggled on and off back again, the right padding in the box remains as the indicator is on.
![image](https://user-images.githubusercontent.com/13998127/148281707-4c04a757-60be-4bb0-bae2-6a9693f562c0.png)

#### Expected behavior:

The right padding in the box should be reset

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by spmonahan** [comment]
Hi @boraunlu, thanks for creating an issue! Can you please update the issue with the version of Fluent UI where you see this issue and provide an example [Codepen using our template](https://aka.ms/fluentpen)?
