### ISSUE TITLE
DatePicker: date range selection

### ISSUE THREAD

**Issue by volfpeter** [microsoft/fluentui#21183]
#### Describe the feature that you would like added

Make it possible to select a date range in `DatePicker`.

#### What component or utility would this be added to

`DatePicker`

**Comment by volfpeter** [comment]
Hi! Thanks for the feedback. I'm quite low on time unfortunately, but I'll keep this issue in mind.

**Comment by JustSlone** [comment]
tagging @microsoft/fluent-date-time who owns the DatePicker to weigh in about this possible contribution. 

note there is a linked PR open in Draft from @jasperwreed (thanks!)

**Comment by conniec218** [comment]
I like this idea, I think it would be a really helpful option for DatePicker consumers, and no conflicts or issues come to mind so far. Happy to take a closer look at the PR when it's ready for review :)

**Comment by jasperwreed** [comment]
Sorry I've been m.i.a for a little bit. I actually work at Microsoft now and my team created a date range picker so I'm going to check with them first to see if it's okay that I use some of the code we wrote there for this pr. In the meantime I've closed my previous draft pr. Feel free to tackle this as I don't know if I'll even get approval to use the code my team is using :)

**Comment by tudorpopams** [comment]
Hello @jasperwreed , do you still need support with this?

**Comment by jasperwreed** [comment]
Sorry @tudorpopams, I no longer have the bandwidth to continue working on this. If when my schedule clears up this is still open, then I'll take a proper stab at it.

**Comment by JustSlone** [comment]
We'll consider this feature for future work on Web Components and React v9 `DatePicker` but are not planning on adding this support to React v8 `DatePicker`.
