### ISSUE TITLE
Details List deselects all the selected items (in case of multiple selection) when the text part of the row is selected

### ISSUE THREAD

**Issue by manishsbh** [microsoft/fluentui#21185]
### Environment Information

- **Package version(s)**: Fluent UI React 8.49.0
- **Browser and OS versions**: 
 URL: https://fabricweb.z5.web.core.windows.net/oufr/7.76.2/#/examples/detailslist/basic
Browser: Edge
OS: Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/manishsbhoopalam/pen/wvrXVEV

#### Actual behavior:

I see that the already selected items in the list get deselected when an extra one is tried selecting by clicking on the text part of the row (rather than the check box)

#### Expected behavior:

Dont want the selected items getting deselected irrespective of where the click is happening

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
High

Products/sites affected: (if applicable)
Security and Compliance Portal of Microsoft

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations, the developers will review this issue and provide feedback once available. 

@TristanWatanabe - Here is the issue that was highlighted for shield by Sean.
