### ISSUE TITLE
PersonaCoin: Allow specifing properties for the icon which is rendered for small coin sizes

### ISSUE THREAD

**Issue by alex3683** [microsoft/fluentui#21188]
#### Describe the feature that you would like added

If the `Persona` or `PersonaCoin` size is set to `PersonaSize.size10` or smaller, an icon is rendered instead of the image. Currently this icon is hardcoded to be the "Contacts" icon (see for example [this code fragment](https://github.com/microsoft/fluentui/blob/dab45a2afe609709735b9b6e604a1af40d50e809/packages/react/src/components/Persona/PersonaCoin/PersonaCoin.base.tsx#L185-L186)). Since we are rendering mixed users, groups and rooms, it would be nice to change this icon depending on the resource type.

I know that this could be achieved by overwriting `onRenderPersonaCoin` but too much surrounding component code would need to be duplicated from the fluent ui sources. So something like `coinIconProps` would be nice.

#### What component or utility would this be added to

`PersonaCoin` component

#### Have you discussed this feature with our team, and if so, who

no

#### Additional context/screenshots

![grafik](https://user-images.githubusercontent.com/768322/148399179-e3314431-f7a2-4b25-a6cc-37ab45322b07.png)

For example in this screenshot the first item has the correct icon, the second should have the "Room" icon and the third should have the "Group" icon.

**Comment by gouttierre** [comment]
@alex3683 - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. In the interim, if you want to submit a PR for this request, please, do so and our development team will review it.
