### ISSUE TITLE
Masked DatePicker

### ISSUE THREAD

**Issue by conejo11** [microsoft/fluentui#21190]
#### Describe the feature that you would like added

Possibility to use masks when using an "allowTextInput" DatePicker.

#### What component or utility would this be added to

DatePicker

**Comment by gouttierre** [comment]
@conejo11 - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. In the meantime, if you have a proposal on this feature and would like to contribute towards it, please, share it and out team will review it.
