### ISSUE TITLE
cxe-coastal Jan 2022 Sprint

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#21197]
# cxe-coastal crew Jan 2022 sprint work

This provides a roll-up summary of the sprint work the cxe-coastal crew plans for Jan 2022.  It will be updated each Monday with status from the crew sync meeting and presented at the Tuesday LT meeting.  

NOTE: Moved to OneNote since issues have description editing collisions:  Closing this as an issue.

https://microsoft.sharepoint-df.com/teams/FluentUIInternal/_layouts/OneNote.aspx?id=%2Fteams%2FFluentUIInternal%2FShared%20Documents%2FGeneral%2FFluent%20UI%20Facts&wd=target%28cxe-coastal%20crew.one%7CF04241ED-3442-414F-B643-55086D0ACDAF%2FJanuary%2022%20Sprint%7CFE3BBFE8-DB1F-074F-AEB9-F8BDD592B68E%2F%29
onenote:https://microsoft.sharepoint-df.com/teams/FluentUIInternal/Shared%20Documents/General/Fluent%20UI%20Facts/cxe-coastal%20crew.one#January%2022%20Sprint&section-id={F04241ED-3442-414F-B643-55086D0ACDAF}&page-id={FE3BBFE8-DB1F-074F-AEB9-F8BDD592B68E}&end

**Comment by smhigley** [comment]
Jan sprint work for me:
- [ ] react-combobox working draft
    - [ ] implementation
    - [ ] spec
- [ ] A11y test passes for RC components
- [ ] Keep v7/v8 a11y bugs manageable

**Comment by ecraig12345** [comment]
- Help Tristan get started with build shield / write docs
- Hand off Input (also do a11y pass, which is almost done)
- Something related to testing: possibly working on fixing screener timeouts and investigating alternatives, testing dep upgrades, and/or conformance tests
