### ISSUE TITLE
[web-components] fluent-icon component

### ISSUE THREAD

**Issue by Eweol** [microsoft/fluentui#21232]
#### Describe the feature that you would like added

It would be realy great to have an fluent-icon component, which is related to the [FluentUI Icons Repo](https://github.com/microsoft/fluentui-system-icons) to have such icons directly in place.

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. However, If you come up with a solution in the interim and would like to submit a PR for this request, please, feel free to do so and our team will review it.
