### ISSUE TITLE
DetailsList & Selection: Allow Selection of itemless groups

### ISSUE THREAD

**Issue by JoaquimEsteves** [microsoft/fluentui#21234]
Currently it's possible to show an itemless group on a selectable `DetailsList` through the `showEmptyGroups` prop, we even get cute little checkbox. However, we're not allowed to select it! 

I have not for the life of me been able to get this to work through the orthodox `ISelection` api, and have had to resort to hot-wiring some hacky `onRender` functions.

#### What component or utility would this be added to

[Selection constructor](https://developer.microsoft.com/en-us/fluentui#/controls/web/references/selection)

[DetailsList](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist)

#### Use Case:

Consider the following scenario:

We're using the select feature to pass highlighted rows as a prop to some other `Delete` button.

Our rows are groupped, and it stands to reason that the same Delete button should also handle deletion of groups.

```jsx
function MyFakeList = () => {

    const selection = useRef(new Selection(selectionOptions));
    const onClickDelete = () => {
        Api.deleteThing(selection.current);
    }

    return (
        <>
            <button onClick={onClickDelete}>Delete Rows<button>
            <DetailsList {...detailProps} selection={selection}/>
        </>
    )
}
```

The `Selection` constructor already allows us to set an `canSelectItem` as well as our items; however the `DetailsList` seems to be disregarding my instructions.

The ideal solution for me would look something like so:

```typescript
interface Selectable<T> {
    canSelect?: boolean | (thing: T) => boolean
    onSelected?: (thing: T, currentSelection: Selection) => Selection
}

interface IGroup extends Selectable<IGroup> { /* etc  */}
interface IItem extends Selectable<IItem> { /* etc  */}
```

Allowing us to place arbitrary business Logic on each item/group of our details list.

```javascript

const item = [
    ...etc, 
    {
        ...etc2,
        canSelect: (thing) => complicatedBusinessLogic(thing, otherParams)
        onSelect: () => showModalOrWhatever()
    }
]
```

P.S. Sorry if I've not made myself clear; I took a look at how the other issues where written up but if I've not done enough due diligence don't be afraid to tell me off.

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. In the interim, if you wish to submit a PR for this request, please do so and our dev team will review it.
