### ISSUE TITLE
DetailsList width expands indefinitely when placed under a css grid section.

### ISSUE THREAD

**Issue by ishantsolanki-vakt** [microsoft/fluentui#21230]
### Environment Information

- **Package version(s)**: 8
- **Browser and OS versions**: MacOS Chrome browser
![Screenshot 2022-01-10 at 17 34 31](https://user-images.githubusercontent.com/67266548/148811931-8b5fe81a-b07b-4928-b6b3-faba380e10b6.png)
Also enable scrollbars to always show. This can be done in macOS under `Preferences > General`

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/ishantsolanki/pen/vYezMrW

#### Actual behavior:
When detailsList is contained within a width restricted div, it continues to expand its width indefinitely.
Using flexbox instead of css grid also leads to same issue.

#### Expected behaviour:
It should set the width to accommodate all the columns.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

**Comment by gouttierre** [comment]
I’ve added this to our backlog for contributors as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.
