### ISSUE TITLE
Add react-spinner Spec and Implementation

### ISSUE THREAD

**Issue by tomi-msft** [microsoft/fluentui#21241]
## Problem
Need to scaffold react-spinner package and add a `Spec.md` as well as initial implementation

## Appetite
4 wks

## Solution
- Add the react-spinner package to the repo(#20961)
- Add `Spinner` spec to the package
- Begin implementation of converged Spinner

## Risks (Rabbit holes)
None

## Out of scope (No-gos)
There will only be an indeterminate Spinner. Rather than creating a determinate variant of Spinner, `ProgressIndicator` should be converged

**Comment by jcusick93** [comment]
Thanks! Can you ping me when up on the Storybook :) ?
