### ISSUE TITLE
Placeholder text for picker

### ISSUE THREAD

**Issue by msdrewh** [microsoft/fluentui#21248]
#### Describe the feature that you would like added

It would be very helpful to have placeholder text like in this example.
https://docs.microsoft.com/en-us/graph/toolkit/components/people-picker#:~:text=placeholder,typing%20a%20name.

#### What component or utility would this be added to

Picker

#### Have you discussed this feature with our team, and if so, who

No I have not.

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
