### ISSUE TITLE
Link Component doesn't work when used as a custom ChoiceField

### ISSUE THREAD

**Issue by rockcs1992** [microsoft/fluentui#21252]
### Environment Information

- **Package version(s)**: 8.49.3
- **Browser and OS versions**: Chrome 96.0.4664.110, win11

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/rockcs/pen/eYGQzRy

#### Actual behavior:
When hovered over, the cursor stays normal at the link. When link is clicked, nothing happens

#### Expected behavior:
The cursor should turn to pointer when it hovers the link. And it should open "google.com" as specified in `href` prop when clicked.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking)

Products/sites affected: Azure Portal - Networking Manager Extension

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows as we’re currently focused on larger coherence work items.

@tomi-msft - Would you be able to confirm if this is a regression, or if this behavior is an issue? Thank you.

**Comment by rockcs1992** [comment]
Just a reminder for myself that adding one line of css could fix the issue. Will raise a PR for v7 later since that is the version our team uses
