### ISSUE TITLE
console.warn node_modules/@uifabric/utilities/lib-commonjs/warn/warn.js:16         Warning: You provided both 'value' and 'defaultValue' to a TextField. Form fields must be either controlled or uncontrolled (specify either the 'value' prop, or the 'defaultValue' prop, but not both). Decide between using a controlled or uncontrolled TextField and remove one of these props. More info: https://fb.me/react-controlled-components

### ISSUE THREAD

**Issue by akhil9tiet** [microsoft/fluentui#21253]
version in use:  "office-ui-fabric-react": "7.164.2"

On using <TextInput /> component with both the props, value and defaultValue, I am getting the warning, listed out in the header.
Also listed below:

```
 console.warn node_modules/@uifabric/utilities/lib-commonjs/warn/warn.js:16
 
      Warning: You provided both 'value' and 'defaultValue' to a TextField. Form fields must be either controlled or uncontrolled (specify either the 'value' prop, or the 'defaultValue' prop, but not both). Decide between using a controlled or uncontrolled TextField and remove one of these props. More info: https://fb.me/react-controlled-components
 
```

In my use case, I should have a default value for the component when is loading and has loaded, but also needs to have a value when the user inputs it. Hence I think, this warning should be removed from the component.

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [TextField ](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
