### ISSUE TITLE
Switching between Tabs hides search string in Pivot

### ISSUE THREAD

**Issue by DChefHarshil** [microsoft/fluentui#21254]
### Environment Information

- @fluentui/react: "^8.34.0"
- OS: Windows 10

### Please provide a reproduction of the bug in a codepen:

Code To Reproduce
```javascript
import * as React from 'react';
import { Label, Pivot, PivotItem, SearchBox } from '@fluentui/react';

export const PivotLargeExample = () => (
  <div>
    <Pivot aria-label="Large Link Size Pivot Example" linkSize="large">
      <PivotItem headerText="My Files">
        <SearchBox key='s1' placeholder='Search Files' />
      </PivotItem>
      <PivotItem headerText="Recent">
        <SearchBox key='s2' placeholder='Search Recent Files' />
        <Label>Pivot #2</Label>
      </PivotItem>
    </Pivot>
  </div>
);
```

#### Actual behavior:

Hides the search string while switching between tabs.

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [pivot examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot) (click “Export to CodePen”) or https://aka.ms/fluentpen.
