### ISSUE TITLE
`::before` pseudo element not rendered in DetailsRow for every 10th row

### ISSUE THREAD

**Issue by henninggross** [microsoft/fluentui#21258]
### Environment Information

- **Package version(s)**: 8.48.0
- **Browser and OS versions**: Any browser and OS

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/pen/gOGQROJ

#### Actual behavior:

When adding a `::before` pseudo element to each DetailsRow in the function passed to the `onRenderRow` prop of `DetailsList` this is not rendered for rows which keys dividable by 10 (e.g. 0, 10, 20, etc.).

<img width="833" alt="detailslist_pseudo_element" src="https://user-images.githubusercontent.com/57948036/149129307-a5aecdb2-7811-4b2e-af41-c3245e034e3c.png">

This happens due to the fact that `DetailsList` uses the `List` components which separates the items in chunks of 10's.

The first child receives the following styling:
```css
.ms-list-cell:first-child .root-xxx::before {
  display: none;
}
```

This happens here: https://github.com/microsoft/fluentui/blob/c4e88d96d13b1b1bcbf6db2bfd4d98d83ca84c07/packages/react/src/components/DetailsList/DetailsRow.styles.ts#L319

I am not sure why this is the case, but removing this rule would also eliminate this issue.

#### Expected behavior:

All rows to render the pseudo element.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

**Comment by gouttierre** [comment]
Thanks for filing this issue with us and for showing a willingness to contribute to this request. If you have the solution in mind and a PR ready, please share it with us and our dev team will review it.
