### ISSUE TITLE
Calendar month view broken on small screens

### ISSUE THREAD

**Issue by livthomas** [microsoft/fluentui#21255]
When `Calendar` component is in the "month picker" mode (`isDayPickerVisible={false}` and `isMonthPickerVisible={true}`), it is not rendered properly on very small screens. It looks like there is some breakpoint defined (around `420px`) and when the screen size is smaller, the component doesn't respect `isDayPickerVisible={false}` prop value.

I have run into this issue in my Electron app where I use `Calendar` component in a small modal window. But it probably affects any web app using this component when you open it on a mobile screen.

### Environment Information

- **Package version(s)**: 8.48.1
- **Browser and OS versions**: Electron 13.5.2, Linux 4.19.223-1-MANJARO

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/livthomas/pen/ZEXmLBJ

#### Actual behavior:

If the window is wide, `Calendar` component works as expected and shows only month view. But if you make the window small enough and refresh the page, the component renders day view instead of month view.

#### Expected behavior:

`Calendar` component in this setup should always render month view regardless of the window size.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by gouttierre** [comment]
Thanks for filing this issue with us and showing a willingness to contribute to this request.  We’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items. Would you mind sharing a PR for this request when it is ready, and our dev team will review it.

**Comment by livthomas** [comment]
I will try to find some time to go over the implementation of this component and see if I am able to fix this issue.
