### ISSUE TITLE
More friendly behavior when GroupedList header is too long.

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/fluentui#21275]
#### Describe the feature that you would like added
1. The header of `GroupedList` should show '...' when it is too long, which says "overflow" of "ms-GroupHeader-title" should be "hidden"
2. The icon should not shrink, which says "flexShrink" of "ms-GroupHeader-expand" should be 0

It makes more sense and the style has been set to 
```
white-space: nowrap;
text-overflow: ellipsis;
```
It appears that `overflow: "hidden"` is forgotten?

#### What component or utility would this be added to

packages/react/src/components/GroupedList/GroupHeader.styles.ts

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
