### ISSUE TITLE
Support tag component

### ISSUE THREAD

**Issue by Lijiaoa** [microsoft/fluentui#21284]
#### Describe the feature that you would like added

Why not support `tag` in the component? Look like this [tag](https://ant.design/components/tag-cn/)

#### What component or utility would this be added to
tag

#### Have you discussed this feature with our team, and if so, who
no

#### Additional context/screenshots
please refer the link on top

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. However, If you come up with a solution in the interim and would like to submit a PR for this request, please, feel free to do so and our team will review it.
