### ISSUE TITLE
FluentProvider apply to target without creating new div

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#21289]
#### Describe the feature that you would like added

While trying out FluentProvider, @MLoughry, on a partner team, found that the extra div rendered by FluentProvider caused layout issues. In this specific case, the FluentProvider needed to be applied at multiple render roots/portals. The added div interrupts styling between the parent and child.

The ask is to allow FluentProvider to be able to not create the extra div and instead be applied to a target div (maybe a singular child?).

#### What component or utility would this be added to

FluentProvider

#### Have you discussed this feature with our team, and if so, who

@miroslavstastny @layershifter

**Comment by miroslavstastny** [comment]
For the cases where the rendered DOM does not match the expectations, the solution is to compose the component in application code. For that reason every Fluent component is composed of a set of hooks.

### custom render function
One option is to implement your own render function - this is not a maintainable approach in the case of `FluentProvider` as it currently renders 4 different context providers:
https://github.com/microsoft/fluentui/blob/7cc28ed8320b00f42d91c63882f10316db2205c5/packages/react-provider/src/components/FluentProvider/renderFluentProvider.tsx#L13-L16
Application developers cannot track when this implementation is changed - any context is added or removed, order of contexts is changed...

### recompose the component
Another option is to recompose the component using the existing hooks and change the root slot.
Slots docs (not covering the compose pattern): https://aka.ms/fluentui-storybook/?path=/docs/concepts-developer-customizing-components-with-slots--page.

You can create your own provider component, call all the FluentProvider hooks, just update the root slot to render a custom component. That component would create a `React.Fragment`

There is a problem similar to the render function tweaks - the component consist of several hooks, application developer needs to know what is the complete set of hooks and their order.  The API is not final and is subject to change - we are working on this problem in #20607 (cc @levithomason ).

**Comment by miroslavstastny** [comment]
Example code sandbox: https://codesandbox.io/s/fluentprovider-without-a-div-xiimm.

When removing the `div` keep in mind there are other things the div solves which you now need to handle separately.
1. it sets initial styles for the application subtree (`font-family`, `foreground-color`, `background-color`.
2. it sets `dir` attribute to support RTL/LTR

**Comment by MLoughry** [comment]
> Example code sandbox: https://codesandbox.io/s/fluentprovider-without-a-div-xiimm.

That's still having to repeat a lot of the internal implementation of the FluentProvider code. An official implementation would be preferable, to avoid divergence if/when more contexts are added or other changes are made.

> When removing the div keep in mind there are other things the div solves which you now need to handle separately.

I am aware. OWA already handles that globally.

**Comment by thure** [comment]
Hey folks, [Fluent Blocks](https://github.com/OfficeDev/fluent-blocks) developer here. This was causing difficult issues for us too since v9 renders tooltips in their own provider in (what appears to be) a separate React root, which would cause the page to become unusable in certain situations for keyboard users.

Setting all providers‘ `div`s to `display: contents` appears to work so far. Tooltips get the right signals about space, CSS custom properties and direction work as usual, and adding/removing provider elements no longer affects the layout of the page. Hopefully this helps others who encounter the same issue.

**Comment by layershifter** [comment]
> Setting provider elements to `display: contents` appears to help in some situations. Folks having issues with the provider’s element occupying space may want to try applying that rule.

@thure can you please provide a repro case on CodeSandbox?

**Comment by thure** [comment]
I will look into doing that when I get a chance…

I think it was just easier to reason about handling multiple scrolling contexts under a single provider when there is no element *with layout* interceding between the root and our own components, though there are probably workarounds that keep the provider’s `block` display. In fairness I'm also not sure that applying `display: contents` won't cause problems in the future.

Ultimately I don't think this is a bug per-se, maybe more a matter of ergonomics or something worth documenting.

**Comment by miroslavstastny** [comment]
This has been open for a long time without any progress. Unfortunately there is no shared requirement, each partner has their special needs. For that reason (especially considering every application has just one instance of the provider) every application should implement their own solution.

**Comment by MLoughry** [comment]
> (especially considering every application has just one instance of the provider)

@miroslavstastny This is not true. In Outlook, we have several render roots (mostly, but not exclusively, for popups and modals and the like), and we have to apply the provider to each.

**Comment by khmakoto** [comment]
@MLoughry, do you want me to reopen this issue?
