### ISSUE TITLE
Input still uses browser focus outline in webkit

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#21296]
On any webkit-based browser (Mac Safari, any iOS browser), there's a browser-default focus outline rendered on the input via the `:-internal-direct-focus` selector, and I couldn't get it to go away (at least on Mac Safari) regardless of what styles I set on that selector. It seemed like either Safari wasn't respecting any styles set on that selector, or possibly make-styles wasn't applying them correctly?

![bad focus outline](https://user-images.githubusercontent.com/5864305/148459893-e0abbddf-16c0-4554-9796-771c80119629.png)

**Comment by spmonahan** [comment]
Fixed by #23197
