### ISSUE TITLE
onRenderLabel support for Slider component

### ISSUE THREAD

**Issue by srinidhiprabhu96** [microsoft/fluentui#21328]
#### Describe the feature that you would like added
An onRenderLabel prop needs to be supported by the Slider component. This has already been implemented for other components like Dropdown

#### What component or utility would this be added to

Slider

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Consumers of the Slider component may want to customize the rendering of the label. For example, we may want to show an info button with tooltip as part of the label:
![image](https://user-images.githubusercontent.com/16191789/150010088-8ab82870-92b4-4a2c-bae8-762126bed430.png)

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
