### ISSUE TITLE
Support logical margins of elements (margin-inline/block-start/end)

### ISSUE THREAD

**Issue by beatrizz** [microsoft/fluentui#21321]
#### Describe the feature that you would like added

I would like Fluent UI to support margin-inline-start, margin-inline-end, margin-block-start and margin-block-end the same way it supports padding-inline-start, padding-inline-end, padding-block-start and padding-block-end.

This would allow us to specify margins in a way that works well in left-to-right and right-to-left languages, allowing us to create better experiences for all of our users.

#### What component or utility would this be added to

I think this would go in IRawStyleBase so that we can use it in all the components that use that.

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

For example, we can now do this:
<Text styles={{ root: { paddingInlineStart: '12px' } }}>Hello</Text>

but not this, and we'd like to (only marginLeft and marginRight are supported):
<Text styles={{ root: { marginInlineStart: '12px' } }}>Hello</Text>

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. However, If you come up with a solution in the interim and would like to submit a PR for this request, please, feel free to do so and our team will review it.

**Comment by beatrizz** [comment]
Thanks @gouttierre ! That makes sense.

I've been having a look at what a PR would be like.

The PR that added the paddingInlineStart, etc. properties just adds them in packages/merge-styles/src/IRawStyleBase.ts and writes a changelog:
https://github.com/microsoft/fluentui/commit/50a43b5d1e13e6d507ab15477316bb5742fa6dbb

More recent PRs that also add properties add them in packages/merge-styles/src/IRawStyleBase.ts, packages/merge-styles/src/IRawStyleBase.ts and write a changelog:
https://github.com/microsoft/fluentui/commit/dedb9ae121ac9fb983e35877fe4dbb6512fd8235
https://github.com/microsoft/fluentui/commit/1959808480faf783fd56f51294f58467371538ad

Would that be enough to add new properties? Is what we write as e.g. "paddingInlineStart" automatically transformed to "padding-inline-start" and applied to components?

Thanks again!

**Comment by beatrizz** [comment]
@gouttierre I have opened a PR here with those changes: https://github.com/microsoft/fluentui/pull/21372

If something else is needed, it might be easier to discuss it in the PR.

Thanks!
