### ISSUE TITLE
Button - Primary/Default Button displays a square box around it

### ISSUE THREAD

**Issue by Suj5432** [microsoft/fluentui#21323]
- **Package version(s)**: office-ui-fabric-react: "^6.189.2",
- **Browser and OS versions**: iOS devices - iphone 12

#### Steps to Reproduce:
- import Primary/Default button from office-ui-fabric-react.
- Use the button component in the code.
- The button displayed in mobile devices (particularly iPhone) has a square border around it.
- The button is modified by adding custom css border-radius: 50%
- Issue is intermittent and only in some iphone devices (12, 7 plus)
#### Actual behavior:
Square box is visible around the button in iPhone device.

#### Expected behavior:
Square box should not be visible around the button in iPhone device.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by Manjunatha123** [comment]
We are also seeing the same issue where a square box is present around the round default button and its been affecting the production users.
Any remediation to this issue will be really helpful.

**Comment by gouttierre** [comment]
I’ve added this to our backlog for contributors as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.

**Comment by khmakoto** [comment]
Hi @Suj5432, v6 is unfortunately out of support now. Have you tried updating at least to v7 and seeing if you still find the same behavior there?
