### ISSUE TITLE
Setting the background color for 'main' is not changing the background color of panel when min-height >= 480px

### ISSUE THREAD

**Issue by jnch009** [microsoft/fluentui#21329]
### Environment Information

- **Package version(s)**: 8
- **Browser and OS versions**: Edge Windows 11

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/jonch009/pen/QWqPBMY

Ensure the height of the panel is 480px or greater otherwise you won't see the issue.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/13592249/150009632-c5f2f18b-75e0-441c-ad1e-9532fae5e73b.png)

#### Expected behavior:

Expecting the whole panel to remain the background color set in 'main'.
![image](https://user-images.githubusercontent.com/13592249/150010362-1ef283e6-bca7-4e83-8c89-dabf74994c8b.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by mbest** [comment]
duplicate of #20643?

**Comment by jnch009** [comment]
Yup, my bad. Will close.
