### ISSUE TITLE
Grouped DetailsList with custom columns blanking out after 250 items

### ISSUE THREAD

**Issue by shashwatjolly** [microsoft/fluentui#21343]
### Environment Information

- **Package version(s)**: latest (8.49.7)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/sjolly/pen/PoJgLmQ

#### Actual behavior:

I made a slight modification to add groups to the DetailsList with custom columns example in the [official demo website](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemcolumns).
Scrolling down in the DetailsList makes the whole list go blank at around the ~250 items mark.

#### Expected behavior:

Scrolling works normally in the DetailsList.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. I see the repro and how the scroll seems to jump as well, just after the 250 mark. To set expectations, the developers will review this issue once capacity allows as we’re currently focused on larger coherence work items. 

@tomi-msft - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by spmonahan** [comment]
Related: [#20825](https://github.com/microsoft/fluentui/issues/20825)

**Comment by spmonahan** [comment]
This is fixed by `GroupedListV2` (see above). Closing.
