### ISSUE TITLE
Slot architecture: Required slots can be set to null, which can crash the component

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#21358]
### Repro

The following code is currently allowed, but causes the component to crash trying to access null

```jsx
<Checkbox input={null} />
```

#### Actual behavior

Slots marked as `required: true` in the call to resolveShorthand can still be set to `null`, which results in the slot not being rendered. However, this fact isn't built into the return type from resolveShorthand, and the component code expects that the slot will be non-null.

Also, some slots are required for a component's basic functionality, and it should not be possible for a user to set it to null.

#### Expected behavior

We should only allow `null` as a shorthand value for slots that explicitly allow for it in their type.

**Comment by bsunderhus** [comment]
This issue is referring to the same problem listed here: https://github.com/microsoft/fluentui/issues/19558
