### ISSUE TITLE
TextField, Modal and NavLink screen reader issue

### ISSUE THREAD

**Issue by c-s-huang** [microsoft/fluentui#21370]
### Environment Information

- **Package version(s)**: FluentUI v7.1803
- **Browser and OS versions**: Chrome and Edge

### Describe the issue:

1. TextField type is number, when tab to the component, the screen reader will pronounce "value, minimum 0 and maximum 0", but it should pronounce value only.
2. TextField type is time, when tab to the component, the screen reader will pronounce "document Hour list, value", but it should pronounce value only
3. TextField will not pronounce suggestion item, but it should pronounce suggestion items for user.
4. When click enter for NavLink, it won't pronounce the selected state, like "value, selected".
5. When click tab, Modal component won't move to text content and pronounce the content.
#### Actual behavior:
1. Tab to TextField type is number, Screen reader will pronounce "value, minimum 0 and maximum 0".
2. Tab to TextField type is time, Screen reader will pronounce "document Hour list, value".
3. Tab to TextField component, screen reader will pronounce "suggestion available".
4. Click enter for NavLink component, screen reader will pronounce "value" only.
5. Open Modal component and tab won't go to Modal content.

#### Expected behavior:
1. Screen reader should pronounce "value" only.
2. Screen reader should pronounce "value" only.
3. Screen reader should pronounce all suggestion items by using tab.
4. Screen reader should pronounce the selected item state.
5. Should be ok to tab to Modal content and screen reader can pronounce the content.

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [textfield examples](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/textfield) (click “Export to CodePen”) or https://aka.ms/fluentpen.
