### ISSUE TITLE
Add Dropdown to Searchbox

### ISSUE THREAD

**Issue by lnhubbell** [microsoft/fluentui#21397]
#### Describe the feature that you would like added

Dropdown list added to the search bar component, similar to the Combobox or dropdown component.

#### What component or utility would this be added to

SearchBox

#### Have you discussed this feature with our team, and if so, who

Nope

#### Additional context/screenshots
Many search experiences want this sort of dropdown/autocomplete feature that shows potential results as you search. This can be built using a dropdown or Combobox, but that loses some of the nice features included in the Searchbox, such as the search/cancel events, search icons, etc.

![image](https://user-images.githubusercontent.com/7283721/150845931-015d92f1-9a26-4779-b9d3-c55dd6a490e3.png)

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. However, if you come up with a solution for this feature request and would like to contribute towards it, please, share your findings and our team will gladly review the PR.

**Comment by praveen5959** [comment]
I think this was raised as feature request earlier also. 

https://github.com/microsoft/fluentui/issues/16566

But no idea whether it was added or not.
