### ISSUE TITLE
Callout text isn't read by NVDA when invoked with a keyboard

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#21413]
Turn on NVDA
Navigate to the CalloutPage -> Non-focusable callout with accessible text example.
Invoke the callout with a keyboard.

Notice that the callout text isn't read aloud.

This scenario does seem to work with the mouse, and also with Windows Narrator.

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [callout examples](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/callout) (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by mltejera** [comment]
Curious - why do I need to add a code pen example if it's reproducible on the demo site?
