### ISSUE TITLE
Pagination missing for detailed list 

### ISSUE THREAD

**Issue by Misbah-Mushtaq** [microsoft/fluentui#21427]
Pagination is missing in Fluent UI

**Comment by Lijiaoa** [comment]
@gouttierre  Although I still think pagination is very important component with table. -- from UX developer

**Comment by Misbah-Mushtaq** [comment]
I agree with you Lijiaoa
Pagination component must be there with data table

**Comment by JustSlone** [comment]
We have a pagination control available in our experiments package. 
https://fluentuipr.z22.web.core.windows.net/heads/master/react-experiments/demo/index.html#/examples/pagination

@Misbah-Mushtaq can you try this out and see if it works for you? If it works well and meets the need here we can look at promoting it to a fully supported component.

**Comment by spmonahan** [comment]
I put together a demo integrating `DetailsList` and `Pagination` a few months back.

[Codesandbox Link](https://codesandbox.io/s/detailslist-pagination-2l5r9c).

The biggest issue I saw with `Pagination` is that localization will need some work. This may also lead to some accessibility work depending on if/how localization changes the rendered output of `Pagination`. That said, it does work seem to work well with `DetailsList` in my demo application and it was fairly simple to set up.

**Comment by Misbah-Mushtaq** [comment]
Hi JustinI have reviewed the pagination. I think this would do the magic in detaillist. Sent from my iPhoneOn 26-Sep-2022, at 10:01 PM, Sean Monahan ***@***.***> wrote:﻿
I put together a demo integrating DetailsList and Pagination a few months back.
Codesandbox Link.
The biggest issue I saw with Pagination is that localization will need some work. This may also lead to some accessibility work depending on if/how localization changes the rendered output of Pagination. That said, it does work seem to work well with DetailsList in my demo application and it was fairly simple to set up.

**Comment by gouttierre** [comment]
https://github.com/microsoft/fluentui/issues/21427#issuecomment-1258397295

I am happy to read that it worked well with DetailsList in your demo application. If you have any further issues with accessibility part for the localization changes in the rendered output, please, let us know by submitting a new issue and the team will review it. Until then I am closing this issue.
