### ISSUE TITLE
Converged Popover: nested popover is not updating position on scrolling container

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/fluentui#21457]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
codesandbox: https://codesandbox.io/s/sad-haze-mzy63?file=/example.tsx

#### Actual behavior:
When scrolling the contaner (green box), the nested popover element is not updating its position to follow trigger:
<img width="314" alt="Screenshot 2022-01-26 at 16 35 46" src="https://user-images.githubusercontent.com/28751745/151195159-e5392a48-9b53-488f-813d-baa194a670a9.png">

This happens because the trigger is rendered outside of the scroll container, so popperjs is not able to identify the scroll container as the trigger's scrollable parent: https://github.com/floating-ui/floating-ui/issues/1267

#### Expected behavior:

In @fluentui/react-northstar, we had the similar issue. It was solved by adding a prop to dismiss popover on scrolling the container element (PR #21453 ). 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) no

Requested priority: (Blocking, High, Normal, Low) low

Products/sites affected: (if applicable)

**Comment by JustSlone** [comment]
We should fix this issue; I would love a better solution than a prop to dismiss on scrolling if we have that option. 
Moving over to the new unified board and assigning to @microsoft/teams-prg

**Comment by layershifter** [comment]
keep open
