### ISSUE TITLE
DetailsList header checkbox visibility not working correctly

### ISSUE THREAD

**Issue by 07JP27** [microsoft/fluentui#21451]
### Environment Information

- **Package version(s)**: 8.49.7
- **Browser and OS versions**: Chrome 97.0.4692.99

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/07JP27/pen/yLPLxpR

#### Actual behavior:
When set folwing property in the code of codepen ```detailsHeaderProps.checkboxVisibility = CheckboxVisibility.hidden```, 
the behavior be same as when set ```detailsHeaderProps.checkboxVisibility = CheckboxVisibility.onHover```  (check box does not hidden)

When set ```detailsHeaderProps.checkboxVisibility = CheckboxVisibility.always``` working correctoly (check box always displayed)

#### Expected behavior:
When set ```detailsHeaderProps.checkboxVisibility = CheckboxVisibility.hidden``` the check box in header should be hidden.

### Priorities and help requested:

Are you willing to submit a PR to fix?: No

Requested priority: Low

Products/sites affected: N/A

**Comment by 07JP27** [comment]
I avoid this problem using CSS like below.
```
'.ms-DetailsHeader-cellIsCheck':{
    visibility: 'hidden'
}
```

**Comment by smhigley** [comment]
@07JP27 the `checkboxVisibility` prop is a property on the root `<DetailsList>` component, and does not exist on the `<DetailsHeader>` props.

If you set it like this, it should work -- I tested it in a codepen, and it worked for me: https://codepen.io/smhigley/pen/LYQyoKV/1a19c1db3324f7117be5510186d4399c

```jsx
<DetailsList
    items={items}
    columns={this._columns}
    checkboxVisibility={CheckboxVisibility.hidden}
/>
```

**Comment by 07JP27** [comment]
@smhigley 
Thank you for your comments.
Your sample certainly works well, but it is not the scenario I am hoping to achieve.

The behavior I want to achieve is to hide only the "Select All" checkbox in the column headers when each row is checkable in CheckboxVisibility.visible, not to hide the checkboxes in all rows.
