### ISSUE TITLE
Menu/Popover support Ref for target (possibly through virtual element helper)

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#21463]
#### Problem

- Menu positioning.target, currently accepts only an HTMLElement or PopperVirtualElement
- Many instances of partner usage of v8 menus leverage Ref for target
- The most common case of providing a target is likely Ref
- The current API restriction was deliberate to avoid issues caused when the referenced element changes. Refs don't provide notification of changes like useState, there are some rendering sequencing issues, and some alternatives cause double renders.

#### Proposed solution

- Provide some kind of helper function or hook that allows the caller to use a Ref on the target, but then pass the HTMLElement or PopperVirtualElement to the positioning.target.

This avoids adding Ref to the target type.  This helps prevent the implication that the Popover can support all the cases where the referenced element changes, but allows callers wanting to use Refs to do so.  Having to call the additional function or hook makes it clear that this is an adapter and if the referenced element is changed, the Popover component may not respond.

**Comment by MLoughry** [comment]
> Proposed solution
> * Provide some kind of helper function or hook that allows the caller to use a Ref on the target, but then pass the HTMLElement or PopperVirtualElement to the positioning.target.

Again, I don't believe that pushing that work onto the app developer is the right thing to do, and it runs into the exact same concerns with regards to either (1) double-rendering because you're using React state as a `ref`, or (2) not detecting when the ref value changes.

My assertion is that ref values changing is *an extreme corner case* and the API should not be restricted so much on this basis alone.

**Comment by bsunderhus** [comment]
We'll not be supporting `ref` as a value to target internally in FluentUI, but here's a link to a shim version of Menu that behaves as expected, supporting target as ref: https://codesandbox.io/s/menu-shim-2ect0h, if required a helper hook can be elaborated out of this element example.

**Comment by MLoughry** [comment]
Can you please give some justification for requiring every developer to implement their own shim to use refs, which are standard for v8 and for passing around elements in React?

**Comment by bsunderhus** [comment]
Doing a quick canvas of other popular UI libraries in the open:

* [Popover - Chakra UI (chakra-ui.com)](https://chakra-ui.com/docs/overlay/popover#popover-props)
* [Popover — Radix UI (radix-ui.com)](https://www.radix-ui.com/docs/primitives/components/popover)
* [Salesforce Lightning Design System | React | Popovers](https://react.lightningdesignsystem.com/components/popovers/)
* [Popover - Ant Design](https://ant.design/components/popover/#API)[Evergreen Popover Documentation (segment.com)](https://evergreen.segment.com/components/popover)
* [React Popover component - MUI](https://mui.com/components/popover/)

It's hard to be able to say that ref props are common practice in React community. The argument of v8 supporting it is sound but it doesn't mean is the way we want to go forward with v9. Besides that there are also the arguments already presented of dealing with changing refs, which might be an edge case, but still is a case.

@MLoughry, let's pair on this if needed, but for now I'll close this issue as it's not a priority in the board as the decision has already been agreed upon with parties.
