### ISSUE TITLE
v9 MenuButton does not support ref, but should

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#21484]
### Environment Information

- **Package version(s)**: main (2022-01-27)
- **Browser and OS versions**: NA

### Problem

When in a MenuTrigger, the MenuButton disallows having a ref prop.

```ts
// This type mimics the interface found in MenuTrigger.types.ts to allow MenuButton and Menu to play correctly with each
// other without having to tightly couple them.
// https://github.com/microsoft/fluentui/blob/master/packages/react-menu/src/components/MenuTrigger/MenuTrigger.types.ts
type MenuTriggerChildProps = Pick<
  React.HTMLAttributes<HTMLElement>,
  'onClick' | 'onMouseEnter' | 'onMouseLeave' | 'onContextMenu' | 'onKeyDown' | 'aria-haspopup' | 'aria-expanded' | 'id'
> & {
  ref?: React.Ref<never>;
};
```

However, a ref is needed for callers wanting to use the menu button as a custom positioning target for a popup (OWA partner)

#### Proposed solution

Add support for ref on menu button (remove the restriction) or determine/explain why the ref should not be allowed and provide a workaround.

**Comment by layershifter** [comment]
I checked this with `react-components@beta.5` and it works, but complains on typings:

![image](https://user-images.githubusercontent.com/14183168/151517975-6695429c-95ca-4711-908b-f160fe88fab3.png)

(🛠 this should be fixed for sure)

Latest nightly has the same issue. So the component supports `ref`, it's not _possible_ to satisfy typings.

- `beta.5` - https://codesandbox.io/s/hopeful-pond-26p9z?file=/example.tsx
- `0.0.0-nightlye0b8e1fa6920220128.1` https://codesandbox.io/s/hopeful-pond-26p9z?file=/example.tsx

**Comment by ling1726** [comment]
`MenuTrigger` types  were updated to not support `ref` in #19805. @khmakoto  do you have any context behind that change ?
