### ISSUE TITLE
fluent-select has a fixed width that can't be altered

### ISSUE THREAD

**Issue by matt-goldman** [microsoft/fluentui#21496]
### Environment Information

- **Package version(s)**: Latest (using https://unpkg.com/@fluentui/web-components)
- **Browser and OS versions**: Windows 10 19042.1466, Edge Version 97.0.1072.76 (but also using inside Outlook in an Office add-in)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/mattgoldman/pen/LYOpegv

#### Actual behavior:

The <fluent-select> element always renders at a fixed width, irrespective of any width restrictions placed on either itself or its parent.

#### Expected behavior:

The <fluent-select> element should respect width restrictions.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, but I wouldn't know where to start

Requested priority: Blocking for me, but not sure what that priority is for you.

Products/sites affected: None available yet

**Comment by paulgildea** [comment]
@chrisdholt - Not sure on the new process on handling web-component related issues - will follow up with you.

**Comment by chrisdholt** [comment]
> @chrisdholt - Not sure on the new process on handling web-component related issues - will follow up with you.

As soon as we can find out about it the quicker we can get back to folks, thanks @paulgildea!

@matt-goldman just getting this assigned; happy to look into it and sorry for the delay! Thank you for the repro link!

**Comment by matt-goldman** [comment]
@chrisdholt will this not be addressed?

**Comment by chrisdholt** [comment]
> @chrisdholt will this not be addressed?

A few things got auto-closed and I'm just getting back today from being out with a medical issue. I'll revisit and see if we can pri these quickly and accordingly. Thanks @matt-goldman for the ping
