### ISSUE TITLE
Aria label is not defined for load more icon

### ISSUE THREAD

**Issue by nadavWeisler** [microsoft/fluentui#21497]
### Environment Information

- **Package version(s)**: 8.36.5
- **Browser and OS versions**: 20H2 (OS Build 19042.928) Edge Version 96.0.1054.43 (Official build) (64-bit)

### Describe the issue:
Load more Icon does not have aria (3 dos

<img width="966" alt="MAS1 3 1-Sitesnsensors-More icon-Aria label is not defined" src="https://user-images.githubusercontent.com/32937058/151759135-604ae40f-fefe-4ce6-9b42-6338236b10eb.png">

**Comment by paulgildea** [comment]
@nadavWeisler Thanks for the feedback. Could you provide a more simplified repo of your issue? 

@andrefcdias - Is this something that the author needs to provide or is this a real issue?

**Comment by nadavWeisler** [comment]
Hey what the meaning of simplified repo of issue?

**Comment by andrefcdias** [comment]
Hey @nadavWeisler, in order for us to be able to better validate the issue, we'll need you to provide us with a reproduction of the problem.
To do so, go to https://aka.ms/fluentpen for a starter codepen and add in code to replicate the issue you're observing.
You can also use the "Export to Codepen" feature for the various components in our documentation site.
Finally, see http://codepen.io/dzearing/pens/public/?grid_type=list for a variety of examples
