### ISSUE TITLE
Menu's hidden on mount have incorrect previously active element set on menu opening

### ISSUE THREAD

**Issue by makopch-ms** [microsoft/fluentui#21493]
### Environment Information

- **Package version(s)**: Fluent v8 -- Likely after https://github.com/microsoft/fluentui/pull/19730
- **Browser and OS versions**: All

#### Actual behavior:
1. Open a menu rendered in the background via keyboard
2. Hit Esc
Focus doesn't go to anchor element / button because previous focused element was the first item in the menu which is now hidden.

When opening a menu on a button with persistMenu and renderPersistedMenuHiddenOnMount set to true, the useLayoutEffect (https://github.com/microsoft/fluentui/blob/22964c2011b81b39c977075bc019b7a232cd988a/packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx#L264) runs twice.  The first time it sets the previousActiveElement to the button/anchor, the second time to the first element in the menu.

The useLayoutEffect is being triggered a second time because `targetWindow.document.activeElement` is changing.  hidden doesn't change.

When a menu is not rendered Hidden on Mount, the useLayoutEffect is called twice, first because hidden is undefined, and a second time because hidden is false.  Both times `targetWindow.document.activeElement` is the anchor.

#### Expected behavior:

Focus goes back to the anchor element correctly.

### Purposed Fix
Change the conditions on which useLayoutEffect should be updated to just `[hidden, tryFocusPreviousActiveElement]`.  Removing `targetWindow.document.activeElement`

Both types of menus still seem to react correctly.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Office Online

**Comment by gouttierre** [comment]
@makopch-ms - Thanks filing this issue with us.  We’re currently focused on larger coherence work items but I see you are willing to contribute a PR for the fix which is great to see. When you have your proposed solution ready , please let us know and the team will review it immediately.

**Comment by micahgodbolt** [comment]
I tried to create a repro but was unable. Is there something in this pen that i'm missing? https://codepen.io/micahgodbolt/pen/popwBqG?editors=0010

**Comment by SavannahBourgeois** [comment]
Sorry this took so long for a response, this bug has been passed around a bit on our side but some of our partner teams are experiencing this and it is causing accessibility bugs now.

So I'm not sure how easy it would be to repro in codepen. Our issue is that with shadow rendered menus, we render the menus twice. We pass in a prop to the contextualMenu called isShadowRendered that is tied to the state in the anchor button. This allows us to populate and update our menus on mount by updating the state and having our menus rerender. It seems like with this method, we call render twice and each time "hidden" is false which means we set previousActiveElement.current. The first time we properly set it to the anchor, the second time, it seems like we set it to the first item in the menu.

Our ask is, can you update the code to only set previousActiveElement.current once? That will ensure the correct item gets focus on menu close for us. 

@makopch-ms @micahgodbolt

**Comment by sysofwan** [comment]
+1 our feature is having the same issue after updating to FluentUI v8. Here is a codepen: https://codepen.io/sysofwan/pen/vYjGzgN

It occurs if there is something focusable inside contextual menu, and the menu got rerendered (for example due to state change in parent component).
