### ISSUE TITLE
Chcekbox: change type and example of custom Label

### ISSUE THREAD

**Issue by mattrick** [microsoft/fluentui#21504]
Using onRenderLabel only to display Link breaks styling, Chcekbox is rendered differently, even after adding ms-Checkbox-text class. Altough it's, from what I've seen, perfectly fine to assign component to a label prop. See the comparison on attached fiddle.

Fiddle: https://jsfiddle.net/98kpnmod/

**Comment by paulgildea** [comment]
@mattrick Thanks for the issue, which parts of the `Checkbox` is the styling breaking?
