### ISSUE TITLE
v9 Menu: investigate VoiceOver bugs

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#21510]
Menu has some behavior bugs with VoiceOver on macOS and iOS. We need to investigate a bit more to determine:
1. Is there anything reasonable we can change that would fix the VO experience without degrading the experience for other users, or setting ourselves up with brittle code
2. If it's a VoiceOver bug, we should make a repro & file a bug
3. Document the issue + any existing workarounds

Bugs to investigate:
- VoiceOver (both iOS and macOS) is drawing odd bounding boxes around menuitems, causing scroll issues
- VO on macOS doesn't always announce checked semantics and checked changes for menuitemcheckbox or radio as expected. Lower severity b/c the check icon + press action is announced. Compare to APG Editor Menubar example for expected checked announcement. Also, weirdly, it worked for me after I first interacted with the APG example, then came back to Fluent and tried again while the menu was still open. VO is weird.
- VO on macOS is buggy when toggling a checked menuitem twice. First time works OK, leaving & returning to the menuitem works OK. But toggling the same menuitem checkbox or radio twice in succession closes the menu or doesn't otherwise work
- VO on macOS is not announcing menu information when opened. If you look at the speech viewer, you can see the text flash, then immediately get overridden by the menuitem announcement (compare to APG example for expected behavior).

**Comment by jialinyang-ms** [comment]
Any update on this? Our app mobile experience is currently blocked by the **odd bounding boxes around menuitems**. The onClick event added to the MenuItem component won't even be triggered on a mobile browser if it is from voiceover double click: 
![IMG_2164](https://user-images.githubusercontent.com/116394446/221284442-ca602651-e100-4877-aeb5-8c7ede5a5b5d.PNG)
