### ISSUE TITLE
Details list example 

### ISSUE THREAD

**Issue by kkazala** [microsoft/fluentui#21516]
DetailsList, when using custom `onRenderRow`, loses focus on selected item if a user clicks outside of the list: [DetailsList - Custom Item Rows](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemrows).
This will not be fixed, as stated in this [issue](https://github.com/microsoft/fluentui/issues/10094#issuecomment-585449205), but we have a [workaround](https://github.com/microsoft/fluentui/issues/10094#issuecomment-585448306) which works.

Could we add a new [example](https://codepen.io/kkazala/pen/OJxYyJx), for a list with custom row rendering that keeps the state of the selected items? This would be awesome.

**Comment by paulgildea** [comment]
@kkazala Thanks for the issue. Would you be interested in contributing the sample to the documentation?

**Comment by kkazala** [comment]
@paulgildea sure, happily. How shall we proceed?
