### ISSUE TITLE
Auto height of PivotItem 

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft/fluentui#21535]
#### Describe the feature that you would like added

Since I can't predict the height needed for PivotItem in code because the number items showing may change at run time. 
Could you mage a "stretch" property that will figure out the height at run time?

#### What component or utility would this be added to

Pivot

#### Have you discussed this feature with our team, and if so, who

Not yet

#### Additional context/screenshots

Thank you for great tool

**Comment by micahgodbolt** [comment]
Can you give an example of what you're trying to accomplish? Screenshot of what isn't working, or a codepen example of your scenario?

**Comment by Ofer-Gal** [comment]
In situation like so:
```
<Pivot onLinkClick={onTabChange} linkFormat={PivotLinkFormat.tabs} linkSize={PivotLinkSize.large}  >
                        <PivotItem headerText="DPC Request" key="request" headerButtonProps={headerProps} >
                            <div>
                                <JobRequestTab RefreshRequest={RefreshRequest} handleJobChange={handleJobChange}  />
                            </div>
                        </PivotItem>
 //more items
</Pivot>
```
The child component "<JobRequestTab " will have different height in different scenarios.  
How can I make sure it it will always show the correct height without scroll bars or empty space at the bottom?
Thanks

**Comment by micahgodbolt** [comment]
Pivot only renders the PivotItem currently selected, which means the Pivot will only be the height of the currently selected item (which is the intended behavior). You might need to wrap the pivot in some HOC, loop through all the possible pivots to find the tallest pivot, and then set the parent to that height before rendering the control. The pivot itself will not provide this functionality.

**Comment by micahgodbolt** [comment]
This behavior is something we should consider for our upcoming v9 pivot @GeoffCox 

The option to render the pivot to fit the tallest item.

**Comment by Ofer-Gal** [comment]
I would love this option. I think many would too.
Thank you
