### ISSUE TITLE
Narrator announcing as "Asterisks" for required field.

### ISSUE THREAD

**Issue by zx3689** [microsoft/fluentui#21538]
Build Details:
OS : Windows 11

OS : Version Dev (OS Build 22509.1011)
Edge Dev : Version 98.0.1100.3 (Official build) dev (64-bit)
URL: https://config.office.com 

Pre-requisite:
Turn on Narrator(Ctrl + Win + Enter)

Repro steps:

Open 'https://config.office.com' in Edge dev with valid credentials.
Sign in with  admin@ocastester.onmicrosoft.com/Hello123 
Navigate to 'Left Navigation Pane', select "Customization" and expand it.
Navigate to "Policy Management" and invoke it .
Navigate to "Name" edit field and listen to the narrator announcement.

same issue:
Same issue is observed in customization -> Device Configuration -> select Create -> Navigate to "Product and Release" -> Expand it -> Navigate to "Which architecture you want to deploy" radio buttons and listen to the narrator announcement 

Actual Result:
Narrator is announcing as "Name, asterisk, edit, required, has popup".

Same issue
Narrator is announcing as " Which architecture you want to deploy, asterisk, Deploy product in 32 bit option selected, radio button, selected, Required, 1 of 2"

Expected Result:
Narrator should announce as "Name, edit, required, has popup".

Same issue
Narrator should announce as "Which architecture you want to deploy, Deploy product in 32 bit option selected, radio button, selected, Required, 1 of 2"

**Comment by micahgodbolt** [comment]
Please provide repro steps for Fluent UI control in question. This isn't an issue queue for any office apps/pages.
