### ISSUE TITLE
Uncalled `expect(name).not.toBeFalsy;` in test code

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/fluentui#21599]
https://github.com/microsoft/fluentui/blob/dab45a2afe609709735b9b6e604a1af40d50e809/packages/utilities/src/object.test.ts#L49

We're wondering if this was intentional or not - it's a bit odd since `name` definitely *is* falsy in this codepath, so while it looks like a simple mistaken uncalled function, this function call appears that it would throw. OTOH maybe that's why the error wasn't detected?

**Comment by RyanCavanaugh** [comment]
ref. https://github.com/microsoft/TypeScript/pull/47719

**Comment by spmonahan** [comment]
Disclaimer: this is the first time I've looked at this particular code :)

I read this as a "fail fast" path in the test and I'm not sure this is strictly necessary so I'll investigate it some more. 

However, I do feel confident in saying that the line in question should be `expect(name).not.toBeFalsy();` (i.e., `toBeFalsy()` needs to be called).

**Comment by spmonahan** [comment]
After looking some more I've opened this PR: #22533
