### ISSUE TITLE
Fluent UI react web control <Dropdown> doesn't handle the 1DS telemetry tagging (data-bi-id and data-bi-name)

### ISSUE THREAD

**Issue by bpuram** [microsoft/fluentui#21600]
We're using React web controls using fluent ui ("@fluentui/react": "^7.173.0") and trying to implement 1DS SDK for telemetry from our web application.

**Problem**
I'm trying to Tag the `<Dropdown>` (namely with 'data-bi-id'='id1' and 'data-bi-name'='name1' attributes on Pivot-Item) from the Dropdown component, hoping to send the attribute values ( i.e, 'id1' and 'name1') within the content blob of 'click' events (using 1DS default settings) when the user clicks on the Dropdown options. But the 1DS library isn't capturing the dropdown click events even though I set the library settings to capture them. The reason for the Dropdown component not being capturing the click events is that the react Dropdown component within Fluent UI today isn't rendered as a native `<select>` html element under-the-hood.

**Expected Behaviour**
The Dropdown component should accept/assign the data-bi-id/data-bi-name attributes passed in and render it as a native html `<select>` element so as the 1DS sdk can read it for pageActions.

NOTE: other react components say `<Checkbox>`, `<Link>`, `<PrimaryButton>`, `<HashLink>` do support the passed in tagging attributes.

[fluentui-react] (https://stackoverflow.com/questions/tagged/fluentui-react).

**Comment by gouttierre** [comment]
Thank you for filing this item with us. I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. However, if you manage to come up with a proposal for the request, please share your PR with us and we will review it.

**Comment by tudorpopams** [comment]
[BacklogReview] We need to understand if this is a bug or a feature and if it's supported in v9.

**Comment by gouttierre** [comment]
Adding issue to investigation queue for follow-up if this is a bug or a feature and if it's supported in v9.

**Comment by miroslavstastny** [comment]
Fluent UI `Dropdown` always renders as a set of `div`s and `button`s.
In addition to that, Fluent UI v9 adds `Select` component which renders a native `<select>` element. That should solve the original issue.
`Select` spec: https://github.com/microsoft/fluentui/blob/0d4794d3924d648c788993e087a48dd45fe10a1b/packages/react-components/react-select/Spec.md.
fyi @smhigley
