### ISSUE TITLE
Searchbox delete button has no tooltip

### ISSUE THREAD

**Issue by huangzumeihan** [microsoft/fluentui#21619]
URL: https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox

Actual result:
Searchbox delete button has no tooltip

Expected result:
The search box delete button should have a tooltip

![image](https://user-images.githubusercontent.com/31198399/152713771-ed61cbbd-2d40-46a4-9ebc-c00c6a724aaf.png)

**Comment by smhigley** [comment]
We intentionally didn't include a tooltip on the clear button for accessibility reasons, and general usability. The "x" symbol is one of the few icons that has wide enough recognition that we judged it doesn't need a separate text label. This also matches native browser implementations as well (see Edge's clear button on search inputs).

If you think the button should have a tooltip, it would need to be a design/feature request. Could you clarify why you think a tooltip should exist on this button?
