### ISSUE TITLE
In Aquatic theme, 'Tick mark' of the selected checkbox is not clearly visible.

### ISSUE THREAD

**Issue by nadavWeisler** [microsoft/fluentui#21622]
### Environment Information

OS: Windows 11 Enterprise 21H2 (OS build: 22000.258)
Browser: Edge(Chromium) Version 98.0.1093.6 (Official build) dev (64-bit)

![image](https://user-images.githubusercontent.com/32937058/152751047-ef4baf27-6e85-4031-bc32-bc4f0e8a8766.png)

#### Actual behavior:

In Aquatic theme, 'Tick mark' of the selected checkbox is not clearly visible.

#### Expected behavior:

In Aquatic theme, 'Tick mark' of the selected checkbox must be clearly visible.

**Comment by micahgodbolt** [comment]
Which package are you having issue with? The current v8 checkboxes are working fine in aquatic.

![image](https://user-images.githubusercontent.com/1434956/163036184-718809d9-fb5e-4e3d-af46-2d9752354a9d.png)
