### ISSUE TITLE
Focus is not visible in button in High Contrast 'Aquatic' and 'Desert' mode.

### ISSUE THREAD

**Issue by nadavWeisler** [microsoft/fluentui#21621]
### Environment Information

OS Version: Version (10.0.22000 Chromium Build 22000)
Browser: Microsoft Edge Chromium Version 98.0.1100.3 (Official build) dev (64-bit)

#### Actual behavior:

  In high contrast 'Aquatic and 'Desert' modes the focus is not visible on the selected Control button. In Normal mode, button is highlighted when focus lands on it, But in High contrast themes, 'Add filter' button is not highlighted.

#### Expected behavior:

In high contrast 'Aquatic and 'Desert' modes the focus should be highlighted on the selected Control button.

![image](https://user-images.githubusercontent.com/32937058/152750115-08fed7cd-0d25-4d4e-adf4-efc5eede9450.png)

**Comment by ameliabateman** [comment]
Adding a +1 here. I'm seeing this on an Icon which has tabIndex of 0 as well as a more normal IconButton. Aquatic and Desert modes in particular are not showing a focus style.

**Comment by gouttierre** [comment]
@nadavWeisler - Thanks for filing this issue with us. But could you please share what version of Fluentui you are using? Are you still having the same problem using the latest version?
