### ISSUE TITLE
Stylesheet._classNameToArgs can cause memory leaks

### ISSUE THREAD

**Issue by jspurlin** [microsoft/fluentui#21630]
### Environment Information

- **Package version(s)**: @fluentui/merge-styles 8.2.3

### Describe the issue:
When the page is being unloadded, window.__stylesheet__._classNameToArgs is still referenced causing a memory leak.

#### Actual behavior:
(Note, this is when fluent is unloaded inside of an electron webView)
![image](https://user-images.githubusercontent.com/7033561/152842699-5874c8cb-74de-4b34-a583-bf4541bd5f63.png)

#### Expected behavior:
That the object be dispose of properly

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High (this needs to be investigated)

Products/sites affected: Office Online

**Comment by dzearing** [comment]
Can you explain what you're doing to unload? Are you navigating to `about:blank`? What kind of conditions are we talking about that create a leak?

Usually leaks happen when you remove a child page, but something still holds on to the child window reference. So more details needed here.
