### ISSUE TITLE
[Icon Tool] Font and Font Family name not updating in exported font file

### ISSUE THREAD

**Issue by rarattay** [microsoft/fluentui#21634]
### Environment Information

- **Package version(s)**: Icon tool app version 2.124.0
- **Browser and OS versions**: Both Safari on Mac OS & Edge on Win 10 OS

### Describe the issue:

The user defined font and font family name text fields at https://fabricicons.azurewebsites.net are not working. The exported .tff and .woff files font and font-family name are always the default values. 

Problematic Font & Font Family Text Fields:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/60023064/152891809-34785342-1e8b-4b2e-a2a4-3fdc45ff9197.png">

#### Actual behavior:

The exported font always has the default font name and font family name.

#### Expected behavior:

The exported font should have the user defined font name and font family name.

### To Reproduce:

1. Go to https://fabricicons.azurewebsites.net
2. Select 1 icon
3. Update font file name and font family name text fields
<img width="316" alt="image" src="https://user-images.githubusercontent.com/60023064/152891809-34785342-1e8b-4b2e-a2a4-3fdc45ff9197.png">
 4. Select "Get Subset"

5. Open up downloaded zip and locate .tff font file
6. Open .tff file in a font editor such as Font Forge https://fontforge.org/en-US/
7. Select Element > Font Info...
8.  Note that font name and font family names are their default values not the user defined ones
<img width="456" alt="image" src="https://user-images.githubusercontent.com/60023064/152891866-f2e19e60-be38-47cc-8e66-3c3ed1e18908.png">

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (High)

Products/sites affected: Power Apps

**Comment by gouttierre** [comment]
@rarattay - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows as we’re currently focused on larger coherence work items.

@tomi-msft - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by imrishabh18** [comment]
Hey @bsunderhus, I was going through [Icons.stories.mdx](https://github.com/microsoft/fluentui/blob/21af8da1d98c070a682b26b7d56775d43a749b3d/packages/react-components/react-components/src/Concepts/Icons/Icon.stories.mdx#L32) file and it is says there is a plugin which exports icons as a font file. Can you guide me what to do next, or is it even the right direction to resolve this issue?
