### ISSUE TITLE
GroupedList with custom checkbox causes warning validateDOMNesting button

### ISSUE THREAD

**Issue by luiscantero** [microsoft/fluentui#21644]
The [GroupedList example with custom checkbox](https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist) ([Codepen from the doc](https://codepen.io/pen/?&prefill_data_id=66c61118-813c-4ff2-b647-243c59d4e854)) shows the following warning in the console out-of-the box:
```
"Warning: validateDOMNesting(...): %s cannot appear as a descendant of <%s>.%s" "<button>" "button" "
    in button (created by ToggleBase)
    in div (created by ToggleBase)
    in div (created by ToggleBase)
    in ToggleBase (created by StyledToggleBase)
    in StyledToggleBase (created by t)
    in button (created by t)
    in div (created by t)
    in div (created by t)
    in div (created by t)
    in t (created by Styledt)
    in Styledt (created by t)
    in div (created by t)
    in t (created by t)
    in div (created by t)
    in div (created by t)
    in div (created by t)
    in div (created by t)
    in t (created by t)
    in div (created by t)
    in t (created by t)
    in t (created by Styledt)
    in Styledt (created by GroupedListCustomCheckboxExample)
    in div (created by t)
    in t (created by GroupedListCustomCheckboxExample)
    in div (created by t)
    in t (created by GroupedListCustomCheckboxExample)
    in div (created by GroupedListCustomCheckboxExample)
    in GroupedListCustomCheckboxExample (created by GroupedListCustomCheckboxExampleWrapper)
    in div (created by ThemeProvider)
    in ThemeProvider (created by GroupedListCustomCheckboxExampleWrapper)
    in GroupedListCustomCheckboxExampleWrapper"
```
Browsers: Edge Chromium, Chrome.

The warning is apparently caused by Toggle control, which is a button, being nested in another button:
![image](https://user-images.githubusercontent.com/1353540/152951512-2f4c7eff-2b68-4ce5-b6dc-67754b02150f.png)

**Comment by gouttierre** [comment]
Thanks for filing this item with us, but your added code pen does not work. Could you retest this scenario and provide up to date repro information. Thanks in advance.

**Comment by luiscantero** [comment]
As I mentioned, this is from the official doc.

All you need to do is [go there](https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist) and click on "Export to CodePen":
![image](https://user-images.githubusercontent.com/1353540/166520636-79fa0635-0496-40b8-a3a7-fd73a0138cda.png)

Then open the Console and you will see the error:
![image](https://user-images.githubusercontent.com/1353540/166521059-ea523638-b384-4b78-8503-c5e4f7a0520f.png)

**Comment by gouttierre** [comment]
@luiscantero - Thanks for updating the issue with repro information.  To set expectations the developers will review this issue once capacity allows.

@GeoffCox - Would you be able to confirm if this is a regression, or if this behavior is an issue?
