### ISSUE TITLE
[Dark mode] If a color in the color picker is the same of the background color, the color becomes not visible. 

### ISSUE THREAD

**Issue by juliaroldi** [microsoft/fluentui#21659]
### Environment Information

- **Package version(s)**:8.36.0

#### Actual behavior:

The darker gray is not visible, since is the same color of the background. 
![Screen Shot 2022-02-08 at 17 22 13](https://user-images.githubusercontent.com/87443959/153076734-7c9cae08-d4e0-439c-a0e5-31f1010c9522.png)

#### Expected behavior:

 Should be able to set a border color at only one cell of the color picker grid. Therefore, will be possible to recognize the color.
![ColorPicker](https://user-images.githubusercontent.com/87443959/153077021-120f449a-0a65-4ce0-9989-a1566c18f316.gif)

**Comment by gouttierre** [comment]
@juliaroldi - Thanks for filing this issue with us. This issue is slightly old I see, would you be so kind to confirm if you're still facing the same problem with dark mode? And are you using the latest version of fluent?

**Comment by juliaroldi** [comment]
@gouttierre  According to the fluent-ui docs, it is not possible to add border to a single cell https://developer.microsoft.com/en-us/fluentui#/controls/web/swatchcolorpicker#IColorCellProps

**Comment by juliaroldi** [comment]
We are using version 8.67.2".
