### ISSUE TITLE
Determine api-extractor usage most appropriate for v9 components

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#21658]
api-extractor does several things for v8 such as document props and detect API changes.

The Commons type issue in v9 brought up that we need to review 
- is api-extractor is providing value for v9 given that storybook is documenting props
- is api-extractor the way we want to detect and gate API changes in the CI builds
- we sometimes have types that are used in an exported type, but that we don't want to export (such as Commons).  Is there a way in api-extractor to handle these cases? (maybe a merge of types for documentation) or should we propose a change to api-extractor?

@ecraig12345 - You may be someone who knows the most about api-extractor and its history with fluent.  This is probably a v-build team consideration as well.

**Comment by ecraig12345** [comment]
> * is api-extractor is providing value for v9 given that storybook is documenting props
> * is api-extractor the way we want to detect and gate API changes in the CI builds

It's still providing some value with at least partial awareness of API changes, though as we stop exporting types that decreases. We could investigate other solutions but I'm not sure what all is available. (Probably shouldn't write our own tool, in the interest of not owning even more tools.)

> * we sometimes have types that are used in an exported type, but that we don't want to export (such as Commons).  Is there a way in api-extractor to handle these cases? (maybe a merge of types for documentation) or should we propose a change to api-extractor?

API Extractor doesn't have an option to handle this case. We could try proposing it but I doubt the request would be accepted.

**Comment by Hotell** [comment]
Based on discussion during tech sync I'm adding recap/some answers for better visibility:


> is api-extractor is providing value for v9 given that storybook is documenting props

Not at the moment, we use it for API generation in V8 only

> we sometimes have types that are used in an exported type, but that we don't want to export (such as Commons). Is there a way in api-extractor to handle these cases? (maybe a merge of types for documentation) or should we propose a change to api-extractor?

- API Extractor will correctly add those non exported types to rolluped dts ( which is the most important part for consumer). - regarding API documentation md file, as @ecraig12345 said, it won't inline those types - that would need to be implemented


**What are our options:**


1. we will ship rolluped dts for packages in upcoming future, to mitigate ability to access private paths (as  we won't be able to rollup package files based on my benchmarking and research - will be presented in different RFC/meeting). 

For this we need either `api-extractor` or some other tool (more info https://medium.com/@martin_hotell/typescript-library-tips-rollup-your-types-995153cc81c7)

2. we can either turn off generating `api.md` files for v9 completely 
```
apiReport.enabled = false
```

 or turn off particular warning and its emit to api report (`ae-forgotten-export`) for v9

```
"messages": {
    "extractorMessageReporting": {
      "ae-forgotten-export": {
        "logLevel": "none",
        "addToApiReportFile": false
      }
    }
  }
```

### Summary

based on tech sync discussion we gonna go with option 2 for now.
