### ISSUE TITLE
Conformance tests for triggers

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#21670]
Recently we had various discussions around triggers and reached the agreement on how it should work:

- No magic handling of props in triggers, props should be applied always. I.e consistently set the same attributes and props
- `child.props` always win, it is user's responsibility to handle it
  - The exclusion from the rule are callbacks, they are merged

Another point that we could cover that contract with conformance tests and enable them for components that use the trigger pattern. For an initial implementation the following scenarios should be covered.

### Props merging

Props specified by a customer always win.

```tsx
function App() {
  return (
    <Trigger>
      <button id="foo" aria-label="bar" />
    </Trigger>
  );
}
```

This should render following markup:

```html
<button id="foo" aria-label="bar"></button>
```

### Callback merging

Internal and user's callbacks should be merged.

```tsx
function App() {
  return (
    <Trigger>
      <button onClick={() => console.log('foo') />
    </Trigger>
  );
}
```

- internal `onClick` handler in `Trigger` should be called if present
- `onClick` specified by user should be also called

**Comment by miroslavstastny** [comment]
This is needed as there are tests which are already copy&paste.
