### ISSUE TITLE
BaseButton IE11 workaround causing significant slowdown

### ISSUE THREAD

**Issue by vijaypemmaraju** [microsoft/fluentui#21677]
I'm working on a chrome extension that injects content into Salesforce Lightning. In this specific scenario, for whatever reason, adding fluent buttons significantly slows down the performance of most inputs on the page (3-4 seconds per interaction), even those that have nothing to do with our chrome extension. After digging around a while, I found [this piece of code](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Button/BaseButton.styles.ts#L57-L62) that adds a wildcard selector to children of the `BaseButton` component. I have confirmed locally that removing this piece of code fixes the performance issue across the board.

I have tried to override this logic by programmatically removing the rules using the `removeRule` DOM API, which works but is pretty hacky and requires doing so in an interval.

Since we are building for a chrome extension, ie11 compatibility isn't relevant for us. Would there be some way to disable this behavior? That would solve our problem immediately.

### Environment Information

- **Package version(s)**: @fluentui/react@8.22.0
- **Browser and OS versions**: Chrome 97.0.4692.99, Mac OS 12.1

### Please provide a reproduction of the bug in a codepen:

Unfortunately, I've been having a very difficult time trying to demonstrate this bug in a codepen because it requires a very content heavy DOM to see the effects. This isn't the first time I've run into performance issues with css and Salesforce Lightning, so it could be something specific to their DOM layout and styling.

#### Actual behavior:

Rendering a button slows down other inputs on the page.

#### Expected behavior:

Rendering a button should not introduce a performance regression on otherwise unrelated parts of the page.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: Salesforce Lightning

**Comment by micahgodbolt** [comment]
Can you pass in some custom styles to override this CSS? I'm afraid that removing it will cause the active shifting noted in the comment.

**Comment by vijaypemmaraju** [comment]
I wasn't able to override this behavior via the styling api, and even if I did, I think just the presence of the style was still causing a performance issue

**Comment by micahgodbolt** [comment]
@vijaypemmaraju it looks like we can change that star to a span quite easily. The immediate child is always the same span in our buttons.
