### ISSUE TITLE
Commandbar separator has focus and appear in the opened menu on the side as button

### ISSUE THREAD

**Issue by garubin** [microsoft/fluentui#21689]
### Please provide a reproduction of the issue in a codepen:
https://codepen.io/galru/pen/yLPbzpr?editors=1010

#### Actual behavior:

Focus is moving to separator elements present in the menu area and it is defined as a menu item. Screen reader is announcing it as 'separator element menu item 2 of 7 disabled'.

#### Expected behavior:

Separator must not be defined as menu element and Focus must not move to separator elements present in the menu area and it must not be defined as a menu item.

### Documentation describing expected behavior

This is an accessibility bug that was opened by Microsoft. Will appriciate your help to be able to add a Separator element and to have the ability to make unfocusable.

**Comment by micahgodbolt** [comment]
CommandBar doesn't support separator elements. If you need a visual separation between two elements you can use css borders or pseudo elements.
