### ISSUE TITLE
Wrong tooltip for tuesday

### ISSUE THREAD

**Issue by debabbe** [microsoft/fluentui#21687]
The tooltips for all day are correctly displayed
![image](https://user-images.githubusercontent.com/20656853/153389544-874c73f5-c65b-49d2-b9d2-296d9d417547.png)
Except of thuesday
![image](https://user-images.githubusercontent.com/20656853/153389711-86ce60b1-c2b8-4c38-8312-e1ca167e80df.png)

**Comment by micahgodbolt** [comment]
I can't seem to repro this. The buttons don't appear to have titles. Can you verify if this is still an issue?

**Comment by micahgodbolt** [comment]
Oh, hover over the days of the week. Sorry, I thought your hover was over the date.
