### ISSUE TITLE
create-react-app logs warnings for source maps with react-components

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#21686]
simply install create-react-app and react-components and we get lots of this error

![image](https://user-images.githubusercontent.com/20744592/153384981-0ebd3b85-d479-4d02-a984-159c9039a780.png)

Code used in create-react-app, pulled from the [card example in the docsite](https://6002298f95a00c00213f4d55-tarzihbtdc.chromatic.com/?path=/docs/preview-components-card--default#action-card)

```tsx
import * as React from "react";

import { Body, Caption } from "@fluentui/react-text";

import { Button } from "@fluentui/react-button";
import { OpenRegular, MoreVerticalRegular } from "@fluentui/react-icons";
import {
  Card,
  CardFooter,
  CardHeader,
  CardPreview,
} from "@fluentui/react-components/unstable"; // codesandbox-dependency: @fluentui/react-card ^9.0.0-beta

const ASSET_URL =
  "https://raw.githubusercontent.com/microsoft/fluentui/master/packages/react-card";

const avatarMauricioURL = ASSET_URL + "/assets/avatar_mauricio.svg";
const powerpointLogoURL = ASSET_URL + "/assets/powerpoint_logo.svg";
const aiDeckTemplateURL = ASSET_URL + "/assets/ai_deck_template.png";

export const Default = () => {
  return (
    <>
      <Card tabIndex={0} onClick={() => console.log("Test action")}>
        <CardHeader
          image={<img src={avatarMauricioURL} alt="Face of a person" />}
          header={
            <Body>
              <b>Mauricio August</b> + 7 others edited
            </Body>
          }
          description={<Caption>Artificial Intelligence Deck</Caption>}
          action={
            <Button
              appearance="transparent"
              icon={<MoreVerticalRegular fontSize={20} />}
            />
          }
        />

        <CardPreview
          logo={<img src={powerpointLogoURL} alt="Microsoft PowerPoint logo" />}
        >
          <img
            src={aiDeckTemplateURL}
            alt="Preview of an artificial intelligence slide deck"
          />
        </CardPreview>

        <CardFooter>
          <Button icon={<OpenRegular fontSize={16} />}>View changes</Button>
        </CardFooter>
      </Card>
    </>
  );
};
```

**Comment by ling1726** [comment]
The root cause of the problem is a misunderstanding of what `--no-cache` in Lage actually does. Our build pipelines assume that `--no-cache` in Lage will still save the build to Lage's cache:

https://github.com/microsoft/fluentui/blob/d5a34ee8ba3e9204aeb99214321045c3d6b786fa/azure-pipelines.release.yml#L51

In the main release pipeline, the assumption is that `test` and `lint` phases will not run the build again. But in fact `test` will run again because of a cache miss **because Lage does not save to cache with the --no-cache flag**. Therefore the `test` command will build all packages again in **development mode** ⚠️⚠️⚠️

The v8 release actually works because of the `bundle` command that runs after `test` and `lint`. Lage will create different cache entries based on the CLI flag. In this case the `--production` flag results in a cache miss and artifacts are built in production mode. 

https://github.com/microsoft/fluentui/blob/d5a34ee8ba3e9204aeb99214321045c3d6b786fa/azure-pipelines.release.yml#L61

In the v9 pipeline, there is no `bundle` task that runs the build again in production mode, so the final shipped packages are actually built in **development mode** ⚠️⚠️⚠️

This results in `inlineSources` option not being set in the `tsc` compile step and results in incorrect source maps being bundled into the published package.

https://github.com/microsoft/fluentui/blob/d5a34ee8ba3e9204aeb99214321045c3d6b786fa/scripts/tasks/ts.ts#L17


**This has been an issue since the first beta release**. However since our current build target is `es2019` there is very little difference between debugging the built code and the actual code through sourcemaps. The warning in the issue will only occur if source map loader is used with webpack.

**Conclusion**: We should fix the pipeline by reordering the steps, then force bump all packages so that they will all be released the next time we run the release pipeline. However, there is no urgency to this. We can simply fix this along with the next batch of RC changes.

**Comment by ecraig12345** [comment]
I just realized there's an arg [`--only`](https://microsoft.github.io/lage/guide/cli.html#only) for running only the specified task, not the tasks it depends on (but doesn't affect the package graph that's run). I think that will let us actually get rid of the extra builds.
