### ISSUE TITLE
Search Box - Query Regarding onClear

### ISSUE THREAD

**Issue by jai8888** [microsoft/fluentui#21692]
- **Package version(s)**:  8.55.0

### Describe the issue:
How to dynamically invoke onClear method?

I want to "clear" the search box, once value is selected?

Scenario: I am using search box to query against a table that is showing data [matching to query] in DetailsList. After selecting the value, it sets the value to a lookup. However the search string still remains in the Search Box. How can I 'clear' it once selection has been made & value has been set?

**Comment by jai8888** [comment]
Hello Team,

Please let me know if there is any update regarding this query?

Thanks!

**Comment by micahgodbolt** [comment]
searchbox can be a controlled input, so onSelection, update the `value` with `setValue`

https://codepen.io/micahgodbolt/pen/jOaXBOX?editors=0010
