### ISSUE TITLE
makeStyles  Object not updated when RTL not changed

### ISSUE THREAD

**Issue by NewFuture** [microsoft/fluentui#21710]
### Environment Information

- **Package version(s)**:  8.49.7
- **Browser and OS versions**:  Chrome 97

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/newfuture/pen/wvPeBKK?editors=1010

```tsx
const useStylesObj = makeStyles({ root: { paddingLeft: "100px" } });
const useStylesFun = makeStyles(() => ({ root: { paddingLeft: "100px" } }));

const RtlStyle = () => {
  return (
    <div>
      <div className={useStylesObj().root}>
        paddingLeft:
        {"const useStylesObj = makeStyles({ root: { paddingLeft: '100px' } })"}
      </div>
      <div className={useStylesFun().root}>
        paddingLeft:
        {"const useStylesFun = makeStyles(() => ({ root: { paddingLeft: '100px' } }))"}
      </div>
    </div>
  );
};
```

#### Actual behavior:

![image](https://user-images.githubusercontent.com/6290356/153570486-4daea856-7760-4e88-be75-8d75a99cc838.png)
![image](https://user-images.githubusercontent.com/6290356/153571032-18f9fade-e30c-41f6-b3bd-8ab84c28b795.png)

#### Expected behavior:
```
const useStylesObj = makeStyles({ root: { paddingLeft: "100px" } });
```
response to  RTL change. (padding-right)

**Comment by micahgodbolt** [comment]
Solution looks pretty simple. We just need to always use the theme for the style path regardless of it is a functional style or not

https://github.com/microsoft/fluentui/blob/master/packages/react/src/utilities/ThemeProvider/makeStyles.ts#L72

```tsx
 const path = isStyleFunction ? [id, win, theme] : [id, win];
// changed to
 const path = [id, win, theme];
```
