### ISSUE TITLE
The @fluentui/react-compose package contains deprecated @types/classnames

### ISSUE THREAD

**Issue by alexey-koren** [microsoft/fluentui#21722]
@fluentui/react-compose has deprecated @types/classnames package in dependencies

![image](https://user-images.githubusercontent.com/36141306/153796470-0e92b09b-a579-4640-ae40-8d09c169003e.png)

![image](https://user-images.githubusercontent.com/36141306/153796631-3e2c29bd-1aa8-4f9c-be74-cdc184a91781.png)

https://www.npmjs.com/package/@types/classnames

![image](https://user-images.githubusercontent.com/36141306/153795402-e4ba569f-25fb-4105-a44c-9b33d3fc7457.png)

https://github.com/JedWatson/classnames/blob/master/HISTORY.md

**Comment by micahgodbolt** [comment]
@fluentui/react-compose has been deprecated and folded into our utilities folder. Are you relying on this package for some reason? If it's a dependencies dependency, upgrade to the latest version and this package should no longer be in your dependency tree.
