### ISSUE TITLE
Horizontal Radio options using FluentUI control choicegroup

### ISSUE THREAD

**Issue by atasims07** [microsoft/fluentui#21727]
#### Describe the feature that you would like added

Horizontal Radio options

#### What component or utility would this be added to

Like in Knockout controls we have option to set the flag "singleItemPerLine" to true which will give us vertical Radio options, can we have something similar to that in FluentUI control Choicegroup? It's very easier that way. Currently we are not able to have horizontal choice groups without custom building it.

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

In order to implement something like this
![Screenshot 2022-02-14 154124](https://user-images.githubusercontent.com/75667107/153844204-268284d5-7413-4486-b4bd-69cf3adb3bcc.png)

**Comment by brendon-colburn** [comment]
> Passing some custom styles into ChoiceGroup can layout items horizontally:
> 
> https://codesandbox.io/s/fluent-v8-horizontal-choicegroup-2sfuqi?file=/src/ChoiceGroupBasicExample.tsx
> 
> ```
> // To make the ChoiceGroup horizontal,
> // the label and flexContainer must both be inline
> // and the flexContainer's direction be set to row.
> //
> // This is the same styling applied when there is an
> // image or icon in the ChoiceGroup.
> //
> // The 1em column gap is added to put some spacing between
> // the items based on the font-size of the options.
> const choiceGroupStyles = {
>   label: {
>     display: "inline"
>   },
>   flexContainer: {
>     columnGap: "1em",
>     display: "inline-flex",
>     flexDirection: "row",
>     flexWrap: "wrap"
>   }
> };
> 
> <ChoiceGroup
>       // The custom styles need to be applied to the choice group
>       // to change the layout to horizontal.
>       styles={choiceGroupStyles}
>     />
> ```

Works well but I think people are typically looking for the choices to be underneath the label.
