### ISSUE TITLE
Searchable dropdown

### ISSUE THREAD

**Issue by TankDoor** [microsoft/fluentui#21746]
#### Describe the feature that you would like added

Given that the dropdown is open I would like to be able to type text and for that text to locate an item in the dropdown

#### What component or utility would this be added to

DropDown

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

None required. This is common drop down behavior else where

**Comment by tomi-msft** [comment]
Hi TankDoor, thanks for filing the issue. Would `ComboBox` be a good component to use for this case? It will allow you to type in the text field and show relevant results in the dropdown menu

**Comment by NWH-SAmin5** [comment]
@tomi-msft its not working as you are suggesting on Fluent UI site
https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/combobox

Try this section with auto complete on
"ComboBox with toggleable autoComplete and allowFreeform"

**Comment by newlogics** [comment]
@TankDoor here is a sample implementation of searchable dropdown in fluent UI.
**Code pen:** [https://codepen.io/newlogics/pen/dyKGeGV](https://codepen.io/newlogics/pen/dyKGeGV) 
**Gist:** [https://gist.github.com/newlogics/75f55e55c9a292d07e61345aab39c60d](https://gist.github.com/newlogics/75f55e55c9a292d07e61345aab39c60d)
