### ISSUE TITLE
Set custom Combobox id 

### ISSUE THREAD

**Issue by pikkoui** [microsoft/fluentui#21753]
Is there a way to set a custom input id on the combobox component?
![image](https://user-images.githubusercontent.com/16716555/154059635-a95d16d2-1bc7-479e-bb0a-dd6a2f6a4177.png)

**Comment by gouttierre** [comment]
I’ve added this to our backlog for contributors as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance..

**Comment by ahalf-yuan** [comment]
May I ask why you need to set a custom input id on the Combobox? Is the `React ref` useful?
