### ISSUE TITLE
Callout doesn't read swatchColorPicker labels in Narrator in Scan mode when nested

### ISSUE THREAD

**Issue by dacheson** [microsoft/fluentui#21765]
### Environment Information

- **Package version(s)**:"^7.170.0"
- **Browser and OS versions**: Edge  98.0.1108.43

### Describe the issue:

If you make a SwatchColorPicker with labels for the color (for Narrator) and nest it inside a callout. When you run narrator and focus on the colors in Scan Mode, narrator only reads out, "Unlabelled Graphic". It works fine when not in Scan Mode. This is in Edge.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/dacheson66/pen/bGYYdbd?editors=1111

#### Actual behavior:
Narrator reads out "unlabelled graphic" when focused on a color in the picker when nested in a callout in Scan Mode.

#### Expected behavior:
Narrator reads out the label e.g. "Pink" when focus shifts to a color. This can be seen by turning Scan Mode off (Caps + Space) and focusing a color.

**Comment by dacheson** [comment]
@tomi-msft @msft-fluent-ui-bot  What is the ETA for triaging accessibility bugs? We will be able to release with only supporting non-scan mode. However we'd like to know if this is something you'd plan on fixing or not please

**Comment by tomi-msft** [comment]
Hi @dacheson Thanks for submitting the issue. I believe what is happening is that the parent button element of the color has the correct `aria-label` but is not passing the prop down to the span that contains the svg. If you use the up and down arrow keys, the Narrator will say the label, then say unlabelled graphic. I will be working with @smhigley on a fix for this next week.
