### ISSUE TITLE
User can't tell which columns are sortable in DetailsList

### ISSUE THREAD

**Issue by DavidParks8** [microsoft/fluentui#21767]
### Environment Information

- **Package version(s)**: v7.x,8.x,9.x
- **Browser and OS versions**: all

### Describe the issue:

For DetailsList columns which have tri-state sort (ascending, descending, and unsorted), there is no indication in the column header by default that the column is sortable when in the unsorted state. Specifically, the code which is the culprit is in [DetailsColumn.base.tsx](https://github.com/microsoft/fluentui/blob/c4912723213bb1a15b4af2f6c7962bc32064bf4a/packages/react/src/components/DetailsList/DetailsColumn.base.tsx#L168) where the sorting icon is not rendered when isSorted is falsey. This violates the [first principle of accessibility](https://www.w3.org/WAI/WCAG21/Understanding/intro#understanding-the-four-principles-of-accessibility) because the user has no way of knowing which columns are sortable vs which are not.

### Please provide a reproduction of the issue in a codepen:

[https://codepen.io/DavidParks8/pen/JjOOdBz](https://codepen.io/DavidParks8/pen/JjOOdBz) 
Ask yourself when the page loads whether or not the "Date Modified" column is sortable.

#### Actual behavior:

Sortable columns end up looking the same as non-sortable columns when the sortable columns are in an "unsorted" state. There is no extra icon in the column to indicate sortability.

#### Expected behavior:

Sortable columns in an unsorted state should show the fluentui up down arrow icon 
![image](https://user-images.githubusercontent.com/18634904/154158138-11a2c005-c8de-46b9-a663-98a23f021afa.png)
 to indicate they are sortable. When the IColumn is sortable but unsorted, there is not enough metadata in the IColumn to know that it is sortable. Currently, there is only isSorted, and isSortedDescending. There needs to be another field or extra metadata that indicates if the column can be sorted, and if so, an up/down arrow icon should be shown in the column header.

### Documentation describing expected behavior

[The four principles of accessibility from WCAG](https://www.w3.org/WAI/WCAG21/Understanding/intro#understanding-the-four-principles-of-accessibility)

**Comment by tomi-msft** [comment]
Hi @DavidParks8 thanks for filing the issue. So after taking a look at this, it looks like this is a feature that you would like to add to DetailsListColumn. 

The metadata you need in the column can be found in the attribute `aria-sort`. `aria-sort="none"` means that a column is sortable and not currently sorted, `aria-sort="ascending/descending"` means that a column is sortable and currently sorted. 

The UpDown arrow icon for an unsorted sortable column is then a design decision
