### ISSUE TITLE
Charting: Legends don't support arrow keys

### ISSUE THREAD

**Issue by jcksonhe** [microsoft/fluentui#21764]
### Environment Information

- **Package version(s)**: @fluentui/react-charting@5.7.14, @fluentui/react@8.55.2
- **Browser and OS versions**: Edge 98.0.1108.43

### Describe the issue:

According to the ARIA practices referenced below, `listbox` roles should support selection with with arrow keys when an option is focused. However, it seems that legends in v8 charting components do not allow this, but it does in v7.

### Please provide a reproduction of the issue in a codepen: 
v7: https://codepen.io/jcksonhe/pen/QWOOwXN
v8: https://codepen.io/jcksonhe/pen/qBVVBLa

#### Actual behavior:

In v8, selecting an option in a legend with `listbox` role and using all arrow keys does not navigate the options, but it does in v7.

#### Expected behavior:

In v8, selecting an option in a legend with `listbox` role and using the left/right arrow keys should selection the option to the left/right (respectively), just like in v7

### Documentation describing expected behavior

https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/listbox/listbox.html

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.
@Raghurk - Would you be able to confirm if this is a regression, or if this behavior is an issue?
