### ISSUE TITLE
Calendar: supports vertical mode and responsive.

### ISSUE THREAD

**Issue by jasonhieu1905** [microsoft/fluentui#21771]
#### Describe the feature that you would like added
We are using Calendar component in a panel, when showing Calendar in some devices which are having limited width (mobile, tablet ...), the Calendar does not fully  show Day and Month picker, also the pickers are not responsive.

#### What component or utility would this be added to
(https://developer.microsoft.com/en-us/fluentui#/controls/web/calendar)

#### Additional context/screenshots
Actual behavior: : 
![image](https://user-images.githubusercontent.com/13063615/154193495-f57d5543-b0be-404c-bc6a-9bb049010abd.png)
![image](https://user-images.githubusercontent.com/13063615/154194124-3dc52d90-9ecc-4f00-82be-51df51c6b906.png)

Expected behavior:
- can decide to show picker vertically on purpose.
- pickers supports responsive mode (month picker automatically on/off when resizing)

Eg:
![image](https://user-images.githubusercontent.com/13063615/154193666-2e5f5785-18be-47d8-94a4-c802ff13ff3e.png)

**Comment by barisbikmaz** [comment]
An example why a vertical version would be also cool and that the calendar is not showing the year picker when screen gets bigger or collapsing when the screen gets smaller.

![FluentUI-Calendar](https://user-images.githubusercontent.com/6338132/157414520-e5aebe5a-e341-4d23-943a-9e60c04006fc.gif)
