### ISSUE TITLE
Migrate screener stories to CSF instead of storiesOf

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#21779]
Right now in the vr-tests packages we use the deprecated `storiesOf` format for declaring stories. This will be removed in storybook v7, so we'll eventually need to migrate the vr-tests stories to CSF (component story format).

Storybook has a migration for `storiesOf` to CSF: `npx sb migrate storiesof-to-csf --glob "**/*.stories.js"`
https://storybook.js.org/blog/component-story-format/

This doesn't quite work out of box on our stories, but if we make the following manual modifications it will get us a lot of the way there:
- Find/replace `addStory` => `add` (so the mod will recognize it; leaving the extra parameters for now is fine)
- For anything with multiple `storiesOf` calls in the same file (at least with the same name), split it into multiple files

The migration more or less works after that (based on a small test). We'll still have to figure out how to restore the functionality of auto-added stories for RTL and different themes (that's what the `addStory` API did) but there should be some way to do it.

**Comment by ling1726** [comment]
Official docs from screener: https://docs.saucelabs.com/visual/faq/#how-do-i-add-screener-steps-to-storybook-component-story-format-csf-stories
