### ISSUE TITLE
TextField autoFocus={false} not working

### ISSUE THREAD

**Issue by NWH-SAmin5** [microsoft/fluentui#21784]
### Environment Information

- **Package version(s)**: 7.174.1
- **Browser and OS versions**: Microsoft Edge Version 99.0.1150.16 (Official build) beta (64-bit) and Windows 10

#### Actual behavior:
This is the code
```
<Modal>
  <div className={styles.modalHeader}>
  </div>
  <div>
        ...
        ...
        ...
        ...
        very very long text
        ...
        ...
        ...
  </div>
  <div className={styles.modalFooter}>
    <Stack tokens={stackTokens}>
      <Stack.Item align="start">
        <TextField className={styles.fullNameTextField} placeholder="Please enter full name here" autoComplete="off" autoFocus={false}/>
      </Stack.Item>
    </Stack>
  </div>
</Modal>
```

**Issue**: Modal has a very long text and TextField is added in the footer of the modal. When modal is rendered there is some auto focus being set to TextField, due to that user is landed on bottom of the modal first. I want to user to land on the top section of the modal.

I tried setting autoFocus={false} for TextField but its still setting focus on it.

#### Expected behavior:

autoFocus={false} should avoid setting focus to TextField

**Comment by tomi-msft** [comment]
Hi, could you please provide a codepen with the issue reprod? I'm having trouble reproing the issue
