### ISSUE TITLE
yAxisTickFormat is not workin

### ISSUE THREAD

**Issue by arnoldnemedi** [microsoft/fluentui#21792]
### Environment Information

- **Package version(s)**: 4.20.5
- **Browser and OS versions**: Chrome

### Describe the issue:

If I set yAxisTickFormat=",.2f" it does not format the y values. Only the ,.2f everywhere.

#### Actual behavior:

If I set yAxisTickFormat=",.2f" it does not format the y values. Only the ,.2f everywhere.

#### Expected behavior:

The numbers should be formatted.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Blocking

Products/sites affected: (if applicable)

**Comment by tomi-msft** [comment]
Hi @arnoldnemedi thanks for submitting an issue. Could you provide more details on which component you are having problems with and a repro of the issue if possible?
