### ISSUE TITLE
Contextual Menu Items do not support only fluent icons

### ISSUE THREAD

**Issue by ashray17aman** [microsoft/fluentui#21804]
### Environment Information

- **Package version(s)**:     "@fluentui/react": "8.45.0",
- **Browser and OS versions**: Chrome Browser and tested on codepen.io

### Please provide a reproduction of the bug in a codepen:
Codepen with visible icons --> https://codepen.io/ashrayaman/pen/ZEarWYW
Codepen with icons not visible --> https://codepen.io/ashrayaman/pen/abVqNOW

#### Actual behavior:
1 - Open the 'ContextualMenu with icons' example in codepen, present in [Fluent UI Contextual Menu](https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu)
2 - You can find the menu items for contextual menu has some icons passed via iconProps --> iconName and some passed via onRenderIcon in one menu item.
3 - The menu items appear just fine. However, if we remove the menu items which has icons passed via iconProps and keep just the menu items with onRenderIcon then the icons do not appear. 
In essence -> the menu items need to have atleast one menu item with 'Office UI Fabric Icon' else the icons won't appear, which in other way is -> if the menu items have icons only from 'Fluent System Library' or custom icons, then it won't appear in the menu items.

#### Expected behavior:
The menu items should appear with icon passed via onRenderIcon even if none of the icons belong to Office UI Fabric Icons.

Extra Info --> 
A use case -> if some but not all menu items have icons, then all the menu item's text appear vertically aligned
I believe the office fabric icons provide a right shift to the text in contextual menu items and if it's not present in any of the menu items then the right shifting of text is missed and the custom icons passed via onRenderIcon do not appear.

### Priorities and help requested:

Are you willing to submit a PR to fix? Can't

Requested priority: Normal

Products/sites affected: Powerapps Portals

**Comment by micahgodbolt** [comment]
Okay, the menu checks to see if you have any icons in your items list before telling the below render functions to make room for, and render those icons. To determine if there are icons, it looks for any item with iconProps. 

One fix would be to also check for onRenderIcon when determining if there are any icons, but that could have negative side effects because sometimes you pass in the "how do I render Icons" even when there aren't any icons to render.

Therefore, the easiest solution for this problem is to just pass in an empty iconProps into at least one of your items

```tsx
  items: [
    {
      hasIcons: true,
      key: 'openInWord',
      text: 'Open in Word!',
      iconProps: {},
      onRenderIcon: props => {
        return <Icon iconName="WordLogo16" />;
      },
    },
  ],
```

I hope this works for you.

**Comment by micahgodbolt** [comment]
created a PR to update that example so you'd have started with that empty object already

https://github.com/microsoft/fluentui/pull/21916

**Comment by ashray17aman** [comment]
Hi, Thank you for looking into it. I had just one concern, it would be more helpful if you could add the same piece of information in the documentation for 'IContextualMenuProps' or in the description text of 'iconProps'
