### ISSUE TITLE
Button not aligned with Dropdown when error message is showing

### ISSUE THREAD

**Issue by xinguo98052** [microsoft/fluentui#21801]
### Environment Information

- **Package version(s)**: Fluent ui 8.49.7
- **Browser and OS versions**: Version 97.0.1072.62 (Official build) (x86_64)

### Please provide a reproduction of the bug in a codepen:

Go to codepen, JS(TypeScript) code:
const { Dropdown, IDropdown, PrimaryButton, IStackTokens, Stack, ThemeProvider, initializeIcons } = window.FluentUIReact;

// Initialize icons in case this example uses them
initializeIcons();

const dropdownStyles = { dropdown: { width: 300 } };

const DropdownRequiredExample: React.FunctionComponent = () => {
  const dropdownRef = React.createRef<IDropdown>();
  const onSetFocus = () => dropdownRef.current!.focus(true);

  const stackTokens: IStackTokens = { childrenGap: 20 };

  return (
    <Stack tokens={stackTokens} verticalAlign="end">
      <Stack horizontal tokens={stackTokens} verticalAlign="end">
        <Dropdown
          componentRef={dropdownRef}
          placeholder="Select an option"
          label="Required dropdown example"
          options={[
            { key: 'A', text: 'Option a', title: 'I am option a.' },
            { key: 'B', text: 'Option b' },
            { key: 'C', text: 'Option c', disabled: true },
            { key: 'D', text: 'Option d' },
            { key: 'E', text: 'Option e' },
          ]}
          required
          styles={dropdownStyles}
          errorMessage="This is test error message!This is test error message!This is test error message!This is test error message!"
        />
        <PrimaryButton
          text="Set focus"
          // eslint-disable-next-line react/jsx-no-bind
          onClick={onSetFocus}
        />
      </Stack>
      <Dropdown
        placeholder="Required with no label"
        ariaLabel="Required dropdown example"
        options={[
          { key: 'A', text: 'Option a', title: 'I am option a.' },
          { key: 'B', text: 'Option b' },
          { key: 'C', text: 'Option c', disabled: true },
          { key: 'D', text: 'Option d' },
          { key: 'E', text: 'Option e' },
        ]}
        required={true}
        styles={dropdownStyles}
      />
    </Stack>
  );
};

const DropdownRequiredExampleWrapper = () => <ThemeProvider><DropdownRequiredExample /></ThemeProvider>;
ReactDOM.render(<DropdownRequiredExampleWrapper />, document.getElementById('content'))

#### Actual behavior:

The "Set focus" button is not aligned with dropdown when error message is showing
![image](https://user-images.githubusercontent.com/99920791/154574023-c044e4d4-5fb1-406f-bbf2-8926ed1fd1a0.png)

#### Expected behavior:
The "Set focus" button should be aligned with dropdown when error message is showing

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable) 

This could be design change / feature request: I believe that the best fix will be adding onRenderFoo to generate custom control for the "Set focus" button.

**Comment by micahgodbolt** [comment]
The set focus button is not part of the control. If you want to align it with the dropdown, move the label out of the dropdown, and put dropdown and button in their own div.

**Comment by micahgodbolt** [comment]
One improvement we could make would be to change the demo code in https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown, moving the label out and above the dropdown and button

https://codepen.io/micahgodbolt/pen/PoOEBam

**Comment by xinguo98052** [comment]
If the error message is too long, like this:
 errorMessage="TestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTest"

then we have this result:
![image](https://user-images.githubusercontent.com/99920791/154777151-df792e0d-90aa-4d7d-b588-811f2965b20a.png)
