### ISSUE TITLE
DefaultButton textoverflow when width is shorter

### ISSUE THREAD

**Issue by iron-man14** [microsoft/fluentui#21818]
### Environment Information

- **Package version(s)**: @fluentui/react v7.170.0

### Describe the issue:

When using DefaultButton and it is wrapped by a div whose width is shorter than the length of the text in DefaultButton, the text overflows from the div and there is no way to justify content, hide overflow or set textOverflow to "ellipsis" to the text of DefaultButton.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/91572832/154778267-69068897-1e86-4fed-823d-864c817bddd6.png)

#### Expected behavior:

- following is achieved by editing css of DefaultButton from developer tool:
![image](https://user-images.githubusercontent.com/91572832/154778701-b695c371-e0bd-4555-bd5f-eb9f5759acd9.png)
1. added overflow: hidden
2. removed justify-content: center

![image](https://user-images.githubusercontent.com/91572832/154778403-54f73c19-5069-4aed-b128-4098938a371a.png)

- cannot even append ellipsis at the end from developer tool due to **span** tag wrapped around the text. (text-overflow can only be applied to block elements; **span** is an inline element)

### If applicable, please provide a codepen repro:

https://codepen.io/harryhtet/pen/JjOpBNw

**Comment by shivangsoni** [comment]
I am facing the similar kinda issue. Can this be prioritized please?
