### ISSUE TITLE
DropDown Multiple Selection Regression Bug

### ISSUE THREAD

**Issue by cstechfoodie** [microsoft/fluentui#21814]
### Environment Information

- **Package version(s)**: (fill this out)
Any version >= 0.52.2. This is the rough version I can trace on the demo web. This is a regression bug, previous versions are good. It could be completely reproducible in https://fluentsite.z22.web.core.windows.net/0.52.2/components/dropdown/definition#types-multiple

- **Browser and OS versions**: (fill this out if relevant)
N/A

### Please provide a reproduction of the bug in a codepen:
1. go to dropdown => multiple selection 
2. selection all dropdown options and make sure there is a scroll bar
3. mouse hover inside the dropdown but not  on any pills
4. [try scroll up and down, the page is scrolling instead of the expected dropdown box.](https://gyazo.com/bab85e6e1156afa3f6ea3af1c359db0a)
5. [Drag and move the scroll bar of the dropdown box, not work
](https://gyazo.com/f2f15dd9afdafe1ae314837f634da5a9)
6. now, hover mouse pointer on pill, and scroll. it only works when hovering on pills.

#### Actual behavior:

Please see the attached gif above

#### Expected behavior:

[A good example in vrsion 0.51.7](https://gyazo.com/5f1bd90ec0e2582e6f99522157286e73)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No. 
Requested priority: (Blocking, High, Normal, Low)
High
Products/sites affected: (if applicable)
Microsoft Product

**Comment by sctamms** [comment]
This issue is still reproducible on 0.63.0.

**Comment by khmakoto** [comment]
@sctamms do you want me to reopen this one?

**Comment by sctamms** [comment]
@khmakoto Just checked in with the team; we will move away from this dependency in the future so feel free to keep closed.
