### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by kbalakumar1** [microsoft/fluentui#21833]
### Environment Information

- **Package version(s)**: 
- @fluentui/react - 8.48.1
- react - 17.0.2
-  styled-components - 5.3.3
- @cseo/controls - 3.5.1
- @cseo/styles - 1.4.1
- **Browser and OS versions**: Microsoft Edge 

### Please provide a reproduction of the bug in a codepen:
I don't have any reproduction steps of the bug in codepen. It's happening locally in my machine.

#### Actual behavior:

The application doesn't start locally when using the command - npm start and throws the following exception in Fluent UI file:

![image](https://user-images.githubusercontent.com/96314696/155230064-f9ee1f86-d625-4857-9ada-b80854b8d319.png)

The line in styleToClassName.js that it throws the exception is:

![image](https://user-images.githubusercontent.com/96314696/155230166-5288fc26-4237-4d6d-a974-e2358befbb3c.png)

Couple of warnings in the browser console regarding __spreadArray:

![image](https://user-images.githubusercontent.com/96314696/155230896-a9674f21-3f53-4298-b30d-6b08cdac3851.png)

#### Expected behavior:

The application loads without any errors or exceptions locally.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/sites affected: (if applicable)
This is preventing the Team from updating the version of a few packages that's currently resulting in an alert issue.

**Comment by vinuthakaranth** [comment]
I am facing the same issue with same set of errors. Any updated on this issue?

**Comment by sarahkang58** [comment]
Hi @vinuthakaranth Adding "tslib": "^2.3.0" to all our package.json files fixed this issue for us.  Hope that works for you?
