### ISSUE TITLE
Panel isHiddenOnDismiss incorrectly set to true on closed Panel, causing entire screen to be read "blank"

### ISSUE THREAD

**Issue by WonSong** [microsoft/fluentui#21843]
### Environment Information

- **Package version(s)**: Test with 8.40.0 and 8.56.0
- **Browser and OS versions**: (fill this out) Any version of Chrome & Edge

### Describe the issue:

Had an issue where using Panel was adding aria-hidden to sibling nodes making the site unreadable by screen readers. Created a brand new CRA app with the latest fluent ui package, and was able to reproduce the issue

useHideSiblingNodes hook in Popup seems to be the culprit

### Please provide a reproduction of the issue in a codepen:

![Screen Shot 2022-02-23 at 8 21 07 AM](https://user-images.githubusercontent.com/5981331/155363107-d6b901fc-175d-4579-9adb-7db999b23f5d.png)

![Screen Shot 2022-02-23 at 8 36 24 AM](https://user-images.githubusercontent.com/5981331/155364278-f8b4786c-6b34-459a-8f7a-f75cfa932b61.png)

![Screen Shot 2022-02-23 at 8 15 03 AM](https://user-images.githubusercontent.com/5981331/155363205-3d6a6978-c0ba-4cb0-be9d-e065f7d9f04f.png)

#### Actual behavior:

Aria-hidden is added to all child elements of Body except script, style and Template

#### Expected behavior:

Should not add aria-hidden to elements that contains contents

### Documentation describing expected behavior

N/A

**Comment by cschlechty** [comment]
I'm guessing this is due to the "isHiddenOnDismiss" property of the panel, since it doesn't remove the panel or the overlay stack, which is normally what triggers the resetting of aria-hidden.

**Comment by WonSong** [comment]
I confirmed what @cschlechty is correct. However, this happens even when the panel was never opened.
