### ISSUE TITLE
Visual indication that a Pivot Item is disabled

### ISSUE THREAD

**Issue by kofrimpong** [microsoft/fluentui#21846]
#### Describe the feature that you would like added

Ability to disable a pivot item

#### What component or utility would this be added to

Pivot

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

There is currently no pivot item property to mark it as disabled. The only option is to use the `headerButtonProps`. Setting the `disabled` property to true does not visually mark the button as disabled. The cursor is still a pointer and hovering over the button changes the background color which shouldn't be.

**Comment by Vertamin** [comment]
Yeah, definitely need this one!

**Comment by yambtz** [comment]
vote +1

**Comment by mmol1** [comment]
I'm missing this basic feature too.
