### ISSUE TITLE
RTL affects vertical cross axis offsets for popper

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#21840]
### Environment Information

- **Package version(s)**: v9 and v0

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/elastic-banach-78uu1p?file=/example.tsx

#### Actual behavior:

The current offset modifier used in `usePopper` will always invert the offset of the cross axis for all placements.

https://github.com/microsoft/fluentui/blob/f8cf163d50469e9457aab009ec6f1801a9da804b/packages/react-positioning/src/usePopper.ts#L81-L90

This means that even if the cross axis is vertical, the offset is inverted in RTL.

#### Expected behavior:

If the cross axis is vertical, then offset should be unchanged.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by ling1726** [comment]
Will be easier to fix with Floating UI in #21828 since middleware can be wrapped.

Fixing this with Popper v2 involves writing an extra modifier or rewriting the offset modifier

**Comment by atomiks** [comment]
FWIW Floating UI will handle all of this by default in the next version 😄  and it's coming up to a fully stable v1 release very soon. RTL, alignments and offsets will work logically rather than physically as expected.

**Comment by ling1726** [comment]
> FWIW Floating UI will handle all of this by default in the next version 😄 and it's coming up to a fully stable v1 release very soon. RTL, alignments and offsets will work logically rather than physically as expected.

Thx for the tip @atomiks, I see some code in the Floating UI repo dealing with rtl... Just a QQ what is `logically` vs `physically` here ?

**Comment by atomiks** [comment]
"Logical" means it's not based on hardcoded physical properties like `top`, `left`, `right`, etc. It will adapt based on writing mode/language direction, alignment, etc in an intuitive way.

- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties
- https://github.com/floating-ui/floating-ui/discussions/1549

**Comment by ling1726** [comment]
> "Logical" means it's not based on hardcoded physical properties like `top`, `left`, `right`, etc. It will adapt based on writing mode/language direction, alignment, etc in an intuitive way.
> 
> * https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties
> * [Direction-agnostic placement values floating-ui/floating-ui#1549](https://github.com/floating-ui/floating-ui/discussions/1549)

Ah ok, that's more or less what we've wrapped around Popper, good to see it's getting first class support :)
