### ISSUE TITLE
Add static class names to all slots

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#21847]
This tracks implementing the slot class names RFC:
* https://github.com/microsoft/fluentui/pull/21206

Work required:
* [x] Add helper type:
  ```ts
  export type ClassNames<Slots> = {
    [SlotName in keyof Slots]-?: string;
  };
  ```
  * In #21933
* [x] Add conformance test to verify class names
* [x] Add `{component}ClassNames` export, and static class names to the slots of:
  * [x] Component template: `use{{componentName}}Styles.ts.hbs`
  * [x] `@fluentui/react-accordion` - Accordion, AccordionHeader, AccordionItem, AccordionPanel
  * [x] `@fluentui/react-avatar` - Avatar
  * [x] `@fluentui/react-badge` - Badge, CounterBadge, PresenceBadge
  * [x] `@fluentui/react-button` - Button, CompoundButton, MenuButton, SplitButton, ToggleButton
    * In #20977 
  * [x] `@fluentui/react-card` - Card, CardFooter, CardHeader, CardPreview
  * [x] `@fluentui/react-checkbox` - Checkbox
  * [x] `@fluentui/react-combobox` - Combobox, ComboButton, Listbox, Option, OptionGroup
  * [x] `@fluentui/react-dialog` - Dialog
  * [x] `@fluentui/react-divider` - Divider
  * [x] `@fluentui/react-image` - Image
  * [x] `@fluentui/react-input` - Input
  * [x] `@fluentui/react-label` - Label
  * [x] `@fluentui/react-link` - Link
  * [x] `@fluentui/react-menu` - MenuDivider, MenuGroup, MenuGroupHeader, MenuItem, MenuItemCheckbox, MenuItemRadio, MenuList, MenuPopover, MenuSplitGroup
  * [x] `@fluentui/react-popover` - PopoverSurface
  * [x] `@fluentui/react-provider` - FluentProvider
  * [x] `@fluentui/react-radio` - Radio, RadioGroup
  * [x] `@fluentui/react-select` - Select
  * [x] `@fluentui/react-slider` - Slider
  * [x] `@fluentui/react-spinbutton` - SpinButton
  * [x] `@fluentui/react-spinner` - Spinner
  * [x] `@fluentui/react-switch` - Switch
    * In #21933 
  * [x] `@fluentui/react-tabs` - Tab, TabList
  * [x] `@fluentui/react-text` - Body, Caption, Display, Headline, LargeTitle, Subheadline, Text
  * [x] `@fluentui/react-toolbar` - Toolbar, ToolbarButton, ToolbarDivider
  * [x] `@fluentui/react-tooltip` - Tooltip
* [x] Export all static class name objects from root of `@fluentui/react-components`

**Comment by micahgodbolt** [comment]
are there any details on how to add the conformance tests?

**Comment by spmonahan** [comment]
Looks like it needs to be two tests. There are existing conformance tests for the single root className but I'm thinking these should be dropped in favor of two tests to handle this new requirement. Tests are:

1. Does the component export a `<ComponentName>classNames` object
2. Does that object have the expected keys
