### ISSUE TITLE
GroupedList should support groups and items on the same level 

### ISSUE THREAD

**Issue by luiscantero** [microsoft/fluentui#21851]
The current GroupedList only supports having groups or items inside of a group, it cannot have both. To create an Explorer-type of application, we need the ability to render folders and files on the same level.

**Comment by OliverKK** [comment]
Hello @tomi-msft ,
how is the progress on this? 
Did you plan to implement this solution soon?

Regards Oliver

**Comment by luiscantero** [comment]
We are still blocked by this limitation and might even be forced to use a 3rd party solution, any news?
CC @cristipogacean

**Comment by gavinyeah** [comment]
Hi @tomi-msft ,
How is the progress on this? Any plan?

**Comment by luiscantero** [comment]
@khmakoto can you please help us get this issue reviewed or at least some form of feedback.

**Comment by veniti** [comment]
Tree View would be amazing, now I have some weird workaround.

**Comment by micahgodbolt** [comment]
We are working on a Tree in the v9 package. This is not something we plan to add to our old GroupList

**Comment by luiscantero** [comment]
FYI @hansgschossmann
