### ISSUE TITLE
DetailsList - Basic example doesn't render rows on SSR

### ISSUE THREAD

**Issue by gilhanan** [microsoft/fluentui#21856]
We are using the [DetailsList - Basic](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic) component from the examples as is in our SSR application but the SSR rendering works partially: only the columns are getting rendered, but the contents of the rows are empty and getting rendered only in the client.

#### Actual behavior:
![image](https://user-images.githubusercontent.com/5566282/155547536-1a88ab8d-6d23-4b0a-9ce6-cb1c637a78eb.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/5566282/155547293-c8e97dd7-3894-4777-9698-5e31cac11aa4.png)

**Comment by ilankhirin** [comment]
I was able to reproduce this issue on a clean template using React SSR: https://github.com/ilankhirin/fluent-ui-ssr-issue
Just clone the repo, npm i and then "npm run start:server".
If you inspect the returned document you'll see that the table is returned with no data:
![image](https://user-images.githubusercontent.com/22425615/160287134-8b04035c-ee50-47a1-89af-e96c56d59ab3.png)

@tomi-msft Can you please assign someone to take a look? Maybe we only need to turn on/off a flag for it work.
I went over the docs but didn't find something that solved the issue.
