### ISSUE TITLE
GroupedList: Cannot set data- attributes for groups

### ISSUE THREAD

**Issue by luiscantero** [microsoft/fluentui#21850]
In order to run UI tests (e.g. using PlayWright), we need a way to attach meta information (e.g. a key) to groups and items. We can attach data- attributes to a DetailsRow, but we cannot do the same for groups.

A possible workaround is to create a custom [onRenderTitle](https://github.com/microsoft/fluentui/blob/3dbb57b1e6940df2d4039f61a35d961bcb8560c3/packages/react/src/components/GroupedList/GroupHeader.base.tsx#L255), however this is very cumbersome and we lose styling information.

It would be great to be able to attach data- attributes to groups, the same as it is possible for items (DetailsRow).

**Comment by luiscantero** [comment]
This issue still exists.

**Comment by khmakoto** [comment]
@luiscantero do you want me to reopen the issue, then?

**Comment by luiscantero** [comment]
In case somebody needs a workaround:
```
const groupProps: IGroupRenderProps = useMemo(() => ({
    onRenderHeader: (props?: IGroupHeaderProps): JSX.Element => (
        <GroupHeader
            ...
            // Expand button: Show key as tooltip and use name as aria-label.
            expandButtonProps={{
                "aria-label": props!.group!.name,
                title: props!.group!.key,
            }}
        />
    ),
    ...
}), [...]);
```
