### ISSUE TITLE
Document the use of <Text> as primitive

### ISSUE THREAD

**Issue by Pixelatex** [microsoft/fluentui#21880]
#### Describe the feature that you would like added

Not really a feature but there is documentation missing for the `<Text>` as component/primitive use case. The generated typescript helpers for what input is expected doesn't help much either. 

#### What component or utility would this be added to

https://developer.microsoft.com/en-us/fluentui#/controls/web/text

#### Have you discussed this feature with our team, and if so, who

no

#### Additional context/screenshots

no

**Comment by micahgodbolt** [comment]
@Pixelatex can you be a bit more specific about what is missing?
