### ISSUE TITLE
CommandBar cannot resize properly when it is put under a zoomed container

### ISSUE THREAD

**Issue by JiuqingSong** [microsoft/fluentui#21888]
### Environment Information

- **Package version(s)**: latest (from the code pen demo)
- **Browser and OS versions**: windows 11

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/songthin/pen/eYePQOb

#### Actual behavior:

Create a commandbar, and put under a zoomed container, e.g. (same with the code pen link above):

```html
<div style="transform: scale(0.5);transform-origin: left top; height: calc(200%); width: calc(200%);)">
  <div id="content"></div>
</div>
```

Then resize this window, when the windows size is less then 2*[required size], the command bar is starting to shrink:

Before:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/23065085/156034914-5b54200a-3e82-494c-9bf0-ab34f26a7f46.png">

After:

![image](https://user-images.githubusercontent.com/23065085/156035014-73d34b40-bbbd-49b9-b4de-8afb00f2aa99.png)

#### Expected behavior:

The resizing logic should consider current zoom context, and use all available space to show the buttons.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) OWA. I have a workaround by assigning a faked width value "1/zoomScale * 100%" to make it work.

**Comment by micahgodbolt** [comment]
that's an interesting bug. what's the context for needing to transform the parent. Just curious.

**Comment by micahgodbolt** [comment]
Certainly makes sense. i'm assuming that when calculating if the current content fits, it doesn't take into account the zoom. Probably have similar issues if you increase the scale.

**Comment by JiuqingSong** [comment]
Exactly, when increase, the "..." button will be pushed to outside of the screen.
________________________________

**Comment by JiuqingSong** [comment]
And to make it easier to get zoom value, we can pass the scale number in as a property. e.g.:

<CommandBar zoomScale={0.5) ... />
________________________________

**Comment by micahgodbolt** [comment]
Well I found the culprit. scrollWidth ignores css scale, and returns the non scaled width

https://codepen.io/micahgodbolt/pen/dyZgLeK?editors=1111
