### ISSUE TITLE
Better Multi-Window Support

### ISSUE THREAD

**Issue by Jamie0** [microsoft/fluentui#21885]
#### Describe the feature that you would like added

We make use of multiple windows in our application, using React Portals to render components into Windows opened by `window.open`. Functionally, almost everything works (except for the odd minor event bubbling issue), except for component stylesheets. 

I currently work around this by attaching a `MutationObserver` to `<head />` and, every time a <link /> or <style /> tag changes, making a copy into the tracked open windows. This mostly works, but it would be great if this could be supported natively in the core. 

#### What component or utility would this be added to

Stylesheet

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

N/A

**Comment by micahgodbolt** [comment]
Do you have a repro of this issue to test? What version of Fluent are you using?

**Comment by Jamie0** [comment]
The project where I noticed this is still using a slightly old version of Fluent (7.162), but I can reproduce it on the 8.x branch. I don't have permission to share the snippet in question, but when I get some free time I'll create an example project that illustrates the problem.

**Comment by micahgodbolt** [comment]
> The project where I noticed this is still using a slightly old version of Fluent (7.162), but I can reproduce it on the 8.x branch. I don't have permission to share the snippet in question, but when I get some free time I'll create an example project that illustrates the problem.

Yeah, if we can get a codepen/codesandbox repro of the issue, we can talk about ways to address the issue and confirm if the solution actually works.
