### ISSUE TITLE
Use CSF for vr-tests

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#21891]
https://docs.saucelabs.com/visual/faq/#how-do-i-add-screener-steps-to-storybook-component-story-format-csf-stories

It's now possible to use component story format for screener and move away from the deprecated `addStory` API.

The advantage to using CSF is that it forces us to use React components, which allow us to use hooks properly. Using hooks inside `addStory`  is actually wrong and results in things like `useContext`  fail silently (easy repro - try to get `dir` value from `useFluent` )

**Comment by Hotell** [comment]
related https://github.com/microsoft/fluentui/issues/21779

**Comment by ling1726** [comment]
duplicate of #21779
