### ISSUE TITLE
Date Picker doesn't use themes correctly for the year

### ISSUE THREAD

**Issue by waterfoul** [microsoft/fluentui#21892]
### Environment Information

- **Package version(s)**: Fluent UI React 8.56.1
- **Browser and OS versions**: Edge 98.0.1108.62

### Describe the issue:

The Date picker does not honor the theme for the year

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/aichlmayr_fr/pen/rNYqovm

#### Actual behavior:

1. Visit the codepen
2. Open the picker
3. Observe: The year uses black text

#### Expected behavior:

The year uses the default font color, and not black

**Comment by micahgodbolt** [comment]
Yeah, looks like since year is a button that it's not inheriting the parent color

**Comment by micahgodbolt** [comment]
![image](https://user-images.githubusercontent.com/1434956/156059042-99208039-f22a-4b26-9684-7d24e56a45ec.png)
Yup, adding inherit works great. Could move the color down to the button, but this is the simplest change without possibly breaking others.
