### ISSUE TITLE
SwatchColorPicker tooltip doesn't support text spacing

### ISSUE THREAD

**Issue by ilanbd** [microsoft/fluentui#21908]
### Environment Information

- **Package version(s)**: 
8.49.6
- **Browser and OS versions**:
Microsoft Edge
Version 98.0.1108.56 (Official build) (64-bit)
Windows11

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/ilanbd/pen/MWOBJLb
1. Enter codepen
3. Use Stylus text spacing tool
2. Hover on a color
3. See that the tooltip doesn't support text spacing 

#### Actual behavior:
The tooltip doesn't support text spacing

#### Expected behavior:

The tooltip should support text spacing

### Documentation describing expected behavior

MAS Reference:
MAS 1.4.12

[MAS 1.4.12 – Text Spacing.docx (sharepoint.com)](https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7bFB620223-4D9E-4BBA-8822-AD30A499FB7E%7d&file=MAS%201.4.12%20%E2%80%93%20Text%20Spacing.docx&action=default&mobileredirect=true)

Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fforms.office.com%2fpages%2fresponsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-asimeena%40microsoft.com%7c02f070ec730f4635a81408d979cb0617%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637674735185347531%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=NlG4XpuUoZFr507Ur1HEU1dohkX2I8F2mmmBf58FYI0%3D&reserved=0)

**Comment by micahgodbolt** [comment]
The tooltips are native browser tooltips due to the aria-label on each of the SVGs. Does MAS 1.4.12 apply to browser tooltips?

**Comment by micahgodbolt** [comment]
> In content implemented using markup languages that support the following text style properties, no loss of content or functionality occurs by setting all of the following and by changing no other style property:

Native tooltips would not fall under this category.
