### ISSUE TITLE
eslint: introduce lint rule to prevent importing non `react-components` suite in stories

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#21907]
### Describe the issue:

We need to introduce lint rule for all v9 stories to mitigate cross-package import from non suite (react-components)

#### Actual behavior:

ATM when one needs to import cross-package in storybook modules, it is allowed to import  both per package or from suite.

```
// @filename demo.stories.tsx
import {Button} from '@fluentui/react-components'  // ✅
import {Text} from '@fluentui/react-text'  // ✅
```

#### Expected behavior:

Because we are exporting those stories to codesandbox and wanna follow best practices that we recommend to users, cross-package import for stories should include only import from `@fluentui/react-components`

```
// @filename demo.stories.tsx
import {Button} from '@fluentui/react-components' // ✅
import {Text} from '@fluentui/react-text'  // 🚨 lint error
```

**Comment by micahgodbolt** [comment]
After our discussion today, we might want to also add relative imports as well.
