### ISSUE TITLE
SplitButton has a11 issues

### ISSUE THREAD

**Issue by pedroafsouza** [microsoft/fluentui#21904]
### Environment Information
- Latest

### Describe the issue:
1. Go to https://developer.microsoft.com/en-us/fluentui#/controls/web/button.
2. Use Microsoft Accessibility Insights to FastPass.
3. Check the errros

#### Actual behavior:

There are many a11 issues on the split button feature for fluent ui.

![image](https://user-images.githubusercontent.com/957088/156193396-39ae64e3-dbb1-41d0-a8da-60820c3bd198.png)

#### Expected behavior:

There shouldn't be issues on the example, so we can follow the implementation.

### Documentation describing expected behavior

![image](https://user-images.githubusercontent.com/957088/156193423-10769e8f-197a-4cfc-8855-5c521537e5ea.png)

**Comment by micahgodbolt** [comment]
the only complain that Acc checker has is that Split button, being `role="button"` has  "...focusable descendants".

This appears to be a bug in acc checker because both buttons have a tabindex of `-1`

![image](https://user-images.githubusercontent.com/1434956/156263441-f6894431-d0d0-432e-b276-5f6f2251245a.png)

**Comment by pedroafsouza** [comment]
@micahgodbolt I have added a bug on the side => https://github.com/microsoft/accessibility-insights-web/issues/5222.

**Comment by shanisebarona** [comment]
Hi, Accessibility Insights here! We wanted to share that we do consider this an accessibility issue. This helpful explanation has more details regarding the nested-interactive rule failing with tabIndex= -1. https://github.com/dequelabs/axe-core/issues/3227#issuecomment-949684411.
