### ISSUE TITLE
Alert icon shrinks when text is too long

### ISSUE THREAD

**Issue by asherjh** [microsoft/fluentui#21911]
### Environment Information

- **Package version(s)**: 0.60.0
- Issue does not repro in 0.47.14 in Fluent UI docs, but does starting in 0.51.7
- **Browser and OS versions**: tested in Edge v100.0.1169.1 and Teams v1.5.00.5855

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/fluent-ui-example-forked-n9i23g?file=/example.js

#### Actual behavior:
The alert icon should remain the same size regardless of the length of the alert text

#### Expected behavior:
Instead, the icon shrinks relative to the length of the text after about one line, regardless of the actual computed width of the text box. For instance, the shrinking normally starts around when the text wraps to a second line, and as the second line gets longer (without changing the overall width of the text), the icon gradually shrinks to about 50% of the original size by the end of the second line.

#### Workaround:
The icon can be passed to the Box as children instead of content, which avoids the strange width computation from Box

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: unsure. Workaround used in Viva Insights Teams app

**Comment by micahgodbolt** [comment]
Looks like the icon in alert is missing a flex-shrink: 0
