### ISSUE TITLE
Is there a standalone type definition file (.d.ts) for all fluent code?

### ISSUE THREAD

**Issue by JiuqingSong** [microsoft/fluentui#21925]
If I'd like to use fluent ui from CDN, e.g.

<script src="//unpkg.com/@fluentui/react@8/dist/fluentui-react.js"></script>

I expect to import from a .d.ts file just like we use react from "@types/react"? 

Thanks.

**Comment by micahgodbolt** [comment]
Does this work? https://unpkg.com/browse/@fluentui/react@8.56.3/dist/react.d.ts

Also, I hope this is only for testing/prototyping as the library is quite large without tree shaking.

**Comment by JiuqingSong** [comment]
Thanks, yes, that is what I'm looking for.
