### ISSUE TITLE
Text component does not update coloring with component level theme setting

### ISSUE THREAD

**Issue by Zeddox** [microsoft/fluentui#21967]
### Environment Information

- **Package version(s)**: 8.57.1
- **Browser and OS versions**:  Edge - Windows 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/zeddox/pen/qBVgGJY

#### Actual behavior:

The Text component receives coloring from the variant theme and no coloring from the component override

#### Expected behavior:

Component level theming is applied to the Text component

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Blocking

Products/sites affected: Internal Microsoft application

### Note:
In version 8.56.0 this was working for us. We need to take 8.57.1 for an a11y bug fix.
It appears the Text component is not using the styled HOC that other components are using, and the createComponent HOC is using the Customizer?

**Comment by andrefcdias** [comment]
Hey @Zeddox! I was able to reproduce this issue but found that this was also not working for version 8.56.0, so can you confirm that it was working for that version?
In parallel, I will be spinning up a PR with a fix for this, just need to validate the solution with the rest of the team.

**Comment by Zeddox** [comment]
@andrefcdias as far as I can tell this is working for us with that version. I did see the issue in builds prior to 8.56.0 (I don't recall the exact version number). Thanks for your investigation!

**Comment by Zeddox** [comment]
@andrefcdias after looking at your draft PR, I see that I missed adding the root style set. Adding that in the codepen solves the issue. I'm still facing the styling not picking up in our app (we're using root there, `theme.components.Text.styles.root`). 

I'll do some further debugging and see if it is a package cache issue or if I can replicate the behavior in a pen.

**Comment by Zeddox** [comment]
@andrefcdias, as mentioned, I'm experiencing this issue in our app (even with the root style set). I'm not sure why the codepen (and codesandbox) behave differently. _I did delete my node_modules and clean my npm cache as a check_

In our app I've put breakpoints in createComponent and in getSlots. The theme object that is passed to getSlots from within TextView, does not contain a components property. In a codesandbox I created, I can set a breakpoint and see a components property.

From what I gather, it looks like [createComponent is using a default CustomizerContext](https://github.com/microsoft/fluentui/blob/9d0611016f1e6f5a39b105df1d6e85beecb1e469/packages/foundation-legacy/src/createComponent.tsx#L55) and not reading from ThemeProvider. Thoughts?

**Comment by Zeddox** [comment]
Closing this, I've cloned to a different repo and do not see this issue. Thanks @andrefcdias for looking into it originally.
