### ISSUE TITLE
Teaching Bubble Primary Button placement doesn't match "Best Practices" docs or Dialog component examples

### ISSUE THREAD

**Issue by hoovercj** [microsoft/fluentui#21978]
#17028 is still a problem.

The Best Practices documentation for [Teaching Bubble](https://github.com/microsoft/fluentui/blob/cb6c569246b6c3e4e9b89c94f39e17ee043fe22f/packages/react-examples/src/react/TeachingBubble/docs/TeachingBubbleBestPractices.md) states:

> Always place the primary button on the left, the secondary button just to the right of it.

Note: This guidance is also present in the [Button component docs](https://github.com/microsoft/fluentui/blob/cb6c569246b6c3e4e9b89c94f39e17ee043fe22f/packages/react-examples/src/react/Button/docs/ButtonBestPractices.md).

[The implementation of Teaching Bubble](https://github.com/microsoft/fluentui/blob/0de01d003589b5e2f166bc070729dca20125a091/packages/react/src/components/TeachingBubble/TeachingBubbleContent.base.tsx#L128)[](https://user-images.githubusercontent.com/2957173/108197743-14166600-711b-11eb-86f2-ccf398415594.png)[](https://user-images.githubusercontent.com/2957173/108198422-e41b9280-711b-11eb-823c-1926cb8dae1f.png) puts the primary button on the right and the secondary button on the left:

```
  if (primaryButtonProps || secondaryButtonProps || customFooterContent) {
    footerContent = (
      <Stack className={classNames.footer} horizontal horizontalAlign={customFooterContent ? 'space-between' : 'end'}>
        <Stack.Item align="center">{<span>{customFooterContent}</span>}</Stack.Item>
        <Stack.Item>
          {secondaryButtonProps && <DefaultButton {...secondaryButtonProps} className={classNames.secondaryButton} />}
          {primaryButtonProps && <PrimaryButton {...primaryButtonProps} className={classNames.primaryButton} />}
        </Stack.Item>
      </Stack>
    );
  }
```

This is also inconsistent with the placement of the buttons in the Dialog component examples which follow the guidance and put the primary button on the left. See screenshots below:

![image](https://user-images.githubusercontent.com/2957173/157014830-62b5545c-5fc5-408d-b038-46fa361e56a6.png)

![image](https://user-images.githubusercontent.com/2957173/157014840-06db2655-9990-4855-b1bb-9ac08c74aa6a.png)

**Comment by micahgodbolt** [comment]
@sopranopillow let's update the website example to match best practices.

**Comment by sopranopillow** [comment]
Will work on it today
