### ISSUE TITLE
[Persona] Text color does not respect styles

### ISSUE THREAD

**Issue by QuSimone** [microsoft/fluentui#21983]
### Environment Information

- **Package version(s)**: ^8.0

#### Actual behavior:

From https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Persona/Persona.types.ts

Persona exposes interface `IPersonaProps`. This has a field `styles`, which may be `IPersonaStyleProps` or `IPersonaStyles`. We specify `IPersonaStyles` to customize the Persona initials color on rest, hover etc. 
![image](https://user-images.githubusercontent.com/72839029/157119620-0befee2f-548f-4a71-9695-9138d7bb1de0.png)
https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Persona/Persona.types.ts#L207

`IPersonaStyles` has the following fields:
![image](https://user-images.githubusercontent.com/72839029/157119722-cf85d515-57b4-439b-9023-da2d4678dae8.png)
https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Persona/Persona.types.ts#L270

None of these fields have any effect on the persona text color. It appears this is deprecated. We instead select the <span> element directly and override the text color that way. 

#### Expected behavior:

I am requesting an update to `IPeronsaStyles` to include fields that will style the Persona as expected.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Low)

Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
Persona and coin text styles appear to be working fine. Here's an example of how you can target the initials, which are part of the Coin

https://codepen.io/micahgodbolt/pen/QWaBvYy?editors=0010
