### ISSUE TITLE
Review Input Control Compatibility with Popular React Form Libraries

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#21985]
Leading into the RC release for input controls we want to verify that these controls can be used with popular React form libraries.

1. [x] [Formik](https://formik.org/) - @khmakoto to review
2. [x] [React Hook Form](https://react-hook-form.com/) - @khmakoto to review
3. [x] [Redux Form](https://redux-form.com/8.3.0/) - @spmonahan to review
4. [x] [JSON Forms](https://jsonforms.io/) - @spmonahan to review

## Acceptance Criteria
For each library:
1. [x] Verify Fluent UI vNext input controls work with the library (assuming they work)
2. [x] Produce a list of issues that prevent controls from working or could be made smoother (assuming there are any)
3. [x] Produce a basic demo Create React App/CodeSandox/Codepen application of Fluent controls working with the form library

## Out of Scope
1. Making any changes to Fluent controls to make them work with a particular library (just document issues, if we need changes we will follow up with a different ticket)
2. Producing any Fluent documentation about how controls work with a particular library

**Comment by spmonahan** [comment]
## Redux Form

[Example Codesandbox App](https://codesandbox.io/s/redux-form-fluent-ui-v9-evdkkf?file=/src/ReduxForm/ReduxForm.tsx)

Controls used:

- react-input
- react-radio (RadioGroup and Radio)
- react-switch
- react-slider
- react-checkbox

All of the controls tested work in that they render correctly, can have things like default values provided and work with the native validation behavior. In my example I used a variety of controls some that have built in labels like Checkbox and Switch and others that do not like Slider and Input. I was able to use all without any issues.

**Comment by spmonahan** [comment]
## JSON Forms

[Example CodeSandbox App](https://codesandbox.io/s/jsonforms-fluent-ui-v9-t0rs87?file=/src/JSONForms/InputControl.tsx)

Controls used:

-react-input
- react-radio (RadioGroup and Radio)
- react-switch
- react-slider
- react-checkbox
- 
All of the controls tested work in that they render correctly, can have things like default values provided. In my example I used a variety of controls some that have built in labels like Checkbox and Switch and others that do not like Slider and Input. I was able to use all without any issues.

I did not test validation behavior in this application. I found the docs were a bit light in this area and I could not find a validation example in Github. I'm confident validation could be applied using JSON Forms though.

**Comment by khmakoto** [comment]
## Formik

[Example CodeSandbox App](https://codesandbox.io/s/input-controls-with-formik-qcx1q6?file=/src/App.tsx)

Controls used:

- react-input
- react-radio (RadioGroup and Radio)
- react-switch
- react-slider
- react-checkbox

All of the controls tested work in that they render correctly, can have things like default values provided and work with the native validation behavior. In my example I used a variety of controls some that have built in labels like Checkbox and Switch and others that do not like Slider and Input. I was able to use all without any issues.

**Comment by khmakoto** [comment]
## Formik

[Example CodeSandbox App](https://codesandbox.io/s/input-controls-with-react-hook-forms-d7ljb6?file=/src/App.tsx)

Controls used:

- react-input
- react-radio (RadioGroup and Radio)
- react-switch
- react-slider
- react-checkbox

All of the controls tested work in that they render correctly, can have things like default values provided and work with the native validation behavior. In my example I used a variety of controls some that have built in labels like Checkbox and Switch and others that do not like Slider and Input. I was able to use all without any issues.
