### ISSUE TITLE
React-Tooltip: Add demo for styling tooltip

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#21997]
It's not obvious that styling the tooltip requires classNames to be passed to the content slot. Instead of changing the component behavior (as originally), this issue is now about adding a demo to show users how to style a tooltip.

**Comment by micahgodbolt** [comment]
So this is an accepted limitation of the tooltip, and styling will need to be done to the content slot? If so, that's fine. I'll create a demo to show how you can do that.

**Comment by layershifter** [comment]
> Right now if you pass className into the tooltip root, the class is ignored.

TypeScript also should throw as `className` is not the props shape.

![image](https://user-images.githubusercontent.com/14183168/157284764-707e65d1-0d8a-4b81-85b8-34aad55736d2.png)

https://codesandbox.io/s/dazzling-dan-yuubm1?file=/example.tsx

**Comment by layershifter** [comment]
> So this is an accepted limitation of the tooltip, and styling will need to be done to the content slot? If so, that's fine.

Yes, it's intentional as other triggers don't accept props. For example, you can pass anything to `MenuTrigger` or `PopoverTrigger`.

**Comment by micahgodbolt** [comment]
Ok, not sure why className isn't throwing in codesandbox, but i see it throwing in vscode

![image](https://user-images.githubusercontent.com/1434956/157287651-ece8ee99-775c-486b-b1e2-db5e6e189e1e.png)

I'll change this issue to creating a quick demo on styling the tooltip
