### ISSUE TITLE
Narrator for CommandBar announces message twice when selecting option in menu

### ISSUE THREAD

**Issue by mohona17** [microsoft/fluentui#22005]
### Environment Information

- **Package version(s)**: 9.0.0-rc.3
- **Browser and OS versions**: Windows, Version 98.0.1108.43 (Official build) (64-bit)

### Describe the issue:

Narrator announces menu item information twice when selecting an option

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/mohona17/pen/KKyLbNq

#### Actual behavior:
When you select an option, "CommandBar key menu item, collapsed, 1 of 2, has popup" is announced twice. Once for the previously selected option, once for the newly selected option.

Overall after selection, it reads:
CommandBar ariaLabel,
CommandBar key, menu item, collapsed, 1 of 2, has popup,
CommandBar key menu item, collapsed, 1 of 2, has popup

In the codepen example:
'Inbox actions, New, menu item, collapsed, 1 of 2, has popup. New, menu item, collapsed, 1 of 2, has popup'

If we update the CommandBar key with the text of each item, the first time CommandBar key is announced with the previous option and the second time the key is the new option. 

#### Expected behavior:

Expecting narrator to announce once, with the new key. 
CommandBar ariaLabel, CommandBar key, menu item, collapsed, 1 of 2, has popup

**Comment by micahgodbolt** [comment]
I can't repro this at all. It works fine for me. Which browser are you using? Edge? I don't get any double announcing.
