### ISSUE TITLE
[Accessibility] Narrator not announcing complete text on callout component

### ISSUE THREAD

**Issue by PrashantMicrosoft** [microsoft/fluentui#22018]
### Environment Information

- **Package version(s)**: 8.60.1 (latest)
- **Browser and OS versions**: Microsoft Windows 10 Enterprise Version 21H1(OS build:19043.1237)
Microsoft edge Version 97.0.1069.0 (Official build) dev (64-bit)

### Describe the issue:
In Edge , Narrator is not announcing complete text that we have on our callout component. It just announces partial content.

### Please provide a reproduction of the issue in a codepen:
Repro in codepen: https://codepen.io/GayatriDeviP/pen/dyZBvPQ
Repro steps:

1. Go to the codepen, Navigate to the Show callout button in codepen.
2. Turn on the Narrator
3. Click on button / press enter, verify whether Screen reader announcing entire callout content placed.

#### Actual behavior:

Narrator is reading partial content.

#### Expected behavior:

It should read full content of callout component

### Documentation describing expected behavior

https://developer.microsoft.com/en-us/fluentui#/controls/web/callout

**Comment by micahgodbolt** [comment]
This is expected behavior. Just because you move focus to a new element doesn't mean that narrator is going to read out that entire DOM. If but button is described by that callout, you can use aria-described by, keep focus on the button, and the entire callout will be read.

**Comment by micahgodbolt** [comment]
you need to turn off `setInitialFocus` otherwise focus moves away from the button, and the label is no longer being read.

**Comment by PrashantMicrosoft** [comment]
I have tried by putting aria-describedby and removed setInitialFocus but the issue persists.
Please note that: It is announcing the content of callout but partially not fully.
Code link: https://codepen.io/GayatriDeviP/pen/dyZBvPQ

**Comment by micahgodbolt** [comment]
not sure that button has a "prop" for those values. Just use the aria-labeledby directly https://codepen.io/micahgodbolt/pen/WNXVYPq?editors=0010
