### ISSUE TITLE
Get the right getGroupHeight for long lists on ShimmeredDetailsList. The list jumps all the time while scrolling

### ISSUE THREAD

**Issue by AlbertodAragon** [microsoft/fluentui#22033]
### Environment Information

- **Package version(s)**: (17.0.2)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

List combined with groups, single lines and virtualization has a problem with extraction the getGroupHeight  as they have an erratic behaviour.

#### Expected behavior:

Get the right getGroupHeight to be able to scroll correctly.

### Priorities and help requested:

Are you willing to submit a PR to fix? ( No)

Requested priority: (Blocking) -> as we can not see the data on long lists

**Comment by micahgodbolt** [comment]
Can you provide a repro of this behavior?
