### ISSUE TITLE
Fluent UI React DetailList Selection Mantener Items pre seleccionados al marcar / desmarcar todos

### ISSUE THREAD

**Issue by jysalazar** [microsoft/fluentui#22037]
Hola, estoy intentando personalizar un MarqueeSelection -> DetailsList de selección multiple con items pre seleccionados sin opción para marcar (disabled), navegando encontré el método onRenderCheck para configurar el disabled y selected con `selection.setKeySelected(item.key, true, false);` y `data-selection-disabled`, el inconveniente es que al momento de marcar en el check general del encabezado todos los elementos y desmarcar se pierde los que inicialmente ya venían pre cargados, alguna sugerencia de donde validar para que en el desmarque no se considere algunos elementos de acuerdo a alguna variable que provenga de las columnas, intenté con la opción `selected={item ? !item.isChecked : false}` sin embargo, logro mantener los iniciales pero no pero me permite marcar los nuevos

```typescript
const onRenderCheck = (props: IDetailsRowCheckProps, item: IBase) => {
      const customStyles: Partial<IDetailsRowCheckStyles> = {};
      /* customStyles.root = { backgroundColor: 'rgba(255, 0, 0, 0.4)' }; */

          const warningButtonTheme: ITheme = createTheme({
          palette: {
              themePrimary: (!item.isChecked) ? theme.palette.neutralQuaternaryAlt : theme.palette.themePrimary,
          },
      })

      if (!item.isChecked) {
          /* console.log('separator');
          console.log(item.nombres + ' ' + item.key); */
          selection.setKeySelected(item.key, true, false);
      }

      /* console.log(item); */

      return <DetailsRowCheck {...props}
          aria-label="custom label based on props"
          /* selected={item ? !item.isChecked : false} */
          data-selection-disabled={!item.isChecked}
          styles={customStyles}
          theme={warningButtonTheme}
          />;
 }
```

**Comment by foxxycodes** [comment]
我不會說西班牙語。但祝你好運:)

**Comment by khmakoto** [comment]
Here's the text translation in English:

> Hello, I'm trying to customize a MarqueeSelection -> DetailsList of multiple selection with preselected items that don't have an option to be selected/unselected (they are disabled). While navigating the website I found the `onRenderCheck` method to configure `disabled` and `selection.setKeySelected(item.key, true, false)` to configure `selected` and `data-selection-disabled`. The problem I'm having is that whenever I click on the general check in the header to unselect I lose all of the pre-selected items. Do you have any suggestions on how I could validate this so that whenever I unselect the general check in the header it does not consider some elements according to maybe some prop coming from the columns? I tried the option `selected={item ? !item.isChecked : false}` however, while this allows me to keep the initial preselected elements it forbids me from selecting new ones.
