### ISSUE TITLE
Component styling of MessageBar icon is overridden by component styling of Icon

### ISSUE THREAD

**Issue by Zeddox** [microsoft/fluentui#22075]
### Environment Information

- **Package version(s)**: 8.56.0
- **Browser and OS versions**: Edge - Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/zeddox/pen/XWVrOrV

#### Actual behavior:

Component styling for the `Icon` is overriding the component styling of the `MessageBar`'s icon.

#### Expected behavior:

`MessageBar` icon component styling takes precedence over the icon component styling.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Blocking - We have different coloring for message bar icons based on light/dark mode and have an accessibility bug logged for this icon coloring issue

Products/sites affected: Internal Microsoft application

**Comment by micahgodbolt** [comment]
I'm not sure if this is something we'd be able to support, as this is how component customization is supposed to work.

If you need a parent to be able to enforce a sub-component styling, you can provide a more specific parent selector


```
styles: {
        root: { 
          color: 'darkred',
          "& i" :{
            color: 'darkred'
          }
        },
      }
```

![image](https://user-images.githubusercontent.com/1434956/162813704-f6d676b6-f5a4-413a-a0c9-e9a432bb408f.png)

**Comment by Zeddox** [comment]
> 

Thanks @micahgodbolt for the reply. This is what we've done. 

Given that this is the only way to override the icon style, is the icon property on `IMessageBarStyles` irrelevant?

**Comment by micahgodbolt** [comment]
The icon works fine as long as you aren't overriding all <Icon> controls globally. I'd suggest using those global overrides as a last resort, especially for those atomic controls that get reused a ton in other controls.
