### ISSUE TITLE
Navigation is not happening with Narrator on Tree control

### ISSUE THREAD

**Issue by mmuditmittal** [microsoft/fluentui#22082]
**Issue:-** When we are expanding or collapsing the tree using left/right arrow then navigation is not working with Narrator.

https://businessappfabric.azurewebsites.net/#component=id__26

![image](https://user-images.githubusercontent.com/29143311/158103780-7124ceef-25f5-4516-b255-60ca8cff415c.png)

**Comment by micahgodbolt** [comment]
These are not fluent ui controls
