### ISSUE TITLE
IContextualMenuItem or IContextualMenuItemProps does not take in aria attributes

### ISSUE THREAD

**Issue by natalieethell** [microsoft/fluentui#22092]
### Environment Information

- **Package version(s)**: Current version
- **Browser and OS versions**: Edge, Chrome

### Describe the issue:

We're unable to pass certain aria attributes into items in a command bar. We would like to pass the `aria-pressed` attributes to these items when they're checked, however, the interface does not take these.

I was wondering if you would consider extending these interfaces from `React.HTMLAttributes<HTMLDivElement>` so that we can pass in these aria attributes, and/or add another aria prop directly to the interface, as you have with `ariaDescribedBy` and `ariaDescription`.

Here is the aria documentation for the aria-pressed attribute: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-pressed.

Thanks!

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/natalieethell/pen/ZEvYRPv. The item in question is the "New" button.

#### Actual behavior:

Cannot pass in aria attributes into items in a command bar.

#### Expected behavior:

Would expect to be able to pass aria attributes into items in a command bar beyond just aria-described-by, aria-description, and aria-label.

**Comment by micahgodbolt** [comment]
It looks like you can only use aria-pressed if you use the `role=checkbox`

https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Button/BaseButton.tsx#L244

**Comment by micahgodbolt** [comment]
to that point, you should just be using the `checked` value instead of manually setting aria values here

**Comment by natalieethell** [comment]
I tried passing in the `checked` boolean, but it seems like that's not enough for the screen reader to read out "checked" or "pressed", as I would expect for a checked button. I would assume it adds some kind of aria value to the root element to designate that it's checked or pressed.

**Comment by micahgodbolt** [comment]
Ok, for aria-pressed it looks like you need to use the `toggle` button from https://developer.microsoft.com/en-us/fluentui#/controls/web/button

When toggle flag is true, checked will invoke aria-pressed. 

otherwise, if you want to use aria-checked, make sure the button is a role 'menuitemcheckbox'

**Comment by natalieethell** [comment]
Perfect, thanks so much @micahgodbolt !!
