### ISSUE TITLE
Add required tag to dropdown component

### ISSUE THREAD

**Issue by jasonburnsmicrosoft** [microsoft/fluentui#22090]
#### Describe the feature that you would like added

Add an option required tag for dropdown components.  The same as the required tag for Input components, it should require the user to make a selection from the list of available items.  

#### What component or utility would this be added to

Dropdown, FormDropdown

#### Have you discussed this feature with our team, and if so, who

N/A

#### Additional context/screenshots

https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown
Should match the required type in the other fluent ui library.  Should also be noticed and spoken by the screen reader and say that the field is required.

**Comment by micahgodbolt** [comment]
Dropdown already supports required

![image](https://user-images.githubusercontent.com/1434956/159597959-09f7577f-0b7d-4df0-8e80-8658ef7095db.png)


is there a problem with the current implementation?

**Comment by jasonburnsmicrosoft** [comment]
Ah, my mistake.  Specifically the react-northstar implementation does not yet have the required tag.
