### ISSUE TITLE
Menu buttons are not actually disabled

### ISSUE THREAD

**Issue by dolevoper** [microsoft/fluentui#22101]
### Environment Information

- **Package version(s)**: 8.61.1

### Please provide a reproduction of the bug in a codesandbox:

https://codesandbox.io/s/pensive-boyd-806wbk?file=/src/App.tsx

#### Actual behavior:

Button is not disabled, it is only given the attribute "aria-disabled" and seems like the onClick callback handler is removed.

#### Expected behavior:

Button should actually be disabled, not even triggering form events like submit/reset.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

---

In the minimal repro provided you can see that form events are not blocked when the button is disabled.
This feature is important in case the command bar is actually in a different component than the component rendering the form (for example when building a main-detail type of view).
We are using a workaround of also setting "pointer-events" to "none" when we want the button to be disabled.

Another problem with the current implementation, when testing using react-testing-library, the button is not considered disabled.
So the following expectation would fail:
```typescript
expect(screen.getByRole("menuitem", { name: /save/i })).toBeDisabled();
```
The workaround we use for this problem is asserting against the "aria-disabled" attribute instead:
```typescript
expect(screen.getByRole("menuitem", { name: /save/i })).toHaveAttribute("aria-disabled", "true");
```

**Comment by micahgodbolt** [comment]
This is expected behavior so that screen readers can inform the user of the button and why it might be disabled.
