### ISSUE TITLE
Icons are not visible in high contrast mode

### ISSUE THREAD

**Issue by mrgarlap** [microsoft/fluentui#22105]
### Environment Information

package -  "@fluentui/react-northstar": "^0.56.0",
browser- chrome & windows 10

### Describe the issue:

when using fluent icons in the react component they are not visible in the **windows high contrast mode** on. (I do not mean Teams high contrast mode)

#### Actual behavior:

icons are invisible

#### Expected behavior:
![highContrastIcon](https://user-images.githubusercontent.com/77505284/158454793-6aabf0d2-7471-4d11-9515-0276dccabcc1.png)

icons should be visible

### If applicable, please provide a codepen repro:

https://codesandbox.io/s/fluent-ui-example-forked-ctzv23

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by jurokapsiar** [comment]
Pleased use forced colors theme instead of the HC one, see https://github.com/microsoft/fluentui/pull/22027.
