### ISSUE TITLE
Remove enzyme setup from converged packages

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#22118]
After #22009 merges, we should remove enzyme setup from converged packages (example: `packages/react-image/config/tests.js`). We could either remove the whole setup file, or just the enzyme parts.

source: https://github.com/microsoft/fluentui/pull/22009#issuecomment-1067950905

**Comment by ecraig12345** [comment]
@layershifter and/or @Hotell any preference whether to remove the whole Jest setup file for converged packages, or leave it as a placeholder and just remove the enzyme parts? I'm fine with either way.

**Comment by layershifter** [comment]
@ecraig12345 We had that discussion with @Hotell before and the conclusion was too keep placeholder files AFAIR.

**Comment by Hotell** [comment]
> @ecraig12345 We had that discussion with @Hotell before and the conclusion was too keep placeholder files AFAIR.

exactly, also some packages use `@testing-library/jest-dom` so removing this would break CI. Also please don't forget to update `migrate-converged-pkg` generator. ty
