### ISSUE TITLE
ContextualMenu submenu item doesn't show right caret in high contrast mode

### ISSUE THREAD

**Issue by dawolff-ms** [microsoft/fluentui#22137]
### Environment Information

- **Package version(s)**: 7.183.1 and 8.61.2
- **Browser and OS versions**: Chrome 99.0.4844.51, Windows 10

### Describe the issue:
Submenu items within a ContextualMenu don't show a right caret until hovered in high contrast.

### Please provide a reproduction of the issue in a codepen:
You can repro on the demo site: https://fabricweb.z5.web.core.windows.net/oufr/8.61.2/#/examples/contextualmenu

#### Actual behavior:
Right caret when not hovered is not visible in high contrast mode.

**Regular contrast**:
![image](https://user-images.githubusercontent.com/15959967/158707314-2a56db6e-0d3b-445e-bf39-9e84ba23edf0.png)

**High contrast**:
![image](https://user-images.githubusercontent.com/15959967/158707266-8b391dc6-81ec-4a56-9b3f-314b3c3217fc.png)

#### Expected behavior:
Right caret when not hovered should be visible in high contrast mode.

### Documentation describing expected behavior
https://www.w3.org/TR/2018/REC-WCAG21-20180605/#non-text-contrast

**Comment by micahgodbolt** [comment]
they are there, they are just SUPER dark
