### ISSUE TITLE
Support year-only picker in Calendar

### ISSUE THREAD

**Issue by livthomas** [microsoft/fluentui#22152]
#### Describe the feature that you would like added

I would need a single year picker where I would see a list of years and would be able to select one. It should also support minimum and maximum year that can be selected. Basically, I just need the year part of `Calendar` component that could be used alone.

#### What component or utility would this be added to

`Calendar` component from `@fluentui/react` package has `isDayPickerVisible` and `isMonthPickerVisible` which enables you to decide whether you want to use it as a day picker or a month picker. But if you set both these props to `false`, nothing is shown. I would expect a year-only picker to be displayed in this case.

#### Additional context/screenshots

Until recently, it was possible to use internal `CalendarYear` component directly. But I noticed many things (such as navigation) didn't work out of the box so I assumed it was not intended to be used outside of `Calendar` component. Moreover, after I updated `@fluentui/react` dependency to the latest version, it stopped working altogether because Vite bundler started to complain about imports from `@fluentui/react/lib/components/Calendar/CalendarYear/CalendarYear`.

**Comment by cthlo** [comment]
+1
It'd be really nice to be able to pick year first, then month then day for things like date of birth.
