### ISSUE TITLE
Single line MessageBar with set font size gets trimmed

### ISSUE THREAD

**Issue by amylemmon** [microsoft/fluentui#22155]
### Environment Information

- **Package version(s)**: fluentui/react 8.62.0
- **Browser and OS versions**: MS Edge !!ZOOM 125%!!

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/amylemmon/pen/OJzNMKx
Change browser zoom to 125%

#### Actual behavior:

The lower portion of the "g" in the message is clipped.

#### Expected behavior:

No trimmed content

**Comment by amylemmon** [comment]
Found in https://office.visualstudio.com/OC/_git/office-bohemia/pullrequest/1250141

**Comment by paulgildea** [comment]
@amylemmon Thanks for the issue.

This one does indeed repro.
