### ISSUE TITLE
[Accessibility] Narrator unnecessarily announcing the partial content of callout when navigating to Link in the callout

### ISSUE THREAD

**Issue by PrashantMicrosoft** [microsoft/fluentui#22172]
We have raised the similar bug earlier also: https://github.com/microsoft/fluentui/issues/22018

Environment Information
Package version(s): 8.60.1 (latest)
Browser and OS versions: Microsoft Windows 10 Enterprise Version 21H1(OS build:19043.1237)
Microsoft edge Version 97.0.1069.0 (Official build) dev (64-bit)
Describe the issue:
In Edge , Narrator unnecessarily announcing the partial content of callout when navigating to Link in the callout
Please provide a reproduction of the issue in a codepen:
Repro in codepen: https://codepen.io/micahgodbolt/pen/WNXVYPq?editors=0010 (This codepen link is from issue: https://github.com/microsoft/fluentui/issues/22018)
Repro steps:

Go to the codepen, Navigate to the Show callout button in codepen.
Turn on the Narrator
Click on button / press enter, then press tab/ navigate to link 

Actual behavior:
Narrator unnecessarily announcing the partial content of callout when navigating to Link in the callout. 

Expected behavior:
It should only announce link text, not any other content of callout. 

Documentation describing expected behavior
https://developer.microsoft.com/en-us/fluentui#/controls/web/callout

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

cc - @smhigley here is a reported a11y issue.

**Comment by smhigley** [comment]
This is standard behavior for Narrator in dialogs. It usually reads content up until the current focused control, unless the user interrupts or focus moves again. This isn't unique to Fluent, and we're not doing anything in our dialog to alter or disrupt the standard Narrator behavior.
