### ISSUE TITLE
 Screen reader announces document while activating Full Screen button

### ISSUE THREAD

**Issue by Prudhvikoganti** [microsoft/fluentui#22178]
### Environment Information

- **Package version(s)**: 7.170.2
- **Browser and OS versions**: All browsers & Windows 11

#### Actual behavior:
Screen Reader is announcing 'CodePen - Fabric Example Pen  **document**' while activating Full Screen button.

#### Expected behavior:

Screen Reader should not read document while activating Full Screen of video.

**Comment by micahgodbolt** [comment]
I do hear a bit of extra noise when going full screen (press escape to exit, title bar, title bar, title bar).....but it seems to be the same noise as when the video is full screened from outside of the modal https://codepen.io/micahgodbolt/pen/BaJPwre

**Comment by micahgodbolt** [comment]
Also, be sure to go to 'debug' window to reduce any of the codepen noise going on https://cdpn.io/pen/debug/BaJPwre
