### ISSUE TITLE
Fluent 8: ThemeProvider should detect child windows

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#22176]
Today, if you were to render from a parent host into a child window, things like `ContextualMenu` end up rendering on the parent host frame rather than the child.

This is because `WindowProvider` is required to pass along the child window reference. Unfortunately this is super unobvious to partners - especially things like Fluid components inside Teams child windows. 

In v7, context was not used for Layer rendering - instead, Layer rendered a placeholder span, and the document was derived from that for knowing the correct document. So upgrading to v8's context approach broke that behavior.

It would be ideal for partners rendering in child frames to not have to worry about providing the window for Layers.

One way we can detect child windows is to render a `div` with a ref, then have an effect which reads `el.ownerDocument.defaultView`. This adds a render pass though which is a perf regression.

Another idea is to render the normal content... then find the root element and detect if it's different than the assumed window object. If so, re-render and provide the correct window object. Only do this if `window` isn't explicitly provided. Then partners could just provide it to avoid the double render.

Lastly, have ThemeProvider render WindowProvider to ensure the correct window is always provided. It double checks in an effect, and 99% of the scenarios are virtually unaffected in perf.

**Comment by dzearing** [comment]
Not sure why this was assigned back to me. This is a design issue with v8 and v9.

**Comment by gouttierre** [comment]
@GeoffCoxMSFT - Would you be able to take a look at this one and work with @micahgodbolt if needed?
I will add it to the investigation queue for now.
