### ISSUE TITLE
Placeholder text overflow in Autofill component (used by PeoplePicker)

### ISSUE THREAD

**Issue by KatherineThayerMicrosoft** [microsoft/fluentui#22198]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "7.183.1"
- **Browser and OS versions**: Not relevant but my repro was on Chrome and Windows 10

### Please provide a reproduction of the bug in a codepen:

Repro: https://codepen.io/KodingKatherine/pen/zYpoXEw

#### Actual behavior:

When the placeholder text passed to the PeoplePicker (and subsequently to the Autofill component) is longer than its container, the overflow behavior is not very good. The text is cut off at the end without any indicator that it has overflowed or any way to view the remaining part of the text.

See code pointer here: https://github.com/microsoft/fluentui/blob/3dbb57b1e6940df2d4039f61a35d961bcb8560c3/packages/react/src/components/pickers/BasePicker.tsx#L308

And here: https://github.com/microsoft/fluentui/blob/3dbb57b1e6940df2d4039f61a35d961bcb8560c3/packages/react/src/components/Autofill/Autofill.tsx#L141

#### Expected behavior:

I would expect a nicer overflow behavior, perhaps an ellipsis and a tooltip that would appear on hover to show the full text.

I think the right fix is to add placeholder text overflow handling in the Autofill component following the linked example (and probably also add a tooltip to show the full text on hover): https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown#overflowing_text

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Microsoft SharePoint

**Comment by micahgodbolt** [comment]
Unfortunately, this is default input placeholder text. Try <input placeholder="lots of stuff....." /> . There is no sense in showing that there is more text in that once you click, it goes away. If you have a default VALUE in the input, that can have the elipsis.

**Comment by micahgodbolt** [comment]
Ah, the placeholder-shown pseudo selector looks like a good choice. It's not supported in IE11, but will certainly look nicer in modern browsers

``` 
input:placeholder-shown {
  text-overflow: ellipsis;
}
```
