### ISSUE TITLE
Week Number incorrect in 2022 with startDay "Monday"

### ISSUE THREAD

**Issue by MKHSKY** [microsoft/fluentui#22192]
### Environment Information

- **Package version(s)**:  "@fluentui/react": "^8.30.2",
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/VitoHusky/pen/PoEbQBW

#### Actual behavior:
The first week is in the last year

#### Expected behavior:
The first Week starts with the first weekday on the new year. So Week Number one would be on monday, 3rd, january 2022

### Priorities and help requested:
Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: Normal

Products/sites affected: Customer system, which makes a million dollars a year, who is using the week numbers often!

**Comment by micahgodbolt** [comment]
This is expected behavior. Microsoft defaults to the 1st day of the year being the 1st week. This is also true in our native apps.

You can change the first week via a prop

https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Calendar/Calendar.types.ts#L92

**Comment by MKHSKY** [comment]
Thank you for your answer! 
Adding the following option really did the trick, sorry!


`firstWeekOfYear: Fluent.FirstWeekOfYear.FirstFourDayWeek,`
