### ISSUE TITLE
Teaching bubble moves to left on focus change

### ISSUE THREAD

**Issue by gaikvij** [microsoft/fluentui#22202]
### Environment Information

- **Package version(s)**: Fluent UI React 8.62.2
- **Browser and OS versions**: 99.0.4844.82 (Official Build) (64-bit)

#### Goto https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar
AND
#### Navigate to CommandBar with coachmark on individual button

When hover on coachmark, it shows the bubble
#### Actual behavior: 
When clicked outside the box, it moves from the displayed position.

#### Expected behavior:
Teaching Bubble box should not move.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

**Comment by micahgodbolt** [comment]
Can you repro this in your app? I believe it's happening in our demo because we have some animation that slides the examples up after page load.  If you export to codepen you can see that it loads up fine.
