### ISSUE TITLE
Dialog not draggable

### ISSUE THREAD

**Issue by danmarshall** [microsoft/fluentui#22218]
On the [Dialog examples page](https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog), when the `draggable` toggle is checked, the popup dialogs are not draggable.

### Environment Information

- **Package version(s)**: >= 8.55

Functionality works up to 8.54 but is broken in 8.55 and later versions.

### Please provide a reproduction of the bug in a codepen:

Broken: https://codepen.io/danmar/pen/RwxpVdw
![drag-broken](https://user-images.githubusercontent.com/11507384/160219029-ae86ef84-f681-4e97-ba0b-d2dee5627295.gif)

Working: https://codepen.io/danmar/pen/abEJWXR
![drag-enabled](https://user-images.githubusercontent.com/11507384/160219033-bef8e589-5933-440b-a959-2054a24528d2.gif)

#### Expected behavior:

Expect to be able to drag a dialog.

**Comment by micahgodbolt** [comment]
it's still working in the '[modal](https://developer.microsoft.com/en-us/fluentui#/controls/web/modal)' component, so there must be some wiring between the two that got messed up.

**Comment by micahgodbolt** [comment]
This is now fixed.
