### ISSUE TITLE
Spinner ignores aria label

### ISSUE THREAD

**Issue by lurifn** [microsoft/fluentui#22217]
### Environment Information

- **Package version(s)**: 7.183.1
- **Browser and OS versions**: Microsoft Edge Version 99.0.1150.52 (Official build) (64-bit)

### Please provide a reproduction of the issue in a codepen:
`<Spinner 
    role='alert'
    size={SpinnerSize.xSmall} 
    ariaLabel='example aria label'
    label='extra small label'
/>`

#### Actual behavior:
Windows screen reader reads "label"

#### Expected behavior:
Windows screen reader reads "ariaLabel"

### Documentation describing expected behavior
https://developer.microsoft.com/en-us/fluentui?fabricVer=7#/controls/web/spinner#usage

**Comment by micahgodbolt** [comment]
Role alert isn't required because the Spinner takes care of "announcing" your ariaLabel value on render. Remove the role and it should work. I checked in both v8 and v7.
