### ISSUE TITLE
SpinButton: Display decimal on whole number when step is decimal

### ISSUE THREAD

**Issue by FinderFees** [microsoft/fluentui#22221]
#### Describe the feature that you would like added

When the SpinButton component has a step value of a decimal, such as {.01}, the component will round the value on whole numbers and exclude the decimal point. If the step is allowing for decimal placements, it seems logical that it would show the decimal value in its entirety, even if it is ".00".

#### What component or utility would this be added to

SpinButton

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots
![SpinButtonDecimal](https://user-images.githubusercontent.com/12091020/160252743-d818298a-85fa-4fed-9247-dae8313abeb7.gif)

**Comment by micahgodbolt** [comment]
Which version of the spin button is this (package name, package version)? It looks like the v8 version of the spin button does this properly.  

https://codepen.io/micahgodbolt/pen/QWavZab?editors=0010

**Comment by micahgodbolt** [comment]
Oh I see what you mean. The rounding when it hits an even number.
