### ISSUE TITLE
AXE accessibility scan error on FluentUI Modal

### ISSUE THREAD

**Issue by cathej** [microsoft/fluentui#22229]
### Environment Information

- **Package version(s)**: 8.45.0
- **Browser and OS versions**: Chrome, Windows 10 Version 10.0.22581 

### Describe the issue:
Our team uses [AXE accessibility scans](https://www.deque.com/axe/) to automate some accessibility bug filing. We recently updated to the new version of AXE (code below with the version update), which has been more accurate in detecting accessibility issues.
  <package id="Selenium.Axe" version="3.0.0" targetFramework="net47" />

We found that some of our modals had [the following error](https://dequeuniversity.com/rules/axe/4.4/landmark-one-main?application=AxeChrome) and we were able to reproduce it on the [FluentUI Modal page](https://developer.microsoft.com/en-us/fluentui#/controls/web/modal)

![image](https://user-images.githubusercontent.com/11904572/160489074-9bbf9714-7218-45f6-be6c-630df7ffd250.png)

### Please provide a reproduction of the issue in a codepen:
https://developer.microsoft.com/en-us/fluentui#/controls/web/modal

#### Actual behavior:
When the modal is popped the page has no main landmark because it is hidden

#### Expected behavior:

When the modal is popped it should have a landmark.

### Documentation describing expected behavior
https://dequeuniversity.com/rules/axe/4.4/landmark-one-main?application=AxeChrome

**Comment by micahgodbolt** [comment]
Modals are simple surfaces to render any content you want, and it is up to the user to provide proper landmarks. But we should also be creating good examples, so we'll update our demos to be more accessible.

**Comment by smhigley** [comment]
Just jumping in here -- this seems to be a false positive from axe, based on the `role="document"` within the modal, which is a standard way to fix a VoiceOver bug with modal dialogs.

We would not be improving accessibility by also throwing a `main` landmark within the dialog, since IMO it is not actually creating a full separate page with the need for a separate main landmark.
