### ISSUE TITLE
Combobox scrollToItem is not always working

### ISSUE THREAD

**Issue by bittola** [microsoft/fluentui#22228]
### Environment Information

- **Package version(s)**: 8.*
- **Browser and OS versions**: any

### Please provide a reproduction of the bug in a codepen:

your examples.

In the code below, currentPendingValue is undefined and therefore currentPendingValue !== '' is always true, which means that currentPendingValueValidIndex is used which is always -1
```
if (onScrollToItem) {
      // Use the custom scroll handler
      onScrollToItem(
        currentPendingValueValidIndex >= 0 || currentPendingValue !== ''
          ? currentPendingValueValidIndex
          : this._getFirstSelectedIndex(),
      );
    } 
```

#### Actual behavior:

scrollSelectedToTop = true doesn't work

#### Expected behavior:

Combobox' view should be scrolled to selected item

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: High

Products/sites affected: internal Microsoft product

https://codepen.io/micahgodbolt/pen/KKZByZv?editors=0010

**Comment by micahgodbolt** [comment]
Can you provide a repro of this bug? I did a quick check with the demos from our site and they seem to be working fine

https://codepen.io/micahgodbolt/pen/KKZByZv?editors=0010

Option C is selected, and pops up to the top when opened

![image](https://user-images.githubusercontent.com/1434956/162842921-e9970a75-58a7-489e-81fc-303eed164503.png)

**Comment by bittola** [comment]
Here's what I see
![image](https://user-images.githubusercontent.com/4676461/162982042-b7cc8060-edb9-44bb-af88-d24e32e8f916.png)
No preselection, no highlighting
It's very annoying for users when you have tens or hundreds of items in the combobox

**Comment by micahgodbolt** [comment]
Okay, so not a scroll issue, but a highlight issue.

**Comment by micahgodbolt** [comment]
Okay, I made my demo longer and I can see that the behavior is a bit more fickle than I thought.
