### ISSUE TITLE
Unable to move narrator cursor when spinButton has a defaultValue greater than 9

### ISSUE THREAD

**Issue by rdraisinghani** [microsoft/fluentui#22237]
### Environment Information

- **Package version(s)**: 8.62.4
- **Browser and OS versions**: Edge 99.0.1150.55 on Windows 10.0.19044

### Describe the issue:
We recently came across a bug where the narrator cursor does not navigate to the next element from a spin button. Upon further analysis we found that this occurs only when the spin button has a default value which is greater than 9. Try the below repro steps with a value less than 10 and it all works as expected.

### Please provide a reproduction of the issue in a codepen:

1. Have a spin button with default value greater than 9.
2. Open narrator and navigate to the spin button by sliding (left to right).
3. "Triple tap" to activate the spin button
4. Slide to move to the "Increment" button.
5. Slide again to move to the "Decrement" button.
6. Slide again to move to the next element.

[https://codepen.io/rdraisinghani/pen/qBpjpeR](https://codepen.io/rdraisinghani/pen/qBpjpeR)
#### Actual behavior:

The narrator says "Unable to move narrator cursor"
#### Expected behavior:

The narrator cursor should move to the next element.

**Comment by micahgodbolt** [comment]
not sure if this is related to the bug reported in #12676

@smhigley do you have any thoughts about what is happening here? I can confirm that once the default value is 10 on the 2nd spin button, i can't use the slide command to move to it. I hear "unable to move narrator cursor"

**Comment by rdraisinghani** [comment]
Any workarounds for this bug would be of great help.
