### ISSUE TITLE
v9 shared form control styles: Input, Select, Combobox, Textarea

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#22231]
Ref: https://github.com/microsoft/fluentui/pull/21068/files#r829433773

We have a number of shared styles and shared style constants (e.g. padding, animation timing, etc.) across Input, Select, Combobox, and Textarea. It would make sense to share those styles somewhere centralized, but we'd need to figure out where.

Existing considerations:
- Focus styles were added to `react-tabster` in https://github.com/microsoft/fluentui/pull/22096. I think this is worth revisiting, since while it does centralize the shared focus style, it also bakes a lot of very theme-specific styles into react-tabster, even with the passed-in options.
- We have both shared styles (e.g. the focus indicator) and also shared constants (the input padding, for instance)
- Some of the shared constants are defined in the `react-text` package, but are not exported (see https://github.com/microsoft/fluentui/pull/21068#discussion_r828899041 for more context)

**Comment by smhigley** [comment]
Also SpinButton :)

**Comment by GeoffCoxMSFT** [comment]
FYI - I'll use this issue for PRs to add the spacing, duration, and curve tokens as well as the contentsize constants, but won't close the issue.

**Comment by GeoffCoxMSFT** [comment]
@sopranopillow - We already have the shared tokens being used.  Coastal consensus is that trying to share this now is a bit early given that the hooks composition model doesn't have style sharing (yet), other libraries take a base-component composition approach, and it is unclear where this shared style would live.  Pls close this if you agree.
