### ISSUE TITLE
Converged (v9) Storybook Hooks Rendering Issue

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#22244]
### Environment Information

- **Package version(s)**: react-components v9.x (and any v9 packages like react-checkbox, etc)

#### Actual behavior:

1. Pull the latest master
2. Run `yarn start` and pick a v9 package like `react-checkbox`
3. Open Storybook in your browser of choice
4. Click on the Docs tab at the top of the page
5. Click on the Canvas tab at the top of the page
6. Error

Error message
```
Rendered fewer hooks than expected. This may be caused by an accidental early return statement.

Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
    at http://localhost:51505/vendors-node_modules_fluentui_react-icons_lib_icons_chunk-1_js-node_modules_fluentui_react-ic-409a96.iframe.bundle.js:47363:13
    at http://localhost:51505/vendors-node_modules_fluentui_react-icons_lib_icons_chunk-1_js-node_modules_fluentui_react-ic-409a96.iframe.bundle.js:54713:12
    at http://localhost:51505/vendors-node_modules_fluentui_react-icons_lib_icons_chunk-1_js-node_modules_fluentui_react-ic-409a96.iframe.bundle.js:54762:14
    at withFluentProvider (http://localhost:51505/main.iframe.bundle.js:2501:6)
    at http://localhost:51505/vendors-node_modules_fluentui_react-icons_lib_icons_chunk-1_js-node_modules_fluentui_react-ic-409a96.iframe.bundle.js:47359:21
    at http://localhost:51505/vendors-node_modules_fluentui_react-icons_lib_icons_chunk-1_js-node_modules_fluentui_react-ic-409a96.iframe.bundle.js:54713:12
    at http://localhost:51505/vendors-node_modules_fluentui_react-icons_lib_icons_chunk-1_js-node_modules_fluentui_react-ic-409a96.iframe.bundle.js:54762:14
    at wrapper (http://localhost:51505/main.iframe.bundle.js:2810:23)
    at http://localhost:51505/vendors-node_modules_fluentui_react-icons_lib_icons_chunk-1_js-node_modules_fluentui_react-ic-409a96.iframe.bundle.js:47876:14
    at http://localhost:51505/vendors-node_modules_fluentui_react-icons_lib_icons_chunk-1_js-node_modules_fluentui_react-ic-409a96.iframe.bundle.js:47890:26
```

Video of the issue in action:

https://user-images.githubusercontent.com/93940821/160722887-3d0ebfa6-3349-4d01-8751-7ac5f6dea577.mp4

Refreshing the page allows Storybook to load the Canvas without errors.

#### Expected behavior:

There should be no errors when changing views in Storybook.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Fluent UI

**Comment by spmonahan** [comment]
I noticed this error message in the console when Storybook starts.

<img width="1695" alt="error message when storybook starts up" src="https://user-images.githubusercontent.com/93940821/163067863-5fcd66b5-a03e-44df-addd-09093e5519fb.png">

**Comment by micahgodbolt** [comment]
haven't seen this issue in a while. open back up if you run into it

**Comment by spmonahan** [comment]
This happened to me just yesterday.
