### ISSUE TITLE
Coachmark teaching callouts are not viewport-aware

### ISSUE THREAD

**Issue by statm** [microsoft/fluentui#22259]
### Environment Information

- **Package version(s)**: latest (v8)
- **Browser and OS versions**: Edge

### Please provide a reproduction of the bug in a codepen:
(This is a similar issue as #19165)

Codepen at: https://codepen.io/statm/pen/oNpeMyJ

- Click 'Show coachmark',
- Hover on the 'teardrop' to expand the teaching callout,
- Horizontall resize the browser window, so that the right line (which should be aligned to the right edge of the callout) is not visible anymore.

#### Actual behavior:

The teaching callout is cropped.
![image](https://user-images.githubusercontent.com/1220327/160938619-5f893c51-1d70-4e5b-b6f2-2a2f5cca47aa.png)

#### Expected behavior:

Ideally the callout should be able to move itself back into viewport so it's fully shown.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, if there's a clear plan of how to fix it.

Requested priority: Normal

Products/sites affected: Office Online

**Comment by micahgodbolt** [comment]
Most of our layered items disappear on page resize for this reason (dropdowns, tooltips, contextual menus). Items placed on another layer are absolutely positioned on the page, so don't really 'flow' with the page contents. I don't see us changing this behavior. My suggestion, if this is an issue, is to close the coachmark on page resize.
