### ISSUE TITLE
List Component does not load content when using arrow down

### ISSUE THREAD

**Issue by weden-wendy** [microsoft/fluentui#22263]
### Environment Information

- **Package version(s)**: @fluentui/react version 8.30.0

### Describe the issue:

Our app is currently using List Component, but when we use arrow down to load more content, when we see the end of loaded content and before we sees the loading icon, the page is stuck and doesn't trigger to load new content if there's more. please help investigate this problem as our app depends on it.

If you need to test it, **open PPT -> login to a premium account -> Insert -> Icons**

using **arrow+down** to scroll down slowly, to a point where you starting see write space and expect it to load more content, but before the spinning icon shows up, you will notice that the list stops loading any new content until you scroll way further. (Please check the attached screenshot for the behavior)

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/77177409/160969391-788d4abb-c1bb-41ff-b5e8-04e9aacf501f.png)

#### Actual behavior:

Content does not load

#### Expected behavior:

Content loads successfully

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (High)

Products/sites affected: M365 Content Picker in Powerpoint, Words, Excel, and more

**Comment by micahgodbolt** [comment]
Before we can try and fix anything in our controls, we need to have a reduced test case using code that we can see and edit. Typically users will create a Codepen or CodeSandbox demonstrating the issue. This way we can work against that demo and ensure that whatever fix we deliver actually fixes the issue.

**Comment by weden-wendy** [comment]
***@***.*** ***@***.***>
