### ISSUE TITLE
Dropdown component giving accessibility issue when used inside shadow dom.

### ISSUE THREAD

**Issue by Gargi1810** [microsoft/fluentui#22270]
### Environment Information

- **Package version(s)**: 7.183.1
- **Browser and OS versions**:Chrome , Windows 10

### Describe the issue:

Dropdown component giving accessibility issue -- Invalid ARIA attribute values: aria-activedescendant="Dropdown906-list0", aria-controls="Dropdown906-list" 
when used inside shadow dom.

Snippet | <div data-is-focusable="true" id="Dropdown0" tabindex="0" role="combobox" aria-haspopup="listbox" aria-expanded="true" aria-labelledby="Dropdown0-label Dropdown0-option" class="ms-Dropdown is-open dropdown-68" aria-activedescendant="Dropdown0-list5" aria-controls="Dropdown0-list">

Fix the following: Invalid ARIA attribute values: aria-activedescendant="Dropdown0-list5", aria-controls="Dropdown0-list"

![image](https://user-images.githubusercontent.com/77674976/161051171-44f41aaa-4a3a-4a0b-b896-03a1afb78b75.png)

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/gargi1810/pen/wvpdXVM

**Comment by micahgodbolt** [comment]
Our controls are not going to work very well with shadow DOM due to classes getting registered in the page's <head> tag.
