### ISSUE TITLE
Determine browser minbar for v9 from current master

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#22273]
We need to determine what the minimum browser version minbars are for Fluent UI v9. This will involve going through our code base and the codebases of all v9 dependencies and analyze:

* ECMAscript syntax and APIs
* Browser platform APIs (i.e. ResizeObserver, MutationObserver, CustomEvent)
* CSS APIs

We can use https://caniuse.com/ to check what are the oldest versions for each of our supported browsers that we can use.

If possible, try to do this with automation so that we can regularly check what our minbar is and if we ever exceed it by accident. Typescript lib.dom types are tied with ecmascript versions which is not a completely accurate mapping to browser supported features.

**Comment by Hotell** [comment]
Desired outcome should look something like this:

**MUI approach:**
![image](https://user-images.githubusercontent.com/1223799/161213532-982f6229-c114-415d-84be-fe57ceab967c.png)
> source: https://mui.com/getting-started/supported-platforms/

- additional bonus is having that browserlist spec if consumer needs to do more deep dive regarding browser support

**Carbon**
![image](https://user-images.githubusercontent.com/1223799/161213855-37cd793b-0616-4691-9e58-4c3cbc7ccca0.png)

> source: https://github.com/Sage/carbon#browser-support


**Antd**

https://ant.design/docs/react/introduce#Environment-Support

**Vuetify**

https://vuetifyjs.com/en/getting-started/browser-support/

**Comment by Hotell** [comment]
### CSS support:

 `autoprefixer` can handle some fallbacks automatically without significant perf bottleneck (although shipping bigger CSS chunks) to consumers via standard CSS "last definition wins" approach.

This has limitations of course.

some css API's cannot be "polyfilled" , to name a few that we use/might use:
  -  Flex box `gap`
  - `at` rules 
  - `media` queries with selectors like [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)
  - pseudo selectors (`:not` ) https://developer.mozilla.org/en-US/docs/Web/CSS/:not
