### ISSUE TITLE
Lack of standard for Storybook asset folder

### ISSUE THREAD

**Issue by andrefcdias** [microsoft/fluentui#22289]
#### Describe the feature that you would like added

At the moment, there is no standard for our Storybook asset folders. This means that these folders are not excluded from the packaging process and we end up shipping images unnecessarily.
We should define a standard for it like, for example, an `assets` folder on the root of the package folder, or under each `stories` folder and add that to the .npmignore file.

#### What component or utility would this be added to

All packages

#### Have you discussed this feature with our team, and if so, who

@Hotell 

#### Additional context/screenshots

Check https://github.com/microsoft/fluentui/pull/21695#discussion_r813765909

**Comment by TristanWatanabe** [comment]
Proposal is to have a standardized `assets` folder at the root of each package with a `documentation` (where readme, spec, etc assets will live) and `stories` (where all story assets will live) subfolders. Since we currently ship readme and spec files to npm, only the `assets/stories` subfolder will be added to the `.npmignore` file of each package.

**Comment by Hotell** [comment]
> 

on first look it makes sense ! , but on the second thought it doesn't express the intent. Asking questions like
- why are `stories` within `assets` ?
- should `documentation` be really an asset ? we should ship proper Readme.md possible linked to additional docs about particular component if feasible. Note that having Readme.md in a subfolder is very uncommon in OSS space

**Comment by TristanWatanabe** [comment]
@Hotell i think there was a misunderstanding with what i initially wrote up 😅 The intent of this was just to add an assets (jpegs, pngs, etcs) folder  to each package where all assets will live and the subfolders are just for separation of concerns (i.e all story assets live in the stories subfolder, all docs assets live in documentation subfolder).

**Comment by TristanWatanabe** [comment]
@Hotell Sounds good to me!

**Comment by Hotell** [comment]
> @Hotell Sounds good to me!

I will try to kick-off an RFC in the future, if you want you can drive/create it. pls lemme know. ty!

**Comment by TristanWatanabe** [comment]
@Hotell I can drive it, I've created a separate issue to track this change here https://github.com/microsoft/fluentui/issues/24129
