### ISSUE TITLE
Narrator is reading the content of textfield component twice

### ISSUE THREAD

**Issue by gchaurasia1** [microsoft/fluentui#22299]
When we use narrator and the navigate using tab to a particular textfield, the narrator reads the content of the field is being announced twice. For the first time it reads the text inside field, and then it reads the text and says selected (since when we navigate through tab, the text is selected by default).

For other screen reader like NVDA, it is working fine.

**Comment by micahgodbolt** [comment]
Which package Textfield are you referring to? Can you supply a reduced test case?
