### ISSUE TITLE
[DetailsView] Code samples using Functional Components

### ISSUE THREAD

**Issue by gmantri** [microsoft/fluentui#22317]
#### Describe the feature that you would like added

Almost all the code samples for `DetailsList` component make use of Class components. I am wondering if samples can be provided using Functional components or are we supposed to use this component inside Class components only.

#### What component or utility would this be added to

DetailsList

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

N/A

**Comment by micahgodbolt** [comment]
Any of our examples could be converted to functional components. Its just that many of these older components were written before functional components were possible (with hooks), and the cost to translate them is not worth it in most cases. As an open source repo, we'd happily take a PR to do one of the conversations.

**Comment by nirtz89** [comment]
@micahgodbolt, seems like a logical step of giving an example using functional components, do you think it should be in a different page or should I just change a current example to be a functional one?

**Comment by micahgodbolt** [comment]
I think functional component examples should replace the class based ones. I don't feel there is value in supporting duplicate examples.

**Comment by shayc** [comment]
Would love to take this
