### ISSUE TITLE
TextFields and input elements lose focus when navigating with Voice access

### ISSUE THREAD

**Issue by lubeeman** [microsoft/fluentui#22322]
### Environment Information

- **Package version(s)**: 7.183.1 (also repros in v8)
- **Browser and OS versions**: Edge, Windows 11 Insider Preview Build 22518

### Describe the issue:

When attempting to navigate inside a single-line TextField using the new "Voice access" feature in Windows (Settings>Accessibility>Speech>Voice access, currently only available in the Insider Preview builds) with commands like "Move before [text]" / "Move after [text]", the TextField loses focus completely. I was also able to repro the issue with a standard input element, but only when the input element is nested within 2 Stack components.

#### Actual behavior:

Cursor moves before or after specified word

#### Expected behavior:

Element loses focus completely

**Comment by micahgodbolt** [comment]
This is a very new API. I'll create a tag for this and we can watch how support might change over time.
