### ISSUE TITLE
Tooltip host shows tooltips over button menus

### ISSUE THREAD

**Issue by tronguye** [microsoft/fluentui#22339]
### Environment Information

- **Package version(s)**: 8
- **Browser and OS versions**: Chromium Edge, Version 99.0.1150.55 (Official build) (64-bit). Windows 10 Enterprise 21H2

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/tronguye/pen/wvpydBW
![image](https://user-images.githubusercontent.com/88746241/161815849-290fe04c-06dc-4635-83bd-1bc000da523f.png)

#### Actual behavior:

1. Navigate to above codepen
2. Click menu
3. Mouse out of menu
4. Mouse in to command button
5. **Observe the tooltip shows on top of the menu**

#### Expected behavior:

1-4. Same as above
5. Tooltip is content-aware and does not impose itself on top of button menus, which is a common scenario especially for icon buttons

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: all consumers of fluent(?)

**Comment by micahgodbolt** [comment]
This is a known concern with Tooltip. We default tooltip to `display: inline` behavior. In the case that you want to use this on a button, or any other inline-block elements, you'll want to change the display of the tooltip itself to also be inline-block. See the 2nd example on https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip

**Comment by tronguye** [comment]
Hey @micahgodbolt, I've updated the codepen to use `display: inline-block`. I'm still seeing the tooltip hover showing over the menu

![image](https://user-images.githubusercontent.com/88746241/163274744-fe3eb7f5-8baf-4267-a492-25086f29f5da.png)

The expected result to me is for the tool tip to not show at all if the menu is open, or for it to be content-aware and go off to the side as to not collide with the child menu content

**Comment by micahgodbolt** [comment]
Ah, we're fighting multiple layers and which one should win. There currently isn't anything built into these two controls to be aware of each other's state. We might be able to play with z-index, or if you want to have the tooltip render a different direction if the menu is open, you could change the direction hint if the menus is open via onMenuClick and onAfterMenuDismiss

**Comment by tronguye** [comment]
currently we're using `onMenuClick` and `onAfterMenuDismiss` to keep track of state, which is then passed along to ToolTipHost `hidden` prop. If ToolTipHost isn't expected to have this behavior baked in, we can continue to do this

**Comment by micahgodbolt** [comment]
Yeah, it looks like you've got the best approach there. Our controls aren't meant to be too aware of each other. That leads to a ton of bloat for combinations you might never use.
