### ISSUE TITLE
Add React 18 Support

### ISSUE THREAD

**Issue by elliot-huffman** [microsoft/fluentui#22330]
#### Describe the feature that you would like added

React 18 support

#### What component or utility would this be added to

Fluent UI for React

#### Have you discussed this feature with our team, and if so, who

Nobody

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/5030490/161791029-824c7d7b-235f-4089-b046-99fe4eca896e.png)

**Comment by cleferman** [comment]
See #22241

**Comment by elliot-huffman** [comment]
Thx @cleferman, closing since this is a duplicate.
