### ISSUE TITLE
Move all input components to RC

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#22340]
Now that we have finished the consistency test for input components we should move them out of beta and into RC (out of unstable and into the regular `react-components`).

These are the components that we should move:
- [x] Checkbox - #22914
- [x] Input - #22674
- [x] Label - #22777
- [x] Radio - #22680
- [x] RadioGroup - #22680
- [x] Slider - #22224
- [x] Switch - #22818
- [x] SpinButton - #23805
- [x] Textarea - #22795

**Comment by spmonahan** [comment]
SpinButton will be moved later. We want to bug bash before moving to stable.

**Comment by khmakoto** [comment]
This work has been finished.
