### ISSUE TITLE
ChoiceGroup does not respect custom 'id' 

### ISSUE THREAD

**Issue by N1K0L45** [microsoft/fluentui#22353]
### Environment Information

- **Package version(s)**: Latest (8.48.0 now in my package.json) - Tested in FluentUI docs also
- **Browser and OS versions**: (Windows 11, browser Brave 1.37)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/n1k0l45/pen/RwxQxrY

#### Actual behavior:

Although the 'id' field is set, it does not change, and uses the random generated by Fluent.

#### Expected behavior:

Respect the value set to 'id'. I know the issue was suppousedly fixed in Fix #14387, but somehow it still does not work. I'm using the latest version of fluent/react

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by micahgodbolt** [comment]
So you want the ChoiceGroupOptions to use the ID provided to the ChoiceGroup as the prefix for the option ID, is that correct?

So then:

```
<ChoiceGroup id="foo" />
```

should produce options that look like

```
<input id="foo0-A"/>
<label for="foo0-A />
```

This isn't the intended behavior, but it is a feature we could add. What's the purpose of doing this?

**Comment by N1K0L45** [comment]
Actually, it's not the prefix what I'm looking for. It's the ChoiceGroup itself (I handle options a bit different using custom components). I just need to be in control of what component the user "touched".

In my case, it's because I made a component where the results of modifyng fields updates a state variable, guided by the `event.target.id` field. there could be multiple ChoiceGroups, as well as CheckBoxes and TextFields. Works fine on everything except for ChoiceGroup.

For example, if you modify a TextField it replaces a value in an object with same key as id of the text input, then sends a request to update it in the server. I need to be in control of every input the user is touching, not the options it's selecting.

**Comment by micahgodbolt** [comment]
Your ID is being passed to the root of the ChoiceGroup
![image](https://user-images.githubusercontent.com/1434956/163445647-d26b36d8-7bd6-4278-a3b5-aaef8ceec1e6.png)

What are you expecting to happen?

**Comment by N1K0L45** [comment]
Actually, it doesn't. At least in my case, when I'm accessing `event.target.id`, it appears as "ChoiceGroup-A", or something like that.

![image](https://user-images.githubusercontent.com/14933791/164056437-dfa4d1a1-c2d9-4d70-8d1d-c1551b4a2d55.png)

The image above it's a console.log of the `event.target.id` when clicking an option. I need it to be the id I provided, as it is with the other components.

**Comment by micahgodbolt** [comment]
Yes, the prefixes for each toggle'd ID is pregenerated with a custom unique prefix. We don't have a way to supply a custom string for the ID prefix, or for the individual ID. These generated IDs are required to ensure all the various internal strings align.
