### ISSUE TITLE
API Extractor generates different file paths in warning comments locally vs. in CI

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#22350]
If there are warning comments generated in a component's API file, it causes the CI to fail with the error that the API file is out of date.

The cause is that the file paths generated in the warnings differ when generated locally vs. in the CI. Here's an example of a warning from a local build that differed from the CI-generated comment:

```
// Warnings were encountered during analysis:
//
// lib/components/Combobox/Combobox.types.d.ts:67:5 - (ae-forgotten-export) The symbol "OptionValue" needs to be exported by the entry point index.d.ts
```

**Comment by Hotell** [comment]
thanks for report @smhigley !

This is unfortunately a side effect of a need to stick with tools that we use for v8 ATM. 

Future plan will unify our approach and thus mitigate this. 

Also note those warnings should not happen anymore after https://github.com/microsoft/fluentui/pull/22144
