### ISSUE TITLE
Localization Issue:  Text in color dialog is not localized.

### ISSUE THREAD

**Issue by nansing90** [microsoft/fluentui#22356]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant) Chrome

#### Actual behavior:
Color name like Hex, green red is not localized

#### Expected behavior:
Color name like Hex, green red should be localized

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)
#
![image](https://user-images.githubusercontent.com/92431353/161969902-9670166e-93a6-4cce-abfc-33fc9f674b92.png)

**Comment by micahgodbolt** [comment]
All of the strings can be localized by passing a "strings" prop into the ColorPicker

https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/ColorPicker/ColorPicker.types.ts#L32
