### ISSUE TITLE
Tooltip on PivotItem doesn't work as expected when the pivotitem is disabled

### ISSUE THREAD

**Issue by vikram-gsu** [microsoft/fluentui#22351]
### Environment Information

- **Package version(s)**: Fluent React 8.45
- **Browser and OS versions**: Microsoft Edge, Windows 11

### Describe the issue:

I'm using onRenderItemLink to add tooltip to PivotItem. This works as expected when the pivotitem is enabled. However, when the pivotitem is disabled, the following happens:
1. Tooltips show fine on initial load
2. Tooltips become very unpredictable and don't show when we visit the tabs again
3. Also, without closeDelay prop set, we can't get into the tooltip text

When PivotItem is enabled, we see this:
![whenEnabled](https://user-images.githubusercontent.com/3606427/161848247-23e64393-c752-4aa1-9a51-9ff4b6049393.gif)

However, when PivotItem is disabled, we see this:
![whenDisabled](https://user-images.githubusercontent.com/3606427/161848344-28447bd0-8341-48e8-a7f3-16ec73e475f2.gif)

### Please provide a reproduction of the issue in a codepen:
[FluentUI PivotItem disabled + Tooltip issue](https://codepen.io/ikramvay/pen/WNdMOmB)

#### Actual behavior:

Tooltips are hard to show/get into when the PivotItem is disabled

#### Expected behavior:

Expected behavior should be same as when the PivotItem is enabled - tooltip should show easily on hover and should let the user to get into the tooltip content

**Comment by micahgodbolt** [comment]
I can see there are differences between your in app gif and the codepen that you provided. I can't really repro the same issues in your codepen.

**Comment by micahgodbolt** [comment]
Part of the issue might be that the focus target is just the text inside the tab

![image](https://user-images.githubusercontent.com/1434956/163102174-6f543533-6c03-4349-aac9-d3a8c9a6bd66.png)

when i hover over the text i get it working consistently
