### ISSUE TITLE
[Bug] onAnimation... events missing from htmlElementProperties

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/fluentui#22354]
### Environment Information

- **Package version(s)**: Fluent UI React 8.63.1
- **Browser and OS versions**: Microsoft Edge 100.0.1185.29

### Please provide a reproduction of the bug in a codepen:

[Sample](https://codesandbox.io/s/fluentui-bug-onanimationend-stack-sn5bm3?file=/src/App.tsx)

#### Actual behavior:

The `onAnimation(End|Start|Iteration...)` property was specified but have no effect. In checking I found that these listeners have not even been bound to DOM.

#### Expected behavior:

Listeners should be bound to DOM and fired correctly.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking, cause my project really needs this property to detect whether the animation has been ended, and my project cannot go on because of this bug.)

Products/sites affected: (Not applicable)

**Comment by AkiraVoid** [comment]
I'm wondering who can help me solve this issue?

**Comment by micahgodbolt** [comment]
I'll triage this today to see what is required to solve the problem.

**Comment by micahgodbolt** [comment]
Okay, it looks like our `getNativeProps` is stripping those out due to them not being part of `htmlElementProperties`.

Depending on the complexity of your stack use, i'd suggest simply using a div with correct 'flex' styles, as Stack is just a helper component.

**Comment by AkiraVoid** [comment]
Yes, I am now using native div element to apply my animations but I actually don’t want to use div because it’s meaningless and I want to keep my code consistent, for example, other codes use Stack to apply flex layout so I want to always use Stack for same layout requirement. Anyway, thanks for your help.
