### ISSUE TITLE
Crash App when using Nav and ContextualMenu

### ISSUE THREAD

**Issue by Tranthanh98** [microsoft/fluentui#22355]
When the ContextualMenu is Opening and click on any Item on Nav component, it will be crashed app
![image](https://user-images.githubusercontent.com/51749033/161959830-1d94d65f-a8f6-4763-b81d-e57f63c777bf.png)

- the ContextualMenu is opening (blue), and if I click on `Dashboad`. It will be throw error
![image](https://user-images.githubusercontent.com/51749033/161960321-5e11ce30-7963-4a8a-8e03-8267ae7cd0d8.png)

**Comment by micahgodbolt** [comment]
We will need an external reproduction of this issue to determine if the problem has anything to do with the ContextualMenu and not something in your app
