### ISSUE TITLE
[ContextualMenu] Focus after selecting submenu's goes to body

### ISSUE THREAD

**Issue by lucas-stanford** [microsoft/fluentui#22364]
### Environment Information

- **Package version(s)**: 8.64.1 
- **Browser and OS versions**: Windows/Chrome

### Describe the issue:

After selecting a ContextualMenu with submenus. The focus goes to the body. This is not the case when selecting a non submenu. 
![contextualmenu](https://user-images.githubusercontent.com/3011776/162062462-b2714298-2476-4708-9a38-a10f2de74e60.gif)

### Please provide a reproduction of the issue in a codepen:

Repros here: https://fabricweb.z5.web.core.windows.net/oufr/8.64.1/#/examples/contextualmenu, check the subheading: 'ContextualMenu with submenus'

#### Actual behavior:

After selecting the submenu item the body gets focus.

#### Expected behavior:

After selecting the submenu item the root contextual menu gets focus (like non submenus)

**Comment by micahgodbolt** [comment]
Confirmed, but haven't dug into the issue yet.
