### ISSUE TITLE
Password field: canRevealPassword eye button disappears on click outside of field (Edge only)

### ISSUE THREAD

**Issue by nipope** [microsoft/fluentui#22362]
### Environment Information

- **Package version(s)**: 8.42.0
- **Browser and OS versions**: Microsoft Edge issue only

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/nipope1/pen/YzYawZL
(Note that while the codepen behavior is also strange, it does not exactly match what we are seeing using the control in our component. The second eye button that pops up in the codepen (to the left of the blue eye icon) is the only eye button we can see using Edge. The behavior of this second eye button in the codepen matches its behavior in our environment.)

#### Actual behavior:

Note: this only repros in Microsoft Edge. 
Reveal password eye becomes visible when the user begins typing in the password field, but becomes invisible as soon as they click anywhere outside the field. In order to make the eye visible again the user needs to clear the password field and type again (just continuing to type without clearing the field does not make the eye reappear). 

#### Expected behavior:

Reveal password eye button should either always be visible or should always be visible when there is text in the password field (to match the behavior in Chrome, it should always be visible.)

I am not too familiar with this code base, but I took a look at the source code and the issue seems to be with this function: https://github.com/microsoft/fluentui/blob/20e754f76bd3ef8fab7580ff1d3ec1f8be2ecca7/packages/react/src/components/TextField/TextField.base.tsx#L669

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Azure Lab Services

**Comment by micahgodbolt** [comment]
![password](https://user-images.githubusercontent.com/1434956/163022075-45a04180-202d-4449-ba08-4ebe99540019.gif)
