### ISSUE TITLE
[React][WhiteBoard] Issue in tooltip text while mouse hover in WB

### ISSUE THREAD

**Issue by shivi057** [microsoft/fluentui#22375]
In this, I have tried to fix incorrect positioning of tooltip text when it is first rendered with keyboard instead of mouse hover.

Since tooltip positioning is entirely within Fluent library, I wanted help in verifying if the solution I proposed is correct or there is something else in the library that needs to be changed to fix the bug that I am missing ?

**Comment by micahgodbolt** [comment]
As an open source repo, please don't link to internal tickets. I've removed them from the description.

Is it possible to repro the issue that you are experiencing outside of your app? You can create a quick codepen at [aka.ms/fluentpen](https://aka.ms/fluentpen)
