### ISSUE TITLE
ComboBox cannot provide an onScroll to calloutProps

### ISSUE THREAD

**Issue by kevinfairclough** [microsoft/fluentui#22372]
### Environment Information

- **Package version(s)**: 8.x
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/kevinfairclough/pen/dyJmdPQ?editors=0010

#### Actual behavior:

Method not called

#### Expected behavior:

Method to be called

### Priorities and help requested:

Are you willing to submit a PR to fix? ( No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
It looks like Combobox has custom onScroll behavior to manage some selection issues. We'd need to add a callback here for any custom callout onScroll events

https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/ComboBox/ComboBox.tsx#L1655
