### ISSUE TITLE
Migrate v8 size auditor tests to use @fluentui/bundle-size

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#22405]
Write fixtures for v8 that will use @fluentui/bundle-size to measure bundle-size. Here is an example of a fixture https://github.com/microsoft/fluentui/blob/master/packages/react-menu/bundle-size/Menu.fixture.js

**Comment by Hotell** [comment]
Closed by https://github.com/microsoft/fluentui/issues/27933
