### ISSUE TITLE
SVG Icons not accessible in high contrast mode

### ISSUE THREAD

**Issue by rwedoff** [microsoft/fluentui#22410]
### Environment Information

- **Package version(s)**: Current Fluent Docs 8.64.1
- **Browser and OS versions**: Windows 10, High Contrast Mode, Edge Chromium
### Describe the issue:

SVG Icons are not accessible in high contrast mode. They do not have enough contrast.

### Please provide a reproduction of the issue in a codepen:
https://fabricweb.z5.web.core.windows.net/oufr/8.64.1/#/examples/icon
See the "Icon using svg factory" example.

#### Actual behavior:
1. Turn on high contrast mode in Windows 10 Settings.
2. Look at new SVG icons
3. Observe, the contrast is not high enough for the icons now.
![image](https://user-images.githubusercontent.com/6679636/162324581-909b9bc7-ebdd-4b29-88d6-80d29c09b8e1.png)

#### Expected behavior:

Regardless of high contrast mode on or not, the icons should have high contrast. This should not be left up to the individual developer as this will easily be missed.

### Documentation describing expected behavior

The solution to this problem is likely to add these media queries to the SVG Icon component.
```
@media screen and (-ms-high-contrast: active) { /* All high contrast styling rules */ }
@media screen and (-ms-high-contrast: black-on-white) { /*  */ }
@media screen and (-ms-high-contrast: white-on-black) { /*  */ }
```

**Comment by micahgodbolt** [comment]
It appears that the CSS WG made some changes recently that affected SVGs and browsers still haven't figured out how to work with SVGs in HCM. It looks like we can force colors to adjust by adding `svg { forced-color-adjust: auto }` to our icons package. 

You should be able to add the CSS yourself for now until we get the issue resolved

![image](https://user-images.githubusercontent.com/1434956/163230209-d35efe8a-7475-485d-b75b-3b8220c97d40.png)
