### ISSUE TITLE
The "DetailsList Fixed Header without ScrollablePane" example doesn't work

### ISSUE THREAD

**Issue by yume-chan** [microsoft/fluentui#22447]
### Environment Information

- **Package version(s)**: 8.64.1
- **Browser and OS versions**: Windows 11, Microsoft Edge stable 100.0.1185.36

### Please provide a reproduction of the bug in a codepen:

1. Open https://developer.microsoft.com/en-us/fluentui#/controls/web/scrollablepane
2. In the "DetailsList Fixed Header without ScrollablePane" example, scroll down several pages

#### Actual behavior:

It became blank

![image](https://user-images.githubusercontent.com/1330321/162567529-3d8bd805-9f13-40e9-8e82-2f3418e26884.png)

#### Expected behavior:

Render correctly

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: N/A

**Comment by yume-chan** [comment]
Also, the vertical scroll bar is visible only when scrolled to the right end.

![image](https://user-images.githubusercontent.com/1330321/162567734-869619dd-1be9-4bb3-9ae7-b93fd1757015.png)

![image](https://user-images.githubusercontent.com/1330321/162567731-aa9de659-3887-43b6-950a-763207b5879a.png)

**Comment by yume-chan** [comment]
Third issue: the horizontal scroll bar doesn't appear on hover if auto-hide is enabled

**Comment by yume-chan** [comment]
The demo given in https://github.com/microsoft/fluentui/issues/18413#issuecomment-854075008 also doesn't work.

If you set `minWidth` of both `column`s to 1000, then scroll horizontally, it also became blank:

https://codesandbox.io/s/18413-detailslist-scrollable-with-fixed-headers-forked-5fmpcz?file=/src/index.tsx

![image](https://user-images.githubusercontent.com/1330321/162567828-072d7dd4-0617-4810-926d-cd2ee08dce3a.png)

**Comment by micahgodbolt** [comment]
It looks like some local styling is causing the issue. These demos are not iframed in, so sometimes their environment causes issues. I'll take a look.
