### ISSUE TITLE
storybook does not change theme for stories, only the theme switcher dropdown

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#22440]
### Environment Information

- **Package version(s)**: master
- **Browser and OS versions**: Chrome, Safari (on Mac OS and Windows)
- Happens at both the published vNext docs and local dev runs of storybook

### Expected

When changing theme, the theme changes for the entire storybook

### Actual

Theme change only effects the theme picker dropdown toolbar

### Screenshots

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/28762486/162550378-00e66a7b-b992-451b-93c5-242545deda95.png">

**Comment by micahgodbolt** [comment]
This appears to be fixed in master. @levithomason probably just needs to update his branch or the aka link

https://61b7c406fa7cd4003a8a07ec-kxbhyuikpy.chromatic.com/?path=/docs/components-button--default

**Comment by paulgildea** [comment]
https://aka.ms/fluentui-react-storybook has been updated.
