### ISSUE TITLE
Narrator is narrating unnecessary information as 'read only' information for table content while navigating using TAB/table short cut (Ctrl+Alt+arrows) keys.

### ISSUE THREAD

**Issue by nansing90** [microsoft/fluentui#22449]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out) Chrome/Edge

### Describe the issue:
 on ShimmeredDetailsList Narrator is narrating unnecessary information as 'read only' information for table content while navigating using TAB/table short cut (Ctrl+Alt+arrows) keys. 

### Please provide a reproduction of the issue in a codepen:
Navigate on ShimmeredDetailsList using tab, Narrator will include read only in all header reading. 

#### Actual behavior:
Navigate on ShimmeredDetailsList using tab, Narrator will include read only in all header reading. 

#### Expected behavior:
Navigate on ShimmeredDetailsList using tab, Narrator will not include read only in all header reading.

**Comment by micahgodbolt** [comment]
I'm having trouble reproducing this issue. Can you give specific steps for reproducing? What do you mean "include read only"? Is it speaking 'read only' or something else?

**Comment by nansing90** [comment]
Steps to Reproduce the Issue:  
1. Go to the targeted component
2. Turn on Narrator  by Ctrl+Enter+ windows key
3.  Navigate using Tab on each header
4. Narrator announces the name of the header +ready only in the end.

**Comment by nansing90** [comment]
Steps to Reproduce the Issue:  
1. Go to the targeted component
2. Turn on Narrator  by Ctrl+Enter+ windows key
3.  Navigate using

**Comment by micahgodbolt** [comment]
I've tried this several times in current Edge and cannot get the DetailsListShimmer headers to read out anything about disabled

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/shimmer
