### ISSUE TITLE
[Bug]: Unable to visually see that a checkbox is unchecked (Mobile only)

### ISSUE THREAD

**Issue by bursteways** [microsoft/fluentui#22455]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 96.54 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Browsers:
    Brave Browser: 99.1.36.117
    Chrome: 100.0.4896.75
    Firefox: 88.0.1
    Safari: 15.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/sburkebuzz/pen/vYpaxyy

## Actual Behavior
**Strictly on Mobile:** We are unable to see if a checkbox is checked (visually). We are able to see via console logs that the checkbox is `checked` and the state is correct, but we cannot see this work.

**Note:** This is reproducible on the chrome emulator and physical mobile devices.
**Note:** This is reproducible on the [component site](https://developer.microsoft.com/en-us/fluentui#/controls/web/checkbox#usage) as well.

## Expected Behavior
The checkbox should be visually unchecked

![checkbox](https://user-images.githubusercontent.com/48305203/162803003-c3b9a8ee-825f-452f-8b92-6794b1252b15.gif)

### Requested priority

Normal

### Products/sites affected

https://developer.microsoft.com/en-us/fluentui#/controls/web/checkbox#usage

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
We are aware of a focus bug in mobile browsers where after clicking on a checkbox focus stays on the checkbox, therefor showing the light gray "hover" checkmark. But there should be no issue with the checkbox being the correct color. I cannot repro this issue, nor my co-workers. Tried Mac, PC, iOS. They all work as expected.

**Comment by bursteways** [comment]
@micahgodbolt Thanks for the reply. Could you please give me a reference to the other bug you're tracking?

**Comment by micahgodbolt** [comment]
The issue is https://github.com/microsoft/fluentui/issues/5734
