### ISSUE TITLE
[Bug]: FocusTrapCallout dismisses on scroll

### ISSUE THREAD

**Issue by rslavey** [microsoft/fluentui#22463]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 19.79 GB / 31.96 GB
  Browsers:
    Chrome: 100.0.4896.75
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.36)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codepen.io/randyslavey/pen/popZZbe

## Actual Behavior
Focus trap goes away on scroll

## Expected Behavior
The focus scroll should only be dismissed with a state change of onDismiss

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
This is expected behavior. All of our floating surfaces dismiss on scroll due to them being on a separate layer and not sitting inside the scrolling DOM. i.e. if you scrolled, the surface would sit still as the page moved.

FocusTrapCallout only handles trapping focus. If you want to enforce that a user can't scroll you can use a modal, or manually limit the page overflow.

**Comment by rslavey** [comment]
Thanks. Does this also apply to divs with overflow that don't move the FocusTrapCallout? For example, I have a list that scrolls next to a FocusTrapCallout. Scrolling that list, even though the page does not move, still dismisses the FocusTrapCallout. Is this also expected behavior? See screenshot. Scrolling the list in (2) still dismisses the FocusTrapCallout in (1), even though that content never moves.
![image](https://user-images.githubusercontent.com/21177142/163096156-4856d23d-bf23-4f91-b909-52de88a2eb4f.png)
