### ISSUE TITLE
Cant remove tabindex from commandbar item

### ISSUE THREAD

**Issue by nadavWeisler** [microsoft/fluentui#22487]
OS: Windows 11 Enterprise 21H2 (OS build: 22000.258)
Browser: Edge(Chromium) Version 98.0.1093.6 (Official build) dev (64-bit)

![image](https://user-images.githubusercontent.com/32937058/163217787-bc492f85-682f-485b-8b98-0abe2f9f4c0f.png)

Hey, I'm trying to remove tabindex in command bar item without any success. It is disabled and using in our user experience as a separator, but the fact is the for accessible user it is not disable, because the user can navigate there using the Tab key.

**Comment by micahgodbolt** [comment]
if you want a visual divider, I wouldn't suggest using a command bar item, but rather use CSS to create a border. Items are not built to be simply decorative.

**Comment by nadavWeisler** [comment]
allowDisabledFocus: false fix the problem, I adivice to add example of it in the docs, maybe other people stuck on that too.
