### ISSUE TITLE
Empty list item is not handled in Detail list

### ISSUE THREAD

**Issue by Misbah-Mushtaq** [microsoft/fluentui#22521]
#### onRenderEmptyList

No data indication in the detailList Items 

- No Record Found !!

Provide a callback in DetailList where the user can check if the item list has data or not and based on the results, the user can show or hide content.

#### Currently it shows empty space

![image](https://user-images.githubusercontent.com/57727236/163536268-4755478e-13d0-482e-a389-77300c7cd6df.png)

@tomi-msft

**Comment by micahgodbolt** [comment]
If you are providing the items to the list, why do you need an internal callback? Can't you provide your own fallback when the list you are providing is empty?
