### ISSUE TITLE
NormalPeoplePicker required attribute

### ISSUE THREAD

**Issue by tpalacino** [microsoft/fluentui#22528]
#### Describe the feature that you would like added

I would like to have a "required" and "onGetErrorMessage" attributes be added

#### What component or utility would this be added to

NormalPeoplePicker (ideally it would be on the BasePicker so all pickers would have it)

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

The expected behavior would be similar to the same attributes of the ComboBox.

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.

**Comment by tpalacino** [comment]
I've implemented the `label`, `required`, `errorMessage`, and `onGetErrorMessage` functionality in the `BasePicker` and `BasePickerListBelow` but the steps of the [Full development workflow walkthrough](https://github.com/microsoft/fluentui/wiki/Development-Workflow) are failing on aspects of the code that I did not change.

Since the same errors occur in the same files when I attempt to run those build commands on the current version of the `master` branch in the `microsoft/fluentui` repo I went ahead with generating a change file and creating the [PR # 23362](https://github.com/microsoft/fluentui/pull/23362)

**Comment by tpalacino** [comment]
@gouttierre Can you help me understand what to do next?

I made the code updates and submitted the PR. Two of the automated validations are failing. One issue should not actually be treated as a failure IMO, and I have shared some details in the PR comments explaining why I think that. Despite recent activity from @ling1726, I have yet to receive have any guidance on how to resolve the issues.

**Comment by tpalacino** [comment]
@gouttierre I've done everything I can for this. How long does it normally take to get a response from anybody at all?

**Comment by JustSlone** [comment]
hey @tpalacino sorry this fell through the cracks, are you still interested in contributing here? Thanks!

**Comment by tpalacino** [comment]
Yes. I think this is a solid addition

**Comment by JustSlone** [comment]
@micahgodbolt, can you, or someone from coastal, work with @tpalacino on this contribution?

@tpalacino this is scheduled for Oct 31- Nov 13th iteration, folks should have time to dig in then.

**Comment by tpalacino** [comment]
@micahgodbolt I am unable to make any sense of why the Sizer step is failing the build on [my PR](https://github.com/microsoft/fluentui/pull/23362). Can you offer any guidance?

**Comment by tpalacino** [comment]
Can I please have some communication from a human on this? I have repeatedly tried to get assistance with getting the PR reviewed and approved.

**Comment by khmakoto** [comment]
@tpalacino I've reopened the issue and I'll try to take a look at your PR as soon as possible.

**Comment by tpalacino** [comment]
Awesome. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tpalacino** [comment]
@khmakoto any update on this?

**Comment by tpalacino** [comment]
@khmakoto I understand that the primary focus is v9 but this update does a lot to unify the developer experience of the normal people picker and other user input components. It'd be awesome to have this functionality merged.

**Comment by tpalacino** [comment]
@khmakoto I would still very much like to contribute this update to the original pickers if it's possible for anyone to help me out with whatever I was/am missing. I ended up creating a new branch because the old one got too outdated.
