### ISSUE TITLE
[Bug]: Pivot cannot be rendered in MDX environment.

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/fluentui#22527]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 6.42 GB / 15.88 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.39)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @fluentui/react: ^8.64.3 => 8.65.0
    @fluentui/react-icons-mdl2: ^1.3.6 => 1.3.8
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/pivot-with-mdx-7wcjl6?file=/docs/doc1.md

### Bug Description

Please navigate to Docs (Click menu button on the top left), and you'll see this bug. The warning message is in console. You may need to start a new terminal and run `yarn start` to get a new instance with updates. (Using docusaurus is just for MDX environment, docusaurus renders all Markdown files as MDX).

## Actual Behavior

The Pivot component throw `The children of a Pivot component must be of type PivotItem to be rendered.` and render nothing.

Relying on `item.type.name` to check if it is a certain component probably wouldn't work with minifiers. `item.type.name` will give non-sensical values in prod because of minification. (This message is from a Docusaurus developer and I don't know what it exactly means).

## Expected Behavior

Component should be rendered as expectation.

### Logs

```shell
The children of a Pivot component must be of type PivotItem to be rendered.
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Does this work with any other components? Have you tried anything other than Pivot?

**Comment by AkiraVoid** [comment]
No, I haven't. I don't know which component will check its children's type like Pivot do.

**Comment by AkiraVoid** [comment]
BTW, docusaurus team made a component which is just like Pivot and named Tabs, it will check its children but not by `item.type.name`, and as that guy said, even their own component will cause this issue if they use this way to judge children's type.

**Comment by AkiraVoid** [comment]
And maybe their [source code of Tabs](https://github.com/facebook/docusaurus/blob/9145ae88cc22ad322e070b705ee3c4c8ef8f0a0a/packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx) would be useful to solve this issue. Line 42 to 54.

**Comment by AkiraVoid** [comment]
DefaulButton works.

**Comment by micahgodbolt** [comment]
Yeah, it appears that MDX treats children differently and it's causing this check to not work

https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Pivot/Pivot.base.tsx#L61-L63

Move the Pivot example out into it's own JS file and you can render the component as a single item, then it works

https://codesandbox.io/s/pivot-with-mdx-forked-uz1991?file=/docs/PivotExample.js

**Comment by micahgodbolt** [comment]
I don't believe we are going to change the way Pivot works to better support MDX. But we'll keep that in mind in our v9 Pivot to see if we can improve that type checking.

**Comment by AkiraVoid** [comment]
OK, I cannot wait to use v9, thanks for your hard-working.
