### ISSUE TITLE
"commandBarButtonAs" prop doesn't work when the CommandBar items come under overflow menu

### ISSUE THREAD

**Issue by RupamSarkar** [microsoft/fluentui#22536]
### Environment Information

- **Package version(s)**:  Fluent UI React 7, 8
- **Browser and OS versions**: All

### Describe the issue:
Custom render of a Command Bar button provided as `commandBarButtonAs` prop doesn't work if the item comes under overflow menu due to small screen real estate or resizing the window.

#### Actual behavior:
In the below screenshot of a Command Bar, the last command ( `Custom download` ) is using `commandBarButtonAs` prop to pass a custom component to the show the button name as `Custom download` instead of `Download` -
![image](https://user-images.githubusercontent.com/17047049/163881938-0540125f-1809-43c7-b0d7-200e00b9050c.png)

But, when the same command comes under overflow menu, it doesn't show the custom component anymore and show the default render - 

![image](https://user-images.githubusercontent.com/17047049/163882299-f4d9d5c0-cbd0-4f59-92e7-1513614d355b.png)

#### Expected behavior:

`commandBarButtonAs` prop should work when the command comes under overflow menu.

### If applicable, please provide a codepen repro:

Codepen repro - https://codepen.io/rupamsarkar/pen/mdpQaeY?editors=0010

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: SharePoint

**Comment by micahgodbolt** [comment]
This is a very intentional design decision noted in the prop's interface

![image](https://user-images.githubusercontent.com/1434956/164034841-09d36bed-338d-4bab-a727-0a2644648636.png)


The items are treated as contextual menu items when rendered in the overflow, and pretty much follow the contextualmenuitem interface if you need to override that render.
