### ISSUE TITLE
[Bug]: Property 'children' does not exist

### ISSUE THREAD

**Issue by sarahkang58** [microsoft/fluentui#22534]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22598
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 5.21 GB / 15.92 GB
  Browsers:
    Edge: 44.22598.1.0
    Internet Explorer: 11.0.22598.1
```

### Reproduction

https://codepen.io/sarahkang58/pen/LYeMJyB

## Actual Behavior
I am using a `<Dialog>` and a `<DialogFooter>` component and am in the process of upgrading from office-ui-fabric-react to the v8 fluentui/react package.  I am not sure if it's because of the upgrade or something else, but when I try building my code now, I get a build error that says `Property 'children' does not exist on type 'IntrinsicAttributes & IDialogProps'.`  I don't understand why this is happening when the Dialog.d.ts files look exactly the same between the old office-ui-fabric-react package and the new v8 fluentui/react package (and these components worked just fine before).

Furthermore, I get this same error with other components like `<Sticky>`, where we put children elements inside.

## Expected Behavior
We don't get a build error.

### Logs

```shell
error TS2322: Type '{ children: Element; hidden: boolean; onDismiss: () => void; dialogContentProps: IDialogContentProps; modalProps: IModalProps; "data-testid": string; }' is not assignable to type 'IntrinsicAttributes & IDialogProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IDialogProps'.
```

### Requested priority

Blocking

### Products/sites affected

Merge

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Did you add the right repro codepen? I don't see any errors on load, dialog open, or close

**Comment by sarahkang58** [comment]
Hi @micahgodbolt , yes the codepen shows a working dialog.  My issue is that I have pretty much the same code, but I'm getting a build error with it.  Maybe this screenshot will help:

![image](https://user-images.githubusercontent.com/64438850/164250550-0a806a66-d302-41aa-9251-a376ae2682c0.png)

And here's the Dialog.d.ts file that I get when I look into the definition in the @fluentui/react package:

![image](https://user-images.githubusercontent.com/64438850/164250811-6843a417-7292-4a87-9667-ce69b76bb957.png)

**Comment by sarahkang58** [comment]
Also, when I add this `children?: React.ReactNode;` to the IDialogProps interface in the Dialog.types.d.ts file, the error goes away.  What I can't understand though is how this Dialog component was working just fine all this time until recently when I tried upgrading my packages.

**Comment by sarahkang58** [comment]
Hi @micahgodbolt , I also tried updating my "@types/react" version from v16 to v17, and then also added "typeRoots": ["./node_modules/@types"] to the tsconfig file and restarted the ts server.  The same "Property children does not exist" issue is still there though.  Does this bring any ideas to mind as to what the problem could be?

**Comment by micahgodbolt** [comment]
Its hard to triage without a way to repro the issue. Are you able to revert back to before you started to upgrade and see if the error persists? If it goes away, what have you changed between then and now.

**Comment by sarahkang58** [comment]
Hi @micahgodbolt , so the issue seemed to come up whenever I tried deleting the package-lock files and regenerating them based off the new package.json's.  I can workaround it for now by just keeping the package-lock files and updating them instead of deleting them entirely.  I'll close this issue, thanks!

**Comment by Basek** [comment]
Hi [sarahkang58](https://github.com/sarahkang58), What version of react definition do you use? The children property was removed from react 18. 

[micahgodbolt](https://github.com/micahgodbolt), Do you have plans about support react 18?

**Comment by sarahkang58** [comment]
Hi @Basek we have React version 16 right now
