### ISSUE TITLE
[Bug]: SpinButton incorrectly handles invalid data if the app doesnt switch focus on increment/decrement buttons

### ISSUE THREAD

**Issue by thomabr** [microsoft/fluentui#22532]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
OS: Windows 10 10.0.19043
CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
Memory: 5.75 GB / 15.91 GB
Browsers:
Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.39)
Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/thomabr/pen/yLpGvdw

## Actual Behavior
Type in an invalid number "1 1" into the spin button
Hit increment button
click elsewhere to find focus.
The value is constantly incrementing

## Expected Behavior
Increment button validates the value and returns it to the last known good.

Office likes to not lose focus on elements when buttons are pressed in our UI. This allows dual mouse/keyboard usage. However, it seems because we don't lose focus from the input element, validation is never called, but is assumed to be present later on

I think we can fix this by adding a mouse down event as well here
https://github.com/microsoft/fluentui/blob/66465d35ef7dd3b9831bbaff303619212fa08915/packages/react/src/components/SpinButton/SpinButton.base.tsx#L251

### Requested priority

Normal

### Products/sites affected

Office Web Apps

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@thomabr - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. However, I see you are willing to submit a fix for this reported issue? Would you be able to share your PR with us and our team will review it. 

cc @GeoffCoxMSFT
