### ISSUE TITLE
[Feature]: Subtle transition between states on v9 Button

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#22552]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Requesting some subtle motion between interaction states on the button: 

transition: all 100ms easyEase;
https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?node-id=13150%3A21043

Note: would be nice to reuse this transition on other areas w/ simple background color changes too, such as list items, menu list items, card bgs)

### Have you discussed this feature with our team

Kay Davis

### Additional context

cc: @khmakoto @paulgildea

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by daisygeng** [comment]
Hey @khmakoto @paulgildea  I am still seeing that the v9 button doesn't have the transitions yet, could we please not close this yet?

**Comment by khmakoto** [comment]
Oops, this should have not been closed, reopening it!
