### ISSUE TITLE
[Bug]: Keyboard focus lands to slider control

### ISSUE THREAD

**Issue by anmohanty123** [microsoft/fluentui#22575]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 16.44 GB / 31.71 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.44)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/anmohanty123/pen/OJzqXRx

## Actual Behavior
Keyboard focus lands to entire slider control through which user might get affected as they will be confused to navigate further.

## Expected Behavior
Keyboard focus lands on slider point control under Timeline section so that user could easily navigate further.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thank you for filing this item with us. I'll add this to our contributors queue as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
