### ISSUE TITLE
Versioned v9 docsite

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#22580]
- versioned docs (partners can switch among versions)

**Comment by ling1726** [comment]
This can be achieved through chromatic [versioning through github releases](https://www.chromatic.com/docs/composition#versioning). We would need to create a GitHub release each time we release v9 **and** publish chromatic from the same commit.

Then chromatic will have a `metadata.json` where the release tags and their corresponding urls are available. A custom component on the storybook acting as a version picker can then do a simple fetch to get the list of available versions. Partially implemented in #22142

**Comment by miroslavstastny** [comment]
Moving to v-build for triage.

**Comment by micahgodbolt** [comment]
Is there any concern with haveing too many versions in switcher? Should we have switching for all minor and patch releases, or just the minors? Do we allow content updates between versions? OR is the version locked into the docs at the time of the release?

**Comment by JustSlone** [comment]
Moving this over to cxe-prg and assigning to @tudorpopams to consider for the future Fluent 2 website. This would be a good thing to think about in terms of the final website. I think we're OK without it for now.
