### ISSUE TITLE
Styles/mixins references

### ISSUE THREAD

**Issue by MaksimIlyenia** [microsoft/fluentui#22584]
Hello. How to migrate from sp-office-ui-fabric to fluentui?
My SCSS file has mixin references:
`@import "~office-ui-fabric-react/dist/sass/References.scss";
@import "~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss";`

I'm using: $ms-color-themeLighter; mixin.

I've found `@import "@fluentui/react/dist/sass/References.scss";` But in does not works.

**Comment by gouttierre** [comment]
Thank you for reach out to us. Please, review our documentation on migrations
	
- [Migration from Fabric (v4.x – v5.x)](https://github.com/microsoft/fluentui/wiki/Fabric5)
- [Migration from Fluent UI React (v6.x - v7.x)](https://github.com/microsoft/fluentui/wiki/Fabric-7)
- [Migration from Fluent UI React (v7.x – v8.x)](https://github.com/microsoft/fluentui/wiki/Version-8-migration-guide)

**Comment by JustSlone** [comment]
Thanks for the question, closing this out. If there is still an issue let us know!
