### ISSUE TITLE
@fluentui/react-components: React 18 support

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#22581]
React 18 was released.
Test with React 18, create list of issues, triage them.

**Comment by denis-sokolov** [comment]
This might be a duplicate of #22241.

**Comment by layershifter** [comment]
@denis-sokolov it's not, this issue is dedicated to `@fluentui/react-components`.

**Comment by micahgodbolt** [comment]
This was fixed in #22592 V9 is currently working in React 18. Upgrading the repo to use v18 is a whole nother story though.
