### ISSUE TITLE
[Bug]: Slider does not update prop changes from useEffect()

### ISSUE THREAD

**Issue by svmvnthvs** [microsoft/fluentui#22597]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 5.64 GB / 15.60 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.39)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/svmvnthvs/pen/KKZEEqx?editors=1111

## Actual Behavior
Using your finger on laptop screen, drag Slider thumb to change Slider value. The slider thumb can not be moved even though `setShouldUpdateSlider(true)` is updated. 

## Expected Behavior
Expect that when  `setShouldUpdateSlider(true);`, the slider thumb can be moved with a TouchEvent.

## Notes:
- Works as expected with MouseEvent
- Worked as expected with @fluentui/react 7.174.1, buggy behavior from @fluentui/react 8.37.3

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by svmvnthvs** [comment]
Repro without hammer on fluent 8 (buggy behavior): https://codepen.io/svmvnthvs/pen/QWaoXOx?editors=1111
Repro without hammer on fluent 7 (expected behavior): https://codepen.io/svmvnthvs/pen/vYpPqQm?editors=1111

**Comment by micahgodbolt** [comment]
This turned out to be an issue of how to disable a slider. Worked with them offline
