### ISSUE TITLE
[Bug]: Combobox does not allow user to type beyond 3 characters

### ISSUE THREAD

**Issue by JonathanCopeland** [microsoft/fluentui#22602]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
All browsers
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/combobox#feedback

## Actual Behavior
User starts tying in the combobox to limit the number of items in the list. After typing the third character they are unable to type anymore characters.  

## Expected Behavior
User starts tying in the combobox to limit the number of items in the list. The user is able to type as many characters as they would like. 

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Can't repro this at all. I go to that given url, click on any freeform combobox and I can type as many characters as I want.
