### ISSUE TITLE
msft-fluent-ui-bot should give a warning first

### ISSUE THREAD

**Issue by mbest** [microsoft/fluentui#22615]
[msft-fluent-ui-bot](https://github.com/msft-fluent-ui-bot) closes issues after 180 days of inactivity. This requires people to open a new issue if it's still a problem, but I think it would be better to first post a warning that the issue will be closed in 7 days so that anyone interested can post an update. 

See #20034

**Comment by gouttierre** [comment]
@mbest - Thank you for reaching out to us. We will take your request up for review and further team discussions.

**Comment by gouttierre** [comment]
Issues shelf life has been extended.
