### ISSUE TITLE
FocusZone should provide a method to override distance calculation heuristic in `moveFocus`

### ISSUE THREAD

**Issue by statm** [microsoft/fluentui#22649]
### Environment Information

- **Package version(s)**: v8
- **Browser and OS versions**: Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.50)

### Describe the issue:

Office Online relies on `ContextualMenu` component to render complex menus, where navigation flows are not necessarily one-dimensional. In this menu, for example, the 'Paste Options' section is a horizontal-flowing `Stack` with 6 buttons:

![image](https://user-images.githubusercontent.com/1220327/165392159-542f456b-4cd2-4713-b143-90cbcdad44c0.png)

For this type of contextual menu, we have two options available for the `direction` prop of the menu's inner `FocusZone`. However, either one of them are less than ideal:

#### 1. Use `FocusZoneDirection.bidirectional`
![focuszone-bidi](https://user-images.githubusercontent.com/1220327/165393449-0e9b561b-8af6-4a3c-8aca-1e9f3ea48a5f.gif)
When user presses <kbd>↓</kbd> key on the regular menu item (Rewrite), the focus goes to the 4th item in the gallery instead of the 1st one, as it has the shortest distance from the center of the currently focused item.

#### 2. Use `FocusZoneDirection.domOrder`
![focuszone-dom](https://user-images.githubusercontent.com/1220327/165394571-d9236896-d615-440c-bda7-44d8d5111c2a.gif)
When user presses <kbd>↓</kbd> key on the regular menu item (Rewrite), the focus goes to the 1st item in the gallery. However, following <kbd>↓</kbd> keypresses will move the focus to the right (as the next gallery items are line up in that direction).

Either case is not 100% what we want to achieve: **when focus moves into the gallery section, it lands on the first item; when arrow keys are pressed, focus will move towards the 'natural' direction**.

When `FocusZone.moveFocus` is trying to decide the next element to focus, it uses a custom heuristic function that's provided by the caller. If the function provides some level of customizability (e.g. external user being able to provide the algorithm to calculate the 'anchor' point from current focus rect), the aforementioned 'natural' keyboard navigation will be achievable.

### If applicable, please provide a codepen repro:

https://codesandbox.io/s/focus-zone-alignment-92nrmx?file=/src/index.tsx

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Office Online

**Comment by JustSlone** [comment]
@jurokapsiar, @khmakoto, @mshoho. Looking forward, will [Tabster](https://github.com/microsoft/tabster) handle this need?

**Comment by hoho** [comment]
@JustSlone I suppose Tabster's recent Mover adjustment for grid behaviour should give the desired result in this case. @ling1726 is already pulling it somewhere, so it likely should be good even without custom function.

**Comment by tudorpopams** [comment]
Hello @statm , how do you feel about @hoho 's suggestion? Is it a good solution to the problem?

**Comment by statm** [comment]
@tudorpopams Sounds good!
