### ISSUE TITLE
xAxisTickCount does not work

### ISSUE THREAD

**Issue by scootercop** [microsoft/fluentui#22657]
### Environment Information

- **Package version(s)**: 5.9.26
- **Browser and OS versions**: Microsoft Edge Version 100.0.1185.50 (Official build) (64-bit), Windows 11 Enterprise Version 21H2

### Describe the issue:

xAxisTickCount property is not working.

#### Actual behavior:

Chart shows all the data points in the x-axis no matter the value of xAxisTickCount

#### Expected behavior:

It should only show the number of ticks defined in xAxisTickCount

### If applicable, please provide a codepen repro:
```

    public render() {
        return <VerticalBarChart chartTitle="Data Volume per day" data={this.dataVolume} height={400} barWidth={10} hideLegend={true} xAxisTickCount={2} />;
    }

```

dataVolume=

```
   return data.map((value, index) => {
                        return {
                            x: index,
                            xAxisCalloutData: moment.utc(value.date).format("MM/DD/YYYY z"),
                            y: value.rowCount,
                        };
                    })
```

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: Blocking

Products/sites affected: MSFT internal

![image](https://user-images.githubusercontent.com/7453097/165462018-7381306a-cd03-4f4a-b6d9-f1374aa0ab1d.png)

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@Raghurk - Would you be able to look at this one? Thanks

**Comment by AtishayMsft** [comment]
Thanks for reporting. We will look into this issue.

**Comment by AtishayMsft** [comment]
Debugged this issue offline with Naval. This issue was happening because the caller was passing the data as string. xAxisTickCount does not work for string axes. The user needs to define the ticks explicitly from their side.
