### ISSUE TITLE
[Bug]: v9 Label: Disabled, dark mode: Elements must have sufficient color contrast

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#22661]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
vr-tests storybook
```

### Are you reporting Accessibility issue?

yes

### Reproduction

vr-tests storybook

## Actual Behavior
Label: Disabled, dark mode: Elements must have sufficient color contrast

## Expected Behavior
Contrast needs to be sufficient

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
After talking to design and Sarah, this is acceptable behavior by Label. Disabled states are not required to follow contrast ratios, but I will add a note on the spec.
