### ISSUE TITLE
[Feature]: SwatchColorPicker should support custom svgs

### ISSUE THREAD

**Issue by rachitkumar13** [microsoft/fluentui#22687]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Currently, the SwatchColorPicker takes the fill attribute(RGB color) as an input which is rendered as SVG. 
This new feature requests the picker to support fill='url(#some_url)'

### Additional context

![1b7808c7-8ed3-44fb-8d9c-332876993a32](https://user-images.githubusercontent.com/6224197/165731500-33a8fc53-6623-4ec8-a5b1-c9424c75d5ae.jpg)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.

**Comment by JustSlone** [comment]
@rachitkumar13 assuming this is feasible without an overhaul of the colorpicker, would you be interested in working with someone on our team to contribute this change?
