### ISSUE TITLE
Misnaming of `react-text` wrapper components

### ISSUE THREAD

**Issue by andrefcdias** [microsoft/fluentui#22700]
### Describe the issue:

Due to the renaming of Fluent typography presets, `react-text` wrapper component names no longer match with the design.

#### Existing components
Headline -> Subtitle1
SubHeadline -> Subtitle2
Body -> Body1
Caption -> Caption1

#### Missing components
Caption2

**Comment by Hotell** [comment]
not sure I understand what needs to be done ? to add `Caption2` component ?

this should also be prioritized for v9 stable correct ?
