### ISSUE TITLE
Update keyboard events to use key or code

### ISSUE THREAD

**Issue by ewylie25** [microsoft/fluentui#22763]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

When trying to update our unit tests to RTL userevent v14, we noticed that a handful of fluent v8 components would not trigger event callbacks when enter was typed. This is because the default user event key mappings do not include keyCodes by design. Per the [userEvent repo](https://github.com/testing-library/user-event/issues/842#issuecomment-1019528148), it seems like this is an intentional change on their part since keyCodes are deprecated. 

As a work around, we can use fireevent, but it would be nice to see the fluent components updated to use key or code, either in place of keyCode or in addition to. Maybe this work is being done in v9 already, just wanted to raise it in case it's not.

Components that we found were affected:
 - SearchBox
 - ComboBox

We also noticed what seemed like heavy usage of [UIEvent.which](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which ), which is flagged by MDN as not suitable for production usage, so it seemed odd. 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tonyhallett** [comment]
FocusZone uses 

https://github.com/microsoft/fluentui/blob/1c9722eec05676468f4c353da7353cccb281b998/packages/react-focus/src/components/FocusZone/FocusZone.tsx#L164

https://github.com/microsoft/fluentui/blob/1c9722eec05676468f4c353da7353cccb281b998/packages/react-focus/src/components/FocusZone/FocusZone.tsx#L680

So fireEvent necessary here for testing keyboard navigation of a Pivot.

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.

**Comment by JustSlone** [comment]
correct, v9 will move away from use of KeyCodes (as well as UIEvent.which). 

We're not planning to update v8 if someone is fairly confident this can be done in a backwards compat way that won't regress perf we'd consider a PR contribution. Let us know!
