### ISSUE TITLE
WCAG 2.2 changes

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#22776]
This is an Epic tracking all of the changes that need to happen to adhere to WCAG 2.2:

- Components with an underline focus will need to be changed to address the "Minimum Area" section of the [Focus Appearance specification](https://w3c.github.io/wcag/understanding/focus-appearance-minimum.html) in WCAG 2.2. Components that are involved in this are:
  - Combobox
  - Input
  - Link
  - Select
  - Spinbutton
  - Textarea

**Comment by flora8984461** [comment]
Is there any insight about when will this get resolved? Thank you!

**Comment by v-sudmandal** [comment]
Is there any update on this bug, when it will be fixed? Thanks!
