### ISSUE TITLE
[Bug]: When Action button used with aria-description, the description is read out twice, once before the text of button is announced, and once after

### ISSUE THREAD

**Issue by nikita-msft** [microsoft/fluentui#22799]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 1.31 GB / 15.75 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.50)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/nikki30/pen/oNEgmPb

## Actual Behavior
Screen reader reads out:
aria-description + text + aria-description

In the codepen example:
Screen reader reads "This is a button. Hello World button. This is a button".

## Expected Behavior
Screen reader should read out:
text + aria-description

In the codepen example:
Screen reader should read "Hello World button. This is a button".

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@nikita-msft - thank you for filing this issue with. To set expectations, we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. However, I see you are willing contribute to this issue, that is great news! 
If you have a solution at hand and would like to contribute towards it, please, share your PR for us and the team will review it.

cc @smhigley
