### ISSUE TITLE
[Bug]: Clicking on context menu target doesn't dismiss context menu

### ISSUE THREAD

**Issue by atsu-suzuki** [microsoft/fluentui#22813]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Package Version: 8.67.2

System:
    OS: Windows 10 10.0.19044
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.32)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/molinger/pen/ZEXjpdL

## Repro steps

1. Right-click one of the buttons to show context menu.
2. Left-click another button.
3. Verify that menu is dismissed.
4. Right-click a button to show context menu.
5. Left-click the button that shows the context menu.

Essentially, reopening this issue: https://github.com/microsoft/fluentui/issues/21207

## Actual Behavior
Context menu is not dismissed.

## Expected Behavior
Context menu is dismissed.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thank you for filing this item with us. I'll add this to our contributors queue as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
