### ISSUE TITLE
[Bug]:  @fluentui/react Breadcrumb item onRender console error

### ISSUE THREAD

**Issue by maxburs** [microsoft/fluentui#22821]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 434.09 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 96.0
    Safari: 15.4
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/genuine_smiles/pen/abqOzBV

## Actual Behavior
Setting the "onRender" property of a @fluentui/react Breadcrumb item causes a console error.

## Expected Behavior
No console error

### Logs

```shell
react-dom.development.js:82 Warning: Unknown event handler property `onRender`. It will be ignored.
    in span (created by ResizeGroupBase)
    in li (created by ResizeGroupBase)
    in ol (created by ResizeGroupBase)
    in div (created by t)
    in t (created by ResizeGroupBase)
    in div (created by ResizeGroupBase)
    in div (created by ResizeGroupBase)
    in div (created by ResizeGroupBase)
    in div (created by ResizeGroupBase)
    in ResizeGroupBase (created by t)
    in t (created by Styledt)
    in Styledt (created by Content)
    in div (created by ThemeProvider)
    in ThemeProvider (created by Content)
    in Content
```

### Requested priority

Low

### Products/sites affected

dataexplorer.azure.com

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thank you for filing this item with us. I'll add this to our contributors queue as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
