### ISSUE TITLE
[Bug]: focus() does not work on Breadcrumb component after a resize.

### ISSUE THREAD

**Issue by scottdurow** [microsoft/fluentui#22844]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz    
    Memory: 11.06 GB / 31.55 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.32)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codepen.io/scottdurow/pen/gOvpdjN

## Actual Behavior
After resize has triggered the ResizeGroup to reduce/expand results in the componentRef.current instance to be null. This means that calling focus on the componentRef does not work and the component does not receive focus.

1. Open https://codepen.io/scottdurow/pen/gOvpdjN
2. Select 'Set Focus'  and then use arrow keys to navigate the breadcrumb trail
3. Resize the browser
4. Select 'Set Focus' again - notice that the focus is not set on the breadcrumb component (because the FocusZone componentRef.current is now null.

This seems to be because more than one FocusZones are rendered and so the componentRef.current is nulled on component unmount of the secondary FocusZones.

## Expected Behavior
Calling focus after resize should still set focus

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thank you for filing this item with us. I'll add this to our contributors queue as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
