### ISSUE TITLE
[Bug]: Should V9 Text add styles to root by default (without any props)?

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#22855]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
v9
```

### Reproduction

see description

## Actual Behavior
Text uses following styles even when no props are used:
```
root: {
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
    fontWeight: tokens.fontWeightRegular,
    textAlign: 'start',
    display: 'inline',
    whiteSpace: 'normal',
    ...shorthands.overflow('visible'),
    textOverflow: 'clip',
},
```

## Expected Behavior
most of the styles are equal to default styles coming from provider, so Text just unexpectedly overrides styles if inserted in a slot of another component.

Should Text be changed to not override any styles by default and only apply styles when necessary? This would mean:
- adding `lineHeight: tokens.lineHeightBase300,` to useProviderStyles
- removing any default styles from Text if no props are used - as the styles are equal to the defaults for span or coming from the provider
- adding a variant for regular Text, if somebody still wants to force-apply the regular font size

### Requested priority

Blocking

### Products/sites affected

Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by andrefcdias** [comment]
Initially `Text` was seen as a way to steer users into using typography that is aligned with Fluent, which is why `Text` provides the base styles for `Body` by default and we also have the type wrappers for ease of use.
Can you clarify that as a user you'd prefer `Text` to not provide any styles by default? If so, what is the proposed usage and value of a style less `Text`?

**Comment by andrefcdias** [comment]
> This feels like a substantial change to the behavior of `Text`. Should we consider it a breaking change?

From what I understood, the theme provider is already applying styles by default and taking the role of `Text` in getting Fluent typography used by default. If that is the case and the applied styles match, then `Text` wouldn't need to apply them and nothing changes for our users. It will be a breaking change, however, for scenarios where these don't match.

**Comment by jurokapsiar** [comment]
Agree - that is the idea, defaults come from the Provider and do not have to be re-applied in each Text usage. That way, you can just use <Text weight="semibold" /> to modify the style coming from the parent elements and only apply the weight on top of them. That will make Text easier to use for the scenarios where it is used in Teams at least.

**Comment by jurokapsiar** [comment]
correct, see packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderStyles.ts

**Comment by jurokapsiar** [comment]
I would propose: let's not add line-height in the provider styles and let's not use in Text unless `size` prop is explicitly used.

**Comment by andrefcdias** [comment]
That would mean incoherence with the design spec and breaking changes for Text users. If the styles applied in the Provider are supposed to enforce a default style according to design, what is the purpose of excluding `line-height` from it?

**Comment by jurokapsiar** [comment]
I think you can try adding line-height to Provider styles, but I don't know if that would work for all partners - would they expect line-height to be set by default? Is it something we can check with design?

**Comment by layershifter** [comment]
The decision was to keep things as they are.
