### ISSUE TITLE
new tsconfig.lib.json fails `yarn build:local`

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#22851]
Run `yarn build:local` from a package within `packages/react-components`

```
$ tsc -p ./tsconfig.lib.json --module esnext --emitDeclarationOnly && node ../../../scripts/typescript/normalize-import --output ./dist/packages/react-components/react-image/src && yarn docs
LING /home/lingga/fluentui/packages/react-components/react-image/dist/packages/react-components/react-image/src
/home/lingga/fluentui/scripts/typescript/normalize-import.js:41
    throw new Error(`${sourceDir} doesn't exist`);
```

notice the `declarationDir` of the tsconfig.lib.json
https://github.com/microsoft/fluentui/blob/e465622ca241f3dd0534da50823a51e7311fd9ef/packages/react-components/react-image/tsconfig.lib.json#L8

The correct output path for `build:local` should be `./dist/types/packages/react-components/react-image/src`

**Comment by Hotell** [comment]
thanks for reporting, I thought we fixed it in our generator but looks like we did not :D
