### ISSUE TITLE
[Bug]-Regression: Absolute-positioned modeless dialogs/modals are no longer visible or repositioned since 8.64.0.

### ISSUE THREAD

**Issue by mbrzakovic** [microsoft/fluentui#22878]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.41 GB / 15.84 GB
  Browsers:
    Chrome: 101.0.4951.54
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.50)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

No.

### Reproduction

https://codepen.io/mbrzakovic/pen/BaYoPZJ

## Actual Behavior
Go to repro link, replace: @8.63.1 with @8.64.0.
Notice that Modal position changes.

## Expected Behavior
No change to Modal position.

In some cases, with specific styling on other elements, this causes the Modal/Dialogs to disappear.
Additionally, when there is position specification (remove top,left) it seems that 'center' behavior has also regressed.

### Logs

```shell
Instead of Logs I will provide my hunch to why this happened and discussion.

I think the cause is that this PR: https://github.com/microsoft/fluentui/pull/22295 changed the order between the high-level 'layer' element and the client's potential root element. (layer element was first, now it is last as it is appended inside <body>).

Discussion: This is surely a regression, but is the current behavior better now?
I feel that for me as a client, I'd expect that absolute position of Dialogs/Modals means the same as 'fixed' position, as I expect that positioning is done based on (0,0) starting point on some implicit overlay element.
```

### Requested priority

Normal

### Products/sites affected

wd

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Looks like the difference is where the layers are being rendered

8.63.1 (layer after content - expected)
![image](https://user-images.githubusercontent.com/1434956/167502867-406b74d3-f30b-495a-a2be-e65deca2c7db.png)


8.64.0 (layer before content - bug)
![image](https://user-images.githubusercontent.com/1434956/167502839-778bcec9-0be8-4c13-a86f-99fdbb6fb979.png)

**Comment by micahgodbolt** [comment]
Can you describe what it is you are trying to accomplish? I don't think adding absolute positioning to the dialog is the best way to approach this.

**Comment by mbrzakovic** [comment]
> Can you describe what it is you are trying to accomplish? I don't think adding absolute positioning to the dialog is the best way to approach this.

I'd like to create a modeless dialog/model that will be positioned on specified place (relative to the screen).

As mentioned in the description/Logs, I am aware that we could mitigate the regression by specifying style: position: fixed
however, it's hard for me to come up with valid reason why position: absolute should not have the same behavior in this case.

**Comment by micahgodbolt** [comment]
Can you verify if this is still an issue? I believe work has been done to resolve this.

**Comment by mbrzakovic** [comment]
Checked on v8.77.2 - unfortunately issue still exists.

Feel free to use minimal repro to double-check.
- In HTML / <script src="//unpkg.com/@fluentui/react@8.63.1/dist/fluentui-react.js"></script> replace @8.63.1 with newest version. No visual change is expected.

**Comment by blustemy** [comment]
Hi, I'm also reproing this issue. I've made a small repro case on CodePen:
https://codepen.io/blustemy/pen/VwXbdKp/

As a workaround, there's a fix that can be made by styling the `Modal` component:
https://codepen.io/blustemy/pen/KKomeoj/

In the CodePen, I'm targeting the specific `8.80.0` version on `unpkg`, so this may be slow to load.

```jsx
<Modal isModeless={true} styles={modalStyles}>
  ...
</Modal>
```

```js
const modalStyles: Partial<IModalStyles> = {
  root: {
    position: "fixed",
    top: 0,
    left: 0,
    pointerEvents: "none"
  },
  main: {
    pointerEvents: "auto"
  }
};
```
