### ISSUE TITLE
Bug: Detailslist cannot resize on smartphone

### ISSUE THREAD

**Issue by yosafatkesuma** [microsoft/fluentui#22873]
#### Actual behavior:

column is not resizable

#### Expected behavior:

column is resizable

[### Reproduce:][https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist)

### Priorities and help requested (not applicable if asking question):

Requested priority: (Blocking)

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. I was unable to reproduce your reported issue. Please, retest the use case and remember to add a code-pen to your issues to make it easier for us to investigate. Thank you

**Comment by yosafatkesuma** [comment]
this is the example, i record it

https://user-images.githubusercontent.com/44065042/170840524-be5d73fe-f8b8-4701-b0de-0f6f7fecab64.mp4
