### ISSUE TITLE
[Bug]: SpinButton API does not allow correct plural translation

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#22882]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
any system
```

### Are you reporting Accessibility issue?

no

### Reproduction

v9 storybook

## Actual Behavior
SpinButton strings have a simple replace method that transforms the default string and adds number to it.
This however does not allow a correct translation in languages that have different form of plurals depending on the amount

## Expected Behavior
SpinButton should accept a callback to get the string, so that it can be used with standardized i18n libraries.

https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-spinbutton/src/components/SpinButton/SpinButton.strings.ts

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
talking with @smhigley about this, and one good approach would be to not use the number in the string at all, and not need a plural option. Sighted users don't see what the step increment is, so we aren't given unsighted users a different experience. Also, if the user can provide a custom string, they can include the 'step' prop in that string on their own. It's not something generated by the control.
