### ISSUE TITLE
[Bug]: react-icons-mdl2-branded please update react peer dependency

### ISSUE THREAD

**Issue by tonyhallett** [microsoft/fluentui#22895]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 2.13 GB / 15.59 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.39)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

n/a

## Actual Behavior
Cannot use with react 17

https://github.com/microsoft/fluentui/blob/master/packages/react-icons-mdl2-branded/package.json
```
  "peerDependencies": {
    "@types/react": ">=16.8.0 <17.0.0",
    "@types/react-dom": ">=16.8.0 <17.0.0",
    "react": ">=16.8.0 <17.0.0",
    "react-dom": ">=16.8.0 <17.0.0"
  },
```

Yet is using "@fluentui/react-icons-mdl2": "^1.3.8",
e.g
```
import * as React from 'react';
import { createSvgIcon } from '@fluentui/react-icons-mdl2';

const AADLogoIcon = createSvgIcon({
  svg: ({ classes }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2048 2048" className={classes.svg}>
      <path d="M2048 1310l-1024 598L0 1310 1024 140l1024 1170zm-526 60q30 0 57-11t46-31 31-47 12-57q0-30-11-56t-32-46-46-31-57-12q-32 0-62 14l-314-359q23-35 23-79 0-30-11-56t-31-46-46-31-57-12q-30 0-56 11t-47 31-31 46-12 57q0 21 6 41t18 38l-314 359q-30-14-62-14-30 0-56 11t-47 31-31 46-12 57q0 30 11 57t31 46 47 31 57 12q28 0 54-10t46-31l257 150q-5 20-5 36 0 30 11 56t32 47 46 31 57 12q30 0 56-11t47-32 31-46 12-57q0-16-5-36l256-150q20 20 46 30t55 11zM962 787l10 4q5 2 12 4v580q-35 11-61 35l-257-150q5-20 5-36 0-44-23-79l314-358zm438 358q-23 35-23 79 0 20 4 36l-256 150q-26-24-61-35V795q6-2 11-4t11-4l314 358z" />
    </svg>
  ),
  displayName: 'AADLogoIcon',
});

export default AADLogoIcon;
```

which has https://github.com/microsoft/fluentui/blob/master/packages/react-icons-mdl2/package.json

```
  "peerDependencies": {
    "react": ">=16.8.0 <18.0.0"
  },
```

## Expected Behavior
Can use

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@tonyhallett - thank you for filing this issue with. To set expectations, we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. However, I see you are willing contribute to this issue, that is great news! 
If you have a solution at hand and would like to contribute towards it, please, share your PR for us and the team will review it.

**Comment by tonyhallett** [comment]
@gouttierre pr in draft status waiting for review

**Comment by jcksonhe** [comment]
Any update on this?

**Comment by tonyhallett** [comment]
I am not getting any joy with any of my issues https://github.com/microsoft/fluentui/issues/created_by/tonyhallett
