### ISSUE TITLE
[Feature]: Dropdown Item uses Avatar component

### ISSUE THREAD

**Issue by kailunh** [microsoft/fluentui#22892]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### Describe the feature that you would like added

When using the dropdown component, the dropdown item only take an url for its image.  However, if we can use the avatar component instead of an image url here, we can have a default  avatar with user's initial when there are no image. For the current dropdown, a bad url will lead a broken avartar here.

### Additional context

![image](https://user-images.githubusercontent.com/20564679/167231463-05f05bfd-5356-4338-90a6-7b7f6027a7c2.png)
![image](https://user-images.githubusercontent.com/20564679/167231530-19104825-bd75-4e31-9515-ec18beb4c385.png)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gouttierre** [comment]
@jurokapsiar - would you and your team be able to review this feature request? Thank you

**Comment by jurokapsiar** [comment]
Hi, it is possible to replace any slot using children props: https://codesandbox.io/s/fluent-ui-example-forked-pcsfdj?file=/example.js

See documentation about slot render callback for details: https://fluentsite.z22.web.core.windows.net/0.64.0/shorthand-props#using-render-props
