### ISSUE TITLE
[Bug]: Dropdown selectedKey and selectedKeys confusion

### ISSUE THREAD

**Issue by dayadam** [microsoft/fluentui#22917]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
n/a
```

### Reproduction

https://codepen.io/PatoBeltran/pen/YMMaex

## Actual Behavior
referencing this https://github.com/microsoft/fluentui/issues/8883

What is even worse, `selectedKey` has been removed from the documentation https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown

I had no idea there was even `selectedKey` until I found this bug report that was ignored 

## Expected Behavior
a working framework 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@dayadam - thank you for filing this issue with. To set expectations, we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. However, I see you are willing contribute to this issue, that is great news! 
If you have a solution at hand and would like to contribute towards it, please, share your PR for us and the team will review it.

**Comment by JustSlone** [comment]
Let's get the v8 documentation updated to explain this issue. This should no longer be an issue in the updated [Dropdown in v9](https://react.fluentui.dev/?path=/docs/preview-components-dropdown--default).
