### ISSUE TITLE
Different between @fluentui/merge-styles and @griffel

### ISSUE THREAD

**Issue by lexuantien** [microsoft/fluentui#22925]
### Discussed in https://github.com/microsoft/fluentui/discussions/22924

<div type='discussions-op-text'>

<sup>Originally posted by **lexuantien** May 11, 2022</sup>
Excuse me, I have a question about [@fluentui/merge-styles](https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/README.md)  and [@griffel](https://github.com/microsoft/griffel). Both of them are Css-in-JS. 
- So what is the diffrent ?
- Can I use both in project ?</div>

**Comment by khmakoto** [comment]
Answered in #22924, so closing this one.

**Comment by lexuantien** [comment]
thanks
