### ISSUE TITLE
Add documentation for v9 Menu / Popper content lazy loading

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#22928]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

To reduce the cost of loading UX code during initial render, consumers can consider lazy loading contents of the Menu / Popups.

Document the best way to achieve lazy loading / rendering of content.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by layershifter** [comment]
Check https://www.npmjs.com/package/use-sidecar

**Comment by bsunderhus** [comment]
I guess you can include every single modal in this issue also @jurokapsiar ? (Tooltip and Dialog)

**Comment by layershifter** [comment]
keep open

**Comment by layershifter** [comment]
keep open
