### ISSUE TITLE
Documentation: Add Inline Stories to Upgrade Guides

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#22988]
## Problem

Currently all the code examples in our v8/v0 --> v9 upgrade guides are static code blocks.

## Solution

These examples should be live code with a "show code" block. This will ensure all examples are working code while providing readers an easy way to see the source.

[Example for adding an inline story to mdx](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/mdx.md#basic-example)

**Comment by JustSlone** [comment]
Moving forward to Unified Board and assigning to @GeoffCox to track, feel free to won't fix if you have other plans for the migration code examples.
