### ISSUE TITLE
[Feature]: PivotItem - alwaysRender={'on'|true|'off'|false|'lazy'}

### ISSUE THREAD

**Issue by kevinfairclough** [microsoft/fluentui#23018]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

It would be nice if we could lazy render the PivotItem in addition to alwaysRender={true}

Setting it to 'lazy' would not render until it selected and then not unmount when selecting another PivotItem.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gouttierre** [comment]
Thanks for filing this item with us. I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.
