### ISSUE TITLE
[Bug]: ContextualMenu secondary text can appear clipped

### ISSUE THREAD

**Issue by brhallin** [microsoft/fluentui#23039]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 16.92 GB / 31.84 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.47)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/brhallin/full/jOZqjgK

## Actual Behavior
At 100% magnification, the secondary text is getting clipped/hidden by the scrollbar (It should read "Secondar**y**"). This occurs when using the default Windows 11/Edge browser scrollbar style.
 
It seems that secondary text combined with a scrollbar is all that's required to repro the bug. While the secondary text's _right padding is scaled_ when zooming, the default _scrollbar is not scaled_ so it doesn't fully overlap the secondary text at all magnifications.
 
What this means is that at some zoom levels, it doesn’t look like the secondary content is being clipped, but it is – it’s just that clipped part is whitespace, not text.

### 100% zoom, default scrollbar
The clipping is obvious.
![image](https://user-images.githubusercontent.com/99288637/168874921-5601fc82-2bd1-44ed-91ff-8669f791194f.png)

### 175% zoom, default scrollbar
Here you can see the “y” in “Secondary” is _just_ clipped.
![image](https://user-images.githubusercontent.com/99288637/168874904-0293704a-2515-4378-8843-739aa6eb0862.png)

However, if we use custom scrollbar CSS, the scrollbar will be scaled, so it will overlap at all magnifications. Please refer to this Codepen sample: **[https://codepen.io/brhallin/full/vYppdJG](https://codepen.io/brhallin/full/vYppdJG)**
 
### 400% zoom, custom scrollbar:
At all magnifications, the scrollbar overlaps the secondary text. This is due to the custom scrollbar being scaled along with the content. In the Dynamics 365 CRM product, we make use of custom scrollbars.

![image](https://user-images.githubusercontent.com/99288637/168874868-f8b5e7db-6034-4b39-9b6b-abdcf68efa65.png)

## Expected Behavior
Secondary text appears as expected at all zoom levels.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@brhallin - Thanks for filing this issue with us. I can confirm the repro stated in local testing. To set expectations the developers will review this issue once capacity allows.

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue?
