### ISSUE TITLE
[Feature]: Add support for eslint@^8 to @fluentui/eslint-plugin

### ISSUE THREAD

**Issue by stephenjust** [microsoft/fluentui#23048]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Currently @fluentui/eslint-plugin is not usable on React 17 (with compatible react-scripts 5) because react-scripts pulls in eslint 8.

Eslint 8 has some breaking changes which plugins need to adopt.

Fluentui should update its dependencies / peer dependencies to unblock eslint 8 support.

### Have you discussed this feature with our team

No

### Additional context

In particular, the breaking change from eslint is that certain rules need to provide additional metadata, or eslint will bail out:
https://eslint.org/blog/2021/10/eslint-v8.0.0-released

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gouttierre** [comment]
@stephenjust - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.

cc @Hotell - I am looping you in as a fyi, I am not sure if this request falls to the vbuild team.
