### ISSUE TITLE
[Feature]: Add a HighContrastSelector string export

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#23093]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

v8 has HighContrastSelector  in style-utilities that is often used by consumers to override existing high-contrast styles. We're currently using a DIFFERENT string in v8, and it's not obvious that we are because we don't export a const for that string, and it turns out the old selector is less specific than our current one.

Adding a v9 HighContrastSelector will make it easier to override our existing media query, and keep these strings in sync in the case we change it.

it'll also remove the possible typos of devs writing the media query in styles, or inconsistencies. 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sysofwan** [comment]
This selector does not exist for Fluent v9. What is the recommendation for this?
