### ISSUE TITLE
[Bug]: Keyboard navigation doesn't highlight menu items, only fills a border

### ISSUE THREAD

**Issue by RishabBindra** [microsoft/fluentui#23104]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 64.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
Browsers:
    Safari: 15.4
```

### Are you reporting Accessibility issue?

yes

### Reproduction

Switch to high contrast theme and open a menu which contains a submenu. Navigate with keyboard and see the selected item only contain a border. Try the same with mouse, and the items will have a fill.

## Actual Behavior
<img width="328" alt="Screenshot 2022-05-20 at 2 43 01 PM" src="https://user-images.githubusercontent.com/64629695/169510005-2885965e-dcab-40e5-b55d-0d446bf2f42e.png">

The highlighted item in the submenu will only contain a border when navigated with the keyboard.

## Expected Behavior
![MicrosoftTeams-image](https://user-images.githubusercontent.com/64629695/169510205-c10062b8-ed9b-4a4d-9582-f46660776cf7.png)

The highlighted item should have a fill color as opposed to border. This is the situation seen with mouse and not keyboard.

## Other issues noticed:
The following is also noticed
- When the user enters the submenu with the keyboard, the expanded item in the parent menu doesn't get highlighted. This happens only when navigating with keyboard not in mouse. Check "item2" in the screenshots.
- When a user enters a submenu, the chevron on the parent is hidden. Check "item2" in the screenshot shared.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@jurokapsiar - would you and your team be able to investigate this issue once capacity allows.

**Comment by jurokapsiar** [comment]
Hi, this is by design:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/13742664/197306392-57525148-e66d-4deb-870c-37c00f3d41a4.png">

Please consider using style overrides if this is a requrement for a specific application.
