### ISSUE TITLE
[Bug]: Contextual Menu does not keep track of originalElement after escaping from submenu item

### ISSUE THREAD

**Issue by kmui** [microsoft/fluentui#23119]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 19.52 GB / 31.90 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.44), ChromiumDev (102.0.1227.0)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/kmui/pen/LYQLExe

### Bug Description

1. keyboard navigate to the "Click for ContextualMenu" button and press enter
2. focus should be on the first item, press esc returns focus back on the item. That is the correct behavior
3. press enter again and and press enter one more time to invoke the submenu
4. press escape twice to exit both menus.

## Actual Behavior
focus return to the button

## Expected Behavior
focus lost

note: 
I attempted a workaround by overriding onRestoreFocus. However, originalElement remain the contextualMenuItem in the first level menu item after you escape from the submenu
```
const onRestoreFocus = function (params: IPopupRestoreFocusParams) {
   if ((params.containsFocus || params.documentContainsFocus) && params.originalElement) {
      params.originalElement.focus({ preventScroll: true });
   }
};
```

note2: I declined to submit a PR for fix because I do not know the proper fix. Alternatively, providing workaround would also be much appreciated.

### Requested priority

Blocking

### Products/sites affected

Fluid

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@jean182 - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.
@khmakoto  - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by kmui** [comment]
@jean182 Yes, it still repro for me. No workaround.
