### ISSUE TITLE
Missing peerDependencies

### ISSUE THREAD

**Issue by jcreamer898** [microsoft/fluentui#23110]
### Environment Information

- **Package version(s)**: lots

### Describe the issue:

While working on midgard-yarn-strict, a strict package manager like pnpm, we found many missing peerDependencies across fluentui.

Here's the list of missings.

[onlyfluent.md](https://github.com/microsoft/fluentui/files/8741843/onlyfluent.md)

#### Actual behavior:

The missing peer dependencies cause issues in a strict package manager like midgard yarn strict which leverages those peerDependencies to correctly create symlinks across the workspaces in a large monorepo.

#### Expected behavior:

Those missing peerDependencies should be correctly added in to the packages.

### Priorities and help requested (not applicable if asking question):
I'll work a bit with this and leverage some help from my team to get these all updated.

Are you willing to submit a PR to fix? Yes

Requested priority: (Low)

**Comment by gouttierre** [comment]
@jcreamer898 - thank you for filing this issue with. To set expectations, we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. However, I see you are willing contribute to this issue, that is great news! 
If you have a solution at hand and would like to contribute towards it, please, share your PR for us and the team will review it.

**Comment by jcreamer898** [comment]
We're definitely going to help out. :)

**Comment by jcreamer898** [comment]
Sorry for the delay, we'll try to get someone on it soon.

**Comment by layershifter** [comment]
FYI: https://github.com/VincentBailly/midgard-yarn-strict/issues/9

---

We discussed this issue internally (please PM in Teams if you want to get a link to the thread) and as I understood `peerDependencies` _are_/_will be_ handled differently now in `midgard-yarn-strict`:

> What it does is that it does not resolve peer dependencies only from the parents but from the nearest ancestor that can fulfill them

So I am going to close this issue as it's no longer a problem.

P.S. We use ESLint & `import/no-extraneous-dependencies` rule to ensure that dependencies are properly declared, for example:

```
/packages/react-components/react-theme/src/index.ts
  4:1  error  '@griffel/react' should be listed in the project's dependencies. Run 'npm i -S @griffel/react' to add it  import/no-extraneous-dependencies

✖ 1 problem (1 error, 0 warnings)
```
