### ISSUE TITLE
Fluent ui pivot does not provide overflow for faritems

### ISSUE THREAD

**Issue by idolage** [microsoft/fluentui#23132]
Hi, 
Is it possible to add farItems to the Pivot control? I'm new to this framework and I want to create something like this: 

<img width="310" alt="Capture" src="https://user-images.githubusercontent.com/69623047/169786161-ffe81753-024f-4d7d-a033-908e64e974ca.PNG">

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the Pivot examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
