### ISSUE TITLE
[Bug]: GroupedList does not force update correctly

### ISSUE THREAD

**Issue by tonyhallett** [microsoft/fluentui#23135]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 7.52 GB / 15.59 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/TonyH/pen/vYdJVqY

## Actual Behavior
Is rendering old items

## Expected Behavior
Rendering current items

The problem is the [getDerivedStateFromProps](https://github.com/microsoft/fluentui/blob/8d58f08997acf595e3eb7f628123e7fa7830c394/packages/react/src/components/GroupedList/GroupedList.base.tsx#L47) as it does not update the state to include the new items from props.

Also there is unnecessary code here.

```
  public static getDerivedStateFromProps(
    nextProps: IGroupedListProps,
    previousState: IGroupedListState,
  ): IGroupedListState {
    const { groups, selectionMode, compact, items, listProps } = nextProps;
    const listVersion = listProps && listProps.version;

    let nextState = {
      ...previousState,
      selectionMode,
      compact,
      groups,
      listProps,
     //items should be in here **************************************
    };

    let shouldForceUpdates = false;

    const previousListVersion = previousState.listProps && previousState.listProps.version;

    if (
      listVersion !== previousListVersion ||
      items !== previousState.items ||
      groups !== previousState.groups ||
      selectionMode !== previousState.selectionMode ||
      compact !== previousState.compact
    ) {
      // If there are any props not passed explicitly to `List` which have an impact on the behavior of `onRenderCell`,
      // these need to 'force-update' this component by revving the version. Otherwise, the List might render with stale
      // data.
      shouldForceUpdates = true;
    }

    // this has already been done above ****************************************
    if (groups !== previousState.groups) {
      nextState = {
        ...nextState,
        groups,
      };
    }

    // this has already been done above **************************************
    if (selectionMode !== previousState.selectionMode || compact !== previousState.compact) {
      shouldForceUpdates = true;
    }

    if (shouldForceUpdates) {
      nextState = {
        ...nextState,
        version: {},
      };
    }

    return nextState;
  }
```

I would normally be happy to submit a pull request but my previous attempt failed with yarn buildci which appeared to be unrelated to the changes that I made.  See https://github.com/microsoft/fluentui/issues/23114

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@tonyhallett - thank you for filing this issue with. To set expectations, we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. Sorry, that you having issues with PR submissions.

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue? Perhaps you could help @tonyhallett and see why their previous attempt failed with yarn buildci which appeared to be unrelated to the changes that they had made. See https://github.com/microsoft/fluentui/issues/23114 for more context.

**Comment by gouttierre** [comment]
@tonyhallett - Thanks for filing this issue with us and sorry about the frustration caused. The team will investigate this issue but to set expectations the developers will only review this issue once personal capacity allows. Sorry to hear you having issues with PR submissions.

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue? Perhaps, you could see why @tonyhallett is having issues with their previous attempt failed with yarn buildci which appeared to be unrelated to the changes that they had made. See https://github.com/microsoft/fluentui/issues/23114 for more context

**Comment by layershifter** [comment]
I re-created a CodeSandbox to ensure that the problem is there: https://codesandbox.io/s/gallant-violet-ycuzhi?file=/src/App.tsx. And it's there 💥 

I also agree with @tonyhallett about changes to `packages/react/src/components/GroupedList/GroupedList.base.tsx` as they have sense:

```diff
    let nextState = {
      ...previousState,
      selectionMode,
+     items,
      compact,
      groups,
      listProps,
    };
```

```diff
-    if (groups !== previousState.groups) {
-      nextState = {
-        ...nextState,
-        groups,
-      };
-    }
-
-    if (selectionMode !== previousState.selectionMode || compact !== previousState.compact) {
-      shouldForceUpdates = true;
-    }
```

@tonyhallett I have seen that you had difficulties before, but would mind to submit these changes as a PR? Would be happy to help.

**Comment by tonyhallett** [comment]
@layershifter 
I will create a pr. Probably Tuesday as away for weekend.

**Comment by tonyhallett** [comment]
@layershifter 
https://github.com/microsoft/fluentui/pull/24385

I am getting an error when running yarn buildci.

![image](https://user-images.githubusercontent.com/11292998/184933219-f7b07dce-5e4d-481b-9db5-21fedebd65dc.png)


Sometimes is a jest async timeout.

**Comment by tonyhallett** [comment]
The PR failed due to a snapshot difference.  The snapshot from before was incorrect and the pr corrects it.  Will look at tomorrow
