### ISSUE TITLE
[Bug]: ResizeGroup: MeasurementContext inconsistent value

### ISSUE THREAD

**Issue by kisinga** [microsoft/fluentui#23133]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 335.44 MB / 32.00 GB
    Shell: 3.4.1 - /usr/local/bin/fish
  Browsers:
    Brave Browser: 92.1.27.109
    Safari: 15.4
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/old-fabric-roszxh, https://codesandbox.io/s/new-fabric-wc82es?file=/src/sample.js:51-66

## Actual Behavior
In fluentui v8, the value of `isMeasured` within `Resizegroup` is different from v6. 
  
**V8**
![image](https://user-images.githubusercontent.com/9964104/169787613-e8f61fdd-15b5-461b-a4e9-3829dc1a64f9.png)
  
**V6**
![image](https://user-images.githubusercontent.com/9964104/169787369-90c47594-3643-4a43-825b-46762f5b9f36.png)

## Expected Behavior
Consistent output 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@kisinga -  thank you for filing this issue with. To set expectations, we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. However, I see you are willing contribute to this issue, that is great news! 
If you have a solution at hand and would like to contribute towards it, please, share your PR for us and the team will review it.

**Comment by kisinga** [comment]
Hello @gouttierre
I honestly haven’t had time to work on a solution, and I may be very slow at it seeing as I have little experience with the lib.
Any pointers would be highly appreciated

**Comment by micahgodbolt** [comment]
This was an intentional change made during a major release to improve the usability of the control. Is there something stopping you from updating your code to support this new logic? We have no plans to return to this previous behavior due to the fact that it would break anyone now expecting false.
