### ISSUE TITLE
v9 Slider: Windows contrast mode ticks are low contrast

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#23149]
Slider uses `Highlight` for the track background in HCM, but the tick marks are regular text/border color, so the result is a fairly low-contrast set of ticks (depending on the theme of course, but `CanvasText` isn't really expected to be visible against `Highlight`).

![screenshot of a slider with white tick marks against a light blue track](https://user-images.githubusercontent.com/3819570/169896101-75c06072-a071-4b91-b09f-8f99efa9859f.png)

We should probably update the tick color to be `HighlightText` in forced-colors.

**Comment by micahgodbolt** [comment]
Yeah, giving HighlightText a shot and it looks much better

![image](https://user-images.githubusercontent.com/1434956/170318946-82374a69-8a67-4c0a-b016-0b9b06045b16.png)

![image](https://user-images.githubusercontent.com/1434956/170318993-176c6851-792b-4095-b2fb-2d4e3d5558b2.png)
