### ISSUE TITLE
v9 Slider: contrast for custom origin

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#23144]
The Origin example for Slider does not indicate the location of the custom origin with enough contrast, so it fails [Use of Color](https://w3c.github.io/wcag/understanding/use-of-color.html):

![screenshot of slider, showing a subtle color difference between a dark grey track and blue fill line, beginning partway down the slider](https://user-images.githubusercontent.com/3819570/169871128-8a16c204-ba50-4e6c-bf98-88b23e296962.png)

**Comment by micahgodbolt** [comment]
we don't actually have a design for origin example. looks that like that was pulled forward from v8. One solution would be to simply remove it completely
