### ISSUE TITLE
[Bug]: Website image gradients clash

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#23157]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/

## Actual Behavior
the Gradient for the storybook sidebar and the gradient for the intro page don't line up and clash causing an undesirable visual artifact. 
![image](https://user-images.githubusercontent.com/40304143/169909189-5e773961-2be2-426e-bf2d-2bd324e197a3.png)

## Expected Behavior
Gradients don't clash, images should meet at the same color value (white/background color might be a good choice so that it blends with any page). 

### Requested priority

Normal

### Products/sites affected

Fluent UI React Website

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
This following the figma design. Happy to consider tweaking if necessary. Its not a 1 to 1 reproduction

![image](https://user-images.githubusercontent.com/1434956/169909803-681a15ce-10dd-4833-b927-43cbc3259936.png)

**Comment by gouttierre** [comment]
> This following the figma design. Happy to consider tweaking if necessary. Its not a 1 to 1 reproduction
> 
> ![image](https://user-images.githubusercontent.com/1434956/169909803-681a15ce-10dd-4833-b927-43cbc3259936.png)

We will need to loop in design to help us with the color gradients.

**Comment by micahgodbolt** [comment]
The design isn't actually using a gradient, it has two colors with a large radial blur around them on the upper left and upper right. I followed that approach. The left navigation has a light white transparent background which causes the color shift you see at the border.

Happy to dial it in with the designers.
