### ISSUE TITLE
v9 Accordion storybook example

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#23150]
Low-priority issue:

The stories for Accordion have no padding around the accordions, so the focus isn't visible in high contrast mode. E.g. in this screenshot, one of the accordions is focused:

![screenshot of three accordions immediately surrounded by a thick white border that hides the focus outline](https://user-images.githubusercontent.com/3819570/169897198-6870ce6a-04f3-4a86-a67e-0fff07256f3e.png)

We could fix this by adding some padding around the accordion stories.

**Comment by kkakroo** [comment]
Checked the latest available storybook. Looks like it's fixed. 
![image](https://user-images.githubusercontent.com/8538475/189533264-d0d08e5e-657b-4597-b712-05a5df0abe18.png)

**Comment by JustSlone** [comment]
Thanks @kkakroo! 
Closing this out
