### ISSUE TITLE
[Bug]: DetailsList/GroupedList group with count 0 and showEmptyGroups false takes up space

### ISSUE THREAD

**Issue by tonyhallett** [microsoft/fluentui#23169]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 4.55 GB / 15.59 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/TonyH/pen/BaYwwRX

## Actual Behavior
The group takes space 

## Expected Behavior
The group does not take space

The GroupedList renders a List https://github.com/microsoft/fluentui/blob/808e2ac15b3558b580cca0aad3378110e9dc46a2/packages/react/src/components/GroupedList/GroupedList.base.tsx#L174
```
          <List
            onRenderCell={this._renderGroup}
```
and will return null for the empty group
https://github.com/microsoft/fluentui/blob/808e2ac15b3558b580cca0aad3378110e9dc46a2/packages/react/src/components/GroupedList/GroupedList.base.tsx#L247
```
    if (!groupProps!.showEmptyGroups && group && group.count === 0) {
      return null;
    }
```

The List though will always provide a cell https://github.com/microsoft/fluentui/blob/808e2ac15b3558b580cca0aad3378110e9dc46a2/packages/react/src/components/List/List.tsx#L610
```
    for (let i = 0; i < items.length; i++) {
      const index = startIndex + i;
      const item = items[i];

      let itemKey = this.props.getKey ? this.props.getKey(item, index) : item && (item as any).key;

      if (itemKey === null || itemKey === undefined) {
        itemKey = index;
      }

      cells.push(
        <div
          role={cellRole}
          className={'ms-List-cell'}
          key={itemKey}
          data-list-index={index}
          data-automationid="ListCell"
        >
          {onRenderCell &&
            onRenderCell(item, index, !this.props.ignoreScrollingState ? this.state.isScrolling : undefined)}
        </div>,
```

Perhaps the result of onRenderCell should determine if a cell is created.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@tonyhallett -  Thank you for filing this item with us. I'll add this to our contributors queue as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
