### ISSUE TITLE
[Bug]: react.fluentui.dev does not display anything in the canvas on iPhone

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#23162]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
iPhone 13 mini
iOS 15.4.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

react.fluentui.dev

## Actual Behavior

When I visit react.fluentui.dev I can see the sidebar but when I tap to the canvas I don't see any documentation

## Expected Behavior

I should see documentation on the canvas

https://user-images.githubusercontent.com/93940821/169922668-65171939-3390-4eb5-81a1-fa170642e286.mp4

### Requested priority

Blocking

### Products/sites affected

react.fluentui.dev

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Also tested on iPad Pro (12.9in) running iPadOS 15.4.1 and the site works fine.

**Comment by TristanWatanabe** [comment]
This was definitely issue for me at IOS 15.4.1 on Safari (using Chrome was fine) but after updating my phone to IOS 15.5, this is no longer an issue on Safari (see below)

https://user-images.githubusercontent.com/8649804/170108270-8069ab1b-f13a-40da-b293-886a46e1c708.MOV

**Comment by smhigley** [comment]
I'm still on 15.4.1, and the issue hasn't shown up for me today either for whatever reason. It wasn't consistent yesterday either, so I'm not sure if that means it's fixed or not 🙈

**Comment by GeoffCoxMSFT** [comment]
This is rendering, poorly but rendering.
