### ISSUE TITLE
[Bug]: Badge should probably have flex-shrink: 0

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#23160]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
All (tested on Windows 11, macOS, iOS)
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A

## Behavior
Several of our components include styles to ensure they display correctly when used within a flex or grid container (e.g. Badge itself has `row-gap` and `column-gap`). It seems a good idea add `flex-shrink: 0` to prevent this case as seen in our docs site:

![screenshot of a set of counter badges showing numbers overflowing the bounds of the badges](https://user-images.githubusercontent.com/3819570/169916108-55a64627-ed18-4681-a693-ba5af266cc2b.png)

The other option would be to directly style the stories themselves.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
flex-shrink only works in flex layouts. We might want to consider `min-width: max-content` instead.
