### ISSUE TITLE
[Bug]: MenuItem: uses `flex-gap` CSS property

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#23175]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

no

### Reproduction

n/a

## Actual Behavior

MenuItem uses the flex-gap property which is not supported by our browser minbar meaning some users will not have a 2px gap between children of MenuItem.

## Expected Behavior

MenuItem should only uses CSS properties fully supported by our browser minbar.

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
Per our [browser support matrix](https://github.com/microsoft/fluentui/blob/master/apps/public-docsite-v9/src/Concepts/BrowserSupportMatrix.stories.mdx) and RFC #22889, `flex-gap` is currently supported.
