### ISSUE TITLE
[Bug]: TabList story uses Overflow that is not exported from react-components

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#23179]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/bxs8r5?file=/example.tsx

## Actual Behavior
- Jump to https://react.fluentui.dev/?path=/docs/components-tablist--default
- Click "Export to CodeSandbox"
- 💣
  ```
  Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
  ```

This happens because `Overflow` is not exported from `@fluentui/react-components`.

## Expected Behavior
It should work.

### Logs

```shell
N/A
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by GeoffCoxMSFT** [comment]
@ling1726 - Are you planning on exporting overflow from react-components?
