### ISSUE TITLE
[Bug]: Spinner and `status` prop 

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#23184]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A

### Bug Description

By spec has "active" & "inactive":

![image](https://user-images.githubusercontent.com/14183168/170070699-65c21d93-5d65-4eef-bc05-0a308d42a1e5.png)

Generally we only use discriminated unions if there are more than 2 states. In this case I can't see more than 2 states ever.

https://github.com/microsoft/fluentui/blob/dd94d998cb154a07cfc70ac760707231c18e41e8/packages/react-components/react-spinner/src/components/Spinner/Spinner.types.ts#L45-L49

## Proposal 

Use `active` (that is `true` by default) or `inactive` as a prop:

```ts
<>
  <Spinner />
  <Spinner active />
  <Spinner active={false} />
<>
```

```ts
<>
  <Spinner />
  <Spinner inactive />
<>
```

### Logs

```shell
N/A
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Let's remove the `status` prop entirely and provide guidance on how to hide the spinner animation via styles and/or slots.
