### ISSUE TITLE
[Bug]: Text box allows for input > maximum limit

### ISSUE THREAD

**Issue by rohitk2497** [microsoft/fluentui#23182]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
NA
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/spinbutton

## Actual Behavior
The textbox allows the user to enter any value even if it is not within the bounded limits of the control. I.E. if the min/max limit of the spin button is 0/100, the user is able to enter 1000000 when typing in the text box which is misleading as to what values can be entered

## Expected Behavior
The user should not be able to enter values greater than the set limit. If the next character added by the user makes the value greater than the limit, the button should simply render the limit. I.E. if the max limit is 100, and the user 103 on entering the 3 the button should render 100 as it is the maximum value.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@rohitk2497  -  Thank you for filing this item with us. I'll add this to our contributors queue as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
