### ISSUE TITLE
[Bug]: Popover uses `noArrow`, `Tooltip` uses `withArrow`

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#23185]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A

## Actual Behavior
There are two components that have similar behavior, but they have different `props`.

We should agree on moving forward:
- keep it as it is (confusing for customers, we got this feedback from feature team)
- use `noArrow` and break `Tooltip`
- use `withArrow` and break `Popover`
- use different prop

### Logs

```shell
N/A
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@khmakoto Assigned to you to drive the discussion about the defaults with design. Also added @ling1726 and @behowell to keep you in the loop.
