### ISSUE TITLE
feat: add DetailsList to/in Fluent UI Web Components

### ISSUE THREAD

**Issue by hkusulja** [microsoft/fluentui#23199]
Hello,
we are comparing Microsoft Fluent UI React - web components - such as DetailsList - https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist which has lot of options, features etc.
To a Microsoft FAST Fluent UI using Blazor WebAssembly (clientside) .NET 6 .
Also, I am referencing Github issue from FAST-Blazor repo - https://github.com/microsoft/fast-blazor/issues/47
FAST-Blazor teams says to open here Github issue.

Can you please align expectations here, when and if will Microsoft FAST have a functionality on grids / DetailsList like sorting, filtering, marquee selection, justified columns, modal selection, compact mode, drag-n-drop, grouping etc.?

Current FAST and Blazor component is very very basic, with almost none mentioned features.

**Comment by hkusulja** [comment]
Can you please update status on this?
This should use this component ? https://react.fluentui.dev/?path=/docs/preview-components-table--default

**Comment by EisenbergEffect** [comment]
@chrisdholt I've assigned this to you so you can move the issue and follow up with @hkusulja

**Comment by tomkuijsten** [comment]
Waiting for an answer as well to decide which ui framework we are going to use. An advanced table component is pretty important.

**Comment by scomea** [comment]
I have a PR out to add row selection to fast data-grid.  https://github.com/microsoft/fast/pull/5786  

I think this is the only part missing from the base data grid component that would make extending it to a "details-list" challenging.  Data- grid already support custom cells with internal nav, sorting the grid is as easy as sorting the provided data array, etc...

**Comment by hkusulja** [comment]
sorting grid is not easy if you want sort per different columns, or have default sort etc. it would be great if component is updated.

**Comment by scomea** [comment]
> It would be great if the grid control would have internal sort , and ability to show in columnDefinition the arrows up/down for the column that is sorted...

I have something along those lines prototyped here on top of the current fluent data-grid: https://wonderful-sea-007305f1e.1.azurestaticapps.net/file-view-page/welcome

Source here: https://github.com/scomea/FASTPWA/blob/main/src/pages/file-view-page/file-view-panel.ts

I think it would be fairly straightforward to have components that extend data grid with that column sort functionality baked in.

**Comment by hkusulja** [comment]
@chrisdholt please reopen and update status, tx
