### ISSUE TITLE
[Bug]: `Label` has `strong` prop

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#23222]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A

### Bug Description

`Label` has two states with different font weights "regular" & "semibold":

![image](https://user-images.githubusercontent.com/14183168/170238755-98b25d51-6c91-4432-a8ff-b0787df9c966.png)

Currently it's implemented as `strong` prop, but other components (`Text`) use `weight` prop.

### Options
- leave it as it is
- replace `strong` with `weight` that includes (`regular` & `semibold`)

I see second as more futureproof solution, especially taking into account that the design team can add other value there.

### Logs

```shell
N/A
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by JustSlone** [comment]
Yep, agree on making the change. Label design spec isn't explicit and text is. The values are the same between both, it's easy to make the jump when looking at both that Label should be weight (it also works better if we add more weights in the future).

**Comment by JustSlone** [comment]
@sopranopillow do you want to pickup this change (as you're on codeowners for label)? Let us know if you agree with the change based on history/context, and if so let's get a PR out quickly

**Comment by sopranopillow** [comment]
Yeah, I can make the change. I'll make the PR quick.

**Comment by sopranopillow** [comment]
> @sopranopillow do you want to pickup this change (as you're on codeowners for label)? Let us know if you agree with the change based on history/context, and if so let's get a PR out quickly

Yeah, I can make the change. I'll make the PR quick.
