### ISSUE TITLE
[Bug]: ComboBox options disappear when another element is scrolled

### ISSUE THREAD

**Issue by juho-ms-v** [microsoft/fluentui#23248]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz    
    Memory: 7.10 GB / 15.92 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/vjheikkila/pen/NWywdpd

## Actual Behavior
`ComboBox` options disappear when another element is scrolled with `element.scrollToView` or by setting `element.scrollTop`. 

## Expected Behavior
Similar to the HTML `select` element, expected `ComboBox` options not to disappear when programmatically scrolling another element. An auto-scrolling message log component caused our `ComboBox` to be unusable, due to the `ComboBox` options disappearing. 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@juho-ms-v - Thank you for filing this item with us. I'll add this to our contributors queue as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
