### ISSUE TITLE
[Feature]: Regular expression search in ComboBox in Fluent UI

### ISSUE THREAD

**Issue by mehulparmariitr** [microsoft/fluentui#23243]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

I am using ComboBox from Microsoft's library - export declare const ComboBox: React.FC<IComboBoxProps>;

Right now ComboBox doesn't support regular expression search. For eg - if I search for "America" it will give no results for "United States of America". It would only appear if I type United.

Is there any way to achieve it in Fluent UI?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mehulparmariitr** [comment]
Can someone please update on this?

**Comment by JustSlone** [comment]
Right, this is about fuzzy search or partial matches in ComboBox. @mehulparmariitr, do you have an example of what you are looking to accomplish here so we understand the scenario better?

We don't have plans to add this to the v8 ComboBox, but this is something we are considering for the updated v9 ComboBox.
