### ISSUE TITLE
[Bug]: VerticalStackedBarChart Cannot read property 'xAxisPoint' of undefined

### ISSUE THREAD

**Issue by SudharsanSukumar** [microsoft/fluentui#23260]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 33.55 GB / 63.92 GB
  Browsers:
    Chrome: 101.0.4951.64
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.44)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://github.com/microsoft/fluentui/blob/dab45a2afe609709735b9b6e604a1af40d50e809/packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx#L353

## Actual Behavior
Error when passing empty data to VerticalStackedBarChart:
TypeError: Cannot read property 'xAxisPoint' of undefined
        at VerticalStackedBarChartBase.Object.<anonymous>.VerticalStackedBarChartBase._adjustProps

Bug is here: https://github.com/microsoft/fluentui/blob/dab45a2afe609709735b9b6e604a1af40d50e809/packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx#L361

Code is assuming there is at least one point to determine xAxisType (line 361)

## Expected Behavior
Render empty chart

### Requested priority

High

### Products/sites affected

Microsoft Project

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@SudharsanSukumar - Thank you for filing this item with us.
@Raghurk - Would you be able to look at this one? Thanks
