### ISSUE TITLE
[Bug]: Dropdown doesn't show options inside the @microsoft/sp-dialog BaseDialog the second time it opens

### ISSUE THREAD

**Issue by Dangerous-Mind** [microsoft/fluentui#23272]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 4.82 GB / 15.69 GB
  Browsers:
    Chrome: 101.0.4951.67
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

It's not possible to create a command set on pen test

## Actual Behavior
Created a commandset with a panel using the BaseDialog (@microsoft/sp-dialog). Implemented a Dropdown from Fluent Ui inside the panel.
When we activate the commnad set the panel and dropdown appear correctly with his options but if we close and open it again the dropdown options are not visible. It get's behind the BaseDialog because of the z-index.

We had the same issue if we used the old office-ui-fabric-react Panel with the fluent Ui Dropdown. 
We fixed using the new fluent ui Panel.
I think the BaseDialog (@microsoft/sp-dialog) also needs a upgrade to be compatible with the fluent Ui.

## Expected Behavior
The Dropdown options should not fall behind the BaseDialog the second time it opens.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@Dangerous-Mind - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the Dropdown examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by Dangerous-Mind** [comment]
I'm not sure how this can be done. 
Does code pen have Site Pages Library to attach a spfx extension with a Command Set?
Also I don't think we will get the css classes from the SharePoint site in there.

The steps to reproduce can be checked in [Microsoft docs Tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx) and adding a the Fluent-ui Dropdown inside the BaseDialog instead of the ColorPicker in the example.
It works fine with the office-ui-fabric-react.

**Comment by gastonframirez** [comment]
Hi all, 
I'm facing a similar issue with a Dialog and a Dropdown. Not sure up until what version, but the dropdown was being added at the end of the document, and therefore the z-index was not an issue. With #22295 the append now the dropdown gets appended in a different place and that makes the z-index conflict.

I think this comment might help:
https://github.com/microsoft/fluentui/issues/23575#issuecomment-1168034733
(the method has since been exported on this PR: #23753)

**Comment by Dangerous-Mind** [comment]
Still happening. 
Had to scrap three commandments last week because of several incompatibilities with spfx.
Like the element inside the dialog not appearing the second time it was open. 

I'll post the solution in here tomorrow if I have some time.

Basically you should just put this basedialog in the trash and inject the component into the dom were you can control it.
