### ISSUE TITLE
Consider renaming v9 Text to Typography

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#23294]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Text component enforces correct usage of font, font weight, line height and other font attributes to be consistent with Fluent design system.

At the same time, Provider is already setting a lot of these styles by default.
With this, the use case for Text is narrower and more specific, as it should be enough for the consumer to use plain html elements or just text to achieve the desired styling.

With this and based on the discussion in the v9 ship meeting I would like to start discussion about changing the v9 Text component name to be Typography instead.

According to [open-ui](https://open-ui.org/research/component-matrix) 4 design systems/component libraries use Text, 2 of them use Typography, but as a wider term.
So this change would **not** be aligned with open-ui collected data.

### Have you discussed this feature with our team

@levithomason

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by spmonahan** [comment]
Is one of the goals of this proposal to free up the `Text` name so we can implement #22855?
Or would we keep both names and deprecate `Text`?

**Comment by layershifter** [comment]
@jurokapsiar AFAIK we don't plan the rename, should be this closed?

**Comment by tudorpopams** [comment]
Yes, it has been agreed not to rename `Text` into `Typography`. Closing.
