### ISSUE TITLE
[Bug]: PR merge is blocked due to visual regressions in unrelated components.

### ISSUE THREAD

**Issue by AtishayMsft** [microsoft/fluentui#23291]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
NA
```

### Reproduction

https://screener.io/v2/dashboard/5e753c387bf3181b00090c18/usr%2Fatisjai%2F0525

## Actual Behavior
Due to issues in unrelated components, PR merge for charting library in v7 branch is blocked.
More details can be found in visual tests (https://screener.io/v2/dashboard/5e753c387bf3181b00090c18/usr%2Fatisjai%2F0525) run for PR (https://github.com/microsoft/fluentui/pull/23215) 

## Expected Behavior
The PR should merge without any issues since the visual regression is in unrelated components.

### Requested priority

High

### Products/sites affected

charting v7

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Looking at the three Screener diffs I see two changes:

1. `Coachmark` has an animation and it looks to me that Screener just caught a different frame of the animation. I think this is okay to accept.
2. In both `MediaTile` diffs the accepted image has a "broken image" icon while that image appears to have loaded in the most recent run. I think this is okay to accept.

**Comment by micahgodbolt** [comment]
screener approved, PR auto merged.
