### ISSUE TITLE
[Bug]: Arrowing breaks when I turn on NVDA in FocusZone

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#23290]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Microsoft Edge
Version 101.0.1210.53 (Official build) (64-bit)

NVDA 2022.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/mltejera/pen/OJQzWyL

## Actual Behavior
Navigate to provided code pen.
Use arrow keys to navigate between buttons.
Turn on NVDA.
Attempt to navigate buttons with arrow keys.
Note that arrow keys no longer navigate items.

## Expected Behavior
Arrow keys should navigate buttons when NVDA is turned on.

Windows narrator seems to work as expected.

https://codepen.io/mltejera/pen/OJQzWyL

### Requested priority

Normal

### Products/sites affected

MAC Admin Center in Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. I have added this to our accessibility queue for further investigations. To set expectations, the developers will review this issue once capacity allows.

cc @smhigley

**Comment by JosephThomas** [comment]
Hey @gouttierre , any updates on this issue?
