### ISSUE TITLE
[Bug]: DatePicker stopsPropagation on Escape keydown even if the calendar callout is not open

### ISSUE THREAD

**Issue by Tanner-MS** [microsoft/fluentui#23308]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz
    Memory: 22.26 GB / 63.73 GB
  Browsers:
    Chrome: 101.0.4951.67
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/Tanner-MS/pen/QWQaPeZ?editors=1111

## Actual Behavior
Escape keydown event's propagation is stopped even though the calendar callout is closed

## Expected Behavior
Escape should only have its propagation stopped if it closes the callout

### Requested priority

High

### Products/sites affected

Power Apps

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Issues addressed in  #23337
