### ISSUE TITLE
[Bug]: Fluent v9 SpinButton's increment/decrement buttons are of type "submit"

### ISSUE THREAD

**Issue by AndrewCraswell** [microsoft/fluentui#23316]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz
    Memory: 17.48 GB / 31.74 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/friendly-fermi-t5ebbc?file=/src/App.tsx

## Actual Behavior
When used in a form, clicking on either the increment or decrement button on the `SpinButton` component in Fluent v9 will cause the form submit handler to be executed because both buttons are of type submit. I don't see this being explicitly set with HTML attributes, so it must be set somewhere else. 

## Expected Behavior
Form submit handlers shouldn't get executed when the `SpinButton` value is stepped.

### Requested priority

Normal

### Products/sites affected

N/A

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by AndrewCraswell** [comment]
The workaround I'm using is to set an explicit Id on the proper Submit button. In the submit handler, I check if the element that triggered the submit has an Id that matches the correct submit button. This works but will have negative side effects of causing the form to not be able to be submitted with the keyboard enter button. That's enough for this not to be a blocker since the status of this component is obviously under development and thus unstable.

**Comment by gouttierre** [comment]
@AndrewCraswell - Thanks for filing this issue with us. Yes, that is correct the component is under development and thus unstable. To set expectations the developers will review the associated issues for `SpinButton` during the development phase to get the control to stable which won't be immediately as we’re currently focused on larger coherence work items.
