### ISSUE TITLE
[Bug]: "Remove" button doesn't work when using "selectedItems" for TagPicker component

### ISSUE THREAD

**Issue by kannan-balasubramanian** [microsoft/fluentui#23328]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Package version(s): @fluentui/react 8
Browser and OS versions: Edge - Windows 10
```

### Reproduction

https://codepen.io/kannan-balasubramanian/pen/RwQMQYL

### Bug Description

- I need to set the value of the picker's selected item on run time.
- For this, I'm trying to use the "selectedItems" and this results in "Remove" button not working.
- If I use the "defaultSelectedItems", the "Remove" button works, but the selected item reverts back to its original value.

## Actual Behavior
The "Remove" button is not working and is unable to clear the currently selected item.

## Expected Behavior
Should be able to click the "Remove" button, the item has to be cleared and I should be able to choose a new item.

Note: The minimal example provided for reproduction is a copy taken directly from https://developer.microsoft.com/en-us/fluentui#/controls/web/pickers.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
If you need to control the selected items during runtime, you are using the component in a controlled mode - it is your responsibility to maintain the list of selected items using the `selectedItems` prop. To remove the items, you should add `onChange` callback, which is called when the "x" button is clicked and it is passed the updated items - you should store them to your state and re-render the component with the new `selectedItems`.

**Comment by miroslavstastny** [comment]
Closing, if I misunderstood the issue, feel free to reopen.

**Comment by kannan-balasubramanian** [comment]
Thank you, I was able to implement the clear functionality using the "onChange" event.
