### ISSUE TITLE
[Bug]: Visual Studio Code Icon isn't available in the icon gallery

### ISSUE THREAD

**Issue by ashishchoudhary001** [microsoft/fluentui#23327]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
NA
```

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/styles/web/icons

## Actual Behavior
Visual Studio Code icon isn't available in the icon gallery: https://developer.microsoft.com/en-us/fluentui#/styles/web/icons

## Expected Behavior
VSCode icon should be available. For reference - Icon can to be added: https://code.visualstudio.com/brand

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@ashishchoudhary001 - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@khmakoto / @tomi-msft - Would either of you be able to confirm where and when our VSCode icons will be available?

**Comment by JustSlone** [comment]
@ashishchoudhary001 thanks for the input, we don't really ship brand icons, other than a pre-existing separate Office brand set. 

Going forward we are open sourcing all our icons and we aren't providing brand icons right now as part of that. This is good input if we do create a brand set, and this would be good feedback to file over at: https://github.com/microsoft/fluentui-system-icons as that is core of icon creation for Fluent Design.
