### ISSUE TITLE
[Bug]: Modeless Dialog is not showing a dialog

### ISSUE THREAD

**Issue by zeinsec** [microsoft/fluentui#23326]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Windows 11 
Browser: Edge 44.22621.1.0
```

### Reproduction

https://codepen.io/zeinsec/pen/OJQvxJg

## Actual Behavior
The model opens but you cant see it

## Expected Behavior
The model opens

Go to this page and scroll to the modeless dialog and hit open dialog. Nothing shows.
https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog

Also this page:
https://developer.microsoft.com/en-us/fluentui#/controls/web/modal

### Requested priority

Normal

### Products/sites affected

Broke our UI 

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@zeinsec - Thank you for filing this item with us. I can confirm the repro. I'll add this issue to our queue to get further input from the team. To set expectations, the developers will review this issue once capacity allows.

@khmakoto - i have added this to the HP board for now and we will need to address the example for modeless Dialog.

**Comment by micahgodbolt** [comment]
I believe this was fixed some time ago. I can't repro the issue with the current release.

**Comment by ZeinSleiman** [comment]
I haven't checked but if that's case we can close the issue.
