### ISSUE TITLE
[Bug]: AccordionHeader button submits the form on click when inside of a form element

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#23348]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Fluent UI v9 beta/rc
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/silly-matsumoto-ikf6f3?file=/example.tsx

## Actual Behavior
Clicking on accordion header button submits the form as button's implicit type is `submit` when in form

## Expected Behavior
Clicking on accordion header button should not submit the form

This can be achieved by adding `type="button"` to the AccordionHeader default button props.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by AndrewCraswell** [comment]
I noticed this as well, and was about to file the same. I also noticed that after opening an accordion item with a form in it, if I use the `Enter` keyboard key to submit the form, it instead collapses the accordion.
