### ISSUE TITLE
Align `react-components` Exports with Sub-package Exports

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#23345]
## Problem

Because `@fluentui/react-components` [does not always re-export all of the functionality of the sub-packages from which it is composed](https://github.com/microsoft/fluentui/pull/23306) it can lack feature parity with its sub-packages.

For example, `@fluentui/react-utilities` provides a `useMount()` hook that is not re-exported from `@fluentui/react-components` meaning a user directly depending on `react-utilities` has access to more features than one depending on `react-components`.

## Appetite

3~4 weeks. We should have a solution prior to [the release of v9 stable at the end of June](https://github.com/microsoft/fluentui/wiki/Fluent-UI-React-v9-Release).

## Solution

All features that are part of the public API of any of `@fluentui/react-components`' sub-packages should also be part of `@fluentui/react-components`' public API.

## Out of scope (No-gos)

1. No breaking changes

## Related

- #23343

**Comment by layershifter** [comment]
@spmonahan is it still a thing? Can you please close it if not?

**Comment by spmonahan** [comment]
I think the linked issue covers this and it has all the updates with the work being done so I'll close this one.
