### ISSUE TITLE
[Bug]: Incorrect recommendation about tabIndex in doc for the Spinner component

### ISSUE THREAD

**Issue by adamsamec** [microsoft/fluentui#23353]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-spinner--default

## Actual Behavior
* In the "Best practices" section of the documentation for the Fluent UI v9 Spinner component, there is a sentence "Add tabIndex={-1} to your Spinner to allow it to be picked up by screen readers.". However, the correct tabIndex value for an element to be included in a Tab sequence is a value equaled or greater than 0, whereas values greater than 0 are not recommended, so the sentence should recommend using tabIndex={0}.
* The other point is that we should recommend setting tabIndex={0} only when the Spinner is the only element on the page. Otherwise, a Spinner component should not be included in the Tab sequence.

## Expected Behavior
The correct sentence should read as follows: "If your Spinner is the only element on the page, set tabIndex={0} on it to allow it to be picked up by screen readers.".

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Fixed by #23385
