### ISSUE TITLE
[Bug]: Dialog is read again when focusing cancel button

### ISSUE THREAD

**Issue by petrjaros** [microsoft/fluentui#23364]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 36.19 GB / 47.73 GB
  Browsers:
    Edge: Spartan (44.22621.1.0), Chromium (98.0.1108.56)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

Cannot be provided. It happens in Teams desktop only.

## Actual Behavior
Jaws is wrongly narrating dialog. When cancel button is focused the narrator reads the content of the dialog again before it reads the cancel button label. 
I am only able to reproduce it in Jaws+ teams desktop client. Jaws+web is OK, NVDA is OK. (Here the narrator correctly reads just the cancel button)
The problem occurs in every dialog in our area.

## Expected Behavior
Jaws or any other narrator does not read whole content of the Dialog again. 
It reads the cancel button label only.

## Proposed fix
role="group" from the group of the buttons (cancel, confirm) fixes the problem for me. Is the role there necessary?

### Requested priority

Normal

### Products/sites affected

MS Teams (Breakout Rooms)

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@petrjaros - Thanks for filing this issue, great to see that you are willing to submit a PR for this request. Would you mind sharing it with us?

@jurokapsiar - Would you and your team be able to investigate this issue once capacity allows. Thanks
