### ISSUE TITLE
[Bug]: package.json 8.72.0 missing DirectionalHint and ThemeProvider exports

### ISSUE THREAD

**Issue by timothyhoffmann** [microsoft/fluentui#23377]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz   
    Memory: 9.52 GB / 31.88 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.30)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://aka.ms/fluentpen

## Actual Behavior
```
import { ThemeProvider } from "@fluentui/react/lib/utilities/ThemeProvider";
import { DirectionalHint } from "@fluentui/react/lib/common/DirectionalHint";
```

WebPack 5 claims these are not exported at build time

## Expected Behavior
Build should work.

## Correction seems to be in package.json by adding:
```
    "./lib/common/DirectionalHint": {
      "types": "./lib/common/DirectionalHint.d.ts",
      "import": "./lib/common/DirectionalHint.js",
      "require": "./lib-commonjs/common/DirectionalHint.js"
    },
    "./lib/utilities/ThemeProvider": {
      "types": "./lib/utilities/ThemeProvider/ThemeProvider.d.ts",
      "import": "./lib/utilities/ThemeProvider/ThemeProvider.js",
      "require": "./lib-commonjs/utilities/ThemeProvider/ThemeProvider.js"
    },
```

to this list of exports.

### Logs

```shell
ERROR in ./src/components/OrderBilling/OrderSummary.tsx 41:26-79
Module not found: Error: Package path ./lib/common/DirectionalHint is not exported from package C:\...\node_modules\@fluentui\react (see exports field in C:\...\node_modules\@fluentui\react\package.json)

ERROR in ./src/taskpane/index.tsx 45:24-78
Module not found: Error: Package path ./lib/utilities/ThemeProvider is not exported from package C:\...\node_modules\@fluentui\react (see exports field in C:\...\node_modules\@fluentui\react\package.json)
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@timothyhoffmann -  Thank you for filing this item with us. I'll add this to our contributors queue as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.

**Comment by trueleader** [comment]
Themeprovider actually (8.91.1) is reexported by Theme which is declared in package.json

`import { ThemeProvider } from "@fluentui/react/lib/Theme";`

**Comment by timothyhoffmann** [comment]
Thanks, yes, changing the import for ThemeProvider as above works at V8.92.0.  DirectionalHint still not working unless there's different import available for it somewhere.

**Comment by trueleader** [comment]
Callout and ContextualMenu components are reexporting DirectionalHint

**Comment by timothyhoffmann** [comment]
Thanks, that seems to be working, too.  I might send in a separate Documentation ticket to add these workarounds.
