### ISSUE TITLE
[Bug]: When navigable is set for List or ListItem, OnClick is not triggered for endMedia items (Button onClick) with press of "enter" button of keyboard

### ISSUE THREAD

**Issue by gautamjain14** [microsoft/fluentui#23389]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
    Memory: 1.43 GB / 15.84 GB
  Browsers:
    Chrome: 101.0.4951.67
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

yes
### Reproduction

https://qoh5fn.csb.app/

## Actual Behavior
1. Create a List with ListItems having endMedia.
2. Set **navigable true** for List/ListItems.
3. Make sure **endMedia has a fluent UI 'Button'** with **onClick** event.
4. When mouse is hovered over listitem, endMedia appears.
5. With Mouse left click on either of buttons, onClick event of button is triggered.
6. Now, Focus ListItem with **KeyBoard**. Using Keyboard keys (tab , arrows keys) navigate to endMedia buttons.
7. Press 'Enter' on a button. **Event will not be triggered**.

## Expected Behavior
Button event should be triggered even on press of enter key on endMedia Button control with Keyboard.

### Logs

```shell
1. Looks like focus is not set on buttons when navigated through keyboard.
2. document.activeElement returns <body> element when navigated to endMedia buttons using KeyBoard.
3. if navigable is true, issue persists, since endMedia controls appears on hover / focus
4. if navigable is false, it works fine, since endMedia controls are always visible
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@jurokapsiar - would you and your team be able to investigate this issue once capacity allows.
