### ISSUE TITLE
[Bug]: Color names are not provided by the ColorPicker control

### ISSUE THREAD

**Issue by Sachin01256** [microsoft/fluentui#23434]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Test Environment:
OS Version: 21H2 (OS build: 22000.493)
Browser: Microsoft Edge Version 98.0.1108.62 (Official build) (64-bit)
Screen Reader: Narrator, NVDA
```

### Reproduction

https://codepen.io/sachin01256/pen/RwQYVrd?editors=0010

## Actual Behavior
Currently, we are using the ColorPicker to select and fill the color in the SwatchColorPicker control. However, when we select any color from the color spectrum, color picker control only provided the hex code of the color, not the actual color name. 

Due to this limitation, we only provide the color hex code to the SwatchColorPicker control in the below format.
{id: 'color2', color: '#1D828C', label: '#1D828C'}

In this way, when the focus moved to SwatchColorPicker control, the screen reader read the hex code of the color. That may create problems for blind or visually impaired people to understand what exactly the color selected.

![image](https://user-images.githubusercontent.com/107034474/172359275-2639e8f9-fd08-4188-955a-af375076618c.png)

![image](https://user-images.githubusercontent.com/107034474/172344173-ffcf7d62-76bc-4fd7-8884-e26df64596ec.png)

## Expected Behavior
ColorPicker control should provide the color name along with hex code.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@Sachin01256 - Thank you for filing this item with us. I'll add this to our contributors queue as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
