### ISSUE TITLE
[Bug]: Northstar provider is polluting global css style by wildcard match *, *:before, *: after

### ISSUE THREAD

**Issue by PorterNan** [microsoft/fluentui#23444]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz
    Memory: 12.90 GB / 31.96 GB
  Browsers:
    Chrome: 102.0.5005.63
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.30)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/x0humk

### Bug Description

1.Create any code using fluent northstar with a provider, 2. check css style for any element, you will see 3 css styles *:{} *:before{} *:after{} are applied globally

To quickly repro, check this sandbox from fluent north star, you will see there are wildcard css styles applied to all element, even those elements outside of provider

![image](https://user-images.githubusercontent.com/11863655/172497499-33fa709a-dbed-41f1-b44c-22698eba0d59.png)
Even root div element is not wrapped by provider, wildcard css styles are still applied to it

We got multiple requests for fixing this, customers don't want their own global css to be overridden, check https://github.com/Azure/communication-ui-library/issues/1969

## Actual Behavior
Wildcard css style applied to all global dom element even it is not under provider

## Expected Behavior
The provider css style will only apply to all wrapped elements, but not polluting the global environment

### Requested priority

High

### Products/sites affected

@azure/communication-ui-library

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@jurokapsiar - would you and your team be able to investigate this issue once capacity allows. Thanks

**Comment by layershifter** [comment]
@PorterNan thanks for reporting, but it's done by design and we won't change it as it will be a huge breaking change 😿 

However, there is a way to avoid these styles being applied: you can customize `staticStyles` in a theme to change the behavior, for example:

```ts
const themeWithoutWildcards: ThemeInput = {
  ...teamsTheme,
  // remove global normalize.css and default styles provided by N*
  staticStyles: []
};
```

https://codesandbox.io/s/fluent-ui-example-forked-qpsis8

---

But, please note that N* components expect to have such styles and there might be unexpected issues caused by missing styles.
