### ISSUE TITLE
[Bug]: Details List crashes/blanks out after 100+ SharePoint Online List columns

### ISSUE THREAD

**Issue by PriyaranjanKS** [microsoft/fluentui#23506]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz
    Memory: 2.06 GB / 15.74 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

The details list is present in SharePoint. I tried to replicate the details list issue with 200+ dummy columns(not sharepoint) and it works without any issue. Pen to Dummy data Details List : https://codepen.io/kspriyaranjan/pen/LYQMppJ

## Actual Behavior
The details list crashes and blanks out when we add more than 100+ SharePoint Online list columns. The moment, we reduce the number of columns, the  details list is back to normal

## Expected Behavior
Details list should work without any issues even when we add more than 100+ SharePoint Online List columns

### Requested priority

Blocking

### Products/sites affected

SharePoint Online List

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@PriyaranjanKS - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by PriyaranjanKS** [comment]
@gouttierre 
this was an issue with the way SharePoint REST API was used. Closing this issue.
