### ISSUE TITLE
[Feature]: TimePicker and DatePicker with Time

### ISSUE THREAD

**Issue by icrocket** [microsoft/fluentui#23534]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Develop a TimePicker component with a better user experience.

The component has the possibility of inserting a time (with or without seconds) either through keyboard input or through a structured callout. (The component in the video was developed by me for internal use)

https://user-images.githubusercontent.com/47525865/173525028-81e19bb5-ee0a-4441-9b7a-7781febad6cf.mov

### Additional context

Insertion of this component inside the DatePicker component so as to allow the choice of date and time at the same time.

The TimePicker could be graphically inserted next to the Calendar of the DatePicker.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gouttierre** [comment]
@icrocket - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
