### ISSUE TITLE
[Bug]: Coachmark doesn't render teaching bubble in the correct place when not in the right

### ISSUE THREAD

**Issue by PatoBeltran** [microsoft/fluentui#23545]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 5.93 GB / 15.92 GB
  Browsers:
    Edge: Spartan (44.22621.160.0), Chromium (102.0.1245.41)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

Repro in docs https://developer.microsoft.com/en-us/fluentui#/controls/web/coachmark#ICoachmark

## Actual Behavior
When rendering the coachmark in the center of the target, once it is open to a teaching bubble, it renders all to the right (instead of centering with the target), once you click outside of it, it jumps to the center position.

https://user-images.githubusercontent.com/2132567/173635585-8a790e37-fe2f-4783-a45e-4afa9000d92f.mp4

This video was recorded from your docs site.

## Expected Behavior
The teaching bubble should be rendered at the center and if you click outside of it it shouldn't jump to a different place.

### Requested priority

Normal

### Products/sites affected

IoT Central

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by malladi-s** [comment]
With persistentBeak option turned on it this looks especially bad - https://codepen.io/malladi-s/pen/rNJEdQa

**Comment by gouttierre** [comment]
@PatoBeltran - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue? Thanks

**Comment by spmonahan** [comment]
This looks like an issue to me. It affects all of the "center" options -- top center, right center, bottom center and left center.

I think there are two parts to this issue:

1. `Coachmark` is not correctly aligned on the horizontal axis initially. As noted in the issue, it ultimately is aligned correctly when it jumps.
2. [All of the `Coachmark` animations slide out to in the up, right, dow and left directions](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx#L23-L28). For a centered `Coachmark` I'd expect it to expand outward so the mark is always centered.

**Comment by micahgodbolt** [comment]
The issue is that when the coachmark is being 'centered', it is currently 0px wide/tall, so the left edge is set to 0px off center. Then when i opens, it opens from where the left edge is placed.

If you remove the transition, so that the coachmark never has to transition to its final size, it works as expected. So the challenge will be applying this transition without breaking the centered positioning.
