### ISSUE TITLE
Autofill bug causing people picker error when user using Korean or Chinese input that click the suggestion before let the text resolve by system input.

### ISSUE THREAD

**Issue by xiangj1** [microsoft/fluentui#23553]
This line supposed to use || instead of &&, causing the update always been triggered.
https://github.com/microsoft/fluentui/blob/1936d2c730f319dfe75dd4033c69356bcc8f19d6/packages/react/src/components/Autofill/Autofill.tsx#L321

**Comment by gouttierre** [comment]
@xiangj1 -  Thank you for filing this item with us. I'll add this to our contributors queue as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
