### ISSUE TITLE
Using @withViewPort decorator from officeFabric utilities

### ISSUE THREAD

**Issue by asrivasms** [microsoft/fluentui#23559]
We have used @withViewPort decorator in few of our custom component from office-fabric(V7). We are trying to upgrade to FluentUI/react 8.67.4 but not able to import this package anymore and get build error. Can you please suggest what is the right way to import it from FluentUI
 
This is what we had in office-fabric

![image](https://user-images.githubusercontent.com/41121690/173895193-51228f67-a6f6-4f12-9444-affbf1962d60.png)

 
We changed the import as suggested by auto imports

import { IViewport, withViewport } from '@fluentui/react/lib/utilities/decorators/withViewport';
 
After using the new path we are getting this build error 
ERROR in ./src/V2/src/Shared/Components/AutoResizePanel/AutoResizePanel.tsx 15:0-85
Module not found: Error: Package path ./lib/utilities/decorators/withViewport is not exported from package D:\powerbi\Customer360\src\client\node_modules\@fluentui\react (see exports field in D:\powerbi\Customer360\src\client\node_modules\@fluentui\react\package.json)
 
Kindly suggest what is the right way to use this decorator.

**Comment by gouttierre** [comment]
@asrivasms - Thanks for filing this question with us. Did you follow your documentation around migrations?

•	[Migration from Fluent UI React (v7.x – v8.x)](https://github.com/microsoft/fluentui/wiki/Version-8-migration-guide)
•	[Moving to Fluent UI React v9.x](https://react.fluentui.dev/?path=/docs/concepts-upgrading-from-v8-overview--page)
