### ISSUE TITLE
[Bug]: Overflow does not work properly with tablist

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#23555]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 17.96 GB / 31.91 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.41)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/purple-cache-gmoxf2?file=/example.tsx

### Steps to reproduce
1) Open the sandbox with a wide screen, 5 tabs all show, select tab "Work Week"
2) Make screen size smaller (on the preview part), until you see "N More" shows
3) Sometimes, the N is incorrect (which is `overflowCount` from `useOverflowMenu`)
an example screenshot:
![image](https://user-images.githubusercontent.com/39588094/173725082-797afa96-d183-4720-b78d-7e89ef2af8f8.png)

4) If 3) is reproduced, make the screen wider, then "N More" button is gone but missing one menu
an example screenshot:
![image](https://user-images.githubusercontent.com/39588094/173725284-5a099efe-4dec-4ba8-9249-8af014fe1484.png)
 
5) If 3) and 4) are reproduced, randomly click on some tabs, and change screen size, sometimes will ran into the following issue:
an example screenshot:
![image](https://user-images.githubusercontent.com/39588094/173725417-379f00a1-e9db-4c39-b1c5-1490f7728ae0.png)

The above issue does not happen every time, I think if I change the screen size a little faster it might have higher chance to happen.

And it's not just happening on the sandbox, it happened on my project as well, and it cannot get the original menus back when I increase the screen size when working on my own project.

## Expected Behavior
Expectation is the above issues should not happen.

I ticked `willing to submit a PR to fix` but I don't quite know what the fix is yet. Would love to investigate if I have time and have more guidance. Thank you!

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@flora8984461- Thank you for filing this issue with. To set expectations, we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. However, I see you are willing contribute to this issue, that is great news! 
If you have a solution at hand and would like to contribute towards it, please, share your PR for us and the team will review it.

**Comment by flora8984461** [comment]
I notice there will be some changes: https://github.com/microsoft/fluentui/pull/25091 
https://github.com/microsoft/fluentui/pull/25122

Will see if those merges can fix this issue or not.

**Comment by ling1726** [comment]
@flora8984461  those changes are released, can you still repro this?

**Comment by flora8984461** [comment]
It seems fixed with latest version. Thank you! 

https://codesandbox.io/s/nifty-rain-zoxhpe?file=/example.tsx
