### ISSUE TITLE
[Bug]:  CommandBarButton's menuIconExpanded style is overridden when hovering on the context menu

### ISSUE THREAD

**Issue by TellonUK** [microsoft/fluentui#23579]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 20.84 GB / 31.60 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (102.0.1245.41)
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/tellonuk/pen/rNJRzOJ

## Actual Behavior
When you provide a color to  menuIconExpanded & menuIconExpandedHovered the chevron will ignore this color when you hover on the context menu. As you hover on the context menu (such as Email message) the chevron will default to black even when menuIconExpanded has been set.

## Expected Behavior
That the chevron would use either menuIconExpanded's ( or menuIconExpandedHovered's if the intention is that hovering on the context counts as hovering on the button) style

### Logs

```shell
Example:
https://codepen.io/tellonuk/pen/rNJRzOJ

Overides:

const chevronStyles = {
    root: {
      color: 'red',
    },
    menuIcon: {
      color: 'red',
    },
    menuIconHovered: {
      color: 'red',
    },
    menuIconPressed: {
      color: 'red',
    },
    menuIconExpanded: {
      color: 'red',
    },
    menuIconExpandedHovered: {
      color: 'red',
    },
    menuIconChecked: {
      color: 'red',
    },
  }
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@TellonUK - Thank you for filing this item with us. I'll add this to our contributors queue as it’s low on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
