### ISSUE TITLE
[Bug]: SpinButton stories cleanup

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#23594]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/preview-components-spinbutton--controlled

### Bug Description

1. SpinButton does not have description like other components
  ![image](https://user-images.githubusercontent.com/14183168/174277090-a6359134-5a22-4e19-8f3e-637ecc276b2c.png)

1. Best practices are not collapsible like in other components
  ![image](https://user-images.githubusercontent.com/14183168/174277220-50b18f05-7662-4b5e-891c-c696c38b135e.png)
  ![image](https://user-images.githubusercontent.com/14183168/174277282-d88d9f00-94b7-49b2-857a-21fb519ff497.png)

1. There is no "SpinButtonDefaut.stories.tsx" like in other components, docs are starting from a complex "Controlled" example

1. "SpinButtonControlled.stories.tsx" contains `console.log` 
  https://github.com/microsoft/fluentui/blob/513752349c8f3eb374cdc0b1bff43e2ca8dda72a/packages/react-components/react-spinbutton/src/stories/SpinButtonControlled.stories.tsx#L28

1. "SpinButtonControlled.stories.tsx" should control both `value` & `displayValue` (?). I don't feel that it's intuitive to show only single value. It would be also nice to show values of `value` & `displayValue` like it https://react.semantic-ui.com/modules/rating/#types-on-rate.

1. We don't have stories for RTL (expect `FluentProvider` as it's a prop there) so `SpinButtonRTL.stories.tsx` probably should be removed for consistency.

1. `SpinButtonStep.stories.tsx` should be minimal and showcase `step` prop i.e. `onSpinButtonChange` should be removed.

1. `SpinButtonBounds.stories.tsx` should be minimal and showcase `min` & `max` props i.e. `onSpinButtonChange` should be removed.

### Logs

```shell
N/A
```

### Requested priority

Normal

### Products/sites affected

N/A

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
> "SpinButtonControlled.stories.tsx" should control both value & displayValue (?). I don't feel that it's intuitive to show only single value.

I don't think we should show `displayValue` in the Controlled story since you do not have to use `displayValue` with a controlled SpinButton. The `DisplayValue` story demonstrates using the `displayValue` prop.

Maybe the controlled story description should mention displayValue and point readers to the other story?

I'm going to leave to as-is since I'm considering your other feedback about an alternate approach to formatting that would eliminate the `displayValue` prop.

> It would be also nice to show values of value & displayValue like it https://react.semantic-ui.com/modules/rating/#types-on-rate.

I'm not sure I understand what you want the story to show. Could you clarify this point please?

**Comment by layershifter** [comment]
> I'm not sure I understand what you want the story to show. Could you clarify this point please?

If you don't plan to show `displayValue` in examples - it's less relevant, I was thinking about something like that, https://codesandbox.io/s/happy-https-1crphv?file=/example.tsx.

**Comment by spmonahan** [comment]
> If you don't plan to show `displayValue` in examples - it's less relevant, I was thinking about something like that, https://codesandbox.io/s/happy-https-1crphv?file=/example.tsx.

Got it! I'll keep it in mind since I'm thinking through your other suggestions and these stories may be updated further.
