### ISSUE TITLE
[Bug]: Not able to navigate through Legends in Browse mode.

### ISSUE THREAD

**Issue by RajeshGoriga** [microsoft/fluentui#23596]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 6.61 GB / 15.90 GB
  Browsers:
    Chrome: 102.0.5005.115
    Edge: Spartan (44.22000.120.0), Chromium (102.0.1245.44), ChromiumDev (104.0.1278.2)
    Internet Explorer: 11.0.22000.120
```

### Reproduction

https://fluentuipr.z22.web.core.windows.net/heads/master/react-charting/demo/index.html#/examples/linechart

## Actual Behavior
Not able to navigate through Legends in Browse mode.

## Expected Behavior
It should navigate through Legends in browse mode 

![image](https://user-images.githubusercontent.com/13463251/174307116-e672edaa-043c-41b7-819d-73c871ae4276.png)

Bug Reference : https://office.visualstudio.com/OC/_workitems/edit/5945616

### Requested priority

Normal

### Products/sites affected

M365 admin center

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by AtishayMsft** [comment]
This issue has been fixed in PR #23885
