### ISSUE TITLE
[Bug]: Coachmark forces focus on itself 1 second after it was open

### ISSUE THREAD

**Issue by PatoBeltran** [microsoft/fluentui#23604]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 5.93 GB / 15.92 GB
  Browsers:
    Edge: Spartan (44.22621.160.0), Chromium (102.0.1245.41)
    Internet Explorer: 11.0.22621.1
```

### Reproduction

https://codepen.io/PatoBeltran/pen/poaBjwv

## Actual Behavior
The coachmark component seems to be taking focus after 1 second of being open. This assumes that the user will not interact with anything in the page for at least one second after it was open, because otherwise it just takes the focus without any option to disable that behavior.

In the repro codepen provided, try to open the coachmark and then immediately open the dropdown, after some time you will see the dropdown closed automatically, this is because the coachmark stole the focus from it, making it close.

This is specially annoying if the coachmark is set on a form field (like a dropdown) and after opening the user tries to use the form field but randomly the focus goes back to the coachmark.

The code that does it is found here:
https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Coachmark/Coachmark.base.tsx#L73

## Expected Behavior
The coachmark should not wait 1 sec to gain focus (if the wait is essential, could it be a considerable amount of time were the user will be idle?), or at least there should be a prop to manage the time in the timeout, or disable the coachmark getting focus at all.

### Requested priority

Normal

### Products/sites affected

IoT Central

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@PatoBeltran - thank you for filing this issue with. To set expectations, we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. However, I see you are willing contribute to this issue, that is great news! 
If you have a solution at hand and would like to contribute towards it, please, share your PR for us and the team will review it.
