### ISSUE TITLE
[Bug] Detailslist Getkey function not working

### ISSUE THREAD

**Issue by okonech** [microsoft/fluentui#23614]
### Environment Information

FluentUI React 8.77.0

### Describe the issue:

Sorting a detailslist containing items without a "key" property but with a passed getKey() function does not work the same as a detailslist containing items with a "key" property.

If a user selects multiple items for deletion for example, then sorts the list, different items are now selected and may incorrectly be deleted if the user proceeds.

#### Actual behavior:

With selections enabled (preferably multiple) select a few entries (first and third items) then sort by a column. Notice the selections are preserved by position (first and third items), even though the actual selected entries are now at different indexes.

![Getkey bug](https://user-images.githubusercontent.com/36140593/174657994-3b22354f-5839-439f-bf96-ff93968e1f6b.gif)

#### Expected behavior:

As with a detailslist containing "key" properties, the selections should follow the items as they are sorted.

![Item key expected functionality](https://user-images.githubusercontent.com/36140593/174658023-9590ed5b-2500-40a6-af59-d88867c5868c.gif)

### If applicable, please provide a codepen repro:

https://codepen.io/okonech/pen/XWZwNOL

This is a stripped down and slightly modified version of the detailslist example from https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Yes

Requested priority: (Blocking, High, Normal, Low)

Normal

Products/sites affected: (if applicable)

Azure portal. Workaround is to manually add a "key" property to items used in the list.

**Comment by gouttierre** [comment]
@okonech - thank you for filing this issue with. To set expectations, we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. However, I see you are willing contribute to this issue, that is great news! 
If you have a solution at hand and would like to contribute towards it, please, share your PR for us and the team will review it.
