### ISSUE TITLE
[Feature]: Add Body 2 type token

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#23617]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Adding body 2 type token to support large size input, text area, and dropdown
Original Request: https://www.figma.com/file/KB9oUjMKen2cKnyPG7RgdS/Design-Tokens-Superset?node-id=23819%3A59861

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JustSlone** [comment]
Tagging @smhigley for dropdown, and @behowell for inputs
