### ISSUE TITLE
[Bug]: Slider does not receive programmatic .focus()

### ISSUE THREAD

**Issue by danmarshall** [microsoft/fluentui#23627]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Codepen
```

### Reproduction

https://codepen.io/danmar/pen/gOvJXxe

## Actual Behavior
Slider does not receive focus when its focus() method is called. Does not respond to keyboard events or show a focus ring.
![sliderfocus](https://user-images.githubusercontent.com/11507384/174867318-a8dbc06b-de68-4e7e-a3ae-4c9a0e0f2291.gif)

## Expected Behavior
After calling .focus() programmatically, expected to show a focus ring and receive keyboard input.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by dzearing** [comment]
The Slider's focus method is trying to focus the thumb span, yet the root element is the thing which should receive focus.

Would be good to add a unit test for this issue, make sure it fails, and then fix it by correcting the ref.

**Comment by danmarshall** [comment]
FYI this happens in React / v7 also

**Comment by gouttierre** [comment]
> Would be good to add a unit test for this issue, make sure it fails, and then fix it by correcting the ref.

@danmarshall - Thanks for filing this issue. Would you be able to add the unit tests for the devs?

**Comment by SchroeerM** [comment]
Same problem here. When will we get a fix for this?
