### ISSUE TITLE
[Bug]: Missing scheduler dependency in react-component packages

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#23639]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Reproduction

N/A

### Bug Description

#21769 moved `scheduler` from `dependencies` to `peerDependencies` in `@fluentui/react-context-selector`. It, however, didn't add it as part of the `dependencies` or `peerDependencies` of packages using `@fluentui/react-context-selector`, which means that, in certain cases, when importing components from these packages, builds error out saying that there is a missing dependency on `scheduler`.

To fix this we should add scheduler as part of the `dependencies` or `peerDependencies` of the following packages which use `@fluentui/react-context-selector`:
- [ ] `@fluentui/global-context`
- [ ] `@fluentui/react-accordion`
- [ ] `@fluentui/react-avatar`
- [ ] `@fluentui/react-combobox`
- [ ] `@fluentui/react-menu`
- [ ] `@fluentui/react-overflow`
- [ ] `@fluentui/react-popover`
- [ ] `@fluentui/react-radio`
- [ ] `@fluentui/react-tabs`

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Can you please provide a repro case for that? I don't know any package manager (I tested NPM v6 & v7 & Yarn) that does not complain about missing `peerDependencies`.

For example:

```shell
$ npm i @fluentui/react-avatar --save

npm WARN @fluentui/react-context-selector@9.0.0-rc.10 requires a peer of react-dom@>=16.8.0 <18.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fluentui/react-context-selector@9.0.0-rc.10 requires a peer of scheduler@^0.19.0 || ^0.20.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by layershifter** [comment]
I created an issue in `midgard-yarn-strict` repository, https://github.com/VincentBailly/midgard-yarn-strict/issues/9
