### ISSUE TITLE
[Bug]: Combobox children hover effect only on first child

### ISSUE THREAD

**Issue by Saintenr** [microsoft/fluentui#23645]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 1.02 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Brave Browser: 96.1.32.113
    Safari: 15.5
```

### Reproduction

https://codepen.io/Saintenr/pen/ExQBZeP

## Actual Behavior
background hover style on combobox items is only working on the first item

![hover 2](https://user-images.githubusercontent.com/33520976/175026405-b7e94ad1-56bc-42a8-93cc-f348082e419f.png)

![hover 1](https://user-images.githubusercontent.com/33520976/175026409-1c67e279-8f3f-4ce3-9b67-dd545edb369a.png)

## Expected Behavior
hover effect is working on every item

### Requested priority

Normal

### Are you willing to submit a PR to fix?

this is only the case if the parameter multiSelect is set to true

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

## Edit

**Comment by gouttierre** [comment]
@Saintenr - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@TristanWatanabe - Would you be able to confirm if this is a regression, or if this behavior is an issue? Thank you

**Comment by TristanWatanabe** [comment]
Behavior seems to be an issue. I'm able to repro it on any browser on a windows machine and the root seems to be that a `:hover` style is added to the first `Combobox` option only when it's multi-select AND there's no `header` option. When a `header` is present as an option, the expected behavior of no `:hover` style on each option can be observed.
