### ISSUE TITLE
[CI Bug]: Screener results not reported back to PRs to a branch

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#23641]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
CI
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://github.com/microsoft/fluentui/pull/23610

### Bug Description

1. Have a custom branch with CI enabled (`9.0-rc`)
2. Create a PR to that branch
3. Check CI

## Actual Behavior
- Screener is run for all v8, v9 and v0
- Screener results are reported back only for v8, there are no results for v9 or v0 visible in the PR

## Expected Behavior
- Screener is run only for the affected library
- Screener results are reported back to the PR

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
We don't use Screener anymore, closing.
