### ISSUE TITLE
v9: children iteration 

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#23666]
## Details
This issue was brough up due to a recent [comment](https://github.com/microsoft/fluentui/pull/22736/files#r902344022) on the implementation of AvatarGroup. Currently the component slices the children expecting them to be of type AvatarGroupItem. This brings up issues with the composition pattern by not handling a case like this:
```
<AvatarGroup>
  <>
    <AvatarGroupItem />
    <AvatarGroupItem />
    <AvatarGroupItem />
    <AvatarGroupItem />
    <AvatarGroupItem />
  </>
</AvatarGroup>
```
A quick fix is to check for a fragment in children and get the AvatarGroupItems from it. As we continue to build more complex components this will become a bigger issue and we should have a set pattern on how to handle it.

The same issue came up in Combobox, which currently relies on dom odering to avoid this problem.

**Comment by layershifter** [comment]
> A quick fix is to check for a fragment in children and get the AvatarGroupItems from it.

There is another case with composition that cannot be fixed:

```tsx
function AlwaysPresentAvatars() {
  return (
    <>
      <AvatarGroupItem />
      <AvatarGroupItem />
    </>
  );
}

function App() {
  return (
    <AvatarGroup>
      <AlwaysPresentAvatars />
    </AvatarGroup>
  );
}
```
