### ISSUE TITLE
[Important] Skeleton animation=wave regression

### ISSUE THREAD

**Issue by cstechfoodie** [microsoft/fluentui#23680]
### Environment Information

- **Package version(s)**: Latest 0.63.0

### Describe the issue:

Animation wave doesnt animate anymore 

#### Actual behavior:
https://fluentsite.z22.web.core.windows.net/0.63.0/components/skeleton/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#variations-animations

#### Expected behavior:
https://fluentsite.z22.web.core.windows.net/0.55.0/components/skeleton/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#variations-animations

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low)
High
Products/sites affected: (if applicable)
Microsoft products

**Comment by gouttierre** [comment]
@cstechfoodie - Thank you for filing this item with us. To set expectations the developers will review this issue once capacity allows.

@jurokapsiar - would you and your team be able to review this request. Thanks
