### ISSUE TITLE
Enforce peerDependencies are met in @fluentui packages

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#23699]
We recently discovered in #23639 that `scheduler` was moved from a `dependency` to a `peerDependency` in `@fluentui/react-context-selector`. However, other `@fluentui` packages using `@fluentui/react-context-selector` were not updated to account for that `peerDependency` by adding `scheduler` as a `dependency` or `peerDependency` of their own, which can cause problems in more strict build environments.

Given all this, we should have a way to enforce this type of dependencies are met going forward so we don't encounter similar scenarios.

**Comment by layershifter** [comment]
@khmakoto FYI: I am going to close it as the requirement is no longer valid, for context https://github.com/microsoft/fluentui/issues/23110#issuecomment-1208062416.
