### ISSUE TITLE
[Bug]: Failed to change Checkbox state from Dropdown change

### ISSUE THREAD

**Issue by yungfu** [microsoft/fluentui#23715]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 2.99 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 15.5
```

### Reproduction

https://codepen.io/yungfu/pen/gOvVYQr

## Actual Behavior
Declare a `{checked, setChecked}=useState<boolean>(undefined);` state. 
Set controlled Checkbox component `checked={checked}`.  Call `setChecked` when another Dropdown component selection changed, `checked` state changed, but Checkbox UI didn't update, its label property update successfully.

Call `setChecked` in Checkbox `onChange`, the Checkbox UI update successfully.

If I change `checked` state default value to `true` or `false`, not `undefined`, Checkbox will be update when Dropdown changed.
>`{checked, setChecked}=useState(false);`
>The problem go away when initial state is boolean.

This issue also exist on **Toggle** component.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@yungfu - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@TristanWatanabe - Would you be able to confirm if this is a regression, or if this behavior is an issue? Thanks!

**Comment by TristanWatanabe** [comment]
Looks like an issue to me - root cause seems to be when the initial value of the `checked` state is `undefined` the `Checkbox` fails to update correctly when the chosen `Dropdown` item is changed.
