### ISSUE TITLE
[Bug]: Focus does not come to iFrame inside modal 

### ISSUE THREAD

**Issue by soshanmums** [microsoft/fluentui#23738]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 32.83 GB / 63.59 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.41)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/soshanmu/pen/RwQXZJY

### Bug Description

Focus does not go to Interactive elements below the iFrame when rendered inside a modal. In the codepen, we can see that the focus gets stuck between the content of the iFrame and the close button. it does not reach the element below the iFrame.

While doing shift+tab, the focus is stuck inside the dialog content, but does not go to the close button,

## Actual Behavior
Focus gets stuck above the elements of iFrame and does not reach to elements below iFrame

## Expected Behavior
Focus should come to all interactable elements of the modal

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@soshanmums -  Thank you for filing this item with us. I'll add this to our contributors queue as it’s lower on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.

**Comment by soshanmums** [comment]
It is working fine after the latest fluent update. Thanks for taking the time to look into the issue, it was reproducible few months bakc
