### ISSUE TITLE
[Bug]: List scrolling does not render the full bottom row

### ISSUE THREAD

**Issue by anros-p** [microsoft/fluentui#23765]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Any environment, the bug can be seen on the documentation site.
```

### Reproduction

https://codepen.io/pen?&prefill_data_id=0d319e27-01bf-471c-8e60-44d48299ea66

## Actual Behavior
Using the scrollToIndex method in bottom or auto mode (if the previous scrolling index was lower), the target item is not fully rendered.

## Expected Behavior
The target item should fully render into the list

This behavior can be observed using the public documentation of the basic list control : https://developer.microsoft.com/en-us/fluentui#/controls/web/list

![image](https://user-images.githubusercontent.com/37807776/176389314-684853da-f5e5-4b7b-b038-b2ba76938876.png)

### Requested priority

High

### Products/sites affected

Power Query Online

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@anros-p - thank you for reaching out to us. I see your code pen is empty. Could you post an updated code-pen on the issue for the dev team to investigate further? Thank you.

cc @layershifter
