### ISSUE TITLE
[Bug]: Tab focus is set at the component but the button is not focusable 

### ISSUE THREAD

**Issue by ashitaagrwl** [microsoft/fluentui#23815]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 4.04 GB / 15.73 GB
  Browsers:
    Chrome: 103.0.5060.66
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.44)      
    Internet Explorer: 11.0.22000.120
```

### Reproduction

https://codepen.io/asagrawal/pen/OJvMmwz

## Actual Behavior
On applying autoFocus as true to primaryButton component, tab focus is set at the component but the button is not focused visibily.

## Expected Behavior
The button should have been focused on initial render.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hi @ashitaagrwl, thanks for filing your first issue! Please update the title for better visibility.

**Comment by gouttierre** [comment]
@ashitaagrwl - Thanks for filing this, but I was unable to reproduce the stated issue. Please, can you retest using the latest version of the lib and let us know if the issue still persists.
