### ISSUE TITLE
[Bug]: [Charting] [Stacked bar chart] Unnecessary tab focus is moving to non interactive control(text), when navigating using tab key

### ISSUE THREAD

**Issue by RajeshGoriga** [microsoft/fluentui#23814]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.64 GB / 15.90 GB
  Browsers:
    Chrome: 102.0.5005.115
    Edge: Spartan (44.22000.120.0), Chromium (102.0.1245.44), ChromiumDev (105.0.1300.0)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://admincontrolsdemoapps.blob.core.windows.net/release/charting-demo/5.0.9/index.html#/examples/StackedBarCharts

## Actual Behavior
Unnecessary tab focus is moving to non interactive control(text), when navigating using tab key
![image](https://user-images.githubusercontent.com/13463251/177526640-ec8c2166-9899-43e1-8224-ea2f50464198.png)

## Expected Behavior
tab focus is not  going to the non interactive controls (text) 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@RajeshGoriga - Thanks for filing this issue with us.  To set expectations the developers will review this issue once capacity allows.

@Raghurk - Would you be able to review this issue? Thanks

**Comment by AtishayMsft** [comment]
We have confirmed with accessibility folks that this issue is not necessary to fix. Closing this as won't fix.
