### ISSUE TITLE
Combobox: onPendingValueChanged can fire with old pendingValue 

### ISSUE THREAD

**Issue by jspurlin** [microsoft/fluentui#23820]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows Server 2016 10.0.14393
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 42.42 GB / 63.90 GB
  Browsers:
    Chrome: 103.0.5060.66
    Internet Explorer: 11.0.14393.2007
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/jspurlin/pen/QWmymow

## Actual Behavior
Using the arrow keys to update the pending value sends in the old pendingValue text

## Expected Behavior
From looking at the code, it should probably not send pendingValue text if a matching option was found

### Requested priority

Normal

### Products/sites affected

Office Online

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Fixed by https://github.com/microsoft/fluentui/pull/23824
