### ISSUE TITLE
[Bug]: DetailsList with single select mode cannot unselect a row with keyboard

### ISSUE THREAD

**Issue by almaasrawi** [microsoft/fluentui#23843]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
npx: installed 1 in 1.706s

  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz
    Memory: 35.87 GB / 63.59 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (102.0.1245.41)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

yes

### Reproduction

DetailsList with single select mode cannot unselect a row with keyboard

## Repro Steps
* Create a DetailsList with single select mode. Example: https://codepen.io/masrawi/pen/vYRGRLm
* Use the keyboard to select a row from the details list.
* Now try to use the keyboard to unselect the row (without selecting another one), either by `space` or `ctrl + space`.

## Actual Behavior
* The row cannot be unselected.

## Expected Behavior
* The row should be unselected, to match the mouse experience which can successfully unselect a row.

### Logs

```shell
N/A
```

### Requested priority

High

### Products/sites affected

make.powerautomate.com, powerapps.com, admin.powerplatform.microsoft.com

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
I don't think this is a bug as `escape` will deselect the selected item in the example. There are two things we should do here though:

1. Improve the keyboard documentation for DetailsList: #23844
2. Consider expanding [keyboard overrides](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/keyboardoverrides) to support single select mode.
