### ISSUE TITLE
Save the DetailList column width to db

### ISSUE THREAD

**Issue by it950** [microsoft/fluentui#23856]
### Discussed in https://github.com/microsoft/fluentui/discussions/23850

<div type='discussions-op-text'>

<sup>Originally posted by **it950** July  9, 2022</sup>
Can we save the changed column width of a DetailList to db?
eg:
Adjust a column width, and save the changes to db, then reload the page,  the column will be displayed with the saved width.
</div>

**Comment by spmonahan** [comment]
I've replied with some guidance in the discussion thread but saving data to a database and restoring component state based on that is outside the scope of Fluent so I'm closing this issue.
