### ISSUE TITLE
[Bug]:When the user tabs to the combo box, Narrator should announce the current state of the button(s) that represent that labels that were previously added.  

### ISSUE THREAD

**Issue by variveros** [microsoft/fluentui#23864]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "7.185.7"
- **Browser and OS versions**:  OS: Windows 10 10.0.22000,  Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.55)

### Describe the issue:

When the user tabs to the combo box, Narrator should announce the current state of the button(s) that represent that labels that were previously added.  The ‘Remove’ word should be eliminated as the state of the button should be enough.

#### Actual behavior:

Tested in edge and chrome, but it only occurs in edge. With narrator on, after selecting an item from the picker, narrator reads the item's label followed by 'remove'. Focus is on the input field, not the remove button, but narrator still reads out 'remove'

#### Expected behavior:

Focusing on the input field of the picker with selected items should announce the state of the selected items only.

### If applicable, please provide a codepen repro:

With narrator on, use any picker, select 'yellow' from the suggestions popup. Narrator will read 'combo edit, collapsed, yellow remove, has popup'
https://developer.microsoft.com/en-us/fluentui#/controls/web/pickers

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
Thank you for filing this item with us. I'll add this to our contributors queue as it’s lower on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
