### ISSUE TITLE
[Feature]: Pass readonly prop to HTML input and textarea element in Input and Textarea components

### ISSUE THREAD

**Issue by adamsamec** [microsoft/fluentui#23875]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Similarly as the "type", "name" or "disabled" props on the root Input component are passed as attributes to the inner input HTML element, also the "readonly" prop should be passed there as well. The same should be implemented for the Textarea component and its "readonly" prop.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jurokapsiar** [comment]
In React, the prop is `readOnly` which works correctly: https://codesandbox.io/s/beautiful-haze-gjt1tj?file=/example.tsx
