### ISSUE TITLE
[Bug]: <Tooltip> max width is fixed

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#23889]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.25151
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 6.08 GB / 31.73 GB
  Browsers:
    Edge: Spartan (44.25151.1010.0), Chromium (103.0.1264.49), ChromiumDev (105.0.1300.0)
    Internet Explorer: 11.0.25151.1000
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/exciting-snyder-5f28gn?file=/example.tsx

## Actual Behavior
The tooltip has a `max-width: 240px` style.
![image](https://user-images.githubusercontent.com/50703224/178726989-e7864d5a-2996-41df-b168-fb8305eb62dc.png)

## Expected Behavior
The tooltip max-width is customizable, as in #2625.
![image](https://user-images.githubusercontent.com/50703224/178727179-5020421c-2c72-4cae-951b-153682089afa.png)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @chenxinyanc, it is possible to override the `maxWidth` style by setting a `className` (or inline `style`) on Tooltip's `content` slot. Something like this:

```jsx
const useStyles = makeStyles({
  myTooltipMaxWidthClass: {
    maxWidth: '480px',
  },
});

export const Default = () => {
  const styles = useStyles();
  return (
    <Tooltip
      content={{
        className: styles.myTooltipMaxWidthClass,
        children: (
          <div>
            <p>Current ID 1: 31e48c18-5b1f-4a4e-9dec-5b71cbc84d0a</p>
            <p>Current ID 2: 562028e6-3e63-42ad-8616-9860bbfd6e47</p>
          </div>
        ),
      }}
      relationship="label"
    >
      <Button icon={<SlideTextRegular />} size="large" />
    </Tooltip>
  );
};
```

It would also work to use`style: { maxWidth: '480px' }` instead of a className, but that is generally worse for performance if you have many instances of this tooltip.
