### ISSUE TITLE
react-positioning: figure out a way to handle `focus` forced scrolling for lazy content

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#23928]
Lazy loaded content can overflow the boundary of the popper. However calling `focus` before the popper has been repositioned can force a scroll even for viewports where scrolling is disabled.

In these cases, there's no API that we provide that can help users with solve this. We should either try to provide a library API that can be used for this scenario or document what needs to be done to avoid this.

Repro: https://codesandbox.io/s/wizardly-bush-n3rt71?file=/example.tsx

**Comment by miroslavstastny** [comment]
Reported by partner. This might be an arch decision or at least we should document why it does not work.
