### ISSUE TITLE
beachball tries to release based on a peer dependency bump

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#23929]
Releases have failed because `react-conformance-griffel` has a dependency on `react-conformance` which is bumped and released as a part of v8.

Because of release scoping `react-conformance-grifffel` is never bumped and the release fails because it tries to release a version that already exists on npm.

PRs that have fixed this issue previously

- #23909
- #23146

**Comment by Hotell** [comment]
discussed offline - we haven't run into this for some time so closing
