### ISSUE TITLE
[Bug]: TabsList jumps pixels when you change tabs.... :(

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#23947]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
chrome, windows
```

### Reproduction

https://stackblitz.com/edit/react-ts-rtwqb7

![tabs](https://user-images.githubusercontent.com/1434956/198094421-532c4083-b18f-4bda-a845-2b2fb4a8ca2b.gif)

## Actual Behavior
Change tabs, bold text changes cause pixel jumps around in the tab

## Expected Behavior
Change tabs, bold tabs doesn't add pixel width to a tab

This used to be a major eye sore in the Fabric Pivot and was later fixed (by always rendered "selected" text and hiding it so that bold widths would take layout space.)

Now it jumps around when you click around. Feels very unpolished.

Also of minor note is that the grey "hover underline" shows momentarily when you select a tab, while the brand colored underline gracefully glides on top of it. Recommend not showing the hover underline when something becomes selected... would make it much more polished.

### Logs

```shell
n/a
```

### Requested priority

Normal

### Products/sites affected

any using tabs

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by GeoffCoxMSFT** [comment]
@dzearing - Both of these are by design according to the figma.  I brought up these visual issues with Yvonne during TabList development. She considered them and decided to stick with the current design as it matches closely to Windows.

**Comment by dzearing** [comment]
No, this is not by design. There is a css trick we're missing.
