### ISSUE TITLE
[Bug]: AvatarGroup (Preview)  Control is Missing Usage Warning and has Incomplete Best Practices. 

### ISSUE THREAD

**Issue by gouttierre** [microsoft/fluentui#23954]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Reproduction

https://react.fluentui.dev/

## Actual Behavior
-The control has no usage warning. 
-Incomplete best practices
-The controls best practices are not in an expandable element. 
 
## Expected Behavior
-Add a warning on the usage like Alert (Preview).
-Complete the best Practices
-Move the Best Practices into an expandable element.

### Requested priority

High

### Products/sites affected

Fluent React v9 Microsite 

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by tudorpopams** [comment]
@microsoft/cxe-red hey folks, do we have any best practices to add to `AvatarGroup` or should we remove the section?

**Comment by behowell** [comment]
AvatarGroup is still in unstable/preview, and I think the documentation isn't done yet. @sopranopillow can you confirm that you're planning to add best practices to `AvatarGroup` docs?

**Comment by sopranopillow** [comment]
I have the documentation done in a branch, but since we are re-working AvatarGroup it will change. I'll updated and add it once the re-work is done.
