### ISSUE TITLE
[Bug]: Breadcrumb - only "..." displayed for too long text item

### ISSUE THREAD

**Issue by nataaad** [microsoft/fluentui#23959]
### Library

React / v7 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 5.08 GB / 15.86 GB
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/nataaad/pen/eYMgaNp

## Actual Behavior
When text is too long, only "..." are displayed.
![image](https://user-images.githubusercontent.com/16607645/179476557-dca5475d-f796-44bf-9510-4606343d0053.png)
https://codepen.io/nataaad/pen/eYMgaNp

## Expected Behavior
At least one item should be displayed even if it is truncated.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ackermannQ** [comment]
I do have the same issue, when the breadcrumbitem text is too large, it's replaced with "..."

**Comment by sachacha** [comment]
I also encountered this issue. I tried to override the component but it did not work... In the meantime, did you find any workaround to avoid it?

**Comment by nataaad** [comment]
> I also encountered this issue. I tried to override the component but it did not work... In the meantime, did you find any workaround to avoid it?

No, I did not find a workaround...

**Comment by Toniotoniotonio** [comment]
What do you mean by "too long" ? Is it always the same limit or does it depend on some factors (windows size, ...) ?

**Comment by nataaad** [comment]
> What do you mean by "too long" ? Is it always the same limit or does it depend on some factors (windows size, ...) ?

It seems that it depends on the size of the window.

**Comment by gouttierre** [comment]
@nataaad - Thanks for filing this issue. I see you stated the issue is in v8 but the codePen you shared is using v7. Have you tried this in the later version (v8)? You can start from one of the [breadcrumb ](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/breadcrumb) examples (click “Export to CodePen”).  Could you confirm the version and retest and get back to us.
