### ISSUE TITLE
[Bug]: Cannot customize GroupedList group headers to include the columns of the table

### ISSUE THREAD

**Issue by ahmednawar1997** [microsoft/fluentui#23965]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
This is not available
```

### Reproduction

https://codepen.io/nawarahmed/pen/MWVpWev?editors=0010

## Overview
We are trying to customize the group header for the DetailsList to have data in the columns of the table. Our approach was to onRenderHeader and render DetailsList with no header for every group header with the same columns as the main DetailsList.

As you can see in the screen shot, we are trying to add the columns details in the group header but the data is not aligned correctly.

![image](https://user-images.githubusercontent.com/25252325/179525542-4343e330-c512-4570-af06-bd3270bde9d4.png)

As you can see in this screenshot, when resizing down the screen width, the columns of the group header does not resize down with it.

![image](https://user-images.githubusercontent.com/25252325/179525587-b4ecd5c9-3cd6-49da-9863-db1ae6ee0f19.png)

![image](https://user-images.githubusercontent.com/25252325/179525565-1f79ae50-0dcf-4e92-8e16-c452214575ab.png)

Please feel free to propose another solution for this design (customized group header to include column details).

## Actual Behavior
The group header (which is rendered as DetailsList) does not resize when we are resizing the screen down. Also, the group header is not aligned with the columns

## Expected Behavior
The group header columns should be aligned with the columns.

### Requested priority

High

### Products/sites affected

https://language.cognitive.azure.com/

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows and all updates will be posted on the issue accordingly.

**Comment by layershifter** [comment]
@ahmednawar1997 I think that it's possible to customize it actually. I am not familiar with this area, but if I understood you correctly you want to archive something like that: https://codesandbox.io/s/laughing-agnesi-uf2z6g

With a custom renderer below you don't need to have nested `DetailsList`s and under `columns` you have already `calculatedWidth` to render columns:

```tsx
const onRenderDetailsHeader = (props: IGroupDividerProps) => {
  return (
    <GroupHeader
      {...props}
      onRenderTitle={() => (
        <div style={{ display: "flex" }}>
          {props.columns.map(column => (
            <div style={{ width: column.calculatedWidth }}>
              {props.group.data[column.fieldName]}
            </div>
          ))}
        </div>
      )}
    />
  );
};
```

Actually with `onRenderTitle` you're customising this part:

https://github.com/microsoft/fluentui/blob/ed1c2354c4069282b0a12240652d0a78cf052ce0/packages/react/src/components/GroupedList/GroupHeader.base.tsx#L259-L273

Please let us know if it works 🐱
