### ISSUE TITLE
Files under `common` folder fail on linter

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/fluentui#23976]
### Environment Information

- **Package version(s)**: v9 packages
- **Browser and OS versions**: irrelevant

### Describe the issue:

Files added under the `common` folder are failing to be found by eslint configuration, as the error states:

> 🚨 The file does not match your project config: src/common/mockDialogContext.ts.
The file must be included in at least one of the projects provided

![image](https://user-images.githubusercontent.com/5483269/179699193-10da5eba-9e95-468b-9267-9c5ae3315450.png)

Requested priority: Low

**Comment by Hotell** [comment]
**Why is this happening:**

If one adds  file/implementation to `common`  ( mocks, some testing helpers etc) and they are not used within any test files, eslint will throw an error.

This is expected as `common` folder is not included in any path resolution withi TS config resolution files:

- spec glob `"**/*.spec.ts", "**/*.spec.tsx", "**/*.test.ts", "**/*.test.tsx", "**/*.d.ts"`
- implementation glob `"./src/**/*.ts", "./src/**/*.tsx", "! ./src/common/**"`
- storybook glob `"../src/**/*.stories.ts", "../src/**/*.stories.tsx"`


Thing is in some packages files that exists within `common` will not throw eslint error. Why ?

_Because how TypeScript works TM._ Althought `common` is not included in any tsconfigs globs, it will be processed if it's used somewhere where globs match passes as TS will parse all three created from statical imports no matter what the include/exclude contains. This will create correct "program" for eslint, thus it will lint the files appropriately.

**Temrporarily Workaround:**

- make sure that files created within `common` are used in one of implementation/test files to make the eslint pass

**Going forward:**

We need to come with better ergonomics/mechanics like where/how to store/create these kind of testing utils in our packages as former behaviour introduces hard to debug issues === BAD DX.
