### ISSUE TITLE
Go to today button gets overlapped on days numbers when 6 weeks visible

### ISSUE THREAD

**Issue by DanielCraig01** [microsoft/fluentui#23980]
### Environment Information

- **Package version(s)**: 7.149.0
- **Browser and OS versions**: Chrome 103.0.5060.114, Windows 11

### Describe the issue:

When the "Go to today" text is displayed it is overlapped when there are 6 weeks visible.

#### Actual behavior:

When the "Go to today" text is displayed it is overlapped when there are 6 weeks visible. Therefore the button is unclickable.

#### Expected behavior:

The "Go to today" button should not be overlapped.

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: Normal
![image](https://user-images.githubusercontent.com/44302103/179733551-c9d78166-7150-4e00-87b6-838536d05f98.png)

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [DatePicker ](https://developer.microsoft.com/en-us/fluentui?fabricVer=7#/controls/web/datepicker) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
