### ISSUE TITLE
Need to resolve privacy concerns with storybook/chromatic telemetry

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#23986]
## Issue
(per discussion in v-build sync meeting)

- Chromatic currently hosts our storybook for Fluent UI React v9
- Chromatic has started collecting telemetry by default
- We are unsure of the privacy review status since it may have been done before the telemetry collection started
- We should disable telemetry collection on our chromatic publication for now
- We should consider hosting the storybook on Azure ourselves
  - This may trigger a wider privacy/security review for our storybook in order to get a certificate for a custom domain
  - We could consider if another team with our org has an existing publication channel we could leverage (piggyback)

**Comment by micahgodbolt** [comment]
@GeoffCoxMSFT where did you hear that they were collecting telemetry? I asked them in slack and they said

> We don’t inject any telemetry in our CDN or extract anything from logs.  There are broad metrics we use for monitoring, but they aren’t broken down on a build basis or even project level.
