### ISSUE TITLE
[Bug]: SpinButton continues to increment this value for as long as the contextual remains open 

### ISSUE THREAD

**Issue by nadineshmo** [microsoft/fluentui#24008]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (20) x64 Intel(R) Core(TM) i9-9900X CPU @ 3.50GHz
    Memory: 15.86 GB / 31.71 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.37)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

this repro's on the Fluent UI SpinButton page: https://developer.microsoft.com/en-us/fluentui#/controls/web/spinbutton

### Bug Description

This is for Fluent UI's SpinButton.

Click and hold the left mouse button the on the down arrow, then, with the left mouse button still held down, click the right mouse button (the user scenario here would be "accidentally clicked both mouse buttons at nearly the same time")
Release both mouse buttons

## Actual:
Continues to increment this value for as long as the contextual remains open and/or as long as the cursor is hovered over the arrow, even though I have released the mouse buttons

## Expected:
Stops incrementing once I release the left mouse button

### Requested priority

Low

### Products/sites affected

AI Architecture & Strategy team

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@nadineshmo -  Thank you for filing this item with us. I'll add this to our contributors queue as it’s lower on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.  In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.

**Comment by khmakoto** [comment]
Hello @nadineshmo, this is browser behavior. You can see that by trying the same thing with a native `<input type="number" />`. Unfortunately, given that this is browser behavior, there is not much we can do about it.

I'll be resolving this issue as "External", but let me know if there is anything else I can help you with.
