### ISSUE TITLE
[Feature]: Support render prop for overflow menu button in Pivot component

### ISSUE THREAD

**Issue by alina-zaieva** [microsoft/fluentui#24001]
### Library

React / v8 (@fluentui/react)

#### Scenario
`Pivot` component supports an overflow behavior where a button with dropdown menu is rendered with all the overflow pivot items. However, this overflow menu button does not have any customization support except for providing a custom `aria-label` via `overflowAriaLabel` prop.

We use `Pivot` component in Microsoft Search UX in SharePoint and Office.com to render tabs for search verticals, and our requirement is that in case of overflow the overflow button should show a special label that includes number of items in the menu (e.g., "3 more" when there are 3 items in the overflow). This is not supported out of the box by `Pivot`, so we have to use a separate custom component together with direct DOM manipulations. This approach is obviously very fragile, and we would prefer to use `Pivot` component without any workarounds as it covers all our other requirements fully.

#### Proposed solution
There is already a component in Fluent UI that is somewhat similar in spirit to `Pivot` - `OverflowSet` - and this component uses `onRenderOverflowButton` render prop to receive a renderer for overflow menu button. On the other hand, `PivotItem` component already supports same approach for rendering custom links (`onRenderItemLink` prop) and it is only the overflow menu button that cannot be customized this way.

Therefore, our proposal is:
1. Add a new prop to `Pivot` component - `onRenderOverflowButton` or similar - which would allow to pass custom renderer for overflow menu button.
2. Pass overflow items to this function and render the overflow button with menu. If it is not provided, then `CommandButton` will be used by default, same as what is currently implemented in `Pivot`.
3. In comparison to `OverflowSet`, `onRenderOverflowButton` will have to support two additional integration points:
    1. `ref` needs to be passed from `Pivot` in order to have working overflow behavior (`menuButtonRef` returned by `useOverflow` hook): https://github.com/microsoft/fluentui/blob/db30e4c8a4c0a00dfee07ef46beb1a37bbe63f25/packages/react/src/components/Pivot/Pivot.base.tsx#L250
    2. Overflow button needs to support "dismiss menu" behavior that is implemented now using a different ref: <https://github.com/microsoft/fluentui/blob/db30e4c8a4c0a00dfee07ef46beb1a37bbe63f25/packages/react/src/components/Pivot/Pivot.base.tsx#L189>

### Additional context

Our Microsoft team is ready to commit to implementing a PR with the proposed solution if the feature and the solution align with Fluent UI design.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gouttierre** [comment]
@alina-zaieva - Thanks for filing this issue with us. Awesome to see you are willing to contribute to the feature request. To set expectations the developers will review this request once capacity allows. 

@TristanWatanabe - Would you be able to confirm if the suggested functionality changes aligns to Fluent UI design? or if this behavior requested is not suitable for the Fluent design system in v8. Thank you!

**Comment by TristanWatanabe** [comment]
@alina-zaieva Spoke to members of the team and you can go ahead with implementing this. One change we would make though is that instead of adding an `onRenderOverflowButton` prop, a `overflowButtonAs` prop might be more appropriate. This is because in this case, you're replacing a known element already (a `CommandButton `) so an `overflowButtonAs` prop with an `Button` interface would be better. You can see how the `overflowButtonAs` prop is implemented in `Breadcrumb` and `CommandBar` components for reference.

**Comment by alina-zaieva** [comment]
@TristanWatanabe thanks for the pointers, created a PR with the proposed solution (see the link above).

**Comment by alina-zaieva** [comment]
@TristanWatanabe I assume this issue can also be marked as done now that the PR is merged. Is there any way to track in which Fluent UI version it will be included?

**Comment by TristanWatanabe** [comment]
@alina-zaieva your PR should be included in version `8.87.0`. You can also see this in the changelog [here](https://github.com/microsoft/fluentui/blob/master/packages/react/CHANGELOG.md).
