### ISSUE TITLE
[Bug]: ToolbarButton (v9) component isn't properly packaged 

### ISSUE THREAD

**Issue by raymeskhoury** [microsoft/fluentui#24015]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
NA
```

### Reproduction

https://codesandbox.io/s/zutwj2?file=/example.tsx

### Bug Description

It seems that the ToolbarButton component isn't properly packaged? The codesandbox links aren't working off here: https://react.fluentui.dev/?path=/docs/preview-components-toolbar--default

See e.g. https://codesandbox.io/s/zutwj2?file=/example.tsx

Also it may be worth noting in the [v8->v9 component mapping](https://react.fluentui.dev/?path=/docs/concepts-upgrading-from-v8-component-mapping--page) that Toolbar is the successor to CommandBar (at least that's what I'm assuming).

### Requested priority

Normal

### Products/sites affected

fluent v9

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@raymeskhoury thanks for the report, indeed `ToolbarButton` was not re-exported. I created a PR to do it, #24015.
