### ISSUE TITLE
Consider allowing a way to collapse a navigation

### ISSUE THREAD

**Issue by scottaohara** [microsoft/fluentui#24011]
For the [nav component](https://developer.microsoft.com/en-us/fluentui#/controls/web/nav), presently if people using fluent want to create a navigation that is shown / hidden via a hamburger menu button, but consistently expose a nav landmark, then they have to add a nav element that wraps the nav component.  And that's odd.

Talking to @smhigley today, this could likely be mitigated by Fluent adding a role prop to the nav component so that authors could overwrite the component's role, and then use the component within their own navigation element.

**Comment by smhigley** [comment]
Yeah, I think the most straightforward and non-breaking change would be to expose `role` as a prop on Nav.
