### ISSUE TITLE
[Feature]: Possibility of Adding size='none' to React-Card component which would Style the React-Card to what it was prior to the introduction of the Size property.

### ISSUE THREAD

**Issue by Keenan-Allgood** [microsoft/fluentui#24029]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

We utilize the react-card component, and have currently styled controls around this. With the introduction to the Size property, a lot of our controls are not appearing as they were. 
Could we avoid using the property to revert the cards back to what they previously were styled as? Something like passing 'none' to the size property.

### Have you discussed this feature with our team

Juraj Kapsiar

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by marcosmoura** [comment]
Adding the `size="none"` prop would introduce some design inconsistencies.
After discussing about this issue, we found out a better way to fix it on the partner's code, which solved the problem and won't introduce a breaking change to the component.
