### ISSUE TITLE
[Bug]: Request for flexible keyboard navigation in BasePicker

### ISSUE THREAD

**Issue by zhnzhzz** [microsoft/fluentui#24028]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 13.14 GB / 31.80 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/keirayang/pen/MWVmZzP

## Actual Behavior
When using keyboard navigation, there is no way we can move the focus to the footer element of BasePicker.

## Expected Behavior
We can move focus to the actionable elements of BasePicker footer with Tab key.

## Comments
For BasePicker, we want to add some buttons in the suggestion footer and make it focusable. Currently no keyboard key can go to footer elements. See the [demo](https://codepen.io/keirayang/pen/MWVmZzP). Thus request for change the keyboard navigation for better Accessibility or provide interface for us to customize the keyboard navigation:

Disable the current Tab key behavior, which has the same result as press Enter key.

Enable Tab key to go to footer actionable elements.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thanks for filing this issue with us and sharing the repro steps. To set expectations the developers will review this issue once capacity allows and all updates will be posted on the issue accordingly.

**Comment by layershifter** [comment]
@zhnzhzz I ported your example to CodeSandbox to simplify debugging (https://codesandbox.io/s/frosty-zeh-7iqkom). I checked what is happening with debugger and it always falls into this branch on <kbd>Tab</kbd>:

https://github.com/microsoft/fluentui/blob/02a6a76a3350adfb4fd95cdfc178864801c8e2bf/packages/react/src/components/pickers/BasePicker.tsx#L635-L645

So there are no options how you can tab to buttons in footer.

---

![image](https://user-images.githubusercontent.com/14183168/185142103-1b6b1135-fc0a-4acf-9507-7709e7e0fbd9.png)

@smhigley would you be able to confirm that it's expected to have any buttons in footer of a picker at all?

**Comment by zhnzhzz** [comment]
Hi, @smhigley can you help take a look?

**Comment by micahgodbolt** [comment]
Talked this over with Sarah, and we agreed that the footer should not contain any interactive elements because this UI pattern does not support them.

If you need an actionable button on the listbox surface, you should add it as an option along with the other suggestions and style it like a button.
