### ISSUE TITLE
Ship/Boat Icon

### ISSUE THREAD

**Issue by alaskandan** [microsoft/fluentui#24047]
### Describe the issue:  [Feature]: New Ocean Vessel Icon

I just wanted to provide some feedback.  NOT A BUG

It would be great to to have a Ship Icon to go along with the plane, and truck that you have.  I'd like to use them for a shipping application

#### Expected behavior:

Ocean Vessel Icon

Requested priority: Low

**Comment by gouttierre** [comment]
Thank you for filing this item with us. I'll add this to our contributors queue as it’s lower on our priority list and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.
