### ISSUE TITLE
[Bug]: [Tooltip][React] Link in tooltip on mobile browsers doesn't work

### ISSUE THREAD

**Issue by aAvoS** [microsoft/fluentui#24054]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz      
    Memory: 37.16 GB / 63.59 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/harryhtet/pen/KKvNMJY

## Actual Behavior
![image](https://user-images.githubusercontent.com/18348867/180773521-f66b4d4f-bd48-4cf1-97d2-6f6d44bfbb5a.png)
Links present inside tooltip are not opening up in mobile browsers. The behavior is as expected in desktop browsers, where links in tooptip can be opened up.

## Expected Behavior
Links present inside tooltip should open up in mobile browsers

### Requested priority

High

### Products/sites affected

https://to-do.office.com/tasks/

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows and all updates will be posted on the issues accordingly by the development team.

**Comment by layershifter** [comment]
I was able to reproduce this on my OnePlus with Android 11 on Chrome 104. This bug affects user experience, but AFAIK we don't have mobile browser support for v0/v7/v8 in our [browser support matrix](https://github.com/microsoft/fluentui/wiki/Browser-Support), only v9 [declares mobile support](https://github.com/microsoft/fluentui/blob/master/rfcs/shared/build-system/06-browser-support-for-v9.md#browser-support-matrix).

**Comment by gouttierre** [comment]
> I was able to reproduce this on my OnePlus with Android 11 on Chrome 104. This bug affects user experience, but AFAIK we don't have mobile browser support for v0/v7/v8 in our [browser support matrix](https://github.com/microsoft/fluentui/wiki/Browser-Support), only v9 [declares mobile support](https://github.com/microsoft/fluentui/blob/master/rfcs/shared/build-system/06-browser-support-for-v9.md#browser-support-matrix).

@JustSlone - Could you confirm that we don't support mobile in Fluent versions other than v9? Thanks
cc @paulgildea

**Comment by JustSlone** [comment]
We support mobile on v8 on a best effort basis. If this is a straightforward fix we'll make it, but if this is a feature add we won't be able to take it. We also welcome contributions to fix important mobile issues on v8. 

@behowell can you or someone from @microsoft/cxe-red investigate this one deeper?

**Comment by layershifter** [comment]
> We support mobile on v8 on a best effort basis. If this is a straightforward fix we'll make it, but if this is a feature add we won't be able to take it. We also welcome contributions to fix important mobile issues on v8.

@JustSlone Thanks for the clarification. Can you update the page (https://github.com/microsoft/fluentui/wiki/Browser-Support) to include this to avoid confusion?

**Comment by JustSlone** [comment]
> @JustSlone Thanks for the clarification. Can you update the page (https://github.com/microsoft/fluentui/wiki/Browser-Support) to include this to avoid confusion?

done: https://github.com/microsoft/fluentui/wiki/Browser-Support#mobile-browser-support-for-fluentuireact-version-8
