### ISSUE TITLE
react-combobox: kick off accessibility UX study with Fable

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#24067]
We (@yvonne-chien-ms and myself) are running a user study on Combobox/Dropdown through Fable Tech Labs to get feedback on interaction patterns, particularly around typing/filtering, keyboard patterns, and multiselect.

Steps:
1. [x] Initial meeting with vendor liaisons
2. [x] Choose specific user testing option (i.e. moderated 1-1 user interview vs. unmoderated rapid feedback)
3. [x] Design scenarios and questions with researcher
4. [x] Build prototype for testing
5. [x] Run study

**Comment by smhigley** [comment]
For the 7/25-8/7 iteration, the plan is to get through steps 1-3.

**Comment by micahgodbolt** [comment]
move this to current iteration. is work currently being done?

**Comment by smhigley** [comment]
Closing as completed
