### ISSUE TITLE
[Bug]: v9 Input (filled) has a shadow by default - not matching the spec

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#24076]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
all systems
```

### Reproduction

https://react.fluentui.dev/?path=/docs/components-input--default#appearance

## Actual Behavior
by default, filled inputs have shadow.

## Expected Behavior
According to the spec:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/13742664/180942385-3f7dc43a-4663-4cc5-ad61-859534e50653.png">

### Requested priority

High

### Products/sites affected

Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Need to follow up with design to check if this applies to other Input-like components such as SpinButton, Combobox, Dropdown, Select, Textarea.
