### ISSUE TITLE
[Bug]: Setting an empty string 'text' prop on ComboBox doesn't unset the visible value

### ISSUE THREAD

**Issue by kelseyyoung** [microsoft/fluentui#24072]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 93.13 GB / 127.71 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/kelseyyoung/pen/oNqePom

## Actual Behavior
Changing the `text` prop value to an empty string `""` does not change the visible value on a ComboBox (alongside `selectedKey = undefined`, not sure if that's required or not)

Using a string with a space in it `" "` does correctly clear the value

The codepen above showcases this by updating the props after 5 seconds. Commented out code shows the string-with-a-space case

## Expected Behavior
Changing the `text` prop value to an empty string "" clears the visible value of the ComboBox

### Requested priority

Normal

### Products/sites affected

Office Online

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
setting the option to 'null' should work to set the option and text back to empty.
