### ISSUE TITLE
[Feature]: Clean up screener code

### ISSUE THREAD

**Issue by ralucapelin** [microsoft/fluentui#24102]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

- [x]  clean up usage of environment variables used by the screener checks code

- [x]  clean up configuration files for screener checks to be relevant according to new changes in the CI/CD workflow

### Have you discussed this feature with our team

ling1726

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ling1726** [comment]
Done in #24739
