### ISSUE TITLE
[Feature]:  Add description section/property to Toggle component

### ISSUE THREAD

**Issue by karthikm897** [microsoft/fluentui#24118]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

![image](https://user-images.githubusercontent.com/14817529/181426424-ba2b9415-5161-4a03-b832-5154765b795b.png)

Often to provide a better product experience we had to add more description to the Toggle Settings. Today this is worked around be appending in label under a separate div element with separate css.

Would be great if Toggle can accommodate an optional description property to help customer understand / build right experience for customer 

### Have you discussed this feature with our team

No

### Additional context

Bugs from relevant scenario : https://github.com/microsoft/fluentui/issues/24117

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gouttierre** [comment]
@karthikm897 - Thank you for filing this item with us. I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance. 
I have scheduled the issue you related to this from the relevant scenario : https://github.com/microsoft/fluentui/issues/24117 to the upcoming investigation cycles.

**Comment by JustSlone** [comment]
@karthikm897 this scenario can be handled via Hint text using the upcoming Field component. It's not exactly what you are looking for, but it covers the scenario of providing some additional information to the user regarding the input control. 
https://react.fluentui.dev/?path=/docs/preview-components-field-switchfield--default

Here's an example:
https://codesandbox.io/s/solitary-grass-ws4q0v
![image](https://user-images.githubusercontent.com/40304143/197421977-28a4e11c-9114-4890-b545-50e130c234a2.png)

**Comment by karthikm897** [comment]
Thanks a lot to FluentUI community for such a quick response and solving
the problem. Appreciate it !!

**Comment by JustSlone** [comment]
Glad you got what you needed @karthikm897. closing this issue
