### ISSUE TITLE
[Bug]: Unable to increase width of Carousel

### ISSUE THREAD

**Issue by MsPoojaSanklecha** [microsoft/fluentui#24120]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
We are using fluent ui Carousel in our web page, we are unable to increase the width of the Carousel. It has a fixed width. Need it to be configurable.
```

### Reproduction

https://aka.ms/kfc

## Actual Behavior
Carousel width is not changeable

## Expected Behavior
Carousel width should be configurable

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hirse** [comment]
You should be able to set the dimensions using `variables` like below, but it looks like there's a bug currently where the size set on `Carousel` does not apply to its children.
```
  <Carousel
    items={carouselItems}
    variables={{
      width: 500,
      height: 500
    }}
  />
```
