### ISSUE TITLE
[Bug]: Cannot copy token names from doc site

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#24130]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
- Windows 11
  - Chrome
  - Edge
  - Firefox
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/theme-color--page

## Actual Behavior

1. Select a token name (e.g., `colorBrandBackground2`).
2. Copy it (e.g., `ctrl + c`, right click > copy)
3. Paste it somewhere else (e.g., `ctrl + v`, right click > paste)
4. Token was not copied to clipboard

![copy_paste](https://user-images.githubusercontent.com/93940821/181617242-e9b73ffd-4cc7-42f6-b737-9fa862ce82d7.gif)

## Expected Behavior

I should be able to copy and paste token names from the doc site.

### Requested priority

High

### Products/sites affected

react.fluentui.dev

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Duplicate #23998?
