### ISSUE TITLE
[Bug]: Dropdown property dropdownWidth="auto" not working in this scenario

### ISSUE THREAD

**Issue by velisekj** [microsoft/fluentui#24137]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Chrome
Version 103.0.5060.134 (Official Build) (64-bit)
```

### Reproduction

https://codepen.io/LemmingCZ/pen/vYRWRPp

## Actual Behavior
![obrazek](https://user-images.githubusercontent.com/3352160/181718060-1a289772-1aa6-4ad5-99fe-f951aa46bb49.png)

## Expected Behavior
![obrazek](https://user-images.githubusercontent.com/3352160/181718152-c79224f8-69a3-4636-bb9b-8a0fab75fd68.png)

### Requested priority

Low

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
> Hey @micahgodbolt Micah Godbolt FTE! I was taking a look at this issue. This bug generated in codepen is because of the change in width of screen and even after the size is more than `480px` it still tries to show the sidebar dropdown.
> 
> I would like to make a PR with a fix, but I am unable to replicate this in storybook. It's working fine for me. How do I do that?

To replicate you need a really long list that will not fit under the dropdown (so that it opens to the right). In the above demo the items are not in a 'sidebar' (note a gap on the right hand side)

**Comment by imrishabh18** [comment]
I tried using a really long list but this issue is not replicated in Storybook, even for different sizes. Check it out here:

<img width="1093" alt="Screenshot 2022-09-09 at 6 29 17 PM" src="https://user-images.githubusercontent.com/38923768/189355731-aedfa87d-6676-4995-be41-f6de9172a07f.png">

<img width="1903" alt="Screenshot 2022-09-09 at 6 29 26 PM" src="https://user-images.githubusercontent.com/38923768/189355831-814e146f-57d4-4d86-b79a-cfb794f31870.png">

**Comment by Poojan3037** [comment]
Hey, Please add responsiveMode={ScreenWidthMaxLarge} prop in the Dropdown component. I hope this will help you.
eg.

import { Dropdown, ScreenWidthMaxLarge } from "@fluentui/react";

 <Dropdown
           placeholder="Select Item"
           options={selectOptions}
            onChange={changeSelect}
            responsiveMode={ScreenWidthMaxLarge}
     />
