### ISSUE TITLE
[Feature]: export GriffelRender type

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/fluentui#24158]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

As documented:

```js
import { createDOMRenderer, RendererProvider, SSRProvider } from '@fluentui/react-components';

function MyApp({ Component, pageProps, renderer }) {
  return (
    // 👇 accepts a renderer from <Document /> or creates a default one
    <RendererProvider renderer={renderer || createDOMRenderer()}>
      <SSRProvider>
        <Component {...pageProps} />
      </SSRProvider>
    </RendererProvider>
  );
}

export default MyApp;
```
The prop `render` of `MyApp` is of type `GriffelRender` in typescript, but this type is not exported, that's to say we have to define it as `any` explicitly, which is not recommended in typescript.

### Have you discussed this feature with our team

No

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by layershifter** [comment]
Fixed in #24202.
