### ISSUE TITLE
Transition away from useAsync in v8 and create best practices for v9

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#24172]
While looking at https://github.com/microsoft/fluentui/pull/24093, we recognized that useAsync is not a great pattern for functional components, and that we should move all of the v8 controls off of useAsync into custom hooks. There is also a goal to create best practices that can be shared with v9 as well. 

- [ ] deprecate useAsync in v8
- [ ] move v8 to dedicated hooks for  useSetTimeOut, useThrottle, useDebounce, useTimeout, useImmediate etc
- [ ] create best practices for v9 components using the same hooks

**Comment by dzearing** [comment]
Yes please! Thanks Micah for opening. We should be avoiding the old monolithic class-based solution in favor of smaller tree-shakable solutions. 

Be aware that async hooks should be `renderToString` safe. That is, if you use these in a server context, they don't start enqueuing async things to happen. Side effects should stay in side effects, where they will be avoided in string rendering scenarios. :)

**Comment by micahgodbolt** [comment]
would love to find another owner for this. i'm not in the headspace to tackle this with all the FAI work going on
