### ISSUE TITLE
[Bug]: Calender forces OS high contrast colors even if the ancestor component disables `force-color-adjust`

### ISSUE THREAD

**Issue by Samigirma1** [microsoft/fluentui#24193]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.03 GB / 15.74 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.77)
    Internet Explorer: 11.0.22000.120
```

### Reproduction

https://codepen.io/samigirma/pen/dymdqBd

## Actual Behavior
The date picker explicitly uses the background and text colors of the window when window's is using high contrast themes. This is problematic when the component is being used under an ancestor that disables forced color adjust. (e.g. when the app want's to explicitly set the colors for high contrast modes. Even if this is discouraged by MDN, [[docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors#accessibility_concerns)] we have use cases that require it.)

CSS from Devtools
![image](https://user-images.githubusercontent.com/46662279/182484509-24c171be-95d0-4e82-9648-2f7e828f1312.png)

## Expected Behavior
Date picker inherits colors from theme and/or style props 

### Requested priority

High

### Products/sites affected

OneNote Fluid

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows and they will update the issue accordingly with the findings.

**Comment by Hotell** [comment]
Can someone from @microsfot/fluent-date-time take a look into this how feasible the implementation is ?  cc @ermercer

**Comment by gouttierre** [comment]
@ermercer and @smhigley could you assist in determining the validity/priority of the issue. Thank you

**Comment by ermercer** [comment]
Adding @microsoft/fluent-date-time team to this issue to help advise here
