### ISSUE TITLE
[Bug]: Multi-select combobox display first option upon typing new value instead of selected options

### ISSUE THREAD

**Issue by aalencar** [microsoft/fluentui#24205]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 11.75 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 103.0.5060.134
    Edge: 103.0.1264.77
    Firefox: 101.0.1
    Safari: 15.5
```

### Reproduction

https://codepen.io/aalencar/pen/ExEEPOy

## Actual Behavior
* Open multi-select ComboBox listbox
* Type a new value and press Enter
* The First element of the list is displayed instead of the previously selected values + typed one

https://user-images.githubusercontent.com/15820796/182652706-687c8f90-1dc8-487a-a8b4-9385bfa18c62.mov

## Expected Behavior
* After typing the new value display all selected values instead of only the first one in the list

### Requested priority

Normal

### Products/sites affected

[H2O.ai Wave](https://github.com/h2oai/wave)

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by JustSlone** [comment]
@aalencar so the issue here is that "First Heading" is shown after hitting enter, instead of "test, Option C, Option D"?

CC: @microsoft/cxe-coastal

**Comment by aalencar** [comment]
@JustSlone yes

**Comment by micahgodbolt** [comment]
This appears to now be fixed.

**Comment by aalencar** [comment]
Seems to be working fine now. Thanks, guys!

https://user-images.githubusercontent.com/15820796/215078212-cd6105c3-44a8-41b5-a1dc-c00192b7ed7f.mov

**Comment by TristanWatanabe** [comment]
Closing as issue has been confirmed as resolved
