### ISSUE TITLE
[Bug]: DatePicker restrictedDates, minDate, maxDate not reflecting accurately on iOS

### ISSUE THREAD

**Issue by rdistasi** [microsoft/fluentui#24211]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz
    Memory: 14.59 GB / 31.71 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://digitalreservations.microsoft.com/en-us/appointment/create/?storeid=9987

## Actual Behavior
On your desktop device, navigate to the provided link, click 'Get shopping advice' -> click 'Surface' -> open the datePicker under 'Choose a day'. Observe that only the next 14 days are available for selection (potentially some days in between may be blacked out as well depending on availability).

Follow the same steps on an iOS device, observe that every day in the month is selectable despite the minDate being set as the current day and maxDate being set as 14 days from current day.

## Expected Behavior
Datepicker should reflect the same behavior between iOS and Windows/Desktop

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hi @rdistasi, I tried to repro the bug with the steps you provided, but wasn't able to. Could you provide a repro without sandbox?

https://developer.microsoft.com/en-us/fluentui#/get-started/web

Thanks!
