### ISSUE TITLE
[Feature]: Dialog close button - configurable props

### ISSUE THREAD

**Issue by mbrzakovic** [microsoft/fluentui#24251]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Currently, close Dialog close button can only be hidden/non hidden and have closeButtonAriaLabel.
https://github.com/microsoft/fluentui/blob/e7597d1df35bd37a8bca78c87e385ac5017d0409/packages/react/src/components/Dialog/DialogContent.base.tsx#L88
Proposal: Add additional property to (I suppose dialogContentProps), to pass through custom props to the close button.

e.g. of a usecase:
Our team is adding custom 'data-id' tag to all active elements, in order to track click-rate via [AppInsights.](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript-click-analytics-plugin).

Due to the missing customization, we don't have much choise other then to do the following:
```
const dialogContentProps: IDialogContentProps = {
    showCloseButton: false,
    topButtonsProps: [{
      ...{
        className: "close-button",
        iconProps: { iconName: 'Cancel' },
        onClick: () => setShowDialog(false)
      } as IButtonProps,
      "data-id": "label.telemetry.example"
    } as any]
```
which is making our code robust.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by micahgodbolt** [comment]
If you are able to work around this limitation, that's great. Our v9 controls are much more customizable and you shouldn't run into that issue. The Dialog is currently in preview right now. https://react.fluentui.dev/?path=/docs/preview-components-dialog--default
