### ISSUE TITLE
[Bug]: Fabric component has button, input, and textarea selectors that add unneeded overhead to style recalcs

### ISSUE THREAD

**Issue by jspurlin** [microsoft/fluentui#24260]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows Server 2016 10.0.14393
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 36.45 GB / 63.90 GB
  Browsers:
    Chrome: 103.0.5060.134
    Internet Explorer: 11.0.14393.2007
```

### Reproduction

https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Fabric/Fabric.styles.ts#:~:text=%27%26%20button%27%3A%20inheritFont,textarea%27%3A%20inheritFont%2C

## Actual Behavior
The `Fabric` component has selectors that match all `button`, `input`, and `textarea` elements inside of it (and sets `{ font-family: 'inherit' }`)  which can lead to a lot of additional checking the browser must do when recalculating styles
<img width="346" alt="image" src="https://user-images.githubusercontent.com/7033561/183203841-b7b2502f-f9d2-408c-b248-e3806a94fbf7.png">

## Expected Behavior
the `Fabric` node shouldn't have these blanket selectors

### Requested priority

Normal

### Products/sites affected

Office Online

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by JustSlone** [comment]
Tagging @khmakoto as he's been working on improving performance here.
