### ISSUE TITLE
[Bug]: Dropdown in panel - focus is not set on first item

### ISSUE THREAD

**Issue by nvazhayil** [microsoft/fluentui#24280]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 19.26 GB / 31.62 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.47)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/dbjorge/pen/qBpMabe

## Actual Behavior

https://fabricweb.z5.web.core.windows.net/oufr/8.55.3/#/examples/dropdown
This is related to behavior of dropdown when accessed via keyboard. When the browser is maximized, pressing on spacebar will open the dropdown inline and when you press DOWN arrow, the 2nd item in the list is selected.

![image](https://user-images.githubusercontent.com/16112438/183491845-b732e13f-107d-4b17-9ad5-398beae8415f.png)

Now, resize the browser so that when we press on spacebar, the dropdown opens as a panel. Press DOWN arrow and you will see that the 3rd item in the list is selected.

![image](https://user-images.githubusercontent.com/16112438/183492664-42b0bb94-9211-4585-a9e2-1e87b6ef3901.png)

On navigating the dropdown via arrow keys on keyboard, there is inconsistency in the item that is selected, when the browser is maximized and resized.  

## Expected Behavior

The selected item should be consistent irrespective of whether the browser is maximized or resized. 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
Hi @nvazhayil , thanks for your report! 

Can you help us understand the problem  better ? The reproduction and your described issue are for 2 separate things. 

ty

**Comment by nvazhayil** [comment]
This is easily reproducible at https://fabricweb.z5.web.core.windows.net/oufr/8.55.3/#/examples/dropdown 
Resize browser and try to access dropdown items via keyboard(DOWN arrow). You should see inconsistency with the item that gets selected.

**Comment by gouttierre** [comment]
@nvazhayil - Thanks for providing more input into the problem you are experiencing. This issue has been queued for upcoming investigations. To set expectations the developers will review this issue once capacity allows and all updates will be posted on the issue accordingly.

**Comment by TristanWatanabe** [comment]
Issue still repros and can be observed when viewport is less than 640px. This is caused by the incorrect list id index being passed to the `firstFocusableTarget` of the `focusTrapZoneProps` prop of the `Panel` component used for the `isSmall` viewport of the `Dropdown`. Simply changing the prop from `#${this._listId}1` to `#${this._listId}0` should correct the issue and have the focus go to the first list option.

https://github.com/microsoft/fluentui/blob/9f8fe44d75df0294762fa6f949126e501b6f79a8/packages/react/src/components/Dropdown/Dropdown.base.tsx#L602

**Comment by AthithyaIthayan** [comment]
can I take up the Issue?
Its my first pick here so 
I should fork it -> make changes -> commit -> sync
If I am right else post a link to the guide Thank You
