### ISSUE TITLE
[Feature]: Remove unnecessary checks from screener code

### ISSUE THREAD

**Issue by ralucapelin** [microsoft/fluentui#24305]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

With the changes from #24292, the ``skipScreener`` environment variable can now be used to determine whether a screener check should be run or not, so other redundant checks and usage of other environment variables can be discarded.

### Have you discussed this feature with our team

ling1726

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ling1726** [comment]
This feature is no longer relevant since the screener-run workflow will check if the artifacts are present and reports that to the proxy.
