### ISSUE TITLE
[Bug]: images don't load in docs

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#24301]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A
```

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/image

## Actual Behavior

![image](https://user-images.githubusercontent.com/14183168/183669210-d393b5f1-b5b5-4ff7-8f0b-07d475fde0cc.png)
![image](https://user-images.githubusercontent.com/14183168/183669346-da570c36-5d08-4d57-8a56-8403389c7628.png)

## Expected Behavior

Images will load.

### Logs

```shell
N/A
```

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
http://via.placeholder.com is being blocked

**Comment by layershifter** [comment]
> http://via.placeholder.com is being blocked

We need to use `https://` there and it will work ;)
