### ISSUE TITLE
[Bug]: Tag Picker component doesnt focus the tag on click

### ISSUE THREAD

**Issue by Divya-2307** [microsoft/fluentui#24314]
- [x] fix ctrl + a and delete key functionality in tag picker
- [x] #24449

### Library

React / v8 (@fluentui/react)

### System Info

```shell
on codepen
```

### Reproduction

https://codepen.io/pen?&prefill_data_id=c02dd12f-ee75-450e-a430-7df671ad470f

## Actual Behavior
ENter multiple tags on tag picker. Clicking on a tag doesnt highlight it
## Expected Behavior
In Fabric 7 version this used to highlight the tag in blue color it doesnt work in fluent 8

### Requested priority

High

### Products/sites affected

sharepoint admin center

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
The codepen provided does not lead to an actual example. Please make sure that you save the codepen before posting the link into the issue.

**Comment by micahgodbolt** [comment]
to clarify, two issues in v8 picker vs v7

ctrl + a does not select all tags
clicking on a tag does not focus the tag

**Comment by micahgodbolt** [comment]
Fixed by #24492
