### ISSUE TITLE
[Feature]: Updated Power Platform icons 

### ISSUE THREAD

**Issue by hugoabernier** [microsoft/fluentui#24325]
### Library

Web Components (@fluentui/web-components)

### Describe the feature that you would like added

Would love to see the new Power Pages, PowerFx, Power Platform, and various other icons that were recently updated (see https://docs.microsoft.com/en-us/power-platform/guidance/icons) reflected in the font icons.

![image](https://user-images.githubusercontent.com/13972467/183958413-bb072965-54c0-446d-988a-9f94e79b6522.png)

### Additional context

Issue is frequently raised in social media and MVP PGI calls.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by micahgodbolt** [comment]
Is this specific to web-components?
