### ISSUE TITLE
[Feature]: Fluent React v9 Preview Banner 🎉

### ISSUE THREAD

**Issue by gouttierre** [microsoft/fluentui#24320]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

In mid to late August the Microsite is planned to go live to the public. To let our customers know of the new site we would like to have a top banner added to the existing [Fluent Design System](https://www.microsoft.com/design/fluent/) to direct customers to the Microsite.

### Solution 
![image](https://user-images.githubusercontent.com/78806055/183884822-f14b1f8a-e5ce-4443-a75c-c6a4026a9200.png)

### Asset Resources 
- For more information into the styling and design, please, view the `website banner` pages in the [Figma file](https://www.figma.com/file/Jm7YiqB9W4lyMA3NxPlK9R/V9-Build-website?node-id=958%3A1908) and make sure to use the design proposed that has 'Frame 3' label on it.
- The `Go To Fluent React v9` button in the banner should direct to https://react.fluentui.dev/

### Have you discussed this feature with our team

yes (Design and Website Team)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by micahgodbolt** [comment]
@gouttierre is this banner only going to be on the home page then? So we'll remove the current banner?

![image](https://user-images.githubusercontent.com/1434956/184256231-a9c65833-8558-4d90-8f2c-0bda0204bcac.png)

Is this a dismiss button for this banner? Or will it always show on the home page?

**Comment by gouttierre** [comment]
> @gouttierre is this banner only going to be on the home page then? So we'll remove the current banner?
> 
> ![image](https://user-images.githubusercontent.com/1434956/184256231-a9c65833-8558-4d90-8f2c-0bda0204bcac.png)
> 
> Is this a dismiss button for this banner? Or will it always show on the home page?

@micahgodbolt - this banner should be on the following url domain:
https://www.microsoft.com/design/fluent/
And its underlying submenus 
i.e. https://www.microsoft.com/design/fluent/#/web 

**Question:** 
Could we add it to the to the url domain for : https://developer.microsoft.com/en-us/fluentui#/ ? To replace the existing one you created?

**Comment by micahgodbolt** [comment]
PR is done and just waiting until the correct time to merge and deploy. Closing this down as the work is done.
