### ISSUE TITLE
ComboBox When the allowFreeForm prop is set to true, voiceover won't open the options

### ISSUE THREAD

**Issue by jean182** [microsoft/fluentui#24336]
### Environment Information

- **Package version(s)**: 8.46.0
- **Browser and OS versions**: macOS Monterey and Chrome 104.0.5112.79

### Describe the issue:

When the allowFreeForm prop is set to true, voiceover won't open the options pressing the ctrl + option + space combination. this is quite misleading because the voice over is telling the user to press that set of keys but it won't open anything.

#### Actual behavior:

When the allowFreeForm prop is set to true, voiceover is not opening the menu if the combination of ctrl + option + space is pressed.

#### Expected behavior:

When the allowFreeForm prop is set to true, voiceover should open the menu if the combination of ctrl + option + space is pressed.

### If applicable, please provide a codepen repro:

The issue occurs in the fluent ComboBox page in the Controlled ComboBox example, or any example that has the Allow freeform toggle.

https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox

### Priorities and help requested (not applicable if asking question):

Yes but I've never contributed here before though.

Requested priority: (Blocking, High, Normal, Low)

High because it makes the component unusable in MacOS if the allowFreeform prop is set to true

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.
