### ISSUE TITLE
[Bug]: npm install command is failing latest react version

### ISSUE THREAD

**Issue by SubbaReddi** [microsoft/fluentui#24365]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 8.07 GB / 15.90 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

Add React- Typescript app to .Net core solution and run following command: npm install @fluentui/react-northstar

## Actual Behavior
npm install @fluentui/react or npm install @fluentui/react-northstar is failing and showing below error:

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: clientapp@0.1.0
npm ERR! Found: @types/react@18.0.17
npm ERR! node_modules/@types/react
npm ERR!   @types/react@"^18.0.17" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@">=16.8.0 <18.0.0" from @fluentui/react@8.87.2
npm ERR! node_modules/@fluentui/react
npm ERR!   @fluentui/react@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\v-sutumm\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\v-sutumm\AppData\Local\npm-cache\_logs\2022-08-14T17_35_07_943Z-debug-0.log

## Expected Behavior
It should install fluent react without errors

### Logs

```shell
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: clientapp@0.1.0
npm ERR! Found: @types/react@18.0.17
npm ERR! node_modules/@types/react
npm ERR!   @types/react@"^18.0.17" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@">=16.8.0 <18.0.0" from @fluentui/react@8.87.2
npm ERR! node_modules/@fluentui/react
npm ERR!   @fluentui/react@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\v-sutumm\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\v-sutumm\AppData\Local\npm-cache\_logs\2022-08-14T17_35_07_943Z-debug-0.log
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
`@fluentui/react-northstar` does not support React 18, please downgrade `@types/react` to `17.*` in your project (currently `@types/react@18.0.17`). Another option is to use `--legacy-peer-deps` to skip that check.

**Comment by kevinfairclough** [comment]
Same error for @fluent/react 8.88.0

**Comment by layershifter** [comment]
> Same error for @fluent/react 8.88.0

https://github.com/microsoft/fluentui/issues/24365#issuecomment-1214740350, the same is true for `@fluentui/react`. Check #22241 for more details.
