### ISSUE TITLE
Contextual menu - background color override on hover and focus interferes with theming

### ISSUE THREAD

**Issue by daweffe** [microsoft/fluentui#24368]
### Environment Information

- **Package version(s)**: 8.10.0
- **Browser and OS versions**: Edge, Windows 11

### Describe the issue:

In Planner, fluent contextual menus are used throughout the product. When both keyboard and mouse are used to navigate through a menu, a white background color is applied to the button, overriding our theme styles:
 
![fluent contextual menu background override in Planner](https://user-images.githubusercontent.com/29383146/184677481-2fe2a670-273e-486b-b777-f43cac493ce6.gif)

I can reproduce this issue on the fluent contectual men sample page:

![fluent contextual menu button background](https://user-images.githubusercontent.com/29383146/184677586-900df348-eb16-4130-8b15-52a762cc098d.gif)

#### Actual behavior:

In some cases, the contextual menu button background is set to white on hover or focus

#### Expected behavior:

Do not set this background color override on hover and focus

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? ( No)

Requested priority: High - this affects production code with millions of daily users

Products/sites affected: Planner web, Tasks in Teams app

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows and all updates regarding the findings will be posted on the issue accordingly.

**Comment by layershifter** [comment]
I can reproduce white background on docsite:

![image](https://user-images.githubusercontent.com/14183168/185148896-92db3e17-f5e8-4dae-876c-a0eab54bddaa.png)

But there is nothing wrong with it 🤔 I tried to reproduce it with a dark theme and created a CodeSandbox (https://codesandbox.io/s/dazzling-burnell-12t6ms), but I can't repro it there as `background` has a proper value there:

![image](https://user-images.githubusercontent.com/14183168/185149575-eabb4f05-e0ec-4c81-a60e-2bca91cad708.png)

---

Can you please fork my CodeSandbox (https://codesandbox.io/s/dazzling-burnell-12t6ms) or provide yours repo so I could check?

P.S. I used latest version of v8.

**Comment by daweffe** [comment]
Thanks for looking at this. So maybe we just need to fix it on our side by passing in the correct background color based on our theme?

**Comment by layershifter** [comment]
> Thanks for looking at this. So maybe we just need to fix it on our side by passing in the correct background color based on our theme?

Yeah, currently it looks like a problem on your side. If you can provide a repro I will take a look.

**Comment by ErichL** [comment]
> > Thanks for looking at this. So maybe we just need to fix it on our side by passing in the correct background color based on our theme?
> 
> Yeah, currently it looks like a problem on your side. If you can provide a repro I will take a look.

It looks like the issue is caused by the ContextualMenu style using palette.white directly.

https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/ContextualMenu/ContextualMenu.cnstyles.ts#L82

```
      rootFocused: {
        backgroundColor: palette.white,
      },
```

This means you cannot change the focus colour of the menu unless you want to change the whites across the application. It would be nice to replace this with a new semantic colour like `semanticColors.menuItemBackgroundFocused` that is defaulted to `palette.white` instead of linking it directly to white which makes it much harder to change.
