### ISSUE TITLE
Cannot SHIFT+Tab out of nested FocusZones with List

### ISSUE THREAD

**Issue by capucat** [microsoft/fluentui#24369]
### Environment Information

- **Package version(s)**: Fluent 7
- **Browser and OS versions**: Edge/Chrome

### Describe the issue:

When a fluent List wrapped by a FocusZone contains list items that have FocusZones, you cannot SHIFT+TAB out of the List. You can however, TAB out to something under the List.

Specifically, it seems like this is due to the usage of both **shouldFocusInnerElementWhenReceivedFocused** and **data-is-focusable** on the listItem's FocusZone. Is there any other way to achieve the same keyboard behavior as shown in the codepen, but that allows navigating back to the button above the List?

#### Actual behavior:

SHIFT+TAB does not allow user to leave List/listitem to button(s) above List

#### Expected behavior:

SHIFT+TAB should allow user to navigate backwards out of the List

### If applicable, please provide a codepen repro:

Some context: 
Our actual feature is more complex, where the listitems themselves are interactable. The 'Edit' button is not visually within the list (rather it's slightly above it). The single 'download' button here represents a few interactable elements that are in a CommandBar above the List.

https://codepen.io/capucat/pen/bGvjqJY

**Comment by micahgodbolt** [comment]
have you been able to try this in Fluent UI v8 to see if the problem persists?

**Comment by capucat** [comment]
yes, I've made a codepen with v8 and the issue still persists, although it required a couple extra things in order for it to work the same as in v7 as the ListItems were not focusable due to the FocusZone
