### ISSUE TITLE
Re-export @fluentui/* packages in v7 to make migration from v7 -> v8 easier. 

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#24393]
re-export @fluentui/* packages in v7 to make migration from v7 -> v8 easier. 

The following packages are needed by ODSP to ease migration (if you would rather just re-export all of the packages listed here: https://github.com/microsoft/fluentui/wiki/Version-8-migration-guide#uifabric-package-renames that is fine too).

- [x] @fluentui/font-icons-mdl2 (re-export @uifabric/icons) (@GeoffCoxMSFT)
  - [ ] Add export of IconInputNames (@GeoffCoxMSFT) 
- [x] #24416 (@micahgodbolt)
- [x] @fluentui/react-experiments (re-exports @uifabric/experiments) (@GeoffCoxMSFT)
- [x] @fluentui/react-file-type-icons (re-exports @uifabric/file-type-icons) (@GeoffCoxMSFT)
- [x] @fluentui/merge-styles (re-exports @uifabric/merge-styles) (@GeoffCoxMSFT)
- [x] @fluentui/react-cards (re-exports @uifabric/react-cards) (@GeoffCoxMSFT)
- [x] @fluentui/react-hooks (re-exports @uifabric/react-hooks) (@GeoffCoxMSFT)
- [x] #24625 (@micahgodbolt)
- [x] @fluentui/scheme-utilities (re-exports @uifabric/variants) (@GeoffCoxMSFT)
- [x] #24569 (@micahgodbolt)
- [ ] Add export of PivotLinkFormatType and PivotLinkSizeType

Quote from dzearing who did the investigation:
>After looking at the imports within odsp-web, I wrote up some renaming guidance and some recommendations for both fluent and odsp to make the renames relatively easy and to address a lot of the friction.
>
>On the fluent side, there is a wiki post covering package renames for v8, but there are a few missing re-export packages we can scaffold to make the rename-without-upgrading possible. The full list of package re-exports missing is (listed above)
>
>On the odsp side, the biggest challenge is the > 1 level deep imports into oufr. This is code debt that will break in the v8 upgrade, and should be cleaned up. An odsp dev can likely help here, but fluent can help make sure anything not exported at the top level is indeed a contract in both v7 and v8.
>
>Examples of this sort of concern:
>office-ui-fabric-react/lib/utilities/dateValues/DateValues
>...when it should be coming from 1-level deep imports which exist in both v7 and v8. Without fixing this we're relying on internal file structures which will break once exports maps are introduced in the v8 upgrade.
>
>Here is the full translation list and my notes:
>
>https://hackmd.io/yauU0bMBSw6LsOV8HX8Nnw?view

**Comment by micahgodbolt** [comment]
Looks like we got all of these, and then some 

![image](https://user-images.githubusercontent.com/1434956/189157994-0f8cbaf6-49e2-4f1e-bde3-86d6fc8e5d39.png)
