### ISSUE TITLE
[Bug]: Spinner renders as a plain circle with prefers-reduced-motion

### ISSUE THREAD

**Issue by NotWoods** [microsoft/fluentui#24405]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-spinner--default

## Actual Behavior
With prefers-reduced-motion, the spinner shows up as a motionless circle with the brand color. This doesn't communicate "Loading" at all and looks odd.

This is reproducable by turning on reduced motion settings (either emulate with DevTools or change computer settings) then looking at the Fluent UI storybook.

## Expected Behavior
I expect to see either simplified animation ([reduced motion doesn't mean no motion](https://www.smashingmagazine.com/2021/10/respecting-users-motion-preferences/#reduced-motion-doesn-t-mean-no-motion)) or some alternate icon like "...".

Related: #23193

### Requested priority

Normal

### Products/sites affected

Microsoft Loop

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
Hi, thanks for opening this issue! Just a quick update: we're currently looking into what we'd want the design to be for the no-motion loading indicator. Ideally, we'd want it to be somewhat standardized across desktop and web.

There's actually a pretty good reason to avoid motion entirely in this case -- while a small linear-motion animation could work for a full page loader, Spinner can also be used to show a loading state for one or more subsections of a page. In that case, and particularly if there are multiple at once, any motion could be distracting enough to block interaction with the rest of the page.
