### ISSUE TITLE
[Bug]: ComboBox,After the drop-down option is selected, reassign the drop-down list, and the selected data does not echo correctly

### ISSUE THREAD

**Issue by ChangBaiMonster** [microsoft/fluentui#24407]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
When the drop-down option has a first word that is the same and is three words, the drop-down selection and then reassign drop-down list will not be echoed correctly.        Interestingly, when there is a first word that is the same and is two words, it will be echoed correctly
```

### Reproduction

https://codepen.io/wqwdna/pen/ZExVXqo?editors=1010

## Actual Behavior
When the drop-down option has the same first word and is three words, such as the drop-down option is ['Finished', 'Finished With Exception'], select 'Finished With Exception', then click the button to reassign the drop-down list as ['Finished', 'Finished With Exception'], and want the default value to be 'Finished', which cannot be echoed correctly at this time, and still displays 'Finished With Exception'.        

## Expected Behavior
Hopefully, click the button again to reassign the drop-down list as [ 'Finished', 'Finished With Exception' ], and hopefully the default value is 'Finished' to correctly echo the default value 'Finished'. 

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ChangBaiMonster** [comment]
version:  @fluentui/react : ^8.79.0

**Comment by micahgodbolt** [comment]
Can you reduce your demo down to the bare minimum needed to reproduce the error? It is difficult to know if the issue is in Combobox or the code you wrote to support your demo.

**Comment by ChangBaiMonster** [comment]
> Can you reduce your demo down to the bare minimum needed to reproduce the error? It is difficult to know if the issue is in Combobox or the code you wrote to support your demo.
I know what you mean, but believe me, this is the simplest example I can restore

**Comment by ChangBaiMonster** [comment]
> Can you reduce your demo down to the bare minimum needed to reproduce the error? It is difficult to know if the issue is in Combobox or the code you wrote to support your demo.

Thank you very much for your reply, but I have found a solution, add a key to comboBox, every time you click button, change the key of comboBox, just make it. Although I still think it has problems, the ideal state is to automatically switch data columns without adding a key.
I still hope you will look at this problem, in the example I updated the code, added const [key, setKey] = React.useState<string>('test1');
