### ISSUE TITLE
[MessageBar Bug]: Link inside MessageBar should follow theme color

### ISSUE THREAD

**Issue by MirandaGe** [microsoft/fluentui#24409]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows Server 2016 10.0.14393
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz
    Memory: 8.53 GB / 16.00 GB
  Browsers:
    Chrome: 104.0.5112.101
    Internet Explorer: 11.0.14393.2007
```

### Are you reporting Accessibility issue?

no

### Reproduction

codepen of repro: https://codepen.io/lingge/pen/VwXqydx

## Actual Behavior
![image](https://user-images.githubusercontent.com/16030290/185346753-6716c5d2-d8a8-4791-8317-023ec14d2249.png)

## Expected Behavior
Expect the link in message bar also follow the theme color, like normal link outside of the message bar.

### Requested priority

Normal

### Products/sites affected

SharePoint

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
The message bar links use a specific semantic color so that they properly contrast with the component background. You can modify that color by adding a customization to the messageLink token

``` 
const appTheme = {
  palette: {
    themePrimary: 'red',
    themeDarker: 'red'
  },
  semanticColors: {
    messageLink: 'red'
  }
};
```
