### ISSUE TITLE
Dropdown quickly dissmisses when clicked from outside FocusTrapZone

### ISSUE THREAD

**Issue by elmazdremdzhe** [microsoft/fluentui#24404]
### Environment Information

- **Package version(s)**:  Fluent 7
- **Browser and OS versions**: Edge/Chrome

### Describe the issue:

When user is trapped in FocusTrapZone that has "isClickableOutsideFocusTrap":true and clicks on the dropdown that lives outside of the FocusTrapZone, dropdown flickers and disappears. CodePen has repro of the issue. 

To reproduce:
1. Enable FocusTrapZone (isClickableOutsideFocusTrap:true)
2. Click on the dropdown (in codePen: "Dropdown outside FocusTrapZone")

#### Actual behavior:

When clicking on dropdown, it flickers and disappears

#### Expected behavior:

When clicking on dropdown, it shows up and items inside it are clickable.

### If applicable, please provide a codepen repro:

https://codepen.io/elmaz/pen/VwXqPNW

**Comment by micahgodbolt** [comment]
note that the panel opens when viewport is smaller, but dropdown dismisses

**Comment by micahgodbolt** [comment]
I'm guessing that this is a dropdown bug, and is related to #24151
