### ISSUE TITLE
[Bug]: focusRect classname may hang around after the useFocusRects component is disposed

### ISSUE THREAD

**Issue by jspurlin** [microsoft/fluentui#24419]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows Server 2016 10.0.14393
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 36.45 GB / 63.90 GB
  Browsers:
    Chrome: 103.0.5060.134
    Internet Explorer: 11.0.14393.2007
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/jspurlin/pen/ZExVZwp

### Bug Description

Repro Steps:
1. navigate to https://codepen.io/jspurlin/pen/ZExVZwp
2. put focus in the result frame
3. press TAB until focus is on the "Hide Standard Button" button
4. click the "Hide Standard Button" button
a.  The standard button is unmounted (which removes the handlers on the Fabric node) but the classname stays

## Actual Behavior
When a component that uses focusRects (e.g. `useFocusRects` or `<FocusRects/>`) is unmounted the classname is not cleaned up

## Expected Behavior
When unmounted, any classname that was set as part of `useFocusRects` should also be removed

This behavior could result in one useFocusRect instance could write to the body which could set focusVisible, be unmounted, but the classname stays focusVisible so components inside another unrelated provider (potentially rendered inside their own ReactDOM.render on a different part of the page) could be impacted (especially if the useFocusRects that gets unmounted didn't have a FocusRectsProvider and hence writes the classname to the body), potentially making components show keyboard focus state when they shouldn't.

Clearing the classname should be safe because if there is another useFocusRects instance tied to the same provider/body it will add the correct classname on the next input (mouse or keyboard)

### Requested priority

High

### Products/sites affected

Office Online

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
@jspurlin Is there a real-world example of this causing a user bad (i.e. focus rect not visible when it should be)? It doesn't seem like it would cause problems in practice.

>components inside another unrelated provider (potentially rendered inside their own ReactDOM.render on a different part of the page) could be impacted (especially if the useFocusRects that gets unmounted didn't have a FocusRectsProvider and hence writes the classname to the body), potentially making components show keyboard focus state when they shouldn't.

The other component would update the focusrect class on the root when it gets mouse or keyboard input, so focus rect visibility should be corrected when it gets focus.

----

I'd rather avoid making further changes to the FocusRect code if this is just a theoretical bug. The code is already a bit complex, and further changes could risk regressions.

**Comment by jspurlin** [comment]
Yes, you could run into a problem where the focus rect shows up when it shouldn't, or worse, not show up when it should (e.g. keyboard navigation)

**Comment by behowell** [comment]
Hi @jspurlin, I wanted to follow up since it's been a while since the last discussion on this issue Have you seen any real-world bugs that result from this behavior? Given that changes to focus rect code seem to have a higher risk of regressions, we'd prefer not to make changes for something that doesn't have a user impact. Thanks.
