### ISSUE TITLE
[Feature]: Use proper logger in screener proxy

### ISSUE THREAD

**Issue by ralucapelin** [microsoft/fluentui#24410]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Screener proxy should use a logger that allows to automatically include relevant information such as PR number for easier debugging.

### Have you discussed this feature with our team

ling1726

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by layershifter** [comment]
We don't use Screener anymore, closing.
