### ISSUE TITLE
Implement DataGrid component

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#24420]
The DataGrid component is intended to be 'smart' component that uses both the table primitives (such as those that are tested as a part of #24386) and the headless table state hook that should be implemented as a part of #24226.

This component will be opinionated and satisfy users that don't want to wire up primitives with state and manage other concerns like accessibility. The component should be accessible by default.

While it would be nice to support virtualization in this component (#24229) it depends on feasibility

**Comment by dzearing** [comment]
What I've learned with implementing DetailsList:

* 1 size doesn't fit all - some scenarios users want render 20 items max, some render 20,000 items. Most things are 500-1000 items which makes not virtualizing a non starter. I'd recommend starting with virtualization.
* not just vertical - horizontal too - usually we have 5 columns, but what about 50 columns with 20k items?
* Sometimes, it should behave like a table, growing columns. But other time, it should behave like excel.
* Sometimes(usually) you want it embedded in document body's scroll, while other times you can get away with a dedicated scrollable region.
* Don't forget about grouping. Grouping adds even more complexity (do you virtualize the group headers? What about groups of groups?)
* Selection needs to be able to be seperately managed; this enables you to change out the ui representation (grid, photos, etc) without resetting selection. Virtualization also needs selection.
* Keyboarding becomes a stress test. And creates some really nasty bugs if you don't have proprietary focus management which is virtualization friendly. We use FocusZone for keyboarding, which works decently in row navigation or cell navigation, but when you hit the non-materialized "gap", it will skip over it, looking for the next available focus target. Bad bug, hard to fix without special handling (e.g. ugh, we've hit a virtualized region... wait for it to materialize, then proceed to navigate.)
* Don't forget about marquee selection!

react-virtualized had this pretty nice wizard to ask a lot of question. They're necessary. Layers really help but even react-window doesn't answer a lot of these things.

DetailsList is one of the most popular components in the group, so it needs the most love and i'm happy to see you have some interest here! There's another dev also looking at this problem in another team; maybe you 2 can compare notes.

**Comment by chihiroxc** [comment]
@ling1726 Hi, I'm using DetailsList to render a big table, the table could be hundreds of columns. But DetailsList doesn't have column virtualization which will cause some perf issues. Looks like this DataGrid component fits us better, will it have column virtualization?

**Comment by ling1726** [comment]
@chihiroxc I don't think column virtualization has ever been considered. However, using the `Table` primitives and the `useTable` hook it should be pretty straightforward to implement column virtualization
