### ISSUE TITLE
Try to migrate v8 DetailsList with Table and DataGrid

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#24421]
Use the DetailsList documentation https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist and try to do a migration of the basic examples in the docsite from that existing code.

Try migrate with both primitives + state hook and DataGrid component

Objective: learn how hard/easy(lol) it was

**Comment by dzearing** [comment]
If you have any q's or need to bounce ideas, ping me :)
