### ISSUE TITLE
Stress Test: Add more testing scenarios

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#24424]
The Stress Test app currently has five testing scenarios:

1. Mount
2. Prop update
3. Style injection
4. Add nodes
5. Remove nodes

All of these tests are somewhat extreme cases in that they do things like "mount 1000 components", "update 1000 components" which are good for learning about behavior in extreme cases but we should add test cases for more typical scenarios that would be expected in an app.

For example, mount 1000 components and then pick one component at random and update its props.

Tasks

- [ ] Create list of new test scenarios
- [ ] Implement test scenarios

**Comment by JustSlone** [comment]
Assigning to cxe-red, since this is self-filled feel free to choose your own priority. If you want advice marke Needs Backlog review

**Comment by spmonahan** [comment]
New test scenarios:

- [ ] Load components, update a prop on every 10th component
- [ ] Load components, click every 10th component
- [ ] Load components, add just a few more components (currently we add a large number of components)
- [ ] Load components, remove every 10th component
