### ISSUE TITLE
[Bug]: Menu doesn't call onBlur for contextualmenuitem when the menu is closed

### ISSUE THREAD

**Issue by makopch-ms** [microsoft/fluentui#24427]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Windows 11 w/ Edge
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/makopch/pen/mdxaNrX

## Actual Behavior
1. Open Menu
2. Keyboard between items (notice Focus & Blur output in console)
3. Press Esc to close menu

Nothing is printed to the console

## Expected Behavior
When the menu is closed, the blur even on the focused contextual menu item is fired.

### Requested priority

Normal

### Products/sites affected

Office Online

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
@makopch-ms unmounting focused elements in React does not trigger `onBlur` https://codesandbox.io/s/adoring-flower-xk881j?file=/src/App.js

Could you please give some more details on what you're trying to achieve by detecting `onBlur` when the contextual menu is closed ? In this case it would seem that `onDismiss` would be a more appropriate way to handle that logic
