### ISSUE TITLE
Table: there is an unexcepted gap between the thead and tbody elements

### ISSUE THREAD

**Issue by NagiaME** [microsoft/fluentui#24439]
### Environment Information

- **Package version(s)**: v9.2.0
- **Browser and OS versions**: Edge (Chromium 104)

### Describe the issue:

There is an gap between the thead and tbody elements in the table component.
![image](https://user-images.githubusercontent.com/11983319/185733700-592ddcf4-c4c6-4309-a075-93450a31e526.png)

#### Actual behavior:

No gap/space should show between the table head and table body.

#### Expected behavior:

Gap/space between the table head and table body.

### If applicable, please provide a codepen repro:

The solution: just to add a CSS property onto the table element:
```css
border-collapse: collapse;
```

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: https://react.fluentui.dev/?path=/docs/preview-components-table--default

**Comment by ling1726** [comment]
Fixed by #24762 using @KBoeh's fix
