### ISSUE TITLE
[Bug]: V9 Dialog content layout breaks when wrapped in element

### ISSUE THREAD

**Issue by NotWoods** [microsoft/fluentui#24433]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/affectionate-varahamihira-kq9yyb?file=/example.tsx

## Actual Behavior
When using a form inside a Dialog to capture submit events, the dialog styling is thrown off.

## Expected Behavior
Wrapper elements like `<form>` can be used.

We'd like to use forms inside dialogs to easily capture "submit" events. We have dialogs with input elements and submit buttons, where the input is in the dialog body and the submit button is in the dialog actions.

This is a common pattern with native HTML dialogs, indicated by the fact that [forms can close native dialogs on submit](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-method).

### Requested priority

Normal

### Products/sites affected

Microsoft Loop

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
The contents of a Dialog are laid out via CSS grid, which is targeting the children of the DialogSurface. Adding the form element breaks that parent/child relationship. Simply adding a 'div' has the same effect. 

You don't need a form element to perform form like actions. Or if you absolutely need to add that element, you'll need to apply your own styling to the children below (or use subgrid once that is more commonly available)
