### ISSUE TITLE
Position of items in DetailList - Grouped is not changing when increasing the level of group in fluentui

### ISSUE THREAD

**Issue by sauravlikhar** [microsoft/fluentui#24441]
### Discussed in https://github.com/microsoft/fluentui/discussions/24440

<div type='discussions-op-text'>

<sup>Originally posted by **sauravlikhar** August 20, 2022</sup>
I want to create one list of nested grouped rows using DetailList in fluentui mentioned [here](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/grouped)

When we increase the level of any group item it is getting shifted to right by one level. I want the items also to be shifted inside this group.

This is the snapshot when I increased the level of groupred0 to 2 enter image description here

<img width="605" alt="image" src="https://user-images.githubusercontent.com/85556281/185743461-2c95f6be-a11d-47ef-bf91-538c66b1a1c9.png">

I want the row items 'a' and 'b' to be aligned with 'Color: "red"(2)' because in my use case there will be multiple groups nested like a file directory structure.

I also can not use the groupedlist of fluentui mentioned [here](https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist)

Because it does not have the option for the list columns header as in the DetailsList.</div>

**Comment by JustSlone** [comment]
Right, so as I understand it you want a table with hierarchal and collapsable sections? I don't believe that is supported and is complicated for the reason Micah mentioned around the cells lining up with the headers. 

This sounds like a combination between Tree and Table/Grid, something that we're looking to enable via composition in v9, but don't have support for in v8. It's perhaps possible that it could be accomplished with heavy customization, but I'd recommend against it. 

Tagging @spmonahan to correct me if I'm wrong. 
CC: @ling1726 for future table scenario

**Comment by spmonahan** [comment]
Yes, that's correct that we don't support this in v8 and have no plans to implement it.
