### ISSUE TITLE
[Feature]: brand variants designer

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/fluentui#24465]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

- A designer for making brand color variants. Similar to [v8 Theme Designer](https://aka.ms/themedesigner). 
- Explain what each variant is used for (use variant 80 as theme color in light mode, use variant xx as theme color in dark mode, etc.).
- A contrast ratio checker.

### Have you discussed this feature with our team

No

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JustSlone** [comment]
@AkiraVoid try this: 
https://fluentuipr.z22.web.core.windows.net/heads/master/theme-designer/storybook/index.html?path=/story/themedesigner--page

@micahgodbolt we might want to prioritize the work to get a stable link for the theme designer and a link from our v9 storybook.

**Comment by micahgodbolt** [comment]
I have an aka link at [aka.ms/fluentdesigner-vt](https://aka.ms/themedesigner-v9)

**Comment by micahgodbolt** [comment]
Closing issue down in favor of starting an epic to track work/progress #25424
