### ISSUE TITLE
[Docs]: Make draggable modal's drag target the title so text can be selected

### ISSUE THREAD

**Issue by cherie-msft** [microsoft/fluentui#24469]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
npx: installed 1 in 1.4s

  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 18.83 GB / 31.71 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.22000.120
```

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/modal

## Actual Behavior
When opening a draggable modal, you can't select any of the text inside the dialog. This repros on the modal sample page as well. (It is possible there's a setting to enable this behavior but I can't figure it out)

## Expected Behavior
Should be able to select text

### Requested priority

High

### Products/sites affected

Power Apps

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Not really a bug, but our docs could be better.

Draggable options allow you to select the dragHandleSelector. If you ommit the selector than the entire modal is the click target.

https://codepen.io/micahgodbolt/pen/poLBbQa?editors=0010

**Comment by cherie-msft** [comment]
Thank you so much! That did fix it for me :)
