### ISSUE TITLE
Accessibility: Talkback does not access content within a dialog that contains no interactive content

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#24471]
After going through the talkback portion of #23773, we found a bug with dialogs that do not have interactive content. This issue is to track the progress of the bug filed in google's issuetracker. 

[link to issuetracker](https://issuetracker.google.com/issues/243456562)

**Comment by behowell** [comment]
Add to known issues for AvatarGroup (and Dialog? etc?)
