### ISSUE TITLE
[Bug][Panel]: Wide content breaks sticky nav and header.

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#24502]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 15.48 GB / 31.90 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.22000.120
```

### Reproduction

https://codepen.io/mltejera/pen/oNqOQpm

### Bug Description

When the panel content is wider than the panel, the nav and header scroll to the right along with the content. The nav should stay fixed.

![image](https://user-images.githubusercontent.com/17346018/186475813-1883eafb-5ff4-4306-9bce-f9b3f7d7a823.png)

### Requested priority

Normal

### Products/sites affected

MADS, M365 Admin Center

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mltejera** [comment]
Any chance this PR might have something to do with it?

https://github.com/microsoft/fluentui/pull/22408

**Comment by micahgodbolt** [comment]
Wish the commands and content div being siblings now, if you want the stuff inside content to be bigger, you'll need to constrain content by adding overflow-x:  scroll
