### ISSUE TITLE
[Bug]: Narrator announces selected ComboBox item twice

### ISSUE THREAD

**Issue by kpasagada** [microsoft/fluentui#24518]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 1.67 GB / 15.79 GB
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/kpasagada/pen/OJvGerN

## Description
Narrator announces the selected combo box item twice. 
Screen reader user will get confused while navigating to the control.
This does not happen in Chrome + NVDA. 

https://user-images.githubusercontent.com/42693353/186553770-6c5a86dc-6c0b-45cf-8532-ba3379ed8d98.mp4

## Actual Behavior
The narrator announces the selected combo box item information twice.

## Expected Behavior
The narrator should announce the selected combo box item information only once.

## Similar bugs reported 
https://github.com/microsoft/fluentui/issues/7408
https://github.com/microsoft/fluentui/issues/13772

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
What are you hearing spoken twice? I hear "ComboBox with toggleable freeform/auto-complete, option a , combo edit collapsed, has popup, Option A selected." 

The option A thing is a little redundant, but the 2nd one is saying that the text is selected, while the first is saying that option a is the current value of the combo box.

**Comment by kpasagada** [comment]
@micahgodbolt If you watch the linked video above (0:26), you can hear narrator announce "option A, 1 of 10, selected, scan, option A, selected".

It looks like it is announcing the selected option twice. It is a bit redundant yes, but it does not happen with NVDA. 

Our a11y team raised this as an issue and hence I wanted to check with you to see if this is a bug or if it is expected behavior from narrator.

**Comment by micahgodbolt** [comment]
Yeah, this is expected behavior. We can't really control how Narrator works, we can just ensure that our DOM is set up correctly for Narrator to do what it wants to do :)
