### ISSUE TITLE
[Bug]: Modal: does not respect LayerProps.insertFirst

### ISSUE THREAD

**Issue by jspurlin** [microsoft/fluentui#24527]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
windows
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://github.com/microsoft/fluentui/blob/3ce6e295fa7c514409413e5ce6b812338fd5ad1c/packages/react/src/components/Modal/Modal.base.tsx#:~:text=insertFirst%3A%20isModeless%2C

## Actual Behavior
Modal does not respect insertFirst if passed in on the layerProps

## Expected Behavior
Modal to respect the isertFirst prop if explicitly passed in

### Requested priority

Normal

### Products/sites affected

Office Online

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
@jspurlin are you planning to fix this? Should I assign it to you?

**Comment by jspurlin** [comment]
Already on it: https://github.com/microsoft/fluentui/pull/24528 🙂

**Comment by micahgodbolt** [comment]
fixed in #24528
