### ISSUE TITLE
onRenderSuffix prop  equivalent for comboBox

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#24552]
### Discussed in https://github.com/microsoft/fluentui/discussions/22195

<div type='discussions-op-text'>

<sup>Originally posted by **chrichung** March 23, 2022</sup>
TextField has a prop for onRenderSuffix where I can render a Spinner component to indicate that a save call is being made. However, comboBox doesn't have something like that from looking at the [IComboBoxProps interface](https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox). Any idea how I can implement the following for comboBox?

`onRenderSuffix: () => {
            return (
                <>
                    {isSubmitting && (
                        <TooltipHost
                            id="goal-saving-id"
                            content={getLocalizedString(ControlStringConstants.savingButton)}
                        >
                            <Spinner aria-describedby="goal-saving-id" />
                        </TooltipHost>
                    )}
                </>
            );
        }`</div>

**Comment by JustSlone** [comment]
We aren't actively adding features to v8 unless they are high priority. This scenario should be covered by slots in v9 @smhigley correct me if I'm wrong. 

Leaving open for further discussion or contribution if someone is able to do this with a minimal change.
