### ISSUE TITLE
[Feature]: SideBar Push Menu option 

### ISSUE THREAD

**Issue by mitrichy20000** [microsoft/fluentui#24565]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

![Capture](https://user-images.githubusercontent.com/107667536/187192418-19db8a8e-a9a0-4903-8f29-205f40787880.PNG)

Fluent UI, doesn't have push side bar. I want same screen sidebar auto adjust screen. If fluent UI have please ping me here the documentation here.

I attached example side bar image. please refer above image.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JustSlone** [comment]
Fluent UI React v8 has a Panel component that is a simple surface allowing you to add content. It animates in, which is likely customizable, but doesn't have any other animations built into the component. 

Check it out: https://developer.microsoft.com/en-us/fluentui#/controls/web/panel
