### ISSUE TITLE
[Bug]: Accordion item is collapsed by clicking on components inside it's content

### ISSUE THREAD

**Issue by chroustak1** [microsoft/fluentui#24561]
### Library

Web Components (@fluentui/web-components)

### System Info

```shell
Windows
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/practical-hamilton-6cv6vs?file=/index.html

## Actual Behavior
Accordion items placed inside an accordion with **expand-mode=single** are collapsed by clicking on a component (e.g. checkbox, another sub accordion item) placed inside its content.
![image](https://user-images.githubusercontent.com/112373165/187139744-5c620b35-c3d6-450a-a4df-bd4175123a24.png)

## Expected Behavior
Clicking on a component inside an accordion item content will not collapse the accordion item.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chrisdholt** [comment]
This has been fixed in our vNext branches but a PR is here to cherry-pick into the current releases: https://github.com/microsoft/fast/pull/6332/files

@chroustak1 are you pulling the packages in via NPM or from CDN?

**Comment by chroustak1** [comment]
@chrisdholt - I'm using CDN (https://cdn.jsdelivr.net/npm/@@fluentui/web-components)

And thanks for super fast reply :)

**Comment by chrisdholt** [comment]
> @chrisdholt - I'm using CDN (https://cdn.jsdelivr.net/npm/@@fluentui/web-components)
> 
> And thanks for super fast reply :)

Thank you! I'll go ahead and force a package update and get it published out. This was fixed for our vNext implementation so a cherry-pick and update of the fast-foundation packages here will solve the issue. I'm going to try and get an additional fix in, but if it's not done by tomorrow we'll expedite this for you. Thanks!

**Comment by chrisdholt** [comment]
The PR containing this fix has been merged. A new version should be published and pushed to the CDN automatically tomorrow AM PST. Thanks!

**Comment by chroustak1** [comment]
New version is working flawlessly. Thank you.
