### ISSUE TITLE
[Bug]: Not able to clear search component value when using as controlled input

### ISSUE THREAD

**Issue by shashank2490** [microsoft/fluentui#24560]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 11.68 GB / 31.67 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/shashank2490/pen/KKojrbg

## Actual Behavior
When trying to reset the value of SearchBox, using it as a controlled component. I am not able to clear the value of searchbox. I tried to set it to empty string, null and undefined, but nothing worked

## Expected Behavior
The value of SearchBox should get cleared

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Dug into this more, and the key is that controlled inputs must start off with a defined value in order to be controlled (otherwise they will be assumed uncontrolled). This is as intended (i.e. changing it would probably cause more regressions than it fixes). 

So always start controlled inputs with a defined value.

**Comment by shashank2490** [comment]
But that is not case for dropdowns, textboxes and other controls. They can work with undefined values as controlled one. For searchbox, chances of it to start of with a value is way less than clearing it off either using state or some method. So, is it not possible to expose `Clear` function on component? Also even after you start off with a value setting it to null and undefined shows that in search box as value, which is also incorrect (You can check it with codepen link). Can you please look into this?

**Comment by micahgodbolt** [comment]
Couple things to unpack:
1. We believe that the current behavior for SearchBox is correct. If you start with an undefined value, you intend for the SearchBox to be uncontrolled, and that later switching to a defined value is a bad practice (as noted by the error in this [codepen](https://codepen.io/micahgodbolt/pen/poLMqdw?editors=0011))
2. TextField is an older class based control, not using our newer hooks. It does allow for this behavior, but as noted, it is a bad practice.
3. To have a 'clear' function for a component, simply start with a defined value (empty string) and on 'clear', return the input to a empty string
4. Null is not valid for 'value', only string or undefined (and undefined denotes uncontrolled input)

**Comment by shashank2490** [comment]
Thank you for the explanation and teaching one of the neglected practise

> Couple things to unpack:
> 
> 1. We believe that the current behavior for SearchBox is correct. If you start with an undefined value, you intend for the SearchBox to be uncontrolled, and that later switching to a defined value is a bad practice (as noted by the error in this [codepen](https://codepen.io/micahgodbolt/pen/poLMqdw?editors=0011))
> 2. TextField is an older class based control, not using our newer hooks. It does allow for this behavior, but as noted, it is a bad practice.
> 3. To have a 'clear' function for a component, simply start with a defined value (empty string) and on 'clear', return the input to a empty string
> 4. Null is not valid for 'value', only string or undefined (and undefined denotes uncontrolled input)
