### ISSUE TITLE
[Feature]: isHeaderSticky parameter for DetailsList

### ISSUE THREAD

**Issue by jillianpenfield** [microsoft/fluentui#24594]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

There is no seamless way to have DetailsList column headers stay in place on scroll. 

The recommended solution of a ScrollablePane wrapping the list, and onRenderDetailsHeader with Sticky components (https://github.com/microsoft/fluentui/issues/1146) places the list on an absolute position on the UI.

The recommended solution of styling on FluentUI's site (https://developer.microsoft.com/en-us/fluentui#/controls/web/scrollablepane) requires a specified height to be provided.

Both of these solutions are not ideal and require set positioning of the list whether in margin or height. With the first solution, I've run into issues with elements being covered up, and with the second I leave extra white space or create a double scroll bar. E.g. Our component has Error message bars that may arise that would change both the margin/height set of the list. Open to ideas on the best work around for this for now.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JustSlone** [comment]
routing this over to @spmonahan for thoughts on how to perhaps better work around or handle this issue. 

To set expectations, we have been making some fixes to details list lately, however, given its use and complexity major changes are not something we're able to take on generally
