### ISSUE TITLE
[Bug]: FluentUI v8 website bugs

### ISSUE THREAD

**Issue by IhnatKlimchuk** [microsoft/fluentui#24610]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

_No_

### Reproduction

https://developer.microsoft.com/en-us/fluentui

## Actual Behavior
1. Fabric Core icons preview is broken and icons are not visible.
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/12488585/187680893-c05168f1-d5b5-481a-a7e5-b410aa12230c.png">
2. Back to top is broken
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/12488585/187681020-33f006e4-46be-44a7-a2eb-2a43b19a7b1f.png">
<img width="854" alt="image" src="https://user-images.githubusercontent.com/12488585/187681080-f9bdb8d3-13ff-4069-a117-ee60d989d18f.png">
3. Icons are not working on https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot
<img width="638" alt="image" src="https://user-images.githubusercontent.com/12488585/187681499-182c1f6f-ee3a-410b-b8ba-44e2735e2de5.png">
4. Images are not loaded due to Content Security Policy violation. Example: https://developer.microsoft.com/en-us/fluentui#/controls/web/image
<img width="863" alt="image" src="https://user-images.githubusercontent.com/12488585/187682072-df703bbe-6059-4deb-b8e9-8f0ff0490fb3.png">

## Expected Behavior
1. Icons are visible
2. Button is working as expected
3. Check icon is displayed correctly 
4. Content Security Policy configured properly

### Logs

```shell
N/A
```

### Requested priority

Low

### Products/sites affected

https://developer.microsoft.com/en-us/fluentui

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
1. seems that the new fabric-core 11.0.1 did not get deployed to CDN properly. Will either get it deployed or roll back to 11.0.0 for the website
2. Due to our hash routing, we had code in place to change the behavior of that button, but the code assumed a specific ID was on the button....which it seems has been removed. I will update the selector.
3. checking
4. we are replacing hosted images with images from our own cdn

**Comment by micahgodbolt** [comment]
fabric core is updated and loading properly. CSP is fixed for images and videos.
