### ISSUE TITLE
[Bug]: Combobox/Select/Dropdown Teams High Contrast outline missing

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#24622]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/preview-components-select--default#appearance

## Actual Behavior

[Combobox](https://react.fluentui.dev/?path=/docs/preview-components-combobox--default#appearance), Dropdown and [Select](https://react.fluentui.dev/?path=/docs/preview-components-select--default#appearance) lack an outline for the filled darker/lighter appearances when using the Teams High Contrast Theme.

<img width="829" alt="combobox_appearance" src="https://user-images.githubusercontent.com/93940821/187775778-0302009e-4db0-4906-809d-ab4d09d44379.png">

## Expected Behavior

Combobox, Dropdown and Select should have a solid white outline when using the Teams High Contrast theme.
<img width="375" alt="combobox_dropdown_design_spec" src="https://user-images.githubusercontent.com/93940821/187776050-6e6ee5a3-7824-439b-903e-34bb2cb5d37a.png">

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by JustSlone** [comment]
setting medium priority
