### ISSUE TITLE
[Bug]: Fluent UI imports don't work with NextJS

### ISSUE THREAD

**Issue by Giuseppetm** [microsoft/fluentui#24636]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
### Packages version
"react": `17.0.2`
"next": `12.2.5`
"@fluentui/react": `8.30.1`,  (`8.90.1` that is the latest doesn't work either)
"typescript": `4.3.2`
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://github.com/StudentiUniMi/website/tree/feature/next_js

### Bug Description

This problem was already reported here:
https://github.com/microsoft/fluentui/issues/12464

Using NextJS with Fluent UI causes some issues about the imports of @fluentui/react components.
Additional info here: https://github.com/microsoft/fluentui/discussions/24497

The main errors are these:
> :warning: TypeError: Cannot read property 'semanticColors' of undefined
> :warning: TypeError: Cannot read property 'fonts' of undefined
> :warning: TypeError: Cannot read property 'disableGlobalClassNames' of undefined

The only workaround I found was using `office-ui-fabric-react/lib-commonjs/` to import the Fluent UI components, but this package is not updated and some components do not behave correctly.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. Please note, that all updates will be posted on the issue as progress is made.

**Comment by miroslavstastny** [comment]
Unfortunately your branch is not accessible.
The typescript version of `_document.tsx` and `_app.tsx` which you linked is for Fluent UI v7.

We definitely need to improve the documentation, the most up to date state of support (and `_document.tsx`) is described in: https://github.com/microsoft/fluentui/issues/11411#issuecomment-1024158756.

I followed the instructions in [wiki](https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing#nextjs-setup) and the Next application renders (complaining about id mismatch and icons as mentioned in https://github.com/microsoft/fluentui/issues/11411#issuecomment-1024158756).

```json
  "dependencies": {
    "@fluentui/react": "^8.98.0",
    "next": "12.3.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
```

Could you please provide us with repros (ideally codesandbox or minimal github repo) - I see there is another issue #24743 reported by you which includes repro - based on that I assume you managed to fix/workaround this issue?

**Comment by Giuseppetm** [comment]
I confirm that the import issues were due to a package using a ui-fabric library. By deleting this package (@uifabric/react-cards) and restoring the imports to @ fluentui/react there are no errors.
