### ISSUE TITLE
[Docs]: FocusZone to Tabster migration docs

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#24635]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

We need to be able to point customers to doc describing how to migrate from FocusZone (and FocusTrapZone) to Tabster. 

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JustSlone** [comment]
[backlog triage] 👍
