### ISSUE TITLE
chore(react-dialog): remove react-button max-width override

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/fluentui#24650]
# Current behaviour

`DialogActions` component provides an override using `.fui-Button` static class to ensure `max-width` of `Button` is not set.

https://github.com/microsoft/fluentui/blob/330aa6b960d371456667aae70cccbf116ed58cef/packages/react-components/react-dialog/src/components/DialogActions/useDialogActionsStyles.ts#L22-L24

# Change request

Remove override `max-width`

**Comment by bsunderhus** [comment]
Waiting for resolution of #24647

**Comment by micahgodbolt** [comment]
> Waiting for resolution of #24647

looks like you got your resolution
