### ISSUE TITLE
[Bug]: Opening a <Menu> inside an iframe causes parent window to scroll to top in certain conditions

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#24651]
### Library

React Components / v9 (@fluentui/react-components)

### Reproduction

https://codepen.io/radugroza/pen/ZExaLEw

## Actual Behavior
Opening a <Menu> inside an iframe causes parent window to scroll to top in certain conditions

This issues has been created from PR #24246

### Requested priority

Normal

### Products/sites affected

v9 docsite

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
As reported by @radugroza, the issue happens when a component is positioned using Floating UI and focused at the same time.
This affects not only `Menu` but other components as well - `Popover`, `MenuButton`.

The cause of the issue seems to be the following:
1. any component positioned by Floating UI is first rendered with `position: fixed; top: 0; left: 0`
2. focusable element inside that component is focused
3. correct position of the component is computed, its style is set to reflect the new position.

What happens is that in the step 2, the browser scrolls the focused element into view 🚨.

**In Chrome this only happens when the `iframe` has a cross-domain origin.** The scroll does not happen if it is the same-domain origin.

Repro sandbox: https://codesandbox.io/s/cross-domain-iframe-duot2s

**Comment by miroslavstastny** [comment]
This issue is not unique to v9, the same problem is in both v0 and v8.
Check this codesandbox for repro: https://codesandbox.io/s/v0-v8-docsite-iframe-umznbm - `Dialog` causes the scroll in both libraries, there are other components in both libraries which are experiencing the same problem.

**Comment by miroslavstastny** [comment]
cc @tudorpopams, @mshoho

**Comment by miroslavstastny** [comment]
Another observation: the scroll does not happen in **Anchor To Custom Target** `Menu` story where we set the `targetRef` imperatively.

**Comment by ling1726** [comment]
Thanks for the detailled findings @miroslavstastny !

**Comment by JustSlone** [comment]
[backlog triage]
sounds like we should keep looking to fix this, this might become a blocker due to use of iframes for embedding/sharing experiences. 
[removing needs: backlog review]

**Comment by kolaps33** [comment]
I recognized the same issue I can reproduce with the combobox:
https://stackblitz.com/edit/nbrsaz?file=src%2Fexample.tsx

When you open the combobox, then page is scrolled into top.
