### ISSUE TITLE
[Bug]: Pressing tab causes the focus to get lost in SwatchColorPicker

### ISSUE THREAD

**Issue by BabiShreema** [microsoft/fluentui#24653]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 4.25 GB / 15.73 GB
  Browsers:
    Edge: Spartan (44.22621.586.0), Chromium (105.0.1343.25)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://project.microsoft.com

## Actual Behavior
Pressing tab in SwtachColorPicker is causing the focus to get lost

## Expected Behavior
Pressing tab in Swatch Color Picker should keep the focus inside the SwatchColorPicker

### Requested priority

High

### Products/sites affected

https://project.microsoft.com

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
SwatchColorPickers are by default in a focus zone, so arrow keys move you around in the color selections. Therefore they are only 1 tab stop per picker.

**Comment by micahgodbolt** [comment]
You can turn off the focusZone by using the `doNotContainWithinFocusZone` prop
