### ISSUE TITLE
Rating component doesn't allow custom rendering of the stars

### ISSUE THREAD

**Issue by juanmad1** [microsoft/fluentui#24667]
### Discussed in https://github.com/microsoft/fluentui/discussions/24662

<div type='discussions-op-text'>

<sup>Originally posted by **juanmad1** September  5, 2022</sup>
When using the property "onRenderStar" the parameter "defaultRender" return undefined in all cases

![image](https://user-images.githubusercontent.com/33957888/188464586-0b5d53f6-43a8-4b6a-a0f9-61db62e590c9.png)
</div>

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [Rating ](https://developer.microsoft.com/en-us/fluentui#/controls/web/rating) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by juanmad1** [comment]
Yes, sorry [https://codepen.io/juanmad1/pen/BaxQOye](https://codepen.io/juanmad1/pen/BaxQOye)
