### ISSUE TITLE
[Feature]: opensource developer.microsoft.com/fluentui page

### ISSUE THREAD

**Issue by naughtyGitCat** [microsoft/fluentui#24687]
### Library

Web Components (@fluentui/web-components)

### Describe the feature that you would like added

the fluentui website `developer.microsoft.com/fluentui` may open source on the GitHub like the`https://github.com/angular/material.angular.io` to make an example to use fluentui to build a modern elegant website

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by naughtyGitCat** [comment]
@JustSlone thanks, never thought that would be hidden in the `fluentui/apps/public-docsite` path 🤣

**Comment by JustSlone** [comment]
@naughtyGitCat yeah that's a good idea, however, we're currently working on a revamp and brand new docsite. So I would wait until we release that next year to invite contribution. 

Thanks for the sugestion!
