### ISSUE TITLE
[Bug]: Cannot execute asynchronous code within the `onClick` event of a command bar item

### ISSUE THREAD

**Issue by TonyTroeff** [microsoft/fluentui#24711]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Memory: 6.33 GB / 31.77 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.22000.120
```

### Reproduction

I will append some screenshots

## Actual Behavior
I cannot use asynchronous functions for the `onClick` event of an `ICommandBarItemProps`:
![image](https://user-images.githubusercontent.com/33567383/189060118-bc659488-2299-4c28-9ca7-53c96c90ffcf.png)

As you can see - I receive an error: 
> TS2322: Type '() => Promise<void>' is not assignable to type '(ev?: MouseEvent<HTMLElement, MouseEvent> | KeyboardEvent<HTMLElement>, item?: IContextualMenuItem) => boolean | void'.   Type 'Promise<void>' is not assignable to type 'boolean | void'.     Type 'Promise<void>' is not assignable to type 'void'. 

## Expected Behavior
I want to use async functions for the `onClick` event.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [Commandbar ](https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
