### ISSUE TITLE
[Bug]: ContextualMenu's componentRef is not initialised anymore after v8.36.3

### ISSUE THREAD

**Issue by fildahui** [microsoft/fluentui#24716]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
  OS: Windows 10 10.0.19044
  CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
  Memory: 10.20 GB / 31.68 GB
Browsers:
  Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.27)
  Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/sleepy-hugle-29121h

## Actual Behavior
When using the `componentRef` prop it never gets initialised (always null).

## Expected Behavior
The `componentRef` prop should be initialised with the component instance (otherwise the prop should be removed)

## Additional info
We use the `DefaultButton` component and set its `menuProps` object to render a `ContextualMenu` component (like you similarly do with your examples here https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu). 
We were using v. **8.19.1** and recently updated it the its latest version and after that the `componentRef` to the `ContextualMenu` instance never held a value anymore (we used it to dismiss the menu clicking on a custom element). From what I could see the first version with the issue is v8.36.4 while v.8.36.3 still held the ref correctly.

You can have a look at both samples here:
**v8.36.4** sandbox --> https://codesandbox.io/s/sleepy-hugle-29121h
**v.8.36.3** sandbox --> https://codesandbox.io/s/admiring-panna-nmdj2l

The samples are the exact same of yours (Basic and Default ContextualMenu samples): you click on the button, the menu opens and then click on the "New" item. You can see in the console the ref being logged correctly for v8.36.3 (for both samples) while nothing is logged with v8.36.4 (ref is null for both).

I had a look at the code and the `ContextualMenu` component was refactored in version 8.36.4 when the `ContextualMenuInternal` class was removed which was where the `componentRef` was actually initialiased. However, that initialisation seems to happen nowhere in code now (and if that's the case maybe a solution like the `useComponentRef` of the `Checkbox.Base` component might work? otherwise it looks like a breaking change to me).

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
This issue has been queued for upcoming investigations. To set expectations the developers will review this issue once capacity allows and all updates will be posted on the issue accordingly.

**Comment by Hotell** [comment]
I was able to pinpoint the  issue  origin to this PR https://github.com/microsoft/fluentui/pull/19730.

Looks like that it is indeed a breaking change. A function component needs to be wrapped within `forwardRef` to be able to obtain it's DOM/instance reference. pinging author @MLoughry to shed some more light if this can be done or we should revert this PR. ty

**Comment by micahgodbolt** [comment]
@fildahui what are you using the componentRef for. Typically, they are used to access the public methods of a component. `IContextualMenu` is empty.
