### ISSUE TITLE
[Bug]: Coachmark's teaching bubble doesn't have a box-shadow

### ISSUE THREAD

**Issue by kehindeoni** [microsoft/fluentui#24723]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 65.38 GB / 127.71 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.49), ChromiumDev (105.0.1336.2)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

Repro in docs https://developer.microsoft.com/en-us/fluentui#/controls/web/coachmark#ICoachmark

## Actual Behavior
When the teaching bubble is rendered via a coachmark, there's no box-shadow on the teaching bubble whereas the stand alone teaching bubble component has a box-shadow

_Teaching Bubble via coachmark(no box-shadow)_
<img width="625" alt="image" src="https://user-images.githubusercontent.com/69808477/189167540-8c5c1f3c-5e93-477e-ab82-65315a5a732a.png">

_Standalone teaching bubble(box-shadow is present)_
<img width="613" alt="image" src="https://user-images.githubusercontent.com/69808477/189168091-8884bdeb-5075-4115-af30-d0ff30839244.png">

## Expected Behavior
Coachmark's teaching bubble should have a box-shadow.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
This issue has been queued for upcoming investigations. To set expectations the developers will review this issue once capacity allows and all updates will be posted on the issue accordingly. The developers will be able to confirm, if this was done by design at the time, or if its a regression, or if this behavior is an issue.

**Comment by miroslavstastny** [comment]
`TeachingBubble` is rendered inside a `CalloutContent` which adds the shadow to its `root`:
https://github.com/microsoft/fluentui/blob/d3b636814a611ec3b44c14d98f495445ac52e5bb/packages/react/src/components/Callout/CalloutContent.styles.ts#L53

On the other hand, `Coachmark` does not use `Callout`. I do not know if the missing shadow is a design decision or a bug.
The solution would be to add `boxShadow: theme.effects.elevation16` to the `entityHost`:
https://github.com/microsoft/fluentui/blob/3dbb57b1e6940df2d4039f61a35d961bcb8560c3/packages/react/src/components/Coachmark/Coachmark.styles.ts#L242-L260

**Comment by miroslavstastny** [comment]
The `enitityHost` applies to both collapsed and expanded coachmark:
![image](https://user-images.githubusercontent.com/9615899/195300298-1bde02de-e32c-4e07-bafc-6d5dbc8f93d5.png)
![image](https://user-images.githubusercontent.com/9615899/195300335-281ce77d-f937-4510-83bf-c25ad82ae21a.png)

If the desired behavior is to add the shadow only to the expanded bubble, it must be added to the `!isCollapsed` branch in the style function.

Codesandbox demonstrating the conditional style override: https://codesandbox.io/s/v8-coachmark-shadow-dbqffi?file=/src/App.tsx

Heads up @microsoft/cxe-red, @microsoft/cxe-coastal: This is currently blocking our partner. Unless the workaround works for them, we will need to handle this on library side ASAP.

**Comment by miroslavstastny** [comment]
> This is currently blocking our partner. Unless the workaround works for them, we will need to handle this on library side ASAP.

Partner has been unblocked by the workaround.

**Comment by kehindeoni** [comment]
Thanks @miroslavstastny for the workaround. I can confirm that it works, and I am now unblocked.
