### ISSUE TITLE
[Feature]: TextField should have an onBlur event.

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft/fluentui#24736]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

TextField should have an onBlur event.
When I use the parameters `(event: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>, newValue?: string)` 
the value of "newValue" is always undefined.

 

### Have you discussed this feature with our team

no

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gouttierre** [comment]
Thank you for filing this item with us. I'll add this to our contributors queue as it’s lower on our priority list for the upcoming quarter and we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items.
 
In the meantime, if you want to contribute towards this feature request, please share your PR and our dev team will review it.

**Comment by Ofer-Gal** [comment]
Thank you.
I have a work around for the time being.
