### ISSUE TITLE
[Bug]: Server-side rendered components and icons do not work properly

### ISSUE THREAD

**Issue by Giuseppetm** [microsoft/fluentui#24743]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 7.88 GB / 15.95 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

Reproduction is in the description of the issue

### Bug Description

(Tests made with NextJS `v12.2.5` and FluentUI `v.8.90.1` - - - Fluent UI `v.7.150.0` **didn't have** these problems!).

## Icons render issues description
**_On the first render_** of the application icons are not showed properly (just a little square instead of the icon): `initializeIcons` is already being used, but does not solve the problem. Looks like this is a problem related to some style properties missing.
- On _client-side render_ there is `root` className that defines a font-family and other properties that render the icon correctly.
- On _server-side render_ the icons are rendered with a `server-root` className that doesn't have the needed styles.

Changing manually the class name to `root-number` when an icon is not rendered correctly (server-side), it actually fixes the problem, but these class names are not static, so this is not a work-around.
 
| className | sample image |
|---|---|
| ![image](https://user-images.githubusercontent.com/52317197/188270740-f6a4428b-3756-4f5e-8f29-d56f97f7a9bf.png) |  ![image](https://user-images.githubusercontent.com/52317197/188270928-8a375050-f1e6-4336-b5ba-300ea30ea4f0.png) |
| ![image](https://user-images.githubusercontent.com/52317197/188270780-fbc6bdb9-60fe-4f1c-8af6-b77c1b9e42a4.png)  |  ![image](https://user-images.githubusercontent.com/52317197/188270946-b9f66493-9616-4eac-b526-c68b3646be87.png) |
 
 ----------
 
 ## Reproduction
[nextjs-fluentui-quickstart.zip](https://github.com/microsoft/fluentui/files/9535700/nextjs-fluentui-quickstart.zip)
 
 ## Additional informations
 Similar issues have been encountered with `AVATAR` and `CALLOUT` components (first render of application has several problems), and I presume there are a lot of other components with render problems. 
 
 As a workaround for my project (https://studentiunimi.it/) I registered some external Ant Design icons and fortunately I was able to use the icons; by forcing some client render I also fixed some styles that were not rendered correctly (texts, themes and more). 
 
 This is pretty serious as server-side-rendering is a technique that is used a lot.
 Can you investigate about global SSR problems with your library? Fluent UI `v.7.150.0` was working fine!
 Thank you!

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
This issue has been queued for upcoming investigations. To set expectations the developers will review this issue once capacity allows and all updates will be posted on the issue accordingly.

**Comment by miroslavstastny** [comment]
I checked the attached zip for repro - I see some version mismatches:
```json
  "dependencies": {
    "@fluentui/react": "^8.90.1",

    "@uifabric/merge-styles": "^7.19.1",
    "@uifabric/utilities": "^7.33.2",
    "office-ui-fabric-react": "^7.197.6",

    "react": "^17.0.1",
    "react-dom": "^16.14.0",
  },
```

You should not mix @fluentui/react (v8) and @uifabric (v7).
Also use the same version of react and react-com.

Basically, `@fluentui/react` should be the only Fluent UI package you import from.
Please try to align on the single Fluent version, use `_document.tsx` from https://github.com/microsoft/fluentui/issues/11411#issuecomment-1024158756 and share your findings.

**Comment by Giuseppetm** [comment]
> I checked the attached zip for repro - I see some version mismatches:
> 
> ```json
>   "dependencies": {
>     "@fluentui/react": "^8.90.1",
> 
>     "@uifabric/merge-styles": "^7.19.1",
>     "@uifabric/utilities": "^7.33.2",
>     "office-ui-fabric-react": "^7.197.6",
> 
>     "react": "^17.0.1",
>     "react-dom": "^16.14.0",
>   },
> ```
> 
> You should not mix @fluentui/react (v8) and @uifabric (v7). Also use the same version of react and react-dom.
> 
> Basically, `@fluentui/react` should be the only Fluent UI package you import from. Please try to align on the single Fluent version, use `_document.tsx` from [#11411 (comment)](https://github.com/microsoft/fluentui/issues/11411#issuecomment-1024158756) and share your findings.

I just tried to remove those dependencies and looks like it's fixed. Thank you very much.

I just have one question: [in my project](https://github.com/StudentiUniMi/website/blob/master/package.json) the problem was related to a `@uifabric/react-cards` import. Looks like this component is not available in `@fluentui/react` package.. how can I solve this? That card component is really important for my web app.

**Comment by miroslavstastny** [comment]
> I have one question: I think [in my project](https://github.com/StudentiUniMi/website/blob/master/package.json) the problem was related to a `@uifabric/react-cards` import. This component is not available in `@fluentui/react` package.. how can I solve this without using uifabric imports? That card component is really important for my web app.

`react-cards` is deprecated in v8 but still available - just change the dependency to `@fluentui/react-cards` and make sure you use latest version ([0.205.9](https://www.npmjs.com/package/@fluentui/react-cards/v/0.205.9) as of today).

Going forward, stable `Card` component will be part of Fluent UI v9.

**Comment by tudorpopams** [comment]
@Giuseppetm does @miroslavstastny 's answer help you solve this issue? If so, can we close this issue?

**Comment by Giuseppetm** [comment]
> @Giuseppetm does @miroslavstastny 's answer help you solve this issue? If so, can we close this issue?

He helped me troubleshoot the imports, but currently I still have issues with components not rendering properly. I'll update the issue as soon as I have some time to get back to it.

**Comment by tudorpopams** [comment]
Hello @Giuseppetm, let us know if you have any updates on this issue. Thanks!

**Comment by Giuseppetm** [comment]
At the moment I don't have time to investigate further on this issue I created. I will send an update about it in the future, thanks everyone for the help.
