### ISSUE TITLE
Rendering issue with SVG icons from @fluentui/react-icons-mdl2

### ISSUE THREAD

**Issue by daric81** [microsoft/fluentui#24740]
### Environment Information

- **Package version(s)**: @fluentui/react-icons-mdl2 v1.3.22 ; @fluentui/react v 8.94.3
- **Browser and OS versions**: Chrome/Edge / Win 10
- 
### Describe the issue:

I'm moving to use svg icons from @fluentui/react-icons-mdl2  from the fluent ui font based icons due to the need for MIT licence .
I've imported the icons needed and registered them. The issue I'm seeing is that the svg set do not render quite the same.

#### Actual behavior:

Most noticeably the icons sit vertically lower the the font equivalent. I'm not sure if I'm using them incorrectly, if this is a bug , or if its up to the me to override some styling to get back to the look of the font based icon set.   

#### Expected behavior:

Id expected there to be no visual or alignment differences between the font and svg icons.

see codesandbox

https://codesandbox.io/s/quizzical-babycat-ryjm14?file=/index.tsx

looks like changing SvgIcon.scss  so the .root selector has line-height:1em and vertical-align:unset corrects layout (for the components i use).

**Comment by gouttierre** [comment]
This issue has been queued for upcoming investigations. To set expectations the developers will review this issue once capacity allows and all updates will be posted on the issue accordingly.

**Comment by tomi-msft** [comment]
Hi @daric81, thanks for filing the issue. With the svg icons in `react-icons-mdl2`, there is some default styling from `SvgIcon.scss`, as you've noticed, so there will be some alignment differences between the two. You should be able to override the styling and get to visual parity.

**Comment by miroslavstastny** [comment]
Thanks @tomi-msft for answering this. Is there any work planned here or can we close the issue?

**Comment by tomi-msft** [comment]
As we are focused on converging v9 components, there is no work planned to modify the icons in `react-icons-mdl2`, You should be able to override the styling to fix any alignment issues from the default styling. I will close the issue now.
