### ISSUE TITLE
[Bug]: Minified React error #321 thrown from @fluentui/utilities/lib/styled.js 10:21 (version: 8.6.0)

### ISSUE THREAD

**Issue by PaulQinMSFT** [microsoft/fluentui#24779]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (40) x64 Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
    Memory: 33.63 GB / 63.63 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

just a generic error message

### Bug Description

We have not figured out how to repro this issue, but from logging we get from real customers in production environment, we are seeing this error as below, and our app is broken by this error.
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### Logs

```shell
The error stack is like this:
Error webpack://../node_modules/react-dom/cjs/react-dom.production.min.js 152:114 
useRef webpack://../node_modules/react/cjs/react.production.min.js 25:229
null webpack://../node_modules/@fluentui/utilities/lib/styled.js 10:21
c webpack://../node_modules/react-dom/cjs/react-dom.production.min.js 153:145
oh webpack://../node_modules/react-dom/cjs/react-dom.production.min.js 173:191
Zh webpack://../node_modules/react-dom/cjs/react-dom.production.min.js 265:424
Rj webpack://../node_modules/react-dom/cjs/react-dom.production.min.js 246:264
Qj webpack://../node_modules/react-dom/cjs/react-dom.production.min.js 246:193
Kj webpack://../node_modules/react-dom/cjs/react-dom.production.min.js 239:171
c webpack://../node_modules/react-dom/cjs/react-dom.production.min.js 123:114
    in StyledToggleBase
    in div
    in t
    in t
    in div
    in t
    in t
    in div
    in t
    in t
    in t
    in div
    in t
    in Connect(t)
    in div
    in div
    in t
    in t
    in div
    in div
    in yt
    in t
    in Connect(t)
    in Unknown
    in Connect(Component)
    in n
```

### Requested priority

Blocking

### Products/sites affected

Office Search Pane

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by PaulQinMSFT** [comment]
Looks like this issue can happen on any fluent controls, in our case, we are seeing this error from below places:
StyledToggleBase
Styledt
StyledFabricBase
StyledCheckboxBase

**Comment by khmakoto** [comment]
We resolved this issue offline. Our main suspicion was that there were multiple copies of React being loaded. The following suggestion was made to help debug if that was the case:

```js
// Add this in node_modules/react-dom/index.js
window.React1 = require('react');

// Add this in your component file
require('react-dom');
window.React2 = require('react');
console.log(window.React1 === window.React2);
```

After digging into some logs of a session that hit the problem it seemed that the culprit was the JS file being loaded twice, which caused the React mismatch copies problem mentioned above. The fix made then was to prevent JS from being loaded more than once.

**Comment by AmonHouston** [comment]
I think this might be occurring for us now as well. 

We have 3 SPFx components run into this issue across 3 different tenants when they were all working fine previously. 

SPFx version - 1.12.1 
Fluent UI version - 8.14.3

**Comment by khmakoto** [comment]
@AmonHouston would you mind opening another bug with those versions and the error log you're getting in the description of the issue?

**Comment by AmonHouston** [comment]
@khmakoto Actually I was able to resolve the issue today (sleeping on a problem works!) 

I replaced my SPFx component from referencing '@microsoft/office-ui-fabric-react-bundle' to instead use '@fluentui/react' for the same components.

**Comment by sparky742** [comment]
> @khmakoto Actually I was able to resolve the issue today (sleeping on a problem works!)
> 
> I replaced my SPFx component from referencing '@microsoft/office-ui-fabric-react-bundle' to instead use '@fluentui/react' for the same components.

This worked for my SPFx component also.  Thanks for posting.
