### ISSUE TITLE
[Bug]: Tooltip not dismissing on scroll

### ISSUE THREAD

**Issue by nayancprakash** [microsoft/fluentui#24781]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 105.96 GB / 127.71 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.33)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/nayancprakash/pen/LYmbVeV

## Actual Behavior
After hovering a Tooltip, the Tooltip content will show. Upon scrolling (without moving the mouse) the Tooltip will continue to show (despite the `onDismiss()` callback firing for each scroll event).

## Expected Behavior
After hovering a Tooltip, the Tooltip content will show. Upon scrolling (without moving the mouse) the Tooltip should dismiss.

### Requested priority

Low

### Products/sites affected

Products/sites affected: (if applicable) Any FluentUI consumer that hosts Tooltips. In my use case this affects Microsoft Loop

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thank you for filing this issue with us and sharing the repro steps. This issue has been queued for upcoming investigations to determine if the behavior is an issue, or a regression, or if it was by design at the time. To set expectations the developers will review this issue once capacity allows and all updates will be posted on the issue accordingly. We are delighted to see that you are willing to contribute to the reported issue, as soon as the developer has determined the outcome they will guide you the suggested fix for a PR submissions.

**Comment by miroslavstastny** [comment]
**Workaround**
Do not pass `tooltipProps.calloutProps` to the `TooltipHost` as it breaks internal components logic.
If you need to pass `calloutProps` to the tooltip, pass them directly to the `TooltipHost` (beware: the component will overwrite `onDismiss`, `onMouseEnter` and `onMouseLeave` which you pass in the `calloutProps`)

**Details**
In the shared example, you are passing the `calloutProps` as follows:
```jsx
<TooltipHost
    tooltipProps={{
        calloutProps: {onDismiss: () => {console.log("onDismiss() called")}}
    }}
    ...
>
```

When `tooltipProps` is passed to `TooltipHost`, it is forwarded to the `Tooltip` (line 116 in the code bellow) overwriting `calloutProps` (lines 108 - 112) created by the `TooltipHost` component (which include event handlers used to dismiss the tooltip).

https://github.com/microsoft/fluentui/blob/70c03a62a18accc5a1903d89e4625600796d09e9/packages/react/src/components/Tooltip/TooltipHost.base.tsx#L102-L117

**Comment by khmakoto** [comment]
Hey @nayancprakash, did the workaround above work for you?
