### ISSUE TITLE
[Bug]: long text in Button overflows (height)

### ISSUE THREAD

**Issue by slorlior** [microsoft/fluentui#24791]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 63.52 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 105.0.5195.102
    Safari: 15.6.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/slorlior/pen/zYjoWpB

## Actual Behavior
when the Button component is given a long text and the button is inside a small div (or when the screen is small) the text is overflow up and down outside the button
![image](https://user-images.githubusercontent.com/22429172/190179830-b28670b5-da00-46a7-8837-b3e46ec5750f.png)

## Expected Behavior
the text should be ellipsis (with a tooltip) when there is no place for it in the button
![image](https://user-images.githubusercontent.com/22429172/190183192-acbd2642-2f27-4e65-a166-e297a02b9860.png)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chetan-d-mahajan** [comment]
We too have been facing this issue with <PrimaryButton> component

![image](https://user-images.githubusercontent.com/26963448/204451496-ab562df9-4a44-46aa-8e89-40b0801729e8.png)

office-ui-fabric-react : 7.174.1

**Comment by TristanWatanabe** [comment]
The v8 `Button` styles all have a fixed height (see example below). This issue can be fixed by replacing the `height` property with a `minHeight` property instead.

https://github.com/microsoft/fluentui/blob/9f8fe44d75df0294762fa6f949126e501b6f79a8/packages/react/src/components/Button/DefaultButton/DefaultButton.styles.ts#L18-L21

**Comment by powerchelle** [comment]
@TristanWatanabe good call, seems like a low-cost fix. Is "Help Wanted" an invitation to consumers/co-developers to contribute the fix back to FluentUI?

**Comment by khmakoto** [comment]
Hi @powerchelle, yes, help wanted is an invitation to contribute a fix back. If you send a PR with the fix I'd be more than happy to review it.
