### ISSUE TITLE
[Bug]: `ssr-tests-v9` build fails on Windows

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#24798]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 15.12 GB / 31.59 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.33), ChromiumDev (107.0.1379.1)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

On Windows (not WSL) run `yarn workspace @fluentui/ssr-tests-v9 build`

## Actual Behavior

Running `yarn workspace @fluentui/ssr-tests-v9 build` fails on Windows (I'm using Powershell but anything that's not WSL will fail).

Example error:

```shell
✘ [ERROR] Could not resolve "......packages\react-components\react-dialogsrcstoriesDialogDialogCustomTrigger.stories"

    dist/stories.tsx:138:53:
      138 │ ...CustomTrigger as DialogCustomTrigger } from "......packages\react-components\react-dialogsrcstoriesDialogDialogCustomTrigger.stories";
          ╵                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path
  "......packages\react-components\react-dialogsrcstoriesDialogDialogCustomTrigger.stories" as
  external to exclude it from the bundle, which will remove this error.
```

Examining the `dist/stories.tsx` file that is built shows imports like this:

```tsx
import { Default as AccordionDefault } from "......packages\react-components\react-accordionsrcstoriesAccordionAccordionDefault.stories";
```

This looks to be from this line in [`getImportsFromIndexFile.ts`](https://github.com/microsoft/fluentui/blob/master/apps/ssr-tests-v9/src/utils/getImportsFromIndexFile.ts#L68) that uses a file system path for the import path:

```ts
path: path.relative(distDir, path.resolve(path.dirname(filename), sourcePath.node.value)),
```

Using Node's [path.posix](https://nodejs.org/api/path.html#pathposix) might be the way to go here but in my (admittedly simple) test `posix` includes the Windows drive letter in the path (e.g., "C:/the/path").

## Expected Behavior

`ssr-tests-v9` can be built and run on Windows.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
I'd say it's normal/medium priority. It's not a hard blocker but it does make it impossible to run a full build on Windows which I discovered when helping a partner with a build issue.

**Comment by JustSlone** [comment]
@spmonahan what version of node were you running on? 14 or 16? I'm guessing 14, and this might be the fix https://github.com/nodejs/node/pull/37747 which looks to have landed in 15/16.

**Comment by spmonahan** [comment]
I'm using Node 16.17.1. I verified that the issue is present for this version by re-installing all node_modules then attempting to build. Issue repros as in the details above.

**Comment by JustSlone** [comment]
> I'm using Node 16.17.1. I verified that the issue is present for this version by re-installing all node_modules then attempting to build. Issue repros as in the details above.

😭

We need to fix this or make clear we don't support command prompt / PowerShell as a development environment (I'm willing to consider this given the popularity, quality, and ease of us of WSL). I would love to fix this, but we have to prioritize.
