### ISSUE TITLE
[Bug]: v9 components do not render with style\theme on v8 surface components

### ISSUE THREAD

**Issue by sgbdev** [microsoft/fluentui#24816]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 10.21 GB / 31.82 GB
  Browsers:
    Chrome: 105.0.5195.102

  npmPackages:
    @fluentui/react: 8.94.4
    @fluentui/react-components: 9.2.0
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/fluentui-v9-theming-v8-surfaces-ttkq1x?file=/src/App.js

## Actual Behavior
When attempting to render a FluentUI v9 component (like a Button), on a FluentUI v8 surface (Callout, Dialog, Panel, Modal), the v9 component renders without styles or theming. In the example provided, make sure the switches for "Use ApplyToBody" and "Use Layer Props" are set to No, and then click any of the example buttons on the right, to open the related v8 surface component. You'll notice the the v8 buttons display with the custom theme, while the v9 buttons do not (see the image below).
![image](https://user-images.githubusercontent.com/34309778/190436605-47279312-39e2-46b3-b85d-369cab8ef2b2.png)

## Expected Behavior
I would expect the v9 buttons\components to render with styles and theming applied, just like the v8 components.

## Additional Observations
There are other issues\feature requests that have been documented, while different, contain comments with potential workarounds for this issue ( see [23626](https://github.com/microsoft/fluentui/issues/23626#issuecomment-1162255474) and [21290](https://github.com/microsoft/fluentui/issues/21290#issuecomment-1014740279)). Although, its not clear which solution is ideal. It would be great if this could be fixed with an out of the box solution. But, if that is not possible, then would you be able to clarify which of workaround you recommend?

### Apply To Body
When setting the "Use ApplyToBody" switch to Yes - the useEffect method that exists in that function calls useThemeClassName, and will apply those classes to the body element. The v9 component will render properly at this point. This is the easiest solution, but its drawbacks are document [here ](https://github.com/microsoft/fluentui/issues/23626#issuecomment-1162255474).

### v8 layerProps
When setting the "Use Layer Props" switch to Yes - the v8 surface components will target an element that is a child of the root FluentProvider. The v9 component will render properly at this point. This solution has its pro's and con's, depending on the implementation of Callout, Dialog, Panel, and Modal. If used within a wrapper component, then its just a matter of updating code in a few locations to implement this. If not, this could be a cumbersome solution, as it would require touching all instances of these components in an app. 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Hey @sgbdev, thanks for reaching us and the detailed demo 👍 

This problem is known and caused by missing CSS variables on portals created by `@fluentui/react`/`@fluentui/react-northstar`. However, this is solved by a package called [@fluentui/react-portal-compat](https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-portal-compat). Add `PortalCompatProvider` as an inner child of `FluentProvider` and it will work 😉 

```tsx
import { FluentProvider } from '@fluentui/react-components';
import { PortalCompatProvider } from '@fluentui/react-portal-compat';

function App() {
  return (
    <FluentProvider>
      <PortalCompatProvider>{/* your components */}</PortalCompatProvider>
    </FluentProvider>
  );
}
```

https://codesandbox.io/s/fluentui-v9-theming-v8-surfaces-forked-umthe4?file=/src/index.js

---

Do you have any suggestions where we can put this in documentation to make it more discoverable? 🤔

**Comment by sgbdev** [comment]
This is exactly what I was looking for! Thank you so much! 

Regarding discoverability in the documentation.
1. A dedicated page in the Components group, or perhaps in another group called Utilities (similar to the v8 docs).
2. Maybe add a note to the [Theming](https://react.fluentui.dev/?path=/docs/components-portal--default) page, in the **How theme is applied** section. Not sure if that's what the intention is with the current link to the Portal component. But, that link does not lead anywhere. 
3. Perhaps adding another example on the **FluentProvider** component page , with a note explaining its applicability if using existing `@fluentui/react` and `@fluentui/react-northstar` libraries. This is where I initially went to see if there was a solution.
4. It may also be worth mentioning on the [Troubleshooting](https://react.fluentui.dev/?path=/docs/concepts-migration-from-v8-troubleshooting--page) or [Theme Migration](https://react.fluentui.dev/?path=/docs/concepts-migration-from-v8-components-theme-migration--page) pages.

**Comment by layershifter** [comment]
@sgbdev Thanks for feedback, I pushed few changes in #24951 👍
