### ISSUE TITLE
[Bug]: Links inside tooltip don't work after click

### ISSUE THREAD

**Issue by asafcohenms** [microsoft/fluentui#24845]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Hi,

When we put a link, either an <a> element or <Link> it doesn't always work. It doesn't respond to both onclick and href. I found it is always reproducible when I click the info icon to open the tooltip or just click somewhere on the tooltip. After I make this "click", the link is not working, and the tooltip is closed.

We use the following:
        "@fluentui/azure-themes": "^8.1.129",
        "@fluentui/react": "7.170.3",
        "@fluentui/react-hooks": "^8.2.6",
        "@fluentui/react-theme-provider": "^0.18.5",
        "@microsoft/azureportal-reactview": "^1.67.1"

I have seen some older posts about this in the last 2-3 years, but they were closed.
```

### Are you reporting Accessibility issue?

no

### Reproduction

Able to reproduce:
1. Create a tooltiphost 
2. Add link to the tooltip host
3. Open the tooltip
4. Click on it somewhere else than the link
5. Click on the link
6. Link is not working

## Actual Behavior
Link inside tooltip host should work with href or with onclick

## Expected Behavior
Link is not working in all scenarios, in some cases as mentioned above onclick is not triggered and link is not working

### Logs

```shell
-
```

### Requested priority

High

### Products/sites affected

Sentinel

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
@asafcohenms thanks for filing this issue! Could you add a codepen or codesandbox repro so I can take a look at what's happening?
