### ISSUE TITLE
[Bug]: Panel header is not sticky when zoom level exceeds threshold

### ISSUE THREAD

**Issue by JensMadsen** [microsoft/fluentui#24863]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
I use "@fluentui/react": "8.90.0"
```

### Reproduction

https://codepen.io/jensmadsen/pen/YzLQrza

## Actual Behavior
When zoom level in Chrome browser (only tested browser) is too high, the header of the panel is no longer sticky. 

https://user-images.githubusercontent.com/6726111/191256714-102f9963-f362-4afb-8cc6-c0e63a36a99c.mp4

## Expected Behavior
Panel header should be sticky; only scrollbars on content. 

### Requested priority

Normal

### Products/sites affected

Karnov Link - Office add-in

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
This is by design to adhere to [WCAG 2.1 Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) requirements.
