### ISSUE TITLE
[Bug]: Icon/Label Dropdown with long names are overflown

### ISSUE THREAD

**Issue by antrianis** [microsoft/fluentui#24861]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 32.52 GB / 63.62 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.42), ChromiumDev (107.0.1379.1)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/andr33/pen/eYrRWKR

## Actual Behavior
The text overflows in the label when using an icon. Both for the selected item and the rest of the dropdown items. 
![image](https://user-images.githubusercontent.com/1173258/191230296-26cd59f3-afdc-4548-a2c4-aee96a7d5681.png)
![image](https://user-images.githubusercontent.com/1173258/191230884-dcfd3375-3fd2-4a17-aaea-b9cf23ee5e6d.png)

## Expected Behavior
The text should be cropped by default or allow access to the text label in order to allow wrapping options by the user. Similar to the dropdown without icon which by default it crops the text: https://codepen.io/avenezia/pen/abLGbKp

### Requested priority

High

### Products/sites affected

Power Query

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
changing the dropdownItem height to "auto" will allow the buttons to grow as large as they need.
