### ISSUE TITLE
[Bug]: ignoreExternalFocusing prop on Dialog is not being honored and focusing of the previously element is still in effect

### ISSUE THREAD

**Issue by Zeddox** [microsoft/fluentui#24874]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Xeon(R) W-11955M CPU @ 2.60GHz
    Memory: 32.06 GB / 63.67 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codepen.io/zeddox/pen/dyeRayZ

## Actual Behavior
With the `ignoreExternalFocusing` set to true, the previously focused element is refocused when the `Dialog` is dismissed

## Expected Behavior
With the `ignoreExternalFocusing` set to true, the previously focused element is _not_ refocused when the `Dialog` is dismissed and the `modalProps.onDismissed` can be used to focus elsewhere.

### Requested priority

Blocking

### Products/sites affected

Internal Microsoft application

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Zeddox** [comment]
This functionality was previously working, but with the update to a functional component version of `Popup`, the `useRestoreFocus` hook does not check the `ignoreExternalFocusing` prop (looks like it was [previously](https://github.com/microsoft/fluentui/commit/1e626b101db22df0f12bf04f42be6e94c1c5fdcb#diff-1fa24f0746dd8fbae5b9a624a59cdfcb699f19bca36d8772a30210c563ecddd2) a `shouldRestoreFocus` prop).

Previous issue for reference: [18564](https://github.com/microsoft/fluentui/issues/18564)

**Comment by Abe-Froman** [comment]
@gouttierre @ling1726 @ecraig12345 for visibility

**Comment by TristanWatanabe** [comment]
Issue still persists in latest version of v8. Seems to stem from `Popup` not accounting for the `shouldRestoreFocus` prop. Adding a condition to only restore focus if `shouldRestoreFocus` is true will probably fix this.

https://github.com/microsoft/fluentui/blob/3916d4647dcc180d4ea4c30b296b0866e6315d69/packages/react/src/components/Popup/Popup.tsx#L81-L90
