### ISSUE TITLE
[Bug]: Placeholder text is not shown completely

### ISSUE THREAD

**Issue by Jing29** [microsoft/fluentui#24882]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Not related
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/lijinglin29/pen/LYmjYdo?editors=1010

## Actual Behavior
The placeholder text can't be shown completely without any title when the length of the text is larger than the width of input box

## Expected Behavior
Use the title or tooltip to show placeholder info

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
Hi @Jing29, you can do that today with both the our `Tooltip` and the `title` prop as can be seen [in this codepen](https://codepen.io/khmakoto/pen/wvXxrBz). Let me know if I can help you in any other way.
