### ISSUE TITLE
[Bug]: Layers will receive a margin when inside a Stack, leading to white gaps

### ISSUE THREAD

**Issue by alex3683** [microsoft/fluentui#24907]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 9.11 GB / 31.73 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/alex3683/pen/eYrExNm

## Actual Behavior
MsLayer components are positioned absolutely outside of the DOM tree they are inserted in. However, when part of a Stack for example, they will still receive the `margin-top` they are assigned by the `childrenGap` property. This leads to awkward results and hence in complicated code to move the layer outside of the stack. In the example a Callout is used for demonstration.

## Expected Behavior
Layers (i.e. `.ms-layer`) is excluded when setting the `margin-top` caused by the Stack `childrenGap`. Or more explicitily the margins of an .ms-layer could be set to 0 explicitly.
hard example:
```css
.ms-layer {
    margin: 0 0 !important;
}
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
Hi @alex3683, this is known behavior that is unfortunately kind of breaking to remove. However, we do have an `enableScopedSelectors` prop that you can pass to the `Stack` that should fix this behavior (bonus is that you should get a nice style recalculation performance boost by using it). You can see how that fixes the issue in [this modified codepen](https://codepen.io/khmakoto/pen/KKeBvKp). Let me know if that fixes the issue for you and if I can help with anything else.

**Comment by alex3683** [comment]
Hi @khmakoto 
I can totally understand that this changes behavior and hence can be considered breaking. Although I could not understand, that someone wants to have this behavior ;-)
Nevertheless, your workaround works well and thus it's fine in my case. Thanks!
