### ISSUE TITLE
[Bug]: (Callout) - Does not revaluate position after width and height modifications

### ISSUE THREAD

**Issue by dkozar** [microsoft/fluentui#24912]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

No

### Reproduction

Repro: https://codesandbox.io/s/withered-shadow-kxgmj?file=/src/App.js

### Bug Description

_Recreated https://github.com/microsoft/fluentui/issues/18839_

When the component is initially rendered it correctly adjusts its position to best fit the screen.

![image](https://user-images.githubusercontent.com/7192338/124684568-4d5e3100-de84-11eb-8109-14b48245f1fb.png)

However, upon changing width or height, its position does not update creating various visual bugs. 

![image](https://user-images.githubusercontent.com/7192338/124684572-50592180-de84-11eb-99e5-73c6ec2c110f.png)

## Actual behavior:

When `Callout` is resized the position is initially detected but then becomes clipped by the screen edge upon size modification.

## Expected behavior:

When `Callout` is resized:
1. The position should detect whether it is being clipped by the screen edge.
2. It should change its position the same as it does upon initial render.

### Logs

N/A

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
I ported your CodeSandbox to latest Fluent (https://codesandbox.io/s/priceless-meninsky-rfnrhf?file=/src/App.js) and updated to make the problem more visible:

![image](https://user-images.githubusercontent.com/14183168/215503349-400ac627-30bd-4ab6-9b8e-7957f3009a00.png)

> Top-right corner of the callout seems to be static, never changing its position. What I would expect to see instead is the callout moving to the right, since there's enough space on the screen to accommodate its size.
> https://github.com/microsoft/fluentui/pull/18887#issuecomment-891748483


---

@dkozar you may consider to use v9 components that have more advanced positioning logic, https://codesandbox.io/s/amazing-sun-309lfn?file=/src/App.js.

**Comment by marielsgtzz** [comment]
This is still happening on `8.85.1`, when the height change happens, the callout is actually repositioned to the bottom of the page
