### ISSUE TITLE
After applying high contrast theme, after selecting the row of the table, the controls (Link) are not clearly visible

### ISSUE THREAD

**Issue by v-vbhanndari** [microsoft/fluentui#24922]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 998.69 MB / 15.85 GB
  Browsers:
    Edge: Spartan (44.22621.521.0), Chromium (105.0.1343.50)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

[NA](https://user-images.githubusercontent.com/114223231/213633701-c92d0a0c-19aa-497f-8486-bd32bc9ec9cb.mp4)

## Actual Behavior
After applying high contrast (Aquatic/Desert) theme, after selecting the row of the table, the controls (Link) are not clearly visible.

## Expected Behavior
After applying high contrast (Aquatic/Desert) theme, after selecting the row of the table, the controls  (Link) should be clearly visible.
![Screenshot 2022-09-23 145322](https://user-images.githubusercontent.com/114223231/191930841-9741e62f-4287-4002-8ca5-b7276f4dbef6.png)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@v-vbhanndari I'm unable to repro this on the latest version of v8. If this is still an issue, please provide a repro example and we'll take a look again.

**Comment by v-vbhanndari** [comment]
Hey @TristanWatanabe , 

I have attached the video in which the issue is reproducible.  

https://user-images.githubusercontent.com/114223231/213633701-c92d0a0c-19aa-497f-8486-bd32bc9ec9cb.mp4


Thanks,
Vipin
