### ISSUE TITLE
[Bug]: Breadcrumb - When using long text, only "..." is displayed

### ISSUE THREAD

**Issue by Toniotoniotonio** [microsoft/fluentui#24938]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 2.37 GB / 7.94 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.50)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codepen.io/toniotoniotonio/pen/ZEoapKR

## Actual Behavior

I took the example "Breadcrumb rendering options" from [FluentUI breadcrumb examples](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/breadcrumb).
I replaced a "Folder 5" by a very long text, and only "..." are displayed (we don't see anymore the text of the other folders).
![image](https://user-images.githubusercontent.com/58749055/192131529-2127d8a6-beb5-44a7-be98-064978712c1c.png)

https://codepen.io/toniotoniotonio/pen/ZEoapK

 ## Expected Behavior

At least one item should be displayed even if it is truncated.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
Can confirm repro of issue but issue only repros in a specific case where the `item` with a very long text is the last item in the `items` list. When there are other items after the one with long text, the `Breadcrumb` renders those items after the overflow icon as expected.
