### ISSUE TITLE
Implement column management features

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#24965]
* Column resizing
* Column reordering

Prototype already implemented in https://github.com/microsoft/fluentui/pull/24944 and #25238

The feature should also be supported by the `DataGrid` component

**Comment by martinoss** [comment]
I would like to migrate V8 DetailsList to V9 DataGrid, but configurable column width is an important missing feature. Thanks for looking into this. Text ellipsis also seems to be missing. A filename with no spaces will not be wrapped nor shortened at the moment.

**Comment by george-cz** [comment]
@martinoss I've implemented the column resizing to Table component, currently its in preview and I'll be adding this functionality to DataGrid shortly ([PR](https://github.com/microsoft/fluentui/pull/26690/files) is now open). 

Regarding the text ellipsis, I believe this should not be handled by the table component itself, but rather the consumer of it, similarly to example here (resize first column): 

https://codesandbox.io/s/recursing-currying-16xpn9?file=/example.tsx

I'll explore this use on DataGrid too to make sure it works properly and discuss if (and how) we should implement it to DataGrid with the team :)

**Comment by george-cz** [comment]
I'll close this one in favor of #26733 and #26734, to simplify tracking of this.

**Comment by george-cz** [comment]
@martinoss Hello, we have just released v 9.15.0, which introduces a `truncate` property on `TableCellLayout`

https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-components/CHANGELOG.md

Please let me know if you run into any issues with this. Thanks!

**Comment by martinoss** [comment]
@george-cz Just updated our project, the new features are working great, thank you ❤
