### ISSUE TITLE
[Bug]: [Accessibility][Dropdown] Keyboard focus is moving out of dropdown when we navigate using tab key

### ISSUE THREAD

**Issue by ranjanbinwani** [microsoft/fluentui#24961]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22622
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 1.99 GB / 15.78 GB
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.22621.590.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/ranjanbinwani/pen/MWGrEjz
Video: https://user-images.githubusercontent.com/25248881/192484110-26314ea4-876a-48c9-bce4-9937851976d1.mp4

## Repro Steps:
Launch URL: https://codepen.io/ranjanbinwani/pen/MWGrEjz
Tab navigate to "Basic uncontrolled example" and expand it.
Tab navigate to "Multi-select uncontrolled example" dropdown and observe that Keyboard focus is moving out of dropdown when we navigate using tab key.

## Actual Behavior

Keyboard focus is moving out of dropdown when we navigate using tab key.

## Expected Behavior

Keyboard focus should not move out of dropdown when we navigate using tab key.

## User Impact:
Keyboard users will face difficulty if the keyboard focus moves out of dropdown.

## MAS Reference:
https://www.w3.org/TR/WCAG21/#keyboard

### Requested priority

Normal

### Products/sites affected

Office Online

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by narinderparmar** [comment]
I think it's not a bug, normal behaviour.
when you tab you switch between controls , use up and down key that is normal behaviour.
