### ISSUE TITLE
[Bug]: ScrollablePane and Sticky do not work consistently when running with hot reload

### ISSUE THREAD

**Issue by Kerryliu** [microsoft/fluentui#24987]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 12.05 GB / 31.91 GB
  Browsers:
    Edge: Spartan (44.22621.521.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.22621.1
```

### Reproduction

https://github.com/Kerryliu/Test123

## Steps to reproduce
- Create a new react project with https://create-react-app.dev/docs/getting-started
- Install fluentUI with yarn: ` yarn add @fluentui/react`
- `yarn start` with code in the codepen.  
- Sticky isn't sticking.  (sometimes tweaking the style in the div breaks/fixes, and I don't know why)

## Actual Behavior
- Sticky should stick but doesn't.  This only occurs when running with `yarn start`.  
- Unable to reproduce when serving a prod build (`yarn build` + `yarn serve`).  
- Unable to reproduce issue in codepen.  (https://codepen.io/berrykerry789/pen/RwyQwax)
- Might be specific to React 18, which I know isn't officially supported. Seems to work fine with React 17.  

## Expected Behavior
- Sticky should stick regardless of running with a dev build or prod build.  

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
This looks like an issue with StrictMode in React 18:
- with `StrictMode` https://codesandbox.io/s/spring-shape-r2ylp8?file=/src/App.js 💥 
- without `StrictMode` https://codesandbox.io/s/spring-shape-r2ylp8?file=/src/index.js ✅
