### ISSUE TITLE
[Bug]: Modal close icon (x) should be placed on the left for RTL 

### ISSUE THREAD

**Issue by hyungkwon** [microsoft/fluentui#24984]
### Library

@fluentui/react": "8.36.3",

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 49.94 GB / 63.84 GB
  Browsers:
    Edge: Spartan (44.22621.521.0), Chromium (105.0.1343.53)
    Internet Explorer: 11.0.22621.1
```

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/modal

## Actual Behavior
Set rtl direction first: document.body.setAttribute('dir', 'rtl')
As you can see the title is place on the right which is correct, but the close icon should be rendered on the left.

<img width="919" alt="image" src="https://user-images.githubusercontent.com/3250446/192656175-a2317e08-a5d4-4788-a1d4-62a6c4709c94.png">

## Expected Behavior
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/3250446/192657360-f98c9799-5cba-4a42-bb3a-45d48455414a.png">

### Requested priority

Normal

### Products/sites affected

mydefender.microsoft.com

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chrisdholt** [comment]
This is not the web components documentation - please provide a specific repro using that package rather than the site listed. 

I’m hesitant to think this is a bug in the web components, because the current package doesn’t include a close button. Please provide the actual package name and version. Removing myself and assigning to @micahgodbolt who may be better suited to triage this issue.

**Comment by chrisdholt** [comment]
Given the browser is EdgeHTML/Spartan, there’s no way this is the web component package.

**Comment by hyungkwon** [comment]
Sorry for the confusion. It's fluentui/react component (Modal).
