### ISSUE TITLE
[Bug]: Menu triggers autofocus on mount

### ISSUE THREAD

**Issue by NotWoods** [microsoft/fluentui#24981]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/suspicious-lamarr-s2ps37?file=/example.tsx

## Actual Behavior
When a menu trigger mounts, it automatically focuses itself

## Expected Behavior
The menu trigger doesn't force focus

### Requested priority

High

### Products/sites affected

Microsoft Loop

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
It looks like this is likely a regression from #24738.

I've created a draft PR with a potential fix, but I'm not familiar enough with the original change to know if this is the correct fix. More details are in the draft PR:
* #25016
