### ISSUE TITLE
[Bug] [Contextual Menu] - Clicking on sub menu item causes the popover(shifting focus as well) to get dismissed automatically. 

### ISSUE THREAD

**Issue by Deena-the-coder** [microsoft/fluentui#24988]
### Environment Information

- **Package version(s)**: 7.198.0
- **Browser and OS versions**: Microsoft Edge 

### Describe the issue:

We have imported the ContextualMenu fluent UI component in our product and have added a Calendar component as a sub menu item inside one of the menu item. The idea is to allow user to pick a date by clicking on one of the date and allowing him to save the date. This used to work well until we had the older version of "office-ui-fabric-react" library (7.170.0). Recently, we have updated this version to latest version 7.197.0 and have started observing a major bug. When we click on any of the sub menu item ( date in our case inside Calender), the menu item gets dismissed automatically and the focus is shifting back. Hence, the user is not able to select any date and this is **P0** bug for us. 

I tried to replicate the issue standalone and I could see the same behavior happening in ContextualMenu code as well. I am attaching the link herewith for you reference.

https://codepen.io/DeenaSparkzz/pen/LYmQEOM

Steps to reproduce the issue :
1. Please click on "Click for ContextualMenu"
2. Click on "Charm"
3. Click on any of the icons and see the popover getting dismissed automatically.

#### Actual behavior:
Clicking on any of the submenu items(icons) inside the menu item causing the menu item to get dismissed automatically. 

#### Expected behavior:
Clicking on any of the submenu items(icons) inside the menu item should allow the focus to stay on the clicked item.

### If applicable, please provide a codepen repro:
https://codepen.io/DeenaSparkzz/pen/LYmQEOM

### Priorities and help requested (not applicable if asking question): **Blocking**

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: https://todo.microsoft.com/tasks/

**Comment by Deena-the-coder** [comment]
It would be really helpful if someone could help us here. Its a blocking bug for us. A major feature is getting blocked because of this bug.

**Comment by Deena-the-coder** [comment]
Can someone please help me here?

**Comment by Deena-the-coder** [comment]
Can Somone please help me here. This was supposed to be closed.

**Comment by Deena-the-coder** [comment]
This bug is getting reproduced in the prod and I am really surprised that no one is helping me out here to fix the bug. It is highly impacting our product and a whole feature is blocked because of this. Can someone please help me out here?

**Comment by micahgodbolt** [comment]
The example given is from one of our website demos, and that demo works exactly as it is written. There aren't any bugs in it. The demo just isn't a fully formed app. It is an example of how you can customize the component. We need a reproduction of your calendar component issue to properly triage this issue.
