### ISSUE TITLE
[Bug]: GroupedListV2 Columns Not Aligning

### ISSUE THREAD

**Issue by MikeMorawski** [microsoft/fluentui#24992]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 5.69 GB / 15.94 GB
  Browsers:
    Chrome: 105.0.5195.127
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.53)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/migee/pen/bGMLqXq

## Actual Behavior
Sizing the columns in the header has no effect on data below. Root level groups and nested groups columns do not align vertically with one another.

## Expected Behavior
Columns across groupings should align vertically

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by MikeMorawski** [comment]
Hey @spmonahan when you developed the updates for V2 were you seeing the same behavior? I feel like I might just be missing something quick?

**Comment by MikeMorawski** [comment]
Also note: simply commenting out the V2 addition `groupedListAs` aligns everything as expected, however avoiding due to #20825

**Comment by spmonahan** [comment]
@MikeMorawski Thanks for the bug report!

I've confirmed this is an issue and will take a look at it.
