### ISSUE TITLE
[Bug]: Narrator is not announcing for the combo box results if there are results and no results found

### ISSUE THREAD

**Issue by v-pratikkh** [microsoft/fluentui#25009]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
  OS: Windows 10 19044.1889
 
  Memory: 146 GB used and 329 GB free
Browsers:
  Edge: Version 105.0.1343.27 (Official build) (64-bit)
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/team/fluentuiwc/pen/RwZZbvJ

## Actual Behavior
1. Start the narrator
2. Go to codepen and Select the combo box default or With autocomplete as mentioned in the codepen 
3. Check if the narrator is announcing the combo box results.

## Expected Behavior

The narrator should announce the combo box results if found or if not found. 

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@v-pratikkh The codepen example you linked uses `@fluentui/web-components` but the issue says it's for v8. Can you clarify for which library you intended to file this issue on?

![image](https://user-images.githubusercontent.com/8649804/213494104-d083f611-6d82-4dbe-80e5-f06334e9495c.png)
