### ISSUE TITLE
[Bug]:  TimePicker - 24:00 option instead of 00:00

### ISSUE THREAD

**Issue by stefoverflow** [microsoft/fluentui#25041]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 1.07 GB / 15.73 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.53)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

Depending on the timezone, I have 24:00 and 24:30 option to select in picker or 00:00 00:30.

## Actual Behavior
![image](https://user-images.githubusercontent.com/44927933/193544024-0f092893-0aba-4432-ba8a-7c155a99c266.png)

## Expected Behavior
![image](https://user-images.githubusercontent.com/44927933/193544160-4b984ef2-fe87-4b71-be16-494a5730e7e8.png)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
Are you able to reproduce the issue with a timezone set in OS without overriding the Location in devtools?

This is what I see when I set the timezone to **Mountain View, CA** in OS:
```js
new Date()
Fri Oct 14 2022 04:40:17 GMT-0700 (Pacific Daylight Time)
for (i = 0; i < 8; i++) { console.log ((new Date(new Date(2022, 9, 14, 22, 0).getTime() + i*30* 60000)).toLocaleTimeString([], {hour: 'numeric', minute: '2-digit', hour12: false}))}
VM6681:1 22:00
VM6681:1 22:30
VM6681:1 23:00
VM6681:1 23:30
VM6681:1 0:00
VM6681:1 0:30
VM6681:1 1:00
VM6681:1 1:30
```
With that the `TimePicker` works as expected.

The only scenario where I can repro the reported issue is when I override the timezone to **Mountain View** (or San Francisco) in Chromium devtools:
```js
new Date()
Fri Oct 14 2022 04:44:11 GMT-0700 (Pacific Daylight Time)
for (i = 0; i < 8; i++) { console.log ((new Date(new Date(2022, 9, 14, 22, 0).getTime() + i*30* 60000)).toLocaleTimeString([], {hour: 'numeric', minute: '2-digit', hour12: false}))}
VM7247:1 22:00
VM7247:1 22:30
VM7247:1 23:00
VM7247:1 23:30
VM7247:1 24:00
VM7247:1 24:30
VM7247:1 01:00
VM7247:1 01:30
```

**Comment by stefoverflow** [comment]
Yes, I am able to reproduce it.
![image](https://user-images.githubusercontent.com/44927933/196458145-055233ac-6f4e-471e-a96a-a0c861558759.png)

**Comment by TristanWatanabe** [comment]
Am able to repro the issue immediately with my timezone (UTC-5 EST): https://codepen.io/tristanwatanabe/pen/MWBOzNK

![image](https://user-images.githubusercontent.com/8649804/213505742-60c26054-95aa-4d2b-ab14-4b12b174c460.png)

**Comment by tarunrajput** [comment]
@TristanWatanabe , hour12 option in toLocaleTimeString() can produce inconsistent results for some timezones on V8. In some timezones, it resolves to h24, while in others it resolves to h23. 
I suggest we consider using the hourCycle option instead of hour12 for timeFormatting. Let me know your thoughts on this.
