### ISSUE TITLE
[Bug]: Menu divider visual bug

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#25097]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
https://aka.ms/fluentui-storybook
```

### Reproduction

https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/components-menu-menu--default#visual-divider-only

## menu divider
In storybook the divider looks like it is 2 px
![image](https://user-images.githubusercontent.com/48726002/194125642-eac99fb8-9652-45cb-be6c-77cfa29cdac2.png)

In the spec, the divider thickness should be mapping to 'strokeWidthThin'
![image](https://user-images.githubusercontent.com/48726002/194125935-db654660-2af4-4077-b788-f7db63bd5129.png)

### Requested priority

Normal

### Products/sites affected

All

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hirse** [comment]
I cannot repro this. It looks like 1px to me:
![image](https://user-images.githubusercontent.com/2564094/197410599-ea84d1a7-69bd-4b69-8a45-9c97c627fd3a.png)
