### ISSUE TITLE
[Bug]: Unable to use TextField component in a Callout on Android devices.

### ISSUE THREAD

**Issue by kashyap-raksha** [microsoft/fluentui#25125]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A
The issue is only on Android devices.
```

### Reproduction

https://codepen.io/rakshakashyap/pen/VwxGQJV

## Actual Behavior
Callout gets dismissed when using a TextField component inside the callout on Android device browser.
This is not observed in iOS or desktop/web browsers.

## Expected Behavior
Callout should not be dismissed. User should be allowed to enter input in the TextField inside Callout.

https://user-images.githubusercontent.com/25738721/194435760-8cd04664-8081-48b5-bbc9-b24dcd40bca1.mp4

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@kashyap-raksha I cannot repro this on Android 12/Chrome 109. Does it still repro?
