### ISSUE TITLE
[Bug]: "VirtualNetwork" is not included in icon list

### ISSUE THREAD

**Issue by zhigzhen** [microsoft/fluentui#25123]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (32) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 111.49 GB / 128.00 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.34)
    Internet Explorer: 11.0.22000.120
```

### Reproduction

https://codepen.io/maxzheng/pen/eYrLEgX

## Actual Behavior
The "VirtualNetwork" icon is not included in the icon list so I cannot use it. According to https://uifabricicons.azurewebsites.net/, the icon is F815

## Expected Behavior
iconName = "VirtualNetwork" should work

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
`@fluentui/font-icons-mdl2` currently uses icons v3.50. The list of available icons is here: https://developer.microsoft.com/en-us/fluentui#/styles/web/icons. This does not contain VirtualNetwork icon.

@tomi-msft - what is our policy re upgrading the icons?

**Comment by tomi-msft** [comment]
Hi @zhigzhen, while the `@fluentui/font-icons-mdl2` package doesn't have the `VirtualNetwork` icon, you can download and use it in your application using the `registerIcons` api. Please take a look at this page for more info: [Register Icons](https://github.com/microsoft/fluentui/wiki/Using-icons#registering-custom-icons)
