### ISSUE TITLE
Bug: Dialog Docs nits

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#25132]
### Library

React Components / v9 (@fluentui/react-components)

- [x] [With Form](https://react.fluentui.dev/?path=/docs/preview-components-dialog-dialog--default#with-form) says 'Having a formulary', which I assume should be 'Having a form'.
- [x] [Trigger Outside of Dialog](https://react.fluentui.dev/?path=/docs/preview-components-dialog-dialog--default#trigger-outside-dialog) It appears that the only thing added by DialogTrigger is the aria-haspopup="dialog". If that's the only thing added, we should note that, and not make the use of DialogTrigger sound so critical.  https://github.com/microsoft/fluentui/issues/25132#issuecomment-1274366111
- [x] opening the "Open non-modal dialog" in [No Focusable Element](https://react.fluentui.dev/?path=/docs/preview-components-dialog-dialog--default#no-focusable-element) leaves the user in a state where they have to refresh the page to return to a useable page state. While I understand that this is the lesson we're trying to teach, I feel this is a bit too much for someone that clicked the button out of curiosity. Either provide a way to close the modal, or at least warn what is about to happen. https://github.com/microsoft/fluentui/issues/25150
- [x] We tell people not to open a dialog from a dialog. I'm glad that we have validated that it is technically possible, but we already talk about it in the 'dont' section. There is no need to have an example of it. 
- [x] Does dialog title need it's own Story page, or can customizing the actions be an example on the main dialog page https://github.com/microsoft/fluentui/pull/25070

**Comment by bsunderhus** [comment]
> [Trigger Outside of Dialog](https://react.fluentui.dev/?path=/docs/preview-components-dialog-dialog--default#trigger-outside-dialog) It appears that the only thing added by DialogTrigger is the aria-haspopup="dialog". If that's the only thing added, we should note that, and not make the use of DialogTrigger sound so critical.

It actually also includes `tabster` deloser attributes which will ensure proper focus behaviour.

**Comment by bsunderhus** [comment]
> opening the "Open non-modal dialog" in [No Focusable Element](https://react.fluentui.dev/?path=/docs/preview-components-dialog-dialog--default#no-focusable-element) leaves the user in a state where they have to refresh the page to return to a useable page state. While I understand that this is the lesson we're trying to teach, I feel this is a bit too much for someone that clicked the button out of curiosity. Either provide a way to close the modal, or at least warn what is about to happen.

This will be addressed by this https://github.com/microsoft/fluentui/issues/25150

**Comment by bsunderhus** [comment]
> We tell people not to open a dialog from a dialog. I'm glad that we have validated that it is technically possible, but we already talk about it in the 'don't' section. There is no need to have an example of it.

This is a valid point. I guess I can keep the validation on a e2e test and omit it from the storybook itself 🤔
