### ISSUE TITLE
[Bug]: Tablist - ARIA hidden element must not be focusable or contain focusable elements

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#25133]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 17.28 GB / 31.59 GB
  Browsers:
    Edge: Spartan (44.22621.521.0), Chromium (106.0.1370.37)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://github.com/flora8984461/tablist-accessbility-repro

## Reproduce step
1. download the code
2. run `yarn (install)`
3. run `yarn start`
4. Use any accessibility test tool test localhost:3000 (for example, I used axe DevTools - Web Accessibility Testing chrome extension, Accessibility Insights for Web Edge extension, and also used storybook a11y addon)

## Actual Behavior
After running Accessibility test, I have this issue:
ARIA hidden element must not be focusable or contain focusable elements
Focusable content should have tabindex='-1' or be removed from the DOM

![image](https://user-images.githubusercontent.com/39588094/194595932-067c32cf-788d-4f63-8c96-a754103505f6.png)

## Expected Behavior
Should not have the above accessibility issue

Note: I also created accessibility issues in our internal tracker.

### Requested priority

Normal

### Products/sites affected

Viva Common UX

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by flora8984461** [comment]
More issues:

The tabs cannot be navigated by tab key.


![image](https://user-images.githubusercontent.com/39588094/195725964-e2441503-9799-43fe-80cd-b7b9b5055cf4.png)

**Comment by miroslavstastny** [comment]
I guess we can use `TabListDefault.stories` for the repro as well.

### ARIA hidden element must not be focusable or contain focusable elements
This issue is reported on `<i data-tabster-dummy>` elements which are added before and after Tablist buttons by Tabster - @ling1726, @mshoho - could you please check this?

### The tabs cannot be navigated by tab key
Tabs are navigable using arrow keys, Home, End. This is by design, see the spec: https://github.com/microsoft/fluentui/blob/5ea871d03d388b192a83e2e5c0e0717e7dc61add/packages/react-components/react-tabs/Spec.md#keyboard

**Comment by mshoho** [comment]
These are Tabster dummy inputs and they must be added to the exception list. They are intentionally aria-hidden as their purpose is to redirect focus to the correct element right when they receive focus and not having aria-hidden will result in the screen readers choking starting to announce them.

**Comment by flora8984461** [comment]
@mshoho thank you for help. Do you mean it's by design and safe to mark case as pass?

**Comment by mshoho** [comment]
@flora8984461 exactly.

**Comment by flora8984461** [comment]
And we have to leave it with `tabIndex = 0` so that it can redirect focus?

**Comment by mshoho** [comment]
yes.

**Comment by flora8984461** [comment]
Thank you! I will close this issue and bring this to the team.
