### ISSUE TITLE
[Bug]: @fluentui/react-northstar DatePicker goToToday is useless

### ISSUE THREAD

**Issue by wxGoldking** [microsoft/fluentui#25142]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
OS: Windows 10 10.0.22000
Browsers:
Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.77)
Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/6nfwe8?module=/example.js&file=/example.js:9-19

## Actual Behavior
DatePicker with goToToday prop, has no goToToday button

## Expected Behavior
show goToToday button

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
The goToToday functionality has never been implemented and AFAIK there is no plan to add it.
We should remove the `goToToday` prop.
