### ISSUE TITLE
[Feature]: Add Custom Callout Props Alongside Default Callout In LineChart

### ISSUE THREAD

**Issue by tedtheoneandonly** [microsoft/fluentui#25160]
### Library

@fluentui/react-charting

### Describe the feature that you would like added

We're looking to implement a message to appear in our callout for cases where a certain event happened that caused our data to change over the past month. For the days where this event occurred, we want to notify the user that it happened.

Looking at the current implementation in LineChart, it looks like we can already set a custom callout, but it replaces the one that already exists. For our case, we want our custom props to appear alongside the current callout, otherwise we would have to recreate the current callout and duplicate the code that generates the callout in our custom callout. Is there a way that we can have our custom callout to appear alongside the current callout?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by miroslavstastny** [comment]
It would be great if you could provide more details, ideally a code sample + image of what you want to achieve in what situation.

There are multiple ways how you can control the content of the callouts.
Every data point has `xAxisCalloutData` and `yAxisCalloutData`, see the example:
https://github.com/microsoft/fluentui/blob/a3a9a88f46832c03f3c164dea9193bd6cb3c38b2/packages/react-examples/src/react-charting/LineChart/LineChart.CustomAccessibility.Example.tsx#L77-L80

Also there is `getCalloutDescriptionMessage` prop on a `LineChart` which you can pass a function which gets all the data and you return the description which then appears in the callout. Example:
https://github.com/microsoft/fluentui/blob/a3a9a88f46832c03f3c164dea9193bd6cb3c38b2/packages/react-examples/src/react-charting/LineChart/LineChart.Gaps.Example.tsx#L261-L273

With that you should be able to customize the callout to your needs:
![image](https://user-images.githubusercontent.com/9615899/195890914-af047f12-e5c5-422a-9b01-29f32a2ecf6a.png)

**Comment by miroslavstastny** [comment]
If you need more customization options (like a formatted content at the top of the callout), there is `onRenderCalloutPerDataPoint` (resp. `onRenderCalloutPerStack`) prop, but as you wrote then you need to recreate the whole callout content as currently the content is baked into the component :-/
https://github.com/microsoft/fluentui/blob/4794f4f540c6df5dcf04fe12f18ee217084a1452/packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx#L354-L408

**Comment by miroslavstastny** [comment]
I guess This is an example callout @tedtheoneandonly is trying to achieve:
![image](https://user-images.githubusercontent.com/9615899/196194706-80135440-1d77-4d8f-a21e-7caec75fa45b.png)

The ask is to refactor the baked-in `_multiValueCallout` to a reusable component.

**Comment by tedtheoneandonly** [comment]
> I guess This is an example callout @tedtheoneandonly is trying to achieve: ![image](https://user-images.githubusercontent.com/9615899/196194706-80135440-1d77-4d8f-a21e-7caec75fa45b.png)
> 
> The ask is to refactor the baked-in `_multiValueCallout` to a reusable component.

That's exactly what we're looking for.

**Comment by tedtheoneandonly** [comment]
@miroslavstastny Do you know when you can implement such a feature?

**Comment by AtishayMsft** [comment]
@tedtheoneandonly Are you willing to submit a PR to add additional customization to the default callout as per your requirement.
