### ISSUE TITLE
[Feature]: Allow usage of SVG icons without React

### ISSUE THREAD

**Issue by gburning** [microsoft/fluentui#25161]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

The "react-icons-mdl2" package makes SVG versions of the MDL2 icons available. This is great, but as the project I am working on uses Vue rather than React I am currently unable to make use of them.

Would it be possible to extract and export only the actual `svg` markup so they can be imported for use without React? Preferably to something similar to the [Iconify format](https://github.com/iconify/icon-sets/blob/master/json/feather.json) From what I can gather there is nothing about the icons that inherently requires them to be defined directly as JSX.

If useful I might be able to provide a pull request for a simple version of this.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gburning** [comment]
This is still an issue

**Comment by khmakoto** [comment]
@gburning reopening

**Comment by TheJaredWilcurt** [comment]
Add Vue support
