### ISSUE TITLE
CommandBar tooltips

### ISSUE THREAD

**Issue by sdudnic** [microsoft/fluentui#25164]
Please add tooltips for FluentUI CommandBar items

>This is by design - Tooltips are shown for UI that doesn't have a textual description of the component. In the case for `CommandButtons` that have a label a Tooltip redundant. 
>
>cc: @smhigley - to weigh in on whether if this prescribed pattern. 
>
>Closing by design for now, but if there is a specific pattern that is required to have tooltips on every `CommandButton` regardless of it's mode, we're open to a contribution.
>
>_Originally posted by @paulgildea in https://github.com/microsoft/fluentui/issues/21534#issuecomment-1062633956_

Not clear the MS "_design_", I have a "**New**" button, but the tooltip is "_Add a new BusinessObject_", why can't we have a detailed explanation of the existing label?

**Comment by miroslavstastny** [comment]
You can use custom renderer for the CommandBar item.

1. Add `commandBarButtonAs: CustomCommandBarItem` to your CommandBar item
2. Implement the renderer:
```jsx
const CustomCommandBarItem = props => {
  return (
    <TooltipHost content="Custom tooltip">
      <CommandBarButton {...props} />
    </TooltipHost>
  );
};
```

_This is a simplified example ignoring accessibility. Make sure you handle all the necessary a11y props accordingly._
