### ISSUE TITLE
Not possible to use `Radio` as a standalone component

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#25206]
https://github.com/microsoft/fluentui/pull/25202/files#r994230706

Here's a sandbox that shows the usage of `Radio` alongside the native `<input />` element: https://codesandbox.io/s/snowy-framework-3xhuoi?file=/example.tsx

it's not possible to use the `Radio` as a standalong component like the `Checkbox` when using it with other components. The only workaround I've found so far is to render the `RadioGroupProvider` around each individual `Radio` component.

The main issue seems to be that there's no way to check the `Radio` component without wrapping it in a `RadioGroup` or `RadioGroupProvider`

**Comment by behowell** [comment]
It should work—could you elaborate what is the problem you’re having? Maybe with a codesandbox repro? It’s just a wrapper around the intrinsic `<input type=“radio”>`, so grouping radios requires them to all have the same `name` prop (which is done automatically if inside a RadioGroup, but can be done manually outside of one). 

I’m actually just adding a storybook page for Radio in PR #25195. You can see the PR build preview here: https://fluentuipr.z22.web.core.windows.net/pull/25195/public-docsite-v9/storybook/index.html?path=/docs/components-radio--default

**Comment by behowell** [comment]
Taking a look at the codesandbox you added to the description. It looks like there are two bugs in the codesandbox: 
* It's not setting `checked={checked}` on the `<Radio>`
* Both the standalone `<Radio>` and the `<RadioGroup>` have the same `name` prop, which results in the browser treating them as the same group, and only allowing one item to be selected at a time.

Here's a forked codesandbox with those two bugs fixed, and it works as expected:
https://codesandbox.io/s/wandering-dew-ezjvqy?file=/example.tsx

**Comment by ling1726** [comment]
After a discussion offline with @behowell  we concluded that the `checked` prop could be used for this purpose like `<Radio checked />`
