### ISSUE TITLE
[Feature]: Add preventDismissOnEvent for ContextualMenu to make it possibile that the menu will not dismiss for focus/resize... event

### ISSUE THREAD

**Issue by luyilin** [microsoft/fluentui#25208]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

I encountered an issue that the menu of ContextualMenu will disappear when the focus is changing, but we want the menu will only disappear for click event.
Currently for [ContextualMenu](https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu) component, there is no preventDismissOnEvent to make the menu not dismiss for events, the menu of ContextualMenu component is implemented by [Callout](https://developer.microsoft.com/en-us/fluentui#/controls/web/callout) component which contains the preventDismissOnEvent prop.
Then this feature can be easily implemented by adding the preventDismissOnEvent prop to IContextualMenuProps. I have raised a [PR](https://github.com/microsoft/fluentui/pull/25210) to add it. Could you help to review if it is appropriate to add the prop to ContextualMenu component and if there is better way to do it. Thanks.
https://codepen.io/luyilin/pen/NWMoxdx

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TristanWatanabe** [comment]
@luyilin Closing this as what you're trying to do should be possible using the `ContextualMenu`'s `calloutProps` prop. Simply passing `calloutProps={{preventDismissOnEvent: (ev) => {...}}}` to the ContextualMenu component should work.
