### ISSUE TITLE
[Bug]: FluentProvider does not adjust padding for RTL

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#25200]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 6.65 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 106.0.5249.103
    Safari: 16.0
```

### Reproduction

https://codesandbox.io/s/rtl-padding-kf49vh

## Actual Behavior
components with padding-left or padding-right do not have padding swapped in RTL.

## Expected Behavior
padding is swapped

This was found as a partner team asked about whether we use padding-inline-start and padding-inline-end which automatically flip in RTL mode.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@GeoffCoxMSFT it's how React Context works, there is nothing wrong with `FluentProvider` (_at least in your example_):`useStyles()` calls should in an inner component to get values properly: https://codesandbox.io/s/rtl-padding-forked-7k2vk1?file=/example.tsx

Check #23853 for more details.

**Comment by layershifter** [comment]
Closing, but we can follow up if more details will be provided.
