### ISSUE TITLE
Associate screener-run workflow with the parent commit

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#25213]
Currently the status of the [screener-build](https://github.com/microsoft/fluentui/actions/workflows/screener-build.yml) workflow in each PR. This is not the case for [screener-run](https://github.com/microsoft/fluentui/actions/workflows/screener-build.yml) which is run from the master branch.

This can be addressed by creating a commit status for the workflow. There are a few OSS actions that do the same such as https://github.com/marketplace/actions/workflow_run-status. However the OSS actions tend to be buggy, see:

* https://github.com/microsoft/fluentui/pull/25144
* https://github.com/microsoft/fluentui/pull/25145
* https://github.com/microsoft/fluentui/pull/25115
* https://github.com/microsoft/fluentui/pull/25096

We should create our own github script that does it like we do with [the triage bot](https://github.com/microsoft/fluentui/tree/master/scripts/triage-bot)

**Comment by TristanWatanabe** [comment]
Closing since we're no longer using Screener
