### ISSUE TITLE
[Bug]: Checkbox uses align-items: center when using onRenderLabel

### ISSUE THREAD

**Issue by ilbrando** [microsoft/fluentui#25235]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 10.22 GB / 31.38 GB
  Browsers:
    Chrome: 106.0.5249.119
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codesandbox.io/s/fluentui-checkbox-onrenderlabel-s7kcxl

## Actual Behavior
When using onRenderLabel the label  layout is having aling-items set to "center" instead of "flex-start".

The source of the problem:

```javascript
 label: [
      classNames.label,
      theme.fonts.medium,
      {
        display: 'flex',
        alignItems: isUsingCustomLabelRender ? 'center' : 'flex-start',
        cursor: disabled ? 'default' : 'pointer',
        position: 'relative',
        userSelect: 'none',
      },
```

[Code on Github](https://github.com/microsoft/fluentui/blob/96a85b4e57d08354fbd083dab6fd1bcd59fc0768/packages/react/src/components/Checkbox/Checkbox.styles.ts#L166)

## Expected Behavior
Layout to be the same as when not using onRenderLabel.

There might be a good reason for this, but at least it would be nice to be able to opt out of it and use the normal layout.

Another idea could be to allow the label to be a JSX element.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
Hey @ilbrando, I'm unaware of why this was decided, but it can be easily opted out of via a simple style override like the one in the following [modified codesandbox](https://codesandbox.io/s/fluentui-checkbox-onrenderlabel-forked-13zoki?file=/src/App.tsx) based on the one you attached to your issue. Let me know if that helps.

**Comment by ilbrando** [comment]
Sorry I forgot to answer. The workaround solves the problem.
