### ISSUE TITLE
[Bug]: Portal Component Not Rendering in Strict Mode

### ISSUE THREAD

**Issue by Caseyyu2** [microsoft/fluentui#25232]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

I created a sandbox with side by side menu component, one has inline=true, the other set inline=false; 
The one with inline=false, the pop over will not shown after click on the menu.

Here's the code sandbox example https://codesandbox.io/s/great-thompson-gkfe8o?file=/src/index.js

Note: I've also tried other portal components, e.g., combobox, dropdown, etc, it's the same behavior the portal component doesn't render correctly

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/great-thompson-gkfe8o?file=/src/index.js

## Actual Behavior
only the menu that has inline=false, the flyout/pop over renders correctly.

## Expected Behavior
both menu should be able to open successfully

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
The problem is strict mode, removing `<StrictMode />` will fix this issue: https://codesandbox.io/s/boring-leavitt-x9huz6?file=/src/index.js

**Comment by paulgildea** [comment]
cc: @GeoffCoxMSFT so we don't lose track.

**Comment by miroslavstastny** [comment]
Might be related to #24085. It would be great if we could fix the issues together.

**Comment by ling1726** [comment]
One way of doing this would be to use react internals and key the singleton with the id of the current fiber. This would be possible with `React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner.current`

https://github.com/facebook/react/blob/e7c5af45ceb8fa2b64d39ec68345254ce9abd65e/packages/react/src/ReactCurrentOwner.js#L23
https://github.com/facebook/react/blob/e7c5af45ceb8fa2b64d39ec68345254ce9abd65e/packages/react/src/ReactSharedInternals.js#L21

However, as react states, if we use these internals we cannot expect any official support and they can break at during any release of react
