### ISSUE TITLE
[Bug]: Not able to collapse all the chevrons when multiple flag is added to Accordion component

### ISSUE THREAD

**Issue by ubanthia** [microsoft/fluentui#25276]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
npx: installed 1 in 2.102s

  System:
    OS: Windows 10 10.0.22621
    CPU: (28) x64 Intel(R) Core(TM) i9-10940X CPU @ 3.30GHz
    Memory: 33.87 GB / 63.72 GB
  Browsers:
    Edge: Spartan (44.22621.674.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.22621.1
```

### Reproduction

https://react.fluentui.dev/?path=/docs/components-accordion--default#multiple

## Actual Behavior
User is not able to collapse all the chevrons when multiple flag is added to the Accordion component. One of the accordion sections is by default open in this case.

## Expected Behavior
User should be able to expand and collapse all the sections at any point of time.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by GeoffCoxMSFT** [comment]
@behowell - Can you kindly review and see if this is indeed a bug?

**Comment by GeoffCoxMSFT** [comment]
Per the discussion, closing.

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/28762486/200387738-3966c0ae-2e29-4d59-ae47-88a6316f1594.png">
