### ISSUE TITLE
[Bug]: DetailsList - ProportionalColumns Example - `NaN` is an invalid value for the `width` css style property.

### ISSUE THREAD

**Issue by chris-chapin** [microsoft/fluentui#25282]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11980HK @ 2.60GHz
    Memory: 14.39 GB / 31.71 GB
  Browsers:
    Edge: Spartan (44.22621.674.0), Chromium (106.0.1370.47)
    Internet Explorer: 11.0.22621.1
```

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/proportionalcolumns

### Bug Description

1. https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/proportionalcolumns > Export to Codepen
2. Developer Tools > Console

## Actual Behavior
iframeConsoleRunner-7549a40147ccd0ba0a6b5373d87e770e49bb4689f1c2dc30cccc7463f207f997.js:1 
        
       Warning: `NaN` is an invalid value for the `width` css style property.
    in div (created by t)
    in t (created by Styledt)
    in Styledt (created by t)
    in div (created by t)
    in t (created by t)
    in t (created by Styledt)
    in Styledt (created by _y)
    in div (created by _y)
    in div (created by _y)
    in div (created by _y)
    in _y (created by t)
    in t (created by o)
    in div (created by o)
    in o (created by Styledo)
    in Styledo (created by DetailsListProportionalColumnsExample)
    in DetailsListProportionalColumnsExample (created by DetailsListProportionalColumnsExampleWrapper)
    in div (created by ThemeProvider)
    in bc (created by ThemeProvider)
    in ThemeProvider (created by DetailsListProportionalColumnsExampleWrapper)
    in DetailsListProportionalColumnsExampleWrapper

## Expected Behavior
no warnings should be logged

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
Able to repro this for the `DetailsList` example linked above. While this issue is isolated in the example story itself, the issue seems to stem from the `column`s having a `flexGrow` property which the `DetailsList` is unable to handle. 

https://github.com/microsoft/fluentui/blob/06505b5c50c6deedcb36b29417cf35b77da85cfc/packages/react-examples/src/react/DetailsList/DetailsList.ProportionalColumns.Example.tsx#L39
