### ISSUE TITLE
[Bug]: Menu contents is blurry if anchor is not on a full pixel boundary

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#25288]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Windows 11 (v22H2)
Edge (v106), and Chrome (v106)
100% DPI
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/smoosh-darkness-02zpzc?file=/example.tsx

## Actual Behavior
The contents of a menu is blurry when the anchor button is not on an exact pixel boundary. One way this could happen is if the button is centered inside a container that is an odd number of pixels tall.

This effect is more pronounced on a menu that has a filter applied, like `backdrop-filter: blur(100px)` in the repro example, which is replicating real-world use in a product.

![image](https://user-images.githubusercontent.com/48106640/196572647-311951f7-5139-47e3-90a7-ba09cc37fda9.png)

It appears that the menu is positioned using a translate transform like `transform: translate(0px, -4.5px)`.

## Expected Behavior
Menus should be crisp, regardless of whether their anchor has subpixel placement. This could be done by rounding the transform offset.

![image](https://user-images.githubusercontent.com/48106640/196572689-eacc9f83-a9f9-43a5-939b-49270d5f950f.png)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by NotWoods** [comment]
I'm able to reproduce this on 160dpi screens (regular dpi) on Windows with a Surface Laptop. It's not as apparent on a high dpi screen but still present.

**Comment by behowell** [comment]
Just added the system info to the bug report: I can repro it on Edge/Chrome on Windows 11. It's possible that Safari/ Mac handles pixel snapping differently?

**Comment by YuanboXue-Amber** [comment]
For me I can't repro it on mac display in edge/chrome/safari (window.devicePixelRatio = 2). I'll find a older monitor and give it a try again

**Comment by behowell** [comment]
It makes sense that it wouldn't be visible on a monitor with 200% DPI. If the menu is shifted by half of a logical pixel, that would still land exactly on the physical pixels. 

If you can't see the blurriness on your monitor, then one way to check if it is repro'ing is to look for a 0.5-pixel transform being applied to the menu div in devtools:
![image](https://user-images.githubusercontent.com/48106640/197046338-35bf37c4-d006-4e04-8e09-d3a57f901f05.png)

**Comment by YuanboXue-Amber** [comment]
I have the repro on my windows machine with an old monitor (window.devicePixelRatio = 1).
It's interesting that I don't have the repro on the same monitor with mac. I think mac is doing something behind the scene.
