### ISSUE TITLE
[Feature]: Set up a branch for WC v3

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#25296]
### Library

Web Components (@fluentui/web-components)

### Describe the feature that you would like added

Set up a branch for Web Components v3 development

- [x] There is stale branch [web-components-v3](https://github.com/microsoft/fluentui/tree/web-components-v3). Rebase the branch to the latest `master`, ~~force~~ push
- [x] Remove all source code from `packages/web-components` in the web-components-v3 branch #25434 
- [ ] Bump the version for `web-components` to `3.0.0-alpha.0`
- [x] Configure `web-components-v3` as a protected branch in github
- [x] Configure CI for `web-components-v3` branch - make sure the build runs
- [x] Set up / verify `yarn change` support for `web-components` (yarn change generates changes for web-components, CI verifies change entry has been created when the sources have been touched)
- [x] Configure beachball releases for `web-components` in the `web-components-v3` branch #25773
  - allow only `prerelease` (alpha) bumps
  - NPM publish to `alpha` dist tag
  - beachball automatically releases `web-components` alpha from the branch when there are changes
  - and NEVER releases any other package from the branch

`web-components@2` will still be released to `latest` from `master` branch (no change)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by miroslavstastny** [comment]
@chrisdholt could you please review the proposed steps?

**Comment by chrisdholt** [comment]
> @chrisdholt could you please review the proposed steps?

This looks great!

**Comment by miroslavstastny** [comment]
Done
