### ISSUE TITLE
[Bug]: name attribute ignored on FormRadioGroup

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/fluentui#25292]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 28.22 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/fluent-ui-example-forked-v87x0u

## Actual Behavior
In the `onSubmit` method on the `Form` component, when creating a `FormData` object from `event.currentTarget`, the value of a radio group is not included in the `FormData` as they do not have the `name` attribute applied to the radio items in the group.

Consider the following example

[![Edit fluent-ui-example (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fluent-ui-example-forked-v87x0u?expanddevtools=1&fontsize=14&hidenavigation=1&theme=dark)

No value is returned for `answer`, but a value is returned for `text`.

## Expected Behavior

Items in the `FormRadioGroup` should be rendered with `name` attributes.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by jurokapsiar** [comment]
Hi, Radio in react-northstar does not render native input elements and thus its data will not be included in the submitted data.

Please use Fluent UI v9 radio group as it renders native input: https://react.fluentui.dev/?path=/docs/components-radio--default
