### ISSUE TITLE
Table should overflow with horizontal scrollbar

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#25300]
Currently the table does not overflow at all which can look quite ugly

Flex layout:
![image](https://user-images.githubusercontent.com/20744592/196775492-c08c1b20-4e9e-4348-80e0-0f552a090edc.png)

Table layout:
![image](https://user-images.githubusercontent.com/20744592/196775445-5c3e2efc-5a1f-45db-9e6f-1ac240c5b70a.png)

**Comment by phierru** [comment]
The table should first compress the columns to minWidth then overflow and display horizontal scrollbar. Also we should be able to fix the first n columns.
