### ISSUE TITLE
[Bug]: Slider's thumb extends past the edges of the control

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#25313]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/preview-components-field-sliderfield--default

## Actual Behavior
The thumb of Slider extends beyond the bounds of its root, which causes it to appear misaligned with a label or other form controls:
![image](https://user-images.githubusercontent.com/48106640/196825726-e1752791-1c16-4b82-ad71-a1e4a6027af3.png)

## Expected Behavior
The slider should be aligned with the edge of its root. Perhaps the track needs to be padded in, so the thumb doesn't extend past the end when it is at 0?

Note: This bug is logged based on a comment in a Field VR test PR: https://github.com/microsoft/fluentui/pull/25263#issuecomment-1282865440

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
cc @micahgodbolt

**Comment by micahgodbolt** [comment]
you kicked the hornet's nest here :) This was a thorn in my side while creating the control. Without using additional wrapping elements I was not able to figure out a way to avoid this, while also allowing the thumb to travel so that it was centered over the rail edge. 

![image](https://user-images.githubusercontent.com/1434956/197834801-b3609b43-461e-45f0-8dfa-b6b24de5fa9c.png)

Typical sliders stop when the edge of the thumb touches the edge of the rail. 

Is it possible to work around this and make a special case for slider? Or do we need to revisit this again?

**Comment by behowell** [comment]
It is technically possible to special-case this for SliderField, but I imagine it would also be a problem for other places that use Slider, if it renders outside the bounds of the root element.

The simplest way to solve this visually would be to add a left/right margin to the root element, to give space for the thumb to extend past the end of the track. That's probably how it would be special-cased for SliderField if needed. But that does feel a little like adding a hack on a hack, since the thumb would still be rendered outside the borders of the root element.

Another option is to add padding to the root element, and refactor the slider's styles a little to account for it. I was prototyping this option and it seems to work pretty well, so I published a draft PR with the fix. The main drawback is that it results in a DOM structure change (or else the styles get unnecessarily complex to account for the padding).
* #25378
