### ISSUE TITLE
[Bug]: Accordion re-renders panels instead of hidding/showing

### ISSUE THREAD

**Issue by Hensorskyy** [microsoft/fluentui#25322]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.57 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 103.0.2
    Safari: 16.0
```

### Reproduction

Add accordion with panels. When you click on a title panels show up and hide. But each time they rerenders instead of just hiding.

## Actual Behavior
Accordion panels are being rerendered each time. It causes issues because many requests are being done instead of one. You may check the actual behavior here in the [example](https://fluentsite.z22.web.core.windows.net/0.64.0/components/accordion/definition?showCode=false&showRtl=false&showTransparent=false&showVariables=false#usage-accordion-panel-custom-title-example)

## Expected Behavior
Expect that the panels just hide or show without rerendering. The logic was available in v59 of the library. Possibly a flag needs to be added that controls the functionality. 
Here is an expected behavior [example] (https://fluentsite.z22.web.core.windows.net/0.59.0/components/accordion/definition?showCode=false&showRtl=false&showTransparent=false&showVariables=false#usage-accordion-panel-custom-title-example)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by jurokapsiar** [comment]
Hi, this was an intentional change as rendering all panels was causing performance issues with large datasets. Would you be willing to contribute a PR if the previous behavior is still preferable? It can be added as a non-breaking option (new prop).

**Comment by Hensorskyy** [comment]
thanks! Could you please share a link on the beaking change PR?

**Comment by jurokapsiar** [comment]
the change was implemented here: https://github.com/microsoft/fluentui/pull/20783/files

**Comment by Hensorskyy** [comment]
@jurokapsiar Could you please take a look at the [PR](https://github.com/microsoft/fluentui/pull/25368)?

**Comment by layershifter** [comment]
@Hensorskyy as @jurokapsiar mentioned the change have been implemented already. I checked with `@fluentui/react-northstar@0.65.0` and it does not render hidden panels:

![image](https://user-images.githubusercontent.com/14183168/214357748-835fed36-208a-4792-bae7-50cd82d3e8a2.png)

Is there anything that I am missing?

**Comment by Hensorskyy** [comment]
@layershifter the problem is with rerendering panels instead of just showing/hiding. Please check the [PR](https://github.com/microsoft/fluentui/pull/25368/files).

**Comment by layershifter** [comment]
@Hensorskyy I see now 👍

Prop naming confused me initially, let's rename it. I left comments on the PR. Thanks!

**Comment by Hensorskyy** [comment]
@layershifter Thanks. Fixed your comments.
