### ISSUE TITLE
[Bug]: ContextualMenu list items do not have hover state in OS High Contrast Mode

### ISSUE THREAD

**Issue by madalynrose** [microsoft/fluentui#25330]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (36) x64 Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz
    Memory: 36.67 GB / 63.80 GB
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/madalynrose/pen/yLjmXKp

## Actual Behavior

1. Open ContextualMenu
2. Hover over menu list item
3. No visual indication of hover

<img width="961" alt="screenshot of contextual menu example with no hover state over 'Edit' list item" src="https://user-images.githubusercontent.com/3230904/197227131-0fa4c20a-b8fb-4b84-9e56-f28d3f54aa67.png">

## Expected Behavior
1. Open ContextualMenu
2. Hover over menu list item
3. Visual indication of hover where either background or foreground color of list item changes

The below screenshot shows the same contextual menu using fluentui/react 8.49.6
<img width="932" alt="screenshot of contextual menu example in codepen using fluentui react 8.49.6 with hover state on 'Edit' list item" src="https://user-images.githubusercontent.com/3230904/197226106-5f7bc6c6-6d4f-4be5-b70b-74a5ca63f1a3.png">

### Requested priority

High

### Products/sites affected

Accessibility Insights for Web

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by natalieethell** [comment]
I notice the PR above, but it looks like there still aren't any hover styles in high contrast mode. Here's a gif from the FluentUI example site in Edge on a Windows machine with Contrast themes set to Aquatic (Fluent UI React 8).

![Fluent UI ContextualMenu HC Hover](https://github.com/microsoft/fluentui/assets/14134000/1380516c-392c-4470-90f9-c657444e3a39)

Are there plans to update these styles? We would really love these for our use case so we don't have to override styles.
