### ISSUE TITLE
[Bug]: A pixel under dropdown callout that keeps making it scrolling

### ISSUE THREAD

**Issue by crane28** [microsoft/fluentui#25348]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 811.68 MB / 7.69 GB
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/crane28/pen/PoaYEbW

## Actual Behavior
There's a small pixel that when hover making the dropdown scrolls down
![DropdownScroll](https://user-images.githubusercontent.com/51945886/197462989-06d56a2e-62ad-4179-8079-9f98b11907c4.gif)

If you cant reproduce this, try to play the browser zoom level. I can only reproduce the bug on codepen when I zoom it to 110% on Chrome. Here's a gif for this:
![DropdownScroll2](https://user-images.githubusercontent.com/51945886/197463465-51ac700e-485e-4607-a6af-4da9254ef746.gif)

## Expected Behavior
The dropdown is not scrolling even when mouse exiting from bottom side.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
Can confirm repro - at a certain browser zoom level (might vary, mine was at 175%) hovering from the bottom right outside the `Dropdown` to the last visible dropdown item does auto-scroll the dropdown.

**Comment by msimecek** [comment]
+1 
Having the same behavior when the dropdown is displayed as Panel. Browser zoom 110%.
