### ISSUE TITLE
[Bug]: Dropdown selected item is not visible inside of Dialog

### ISSUE THREAD

**Issue by divad-msft** [microsoft/fluentui#25372]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
Browser: Google Chrome
Version: Version 108.0.5359.10
OS version: windows 11
```

### Are you reporting Accessibility issue?

Yes

### Reproduction

https://codesandbox.io/s/fluent-ui-example-forked-exzq4j?file=/example.js

## Actual Behavior
The dropdown selected item is not visible if the dialog size is small, there is a scrollbar but there is not accessible if we use the keyboard

## Expected Behavior
There are 2 scenarios.

1. The result area should be limited by the size of the dialog
2. When an item is selected the scroll should move too

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by adrinamin** [comment]
I'm currently having the same problems when implementing a dropdown component inside a dialog, using _fluentui/react-northstar@0.65.0_. Any updates on that issue? Or is there at least some kind of workaround?

**Comment by jurokapsiar** [comment]
Hi, the Dialog sets overflow: 'auto' which will detect the dropdown as overflowing the container. if you set overflow: 'unset' it will make the dropdown work like in the popup... but then you have no overflow handling.

https://codesandbox.io/s/fluent-ui-example-forked-3y5u2r?file=/example.js

thank you @ling1726 for the insight.
