### ISSUE TITLE
Investigate Layer and portal stacking context

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#25391]
There might be some issues with the order of portals between v8 and v9. Investigate the reported repro and determine the root cause.

https://codesandbox.io/s/determined-mountain-87b6vp?file=/example.tsx

The below screenshot shows the `Combobox` callout render under the popover

![image](https://user-images.githubusercontent.com/20744592/198132050-b0ee8af6-7035-4afc-a407-3046306d5427.png)

**Comment by miroslavstastny** [comment]
There might be a workaround by setting `layerHost` in v8 `layerProps`. We should investigate.

**Comment by miroslavstastny** [comment]
@layershifter to link other related issues, add Geoff to the loop.

**Comment by layershifter** [comment]
Related issues: #26386, #26278.

According to https://github.com/microsoft/fluentui/issues/26386#issuecomment-1405191125 we are not going to work on it now.
