### ISSUE TITLE
Menus gone from Fluent UI website

### ISSUE THREAD

**Issue by socialpixe** [microsoft/fluentui#25398]
Menus gone from main website.

https://react.fluentui.dev/?path=/docs/concepts-introduction--page

![Screenshot from 2022-10-27 09-44-04](https://user-images.githubusercontent.com/24809844/198190009-eabdcef4-9482-4ef1-8e4b-c13aea48204d.png)

**Comment by khmakoto** [comment]
Hi @socialpixe, I'm not seeing this anymore. Can you confirm if you are still seeing this on your side?

![image](https://user-images.githubusercontent.com/7798177/204368345-6044bcbc-b32c-4a0b-ab5e-0d3fad7b3df2.png)
