### ISSUE TITLE
[Bug]: Pivot : Callout for overflow menu not full size. Is it possible to change callout styles?

### ISSUE THREAD

**Issue by dennymicrosoft** [microsoft/fluentui#25392]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
    Memory: 904.77 MB / 15.73 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.22000.120
```

### Reproduction

Create a pivot with overflow menu enabled and so that it displays the menu

## Actual Behavior
Scroll bar showing for one item in menu callout
![image](https://user-images.githubusercontent.com/116671731/198136854-ed8eaf15-d343-4e47-a4e1-2aa4827d78b9.png)

## Expected Behavior
Callout should not display scroll bar for few menu items. Is there a way to pass styles to the callout so I can set the height / max height?

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by dennymicrosoft** [comment]
I guess a work around would be make a custom render with the overflowButtonAs prop, but there is no other way?

**Comment by khmakoto** [comment]
Hi @dennymicrosoft, do you have a minimal repro in a codepen or a codesandbox I could take a look at?
