### ISSUE TITLE
[Feature]: Bring back on and off text from v8 Toggle in v9 Switch

### ISSUE THREAD

**Issue by tomresing** [microsoft/fluentui#25393]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

We're in the process of migrating from v8 to v9 and there are some breaking changes in the UX between [the Toggle control in v8](https://developer.microsoft.com/en-us/fluentui#/controls/web/toggle) and [the Switch component of v9](https://react.fluentui.dev/?path=/docs/components-switch--default).

In v8, the default for a Toggle is to show the state in text following the toggle button as "On" or "Off". The label shows on before the toggle button, by default.

For example, the default toggle code, shown in the example in the documentation follows.
`<Toggle label="Enabled and checked" defaultChecked onText="On" offText="Off" onChange={_onChange} />`
And it renders as follows:
![image](https://user-images.githubusercontent.com/2660081/198151836-c156e8f7-5ebb-45b4-b0a3-25431395f38e.png)

In v9, there's no distinction between the text for the state of the switch and the text for the label.

The default code for the switch follows:
`<Switch label="This is a switch" />`
And renders as follows:
![image](https://user-images.githubusercontent.com/2660081/198152067-da626693-0d7d-41ae-a72a-4f8e29924562.png)

I suspect this difference from v8 derives from an inheritance from [the checkbox control in v0](https://fluentsite.z22.web.core.windows.net/0.51.7/components/checkbox/definition). V0 doesn't have a dedicated toggle control. Instead, the checkbox control has a "toggle" Boolean property which, when true, styles the checkbox button as a toggle button, as follows:
`<Checkbox label="Subscribe to weekly newsletter" toggle />`
![image](https://user-images.githubusercontent.com/2660081/198152748-e3e84b8b-d95a-46f1-90e5-d636f5cfde9f.png)

The other web flavor also includes text properties similar to v8. [Fluent UI Web Components has a Switch component](https://learn.microsoft.com/en-us/fluent-ui/web-components/components/switch?pivots=typescript), which also has text properties for state as follows:
`<fluent-switch>
  <span slot="checked-message">On</span>
  <span slot="unchecked-message">Off</span>
  <label for="cap-switch">Captions:</label>
</fluent-switch>`
![image](https://user-images.githubusercontent.com/2660081/198155812-7b33ec05-0164-4f99-af0f-17665e515d56.png)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ling1726** [comment]
Assigning to @khmakoto  in cxe-red to see if this is a feature request that they would like to support

**Comment by khmakoto** [comment]
Hi @tomresing, this is by design because our philosophy in v9 is to have a cleaner interface that don't have props that could be derived from very well-known patterns like controlled behavior. Hooking things up to achieve this in v9 by yourself is a relatively easy effort, as you can see in [this codesandbox](https://codesandbox.io/s/controlled-switch-with-labels-on-top-and-on-the-side-rdpscf) I've made to illustrate the issue. Let me know if there is anything else I can do to help!

**Comment by tomresing** [comment]
Thanks for the explanation. We're going to need robust migration documentation for updating this component!
