### ISSUE TITLE
[Bug]: Selecting options in Combobox using arrow keys does not work correctly.

### ISSUE THREAD

**Issue by irynakaban** [microsoft/fluentui#25414]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 52.49 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
Browsers:
    Chrome: 106.0.5249.119
    Firefox: 94.0.1
    Firefox Developer Edition: 107.0
    Safari: 16.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/irynakaban/pen/bGKNzym -- code
https://drive.google.com/file/d/1g1ms-zd3s1_PO8I_Mx2VTCQ9oP3CSPsS/view?usp=sharing -- video

### Bug Description
In the Combobox component, when the allow freeform setting is selected and arrow keys + enter is used to select options, the last selected option is not selected after the user de-focuses. This will only reproduce when the allow freeform setting is active. 

## Actual Behavior
1. Enable allow freeform.
2. Put the focus on the combobox.
3. Using arrow key select option and press enter.
4. Remove the focus from the combobox.
5. Open the list of items. The option selected on step 2 is not selected.

The behavior is similar when you select multiple items with arrow keys. But on the fourth step you will not select the last selected item.

## Expected Behavior
1. Enable allow freeform.
2. Put the focus on the combobox.
3. Using arrow key select option and press enter.
4. Remove the focus from the combobox.
5. Open the list of items. The option selected on step 2 is selected.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Which option are you selecting before hitting enter?

**Comment by micahgodbolt** [comment]
Ok, I finally repro'ed it. You need to put focus in combobox, and then hit enter to open the listbox. Then arrow down to "Option A". Hit enter to select it, and then tap out.
