### ISSUE TITLE
[Bug]: Coachmark and TeachingBubble anchors don't handle page resizing 

### ISSUE THREAD

**Issue by monica-pandey** [microsoft/fluentui#25415]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
"@fluentui/react": "^8.85.0"
```

### Reproduction

Here's an easy repro:

- v7 https://codesandbox.io/s/funny-dew-eihn2
- v8 https://codesandbox.io/s/sleepy-alex-2e25bi

### Bug Description

Actual behavior:
At initial zoom, coachmark looks like:
(browser is 'Restore down')
![image](https://user-images.githubusercontent.com/65119146/198293993-bdbfb177-1efa-4f1a-903b-9b9b75604a7d.png)

After zooming out, coachmark looks like:
(browser is maximized)
![image](https://user-images.githubusercontent.com/65119146/198294026-d1744354-e15e-4387-8537-2977607e0b29.png)

Please note, the issue is happening on page resizing

Expected behavior:
Callout elements remain anchored to their targets.

### Requested priority

High

### Products/sites affected

Excel

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
The issue can be reproduced on both v7 & v8. 

In v8 there is a listener for `resize` event that is triggered on a page resize:

https://github.com/microsoft/fluentui/blob/52fad61a1e6c29e8e815fd74bc66f06a100710e3/packages/react/src/components/Coachmark/Coachmark.base.tsx#L278-L289

However, it seems that something does not work as expected.

**Comment by micahgodbolt** [comment]
Don't use 'float: right' to reposition the components. Use flex or grid instead.

![image](https://user-images.githubusercontent.com/1434956/217046735-dda4067e-c43a-4d82-8977-ef5d8c235710.png)
