### ISSUE TITLE
[Bug]: react-tabster - findAllFocusable method always returning ALL elements inside the target

### ISSUE THREAD

**Issue by marcosmoura** [microsoft/fluentui#25413]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
-
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/

## Actual Behavior
The `findAllFocusable` method needs an `acceptCondition` function that, when provided, will return all the elements inside the container (not only the focusable ones).
![image](https://user-images.githubusercontent.com/1357885/198292993-d39c9de4-2541-4bfa-a6a8-e9c5fbb9384a.png)

On the Tabster library, the `acceptCondition` function is optional, but the `react-tabster` wrapper has a required param. Changing it to optional, might fix the problem.

Another alternative would be changing the second parameter to a `FindAllProps` type, so we could decide which props to pass to Tabster.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
closed by https://github.com/microsoft/fluentui/pull/25416

**Comment by bsunderhus** [comment]
Actually, let's keep it open, I want to investigate another possible solution, I've talked with @marcosmoura  to have https://github.com/microsoft/fluentui/pull/25416 as a quick fix for now!
