### ISSUE TITLE
[Bug]: FluentProvider stylesheet (CSS vars for theme) are not server-side rendered

### ISSUE THREAD

**Issue by paularmstrong-msft** [microsoft/fluentui#25425]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/github/paularmstrong-msft/fluentui-ssr-issue/draft/silent-smoke

## Actual Behavior
No theme variables are server-side rendered, causing the site to initially display with no colors, incorrect fonts, incorrect spacing, etc, etc. 
<img width="260" alt="Screenshot 2022-10-27 at 12 59 16" src="https://user-images.githubusercontent.com/108080477/198386684-e1c5eb10-6da9-4380-a256-16deffc8db2d.png">

## Expected Behavior
When following the [SSR instructions](https://react.fluentui.dev/?path=/docs/concepts-developer-server-side-rendering--page), it is expected that ALL styles are rendered to the page and do not have a flash of unstyled content (FOUC).
<img width="265" alt="Screenshot 2022-10-27 at 13 02 04" src="https://user-images.githubusercontent.com/108080477/198386967-7ce4cff2-602e-488b-85e3-552f8ed5ebdb.png">

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hi @paularmstrong-msft, your repro doesn't show the issue. I think it's probably related to this #23620. The fix would be to change your `next.config.js` file to the following:
```js
module.exports = {
  reactStrictMode: false
};
```

You can see that the sandbox you provided has StrictMode turned off. Let me know if you still have issues after making the change. Thanks!

**Comment by paularmstrong** [comment]
@sopranopillow Set your network inspector to "slow 3g" or turn of javascript in your browser to reproduce the issue. Also, the `next.config.js` has strict mode disabled: https://codesandbox.io/p/github/paularmstrong-msft/fluentui-ssr-issue/draft/silent-smoke?file=%2Fnext.config.js

**Comment by JustSlone** [comment]
I can confirm that I do see a FOUC briefly in the above repro

**Comment by layershifter** [comment]
Indeed, `FluentProvider` does not server CSS variables on a server. On of ideas to on how to solve it is to render them inline on a server like Emotion does:
https://github.com/emotion-js/emotion/blob/92be52d894c7d81d013285e9dfe90820e6b178f8/packages/react/src/global.js#L69-L76

**Comment by ahmed-adly-khalil** [comment]
I have the same issue, my solution with Next JS 13 is to use `use client` and render everything client side which is not a good solution and causes a delay in rendering / slowness

**Comment by AkiraVoid** [comment]
So, will this be fixed or something? And when will this be fixed? @layershifter

**Comment by kletse** [comment]
Any update on this yet?

The documentation states: 
**"Fluent UI React v9 fully supports Server-Side Rendering."** 
https://react.fluentui.dev/?path=/docs/concepts-developer-server-side-rendering-basic-setup--page

This issue actually makes this statement incorrect, as most components won't be styled correctly with the CSS and HTML served to the client until javascript is loaded.

I can't migrate a project (a public website) from v8 to v9 as long as this is the case.

**Comment by layershifter** [comment]
> So, will this be fixed or something? And when will this be fixed? @layershifter Oleksandr Fediashov aka shift FTE

Yes, the plan is to fix it in one of our upcoming sprints.

**Comment by layershifter** [comment]
> Indeed, `FluentProvider` does not render CSS variables on a server. On of ideas to on how to solve it is to render them inline on a server like Emotion does: https://github.com/emotion-js/emotion/blob/92be52d894c7d81d013285e9dfe90820e6b178f8/packages/react/src/global.js#L69-L76
> 
> However, we need to ensure that it will work with portals.

Seems to work like it should, https://codesandbox.io/s/kind-morning-1n281k?file=/src/App.js
