### ISSUE TITLE
[Bug]: Link to Theme token docs does not work on react.fluentui.dev

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#25436]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/concepts-developer-theming--page

## Actual Behavior
1. Go to https://react.fluentui.dev/?path=/docs/concepts-developer-theming--page
2. Under the "Theming" section click the "Theme" link
3. Page does not navigate

## Expected Behavior
I should be taken to the page about theme tokens.

### Requested priority

Normal

### Products/sites affected

react.fluentui.dev

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
current link https://react.fluentui.dev/iframe.html?path=/docs/theme-colors--colors

actual page URL
https://react.fluentui.dev/?path=/docs/theme-color--page


looks like it's the change from colors to page that broke it
