### ISSUE TITLE
[Bug]: [Accessibility]:  Fluent UI Line chart No updated tooltip information is shown for the marker where the 'line-chart' has gaps between lines based on dates, when navigated with Keyboard (tabs and arrows)

### ISSUE THREAD

**Issue by rsoni0809** [microsoft/fluentui#25431]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Please refer the link:

https://codepen.io/rahulsoni/pen/VwdLpqo

Steps to reproduce:
1. Open the Codesandbox
2. Press tab and reach to first dot of line and then press right arrow
3. On each right arrow new tool tip will be appeared
4. Now once we reach to the end of distorted line no new tool tip will be appeared and tool tip will be of previous dot. 
5. This issue is for all intermediate distorted line
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/rahulsoni/pen/VwdLpqo

### Bug Description

Please refer the link:

https://codepen.io/rahulsoni/pen/VwdLpqo

Videos link: https://drive.google.com/file/d/1uo6GG5shBtT0944JZxhqQeX82HHLOnKr/view

Steps to reproduce:
1. Open the Codesandbox
2. Press tab and reach to first dot of line and then press right arrow
3. On each right arrow new tool tip will be appeared
4. Now once we reach to the end of distorted line no new tool tip will be appeared and tool tip will be of previous dot. 
5. This issue is for all intermediate distorted line 

## Actual Behavior
fill this out
When pressing with right/left arrow in line chart tooltip previous dot tooltip is appearing
## Expected Behavior

When pressing with right/left arrow in line chart tooltip should be updated corresponding to the dot
fill this out
[](url)

### Requested priority

High

### Products/sites affected

Microsoft

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by rsoni0809** [comment]
@msft-fluent-ui-bot Could you please let me know if any ETA for this?

**Comment by smhigley** [comment]
@Raghurk -- would you be able to take a look at this one?

**Comment by AtishayMsft** [comment]
@Shubhabrata08 FYI
