### ISSUE TITLE
[Bug]: TagPicker onResolveSuggestions not triggered in React 18 using createRoot

### ISSUE THREAD

**Issue by mrmonday** [microsoft/fluentui#25441]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Reproduces in the sandbox and on my dev machine.
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/elated-jackson-21qury

### Bug Description

Modify the `useCreateRoot` boolean in the `index.js` reproduction to toggle working/non-working behaviour.

## Actual Behavior

`onResolveSuggestions` is not called when text is entered in the tag picker when using React 18's `createRoot` API.

## Expected Behavior

`onResolveSuggestions` should called when text is entered in the tag picker when using React 18's `createRoot` API.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
Related to #22592 and possibly #24093

I'm guessing the issue is this, in `componentDidMount`:
```ts
this._onResolveSuggestions = this._async.debounce(this._onResolveSuggestions, this.props.resolveDelay);
```

**Comment by micahgodbolt** [comment]
Also note that this only happens in Strictmode

**Comment by OneCyrus** [comment]
this issue is blocking us from updating to react 18. did anyone look deeper into this yet? or is someone aware of a workaround without disabling strict mode?

**Comment by mrmonday** [comment]
This is still an issue, and should not have been closed.

**Comment by khmakoto** [comment]
Reopening
