### ISSUE TITLE
[Bug]: V8 ThemeProvider doesn't work with v9 FluentProvider

### ISSUE THREAD

**Issue by sanjaydebnath** [microsoft/fluentui#25454]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 2.42 GB / 15.92 GB
  Browsers:
    Edge: Spartan (44.22621.674.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/naughty-edison-1kryml

## Actual Behavior
My main project uses v9 components with theming enabled (using FluentProvider), which works fine. Now when I use a v8 component like a TimePicker component inside a V9 component but with old v8 ThemeProvider, the theming of v8 component doesn't work. Like if I set the FluentProvider to use dark theme (for v9) and also set the ThemeProvider for v8 component to use dark theme, it doesn't work. Also no error is reported anywhere in console.

## Expected Behavior
V8 component should respect its own parent theming.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
Hi @sanjaydebnath, you have to do a bit more than you did to make a v8 theme dark. You can see how I'm importing a `Dark` theme from `@fluentui/theme-samples` and making it work in an updated fork of your codesandbox above.

https://codesandbox.io/s/adoring-brattain-ylyn7k?file=/src/V8.tsx

Let me know if you need any more help.

**Comment by sanjaydebnath** [comment]
> Hi @sanjaydebnath, you have to do a bit more than you did to make a v8 theme dark. You can see how I'm importing a `Dark` theme from `@fluentui/theme-samples` and making it work in an updated fork of your codesandbox above.
> 
> https://codesandbox.io/s/adoring-brattain-ylyn7k?file=/src/V8.tsx
> 
> Let me know if you need any more help.

Thanks a lot. I'll follow the sample to understand more on how to add the v8 dark/light themes in my project (as the sample seems not to be used in production app). This helps a lot.

**Comment by khmakoto** [comment]
@sanjaydebnath for sure, let us know if you need help with anything else! Otherwise, feel free to close this issue. Thanks! 😄
