### ISSUE TITLE
[Bug]: State of the selected item is not announced in Dropdown component

### ISSUE THREAD

**Issue by luckyrass** [microsoft/fluentui#25502]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
OS: Window 11 Version 21H2 (OS Build 22471.1000)
Edge Dev: Version 96.0.1028.0 (Official build) dev (64-bit)
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/luckyrass/pen/qBKZyyd

### Bug Description

There is an accessibility issue in the dropdown component.  State of the selected item is not announced in Dropdown component
![image](https://user-images.githubusercontent.com/12230173/199665800-a22fe693-f314-4937-8f69-df9775e292cb.png)

## Actual Behavior
NVDA is announcing "30 days 30 days 2 of 4".

## Expected Behavior

NVDA should announce "30 days selected 2 of 4".

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@luckyrass this is a very common misconception 😊. NVDA and JAWS both will announce "not selected" for options in a listbox that are not selected, but will not explicitly say "selected" for items that are selected.

This is the screen reader software's own UX decision, and is consistent across the web -- there is nothing Fluent or a web developer can do to change that announcement in this specific type of control.

Hope that helps!
