### ISSUE TITLE
[Feature]: Disable today highlight in Calendar / allow to change its style

### ISSUE THREAD

**Issue by simonenkoav** [microsoft/fluentui#25506]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

I want to select days not in ranges but in a custom way by clicking on each day. So to show selection I want to color selected days — but class name or style of "today" day does not seem to be editable (I cannot change background or text color).

### Have you discussed this feature with our team

No

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by simonenkoav** [comment]
My bad: class name is actually editable, I solved my task.

**Comment by smhigley** [comment]
Hi! The style key for the today button is `dayIsToday`, and it can be added to Calendar's `calendarDayProps.style` object.

This example code will override the today button's background color to be red:

```tsx
const customStyles: ICalendarDayGridStyles = {
  dayIsToday: {
    backgroundColor: 'red'
  }
};

export const CalendarInlineExample: React.FunctionComponent = () => {
  const [selectedDate, setSelectedDate] = React.useState<Date>(new Date());

  return (
    <div style={{ height: '360px' }}>
      <div>Selected date: {selectedDate?.toLocaleString() || 'Not set'}</div>
      <Calendar
        showGoToToday
        onSelectDate={setSelectedDate}
        value={selectedDate}
        calendarDayProps={{ styles: customStyles }}
        // Calendar uses English strings by default. For localized apps, you must override this prop.
        strings={defaultCalendarStrings}
      />
    </div>
  );
};
```

Hope that helps!

**Comment by smhigley** [comment]
ah, just saw you were able to solve it :D
