### ISSUE TITLE
[Bug]: fluentui/TimePicker onChange handler is giving a Date that is inconsistent with the input string 

### ISSUE THREAD

**Issue by nipothar** [microsoft/fluentui#25508]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 17.85 GB / 31.59 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.26)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codepen.io/nipothar/pen/RwJRwwN?editors=1111

## Actual Behavior

Given that onFormatDate and onValidateUserInput are specified. We are using the timePicker as a form field using the react-final-form to be specific. 

When the user inputs something like "07:000" or "07:00 Ax" the onChange handler for the component resolves these to be a valid date with the time as 07:00 AM when it should be an invalid date instead.

So, in these scenarios, although onValidateUserInput has an error, the onChange handler of the TimePicker returns a valid date. 

When this happens and the form field validator is triggered after the field value is updated to the date, the validation succeeds because the date is valid while instead it should return an error. 

This is causing a lot of dependency issues for us to handle the inconsistency between what the onValidateUserInput is giving vs what the date is coming from onChange handler even if the string is invalid.  Essentially, the user does not know what the date it resolved to is because the string is invalid but there is no error displayed. 

## Expected Behavior

The expected behavior should be for the Date from the component onChange function to be invalid if the input string is invalid. 

Especially if onValidUserInput and onFormatDate is enabled. 

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@nipothar can you please provide exact reproduction steps for your Codepen?

- I selected "11:30", "onChange" is triggered with a `Date` object (Thu Nov 25 2021 11:30:00 GMT+0100 (Central European Standard Time))
- I selected "11:0", "onChange" is triggered with a `Date` object (**Invalid Date**)

The same happens when I use keyboard. If I type manually "06:000", `onChange` is not triggered.

It looks that it already works as you expect. Can you please check?
