### ISSUE TITLE
How to add data-* attribute to IButtonProps

### ISSUE THREAD

**Issue by kmkaliraj** [microsoft/fluentui#25518]
### Discussed in https://github.com/microsoft/fluentui/discussions/25517

<div type='discussions-op-text'>

<sup>Originally posted by **kmkaliraj** November  3, 2022</sup>
Hi,

  I'm trying send data attributes along with IButtonProps.
buttonProps={{
              id: StudioTourHooks.NEW_TABLE_BUTTON,
              text: formatMessage({ id: LocalizationConstant.TABLE }),
              onClick: AddTableButtonClick,
              ariaLabel: formatMessage({ id: LocalizationConstant.ADD_TABLE_BUTTON_ARIA_LABEL }),
              iconProps: { iconName: IconNames.Add },
              [`data-testid`]: {dataWorkspace.panel.addNewTable},
            }}

Gettig this following error.

 Object literal may only specify known properties, and '[`data-testid`]' does not exist in type 'IButtonProps'.ts(2322)</div>

**Comment by smhigley** [comment]
Answered in the discussion thread :). Closing this as a discussion rather than an issue.
