### ISSUE TITLE
[Bug]: createFocusOutlineStyle works weird on Firefox when with ul & li

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#25511]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 17.96 GB / 31.91 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.41)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/compassionate-waterfall-ocpwq5?file=/example.tsx

## Actual Behavior

On Firefox:

![image](https://user-images.githubusercontent.com/39588094/199807410-2ae1155d-82b2-4141-be89-90ea809b1c96.png)

## Expected Behavior

On edge / chrome, it works fine as expected:

![image](https://user-images.githubusercontent.com/39588094/199807589-810e1605-aa20-4518-a0fb-fe7ba2ce2087.png)

**Note**: 
We need ul & li for accessibility. 

**Code snippet**:
```
import {
  createFocusOutlineStyle,
  Link,
  LinkProps,
  makeStyles,
  Text
} from "@fluentui/react-components";
import * as React from "react";

const useStyles = makeStyles({
  focusIndicator: {
    ...createFocusOutlineStyle(),
    position: "relative"
  }
});

export const Default = (
  props: LinkProps & {
    as?: "a";
  }
) => {
  const styles = useStyles();

  return (
    <div>
      <ul
        style={{
          display: "flex",
          flexDirection: "column",
          rowGap: "20px",
          width: "100%",
          paddingInlineStart: "0"
        }}
      >
        <li style={{ listStyleType: "none" }}>
          <Link href="https://www.bing.com" className={styles.focusIndicator}>
            <div className="some">
              <span>This is icon</span>
              <Text>This is a link</Text>
            </div>
          </Link>
        </li>
      </ul>
    </div>
  );
};

```

Our current versions:

React ^16.14.0
Fluentui ^9.0.1
typescript: ^4.5.3

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by flora8984461** [comment]
I found a workaround is to add createFocusOutlineStyle() to li element. But still hope to see if this issue get fixed.

**Comment by smhigley** [comment]
This looks like a bug in how Firefox is computing the content edges of a relatively positioned ancestor when it is inline. If you apply a `display` value to the link of block or inline-block, the issue no longer appears.

For reference, here's the CSS spec on how to calculate the box of an inline relatively positioned ancestor: https://www.w3.org/TR/css-position-3/#def-cb. Based on that, it seems Chrome is doing the correct thing, but Firefox is not in this case.

I think we have two options: modify the focus outline style to work with inline elements on Firefox, or provide an easy workaround for now, and log a bug on Firefox.

**Comment by flora8984461** [comment]
@smhigley thank you for your help. I am adding a display value to the link of block as my solution.

In addition, it would be great if we can log a bug on Firefox. Will your team do it, or would you mind guiding me how to log a bug on Firefox? Thank you!

**Comment by flora8984461** [comment]
@smhigley by "modify the focus outline style to work with inline elements on Firefox", do you mean fluentui will modify it or we do it on our own?  Thank you!
