### ISSUE TITLE
[Bug]: tooltip not working in React 18 & StrictMode (works fine without StrictMode)

### ISSUE THREAD

**Issue by Tim91084** [microsoft/fluentui#25534]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 7.47 GB / 15.89 GB
  Browsers:
    Chrome: 106.0.5249.119
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.26)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codepen.io/timothy-macintyre/pen/rNKLZZO

## Actual Behavior
Tooltip should display in strict mode

## Expected Behavior
Tooltip does not display

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Tim91084** [comment]
The DetailsList also has issues on initial render sizing, resizing columns, and moving columns.

**Comment by smhigley** [comment]
This seems related to the issue #24041 and PR #24093

tagging @micahgodbolt since you may have more insight into this one
