### ISSUE TITLE
[Bug]: Text wrappers lack proper documentation explaining usage and motivation

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#25548]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a documentation bug
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-text--default

## Actual Behavior
Text documentation shows the wrappers and their styles, but does not explain the concept/purpose of the wrappers, nor show much documentation on the usage. 

## Expected Behavior
The wrappers with fixed styles is a new concept, we should explain it, and explain it's motivation. 

See #24341 for issue filed on this.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
can we improve title of this issue ?
