### ISSUE TITLE
[Bug]: FATAL ERROR running out of heap memory when using FluentUI v9, adding `<FluentProvider>` component increases project memory footprint by almost 3GiB

### ISSUE THREAD

**Issue by KerimG** [microsoft/fluentui#25547]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 373.77 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 106.0.3
    Firefox Developer Edition: 107.0
    Safari: 16.1
 Node.js verion: 18.12.1
```

### Reproduction

https://github.com/KerimG/cra-fluentui-problem

## Actual Behavior
I created a React project using CRA and the TypeScript template, as described [here](https://create-react-app.dev/docs/adding-typescript/).

Then followed the [Fluent UI React components quick start](https://react.fluentui.dev/?path=/docs/concepts-developer-quick-start--page) up to the first code block (added added the <FluentProvider> component).

`npm run start` takes unusually long to start and after 30-60 seconds of successfully starting and opening the browser, the script crashes with the following output.

## Expected Behavior
The project to compile successfully and being able to use FluentUI components in the React project.

### Logs

```shell
Compiled successfully!

You can now view my-app in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.2.100:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

webpack compiled successfully
No issues found.

<--- Last few GCs --->

[53613:0x120078000]    98421 ms: Mark-sweep (reduce) 1980.7 (2033.3) -> 1980.7 (2033.0) MB, 348.2 / 0.0 ms  (average mu = 0.276, current mu = 0.000) last resort; GC in old space requested
[53613:0x120078000]    98778 ms: Mark-sweep (reduce) 1980.7 (2033.0) -> 1980.7 (2033.0) MB, 356.8 / 0.0 ms  (average mu = 0.162, current mu = 0.000) last resort; GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x1026e6200 node::Abort() [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
 2: 0x1026e63f0 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
 3: 0x10282c8ec v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
 4: 0x1029cb4c8 v8::internal::MemoryController<v8::internal::V8HeapTrait>::MinimumAllocationLimitGrowingStep(v8::internal::Heap::HeapGrowingMode) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
 5: 0x1029b0328 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
 6: 0x1029a7f30 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
 7: 0x102c5214c v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
 8: 0x102d38fdc v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
 9: 0x10308d04c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
10: 0x103064108 Builtins_MapPrototypeSet [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
11: 0x1085baaa0
12: 0x1085db170
13: 0x1085de134
14: 0x1085dd374
15: 0x1085daf78
16: 0x1085d673c
17: 0x1085daf78
18: 0x1085cbba0
19: 0x1085d1868
20: 0x1085d2238
21: 0x1085d1a9c
22: 0x1085dd374
23: 0x1085daf78
24: 0x1085cbba0
25: 0x108451354
26: 0x108009160
27: 0x10800a5a8
28: 0x103018198 Builtins_InterpreterEntryTrampoline [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
29: 0x103018198 Builtins_InterpreterEntryTrampoline [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
30: 0x108009160
31: 0x103018198 Builtins_InterpreterEntryTrampoline [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
32: 0x103018198 Builtins_InterpreterEntryTrampoline [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
33: 0x103018198 Builtins_InterpreterEntryTrampoline [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
34: 0x10801c33c
35: 0x103018198 Builtins_InterpreterEntryTrampoline [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
36: 0x10801c33c
37: 0x103018198 Builtins_InterpreterEntryTrampoline [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
38: 0x103049ef4 Builtins_AsyncFunctionAwaitResolveClosure [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
39: 0x1030d86f8 Builtins_PromiseFulfillReactionJob [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
40: 0x10303bc4c Builtins_RunMicrotasks [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
41: 0x1030163a4 Builtins_JSRunMicrotasksEntry [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
42: 0x102958e7c v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
43: 0x10295936c v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
44: 0x102959548 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
45: 0x10297fc18 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
46: 0x1029804b0 v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
47: 0x102630c4c node::InternalCallbackScope::Close() [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
48: 0x102630fc8 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
49: 0x1026458ec node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
50: 0x1026eab34 node::fs::FSReqCallback::Resolve(v8::Local<v8::Value>) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
51: 0x1026eb0ec node::fs::AfterNoArgs(uv_fs_s*) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
52: 0x1026e27b0 node::MakeLibuvRequestCallback<uv_fs_s, void (*)(uv_fs_s*)>::Wrapper(uv_fs_s*) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
53: 0x102ff4d28 uv__work_done [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
54: 0x102ff84c4 uv__async_io [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
55: 0x10300a210 uv__io_poll [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
56: 0x102ff8954 uv_run [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
57: 0x1026316d4 node::SpinEventLoop(node::Environment*) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
58: 0x102721128 node::NodeMainInstance::Run() [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
59: 0x1026b4ec8 node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
60: 0x1026b5190 node::Start(int, char**) [/Users/kg/.nvm/versions/node/v18.12.1/bin/node]
61: 0x194163e50 start [/usr/lib/dyld]
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by KerimG** [comment]
I tried running the same on a Windows machine with more RAM and managed to get it running, though the compilation step takes several minutes.

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
    Memory: 20.96 GB / 31.91 GB
  Browsers:
    Chrome: 107.0.5304.88
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.35)
    Internet Explorer: 11.0.19041.1566
  Node.js verion: 18.12.1
```

What I noticed is that after adding FluentUI, the project needs over 3GB of RAM. 

![image](https://user-images.githubusercontent.com/9061713/200140834-179f3fed-6b3b-439b-aa7e-b0aa5a7b3080.png)

Simply removing the `<FluentProvider>` component, improves compilation time enormously and reduces memory footprint to ~300MB:
![image](https://user-images.githubusercontent.com/9061713/200140922-f422264c-b918-4271-9711-0a741abfb5a4.png)

**Comment by Hotell** [comment]
I can repro this to some extent.

1st cold start after `npm i` ( I'm on mac M1 ) takes around 40ish seconds.

**Comment by KerimG** [comment]
Thanks a lot @Hotell ! 

Trying it out with `yarn` did improve initial boot and more importantly recompilation speeds on my Windows machine. I will later try it out on my Mac, as well. The memory footprint is also only about 1/10 - 1/9 of what it was before. 

I am not sure if I want to switch to `yarn` yet and as such I am not 100% convinced that this is a long-term solution but it's perfectly sufficient for my local prototyping.

**Comment by jsancho** [comment]
Disabling source map generation has been key for me `GENERATE_SOURCEMAP=false`
Mind that I had been using fluent v9 for a couple of weeks without any problems.

After upgrading to the latest version of the packages `yarn start` has been consistently aborting with node heap out of memory.

"@fluentui/react": "8.103.0" => "@fluentui/react": "8.104.1"
"@fluentui/react-components": "^9.7.1" => "@fluentui/react-components": "^9.7.4"
"@fluentui/react-icons": "^2.0.187" => "@fluentui/react-icons": "^2.0.190"

That is, react-components 9.7.1 and react-icons 2.0.187 were working just fine, upgrading to the versions above causes the out of memory exception.

I'm using a PC with 64GB of memory and I the node process has 8GB assigned with `max_old_space_size`.
node version `16.19.0`

**Comment by flora8984461** [comment]
In my case I am not sure if `GENERATE_SOURCEMAP` works for me. I use Playwright (which uses rollup and the config is blackbox for me). 
I have a re-produce code described in https://github.com/microsoft/playwright/issues/22937. 
I am seeking for suggestions how to make it work with Playwright. Thank you 🙏

**Comment by c33k** [comment]
Try this, maybe it may help:

I got the same issue using @fluent-ui/react-components@9.19.1 and 9.20.0.

Initially I set NODE_OPTIONS with --max_old_space_size=8192 and this helped the tests pass on our pipelines.

I made some heap analysis on my machine and confirmed that there is memory leak on my tests related to icons (the whole icons strings are copied multiple times).

I got the version of react-icons that @jsancho mentioned that works and forced an override on my package.json:

```json
"overrides": {
    "@fluentui/react-icons": "2.0.187"
}
```
I also ran JEST with --runInBand argument.

After running the tests, the memory usage went down by +-50% and I could remove the NODE_OPTIONS variable.

This, of course, is just a workaround for it to work in my scenario and that may help someone else with the same problem.

**Comment by jsancho** [comment]
For what is worth, we managed to workaround this problem by migrating from create react app to [vite](https://vitejs.dev/).

We did not only avoid those memory exceptions, it also massively improved the start-up speed of the project and it made it possible for devs on "lower-end" laptops to have a snappy hot reloading experience.

Strongly recommend migrating away from CRA if you can afford to invest the time, it will definitely pay off in the long term.

**Comment by 15MariamS** [comment]
Running `yarn dedupe` fixed the issue for me. My upgrade caused my dependency tree to contain redundant versions of `@fluentui/react-icons`.
