### ISSUE TITLE
[Bug]: createCustomFocusIndicatorStyle works weird when with div & Link

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#25565]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 17.96 GB / 31.91 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.41)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/focused-andras-tlr9jj?file=/example.tsx

## Actual Behavior

The box-shadow and outline styles only shows 2 corners as the screenshot shows:

![image](https://user-images.githubusercontent.com/39588094/200439431-440e62bb-2d1f-43f8-a8b5-342d2adab514.png)

## Expected Behavior

Expect to have box-shadow and outline styles as the screenshot shows:

![image](https://user-images.githubusercontent.com/39588094/200439824-2a76e4af-fb38-426c-b179-d4d2ecc7e805.png)

**Note:**
We add inner div with purpose.

**What I tried:**
I tried to change "div" to "slot" in codesandbox, it fixes but in our codebase but still does not work. 

This is similar but not the same as: 
https://github.com/microsoft/fluentui/issues/25511

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@flora8984461 this is because a link is an inline element by default, and a `<div>` is a block-level element. If you nest block-level elements inside of inline elements, you may get odd side effects. If you try to style the link's `background-color` you'll see the same issue -- it doesn't show up.

You can fix this by setting `display: block|inline-block|flex|inline-flex|etc.` on the link, or by using a `<span>` instead of a `<div>`.

Hope that helps!

**Comment by flora8984461** [comment]
@smhigley thank you so much for your help! 

I think this is on us (users) to decide the styles? I think there is nothing fluentui team can do for this one? If so, please feel free to close it. thanks!
