### ISSUE TITLE
[Bug]: ShimmeredDetailsList can't load all items when parent node has 'overflow-y: overlay' style

### ISSUE THREAD

**Issue by wshxj123** [microsoft/fluentui#25571]
### Environment Information

- **Package version(s)**: (fill this out) latest 8.100.0
- **Browser and OS versions**: (fill this out if relevant) Chrome Win11

#### Actual behavior:

ShimmeredDetailsList can't load all items. And there is a blank area at the bottom.
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/5541417/200580480-8fe28f68-9bf4-45e5-8be4-a4ed943e2bfd.png">

#### Expected behavior:

Load all items normally.

### If applicable, please provide a codepen repro:

https://codepen.io/wshxj123/pen/NWzbeXX

There is only one difference with the [document](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/shimmer). I **add styles `style="height: 100vh;overflow-y: overlay;"`**
<img width="381" alt="image" src="https://user-images.githubusercontent.com/5541417/200577397-7f3c1083-342a-400a-906a-1c5481e09cd2.png">

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
Our Teams app

**Comment by smhigley** [comment]
@wshxj123 when adding a different scrollable parent to a virtualized container, add `data-is-scrollable="true"` to the node so the virtualized list knows where to listen for scroll events.

If you update the `<div>` in your Codepen to this, it works:
```html
<div id="content" style="height: 100vh; overflow-y: scroll" data-is-scrollable="true"></div>
```

(as a side note, guessing this was just a typo, but `overlay` is not a valid value for `overflow` styles -- the possible values are `visible`|`hidden`|`scroll`|`auto`)

Hope that helps!
