### ISSUE TITLE
Icon Tool - Error when embedding Icons - All kind of fonts being loaded

### ISSUE THREAD

**Issue by JotFX** [microsoft/fluentui#25572]
Dear Folks,

I have an issue with embedding the icons into my project. Let me explain:

### Environment Information

- **Package version(s)**: @fluentui/react: 8.96.1 + @uifabric/styling: 7.21.1
- **Browser and OS versions**: Windows 11 and Chrome current or Firefox current

### Describe the issue:

I am developing a custom visual for Power BI. I am using Fluent UI in my project for the UI. The big caveat now is, that I am not allowed to use external resources, so I have to bundle everything into the final package. I am using the default webpack configuration provided by the custom visuals team.
To keep bundle size as low as possible, I am creating a TS file with the following content, including the inline CSS. 
`
// tslint:disable:max-line-length
import {IIconOptions, IIconSubset, registerIcons} from '@uifabric/styling';

export function initializeIcons(
    baseUrl: string = '',
    options?: IIconOptions
): void {
    const subset: IIconSubset = {
        style: {
            MozOsxFontSmoothing: 'grayscale',
            WebkitFontSmoothing: 'antialiased',
            fontStyle: 'normal',
            fontWeight: 'normal',
            speak: 'none'
        },
        fontFace: {
            fontFamily: `"InnofallsIcons-22-08"`,
            src: `url('data:application/octet-stream;base64,d09GRgA ...... AA==') format('truetype')`
        },
        icons: {
            'AddBookmark': '\uF5B7',
            'ArrowUpRight': '\uF069',
            'AutoEnhanceOn': '\uE78D',
            'BarChartHorizontal': '\uE9EB',
            'BarChartVertical': '\uE9EC',
            'BookmarkReport': '\uF76B',
            'ChartSeries': '\uF513',
            'CheckMark': '\uE73E',
            'ChevronDown': '\uE70D',
            'ChevronRight': '\uE76C',
            'Clicked': '\uF268',
            'ColorSolid': '\uF354',
            'DrillExpand': '\uF534',
            'EraseTool': '\uE75C',
            'History': '\uE81C',
            'Info': '\uE946',
            'More': '\uE712',
            'Redo': '\uE7A6',
            'ReviewRequestSolid': '\uF356',
            'Save': '\uE74E',
            'SeeDo': '\uE808',
            'StackedColumnChart2': '\uF666',
            'Undo': '\uE7A7',
            'Up': '\uE74A',
            'Zoom': '\uE71E',
            'ZoomIn': '\uE8A3'
        }
    };
    registerIcons(subset, {disableWarnings: true});
}
`

This works fine so far, the icons are loaded and shown correctly. BUT I often get the following errors in the console:

**Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.**

**Tspan.js:32 Refused to load the font 'https://static2.sharepointonline.com/files/fabric/assets/fonts/leelawadeeui-thai/leelawadeeui-light.woff2' because it violates the following Content Security Policy directive: "default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.**

... and so forth.

#### Actual behavior:

Fluent UI seems to try to load all kind of asian fonts, which are hardcoded in 
"node_modules/@fluentui/react/dist/css/fabric.css"

#### Expected behavior:

Fluent UI should not try to load the asian fonts. I don't need them anyway.

### If applicable, please provide a codepen repro:

Without the whole Power BI SDK it's hard to create a repro case. I hope for a solution without :)

### Priorities and help requested (not applicable if asking question):

Prio is pretty high for me, as the product cannot be published with errors in the console.

So how can I prevent all those files being loaded by Fluent UI?

All the best
Jonas

**Comment by smhigley** [comment]
@JotFX the [@uifabric/styling](https://www.npmjs.com/package/@uifabric/styling) package is the older styling package that was moved to [@fluentui/style-utilities](https://www.npmjs.com/package/@fluentui/style-utilities) with the move to the `@fluentui` scope in v8.

Since I see you're using `@fluentui/react` v8, could you try importing the icons from `@fluentui/style-utilities` and then let us know if the issue persists? Looking at npm, it appears `@uifabric/styling` is only being updated with the v7 versions, and I'm not sure how that works with our v8 components.

**Comment by JotFX** [comment]
Dear Sarah,

this change didn't bring any success.

What I like to prevent is, that Fluent UI is loading all default fonts in the beginning, even if they are not needed.
There are several DefaultFontStyles.js file in the node modules, which are all loading the default fonts. As in Power BI no external resources may be accessed, I get those errors.

Is there any way to prevent Fluent UI loading those fonts, other than monkey patching to whole thing with webpack?

All the best 
Jonas

**Comment by JotFX** [comment]
Dear Sarah,

this change didn't bring any success.

What I like to prevent is, that Fluent UI is loading all default fonts in the beginning, even if they are not needed.
There are several DefaultFontStyles.js file in the node modules, which are all loading the default fonts. As in Power BI no external resources may be accessed, I get those errors.

Is there any way to prevent Fluent UI loading those fonts, other than monkey patching to whole thing with webpack?

All the best 
Jonas
