### ISSUE TITLE
[Bug, Accessibility] Narrator skips the first item in a contextual menu

### ISSUE THREAD

**Issue by mgtk77** [microsoft/fluentui#25584]
### Environment Information

- **Package version(s)**: UI React 8.101.0
- **Browser and OS versions**: Edge 107.0.1418.35, Windows 11

#### Actual behavior:
When Windows narrator is open, and using the keyboard for navigation, then opening a contextual menu and pressing the keyboard down button, the second item will be selected instead of the first one. 

#### Expected behavior:
The first item should be selected. 

### If applicable, please provide a codepen repro:

https://codepen.io/mgtk77/pen/MWXbxge

(CodePen was created only by using the "Export to Code" on your documentation site: https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu
I didn't change anything.

Attached a video of the bug from your documentation site. 

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

https://user-images.githubusercontent.com/48786769/200818607-03993b8f-d627-4500-96f3-d7ab2b97627a.mp4

**Comment by smhigley** [comment]
This was a [Narrator bug](https://microsoft.visualstudio.com/OS/_workitems/edit/39043405) that caused it to skip the first item in a container when navigating in scan mode. It has been fixed, and should be available in the version of Windows released after the fix.

Generally menus will be used in app mode, not scan mode, so this should not have much impact on the ContextualMenu control. I noticed that in the video you were navigating options in scan mode -- I'd suggest switching modes (or allowing Narrator to auto-switch, though that is sometimes buggy), and this particular bug will no longer be an issue there.

**Comment by mgtk77** [comment]
Hey,

I see that the narrator bug you mentioned still has "Active" status - how do you know it was fixed? Do you know what is the expected Windows version that will have the fix?

**Comment by smhigley** [comment]
@mgtk77 ah my bad, I got it mixed up with another bug with Narrator skipping nodes in a popup in scan mode that was fixed in March 🙈.

Looks like that one's still open, but I'd still recommend referencing it in your own bug, assuming you have one. In practice, there's nothing either of us can do to fix this on our side -- the fix would need to come from Narrator.
