### ISSUE TITLE
[Feature]: GroupedList to have pagination or load items on scroll

### ISSUE THREAD

**Issue by kroudams** [microsoft/fluentui#25586]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Allow items to be loaded on scroll (or any other way) for pagination implementation. I would love to have an option to load more items, let's say on scroll.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JustSlone** [comment]
@kroudams, so I understand correctly you are asking for some way to be notified that you should load new items from the server as someone scrolls through the list? Something like an infinite scroll behavior?

We aren't adding new features to our existing GroupedList, but we are working on a refactor/update for Lists, Tables, Trees, Grids, as part of v9. This is a good feature to consider as part of that, and this could be in our component implementation or perhaps in our virtualizer implementation. 

CC: @ling1726, @bsunderhus @mitch-at-work
