### ISSUE TITLE
[Bug]: Button hover in highcontrast fickers colors

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#25591]
### Library

React Components / v9 (@fluentui/react-components)

### Are you reporting Accessibility issue?

yes

### Reproduction

https://react.fluentui.dev/?path=/docs/components-button-button--default

### Bug Description

in high contrast mode there is a light flicker on hover before the button turns to the specified color

![hc-buttons](https://user-images.githubusercontent.com/1434956/200900873-ea58a63a-c4cf-4ac4-949e-6d56d767c550.gif)

**Comment by khmakoto** [comment]
Initial investigation leads to 2 possible theories on the culprit of the flashing:

1. The `prefers-reduced-motion` setting, which can possible be enabled by remote desktop.
2. `forcedColorAdjust: none` in high contrast on hover only may not possibly animate properly.
