### ISSUE TITLE
ChoiceGroup - checked attribute not updating in HTML

### ISSUE THREAD

**Issue by techtor** [microsoft/fluentui#25605]
### Environment Information

- **Package version(s)**: 8.101.0
- **Browser and OS versions**: Edge 109.0.1481.0, Windows 11 22000.1219

### Describe the issue:

When selecting different radio buttons inside a ChoiceGroup, everything updates visually, but the `checked` attribute does not change on the relevant `input` elements. This creates complications when doing validations in UTs, but it also may be an accessibility issue if the screen reader falls back to `checked` when `aria-checked` is unavailable.

Repro steps:
1. Go to https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup
2. Look at Option B for the Basic ChoiceGroup in the Elements pane of browser dev tools
![image](https://user-images.githubusercontent.com/421682/200994767-b0894ac4-47a4-4b76-8835-51c01e6659eb.png)
3. Select Option A.
4. Look at Option B in the Elements pane again.
![image](https://user-images.githubusercontent.com/421682/200994902-02fa3d8d-17d8-44e5-b249-9907f60f290d.png)

#### Actual behavior:

Option B keeps the `checked` attribute even though Option A is selected. Option A does not have the `checked` attribute even though it's selected.

#### Expected behavior:

`checked` attribute appears on the selected element, and does not appear on an element that is not selected.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Sure, although I've never worked in this codebase before.

Requested priority: Normal. This has the potential to be an accessibility issue, but engineers can code around this. Engineers can also code around potential validation difficulties using other attributes/selectors.

Products/sites affected: Any site using ChoiceGroup.

**Comment by smhigley** [comment]
@techtor this is actually just how the HTML `checked` attribute works. The HTML attribute itself does not reflect the IDL value (i.e. what the browser stores as `element.checked` if you were to get it through DOM APIs).

You can see the same behavior here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

This is expected, and not an accessibility or other issue. Hope that helps!
