### ISSUE TITLE
[Bug]: Selection is not working properly

### ISSUE THREAD

**Issue by bhanu345-cmd** [microsoft/fluentui#25610]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
@fluentui/react:8.77.3
react : 18.0.0
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/inspiring-carson-s575yk

## Actual Behavior
On selection item should be selected

## Expected Behavior
On selection item is not getting selected

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
There are few reasons why this example doesn't work:

1. The component needs to be rerendered when the selection changes
2. React strict mode is being used

The `DetailsList` API is pretty awful for selection, and unfortunately it's just how it was designed to work so nothing too much can be done there.

Here is a sandbox where this works without strict mode: https://codesandbox.io/s/wild-flower-3t134x?file=/src/App.tsx

I've made another example where userland code is strict mode compliant, but it seems the `DetailsList` just doesn't work in strict mode either  https://codesandbox.io/s/little-shadow-jptju2?file=/src/App.tsx

cc @micahgodbolt  who has been looking into react 18 support
