### ISSUE TITLE
[Bug]: during v9 release react-northstar package.json was not update - causing broken master

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#25637]
### Library

React Components / v9 (@fluentui/react-components)

### Reproduction

https://github.com/microsoft/fluentui/pull/25636

## Actual Behavior

v9 release was triggered bump to v9 package which is used as dependency in react-northstar. This bump was not reflected in react-northstar package.json, thus release failed and we got master in invalid state.

## Expected Behavior
react-northstar package.json should be updated during release if appropriate

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
@Hotell  duplicate of #25316 ?

**Comment by Hotell** [comment]
ah indeed ! ty
