### ISSUE TITLE
[Bug]: Group Row selects item when SelectionMode is set to single

### ISSUE THREAD

**Issue by dggsax** [microsoft/fluentui#25647]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Xeon(R) W-2145 CPU @ 3.70GHz
    Memory: 55.32 GB / 95.73 GB
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/danigon-msft/pen/LYrLYoe

## Actual Behavior
The DetailsList has the prop `selectionMode={SelectionMode.single}`. When I select a group header, like `Color: "red" (2)`, the last item in the group, "b", is selected.

## Expected Behavior
Let me know if this is the expected behavior, but since the selection mode is to select a single item, intuitively I would imagine that the user would have to click the item directly to select the item, and that clicking the group header row would have no impact on the selection.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
This seems to be a regression and only starts to occur from `@fluentui/react@8.88.0`

* 8.88.0: https://codepen.io/ling1726/pen/ZERJWao
* 8.87.2: https://codepen.io/ling1726/pen/NWzvNXj

**Comment by NguyenVanBay101097** [comment]
Yes, I also have this bug in new version. so any people have an idea for resolve this issue?

**Comment by NguyenVanBay101097** [comment]
> This seems to be a regression and only starts to occur from `@fluentui/react@8.88.0`
> 
> * 8.88.0: https://codepen.io/ling1726/pen/ZERJWao
> * 8.87.2: https://codepen.io/ling1726/pen/NWzvNXj

so, what should we do for new version ???
