### ISSUE TITLE
[Bug]: Type 'IAppStyles' does not satisfy the constraint 'IStyleSet<IAppStyles>'.

### ISSUE THREAD

**Issue by mishabutuzov** [microsoft/fluentui#25648]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 18.73 GB / 31.85 GB
  Browsers:
    Chrome: 107.0.5304.107
    Internet Explorer: 11.0.17763.1852




    "@fluentui/react": "8.96.0",
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/github/mishabutuzov/Issue001/draft/eloquent-lamport?file=%2Fsrc%2Fcomponents%2FApp%2FApp.types.ts&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A19%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522claf1nm5j000bl3dhcr3p6k4x%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522claf222kg028p356myqxfl075%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Atrue%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522claf222kg028q356mc51et02j%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

## Actual Behavior
Typescript error when defining Panel type:

export interface IAppStyles {
    sidebarPanel: Partial<IPanelStyles>;
}

![error](https://user-images.githubusercontent.com/20751556/201529928-28394f26-5ebe-45d4-be42-c3ca0359005c.JPG)
![error2](https://user-images.githubusercontent.com/20751556/201529931-2eb91d34-d69c-4534-a8ba-5dcc24d8d7e5.JPG)

## Expected Behavior
No Typescript  errors when defining Panel type this way:

export interface IAppStyles {
    sidebarPanel: Partial<IPanelStyles>;
}

### Logs

```shell
Compiled with problems:X

ERROR in src/components/App/App.types.ts:7:53

TS2344: Type 'IAppStyles' does not satisfy the constraint 'IStyleSet<IAppStyles>'.
  Type 'IAppStyles' is not assignable to type '{ contentStack: IStyle; sidebarPanel: IStyle; }'.
    Types of property 'sidebarPanel' are incompatible.
      Type 'Partial<IPanelStyles>' is not assignable to type 'IStyle'.
        Type 'Partial<IPanelStyles>' is not assignable to type 'IRawStyle'.
          Types of property 'content' are incompatible.
            Type 'IStyle' is not assignable to type 'string | undefined'.
              Type 'null' is not assignable to type 'string | undefined'.
     5 |     title: string;
     6 |     theme?: ITheme;
  >  7 |     styles?: IStyleFunctionOrObject<IAppStyleProps, IAppStyles>;
       |                                                     ^^^^^^^^^^
     8 | };
     9 |
    10 | export declare type IAppStyleProps = Pick<IRootAppProps, 'theme'> & {
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
It seems that the `content` property in `IPanelStyles` is conflicting with `content` in `IRawStyleBase`

https://github.com/microsoft/fluentui/blob/71139fbfe025c22f9934738ab53d14b5f62e4d66/packages/merge-styles/src/IRawStyleBase.ts#L846

https://github.com/microsoft/fluentui/blob/71139fbfe025c22f9934738ab53d14b5f62e4d66/packages/react/src/components/Panel/Panel.types.ts#L497

**Comment by ling1726** [comment]
The conflicting `content` property is definitely a bug on Fluent but I'm not quite sure what the workaround should be. In your codesandbox repro, if I simply remove `IStyleFunctionOrObject<IAppStyleProps, IAppStyles>;` then the app will run.

I don't know how `getStyles` is throwing a type error because returning `Partial<IAppStyles>` works according to your repro
