### ISSUE TITLE
[Bug]: `FileIconType.linkedFolder` icon is different between sizes.

### ISSUE THREAD

**Issue by yume-chan** [microsoft/fluentui#25645]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.25236
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 11.16 GB / 31.91 GB
  Browsers:
    Edge: Spartan (44.25236.1010.0), Chromium (107.0.1418.35), ChromiumDev (109.0.1481.0)
    Internet Explorer: 11.0.25236.1000
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/suspicious-sunset-jswqxe?file=/src/icons.js

## Actual Behavior
32px `FileIconType.linkedFolder` icon has a person symbol on it, but the 64px version doesn't

https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20221015.001/assets/item-types/32_1.5x/linkedfolder.png:

![](https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20221015.001/assets/item-types/32_1.5x/linkedfolder.png)

https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20221015.001/assets/item-types/64_1.5x/linkedfolder.png:

![](https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20221015.001/assets/item-types/64_1.5x/linkedfolder.png)

## Expected Behavior
They should be same, like in this older version, both of them don't have any person symbol:

https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20220309.001/assets/item-types/32_1.5x/linkedfolder.png:

![](https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20220309.001/assets/item-types/32_1.5x/linkedfolder.png)

https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20220309.001/assets/item-types/64_1.5x/linkedfolder.png:

![](https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20220309.001/assets/item-types/64_1.5x/linkedfolder.png)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
@gouttierre  @paulgildea  would you have a contact path to design about this one? This isn't Fluent related but rather design related since we just pull the icons from cdn
