### ISSUE TITLE
Test @fluentui/react-northstar with react 18 strict mode

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#25651]
Test @fluentui/react-northstar with react 18 strict mode and compile list of issues

**Comment by ling1726** [comment]
The request comes from another microosft partner that uses the
* Chat
* Provider
* Ref
* Flex

components, so focus on those first

**Comment by Hotell** [comment]
I'm fixing our current v18 test suite, we can build on that to make it work for v0 as well. https://github.com/microsoft/fluentui/pull/25758

**Comment by FullStackSteve** [comment]
@ling1726 @Hotell was this resolved in https://github.com/microsoft/fluentui/pull/25758 ?

We are hoping for this to be resolved https://github.com/Azure/communication-ui-library/issues/1900 so we can upgrade our platform to use React 18 but as `@Azure/communication-react` does not yet support 18 we are blocked
