### ISSUE TITLE
[Bug]: <Stack /> removes all non-ReactElement children while rendering

### ISSUE THREAD

**Issue by jeffswt** [microsoft/fluentui#25653]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
All @fluentui/react versions since commit 277d440d579167614823f740f58758f05cb40ca2.
```

### Reproduction

See bug description below.

## Actual Behavior

For the code below, only 'AAA' is shown in the rendered HTML.

```jsx
<Stack horizontal>
    <span>AAA</span>
    bbb
</Stack>
```

## Expected Behavior

The rendered HTML is expected to produce `AAAbbb` as an output.

We've identified this issue as a change introduced in commit `277d440d579167614823f740f58758f05cb40ca2`, that `_processStackChildren` had missed out `Stack` children that are not React elements.

Is this change intended?

### Requested priority

Blocking

### Products/sites affected

We discovered this issue before rolling out our website to Production.

### Are you willing to submit a PR to fix?

depends. i don't currently have a raw testing environment just for fluentui.

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
This is a regression

* `@fluentui/react@latest` : https://codepen.io/ling1726/pen/ZERJQXB
* `@fluentui/react@8.98.8`: https://codepen.io/ling1726/pen/LYrjGzd

**Comment by nikki9696** [comment]
Will the fix also handle an element example like this?
`<Stack>
          hi
          <Link href="http://www.google.com">linky</Link>
        </Stack>`

**Comment by khmakoto** [comment]
@nikki9696 I think it should.
