### ISSUE TITLE
[Bug]: Can't scroll within fluent v9 menu component

### ISSUE THREAD

**Issue by clgutier** [microsoft/fluentui#25666]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 5.61 GB / 31.84 GB
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.35)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/gracious-panini-yfdxp4?file=/index.tsx

## Actual Behavior
When having a menu button that is always at the top of the page and a long list of menu items that don't fit in the current viewport, there's no way to scroll within the menu container. Because of this, items outside of the viewport are non accessible.

To repro with sandbox provided: 
1. Make the window smaller (less height) such that not all of the menu items fit in the viewport:
![image](https://user-images.githubusercontent.com/94577746/201794461-622c9b35-aeb8-4725-a589-0edbaac7bd8d.png)
2. Try scrolling - background scroll is available, but for a component that's static and is always at top of the page, a scrollbar for the menu container is needed.

## Expected Behavior
If menu doesn't fit in the current viewport, it should be scrollable. 
![image](https://user-images.githubusercontent.com/94577746/201794691-4113e51b-11a9-4d98-99dd-0c347cbdbe77.png)

### Requested priority

High

### Products/sites affected

UCI / Dynamics

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
You should be able to enable that behaviour with the `autoSize` property in the `positioning` configuration

https://codesandbox.io/s/gracious-grass-ev1l5e?file=/example.tsx
