### ISSUE TITLE
[Bug]: Flickering buttons when rendering more than one TeachingBubble 

### ISSUE THREAD

**Issue by TZamir92** [microsoft/fluentui#25674]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
https://s4.gifyu.com/images/flicker341a8c15f4856bd4.gif

(On https://developer.microsoft.com/en-us/fluentui#/controls/web/teachingbubble, just change the first one to be always visible and then open any other example)
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/teachingbubble

## Actual Behavior
When rendering more than one TeachingBubble component, the buttons inside the bubble are flickering.

## Expected Behavior
The components should be rendered without any flickering

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
@TZamir92  Please provide a repro for this issue
