### ISSUE TITLE
[Bug]: AvatarGroup pie variant breaking in dir="rtl"

### ISSUE THREAD

**Issue by kkakroo** [microsoft/fluentui#25680]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 13.12 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.1
```

### Reproduction

https://codesandbox.io/s/fluent-v9-avatar-group-pie-rtl-bug-c6lmil?file=/example.tsx

## Actual Behavior
Avatar Group pie renders properly in rtl direction

## Expected Behavior
Avatar Group pie is breaking in rtl direction
![image](https://user-images.githubusercontent.com/8538475/201987212-7c9b2c20-3de7-4796-881e-fb3b43d07612.png)

[Repro](https://codesandbox.io/s/fluent-v9-avatar-group-pie-rtl-bug-c6lmil?file=/example.tsx)

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
Here's a sandbox with a side by side comparison that will illustrate the issue better: https://codesandbox.io/s/fluent-v9-avatar-group-pie-rtl-bug-forked-24rtvo?file=/example.tsx
