### ISSUE TITLE
[Bug]: Tooltip can not be triggered using CSS

### ISSUE THREAD

**Issue by kroudams** [microsoft/fluentui#25692]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
No info
```

### Reproduction

.

## Actual Behavior
Tooltip can not be triggered from CSS.

## Expected Behavior
I need to have a way to trigger the tooltip from CSS. I need to activate the tooltip inside a card (custom component) declared inside a GroupedList's row. Once a GroupedList row is focused I'd like to trigger the tooltip, on an icon, using CSS.

### Requested priority

High

### Products/sites affected

.

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
Thanks for submitting a feature request, please get in touch with @gouttierre  @paulgildea to prioritize new feature requests for v8
