### ISSUE TITLE
[Bug]: Regression - `childrenGap` on Stack with `wrap` breaks layout

### ISSUE THREAD

**Issue by stefan-schweiger** [microsoft/fluentui#25701]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.13 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 100.0.2
    Safari: 16.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/laughing-architecture-f92pyg?file=/src/ActionBar.tsx

### Bug Description

As far as I can tell since v8.97 using wrap on a Stack with childrenGap breaks the layout and does not apply the correct gap. Sometimes it works on the first page load but if you press reload (in the code sandbox use the one of the integrated preview not your browser reload) it breaks.

## Actual Behavior
<img width="383" alt="image" src="https://user-images.githubusercontent.com/3532342/202425315-84ac6031-b3f0-40d4-90f4-cb58fa326cc9.png">

## Expected Behavior
A stack with wrap and childrenGap should render correctly:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/3532342/202424842-76c5b414-d362-4d52-90fd-4d3a2143240f.png">

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
I doubt it, if it was that change both the wrap and no-wrap versions should have the issue. I'll take a look and see if that change caused it.

**Comment by sopranopillow** [comment]
After looking into it, it does seem to be the root cause. I can take the issue!
