### ISSUE TITLE
[Bug]: Avatar doesn't show numbers unless primary field contains at least 1 letter

### ISSUE THREAD

**Issue by clgutier** [microsoft/fluentui#25704]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 35.39 GB / 63.73 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codesandbox.io/s/black-paper-4imo99?file=/example.tsx

## Actual Behavior
In example above, when name/primary field is "123" (only numbers), avatar won't show the numbers. If instead name is "123A", it will show a number. 

## Expected Behavior
Avatar should show number even if primary field only contains numbers.

### Requested priority

High

### Products/sites affected

UCI Dynamics

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @clgutier, this behavior is by design: Avatar doesn't attempt to derive initials from numeric-only names. If you want to customize this behavior, you can set the `initials` prop (in addition to the `name` prop):
```jsx
<Avatar name="123" initials="1" />
```

Does that work for your scenario?
