### ISSUE TITLE
[Feature]: We are migrating from NorthStar to FluentUI -  missing List component

### ISSUE THREAD

**Issue by pooranoayaw** [microsoft/fluentui#25700]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

The list component has a significant advantage over the table component concerning display. Our previous react app that used Northstar had made use of List heavily. We are stuck with migration because of this and trying to find alternatives outside the FluentUI to implement this. Please include the List component asap.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ling1726** [comment]
@paulgildea, do we have a 1 dimensional list component in our roadmap?

**Comment by disgyze** [comment]
any news on this?

**Comment by ling1726** [comment]
Tracked in https://github.com/microsoft/fluentui/issues/27382
