### ISSUE TITLE
[Feature]: Custom component for Link component

### ISSUE THREAD

**Issue by fakkio** [microsoft/fluentui#25716]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Hello everybody,

I'm using RedwoodJs and it has its own `Link` component used to make it possible to generate and navigate to app urls - it also happens in other libraries, e.g. react router. It would be nice if you could use a custom component in the fluent `Link` component in addition to the already available `a` and `button`, so that you don't have to use two a's nested inside each other, which is the only solution to the moment.

Thanks.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AkiraVoid** [comment]
Link's behavior is easy to override. Almost all libraries as you mentioned support a programmatical method for routing, so you could simply do this:

```tsx
import { Link, LinkProps } from "@fluentui/react-components";

function MyLink(props: LinkProps) {
  return <Link 
    {...props} 
    onClick={(e) => {
      // Disable default behavior.
      e.preventDefault();
      props.onClick && props.onClick(e);
      // Do routing.
      // navigateTo(props.href);
    }}
    />
}
```

**Comment by khmakoto** [comment]
Hi @fakkio, as @AkiraVoid said, most libraries support a programmatical method for routing that you can use on your custom link. Alternatively, if you want to use another link as what's rendered as a v9 `Link`, you can make use of our hooks model to support this. I've created an example of how to do this with a react-router `Link` in [this codesandbox](https://codesandbox.io/s/custom-react-router-v9-link-3oqzwb). Let me know if there is anything else I can do to help.

**Comment by Hedaozi** [comment]
Hi @khmakoto , I am trying to override `onLinkClick` method of `Nav` for routing. However, I notice that there is a **lag** in nav location. For example, if I route to `pages/1` and then `pages/2`, the checked item of nav will be `pages/1` instead of `pages/2` (which is expected). My code is like:

```typescript
<Nav
  styles={navStyles}
  groups={navGroups}
  onLinkClick={(ev, item) => {
    ev?.preventDefault();
    navigate(item?.url as string);
  }}
/>
```

Or you can reproduce this lag by downloading the dev branch of my repos: https://github.com/Hedaozi/hedaozi.com/tree/dev, running it and then route to `./data-analysis-and-software-application` and click the items in nav.

**Comment by khmakoto** [comment]
@Hedaozi can you open a separate issue with that info?

**Comment by Hedaozi** [comment]
@khmakoto OK
