### ISSUE TITLE
[Bug]: Focus is handled inside FocusTrapZone even if disableFirstFocus is true

### ISSUE THREAD

**Issue by antrianis** [microsoft/fluentui#25723]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) x64 Apple M1
    Memory: 24.54 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Browsers:
    Chrome: 107.0.5304.110
    Edge: 107.0.1418.42
    Safari: 16.1
```

### Are you reporting Accessibility issue?

No

### Reproduction

https://codepen.io/andr33/pen/OJEQMeZ

## Actual Behavior
The disableFirstFocus is set to true for the FTZ but the icon gets the focus.
Element is focused by receiving a focus event in fluentui FocusTrapZone.ts function: _onBumperFocus by the stacktrace in logs.
The _onBumperFocus has no checks on disableFirstFocus.

## Expected Behavior
No focus should be put on any element if focusTrapZone has property disableFirstFocus

### Logs

```shell
[Log] Trace
	Eval Code (Anonymous Script 21 (line 1))
	(anonymous function) (office-fabric.bundle.js:10494:122)
	focus
	focusFirstTabbableElement (o.a.bundle.js:46879)
	focusFirstTabbableElement (o.a.bundle.js:8301:108)
	componentDidUpdate (o.a.bundle.js:8249)
	commitLifeCycles (react.bundle.js:19844)
	commitLayoutEffects (react.bundle.js:22812)
	callCallback (react.bundle.js:197)
	dispatchEvent
	invokeGuardedCallbackDev (react.bundle.js:246)
	invokeGuardedCallback (react.bundle.js:301)
	commitRootImpl (react.bundle.js:22550)
	commitRootImpl
	unstable_runWithPriority (react.bundle.js:26086)
	commitRoot (react.bundle.js:22390)
	finishSyncRender (react.bundle.js:21816)
	performSyncWorkOnRoot (react.bundle.js:21802)
	performSyncWorkOnRoot
	(anonymous function) (react.bundle.js:11098)
	unstable_runWithPriority (react.bundle.js:26086)
	flushSyncCallbackQueueImpl (react.bundle.js:11093)
	flushSyncCallbackQueue (react.bundle.js:11081)
	scheduleUpdateOnFiber (react.bundle.js:21208)
	enqueueSetState (react.bundle.js:12648)
	(anonymous function) (react.bundle.js:26802)
	(anonymous function) (builder-dialog.bundle.js:2143)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Was this bug Safari only?

**Comment by antrianis** [comment]
Thought so initially as it repros only on Safari with minor changes in the codepen, but the current codepen repro shows in Chrome and Safari the issue

**Comment by micahgodbolt** [comment]
Looks like this isn't a bug, rather, Dialog has it's own FTZ, so props can be passed into it via modalProps:{ focusTrapZoneProps: foo}

**Comment by antrianis** [comment]
You are right, since it has another FTZ I need to disable first focus also there. In the new repro link I now see the issue only in safari.
