### ISSUE TITLE
[Feature]: Ability to close triggered dialogs programmatically 

### ISSUE THREAD

**Issue by malekpour** [microsoft/fluentui#25729]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Export `useDialogContext_unstable` to allow closing dialog box programmatically. As per documentation it is recomended to use state and open property to close dialog boxes in async submission scenarios. It is cumbersome and makes `<DialogTrigger />` mechanism useless in many scenarios.

[DialogWithForm](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-dialog/stories/Dialog/DialogWithForm.md)

### Additional context

Right now I am using the following hook to close dialog box by calling the close method after form submission.
```tsx
export const useDialogCloser = () => {
  const ref = useRef<HTMLButtonElement>(null);
  const close = () => ref.current?.click();

  return {
    closer: (
      <DialogTrigger action="close">
        <button style={{ display: 'none' }} ref={ref} />
      </DialogTrigger>
    ),
    close
  };
};
```
```tsx
export const SampleDialog = () => {
  const styles = useStyles();
  return (
    <Dialog modalType="alert">
      <DialogTrigger>
        <Button appearance="primary" size="small">Open</Button>
      </DialogTrigger>
      <DialogSurface>
        <SampleDialogBody />
      </DialogSurface>
    </Dialog>
  );
};
```

```tsx
const SampleDialogBody = (props: StatementProps) => {
  const { mutateAsync } = useMutation();
  const { closer, close } = useDialogCloser();

  const onSubmit: SubmitHandler = async () => {
    await mutateAsync();
    close();
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <DialogBody>
        {closer}
        <DialogContent>{/* form inputs */}</DialogContent>
        <DialogActions>
          <Button appearance="primary" type="submit">
            Save
          </Button>
          <DialogTrigger>
            <Button>Close</Button>
          </DialogTrigger>
        </DialogActions>
      </DialogBody>
    </form>
  );
};
```

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ling1726** [comment]
cc @bsunderhus

**Comment by bsunderhus** [comment]
> it is cumbersome and makes <DialogTrigger /> mechanism useless in many scenarios.

@malekpour,  I'm not sure I'm following.... what is so cumbersome about simply declaring your own open state? Also, yeah... there's absolutely no advantage on using `<DialogTrigger/>` in controlled scenarios (besides the addition of the `aria-expanded` property).

but let's say I export the `useDialogContext_unstable`, how would that help you on this usage?
