### ISSUE TITLE
[Bug]: Split-Button borders are not mirrored correctly for RTL

### ISSUE THREAD

**Issue by RamyRafik** [microsoft/fluentui#25725]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz
    Memory: 34.06 GB / 63.69 GB
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.52)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/eloquent-carlos-s62bgg?file=/example.tsx

## Actual Behavior
When Split-Buttons are rendered in RTL mode, the 2 buttons switch places, but the borders are kept the same.
![image](https://user-images.githubusercontent.com/20221435/202817521-e5e3a040-89ab-4d29-91a0-b2db15f9e38c.png)

## Expected Behavior
Borders would be mirrored
![image](https://user-images.githubusercontent.com/20221435/202817882-cb8cf91d-a54a-45cd-996d-c75870a1948e.png)

### Requested priority

Blocking

### Products/sites affected

PowerApps

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by paulgildea** [comment]
cc: @khmakoto

**Comment by RamySaroufim** [comment]
By the way, I got it working by setting `dir="rtl"` on the FluentProvier element.
https://codesandbox.io/s/brave-rgb-s550ym?file=/example.tsx

However, it doesn't work when setting `direction: "rtl"` CSS Property on the Split-Button (Sandbox provided in Bug)

Is this by design?

**Comment by layershifter** [comment]
@RamySaroufim Fluent UI React v9 has built in support for `rtl` via `dir` prop on `FluentProvider`:

```diff
-<FluentProvider theme={webLightTheme}>
+<FluentProvider dir="rtl" theme={webLightTheme}>
```

```diff
-direction: "rtl"
```

https://codesandbox.io/s/friendly-sanderson-79xg3j?file=/example.tsx

---

Are there reasons to use `direction: "rtl"`?

**Comment by RamyRafik** [comment]
There are no strong reason to use `direction: "rtl"` CSS attribute.
Using `dir="rtl"` on the FluentProivder is working as intended.

Sorry for the false alarm. I'll close the bug now.
