### ISSUE TITLE
[Feature]: allow clear value in SpinButton

### ISSUE THREAD

**Issue by Misaka-0x447f** [microsoft/fluentui#25733]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Wanted a property to allow clear value in SpinButton. This is impossible for now. If all char is cleared it will return to previous value on lose focus.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ling1726** [comment]
cc @spmonahan who is the current contact for `SpinButton`

**Comment by spmonahan** [comment]
Hi @Misaka-0x447f , how are you clearing the control? `backspace` then tab away? Is you `SpinButton` controlled or uncontrolled?
