### ISSUE TITLE
[Bug]: Behavior of <Input /> differs from native <input /> element when used inside a form

### ISSUE THREAD

**Issue by fruhnow** [microsoft/fluentui#25749]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor
    Memory: 6.77 GB / 15.95 GB
  Browsers:
    Chrome: 107.0.5304.107
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.52)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/billowing-hill-peeses

### Bug Description

When creating a form with react-hook-forms and @fluentui/react-components the behavior of the `<Input />`-Element differs from the native `<input />`-Element. In the given example I try to calculate an Inputs value by the value of 2 other Inputs. When doing this with native inputs it works as expected, when using FluentUI Inputs the value flashes in for the blink of a second but then is gone visually, while still being available and correct in the forms state (see using submit-Button).

I added some comments to the sandbox trying to make more clear what im trying to say - Comments can be switched to see the behavior with native elements and vice versa.

Due to being relatively new to react, i dont see much value in me trying to fix this in a PR. Maybe ill get to try archieving something but estimation is quite low for me.

If there is anything additionally needed, ill try to update this Issue asap.

## Actual Behavior
Input looses its calculated value visually.

## Expected Behavior
The value should stay visually available like it does using native inputs.

Thanks in Advance

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
`react-hook-form` updates the value of the `<input />` by ref through the `register` function. This does not update the state that's internal to the `Input` component, so on subsequent  re-renders the value is no longer displayed by the component but the state is still managed by `useForm`.

@spmonahan  what would be the recommended way to support `react-hook-form`? or is there extra work that's needed to support this library? it's one of the most popular form control libraries

**Comment by s97712** [comment]
I think supporting uncontrolled components allows for better integration with other libraries.

**Comment by behowell** [comment]
Like @ling1726 said: `Input` is using our `useControllableState` hook, which doesn't work when the value is changed via a ref. It looks like it's not necessary to use `useControllableState` within the `Input`, and it can be removed to fix this bug for the `Input` control. I'll make a PR to do that.

However, there are other input wrappers like `Checkbox` and `Slider`, which do rely on `useControllableState` to render properly, and it's not as easy to remove the uses there. In those cases, we'll likely need to find an alternative solution for those.

**Comment by behowell** [comment]
Hi @fruhnow, after discussing further with the team, we've determined that we don't plan to support modifying the `Input`'s value via a ref, which is the approach that `react-hook-form` is using. It bypasses the props API, and does not allow for components to change how they render based on the value of the input. Although `Input` could be refactored to not require this behavior, we can't guarantee that won't change in the future, and it would not be considered a breaking change. Other controls like `Checkbox`, `Combobox`, and `Slider` rely on knowing the input's value at render time, and we don't plan on refactoring those.

`react-hook-form` provides a [`<Controller>` adapter](https://react-hook-form.com/get-started/#IntegratingControlledInputs) for this scenario, and that would be the recommended way to use it with our library.
