### ISSUE TITLE
[Bug]: SplitButton renders primaryActionButton slot inside button

### ISSUE THREAD

**Issue by Aidam1** [microsoft/fluentui#25763]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 6.08 GB / 15.88 GB
  Browsers:
    Chrome: 107.0.5304.107
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/patient-cache-zu23z3?file=/example.tsx

## Actual Behavior
The primaryActionButton slot is rendered inside a button (```className='fui-SplitButton__primaryActionButton'```).
## Expected Behavior
primaryActionButton replaces the button inside SplitButton, instead of nesting it inside button.

My use case is that I want to disable primaryButton while keeping the menu button still enabled. I think this is impossible at the moment. If there is any workaround, please let me know.

### Logs

`Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>`

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
Hey @Aidam1! Thanks for filing this issue. This behavior is possible by passing `disabled: true` to the `primaryActionButton` slot. You can see that in this [modified codesandbox](https://codesandbox.io/s/splitbutton-with-primaryactionbutton-disabled-frsx62?file=/example.tsx) based on the one you provided. Let me know if there's anything else I can do to help!

**Comment by Aidam1** [comment]
Thank you for your help @khmakoto!
