### ISSUE TITLE
[Bug]: On safari focus is handled inside FocusTrapZone even if disableFirstFocus is true 

### ISSUE THREAD

**Issue by antrianis** [microsoft/fluentui#25760]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) x64 Apple M1
    Memory: 24.54 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Browsers:
    Chrome: 107.0.5304.110
    Edge: 107.0.1418.42
    Safari: 16.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/andr33/pen/OJEQMeZ

## Actual Behavior
The disableFirstFocus is set to true for the FTZ but the icon gets the focus.
Element is focused by receiving a focus event in fluentui FocusTrapZone.ts function: _onBumperFocus by the stacktrace in logs.
The _onBumperFocus has no checks on disableFirstFocus.

## Expected Behavior
No focus should be put on any element if focusTrapZone has property disableFirstFocus

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
I unfortunately don't have a mac machine to test the repro. @smhigley would you mind helping me out here? 😅
