### ISSUE TITLE
[Feature]: Automatic release of @fluentui/web-components from web-components-v3 branch

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#25773]
### Library

Web Components (@fluentui/web-components)

### Describe the feature that you would like added

Perform automatic daily release of @fluentui/web-components from web-components-v3 branch.

- Allow only `prerelease` bumps
- Only release to `3.0.0-alpha.xxx` to `alpha` dist tag
- Never release any other package than the web-components from the branch.

### Have you discussed this feature with our team

Hotell

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Hotell** [comment]
Implemented by https://github.com/microsoft/fluentui/pull/25808
