### ISSUE TITLE
[Bug]: 'FocusZone' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by Hedaozi** [microsoft/fluentui#25792]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.25247
    CPU: (16) x64 AMD Ryzen 7 6800HS with Radeon Graphics
    Memory: 2.33 GB / 15.25 GB
  Browsers:
    Edge: Spartan (44.25247.1000.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.25247.1000
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://github.com/Hedaozi/hedaozi.com/tree/dev

## Reproduction
Just run the project. 

## Actual Behavior
```
Compiled with problems:

ERROR in src/docs/dsg-python-tutorial/python-to-excel.tsx:179:10

TS2786: 'FocusZone' cannot be used as a JSX component.
  Its instance type 'FocusZone' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("C:/Users/20172/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
    177 |           </Stack>
    178 |         ): null }
  > 179 |         <FocusZone handleTabKey={FocusZoneTabbableElements.all} isCircularNavigation>
        |          ^^^^^^^^^
    180 |           <Stack className={shared.styles.buttons} gap={8} horizontal>
    181 |             <PrimaryButton onClick={filterCode}>确认</PrimaryButton>
    182 |             <DefaultButton onClick={toggleIsCodeCalloutVisible}>取消</DefaultButton>
```

## Expected Behavior
Pass compiling

## Addition information
It worked at begin. However, after I installed some packages, the error was raised.

In addition, I try to create a new project using `npx create-react-app my-app --template @fluentui/cra-template`, but this error still exists.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
Hey @Hedaozi, I cloned your repo and was successful in both building and starting it with the following commands:
- yarn
- yarn build
- yarn start

![image](https://user-images.githubusercontent.com/7798177/204375006-dedbd3a3-be3a-41ee-8220-6b80c14df040.png)

This is my current configuration:
- yarn v1.22.19
- node v16.16.0

**Comment by Hedaozi** [comment]
> 

Thanks! It seems that this error is caused by `npm`. I will try yarn later.

**Comment by khmakoto** [comment]
Hey @Hedaozi, I cloned your repo again and checked out the `dev` branch, after which I could reproduce the same error. It seems that the problem is that the types are being pulled from 2 places, `@types/react` and `@types/react-syntax-highlighter`. Adding

```
"resolutions": {
  "@types/react": "^17.0.52"
}
```

At the end of `package.json` made the issue go away for me and allowed `yarn build` to finish.

Let me know if that works for you!

**Comment by Hedaozi** [comment]
> Hey @Hedaozi, I cloned your repo again and checked out the `dev` branch, after which I could reproduce the same error. It seems that the problem is that the types are being pulled from 2 places, `@types/react` and `@types/react-syntax-highlighter`. Adding
> 
> ```
> "resolutions": {
>   "@types/react": "^17.0.52"
> }
> ```
> 
> At the end of `package.json` made the issue go away for me and allowed `yarn build` to finish.
> 
> Let me know if that works for you!

Sadly, it still does not work for me. :cry: And my current configuration of yarn and node is the same as yours.

**Comment by Hedaozi** [comment]
> "resolutions": {
>   "@types/react": "^17.0.52"
> }

After I run my code on another PC, it raises another error code. It seems that the error may be due to some environmental settings or even the OS version. I will debug later and tell you my findings.

**Comment by Hedaozi** [comment]
@khmakoto 

Finally, it works. See https://github.com/Hedaozi/hedaozi.com/commit/b79a4fc9f5587135937c892ab170d293623ee256 Thanks again for your help!

**Comment by khmakoto** [comment]
I'm glad it worked @Hedaozi, feel free to close this issue if it's no longer a problem for you, and let us know if you need anything else 😄

**Comment by Hedaozi** [comment]
@khmakoto
There are no other problems for me. I enjoy developing using FluentUI.
