### ISSUE TITLE
[Feature]: Component scope to be constants and not hard coded strings

### ISSUE THREAD

**Issue by tonyhallett** [microsoft/fluentui#25793]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Components are scoped which allows styling to be supplied for instance of a component via Theme.components or the ICustomizerContext.customizations.scopedSettings.  

e.g for DetailsHeader the scope is hard coded as 'DetailsHeader'

```
export const DetailsHeader: React.FunctionComponent<IDetailsHeaderBaseProps> = styled<
  IDetailsHeaderBaseProps,
  IDetailsHeaderStyleProps,
  IDetailsHeaderStyles
>(DetailsHeaderBase, getDetailsHeaderStyles, undefined, { scope: 'DetailsHeader' });

export type { IDetailsHeaderProps, IDetailsHeaderBaseProps };
```

Propose this should be changed to

```
export const DetailsHeaderScope = 'DetailsHeader';
export const DetailsHeader: React.FunctionComponent<IDetailsHeaderBaseProps> = styled<
  IDetailsHeaderBaseProps,
  IDetailsHeaderStyleProps,
  IDetailsHeaderStyles
>(DetailsHeaderBase, getDetailsHeaderStyles, undefined, { scope: DetailsHeaderScope });

export type { IDetailsHeaderProps, IDetailsHeaderBaseProps };
```

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by layershifter** [comment]
@tonyhallett can you please clarify how it could be useful? Just to have `DetailsHeaderScope` exported?

**Comment by tonyhallett** [comment]
It has been a while since I used fluentui so I may be incorrect with this and I am not able currently to look through my projects.

As I mentioned - 

> Theme.components or the ICustomizerContext.customizations.scopedSettings.

allows providing styling to all components of a particular type.

https://github.com/microsoft/fluentui/blob/5a6bc1fb9dd94941a953c00a0faa5624348b9b0a/packages/theme/src/types/Theme.ts#L27

```
/**
 * {@docCategory Theme}
 * Component-level styles and token set.
 */
export type ComponentsStyles = {
  [componentName: string]: ComponentStyles;
};

/**
 * {@docCategory Theme}
 * A prepared (fully expanded) theme object.
 */
export interface Theme extends IScheme {
  /**
   * Component-level styles and token set.
   * This is still in an experimental phase and is only applied by `ThemeProvider`.
   */
  components?: ComponentsStyles;
```

You do this by providing the scope from the component - e.g for a DetailsHeader

```
export const DetailsHeader: React.FunctionComponent<IDetailsHeaderBaseProps> = styled<
  IDetailsHeaderBaseProps,
  IDetailsHeaderStyleProps,
  IDetailsHeaderStyles
>(DetailsHeaderBase, getDetailsHeaderStyles, undefined, { scope: 'DetailsHeader' });

export type { IDetailsHeaderProps, IDetailsHeaderBaseProps };
```

I would need to know it is 'DetailsHeader' ( they probably all follow the same naming convention ) and of course these strings can be mistyped.
Seems logical to me they should be exported constants that can be imported in the exact place that they are intended to be used.
