### ISSUE TITLE
Button: Unable to increase icon size without increasing button height

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#25807]
This is an issue that was introduced with #24682

Below are two sandboxes, the first with the current version, the second is the version before the root cause PR was released.

* 9.7.1: https://codesandbox.io/s/loving-haze-lbo552?file=/example.tsx
* 9.2.0: https://codesandbox.io/s/vibrant-snowflake-8472op?file=/example.tsx

In the current version in order to increase the icon size to `24px` the button height will become `36px` instead of staying at `32px` because the size of the padding is added on top of the 4px increase to the default (20px) icon size.

Prior to 9.3.0, any overrides that changed increased the size of icons in the button need to restyle their `Button` components after upgrade in order to maintain the correct `32px` height for buttons.

Also in the future, in order to increase the icon size, users will need to update the `padding` styles

**Comment by marianadasilvadev** [comment]
Hey, I would like to contribute to this issue. Can I take it?
