### ISSUE TITLE
[Bug]: Using a date format of YYYY-MM-DD with DatePicker yields incorrect results

### ISSUE THREAD

**Issue by jasonperrone** [microsoft/fluentui#25811]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Core(TM) i7-4960X CPU @ 3.60GHz
    Memory: 3.41 GB / 11.78 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: /home/jason/.mozilla/firefox
Found default profile: 5tdqvi2a.default-release
Import done in 1.581 s
Mozilla Firefox 107.0
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker

## Actual Behavior
Using the very demos of Fluent UI, using the DatePicker Allowing Text Input sample, input a date in the form of YYYY-MM-DD, such as 2022-11-15. When you leave the field it is changed to November 14, the day before. If, however, you enter it as MM/DD/YYYY, such as 11/15/2022, no problem.

As a matter of fact, a user already reported this issue in #22846 but it was closed as not reproducible. This is incorrect, it is easily reproducible right here: https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker

## Expected Behavior
Hand typing a date in the form of YYYY-MM-DD should not incorrectly alter the date when you leave the field.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Svudec** [comment]
I played a little bit with changing the time zone of my browser and managed to reproduce it in some time zones. I'll take a closer look into it.
