### ISSUE TITLE
how to add filtering in fluentui/react detailslist's contextmenu?

### ISSUE THREAD

**Issue by imir-hoxha** [microsoft/fluentui#25815]
I found this post form another user and I am wondering how to achieve this?

        ok, I think we can use contextmenu for this problem too with official example Variable row height
just use onrender, I believe it should be workable....
![image](https://user-images.githubusercontent.com/38148709/54721858-59d9e680-4b20-11e9-95d4-9143a1b2f450.png)

_Originally posted by @nealYangVic in https://github.com/microsoft/fluentui/issues/4502#issuecomment-475044195_
     
@nealYangVic any help?

**Comment by micahgodbolt** [comment]
This is not an issue. Feel free to re-open in our discussion page.
