### ISSUE TITLE
Add contributing guide to react-components package

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#25825]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

React-components is lacking a contributing guide, making it hard for new developers to start with the development.

### Have you discussed this feature with our team

@hotell

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by micahgodbolt** [comment]
Who is going to be responsible for this? Added backlog review tag.

**Comment by tudorpopams** [comment]
Let's talk about it during the Tech Sync and see if anyone is interested in picking this up.
