### ISSUE TITLE
[Bug]: data-selection-disabled on Details row is not working

### ISSUE THREAD

**Issue by bhanu345-cmd** [microsoft/fluentui#25824]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Fluent ui : 8.96.1
react:18.0.0
```

### Reproduction

https://codesandbox.io/s/dreamy-nobel-es44u0?file=/src/App.tsx

## Actual Behavior
fill this out
Even after giving data-selection-disabled={true} to Details row onSelectionChanged is also responding on click of row
## Expected Behavior
fill this out
When data-selection-disabled={true} selection should not respond on click of row

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
Hi @bhanu345-cmd, thanks for filing this issue! I can confirm that I can reproduce this behavior and I'll have a PR to fix this shortly.
