### ISSUE TITLE
[Bug]: checkbox focus visible inside dialog

### ISSUE THREAD

**Issue by steabert** [microsoft/fluentui#25843]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 11.54 GB / 31.21 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 107.0
```

### Reproduction

https://codesandbox.io/s/lingering-tdd-iqqvt4?file=/example.tsx

## Actual Behavior

Focus visible and border overflowing dialog content when pressing the checkbox label.

![image](https://user-images.githubusercontent.com/1499470/204752140-214dbe8d-58d8-4f8c-b037-d451e85d5414.png)

## Expected Behavior

- Focus not visible unless tabbing through the content.
- Focus border should overflow dialog content when visible.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
@steabert would you mind putting parentheses around what you return in `example.tsx`? I think that should fix the issue as can be seen [in this modified codesandbox](https://codesandbox.io/s/crazy-tom-8uh461?file=/example.tsx).
