### ISSUE TITLE
[Bug]:  Hidding an Overflown TabList causes a "Priority queue empty" error

### ISSUE THREAD

**Issue by daric81** [microsoft/fluentui#25859]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz     
    Memory: 6.05 GB / 23.89 GB
  Browsers:
    Chrome: 107.0.5304.122
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/blissful-hill-xljpbe?file=/example.tsx

## Actual Behavior
When hiding an Overflow TabList  using display style 'none' I get a console error "Priority queue empty". The codesandbox repro is based on the TabList with overflow example from the v9 docs website. Changing selection of the horizontal "today" tab to another causes the error. In our app we have overflowing tabs within overflowing tabs taken from the docs example. I presume this is an issue with the Overflow component, rather than the combination of Overflow and TabList

## Expected Behavior
I expect to not receive an error.

### Logs

```shell
priorityQueue.js:41 Uncaught Error: Priority queue empty
    at Object.dequeue (priorityQueue.js:41:13)
    at makeItemInvisible (overflowManager.js:67:44)
    at processOverflowItems (overflowManager.js:124:7)
    at forceUpdate (overflowManager.js:135:5)
    at eval (debounce.js:14:9)
dequeue @ priorityQueue.js:41
makeItemInvisible @ overflowManager.js:67
processOverflowItems @ overflowManager.js:124
forceUpdate @ overflowManager.js:135
eval @ debounce.js:14
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@daric81 cannot repro this anymore on `@fluentui/react-components@9.11.0`. Can you please check?

**Comment by daric81** [comment]
@layershifter , I've just checked, the issue is no longer there from v9.9.0 onward. Thanks for your time.

**Comment by layershifter** [comment]
Then closing, thanks for reporting 👍
