### ISSUE TITLE
Investigate react-icons tree-shaking not working correctly

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#25861]
The `react-icons` package is not being tree-shaken properly, becoming a pretty big hit in the bundle of components that use it.

**Comment by micahgodbolt** [comment]
not sure if its related, but react-icons also fails to work in skypack

https://www.skypack.dev/view/@fluentui/react-icons

**Comment by ms-jb** [comment]
@tomi-msft @khmakoto has there been any progress on this? Thank you!

**Comment by paulgildea** [comment]
Folks on the ACS team reached out too about hitting some size limitations because of the tree-shaking issue

**Comment by ddematheu2** [comment]
Just adding a bit of context, we are seeing the size of the bundle for react-icons to throw warnings during the Power Apps component build process. (They provide warning when bundles are over 500KB).

**Comment by spmonahan** [comment]
This is also affecting a partner I'm working with.

**Comment by Germey** [comment]
Same issue, any progress here? @khmakoto

**Comment by tomi-msft** [comment]
This is a PR in the icons repo that reduces the package size: https://github.com/microsoft/fluentui-system-icons/pull/562

**Comment by kkocdko** [comment]
On my machine (with esbuild), tree-shaking works very well, even before my PR. What my PR do is reduce more size.

What I know is if I create a `interface FluentIcon` and import it, the `/*#__PURE__*/` mark in generated file will disappear. So in that PR I use `type FluentIcon`.

**Comment by behowell** [comment]
@tomi-msft Was this fixed by https://github.com/microsoft/fluentui-system-icons/pull/562?

**Comment by tomi-msft** [comment]
Yes this was fixed by the above PR, the issue was the `/*#__PURE__*/` annotations disappearing, which turned out to be a typescript issue that was fixed when it was upgraded to a newer version. Upgrading to `@fluentui/react-icons` version `2.0.200` should solve this issue @behowell

**Comment by behowell** [comment]
Fixed by https://github.com/microsoft/fluentui-system-icons/pull/562
