### ISSUE TITLE
[Bug]: Hover style not applied if scrolling fast

### ISSUE THREAD

**Issue by Weffe** [microsoft/fluentui#25862]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 15.81 GB / 31.59 GB
  Browsers:
    Chrome: 108.0.5359.72
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/zxc7777/pen/vYrBodG?editors=1010

## Actual Behavior

Looks like if you are wiggling your mouse as you scroll down fast, the browser is forced to repaint the hover state so it's "catcing up" more frequently. If you just scroll with the mouse wheel and don't move your mouse, the browser doesn't paint the hover state until you move the mouse again.

## Expected Behavior

As you scroll fast down the dropdown, the hover style will be applied to what's underneath the mouse cursor.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Weffe** [comment]
https://user-images.githubusercontent.com/6274727/205140623-6ba7f99b-5e12-49e5-9b5f-f80245c62065.mp4

**Comment by Weffe** [comment]
I'm pretty sure this is just default browser behavior but wanted to bring it up here just in case. The screen recording is from Edge 107.0.1418.42.

**Comment by khmakoto** [comment]
Hi @Weffe, this is definitely browser behavior in all Chromium browsers. Feel free to report a bug to Chromium [here](https://bugs.[chromium](https://bugs.chromium.org/p/chromium/issues/wizard).org/p/chromium/issues/wizard). In the meantime, I'll be resolving this as "External", since we can't really do much about it.
