### ISSUE TITLE
[Feature]: Add a UTC prop to TimePicker

### ISSUE THREAD

**Issue by ngarijosh** [microsoft/fluentui#25860]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Add a UTC prop on Timepicker such that when true, input time values will be interpreted as UTC (Zulu time). Otherwise they will default to the user's local timezone as is currently.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tudorpopams** [comment]
As our current capacity is limited, this would be a great external contribution. Would you be interested in providing a PR for this?
