### ISSUE TITLE
[Bug]: Buttons not aligned in DialogFooter if one of them has an icon

### ISSUE THREAD

**Issue by stues** [microsoft/fluentui#25873]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 1.20 GB / 15.89 GB
  Browsers:
    Chrome: 107.0.5304.123
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/stues/pen/ExRdrxv?editors=1111

## Actual Behavior
If a dialog has two or more buttons in the dialog footer, the buttons appear in a row and are nicely aligned vertically. If one button has an icon defined, the two buttons are no longer perfectly aligned vertically:
![button_alignment](https://user-images.githubusercontent.com/6398408/205294929-a6662d23-c6d3-4e2c-b85c-b082f63070c2.png)

## Expected Behavior
All buttons should be aligned nicely independently whether they have icons defined or not

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sldk-yuri** [comment]
The "height" of the button calculates depend on 1st element in the flex container, for the button with leading icon 1st element (icon) styles are: 
```css
  /* ... */
  font-family: FabricMDL2Icons-5;
  font-size: 16px;
  font-weight: normal;
  line-height: 16px;
  height: 16px;
  /* ... */
```
but for the default button (1st element is span with text) styles are:
```css
  /* ... */
  font-family: "Segoe UI";
  font-size: 14px;
  font-weight: 600;
  line-height: 100%;
  /* ... */
```

These differences add space at the bottom of the button. To align buttons we have to "synchronize" elements styles. If we swap `icon` with `text` then buttons aligned, the same behavior if we add leading icon to the 2nd button.

I've created a [sandbox ](https://codesandbox.io/s/fluentui-issue-25873-m8pk2n?file=/src/index.tsx) to illustrate text above.

I just have started to explore the project, not sure how we can fix these without naive or major changes but believe that we can have an elegant solution.
