### ISSUE TITLE
[Bug]: IconButton/ CommandButton menus do not close when invoked twice in safari 

### ISSUE THREAD

**Issue by anna-mcmahon** [microsoft/fluentui#25876]
### Library

React v7 (office-ui-fabric-react) & @fluentui/react v8

### Environment Information
Package version(s): 7.146.0, 7.152.1, (that I checked)
Browser and OS versions: Safari version 14

**I am recreating [this bug](https://github.com/microsoft/fluentui/issues/16031) which was soft closed**

### Reproduction

In Safari: click the IconButton or the CommandButton. click the button again
link to demo https://developer.microsoft.com/en-us/fluentui#/controls/web/button

### Actual behavior
The button re-opens the menu on the second click

### Expected behavior
The button should close the menu on the second click

### Priorities and help requested 
Are you willing to submit a PR to fix? No

Requested priority:Normal
Products/sites affected: OWA

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@anna-mcmahon I checked on Safari 16.1 and can't repro the problem. Does it repro only on Safari 14?

**Comment by layershifter** [comment]
@anna-mcmahon thanks 👍 Confirmed, can reproduce it in docs (https://developer.microsoft.com/en-us/fluentui#/controls/web/button) for both v7 & v8.
