### ISSUE TITLE
[Bug]: Lag in navigation with customized `onLinkClick` method

### ISSUE THREAD

**Issue by Hedaozi** [microsoft/fluentui#25871]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.25252
    CPU: (16) x64 AMD Ryzen 7 6800HS with Radeon Graphics
    Memory: 6.78 GB / 15.25 GB
  Browsers:
    Edge: Spartan (44.25252.1000.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.25252.1000
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://github.com/Hedaozi/docs.hedaozi.com/

### Bug Description

I am trying to override `onLinkClick` method of `Nav` for routing. However, I notice that there is a **lag** in the checked item of nav. For example, if I route to `pages/1` and then `pages/2`, the checked item of nav will be `pages/1` instead of `pages/2` (which is expected). My code is like this:

```typescript
<Nav
  styles={navStyles}
  groups={navGroups}
  onLinkClick={(ev, item) => {
    ev?.preventDefault();
    navigate(item?.url as string);
  }}
/>
```

I guess I should manually change the checked item. However, `props.onLinkClick && props.onLinkClick(ev, item);` doesn't work for me. So I would like to ask for your help.

Or you can reproduce this lag by downloading the dev branch of my repos: https://github.com/Hedaozi/hedaozi.com/tree/dev, running it, and then routing to `./data-analysis-and-software-application` and clicking the items in nav.

The file is in `./src/routes/doc.tsx`, line 105 to line 111.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hedaozi** [comment]
I notice that expanding or collapsing the Chevron Button can refresh the nav.

**Comment by layershifter** [comment]
@Hedaozi can you please provide a minimal reproduction case?

**Comment by Hedaozi** [comment]
Hi @layershifter , I've uploaded a reproduction case at [here](https://github.com/Hedaozi/nav-bug-reproduction). Sorry for my late reply!
