### ISSUE TITLE
OverflowSet is not using the custom rendering on overflowitems

### ISSUE THREAD

**Issue by BHolse** [microsoft/fluentui#25888]
### Environment Information

- **Package version(s)**: 
    "@fluentui/react": "^8.67.1",

### Describe the issue:
When I use an OverflowSet component only with overflowItems the onRenderItem is never called. And I would like to add icons to my overflow menu. 
                                        <OverflowSet 
                                            styles={{ root: {display:"inline-block"}}}
                                            overflowItems={[
                                                {
                                                    key: 'item4',
                                                    name: 'Overflow Link 1',                                                    
                                                    onClick: ()=>{ alert("wassup")},
                                                },
                                                {
                                                    key: 'item5',
                                                    name: 'Overflow Link 2',
                                                    onClick: ()=>{},
                                                },
                                                ]} 
                                            onRenderOverflowButton={this.onRenderOverflowButton}
                                            onRenderItem={this.onRenderItem}                                            
                                        />

    public onRenderItem = (item: IOverflowSetItemProps): JSX.Element => {
        return (
          <Link styles={{ root: { marginRight: 10 } }} onClick={item.onClick}>
            Icon {item.name} 
          </Link>
        );
      };

#### Actual behavior:

The overflow list shows as default without the text Icon

#### Expected behavior:

The overflow list should show the custom rendering

**Comment by khmakoto** [comment]
Hey @BHolse, the `onRenderItem` is only used for the `items`, not the `overflowItems`. You need to use `onRenderOverflowButton` and, if using one of our buttons, send this render function via `onRenderContextualMenuItem` within `menuProps`. I've done an example of this in [the following codepen](https://codepen.io/khmakoto/pen/YzvgzrB?editors=0010).
