### ISSUE TITLE
[Bug]: Can't see bottom edge of menu when using autoSize

### ISSUE THREAD

**Issue by clgutier** [microsoft/fluentui#25907]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 6.38 GB / 31.84 GB
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/gracious-grass-ev1l5e?file=/example.tsx

### Bug Description

I had previous opened a bug Issue #25666 where I was suggested to use autoSize (as in above repro example) to be able to scroll when menu was larger than viewport height. 

## Actual Behavior
When in small viewport (height), opening the menu will set it's max-height to the viewport size but the edge of the menu is not visible. 
![image](https://user-images.githubusercontent.com/94577746/206043537-7c531133-b405-4b6a-8e2a-3588f1996a38.png)

This makes it difficult to know if there's more elements when you scroll until the bottom of the list:
![image](https://user-images.githubusercontent.com/94577746/206043847-2351cea7-95e2-4c9f-9fba-c08fca8342b6.png)

## Expected Behavior
The expected behavior is that the edge of the menu should be visible when autosize sets a max-height. The fix is probably to set the max-height a bit smaller than the viewport size. 

### Requested priority

High

### Products/sites affected

UCI / Dynamics

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
@GeoffCoxMSFT  I've added both bugs to our board, seems that they were never triaged into a sprint. The current sprint ends this week, so it'll probably make it to next sprint. If this is more urgent, tag it with the `Partner Ask` label and let @miroslavstastny  know
