### ISSUE TITLE
[Bug]: Dropdown's callout does not close automatically when clicking an <iframe>

### ISSUE THREAD

**Issue by samsam1414** [microsoft/fluentui#25902]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 24.32 GB / 47.71 GB
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (108.0.1462.42)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/samsamsam123456/pen/XWYoyPx

### Bug Description

The `Dropdown`'s callout does not disappear when clicking **inside** an `<iframe>` element.

This is in contrast to the native `<select>` element, whose callout does go away after clicking inside an `<iframe>`.

## Actual Behavior
Dropdown's callout does not close when clicking inside an `<iframe>`.

## Expected Behavior
The callout should close when clicking inside an `<iframe>`.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by samsam1414** [comment]
Is this deemed a low priority issue?

**Comment by samsam1414** [comment]
Any updates?

**Comment by micahgodbolt** [comment]
This is primarily done by design. Iframes are often used inside our various surfaces, so we don't call dismiss when focus moves to them. To be specific, we don't remove focus unless we can determine what the target of the click event is, and verify that the target is not inside of the popup

https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Popup/Popup.tsx#L116

**Comment by micahgodbolt** [comment]
I was able to simulate what you are looking for by adding an onBlur to the calloutProps. Just like popup you need to check to make sure the relatedTarget is not inside of the callout before deciding if you are going to call dismissMenu

https://codepen.io/micahgodbolt/pen/YzjZWNK?editors=0010

**Comment by samsam1414** [comment]
> I was able to simulate what you are looking for by adding an onBlur to the calloutProps. Just like popup you need to check to make sure the relatedTarget is not inside of the callout before deciding if you are going to call dismissMenu

Woah. I didn't know about calloutProps, but this is great. Combining refs and the explicit call to `dismissMenu`. I will use this as a starting point. Thank you Micah
