### ISSUE TITLE
State of FluentUI for React-Native

### ISSUE THREAD

**Issue by jaime-rivas** [microsoft/fluentui#25917]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Hi there - FluentUI is an incredible toolkit and many of us would love to learn about your thoughts for react-native. I've been following FluentUI for several years and it seems that the react-native components never got traction (just a couple of components released). A year ago, the same question was asked (https://github.com/microsoft/fluentui/issues/21111) but it was closed without any response. Please could you share your latest thoughts? Thank you very much.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by khmakoto** [comment]
@paulgildea @JustSlone

**Comment by JustSlone** [comment]
Hey @jaime-rivas thanks for reaching out. There is in-fact active development happening on a react-native implementation for Fluent UI. You can check out the latest over in the fluentui-react-native project: https://github.com/microsoft/fluentui-react-native/tree/main/packages/components

This implementation will align with Fluent UI React component names as well as support the same design token system, allowing theming interoperability between the libraries. The work is still in alpha and not yet ready for use in production but is in the works. If you check out the root readme for the project it has some early documentation, there also should be specs for each off the components in the repo as well.
