### ISSUE TITLE
[Bug]: TextField RTL w Overflow Ellipses No Option to keep LTR Direction for URLs (non-language specific text)

### ISSUE THREAD

**Issue by daneuber** [microsoft/fluentui#25951]
### Library

React v7/8

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 13.40 GB / 31.71 GB
Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None ; localization issue

### Reproduction

https://codepen.io/daneuber/pen/wvXZWBO

## Actual Behavior
1. Use TextField in application
2. Input on TextField is a URL of length greater then TextField size -> overflow is added with ellipses
3. On LTR Langauages eg English the ellipses is on the right hand side which is correct
![image](https://user-images.githubusercontent.com/22989057/206740539-47387ffc-816c-443a-84f4-71e223d67cbb.png)
4. Change language to a RTL language. Notice the ellipses change to the left hand side which is technically correct for most text, but is incorrect for language-agnostic text such as URLs.
![image](https://user-images.githubusercontent.com/22989057/206740761-c6219a11-c9e8-4057-93ff-7ef596b7dc8d.png)

## Expected Behavior
TextField should have an option to mark text content as RTL/LTR language direction agnostic, or specify a static direction, so that URLs can be the intended direction

Reach out internally to product team Share dialog / Stream team for bug link and more information if needed.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
Hi @daneuber, this should be fairly easy to do by specifying the `dir` prop in your tree right at the parent of your `TextField`. I have created the following [codesandbox](https://codesandbox.io/s/ltr-textfield-in-rtl-environment-kpxyjv?file=/src/App.tsx) showing how this can be done. Let me know if I can help you in any other way.
