### ISSUE TITLE
[Bug]: Cells in DetailsList not able to be navigated using ctrl + alt + arrow

### ISSUE THREAD

**Issue by v-giovanir** [microsoft/fluentui#25955]
### Library

React v8 (@fluentui/react)

### System Info

```shell
windows 10 / macos
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemcolumns

### Bug Description

**Issue**
- type: accessibility
- problem: after trying to access a cell of the data grid row / details list, using `ctrl + alt + arrow`, the focus goes to the first actionable element it finds ex: <a>. If there is not an actionable element within the row, then the focus is trapped on the whole row.
- this does not appear to be a screen reader issue as the screen reader reads the values for each row.

**repro steps**
- go to https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemcolumns
- tab into a row within the details list
- press `ctrl + alt + right arrow`
- press right arrow again

**Definition of done**
- being able access the cells that are within a row using `ctrl + alt + arrow`

**Resources**
- Tried the navigation successfully of a table with a role grid using ctrl + alt + arrow here: https://www.w3.org/WAI/ARIA/apg/example-index/grid/dataGrids.html
- Replicated this issue with Details List custom item here: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemcolumns
- Tried the navigation successfully with divs that have a role grid here https://www.w3.org/WAI/ARIA/apg/example-index/grid/LayoutGrids.html
- Tried the navigation successfully with a table pattern here: https://www.w3.org/WAI/ARIA/apg/patterns/table/

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@v-giovanir 

Are you using a screenreader for navigation? If so, please let us know what type and its versions 🙏

I checked following best practices:
- https://w3c.github.io/aria-practices/examples/table/table.html
- https://w3c.github.io/aria-practices/examples/grid/dataGrids.html
- https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist (our docs)

They don't mention <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Arrow</kbd> hotkeys. Can you please reference the requirement? Thanks.
