### ISSUE TITLE
[Bug]: Inconsistent application of `minWidth` and `maxWidth` in DetailsList Columns

### ISSUE THREAD

**Issue by KindaOK** [microsoft/fluentui#25960]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A. Minimal reproduction in a codepen is provided
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/aszc/pen/BaVEEOQ

## Actual Behavior
`minWidth == 0` for a column causes it to use either the value of `maxWidth` or 100 instead.

`maxWidth == 0` is equivalent to `maxWidth == Infinity`

## Expected Behavior
`minWidth == 0` should be respected and not coerced to 100

`maxWidth == 0` should have a behavior defined in documentation. The existing behavior seems fine though since `maxWidth == 0` is not very meaningful in this context.

## Suggested Fix
There are several places where `||` is used instead of `??`. That should be the only fix needed so values of 0 are respected.
[`calculatedWidth: column.minWidth || MIN_COLUMN_WIDTH,`](https://github.com/microsoft/fluentui/blob/2ae8cc79c87d510b6ad5afd01b77c6a89f5debd9/packages/react/src/components/DetailsList/DetailsList.base.tsx#L1319)

### Requested priority

Low

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@KindaOK I ported your example to CodeSandbox, https://codesandbox.io/s/fervent-smoke-vj51yr?file=/src/App.tsx. For `column3` I set `minWidth: 0` and for `column4` - `minWidth: 0`.

I think that you're right about the issue, do you want to submit a PR?

**Comment by KindaOK** [comment]
I can make a pull request.

**Comment by KindaOK** [comment]
I'm realizing a problem. Since `minWidth` (which is a `number` type) is a required parameter for `IColumn`, it *should* never be nullish (of course it could be, but that would defeat the point of typing it in the first place). What should this mean for the default value (100px) in the future? Should `minWidth` have a default value of 100 and become optional, removing `MIN_COLUMN_WIDTH`?
