### ISSUE TITLE
Feature: using Flow-relative values for text-align

### ISSUE THREAD

**Issue by kroudams** [microsoft/fluentui#25963]
https://github.com/microsoft/fluentui/blob/cde3b23327675713ed9e15a348a9e9e9df798eda/packages/react-components/react-link/src/components/Link/useLinkStyles.ts#L30

I believe using Flow-relative values here, namely `start`, might be more appropriate and beneficial.

**Comment by layershifter** [comment]
@kroudams it's a good point. I checked that `start` & `end` values match our browser support matrix, so we could try to use it.
