### ISSUE TITLE
Have github website publish workflow automatically publish new version on changes to @fluentui/public-docsite-v9

### ISSUE THREAD

**Issue by TristanWatanabe** [microsoft/fluentui#25968]
Currently only changes to `@fluentui/react-components` trigger automatic publishing of the v9 website. Make it so that changes in the website package itself (`@fluentui/public-docsite-v9`) triggers an automatic website publish as well.

**Comment by Hotell** [comment]
we cannot do this ATM because that would publish something that is not ready for "public" yet
