### ISSUE TITLE
[Issue]: On a mobile device, the Modal popup <DetailsList/> is not scrolling properly

### ISSUE THREAD

**Issue by pradeepb007** [microsoft/fluentui#25974]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Package version(s): "^7.124.1"
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/pradeepb007/pen/RwJzWoj

## Actual Behavior

open on Mobile device and try to scroll details list items horizontally, 
it's not scrolling smoothly as expected. 

without modal pop up its working fine. but in modal horizontal scroll not working properly.. please check and let me know if any solution

## Expected Behavior
open on Mobile device scrolling should be smooth, 

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Ported the example to CodeSandbox: https://codesandbox.io/s/adoring-murdock-hhv0nr?file=/src/App.tsx

I can repro it on my Android mobile, however it can be reproed in device emulation in a desktop browser.

**Comment by nazarbroslavskyi** [comment]
**IMPORTANT !!!**
Hi) I also have problem according to Modal. This is not scrollable on mobile devices
