### ISSUE TITLE
react-avatar: display: inline-block in flex container

### ISSUE THREAD

**Issue by kroudams** [microsoft/fluentui#25976]
Flex item will have `display: block` implicit value, so not sure why we need to set `display: inline-block` explicitly as it won't have any effect on the item's layout.

https://github.com/microsoft/fluentui/blob/cde3b23327675713ed9e15a348a9e9e9df798eda/packages/react-components/react-avatar/src/components/Avatar/useAvatarStyles.ts#L28

**Comment by behowell** [comment]
Hi @kroudams could you give more info about why this is a bug? Please link a codesandbox or codepen with a repro of the bug that is caused by using inline-block on Avatar. Thanks!
