### ISSUE TITLE
[Bug]: Update High Contrast Colors

### ISSUE THREAD

**Issue by redongreen** [microsoft/fluentui#25995]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/theme-color--page
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/theme-color--page

## Context
Our high-contrast colors were updated by our accessibility team member Ben Truelove.

### Update the current/default Fluent V9 high-contrast colors to the latest HC ramp.

- hcHyperlink from #FFFF00 to #75E9FC
- hcDisabled from #3FF23F to #A6A6A6
- hcHighlight from #1AEBFF to #8EE3F0
- hcCanvas from #000000 to #202020
- hcCanvasText from #FFFFFF to #FFFFFF
- hcHighlighText from #000000 to #263B50
- hcButtonFace from #FFFFFF to #202020
- hcButtonText from #000000 to #FFFFFF

### Add an additional high-contrast "desert" ramp.

- hcHyperlink #1C5E75
- hcDisabled #676767
- hcHighlight #903909
- hcCanvas #FFFAEF
- hcCanvasText #3D3D3D
- hcHighlighText #FFF5E3
- hcButtonFace #FFFAEF
- hcButtonText #202020

![image](https://user-images.githubusercontent.com/20573265/207684385-96ac0b15-d7af-4649-a755-1b1212b37f6f.png)

I expect there to be accessibility warnings when implementing this. Please tag @redongreen for review and any questions.

### Requested priority

Normal

### Products/sites affected

Fluent 2 WEB UI

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by daisygeng** [comment]
cc: @miroslavstastny this is a request for the new year (Jan 2023), swapping out the hex values for example in storybook to use Win 11's default high contrast themes. Also requesting adding hcButtonFace and hcHighlightText slots (it looks like Windows currently supports those and we're missing them in v9)
