### ISSUE TITLE
[Bug]: fluentui/react-component types break with TS exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#25993]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
CodeSandbox (link provided)
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/exactoptionalpropertytypes-y22yr1?file=/src/index.tsx

## Actual Behavior
Using `exactOptionalPropertyTypes` breaks fluentui component types with `error TS2604: JSX element type 'Button' does not have any construct or call signatures.` errors. It appears to be because this type resolves to `never`:

`export declare type ForwardRefComponent<Props> = ObscureEventName extends keyof Props ? Required<Props>[ObscureEventName] extends React_2.PointerEventHandler<infer Element> ? React_2.ForwardRefExoticComponent<Props & React_2.RefAttributes<Element>> : never : never;`

From CodeSandbox:

![image](https://user-images.githubusercontent.com/26070760/207668051-7c560819-6045-496d-bfe5-226b443eedcd.png)

If you change `exactOptionalPropertyTypes` to `false` in this CodeSandbox and reload, it will resolve the type error.

## Expected Behavior
Can render fluentui components with `exactOptionalPropertyTypes` enabled. This issue is preventing us from adopting `exactOptionalPropertyTypes` for improved typing.

### Requested priority

High

### Are you willing to submit a PR to fix?

no (this type is pretty core to fluentui and I wouldn't want to break other uses, but I'm willing to try and help narrow this as a fluentui vs. TS issue, if needed)

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by MatthewSkingley** [comment]
This issue, specifically `JSX element type ... does not have any construct or call signatures` is present in my project without exactOptionalPropertyTypes with react-components version 9.9.1. I locked my dependency to 9.6.1 where the issue is not present. In both configurations, react-utilities is at version 9.4.0.

**Comment by yuhr** [comment]
Can't use this library due to this problem.

**Comment by mabuelhagag** [comment]
Same
