### ISSUE TITLE
[Bug]: Multi-select ComboBox preserves focused style even when not focused

### ISSUE THREAD

**Issue by croraf** [microsoft/fluentui#26014]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
@fluentui/react: "~8.103.8"
Browser: Chrome 108, Edge 108
OS: Windows 10, Linux Ubuntu
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox#usage "Basic uncontrolled ComboBox"

## Actual Behavior
1. Click on the "Basic multi-select ComboBox" dropdown arrow so that the dropdown opens.
2. Click away from the component, on blank part of the page.
3. Click on the "Basic single-select ComboBox" dropdown arrow. (you can additionally click on the blank part of the page after this step)

**Notice that both `ComboBox`es appear as they have focus.**

## Expected Behavior
After step 3 above the "Basic multi-select ComboBox" should not look as being focused.

### Requested priority

High

### Products/sites affected

Microsoft Power BI

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
After looking at it for a bit, I can repro only in public-docsite. Locally in `@fluentui/react`'s storybook it's not reproing. 

@croraf you can confirm this is happening in your side as well?  or did you find this bug only in the docsite?

**Comment by croraf** [comment]
It is happening on the app I'm working on, but the usage is slightly complicated. I wasn't able to reproduce it in a simple example in codepen.

**Comment by micahgodbolt** [comment]
It looks like a race condition. Focus rect is removed when focus moves from the input to the body. When you close the menu by clicking on the body the input doesn't properly blur. If you close the menu by hitting escape, focus stays in the input, and then clicking the body blurs it.

**Comment by micahgodbolt** [comment]
my guess is something to do with 

```
  /**
   * Determines if we should be setting focus back to the input when the menu closes.
   * The general rule of thumb is if the menu was launched via the keyboard focus should go back
   * to the input, if it was dropped via the mouse focus should not be forced back to the input.
   */
  private _focusInputAfterClose: boolean;
```

**Comment by micahgodbolt** [comment]
This DOES repro when building the website locally. Maybe it has something to do with a page full of other comboboxes. At least we can dig in better.
