### ISSUE TITLE
[Bug]: Fluent UI Dropdown is UI is not working as expected on responsive Screen

### ISSUE THREAD

**Issue by sachin161194** [microsoft/fluentui#26033]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Please refer below Reproduction link from Code Sandbox :
https://codesandbox.io/s/flamboyant-kare-cgh78g?file=/src/index.tsx&resolutionWidth=320&resolutionHeight=675
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/flamboyant-kare-cgh78g?file=/src/index.tsx&resolutionWidth=320&resolutionHeight=675

## Actual Behavior

Before Focusing on Dropdown options: 
![image](https://user-images.githubusercontent.com/92863921/208429785-f704c29e-b255-46c8-b38c-b65d7bd60858.png)

After hovering over dropdown options ,first two options are getting shifted towards upside & not accessible: 
![image](https://user-images.githubusercontent.com/92863921/208430178-3b507d22-1bfc-4004-8b7b-7e7bae1f8b79.png)

## Expected Behavior
Dropdown option needs to be in place after hover and selection as well

## Reproduction Link/URL
https://codesandbox.io/s/flamboyant-kare-cgh78g?file=/src/index.tsx&resolutionWidth=320&resolutionHeight=675

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Only happens when list is taller than the window

**Comment by JKohlman** [comment]
This also happens on a normal sized screen and setting `responsiveMode={ResponsiveMode.small}`. Once you have enough items to make it scrollable then hovering the mouse over the list/items automatically scrolls it down an amount. Interestingly enough, this does **not** happen when `multiSelect={true}` is enabled.

Reproducible sandbox: https://codesandbox.io/s/confident-mountain-8cmusf?file=/src/index.tsx
