### ISSUE TITLE
[Bug]:Accessibility Issue - Calendar [ARIA role gridcell is not allowed for given element]

### ISSUE THREAD

**Issue by ChithiraMG** [microsoft/fluentui#26043]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 3.55 GB / 15.78 GB
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

Run fastpass for calender component in fluent UI

## Actual Behavior
ARIA role gridcell is not allowed for given element
![image](https://user-images.githubusercontent.com/101738825/208630211-34c0d68b-abfb-4d59-88a1-96937a1fdcd4.png)

## Expected Behavior
Kindly help to solve the above mentioned fast pass accessibility issue

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
This is a false positive from Accessibility Insights -- gridcell has good support and works better on `<button>` elements than on `<div>` elements in this use case.
