### ISSUE TITLE
[Bug]: List does not display initially when using getItemCountForPage

### ISSUE THREAD

**Issue by wHavelin** [microsoft/fluentui#26040]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz
    Memory: 21.25 GB / 63.73 GB
  Browsers:
    Chrome: 108.0.5359.125
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/wHavelin-the-vuer/pen/rNrNKzw

## Actual Behavior
I'm seeing the list not render initially. In my case, my List is in a FocusZone in a modal, and I saw that the visibleRect being passed into getItemCountForPage has a width of 0 because it's being called before the modal is opened. I can provide more details on how I'm using the list, but I saw that the same issue seems to be happening with the example List from the documentation. So that's what I used for the reproduction link, but if it's helpful to know more details of where it's happening for me let me know.
<img width="835" alt="image" src="https://user-images.githubusercontent.com/4746572/208523706-2440fdf7-fb24-49ec-82c3-f3133ab84cc4.png">

## Expected Behavior
The list should render the items.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by josgd** [comment]
We found the same problem, we also have a full-screen div and a FocusZone around the List.
Calling forceUpdate() once, on the component containing the List, in the getItemCountForPage callback, can serve as a workaround.
