### ISSUE TITLE
[Bug]: Accessibility Issue - Rating star

### ISSUE THREAD

**Issue by ChithiraMG** [microsoft/fluentui#26044]
### Library
v8

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 3.55 GB / 15.78 GB
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

Use the Rating component to add user favourites, and use the Fastpass test

## Actual Behavior
Code snippet: `<div class="ms-FocusZone css-125 ms-Rating-focuszone ratingFocusZone-260 ms-RatingStar-root--large rootIsLarge-252" role="textbox" aria-readonly="true" data-is-focusable="true" tabindex="-1" data-focuszone-id="FocusZone195">`

Fix ONE of the following:
aria-label attribute does not exist or is empty
aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
Element has no title attribute
![image](https://user-images.githubusercontent.com/101738825/208639784-8cefef96-e10a-4d16-980a-c3b846a7d19f.png)

## Expected Behavior
Kindly help to solve the above mentioned fast pass accessibility issue

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Running fast pass on our rating controls does not produce any issues. Please provide a proper repro of this issue.

![image](https://user-images.githubusercontent.com/1434956/214902242-f021dce7-f323-47fd-bf2f-16cfd7115eb3.png)
