### ISSUE TITLE
[Bug]: Accessibility Issue -Split button [Using a negative tabindex on an element inside an interactive control does not prevent assistive technologies from focusing the element (even with 'aria-hidden=true')]

### ISSUE THREAD

**Issue by ChithiraMG** [microsoft/fluentui#26042]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 3.55 GB / 15.78 GB
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

Run fastpass for split button in fluent ui

## Actual Behavior
Using a negative tabindex on an element inside an interactive control does not prevent assistive technologies from focusing the element (even with 'aria-hidden=true')
![image](https://user-images.githubusercontent.com/101738825/208417144-b8e09aa4-6e1d-4513-9a83-a9a0f86c4134.png)

## Expected Behavior
Kindly help to solve the above mentioned fast pass accessibility issue

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
Could you elaborate on this?
> Using a negative tabindex on an element inside an interactive control does not prevent assistive technologies from focusing the element (even with 'aria-hidden=true')

How are you focusing on the element with an AT, and which AT are you using?

**Comment by ChithiraMG** [comment]
Focusing on the element using tab stops.
AT: Accessibility Insights for web -->Fastpass

**Comment by smhigley** [comment]
@ChithiraMG the tab key can't reach an element with `tabindex="-1"`. Could you add some more information on what assistive tech you're running, what browser you're using, and the step-by-step interactions you're doing to reach the element with `aria-hidden="true"`?
