### ISSUE TITLE
Input: `contentBefore` and `contentAfter` don't work with `bundleIcons`

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#26057]
**Repro:** https://codesandbox.io/s/mystifying-austin-02jpd4?file=/example.tsx

![image](https://user-images.githubusercontent.com/20744592/208868776-ffe89ce8-ff44-4b43-ac1f-525ea3cd33e6.png)

The specificity of the content styles in `Input` are more specific than the styles applied in bundled icons, the result is that both filled and regular icons are always visible

https://github.com/microsoft/fluentui/blob/66bf89f634cad4a275e957d7a2214c7e73ff8c2e/packages/react-components/react-input/src/components/Input/useInputStyles.ts#L215-L235

**Comment by nandin-borjigin** [comment]
I don't see a value for `bundleIcons` to always render both of the icon variants and control their `display` rule. 

An icon being `filled` or `regular` is mostly a static decision and doesn't seem to change at runtime. So, a logic like `props.fill ? <FilledVariant /> : <RegularVariant />` would be much more robust. 

It is correct for consumers of `bundleIcon` to expect `bundleIcon` only renders one element and they may do some other modifications like `.parent:nth-child(0) { /* some rule */ }`. The fact that `bundleIcon` renders two elements actually breaks such assumption.

**Comment by ling1726** [comment]
> An icon being filled or regular is mostly a static decision and doesn't seem to change at runtime. 

This assumption isn't necessarily correct, quite often designs call for 'hover' icons.

![msedge_xz0WtIMobU](https://user-images.githubusercontent.com/20744592/208884211-a5046cd5-0f2b-438c-bec2-739f438712f1.gif)

**Comment by nandin-borjigin** [comment]
@ling1726 , thanks for clarifying, I didn't know that.

But still, switching between `display: none` and `display: inline` still affects the render tree (as opposed to DOM tree) and causes a reflow, so I presume it doesn't bring too much value in terms of perf compared with `filled ? <FilledVariant /> : <RegularVariant />`.

However, doing so brings inconsistency between the actual behavior of the wrapper component and its expected semantic (User expects one element out of it but it actually yields two)

**Comment by ling1726** [comment]
@nandin-borjigin, implementing this with javascript isn't a great idea since you would need to use event handlers like `onMouseEnter` and `onMouseLeave` to make this possible and might scripting perf concerns + being more flaky since it needs both event handlers to work correctly. the CSS based solution means that they can be styled with the `:hover` pseudo selector.
