### ISSUE TITLE
[Bug]: <InputField> in <DialogContent> causes a vertical scrollbar being rendered

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#26061]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components: v9.7.4
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/inputfield-in-dialog-di3b13?file=/example.tsx

## Actual Behavior
![image](https://user-images.githubusercontent.com/50703224/208923798-c2f205cc-8ef0-4406-94a7-dd1f60ad6c26.png)

## Expected Behavior
There shouldn't be a vertical scrollbar in the dialog.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
This seems to be caused by the SVG icon wrapped in a `display: inline` parent, despite being explicitly `display: inline` itself. Removing grid styles from all parents has no effect -- it seems purely caused by the SVG + inline parent. Styling the parent as `display: inline-block` fixes it, as does making the entire status message `display: flex`.

**Comment by smhigley** [comment]
There are two easy fixes for this -- making the status message parent `display: flex`, or making the svg icon slot `display: inline-block`. Those both fix the scrollbar issue, it would just depend on whether we want wrapping status message text to look like this (the current style):
![screenshot of input field with second status message line wrapping below the inline icon](https://user-images.githubusercontent.com/3819570/209726542-43984ffd-3126-4ea0-a9a0-5010895fca89.png)
or like this:
![sreenshot of input field with icon in its own column, and text wrapping in a block adjacent to the icon column](https://user-images.githubusercontent.com/3819570/209726605-fbed05c0-327d-4b99-b9f4-8aa53bc48490.png)

**Comment by chenxinyanc** [comment]
Interestingly, I've tried to remove the `line-height: 12px` style from the `<span>` wrapping the icon, and the scrollbar is gone.
![image](https://user-images.githubusercontent.com/50703224/210047719-4181324b-ca5e-485b-9bd5-3000eee5789f.png)

**Comment by chenxinyanc** [comment]
> or like this:
> ![sreenshot of input field with icon in its own column, and text wrapping in a block adjacent to the icon column](https://user-images.githubusercontent.com/3819570/209726605-fbed05c0-327d-4b99-b9f4-8aa53bc48490.png)

Yet personally I would choose the second line wrapping behavior as you've shown above.

**Comment by smhigley** [comment]
@chenxinyanc I checked with design, and we are indeed going with the second behavior 😊

The `line-height: 12px` removal works because if the height of the text is taller than the icon, it's fine. If the icon is taller than the text, it causes that scrollbar problem.

Fix incoming!
