### ISSUE TITLE
[Bug]: HC mode > focus outline inconsistency > Primary button focus indicator is hardly visible 

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#26077]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 17.39 GB / 31.74 GB
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/cg6rim?file=/example.tsx

### Bug Description

1. Change Windows HC mode into "aquatic" or "desert"
2. Open example with primary button
https://codesandbox.io/s/cg6rim?file=/example.tsx
3. Navigate with keyboard on the primary button
4. Observe focus outline

Actual: there is focus outline around the primary button, but outline is thin and is hardly visible when user need to see clearly focus on the screen. 
Please compare the primary button outline with no-primary button outline. This one is thicker.

Expected:  primary focus outline is such thick as it is for no-primary button

Primary focus outline:
![image](https://user-images.githubusercontent.com/22620150/209105738-420a104d-8868-4da7-b1ba-95f5e3378565.png)
![image](https://user-images.githubusercontent.com/22620150/209104883-8f379feb-d699-4bda-8985-932f2c05ba51.png)

No-primary button focus outline:
![image](https://user-images.githubusercontent.com/22620150/209105820-c8653e29-0813-4d09-9f6f-2fd3d91e545b.png)
![image](https://user-images.githubusercontent.com/22620150/209104943-5f53beb0-4a94-483b-9b02-81f9782f6a2d.png)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
Also fixed by #26089
