### ISSUE TITLE
Remove screener related secrets now that they are not being used

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#26086]
SCREENER_API_KEY and AZURE_STORAGE_CONNECTION_STRING

Also, now that PRs don't need access to these secrets to build, can we change the workflow permissions for token usage?

**Comment by TristanWatanabe** [comment]
`SCREENER_API_KEY` and `AZURE_STORAGE_CONNECTION_STRING` github secrets have been deleted. `screener.key` used in the ADO pipelines has also been deleted from the `fabric-variables` variable group
