### ISSUE TITLE
[ComponentGovernanceCompliance]: loader-utils@2.0.0 critical severity 

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#26095]
### Bug Description

Prototype pollution vulnerability in function parseQuery in parseQuery.js in webpack loader-utils prior to version 2.0.3 via the name variable in parseQuery.js.

## Actual Behavior

our dependency tree contains `loader-utils` 2.0.0 which is a dependency of `@mdx-js/loader@1.6.22`.

Unfortunately mdx loader uses exact version in their pacakge.json so it cannot be deduped/bumped to 2.0.3. Only option is to migrate to mdx-2 but which **is not possible** because storybook uses mdx 1.

Unless mdx authors release version 1.6.23 with carret for loader-utils there is pretty much nothing we can do to mitigate this vulnerability. 

_NOTE:_ mdx loader is directly used in northstar docs, which is doable to migrate

## Expected Behavior

Upgrade loader-utils from 2.0.0 to 2.0.3 to fix the vulnerability.

https://github.com/mdx-js/mdx/issues/2200

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ChristianMurphy** [comment]
See https://github.com/mdx-js/mdx/pull/2169#issuecomment-1321283767 for context on why this isn't really a critical issue.

If for compliance reasons, you want to remove upgrade the dependency anyway.
I'd recommend going to MDX version 2, which storybook does support through https://github.com/storybookjs/mdx2-csf/
MDX version 2 is also used by default in Storybook 7 (currently in beta https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.14)

It will be more time and cost effective to upgrade storybook to version 7 and mdx to version 2 (see https://github.com/mdx-js/mdx/pull/2169#issuecomment-1321295810 for context)
