### ISSUE TITLE
[Bug]: If the text in message bar fits into one line, then also the expand(chevron) icon is visible. Ideally it should not.

### ISSUE THREAD

**Issue by priyanshulnu** [microsoft/fluentui#26126]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
Memory: 22.49 GB / 31.21 GB
Container: Yes
Shell: 5.0.17 - /bin/bash
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/priyanshulnu/pen/ZEjWbvO

## Actual Behavior
For the MessageBar component, if the text is small which fits in one line, then also we see the expand (chevron) icon for the message bar.

## Expected Behavior
If the text is small which fits in one line, then we should not see the expand(chevron) icon. This chevron icon should be visible only if text is not fitting in one line and is getting truncated to multiple lines.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@priyanshulnu the MessageBar component itself doesn't do anything to check the length of the message text and whether it fits on a single line. The `truncated` prop fully controls whether the chevron button appears or not.

If you want to conditionally apply `truncated` based on whether the text is wrapping, you would likely need to check the actual rendered height of the MessageBar and compare it to the height of a single-line or truncated MessageBar.

**Comment by priyanshulnu** [comment]
Thanks @smhigley for the response. Is there any way that I can dynamically check whether the text is fitting in one line or not? If possible, can you provide some suggestions in the codepen above?
