### ISSUE TITLE
[Bug]: Coachmark doesn't display TeachingBubble

### ISSUE THREAD

**Issue by xradgul** [microsoft/fluentui#26137]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 73.26 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 15.5
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/winter-pond-ni4077?file=/src/CoachmarkExample.tsx

## Actual Behavior
Coachmark only displays beak, and not the teaching bubble. 

Demo: https://codesandbox.io/s/winter-pond-ni4077?file=/src/CoachmarkExample.tsx

The demo was created by:
1. Created a fresh Creact React App with TypeScript
2. Installed @fluentui/react
3. Copy/pasted sample code from `CommandBar with coachmark on individual button` mentioned here: https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar

## Expected Behavior
Coachmark should also display teaching bubble

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
All the necessary mark up seems to be present in the DOM and the "pulse" animation is even visible when the example first loads but the teaching bubble and coachmark are never visible.
