### ISSUE TITLE
[Bug]: Issue in accessing external component but used within Panel

### ISSUE THREAD

**Issue by hardik2205** [microsoft/fluentui#26133]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
'@fluentui/react/lib/Panel'
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/issue-in-accessing-external-component-but-used-within-panel-rene7m

## Actual Behavior
Within Panel component the isBlocking default is set is true, this blocks and do not allow any action on the external component (which may be rendered via reactDom.createPortal to div outside of the Panel component). In my case I am using tinymce editor which opens its modal outside of the Panel.

Also Panel get close as the action happens outside of the Panel. I try to suppress this by event.PreventDefault inside the onDismiss handler, but then it do not propagate the event further inorder for the main actions.
Secondly, if I use isBlocking = false, but then dismiss can only be done with the close icon.

[Example Link here](https://codesandbox.io/s/issue-in-accessing-external-component-but-used-within-panel-rene7m)

## Expected Behavior
Can you help me how should I use the Panel as
- Panel to allow the actions outside of the Panel for particular div/divs or which are triggered from components within the Panel components.
- It should dismiss the Panel and onDismiss to be trigger, if I click outside of Panel. and should not trigger dismiss or close if I perform action on elements within external div/divs (like tinymce editor popups) but also allow executes the require actions.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Hey @hardik2205, I think I understand what you're asking but I'll rephrase so we can be sure we're talking about the same thing (please correct me if I'm wrong!).

1. You want to open a `Panel` but have it be non-modal in that you can click on anything outside of the panel ([see the "non-modal" example in the docs](https://developer.microsoft.com/en-us/fluentui#/controls/web/panel))
2. Clicking on certain elements outside the panel will dismiss the panel
3. Clicking on other elements outside the panel will not dismiss the panel

Assuming all the above is correct, there isn't a solution for this in `Panel` by itself. However, you can do this by manually wiring up event listeners and using refs. This can get quite complicated and may not work in your actual application but I do have a demo showing one way to accomplish this.

[Link to demo](https://codesandbox.io/s/issue-in-accessing-external-component-but-used-within-panel-forked-e0ldrq?file=/index.js)

I've commented the demo app but I'll outline the main points here:

1. Get a `componentRef` to the `Panel`. This will allow you to imperatively call `Panel`'s public API (i.e., `dismiss()`).
2. When the `Panel` is open attach click listeners to `document`.
    1. Make sure the listeners are removed when the panel is closed or the component is unmounted to avoid unwanted behavior and memory leaks.
3. Put your business logic into the click handler. That is, decide whether the given click should dismiss the `Panel` or not.

**Comment by hardik2205** [comment]
Hi spmonahan,
Yes, you understood the need correctly. 
I also placed the same logic that you mention to check for the element in the dismiss function handler and then to allow or disallow the dismiss event. 
- But this only works when isBlocking = {false} (you also added same in [your example](https://codesandbox.io/s/issue-in-accessing-external-component-but-used-within-panel-forked-e0ldrq?file=/index.js)). But then the greyish background is removed, if we set isBlocking= false.
- And if I use isBlocking = {true}, then it have the greyish background. But it prevent the events/actions from getting propagated and execute the needed functionality for the elements where don't want to dismiss the panel.

So, for me the scenario is.
- I open the panel, and then inside panel I have a button (buttonX). 
- On clicking buttonX, it opens up the new modal. but this is not rendered within the panel but out side using react createPortal. 
- now if I want to do any input box changes or click event on modal button then, Panel present it from happening within modal. I am also suppressing the events to not dismiss the modal, but still the events are not getting propagated/executed on the actual element as they were getting prevented by Panel isBlocking property. 
- You can check is nearly similar behavior in [example - Confirm light dismiss ](https://developer.microsoft.com/en-us/fluentui#/controls/web/panel). In this even if you click 'No' on the modal the panel closes.

So, is there a way, to have the panel functionality with
- greyish background with panel 
- And dismiss modal functionality  when clicked outside but not for certain element(in above case modal and its childrens.)
- Allow modal to work normally as it work when the Panel props isBlocking is false. (to allow actions/events on the modal outside of panel).

**Comment by hardik2205** [comment]
Is there any luck or update or this issue?

**Comment by spmonahan** [comment]
This isn't really a scenario that Panel supports but I think you can apply some styling to make it work.

[Here's an updated example](https://codesandbox.io/s/issue-in-accessing-external-component-but-used-within-panel-forked-e0ldrq?file=/index.js).

I've updated some of the event handling but one important thing is that you need to apply [`z-index`](https://codesandbox.io/s/issue-in-accessing-external-component-but-used-within-panel-forked-e0ldrq?file=/index.html:205-276) to your modal so it sits above the layer with the panel and it's overlay.
