### ISSUE TITLE
[Feature]: Semantic color slots

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#26168]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Design side would like to have referenceable semantic tokens for Danger, Success, Warning, Severe, and Out of Office

The mappings are here: 
https://www.figma.com/file/KB9oUjMKen2cKnyPG7RgdS/Design-tokens-superset?node-id=33176%3A64587&t=LR0EG0zmttGmgl4v-4

### Have you discussed this feature with our team

Miro Stastny and Geoff Cox

### Additional context

cc: @GeoffCox, @miro

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by miroslavstastny** [comment]
We need to discuss a way how we can implement this without a perf penalty.
See #25720 for a related discussion.
