### ISSUE TITLE
[Bug]: Drag and drop functionality not working on DetailsList component upon touch operation

### ISSUE THREAD

**Issue by shchhabra-dot** [microsoft/fluentui#26175]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 2.48 GB / 15.73 GB
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/shubham_687/pen/xxJEvJP

## Actual Behavior
Drag and drop functionality not working for DetailsList component upon touch operation
As a result, it does not work at all on devices which support touch screen and for mobile devices.
## Expected Behavior
Drag and drop functionality should work on devices which support touch screen and for mobile devices.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Can reproduce it on my Android Chrome and Windows 11 laptop.
