### ISSUE TITLE
[Feature]: Promote GroupedListV2 to stable

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#26189]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

`GroupedListV2` is currently an unstable export in Fluent v8. Make it stable as it's been used in production for some time now with no bug reports.

### Have you discussed this feature with our team

@spmonahan

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tudorpopams** [comment]
@spmonahan is there anything specific you need from the backlog review team for this?

**Comment by spmonahan** [comment]
@tudorpopams No, it's just a reminder to make the change in the future. Not a priority.
