### ISSUE TITLE
[Bug]: VirtualizedComboBox selects wrong option when options are updated while callout is open

### ISSUE THREAD

**Issue by rothsandro** [microsoft/fluentui#26193]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
The envinfo command isn't helpful here as we currently use the old 
office-ui-fabric packages (office-ui-fabric-core@11.0.1, office-ui-fabric-react@7.199.4) 
but will soon update to @fluentui/react. The bug can be reproduced with the new package.

Browser: Chrome 108.0.5359.125
OS: Windows 11
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/sndrrth/pen/YzjpYXr?editors=1010

### Bug Description

We render a VirtualizedCombobox with 20 items. We update the list of options in a useEffect + setTimeout (in real we update the options in the `onPendingValueChanged` callback).

1. Open the combobox => 20 items are shown
2. Wait 3s until the options are updated
3. Click on "Option 12"

## Actual Behavior
"Option 6" is selected

Note: After updating the options, the checkbox (input) of "Option 6" and "Option 12" have the same id. The change event is triggered on the option 6 checkbox.

## Expected Behavior
"Option 12" should be selected.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
After the options are changed, all of the options with ID's outside of the new range (9 items) are reset, though those under 9 are not reset. So option 6's ID is staying the same, while option 12's is being recalculated and also set to 6.


![image](https://user-images.githubusercontent.com/1434956/214893838-b3150710-23e3-47e5-89d3-980c5fb19751.png)


![image](https://user-images.githubusercontent.com/1434956/214893739-f9242e99-3090-4bee-aea3-6c382ada696b.png)

**Comment by micahgodbolt** [comment]
Note that this only happens for VirtualizedCombobox, and is not an issue in regular non virtualized combobox.

**Comment by mboggs1** [comment]
@micahgodbolt - did this get fixed? I tried updating to the newest version but can still repro.

**Comment by khmakoto** [comment]
Reopening
