### ISSUE TITLE
[Bug]: PeoplePicker has inconsistent styling on select

### ISSUE THREAD

**Issue by powerchelle** [microsoft/fluentui#26222]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
I don't have dev setup here, but I'm seeing this on Edge 108.0.1462.54.
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/powerchelle/pen/oNMYaKK

## Actual Behavior
This example is taken directly from the FluentUI storybook. https://codepen.io/powerchelle/pen/oNMYaKK

Tabbing through, selection looks different for first and next item.
On first select
![image](https://user-images.githubusercontent.com/10646539/211068043-c6db54aa-b7ca-4215-bd4e-d701dfa3d8ed.png)

On next select
![image](https://user-images.githubusercontent.com/10646539/211068706-da953fa6-a994-44db-90c9-323bf5c8c464.png)

## Expected Behavior
We would expect to see the same highlighting regardless of order.

### Logs

```shell
n/a
```

### Requested priority

Normal

### Products/sites affected

https://account.microsoft.com

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Looks like tabbing into the people picker doesn't properly invoke "focus" on the person.
