### ISSUE TITLE
[Bug]: DetailsList Group checkbox is only shown on hover when checked

### ISSUE THREAD

**Issue by mizeljko** [microsoft/fluentui#26249]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 12.40 GB / 31.83 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

Render any DetailsList with a group and select all items in that group.

## Actual Behavior

Checkbox for group is not shown after clicking on it and selecting all items from that group. It is only available on hover.
Codepen example: https://codepen.io/mizeljko/pen/oNMYOdo

## Expected Behavior

Checkbox for group is always shown after clicking on it and selecting all items from that group.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
The group checkbox is shown to denote that a group can be toggled on/off. The "group" is not actually selected, just the items inside of the group. Same behavior if you were to select all the items in a group. The checkbox selection doesn't show up.
