### ISSUE TITLE
[Bug]: onOpened is not triggered on Panel component in React 18

### ISSUE THREAD

**Issue by manuelpoelzl** [microsoft/fluentui#26256]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 14.79 GB / 31.78 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/peaceful-cache-0vhotd?file=/src/App.js

## Actual Behavior
If a function is specified for the onOpened function of the Panel and the panel gets opened, nothing happens, the callback is not triggered.

## Expected Behavior
The callback function should get executed

---
This issue seems similar: #11782

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
This appears to be a React 18 issue, as it works in React 17. It does not seem to require strict mode to repro though, so that's even more interesting.
