### ISSUE TITLE
[Bug]: Docs: Sections incorrectly highlighted in right-hand sidebar

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#26268]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-avatar--default

## Actual Behavior

1. Load the [Avatar page on react.fluentui.dev](https://react.fluentui.dev/?path=/docs/components-avatar--default)
2. In the right-hand side bar click "Badge", note that the selection indicator is next to "Badge"
3. Then click "Badge Icon", note that the selection indicator is not next to "Badge Icon"

https://user-images.githubusercontent.com/93940821/211418744-e3863e92-8dae-436e-b116-84fc4264e6bd.mp4

One possibility is that the colons in the sidebar headings are causing a problem with linking.

## Expected Behavior

The selection indicator should be next to the item I clicked in the sidebar.

### Logs

```shell
Observed in

- MS Edge Version 108.0.1462.76 (Official build) (64-bit)
- Firefox 108.0.2
- Chrome Version 108.0.5359.125
```

### Requested priority

Low

### Products/sites affected

react.fluentui.dev

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
using intersection observer to set the values as you scroll...might need to turn that OFF for a short period after you click, otherwise the last item to come into view takes precedence.
