### ISSUE TITLE
[Bug]: Fluent 2 Theme for v8 - SplitButton is missing rounded corners

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui#26269]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/button#usage

## Actual Behavior
Applying the Fluent 2 Web Light Theme on the v8 SplitButton - the top right and bottom left corners are not rounded: 
<img width="332" alt="image" src="https://user-images.githubusercontent.com/33229964/211422200-a5a15066-bfbe-496e-ae05-cb4da2871a5d.png">

## Expected Behavior
When applying the Fluent 2 Web Light Theme on the v8 SplitButton it has the correct values:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/33229964/211422592-99e7603a-05d9-4641-abdc-722ef52bd684.png">

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mltejera** [comment]
Thanks Paul - I think I have a fix for this in my repo - just a matter of getting my OUIFR repo hydrated and running proplerly.
