### ISSUE TITLE
[Bug]: Error on @fluentui/react-components code when running tsc 4.9

### ISSUE THREAD

**Issue by jvatic** [microsoft/fluentui#26289]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 6.11 GB / 7.77 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/jvatic/fluentui-issue-26289-repro

## Actual Behavior
Running `tsc src/* --jsx react --moduleResolution nodenext --outdir dst` results in an error

## Expected Behavior

tsc to complete successfully

## Work-around

Enabling the `skipLibCheck` flag in the TypeScript config mitigates the issue, but is not ideal.

### Logs

```shell
> tsc src/* --jsx react --moduleResolution nodenext --outdir dst

node_modules/@fluentui/react-avatar/dist/index.d.ts:100:67 - error TS2344: Type 'Partial<AvatarGroupPopoverSlots>' does not satisfy the constraint 'SlotPropsRecord'.
  Property 'tooltip' is incompatible with index signature.
    Type 'NonNullable<WithSlotShorthandValue<TooltipProps>>' is not assignable to type 'UnknownSlotProps | SlotShorthandValue'.
      Type 'Omit<TooltipSlots, "root"> & TriggerProps<TooltipTriggerProps> & Pick<PortalProps, "mountNode"> & { ...; }' is not assignable to type 'UnknownSlotProps | SlotShorthandValue'.
        Type 'Omit<TooltipSlots, "root"> & TriggerProps<TooltipTriggerProps> & Pick<PortalProps, "mountNode"> & { ...; }' is not assignable to type 'UnknownSlotProps'.
          Type 'Omit<TooltipSlots, "root"> & TriggerProps<TooltipTriggerProps> & Pick<PortalProps, "mountNode"> & { ...; }' is not assignable to type 'Pick<HTMLAttributes<HTMLElement>, "style" | "className" | "children">'.
            Types of property 'children' are incompatible.
              Type 'ReactElement<any, string | JSXElementConstructor<any>> | ((props: TooltipTriggerProps) => ReactElement<any, string | JSXElementConstructor<...>>)' is not assignable to type 'ReactNode'.
                Type '(props: TooltipTriggerProps) => ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.

100 export declare type AvatarGroupPopoverProps = Omit<ComponentProps<Partial<AvatarGroupPopoverSlots>>, 'children'> & {
                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@fluentui/react-avatar/dist/index.d.ts:134:31 - error TS2344: Type 'TooltipProps' does not satisfy the constraint 'keyof IntrinsicElements | UnknownSlotProps | ComponentType<{}> | VoidFunctionComponent<{}>'.
  Type 'TooltipProps' is not assignable to type 'UnknownSlotProps'.
    Type 'TooltipProps' is not assignable to type 'Pick<HTMLAttributes<HTMLElement>, "style" | "className" | "children">'.
      Types of property 'children' are incompatible.
        Type 'ReactElement<any, string | JSXElementConstructor<any>> | ((props: TooltipTriggerProps) => ReactElement<any, string | JSXElementConstructor<...>>)' is not assignable to type 'ReactNode'.

134     tooltip: NonNullable<Slot<TooltipProps>>;
                                  ~~~~~~~~~~~~

node_modules/@fluentui/react-avatar/dist/index.d.ts:140:62 - error TS2344: Type 'AvatarGroupPopoverSlots' does not satisfy the constraint 'SlotPropsRecord'.
  Property 'tooltip' is incompatible with index signature.
    Type 'NonNullable<WithSlotShorthandValue<TooltipProps>>' is not assignable to type 'UnknownSlotProps | SlotShorthandValue'.

140 export declare type AvatarGroupPopoverState = ComponentState<AvatarGroupPopoverSlots> & Required<Pick<AvatarGroupPopoverProps, 'count' | 'indicator'>> & {
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~


Found 3 errors in the same file, starting at: node_modules/@fluentui/react-avatar/dist/index.d.ts:100
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@jvatic your example points to `@fluentui/react-components`. With what package do you have problems?

**Comment by jvatic** [comment]
@layershifter sorry, looks like I'd missed cleaning up the package.json in the repro repo, which I've now done. The issue occurs with just importing the `@fluentui/react-components` package.

**Comment by layershifter** [comment]
@jvatic thanks, I've updated the issue.

**Comment by layershifter** [comment]
Was able to repro, TS version is 4.9.4.

**Comment by zachhats** [comment]
@layershifter I'm not sure if this is exactly the same issue, but I was also able to repro this with @fluentui/react 8.104.6, @fluentui/merge-styles 8.5.5, and typescript 4.8.4. See [here](https://github.com/zachhats/fluentui-issue-26289-repro)

This is blocking our upgrade to typescript 4.8, let me know if (1) I should open a separate issue for this or (2) if I can be any help with repro (I am also MSFT internal, so can show your our actual settings offline)

**Comment by layershifter** [comment]
@zachhats please create a separate issue as it's a different package 🙏

**Comment by Hotell** [comment]
> Enabling the skipLibCheck flag in the TypeScript config mitigates the issue, but is not ideal.

Can you provide more reasoning behind this statement ("not ideal"). 

This flag is a recommended pattern unless you're creating low level primitives (re-usable library etc). having it not enabled also slows down TS checking time, so you're getting performance bottleneck without valid reason.

Regarding repro, as TS is introducing Breaking changes on Minor releases we cannot give any guarantees so far. We will have automated solution for verifying our code against various TS versions this year though which should mitigate this in future.

**Comment by titanous** [comment]
Hi @Hotell,

I'm a colleague of @jvatic. We only run TS typechecking as a part of our test suite (compilation is done by SWC), so there is no meaningful performance impact for regular development flows. We'd prefer to leave `skipLibCheck` off so that we aren't surprised by bugs or incompatibilities in packages that we depend on.

**Comment by rosergeev** [comment]
Yesterday I upgraded packages to latest versions and faced with exactly the same issue
`
$ npx tsc
node_modules/.pnpm/@fluentui+react-avatar@9.5.28_@types+react-dom@18.2.7_@types+react@18.2.21_react-dom@18.2.0_r_5vuhustd5tz5u3pva7q3dswlkq/node_modules/@fluentui/react-avatar/dist/index.d.ts:101:67 - error TS2344: Type 'Partial<AvatarGroupPopoverSlots>' does not satisfy the constraint 'SlotPropsRecord'.
  Property 'tooltip' is incompatible with index signature.
    Type 'NonNullable<WithSlotShorthandValue<TooltipProps>>' is not assignable to type 'UnknownSlotProps | SlotShorthandValue'.
      Type 'Omit<TooltipSlots, "root"> & TriggerProps<TooltipTriggerProps> & Pick<PortalProps, "mountNode"> & { ...; }' is not assignable to type 'UnknownSlotProps | SlotShorthandValue'.
        Type 'Omit<TooltipSlots, "root"> & TriggerProps<TooltipTriggerProps> & Pick<PortalProps, "mountNode"> & { ...; }' is not assignable to type 'UnknownSlotProps'.
          Type 'Omit<TooltipSlots, "root"> & TriggerProps<TooltipTriggerProps> & Pick<PortalProps, "mountNode"> & { ...; }' is not assignable to type 'Pick<HTMLAttributes<HTMLElement>, "style" | "className" | "children">'.
            Types of property 'children' are incompatible.
              Type 'ReactElement<any, string | JSXElementConstructor<any>> | ((props: TooltipTriggerProps) => ReactElement<any, string | JSXElementConstructor<...>>)' is not assignable to type 'ReactNode'.
                Type '(props: TooltipTriggerProps) => ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.       

101 export declare type AvatarGroupPopoverProps = Omit<ComponentProps<Partial<AvatarGroupPopoverSlots>>, 'children'> & {`
