### ISSUE TITLE
[Bug]: Cannot type space in a Combobox when freefrom is enabled

### ISSUE THREAD

**Issue by blueset** [microsoft/fluentui#26295]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Tested on `@fluent/react-components==9.9.1`, Microsoft Edge 107.0.1418.26 on Windows 11
```

### Are you reporting Accessibility issue?

no

### Reproduction

[https://codesandbox.io/api/v1/sandboxes/define?parameters=N4IgZg[...]sCc6DQA&query=file%3D%2Fexample.tsx](https://codesandbox.io/api/v1/sandboxes/define?parameters=N4IgZglgNgpgziAXKGAPAhgWwA6wHQAucqSoEcAQhAHboBOAnkmOlHDADQgDGA9tQRgCkICDl50CAAmBTM6ANYwAygQaw4HKXAAWEgjvTUAJpqkBXdgEljUgL5SwdXpikAdEAAEwUc0ILmEAD0dDDo3AQAtHzi1P5wHgDcbtRi2PoyUgDCLgBGvPmoWjmY-YUACs7YZgDy2AQQ_PaOzq4e3r7-gSFhEdEu6XECcEHm1HAE6LmwSSlpGQBUUuhwUgBKvdJOLlIA5KHhBLvJ1Hzj0pYqahpSALxyilfq8AAUwClSUs68BIgyH58pEEglJVOEFFIDDApFApjAoMt8gA3aFQxwQeG2ADuEAMyykAHN0NgAZ9jORcOgGH9dgS6BBjLsOKTCfTjAAVGA4WGCNa8LFwGmhbBhAgvACMTgAlEyWQArSwNMAMKyCTCCvYTehHZnUQFSPCG3T6QwmOB4InYF67ABM2FQuyluv18lQAHUGQYaQAWAAMvvtuwBdhSdilJzQ6UkUjOEykADFQjAwBJXPcXtgqhrytqIKwADwlMq8VCVXjVAB8UruFf-epj_DjMXyNjuFmsxmtzd4kWMyfQ5igR3DANj0nLDUbbYA2rssugdXt54I6NhoLC6EylwvILot3OdDAYJMdPusjoINwlNQz7wrwuMVBb1j9wARXgEt-8KDYC83rS7PGMB0KEi6ARAoQ-Aw-7xuQp4AfGJYwSWUiciBGKbghzifgBAASWATMB-7KLQSi7AAuicnxjlI07yAQ3B_gSdSTuMWjsAQACyC6MTQzH1I04zkW2GyHHglxgoILzToaeAToJcDkSO9Y0dO3CKi4yhhHQjHsceWQaZgWn0Ixwn3KJETiewkkwPmEz0tQBJSAAPhYJjJjQMDGBWLzKdRjbSBMzyrPcEnXK8fkNucUj8OeRgEjAfxFgUJZltUs6xaaCUUW2MAogINZ1vqNFIqwfi5flBCEPQCVVaVnSEPSmC-VRgI0fRjHwG28mNngkBDsBLw9Xqty1sNhC8AAMvywHzuwvl4DQfaoDUYAvPVfgTdNWKzSsMC-dWtxHVIvqRZ8HHcQxTEsQpLwdYecBnVIEBgFI61lTAeCwI5eIAGS_Q8V3wF9QgEni-ZSOK1bvPW-ocQZEyadpjHvZ0T0OPC7BFfq2j6YZxk6ToLxjH2kBxMY6PBq1NH8Dd_BabAERJXkKWllmGXUHT1AMzAEQ5emeX-FoxgLugh21jDxUBYDvGOVzbYi5MckCfwnKoNI_0xSr4yLacvh9nALyK-gyusWrBBPS9b33XxXPQyy5144jRnI0TJMeeT6NSJj0KSzj8P467Rui6bgnm5T9Z2K1oHmHQer5uSSIxrCcBwAAclgMC3MAQUaHg3wEHYFYO1I-awrk8LPcY2fdjYRcUPA0gigQ-ZBOX8LF7DgKFizhTLPS6CRO3UCwMYuQMDXLN1y0R4pnQriUtwMB6FAfZ0LcHg8xEyx6kYYisB4MXUHFjlZ8AmXxTADi09rW8ENnN-sXfDjALJmblnARcl58wBBEsbrQlCDETAQhbDkjgJSBgfF8TqWdjPZMqZtAEAcgSLQVs0SXDoM9ag2BzDSGMLweAN5pD3R3jvfeCIFhBBDF3fUwBYEECRiZHQUgAD8pd5ZKAnh4Jws9UyH0EOrGugdmFf1oTjT4Hh6EiMJiGEA39u5BC5rWP41BBxQBoRIn-Ns5ba3NPIK0w1Cr5k4TACe59tZFwsaxOwrdlFSk0TjVuyVCid31K3ROFYThRxSImPh888DYHoJnFcIVsYEO4BqP2ZJ4DcHpNrP40TASI0YDSFxKE4DmGwFGIgkJDxSAAAa8IQfPApUh37YC0FiC8jFlgj35KsYpc9XCCOkDQXBVU9hSAANR7CsNyLk_hoH9RXNAxhtVDxYJxHiIpSZmllPIISIQwFWBQAYF8XmLgQHuWMHgIMXdHE0KjiAOwXAlpoDwDoAgmAoCkFEJQGg9AmCIBYGwTgPB-CCGEIgEACcIBJwZBvEABcPAVg8f8isJyznuVQIQYgdzyBUFoIwZgrB2BcDOF8ggIh5jRiWCsdYmxXw1E4i0HY-xNi9hcMcOY4hoyyHjJ0AQZYkQMmAlUmAuRJoQAJFc9kh4QHNG2K4XYHQ_ACG6AcPoMRBjxBpakOl0gGVzMQQSgAohgAZQrWh7DwEENAWBcAwHlcCFIwIpAAE1eDmBjEYb25JpAGEWQarVNB3AgBdUauFqAPB4DNUEFIFkCDEs4vnUBg0WT5kZeKggLK2VYKhCA7OO0uU8r5QKq-bitH5g1Ya2AQIs2fFbtG_wca14VmdICCJ5htlVVqmq2AtaKAqk7PsXgPxHS6nDFCkAQT7wJTwHKOA_AEUPORc8156KPkCH8CId4IA-wincqcDECRSDtB8DGyVlKZX8HiB4RAHgAB6ABOPAvpz0eGZMCzYB7j3igAOxXo8FKqIBDMB3pAEex9z6b2HEiHAOJEB6hrsPSAHkjcPB2DsCc6DQA&query=file%3D%2Fexample.tsx)

## Actual Behavior
Combobox selects the first option in dropdown when <key>space</key> is pressed.

## Expected Behavior
Combobox should allow user to type a space in the input field.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Confirmed, can reproduce with latest version.

**Comment by kwilkins** [comment]
Any update or workaround possible for this issue? We are also seeing it in v8.72.2 FluentUI react components.

https://codesandbox.io/s/fast-sun-0z5s79?file=/src/App.js

**Comment by kwilkins** [comment]
Hi FluentUI Team, is there any update on this getting checked in? We've been experiencing ongoing issues from this bug and would love to get a fix out ASAP.

**Comment by kwilkins** [comment]
Hi FluentUi Team, any update on getting this fix released? We are eager awaiting this change.
