### ISSUE TITLE
[Bug] Can't access xAxisCalloutData property for ICustomizedCalloutData in LineChart

### ISSUE THREAD

**Issue by itsein** [microsoft/fluentui#26303]
### Environment Information

- **Package version(s)**: not provided

### Describe the issue:

I want to display a custom HoverCard in my LineChart, so I pass in a customHoverChart using onRenderCalloutPerDataPoint that takes props of ICustomizedCalloutData type. My ILineChartPoints have values for xAxisCalloutData and yAxisCalloutData. However, when I try to access these values like {props.values[0]?.xAxisCalloutData} and {props.values[0]?.yAxisCalloutData}, I cannot only access the xAxisCalloutData value. I can only access the yAxisCalloutData value. 

#### Actual behavior:

I can't access the xAxisCalloutData.

#### Expected behavior:

Being able to access the xAxisCalloutData value.

### If applicable, please provide a codepen repro:

[https://codepen.io/itsein/pen/qByrGNj](https://codepen.io/itsein/pen/qByrGNj)

![image](https://user-images.githubusercontent.com/112440626/211892118-92221911-845c-4bfa-b248-33be212aed30.png)
In the HoverCard, "xtext2" should also appear.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) Outlook Web

**Comment by AtishayMsft** [comment]
@itsein This is a known issue. xAxisCalloutData value is not hooked up in the hover card for some charts.

**Comment by AtishayMsft** [comment]
Reopening the issue.
