### ISSUE TITLE
[Bug]: can not get custom data from IconButton

### ISSUE THREAD

**Issue by duqingnian** [microsoft/fluentui#26309]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   
    Memory: 8.40 GB / 15.92 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/button

### Bug Description

I use the IconButton for react, I want when I click the IconButton, I can get the custom data in the callback function,
so, I use this:
`<IconButton onClick={this.click_callback} data={{testname:"duqingnian"}} data-testname="dqn" iconProps={{ iconName: 'CirclePlus', style: { color: 'rgba(0,0,0,.9)' } }} />`
But in the click_callback function, I can't find any way to get the custom data.
please help me,thanks a lot

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@duqingnian

If you want to have `data-*` properties on DOM:

```tsx
<IconButton
  onClick={e => {
    console.log("data", e.target.closest("button").dataset);
  }}
  data-testname="dqn"
  iconProps={{
    iconName: "CirclePlus",
    style: { color: "rgba(0,0,0,.9)" }
  }}
/>
```

If you don't want to have them on DOM you can create a wrapping component:

```tsx
function Wrapper({ data, onClick, ...props }) {
  return (
    <IconButton
      onClick={e => {
        onClick(e, data);
      }}
      data-testname="dqn"
      iconProps={{ iconName: "CirclePlus", style: { color: "rgba(0,0,0,.9)" } }}
    />
  );
}
```

And then use it:

```tsx
<Wrapper
  onClick={(e, data) => {
    console.log("data", data);
  }}
  data={{ testname: "dqn" }}
  iconProps={{
    iconName: "CirclePlus",
    style: { color: "rgba(0,0,0,.9)" }
  }}
/>
```

https://codesandbox.io/s/compassionate-bird-q5npyj?file=/src/App.tsx
