### ISSUE TITLE
[Bug]:  Combobox - Multiselect With Tags - Tags are wrapped in list 

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#26319]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 12.51 GB / 31.74 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/bgcx1j?file=/example.tsx

### Bug Description

Steps:
1. Screen reader is on (tested with Chrome/NVDA)
2. Navigate to combobox
3. Select couple of items
4. Press Shif+TAB navigate to the selected items pills/tags
5. observe narration

## Actual Behavior
Narration: clickable  list  with 4 items  Remove Snake  button  

## Expected Behavior
screen reader recognize tags are in the list, but this doesn't looks correct because:
- user can expect navigation with arrow keys in list but user can navigate only with TAB or Shif+TAB between buttons
- it is not good practice to put button in the listitem

I think we have two solution:
- add role=presentation on `<ul>` and `<li>` elements to remove list sematic for screen reader
- change it to real list, then we need to speak which component should it be... (listbox/option or one row table)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
The selected items are in a static list, not an interactive list -- this is a very common interaction pattern on the web, where lists are not expected to be interactive or use arrow keys to move between items. The steps under the heading "Bug Description" are a good example.

In this case, the list is static, but the buttons are interactive. This allows the items to be in a named container, and for the number of selected items to be exposed.
