### ISSUE TITLE
[Bug]: Combobox + Dropdown - Complex Options - item is narrated twice

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#26314]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 12.51 GB / 31.74 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction
combobox:
https://codesandbox.io/s/tnmhtc?file=/example.tsx
dropdown:
https://codesandbox.io/s/bzfr5k?file=/example.tsx

### Bug Description

Steps:
1. Screen reader is on (tested with Chrome/NVDA)
2. Navigate to combobox
3. Press enter key to open list 
4. navigate between item in list
5. observe narration

## Actual Behavior
content of item is narrated twice:
Katri Athokas available Katri Athokas Available  not selected  1 of 4
Elvia Atkins busy Elvia Atkins Busy  not selected  2 of 4

## Expected Behavior
content of the item is narrated only once

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
Ah yeah, this is caused by Persona exposing both the image and the name + status text. I can explicitly pass `aria-hidden` to the avatar slot in this example, though I wonder if it's worth revisiting in Persona as well.

(cc/ @sopranopillow)
