### ISSUE TITLE
[Bug]: Combobox - Freeform - custom not existing option can be selected

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#26317]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 12.51 GB / 31.74 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

YES

### Reproduction

https://codesandbox.io/s/1uehvw?file=/example.tsx

### Bug Description

Steps:
1. Screen reader is on (tested with Chrome/NVDA)
2. Navigate to combobox
3. Type some word which doesn't exists in combobox list like for example "catt"

## Actual Behavior
list is opened like this item would exists in the list
user hear they are in the list and item is not selected
user can do selection and think he found item
So in the end user can consider the item was found in the list and selected. There is no narration about quotas which are displayed in the UI.
enclosing screen reader narration visualization: 
![image](https://user-images.githubusercontent.com/22620150/212058449-1c25e6bb-289b-434c-9a39-51dcc88e6a41.png)

## Expected Behavior
not fully understand this scenario but we should communicate in better way to screen reader user what they found and what they selected, when item doesn't exists in the list

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
In the UX study, we made the text within the freeform option `Select "typed value"`, but found that while people liked having the option appear, the text wasn't ideal. One of the challenges is that I think the best string value would depend a lot on the specific use case. For example, one use of freeform might be something like a search box, and then the freeform option could say something like `Search "typed value"`.

I could alter the example somewhat to have it imitate a search box with suggestions, and then update the custom string option to say "Search X" for now -- does that seem like a good approach?
