### ISSUE TITLE
Documentation - Fonts not loading - https://developer.microsoft.com/en-us/fluentui#/controls/web/????

### ISSUE THREAD

**Issue by thoffmann-fms** [microsoft/fluentui#26349]
### Environment Information
Any

### Describe the issue:

Font files are not loading so parts of the page are not rendered with correct characters but just placeholders.
The browser console log shows:
![image](https://user-images.githubusercontent.com/28546239/212398966-9544c029-3d9e-4af5-a89c-0c869a01c3fa.png)

#### Actual behavior:
FireFox:
![image](https://user-images.githubusercontent.com/28546239/212398392-a6c09993-cb79-44ff-abb0-5708cb87677d.png)
![image](https://user-images.githubusercontent.com/28546239/212398432-a06c8b98-f3d0-4fae-acc7-7b8e2063c646.png)
Edge:
![image](https://user-images.githubusercontent.com/28546239/212398488-50c0bf90-1ad4-4a64-b62a-56304ba0dfe3.png)
![image](https://user-images.githubusercontent.com/28546239/212398510-212034d2-ad2d-4ebc-9b4f-e699753d02b6.png)

#### Expected behavior:
Page should render correctly and not show placeholders.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) N/A

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by layershifter** [comment]
I don't see errors about `.woff` files anymore, but some CSS files are not loaded:

![image](https://user-images.githubusercontent.com/14183168/214564518-d39a5e67-58e5-41e9-8334-79279c68ecf8.png)

It also fails to load another font:

![image](https://user-images.githubusercontent.com/14183168/214564573-1bafc177-e94f-4da9-9baa-ddfef0bccd61.png)

I also can repro the issue with missing glyphs in an editor:

![image](https://user-images.githubusercontent.com/14183168/214564841-e01d4b50-19b7-4146-9aca-4f4c29e94c10.png)
