### ISSUE TITLE
[Bug]: selectedKeys not working when dynamically setting selectedKeys values from state object.

### ISSUE THREAD

**Issue by manuhinCCS** [microsoft/fluentui#26341]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
npx envinfo --system --npmPackages '{@fluent/*}' --browsers
-----------------------------------------------------------
npx: installed 1 in 9.157s

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz    
    Memory: 1.71 GB / 7.88 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

NIL

## Actual Behavior
Drop down values not getting selected when setting **selectedKeys** array values dynamically.

## Expected Behavior
When adding values in selectedKeys array. It should show as selected in drop down.

### Logs

```shell
public getContacts(vendoritem: IDropdownOption): void {
    const listurl: string = this.props.context.pageContext.web.serverRelativeUrl + "/Lists/Contacts";
    this._bidService.getContacts(listurl, vendoritem.key)
      .then((responsedata: any) => {
        if (responsedata !== undefined && responsedata !== null) {
          responsedata.forEach((cnt: { Id: number, Title: string, Default: boolean }) => {
            let filteritem = this.contactsOptions.filter((el) => el.key === cnt.Id)
            if (filteritem.length > 0) {
              const index = this.contactsOptions.indexOf(filteritem[0])
              const defIndex = this.defaultCntOptions.indexOf(cnt.Id)
              if (index > -1) {
                this.contactsOptions.splice(index, 1);
                this.defaultContactOptions.splice(defIndex, 1);
              }
            }
            else {
              this.contactsOptions.push({ key: cnt.Id, text: cnt.Title })
              if (cnt.Default) {
                this.defaultContactOptions.push(cnt.Id);
              }
            }
          });
          this.setState({ contactsData: this.contactsOptions, defaultContacts: this.defaultContactOptions});
        }
      });
  }
```

### Requested priority

Blocking

### Products/sites affected

NIL

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by manuhinCCS** [comment]
<Dropdown
                placeholder=""
                label="Contacts"
                options={this.state.contactsData}
                multiSelect
                selectedKeys={this.state.defaultContacts}
                disabled={this.state.contactsData.length <= 0}
              />

**Comment by layershifter** [comment]
@manuhinCCS can you please provide a reproduction case?
