### ISSUE TITLE
[Bug]: Native tooltip is still shown in Facepile component for overflow descriptive button even when `showTooltip` is set to false

### ISSUE THREAD

**Issue by anil-adepu** [microsoft/fluentui#26351]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 91.14 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Brave Browser: 108.1.46.134
    Chrome: 108.0.5359.124
    Safari: 16.2
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/anil_adepu/pen/abjwYga

## Actual Behavior
On setting `showTooltip` prop to `false` to avoid rendering native tooltips, no tooltips are shown for individual personas but the native tooltip is still shown for the overflow descriptive button

## Expected Behavior
fill this out

Ideally, when `showTooltip` is set to `false`, native tooltip should not be shown for overflow button as well. 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Not necessarily a bug, as the showTooltip prop and custom render mentioned in the prop are only for rendering the personas, and not the persona overflow button. But I can see how this leaves the feature incomplete if you wanted to also customize the behavior of the overflow button.

**Comment by micahgodbolt** [comment]
Actually, all you need to do is add a `title` value to the overflowButtonProps, and that will override the title (and tooltip). 

Seeing as there is an easy workaround here, I don't feel that we'd add this feature.

**Comment by anil-adepu** [comment]
Right, although `showTooltip` prop is intended only for individual personas, once the descriptive overflow button comes in, one would intuitively expect the overflow button as well to inherit the tooltip visibility prop.

Although, we have this dirty hack to set `title` to `''`, when rendering a custom tooltip to overflow button, (which is what we have been using as a workaround hitherto), this is overriding `ariaDescription`  which is also being set to `''` and is potentially breaking the accessibility as well. 

[https://github.com/microsoft/fluentui/blob/6fa0a3e69c74b3bc22d5e5f62fb6c9492dfe0d76/packages/react/src/components/Facepile/Facepile.base.tsx#L243](https://github.com/microsoft/fluentui/blob/6fa0a3e69c74b3bc22d5e5f62fb6c9492dfe0d76/packages/react/src/components/Facepile/Facepile.base.tsx#L243)

So, it would be great if this can be fixed. I'm happy to contribute as well, shall raise a PR soon! :)
