### ISSUE TITLE
[Bug]: itemLimit not being respected by NormalPeoplePicker

### ISSUE THREAD

**Issue by nayancprakash** [microsoft/fluentui#26354]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 8.00 GB / 31.71 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/nayancprakash/pen/yLqXqGX

## Actual Behavior
No matter what value of `itemLimit` is provided to NormalPeoplePicker (whether higher or lower) only a default amount is used

## Expected Behavior
The `itemLimit` prop should specify the maximum number of items in the Picker

### Requested priority

Blocking

### Products/sites affected

loop (blocking fluentui version bump)

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
I can't repro this. As soon as I change the value to 2, I can only select 2 people
