### ISSUE TITLE
[Bug]: Combobox - Multiselect With Value String - Select/unselect item moving checkbox elements 

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#26363]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 12.51 GB / 31.74 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/ecf1xz?file=/example.tsx

### Bug Description

Steps:
1. Navigate to combobox
2. open combobox with down arrow key 
3. navigate on first item "cat"
4. toggle item with press space bar. To select and unselect it.
 5. observe checkbox element for each option in the list
 
## Actual Behavior
once user do select and unselect checkbox elements are moving up/down in UI

## Expected Behavior
UI should stay stable

Comment:
looks like it is related only first items in the list, because in the background we update the string with selected items...

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
I don't currently see any issues with UI moving around or checkboxes doing anything unexpected when I toggle the first item in the codesandbox, or multiselect with value string example on the docs site. Is there any more info on browser, OS, and repro steps that could be included? I notice both Edge and IE 11 were mentioned, though I don't think IE 11 is supported by v9 -- is this happening in both browsers?

**Comment by kolaps33** [comment]
Hi :)
enclosing the video :) 
https://user-images.githubusercontent.com/22620150/213147838-edb8d759-8348-4fea-ac95-029f0f83048e.mp4

Sorry about not mentioned related browser under test it is chrome 108.0.5359.126

**Comment by layershifter** [comment]
@smhigley @kolaps33  I was able to repro on Chrome with zoom level 125% & 175%.

**Comment by smhigley** [comment]
I was able to repro after adjusting zoom too (110% for me 🤷‍♀️). It no longer repros after #26509 though, so I'm closing this as fixed.
