### ISSUE TITLE
[Bug]: Fluent-horizontal-scroll has flipper on incorrect side in RTL mode

### ISSUE THREAD

**Issue by sarahstandish** [microsoft/fluentui#26388]
### Library

Web Components (@fluentui/web-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/coldwintryday/pen/QWBgVRx

## Actual Behavior
In RTL mode, a flipper appears on the right-hand side of the screen.

## Expected Behavior
In RTL mode, a flipper displays on the left-hand size of the screen.

### Requested priority

High

### Products/sites affected

Edge

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by eljefe223** [comment]
I **think** this has been fixed in later builds. I need to unblock the archives branch and verify
