### ISSUE TITLE
LineChart Y axis are not scaled for the values between 0 and 1

### ISSUE THREAD

**Issue by ovysotska** [microsoft/fluentui#26383]
When using LineChart component I would like the plots to be scaled based on the min and maximum value for Y axis.
Unfortunately, when I am using the component parameters ` yMaxValue=0.9` and `yMinValue=0.1`, the Y axis of the plot are showing the values from 100m to 1.1, which is definitely not my intention. Please check the image below.

### Environment Information

- **Package version(s)**: "@fluentui/react-charting": "5.12.19",
- **Browser and OS versions**: Edge

### Describe the issue:

When using LineChart component I would like the plots to be scaled based on the min and maximum value for Y axis.
Unfortunately, when I am using the component parameters ` yMaxValue=0.9` and `yMinValue=0.1`, the Y axis of the plot are showing the values from 100m to 1.1, which is definitely not my intention. 
My guess is that there is a strange behavior when dealing with values between 0 and 1.

<img width="627" alt="line_bug_from_0_to_1" src="https://user-images.githubusercontent.com/8457823/212941178-ca3a3469-1676-4c53-bcd8-23ed8521e3f8.png">

#### Expected behavior:

The Y axis are scaled according to the float values that are given, namely 0.1 and 0.9 or 0.0015 and 0.02.
and there are also ticks shown in between those values.

**Comment by AtishayMsft** [comment]
@ovysotska Could you share the code you are using so that we can repro it at our end.

**Comment by ovysotska** [comment]
Hi @AtishayMsft thanks for getting back to me.

Here is a code:

```
import "./styles.css";

import * as ReactCharting from "@fluentui/react-charting";

function FluentUiChart() {
  const chartProp = {
    chartTitle: "Line Chart",
    lineChartData: [
      {
        legend: "From_Legacy_to_O365",
        data: [
          {
            x: new Date("2020-03-03T00:00:00.000Z"),
            y: 0.1,
            onDataPointClick: () => alert("click on 217000")
          },
          {
            x: new Date("2020-03-03T10:00:00.000Z"),
            y: 0.3,
            onDataPointClick: () => alert("click on 217123")
          }
        ],
        color: "blue",
        onLineClick: () => console.log("From_Legacy_to_O365")
      }
    ]
  };
  return (
    <ReactCharting.LineChart
      data={chartProp}
      legendsOverflowText={"Overflow Items"}
      height={100}
      width={300}
      yMinValue={0.0}
      yMaxValue={0.2}
    />
  );
}

export default function App() {
  return (
    <div className="App">
      <h1>Testing LineChart</h1>
      <FluentUiChart />
    </div>
  );
}
```

It is possible to run in in react sandbox in the browser with the following dependencies: 
![image](https://github.com/microsoft/fluentui/assets/8457823/35d0eb5d-45bf-4f5d-9c84-55f7ad078f55)

The code above produces a plot with 2 points, where first y coordinate is 0.1 and second is 0.3.
So, I would like to plot to scale the y-axis automatically between 0.1 and 0.3. Such that instead of 1 it is 0.3 in this case as marked on the image below.
![line_chart_axis_y_shoud_be](https://github.com/microsoft/fluentui/assets/8457823/52f4ea3c-fe50-4a62-b73c-2dc62ab65757)


Moreover, if I change the values to ` yMinValue={0.1}` and `yMaxValue={0.3}`, the y scales show me some different values at all.
![image](https://github.com/microsoft/fluentui/assets/8457823/be29eee2-0fb6-4471-b9f5-3d4c31cd7f4d)


Thanks for your help!

**Comment by AtishayMsft** [comment]
@Shubhabrata08 we have received a use case where the datapoints are all integer but the axis ticks are showing as decimal as per fixing this issue.
Could you add a check to make decimal ticks only if any of the datapoints contain a decimal value.
See this dataset.

[
    {
        "x": "Su",
        "y": 0
    },
    {
        "x": "M",
        "y": 0
    },
    {
        "x": "Tu",
        "y": 0
    },
    {
        "x": "W",
        "y": 0
    },
    {
        "x": "Th",
        "y": 2
    },
    {
        "x": "F",
        "y": 3
    },
    {
        "x": "Sa",
        "y": 1
    }
]
