### ISSUE TITLE
[Bug]: props: onLoadingStateChange of image component returns wrong ImageLoadState enum when image does not load in browser

### ISSUE THREAD

**Issue by sk1649** [microsoft/fluentui#26399]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (28) x64 Intel(R) Core(TM) i9-10940X CPU @ 3.30GHz
    Memory: 38.55 GB / 63.72 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.55)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

NA

## Actual Behavior
When image does not load , callback prop : onLoadingStateChange  of Image component, gets invoke with enum = 1 (image load successfully) as argument . This happens intermittently.

## Expected Behavior
When image does not load , callback prop : onLoadingStateChange  of Image component, should get invoke with enum = 2 (image does not load) as argument.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@sk1649 I noticed what you wrote that the issue happens intermittently, but without a reproduction case we cannot debug the problem. I tried to repro and it works as expected (https://codesandbox.io/s/competent-knuth-l7y9bq?file=/src/App.tsx).

Can you please provide a reproduction case? 🙏
