### ISSUE TITLE
[Bug]: Not able to change the rating fluent UI control to have a partial rating

### ISSUE THREAD

**Issue by lovyjain** [microsoft/fluentui#26395]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 3.61 GB / 15.82 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/lovyjain/pen/VwBMNjV

## Actual Behavior
Not able to change the rating to have a partial value, when I have a on change event it fills the whole star value
--------
import styles from './RatingControl.module.scss';
import { IRatingControlProps } from './IRatingControlProps';
import { escape } from '@microsoft/sp-lodash-subset';
import * as React from 'react';

import { Rating, RatingSize } from '@fluentui/react';

const getRatingComponentAriaLabel = (label: string) => (rating: number, maxRating: number): string => {
  console.log(rating,maxRating)
  return `${label} rating value is ${rating} of ${maxRating}`;
};

 
// export const RatingControl: React.FunctionComponent = (props:IRatingControlProps,{}) => {
  export default function RatingControl(props:IRatingControlProps)
  {
   
    const [rating, setRating] = React.useState<any>(1.5);

    const onLargeStarChange = (ev: React.FocusEvent<HTMLElement>, rating: number): void => {
      setRating(rating);
    };
  
    return (
      <Rating
      max={5}
      rating={rating}
     
  
      onChange ={ onLargeStarChange}
      ariaLabelFormat="{0} of {1} stars"
    />
  );
};
---------------

## Expected Behavior
The stars should be able to select with partial values as 2.5, 3.5, etc

### Requested priority

Normal

### Products/sites affected

Fluent UI rating

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
This is really a feature add. The partial star values are used to display an averaged value. There is no click or keyboard events that allow triggering half star ratings. If you need more granularity, use a 10 star rating system.

**Comment by lovyjain** [comment]
Thanks for information and clarity.
