### ISSUE TITLE
[Bug]: Persona primary text/name doesn't vertically align in the center if other texts (like secondary, tertiary etc.) are missing

### ISSUE THREAD

**Issue by vincha2011** [microsoft/fluentui#26436]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 4.03 GB / 15.71 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.55)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/wandering-mountain-4k9v8b?file=/example.tsx

## Actual Behavior
When persona is provided only the name property, the name that appears in the persona is aligned to the top of the Avatar

## Expected Behavior
In the above scenario, the name should automatically vertically align to the middle (just like V8 persona component) rather than staying at the top

## V8 vs V9 
![image](https://user-images.githubusercontent.com/63151713/213741083-d240d1a9-9e89-4fd4-a187-9294feba5eca.png)

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by vincha2011** [comment]
Don't see any activity on this. Can anyone please triage this issue?

**Comment by layershifter** [comment]
Workaround:

```tsx
import { Persona, makeStyles } from "@fluentui/react-components";
import * as React from "react";

const useClasses = makeStyles({
  persona: {
    alignItems: "center",
    gridTemplateRows: "1fr"
  }
});

export const Default = () => {
  const classes = useClasses();

  return <Persona name="John Doe" className={classes.persona} />;
};
```

https://codesandbox.io/s/competent-danilo-p1sixg?file=/example.tsx
