### ISSUE TITLE
[Bug]: DataGrid: Code Sandbox examples not working

### ISSUE THREAD

**Issue by martinoss** [microsoft/fluentui#26433]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 17.11 GB / 47.71 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/31j93c?file=/example.tsx

## Actual Behavior
Compile errors: 
```
TypeError
(0 , _reactComponents.createTableColumn) is not a function
```
## Expected Behavior
Examples should work

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by martinoss** [comment]
Ok, the issue is that it imports from /react-components instead of /react-components/unstable

**Comment by layershifter** [comment]
Can repro on the latest deployment.
