### ISSUE TITLE
[Bug]: theme overwritten because useFluentProviderThemeStyleTag returns non global scope id causing duplicate fui-FluentProvider class names

### ISSUE THREAD

**Issue by flvyu** [microsoft/fluentui#26448]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz
    Memory: 33.30 GB / 63.84 GB
  Browsers:
    Chrome: 109.0.5414.75
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.61)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

 https://stackblitz.com/edit/express-simple-zmocuw

## Actual Behavior
When multiple different themes are loaded on a page using `FluentProvider`, the `FluentProvider` may have the same `fui-FluentProvider` id in the class name. 

The first id that would be created by the first `FluentProvider` would be `fui-FluentProvider1`. because the id initializes to 0 the first time. This id will be added to the body element of the page. This means that the fluent css tokens will be mapped to the css flass name `.fui-FluentProvider1`.

However, when another theme is loaded, the id will also initialize to 0 the first time causing the same id `fui-FluentProvider1` to be appended to an element on the page, thus having the fluent css tokens overwritten.

As a result, because the ids are the same the theme that is loaded the latest will overwrite the previous theme changing the UI of the whole app.

Digging deeper, I found that FluentProvider is calling `useFluentProviderThemeStyleTag` which creates the class names that contain the `fui-FluentProvider1`. `useFluentProviderThemeStyleTag` calls useId from '@fluentui/react-utilities' which does not store the current id in the global scope, unlike the `useId` implementation in `@fluentui/react-hooks`.

## Expected Behavior
Class names generated by `useFluentProviderThemeStyleTag` should be unique across FluentProvider renders so that it does not cause themes to be overwritten.

### Logs

```shell
N/A
```

### Requested priority

Blocking

### Products/sites affected

Fluent V9

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
>  useFluentProviderThemeStyleTag calls useId from '@fluentui/react-utilities' which does not store the current id in the global scope, unlike the useId implementation in @fluentui/react-hooks.

Storing ids in global scope is unsafe for SSR as it will be preserved there: on first render starts with 0, on second starts with N 💥 That's the reason why `useId()` implementation does not use that.

> When multiple different themes are loaded on a page using FluentProvider, the FluentProvider may have the same fui-FluentProvider id in the class name.
>
> https://codesandbox.io/s/recursing-saha-mqgey6?file=/src/index.tsx:249-250

@flvyu does not seem that the example repros the problem that you're describing:

![image](https://user-images.githubusercontent.com/14183168/214005272-7af214fc-3eb5-483d-a250-7b940a4b4d48.png)

**Comment by flvyu** [comment]
@layershifter We have a similar setup to the example, which I thought would reproduce it but unfortunately did not. Looking further into the issue on our end, the problem, although still due to conflicting Ids, seem to be happening because there is two bundles containing the Fluent V9 useId(). One is coming from the host app which has it's own bundle. The other is from a package that uses the same version of Fluent V9, but seems to be including it's own copy of the useId() bundle. At runtime, both of these are being used, causing the useId() to be initialized at 0, creating duplicate Ids.

I'll see if I can get the example in this state for a repro.

**Comment by layershifter** [comment]
> @layershifter We have a similar setup to the example, which I thought would reproduce it but unfortunately did not. Looking further into the issue on our end, the problem, although still due to conflicting Ids, seem to be happening because there is two bundles containing the Fluent V9 useId(). One is coming from the host app which has it's own bundle. The other is from a package that uses the same version of Fluent V9, but seems to be including it's own copy of the useId() bundle. At runtime, both of these are being used, causing the useId() to be initialized at 0, creating duplicate Ids.

Yeah, this indeed could cause collisions. A fair note is that v9 utilises React Context heavily and there might other unobvious side-effects if it is bundled twice.

Is it possible to deduplicate Fluent? For example, share the same chunk?

**Comment by flvyu** [comment]
We have two separate bundles that are bundled as part of separate bundle tasks so they can not be deduplicated.

**Comment by layershifter** [comment]
@flvyu I have built the repro https://stackblitz.com/edit/express-simple-zmocuw 😉

**Comment by flvyu** [comment]
Thank you! I suspected something like that, I tried something similar locally with create-react-app but was not able to get it working, glad to see how it's done now :)
