### ISSUE TITLE
[Feature]: Load state tracking for Image component

### ISSUE THREAD

**Issue by Arthur-MSoft** [microsoft/fluentui#26452]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Fluent UI v8 [Image](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/image) has a load state enum (ImageLoadState) that is quite handy. It would be very helpful to have a similar feature for Fluent UI v9

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by layershifter** [comment]
@Arthur-MSoft you can use `onLoad` & `onError` callbacks directly:

```tsx
<Image
  onLoad={() => console.log("An image loaded!")}
  onError={() => console.log("An image failed to load!")}
/>
```

https://codesandbox.io/s/serene-julien-vhiscu?file=/example.tsx

---

Is there anything special in `onLoadingStateChange` that is helpful for you?

**Comment by GeoffCoxMSFT** [comment]
@tudorpopams Could you kindly assign this issue to the dev who now owns the Image component?

**Comment by Arthur-MSoft** [comment]
@layershifter the callbacks are perfect for what I need. Thank you.
I think we can look into updating the [documentation](https://react.fluentui.dev/?path=/docs/components-avatar--default) to reflect what callbacks are available for use

**Comment by layershifter** [comment]
> I think we can look into updating the [documentation](https://react.fluentui.dev/?path=/docs/components-avatar--default) to reflect what callbacks are available for use

If a component or a slot represents a HTML element it will have all its DOM props i.e. `Image` has all props that `img` has. If we will list all props of a native element in docs IMO it will not be useful as it's more than 50 properties 💥 

For example, v8 documentation for `Image` shows that it extends some interface (https://developer.microsoft.com/en-us/fluentui#/controls/web/image):

![image](https://user-images.githubusercontent.com/14183168/216036143-d6985166-e358-4328-af90-2b6775d6dea8.png)

Will it be helpful for you? Or do you other ideas? 🤔

**Comment by Arthur-MSoft** [comment]
I think that works. Showing what interface a component extends will suffice

**Comment by layershifter** [comment]
@Arthur-MSoft cool, I created an issue to followup on this #26585.

**Comment by Arthur-MSoft** [comment]
Thanks @layershifter
