### ISSUE TITLE
V9: Dialog BorderRadius not using Theme values

### ISSUE THREAD

**Issue by blendsdk** [microsoft/fluentui#26450]
Hi,

It seems that the Dialog component in V9 does not honor the Border Radii from Theme:

### The Code
https://github.com/microsoft/fluentui/blob/294d8a773e2d154f04addf24ff8600a7bb408a31/packages/react-components/react-dialog/src/contexts/constants.ts#L4

https://github.com/microsoft/fluentui/blob/294d8a773e2d154f04addf24ff8600a7bb408a31/packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurfaceStyles.ts#L47

### Theme:
https://react.fluentui.dev/?path=/docs/theme-border-radii--page

### Several other places:

![image](https://user-images.githubusercontent.com/5524595/213920420-ac124edf-387f-4e1b-8412-25dc5c61294b.png)

**Comment by bsunderhus** [comment]
Thanks for reporting this @blendsdk! Seems like the design spec for the Dialog doesn't include the proper tokens to be used, and that ended up being reflected on the implementation.

I'll get in contact with designers to properly update the design spec to include the right token. In the meantime I'll open a PR to modify this to use `borderRadiusXLarge` as I assume it'll be the expected token.

**Comment by bsunderhus** [comment]
Regarding the other components I'll bring this subject up and see if we can investigate it all at once to ensure we're following the proper tokens everywhere! @blendsdk

**Comment by blendsdk** [comment]
@bsunderhus thank you for fixing.
