### ISSUE TITLE
Dropdown lacking a search bar, select all

### ISSUE THREAD

**Issue by jeffersoneagley** [microsoft/fluentui#26469]
## Describe the feature that you would like added
The dropdown needs the option for a "Search bar" and "select all". ComboBox does not do the same thing, and does not align with the design I was give (which appears to be a stock MS control from somewhere). This is a very common requirement for dropdowns.

## What component or utility would this be added to
Dropdown

## Have you discussed this feature with our team, and if so, who
Yes, this has come up repeatedly in accessibility bugs now.

## Additional context/screenshots
Here's a screenshot of our current version of this:
![image](https://user-images.githubusercontent.com/15936010/214173942-4704a8ed-7bd4-4756-a9e6-445373d6b96f.png)
This implementation fails accessibility no matter what we do, because the testers are not ok with it being an overloaded ContextualMenu and Dropdown still doesn't seem to have any way to add this feature. (example: https://codepen.io/newlogics/pen/dyKGeGV)

I vaguely remember Fluent's north star package supporting this at some point, but it's been a few years since that, and I'm not sure I could get the team on board for switching to north star as it's considered experimental.

## Did you search for this issue already?
Yes, and it has been asked for multiple times before, but seems to always get auto-closed rather than resolved. 

#21746

**Comment by maxburs** [comment]
+ 1

Our team needed this enough to roll our own
