### ISSUE TITLE
[Bug]: Click action not working for the elements rendered outside the panel wrapper elements.

### ISSUE THREAD

**Issue by IndrajithSrinivasan** [microsoft/fluentui#26494]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Chrome browser
React platform
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/react-3mkyhk?file=index.js,index.html,package.json,index.css

## Actual Behavior
The click action is not working for the button outside the panel elements.

Sample: https://stackblitz.com/edit/react-3mkyhk?file=index.js,index.html,package.json,index.css

## Expected Behavior
Click action must work for the elements outside the panel elements, which are placed inside the body.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@IndrajithSrinivasan by default `Panel` is a modal and blocks UI. If you would you like to make it non-modal, you need to configure it:

```ts
<Panel
  // this prop makes the panel non-modal
  isBlocking={false}
/>
```

https://developer.microsoft.com/en-us/fluentui#/controls/web/panel

---

Does it solve your problem?

**Comment by IndrajithSrinivasan** [comment]
Thanks for your suggestion, i tried but it doesn't help,

@layershifter It makes it as non-modal but still the outside button click action is prevented. Updated the sample with block enabled, check the below sample.

Sample: https://stackblitz.com/edit/react-3mkyhk-jlbqlc?file=index.js

**Comment by layershifter** [comment]
Your sample does not seem correct to me:
- it uses ancient version of  `office-ui-fabric-react@0.88.0`
  ![image](https://user-images.githubusercontent.com/14183168/214587296-a231c385-ded8-4236-b4c9-97657e418e70.png)
- it uses React 18, but v7 does not have support for React 18 🙃

I bumped `office-ui-fabric-react` to latest 7 and downgraded React 17. Works as expected: https://stackblitz.com/edit/react-3mkyhk-zieezl?file=index.js
