### ISSUE TITLE
[Bug]: [Popover] Modalizer must have either aria-label or aria-labelledby 

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#26534]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 17.96 GB / 31.91 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.41)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/bold-neco-fuin5l

## Actual Behavior
When open the popover, I get console log of this warning. 

<img width="496" alt="image" src="https://user-images.githubusercontent.com/39588094/215117758-4b9fc664-30c0-413d-aa81-7a2e6830d988.png">

It can be fixed by adding aria-label / aria-labelledby to popover surface. But still wondering if this is an accessibility issue. 

## Expected Behavior
Expect to not have this warning;

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
Will be fixed by a tabster bump after microsoft/tabster#230
