### ISSUE TITLE
[Bug]: SpinButton - missing Home and End navigation 

### ISSUE THREAD

**Issue by emilyamclean** [microsoft/fluentui#26539]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Hi Sean! The SpinButton component is currently missing the option to navigate to the first and last values by using the Home and End key controls, respectively. 

See Figma reference here: https://www.figma.com/file/4ErMjZ0Mi72legBtMAbbEp/SpinButton?node-id=286%3A50107&t=6b2K5k2hqKNkXgjO-4

### Have you discussed this feature with our team

Sean Monahan

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by spmonahan** [comment]
@emilyamclean In looking more closely at the code Home and End are already supported but only when min or max are set, respectively. You can see this in the ["bounds" example](https://react.fluentui.dev/?path=/docs/components-spinbutton--default#bounds).

This is a good opportunity to improve our docs though! I've updated the default example to include both min and max so Home/End hotkeys are observable. I've also updated the "bounds" description to discuss this functionality and finally added more tests to ensure it's well covered and behaving properly.
