### ISSUE TITLE
[Callout]: After the callout is rendered and the target element moves its location, the callout should move accordingly.

### ISSUE THREAD

**Issue by junchen1** [microsoft/fluentui#26551]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

N/A

## Actual Behavior
The callout stays at the same location.

## Expected Behavior
The callout should move together with the target.

### Logs

```shell
N/A
```

### Requested priority

Normal

### Products/sites affected

N/A

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@junchen1 Sorry, but the problem is unclear to me. Can you please fill the issue template fully i.e. provide reproduction and better explainer? 🙏

**Comment by junchen1** [comment]
The callout was originally aligned with "Sort by size". But the pink bar with string "Your storage is 90% full. If you run out" is rendered after the callout is rendered and pushed the "Sort by size" down. Then the callout is aligned to the wrong location.

[cid:e8aa3154-5bcd-4482-9616-8477e9be921c]

Thanks,

Jun
________________________________

**Comment by micahgodbolt** [comment]
Callouts are typically placed on a separate layer, and positioned absolutely. They are not built to travel with their target. In the case the page scrolling, or resizing, the Callout's onDismiss is fired. We would expect the same thing to happen if the target moved. 

If you would like it to track with the DOM, you can use the `doNotLayer` prop to avoid layering and to place the callout within the DOM of where it is rendered. This will allow it to move with the page, but often has issues with clipping.
