### ISSUE TITLE
[Feature]: Size prop for Alert Component

### ISSUE THREAD

**Issue by pitric** [microsoft/fluentui#26561]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

The Preview Component Alert does not have a size prop.

It would be nice to set the size of the alert to small, medium and large, similar to other components like Label, Input and Textarea.

### Have you discussed this feature with our team

No.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by layershifter** [comment]
I checked the design spec and it does not have definitions for different sizes. Will assign this to PMs to handle.
