### ISSUE TITLE
[Bug]: Dropdown clear indicator should not be aria-hidden

### ISSUE THREAD

**Issue by 1hw7** [microsoft/fluentui#26563]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 6.28 GB / 31.71 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.61)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://fluentsite.z22.web.core.windows.net/0.65.0/components/dropdown/definition

## Actual Behavior
When you request "show numbers" with voice access, there is no number for the clear indicator because it has aria-hidden = true. 

## Expected Behavior
If aria-hidden is removed from the clear indicator, then show numbers does successfully show a number for the clear indicator
issue can be observed on fluent site when asking for show numbers

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
![image](https://user-images.githubusercontent.com/14183168/216002065-9f2ac387-3c45-49d5-a6ce-7946cd1b7288.png)

To clarify, it's about that button.
