### ISSUE TITLE
docs: show props of native parent native elements in props table

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#26585]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

We need to show in docs that our components support props from HTML primitives to avoid confusion for customers (https://github.com/microsoft/fluentui/issues/26452#issuecomment-1411917191). For example, `Image` supports props from `img`.

- List all props from a native element (less preferred as it will create a lot of noise)
- List all props from a native element under a spoiler
- Show the inheritance like in v8 docs
  ![image](https://user-images.githubusercontent.com/14183168/216053713-47e78d7f-7774-4fa5-b6d9-9bf227856192.png)

### Have you discussed this feature with our team

No

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mainframev** [comment]
Resolved in #31829
