### ISSUE TITLE
[Bug] Slots should accept a render function as a shorthand value

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#26595]
### Current behavior

Using a render function for a slot requires passing a props object with the render function as its children:

```jsx
  <Button icon={{ children: (Component, props) => <AnimalCat20Filled {...props} /> }} />
```

If you pass the render function as a shorthand value, it is silently ignored and nothing is rendered:
```jsx
  <Button icon={(Component, props) => <AnimalCat20Filled {...props} />} />
```

### Expected

Render functions should be allowed as shorthand values.

**Comment by layershifter** [comment]
@behowell FYI, this is not in the spec for slots https://github.com/microsoft/fluentui/blob/master/specs/Slots.md. It's not a bug, it's a feature.

**Comment by behowell** [comment]
@layershifter There's nothing preventing you from writing your second example with the `children:` syntax:
```jsx
<Component slot={{ children: (Component, props) => <Component foo {...props} /> }} />
```
It might be that it causes problems in some cases (hopefully not many/any?), but limiting the shorthand syntax won't prevent it from happening.

As of now, using the shorthand syntax doesn't generate any type errors or runtime errors, and fails silently. That should probably be fixed regardless.

**Comment by layershifter** [comment]
> As of now, using the shorthand syntax doesn't generate any type errors or runtime errors, and fails silently. That should probably be fixed regardless.

https://codesandbox.io/s/fervent-galois-o6em0d?file=/example.tsx

Wow, this indeed is a bug. I would start with fixing it.

**Comment by behowell** [comment]
On further investigation, I was mistaken above. The types do not allow render functions as shorthands. It only allows SlotShorthandValue types:
```ts
export type SlotShorthandValue = React.ReactChild | React.ReactNode[] | React.ReactPortal;
```

And given that it's by design that slot shorthand doesn't accept render functions, I'm going to close this issue.
