### ISSUE TITLE
v8: build problem with React18

### ISSUE THREAD

**Issue by blendsdk** [microsoft/fluentui#26606]
Hi,

I am referencing `@fluentui/react v8.105.2` which is using `@fluentui/utilities v8.13.5`
My build break due the following error:

## error:

`
 node_modules/@fluentui/utilities/lib/DelayedRender.d.ts(7,52): error TS2694: Namespace 'React' has no exported member 'Props'.
`

## cause:

https://github.com/microsoft/fluentui/blob/09da68fa3dd4695fb969b76814d76f88e671111f/packages/utilities/src/DelayedRender.tsx#L10

## possible fix:

```
  *
  * @public
  */
-export interface IDelayedRenderProps extends React.Props<{}> {
+export interface IDelayedRenderProps {
     /**
      * Number of milliseconds to delay rendering children.
      */
```

**Comment by layershifter** [comment]
Can you please provide a minimal reproduction case (CodeSandbox or a repo)?

**Comment by blendsdk** [comment]
@layershifter, I am unable to reproduce this in CodeSandbox. Give me until Friday and then close this issue please.
