### ISSUE TITLE
[Bug]: v9 - Focus ring does not disappear when user switch from keyboard to mouse

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/fluentui#26609]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
v9.11.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-menu-menu--default

## Actual Behavior
Focus ring does not disappear when user switch from keyboard to mouse

## Expected Behavior
Focus ring should disappear when user switch to mouse. 
 
Re-pro step:
1. Open https://react.fluentui.dev/?path=/docs/components-menu-menu--default
2. Tab until focus land on the first example: 
     <img width="227" alt="image" src="https://user-images.githubusercontent.com/28751745/216376763-3d63be82-da48-4382-b70e-4a67f64fc134.png">
3. CLICK on the button to open menu, and hover on each menu item. Focus ring should disappear, but it's not the case.
     <img width="267" alt="Screenshot 2023-02-02 at 17 04 22" src="https://user-images.githubusercontent.com/28751745/216377115-b7c97503-6de2-45f7-ab14-7c4313578ffe.png">

_I used menu in the re-pro step. But I'm not sure if this issue is Menu only_

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
offline I met with @YuanboXue-Amber  and @george-cz to try and repro this bug:

* On windows I could not repro this bug on chrome/edge/firefox
* On M1 Mac @george-cz  could not repro this on chrome

However we did see @YuanboXue-Amber  repro this on her mac, we noticed that the problem only occurs if 'click on tap' is enabled in MacOS (and only for her mac), the harder click on the touchpad could not repro this bug
