### ISSUE TITLE
[Bug]: Focus gets trapped in TabList when followed by a Toolbar

### ISSUE THREAD

**Issue by nkirchem** [microsoft/fluentui#26610]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
    Memory: 29.57 GB / 63.73 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/relaxed-rui-lwzc72?file=/example.tsx

## Actual Behavior
When a TabList is directly followed by a Toolbar, you can tab to the TabList, arrow through the tabs, then pressing tab again moves focus to the first Toolbar item. All good.

But in the same scenario, if the Toolbar is wrapped by a surrounding div element, focus gets trapped in the tab list. Once you are in the tab list, the tab key no longer has any effect. You can shift-tab outside but can't get focus past the tab list, even if there is focusable content below the toolbar.

See a simple repro here:
https://codesandbox.io/s/relaxed-rui-lwzc72?file=/example.tsx

I don't think the Toolbar is at fault here, I can repro the same thing if I use a second TabList in place of the Toolbar above. Likely another tabster component following a tab list causing issues when the second component is wrapped in a div.

## Expected Behavior
Focus should continue to work in this scenario. This is a common scenario in our application. In our tabbed views, some tabs may have a Toolbar at the top of them. We have a div around the tab's content, and this seems to cause an issue.

### Requested priority

High

### Products/sites affected

Microsoft Azure Machine Learning

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Yeah, you can take Toolbar out of the equation. A TabList followed by any Tabster type component inside of a div.

**Comment by ling1726** [comment]
@nkirchem I can no longer repro this bug with the lateest 9.15.6

![tablist bug](https://user-images.githubusercontent.com/20744592/222112772-ce2424c3-199b-4e44-bfba-a4fa67b0fa9f.gif)

If I'm try the repro incorrectly, let me know and I can reopen the issue
