### ISSUE TITLE
[Bug]: Dropdown in 9.12 not compatible with React 18 Strict mode

### ISSUE THREAD

**Issue by noynek** [microsoft/fluentui#26651]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
none
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/cocky-golick-noknhb?file=/example.tsx

## Actual Behavior
With the recent move of the <Dropdown> component from unstable into the main library, the component is broken. When you click on the dropdown the following error appears.
`Failed to execute 'querySelector' on 'Element': '#fluent-option:r3:' is not a valid selector.`

Interestingly, we discovered that adding an `id` to the `<Option>`s fixes the error.

## Expected Behavior
Dropdown should display a list of options with throwing an exception

I don't know how there isn't already a bug filed. Am I missing something?
Here's a sandbox environment to repro. 
https://codesandbox.io/s/cocky-golick-noknhb?file=/example.tsx

![image](https://user-images.githubusercontent.com/2458230/216677489-2b9e11df-56eb-4f54-9333-05b1375e7c56.png)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
This looks like a React 18 related bug. Did you recently upgrade to React 18, or did it used to work in React 18?

**Comment by noynek** [comment]
> This looks like a React 18 related bug. Did you recently upgrade to React 18, or did it used to work in React 18?

No change in React version for us. I don't think we changed to strict mode either. I wanted to be sure which is why I used the codesandbox link from the fluent documentation and just updated the react-components version. Thanks

**Comment by simon5057** [comment]
Hi there, I encountered the same issue while using the Combobox component, I think the selector string "#fluent-option:r3:" cannot be recognized by the browser and then crashes the application. I hope you can solve it soon. Thanks!

**Comment by simon5057** [comment]
Hi @noynek , I just found out You can add the prop `id` to the `Option` component as a temporary solution.
Like this,
``` tsx
{options.map((option,i) => (
  <Option id={`my-option-${i}`} key={option} disabled={option === "Ferret"}>
    {option}
  </Option>
 ))}
```

**Comment by chenxinyanc** [comment]
> This looks like a React 18 related bug. Did you recently upgrade to React 18, or did it used to work in React 18?

I came here due to the same error. They used to work until recent upgrades in Fluent UI React packages.

**Comment by sopranopillow** [comment]
Hi @noynek, could you check if this issue has been resolved?
