### ISSUE TITLE
[Bug]: Unable to see all records in DetailsList

### ISSUE THREAD

**Issue by salmanmsft** [microsoft/fluentui#26686]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
7.8.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

This is not deterministic issue.

## Actual Behavior
![image](https://user-images.githubusercontent.com/124574952/216959201-4a67a97a-8379-41ae-98fc-ebc0151ca4f8.png)

If you see above image, we are not able to see all 100 records even after scrolling end of the grid, it is showing nearly 74 records and when we start collapsing groups one by one then non-rendered groups start showing up and after collapsing all the groups, we were able to see only 96 records but never 100 also, we can see unnecessary space here.
This issue not coming for small number of groups (less than 6-7 groups containing 30-40-50 records each making it 100 records for the page) it will come If we have large number of groups containing 4-12 records per group.

## Expected Behavior
Able to see all 100 records at once if we are passing 100 records in any number of groups to list and no unnecessary spaces will be generated.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
There is an FAQ on the List component page that has some troubleshooting tips for scrolling.

https://developer.microsoft.com/en-us/fluentui#/controls/web/list

Otherwise, we need some type of reduce repro (in a codepen or codesandbox) to triage this issue.
