### ISSUE TITLE
SpinButton with increments, Step is always 1 or 2 

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft/fluentui#26684]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 91.14 GB / 127.67 GB
  Browsers:
    Internet Explorer: 11.0.22000.120

PS C:\DATA\Sources\Repos\SPFx15\DpcAllJobsScreen>
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/ofergal/pen/mdjoavj

## Actual Behavior
SpinButton The increments are 2 at the time even though the step is set to 10

## Expected Behavior
when  the step is set to 10 it should go from 100 % to 110 % not 102 %

Thank you

### Requested priority

Low

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
This example using onIncrement/onDecrement to manually change the value. The step value won't have any effect.

![image](https://user-images.githubusercontent.com/1434956/217038018-fbc5da1a-401b-4c10-a5ad-3013ac1ad9a3.png)

**Comment by Ofer-Gal** [comment]
So this by design? 
I tried to add the step to the numericValue but it creates endless loop :-)
