### ISSUE TITLE
[Bug]: disableRestoreFocus not working in Modal & Dialog

### ISSUE THREAD

**Issue by j2kenton** [microsoft/fluentui#26695]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Memory: 42.56 GB / 63.73 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.78)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/j2kenton/pen/jOpRbrL

## Actual Behavior
Open Modal or Dialog with `disableRestoreFocus` via the keyboard. Close the modal/dialog. Focus is still restored to the button that triggered opening the modal/dialog.

## Expected Behavior
Focus should not be restored, as stated in the [documentation](https://developer.microsoft.com/en-us/fluentui#/controls/web/references/iaccessiblepopupprops#IAccessiblePopupProps:~:text=If%20false%20(the%20default)%2C%20the%20control%27s%20FocusTrapZone%20will%20restore%20focus%20to%20the%20element%20which%20activated%20it%20once%20the%20trap%20zone%20is%20unmounted%20or%20disabled.%20Set%20to%20true%20to%20disable%20this%20behavior.):

> If false (the default), the control's FocusTrapZone will restore focus to the element which activated it once the trap zone is unmounted or disabled. Set to true to disable this behavior.

### Requested priority

Normal

### Products/sites affected

ADP Portal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Setting disableRestoreFocus is passed on to the FocusTrapZone and tells the FTZ to not manually set focus when it is dismiss, but let the browser determine where focus should go. In this case, the browser is putting the focus back on the button. i.e. the prop is working fine, it just doesn't have any effect in this scenario.
