### ISSUE TITLE
Details List Grouped giving accessibility issue "Ensures ARIA attributes are allowed for an element's role"

### ISSUE THREAD

**Issue by satyamamit** [microsoft/fluentui#26694]
### Environment Information

- **Package version(s)**: 8.82.1
- **Browser and OS versions**: Chrome & Win 11

### Describe the issue:

We are seeing aria-allowed-attr on Details List- Grouped when running accessibility Insights on the page.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/544943/217069632-d45f518a-fa8d-4070-b070-618e106638ae.png)

#### Expected behavior:
We shouldn't be seeing this accessibility error for Details list.

**Comment by micahgodbolt** [comment]
Looks like aria-expanded is the attribute of concern.

https://developer.mozilla.org/en-US/docs/web/accessibility/aria/attributes/aria-expanded#rows

It looks like role="row" can use aria-expanded if it is inside of a treegrid, but our grouped details list is role='grid'. 

We might have a valid reason for doing it this way instead. I'll check.

**Comment by micahgodbolt** [comment]
This is actually intentional. Here is the explanation:

> We have kept the grid role for Grouped DetailsList intentionally, since treegrid does not have as good support for table navigation as grids do.
> 
> For this reason, GroupedList uses treegrid, since it functions more like a tree (e.g. no column headers), while Grouped DetailsList keeps the grid semantics.
> 
> Grouped DetailsList also uses `aria-expanded` on row elements because:
> It actually works in most screen readers, allowing users to know that a row is expandable, and what its current state is.
> It causes no harm when it doesn't work.
> 
> TL:DR; There are no user-facing downsides to keeping it, and it provides some benefit.
