### ISSUE TITLE
[Bug]: SpinButton fails to emit event on single digit change

### ISSUE THREAD

**Issue by lingtjien** [microsoft/fluentui#26741]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Can be reproduced using the latest documentation spinbutton component

https://react.fluentui.dev/?path=/docs/components-spinbutton--default
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-spinbutton--default

## Steps to reproduce
1. go to the provided link of the SpinButton component fluentui v9 documentation
2. go to the default example (first example from the top of the page)
3. click on the spinbutton content (the number that is by default set to 10) to focus the component field input
4. use the shortcut `Ctrl+A` to select the whole input (10 should be selected now)
5. type the number `2` on your keyboard and hit `enter` on your keyboard

## Actual Behavior
the spinbutton value changes back to the original value 10

## Expected Behavior
the spinbutton value changes to the new value 2

(Side note: typing `02` in step 5 does produce the desired result)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@lingtjien This is fixed and has been released in [9.15.0](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-components/CHANGELOG.md#9150).
