### ISSUE TITLE
[Feature]: Custom Styles for Table

### ISSUE THREAD

**Issue by Aloento** [microsoft/fluentui#26746]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

The table component in the old version 8 is called `DetailsList`, which support setting `className` and `headerClassName` in `IColumn`.

I use it to adjust the proportion of each column occupied.
There are times when it is not enough to just set the max-min and default px and more important is the percentage.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by micahgodbolt** [comment]
All slots will be able to take in custom classNames. Can you write a codesandbox demo of what you are trying to do, and how you'd like to be able to pass in a className?
