### ISSUE TITLE
ProgressBar: Indeterminate variant can have Validation State

### ISSUE THREAD

**Issue by ValentinaKozlova** [microsoft/fluentui#26756]
**Steps:**
Create Progress bar with the following props:
```jsx
<ProgressBar validationState="error" />
<ProgressBar thickness="large" validationState="success" />
```
## Actual Behavior
![image](https://user-images.githubusercontent.com/11574680/217508504-d9ad2cc5-0d94-4e07-a5db-de8cd7f2a3fe.png)
![image](https://user-images.githubusercontent.com/11574680/217508182-7fe4cb80-f652-4a24-9898-a6a95ffa82be.png)

## Expected Behavior
By documentation, Indeterminate is a separate variant that doesn't include validation states.
![image](https://user-images.githubusercontent.com/11574680/217508060-d8d95993-3c9c-4b78-86a4-437231d0f55c.png)

**Comment by tomi-msft** [comment]
Fixed by #27038
