### ISSUE TITLE
Need to add a story to ProgressBar that shows how to add a label using Field

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#26754]
The design spec specifies label and description text fields, these are not implemented currently

![image](https://user-images.githubusercontent.com/20744592/217506216-9fb48487-fe4e-49b9-8203-26bef41bff64.png)

**Comment by ling1726** [comment]
Feel free to close this if this will be implemented as a part of @behowell's work on Field

**Comment by behowell** [comment]
Yes, the intent is to use Field, like:
```jsx
<Field label="Label" hint="Helper text">
  <ProgressBar />
</Field>
```

I'm going to update this issue to track adding a story to ProgressBar that references Field.

**Comment by behowell** [comment]
Waiting for Field to be released as stable.
