### ISSUE TITLE
[Feature]: Documentation Sample

### ISSUE THREAD

**Issue by kkazala** [microsoft/fluentui#26777]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Would you be interested in adding a new sample to the https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist?
I'm using DataList component to generate a heatmap: https://codepen.io/kkazala/pen/yLqWMmm and perhaps it would be a good addition?
Please let me know if you are interested

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by micahgodbolt** [comment]
V8 controls are mostly on maintenance mode. Our current focus is on our new v9 controls. Feel free to add that link in our discussions as a show and tell.

https://github.com/microsoft/fluentui/discussions
