### ISSUE TITLE
Some codesandbox exports are missing the `@fluentui/react-components` dependency.

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#26774]
Some codesandbox exports are missing the `@fluentui/react-components` dependency. Here are a few components affected. Simply go to the component page on https://react.fluentui.dev and export the default example to codesanbox

* MenuList
* Radio
* RadioGroup
![image](https://user-images.githubusercontent.com/20744592/217779825-8b3d60f5-e942-4efa-87a7-387764e46846.png)

![image](https://user-images.githubusercontent.com/20744592/217779854-8e4e9177-d4fb-4e5e-888f-7f68e2128009.png)

**Comment by george-cz** [comment]
Closing, this has been fixed in https://github.com/microsoft/fluentui-storybook-addons/pull/34
