### ISSUE TITLE
[Bug]: Focus escapes from Dialog

### ISSUE THREAD

**Issue by zjhch123** [microsoft/fluentui#26771]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 5.24 GB / 31.72 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.70)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/upbeat-bohr-2krd8q?file=/example.tsx

## Actual Behavior

When I use the keyboard (`Tab`) to control the focus, I find that the focus can escape from the Dialog.

See the gif here:

![focus](https://user-images.githubusercontent.com/12215513/217760725-5a6c1be0-91e6-4bda-ad1f-f7f071dbdb56.gif)

(I'm not sure if it is an a11y bug)

## Expected Behavior

The focus should be restricted to the Dialog and could not escape from Dialog, just like the behavior in v8.

### Logs

```shell
No
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by lancelodliu** [comment]
@micahgodbolt according to doc, this is not by design I think.
![image](https://user-images.githubusercontent.com/19603852/217991122-267be0ca-a0e1-4aa7-bd63-f3edb4e58f52.png)

**Comment by zjhch123** [comment]
Thank you @lancelodliu!

Hi @micahgodbolt, according to the [w3c - dialog-modal](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/) document, the current tab behavior doesn't seem to meet the requirement.

![image](https://user-images.githubusercontent.com/12215513/217993076-95a35368-fa62-4c4b-b57a-1227b4dd8ca2.png)

Could you please double-check if it is as designed? Thank you very much.
