### ISSUE TITLE
[Bug]: Spinner styles defined in fluent2-theme coerces all the spinners into the same 32x32 size

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#26785]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
With CodeSandbox:
    "@fluentui/fluent2-theme": "8.104.19",
    "@fluentui/react": "8.105.5",
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/fluent-ui-react-v8-spinner-tcxiz9?file=/src/App.tsx

## Actual Behavior
![image](https://user-images.githubusercontent.com/50703224/217827867-1dca5997-f87d-4cbd-bac2-dd01e9b57e15.png)

## Expected Behavior
Fluent2WebLightTheme shouldn't fix the size of spinners.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chenxinyanc** [comment]
Related source code:
https://github.com/microsoft/fluentui/blob/0a3196e08cfeba3068f4100e0faff2771a24fcdc/packages/fluent2-theme/src/componentStyles/Spinner.styles.ts#L13-L14

**Comment by micahgodbolt** [comment]
Thanks @chenxinyanc. We certainly support different size spinners in Fluent 2, so no reason we should force them all to be 32px.
