### ISSUE TITLE
[Feature]: Neutral Stroke 4 token

### ISSUE THREAD

**Issue by vivwhsu** [microsoft/fluentui#26794]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Requesting one new token
colorNeutralStrokeSubtle

![Screenshot 2023-03-03 at 2 21 01 PM](https://user-images.githubusercontent.com/31045149/222844797-6ba25909-a72f-4fff-bb7f-33ce225c1cf0.png)
https://www.figma.com/file/KB9oUjMKen2cKnyPG7RgdS/Design-tokens-superset?node-id=38002%3A79865&t=Mupzpdnt6AqP3byx-4
### Have you discussed this feature with our team

Yes

### Additional context

For use of dividers for headers and panels. needed a darker color for dark theme
![image](https://user-images.githubusercontent.com/31045149/217958734-ec8d8d86-8fbd-4b13-a105-6e4960a8b194.png)
![image](https://user-images.githubusercontent.com/31045149/217958771-d1eb5645-2ca7-4bbe-8459-01b2ba0074c2.png)
![image](https://user-images.githubusercontent.com/31045149/217958811-2a2c42a9-c797-4ed7-b38d-1d234a3b64b8.png)
![image](https://user-images.githubusercontent.com/31045149/217958829-2d2dcc67-3c67-421d-be48-2d067bdca8ec.png)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by miroslavstastny** [comment]
This token is still being discussed in Design, cc @daisygeng, @redongreen
