### ISSUE TITLE
[Bug]: Disabled <MenuItem> still highlights its icon when hovered

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#26802]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Using CodeSandbox
    "@fluentui/react-components": "9.15.0",
    "@fluentui/react-icons": "latest",
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/fluent-ui-v9-disable-menu-item-4epm1g?file=/package.json

## Actual Behavior
![](https://user-images.githubusercontent.com/50703224/189070350-70084415-8697-4b87-aed8-376697afb775.gif)

## Expected Behavior
The "Edit" icon should keep gray even if it's being hovered on.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chenxinyanc** [comment]
Re-opened this bug from #24713 instruction of https://github.com/microsoft/fluentui/issues/24713#issuecomment-1417292602.

**Comment by micahgodbolt** [comment]
Sorry for missing the initial bug report. This is certainly valid and we will fix it.

**Comment by elibery** [comment]
I am having the same issue for the MenuItem
