### ISSUE TITLE
[Bug]: DetaislList functionality change tab index dynamically and cause accessibility bugs

### ISSUE THREAD

**Issue by nadavWeisler** [microsoft/fluentui#26818]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
8.101.0
```

### Are you reporting Accessibility issue?

yes

### Reproduction

create detailed list with 3 buttons  in a row and try to access them using the TAB key

## Actual Behavior
After creating group header, with 3 role=button components, only the first is accessible using the TAB key. Even that all the components with tab_index = 0, its dynamically changed to -1.

## Expected Behavior
All 3 components will have tab_index = 0 and accessible by the TAB key

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Can you supply a codepen of this behavior so we can be confident that we're testing the right thing?
