### ISSUE TITLE
[Bug]: Empty div with react datagrid

### ISSUE THREAD

**Issue by osnoser1** [microsoft/fluentui#26820]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22622
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 33.76 GB / 63.84 GB
  Browsers:
    Edge: Spartan (44.22621.450.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-datagrid--default

## Actual Behavior
Since 9.15 update and react table stabilization an empty div is rendering in html, you can see this in the official documentation: https://react.fluentui.dev/?path=/docs/components-datagrid--default

![image](https://user-images.githubusercontent.com/1179744/218372975-a0d18d35-4ed5-42e9-acb9-520d636daec8.png)

## Expected Behavior
That div shouldn't render it

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
This is a utility element used by table resizing feature (rendered always, no matter whether resizing is enabled or not). Not a bug.
