### ISSUE TITLE
[Bug]: When no focus element on the dialog, focus will jump to background element

### ISSUE THREAD

**Issue by Jingren-dev** [microsoft/fluentui#26829]
### Environment Information
**Library**
React Components / v9 (@fluentui/react-components)

- **Package version(s)**: latest, 9.17
- **Browser and OS versions**: Microsoft Edge Version 109.0.1518.61 (Official build) (64-bit)

#### Actual behavior:
Focus being send to the element behinds the trigger (even though in this example, it's just a brief flash). If the user hit enter at that time, it will trigger the action.

#### Expected behavior:
Focus should be trapped within modal leaving no focusable element on the current dom.

### If applicable, please provide a codepen repro: 
https://codesandbox.io/s/gbc5ps?file=/example.tsx

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix?    No

Requested priority:    High

Are you reporting Accessibility issue?   Yes

**Comment by bsunderhus** [comment]
> Focus being send to the element behinds the trigger (even though in this example, it's just a brief flash). If the user hit enter at that time, it will trigger the action.

I couldn't reproduce this in the given example @Jingren-dev. If by element behind the trigger you mean the dialog surface, it is expected behaviour in this case for modals without focusable elements, otherwise there would be no way to close the dialog on the `non-modal` scenario
