### ISSUE TITLE
Issue: Do we have any CDN links for all the images/svgs used in the Fluent UI.

### ISSUE THREAD

**Issue by iamb15** [microsoft/fluentui#26833]
### Describe the issue:

Do we have CDN links for all of the images used in the Fluent UI? 
We don't want to download and host the images statically since it may infringe copyright, therefore if we can use any already hosted images via CDN URLs, that would be helpful.

Requested priority: High

**Comment by iamb15** [comment]
A bit more context here:

We are trying to consume the fluent illustrations present on this link: https://www.figma.com/file/G72y8fk3oTWIDKxefi3HtQ/Fluent-Illustrations?node-id=19%3A2&t=GlgFWzbTJajmCilY-0 , and this link: https://www.figma.com/file/G72y8fk3oTWIDKxefi3HtQ/Fluent-Illustrations?node-id=443%3A18&t=Ulh6fOPkH1q4A9Ll-4.
Currently we are downloading and storing the images locally and using them, but its causing the react build to fail.

These are the fluent & react version details:
  "@fluentui/react": "7.147.1",
    "react": "16.14.0",
    "react-dom": "16.14.0",
    "react-jss": "^10.5.0",
    "typescript": "4.4.3",

Storing it statically might cause many issues in the future like copyright infringement, and also what if these images got changed in the future. 
So instead of statically storing the images locally, can you provide us the CDN links for these images in order to use them via CDN URLs.

**Comment by micahgodbolt** [comment]
It looks like these are old internal assets that were not really built for public use. Therefor there are not hosted on any CDN.

**Comment by iamb15** [comment]
We need this for Microsoft internal use only. Then the only way to use these images / svgs is to put them as static files locally, could you please confirm this?

**Comment by micahgodbolt** [comment]
moved internal
