### ISSUE TITLE
DetailsList: Colum resize is broken for justified columns since version 8.98.0

### ISSUE THREAD

**Issue by sysofwan** [microsoft/fluentui#26832]
### Environment Information

- **Package version(s)**: 8.98.0 and later
- **Browser and OS versions**: all versions

### Describe the issue:

When details list is larger than viewport (it has a horizontal scrollbar), in justified mode, columns cannot be resized.

This was previously working correctly. I think a regression was introduced in [this PR](https://github.com/microsoft/fluentui/pull/24959).

#### Actual behavior:

![Animation](https://user-images.githubusercontent.com/1856058/218601294-8a85684f-8080-410d-8ad3-76e02c067013.gif)

#### Expected behavior:

![Animation](https://user-images.githubusercontent.com/1856058/218601491-1c7468df-5d77-4ae2-aebc-c6c38875aad6.gif)

### If applicable, please provide a codepen repro:

To reproduce, decrease screen width until the list scrolls horizontally.

[Version 8.98.0 (actual)](https://codepen.io/sysofwan/pen/BaOBXPK)
[Version 8.97.2 (expected)](https://codepen.io/sysofwan/pen/XWPrvEE)

### Priorities and help requested (not applicable if asking question):

Requested priority: (Blocking, High, Normal, Low)

High, impacting multiple customers.

Products/sites affected: (if applicable)

Microsoft Defender, Microsoft Purview

**Comment by sysofwan** [comment]
We had a similar regression about 2 years ago #15971

**Comment by alice-ep** [comment]
Hi, are there any updates about this bug?

**Comment by spmonahan** [comment]
@alice-ep This is available in `@fluentui/react@8.110.3`

**Comment by sysofwan** [comment]
Thank you @spmonahan!
