### ISSUE TITLE
[Bug]: MicrosoftLogo.png is not visible at https://www.aka.ms/themedesigner

### ISSUE THREAD

**Issue by rafalfitt** [microsoft/fluentui#26858]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
GET https://themingdesigner.blob.core.windows.net/$web/MicrosoftLogo.png

HTTP/1.1 409 Public access is not permitted on this storage account.
Content-Length: 248
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: a460b7eb-b01e-009d-0c45-41bfb4000000
x-ms-version: 2009-09-19
Date: Wed, 15 Feb 2023 13:57:06 GMT
```

### Are you reporting Accessibility issue?

None

### Reproduction

go to https://fluentuipr.z22.web.core.windows.net/heads/master/theming-designer/index.html

## Actual Behavior
The Microsoft Logo is not visible on https://fluentuipr.z22.web.core.windows.net/heads/master/theming-designer/index.html because the request fails and error 409 is returned "Public access is not permitted on this storage account."

## Expected Behavior
fill this out

### Requested priority

Normal

### Products/sites affected

https://fluentuipr.z22.web.core.windows.net/heads/master/theming-designer/index.html

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Yeah, seems this asset url is no longer any good.

https://themingdesigner.blob.core.windows.net/$web/MicrosoftLogo.png

**Comment by rafalfitt** [comment]
(knock knock)

**Comment by khmakoto** [comment]
Reopening
