### ISSUE TITLE
[Bug]: Complex CSS selector doesn't work in Fluent UI 8

### ISSUE THREAD

**Issue by kroudams** [microsoft/fluentui#26857]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
none
```

### Are you reporting Accessibility issue?

None

### Reproduction

[class^="body-"]:has( > *:not(:empty)) doesn't work

## Actual Behavior
Using a complex selector with `has()` and nested `not()` doesn't work. 
```css
[class^="body-"]:has( > *:not(:empty)): {
    background: "red"
}
```
CSS rule is not applied

## Expected Behavior
CSS rule should work

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
I was able to get it to work. The issue with that selector is that it won't match an element with multiple classes.

https://codepen.io/micahgodbolt/pen/oNPgWKj?editors=0011

but this works

``` 
[class*="body-button"]:has( > *:not(:empty))
```

**Comment by kroudams** [comment]
It works in plain CSS

![image](https://user-images.githubusercontent.com/87769044/219281422-4e0cb092-9fa4-4311-af3f-d9cb8dfdedaf.png)

**Comment by kroudams** [comment]
@micahgodbolt,
Moreover, your selector is not the same as the one that I've used.

```css
// Issue selector
[class^="body-"]:has( > *:not(:empty))

// different selector
[class*="body-button"]:has( > *:not(:empty))

```

There is a big difference between those two. The selector will and should match any element with any number of classes as long as its first class starts with `body-`, thus `^=`.

Here is an example with multiple classes

![image](https://user-images.githubusercontent.com/87769044/219282237-fa6086de-9a9d-4beb-a8fa-fd046e3c9e85.png)

**Comment by micahgodbolt** [comment]
ok, one important point is that mergeStyles creates a className to use (see my example), and whatever styles you include will be scoped to that className

.foo [class^="body-"] etc

To make a style global (i.e. break out of its context and just be whatever selector you write), use the :global() keyword

```
const styles = mergeStyles({
    ':global([class^="body-"]:has( > *:not(:empty)))': {
      backgroundColor: "green"
    }
```

Now that style won't be appended by a hashed class.

You'll still have a problem with that "beginning of string match" selector with any Fluent component, as we don't always put the user provided className first. The selector only matches if the entire string starts with your provided string

![image](https://user-images.githubusercontent.com/1434956/219416452-53c1c875-0271-4caf-88eb-c1f17e3997b9.png)

class="body-button"   matches, but class="msButton ..... body-button" does not.

**Comment by micahgodbolt** [comment]
https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/README.md#global-selectors
