### ISSUE TITLE
[Bug]: Input with type 'date' - default not working

### ISSUE THREAD

**Issue by NWessel** [microsoft/fluentui#26860]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
any
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/ndw-test-date-input-c8tlhn?file=/example.tsx

## Actual Behavior
comes with placeholder values

## Expected Behavior
Should set the date specified in the default value

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Date needs to be in this format: `<Input type="date" defaultValue="2018-07-22" />`


https://developer.mozilla.org/en-US/docs/web/html/element/input/date
> Note: The displayed date format will differ from the actual value — the displayed date is formatted based on the locale of the user's browser, but the parsed value is always formatted yyyy-mm-dd.
