### ISSUE TITLE
PresenceBadge: 'Unknown' color should be the same as the 'Offline' color, i.e. '#616161'.

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#26876]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
any
```

### Are you reporting Accessibility issue?

no

### Reproduction

v9 docs site

## Actual Behavior
<img width="237" alt="image" src="https://user-images.githubusercontent.com/13742664/219424374-d6e0f4a2-ba57-4703-a558-81861a03ac43.png">

## Expected Behavior
The color for [the 'Unknown' status in the Fluent UI v9 version](https://react.fluentui.dev/?path=/docs/components-badge-presencebadge--default#status) is '#d13438' (same as the 'Blocked', 'Busy', 'Busy OOF', 'Do Not Disturb' and 'Do Not Disturb OOF' colors). The 'Unknown' color should be the same as the 'Offline' color, i.e. '#616161'.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/13742664/219424574-00254b33-2e28-4d64-8049-b823e9dcb15b.png">

### Requested priority

High

### Products/sites affected

Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
The current color (red) matches what is in the design spec. I'm going to follow up with the designers to see if the design should be updated.

**Comment by behowell** [comment]
Confirmed that the design spec needs to be updated: we'll go ahead with this fix.
