### ISSUE TITLE
Component Tooltip - Missing maxWidth props in ITooltipHostProps

### ISSUE THREAD

**Issue by sirdawidd** [microsoft/fluentui#26886]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
not related
```

### Are you reporting Accessibility issue?

None

### Reproduction

React / v8 - https://aka.ms/fluentpen

## Actual Behavior
Component Tooltip   have interface ITooltipProps which is similar to ITooltipHostProps but have maxWidth parameter, where we can define width of tooltip window.

https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip

## Expected Behavior
ITooltipHostProps  should contain parameter maxWidth

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
you can use [tooltipProps](https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip#row703-15-header) `<TooltipHost tooltipProps={{maxWidth:'10px'}}`>....</TooltipHost>`
