### ISSUE TITLE
[Bug]: Dialog body bleeds outside of the dialog surface if height/maxHeight is changed

### ISSUE THREAD

**Issue by ryantrem** [microsoft/fluentui#26885]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.15 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 110.0.5481.100
    Edge: 109.0.1518.78
    Firefox: 97.0
    Safari: 16.3
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/dawn-monad-mqm8q9?file=/src/App.js

## Actual Behavior
By default dialogs grow in height to accommodate their content. If you don't want the dialog to grow to the full height of the viewport, then setting its maxHeight (to say `'80vh'`) seems natural. However, if you actually do this then the dialog body does not stay contained within the dialog surface:

![image](https://user-images.githubusercontent.com/5084643/219552702-babbd5f2-2d87-4f23-9e41-e2f8421ac0da.png)

If I change the DialogSurface `height` to `auto` and DialogBody `height` to `auto` and `maxHeight` to `100%`, then I seem to get the right default behavior, and can also change DialogSurface `maxHeight` to values like `80vh` and have things work as expected.

Note that all this also seems to apply to width/maxWidth.

## Expected Behavior
I should be able to set a Dialog's `maxHeight` (via `DialogSurface` I suppose, though setting a `className` directly on Dialog seems like it would be more intuitive) without breaking the visuals.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
not 100% sure if this is a bug, or just need clear guidance on how to properly resize dialogs

**Comment by bsunderhus** [comment]
Hey there @ryantrem ,  how about this? https://codesandbox.io/s/winter-wind-ukhx2h?file=/src/App.js ,does this solve your issue?
