### ISSUE TITLE
[Bug]: [ChoiceGroup]: Clicking on empty horizontal space of the radio buttons selects the corresponding option

### ISSUE THREAD

**Issue by valangar** [microsoft/fluentui#26898]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz
    Memory: 14.86 GB / 31.83 GB
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.46)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/valangar/pen/BaONbzZ

## Actual Behavior
Clicking on the horizontal white space to the right of the ChoiceGroup radio buttons selects the respective option. 

## Expected Behavior
Users should be able to click around the control without affecting the selection state of the control.

Please note: This issue was reported by a customer who was using our Azure Portal service. To fix the issue with our service, we have added a wrapper CSS on the control with a fit-content width. This issue only resolves the issue in our service and so the customer is concerned that the behavior could be broken in other instances of the Portal. 

Could you please add a default behavior for the control where its width is dependent on the content and not the whole parent width?

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
This is not the behavior of our checkboxes, so I don't see why it should be this way for choicegroup

**Comment by spmonahan** [comment]
I created a draft PR to consider this change but ultimately I think we should leave the existing behavior as-is.

Styles can be overridden at the theme level, allowing users to override styles for all instances of a control in a single place. Here's a Codepen example: https://codepen.io/seanms/pen/rNZjNZW?editors=0010

The styles for `ChoiceGroup` and `ChoiceGroupOption` were last touched two years ago so other users may be relying on the existing behavior. Further, the [ChoiceGroup with custom option rendering](https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup) example implies that the area inside the green border is interactive.

While this does feel like a bug it is also not clearly a bug and it is risky to make a change to the default behavior. While we could put the new behavior behind a prop flag (e.g., `constrainWidth={true}`) that would still need to be set on every instance of ChoiceGroup.

**Comment by spmonahan** [comment]
After discussing with the team and @valangar we've decided to not make the requested change.

While the current behavior is probably incorrect (in fact RadioGroup in v9 does not exhibit this behavior) it's been longstanding, and it present not just in Fluent v8 but also v7. As such it's likely that users rely on the current behavior so changing the default will lead to bugs for those users.
