### ISSUE TITLE
[Feature]: enable TS strict mode in wc3

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#26891]
### Library

Web Components (@fluentui/web-components)

### Describe the feature that you would like added

ATM web-components use very weak TS compiler checks .

This introduces various issues in terms of compatibility with other packages in monorepo and scaleability of the library.

**Current:**

```
"strictNullChecks": true,
```

**Expected:**

```
"strict": true,
```

### Have you discussed this feature with our team

@miroslavstastny 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by miroslavstastny** [comment]
Done in #26950.
