### ISSUE TITLE
[Bug]: GroupedListV2 collapse/expand all broken.

### ISSUE THREAD

**Issue by E-v-a-n-S** [microsoft/fluentui#26895]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/groupedv2

## Actual Behavior
Selecting chevron to collapse or expand all doesn't trigger groups to collapse/expand. It appears the internal collapsed state is updated, because the next render does reflect the updated collapsed state.
(repro in documentation)

## Expected Behavior
That collapse/expand all click will update groups immediately.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@E-v-a-n-S This fix is available in [8.107.3](https://github.com/microsoft/fluentui/blob/master/packages/react/CHANGELOG.md#81073)
