### ISSUE TITLE
[Accessibility]:  SwatchColorPicker add incorrect role="gridcell" on color cell if grid has multiple rows

### ISSUE THREAD

**Issue by jichang** [microsoft/fluentui#26907]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz
    Memory: 14.50 GB / 31.73 GB
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.22621.1

  FluentUI:
    8.105.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/Ji-Chang/pen/dyqYBJP

## Actual Behavior
When using SwatchColorPicker like below
<SwatchColorPicker />

There rendered color grid cell has role="gridcell", but since it's a button, it can not have "gridcell" as aria role

```HTML
<button role="gridcell" type="button" id="swatchColorPicker126-fb474c7f-568b-4570-a2e8-6fe9ba3e9172-0" data-index="0" data-is-focusable="true" aria-selected="false" title="Dark Green"  class="ms-Button ms-Button--action ms-Button--command colorCell-243" aria-label="Dark Green" tabindex="0"><span class="ms-Button-flexContainer flexContainer-73" data-automationid="splitbuttonprimary"><svg class="svg-242" role="img" aria-label="Dark Green" viewBox="0 0 20 20" fill="#0E700E" focusable="false"><rect width="100%" height="100%"></rect></svg></span></button>
```

## Expected Behavior
I assume the correct behaviour should has another container outside which has role="gridcell"

```
<div  role="gridcell">
    <button type="button" id="swatchColorPicker126-fb474c7f-568b-4570-a2e8-6fe9ba3e9172-0" data-index="0" data-is-focusable="true" aria-selected="false" title="Dark Green" class="ms-Button ms-Button--action ms-Button--command colorCell-243" aria-label="Dark Green" tabindex="0"><span class="ms-Button-flexContainer flexContainer-73" data-automationid="splitbuttonprimary"><svg class="svg-242" role="img" aria-label="Dark Green" viewBox="0 0 20 20" fill="#0E700E" focusable="false"><rect width="100%" height="100%"></rect></svg></span></button>
</div>
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by KeiraYang** [comment]
![image](https://user-images.githubusercontent.com/28148759/220567453-32426064-77a4-4985-a6b0-e1e8290b3b4a.png)
Use Accessibility insights tool find the issue. Can reproduce.

**Comment by dapengwang2464** [comment]
Container div's row is set to "row" for multiple line color picker, which caused another a11y issue: 
![image](https://user-images.githubusercontent.com/126704796/222213238-35f19e4b-d7ae-4fb8-95d2-2bbeba688094.png)

**Comment by Gullanshire** [comment]
@smhigley @jichang @smhigley Could we reopen this issue as the issue is still observed on the fluent UI official website?

<img width="929" alt="image" src="https://github.com/microsoft/fluentui/assets/6789898/90b7db67-2d2e-4515-a147-a5cae56d5651">
