### ISSUE TITLE
Storybook build needs addons to be built first

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#26925]
`build-storybook` will not work unless all addon code has been built. To repro simply delete the `lib` folder in `react-storybook-addon` and run any of the commands:

* yarn workspace @fluentui/public-docsite-v9 build
* yarn workspace @fluentui/vr-test-react-components build
* yarn workspace @fluentui/recipes-react-components build

![image](https://user-images.githubusercontent.com/20744592/220323520-37ce4f60-e5f9-41bf-979b-a2a8187b38b3.png)

**Comment by Hotell** [comment]
Hey so this works as expected/by design. 
See https://github.com/microsoft/fluentui/blob/master/scripts/storybook/src/utils.spec.js#L88-L100

our react-storybook-addon is already defined as dependency for apps for this particular reason.

**Comment by Hotell** [comment]
We will have now true no-build needed environment also for workspace addons on production builds. https://github.com/microsoft/fluentui/pull/27006

We probably still should declare our workspace addons to package.json apps dependencies to keep dependency tree up to date.
