### ISSUE TITLE
[Bug]: createV9Theme isn't exported

### ISSUE THREAD

**Issue by djyde** [microsoft/fluentui#26948]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 8.96 GB / 15.62 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/jitq50?file=/example.tsx

### Bug Description

Acoording to sample code in the doc https://react.fluentui.dev/?path=/docs/migration-shims-v8-theme-createv9theme--playground . There is a `createV9Theme` method can be imported from `@fluent/react-components`, but it doesn't be exported from `react-components`.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by djyde** [comment]
I knew it's exported from `react-migration-v8-v9`, should I use this package instead of `react-components`?

**Comment by Hotell** [comment]
> I knew it's exported from `react-migration-v8-v9`, should I use this package instead of `react-components`?

that's correct. Migration shims are not part of react-components API surface to properly separate domains.

Regarding the docs feel free to send PR that fixes the documentation if you can 🙏.

**Comment by Hotell** [comment]
hmm looks like a bug with our storybook addon that parses the code for the examples.

**Comment by Hotell** [comment]
https://github.com/microsoft/fluentui/issues/26961
