### ISSUE TITLE
[Bug]: Command bar render issue when some items have dynamic content

### ISSUE THREAD

**Issue by rayhong118** [microsoft/fluentui#26947]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz
    Memory: 37.59 GB / 63.59 GB
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.49)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/react-ts-mafjkj?file=App.tsx

## Actual Behavior
when the item in command bar change size due to its content has changed, command bar will still use the old width value when deciding whether to move things into overflow item list. This is causing primary section of command bar using more space than it should do and pushing far items our of view. 

![20230222-1](https://user-images.githubusercontent.com/17467424/220789930-11bbc860-6ffb-404f-ac00-98b3b4b2a123.gif)

when we set min-width for primary section of command bar to 0, now primary and far section overlaps.
![image](https://user-images.githubusercontent.com/17467424/220791020-7d7e19d9-1c54-424f-b5bd-58775ce0b237.png)

## Expected Behavior
command bar should adapt to updated width of items. all far items should remain within view, and no overlapping should occur. 

### Requested priority

Blocking

### Products/sites affected

PowerApps

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
There is no component owner. This issue will go to the grooming session for next triage.

**Comment by micahgodbolt** [comment]
when a component changes size dynamically, the command bar caching won't know that it should allow it more space. Change the item's cacheKey to a new value anytime that an item changes width. This will force the command bar to recalculate.
