### ISSUE TITLE
[Bug]: Select component dropdown list looks very different in firefox & chrome.

### ISSUE THREAD

**Issue by thelastfantasy** [microsoft/fluentui#26963]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-1280P
    Memory: 6.69 GB / 31.71 GB
Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.50)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

sdf

## Actual Behavior
Select dropdown looks very different in firefox & chrome.
I think fluent ui uses the default styles of  option element caused this problem.

## Expected Behavior
Should do some custom to keep the dropdown looks the same in different browsers.

### Logs

```shell
No
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
Hey, can you please provide repro instead of `sdf` ? ty
