### ISSUE TITLE
Documentation for v9 SplitButton doesn't have examples on how to bind onClick event to primary button

### ISSUE THREAD

**Issue by nanabear0** [microsoft/fluentui#26976]
### Describe the issue:

I am trying to use SplitButton but the documentation doesn't explain how to bind an onClick event to the split button. If I use onClick of SplitButton, it gets triggered even when I press the menu button. The documentation could use examples regarding how to bind an onClick event.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low)
Normal
Products/sites affected: (if applicable)

**Comment by Hotell** [comment]
Hey! not sure such a documentation is needed. To give you more context, the docs are within types, if we would like to be consistent we would need to document via example every prop customization which would be quite difficult to manage.

you can use standard JS/React patterns like following:

```jsx
<Menu positioning="below-end">
    <MenuTrigger disableButtonEnhancement>
      {(triggerProps: MenuButtonProps) => (
        // 💡spread + override by supported property and custom behaviour
        <SplitButton menuButton={{...triggerProps, onClick:()=>{
          console.log('click me');
        }}}>Example</SplitButton>
      )}
    </MenuTrigger>

    <MenuPopover>
      <MenuList>
        <MenuItem>Item a</MenuItem>
        <MenuItem>Item b</MenuItem>
      </MenuList>
    </MenuPopover>
  </Menu>
```

**Comment by spmonahan** [comment]
Created a follow up here: #27105
