### ISSUE TITLE
[Feature]: Components to support large font sizes

### ISSUE THREAD

**Issue by swese44** [microsoft/fluentui#26996]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

There are some FUI8 components which set a pixel height value on text containers, like menu items. This introduces a11y issues when we allow the user to set a larger font size and the text overflows:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/471731/221655222-e8e0ca1a-7a4e-4db0-9e5c-f3b9d6284777.png)

We are adding style overrides to fix these in our usage of the FUI8 components. However when we move forward with FUI9 we would prefer to reduce the amount of style overrides and customization. Can FUI9 components support larger font sizes? Is there a strategy for FUI9 components to follow, like setting vertical paddings on text containers without setting a `height` style?

Thanks!

### Have you discussed this feature with our team

micahgodbolt

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by micahgodbolt** [comment]
Example

![image](https://user-images.githubusercontent.com/1434956/222206736-941a8d29-0e42-4ce0-b06d-9a3d371f9dde.png)

**Comment by JustSlone** [comment]
@micahgodbolt can you share more context for your example above?

**Comment by swese44** [comment]
@JustSlone Micah's example shows that the MenuItem div has a height of 32px. When consumers provide a theme with larger font-sizes, or a theme with rem-based font-sizes and the browser has a default font-size of large, the container will remain 32px tall and larger text will get clipped or overflow.

We'd like to see FUI9 components adhere to a sizing strategy which allows text-containing elements to grow (or shrink) with the text size. For example, the MenuItem div Micah shared could remove its `height` style and add `padding-top` and `padding-bottom` values. Then the text could grow with the theme font size or rem size and this container element will grow with it.

**Comment by tudorpopams** [comment]
This is a great starting point into offering more mobile support. We discussed this internally and we plan to offer a theme like solution which would enable partners to opt-in for this kind of feature, but we don't have all the technical details yet, as this needs to be thoroughly planned out and that can't happen over night. 

We plan on having updates on this in the upcoming months.

**Comment by tudorpopams** [comment]
Based on internal priorities, we decided to postpone this feature for now. I will update this issue as soon as we have any news on it.
