### ISSUE TITLE
[Bug]: Unable to add Unit tests for Dropdown component

### ISSUE THREAD

**Issue by Naina-G** [microsoft/fluentui#27016]
### Library

React Northstar / v0(@fluentui/react-northstar)

### System Info

```shell
Version - "@fluentui/react-northstar": "0.62.0",  
 System Details:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 138.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 110.0.5481.177
    Edge: 110.0.1587.57
    Firefox: 108.0.2
    Safari: 16.3
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/clever-cloud-x30tjf?file=/test.js

## Actual Behavior
Should be able to add unit tests for Dropdown component in FluentUI using RTL and Jest.

## Expected Behavior
We have used Dropdown component of `@fluentui/react-northstar`  in our Application to show the suggestions based on the text entered by the user.
Now when I am trying to add unit tests for this component using RTL and Jest. I am unable to do so because internally FormDropdown is comprised of text-box where we enter the text followed by listbox where we would show the matching options.
So when we try to capture this textbox which is inside this FormDropdown component and try to trigger change event to add a text in it, we get the below error.

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'activeElement')

      117 |         const selectBox = screen.getByTestId("select-box");
      118 |         const  selectBoxInput = within(selectBox).getByRole("textbox");
    > 119 |         fireEvent.change(selectBoxInput, {target : {value : "A"}});
          |
```

### Requested priority

Normal

### Products/sites affected

N/A

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
Hey, can you please provide an actual repro ? the link you provided is only dummy northstar template . thanks!

**Comment by Naina-G** [comment]
@Hotell 
Thanks for your response.
I have added reproduction of the issue we are facing at this link now - 
https://codesandbox.io/s/clever-cloud-x30tjf?file=/test.js
Details :
I have added a new component called Test component where I have used  searchable Dropdown to fetch results based on the input text.
Here the functionality works fine but adding unit test for this component is where we are facing the issues mentioned in the Bug. Our actual unit tests and workaround we tried are in the test.test.js file in the shared sandbox link.
I have added the versions of testing library being used by us and the test results are seen in the "Tests" Window
Please let me know in case of any futher questions

**Comment by Naina-G** [comment]
Hi Team,
Could you have a look at the shared details and sandbox link

Thanks

**Comment by shabbir-dhangot** [comment]
Hi @jurokapsiar,

Any update on the issue. Facing similar issue and need immediate attention as its blocker for us to increase unit test case coverage. 

Regards,
Shabbir

**Comment by xnivaxhzne** [comment]
Facing similar issue.

**Comment by shabbir-dhangot** [comment]
@miroslavstastny and @jurokapsiar anyone of you looking into this issue?

**Comment by layershifter** [comment]
`Dropdown` and some other components rely on having `Provider` as it provides a proper context values including a `document`.

Basically, it means that you should `Provider` as a wrapper:

```diff
+import { Provider } from "@fluentui/react-northstar";

describe("Tests for Test Component", () => {
  beforeEach(() => {
-   render(<Test />);
+   render(<Test />, { wrapper: Provider });
  });
```

https://codesandbox.io/s/dawn-rain-cz6s9y?file=/test.test.js
