### ISSUE TITLE
DatePicker Decade Component - Missing / Possibly Expected

### ISSUE THREAD

**Issue by sitepodmatt** [microsoft/fluentui#2705]
The DatePicker invoked by Fabric UI react does not seem to have the Decade component (pretty essential for DOB unless granpa simpson is going to click 99 times), is this an oversight, a bug, or a feature enhancement? I am confused about what is the current expectation of this pakage, there seems to be little docs at how to consider this, the roadmap 404s for example too https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/ROADMAP.md

**Comment by sitepodmatt** [comment]
This issue still remains.

**Comment by sitepodmatt** [comment]
This issue still remains

**Comment by micahgodbolt** [comment]
@lorejoh12 - this question has come up a few times. Is the best practice for picking a date far in the past (like birthdate) to use datepicker? or should they simply use a set of dropdowns/comboboxes.
