### ISSUE TITLE
Slot children render function won't override existing children.

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#27089]
Repro: https://codesandbox.io/s/elated-babbage-46ez1w?file=/example.tsx

It's not possible use children render function to override an entire slot, if `children` are already used. The above is a minimal repro of an issue that can be seen in Fluent in the `AccordionHeader` component. The component renders the `button` slot which contains its own children. JSX children will win over props children - which is how children render functions are rendered by `getSlots`

https://github.com/microsoft/fluentui/blob/220b321042b4bcc126c86a91811a34b04934d49b/packages/react-components/react-accordion/src/components/AccordionHeader/renderAccordionHeader.tsx#L13-L25

Requirements for children render function:

* should be able to override the entire slot
* When rendering the original children, should respect nested slots.

**Comment by bsunderhus** [comment]
I'll be opening a PR per package here to ensure proper migration to newest custom JSX pragma that will ensure support for this feature:

- https://github.com/microsoft/fluentui/pull/27475

**Comment by ling1726** [comment]
@bsunderhus can this issue be closed now that you're merged all the jsx pragma PRs?
