### ISSUE TITLE
[Bug]: Not able to get the horizontal scroll when the screen resolution is increased to 200%

### ISSUE THREAD

**Issue by FunnyThota** [microsoft/fluentui#27120]
### Library

React v8 (@fluentui/react)

### System Info

```shell
https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/keyboardcolumnreorderresize
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/keyboardcolumnreorderresize

## Actual Behavior
We I increase the screen resolution to 200%, then the grid columns are going out of the screen and no horizontal scroll is enabled. But when I used this in my project I see the horizontal scroll but column resize stops working. When there is no horizontal scroll column resize works fine.

## Expected Behavior
We I increase the screen resolution to 200%, then the grid columns should be visible and horizontal scroll should be enabled. Also, column resize should work even if we get horizontal scroll.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@FunnyThota This behavior expected since the default behavior of `DetailsList` is to drop columns that don't fit the view. If you would like to attain horizontal scroll, you can pass the `layoutMode={0}` prop to the `DetailsList`. See modified codepen example: https://codepen.io/tristanwatanabe/pen/yLGVVRB
