### ISSUE TITLE
[Bug]: Fluent Panel overlay is inconsistent with other transient UI

### ISSUE THREAD

**Issue by isabelacmor** [microsoft/fluentui#27130]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 62.13 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
Browsers:
    Safari: 16.3
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/isabelacmor/pen/vYzWBrr

## Actual Behavior
The Panel's overlay is white translucent.

## Expected Behavior
The Panel's overlay should ideally be black translucent to match with other transient UI, such as Modal and Dialog.

### Requested priority

Normal

### Products/sites affected

All products using Panel

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @isabelacmor, you can change the overlay to be dark by using `overlayProps={{ isDarkThemed: true }}`. Here's an example codepen: https://codepen.io/behowell/pen/qBMLJmZ?editors=0010

I don't think we'd want to change the default behavior, as that would affect all users of Panel.
