### ISSUE TITLE
[Bug]: docs for Menu radio items and checkbox items don't render html correctly

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#27151]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-menu-menu--default#radio-items

## Actual Behavior

Docs render `[object Object]`

<img width="649" alt="object_Object" src="https://user-images.githubusercontent.com/93940821/224177267-df939416-a4d4-457a-b7c6-ae33c3a52c11.png">

## Expected Behavior

Docs should render 

```html
<input type="checkbox" name="name" value="value" />
```

### Requested priority

Low

### Products/sites affected

react.fluentui.dev

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
Closing since this can't be reproed anymore

![Uploading image.png…]()
