### ISSUE TITLE
[Bug]: DatePicker broken cass

### ISSUE THREAD

**Issue by janeecko** [microsoft/fluentui#27162]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
NA
```

### Are you reporting Accessibility issue?

None

### Reproduction

issue happens only if app is deployed to app catalog

### Bug Description

when implementing default setup for Datepicker CSS is broken, see picture
![DatePIcker broken css](https://user-images.githubusercontent.com/31740215/224306825-7327d798-970b-4950-ad8d-be6693cb13d6.PNG)

this is happening only if application is deployed to app catalog. 
if I run application locally with gulp serve, date picker looks correct, as in sample on Fluent UI site. 

### Requested priority

Blocking

### Products/sites affected

SPFx

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by janeecko** [comment]
I was able to fix this issue by adding 
 styles={{ callout: { '& .ms-DatePicker-day-button ': { minWidth: 0, marginLeft:0 } } }}
to the DatePicker component. 
When I deploy app it was by default adding minWidth : 6em which breaks whole callout

**Comment by behowell** [comment]
Hi @janeecko, is this still an issue? If so, could you please add a link to a codepen that reproduces this issue? If the issue is resulting from additional css styles your app is adding to the date picker, then that's not something we can fix on our end; the styles added by the app would need to be fixed.
