### ISSUE TITLE
[Bug]: Details List header resizing does not work when React.StrictMode is applied

### ISSUE THREAD

**Issue by jdthorpe** [microsoft/fluentui#27166]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.39 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.3
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/jdthorpe/fluent-ui-detailslist-header-strictmode-bug

## Actual Behavior
When React.StrictMode is applied, Columns in a DetailsList table are not resizable.  In particular, this is true for projects that are created with `create-react-app`

## Expected Behavior
Columns should be resizable regardless of React.StrictMode

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Blocked by #27851
