### ISSUE TITLE
[Bug]: Chrome with 24hr format shows 24:00 24:30 in the dropdown

### ISSUE THREAD

**Issue by arnavKarforma** [microsoft/fluentui#27183]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 19.43 GB / 63.71 GB
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.46)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/timepicker

## Actual Behavior
Chrome shows something like this
![image](https://user-images.githubusercontent.com/44005442/224789086-995ad0e5-55e6-40e4-8f9c-b6b180c214f2.png)
but in Edge it is alright
![image](https://user-images.githubusercontent.com/44005442/224785661-02a595e4-b161-4188-af1f-ed521e27d21e.png)

## Expected Behavior
fill this out

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@arnavKarforma I'm unable to repro this on Chrome, can you confirm if this is still an issue on your end?

<img width="778" alt="image" src="https://github.com/microsoft/fluentui/assets/8649804/74fb1f23-8ebd-4689-ab03-175ee7c1c40f">
