### ISSUE TITLE
[Feature]: There is no way to add custom validation/error message to TimePicker

### ISSUE THREAD

**Issue by arnavKarforma** [microsoft/fluentui#27184]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

If a user gives the format string for time picker than current code will look at the onValidateUserInput message that too when the user input is entered as a free text.

And the errormessage props passed to Combo Box is derived based on this mechanism. But what if user wants to add any custom validation on time select from the dropdown it cannot be done now, or if the user simply wants to pass an ErrorMessage based on business specific validation   

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by khoait** [comment]
This is needed as the OOTB error message is not very user-friendly.
