### ISSUE TITLE
[Bug]: Jest performance suffers from @fluentui/react-components barrel file exports

### ISSUE THREAD

**Issue by swese44** [microsoft/fluentui#27205]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
This is my local system info, but we're primarily seeing this issue in CI.

  System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 25.23 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 81.0
    Safari: 16.3

Jest v26.6.3
```

### Are you reporting Accessibility issue?

no

### Reproduction

export { makeStyles, mergeClasses, shorthands } from '@fluentui/react-components';

### Bug Description

We are just starting to adopt FUI9. Our first PR converted one component's styles to FUI9/Griffel `makeStyles` and introduced an export for our consumers:
```ts
export { makeStyles, mergeClasses, shorthands } from '@fluentui/react-components';
```
After this PR merged we saw our Jest unit times slow down significantly. I've discovered that barrel files are a known issue with Jest, Jest doesn't know which exports it needs and so it imports everything. And this cost must be paid for every test file. Since FUI9 us barreling everything from the root I suspect our unit tests will continue to slow down as our apps pull in more and more dependencies behind `@fluentui/react-components`.

Jest issue:
https://github.com/facebook/jest/issues/11234

Dev blog post:
https://blog.bitsrc.io/why-is-my-jest-suite-so-slow-2a4859bb9ac0#14e6

By updating our styling utils to export directly from Griffel we can significantly cut down our unit test times:
```ts
export { makeStyles, mergeClasses, shorthands } from '@griffel/react';
```
but this won't scale as we continue to adopt more FUI9 components.

Exporting these from `@fluentui/react-components` takes our library test suite 52 minutes to complete, even though there's only a single file importing and using them. Changing those exports to `@griffel/react` cuts library unit test time by 33%, down to 35 mins.

As a side note, our project uses lint rules to allow/disallow import paths. For FluentUI specifically, this allowed us to restrict component files to import from `@fluentui/components/*`, styling utils to import from `@fluentui/styling`, etc. So it's a little bit of a bummer that we've lost the ability to help engineers only import desired things from specific files.

## Actual Behavior
Unit tests for our project are very slow

## Expected Behavior
Unit tests are not slow

### Requested priority

High

### Products/sites affected

Yammer / Viva Engage

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
Hey, thanks for report! couple of questions:

- can you migrate to jest 29 and provide results ? (you should be using jest 29 pass MSFT CDA btw)
- can you share your detailed jest config and everything related to that config ( if you use ts-jest , what's the tsconfig for that , if you use babel etc...) ?
- can you switch to esbuild or swc and provide results for tests ?

_Regarding barrel files:_

Our situation is not 1:1 like described in that article. We actually enforce to not use `export *` as that's one of biggest issues for bundlers (also completely removes what is being actually exported).

> So it's a little bit of a bummer that we've lost the ability to help engineers only import desired things from specific files.

that's by design, nested imports provide unreliable/hard to manage public API. In future (when we fully adopt native ESM that might be a thing powered by exports maps)


ty!

**Comment by benkeen** [comment]
Hi @Hotell, thanks for the response! We'll try the jest 29 upgrade but it may take a little time. It's a big system and we attempted to update to 27 a while back but ran into a number of tricky problems so it was temporarily shelved. But we'll try to patch it to work with 29 just for examination purposes & get back to you.

**Comment by swese44** [comment]
Bump to prevent closure until we can spike the Jest upgrade
