### ISSUE TITLE
[Bug]: Field overwrites id of wrapped control

### ISSUE THREAD

**Issue by adamsamec** [microsoft/fluentui#27202]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

Yet to be provided

## Actual Behavior

When a v9 Field component is used to wrap an inner native HTML control or v9 control like Input or Checkbox, and an "id" attribute is set on that inner control, the "id" gets overwritten with a generated "id".
## Expected Behavior

The "id" attribute of the inner control should be preserved when wrapped by the Field component.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
It turns out this was related to using a react-hook-form Controller inside the Field. While it's possible to make this work, Field's API could be improved to work better with form validation libraries.

Repro: https://codesandbox.io/s/happy-butterfly-c7pcmr?file=/example.tsx
