### ISSUE TITLE
Virtualizer should support scrolling detection for items

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#27218]
Items should be able to know that scrolling is happening so that they can optionally render a more 'lightweight' variant to increase scrolling performance and decrease whitespace.

A similar feature exists in [react-window](https://[react-window](https://react-window.vercel.app/#/api/FixedSizeList).vercel.app/#/api/FixedSizeList)

**Comment by brandonthomas** [comment]
@Mitch-At-Work since there's Suspense support is this handled?

**Comment by Mitch-At-Work** [comment]
Can close thanks to https://github.com/microsoft/fluentui/pull/27864 - user can set a flagged index in any virtualizer and request access to the virtualizer index/length to detect current range, as well as be notified when the scrollview reaches it's scrolledTo call via callback.
