### ISSUE TITLE
[CheckBox]: Unable to set/change the checkbox color from default color blue

### ISSUE THREAD

**Issue by vidyasiva** [microsoft/fluentui#27212]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### Describe the feature that you would like added

In the checkbox currently the color for the checked state is Blue, i would like to apply different colors for all the available check boxes. 
Currently this is achieved via backgroundImage url, instead of this tick mark can be a url however color should be changed by user.

### Have you discussed this feature with our team

Juraj

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jurokapsiar** [comment]
adding v9 tag - we are not adding new features to v0 components that have v9 alternatives available.

**Comment by tudorpopams** [comment]
We discussed this issue during our backlog grooming process and decided that we should enable easy switching of the default checkbox color. There are apps / partners that require this feature, like the Outlook calendar which uses different checkboxes for multiple calendars.
