### ISSUE TITLE
[Feature]: expose blur() for ISearchBox's ref.

### ISSUE THREAD

**Issue by JuAn-Kang** [microsoft/fluentui#27238]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Hello, 
We at Viva Engage are using this SearchBox to support an autocomplete-enabled search input, and need a clean way to blur the focus out of the input upon clicking an autocompleted item. Just found out that while focus() and hasFocus() are exposed, we do not have a way to use blur().

Can we have that opened in the ref implementation? 

Thank you. 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by behowell** [comment]
It seems reasonable to add `blur()` to ISearchBox component ref. It looks like we have a blur function on the similar ITextField component ref.
