### ISSUE TITLE
[Bug]: Spacebar: Closes the popup and returns focus to the Combobox and clears the contents of the Combobox.

### ISSUE THREAD

**Issue by inteclix** [microsoft/fluentui#27255]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz    
    Memory: 1.39 GB / 7.89 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.44)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/romantic-frost-wg1zew?file=/src/App.tsx

## Actual Behavior
fill this out

## Expected Behavior
fill this out

### Logs

```shell
Spacebar it work like Escape: Closes the popup and returns focus to the Combobox and clears the contents of the Combobox.
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ParadimeWeb** [comment]
I reported this also. Apparently, it's by design... Even when you have freeform set to true, it won't allow you to type something with a space in it. Weird...

**Comment by ParadimeWeb** [comment]
https://github.com/microsoft/fluentui/issues/26361

**Comment by behowell** [comment]
@smhigley could you investigate whether this behavior is by design?
