### ISSUE TITLE
[Bug]: Dropdown items panel overlay issue when used in Dialog component

### ISSUE THREAD

**Issue by makmilind** [microsoft/fluentui#27264]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 12.18 GB / 31.73 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.44)   
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/serverless-field-rjix4g

## Actual Behavior

- The panel opens inside the dialog container and overflows within the dialog.
- To see dropdown items, the user has to scroll down in the dialog.

#### Package Versions:

- @fluentui/react-northstar: 0.66.4
- react: 17.0.2
- react-dom: 17.0.2
- react-scripts: 5.0.1

#### Repro:
- CodeSandbox: https://codesandbox.io/s/serverless-field-rjix4g

## Expected Behavior

- The dropdown items panel should be displayed on top and outside of the dialog.

#### Package Versions:

- @fluentui/react-northstar: 0.54.0
- react: 17.0.2
- react-dom: 17.0.2
- react-scripts: 5.0.1

#### Repro:
- CodeSandbox: https://codesandbox.io/s/black-field-grgq50

Please let me know if there is a quick solution to this, which I can fix it by myself in the code directly or it would be great and really help if someone can put out a fix for this.

Thank you!

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ozluy** [comment]
![Screenshot 2023-03-20 at 22 22 17](https://user-images.githubusercontent.com/2522722/226469310-65dcef02-5ef9-4a66-a01b-66318e004fcd.png)
Seems like these two overflow styles are causing it... Its also possible that using absolute position in fixed position modal might cause it.

**Comment by makmilind** [comment]
You are right, I just found that out earlier. I guess I can override the overflow property of the Dialog. That resolve the issue for me! Assuming, it is not going to have any adverse effects. Thank you for the help!
