### ISSUE TITLE
[Bug]:  The Label of Textfield does not change according to the provided style 

### ISSUE THREAD

**Issue by groh-f** [microsoft/fluentui#27261]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 1.57 GB / 15.92 GB
  Browsers:
    Chrome: 110.0.5481.178
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.44), ChromiumDev (112.0.1722.11)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/groh-f/pen/vYzzdNr

## Actual Behavior
Color and background color of the label which describes the Textfield does not change

## Expected Behavior
Color and background color of the label which describes the Textfield should change to the color defined in the style

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ozluy** [comment]
I guess you forgot the pass `root` into `label`  try as below or see here => https://codepen.io/ozluy/pen/BaOOMZe

```jsx
 <TextField
          label="Standard"
          styles={{
            field: {
              backgroundColor: "Red"
            },
            subComponentStyles: {
              label: {
                root: {
                  color: "Blue",
                  backgroundColor: "Red"
                }
              }
            }
          }}
        />
```

**Comment by groh-f** [comment]
Thanks for letting me know!
