### ISSUE TITLE
[Bug]: Coachmark is not positioning correctly when using "right/left center"

### ISSUE THREAD

**Issue by kehindeoni** [microsoft/fluentui#27280]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 65.38 GB / 127.71 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.49), ChromiumDev (105.0.1336.2)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/kehindeoni/pen/dyqgdjK

### Bug Description

How to reproduce
- Set coachmark position to "right center"
- Hover on the coachmark

## Actual Behavior
The coachmark beak does not align with its target when expanded

![image](https://user-images.githubusercontent.com/69808477/226739535-8d21172e-85b7-44f9-873a-db58543d0bfe.png)

## Expected Behavior
The coachmark beak aligns with its target when expanded
![image](https://user-images.githubusercontent.com/69808477/226740320-d96a6f01-2c1a-418e-b5b0-c08f0916c3fb.png)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Looks like this [PR](https://github.com/microsoft/fluentui/pull/26725/files) caused the regression in 8.105.6
