### ISSUE TITLE
[Bug]: Focus outline is clipped inside `DialogBody`

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#27294]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/dialog-focus-outlines-clipped-3yjogb

## Actual Behavior

Focus outlines are clipped for controls like `RadioGroup`/`Radio` when inside a `DialogBody`

https://user-images.githubusercontent.com/93940821/227028660-67ea2242-c086-453a-8fae-505c0e6d97ad.mp4

## Expected Behavior

Focus outlines should not be clipped.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
Looks like a duplicate from https://github.com/microsoft/fluentui/issues/25843 @spmonahan
