### ISSUE TITLE
[Bug]: Detail List Multi Select get latest selected/unselected item not working

### ISSUE THREAD

**Issue by mohamed-isak** [microsoft/fluentui#27301]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
npm i @fluentui
```

### Are you reporting Accessibility issue?

no

### Reproduction

ok

## Actual Behavior
Detail List Multi Select get latest selected/unselected item not working properly
If I use below code am facing this issue
```
this._selection = new Selection({
      onSelectionChanged: () => {
        // Multi Select get latest selected item 
        // And Find how to get selected/unselected status for particular item
        console.log(this._selection.getSelection()); // getSelection gives only array of         items[] not latest item selected 
      },
    });
```
If I use onActiveItemChanged default detail list behavior able to get latest item but once scenario its bug
like first item selected (items is printed) if unselected the same first item unable to get unselected item. 
 

## Expected Behavior

- Detail List Multi Select get latest selected/unselected item
- Detail list multi select get selected/unselected status (Boolean) if selected = give true unselected=false

Below is my Code Pen
[https://codepen.io/mohamed_isak_077/pen/dyqQmgL?editors=1112](url)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @mohamed-isak, it looks like DetailsList does not have a feature to indicate which particular items were selected/deselected in a selection change event. If you need that information, you could store an array of the previous selected items, and check for differences with the new array when onSelectionChanged is called. Hopefully that will work for your scenario.

**Comment by mohamed-isak** [comment]
Thanks

**Comment by mohamed-isak** [comment]
Thanks
