### ISSUE TITLE
[Bug]: Detail List Row click multiple selection mode needed like check box click multi selection

### ISSUE THREAD

**Issue by mohamed-isak** [microsoft/fluentui#27305]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
npm i
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist
Turn on "Enable modal selection"

### Bug Description

Currently, when clicking the row (and not the checkbox) in multiselect mode` (selectionMode = SelectionMode.multiple)`, the current selection is reset.

This means that clicking the row has the single selection mode behavior `(selectionMode = SelectionMode.single).` Clicking checkboxes directly has the multiselect behavior though.

We'd like to allow the user easier row selection, so we'd want clicking the row to behave exactly like clicking the checkbox (toggling selection of current row, without changing selection of other rows).

Attaching screen video 

![159920792-53342186-16f0-4c6c-8fd8-44b86ac81a06](https://user-images.githubusercontent.com/61628358/227203204-df10890f-4bc4-4eb5-8b8a-3060831123af.gif)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by nkartchner** [comment]
@mohamed-isak have you tried adding the property `isSelectedOnFocus={false}` to the DetailsList?
```
<DetailsList 
  ...
  isSelectedOnFocus={false}
/>
```
