### ISSUE TITLE
[Bug]: commonjs source-maps `sources` point to `.js` and cjs files contain duplicated `sourceMappingURL`

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#27320]
### Library

React Components / v9 (@fluentui/react-components)

### Are you reporting Accessibility issue?

None

### Reproduction

Pre swc (using TS): 

- esm map: https://unpkg.com/@fluentui/react-text@9.3.1/lib/Body1.js.map 
- cjs map: https://unpkg.com/@fluentui/react-text@9.3.1/lib-commonjs/Body1.js.map
- cjs: https://unpkg.com/@fluentui/react-text@9.3.1/lib-commonjs/Body1.js

Post swc:

- esm map: https://unpkg.com/@fluentui/react-text@9.3.2/lib/Body1.js.map 
- cjs map: https://unpkg.com/@fluentui/react-text@9.3.2/lib-commonjs/Body1.js.map
  - duplicate `sourceMappingURL ` present within the source map as well <img width="1553" alt="image" src="https://user-images.githubusercontent.com/1223799/227569093-d6855266-eac6-4e56-956c-abacd94453ed.png">
 
- cjs: https://unpkg.com/@fluentui/react-text@9.3.2/lib-commonjs/Body1.js
  - <img width="640" alt="image" src="https://user-images.githubusercontent.com/1223799/227569790-30df203b-4bd4-4c4d-bb3d-58d40168c547.png">
 

## Actual Behavior

After migration to swc, source maps for commonjs inputs don't point to TS original source anymore.

Also the `sourceMappingURL` is being printed twice within cjs output (which is present within  the source map )

## Expected Behavior

This regression is actually expected, but we didn't thought about it while implementing the change, as our transpilation pipeline changed 

From

```mermaid
graph LR;
 
S["Start"]
E["End"]
B["Babel"]

    S-->TSC:esm-->B
    S-->TSC:cjs-->B
    B-->E;
```

To

```mermaid
graph LR;
 
S["Start"]
E["End"]
B["Babel"]

    S-->SWC:esm-->B-->SWC:cjs-->E
```

Besides the duplicated `sourceMappingURL` emit within cjs output, it shouldn't have any real impact for consumers, as we use `sourcesContent` which is a source of truth for the actual source mapping.

More feedback is needed.

Actionable for now is to reduce that duplicate emit for commonjs. 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

## Related issues/PRs

https://github.com/microsoft/fluentui/pull/27250

**Comment by layershifter** [comment]
It's clearly SWC bug: https://codesandbox.io/p/sandbox/funny-wildflower-wnxf1b

```shell
$ npx swc ./index.js -o output.esm.js --config module.type=es6 --source-maps=true
```

⬇️⬇️⬇️

```js
import path from "path";
console.log("Hello CodeSandbox", path.dirname("./foo/bar.js"));


//# sourceMappingURL=output.esm.js.map
```

```shell
$ npx swc ./output.esm.js -o output.cjs.js --config module.type=commonjs --source-maps=true
```

⬇️⬇️⬇️

```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
var _path = /*#__PURE__*/ _interopRequireDefault(require("path"));
function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
        default: obj
    };
}
console.log("Hello CodeSandbox", _path.default.dirname("./foo/bar.js")); //# sourceMappingURL=output.esm.js.map


//# sourceMappingURL=output.cjs.js.map
```

👆"sourceMappingURL" comment is doubled
