### ISSUE TITLE
[Bug]: The width setting for the AreaChart doesn't work on small screen devices

### ISSUE THREAD

**Issue by huimiu** [microsoft/fluentui#27331]
### Library

fluentui/react-charting

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 12.20 GB / 31.78 GB
  Browsers:
    Edge: Spartan (44.22621.1483.0), Chromium (111.0.1661.44)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/huimiu/area-chart-repro

## Actual Behavior
Width is very narrow.
![image](https://user-images.githubusercontent.com/107838226/227904926-e41e255e-5832-4827-889c-09bafe50bceb.png)

## Expected Behavior
It should fill the container or can specify the width freely.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by AtishayMsft** [comment]
@huimiu Does changing the width property not change the width of your chart. If the fix doesn't work, lets connect on how to solve it.

**Comment by huimiu** [comment]
@AtishayMsft Yes, I tried to modify the width property, but it's not working.

**Comment by huimiu** [comment]
@AtishayMsft May I ask if there has been any progress?

**Comment by AtishayMsft** [comment]
Checked with Hui. The issue is not reproing at our end.
Feel free to reopen if you get a consistent repro.
