### ISSUE TITLE
MenuItem unexpectedly applies keyboard-only focus-visible style in input mode

### ISSUE THREAD

**Issue by RachelYing** [microsoft/fluentui#27352]
### Environment Information

- **Package version(s)**: Fluent UI React V9
- **Browser and OS versions**: Chrome, Edge, macOS 13.2.1, Windows 11

### Describe the issue:

Please check the attached video: when input mode is active, focus-visible style got activated on MenuItem and it shows a black border around MenuItem; But focus-visible style is supposed to only be activated when user is navigating using the keyboard. 

To repro: Typing in a input area and then hover mouse over the MenuItem component, or press Ctrl on keyboard while focus anywhere, see the black border around MenuItem component.

#### Expected behavior:

There should be no black border around MenuItem unless user is navigating using the keyboard. 

### If applicable, please provide a codepen repro:
if this helps: demo: https://codesandbox.io/s/mutable-https-bcgblb?file=/example.tsx
https://bcgblb.csb.app/

screen recording:
https://user-images.githubusercontent.com/33263585/228078007-81293f9c-6680-4d45-8b92-400a0d3b38a2.mov

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) - I'm not sure how to fix it

Requested priority: (Blocking, High, Normal, Low) - High

Products/sites affected: (if applicable)

**Comment by ling1726** [comment]
Blocked by microsoft/keyborg#36
