### ISSUE TITLE
[Bug]: package.json should export css files

### ISSUE THREAD

**Issue by Aidam1** [microsoft/fluentui#27356]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 3.22 GB / 15.88 GB
  Browsers:
    Chrome: 111.0.5563.110
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.54)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/currying-pond-89zwg6?file=/src/App.tsx

## Actual Behavior
Cannot import '@fluentui/react/dist/css/fabric.min.css', because it is not defined in package.json exports. This is not happening in codesandbox example, but is still an issue.

## Expected Behavior
I'm able to import css files directly into my project. It should work the same as with sass files.

### Logs

```shell
ERROR Module not found: [...] Error: Package path ./dist/css/fabric.min.css is not exported from package
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
I don't have all context regarding v8 public APIs for styling but it sounds reasonable to add compiled styles we already ship to npm to our exports

```diff
"exports": {
+    "./dist/css/*": "./dist/css/*",
    "./dist/sass/*": "./dist/sass/*",
```

**Comment by Hotell** [comment]
@Aidam1 can you provide your use-case with this approach ? why can't you use scss etc ? ty!

**Comment by Aidam1** [comment]
> @Aidam1 can you provide your use-case with this approach ? why can't you use scss etc ? ty!

@Hotell I am not using scss in my project, and I didn't want to add it just for these styles. Since the option of .css was available, I didn't see any reason to go for scss.
