### ISSUE TITLE
[Bug]: Tree - No selected state

### ISSUE THREAD

**Issue by Jing29** [microsoft/fluentui#27355]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components 9.18.6
Tree component: https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/preview-components-tree-tree--default
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/cranky-cannon-7pbxvp?file=/example.tsx

## Actual Behavior
Cannot not set selected state for a tree node

## Expected Behavior
Can set selected state for a selected tree node

## Repro code sandbox:
https://codesandbox.io/s/cranky-cannon-7pbxvp?file=/example.tsx
![image](https://user-images.githubusercontent.com/19400548/228140192-6a99612c-e44b-42c8-ae8e-e97842a074f9.png)

### Requested priority

Blocking

### Products/sites affected

PowerBI

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
Hey there @Jing29, select/multiselect state is a desirable feature we will be implementing before releasing stable version of `react-tree`! For now it is not available, but rest assured this will change in no time!
