### ISSUE TITLE
[Bug]: DetailsList - React 18 StrictMode - Selection.Mode multiple - item selecting issue

### ISSUE THREAD

**Issue by hxltinh** [microsoft/fluentui#27370]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.55 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 103.0.2
    Safari: 16.3
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/hxltinh/fluent-ui-details-list-react-strict-mode-bug

### Bug Description

# Fluent UI DetailsList React Strict Mode issue.

When using React 18 and Detailslist in StrictMode, it is not possible to select an item. When clicking a checkbox the list item does not get selected.

## Available Scripts

In the project directory, you can run:

### `npm start`

Runs the app in the development mode.\
Open [http://localhost:3000](http://localhost:3000) to view it in the browser.

## Reproduce steps.

- Start App in development mode and try to select and item
- Observe that you cannot select an item
- Remove `<StrictMode>` tag from App.ts to see the difference.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Blocked by #27851

**Comment by kescherCode** [comment]
Fucking stale bots.

**Comment by DGuentherTV** [comment]
Just ran into this bug.

It boils down to this:

- React 18 strict mode unmounts and remounts components.
- Unmounting the DetailsRowBase component leads to calling dispose() on its internal EventGroup instance.
- Remounting does not call the constructor again, so the componentDidMount hook will try to subscribe to the disposed EventGroup instance which is basically a noop. 

Subsequently, the component does no longer re-render when the selection changes
