### ISSUE TITLE
[Bug]: Popover keyboard tab behaves differently with tabster v4 and v3

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#27422]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 51.85 GB / 63.57 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.78)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/festive-meninsky-uzbwe5?file=/example.tsx

## Actual Behavior
In [newer version codesandbox](https://codesandbox.io/s/festive-meninsky-uzbwe5?file=/example.tsx), note that if you use keyboard tab, open the dialog, the dialog will show loading firstly then has focusable elements. After the popover loading is ready, you cannot tab into popover because `aria-hidden=true` is applied to it. I have to manually call elment.focus after loading to activate popover.

## Expected Behavior
In [earlier version codesandbox](https://codesandbox.io/s/vigorous-yonath-bnn7eh?file=/example.tsx), I do not need to manually call elment.focus after loading, it will not add `aria-hidden=true` to the popover. And with legacyTrapFocus, it behaves as expected. 

Without legacyTrapFocus, it will not trap focus even I set trapFocus to true, unless I manually call elment.focus after loading. However this is another issue. 

The main issue here is with latest fluentui v9, with tabster v4, it will automatically apply `aria-hidden=true` to the popover. Is this expected behavior? 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by flora8984461** [comment]
Not sure if this https://github.com/microsoft/tabster/issues/250 might cause this? Or totally different issue?

**Comment by miroslavstastny** [comment]
@bsunderhus could you please check (cc @mshoho)

**Comment by bsunderhus** [comment]
This seems to be very similar to https://github.com/microsoft/fluentui/issues/27468, but on `PopoverSurface` instead of `DialogSurface`. seems like adding modalizer attributes are causing some troubles

**Comment by mshoho** [comment]
@bsunderhus from the Tabster side this is working as intended. A popup here has a focus trap enabled which creates Modalizer to make the popup contents modal. Making it modal means that it is not accessible to the rest of the application when inactive (doesn't have focus) or the rest of the application is not accessible when the modal is active (has focus).

The way to make modal active is to programmatically focus something in it, but there is nothing to focus when there are no focusable elements, so auto focusing first element doesn't work on mount and the modal remains inactive. So, the manual focusing is needed to activate it. Or the focus trap could be disabled.

Perhaps we could provide some helper to make focusing asynchronously mounted focusable things easier. But for now in this scenario the manual focus call is required to activate the popup's modal (if focus trap is used).
