### ISSUE TITLE
[Bug]: It is not possible to attach onSelect or onClick handler on a Tab component within TabList

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#27427]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
any
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/exciting-bhaskara-530j9z?file=/example.tsx

## Actual Behavior
onClick or onSelect props on Tab are ignored 

## Expected Behavior
When onClick or onSelect is used, the callbacks provided by the user on Tab need to be called when the tab is selected (or clicked using mouse/touch/keyboard)

### Requested priority

Blocking

### Products/sites affected

Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by GeoffCoxMSFT** [comment]
The PR fixed the onClick issue.  There is not an onSelect event callback for Tab, only TabList, so callers need to subscribe to the event there.
