### ISSUE TITLE
[Bug]: `@types/react@17.0.56` contains breaking change that fails `tsc` on fluentui/react (V8)

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#27425]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
na
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=295858&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=254ee48e-1503-524f-f75e-e2c69d0380f5

1. `yarn lage build --to @fluentui/ts-minbar-test-react`
2. `yarn workspace @fluentui/ts-minbar-test-react test`

## Actual Behavior

> Observed yesterday (3rd of April in master pipeline ).

our TS minbar is a safeguard to prevent shipping non supported TS features to our users.

for react(v8) test suite we specify `dependencies` like for react types via `@types/react@17`, which during test run will install latest 17 type version. 

- version 17.0.55 worked as expected
- version 17.0.56 introduced breaking change making `tsc` throw error

👀 Issue introduce by this PR https://github.com/DefinitelyTyped/DefinitelyTyped/commit/3f5d20608d31363487694535189ef64569043ff9#diff-6df5e9a2eb9edb2dcf93fe75b95032e8870a94789157856c5544ece346026a0a

**Diff:**

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/1223799/229738458-26d79a80-55ea-467c-8aaf-cd8c79e50e3a.png">
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/1223799/229738618-31fdd3fe-55f8-44d1-b77e-0f9996c833b7.png">
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/1223799/229738730-74dec1c9-68de-42fc-97bc-05311020b41a.png">

version 17.0.56 did some `content` interface property re-shuffling which causes following tsc errors:

<img width="1694" alt="image" src="https://user-images.githubusercontent.com/1223799/229738078-8f425ecf-f0ef-45e9-a98b-47d1315dc440.png">

## Expected Behavior

minor/patch versions of 3rd party types should not introduce breaking changes - this needs to be fixed on DefinitelyTyped repo.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
to unblock our pipelines we can pin version of `@types/react` to `17.0.55`, but this change needs to be rollback on DTS package

**Comment by jeswr** [comment]
Having a look at the line in your code causing the error (https://github.com/microsoft/fluentui/blob/5a8d7a29645b3b500eb7145d2e42ac34fcafc4c6/packages/react/src/components/Tooltip/TooltipHost.types.ts#L66); the content parameter is already optional which implicitly allowed for undefined values pre typescript 4.4 (which you appear to support https://github.com/microsoft/fluentui/blob/5a8d7a29645b3b500eb7145d2e42ac34fcafc4c6/package.json#L343).

So as far as I can tell `undefined` should have been added an option in preparation for `exactOptionalPropertyTypes` in Typescript 4.4 (similar to PRs like https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54244/files); and so the best course of action would be to patch this library - updating the `content` parameter to have type `content?: string | JSX.Element | JSX.Element[] | undefined`.

**Comment by Hotell** [comment]
hey @jeswr , thanks for reaching out. your suggested changes wont help <img width="1806" alt="image" src="https://user-images.githubusercontent.com/1223799/230332516-968e89d8-94e0-42d1-b6de-712eb7642270.png">

To give you more context, while our repo uses TS 4.3.5 our supported minbar is TS 3.9 , that's the version we use to run type check validations on CI. So this needs to be rolled back on Definitely typed or start using `typeVersions`

**Comment by johnnyreilly** [comment]
> we can pin version of @types/react to 17.0.55

**Comment by Hotell** [comment]
hey @johnnyreilly ! hope you're doing good sir 🙌 , yes in typescript case that's true. pinning deps introduces dupes in users codebases so while it might protect our code, it might make users life far worse. so pick your poison right. 🔥

anyways the workaround should be good for now. cheers
