### ISSUE TITLE
[Feature]: Allow for arbitrary colors to be passed in Avatar

### ISSUE THREAD

**Issue by tronguye** [microsoft/fluentui#27437]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

`<Avatar />` currently accepts a prop, `color`, that can be either neutral, brand, colorful, or a specific predefined color by name

For Microsoft Loop we'd like to be able to be able to pass arbitrary/custom colors to the Avatar to match the presence color used within the canvas for carets, which may not cleanly map to the predefined colors or the underlying v9 tokens that are used

Ideally we'd be able to pass in any valid css color string, but open to specifically hex or rgb formatted strings if that would allow for better TS definitions.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by miroslavstastny** [comment]
There are two reasons why there is a limited set of named colors:
1. to ensure the colors match Fluent theme
2. to support Light/Dark (/High Contrast) theme switching.

How would you expect the theme switching would work in your scenario? I can see some solutions but none of them seems to be robust enough.
