### ISSUE TITLE
[Feature]: Ability to have Details List first column header follow groups, not items

### ISSUE THREAD

**Issue by Mitchell-Larson** [microsoft/fluentui#27435]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

At present, when specifying a `DetailsList` with at least one nested group, the farthest left column header will align itself with the horizontal position of the first cell of the items:
![image](https://user-images.githubusercontent.com/129885847/229910852-6cd1d158-a8fd-4371-b354-276d3260fb6c.png)

However, what my team and I are looking for is to have the farthest left column header align itself with the top-level groups:
![image](https://user-images.githubusercontent.com/129885847/229910786-ea81332a-a3cc-44db-92a6-c2d206159bc5.png)

This is because the way we're using the `DetailsList`, it makes more sense for us to have a column header which labels/refers to the groups. As far as I can tell, we don't have a way to accomplish this presently without breaking some of the column layout logic.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by miroslavstastny** [comment]
Correct, `DetailsList` unconditionally adds <GroupSpacer /> into the header when there are nested groups.
