### ISSUE TITLE
v9 @fluentui/react-portal-compat has typescript errors with react 18

### ISSUE THREAD

**Issue by ewylie25** [microsoft/fluentui#27432]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.20348
    CPU: (16) x64 Intel(R) Xeon(R) W-2245 CPU @ 3.90GHz
    Memory: 90.19 GB / 127.59 GB
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/elastic-satoshi-verts6?file=/src/index.tsx:178-198

## Actual Behavior
In codesandbox I get the intellisense error "Cannot find module '@fluentui/react-portal-compat' or its corresponding type declarations"
In local development environment I get this error from tsc: "Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'."

## Expected Behavior
provider works as documented - https://react.fluentui.dev/?path=/docs/concepts-migration-from-v8-troubleshooting--page#i-tried-using-the-new-components-inside-v8-callouts-panels-etc-but-there-does-not-seem-to-be-any-styling-applied-to-them-am-i-doing-something-wrong

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
@ewylie25 you can check for the PR # in [this file](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-portal-compat/CHANGELOG.md), once you see it there it should be obvious which version of the package this change was released in.
