### ISSUE TITLE
[Bug]: TooltipHost does not open when hovered/focused when running with `vite run`

### ISSUE THREAD

**Issue by rcbevans** [microsoft/fluentui#27451]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (48) x64 AMD Ryzen Threadripper 3960X 24-Core Processor
    Memory: 44.73 GB / 62.66 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 111.0.1

    "@fluentui/react": "^8.107.1",
    "@fluentui/react-hooks": "^8.6.20",
    "@fluentui/react-icons-mdl2": "^1.3.37",
    "@fluentui/react-shared-contexts": "^9.3.3",
    "@fluentui/theme": "^2.6.25",
    "vite": "^4.2.1",
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rrim5b?file=src/App.tsx

## Actual Behavior
Mouse over/focus TooltipHost and the tooltip content doesn't show.

## Expected Behavior
Tooltip content should show on mouse over/focus.

Observe in the repro that onMouseEnter/onMouseLeave fire correctly for the 'Normal Div' but the events events are not firing for the TooltipHost.  It seems when running under vite the TooltipHost does not attach the necessary listeners, or receive the expected events.

Producing a "production" build which compiles for release using rollup, the Tooltips work as expected.

### Requested priority

Normal

### Products/sites affected

All users of vite + @fluentui TooltipHosts in dev

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by rcbevans** [comment]
Someone from vite looked at this based on the other bug report and noticed that the TooltipHost works under vite run when the TooltipHost is not a descendant of React.StrictMode.

**Comment by spmonahan** [comment]
Blocked by #27851
