### ISSUE TITLE
[Feature]: New tokens for translusent colors

### ISSUE THREAD

**Issue by NataliaBar** [microsoft/fluentui#27459]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

At the moment, there are only 2 tokens (and extra tokens for hover/pressed/selected) for translucent colors in v9:
colorNeutralBackgroundAlpha
colorNeutralBackgroundAlpha2

![v9Alpha Tokens](https://user-images.githubusercontent.com/19690885/230243641-a6d0a984-66ef-49ed-bb8c-a953be2d8241.jpg)

However, there are more [translucent color values](https://www.npmjs.com/package/@fluentui/design-tokens-dcs?activeTab=code), that are used in product today (and are planned to be used in the future)

At the moment, our team is missing a token for  `--globalColorWhiteAlpha20: #ffffff33`
But I'd argue that all translucent colors should be added to v9.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by miroslavstastny** [comment]
cc @daisygeng, @redongreen
