### ISSUE TITLE
[Bug]: For FluentUI V9's dialog, I can't focus elements in dialog's form if I click outside trigger button while dialog opening.

### ISSUE THREAD

**Issue by adamma1024** [microsoft/fluentui#27468]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 6.73 GB / 31.78 GB
  Browsers:
    Chromium (111.0.1661.41)
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/modest-margulis-e1uej9

## Repro steps
1. Click `Open formulary dialog` button
2. While dialog opening, click `Open formulary dialog` button again (Do not close dialog)
3. Click the any input in the dialog. You will find that it will automatic blur, and users can not continually input anymore.

## Actual Behavior
It will automatically blur when users try to focus on the input.

## Expected Behavior
It focuses correctly.

### Logs

```shell
I notice that `tabster.esm.js` and `keyborg.esm.js` will be invoked anytime when exception occurring. And the Call Stack is as following:

_restoreModalizerFocus (tabster.esm.js:4777)
(anonymous) (tabster.esm.js:4523)
setTimeout (async)
ModalizerAPI._onFocus (tabster.esm.js:4523)
eval (tabster.esm.js:2253)
_callCallbacks (tabster.esm.js:2253)
setVal (tabster.esm.js:2244)
setVal (tabster.esm.js:3753)
_setFocusedElement (tabster.esm.js:3748)
FocusedElementState._onFocusIn (tabster.esm.js:3475)
focusInHandler (keyborg.esm.js:130)

I wish it can be helpful
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
Reproducible, thanks for reporting the issue.
cc @mshoho, @bsunderhus

**Comment by bsunderhus** [comment]
This seems to be an issue with tabster attributes on non-modal dialogs. Thanks for the reproduction steps @adamma1024

**Comment by bsunderhus** [comment]
Here's a minimal reproduction of the same problem https://codesandbox.io/s/busy-breeze-pybxcb?file=/example.tsx
