### ISSUE TITLE
[Bug]: <Dropdown> in <Dialog> renders the dropdown box too long

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#27486]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
(Using CodeSandbox)

"@fluentui/react-components": "9.18.6"
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/dropdown-dialog-long-list-5iwjsr

## Actual Behavior
Dropdown box inside the Dialog seems to get extended over the top of the web view. There is no vertical scrollbar.

![image](https://user-images.githubusercontent.com/50703224/230603677-21abc3e2-18b5-4add-a252-f858dcfee59d.png)

## Expected Behavior
Dropdown box outside the Dialog chooses a suitable height and I can scroll through the items with vertical scrollbar.

![image](https://user-images.githubusercontent.com/50703224/230603553-b6e8ff29-3c0e-4b5c-b162-652b16d567ec.png)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by adamma1024** [comment]
I met this issue either. Looks like it didn't consider the current position while calculating the `max-height`

**Comment by sumitshinde-84** [comment]
I would like to work on this issue,  can you please assign it to me?
