### ISSUE TITLE
[Bug]: Datepicker edge case inside Dialog component

### ISSUE THREAD

**Issue by lmvdz** [microsoft/fluentui#27495]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
    Memory: 3.53 GB / 15.66 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
```

### Are you reporting Accessibility issue?

None

### Reproduction

Can not reproduce given tools, as the other bug doesn't allow for installing the datepicker from npm

## Actual Behavior
Datepicker inside Dialog

When the calendar popup is dismissed by clicking away from the popup, the ability to focus the input for text input bugs out for **all** inputs of the Dialog. 

As soon as the input is clicked and focused, the focus gets removed.

Another bug with this is the page scrolls all the way to the bottom.

Only after selecting a date from the calendar popup does focusing inputs inside the dialog work as expected.

Works as expected outside of Dialog!

## Expected Behavior
When clicking away from the popup, the ability to focus the input should not bug out.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
It appears that sometimes when the Datepicker is closed, it causes tabster to act as if the Dialog was closed as well -- it re-focuses the original dialog trigger, prevents focus from entering the dialog, and removes `aria-hidden` from the main body content. This is what is causing the observed focus issue with the input.

There are two other focus problems with Datepicker:
- Pressing `Escape` from within the Datepicker popup closes the Dialog
- Clicking something outside the Datepicker popup like a sibing Input does not allow focus to remain in the clicked element
