### ISSUE TITLE
[Bug]: Can't find module @fluentui/react-datepicker-compat

### ISSUE THREAD

**Issue by lmvdz** [microsoft/fluentui#27494]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
    Memory: 3.53 GB / 15.66 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
```

### Are you reporting Accessibility issue?

None

### Reproduction

yarn add @fluentui/react-datepicker-compat

## Actual Behavior
no package found (npm package not published)

## Expected Behavior
install the package

[](https://react.fluentui.dev/?path=/docs/preview-components-datepicker-compat--default)

### Logs

```shell
An unexpected error occurred: "https://registry.yarnpkg.com/@fluentui%2freact-datepicker-compat: Not found".
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by lmvdz** [comment]
I see the compat folder in the git packages/react-components directory, but it doesn't install. 

```json
{
"name": "@fluentui/react-components",
  "version": "9.18.8",
  }```

**Comment by miroslavstastny** [comment]
The package is still under active development and for that reason intentionally marked as private. ETA for unstable version publish is this month.
