### ISSUE TITLE
[Bug]: <Input> + <Field> in <DialogContent> causes a vertical scrollbar being rendered

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#27500]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components: v9.18.6
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/field-in-dialog-uinyxp?file=/example.tsx

### Bug Description

Regression of #26061

## Actual Behavior
![image](https://user-images.githubusercontent.com/50703224/230903060-3a1393a0-d3be-4741-a383-dc99aee7bec8.png)

## Expected Behavior
There shouldn't be a vertical scrollbar rendered.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by nsteenbeek** [comment]
This issue was reproducible by a any content like <p>lorem ipsum</p>.
I had the same problem but found that upgrading from v9.18.6 to v9.18.8 solved the problem.
@chenxinyanc please check and close the issue?

**Comment by smhigley** [comment]
@chenxinyanc I also don't see the scrollbar issue on the latest release. Could you let me know if you still see any overflow issues after updating?
