### ISSUE TITLE
[Bug]: Reset icon does not render in button

### ISSUE THREAD

**Issue by Lalithakmsft** [microsoft/fluentui#27511]
### Library

Web Components (@fluentui/web-components)

### System Info

```shell
Please ignore as this is failing with timeout error:

35 verbose stack FetchError: request to https://registry.npmjs.org/envinfo failed, reason: connect ETIMEDOUT 2606:4700::6810:1623:443
35 verbose stack     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
35 verbose stack     at ClientRequest.emit (node:events:513:28)
35 verbose stack     at TLSSocket.socketErrorListener (node:_http_client:502:9)
35 verbose stack     at TLSSocket.emit (node:events:525:35)
35 verbose stack     at emitErrorNT (node:internal/streams/destroy:151:8)
35 verbose stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
35 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/lalitha78/pen/VwELNKg

## Actual Behavior
New item button is given "Reset" icon but does not render the icon.

## Expected Behavior
"Reset" icon should render.

![image](https://user-images.githubusercontent.com/128369884/231108987-221e9e44-b869-47d0-9fcb-4f6f58038c49.png)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chrisdholt** [comment]
@Lalithakmsft the repro above explicitly points to *React*, yet this has been noted as "Web Components". Web Components are a collection of technologies which make up the component model on the web rather than being read as "components for the web": https://developer.mozilla.org/en-US/docs/web/web_components. React, is a framework and the two are fundamentally different. Assigning this to @smhigley for triage.

**Comment by smhigley** [comment]
@Lalithakmsft the reason it doesn't render is because "Reset" is not a Fluent icon name. You can see the full catalog of Fluent icons in our documentation here: https://developer.microsoft.com/en-us/fluentui#/styles/web/icons#fabric-react

The closest I can think of offhand is "Undo".

**Comment by Lalithakmsft** [comment]
Hi Sarah,

Thank you for checking this and letting me know. I would like to share feedback that it will helpful if one liner is mentioned in this page as well "https://developer.microsoft.com/en-us/fluentui#/controls/web/icon" saying that the svg icons should be consumed differently than the font icons and share the below link there.

Many thanks again.

Thanks,
Lalitha
