### ISSUE TITLE
[Bug]: DatePicker focus of current value (v8 regression) 

### ISSUE THREAD

**Issue by JeffJankowski** [microsoft/fluentui#27510]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 3.87 GB / 15.86 GB
Browsers:
    Chrome: 112.0.5615.49
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.34)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/JeffJankowski/pen/abROKVz

## Actual Behavior
Setting date programmatically when initially set as `undefined` does not focus the current date in the calendar view.

![image](https://user-images.githubusercontent.com/5688647/231073566-a2819094-f2b7-4efe-adc4-f21482b418dc.png)

## Expected Behavior
This worked previous in v7, which can be seen by changing the unpkg version in the codepen.

![image](https://user-images.githubusercontent.com/5688647/231073708-acd3c594-2247-4fd4-b0e1-f90345b484bc.png)

Note this can "fixed" by setting the initial date value as `null` instead of `undefined`. However, the Typescript type definitions for the `value` prop does not accept `null` and therefore requires a ts linter ignore comment.

### Requested priority

Normal

### Products/sites affected

Fluent React v8

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
This is because the DatePicker in the codepen is initialized as uncontrolled, since the initial state is `undefined`. If you do this instead, it works:

`const [selectedDate, setSelectedDate] = React.useState<Date>(new Date());`

@JeffJankowski let me know if that solves your issue!

**Comment by JeffJankowski** [comment]
@smhigley Yes, I understand that. But there are circumstances where I want a controlled component, but the initial value is not set. This is solved by using an empty string in like a TextField, but obviously that is not going to work where the value needs to be a Date object. 

For non-string valued components, the typical strategy is using `undefined` for uncontrolled, and `null` for "not-set, but controlled." This works in this case here as well, but the current type definitions do not indicate `null` is valid and therefore will throw an error.

**Comment by JeffJankowski** [comment]
@smhigley Can you explain why this was closed? I'm open to the idea that this is not an issue or I'm missing something here, but initializing the value with `new Date()` does not provide the missing functionality I originally opened this ticket for.
