### ISSUE TITLE
[Bug]: I cannot set the rating to zero once I add a rating. 

### ISSUE THREAD

**Issue by akravindran** [microsoft/fluentui#27513]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.23435
    CPU: (20) x64 Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
    Memory: 49.66 GB / 63.72 GB
  Browsers:
    Edge: Spartan (44.23435.1000.0), Chromium (112.0.1722.39)
    Internet Explorer: 11.0.23435.1000
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/akravindran123/pen/MWPwRrO

## Actual Behavior
When using tab to navigating to Rating element on page it sets the rating to be 1. But there is no way to set it to zero

## Expected Behavior
Must be able to set the rating to 0

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@akravindran the 0-star rating is like the half-star rating in that it can be programmatically set or set as a default value, but cannot be user-selected.

Here are our docs on `allowZeroStars`:
> Allow the initial rating value (or updated values passed in through rating) to be 0. Note that a value of 0 still won't be selectable by mouse or keyboard.

**Comment by smhigley** [comment]
I admit both our 0-star Rating and half-star Ratings are quite weird/unintuitive 😅
