### ISSUE TITLE
[Bug]: Screen Reader reads "button collapsed" for DOM element with data-tabster attribute

### ISSUE THREAD

**Issue by saahilchawande123** [microsoft/fluentui#27526]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10
Browsers:
    Edge, Chrome
```

### Are you reporting Accessibility issue?

yes

### Reproduction

Issue not reproducible in the sandbox

## Actual Behavior
The screen reader reads "button collapsed" for a DOM element at the bottom of the page. The DOM element looks like this:
`<div class="___z48vva0 f19dog8a f198g47y fvfyk4 f1565x02 fd9tnaj" role="button" tabindex="0" data-tabster="{&quot;deloser&quot;:{}}" aria-expanded="false"></div>`

## Expected Behavior
The screen reader should not read "button collapsed" for the DOM element.

Minimal Screen Recording:

https://user-images.githubusercontent.com/116312427/231307454-5935851d-d0ee-458b-9ea6-8e8c8ca4daee.mp4

NOTE: We are importing tabster in the package.json file, is there an expectation to use @fluentui/react-tabster import in package.json? 

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@saahilchawande123 the reason for the "button collapsed" announcement is the combination of `role="button"` and `aria-expanded="false"`. Tabster and the data-tabster attribute is not affecting it in any way.

What is the JSX for the div-button? Is this in a Fluent component?

**Comment by saahilchawande123** [comment]
Hello @smhigley, yes this is a FluentUI component. I could not locate the JSX for this DOM element, think it's coming from fluentui.

**Comment by smhigley** [comment]
@saahilchawande123 what Fluent component is it? In general, at a minimum when creating buttons you would need to provide either visible text or an accessible name (e.g. in the case of an icon button).

If we have a div-button somewhere in v9 I'd like to take a look though, since we've made it a priority to use built-in HTML elements for interactive controls.

**Comment by smhigley** [comment]
Chatted with @saahilchawande123 separately and we found the rogue button. Closing this issue.
