### ISSUE TITLE
[Bug]: Popover surface does not respect left and right css props

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#27522]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 51.85 GB / 63.57 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.78)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/exciting-wildflower-9kitt7?file=/example.tsx

## Actual Behavior
Passing style of left and right to the popover surface does not work. I hope to adjust the position, but do not want to break what currently it has already.

## Expected Behavior
Passing style of left and right to the popover surface should adjust the position to a left or right, and does not break what currently it has already. 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@flora8984461 Popover dynamically positions itself when it opens based on props, and will override positioning props applied through styles.

To customize Popover position, use the `position`, `align`, and `offset` props, documented here: https://react.fluentui.dev/?path=/docs/concepts-developer-positioning-components--default. Those should allow you to fully customize position relative to the target along both axes.

Hope that answers your question!

**Comment by flora8984461** [comment]
Thank you @smhigley  I didn't notice there is another doc page for position. This works. Thank you!
