### ISSUE TITLE
[Bug]: `@fluentui/react-portal-compat` not working in React 18.

### ISSUE THREAD

**Issue by blueset** [microsoft/fluentui#27530]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.25330
    CPU: (12) x64 Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz
    Memory: 26.19 GB / 63.59 GB
  Browsers:
    Edge: Spartan (44.25330.1000.0), Chromium (112.0.1722.39)
    Internet Explorer: 11.0.25330.1000


- `@fluentui/react`: 8.107.1,
- `@fluentui/react-components`: 9.18.8
- `@fluentui/react-portal-compat`: 9.0.51
- `react`: 18.2.0
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/trusting-allen-tssvzy?file=/example.tsx

## Actual Behavior
Fluent UI v9 components in a Fluent UI v8 `<Panel />` should be styled properly.

## Expected Behavior
Fluent UI v9 components in a Fluent UI v8 `<Panel />` are not styled.

## Cause
[Fluent UI v9 is using `useId()` from React behind the scene if available](https://github.com/microsoft/fluentui/blob/740f3aa9dc9946d9f646831e92f8eccc34e80a22/packages/react-components/react-utilities/src/hooks/useId.ts#L35-L46), and [`useId()` in React 18 does not ensure the ID appended to the prefix is numeral](https://github.com/facebook/react/blob/5426af3d50ff706f3ebeb4764f838e0a3812bf9a/packages/react-reconciler/src/ReactFiberHooks.js#L2515), while [`<PortalCompatProvider />` is looking for a numerical suffix while looking for the theme class name](https://github.com/microsoft/fluentui/blob/740f3aa9dc9946d9f646831e92f8eccc34e80a22/packages/react-components/react-portal-compat/src/PortalCompatProvider.tsx#L8). Causing the lookup to fail, and the styles of v9 components not applied when in a v8 portal with the compatibility layer applied.

### Logs

```shell
N/A
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@blueset great catch ❤️ Are you interested in contributing a fix?

**Comment by blueset** [comment]
@layershifter, Opened a PR at #27577

**Comment by layershifter** [comment]
> @layershifter Oleksandr Fediashov aka shift FTE, Opened a PR at #27577

@blueset cool, I will review it next week 👍
