### ISSUE TITLE
[Feature]: Disable CodeSandbox CI?

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#27531]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

We have a CI step that currently does not produce meaningful results and sometimes just randomly fails:

<img width="844" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/14183168/231416831-cb9ab97d-3e78-484d-92ee-e349255cfdf7.png">

We also don't use features provided by CodeSandbox CI.

The proposal is to disable it and reduce an amount of checks that we have.

### Have you discussed this feature with our team

@Hotell

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Hotell** [comment]
based on v-build convo we will remove it from pipeline checks for now. 



some additional context: 
it brings a value though for contributors as it build in PR changes that can be tested out on codesandbox directly ( this is not reflected in our v9 storybook docsite examples though ). 

for future this can be a good candidate for v9 nightlies.

**Comment by Hotell** [comment]
this is planned

**Comment by Hotell** [comment]
just removed codesandbox app
