### ISSUE TITLE
[Bug]: DetailsList virtualization does not work if is descendant of React.StrictMode

### ISSUE THREAD

**Issue by nlips** [microsoft/fluentui#27533]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
  OS: Windows 10 10.0.22621
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 2.64 GB / 15.85 GB
Browsers:
  Edge: Spartan (44.22621.525.0), Chromium (112.0.1722.34)
  Internet Explorer: 11.0.22621.1

- `@fluentui/react`: 8.107.4
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react-detailslist-strictmode-virtualization.stackblitz.io

## Actual Behavior
Only the first few items appear. When scrolling, the following items are not displayed.

## Expected Behavior
When scrolling, the following items must be displayed.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
I'm pretty sure FUI v8 does not support React 18 strict mode, @micahgodbolt can you confirm?

**Comment by spmonahan** [comment]
Blocked by #27851
