### ISSUE TITLE
chore: Add conformance tests for slot render functions

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#27566]
We need tests that check that slot render functions are working properly when set via a slot prop.

This bug was a recent regression that broke all slot render functions, but was not caught by any tests:
* #27559

The test could be in the form of a conformance test, or possibly an e2e test.

**Comment by bsunderhus** [comment]
How about a simple unit test that ensure `getSlots` works properly when in interop with `resolveShorthand`?

That's what is missing so far, we test each of them separately, but we don't have tests for both methods together.
