### ISSUE TITLE
[Bug / Discussion]: Should Tooltip show on focus only in keyboard mode?

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#27576]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
v9
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/upbeat-worker-9l6c8u

## Actual Behavior
After closing the dialog with both ESC and using mouse to click on Cancel, Tooltip attached to the trigger is displayed

## Expected Behavior
Up for discussion - if user closed the dialog with mouse, should the tooltip show up even if user is not hovering over the trigger?

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by matt-src** [comment]
My 2 cents from user perspective - I expect a tooltip to show up for a button when I indicate that I am interested in the button / show some intent to click it. If I close a tooltip, I don't believe that indicates any intent that my next action is going to be clicking the button again.

**Comment by smhigley** [comment]
I agree with the desired behavior in this scenario -- showing a tooltip after closing a dialog seems weird.

I think the keyboard vs. mouse is a red herring though -- I wouldn't expect that tooltip to show up after I close a dialog with the keyboard either. And not showing the tooltip on focus for "mouse mode" will have negative side effects for people using screen readers (including sighted or partially sighted SR users), touch users, voice control users, etc.

The better solution IMO would be to not show a tooltip when focus is programmatically moved to a control with JS. That would incidentally also fix the issue with showing a tooltip for the first menu item when a menu opens, or first focusable button in popup, etc.
