### ISSUE TITLE
[Bug][a11y]: Voice Control - Numbers are showing for all 'non-interactive' texts

### ISSUE THREAD

**Issue by vdevarapally** [microsoft/fluentui#27596]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
"@fluentui/react-components"
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/gifted-babbage-g1q7d6?file=/example.tsx

### Bug Description

This is regarding the a11y issue that I have noticed within Text Component of the Fluent UI. When voice control is turned on in Iphone (Settings>>Accessibility>>Voice control) - Looks like the Text elements are also numbered. As per the a11y guidelines - All the non interactive elements should not show numbers. Please find the attached screenshot - 

## Actual Behavior
Text elements are numbered with voice control on over on Iphone.

## Expected Behavior
Non-interactive elements like Text component should not be numbered.
![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/127553436/232589828-e02e80a2-aff9-44f0-92eb-f524061e57f1.png)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
Hi @vdevarapally!

Voice Control on iOS does this across all websites. You can open up wikipedia or any other web page hosting static content, and see numbers generated for static text nodes. This isn't an issue with the Fluent text control, and you shouldn't be worried about this behavior in your own app.
