### ISSUE TITLE
[Feature]: Update the `react` and `react-dom` peer dependency packages to version 18

### ISSUE THREAD

**Issue by kavinkuma6** [microsoft/fluentui#27641]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### Describe the feature that you would like added

Is it possible to update the peer dependencies `react` and `react-dom` to its latest version 18? [Currently it is 17](https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-northstar/package.json#L57)

### Have you discussed this feature with our team

No

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by miroslavstastny** [comment]
`@microsoft/fluentui-northstar` currently does not support React 18 and there is no plan to add the support.
Please consider upgrading to Fluent UI v9 for React 18 support.
