### ISSUE TITLE
[Bug]: useIsOverflowItemVisible returns incorrect at initial state

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#27656]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 51.85 GB / 63.57 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.78)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/admiring-feather-mtyojz?file=/example.tsx

## Actual Behavior
At initial state when there is enough space for all items to show, useIsOverflowItemVisible returns false for each item. As the screenshot shows, and you can also check it in the reproduction codesandbox. It feels like at initial state, and the space is enough, items are not registered to the overflow or the initial context set to false; and the state in context changes only after resize happens. (Let me know if my guess is correct, thank you 😊) 

![image](https://user-images.githubusercontent.com/39588094/233738960-3fa20bf8-0fc6-4ca3-879f-774a34a49a51.png)

## Expected Behavior
Expect the useIsOverflowItemVisible returns true when initial state the items are really showing.

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by flora8984461** [comment]
Hi @ling1726 Do you have any timeline for this to be fixed? We are planning on our product's release. Thank you!

**Comment by ling1726** [comment]
@flora8984461  I've added this to the next sprint 01/05 - 14/05
