### ISSUE TITLE
Toolbar buttons should not have gaps

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#27662]
Current the toolbar buttons have a built in 8px gap 
![image](https://user-images.githubusercontent.com/20744592/233931146-7e40718a-87df-4fbe-bb3a-d34c8e9d5929.png)

According to the design spec, there should be no gaps between toolbar buttons

![image](https://user-images.githubusercontent.com/20744592/233931270-91b7b58d-f4d1-4c3b-9f18-2216b76f0048.png)

**Comment by hirentimbadiya** [comment]
i'd like to contribute to this issue , can you please assign me @ling1726 ?

**Comment by ling1726** [comment]
@hirentimbadiya, feel free to take a shot at this
