### ISSUE TITLE
[Feature]: Tree v9 provide way to stop aligning items

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/fluentui#27683]
### Library

React Components / v9 (@fluentui/react-components)

## Current behaviour

At the moment, by design, nodes on a tree are aligned by it's contents, which means that a leaf node will have an extra left padding to ensure it's always at the same alignment position as branch nodes

![image](https://user-images.githubusercontent.com/5483269/234263733-6a654561-6889-464e-b938-43bb686dd352.png)

## New behaviour

add a property or some mechanism that allows leaf nodes to not be aligned with branch nodes:

![image](https://user-images.githubusercontent.com/5483269/234263887-9f779007-59a5-4c5f-87df-a35189c1b4a5.png)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by petdud** [comment]
Example from VS Code with template that doesn't align items if they are not expandable:
<img width="396" alt="Screenshot 2023-04-25 at 1 50 55 PM" src="https://user-images.githubusercontent.com/13124780/234269685-60e4e4b7-57cc-4173-a604-0d40876bd121.png">

**Comment by petdud** [comment]
We discussed this issue with the design team and agreed that this will not be supported internally. However, this result can be achieved using custom inline styles, here is a simple example: https://codesandbox.io/s/delicate-leftpad-wdtevr?file=/example.tsx
