### ISSUE TITLE
[Bug]: Links inside the content of a TooltipHost seem inaccessible with the keyboard

### ISSUE THREAD

**Issue by riosn-n** [microsoft/fluentui#27693]
### Library

Fluent UI v8

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/riosn/pen/gOBPQPx

## Actual Behavior
User can't click on a link using the keyboard

## Expected Behavior
User should be able to click on a link using the keyboard

https://codepen.io/riosn/pen/gOBPQPx

### Requested priority

High

### Products/sites affected

Power Apps

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
Tooltips should not contain focusable elements and is an a11y antipattern. If you would like to have focusable elements in a positioned component, please use the callout https://developer.microsoft.com/en-us/fluentui#/controls/web/callout
