### ISSUE TITLE
[Bug]: `block` prop is not available on `Button` component.

### ISSUE THREAD

**Issue by nandin-borjigin** [microsoft/fluentui#27715]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 22.72 GB / 39.95 GB
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.58)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/red-snow-r079o9?file=/example.tsx

## Actual Behavior
`block` prop is not respected by `Button` component

## Expected Behavior
Setting `block` prop on `Button` component should make the button to consume the entire width of its parent.

In V0, there was a `fluid` prop does that. And the [migration documentation](https://react.fluentui.dev/?path=/docs/concepts-migration-from-v0-components-button-migration--page#how-to-migrate-props) says we should replace `fluid` with `block`, but `block` is nevertheless taking effect.

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
This is only an issue with the documentation, the `block` prop was deprecated and later removed before the first stable version of `@fluentui/react-components`.
