### ISSUE TITLE
[Bug]: Input in dialog not focusable after closing second dialog

### ISSUE THREAD

**Issue by WanderG** [microsoft/fluentui#27751]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 12.54 GB / 31.85 GB
  Browsers:
    Chrome: 111.0.5563.149
    Edge: Spartan (44.22621.1555.0), Chromium (111.0.1661.44)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @fluentui/react: 8.104.6 => 8.104.6
    @fluentui/react-components: 9.19.1 => 9.19.1
    @fluentui/react-migration-v8-v9: 9.2.1 => 9.2.1
    @fluentui/react-portal-compat: 9.0.45 => 9.0.45
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/dawn-grass-7mxp97?file=/src/index.tsx

### Bug Description

This is something we ran into when upgrading from v8 to v9.
The problem doesn't happen when the dialog is unconctrolled and opened with a dialog trigger, but that is not something we can easily switch to anytime soon. (We use a redux-like system, modals are opened after actions, possibly after an async validation)

The use case is a dialog with a form so the user can insert data. Within the form is a settings button that opens a second dialog with some settings regarding the form.

## Actual Behavior
Within a dialog, open a second dialog. Close the second dialog.
Inputs within the first dialog can no longer be used.

## Expected Behavior
The input should continue to work normally.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
This seems to be very similar to https://github.com/microsoft/fluentui/issues/26824

**Comment by mshoho** [comment]
@bsunderhus this is about how Modalizers work and about the necessity of a proper focus management.

A dialog has Modalizer. The way to activate the modalizer is to programmatically focus something inside it (or focus something outside to deactivate). When we unmount the active modalizer, we end up with no active modalizer.

From the proper focus management perspective once you close the second modal, the focus should be moved to the most recently focused element which is still available. And here it just goes to body because of not being handled (which is generally wrong).

Either there should be a focus call when the modal closes or perhaps there should be Deloser on the trigger.

**Comment by bsunderhus** [comment]
> And here it just goes to body because of not being handled (which is generally wrong).

Not true anymore @mshoho, the focus now goes back to the first trigger, apparently something wrong with the order of focus restorer targets?! Here's an updated example using restorer API https://codesandbox.io/s/sharp-silence-j95sx9?file=/src/index.tsx

**Comment by bsunderhus** [comment]
> Either there should be a focus call when the modal closes or perhaps there should be Deloser on the trigger.

There used to be a deloser in the trigger, now there's a restorer, but apparently we're having some issue focusing on the first modal once the second modal is closed.

**Comment by miroslavstastny** [comment]
@mshoho - is this still valid?

**Comment by mshoho** [comment]
@miroslavstastny In the form it is present in the repro, it's not a bug. To move focus to a mounted modal dialog, there should be a focus call for something inside the dialog. Either manual or using Restorer (which is present on the dialog trigger), and the repro doesn't do it.
