### ISSUE TITLE
[Bug]: react fabric.css has a charset declaration and missing non-ascii characters

### ISSUE THREAD

**Issue by nottagg** [microsoft/fluentui#27778]
### Library

React  / v8 (@fluentui/react)

### System Info

```shell
version 8.102.0
```

### Are you reporting Accessibility issue?

None

### Reproduction

yarn add @fluentui/react

## Actual Behavior
{PROJECT}\node_modules\@fluentui\react\dist\css\fabric.css has the following at the top:
`@charset 'UTF-8';`
The use of single quotes is incorrect per https://developer.mozilla.org/en-US/docs/Web/CSS/@charset

There are also various stylings that don't appear to survive encoding and are simply 

Example classes:
```
.ms-Icon--BulletedListBullet::before {
  content: '';
}

[dir='rtl'] .ms-Icon--BulletedListBullet::before {
  content: '';
}

.ms-Icon--BulletedListBulletMirrored::before {
  content: '';
}

[dir='rtl'] .ms-Icon--BulletedListBulletMirrored::before {
  content: '';
}

.ms-Icon--BulletedList::before {
  content: '';
}
```

## Expected Behavior
There should not be a @charset declaration at all, or it should be the appropriate "UTF-8"
The classes with  should have the appropriate character

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by nottagg** [comment]
Mislabeled - Navigated away and forgot to update the library. This is fluentUI-react v8

**Comment by Hotell** [comment]
one quick repro is checking the css we are shipping on CDN https://unpkg.com/browse/@fluentui/react@8.110.2/dist/css/fabric.css

**Comment by sopranopillow** [comment]
Hey, the issue mentioned above about the v8 website is a known problem in monaco-editor: https://github.com/microsoft/fluentui/issues/19088. @nottagg, would you mind providing a codesandbox with a repro of this issue? Thanks!
