### ISSUE TITLE
Weird symbols

### ISSUE THREAD

**Issue by jcortescruz** [microsoft/fluentui#27777]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Microsoft Edge Enterprise Version 112.0.1722.64 (Official build) (64-bit)

### Describe the issue:

We are using the icons that come in *fabric.min.css* & *fabricmdl2icons-3.70.woff*, however there are occasions when the icons do not display and instead strange symbols are shown. Could you please let me know if there is fix for this issue? or if it could be caused by something foreign to you?

** Btw, this "bug" comes either if we reference the stylesheet from your CDN or from a local folder in our project.

#### Actual behavior:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/132708203/236555031-48fab77c-ac35-409a-bb21-bb3d91486dd8.png">

#### Expected behavior:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/132708203/236554026-aaae217a-2e91-4fcf-ab18-b1705ab1f9d3.png">

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by dom-zhu** [comment]
Also seeing this in my project.. 
![image](https://github.com/microsoft/fluentui/assets/44078427/e2af77e8-fe50-4c04-a05b-7e372bc9bb4f)
![image](https://github.com/microsoft/fluentui/assets/44078427/7eb926bd-ab4a-4b97-bb3d-b1f90b9098d2)

**Comment by Hotell** [comment]
can you provide link to codesandbox as repro ? without repro issues will be closed. thank you

**Comment by dom-zhu** [comment]
This is to do with the file not being interpreted as UTF-8. The fabric.css / fabric.min.css incorrectly set the charset
![image](https://github.com/microsoft/fluentui/assets/44078427/904b2f12-58e1-4026-a188-f1693e1693b7)
1. supposed to use double quotes https://developer.mozilla.org/en-US/docs/Web/CSS/@charset#examples
2. Charset must be the first thing in the file https://www.w3.org/International/questions/qa-css-charset  

see https://github.com/microsoft/fluentui/issues/27778

**Comment by tudorpopams** [comment]
Can you please provide a Codesanbox link so we can better understand the problem?
