### ISSUE TITLE
[Bug]: On the Menu component: Types of property 'children' are incompatible.     Type 'Element[]' is not assignable to type 'Element | [Element, Element]'.

### ISSUE THREAD

**Issue by PauwelsYoran** [microsoft/fluentui#27787]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 18.77 GB / 31.64 GB
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/ttd17t?file=/example.tsx

## Actual Behavior
When trying to create a menu component using the example code i get the following error.
I am creating the component in an spfx webpart, using the latest yeoman generator.
When using eslign to surpress the error the component does render.

Type '{ children: Element[]; }' is not assignable to type '{ children: Element | [Element, Element]; hoverDelay?: number; inline?: boolean; onOpenChange?: (e: MouseEvent | React.MouseEvent<...> | KeyboardEvent<...> | TouchEvent, data: MenuOpenChangeData) => void; ... 6 more ...; closeOnScroll?: boolean; }'.
  Types of property 'children' are incompatible.
    Type 'Element[]' is not assignable to type 'Element | [Element, Element]'.
      Type 'Element[]' is not assignable to type '[Element, Element]'.
        Target requires 2 element(s) but source may have fewer.

## Expected Behavior
This should not happening as this is the example code and should not give an error.

![image](https://user-images.githubusercontent.com/29042267/236791757-15b24829-d551-4ba3-adfa-f1317c87a69d.png)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by tomi-msft** [comment]
Hi @PauwelsYoran , thanks for submitting the issue. I can't seem to be able to repro the issue you've described. Could you provide some more details on the error you're having?

**Comment by jacksonv1lle** [comment]
I think the issue is caused by @types/react: "17.0.45" which is used in the latest SPFx 1.17 package.

You can reproduce the bug by updating the version of the SPFx yeoman generator to the latest.
`@microsoft/generator-sharepoint@1.17.2`

Generate a new SPFx solution with a HelloWorld web part.
Install "@fluentui/react-components": "9.19.1".
Add the FluentUI Menu example code to HelloWorld.tsx
