### ISSUE TITLE
[Bug]: DataGrid cell border style is not as expected with column resizing

### ISSUE THREAD

**Issue by chihiroxc** [microsoft/fluentui#27808]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 13.34 GB / 31.59 GB
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/vigilant-joliot-yuwgnd?file=/example.tsx

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/71873562/12af23a7-813c-4fe8-a8dc-01ca484a0dfd)
The right border is out of the row element and there is a horizontal scroll bar.

## Expected Behavior
![image](https://github.com/microsoft/fluentui/assets/71873562/81565258-8550-436c-85bd-d296a96f0189)
This is the behavior without column resizing.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
Closing as duplicate of #27570
