### ISSUE TITLE
[Bug]: SplitButton does not render `:active` styles when pressed in Chrome/Edge

### ISSUE THREAD

**Issue by kycutler** [microsoft/fluentui#27801]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/button

## Actual Behavior
Clicking in a SplitButton does not trigger the "active" styles:
![c8ea0d87-c2b8-4563-8e11-38d3a91db574](https://github.com/microsoft/fluentui/assets/67761731/bc027780-6c3c-4c3e-8eba-bbef1796befd)

## Expected Behavior
The button should show "active" styles, like a normal button does:
![6b75034e-2de6-49c8-9353-567bd8ccd7fe](https://github.com/microsoft/fluentui/assets/67761731/4004da80-bdb3-4119-ab21-e9eb778ccd29)

It works as expected in Firefox, but not in Chrome / Edge.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by tomi-msft** [comment]
Hi @kycutler, thanks for submitting the issue. I am unable to repro this in my browser. Could you try updating your browser version and see if that fixes it?

**Comment by kycutler** [comment]
Hi @tomi-msft -- I updated to the latest Edge (Version 113.0.1774.42 on Windows 11) and the issue still repros for me. To be clear, I am just referring to the "pressed" state of the split button -- hovering works fine, but the pressed / active state is not triggered on mouse down like it is with a normal button.
