### ISSUE TITLE
[Bug]: Rating component focus shouldn't set the rating

### ISSUE THREAD

**Issue by joshualamusga1** [microsoft/fluentui#27818]
### Library

React / v8 (@fluentui/react)

### Are you reporting Accessibility issue?

None

## Actual Behavior
Rating is set on focusing the component

The rating control has functioned this way through several versions. In a nutshell, setting focus and arrowkey navigation in the control both change the rating control value. Both are unexpected side effects, but the side effect on focus is much harder to avoid because tabbing past the control sets the value to 1 star, affecting real world scenarios like an optional rating on a submit form. I'm experiencing that scenario now.

Suggested fix: If the component receives focus from outside itself and it wasn't via mouse click, read out the rating (ARIA) instead of setting it. Show something like a focus rectangle around the control to indicate it has focus. In this state, pressing right arrowkey should set to 1 star filled. This avoids having to update the design to include hollow stars, and preserves normal user interaction. It only affects focus change to prevent unintentionally setting a rating by tabbing beyond the control.

Alternative fix: This is a harder fix affecting design and interaction. Remove all side effects from navigation by focus/hover/arrowkeys; a rating is only set by click/touch, space, and enter keypress. A hover effect is used to indicate responsiveness; use the same blue tinting that the Rating control uses for hovering over stars with the mouse, except use it across all stars from the first to the one the user is focused/hovered over.

## Expected Behavior
Rating should not change value when it receives focus

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
next time when creating issue please make sure to provide repro, otherwise issue will be marked as needs repro and closed without resolving it.


here's the repro:

```tsx
      <Rating
        max={5}
        allowZeroStars
        size={RatingSize.Large}
        ariaLabel="Large stars"
        ariaLabelFormat="{0} of {1} stars"
      />
```

**Comment by tomi-msft** [comment]
I think this [PR](#28303 ) will fix this issue
