### ISSUE TITLE
[Feature]: Add Toolbar Groups to Align FAST Toolbar with Fluent Spec

### ISSUE THREAD

**Issue by halerankin** [microsoft/fluentui#27812]
### Library

Web Components (@fluentui/web-components)

### Describe the feature that you would like added

[Fluent Toolbar Spec](https://www.figma.com/file/QfHyx6ApwFEcw5q4pM9CSZ/Toolbar?type=design&node-id=2367-15986&t=YlkuePnvKRzXDKZj-4) shows toolbar tab grouping: 

![image](https://github.com/microsoft/fluentui/assets/12279161/481e78b8-646d-454c-b3f8-59730aaeea74)

Implementing a focusable wrapping element to contain toolbar items would allow functionality to be broken out into distinct groups, separated by vertical dividers. Each tab group or toolbar group would be accessible via keyboard. 

This would go a long way to improving the parsing of toolbar actions into discrete chunks for an accessibilility user.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chrisdholt** [comment]
> Implementing a focusable wrapping element to contain toolbar items would allow functionality to be broken out into distinct groups, separated by vertical dividers. Each tab group or toolbar group would be accessible via keyboard.
>
>This would go a long way to improving the parsing of toolbar actions into discrete chunks for an accessibilility user.

IMO this seems like an implementation detail - without digging into the design spec, I'd like to understand _how_ this helps/supports AT users and how parity does not currently exist within the current toolbar. The toolbar currently supports the expected Keyboarding behavior for Toolbars as described by the APG and has affordances specific to when radio-groups are present, text fields, etc...

Here's the APG guidance which [details the toolbar as a single tab-stop](https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/). I'm curious what the accessible *role* is for each tab grouping that's been proposed and then likewise what the role is for the toolbar if not "toolbar" and mapping to the suggested pattern?

**Comment by halerankin** [comment]
> > Implementing a focusable wrapping element to contain toolbar items would allow functionality to be broken out into distinct groups, separated by vertical dividers. Each tab group or toolbar group would be accessible via keyboard.
> > This would go a long way to improving the parsing of toolbar actions into discrete chunks for an accessibilility user.
> 
> IMO this seems like an implementation detail - without digging into the design spec, I'd like to understand _how_ this helps/supports AT users and how parity does not currently exist within the current toolbar. The toolbar currently supports the expected Keyboarding behavior for Toolbars as described by the APG and has affordances specific to when radio-groups are present, text fields, etc...
> 
> Here's the APG guidance which [details the toolbar as a single tab-stop](https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/). I'm curious what the accessible _role_ is for each tab grouping that's been proposed and then likewise what the role is for the toolbar if not "toolbar" and mapping to the suggested pattern?

This is not about what the FAST Toolbar isn't doing; it is in fact in parity with the APG. When I saw that the Fluent Toolbar Spec showed multiple tab stops within the toolbar, I thought it should be implemented. If having a single tab stop is what we want, then there is no additional work to be done here.

**Comment by chrisdholt** [comment]
> > > Implementing a focusable wrapping element to contain toolbar items would allow functionality to be broken out into distinct groups, separated by vertical dividers. Each tab group or toolbar group would be accessible via keyboard.
> > > This would go a long way to improving the parsing of toolbar actions into discrete chunks for an accessibilility user.
> > 
> > 
> > IMO this seems like an implementation detail - without digging into the design spec, I'd like to understand _how_ this helps/supports AT users and how parity does not currently exist within the current toolbar. The toolbar currently supports the expected Keyboarding behavior for Toolbars as described by the APG and has affordances specific to when radio-groups are present, text fields, etc...
> > Here's the APG guidance which [details the toolbar as a single tab-stop](https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/). I'm curious what the accessible _role_ is for each tab grouping that's been proposed and then likewise what the role is for the toolbar if not "toolbar" and mapping to the suggested pattern?
> 
> This is not about what the FAST Toolbar isn't doing; it is in fact in parity with the APG. When I saw that the Fluent Toolbar Spec showed multiple tab stops within the toolbar, I thought it should be implemented. If having a single tab stop is what we want, then there is no additional work to be done here.

I think I'd like to better understand the decision here so we can identify if parity is preferred and what the implications are. There were likely "reasons" here, but I don't see them aligning with the current guidance around toolbars.

**Comment by halerankin** [comment]
I can reach out to the design team to learn more about their reasoning behind this. Might be helpful to know whether or not they added this as a "nice-to-have" without tracking down the APG for toolbar.
