### ISSUE TITLE
[Bug]: TextArea rows not working

### ISSUE THREAD

**Issue by Senadtm87** [microsoft/fluentui#27842]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
NA
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/nameless-meadow-cwkc6x?file=/example.tsx:48-74

### Bug Description

Settings rows in Textarea does not increase element size.
Workaround can be done by setting  textarea={{style:{height:"auto"}}} 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Ogglas** [comment]
Any update on this? Probably related issues and PR: https://github.com/microsoft/fast/issues/3869 https://github.com/microsoft/fast/pull/5856 https://github.com/microsoft/fluentui-blazor/issues/72

**Comment by Hotell** [comment]
@Ogglas its not related to fast, this issue is for react implementation of fluent not web-components

**Comment by Hotell** [comment]
`rows` being present in the API might be a bug on our side as it probably doesn't do anything. cc @sopranopillow
