### ISSUE TITLE
[Bug]: @fluentui/react-field not installable

### ISSUE THREAD

**Issue by trickreich** [microsoft/fluentui#27841]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
it looks like @fluentui/react-field is private package now?
```

### Are you reporting Accessibility issue?

None

### Reproduction

try install

## Actual Behavior
fill this out

## Expected Behavior
fill this out

### Logs

```shell
 ERR_PNPM_FETCH_503  GET https://registry.npmjs.org/@fluentui%2Freact-field: Service Unavailable - 503
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@trickreich, i'm unable to repro the issue. I installed the latest version (9.1.2) of `@fluentui/react-field` on a fresh react app via `npm` and `yarn` and both installed as expected. It's possible that when you tried to do so, npm had a temporary outage so i'd advise to try again.

**Comment by trickreich** [comment]
is working now again
