### ISSUE TITLE
[Bug]: [TextField]Cursor jumps to the next line in Edge and when auto autocompleted on

### ISSUE THREAD

**Issue by nancyz1031** [microsoft/fluentui#27879]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System: Windows 10
Library: @fluentui/react 7
Browser: Edge
```

### Are you reporting Accessibility issue?

no

### Reproduction

open https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield in Edge, and turn on auto autocompleted, type something in Multiline TextField

## Actual Behavior
typing in Multiline TextField, when auto complete the sentence, cursor jumps to the next line, please check the .gif

## Expected Behavior
what I am typing should always be visible
![cursor jump](https://github.com/microsoft/fluentui/assets/29285878/bae929b4-5160-44b7-b46e-a43d32c5225e)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
hmm this might be quite tricky, dunno what kind of browser feature/plugin are you using to get that tab autocompletion, meaning it will matter how that thing inserts the content within the control. it might be out of our control to actually support this feature for every kind of plugin if it's not done via some standard DOM api value injection or event being triggered.
