### ISSUE TITLE
[Bug]: DataGrid single and multiple select controlled not work

### ISSUE THREAD

**Issue by slobber** [microsoft/fluentui#27896]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 40.11 GB / 63.68 GB
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-datagrid--default#single-select-controlled

### Bug Description

The samples in official doc site (https://react.fluentui.dev/?path=/docs/components-datagrid--default#single-select-controlled, https://react.fluentui.dev/?path=/docs/components-datagrid--default#multiple-select-controlled) have the bug.

## Actual Behavior
Click one row, the selection not change, and not fire selectionChange event.

## Expected Behavior
Click one row, selectionChange event is not fired, and onSelectionChange handler is not called.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by yethee** [comment]
Seems, this issue related to #27702. Hook `useControllableState` returns the noop function for the set action when state is controlled.

**Comment by layershifter** [comment]
@slobber thanks for reporting 👍 @yethee you're correct, I created a PR to revert it and added a new test to cover that scenario (see #27978) 👍

**Comment by slobber** [comment]
v9.20.3

single select controlled worked, but multiple select controlled still doesn't work.

https://react.fluentui.dev/?path=/docs/components-datagrid--default#multiple-select-controlled
