### ISSUE TITLE
WeakMap holding react pane in memory

### ISSUE THREAD

**Issue by msrohit** [microsoft/fluentui#27904]
We see memory leaks from key value pairs in weakMap holding the react pane. The only explanation we found is that the weak map has a strong reference inside it

original bug  - [Bug 3062098](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/3062098): Detected high memory usage. RWS: 1207.50 MB, #JSH: 767.12 MB

transferring to FluentUI folks as discussed below with memory team after investigation. Channel thread linked below for more details if needed.

![image](https://github.com/microsoft/fluentui/assets/100732869/f59c8a2d-3bfc-4218-9728-14d6200a689c)

more details here

[Jan Dolezel: Looking at contents of the weakmap, looks like it is https://github.c...](https://teams.microsoft.com/l/message/19:ec4abf0e9b9d4e9e98ca5e39b2d5c99d@thread.skype/1684246735595?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=af55e84c-dc67-4e48-9005-86e0b07272f9&parentMessageId=1683664446357&teamName=Microsoft%20Teams&channelName=Memory&createdTime=1684246735595)
posted in Microsoft Teams / Memory on Tuesday, May 16, 2023 7:18 AM

**Comment by khmakoto** [comment]
This should have been solved by #28080.
