### ISSUE TITLE
[Bug]: display issues for slot props in Storybook

### ISSUE THREAD

**Issue by davidtong** [microsoft/fluentui#27908]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
https://react.fluentui.dev/?path=/docs/components-dropdown--default
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-dropdown--default

## Actual Behavior
<img width="1303" alt="Screen Shot 2023-05-18 at 11 00 43 PM" src="https://github.com/microsoft/fluentui/assets/583962/60717cfb-3f6a-4c43-904d-5fe8a746acb7">
The first 4 props aren't correctly formatted. For example, it is unclear whether the prop `expandIcon` is a boolean or an actual React element.

## Expected Behavior
The 4 props shown in the screenshot should be written in English sentences.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
FYI It's a general issue and happens for other components, too.

**Comment by Hotell** [comment]
as @layershifter mentioned , unless react-docgen improves generation of complicated interfaces or we will implement a custom storybook plugin I don't think there is much to do on our side.

**Comment by layershifter** [comment]
keep open
