### ISSUE TITLE
[Bug]: DatePicker does not respect passed in styles for readOnlyTextField

### ISSUE THREAD

**Issue by cabillin** [microsoft/fluentui#27926]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 2.92 GB / 15.60 GB
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/KnetTravlr/pen/bGmQKOB

## Actual Behavior
styles passed in under the readOnlyTextField key have no affect

## Expected Behavior
styles passed in under the readOnlyTextField key take affect on the displayed date value

### Requested priority

Normal

### Products/sites affected

Mission Control (internal Microsoft web site)

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
after quick debugging it looks like that styles for those are overiden by higher specificity css styles defined within the component

<img width="1153" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/b88af4eb-6b91-4c53-b7b2-092868c95341">
