### ISSUE TITLE
[Feature]: migrate from internal `bundle-size` to OSS `monosize`

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#27934]
### Library

- React Components / v9 (@fluentui/react-components)
- React / v8 (@fluentui/react)

### Describe the feature that you would like added

We are using `bundle-size` tool which source etc lives within fluent. In the meantime it was "forked" and open sourced as `monosize` https://github.com/microsoft/monosize tool.

For better maintenance, consistency and support we will migrate to use monosize only.

### Have you discussed this feature with our team

@microsoft/fluentui-react-build @layershifter 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by layershifter** [comment]
@Hotell  AFAIR Node 16 can run it, Node 18 is required only for one of storage adapters to use native fetch.
