### ISSUE TITLE
Usage of Alert/Sekeleton use in Production

### ISSUE THREAD

**Issue by StefanH114** [microsoft/fluentui#27949]
We plan to use the Alert and Skeleton component in our product.
As you mention on your documentation of Fluent UI v9 we would like to reach out to you and as when do you plan to move these components to a stable version? Are there any major changes to the component in planning?
as I don't know how to contact you in any other way I opened this issue.
If this is the wrong place please close

**Comment by layershifter** [comment]
@StefanH114 please consider to use Github Discussions for questions 🙏 

- `Skeleton` is stable #27767, I created a PR to move it to a proper section (#27959), thanks for heads up 👍 
- `Alert` will be deprecated in favour of `Toast` & `MessageBar` components. `Toast` is WIP right now, @ling1726 is it accurate?

**Comment by layershifter** [comment]
> So did I get it right, that we have no stable alternative for alerts in the near future in fluent UI v9?

Not yet. I suggest to follow #22579.

**Comment by StefanH114** [comment]
@layershifter okay, thanks for the reply
