### ISSUE TITLE
[Bug]: Update color of colorPaletteRedForeground1 to black in Teams HC theme

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#27952]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
all systems in the world
```

### Are you reporting Accessibility issue?

yes

### Reproduction

Teams

### Bug Description

HC theme is only used in Teams

However, Teams also overrides the value of the colorPaletteRedForeground1 token to black, making it hard to understand.

colorPaletteRedForeground1 should be changed to black in HC theme.

### Requested priority

High

### Products/sites affected

Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
What is in the library is correct, the discrepancy should be fixed on product side.
