### ISSUE TITLE
[Docs]: Add an example of Dialog usage without DialogTrigger

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#27962]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

- `DialogTrigger` manages focus handling (restoration) when a `Dialog` gets closed
- `Dialog` can be used without triggers
- We need a documentation example for that case (#27914)

### Have you discussed this feature with our team

N/A

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by miroslavstastny** [comment]
(Trigger outside dialog)[https://react.fluentui.dev/?path=/docs/components-dialog--default#trigger-outside-dialog] is a good storybook example but after closing the dialog the focus goes the body.
It should go back to trigger and it should also be explicitly documented.
