### ISSUE TITLE
[Docs]: add docs of usage for @fluenui/react-tabster

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/fluentui#27961]
### Discussed in https://github.com/microsoft/fluentui/discussions/27883

<div type='discussions-op-text'>

<sup>Originally posted by **AkiraVoid** May 17, 2023</sup>

 the docs of @fluenui/react-tabster should be improved in case the users don't know how to use it.

**Comment by miroslavstastny** [comment]
Docs for `react-tabster` hooks. There is a separate issue for Migration guide from focus-zone.
