### ISSUE TITLE
[Bug]: v9 Table does not resize when 'aside' string is passed

### ISSUE THREAD

**Issue by pradeept95** [microsoft/fluentui#27970]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
NA
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/xenodochial-tree-qoxtz7?file=/example.tsx

## Actual Behavior
Column Resize is not allowed if the `aside` prop is set to TableHeaderCell.

## Expected Behavior
Should be able to resize column even if `aside` passe to the TableHeaderCell.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
It looks like the aside slot is used for the resizing element, so passing in a custom string replaces the resize handle. I'll have the author look at this to see how he'd suggest customizing the aside slot.
