### ISSUE TITLE
[Bug]: Dialog buttons get larger when width is less than 480px

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#27991]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 19.18 GB / 62.66 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 104.0
```

### Are you reporting Accessibility issue?

no

### Reproduction

Default example in the docsite

## Actual Behavior

![image](https://github.com/microsoft/fluentui/assets/5953191/e4dfbafb-f0e6-457c-9ad4-70bb0838b529)

## Expected Behavior

Buttons shouldn't take more space than what the text needs.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
the buttons are placed in columns 2 and 3, which is probably okay except that they are also justify stretch. curious what the figmas prescribe here

![image](https://github.com/microsoft/fluentui/assets/1434956/8b23335b-3cf9-42a4-ba55-e82decc2566b)

**Comment by bsunderhus** [comment]
It should stretch all the way through all the columns, good catch! I'll investigate, this bug probably appeared after modifications on the grid structure for the `DialogSurface`
