### ISSUE TITLE
[Bug]: no code sample in fluent2 docs

### ISSUE THREAD

**Issue by pelikhan** [microsoft/fluentui#27992]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
edge latest
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://fluent2.microsoft.design/components/web/react/divider/code

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/4175913/39583f40-ef70-428a-9e20-2f8b9d612f25)

## Expected Behavior
code sample

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
As I see none of pages contains code snippets for components, only "Open In CodeSandbox" link is present. So this looks more like a feature, @tudorpopams can you please check this one?

**Comment by tudorpopams** [comment]
> As I see none of pages contains code snippets for components, only "Open In CodeSandbox" link is present. So this looks more like a feature, @tudorpopams can you please check this one?

That's right, none of the code tabs show actual code other than linking to CodeSandbox and the Storybook resource itself. We are planning to add code examples to the website, but I can't give you an estimate for when will that happen right now.

@pelikhan please refer to the Storybook link (right under the component demo) for code examples.
