### ISSUE TITLE
[Bug]: Using a non-html element in `as` props of ThemeProvider cause useFocusRect to crash

### ISSUE THREAD

**Issue by weichensw** [microsoft/fluentui#28016]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
npx: installed 1 in 2.252s

  System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 23.51 GB / 31.72 GB
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/xbtsw/pen/bGmJeod

## Actual Behavior
useFocusRect will crash because it attempt to call `addEventListener` on a non-HTML element.

## Expected Behavior
The focus rect should be on the window object, as per design.

A screenshot to assist with understanding (this is not from the minimal repro as that stack is minified)
![image](https://github.com/microsoft/fluentui/assets/4098537/dc24c208-adf5-4936-a727-09b57c529f2b)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Yeah, i believe this is intentional. The as prop is typically used to change the DOM element rendered at the root (span or section etc)

It was never expected to take any functional component. I'll update the prop description.

**Comment by micahgodbolt** [comment]
I dug in and it looks like it broke at 8.84.0, while it works in 8.83.1

https://codepen.io/micahgodbolt/pen/ZEmQGNO?editors=1011

I don't see anything obvious in the change logs. 

```md
## [8.84.0](https://github.com/microsoft/fluentui/tree/@fluentui/react_v8.84.0)

Tue, 26 Jul 2022 07:39:34 GMT 
[Compare changes](https://github.com/microsoft/fluentui/compare/@fluentui/react_v8.83.1..@fluentui/react_v8.84.0)

### Minor changes

- fix: Scope focus visible classnames and event listeners to ThemeProvider by default, and to the window body as a fallback. ([PR #24025](https://github.com/microsoft/fluentui/pull/24025) by Humberto.Morimoto@microsoft.com)
- Bump @fluentui/foundation-legacy to v8.2.11 ([PR #24068](https://github.com/microsoft/fluentui/pull/24068) by beachball)
- Bump @fluentui/font-icons-mdl2 to v8.4.4 ([PR #24068](https://github.com/microsoft/fluentui/pull/24068) by beachball)
- Bump @fluentui/react-focus to v8.7.4 ([PR #24068](https://github.com/microsoft/fluentui/pull/24068) by beachball)
- Bump @fluentui/react-hooks to v8.6.2 ([PR #24068](https://github.com/microsoft/fluentui/pull/24068) by beachball)
- Bump @fluentui/style-utilities to v8.7.3 ([PR #24068](https://github.com/microsoft/fluentui/pull/24068) by beachball)
- Bump @fluentui/theme to v2.6.8 ([PR #24068](https://github.com/microsoft/fluentui/pull/24068) by beachball)
- Bump @fluentui/utilities to v8.10.0 ([PR #24068](https://github.com/microsoft/fluentui/pull/24068) by beachball)
- Bump @fluentui/common-styles to v1.1.3 ([PR #24068](https://github.com/microsoft/fluentui/pull/24068) by beachball)
```

The bump in theme appears to just update to the latest utilities. Looking into the utils change.
