### ISSUE TITLE
[Bug]: NormalPeoplePicker auto selects the user on page scroll

### ISSUE THREAD

**Issue by harshika-kashyap** [microsoft/fluentui#28034]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 3.09 GB / 15.75 GB
Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/harshika123/pen/PoyvbgB

https://github.com/microsoft/fluentui/assets/26279056/65d23de2-87b9-473d-9449-0a0a3bb01339

## Actual Behavior
NormalPeoplePicker auto selects the user on page scroll

## Expected Behavior
NormalPeoplePicker should not auto select the user on page scroll

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
This is actually a bit intentional. The expected behavior is: if you move focus to an item in the list, and then you move focus out of the dropdown, the selection goes into the input. It behaves like a combobox. I don't believe we are going to change this behavior.
