### ISSUE TITLE
[Feature]: focusAsync counterpart in @fluentui/react-components

### ISSUE THREAD

**Issue by sjwilczynski** [microsoft/fluentui#28030]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Fluent 8 has [focusAsync utility](https://github.com/microsoft/fluentui/blob/e95ec0fee21e2ceb113d0678520d2bf6084b1495/packages/utilities/src/focus.ts#LL488C17-L488C27). However, there is no counterpart for it in Fluent 9. It would be great if we had similar utility. With tabster it's possible just by reusing [Observed API](https://tabster.io/docs/observed#requestfocus), with additional feature of being able to focus element which have not yet apperead in DOM. I was thinking about something like:

```ts
import { useTabsterAttributes } from "@fluentui/react-tabster";
import { createTabster, getObservedElement } from "tabster";
import type { Types } from "tabster";

export const useFocusElement = (
  name: string,
  timeout = 1000
): {
  attributes: Types.TabsterDOMAttribute;
  focus: () => Types.ObservedElementAsyncRequest<boolean>;
} => {
  const attributes = useTabsterAttributes({ observed: { names: [name] } });

  const tabsterCore = createTabster(window); // if this was part of @fluentui/react-tabster, we could call useTabter here instead

  const observedElement = getObservedElement(tabsterCore);
  return {
    attributes,
    focus: () => observedElement.requestFocus(name, timeout),
  };
};
```

What do you think?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by micahgodbolt** [comment]
@ling1726 what are your thoughts on this? Is this a good use for tabster?

**Comment by ling1726** [comment]
Yeah, this is a feature request, to add observable focusing to react-tabster from the main tabster package
