### ISSUE TITLE
[Bug]: Panel content visible behind footer when modified via internal state

### ISSUE THREAD

**Issue by lubeeman** [microsoft/fluentui#28057]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 14.38 GB / 31.85 GB
  Browsers:
    Chrome: 113.0.5672.127
    Edge: Spartan (44.22621.1825.0), Chromium (113.0.1774.57), ChromiumDev (115.0.1866.1)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/lubeeman/pen/LYgXerO

## Actual Behavior
When additional content appears in a Panel (e.g. expanding a collapsible element) and increases the content height after the initial render so that a scrollbar is now required, the content is visible behind the panel footer. It's only when the window is resized that the panel recalculates and adds a background color and top border to the panel footer.
![image](https://github.com/microsoft/fluentui/assets/102998701/5bc06e17-cd54-4c48-b2bd-3a76e4cb6daf)

## Expected Behavior
The panel content should never be visible behind the panel footer.

### Requested priority

Normal

### Products/sites affected

SharePoint

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Yeah, there is a calculation done when the panel is rendered to see if the content fits. Unfortunately there are no listeners for changing content to see if the content has moved far enough down to need to change.

One simple approach would be to fore a re-render the component anytime the content changes.
