### ISSUE TITLE
[Bug]: Api extractor output does not match ci

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#28084]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 51.01 GB / 62.66 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 104.0
```

### Are you reporting Accessibility issue?

no

### Reproduction

Cloning the repo and running yarn buildci gives a bunch of api changes.

## Actual Behavior

Getting many api changes: 
![image](https://github.com/microsoft/fluentui/assets/5953191/05ce0691-cdad-4540-8b54-a4b78319851f)

After talking to @TristanWatanabe, he mentioned this is due to a recent PR https://github.com/microsoft/fluentui/pull/27936 that bumps api-extractor. This bump included this change:

![image](https://github.com/microsoft/fluentui/assets/5953191/41041625-c597-40ae-9655-35d6bb570b54)

therefore our current way of dealing with path aliases is not working correctly:

![image](https://github.com/microsoft/fluentui/assets/5953191/5d8e97fb-b603-475c-afa6-a95e07393b0d)

From this, we get a removal of the following due to the api extractor not giving the same output as ci (also the local output is wrong)

![image](https://github.com/microsoft/fluentui/assets/5953191/89353437-d573-4c07-b623-963a660c160c)

## Expected Behavior
CI and local api extractor should provide the same output.

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
For extra context, I believe this was the PR introduced in api-extractor version `7.21.0` that changed the behavior with how TS path aliases are handled: https://github.com/microsoft/rushstack/pull/3321
