### ISSUE TITLE
[Bug]: Coachmark does not update position when another component changes layout

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#28102]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 42.89 GB / 62.66 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 104.0
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/quirky-snowflake-11ks56?file=/src/index.tsx

## Actual Behavior
The target is the Toggle, but it stays where it was initially rendered.

![image](https://github.com/microsoft/fluentui/assets/5953191/3e125f40-6dda-4c48-a747-fee0810d6df5)

## Expected Behavior

Coachmark should update its position to be where the toggle is.

### Requested priority

Low

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Resizing the window will correctly re-position the `Coachmark` so I think the missing piece is that the `Coachmark` needs to track whether its target has moved. Neither `MutationObserver` nor `ResizeObserver` seem to support tracking this information. In order to update the `Coachmark` in situations like this I think we'll need to poll its position which is an expensive proposition.

**Comment by sopranopillow** [comment]
> Resizing the window will correctly re-position the `Coachmark` so I think the missing piece is that the `Coachmark` needs to track whether its target has moved. Neither `MutationObserver` nor `ResizeObserver` seem to support tracking this information. In order to update the `Coachmark` in situations like this I think we'll need to poll its position which is an expensive proposition.

Hmmm this might not be worth the perf hit. The person asking for this change hasn't pinged anymore, so I'll adjust priority.
