### ISSUE TITLE
[Bug]: Missing chevron icon from <MenuButton> if children is empty

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#28117]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
(Using CodeSandbox)
  "dependencies": {
    "@fluentui/react-components": "9.18.6",
    "@fluentui/react-icons": "2.0.199",
    "react": "^17",
    "react-dom": "^17",
    "react-scripts": "latest"
  },
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/fluent-ui-v9-menubutton-without-children-1eezpp?file=/example.tsx

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/50703224/792747a7-467d-43a6-99e4-a2b2bdaf98d3)

## Expected Behavior
I expect to see the chevron icon even if the button has no label -- otherwise, what is the difference this component make, compared to `<Button>` component?

Background: I'm using `<MenuButton>` on `<Toolbar>` becuase there is currently no such component like `<ToolbarMenuButton>`.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
This is 100% intentional. If it's just an icon then it doesn't need to have a chevron. It'd look funny to have both icons.

https://react.fluentui.dev/?path=/docs/components-button-menubutton--default#icon

**Comment by chenxinyanc** [comment]
> This is 100% intentional. If it's just an icon then it doesn't need to have a chevron. 

Okay I'm expecting this. @micahgodbolt But does this applies even if I'm specifying the `menuIcon` *explicitly*? Note that I'm explicitly specifying this property in the last `MenuButton`:

```tsx
<Menu>
  <MenuTrigger disableButtonEnhancement>
    <Tooltip
      content="With calendar icon and no contents"
      relationship="label"
    >
      <MenuButton
        icon={<CalendarMonthRegular />}
        menuIcon={<FilterRegular />}
      />
    </Tooltip>
  </MenuTrigger>
  <MenuPopover>
    <MenuList>
      <MenuItem>Item a</MenuItem>
      <MenuItem>Item b</MenuItem>
    </MenuList>
  </MenuPopover>
</Menu>
```

However, the icon I've specified is removed, nevertheless.

As I've mentioned, I'm adding this button to the `<Toolbar>` component. Regretfully, there is no such thing like `<ToolbarMenuButton>`, so I'll have to use `<MenuButton>` instead. What I'm trying to achieve is something like this

![image](https://github.com/microsoft/fluentui/assets/50703224/c9b85738-c235-48c6-94a1-50a881618e4a)

or this

![image](https://github.com/microsoft/fluentui/assets/50703224/d0ea794e-06ae-4908-9b52-94a67ec2c08c)

**Comment by khmakoto** [comment]
@chenxinyanc the workaround if you want both an icon and the down chevron to be shown is to pass the icon not to the `icon` slot, but as a child of the `MenuButton` and modify its styles. You can see this achieved in [this codesandbox](https://codesandbox.io/s/menubutton-with-icon-and-menuicon-gxm0kh?file=/example.tsx).
