### ISSUE TITLE
[Bug]: Callout does not reposition

### ISSUE THREAD

**Issue by aftab-hassan** [microsoft/fluentui#28122]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 45.35 GB / 63.79 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

Repro for both v7 and v8 below

### Bug Description

Callout's positioning logic does not reposition Callout correctly. 

Works in Fluentui-7 - Try selecting one of the other DirectionalHints from the Dropdown and you would notice it repositios correctly.
https://codepen.io/afhassan_microsoft/pen/RweXMLj?editors=1010

Does not work in Fluentui-8 - Selecting another DirectionalHint from the Dropdown does not rerender/reposition Callout
https://codepen.io/afhassan_microsoft/pen/xxyvWXO

Possibly related to 
[return shallowCompare(previousProps, nextProps);](https://github.com/microsoft/fluentui/blob/0868df85405025c1488c8b0f8285ead56c379626/packages/react/src/components/Callout/CalloutContent.base.tsx#LL545C1-L546C1) in v8 versus
[return !shallowCompare(this.props, newProps) || !shallowCompare(this.state, newState);](https://github.com/microsoft/fluentui/blob/bcb8832dacb593d38e678567321411852482b1fb/packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx#LL127C5-L127C91) in v7

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
It does not reposition in that demo showcase (probably reason why it hides after click on that position select-box. 

not sure if this behaviour is "works as expected" or indeed a bug.

**Comment by aftab-hassan** [comment]
@Hotell thanks for taking a look!
It does break a few scenarios after we moved to fluent-ui 8 such as these:

Before:
![image](https://github.com/microsoft/fluentui/assets/8922176/a6d1d089-d0ad-489f-8ee7-da56f55e5fce)

After:
![image](https://github.com/microsoft/fluentui/assets/8922176/56856dd6-2379-4505-ab5d-016de343223f)

**Comment by marielsgtzz** [comment]
I'm also seeing some issues with the callout positioning. When the user filters and the list shortens the size of the callout also resizes (which is expected) but then it is placed on the edge of the screen instead than next to the button that triggers the callout.

**Comment by marielsgtzz** [comment]
An example of what is happening is also visible in [this other](https://github.com/microsoft/fluentui/issues/24912#issuecomment-1869246598) ticket #24912
