### ISSUE TITLE
[Bug]: Menu Item has fixed height, causing text to fall out if it's split in two lines

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#28153]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
any system
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/dank-wave-4ltcei

### Bug Description

<img width="324" alt="image" src="https://github.com/microsoft/fluentui/assets/13742664/03ec0d29-c16d-4a30-b8de-9300ca6e4fa1">

### Requested priority

Normal

### Products/sites affected

Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
This does not repro anymore, leaving closed.
