### ISSUE TITLE
[TextField] placeholder icon is rendered when iconName is undefined

### ISSUE THREAD

**Issue by fildahui** [microsoft/fluentui#28164]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 6.89 GB / 31.68 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/mm6jz742xy

## Actual Behavior
When the `iconProps` prop is set on the textfield but the `iconName` value is undefined it renders a placeholder icon (noticeable if you use `type="password"` and enable the reveal button), like the following

```
<TextField 
  type="password" 
  canRevealPassword
  iconProps={{
    iconName: undefined
  }}
/>
```

According to the IIconProps interface, it should render a placeholder icon only when iconName is an **empty string**.

## Expected Behavior
When iconName is null or undefined it should not render a placeholder icon.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
IMO this works as expected, under the hood the native `input` is set to `type` password - and browser UI renders that reveal button.

**Comment by fildahui** [comment]
No sorry, you did not understand the issue, It's not the reveal button the problem, that is rendered correctly. the issue is that a blank space is rendered next to it when the iconName prop is undefined (first pic), and it should not be rendered IMO.

if the iconProps object is undefined, then no placeholder is rendered (see second pic) but that behaviour should be the same anyway when iconName is undefined/null:

![image](https://github.com/microsoft/fluentui/assets/17295499/022cf0e4-ba0e-4457-8058-501741f132b0)

![image](https://github.com/microsoft/fluentui/assets/17295499/432cf48b-acc1-4e21-b0c9-923c69e321a9)
