### ISSUE TITLE
[Feature]: Add theme palette colors to ThemeContext 

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#28178]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

The current ThemeContext_unstable contains all of the tokens and values used in the theme, but it does not have the actual 16 palette colors. 

Having access to the original 16 colors would 1) ensure that developers could find the brand/80 and 2) they would have access to colors not already assigned to semantic tokens. 

There is another conversation about if those 16 colors should be included as CSS variables, but if we at least include them in context, then any app team could access them and create variables of their own with those values.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by miroslavstastny** [comment]
If I understand it correctly you mean the brand ramp. We intentionally omit the global colors because those are not safe to be used in styles as they do not change between light and dark theme.
Could you please elaborate more on your use case?
