### ISSUE TITLE
[Feature]: for DetailsList please add pagination and filtering on column header

### ISSUE THREAD

**Issue by saimanepalli** [microsoft/fluentui#28189]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### Describe the feature that you would like added

DetailsList please add pagination and filtering on column header

### Have you discussed this feature with our team

No

### Additional context

DetailsList please add pagination and filtering on column header

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Hotell** [comment]
not sure if this is your feature request if for the correct library as react-northstar has no DetailList component ?

can you please provide link to repro using component you're referring to ? ty
