### ISSUE TITLE
[Bug]: DetailsList OnItemContextMenu is invoked for empty Groups & Group Headers

### ISSUE THREAD

**Issue by irah2008** [microsoft/fluentui#28193]
### Library

React v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 3.13 GB / 15.70 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (114.0.1823.41)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/irah2008/pen/NWEqoqJ

## Actual Behavior
OnItemContextMenu is triggered for Empty groups and Group Headers

## Expected Behavior
OnItemContextMenu should not be invoked for Empty Groups & Group Headers as there are no item element associated with them

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
this is clearly a mistake as the repro and description is for `@fluentui/react` library

**Comment by Hotell** [comment]
not sure if this is a bug or works as expected, I don't have proper context for this component, lets see what folks from @microsfot/cxe-red can share with us
