### ISSUE TITLE
[Feature]: support Next.js 13 appDir

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/fluentui#28196]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

As I described in #27227 , Next.js appDir used Server Component feature from React 18. In the time #27227 was made, @layershifter told me that Server Component is an experimental feature which means it could have some breaking changes in the future. But for now, as Next.js 13 has already announced that appDir is stable, Fluent UI should support this framework which may be used by a significant part of people who use React.

### Have you discussed this feature with our team

@layershifter 

### Additional context

#27227 

#25384 

IMO, Fluent UI team should at least complete the docs by offering a more detailed way to use Fluent UI in Next.js 13 appDir. For now, when this issue is created, the docs only mentioned:

> Note on [experimental appDir support](https://beta.nextjs.org/docs/api-reference/next-config#appdir)
> 
> Fluent UI React v9 use extensively React Context API, to use Fluent components within app directory please use [use client directive](https://beta.nextjs.org/docs/rendering/server-and-client-components#convention).

But it didn't offer us a useful message on how and where to add this directive. We definitely do not want to add "use client" directive in the root layout, because it will make the convenient features of Server Component completely unusable for us. As I know, [Next.js suggests](https://nextjs.org/docs/messages/context-in-server-component) that all files which have code called `React.createContext` should add "use client" directive on the top of themselves, so I believe that Fluent UI team may could simply add that directive in those files, if you do not want to make this library leverage Server Component features (which may not be so useful for a pure UI library).

In fact, I have tried to use appDir with Fluent UI by creating a component called `AppProvider` which host all Fluent UI related code (except `createDOMRenderer` and `renderToStyleElements`, which is supposed to be called on the server side), and add "use client" directive on the top of the file which declared this component, but Next.js still complain I missed "use client". The error happened in griffel which called "createContext" but didn't add "use client" [in this file](https://github.com/microsoft/griffel/blob/9126746567df4cf7ad8fb552c102f6499000264a/packages/react/src/RendererContext.tsx#LL30C29-L30C29). I then tried to add directive in `page.tsx`, still has no effect. My appDir has only three files: `AppProvider.tsx`, `layout.tsx` and `page.tsx`, it seems that the only option left to me is add directive in `layout.tsx`, which I never want to do. I will post these files below:

`AppProvider.tsx`:
```tsx
'use client';

import SiteConfiguration from '@/types/SiteConfiguration';
import {
  FluentProvider,
  GriffelRenderer,
  RendererProvider,
  SSRProvider,
  createDOMRenderer,
  createLightTheme,
  webLightTheme,
} from '@fluentui/react-components';
import React from 'react';

type AppProviderProps = React.PropsWithChildren<{
  renderer?: GriffelRenderer;
  configuration?: SiteConfiguration;
}>;

export default function AppProvider({
  children,
  renderer,
  configuration,
}: AppProviderProps) {
  return (
    <RendererProvider renderer={renderer || createDOMRenderer()}>
      <SSRProvider>
        <FluentProvider
          theme={
            configuration?.themeColors
              ? createLightTheme(configuration.themeColors)
              : webLightTheme
          }
        >
          {children}
        </FluentProvider>
      </SSRProvider>
    </RendererProvider>
  );
}
```

`layout.tsx`:
```tsx
import {
  createDOMRenderer,
  renderToStyleElements,
} from '@fluentui/react-components';
import React from 'react';
import AppProvider from './AppProvider';
import * as config from '../../web.config';

export default function Root({ children }: React.PropsWithChildren) {
  const renderer = React.useMemo(() => createDOMRenderer(), []);
  const styles = React.useMemo(
    () => renderToStyleElements(renderer),
    [renderer]
  );

  return (
    <html>
      <head>{styles}</head>
      <body>
        <AppProvider renderer={renderer} configuration={config}>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
```

`page.tsx`:
```tsx
'use client';

import { Button } from '@fluentui/react-components';

export default function Home() {
  return (
    <div>
      Home<Button>Hello</Button>
    </div>
  );
}
```

As a workaround, I could move `createDOMRenderer` and `renderToStyleElements` call into `AppProvider`, and use `next/head` component to insert style elements into `<head/>`. But I think it is not an elegant way to support CSS-in-JS in Next.js 13, because it seems that the root layout was designed to support CSS-in-JS with Server Component enabled.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by katungi** [comment]
Hey @sopranopillow ,
How is the progress for this coming along? and is there any way I can help?
I was trying to use Fluent with Next 13 and got lots of issues. I am open to helping with this issue in any capacity.

**Comment by sopranopillow** [comment]
Hi @katungi, I'll be out for a few weeks, but once I'm back I'll asses the work it will take to fully support NextJS 13. From there we'll decide if having a workaround is enough or fully committing to its support.

**Comment by katungi** [comment]
Hey @sopranopillow , No worries. Please keep in the loop when you get back.

**Comment by anish-dev-127** [comment]
please provide solution

**Comment by sopranopillow** [comment]
Hi @anish-dev-127, please refer to the comment above from @AkiraVoid for issues without styles. If you are having further problems that aren't related to NextJS 13, please create an issue giving details and repro for your error. This issue is only concerning whether NextJS 13 will be fully supported, or we'll provide a workaround.

**Comment by RudyCo** [comment]
Hello, I am new to Next.js and I would like to use it to create an Excel Add-in with Fluent UI React components. This lack of documentation is really annoying. Do you have an estimate for this issue? Thanks!

**Comment by sopranopillow** [comment]
Hi @RudyCo, I'm looking into it today as part of my hackathon and hopefully will have at least an issue detailing the path forward. Sorry for the inconvenience.

**Comment by AkiraVoid** [comment]
@sopranopillow Did we get any update on this?

**Comment by dashkevych** [comment]
I'm super excited that this issue of adding better support for Next.js 13 has been raised.

A few months ago, when the app directory was still an experimental feature in Next.js 13, I experimented with integrating Fluent UI with a Next.js project. I was successful in doing so, but one issue that kept me away from fully adopting Fluent UI was the slow initial load time, and I couldn't pinpoint the exact reason for this. Here is my code for reference: [fluentui-notes](https://github.com/dashkevych/fluentui-notes).

I am a big fan of Fluent UI for its professional touch that it adds to the user interface. However, the performance issue has been a significant concern. I am hopeful that with the support for Next.js 13, this issue will be addressed and optimized 🤞

**Comment by sopranopillow** [comment]
I have some news! I have completed the work for the swc plugin and can be found here:
- repo: https://github.com/sopranopillow/fluentui-nextjs-appdir-plugin
- npmjs: https://www.npmjs.com/package/fluentui-next-appdir-directive

For now, the repo explains how to use it, but if any question or concerns come up related to that package, please feel free to open issues in that repo. 

I will be updating the documentation for NextJS@>=13 to have a more in-depth setup guide. Will update this issue once I have the PR ready.

I currently have a simple NextJS@14 app with the plugin working as expected. There's a side issue with the provider as mentioned in [Shift's comment](https://github.com/microsoft/fluentui/issues/29361#issuecomment-1860257471), but that's a separate issue and will look into reporting. I will mark this issue as completed once the docs are updated. Thanks for being patient!

**Comment by pksorensen** [comment]
@sopranopillow  - awesome work. Just noticed this.

Would be even more awesome if someone have insights on using makestyles, fluentui components from the RSCs and css extractions. Not many examples out there showing that stuff.

**Comment by sopranopillow** [comment]
@pksorensen I don't have much available time at the moment, but was already thinking about adding examples on how to use css extraction. I'll update this comment with the issue to track the work.

**Comment by pksorensen** [comment]
@sopranopillow Sounds awesome, hope you will get more time ;D  

Another pain atm is also creating these really dummy client components for something as simple as using griffel/styles.
![image](https://github.com/microsoft/fluentui/assets/2718591/34168e23-a76a-4855-a562-68a187cd4e4e)
