### ISSUE TITLE
[Bug]: V8 Tooltips not shown in React 18/StrictMode

### ISSUE THREAD

**Issue by andyrooger** [microsoft/fluentui#28230]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 20.60 GB / 47.76 GB
  Browsers:
    Chrome: 114.0.5735.111
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/fluent8-react18-tooltip-yxzvl3

### Bug Description

Opening a new bug since #25534 was auto-closed

## Actual Behavior
In React 18 with strict mode, no tooltips are shown on hover.

## Expected Behavior
Tooltips should be shown correctly whether or not we're using strict mode

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by PMcGown** [comment]
We experienced this same issue. We did not need a delay and found that setting the `delay={TooltipDelay.zero}` rendered a tooltip in StrictMode. `TooltipDelay.medium` and `TooltipDelay.long` did not work.
