### ISSUE TITLE
[Bug]: Scrolling issue using ComboBox component

### ISSUE THREAD

**Issue by vinguyen12** [microsoft/fluentui#28248]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 4.47 GB / 15.71 GB
 Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.51)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/vinguyen12/pen/YzRqNwL?editors=1111

### Bug Description

Scrollbar is freezing for Combobox's dropdown

Repro steps: Open drop down -> use scrollbar (click arrow up/down, drag the thumb) to scroll up/down -> Observe behavior

## Actual Behavior
Scrollbar thumb is not moving when dragging it -> can't scroll the options list
Clicking arrows doesn't scroll the options list

## Expected Behavior
Arrows and scrollbar thumb should be functional and help us scroll the options list

Don’t repro on Chrome
However, if we hover mouse in and out the drop down list multiple times, the scrollbar would work normally.

### Requested priority

Normal

### Products/sites affected

Outlook Web

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ValentinaKozlova** [comment]
I wasn't able to reproduce the issue. Could you please give more details. Ideally, the video

**Comment by vinguyen12** [comment]
Here is the repro on my codepen.
![scroll-issue](https://github.com/microsoft/fluentui/assets/74168693/a6b166eb-d69e-443c-9abc-df500e9203ba)

The OS is correct. For browser, I can repro this on Edge but not Chrome.

**Comment by jpark58** [comment]
Same issue happens to me. So far, it only happens on Edge, not Chrome

**Comment by ValentinaKozlova** [comment]
@vinguyen12 , I was able to reproduce the issue. But the steps are inaccurate. If you use up/down arrow, after that it works. For me steps to reproduce were:
1. Click on the dropdown
2. Click on a scroller and try to drag it
Actual result:
It doesn't work
3. Click on arrows in the scroll bar
Actual result: nothings happens

But if I click on arrow keys and after that drag the scroller then everything works as expected.

**Comment by vinguyen12** [comment]
@ValentinaKozlova, as mentioned in the issue, it works as expected if we give the scroller and the arrows multiple tries. Such as, hovering mouse in and out the drop down list multiple times, then the scrollbar would work as expected. I think this makes it has several ways to reproduce the issue.

**Comment by penseleit** [comment]
This is happening in version 7.86.0 as well.

**Comment by dhw970805** [comment]
> Same issue happens to me. So far, it only happens on Edge, not Chrome

yes, it also happens to me , only on edge, works well on chrome
