### ISSUE TITLE
[Bug]: Selecting multiple items in list with footer will be resulted in selection of unexpected item on Top of the list.

### ISSUE THREAD

**Issue by gggjtgxing** [microsoft/fluentui#28246]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
it can repro in any system
example system: 
  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 14.54 GB / 31.79 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.43), ChromiumDev (95.0.997.1)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://m365b357263.sharepoint.com/sites/Test0607/Shared%20Documents/Forms/AllItems.aspx

### Bug Description

Document Library for Repro: https://m365b357263.sharepoint.com/sites/Test0607/Shared%20Documents/Forms/AllItems.aspx
account: admin@M365B357263.onmicrosoft.com 
ps: 8~B[ht=34I}t9XsZ

## Actual Behavior
![footer-selection](https://github.com/microsoft/fluentui/assets/17696563/22bc3ff6-9c05-4465-85fe-d87951645c56)
## Expected Behavior
only the last item should be selected

### Requested priority

Blocking

### Products/sites affected

SharePoint 

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ValentinaKozlova** [comment]
@gggjtgxing the link for reproduction is dead. I got message `We're sorry, but [email] can't be found in the m365b357263.sharepoint.com directory` Could you please share a working link?
