### ISSUE TITLE
[Bug]: TreeItem leaf and branch are not aligned

### ISSUE THREAD

**Issue by NiklasRamstrom** [microsoft/fluentui#28254]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 638.03 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 113.0.2
    Safari: 16.5
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/modest-frog-kzsmzr?file=/example.tsx

## Actual Behavior
When a Tree has both leaf and branch TreeItem on the same level, they are not aligned
Fluent version 9.21.0:
<img width="175" alt="image" src="https://github.com/microsoft/fluentui/assets/67627784/7710df1f-0ab6-49bd-bb27-4fb6f6e7194e">

## Expected Behavior
Branch and leaf TreeItems should align (as in Fluent version 9.18.0)
Fluent version 9.18.0:
<img width="182" alt="image" src="https://github.com/microsoft/fluentui/assets/67627784/b8af01b2-834f-46ab-982a-cc5a28ff5d3a">

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
That definitely looks like some regression! thanks for the catch @NiklasRamstrom! I'll investigate this
