### ISSUE TITLE
Data Grid: Freezing/Sticky columns

### ISSUE THREAD

**Issue by v-vedas** [microsoft/fluentui#28260]
### Discussed in https://github.com/microsoft/fluentui/discussions/28259

<div type='discussions-op-text'>

<sup>Originally posted by **v-vedas** June 20, 2023</sup>
Do we have the plan to support Locked/Sticky columns/ Rows in DetailsList component? Like the below, we can specify Frozen Rows and Columns.

![image](https://github.com/microsoft/fluentui/assets/59569793/a99f9675-64d4-4463-b5b0-b9b027faead0)

</div>
```[tasklist]
### Tasks
```

**Comment by aeromac** [comment]
This would still be a handy feature to have - both sticky rows and columns
