### ISSUE TITLE
[Bug]: Sticky sometimes cannot find ScrollablePane via context

### ISSUE THREAD

**Issue by dkozar** [microsoft/fluentui#28277]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
"@fluentui/react": "8.97.2"
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://aka.ms/fluentpen

## Introduction

It seems that `<ScrollablePane>` with `<Sticky>` works different in two different apps, and I'm not able to find out why. Both the apps use the same version of `@fluentui/react` (8.97.2).

I created a tiny DetailsList wrapper component, which is part of the shared library.
I wrapped the DetailsList with `<ScrollablePane>`. I also wrapped its header with `<Sticky>`.
The effect of this is that I could scroll the grid, and the header is sticky (is not scrolling away).

```ts
const headerRenderer:IRenderFunction<IDetailsHeaderProps> = (props, defaultRender): JSX.Element => {
  return (
    <Sticky>
      {defaultRender!({
        ...props,
        styles,
      })}
    </Sticky>
  );
}

const detailsList = (
  <DetailsList
     items={items}
     onRenderDetailsHeader={headerRenderer}
  />
);
    
return <ScrollablePane>{detailsList}</ScrollablePane>;
```

This works great in with one consumer app, but with the other the Sticky doesn't work as expected.

## Actual Behavior

With one consumer (Storybook), this works as expected.
With another, the Sticky is ignored, and the header scrolls away on scroll:

![image](https://github.com/microsoft/fluentui/assets/1078403/db222b20-a8b6-47ce-8ec7-fea00ead874c)

![image](https://github.com/microsoft/fluentui/assets/1078403/a6ad0a9f-d669-411d-ade0-12bd7982731b)

## Expected Behavior

The header shouldn't scroll away, but stay sticky.

## Root cause

By looking at the source, I realized that if the `scrollablePane `cannot be found in context, Sticky just wraps the children into a `div`:

https://github.com/microsoft/fluentui/blob/5809e04461b488016393f68d0c809d5b43eb93db/packages/react/src/components/Sticky/Sticky.tsx#L152

I managed to put a breakpoint into this method, and I could confirm that this is what actually happens:

![image](https://github.com/microsoft/fluentui/assets/1078403/b03dfd07-abef-4795-868c-4cd5e3a646af)

I'd appreciate any inputs on:

- have you possibly seen this before?
- how to debug it and understand the reason why the `scrollablePane `cannot be found?

Probably unrelated but, [ScrollablePane](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/ScrollablePane/ScrollablePane.base.tsx#L235) is a functional React component, whereas Sticky is class based React component.

### Logs

```shell
-
```

### Requested priority

High

### Products/sites affected

-

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by UsmanMuhammad** [comment]
Hi, I would like to investigate the issue, and if I can find the root cause then submit a PR.

**Comment by rtrevino89** [comment]
I'm also seeing this same issue with fluent 7. It seems the scrollable pane is not being found:

![image](https://github.com/microsoft/fluentui/assets/99822668/8ffd70b4-44e6-43c4-acf0-297ebafc1a41)
