### ISSUE TITLE
[Bug]: @fluentui/react-charting does not respect data updates when initially empty since version 5.16.37

### ISSUE THREAD

**Issue by sysofwan** [microsoft/fluentui#28280]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 35.61 GB / 63.78 GB
  Browsers:
    Chrome: 114.0.5735.134
    Edge: Spartan (44.22000.120.0), Chromium (114.0.1823.43), ChromiumDev (116.0.1923.0)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/gigroove_microsoft/pen/wvQWVXG

### Bug Description

A [recent commit](https://github.com/microsoft/fluentui/commit/3d73007c50ca4008618498a998cdaed5675bbda6#diff-01c391189335aeb7f9820e559af8ec24da286c1026852febd1b8ec319a653744) introduced empty data screen reader support for accessibility.

There is a bug in this implementation since the `emptyChart` state is only initialized in constructor or in `componentDidMount`. This prevents any updates to the chart data (i.e. for data requiring network requests) to be respected. Further updates to chart data results in an empty chart.

Ideally `emptyChart` should not be a state, and should be inferred based on `props.data` in the `render()` function.

## Actual Behavior
In version 5.16.37, chart is empty after `props.data` update.
https://codepen.io/gigroove_microsoft/pen/wvQWVXG

## Expected Behavior
In version 5.16.36, chart is not empty after `props.data` update
https://codepen.io/gigroove_microsoft/pen/rNQLXYY

### Requested priority

High

### Products/sites affected

Microsoft Defender, Microsoft Compliance Center

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by AtishayMsft** [comment]
This issue has been fixed in version [5.16.57](https://github.com/microsoft/fluentui/tree/@fluentui/react-charting_v5.16.57) of the charting library.
