### ISSUE TITLE
[Feature]: DataGrid Freezing/Sticky Columns and Rows

### ISSUE THREAD

**Issue by v-vedas** [microsoft/fluentui#28288]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Data Grid (Fluentui React Components (v9)) component need to support Frozen Rows and Columns Like the below mentioned screenshot. 

![image](https://github.com/microsoft/fluentui/assets/59569793/ca253262-7cb9-4c69-896f-4ae5b5f159b3)

### Have you discussed this feature with our team

Sean Monahan, Lingfan Gao

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ValentinaKozlova** [comment]
@v-vedas, could you please also rename the issue to the DataGrid? #28260

**Comment by ValentinaKozlova** [comment]
#28260
