### ISSUE TITLE
[Bug]: Selection in Single mode could cause unexpected behaviour when setIndexSelected is called more than once with the same values

### ISSUE THREAD

**Issue by msd-sal** [microsoft/fluentui#28306]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 9.79 GB / 31.63 GB
  Browsers:
    Chrome: 114.0.5735.134
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/microsoft/fluentui/blob/d93cb0b8cb80f56e753ad18c645eeb84a9c10256/packages/utilities/src/selection/Selection.ts

### Bug Description

https://github.com/microsoft/fluentui/blob/d93cb0b8cb80f56e753ad18c645eeb84a9c10256/packages/utilities/src/selection/Selection.ts
```
public setIndexSelected(index: number, isSelected: boolean, shouldAnchor: boolean): void {
    if (this.mode === SelectionMode.none) {
      return;
    }

    // Clamp the index.
    index = Math.min(Math.max(0, index), this._items.length - 1);

    // No-op on out of bounds selections.
    if (index < 0 || index >= this._items.length) {
      return;
    }

    this.setChangeEvents(false);

    const isExempt = this._exemptedIndices[index]; // <-- move from here
    const canSelect = !this._unselectableIndices[index];

    if (canSelect) {
      if (isSelected && this.mode === SelectionMode.single) {
        // If this is single-select, the previous selection should be removed.
        this._setAllSelected(false, true);
      }
      //  --> Move to here  <--
      // Determine if we need to remove the exemption.
      if (isExempt && ((isSelected && this._isAllSelected) || (!isSelected && !this._isAllSelected))) {
        delete this._exemptedIndices[index];
        this._exemptedCount--;
      }

      // Determine if we need to add the exemption.
      if (!isExempt && ((isSelected && !this._isAllSelected) || (!isSelected && this._isAllSelected))) {
        this._exemptedIndices[index] = true;
        this._exemptedCount++;
      }

      if (shouldAnchor) {
        this._anchoredIndex = index;
      }
    }

    this._updateCount();

    this.setChangeEvents(true);
  }
```
## Actual Behavior
The function `setIndexSelected`  when `SelectionMode` is `single` and its parameter `isSelected  = true` unselects all items in the list like this:
`this._setAllSelected(false, true)`
before that `isExempt` would have been already set based on the value of  `this._exemptedIndices`. Since `this._exemptedIndices` is changed when `this._setAllSelected(false, true)` is called, the value of `isExempt` seems stale for the purpose of this function.

If `Selection.prototype.setIndexSelected` is called a second time with the same values, the unselection happens again which causes `isExempt` to become stale and the code that follows would execute based on the stale value.

Execution: 

- 1st call `Selection.prototype.setIndexSelected(i, true, false)` 
   - `isExempt` has value `false`
   - `this._setAllSelected(false, true)` is called
   - line `this._exemptedIndices[index] = true;` executes
- 2nd call `Selection.prototype.setIndexSelected(i, true, false)` 
   - since `this._exemptedIndices[index]` has `true` from last call, `isExempt` has value `true`
   - `this._setAllSelected(false, true)` is called
   - `isExempt` still has  `true` eventhough `this._exemptedIndices` has been cleared
   - the following condition evaluates to `false`
      `(!isExempt && ((isSelected && !this._isAllSelected) || (!isSelected && this._isAllSelected)))`
      so the line `this._exemptedIndices[index] = true;` does not execute
We are at an inconsistent state

## Expected Behavior
`isExempt` to be evealuated AFTER `this._setAllSelected(false, true)` is called thus allowing for further code to execute and leaving us in a consistent state with an exemption for the index of the selected item 

This can be achieved by moving the `isExempt` declaration to line 395 below it

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by 3m3sd1** [comment]
has this been addressed in any build?
