### ISSUE TITLE
[Bug]: css variables get removed from FluentProviders of different sources

### ISSUE THREAD

**Issue by KagamiChan** [microsoft/fluentui#28310]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 41.80 GB / 63.16 GB
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.58)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/zen-tess-sjlvff

## Actual Behavior
clicking show Guest UI, the css varaibles are removed

## Expected Behavior
clicking show Guest UI, css variables are kept for every components

background:
Our project have Fluent UI from different sources, precisely, the main framework and some sections are built separately and both bundles a fluent UI library. We chose this architecture because the framework and sections are required to shipped separately.

This issue happens when we want to upgrade from 9.18 to 9.21, and 9.21 is the most suspecious because there's griffel updates. It behaves like the minimal repro: when we jump into a page of main framework and switch to a section page, then the styles are lost because css variables are nowhere in the provider, and the same thing goes if we starts from a section page and switch to main framework page.

in the repro, The App represents the main framework, and there's a compiled guest-index.js which represents the section that's built separately.

### Requested priority

High

### Products/sites affected

Edge wallet

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@KagamiChan we don't recommend to bundle Fluent multiple times for obvious reasons (more JS, bigger bundles). I suggest to consider a different strategy like using [`externals` in Webpack](https://webpack.js.org/configuration/externals/) or [Module Federation](https://webpack.js.org/concepts/module-federation/).

Anyway, you can resolve this by using `IdPrefixProvider`:

```tsx
<IdPrefixProvider value="host">{children}</IdPrefixProvider>
```

https://codesandbox.io/s/charming-ellis-96568f?file=/src/App.js

More details:
- https://react.fluentui.dev/?path=/docs/concepts-developer-advanced-configuration--page#idprefixprovider
- https://github.com/microsoft/fluentui/pull/26496

**Comment by KagamiChan** [comment]
Thanks @layershifter for pointing out the solution.

We cannot use externals nor module federation because it also has version compatibility issue considering 2 projects are built and shipped separately. So we'll have to keep reporting such issues we met :(
