### ISSUE TITLE
Performance Issue with Combo Box Containing 3000+ values-Fluent UI 9

### ISSUE THREAD

**Issue by Tamilselvan27** [microsoft/fluentui#28319]
<!--
### Environment Information

- **Package version(s)**: 9.20.0
- **Browser and OS versions**: Microsoft Edge/Chrome

### Describe the issue:

I am encountering a performance issue while working with a combo box that contains a large dataset of 3000+ entries. The problem arises when attempting to interact with the combo box on the web page, resulting in the page becoming unresponsive or crashing.

But while using the office UI fabric react (fluent UI 8), the component works.

```[tasklist]
### Tasks
```

**Comment by behowell** [comment]
Hi @Tamilselvan27, when logging a bug, please use the template for a Bug Report here: https://github.com/microsoft/fluentui/issues/new/choose. Make sure to fill out all fields, especially a link to a repro.
