### ISSUE TITLE
[Bug]: Dropdown with multiple items of the same name

### ISSUE THREAD

**Issue by SigarDave** [microsoft/fluentui#28333]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 3.48 GB / 15.73 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.58)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/infallible-feistel-t2sq6c

## Actual Behavior

If there are duplicate items in the Dropdown auto-populate item selection list then, it is adding the same items multiple times. 

## Expected Behavior
Even if there are multiple items with the same name, it should not add them to the auto-completion list multiple times. 

![image](https://github.com/microsoft/fluentui/assets/46348586/201c3615-fbaf-4aa1-a24a-936680e1e36c)

Behaviour:
![image](https://github.com/microsoft/fluentui/assets/46348586/bd2ae604-41b3-4ed7-a3ab-e371b878b251)

### Requested priority

Normal

### Products/sites affected

react-northstar

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by SigarDave** [comment]
Any Updates on this?

**Comment by layershifter** [comment]
@SigarDave your example uses shorthand form for values where keys and values are generated from a string i.e. `"Item"` => `{ header: "Item", key: "Item" }`. That's why you have a warning from React in your example:

```
Warning: Encountered two children with the same key, `Scarlett O'Hara`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

in this case you need to use shorthands instead of longhands to define keys properly, for example:

```ts
const inputItems = [
  { header: "Scarlett O'Hara", key: "scarlett A" },
  { header: "Scarlett O'Hara", key: "scarlett B" }
];
```

Full example: https://codesandbox.io/s/bold-darkness-c9pqky?file=/index.js:212-420
