### ISSUE TITLE
[Bug]: Select in Teams High contrast mode is not distinguishable from the background

### ISSUE THREAD

**Issue by Plahot** [microsoft/fluentui#28334]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Issue is reproducable in Fluent Ui docs : https://react.fluentui.dev/?path=/docs/components-select--default
```

### Are you reporting Accessibility issue?

yes

### Reproduction

Screenshot

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/118245242/52436bee-95ee-4d13-b01e-699d643f7dd8)

## Expected Behavior
Visible outline that allows distinguishing select from the background

### Requested priority

Normal

### Products/sites affected

Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @Plahot, the Teams High Contrast theme is only intended to be used by the Teams app. Are you able to reproduce this in Teams? Other apps use the 'forced colors' high contrast mode, which does show the outline (example with the Windows Aquatic contrast theme):
<img width="266" alt="image" src="https://github.com/microsoft/fluentui/assets/48106640/259908b5-dcaf-4d99-b73c-e6a38fff44f2">
