### ISSUE TITLE
[Feature]: Make v9 Dialog Draggable like v8

### ISSUE THREAD

**Issue by JamesBurnside** [microsoft/fluentui#28359]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

In v8 the [dialog](https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog) and modal components could be dragged.

To unblock our upgrade to v9 we would need the same draggable behavior in [v9's dialog](https://react.fluentui.dev/?path=/docs/components-dialog--default).

### Additional context

We used the draggable modal from v8 to create a [floating video tile](https://azure.github.io/communication-ui-library/?path=/docs/ui-components-videogallery--video-gallery#floating-local-video-layout) in our library.

Open to suggestions or recommended alternatives

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gouttierre** [comment]
📢"Ben will assign a developer during triage. cc @behowell"

**Comment by gouttierre** [comment]
📢" @marcosmoura is the assigned developer to complete this feature."

**Comment by gouttierre** [comment]
📢"Still in development with engineering."

**Comment by gouttierre** [comment]
📢 
- Marcos was out sick. He is almost done but needs to discuss a few things with Bernardo. The ETA has been updated to the EOM. cc @tudorpopams , @marcosmoura

**Comment by gouttierre** [comment]
📢 
- Marcos is about close to done with this feature request. It should be completed relatively soon but the developer and EM will confirm the status.  cc @marcosmoura , @tudorpopams

**Comment by gouttierre** [comment]
📢

-  @marcosmoura , @tudorpopams , please can you update the ETA for when this feature will be completed. Thank you.

**Comment by gouttierre** [comment]
📢
- The code for Draggable is done and ready for a pull request to be approved. CXE Prague will discuss the release and announcement strategy on Monday, so we can have a beta version for the partner to test before moving it to stable. cc @tudorpopams , @marcosmoura

**Comment by gouttierre** [comment]
📢 
- Need to merge the last feature PR code then will release the initial version.
- Need to create E2E tests. 
- Marcos will update the documentation and monitor possible issues and integration with partners

**Comment by gouttierre** [comment]
Component is done [react-draggable-dialog](https://microsoft.github.io/fluentui-contrib/react-draggable-dialog)

cc @tudorpopams

**Comment by markhughes** [comment]
@gouttierre When can we expect it to be published to npm? it looks documented, and available, but the package is not visible
