### ISSUE TITLE
[Feature]: TreeGrid

### ISSUE THREAD

**Issue by logicaloud** [microsoft/fluentui#28363]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

It would be nice to have a built in option for a tree grid, that is, a Tree with additional columns.

I hacked an example together here, based on a DataGrid with resizable header columns (only the header is used) and the Tree component: https://codesandbox.io/s/floral-cloud-f67c5q?file=/example.tsx

Is there a better way to achieve the same with the current functionality? Or could this be added as a new feature?

### Additional context

![image](https://github.com/microsoft/fluentui/assets/47704763/4bd0d5a2-fb82-4371-b206-0fc5fdea5894)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ldsenow** [comment]
hi, is this feature gonna have any priority in the roadmap?

**Comment by bsunderhus** [comment]
Hey there @ldsenow , the `TreeGrid` component has been developed in the [fluentui-contrib repo](https://github.com/microsoft/fluentui-contrib/blob/main/packages/react-tree-grid/README.md), with a less opinionated style approach
