### ISSUE TITLE
[Bug]: Dialog's height is not working correctly on older Firefox

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#28391]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 45.91 GB / 62.66 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 85.0.0
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-dialog--default

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/5953191/a7161422-f8ee-4135-aaa6-edf31f903ce4)

left is edge canary latest and right is firefox 85. We support firefox 75+ so this is not supposed to happen.
## Expected Behavior
left and right should match

### Requested priority

Low

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
Ok, seems this is related to some problem on supporting proper height on `fixed` elements on that version of firefox. The problem persists if we set the element to `absolute`. This will require further investigations
