### ISSUE TITLE
[Bug]: IconButton menu items with only SVGIcon don't render icons

### ISSUE THREAD

**Issue by benkeen** [microsoft/fluentui#28408]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 97.08 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/benjamin-keen/pen/vYQmdez?editors=1010

## Actual Behavior
When you create an IconButton with menu items that ONLY contain SVG Icons, none of the icons show. When you add one menu item with a Font icon, all the icons now show. 

## Expected Behavior
When you create an IconButton with menu items that only contains SVG Icons, the icons show up.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @benkeen, it appears the Menu only renders the icons if a menu item has `iconProps` set. You can work around this by adding `iconProps: {}` to the menu items that are rendering SVG icons.

Here's your example, modified to set `iconProps: {}`: https://codepen.io/behowell/pen/WNYZKyv?editors=1010 

Let me know if that workaround doesn't work for you. Thanks.

**Comment by benkeen** [comment]
Great stuff, @behowell. Odd one, but yes I think that would do fine. We'll be moving to FUI9 at some point so this'll be moot with the newer components.
