### ISSUE TITLE
Clicking on anything non-focusable in the dialog focuses the dialog

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#28404]
This is especially noticeable when there are scrollable containers inside the dialog. https://codesandbox.io/s/sad-sanne-77x373?file=/example.tsx

In the gif you can see that the input is blurred once the scrollbar is clicked

![combobox blur](https://github.com/microsoft/fluentui/assets/20744592/f430da87-7dbf-498a-a8bc-a40f0e4efba3)

By default the `mousedown`  event will propagate and focus a focusable parent (i.e. tabindex >= -1) if available. This can be detrimental when users want to have focus/blur related behaviour within the dialog because clicking on things like scrollbars should not blur a component like a combobox

**Comment by jurokapsiar** [comment]
related: https://bugs.chromium.org/p/chromium/issues/detail?id=1459926&q=&can=4

**Comment by bsunderhus** [comment]
In the example provided, if you simply add `tabIndex=undefined` to `DialogSurface` the problem is solved

https://codesandbox.io/s/sad-sanne-77x373?file=/example.tsx

**Comment by ling1726** [comment]
I suggest moving this issue to the backlog until we see more standard use cases that are affected.

We've only seen one use case where this tabindex causes problems. We found a simple enough workaround for that,
