### ISSUE TITLE
`colorBrandForegroundInverted` tokens not visible on inverted background in teams high contrast mode

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#28400]
The `Link` component uses `colorBrandForegroundInverted ` as foreground color when on inverted background. However it is not visible when hovered/pressed
![inverted hover](https://github.com/microsoft/fluentui/assets/20744592/a38cfeb3-fa31-435a-835b-971397c9195a)

**Comment by ling1726** [comment]
@daisygeng can you take a look at this?

**Comment by YuanboXue-Amber** [comment]
@daisygeng I have another issue also related to token: #28478
