### ISSUE TITLE
[Bug]: Page gets scrolled down on opening a callout with focustrapzone inside

### ISSUE THREAD

**Issue by ramnarendar** [microsoft/fluentui#28429]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 12th Gen Intel(R) Core(TM) i9-12950HX
    Memory: 38.56 GB / 62.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
```

### Are you reporting Accessibility issue?

yes

### Reproduction

yes

## Actual Behavior
I am returning a callout post invoking a button. Inside callout i have focustrapzone. when its invoked, page gets scrolled to the end
## Expected Behavior
Page should not get scolled down
![Screenshot 2023-07-04 185251](https://github.com/microsoft/fluentui/assets/68994213/d1c66686-d6e8-4095-a127-c786a6ac3a6e)

### Requested priority

Blocking

### Products/sites affected

viva goals

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @ramnarendar, please provide a link to a reproduction in a codepen (or codesandbox, etc.). Thanks!

**Comment by behowell** [comment]
Closing as no repro was provided. If this is still an issue for you, please add a repro link. Thanks.
