### ISSUE TITLE
Bug: v9 RadioGroup does not provide an easy way to focus selected radio, and does not play well with tabster

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#28438]
### Describe the issue:

Radios within a radiogroup are treated as a single tab stop, with focus landing on the selected radio. This is handled by the browser when tabbing between native `<input type="radio">` elements, but needs to be manually implemented when programmatically calling focus on the group.

In Fluent v8's ChoiceGroup, we had a [custom `.focus()` handler](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/ChoiceGroup/ChoiceGroup.base.tsx#L66) that called focus on the selected radio. In v9, we have two scenarios that likely need to be handled in a similar way:
1. Authors needing to send focus to the selected Radio in the RadioGroup
2. Tabster sending focus to the RadioGroup when it is the first or last item in a focus trap. Here's a codesandbox demonstrating the tabster issue: https://codesandbox.io/s/86p2ck?file=/example.tsx

The tabster issue may be better fixed in tabster itself, since the same bug will be present for non-Fluent radios.

### Priorities and help requested (not applicable if asking question):

Products/sites affected: Teams

**Comment by behowell** [comment]
I've closed/recalled the PR that would have added an API to RadioGroup for item 1 in this issue. That is something that a user can handle with a few lines of code.

Item 2 will need to be fixed in tabster itself.

**Comment by behowell** [comment]
I've logged https://github.com/microsoft/tabster/issues/342 to track the fix in Tabster. I'm going to resolve this issue as External.

I don't think it's necessary to write a documentation example for programmatic focus to the radio group, but here's an option if we later decide it is needed:

```ts
export const ProgrammaticFocus = () => {
  const ref = React.useRef<HTMLDivElement>(null);

  const focusRadioGroup = () => {
    if (ref.current) {
      // Find the selected radio item. Or if none is selected, find the first enabled radio item.
      const target =
        ref.current.querySelector<HTMLInputElement>('input[type=radio]:checked') ||
        ref.current.querySelector<HTMLInputElement>('input[type=radio]:enabled');

      target?.focus();
    }
  };

  return (
    <>
      <Field label="Favorite Fruit">
        <RadioGroup defaultValue="banana" ref={ref}>
          <Radio value="apple" label="Apple" />
          <Radio value="pear" label="Pear" />
          <Radio value="banana" label="Banana" />
          <Radio value="orange" label="Orange" />
        </RadioGroup>
      </Field>
      <Button onClick={focusRadioGroup}>Focus on RadioGroup</Button>
    </>
  );
};
```
