### ISSUE TITLE
[Bug]: Fabric core CSS files incorrectly set @charset

### ISSUE THREAD

**Issue by dom-zhu** [microsoft/fluentui#28442]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
not relevant
```

### Are you reporting Accessibility issue?

None

### Reproduction

a

## Actual Behavior
The fabric core css files incorrectly set the charset at the top of the file.

![image](https://github.com/microsoft/fluentui/assets/44078427/904b2f12-58e1-4026-a188-f1693e1693b7)
1. supposed to use double quotes https://developer.mozilla.org/en-US/docs/Web/CSS/@charset#examples
2. Charset must be the first thing in the file https://www.w3.org/International/questions/qa-css-charset  

see https://github.com/microsoft/fluentui/issues/27778

## Expected Behavior
Charset to be written at the top of the file, before the comments as
```
@charset "UTF-8";
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @dom-zhu could you provide details about the problem that results from this charset declaration? Ideally provide a codepen or codesandbox repro link that shows the resulting issue that would be corrected by fixing the charset declaration. That will help us prioritize this. Thanks!
