### ISSUE TITLE
[Bug]: Combobox doesn't dismiss when dragged in dialog

### ISSUE THREAD

**Issue by SavannahBourgeois** [microsoft/fluentui#28446]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
all environments
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/savannahbourgeois/pen/QWJqwWd

### Bug Description

Repro Steps:
1. Open dialog
2. Open combobox dropdown on dialog
3. Drag dialog with dropdown open

## Actual Behavior
Dropdown does not close until mouse up and "detaches" from the combobox while dragging so there is a floating menu

## Expected Behavior
Either dropdown dismisses or moves with the combobox
![dialogcombobox](https://github.com/microsoft/fluentui/assets/42548121/ca6cb726-dafd-48b4-9a84-9d2ebc7ff8a6)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Thanks for logging this @SavannahBourgeois! As discussed offline, we're going to Won't-Fix this issue:
* The scenario is relatively rare: dragging dialogs while a Combobox is open is not a common thing to do.
* The user bad is only aesthetic: the Combobox does dismiss when finished dragging the dialog.
* The bar is higher for longstanding v8 fit-and-finish issues, now that v9 is available.

Thanks!

**Comment by 15MariamS** [comment]
👋 I'm having a similar issue with the dropdown not closing in a dialog at all. The listbox stays open, even when I click outside of the dropdown.
![2023-09-29 20 57 14](https://github.com/microsoft/fluentui/assets/81782111/cfa1b6a2-402e-4f7b-aa1f-8f8dd7e4a768)
