### ISSUE TITLE
[Bug]: CardHeader header slot with children and props are broken in latest Fluent UI version

### ISSUE THREAD

**Issue by NotWoods** [microsoft/fluentui#28448]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/crazy-tesla-m23yyw?file=/example.tsx

## Actual Behavior
When passing an object with `className` and `children` to the `header` slot in a `CardHeader`, React throws an error.

```tsx
// style the floating action container
<CardHeader
  header={{
    className: styles.header,
    children: <Text />
  }}
>
```

## Expected Behavior
Using an object prop with `children` and other properties like `className` used to allow us to style the container while inserting a custom child. The [Microsoft Loop](https://loop.microsoft.com) logged-in homepage has some examples of this working.

We previously used 9.20.0 and noticed this issue when trying to upgrade to 9.24.0. It may have been introduced in a version between those two, however.

### Requested priority

Blocking

### Products/sites affected

Microsoft Loop

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
@marcosmoura this appears to be a regression from:
* https://github.com/microsoft/fluentui/pull/28266

In particular, it looks like the call to `getChildWithId(header)` is using `props.header`, which could be either slot shorthand or a props object. Currently, this is crashing when the header is a props object. Instead, you need to move up the call to `resolveShorthand` for the header slot (currently on line 88), and call `getChildWithId(resolvedHeader.children)`.
