### ISSUE TITLE
[Bug]: Dropdown's calloutProps.layerProps.componentRef does not set, always null

### ISSUE THREAD

**Issue by aibek-draftwise** [microsoft/fluentui#28443]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 81.78 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 15.3
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/Aibek-Smagulov/pen/MWzvZeQ
Create a Dropdown, try setting componentRef with useRef into calloutProps.layerProps.componentRef and print the ref, it is always null 

## Actual Behavior
The ref is not referring to the outside Layer component

## Expected Behavior
The ref is should refer to the outside Layer component, and have access to its functionality

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @aibek-draftwise, it looks like the `ILayer` interface for `layerProps.componentRef` is an empty interface (see [Layer.types.ts](https://github.com/microsoft/fluentui/blob/e3a0d071997ee796ba7d0931b6d3a5a341fb3921/packages/react/src/components/Layer/Layer.types.ts#L9)). There would be nothing you could do to this object if it were to be set to something other than `null`. I'm not sure why the `componentRef` prop was added to Layer, but it looks like it might have been a mistake. Any fix here would likely be to add a `@deprecated` comment, and a warning that it doesn't work.

Please let me know if I misunderstood the issue.
