### ISSUE TITLE
[Bug]: In a Combobox with freeform, typing a text that doesn't match any of the options raises onOptionSelect with empty selection

### ISSUE THREAD

**Issue by RamyRafik** [microsoft/fluentui#28453]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz
    Memory: 38.32 GB / 63.69 GB
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.55)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/nervous-liskov-4x3kjm?file=/example.tsx

## Intro
The sandbox contains a Combobox with freeform enabled, but no filtering logic is implemented. Handler for onOptionSelect shows an alert with the selected option.

## Steps
1- Open the options list by clicking on the Combobox
2- Select "Cow" -> An alert shows "Option selected: Cow" (Expected)
3- Highlight the text of the textbox
4- Type "F" -> The list expands, activates first matching option "Fish", "Cow" is still selected, no Alert. (Expected)
5- Type "x" after the "F"

## Expected Behavior
Textbox would contain "Fx". "Cow" would still be selected. No Alert shows (As selection hasn't changed)

## Actual Behavior
An alert shows "Option selected: undefined". "Cow" is unselected.
Debugger shows a call to function `clearSelection` in `useSelection.js`

### Logs

```shell
Call stack 
    at onOptionSelect (example.tsx:30:5)
    at clearSelection (useSelection.js:58:73)
    at onTriggerChange (useCombobox.js:122:13)
```

### Requested priority

High

### Products/sites affected

PowerApps

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
@smhigley can you confirm whether this is a bug or working as intended? If you type something that is not one of the available options, then it makes sense to me that there would not be anything selected.
