### ISSUE TITLE
[Bug]: DialogOpenChangeData not reachable in imports but present as an export in library

### ISSUE THREAD

**Issue by jatin-tarachandani** [microsoft/fluentui#28462]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 74.91 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.67
    Safari: 15.6.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

codesandbox.io/jovial-gould-nfydg8

## Actual Behavior
When attempting to import and use as shown in the examples on the documentation website https://react.fluentui.dev/?path=/docs/components-dialog--default, it says "export 'DialogOpenChangeData' (imported as 'reactComponents') was not found in '@fluentui/react-components'"
in the codesandbox link which is a direct copy of the code on the documentation website, the import is not being recognised.

## Expected Behavior
The export of DialogOpenChangeData (which is present in my installation of the library) should be imported and usable. 

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by jatin-tarachandani** [comment]
Apologies: The issue is with react-components library, not react-northstar

**Comment by behowell** [comment]
Hi @jatin-tarachandani , your repro link is a 404. Can you update the repro link?

I tried opening the [Trigger Outside Dialog](https://react.fluentui.dev/?path=/docs/components-dialog--default#trigger-outside-dialog) example in codesandbox, which imports DialogOpenChangeData, and it compiles without issue: https://codesandbox.io/s/z6l97l?file=/example.tsx
