### ISSUE TITLE
[Bug]: `convergence_epic.md` out of date

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#28466]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://github.com/microsoft/fluentui/wiki/new-release-process---v9-packages

## Actual Behavior
`convergence_epic.md` has a checklist item to publish a new package to `/unstable. ([link](https://github.com/microsoft/fluentui/blob/master/.github/ISSUE_TEMPLATE/convergence_epic.md?plain=1#L33))

## Expected Behavior
Based on our [new release guide](https://github.com/microsoft/fluentui/wiki/new-release-process---v9-packages) nothing should be changed in `/unstable` and we have a new workflow for in-development components.

The epic template needs to be updated to reflect these changes.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
FYI @ling1726 @Hotell
