### ISSUE TITLE
[Bug]: Tooltip with ReactNode content was inserted into DOM tree without triggering

### ISSUE THREAD

**Issue by ymyqwe** [microsoft/fluentui#28472]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 27.85 GB / 31.21 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/great-hill-9ersrj?file=/example.tsx

## Actual Behavior
if we use a tooltip as below, the content is a ReactNode instead of a string:
![image](https://github.com/microsoft/fluentui/assets/11665103/f2c2ef4a-13a9-4aa9-a0fd-e660544db094)
And it will directly render a Tooltip DOM in the HTML. 
![image](https://github.com/microsoft/fluentui/assets/11665103/ad7ab8b9-acc7-47cd-a07f-bd7f72fbcbda)

## Expected Behavior
The tooltip should be mounted to the DOM tree when hovering.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
This is by design:
https://github.com/microsoft/fluentui/blob/1082207b08959996cd736725735cadc01d0849b0/packages/react-components/react-tooltip/docs/Spec.md?plain=1#L368-L371
