### ISSUE TITLE
[Bug]: `colorBrandBackground2Hover` and pressed is not visible on `colorbrandbackground2` in contrast mode 

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/fluentui#28478]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
v9.25.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/theme-colors--page

### Bug Description

Semantically a component can have background color `colorBrandBackground2`, hover background `colorBrandBackground2Hover` and pressed background `colorBrandBackground2Pressed`.
But they are the same color in contrast theme, making it not visible when hover/pressed: 
<img width="1171" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/6704dcc5-1bf0-4255-9612-30c8780d5b61">

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
@redongreen - would appreciate your opinion on this. cc @daisygeng
