### ISSUE TITLE
[Bug]: Accessibility for multiple selection control is not working in mobile.

### ISSUE THREAD

**Issue by kidtalkative** [microsoft/fluentui#28473]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
Issue component: @fluentui/react-northstar@0.66.2 | Dropdown - Multiple Selection
The issue occurred on mobile: tested on Android 13 and IOS 16.5.1
```

### Are you reporting Accessibility issue?

Yes

### Reproduction

https://codesandbox.io/s/66enq3?module=/example.js

### Bug Description

We're using the library fluentui/react-northstar version 0.66.2 to build a search filter with the multiple selection dropdown component.
Everything works perfectly except for the accessibility for this component on the mobile.
Steps to replicate the issue:
1. Turn on Talkback/VoiceOver.
2. Navigate to the multiple selection dropdown.
3. Try to open the dropdown, select and remove an item.

## Actual Behavior
For Android - Talkback in Android 13
We're able to open the list. Talkpad announces the number of items but we cannot navigate to the list nor select items. Try to swipe the screen will focus on the next item on the page instead of traversing the list.

For IOS - VoiceOver in IOS 16.5.1
We're able to open and select multiple items in IOS. However, there's no way to remove selected items. 
VoiceOver keeps announcing "using the delete or back buttons to remove the selected item". Try to swipe or double tap leads to nothing.

## Expected Behavior
1. On mobile devices in accessibility mode, users should be able to select and remove items.
2. The multiple selection dropdown should provide appropriate context for removing an item, as the delete or back buttons may not be accessible through the keyboard.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by jurokapsiar** [comment]
Hi, Fluent UI v0 does not support mobile devices. https://fluentsite.z22.web.core.windows.net/0.66.2/faq#does-fluent-ui-support-mobile

We are happy to accept PRs if they fix the issues though. You can also check if the experience is better in the v9 Combobox/Dropdown - https://react.fluentui.dev/
