### ISSUE TITLE
[Bug]: Calendar Functionality - Incorrect Day names n

### ISSUE THREAD

**Issue by sasif2280** [microsoft/fluentui#28485]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
OS: Windows
    CPU: (8) x6
    Memory: 3.4
  Binaries:
    Node: 16.17
    npm: 8.15.0
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://github.com/sasif2280/fluent-UI-calender-functionality-bug

### Bug Description

We are using fluentUI v 8.62.4
we need update into this version only.
we are getting wrong day name when hovered over shot day name it shows day name with its short name
 please see the screenshot 

<img width="970" alt="bug" src="https://github.com/microsoft/fluentui/assets/61416943/e24be51f-0267-436f-a9d9-136272b3376d">

### Logs

```shell
n.a
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
This issues was fixed in #25003 and released in version 8.98.0 in October 2022. If you need a fix to an older version, I would suggest to patch the package on your side (for example by using `patch-package`).
