### ISSUE TITLE
[Feature]: DataGrid v9 - ability to set sortable property on individual columns

### ISSUE THREAD

**Issue by baggasumit** [microsoft/fluentui#28511]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

For Fluent v9 DataGrid component, it will be great to have the ability to set individual columns to be sortable or not. Right now, we can only specify the sortable property at the DataGrid level, so either all columns are sortable or none are sortable. Please let us know if there is already a workaround for this, so that we can use that in the mean time.

### Have you discussed this feature with our team

No

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kkakroo** [comment]
Hi @ling1726 , wanted to give this a shot if that's okay.
Do you think adding a `sortable` prop to `createTableColumn` would be the right approach.

**Comment by ling1726** [comment]
> Hi @ling1726 , wanted to give this a shot if that's okay. Do you think adding a `sortable` prop to `createTableColumn` would be the right approach.

I don't think that extra information is necessary, each column definition already includes an optional `comparator`. I think it should be fine to check for the existence of the comparator to know if a column is sortable.

You'd also need to make updates to the base `TableHeaderCell` and add a `sortable` prop to explicitly turn override `sortable` which is passed from the top level `Table` component
