### ISSUE TITLE
[Bug]: Input box not behaving same html input control when value are updated

### ISSUE THREAD

**Issue by pbal** [microsoft/fluentui#28518]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Win 11
    CPU: x64 Intel(R) Core(TM) i9-12900K
    Memory: 32.00 GB
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.67 

```

### Are you reporting Accessibility issue?

no

### Reproduction

codesandbox.io/s/aged-wave-mds83y?file=/example.tsx

## Actual Behavior

When you open the sandbox, click the "Submit" button in preview a couple of times.
You will notice that input(default html) box toggles its value between true/false. It also toggles disable on the input(default html) box.

Now change line 24 in example.tsx from "input" to "Input" so it uses fluent textbox input. When you click "Submit" button now, you will notice the control toggles its disability but the value in the control is never reflected.

## Expected Behavior
"Input" control should behave the same way "input" control and reflect value correctly on update.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Duplicate of #25749, please check https://github.com/microsoft/fluentui/issues/25749#issuecomment-1404231941.

**Comment by pbal** [comment]
As per suggestion from above linked issue, I wrapped Input component with Controller. Issue was still not resolved.

Update same codesandbox with suggestion.

**Comment by pbal** [comment]
Updated code sandbox with feedback. 

Input element now correctly reflect the value
