### ISSUE TITLE
[Bug]: Module not found: Error: Package path ./lib/useId is not exported from package @fluentui\react-hooks

### ISSUE THREAD

**Issue by Ronnysi** [microsoft/fluentui#28535]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
"@fluentui/react": "8.103.5",
    "react": "17.0.2",
    "react-dom": "17.0.2"

Node.js 16.8.1
npm 6.14.17
```

### Are you reporting Accessibility issue?

None

### Reproduction

NA

### Bug Description

When upgrading "@fluentui/react" from "7.170.3" to "8.103.5",
I get the error: Module not found: Error: Package path ./lib/useId is not exported from package path... \node_modules\@fluentui\react-hooks (see exports field in path...\node_modules\@fluentui\react-hooks\package.json)

I don't use useId or @fluentui\react-hooks no where in my code.

In node_modules\@fluentui\react-hooks\lib\useId.d.ts I can see:
export declare function useId(prefix?: string, providedId?: string): string;

### Logs

```shell
Module not found: Error: Package path ./lib/useId is not exported from package path... \node_modules\@fluentui\react-hooks (see exports field in path...\node_modules\@fluentui\react-hooks\package.json)
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Talked to Ronnysi offline, and the issue was resolved on their end.
