### ISSUE TITLE
[Feature]: DetailsList drag and drop to groups.

### ISSUE THREAD

**Issue by aravindjaimon** [microsoft/fluentui#28537]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Currently the drag and drop in a detailed list works only with reordering items in the table. If we need to move the data from one section to another how to do that?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sopranopillow** [comment]
Hi @aravindjaimon Would you mind giving more context? I think what you're talking about is dragging and dropping only cells?
