### ISSUE TITLE
[Bug]: Changelog of @fluentui/react is too big to open

### ISSUE THREAD

**Issue by ElPrudi** [microsoft/fluentui#28544]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
.
```

### Are you reporting Accessibility issue?

None

### Reproduction

.

### Bug Description

When you go to the changelog of @fluentui/react, the file is too big for github to open
![image](https://github.com/microsoft/fluentui/assets/86804651/2b685a6d-a285-4bd6-88a8-cf1e7caa18f9)

### Logs

```shell
.
```

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
This is expected, there's been many changes and it's a pretty long text. Usually refreshing the page works, but if that's not working you can try reading it in raw format.
