### ISSUE TITLE
[Bug]: In Button subtle mode in windows high contrast, icon is not visible on button hover

### ISSUE THREAD

**Issue by sjwilczynski** [microsoft/fluentui#28546]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Reproducable on codesnadbox from current version of https://react.fluentui.dev/?path=/docs/components-button-button--default#appearance
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/isi9x1?file=/example.tsx

## Actual Behavior

![subtleButtonInHC](https://github.com/microsoft/fluentui/assets/19153565/dcfcbc94-2d4e-4cca-a7b9-2031a0584ec6)

## Expected Behavior

The icon should be visible in all modes

### Requested priority

Normal

### Products/sites affected

People App

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sjwilczynski** [comment]
Note: the issue reproes in windows high contrast mode when Teams light theme is picked

**Comment by sopranopillow** [comment]
Looks like it was partially fixed, but still doesn't have a great contrast:

https://github.com/microsoft/fluentui/assets/5953191/e2a877bc-f8ee-4e71-81b2-db245983e755

**Comment by micahgodbolt** [comment]
yeah, we made some improvements in the past to get closer, but it seems we still missed this

![image](https://github.com/microsoft/fluentui/assets/1434956/a534b02a-7583-40ff-809a-61ffb9e1cfcc)

The text color shouldn't canvas

![image](https://github.com/microsoft/fluentui/assets/1434956/b790bda7-82cd-48a7-a4d3-a005f85ebbc1)

It should be highlight

![image](https://github.com/microsoft/fluentui/assets/1434956/2d7cf5af-6e39-4475-a1c1-b893d63f03aa)


also need to make sure that the icon is using highlight or just inherit

**Comment by sjwilczynski** [comment]
Great, thank you!
