### ISSUE TITLE
[Feature]: zIndex handling in v9

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#28543]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

The problem was initially raised by our partner (Teams), they want to standardize `zIndex` values across the app i.e. create a set of `zIndex` values:

```ts
export const zIndexes = {
  layerA: 1,
  layerB: 2,
  layerC: 3,
}
```

The similar thing exists in both v0 & v8:

https://github.com/microsoft/fluentui/blob/c3f4b77f8160185518b1fea6d74be239519fba73/packages/style-utilities/src/styles/zIndexes.ts#L1-L11

https://github.com/microsoft/fluentui/blob/c3f4b77f8160185518b1fea6d74be239519fba73/packages/fluentui/react-northstar/src/themes/teams/siteVariables.ts#L72-L79

However, in v9 we use arbitrary values:

<img width="1319" alt="image" src="https://github.com/microsoft/fluentui/assets/14183168/98523e59-fcb1-476c-86c0-91a72cedf830">

---

The feature requires RFC and proper design.

### Have you discussed this feature with our team

Yes, during Tech sync

### Additional context

@Hotell proposed to utilize stacking contexts instead of usage of z-indexes: https://web.dev/learn/css/z-index/#stacking-context

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gouttierre** [comment]
📢
- Tudor will follow-up and start conversations with Shift.
 cc @tudorpopams , @layershifter , @JustSlone

**Comment by gouttierre** [comment]
📢
- Marcos is going present the proposal during the tech sync on Wednesday. Dev has the implementation ready, so the outcome should be quick to be delivered.

cc @tudorpopams , @marcosmoura , @jurokapsiar

**Comment by gouttierre** [comment]
📢 
- Completed by #31831 

cc~ @tudorpopams , @JustSlone , @marcosmoura
