### ISSUE TITLE
[Bug]: React-components Button high contrast styles too easily overridden by custom styles

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#28552]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
na
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/empty-http-3r6nvq?file=/example.tsx

### Bug Description

When applying text and background customization to buttons via griffel, those colors always win over any default buttons styles due to griffelResetStyles

Unfortunately this means that since button uses forcedColorAdjust and customized HC colors, adding any textColor or backgroundColor overrides the customized HC colors

This might be solved by moving HC colors outside of resetStyles, or maybe some component specific css vars that only affect the non HC colors. 

For now I am wrapping my custom styles in `@media (forced-colors: none)` so that it doesn't effect the colors when HC is active

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Tracked by https://github.com/microsoft/griffel/issues/403.
