### ISSUE TITLE
[Feature]: Popup provides a way to not dismiss when a focus event fires from iframe

### ISSUE THREAD

**Issue by lubobill1990** [microsoft/fluentui#28556]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

There were PRs and issues about dismissing popup when activeElement change to iframe.

https://github.com/microsoft/fluentui/issues/19956
https://github.com/microsoft/fluentui/pull/8290

The latest behavior that dismisses popup when activeElement changes to iframe is not always as expected, since the activeElement can change to iframe when the iframe has some JavaScript code to call focus() function.

In most cases, the iframe's code is not in control, and it results in bugs.

I propose to add props to Popup to disable this auto dismiss logic.

### Have you discussed this feature with our team

Not yet, will contact Juraj

### Additional context

This auto dismiss behavior result in two bugs in Teams meeting scenario.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by lubobill1990** [comment]
Current code on auto dismiss: https://github.com/microsoft/fluentui/pull/18893/files#diff-f6b2903f4db0de6ccc491199dedf162836c43d833651cdb7140d5617d12f2287R186

**Comment by layershifter** [comment]
I created a CodeSandbox example where such issue reproes: https://codesandbox.io/s/quirky-joji-yc4wgw?file=/example.tsx
