### ISSUE TITLE
[Bug]: DataGrid Headers look weird on Safari

### ISSUE THREAD

**Issue by barisbikmaz** [microsoft/fluentui#28562]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 71.48 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 15.3
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/xnqzvf?file=/example.tsx

## Actual Behavior
DataGrid Headers look like this on Mac Safari

<img width="1004" alt="image" src="https://github.com/microsoft/fluentui/assets/6338132/45edd760-d6f2-473f-bdfe-0037bd6d7646">

## Expected Behavior
<img width="846" alt="image" src="https://github.com/microsoft/fluentui/assets/6338132/def8139a-7eda-4d8c-8ce7-389855ca89d3">

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by barisbikmaz** [comment]
The label is wrong. It must be Fluent UI Components (v9)

**Comment by miroslavstastny** [comment]
@ling1726 can you please review the PR?
