### ISSUE TITLE
[Feature]: Handle dynamic IDs in Jest Serializer

### ISSUE THREAD

**Issue by Symbitic** [microsoft/fluentui#28586]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Several FluentUI components like Pivot generate dynamic IDs, which causes snapshots in jest and vitest to fail. I'd like the jest serializer to be extended to handle dynamically generated IDs as well.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sopranopillow** [comment]
Hi @Symbitic, I suggest you use https://github.com/microsoft/fluentui/tree/master/packages/jest-serializer-merge-styles to avoid having issues with jest. This should fix the problem.

**Comment by Symbitic** [comment]
Tried that. It still generates dynamic IDs. That package is actually why I filed this.

**Comment by sopranopillow** [comment]
This seems to be a bug instead of a feature request, could you create an issue for the bug and provide a repro of what you're doing? jest-serializer-merge-styles should be the solution to what you're trying to do.
