### ISSUE TITLE
[Bug]: Selecting an item, which has as media prop an image on a Virtualized Table, leads to image flickering 

### ISSUE THREAD

**Issue by kboul** [microsoft/fluentui#28598]
### Library

React Components / v9 (@fluentui/react-components) version 9.26.1

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 1.31 GB / 15.50 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Browsers:
    Chrome: 111.0.5563.146
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/selecting-an-item-which-has-as-media-prop-an-image-on-a-virtualized-table-leads-to-image-flickering-25qdj9

## Actual Behavior
Please click the open in a new tab option in the provided codesandbox and **open the console** . Opening the console is really important because otherwise the bug is not reproducible. Or please see the attached GIF:
![fluent-table-virtualization-img-flickering-on-select](https://github.com/microsoft/fluentui/assets/14216599/08ceaabf-e114-4856-b152-f3f5ea1dba4d) 
In the GIF the console was opened as a separate window therefore it is not obvious that it is open, that is why I am mentioning it.

When using Virtualization in a table and selecting a row, which has an image, causes all the images on every row to flicker upon row toggling.

## Expected Behavior
Selecting a table row does not lead to image flickering

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sjwilczynski** [comment]
+1 on this, cc @ling1726 for us it also reproes when item list gets updated after loading more data
