### ISSUE TITLE
[Feature]: Add css containment to Dialog Surface

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#28612]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

It would be great to add [css containment](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment) to the dialog surface, this would improve performance and make the component more robust. It could use a strict containment but we would have to check if it's supported, otherwise we could just have layout.

I don't have as much context on how heavy dialog already is, but if this is possible, it would be a great win.

### Have you discussed this feature with our team

@spmonahan

### Additional context

Carousels can be used in dialogs, this means that there are elements hidden outside of the dialog. If containment was applied, there would be much less recalc and the users would get this win out of the box.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by layershifter** [comment]
This can be done also on a consumer side with style overrides applied to `DialogSurface`.
