### ISSUE TITLE
[Bug]: The SearchBox shows autocomplete even in Edge

### ISSUE THREAD

**Issue by mkokabi** [microsoft/fluentui#28618]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1270P
    Memory: 9.35 GB / 31.24 GB
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/mkokabi/pen/RwqBdZz

## Actual Behavior
The SearchBox shows browser AutoComplete

## Expected Behavior
The SearchBox shouldn't shows browser AutoComplete

## Additional context
This issue was reported https://github.com/microsoft/fluentui/issues/9311 but the ticket was closed because [it was said ](https://github.com/microsoft/fluentui/issues/9311#issuecomment-498362689) that it is a Chrome issue. But it's easy to reproduce the issue in the Edge. 

## Reproduction
Just try the samples provided https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox in CodePen in Edge. First time you open this sample in CodePen provide a value, Close the tab and click on the same link in the sample and when it showed the searchbox click in the textarea and it would pop up a autocomplete.
![Screenshot 2023-07-24 061155](https://github.com/microsoft/fluentui/assets/2146505/fcbc6bd0-59ee-4dc9-a7cd-b3f0b86c4f51)

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@mkokabi I'm unable to repro the error in the latest Chrome and Edge browsers, can you confirm if this is still an issue?
