### ISSUE TITLE
[Bug]: Field validationMessage can't be dynamically set

### ISSUE THREAD

**Issue by NoisyMonk** [microsoft/fluentui#28627]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 11.33 GB / 31.79 GB
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/stupefied-bas-k7h9ql?file=/example.tsx

## Actual Behavior
Dynamically changing the validationMessage value doesn't update the displayed message.

## Expected Behavior
When the validationMessage is dynamically changed it should be rendered.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by pradeept95** [comment]
In order to re-render in react, isn't this how you suppose to do?

https://codesandbox.io/s/compassionate-breeze-zqjv46?file=/example.tsx
