### ISSUE TITLE
[Investigate] react-tree:  toolbar for actions & context menu

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/fluentui#28646]
Currently, the mechanism for utilizing `actions` from a tree item is not well defined.

1. There's an irregular amount of tabbing you can do, which might lead to some confusion for screen readers users.
2. There's no context menu available that would allow a screen reader user to opt out entirely of the usage of `actions`

As a possible solution I'm proposing to investigate the usage of a `toolbar` widget in place of the `actions` to ensure a single tab stop is determined and narration is properly provided, as well as horizontal arrow navigation, and for the context menu problem, it would be nice to have that well documented somehow.

## Tasks:

- [x] converts actions to be role `toolbar` - https://github.com/microsoft/fluentui/pull/28719
- [ ] stories to stress the importance of context menu with actions

**Comment by sopranopillow** [comment]
@bsunderhus looks like this one is marked as done, should we close it?
