### ISSUE TITLE
[Feature]: Provide a way to extract a physical theme token value from a component

### ISSUE THREAD

**Issue by RoystonS** [microsoft/fluentui#28652]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

I can't currently find a (supported) way to identify the value of a theme token at a particular point in a component hierarchy. Obviously, in the vast majority of cases, we should just use the tokens, which correspond to CSS variables.

BUT there are a few cases where having access to the actual physical colours/values for the tokens for the current theme is necessary. For instance, using HTML Canvas or WebGL, or other external UI components such as maps. A lot of these features don't cope with CSS variables, so using them requires access to the current physical token for a theme.

Alternatives considered:
* I know I could use `useContext(ThemeContext_unstable)` but that's clearly an unsupported API which may go away.
* I could pass the theme down through the React tree using my own parallel context, but I'd be duplicating the contextual work that `FluentProvider` already does, and risking forgetting to use my provider if I need to use `FluentProvider` in a nested manner. Also, `FluentProvider` does theme merging between the parent theme and child theme, and I don't really want to duplicate that work either.

A nice simple approach would be to expose a hook that either exposes the whole current merged theme as an object, or takes the name of a token and extracts that value from the current merged theme.

I'm aware that there was a `useTheme` hook previously, but that was removed in #20482.  That issue argues that there were only 2 use cases for the previous API (internal use and theme extension), but interfacing with external APIs that can't cope with CSS variables is another use case.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by miroslavstastny** [comment]
Thanks for the feedback, this sounds like a reasonable requirement. We currently do not plan to implement this, but let's track the incoming requests.
