### ISSUE TITLE
[Bug]: In PeoplePicker, can not use arrow keys to move cursor around

### ISSUE THREAD

**Issue by rayhong118** [microsoft/fluentui#28655]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 28.25 GB / 47.71 GB
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.86)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker

## Actual Behavior
In the input box of PeoplePicker, after typing something, pressing left or right arrow key clears the typed content. 
However, if backspece has been used to delete characters, then pressing left or right arrow key does not clear typed content and correctly moves cursor to the left / right.

## Expected Behavior
User should be able to use arrow key to move cursor around within input box. 

### Requested priority

Low

### Products/sites affected

PowerApps

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by azizChebbi** [comment]
@rayhong118 are you working on this bug ?
If you are not, then can I take it ?

**Comment by rayhong118** [comment]
> @rayhong118 are you working on this bug ? If you are not, then can I take it ?

No I'm not working on this one.

**Comment by azizChebbi** [comment]
can I get assigned to fix this bug ?

**Comment by sopranopillow** [comment]
Hi @azizChebbi, if you're still interested in this bug, I'll assign it to you for now.

**Comment by azizChebbi** [comment]
working on it...
