### ISSUE TITLE
[Bug]: Text in dropdown box and dropdown list wraps when overflows

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#28659]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components 9.27.1 (Using CodeSandbox)
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/fluent-ui-v9-dropdown-overflow-pzqlvg?file=/example.tsx

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/50703224/2e522e5d-5aa5-4011-950e-758f3c61fc9f)
![image](https://github.com/microsoft/fluentui/assets/50703224/fb37da00-2951-4be4-b8db-df6c39df105d)
![Recording_20230727T205955](https://github.com/microsoft/fluentui/assets/50703224/259aace8-bec2-425a-808e-acaae2e4041e)

## Expected Behavior
I expect something just like plain-old Fluent UI v8.

![image](https://github.com/microsoft/fluentui/assets/50703224/930e7f83-56af-4f88-b897-52fbf2628d5e)
![Recording_20230727T210734](https://github.com/microsoft/fluentui/assets/50703224/fcfe9b5b-e163-4d96-a0ba-65feed34199f)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by omlondhe** [comment]
May I work on this one?
