### ISSUE TITLE
[Bug]: Menu does not overflow vertically

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#28679]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components v9.27.1
(Using CodeSandbox)
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/fluent-ui-v9-menu-vertical-overflow-7hdl86?file=/example.tsx

## Actual Behavior
The popup menu extends the browser document vertically, and the menu may get clipped if we apply `overflow: hidden` style to the document.

![Recording_20230731T161734](https://github.com/microsoft/fluentui/assets/50703224/12fd7763-2063-4c49-be03-e31314b7d4b3)

## Expected Behavior
The popup menu itself could be scrollable.

This is what I see in Fluent UI v8:

![Recording_20230731T161941](https://github.com/microsoft/fluentui/assets/50703224/c409be29-2fb5-4463-8469-04db91da56e9)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
This can be done using the `autoSize` option when configuring positioning https://codesandbox.io/s/fluent-ui-v9-menu-vertical-overflow-forked-q6pnt9?file=/example.tsx

**Comment by chenxinyanc** [comment]
> This can be done using the `autoSize` option when configuring positioning https://codesandbox.io/s/fluent-ui-v9-menu-vertical-overflow-forked-q6pnt9?file=/example.tsx

Thanks for the tip! However, why isn't this behavior the default menu behavior?
