### ISSUE TITLE
[Bug]: animationIterationCount: 'infinite' should not be used for loading components.

### ISSUE THREAD

**Issue by zbogard** [microsoft/fluentui#28673]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Not relevant.
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/

### Bug Description

Animations set to run infinitely can have a significant impact on performance, especially on devices with limited processing power or older hardware. Continuous animations can consume a lot of CPU and GPU resources, leading to slower page rendering, increased battery drain on mobile devices, and potential overheating on low-end devices.

## Actual Behavior
The Fluent v9 Spinner, Loader, and Shimmer components all use `animationIterationCount: 'infinite'` as a style.
## Expected Behavior
The Fluent v9 Spinner, Loader, and Shimmer components should use a more reasonable `animationIterationCount` that's equivalent to approximately 1 minute. 

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Stopping indeterminate animations like spinner, loader and shimmer ("the indicator"), in the Fluent layer, is probably not the correct action to take here. My feeling is that users will expect these indeterminate indicators to animate indefinitely.

As a user, if an operation is taking some unknown amount of time my expectation is that the indicator will continue to animate the entire time. If the animation stops after some amount of time I'd likely interpret that as the application being broken. That said, if the animation just spins for 1 minute+ I'd likely also interpret that as a broken application :)

One minute feels both arbitrary and like a really long time for an indeterminate indicator. If an application expects loading scenarios that are on this time scale perhaps a better solution is for the application to take a more active role in the loading visuals. Roughly something like:

1. Display indicator with "loading..." label
2. 30s later, remove indicator, set label to "still working..."
3. 15s later, bring back indicator, set label to "sorry it's taking so long..."
4. and so on.

The idea being that, for long running loading scenarios, the indicator isn't only the animation but other visual updates that could help alleviate performance concerns (particularly on low end devices).

---

Today it's possible for users to control `animation-iteration-count` with custom styles.

[Example](https://codesandbox.io/s/custom-styles-for-animation-iteration-f5ls3f?file=/example.tsx)

While certainly not the most elegant API, this can be used to achieve the requested outcome.

---

With all the above said, performance and battery life are important concerns that we should consider when implementing components. Do you have any data that shows how these animations affect these metrics? What other approaches could we take for these indicators other than just stopping them after set amount of time?
