### ISSUE TITLE
[Bug]: Update minified css file @charset at-rule

### ISSUE THREAD

**Issue by tudorpopams** [microsoft/fluentui#28674]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

The [currently minified fabric.min.css file](https://www.npmjs.com/package/@fluentui/react?activeTab=code) does not specify the `@charset` at-rule correctly based on the official documentation ([one](https://developer.mozilla.org/en-US/docs/Web/CSS/@charset#examples), [two](https://www.w3.org/International/questions/qa-css-charset)). This is causing issues for some of our icons, as specified in #27777 .

![image](https://github.com/microsoft/fluentui/assets/97875118/2f879d0e-f448-4a05-99bb-e1c973582a1c)

### Have you discussed this feature with our team

@justslone, @jurokapsiar

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by marcosmoura** [comment]
I couldn't find the fix for it yet. I planned the fix for the next iteration.
