### ISSUE TITLE
[Bug]: [Re-open] <MenuItem> text overflow behavior is weird and inconsistent

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#28680]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components: v9.27.1
(Using CodeSandbox)
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/menu-overflow-behavior-8itymw?file=/example.tsx

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/50703224/0ba35570-e6a2-4033-add9-40174e7ec351)

## Expected Behavior
I'm not sure whether the menu should be extended horizontally, or the menu content should be trimmed, but at least the menu content shouldn't brim out of the menu border or get wrapped to a second line.

In Fluent UI v8, the menu gets extended horizontally automatically if the text is too long.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chenxinyanc** [comment]
Re-opened from #24297 as it was closed without follow-up.

**Comment by ling1726** [comment]
The max width set is according to design guidance that Menus should not be larger than 300px

![image](https://github.com/microsoft/fluentui/assets/20744592/6a7f8739-3781-4ec7-b537-b59b45e1308a)

We are planning a task to add automatic text overflow ellipsis to larger MenuItem content. Users can still always override the styles if necessary

**Comment by chenxinyanc** [comment]
> The current plan is to grow menu horizontally, until it reaches max width 300px, and then grow it vertically to fit the content.

Thanks! Does it also properly trim/ellipsis the text if there is no chance for line breaking (like the `A_Very_Long_Menu_Item_With_No_Space_In_Between` item I've mentioned in the example)?
