### ISSUE TITLE
[Bug]: @fluentui/react-conformance and @fluentui/react-conformance-griffel use ReactDOM.render that is not supported in React 18

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/fluentui#28702]
### Library

@fluentui/react-conformance 
@fluentui/react-conformance-griffel

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.97 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.6
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/vhuseinova-msft/react18-fluentui-v9-tests

## Steps to reproduce:
1. download the app
2. `npm i`
3. `npm test`

## Actual Behavior
@fluentui/react-conformance and @fluentui/react-conformance-griffel use ReactDOM.render functionality that is no longer supported in React 18. The warnings about this issue are posted in console.

## Expected Behavior
@fluentui/react-conformance and @fluentui/react-conformance-griffel tests can be run without warnings for React 18.

### Logs

```shell
console.error
    Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

### Requested priority

Normal

### Products/sites affected

https://github.com/Azure/communication-ui-library

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hi @vhuseinova-msft, currently we fully support React 17, but have made any necessary changes to support React 18. From this we created a package to test React 18 #23807, but until we move completely to React 18, conformance tests should stay in React 17.
