### ISSUE TITLE
[Bug]:  Missing colors in Fluent v9

### ISSUE THREAD

**Issue by agetmanchuk2** [microsoft/fluentui#28703]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Missing colors in Fluent v9 (ex. colorPaletteLightTealBackground1)

Need:
- colorPaletteLightTealBackground1
- colorPaletteLightTealForeground1

at least
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/nervous-dew-qw37sl?file=/example.tsx:0-705

## Actual Behavior
colorPaletteLightTealBackground1 DOES NOT exist on tokens

## Expected Behavior
colorPaletteLightTealBackground1 exists on tokens

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hi @agetmanchuk2, looking at our design tokens in Figma, we do not have any colorPaletteLightTealBackground1. would you mind pointing me where the version 1 comes from?

**Comment by sopranopillow** [comment]
We currently only support
- colorPaletteLightTealBackground2
- colorPaletteLightTealForeground2

Since there's no mention of the {token}1 in our design spec, I'll close this.
