### ISSUE TITLE
[Bug]: Can't set dropdown width

### ISSUE THREAD

**Issue by ThomasPe** [microsoft/fluentui#28710]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components: ^9.27.3 => 9.27.3
@fluentui/react-datepicker-compat: ^0.2.4 => 0.2.4
@fluentui/react-icons: ^2.0.209 => 2.0.209
```

### Are you reporting Accessibility issue?

no

### Reproduction

~https://codesandbox.io/s/youthful-ives-vfq2cg?file=/example.tsx~
Updated CSB with new dependency (code is the same): https://codesandbox.io/s/determined-sky-k2yvnk?file=/example.tsx

## Actual Behavior
ignores width set via makeStyle

## Expected Behavior
would expect same behavior as Select
https://codesandbox.io/s/blissful-davinci-jmnyrj?file=/example.tsx:168-258

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by pradeept95** [comment]
It seems min-width is set default to 250px, so that you need to override the min-with for your dropdown.

![image](https://github.com/microsoft/fluentui/assets/28040299/10f64b49-bd25-4a88-b695-efbdb8d70276)


Here is the working example!

https://codesandbox.io/s/fervent-khorana-nrmj5z?file=/example.tsx

**Comment by spmonahan** [comment]
I think @pradeept95 's example covers this. Does that work for you @ThomasPe ?

**Comment by ThomasPe** [comment]
Yes this works, thanks.
Only issue is that the listbox popup also tries to take that smaller width (which I guess is the reason for the min-width in the first place?).
Is it possible to override that with a custom width? I'd like to show additional information for each option while the option names themselves are quite short.

![image](https://github.com/microsoft/fluentui/assets/4225039/a4a5bc14-19ad-461b-8aab-42b5528cdc47)

**Comment by spmonahan** [comment]
> Is it possible to override that with a custom width?

You should be able to do that as the `listbox` is a slot. [Here's the docs on how to customize components with slots](https://react.fluentui.dev/?path=/docs/concepts-developer-customizing-components-with-slots--page).

Let me know if you have any questions.

**Comment by ThomasPe** [comment]
yes, was able to pass a class and fix it that way. much appreciated, you all are doing a great job with this library! ♥️
