### ISSUE TITLE
[Bug]: DatePicker localized shortMonth strings not reflected in display

### ISSUE THREAD

**Issue by hopewelchmicrosoft** [microsoft/fluentui#28716]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://aka.ms/fluentpen

### Bug Description

Context: In order to override English in the DatePicker, [the `strings` prop must be defined. ](https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker#best-practices:~:text=The%20control%20provides%20English%20strings%20by%20default.%20For%20localized%20apps%2C%20you%20must%20override%20these%20using%20the%20strings%20prop.)

## Actual Behavior
The `shortMonths` array in the JSON string we pass to the `strings` prop is fully defined with the Spanish month names. However, the box with the selected date still displays the English abbreviated month, as seen in this screenshot:
![for-fluentui-shortmonths-missing-abbrev-days](https://github.com/microsoft/fluentui/assets/135391843/3710be14-a02c-47cc-9623-f1b0f33f2826)

Additionally, there is no way to override English abbreviated weekdays (Sun, Mon, Tue, Wed, Thu, Fri, Sat) in this `strings` prop. So, the yellow highlighted text in the screenshot is: "Thu Aug 10 2023", completely in English.

This also happens in an isolated environment like Code Pen: https://codepen.io/hopewelchmicrosoft/pen/rNQPpjW

## Expected Behavior
The yellow highlighted text on the webpage should be "Jue Ago 10 2023" , completely in Spanish according to the `strings` prop in the example screenshot.
There should be a way to define abbreviated weekdays and override the default English versions.

### Requested priority

High

### Products/sites affected

https://portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/0f3dcfc3-18f8-4099-b381-8353e19d43a7/resourceGroups/hope-rg1/providers/Microsoft.DataShare/accounts/hope-test-share-A/sentshares

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Looking into it, for the textfield text you could add a formatting function to handle the strings you're providing like this: https://codepen.io/sopranopillow/pen/bGOVKNd?editors=0010.

**Comment by sopranopillow** [comment]
I think that would be the right way to go, let me know if you have any questions.

**Comment by hopewelchmicrosoft** [comment]
@sopranopillow thank you very much! The only possible issue with that solution that I can see is calling those datePicker strings directly. With the way localization works in our code, directly accessing those values might skip the localization part and still display english anyways.

I will try this solution and get back you either way!

**Comment by sopranopillow** [comment]
Sounds good, I'll add soft close for now, but if you have any other questions feel free to reopen the issue

**Comment by hopewelchmicrosoft** [comment]
@sopranopillow  The format function solution works great, there were no problems! Thanks again for your help! Can this issue remain in Soft Close for a little longer? I'd like to confirm everything works in prod before officially closing, and the release process takes a few weeks.

**Comment by sopranopillow** [comment]
The bot should close it after some time!
