### ISSUE TITLE
[Bug]:  PeoplePicker doesn't allow loading more suggestions

### ISSUE THREAD

**Issue by xinding1121** [microsoft/fluentui#28721]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 1.33 GB / 15.71 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/Xin-Ding/pen/jOQdQJR

## Actual Behavior

**Note: The repro link above cannot show this issue, since fluentpen doesn't have type check so adding extra props is allowed. I added it to submit this issue.**

PeoplePicker doesn't allow users to configure "moreSuggestionsAvailable" attribute, so "load more suggestions" function doesn't work.

I am using PeoplePicker and I need the 'load more suggestions' function since we can have a quite long user list provided by an API that requires pagination params. But PeoplePicker's pickerSuggestionsProps doesn't allow us to configure "moreSuggestionsAvailable", even though searchForMoreText and onGetMoreResults exist(https://github.com/microsoft/fluentui/blob/4b802ba3745dde01c68224329c1414f077faa1db/packages/react/src/components/pickers/Suggestions/Suggestions.tsx#L203). Its type is boolean and its value is undefined by default so works the same as false. That makes the "load more suggestions" function hidden. 

In the IBasePickerSuggestionsProps, moreSuggestionsAvailable hasn't been picked from ISuggestionsProps.
https://github.com/microsoft/fluentui/blob/4b802ba3745dde01c68224329c1414f077faa1db/packages/react/src/components/pickers/BasePicker.types.ts#L257

This issue is similar to an old one: https://github.com/microsoft/fluentui/issues/6582

## Expected Behavior
PeoplePicker allows setting moreSuggestionsAvailable = true

We've received an incident saying a customer reported they couldn't see all their users in the suggestions of the picker on our website. Could you please support it? Thanks.

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Based on [the conversation in 6582](https://github.com/microsoft/fluentui/issues/6582#issuecomment-429033181) it seems there was consensus to implement this change a while back but the work was never done.

@xinding1121 you indicated you'd be willing to open a PR for this change. Is that still the case? Happy to help that along!
