### ISSUE TITLE
unnecessary peer dependency of @fluentui/react-charting

### ISSUE THREAD

**Issue by NewFuture** [microsoft/fluentui#28742]
https://github.com/microsoft/fluentui/blob/253798f25326e92ba19b313c47a9c9530af12526/packages/react-charting/package.json#L68C9-L68C9

```
 @fluentui/react-charting@5.16.57" has incorrect peer dependency "@testing-library/react@12.1.2"
```
I think the developers who use the charting do not need to install `@testing-library/react@12.1.2`.

Did we put it in a wrong place?

**Comment by insaneinside** [comment]
See also #28683 -- same issue.

**Comment by NewFuture** [comment]
track it #28683
