### ISSUE TITLE
[Bug]: Expression produces a union type that is too complex to represent. ts(2590)

### ISSUE THREAD

**Issue by chandpravandan** [microsoft/fluentui#28744]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Using "@fluentui/react-components": "^9.19.0", but this repro's on "9.27.0" as well.
```

### Are you reporting Accessibility issue?

None

### Reproduction

`Note - Please replace SomeFluentIcon with a FluentIcon.`

```
<Combobox
        input={{
          children: (Element, props) => (
            <div>
              <SomeFluentIcon />
              {/** Error is on the below line */}
              <Element {...props} />
            </div>
          )
        }}
      >
    
    <Option>
        choice 1
    </Option>

    <Option>
        choice 2
    </Option>

</Combobox>
```

## Actual Behavior

A sample snippet of the code where this error repro's

Note - Please replace `SomeFluentIcon` with a FluentIcon.

```
<Combobox
        input={{
          children: (Element, props) => (
            <div>
              <SomeFluentIcon />
              {/** Error is on the below line */}
              <Element {...props} />
            </div>
          )
        }}
      >
    
    <Option>
        choice 1
    </Option>

    <Option>
        choice 2
    </Option>

</Combobox>

```

This above code while building results in error - "Expression produces a union type that is too complex to represent. ts(2590)"

## Expected Behavior

The error "Expression produces a union type that is too complex to represent. ts(2590)" should not appear for the provided code snippet.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
This problem is due to the Element type being resolved to a `<input>` element, which is correct, but the props provided use the type that hasn't been resolved. This is a known issue in our types and we are actively trying to improve our typying system. To get around that you can cast the props type to a resolved input types with `React.HTMLAttributes<HTMLInputElement>` as shown in this cdsbx: https://codesandbox.io/s/youthful-blackburn-wxlj8m?file=/example.tsx
