### ISSUE TITLE
[Bug]: DetailList : State is not updating when onSelectionChanged, need to reload

### ISSUE THREAD

**Issue by matieydjato** [microsoft/fluentui#28756]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
NPM Install
```

### Are you reporting Accessibility issue?

None

### Reproduction

ok

## Actual Behavior

The state is not being updated inside the onSelectionChanged function

`const handleSelectionChange = useCallback((selection,selectionItem,isItemSelected) => {   
    if (timeSeriesType===TimeSeriesTypes.DEFAULT && !isDetailViewEdit) { // isDetailViewEdit state value is not updating
      selectionForDefault(selection)
    }
    // Add Calculation Variable When use click the item
    if(timeSeriesType===TimeSeriesTypes.CALCULATION || isDetailViewEdit){
      selectionForCalculation(selectionItem,isItemSelected);
    }
  }, [isDetailViewEdit, timeSeriesType,selectionForCalculation,selectionForDefault]);
`
` <DetailsList
            items={items}
            compact={isCompactMode}
            columns={columns}
            selectionMode={SelectionMode.none}
            layoutMode={DetailsListLayoutMode.justified}
            isHeaderVisible={true}
            onSelectionChanged={handleSelectionChange}
/>`
## Expected Behavior

Update the state when the selection changes

### Requested priority

Normal

### Products/sites affected

no

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hi @matieydjato, could you provide a codesandbox with a repro? aka.ms/fluentpen
