### ISSUE TITLE
[Feature]: Imrpove Office UI Fabric Icons 

### ISSUE THREAD

**Issue by SiemvandenBerg** [microsoft/fluentui#28772]
### Library

Web Components (@fluentui/web-components)

### Describe the feature that you would like added

This website: [https://uifabricicons.azurewebsites.net/](https://uifabricicons.azurewebsites.net/)

It's the only thing I use from Fluent UI, and I use it a lot.

Why is still called Fabric icons? 

You can download the icon font via [links](https://developer.microsoft.com/en-us/fluentui#/resources). This way you can copy glyps and paste them into a text field in a design program. 
But every now and then the glyph is not recognized in the icon font. I think the font and the icons on display are not the same version. (for example 'OfficeChatSolid')

Searching for icons is problematic because it only looks in the name of the icon which isn't always useful. (For example: 'Ringer' is such a weird name for a bell, notification icon.)

It would be great to be able to copy a glyph with a single click.

In general I would greatly appreciate if this website gets a few QOL upgrades.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by chrisdholt** [comment]
Not WC related, removing automatic assignment

**Comment by SiemvandenBerg** [comment]
> Not WC related, removing automatic assignment.

Not sure what this was supposed to fall under but it is a valid concern. I was hoping @Jahnp would be able to shed some light on it. I understand my report comes off as short, and that this is probably a passion project of sorts. I'm just voicing these opinions.

**Comment by chrisdholt** [comment]
> > Not WC related, removing automatic assignment.
> 
> Not sure what this was supposed to fall under but it is a valid concern. I was hoping @Jahnp would be able to shed some light on it. I understand my report comes off as short, and that this is probably a passion project of sorts. I'm just voicing these opinions.

@SiemvandenBerg - No worries, my comment above was because I was modifying the labels and assignment which was automated based on the "web-component" string in your issue. I wanted to make sure this doesn't get assigned to the wrong person and go unnoticed. @JustSlone as FYI :)
