### ISSUE TITLE
In PeoplePicker, load more functionality has bug

### ISSUE THREAD

**Issue by darshita1108** [microsoft/fluentui#28779]
### Library

~~React Northstar / v0 (@fluentui/react-northstar)~~ v8

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

None

### Reproduction

Present in KnowledgeManagementWizard in mac

## Actual Behavior

I am using NormalPeoplePicker and the API I am using returns results in pages. I need to implement a "load more" functionality to fetch all the pages from the API. However, after the first call to 'onGetMoreResults', the load more button disappears. 

## Expected Behavior
The 'Load more' button should be visible until there are no further calls

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@darshita1108 We will need an isolated reproduction example since there's not much we can do to assist without one.
