### ISSUE TITLE
[Bug]: V9 Tooltip should have stopPropagation and preventDefault as options

### ISSUE THREAD

**Issue by tejohans** [microsoft/fluentui#28789]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (20) x64 Intel(R) Core(TM) i9-9900X CPU @ 3.50GHz
    Memory: 11.77 GB / 31.71 GB
  Browsers:
    Chrome: 115.0.5790.171
    Edge: Spartan (44.22621.2129.0), Chromium (113.0.1774.57), ChromiumDev (115.0.1880.3)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://jsfiddle.net/wehtjbz8/

## Actual Behavior
When a tooltip is triggered, and document.activeElement is an input element of type="search", clicking Escape will clear the text of the input field, without the input field having a chance to preventDefault.

## Expected Behavior
The tooltip should not make it impossible to propagate the _keydown_ event to the active element in the page when clicking escape. Since previous issues have shown that the oposite is required, I would consider taking in the behaviour as an optional flags. 

## Related issues and commits:
https://github.com/microsoft/fluentui/issues/24800
https://github.com/microsoft/fluentui/commit/81de40f0df0dfa8bac4e4fb522bf830d9fe8e066#diff-bc9f39e43e65813fb32b3f8d22743fdcb84fee688bb5c3d960b36b268f8721cf

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
From the offline conversation:

> The first <kbd>Escape</kbd> press should close a tooltip itself. This requirement can be achieved only with `stopPropagation()` (like it was done in #24800). Making this optional breaks the accessibility requirement.
>
> For `.preventDefault()` it's a bit tricky as Tooltip does not expose that event in its callback.

---

It might be reasonable to expose the matching DOM event in `onVisibleChange()` callback, so consumers would be able to control the component's behavior, for example:

```ts
<Tooltip
  onVisibleChange={(ev, data) => {
    if (!data.open && ev.key === 'Escape') {
      e.preventDefault()
    }
  }}
/>
```

**Comment by behowell** [comment]
Hi @tejohans, with PR https://github.com/microsoft/fluentui/pull/28951, it is possible to prevent default of the keyboard event like @layershifter's example, but with one change. The keyboard event is passed in as `data.documentKeyboardEvent` rather than in the `ev` argument. This was necessary because changing the type of the `ev` argument would be a breaking change.

So the example would look something like this:

```jsx
<Tooltip
  onVisibleChange={(_ev, data) => {
    if (!data.open && data.documentKeyboardEvent?.key === 'Escape') {
      e.preventDefault();
    }
  }}
/>
```
