### ISSUE TITLE
[Bug]: Filterable Combobox does not function properly (at all) with screen readers

### ISSUE THREAD

**Issue by stevencomsft** [microsoft/fluentui#28793]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.23516
    CPU: (20) x64 Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
    Memory: 12.94 GB / 31.72 GB
Browsers:
    Edge: Spartan (44.23516.1000.0), Chromium (116.0.1938.36)
    Internet Explorer: 11.0.23516.1000
```

### Are you reporting Accessibility issue?

yes

### Reproduction

~https://codesandbox.io/s/laughing-microservice-73ycvw~
Update: https://codesandbox.io/s/dazzling-lumiere-vvkt9z

Added a new required dep to the CSB, code is same

## Actual Behavior
With Windows Narrator on, the Fluent v9 Combobox (in filterable mode) does not react to:

- Arrow keys up/down to navigate through the list of options
    - Pressing either arrow key causes the options list to blur and close, making it impossible to select an options
- Pressing enter on the ChevronDown icon in the combobox to open the list of options
    - In the scenarios where the focus passes from the input to the chevron icon, pressing "Enter" key does nothing
- Typing to search/filter for options
    - Currently you can type a single letter before the input begins intercepting the events and prevents you from typing more or backspacing/deleting

## Expected Behavior
- Arrow keys should function as normal with Narrator on otherwise users of screen readers will not be able to use Combobox
- Pressing enter on the ChevronDown should always open the options list, or it should be aria-hidden
- Typing to search/filter options in the Combobox should always function and it should be possible to backspace/delete as well

## Note
- The above CodeSandbox is the existing default code sandbox in the Fluent v9 Combobox docs, here, under "Filtering":
https://react.fluentui.dev/?path=/docs/components-combobox--default#filtering
- It's also worth noting that this reproduces for more than just the "Filtering" example. 

## Important
- If it helps with debugging this issue, I have noticed that if you tab to the Combobox, press Enter to open it, then immediately press Enter to re-select the currently selected item, then press Enter to open the Combobox again, that arrow keys work as expected. My guess is that there is something funky with the registration of Tabster in the options list or that there is something intercepting all key events until an item is "selected". 
    - However, this "workaround" does not make the other noted items work as expected. Only Arrow keys. 
- This is a pretty severe A11y bug that will make it very difficult to continue adoption of the Combobox going forward

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by marcinkiewicz** [comment]
Upvoting the issue.

**Comment by spmonahan** [comment]
I've verified the reported issues using Windows 11 Narrator and Edge. However, I will note that I'm not an expert Narrator user so I'm unaware of what Narrator users will expect in this case. That said, I agree these are bugs.

My triage notes:

> Arrow keys should function as normal with Narrator on otherwise users of screen readers will not be able to use Combobox

`alt + arrow` allows navigation. Not sure if this is expected Narrator behavior or not. I can confirm that `arrow` alone does not allow list navigation.

> Pressing enter on the ChevronDown icon in the combobox to open the list of options
In the scenarios where the focus passes from the input to the chevron icon, pressing "Enter" key does nothing

Can repro, though I am also able to open the listbox via the Enter key on the chevron at times.

> Typing to search/filter for options
Currently you can type a single letter before the input begins intercepting the events and prevents you from typing more or backspacing/deleting

Can repro this.

@stevencomsft Can you confirm that would tested on Windows 10? Also, which browser did you test with?

**Comment by smhigley** [comment]
@stevencomsft I actually can't reproduce this issue, using Narrator as expected in a combobox. From a quick read, this sounds like behavior you'd encounter when switching into scan mode -- could you confirm that this is something you're experiencing while Narrator is in application mode?
