### ISSUE TITLE
[Docs]: ContextualMenu prop delayUpdateFocusOnHover is not clearly described in the docs

### ISSUE THREAD

**Issue by Stan-Stani** [microsoft/fluentui#28795]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 31.04 GB / 63.67 GB
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.200)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A

### Bug Description

The conversation in #17035 demonstrates that the description of `delayUpdateFocusOnHover` in the [documentation ](https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu#implementation) does not clearly explain the function of the prop:
"If true, the contextual menu will not be updated until focus enters the menu via other means. This will only result in different behavior when shouldFocusOnMount = false."

@joschect clarifies that the prop is used to prevent the contextual menu items from capturing focus automatically.

### Requested priority

Low

### Are you willing to submit a PR to fix?

yes

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@Stan-Stani, clarifying this point in the docs make sense to me. How do you propose we update the docs?

**Comment by Stan-Stani** [comment]
Great! Let me think on it.

**Comment by Stan-Stani** [comment]
I guess I don't fully understand what is meant by "will not be updated."

I would change it to:
