### ISSUE TITLE
[Bug?]: `resolveShorthand` should ignore function as a value

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/fluentui#28807]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-uititlites 9.11.0
```

### Are you reporting Accessibility issue?

None

## Behavior in @fluentui/react-utilties 9.10.1 and before
When user passes a function in `resolveShorthand`, it is ignored because of the logic below:
```ts
  if (typeof value === 'string' || typeof value === 'number' || Array.isArray(value) || isValidElement<any>(value)) {
    resolvedShorthand.children = value;
  } else if (typeof value === 'object') {
    resolvedShorthand = value;
  }
```
https://github.com/microsoft/fluentui/blob/f9425b245b88f58dedcb21cd81384186b3153901/packages/react-components/react-utilities/src/compose/resolveShorthand.ts#L33

So when someone does `<Button icon={someFunction as any} />`, there is no warnings because this is is considered as `<Button icon={{}} />`

## Behavior in @fluentui/react-utilties 9.11.0 
When user passes a function, it is used as is:
```ts
  if (
    typeof value === 'string' ||
    typeof value === 'number' ||
    Array.isArray(value) ||
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    React.isValidElement<any>(value)
  ) {
    return { children: value } as Props;
  }

  return value;
``` 
https://github.com/microsoft/fluentui/blob/5d0670b556b7958645c9d5e2685f7d39321de91d/packages/react-components/react-utilities/src/compose/slot.ts#L85

So when someone does `<Button icon={someFunction as any} />`, `someFunction` is resolved to an object and passed to the icon slot, which can lead to console error `Warning: React does not recognize the xxx prop on a 
DOM element`

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by YuanboXue-Amber** [comment]
cc @bsunderhus I think this "bug" become visible to us due to error in usage. The new behavior, even though different from the old behavior, feels correct to me

**Comment by layershifter** [comment]
As was proposed by @YuanboXue-Amber and @bsunderhus, we should emit our own warning in this case.
