### ISSUE TITLE
[Bug]: Button doesn't respect JSS styles passed through classnames.

### ISSUE THREAD

**Issue by karthicrajakumar** [microsoft/fluentui#28802]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 31.68 GB / 63.95 GB
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.200)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/optimistic-babycat-xqmdtm?file=/example.tsx

## Actual Behavior
Classname with styles passed from shims or the actual v9 <Button> is not respected, meaning we can only override through the makeStyles function.

This will make it hard to go and fix all our v8 implementations to migrate from jss to makestyles.

This seems to be fixable when if we assign the user defined class name first in the order here - 
https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-button/src/components/Button/useButtonStyles.styles.ts
![image](https://github.com/microsoft/fluentui/assets/10362009/215abd42-af24-4d9d-8ee0-e2378c315f9c)

## Expected Behavior
JSS classnames should be respected in the shims.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by karthicrajakumar** [comment]
any concers/suggestions for addressing this issue?

**Comment by layershifter** [comment]
You mentioned JSS, but you're using `merge-styles` in your sandbox, that's a bit confusing.

---

Anyway, the recipe for JSS might be a bit different, but the idea is the same, you need to control the order of insertion. Both v8 and v9 have APIs to do this.

> Note: this change will affect all your styles in the app.

As v8 does not have flexible API, I will fallback to the usage of "placeholder element":

```diff
// index.html

    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />

+    <style data-griffel-placeholder="true"></style>
+    <style data-merge-styles="placeholder"></style>

    <title>React App</title>
```

And then configure Griffel to use that element as an insertion point:

```ts
// App.tsx

const renderer = createDOMRenderer(document, {
  insertionPoint: document.querySelector("style[data-griffel-placeholder]")
});

function App() {
  return <RendererProvider renderer={renderer} />
}
```

- https://griffel.js.org/react/api/create-dom-renderer#insertionpoint
- https://codesandbox.io/s/busy-wozniak-j8xgzp?file=/src/App.tsx
