### ISSUE TITLE
[Bug]: Is there any option to highlight the filter text in suggestions of Tag picker.

### ISSUE THREAD

**Issue by bhanu345-cmd** [microsoft/fluentui#28841]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
React:^18.0.0
@fluent/React:^8.109.0
```

### Are you reporting Accessibility issue?

None

### Reproduction

-

### Bug Description

Search text is not getting highlighted in suggestions.

It would be good if we able to high light the search Text in suggestion items

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Can you add a reproduction please? I'm not able to dig into the issue without one.
