### ISSUE TITLE
[Bug]: Not able to scroll to items present in office-ui-fabric-react Dropdown only for iOS devices(not happening for android/desktop)

### ISSUE THREAD

**Issue by JitMajumder007** [microsoft/fluentui#28900]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
iOS devices (iPad and iPhone device)
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/ecraig12345/pen/WWMaXy

## Actual Behavior
We have used  Dropdown from office-ui-fabric react having version as ^8.110,13 in our project, there are multiple items present as options of that dropdown. We have designed the CSS class for both desktop site and mobile devices(android, iPad/iPhone). Scrollbar present in the dropdown is perfectly fine for desktop devices(we have checked multiple instances in multiple browsers) and also we can scroll all items in android itself **however we are unable to scroll the items present in the dropdown for iOS devices specifically for iPad device irrespective of their versions.**

We have checked and found that it is not our code issue as it is more likely a bug present for iOS devices (because we are applying same styling for android and iOS device but not sure why this issue is only happening in iOS devices)

## Expected Behavior

We can scroll all items present in the dropdown list in iOS devices as like we can scroll them in other devices(Desktop and android)

### Logs

```shell
None
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
I was not able to repro in both iOS and ipadOS

iOS

https://github.com/microsoft/fluentui/assets/5953191/4a51e74a-dde4-4e6a-8818-c7ec1cab6359

ipadOS

https://github.com/microsoft/fluentui/assets/5953191/e7ee4023-27b2-4d99-b857-62941e38502f
