### ISSUE TITLE
[Feature]: Update @swc/helpers to 0.5.x

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/fluentui#28919]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Currently v9 uses `'@swc/helpers': '^0.4.14'`. In codesandbox it resolves to `0.4.36`. But `@swc/helpers@0.4.36` uses dependency alias, which is not supported by codesandbox. And breaks all our exported codesandbox. PR #28918 temporarily resolves the broken codesandbox issue by pinning `'@swc/helpers': '0.4.14'` in the exported codesandbox. But @swc/helpers are now on 0.5.x. We should update @swc/helpers and remove the temporary version pin in codesandbox.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by ling1726** [comment]
Related codesandbox and swc issues

https://github.com/codesandbox/codesandbox-client/issues/7975
https://github.com/swc-project/swc/issues/7843
