### ISSUE TITLE
[Bug]: Datagrid with selection and without items shows "all selected" in header

### ISSUE THREAD

**Issue by logicaloud** [microsoft/fluentui#28927]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.203)
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/happy-rgb-cqv5kl?file=/example.tsx

## Actual Behavior

A selection list that does not contain any items should not indicate that all items are selected in the header. This may result in the header selection flashing briefly when items are in the process of loading: First the empty list appears as "all selected", then, once items are loaded and listed, the header selection reverts to the unselected state.

![datagrid-no-item-selection](https://github.com/microsoft/fluentui/assets/47704763/cce1368d-4c01-48d5-baf1-2c3a1613a125)

## Expected Behavior

If there are no items in the DataGrid, then the header checkbox should be in the unchecked state.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Agree this is a bug. Made an updated example to toggle items so the behavior is more apparent: https://codesandbox.io/s/datagridheader-select-all-bug-vq9d7r

[I believe this is the bit of code that leads to this behavior](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-table/src/hooks/useTableSelection.ts#L56-L68).
