### ISSUE TITLE
[Feature]: Export `DataGrid` context.

### ISSUE THREAD

**Issue by jvince** [microsoft/fluentui#28944]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Hi,

We need to extend the DataGrid component. The change requires a new render function but the library does not export the `DataGridContextProvider`. Can the `DataGridContextProvider` be exported from the library? For example `Table` exports its `TableContextProvider` [see](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-table/src/index.ts#L93).

Thanks!

Thanks for the great library!

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by sopranopillow** [comment]
sounds reasonable!
