### ISSUE TITLE
Enable selective running of conformance tests that don't require TS info

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/fluentui#28950]
Some tests in @fluentui/react-conformance are for typings and requires `ts.createProgram`. However this can lead to JS out of memory error when @fluentui/react-conformance is used in a large repo. We build re-usable components in a large repo following fluent standard, but we face OOM error and can't run conformance tests. 
Can we build ts program only when we need to run the tests that need it? This way we can run most of the conformance tests in our large repo.

**Comment by sopranopillow** [comment]
Hi @YuanboXue-Amber, is this a feature request? or an issue you created to keep track of?

**Comment by YuanboXue-Amber** [comment]
I'll use this issue as tracking issue for myself to add an option in react-conformance to run test that does not need TS. 
Long-term we probably want to revisit react-conformance instead of just patching options. I'll discuss this with the team and create a new issue if needed.

**Comment by Hotell** [comment]
can you provide examples facing OOM errors ? we mitigated and drastically improved conformance test type execution by implementing  https://github.com/microsoft/fluentui/pull/27664

> Can we build ts program only when we need to run the tests that need it? 

this is great optimization indeed and something that was planned as well. could you please next time bring these topics to v-build syncs ?

in general whole conformance DX isn't the most ergonomic with its current api design as it posses lots of limitations. You can learn more what's planned for future in this epic https://github.com/microsoft/fluentui/issues/27359

ty
