### ISSUE TITLE
[Bug]: Stack in @fluentui/react version 8.101.2 changed to rendering falsy elements instead of returning null causes zeros to render

### ISSUE THREAD

**Issue by ghadnani** [microsoft/fluentui#28970]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
react v. 16
@fluentui/react v. 8.101.2

Stack in @fluentui/react version 8.101.2 changed to rendering falsy elements instead of returning null. 

This change caused many zeroes to appear in Stack's children that were zeroes but consumers were expecting them to be nulled by Stack. 

This is a breaking change on our side as consumers.

Here is a codepen demonstrating the behavior expected in 8.101.1
https://codepen.io/ghadnani/pen/oNJXMBL

And here is a codepen demonstrating the breaking change in 8.101.2
https://codepen.io/ghadnani/pen/mdaJjRw
```

Expected: 
![image](https://github.com/microsoft/fluentui/assets/143042218/32ac07d1-009e-4a19-99c8-188f9eecd709)

Rendered: 
![image](https://github.com/microsoft/fluentui/assets/143042218/b57762e0-8c4e-41e8-bd25-09b1769efad7)

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/ghadnani/pen/mdaJjRw

## Actual Behavior
Zeroes and other falsy elements changed to being rendered by Stack. 

## Expected Behavior
Zeroes and other falsy elements to continue being nulled out by Stack. 

### Requested priority

Normal

### Products/sites affected

AMC (account.microsoft.com)

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
This behavior was initially changed in https://github.com/microsoft/fluentui/pull/25685

**Comment by sopranopillow** [comment]
To give more clarification, this was done so in case you want to render something like a list of numbers where 0 is valid. The previous behavior is actually a bug.
