### ISSUE TITLE
[Feature]: Nested Rows in Data Grid Component

### ISSUE THREAD

**Issue by yyzh6236** [microsoft/fluentui#28987]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

We would like to have nested rows in Data Grid display, which could group rows together and display the child rows expandable like the table below:
<img width="272" alt="image" src="https://github.com/microsoft/fluentui/assets/139863902/ac91dc80-a3ab-4134-9bf9-97ccc76dc1cd">

### Have you discussed this feature with our team

Paul Gildea

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by jurokapsiar** [comment]
this should be covered in a new TreeGrid component, let's work with @paulgildea on the priorities.

**Comment by logicaloud** [comment]
The TreeGrid feature request is here: #28363
