### ISSUE TITLE
Pin @swc/helpers to an exact version before 0.4.36

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/fluentui#28995]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 94.13 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.6
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/Azure/communication-ui-library/tree/vhuseinova/edit-message-styles-fix

### Bug Description

`@swc/helpers` dependency is set to ^0.4.14 which includes 0.4.36 that introduces a new dependency `legacy-swc-helpers: /@swc/helpers@0.4.14`. As discussed in https://github.com/swc-project/swc/issues/7843 by @ling1726, 0.4.10 is recommended to be used before `@swc/helpers` 0.5.*

Steps to reproduce:
- open the link from the Reproduction field
- download the project and navigate to it in Terminal
- `rush update`

## Actual Behavior
Error because of 0.4.36 version of `@swc/helpers`

## Expected Behavior
@fluentui/react-components can be used without issues with dependencies

What tested to fix the issue (didn't help):
- add a dependency @swc/helpers with 0.4.14 version
- add `overrides` to package.json

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
@vhuseinova-msft Can you please provide more details what the exact error is and how to repro it? so we can evaluate the impact there.

There is currently some effort to bypass the 0.4.x problems entirely tracked in #28919

**Comment by vhuseinova-msft** [comment]
Hi @ling1726 , thanks for the reply!

It looks like the initial issue is with rush tool and[ I've created an issues for it](https://github.com/microsoft/rushstack/issues/4298). 

The demo repo can be found [here](https://github.com/vhuseinova-msft/fluentui-components-swc-helpers-demo) and steps to reproduce are:

- download the demo app
- navigate to the demo app folder
- run `rush update`.

There is also a temporary workaround that can be used:
Set a version for @swc/helpers package in globalOverrides in pnpm-config.json

**Comment by vhuseinova-msft** [comment]
The issue is fixed with updating rush version.
