### ISSUE TITLE
[Bug]: SpinButton's spinner is not rendered in the right place

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#29028]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows
  Browsers:
    Edge Chromium: Version 118.0.2070.0
```

### Are you reporting Accessibility issue?

no

### Reproduction

public docsite

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/5953191/d3e1494d-517d-4dba-9c2d-139e7c1c4e5c)

## Expected Behavior
to render the spinner in the right place.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Some quick notes: this does not appear in the current release build of Edge/Chrome (116) but it does appear in the current Canary build (118).

**Comment by spmonahan** [comment]
Since this isn't a bug in the current release (and might be a bug in Chromium) I'll leave this open but won't investigate further.

@sopranopillow Can you look into opening a bug against Chromium and linking it here?

**Comment by sopranopillow** [comment]
Here's the bug report in chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1477350
