### ISSUE TITLE
[Bug]: Clear button does not work for 'Controlled' SearchBox in preview component

### ISSUE THREAD

**Issue by syphe** [microsoft/fluentui#29034]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 10.66 GB / 31.85 GB
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

Can be reproduced from `master`. `yarn start`, select `@fluentui/react-search-preview`, select `SearchBox/Controlled`, enter text and hit the 'X' button.

## Actual Behavior
Text within the search box remains after clicking the 'X'

## Expected Behavior
Text within the search box should be cleared when clicking the 'X'

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by syphe** [comment]
Have added a PR which allows the consumer to control this behaviour, if we want it to be controlled better internally, it would be a bit more work, as would require firing an onChange event or similar, and I couldn't easily find the constructor or simply way to fire off this event so it would be captured like normal

**Comment by FengQiMS** [comment]
I wonder why this action disappear as v8 works well @syphe
