### ISSUE TITLE
[Bug]: Can't render TeachingBubble by adding calloutProps.layerProps normally

### ISSUE THREAD

**Issue by airmelt-ms** [microsoft/fluentui#29048]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 13.60 GB / 31.78 GB
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/Ji-Li/pen/vYvKJdx

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/110365725/177144eb-16b2-419e-b61e-8a7f8a6ecb1b)

![image](https://github.com/microsoft/fluentui/assets/110365725/b24fa237-40d0-4287-91be-95da0d2201d9)

## Expected Behavior
![image](https://github.com/microsoft/fluentui/assets/110365725/9a957a49-5f32-42c0-a54b-fba412f2bbe3)

### Logs

```shell
useful link: https://github.com/microsoft/fluentui/issues/17409
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Looks like something changed between v7 and v8 as this works correctly in 7.x: https://codepen.io/seanms/pen/eYbzLPw

**Comment by airmelt-ms** [comment]
> Looks like something changed between v7 and v8 as this works correctly in 7.x: https://codepen.io/seanms/pen/eYbzLPw

yes, it's normal in Fluent UI v7, but can't render in v8.
