### ISSUE TITLE
[Bug]: The element with `slot` attribute cannot work properly in Vue 2.6+

### ISSUE THREAD

**Issue by crrashh1542** [microsoft/fluentui#29044]
### Library

Web Components (@fluentui/web-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.23531
    CPU: (4) x64 Intel(R) Xeon(R) CPU E3-1225 v5 @ 3.30GHz
    Memory: 742.70 MB / 15.88 GB
  Browsers:
    Edge: Spartan (44.23531.1001.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.23531.1001
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/vue3-fluent-slot-testing-mppndl?file=/src/App.vue

## Actual Behavior
Because the `slot` attribute has been no longer used since Vue 2.6.0, the project with component including `slot` attribute stopped with the error message below:
```
`slot` attributes are deprecated. (vue/no-deprecated-slot-attribute)
```

## Expected Behavior
The components with `slot` attribute can display properly, same as running in the pure HTML or another environment.

## Possible Resolution
Change the `slot` attribute name needed by certain components to another attribute name which is not a keyword in any front-end framework.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chrisdholt** [comment]
Thanks or the issue @crrashh1542 but I think there might be some confusion here. The HTML `slot` attribute is not a Vue construct, it's a standard HTML attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/slot. Changing the code from `<span :slot="heading">Hello</span>` to `<span slot="heading">Hello</span>` works as expected. I'd recommend raising this to the Vue team - I'd be surprised if this is an intended application of the lint error/warning.

<img width="1133" alt="image" src="https://github.com/microsoft/fluentui/assets/13071055/91155997-20f1-44ab-bbdd-e8d1fda8b6f9">
