### ISSUE TITLE
[Bug]: Checkbox component in Windows high contrast 

### ISSUE THREAD

**Issue by DarynaAkhmedova** [microsoft/fluentui#29058]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
It is reproducible in Fluent UI React v9 in Storybook - https://react.fluentui.dev/?path=/docs/components-checkbox--default#disabled
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://react.fluentui.dev/?path=/docs/components-checkbox--default#disabled

## Actual Behavior
Chrome - Version 116.0.5845.140
When Windows High Contrast theme is on (especially Desert one) default checkbox component looks the same as disabled. Please have a look at the screenshot below.
<img width="777" alt="image" src="https://github.com/microsoft/fluentui/assets/132382266/c5edb277-1d07-4757-81ba-f11b89796041">

## Expected Behavior
It is possible to differentiate between disabled and non disabled checkbox component state in Windows High Contrast

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by vedant-3010** [comment]
Can I resolve this issue and create a PR?
I would love to work on this issue.

**Comment by TristanWatanabe** [comment]
@smhigley Correct me if i'm wrong but i tested the color contrast in Windows HCM (Desert Mode) and it came back as passing for both the checkbox itself and the text label so does that mean this wouldn't qualify as an a11y bug?

![image](https://github.com/microsoft/fluentui/assets/8649804/bca4ac9e-7885-47a7-ae44-00fc43df3052)

**Comment by sjwilczynski** [comment]
@TristanWatanabe the bug is not about color contrast itself. It's about disabled state being indistinguishable visually from enabled in Desert HC mode. So we need to look at these two states side by side, not in isolation
