### ISSUE TITLE
[Bug]: Jumping Dropdown and Combobox list

### ISSUE THREAD

**Issue by kamilkazmierczakMtab** [microsoft/fluentui#29068]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 1.89 GB / 32.00 GB
  Browsers:
    Brave Browser: 116.1.57.57
    Chrome: 116.0.5845.140
    Safari: 16.6
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-dropdown--default#default

## Actual Behavior
It is easily visible that list changes its width to be equal to size of `Dropdown`.

## Expected Behavior
List is displayed in valid width on first render

## Comments
It is possible that changing `useEffect` to `useLayoutEffect` https://github.com/microsoft/fluentui/blob/0cd9cea196d1ddf7f4c3c3b30fef8ef9fade7993/packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx#L40
will fix that issue, but truth is that width could be measured before opening list.
Same issue occurs for `Combobox` but it's much harder to notice and problem is visible only on first render because of this improvement https://github.com/microsoft/fluentui/blob/0cd9cea196d1ddf7f4c3c3b30fef8ef9fade7993/packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx#L79

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@kamilkazmierczakMtab I'm not totally following so can you please elaborate on what the issue here is? And can you provide step by step instructions on how to reproduce the bug you are seeing? Any screenshots or video/gifs would be helpful as well.

**Comment by kamilkazmierczakMtab** [comment]
When menu is opened at the beginning width of the list is equal to widest item element and then calculation of input width is performed and that width is then applied to list width.

https://github.com/microsoft/fluentui/assets/89968733/5cd59517-4f57-46e0-9e5f-171ed877be57
