### ISSUE TITLE
[Bug]: I'm not able to use library with latest react version 18.2.0

### ISSUE THREAD

**Issue by bassamIHabash** [microsoft/fluentui#29069]
### Library

React / v7 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 118.64 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 16.6
    Safari Technology Preview: 17.0
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://www.npmjs.com/package/@uifabric/react-cards

### Bug Description

mac@Macs-MacBook-Pro Chief.Web % npm i @uifabric/react-cards@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: Linz-Heritage-Angus@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=16.8.0 <18.0.0" from @uifabric/react-cards@0.119.27
npm ERR! node_modules/@uifabric/react-cards
npm ERR!   @uifabric/react-cards@"0.119.27" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/mac/.npm/_logs/2023-09-05T19_13_46_517Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/mac/.npm/_logs/2023-09-05T19_13_46_517Z-debug-0.log

### Logs

```shell
mac@Macs-MacBook-Pro Chief.Web % npm i @uifabric/react-cards@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: Linz-Heritage-Angus@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=16.8.0 <18.0.0" from @uifabric/react-cards@0.119.27
npm ERR! node_modules/@uifabric/react-cards
npm ERR!   @uifabric/react-cards@"0.119.27" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/mac/.npm/_logs/2023-09-05T19_13_46_517Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/mac/.npm/_logs/2023-09-05T19_13_46_517Z-debug-0.log
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@bassamIHabash The `@uifabric/react-cards` package is a legacy package that does NOT support react 18 which is what the error you're experiencing is referring to. We now recommend that you folks use the latest version of that component in v9 which is `@fluentui/react-card`. If you did want to use the legacy `@uifabric/react-cards` package for your own reasons, you can still install it using the new scope at [@fluentui/react-cards](https://www.npmjs.com/package/@fluentui/react-cards)  which has the peer dependency on `react` set to include react 18 which should fix the npm install issue you're experiencing.
