### ISSUE TITLE
[Bug]: react-jsx-runtime@9.0.5 missing some types (.d.ts) files

### ISSUE THREAD

**Issue by sysofwan** [microsoft/fluentui#29086]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:                         
    OS: Windows 10 10.0.22621
    CPU: (28) x64 Intel(R) Core(TM) i9-10940X CPU @ 3.30GHz
    Memory: 33.41 GB / 63.80 GB
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/smoosh-wildflower-7mvr6h

## Actual Behavior
Compiling with `@fluentui/react-jsx-runtime` using `jsxImportSource` [following the README](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-jsx-runtime/README.md#usage) results in a compile error. 

```
Could not find a declaration file for module
@fluentui/react-jsx-runtime/jsx-runtime. 
node_modules/@fluentui/react-jsx-runtime/lib/jsx-runtime.js implicitly has an 'any' type.
 
Try `npm i --save-dev @types/fluentui__react-jsx-runtime` if it exists
or add a new declaration (.d.ts) file containing
`declare module '@fluentui/react-jsx-runtime/jsx-runtime'`
```

Looking at the package files, some files declared in the exports field (`./dist/jsx-dev-runtime.d.ts` and `./dist/jsx-runtime.d.ts`) are missing:

Exports field:
![image](https://github.com/microsoft/fluentui/assets/1856058/a95b0128-3e19-4ab3-b772-20cb14e70b3d)

Package files:
![image](https://github.com/microsoft/fluentui/assets/1856058/5e215379-6d6e-448a-9759-bf030d8f469b)

## Expected Behavior
`./dist/jsx-dev-runtime.d.ts` and `./dist/jsx-runtime.d.ts` should be included in the published package.

### Requested priority

Normal

### Products/sites affected

Microsoft Defender, Microsoft Purview

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
Can confirm this to be an issue, on the latest version of the package, we aren't shipping either `jsx-dev-runtime.d.ts` or `jsx-runtime.d.ts` files

https://unpkg.com/browse/@fluentui/react-jsx-runtime@9.0.6/dist/
