### ISSUE TITLE
[Bug]: Checkbox has a focus border when using mouse click on the label

### ISSUE THREAD

**Issue by RongqiZ** [microsoft/fluentui#29106]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 25.50 GB / 63.80 GB
Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.54)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/musing-cartwright-3fwtm2?file=/example.tsx

## Step
repro link: https://codesandbox.io/s/musing-cartwright-3fwtm2?file=/example.tsx
Click the checkbox label in the Dialog

## Actual Behavior
Tick the checkbox, **with** focus border

## Expected Behavior
Tick the checkbox, **without** focus border

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
Can confirm repro - clicking on checkbox labels triggers a focus border whereas clicking on the checkbox itself does not.

https://github.com/microsoft/fluentui/assets/8649804/7de0b48a-3af7-4321-be76-1e8e4c50d036

**Comment by RongqiZ** [comment]
some observation:

When click on the checkbox label, **two** focusin events will be received, and **one** mousedown event will be received.
The one more chance of the focusin event, make the keyborg to set this is as keybord event, then set the data-fui-focus-within  attribute onto the checkbox.

**Comment by RongqiZ** [comment]
it cannot repro from 9.34.2
