### ISSUE TITLE
[Bug]: Tooltip on icon display wrong position when using wrapIcon

### ISSUE THREAD

**Issue by FengQiMS** [microsoft/fluentui#29109]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900
    Memory: 29.47 GB / 63.70 GB
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/adoring-lumiere-jt43pz?file=/example.tsx

## Actual Behavior
tooltip display always at left top corner
![image](https://github.com/microsoft/fluentui/assets/44865230/77030c67-b0cd-4c1f-ab57-994b0e61b156)
There is previous issue similar https://github.com/microsoft/fluentui/issues/24544 and got resolved, I've tried setting ref to the wrapIcon and it does not work.

For the icons provided in fluentui/react-icons there is no such issue

## Expected Behavior
tooltip should display at the icon placement

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@FengQiMS  Ref forwarding doesn't seem to be a feature available in `wrapIcon` just yet. There is an open issue in the react-icons repo regarding it: https://github.com/microsoft/fluentui-system-icons/issues/504

**Comment by tomi-msft** [comment]
Hello @FengQiMS thanks for filing the issue.  I will be updating the `wrapIcon` method signature to include ref forwarding, it will be fixed in the next version of `@fluentui/react-icons`. https://github.com/microsoft/fluentui-system-icons/issues/645

**Comment by FengQiMS** [comment]
@tomi-msft  Thanks for taking care of it, seems [646](https://github.com/microsoft/fluentui-system-icons/pull/646) already been merged, new version should contains the change right?

**Comment by tomi-msft** [comment]
Fixed in [646](https://github.com/microsoft/fluentui-system-icons/pull/646)
