### ISSUE TITLE
[Bug]: SearchInput DisableAnimation doesn't seem to do anything

### ISSUE THREAD

**Issue by russrimm** [microsoft/fluentui#29117]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
When disabling animation, either by using the FluentUI control or even testing it out on the FluentUI samples page, the TextInput doesn't appear to behave any differently based on whether or not DisableAnimation is true or false.
```

### Are you reporting Accessibility issue?

None

### Reproduction

Create a FluentUI TextInput, set DisableAnimation to True and False and observe behavior of the control.

## Actual Behavior
Disabling or Enabling the SearchBox animation doesn't disable the animation

## Expected Behavior
Disabling the SearchBox animation should disable the animation on the control

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@russrimm If you're talking about the v8 [SearchBox](https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox) component then things seem to be working as expected. In the default example, the search icon animates out of the input upon it receiving focus. Whereas in the below example with `disableAnimation` set, the search icon just disappears with no animation when input receives focus. If this isn't the issue you're referring to, could you please provide a repro example and we'll take a closer look.

https://github.com/microsoft/fluentui/assets/8649804/0e454ab7-60b7-48af-820d-b10f7dc0351c

**Comment by russrimm** [comment]
@TristanWatanabe AH!  I now see how it works - I was not seeing the slight difference of sliding out vs popping out instantly.  Now I understand how it works better.  Sorry to take up your time, and thanks for your assistance.
