### ISSUE TITLE
[Bug]: Controlled Dropdown component missing checkmark in options list when selected option changes from different component

### ISSUE THREAD

**Issue by sgerendasyaracelibio** [microsoft/fluentui#29115]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz  
    Memory: 42.38 GB / 63.75 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.76)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/admiring-frost-jdqgkg?file=/example.tsx

## Actual Behavior
When using a controlled dropdown component, the checkmark next to the selection Option is missing when the Option is selected outside of using the dropdown component. For example, if a user presses a reset button which, onClick, selects the first Option in the Options list, the checkmark will be missing.

## Expected Behavior
The checkmark should appear next to the selected option, even when the option is selected from a component other than the dropdown.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@sgerendasyaracelibio Made a small tweak to your example to pass the `value` to the `setSelectedOptions` hook and it accomplishes the behavior you're looking for: https://codesandbox.io/s/snowy-rain-q46lk7?file=/example.tsx

<img width="750" alt="image" src="https://github.com/microsoft/fluentui/assets/8649804/9ccafc76-8e05-4483-a325-4b97616d4521">

**Comment by sgerendasyaracelibio** [comment]
Ah I see, the value needs to match for the selectionOptions. I'll close this, thanks!
