### ISSUE TITLE
[Bug][React / v8]: TeachingBubble blocks the page that caused by the "preventDismissOnEvent" property

### ISSUE THREAD

**Issue by pochih** [microsoft/fluentui#29124]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (32) x64 Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz
    Memory: 8.83 GB / 31.66 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.200)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/BrianHuang/pen/zYyZbeo

## Actual Behavior
The teaching bubble blocks the input to other components.
In the reproduction example, the teaching bubble blocks the input of the search box.
![image](https://github.com/microsoft/fluentui/assets/8791614/cd48b9e9-6a18-43a9-bea0-8e93a233ee22)

I believe this is introduced by the "preventDismissOnEvent" property.
Need to set this property to prevent the teaching bubble from getting dismissed when losing focus.
```javascript
calloutProps={{
  preventDismissOnEvent: () => true,
}}
```

## Expected Behavior
The teaching bubble should not block the input to other components.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by pochih** [comment]
As a comparison, the `Callout` component doesn't have this issue.
https://codepen.io/BrianHuang/pen/KKbWOdd

![image](https://github.com/microsoft/fluentui/assets/8791614/e1a2b4bd-d218-4967-8d4c-b9982b6e6366)

**Comment by Hotell** [comment]
IMO that's by design  but I dont have proper context why things were implemented like this.
