### ISSUE TITLE
[Bug]: Inline drawer on doc page flashes when opening for the first time

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#29134]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 42.89 GB / 63.57 GB
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/preview-components-drawer--default#inline

## Actual Behavior
This only happens on the doc page (inline example) when multiple drawers are used. 

When open inline left or right for the first time, the other side would flash with a blank div. But it won't happen since 2nd open. 

Please check the recording. Thank you!

https://github.com/microsoft/fluentui/assets/39588094/07ab6c48-e8f8-4e4e-8bd7-042dece304fd

## Expected Behavior
Do not flash with a blank div when opening. 

### Requested priority

Low

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@marcosmoura can you please check?
