### ISSUE TITLE
[Bug]: "IconDirectionContextProvider" no matching export

### ISSUE THREAD

**Issue by mrkevkev-2** [microsoft/fluentui#29141]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (32) x64 AMD EPYC 7763 64-Core Processor
    Memory: 119.35 GB / 125.79 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
```

### Are you reporting Accessibility issue?

no

### Reproduction

(Bug is asking for others seeing an error in importing, ever since a PR from fluentui)

### Bug Description

Hi there,

PR "AddIconDirectionProvider to FluentProvider" #28803 PR was added recently and it's causing build breaks and stopping Outlook from being able to update our packages to the latest @fluentui/react-provider version.

We're seeing this error:
```
ERROR (default:vendor:<general>) at node_modules/@fluentui/react-provider/lib/components/FluentProvider/renderFluentProvider.js:5
	import { IconDirectionContextProvider } from '@fluentui/react-icons';
	No matching export in "node_modules/@fluentui/react-icons/lib/fonts/index.js" for import "IconDirectionContextProvider"
```
Is anyone else seeing this? I'm not sure why it can't find `IconDirectionContextProvider`, as it seems to be exported fine from react-icons, however the compiler isn't agreeing.

Our react-icons version is 2.0.212, our react-provider version we're trying to update to is 9.8.4.

Thanks,
lekevin

(@tomi-msft for possible help here regarding that PR and why we might be seeing this issue.)

### Logs

```shell
ERROR (default:vendor:<general>) at node_modules/@fluentui/react-provider/lib/components/FluentProvider/renderFluentProvider.js:5
	import { IconDirectionContextProvider } from '@fluentui/react-icons';
	No matching export in "node_modules/@fluentui/react-icons/lib/fonts/index.js" for import "IconDirectionContextProvider"
```

### Requested priority

Blocking

### Products/sites affected

Outlook Web

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
`@fluentui/react-provider@9.8.4` requires `@fluentui/react-icons@2.0.207`
`@fluentui/react-icons@2.0.207` contains an export for `IconDirectionContextProvider`

> https://unpkg.com/@fluentui/react-provider@9.8.4/package.json
> https://unpkg.com/@fluentui/react-icons@2.0.207/lib/index.js


From the report it looks that the version of icons does not match required. @mrkevkev-2 can you please provide contents of following files `node_modules/@fluentui/react-icons/lib/fonts/index.js` & `node_modules/@fluentui/react-icons/package.json`?
