### ISSUE TITLE
[Bug]: search-box component is not adding title, aria-lable, aria-labelledby to the parent div of input element where as it is adding only role to the parent div

### ISSUE THREAD

**Issue by Govindu9** [microsoft/fluentui#29178]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
PS C:\source\M365AdminUX> npx envinfo --system --npmPackages '{@fluent/*}' --browsers
npx: installed 1 in 4.323s

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
    Memory: 4.07 GB / 15.85 GB
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (116.0.1938.81)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

Yes

### Reproduction

https://codepen.io/mohan-sri-the-sasster/pen/RwEjRXR

## Actual Behavior

title and ariaLabel  attributes are not added to the parent div of input element. Only role is getting added to parent div of input element

## Expected Behavior
Like  how role attribute is added to parent div of input element  the same should happen with title , ariaLable props as well. 

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
This is intended behavior. The input is the primary part of this control, the outer wrapper is just a wrapper to help contain the icon.
