### ISSUE TITLE
[Bug]: CommandBar's overflow behavior can get stuck when using createRoot and React 18

### ISSUE THREAD

**Issue by brandonthomas** [microsoft/fluentui#29174]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 13.96 GB / 31.94 GB
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.31), ChromiumDev (118.0.2088.2)
    Internet Explorer: 11.0.22621.1


^ this info is flawed. I'm on Windows 11 pro, 22H2 22621.2283
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/brandonthomas/pen/mdaBZwy

### Bug Description

Repro:

- Go to the link and reduce the size down to overflow and expand it back again. If this doesn't work, try throttling performance through the debug tools. We believe that this is a performance gated issue and has to do with React 18's batch rendering. If you remove the DetailsList the CommandBar works pretty well in isolation. This isn't a great test though because this component is never rendered in isolation. When in applications or scenarios with small perf hits we even see it recover at times. If the application has a lot going on though, it gets stuck until the whole page is re-rendered or the application is reloaded (both work). 

## Actual Behavior
When using React 18, CommandBar can get stuck when shrinking and growing within overflow. At times, only a single element (sometimes the overflow button but other times we've seen items themselves stuck) is visible and the functionality of the application is reduced.

## Expected Behavior
CommandBar shrinks and grows to show the proper items that fit within the viewport.

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Mitch-At-Work** [comment]
Can confirm I was able to reproduce this issue with a react 18 implementation of the v8 Fluent Storybook CommandBar page.
