### ISSUE TITLE
[Bug]: Tooltip on button with styled FluentProvider blinks

### ISSUE THREAD

**Issue by MichaelGoulding** [microsoft/fluentui#29184]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
See sandbox environment
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/keen-glitter-mds93r?file=/index.tsx

## Actual Behavior
Hovering over the icon button causes the whole page to blank except for the tooltip, which causes the button to lose focus which makes the tooltip disappear, but then the button is hovered immediately afterwards, which causes the tooltip to show again, cycling and causes the whole page to blink.

## Expected Behavior
Tooltip should function as normal while still allowing the fluentProvider to be height 100%

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Don't add any styles to the provider that you don't also want added to the tooltip surface. We intentionally copy over styles to ensure that the tooltip gets rendered in the react portal with all of the appropriate styles. If you need a 100% height wrapper, move that style to a div. 

<FluentProvider theme={webLightTheme}>
      <div className={classes.fluentProvider}>
        <Tooltip content="Example tooltip" relationship="label">
          <Button icon={<LightbulbRegular />} size="large" />
        </Tooltip>
      </div>
    </FluentProvider>
