### ISSUE TITLE
bump SWC to latest once bug is fixed

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#29192]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Bump SWC to latest once https://github.com/swc-project/swc/issues/7977 is fixed as it causes memory leaks on some context usages.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by Hotell** [comment]
fix landed in master - waiting for new compiler release
