### ISSUE TITLE
Drawer should use makeResetStyles for base styles

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#29205]
![image](https://github.com/microsoft/fluentui/assets/20744592/56f4ad4f-868a-4426-8984-235de28ea6fd)

The DrawerOverlay has 87 classes applied to it. Having more classes can affect performance negatively. None of the Drawer components use `makeResetStyles` which will apply the base styles into one since css class.

Also instead of additional hooks, like `useDrawerBaseClassNames` it's possible just to share mixins

```ts
const useDrawerRootStyles = makeStyles({
  root: {
    ...drawerBaseStyles(),
   // overrides to base styles
    position: 'fixed',
    top: 0,
    bottom: 0,
    opacity: 0,
    boxShadow: '0px transparent',
    transitionProperty: 'transform, box-shadow, opacity',
    willChange: 'transform, box-shadow, opacity',
  },
```

This should make it much easier to use makeResetStyles in each of the drware components

**Comment by Hotell** [comment]
@ling1726 does griffel ship lint rules for this ? feels like missed opportunity to provide good DX/ship performant components

**Comment by ling1726** [comment]
Griffel does not have rules to enforce reset styles, these should be decided on a library/app level, since reset styles can only be used _**once**_ on a component.

In this case we could have a lint rule that tries to enforce this in Fluent
