### ISSUE TITLE
Drawer with modalType="alert" should be dismissible with Escape

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#29207]
For reference: https://github.com/microsoft/fluentui/pull/28276#issuecomment-1728200141

To be compliant with the WAI-Aria best practices, alertdialogs should be dismissible with Escape. Open/close state can be controlled in userland to create undismissible dialogs if required. We should be using the most accessible patterns by default

**Comment by marcosmoura** [comment]
By default, the Drawer follows the same behavior as Dialog, so that is also reflected.
The example we have in Drawer docs uses the controlled state to prevent closing.
I made an update to the storybook description to explain that a little better.
