### ISSUE TITLE
[Bug]: onscreen keyboard causes ContextualMenu to close, breaking change in behavior

### ISSUE THREAD

**Issue by jeffersoneagley** [microsoft/fluentui#29200]
### Library

React / v8 (@fluentui/react)

### System Info

This is probably not the system info you're looking for. The actual issue doesn't repro on Windows, and the requested command doesn't matter on Android with Edge, Brave, or Chrome.

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 47.52 GB / 63.95 GB
  Browsers:
    Edge: Spartan (44.22621.2265.0), Chromium (117.0.2045.35)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

#### In-situ:

Get a mobile device that uses a docked virtual keyboard (ie: default android behavior).

Open: https://msrc-ppe.microsoft.com/update-guide/

Try to change "Product Family".

#### Contrived:

https://codepen.io/jefferson-eagley/pen/QWzaKbq

### Bug Description

>  This is broken **in production!!!**

## Actual Behavior
We have a button. That button has a contextualmenu. That contextualmenu contains a textfield. Mobile users report not being able to access the menu.

It appears that this is an issue with screen resize behavior being changed to cause the dropdown/contextualmenu to close. 

Behavior chain: 

- user clicks dropdown
- dropdown opens 
- the text input for searching within the dropdown list is automatically focused
- selecting the search field (text input) triggers onscreen keyboard
- the addition of an onscreen keyboard is counted as a "resizes" of the page
- resizing the page closes the menu.
- **All** mobile users are unable to open contextual menus if they trigger/alter the onscreen keyboard.

## Expected Behavior
- Mobile users should be able to use `ContextualMenu` even with internal fields that accept input.
- Virtual keyboard should be able to adjust the screen size without closing contextual menus.

### Requested priority

Blocking

### Products/sites affected

https://msrc.microsoft.com/update-guide

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by jeffersoneagley** [comment]
Just checking back in so the ticket stays alive.

**Comment by jeffersoneagley** [comment]
Just checking back in so the ticket stays alive.

**Comment by jeffersoneagley** [comment]
Checking back in since this seems to be stagnating and is still an issue for us.

**Comment by Dante-Auditore-da-Firenze** [comment]
Hi @jeffersoneagley , can you try setting 'preventDismissOnResize' to true in [calloutProps](https://developer.microsoft.com/en-us/fluentui#/controls/web/callout#ICalloutProps). calloutProps can be passed to ContextualMenu.
This worked for me.

**Comment by jeffersoneagley** [comment]
Thanks @Dante-Auditore-da-Firenze, I'll give that bandaid a try. 

I do need this fixed within the actual library though, because it impacts a bunch of MS websites that now don't work correctly when opened on a phone. It didn't used to do this, and fixing the root cause with Fluent will fix it everywhere (vs just fixing my 5 websites).

**Comment by jeffersoneagley** [comment]
Oh... preventDismissOnResize is deprecated.

**Comment by Sti2nd** [comment]
Thank you for documenting this on GitHub @jeffersoneagley 💪🏿
