### ISSUE TITLE
[Bug]: Card Component - selected={false] not being honored after user click a card

### ISSUE THREAD

**Issue by tedishero** [microsoft/fluentui#29202]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Website
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/sad-lovelace-6w9sx5?file=/example.tsx:2932-2937

## Actual Behavior
Sandbox repro: https://codesandbox.io/s/sad-lovelace-6w9sx5?file=/example.tsx:2932-2937
In the example I am setting selected={false} but after user clicks a card, the card still shows selected state visually even though I am passing false. 

## Expected Behavior
I am expecting the visual state to follow what I am setting selected prop to.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by marcosmoura** [comment]
@tedishero This is indeed a bug. I'm working on a fix.
