### ISSUE TITLE
Inline drawer animation causes content to jump

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#29208]
Feel free to close if this is by design.

While the animation of the drawer slide is smooth, it will push the content immediately, making it jump horizontally and leaving and empty space while the drawer slides in.

![jumpy drawer](https://github.com/microsoft/fluentui/assets/20744592/bde38412-cf0a-4b3f-adf5-2a5e27912f22)

**Comment by marcosmoura** [comment]
This is by design, but I'll leave this open as we will revisit this with the designers.
The reason we have this animation now is the performance.

**Comment by spmonahan** [comment]
> This is by design, but I'll leave this open as we will revisit this with the designers.
> The reason we have this animation now is the performance.

Does this explain why the custom animation doesn't seem to have this issue?

**Comment by dgray0229** [comment]
I'm hoping to look into developing a fix, do you have any suggestions on where to start? I can see about implementing `transform` into the component animations. If you cant think of anything I can figure it out.

**Comment by marcosmoura** [comment]
For now, we'll keep the animations as is. The design team will review the need to change this in the future.
As we support custom animations, it is fairly easy to override the default one.
