### ISSUE TITLE
Disabled tag has hover state in windows high contrast mode

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#29224]
It's possible to hover over disabled tags and trigger the hover state

![image](https://github.com/microsoft/fluentui/assets/20744592/16e21682-13c9-4674-a80c-4b4052b50ddb)

Feel free to close if this is by design

**Comment by YuanboXue-Amber** [comment]
Hmm can you help me repro this - I tried all three themes and I can't get a hover state

**Comment by ling1726** [comment]
Sorry, I can repro this in windows high contrast mode - I updated the issue title
