### ISSUE TITLE
Tag dismissible - the dismiss icon should be highlighted on focus

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#29225]
## Actual Behavior
The dismiss button is not higlighted on focus:
<img width="129" alt="image" src="https://github.com/microsoft/fluentui/assets/9615899/13df3d02-b411-4caa-bc6b-a558a883cc80">

## Expected Behavior
Spec:
When navigating with a keyboard, and focus lands on a Tag, the dismiss button changes to the hover state to highlight that the dismiss button is interactive.

**Comment by YuanboXue-Amber** [comment]
I went thru the figma and I'm seeing only InteractionTag's outlined variant has color change on focus: 
<img width="184" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/9eda6f86-f0b1-4da1-a985-8ad9992dcfaf">
In the filled/brand variants, on focusing the dismiss button, icon color does not change. 
And in Tag's all 3 variants, on focusing the tag, icon color does not change.
Therefore I think changing color might be a mistake in figma. I'll verify this with the designer.

**Comment by YuanboXue-Amber** [comment]
Verified this was not intentional in figma. Focus should only have focus ring :) closing this issue
