### ISSUE TITLE
Breadcrumb seems to be missing hover and pressed back plates

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#29232]
Bug Bash

Design spec calls out back plates for hover and pressed states.

https://www.figma.com/file/kFS0a9HlhSRCtSUuZK2g4v/Breadcrumb?type=design&node-id=4683-252648&mode=design&t=mxKb8Up4M4z22Ylo-4

These seem to be missing from the code implementation. Every clickable breadcrumb in the demo behaves as a link - with no backplates.

**Comment by ValentinaKozlova** [comment]
@mltejera , could you please give me more details on that bug? I can't reproduce it.
That's expected result:
<img width="393" alt="image" src="https://github.com/microsoft/fluentui/assets/11574680/7e2cf866-2ebd-458f-838e-58c300e4f88e">
And that's what I have:
![button-states](https://github.com/microsoft/fluentui/assets/11574680/f59908af-0024-42ab-8f8d-0f865df907cd)

**Comment by mltejera** [comment]
ah - I was just looking at this one and didn't notice a transparent mode. You might consider making the back plate presence the default behavior since the design spec calls it out, and I didn't notice it.

I might also be using the wrong build: https://react.fluentui.dev/?path=/docs/preview-components-breadcrumb--default

**Comment by ValentinaKozlova** [comment]
Not a bug. That behavior is expected
