### ISSUE TITLE
[Bug]: Named imports are not working in the v3 version of @fluentui/web-components

### ISSUE THREAD

**Issue by atulkatti** [microsoft/fluentui#29230]
### Library

Web Components (@fluentui/web-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/typescript-966wjs?file=index.ts,section%2Fsection.ts,package.json,content1.ts,section%2Fnamed_exports.ts

## Actual Behavior
It seems no named exports are done in the v3 web components.

## Expected Behavior
Named exports like the ones below should be possible from the v3 web components.
import { AnchorButtonAppearance } from '@fluentui/web-components-v3/anchor-button.js';
import { Checkbox } from '@fluentui/web-components-v3/checkbox.js';
import { Switch } from '@fluentui/web-components-v3/switch.js';

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chrisdholt** [comment]
The reason nothing is coming in from the files above are that they only export the component definitions, there aren't additional files exported from those export paths at this time. It seems reasonable to export any corresponding const objects and types from that for convenience.
