### ISSUE TITLE
Breadcrumb examples are complex

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#29239]
Some general feedback - many of the breadcrumb examples are complex, that have lots of other components and state management to show off all the awesome things about the component.

However it makes them hard follow, and very few consumers will use them in that way.

Consider adding some simpler examples that just illustrate the fundamentals of the component; in ways most people would use them. Then introduce the complex examples.

**Comment by ValentinaKozlova** [comment]
Thank you for your feedback. I made those stories simpler. Complex examples are still there for Overflow logic and tooltips
