### ISSUE TITLE
Breadcrumb components should be under one page

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#29246]
You could have the `BreadcrumbButton`, `BreadcrumbDivider` and `BreadcrumbItem` examples underneath the regular `Breadcrumb` page and have their APIs next to each other, similar to how `Dialog` does this:

![image](https://github.com/microsoft/fluentui/assets/7798177/2ee7cd52-0c31-4bd6-a719-3669f0ee8bed)

**Comment by ValentinaKozlova** [comment]
Fixed in #29302
