### ISSUE TITLE
Bug: "open right" slides the entire page over

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#29241]
### Repro

1. Open the ["position" story](https://react.fluentui.dev/?path=/docs/preview-components-drawer--default#position) in Firefox or Safari
2. Click "Open right"
3. Page slides over and appears broken
4. Closing the Drawer does not slide the page back

https://github.com/microsoft/fluentui/assets/93940821/24900e26-8a2b-425a-a331-ba8d9b06956f

- **Browser:** Firefox
- **Version:** 117.0.1 (64-bit)
- **OS:** Windows 11

- **Browser:** Safari
- **Version:** 16.6
- **OS:** macOS Ventura 13.5.2

**Comment by marcosmoura** [comment]
This is not an issue with the Drawer, but rather the Storybook iframe itself. I created a fix for it: https://github.com/microsoft/fluentui/pull/29410
