### ISSUE TITLE
[Bug]: Link in Dialog has a focus border when the Dialog is open by default

### ISSUE THREAD

**Issue by Janey2022** [microsoft/fluentui#29251]
Library
React Components / v9 (@fluentui/react-components)

System Info
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 25.50 GB / 63.80 GB
Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.54)
    Internet Explorer: 11.0.22621.1
Are you reporting Accessibility issue?
None

Reproduction
https://codesandbox.io/s/interesting-gagarin-pnj5v8

Bug Description
Step
repro link: https://codesandbox.io/s/interesting-gagarin-pnj5v8
By default, the dialog is open, when it shows, the focus border shows around the link.

Actual Behavior
Refresh the page, when the Dialog shows, the focus border shows around the link in Dialog.

Expected Behavior
There is no focus border around the link element.

Logs
No response

Requested priority
High

Products/sites affected
No response

Are you willing to submit a PR to fix?
no

Validations
If the dialog is not open by default, the issue can't be reproduced.

**Comment by GeoffCoxMSFT** [comment]
@bsunderhus - Can you kindly investigate this issue? I found that even if I set the link tabindex to -1 it still is getting the focus every time the dialog opens.  The issue might be reproducible even when the dialog is not open by default because the link focus is only showing up when the keyboard focus is active.  I see the focus rectable on the link anytime I use the keyboard to click the trigger button and open the dialog.

**Comment by bsunderhus** [comment]
I'm not sure this is a dialog problem per se @GeoffCoxMSFT.

Dialog must focus on it's first focusable element when it opens, in the case this first element is a `Link` and we have the dialog opened by default the `keyborg.isNavigatingWithKeyboard` would be `false`  by default so the focus outline should not be visible (as there is no need for it on mouse navigation), this might be a bug with focus outline?! @ling1726 

I'll be investigating more!

**Comment by Rita-Okonkwo** [comment]
Just noting that I am experiencing this too
