### ISSUE TITLE
[Bug]: unable to copy to clipboard content within storybook doc blocks

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#29265]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-textarea--default

## Actual Behavior

1. Type some text into a Fluent `Textarea`
2. Copy the text
3. Paste the text
4. Whatever was previously in your clipboard is pasted

## Expected Behavior

I should be able to copy text from a `Textarea`.

https://github.com/microsoft/fluentui/assets/93940821/03f5ee5a-f8b6-4a8f-881c-67e389ad0a67

## Browsers

- Firefox 117.0.1 (64-bit) Windows 11
- Edge 117.0.2045.36 (Official build) (64-bit) Windows 11

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gani1000** [comment]
I couldn't replicate this issue in Edge Version 117.0.2045.41 (Official build) (64-bit) Windows 10, Firefox Windows 10, and Chrome. Copy and paste works by selecting and using keyboard shortcuts in windows 10.

**Comment by Hotell** [comment]
this is also happening for `Field` https://react.fluentui.dev/?path=/docs/components-field--default within storybook docs. outside storybook everything works as expected so this must be some very weird storybook clipboard hijacking.

when you press cmd/ctrl+c there is this storybook popup shown "copied" 

<img width="1391" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/f63f7b2a-7fd7-483c-87e5-19213b9e5713">

**Comment by Hotell** [comment]
confirmed this is SB bug and they have no plans to fix it for v6 unfortunately https://github.com/storybookjs/storybook/issues/18611#issuecomment-1382712894

**Comment by Hotell** [comment]
@behowell  ran into similar thing some time ago https://github.com/microsoft/fluentui/pull/24135. 

With v6 only workaround is to stopping rendering `show code` functionality - which for these more complex control is not something we should do. thoughts ?

**Comment by spmonahan** [comment]
Perhaps we should upgrade to v7? @TristanWatanabe upgraded another repo to v7 so he can probably comment on the effort required.

**Comment by mltejera** [comment]
Hey is there an ETA on the v7 upgrade? This bug is making some of the theme tooling on our site unusable... like, if it were a product this would be a sev 0, work through the weekend, we're breaking SLA and losing money bug.

**Comment by EdDaWord** [comment]
+1 to Mason's point. In cases like [createV9Theme](https://react.fluentui.dev/?path=/docs/migration-shims-v8-theme-createv9theme--playground)

There's no way to actually copy the output, even inspecting the HTML only gets you 80% of the output. It'd be amazing if we could upgrade to v7. 

![image](https://github.com/user-attachments/assets/f8988cca-4eba-4506-a4e8-ef1901c778ca)

**Comment by Hotell** [comment]
> Hey is there an ETA on the v7 upgrade? This bug is making some of the theme tooling on our site unusable... like, if it were a product this would be a sev 0, work through the weekend, we're breaking SLA and losing money bug.

it's planned for this Quarter - you can check all planned work within our Unified Project Board

**Comment by robertpenner** [comment]
This copy hijacking was affecting my work as well.
