### ISSUE TITLE
[Bug]: Duplicated ids for MultiStackedBarChart

### ISSUE THREAD

**Issue by wangcan-microsoft** [microsoft/fluentui#29270]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
"@fluentui/react-charting": "5.17.7"
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/wangcansunking/pen/OJrvWPB

## Actual Behavior
Id of rect is duplicated.
![image](https://github.com/microsoft/fluentui/assets/60836994/9c28701c-366a-4d89-9d8e-d44e3087f6dd)
![image](https://github.com/microsoft/fluentui/assets/60836994/c1599789-9bc6-48d1-b639-596ced5c8eaa)
![image](https://github.com/microsoft/fluentui/assets/60836994/dbee0f97-4a5e-4200-9ff0-c622af7c15bc)

## Expected Behavior

The ids should be different.

## Additional information
The issue only happens on "@fluentui/react-charting": "5.17.7". In "@fluentui/react-charting": "5.16.36", there is no issue.

[These lines](https://github.com/microsoft/fluentui/blame/e31d18c0326a4c3f8f0966aaf2bb889cf44e4ce4/packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx#L125) cause this issue.
The duplicated ids' prefixes are `_MSBC_bar` and `_MSBC_rect`.

![image](https://github.com/microsoft/fluentui/assets/60836994/26dc8dd0-eeec-4f0e-92f7-ccff12fb266d)
![image](https://github.com/microsoft/fluentui/assets/60836994/589ce762-f656-44de-901d-d3ec5ca32e2c)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by AtishayMsft** [comment]
@harsh9975 You can look into this issue.

**Comment by harsh9975** [comment]
okay👍

**Comment by AtishayMsft** [comment]
This issue is resolved.
