### ISSUE TITLE
[Feature]: Add barMinimumHeight property to VerticalBarChart

### ISSUE THREAD

**Issue by duckduckmuse** [microsoft/fluentui#29282]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Currently when displaying items that have a small y-value compared to other items in a `VerticalBarChart`, the item will not display a bar or y-value which can be confused with the item having a y-value of 0. Adding `barMinimumHeight` to `IVerticalBarChartProps` would small-scale y-values to be displayed, similar to VerticalStackedBarChart.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by AtishayMsft** [comment]
@duckduckmuse This functionality is in our backlog but not prioritized yet.
Are you willing to submit a PR to add this functionality.
The Charting team would be happy to guide and merge the changes.
