### ISSUE TITLE
[Bug]: TabList tab names should wrap responsively to screen size

### ISSUE THREAD

**Issue by 15MariamS** [microsoft/fluentui#29283]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 35.20 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.5.2
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/adoring-driscoll-z3x3hd?file=/example.tsx:0-871

## Actual Behavior
TabList is not responsive to small screen sizes.

## Expected Behavior
Tab names in a TabList should wrap when the TabList does not fit inside the container

Either stack vertically when screen size is too small [like this](https://github.com/microsoft/fluentui/assets/81782111/20ec8548-8ffc-4cf4-9fa4-a89a7b1de191) or wrap the tab names in each tab. I do _not_ want to add options into the `...` overflow button because visibility of options is important in my feature.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
just to clarify, what you're basically asking is to change rendering from `vertical` false to true on screens where it cannot fit ? 

if yes you can implement some kind of viewport media query hook and change those tabs properties as necessary based on your viewports needs.

**Comment by GeoffCoxMSFT** [comment]
If you do overflow, you can choose to keep certain tabs out of the overflow menu.  Take a look at this [example](https://react.fluentui.dev/?path=/docs/components-overflow--default#overflow-by-priority) for more info.  Having any dynamic resizing/orientation based on space isn't part of the current design so we'd have to open a design feature request first.
