### ISSUE TITLE
[Bug]: AccordionHeader  <button> cannot appear as a descendant of <button>error

### ISSUE THREAD

**Issue by EbramTawfik** [microsoft/fluentui#29308]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 23.70 GB / 47.71 GB
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.43)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction
https://stackblitz.com/edit/stackblitz-starters-lrowmr?file=src%2FApp.tsx
https://stackblitz-starters-lrowmr.stackblitz.io

## Actual Behavior
I am trying to add a button to the header of the accordion but I am getting "button cannot appear as a descendant of button". I had to use another component to avoid this issue but other components will not have the same other focus features like the button.
Here is the example:
https://stackblitz-starters-lrowmr.stackblitz.io
  
## Expected Behavior
having non button AccordionHeader will help with the fix.

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
can you provide link to cloud IDE where we can see source code as well? 

I'm not sure if this issue is for react (v8) or react-components (v9) and we need this info in order to process your request. ty

**Comment by EbramTawfik** [comment]
@Hotell yes here is the code https://stackblitz.com/edit/stackblitz-starters-lrowmr?file=src%2FApp.tsx
