### ISSUE TITLE
[Bug]: Can not move the cursor to the tooltip content easily

### ISSUE THREAD

**Issue by harunurhan** [microsoft/fluentui#29331]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 36.18 GB / 63.95 GB
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.43)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/Harun-Urhan/pen/jOXKmoK

## Actual Behavior
User can not move the cursor to the tooltip content easily since it's closing way too early

![broken-hover-hover](https://github.com/microsoft/fluentui/assets/4868667/1580cc24-beaf-40d1-9f97-ac02dac89971)

## Expected Behavior
We should enable users to move the cursor to the tooltip content without a fight, it is useful cases like if they want to copy-paste the content or tooltip has a link.

An approach which was used to address such issues: https://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by kycutler** [comment]
I was just about to report the same issue 🙂 even when passing `hoverDelay` to prevent the tooltip from disappearing immediately, it will still disappear even if the user is hovering over it:

![6bf6a227-4b65-4f6f-9460-f63c9380cfbe](https://github.com/microsoft/fluentui/assets/67761731/9a5fbe5c-f258-49c0-b85c-d5ef2d7db669)

There was a previous instance of this issue in #9464, but it seems to have regressed (possibly in #9845).

**Comment by Hotell** [comment]
dropdown and tooltip are bit different UX patterns IMO so maybe if you need that copy / actionable functionality you should look for some different pattern instead of toolltip.

anyways ATM only "mitigation" is to use `closeDelay` property with reasonable time for you particular UI flow.

**Comment by harunurhan** [comment]
@Hotell , as mentioned by @kycutler, `closeDelay` doesn't mitigate this. It still closes when delay is over even if the cursor is still on the tooltip content.

**Comment by harunurhan** [comment]
@behowell could you re-open this?
