### ISSUE TITLE
[Bug]: DataGrid overlaps columns if first column has a long word in it and "resizableColumns" is present.

### ISSUE THREAD

**Issue by MichaelGoulding** [microsoft/fluentui#29365]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components 9.33.0

See reproduction link for full dependency list.
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/recursing-bird-mvyg7y?file=/example.tsx

### Bug Description

I copied the sample from https://react.fluentui.dev/iframe.html?viewMode=docs&id=components-datagrid--default#sort and added the resizableColumns property to it.  I then made the filename values one word instead of a few.

## Actual Behavior
When the first column contains a long filename, the 2nd column is overlapped on the first if the "resizableColumns" property is added to the list.
<img width="599" alt="image" src="https://github.com/microsoft/fluentui/assets/18077959/6c48bbae-404f-4105-a045-d1798c30ac46">

## Expected Behavior
Either making the column large enough to fit, like what is seen when the "resizableColumns" property is removed or truncate the first column instead of drawing both columns on top of each other.  The first option is preferred.
<img width="796" alt="image" src="https://github.com/microsoft/fluentui/assets/18077959/a11e0693-9681-401e-a911-4d7133002b12">

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by thesharifi** [comment]
@MichaelGoulding, I am interested in this repository, Please assign this to me.

**Comment by marcosmoura** [comment]
@MichaelGoulding 
The TableCellLayout component has a `truncate` property, as it can be seen on the [Resizable Columns (preview) example](https://react.fluentui.dev/?path=/docs/components-datagrid--default#resizable-columns--preview-).
The usage:
```tsx
<TableCellLayout truncate media={item.file.icon}>
  {item.file.label}
</TableCellLayout>
```

If you need to control the `width` of the columns, the `columnSizingOptions` prop can be provided.

**Comment by swinefeaster** [comment]
shouldn't truncate be on by default? otherwise it seems kinda broken with resizable columns turned on.

**Comment by MichaelGoulding** [comment]
> @MichaelGoulding The TableCellLayout component has a `truncate` property, as it can be seen on the [Resizable Columns (preview) example](https://react.fluentui.dev/?path=/docs/components-datagrid--default#resizable-columns--preview-). The usage:
> 
> ```tsx
> <TableCellLayout truncate media={item.file.icon}>
>   {item.file.label}
> </TableCellLayout>
> ```
> 
> If you need to control the `width` of the columns, the `columnSizingOptions` prop can be provided.

The right column sizes are chosen for the content if the columns aren't resizable.  We shouldn't have to either truncate or calculate the right sizes when it is already possible to have the right sizes by default.
