### ISSUE TITLE
FluentUI github showing wrong README file

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#29380]
The wrong README file is being shown on https://github.com/microsoft/fluentui. It looks like this is a result of @Hotell's https://github.com/microsoft/fluentui/pull/29301 that added a new `.github/README.md` file.  It's apparently a "feature" of GitHub to prefer showing the readme in the `.github/` folder over one in the root: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes.

Not sure of the preferred fix. Might need to rename `.github/README.md`?

<img width="457" alt="screenshot of readme file" src="https://github.com/microsoft/fluentui/assets/48106640/35195783-3ef5-419d-a523-19ea031ed5d4">

**Comment by Hotell** [comment]
https://github.com/microsoft/fluentui/pull/29463
