### ISSUE TITLE
[Feature]: FluentProvider dir="auto"

### ISSUE THREAD

**Issue by Pistonight** [microsoft/fluentui#29382]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Currently, FluentProvider only supports dir="rtl" or dir="ltr" through its props and set the attribute on the underlying div: https://react.fluentui.dev/?path=/docs/components-fluentprovider--default

According to https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir, there is a third valid value "auto" for the dir attribute, which is supported for all browsers

The proposal is to add the "auto" option to the prop type, which sets dir="auto" on the div and let the browser detect the direction

### Have you discussed this feature with our team

No

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by layershifter** [comment]
It can't be `auto` as this value is used define text direction for CSS-in-JS (https://griffel.js.org/react/api/text-direction-provider) and that value can be only `ltr` or `rtl`. Using auto will be confusing in this case. If you would like to apply `dir="auto"`, I suggest to following:

```js
<FluentProvider>
  <div dir="auto"></div>
</FluentProvider>
```
