### ISSUE TITLE
[Feature] Advanced Dropdowns - Filter, Clearable

### ISSUE THREAD

**Issue by gouttierre** [microsoft/fluentui#29399]

**Comment by gouttierre** [comment]
📢"Teams have this planned for the current quarter; they aim to add Clearable variants to Combobox and Dropdown, as well as add more consistent filtering to Combobox. This brings these components to functional parity with v0 and unlocks migration."

**Comment by gouttierre** [comment]
📢"Teams have this planned for the current quarter. There might be an overlap with the `PeoplePicker` component as `Toshie` looks into those `Clearable` and `filtering` `actions`.

**Comment by miroslavstastny** [comment]
@gouttierre - moving the ETA to Jan 2024 as nobody has started working on that yet

**Comment by gouttierre** [comment]
📢"ETA has moved to next year (Jan 2024) as there are no dev resources now."

**Comment by gouttierre** [comment]
📢 
- Shift has started working on implementation this quarter.

**Comment by layershifter** [comment]
Has been implemented in:
- #30033 
- #30046

**Comment by stefan-schweiger** [comment]
Great features! Will we get some documentation on this as well?

**Comment by layershifter** [comment]
@stefan-schweiger yes, it was added in linked PRs:
- https://react.fluentui.dev/?path=/docs/components-combobox--default#clearable
- https://react.fluentui.dev/?path=/docs/components-dropdown--default#clearable
- https://react.fluentui.dev/?path=/docs/components-combobox--default#filtering
