### ISSUE TITLE
[Bug]: popover behaves differently with react 18

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#29402]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 51.85 GB / 63.57 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.78)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/nostalgic-christian-gkp9mr?file=/example.tsx

## Actual Behavior
When using popover with react 18, the animation is gone, and the focus does not change until I focus on the first element again. 

I record a video: 

https://github.com/microsoft/fluentui/assets/39588094/d3399d60-cb22-4ec1-9e02-d7ddba0216db

## Expected Behavior
Should keep the animation as with react 17 and the focus should change accordingly. 

A video with react 17: 

https://github.com/microsoft/fluentui/assets/39588094/c2290a3f-18fc-44d8-951e-4cc88ed4d731

sandbox with react 17:
https://codesandbox.io/s/floral-rain-t4g3vf?file=/example.tsx

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by flora8984461** [comment]
I tried with prod built app the issue seems not happen in prod env.

**Comment by ling1726** [comment]
I can't repro the animation issue, but the focus outline I can repro
