### ISSUE TITLE
[Bug]: MessageBar text is not vertically aligned with icon

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#29416]
In the design spec the icon and text appears to be align along their vertical centers

## React component
<img width="429" alt="msgbar_valign" src="https://github.com/microsoft/fluentui/assets/93940821/4ad9d79b-8a96-4ac5-b022-16a194651f13">

### Design spec

<img width="128" alt="msgbar_spec" src="https://github.com/microsoft/fluentui/assets/93940821/a239915f-d6e7-4ba0-898f-fe209f89abcf">

**Comment by ling1726** [comment]
I think that's rather the problem with upper case vs lower case letters, If I use the same upper case 'D' then I seem to have a centered experience 
![image](https://github.com/microsoft/fluentui/assets/20744592/f8811819-3b6f-4e49-91b4-d2f358afdebd)
