### ISSUE TITLE
[Bug]: [Facepile] Optional overflowButtonProps property is required for overflow button to be displayed

### ISSUE THREAD

**Issue by kapilkashyap** [microsoft/fluentui#29428]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 8.87 GB / 31.69 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.47)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/kapilkashyap/pen/ZEVmavr

### Bug Description

We always have to provide `overflowButtonProps` property (even though it is optional) for the overflow button to be displayed. It does not matter if the property is an `empty object`.

## Actual Behavior
If `overflowButtonProps` property is not provided then overflow button is not displayed when personas overflow

## Expected Behavior
If `overflowButtonProps` property is not provided then overflow button should be displayed when personas overflow

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Hi @kapilkashyap I'm going to close this in favor of a docs PR. Let me know when you have that ready for review!
