### ISSUE TITLE
[Bug]: Combining selection and default in the tree, when setting the height of the tree item, clicking checkbox will trigger the scroll event

### ISSUE THREAD

**Issue by Lomnus** [microsoft/fluentui#29444]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/quirky-dew-sdt9gc?file=/example.tsx

## Actual Behavior
Combining selection and default in the tree and setting the height of the tree item, when the scroll thumb at top then clicking checkbox will trigger the scroll event

## Expected Behavior
Scroll event should not be triggered

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

No

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ValentinaKozlova** [comment]
Hello @Lomnus , could you please provide steps how to reproduce this issue? And expected/actual result with screenshots. Maybe the author would understand it from your description but for others it might be not clear.
That's the result I get:
![image](https://github.com/microsoft/fluentui/assets/11574680/0fd5ab08-c478-4d58-a2b3-df56ba92a23c)
I don't know if it's expected or not.

**Comment by bsunderhus** [comment]
You are combining `Tree` with a `FlatTree` inside of it @Lomnus, This is an invalid case scenario, could you please provide an example by just using one of the 2 components? you cannot combine both base components, they're not compatible. I'll be sure to follow up with some sort of warning if this happens!

**Comment by Lomnus** [comment]
Sure, The example I provided, At first let scroll thumb at top, then click any checkbox, you will find that scroll thumb moved a little.
![image](https://github.com/microsoft/fluentui/assets/50653281/38e9f74e-f6fc-41fd-9253-9278b4f0fba6)

![image](https://github.com/microsoft/fluentui/assets/50653281/ac97d823-8610-42a6-8d3b-df5531475d12)




> Hello @Lomnus , could you please provide steps how to reproduce this issue? And expected/actual result with screenshots. Maybe the author would understand it from your description but for others it might be not clear. That's the result I get: ![image](https://user-images.githubusercontent.com/11574680/273549534-0fd5ab08-c478-4d58-a2b3-df56ba92a23c.png) I don't know if it's expected or not.

**Comment by Lomnus** [comment]
So If combining Tree with a FlatTree is not correct, is there another way to make FlatTree has scroll with large data. I didn't find any help from document, even tried with CSS, Beacuse every tree item level is the brother dom.

> You are combining `Tree` with a `FlatTree` inside of it @Lomnus, This is an invalid case scenario, could you please provide an example by just using one of the 2 components? you cannot combine both base components, they're not compatible. I'll be sure to follow up with some sort of warning if this happens!
