### ISSUE TITLE
[Bug]: 'Spinner' control does not animate in hyper-v or windows sandbox

### ISSUE THREAD

**Issue by Ausxor** [microsoft/fluentui#29457]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 1.79 GB / 12.00 GB
  Browsers:
    Edge: Chromium (117.0.2045.60)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/zdtfs2?file=/example.tsx

## Actual Behavior
The 'spinner' control in v9 does not animate when viewed from a virtual machine. I can replicate this in both hyper-v VM, and in windows sandbox. The spinner control appears as a blue circle, no animation.

## Expected Behavior
The animator would spin. i.e. Bootstrap spinner has not issues in the same environment. https://getbootstrap.com/docs/4.2/components/spinners/

### Requested priority

Normal

### Products/sites affected

MS Internal App

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by tomi-msft** [comment]
Hi @Ausxor, thanks for filing this issue. First can you check if reduced-motion is active in the vm? This setting could be active, which means that the Spinner animation will be stopped after one iteration

**Comment by Ausxor** [comment]
@tomi-msft Thanks for the comment, that resolved the issue. As per https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion, I had animation effects disabled in windows 11 on the VM.

The Mozilla article mentions this feature is for accessibility purposes, although the OS settings that it leverages are also used for performance reasons. This seems to create a conflict. Compared to window transition or popup effects for instance, disabling the spinner creates a jarring experience for users as it is arguably serves a more functional purpose. When disabled it is just a circle that doesn't move, and makes the application look stuck. This is an odd default experience in a VM.

Would there be a way to meet both the accessibility requirements, and the functional requirements?

For example, bootstrap solve this problem by reducing the animation speed of the spinner when reduced motion is enabled. See https://getbootstrap.com/docs/5.0/components/spinners/.
