### ISSUE TITLE
[Bug]: Dropdown is not closed when scroll and click outside

### ISSUE THREAD

**Issue by NataliaKravcheniaTR** [microsoft/fluentui#29456]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:                                                     
    OS: Windows 10 10.0.19044                                 
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 9.25 GB / 32.00 GB                                
  Browsers:                                                   
    Chrome: 107.0.5304.0.                                     
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.60) 
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/wqhl76?file=/example.tsx

### Bug Description

https://react.fluentui.dev/?path=/docs/components-dropdown--default#custom-options
1, Open drop down 
2. Use scroll bar on the right to scroll **(not mouse wheel)**
3. Click anywhere out of the drop-down

## Actual Behavior
 drop-down is not closed

## Expected Behavior
drop-down should be closed

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@NataliaKravcheniaTR I can't reproduce this in the codesandbox or docs site on macOS Edge/Chrome or Windows Edge/Chrome. Could you provide more details about the OS and browser this is happening on, and any other specifics about the interaction you're doing to get it to reproduce? The details in the bug seem potentially inaccurate (I don't believe we still support Edge Spartan, for example, and I don't currently have Windows 10 to test on, so if it's specific to that I may need your help reproducing it)

**Comment by NataliaKravcheniaTR** [comment]
@smhigley I'm able to reproduce it on MacOs Chrome
I made a recording:
https://drive.google.com/file/d/10efF6ZFxHQqK4TKly_yAFGhiaRKQDSdN/view?usp=sharing

**Comment by frankyphs** [comment]
@NataliaKravcheniaTR , have you solved this problem? I think i have the same problem as you. The difference is, i insert Button component on option, when i click it and click outside, the option is not close too. Do you have advice?

**Comment by kushagrms** [comment]
Any solution yet? I am able to reproduce it as well.
