### ISSUE TITLE
[Bug]: Easing curve tokens do not match design spec

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#29473]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
-
```

### Are you reporting Accessibility issue?

no

### Reproduction

-

## Actual Behavior
```ts
export const curves: CurveTokens = {
  curveAccelerateMax: 'cubic-bezier(1,0,1,1)',
  curveAccelerateMid: 'cubic-bezier(0.7,0,1,0.5)',
  curveAccelerateMin: 'cubic-bezier(0.8,0,1,1)',
  curveDecelerateMax: 'cubic-bezier(0,0,0,1)',
  curveDecelerateMid: 'cubic-bezier(0.1,0.9,0.2,1)',
  curveDecelerateMin: 'cubic-bezier(0.33,0,0.1,1)',
  curveEasyEaseMax: 'cubic-bezier(0.8,0,0.1,1)',
  curveEasyEase: 'cubic-bezier(0.33,0,0.67,1)',
  curveLinear: 'cubic-bezier(0,0,1,1)',
};
```

## Expected Behavior
```ts
export const curves: CurveTokens = {
  curveAccelerateMax: 'cubic-bezier(0.9,0.1,1,0.2)',
  curveAccelerateMid: 'cubic-bezier(1,0,1,1)',
  curveAccelerateMin: 'cubic-bezier(0.8,0,0.78,1)',
  curveDecelerateMax: 'cubic-bezier(0.1,0.9,0.2,1)',
  curveDecelerateMid: 'cubic-bezier(0,0,0,1)',
  curveDecelerateMin: 'cubic-bezier(0.33,0,0.1,1)',
  curveEasyEaseMax: 'cubic-bezier(0.8,0,0.2,1)',
  curveEasyEase: 'cubic-bezier(0.33,0,0.67,1)',
  curveLinear: 'cubic-bezier(0,0,1,1)',
};
```

## Background
The values were added to the library in #22607 in April 2022. Those were based on v0 tokens (originally added in #13046 in May 2020) but do not much Fluent 2 design.

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by paulgildea** [comment]
Do folks have any concerns about this may be a visual break? Not sure if teams do motion based testing assuming the timings staying the same - it's really just the curves that are changing.

**Comment by AkiraVoid** [comment]
@paulgildea This whole library is based on Fluent Design Language, which means the behavior of this lib should follow it precisely. Thus, this change should be considered as a bug fix, and no one will think a bug fix might be a breaking change, and everyone who used a bug as feature in their code should fix it since it's not a desired way to code.

*All lines above are based on my own opinions, I am not intent to force anyone, but to introduce a way of thinking.*

**Comment by robertpenner** [comment]
`react-northstar` easing curves need the same fix. I'll create a separate PR so the change can be managed independently. @miroslavstastny Should we add that as a note to this bug, or create a new bug for northstar?

https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-northstar/src/themes/teams/animations/timingFunctions.ts

**Comment by miroslavstastny** [comment]
I do not think this is worth fixing in `react-northstar`. We only fix critical bugs there, this has been there forever.

**Comment by robertpenner** [comment]
For reference, [this tokens superset Figma](https://www.figma.com/file/KB9oUjMKen2cKnyPG7RgdS/Design-tokens-superset?type=design&version-id=978048725&node-id=1297-14622&mode=design&t=0oqSmd7rSX9qyCtx-0) has these incorrect easing curve values added at precisely July 13, 2021. But PR #13046 predates this file by over a year.
