### ISSUE TITLE
[Feature]: Change thickness of Tab Stroke

### ISSUE THREAD

**Issue by Undianer** [microsoft/fluentui#29475]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

In the Tablist component the Tab's stroke uses a variable in order to define the width (thickness) of it, namely `var(--strokeWidthThicker)`
There are also the vars `strokeWidthThick` and `strokeWidthThickest`, but  `strokeWidthThicker` is used per default, and there is no way in changing the thickness, except changing the css itself and access the vars via `tokens`.

It would be nice to be able to change it simply as property, like `size='small'` you could write `stroke=''thick'`. Another way would simply be to change the stroke size with the `size `property, since this property is only affecting the spacing.

An interesting point is, that Teams itself seems to use another thickness as the default thickness. Did they achieve that by changing the css? If they had to change it this way, why would they not make this propose to the fluent team?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by GeoffCoxMSFT** [comment]
@Undianer Thanks for explaining the feature.  The Tab styles for the indicator do change their stroke thickness, padding, etc based on a size variable.  The supported sizes are small, medium, and large.  For each size, a different design token (like strokeWidthThick or strokeWidthThicker) are applied.  The design specification details each of the tokens to use for each size.  You can change the styles via makeStyles and passing a className value to each tab.
