### ISSUE TITLE
[Bug]: CI should pass by default for create-package

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#29484]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 71.72 GB / 127.71 GB
  Browsers:
    Edge: Chromium (117.0.2045.47)
```

### Are you reporting Accessibility issue?

no

### Reproduction

create-package generator

## Actual Behavior
CI fails after creating a package, it should pass by default and the error doesn't give much information where it comes from:
![image](https://github.com/microsoft/fluentui/assets/5953191/c3e6e04a-66ea-49b0-8be5-cc719a49f407)

This happens due to stories being empty and linting not finding any files. A workaround is creating a folder of a component you'll know you will add and adding a index.stories.tsx with `export {}`. Though this is not sustainable for the generator.

## Expected Behavior
CI should pass after creating a package.

### Requested priority

Low

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
repro: 

`yarn nx generate @fluentui/workspace-plugin:react-library --name=react-one-two --owner=@microsoft/fluentui-react-build`

`yarn workspace @fluentui/react-one-two-preview lint`

**Comment by Hotell** [comment]
this is the culprit ( just eslint task ) 

<img width="692" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/fd9ac212-db34-44db-9a25-2ba3d56b6b06">
