### ISSUE TITLE
[Feature]: Supporting textarea for the Combobox component to allow wrapping long texts in the search input

### ISSUE THREAD

**Issue by aibek-draftwise** [microsoft/fluentui#29493]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

I would like to propose a feature to switch between input and textarea HTML elements to be able to support multiline inputs and wrapping long texts in the search inputs

### Have you discussed this feature with our team

no

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by tudorpopams** [comment]
Hello @aibek-draftwise, we discussed this proposal internally and there could be some a11y related challenges to this (ie form submission). Have you considered using the [v9 Combobox](https://react.fluentui.dev/?path=/docs/components-combobox--default) for this use case?
