### ISSUE TITLE
[Feature]: Removing overflow items without unmounting an overflow item component

### ISSUE THREAD

**Issue by lekoaf** [microsoft/fluentui#29509]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 6.0 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 16.86 GB / 31.04 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
Browsers:
    Chrome: 116.0.5845.140
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/sandbox/youthful-aj-92tq3t

## Actual Behavior

When removing items from an overflow menu, the menu bugs out with an empty menu.

If I had only used the buttons to remove the items, it works.
![overflow_button](https://github.com/microsoft/fluentui/assets/7765599/f3a20eca-7252-4603-a9f3-0c1a5f176608)

But when using the menu, it bugs out.
![overflow](https://github.com/microsoft/fluentui/assets/7765599/3475f471-de54-4c85-98c9-442ce93e7fad)

## Expected Behavior

Overflow menu should dissapear when enough items have been removed.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by lekoaf** [comment]
> Are you willing to submit a PR to fix? no

I could be willing, but I don't know where the issue is. Haven't dived in to the Fluent source code.

**Comment by lekoaf** [comment]
The "Status: In PR" label doesn't seem to be correct. I think @ling1726 accidently mentioned the wrong issue in his PR.

**Comment by ling1726** [comment]
The design of the overflow library never took into account removal of items from the menu, only from the actual overflow set. The reason being that, the requirements were mainly driven by a toolbar being overflown.

This is a valid feature request and we should see how to prioritize this

**Comment by lekoaf** [comment]
@ling1726 @miroslavstastny, this issue shouldn't be closed. It was closed because it was accidently mentioned in a PR.
