### ISSUE TITLE
[Bug]: Loss of data in input box of Modal box

### ISSUE THREAD

**Issue by bovinphang** [microsoft/fluentui#29511]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
    Memory: 3.93 GB / 15.87 GB
  Browsers:
    Chrome: 117.0.5938.149
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.60)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/modal

## Actual Behavior
I entered data in the input box of the form in the Modal box, clicked on "Restore Down" in the upper right corner of the browser, narrowed the browser window, and then enlarged the browser window, and the data in the input box was lost.

![test2](https://github.com/microsoft/fluentui/assets/17447895/d4ad377b-dc83-4eb8-9fb5-7825f8fe111d)

## Expected Behavior
Zooming in and out of the browser window leaves the data in the input box unchanged.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.
```[tasklist]
### Tasks
```

**Comment by behowell** [comment]
Hi @bovinphang, please link a codesandbox with a repro of this behavior. Thanks!
