### ISSUE TITLE
[Bug]: selectedKey doesn't work in pivot component

### ISSUE THREAD

**Issue by Lijiaoa** [microsoft/fluentui#29531]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
pivot selectedKey doesn't work in fluent version: "@fluentui/react": "^8.105.3"

#https://github.com/microsoft/fluentui/issues/13456
```

### Are you reporting Accessibility issue?

None

### Reproduction

any

## Actual Behavior
fill this out

## Expected Behavior
fill this out

### Logs

```shell
any
```

### Requested priority

Blocking

### Products/sites affected

any

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by rickynyairo** [comment]
By default, the Pivot automatically maintains the currently selected key and you should only provide that property if you also have the logic to maintain the currently selected key. If instead you mean to have a preselected/default pivot item, you should use the defaultSelectedKey property. Do you mind sharing a sample of how you are using it?
