### ISSUE TITLE
[Bug]: Two or more dropdown are showed at the same time 

### ISSUE THREAD

**Issue by dianavoyanets** [microsoft/fluentui#29576]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 305.71 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
Browsers:
    Chrome: 118.0.5993.70
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://zw4h7h.csb.app/

[edit -behowell] Also repros on the documentation site: https://react.fluentui.dev/?path=/docs/components-dropdown--default#appearance

## Actual Behavior
[iPhone] Two and more filter dropdowns can be opened

## Expected Behavior
The other opened dropdown is closed when another dropdown is opened

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by kushagrms** [comment]
@behowell I am able to reproduce it on desktop as well
