### ISSUE TITLE
Performance: Improve the light house perf score of “30k Data points area chart” from 50 to 90.

### ISSUE THREAD

**Issue by AtishayMsft** [microsoft/fluentui#29571]

**Comment by AtishayMsft** [comment]
@ankityadav4 Could you resolve this issue adding your findings.

**Comment by ankityadav4** [comment]
The Perf score for the Area Chart has now reached 71. Below are the findings related to this task:

1.Previously, we did not enable the PerfOptimization flag for this scenario. With the flag now enabled, the score has improved to 71.

2.We experimented with strategies such as avoiding multiple iterations of the code and refraining from calling d3stack when only a single series is present. However, these changes did not yield significant improvements in the LH score. As a result, we have decided not to proceed with these modifications.
