### ISSUE TITLE
[S360 Alert]: Migrate 'Fluent UI React - CI' to a governed template

### ISSUE THREAD

**Issue by AtishayMsft** [microsoft/fluentui#29580]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
NA
```

### Are you reporting Accessibility issue?

no

### Reproduction

Security alert. Steps to fix are in the wiki below

## Actual Behavior
We have received a S360 alert to Migrate 'Fluent UI React - CI' to a governed template as part of the react-charting library with an ETA of 11/01/2023.
Here is a screenshot for the alert.
![image](https://github.com/microsoft/fluentui/assets/98592573/a598c3a4-9be2-4198-96b6-cfd1bbec16f2)
Here is the document guiding migration to 1ESPT: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/migration/overview

## Expected Behavior
S360 alert is resolved.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by AtishayMsft** [comment]
Quick update on this issue. 
I removed the dependency on the **Fluent UI React - CI** pipeline from the Charting product catalog which was causing this s360 alert to show under my name.
This alert is now showing under @JustSlone's alerts. Please ack and prioritize it accordingly.

**Comment by Hotell** [comment]
fixed
