### ISSUE TITLE
[Bug]: ChoiceGroup is adding display: block user agent style

### ISSUE THREAD

**Issue by ppgovekar** [microsoft/fluentui#29582]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Recently noticed that Fluent UI ChoiceGroup has a div with display: block which modifies our flex style added on root. Please remove this styling:
div {
    display: block;
}
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup

## Actual Behavior
Getting an extra div with display: block under root style

## Expected Behavior
No div with display: block

### Requested priority

High

### Products/sites affected

Azure Portal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @ppgovekar, we aren't able to modify the tree structure of ChoiceGroup, as that would be a breaking change. 

You can style the div under the root using a `'> div'` child selector, such as:
```jsx
<ChoiceGroup
  styles={{ 
    root: {
      "> div": { 
        display: "flex",
      }
    },
  }}
>
```

Let me know if that works for you. Thanks!
