### ISSUE TITLE
[Bug]: dropDown inconsistency when rendering multiple dropdown with OnOpenChange property

### ISSUE THREAD

**Issue by ManoharRTTR** [microsoft/fluentui#29591]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:                                                     
    OS: Windows 10 10.0.19044                                 
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 9.25 GB / 32.00 GB                                
  Browsers:                                                   
    Chrome: 107.0.5304.0.                                     
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.60) 
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/quiet-sky-5s74hx?file=/example.tsx

## Actual Behavior

When multiple dropdown is rendered with onOpenChange property we see both the dropdown opened together.

## Expected Behavior

only one dropdown is opened each time

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Gaurav-jo1** [comment]
I attempted to replicate the issue, and it seems that utilizing setState directly within onOpenChange is triggering the bug. Below is the modified rendition of the code for the dropdown.

https://stackblitz.com/edit/vitejs-vite-azumjh?file=src%2FApp.tsx

**Comment by behowell** [comment]
Hi @ManoharRTTR, I can't repro the issue using the linked CodeSandbox https://codesandbox.io/s/quiet-sky-5s74hx?file=/example.tsx . Was the CodeSandbox modified since the issue was logged? Based on the comment by @Gaurav-jo1, it sounds like it may have been a bug in the repro code, and not in Dropdown itself.

Is this still an issue?
