### ISSUE TITLE
[Bug]:  Textfield with type ="number" should not accept letter "e"

### ISSUE THREAD

**Issue by Ivesonchen21** [microsoft/fluentui#29619]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Xeon(R) W-2245 CPU @ 3.90GHz
    Memory: 43.25 GB / 63.59 GB
  Browsers:
    Edge: Chromium (118.0.2088.57)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/Ivesonchen21/pen/ExraZQR

## Actual Behavior
fill this out

Typing "e" after selecting the Textfield with type ="number", it's accepting letter (only 'e') when only numbers should be allowed.

## Expected Behavior
fill this out

Only numbers will be allowed in textfield.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
This comes from the fact that `e` is a [mathematical constant](https://en.wikipedia.org/wiki/E_(mathematical_constant)). You can see that it is also accepted by the regular HTML `<input type="number" />` in the [MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number). As such, I'll be resolving this as `Not an issue`.
