### ISSUE TITLE
[Bug]: Slider does not show specified maximum decimal value

### ISSUE THREAD

**Issue by Ramakrishnan24689** [microsoft/fluentui#29621]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 2.54 GB / 15.85 GB
  Browsers:
    Edge: Chromium (118.0.2088.61)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/charming-wing-s25wz7?file=/example.tsx

## Actual Behavior
1) Open the [codesandbox](https://codesandbox.io/s/charming-wing-s25wz7?file=/example.tsx) and move the slider(Min 30.5 & Max 98.8) to maximum value.
2) Slider shows a maximum value of 98.5, even though the maximum value specified is 98.8

## Expected Behavior
Slider should show the specified maximum value which is 98.8(in the sandboxcode example)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
This comes from the behavior of the native `<input type="slider">` control. By default, it increments in steps of 1.0 above its min value (the min is 30.5 in your example, so it increments to 31.5, 32.5, ..., 98.5).

The way to fix this is to set the `step` to a value that evenly divides `max - min`, which is probably 0.1 in this example:
```jsx
<Slider step={0.1} />
```

Unfortunately, setting `step` on the Slider component _also_ enables tick marks to be shown, which is likely not desirable. If you want to change the `step` without displaying tick marks, you'll need to set it directly on the input slot, like so: 
```jsx
<Slider input={{ step: 0.1 }} />
```

Here's a modified codesandbox showing that working: https://codesandbox.io/s/confident-albattani-jz2zzh?file=/example.tsx

@micahgodbolt can you confirm if there's any officially supported way to set the `step` prop on slider without showing tick marks?
