### ISSUE TITLE
[Bug]: Switch, On form reset, change checked state for switch but not triggering onChange event

### ISSUE THREAD

**Issue by pradeept95** [microsoft/fluentui#29622]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 4.91 GB / 16.00 GB
  Browsers:
    Internet Explorer: 11.0.17763.2989
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/shy-silence-htqkp4?file=/example.tsx

### Bug Description

Setps:

- Open Minimal Reproduction link
- Check the unchecked Switch
- Click on Reset Button

## Actual Behavior
If Reset is clicked on the form, switch change the internal state to default or initial state, but it does not trigger the onChange event so external managed state will be out of sync with internal state.

## Expected Behavior
On form reset switch should trigger the onChange Event

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
This is not a bug. This behavior comes from the native HTML input element. The change event does not fire when the form is reset--see this pure JS demo of the same scenario as in your repro: https://codepen.io/behowell/pen/dyaoGPB?editors=1011. You'll need to handle this case in your onReset handler. 

You may want to consider using a controlled Switch control, and adding custom code in your onReset handler to set your state back to the default. For more info about controlled components, see https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable
