### ISSUE TITLE
[Bug]: Combobox autocomplete interferes with my search in the search box

### ISSUE THREAD

**Issue by 15MariamS** [microsoft/fluentui#29630]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 37.45 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 16.5.2
```

### Are you reporting Accessibility issue?

no

### Reproduction

(havent been able to on codesandbox)

## Actual Behavior
autocomplete / autocorrect makes it difficult for me to search with the search on ComboBox

## Expected Behavior
I want to turn off the autocomplete / autocorrect feature
<img width="327" alt="autocomplete" src="https://github.com/microsoft/fluentui/assets/81782111/79db080a-22d1-4039-ad00-b18105a72b35">
<img width="322" alt="Screenshot 2023-10-24 at 7 37 24 PM" src="https://github.com/microsoft/fluentui/assets/81782111/d4467ab3-b86e-4145-9dfb-8594c8ba72d4">

In `<Combobox/>`, I've already set these to "off":
```
autoComplete="off"
autoCorrect="off"
autoCapitalize="off"
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @15MariamS, Combobox does not have an autocomplete feature like the one in your screenshot. Is it coming from your browser or device's OS? You'd need to figure out how to disable the platform feature, since it's not part of FluentUI.

If I've misunderstood and this is an issue with Combobox itself, please provide a repro link so we can investigate it. Thanks.
