### ISSUE TITLE
[Bug]: @fluentui/react-datepicker-compat is missing the spec

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#29634]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A

## Actual Behavior

https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-datepicker-compat/docs/Spec.md - is empty

## Expected Behavior

https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-datepicker-compat/docs/Spec.md - is filled

### Logs

```shell
N/A
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
DatePicker shouldn't have a spec since we didn't develop the component, we only ported it. It has been removed in #29764
