### ISSUE TITLE
[Bug]: Arrow navigation happening in background when v9 Dialog is wrapped with v8 focus zone

### ISSUE THREAD

**Issue by haribaz** [microsoft/fluentui#29657]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 13.27 GB / 31.83 GB
  Browsers:
    Edge: Chromium (118.0.2088.57)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/vibrant-snow-ddq2zn?file=/example.tsx

## Actual Behavior
When a v9 Dialog component wrapped with a v8 Focus Zone, and I try to use the arrow keys to navigate when the Dialog is open, the navigation happens outside of the Dialog.

## Expected Behavior
The navigation must happen within the Dialog

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
As an easy solution @haribaz I'd suggest migrating from `FocusZone` to using tabster arrow navigation https://codesandbox.io/s/elastic-dream-r5pdn2?file=/example.tsx

**Comment by haribaz** [comment]
It is not viable to move out of using FocusZone for my use case
