### ISSUE TITLE
[Bug]: Performance Issue with Combo Box Containing 3000+ options - in Fluent UI 9

### ISSUE THREAD

**Issue by voidsteed** [microsoft/fluentui#29683]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 8.13 GB / 31.71 GB
  Browsers:
    Edge: Chromium (118.0.2088.69)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/fluent-ui-react-components-v9-forked-jtjxf8?file=/components/ComboboxExample.tsx:439-542

## Actual Behavior
when click on ComboBox, it freezes

## Expected Behavior
show 3000 list item for selecting in ComboBox

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by voidsteed** [comment]
any update on this?

**Comment by spmonahan** [comment]
A list that size really needs to be virtualized. We have an [example that shows how to virtualize `ComboBox`](https://react.fluentui.dev/?path=/docs/components-combobox--default#virtualizer).
