### ISSUE TITLE
Unable to change reference from static2.sharepointonline.com in SPFx project

### ISSUE THREAD

**Issue by jlara005** [microsoft/fluentui#29697]
### Libraries

Node version: v8.17.0

Package version(s):
- @office-ui-fabric-react: ^5.135.6
- @microsoft/sp-core-library: ~1.4.0
- @microsoft/sp-application-base: ~1.4.0
- react: 15.6.2
- @uifabric/styling: 5.37.0

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
    Memory: 25.51 GB / 32.00 GB
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (118.0.2088.69)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://github.com/jlara005/TestAppCustomizer

### Bug Description

I am working on a SharePoint SE on-premises SPFx application customizer project and because of security reasons there is no internet access. The fonts keep being fetched from https://static2.sharepointonline.com/files/fabric/assets/fonts.

I have tried to set the fontBaseUrl window property before all imports on the main entrypoint file TestAppCustomizerApplicationCustomizer.ts file and the reference to static2.sharepointonline.com still remains. Seems like the imports are being evaluated before the property is being set. How can I set this on an application customizer SPFx project?

Actual behavior:
- Several CSS/Font assets have to be fetched from CDN every time.
- Adding the following property to the window object before all imports on the main entrypoint file doesn't work
window.FabricConfig = {
    fontBaseUrl: 'https://mycdn.com'
};
- Network requests stay same. There is no request for own CDN.

Expected behavior:
- Setting the property will allow override to default url
- All CSS/Font dependencies should be included as part of the NPM package.

![CDN](https://github.com/microsoft/fluentui/assets/29823126/2c0aa1d4-2027-4375-ada0-d74e7864601c)

### Related Issues
This issue is related to 11477 which was never really given a solution: https://github.com/microsoft/fluentui/issues/11477

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
The requirement for the CDN override to work is to change the `fontBaseUrl` before fabric is loaded, as described in https://github.com/microsoft/fluentui/issues/10363#issuecomment-572908081.

This codesandbox shows that in that case the custom CDN is used: https://codesandbox.io/s/customizing-fabric-icons-and-fonts-forked-8scp75?file=/src/alternativeCDNs.tsx
<img width="447" alt="image" src="https://github.com/microsoft/fluentui/assets/9615899/73d843ee-a4c3-4d3a-92f8-7e63b7448e10">


I would suggest you to follow up in the SPFx issue SharePoint/sp-dev-docs/issues/9307
