### ISSUE TITLE
[Bug]: Combobox doesn't close when clicked outside if its scrollbar is clicked

### ISSUE THREAD

**Issue by dmytroua** [microsoft/fluentui#29701]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Xeon(R) W-2245 CPU @ 3.90GHz
    Memory: 31.60 GB / 63.59 GB
  Browsers:
    Edge: Chromium (118.0.2088.46)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/8n3rhp?file=src%2Fexample.tsx

## Actual Behavior
After clicking on the scrollbar of the Combobox's listbox, the combobox no longer closes automatically if clicked outside of it. Also, pressing the Esc key won't close it.

![Combobox not closing on focus loss](https://github.com/microsoft/fluentui/assets/8906160/67270a4f-d3c4-4072-bc47-5c442b8d8695)

## Expected Behavior
The combobox should close automatically if clicked outside of it or the Esc key is pressed.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
I do not understand why the event listener is removed out of the condition, @khmakoto any idea?
https://github.com/microsoft/fluentui/blob/787e8e99a558d76ac2c2bdfe9f1537cf723b74cb/packages/react-components/react-combobox/src/utils/useTriggerListboxSlots.ts#L99-L104

**Comment by khmakoto** [comment]
I think I might know why this is happening, I'm assigning this bug to myself and will work on it soon.
