### ISSUE TITLE
[Bug]: useMotion() has multiple renders on enter

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#29719]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/wild-worker-nqwj6s

### Bug Description

- Load an example
- Clean console logs
- Trigger visibility
- Check logs again

## Actual Behavior

```
App:render {motionType: "unmounted"}
App:render {motionType: "unmounted"}
App:render {motionType: "entering"}
App:render {motionType: "idle"}
```

(double render for "unmounted state")

## Expected Behavior

```
App:render {motionType: "unmounted"}
App:render {motionType: "entering"}
App:render {motionType: "idle"}
```

Also, curious where "entered" state is gone.

### Logs

```shell
N/A
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
cc @marcosmoura
