### ISSUE TITLE
useMotion() design forces to control state on an upper level to change animations

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#29718]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

see in text

### Bug Description

Currently `useMotion()` API is exposed in `Drawer` & `InlineDrawer`. These components are controlled only i.e. you need to pass `open` prop to change components' behavior as there is no triggers API. There is nothing wrong with that.

That's why `useMotion()` works there nicely:
- https://react.fluentui.dev/?path=/docs/preview-components-drawer--default#motion-custom
- https://codesandbox.io/s/h7xw3x?file=src%2Fexample.tsx

The state of a component is controlled anyway, example is below:

```ts
  const [open, setOpen] = React.useState(false);
  const motion = useMotion<HTMLDivElement>(open);
  const drawerMotionClassNames = useMotionClassNames(
    motion,
    useDrawerMotionStyles()
  );
```

However, with others components, for example Dialog, this approach does not work so nicely:
- it forces to control state
- state should be controlled somewhere above in a React tree i.e. updates root gets moved

### Dialog by default

```tsx
// React tree
<App>
  <Dialog> {/* ⚛️ update root */}
    <DialogTrigger />
    <DialogSurface />
  </Dialog>
</App>
```

https://codesandbox.io/s/billowing-browser-qzqtrj?file=/src/example.tsx

#### Log on dialog open

```
render:<Content /> 
```

### Dialog with a custom animation

```tsx
// React tree
<App>  {/* ⚛️ update root */}
  <Dialog>
    <DialogTrigger />
    <DialogSurface />
  </Dialog>
</App>
```

https://codesandbox.io/s/adoring-bash-n7gl4m?file=/src/example.tsx

#### Log on dialog open

```
render:<Root /> 
render:<Content /> 
render:<Content /> 0
render:<Content /> 1
render:<Content /> 2
render:<Content /> 3
render:<Content /> 4
render:<Content /> 5
render:<Content /> 6
render:<Content /> 7
render:<Content /> 8
render:<Content /> 9
render:<Root /> 
render:<Content /> 
render:<Content /> 0
render:<Content /> 1
render:<Content /> 2
render:<Content /> 3
render:<Content /> 4
render:<Content /> 5
render:<Content /> 6
render:<Content /> 7
render:<Content /> 8
render:<Content /> 9
```

The worst part there is that `useMotion()` triggers also own state updates to apply a proper animation that causes multiple renders.

The workaround is obvious: create `RootDialog` component and push updates root down again i.e.:

```tsx
// React tree
<App>
  <RootDialog>  {/* ⚛️ update root */}
    <Dialog>
      <DialogTrigger />
      <DialogSurface />
    </Dialog>
  </RootDialog>
</App>
```

However, this contract is implicit and causes performance issues by design.

## Actual Behavior

- Applying custom animations changes the root of updates
- The root gets multiple re-renders

## Expected Behavior

- Updates root remains the same
- No changes in lifecycle of other components

### Logs

```shell
N/A
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
cc @marcosmoura
