### ISSUE TITLE
[Feature]: Loading state for Button

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#29724]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Loading state for Button, Figma design is here: https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?type=design&node-id=4428-18424&mode=design&t=jfMkQ1vbx6E9RHKK-4
<img width="561" alt="image" src="https://github.com/microsoft/fluentui/assets/48726002/d3764cfb-465d-4fcc-bbc5-401ff8d44a2e">

Design Note: We want to make sure that the button is not interact-able while it is in Loading and Success state, as to prevent the user from re-triggering the same process that is already taking place. However, we're hesitant to use the disabled state styling as we want the foreground elements to still meet contrast. 

Sounded like at the time of Button implementation, Spinner component was not available yet and this could be done by passing Spinner into the icon slot. We've been getting a handful of requests from product teams for a loading state. 

### Have you discussed this feature with our team

Yes, Makoto Burgos

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by balaji-sivasakthi** [comment]
@daisygeng I would like to work on this issue?

**Comment by gouttierre** [comment]
> @daisygeng I would like to work on this issue?

@balaji-sivasakthi: Thank you for your willingness to contribute to this feature request. This is great news! Please, go ahead with the contributions and let us know when you are ready to submit your PR. 
cc @daisygeng, @JustSlone , @khmakoto.

**Comment by chrisdholt** [comment]
@gouttierre this seems like it’s related to the content of the button - does this need to be baked into an existing or new component at all?

**Comment by lokeshvasnik** [comment]
I would like to contribute

**Comment by SantoshPisini** [comment]
I would like to take it up!

**Comment by khmakoto** [comment]
We have decided as a team to show this as a recipe in our docs and not bundle in this behavior into the button component, as it complicates the component without bringing a lot of value due to the minimal customizations needed to make this work correctly.
