### ISSUE TITLE
[Feature]: Expand Text `as` prop support to include semantic elements

### ISSUE THREAD

**Issue by stonebk** [microsoft/fluentui#29749]
### Library

~~React Northstar / v0 (@fluentui/react-northstar)~~
React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

The `Text` component supports changing the underlying element with the `as` prop:

![MicrosoftTeams-image (1)](https://github.com/microsoft/fluentui/assets/1432010/7a53b29b-9e05-4014-b34b-297a6d475b4b)

The `as` prop however is missing some common semantic text elements:

* [`strong`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)
* [`b`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b)
* [`em`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em)
* [`i`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i)

Trying to use one of these semantic elements like `strong` works, but results in a type error:

![MicrosoftTeams-image (1)](https://github.com/microsoft/fluentui/assets/1432010/a165ed8c-82ce-42d5-a1c5-109863aae161)

Semantic elements like this are especially important for copy/paste scenarios with rich text editors -- without semantic elements, you often lose formatting when copy/pasting content.

### Have you discussed this feature with our team

Geoff Cox

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by bsunderhus** [comment]
IMO I agree with this change, I don't see why not we can't support semantic elements that make sense for `Text` in this case, but... This feature request might be considered a breaking change, as we stated on previous RFC's that extending unions *are* breaking changes: https://github.com/microsoft/fluentui/pull/29296#pullrequestreview-1697954406

**Comment by stonebk** [comment]
> IMO I agree with this change, I don't see why we can't support semantic elements that make sense for `Text` in this case, but... This feature request might be considered a breaking change, as we stated on previous RFC's that extending unions **are** breaking changes: [#29296 (review)](https://github.com/microsoft/fluentui/pull/29296#pullrequestreview-1697954406)

I think it should be safe to extend the type here since it is the user providing the new value. The case you referenced is a bit different because the type being extended is an event passed to a user defined callback. In that case, if the union changed, the event passed back could be a different type and break the user callback. Here though, the user is the one who would have to provide the new value so there is no chance for things to break -- it should be backwards compatible.

**Comment by bsunderhus** [comment]
> > IMO I agree with this change, I don't see why we can't support semantic elements that make sense for `Text` in this case, but... This feature request might be considered a breaking change, as we stated on previous RFC's that extending unions **are** breaking changes: [#29296 (review)](https://github.com/microsoft/fluentui/pull/29296#pullrequestreview-1697954406)
> 
> I think it should be safe to extend the type here since it is the user providing the new value. The case you referenced is a bit different because the type being extended is an event passed to a user defined callback. In that case, if the union changed, the event passed back could be a different type and break the user callback. Here though, the user is the one who would have to provide the new value so there is no chance for things to break -- it should be backwards compatible.

Yes @stonebk, after some quick investigation I can agree that this won't be a breaking change because all the semantic elements 
suggested here do not have custom interfaces, they're all defined as `React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>` which is a subset of the current signature! if we were to include something like `a` then it would be a problem.
