### ISSUE TITLE
[Bug]: FlatTree - Using custom method for onCheckedChange removes onCheckedChange default behavior

### ISSUE THREAD

**Issue by chiim** [microsoft/fluentui#29774]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 12.75 GB / 31.64 GB
  Browsers:
    Edge: Chromium (119.0.2151.44)
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/competent-thompson-xnmzgf

## Actual Behavior
When assigning a method to onCheckedChange, checkboxes are no longer checked on click. Seems like the onCheckedChange default behavior is overridden.

## Expected Behavior
Checkboxes should still be checked on click, and my method should extend the default behavior of onCheckedChange instead of overriding it.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
`useHeadlessFlatTree_unstable` hook returns you `onCheckedChange` handler as part of the tree props which you need to apply to the `FlatTree`. This handler is responsible for managing the exapnded/collapsed state. In your sandbox example, you overwrite the handler with your custom one:

```jsx
const customOnChange = () => {}
//...
<FlatTree
  {...flatTree.getTreeProps()}
  aria-label="Selection"
  onCheckedChange={customOnChange} // ❌ overwrites the handler from getTreeProps()
>
```

If you want to pass your custom handler and still let the component controls its state, you need to call the built-in handler as well. One of the possible ways is to use `mergeCallbacks()` utility:
```jsx
import {mergeCallbacks} from "@fluentui/react-components";

//...

const treeProps = flatTree.getTreeProps()
const mergedOnChange = mergeCallbacks(treeProps.onCheckedChange, customOnChange);

//...

<FlatTree
  {...flatTree.getTreeProps()}
  aria-label="Selection"
  onCheckedChange={mergedOnChange} // 👍
>
```
