### ISSUE TITLE
[Bug]: Package/Component creation bugs

### ISSUE THREAD

**Issue by george-cz** [microsoft/fluentui#29775]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A - internal bug report

### Bug Description

Found a few bugs in package and component creation with `yarn create-package` and `yarn create-component`. Both can be easily reproduced by trying to create a package and a component and build it.

## create-package
- the new package is missing in `tsconfig.base.json` and `tsconfig.base.all.json`

## create-component
- the `<componentName>Styles_unstable` is called twice, see https://github.com/microsoft/fluentui/pull/29452/files#diff-d7f3107892be3bbccf7579fb77ca3a5a090c5fee8c1e145afb508e961e13859eR16
- the types are not automatically added to `CustomStyleHooksContext.ts`, which results in a failed component creation
- `@fluentui/react-shared-contexts` not automatically added to the new component's `package.json` file as dependency, causing build to fail

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
> create-package
>
> the new package is missing in tsconfig.base.json and tsconfig.base.all.json

I cannot repro this

```
yarn create-package --name react-zooooom  
```

<img width="1475" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/127e2160-0489-4efa-a741-03ce2c4de359">
<img width="1459" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/b4a65f17-747d-4927-8013-a7222090d4a7">

**Comment by Hotell** [comment]
After #29776 

there are no more bugs, only 1 feature request that we will implement:

- add types+global hooks  automatically to CustomStyleHooksContext.ts
