### ISSUE TITLE
[Bug]: v9 Positioning does not account for window/document bounds when choosing fallback positioning

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#29773]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/zen-dawn-372jct?file=/src/example.tsx

## Actual Behavior
At reflow-size screens where the menu does not fully fit anywhere in the viewport, the menu will position itself above the trigger. This causes some menu items to be visually inaccessible (can't scroll to them, focus doesn't trigger window scroll), since they are clipped by the top of the window:
<img width="389" alt="screenshot of a menu open at small screensize, with the top of the menu clipped by the viewport" src="https://github.com/microsoft/fluentui/assets/3819570/86e2683f-a691-47c2-9efb-b4e2cb7d9a68">

The current behavior is causing an a11y bug on a partner team that's under SLA

## Expected Behavior
Ideally, the positioning utility should take window dimensions into account when calculating fallback positions, and position the menu somewhere where it can be scrolled to, and never above or to the left of the window/document bounds (since below will at least allow for scroll).

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
This can be fixed by using `<Menu positioning={{autoSize: true}} />`. Leaving this issue open to discuss whether we make that value default
