### ISSUE TITLE
[Bug]: TimePicker incorrectly handles daylight saving change

### ISSUE THREAD

**Issue by rocketBANG** [microsoft/fluentui#29783]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 12.78 GB / 31.71 GB
  Browsers:
    Edge: Chromium (118.0.2088.76)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/rocketbang/pen/qBgrEZW

## Actual Behavior
When selecting a date anchor on a day when a daylight saving change happens, the TimePicker displays duplicate times
example November 5, 2023 00:00:00 in PST timezone
![image](https://github.com/microsoft/fluentui/assets/2422566/42f80cdd-bef3-4f6a-96e4-94e9d1761cf4)

The bigger issue is even using the timezone offset value of these given dates and trying to format (using `onFormatDate`) that shows that the duplicated 1:00 and 1:30 dates have the timezone value set incorrectly
https://codepen.io/rocketbang/pen/NWopPRX

![image](https://github.com/microsoft/fluentui/assets/2422566/45a76d3e-5ace-4553-a6b2-fe7b8b763165)

There's also the issue of duplicated keys showing up regardless of how `onFormatDate` is used due to the `TimePicker` generating keys without the timezone
![image](https://github.com/microsoft/fluentui/assets/2422566/886e622f-d8bc-44a0-aafe-60d468d43be6)

## Expected Behavior
1. I would expect that the dates received in `onFormatDate` have their timezone set correctly
e.g. in the above timezone screenshot it should be 00:30 TZ 420, 1:00 TZ 420, 1:30 TZ 420, 1:00 TZ 480, 1:30 TZ 480, 2:00 TZ 480
This allows users of this component to display the timezone correctly to the user when needed
2. With that fixed some default behaviour to handle the daylight saving change when generating unique keys so the warning does not show up

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
I can repro the problem in v8, does not seem to repro in v9.

**Comment by YuanboXue-Amber** [comment]
I'll create an issue to add a test for this in V9

**Comment by YuanboXue-Amber** [comment]
I take a look at why this happens:
TimePicker does [`date.setSeconds(0)`](https://github.com/microsoft/fluentui/blob/9fdfa4c1d442dc164c0ad07e56b29795c97a5b78/packages/react/src/components/TimePicker/TimePicker.tsx#L86) when it generates time options, but this will set hour as well for daylight saving. For example:
```js
const date = new Date('Sun Oct 29 2023 02:00:00 GMT+0100 (GMT+01:00)'); 
date.setSeconds(0); 
console.log(date.toString()); // Logs: Sun Oct 29 2023 02:00:00 GMT+0200 (GMT+02:00)
```
Note the result is GMT+02:00 instead of +1.

It seems very much like a bug in javascript date. 

This doesn't happen in v9 because v9 doesn't do `setSeconds(0)` -> I'm not sure why this is needed, probably can be removed?
