### ISSUE TITLE
[Feature]: Ability to show "no data exists" in DetailsList component 

### ISSUE THREAD

**Issue by neelindap** [microsoft/fluentui#29814]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

In the `DetailsList` component, if no data exists for list there's no indicator currently.
![image](https://github.com/microsoft/fluentui/assets/17910973/faabf119-f1b7-497e-a2ad-6f9f87a408d5)

Would be great to have the component accept a component or string to be present in case of no data is present for the list.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by miroslavstastny** [comment]
As partners are supposed to migrate from v8 to v9 there is a low chance that new features would be added to v8. Have you considered upgrading to v9?
Tracking this as a feature request for now anyway.

**Comment by neelindap** [comment]
Hey @miroslavstastny  - I checked the v9 library, I think the `DetailsList` component is replaced with `Table`?
If so, I tried a codepen with blank input (https://codesandbox.io/s/lingering-sound-6w22p7), and same result - no indicator there either.

Additionally, noticed the `Table` component in v9 doesn't support grouped lists, which could be a blocker in our case.
Let me know if there's a grouped list implementation in v9 - if so, we can work towards migrating to v9

**Comment by spmonahan** [comment]
Hi @neelindap , as Miro noted we're encouraging partners to migrate to v9 controls whenever possible. As it seems like v9 may also need this feature the best course of action is to make a feature request against v9 `Table` so we can consider how this feature might work there.

For v8 we currently prioritize bugs over features. I am happy to review a PR if this is a feature you're willing to contribute but we are unlikely to commit to adding new v8 features.

Also, while not exactly what you want. The actual list of `items` passed into the `DetailsList` is controlled from outside the `DetailsList` so it is possible to conditionally render a "no data exists" message in place of the DL. [Here's an example of that](https://codepen.io/seanms/pen/YzgWWRB).
