### ISSUE TITLE
[Bug]: TextField with multiline and autoAdjustHeight unexpectedly scrolls 

### ISSUE THREAD

**Issue by NguyenVanBay101097** [microsoft/fluentui#29820]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
i using latest verion v8 of fluent. 
regarding to the bug when use textfield like this issue. 
https://github.com/microsoft/fluentui/issues/16653
how to fix?
```

### Are you reporting Accessibility issue?

None

### Reproduction

yes

## Actual Behavior
fill this out
i using latest verion v8 of fluent. 
regarding to the bug when use textfield like this issue. 
https://github.com/microsoft/fluentui/issues/16653
how to fix?
## Expected Behavior
fill this out

### Logs

```shell
no
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Can confirm this still repro in v8, for some reason we never merged that PR, but it does seem to be the way to go. I'll open up a PR to get this in since that one is very outdated.

**Comment by NguyenVanBay101097** [comment]
> Can confirm this still repro in v8, for some reason we never merged that PR, but it does seem to be the way to go. I'll open up a PR to get this in since that one is very outdated.

thank you, waiting your PR will be approved
