### ISSUE TITLE
[Bug]: `@fluentui/react-portal-compat-context` is targeted higher than ES5

### ISSUE THREAD

**Issue by wfwf1997** [microsoft/fluentui#29829]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 20.34 GB / 31.32 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
```

### Are you reporting Accessibility issue?

None

### Reproduction

Not related. Please inspect the package content.

## Actual Behavior
`@fluentui/react-portal-compat-context` uses ES6 syntax `const` in its release since 9.0.5.

## Expected Behavior
`@fluentui/react-portal-compat-context` only uses ES5 syntax. The v8 package `@fluentui/react` is targeted to ES5 and has ability to support IE/old Edge, so as its dependency, `@fluentui/react-portal-compat-context` needs to be ES5 out of box.

### Requested priority

High

### Products/sites affected

@fluentui/react

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by wfwf1997** [comment]
The 2 files ensures that product of Fluent UI v8 uses ES5.
[webpack-resources.js#L34](https://github.com/microsoft/fluentui/blob/master/scripts/webpack/src/webpack-resources.js#L34)
[tsconfig.json#L5](https://github.com/microsoft/fluentui/blob/master/packages/react/tsconfig.json#L5)

**Comment by smhigley** [comment]
The `react-portal-compat-context`'s `tsconfig.json` is targeted at ES5, and it looks like it's correctly transpiled within the hook, but not for `const` declarations outside the hook.

Incidentally, our Calendar and Datepicker compat components look like they're targeted at ES2019, which may not be intentional since the v8 `react-date-time` package is also ES5.

@TristanWatanabe or @Hotell, would you be able to take a look?

**Comment by wfwf1997** [comment]
I believe the change is brought about by the `swc` compiler, which is introduced in `9.0.5`. If I change the target to `ES5` in `.swcrc`, it produces the code with `var` only. Still, I'm not an expert in the build system, I'm not sure if it is a good approach to change things there.

**Comment by Hotell** [comment]
100% a regression during our migration to swc. thanks for reporting
