### ISSUE TITLE
[Bug]: NVDA is not narrating the expanded menu state 

### ISSUE THREAD

**Issue by NataliaKravcheniaTR** [microsoft/fluentui#29836]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:                                                      
    OS: Windows 10 10.0.19045                                  
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 11.93 GB / 32.00 GB                                
  Browsers:
    Chrome: 107.0.5304.0.
    Edge: Spartan (44.19041.3570.0), Chromium (119.0.2151.58)
    Internet Explorer: 11.0.19041.3570
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/ylhpdl?file=src%2Fexample.tsx

### Bug Description

Expand menu

## Actual Behavior
NVDA is not narrating expanded state
![image](https://github.com/microsoft/fluentui/assets/67966577/dab449e6-c565-4d8e-a0cf-79b1f80dff47)

## Expected Behavior
NVDA is narrating expanded state

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
The NVDA behavior is correct -- it is reading the state of the menu button when the button has focus (which is when it is collapsed). When you activate the button, focus moves into the menu and NVDA reads the menu item. When you close the menu, focus moves back to the menu button and NVDA reads that + the state again (which is collapsed).

This is all standard and expected menu interaction. If a tester is saying NVDA should say something like "expanded" after moving into the menu, they are incorrect.
