### ISSUE TITLE
[Feature]: Need guidance on migrating react-file-type-icons to v9

### ISSUE THREAD

**Issue by stuartlong** [microsoft/fluentui#29848]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

The current guidance on using `react-file-type-icons` to render different file icons is to use the v8 `Icon` component:
> import { Icon } from '@fluentui/react/lib/Icon';
> import { getFileTypeIconProps } from '@fluentui/react-file-type-icons';
> 
> <Icon {...getFileTypeIconProps({ extension: 'docx', size: 16 })} />;

There's no clear analog in v9 for `Icon` that doesn't come from `@fluentui/react-icons` and `@fluentui/react-icons` doesn't have file icons. 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by lb90** [comment]
In the meantime you can use `getFileTypeIconAsUrl`.

Remember to initialize the package:

```js
import { initializeFileTypeIcons } from '@fluentui/react-file-type-icons';
initializeFileTypeIcons();
```

Then get the icon:

```js
import {
  getFileTypeIconAsUrl,
} from '@fluentui/react-file-type-icons';

const docxIconUrl = getFileTypeIconAsUrl({ extension: 'docx', size: 16 });

const MyComponent = (props) => {
  return (
    ...
    <img src={docxIconUrl} />
    ...
  );
};
```
