### ISSUE TITLE
[Feature]: Implement CommandBar in v9

### ISSUE THREAD

**Issue by sethreidnz** [microsoft/fluentui#29847]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

As far as I can tell and from discussions with people on the team I don't see CommandBar in the roadmap for v9. Is there a plan to add it? It's heavily used in the internal app I am building and would block us from fully migrating.

### Have you discussed this feature with our team

I have but cannot remember who

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Low

**Comment by smhigley** [comment]
Hi @sethreidnz!

The v8 CommandBar was semantically a menu bar, so it's closest to the v9 MenuList control. With some style customization, you should be able to use MenuList as a CommandBar as a stop-gap.

I've added the owner of v9 Menu to comment on whether there's a plan to make it easier to use MenuList (or another menu variant) for a CommandBar-like control, or to say if that already exists and I missed it 😅

**Comment by ling1726** [comment]
Have you tried using the v9 Toolbar? https://react.fluentui.dev/?path=/docs/components-toolbar--default

**Comment by sethreidnz** [comment]
> Have you tried using the v9 Toolbar? https://react.fluentui.dev/?path=/docs/components-toolbar--default

@ling1726  I have seen it but it doesn't really serve the same purpose as a command bar unless I'm missing something. I can't really share the application I'm working on but it's a similar usecase to Azure Data Explorers dashboards which also use the Command Bar (and have a mix of Fluent 1 and 2 components). We use the command bar as described in the Fluent V1 docs

"CommandBar is a surface that houses commands that operate on the content of the window, panel, or parent region it resides above. CommandBars are one of the most visible and recognizable ways to surface commands, and can be an intuitive method for interacting with content on the page; however, if overloaded or poorly organized, they can be difficult to use and hide valuable commands from your user. CommandBars can also display a search box for finding content, hold simple commands as well as menus, or display the status of ongoing actions."

![CleanShot 2023-11-22 at 09 53 20](https://github.com/microsoft/fluentui/assets/4713713/8855aeb2-2f46-417f-8d9e-04336645c231)

> With some style customization, you should be able to use MenuList as a CommandBar as a stop-gap.

@smhigley Is this not more like a context menu? I don't see how that is analagous to the command bar in v1? I could potentially stitch together something that would look like a command bar building a complex custom component, but the command bar was one of the main components that we first adopted when moving from doing custom componetns to trying to use Fluent as much as possible. I'm wondering have you spoken with any other teams currently using the command bar such as Azure Data Explorer shown above?

**Comment by ling1726** [comment]
Do you mind listing what are the requirement gaps for the toolbar to be used in the same capacity as the command bar?

**Comment by sethreidnz** [comment]
I'm still curious on my other question though about what the thought process behind not implementing CommandBar and if you've talked with other users such as Azure Data Explorer that use it heavily?

**Comment by ling1726** [comment]
I've managed to implement all of the features that you mentioned using the Toolbar component https://codesandbox.io/p/sandbox/awesome-waterfall-37zw64?file=%2Fsrc%2Fexample.tsx%3A44%2C39

I do see a few things that aren't there by default:
* down chevron - perhaps a ToolbarMenuButton would be nice
* Extra styles necessary to push the second group to the right
* `role="menubar"` not set by default

In general the way v9 favours JSX composition instead of shorthand javascript objects to declare UI, you can actually do quite a lot with it. I'd advise you to take a look at the toolbar docs to see all the features that are there https://react.fluentui.dev/?path=/docs/components-toolbar--default#controlled-toggle-button

@smhigley  do you think from an a11y PoV we should be shipping some kind of Menubar component? apart from the role I don' think there's a huge amount of difference compared to the CommandBar tbh

FYI @gouttierre

**Comment by sethreidnz** [comment]
Ahh no that is very useful and that does pretty much satisfy the needs except for the ability = push things out to the right, and as you say the role. I wonder if the docs wouldn't benefit from some examples that look less like a control just for a text editor and had more command bar looking things with regular buttons rather than little icon buttons. I think that is what threw me, it's not at all clear from that page that you could do what you did.

That being said I'd be happy to contribute at some stage (perhaps not in the immediate future but I'll talk to my manager) and create a similar migration page that you have for other v8 components on how to migrate from v8 CommandBar common use cases, to the v9 toolbar to be similar. I think that would be pretty cool and I'd love to help if I can.
