### ISSUE TITLE
[Feature]: Carousel slider 

### ISSUE THREAD

**Issue by ShakthiNR** [microsoft/fluentui#29856]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Dear Team,
    I am an avid user of microsoft/fluentui and have found immense value in its capabilities. However, I am unable to find the Carousel slider component in microsoft/fluentui. I believe that incorporating this Carousel component would greatly enhance the framework's versatility and allow developers to create more dynamic and engaging user interfaces

Thanks,
Shakthi NR

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by smhigley** [comment]
Hi @ShakthiNR!

Thanks for reaching out! We're currently still prioritizing getting parity with v8 components in v9, but it's always good to know what components partners need. Please feel free to contact us directly in chat if this is a high-priority control for your team.

**Comment by ShakthiNR** [comment]
Hi @smhigley 
   Thank you for your response! We appreciate your efforts, having Carousel slider in fluent UI would greatly enhance the versatility of the framework. Since it is not available in Microsoft/FluentUI v8, we have taken the initiative to build a custom component in React to full fill our requirements. I kindly request that you consider adding the Carousel slide feature to Microsoft/FluentUI V9.

Thanks
Shakthi Naarayananan R

**Comment by briandrouin** [comment]
This may be duplicative of Carousel work; Karina can look into it.

**Comment by gouttierre** [comment]
📢"As mentioned above this could be a duplicate to #26647. I will keep this feature request open until we receive confirmation from the design team"

**Comment by gouttierre** [comment]
> 📢"As mentioned above this could be a duplicate to [#26647](https://github.com/microsoft/fluentui/issues/26647). I will keep this feature request open until we receive confirmation from the design team"

Marking as duplicate. Component will be handled with https://github.com/microsoft/fluentui/issues/26647.
