### ISSUE TITLE
[Bug]: Transparent Icons shown background color from Image initials in Persona component 

### ISSUE THREAD

**Issue by MohanSuri** [microsoft/fluentui#29879]
### Library

React Components/ v9 (@fluentui/react-components)

### System Info

```shell
repro from codesandbox
https://codesandbox.io/s/wizardly-liskov-qrcsc3?file=/src/example.tsx
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/wizardly-liskov-qrcsc3?file=/src/example.tsx

## Actual Behavior
Transparent icons rending with background color (from image initials)

## Expected Behavior
Transparent icons should render without showing any background color

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
Hi @MohanSuri, I'll double-check if we need to default to a background for some reasons, but I agree that we could at least ensure that the initials are hidden if an `image` is present. I'll speak with the code owner of the component to gather their thoughts on this.

**Comment by behowell** [comment]
Hi @MohanSuri, Avatar wasn't designed to be used without a background, so this isn't something we would plan to change in Avatar itself.

However, in the cases in your example, you can work around this by preventing the `initials` slot from rendering by setting it to `null`. Please let us know if that works for you.

```jsx
<Persona
  {...personaProps}
  avatar={{
    initials: null,
    icon: <Alert24Regular />,
  }}
/>
```

```jsx
<Persona
  {...personaProps}
  avatar={{
    initials: null,
    image: {
      className: image,
      src: 'https://res-1.cdn.office.net/files/fabric-cdn-prod_20230815.002/assets/brand-icons/product/svg/m365_48x1.svg',
    },
  }}
/>
```
