### ISSUE TITLE
[Bug]: Combobox Keyboard Navigation Bug in DetailsList

### ISSUE THREAD

**Issue by Ali-ELMAS** [microsoft/fluentui#29885]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 34.80 GB / 63.78 GB
  Browsers:
    Edge: Chromium (119.0.2151.44)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/friendly-neco-sqml9y?file=/src/App.tsx

## Description
I encountered an issue while using a ComboBox within a DetailsList. The problem revolves around keyboard navigation. Specifically, when navigating through different columns within a row, the focus becomes stuck on the ComboBox column. Even after pressing the right or left arrow keys, the focus fails to move to the next column. Additionally, clicking the up or down arrow keys alters the ComboBox selection instead of moving to the adjacent row. The desired behavior is for the right arrow key to advance to the next column, and the up arrow key to move to the row above.

## Actual Behavior

- The focus remains stuck on the ComboBox column, even after pressing the right or left arrow keys.
- Clicking the up or down arrow keys alters the ComboBox selection instead of moving to the adjacent row.

## Steps to Reproduce
- Navigate to a page with a DetailsList containing a ComboBox in one of the columns.
- Attempt to navigate through different columns within a row using the keyboard arrows.

## Expected Behavior
- Pressing the right arrow key should move the focus to the next column.
- Pressing the up arrow key should move the focus to the row above.

## Additional Information
While researching this issue on Google, I found a similar problem reported at the following link: [GitHub Issue #15036](https://github.com/microsoft/fluentui/issues/15036#issuecomment-696572556).

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@Ali-ELMAS When the next version of Fluent v8 releases this will be fixed by adding the `allowParentArrowNavigation={true}` prop to your `ComboBox`.
