### ISSUE TITLE
[Bug]: List virtualization won't work in Strict mode

### ISSUE THREAD

**Issue by mhverbakel** [microsoft/fluentui#29880]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:                                                      
    OS: Windows 10 10.0.19045                                  
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 7.18 GB / 31.69 GB                                 
  Browsers:                                                    
    Edge: Spartan (44.19041.3570.0), Chromium (119.0.2151.44)  
    Internet Explorer: 11.0.19041.3570
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/m-verbakel-eshgro/pen/WNPMaGN

## Actual Behavior
When rendering a list with virtualization enabled _in strict mode_, the next page is not rendered.

## Expected Behavior
Rendering a list with virtualization enabled _in strict mode_ behaves the same as a list with virtualization enabled _without strict mode_.

## Cause
Strict mode renders the component twice. To do this, the component is unmounted and then remounted. In [List.componentWillUnmount](https://github.com/microsoft/fluentui/blob/1a26dc71a18fed4b842ec6b551189da2d0c389b2/packages/react/src/components/List/List.tsx#L394), a dispose is called on the `EventGroup`. However, since the `EventGroup` is only instantiated in the constructor, the disposed `EventGroup` is reused when `componentDidMount` is called again. Hence, the event listeners for scrolling are added, but they immediately return [because their group is disposed](https://github.com/microsoft/fluentui/blob/873b079e8c57fc139366d6ab57d9070abd81865a/packages/utilities/src/EventGroup.ts#L207).

This seems to be related to https://github.com/microsoft/fluentui/issues/28230#issuecomment-1593363167.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by DiegoSalazar** [comment]
Also experiencing this issue during local dev (strict mode on).
