### ISSUE TITLE
[Bug]: Footer of the panel is not sticky in v8

### ISSUE THREAD

**Issue by Rafaelki** [microsoft/fluentui#29896]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Browser: chrome
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/rafaelki/pen/dyamQLy

## Actual Behavior
The footer of the panel is not sticky in V8 and the property isFooterAtBottom doesn't work

No sticky:
![image](https://github.com/microsoft/fluentui/assets/24438807/f24d500b-d5aa-46c9-a139-4666d8c516a0)

No at the bottom:
![image](https://github.com/microsoft/fluentui/assets/24438807/414af78a-f527-4d25-ba56-d7ca6361bd3b)

## Expected Behavior
It should work as in V7 and as it is documented, i.e. the footer should be sticky (it is visible even when the body area is too large, so the body area has a scroll) and isFooterAtBottom (footer should appear at the bottom when the body area is small)

note the same code in V7 works as expected:
https://codepen.io/rafaelki/pen/zYeWMQe

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Rafaelki** [comment]
Hi! Sorry to chase... Any update on this? any workaround, please?

**Comment by Rafaelki** [comment]
Shouldn't the footer element be outside of the scrollableContent div, for flexGrow: 1 to work?

like this:

![image](https://github.com/microsoft/fluentui/assets/24438807/37273642-20fc-43fa-a331-f45b1d01fd30)

**Comment by khmakoto** [comment]
Hi @Rafaelki, I see the footer at the bottom in the codepen reproduction you sent. Are there any specific steps I need to follow to repro this behavior?

![image](https://github.com/microsoft/fluentui/assets/7798177/ae034a6f-2840-431b-91c6-9cfbebf7b477)

**Comment by Rafaelki** [comment]
@khmakoto you are absolutely right. Sorry, I was using a view in Codepen that made the demo area smaller and I didn't realize there where a media query fo the height of the screen.

I am closing this issue, my apologies once again.

![image](https://github.com/microsoft/fluentui/assets/24438807/bf51be0b-53ed-48b5-8db5-2518ff4bd57c)
