### ISSUE TITLE
[Bug]: `<SearchBox />`  `onSearch` prop doesn't get called correctly in tests

### ISSUE THREAD

**Issue by sethreidnz** [microsoft/fluentui#29913]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 476.56 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.159
    Edge: 119.0.2151.72
    Safari: 17.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/sethreidnz/fluent-v8-search-react-test-libary-issue

## Actual Behavior

When using the <SearchBox /> and trying to write a test using jest + react testing library where the user types in the search box and presses enter, the `onSearch` callback is never called so the test fails. This is in contrast to the other test in my example where I am using onKeyPress which does pass with the exact same test case.

## Expected Behavior

When using the <SearchBox /> and trying to write a test using jest + react testing library where the user types in the search box and presses enter, the `onSearch` callback is called when the test simulates a user pressing enter inside the text box.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
I would expect the test to pass given the [source code](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/SearchBox/SearchBox.base.tsx#L170-L176).

In the test that passes can you log `event.keyCode`. It should be `13` as this maps to Enter/Return.
