### ISSUE TITLE
[Feature]: add support for NextJS server-side component in `global-context` 

### ISSUE THREAD

**Issue by abutahermuhammad** [microsoft/fluentui#29911]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

It seems that the `global-context` module only supports client-side components because it utilizes `React.createContext()`. However, the development team has explained that this module helps with creating a global context. Unfortunately, the NextJS server-side component does not support `React.createContext()`, so I would like to request the development team to add some support for it.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by spmonahan** [comment]
Thanks for the feature request! Can you please provide some documentation links for NextJS server-side components so we can evaluate this?

**Comment by abutahermuhammad** [comment]
Hi @spmonahan, thank you for your time. Can you look into this official documentation?
[Server and Client Composition Patterns](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns)
