### ISSUE TITLE
[Chore]: upgrade Floating UI to 1.5.3

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/fluentui#29938]
We're currently using `@floating-ui/dom@1.2.0` on `@fluentui/react-positioning` and we do support all minor versions since it's a caret based dependency `^1.2.0` . Any of our partners using a higher compatible version might come to some visual regressions.

## Solution

Let's bump our codebase of `@floating-ui/dom` and  investigate what's causing the regressions.

## Problems found while trying to upgrade

Seems like we have some visual regressions being reported on version 1.4.0 of `@floating-ui/core` https://github.com/microsoft/fluentui/pull/29928

### Possible regression cause

1. https://github.com/floating-ui/floating-ui/pull/2558

**Comment by lekoaf** [comment]
@bsunderhus floating-ui-devtools is breaking our workflows, because it doesn't have a license.

**Comment by bsunderhus** [comment]
> @bsunderhus floating-ui-devtools is breaking our workflows, because it doesn't have a license.

I just added it!

**Comment by lekoaf** [comment]
> > @bsunderhus floating-ui-devtools is breaking our workflows, because it doesn't have a license.
> 
> I just added it!

Great! Thanks! :smiley:
