### ISSUE TITLE
[Bug]: Popover arrow border incorrectly rotated in RTL

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#29944]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
-
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/sandbox/popover-arrow-rtl-ww4gz9

## Actual Behavior
`<Popover withArrow />` rendered inside RTL has the arrow border rotated incorrectly:

![image](https://github.com/microsoft/fluentui/assets/9615899/7229badd-b929-4a04-9dae-3cbd7e209e1c)

## Expected Behavior
The arrow border is rotated towards the trigger.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
This happens specifically with the `teamsHighContrastTheme`.

**Comment by spmonahan** [comment]
> This happens specifically with the `teamsHighContrastTheme`.

Yeah, doesn't repro with `webDarkTheme`.

I suspect the issue is [around here somewhere](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-positioning/src/createArrowStyles.ts#L98-L113).
