### ISSUE TITLE
[Bug]: Storybook docsite: multiple "Open in CodeSandbox" buttons

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#29945]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
-
```

### Are you reporting Accessibility issue?

no

### Reproduction

-

## Actual Behavior
Every time a theme is switched a new "Open in CodeSandbox" is added:
<img width="1061" alt="image" src="https://github.com/microsoft/fluentui/assets/9615899/0b27d94e-0102-428c-9da7-fa34f72df246">

### Requested priority

Low

### Products/sites affected

react.fluentui.dev

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
This is fixed now. It was already fixed in code but was missing a release to the docsite.
