### ISSUE TITLE
[Bug]: isConformant - type error when using component with root slot div or ul

### ISSUE THREAD

**Issue by george-cz** [microsoft/fluentui#29943]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A - internal bug report

### Bug Description

When working on List, I had to cast the `List` component in `isConformant` call to get rid of this error:

<img width="1407" alt="Screenshot 2023-11-29 at 17 34 22" src="https://github.com/microsoft/fluentui/assets/2070479/829a32a1-601d-457a-aafe-2060ad27a580">

@layershifter proposed to create an issue here: https://github.com/microsoft/fluentui/pull/29760#discussion_r1407951902

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
@george-cz can you try using `isConformant<ListProps>` in here? I think that's really all that's needed in this scenario.
