### ISSUE TITLE
[Feature]: Segment Component

### ISSUE THREAD

**Issue by aokihu** [microsoft/fluentui#29953]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

I think Segment Component is useful in switching panel, 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by spmonahan** [comment]
Hi @aokihu, can you please elaborate on what a "Segment Component" is? And perhaps provide some examples? Currently there isn't enough information for us to do anything.
