### ISSUE TITLE
[Bug]: Hover, Pressed states in Menu items do not show filled icons 

### ISSUE THREAD

**Issue by stchoioutlook** [microsoft/fluentui#29950]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-menu-menu--default

## Actual Behavior
The menu item on hover and pressed states do not change the icon to the filled version. It also looks like the wrong theme colored token is being used. Below is a screenshot of the current implementation. 
<img width="211" alt="MicrosoftTeams-image (10)" src="https://github.com/microsoft/fluentui/assets/152447236/b61a909e-478a-45e4-a2c7-40f641aa2072">

## Expected Behavior
This is the intended behavior as shown in Fluent specs for Menu items. The icon colors are also CompoundBrandForeground1/Hover on Hover and CompoundBrandForeground1/Pressed on Pressed
<img width="455" alt="MicrosoftTeams-image (11)" src="https://github.com/microsoft/fluentui/assets/152447236/bc1883a2-83de-4998-b731-3d8c55f1e23d">

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
Hi @stchoioutlook, the icons do switch between the regular and filled versions as long as you use the `bundleIcon` utility that is shown in our `Menu` stories, for example [this one](https://react.fluentui.dev/?path=/docs/components-menu-menu--default#menu-items-with-icons).

I agree that we should add the correct color for the pressed state though, I'll make a PR to fix that.
