### ISSUE TITLE
[Bug]: Checkbox has invalid DOM nesting.

### ISSUE THREAD

**Issue by TomSoftwerft** [microsoft/fluentui#29969]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 41.59 GB / 62.50 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Browsers:
    Chrome: 119.0.6045.159
    Chromium: 119.0.6045.159
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-checkbox--default

## Actual Behavior
The `Checkbox` component has invalid DOM nesting. The `indicator` renders as `div` and is nested inside a `span`.
The [W3C validator](https://validator.w3.org/) show the following error:

`Element div not allowed as child of element span in this context. (Suppressing further errors from this subtree.)`

## Expected Behavior
Checkbox should not have invalid DOM nesting.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Shubhdeep12** [comment]
Hey @khmakoto, what if we use an indicator span instead of a div? Just want to know the reason behind this.

**Comment by mainframev** [comment]
@TomSoftwerft 

Hi 👋🏻 Currently we cannot make a complete fix for this issue, as it's breaking the current incorrect behavior 😞 
So as a temporary solution we are extending the type to accept `span` 

Please add this until we will release a major with a complete fix 🙏🏻 

```jsx
indicator={{ as: 'span' }} 
```

**Comment by TomSoftwerft** [comment]
> @TomSoftwerft
> 
> Hi 👋🏻 Currently we cannot make a complete fix for this issue, as it's breaking change to the current incorrect behavior 😞 So as a temporary solution we are extending the type to accept `span`
> 
> #31640
> 
> Please add this until we will release a major with a complete fix 🙏🏻
> 
> ```js
> indicator={{ as: 'span' }} 
> ```

Hi @mainframev , thank you for the response and the temporary solution.
