### ISSUE TITLE
[Bug]: Spinner flicker when delay prop is set

### ISSUE THREAD

**Issue by gaoqiangz** [microsoft/fluentui#29974]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
    Memory: 17.81 GB / 31.94 GB
Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.93)    
    Internet Explorer: 11.0.19041.3636
```

### Are you reporting Accessibility issue?

no

### Reproduction

See description

## Reproduce

```tsx
<Spinner delay={10000} />
```

## Actual Behavior

Display immediately then hidden.

## Expected Behavior

Display when delay time elapsed.

## Code

`isVisible` initial value should be `false`.

https://github.com/microsoft/fluentui/blob/96379f5a4924df47adcfb0166cb6461e1c138ab9/packages/react-components/react-spinner/src/components/Spinner/useSpinner.tsx#L41-L54

As the `useEffect` documentation said that `setup` callback will call after component mouted:

> setup: The function with your Effect’s logic. Your setup function may also optionally return a cleanup function. When your component is added to the DOM, React will run your setup function. After every re-render with changed dependencies, React will first run the cleanup function (if you provided it) with the old values, and then run your setup function with the new values. After your component is removed from the DOM, React will run your cleanup function.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
[I didn't see it here in Edge on Mac](https://codesandbox.io/p/sandbox/sad-hooks-c2fw64?file=%2Fsrc%2Fexample.tsx%3A6%2C26) but the proposed fix still seems like a good thing to do.
