### ISSUE TITLE
[Bug]: Popover missing Callout migration props mapping in storybook

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#29972]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A - check storybook migration/from v8/Components section

## Actual Behavior
There is a missing topic for Callout -> Popover in the migration documentation

## Expected Behavior
A storybook topic covering the props mapping and migration recommendations

### Requested priority

Normal

### Products/sites affected

Partner migration

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
@GeoffCoxMSFT in the report you wrote you are willing to submit a PR for this. Do you plan to work on the issue or is teams-prg supposed to take it?
