### ISSUE TITLE
[Feature]: Left Rail component

### ISSUE THREAD

**Issue by gouttierre** [microsoft/fluentui#29977]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Would Fluent UI be interested in adding a component for Left Rail? It's a pattern used in Teams and that will soon be adopted by Loop. It somewhat relates to the Drawer component that was added to V9 recently.
 

### Have you discussed this feature with our team

Yes. Below is a reference from the last communications
>Shift: _Miroslav with others worked recently on a new set of components for the left rail on Teams side, so it would be cool if you could connect efforts. As this looks like a perfect candidate to be a contrib package (similarly to Teams chat)._

### Additional context

- This is a partner ask. Tiger is the requester.
- Teams has a reusable left rail feature that is proposed but the Teams PM needs to draft the initial spec and prioritize the efforts. 
- The design team handling the spec will be on the Teams team 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by gouttierre** [comment]
We should hold and wait as Teams has a reusable left rail feature that is proposed. They are waiting on PM spec on the Teams side to proceed.
cc: @JustSlone , @jurokapsiar , @tudorpopams

**Comment by gouttierre** [comment]
Hi @layershifter, @miroslavstastny I remember that Teams had a reusable left rail feature that was proposed. Do you know the status of that effort?
cc @tudorpopams , @JustSlone

**Comment by mltejera** [comment]
Recapping offline discussion: This is not currently in scope for the L2 Nav. Parts of it might be baked into the L1 Nav. Going to close for now, and may re-open if & when we go tackle L1 Nav.
