### ISSUE TITLE
[Bug]: ThemeProvider overrides Customizer's scopedSettings

### ISSUE THREAD

**Issue by aviellavie** [microsoft/fluentui#29997]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 34.07 GB / 63.95 GB
  Browsers:
    Edge: Chromium (119.0.2151.72)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @fluentui/react: ^8.72.1 => 8.112.9
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/aviellv/pen/WNPLJMq

## Actual Behavior
 Panel does not receive the Layer hostId override

## Expected Behavior
 Panel should receive the Layer hostId override

### Requested priority

Blocking

### Products/sites affected

SCC

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@spmonahan to review PR
