### ISSUE TITLE
[Feature]: add lint to enforce `React` usage style

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#30007]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

In Fluent v9 we always (I think anyway) use the `React` global when using React code. E.g.,:

```ts
// Yes ✅
import * as React from "react";

const myGoodHandler = React.useCallback(() => ...);

// No ❌
import { useCallback } from "react";

const myBadHandler = useCallback(() => ...);
```

From what I can tell there is no technical reason the latter example is "bad" and this is largely a stylistic choice. The `React.` form is helpful as it distinguishes built-in React hooks from custom ones.

### Have you discussed this feature with our team

@spmonahan

### Additional context

This came up in a [code review](https://github.com/microsoft/fluentui/pull/29894#discussion_r1410032138).

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by mainframev** [comment]
Should be possible to catch those via `no-restricted-syntax` and select, smth like this: 

```json
"no-restricted-syntax": [
  "error",
  {
    selector: "ImportDeclaration[source.value='react'] ImportSpecifier",
    "message": "Avoid named imports from 'react'. Use 'import * as React from \"react\"' instead."
  },
]
```

**Comment by spmonahan** [comment]
@mainframev Can you make a PR please?
