### ISSUE TITLE
[Bug]: `width` prop in `Skeleton` does not work

### ISSUE THREAD

**Issue by wfwf1997** [microsoft/fluentui#30016]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 23.81 GB / 31.32 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Browsers:
    Chrome: 119.0.6045.159
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/sandbox/unruffled-edison-8lv8rz

## Actual Behavior
The Skeleton in 100% in width

## Expected Behavior
The Skeleton in 75% in width

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by pradeept95** [comment]
I think you can set skeleton with using className props,

Here is the working example:
https://codesandbox.io/p/sandbox/vigorous-panna-6myc9c?file=%2Fsrc%2FApp.jsx

**Comment by wfwf1997** [comment]
Hi @pradeept95, thanks for your workaround. However, what I want to say is that even tough `width` is a documented `prop` in the documentation and handled specially in the type definition, it actually doesn't work at all.

**Comment by tomi-msft** [comment]
This is intended behavior, as `width` should be modified through the `className` as is the paradigm for the fluent components. I will make a PR to deprecate this prop.
