### ISSUE TITLE
[Bug]: Broken links in the documentation

### ISSUE THREAD

**Issue by joliveira12** [microsoft/fluentui#30022]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/concepts-migration-from-v0-components-popup-migration--page

### Bug Description

Two broken links in the page that explains how to migrate the Popup component from Northstar to v9
https://react.fluentui.dev/?path=/docs/concepts-migration-from-v0-components-popup-migration--page

## Actual Behavior
First broken link is to a page that explains how to migrate the positioning props, it links to https://react.fluentui.dev/iframe.html?path=/docs/concepts-migrating-from-v0-positioning--page

Second broken link is to a page that explains how to migrate styles, it links to https://react.fluentui.dev/iframe.html?path=/docs/concepts-migrating-from-v0-custom-style-overrides--page

## Expected Behavior
First link should be https://react.fluentui.dev/?path=/docs/concepts-migration-from-v0-positioning--page

Second link should be https://react.fluentui.dev/?path=/docs/concepts-migration-from-v0-custom-style-overrides--page

### Requested priority

Low

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Note: this is also present in other migration pages like Avatar.

Looks like the link is "correct": https://github.com/microsoft/fluentui/blob/master/apps/public-docsite-v9/src/Concepts/Migration/FromV0/Components/Popup.stories.mdx#L48

However, the actual page where that link is rendered is in an iframe (this is where `iframe.html` comes from) so we end up with the observed link.
![Screenshot 2023-12-11 at 2 33 17 PM](https://github.com/microsoft/fluentui/assets/93940821/e8f1d0ac-3059-48ed-a62e-01fe4cae69c0)
