### ISSUE TITLE
Combobox inline style override no longer works

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#30027]
https://codesandbox.io/p/sandbox/blissful-browser-f3zpc6?file=%2Fsrc%2Fexample.tsx%3A16%2C16

Before https://github.com/microsoft/fluentui/pull/29690 it was possible to override the width of the listbox with inline styles. However moving the application of the inline style to a positioning middleware makes it unoverridable.

**Comment by layershifter** [comment]
Was it fixed in #30028?

**Comment by ling1726** [comment]
> Was it fixed in #30028?

Yes, closing this issue
