### ISSUE TITLE
[Feature]: Neutral Card Background 1 - Colour token request

### ISSUE THREAD

**Issue by suvoray-microsoft** [microsoft/fluentui#30037]
### Library

~~React Northstar / v0 (@fluentui/react-northstar)~~

v9

### Describe the feature that you would like added

Request to add this colour token in the V9 library. This is for the cards design that we recently implemented in Teams. 

![Card combanitions](https://github.com/microsoft/fluentui/assets/140199829/b862eee0-95ec-4239-be87-fa949036a7ed)

### Have you discussed this feature with our team

Yes

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by suzto** [comment]
@miroslavstastny - I’m excited to share that our developer has completed our new Adaptive Card framework that uses this token. We are **eager to ship it as soon as possible**, but we need your support. Could you please let us know when the token will be ready on your end? Thank you for your cooperation and hard work. 🙏
