### ISSUE TITLE
[Bug]: [Donut chart] Donut chart category with small number not displayed

### ISSUE THREAD

**Issue by Gabnight** [microsoft/fluentui#30034]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz
    Memory: 14.78 GB / 31.92 GB
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.61), ChromiumDev (121.0.2256.2)
    Internet Explorer: 11.0.19041.3636
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/Gabnight/pen/poGBejV

### Bug Description

Have a donut chart with one category with very low hits (<1%).
Observe
Ex:
https://codepen.io/Gabnight/pen/poGBejV

## Actual Behavior
no bar for the "small" category
![image](https://github.com/microsoft/fluentui/assets/122602310/d0177140-c8fd-4d52-bfa4-48dc40899c6a)

## Expected Behavior
at lease a 1px bar for each category present

### Requested priority

Normal

### Products/sites affected

make.powerautomate.com

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by AtishayMsft** [comment]
Thanks for reporting this issue. We will not be able to prioritize fixing it in the current Semester (Jan-June).
Feel free to submit a fix if it is important for your scenario.

**Comment by AtishayMsft** [comment]
@Shubhabrata08 FYI
