### ISSUE TITLE
[Bug]: [DatePicker] [A11y] grid navigation would be expected for "year" table

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#30036]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 18.10 GB / 31.74 GB
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/solitary-tree-3r7vnj

### Bug Description

1. Navigate to the https://codesandbox.io/p/sandbox/solitary-tree-3r7vnj
2. navigate to "Select a date  combo box"
3. open combobox (calendar opens) 
4. navigate with using TAB key into "2023  table"

## Actual Behavior
up/down arrow key navigate to next/previous cell 

## Expected Behavior
I would expect user can do grid navigation in the table. Up/down arrow key navigate to next/previous row.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Looks like a bug to me. [v8 DatePicker](https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker) exhibits the expected behavior.
