### ISSUE TITLE
[Bug]: TOGGLE doesn't have ability to disable focus via "data-is-focusable". Cannot disable focus in DETAILSLIST like we can with CHECKBOX

### ISSUE THREAD

**Issue by tandrasi** [microsoft/fluentui#30049]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 19.83 GB / 31.92 GB
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/tandrasi/pen/zYeQrYJ?editors=1010

Repro steps:

1. Go to the codepen and navigate to the rendered details list.
2. Press the TAB key to shift focus to the first row in the details list (the row below the header row).
3. Now that the focus is on the row, press the right arrow key and notice how the toggle control receives focus.

## Actual Behavior
While navigating using the TAB key, once the details list row receives focus, pressing the right arrow key will shift focus to the toggle control. 

## Expected Behavior
Like the checkbox control, I expect the ability to supply a prop to the toggle control which will cull focus events in the details list. In this example, pressing the right arrow key when the details list row receives focus should **not** focus the toggle control.

This is a quick code snippet to show the two controls and how I expect the toggle control to work:

_line 134_
**Doesn't work as expected as the functionality isn't implemented nor does a relevant prop exist:**
Toggle:
`<Toggle data-is-focusable={false} />`

_line 149_
**Works as expected - we can supply "inputProps":**
Checkbox:
`<Checkbox inputProps={{ "data-is-focusable": false }} />`

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
This is because `Toggle` internally renders [`<button>`](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Toggle/Toggle.base.tsx#L153) which is [where `data-is-focusable={true}` is set](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Toggle/Toggle.base.tsx#L129). However, unlike `Checkbox` no API is provided for users to override this value.
