### ISSUE TITLE
[Bug]: Tree onOpenChange inconsistent between Tree and TreeItem

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#30048]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react@9.42.0
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/sandbox/tree-onopenchange-gwwd49

## Actual Behavior
1. Render a nested `Tree` with `open` prop passed to the `TreeItem`, so that the tree item is expanded on the initial render.
2. Add `onOpenChange` to the `Tree`, control to expanded/collapsed state based on the `data.open` from the callback.
3. Click on the tree item chevron to collapse the subtree.

```tsx
const [open, setOpen] = React.useState(true);
//...
<Tree onOpenChange={(e, data) => {setOpen(data.open);}} >
  <TreeItem itemType="branch" open={open}>Parent</TreeItem>
</Tree>
```

⚠️ The subtree does not collapse on the first click. It collapsed on the second click.

If the `onOpenChange` handler is moved from the `Tree` directly to the `TreeItem` it works as expected. Only the first call is out of sync:
```log
// first click - open states do not match
TreeItem::onOpenChange {value: 'fuiTreeItemValue-4', open: false}
Tree::onOpenChange {value: 'fuiTreeItemValue-4', open: true}

// subsequent call - open states match
TreeItem::onOpenChange {value: 'fuiTreeItemValue-4', open: false}
Tree::onOpenChange {value: 'fuiTreeItemValue-4', open: false}
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
In the [documentation](https://react.fluentui.dev/?path=/docs/components-tree--default#open-item-controlled) we state:

> Note: It's not recommended to use both `openItems` and `open` at the same time, as this can lead to unexpected behavior! Stick to one or the other.

I guess we'll have to improve it a little bit and also state that you can't use `onOpenChange` on `Tree` and expect it to be synced with `open` on the `TreeItem`.  Basically you can't mix item control with root control, it's not viable at the moment and it would require us to do some  weird synchronization between the components which would force re-renders, the best solution at the moment is: if you're going to use the `onOpenChange` on `Tree`, you gotta use `openItems` on `Tree` and if you're going to use `onOpenChange` on `TreeItem` then you gotta use `open` on `TreeItem` itself, you can't use them both together (the same goes to the callbacks, can't use them together, they're not synchronized).


As a solution at the moment I'll update documentation and also emit a warning if you don't provide `onOpenChange` when you provide `open` on `TreeItem`
