### ISSUE TITLE
[Bug]: open-state-controlled Dropdown cannot get dismissed by clicking outside the dropdown button

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#30045]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
"@fluentui/react-components": "^9.42.0",

Using CodeSandbox
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/sandbox/open-controlled-dropdown-w4rfn4?file=%2Fpackage.json%3A5%2C5-5%2C45

## Actual Behavior
![Recording_20231212T204611](https://github.com/microsoft/fluentui/assets/50703224/87a491e4-a3c5-4a7a-b831-615a97bb472b)

## Expected Behavior

I should be able to dismiss the dropdown box by clicking outside the dropdown component, even if it is opened by clicking "Open dropdown" button.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chenxinyanc** [comment]
If this behavior is by design, then what is the recommended approach for us to enable user dismissing the dropdown list by clicking anywhere else in the HTML document?

**Comment by layershifter** [comment]
@spmonahan this is a bug, other controls like `Menu` or `Popover` handle this scenario, https://react.fluentui.dev/?path=/docs/components-popover--default#controlling-open-and-close

**Comment by spmonahan** [comment]
> @spmonahan this is a bug, other controls like `Menu` or `Popover` handle this scenario, https://react.fluentui.dev/?path=/docs/components-popover--default#controlling-open-and-close

I think we need to update the `Popover` story because it's possible to click the label making this behavior appear buggy in the example 🙂

https://github.com/microsoft/fluentui/assets/93940821/90be7880-b8dc-43c8-a0ed-e700593e81df

**Comment by Devjoyti-Barman** [comment]
@smhigley are you working on this? Mind if I pick this up?

**Comment by SiriratS** [comment]
Hi @smhigley,

When you open the dropdown in Safari (I'm using Safari Version 16.3 on Mac Ventura 13.2.1)

It also can't dismissed by clicking outside the dropdown as well

You can test it on the version 9 document https://react.fluentui.dev/?path=/docs/concepts-developer-accessibility-components-dropdown--page

Do you have a plan to fix this issue as well? or Should I create a separate issue for Safari?
