### ISSUE TITLE
[Bug]: Dialog animation is not respecting reduced motion OS setting

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#30041]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
https://react.fluentui.dev/?path=/docs/components-dialog--default
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-dialog--default

### Bug Description

Use reduced motion:
<img width="504" alt="image" src="https://github.com/microsoft/fluentui/assets/13742664/85398dd8-b263-472d-9085-8a8a81f4b860">

## Actual Behavior
Animation is enabled when Dialog appears

## Expected Behavior
Dialog is shown without animation

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
Waiting for changes in motion.
