### ISSUE TITLE
[Bug]: Putting a PopoverTrigger without trapFocus in a Toolbar breaks keyboarding

### ISSUE THREAD

**Issue by NotWoods** [microsoft/fluentui#30047]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22635
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 3.01 GB / 15.60 GB
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/p/sandbox/floral-brook-zmknpz?file=%2Fsrc%2FApp.tsx

## Actual Behavior
A Popover (without `trapFocus`) placed inside a Toolbar does not get dismissed when focus leaves the popover. 

## Expected Behavior
Popover should auto-dismiss rather than stay on screen, as it does when not placed inside a Toolbar.
---
In the minimum repro, the Bell icon is a popover outside a toolbar while the Image icon is a popover inside a Toolbar.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
This looks like a problem with Tabster and attributes from `useArrowNavigationGroup()`, as once I add it to the first toolbar-like "div" - it breaks 💥 

https://codesandbox.io/p/sandbox/laughing-grass-p2gsy9?file=%2Fsrc%2Fexample.tsx%3A23%2C7
