### ISSUE TITLE
[Bug]: [Donut chart] Hovering over a donut legend with 0 value does not put 0 in the centered value

### ISSUE THREAD

**Issue by adboillo** [microsoft/fluentui#30051]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22635
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
    Memory: 10.41 GB / 31.92 GB
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/adriblt/pen/GRzaryb

## Actual Behavior
In a donut chart, hovering on a section or the legend updates the center text to have the associated value.
This does not work as expected for sections with a 0 value, instead it displays the total.

Default view:
![image](https://github.com/microsoft/fluentui/assets/153725797/c1697d0a-03f5-43c2-97dc-674497e162b0)

Hovering legend with non zero velu:
![image](https://github.com/microsoft/fluentui/assets/153725797/0bbeeed6-5a59-409a-8c60-396605bf83ff)

Hovering legend with a 0 value:
![image](https://github.com/microsoft/fluentui/assets/153725797/8d1e3bf5-2732-4a89-926d-6f320f404204)

## Expected Behavior
The centered value should be "0" when hovering the legend

### Requested priority

Normal

### Products/sites affected

https://make.powerautomate.com/

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by AtishayMsft** [comment]
Thanks for reporting this issue. We will not be able to prioritize fixing it in the current Semester Jan-June.
Feel free to submit a fix if it is important for your scenario.
