### ISSUE TITLE
[Bug]: MenuItem does not show hover highlight in OS high contrast mode

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#30065]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 949.42 MB / 15.60 GB
  Browsers:
    Edge: Chromium (120.0.2210.61), ChromiumDev (121.0.2256.2)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://react.fluentui.dev/?path=/docs/components-menu-menu--default

## Actual Behavior

MenuItems don't have hover visuals when using the OS high contrast theme, such as Windows Aquatic.

https://github.com/microsoft/fluentui/assets/48106640/2601bace-01b6-48ec-a3c5-e2e74a4222de

## Expected Behavior

MenuItem should show a highlight background when hovered in high contrast.

## Related Issues

This is also an issue in v8, which is covered by https://github.com/microsoft/fluentui/issues/25330. However, I couldn't find another issue logged about v9 Menu.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
According to @ling1726, this is the default behavior for buttons in Windows HC.
FUI overrides that behavior for `Button`.
