### ISSUE TITLE
[Bug]: Jest tests fail when testing combobox

### ISSUE THREAD

**Issue by 15MariamS** [microsoft/fluentui#30095]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 37.77 GB / 64.00 GB
    Shell: 3.2.57 - /bin/sh
  Browsers:
    Chrome: 120.0.6099.109
    Edge: 120.0.2210.77
    Safari: 16.5.2
```

### Are you reporting Accessibility issue?

None

### Reproduction

NA

## Actual Behavior
Similar to https://github.com/microsoft/fluentui/issues/29703, my jest tests will fail when testing combobox. I require multiple reruns to get them to pass due to the animations timing out the test. Can we remove the animations from test environments, like for the dialog in https://github.com/microsoft/fluentui/pull/29692?

## Expected Behavior
Tests regularly pass when rendering combobox in jest test

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
> @layershifter it looks like this issue is persisting. Are you able to look into it and see if your PR just needs to be adjusted?

@micahgodbolt not sure that I follow, this issue is related to `Combobox`, while the original issue was related to `Dialog`. I don't think that these problems are connected.

**Comment by 15MariamS** [comment]
Any way we can disable animations for testing? We're really often needing to add extra logic to our tests because the animations time out in jest tests

**Comment by 15MariamS** [comment]
Can we remove `transition` on testing environments, like here: https://github.com/microsoft/fluentui/pull/29692

**Comment by 15MariamS** [comment]
👋 running into some issues when testing again (combobox and dropdown are _really_ slow in jest tests). How can I speed them up in tests? e.g. can we remove `transition` on testing environments, like in this fix for the modal that had the same issue? https://github.com/microsoft/fluentui/pull/29692

**Comment by layershifter** [comment]
@15MariamS is the issue still relevant? If so, please provide a repro (Github repo/Stackblitz), so we could check.
