### ISSUE TITLE
[Bug]:  Warning: prop classname did not match server: "css-149" client: "css-151"

### ISSUE THREAD

**Issue by KocakAli** [microsoft/fluentui#30115]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
I am using:

Nextjs 14.0.2
fluent ui 8.113
react 18

```

### Are you reporting Accessibility issue?

None

### Reproduction

React / v8

## Actual Behavior
Hey, I am getting this error :

warning: prop classname did not match server: "css-149" client: "css-151" 
didnt render component because of conflict with classname's didnt match

Is there a solution to this problem because I can't find a solution I'm using typescript and app router.

## Expected Behavior
render components properly

### Logs

```shell
warning: prop classname did not match server: "css-149" client: "css-151"
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hello @KocakAli, would you mind providing a codesanbox link with a minimal repro?
