### ISSUE TITLE
Teaching Popover PR Feedback

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#30127]
This issue is tracking the resolution of outstanding comments from PR [feat(react-teaching-popover-preview): Core functionality](https://github.com/microsoft/fluentui/pull/29894)

Unresolved comments from @layershifter:
- [ ] [Use images from CDN in examples](https://github.com/microsoft/fluentui/pull/29894#discussion_r1427770397) 
- [ ] [Fix use of `renderByDefault` in `useTeachingPopoverHeader`](https://github.com/microsoft/fluentui/pull/29894#discussion_r1427795245)
- [ ] [Consider changing `TeachingPopoverButton.buttonType` prop](https://github.com/microsoft/fluentui/pull/29894#discussion_r1427788954) 
- [ ] [Consider changing `TeachingPopoverButton.altStepText` prop](https://github.com/microsoft/fluentui/pull/29894#discussion_r1427789461) 
- [ ] [Remove `Paritial<>` around slots type for `TeachingPopoverPageCountProps`](https://github.com/microsoft/fluentui/pull/29894#discussion_r1427797604) 
- [ ] [Don't use render props: `TeachingPopoverPageCountChildRenderFunction`](https://github.com/microsoft/fluentui/pull/29894#discussion_r1427798617) 
- [ ] [Rename useTeachingPopoverContext.ts to useTeachingPopoverContextValues.ts](https://github.com/microsoft/fluentui/pull/29894#discussion_r1430670341)
- [ ] [Add `defaultCurrentPage` prop to `TeachingPopover`](https://github.com/microsoft/fluentui/pull/29894#discussion_r1430670838) 
- [ ] Update `useTeachingPopoverContextValues` to match what's in `renderTeachingPopover`, and [use `contextValues.teachingPopover` in the render function](https://github.com/microsoft/fluentui/pull/29894#discussion_r1430671019) 
- [ ] [Remove `TeachingPopoverTitle.showDismiss` prop because it's redundant with `dismissButton={null}`](https://github.com/microsoft/fluentui/pull/29894#discussion_r1430675393) 

Unresolved comments from @behowell:
- [ ] [`renderTeachingPopoverPageCount` shouldn't return null](https://github.com/microsoft/fluentui/pull/29894#discussion_r1428373363)
- [ ] [TeachingPopoverPageCount shouldn't render its `carouselIcon` slot multiple times](https://github.com/microsoft/fluentui/pull/29894#discussion_r1432001393)

**Comment by 15MariamS** [comment]
👋 After getting the latest version of the teaching popover, I seem to get a bug on styling. I'm wondering if it may be related to these changes: 
- https://github.com/microsoft/fluentui/issues/30756 (mislabled - it is for v9)
