### ISSUE TITLE
[Bug]: TimePicker is missing do's and dont's

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#30125]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

docs

## Actual Behavior
TimePickerCompat has empty do's and dont's

## Expected Behavior
TimePickerCompat should either have do's and dont's or remove the empty file.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by YuanboXue-Amber** [comment]
Oh good catch! let me add it
