### ISSUE TITLE
[Bug]: [DatePicker] Time Picker with Date Picker, mouse pointer shows area as interactive when it is not.

### ISSUE THREAD

**Issue by redongreen** [microsoft/fluentui#30124]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
https://react.fluentui.dev/?path=/docs/preview-components-timepicker--default#controlled
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/preview-components-timepicker--default#controlled

### Bug Description

Currently the labels "S M T W T.." shows the mouse pointer as interactive. See the gif below. Mouse changes from default to interactive when you hover over the labels "S M T.." but you are unable to select.

![CleanShot 2023-12-19 at 09 01 56](https://github.com/microsoft/fluentui/assets/20573265/affbe404-bcb9-44ab-8d01-50668e59fab3)

Expected behavior:
The label area should not be interactive.

### Logs

```shell
https://react.fluentui.dev/?path=/docs/preview-components-timepicker--default#controlled
```

### Requested priority

Normal

### Products/sites affected

https://react.fluentui.dev/?path=/docs/preview-components-timepicker--default#controlled

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by YuanboXue-Amber** [comment]
This is found in TimePicker bug bash, but it is an issue in DatePicker https://react.fluentui.dev/?path=/docs/compat-components-datepicker--default.
