### ISSUE TITLE
[Bug]: Dialog not rendering properly in d365 (tenant and sandbox)

### ISSUE THREAD

**Issue by rexkenley** [microsoft/fluentui#30126]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 11.00 GB / 32.00 GB
  Browsers:
    Internet Explorer: 11.0.17763.2989
```

### Are you reporting Accessibility issue?

None

### Reproduction

Is there a repo service for pcf components?

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/10548251/71d7b7f6-4290-4002-9aba-829ca695e7ed)

## Expected Behavior
Render the dialog properly

### Logs

```shell
const dlgProps: DialogProps = {
      modalType: "modal",
      open: showColumnEdit
    };

      <Dialog {...dlgProps}>
        <DialogSurface>
          <DialogBody>
            <DialogTitle>Edit column</DialogTitle>
            <DialogContent>
              <ColumnType {...ctProps} />
            </DialogContent>
            <DialogActions>
              <Button {...btnOkProps}>Ok</Button>
              <Button {...btnCancelProps}>Cancel</Button>
            </DialogActions>
          </DialogBody>
        </DialogSurface>
      </Dialog>
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
> Is there a repo service for pcf components?

you could provide a minimal repro with codesandbox based on your setup. 

Couple of things to consider:
* Is this app combining v8 with v9? 
* Have you checked if there's a FluentProvider somewhere up the tree?
* When the Dialog's surface renders, does the wrapper contain a `fui-FluentProvider` classname? if so, are the variables applied empty?

Will wait for a repro or answer on those questions since looking at this, it works correctly in codesandbox.

**Comment by rexkenley** [comment]
I don't think it will show up in code sandbox, because it doesn't occur in my storybook build. It only occurs in the d365 sandbox. 

I am trying to create a slim downed repo (same element structure) but couldn't get it to replicate the issue. The dialog itself is virtually the same.

The component is pure v9
FluentProvider is in the dom

I don't see the fui-FluentProvider near the dialog but it is in the body. 1 thing I did notice is that the "not working" one has only 2 instances, but working one has 3. Could that be it?

Not working
![image](https://github.com/microsoft/fluentui/assets/10548251/4e85ea5e-4935-43cb-ac96-2c8fa2f3250c)

![image](https://github.com/microsoft/fluentui/assets/10548251/a6545ef4-3250-4d9b-9ad6-f4de9aad3465)

Working
![image](https://github.com/microsoft/fluentui/assets/10548251/9656826a-06d3-42a9-8526-381ff63deb16)

![image](https://github.com/microsoft/fluentui/assets/10548251/de1a5926-ee55-4f1f-942a-d54630c1de0a)

**Comment by rexkenley** [comment]
@sopranopillow Well I was able to extract the pcf and it is working.

![image](https://github.com/microsoft/fluentui/assets/10548251/eadd2e44-efe4-439c-960e-5c2c99a0cf77)
![image](https://github.com/microsoft/fluentui/assets/10548251/cbf0807b-f631-4958-8798-13b64685d606)

Do you have any suggestions as to how to find what is causing the dialog "to lose" the Provider? All the other components seem to be unaffected,

**Comment by rexkenley** [comment]
@sopranopillow 

I did some more testing and something weird is going on.

If I add the DialogTest.tsx locally to the pcf project it works fine. But when I use the same file from a library, the theme "gets lost".

Local (themes working)
![image](https://github.com/microsoft/fluentui/assets/10548251/d1c11099-3e1f-456f-9a7c-c75c7c2b67fe)
![image](https://github.com/microsoft/fluentui/assets/10548251/70462b9e-ea99-4d0a-b4ee-b073ae579f7d)
![image](https://github.com/microsoft/fluentui/assets/10548251/be8f1600-f2b4-4f05-9874-e5ed8b700c68)

Library (themes not working)
![image](https://github.com/microsoft/fluentui/assets/10548251/5dd915a5-fc6e-46b6-bb53-02e458bd48d9)
![image](https://github.com/microsoft/fluentui/assets/10548251/72e9b9b1-e482-487e-bc6a-795b561fb2cb)
![image](https://github.com/microsoft/fluentui/assets/10548251/4feb07d5-1919-4a5b-85c7-1db3cc7887cc)

1 thing I did notice is that there is a fluentProvider "wrapper" missing in the Library method.

**Comment by sam961124** [comment]
Same issue here. If we use `<FluentProvider>` from a library, the theme for Dialog won't work. However, if we put `FluentProvider` and `Dialog` in the same repository, then it works. The behavior is the same as @rexkenley had described that the class name "fui-FluentProvider" is missing from the wrapper div. We also only saw this issue on Dialog.

**Comment by micahgodbolt** [comment]
If this is an issue of controls not working properly in a specific internal environment, can we take the conversation into teams? If you suspect there is an actual bug in our code (and we can repro the bug in a codesandbox), we can continue the conversation here.

**Comment by rexkenley** [comment]
@sam961124 , @micahgodbolt 

The workaround I came up with is to include the FluentProvider within the App. This is not ideal as I "kragled" the theme provider with the app.

Original
`<FluentProvider theme><App /></FluentProvider>`

Work around
`<App theme />`

App.tsx
`<FluentProvider theme>...</FluentProvider>`

@micahgodbolt , does the theme provider do some sort of "check" to only load the css if it detects fluent ui children?

**Comment by sopranopillow** [comment]
@rexkenley  It does, when rendeing the mount node for dialogs and such, it checks through context if there's a provider higher up the tree to get the same classname that includes the css vars.

**Comment by marcosmoura** [comment]
@rexkenley @sam961124 I will be closing this issue as the problem seems to be bound to an internal environment. In case you suspect there might be an actual bug, please feel free to reopen and add further comments.
