### ISSUE TITLE
[Bug]: Unable to override submenu icon using submenuIconProps

### ISSUE THREAD

**Issue by joannakuo** [microsoft/fluentui#30141]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 75.41 GB / 127.71 GB
  Browsers:
    Edge: Chromium (120.0.2210.77)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/joannakuo/pen/GReKemO

## Actual Behavior
submenuIconProps not overridden 

## Expected Behavior
submenuIconProps should override chevron icon. (in repro, icon should be + and color should be red)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by fildahui** [comment]
hey @joannakuo , I guess you should use the `menuIconProps` prop
```
<DefaultButton menuProps={menuProps} menuIconProps={menuIconProps} />
```

like in here https://codepen.io/fildahui/pen/eYXpraN

the `subMenuIconProps` on the `menuProps` is meant to be used to configure the chevronRight/Left icons on the subitems, not the chevrondown on the main button (if I remember correctly)
