### ISSUE TITLE
[Bug]: Regression v9.42.0 caused by using floating-ui-devtools in http:// non-localhost contexts

### ISSUE THREAD

**Issue by raphaelsummers** [microsoft/fluentui#30165]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 17.79 GB / 31.59 GB
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

(Will provide specific details below, can't reproduce the issue using codesandbox)

## How to reproduce
- Use fluentui v.9.42.0+
- Add any element such as dropdown
- Launch non-production version in a non-localhost http:// environment (such as `http://www.example.com`)
- Observe that dropdowns and other dynamically positioned elements don't work as expected (are positioned in the left upper corner)
- Observe `crypto.randomUUID is not a function` errors in the browser console

Most likely this happens because the floating-ui-devtools rely on [`crypto.randomUUID`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) that is only available in secure contexts.

Reporting this here since fluentui **unconditionally** uses the floating-ui-devtools in dev contexts, and since it breaks development experience for fluentui.

See #29905.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Fixed by #30235 in https://github.com/floating-ui/floating-ui/pull/2678. Will be a part of the next release.
