### ISSUE TITLE
[Bug]:  TableCellLayout shows the overflow-Y scroll in some computers/browsers

### ISSUE THREAD

**Issue by xavigimenezsanchez** [microsoft/fluentui#30169]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Windows 11, Chrome Version 120.0.6099.130 (Official Build) (64-bit)
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/

## Actual Behavior
The cell shows the scroll bar
![image](https://github.com/microsoft/fluentui/assets/1479342/defedd8c-4b8c-45b1-bbe5-8a5d5df4e8dd)

## Expected Behavior
Not show the scroll bar
![image](https://github.com/microsoft/fluentui/assets/1479342/f3e3fa1c-24ac-4aa9-ab6c-9704ccc77b88)

To fix this issue I've added this style to the component "TableCellLayout"

fixOverflow: {
    "& > div > span": {
      overflowY: "hidden",
    },
  },

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by xavigimenezsanchez** [comment]
@fluentui/react-components version 9.35.0

**Comment by micahgodbolt** [comment]
Can you please supply a working reproduction of the issue
