### ISSUE TITLE
[Feature]: TabList styling interface

### ISSUE THREAD

**Issue by zensho-mjp** [microsoft/fluentui#30172]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Hi everyone,

I've just started to use Fluent UI v9 and discovered a huge change in styling component.
Although you can use makeStyles() to override styles of component, there is no interface anymore for styling purposes like before (IButtonStyles, IDetailsListStyle, IDropdownStyles, etc.).  This is quite annoying because with those interfaces we knew what properties to target to adjust styling of fluent ui components.
I am in the situation where I want to change the Tab styling from the TabList component, and I have nothing at my disposal to know how to do it, and how to be sure I target the correct property.
It would be interesting to add interfaces again so that developers know what they do.

In the meantime, does anyone know how I could style different part of that component?

Thank you,

Maxime

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by micahgodbolt** [comment]
You use slots to style and each component has an interface that defines the slots.
