### ISSUE TITLE
[Bug][Repro provided]: In TextField component, calling focus event using componentRef does not focus in mobile devices

### ISSUE THREAD

**Issue by amishagupta97** [microsoft/fluentui#30183]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 15.69 GB / 31.73 GB
  Browsers:
    Edge: Chromium (120.0.2210.77)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/Amisha-Gupta-the-builder/pen/LYapmYE

## Actual Behavior
TextField focus using componentRef does not open keyboard in mobile devices to start typing.

## Expected Behavior
When using componentRef to focus text field, it should focus the text field in mobile devices for user to start typing instantly.

### Logs

```shell
Affected Fluent UI control -> TextField
```

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Your demo appears incomplete. The ref is never used

**Comment by amishagupta97** [comment]
> Your demo appears incomplete. The ref is never used

Sorry, seems like all the changes were not saved. I have updated the demo code.
![image](https://github.com/microsoft/fluentui/assets/57914033/1589dc0b-be49-4961-bf7b-f7cc35fb7d82)

**Comment by amishagupta97** [comment]
@micahgodbolt hope you were able to reproduce the issue?

**Comment by amishagupta97** [comment]
@micahgodbolt  requesting priority on this bug. Please let me know if you need more details.

**Comment by spmonahan** [comment]
@amishagupta97 Can you share which devices you have this problem with? I'm not able to repro on iOS 18 with Safari 18.
