### ISSUE TITLE
Menu: Menu not adhering to larger text accessibility setting on iOS

### ISSUE THREAD

**Issue by anilsingla-ms** [microsoft/fluentui#30189]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
iOS Teams/Loop App
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/sharp-wescoff-3jy87t

## Actual Behavior
Menu items are not adhering to larger text accessibility setting on iOS. Due to which items shown are smaller in size.

## Expected Behavior
Menu items should adhere to larger text setting and should appear larger as per the setting's value.

### Requested priority

High

### Products/sites affected

https://loop.microsoft.com/

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by GeoffCoxMSFT** [comment]
@ling1726 Could you kindly take a look at this? We need to verify that the Menu should increase text size according to the design figma and then see if there is a bug to fix.

**Comment by smhigley** [comment]
Web content does not adjust text size based on the iOS Settings Larger Text feature unless you [add the Apple system font](https://dev.to/colingourlay/how-to-support-apple-s-dynamic-text-in-your-web-content-with-css-40c0) to the font family. I believe we intentionally do not set `-apple-system-body` in our default font family in Fluent, but I'd recommend considering doing so for hybrid native apps. For apps rendered in a web browser, the browser's own font scaling will work on web content.

Here's a screenshot of that same codepen with vanilla unstyled heading and paragraph text added so you can see that no content is scaled by default (compare to the URL bar below, which has scaled up with the text size setting):

![screenshot of a web page with tiny text, followed by a URL bar with large text](https://github.com/microsoft/fluentui/assets/3819570/d1d3e2c8-a3d8-42b2-9c2a-2c9fbda62c40)
