### ISSUE TITLE
[WeeklyDayPicker]: Replacing day with short month name for first month day in week view causes misalignment in certain languages

### ISSUE THREAD

**Issue by Ashwin-Nikam** [microsoft/fluentui#30193]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (32) x64 AMD EPYC 7763 64-Core Processor
    Memory: 106.75 GB / 125.78 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/ashwin-7/pen/jOJbJmm

### Bug Description

If the current week in the WeeklyDayPicker consists of the first day of the month and we are only showing 1 week, we replace the day with short month name

![image](https://github.com/microsoft/fluentui/assets/23515356/92f6dd35-2c57-454d-8777-fe074ecb2f26)

[Codepen](https://codepen.io/ashwin-7/pen/jOJbJmm)

This results in misalignment in some languages as can be seen in the following screenshot which is most likely because of the longer month name is certain languages

![image](https://github.com/microsoft/fluentui/assets/23515356/afba3263-417b-4da1-8bce-b583794fcc54)

To address this, I'd like to propose that we give the consumers of this control the option to toggle off [this](https://github.com/microsoft/fluentui/blob/f4b8c348a749229dcf1d9fdbf07ee3476e9b95a7/packages/react/src/components/CalendarDayGrid/CalendarMonthHeaderRow.tsx#L17) behavior if and when needed so we won't swap the day for the short month name. 

### Requested priority

Normal

### Products/sites affected

Outlook web

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hi Ashwin, we no longer plan on adding any features to the components in v8. Have you taken a look at our v9 DatePicker and Calendar compat? These provide the same functionality as v8, if the feature is needed there as well, we can look into adding it there!
