### ISSUE TITLE
[Bug]: react-components peer-dep `@types/react-dom` requires non-existent version for 16.x 

### ISSUE THREAD

**Issue by octogonz** [microsoft/fluentui#30196]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (14) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 3.76 GB / 10.75 GB
  Browsers:
    Chrome: 120.0.6099.130
    Edge: Chromium (120.0.2210.77)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

The source code is obviously wrong without need for a repro

## Actual Behavior

When trying to install `@fluentui/react-components@9.27.4` using `react@16.x`, the installation fails with error such as:
```
│ │ ├─┬ @fluentui/react-aria 9.6.0
│ │ │ ├── ✕ unmet peer react@">=16.14.0 <19.0.0": found 16.13.1
│ │ │ ├── ✕ unmet peer @types/react-dom@">=16.14.0 <19.0.0": found 16.9.14
│ │ │ ├── ✕ unmet peer react-dom@">=16.14.0 <19.0.0": found 16.13.1
```

The latest published version of `@types/react-dom@16.x` is `16.9.24`.

However FluentUI's **package.json** constraint requires `">=16.14.0 <19.0.0"`.  

## Expected Behavior

The mentioned version `16.14.0` is nonsensical.  The `"peerDependencies"` field should refer to version numbers that actually exist.  

Alternatively, if FluentUI has dropped support for React 16, then the version ranges should not refer to version `16`.

### Requested priority

Blocking

### Products/sites affected

https://github.com/microsoft/rushstack/tree/main/vscode-extensions/rush-vscode-command-webview

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
our react peer deps all got bumped up to >=16.14.0 in this PR https://github.com/microsoft/fluentui/pull/28959, but types/react-dom doesn't have a version past 16.9.8
