### ISSUE TITLE
[Bug]: fix flaky HorizontalBarChartWithAxisRTL.test.tsx test that cause intermittent master pipeline failures

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#30216]
### Library

@fluentui/react-charting

### System Info

```shell
na
```

### Are you reporting Accessibility issue?

None

### Reproduction

Failed pipelines
- https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=329693&view=logs&j=e51d397b-0a7b-5b89-4b48-0052e021371d&t=88c41216-94ff-5ca8-d686-48ce16c1eefc
- https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=329866&view=logs&j=e51d397b-0a7b-5b89-4b48-0052e021371d&t=88c41216-94ff-5ca8-d686-48ce16c1eefc

## Actual Behavior

react-charting tests are flaky

## Expected Behavior

react-charting tests should be reliable on CI

### Requested priority

High

### Products/sites affected

monorepo CI

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by AtishayMsft** [comment]
@v-baambati is already looking into it.

**Comment by Hotell** [comment]
another master failure 

https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=330813&view=logs&j=e51d397b-0a7b-5b89-4b48-0052e021371d&t=88c41216-94ff-5ca8-d686-48ce16c1eefc


<img width="1441" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/1267b18f-df53-40c3-a5e7-ecedbb96d3a6">

re-opnening

**Comment by AtishayMsft** [comment]
@v-baambati The below test also needs to be skipped for prod pipeline.

https://github.com/microsoft/fluentui/blob/d8321c5e8191f94e9413aee0e800f96d3de8e311/packages/react-charting/src/components/HorizontalBarChartWithAxis/HorizontalBarChartWithAxisRTL.test.tsx#L296
also under runtest.

**Comment by AtishayMsft** [comment]
Few tests causing the issue were missed. These are fixed in #30297.
Closing the issue.
