### ISSUE TITLE
[Bug]: Spinner component is not loading sometimes under Edge browser

### ISSUE THREAD

**Issue by xhywxtt** [microsoft/fluentui#30214]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 10.62 GB / 31.72 GB
  Browsers:
    Edge: Chromium (120.0.2210.91), ChromiumDev (121.0.2277.4)
    Internet Explorer: 11.0.19041.3636
    Chrome: 120.0.6099.130
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-spinner--default

## Actual Behavior
The icon of Spinner is loading under Chrome browser, but it is not loading under Edge browser sometimes.
- Chrome:
![image](https://github.com/microsoft/fluentui/assets/8031353/2113ef39-b3a3-4d09-b94e-e54ab97ebaa0)

- Edge:
![image](https://github.com/microsoft/fluentui/assets/8031353/81721472-ebc4-4c6c-9b7d-b327bae12e7b)

## Expected Behavior
The icon of Spinner should be loading.

Note: this bug can be easily repro on fluentui document: https://react.fluentui.dev/?path=/docs/components-spinner--default

### Requested priority

High

### Products/sites affected

Wallet Express Checkout in Edge browser

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
The spinner works fine in my version of edge. You probably have 'prefers reduced animation' turned on in your windows or browser settings

**Comment by xhywxtt** [comment]
I have checked my windows settings:
![image](https://github.com/microsoft/fluentui/assets/8031353/8ccf74d8-1e35-4856-bfe6-fa7183644c8b)

 
And I cannot find settings on browser

However, from my side, each time it's different. Sometimes it works on chrome but didn't work on Edge. Sometimes it works well on Edge. Sometimes it cannot work for both Edge and Chrome

**Comment by layershifter** [comment]
@xhywxtt when it reproes, please evaluate `window.matchMedia("(prefers-reduced-motion)").matches` in the browser's console and check what it returns. If it's `true` => motion is reduced according to OS/browser settings and it's expected.
