### ISSUE TITLE
[Bug]: fix new act errors in react-charting tests

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#30215]
### Library

@fluentui/react-charting

### System Info

```shell
na
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=329693&view=logs&j=e51d397b-0a7b-5b89-4b48-0052e021371d&t=88c41216-94ff-5ca8-d686-48ce16c1eefc

## Actual Behavior

some amount of act errors have been fix https://github.com/microsoft/fluentui/pull/30143

act errors are present in following tests:
- src/components/GaugeChart/GaugeChart.test.tsx
- src/components/HeatMapChart/HeatMapChartRTL.test.tsx

## Expected Behavior

after adding new tests new act errors are present.

- we need to fix those
- going forward we need to establish a style guide/rules that wont pass PRs to be merged if those violations exist

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by AtishayMsft** [comment]
@srmukher Why are new act errors being reported now. What is the permanent fix for it.

**Comment by srmukher** [comment]
> @srmukher Why are new act errors being reported now. What is the permanent fix for it.

Looks like these are because of the accessibility tests which are checked in after my PR. I had fixed most of them which were checked in before mine.
