### ISSUE TITLE
[Bug]: Scrollable Drawer divider showing behind inputs

### ISSUE THREAD

**Issue by Cam-Bloom** [microsoft/fluentui#30228]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700
    Memory: 8.08 GB / 31.70 GB
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.3636
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/mystifying-colden-4htnzg?file=%2Fsrc%2Fexample.tsx%3A40%2C42

## Actual Behavior
Border between DrawerHeader component and DrawerBody component, shows behind inputs in the DrawerBody
![image](https://github.com/microsoft/fluentui/assets/117858656/f20e8efe-b275-43ac-8529-921fc1289b33)

## Expected Behavior
Border shows in front of inputs to have a clear barrier between header and body

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
your 'actual behavior' screenshot looks different than the CSB demo

![image](https://github.com/microsoft/fluentui/assets/1434956/4687b9d9-4287-4edb-9aec-c1328e623209)

Is this the correct demo?

**Comment by Cam-Bloom** [comment]
Yeah demo is correct, screen shot is from my project, the problem is the border in-between `DrawerHeader` and `DrawerBody` in both example and screen shot should be able to see that the line in broken by the input, as if the input has a higher z index, I expected the result to be as so:
![image](https://github.com/microsoft/fluentui/assets/117858656/098829ea-82e0-44ff-9fdd-1e0b623997d8)

Where the line remains complete to provide a barrier between header and body, code sandbox of the expected behaviour to compare 
https://codesandbox.io/p/sandbox/silly-gwen-c7r5w7?file=%2Fsrc%2Fexample.tsx%3A154%2C35-157%2C77

**Comment by marcosmoura** [comment]
The is a bug. We will addressed it ASAP.

**Comment by jvince** [comment]
Hi @marcosmoura!

We also have an issue with the linear gradient as the background image used in the drawer's body.
 In our case, we are using Cards inside the Drawer.

Reproduction: https://codesandbox.io/p/sandbox/hungry-tdd-rw22lz?file=%2Fsrc%2Fexample.tsx%3A94%2C28
