### ISSUE TITLE
[Bug]: Reading component name (Separator) instead of text within the Separator component even after providing aria-label="Preview".

### ISSUE THREAD

**Issue by RituShinde** [microsoft/fluentui#30229]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz   
    Memory: 5.30 GB / 15.68 GB
  Browsers:
    Chrome: 120.0.6099.131
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.3636
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/p/sandbox/busy-ives-rcmdmj?file=%2Fsrc%2FApp.js%3A7%2C16

## Actual Behavior
Reading Component name

## Expected Behavior
Should read text provided in the component

### Logs

```shell
<Separator alignContent="start" aria-label="Preview">
        Preview 
</Separator>
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
please provide a working code demo
