### ISSUE TITLE
[Bug]: SpinButton increment / decrement button bounds behaving improperly.

### ISSUE THREAD

**Issue by Aloento** [microsoft/fluentui#30234]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-spinbutton--default#bounds

### Bug Description

1. increase to 20
2. decrease to 19

Then, incrementButton has the disabled style.

3. decrease to 0
4. increase to 1

Then, decrementButton has the disabled style.

---

I think only when 0 / 20 should have the disabled style but it didn't.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Ri96** [comment]
this is only happening in the page, but it's working fine if you open the sandbox and try.

**Comment by micahgodbolt** [comment]
Confirmed, this doesn't appear to repro in a code sandbox. Maybe it has something to do with all of the different SpinButtons on the storybook page? Or maybe something about the storybook app itself? Worth looking into if its a deep underlined problem.

**Comment by Aloento** [comment]
@micahgodbolt This problem appeared in my own app, so I opened this issue. Can you investigate it? Thx.

**Comment by Jing29** [comment]
It also repro in the real product. Maybe because sandbox has some special setting which stops the issue happened. Please ensure that the story book doesn't have such issue.
