### ISSUE TITLE
[Bug]: When a detailList row is selected, for columns with button it is reading previous column as well.

### ISSUE THREAD

**Issue by RituShinde** [microsoft/fluentui#30231]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz   
    Memory: 5.30 GB / 15.68 GB
  Browsers:
    Chrome: 120.0.6099.131
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.3636
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/affectionate-roman-htx55n?file=%2Fsrc%2Findex.tsx%3A77%2C22

## Actual Behavior
When a detailList row is selected, for columns with button it is reading previous column as well.

## Expected Behavior
When a detailList row is selected, for columns with button it should not read the previous column content. It should read content provided in aria-label for columns with button.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
please fix the CSB, they don't load
