### ISSUE TITLE
[Bug]: Reading 'button selected selected' for a button column in selected row: Accessibility testing

### ISSUE THREAD

**Issue by RituShinde** [microsoft/fluentui#30232]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz   
    Memory: 5.30 GB / 15.68 GB
  Browsers:
    Chrome: 120.0.6099.131
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.3636
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/upbeat-chandrasekhar-kssv8z?file=%2Fsrc%2Findex.tsx%3A78%2C45

## Actual Behavior
Reading 'button selected selected' for a button column in selected row.

## Expected Behavior
Should read 'button selected' for a button column in selected row.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
your CSB doesn't appear to be loading, can you look over it

**Comment by micahgodbolt** [comment]
and duplicate reading by narrator is often due to more popular screen readers requiring this narration setup in order to work properly. If the only issue is a button stating 'selected' twice, it was probably done for a reason.

**Comment by marcosmoura** [comment]
@RituShinde Could you check the past two comments? :)
