### ISSUE TITLE
[Feature]: Search bar in Icon using SVG factory  

### ISSUE THREAD

**Issue by shumbul** [microsoft/fluentui#30243]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Currently it is very difficult to navigate and look for [icons](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/icon) using svg factory. A search bar is a must have feature on that page.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by tomi-msft** [comment]
Hello @shumbul, thanks for submitting the issue. Please use [this](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/styles/web/icons) page to search for v8 icons, there is a searchable catalog there.
