### ISSUE TITLE
[Bug]: Coachmark difficult to click on mobile

### ISSUE THREAD

**Issue by harryhaomsft** [microsoft/fluentui#30273]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 4.08 GB / 31.71 GB
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/coachmark

## Actual Behavior
This bug repros on the FluentUI Coachmark demo page. This repros on mobile but also repros on device emulator on browser devtools. 
 - Open the Coachmark demo page https://developer.microsoft.com/en-us/fluentui#/controls/web/coachmark
 - If using desktop browser, use device emulator(any size). Or open on mobile browser.
 - Observe that the coachmark shows up, but when try to click on it, it's almost unclickable. There is a small corner area you can click on but most of the coachmark does not respond to click. On mobile device it's actually impossible to click on it

## Expected Behavior
Coachmark reacts to clicking on Mobile like in desktop environments

### Requested priority

High

### Products/sites affected

stream.aspx on SharePoint - example https://microsoft.sharepoint-df.com/:v:/t/cyrusdogfood/EdhqHufZwdVFhLtcAvoqGLoBmek-2YufjnH9ShCupmkQjg?e=ViUJao&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
when opened in a codepen it seems to work better on my mobile device, but the hit target is difficult for sure
