### ISSUE TITLE
[Bug]: v9 bundleIcon does not pass down primaryFill

### ISSUE THREAD

**Issue by ReillyBova** [microsoft/fluentui#30272]
### System Info

```shell
Relevant packages: 


    "@fluentui/react-components": "9.44.1",
    "@fluentui/react-icons": "2.0.224",
```

### Are you reporting Accessibility issue?

None

### Reproduction

See repro from docs

## Actual Behavior
The bundleIcon util documented [here](https://react.fluentui.dev/?path=/docs/concepts-developer-icons-icons--page) does not behave as expected.

In particular, it does not pass down the `primaryFill` prop to the internally rendered icon, which is a real issue.

Additionally, the documentation linked above has other problems: "iconClass" appears meaningless, and the <AccessIcon /> node is missing the `filled` prop required to default to the filled variant on no-hover.

As a bit of feedback to the component design / dev team, we are finding the v9 icon system a bit cumbersome to work with compared to previous Fluent libraries that we've worked with. In particular, it'd be very helpful if a pre-bundled version of each icon was available to import directly from the fluent-icons library.

## Expected Behavior
The color passed via primaryFill prop to the root export of bundleIcon should apply to the rendered icon. In the docs example, a purple filled icon should be visible, but I am seeing a regular icon with the active font color applied.

### Requested priority

Blocking

### Products/sites affected

Viva Insights

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ReillyBova** [comment]
Here is a PR: https://github.com/microsoft/fluentui-system-icons/pull/679

**Comment by micahgodbolt** [comment]
this can be closed as soon as we pull in the latest icons
