### ISSUE TITLE
[Feature]:  Support of different calendar systems for FluentUI Calendar

### ISSUE THREAD

**Issue by claudiuciumedean** [microsoft/fluentui#30292]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Hello,
I would like to know if there is any plan on supporting different calendar systems, other than Gregorian, for the FluentUi calendar.

I am asking this since we have just integrated the FluentUi calendar in our application and it would add great value to our product if the calendar was to support different calendar systems. In last year we actually had quite a few support tickets where customers were complaining that the Hijri calendar  was not supported.
I can see that at some point someone opened [an issue](https://github.com/microsoft/fluentui/issues/9634) on this topic but there was no action on it.

Thank you

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by micahgodbolt** [comment]
We have no plans to support other calendars. This ask has been brought up before.

**Comment by claudiuciumedean** [comment]
@micahgodbolt 
Sure, but the comment is from 4 years ago. I was hoping that things have changed.
Is there a good reason to why you are not planning on supporting other calendars?

I believe that other Microsoft products, including the one I am working on, would benefit greatly.
