### ISSUE TITLE
[Bug]: Tree leaf nesting too deep.

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/fluentui#30300]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.23615
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 30.26 GB / 63.91 GB
  Browsers:
    Edge: Chromium (121.0.2277.4)
    Internet Explorer: 11.0.23615.1000
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/mystifying-dream-k26vsv

## Actual Behavior
Leaf nesting is too deep - this is especially noticeable when the leaf node has an `iconBefore`

## Expected Behavior
See reproduction link - I hacked it by decreasing the aria-level

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
seems this repros on our docsite as well
![image](https://github.com/microsoft/fluentui/assets/1434956/bbbda004-b856-45d0-bf3c-0dc772ec2b39)

**Comment by micahgodbolt** [comment]
oh....i think the hope is that the level 2 items would be lined up with the chevron?

**Comment by GordonSmith** [comment]
FYI Things get even worse when using `expandIcon` and/or `iconBefore`:
![image](https://github.com/microsoft/fluentui/assets/966863/a1a357b7-760b-4209-afee-5907843b6903)

But I don't want the open folder AND the expand contract icon so I switch to `expandIcon`:
![image](https://github.com/microsoft/fluentui/assets/966863/8819e0d5-3f2c-4302-8663-69fc9eb19bad)

**Comment by bsunderhus** [comment]
> @bsunderhus can you please check what design says?

Seems like there's no design spec on this. I'll follow up

**Comment by bsunderhus** [comment]
The problem here is how will this look like in the case you have leaves side by side with branches, right now the nodes that are on the same level will be aligned

![image](https://github.com/microsoft/fluentui/assets/5483269/ed47decf-99e0-4a51-a674-6849c10c2011)


With this requested change they won't be anymore

![image](https://github.com/microsoft/fluentui/assets/5483269/dcd21835-b11e-4351-817a-54edbb4b2fdf)


As we don't have any design spec on this I'll contact main designer to follow up on this

**Comment by GordonSmith** [comment]
> With this requested change they won't be anymore
...this requested change has nothing to do with your second image...

**Comment by toshie-rashtavie** [comment]
Hi @GordonSmith! Designer here! ✨  

The default indentation works in 24px increments, which is the same width of the container that holds the `expandIcon`. If you have a leaf item that does not contain any children, an additional 24px indent is added to make up for the lack of an `expandIcon`. This was done to maintain visual alignment for scenarios where you have a mix of child items that **have children within them** and leaf items. The visual alignment is needed for users to understand where they are within a tree and what level they're in. 

If you know that all child items won't have its own set of children, then you could reduce the indentation by 24px and it would look less indented. But if there will be a chance of child items with more children, those child items will have an `expandIcon` and it will break the visual hierarchy if you don't add the additional 24px indent. I've attached an image below:

![image](https://github.com/microsoft/fluentui/assets/107895541/aee1d27f-e0bb-441f-91f3-2a752c0cfd9c)

Hope that made sense, happy to chat through this more! 😄

**Comment by GordonSmith** [comment]
Looks like what I would expect - From a design perspective I would add the following scenarios:

|Branch Chevron|Branch Icon|Leaf Icon|
|-----------------|-------------|----------|
|yes|no|no|
|no|yes|no|
|yes|no|yes|

Basically if a leaf / Branch does not have an Icon, I would expect the text to start where the icon would be?

**Comment by toshie-rashtavie** [comment]
@GordonSmith Yep! That's right, you could have a row where all those columns be `Yes` as well. In your table, I would highly recommend leaning towards rows where the `Branch Chevron` is a `Yes` to give more of a visual indicator to users that it is a group that can be expanded.

In addition to all of that, I would not recommend a mixed group of items where some have an icon and some don't, this also makes it hard to understand where you are within a `Tree`. Screenshot below: 

![image](https://github.com/microsoft/fluentui/assets/107895541/e12ec50c-55ed-4841-862a-7076df2c5774)

I will work with content design to get this in the usage guidance, thank you for bringing this up! 😄

**Comment by bsunderhus** [comment]
Thx @toshie-rashtavie for the examples! following up on the examples you've provided we have an inconsistency:

![image](https://github.com/microsoft/fluentui/assets/5483269/88019286-9abe-4e9f-95dd-736be77792eb)

On the example `No chevron all up`, children node expects parent to have a expand icon. I'll follow up with a PR to fix that specific case, here's the [example](https://codesandbox.io/p/sandbox/flamboyant-heisenberg-rsdvkh?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrhj5qi300063j6igjreoph9%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrhj5qi300023j6i0itdbyng%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrhj5qi300033j6i19pbwrkh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrhj5qi300053j6idptcpbo9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrhj5qi300023j6i0itdbyng%2522%253A%257B%2522id%2522%253A%2522clrhj5qi300023j6i0itdbyng%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clrhj5qi300053j6idptcpbo9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrhj5qi300043j6i9gwh8h6b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrhj5qi300053j6idptcpbo9%2522%252C%2522activeTabId%2522%253A%2522clrhj5qi300043j6i9gwh8h6b%2522%257D%252C%2522clrhj5qi300033j6i19pbwrkh%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrhj5qi300033j6i19pbwrkh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A11.473354231974923%257D) of all the cases you presented
