### ISSUE TITLE
In High Contrast Mode, Choicegroup Hover doesnot highlight the radio button 

### ISSUE THREAD

**Issue by akhil10805373** [microsoft/fluentui#30302]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
In High Contrast Mode, Choicegroup Hover doesnot highlight the radio button
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/akravindran123/pen/dyrOpOq

## Actual Behavior
When I hover over the unselected radio button within Choicegroup nothing happens in HighContrast Mode

## Expected Behavior
When I hover over the unselected radio button within Choicegroup it should highlight a small circle in HighContrast Mode

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Hover is not required for accessibility, and often makes HC mode harder to use.
