### ISSUE TITLE
[Bug]: Test Failure - Error: Cannot resolve '/<url>', 

### ISSUE THREAD

**Issue by nishila2** [microsoft/fluentui#30311]
### Environment Information

- NodeJS: 18.19.0
- vitest: 1.1.0
- OS: Windows 11 Pro / 23H2
- @microsoft/signalr: 8.0.0

### Describe the issue:

While creating a @microsoft/signalr.HubConnection for testing, I got an error: cannot resolve '/testUrl'.

#### Actual behavior:

Tests are crashing when upgrading `@microsoft/signalr` to 8.0.0. but there is no error when it is the second-latest version, 7.0.14.

`Error: Cannot resolve '/chat'.`
 `❯ HttpConnection._resolveUrl node_modules/@microsoft/signalr/src/HttpConnection.ts:563:19`
 `❯ new HttpConnection node_modules/@microsoft/signalr/src/HttpConnection.ts:76:29`
 `❯ HubConnectionBuilder.build node_modules/@microsoft/signalr/src/HubConnectionBuilder.ts:250:28`
 `❯ src/EventContext.tsx:8:4.withUrl("/chat").withAutomaticReconnect().build();`
 ` export const EventManagerContext =`
 `❯ src/Footer.tsx:2:31`

#### Expected behavior:

All tests should pass as before.

#### Reproduction
https://github.com/nishila2/microsoft.signalr.8.0.0.test.failure

##### The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Please report the issue to the proper repo. I don't Fluent UI package in your repro repository.
