### ISSUE TITLE
Size reduction continuation.

### ISSUE THREAD

**Issue by srmukher** [microsoft/fluentui#30318]
Draft PR - Bundle size by ankityadav4 · [Pull Request #30244 · microsoft/fluentui (github.com)](https://github.com/microsoft/fluentui/pull/30244)

**Comment by AtishayMsft** [comment]
We are focusing on migrating charts to fluent v9 stack.
This will bring out of box size optimizations by adopting smaller number of design tokens, smaller number of fluent utilities and newer d3 dependencies.
