### ISSUE TITLE
[Bug]: "ResizeObserver loop completed with undelivered notifications." error when try using DataGrid with resizableColumns

### ISSUE THREAD

**Issue by mkokabi** [microsoft/fluentui#30312]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1270P
    Memory: 7.64 GB / 31.24 GB
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/mkokabi/testApp

## Actual Behavior
Showing this error: ResizeObserver loop completed with undelivered notifications.

## Expected Behavior
Allowing 

# Note: 
Please checkout the branch addinAuth
I have also created the root https://github.com/mkokabi/root

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mkokabi** [comment]
Hi @Hotell ,
Yes, It's for react V9 components. I would try to create a repro in codesandbox but initially I was suspicious that issue is related to using datagrid in a single-spa and I don't think a single-spa solutions could be created in codesandbox. Then I created this repo in github with another repo for the root. But the issue didn't happen and I went one step further and added MSAL and it started happening. 
Regards

**Comment by george-cz** [comment]
Hello @mkokabi, unfortunately I'm unable to run your demo project locally.

Please provide better steps how to run the project and reproduce the issue, or even better, a codesandbox link.

Thank you.

**Comment by 15MariamS** [comment]
👋 also running into this. @mkokabi did you find a fix?

**Comment by StevenDeRoover** [comment]
I too, just today, noticed this issue.

For me, I have a combobox (a simple one, with just a few options).  The combobox works fine, but when I resize the window, so that the "popup" of the dropdown will appear outside the window bounds, I get this error message.
Imho, I think this has something to do with the combobox (and maybe other controls) trying to position the popup, and failing so.

I've also tried to adjust the positioning to "above" (because the dropdown is on the bottom of my page), but that did not resolve the issue.

**Comment by Patchrik** [comment]
@StevenDeRoover I'm seeing this issue with the Select component as well. Seems if the Popover could render outside of the container I get the error. And yes even having the pop over render above the select, still doesn't fix the issue.

**Comment by Patchrik** [comment]
@15MariamS  and @StevenDeRoover 

Are both of y'all using react to make a Teams app by chance?

I'm getting this error within Teams running in Chrome when the popover for dropdown or combobox would overflow the container boundary.

**Comment by 15MariamS** [comment]
> Are both of y'all using react to make a Teams app by chance?
> 

Using React to make a Microsoft Word add-in. But same setup — getting the error when the combobox list overflows

**Comment by nadineshmo** [comment]
Hi, I am wondering why this issue got closed? I am having the same issue with DataGrid.

**Comment by hasannaqvi83** [comment]
Guys, try adding below snippet in your index.tsx/js file

```
// --- FIX START: Fluent UI v9 ResizeObserver Patch ---
const OriginalResizeObserver = window.ResizeObserver as any;

window.ResizeObserver = class ResizeObserver extends OriginalResizeObserver {
  constructor(callback: ResizeObserverCallback) {
    super((entries: ResizeObserverEntry[], observer: ResizeObserver) => {
      window.requestAnimationFrame(() => {
        if (!Array.isArray(entries) || !entries.length) return;
        
        // FIX: Cast 'observer' to 'any' to satisfy TypeScript (TS2345)
        callback(entries, observer as any);
      });
    });
  }
} as any;
// --- FIX END ---
```
