### ISSUE TITLE
[Bug]: FluentProvider clutters the React component tree with nine (9!) nested providers

### ISSUE THREAD

**Issue by LarsKemmann** [microsoft/fluentui#30314]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz
    Memory: 1.31 GB / 15.95 GB
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.3636
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/sandbox/funny-sanne-y7zlp3?file=%2Fsrc%2Findex.tsx%3A11%2C41

## Actual Behavior
`<FluentProvider />` should be intelligent enough to provide state to the application without cluttering up the component tree. Especially because it often lives near the root of the application, this number of nested components makes navigating the Components view (and various troubleshooting activities) more difficult.
![image](https://github.com/microsoft/fluentui/assets/5834429/33418cfc-fdba-48e0-b66b-bedaebffb39f)

## Expected Behavior
```
<AppRoot />
  <FluentProvider />
    <App />
      <Button />
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
Thanks for report ! We are well aware about this and it is by design.

As you can see our provider renders multiple shared global contexts https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-provider/src/components/FluentProvider/renderFluentProvider.tsx

while its indeed possible to mitigate this with additional abstraction/3rd party library, without performance downgrades ( re rendering all trees wrapped into context if 1 value changes etc), we decided to go with granular/vanilla  approach.

Folks can add more context @microsoft/teams-prg

**Comment by layershifter** [comment]
While some contexts could be collapsed, for example, we can merge `Provider`, `ThemeClassNameProvider` & `OverridesProvider` - there are other contexts like `IconDirectionContextProvider` & `TextDirectionProvider` that are coming from other packages/repositories:

https://github.com/microsoft/fluentui/blob/0c422edc87177d3d707c71fa3cad3fa2b872bdf8/packages/react-components/react-provider/src/components/FluentProvider/renderFluentProvider.tsx#L31-L40

There are also no proven performance issues with the current approach. Other libraries have similar structure for top level providers i.e. it's a common thing/approach. To collapse the tree in devtools, I suggest to rely on node filtering (devtools have built-in filter for context nodes):

<img width="454" alt="image" src="https://github.com/microsoft/fluentui/assets/14183168/ede23abb-bbab-421c-a6f5-c58cd5ca6ff9">
