### ISSUE TITLE
[Feature]:  Mac friendly Monospace font fallback

### ISSUE THREAD

**Issue by Daniel-Gla** [microsoft/fluentui#30325]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Render platform-native code snippets on Apple devices, using the Menlo typeface before falling back to the Courier New font.

### Have you discussed this feature with our team

Micah Godbolt

### Additional context

Current appearance:
![Snippet on Mac](https://github.com/microsoft/fluentui/assets/149529832/307b4a94-ffb8-4ea3-9ce7-c4c4fcc38150)
Suggested appearance:
![Snipper on Mac 2](https://github.com/microsoft/fluentui/assets/149529832/9a9fb09d-2424-4b31-9ac9-dd52e04e46ce)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by k3sha7** [comment]
Hi there! I'm a new contributor and interested in tackling this issue (# [30325]). I've reviewed the description and believe I have the skills necessary to address it. Would you be able to assign it to me?

**Comment by tudorpopams** [comment]
Hello @Daniel-Gla and @k3sha7 , thank you both for the interest in this topic. We are discussing it with our design team to see if it would make sense to have this feature implemented from a design POV. Will update as soon as we have any news.

**Comment by gouttierre** [comment]
Here is a brief update on the issue raised. Fluent does not have any guidance on monospaced fonts. Apple recently switched from Menlo. MacOS uses SF Pro as the system font for UX. The monospaced font would be SF Mono. 
@k3sha7, we appreciate your willingness to contribute to this issue. Please, submit your PR when you are done and the team will review it.
cc @tudorpopams
