### ISSUE TITLE
[Bug]: V9 MessageBar grid multi-line layout is not right when there's no secondaryAction

### ISSUE THREAD

**Issue by zhou-0818** [microsoft/fluentui#30331]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22623
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 10.16 GB / 31.80 GB
  Browsers:
    Edge: Spartan (44.22621.1245.0), Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/flamboyant-engelbart-wlzs2k

## Actual Behavior
When we only have message content and dismiss button, the grid layout has two rows.
![8954d740-6298-4960-aa7c-e6cf712c73f0](https://github.com/microsoft/fluentui/assets/53247081/5a52a0a1-a896-47f5-a69c-1917bbd05157)
## Expected Behavior
Should only has one row, 
![image](https://github.com/microsoft/fluentui/assets/53247081/fc68282f-9e21-47d2-a1d0-4fb2c7ad36ee)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
not sure why this is a problem as without that 2nd row you wouldn't get any padding, but @ling1726  can provide more context.

**Comment by ymyqwe** [comment]
Also spotted this issue. This will happen when there is close icon and no really actions with multiline layout.
