### ISSUE TITLE
[Bug]: Tab zIndex is set and causes overlap issues

### ISSUE THREAD

**Issue by agetmanchuk2** [microsoft/fluentui#30343]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 13.48 GB / 47.71 GB
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/sandbox/dawn-wind-5jqmhk

## Actual Behavior
TabList <Tab /> component has a zIndex that overlaps all other content without zIndex (such as infoBubble)

## Expected Behavior
should remain on the same level as the rest of the tab and not overlap other content 

![image](https://github.com/microsoft/fluentui/assets/141177817/28cd939e-65a3-4130-b117-77d33d357dbb)

Repro steps:
tablist under an infobubble
when info bubble opens above a selected tab, the line under of the tab appears over infobubble content

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by yongfront** [comment]
Can I fix this issue?

**Comment by yongfront** [comment]
May I fix this issue?

**Comment by agetmanchuk2** [comment]
Is there any update on the status of the resolution?

**Comment by agetmanchuk2** [comment]
Based on testing, this bug is not properly resolved. The initial issue still persists
