### ISSUE TITLE
[Bug]: New Dropdown and Combobox clearable button missing "button" type

### ISSUE THREAD

**Issue by xkadl17** [microsoft/fluentui#30344]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components: 9.44.5
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/ws95pc?file=src%2Fexample.tsx

## Actual Behavior
Currently the new clearable button in Dropdown and Combobox is missing `type="button"` attribute, so when you press it inside from, it will submit the form. (Codesandbox posted from docs)

<img width="1095" alt="image" src="https://github.com/microsoft/fluentui/assets/32716481/c64ba880-ac51-4a3d-aa4a-49b9822464bf">

## Expected Behavior
The attribute should be added, so it prevents form submission. (It is already on the expand icon button)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
FYI that's only a problem for `Dropdown` as `Combobox` renders a `span` instead:

https://github.com/microsoft/fluentui/blob/6220c3d5d2e41a549e831b563eaa2ef3605047fc/packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx#L110-L117

**Comment by xkadl17** [comment]
> FYI that's only a problem for `Dropdown` as `Combobox` renders a `span` instead:
> 
> https://github.com/microsoft/fluentui/blob/6220c3d5d2e41a549e831b563eaa2ef3605047fc/packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx#L110-L117

That's interesting, is it accessible when it's a `span`? Not sure if there was a reason not to make it a button.

**Comment by layershifter** [comment]
> That's interesting, is it accessible when it's a `span`? Not sure if there was a reason not to make it a button.

No, in `Combobox` clear button is hidden from screen readers, see #30033. That approach was agreed with our accessibility champs (@kolaps33, @jurokapsiar & @smhigley).
