### ISSUE TITLE
[Bug]: optionToText for useComboBoxFilter doesn't work in a `Controlled` Combobox 

### ISSUE THREAD

**Issue by sydsutton** [microsoft/fluentui#30355]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 11.36 GB / 31.95 GB
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/interesting-bird-qqmp8m?file=%2Fsrc%2Fexample.tsx

## Actual Behavior
When using `optionToText` in `useComboboxFilter` in an uncontrolled component (not using `useState` to control the combobox's selected options), `optionToText` changes the options' text in the `listbox` appropriately (ie- `optionToText: (o) => { return "Animal: " + o.value }` will change each option to show as `Animal: {animal name}`). When using `useState` to control selected options, `optionToText` does not change each options' text.
![image](https://github.com/microsoft/fluentui/assets/83406605/09018472-82d3-4a27-85a3-b6910eaeb927)

## Expected Behavior
`optionToText` should change each option's text regardless of it the component is controlled or not.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@sydsutton I don't a problem with a component there. As I see you're mixing there `value` (state of an input) and `selectedOptions` (selection state).

You have following:

```tsx
      <Combobox
        value={query ? query : selected.join("")}
        selectedOptions={selected}
        onChange={(ev) => setQuery(ev.target.value)}
        onOptionSelect={(_, o) => {
          setSelected(o.selectedOptions);
          setQuery("");
        }}
```

`Combobox.value` is `selected.join()`, however `selected` is basically an array of selected _values_  (`selectedOptions`), i.e. in your case it could be `["Alligator"]`, `["Bee"]`, etc.

_Why?_ Because it's what defined in `options`:

```ts
  { children: "Alligator", value: "Alligator" /* 👈 */ },
  { children: "Bee", value: "Bee" /* 👈 */ },
```

As you're not using `multiselect`, then you can do in your code to achieve the expected result:

```diff
        onOptionSelect={(_, o) => {
          setSelected(o.selectedOptions);
-         setQuery("");
+         setQuery(o.optionText ?? '');
        }}
```
