### ISSUE TITLE
[Bug]: Spinner Component Not Functioning in Documentation and CodeSandbox

### ISSUE THREAD

**Issue by buzzo123** [microsoft/fluentui#30353]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
-
```

### Are you reporting Accessibility issue?

None

### Reproduction

The spinner component in the documentation is not functioning as expected, it doesn't spin. This issue is also replicated in the provided CodeSandbox.

### Bug Description

**Bug Summary:**
The spinner component in the documentation is not functioning as expected, it doesn't spin. This issue is also replicated in the provided CodeSandbox.

**Steps to Reproduce:**
1. Navigate to the documentation page containing the spinner component.
2. Observe that the spinner doesn't spin.
3. Access the provided CodeSandbox link.
4. Observe that the spinner doesn't spin.

**Expected Behavior:**
The spinner component should display and function properly both in the documentation and the associated CodeSandbox.

**Additional Information:**
- Browser/Environment: Google Chrome
- Documentation Page URL: https://react.fluentui.dev/?path=/docs/components-spinner--default
- CodeSandbox Link: https://codesandbox.io/p/sandbox/musing-drake-hvq6fn

**Note:**
This issue report is based on the user's experience, and further investigation may be required to identify the root cause of the problem.

### Logs

```shell
-
```

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by marcosmoura** [comment]
@buzzo123 We've tested in multiple browsers and for both links you sent, the Spinner works as it should. Could you provide more information about the environment you are running in?
Please run this command in your Terminal application and post here the results:
```shell 
npx envinfo --system --npmPackages '{@fluent/*}' --browsers
```

**Comment by buzzo123** [comment]
@marcosmoura Here are the details from the command you requested:

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 2.19 GB / 15.25 GB
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.19041.3636
```

I've tested in multiple browser too but the result is static:

![image](https://github.com/microsoft/fluentui/assets/2952183/5db5c35d-9c91-434b-8565-fb3f439ad238)

**Comment by buzzo123** [comment]
> @buzzo123 There is one scenario when the Spinner will not work, which is when the OS has disabled or reduced animations. Could you make one more check, please? `Start` > `Settings` > `Ease of Access` > `Display` > toggle `Show animations` in Windows.
> 
> Does that fix the problem?

Yes this fix the problem! Thanks!

Question: this kind of animation is different from the animations implemented in fluent 8?
Because in fluent 8 I didn't encounter in this problem.

Thanks  for the help!

**Comment by layershifter** [comment]
> Question: this kind of animation is different from the animations implemented in fluent 8?
> Because in fluent 8 I didn't encounter in this problem.

@buzzo123 it's not a bug. v9 is more focused on accessibility, so we respect OS settings for motion. That's why in your case animations have been disabled 🐱
