### ISSUE TITLE
[Bug]: DataGrid resizing columns is not possible when overflowX is enabled

### ISSUE THREAD

**Issue by savkelita** [microsoft/fluentui#30379]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 13.71 GB / 31.78 GB
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (120.0.2210.144)
    Internet Explorer: 11.0.19041.3570
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/romantic-bardeen-rr4h28?file=%2Fsrc%2FApp.tsx%3A16%2C20

## Actual Behavior
![chrome-capture-2024-1-24](https://github.com/microsoft/fluentui/assets/7733834/85368416-d093-4640-8bc8-801eb20a6aab)

## Expected Behavior
DetailsList Component FluentUI v8:
![chrome-capture-2024-1-24 (2)](https://github.com/microsoft/fluentui/assets/7733834/48e26fdc-cb0e-4a0e-a1fa-f446596eab81)

I think this is important to be fixed because content inside cell is not readable.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Prommerbua** [comment]
Any update/workaround on this? Having the same problem.
