### ISSUE TITLE
[Feature]: New lint rule to test event callback type and deprecate/migrate conformance test consistent-callback-args

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/fluentui#30372]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

This is an issue to gather all necessary steps to add testing for new event type.

A new type for event callback is proposed in - https://github.com/microsoft/fluentui/blob/master/rfcs/react-components/convergence/event-handlers-event-type.md

We need to:
1. deprecate existing consistent-callback-args test #30301
2. add lint rule for new type #30293
3. update existing consistent-callback-args test to make sure it doesn't run for new callbacks added to existing component #30376

### Have you discussed this feature with our team

Yes

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by Hotell** [comment]
1. can we improve the issue title? it's bit confusing IMO what's the feature request

2. regarding `consistent-callback-args` conformance test:

copy paste from PR for better visibility (https://github.com/microsoft/fluentui/pull/30376#pullrequestreview-1841565830) 

This rule is the last rule that needs to create TS program when running these conformance test which is extremely slow https://github.com/microsoft/fluentui/issues/27359.

The end goal of conformance tests is to have all of those rules ported to ESlint.

**Aim of this issues should be:**
- migrate logic of this conformance test to our workspace lint rules
- remove this rule from conformance package

this has 2 major benefits:

- performance of tests
- improved DX in comparison with current approach. lint rule can be then enabled directly in source code for problematic callbacks, for fine grained control and getting rid of unnecessary decoupling of concerns
