### ISSUE TITLE
[Bug]: Sticky hover effect on mobile

### ISSUE THREAD

**Issue by daniharo** [microsoft/fluentui#30388]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 63.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Safari: 17.2.1
    
NPM packages:
"@fluentui/react-components": "^9.45.0"
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/sandbox/fluent-sticky-hover-cxcx89

## Actual Behavior
In Safari mobile or Chromium mobile, after touching a button, it remains being shown in the "hover" styles. 

<img width="371" alt="image" src="https://github.com/microsoft/fluentui/assets/47931084/8a0bbd6d-7477-4fc0-94d1-5741bee85386">

[Edit @behowell] This also repros on Edge on Windows when using touch.

## Expected Behavior
In mobile browsers, :hover styles should be disabled for all components. There's no obvious way to do this for Fluent v9 components right now.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment]
Hi @daniharo 👋🏻 

Unfortunately, after investigating it and a short discussions we had, the problem reported can't be fixed right now. It requires proper investigation and a lot of changes on our side. I created a [feature request](https://github.com/microsoft/fluentui/issues/31858), so we won't lost it 

Thank you for reporting an issue 🫶
