### ISSUE TITLE
[Bug]: Menu refocuses even after it leaves the viewport

### ISSUE THREAD

**Issue by mltseng** [microsoft/fluentui#30417]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/aged-feather-4jfyjl

### Bug Description
The `Menu` component is refocusing onto itself after a user navigates to a second `Menu`, even if the first `Menu` is out of view. While the first `Menu` is in the viewport, I would like to allow the user to scroll the page without it closing, so I don't want to use the `closeOnScroll` prop.

1. Click on the first `Menu` to open it.
2. Scroll to bottom of the page. Ensure the first `Menu` is not in the viewport.
3. Hover over the second `Menu` to open it.
4. Move the mouse away from the second `Menu` to close it.
5. Observe the jump back to the first `Menu`

## Actual Behavior
The `Menu` forcibly refocuses onto itself.

## Expected Behavior
The `Menu` does not automatically regain focus.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
This is by design. Hover does not set focus, and in this case the focus restoration will restore focus to the last focused element. You can simply add a mouseenter listener to focus the trigger and solve your problem. https://stackblitz.com/edit/6ttf96?file=src%2Fexample.tsx

**Comment by jamespero** [comment]
It appears the production steps are missing a step just before the hover step:

After activating the first menu button, click outside to close the menu (this should remove focus), then perform the hover on the next Menu button.

Clicking outside the first button it would be expected that button should lose focus.
