### ISSUE TITLE
[Bug]: Window size cuts off fluent v9 menu component when window is small

### ISSUE THREAD

**Issue by foodprison2020** [microsoft/fluentui#30419]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 45.44 GB / 63.95 GB
  Browsers:
    Edge: Chromium (120.0.2210.121)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/sweet-lewin-pxhzk5?file=%2Fsrc%2FApp.tsx

## Actual Behavior
When the menu no longer fits in the window, it is cut off by the window.  This can be a problem when the menu is placed at the top of the browser window. This can happen from the bottom or top.

This can be demonstrated in any of the menu examples listed at the following site:
https://react.fluentui.dev/?path=/docs/components-menu-menu--default#nested-submenus-controlled
![image](https://github.com/microsoft/fluentui/assets/66027892/fe473a0a-012d-41f2-a089-711d576cc415)

Even if I try to add a scrollbar to handle an overflow-y attribute, the menu is still cut off as the min and max height of the menu never changes when the size of the host window changes. In the following picture the bug is cut off at the top.
![image](https://github.com/microsoft/fluentui/assets/66027892/dfc77168-c433-463a-9b9b-d2461933ada1)

## Expected Behavior
The menu should handle the case where the menu might get cut off by the browser window size. One solution could be a scrollbar. 

### Requested priority

Normal

### Products/sites affected

Outlook Web Access

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by YuanboXue-Amber** [comment]
Hi, the menu will have scrollbar in small viewport with prop `positioning={{autoSize: true}}`.
https://stackblitz.com/edit/evhupd?file=src%2Fexample.tsx
<img width="1209" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/fb609f7f-a084-439d-9126-b9409e713619">


I'm working on adding a story for autoSize in [our docs for `positioning` prop](https://react.fluentui.dev/?path=/docs/concepts-developer-positioning-components--default).
