### ISSUE TITLE
[Feature]: CalenderCompat v9 added capabilities

### ISSUE THREAD

**Issue by gouttierre** [microsoft/fluentui#30426]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

**Background** 
A partner team is not doing any v9 work this semester due to resources constraints and there are two features that aren't/may not be in the `compat component`, but they seem like `easy` adds to use the `compat calendar` when they get to that point.

**Enhancements to [#26646](https://github.com/microsoft/fluentui/issues/26646)** 

1. Ability to make the selected days accessible by adding a border to the selection. 

### Have you discussed this feature with our team

React PM

### Additional context

Stephanie from design has the context.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by gouttierre** [comment]
📢 
- Stephanie had conversations with Esteban on the request. The design spec needs to be done/ completed. Stephanie and Toshie will have it ready `mid-Feb 2024`. cc @tudorpopams

**Comment by stapple3** [comment]
Adding screenshots of the design spec. Please reach out if you'd like the Figma dev mode link to the spec.



![Image](https://github.com/microsoft/fluentui/assets/126008470/97b76078-89e2-4704-a197-47993aacb127)

![Image](https://github.com/microsoft/fluentui/assets/126008470/752b447f-5aec-4779-9ebd-1d58f2578468)

![Image](https://github.com/microsoft/fluentui/assets/126008470/6bb629b3-ac01-4986-a3d7-ba440b2a4400)

**Comment by gouttierre** [comment]
📢 
- EM's to assign a developer in the next sprint. The spec is completed and done from design (Stephanie).  cc @tudorpopams , @JustSlone

**Comment by gouttierre** [comment]
📢 
- Feature implementation is done by engineering.
- However, there is a [[Bug]: Focus indicator gets cut off in CalendarCompat component · Issue #31551 · microsoft/fluentui (github.com)](https://github.com/microsoft/fluentui/issues/31551) that will be addressed before closing out this request.

cc @ValentinaKozlova , @tudorpopams , @stapple3

**Comment by gouttierre** [comment]
📢
- This feature request is completed by the team. 

cc @tudorpopams , @ValentinaKozlova , @stapple3
