### ISSUE TITLE
[Bug]: Dropdown v9 has no support for custom data 

### ISSUE THREAD

**Issue by Weffe** [microsoft/fluentui#30430]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

n/a

### Bug Description

In Fluent 8, [Dropdown options](https://github.com/microsoft/fluentui/blob/a2c784f4a2990f056b7146543d8b06bf2cff408b/packages/react/src/utilities/selectableOption/SelectableOption.types.ts#L56) exposed a prop called `data` that you can pass to it custom data of your choice and Fluent 8 will pass said data along to the `onChange` handler which you can use as needed.

In Fluent 9, there is no way to do this or at least no documented way. Take the following as an example.

Fluent 8:

```
const products = [
 { id: 'uuid', name: 'apple', category: 'fruit', color: 'red' },
 { id: 'uuid', name: 'banana', category: 'fruit', color: 'yellow' },
 { id: 'uuid', name: 'onion', category: 'vegetable', color: 'white' }
];

const options: IDropdownOption = products.map(product => ({ text: product.name, data: product }));

const onChange = (_event, option) => {
  if (option) {
    const color = option.data.color;
    console.log(color);
  }
}

<Dropdown options={options} onChange={onChange} /> 
```

Fluent 9:

```

const products = [
 { id: 'uuid', name: 'apple', category: 'fruit', color: 'red' },
 { id: 'uuid', name: 'banana', category: 'fruit', color: 'yellow' },
 { id: 'uuid', name: 'onion', category: 'vegetable', color: 'white' }
];

const options = products.map(product => ({ text: product.name, data: product }));

const onOptionSelect= (_event, optionData) => {
  const color = optionData.??? // there is no `data` property here

  // ugly hack is to look up the product object by the name...
  const product = products.find(product => product.name === optionData.optionText);

  if (product) {
    const color = product.color;
    console.log(color);
  }
}

<Dropdown onOptionSelect={onOptionSelect}> 
  {products.map((product) => (
    <Option key={product.id} data={product}>{product.name}</Option>
  ))}
</Dropdown>
```

Is there any hesitations to add back support for `data` or some form of support for complex data on a dropdown option? What is the guidance around this in the meantime?

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ValentinaKozlova** [comment]
I see in Dropdown V9 API usage of `data` in `onOptionSelect` and `onOpenChange` methods. Maybe it's what you need. cc: @smhigley

**Comment by behowell** [comment]
The `Option` component has a `value` prop, which you can use as a unique identifier for that option to look up in your data structure. The selected item's value is passed to Dropdown's `onOptionSelect` as `data.optionValue`.

For example, if your data is:
```
const products = [
 { id: 'uuid', name: 'apple', category: 'fruit', color: 'red' },
 { id: 'uuid', name: 'banana', category: 'fruit', color: 'yellow' },
 { id: 'uuid', name: 'onion', category: 'vegetable', color: 'white' }
];
```

Then you can set each Option's `key` to the `id`, and then look up the selected product based on the id.

Here's an example: https://stackblitz.com/edit/fluentui-starters-w36kty-iueanp?file=src%2FExample.tsx

That should allow you to look up the data without needing a separate `data` prop on the Option.

**Comment by Weffe** [comment]
I know it's late coming back to this but a reverse lookup isn't as nice as just passing a reference to a complex object as the custom "data" that's propagated to handlers for onClick. Especially if I need to build the reverse lookup map for something like this.

Supporting a custom data object that is drilled through could alleviate open issues like #30571
