### ISSUE TITLE
[Bug]: DataGrid resizable columns do not resize under StrictMode

### ISSUE THREAD

**Issue by riverar** [microsoft/fluentui#30450]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.26040
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 99.21 GB / 127.12 GB
  Browsers:
    Edge: Chromium (122.0.2365.3)
    Internet Explorer: 11.0.26040.1000
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/riverar/repro-7cf24c764b61

1. Clone repository
2. `npm install`
3. `npm start`
4. Resize viewport width, observe columns do not shrink
5. Stop debugging/serving up the site
6. Open `index.tsx` and remove `<StrictMode>` / `</StrictMode>` nodes. Also remove the `import { StrictMode } from 'react';` to satisfy the linter.
7. `npm start`
8. Resize viewport width, observe columns shrink as expected

## Actual Behavior
DataGrid columns do not resize when the viewport width shrinks/expands, under StrictMode

## Expected Behavior
DataGrid columns resize consistently with StrictMode on or off.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by george-cz** [comment]
Hello @riverar, this seems to be a bug in React's StrictMode, as you can see in this example here:

https://stackblitz.com/edit/vitejs-vite-jtl3eh?file=src%2Fmain.tsx

This uses useMeasureElement hook, which was taken from our codebase and listens on the container size change.
When you enable `<React.StrictMode>` in the main.tsx, you can see that the number stops updating.

I'll create a bug in React and see if this is something they can help us work around.

**Comment by riverar** [comment]
Thanks @george-cz feel free to ping me anytime if you need testing or have questions.
