### ISSUE TITLE
[Bug]: OverlayDrawer `defaultOpen` is not respected

### ISSUE THREAD

**Issue by Weffe** [microsoft/fluentui#30451]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 10.00 GB / 31.60 GB
  Browsers:
    Chrome: 121.0.6167.87
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/sandbox/nervous-booth-thrvnn?file=%2Fsrc%2Fexample.tsx%3A16%2C41

## Actual Behavior
When `defaultOpen` is set to true, the OverlayDrawer is NOT opened upon render.

## Expected Behavior
When `defaultOpen` is set to true, I expect the OverlayDrawerto be open upon render.

Looks like in [useDrawerDefaultProps](https://github.com/microsoft/fluentui/blob/27ca189bc2fde6aade956712c1f87845296981bd/packages/react-components/react-drawer/src/shared/useDrawerDefaultProps.ts#L3) is not setting `open` based on `defaultOpen`.

We should update that hook to look like:

```diff
export function useDrawerDefaultProps(props: DrawerBaseProps) {
-  const { open = false, size = 'small', position = 'start' } = props;
+  const { open = props.defaultOpen ?? false, size = 'small', position = 'start' } = props; 


  return {
    size,
    position,
    open,
  };
}
```

That would mean `InlineDrawer` would also need to be updated to include the `defaultOpen` prop too.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
`OverlayDrawer` can work only as a controlled component and does [not support uncontrolled mode](https://legacy.reactjs.org/docs/uncontrolled-components.html) i.e. `defaultOpen` prop.

It looks that we overlooked it before (#29274), this prop should be marked as deprecated and never used. Thx for reporting 👍
