### ISSUE TITLE
[Bug]: MessageBar bottom padding missing

### ISSUE THREAD

**Issue by alex-rantos** [microsoft/fluentui#30461]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
no_need
```

### Are you reporting Accessibility issue?

None

### Reproduction

Make a two line messageBar

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/22919198/879736c2-a049-4d5c-8872-b131a57e4c60)
## Expected Behavior
MessageBarBody text should have some padding on the bottom.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ValentinaKozlova** [comment]
@alex-rantos , you wrote it `React Northstar / v0 (@fluentui/react-northstar)` but screenshot is from V9
