### ISSUE TITLE
[Bug]: Unexpected "up" and "down" key behavior in bi-directional FocusZone 

### ISSUE THREAD

**Issue by maxpedersenmsft** [microsoft/fluentui#30462]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 993.26 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.3
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/focuszone#usage

## Actual Behavior
When navigating the top row of a bi-directional FocusZone, pressing the "up" arrow key navigates to the next element to the left, and when in the bottom row, pressing the "down" arrow key navigates to the next element to the right.

This is visible in the documentation under "Non-uniform photos within bidirectional FocusZone." Mouse click on the "F" tile in the second row, all the way to the right:

![Screenshot 2024-02-02 at 9 17 53 AM](https://github.com/microsoft/fluentui/assets/92552901/ca1d82b0-5df2-4f81-97a9-3f32ff837493)

Use the keyboard arrow keys to press up to get to the first row. Press it again, and it goes to the left. Keep pressing up and you end up all the way to the left. Then, press down, and you end up back at the right-most tile in the second row. 

## Expected Behavior
If there is no tile above the currently selected tile, I would expect pressing up to do nothing, not go to the left. Same with the down key in the last row; I would expect pressing down would do nothing.

In my scenario above, if there's a reason why pressing up goes left instead of doing nothing, once I've found myself all the way to the left in the first row after pressing up numerous times, I would at least expect pressing the down key to take me one tile down, not all the way back to the rightmost tile.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by tomi-msft** [comment]
Hello, thanks for submitting the issue @maxpedersenmsft . I went to the bidirectional `FocusZone` example in the docsite and was unable to repro this. Could you submit a codepen or steps to repro?
