### ISSUE TITLE
[Bug]: DataGrid columns do not resize to fit data

### ISSUE THREAD

**Issue by riverar** [microsoft/fluentui#30463]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.26040
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 99.21 GB / 127.12 GB
  Browsers:
    Edge: Chromium (122.0.2365.3)
    Internet Explorer: 11.0.26040.1000
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/riverar/repro-6badcbf612.git

## Actual Behavior
With `resizableColumns=false`, DataGrid [reportedly](https://github.com/microsoft/fluentui/issues/29365#issuecomment-1745688174) resizes its columns to fit data contained within. Instead, it appears DataGrid adjusts its columns to have equal widths that add up to 100%.

Provided repro. creates two columns with varying data lengths and the columns appear to remain at 50% each **regardless of data passed in**. Screenshot below.
![image](https://github.com/microsoft/fluentui/assets/475132/2196b130-b158-43a5-a496-42f9b8d931f9)

## Expected Behavior
DataGrid should resize its columns to fit the data contained within. In this scenario, name would be expanded a bit more to accommodate the longer name, as value space is present.

Alternative it could use `columnSizeOptions` to hint at better column sizes?

Note: If `resizableColumns=true` is set, you lose all auto-fit capabilities and are stuck with static column widths, which is not ideal either.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
https://stackblitz.com/edit/stackblitz-starters-ewfmvn?file=src%2FExample.tsx,src%2FApp.tsx

**Comment by george-cz** [comment]
Hello, 

the `columnSizingOptions` is only used when resizable columns are enabled. When true, the internal state takes over the column widths, which is not what you want.

You can use table layout instead of flex layout by passing `noNativeElements={false}` prop to the DataGrid component and setting its css property `table-layout: auto`.

Please see the updated example here: https://stackblitz.com/edit/stackblitz-starters-545dji?file=src%2FExample.tsx

**Comment by rocketBANG** [comment]
@george-cz 
when I try that and enable selection with `selectionMode="single"` or `selectionMode="multiselect"`, I see the selection icons are not vertically aligned anymore, is that expected?

![image](https://github.com/microsoft/fluentui/assets/2422566/d0d8e4b9-5cfd-481b-8300-e9d02acd5578)

https://stackblitz.com/edit/stackblitz-starters-wxhjki?file=src%2FExample.tsx

**Comment by george-cz** [comment]
Hi @rocketBANG,

this is not expected, please file a bug based on this issue, we'll take a look at that.

In the meantime, you can work around this by adding a `vertical-align: middle` style to the selection cell, in the `selectionCell` slot of the `DataGridRow` component, like in this example here: https://stackblitz.com/edit/stackblitz-starters-b6wabf?file=src%2FExample.tsx
