### ISSUE TITLE
[Bug]: Wrong tokens used on ToggleButton

### ISSUE THREAD

**Issue by markuslindmark** [microsoft/fluentui#30476]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
v9.46.3
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-button-togglebutton--default#appearance

## Actual Behavior
Toggle button with subtle appearance, in selected mode the icon uses colorNeutralForeground2Selected

## Expected Behavior
As the figma design show the icon should use colorNeutralForeground2BrandSelected.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
This is not right, `ToggleButton` already uses `colorNeutralForeground2BrandSelected` for the icon when `checked` and `subtle`.

https://github.com/microsoft/fluentui/blob/0f9eada07c589f4eca36cffa1b0f356329943379/packages/react-components/react-button/src/components/ToggleButton/useToggleButtonStyles.styles.ts#L216

**Comment by markuslindmark** [comment]
It still uses the colorNeutralForeground2Selected in latest version though.
https://react.fluentui.dev/?path=/docs/components-button-togglebutton--default#appearance
