### ISSUE TITLE
[Bug]: Space key toggles popup

### ISSUE THREAD

**Issue by jke-r** [microsoft/fluentui#30487]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 3.37 GB / 15.88 GB
  Browsers:
    Chrome: 121.0.6167.140
    Edge: Chromium (121.0.2277.106)
    Internet Explorer: 11.0.19041.3636


  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 3.39 GB / 15.88 GB
  Browsers:
    Chrome: 121.0.6167.140
    Edge: Chromium (121.0.2277.106)
    Internet Explorer: 11.0.19041.3636
```

### Are you reporting Accessibility issue?

None

### Reproduction

See example in bug description

## Minimal code for reproduction

`import { SearchIcon, Input, List, Flex, Text, Popup } from "@fluentui/react-northstar";`

`<Flex column fill styles={{ height: "3.5rem" }}>
        <Popup position="below" on="click" content={<List styles={{width:"20em"}} />} trigger={<Input fluid icon={<SearchIcon />} placeholder={"Search..."} clearable />}  />
      </Flex>`

## Actual Behavior
When I enter a spacekey (space key) in the text field (=trigger), the popup automatically toggles (hides / shows). The spacekey is not provided to the text field. So I can not enter a spacekey to the input text field. We have build a search with this component, where the results are shown in the popup / list. The actual code is more sophisticated. We reduced it to pin point the error and found out that the behaviour is due to the popup component.  It is very unconvient that spacekeys are not supported at the moment.

## Expected Behavior
The popup shall not toggle when a space key is entered in the trigger (=text field).

## Additional Infos

We have already tracked down the code in the popup.tsx component that is responsibile for that behaviour. Unfortunately, we have no idea how to create a workaround. Can you support us with a workaround? Maybe we miss a configuration from the popup?

Code snipped from popup.tsx:

`const handleDocumentKeyDown = (getRefs: Function) => (e: KeyboardEvent) => {
    const keyCode = getCode(e);
    const isMatchingKey = keyCode === keyboardKey.Enter || keyCode === SpacebarKey;

    if (isMatchingKey && isOutsidePopupElementAndOutsideTriggerElement(getRefs(), e)) {
      trySetOpen(false, e);
    }

    // if focus was lost from Popup and moved to body, for e.g. when click on popup content
    // and ESC is pressed, the last opened Popup should get closed and the trigger should get focus
    const lastContentRef = getRefs().pop();
    const isLastOpenedPopup: boolean = lastContentRef && lastContentRef.current === popupContentRef.current;

    const activeDocument: HTMLDocument = context.target;
    const bodyHasFocus: boolean = activeDocument.activeElement === activeDocument.body;

    if (keyCode === keyboardKey.Escape && bodyHasFocus && isLastOpenedPopup) {
      close(e, () => _.invoke(triggerFocusableRef.current, 'focus'));
    }
  };`

The search field / input field is already in production. On of our users filed in the bug. It would be great if you can support us here. Thanks!

### Requested priority

Blocking

### Products/sites affected

yes

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
I do not think that it is a good idea how to implement the search. The preferred way would be to use `Dropdown` component.

If you really need to use the `Popover`, I would not set the `Input` as a trigger. You can set the `Input` as a `target` of the popup to position it but then use the `Popover` in controlled mode by passing `open` and `onOpenChange` props and decide when to open and close the popover.

If you still want to explore the way of having the `Input` as a trigger, then dive into [Accessibility behaviors](https://fluentsite.z22.web.core.windows.net/0.66.2/accessibility-behaviors).
The popover uses `popupBehavior` by default which adds several keyhandlers to its trigger. One of the actions is `toggle` which is invoked on space and enter - that action calls `preventDefault` on the event (that's why the space is swallowed) and closes the popup.
The workaround to not close the popover on space might be something like this:
```jsx
import * as React from 'react';
import { SearchIcon, Input, List, Flex, Text, Popup, popupBehavior } from '@fluentui/react-northstar';

const customPopupBehavior = props => {
  const customBehavior = popupBehavior(props);
  customBehavior.keyActions.trigger.toggle.keyCombinations = [{ keyCode: 13 }]; // This overwrites the default combinations which are 13 (Enter) and 32 (Space)
  return customBehavior;
};

const PopupExample = () => (
  <Flex column fill styles={{ height: '3.5rem' }}>
    <Popup
      position="below"
      on="click"
      accessibility={customPopupBehavior}
      content={<List styles={{ width: '20em' }} />}
      trigger={<Input fluid icon={<SearchIcon />} placeholder={'Search...'} clearable />}
    />
  </Flex>
);
```
**But once again, I would not recommend this path!**
