### ISSUE TITLE
[Bug]:Java Heap OOM errors when trying to execute playwright test invoking react component using React-Icons package v2.0.226

### ISSUE THREAD

**Issue by salujamanish** [microsoft/fluentui#30490]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 14.27 GB / 15.48 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/microsoftgraph/microsoft-graph-toolkit/tree/next/mgt-chat

## Actual Behavior
I'm having an issue and getting Java Heap OOM errors when I create new yarn based workspace in the project, install playwright and try to execute playwright test invoking component which references package react-icons version 2.0.226.
Observation:
If remove the reference of @fluentui/react-icons package from component test are executed successfully without OOM errors

To Reproduce
Create yarn based new workspace in the project.
yarn create react-app

Install playwright in the new workspace created.
yarn create playwright

Configure NODE_OPTIONS to 8GB memory
"test-ct": "NODE_OPTIONS=--max-old-space-size=8192 playwright test -c playwright-ct.config.ts"

create a simple test invoking chat component and execute the test
yarn test-ct Chattest.spec.tsx

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
1: 0xb85bc0 node::Abort() [/.nvm/versions/node/v18.18.2/bin/node]
2: 0xa94834 [/.nvm/versions/node/v18.18.2/bin/node]
3: 0xd66d10 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/.nvm/versions/node/v18.18.2/bin/node]
4: 0xd670b7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/.nvm/versions/node/v18.18.2/bin/node]
5: 0xf447c5 [/.nvm/versions/node/v18.18.2/bin/node]
6: 0xf56cad v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/.nvm/versions/node/v18.18.2/bin/node]
7: 0xf313ae v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) /.nvm/versions/node/v18.18.2/bin/node]
8: 0xf32777 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) /.nvm/versions/node/v18.18.2/bin/node]
9: 0xf1394a v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) /.nvm/versions/node/v18.18.2/bin/node]
10: 0x12d8caf v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) /.nvm/versions/node/v18.18.2/bin/node]
11: 0x1705b39 /.nvm/versions/node/v18.18.2/bin/node]

Remove the reference of @fluentui/react-icons package from mgt-chat and rerun the test
yarn test-ct Chattest.spec.tsx
Running 2 tests using 2 workers

vite v4.5.1 building for production...
✓ 2210 modules transformed.
[plugin:vite:reporter]
(!) /microsoft-graph-toolkit/packages/mgt-components/dist/es6/components/mgt-person-card/mgt-person-card.js is dynamically imported by / microsoft-graph-toolkit/packages/mgt-components/dist/es6/components/mgt-person/mgt-person.js but also statically imported by /microsoft-graph-toolkit/packages/mgt-components/dist/es6/components/components.js, dynamic import will not move module into another chunk.

playwright/.cache/playwright/index.html 0.33 kB │ gzip: 0.24 kB
playwright/.cache/assets/index-961ceb41.js 148.91 kB │ gzip: 47.41 kB │ map: 415.80 kB
playwright/.cache/assets/ChatListItem-ba7d8537.js 15,400.04 kB │ gzip: 3,049.81 kB │ map: 21,913.53 kB
2 passed (1.6m)

## Expected Behavior
Expect the test written to be executed successfully

### Logs

```shell
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
1: 0xb85bc0 node::Abort() [/.nvm/versions/node/v18.18.2/bin/node]
2: 0xa94834 [/.nvm/versions/node/v18.18.2/bin/node]
3: 0xd66d10 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/.nvm/versions/node/v18.18.2/bin/node]
4: 0xd670b7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/.nvm/versions/node/v18.18.2/bin/node]
5: 0xf447c5 [/.nvm/versions/node/v18.18.2/bin/node]
6: 0xf56cad v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/.nvm/versions/node/v18.18.2/bin/node]
7: 0xf313ae v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) /.nvm/versions/node/v18.18.2/bin/node]
8: 0xf32777 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) /.nvm/versions/node/v18.18.2/bin/node]
9: 0xf1394a v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) /.nvm/versions/node/v18.18.2/bin/node]
10: 0x12d8caf v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) /.nvm/versions/node/v18.18.2/bin/node]
11: 0x1705b39 /.nvm/versions/node/v18.18.2/bin/node]
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@salujamanish please provide reproduction steps as I cloned branch, but it's obviously not enough. I suggest to run `yarn dedupe` and check again.

**Comment by Hotell** [comment]
as @layershifter mentioned, please provide isolated reproduction where we can see the issue ( you can use stackblitz for example ).

regarding react-icons we had multiple perf issues in various codebases because duplicates in node_modules, try checking for these dupes. see https://github.com/microsoft/fluentui/issues/31714#issuecomment-2192050491
