### ISSUE TITLE
[Bug]: TimePicker resets when `startHour` and `endHour` is set

### ISSUE THREAD

**Issue by kamilkazmierczakMtab** [microsoft/fluentui#30496]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 13.6.2
    CPU: (10) arm64 Apple M2 Pro
    Memory: 2.05 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 120.1.61.120
    Safari: 17.1.2
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/blissful-kare-6c8nmj

## Reproduction steps
Select any time from TimePicker and select `Set start hour to 8` button

## Actual Behavior
After updating `startHour` or `endHour` current value in input is cleared (although selected value is still there - combobox list still has it selected)

## Expected Behavior
Input value **is not** cleared after updating `startHour` or `endHour`

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
@kamilkazmierczakMtab thanks for reporting the issue. I cannot open the linked codesandbox. Could you please verify it still exists and is public?

**Comment by YuanboXue-Amber** [comment]
@kamilkazmierczakMtab it still shows sandbox not found, maybe it is set to private sandbox? You can also create repro with stackblitz from here: 
<img width="866" alt="image" src="https://github.com/user-attachments/assets/a4f9a1e3-5e5b-4e9b-826d-1b8e2c4a27f2">
