### ISSUE TITLE
[Feature]: Dialog - add checkbox example in Storybook

### ISSUE THREAD

**Issue by toshie-rashtavie** [microsoft/fluentui#30507]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

We'd like to add a checkbox example in the Storybook to show partners that this example is possible and how it should look from a Fluent perspective. For certain complex actions, CELA requires explicit acknowledgement to confirm that the user has reviewed the message. Will definitely be available for design support! :) 

Expected behaviour: 

<img width="615" alt="image" src="https://github.com/microsoft/fluentui/assets/107895541/d3caa281-5013-4364-ad12-b56dbe8686dd">

1. Primary button is disabled when checkbox is not checked
2. once checked, primary button becomes enabled and user needs to click on primary button to complete action 

This example to be added to the "With form" section in the Storybook

### Have you discussed this feature with our team

@bsunderhus

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by AntoniaBlume** [comment]
While you are in here making changes... I'd like to request small text fixes to several of the dialog buttons and dialog titles that are shown in Storybook as examples. All button and title text should be sentence cased, that is, only the first word is capitalized. So, e.g. "Do Something" and "Third Action" should say "Do something" and "Third action"; "Dialog Title" should be "Dialog title" etc. Thank you!

**Comment by AntoniaBlume** [comment]
And for the new dialog requested above, can you please revise the dialog title and body copy to the following? There are several corrections to ensure this follows our best practices for the content. Thanks!
title: Delete this campaign?
body: You're about to delete the campaign group "Campaign name that goes up to two lines". This will also delete all associated campaign resources, including the overview page, files, publications, conversations, and so forth. Please back up any content you need before proceeding.
