### ISSUE TITLE
[Bug]: A11y is not correct for text lumination ratio, do not meet minimum contrast ratio with the surrounding text.

### ISSUE THREAD

**Issue by qixiaojian310** [microsoft/fluentui#30500]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (8) x64 Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz
    Memory: 16.53 GB / 31.68 GB
  Browsers:
    Edge: Chromium (121.0.2277.110)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

No need for reproduction

## Actual Behavior
In docs the color of link is #115ea3
![image](https://github.com/microsoft/fluentui/assets/62613977/5f4fd720-588b-4a78-8025-00becd84236f)
The color of ordinary text is #242424
![image](https://github.com/microsoft/fluentui/assets/62613977/25771317-445b-4077-bd33-9520f8e54cde)
but the luminosity ratio is 2.33.
![image](https://github.com/microsoft/fluentui/assets/62613977/19605a02-7863-46fb-8a7e-19d6057acc8f)

Accessibility Insights for Web need 3:1 for a text

## Expected Behavior
fill this out

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
The purpose of `colorBrandForegroundLink` is not to be used as a background for text, but to be used as a foreground of a link text on a background, for example `colorNeutralBackground1` which is white in the light theme which you are referring to.
