### ISSUE TITLE
[Feature]: Show two month view in Calendar and allow date range selection

### ISSUE THREAD

**Issue by mokshpyla** [microsoft/fluentui#30511]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### Describe the feature that you would like added

The ability to pick a start date and end date as seen in below screenshot:
![image](https://github.com/microsoft/fluentui/assets/133318989/dff8e6c6-9eb9-4cf7-a4df-df74d2a36194)

### Additional context

I believe this issue is in the same lines: https://github.com/microsoft/fluentui/issues/28479

But requesting two month view as well 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by miroslavstastny** [comment]
You are referring to Fluent UI react-northstar (v0) which is legacy version with no new features. Is that intentional or are you talking about Fluent UI v9, as the linked issue?

**Comment by mokshpyla** [comment]
@miroslavstastny Apologies. If the legacy version will no longer have new features, then I would be requesting the desired behavior in Fluent UI v9. The capability to show two months and date range selection
