### ISSUE TITLE
v9 font size is fixed instead of relative

### ISSUE THREAD

**Issue by Erikvv** [microsoft/fluentui#30532]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

Yes

### Reproduction

https://codesandbox.io/p/sandbox/romantic-cache-5gscm6

## Actual Behavior

The `FluentProvider` sets `font-size: var(--fontSizeBase300);` which is [14px by default](https://github.com/microsoft/fluentui/blame/1e10b26c2d07f57cba4e90d34cd02e00c0b12f97/packages/tokens/src/global/fonts.ts#L6).

Doing it like this overrides the font size set by the user in the OS or browser (or by the developer on the root element). The user might have increased the font size for legibility/accessibility.

## Expected Behavior

Respect user setting of font size. For example by setting it to 1rem.

If there is a reason to not respect the absolute size then at least have it scale relative to the users preference. For example by using `0.875rem` instead of `14px`. 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
As of now, Fluent UI v9 does not support scaling based on browser font size. This is not only about the font size being set to 14px, but mainly about pixels being used for all the other dimensions in styles for Fluent UI v9.
The preferred way to size the Fluent UI v9 based application is by using browser zoom.

**Comment by miroslavstastny** [comment]
Closing for now, cc @gouttierre for the feedback.

**Comment by mnhlt** [comment]
How could this decision be made for v9?
the invent of "rem" does not mean anything?
even use fix pixel values, at least give us a way to calculate relative size between components base on base value to respect UI principles.
