### ISSUE TITLE
[Bug]: DatePicker closes prematurely after using keyboarding shortcuts

### ISSUE THREAD

**Issue by claudiuciumedean** [microsoft/fluentui#30556]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-calendar-compat - "0.0.9"
```

### Are you reporting Accessibility issue?

no

### Reproduction

See bug description

### Bug Description

We are experiencing a bug with the calendar control.

- Open date picker
- Focus the days of the month
- Press "pg up" or "pg dn" on the keyboard
- Note: The month changes, focus is no longer visible
- Press "up" or "down" arrow on the keyboard

## Actual Behavior
The page scrolls and the date picker closes

## Expected Behavior
The selected date moves

See repro here [Compat Components / DatePicker - Default ⋅ Storybook (fluentui.dev)](https://react.fluentui.dev/?path=/docs/compat-components-datepicker--default#week-numbers)

### Requested priority

Normal

### Products/sites affected

Microsoft Dynamics 365 Business Central

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
I am not able to repro the exact issue, but I see that hitting Page Up in the date picker popover multiple times eventually moves the focus to body. We should investigate.

**Comment by ValentinaKozlova** [comment]
Hey @claudiuciumedean, could you please give more details on this issue? I'm not able to reproduce it

**Comment by ValentinaKozlova** [comment]
This fix should resolve it https://github.com/microsoft/tabster/pull/393

**Comment by ValentinaKozlova** [comment]
Issue is fixed
