### ISSUE TITLE
[Bug]: Vertical scrollbar appears occasionally when Spinner is the only element in an `overflow: auto` container

### ISSUE THREAD

**Issue by wfwf1997** [microsoft/fluentui#30610]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 20.60 GB / 31.21 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
```

Browser: Edge 121.0.2277.128
Reduce motion: false
window.devicePixelRatio: 1.25

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/sandbox/adoring-feather-mcj59v

## Actual Behavior
The container sometimes overflow. The vertical scrollbar appears occasionally.

## Expected Behavior
The container will not overflow.

### Requested priority

Normal

### Products/sites affected

SharePoint

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@wfwf1997 thanks for the bug report! I've added a PR (linked above). If you need a quick fix before then, you should be able to use the same approach in that PR and add an `overflow: hidden` style to the spinner slot of the Spinner component.
