### ISSUE TITLE
[Bug]: Keyboard focus is moving out of the modal popup

### ISSUE THREAD

**Issue by joesrinadh** [microsoft/fluentui#30622]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 2.58 GB / 15.69 GB
  Browsers:
    Edge: Chromium (121.0.2277.128)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

Yes

### Reproduction

https://codesandbox.io/p/devbox/5mpk6w?file=%2Fsrc%2FModalBasicExample.tsx%3A12%2C14

### Bug Description

Keyboard focus is moving out of the modal popup when we use it as a webpart in share point.
Same component is working as expected when we use it as a component in react.

Here are the package versions
"@fluentui/react": "~8.11.2",
"react": "16.8.5",
"react-dom": "16.8.5",

## Actual Behavior
Keyboard focus is moving out of the modal popup

## Expected Behavior
Keyboard focus should stay within the modal popup

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
@joesrinadh I am not able to repro in the codesandbox but if I understand the report correctly this is expected as it only repros in the sharepoint? Any chance we can get a repro to debug?
@khmakoto any idea?
