### ISSUE TITLE
[Feature]: <TooltipHost/> instead of title for DatePicker customDayCellRef

### ISSUE THREAD

**Issue by simonenkoav** [microsoft/fluentui#30649]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

There is possibility to add custom tittle to dayCell in fluent v8 DatePicker, but tittle works poorly and not enough for some cases. It would be great to support amazing fluent <TooltipHost/> instead. If v8 is not developed anymore then support in v9 would be also great (v9 DatePicker does not support tittle at all as far as I got, that blocks our component migration to v9).

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by miroslavstastny** [comment]
@simonenkoav Thanks for the report. Could you please explain more on what functionality you are missing? I would not expect any changes to v8, but we might consider that in v9.

**Comment by simonenkoav** [comment]
We want to show additional info about day on hover. Currently for v8/DatePicker we use title for that (screenshot 1). But would like to move from title to `<TooltipHost/>` (like one we use for another component on the screenshot 2).
<img width="270" alt="Screenshot 2024-02-29 at 18 07 07" src="https://github.com/microsoft/fluentui/assets/22726232/0fe72220-52ff-4d7a-a1b5-21376537124b">
<img width="310" alt="Screenshot 2024-02-29 at 18 08 45" src="https://github.com/microsoft/fluentui/assets/22726232/a8e81ae5-aed7-4d32-aba5-3f989ffd93c7">

**Comment by gouttierre** [comment]
@simonenkoav - I appreciate your feedback. Showing the information on hover with a tooltip is a possible option. However, the Fluent design guidelines advise against hiding too much information in a tooltip. Our Fluent design team is working on updating the guidelines to reflect this. We have higher Fluent core priorities to focus on right now, so we cannot work on this request. But if you want to contribute to this feature, you can submit a PR and we will review it.
