### ISSUE TITLE
[Bug]: bug bash feedback for @fluentui/react-rating-preview

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#30647]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

N/A

## General [prio: low]

Resolve TODOs in code and JSdoc, for example:

https://github.com/microsoft/fluentui/blob/d27ded5aae466199135de53d143cc9d88659770d/packages/react-components/react-rating-preview/src/components/RatingItem/RatingItem.tsx#L8-L10

### `itemLabel` [prio: low]

Typo in jsdoc "ra**tn**g"

https://github.com/microsoft/fluentui/blob/d27ded5aae466199135de53d143cc9d88659770d/packages/react-components/react-rating-preview/src/components/Rating/Rating.types.ts#L31

### `iconFilled` & `iconOutline` [prio: high]

IMO it's not a good idea to use `React.ReactElement` as input for these props as it will cause unnecessary updates, see `useRatingContextValues():itemLabel` below. The reason is the same, JSX elements as just objects that are not strictly equal:

```tsx
<div /> === <div /> // false
```

This will cause unnecessary updates of `RatingItem`s because of context propagation once a component that contains `Rating` is re-rendered.

The same is true for `RatingDisplay#icon`.

#### Proposed action

Update interface to use `React.ElementType`:

```diff
  /**
   * The icon to display when the rating value is greater than or equal to the item's value.
   */
- iconFilled?: React.ReactElement;
+ iconFilled?: React.ElementType;
  /**
   * The icon to display when the rating value is less than the item's value.
   */
- iconOutline?: React.ReactElement;
+ iconOutline?: React.ElementType;
```

Then usages will be:

```diff
-<Rating iconFilled={<CircleFilled />} iconOutline={<CircleRegular />} step={0.5} />
+<Rating iconFilled={CircleFilled} iconOutline={CircleRegular} step={0.5} />
```

As components are expected to be passed, they will have a stable reference.

### `name` [prio: low]

nit: `useId()` allows to pass a generated `id`:

```diff
-const generatedName = useId('rating-');
  const {
    color = 'neutral',
    iconFilled = defaultIconFilled,
    iconOutline = defaultIconOutline,
    max = 5,
-    name = generatedName,
+const name = useId('rating-', props.name);
```

### `itemLabel` [prio: high]

`itemLabel` is not included to `state` object and won't be passed to `useRatingContextValues()` & proper context.

### `itemLabel`

`itemLabel` is a prop of `Rating` component that can be defined as below:

```tsx
<Rating itemLabel={() => {}} />
```

In this case, it will be a new reference once a component that contains `Rating` is re-rendered.

#### Proposed action

> Note: `useEventCallback()` won't work as `itemLabel` called during a render.

It's tricky as we are limited in memoization tricks for this case.

### `hoveredValue` & `value` [prio: high]

This is a performance issue with invalid usage of context:

https://github.com/microsoft/fluentui/assets/14183168/ba5ff1d7-c3f9-4dbd-b1d0-d01f1a667ee0

`hoveredValue` & `value` will refresh often based on interactions and re-render all `RatingItem`s.

#### Proposed action

Similarly to `Accordion`, `Menu` & etc. `Rating` should use an approach with `useContextSelector()` to reduce re-renders on context updates.

## `Rating

I am not entirely follow the idea with `selectedIcon` & `unselectedIcon` + `halfValueInput` & `fullValueInput`. Why these should be separate slots?

## Spec [prio: mid]

It looks that the spec is outdated, please ensure that it's up to date.

### Logs

```shell
N/A
```

### Requested priority

Blocking

### Products/sites affected

N/A

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
@layershifter Regarding Context Selector: IMO it is overkill for this case. It could reduce the number of RatingItems that re-render when hovering, but RatingItem is a relatively simple component, and there is a small, fixed number of them (typically 5). Context selector has a big bundle size overhead (and probably perf overhead but I haven't measured that).

I just did a quick perf test using the React Dev Tools on Rating as it is now. I used React Dev Tools to measure the render time while moving the mouse onto the first star (so only the first one had a visual change). The RatingItem that changed is shown in green. It does render the rest of the RatingItems (blue - tooltip shows their stats), but the render time for those items that didn't change is negligible.

![graph of perf measurement of Rating render on hover](https://github.com/microsoft/fluentui/assets/48106640/55d27353-a35b-498d-8015-800ba0acfbf8)
