### ISSUE TITLE
Some charts are not rendering correctly in RTL

### ISSUE THREAD

**Issue by krkshitij** [microsoft/fluentui#30660]
### LTR 

![image](https://github.com/microsoft/fluentui/assets/110246001/7aa9037e-86f1-4c36-9068-bf8e91eee760)

### RTL

![image](https://github.com/microsoft/fluentui/assets/110246001/b9ee6279-a751-4bc3-9f87-7e392abf1566)

Notice that the order of axis ticks is being reversed from LTR to RTL, but this is not happening with the bars.

**Comment by AtishayMsft** [comment]
FYI @Shubhabrata08.

**Comment by krkshitij** [comment]
Reopening as this issue still exists with VerticalBarChart Date Axis

**Comment by AtishayMsft** [comment]
@Shubhabrata08 The same fix needs to be applied to VerticalBarChart as well

**Comment by Shubhabrata08** [comment]
Ok... Looking into it
