### ISSUE TITLE
[Bug]: When resizing a window with open dialog, the content modified through ref in content is discarded

### ISSUE THREAD

**Issue by hajekj** [microsoft/fluentui#30701]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.26058
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900 @ 2.50GHz
    Memory: 9.00 GB / 31.84 GB
  Browsers:
    Edge: Chromium (122.0.2365.52)
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/hajekj/pen/wvZaBzB

## Actual Behavior
1. Open the CodePen sample - https://codepen.io/hajekj/pen/wvZaBzB - in full screen
2. Resize the browser to a regular window, wait 5 seconds for multiple `test` values to appear
3. Resize to full screen
4. Content is dropped

## Expected Behavior
I expect the contents to stay unmodified.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by hajekj** [comment]
I also tried it with raw `Modal` where this issue doesn't happen - https://codepen.io/hajekj/pen/qBwdEpJ?editors=0010

**Comment by behowell** [comment]
Hi @hajekj, your example is using `appendChild` to modify the DOM of a react-controlled element, which is not allowed in React.  You need to add content using React elements instead of appending DOM nodes.
https://react.dev/learn/manipulating-the-dom-with-refs#best-practices-for-dom-manipulation-with-refs

**Comment by hajekj** [comment]
Hello @behowell, thank you for the response. I understand that this shouldn't be done, however - the same operation works perfectly fine when using `Modal` directly, the issue is just when using `Dialog`. My case unfortunately requires modifying the DOM, since I am rendering some dynamic `iframe` elements within the `Dialog` (now `Modal`), and keeping it within React would result in really complex solution. So that's just to add context why I am going this way.

The use of `Modal` is perfectly fine solution for me, but I think there are some shenanigans going on, on maximazing browser window with Dialog.
