### ISSUE TITLE
[Feature]: introduce motionSlot() and necessary types

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#30700]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

- Add `motionSlot()`
- Add necessary types
- Expose `motion` prop for components that have motion

### Have you discussed this feature with our team

See https://github.com/microsoft/fluentui/pull/29958

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by layershifter** [comment]
Blocked until `@fluentui/react-motions-preview` won't reach stable.

**Comment by miroslavstastny** [comment]
H2/2024
