### ISSUE TITLE
[Bug]: Toast action button color contrast

### ISSUE THREAD

**Issue by gouttierre** [microsoft/fluentui#30705]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://uifabric.visualstudio.com/iss/_workitems/edit/10218

## Actual Behavior
The current action button in toast is the transparent button variant set to the Brand Foreground link color. This brand foreground link color doesn't pass accessibility (3:1) against the primary text token in the Loop brand and possibly other brand colors. 

## Expected Behavior
The solution is to change the button from transparent button to default secondary button at the small size.
We also need to investigate all brand link colors against foreground 1 to make sure they pass 3:1.

![image](https://github.com/microsoft/fluentui/assets/78806055/b2c2c51d-e4b0-428d-a016-0b1a60bc3c47)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@tudorpopams Fyi on a new item for backlog review.

**Comment by tudorpopams** [comment]
@ling1726 I just assigned this to your team. Please include it in your next planning session.

**Comment by george-cz** [comment]
Hi @gouttierre,

the Toast itself doesn't really have any Action button. We are using a `Link` component in our docs as action button, but you can use anything you'd like, including a `Button` component.

Should this ticket be about updating the docs?

**Comment by miroslavstastny** [comment]
This is not `Toast` specific. The stories render `Link` component on the default background. The link foreground is specific to a brand ramp used. cc @redongreen
