### ISSUE TITLE
[Bug]: `swc-plugin-de-indent-template-literal` doesn't work with new swc

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#30718]
### Library

React Components / v9 (@fluentui/react-components)

### Are you reporting Accessibility issue?

no

### Reproduction

- checkout https://github.com/microsoft/fluentui/pull/30620
- undo this change https://github.com/microsoft/fluentui/pull/30620/files#diff-cb3a7716f2a1a7adc9150c301501028ff19ce406a665f16a440edf934b6381ca
- run build for react-utilities

## Actual Behavior

https://github.com/microsoft/fluentui/pull/30620/files#r1504727678
https://github.com/bsunderhus/swc-plugin-de-indent-template-literal/issues/1

## Expected Behavior

Plugins we use for core v9 should be maintained and work with swc.

If we feel that plugin is not worth investing I'd suggest to remove it from our build pipeline.

### Requested priority

High

### Products/sites affected

v9 core

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
@Hotell  can you confirm this issue? it should have been resolved by https://github.com/bsunderhus/swc-plugin-de-indent-template-literal/issues/1

**Comment by Hotell** [comment]
> @Hotell can you confirm this issue? it should have been resolved by [bsunderhus/swc-plugin-de-indent-template-literal#1](https://github.com/bsunderhus/swc-plugin-de-indent-template-literal/issues/1)

let's keep it closed for now, I'll double check once getting back to bumping for native ESM story. ty
