### ISSUE TITLE
[Bug]: @fluentui/web-components - web-components-v3 - css variable token resolutions (output) has changed

### ISSUE THREAD

**Issue by bearcat-msft** [microsoft/fluentui#30720]
### Library

Web Components (@fluentui/web-components)

### System Info

```shell
Silicon Mac M2

Tested in edge v 122.0.2365.59
and chrome v 122.0.6261.94
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ymc7yw?file=index.html&terminal=dev

## Actual Behavior
Version 3.0.0-beta.5 the css variable tokens resolve like this:

<img width="1454" alt="image" src="https://github.com/microsoft/fluentui/assets/90428651/8c4fb361-cd5d-481b-ae4e-000792fb14ec">

In version 3.0.0-beta.8 the css variable tokens resolve like this:

<img width="1590" alt="image" src="https://github.com/microsoft/fluentui/assets/90428651/0ce9a7bb-e75b-4e07-8d22-0bfade5b555e">

The effective difference is that applying the values in a css template literal may require different methods:

When running the built code of version beta.5 the css below compiles as `color: var(--colorNeutralForeground1)`:

```javascript
const styles = css`
.cssClassSelector {
    color: ${colorNeutralForeground1};
}
`
```

However, in version beta.8 I've found that the same code resolves differently and gives this output:  `color: --colorNeutraolForeground1` and does not include the var() call.

## question

Is this an intentional update / breaking change?

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
See #30002

**Comment by bearcat-msft** [comment]
thanks, closing this issue as it is the expected behavior.
