### ISSUE TITLE
[Bug]: GroupedList returning to the initalScrollPosition when scrolling down and unable to select last file

### ISSUE THREAD

**Issue by isaudagar** [microsoft/fluentui#30730]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Scrollable Pane returning to the initalScrollPosition when scrolling down and unable to select last file
This issue is reproducible with more than 65 file uploads.
contentContainer class causing issue.
```

### Are you reporting Accessibility issue?

yes

### Reproduction

[edit @behowell] A similar issue repros on the GroupedList documentation page: https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist

## Actual Behavior
Unable to select last file it is redirecting to top position. after unchecking position or overflow then able to scroll down and select last file .
![fluentUI](https://github.com/microsoft/fluentui/assets/142884096/26443b72-7d72-48dd-8fd2-1ad5c8a088f3)

## Expected Behavior
Should be scroll properly in scrollable pane. 

### Logs

```shell
.
```

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by YusakuNo1** [comment]
Steps to reproduce (with Azure subscription for Machine Learning):
1. open ml.azure.com
2. open notebooks tab
3. create a lot of files in file explorer, e.g. 100+
4. try to scroll and found the issue

When we disabled the `position` and `inset` in CSS class `contentContainer-398`, the scrolling works fine. Can someone help us what are these 2 fields for in the CSS class?

**Comment by behowell** [comment]
Triage: This is using GroupedList. It looks like something similar happens when trying to scroll the GroupedList on the documentation site: https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist. The scrollbar jumps back to the top when scrolling down.

**Comment by spmonahan** [comment]
I believe using `GroupedListV2` will resolve this issue. `GroupedListV2` is an API-compatible replacement for `GroupedList` that should be a drop-in replacement. That said, it does render different DOM and have different virtualization behavior (hence the "V2") so you should validate your application after upgraded.

[Here's an example of using it](https://codepen.io/seanms/pen/eYoJzmb).

**Comment by isaudagar** [comment]
Hi @spmonahan,
Could you please help me with some information. Which version introduce GroupedListV2?
We are using @fluentui/react version 8.58.0 and not able to import GroupedListV2.
GroupedList available in node_modules but there is no GroupedListV2.

**Comment by spmonahan** [comment]
@isaudagar 

[8.96.0](https://github.com/microsoft/fluentui/blob/master/packages/react/CHANGELOG.md#8960) is where `GroupedListV2` is introduced. There have been bug fixes and improvements since then with the most recent one landing in [8.112.1](https://github.com/microsoft/fluentui/blob/master/packages/react/CHANGELOG.md#81121).
