### ISSUE TITLE
[Feature]: Add a `Navbar` component 

### ISSUE THREAD

**Issue by rhalaly** [microsoft/fluentui#30746]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Add a `Navbar` component, like other UI libraries such as Bootstrap and Material UI.

https://react-bootstrap.netlify.app/docs/components/navbar/

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by behowell** [comment]
There is a `Nav` component in development. This is the issue tracking its progress: https://github.com/microsoft/fluentui/issues/26649

There is also already a `TabList` component, which is not the same but may work depending on what you need: https://react.fluentui.dev/?path=/docs/components-tablist--default
