### ISSUE TITLE
[Bug]: `List` requires explicit `data-is-scrollable` to be defined when rendered inside `Modal`

### ISSUE THREAD

**Issue by harunurhan** [microsoft/fluentui#30748]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 34.81 GB / 63.95 GB
  Browsers:
    Edge: Chromium (122.0.2365.80)
    Internet Explorer: 11.0.22621.1

"@fluentui/react": "8.115.5"
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/Harun-Urhan/pen/NWmxYpy

## Actual Behavior
Rendering a `<List>` with scrollable container (`overflow: auto`) inside a `<Modal>` doesn't work out of the box (without specifying `data-is-scrollable=true` for the parent)

This is because `Modal` renders a some inner `div` with `data-is-scrollabe=true`, which then takes over as the scrollable parent.

Normally fix is straight forward, just add `data-is-scrollable` to the actual scrollable container however we are migrating a large application with many usages of `List` (that doesn't have explicit `data-is-scrollable` definition); to now use `Modal` instead of our own modal implementation. Therefore most of our `List` will be broken as a result of this.

Since it's a very large application, it is not feasible to go for every place where we render `List` directly or indirectly and define `data-is-scrollable` explicitly.

## Expected Behavior
This works by default, or we need either

- A way to remove `data-is-scrollable` attributed from `Modal`
- A way to disable optimization for looking for `data-is-scrollable` element first [here](https://github.com/microsoft/fluentui/blob/6e6a1bf624e5a682b3607d918793d6f0eeb6b12a/packages/utilities/src/scroll.ts#L175) for the `List` component.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by F-Forget** [comment]
Thank you, @harunurhan, for identifying this bug. I am currently working on a project and find myself in a similar situation. What if it's simply not feasible to add the data-is-scrollable attribute explicitly?

The [findScrollableParent](https://github.com/microsoft/fluentui/blob/6e6a1bf624e5a682b3607d918793d6f0eeb6b12a/packages/utilities/src/scroll.ts#L175) function is an attempt to find the appropriate parent, but it's not flawless as it relies on heuristics.

What I propose is that instead of relying on guesswork (which is clever but might not always be accurate), there should be a way to specify (perhaps through a configuration prop in List) the scrollable parent. This would allow any complex application or project to take responsibility for finding the correct scrollable parent and pass it to the List component, ensuring the desired outcome.

**Comment by harunurhan** [comment]
Agreed that would be the most flexible way here, I have seen similar approach in `ant-design` before ([see AnchorProps.getContainer](https://ant.design/components/anchor#anchor-props)).

**Comment by spmonahan** [comment]
@harunurhan @F-Forget would either of you be willing to spin up a PR for this feature?

**Comment by harunurhan** [comment]
@spmonahan 

Not sure when I'll find time but before that happens

- What would the API look like? a prop `findScrollableContainer: (listElement: HtmlElement) => HtmlElement | Window` ?
- What about if somebody wants part of [findScrollableParent](https://github.com/microsoft/fluentui/blob/6e6a1bf624e5a682b3607d918793d6f0eeb6b12a/packages/utilities/src/scroll.ts#L175) but just not a lot of it. For example we may wanna use it but only with a different `DATA_IS_SCROLLABLE_ATTRIBUTE` or we may want to use [the part where it's looking at the computed styles](https://github.com/microsoft/fluentui/blob/6e6a1bf624e5a682b3607d918793d6f0eeb6b12a/packages/utilities/src/scroll.ts#L188C1-L201C4), I guess it is OK to expose these as utilities so that consumers can use them to compose their intended `findScrollableContainer` logic?
- Is this also an issue for v9? and does it need to be addressed as well?

**Comment by spmonahan** [comment]
Perhaps just expose a `findScrollableParent` prop that maintains the existing interface:

```ts
findScrollableParent: (startingElement: HTMLElement) => HTMLElement | Window | undefined | null
```

When this prop is not set we default to the existing implementation to maintain compatibility but users are free to provide their own implementation to suit their needs.

**Comment by harunurhan** [comment]
@spmonahan ok I'll give it a try when I have time unfortunately can't prioritize since we solved it internally.
