### ISSUE TITLE
[Bug]: TeachingPopover has no styling anymore and background is transparent

### ISSUE THREAD

**Issue by 15MariamS** [microsoft/fluentui#30756]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (14) arm64 Apple M3 Max
    Memory: 96.53 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.4
```

### Are you reporting Accessibility issue?

no

### Reproduction

(working on it)

## Actual Behavior
- The popover is transparent and has no styling anymore
- Adding custom styling does not work
- Updating `appearance` prop does nothing
<img width="459" alt="Screenshot 2024-03-11 at 7 58 47 AM" src="https://github.com/microsoft/fluentui/assets/81782111/82954565-c2b9-4aae-9fec-a575a3b20055">

## Expected Behavior
- Looks like in [docs](https://react.fluentui.dev/?path=/docs/preview-components-teachingpopover--default#default)
<img width="495" alt="Screenshot 2024-03-11 at 7 59 59 AM" src="https://github.com/microsoft/fluentui/assets/81782111/d3236d32-b732-4911-a8ed-2584adc39e06">

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
@15MariamS can you check if you're getting more than one version of `@fluentui/react-shared-contexts` in your lock file? If so, can you try deduplicating it and see if that fixes your issue?

**Comment by 15MariamS** [comment]
> @15MariamS can you check if you're getting more than one version of `@fluentui/react-shared-contexts` in your lock file? If so, can you try deduplicating it and see if that fixes your issue?

 yup, looks like I had both `9.14.1` and `9.15.0`. Thank you!
