### ISSUE TITLE
[Feature]: Scroll Bar support for Menu's based on Realestate

### ISSUE THREAD

**Issue by PoorviSrivastavaGit** [microsoft/fluentui#30764]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Currently the Menu in V9 do not have a scroll bar when unstable_disableTether prop is used. 
As a consequence, in small screen users are not able to see the entire menu.
Ask if to provide a scroll bar on basis of the RealEstate on the worksheet, if the work book has sufficient real estate when unstable_disableTether prop is used.

### Have you discussed this feature with our team

yes discussed with Lingfan @ling1726 

### Additional context

https://codesandbox.io/p/sandbox/intelligent-stitch-9hns3y?file=%2Fsrc%2Fexample.tsx

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by george-cz** [comment]
Hello, 

this already works, but you have to set a value of `position` property that results in an axis of `x`, like `after`. 

See my example here: https://stackblitz.com/edit/57jmmx?file=src%2Fexample.tsx

The limitation comes from the underlying library we use for positioning, Floating UI. The `size` middleware only auto-sizes X or Y axis, based on the positioning of the floating element. The positioning `above` results in auto-sizing the `y` position, i.e. width. Positioning the element `before` or `after` the trigger will auto-size the `x` axis, also known as height.
 
Hope this helps! 🙂
