### ISSUE TITLE
PeoplePickerComponent

### ISSUE THREAD

**Issue by Muhammad-saqib** [microsoft/fluentui#30782]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
"@fluentui/react": "^8.115.7",

https://github.com/microsoft/fluentui/issues/9310

i have same issue as mention in above ticket that was closed automatically.i am using 
 "@fluentui/react": "^8.115.7",

i have issue when user type some thing, event "onResolveSuggestions" would not fire but some time it does fire when you click through mouse and popup would open .
```

### Are you reporting Accessibility issue?

None

### Reproduction

onResolveSuggestions

## Actual Behavior
fill this out
onResolveSuggestions should be called in people component
## Expected Behavior
fill this out
onResolveSuggestions should not be called in people component

### Logs

```shell
i have node version 16

and my package is 
"@azure/msal-browser": "^3.0.1",
        "@azure/msal-react": "^2.0.1",
        "@fluentui/react": "^8.115.7",
        "@microsoft/mgt-msal2-provider": "^4.1.0",
        "@microsoft/microsoft-graph-client": "^3.0.7"
```

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Can you please provide a reduced repro of the issue using codepen (aka.ms/fluentpen).
