### ISSUE TITLE
[Feature]: Fluent UI React V9 - Layout, header, content, grid ect..

### ISSUE THREAD

**Issue by jasonwang1109** [microsoft/fluentui#30798]
### Describe the feature that you would like added

When using the V9 version, I cannot find the layout component on the document.  Will it be supported in the future?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by micahgodbolt** [comment]
Can you give more information about what kind of layout you're looking for? CSS already provides great grid support.

**Comment by jasonwang1109** [comment]
Out-of-box portal layout，like Header, Navigation, Sider, Content, Footer etc...

> Can you give more information about what kind of layout you're looking for? CSS already provides great grid support.

**Comment by layershifter** [comment]
@jasonwang1109 v9 intentionally does not support layout components as both CSS Flex and CSS Grid are supported well everywhere nowadays. We will not be able to build components for layouts that are flexible as much as CSS 🐱 

I suggest to check to check:
- https://yoksel.github.io/flex-cheatsheet/
- https://grid.malven.co/

And of course, there is nothing that would stop you from building application specific components for layouts 😉  

See for context:
- https://github.com/microsoft/fluentui/pull/18236
- https://react.fluentui.dev/?path=/docs/concepts-migration-from-v8-components-flex-stack--page
