### ISSUE TITLE
[Bug]: Accordion navigation prop is not align with new ARIA APG pattern 

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#30799]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 18.31 GB / 31.74 GB
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/thq3zi?file=src%2Fexample.tsx

### Bug Description

When user use the navigation prop "navigation" then navigation is not working as execpted.

Repro steps:
Navigate to the URL example
open the dialog

## Actual Behavior
user can use down/up arrows inside the accordion 
then it bring a lot of misunderstanding and wrong navigation... if needed I can provide more details...

## Expected Behavior
based on APG pattern
https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/
such navigation is not supported.
![image](https://github.com/microsoft/fluentui/assets/22620150/328c3e55-6ced-4f80-b03f-5a11a46d2c61)

Proposal fix: remove the "navigation" prop 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
Agree, the arrow key behavior is odd and doesn't match the semantics of accordion. Extra odd that it has both arrow key navigation and tab-through navigation at the same time.

If we have partners asking to arrow through accordions, I think we need to have a more in-depth conversation on what exactly they need, why they need it, and what semantics and patterns would actually match their use case.

**Comment by mainframev** [comment]
@kolaps33, 
Hi 👋🏻  it was deprecated in #31587 and arrow key navigation will be dropped. Thanks for reporting 🙂

**Comment by mainframev** [comment]
navigation prop was deprecated in #31587
