### ISSUE TITLE
[Bug]: Drawer animation wrong direction in RTL languages

### ISSUE THREAD

**Issue by NiklasRamstrom** [microsoft/fluentui#30801]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Any
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/components-drawer--default&globals=storybook_fluentui-react-addon_dir:rtl

## Actual Behavior
When setting direction to RTL, the Drawer animation is from left to right.

## Expected Behavior
When setting direction to RTL, the Drawer animation should be from right to left.
(This is reproducible in the Fluent 9 Storybook)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
@marcosmoura, what is the expected behavior of 'left' positioned drawer in RTL? Is it expected to flip or remain consistent?

**Comment by marcosmoura** [comment]
@micahgodbolt @NiklasRamstrom We'll investigate the fix for this issue and I'll link any actionable PRs related to it here.

**Comment by marcosmoura** [comment]
Related to #31663
