### ISSUE TITLE
[Feature]: Add an option to highlight multiple dates in Fluent UI Calendar 

### ISSUE THREAD

**Issue by shub0012** [microsoft/fluentui#30827]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Right now we can not highlight multiples dates in a month in fluent ui calendar. we can give an array of dates as props so that provided date can be highlighted with a circle and choice of color provided as props

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by micahgodbolt** [comment]
Current approach used by outlook and other apps is to use two calendars for selection. This is not a new ask and is a duplicate of #30511
