### ISSUE TITLE
[Bug]: Dropdown menu has no styling at all.

### ISSUE THREAD

**Issue by zensho-mjp** [microsoft/fluentui#30820]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
    Memory: 6.33 GB / 15.78 GB
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.19041.3636
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/devbox/fr237x?file=%2Fsrc%2FApp.tsx%3A1%2C1-54%2C1&migrateFrom=5hrs2w
## Actual Behavior
A colleague told me he had a bug about the dropdown component.  The dropdown menu, rendering the options, has no styling at all.  It's like everything is erased.  Black, unstyled borders, default font family, etc.
I've tried on a mockup project, with the exact same code you provide, the same bug occurs on my side too.
It seems there is a real bug regarding this component.

![dropdown_bug](https://github.com/microsoft/fluentui/assets/90324108/55e26317-7cc6-440c-a21e-c5e3d0a2e15f)

## Expected Behavior
Dropdown menu having the default styling of the fluent ui v9 library as in the examples present in the documentation.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Taciturne** [comment]
I've got the exact same issue.

**Comment by rvolberg** [comment]
same issue for me as well

**Comment by bsunderhus** [comment]
It seems like in the link provided you forgot to properly [setup](https://react.fluentui.dev/?path=/docs/concepts-developer-quick-start--page#setup) FluentUI. You have to provide a proper `FluentProvider` to ensure a `theme` is present
