### ISSUE TITLE
[Bug]: Listbox is not positioning correctly under combobox when drawer is open and closed

### ISSUE THREAD

**Issue by mikeatms1** [microsoft/fluentui#30846]
what I would like to achieve is a way for the user to interact with a combo box, that always shows the drop list, and employs a Drawer and an Accordion to dynamically show/hide

Here is the component architecture that I used:

![image](https://github.com/microsoft/fluentui/assets/164367402/602420bb-c875-4622-94d2-719a20a74455)

**Desired functionality:**
When the user opens the drawer, and the accordion is open, this is what I would like the user to see

![image](https://github.com/microsoft/fluentui/assets/164367402/f2bb8ad8-fcd0-4b02-933f-0df678162b81)

**Bug**
However, when the Drawer is open and the Accordion is open, the user sees this:

![image](https://github.com/microsoft/fluentui/assets/164367402/10622bb0-316d-4459-a32e-5d6829b38809)

**Steps to reproduce:**
Open the Drawer
Open the Accordion
Close the Drawer
_NOTE_ closing the Drawer saves the "open" Accordion state so the next time the Drawer is opened, the Accordion is also open
Open the Drawer

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Can you provide a working repro of this issue in StackBliz

https://react.fluentui.dev/?path=/docs/components-dropdown--default#default

![image](https://github.com/microsoft/fluentui/assets/1434956/3a824081-4f9c-464f-ae7c-983efb2a654e)

**Comment by mikeatms1** [comment]
can you provide the code to show what I would like it to do ?

**Comment by mikeatms1** [comment]
I have found a way to show the list - `open={true}`

**BUT** when I open the drawer, this is what I see

![image](https://github.com/microsoft/fluentui/assets/164367402/be17f84c-1479-4cf0-9cb1-b9837dbdf3a4)


as soon as I click in the combo box area eg on the `x`
![image](https://github.com/microsoft/fluentui/assets/164367402/41f7b60e-06f3-4a92-ab3d-a1643ccd84e7)

the list moves to under the combo box:
![image](https://github.com/microsoft/fluentui/assets/164367402/0c7e0ea9-b16a-42ae-93a0-b801ac7269d7)

**Comment by mikeatms1** [comment]
Additionally... when I close the drawer.. the list remains there until the drawer closes... then the list disappears
( this is hard to capture with a screen shot )

Here the drawer has just begun to close... `Programs` is slightly greyed out and the entire drawer has shifted to the right 'out from under' the list of items

![image](https://github.com/microsoft/fluentui/assets/164367402/a125e8a1-0408-4028-9ad0-298db6346bad)

In this next screen shot, the drawer almost closed, `Programs` is still visible, but getting lighter and has shifted almost all the way to the right as the drawer closes - the list is still present 

![image](https://github.com/microsoft/fluentui/assets/164367402/d9e3306b-ce18-4f31-aff1-47a8563a7310)

**Comment by mikeatms1** [comment]
**NOTE**:  in this code:

```
return (
        <div className={styles.root}>
            <Combobox
                className={styles.combobox }
                aria-labelledby={labelledBy}
                multiselect={true}
                placeholder="Search values"
                onOptionSelect={onSelect}
                open={true}
                {...props}
            >
                <div style={{ height:"150px", width: "100%" }}>
                {programs.map((option) => (
                    <Option key={option} >
                        {option}
                    </Option>
                ))}
                </div>
            </Combobox>
        </div>
    );
```

I have tried altering the `position` for the div above the mapping as follows:

`<div style={{ position:"static", height:"150px", width: "100%" }}>` - did not work

`<div style={{ position: "relative", height:"150px", width: "100%" }}>`  - did not work

`<div style={{ position:"absolute", height:"150px", width: "100%" }}>` - makes it super bad, did not work

`<div style={{ position:"sticky", height:"150px", width: "100%" }}>` - did not work

`<div style={{ position:"fixed", height:"150px", width: "100%" }}>` - makes is super bad, did not work

Tried changing `top` 

`<div style={{top:"100px", height:"150px", width: "100%" }}>` - did not work

`<div style={{top:"100%", height:"150px", width: "100%" }}>` - did not work

`<div style={{top:"auto", height:"150px", width: "100%" }}>` - did not work

**Comment by mikeatms1** [comment]
Two of my colleagues have looked at this issue, and we believe there is an issue with the combobox listbox not "listening" or "responding" to the animation of the drawer as it opens.

**Comment by mikeatms1** [comment]
Pictorially here is the summary:

**Scenario 1**
When the user opens the drawer and the accordion is closed: 
![image](https://github.com/microsoft/fluentui/assets/164367402/aa05fd68-ef20-4255-acce-01897f49a398)

Then if the user expands the accordion, the list box is in the correct location.
_NOTE: if the user closes the accordion **_before_** closing the drawer and then opens the drawer again and opens the accordion, the list box is always in the correct location_.
![image](https://github.com/microsoft/fluentui/assets/164367402/56c34cc6-7b0e-48c4-8f8d-2ed7ca37c50d)

**Scenario 2**
When the accordion is **expanded** 
![image](https://github.com/microsoft/fluentui/assets/164367402/0d69875e-1493-449c-9b7a-45a1f80af054)

and the **drawer is closed** when the draw is opened again, the list box is not in the correct location

![image](https://github.com/microsoft/fluentui/assets/164367402/6c0b1aae-cca6-475b-8d64-42258cbedd5e)

**Comment by mikeatms1** [comment]
Any progress on this?

**Comment by bsunderhus** [comment]
Hey there @mikeatms1, can you provide a reproduction?
