### ISSUE TITLE
[Bug]: Pivot Component with overflowBehavior="menu" emits "ResizeObserver" error when there is only 1 item showing

### ISSUE THREAD

**Issue by michxzhou** [microsoft/fluentui#30840]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 23.25 GB / 47.71 GB
  Browsers:
    Chrome: 122.0.6261.112
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/michzhou/pen/PogpKWw

In the reproduction link, resize the window to be smaller and notice that the error is logged in the console. Sometimes it appears in the codepen link just from resizing but you may need to drag the browser from a smaller screen to a bigger screen (eg. monitor) to notice the error appearing. 

## Actual Behavior
Pivot component with overflowBehavior="menu" emits a "ResizeObserver loop completed with undelivered notifications" error on load. The error disappears when this prop is removed, but we would like to keep the prop present in the component.

## Expected Behavior
Pivot component with overflowBehavior="menu" should not emit any errors

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Looks like when the pivot gets down to just 1 pivot and the overflow (and it can't get any smaller), the resize loop occurs.

**Comment by michxzhou** [comment]
Hi @tudorpopams - I was out of office for a couple weeks, so I'm just seeing this message now. Sure, I can put up a PR and link it to this issue. I will need to plan this work for a future sprint though, so I'll let you know when I start work on this. Thanks!

**Comment by michxzhou** [comment]
Hi @tudorpopams and @behowell , actually I spoke with my team and it turns out that I don't have capacity to take on this bug as we have a lot of workstreams to prioritize for our service. I will edit the original message to reflect that I will not be able to submit a PR to fix this. Sorry about that!

**Comment by behowell** [comment]
Hi @michxzhou, I'm not able to reproduce this. I tried resizing the codepen panel, resizing the browser window, and moving the browser window between monitors as you mentioned in the repro steps. However, I haven't seen any console error messages. Are you still able to reproduce it in the codepen? Could you give any more details about how to repro it, including what browser you're using? If you're able to post a screenshot or video of the error that may help as well. Thanks.

**Comment by michxzhou** [comment]
Hi @behowell, thanks for following up on this - I just checked and I am no longer able to reproduce this issue on my end, both in the codepen and in the service. I will close this bug now, thanks!
