### ISSUE TITLE
[Bug][TeachingPopover]: Arrow styling is missing dropshadow and is slightly offset

### ISSUE THREAD

**Issue by samfeng279** [microsoft/fluentui#30850]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 6.19 GB / 31.60 GB
  Browsers:
    Chrome: 122.0.6261.129
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/preview-components-teachingpopover--default

## Actual Behavior
Widest part of TeachingBubble arrow is not flush to TeachingBubble. Also doesn't have drop shadow styling like the rest of the TeachingBubble
![image](https://github.com/microsoft/fluentui/assets/15076959/7123f57d-5fa5-4bc9-b529-8f4f02264f47)

## Expected Behavior
Arrow should look like a perfect triangle, and should have drop shadow

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
little more obvious with the brand color

![image](https://github.com/microsoft/fluentui/assets/1434956/81dd58ea-9047-48a7-9345-c2447146e34e)

**Comment by Mitch-At-Work** [comment]
I'm seeing the same issue present on the underlying Popover class, will resolve as part of Popover updates.

**Comment by Mitch-At-Work** [comment]
This has been resolved via: https://github.com/microsoft/fluentui/pull/32138
