### ISSUE TITLE
[Bug]: SearchBox needs SearchBoxChangeEvent exported

### ISSUE THREAD

**Issue by bwaldbaum** [microsoft/fluentui#30869]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 49.77 GB / 63.95 GB
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

Enter a character in SearchBox to generate OnChange event

## Actual Behavior
When the OnChange event is called, the event handler's first param should be `SearchBoxChangeEvent`.  That type isn't being exported from SearchBox.types.ts so consumers of the control can't use it (without a workaround like calling it a React.ChangeEvent instead).

## Expected Behavior
The type should be exported in index.ts so consumers can correctly define the types for the OnChange event.

### Requested priority

Normal

### Products/sites affected

Outlook Monarch

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@bwaldbaum Agreed that the type should be exported. Can you spin up a PR with the fix?
