### ISSUE TITLE
[Bug]: DataGrid does not work with noNativeElements and focusMode "composite"

### ISSUE THREAD

**Issue by rocketBANG** [microsoft/fluentui#30873]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 10.66 GB / 31.71 GB
  Browsers:
    Edge: Chromium (123.0.2420.53)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/szbtzi?file=src%2Fexample.tsx

## Actual Behavior
with `focusMode="composite"` and `noNativeElements={false}`
https://stackblitz.com/edit/szbtzi?file=src%2Fexample.tsx
![image](https://github.com/microsoft/fluentui/assets/2422566/afe41e69-431f-4249-a59c-86ef5e190d1d)

## Expected Behavior
I would expect the columns would still align with these props set like when focus mode is set to `"cell"`. I also think the rows should align.
with  `focusMode="cell"` and `noNativeElements={false}`
![image](https://github.com/microsoft/fluentui/assets/2422566/093741ea-f9f2-4b15-9ce7-2b5f43e06519)

Also it appears the docs are wrong about the default state of `noNativeElements`. It says it's default `false` but when I add it as a prop manually, I get a different behaviour (seems it's defaulted to true)
![image](https://github.com/microsoft/fluentui/assets/2422566/a0820c01-56ae-45df-8c9a-2ad15435c811)

I'm trying to use this `noNativeElements` mode as there doesn't appear to be a way to size the columns to fit the content inside them otherwise - if there's a workaround for that I may not need this mode and it wouldn't be an issue

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
A table with native elements should not support focus management. When focus management is involved, only elements with `role="grid"` are truly accessible.

Statically sizing the columns is possible but just requires different CSS properties and paradigm since everything is a flex based layout https://stackblitz.com/edit/cokahv?file=src%2Fexample.tsx
