### ISSUE TITLE
[Bug]: Unable to execute component test with playwright

### ISSUE THREAD

**Issue by rosergeev** [microsoft/fluentui#30871]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
    Memory: 8.47 GB / 16.00 GB
  Browsers:
    Edge: Chromium (122.0.2365.66)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/devbox/testwithvitestandplaywright-v8zjns?file=%2Fsrc%2Fe2e%2FCalendarWrapper.test.tsx%3A22%2C1

## Actual Behavior
We have a bunch of wrapper controls of the fluentui v9 components. Several of them use combobox, calendar, etc, in other words some kind of popover inside a portal. In the following [discussion](https://github.com/microsoft/fluentui/discussions/30821) @bsunderhus suggested to test them with help of one of the e2e test framework, e.g. Playwright. 
Our components are used in Office Add-Ins(for Excel, Word and Outlook) and in order to localize them we create LocalizationContext which provides locale of the host application to the Add-In application. So, in repro I have provided simplified version of the code. The main idea is that all components are rendered within LocalizationContext which in turn provides translator with some localized strings.
But this combination doesn't work with playwright framework. It doesn't compile the test with syntax error  "Named export 'defaultDatePickerStrings' not found".  With our production code I've seen similar error but for makeStyles function.

### Logs

```shell
workspace git:(master) ✗ npm run test-ct

> react-vite-ts@0.0.0 test-ct
> playwright test -c playwright-ct.config.ts

SyntaxError: Named export 'defaultDatePickerStrings' not found. The requested module '@fluentui/react-datepicker-compat' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@fluentui/react-datepicker-compat';
const { defaultDatePickerStrings } = pkg;


SyntaxError: Named export 'defaultDatePickerStrings' not found. The requested module '@fluentui/react-datepicker-compat' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@fluentui/react-datepicker-compat';
const { defaultDatePickerStrings } = pkg;


Error: No tests found

To open last HTML report run:

  npx playwright show-report
```

### Requested priority

Blocking

### Products/sites affected

ImageMaster OfficeClient Add-In

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
It seems like `playwright` might be failing to resolve the ES modules and is opting in to use CJS instead and for some reason its failing to resolve named exports?! Try this  https://codesandbox.io/p/devbox/testwithvitestandplaywright-forked-jzq52x?file=%2Fsrc%2Flocalization%2FEnglishScheme.ts%3A10%2C1

**Comment by rosergeev** [comment]
@bsunderhus , Thank you for your reply. This helped me a bit, but I have encountered with the next issue
![image](https://github.com/microsoft/fluentui/assets/12766193/0462a8b5-e28b-49f4-af9d-707d56d834ca)

And I can't reproduce it at codesandbox, as the same code works as expected. If I use named import then I get the same error:
![image](https://github.com/microsoft/fluentui/assets/12766193/2cad8e01-fdb0-45a1-96f1-734691f5bdd4)
but this is expected behavior

**Comment by bsunderhus** [comment]
You're bumping into the same problem there, it seems like your environment is not properly set. Those named exports do exist on `@fluentui/react-components` bundle, both on ES and CJS outputs.

Here's the `unpkg` [link](https://unpkg.com/@fluentui/react-components@9.47.2/lib-commonjs/index.js) for the cjs export

Here's the `unpkg` [link](https://unpkg.com/@fluentui/react-components@9.47.2/lib/index.js) for the ES export
