### ISSUE TITLE
Bugs arising after migrating to D3's scaleUtc utility

### ISSUE THREAD

**Issue by krkshitij** [microsoft/fluentui#30893]
Following bugs have been identified/reported:
1. In some cases, axis ticks only display the time component instead of a more meaningful representation.
   Possible reason: The `multiFormat` utility is not working well with `scaleUtc`.

   ![image](https://github.com/microsoft/fluentui/assets/110246001/3f126f9d-4938-4e05-b1d9-bdc9684437dc)

2. Axis ticks are shown in UTC time, whereas other elements of the chart, such as the callout, display local time.

   ![image](https://github.com/microsoft/fluentui/assets/110246001/0c1f62b7-3e58-4a70-96a0-1b69b286033b)

**Comment by AtishayMsft** [comment]
Another issue is that if the date object is in local datetime format, then the x axis ticks are not rounded off to 00:00 but take the utc equivalent date and then convert it into the local time ticks creating a weird tick behavior.

More details are reported in this bug: https://github.com/microsoft/fluentui/issues/31269
