### ISSUE TITLE
[Bug]: Tooltip can't disappear in Dropdown

### ISSUE THREAD

**Issue by sherryzhao11** [microsoft/fluentui#30894]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 1.95 GB / 4.01 GB
    Container: Yes
    Shell: Unknown
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/devbox/currying-worker-9qputt?file=%2Fsrc%2FApp.tsx%3A36%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluak4dnj00073d5uw9l8ub8z%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluak4dni00023d5u19278s61%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluak4dni00043d5ugw9xdwvj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluak4dnj00063d5ugp482j20%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluak4dni00023d5u19278s61%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluak4dni00013d5upnn90n75%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cluak90ay00973d5uvg0977zx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A36%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A36%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cluak4dni00023d5u19278s61%2522%252C%2522activeTabId%2522%253A%2522cluak90ay00973d5uvg0977zx%2522%257D%252C%2522cluak4dnj00063d5ugp482j20%2522%253A%257B%2522id%2522%253A%2522cluak4dnj00063d5ugp482j20%2522%252C%2522activeTabId%2522%253A%2522cluakaz7a00lb3d5unbtrro5j%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluak4dnj00053d5u0gf65nzm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5174%252C%2522id%2522%253A%2522cluakaz7a00lb3d5unbtrro5j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cluak4dni00043d5ugw9xdwvj%2522%253A%257B%2522id%2522%253A%2522cluak4dni00043d5ugw9xdwvj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluak4dni00033d5u6eccrp1n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cluak9m9i00hy3d5uzgbekgpp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluak9mmc000tdjip7reocl8r%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluak9m9i00hy3d5uzgbekgpp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Bug Description

When add Tooltip for options in Dropdown, once the option is selected, but the tooltip is not disappear as soon. 

Reproduce the issues in [codesandbox](https://codesandbox.io/p/devbox/currying-worker-9qputt?file=%2Fsrc%2FApp.tsx%3A36%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluak4dnj00073d5uw9l8ub8z%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluak4dni00023d5u19278s61%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluak4dni00043d5ugw9xdwvj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluak4dnj00063d5ugp482j20%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluak4dni00023d5u19278s61%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluak4dni00013d5upnn90n75%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cluak90ay00973d5uvg0977zx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A36%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A36%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cluak4dni00023d5u19278s61%2522%252C%2522activeTabId%2522%253A%2522cluak90ay00973d5uvg0977zx%2522%257D%252C%2522cluak4dnj00063d5ugp482j20%2522%253A%257B%2522id%2522%253A%2522cluak4dnj00063d5ugp482j20%2522%252C%2522activeTabId%2522%253A%2522cluakaz7a00lb3d5unbtrro5j%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluak4dnj00053d5u0gf65nzm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5174%252C%2522id%2522%253A%2522cluakaz7a00lb3d5unbtrro5j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cluak4dni00043d5ugw9xdwvj%2522%253A%257B%2522id%2522%253A%2522cluak4dni00043d5ugw9xdwvj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluak4dni00033d5u6eccrp1n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cluak9m9i00hy3d5uzgbekgpp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluak9mmc000tdjip7reocl8r%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluak9m9i00hy3d5uzgbekgpp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Example code with react v9

`import {
  Dropdown,
  makeStyles,
  Option,
  shorthands,
  useId,
  Tooltip,
  Text
} from "@fluentui/react-components";
import type { DropdownProps } from "@fluentui/react-components";

const useStyles = makeStyles({
  root: {
    // Stack the label above the field with a gap
    display: "grid",
    gridTemplateRows: "repeat(1fr)",
    justifyItems: "start",
    ...shorthands.gap("2px"),
    maxWidth: "400px",
  },
});

export const Default = (props: Partial<DropdownProps>) => {
  const dropdownId = useId("dropdown-default");
  const options = [
    "Cat",
    "Caterpillar",
    "Corgi",
    "Chupacabra",
    "Dog",
    "Ferret",
    "Fish",
    "Fox",
    "Hamster",
    "Snake",
  ];
  const styles = useStyles();
  return (
    <div className={styles.root}>
      <label id={dropdownId}>Best pet</label>
      <Dropdown
        aria-labelledby={dropdownId}
        placeholder="Select an animal"
        {...props}
      >
        {options.map((option) => (
          <Option key={option} text={option} disabled={option === "Ferret"}>
            <Tooltip content={option} relationship="label">
            <Text>{option}</Text></Tooltip>
          </Option>
        ))}
      </Dropdown>
    </div>
  );
};`

https://github.com/microsoft/fluentui/assets/132635147/5fdf979c-4636-43fa-8fe1-93b486ebf71b

But when add mountNode, the tooltip can disappear, but the long content tooltip would be cut .
 
`
import * as React from "react";
import {
  Dropdown,
  makeStyles,
  Option,
  shorthands,
  useId,
  Tooltip,
  Text
} from "@fluentui/react-components";
import type { DropdownProps } from "@fluentui/react-components";

const useStyles = makeStyles({
  root: {
    // Stack the label above the field with a gap
    display: "grid",
    gridTemplateRows: "repeat(1fr)",
    justifyItems: "start",
    ...shorthands.gap("2px"),
    maxWidth: "400px",
  },
});

export const Default = (props: Partial<DropdownProps>) => {
  const dropdownId = useId("dropdown-default");
  const options = [
    "longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong",
    "Caterpillar",
    "Corgi",
    "Chupacabra"
  ];
  const styles = useStyles();
  const [ref, setRef] = React.useState<HTMLElement | null>();
  return (
    <div className={styles.root}>
      <label id={dropdownId}>Best pet</label>
      <Dropdown
        aria-labelledby={dropdownId}
        placeholder="Select an animal"
        {...props}
      >
        {options.map((option) => (
          <Option key={option} text={option} disabled={option === "Ferret"} ref={setRef}>
            <Tooltip content={option} relationship="label" mountNode={ref}>
            <Text>{option}</Text></Tooltip>
          </Option>
        ))}
      </Dropdown>
    </div>
  );
};
`
![Screenshot 2024-03-28 at 10 03 41](https://github.com/microsoft/fluentui/assets/132635147/d4b22fd4-2a81-46f4-b942-9a17f2c76129)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@sherryzhao11 Can you please add a working repro? I opened the linked Codesandbox but it looks like it's just the default setup without your code.

**Comment by sherryzhao11** [comment]
Hi @spmonahan , sorry to link the wrong codesand , this address, and also the code can 
 https://codesandbox.io/p/devbox/new-surf-lmrnk8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluak4dnj00073d5uw9l8ub8z%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluak4dni00023d5u19278s61%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluak4dni00043d5ugw9xdwvj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluak4dnj00063d5ugp482j20%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluak4dni00023d5u19278s61%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluak4dni00013d5upnn90n75%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cluak90ay00973d5uvg0977zx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A1%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cluak4dni00023d5u19278s61%2522%252C%2522activeTabId%2522%253A%2522cluak90ay00973d5uvg0977zx%2522%257D%252C%2522cluak4dnj00063d5ugp482j20%2522%253A%257B%2522id%2522%253A%2522cluak4dnj00063d5ugp482j20%2522%252C%2522activeTabId%2522%253A%2522cluakaz7a00lb3d5unbtrro5j%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluak4dnj00053d5u0gf65nzm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5174%252C%2522id%2522%253A%2522cluakaz7a00lb3d5unbtrro5j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cluak4dni00043d5ugw9xdwvj%2522%253A%257B%2522id%2522%253A%2522cluak4dni00043d5ugw9xdwvj%2522%252C%2522activeTabId%2522%253A%2522cluak9m9i00hy3d5uzgbekgpp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluak4dni00033d5u6eccrp1n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cluak9m9i00hy3d5uzgbekgpp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluak9mmc000tdjip7reocl8r%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520install%2520%2540fluentui%252Freact-components%25409.47.2%2520--save-dev%2522%252C%2522id%2522%253A%2522cluakgi9n002q3d5ujzuh57ut%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D


Also the code can reproduce:
``import {
Dropdown,
makeStyles,
Option,
shorthands,
useId,
Tooltip,
Text
} from "@fluentui/react-components";
import type { DropdownProps } from "@fluentui/react-components";

const useStyles = makeStyles({
root: {
// Stack the label above the field with a gap
display: "grid",
gridTemplateRows: "repeat(1fr)",
justifyItems: "start",
...shorthands.gap("2px"),
maxWidth: "400px",
},
});

export const Default = (props: Partial) => {
const dropdownId = useId("dropdown-default");
const options = [
"Cat",
"Caterpillar",
"Corgi",
"Chupacabra",
"Dog",
"Ferret",
"Fish",
"Fox",
"Hamster",
"Snake",
];
const styles = useStyles();
return (


Best pet
<Dropdown
aria-labelledby={dropdownId}
placeholder="Select an animal"
{...props}
>
{options.map((option) => (
<Option key={option} text={option} disabled={option === "Ferret"}>

{option}

))}


);
};`

**Comment by TristanWatanabe** [comment]
@sherryzhao11 can you clarify what the issue is? From my understanding, you mentioned that the tooltip does not go away after selecting a dropdown option, but i'm not able to reproduce that:

https://github.com/user-attachments/assets/240eda7a-4116-4bfb-80fa-4c075b0477bc
