### ISSUE TITLE
[Bug]: Menu autosize positioning does not apply boundary padding vertically

### ISSUE THREAD

**Issue by rocketBANG** [microsoft/fluentui#30901]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 10.66 GB / 31.71 GB
  Browsers:
    Edge: Chromium (123.0.2420.53)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/jurvrn-8vxs7f?file=src%2Fexample.tsx

## Actual Behavior
when menu has positioning props of `autosize: true` and `overflowBoundaryPadding`, it doesn't appear the boundary padding is respected with bottom and top. The menu expands to the very bottom of the page without padding
```ts
<Menu
    positioning={{
      autoSize: true,
      overflowBoundaryPadding: { bottom: 24, top: 24 },
    }}
  >
```

![Screenshot 2024-03-28 131915](https://github.com/microsoft/fluentui/assets/2422566/8af282f5-5117-44ce-a51e-f8dc147051f2)

## Expected Behavior
I would expect by setting the bottom `overflowBoundaryPadding` to 24 that there would be 24px between the bottom of the menu and the bottom of the webpage/viewport

![image](https://github.com/microsoft/fluentui/assets/2422566/0955cc0f-f686-49f9-ac6e-021ab03db69a)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by rocketBANG** [comment]
Looks like the `overflowBoundary` props are passed into `maxSize`, but not `overflowBoundaryPadding`

https://github.com/microsoft/fluentui/blob/caf072510560c342c3e6e0bcc57b83b8500d21f6/packages/react-components/react-positioning/src/middleware/maxSize.ts#L40-L43

**Comment by spmonahan** [comment]
Part of the problem with the repro is that `overflowBoundary` is not set in positioning like it is in [the example](https://react.fluentui.dev/?path=/docs/concepts-developer-positioning-components--default#overflow-boundary-padding).

Even with that it seems that `bottom` is not respected: https://stackblitz.com/edit/jurvrn-dwzvro?file=src%2Fexample.tsx
