### ISSUE TITLE
ComboBox Freeform Input Matches Option Without Case Sensitivity Check

### ISSUE THREAD

**Issue by libjosep** [microsoft/fluentui#30915]
### Environment Information

- **Package version(s)**: fluentui react@8
- **Browser and OS versions**: Chrome 123.0.6312.86 (Official Build) (64-bit). Windows 11

### Describe the issue:

The issue arises when utilizing the ComboBox feature with freeform input. Currently, if the ComboBox contains an option such as 'black' (in lowercase), and the user inputs 'BLACK' (in uppercase), the ComboBox automatically loads the existing option 'black'. However, the desired behavior is to treat 'BLACK' as a distinct freeform entry rather than automatically matching it to the existing option.

#### Actual behavior:

The current behavior of the ComboBox with freeform input is such that if the ComboBox already contains an option like 'black' (in lowercase), and the user types 'BLACK' (in uppercase), the ComboBox automatically selects and loads the existing option 'black'. This occurs without performing any case sensitivity check on the user input.

#### Expected behavior:

The expected behavior for the ComboBox with freeform input is that regardless of the case, if the user inputs 'BLACK' (in uppercase) and it does not match any existing option exactly, it should be treated as a distinct freeform entry. Therefore, 'BLACK' should appear as a separate text option rather than automatically matching it to an existing option like 'black'.

### Demo Video

https://github.com/microsoft/fluentui/assets/28481997/f56b9e16-3c46-4f0c-8a46-eea12b3eddaf

### If applicable, please provide a codepen repro:
https://codepen.io/libinpjoseph/pen/vYMWyMw?editors=1111

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by spmonahan** [comment]
The [lowercase comparison is hard coded](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/ComboBox/ComboBox.tsx#L900) so this feature request would require updating `ComboBox` to opt out of this behavior.
