### ISSUE TITLE
[Bug]: https://uifabricicons.azurewebsites.net/ - not generating subsets - throws internal server error 500

### ISSUE THREAD

**Issue by ThayalanGR** [microsoft/fluentui#30916]
### Library

Web Components (@fluentui/web-components)

### System Info

```shell
Something like this happening - https://github.com/microsoft/fluentui/issues/10457
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://uifabricicons.azurewebsites.net/

### Bug Description

Something like this happening - https://github.com/microsoft/fluentui/issues/10457

### Logs

```shell
https://uifabricicons.azurewebsites.net/
```

### Requested priority

Blocking

### Products/sites affected

https://uifabricicons.azurewebsites.net/

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Bertie2011** [comment]
+1 Please Fix!

**Comment by chrisdholt** [comment]
@Jahnp assigning this to you since I'm not sure who owns this area at this point in time - feel free to forward or move to the right person :)

**Comment by Jahnp** [comment]
Thanks @chrisdholt, I'm still the right person for this.

@ThayalanGR is this still reproducing for you? From checking logs the last 7 days it looks like there were some errors I'm investigating, but I've been unable to repro any issues today.

**Comment by ThayalanGR** [comment]
@Jahnp let me check now!

**Comment by ThayalanGR** [comment]
@Jahnp just checked, Now works like a charm!
