### ISSUE TITLE
[Bug]: Dropdown `value` set but not displayed

### ISSUE THREAD

**Issue by kidlj** [microsoft/fluentui#30912]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M2
    Memory: 93.08 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 123.0.6312.86
    Safari: 17.4
  npmPackages:
    @fluentui/react-components: ^9.47.1 => 9.47.1 
    @types/node: ^20 => 20.11.30 
    @types/react: ^18 => 18.2.69 
    @types/react-dom: ^18 => 18.2.22 
    autoprefixer: ^10.0.1 => 10.4.19 
    eslint: ^8 => 8.57.0 
    eslint-config-next: 14.1.4 => 14.1.4 
    next: 14.1.4 => 14.1.4 
    postcss: ^8.4.38 => 8.4.38 
    react: ^18 => 18.2.0 
    react-dom: ^18 => 18.2.0 
    sass: ^1.72.0 => 1.72.0 
    tailwindcss: ^3.3.0 => 3.4.1 
    typescript: ^5 => 5.4.3
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://github.com/kidlj/fluentui-v9-dropdown-debug

## Actual Behavior

With Dropdown component, when an sibling `Input` value of the same form has changed, Dropdown `value` field is correctly set, but is not displayed(it's cleared in UI, but not on the DOM, see the demo video).

## Expected Behavior

When Dropdown `value` field is set, it's also displayed in the UI.

## Demo video

https://github.com/microsoft/fluentui/assets/300616/c973ac22-1f51-4f91-9c4c-0dafc25e9259

### Requested priority

Normal

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Your repro link didn't have any Fluent `Input`s or `Dropdown`s that I could see but based on the video I put together this potential solution: https://stackblitz.com/edit/spmonahan-fluentui-gqauqo?file=src%2FApp.tsx

**Comment by kidlj** [comment]
> Your repro link didn't have any Fluent `Input`s or `Dropdown`s that I could see but based on the video I put together this potential solution: https://stackblitz.com/edit/spmonahan-fluentui-gqauqo?file=src%2FApp.tsx

Sorry for the inconvenience. The `Dropdown` and `Input` resides in https://github.com/kidlj/fluentui-v9-dropdown-debug/blob/main/components/form.tsx, and you can visit http://localhost:3000/project to see the form page.

**Comment by TristanWatanabe** [comment]
@kidlj Looking at the code you provided, you'll need to track the **state** of `value` to get the desired behavior you want. You can see an example in the docsite [here](https://react.fluentui.dev/?path=/docs/components-dropdown--docs#controlled). The [example](https://stackblitz.com/edit/spmonahan-fluentui-gqauqo?file=src%2FApp.tsx) @spmonahan provided is also a great point of reference
