### ISSUE TITLE
[Bug]: Dropdown option is not selected when option value is empty string or 0

### ISSUE THREAD

**Issue by ymyqwe** [microsoft/fluentui#30924]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 43.69 GB / 47.05 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/w57l4n?file=src%2Fexample.tsx

## Actual Behavior
When Option Value is empty string or zero. The option is not selected with checkIcon.

![image](https://github.com/microsoft/fluentui/assets/11665103/781274f7-95d1-48b9-841e-cdb7c0c792f8)

## Expected Behavior
Option should be selected with checkIcon
![image](https://github.com/microsoft/fluentui/assets/11665103/6b218502-82f4-426b-a270-6278565d69cd)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
This is probably because of the `!!optionValue` [here](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-combobox/src/components/Option/useOption.tsx#L64).
