### ISSUE TITLE
TeachingPopoverCarousel - onPageChange is called twice for each page change 

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#30932]
```tsx
 <TeachingPopoverCarousel
          onPageChange={console.log}
          strings={{
            next: 'Next',
            previous: 'Previous',
            initialStepText: 'Close',
            finalStepText: 'Finish',
          }}
        >
```

Each time a page changes the `console.log` is called twice, this is because there are two separate calls that handle `onPageChange`:

1. On the carousel root - https://github.com/microsoft/fluentui/blob/fdc1773ee8ab3c45ae449ea3a297d26b63e37523/packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarousel/useTeachingPopoverCarousel.ts#L65
2. On the nav button - https://github.com/microsoft/fluentui/blob/fdc1773ee8ab3c45ae449ea3a297d26b63e37523/packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarouselNavButton/useTeachingPopoverCarouselNavButton.tsx#L40

**Comment by Mitch-At-Work** [comment]
Resolved by: https://github.com/microsoft/fluentui/pull/30998
