### ISSUE TITLE
TeachingPopoverCarousel - unable to override Nav component

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#30930]
When I try to override the carousel nav with my own nav button elements, the default nav still renders the default nav buttons:

```tsx
<TeachingPopoverCarousel
        strings={{
          next: 'Next',
          previous: 'Previous',
          initialStepText: 'Close',
          finalStepText: 'Finish',
        }}
        nav={
          <>
            <TeachingPopoverCarouselNavButton index={0} />
            <TeachingPopoverCarouselNavButton index={1} />
            <TeachingPopoverCarouselNavButton index={2} />
          </>
        }
      >
```

![image](https://github.com/microsoft/fluentui/assets/20744592/d818ceba-c2b5-457d-acae-dad6f8bfdd18)

**Comment by ling1726** [comment]
This is most likely due to the fact thathe slot is being assigned to the wrong place (nav slot assigned to pageCount)

https://github.com/microsoft/fluentui/blob/fdc1773ee8ab3c45ae449ea3a297d26b63e37523/packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarousel/useTeachingPopoverCarousel.ts#L133-L137

**Comment by Mitch-At-Work** [comment]
Resolved by: https://github.com/microsoft/fluentui/pull/30998
