### ISSUE TITLE
[Bug]: Toast with Nextjs gives Warning: A props object containing a "key" prop is being spread into JSX 

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#30942]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 51.85 GB / 63.57 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.78)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-ddbwif?file=package.json

## Actual Behavior
We are using Nextjs v13 and Toast component from @fluentui/react-components v9.47.1. 

When using Vite and when the Toast renders, it works fine without any logs. But when using Nextjs v13, we get warning log: 

```
Warning: A props object containing a "key" prop is being spread into JSX:
  let props = {key: someKey, onTimeout: ..., running: ..., timeout: ...};
  <Timer {...props} />
React keys must be passed directly to JSX without using spread:
  let props = {onTimeout: ..., running: ..., timeout: ...};
  <Timer key={someKey} {...props} />
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@fluentui/react-toast/lib/components/ToastContainer/ToastContainer.js:19:97)
    at div
    at Toaster (webpack-internal:///(app-pages-browser)/./node_modules/@fluentui/react-toast/lib/components/Toaster/Toaster.js:19:83)
......
```

**Screenshot:**

![image](https://github.com/microsoft/fluentui/assets/39588094/a2900b39-afe6-43d3-b09a-12468af0eac8)

## Expected Behavior
The expectation is that Toast props should be spread properly. 

## Two Sandboxes
With **Nextjs**, the warning appears: 
https://stackblitz.com/edit/stackblitz-starters-ddbwif?file=package.json

With **Vite**, no warning: 
https://stackblitz.com/edit/zprd9b?file=src%2FAnotherComponent.tsx

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Next.js uses canary versions of React, that's a warning is reproducible only with Next.js 🐱 It reproes with Vite once the canary version is used: https://stackblitz.com/edit/zprd9b-qqxb9i?file=yarn.lock,package.json

**Comment by layershifter** [comment]
> I am wondering how you found out that Next is using canary versions of React? I checked the package-lock and my local installed node_modules, I couldn't find the specific canary versions. Really appreciate if you would love to share more inputs. Thank you!

> The App Router is built on the React canary channel, which is [stable for frameworks](https://react.dev/blog/2023/05/03/react-canaries) to adopt new features. As of v14, Next.js has upgraded to the latest React canary, which includes stable Server Actions.
>
> https://nextjs.org/blog/next-14#server-actions-stable

You can also do `console.log(React.version)`, in sandbox it was `18.3.0-canary-d6dcad6a8-20230914`.
