### ISSUE TITLE
[Bug]: DetailList change not clear other selected row when i click on the link inside cell

### ISSUE THREAD

**Issue by bnv-onix** [microsoft/fluentui#31024]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
i using latest verion v8 of fluent. 
reactjs version 18
```

### Are you reporting Accessibility issue?

no

### Reproduction

yes

## Actual Behavior
step 1: i select 2 row: item 1 and item 2. the column cell is a tag <a> that user can click on to open new tab browser.
step 2: i click on the link of the cell the row "item 2"

![image](https://github.com/microsoft/fluentui/assets/160565811/5d2638b0-115e-49fd-a130-20ab34c574eb)
step 3: the "item 1" still be selected
## Expected Behavior
i expect to unselected the "item 1" like bellow: 
![image](https://github.com/microsoft/fluentui/assets/160565811/efc615ae-dfce-4091-be36-380106451d14)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bnv-onix** [comment]
@sopranopillow  do you have any idea to solve this issue ?

**Comment by bnv-onix** [comment]
> @sopranopillow do you have any idea to solve this issue ?

i have been stucked at here !

**Comment by spmonahan** [comment]
I think the observed behavior is correct in this case. When clicking a link inside `DetailsList` I would expect the link to handle the click and selection to not be changed.

That said, you should be able to achieve your desired behavior by manually invoking a click from the `Link`'s click handler.

[Here's an example Codepen](https://codepen.io/seanms/pen/BagZYEj).

The relevant bit of code is:

```ts
const onLinkClick = (e) => {
    e.currentTarget.parentElement.click();
}
```
