### ISSUE TITLE
[Feature]: Combobox should support Grid, Tree, and Dialog Popup Types

### ISSUE THREAD

**Issue by dtarjeft** [microsoft/fluentui#31040]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

The [APG for Combobox](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/#aboutthispattern) states: 

> The popup may be a [listbox](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/), [grid](https://www.w3.org/WAI/ARIA/apg/patterns/grid/), [tree](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/), or [dialog.](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/)

The current Combobox Fluent implementation focuses on Listbox-type popups. We should make it easy to create Combobox popups of the other types in the spec -- if it's doable today, we should create examples or guides for the documentation.

### Additional context

I was able to create a pseudo-Tree by customizing Option quite heavily, but filtered (Combobox) and collapsed (Tree) values conflicted badly. Keyboard navigation behaved like a Listbox, without easy/intuitive overrides. Giving the Option the onKeyDown event (before it gets to Input) could allow Grid/Tree row-specific responses.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by smhigley** [comment]
Grid, tree, and dialog combobox popups have some fairly large open accessibility-related semantics and keyboard issues. The biggest of which include:
- How do we resolve the behavior of left/right arrow keys between moving through text vs. operating a tree/grid?
- Dialog is a free-for-all in terms of keyboard navigation, how do we even begin to build in keyboard operation of the dialog controls vs. the input?

These are not common, understood controls even on Windows desktop. The base combobox pattern is already quite difficult  to use in terms of real-world understandability and operation, especially with assistive tech. Before we consider non-listbox combobox variants, I think we would need compelling evidence that they are usable in practice, and not better served by other patterns. My gut feeling is that these use cases would be much better served by a button that a popup that takes focus, where the user can interact with the tree, grid, or other controls and hit "confirm" to select.

The APG has many patterns that are technically possible but not a good idea in practice (e.g. the whole `role="menu"` navigation pattern). It's a good reference for what ARIA attributes need to be added to a specific role/pattern, but not a good baseline for what controls should be used in a real UI 😅. For now, this specific pattern is not part of the Fluent v9 roadmap, though that could also change, given a compelling use case.

If you have a specific UI in mind, we're also always happy to discuss what Fluent controls and semantics/keyboard behavior would best fit your use case!
