### ISSUE TITLE
[Bug]: Module '"@fluentui/react-components"' has no exported member 'SearchBox'.

### ISSUE THREAD

**Issue by Davidihl** [microsoft/fluentui#31063]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.20348
    CPU: (8) x64 AMD EPYC 7371 16-Core Processor
    Memory: 19.36 GB / 32.00 GB
  Browsers:
    Edge: Chromium (121.0.2277.112)
    Internet Explorer: 11.0.20348.380
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/6hdwvf?file=src%2Fexample.tsx

## Actual Behavior
According to https://react.fluentui.dev/?path=/docs/components-searchbox--default

`import {  SearchBox } from "@fluentui/react-components";`
prompts Error: Module '"@fluentui/react-components"' has no exported member 'SearchBox'.

## Expected Behavior
`SearchBox` gets exported as well as `SearchBoxProps` or update Docs if another Package is required.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mrtalley** [comment]
I'm having the same issue on the latest version. The component is accessible via the `@fluentui/react-search` library, but should also be available in the main library according to the docs.

**Comment by khmakoto** [comment]
I think what happened is that the component was moved to stable by officially exporting it from `@fluentui/react-components`, but we haven't had a release since then. The component should be available in the next minor release.

**Comment by TristanWatanabe** [comment]
Yup @khmakoto is right, our docsite and what's published are currently out of sync. I will trigger a release of `@fluentui/react-components` today so this issue should be fixed in the next minor release (`9.48.0`)

**Comment by TristanWatanabe** [comment]
version `9.48.0` has been released - all `@fluentui/react-search` related exports should now be available from the `@fluentui/react-components` package :https://www.npmjs.com/package/@fluentui/react-components

**Comment by Davidihl** [comment]
Thank you, I can confirm this issue fixed looking at my stackblitz demo

**Comment by mrtalley** [comment]
Thanks for the quick turnaround on this!
