### ISSUE TITLE
[Bug]: Combobox does not allow selection of empty string

### ISSUE THREAD

**Issue by daniellittledev** [microsoft/fluentui#31062]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-combobox
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/dasaev-nefgtn?file=src%2Fexample.tsx

## Actual Behavior
I can select the option in the dropdown

## Expected Behavior
The option cannot be selected

This is due to a !!optionValue comparison which returns false for an empty string, the check should test for null or undefined instead.
https://github.com/microsoft/fluentui/blob/0e7d5aacea7d9306b10f37c014c82e668b098324/packages/react-components/react-combobox/src/components/Option/useOption.tsx#L64

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Fixed in #31170.
