### ISSUE TITLE
[Bug]: Combobox virtualizer sometimes does not render options while scrolling

### ISSUE THREAD

**Issue by mboggs1** [microsoft/fluentui#31075]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 40.88 GB / 63.95 GB
  Browsers:
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://stackblitz.com/run?file=src%2Fexample.tsx

## Actual Behavior
Scrolling through virtualized combobox options sometimes causes options to not render. The repro can be inconsistent, but I have found these steps to reproduce is after a few tries: 
1. Grab the scroll bar and drag it far enough to render a new page of options 
2. Use the scroll wheel to start scrolling down through options
3. Eventually, new options will stop rendering and I see an empty listbox
4. Scrolling back up to the rendered options and scrolling down again will fix the issue

Can be reproduced in the virtualized combobox storybook example. 

![V9_ComboBox_Virtual_Bug](https://github.com/microsoft/fluentui/assets/102692996/5a7a6680-9f78-4477-accb-2035e42bf6a6)

## Expected Behavior
Options should always render as expected. 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
@mboggs1 are you still seeing this? I haven't been able to repro it, even through multiple page refreshes, with CPU throttling, and/or with network throttling.

FYI @Mitch-At-Work.

**Comment by mboggs1** [comment]
@khmakoto - Yup can still repro this on the examples page. It's not easy to repro though. It took me a few minutes of trying, but eventually I did see it. I didn't try throttling, just with the steps above.
