### ISSUE TITLE
[Feature]: Honor offset when Popover surface is flipped

### ISSUE THREAD

**Issue by danavishnukb** [microsoft/fluentui#31084]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

As of today, whenever popover components are flipped either horizontally or vertically, the offset associated with the popover surface is discarded. This feature requests that offset be honored or atleast some sort of indication be added via a callback to show that the surface has been flipped.

### Have you discussed this feature with our team

Lingan Gao

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by george-cz** [comment]
Hello @danavishnukb,

can you please provide a minimal reproducible example on Stackblitz?

I've tried to reproduce this behavior based off your description but it seems that as I resize the window and the popover flips, the offset is properly respected. https://stackblitz.com/edit/btnywm?file=src%2Fexample.tsx

Thanks!

**Comment by ling1726** [comment]
Made a more minimal repro here https://stackblitz.com/edit/btnywm-vtm8cm?file=src%2Fexample.tsx

@danavishnukb let's discuss offline again to see what the root cause of your issue was
