### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft/fluentui#31103]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz     
    Memory: 89.25 GB / 127.67 GB
  Browsers:
    Edge: Chromium (123.0.2420.65), ChromiumDev (123.0.2380.1)       
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/ofergal/pen/RwOeLLm

## Actual Behavior
target="_blank" does not open it a new tab when the target is in the same /SitePages library in sharePoint
## Expected Behavior
target="_blank" should open in separate tab no matter where.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
I'm unable to repro the described issue - link opens in new tab as expected: 
![Target blank issue](https://github.com/microsoft/fluentui/assets/8649804/91e89495-783f-474d-9188-85e484e940ba)

**Comment by Ofer-Gal** [comment]
I tied to explain that it works in the repo but in my SPFx web part, the link to a same library  aspx page, opens it the same window. If it is too much trouble , I will use a normal A tag.

**Comment by marcosmoura** [comment]
@Ofer-Gal Since the issue happens in an extremely specific environment, we cannot reproduce as it works correctly in our docs and CodePen.
