### ISSUE TITLE
[Feature]: TabList is missing built-in overflow support

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#31118]
### Library

react-components v9
https://react.fluentui.dev/?path=/docs/components-tablist--default

### Describe the feature that you would like added

If you scroll down the page, you will find an overflow example. However, it is exceedingly complicated and involved for the developer. This creates a disincentive for a consistent behavior. While I can understand bundle size concerns because not every scenario needs overflow behavior, I would challenge that we should have a TabList implementation that includes overflow behavior that the majority of M365 cases use. Otherwise we get inconsistent implementations. It could be exported as a separate component like `OverflowTabList`, but it feels like it should be part of the tab list package.

Separately I tried messing with Overflow. It feels overly complicated, especially WRT the custom menu you need to create. The documentation doesn't really explain the steps to use it, so you have to reverse engineer the coding samples.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by tudorpopams** [comment]
I've assigned this issue to @microsoft/cxe-red so they can review and plan it accordingly.

**Comment by dmytrokirpa** [comment]
Thank you @dzearing for your feature request and the valuable feedback. We understand the need for a consistent overflow behavior in TabList implementations to ensure uniformity across M365 cases. However, integrating overflow directly into tabs would significantly increase the complexity and maintenance of the component API. Overflow functionality is designed to be flexible and is implemented through child TSX elements, allowing for customization based on specific needs. While we acknowledge that the current implementation may seem complicated, it provides the necessary flexibility for diverse scenarios. We aim to keep our components lean and maintainable, and thus, we encourage developers to implement overflow behavior as needed for their particular use case. We appreciate your understanding and will continue to explore ways to improve our documentation and examples to make the implementation process clearer.

cc @GeoffCoxMSFT

**Comment by dmytrokirpa** [comment]
Hi @dzearing, following further discussions with the team, we've concluded that integrating OverflowTabs into the core library without compromising customizability is not feasible. Therefore, we could build an extension for `OverflowTabList`, `OverflowTab`, and `OverflowMenu` within the [fluentui-contrib](https://github.com/microsoft/fluentui-contrib) repository, similar to what is demonstrated [here](https://stackblitz.com/edit/g5nl5m?file=src%2Fexample.tsx). 

Please let us know if this solution aligns with the use cases you've described.
