### ISSUE TITLE
[Bug]: Spinner embedded in button results in broken animation

### ISSUE THREAD

**Issue by nolanmsft** [microsoft/fluentui#31125]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-1280P
    Memory: 5.15 GB / 31.67 GB
  Browsers:
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-button-button--default#loading

## Reproduction
Click the "start loading" button under the button component docs for fluent 9. I've been able to reproduce this issue by embedding a spinner inside the button icon prop similar to the button loading docs and also by just putting a spinner inside a button component. 

## Actual Behavior
Embedding a spinner component in to the icon prop of a button results in a broken animation. 

## Expected Behavior
Normal spinner animation when a spinner is embedded inside a button. 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
I am able to repro it:

![2024-04-22 10 54 39](https://github.com/microsoft/fluentui/assets/14183168/fb000c9f-1e93-4d6d-a65a-11902f1bc2b6)
