### ISSUE TITLE
[Feature]: Dynamic Height Adjustment for Textareas Based on Content

### ISSUE THREAD

**Issue by A-ZHANG1** [microsoft/fluentui#31122]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

I'm requesting a feature that allows the height of a textarea to adapt dynamically based on its content, instead of having a fixed height or requiring a scrollbar. Currently, textarea elements don't provide a built-in mechanism to calculate their height based on their content. Please see the picture below for proposed interaction:

<img width="335" alt="image" src="https://github.com/microsoft/fluentui/assets/21293571/45da3f89-19dc-4410-aa7b-1b7f9d5e314a">

The implementation can be a method like `oncontentsizechanged` of react native.

### Have you discussed this feature with our team

_No_

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by layershifter** [comment]
_5 cents: I don't think that it should be built-in into the library._ However, it might a good component for contrib.

Today, it could be achieved by using `react-textarea-autosize` and our composition patterns, [Stackblitz example](https://stackblitz.com/edit/4ufrcp).

**Comment by A-ZHANG1** [comment]
Thank you. The challenging aspect lies in the initial appearance being restricted to a single line, akin to an <input> field, and transitioning to a <textarea> dynamically.

**Comment by A-ZHANG1** [comment]
Realized I can use `rows` to set the initial appearance of <textarea> to single line.
