### ISSUE TITLE
[Bug]: Tagpicker doesn't respect multiselect prop

### ISSUE THREAD

**Issue by ivonool** [microsoft/fluentui#31133]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 10.35 GB / 31.70 GB
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @fluentui/react: ^8.106.4 => 8.117.6
    @fluentui/react-components: 9.48.0 => 9.48.0
    @fluentui/react-tag-picker-preview: 0.3.1 => 0.3.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/4elmvh?file=src%2Fexample.tsx

## Actual Behavior
TagPickerList prop is set to: multiselect={false} 
According to documentation, it is false by default. Anyway you can still select multiple tags.

## Expected Behavior
Selection limited to one opt.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
This property does not make sense in the `TagPicker` component implementation and it'll probably be removed before any official release

**Comment by ivonool** [comment]
@bsunderhus I was trying to use it as People Picker. For some scenarios I need to limit the selection to one.

**Comment by bsunderhus** [comment]
> @bsunderhus I was trying to use it as People Picker. For some scenarios I need to limit the selection to one.

Gotcha, I'll be adding an example in the documentation on how to achieve that! 😁
