### ISSUE TITLE
[Bug]: Module not found error : Package path ./lib is not exported error after `reactview-build`

### ISSUE THREAD

**Issue by kipackjeongMS** [microsoft/fluentui#31163]
### Library

React / v8 (@fluentui/react)

### Are you reporting Accessibility issue?

None

### Reproduction

NA

## Actual Behavior
Getting error when did npm run build to build the react project. 

## Expected Behavior
Should be able to build the react project.

Hello team,
I'm coming from MS azure service team.
We have our react app that uses the @fluentui, and we are currently getting below error when we did `npm run build`
```
Module not found : error : Package path ./lib is not exported from package C:\Users\kipackjeong\Code\Portal\AppConfigPortalExtension\<ourservice>PortalExtension\Client\React\Views 
\node_modules\@fluentui\react 
(see exports field in C:\Users\kipackjeong\Code\Portal\<ourservice>PortalExtension\AppConfigPortalExtensi on\Client\React\Views\node_modules\@fluentui\react\package.json)
```

```json
//package.json
{
  "name": "reactviews",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "reactview-build --disabledExternedResources --outputDirectory ../../../Output/Content/Scripts/React/Views/",
    "build:dev": "reactview-build --development --disabledExternedResources --outputDirectory ../../../Output/Content/Scripts/React/Views/",
    "watch": "reactview-build --watch --development --disabledExternedResources --outputDirectory ../../../Output/Content/Scripts/React/Views/",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@azure/arm-appconfiguration": "^4.0.0",
    "@azure/arm-appinsights": "^5.0.0-beta.7",
    "@azure/arm-operationalinsights": "^9.0.0",
    "@azure/arm-storage": "^18.2.0",
    "@azure/monitor-query": "^1.1.1",
    "@fluentui/react": "^8.117.6",
    "@fluentui/react-charting": "^5.20.2",
    "@fluentui/react-components": "^9.47.5",
    "@microsoft/azureportal-reactview": "^12.321.0",
    "@microsoft/monitor-chart": "^1.3.3-build",
    "azure-app-configuration-sync": "0.0.4",
    "jwt-decode": "^4.0.0",
    "react-monaco-editor": "0.54.0"
  },
  "devDependencies": {
    "@microsoft/azureportal-reactview-tools": "^1.4.0",
    "ts-loader": "^9.5.1",
    "typescript": "~5.3.3"
  }
}
```

The error gets resolved when I modify the `@fluentui/react/package.json` manually like below.
![image](https://github.com/microsoft/fluentui/assets/133722803/6a979c55-d795-4b6f-ab7b-dae9c24b9ab3)

### Logs

```shell
Module not found : error : Package path ./lib is not exported from package C:\Users\kipackjeong\Code\Portal\AppConfigPortalExtension\<ourservice>PortalExtension\Client\React\Views 
\node_modules\@fluentui\react 
(see exports field in C:\Users\kipackjeong\Code\Portal\<ourservice>PortalExtension\AppConfigPortalExtensi on\Client\React\Views\node_modules\@fluentui\react\package.json)
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Imports from `@fluentui/react/lib` are not supported.

You should do either `import { X } from "@fluentui/react"` or, for example, `import { IButtonStyles } from '@fluentui/react/lib/Button';` (or other aliases from `package.json`).

**Comment by kipackjeongMS** [comment]
I understand that I will have to use that import convention when using components from the @fluentui/react.
But one of my dependencies, such as `@fluentui/react-charting` seems like importing `@fluentui/react/lib` and that maybe the cause of this error. Not sure which lib should have the fix for it. But this is our blocker.

**Comment by layershifter** [comment]
@kipackjeongMS `@fluentui/react-charting` is hosted in this repo. I cannot find `@fluentui/react/lib` in source code. In which file is it happening?
