### ISSUE TITLE
[Bug]: Commandbar responsiveness breaks when extra gap is introduced to primarySet

### ISSUE THREAD

**Issue by p-rk** [microsoft/fluentui#31187]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 12.43 GB / 31.88 GB
  Browsers:
    Edge: Chromium (123.0.2420.97), ChromiumDev (123.0.2420.10)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

React / v8 - Commandbar

## Actual Behavior
When gap/margin is introduced for the primarySet in the commandBar it breaks the responsiveness and the menu items in the commandbar overflows.

`export const customCommandBarStyles = {
    root: {
        height: '40px',
        paddingBottom: '2px',
        '.ms-OverflowSet-item': {
            height: '32px'
        },
        gridGap: '4px',
    },
    primarySet: {
        width: 'auto',
        gridGap: '4px', // this extra gap causing the overflow instead of showing more button in the commandbar
        overflow: 'hidden',
        margin: '0 4px',
        alignItems: 'center',
        '.ms-Button--commandBar': {
            borderRadius: '4px',
            minWidth: 'unset'
        }
    },
    secondarySet: {
        alignItems: 'center',
    }
};`

<img width="1913" alt="image" src="https://github.com/microsoft/fluentui/assets/30556391/ea772522-af94-467b-8dfa-f12357b435e1">

## Expected Behavior
When gap is introduced for the primarySet in the commandBar it should not break, it should show the more button instead of overflowing out of the window

### Requested priority

Blocking

### Products/sites affected

yes

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
please provide a reproduction via codepen, without repro this issue will be closed. thank you
