### ISSUE TITLE
[Feature]: Combobox typeahead

### ISSUE THREAD

**Issue by dhwanilc** [microsoft/fluentui#31188]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Request:
Have the fluent v9 combobox support typeahead feature to allow filtering from an external endpoint. Allow defining properties like debouncing timer after input, API endpoint to fetch new records, etc. 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by tudorpopams** [comment]
Hello @dhwanilc , did you had a chance to check my comment above and decide if it sounds as something feasible?
