### ISSUE TITLE
[Feature]: React-Experiments Pagination: Enable callout styling when combobox format is used.

### ISSUE THREAD

**Issue by p-saga** [microsoft/fluentui#31183]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Hi Team,
While using the Pagination component in the react-experiments folder, I noticed that the page numbers are not completely visible if the number of pages is very high.  At times, the Combobox callout's CSS tends to get affected by other styles in the application.

![image](https://github.com/microsoft/fluentui/assets/65545088/5ee1f2c8-700d-46a7-b5c3-ab9108ce18d4)

It will be helpful if the ComboBox callout's style option is also exposed outside like the ComboBox container style option ( highlighted in the below pic) so that a user can control the callout's styles even if other styles in the application affect it. 
![image](https://github.com/microsoft/fluentui/assets/65545088/07a71bc6-ce79-4e19-92b2-9b2c6ea356c2)

![image](https://github.com/microsoft/fluentui/assets/65545088/20cf87c7-a992-4a2b-a3a9-56582acc8655)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by khmakoto** [comment]
Hi @p-saga, the components inside of `react-experiments` are not officially supported and the team is not working on them anymore. If you'd like this functionality, feel free to create a PR adding it to the component.
