### ISSUE TITLE
Motion token values do not match theme values

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#31191]
### Describe the issue:
react-motions-preview has its copy of motion token values. Those currently differ:

#### Actual behavior:
Motion values:
https://github.com/microsoft/fluentui/blob/4ad395276e01a2a04df8f0263e1af2467310bcfd/packages/react-components/react-motions-preview/src/motions/motionTokens.ts#L9-L17

Theme tokens:
https://github.com/microsoft/fluentui/blob/4ad395276e01a2a04df8f0263e1af2467310bcfd/packages/tokens/src/global/curves.ts#L3-L13

#### Expected behavior:

The tokens should match each other. If we are ok with the copied tokens, we should have automation in place which will guarantee those would not diverge.

**Comment by robertpenner** [comment]
@miroslavstastny Thanks for filing this bug. I had noticed this divergence and addressed it in a larger prototyping branch: 
 https://github.com/microsoft/fluentui/pull/30736/commits/e8bd2da01d880451ad901601152cded568b5b5de
 I will be breaking it up into smaller PRs, one of which will address this easing curve issue.
