### ISSUE TITLE
[Feature]: For "DetailsList" component when multiline is on, add the ability to control the maximum number of lines

### ISSUE THREAD

**Issue by liquidserviceaccount** [microsoft/fluentui#31208]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### Describe the feature that you would like added

For "DetailsList" component when multiline is on, add the ability to control the maximum number of lines and the text should should ellipsis when it overflowing.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by Hotell** [comment]
are you sure the feature request is for react-northstar library ? if yes we don't support any new feature additions to it.
