### ISSUE TITLE
[Bug]: Width still is shown in the Skeletons storybook even though the width prop is depecated

### ISSUE THREAD

**Issue by snisonoff-microsoft-unmanaged** [microsoft/fluentui#31223]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
PR where width was deprecated: https://github.com/microsoft/fluentui/pull/31111
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-skeleton--default

## Actual Behavior
Storybook shows width as though it is a prop we are allowed to use

## Expected Behavior
Storybook should not show width, because the prop is deprecated

### Requested priority

Blocking

### Products/sites affected

TwoUI

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
This is actually a problem with all deprecated props in storybook in general, I've opened an uber issue to cover all of these in #31245. I'll close this issue in favor of that one.
