### ISSUE TITLE
[Bug]: Module not found: Error: Package path ./lib-amd is not exported from package

### ISSUE THREAD

**Issue by mrdrdocs** [microsoft/fluentui#31224]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
Currently, we are using the version of '@fluentui/react": "^8.41.2'. The npm run build is giving the below error while generating the production build.
Module not found: Error: Package path ./lib-amd is not exported from package.

Any inputs will be helpful to fix the issue.
```

### Are you reporting Accessibility issue?

None

### Reproduction

Sure

## Actual Behavior
fill this out
![Package not found](https://github.com/microsoft/fluentui/assets/82019400/cb05e82d-5765-4d64-9da1-68bfcc8f24bb)

## Expected Behavior
fill this out

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Imports from `@fluentui/react/lib-amd` are not supported:
- it's the same as just `@fluentui/react`
- AMD output is probably wrong if you're using a modern bundler

I suggest to fix imports and avoid `/lib-amd`. That's similar to https://github.com/microsoft/fluentui/issues/31163#issuecomment-2075015516.
