### ISSUE TITLE
[Bug]: In IOS, People picker fly out pannel is closing when user minimize the keypad & not able to select last user

### ISSUE THREAD

**Issue by linhu2020** [microsoft/fluentui#31248]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
NormalPeoplePicker does not work well in IOS. Cause we can not choose the last one suggestion. Just see the video.
```

### Are you reporting Accessibility issue?

no

### Reproduction

None

## Actual Behavior
People picker fly out pannel is closing when user minimize the keypad & not able to select last user.
## Expected Behavior
After click done in keyboard, the suggestion panel should not close and user can select the last suggestion by scrolling it.

https://github.com/microsoft/fluentui/assets/132728542/e9fd57c9-492e-4a1c-9412-5c25dd6af14a

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
hello, can you please provide reproduction via stackblitz ? otherwise this will be closed. ty
