### ISSUE TITLE
[Bug]: InfoLabel does not respect `mountNode` property

### ISSUE THREAD

**Issue by brhallin** [microsoft/fluentui#31242]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz
    Memory: 36.24 GB / 63.59 GB
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/4bnprj?file=src%2Fexample.tsx

## Actual Behavior
When clicked, the InfoLabel popover component should be attached to the DOM as a child of the element passed to the control, e.g.
```ts
<InfoLabel
  {...props}
  infoButton={{ popover: { mountNode: popoverRoot } }}
/>
```

## Expected Behavior
When clicked, the InfoLabel popover component is attached to the DOM as a sibling of its `<button>`.

Note that this behaviour was previously supported, albeit in a slightly different fashion, back when the component was simply known as `InfoButton`, via its `popover` property, e.g. `<InfoButton {...rest} popover={{ mountNode: popoverRoot }} />`.

In the provided minimal repro, we can see that the `mountNode` property provided does indeed point to a valid DOM element.

### Requested priority

Blocking

### Products/sites affected

PowerApps Canvas InfoButton component

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Shubhdeep12** [comment]
Hi @brhallin @Hotell can I try resolving this bug?

Based on my initial debugging looks like there are 2 issues - 

1. divRef.current in the code is passed as null only because after initial render and when divRef gets value, the component will not re-render.
2. Yes, the infoLabel is not working fine on passing mountNode in infoButton prop
  a. reason for this is infoLabel uses -> infoButton -> PopOver 
  b. PopOver surface uses Portal when surface is not inline.
  c. in useInfoButton.tsx we have default prop -> inline with default value as true. (this is causing the issue).
  d. either we should pass inline as false or inline should be false automatically when mountNode is passed.

**Comment by brhallin** [comment]
Thanks for investigating the issue and identifying the problem!
 
> We should either pass `inline` as `false` or have `inline` automatically set to false when `mountNode` is passed.

That's entirely up to the Fluent team, so I won't comment on the best decision. My team, however, now has a way forward -- we'll just add `inline: false` along with the `mountNode` prop, and we'll be unblocked.

🍻

**Comment by Shubhdeep12** [comment]
Sure but we are halfway.

on passing` inline: false` along with `mountNode` in `infoButton`, do create the `infoLabel` popover inside the `mountNode` element, but the positioning of the popover is still at `infoButton`.

Reference: popover is created and gets added in mountNode div element but still shown above the infoButton
![image](https://github.com/microsoft/fluentui/assets/43654389/15a73dbc-75ac-471c-bcbd-29b4a6327ca5)

**Comment by brhallin** [comment]
FWIW, in our use case, with the Canvas environment, the `mountNode` property we're providing points to a valid DOM element and with the addition of `inline: false`, it's now respecting that element.

<img width="609" alt="image" src="https://github.com/microsoft/fluentui/assets/99288637/b56cccc1-0c27-4ee2-bc63-b07bcfda864a">

**Comment by brhallin** [comment]
It's possible that the minimal demo I provided is faulty.

**Comment by mainframev** [comment]
@Shubhdeep12 @brhallin 

👋🏻 

It seems as no action needed in this case on our side, `mountNode` works and if you need to position the popover above the pink container as it says in the initial repro, you can use the `positioning.target`

```jsx
export const Default = (props: Partial<InfoLabelProps>) => {
  const buttonRef = React.useRef<HTMLButtonElement>(null);
  const [divRef, setDifRef] = React.useState<HTMLDivElement | null>(null);
  const [text, setText] = React.useState('');

  const updateText = () => {
    console.log(divRef);
    const t = divRef?.getAttribute('id') + ' ... ' + Math.random();
    setText(t);
  };

  React.useEffect(() => {
    updateText();
  }, [divRef]);

  const handleClick = () => {
    updateText();
  };

  return (
    <>
      <InfoLabel
        info={<>This text should pop up above the pink container.</>}
        {...props}
        infoButton={{
          popover: {
            mountNode: divRef,
            inline: false,
            open: true,
            positioning: {
              target: divRef,
            },
          },
        }}
      >
        Example label
      </InfoLabel>

      <div style={{ padding: '10px' }}>
        <span>{text}</span>
      </div>

      <div
        id="foo"
        ref={setDifRef}
        style={{
          padding: '20px',
          backgroundColor: '#f0f',
          position: 'absolute',
          top: '200px',
        }}
      >
        <button id="myButton" onClick={handleClick} ref={buttonRef}>
          click me
        </button>
      </div>
    </>
  );
};
```

![Screenshot 2024-08-07 at 0 26 51](https://github.com/user-attachments/assets/d5fa3cb9-8d23-48a3-a77e-940332732420)
