### ISSUE TITLE
[Bug]: react-tag-picker-preview : pressing space on keyboard causing pickier closing

### ISSUE THREAD

**Issue by pradeept95** [microsoft/fluentui#31259]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
NA
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/preview-components-tagpicker--default#freeform

## Actual Behavior
While searching, if you press space on keyboard, picker popover is closing. (It is happening on both normal or freeform picker)

## Expected Behavior
Should be able to type space while searching

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
This is expected behavior, as discussed with @adamsamec and others. After further investigations we've opted by having this behaviour, both `Space` and `Enter` keydown on an option will closed the dropdown and select the option.

**Comment by bsunderhus** [comment]
This PR https://github.com/microsoft/fluentui/pull/31316 modifies this behavior a bit
