### ISSUE TITLE
[Feature]: Can we have a paginated/Infinite scrolling ComboBox.

### ISSUE THREAD

**Issue by jbujula** [microsoft/fluentui#31261]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

When you do a Odata call and if the response contains more than 5000 records it usually gives a Odata.nextlink which is a URL that is used to fetch next set of items. So, in order to append those results to the dropdown we need a callback which triggers upon scrolling to bottom.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by Mitch-At-Work** [comment]
Hi there, as the combo box is composable the code to enable this would best be introduced app logic side.

Recommendation would be for users to render a non-interactive loading indicator as the final option in the combo box, attached to an IntersectionObserver callback (https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver) - this will notify users when the user has scrolled the loading indicator into view and give users full control over the visibility/refresh logic.

We also implement a Virtualized example for large lists to enable performant loading of large numbers of items: https://react.fluentui.dev/?path=/docs/components-combobox--default#virtualizer

**Comment by joeyfigaro** [comment]
For anyone else stumbling here, the current working link for the virtualizer example Mitch mentioned seems to be here: https://react.fluentui.dev/?path=/docs/components-combobox--docs#virtualizer

It doesn't currently seem to have working search, though. Searching for numbers in the (virtualized) list doesn't focus any of the options or scroll to them. Hitting enter, clicking, and hitting tab don't select option values either.
