### ISSUE TITLE
[Bug]: Tooltip scrolling issues with long text

### ISSUE THREAD

**Issue by msDestiny14** [microsoft/fluentui#31274]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

Edge

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/mper2n?file=src%2Fexample.tsx

### Bug Description

It would appear that when creating a tooltip with long text and setting the position to "after" there is an issue when scrolling the page.
(This happens if the tooltip is so long it extends past the bottom of the viewport) 

https://stackblitz.com/edit/mper2n?file=src%2Fexample.tsx

## Actual Behavior
Tooltip is stuck and properly scroll with page.

## Expected Behavior
Tooltip should scroll properly with the page. 

https://github.com/microsoft/fluentui/assets/67929198/01ad1181-86cf-4040-b4d7-eec4918aace7

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@msDestiny14 please use `autoSize: 'height'` or other `autoSize` values depending on the scenario in such cases, I updated your example: https://stackblitz.com/edit/mper2n-6wjl91?file=src%2Fexample.tsx,src%2Findex.tsx

You can find out more in docs about positioning https://react.fluentui.dev/?path=/docs/concepts-developer-positioning-components--default#auto-size-for-small-viewport.

**Comment by snisonoffMS** [comment]
@layershifter Please reopen this issue. We should not have to add styles for something that was already implemented for us in v8.

**Comment by layershifter** [comment]
@snisonoffMS there is no need to add styles, just tweak `positioning` prop.

For context, this functionality (`autoSize`) was not implemented from a day zero. While we would like to enable it by default, we consider enabling it as a breaking change. That's the reason why it's not enabled by default now.

**Comment by snisonoffMS** [comment]
@layershifter This leads to additional bugs such as long text that is supposed to appear on the right appearing on the bottom. We just want this to work the way it did in v8 please.
