### ISSUE TITLE
[Bug]: PeoplePicker suggestions inside a Dialog are displayed behind the Dialog

### ISSUE THREAD

**Issue by raymondroc** [microsoft/fluentui#31309]
### Library

React / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/wvtwmd?file=src%2Fexample.tsx

## Actual Behavior
When a PeoplePicker is located inside a Dialog, the list of suggestions appears behind the dialog (greyed out like the rest of the screen). Does not always occur the first time the dialog is shown but occurs consistently after the dialog is closed and reopened.

## Expected Behavior
The list of suggestions should appear above the dialog.
 
![image](https://github.com/microsoft/fluentui/assets/54997940/df25501b-6d03-4d89-b3fd-79a574e325ea)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
can you take a look at this one @bsunderhus  ? it's a cross library issue (v8 rendered inside v9)

**Comment by layershifter** [comment]
Please check https://react.fluentui.dev/?path=/docs/concepts-migration-from-v8-troubleshooting--page#i-tried-uing-a-layered-v8-component-like-callout-in-a-layered-v9-component-like-dialog-and-my-callout-appears-beneath-my-dialog-whats-going-on
