### ISSUE TITLE
Run Griffel codemod to remove usage of `shorthands.*()`

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#31318]
There is a PR to update `@griffel/*` packages (#31258).

Once it will be be merged, we should run codemod to remove usages of `shorthands.*()` and disabled ESLint rules.

**Comment by flora8984461** [comment]
@layershifter Thanks for making improvements on shorthands. We are upgrading fluentui v9 package and removing shorthands on our end as well. Wondering if borderWidth, borderColor and borderStyle are supported as of "^9.54.13"? Thank you!

**Comment by layershifter** [comment]
@flora8984461 you can find all details in this issue https://github.com/microsoft/griffel/issues/531 🐱
