### ISSUE TITLE
[Bug]: Dialog (v8) does not produce click events

### ISSUE THREAD

**Issue by krystofmatejka** [microsoft/fluentui#31320]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 21.66 GB / 31.18 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/krystof-matejka/pen/mdYdELr

## Actual Behavior
When I register click event handler `window.addEventListener('click', (e) => console.log('clicked on', e))` it does not produce events on elements, for example buttons, within `Dialog` component.

## Expected Behavior
I expect that click events will be produced even from `Dialog`.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Shubhdeep12** [comment]
Hi @kxmatejka is it working fine in v9? or in both v8 and v9?

**Comment by kxmatejka** [comment]
hello @Shubhdeep12 yes it works in v9. unfortunately, i cannot upgrade

demo: https://stackblitz.com/edit/dpihmf?file=src%2Fexample.tsx

**Comment by krystofmatejka** [comment]
hey, i have found the issue. you have to pass `layerProps.eventBubblingEnabled: true` to the `Dialog` component

**Before**
```
  const modalProps = React.useMemo(
    () => ({
      titleAriaId: labelId,
      subtitleAriaId: subTextId,
      isBlocking: false,
      styles: dialogStyles,
      dragOptions: isDraggable ? dragOptions : undefined,
    }),
    [isDraggable, labelId, subTextId],
  );
```

**After**
```
  const modalProps = React.useMemo(
    () => ({
      titleAriaId: labelId,
      subtitleAriaId: subTextId,
      isBlocking: false,
      styles: dialogStyles,
      dragOptions: isDraggable ? dragOptions : undefined,
      layerProps: {
        eventBubblingEnabled: true
      }
    }),
    [isDraggable, labelId, subTextId],
  );
```

Full example https://codepen.io/krystof-matejka/pen/mdYdELr
