### ISSUE TITLE
[Bug]: Required asterisk missing on contrast theme

### ISSUE THREAD

**Issue by karanbhandari** [microsoft/fluentui#31338]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
sh: 1: envinfo: not found
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield

## Actual Behavior
https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield
When user uses Aquatic contrast theme in windows, the Textfield with required label has the asterisk unreadable
![image](https://github.com/microsoft/fluentui/assets/13277201/417d0819-82f6-46ac-8666-4a8304ce3722)

In light mode it works as expected
![image](https://github.com/microsoft/fluentui/assets/13277201/3420c9e3-b9cf-481d-9824-e752370362af)

## Expected Behavior
Aquatic contrast theme should show the asteriks (*) for important Textfield

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Looking at it, it does seem to be working correctly:
![image](https://github.com/microsoft/fluentui/assets/5953191/7a33decb-84e3-4319-8e5c-437c0393baa5)
