### ISSUE TITLE
[Bug]: Overlay Drawer Component Does Not Restore Scroll Position When Closed

### ISSUE THREAD

**Issue by buzzo123** [microsoft/fluentui#31334]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 884.71 MB / 15.25 GB
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.19041.3636
```

### Are you reporting Accessibility issue?

None

### Reproduction

Overlay Drawer Component Does Not Restore Scroll Position When Closed

### Bug Description

**Issue Description:**

The overlay drawer component in the React library does not restore the scroll position of the page when closed. This issue can lead to users being stuck in a scrolled position, causing inconvenience and a poor user experience.

**Steps to Reproduce:**

1. Visit the documentation page for the overlay drawer component: [Overlay Drawer Component Documentation](https://react.fluentui.dev/?path=/docs/components-drawer--default)
2. Open the overlay drawer by interacting with the relevant UI element.
4. Close the overlay drawer by clicking on the close button or any other interaction method.
5. Notice that the page doesn't scroll anymore.

**Expected Behaviour:**

After closing the overlay drawer, the page should automatically restore to its scroll behaviour  before the drawer was opened.

**Actual Behaviour:**

The page's scroll position does not revert to its original state upon closing the overlay drawer. Users may remain stuck in the page, need a refresh to restore the scroll bar.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by marcosmoura** [comment]
This is a regression that we've caught and fixed. Should be available in the next release.
