### ISSUE TITLE
[Bug]: Menu with `openOnHover` does not restore focus in some cases

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#31344]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/zdyuuh-spevbr

## Actual Behavior
- Focus First Button using keyboard to observe focus indicator
- Hover any of the Menu-Trigger buttons to open menu
- Move mouse away and wait for menu to close
- Focus is lost, focus is on body

## Expected Behavior

- Focus is not lost

### Logs

```shell
N/A
```

### Requested priority

High

### Products/sites affected

Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
@mshoho to follow up on hover opening menus

@ling1726 to add documentation that this case needs to be handled in userland

**Comment by ling1726** [comment]
Fixed by https://github.com/microsoft/fluentui/pull/32840 as the menu now restores focus always to trigger
