### ISSUE TITLE
colorNeutralBackgroundCard and colorNeutralBackgroundCardHover seem to be swapped.

### ISSUE THREAD

**Issue by codysorgenfrey** [microsoft/fluentui#31354]
https://github.com/microsoft/fluentui/blame/c35e78e5853894033a69f6135ad003894a8b6a95/packages/tokens/src/alias/lightColor.ts#L128

I couldn't find a spec for these tokens, @miroslavstastny can you provide where they came from? They seem to be swapped, as the resting state is darker than the hover state which is odd for cards.

I also couldn't find any reference to them in the rest of the repo, are they being used for anything?

**Comment by miroslavstastny** [comment]
Discussed offline. Those tokens were added in #30037 and match the design spec. The card tokens are not used by the core library directly but in a higher layer shared across multiple applications.
