### ISSUE TITLE
[Bug]: calendar-compat UI bug in Teams High Contrast mode

### ISSUE THREAD

**Issue by kumarapoorva** [microsoft/fluentui#31375]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 117.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 124.0.6367.202
    Edge: 124.0.2478.97
    Safari: 17.4.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/p/sandbox/calendara-compat-teams-hc-m9t2yj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw75ecmz00063p6h2bz8d0hj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw75ecmz00023p6hppswz6ye%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw75ecmz00033p6h5bcj82ys%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw75ecmz00053p6hgiryzyt4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw75ecmz00023p6hppswz6ye%2522%253A%257B%2522id%2522%253A%2522clw75ecmz00023p6hppswz6ye%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clw75ecmz00053p6hgiryzyt4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw75ecmz00043p6h80tc8u6a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clw75ecmz00053p6hgiryzyt4%2522%252C%2522activeTabId%2522%253A%2522clw75ecmz00043p6h80tc8u6a%2522%257D%252C%2522clw75ecmz00033p6h5bcj82ys%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clw75ecmz00033p6h5bcj82ys%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

## Actual Behavior

In calendar-compat v9 component having overlaid month, Teams HC mode, hovering on Month-and-Year header makes text unreadable as both background and text become black

## Expected Behavior

In Teams HC mode, hovering on Month-and-Year header should not make text unreadable 

### Requested priority

High

### Products/sites affected

Loop in Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Shubhdeep12** [comment]
yeah it looks like a valid bug
and looks like the values of `colorBrandBackground2` and `colorNeutralForeground1Hover` is  set to #000000 for the teamsHighContrast theme here in this file - https://github.com/microsoft/fluentui/blob/1cc1aa39132593d2ee1efcb711ba43cde3e412ec/packages/tokens/src/alias/highContrastColor.ts

cc @layershifter  @Hotell
