### ISSUE TITLE
[Bug]: react-charting dependency on d3 is on an old major (d3-time), causing dupes downstream

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#31397]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
all.
```

### Are you reporting Accessibility issue?

None

### Reproduction

check package.json

## Actual Behavior

loop uses react-charting. They also use d3-time v3. React-charting's dependencies are out of date.

## Expected Behavior

d3 deps are all updated to the latest major version.

### Requested priority

Normal

### Products/sites affected

loop

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by AtishayMsft** [comment]
@dzearing Please provide details about what issue is being caused by package duplication for loop product.
