### ISSUE TITLE
[feature: web-components]: Convert Checkbox to use ElementInternals

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fluentui#31399]
### Describe the issue:
This issue exists to track converting the web-component checkbox to use `ElementInternals` rather than the current FormAssociation behavior.

As part of this change, we should:
- Get the DOM as clean and light as possible
- Strip as much duplication of observed ARIA attributes out of the control
- Ensure the control reads as expected from assistive technology
- Add tests to validate the control participates in form association as expected by the platform.

**Comment by radium-v** [comment]
Completed in #31468.
