### ISSUE TITLE
[Bug]: React testing library tests are failing intermittently after the fluent v9 update to 9.50.0

### ISSUE THREAD

**Issue by nanivijay** [microsoft/fluentui#31394]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.26217
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13800H
    Memory: 39.80 GB / 63.83 GB
  Browsers:
    Edge: Chromium (126.0.2566.1), ChromiumDev (126.0.2566.1)
    Internet Explorer: 11.0.26217.5000

Node Version: v20
Jest Version: 29.5.6
@testing-library/react: 12.1.5
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://msazure.visualstudio.com/OneAgile/_build/results?buildId=93748799&view=logs&j=a11cdf60-0d11-5130-c801-1b4953009464

## Actual Behavior
 React testing library tests are failing intermittently after the fluent v9 update to 9.50.0
` <body
      data-tabster="{\"root\":{}}"
      style="--tabster-root: ztbcjb1a72b79mdfn41ldyhd0|1|lw9e5aev,;"
    >
      <i
        aria-hidden="true"
        data-tabster-dummy="isFirst=true, isOutside=false, (Root, tabbable=true)"
        role="none"
        style="position: fixed; height: 1px; width: 1px; opacity: 0.001; z-index: -1; top: 0px; left: 0px;"
        tabindex="0"
      />
      <div
        aria-hidden="true"
      />
      <i
        aria-hidden="true"
        data-tabster-dummy="isFirst=false, isOutside=false, (Root, tabbable=true)"
        role="none"
        style="position: fixed; height: 1px; width: 1px; opacity: 0.001; z-index: -1; top: 0px; left: 0px;"
        tabindex="0"
      />
    </body>`

Node: 
## Expected Behavior
Tests should pass. The tests were successfully running on fluent ui version `9.42.0`
I am not seeing the issue if I run single test.

### Requested priority

High

### Products/sites affected

Power Platform Admin Center

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by marcosmoura** [comment]
@nanivijay Can you please provide the output that react testing library gives in your Terminal? The info you provided is not enough for us to know what the problem could be.

**Comment by 15MariamS** [comment]
I'm also getting this error after the upgrade — specifically, none of the dialogs "close" in the jest test
