### ISSUE TITLE
[Bug]: unable to focus elements in dialog 1 after dialog 2 is opened on top of it and then dismissed

### ISSUE THREAD

**Issue by angelo-mollame** [microsoft/fluentui#31421]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 1.62 GB / 15.92 GB
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

None

### Reproduction

Error while trying to create repro link (explaination below)

## Actual Behavior
I click on a button that opens Dialog 1.
On Dialog 1, I click on another button, which opens Dialog 2 on top of Dialog 1.
On Dialog 2, I click on another button, which dismissed Dialog 2.
Now I am back on Dialog 1, and I click on a textbox in it, but I can't get to keep the focus.

## Expected Behavior
The textbox in Dialog 1 should be focusable.

--------------------------

This seems to be the same issue as https://github.com/microsoft/fluentui/issues/26824, which has been closed and declared fixed, but for some reason I am still experiencing it.

--------------------------

I tried creating a setup in CodeSandbox, but for some reason I am getting this error:

![image](https://github.com/microsoft/fluentui/assets/1851952/81b6e60f-4c41-4dfd-b783-35b68fd35c36)

So sharing the repro code here:
- In package.json, reference "@fluentui/react-components": "9.47.0"
- Use this code in `index.tsx`:

```
import ReactDOM from "react-dom/client";

import { App } from "./App";

const root: ReactDOM.Root = ReactDOM.createRoot(document.getElementById("root") as HTMLElement);

root.render(<App />);
```

- Use this code in `App.tsx`:

```
import {
    Button,
    Dialog,
    DialogBody,
    DialogSurface,
    FluentProvider,
    webLightTheme,
    Input,
    DialogTitle,
    DialogContent,
} from "@fluentui/react-components";
import * as React from "react";

export const App: React.FunctionComponent = () => {
    const [isDialog1Open, setDialog1Open] = React.useState<boolean>();
    const [isDialog2Open, setDialog2Open] = React.useState<boolean>();

    return (
        <FluentProvider theme={webLightTheme}>
            <Button onClick={() => setDialog1Open(true)}>Open dialog 1</Button>
            {isDialog1Open && (
                <Dialog open={true}>
                    <DialogSurface>
                        <DialogBody>
                            <DialogTitle>Dialog 1</DialogTitle>
                            <DialogContent>
                                <Input />
                                <Button onClick={() => setDialog2Open(true)}>Open dialog 2</Button>
                            </DialogContent>
                        </DialogBody>
                    </DialogSurface>
                </Dialog>
            )}
            {isDialog2Open && (
                <Dialog open={true}>
                    <DialogSurface>
                        <DialogBody>
                            <DialogTitle>Dialog 2</DialogTitle>
                            <Button onClick={() => setDialog2Open(false)}>Close</Button>
                        </DialogBody>
                    </DialogSurface>
                </Dialog>
            )}
        </FluentProvider>
    );
};
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ValentinaKozlova** [comment]
Hello @angelo-mollame, looks like it's the same issue: #27914
@layershifter shared working example: https://codesandbox.io/s/sleepy-panka-mi47vo?file=/main.tsx

For more details: https://github.com/microsoft/fluentui/issues/27914#issuecomment-1559520738

**Comment by angelo-mollame** [comment]
From the comment in 27914, it seems like the fact that the focus is not automatically restored on dialog dismiss is a result of not using triggers. That part is reasonable.

But the problem here is that not only the focus is not automatically restored. If the user clicks on the textbox to restore the focus manually, that doesn't work either. Something is just preventing that textbox from regaining the focus even after an explicit click.

Is this second part of the behavior also by design, if triggers are not used?

I would be ok not having the focus auto-restores, if clicks at least worked to bring the focus back.

**Comment by ValentinaKozlova** [comment]
> From the comment in 27914, it seems like the fact that the focus is not automatically restored on dialog dismiss is a result of not using triggers. That part is reasonable.
> 
> But the problem here is that not only the focus is not automatically restored. If the user clicks on the textbox to restore the focus manually, that doesn't work either. Something is just preventing that textbox from regaining the focus even after an explicit click.
> 
> Is this second part of the behavior also by design, if triggers are not used?
> 
> I would be ok not having the focus auto-restores, if clicks at least worked to bring the focus back.

Have you tried the solution from https://codesandbox.io/s/sleepy-panka-mi47vo?file=/main.tsx? Everything works there.
What about second issue, I saw that, I'll ask the author if whether it's expected

**Comment by bsunderhus** [comment]
>Is this second part of the behavior also by design, if triggers are not used?

It is not. You're basically getting locked out of the modalizer here @mshoho, maybe we could have a solution for this?

> I would be ok not having the focus auto-restores, if clicks at least worked to bring the focus back.

This is not ok on a11y side, focus should never be lost! Ideally, if you don't want to use the trigger you could follow our documentation on how to leverage [useRestoreFocusTarget](https://react.fluentui.dev/?path=/docs/components-dialog--default#trigger-outside-dialog) to substitute the trigger (this is basically what the trigger is using internally)

**Comment by angelo-mollame** [comment]
Thanks for the pointers.

My understanding is that the approach of `restoreFocusTargetAttribute` and `useRestoreFocusTarget` shown [here](https://stackblitz.com/run?file=src%2Fexample.tsx):
- requires knowing in advance (and hardcoding) for each specific first dialog that may suffer from this issue what element is going to be the recipient of the focus once the second dialog is dismissed
- doesn't allow to have the focus automatically restored to whatever element in the first dialog had the focus when the second dialog appeared (you have to pick one)

Please let me know if I've missed something.

I was hoping for a more automatic solution than that.
I ended up addressing this problem with the following code, in case it may help others that encounter the same issue.

I have a `RefDialog` component:

```
import * as React from "react";

export interface IRefDialog<TDialogProps> {
    show: (props: TDialogProps) => void;
    updateProps: (updater: (props: TDialogProps | undefined) => TDialogProps | undefined) => void;
}

export function RefDialog<TDialogProps>(refDialogProps: {
    dialog: React.FunctionComponent<TDialogProps & { hideDialog: () => void }>;
    dialogRef: React.MutableRefObject<IRefDialog<TDialogProps> | undefined>;
}): React.ReactElement | null {
    const [dialogProps, setDialogProps] = React.useState<TDialogProps>();
    const focusRestoreElementRef: React.MutableRefObject<HTMLElement | undefined> = React.useRef();

    React.useImperativeHandle(refDialogProps.dialogRef, () => ({
        show,
        updateProps: setDialogProps,
    }));

    function hideDialog(): void {
        setDialogProps(undefined);
        focusRestoreElementRef.current?.focus();
    }

    function show(props: TDialogProps): void {
        focusRestoreElementRef.current = document.activeElement as HTMLElement;
        setDialogProps(props);
    }

    if (dialogProps) {
        const TDialog: React.FunctionComponent<TDialogProps & { hideDialog: () => void }> = refDialogProps.dialog;

        return <TDialog {...dialogProps} hideDialog={hideDialog} />;
    }

    return null;
}
```

I can consume this component like this:
- Example of custom dialog
```
export const MessageDialog: React.FunctionComponent<MessageDialogProps & { hideDialog: () => void }> = props => {
    ...
}
```
- Example of consumption of the custom dialog
```
    const messageDialogRef: React.MutableRefObject<IRefDialog<MessageDialogProps> | undefined> = React.useRef();

    function showMessageDialog(messageDialogProps: MessageDialogProps): void {
        messageDialogRef.current?.show(messageDialogProps);
    }

    return (
        <>
            <other rendering code here.../>
            <RefDialog dialog={MessageDialog} dialogRef={messageDialogRef} />
        </>
    );
```

This solution seems to work well.
Let me know if you have any thoughts.
