### ISSUE TITLE
[Bug]: Combobox style

### ISSUE THREAD

**Issue by Fn4ch** [microsoft/fluentui#31433]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Combobox style: align-self: stretch;
Right version: align-self: center;
```

### Are you reporting Accessibility issue?

yes

### Reproduction

no message

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/71707224/de10675f-92c4-4eeb-a260-a1d8ac17e697)
align-self: stretch

## Expected Behavior
align-self: center
![image](https://github.com/microsoft/fluentui/assets/71707224/ea0b6291-b1db-442d-91a6-553dd5f7f1d3)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ValentinaKozlova** [comment]
Hello @Fn4ch , could you please provide system info? What browser do you use?
I can't reproduce it. Tried on Chrome, Edge and Firefox.
![image](https://github.com/microsoft/fluentui/assets/11574680/f3c60d66-ab5c-4c58-91d0-27afabe3b671)

**Comment by Fn4ch** [comment]
> Hello @Fn4ch , could you please provide system info? What browser do you use? I can't reproduce it. Tried on Chrome, Edge and Firefox. ![image](https://private-user-images.githubusercontent.com/11574680/332428249-f3c60d66-ab5c-4c58-91d0-27afabe3b671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzg5NzEsIm5iZiI6MTcxNzA3ODY3MSwicGF0aCI6Ii8xMTU3NDY4MC8zMzI0MjgyNDktZjNjNjBkNjYtYWI1Yy00YzU4LTkxZDAtMjdhZmFiZTNiNjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE0MTc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MzdiMmVmOWEzMzc5OWMwMmQ3ZjE1ODgyNThlZTQxNTMzN2FkMmQ1Mzc1YjNjOGFlMDc2ZDczYzI2ZmQxNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u8OVLTWBccpdIqvfCi-9JGZxsSvxhKTbJZ1dMu_4-Ds)

Im using Chrome 125.0.6422.78, and i got this problem everywhere
SpinButton example:
![image](https://github.com/microsoft/fluentui/assets/71707224/94711e55-0d46-4a38-a237-21506420c546)

**Comment by ValentinaKozlova** [comment]
> > Hello @Fn4ch , could you please provide system info? What browser do you use? I can't reproduce it. Tried on Chrome, Edge and Firefox. ![image](https://private-user-images.githubusercontent.com/11574680/332428249-f3c60d66-ab5c-4c58-91d0-27afabe3b671.png?

Could you please send codesandbox or codepen example of how you use the component? Because it's not reproducible on our side

**Comment by Fn4ch** [comment]
![image](https://github.com/microsoft/fluentui/assets/71707224/d43bf3dd-44d3-4a5c-be2a-f02fd0adce43)
Win 10 pro

deps:
react and etc
  "@fluentui/react-components": "^9.53.0",
  "@fluentui/react-icons": "^2.0.237",
  "@storybook/react": "^8.0.9",
  "@storybook/react-vite": "^8.0.9",
  
  
This component (Combobox) is shown through the storybook

My component:
```
import * as React from "react"
import { useState, useEffect } from "react"
import {
  Combobox,
  makeStyles,
  shorthands,
  useId,
  useComboboxFilter
} from "@fluentui/react-components"
import type { ComboboxProps } from "@fluentui/react-components"
import { MultipleComboboxProps } from "@/shared/models"

const useStyles = makeStyles({
  root: {
    display: "grid",
    gridTemplateRows: "repeat(1fr)",
    justifyItems: "start",
    ...shorthands.gap("2px"),
    maxWidth: "400px",
  },
})

const MultipleCombobox = (props: MultipleComboboxProps) => {
  const {
    options = [],
    placeholder = '',
    labelTitle = '',
    selectedValue = [],
    onSelectOptionsChange
  } = props

  const comboId = useId("combo-source")
  const selectedListId = `${comboId}-selection`
  const [value, setValue] = useState('')
  const styles = useStyles()

  const onSelect: ComboboxProps["onOptionSelect"] = (event, data) => {
    onSelectOptionsChange(data.selectedOptions)
    setValue("")
  }

  useEffect(() => {
    if(selectedValue.length === 0){
      setValue('')
    }
  }, [selectedValue])

  const children = useComboboxFilter(value, options, {
    noOptionsMessage: "Nothing was found for your request",
  })

  const onFocus = () => {
    setValue("")
  }

  const onBlur = () => {
    setValue(selectedValue.join(", "))
  }

  const onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setValue(event.target.value)
  }

  useEffect(() => {
    const comboboxes = document.querySelectorAll('[role="combobox"]')
    comboboxes.forEach(c => c.classList.remove('f1ub7u0d'))
  }, [])

  return (
    <div className={styles.root}>
      <label id={comboId}
        style={{fontWeight: 600}}
      >{labelTitle}</label>
      <Combobox
        aria-labelledby={comboId}
        multiselect
        placeholder={placeholder}
        selectedOptions={selectedValue}
        value={value}
        onBlur={onBlur}
        onChange={onChange}
        onFocus={onFocus}
        onOptionSelect={onSelect}
        {...props}
      >
        {children}
      </Combobox>
    </div>
  )
}

export default MultipleCombobox
```
Im using useEffect, to delete style: allign-self: stretch
