### ISSUE TITLE
TagPicker needs to filter items when TagPickerOption contains children other then Text (control or only string). 

### ISSUE THREAD

**Issue by ravindersharma** [microsoft/fluentui#31431]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Current working : When we use the options as string Array in TagPicker, pass TagPickerOption  as Given below its filter feature working fine. 
` <TagPickerOption
                    secondaryContent="Microsoft FTE"
                    media={
                      <Avatar
                        shape="square"
                        aria-hidden
                        name={option}
                        color="colorful"
                      />
                    }
                    value={option}
                    key={option}
                  >
                    {option}
                  </TagPickerOption>`

Needed Feature: In case we are using an object Array or even string Array an pass a Persona Control as children for TagPickerOption it stops filtering item. 

Expected Issue:  Since current working example have String Array and Have Text as children for TagPickerOption it search easily. but in Persona case we don't have any text property for TagPickerOption to pass. In  that case it stops working. 
`  <TagPickerOption value={option} key={option}>
                    <Persona
                      avatar={{
                        color: 'colorful',
                        'aria-hidden': true,
                      }}
                      name={option}
                      secondaryText="Microsoft FTE"
                    />
                  </TagPickerOption>`

Please check Following example for clarity:
[https://stackblitz.com/edit/sknhsb-7t6uwy?file=src%2Fexample.tsx](https://stackblitz.com/edit/sknhsb-7t6uwy?file=src%2Fexample.tsx)

Here is Related issue : [https://github.com/microsoft/fluentui/issues/26652](https://github.com/microsoft/fluentui/issues/26652)

 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by bsunderhus** [comment]
I'm not sure I follow what do you mean by filtering in the example you provided, there's no filtering happening anywhere...

Do you mean that the focus is not properly focusing in the `TagPickerOption` that is the closest to the provided input?

**Comment by ravindersharma** [comment]
Hi @bsunderhus , yes  you are right, here I mean filtering feature is, what currently shown as Focus for TagPicker when you search for any user name in example code. For example,  if you type **Ja** you will get "Jane Doe" user focused in "Select Employees with Text" TagPicker.

![image](https://github.com/microsoft/fluentui/assets/10610076/3da6aee4-9102-4f31-9ca5-66d6d8936cb6)


But if you do same in "Select Employees With Persona" TagPicker you will get no Focused options. 

![image](https://github.com/microsoft/fluentui/assets/10610076/f7e42b3f-5987-4174-b8d5-6c150c5732c0)

**Comment by pradeept95** [comment]
Hi @bsunderhus , Combobox have text props in there option to handle complex option scenario but TagPickerOption lags that. I think this is the main reason we are seeing this warning in console.

https://react.fluentui.dev/?path=/docs/components-combobox--default#complex-options

![image](https://github.com/microsoft/fluentui/assets/28040299/60b61cad-609a-4cc3-b61d-417b3d17b4d3)

![image](https://github.com/microsoft/fluentui/assets/28040299/bfb67bde-9a0d-4ff0-99b3-d4e1069e9ce6)

**Comment by bsunderhus** [comment]
> Hi @bsunderhus , Combobox have text props in there option to handle complex option scenario but TagPickerOption lags that. I think this is the main reason we are seeing this warning in console.
> 
> I believe it is main reason for the above issue as well.
> 
> https://react.fluentui.dev/?path=/docs/components-combobox--default#complex-options
> 
> ![image](https://private-user-images.githubusercontent.com/28040299/333236023-60b61cad-609a-4cc3-b61d-417b3d17b4d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDQzNzUsIm5iZiI6MTcxNjU0NDA3NSwicGF0aCI6Ii8yODA0MDI5OS8zMzMyMzYwMjMtNjBiNjFjYWQtNjA5YS00Y2MzLWI2MWQtNDE3YjNkMTdiNGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA5NDc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViODAxNjNmYTBkYjQ5Y2JiYzQxOTdkZjliOTYwMjViNzhmNzMzNmYzMjRmMTMxYTU4ZmM1NjRiOWZmYWVlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.laImGO5SpYcNUvWRn87xaliC4hQRNIo9SYJnbu8Fsls)
> 
> ![image](https://private-user-images.githubusercontent.com/28040299/333235363-bfb67bde-9a0d-4ff0-99b3-d4e1069e9ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDQzNzUsIm5iZiI6MTcxNjU0NDA3NSwicGF0aCI6Ii8yODA0MDI5OS8zMzMyMzUzNjMtYmZiNjdiZGUtOWEwZC00ZmYwLTk5YjMtZDRlMTA2OWU5Y2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA5NDc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhODk4NWU5OWU4YzNkZmE5MGYyNTU3Njg2OTA5MjA0NjQzYWJkZDBiZTM5M2IyNDY4MWYwMmJmMGU3ZTU1MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HOZzBoojwd-16F-MzzE_znJdWBZC5MtZnXz9bix6ftk)

I am aware of that property @pradeept95, it's just that I don't think it's necessary. The `TagPickerOption` should be able to focus on the content based on the text string inside of elements.

Here's an [example from `Tree` component](https://stackblitz.com/edit/t38ark?file=src%2Fexample.tsx), which has typeahead verification (if you type the first letter of an item it should focus on that item), and it doesn't matter if you wrap the text content inside another node
