### ISSUE TITLE
[Bug]:  Related to the Table rendering in Chrome and other browser

### ISSUE THREAD

**Issue by coder-002** [microsoft/fluentui#31446]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 6.7 Fedora Linux 39 (Workstation Edition)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 8.76 GB / 15.35 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/

## Actual Behavior
The fluent ui datagrid is not rendering properly in chrome. As I was using single select in Datagrid component it is pushing the row forward.
![Screenshot from 2024-05-22 13-48-11](https://github.com/microsoft/fluentui/assets/72916247/15e0d677-1e9e-4e73-a561-68864e3d0189)
In above picture the radio button is pushing the content to right 

## Expected Behavior
But same as thing rendering in firefox is working well 
![image](https://github.com/microsoft/fluentui/assets/72916247/1031cd77-9196-429d-8440-e53b40d0c8fc)

In above picture the radio button is not pushing the content but has its own column I believe.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ValentinaKozlova** [comment]
Hello @coder-002 , could you please add a working link to reproduce this issue?

**Comment by coder-002** [comment]
Actually you can run datagrid with single select which is found in documentation it self.
