### ISSUE TITLE
[Bug]: useComboboxFilter filters the value not the text

### ISSUE THREAD

**Issue by sven-pohl** [microsoft/fluentui#31464]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
OS: Linux 5.15 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (16) x64 AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics
    Memory: 6.50 GB / 11.52 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
```

### Are you reporting Accessibility issue?

None

### Reproduction

import { Combobox, makeStyles, useComboboxFilter, useId, type ComboboxProps } from '@fluentui/react-components';
import * as React from 'react';

const useStyles = makeStyles({
    root: {
        // Stack the label above the field with a gap
        display: 'grid',
        gridTemplateRows: 'repeat(1fr)',
        justifyItems: 'start',
        gap: '2px',
        maxWidth: '400px',
    },
});

const options = [
    { children: 'Alligator', value: '1' },
    { children: 'Bee', value: '2' },
    { children: 'Bird', value: '3' },
    { children: 'Cheetah', disabled: true, value: '4' },
    { children: 'Dog', value: '5' },
    { children: 'Dolphin', value: '6' },
    { children: 'Ferret', value: '7' },
    { children: 'Firefly', value: '8' },
    { children: 'Fish', value: '9' },
    { children: 'Goat', value: '10' },
    { children: 'Horse', value: '11' },
    { children: 'Lion', value: '12' },
];

export const ComboboxIssue = () => {
    const comboId = useId();
    const styles = useStyles();

    const [query, setQuery] = React.useState<string>('');
    const children = useComboboxFilter(query, options, {
        noOptionsMessage: 'No animals match your search.',
    });
    const onOptionSelect: ComboboxProps['onOptionSelect'] = (e, data) => {
        setQuery(data.optionText ?? '');
    };

    return (
        <div className={styles.root}>
            <label id={comboId}>Best pet</label>
            <Combobox
                onOptionSelect={onOptionSelect}
                aria-labelledby={comboId}
                placeholder="Select an animal"
                onChange={(ev) => setQuery(ev.target.value)}
                value={query}
            >
                {children}
            </Combobox>
        </div>
    );
};

## Actual Behavior
`{ children: 'sometext', value: 'c9e0165d-6538-4300-aaf3-94c5b7f01fb7' }`
The combobox component displays the "children" property as selectable option. The useComboboxFilter hook does use the "value" property for filtering. If the "value" property is set to e.g. a guid (which is very likely in data driven applications) the user has to type the guid to get the combobox filtered .

## Expected Behavior
The filter is using the same property as displayed to the user for filtering (children).

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ValentinaKozlova** [comment]
Hello @sven-pohl , could you please provide a link for reproduction e.g. on codesanbox or stackblitz?

**Comment by sven-pohl** [comment]
> Hello @sven-pohl , could you please provide a link for reproduction e.g. on codesanbox or stackblitz?

Here you go: https://stackblitz.com/edit/vitejs-vite-4hacxy?file=src%2FComboboxIssue.tsx

**Comment by sven-pohl** [comment]
> Looks like it's expected behavior. But I'll double-check

Try the stackblitz. I hope this is not expected. In real life applications in any kind of select field you have a text and a value which often is an ID.

**Comment by sven-pohl** [comment]
> Presented here a possible work around for this issue.
> 
> Provide a custom function for `optionToText`. This function accounts for the text values only being in the `children` property, allowing keys to be in the value property.
> 
> I have a Codesandbox example here:
> 
> https://codesandbox.io/p/github/JoseHerminioCollas/gatsby-fluent9/main
> 
> @sven-pohl Is this the expected action of the ComboboxFilter?

Yes, exactly. That's what I expect it to work,

**Comment by ling1726** [comment]
There is an `optionText` API that can be used to set a user defined field for filter text. Here's an example on how it could be used https://stackblitz.com/edit/nhpsvt?file=src%2Fexample.tsx
