### ISSUE TITLE
[Bug]: TagPicker filter not work as expected 

### ISSUE THREAD

**Issue by hoangducdev** [microsoft/fluentui#31472]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1355U
    Memory: 17.23 GB / 39.68 GB
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.19041.4355
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/5ehij2?file=src%2Fexample.tsx

## Actual Behavior
I've modified the options to make it have some value duplicated. Then when I enter the "/". It is not filter correctly

## Expected Behavior
only display 'We couldn't find any matches'

![image (1)](https://github.com/microsoft/fluentui/assets/19942805/e24f9f93-ca40-4fa8-a8e4-67e9749b06f5)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
Looks like a duplicate from https://github.com/microsoft/fluentui/issues/31431
