### ISSUE TITLE
[Bug]: Apply tooltip for split button is not accessible afterwards 

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#31485]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 17.56 GB / 31.74 GB
  Browsers:
    Edge: Chromium (125.0.2535.51)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/wcqpul-jchfh8?file=src%2Fexample.tsx

### Bug Description

Repro steps:
1. Run NVDA
2. Navigate to the code sandbox: https://stackblitz.com/edit/wcqpul-jchfh8?file=src%2Fexample.tsx
3. use TAB key to navigate into "chevron" in split button 

## Actual Behavior
NVDA narration: "Example  menu button  collapsed  subMenu "

Observation:
The aria-label from tooltip is propagated to the button but there is still  `aria-labelledby` which cannot be overridden...  and then screen reader doesn't narrate aria-label but only aria-labelledby... 

![image](https://github.com/microsoft/fluentui/assets/22620150/4ba9c2c7-8536-47b1-9c4c-0c56cfebf1e5)

## Expected Behavior
NVDA narration: "More options button  collapsed  subMenu "

**Comment:**
We may do something wrong in our implementation, so please if there is some solution how to reach this please add example to the docsite.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment]
@kolaps33 hi 👋🏻 

I can't check it right now with NVDA, but with voiceover it seems to be working right, if pass aria-label straight to menuButton slot, not the children. Can you check if this behaviour is what you need? 

```tsx
import * as React from 'react';
import {
  Menu,
  MenuItem,
  MenuList,
  MenuPopover,
  MenuTrigger,
  SplitButton,
  Tooltip,
} from '@fluentui/react-components';
import type { MenuButtonProps } from '@fluentui/react-components';

const onClick = () => alert('Primary action button clicked.');

const primaryActionButtonProps = {
  onClick,
};
export const Default = () => (
  <Menu positioning="below-end">
    <MenuTrigger disableButtonEnhancement>
      {(triggerProps: MenuButtonProps) => (
        <SplitButton
          menuButton={{
            'aria-label': 'more options',
            children: (Component, props) => (
              <Tooltip content="more options" relationship="label">
                <Component {...props} {...triggerProps} />
              </Tooltip>
            ),
          }}
          primaryActionButton={primaryActionButtonProps}
        >
          Example
        </SplitButton>
      )}
    </MenuTrigger>

    <MenuPopover>
      <MenuList>
        <MenuItem>Item a</MenuItem>
        <MenuItem>Item b</MenuItem>
      </MenuList>
    </MenuPopover>
  </Menu>
);
```

![Image](https://github.com/user-attachments/assets/75574d37-1615-4012-90e2-9e6577e385d9)
