### ISSUE TITLE
[Bug]: 'Single pointer action alternative' Not provided for the draggable control between the column headers

### ISSUE THREAD

**Issue by xiaoyangliu1123** [microsoft/fluentui#31507]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 11.61 GB / 31.72 GB
  Browsers:
    Edge: Chromium (124.0.2478.97)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/xiaoyangliu1123/pen/LYoxpBE

## Actual Behavior
The headers of the DetailList component can have their width modified by clicking and dragging the vertical line between two headers:
![image](https://github.com/microsoft/fluentui/assets/152237890/2e3fac16-6548-48d0-a937-e97c7876d177)
But 'Single pointer action alternative' is not provided for the draggable control between the column headers.

## Expected Behavior
Specifically, a "single pointer action alternative" refers to providing an alternative method for users who cannot use a mouse or touch screen. For instance, users should be able to adjust column widths using keyboard actions. However, the current control does not offer such an alternative, making it potentially inconvenient for some users.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@xiaoyangliu1123 This example demonstrates how to [configure resize via keyboard](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/keyboardcolumnreorderresize).
