### ISSUE TITLE
[Feature]: `KeyTipLayer` add ability to invoke keytips after certain amount of time

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#31500]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

I'd like to be able to have keytips invoked after I hold down the start sequence key(s) for a certain amount of time. For example, if the start sequence key is `Alt` I'd like to be able to hold down the `Alt` key for 2 seconds and at that point have keytips displayed. This allows users to signal clear intent that they want keytips to be shown.

A rough sketch of the API:

```ts
interface IKeytipLayerProps {
  /**
   * Time in milliseconds that KeyTip start sequence must be held
   * to activate keytips.
   * Values < 0 disable the feature
   * @default -1
   */
  keytipConfirmationTime: number? = -1;

  // ... other props ...
}

```

### Have you discussed this feature with our team

@spmonahan

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by mainframev** [comment]
@spmonahan Hi 👋🏻  

I guess we can close it, considering, that v8 is in fix-maintenance mode and v9 Keytips are in development. I've added this feature to v9 in contrib.
