### ISSUE TITLE
[Bug]: V9 Combobox doesn't keep its state when multiple comboboxes are on the page

### ISSUE THREAD

**Issue by irinatarn** [microsoft/fluentui#31513]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 5.37 GB / 31.71 GB
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/wxajxv-dney1w?file=src%2Fexample.tsx

## Actual Behavior
When you have 2 or more combo boxes on the page and change selection on one of them, the other one forget its state

## Expected Behavior
The states of the combo boxes should be independent.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by pradeept95** [comment]
Hi @irinatarn,
Based on your example, you should use `value` props instead of `defaultValue`. `defaultValue` prop is for Uncontrolled Input. In your case you're using Controlled input.

Here is the working example: https://stackblitz.com/edit/wxajxv-mcjumr?file=src%2FComboBox.tsx

Here is the documentation for controlled Combobox.
https://react.fluentui.dev/?path=/docs/components-combobox--default#controlled

**Comment by irinatarn** [comment]
Hi @pradeept95,
In my scenario I need couple of combo boxes on the page to be Uncontrolled Input and been populated with default value and not loose that value on rerender. The example is valid. The bug is valid too.

Thanks,
I.

**Comment by layershifter** [comment]
@irinatarn as @pradeept95 pointed out - the example is invalid usage of the component: it should be either fully uncontrolled `defaultSelectedOptions` + `defaultValue` or fully controlled `selectedOptions` + `value`.

You can also observe errors in the console that confirms the statement above:

<img width="379" alt="image" src="https://github.com/user-attachments/assets/402d8f7d-bdba-4ca2-8098-6e278feb1beb">
