### ISSUE TITLE
[Bug]: Unable to upgrade fluentUI react-components and react-icons

### ISSUE THREAD

**Issue by 15MariamS** [microsoft/fluentui#31524]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (14) arm64 Apple M3 Max
    Memory: 352.91 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 125.0.6422.113
    Safari: 17.4
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://gist.github.com/15MariamS/baf3dabd7a4880db55254cb4c2ca760a#file-package-json-L20

### Bug Description

I'm trying to upgrade @fluentui/react-icons from 2.0.237 to 2.0.240 and upgrade @fluentui/react-components from 9.49.0 to 9.53.0. 

However, I'm unable to upgrade my `@fluentui/react-components`.  If I remove `@fluentui/react-icons`, the error is solved (but I need that dependency). Here is my current [package.json](https://gist.github.com/15MariamS/baf3dabd7a4880db55254cb4c2ca760a#file-package-json-L20).

The issue seems similar to this one, though the potential fixes there haven't helped: https://github.com/microsoft/fluentui/issues/24952#issuecomment-1305706032

### Logs

Logs: https://gist.github.com/15MariamS/094fef318b4be63cb81c3db5fae12bf2

```shell
▲ Next.js 14.1.4

   Creating an optimized production build ...

<--- Last few GCs --->

[1734:0x71dc2e0]    60800 ms: Mark-Compact 2032.2 (2088.4) -> 2021.1 (2089.2) MB, 1524.13 / 0.00 ms  (average mu = 0.298, current mu = 0.070) allocation failure; scavenge might not succeed
[1734:0x71dc2e0]    63052 ms: Mark-Compact 2029.2 (2089.2) -> 2022.9 (2102.9) MB, 2188.55 / 0.00 ms  (average mu = 0.162, current mu = 0.028) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xb82c28 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/opt/hostedtoolcache/node/20.13.1/x64/bin/node]
 2: 0xeed540 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/opt/hostedtoolcache/node/20.13.1/x64/bin/node]
 3: 0xeed827 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/opt/hostedtoolcache/node/20.13.1/x64/bin/node]
 4: 0x10ff3c5  [/opt/hostedtoolcache/node/20.13.1/x64/bin/node]
 5: 0x[11](https://github.com/company/web/actions/runs/9297919227/job/25588880985?pr=2248#step:5:12)17248 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/opt/hostedtoolcache/node/20.13.1/x64/bin/node]
 6: 0x10ed361 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/opt/hostedtoolcache/node/20.13.1/x64/bin/node]
 7: 0x10ee4f5 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/opt/hostedtoolcache/node/20.13.1/x64/bin/node]
 8: 0x10cbb46 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/opt/hostedtoolcache/node/20.13.1/x64/bin/node]
 9: 0x1527976 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/opt/hostedtoolcache/node/20.13.1/x64/bin/node]
10: 0x7ffb44e99ef6 
Error: Process completed with exit code [12](https://github.com/company/web/actions/runs/9297919227/job/25588880985?pr=2248#step:5:13)9.
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by disgyze** [comment]
Usually, when this kind of error happens to me, I delete yarn.lock and then reinstall all the dependencies (yarn **up**). If that doesn't help, I then remove yarn.lock and node_modules folder, and use yarn up again.

**Comment by 15MariamS** [comment]
> When this kind of error happens to me, I delete **yarn.lock** and then reinstall all the dependencies (`yarn up`). If that doesn't help, I then remove **yarn.lock** and **node_modules** folder, and use `yarn up` again.
> 
> Hope this helps.

Yup, that did it! Thank you @disgyze 🙇‍♀️

**Comment by 15MariamS** [comment]
Running `yarn dedupe` fixed the issue for me. My upgrade caused my dependency tree to contain redundant versions of `@fluentui/react-icons`.
