### ISSUE TITLE
[Bug]:  Accordion does not return to initial state of all items being in the closed state

### ISSUE THREAD

**Issue by JoseHerminioCollas** [microsoft/fluentui#31556]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Appears on FluenUI 9 example page:
https://react.fluentui.dev/?path=/docs/components-accordion--default
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-accordion--default

## Actual Behavior

On the example page for FluentUI 9, for the [default](https://react.fluentui.dev/?path=/docs/components-accordion--default#default) example of Accordion, the initial state is all the items in a closed state. The user opens an item but can not toggle that item off so that the Accordion can return to its initial state.
If the user is presented with an initial state of all items being closed then the user would expect to return to an initial state of all items being closed.
This issue is present in other examples. 

This action would be expected in the case of the example [Open Items](https://react.fluentui.dev/?path=/docs/components-accordion--default#open-items).

The example Open Items has an initial state with an open item so the user should not expect to return to a state of all items being closed.

## Expected Behavior

If the Accordion has an initial state of all items closed then the expectation is that the Accordion should be able to return to that initial state.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @JoseHerminioCollas, this is already supported via the `collapsible` attribute.
https://react.fluentui.dev/?path=/docs/components-accordion--default#collapsible

**Comment by JoseHerminioCollas** [comment]
The assumption is the user would expect to return to the UI state presented initially. In the case of the Accordion, the [default ](https://react.fluentui.dev/?path=/docs/components-accordion--default#default)state does not enable the user to return to an initial state. This is possible through configuration, yes. The issue is that the default state should present the user with the option of returning to the initial state. 

Yes, I see that this may be by design and _not_ an issue, I present this issue based on the assumption presented previously.

**Comment by behowell** [comment]
Yes, this behavior is by design. It can be configured through props, including collapsible and/or whether a panel is initially opened.
