### ISSUE TITLE
[Bug] [Accessibility] [Charting] aria-required-children: Ensures elements with an ARIA role that require child roles contain them

### ISSUE THREAD

**Issue by Gabnight** [microsoft/fluentui#31563]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 46.93 GB / 63.95 GB
  Browsers:
    Edge: Chromium (125.0.2535.85), ChromiumDev (127.0.2610.3)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/legends

## Actual Behavior
When you do a 'Fast pass' with 'Accessibility insight for web' web extension, it found this issue:
Title: WCAG 1.3.1: Ensures elements with an ARIA role that require child roles contain them (div[data-focuszone-id="FocusZone164"])
Tags: Accessibility, WCAG 1.3.1, aria-required-children

Issue: Ensures elements with an ARIA role that require child roles contain them (aria-required-children - https://accessibilityinsights.io/info-examples/web/aria-required-children)

Target application: Fluent UI - Controls - React - Legends - https://developer.microsoft.com/en-us/fluentui#/controls/web/legends

Element path: div[data-focuszone-id="FocusZone164"]

Snippet: <div role="listbox" aria-label="Legends" aria-multiselectable="false" data-tabster="{&quot;uncontrolled&quot;: {}}" class="ms-FocusZone css-134" data-focuszone-id="FocusZone164">

How to fix: 
Fix any of the following:
  Element has children which are not allowed: [role=button]
  Element uses aria-busy="true" while showing a loader

Environment: Microsoft Edge version 125.0.0.0

====

This accessibility issue was found using Accessibility Insights for Web 2.42.0 (axe-core 4.8.4), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

Screenshot:
![image](https://github.com/microsoft/fluentui/assets/122602310/6ae6a522-ab32-4a05-be8d-26759ff35106)

## Expected Behavior
No Fast pass issue in the legen

### Requested priority

High

### Products/sites affected

https:/make.powerautomate.com

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by zh244135370** [comment]
Facing the same issue, any update here for it? @AtishayMsft

**Comment by AtishayMsft** [comment]
This issue will be fixed by end of July.
