### ISSUE TITLE
[Feature]: add the copilot icon to https://developer.microsoft.com/en-us/fluentui#/styles/web/icons#available-icons 

### ISSUE THREAD

**Issue by t-mrinal** [microsoft/fluentui#31575]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Copilot icon is not there as of yet in Microsoft tools icon list kindly add it.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by tomi-msft** [comment]
Hello @t-mrinal thanks for submitting the issue. The Copilot icon is not under the MIT license, so has more strict usage policies, and therefore cannot be released in the react-icons package.
