### ISSUE TITLE
[Bug]: Tooltip v9 will throw error if use v8 component as it's children

### ISSUE THREAD

**Issue by Leolewin** [microsoft/fluentui#31571]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz
    Memory: 2.52 GB / 31.73 GB
  Browsers:
    Chrome: 125.0.6422.142
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/tooltip-v9-issue-8h462v?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx1fds1u00063j6gcxyfumry%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx1fds1u00023j6gmfkd27y4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx1fds1u00033j6gvfl7t99z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx1fds1u00053j6g6r2v30o0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx1fds1u00023j6gmfkd27y4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx1fds1u00013j6g5s0tgazd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clx1fds1u00023j6gmfkd27y4%2522%252C%2522activeTabId%2522%253A%2522clx1fds1u00013j6g5s0tgazd%2522%257D%252C%2522clx1fds1u00053j6g6r2v30o0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx1fds1u00043j6g4pxwg5r7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clx1fds1u00053j6g6r2v30o0%2522%252C%2522activeTabId%2522%253A%2522clx1fds1u00043j6g4pxwg5r7%2522%257D%252C%2522clx1fds1u00033j6gvfl7t99z%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clx1fds1u00033j6gvfl7t99z%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

## Actual Behavior
When `Tooltip (V9)` uses fluentui v8 component or any component not handled `ref` prop as its children directly, it will throw some error as belowing:
![image](https://github.com/microsoft/fluentui/assets/12589994/97ad5d22-cf4a-4de3-a170-e354e7d22a1f)
 
## Root cause:
Tooltip passe [mergedRef](https://github.com/microsoft/fluentui/blob/6c603f4ae1017108a995aeb7ed98b7ddc2974ab8/packages/react-components/react-tooltip/src/components/Tooltip/useTooltip.tsx#L262) to its children and call some DOM API in [ref callback](https://github.com/microsoft/fluentui/blob/6c603f4ae1017108a995aeb7ed98b7ddc2974ab8/packages/react-components/react-tooltip/src/components/Tooltip/useTooltip.tsx#L262)
however, if the children is a component that **NOT HANDLING** `ref`, the value in callback will be a component instance instead of real DOM element.

## Expected Behavior
Tooltip show correctly

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
> however, if the children is a component that **NOT HANDLING** `ref`, the value in callback will be a component instance instead of real DOM element.

That's expected, `children` of `Tooltip` & `*Trigger` components should be wrapped with `React.forwardRef()`. The workaround in this case would be:

```tsx
const ButtonWrapper = React.forwardRef((props, ref) => {
  return <DefaultButton {...props} elementRef={ref} />;
});

// ---

<TooltipV9 content={"test tooltip v9"} relationship="label">
  <ButtonWrapper text="Hover Over Me" />
</TooltipV9>
```
