### ISSUE TITLE
[Bug]: Cannot interact with buttons inside TableHeaderCell

### ISSUE THREAD

**Issue by WayneFerrao** [microsoft/fluentui#31588]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 391.55 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 125.0.6422.142
    Edge: 125.0.2535.85
    Safari: 17.5
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://stackblitz.com/edit/pvnqst?file=src%2Fexample.tsx

### Bug Description

I can't access any buttons inside the header cell using the keyboard. I'm trying to keyboard access an InfoLabel that's inside a TableHeaderCell and tried following the dev guide which mentions using utilities without success. I was able to access it by changing it from a TableHeaderCell to a TableCell. This works but the header aspect is important for screen readers in particular, to help differentiate "content" from "context", as well as to associate individual data cells with their semantics.

## Actual Behaviour
There is multiple focus on the TableHeaderCell and InfoLabel and I can't interact with the info tooltip to see its contents. This bug also repros on this docsite example: https://react.fluentui.dev/?path=/docs/components-table--default#resizable-columns---controlled--preview-

## Expected Behaviour
To be able to tab/arrow navigate through TableHeaderCells and interact with buttons inside them.

This seems to be a general functionality issue and not specifically a11y, although it does affect that as well.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
There are a couple things going on here -- to start, I'd recommend using `DataGrid` over `Table` for interactive use cases, since that will give you all the correct semantics & tabster attributes without you needing to manually do them yourself.

On our side, it looks like we need to add a `focusMode` prop to `DataGridHeaderCell`. We have that for `DataGridCell` already to handle nested interactives, but not the header cell.

@ling1726 does that ^ sound like the right approach? It might get more hairy with the sortable behavior, since that wraps everything in a button and would create its own separate problems with nested interactives 😅

**Comment by ling1726** [comment]
The design of the Table was that there should be no focusable item in the header apart from the sort button. In this case as a workaround you could use the `aside` slot https://stackblitz.com/edit/pvnqst-pf7rtb?file=src%2Fexample.tsx

**Comment by WayneFerrao** [comment]
Unfortunately, that workaround isn't accessibility compliant.  While you can interact with the tooltip within the HeaderCell,  tab navigating still gives multiple focuses to the cell and the tooltip.

**Comment by ling1726** [comment]
The double focus indicator can be removed with CSS - there is never morethan one element focused in the browser by design, that's purely a styling issue https://stackblitz.com/edit/pvnqst-pf7rtb?file=src%2Fexample.tsx
