### ISSUE TITLE
[Bug]: queryMatch.addEventListener is not a function

### ISSUE THREAD

**Issue by akisnejuhasz** [microsoft/fluentui#31591]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 3.28 GB / 15.73 GB
  Browsers:
    Edge: Chromium (125.0.2535.85)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

no

### Reproduction

Please contact me if you need the link to the repo.

## Actual Behavior
When trying to run unit tests for the Fluent v9 `Dialog` component, I get `queryMatch.addEventListener is not a function` error, no matter what I add/remove/change in the code or in the test file. matchMedia (targetWindow.matchMedia) is not returning an object that has addEventListener.

## Expected Behavior
Fluent should check that addEventListener is a function before calling it.

### Logs

```shell
TypeError: queryMatch.addEventListener is not a function
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
In Jest & jsdom `typeof window.matchMedia` returns:

```js
console.log("window.matchMedia: typeof", typeof window.matchMedia)
// window.matchMedia: typeof undefined
```

And we have already a check against it:

https://github.com/microsoft/fluentui/blob/02ad9418f19b4d03c15c1862c2436955a7a0f356/packages/react-components/react-motion/src/hooks/useIsReducedMotion.ts#L16

It looks that your env mocks `window.matchMedia` without providing a proper implementation.

**Comment by GeoffCoxMSFT** [comment]
@layershifter - In this case the partner is trying to unit test a dialog of their own.  Our Dialog uses the reduced motion hook.  When we test the hook, we mock the media queries.  It seems like an unnecessary burden for callers of Dialog writing tests to have to mock all the internals of Dialog and any hooks it uses.  The matchMedia returns an object but it doesn't have the add/remove event listener.  If the hook checked that the add/remove event listener functions were non-null and functions like it does the matchMedia function, then the hook could return false without the partner needing to mock.

**Comment by layershifter** [comment]
> When we test the hook, we mock the media queries. ... It seems like an unnecessary burden for callers of Dialog writing tests to have to mock all the internals of Dialog and any hooks it uses. 

@GeoffCoxMSFT do I correctly understand that `window.matchMedia` is mocked? If so, why is that needed for `Dialog`? As it's not required...

**Comment by akisnejuhasz** [comment]
Talked offline to show the affected files in the repository. In the end it was me how did not set up a mock correctly for `window.matchMedia` and `addEventListener` inside it.

Thank you @layershifter for the help!
