### ISSUE TITLE
[Bug]: Dialog remains in DOM after close when using Jest

### ISSUE THREAD

**Issue by wfwf1997** [microsoft/fluentui#31593]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 28.73 GB / 31.32 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Browsers:
    Chrome: 123.0.6312.105
```

### Are you reporting Accessibility issue?

no

### Reproduction

Add Dialog close validation to `packages/react-components/react-dialog/src/components/Dialog/Dialog.test.tsx`

```diff
    const result = render(
      <Dialog>
        <DialogTrigger disableButtonEnhancement>
          <button data-testid="trigger">Open dialog</button>
        </DialogTrigger>
        <CustomDialogSurface>
          <div data-testid="surface-content">content in surface</div>
+          <DialogTrigger>
+            <button data-testid="trigger-close">Close dialog</button>
+          </DialogTrigger>
        </CustomDialogSurface>
      </Dialog>,
    );

    result.getByTestId('trigger').click();

    expect(result.getByTestId('surface-content')).toBeInTheDocument();
    expect(result.getByTestId('surface-content')).toBeVisible();

+    result.getByTestId('trigger-close').click();
+    expect(result.queryByTestId('surface-content')).toBeNull();
```

Then run the tests.

## Actual Behavior
The test passed. The element with `data-testid="surface-content"` does not exist. `react-components@9.52.0` passes this test.

## Expected Behavior
The test failed. The element with `data-testid="surface-content"` exists. `react-components@9.53.0` fails this test.

### Requested priority

Blocking

### Products/sites affected

ODSP

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by wfwf1997** [comment]
This issue has also been reported in #31592 as point 1. Create this issue to track this bug specifically.

**Comment by 15MariamS** [comment]
Thank you for the fix, team! 🙏
