### ISSUE TITLE
[Bug]: Missing Fluent icon in tab for Storybook

### ISSUE THREAD

**Issue by gouttierre** [microsoft/fluentui#31606]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/

## Actual Behavior
![image](https://github.com/microsoft/fluentui/assets/78806055/ecc400b2-bf99-40c0-b909-a5ed767532ef)

## Expected Behavior
![image](https://github.com/microsoft/fluentui/assets/78806055/66c4e7bc-d9e7-4fda-9ad8-e79b5af606d4)

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by hcz** [comment]
Fixed this in https://github.com/microsoft/fluentui/pull/31706

**Comment by hcz** [comment]
@tudorpopams May I ask you to see the code of this fix? https://github.com/microsoft/fluentui/pull/31706
