### ISSUE TITLE
[Bug]: Dialog documentation could be clearer

### ISSUE THREAD

**Issue by ccardiasmenosMSFT** [microsoft/fluentui#31620]
### Library

Web Components (@fluentui/web-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

N/A

## Actual Behavior
The Dialog documentation found here was a bit confusing. We only show a close button on the non-modal dialog type but then explain later that modal and non-modal dialogs can both have close buttons.: https://fluent2.microsoft.design/components/web/react/dialog/usage

## Expected Behavior
It would help to provide visuals that convey that you can interact with the below content in a non-modal dialog rather than have the only difference showing be the close button.

### Requested priority

Normal

### Products/sites affected

All

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chrisdholt** [comment]
@gouttierre looks like this is for React, can you assign to the right person?

**Comment by ccardiasmenosMSFT** [comment]
I updated the description above. This doesn't need to be considered a bug but is a suggestion to improve the documentation. If there's a way to change the issue type, please let me know.

**Comment by layershifter** [comment]
@tudorpopams FYI

**Comment by tudorpopams** [comment]
Hi @ccardiasmenosMSFT , thanks for submitting this issue. This is intended for the Fluent 2 website and not Fluent UI React v9 per se, so I'm going to close this issue and recreate it on the website board (which is private, unfortunately) as an improvement suggestion.

**Comment by ccardiasmenosMSFT** [comment]
[like]  Caroline Cardiasmenos reacted to your message:
________________________________
