### ISSUE TITLE
[Feature]: Tooltips should not render when Menus are open

### ISSUE THREAD

**Issue by NotWoods** [microsoft/fluentui#31639]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

For a pattern like this:
```jsx
<Menu>
  <MenuTrigger>
    <Tooltip relationship="label">
      <Button />
    </Tooltip>
  </MenuTrigger>
  <MenuPopover />
</Menu>
```

The tooltip will sometimes render on top of the menu depending on user actions. Ideally, the tooltip should not be visible when the menu attached to the same trigger is open.

This can be done manually but it's a common enough pattern I think it should be supported by default.

### Additional context

![image](https://github.com/microsoft/fluentui/assets/1782266/3bc96668-eec2-4346-9667-97ad22e2da0c)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Med-High

**Comment by miroslavstastny** [comment]
There are more partners reporting this.

**Comment by gouttierre** [comment]
📢

- Internal partner teams are re-implementing workarounds in Office.com as well as Loop. 
- Moving the feature request to backlog review for upcoming triage.
- The priority of the request has been elevated.

cc~ @NotWoods , @miroslavstastny , @tudorpopams , @jurokapsiar , @JustSlone
