### ISSUE TITLE
[Bug]: Tree with virtualization focus on active tree item 

### ISSUE THREAD

**Issue by ruthshemla** [microsoft/fluentui#31643]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
I would like to get the border around tree item on first click on tree item
currently I get the border only after keyboard navigation (up down left right)
```

### Are you reporting Accessibility issue?

no

### Reproduction

I would like to get the border around tree item on first click on tree item currently I get the border only after keyboard navigation (up down left right)

## Actual Behavior
Calling focus on element does not make the border around tree item to show up
## Expected Behavior
being able to get the border around tree item as "selection" indicator

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@ruthshemla just to confirm, is this the outline you're referring to in this bug?:

<img width="855" alt="screenshot of the Fluent Tree default example, with a black 2px outline around the first tree item" src="https://github.com/microsoft/fluentui/assets/3819570/b2e12577-f55d-4640-829c-ac1860b8b212">

If so, that's the focus outline, and we intentionally only show it when the user is navigating via keyboard. It only indicates focus, not selection. Selection is indicated with checkboxes like these (or round ones in the case of single-select):

<img width="290" alt="screenshot of the Fluent Tree selection example, no focus outline is showing but tree items have either empty square checkboxes showing an unchecked state, or checked checkboxes showing a checked state. One parent has a partially checked checkbox, showing a mixed state." src="https://github.com/microsoft/fluentui/assets/3819570/3bb7edf4-3491-48f3-8834-60a3f4ccc878">

Could you clarify why you want an outline to show up on click? Or did you mean something other than the focus outline?
