### ISSUE TITLE
[Bug]: [vite]: Rollup failed to resolve import "scheduler" from "D:/a/1/s/node_modules/@fluentui/react-context-selector/lib/createContext.js".

### ISSUE THREAD

**Issue by sujitykulkarni** [microsoft/fluentui#31680]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components  v9.50.0
Node v18.20.3

**Cannot obtain exact system info as the mentioned problem is occurring in an Azure Devops pipeline when `npm run build` is performed. Please refer logs provided for more info.**
```

### Are you reporting Accessibility issue?

no

### Reproduction

Cannot provide reproduction URL as the issue is observed only in my Azure Devops pipline at the build time

## Actual Behavior
- Build Failure: The build process for the <package_name> failed during the `NPM build <package_name>` step, in the Azure Devops Pipeline
- Error Details: The error occurred due to Rollup failing to resolve the import “scheduler” from a module in the @fluentui/react-context-selector library

## Expected Behavior
- Successful Build: The expected behavior is a successful build of the <package_name> without any errors.
- Correct Module Resolution: All modules, including “scheduler,” should be correctly resolved during the build process, ensuring a smooth and error-free build.

### Logs

```shell
; node bin location = C:\hostedtoolcache\windows\node\18.20.3\x64\node.exe
; node version = v18.20.3
; npm local prefix = D:\a\1\s
; npm version = 10.7.0
; cwd = D:\a\1\s
; HOME = C:\Users\VssAdministrator
; Run `npm config ls -l` to show all defaults.
C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\node\18.20.3\x64\npm.cmd run build -w <package_name>"
x Build failed in 6.76s

error during build:
> <package_name>@1.14.11 build
Error: [vite]: Rollup failed to resolve import "scheduler" from "D:/a/1/s/node_modules/@fluentui/react-context-selector/lib/createContext.js".
> tsc && vite build
This is most likely unintended because it can break your application at runtime.

If you do want to externalize this module explicitly add it to
vite v5.2.11 building for production...
`build.rollupOptions.external`
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
Could you please check your installed dependencies?

`@fluentui/react-context-selector` has `scheduler` as a **peer** dependency:
https://github.com/microsoft/fluentui/blob/8cfadd0245da036b77c921a7e6a128969cb72462/packages/react-components/react-context-selector/package.json#L34-L40

Make sure you have that package installed. Your package manager should complain, unless you use `midgard-yarn`, see #23639 for more details.

**Comment by sujitykulkarni** [comment]
Adding `scheduler` as a peer dependency explicitly, helped me resolve the issue. Thanks for that. By the way, I wasn't required earlier to add this package to my peer dependencies. I'm actively using  FluentUI v9 in my project for almost last six months.

**Comment by layershifter** [comment]
> Adding `scheduler` as a peer dependency explicitly, helped me resolve the issue. Thanks for that. By the way, I wasn't required earlier to add this package to my peer dependencies. I'm actively using FluentUI v9 in my project for almost last six months.

Probably something changed in your env as `scheduler` is a required peer dependency for ages 🐱 Anyway, closing as it was resolved.
