### ISSUE TITLE
[Bug]: Opening Drawer from Modal causes focus issues

### ISSUE THREAD

**Issue by rocketBANG** [microsoft/fluentui#31709]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 33.85 GB / 63.95 GB
  Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/hibkph-pxw8qg?file=src%2Fexample.tsx

## Actual Behavior
Opening a Drawer using a button in the Modal causes issues where nothing in the opened drawer can be focused. For example there's an `Input`, it will be selected for a second on click but then focus will be lost again before you can type in it

## Expected Behavior
For elements in the OverlayDrawer to be focusable

I tried adding `DialogTrigger`s to the button that opens the drawer and `useRestoreFocusTarget` as described in the "Trigger Outside Dialog" example, but to no avail

Even if the modal is dismissed, the focus is still not correct and clicking on the text box will focus for a second then focus will be lost again

I also set `disableRestoreFocus` on the `Modal` to try make sure it wasn't interfering with the focus but that doesn't appear to achieve anything

### Requested priority

Blocking

### Products/sites affected

Dynamics Fraud Protection - dfp.microsoft.com

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment]
Hi 👋🏻 @rocketBANG 

Modal has `focusTrapZoneProps`, which you can disable, when `Drawer` is opened. 
I think something like this should work: 

Works as expected with this:
```
  <Modal
        isOpen={isModalOpen}
        onDismiss={() => {
          setIsModalOpen(false);
        }}
        disableRestoreFocus={true}
        focusTrapZoneProps={{
          disabled: isDrawerOpen,
        }}
      >
```

**Comment by rocketBANG** [comment]
thanks for the help! I also found another workaround, but probably not ideal to have a delay and wait for the modal to close

```js
onClick={() => {
  setIsModalOpen(false);
  setTimeout(() => {
    setIsDrawerOpen(true);
}, 500)
```

**Comment by mainframev** [comment]
@rocketBANG you're welcome, i will close it then 🙂
