### ISSUE TITLE
[Bug]: After updating to FluentUI 9.54.0, the runtime of all unit tests has significantly increased.

### ISSUE THREAD

**Issue by wendyyuanxie** [microsoft/fluentui#31714]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (32) x64 AMD EPYC 7763 64-Core Processor
    Memory: 116.48 GB / 125.78 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
```

### Are you reporting Accessibility issue?

None

### Reproduction

not sure how to share a repo at this case

### Bug Description

After we update fluent package to version 9.54.0, the runtime of all the unit tests are increased significantly in our codebase. Especially, the unit tests are running against UI components. The other stuff are remain unchanged. We have notice this issue since fluent 9.53.0. 

We are currently running fluent v9.46.6, and the runtime of our unit tests are around 40s:
<img width="344" alt="before-update-to-latest" src="https://github.com/microsoft/fluentui/assets/125315752/0c2bbf77-aeb7-413e-9f12-33d9ff13d0ec">

After we update to fluent 9.54.0, and run the unit tests, the runtime now is around 230s, which is **6** times more: 

<img width="404" alt="after-update-to-latest" src="https://github.com/microsoft/fluentui/assets/125315752/783f91be-780b-41a8-9931-9b2d751de8a2">

The testing library we are using is `Jest` (29.7.0),  `react-test-renderer` (18.2.0), and we have `react` 18.2.0

This prevent us from updating our fluent package to the latest. Any help will be greatly appreciated!

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
**BEFORE:**
| react-components version | `jest --ci` / s |
|--------|--------|
| 9.46.6 (current) | 91s |
| 9.54.1 | 580s / **𝚫 537% SLOWER 🚨**  | 

**AFTER:**
resolved the issue within user codebase with following perf results:

| react-components version | `jest --ci` / s |
|--------|--------|
| 9.46.6 (current) | 91s |
| 9.54.1 | 71s / **𝚫 22% FASTER**  | 


**What was the issue:**

pinned react-icons which created duplicates within node_modules -> causing gigantic perf slowdowns

**Comment by Hotell** [comment]
@wendyyuanxie please confirm if you're unblocked and we can close this. ty!
