### ISSUE TITLE
[Bug]: Drawer Overlay from bottom gets off the canvas/window in mobile browsers on opened

### ISSUE THREAD

**Issue by Narvalex** [microsoft/fluentui#31724]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz
    Memory: 11.29 GB / 23.73 GB
  Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/devbox/epic-flower-ndtcmn

## Actual Behavior
When opening the drawer in **an Android mobile browser (Edge, Chrome, Firefox)**, it opens from the bottom and grows to the top of viewport, but then it countinues to grwo until getting the top part of the drawer off canvas
![image](https://github.com/microsoft/fluentui/assets/11648387/81173c47-054a-4262-87b1-c168905244a1)

## Expected Behavior
In **an Android mobile browser (Chrome, Edge, Firefox)** When opening the drawer from the bottom with full size, you expect to cover exactly the full page
![image](https://github.com/microsoft/fluentui/assets/11648387/2c2ef496-8c20-4117-b217-ec28556c6d3d)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
`<OverlayDrawer size={full} position="bottom" />` sets height to `100vh` which collides with mobile address bar or keyboard:
https://github.com/microsoft/fluentui/blob/cb605ecd8727bc581edad74a7c672a2ddc58db70/packages/react-components/react-drawer/library/src/shared/useDrawerBaseStyles.styles.ts#L93-L95

### Workaround
Set the drawer height to `100%`:

```tsx
const useStyles = makeStyles({
  drawerHeightFix: {
    ['--fui-Drawer--size']: '100%',
  },
});

//...

<OverlayDrawer className={styles.drawerHeightFix} />
```
