### ISSUE TITLE
[Bug]: react-nav-preview 0.4.0 footer styling issue

### ISSUE THREAD

**Issue by techienickb** [microsoft/fluentui#31723]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 1.99 GB / 15.83 GB
  Browsers:
    Edge: Chromium (126.0.2592.56), ChromiumDev (127.0.2610.3)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/kt5i1c?file=src%2Fexample.tsx

## Actual Behaviour
Nav Footer padding is not set correctly, is currently 0

Footer nav item category isn't width: 100% either

## Expected Behaviour
Padding should be 
```html
0 var(--spacingHorizontalXS) 0 var(--spacingHorizontalMNudge)
```
Width on item category should be 100%

To reproduce use the NavDrawerFooter and compare the style tags with NavDrawerBody

Compare the body and footer in the example on https://stackblitz.com/edit/kt5i1c?file=src%2Fexample.tsx

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
<img width="269" alt="image" src="https://github.com/microsoft/fluentui/assets/9615899/f6afd613-1092-4782-8a59-3738eccfe568">

FYI @mltejera

**Comment by mltejera** [comment]
Hey thanks for submitting @techienickb! 

We've since changed direction on the footer for the Nav in that we don't want to include any content in the footer area going forward. We no longer consider it a supported path, even if it is possible. Please feel free to contribute a fix or solve on the consumption end :-)
