### ISSUE TITLE
[Bug]: After version 9.54.1, bundleIcon required additional parameter to create composite icon!!!!!

### ISSUE THREAD

**Issue by pradeept95** [microsoft/fluentui#31729]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
NA
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://stackblitz.com/run?file=src%2Fexample.tsx

## Actual Behavior
after V9.54.1, the bundleIcon added one more prams while creating composite icon called "LightIcon" which causing all application incompatible with v9.54.1 and above. 

![image](https://github.com/microsoft/fluentui/assets/28040299/ed1c7dc8-1108-4160-8e9c-c1a42476a303)

## Expected Behavior
bundleIcon should not add more parameter without providing support for existing behavior

### Logs

```shell
Expected 3 arguments, but got 2.(2554)
bundleIcon.d.ts(2, 77): An argument for 'LightIcon' was not provided.
(alias) bundleIcon(FilledIcon: FluentIcon, RegularIcon: FluentIcon, LightIcon: FluentIcon): FluentIcon
import bundleIcon
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Linking with https://github.com/microsoft/fluentui-system-icons/issues/727

**Comment by christophepeerens** [comment]
Hello,

Since not finding the Light icon, I tried to define the Regular one twice.

const EditIcon = bundleIcon(EditFilled, EditRegular, EditRegular);

<Button
    icon={<EditIcon />}
    appearance="subtle"
    aria-label={t('Edit')}
    onClick={() => dispatch(dataActionCreators.requestTimeSheetEntryEdition(ts))}
/>

But the button displays the icon twice!

**Comment by techienickb** [comment]
Work around for anyone with this issue, override fluent ui back to before this breaking change, add this to your package.json

```json
   "overrides": {
      "@fluentui/react-icons": "2.0.243"
   },
```

**Comment by tomi-msft** [comment]
PR to revert the change: https://github.com/microsoft/fluentui-system-icons/pull/728

**Comment by tomi-msft** [comment]
Fixed in latest version of `@fluentui/react-icons`
