### ISSUE TITLE
[Bug]: Accessibility issue while using PopoverTrigger inside Menu

### ISSUE THREAD

**Issue by MANVI-15** [microsoft/fluentui#31750]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (32) x64 AMD Ryzen Threadripper PRO 3955WX 16-Cores
    Memory: 87.34 GB / 127.86 GB
  Browsers:
    Edge: Chromium (126.0.2592.56)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://stackblitz.com/edit/eojfwu?file=src%2Fexample.tsx

## Actual Behavior
In the example link provided , the Narrator announces ‘MenuItem’ for the initial two items, but for the third item, it identifies it as a button.

## Expected Behavior
It should announce 'MenuItem' for the third option in the example link ( for the mneuitem wrapped inside the popover trigger)

### Requested priority

Normal

### Products/sites affected

Loop

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by MANVI-15** [comment]
Raised the same issue on the Fluentv9 channel here is the link for that:https://teams.microsoft.com/l/message/19:86b094239256467da9dfa96ba0897ca2@thread.skype/1718628555437?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=ffe264f2-14d0-48b5-9384-64f808b81294&parentMessageId=1718628555437&teamName=Fluent%20Community&channelName=Fluent%20UI%20React%20(Web)&createdTime=1718628555437

**Comment by miroslavstastny** [comment]
Workaround suggested by @MANVI-15 is to explicitly assign `role="menuitem"` to the `MenuItem` which is the `PopoverTrigger`
