### ISSUE TITLE
[Bug]: Fluent V9 Tree : onOpenChange is not correctly sending/recieving the Enter keydown event to TreeItemOpenChangeEvent

### ISSUE THREAD

**Issue by dennymicrosoft** [microsoft/fluentui#31760]
### Library

~React Northstar / v0 (@fluentui/react-northstar)~
v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 32.04 GB / 63.95 GB
  Browsers:
    Edge: Chromium (126.0.2592.61)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/xxnjkp?file=src%2Fexample.tsx

## Actual Behavior
Enter keydown on TreeItem is triggering `Click` `data.type` instead of the `Enter` type for `TreeItemOpenChangeEvent`

## Expected Behavior
Pressing Enter on focused treeitem will send `Enter` `data.type` to `onOpenChange`. Would like to add custom functionality when ctrl + Enter for `onOpenChange`.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
Confirming, `data.type` in `TreeItemOpenChangeData` is correctly set to `ArrowLeft` or `ArrowRight` when arrows are used, but to `Click` when pressing `Enter`.

**Comment by miroslavstastny** [comment]
We should perhaps add support for handling modifier keys better in the library. @ling1726 to create a tracking issue and link it here.
@bsunderhus we should align `Tree` and `TreeItem` types to match.

**Comment by bsunderhus** [comment]
@dennymicrosoft, quick question here. WDYT if we propagated the ctrl key to the click event? https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/ctrlKey  🤔

**Comment by bsunderhus** [comment]
Ok @dennymicrosoft , we've decided to go with the [example's](https://stackblitz.com/edit/xxnjkp-2r2okz?file=src%2Fexample.tsx) approach for your use case, here's the reasons:

1. you want a custom behavior that is not associated with controlling open state
2. we do provide a mechanism for you to stop the `onOpenChange` invocation down to the `keydown` event handler (by invoking `event.preventDefault`, which allows you to prevent open state changes and add your custom behavior
3. adding anything that supports both `click` and `Enter` scenarios discerning them apart is troublesome as people might forget to support both cases and this will introduce a11y issues.

Let me know if the example provided is enough to ensure achieve what you want.
