### ISSUE TITLE
[Bug]: Inconsistent Typography Font Weights in Fluent UI Implementation

### ISSUE THREAD

**Issue by higan-hub** [microsoft/fluentui#31773]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 30.43 GB / 63.95 GB
  Browsers:
    Chrome: 126.0.6478.62
    Edge: Chromium (126.0.2592.56)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

None

### Reproduction

ok

### Bug Description

Reporting an issue we have encountered with the typography font weights in Fluent UI. We have noticed that the font weights applied to typography components in our application do not match the appearance as demonstrated in the Fluent UI documentation.

**Issue Description:**
When using typography components such as Body1Strong and applying font weights, the visual output in our application is inconsistent with the examples provided in the Fluent UI documentation. Specifically, the font weights appear differently, affecting the overall look and feel of our UI.

**Steps to Reproduce:**

Create a Body1Strong component (Which has font weight 600).
Render the component in a React application.
Compare the font weight appearance with the Fluent UI documentation.
Expected Behavior:
The font weights of typography components should appear consistent with the examples provided in the Fluent UI documentation.

**Observed Behavior:**
The font weights appear differently (heavier) in our application, leading to a mismatch in the visual styling.

**Workaround:**
As a temporary solution, we have manually applied the desired font weight (500) to ensure consistency in the appearance which is not matching the Body1Strong in the fluent UI documentation. However, we believe this should be addressed within the Fluent UI framework for a more robust solution.

### Requested priority

Blocking

### Products/sites affected

Dynamics 365 Commerce Point of Sale App

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
Thank you for reporting the issue. As you pointed out, the issue does not reproduce in the docsite, so it would need some debugging in your environment.

Here is a sandbox rendering `Body1`, `Body1Strong`, `Body1Stronger`: https://stackblitz.com/edit/qzpwab?file=src%2Fexample.tsx.
It should render like this:
<img width="120" alt="image" src="https://github.com/microsoft/fluentui/assets/9615899/7f6702c3-ad98-44cd-9e2f-565044d95c84">

I assume that is what you see, but does not match what you get in your application? In that case, could you please inspect your font resolutions?

Body styles use `--fontFamilyBase` CSS variable to set font family. For any of default Fluent UI themes, this should be set to:
```
'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif
```
Font weight for `Body1Strong` is 600 (`var(--fontWeightSemibold)`). With that, Windows should use **Segoe UI Semibold** font:

<img width="635" alt="image" src="https://github.com/microsoft/fluentui/assets/9615899/37662312-28a5-4933-816f-614892fc3498">

Could you please check the font family used in your case and attach a screenshot of what you are seeing?
