### ISSUE TITLE
[Feature]: Create theme with key color

### ISSUE THREAD

**Issue by spsvietnam** [microsoft/fluentui#31784]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Export method to create theme in v9 within a key color, hue torsion and vibrancy like the way Theme Designer does

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by miroslavstastny** [comment]
Thanks for the report.
You can create a theme based on a custom brand ramp as [documented here](https://react.fluentui.dev/?path=/docs/concepts-developer-theming--page#customizing-the-theme).

There is currently no plan to add any functionality to the core library to generate the brand ramp based on any other parameters.

Closing the issue for now, feel free to comment to track the interest.

cc @brandonthomas

**Comment by spsvietnam** [comment]
Thanks for fast support.
I like ramp generated by Fluent Theme Designer. It's great if having way to create brand ramp from a key color, hue torsion and vibrancy. User can choose color from SwatchPicker, then brand ramp is generated and put the ramp into createLightTheme/createDarkTheme.
