### ISSUE TITLE
[Bug]: Fluent react v8 to v9 migration documentation out of date

### ISSUE THREAD

**Issue by barrcodes** [microsoft/fluentui#31782]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a, see description
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/barrcodes/pen/WNBzGRY

## Actual Behavior
I couldn't find an appropriate location to post this, as there does not appear to be a way to contribute on the documentation. Apologies for the extra bug report.

The document found [here](https://react.fluentui.dev/?path=/docs/concepts-migration-from-v8-component-mapping--page) is out of date. The only two components that are still in-progress are the Nav and the List. The rest of the github projects are closed, and the docs for the replacements are available.

That means the following should be linked in the docs:
- MessageBar -> MessageBar
- Panel -> Drawer
- Rating -> Rating
- TeachingBubble -> TeachingPopover
- TimePicker -> TimePickerCompat

## Expected Behavior
migration docs should match the current fluent react v9 spec

### Requested priority

Normal

### Products/sites affected

fluent react v9 documentation

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by barrcodes** [comment]
sorry, clicked the wrong library version. updated my report, but it is still tagged as northstar

**Comment by miroslavstastny** [comment]
Thanks for the report. If you would like to contribute, the source of the migration documentation is here: https://github.com/microsoft/fluentui/blob/master/apps/public-docsite-v9/src/Concepts/Migration/FromV8/ComponentMapping.stories.mdx

**Comment by khmakoto** [comment]
It seems like this was recently updated in #31841, so I'll be closing this issue.
