### ISSUE TITLE
[Bug]: MenuButton transparent appearance styling not consistent when rendered within a Popover trigger element

### ISSUE THREAD

**Issue by mashenoy** [microsoft/fluentui#31804]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/ixwcan-uutrkp?file=src%2Fexample.tsx

## Actual Behavior
Button color on rest state is blue for transparent state
https://stackblitz.com/edit/ixwcan-uutrkp?file=src%2Fexample.tsx

## Expected Behavior
Button color on rest state should be black for the transparent state
https://react.fluentui.dev/iframe.html?viewMode=docs&id=components-button-menubutton--default#appearance
![image](https://github.com/microsoft/fluentui/assets/16196129/e1a4e86b-afc4-4dc0-aa4a-928d4d8de04d)

Stackblitz Repro - 
https://stackblitz.com/edit/ixwcan-uutrkp?file=src%2Fexample.tsx

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
Looks like this was an issue in `useMenuButtonStyles`. PR added!
