### ISSUE TITLE
[Bug]: App not run in dev mode

### ISSUE THREAD

**Issue by DevJoaoLopes** [microsoft/fluentui#31928]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
branch master
```

### Are you reporting Accessibility issue?

None

### Reproduction

yarn install

## Actual Behavior

After this MR (https://github.com/microsoft/fluentui/commit/400cd5a243536dc82a7d34de17eebc896de66dc6) the app not run in dev mode

command: `yarn install`

![image](https://github.com/microsoft/fluentui/assets/27088259/10f10375-e6b2-4981-bbf8-e0f08b77e223)

### Logs

```shell

```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment]
Hi @DevJoaoLopes 👋🏻 

Thanks for reporting. I guess the reason of this is the recent removal of scopes [here](https://github.com/microsoft/fluentui/pull/31893), so react and `@fluentui/react` are conflicting 😿

**Comment by DevJoaoLopes** [comment]
@mainframev I believe this is the case, is it already being seen by anyone? I can take a look here if you prefer

**Comment by mainframev** [comment]
@DevJoaoLopes thanks for your willingness to help! I believe better will be to ping @Hotell as he is the one working on this and there is still ongoing work (#31926 in progress) 🙂

**Comment by DevJoaoLopes** [comment]
Cool, I'm waiting for updates @mainframev 😁
