### ISSUE TITLE
TagPicker: Switch suggestions to use List to fix performance

### ISSUE THREAD

**Issue by SeanK1191** [microsoft/fluentui#3195]
Package versions: office-ui-fabric-react 6.0.1, react 15.5.4

The issue:

If you have a lot of items going into a TagPicker (Around 9000 in my case), when you navigate the control using keyboard and select a Suggested Item by hitting enter, the page is unresponsive and takes around 10 seconds to finish.

When clicking! on the Suggested Item it is very fast, even with the same data set.

I tried looking into what could be causing this and I am not completely sure but the most time is being taken up during react code, I think when calling closeAll.

If you want to reproduce, you only need to pass a large number (Likely in the thousands) of items into selectedItem and then navigate the control with the keyboard and select an item using enter.

I have attached two profiles I took using the react_perf query on my website and recording performance with the chrome dev tools, you can load these profiles using the dev tools performance tab.
[Performance Profiles](https://github.com/OfficeDev/office-ui-fabric-react/files/1407452/Profile-20171023T120442.zip)

I am completely unaware of why clicking is fine and the keyboard is not, so any guidance would be appreciated. Sorry if this is a duplicate, couldn't see anything about it.

**Comment by michaelangotti** [comment]
@dzearing Can you look into this one since this is related to 6.0 branch.

**Comment by dzearing** [comment]
picker related.@joschect

**Comment by Alison-Sarah-P-C** [comment]
We are on the latest version of office Fabric and still seeing this issue

**Comment by joschect** [comment]
@Alison-Sarah-P-C I can reproduce this behavior. 
@dzearing We can probably fix this if we change the behavior of the suggestions list to virtually render the subcomponents, but I'm not sure how much work it will be.
