### ISSUE TITLE
[Bug]: Slider design needs an update when the value is set to 10 or 90

### ISSUE THREAD

**Issue by gouttierre** [microsoft/fluentui#31985]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

https://react.fluentui.dev/?path=/docs/components-slider--default

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-slider--default

## Actual Behavior
- As we discussed via mail, Zacky checked the [Figma file](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.figma.com%2Fdesign%2FIBCBJxEbPKS7CvLHG55Wn9%2FSlider%3Fnode-id%3D1512-14789%26t%3DSsrzbKTt1dTrIInB-0&data=05%7C02%7Cgogomes%40microsoft.com%7C698f303da216455bb76708dc9b907846%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638556292020882653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ABW8b8ZwNwq0WuZL4GeCNOpKKKkj55zZ0rl87%2BBzzug%3D&reserved=0), and I think the Slider issue is a design issue.
 
- The current issue is, given the slider value range is 0 to 100, when the value is set to 10 or 90, the thumb is positioned very close to the edge of the track, which could look like 0 or 100 to users. 

![Image](https://github.com/user-attachments/assets/712444a1-2c6d-4bbe-8e36-db528c31059c)

## Expected Behavior
- The Slider UI needs to be more clear to the user when the value is set to +/- 90
- Angie Badillo will review the Slider design spec [[TASK 10897](https://uifabric.visualstudio.com/iss/_workitems/edit/10897)]

### Requested priority

Blocking

### Products/sites affected

Edge

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by dmytrokirpa** [comment]
The issue will be addressed as part of #32171.
