### ISSUE TITLE
[Bug]: can't release @fluentui/react-northstar

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#32019]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

N/A

## Actual Behavior
- Trigger N* release with following options (`publishDocsiteOnly: true`)
  <img width="278" alt="image" src="https://github.com/user-attachments/assets/5d001a56-4389-411b-a488-d525ec6337f3">
- Build fails 🚨
  <img width="1134" alt="image" src="https://github.com/user-attachments/assets/4128a654-bd4d-4420-b9c6-a7bd7bd484ca">

## Expected Behavior

Build should pass

### Logs

```shell
https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=352158&view=logs&j=9f442298-0a28-5190-5c4a-ff864e098e26&t=8f67f334-8e29-5b39-4592-aeaffcba5b74

(can't paste as "comment is too long")
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
based on the variables set, you wanna also release new version of v0 or only publish and deploy new docsite ? 

if the latter you need to set `publishDocsiteOnly` to `true`

**Comment by layershifter** [comment]
> based on the variables set, do you wanna release new version of v0 as well or only publish and deploy new docsite ?

@Hotell I want just to publish docsite. Oops, updated the screentshot.

**Comment by Hotell** [comment]
problematic command `yarn workspace @fluentui/docs build`

will be resolved/fixed by https://github.com/microsoft/fluentui/pull/31926
