### ISSUE TITLE
[Bug]: Search not activating on click on search icon

### ISSUE THREAD

**Issue by vaishngupta23** [microsoft/fluentui#32015]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 36.42 GB / 63.95 GB
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/run?file=src%2Fexample.tsx

## Actual Behavior
Search not activating on click on search icon

## Expected Behavior
Search box should be activated by clicking anywhere inside the box

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Thulof** [comment]
Please update reproduction link

**Comment by sopranopillow** [comment]
As @Thulof mentioned, the repro link does not work, please update to continue working on this issue!
