### ISSUE TITLE
[Feature]: a React provider to disable motions

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#32046]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Provide a React provider or a prop to disable animations in `@fluentui/react-motion`.

### Have you discussed this feature with our team

-

### Additional context

Needed for testing scenarios and also when an app controls motion behavior.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by miroslavstastny** [comment]
Also required for low-perf devices.
