### ISSUE TITLE
[Bug]: [DetailsList] Selection gets lost when filtering

### ISSUE THREAD

**Issue by riosn-n** [microsoft/fluentui#32059]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist

### Bug Description

See attached video for details.

## Actual Behavior
Current selection is lost

## Expected Behavior
Current selection is maintained

https://github.com/user-attachments/assets/7efab7d3-d8ee-4884-8a08-fad1811a95df

### Requested priority

High

### Products/sites affected

Power Apps

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Related: #25707
