### ISSUE TITLE
[Bug]: Disabled primary button having very less color contrast ratio

### ISSUE THREAD

**Issue by v-vibsingh** [microsoft/fluentui#32076]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx
    Memory: 2.63 GB / 13.90 GB
  Browsers:
    Chrome: 124.0.6367.207
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/button

## Actual Behavior
When button is disabled and check for color contrast ratio between button text color to button's background then it appears that the ratio is less than 3:1.

![image](https://github.com/user-attachments/assets/7d47706a-b3c1-401e-b693-fc8e5bf94499)

## Expected Behavior
All the buttons should pass minimum color contrast ratio which is 3:1 for the non-compliance for accessibility.

### Requested priority

High

### Products/sites affected

https://admin.powerplatform.microsoft.com/home

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hi @v-vibsingh, this is expected behavior. Disabled buttons and labels are not expected to pass the contrast ratio. This is why it's important to avoid using disabled controls as much as possible. Increasing contrast might backfire and make people think it's not actually disabled. Thank you for the issue!
