### ISSUE TITLE
[Bug]: Not all components have their props listed on the docs site

### ISSUE THREAD

**Issue by benkaiser** [microsoft/fluentui#32070]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Issue with doc site, not specific to local version.
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-teachingpopover--default

## Actual Behavior
When viewing [documentation for components such as TeachingPopover](https://react.fluentui.dev/?path=/docs/components-teachingpopover--default), the props for TeachingPopover itself are listed, but not for any of the subcomponents. This makes it difficult to work out the purpose and use of many of the subcomponents such as TeachingPopoverBody, TeachingPopoverHeader, TeachingPopoverTitle, TeachingPopoverSurface, TeachingPopoverTrigger and TeachingPopoverFooter.

Can these be included in the documentation to prevent needing to use editor intellisense / reading the fluent source code to identify these.

## Expected Behavior
Docs site should show docs for every single exported component from the library, and ideally the searchbox should also let you search by these (e.g. TeachingPopoverFooter returns nothing, you have to remove the suffix and search TeachingPopover to see a result).

### Requested priority

Normal

### Products/sites affected

Docs

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by crperezt** [comment]
This is marked as completed but the subcomponents are still not available on the docs. https://react.fluentui.dev/?path=/docs/components-teachingpopover--docs

**Comment by khmakoto** [comment]
@crperezt can you check again? I see them available in the link you shared

![image](https://github.com/user-attachments/assets/42ae34ba-83b8-44b6-a6e6-df610daaf0f8)

**Comment by crperezt** [comment]
Ah, yes I do see them now. Sorry, I was looking for them on the left sidebar and missed them there.
