### ISSUE TITLE
[Bug]: Uncaught TypeError in WindowProvider.js: React as undefined

### ISSUE THREAD

**Issue by JotaCeR** [microsoft/fluentui#32118]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
WindowProvider.js
-----------------
import React from 'react';
/**
 * Context for providing the window.
 */
// eslint-disable-next-line @fluentui/no-context-default-value
export var WindowContext = React.createContext({
    // eslint-disable-next-line no-restricted-globals
    window: typeof window === 'object' ? window : undefined,
});
/**
 * Hook to access the window object. This can be overridden contextually using the WindowProvider.
 */
export var useWindow = function () { return React.useContext(WindowContext).window; };
/**
 * Hook to access the document object. This can be overridden contextually using the WindowProvider.
 */
export var useDocument = function () { var _a; return (_a = React.useContext(WindowContext).window) === null || _a === void 0 ? void 0 : _a.document; };
/**
 * Component to provide the window object contextually. This is useful when rendering content to an element
 * contained within a child window or iframe element, where event handlers and styling must be projected
 * to an alternative window or document.
 */
export var WindowProvider = function (props) {
    return React.createElement(WindowContext.Provider, { value: props }, props.children);
};
//# sourceMappingURL=WindowProvider.js.map
--------------------

And the error I get in the console is:

WindowProvider.js:6  Uncaught TypeError: Cannot read properties of undefined (reading 'createContext')
    at WindowProvider.js:6:28
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/jotacer/pen/vYqXMmo

## Actual Behavior
I was working on my current project in which I use @fluentui/react and react. And reinstalling dependencies yesterday I started having an issue with the file WindowProvider.js inside the @fluentui/react-window-provider/lib directory.

## Expected Behavior
So to my understanding this intern file of @fluentuit/react has trouble importing React so when it tries to use React.createContext() it cant do it since it reads React as undefined.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hi @JotaCeR, it seems the repro you posted doesn't use our library. I think the code snippet you posted is where the error points to, but this doesn't show much of the environment where this is used. Would it be possible to update the repro to use stackblitz and have the error repro while using the library rather than the code snippet you posted? Thanks!

**Comment by arvind1983** [comment]
Was this issue resolved. I am seeing the issue while using the 2.2.28 version of fluentui. 

<img width="696" alt="Image" src="https://github.com/user-attachments/assets/2aa85d3e-6c2a-47d0-a9aa-438c252354ab" />

<img width="738" alt="Image" src="https://github.com/user-attachments/assets/aeeb77db-9d1c-446e-8a85-51251db010f8" />

**Comment by aappddeevv** [comment]
Just ran into this as well. Very strange.

**Comment by aappddeevv** [comment]
This appears to be an issue where for me using vite, the bundling algorithm put the @fluentui/react-window-provider into one bundle but it was needed in another bundle. If that other bundles loads first, then React, in this case, is undefined. I made my vite rollup config output one large bundle and it all worked reinforcing that this was mostly likely the problem.
