### ISSUE TITLE
[Feature]: Can the react-icons-mdl2 support importing svg react component created by svgr

### ISSUE THREAD

**Issue by xlnhaha** [microsoft/fluentui#32184]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

For react-icons-mdl2/createSvgIcon, when transfer a react component created automatically by svgr from svg file, it would get error like this:  "Cannot convert object to primitive value"
It is caused by the classes from SvgIcon.scss is a Object which contain both root and svg, can a prop to be added to handle normal svg file, which only need svg style?

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

None

**Comment by spmonahan** [comment]
Hi @xlnhaha , thanks for opening the issue. I don't have a clear idea of your feature request. Can you share an example code snippet of how you'd like the feature to look?

**Comment by xlnhaha** [comment]
Hi @spmonahan  Thanks for your reply. 
When I tried to create icon from normal svg file using createSvgIcon exported from fluentui like this:  
const PhoneIcon = createSvgIcon({ svg: require(`../../icons/phone.svg`).default, displayName: "Phone" }); // svgr can help to handle svg file to React Component like what react-icons-mdl2/src/components do.
It would get error as in createSvgIcon, it add classes not only svg-class but also root-class, and when it runs to 
svg({ classes, props })
the component created from svg file would handle classes like this: class = '' + classes, as classes here is module/object type, it will  throw an error "Cannot convert object to primitive value".

Is it possible to add prop to handle the classes for this situation? When the icon is created from svg file and also share style from fluentui, it would be useful.

**Comment by spmonahan** [comment]
`createSvgIcon()` expect an [SvgIconChildrenFn](https://github.com/microsoft/fluentui/blob/master/packages/react-icons-mdl2/src/utils/types.ts#L10).

The `svg` argument needs to be a function because it is [called here](https://github.com/microsoft/fluentui/blob/master/packages/react-icons-mdl2/src/utils/createSvgIcon.ts#L31).
