### ISSUE TITLE
[Bug]: fluentui-react.* files removed from "dist" folder

### ISSUE THREAD

**Issue by isaacmissinghamwt** [microsoft/fluentui#32189]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
NA
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://codepen.io/pen/?template=jOVZXaW

## Actual Behaviour
Using https://unpkg.com/@fluentui/react@8/dist/fluentui-react.umd.js results in 

`Cannot find "/dist/fluentui-react.umd.js" in @fluentui/react@8.120.1`

Linked CodePen shows a blank page as dist folder now only has `react.d.ts` within it, perfectly exemplifying the issue.

## Expected Behaviour
Expected that fluentui-react.* files remain in the "dist" folder.

Unfortunately, we are not in a position to roll a hotfix by changing the <script> tag to https://unpkg.com/@fluentui/react@8.120.0/dist/fluentui-react.umd.js.

It would be ideal if backward compatibility with applications expecting a fluentui-react.* file was maintained with updates, at least until the next major version, where release notes/a warning would give time to adjust.

Only started occurring since package update 6 or so hours ago.

### Requested priority

High

### Products/sites affected

All our customers

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Confirmed the behavior using https://aka.ms/fluentpen as well.

**Comment by Hotell** [comment]
introduced here https://github.com/microsoft/fluentui/pull/32031

need to verify release logs what went wrong

**Comment by spmonahan** [comment]
> Unfortunately, we are not in a position to roll a hotfix by changing the <script> tag to

Can you clarify this point please? Is your production app dependent on the unpkg URL?

**Comment by spmonahan** [comment]
Hi @isaacmissinghamwt this is fixed now. Thanks for the bug report!

**Comment by isaacmissinghamwt** [comment]
Thanks so much for your quick response! We appreciate your hard work 🫡

**Comment by imis737** [comment]
Hi @spmonahan - it looks like this same thing has occurred again? "dist" folder is entirely missing from latest release. Is this intentional?

**Comment by khmakoto** [comment]
Hi @imis737 this should be fixed now, we have deprecated version `8.121.10` from npm and released a new version `8.121.11` that should have all assets.

**Comment by isaacmissinghamwt** [comment]
@khmakoto @Hotell @spmonahan hi guys, sorry to bother but this issue has happened yet again. 
Can we please ensure the "dist" folder is available for consumption.

**Comment by khmakoto** [comment]
Hey @isaacmissinghamwt, yes, we are aware of this and are tracking it in #34043.
