### ISSUE TITLE
[Feature]: Filter option list by input text 

### ISSUE THREAD

**Issue by Nuwanlwx** [microsoft/fluentui#32197]
### Library

React fluent UI version 8

### Describe the feature that you would like added

Filter option list by input text for combo boxes  is available in version 9 but not available in version 8

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

High

**Comment by spmonahan** [comment]
It should be possible to filter a Combobox. I think this is what you want: https://codepen.io/seanms/pen/GRbWBZm
