### ISSUE TITLE
[Docs]: Add documentation about createCSSRuleFromTheme

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#32206]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

After a few questions have come up with css extraction in a SSR environment, it has come to my attention that the createCSSRuleFromTheme is not documented. It would be nice to either add a CSS extraction recipe or some documentation page about how to use this or about when it should be used. Currently the only piece of docs about this is about web components.

#29052

### Have you discussed this feature with our team

David Zearing

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

Low

**Comment by layershifter** [comment]
https://react.fluentui.dev/?path=/docs/utilities-theme-createcssrulefromtheme--default ?

**Comment by spmonahan** [comment]
> https://react.fluentui.dev/?path=/docs/utilities-theme-createcssrulefromtheme--default ?

Glad it exists! This is another example of why I think `Utilities` should appear above `Components` on the docs site :)
