### ISSUE TITLE
[Feature]: Is there a way to select all rows or unselect all rows in datagrid

### ISSUE THREAD

**Issue by it950** [microsoft/fluentui#32219]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

In datagrid i want to do the following things:
1, select all rows outsde of datagrid, like DetailList v8 selection utility
2, unselect all rows outside of datagrid DetailList v8 selection utility
3, select the specified row by rowId,
4, get the current row that the user focused or clicked
5, get selected row not the rowId
6, add a footer to DataGrid
7, add a filter row in DataGridHeader
8, drag and drop to change grid column header order like DetailList v8

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

None

**Comment by ling1726** [comment]
This is already possible - https://stackblitz.com/edit/x5qrvk?file=src%2Fexample.tsx

The V9 pattern reverts to using React best practices that rely on state to perform selection updates instead of an imperative API.

**Comment by emmayjiang** [comment]
@it950 If there's anything left unanswered, please break down any remaining issues/feature requests into separate issues and we will take a look again. Thanks!

**Comment by it950** [comment]
@ling1726 Thanks for you reply and example, now it is very easy to use state to perform selection update in v9 DataGrid.
`
const useDataGridSelect = (items,getRowId)=>{
  const [selectedRows, setSelectedRows] = useState(new Set());
  
  const selectRow = useCallback((rowIds) => {
    // eslint-disable-next-line no-undef
    setSelectedRows(new Set(rowIds));
  }, []);

  const selectAllRow = useCallback(() => {
    if (!items) return;
    const rowIdSet = items.reduce((set, item) => {
      set.add(getRowId(item));
      return set;
      // eslint-disable-next-line no-undef
    }, new Set());

    setSelectedRows(rowIdSet);
  }, [getRowId, items]);

  const unSelectAllRow = useCallback(() => {
    // eslint-disable-next-line no-undef
    setSelectedRows(new Set([]));
  }, []);

  return {selectRow,selectAllRow,unSelectAllRow};
}
`

**Comment by it950** [comment]
@emmayjiang Thanks for your reply.
