### ISSUE TITLE
[Bug]: Dropdown: Keyboard focus rectangle doesn't grow when scrolling to the right

### ISSUE THREAD

**Issue by bwaldbaum** [microsoft/fluentui#32228]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (32) x64 AMD EPYC 7763 64-Core Processor
    Memory: 89.58 GB / 125.78 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/uyeyc5-j3jf4v?file=src%2Fexample.tsx

### Bug Description

When a Dropdown control contains a string longer than the width of control, scrolling to the right to see the rest of the string then clicking the Up arrow key to focus on the entry, it shows the keyboard focus rectangle in the original width position instead of a border around the full string.  See screenshot:

![image](https://github.com/user-attachments/assets/b9c73227-cb85-48c0-9ace-0760dfb613f1)

## Actual Behavior
Focus rectangle does not border the entire string; it goes through the middle of it.

## Expected Behavior
Focus rectangle should border the entire string.

### Requested priority

Normal

### Products/sites affected

Outlook Monarch

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@bwaldbaum so this essentially comes down to the text overflow behavior, and to define an overflow style (e.g. `overflow-wrap: no-wrap` in this case), it needs to be wrapped in a `<span>`.

I've added a story demo'ing that in the linked PR -- does that approach work to resolve your use case?

**Comment by dmytrokirpa** [comment]
@bwaldbaum, Here is an [example for Combobox](https://stackblitz.com/edit/tfmwwq?file=src%2Fexample.tsx) inspired by @smhigley's PR. Could you please check if this meets your needs or if you're seeking something different?
