### ISSUE TITLE
[Bug]: Dropdown checkbox squished when unchecked and string is longer than Dropdown width

### ISSUE THREAD

**Issue by bwaldbaum** [microsoft/fluentui#32227]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (32) x64 AMD EPYC 7763 64-Core Processor
    Memory: 89.58 GB / 125.78 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/uyeyc5-j3jf4v?file=src%2Fexample.tsx

### Bug Description

When a Dropdown contains checkboxes and the checkbox is unchecked for an entry that has a string longer than the Dropdown width, the checkbox renders squished.

Internal repro: Outlook Monarch > Settings > General > Notifications > expand top section. See screenshot below.

## Actual Behavior
Squished checkbox

## Expected Behavior
Normal, unchecked checkbox

![image](https://github.com/user-attachments/assets/cb247935-9838-4a69-b258-0b3f1bea072b)

### Requested priority

High

### Products/sites affected

Outlook Monarch

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Note: we can workaround this now by setting `flex-shrink: 0` on the icon.

Ex: https://stackblitz.com/edit/uyeyc5-mgrcph?file=src%2Fexample.tsx%3AL25

Not sure if this is the way we want to handle a fix in the library itself.

**Comment by smhigley** [comment]
@spmonahan heh, I added that exact style before I saw your comment. I don't really see any downside to adding it to our internal styles.
