### ISSUE TITLE
[Bug]: spfx fluentui theme styles do not work

### ISSUE THREAD

**Issue by Tim-Buecker** [microsoft/fluentui#32231]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 AMD EPYC 7543P 32-Core Processor
    Memory: 1.96 GB / 32.00 GB
  Browsers:
    Internet Explorer: 11.0.17763.2989

(Windows Server)

npm v: 10.7.0
node v: v18.20.4

dependencies:
                "react": "17.0.1",
		"react-dom": "17.0.1",
                "@fluentui/react": "8.106.4",
		"@fluentui/react-components": "^9.0.0",
		"@fluentui/react-datepicker-compat": "^0.4.46",
		"@fluentui/react-portal-compat": "^9.0.155",
		"@microsoft/decorators": "1.18.2",
		"@microsoft/sp-adaptive-card-extension-base": "1.18.2",
		"@microsoft/sp-application-base": "1.18.2",
		"@microsoft/sp-component-base": "1.18.2",
		"@microsoft/sp-core-library": "1.18.2",
		"@microsoft/sp-dialog": "1.18.2",
		"@microsoft/sp-http": "1.18.2",
		"@microsoft/sp-lodash-subset": "1.18.2",
		"@microsoft/sp-office-ui-fabric-core": "1.18.2",
		"@microsoft/sp-property-pane": "1.18.2",
		"@microsoft/sp-webpart-base": "1.18.2",
```

### Are you reporting an Accessibility issue?

None

### Reproduction

deploy spfx webpart with fluentui 9 and publish sitepage

## Actual Behavior
I have created a spfx webpart and use the new FluentUI v9.
After deploying the app, as well as when testing the app during development, the styling of some components is no longer displayed correctly as soon as I publish the web part on a SitePage.

The FluentProvider is already integrated in the source code. Some of the components also receive the styling of the new FluentUI. 
For some components, such as the dropdown, only the styling of the button is applied. The selection list in the dropdown has no styling at all.

## Expected Behavior
Actually, the styling of the dropdown or the selection list of the dropdown should be styled with the FluentUI. 

(If I do this entirely with a normal React app, everything works perfectly)

I suspect that the styling of the SharePoint is partially applied and thus the styling of the components of the SharePoint is partially overwritten. 

I have already read and tested the troubleshooting and migration documentation. All the solutions listed there do not work.

Web part in edit mode of sitepage:
![Screenshot 2024-08-06 082940](https://github.com/user-attachments/assets/e1c0564b-ab5d-4e20-9305-7b9af7dfe83d)

Web part after publishing the sitepage:
![Screenshot 2024-08-06 082802](https://github.com/user-attachments/assets/f88a5b8e-ceb1-4260-9bde-48bc8a9a3451)

### Requested priority

Normal

### Products/sites affected

internal company webparts

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Tim-Buecker** [comment]
I have found an interim solution.
with the IdPrefixProvider you can prevent the problem with overwriting the styling.

**Comment by bewster** [comment]
> I have found an interim solution. with the IdPrefixProvider you can prevent the problem with overwriting the styling.

How did you do this? I tried but made no difference for me.

**Comment by Tim-Buecker** [comment]
> > I have found an interim solution. with the IdPrefixProvider you can prevent the problem with overwriting the styling.
> 
> How did you do this? I tried but made no difference for me.

@bewster 
I have used the IdPrefixProvider as follows.
Then everything was rendered with the correct styles for the child components.

```JSX
<React.StrictMode>
  <IdPrefixProvider value={'YourAppName'}>
    <FluentProvider theme={lightTheme}>
      {/* // Your content */}
    </FluentProvider>
  </IdPrefixProvider>
</React.StrictMode>
```

**Comment by bewster** [comment]
Thanks @Tim-Buecker, I was only wrapping the combobox and not the entire app content.
Also didn't use `React.StrictMode`.

I had already learnt `FluentProvider`.

**Mark**
