### ISSUE TITLE
Lack of Support for Passing SharePoint Theme Colors to FluentProvider in SPFx Webpart

### ISSUE THREAD

**Issue by Rahul-Trimukhe** [microsoft/fluentui#32250]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Fluent UI version: 9.x.x
SPFx version: 1.18
SharePoint version: Online
Node: 16.x
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://github.com/Rahul-Trimukhe/FluentV9POC.git

### Bug Description

Description:
I am currently working on integrating Fluent UI 9 in a SharePoint Framework (SPFx) webpart and facing issues with passing the current SharePoint theme colors to the FluentProvider component. It seems there is a lack of direct support or documentation on how to achieve this.

Steps to Reproduce:

	1.	Set up an SPFx webpart using Fluent UI 9.
	2.	Attempt to pass the current SharePoint section theme colors to the FluentProvider component.
	3.	Notice the difficulty or lack of clear method to retrieve and apply the SharePoint theme.

Expected Behavior:
There should be a straightforward method or example provided for extracting the current SharePoint theme and passing it to the FluentProvider component in an SPFx webpart.

Current Behavior:
I am unable to find a clear way to retrieve the current section theme in SharePoint and pass it to the FluentProvider component.

### Logs

```shell
Additional Context:
It would be helpful to have detailed guidance or built-in support for this scenario, as theming integration is a common requirement when using Fluent UI in SPFx webparts. Any assistance or updates to the documentation would be appreciated.
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by pradeept95** [comment]
Hi @Rahul-Trimukhe,

I have extracted theme builder from this repo and created separate package to build fluentui v9 theme based on primary color coming from SharePoint.

Here is the working boilerplate that I created using fluent v9 with SharePoint (It allows you to change the theme  from SharePoint )

https://github.com/pradeept95/spfx-boilerplate/blob/main/src/webparts/spOnlineExample/SpOnlineExampleWebPart.ts

Additionally, I have created many other packages, that helps on SPO development, please check following link if you interested.

https://github.com/pradeept95/fluent-extension-packages
 
debounce  - To handle async debounce behavior
export-helpers - Export utilities 
fluent-common-features  - for alert, loading, confirm, etc
fluent-input-extensions - Rich Text Editor, People Picker, Tag Picker behavior
fluent-react-hook-form - Integrated all the fluent input components with react hook form
fluent-react-table-v2 - Full featured grid using fluent theme and tokens - behavior using tanstack table
fluent-theme - fluent extension package having same behavior as Theme designer (create full theme object using brand/primary color)
 react-control-flow - Control flow components (Show, Switch/Case, For etc)
spfx-core - Core behavior for SPFx project - provides global context access, auto set all pnp-sp behaviors, auto configuration of   azure app insights etc)

**Comment by emmayjiang** [comment]
This issue is external and does not require any intermediate change to Fluent UI.

**Comment by Rahul-Trimukhe** [comment]
Thanks @emmayjiang for your response. Does that mean it’s not recommended to use in Spfx?

**Comment by emmayjiang** [comment]
@Rahul-Trimukhe No, just that it's up to SharePoint to resolve the issue.

**Comment by Rahul-Trimukhe** [comment]
@VesaJuvonen Any idea about this issue?
