### ISSUE TITLE
[Bug][Facepile][Edge]: Narrator reads Facepile overflow names on focus in Edge

### ISSUE THREAD

**Issue by sergepla** [microsoft/fluentui#32274]
### Library

v8

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (32) x64 AMD EPYC 7763 64-Core Processor
    Memory: 99.94 GB / 125.78 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
```

### Are you reporting an Accessibility issue?

yes

### Reproduction

The issue can be reproduced with the "Facepile with overflow buttons" example on the Facepile doc page: https://developer.microsoft.com/en-us/fluentui#/controls/web/facepile

## Actual Behavior
The issue reproes only in Edge, Chrome and Firefox don't have it.

When navigating through controls with Narrator enabled, upon selecting the overflow button with area-label specified, Narrator reads "More users (areal-label content) <pause> Button <pause> <The list of people names in the overflow>".

The issue can be reproduced with the "Facepile with overflow buttons" example on the Facepile doc page: https://developer.microsoft.com/en-us/fluentui#/controls/web/facepile

## Expected Behavior
Narrator should read only "More users (areal-label content) <pause> Button" on focus.

https://github.com/user-attachments/assets/5cde8c5c-434e-45a4-8529-f34065915383

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
This behavior is certainly intentional as screen reader text is added to the page

![image](https://github.com/user-attachments/assets/ca04bb10-8bb9-47d1-b6cf-7e556d3ccaaf)
