### ISSUE TITLE
[Bug]: react-dialog / drawer pushes elements a little extra to the right side

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#32270]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 52.05 GB / 63.57 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/qy7eyr-7mlpy8?file=src%2Fexample.tsx

## Actual Behavior
We recently upgraded fluentui/react-components from 9.47.1 to 9.54.4, @fluentui/react-drawer upgraded from 9.1.9 to 9.5.7, @fluentui/react-dialog from 9.9.15 to 9.11.7. The more detailed package changes is in the internal teams channel.
 
When using drawer opened from right, the scrollbar seems to take up empty blank space, the elements seem to be pushed to the right side as screenshot shows:

![image](https://github.com/user-attachments/assets/df8ffccb-007e-439a-86e1-c9ebc7f7a200)

## Expected Behavior
Do not expect the blank space of scrollbar and the content should not be pushed to the right.

![image](https://github.com/user-attachments/assets/c090eebf-1179-4420-8fe1-9f1f880e54c7)

Expected behavior sandbox:
https://stackblitz.com/edit/qy7eyr-51y176?file=package.json

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
That extra space is the width of the scroll bar. 

![image](https://github.com/user-attachments/assets/8eeba8ee-a926-414b-9ee9-db9d4b97479a)

![image](https://github.com/user-attachments/assets/8978af33-0212-4d15-a115-4d3fdf1980fb)

**Comment by flora8984461** [comment]
@micahgodbolt thank you for the info. 
In the older version, the scrollbar white space will be taken up when the dialog / drawer shows. Is it still possible with the newer version? Thanks!

**Comment by miroslavstastny** [comment]
@bsunderhus please check this one, might be related to recent scrollbar-related changes.

**Comment by flora8984461** [comment]
@bsunderhus Thank you for the help!

Using `position: absolute`, the experience is somehow different from `fixed`.  For example, if we scroll down, the header is still there (fixed) and scroll away (absolute). I made [another sample](https://stackblitz.com/edit/qy7eyr-xz7zpw?file=src%2Fexample.tsx) which might work for our expected UX experience: 
Make the container for all contents below the header as: 
```
        style={{
          overflow: 'scroll',
          position: 'absolute',
          height: '100vh',
          width: '100vw',
        }}
```
Inspiration from viva insights web app 😄. 

I still need to experiment this with our real app and discuss with the team about this layout change. Will let you know once I have more discussions. 

Additionally, is it possible to expose an option to keep the older behavior? 

Thank you! 🙏

**Comment by bsunderhus** [comment]
> Additionally, is it possible to expose an option to keep the older behavior?

This sounds dangerous to me @flora8984461 👀, as the old behaviour would not account for animation jumps. it's a delicate balance ⚖️.

If `position: absolute` is not a possibility in your case, I'd suggest keeping the `position: fixed` with some `padding-right` strategy to account for the gutter width. You can use our helper method [useScrollbarWidth](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-utilities/src/hooks/useScrollbarWidth.ts) to measure how big the gutter will be while doing this calculations!

**Comment by layershifter** [comment]
Closing it as according to @bsunderhus we are not going to fix it.

**Comment by flora8984461** [comment]
Thank you for the help! I will discuss this design with the team. @bsunderhus
