### ISSUE TITLE
[Bug]: v8 snapshot tests are not updating

### ISSUE THREAD

**Issue by emmayjiang** [microsoft/fluentui#32284]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 7.86 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Edge: 127.0.2651.98
    Safari: 17.6
```

### Are you reporting an Accessibility issue?

None

### Reproduction

n/a

## Actual Behavior
The commands `just jest -u` and `update-snapshots` are not updating v8 snapshots. Even with `just jest --watch`, there are two failing holdouts that will not update. Blocking #32264 

## Expected Behavior
The snapshots update correctly.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by emmayjiang** [comment]
Tagging @microsoft/fluentui-react-build to take a look at this issue please!

**Comment by Hotell** [comment]
can you be more specific please ? I'm unable to repro. Also the PR you references is passing.

`yarn nx run react:test --watch`

<img width="668" alt="image" src="https://github.com/user-attachments/assets/c1efe546-559b-47a4-bde3-53368bb934b8">

pressing `u`  (update snapshots)

<img width="585" alt="image" src="https://github.com/user-attachments/assets/90f70a16-5ba0-4db8-8d7d-34e3db3bf8eb">

**Comment by emmayjiang** [comment]
@Hotell We were eventually able to update it manually via `--watch` and pressing `u` for each snapshot, but they weren't updating with `just jest -u`

**Comment by Hotell** [comment]
ah gotcha! fix is on it's way.
