### ISSUE TITLE
[Feature]: Ranges in Slider

### ISSUE THREAD

**Issue by MarcusDunn** [microsoft/fluentui#32283]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Double slider for selecting ranges of values. Similar to MUI's [RangeSlider](https://mui.com/material-ui/react-slider/#range-slider).

### Additional context

This would be used for selecting a range of valid integer values to search for (e.g. ratings out of five between 3-5).

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

Low

**Comment by layershifter** [comment]
Duplicate of #30617.
