### ISSUE TITLE
[Bug]: Narrator only reads a toast the first time it is dispatched.

### ISSUE THREAD

**Issue by dustinroepsch** [microsoft/fluentui#32282]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
This bug is found on the storybook for v9
```

### Are you reporting an Accessibility issue?

yes

### Reproduction

https://react.fluentui.dev/?path=/docs/components-toast--default

## Actual Behavior

1) Turn on windows narrator
2) Go to the Toast storybook page here: https://react.fluentui.dev/?path=/docs/components-toast--default
3) Click on a button to dispatch a toast
   - The narrator properly reads this toast out loud
4) Click on the same button again to dispatch another toast
   - The narrator remains silent

## Expected Behavior
1) Turn on windows narrator
2) Go to the Toast storybook page here: https://react.fluentui.dev/?path=/docs/components-toast--default
3) Click on a button to dispatch a toast
   - The narrator properly reads this toast out loud
4) Click on the same button again to dispatch another toast
   - The narrator should read the contents of the toast again

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
Can confirm that this bug reproduces using Narrator on Edge. It doesn't reproduce when using NVDA however. There's a bug filed specifically on Narrator regarding it not announcing live region text if the same text is announced twice so closing this as external.
