### ISSUE TITLE
[Bug]: MenuList out-grows window if opened to top / MenuList extends the view port to the bottom if opened to bottom

### ISSUE THREAD

**Issue by mathis-m** [microsoft/fluentui#32311]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
"@fluentui/react-components": "^9.54.7",
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/s9pvg7?file=src%2Fexample.tsx

## Actual Behavior
1. Place Menu after center of height of the page, so that it opens to the top
2. Add so many options, so that it out-grows the window
3. Open the menu
4. The most upper options are not visible and can not be scrolled into the view
![image](https://github.com/user-attachments/assets/d9ec98a6-a1f3-4cea-9ed4-aa94118d67af)

## Expected Behavior
1. Open menu at any position
2. If the list does not fit into the view port, make it scrollable
3. It does not extend the view port to the bottom
4. It does not out grow the view port in the top
5. All options can be accessible via scroll inside the menu, not scrolling the page

Essentially, this should be the same as when using a dropdown list.

### Logs

```shell
n/a
```

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Please check `autoSize`, https://react.fluentui.dev/?path=/docs/concepts-developer-positioning-components--docs#auto-size-for-small-viewport

```tsx
 <Menu positioning={{ autoSize: true }} />
```

**Comment by mathis-m** [comment]
Yeah that works, thanks.

But should this not be set by default? Or at least add a example on configuration in the menu storybook :)

**Comment by layershifter** [comment]
> But should this not be set by default?

It should be, but it would be a breaking changes, that's why it's opt-in.

> Or at least add a example on configuration in the menu storybook :)

There is an issue to improve discoverability, #25098 🐱 

----

Going to close it as it was resolved.

**Comment by Weffe** [comment]
@layershifter I would consider calling out this behavior in the migration from v8 to v9 because currently in v8 this is the default behavior:

I took an example codepen [from the v8 docs](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/contextualmenu) and recreated this scenario with a lot of menu items: 

https://codepen.io/zxc7777/pen/oNrrMbr

I would consider this a breaking behavior in the upgrade path to v9 and the only way to get the old behavior is to set `autoSize: true`

**Comment by LauraAlspaugh** [comment]
We ran into this issue also, when upgrading to V9. Having this behavior transition highlighted in the docs would have been helpful.
