### ISSUE TITLE
[pr 32008][Guage chart] When we toggle on Enable Gradient the colors of the chart are not changing.

### ISSUE THREAD

**Issue by AtishayMsft** [microsoft/fluentui#32328]
Repro steps:
1.click on above link provided.
2.click on any Gauge Chart 
3.toggle on Enable Gradient the colors
4.observe

Actual behavior:
When we toggle on Enable Gradient the colors of the chart are not changing. when it is on the colors of the chart are thick when we off the colors of the charts are light

Expected behavior:
colors should change as the toggle on Enable Gradient on the chart

Note: please find attached Video for reference.

https://github.com/user-attachments/assets/c65e477d-1082-4cca-a24b-b9889779076f

**Comment by AtishayMsft** [comment]
@t-shawngrant  It looks like the gray color shifts when toggling the gradient. It should be #e6e6e6 for both states.

**Comment by shawn-grant** [comment]
The colors are changing, but the gradients specified for this example were `DataVizGradientPalette.success`,  `DataVizGradientPalette.warning`, and  `DataVizGradientPalette.error`.
Should the default gradient order be used instead?

**Comment by shawn-grant** [comment]
> The first part with status colors is fine. Could you fix the second part and modify the color tokens of gray color as mentioned by Tor.
> 
> > It looks like the gray color shifts when toggling the gradient. It should be #e6e6e6 for both states.

Ok, will open a PR for this

**Comment by shawn-grant** [comment]
> The first part with status colors is fine. Could you fix the second part and modify the color tokens of gray color as mentioned by Tor.
> 
> > It looks like the gray color shifts when toggling the gradient. It should be #e6e6e6 for both states.

Resolved in #32340
