### ISSUE TITLE
[Bug]: BreadcrumbButton icon size and margin are not aligned with base Button component

### ISSUE THREAD

**Issue by soniaboller** [microsoft/fluentui#32342]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 118.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 127.0.6533.120
    Edge: 127.0.2651.105
    Safari: 17.6
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/sykmjn?file=src%2Fexample.tsx

## Actual Behavior
There's a discrepancy between the icon size and margin for the BreadcrumbButton and the Button component.
![image](https://github.com/user-attachments/assets/e56cf5be-4707-436e-b463-4f7ebe2f7c8f)
^ [BreadcrumbButton](https://react.fluentui.dev/?path=/docs/components-breadcrumb--docs)
![image](https://github.com/user-attachments/assets/02c15b3a-1cc9-459b-9f9d-6e4a1394f6d8)
^ [Button](https://react.fluentui.dev/?path=/docs/components-button-button--docs)

From the designs you can see that the BreadcrumbButton uses the Button as the base component, but it appears out of sync with the current Button.
![image](https://github.com/user-attachments/assets/715ef022-47ec-40fa-a487-f468f8de4b94)
^ [BreadcrumbButton designs](https://www.figma.com/design/guRLHkt8rh5eRO9Z78tuQy/Microsoft-Fluent-2-Web-(Community)?node-id=8934-32418&t=cKUqnXZObtzYr75S-4)
![image](https://github.com/user-attachments/assets/c36e2ed7-1c58-4291-92ad-9bc0c2ce4219)
^ [Button designs](https://www.figma.com/design/guRLHkt8rh5eRO9Z78tuQy/Microsoft-Fluent-2-Web-(Community)?node-id=8934-16537&t=cKUqnXZObtzYr75S-4)

It also looks like some custom [styles](https://github.com/microsoft/fluentui/pull/29623/files#diff-a3cf7a0d7eb95556a94835e474f72e56012dbe019113408abc59943817c519c2) were added specifically to the BreadcrumbButton, which override the base Button styles, but this feels like it might be an oversight since the designs use the Button component in the BreadcrumbButton so the expectation is that the BreadcrumbButton would have the same styles as the Button.

## Expected Behavior
Since the BreadcrumbButton uses the Button as its base component they should have the same icon size and icon margin.

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by soniaboller** [comment]
Hi Tristan, thanks for getting back to me!

Yeah, I see that in the guidance, but then in that documentation there's a link to "View details from Button"
<img width="684" alt="image" src="https://github.com/user-attachments/assets/b92e1dcb-3646-4839-8640-80387d5e1683">
and when you click on that it takes you to the [Button guidance](https://www.figma.com/design/Nj9EBBvOZmS11zKNJfilVR/Button?node-id=4428-13409&t=uspHk2AFTqpSZLEA-4), which has different icon sizes and spacing.

Small
<img width="514" alt="image" src="https://github.com/user-attachments/assets/423f5d72-12d5-48d6-b9ba-167f4ac4c41a">
Medium
<img width="512" alt="image" src="https://github.com/user-attachments/assets/a8458461-8674-40a3-80bc-103dbd29619f">
Large
<img width="509" alt="image" src="https://github.com/user-attachments/assets/c9709078-4872-4797-84ba-d4ddc69412a6">

So I just want to confirm from a design perspective that the `BreadcrumbButton` is supposed to have different styles from the `Button`, despite the fact that the Button is used as a base component for the `BreadcrumbButton` and is referenced in the designs. Just want to make sure this this isn't an oversight from design.

**Comment by TristanWatanabe** [comment]
@soniaboller spoke with design and can confirm that this was done intentionally because for `Breadcrumb`, they had to take into account making the Breadcrumb strings balanced hence the reduced margins and icon size.

**Comment by soniaboller** [comment]
Awesome, thank you for checking on that for me!
