### ISSUE TITLE
[Bug]: Button-like Anchor doesn't have vertically centered text

### ISSUE THREAD

**Issue by Aidam1** [microsoft/fluentui#32378]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
-
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/button

## Actual Behavior
Text isn't centered. This is screenshot from fluent v8 button documentation:
![image](https://github.com/user-attachments/assets/5f3c0cea-f214-40f1-a93f-5141ac02fe04)

## Expected Behavior
Text is centered the same as in other types of button

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@Hotell assiging to you since you made the PR
