### ISSUE TITLE
[Bug]: calling onClick handler on TreeItem on every single click, not filtering clicks from action, subtree or selection. 

### ISSUE THREAD

**Issue by anuj7676** [microsoft/fluentui#32390]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/b4iyu4-zbjym5?file=src%2Fexample.tsx,index.html

### Bug Description

This is a regression on Fluent side, here we are calling onClick handler on TreeItem on every single click, we're not filtering clicks from action, subtree or selection. 
 
Seems like it's another ripple effect from this https://github.com/microsoft/fluentui/pull/31766
 
Previous to the bugfix from #31766, we would use onOpenChange method, which filtered those cases, now that onOpenChange is no longer being called we should filter directly on onClick?!

## Actual Behavior
calling onClick handler on TreeItem on every single click, we're not filtering clicks from action, subtree or selection. 

## Expected Behavior
filter clicks from action, subtree or selection. 

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
@anuj7676  can you please provide repro that showcases the issue ? your link opens blank stackblitz.

Note that without repro we are unable to investigate further and the issue will be closed. thanks

**Comment by anuj7676** [comment]
@Hotell I have updated the stackblitz link. Please let me know if this is helpful - 

https://stackblitz.com/edit/b4iyu4-4mmxw4?file=src%2Fexample.tsx,index.html

**Comment by bsunderhus** [comment]
This has already been resolved here: https://github.com/microsoft/fluentui/pull/32434

**Comment by miroslavstastny** [comment]
Fixed, closing

**Comment by anuj7676** [comment]
@bsunderhus @miroslavstastny can you please let me know when the next release will be. Can you please let me know any ETA. Thanks

**Comment by bsunderhus** [comment]
It has been released already @anuj7676 https://github.com/microsoft/fluentui/releases/tag/%40fluentui%2Freact-tree_v9.8.0
