### ISSUE TITLE
[Bug]: Button autofocus does nothing

### ISSUE THREAD

**Issue by mohamedmansour** [microsoft/fluentui#32394]
### Library

Web Components (@fluentui/web-components)

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (20) x64 Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz
    Memory: 52.99 GB / 62.39 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Browsers:
    Chrome: 128.0.6613.84
  Packages:
    "@fluentui/web-components": "3.0.0-beta.39",
    "@microsoft/fast-element": "2.0.0-beta.26",

According to the code https://github.com/microsoft/fluentui/blob/master/packages/web-components/src/button/button.ts#L30 there is `autofocus` but it isn't being used. 

<fluent-button autofocus>Click</fluent-button>
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/typescript-nsy8jf?file=index.ts

### Bug Description

Autofocus is not implemented but defined in button.ts https://github.com/microsoft/fluentui/blob/master/packages/web-components/src/button/button.ts#L30

Right now devs are doing this:
```
<fluent-button
    ${ref('primaryButtonRef')}>
```
and 
```
      const primaryButton = this.primaryButtonRef;
      if (primaryButton) {
        primaryButton.focus();
      }
```

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by radium-v** [comment]
The provided stackblitz demo works for me in Edge and Chrome when viewing the preview in a new tab (after clicking "run this project" and refreshing the page).

**Comment by chrisdholt** [comment]
> The provided stackblitz demo works for me in Edge and Chrome when viewing the preview in a new tab (after clicking "run this project" and refreshing the page).

Yeah I see the same and the issue exists within stackblitz for regular buttons as well.

**Comment by radium-v** [comment]
We may just want to remove the explicitly defined attribute to avoid confusion or conflicts with the global attribute.

**Comment by mohamedmansour** [comment]
False alarm, in Chromium development we have two origins one trusted chrome://foo and untrusted (for trusted content), chrome-untrusted://foo  (for untrusted content). 

So sending focus to untrusted yields this error, so that is why we need JS for the initial focus.
```
console: Autofocusing on an element within a cross-origin subframe is generally blocked by modern browsers due to security restriction.
```
