### ISSUE TITLE
[Feature]: Spinner root slot as span

### ISSUE THREAD

**Issue by mathis-m** [microsoft/fluentui#32416]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

It would be great to allow `span` root slot type for the `Spinner` component.
This would help to keep the dom nesting valid for a scenario where a spinner needs to be inside a `Paragraph` element.

Currently I need to cast the `as` prop to make this work:

```tsx
<Spinner as={"span" as unknown as "div"}/>
```

### Additional context

My use-case is a spinner within a richtext editor.  
Users can add certain custom elements to the richtext which are requiring async data load.  
While loading the spinner should be displayed.  
As this is a richtext editor the root element of each paragraph the user is entering is a `p` tag.

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

Low

**Comment by Hotell** [comment]
not sure if this is a bug on our side as spec mentions `span` for root element ? @tomi-msft  https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-spinner/library/docs/Spec.md?plain=1#L73

**Comment by mathis-m** [comment]
https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-spinner/library/src/components/Spinner/Spinner.types.ts#L9
