### ISSUE TITLE
[Feature]: Dialog stories do not include an example for customizing (or disabling) motion

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#32411]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

The dialog documentation / stories does not include information on how to customize or disable animations. The only information is a brief mention of the types for `surfaceMotion`. In fact `backdropMotion` is not even mentioned in the docs. 

### Additional context

This issue comes from a partner request about "how to disable motion on dialog". 

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by tudorpopams** [comment]
@bsunderhus would you be able to also update the `Dialog` docs to mention the `backdropMotion` prop as well? As Justin says here, there's no mention for it anywhere for now.

**Comment by layershifter** [comment]
The same is applicable there https://github.com/microsoft/fluentui/issues/32432#issuecomment-2324687163

**Comment by bsunderhus** [comment]
> > UPDATE: We did a new release for the v9 storybook and [sub component tabs are now back](https://react.fluentui.dev/?path=/docs/components-dialog--docs), which include `DialogSurface` that mentions `backdropMotion`.
> 
> This is great, thanks!
> 
> @tudorpopams, @bsunderhus Should we also have a story showing how to customize motion?

We have a section in our stories on how to customize motion @JustSlone, I believe on the `Dialog` side is enough to show what property gives access to motion, and then it becomes users responsibility to research `Motion` on our docs 😁
![image](https://github.com/user-attachments/assets/29521148-9056-44eb-8ee4-089e2a18e93b)

**Comment by miroslavstastny** [comment]
We need general motion doc page in storybook about this.
