### ISSUE TITLE
[Feature]: Drawer lost focuse when use a dialog in it

### ISSUE THREAD

**Issue by it950** [microsoft/fluentui#32429]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

The Drawer component will lost focuse when invoke a Dialog by shortkey(CTRL+ALT) like, the following picture: 
1, first, i create sales order by press CTRL+ALT
2, then press the CTRL+ALT again, an error message show in Dialog
3, Press then enter to close Dialog
4, The focuse lost from Drawer
![drawer-with-dialog-lost focus](https://github.com/user-attachments/assets/95b645a9-7076-4bcb-84d6-034d6c5283dc)

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

None

**Comment by marcosmoura** [comment]
Since the two issues are quite similar, I'm closing this one to focus the conversation in only one place.
