### ISSUE TITLE
[Feature]: The react-data-grid-react-window vertical scrollbar can not display

### ISSUE THREAD

**Issue by it950** [microsoft/fluentui#32428]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

When the columns are too many, the vertical bar can not display:
![image](https://github.com/user-attachments/assets/7feecaf9-3d15-4f7d-bc3a-2478f8ecf3ff)

only when scroll horizontal bar to the right, the vertical bar can display:
![image](https://github.com/user-attachments/assets/a6cee0c5-0433-47fd-8fbf-5e58ab91f5c4)

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

None

**Comment by nanivijay** [comment]
I am facing the same issue. any solution fr this?
