### ISSUE TITLE
[Bug]: Drawer focus is lost after opening a dialog from it

### ISSUE THREAD

**Issue by chadsowald** [microsoft/fluentui#32440]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 29.82 GB / 63.95 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/mgba2r?file=src%2Fexample.tsx

## Actual Behavior
Drawer (and the form inside it) lose focus and cannot get it back.

## Expected Behavior
The Drawer and form should have focused restored after the Dialog is closed.

## Minimal repro
https://stackblitz.com/edit/mgba2r?file=src%2Fexample.tsx

## Similar bug (but it's missing a repro)
https://github.com/microsoft/fluentui/issues/32429

## Context
Our product uses this pattern frequently to warn the user they will lose the info they entered in the form if they dismiss/close it.  We're upgrading from v8 to v9 and are blocked on migrating this behavior.  I see at least one other bug someone has filed for a completely different product with the same problem.

### Requested priority

Blocking

### Products/sites affected

Dynamics 365 Fraud Protection

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by marcosmoura** [comment]
@chadsowald 
The issue here is that Dialog cannot know how to restore focus unless the `<DialogTrigger>` is used. This is stated in [our documentation](https://react.fluentui.dev/?path=/docs/components-dialog--docs#trigger-outside-dialog), alongside with alternatives on how to implement the focus restore feature.

I went ahead and created a [Stackblitz example](https://stackblitz.com/edit/mgba2r-gpbrrm?file=src/example.tsx) with this behavior applied, which fixes the repro. Let us know if that makes sense. I'll be closing the issue for now, but in case there are more things to be discussed, feel free to reopen it.

**Comment by chadsowald** [comment]
Thanks @marcosmoura.  Just wanted to follow up that I ended up going with another solution that I wanted to share.

In the Panel/Drawer that opens the dismiss confirmation dialog I added this:

```
React.useEffect(() => {
	const focusWatcher = (focusEvent: FocusEvent) => {
		const el = focusEvent.target as HTMLElement;
		if (el?.closest('.MyPanelContent')) { //Just some class that wraps all the panel content importantly, name not important
			lastFocusedElement.current = el;
		}
	};

	document.addEventListener('focusout', focusWatcher);

	return () => document.removeEventListener('focusout', focusWatcher);
}, []);
```

And then in the dismiss confirmation dialog's dismiss handler (and only the dismiss handler, not the primary click handler) we run:

```lastFocusedElement.current?.focus();```

The thing that gets me is that this seems like something FluentV9 should handle.  Specifically:

- DialogTrigger is very hard to use on V8 --> V9 migrations.  Most of our Dialogs are in separate components from where we have the button that opens them, making wrapping the whole thing in a Dialog (to ultimately wrap the button in DialogTrigger) a large undertaking.  It's also impossible to use DialogTrigger in scenarios where other libraries have event handlers that we trigger Dialogs from.
- The restore focus hook implies you know which control to always focus back on.  It's not flexible.  It also means you have to use function components.  Our product has a mix of class components and function components, and again it's a lot of extra work to migrate just to use one hook here or there.

For those 2 reasons, please consider building something in V9 that can automatically restore focus without the need to use one of those two things above.

**Comment by petrachemarincognizant** [comment]
> @chadsowald The issue here is that Dialog cannot know how to restore focus unless the `<DialogTrigger>` is used. This is stated in [our documentation](https://react.fluentui.dev/?path=/docs/components-dialog--docs#trigger-outside-dialog), alongside with alternatives on how to implement the focus restore feature.
> 
> I went ahead and created a [Stackblitz example](https://stackblitz.com/edit/mgba2r-gpbrrm?file=src/example.tsx) with this behavior applied, which fixes the repro. Let us know if that makes sense. I'll be closing the issue for now, but in case there are more things to be discussed, feel free to reopen it.

Hi @marcosmoura,

It seems there is still an issue that might be related with the active "element", if you would have a page with vertical scrollbar and then open a drawer from it(the scrollbar disappear as normally if drawer content fits into the screen ), open a dialog, close the dialog, the scrollbar would appear and would scroll the body behind the drawer.

Closing the drawer and reopen it again would remove the scrollbar, but of course doing the steps again would make it to reappear.

Do you have any solution for it?

![Screenshot 2024-09-24 at 03 57 53](https://github.com/user-attachments/assets/71154481-c972-4b55-9081-01f1f1f30779)
![Screenshot 2024-09-24 at 03 58 21](https://github.com/user-attachments/assets/e418c081-ea75-4ac9-b0bb-a4278a3b9289)
