### ISSUE TITLE
[Bug]: Nav Bar NavCategory closes when redirected by NavSubItem link

### ISSUE THREAD

**Issue by ayma-kw** [microsoft/fluentui#32446]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 14.80 GB / 31.83 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://msazure.visualstudio.com/Azure%20Mission%20Platform%20GRC/_git/embark

## Actual Behavior
When internally redirecting to a different page linked by one of the nav sub items (using React's navigate) nav category closes. There is no state within nav bar to keep it open, so user has to reopen the category to click on a different nav sub item each time.
## Expected Behavior
When internally redirecting to a different page, nav category should stay open. There must be a controlled state

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by marcosmoura** [comment]
@ayma-kw 
The link for the repro is not correct. Could you create an example on Stackblitz on how to reproduce this issue?

**Comment by ayma-kw** [comment]
No longer can reproduce - closing.
