### ISSUE TITLE
[Bug]: Global Storybook styles are being applied to story elements

### ISSUE THREAD

**Issue by marcosmoura** [microsoft/fluentui#32471]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
.
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-drawer--docs#separator

### Bug Description

Some elements inside the stories examples are affected by global CSS used to style main global Storybook elements. This was not the case for Storybook 6 since it uses iframes. Now with Storybook 7, some styles are broken.

For example, global styles applied to h2 titles are affecting stories that contain a v9 component that renders a h2 tag:

Current:
![image](https://github.com/user-attachments/assets/323b2724-972f-4d31-b188-b29a67375b16)

Expected:
![image](https://github.com/user-attachments/assets/5fe4eb04-f099-4d8b-adac-c6d9401e910c)

For this specific issue, the culprit is the selector `#storybook-docs .sbdocs h2`, but our `docs-root.css` file has several global styles that applies to all storybook examples.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
<img width="342" alt="image" src="https://github.com/user-attachments/assets/29605a3a-2458-4e97-b88d-37adf5dba6c3">

Another breaking style.
