### ISSUE TITLE
[Feature]: SpinButton required

### ISSUE THREAD

**Issue by davidrsch** [microsoft/fluentui#32478]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Add the possibility to mark a SpinButton as required

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

None

**Comment by ValentinaKozlova** [comment]
Could you please add more details about this feature? What exactly do you want? Should it be built in validation of a SpinButton and design change?
Currently you can use `<Label htmlFor={id} required>` to show a required field.

**Comment by davidrsch** [comment]
I think it would be nice to have the possibility of specifying required at SpinButton itself like with other inputs:
```
<SpinButton 
        label="Must specify a value:"
        min={0}
        max={10}
        required
/>
```

**Comment by ValentinaKozlova** [comment]
> I think it would be nice to have the possibility of specifying required at SpinButton itself like with other inputs:
> 
> ```
> <SpinButton 
>         label="Must specify a value:"
>         min={0}
>         max={10}
>         required
> />
> ```

I added your request to PM board. They'll review it

**Comment by tudorpopams** [comment]
hello @davidrsch , to mark v9 form components such as Input, Field, and SpinButton as required, you can utilise the `required` property available in the Field component. This property not only visually indicates that a field is required (by appending a red asterisk to the label) but also sets the `aria-required` attribute on the child input component, enhancing accessibility for users with disabilities.

 **SpinButton Example**: Similarly, you can use the SpinButton within a Field to mark it as required.

   ```jsx
   <Field required label="Quantity">
       <SpinButton />
   </Field>
   ```

**Validation Message**: You can also provide a validation message to inform users about the requirement. This can be done by using the `validationMessage` property of the Field component.

   ```jsx
   <Field required label="Email" validationMessage="Email is required">
       <Input />
   </Field>
   ```

**Accessibility Considerations**

By marking fields as required, you ensure that screen readers announce the requirement to users, which is crucial for accessibility. The `aria-required` attribute is automatically added to the input elements, making it clear that the field must be filled out before submission.

**Comment by davidrsch** [comment]
Thanks
