### ISSUE TITLE
[Bug]: GroupedList bouncing scrollbar in an infinite loop

### ISSUE THREAD

**Issue by mihir0** [microsoft/fluentui#32826]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
OS: Microsoft Windows 11 Enterprise, Version 10.0.22631 Build 22631
CPU: AMD EPYC 7763 64-Core Processor
Installed RAM: 64.0 GB

Browser:
Edge: 128.0.2739.63
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://codepen.io/mihirpar_microsoft/pen/ExBrOrX

## Description
When fully expanding all of the nested groups in each row of a grouped list, scrolling down to the bottom causing the scroll bar to jump up and down in an infinite loop. 

## Reproduction
1) Go to the codepen https://codepen.io/mihirpar_microsoft/pen/ExBrOrX or GroupedList fluent component on the developer docs: https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist
2) Fully expand all of the groups in the list
3) Click and drag the scroll bar to the bottom of the list

## Actual Behavior
The scrollbar quickly jumps up and down, in an infinite loop. View attached screen recording to see this behavior.
https://github.com/user-attachments/assets/e8109b9d-efb6-40fe-be15-d1738b31ce51

## Expected Behavior
The scrollbar should remain stationary in the position that it was left in. No bouncing is expected.

### Requested priority

High

### Products/sites affected

SharePoint

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@mihir0 Can you try using `GroupedListV2` -- it fixes this specific issue.

Example usage is here: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/groupedv2
