### ISSUE TITLE
[Bug]: Search not activating on click on search icon

### ISSUE THREAD

**Issue by vaishngupta23** [microsoft/fluentui#32848]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 36.42 GB / 63.95 GB
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/crazy-galois-kys3nk?file=%2Fsrc%2FApp.tsx

## Actual Behavior
Search not activating on click on search glass icon. The search box goes out of focus when clicked on this icon.

![image](https://github.com/user-attachments/assets/5a349e3d-65f9-4d9a-b6f1-a1ea6cc05287)

## Expected Behavior
Search should activate on clicking on the search glass icon

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment]
@vaishngupta23 hi 👋🏻 

I think it was made like that on purpose and it's a decorative / presentational icons that won't trigger input focus. If you would like to make it actionable, you should use `Button` with icon. (See [contentBefore/contentAfter](https://react.fluentui.dev/?path=/docs/components-input--docs#content-before-after) example).
