### ISSUE TITLE
[Bug]: Carousel card is set to inert

### ISSUE THREAD

**Issue by hannkim-msft** [microsoft/fluentui#32847]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 34.94 GB / 63.95 GB
  Browsers:
    Edge: Chromium (128.0.2739.63)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/k2qafx?file=src%2Fexample.tsx%3AL79

## Actual Behavior
Trying to create a carousel with free layout and inline nav buttons where each carousel card is a button. However, if the content of the current card is cut off by the next button due to the max width of the carousel, it is no longer clickable as the card is set to 'inert'. 

## Expected Behavior
Carousel should have free layout and the current card should still be clickable, even if the text is cut off.

### Requested priority

Normal

### Products/sites affected

Power Apps

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment]
@hannkim-msft It might be expected behaviour, as not visible elements should have aria-hidden. Carousel is using Embla carousel inside and it might need to adjust some option like [inviewthreshold](https://www.embla-carousel.com/api/options/#inviewthreshold), so half hidden elements are considered visible. I will keep it as bug and let the owner decide.

**Comment by Mitch-At-Work** [comment]
Hi @hannkim-msft - for Carousels with multiple cards or partial cards in view, we recommend setting the 'cardFocus' prop to 'true' on CarouselSlider, this is our intended accessible format to ensure multi-card views are fully accessible and keyboard navigable, you can then select the cards via focus and press 'enter' to dive into the tab group.

This will also remove the 'inert' functionality which is intended for full width banner carousel cards.

**Comment by hannkim-msft** [comment]
Awesome, just tried this out! 

I was using an older version that didn't include this change. Thanks for the update!
