### ISSUE TITLE
[Bug]: Can't resize columns in DetailsList on mobile

### ISSUE THREAD

**Issue by WillHavelin** [microsoft/fluentui#32857]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Android phone in chrome browser
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://codepen.io/wHavelin/pen/VwJJxJx

## Actual Behavior
On my desktop, I can resize the columns by clicking the seperation between two columns and draggging the columns to resize. On my phone, I can't find anyway to resize the columns.

## Expected Behavior
I expect to be able to resize the columns even if I am using a device like a phone.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment]
@WillHavelin hi 👋🏻 

Thanks for reporting. I found that this bug [was already reported](https://github.com/microsoft/fluentui/issues/22873) before, but somehow wasn't reproduced. It's not about android specifically, any mobile in general.

**Comment by WillHavelin** [comment]
Let me know if you have any questions about the repro. Also, do you have an estimate for when it will be fixed?

> @WillHavelin hi 👋🏻
> 
> Thanks for reporting. I found that this bug [was already reported](https://github.com/microsoft/fluentui/issues/22873) before, but wasn't reproduced. It's not about android specifically, any mobile in general.

**Comment by spmonahan** [comment]
We have an example demonstrating how to resize columns via the keyboard that I've confirmed works for iOS as well.

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/keyboardcolumnreorderresize

> Also, do you have an estimate for when it will be fixed?

This is a low priority feature request for us as we have a working solution already. If it's something you really need we're always happy to take pull requests and I can help you land the feature.

**Comment by WillHavelin** [comment]
> We have an example demonstrating how to resize columns via the keyboard that I've confirmed works for iOS as well.
> 
> https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/keyboardcolumnreorderresize
> 
> > Also, do you have an estimate for when it will be fixed?
> 
> This is a low priority feature request for us as we have a working solution already. If it's something you really need we're always happy to take pull requests and I can help you land the feature.

Thanks for sharing that example. I'll try using that. It might be good to mention that example in the accessibility section on the main doc page for DetailsList. Otherwise, people using the control (like me) won't realize that the should be doing that extra implmentation to make resizing columns work on mobile

**Comment by spmonahan** [comment]
> It might be good to mention that example in the accessibility section on the main doc page for DetailsList.

@WillHavelin Can you make an issue for this please?
