### ISSUE TITLE
[Bug]: Icons no longer load from MS CDNs

### ISSUE THREAD

**Issue by dvTB** [microsoft/fluentui#32861]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
All fluentui versions that use a CDN.
```

### Are you reporting an Accessibility issue?

no

### Reproduction

Try loading https://static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons-3.54.woff into your web-application.

## Actual Behavior
It seems that the MS CDNs were reconfigured. Embedding resources into the site (like fluent UI Icons) does currently not work (not even with localhost). 

Access to font at 'https://static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons-3.54.woff' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
GET https://static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons-3.54.woff net::ERR_FAILED 301 (Moved Permanently)

I know this isn't really a bug of the software, but you might be in the position to get this problem fixed ;)

## Expected Behavior
At least the default CDN should work.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by renatodias13** [comment]
I have the exact same issue in PRD 

![image](https://github.com/user-attachments/assets/f6aa7553-3ccb-4b97-9dda-e2f3712dc808)

**Comment by mrphannguyen** [comment]
Im face this issue, pls check the CDN asap, it's effecting our production now

**Comment by AndreAndradeLR** [comment]
Any update on this? all of our SP Subscription Editon farms are affected as well. CDN seems to work when we call the files directly from the browser, but not when the call is made by the applications (CORS)

**Comment by dvTB** [comment]
Seems like MS moved the CDNs to another location but didn't add CORS * entry for the redirect. More or less all MS projects are affected (e.g. even the old Office-UI)

**Comment by mrphannguyen** [comment]
You guys can override the CDN url path, it works

$ms-icon-cdn-path: 'https://res.cdn.office.net/files/fabric-cdn-prod_20230815.002/assets/icons';
$ms-font-cdn-path: 'https://res.cdn.office.net/files/fabric-cdn-prod_20230815.002/assets/fonts';

@import '../../node_modules/@fluentui/react/dist/sass/Fabric';

**Comment by sysofwan** [comment]
Our product is impacted too. Causing livesite incident.

**Comment by mainframev** [comment]
hi @dvTB 

instead of static.sharepoint, try to use this one: https://res.cdn.office.net/files/fabric-cdn-prod_20240805.001/assets/icons/fabricmdl2icons-3.54.woff 

@mrphannguyen gave a good suggestion, but the version is older. This one above should be the latest

**Comment by mrphannguyen** [comment]
@mainframev Yeah, depending on the version of fluentui in your project then you update the path for consistent

**Comment by dvTB** [comment]
@mainframev currently the projects use the default path. For some CDNs microsoft seem to have fixed the issue (e.g. the older Office UI had also these issues, but  there it now works again).
Currently I try to use my own cdn (which make future upgrades of fluent a bit more complicated) but it is a bit more problemetic with initializeFileTypeIcons, as those assets are not packaged anywhere. 
Would be great for future releases if all used assets were inside of the npm packages.

**Comment by tudorpopams** [comment]
Hello folks, until the CDN issue gets sorted out (we're discussing now with the owners, this might have been a security compliance requirement), please try to host the assets on your own, by checking this guidance: https://github.com/microsoft/fluentui/blob/master/docs/react-wiki-archive/BestPractices/Using-icons.md#alternative-cdn-options

I'm fully aware that this might not be ideal in many cases, but it can fix the current issues and offer long term control over the endpoints.

**Comment by tudorpopams** [comment]
here's an answer we got from the CDN owners: 

> SharePoint CDN team wants to deprecate few old endpoints (including static2) as we already migrated to 1CDN more than 1.5 years ago. The changes were deployed earlier this week to make the redirect to the new endpoint.
> 
>  
> Few solutions.
> 
> 1. Application fixes the CSP right now so the redirect can be chased. [short term]
> 2. Revert the CDN redirect change temperately until the application fixes the CSP. [short term]
> 3. Application packages the resources that it needs with the JavaScript. [medim-term]
>  
> The preferred solution is 1.

**Comment by micahgodbolt** [comment]
The CDN change has been reverted.

**Comment by tudorpopams** [comment]
Although the CDN changes have been reverted, it is very important for everyone to update their projects and host these assets themselves as the previous changes will be applied again in the near future.

**Comment by renatodias13** [comment]
We are not sure how to change the Fonts & Icons when using the vs **5.135.6**.
We are using SharePoint SE (so we are forced to use VS 5) and trying to change the fonts and icons we came across this post: 
https://github.com/SharePoint/sp-dev-docs/issues/9307

We also found this solution but only seems to work on VS 7 or above:
https://codesandbox.io/p/sandbox/customizing-fabric-icons-and-fonts-bveg8?file=%2Fpackage.json%3A15%2C34

Is there a way to do overwrite the default url on VS 5 (for fonts and icons)?

@tudorpopams your post is what concerns me the most because we can't really figure out how to proceed with the issues we detailed above and we really dont know when this security change will be applied again.

**Comment by biswanathhalder85** [comment]
![Image](https://github.com/user-attachments/assets/a6569dff-860b-4b3d-a96b-83d48494fdd5)

Same issue is happening from today . Could you pls advice ?

**Comment by influential-eliot** [comment]
Yep, I am also seeing this, @biswanathhalder85 ... except in Azure. It appears to be due to Cross-Origin Request blocking by the browser:

![Image](https://github.com/user-attachments/assets/8cb323ed-581a-46ab-8df9-4ee81bcdd27b)

We may need to open a new incident as a repeat of this ... not sure.

**Comment by Pedja-Cucak** [comment]
Hello, any update on this?

@biswanathhalder85, @influential-eliot did you guys found some solutions?

**Comment by influential-eliot** [comment]
I have not, @Pedja-Cucak :(

**Comment by Pedja-Cucak** [comment]
@influential-eliot I solved it in this way

I've installed @fluentui/react-icons-mdl2 package, and used svg icons from there.

Like this:

```
import { initializeIcons } from '@fluentui/react'
import { AddIcon } from '@fluentui/react-icons-mdl2';

// Do not forget to call
initializeIcons()

import { AddIcon } from '@fluentui/react-icons-mdl2';

<AddIcon />;
```

or you can register them and use it at multiple places by new names (AddCustom, DeleteCustom,...)

```
import { initializeIcons } from '@fluentui/react'
import { AddIcon, DeleteIcon } from '@fluentui/react-icons-mdl2';

// Do not forget to call
initializeIcons()

// this you can put inside of your index(.jsx, .tsx) file
registerIcons({
  icons: {
    AddCustom: <AddIcon />,
    DeleteCustom: <DeleteIcon />,
    // ... register more icons
  },
});

// And then use it
<CommandBarButton 
    iconProps={{ iconName: 'AddCustom' }}
    // ... other props
/>
```

I hope this will be helpful to others also 😄

**Comment by influential-eliot** [comment]
@Pedja-Cucak ... dangit ... I'm not entirely sure what all of that is ... I'm just using Firefox on Debian 12 (Wayland/Gnome).

---

@renatodias13 ... also dangit ... not sure what I can do with SCSS, because I can only put CSS in my UserContent.css in my Firefox profile setup ... (_i've not learned much about SCSS ... I'd love to, but not had the time or need to do so_)

**Comment by renatodias13** [comment]
@influential-eliot should be the same thing

Is more or less the same with a scss or a css file, here and exemple with css and html

Example for css file 

@font-face {
  font-family: 'FabricMDL2Icons';
  **src: url('../fonts/fabric-icons-824dd578.woff') format('woff');**
}

.ms-Icon {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  display: inline-block;
  font-family: 'FabricMDL2Icons';
  font-style: normal;
  font-weight: normal;
  speak: none;
}

.ms-Icon--Edit:before { content: "\E70F"; }

<i class="ms-Icon ms-Icon--Group"}></i>

if you go here and download the subset it will be clear the example I just posted

https://uifabricicons.azurewebsites.net/

**Comment by influential-eliot** [comment]
Still a bit alien to me ... but I'll try just plopping that in `UserContent.css` and see if that fixes it, cheers, @renatodias13 !!
Then I'll publish it on GreasyFork if it works, lol 😅 !
