### ISSUE TITLE
[Bug]: Esc key doesn't work for command bar button if it is a contextual menu button and in overflow menu

### ISSUE THREAD

**Issue by alton-browsing** [microsoft/fluentui#32871]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 33.57 GB / 63.95 GB
  Browsers:
    Edge: Chromium (127.0.2651.105)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

yes

### Reproduction

https://codepen.io/alton25/pen/XWLvByo

### Bug Description

To reproduce the issue, click on the overflow button (the three dots) then click on the columns button that shows up in the overflow menu and then try to click esc from that context menu that shows up.

## Actual Behavior
Esc key doesn't dismiss the contextual menu pop up

![image](https://github.com/user-attachments/assets/1ef6f33c-3c45-440e-9c82-44e3e4bb3bb8)

## Expected Behavior
Esc key should dismiss the contextual menu pop up

### Requested priority

Normal

### Products/sites affected

intune.microsoft.com

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment]
@alton-browsing :wave: 

Not sure if it's a bug, but if you will remove `onDismiss` it will work as expected. Maybe you need  to use `onMenuDismiss` instead.

**Comment by alton-browsing** [comment]
It does look like that solves as a workaround, thanks! Ill keep the discussion open in case it actually isn't intended and onDismiss should also esc.
________________________________

**Comment by spmonahan** [comment]
@alton-browsing I'm not able to repro in Edge. Are you still able to repro the issue?

**Comment by alton-browsing** [comment]
Yea, it still repros. Sorry I had the workaround code in there but I have since swapped it back to onDismiss (instead of onMenuDismiss)

**Comment by sopranopillow** [comment]
seems like it only reproes when onDismiss is provided. Since the workaround does work and we are avoiding making changes to v8 unless necessary, we'll close it as won't fix.

FYI for future reference, using onMenuDismiss instead of onDismiss will get the same result.
