### ISSUE TITLE
[Bug]: Accessibility issue in tag picker

### ISSUE THREAD

**Issue by ChithiraMG** [microsoft/fluentui#32932]
### Component

TagPicker

### Package version

v8

### React version

"^18.2.0"

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 3.25 GB / 15.78 GB
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.3527
```

### Current Behavior

![image](https://github.com/user-attachments/assets/6fa0b14d-e615-47c9-8384-fac0a1a5415f)

### Expected Behavior

Fluent ui tag picker component is showing accessibility issues
https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker
![image](https://github.com/user-attachments/assets/73431c9f-7672-4ebe-8d0d-cddf0d075f8f)
![image](https://github.com/user-attachments/assets/6fa84457-af9f-449c-bb49-c1ef9115f6e2)

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker

### Steps to reproduce

Go to this link 
https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker
Run fast pass accessibility check using accessibility insights for web chrome extension

### Are you reporting an Accessibility issue?

None

### Suggested severity

Urgent - No workaround and Products/sites are affected

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
This looks like it's complaining about having a `role="status"` live region inside the `role="listbox"` suggestions container. Since this is a v8 control and that specific semantic structure will not cause any practical accessibility issues, I'm marking this "won't fix".

If you have a related accessibility issue filed on your own code, I'd suggest also closing it as having no practical impact.
