### ISSUE TITLE
[Bug]: colorNeutralForeground1Static still changes with theme in SharePoint

### ISSUE THREAD

**Issue by sunyd0112** [microsoft/fluentui#32943]
### Component

FluentProvider

### Package version

^9.54.13

### React version

17.0.1

### Environment

```shell
System:
    OS: Linux 6.8 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 57.43 GB / 62.79 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Browsers:
    Chrome: 127.0.6533.99
```

### Current Behavior

I am using Fluent tokens to defined text colors. And my scenario is I will have some text on an image with an overlay.
So I would like the text color to always be light text when overlay is black, and text color to always be dark text when overlay is white, no matter whether the current theme is light or dark.

I checked the colors documentation on this site: https://react.fluentui.dev/?path=/docs/theme-colors--docs
It seems like colorNeutralForeground1Static and colorNeutralForeground1StaticInverted are just what I want.
![image](https://github.com/user-attachments/assets/86eca49b-1182-4e5d-9c37-9dde2792f4cd)

However, when I applied the token in SharePoint, they also changed based on theme.
![image](https://github.com/user-attachments/assets/edfead6a-073b-4e4e-bbae-211cd5c4206e)

### Expected Behavior

The value of these two tokens should not change when theme changed, otherwise, the 'static' means nothing.

### Reproduction

This cased happens in SharePoint. Cannot get a repro out of SharePoint.

### Steps to reproduce

1. In SharePoint, set some color as tokens.colorNeutralForeground1Static.
2. Then change the theme from light to dark.
3. Observe the color changes.

### Are you reporting an Accessibility issue?

None

### Suggested severity

Medium - Has workaround

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by dmytrokirpa** [comment]
Hello @sunyd0112, to effectively address the issue, it's essential to have a proper reproduction setup. Could you ensure that your component is enclosed within the `FluentProvider` and is using the correct theme? It seems that a different theme, possibly from SharePoint, is being applied to your component.
