### ISSUE TITLE
[Feature]: Circular Tab variant

### ISSUE THREAD

**Issue by dmytrokirpa** [microsoft/fluentui#32951]
### Area

React Components (@fluentui/react-components)

### Describe the feature that you would like added

Add a new `circluar` Tab variant to support existing partner uscases.

Figma - https://www.figma.com/design/dK5AnDvvnSTWV9lduQWeDk/TabList?node-id=11485-46208&t=mGEm2A0P5LNHTYUs-1

![image](https://github.com/user-attachments/assets/e0062a98-f1de-4e99-bc15-1ddfcfa5d8b4)

### Have you discussed this feature with our team

@tudorpopams

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

High

**Comment by Hotell** [comment]
when I first saw it I was quite confused tbh... circular (like infinite 🥵 ?)  ... 

I'd suggest to get some feedback to desing team and adjust:
- is this part of official design language for all fluent (including web-components @chrisdholt ) ?
- can we change the variant to something that is better expressing what it does ( without that confusing CS "circular" wording ) https://v2.chakra-ui.com/docs/components/tabs/usage#tab-variants-and-color

**Comment by yvonne-chien-ms** [comment]
Hi @Hotell, "circular" aligns better with what we use in the Button component. "Round" refers to a smaller border radius https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/components-button-button--default#stories
