### ISSUE TITLE
[Bug]: Portability issue — box-sizing depends on browser defaults

### ISSUE THREAD

**Issue by ReillyBova** [microsoft/fluentui#32952]
### Component

Other...

### Package version

9.54.17

### React version

17.0.2

### Environment

```shell
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1
    Memory: 69.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 129.0.6668.70
    Edge: 129.0.2792.65
    Safari: 18.0
  npmPackages:
    @fluentui/accessibility: 0.66.5 => 0.66.5 
    @fluentui/react-brand-icons: 1.0.125 => 1.0.125 
    @fluentui/react-components: 9.54.17 => 9.54.17 
    @fluentui/react-icons: 2.0.259 => 2.0.258 
    @fluentui/react-migration-v0-v9: 9.0.54 => 9.0.54 
    @fluentui/react-northstar: 0.63.1 => 0.63.1 
    @fluentui/react-portal-compat: 9.0.118 => 9.0.118 
    @types/react: 17.0.2 => 17.0.2 
    @types/react-dom: 17.0.2 => 17.0.2 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2
```

### Current Behavior

To reduce inconsistencies in default CSS behaviors between browsers and devices, our project uses `normalize.css`, which is a fairly common industry practice (with 1mil weekly downloads on npm). `normalize.css` has spawned a few clones and modernizations over the years, but one bit of CSS sanitization is fairly consistent across all projects:

```
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}
```

Unfortunately, there are a few components in Fluent v9 that depend on `box-sizing: content-box` to display correctly. While modern browsers default to `box-sizing: content-box`, this default behavior is frequently overridden by major projects, and is one of the infamous [self-identified CSS design mistakes](https://wiki.csswg.org/ideas/mistakes).

To ensure interoperability with projects using CSS normalization/reset practices, Fluent v9 should explicitly set `box-sizing: content-box` wherever it is currently letting a width/height measurement fall back to the default browser box-sizing model for a given HTML element.

Here is an example of how <InteractionTag /> displays an icon on a project using the above box-sizing reset CSS (part of normalize.css, and many other CSS reset libraries):

```
export const Icon = () => (
  <InteractionTag>
    <InteractionTagPrimary icon={<CalendarMonthRegular />}>
      Primary text
    </InteractionTagPrimary>
  </InteractionTag>
);
```

<img width="136" alt="Screenshot 2024-10-01 at 2 50 16 AM" src="https://github.com/user-attachments/assets/04cb1a2e-5e86-420c-9485-e2df16130655">

The icon is super tiny here because the padding on the icon span is considered part of its width in the border-box box sizing model.

### Expected Behavior

InteractionTag should render as it does on the doc-site, right out of the box:

https://react.fluentui.dev/?path=/docs/components-tag-interactiontag--docs

### Reproduction

https://stackblitz.com/edit/2sezsm?file=index.html

### Steps to reproduce

1. Apply the following ubiquitous CSS reset style:

```
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}
```
2. Certain v9 width measurements break, like the Icon size in InteractionTag

### Are you reporting an Accessibility issue?

None

### Suggested severity

Medium - Has workaround

### Products/sites affected

Viva Insights

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
Thanks for filing this! This would probably require a bigger audit of the v9 components to see where else this issue surfaces. For now I'll tag this as referencing just the `Tag` component per the repro example
