### ISSUE TITLE
[Bug]: TagPicker deletes user pill on clicking anywhere (even though X button is present)

### ISSUE THREAD

**Issue by junaid51** [microsoft/fluentui#32994]
### Component

TagPicker

### Package version

9.54.2

### React version

18.2

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 12th Gen Intel(R) Core(TM) i9-12950HX
    Memory: 14.07 GB / 15.62 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  npmPackages:
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1
```

### Current Behavior

After selecting a user from dropdown -> Clicking anywhere on the selected user deletes it from the list of selected users

### Expected Behavior

User should only be removed when the 'X' button is clicked on the pill.

### Reproduction

https://stackblitz.com/run?file=src%2Fexample.tsx

### Steps to reproduce

1. Click on TagPicker input and add a few options from dropdown
2. In the list of selected options, click on anywhere except the close button
3. Notice the option is removed by clicking anywhere

### Are you reporting an Accessibility issue?

no

### Suggested severity

Urgent - No workaround and Products/sites are affected

### Products/sites affected

Viva Goals

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
I believe this is the intentional behaviour, can you confirm it @YuanboXue-Amber ?

**Comment by YuanboXue-Amber** [comment]
Tag pill supports only one action so it is expected behavior that click on anywhere dismisses it

**Comment by junaid51** [comment]
![Image](https://github.com/user-attachments/assets/71bb7c0e-3678-4ff9-be27-c184a50d3d90)

So Tag's have a dismissable button on them. Can we move the remove pill action when clicking on the dismiss button instead of the entire tag?

**Comment by bsunderhus** [comment]
What you want @junaid51 is an [InteractionTag](https://react.fluentui.dev/?path=/docs/components-tag-interactiontag--docs), and unfortunately we do not support usage of `InteractionTag` with `TagPicker` as that results on multiple accessibility problems with the current way the `TagPicker` is structured.
