### ISSUE TITLE
[Bug]: Wrapping Radio labels with <InfoLabel> causing items unselectable in <RadioGroup>

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#33027]
### Component

InfoLabel

### Package version

9.55.0

### React version

18.3.1

### Environment

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  npmPackages:
    @fluentui/react-components: ^9.0.0 => 9.55.0 
    @types/react: ^17 => 17.0.83 
    @types/react-dom: ^17 => 17.0.25 
    react: ^18 => 18.3.1 
    react-dom: ^18 => 18.3.1 

### Current Behavior

I cannot click to select the Radio option wrapped in `<InfoLabel>` _most of the time_.

![Image](https://github.com/user-attachments/assets/72d2f558-79ec-4938-ad37-f75a3eca62ce)

### Expected Behavior

I should be able to click and select the Radio option.

### Reproduction

https://stackblitz.com/edit/7ywkfs?file=src%2Fexample.tsx,src%2Findex.tsx,package.json

### Steps to reproduce

Open the reproduction link and do as the reproduction screen recording does.

### Are you reporting an Accessibility issue?

no

### Suggested severity

High - No workaround

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by pradeept95** [comment]
Hello @chenxinyanc , it appears there is an issue.

As a temporary fix, you can manually assign id and htmlFor attributes to Option and InfoLabel like this:

```jsx
import type { RadioGroupProps } from '@fluentui/react-components';
import {
  Field,
  InfoLabel,
  Radio,
  RadioGroup,
} from '@fluentui/react-components';

export const Default = (props: Partial<RadioGroupProps>) => (
  <Field label="Favorite Fruit">
    <RadioGroup {...props}>
      <Radio value="apple" label="Apple" />
      <Radio
        value="pear"
        id="pear"
        label={
          <InfoLabel info="Pear" htmlFor="pear">
            Pear
          </InfoLabel>
        }
      />
      <Radio
        value="banana"
        id="banana"
        label={
          <InfoLabel info="Banana" htmlFor="banana">
            Banana
          </InfoLabel>
        }
      />
      <Radio value="orange" label={<>this is orange</>} />
    </RadioGroup>
  </Field>
);
```

**Comment by mainframev** [comment]
@chenxinyanc hi 👋🏻 

In our docs, there is an example called `Field`, you can take a look on this to see how label slot is used with `InfoLabel`. Here is the more correct example  with render function, comparing to posted above. It works as expected. 

```tsx
import * as React from 'react';

import type { RadioGroupProps } from '@fluentui/react-components';
import {
  Field,
  InfoLabel,
  Radio,
  RadioGroup,
  LabelProps,
} from '@fluentui/react-components';

export const Default = (props: Partial<RadioGroupProps>) => (
  <Field label="Favorite Fruit">
    <RadioGroup {...props}>
      <Radio value="apple" label="Apple" />
      <Radio value="pear" label={<InfoLabel info="Pear">Pear</InfoLabel>} />
      <Radio
        value="banana"
        label={{
          children: (_: unknown, props: LabelProps) => (
            <InfoLabel info="Banana" {...props}>
              Banana
            </InfoLabel>
          ),
        }}
      />
      <Radio value="orange" label="Orange" />
    </RadioGroup>
  </Field>
);
```

**Comment by chenxinyanc** [comment]
> I do not think that having infoLabel for each Radio is providing a good UX, imo better to have a single infoLabel added to a Field and normal labels to radios.

@mainframev Thanks for the insight. However, while easy to implement, it seems not very trivial for me to wrap the Radio button in a flexbox `<div>`, along with an info icon. I'll even have to create a React component by myself for this purpose.

If such request become common in the future, probably you might need to consider it.
