### ISSUE TITLE
[Bug]: MessageBar Background Color Does Not Change in Dark Mode

### ISSUE THREAD

**Issue by bentsai10** [microsoft/fluentui#33030]
### Component

MessageBar

### Package version

^9.54.13

### React version

>=16.13.1 <18.0.0

### Environment

 System:
    OS: Linux 6.5 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (32) x64 AMD EPYC 7763 64-Core Processor
    Memory: 120.19 GB / 125.78 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Browsers:
    Chrome: 128.0.6613.137

### Current Behavior

Message bar background color does not change in dark mode, makes text within it ![Image](https://github.com/user-attachments/assets/e203e64d-5edf-43cf-a0db-7bc368d7143c)
![Image](https://github.com/user-attachments/assets/30f36fa8-b650-410c-a0ea-da2906ccfc11)
unreadable

### Expected Behavior

Message bar background color should change in dark mode to make text within it readable

### Reproduction

n/a

### Steps to reproduce

- Navigate here: [testdark - Home (sharepoint-df.com)](https://microsoft.sharepoint-df.com/sites/testdark?xsdata=MDV8MDJ8fGM5NjI0OGYwMmNmNzRhNzcyYTkwMDhkY2U5NzkwZjE5fDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDB8MHw2Mzg2NDE5NTMzMzMzODk5Njh8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPamMyT0RjNFltTmtMV1JoWmpVdE5HSTBOQzFpWVdRNUxURTJPV1l4T1RBME1qYzBZbDg1TXpaalpXRXhZaTFqWTJZM0xUUmtZamd0WWpnNE9TMW1ZbUV6TUdaaFpHUTJOamhBZFc1eExtZGliQzV6Y0dGalpYTXZiV1Z6YzJGblpYTXZNVGN5T0RVNU9EVXpNalF4TXc9PXxmNzMxZjYwOWJlYzI0YTIyMmE5MDA4ZGNlOTc5MGYxOXw2M2FlODM5NmQxMGU0MDA1ODNiNzA0MTJiYjAzZWQ4Yw%3D%3D&sdata=dFY0Y2xSOUZtOHRVZGk3QWErTjRyU0JNa2taeGd0RjlEQ21VNWk4NlF6ND0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cbentsai%40microsoft.com)
- Click '+ New' in the command bar of the page, and click 'Copilot agent' in the dropdown
- Modal opens, click 'Edit'
- Click 'Sources' at the top of the modal
- In search bar in the modal, type 'spex'. When results populate, select spexdogfood
- Under spexdogfood, change dropdown to 'sourced from document libraries...'
- Click 'add document libraries...'
- File picker opens, select all the available files (press checkmark at top left of table), click select
- See the warning bar

### Are you reporting an Accessibility issue?

yes

### Suggested severity

Medium - Has workaround

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
In dark theme, the value for `colorStatusDangerbackground1` should be `3b0509` as you are showing in the screenshot. The problem seems to be product specific. Please reopen with isolated repro.
