### ISSUE TITLE
[Docs]: react-builder

### ISSUE THREAD

**Issue by uma-uc** [microsoft/fluentui#33044]
### Area

React Components (https://react.fluentui.dev)

### What kind of documentation issue are you reporting?

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

As per document, to run react-builder, the following steps needs to be followed
1. Clone the repository.
2. From the root folder (fluentui), run yarn to install required dependencies. This may take a while.
3. To build the project, run yarn start:northstar. Upon success, the builder can be found at localhost:8080. Happy building!

_**However, step 3, viz, yarn start:northstar is not found anywhere in the repo**_

Please provide instructions to run react-builder.

### Description

3. To build the project, run yarn start:northstar. Upon success, the builder can be found at localhost:8080. Happy building!

_**However, step 3, viz, yarn start:northstar is not found anywhere in the repo**_

Please provide instructions to run react-builder.

### Validations

- [x] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

**Comment by ling1726** [comment]
react-northstar is deprecated and will be EOL soon, we do not expect more maintenance to the builder at this time
