### ISSUE TITLE
[Docs]: react-charting

### ISSUE THREAD

**Issue by uma-uc** [microsoft/fluentui#33045]
### Area

React Components (https://react.fluentui.dev)

### What kind of documentation issue are you reporting?

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Please provide documents for fluent-ui's react-charting.

### Description

Please provide documents for fluent-ui's react-charting.

### Validations

- [x] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

**Comment by AtishayMsft** [comment]
You can find the charting documentation here. https://microsoft.github.io/fluentui-charting-contrib/
