### ISSUE TITLE
[Bug]: Popover with matchTargetSize: 'width' does not match width of Target

### ISSUE THREAD

**Issue by Robstei** [microsoft/fluentui#33056]
### Component

Popover

### Package version

9.54.13

### React version

18.3.1

### Environment

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  npmPackages:
    @fluentui/react-components: ^9.0.0 => 9.54.13 
    @types/react: ^17 => 17.0.80 
    @types/react-dom: ^17 => 17.0.25 
    react: ^18 => 18.3.1 
    react-dom: ^18 => 18.3.1 

### Current Behavior

Hello,

[here is a reproduction](https://stackblitz.com/edit/q5uszp?file=src%2FApp.tsx,package-lock.json).

It look like using matchTargetSize: 'width' does take the padding into account.

Therefore the Popover is 2x16px = 32px wider than the PopoverTrigger.

### Expected Behavior

I would expect for the Popover to have the same width as the PopoverTrigger when using matchTargetSize: 'width'.

### Reproduction

https://stackblitz.com/edit/q5uszp?file=src%2FApp.tsx

### Steps to reproduce

1. Click the Button
2. Compare the width of the Button with the width of the Popover

### Are you reporting an Accessibility issue?

None

### Suggested severity

Medium - Has workaround

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment]
@Robstei 👋🏻  

`react-positioning` which is responsible for `matchTargetSize` [API used to provide `box-sizing: border-box`](https://github.com/microsoft/fluentui/pull/29690/files#diff-195c0ced1e1f117c55c25e3626d5700a48c3e57df4e55614373e1a599fd93c12R19) property explicitly to a floating element. 

However, it was later changed [here](https://github.com/microsoft/fluentui/pull/30028/files#diff-195c0ced1e1f117c55c25e3626d5700a48c3e57df4e55614373e1a599fd93c12R20-R22). 

Not sure here on 100% why for Popover it was not added. Maybe @ling1726 remembers 🙂 

Meanwhile you can easily fix it on your side by providing box-sizing to PopoverSurface: 

```tsx
import {
  Button,
  FluentProvider,
  Popover,
  PopoverSurface,
  PopoverTrigger,
  webLightTheme,
  makeStyles,
} from '@fluentui/react-components';

const useStyles = makeStyles({
  borderBox: {
    boxSizing: 'border-box',
  },
});

const App = () => {
  const styles = useStyles();

  return (
    <FluentProvider theme={webLightTheme}>
      <div>
        <Popover
          positioning={{
            matchTargetSize: 'width',
            align: 'start',
            position: 'below',
          }}
        >
          <PopoverTrigger disableButtonEnhancement>
            <Button>My Trigger Button</Button>
          </PopoverTrigger>

          <PopoverSurface className={styles.borderBox}>kek</PopoverSurface>
        </Popover>
      </div>
    </FluentProvider>
  );
};

export default App;

```

**Comment by Robstei** [comment]
Thanks for the nice and detailed response @mainframev 

Since this is marked as "as requiring author feedback" do you need anything from me?

I wasn't able to use your fix but it look straight forward 👍
