### ISSUE TITLE
[Bug]: Primary split button does not keep the primary color background when open

### ISSUE THREAD

**Issue by avenezia** [microsoft/fluentui#33061]
### Package

react

### Package version

8.120.9

### React version

16.14.0

### Environment

Currently having issues running npx

### Current Behavior

When opening the menu for a primary split button, the section which contains the chevron icon does not keep the primary background (e.g. green) and instead gets the Fluent UI default one being blue.

![Image](https://github.com/user-attachments/assets/22af7381-6b8f-46b2-88a8-29bc38d9754d)

### Expected Behavior

The color should not change when opening the button menu.

### Reproduction

https://codepen.io/avenezia/pen/jOgmYJa

### Steps to reproduce

1. Go to https://codepen.io/avenezia/pen/jOgmYJa and click on the primary split button
2. The section with the chevron icon gets the blue background instead of keeping the green one

### Are you reporting an Accessibility issue?

None

### Suggested severity

Urgent - No workaround and Products/sites are affected

### Products/sites affected

Power Query

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chr-sad** [comment]
I can confirm this issue - we experience the same in our solution with @fluentui/react v8.121.5.

**Comment by avenezia** [comment]
Can you please share an ETA on when this is going to be fixed?

**Comment by khmakoto** [comment]
Hey @chr-sad and @avenezia, I just created a PR with a fix for this issue, thanks for reporting it!
