### ISSUE TITLE
[Bug]: Closing InfoLabel by ESC in a Modal or Projection will close the entire window of the Projection or Modal

### ISSUE THREAD

**Issue by racer97** [microsoft/fluentui#33062]
### Component

InfoLabel

### Package version

9.51.1

### React version

18.2.0

### Environment

System:
    OS: Windows 11 10.0.26100
    CPU: (24) x64 AMD Ryzen Threadripper PRO 3945WX 12-Cores
    Memory: 46.36 GB / 63.86 GB
  Browsers:
    Edge: Chromium (129.0.2792.52)
    Internet Explorer: 11.0.26100.1882

### Current Behavior

The issue is when closing the popover of the InfoLabel by pressing ESC button, instead of just closing the popover itselt, the entire settings dialog will be closed as well. This happens to all the InfoLabel usages in Outlook Monarch Settings including General -> Notifications and General -> Files and links and both in OWA and Monarch.

My assumption is the command of pressing ESC will propagate to the Projection or Modal causing them getting closed. Is there a way to stop the propagation through FluentUI apis? Thank you.

### Expected Behavior

When the popover of InfoLabel is open in a Modal or Projection window, pressing ESC will only close the popover rather than the window.

### Reproduction

https://stackblitz.com/edit/tvapcd?file=src%2Fexample.tsx

### Steps to reproduce

1. Open Outlook Monarch or OWA
2. Click on the Gear button on the top menu
3. Go to General -> Notifications
4. Expand Mail tab under Notify me about
5. In Reaction section, click on the circle i button next to the text "Show in notifications pane". A popover will open
6. Press ESC. The whole settings window is closed.

### Are you reporting an Accessibility issue?

yes

### Suggested severity

High - No workaround

### Products/sites affected

Outlook Settings

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment]
hi @racer97  👋🏻 

By default it's not stopping propagation, so when you are hitting ESC, the event is bubbling. You can control this behavior in `infoLabel` via slots. `infoLabel` has `infoButton` slot, which has popover slot. 

The reason why it's not a default is that stopping event propagation is might be problematic on DS level. It's more simple to prevent the event bubbling on the user side, than on our side, where we basically denying event for the user. 

Here is the quick example of how you can prevent the event bubbling: 

```tsx
import * as React from 'react';
import {
  useModalAttributes,
  useFocusFinders,
  makeStyles,
  Button,
  tokens,
  InfoLabel,
  Link,
} from '@fluentui/react-components';

const useStyles = makeStyles({
  dialog: {
    position: 'fixed',
    backgroundColor: tokens.colorNeutralBackground1,
    inset: '0',
    padding: '10px',
    margin: 'auto',
    border: 'none',
    overflow: 'unset',
    boxShadow: tokens.shadow16,
    width: '450px',
    height: '200px',
    display: 'flex',
    flexDirection: 'column',
  },

  footer: {
    display: 'flex',
    marginTop: 'auto',
    justifyContent: 'end',
    gap: '5px',
  },
});

export const Default = () => {
  const styles = useStyles();
  const [open, setOpen] = React.useState(false);
  const { triggerAttributes, modalAttributes } = useModalAttributes({
    legacyTrapFocus: true,
    trapFocus: true,
  });
  const { findFirstFocusable } = useFocusFinders();
  const triggerRef = React.useRef<HTMLButtonElement>(null);
  const dialogRef = React.useRef<HTMLDivElement>(null);
  const onClickTrigger = () => {
    setOpen(true);
  };

  const onDialogKeydown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (e.key === 'Escape') {
      setOpen(false);
      triggerRef.current?.focus();
    }
  };

  React.useEffect(() => {
    if (open && dialogRef.current) {
      findFirstFocusable(dialogRef.current)?.focus();
    }
  }, [open, findFirstFocusable]);

  return (
    <>
      <Button ref={triggerRef} {...triggerAttributes} onClick={onClickTrigger}>
        Open dialog
      </Button>
      {open && (
        <div
          onKeyDown={onDialogKeydown}
          ref={dialogRef}
          {...modalAttributes}
          aria-modal="true"
          role="dialog"
          className={styles.dialog}
          aria-label="Example dialog"
        >
          <InfoLabel
            infoButton={{
              popover: {
                onOpenChange: (ev) => ev.stopPropagation(),
              },
            }}
            info={
              <>
                This is example information for an InfoLabel.{' '}
                <Link href="https://react.fluentui.dev">Learn more</Link>
              </>
            }
          >
            Example label
          </InfoLabel>{' '}
        </div>
      )}
    </>
  );
};
```

There are reasons behinds this, so I found some older issues with related context:

**Comment by mainframev** [comment]
@racer97 some context: 

- https://github.com/microsoft/fluentui/issues/30590
- https://github.com/microsoft/fluentui/issues/30384
- https://github.com/microsoft/fluentui/pull/27832

**Comment by racer97** [comment]
Thank you for the example and context. They're very helpful! I'm able to stop propagation. I'll close this bug.
