### ISSUE TITLE
[Bug]: Skeleton not showing animation

### ISSUE THREAD

**Issue by nicoleweese** [microsoft/fluentui#33076]
### Component

Skeleton

### Package version

9.54.13

### React version

18.3.1

### Environment

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 42.93 GB / 63.95 GB
  Browsers:
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.22621.3527

### Current Behavior

`    return (
        <div className={classNames.essentialsItem}>
            <div className={mergeClasses(classNames.essentialsNoWrap, classNames.essentialsLabel)}>{label}</div>
            <div className={mergeClasses(classNames.essentialsNoWrap, classNames.essentialsDivider)}>:</div>
            <div
                aria-busy={!value}
                aria-label={`${labelAria} ${valueAria}`}
                className={mergeClasses(classNames.essentialsNoWrap, classNames.essentialsValueContainer)}
            >
                {!value ? (
                    // TODO: is not "shimmering"
                    <Skeleton animation="wave">
                        <SkeletonItem animation="wave" />
                    </Skeleton>
                ) : (
                    FieldValueContent
                )}
            </div>
        </div>
    );
`

When loading the SkeletonItem, I don't see any wave or pulse regardless of whether I specify animation or not. Even when rendering the Skeleton without allowing it to update to actual content, the animations never show up.

### Expected Behavior

I am expecting the wave animation to show by default, and the pulse animation to show when specified.

### Reproduction

https://stackblitz.com/edit/cieedh?file=src%2Fexample.tsx

### Steps to reproduce

I don't see it reproducing in stackblitz.

### Are you reporting an Accessibility issue?

no

### Suggested severity

High - No workaround

### Are you willing to submit a PR to fix?

yes

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by WanderG** [comment]
Did you check if animations are enabled in your windows settings? (Accessibility => Visual effects => Animation effects)

**Comment by nicoleweese** [comment]
That fixed it. Thank you :)
