### ISSUE TITLE
[Bug]: Setting `className` of `mountNode` of a drawer makes it invisible

### ISSUE THREAD

**Issue by wfwf1997** [microsoft/fluentui#33088]
### Component

Drawer

### Package version

9.54.15

### React version

17.0.1

### Environment

  System:
    OS: Linux 6.5 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 57.64 GB / 62.78 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Browsers:
    Chrome: 129.0.6668.70
  npmPackages:
    @fluentui/merge-styles: ^8.6.2 => 8.6.2 
    @fluentui/react: ^8.117.5 => 8.117.5 
    @fluentui/react-components: ^9.54.15 => 9.54.15 
    @fluentui/react-datepicker-compat: ^0.4.50 => 0.4.50 
    @fluentui/react-hooks: ^8.7.2 => 8.7.2 
    @fluentui/react-icons: ~2.0.258 => 2.0.261 
    @fluentui/react-portal-compat: ^9.0.163 => 9.0.163 
    @fluentui/react-utilities: ^9.18.14 => 9.18.14 
    @fluentui/utilities: ^8.15.2 => 8.15.2 
    @types/react: 17.0.45 => 17.0.45 
    @types/react-dom: 17.0.17 => 17.0.17 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 

### Current Behavior

The drawer is invisible.

### Expected Behavior

The drawer is visible.

### Reproduction

https://codesandbox.io/p/sandbox/nice-butterfly-5kfl63

### Steps to reproduce

Just open the codesandbox and you can observe the issue.

If you delete the className comment in the App.tsx in the sandbox, it will emluate the old behavior, and the drawer comes to be visible again.

### Are you reporting an Accessibility issue?

None

### Suggested severity

Medium - Has workaround

### Products/sites affected

OneDrive and SharePoint

### Are you willing to submit a PR to fix?

yes

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by wfwf1997** [comment]
I believe this bug is introduced in #32816

**Comment by pradeept95** [comment]
Hi @wfwf1997 

`mountNode` props expect an element. You need to pass a ref to the element. Here is a basic example that illustrates a custom mount node with `className`.

```
import * as React from "react";
import {
  FluentProvider,
  webLightTheme,
  makeStyles,
  Button,
} from "@fluentui/react-components";
import { OverlayDrawer, DrawerBody } from "@fluentui/react-components";

const useStyles = makeStyles({
  positionFixed: {
    position: "fixed",
    width: "500px",
    height: "500px",
  },
});

export default function App() {
  const ref = React.useRef(null);
  const [isOpen, setIsOpen] = React.useState(false);

  const styles = useStyles();

  return (
    <FluentProvider theme={webLightTheme}>
      <div>
        <Button
          appearance="primary"
          onClick={() => setIsOpen((isOpened) => !isOpened)}
        >
          Open Drawer
        </Button>
        <div className={styles.positionFixed} ref={ref}>
          <OverlayDrawer
            mountNode={ref.current}
            open={isOpen}
            onOpenChange={(_, { open }) => setIsOpen(open)}

            // backdrop={{ className: styles.positionFixed }}
            // className={styles.positionFixed}
          >
            <DrawerBody>
              <p>Drawer content</p>
            </DrawerBody>
          </OverlayDrawer>
        </div>
      </div>
    </FluentProvider>
  );
}
```

With these changes, you should have a custom mount node for your OverlayDrawer that allows precise control over its positioning and styling

**Comment by mainframev** [comment]
@wfwf1997 hi 👋🏻 

@pradeept95 gave correct suggestion, the only addition to that, if you are passing the className to the `mountNode` slot, do not forget to provider also `element` property. Or you can pass simply ref as it's suggested above. Closing as it's not an issue.
