### ISSUE TITLE
[Scale] Migrate to new variant structure

### ISSUE THREAD

**Issue by robertpenner** [microsoft/fluentui#33112]
Follow the changes for `Fade` in [33081](https://github.com/microsoft/fluentui/issues/33081).

NOTE: We are not including `Scale` in the motion components beta release. It needs more design and API work.

**Comment by pixel-perfectionist** [comment]
https://github.com/microsoft/fluentui/blob/48aaf290109e36e4c7282855a5bd4b86feedad38/packages/react-components/react-motion-components-preview/library/src/components/Scale/Scale.ts - made update with migration to new variant structure. I would like to review with Robert before move forward.

**Comment by robertpenner** [comment]
> https://github.com/microsoft/fluentui/blob/48aaf290109e36e4c7282855a5bd4b86feedad38/packages/react-components/react-motion-components-preview/library/src/components/Scale/Scale.ts - made update with migration to new variant structure. I would like to review with Robert before move forward.

Thanks Alex, I'll review this and check back in with you.
