### ISSUE TITLE
[RFC]: Fluent Semantic Tokens

### ISSUE THREAD

**Issue by janechu** [microsoft/fluentui#33115]
### Area

Tooling

### Describe the feature that you would like added

# 💬 RFC

The current structure of Fluent UI components currently uses a single design tokens package (`@fluentui/design-tokens`), from which CSS variables using the Fluent 2 design tokens are exported. In development currently are the Fluent Semantic Tokens (referred to as FST) which are meant to be the new tokens solving a number of issues with the Fluent 2 tokens. There are some challenges with the current approach in Fluent UI for enabling this.

### FST (Fluent Semantic Tokens)

FST offer more semantic meaning and a higher fidelity that will allow for cross platform/product theme alignment. This is achieved by having optional tokens that can sometimes target specific controls. We refer to these as optional tokens, but all of FST will be prefixed by "fst".

### Problem Space

- Both FST and fluent 2 tokens must be put in place with a fallback structure to prevent any breaking changes.
- This structure must be per-component, as any component may match to any combination of tokens. 
    
    Example:
    > Component A background uses FST `fst-token-a` and Fluent 2 token `fluent2TokenA`
    Component B background uses FST `fst-token-a` and Fluent 2 token `fluent2TokenB`
- Meta-data about tokens should be made available for developers.

## 💻 Proposed Solutions

- JSON as a source of truth describing the relationship per component of FST, optional FST, and alias (fluent 2) tokens.
- Export FST as a string const to allow for string interpolation which for products should compile by bundlers such as webpack to a string.
     - This fallback structure should use CSS variables.
- A CSS variable fallback structure such as `var(--fst-token-a, var(--fluent2TokenA))`
- A scripted way to generate the fallback structure from JSON metadata
- Exporting the fallback structure to be per component

### Per component package structure

```
packages/
└ tokens-components/
     └ tokens-button (@fluentui/tokens-button)
     └ tokens-checkbox (fluentui/tokens-checkbox)
     └ ... etc.
```

### JSON file describing metadata of tokens

Example content of `packages/tokens-components/tokens-button/dependencies.json`:
```json
[
    {
        "name": "backgroundControlBrandRest",
        "fst": "background-control-brand-rest",
        "f2": "colorBrandBackground"
    },
    {
        "name": "backgroundControlBrandHover",
        "fst": "background-control-brand-rest",
        "optional": "background-control-brand-hover",        
        "f2": "colorBrandBackgroundHover"
    },
... etc.
]
```

### Export string variables representing the CSS fallback structure

Use a script to convert the components JSON dependency file above to exported variables.

Generated file from dependencies.json example (`packages/tokens-components/tokens-button/src/index.ts`): 

```ts
export const backgroundColorBrandRest = `var(--fst-background-color-brand-rest, var(--colorBrandBackground))`;
export const backgroundControlBrandHover = `var(--fst-background-control-brand-hover, var(--fst-background-control-brand-rest, var(--colorBrandBackgroundHover)))`;
... etc.
```

Example usage (`packages/web-components/button/button.styles.ts`):
```ts
import { backgroundColorBrandRest } from "@fluentui/tokens-button";

export styles = css`
    :host {
        background: ${backgroundColorBrandRest};
    }            
`;
```

### Notes on Token Design Language

FST may have the following options:
- Optional - these override another FST, there should only ever be 1 optional and 1 other FST 
- Null - Additional theming options (to support existing platforms or future theming needs). Does not have an existing F2 fallback. Empty (Does nothing) when undefined

In Figma these are represented as the following:

![Image](https://github.com/user-attachments/assets/4c7eb0eb-c698-4e69-afcd-f94b845a3b48)

"->" in the FST variable names denotes an "Optional token."
These tokens have an FST fallback. For example, Size/Indicator Pill/Length->Hover falls back to Size/Indicator Pill/Length/Rest.

![Image](https://github.com/user-attachments/assets/fa25363c-f403-42a3-a70f-edcd1f5995c2)

"--" in the FST variable names denotes a "Null token."

#### Understanding the Design System

Previously we had no way to understand which tokens were part of any given component. This can change by adding a complete set of tokens with details such as descriptions, the components that each token uses, and fallback options (referred to as f2). There are more opportunities for adding additional meta data to the tokens package, this is not covered in this RFC but may be a future RFC.

#### Themeing

This is also not covered in this RFC, only the individual structural applications of the FST to components.

This is a rather large update, which adds a significant number of additional published packages to the repository. Please drop any comments below!

### Additional context

There are some small edge cases where additional CSS may be needed in components to overcome any instances where the FST are not a 1:1 match with Fluent 2 tokens. This will need to be resolved, the most likely result will be an additional internal CSS variable. An example of this would be how shadows are handled, with 6 FST to 1 Fluent 2 token.

Additional style example:
```css
:host {
    --internal-shadow: 0 var(--fst-control-fab-bg-fg-shadow-key-rest-y) var(--fst-control-fab-bg-fg-shadow-key-rest-blur) var(--fst-control-fab-bg-fg-shadow-key-rest-color), 0 var(--fst-control-fab-bg-fg-shadow-ambient-y) var(--fst-control-fab-bg-fg-shadow-ambient-blur) var(--fst-control-fab-bg-fg-shadow-ambient-color)
    box-shadow: var(--internal-shadow, var(--shadow2));
}
```

### Have you discussed this feature with our team

@EdDaWord, @chrisdholt, @mltejera, @brandonthomas, @JustSlone

### Validations

- [x] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

Medium

**Comment by spmonahan** [comment]
Great work! I have a question:

Having Fluent Web Components support the Fluent 2 token set helps keep WC and React visually consistent should they be used together in a page/app. Does Fluent React need to adopt FST to maintain this consistency?

> the components that each token uses,

I wonder if this component usage metadata could somehow be tied into the generation script you mentioned? This way the component must be hooked into the build process to be listed in the metadata so it remains accurate.

**Comment by janechu** [comment]
> Having Fluent Web Components support the Fluent 2 token set helps keep WC and React visually consistent should they be used together in a page/app. Does Fluent React need to adopt FST to maintain this consistency?

Yes! There is a team working on this with us.

> > the components that each token uses,
> 
> I wonder if this component usage metadata could somehow be tied into the generation script you mentioned? This way the component must be hooked into the build process to be listed in the metadata so it remains accurate.

We haven't discussed this in particular, but I could see us adding this as an extra check.

**Comment by ling1726** [comment]
@janechu the RFC process involves creating the RFC as a pull request to the RFC folder in the repo https://github.com/microsoft/fluentui/tree/master/docs/react-v9/contributing/rfcs/react-components
