### ISSUE TITLE
[Bug]: Popover Overflow Issue When Adding Content

### ISSUE THREAD

**Issue by TalZamirM** [microsoft/fluentui#33162]
### Component

Accordion

### Package version

9.52.0

### React version

16.14.0

### Environment

  System:
    OS: Windows 11 10.0.26100
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 8.97 GB / 31.60 GB
  Browsers:
    Edge: Chromium (130.0.2849.56)
    Internet Explorer: 11.0.26100.1882

### Current Behavior

**Bug Report:**

We are encountering an issue with the Popover component in Fluent UI 9. When the Popover is mounted to a button and opened, it functions correctly. However, when we add more content to the Popover using a button within it, the Popover exceeds the screen boundaries. As a result, users cannot scroll to access the whole popover content, making it inaccessible.

**Before adding additional fields to the content:**
![Image](https://github.com/user-attachments/assets/83845770-3c00-456e-931b-e154c5064b3d)

**After adding additional fields to the content:**
![Image](https://github.com/user-attachments/assets/098ed021-e731-4b02-98df-106dff91642f)

Thank you.

### Expected Behavior

**Expected Behavior:** The Popover should adjust its size or provide a scrollable area to ensure all content remains accessible within the viewport.

**Actual Behavior:** The Popover expands beyond the screen limits, and there is no scrolling functionality to view the hidden content.

### Reproduction

Creating a Popover content overflow

### Steps to reproduce

- Render a Popover attached to a button.
- Click the button to open the Popover.
- Click a button inside the Popover to add more content.

### Are you reporting an Accessibility issue?

yes

### Suggested severity

Medium - Has workaround

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@TalZamirM have you tried `autoSize`? https://react.fluentui.dev/?path=/docs/concepts-developer-positioning-components--docs#auto-size-for-small-viewport

**Comment by TalZamirM** [comment]
I wasn't aware this existed. It works like a charm, thank you!
