### ISSUE TITLE
[Bug]: react-tag-picker cypress tests fail on OSX

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#33173]
### Component

TagPicker

### Package version

workspace:*

### React version

17

### Environment

osx

### Current Behavior

cypress tests are failing on OSX. Reproduced locally and on CI.

This is critical to our migration to GHA utilising ARM agents in order to be compliant with security efforts.

see https://github.com/microsoft/fluentui/pull/33070/files#diff-294ac31394ab40e9246a7dced5c4dcb0e70fa231625bdde6a16c925c0a5bfec8

### Expected Behavior

cypress tests work cross platform

### Reproduction

https://github.com/microsoft/fluentui/pull/33070/files#diff-294ac31394ab40e9246a7dced5c4dcb0e70fa231625bdde6a16c925c0a5bfec8

### Steps to reproduce

1. checkout https://github.com/microsoft/fluentui/pull/33070 
2. un-skip problematic tests https://github.com/microsoft/fluentui/pull/33070/commits/fa133c18765caecb2475479656ec907cab939247#diff-294ac31394ab40e9246a7dced5c4dcb0e70fa231625bdde6a16c925c0a5bfec8
3. run `yarn nx run react-tag-picker:e2e`
4. see CI fail ( or locally if you're on Mac ) 

### Are you reporting an Accessibility issue?

None

### Suggested severity

Medium - Has workaround

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
@YuanboXue-Amber would you please be able to check this one?
