### ISSUE TITLE
[Bug]: Dropdown Component Jumps Position When Resizing Browser Window in Dialog Component

### ISSUE THREAD

**Issue by jaime-fp** [microsoft/fluentui#33180]
### Component

Dropdown

### Package version

^9.54.14

### React version

^18.3.1

### Environment

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 2.99 GB / 15.71 GB
  Browsers:
    Edge: Chromium (129.0.2792.89)
    Internet Explorer: 11.0.19041.4355

### Current Behavior

I am experiencing an issue with the `Dropdown` component when it is placed inside a `Dialog` component. This problem only occurs when the React app is running inside the browser-based Microsoft Teams app. When the browser window is resized, the dropdown position unexpectedly jumps to different areas on the screen, causing visual inconsistency and usability issues.

[Current behavior video](https://github.com/jaime-fp/bug-recordings/raw/refs/heads/main/dialog-dropdown-bug.mp4)

### Expected Behavior

The dropdown should handle resizing flawlessly, maintaining its position relative to its parent component within the dialog regardless of window size changes.

### Reproduction

https://stackblitz.com/edit/r7fupd?file=src%2Fexample.tsx

### Steps to reproduce

**Prerequisite:**
This issue only occurs when the component is running inside the browser-based Microsoft Teams app and I have not been able to replicate it in StackBlitz.

**Steps to replicate**
1. Use the provided code snippet to create a `Dialog` containing a `Dropdown` with multiple options.
2. Open the dialog and interact with the dropdown.
3. While the dialog is open, resize the browser window.
4. Observe the dropdown's behavior as the window resizes.

Code snippet:
``` typescript
const DialogDropdownBug = () => {
  return (
    <Dialog open={true}>
      <DialogSurface>
        <DialogBody>
          <DialogTitle>dropdown window bug</DialogTitle>
        </DialogBody>
        <DialogContent>
          <Dropdown style={{ width: "100%" }}>
            {Array.from({ length: 100 }, (_, i) => `Option ${i}`).map((o, i) => (
              <Option id={i.toString()} value={o} text={o}>
                {o}
              </Option>
            ))}
          </Dropdown>
        </DialogContent>
      </DialogSurface>
    </Dialog>
  );
};
```

### Are you reporting an Accessibility issue?

None

### Suggested severity

Medium - Has workaround

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
Duplicate https://github.com/microsoft/fluentui/issues/30166#issuecomment-2296316794
