### ISSUE TITLE
[Bug]: DataGrid: Clicking on Button in a cell also changes selection

### ISSUE THREAD

**Issue by eddieleem** [microsoft/fluentui#33249]
### Component

DataGrid

### Package version

9.56

### React version

18

### Environment

```shell
npmPackages:
    @fluentui/react-components: ^9.56.0 => 9.56.0 
    @types/react: ^18 => 18.3.12 
    @types/react-dom: ^18 => 18.3.1 
    react: ^18 => 18.3.1 
    react-dom: ^18 => 18.3.1 
```

### Current Behavior

Clicking on a button or checkbox in a cell also changes the DataGrid selection. 

### Expected Behavior

Clicking on a button or checkbox in a cell must not change the DataGrid selection

### Reproduction

https://react.fluentui.dev/?path=/docs/components-datagrid--docs

### Steps to reproduce

1. Go to https://react.fluentui.dev/?path=/docs/components-datagrid--docs
2. Go to 'Focusable Elements In Cells' section
3. There are buttons for a selectable DataGrid
4. Click on any buttons

### Are you reporting an Accessibility issue?

None

### Suggested severity

High - No workaround

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
@eddieleem this is easily solved by stopping propagation on click of the button, but I agree that this should be added to the example, so I'll raise a PR to add that information.

**Comment by eddieleem** [comment]
> stopping propagation

I've already tried stopPropagation but that did not work. I do agree adding an example would be very helpful.

Thank you.

**Comment by eddieleem** [comment]
@khmakoto Thank you. You are right.
I've checked again and I confirm stopPropagation worked like a charm for Button and is not a bug for DataGrid.

However, I found that stopPropagation does not work with Checkbox or ToggleButton.

Using stopPropagation affected the actual function of Checkbox and ToggleButton, meaning it stopped changing the selection for DataGrid but that made checkbox uncheckable.

It's a bug of Checkbox and ToggleButton. I will open another issue.

**Comment by eddieleem** [comment]
Interesting...
It's not a bug for Checkbox or ToggleButton but this behavior only happens when Checkbox or ToggleButton are used within DataGrid.

with stopPropagation, Checkbox does not toggle.

```
    createTableColumn<SortItem>({
      columnId: "distinct",
      renderHeaderCell: () => {
        return "Distinct";
      },
      renderCell: (item) => {
        return (
          <>
            <Checkbox checked={item.distinct.distinct}
              onChange={(ev) => {
                item.distinct.distinct = ev.target.checked;
              }}
              onClick={(ev) => ev.stopPropagation()}
            />
          </>
        );
      },
    }),
```

https://github.com/user-attachments/assets/ffafb939-4ee3-49ed-bf88-6d06ae600fdd

**Comment by eddieleem** [comment]
Here is the bypass of the problem.
```
            <Checkbox checked={item.distinct.distinct}
              onClick={(ev) => {
                ev.stopPropagation();
                item.distinct.distinct = !item.distinct.distinct;
                setSortColumns([...sortColumns]);
              }}
            />
```

**Comment by khmakoto** [comment]
> Interesting... It's not a bug of Checkbox or ToggleButton but this behavior only happens when Checkbox or ToggleButton are used within DataGrid.
> 
> with stopPropagation, Checkbox does not toggle.
> 
> ```
>     createTableColumn<SortItem>({
>       columnId: "distinct",
>       renderHeaderCell: () => {
>         return "Distinct";
>       },
>       renderCell: (item) => {
>         return (
>           <>
>             <Checkbox checked={item.distinct.distinct}
>               onChange={(ev) => {
>                 item.distinct.distinct = ev.target.checked;
>               }}
>               onClick={(ev) => ev.stopPropagation()}
>             />
>           </>
>         );
>       },
>     }),
> ```
> 
>  Screen.Recording.2024-11-13.at.9.43.36.AM.mov

@eddieleem I don't know why that's happening for you, but you can see in [this StackBlitz](https://stackblitz.com/edit/2f2nh8?file=src%2Fexample.tsx) that we can stop propagation and still have `Checkbox` and `ToggleButton` toggle correctly.

**Comment by eddieleem** [comment]
Ahh, it turns out it was a problem of using 'controlled' components in DataGrid. That's why setting the data for DataGrid made it work correctly.

Thank you very much for your patience and kind reply.

**Comment by khmakoto** [comment]
No problem! Let us know if there is anything else I can do to help!
