### ISSUE TITLE
[Docs]: I can't find setTheme using CDN

### ISSUE THREAD

**Issue by Rizary** [microsoft/fluentui#33244]
### Area

Web Components (https://web-components.fluentui.dev)

### What kind of documentation issue are you reporting?

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://web-components.fluentui.dev/?path=/docs/concepts-developer-quick-start--docs#setup

### Description

I tried to follow the step:
```js
import { setTheme } from '@fluentui/web-components';
import { webLightTheme } from '@fluentui/tokens';

setTheme(webLightTheme);
```

and based on the [usage section](https://web-components.fluentui.dev/?path=/docs/concepts-developer-quick-start--docs#usage), I can just easily use the button by import like this: `import '@fluentui/web-components/button.js';`

When I try change the appearance into primary, the button didn't change. Turns out, there's no `setTheme` in the cdn file.

### Validations

- [x] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

**Comment by apoorvarajan** [comment]
I am using 2.6.1 version and am still not able to find setTheme. Is there any solution for this?
