### ISSUE TITLE
[Bug]: Fluent dropdown item is read out twice by narrator

### ISSUE THREAD

**Issue by JamesBurnside** [microsoft/fluentui#33292]
### Package

react

### Package version

LTS (repros on https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown)

### React version

LTS (repros on https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown)

### Environment

```shell
https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown
```

### Current Behavior

Narrator _sometimes_ reads out the combobox selection twice.

Observe:
- Narrator reads out the selection twice

See recording. The first time I try everything is A-OK. The second time the issue repros.

It reads: "Fruits Group Apple 1 of 7 Selected Apple 1 of 7 Selected"
Notice: "Apple 1 of 7 Selected" is read out _twice_.

We have had bug filed on us on both on windows narrator and safari voice over.

https://github.com/user-attachments/assets/5b06f899-bdd0-40ff-949a-8a1180d8063c

### Expected Behavior

It should only read it out once

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown

### Steps to reproduce

- Turn on narrator
- Navigate to combobox
- Hit enter to open combobox

### Are you reporting an Accessibility issue?

yes

### Suggested severity

Urgent - No workaround and Products/sites are affected

### Products/sites affected

Out customers using https://azure.github.io/communication-ui-library/

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by JamesBurnside** [comment]
This issue has been filled similarly a couple times before:
- https://github.com/microsoft/fluentui/issues/13772
- https://github.com/microsoft/fluentui/issues/9885
- https://github.com/microsoft/fluentui/issues/18630

**Comment by sopranopillow** [comment]
Hi @JamesBurnside, I looked into this and couldn't get it to repro. I also asked our a11y expert, @smhigley, and she wasn't able to repro in voice over. We discussed it a bit more and this might be one of those narrator quirks, so since this is v8 and sometimes narrator does this in general we will leave this as won't fix. If you have any thoughts on this or find a way to repro consistently feel free to reopen the bug, thanks for your patience!
