### ISSUE TITLE
[Bug]: Combobox cannot type more character in input area after matching an option

### ISSUE THREAD

**Issue by MirandaGe** [microsoft/fluentui#33437]
### Component

Combobox

### Package version

9.56.3

### React version

17.0.1

### Environment

```shell
Edge chromium latest version
Narrator latest version
```

### Current Behavior

1. Open Narrator
2. Set focus into a combo box
3. Input any character which can map one option inside the dropdown list
4. The focus dumps to the matched option, and if I type more characters, the characters fail to insert.
See video: [demo](https://microsoft-my.sharepoint-df.com/:v:/p/lingge/EXhgmUU-5LtGin1NjA2TjnkB6y71ItqfJP8lUxOuRn1jxQ?e=o30JCN)

### Expected Behavior

If I type some characters with matched option, I can continue typing more characters.

### Reproduction

https://stackblitz.com/run?file=src%2Fexample.tsx

### Steps to reproduce

1. Open Narrator
2. Set focus into a combo box
3. Input any character which can map one option inside the dropdown list
4. The focus dumps to the matched option, and if I type more characters, the characters fail to insert.

### Are you reporting an Accessibility issue?

yes

### Suggested severity

Urgent - No workaround and Products/sites are affected

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by betrue-final-final** [comment]
@smhigley what is happening here? It seems that focus is getting moved to the menu. Is this actually Fluent 2 behavior now?

**Comment by smhigley** [comment]
Hi! From your video, it appears that you switched Narrator into scan mode, which is why you cannot continue to type. This has nothing to do with Fluent, this is just how Windows screen readers work. In scan mode (or in VPC cursor in JAWS, or browse mode in NVDA), character keys activate specific navigation shortcuts, and are not used for typing. If you wish to type, you need to be in application mode / forms mode. The reason Narrator said "unavailable" is because there were no available navigable controls for the characters you pressed.

Hope that helps!

**Comment by MirandaGe** [comment]
Hi @smhigley , thanks for the quick response, let me add more details about the repro steps:
Firstly, I set scan mode on when navigating to the combobox input area. When focusing on the input area, scan mode will close automatically (I didn't do it manually). If I start typing, (again I didn't change any Narrator scan mode manually), scan mode will automatically set as on and it prevent me from typing more characters into it. 
Could you help confirm whether it is still expected behavior? If so, I can have this issue closed. Thank you again!
