### ISSUE TITLE
font sizes defined in `px` instead of `rem`

### ISSUE THREAD

**Issue by jligeza** [microsoft/fluentui#33488]
Having font sizes for tokens/components defined in `px` instead of `rem` hurts accessibility, because it makes them unaffected by web browser global font size setting.

It would be better to have them and line heights converted to `rem`.

https://github.com/microsoft/fluentui/blob/b59061d2bf717f833fa28c4968b9238f6fdde962/packages/tokens/src/global/fonts.ts#L3

**Comment by layershifter** [comment]
That's the intentional decision to go with pixels over rem units.

I don't recall if there is a RFC about it, but it was discussed multiple times in offline and it was decided to use pixels.

**Comment by jligeza** [comment]
> That's the intentional decision to go with pixels over rem units.
> 
> I don't recall if there is a RFC about it, but it was discussed multiple times in offline and it was decided to use pixels for Fluent UI over other units.

I am curious why you decided not to go with `rem`, which is needed for optimal accessibility. Could you explain?
