### ISSUE TITLE
[Bug]: Popover - autoSize: true - Bottom arrow disappears and causes redundant scroll

### ISSUE THREAD

**Issue by TalZamir** [microsoft/fluentui#33481]
### Component

Accordion

### Package version

9.52.0

### React version

16.14.0

### Environment

```shell
System:
    OS: macOS 15.2
    CPU: (14) arm64 Apple M3 Max
    Memory: 189.44 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 131.0.6778.140
    Edge: 131.0.2903.99
    Safari: 18.2
```

### Current Behavior

When the container resizes, the arrow icon moves from the bottom to inside the container, causing redundant scrolling.

### Expected Behavior

The arrow icon should remain in its place and not move inside the container, causing redundant scrolling.

### Reproduction

...

### Steps to reproduce

1. Open a popover.
2. Trigger a resize event.
3. The arrow moves from the bottom and is no longer positioned correctly, causing redundant scrolling, even though there is enough space for the container. (Hiding the arrow element using the browser's dev-tools removes the redundant scroll.)

### Are you reporting an Accessibility issue?

None

### Suggested severity

Low - Has or doesn't need a workaround

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@TalZamir please provide a reproduction case.
