### ISSUE TITLE
[Bug]: Panel footer has transparent background until screen resizing

### ISSUE THREAD

**Issue by Elaina-Lee** [microsoft/fluentui#33508]
### Package

react

### Package version

8.110.2

### React version

19.0.0

### Environment

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 10.22 GB / 31.83 GB
  Browsers:
    Edge: Chromium (130.0.2849.46)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    @types/react: 18.3.0 => 18.3.0 
    @types/react-dom: 18.3.0 => 18.3.0
```

### Current Behavior

The panel footer is transparent and therefore extending the body image until the manual resizing of the screen happens.

Before resizing of the screen (initial panel rendering)

After resizing of the screen (manually dragging the browser to trigger resizing)

### Expected Behavior

The panel footer should not be transparent and be rendering the same of after resizing of the screen since the beginning.

Both on initial rendering and after resizing the screen

### Reproduction

https://codepen.io/ijackson/pen/BamONop

### Steps to reproduce

I found the same issue that was submitted from before, https://github.com/microsoft/fluentui/issues/21869; therefore, I am re-using the codepen from the issue.

I am observing the same issue, and am looking for a fix (the duplicate issue from the past has been closed)

### Are you reporting an Accessibility issue?

no

### Suggested severity

Urgent - No workaround and Products/sites are affected

### Products/sites affected

Portal Logic Apps Templates

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Removing screenshots in case there's confidential info and the linked issue explains the problem
