### ISSUE TITLE
[Feature Request] Vertical Tab list item and tab panel

### ISSUE THREAD

**Issue by nikhilexe** [microsoft/fluentui#3593]
In our product we wanted to have vertical tab list similar to shown in below image, if I see this it is extension of Pivot except it is rendered vertically and have splitter to separate left and right section. We need splitter so that customer can drag it as per need. Can we extend pivot to support this or we can have separate component? 

![image](https://user-images.githubusercontent.com/25940082/34108947-17aa97f6-e428-11e7-9fb0-d1860f9d4a62.png)

**Comment by aditima** [comment]
@dzearing @betrue-final-final @Jahnp - new component request.

**Comment by micahgodbolt** [comment]
@betrue-final-final do we have any designs for this type of behavior?

**Comment by JustSlone** [comment]
Closing this as this is an old request and not something included in the designs. If someone is interested in building this component and contributing it as a community component, let me know
