### ISSUE TITLE
Calendar component range select

### ISSUE THREAD

**Issue by bengcooper** [microsoft/fluentui#3600]
It would be nice if you could select a date range with the component by selecting the start date then the end date (this could be optionally only enabled when the user is holding down the shift key).

**Comment by michaelangotti** [comment]
This sounds like a reasonable ask. @betrue-final-final What do you think?

**Comment by bmckilligan** [comment]
I think the best implementation of this is the 'Timeline' component available for pivot tables in Microsoft excel.

The web version of Excel has support for this feature, and it would be great to have this.  

The control appears to be called  'timeSlicer' , guessing by the css classnames used in the sub components,   'ewr-timeslicer-background',   'ctl00_m_timeSlicerContainer'  ect ... 

An example of a simpler version of this  http://ghusse.github.io/jQRangeSlider/demo.html

which brings up a different but related feature request, a range slider control for regular numeric values,  

from the documentation on https://developer.microsoft.com/en-us/fabric#/components/slider ,  it looks like the sliders are for returning single values

**Comment by juliehubs** [comment]
I'll add that adding in time range as well would be awesome! 

Thanks for all your hard work!

**Comment by assafsun** [comment]
is this issue still open for PR?

**Comment by JustSlone** [comment]
@lorejoh12, are we still interested in taking a PR for this feature? Any pending changes to Calendar that would affect this feature?

**Comment by bmckilligan** [comment]
any updates on this?
