### ISSUE TITLE
Feature Request : Option to select "All" in multi select dropdown

### ISSUE THREAD

**Issue by samikroy** [microsoft/fluentui#3726]
Currently Multiselect dropdown component allows to select multiple choices. Is there a possibility to have an option as "All". Upon check and uncheck by the users, all other options will be checked and unchecked  respectively. In case of unchecking  any option "All" should get unchecked as well.
Can this be a new property to the dropdown component.

**Comment by betrue-final-final** [comment]
This isn't usually a feature seen in these as the more common case is just selecting a couple, and this would add a whole new row. We'll take it under advisement and get back to you.

**Comment by jayeshvg** [comment]
Sounds like a required feature. Usually in multi select we would need Select "All" option which can work smartly depending on the selection. Any considerations?

**Comment by oengusmacinog** [comment]
feature request stay alive

**Comment by oengusmacinog** [comment]
@samikroy @jayongg Just an update that this is not currently on our roadmap.  However, we would be happy to review a PR for this change if you'd like to submit one.

**Comment by qazizaahirah** [comment]
Any plans for implementing this feature?

**Comment by micahgodbolt** [comment]
no plans right now. we're considering a major overhaul for dropdown/combobox and would certainly consider this feature then

**Comment by xugao** [comment]
@chsach2050 reported same request in #11640. we should make sure this feature request gets attention . FYI @khmakoto

**Comment by agg23** [comment]
Pushing for attention once again. It's not incredibly difficult to add "select all" yourself, but the lack of indeterminate support is problematic.

**Comment by vorobievik** [comment]
> Pushing for attention once again. It's not incredibly difficult to add "select all" yourself, but the lack of indeterminate support is problematic.


please tell me how can I do it myself

**Comment by rwormsbecher** [comment]
@vorobievik 

I created a select all version the other day, even though the code could be written cleaner I will provide the onChange method. From there you should be able to find out what's going on, if not let me know, I will help you to clarify it.

```

 const _onChange = (event: React.FormEvent<HTMLDivElement>, item: IDropdownOption | undefined): void => {
        if (item) {

            // if the option all sites is selected, update the uniqueSiteOptions to contain all sites but alloptions
            if (item.key === 'all options') {
                const allOptionsIsChecked = sitesSubset.indexOf('all options') > -1 ? false : true;

                if (allOptionsIsChecked) {
                    const allSitesExceptAllOptions = uniqueSiteOptions.map(site => {
                        return site.text
                    })
                    setSitesSubset(allSitesExceptAllOptions);
                } else {
                    setSitesSubset([] as string[])
                }


            } else {
                // create a new object to get rid of the reference.
                let tempData: any = [...sitesSubset];
                if (sitesSubset.indexOf(item.text) === -1) {

                    tempData.push(item.key);

                    // if all options are selected, check the all options checkbox.
                    if (uniqueSiteOptions.length - (sitesSubset.length + 1) === 1) {
                        tempData.push("all options");
                    }

                    setSitesSubset(tempData);
                } else {
                    // if not all options are selected, uncheck the all options checkbox
                    if (uniqueSiteOptions.length - (sitesSubset.length) == 0) {
                        tempData = tempData.filter(item => item !== 'all options');
                    }
                    setSitesSubset(tempData.filter(entry => item.text !== entry));
                }
            }
        }
    };

```
The most important part is the main else block. Here we will check whether the length of the options checked is equal to the total number of options, plus or minus one depending is the "all options" checkbox is selected.

**Comment by jeffersoneagley** [comment]
I'm also currently having to implement both this and dropdown searching for a web portal that needs the "select all" in basically all of my filter sets.

**Comment by Github307** [comment]
Hi, are there any updates on this feature? @jahnp @micahgodbolt @xugao 

As mentioned in above comments, implementing 'Select All' functionality can be done, but we need to show indeterminate state in the 'Select All' checkbox, when all options are not selected. 

![image](https://user-images.githubusercontent.com/38312563/98127163-6325eb80-1edc-11eb-8b04-2bf6c22d5907.png)

Any approach to achieve this in UI?

**Comment by Satyarthsr** [comment]
Hi, any updates if or when will this feature be added? @Jahnp  @micahgodbolt  @xugao .

**Comment by skoofy5** [comment]
Still no movement on this?

**Comment by jeffersoneagley** [comment]
Yea I'm still using an overloaded button+contextualmenu to achieve basically the same dropdown that's in fluent's northstar designs.

**Comment by JustSlone** [comment]
@smhigley can you share here the workaround we have for adding select all to a multi-select dropdown. 

In terms of building this into the component. This will have to wait until we converge/refactor dropdown/combobox as part of the Fluent UI vNext effort.

**Comment by nelsonwhyu** [comment]
Hi, hope and seems having "Select All" option in dropdown/combobox multiSelect is the consensus. My firm is adopting fluent ui for software development and it's common than not that our dropdown will contain at least 20+ options and Select All becomes critical for user experience.

Seeing you have plan to overhaul dropdown/combobox, here are some features in my wish-list:

1. Option to Select All
2. Option to Select Group similar to GroupList, within a dropdown box. 
3. Option to filter dropdown menu based on freeform text input, that will be useful if my user need to find that particular option out of a list of 100.

Thanks!

**Comment by scwood** [comment]
For those wanting an example implementation of a custom "Select all" option, here's a small snippet.

```typescript
import { Dropdown, IDropdownOption } from '@fluentui/react';
import React, { useState } from 'react';

const options: IDropdownOption[] = [
  { key: 'all', text: 'All' },
  { key: 'orange', text: 'Orange' },
  { key: 'apple', text: 'Apple' },
  { key: 'banana', text: 'Banana' }
];

const DropdownSelectAllExample: React.FunctionComponent = () => {
  const [selectedKeys, setSelectedKeys] = useState<string[]>([]);

  function handleChange(event: React.FormEvent<HTMLDivElement>, option: IDropdownOption | undefined) {
    if (option === undefined) {
      return;
    }
    if (option.key === 'all' && option.selected === true) {
      setSelectedKeys(options.map((option) => option.key as string));
    } else if (option.key === 'all') {
      setSelectedKeys([]);
    } else if (option.selected) {
      setSelectedKeys([...selectedKeys, option.key as string]);
    } else {
      setSelectedKeys(selectedKeys.filter((key) => key !== option.key));
    }
  }

  return (
    <Dropdown
      multiSelect
      selectedKeys={selectedKeys}
      onChange={handleChange}
      options={options}
      label="Fruits"
      placeholder="Select fruits"
    />
  );
};
```

If you use this, you'll most likely want to implement `onTitleRender`, since the value of the dropdown will be "All, Orange, Apple, Banana" when "All" is selected, but I'll leave that up to the reader.
