### ISSUE TITLE
Theming: isInverted not working or no effect

### ISSUE THREAD

**Issue by emilenriquez** [microsoft/fluentui#3758]
When I load a theme, and toggle `isInverted` option to true/false, I don't see any effect on my site.
#### Actual behavior:
no change

#### Expected behavior:
should toggle `dark` and `light` themes.

**Comment by lambertwang** [comment]
I don't know exactly what you're trying to do, but I think you should take a look at the theming document  
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/Theming.md

**Comment by Jahnp** [comment]
Hey @emilenriquez do you have a repro or CodePen environment so we can see the issue?
