### ISSUE TITLE
Horizontal and vertical scrollbars in DetailsList when none should be needed

### ISSUE THREAD

**Issue by antonafMSFT** [microsoft/fluentui#4258]
### Bug Report

- __Package version(s)__: v5.60+, lower versions not tested.
- __Browser and OS versions__: IE11.

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:

Scrollbars are added to scroll the content of the DetailsList when no scrolling should be necessary.

#### Actual behavior:

A vertical and a horizontal scrollbars added.

#### Expected behavior:

No scrollbars.

### If applicable, please provide a codepen repro:

https://developer.microsoft.com/en-us/fabric#/components/detailslist

**Comment by lambertwang** [comment]
In your repro, the `overflow-y: scroll` css is added to the Details List grouped example explicitly. Are there scenarios in which the scrollbar appears when a user doesn't intend for their list to have a scrollbar?
