### ISSUE TITLE
Feature Request: Custom Chevron icon for Nav

### ISSUE THREAD

**Issue by newtonsheikh** [microsoft/fluentui#4417]
### feature request: Customize the chevron icons in < Nav />

- __Package version(s)__: 5.75.0

Original Stackoverflow [StackOverflow](https://stackoverflow.com/questions/49542450/override-officeui-nav-chevron-icon) question

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix?  No

Requested priority: Low 

Products/sites affected: (if applicable)

#### Describe the issue:

The current < Nav /> has default chervron icons for group links, it would be great if we could customize it.

Please see the example below. To acheive the following i had to hack the code. 

File: Nav.base.tsx
`    return (
      <div
        { ...divProps }
        key={ link.key || linkIndex }
        className={ classNames.compositeLink }
      >
        { (link.links && link.links.length > 0 ?
          <button
            className={ classNames.chevronButton }
            onClick={ this._onLinkExpandClicked.bind(this, link) }
            aria-label={ this.props.expandButtonAriaLabel }
            aria-expanded={ link.isExpanded ? 'true' : 'false' }
          >
            { link.isExpanded ?
              <Icon className={ classNames.chevronIcon } iconName='OpenFolderHorizontal' />
              : <Icon className={ classNames.chevronIcon } iconName='FolderHorizontal' />
            }
          </button> : null
        ) }
        { this._renderNavLink(link, linkIndex, nestingLevel) }
      </div>
    );
  }
`
File: Nav.styles.ts

`chevronIcon: [
      'ms-Nav-chevron',
      {
        position: 'absolute',
        left: '8px',
        height: `${navHeight}px`,
        lineHeight: `${navHeight}px`,
        fontSize: '12px',
        transition: 'transform .1s linear',
      },
      isExpanded && {
        transform: 'rotate(0deg)',
      },

`

#### Expected behavior:

![basicnav](https://user-images.githubusercontent.com/5118869/38150679-c7b62192-347d-11e8-8cdc-7364ceff1325.gif)

**Comment by JasonGore** [comment]
This should be considered when resolving #5815 and have added a reference to this issue there.

**Comment by JustSlone** [comment]
Work on Nav isn't currently on our backlog, keeping this open to possibly consider in the future, but making it clear it won't be soon
