### ISSUE TITLE
Component Classes should not define their methods with lambdas, as it prevents inheritance

### ISSUE THREAD

**Issue by craftytrickster** [microsoft/fluentui#4478]
As of Fabric version `5.79.1`, I have noticed a mix of lambda and regular method functions in the classes such as `BasePicker`.

In the below case, you will see that onInputChange is such an example.

An example can be seen in its typings:
```ts
    protected updateSuggestionsList(suggestions: T[] | PromiseLike<T[]>, updatedValue?: string): void;
    protected resolveNewValue(updatedValue: string, suggestions: T[]): void;
    protected onChange(items?: T[]): void;
    protected onInputChange: (value: string) => void;
```

Besides being inconsistent, it prevents the ability to cleanly call super methods, since TypeScript is unable to reason that the lambda is actually a function on the parent class.

So, if I were to derive from BasePicker, and do something like this:

```ts

protected onInputChange = (value: string) => {
   console.log('VsCode is really good');

  // super.onInputChange(value); // THIS DOES NOT WORK
  
  // instead, I need to do something like this:
  (BasePicker.prototype as any).onInputChange.call(this, value);
}
```

It is not urgent, but it is a nuisance, and I am sure this is probably in other components as well.

Thanks for the help.

**Comment by dzearing** [comment]
We need someone to look for protected methods to ensure they aren't using lambdas. 

@joschect I believe pickers are the only place we rely on protected. I didn't know this would happen. Are we missing tests to validate this?

**Comment by joschect** [comment]
@dzearing Pickers is probably one of the only components that uses protected functions in this manner, but there could be others lurking. While I don't believe that we have them overridden anywhere it could be an issue. I can certainly revert them and add some tests if that's the route we want to go. Alternatively, we could leave them as is, deprecate the idea of extending a component and remove that concept entirely from 6.0.

**Comment by aditima** [comment]
@dzearing - what is your latest guidance on this?

**Comment by dzearing** [comment]
@joschect I do think we should remove protected and overriding; it's just not a good practice, but! not in the current major release. That is a huge change for partners.

@joschect When these were using autobind, were we able to use super correctly? Should we just move back to autobind for pickers?

**Comment by joschect** [comment]
Yes we were able to use it with autobind. We could go back to that for pickers, or why not just do the bindings in the constructors and comment it so it's noted as a current special case?

**Comment by khmakoto** [comment]
@dzearing, @joschect is this something we'd still like to tackle? I could work on getting read of lambdas in protected methods.

**Comment by JustSlone** [comment]
Updating Pickers is not currently on our roadmap, when we update pickers we'll likely move to function components as well. However, since this is an issue in the existing pickers, keeping this open

**Comment by JustSlone** [comment]
Closing this out as it is irrelevant with the move to function components going forward, if there is a strong case to fix this now feel free to re-open with reasoning
