### ISSUE TITLE
Picker: add defaultValue

### ISSUE THREAD

**Issue by thelok** [microsoft/fluentui#4642]
It would be nice if the Picker could be given an initial value to set for the input text box as a raw string. My use case is that I want to load a form with a pre-defined raw text value. It looks like the only way to set any default value is to use `defaultSelectedItems` or `selectedItems` but I wish to allow the user to modify the text string so that my suggestions can be populated. However, the user is not able to "modify" the values in the text -- they can remove the data from `defaultSelectedItems` or `selectedItems` but they can't perform editing unless they type in the raw string themselves.

**Comment by michaelangotti** [comment]
@betrue-final-final Your thoughts?

**Comment by thelok** [comment]
One use case is pre-loading a value while still letting the user modify the terms of the picker suggestions. Currently the picker only allows all or none (i.e. select a picker value or clear it) but there is no in between of allowing raw text manipulation similar to a text box.

I guess another solution that would be nice is letting the user modify the picker selection and choosing another value instead of simply wiping out the old raw text value.

**Comment by betrue-final-final** [comment]
I'm so sorry. Can you explain what the user is doing, and what they see, rather than talking about what the code does behind the scenes? 

Are you talking about typing a file name in the box and having it select the file with the characters typed in the file name?

**Comment by thelok** [comment]
The user wants to load a form with a picker to **edit** it, and to make it easier for the user it comes pre-populated with some raw text that will help them start performing their suggestion search using the picker. It's just allow the user to **edit** the picker. The user can start modify the pre-populated raw text and use the picker suggestions.

It's similar to how `defaultValue` or `value` from `TextField` would work.

**Comment by joschect** [comment]
This was likely fixed at some point, You can currently add a default text value to appear on first load by doing
`<Picker inputProps={{defaultVisibleValue: 'some string'}}/>`
