### ISSUE TITLE
Coachmark + Callout: high contrast states

### ISSUE THREAD

**Issue by lynamemi** [microsoft/fluentui#4730]
Coachmark has a lot of problems in high contrast. Will need to coordinate with other Callout components, including TeachingBubble, to come up with a consistent design.

**Comment by aditima** [comment]
Keeping this assigned to @betrue-final-final till we know what the design should be.

**Comment by JasonGore** [comment]
Similar to Dropdown/ComboBox and discussion on #1655, should we consider consolidating Coachmark/Callout/TechingBubble?

**Comment by betrue-final-final** [comment]
Not sure about coachmark, but I imagine teaching bubble could be a variant of callout. I’ll defer to @dzearing there.

**Comment by micahgodbolt** [comment]
Here is the existing coachmark in high contrast. 

![coachmark](https://user-images.githubusercontent.com/1434956/69287329-a93e4e00-0baa-11ea-9ef2-6d0f418d2c1a.gif)



And here it is in regular.

![coachmark-normal](https://user-images.githubusercontent.com/1434956/69287379-e571ae80-0baa-11ea-84a1-9bf4ccea69c2.gif)

I don't think we're too far off. The button states are default buttons (which could be improved at the button level). 

@betrue-final-final are there some obvious tweaks we can make to close this standing issue out?

**Comment by micahgodbolt** [comment]
I'm going to remove the accessibility flag. This is in no way unusable in high contrast. This issue is just about making high contrast look a bit more consistent.

**Comment by JustSlone** [comment]
Closing this out since it's usable as is, if there is a new High Contrast design here, happy to update things. If this continues to be an issue, feel free to reopen
