### ISSUE TITLE
New Component: Tag List

### ISSUE THREAD

**Issue by jimlamb** [microsoft/fluentui#4808]
### Problem

The TagPicker won't always be used in the context of a data-entry form. There will be cases where we want to show the tags associated with an entity and provide an in-place editing experience. 

### Proposed solution

Add a showChromeOnFocusOnly property that, when set to true, hides the border and the "X" (remove) buttons. When the component gets the input focus, these elements will become visible.

**Comment by oengusmacinog** [comment]
@jimlamb This is not how the TagPicker is meant to be used.  It sounds like you want something that functions as a tag cloud (display only).  Marking as a Feature Request that needs design.  I am not sure I understand the context of the edit on focus.

**Comment by michaelangotti** [comment]
@jimlamb Can you provide a little be more background on this request? A use case or example would be helpful. Thanks!

**Comment by jimlamb** [comment]
Sure @michaelangotti. Here's a screenshot of a view that illustrates the issue:

![image](https://user-images.githubusercontent.com/82873/40743085-90c40eda-641e-11e8-821b-037ccd3a5226.png)

The tags are shown in a TagPicker with the border hidden when it doesn't have the input focus. We'd like to constrain the height of the component to 1 or 2 rows of tags when it doesn't have the focus with some kind of overflow indicator. The user should be able to get a feel for how many tags are assigned (roughly) with an easy gesture to see them all and add/remove them when necessary. 

The primary scenario for us is to view tags since they are nearly always added via an automated process. Does that help?

**Comment by dzearing** [comment]
@joschect just fyi

**Comment by JustSlone** [comment]
Keeping this open, but marking Not on roadmap as we're unlikely to implement this anytime soon
