### ISSUE TITLE
Nav: Expanded state of all groups are set back to default if item is added or removed

### ISSUE THREAD

**Issue by Fensterbank** [microsoft/fluentui#4901]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

No

Requested priority: Normal

#### Describe the issue:

It doesn't seem the collapsed/expanded state is preserved in the `Nav` or it is resetted to the initial prop when the `links` prop changed.
When using `Nav` and more items are dynamically inserted to or removed from ~~an expanded group~~ the array of items, all groups becomes collapsed.

Example: https://codesandbox.io/s/x978ln5l5z

If I set `isExpanded: true` for the `Favorite` group, it works as expected, so I could indeed make a workarround for this issue.
See: https://codesandbox.io/s/91mqm265xy

But I think the right way would be, if the component handles the `isExpanded` state and don't fall back to default if an item is changed

#### Actual behavior:

When an item is inserted dynamically to the array of links, the group gets collapsed.

#### Expected behavior:

The group should preserve its expanded state even if items are added or removed dynamically.

**Comment by dzearing** [comment]
Once CollapsibleSection is ready, we should probably integrate into the experimental nav, and then move that to oufr.

**Comment by JasonGore** [comment]
Unfortunately there is no easy fix for this. For this and other issues and to formally document we know we have needed for some time, I have created #5815.

**Comment by vishalgurav** [comment]
**isExpanded**: true is no more working with office-ui-fabric-react version": "6.143.0".

I saw the code form @Fensterbank 's sandbox https://codesandbox.io/s/91mqm265xy and its was working in version "5.96.1"

Can somebody confirm if this is no more available.

**Comment by JustSlone** [comment]
Cleaning up old issues that are unlikely to get fixed. There likely will be a refactor of Nav or a new Nav in the future, given the difficulty of this fix, that should be the approach we take.
