### ISSUE TITLE
[MaskedTextField] The field does not respond to the event settings. 

### ISSUE THREAD

**Issue by IASamoylov** [microsoft/fluentui#4904]
### Bug Report

- __Package version(s)__: (5.104.0)
- __Browser and OS versions__: (ALL)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal) 
#### Describe the issue:

MaskedTextField ignores all user-defined event handlers and does not work with validateOnFocusIn/validateOnFocusOut attribute(when they are set by user)

![epwNV_](https://media.giphy.com/media/mJQLBcZAHmbkfOWVP2/giphy.gif)

#### Actual behavior:
- Does not call user event handlers
- Does not work with validateOnFocusIn/validateOnFocusOut attributes

#### Expected behavior:

- Call user event handlers
- Correct work validateOnFocusIn/validateOnFocusOut attributes

### If applicable, please provide a codepen repro:

https://jsfiddle.net/x4tcuLpa/5/

**Comment by jordandrako** [comment]
It seems to accept almost all native attributes, but `onKeyDown` is used to check the value against the mask, should be simple to add the `onKeyDown` prop to the method it calls, and all the other default attributes it takes over.

However, I'm not sure why the validation options aren't working. @lambertwang Can you take a look? I can submit a PR to fix the native attributes that are not working.
