### ISSUE TITLE
Breadcrumb: allow FocusZone to be removed through slots

### ISSUE THREAD

**Issue by jdrush89** [microsoft/fluentui#4930]
Feature Request:

I'd like to be able to pass an optional prop into a breadcrumb to allow me to manage focus myself instead of using a FocusZone.  I have items surrounding the breadcrumb I'd like to be able to get to via the arrow keys instead of having to tab into a separate zone.

I would be happy to make this change if it sounds like a good suggestion.  I'm currently blocked by this.

**Comment by micahgodbolt** [comment]
I believe the proper approach here would be to allow the focus zone in breadcrumb to be turned off so that you could handle focus yourself, right? We already do something like this in overflowSet (though I think the prop name is a bit verbose).


Is this an approach that't work for you?

**Comment by micahgodbolt** [comment]
We decided the solution for this problem will be solved by adding slots #7308 to this control. This way you can replace the wrapping focus zone with a div and control focus on your own.

**Comment by JustSlone** [comment]
It's unlikely we'll be adding slots to the existing breadcrumb, however eventually we should refresh or converge the component and at that time this will be handled, closing this out
