### ISSUE TITLE
Combobox checked state applied when checked, or when hovered

### ISSUE THREAD

**Issue by suztocco** [microsoft/fluentui#4992]
### Bug Report

- __Package version(s)__: Current

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? NO

Requested priority: High

Products/sites affected: CALENDAR

#### Describe the issue:

There should be a visual difference between a selected menu item and a menu item that has been hovered on.

#### Actual behavior:

The "selected" value in the combobox is the same color as the "hover". 

#### Expected behavior:

I expect the selected value to be separate and to look like the selected state we have for dropdowns.

![image](https://user-images.githubusercontent.com/20954039/40556694-7dc2cc06-6002-11e8-8de2-04f871f5a27d.png)

![image](https://user-images.githubusercontent.com/20954039/40556745-b094f168-6002-11e8-8b86-4ad9db66ea44.png)

**Comment by micahgodbolt** [comment]
Just to clarify, this is not an issue of a missing state, but rather the color for the selected state is incorrect.

If that is the case, can you supply us with the color that the selected state bg should be

**Comment by micahgodbolt** [comment]
ok, looks like it's #dadada
![image](https://user-images.githubusercontent.com/1434956/40800849-4ff42450-64c6-11e8-80a6-f04a5e570ff4.png)

**Comment by betrue-final-final** [comment]
Yes, which is currently neutralQuaternaryAlt

**Comment by micahgodbolt** [comment]
@suztocco is this something you'd be comfortable changing? Should be tracking down the selected bg color and changing it to neutralQuartenaryAlt

![image](https://user-images.githubusercontent.com/1434956/40800928-86e78c90-64c6-11e8-9dba-cf14a4dc9369.png)

**Comment by betrue-final-final** [comment]
@suztocco isn't an engineer. Maybe if she wants to dabble she can try it, but she'd have to get set up.

**Comment by micahgodbolt** [comment]
@betrue-final-final oh yeah! Totally forgot. This might be an interesting exercise to get set up and attempt to make the change herself. but for the sake of efficiency we can take care of it. 

Last big question, can we target the 6.0 release? Or does this work have to be done in 5.x? Doing 5.x will mean twice the work (PRs for both branches).

**Comment by suztocco** [comment]
Sorry have been on a firedrill this week. I’d love to get set up someday though!
When is the 6.0 release?

**Comment by micahgodbolt** [comment]
6,0 was just released this week.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by suztocco** [comment]
Not following the timeline for this then if 6.0 was already released. What are the timing options here?

**Comment by suztocco** [comment]
@micahgodbolt  I am checking with our devs now. We launch to MSIT in a month and go live to consumers in like Sept. So it sounds like it is mainly up to our devs as to when they can upgrade right? So if you make this fix soon we can get it when they upgrade, otherwise you would have to push it to an earlier "branch". Correct?

**Comment by suztocco** [comment]
@micahgodbolt  All good for 6.0! The devs are working on this now. Thanks so much!

**Comment by micahgodbolt** [comment]
Awesome! Thanks for getting that info. Let me take a look at fixing this in the main 6.0 branch. __Should__ be a quick fix.

**Comment by suztocco** [comment]
@micahgodbolt - Just wanted to check in on this. Any movement?

**Comment by micahgodbolt** [comment]
Not yet unfortunately. This bug appears larger than a simple color tweak. We have in our backlog a story to overhaul this component, converting it to CSS in JS. That will be a good opportunity to resolve this theming issue as well.

**Comment by micahgodbolt** [comment]
@jspurlin I looked into Combobox vs Dropdown, and in Dropdown you solved the "one notion of focus" by making onMouseEnter set focus on the hovered item. 

In Combobox we are affecting the "isSelected" item every time we hover an item. That is causing a difference in behavior between the two controls. Is there a reason that we don't just 'set focus' on hover? I'm guessing it has something to do with the fact that 'focus' change via keyboard, also updates the selected value. 

> ContextualMenu/ComboBox/Dropdown: Update so they have one notion of focus (from both hover and keyboard) (#3274)

Also, @joschect it looks like you removed the focused style, and moved it to only focus + hover. Was there intention there of not having focus styles?

> Combobox: Fix styling (#9515)

**Comment by micahgodbolt** [comment]
Here's our current state with no selected styles, only hover/focus. 

![combo](https://user-images.githubusercontent.com/1434956/71685995-cdb34b80-2d4e-11ea-9c25-214b78ea5290.gif)

**Comment by joschect** [comment]
@micahgodbolt I believe that I only removed/changed the `checked` styling. Which I think is different than the `focus` styling. I still see a variety of [focus styling](https://github.com/joschect/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.styles.ts#L121-L138) am I missing something?

**Comment by micahgodbolt** [comment]
Sorry, its the 'checked' value that I was referring to.  It used to have a background color, now it's just

```
 rootChecked: [
        {
          backgroundColor: 'transparent',
          color: option.textSelectedColor,
...
```

**Comment by micahgodbolt** [comment]
@joschect worked on this last night and we think we have a decent solution to make the combobox more aligned with the dropdown.

**Comment by suztocco** [comment]
I no longer work in this area so please loop in a designer as needed who works on fabric.
Thanks
