### ISSUE TITLE
Update the theming documentation for providing fonts, sizing, colors and styling

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#5035]
Problem:

A customer wants to use their own font face, redefine font sizes, adjust colors, tweak sizing. We will do a few work items here:

1. Introduce a `Text` component which respects fonts defined in the theme.
2. Update all components to use the `Text` component.
3. Ensure you can provide contextual theming in all things (finish the css in js conversion.)
4. Update the documentation to document how you override fonts, colors and sizing.

Scenarios that have been asked for:

CommandBar: font size too small
CommandBar: themed background color
Header: dark header rendering components which should be light colored
Fonts: what is the right way to use a custom font (Selawik)

**Comment by allpwrfulroot** [comment]
Any news on this? I see a families -> default field in theme -> typography, but so far I haven't been able to display any custom fonts.

**Comment by cliffkoh** [comment]
I know we started on a Text component (unsure about the super detailed, most up-to-date status) but given that this is a "meta", multi-step feature, assigning this to @micahgodbolt to track the all-up progress.

**Comment by micahgodbolt** [comment]
We're hoping to have a release candidate for the Text component in the coming weeks. As Cliff said, this is a very large, multi-step process, but we're determined to make it happen over the next few months.

Expect the component to be out within a few weeks
Expect components to be converted over to use Text over the next few months (it'll be quite a conversion process)

**Comment by micahgodbolt** [comment]
Blocked waiting for #5295

**Comment by Nimelrian** [comment]
Just wanted to ask about the progress here. Even if I set a custom font family for `ITheme::typography::families::default` I get Segoe UI in some places (e.g. column headers of `DetailsList`). Using Segoe UI is a no go and thus a blocking issue for our app.

**Comment by dzearing** [comment]
@Nimelrian couple of things:

1. The Text component was added, but we're still assessing where and when to use correctly.
2. In the meanwhile, @aneeshack4 will be fixing the components to always pull (and inject) the font from the theme, rather than assuming the consumer will use a `Fabric` component wrapper which defines the font family. Therefore if you provide typography in the theme we'll respect it universally. Tracked in #6528

**Comment by dzearing** [comment]
Targetting the purpose of this tracking issue.
