### ISSUE TITLE
Callout directionalHintForRtl

### ISSUE THREAD

**Issue by amyngu** [microsoft/fluentui#5148]
### Bug Report

- __Package version(s)__: 6.6.0
- __Browser and OS versions__: Chrome, Edge were tested

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)  High

Products/sites affected: (if applicable) All sites using callout with RTL

#### Describe the issue:
Callout is not using directionalHintForRtl correctly, and/or not flipping the directionalHint if its not provided? It is set, but it is not displaying as expected

#### Actual behavior:

![image](https://user-images.githubusercontent.com/31973030/41170059-ba602c28-6aff-11e8-88a4-352dc0256e95.png)
![image](https://user-images.githubusercontent.com/31973030/41170220-3390768e-6b00-11e8-8ea9-57189223c66b.png)

![image](https://user-images.githubusercontent.com/31973030/41170265-629137ca-6b00-11e8-9c01-9fd63cbb54ea.png)

#### Expected behavior:

In RTL the callout should be placed in the opposite of the direcitonalHint given here

**Comment by michaelangotti** [comment]
@joschect IS this expected?

**Comment by joschect** [comment]
The callout should flip, it's in it's positioning logic. That is not expected behavior. I'm having trouble building 6.0 but I can't reproduce this in a slightly older version.

**Comment by amyngu** [comment]
@joschect any luck? Is it possible to get this work done soon?

**Comment by micahgodbolt** [comment]
![image](https://user-images.githubusercontent.com/1434956/45278197-de1c2480-b480-11e8-8fc0-e5c6d3b4efcd.png)
 

Seems to still be an issue.

**Comment by micahgodbolt** [comment]
Just confirming, this is still an issue as of 6.117.2

**Comment by joschect** [comment]
This is an easy fix, but I'm on the fence on it. We do swap alignment edge, so that part is already handled. We just don't handle target edge, I'm guessing because left is left even in RTL. So maybe we should even remove the alignment check? That's what the directionalHintForRTL is for. I'm not sure about this though.

**Comment by micahgodbolt** [comment]
We could add hints that use "start/end" vs "left/right" because I agree. If I say "left" i expect it to be on the left.

**Comment by joschect** [comment]
@micahgodbolt That's what a lot of other positioning packages do, maybe this should be part of a larger positioning refactor?

**Comment by paulgildea** [comment]
@dzearing what's our library principle on mirroring physical properties? Also if we were to change this behavior now it might be a tough breaking change?
