### ISSUE TITLE
Investigate using ContextualMenu for the menus in the dropdown and comboBox components

### ISSUE THREAD

**Issue by jspurlin** [microsoft/fluentui#5206]
### Bug Report

- __Package version(s)__: 6.9.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Low 

Products/sites affected: (if applicable)

#### Describe the issue:
Currently when menu behavior (like keyboarding and focus) is updated ContextualMenu, Dropdown, and ComboBox all must be updated to be consistent... Ideally these should use the same underlying component so that the change only needs to be made in one place

**Comment by dzearing** [comment]
I am going to assign to you, but we can consider closing this if it's covered by other things. Maybe there is some code to share here.

**Comment by Vitalius1** [comment]
In the attempt to merge Dropdown with ComboBox, it would make sense to extract the ITEM from the list of options to a separate subcomponent which then later can be used when in` ContextualMenu` when it's up for a major refactor. During the fluent work done on all 3 components I had to style them separately with 3 different approaches. In some of them to actually style them I had to either add `subComponentStyles` hook or target a global className. When talked to designers, apparently these items in all 3 components should share the same styles in all states (rest/hover/focus/active), so having them as a sharable component with styles and logic in one place would help to exclude inconsistencies and reduce the amount o effort to keep them all in sync.

**Comment by joschect** [comment]
This can be part of the dropdown/combobox refactor found #6030

**Comment by paulgildea** [comment]
We’re currently focusing on improvements to performance and coherence, as you can see in our pinned issue on the repo detailing our v8 plans. So while we don’t plan to address this right now, we will take it into consideration when we schedule future work for DropDown. 

Thank you for reaching out to us.
