### ISSUE TITLE
TagPicker: does not show suggestions using defaultVisibleValue 

### ISSUE THREAD

**Issue by PriyankaPuranik1** [microsoft/fluentui#5219]
### Bug Report

- __Package version(s)__: 5.95.0- 
__Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High
Products/sites affected: Project, CRM grid
#### Describe the issue:
Fix for https://github.com/OfficeDev/office-ui-fabric-react/issues/4725 did not address the main issue. 

Currently we have a control that opens the tagpicker. When user types in text we want the tag picker to open with the typed in text. The Tag Picker control nowgives a way to set default text. But this text is never respected and no suggestions will show up with defaultVisibleValue .

If I set defaultVisibleValue the value appears in the picker but the suggestions open up with no results found. There should be a way to display suggestions using the default visible value?

If I delete 3 and then retype it the code hits onFilterChanged and correctly displays the suggestions but not on initial render.

**Comment by dzearing** [comment]
Codepen here:

https://codepen.io/dzearing/pen/ErWKdK

**Comment by micahgodbolt** [comment]
@PriyankaPuranik1 Do you have any designs that describe how this interaction should work?

**Comment by adhithyar** [comment]
@micahgodbolt I am an engineer in @PriyankaPuranik1's team. A PM from our team will be in touch regarding the behavior we would like.

**Comment by hocull** [comment]
@micahgodbolt - Here's the full spec [https://microsoft.sharepoint.com/:w:/t/ProjectonxRM/EXlxaKrmhtBFl6KHOYLRq4YB0wX_WkdGP5kutN7U65nWcw?e=uypigK](url) 

Basically, when the user clicks, tabs, arrows to the cell so the cell is active, when they start typing we should search on what they type. Right now the first character is being dropped since the first character puts the user into edit mode and then we capture what they've typed. This extra steps in confusing and seems unnecessary. 

I can demo the issue to you if that helps and show you another cell that uses the people picker but has a similar UX that works correctly.

**Comment by micahgodbolt** [comment]
@joschect does this seem like a reasonable ask?

**Comment by vivekbrnl** [comment]
@micahgodbolt 

I am vivek, working for project team(MS). Can you please provide some update on it?

**Comment by micahgodbolt** [comment]
@vivekbrnl, nothing at the moment. @joschect does most of our work on pickers, and he's got a pretty long queue of issues he's already working on.

For clarity, what branch of Fabric are you currently on? This original issue mentioned the 5.x branch which is now N-2 versions old. 

Secondly, is this work that you are interested in contributing? As an open source framework, if this feature is blocking your ability to release, we'd happily assist you in adding it.

**Comment by vibaranw** [comment]
Its vivek, i am writing from my microsoft mail account. 
@micahgodbolt 
we are on 6.150.0 version. I will be happy to contribute. But, I am not familiar with the code. Not sure, where should i make the changes. Could you please help me with that?

**Comment by joschect** [comment]
@vibaranw and @micahgodbolt I think that this is a good ask. I'm not quite sure the right way to go about implementing it though. The picker code is a bit complicated and implementing something like this might be touch a few areas. I'll take a look when I get some time and see if I can provide more guidance.

**Comment by joschect** [comment]
Closing in favor of #12612
