### ISSUE TITLE
MergeStyles: implement atomic classes

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#5403]
Today, when evaluating these rules:

```js
{
  background: 'red',
  color: 'white'
}
```

and:

```js
mergeStyles({
  color: 'white',
  background: 'red'
})
```

Merge styles will generate 2 independent classes, even though they result in the same css. This is because it will not sort the properties before generating a key.

Yet even if it did sort, and both calls generated the same class, all it takes is to add one more property for it to generate a new class name.

What we should consider doing is to follow atomic css conventions found in other packages: 1 property = 1 class name. This should improve key generation time and lookup time. Keys would always only equate to one property name/value pair, and sorting would no longer be required. The number of rules you'd insert would also have a much much higher likelihood of cache hit, increasing logarithmically over the lifetime of the app.

Specifically it means:

```
mergeStyles({ color: 'white', background: 'red' }) // returns classname 'a b'
mergeStyles({ background: 'red', color: 'white' }) // returns classname 'b a'
mergeStyles({ color: 'white' }) // returns classname 'a'
mergeStyles({ background: 'red' }) // returns classname 'b'
```

There are gotchas here in specificity. For example, `:active` elements should always have prescidence over `:hover`, yet due to the nature of css in js and improving cache-ability, the timing of these rules being registered would be unpredictable. We could consider either artificially increasing specificity for certain selectors, or making a plugin system to allow the caller to derive specificity.

Alternatively, switch to another package that supports atomic css already. Ultimately, for large scale applications which contain a large quantity of rules, I think this makes a lot of sense. It also opens up the door for "auto priming" which means we pre-register a number of common rules at load time to preempt insertRules in a batch upfront operation. This priming json could be generated by simply rendering your PLT1 of your app and calling an API to generate the primed result.

**Comment by cliffkoh** [comment]
test

**Comment by JustSlone** [comment]
Closing this out since it will be covered by the new styling approach
