### ISSUE TITLE
New Component: Grid

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#5418]
## Component Details

Proposal: Grid component should abstract css grid.

Required features:
* row/column templates
* gap size
* named cells
* works in ie11

### Code mockup/example

__Code Sample__

```

```

__Types__

| Name      | Type     | Default Value | Description |
|-----------|----------|---------------|-------------|
| className | string   |               | Optional class name to be added to the root |

## Steps

- [ ] Themable (Component.base/Component.styles)
- [ ] Unit tests
- [ ] Visual tests
- [ ] Documentation and examples
- [ ] Keyboard Accessible
- [ ] High Constrast Support
- [ ] RTL Support
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by micahgodbolt** [comment]
I did a few demos in codepen a while ago showing IE11 grid. 
There are some difference between the two that will make supporting a single interface difficult...but certainly doable. 


https://codepen.io/micahgodbolt/pen/OOQaMY

https://codepen.io/micahgodbolt/pen/MOQzpJ

**Comment by micahgodbolt** [comment]
Note that one of the major omissions from ie11 support is that of auto placement of items (i.e. you have to manually place each one). This could be overcome by automtically writing/injecting styles for each item in the gallery. 

In my 2nd example i used sass to loop through and set an nth of type doing the math of where the item would start/stop

```
li:nth-of-type(#{$i + 1}) {
   -ms-grid-row: floor(($i) / 4) * 2 + 1;
   -ms-grid-column: (($i) % 4) * 4 + 2;
   -ms-grid-column-span: 3; 
    background-color: hsl($i * 60, 75%, 75%);
  }
```

**Comment by micahgodbolt** [comment]
For modern browsers, you just need the following

```
.grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
}
```

Abstracting this via the interface will take a little time and thought.

**Comment by micahgodbolt** [comment]
Would be great to support both. columns as a shorthand, and normal templateColumns. 
```
<Grid columns=3 gap=10>   
  <Grid.item span=3 className="Header" />   
  <Grid.item span=2 className="Content" />   
  <Grid.item span=1 className="Sidebar" />   
  <Grid.item span=3 className="Footer" /> 
</Grid>
```

```
<Grid templateColumns="200px 1fr 400px" templateRows="1fr 1fr 300px" gap=10>   
  <Grid.item span=3 className="Header" />   
  <Grid.item span=2 className="Content" />   
  <Grid.item span=1 className="Sidebar" />   
  <Grid.item span=3 className="Footer" /> 
</Grid>
```

**Comment by yuanstanley** [comment]
Hi, just wondering if there's a current ETA on this? @kkjeer @dzearing

**Comment by JustSlone** [comment]
Updating to make this clear it's not on our current roadmap and likely won't be implemented soon
