### ISSUE TITLE
DetailsList onRenderItemColumn

### ISSUE THREAD

**Issue by aslanovsergey** [microsoft/fluentui#5487]
### Bug Report 
 
- __Package version(s)__: (5.83.0)
- __Browser and OS versions__: (Google Chrome Version 67.0.3396.99, Windows 10)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Normal) 
 
Products/sites affected: (some of developing solutions)
 
#### Describe the issue:
 
Event onRenderItemColumn fires on scrolls and on screen size changes

 
#### Expected behavior:
 
I can understand firing event of screen size change but on scrolls, isn't it too performance voracious?
 
### If applicable, please provide a codepen repro:
 
https://codepen.io/aslanovsergey/pen/rrBdeJ

**Comment by dzearing** [comment]
Sounds like a perf improvement opportunity. @ThomasMichon @aditima
