### ISSUE TITLE
Ship Chiclet component

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#5544]
#### Exports
Chiclet/base
ChicletCard/base
OpenGraph

#### Intended Package
OUFR

#### Code mockup/example
```
<Chiclet url="http://localhost:4322" size={ChicletSize.medium} footer={<p>hello</p>} />
```
## Steps
- [X] Initial code in experiments
- [X] Example usage
- [ ] Investigate use cases (integrate) (what about mobile vs pc)
- [ ] Documentation
- [ ] Tests
- [ ] Visual tests
- [ ] Integrated into product scenario
- [ ] Ship plan (what package name, move code to correct package, what meetings need scheduled, dates)
- [ ] Design Review
- [ ] Bump to major release

**Comment by JustSlone** [comment]
closing, no longer relevant
