### ISSUE TITLE
List re-renders all pages on every scroll

### ISSUE THREAD

**Issue by cschleiden** [microsoft/fluentui#5551]
See this gif, the already rendered pages should not be re-rendered when I scroll.. sometimes they are even re-rendered twice:

![details-list](https://user-images.githubusercontent.com/2201819/42688020-fe849fcc-869a-11e8-914d-d55c990958fc.gif)

```ts
import * as React from "react";
import { render } from "react-dom";

import { List } from "office-ui-fabric-react/lib/components/List";

const items: number[] = [];
for (let i = 0; i < 200; ++i) {
  items.push(i);
}

class Row extends React.Component {
  private renderCount = 0;

  render() {
    return (
      <div style={{ height: 20 }}>
        {this.props.item} - Render: {++this.renderCount}
      </div>
    );
  }
}

const App = () => (
  <div>
    <List 
      renderedWindowsAhead={0}
      renderedWindowsBehind={0}
      items={items}
      getPageHeight={() => 200}
      onRenderCell={(item) => (
        <Row key={item} item={item} />
      )}
      />
  </div>
);

render(<App />, document.getElementById("root"));
```

**Comment by dzearing** [comment]
something definitely is borked
https://codepen.io/dzearing/pen/ejpVJQ

**Comment by dzearing** [comment]
@lambertwang I see this added in List:

```
    // Update if the page stops scrolling
    // if (!newState.isScrolling && this.state.isScrolling) {
    //   return true;
    // }
```

This forces a re-render when scrolling stops.

**Comment by stefaniehansen** [comment]
Hi there, are there any updates on this?

**Comment by lambert-wang** [comment]
@dzearing That check was added as part of the ghosting feature added to the List component a while ago. Ghosting refers to letting the user render a lightweight placeholder (the ghost) in place of the actual list contents while the list scrolls. When the user stops scrolling, the ghost should be replaced with the actual list contents. 

Commenting out that section of code does not stop the items from rendering while I'm scrolling, but it does stop a potential re-render when the list stops scrolling.

However, the re-render is required for ghosting to work as the render call is invoked with `isScrolling = false`.
