### ISSUE TITLE
Add Likes/Social component

### ISSUE THREAD

**Issue by mikewheaton** [microsoft/fluentui#5665]
**Describe the feature that you would like added**
The Fabric Toolkit includes a Likes/Social component.

**What component or utility would this be added to**
This might be a new component, or a variant of icon button.

**Have you discussed this feature with our team, and if so, who**
Included in the toolkit that @betrue-final-final is working on.

**Additional context/screenshots**
From the toolkit:
![image](https://user-images.githubusercontent.com/1382445/43154800-79741d92-8f2a-11e8-9b51-a0270a3d3e6d.png)

**Comment by dzearing** [comment]
Some things to consider:

Is it a toggle button that toggles between checked/not checked?

Is there an animation between the two states?

**Comment by Jahnp** [comment]
Popping in to revisit this--there is a design for this in the new Fluent toolkits, and is something we will likely want to look at over the coming months. David has good questions here--there should be an evolved POV on this now that hopefully addresses them.
