### ISSUE TITLE
New Component: CollapsibleSection

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#5736]
## Component Details

CollapsibleSection is meant to be an simple composable component with two rendered areas, a title and a body. The body is collapsible and is simply composed of the children passed into CollapsibleSection.

CollapsibleSection can be used for both simple and complex scenarios. For example, a tree view is simply a composition of nested CollapsibleSections.

Also need to consider:
* Slots/Token support for CollapsibleSection. 
* CollapsibleSectionTitle's `text` prop should probably be changed to `content`.
* Is there a need for CollapsibleSection? Or can it just be a state hook with CollapsibleSectionTitle?
* Revisit having `titleAs` prop or find way to support replacing Title implementation with slots. (See https://codepen.io/jasongore/pen/JxqxrP)
  * Can 'as' be a prop in CSTitle that's accessible from CS to allow this? 
    `<CollapsibleSection title={{ text:'Persona', as: CustomizedCollapsibleSectionTitle}}>`
  * Keep in mind that `as` has typically meant replacing the root element and not the whole component, so perhaps `as` is not the right wording to use in this case.
  * Could CSTitle be a render component instead? `<Slots.title>{ props => ... }</Slots.title>` How would slot props work in this case?

### Intended Package
`@uifabric/experiments`

### Code mockup/example

__Code Sample__

```

```

__Props__

| Name      | Type     | Default Value | Description |
|-----------|----------|---------------|-------------|
| className | string   |               | Optional class name to be added to the root |

## Steps

- [ ] is themable (base/styles)
- [ ] has unit tests
- [ ] has snapshot tests
- [ ] has visual tests
- [ ] has documentation and examples
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by micahgodbolt** [comment]
This component is needed for the Leftnav work we'll be doing in the coming months.

**Comment by micahgodbolt** [comment]
ok ok..not sure if it'd be this OR the accordion that'd be used in the Leftnav, but one of them would be used :D

**Comment by dggsax** [comment]
Hello! Is this being considered for future iterations? It would be really cool to just do:

```javascript
// code to do collapsed logic, probably the useBoolean hook
<Collapsible collapsed={collapsed} onCollapse={onCollapse}>
    <Stack>
        <Text>Howdy</Text>
    </Stack>
</Collapsible>
```

A place where this is done is the [Pickers documentation page](https://developer.microsoft.com/en-us/fluentui#/controls/web/pickers) where it says "See More". If there's no resources to do this in the near-term, perhaps making available the code that does the "See more" functionality".

I'm unsure if the FluentUI design framework was designed with "collapsability" in mind, though (don't quote me on this, this is just a hypothesis), is the intent that what was traditionally in collapsible components be put into `<Panel/>`s? If so, maybe just pointing this out in the [styles](https://developer.microsoft.com/en-us/fluentui#/styles) section of the documentation.

Thank you in advance!
