### ISSUE TITLE
New Component: Accordion

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#5737]
## Component Details

An Accordion is a set of collapsible sections where only one is expanded at a time.

Accordion is meant to serve as an example of how some simple state control can take a simple component like CollapsibleSection and turn it into a higher order component by adding some simple state logic.

### Intended Package
`@uifabric/experiments`

### Code mockup/example

__Code Sample__

```

```

__Props__

| Name      | Type     | Default Value | Description |
|-----------|----------|---------------|-------------|
| className | string   |               | Optional class name to be added to the root |

## Steps

- [ ] is themable (base/styles)
- [ ] has unit tests
- [ ] has snapshot tests
- [ ] has visual tests
- [ ] has documentation and examples
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by micahgodbolt** [comment]
This component is needed for the Leftnav work we'll be doing in the coming months.
