### ISSUE TITLE
Add themed variation to all visual regression tests

### ISSUE THREAD

**Issue by cliffkoh** [microsoft/fluentui#5757]
It is too easy to have bugs/regressions that looks fine on the base variant but fails in themed variant.

This is quite a big work item that requires Design to help validate the baseline - and it might make sense to do this a component at a time, so this issue will need to be split into smaller issues.

**Comment by micahgodbolt** [comment]
Can you provide an example of a component failing in this way? When you say themed variants, do you mean the varients we ship out of the box? Or is this making sure that our styles interface continues to work (styles aren't getting overwritten)?

**Comment by cliffkoh** [comment]
See email in v-team alias please.

**Comment by micahgodbolt** [comment]
Looks like the best thing to do is run a simple inverted theme to catch any assumptions we make about inherited/default backgrounds or text colors. It might not always be pretty, but it should fail in times where the non inverted theme would pass.

**Comment by micahgodbolt** [comment]
Might be blocked at the moment not being able to simply pass a new palette into the theme prop. Checking in on that.

**Comment by KevinTCoughlin** [comment]
This is a good idea 👍

**Comment by cliffkoh** [comment]
@micahgodbolt just pinging this issue cause we chatted about this today.

**Comment by micahgodbolt** [comment]
yup! Looks like it's about time.

**Comment by micahgodbolt** [comment]
@kkjeer any thoughts on how I'd add a theme to your addStory addon? It's not JSX, so I can't just wrap the storyFn in customizer. Can I use a decorator somehow?

**Comment by kkjeer** [comment]
@micahgodbolt I haven't tested this, but could a `loadTheme` call work (similar to the existing `setRTL` calls for RTL stories)?

**Comment by micahgodbolt** [comment]
The fluent customization isn't just a theme, it's a customizer setting.
