### ISSUE TITLE
Refactor: Nav

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#5815]
## Component Details

The current implementation of Nav tracks all of its internal state by mutating props, which leads to inconsistent and unexpected behavior. This means that every time props change, the component loses all of its "state" which leads to issues like #4901. The refactor should also consider other outstanding Nav issues, like #5047, #4575, #5254, #4417 and #733.

Recreate Nav, possibly using CollapsibleSection. Nav should be more simplified, track state internally (NOT in props), and remove unnecessary nesting and complication in its implementation.

### Code mockup/example

__Code Sample__

```

```

__Types__

| Name      | Type     | Default Value | Description |
|-----------|----------|---------------|-------------|
| className | string   |               | Optional class name to be added to the root |

## Steps

- [ ] Themable (Component.base/Component.styles)
- [ ] Unit tests
- [ ] Visual tests
- [ ] Documentation and examples
- [ ] Keyboard Accessible
- [ ] High Constrast Support
- [ ] RTL Support
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by khmakoto** [comment]
Closing since we are not likely going to invest in the current implementation of `Nav` going forward.
