### ISSUE TITLE
For DetailList grid, Narrator does not mention about sorting option available at all column headers

### ISSUE THREAD

**Issue by chakradhar2** [microsoft/fluentui#6011]
For DetailList grid, Narrator does not mention about sorting option available at column headers.
 
Expected : 
 The narrator should able to read like: "CoumnName Column header, sort button, press Enter to sort the records".

**Comment by dzearing** [comment]
@chakradhar2 If you can help dig into exactly which attribute you need, we can help find a way to get that attribute there. But yes @ThomasMichon would know best here, or @cschlechty.
