### ISSUE TITLE
Layer: Contaminated context for Layers at same React hierarchy level

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#6029]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/jasongore/pen/XPbjRJ

### Bug Report 
 
 
- __Package version(s)__: 6.52.0
- __Browser and OS versions__: n/a
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
This [CodePen](https://codepen.io/jasongore/pen/XPbjRJ) shows how `Dialogs` (which use `Layers`) have contaminated context between `Dialogs` sharing the same React component parent. It appears the last context customized (in this case, `Customizer` using the inverted theme) contaminates and affects all other `Dialogs` at the same level, which can be seen by opening the dialogs.

This seems to be resolved in the second part of the CodePen simply by interjecting one layer of React components to the hierarchy.

This issue seems to be orthogonal to #6055 as it occurs before and after #5701. I suspect that this particular issue is an issue with `Layer` and how it interfaces with its parent root.

#### Actual behavior:

Context for `Layers` at the same level are contaminated by the last `Layer` at that level.
 
#### Expected behavior:
 
`Customizers` and changes to context should not affect other `Layers` outside of the `Customizer` hierarchy. Behavior should be like that of the second part of the CodePen.

**Comment by JasonGore** [comment]
Consider it only affects Layers at the same level of hierarchy, I would say normal priority but I wouldn't mind David's confirmation.

**Comment by pmsandhu** [comment]
I don't think this is an issue with the customizer but with the layer component itself. As you can see from the following pen all layers within the same parent are all rendered at once with the last child layer being painted on top of the other children. 
https://codepen.io/pmsandhu/pen/oPxzgO?editors=0110

**Comment by JasonGore** [comment]
Yeah, I've seen the same behavior myself and makes me think it's related to Layer parent management. I'm curious where you saw the implication that this is a Customizer issue?

**Comment by pmsandhu** [comment]
In your code pen you wrote `It appears that whatever context is used via Customizer for the last Layered component will affect ALL Layered elements sharing the same React component parent` as well as in the "Expected Behavior" section of this issue.

**Comment by JasonGore** [comment]
`I suspect that this particular issue is an issue with Layer and how it interfaces with its parent root.`

**Comment by JustSlone** [comment]
Cleaning up older issues, if this is still an important issue please feel free to reopen
