### ISSUE TITLE
Remove CSS styling from examples

### ISSUE THREAD

**Issue by kkjeer** [microsoft/fluentui#6075]
**Describe the feature that you would like added**

Clean up the Fabric examples so that they use JS styling instead of CSS styling.

**What component or utility would this be added to**

Examples

**Have you discussed this feature with our team, and if so, who**

@micahgodbolt 

**Additional context/screenshots**

Users are having trouble modifying the examples to fit their own codebase when the examples use CSS styling, e.g. in #6072

**Comment by cliffkoh** [comment]
This is going to be huge and probably requires splitting up the work across the team...

**Comment by micahgodbolt** [comment]
yeah, this is certainly more of a meta issue. lets be sure to update as we make changes.

**Comment by ecraig12345** [comment]
Reopening since this isn't fully fixed

**Comment by JustSlone** [comment]
Closing this out as it's very old, mostly done, and examples will likely be updated soon anyway
