### ISSUE TITLE
Add useTargetAsMinWidth and useTargetWidth properties to Callout

### ISSUE THREAD

**Issue by redoz** [microsoft/fluentui#6111]
**Describe the feature that you would like added**
As the callout takes a target, it would be nice if it also had the `useTargetAsMinWidth` and `useTargetWidth` properties like the `ContextualMenu` already does.

**What component or utility would this be added to**
Callout

**Have you discussed this feature with our team, and if so, who**
No

**Comment by redoz** [comment]
Will you take a PR for this? Looks like it shouldn't be too hard to push the code from `ContextualMenu` into `Callout`?

**Comment by micahgodbolt** [comment]
hey, sorry for late reply, but that'd be a nice addition for sure. In fact, contextualMenu is based on callout, so moving that functionality to callout might allow us to remove it from contextual menu.
