### ISSUE TITLE
Add option to ScrollablePane to only show one sticky item.

### ISSUE THREAD

**Issue by redoz** [microsoft/fluentui#6207]
**Describe the feature that you would like added**
I'm trying to use the `ScrollablePane` to implement a grouped list, and as you scroll I'd like to the last group header to be `Sticky` but currently all sticky items pile up in a large stack.

**What component or utility would this be added to**
`ScrollablePane`  and/or `Sticky` 

**Have you discussed this feature with our team, and if so, who**
No.

**Additional context/screenshots**
Current behavior:
![image](https://user-images.githubusercontent.com/1670030/45020326-f3332680-b02e-11e8-8063-b6726ad45c8c.png)

Wanted behavior:
![image](https://user-images.githubusercontent.com/1670030/45020450-50c77300-b02f-11e8-90ab-504e56fd8963.png)

**Comment by redoz** [comment]
Thinking about this some more, perhaps it's best to add two new properties: `maxFooterStickyCount? : number` and `maxHeaderStickyCount? : number`.

These could then indicate the maximum number of stickies that are rendered in the footer and header respectively.

**Comment by redoz** [comment]
I've poked around the component a little and the code looks fairly complicated, but if you're accepting a PR for this I can take a stab at it.

**Comment by micahgodbolt** [comment]
One idea here would be to simply have several sticky items stacked on top of each other.
