### ISSUE TITLE
People Picker - Support copy/paste and multi-select

### ISSUE THREAD

**Issue by maddyt** [microsoft/fluentui#6280]
**Describe the feature that you would like added**
People Picker needs to support performing copy/paste operation so that email address copied from the To: line in Outlook Web Access and actually be pasted into the People Picker control.
**What component or utility would this be added to**
People Picker
**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**

**Comment by JustSlone** [comment]
I personally would love to see this, unfortunately this is not on our roadmap right now
