### ISSUE TITLE
Remove TSlint overrides in OUFR

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#6310]
Wanted to get these on the backlog. Can be done as a single issue or broken up into multiple	

- [x] "deprecation": false, (#12045)
- [ ] "jsx-ban-props": false,
- [x] "max-line-length": [false, 140],
- [ ] "no-any": false,
- [ ] "typedef": [false]

**Comment by micahgodbolt** [comment]
you'll probably run into a lot of errors upon turning each one of these off. probably safest to do 1 at a time along with any fixes needed to support that change.

**Comment by cliffkoh** [comment]
@micahgodbolt I think enabling IE 11 screener tests is far more bang for buck than some of these tslint rules. `deprecation` is a good one though.

**Comment by cliffkoh** [comment]
Also, is this really a good first issue?

**Comment by micahgodbolt** [comment]
that's what david suggested. It's a 'turn off the exception' and fix what breaks. Rise repeat.

**Comment by cliffkoh** [comment]
Fixing the breaks may be far from trivial though... But if Eddie is working on this already, we'll see how far he gets. I still think enabling IE 11 screener is much more valuable.

**Comment by leddie24** [comment]
Do we actually want to remove `jsx-ban-props`?  It complains about the 

> Use of the prop 'style' is not allowed. Use className and provide css rules instead of using inline styles.

  Don't we want to use inline styles for some components and utilities (e.g `withViewport`)?

**Comment by micahgodbolt** [comment]
hey @khmakoto, is this work still on your radar?

**Comment by khmakoto** [comment]
I have one more change regarding the deprecation flag. Would have to talk with David to see if I will take on the work of other overrides or not.

**Comment by khmakoto** [comment]
Not applicable anymore since we use eslint and not tslint now. Closing.
