### ISSUE TITLE
BasePicker should do own browser detection for enableSelectedSuggestionAlert prop

### ISSUE THREAD

**Issue by BrendanMcK** [microsoft/fluentui#6431]
### Bug Report 
 
 
- __Package version(s)__: 6.49.2
- __Browser and OS versions__: n/a
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Maybe
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable) n/a
 
#### Describe the issue:
 
A colleague (hi @richardtagger) noticed that BasePicker has a `enableSelectedSuggestionAlert` prop that may need to be set when using IE11 for accessibility compat reasons. From the [docs](https://developer.microsoft.com/en-us/fabric#/components/pickers):

> Adds an additional alert for the currently selected suggestion. This prop should be set to true for IE11 and below, as it enables proper screen reader behavior for each suggestion (since aria-activedescendant does not work with IE11). It should not be set for modern browsers (Edge, Chrome).

IMO any browser detection and compat work should be handled by Fabric itself - it shouldn't be necessary for the user of a Fabric control to notice this fine-print item in the first place, and then do additional work to get the accessibility working correctly.

Can (a) verify if this is still needed, and if so, (b) have Fabric Do The Right Thing Automatically here?

**Comment by micahgodbolt** [comment]
@joschect do you have any background on this prop in the picker?

**Comment by micahgodbolt** [comment]
in light of edge's announcement, i'm curious if this is going to be an issue. will we be able to sunset IE11 much sooner now that an evergreen edge will be available all the way back to Win 7?

**Comment by joschect** [comment]
@micahgodbolt Correct me if I'm wrong but I don't think we do browser detection anywhere else in fabric? I don't think we should add it if we can help it.

**Comment by micahgodbolt** [comment]
Yeah, regardless of the future of IE11, I think it's safe to say that browser detection is best left up to individual applications. Adding it now would probably cause more issues than it would solve.

**Comment by dzearing** [comment]
Ping @joschect 

IE11 detection is quite simple... like 1 line of code that we can stick in browser.ts or something in utilities if it's not already there.

 https://stackoverflow.com/questions/21825157/internet-explorer-11-detection

I agree that we should not expect end users to be hyper aware of super subtle details like this...

**Comment by dzearing** [comment]
@micahgodbolt I don't suspect IE11 dying for at least a year and a half, maybe 2.

I also really disagree here. In the rare cases where our code needs to fork for ie11, we should not ask authors to go out of their way to look the stackoverflow article up and do that...

If we can't find a solution that works in every browser, doing the detection for the user would be the next best... but asking them to do it and pass in true feels really gross. It just won't be consistently implemented.

**Comment by micahgodbolt** [comment]
Yeah, that IE11 detection seems pretty straight forward. I was assuming it'd be quite a bit more complex. In that case, should this even be a prop? Shouldn't the control just make the necessary adjustments for IE11?

**Comment by joschect** [comment]
@dzearing Sure, that makes sense. I think you're probably right that it's okay to do a little detection. I'm still against it overall but I think you make good points.

**Comment by dzearing** [comment]
Removing needs attention flag; if you could fix the prop when you get a cycle, that'd be great. Alternatively @BrendanMcK if you'd like to take a stab sooner than @joschect can, let us know. I think it would be correct to avoid burdening the consumer if we really need to differentiate on ie11.

**Comment by paulgildea** [comment]
@joschect @dzearing Is this still and issue or are we considering changing the behavior here?
