### ISSUE TITLE
Dropdown: Should narrow down/navigate to option on keyboard entry

### ISSUE THREAD

**Issue by jaduong** [microsoft/fluentui#6565]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/XxKWWE
(always repros) 

### Bug Report 
 
 
- __Package version(s)__: 15.6.1
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) 
 
Requested priority: (Blocking, High, Normal, Low) Normal-High
 
Products/sites affected: (if applicable) Project Roadmap
 
#### Describe the issue:
 
Expect that the dropdown will help select the appropriate item for the user when typing a character. 

#### Actual behavior:
 
Type "P" in a dropdown, nothing happens.
 
#### Expected behavior:
 

Type "P" in a dropdown, navigates to item in list that starts with "P".

**Comment by Vitalius1** [comment]
@jaduong I believe we don't have this behavior in the dropdown but we do support this in our ComboBox component. https://codepen.io/vitalius1/pen/LgZVJB here is a quick demo of ComboBox with `allowFreeform={true}` and `autoComplete="on"` props doing exactly what you expect.
Let us know if this is what you were looking. Plus there are plenty of other examples [here](https://developer.microsoft.com/en-us/fabric#/components/ComboBox).

@micahgodbolt feels like ComboBox is an improved version of Dropdown. Are we having any plans and solidifying this two under one control?

**Comment by micahgodbolt** [comment]
We certainly have a desire to consolidate to a single component. It won't be a small feat though, so I'm not sure of the timeframe. 

https://github.com/OfficeDev/office-ui-fabric-react/issues/6030

**Comment by micahgodbolt** [comment]
I've added this request to #6030. We'll investigate if we're able to add it.

**Comment by Geeta-Capsitech** [comment]
combobox is not able to  set value using onchange event
