### ISSUE TITLE
Theming: language should be provided by the theme

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#6607]
There are cases where the font is dependent on language, and that the page itself may render more than one language at a time. For example, you may use an email client in English, but you read a mail written in Hebrew, which would need a different font rendered.

Recommendation:
Font families are currently providable via theme. However, the fontface definitions are only registered on load.

1. We should at a minimum provide an idempotent way of ensuring fontfaces, given a language, are registered. 
2. We should provide clear documentation on loading fontfaces on demand, or ensure that it happens automatically.
3. There should be examples of loading multiple languages on the page.

This also is tightly coupled with the FabricConfig.baseUrl setting which I believe controls the base location of the fonts for custom cdn solutions. This detail should also be documented.

**Comment by xugao** [comment]
Closing as dup of #15155
