### ISSUE TITLE
Standardize documentation comment formatting (including grammar and backtick usage)

### ISSUE THREAD

**Issue by kkjeer** [microsoft/fluentui#6651]
**Describe the feature that you would like added**

Currently, there are inconsistencies with backtick usage (some property names are rendered with backticks and some are not). It would be good to clarify what pieces of documentation should use backticks.

**What component or utility would this be added to**

All component docs

**Have you discussed this feature with our team, and if so, who**

@cliffkoh 

**Additional context/screenshots**

**Comment by micahgodbolt** [comment]
@kkjeer do you have specific examples for reference?

**Comment by kkjeer** [comment]
In the Pivot documentation, initialSelectedKey does not use backticks:
The index of the pivot item initially selected. It only works when initialSelectedKey is not defined. You must not use them together.

In the Dropdown documentation, dropdownItems does use backticks:
Refers to the element that wraps `dropdownItems`.

**Comment by micahgodbolt** [comment]
example 
![image](https://user-images.githubusercontent.com/1434956/50600203-38445980-0e65-11e9-8ccd-21df13668f09.png)

**Comment by dzearing** [comment]
Is there a programmatic way to scan and resolve this? We have the api-extractor json...

**Comment by dzearing** [comment]
It would be great to just have a big table of all props and comments, alphabetized, so that we could also scan for inconsistencies.

**Comment by dzearing** [comment]
Curious how @natalieethell work will impact the comments. For example, we might have Slider component which references `onChange` from the `value` prop comment. 

Would we would need to manually modify this comment in any way, or would the doc tooling somehow detect that "onChange" refers to `ISliderProps.onChange`?

I suspect we will have a lot of manual scrubbing to do here in any case, and that Natalie's work won't solve this.

**Comment by dzearing** [comment]
Suggested work here:

I think backticks are just one of many inconsistencies. Could we get a table of all props, next to each other?

Then schedule a meeting with a few devs to divide and conquer the table.

Then check in.
