### ISSUE TITLE
Scrub and Cleanup API surface of OUFR

### ISSUE THREAD

**Issue by cliffkoh** [microsoft/fluentui#6776]
For some reason, "variables" like "mru" from the PeoplePicker example are making it into the API Surface. This goes against Fabric convention.

Yet we are unable to fix this right now without breaking semver. 

We should scrub and cleanup the API surface as part of V7.

**Comment by jeremy-coleman** [comment]
Please do. You should also look at your lib-commonjs folder, its importing from the lib folder causing duplication and runtime errors. i have to manually delete the lib commonjs folder and manually change main in the pkgjson When using any bundler other than webpack. You also are importing unresolved scss in several components

Imo you should delete all the junk in the core lib and put an actual copy of merge styles , icons, utils, and styling in the fabric folder to fix other neated dependency issues. U guys are using pnpm so u may not see the issues. Fyi by combining the libs and deleting junk i got the prod build down to 400kb from 1mb
