### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#6780]
## Website

| Status | Action | Rationale | Issue |
|--------|--------|------------|-------|
| <ul><li>- [X] </li></ul> | Re-do Implementation section | Make use of api-extractor and TSDoc to improve documentation generation, and include hyperlinks. |#7819, #7309, #6010 |
| <ul><li>- [ ] </li></ul> | Look into docs.microsoft.com capabilities | Consider moving some documentation to here. ||
| <ul><li>- [ ] </li></ul> | Standardize back tick usage | We should be consistent here. | #6651 |
| <ul><li>- [ ] </li></ul> | Document theming | We need documentation for properties like `defaultFontStyle`, for example. | #7416, #7417 |
| <ul><li>- [ ] </li></ul> | Document utilities | Documentation will help make developers aware of existing utility functions so that they are not re-written | |
| <ul><li>- [ ] </li></ul> | Document prior versions of OUFR | We should be able to easily see older versions' APIs | |

## Wiki

| Action | Rationale | Issue |
|--------|------------|-------|
| Link wiki to external wiki repo | Moving our wiki to an external repo and syncing it back here gives us the ability to create PRs for our wiki|#7183 |
| Re-vamp ExampleCard component | We want this to be more interactive, and use a more relevant control | |
|Clean up Wiki Navigation| Duplicate/similar pages, dead ends etc|#7182|

**Comment by natalieethell** [comment]
Updated the issue above to include standardizing back tick usage, documenting theming, documenting utilities, and documenting prior versions of office-ui-fabric-react.

**Comment by natalieethell** [comment]
Updated the description to include a link to an issue that highlights the importance of documenting inheritance (#7819)

**Comment by natalieethell** [comment]
Added #7309 and #6010 to the table above

**Comment by JustSlone** [comment]
Closing out old issues. 
If this is still a need, reopen, or file an updated issue. Thanks!
