### ISSUE TITLE
☂TextField: Issues to consider in converged approach

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#6827]
## Component Details

The current implementation of `TextField` is complex with the mixing of controlled vs. uncontrolled state logic  as well as the state logic's mixture with view output. In addition, `TextField` has had multiple issues with controlled vs. uncontrolled behavior such as #1350 and #5518, some of which is still present. And fixing issues like #1350 will be perceived as a "breaking" change, even though this it is how a controlled component should operate.

All of these characteristics make `TextField` a good candidate for Foundation conversion. I believe that separating out state and view logic as well as creating a refactored component will make it easier to introduce a component that many will perceive as "breaking".

### Code mockup/example

__Code Sample__

```

```

__Types__

| Name      | Type     | Default Value | Description |
|-----------|----------|---------------|-------------|
| className | string   |               | Optional class name to be added to the root |

## Steps

- [ ] Themable (Component.base/Component.styles)
- [ ] Unit tests
- [ ] Visual tests
- [ ] Documentation and examples
- [ ] Keyboard Accessible
- [ ] High Constrast Support
- [ ] RTL Support
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by dzearing** [comment]
Just drawing attention to #4440 here; it would be ideal to have an Input that's simple and has no validation logic. Then layer on that something like a StatusInput, which can render optional "status" below the input based on callback criteria. It was called out in the bug that not all status is "error" and that we should consider warning/success styling as well. But let's discuss the right solution for that.

**Comment by micahgodbolt** [comment]
another opportunity here is to make textfield the goto field to build all other picking controls off of. date picker, people picker, dropdown, comobobox etc

**Comment by JustSlone** [comment]
Repurposed this issue to track ideas and other issues we should consider with textfield refresh/convergence

**Comment by ecraig12345** [comment]
Closing in favor of #16549
