### ISSUE TITLE
CommandBar: Root style section not applied to root component

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#6838]
### Please provide a reproduction of the bug in a codepen:
 
This [CodePen](https://codepen.io/jasongore/pen/ePQVoE) highlights the application of className prop and `root` section at different levels, highlighted in the image below.

![cb](https://user-images.githubusercontent.com/26070760/47458926-b44c6200-d78f-11e8-854e-2ed1a0abe138.png)

### Bug Report 
 
 
- __Package version(s)__: 6.92.0
- __Browser and OS versions__: n/a
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Normal)
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
While implementing the resolution for #6828, I discovered that the `root` style is not actually applied to the root component, but 3 levels down. 

In investigating a fix for this issue, I encountered the following:

- Just moving the `root` section's styling will break the layout of `CommandBar`, requiring a new style section at `root`'s current level with default `root` styling (padding, flex, etc.) to resolve.
- The fix will be a style API breaking change as consumers using `root` styling may now need to use the new style section to avoid layout regression.

#### Actual behavior:
 
`root` style is not applied to root component.
 
#### Expected behavior:
 
`root` style is applied to root component.

**Comment by ericame** [comment]
Could this change be the cause of why I see my .toolbar and .identity classes no longer working properly in this pen: https://codepen.io/anon/pen/VqBPwJ?editors=0110? This is after I upgraded from 6.90.0 to 6.121.0.

I have worked around the issue, but I'm curious what the correct way to adjust the height and background color would be.

**Comment by micahgodbolt** [comment]
all of the styles are on root, so height, bg color etc would be applied there. The only thing you'd put on the outermost wrapper would be layout styles, though I wouldn't recommend changing display to anything other than block due to the way that resize group works.

**Comment by ericame** [comment]
I think I'm a little confused. When you say you would apply the styles to the root, does that meant there's a property to do so or I would just use the root class name?

**Comment by micahgodbolt** [comment]
`<CommandBar styles={{root: {height: 20}}} />`

**Comment by micahgodbolt** [comment]
Without a breaking change, the easiest solution is to either wrap the command bar in a div, or simply pass styles through via style prop. This works fine. 

![image](https://user-images.githubusercontent.com/1434956/71690065-7c0fbe80-2d58-11ea-99fc-ace974c35088.png)

![image](https://user-images.githubusercontent.com/1434956/71690071-80d47280-2d58-11ea-8b22-41ccebbf5026.png)
