### ISSUE TITLE
Type Safety: `defaultProps` and Non-null Assertion Operator Usage

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#6905]
#### Describe the issue:

DefinitelyTyped does not recognize `defaultProps` as ensuring that optional properties have guaranteed values. As a result, Fabric developers have to use the non-null assertion operator (e.g. the `!` in `step!.toString()` on these properties. The concern is that the use of the non-null assertion operator creates a fragile binding and potentially insidious source of bugs if somebody purposely or accidentally removes a prop value from `defaultProps`.

For example, in `Slider.base.tsx`, there are [multiple usages of the `step` prop as `step!`](https://github.com/OfficeDev/office-ui-fabric-react/blob/8735ebd4196ed804c115b2a6e8b4145b7991735e/packages/office-ui-fabric-react/src/components/Slider/Slider.base.tsx#L165) including dereferencing that may lead to issues if `step` is ever removed from `defaultProps`.

[This DefinitelyTyped issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11640) highlights this problem with some potential workarounds.

This should also probably be handled by the create-component script, createComponent, styled and / or component creation document standards.

This issue blurs the lines between bug and feature request, but I certainly think it has the potential of preventing exceptional bugs through typing improvements.

### Environment Information 
 
 
- __Package version(s)__: 6.96.0
- __Browser and OS versions__: n/a

**Comment by JasonGore** [comment]
It looks like TypeScript 3.0 will allow us to resolve this issue: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#support-for-defaultprops-in-jsx

**Comment by jdhuntington** [comment]
Removing the _fabric 7_ label; still desirable, but not a ship blocker for 7.
