### ISSUE TITLE
Theming: Terminology

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#6980]
This issue defines theming terminology to reduce ambiguity and encourage consistency. Terms should conform to widely accepted existng terms as much as possible, such as [style guide resources](http://styleguides.io./).

| Term | Definition | Comment |
|-------|------------|------------|
| Component | Atomic element with self-contained styling, theming, state and view associated with and required to instantiate component. | |
| Scheme | A variant of a theme with contrasting colors, such as `strong`, `soft` and `neutral`. | Need to clearly delineate schemes from themes. Are schemes always relative to their context? | 
| Slot | A subcomponent that is exposed via a component's props. |
| Styles | An object or function that defines styling for specific areas of a component. | |
| Styles Section | An area of a component that can have specific styling applied to it. Related to slots in that every slot is a styles section. |
| Tokens | Component props that affect component styling in one or more ways. | |
| Theme | A definition affecting the following component styling characteristics: colors, typography, spacing. |  |

**Comment by micahgodbolt** [comment]
Component Variable has always felt super verbose to me. Is there an opportunity for discussion on this term? Or is that used to align with stardust?

I have always used the term "token" for these types of data. Lightning Design System has used this term for a while. Sometimes tokens are global (similar to our palette/semantic colors) and sometimes they are per component.

**Comment by JasonGore** [comment]
A lot of these definitions will depend on the outcome of #7005 so I expect this list (or at least the definitions) to change. If "Component Variables" end up just being theming and styling for Fabric, I'll make sure to tighten up the definitions for clarity. Stardust is also making use of popularized terms from multiple systems so I think we should converge as much as possible, assuming the terms are in wide use. (There's a link to style guide resources in the description.)

**Comment by dzearing** [comment]
Housekeeping, closing as much of this has since changed.
