### ISSUE TITLE
Link: No longer inherits font size

### ISSUE THREAD

**Issue by jordandrako** [microsoft/fluentui#6984]
### Environment Information 
 
 
- __Package version(s)__: 6.99.0

### Please provide a reproduction of the bug in a codepen:
 

https://codepen.io/anon/pen/EOjWZr
 
#### Actual behavior:
 
```
root: [
  classNames: root,
  theme.fonts.medium, // This explicitly sets the font size, defaulting to 14px.
...
```
Nesting a `<Link href="#">` in anything with a set font-size, it doesn't inherit the size anymore.

#### Expected behavior:
 
`<p style='font-size: 18px'>This is a <Link href='#'>link.</Link></p>`
The link should be 18px like the surrounding paragraph.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: (Blocking, High, Normal, Low) High
 
Products/sites affected: HIG fabric site.

**Comment by micahgodbolt** [comment]
Here's the change

https://github.com/OfficeDev/office-ui-fabric-react/pull/6647/files#diff-88bab38679ea4055cedab0711613d137R17

It was in moving the font styles from the fabric component down onto the controls.

**Comment by jordandrako** [comment]
My idea is to add a `inherit` option to the theme.fonts object that sets the size and weight to inherit instead.

**Comment by micahgodbolt** [comment]
to really resolve this, we need to have the default behavior be the original inheriting behavior.

**Comment by micahgodbolt** [comment]
The Fabric component still has the font size in it, so removing this font size shouldn't cause any regression if used inside of Fabric component.
