### ISSUE TITLE
Theming: High Level Features

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#6989]
| HLF | Rationale | Related Issues | 
|------|-----------|-------|
| Icon theming | How do icons need to evolve? Will icons be part of theming? Can icons be defined contextually as needed? (there is a current need for this) Should this even be supported contextually or rather be supported through component props? Font, SVG, and other format support.
| Platform inheritance | Support inheriting theme from underlying platform where applicable. Detect and propagate change when platform theme changes. |
| Styling provider agnostic | Eliminate static dependencies on an underlying styling implementation. |
| Schemes | Support named variants of themes. | #5979 |
| Component Foundation | Support method for creating components that handles boilerplate aspects of theming and styling. | #5721 |

**Comment by danmarshall** [comment]
Hello, not sure if this is the right place to ask for a feature, but I'd like to be able to support changing the theme at runtime, to support both a Light and a Dark theme.

**Comment by JasonGore** [comment]
@danmarshall We currently support this via `Customizer`. You can do something like:

```tsx
let activeTheme = someVariable ? lightTheme : darkTheme;
<Customizer theme={...activeTheme>
  ... your JSX
</Customizer>
```

You can even nest `Customizer`. This assumes your components are built using the `styled` helper. The `styled` helper automatically grabs the theme as loaded by either `loadTheme` and/or `Customizer` (with the closest parent `Customizer` having higher priority.)

There's an recent demo we created showing this behavior as well: https://microsoft.github.io/frontend-bootcamp/step2-03/demo/

**Comment by danmarshall** [comment]
@JasonGore - thanks! I am able to use loadTheme successfully. My question is can I call it again later to change the theme afterwards. I'll experiment with calling loadTheme a second time.

**Comment by JustSlone** [comment]
These concerns and work are covered by the ongoing styling and theming work. Closing out 

CC: @xugao who is working on Theming
