### ISSUE TITLE
Theming: Storage and Perf

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#7003]
Current implementations of Customizer and Theme Provider reconstruct settings on every render pass, even if theme data and scheme do not change. This issue explores how perf can be optimized given an approach on theme access and storage.

* Should contextual theme data be stored in context or global store?
* ShouldCustomizer / TP memoize locally to optimize perf instead of referring to global store? 
    * https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#what-about-memoization
* Reconcile named theme approach with storage implications. Are named themes actually schemes or totally separate themes with their own schemes? What is their scope?
* Can Customizer/ThemeProvider be optimized not to trigger on global change if it's inside another Customizer/TP in a non-hacky way?
  * Could context propagation be blocked? Do changes to context bypass shouldComponentUpdate filters?
* Theme Merging: Do we support partial themes and merge with parent? (Current implementations of Customzier and Theme Provider do not.)
* mergeStyles is having a roughly 10% impact (quantify this more) on existing components such as DetailsList.

Related issues: #4575

**Comment by JustSlone** [comment]
Closing this as it's no longer relevant, if I'm wrong feel free to re-open with more information!
