### ISSUE TITLE
[tslint rule] Add a rule to prevent the use of inline loader syntax in require or imports

### ISSUE THREAD

**Issue by kenotron** [microsoft/fluentui#7018]
**Describe the feature that you would like added**
Recently, we had some `require()`'s that were checked in with an inline loader syntax. This unnecessarily tied the library consumers to a specific bundler and specific loaders for the file type.

**What component or utility would this be added to**
rule should be run across all packages

**Comment by kenotron** [comment]
@brandonthomas suggested offline to look at something like this: https://palantir.github.io/tslint/rules/no-implicit-dependencies/

**Comment by brandonthomas** [comment]
Might not actually work as things like css are typically not declared in package.jso

**Comment by brandonthomas** [comment]
@kenotron have you looked at this anymore? I just realized there's a src option in their example now. Maybe it will work for this?

**Comment by brandonthomas** [comment]
Any update on those @kenotron or @khmakoto? Is this even an issue anymore?
