### ISSUE TITLE
[DevExp] Add declaration mapping so that F12 navigation from one pkg to another goes to the src

### ISSUE THREAD

**Issue by kenotron** [microsoft/fluentui#7030]
**Describe the feature that you would like added**
Currently in VS Code, because we only do `declaration: true`, navigating code from one src file to another goes to the declaration even though we're all in a single monorepo. We should generate declaration map to navigation from src to src.

**Comment by kenotron** [comment]
Shoot, we don't minbar TS2.9: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html

We cannot do this until Fabric 7.0.

**Comment by cliffkoh** [comment]
@micahgodbolt  @kenotron should this be added to some 7.0 milestone?

**Comment by micahgodbolt** [comment]
if it's a 2.9 minbar, I think 7.0 is definitely appropriate.
