### ISSUE TITLE
SearchBox sometimes requires double clicking in IE for focus

### ISSUE THREAD

**Issue by dliu120** [microsoft/fluentui#7035]
This one is easy to reproduce. 

1) Open https://developer.microsoft.com/en-us/fabric#/components/searchbox
in IE.
2) In the *Searchbox with no animation*: Click between the icon and the placeholder text on the Searchox.
3) Observe that the icon disappears, the placeholder stays, but no focus is received. This behavior can sometimes be replicated in other search box, but consistently repros in the searchBox without animations in IE11

**Comment by kkjeer** [comment]
Reopening since #7319 was reverted in order to fix #7291. This issue will likely require a larger refactor.

**Comment by ecraig12345** [comment]
Closing since this is specific to IE 11 (which is nearing end of support), only repros if the user happens to click in a very specific place, and is easy to recover from (click elsewhere in the box).
