### ISSUE TITLE
DatePicker is not DST safe

### ISSUE THREAD

**Issue by abettadapur** [microsoft/fluentui#7046]
### Bug Report

- __Package version(s)__: Latest

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal
#### Describe the issue:
DatePicker can return unexpected results over DST boundaries

1. Set Timezone to Brasilia (-3UTC)
2. Navigate calendar to the month of November 2018
3. Select November 6th

#### Actual behavior:

Returned date is of the form 11/6/18 01:00:00 -2

#### Expected behavior:

Returned date is of the form 11/6/18 00:00:00 -2

### If applicable, please provide a codepen repro:
https://codepen.io/anon/pen/jQqvMb

**Comment by kenotron** [comment]
This is actually due to a flaw in JS date math itself depending on the system's timezone info. There are precedence here:
https://github.com/moment/moment/issues/2353

Unless we implement our own timezone aware date math, we will not be able to get around this. It seems out of scope in a quick fix, I'm going to put this in the backlog and assign to @lorejoh12 & @fpintos to give some input.

**Comment by j-te** [comment]
The solution for the developers is really ensuring that the API or content-type interprets the JS date format correctly **with** the timezone information. 

For example it's a common mistake to use SQL type `datetime` if the input has timezone information. The DB would discard the timezone information for this type thus offsetting incorrectly when **reading** the entry again. What you want to use is `datetimeoffset` which stores timezone information. 

If the documentation could be updated to educate/give guidance for operating on JS Dates then it will help prevent errors and requests for new features (maybe). I would encourage anyone to avoid manipulating the date object value where possible (do you really need to).
