### ISSUE TITLE
Allow Surfaces to be attached to any dom element

### ISSUE THREAD

**Issue by rexkenley** [microsoft/fluentui#7056]
Similar to react-modal's parentSelector property, it would great if surfaces have this feature. Especially in Crm365 webresource development where we want to display dialogs but are currently limited to the frame where the webresource resides.  The dialogs should be rendered on the main Crm365 form window, thus graying out the entire form in the backgroud.

http://reactcommunity.org/react-modal/#custom-parent

Thanks!

**Comment by rexkenley** [comment]
This is what my webresource current looks like (it is a full html doc inside a frame)
![image](https://user-images.githubusercontent.com/10548251/48280285-2cb65280-e421-11e8-9ca9-64e12eaa6fe6.png)

I want it to look like this (within the Crm form). So the Dialog box would be "outside" the frame.
![image](https://user-images.githubusercontent.com/10548251/48280456-a5b5aa00-e421-11e8-9144-fcdb6405ed7e.png)

**Comment by rexkenley** [comment]
Kenotron,

What is the proper way to link the fabric css on a page? I was thinking that if I could do that I could solve this issue where the components are there but the styling is missing.

![image](https://user-images.githubusercontent.com/10548251/48483009-3dc7e080-e7e0-11e8-9194-63e9ee1a0b95.png)

**Comment by micahgodbolt** [comment]
@rexkenley can you possibly recreate this issue in a codepen? I want to make sure I fully understand the ask.

Also, have you looked into the layer hostId prop? Will this solve your issue? https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Layer/Layer.types.ts#L50

**Comment by rexkenley** [comment]
Hi Micah,

Yes I did look at the hostid, the only problem is that it is tied to the current document.

Basically in Crm365, webresources are rendered inside a frame. This limits any "modal surface" rendering to just inside the frame. It would be great if I can pass the parent DOM object that hosts the frame and then the "modal surface" can render beyond its containing frame.

Something like this, as you can see the Clients frame is so much shorter than the Batch Update dialog. 
![image](https://user-images.githubusercontent.com/10548251/49611867-ef39dc00-f970-11e8-9fe2-1b4000db480c.png)

Thanks for taking a look at this.

**Comment by dzearing** [comment]
This is projection to another popout? Like new mail in OWA?

Trying to understand what the css requirement is. Project all rules over to the other frame?

**Comment by rexkenley** [comment]
Hi Micah,

That is correct. Currently I am using a workaround utilizing react-portal(https://github.com/tajo/react-portal). It has a "node" prop that I pass the parent DOM. I had to re-render the entire thing because react-portal doesn't seem to bring the necessary css for the ui elements.

**Comment by rexkenley** [comment]
Hi David.

Yes. Using this image as example, imagine the columns are the iframes (menu, emails, selected email view). I want to be able to display a dialog box across frames like the context menu and not be limited to the origin iframe borders.

As I mentioned before I tried react-portal, but it has issues with delivering the css to the "main" window. I tried linking the css to the main page but to no avail.

![image](https://user-images.githubusercontent.com/10548251/49626826-891d7b00-f9a9-11e8-9d75-ed81bf0a7660.png)

**Comment by micahgodbolt** [comment]
Portal appears to be the same thing as the Fabric Layer, moving DOM into a second top level node. I don't believe this will help you get outside of an iframe. You would need support from the parent application to be able to render anything that goes outside of that frame.

**Comment by micahgodbolt** [comment]
@rexkenley is there any chance you can repro this in a codepen? I haven't ever seen this library work, so it's hard to guess what is happening.

**Comment by micahgodbolt** [comment]
Yeah, it's my understanding that it is not possible to extend iframe content outside of the iframe

https://stackoverflow.com/questions/31081821/extend-div-outside-bounds-of-iframe


It's a security concern: if an iframe can create an input, and place it on top of the password field, it could intercept passwords.

**Comment by rexkenley** [comment]
Micah

But I was able to do it with react-portal. As I mentioned before react-portal has a node prop which I populate with window.parent.document.getElementId("root").

Fabric is using the same "node prop" except it is "hard coding" it to the current document. 

Here is what the full re-render looks like in Crm
https://user-images.githubusercontent.com/10548251/49611867-ef39dc00-f970-11e8-9fe2-1b4000db480c.png

This is a combination of react-portal and Fabric DialogBox
https://user-images.githubusercontent.com/10548251/49681380-c8fa6600-fa6e-11e8-9760-3ed10707a777.png

**Comment by micahgodbolt** [comment]
Yeah, we just won't be able to debug this scenario unless we can repro the bug. Have you tried adding react-portal to your example? Or at least mock it up in a quick create-react-app repo


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by rexkenley** [comment]
Micah

I was studying the Layer source code and I have suggestion of how to do this.
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Layer/Layer.base.tsx

ReactDOM.createPortal(eventBubblingEnabled ? (<Fabric className={classNames.content}>{this.props.children}</Fabric>) : (<Fabric className={classNames.content} onClick={this._filterEvent}
onContextMenu={this._filterEvent} onDoubleClick={this._filterEvent} onDrag={this._filterEvent}
onDragEnd={this._filterEvent} onDragEnter={this._filterEvent} onDragExit={this._filterEvent}
onDragLeave={this._filterEvent} onDragOver={this._filterEvent} onDragStart={this._filterEvent}
onDrop={this._filterEvent} onMouseDown={this._filterEvent} onMouseEnter={this._filterEvent}
onMouseLeave={this._filterEvent} onMouseMove={this._filterEvent} onMouseOver={this._filterEvent}
onMouseOut={this._filterEvent} onMouseUp={this._filterEvent} onKeyDown={this._filterEvent} onKeyPress={this._filterEvent} onKeyUp={this._filterEvent} onFocus={this._filterEvent}
onBlur={this._filterEvent} onChange={this._filterEvent} onInput={this._filterEvent}
onInvalid={this._filterEvent} onSubmit={this._filterEvent}>{this.props.children}</Fabric>),
            **this._layerElement**
)

This is the same method call that react-portal is using. I traced it to the function _getLayerElement().

if (host) {
  this._host = host;

  if (!this._layerElement) {
    const doc = getDocument();
    if (!doc) {
      return;
    }

    this._layerElement = doc.createElement("div");
    this._layerElement.className = classNames.root!;
    setPortalAttribute(this._layerElement);

    host.appendChild(this._layerElement);
  }
}

If we can somehow add a parentNode parameter to _getLayerElement, I think that should work. What do you think?

if (parentNode || host) {
  this._host = parentNode || host;

  if (!this._layerElement) {
    const doc = (!!parentNode && parentNode.ownerDocument) || getDocument();
    if (!doc) {
      return;
    }

    this._layerElement = doc.createElement("div");
    this._layerElement.className = classNames.root;
    setPortalAttribute(this._layerElement);

    host.appendChild(this._layerElement);
  }
}

**Comment by micahgodbolt** [comment]
@rexkenley if you feel this small change would resolve your situation, go ahead and write up a PR. I think it'll help us better understand what you are trying to do as well.

**Comment by rexkenley** [comment]
Sorry, got busy with work and have need done a pull request before.

**Comment by Johns3n** [comment]
+1 
I declare <Modal> in an Iframe and use ReactDOM.createPortal() to attach it to a node in window.top, but doesn't really work (only <div class="ms-layer"> is attached to node in <body>, but nothing from the modal)

**Comment by rexkenley** [comment]
I want to report that if you are using Unified Interface, the surfaces render properly using a pcf control. However, this is still an issue if you are using a web resource. 

*The red line borders the pcf control.
![image](https://user-images.githubusercontent.com/10548251/69071059-422c6800-09f7-11ea-9631-b43a784dcfb3.png)

**Comment by rexkenley** [comment]
I am going to close this issue since MS is pushing for adoption of the Unified UI.

Everybody should check out the new Fluent UI.
