### ISSUE TITLE
SwatchColorPicker: Fluent theme

### ISSUE THREAD

**Issue by Vitalius1** [microsoft/fluentui#7069]

**Comment by Vitalius1** [comment]
When reviewing this component could you pay more attention to the border thickness and the white gap in between the border and the color itself when hovered or selected. The toolkit shows 2 sizes but in code we have the ability to have infinite variations. It would make sense to have a breakpoint of some sort saying something like this: if the size provided bigger than X amount of pixels we have these white gap and this border thickness, otherwise have a default to some set numbers. Keep in mind that this issue looks like exists in the default styles which I filed in #7086

**Comment by betrue-final-final** [comment]
Sure thing! I'll set up breakpoint info after we ok this.

**Comment by maxwellred** [comment]
### Fluent Updates

**Diffs between Toolkit (TK) and Live**

-**Large Swatch Style:** There isn't a default large size and I'm wondering if you want one created.
-**Border Radius of Containing Table:** Live = None / TK = 2px
-**Box Shadow of Containing Table:** Live = None / TK = elevation8
-**Circle Border (acting as focus border) at Rest:** Live = #EAEAEA / TK = #A19F9D
-**Color Swatch border in hover/active/focus states:** Live = #EDEBE9 / TK = #F3F2F1

@betrue-final-final please let me know which of these changes are required

**Comment by Vitalius1** [comment]
@maxwellred it might be that the toolkit is not updated with the latest designs that I got from the designer owning the component. @betrue-final-final do you know if Janet ever ported the SwatchColorPicker specs we discussed into the toolkit?
