### ISSUE TITLE
Add Ability to Style row styles (height, color, etc.) from props on DetailsList

### ISSUE THREAD

**Issue by davallen** [microsoft/fluentui#7080]
In order to change the height of a row (not using compact property) you need to style the root and cell of IDetailsRowStyles. Also, then you need to get a handle to selectors attribute of the IDetailsListStyles and override there also. 

Component: DetailsList 

Tagging: @KevinTCoughlin

**Comment by aneeshack4** [comment]
@davallen Can you fill out the bug report please? Or provide a codepen or at least expected behavior vs. actual behavior? Thank you.

**Comment by KevinTCoughlin** [comment]
> 
> 
> @davallen Can you fill out the bug report please? Or provide a codepen or at least expected behavior vs. actual behavior? Thank you.

I have some context here from a discussion on Teams the other day. I'll fill this out as a feature request in a bit. Tagging myself so I'm aware.

Thanks for opening this @davallen.

**Comment by KevinTCoughlin** [comment]
Labeled as "Needs: Backlog Review" as we should tackle this holistically. Currently, there exists a number of limitations with styling `DetailsList` and its inner components. An ask which highlights this is to make the list's background `transparent`.

**Comment by agg23** [comment]
+1

**Comment by JustSlone** [comment]
Closing out old issues. 
This may be tackled in future updates to DetailsList.
If this is still a need, reopen, or file an updated issue. Thanks!
