### ISSUE TITLE
Simplify Icon Naming

### ISSUE THREAD

**Issue by jsedlak** [microsoft/fluentui#7141]
**Describe the feature that you would like added**
Searching https://developer.microsoft.com/en-us/fabric#/styles/icons#icons for "player", "person", "account" and "people" all result in similar icons. While a difference in naming between singular and plural is understandable, the addition of account and player makes things confusing. Additionally, there exists no base icon for an individual. These should be simplified into Person/People or Account/Group and fleshed out for Add/Remove/Settings/etc.

**What component or utility would this be added to**
Icon Library

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
Based on documentation: https://developer.microsoft.com/en-us/fabric#/styles/icons#icons

**Comment by Jahnp** [comment]
Hi @jsedlak , thanks for the feedback. We'll bring this feedback to the central icons team that Fabric draws from, as we prefer to make as few "middle-tier" changes as possible to our icon definitions. That said, I believe there *may* be tagging/alias information available for some icons that we could draw from to help parse the differences. I'll look into that and follow up here.

**Comment by Magendiran** [comment]
**Somebody really needs to look at Icon namings...**
Found so many issues with Icon naming and it's completely irrelevant to the way its tagged

**Few of Icons with wrong names** 
https://developer.microsoft.com/en-us/fabric#/styles/icons#icons

1. Location (Radio Button)
2. Focal Point (Landscape)
3. AspectRatio (Looks like Drang and Drop)
4. Annotation (Cut)
5. AutoEnhanceOff / AutoEnhanceOn (Names swapped)
6. Record2 (Just Circle)
7. Toggle Off (No Toggle On) do we need to use CSS rotation?
8. Preview
9. AutoHeight
10. Accounts (must be Email Accounts)
11. AddOnlineMeeting / JoinOnlineMeeting (Could be better)
12. UserEvent
(Person must be a fan of Falsh superhero, there are so many power bolt symbols in Icons 🥇  :) )

**Comment by JadyM** [comment]
[Icon Tool] -- it is sometimes difficult to find a relevant icon due to unusual icon names, as mentioned in prior comments. I guess they cannot now be changed as that would break all existing components. 

Could the Office UI Fabric icons listed in [Icon Tool] be given **tags** or **secondary descriptive names** so it's easier to find the icon you want using search? I imagine people use a wide variety of different search terms to find an icon. 

Other than that minor problem, the Icon Tool is an **excellent resource**; something I use constantly every day. Thanks!!

**Comment by JustSlone** [comment]
Closing this out as we have a new set of Fluent UI icons with new and better names. If this is still an issue, please file it over here: https://github.com/microsoft/fluentui-system-icons
