### ISSUE TITLE
Cleanup: OUFR packages should not depend on react-dom

### ISSUE THREAD

**Issue by kenotron** [microsoft/fluentui#7160]
### Environment Information 
 
- __Package version(s)__: master packages all have this
- __Browser and OS versions__: applies to all

#### Actual behavior:
 
`ReactDOM.findDOMNode` is present in DragAndDropHelper, for example. Generally it is a code smell if the component code has some dependency on ReactDOM. We should eliminate this dependency. Libraries built on top of Fabric is arbitrarily tied to react-dom package which is unnecessary.
 
#### Expected behavior:

packages/office-ui-fabric-react should not have `react-dom` in its dependencies list.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Yes
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable) All

**Comment by KevinTCoughlin** [comment]
Also:

https://github.com/OfficeDev/office-ui-fabric-react/blob/fd8af84b7deea5e883773f565477b74831cd6c81/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx#L341

Curious, how would one avoid its usage in `Layer.base`?

https://github.com/OfficeDev/office-ui-fabric-react/blob/fd8af84b7deea5e883773f565477b74831cd6c81/packages/office-ui-fabric-react/src/components/Layer/Layer.base.tsx#L103

**Comment by kenotron** [comment]
Shoot didn't realize portal hangs off of ReactDOM. Will have to figure out whether we can abstract that out.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by kenotron** [comment]
This really is a sticking point because of the use of portals... not much going around this - OUFR must then depend on ReactDOM. Question is whether we could use a lint rule to disable to use of it?

https://palantir.github.io/tslint/rules/import-blacklist/

So we can at least reduce the use of it via a rule? That means we can at least disable this rule only for exceptional cases?

**Comment by KevinTCoughlin** [comment]
@kenotron were you planning on doing this work or should I leave it unassigned / for shield?

**Comment by KevinTCoughlin** [comment]
> 
> 
> This really is a sticking point because of the use of portals... not much going around this - OUFR must then depend on ReactDOM. Question is whether we could use a lint rule to disable to use of it?
> 
> https://palantir.github.io/tslint/rules/import-blacklist/
> 
> So we can at least reduce the use of it via a rule? That means we can at least disable this rule only for exceptional cases?

@kenotron are we able to exclude `*.test.tsx` files from this rule since they all use `react-dom`? It doesn't seem like it from the documentation. If that's the case, then it seems like we'd have to write a custom task for this lint rule.

**Comment by micahgodbolt** [comment]
@kenotron was this a placeholder for yourself? Should we remove this issue from the shield?

**Comment by kenotron** [comment]
I believe Kevin's done a lot of investigative work here. @KevinTCoughlin if this isn't feasible, we may as well just close this :(

**Comment by micahgodbolt** [comment]
Ah, I didn't know kevin had background on this one. Thought it just feel on his lap due to shield duty. Whatever works for you two.

**Comment by kenotron** [comment]
@KevinTCoughlin - this one is tough! I am not sure how to exclude certain rules in tslint for subset of files. We can only do tslint:disable for those. It seems kind of excessive at this point. I'm thinking of just closing this issue. What do you think?

**Comment by ecraig12345** [comment]
Now that we're finally removing `findDOMNode`, that means we can remove `react-dom` and `@types/react-dom` from `peerDependencies` in all of our main packages as part of the version 8 release. (It will still be needed as a dev dependency for tests, and as a dependency or peer dependency in a few niche cases.)

**Comment by ecraig12345** [comment]
Circling back on this since I tried to make a PR removing react-dom everywhere and then noticed the Layer issue which had already been mentioned here (oops). 😆  @dzearing Do you know if there's any way around having Layer use `ReactDOM.createPortal`?

**Comment by ecraig12345** [comment]
I was able to remove the react-dom peer dep from some of the packages at least (see #15634), just not react-internal or anything that depends on it. 😞

**Comment by ecraig12345** [comment]
It won't be possible to do further removals due to certain components needing `createPortal`, which is only available from `react-dom`.
