### ISSUE TITLE
Improvements to documentation: "Open a CallOut from a mouse click"

### ISSUE THREAD

**Issue by fergiemcdowall** [microsoft/fluentui#7162]
**Improvement to the CallOut doc: https://developer.microsoft.com/en-us/fabric#/components/callout (and I think this could also apply to ContextualMenu)**

A pretty typical user scenario is "right click anywhere on the page" -> "get up some info" (a menu, or an explanation box). In Fabric, you would do this by positioning a `CallOut` or `ContextualMenu` around a mouse click.

"Open a CallOut from a mouse click" is only partially, tantalisingly documented (In `office-ui-fabric-react@4.x` you can sniff out the coords of a click and then initialise a CallOut by setting `targetPoint`. However this method is marked as _depreciated_, and doesn't seem to work at all in `office-ui-fabric-react@5.x`).

The docs say that a CallOut can be positioned by passing a MouseEvent object to it, but no examples are provided.

IMPROVEMENTS TO DOCS:

1. As a developer I would like to see an example in the [Variants section](https://developer.microsoft.com/en-us/fabric#Variants) of positioning a CallOut by setting `target` with a `MouseEvent`
2. If `targetPoint` is in fact not available in `office-ui-fabric-react@5.x`, then the docs should be updated to reflect this

**Comment by KevinTCoughlin** [comment]
> IMPROVEMENTS TO DOCS:
> 
>     1. As a developer I would like to see an example in the [Variants section](https://developer.microsoft.com/en-us/fabric#Variants) of positioning a CallOut by setting `target` with a `MouseEvent`

@fergiemcdowall, I must defer to @micahgodbolt & @Jahnp regarding the above ask of adding a variant for `Callout`. I know that for a number of components, the variants are due for an audit.

If we were to render a variant of `Callout` at the current mouse position given a region or user interaction, my primary concern would be that it seems broken or out of place if not presented clearly. That said, the content of the website resides in this repository and is open-source.

I believe you had opened a StackOverflow question with similar content, however I can't seem to find it to link here.

>     2. If `targetPoint` is in fact not available in `office-ui-fabric-react@5.x`, then the docs should be updated to reflect this

It looks like `targetPoint` is available in `office-ui-fabric-react@5.x`. Here is the definition:

https://github.com/OfficeDev/office-ui-fabric-react/blob/8b4262dcc4a6c99d2fe840aca3373f5cfc9f76aa/packages/office-ui-fabric-react/src/components/Callout/Callout.types.ts#L80

Here is usage of the above interface member in code:

https://github.com/OfficeDev/office-ui-fabric-react/blob/8b4262dcc4a6c99d2fe840aca3373f5cfc9f76aa/packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx#L481

Can you share a repro of the above not working in `5.x` as per our [issue template](https://github.com/OfficeDev/office-ui-fabric-react/issues/new?template=bug_report.md)? It will help the team debug.

**Comment by micahgodbolt** [comment]
Yeah, it'd be difficult without an iFrame to do this on the Callout page. I could see creating a Codepen and linking out to it from the page.

**Comment by fergiemcdowall** [comment]
Hello! I posted this bug report [a little over a year ago](https://github.com/OfficeDev/office-js-docs/issues/1187), and was recently asked to reopen it here, which I did. Sadly I don't have the capacity to file or reformat the report for a third time.

Basically I am suggesting that "rightclick -> open context menu" is a common user paradigm that should be described in the documentation. Surely a context menu should be available from a rightclick? If so, an code example should be provided.

**Comment by KevinTCoughlin** [comment]
Thanks for the context @fergiemcdowall. It looks like @Jahnp is onboard with adding this example to the `Callout` documentation page given https://github.com/OfficeDev/office-js-docs/issues/1187#issuecomment-355681744.

@Jahnp, should the above "ContextualMenu"-like example be bound to a specific area of the `Callout` page? I ask because this a unique example which I don't believe we have an existing pattern for. Once we understand how it should be presented, it should be trivial to implement.

**Comment by KevinTCoughlin** [comment]
Tagged "Needs: Design" input on the following:

1. Is this an example we want to surface on the `ContextualMenu` variants page?
1. If so, how should it look?
    - One idea is to render a container with text suggesting the user right-click within to render the `ContextualMenu` at the mouse target.

cc: @Jahnp if he's back in the office

**Comment by ling1726** [comment]
`@fluentui/react-positioning` provides a helper function [createVirtualElementFromClick](https://github.com/microsoft/fluentui/blob/master/packages/react-positioning/src/createVirtualElementFromClick.ts) which creates a virtual anchor element from a mouse event.

This virtual anchor pattern is compatible with any of our components that use `usePopper` which will be used across v9. This is already used in `@fluentui/react-popover`.

FYI @khmakoto  @JustSlone
