### ISSUE TITLE
Move wiki into oufr and automate publishing to github

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#7183]
(Updated by @dzearing)

1. Move wiki into oufr repo, under /wiki folder.
2. Add a regular job (maybe it can be triggered on /wiki modifications in master) which reflects the updates to the wiki.git

**Comment by Jahnp** [comment]
This would be great. We had an issue for this, #3823, a few months back that, sadly, was closed by stalebot before we ramped up the team and added the shield process.

**Comment by micahgodbolt** [comment]
One other wacky idea....what if we were to leverage our devops public wiki? It's 100% public, and might have better functionality. https://uifabric.visualstudio.com/fabricpublic/_wiki

**Comment by cliffkoh** [comment]
That.. doesn't support PRs (and it wouldn't allow the public to change the wiki either). I'm not sure how it would be better.

**Comment by micahgodbolt** [comment]
I hadn't looked yet at the devOps option. yeah, if it doesn't support PRs, its of no extra value

**Comment by ecraig12345** [comment]
I see 
```
```

I'm confused, am I supposed to 

Copying in @dzearing's description from #7702:

> The Wiki is right now using the github wiki support. This is somewhat convenient for repo contributors but makes it impossible for readers to submit requests for changes.
>
> Let's move the wiki content into the repo and set up a nightly job to push the changes into the github wiki branch. That way people can submit PRs to modify things.

**Comment by ecraig12345** [comment]
I don't understand why we'd want to put the docs in a separate repo, as opposed to just a folder in OUFR?

Noticed we already have a `ghdocs` folder at the root of the repo, but that just has a readme saying:
```
## Docs have been moved to Wiki repo.
### https://github.com/OfficeDev/office-ui-fabric-react/wiki
### https://github.com/OfficeDev/office-ui-fabric-react.wiki.git
```

Would it make sense to move the docs back into this folder, then (like @dzearing  suggested in #7702) set up a nightly job to copy the changes to the wiki?

**Comment by dzearing** [comment]
@ecraig12345 Do what I mentioned in the other bug. We went back and forth on the right thing here, and keeping the wiki inside the same repo helps with discoverability. So, expected outcome here is:

Move wiki into oufr repo, under /wiki folder.
Add a regular job (maybe it can be triggered on /wiki modifications in master) which reflects the updates to the wiki.git

**Comment by dzearing** [comment]
updated original description.

**Comment by JustSlone** [comment]
Closing this out, if it comes back up as a need we can tackle it
