### ISSUE TITLE
Make a circular determinate progress control

### ISSUE THREAD

**Issue by betrue-final-final** [microsoft/fluentui#7244]
There's a need for a more compact version of our progress bar. 
We could use the same design for the Spinner component, and possibly reuse the styles there. This would be used in a new design for a progress panel, but could be used in any number of places.

**Comment by micahgodbolt** [comment]
spinner gets us close to the design, but we'd need to flesh it out a bit more before starting.

**Comment by betrue-final-final** [comment]
That would be great.

**Comment by micahgodbolt** [comment]
Are you able to provide a concrete design example? What does 0% look like, what does 100% look like?

**Comment by betrue-final-final** [comment]
Pretty simple. 0 would be all grey or the lighter theme color track. Filled would be themed color.

**Comment by betrue-final-final** [comment]
I can send a picture when I'm home

**Comment by betrue-final-final** [comment]
![image](https://user-images.githubusercontent.com/20363037/49229720-fa09d500-f3a2-11e8-82da-cd70e2686013.png)

**Comment by micahgodbolt** [comment]
Thanks ben! Wasn't sure where you'd want it to start. So that's great.

**Comment by KevinTCoughlin** [comment]
Nice! Interested to see this in action, particularly the animation curve 😃

**Comment by betrue-final-final** [comment]
I would defer to Fluent curves for this one...also as it is data bound, not sure how that would work. The product design this is going to support first also is looking at pause button functionality inside it. We can also do fun things like make it a check at completion.
![image](https://user-images.githubusercontent.com/20363037/49310503-55b38b80-f493-11e8-88e2-a7e1d65c2fe0.png)

**Comment by mdtauk** [comment]
Right To Left should have the direction reversed.

Also there could be a Starting Angle if there is a need to change that.
