### ISSUE TITLE
Use DatePicker to select just a month

### ISSUE THREAD

**Issue by venuprasadnaik** [microsoft/fluentui#7327]
This is the sample work I have done 

export interface IDatePickerRequiredExampleState {
  monthOfYear?: MonthOfYear;
}

export class MonthPicker extends React.Component<{}, IDatePickerRequiredExampleState> {

  constructor(props: {}) {
    super(props);

    this.state = {
      monthOfYear: MonthOfYear.January,
    };
   public render(): JSX.Element {
      const { monthOfYear } = this.state;
      <div className="col-sm-3">
            <DatePicker
              label="From"
              isRequired={true}
              isMonthPickerVisible={true}
              placeholder="Select a date"
              ariaLabel="Select a date"

            />
          </div>
     }
}

**Comment by kkjeer** [comment]
Hi @venuprasad3, it doesn't look like the DatePicker component currently supports this behavior. I can add it to our backlog review to see if we will implement this feature.

I don't know if this suits your scenario, but the [Dropdown](https://developer.microsoft.com/en-us/fabric?example=#/components/dropdown) component can be used to allow the user to select a month.

@micahgodbolt some information on this feature request:
1. The CalendarMonth component exposes an `onSelectDate` method that is called when the month is selected.
2. The CalendarMonth component is not currently exposed from oufr.
3. The DatePicker component could take in a prop such as `monthPickerOnly` that is used to display only the month picker component in the DatePicker and call its `onSelectDate` prop when the CalendarMonth `onSelectDate` is called.

**Comment by ymihir** [comment]
I also need this. Any update on this please?

**Comment by flanakin** [comment]
+1

**Comment by andrueastman** [comment]
+1

**Comment by PontusEkengren** [comment]
+1
I need to be able to select year and month just as react-date-picker offer in their tool.
![image](https://user-images.githubusercontent.com/3965061/106576302-4631a080-653d-11eb-8fba-5643c5c16a51.png)
