### ISSUE TITLE
ScrollContainer and VirtualizedList experiments are using legacy context API

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#7368]
As part of removing deprecated constructs in preparation for future React versions (see [this issue comment](https://github.com/OfficeDev/office-ui-fabric-react/issues/4613#issuecomment-446413003)), we need to remove usage of the legacy context API. ScrollContainer and VirtualizedList in experiments are some of the components using this API.

See [the React docs](https://reactjs.org/docs/context.html) for more info about the new context API.

**Comment by layershifter** [comment]
https://github.com/microsoft/fluentui/wiki/Version-8%3A-Release-notes#full-strict-mode-support-for-all-suite-components

> (Exception: There are still a few components in @fluentui/react-experiments which use UNSAFE_ methods, as well as the @fluentui/react/lib/compat Calendar and DatePicker. These were lower priority to fix due to their experimental or deprecated status. If you have a dependency on an experimental component and need strict/concurrent mode, please file an issue.)

Feel free to follow up on this issue 😼
