### ISSUE TITLE
ITheme: Discuss support for custom font variants, spacing and typography

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#7385]
Right now the IFontStyles interface is simply tiny through mega (all size related). What happens when I need custom variants like "BlogHeader" vs "PageTitle". Is my only recourse to document that blog headers are large but page titles are xLarge?

Then, if we are supporting custom text variants, it'd be preferred to style them with themable values (font family, font size, font weight, as well as colors) so that a user could simply change the type ramp and all of their text sizes would follow suite. 

I'd also want theme to support some spacing values. We currently have spacing as an internal value, but I definitely want to see that fleshed out so that we can use `<Stack gap={ theme.spacing.small} />` and easily change the density of the application through theming.

**Comment by natalieethell** [comment]
ITheme now has a `spacing` property and IPartialTheme has a `defaultFontStyle` property. 

https://github.com/OfficeDev/office-ui-fabric-react/blob/4f37bd4de75b6aa610fcf4787b62af42c44f7501/packages/styling/src/interfaces/ITheme.ts#L32-L38

https://github.com/OfficeDev/office-ui-fabric-react/blob/4f37bd4de75b6aa610fcf4787b62af42c44f7501/packages/styling/src/interfaces/ITheme.ts#L57-L60

You can specify `defaultFontStyle` to specify font property defaults, like so:

```tsx
loadTheme({ defaultFontStyle: { fontFamily: 'Segoe UI' } });
```

**Comment by micahgodbolt** [comment]
It'd be nice to have defaultFontFamily, as well as fixedWidthFontFamily etc, and if we have spacing, it'd be nice to have fontSize in a similar stack. A lot of this is to be able to drive custom font styles as well, assuming we have a story for creating/using custom font styles in our Text control. i.e. how do I create a CenteredHeader Text style that content authors can reuse.
