### ISSUE TITLE
New Component: Scheduler

### ISSUE THREAD

**Issue by jtermine** [microsoft/fluentui#7467]
**Describe the feature that you would like added**

A scheduler component with a "month view", "week view", "work week view", "day view", "agenda view" and the ability to view the schedules of multiple people or resources side-by-side.  The appointments in the schedule could be updated with drag-and-drop, mouse interactions with time blocks, hotkeys, etc.  See Outlook on the desktop or DevExpress for an example.

**What component or utility would this be added to**

This is a complex component that would integrate various existing Office Fabric UI components.  Although any skilled individual could create this complex component him or herself with the existing components, there is considerable value having an "approved" scheduler style that is harmonious with Fabric UI design principles.

**Have you discussed this feature with our team, and if so, who**

N/A

**Additional context/screenshots**

DevExpress has some good examples of what a scheduler might look like.  https://demos.devexpress.com/aspxschedulerdemos/

**Comment by micahgodbolt** [comment]
I'd love to see a Fabric lead effort to standardize calendering. I've spoken with the calendar team a few times about this. There's certainly desire, but not bandwidth.

**Comment by JustSlone** [comment]
A full scheduling/calendar component is beyond the scope of Fluent UI right now. Closing this out
