### ISSUE TITLE
Typing is not proper in HoverCard/ExpandingCard component props

### ISSUE THREAD

**Issue by atneik** [microsoft/fluentui#7571]
Refer to conversation in #7513 and fix typing in HoverCard/ExpandingCard component props. The issue is targeting 7.0 release as the ideal fix will be a breaking change
 
Are you willing to submit a PR to fix? Yes
Requested priority: Normal

**Comment by jdhuntington** [comment]
Pushing to `@next`, as this is an ideal place to use slots.
