### ISSUE TITLE
New Component: Tree

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#7597]
## Needed By
Sharepoint/Onedrive

### Code mockup/example

__Code Sample__

```

```

__Types__

| Name      | Type     | Default Value | Description |
|-----------|----------|---------------|-------------|
| className | string   |               | Optional class name to be added to the root |

## Steps

- [ ] Themable (Component.base/Component.styles)
- [ ] Unit tests
- [ ] Visual tests
- [ ] Documentation and examples
- [ ] Keyboard Accessible
- [ ] High Constrast Support
- [ ] RTL Support
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by micahgodbolt** [comment]
Blocked until we're happy with collapsible section

**Comment by juliosaenz** [comment]
This would be very helpful for our project in which we show the content on a NuGet package in a hierarchical fashion using a tree.

**Comment by reli-msft** [comment]
Hope a strong tree view can be there. The most complex example of a tree view may like this:

![image](https://user-images.githubusercontent.com/50213618/60623221-f5712900-9d96-11e9-9ab7-ab8e1a123e08.png)

You have:
 - (Optional) link lines
 - Rightmost buttons
 - Inline buttons

**Comment by ndoiselet** [comment]
Do you have any information on when this component will be implemented ?

**Comment by daxamin** [comment]
Any updates on this component?

**Comment by JustSlone** [comment]
This is a component we'd like to add, however, it's not on the current [roadmap](https://github.com/microsoft/fluentui/wiki/Fluent-UI-React-Roadmap) 

If someone from the community wants to collaborate with us and contribute the base of a tree component, let me/us know

**Comment by akash07k** [comment]
It would be good if someone works on this component and adds it in fluent UI

**Comment by JustSlone** [comment]
Also, if you're interested in this component please drop a 👍 on the issue, this will help us prioritize this against other requests
