### ISSUE TITLE
DetailsList-Grouped Focus not Working Properly After Selecting ShowAll With Keyboard or Mouse

### ISSUE THREAD

**Issue by canmenekse** [microsoft/fluentui#7604]
### Environment Information 
 
 
- Package version(s) : 6.124.0 probably, as of now it uses the one that is pointed by unpkg.com, hence [//unpkg.com/office-ui-fabric-react/dist/office-ui-fabric-react.min.js](//unpkg.com/office-ui-fabric-react/dist/office-ui-fabric-react.min.js)
- Browser and OS versions:  Happens both in Chrome & Edge

### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/anon/pen/JwaYOz
 
#### Actual behavior:

When using only with keyboard after selecting showAll, the focus should not goes back to the top of the page
 
#### Expected behavior:
 Don't actually know the current behaviour, but not the one it currently does
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, **No**)
 
Requested priority: (Blocking, High, **Normal**, Low)

**Comment by Vitalius1** [comment]
@cliffkoh do you know why this issue was not labeled and assigned to me by the Fabric bot? just as FYI.

@dzearing Is this related to #7609 or this looks like a little bit different?

**Comment by dzearing** [comment]
Well... I'm unsure if the FocusZone changes would address this, but I think it would. I can probably test this codepen once the FocusZone issue is addressed and get a better idea.

I will assign to myself and once the other bug fix is complete, run through this to double check.
