### ISSUE TITLE
New Component: Progress

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#7623]
### Description
The Progress control would be a universal control for all determinate, and indeterminate controls of any shape or design. Horizontal and circular controls would be included, but the control would support various other styles.

This control would deprecate, or replace the code used for spinners and progress indicators 

### Component ownership
Fabric Tactical

### Exports/Component breakdown
Progress

Possible variants

- CircularLoader
- HorizontalLoader
- CircularProgress
- HorizontalProgress

### Intended package/s
OUFR

### Example code

```jsx
//Determinate
<Progress max="100" value="70" />

//Indeterminate
<Progress /> 
```

### Public methods
| Name      | Type     | Description |
|-----------|----------|-------------|
| focus | () => void   | Sets focus on the control |

### Slots
| Name      | Type     |  Description |
|-----------|----------|-------------|
| root | div   | The outermost element |

### Tokens

| Name      | Type     | Default Value | Description |
|-----------|----------|---------------|-------------|

### Props
| Name      | Type     | Default Value | Description |
|-----------|----------|---------------|-------------|
| className | string   |               | Optional class name to be added to the root |

### Current state 
Proposed

### Todos

- [ ] Add Todos

### Steps

- [ ] Themable
- [ ] Unit tests
- [ ] Visual tests
- [ ] Documentation and examples
- [ ] Keyboard Accessible
- [ ] High Constrast Support
- [ ] RTL Support
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by JustSlone** [comment]
Keeping this open, but making it clear that this is not on the current [roadmap](https://github.com/microsoft/fluentui/wiki/Fluent-UI-React-Roadmap)
