### ISSUE TITLE
☂ Panel open issues for convergence

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#7625]
There are often issues using Panel due to the way that the internal structure is built (header/content/foot/scrollable sections etc). For those that want the structure of a pane (popover full height container with close button and dismiss capture) we should do what we did with Dialog and Modal. Create a 'pane' (or other named control) that is a non opinionated version of the Panel. No headers/footers, no panel type, no onRenders. Then create a Panel which extends? the pane and adds content specific properties, types, and other opinions. 

This would also be an opportunity to improve the resilience of the layout logic, add slots tokens and build everyone on createComponent etc. 

- [ ] Abstract out Pane
- [ ] Refactor with slots/createComponent
- [ ] Add Tokens
- [ ] Rewrite layout to be more resiliant (flex based)
- [ ] #6772
- [ ] #6658
- [ ] #6657
- [ ] #9068
- [x] #10905

**Comment by JasonGore** [comment]
I completely agree with this! Adding #9068 which popped up as well.

**Comment by xugao** [comment]
related to #10905 as well. footer content is not scroll-able

**Comment by mltejera** [comment]
@brandonthomas FYI

**Comment by mltejera** [comment]
Related to #10905, which is now closed:

For WCAG 2.1 support, our panel component has had to hack this panel a little bit. At small screen sizes we remove content from the headers and footers and instead stuff those inside the body render function so they're included in the scrolling. We leave the nav section pinned to the top.
