### ISSUE TITLE
Form Input Improvements: Meta Issue

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#7636]
Up until now our form inputs have been pretty purpose built for how they get used in our primary applications. We have not been spending much time thinking about how form inputs work as a whole. Consistent required states, labels, descriptions and error text. Controlled vs uncontrolled. An easy way to combine inputs into a single form and get a response on submit.

This issue is to capture all of the various input coherence efforts in our backlog and ensure that we have a well thought out plan for what our inputs look like in the future. 

## New Controls/Refactors
New Component: TextField Refactor #6827 
New Component: Form #5582
ComboBox/Dropdown: refactor and/or merge #6030
Investigate using ContextualMenu for the menus in the dropdown and comboBox components #5206
Feature: Unified Error and validation handling for "Form" components #3620
DatePicker: onRenderPrefix, onRenderSuffix #5290 (This should come via TextField, or an abstraction of Textifield view, being the base control for all pickers)

## Misc
BasePicker: add description and errorMessage props #7457
Pickers should have `isRequired` property #6636
add underline style for DatePicker and Dropdown #5631
Add errorMessage to ChoiceGroup Component #6527
Indeterminate state missing for Radio and Checkbox #5390
Dropdown: Add public interface to get selected value #7692 (this applies to all form components)
SpinButton: Add errorMessage and onGetErrorMessage #11923

**Comment by ThreadPitt** [comment]
Yes, that is something that makes it quite hard for us devs to work with it, e.g. I'd expect to be an "errorMessage" on all components, etc. Especially, if you use something like yup to roll your validation logic and you have no consistent way to set an error message across all controls.

**Nonetheless, keep up to good work, guys!**
