### ISSUE TITLE
ComboBox: iOS focusing on Text Input after tapping dropdown button

### ISSUE THREAD

**Issue by jh2he** [microsoft/fluentui#7658]
On iOS, tapping on the drop-down button of the ComboBox will open the popout then immediately close it.
Possibly this is caused by the auto focus on the Text Input, highlighting the selection, which causes the flyout to lose focus.
This happens not all of the time, but very frequently.

Is there a property I can set to not have it auto focus on the Text Input when clicking on the Button/Icon?

### Environment Information 

- __Package version(s)__: Latest 6.125 https://fabricweb.z5.web.core.windows.net/oufr/6.125.0/#/examples/ComboBox
- __Browser and OS versions__: iOS only, Chrome and Safari.
Tested on iPhone X. iOS 12.
 
#### Actual behavior:

![fabric ios combobox](https://user-images.githubusercontent.com/20142717/51211883-cc420680-18e4-11e9-81f2-cd0e99288626.gif)

Tapping the dropdown button opens and immediately closes the popout.

#### Expected behavior:
 
Tapping the drop down button should show the flyout without issues.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, but I will need to take while to familiarize with ComboBox.
 
Requested priority: Normal
 
Products/sites affected: Microsoft Dynamics 365

**Comment by mikewheaton** [comment]
I'm not able to repro this in Safari on an iPhone 7 Plus or iPad Pro, both running iOS 12.1.2.

What browser are you using? It doesn't look like Safari based on the tab bar. And you mentioned that this doesn't always happen; do you see any patterns for when it does or doesn't happen?

**Comment by jh2he** [comment]
If the control is at the top of the page, it seems to have no trouble. If it's near the bottom or maybe lower-middle, the keyboard might be blocking/closing the popout instantly.

**Comment by mikewheaton** [comment]
It's not disappearing for me, but I can get into a weird state where the input I'm typing in is covered by the options.

![img_c4614f7c9bd3-1](https://user-images.githubusercontent.com/1382445/51213920-2e910c00-18d1-11e9-93b1-9f3df72aa57d.jpeg)
