### ISSUE TITLE
Sticky- scroll behavior

### ISSUE THREAD

**Issue by tharshada** [microsoft/fluentui#7673]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 If the cursor is placed on[ sticky header](https://microsoft.sharepoint.com/teams/cyrusplayground/yiminlib/Forms/AllItems.aspx?enableFeatures=1207
), on scrolling down, the [scroll stops](https://microsoft-my.sharepoint.com/:v:/p/hatrived/ETlMSXTP5a1DmWMAWnrUJTsBMafNwggO15VXdU2IcNIkCw?e=CufVyC
) when component becomes sticky & scrolling (up & down) doesn’t work after a certain scroll

 
#### Expected behavior:
 Not known

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: Normal
 
Products/sites affected: (if applicable)

**Comment by tharshada** [comment]
@leddie24 @mikewheaton @Vitalius1 @shagra-ms

**Comment by mikewheaton** [comment]
@leddie24 replied to an email about this, noting that it's known issue:

> Yes, this is an expected behavior, but not a desired one.  The Sticky’d element is not part of the scrolling container when it becomes Sticky, so any scroll events aren’t seen by the scroll container when the cursor is above it.
