### ISSUE TITLE
[Cleanup]: Fix event lifecycles in DragDropHelper

### ISSUE THREAD

**Issue by ThomasMichon** [microsoft/fluentui#7744]
This is to track TODO issues recorded in this PR #7738.

In React, event listeners should only be registered in `componentDidMount` or `componentDidUpdate` within the lifecycle of a `React.Component`. However, the components which consume `DragDropHelper` create instances in the `constructor` (bad since it may never get mounted) or in `render()` (bad since compnents should never mutate state or register listeners during `render()`).

Since PR #7738 is a minimal fix to stop a memory leak, this issue tracks that refactoring needs to occur in `DragDropHelper` and its consumer components to respect React lifecycles properly.

A better way to do this would be to have `DragDropHelper` itself be a render-prop component, which passes an interface for use in child components, provides a ref to the host component, and manages its registration of global listeners internally. This will ensure that React's lifecycle methods are always respected, while preserving the ability to use it from multiple consumers.

**Comment by micahgodbolt** [comment]
@KevinTCoughlin are you the best person to assign here?

**Comment by KevinTCoughlin** [comment]
> 
> 
> @KevinTCoughlin are you the best person to assign here?

Not if this needs to be done within the next week or two. And even then, I think the horizontal scroll fixes we have in mind are higher priority. 

I'm unsure of the scope of the refactor and verification. @natalieethell is currently on shield if that is a consideration.

**Comment by JustSlone** [comment]
Update
- The TODO in DetailsHeader.base.tsx is fixed.
- The TODO in DetailsList.base.tsx is still there

 https://github.com/microsoft/fluentui/blob/c6ae2b350037deb4e0bea07cdbdfe2e93455f4b1/packages/react/src/components/DetailsList/DetailsList.base.tsx#L776-L782
