### ISSUE TITLE
Panel: Fluent theme

### ISSUE THREAD

**Issue by Vitalius1** [microsoft/fluentui#7920]

**Comment by kenotron** [comment]
@vitalius1 - Could you attach a screenshot of what the panel fluent theme will look like?

**Comment by Vitalius1** [comment]
@kenotron There are some questions I still have to get clear on with designers about the redlines I got for a fluent Panel... but the main change would be in the drop-shadow and probably the header will be a little more bolded. With that said there are lots of other discrepancies in the default styles that I found while investigating some of the breakpoints issues and I am willing to do a cleanup (align it with the toolkit) in the default styles and then proceed with fluent changes.
Here is all I got but need to confirm with designers that this the final draft of the fluent styles
![screen shot 2019-02-07 at 11 39 51 am](https://user-images.githubusercontent.com/29514833/52438000-1cb81880-2acd-11e9-8466-632767c8a468.png)

**Comment by kenotron** [comment]
Cool - just saw this come thru with no description :) This helps a lot! Thanks!

**Comment by Vitalius1** [comment]
@betrue-final-final I will mark this issue as blocked as it lacks designs for all the Panel types. #7933 is bringing only the common changes for all Panels minus some specifics to Header's margins and breakpoints. Will also remove myslef from assigned for now and feel free to assign me back when the fluent redlines are done.

**Comment by JustSlone** [comment]
Old issue, closing this is either already done or tracked through other means, if this is incorrect feel free to reopen with more information! 👍
