### ISSUE TITLE
List bugs with getPageSpecification

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#7925]
Thomas mentioned a known bug with list around getPageSpecification and getPageHeight. Creating this issue to track that work. Need him to update this issue with better title/description.

**Comment by KevinTCoughlin** [comment]
@ThomasMichon can you share more? I currently have #8125 out for review which involves `getPageHeight`.

**Comment by KevinTCoughlin** [comment]
See: https://github.com/OfficeDev/office-ui-fabric-react/pull/8125/files#r260954189 for context.
