### ISSUE TITLE
Clicking Prefix/Suffix in TextField does not result in the focus being set.

### ISSUE THREAD

**Issue by redoz** [microsoft/fluentui#7935]
### Environment Information 
 
- __Package version(s)__: current
- __Browser and OS versions__: all

#### Actual behavior:
 

Clicking the prefix or suffix section does nothing.
 
#### Expected behavior:
Clicking the prefix or suffix section of a TextField should result in the TextField receiving focus.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Low
 
Products/sites affected: (if applicable)

**Comment by kenotron** [comment]
Linking here for posterity's sake. https://developer.microsoft.com/en-us/fabric/#/components/textfield

If you click on the prefix / suffix in the http / .com example, it doesn't do anything. We should focus inside the textfield as @redoz mentioned here.

**Comment by redoz** [comment]
I'll provide a PR shortly.

**Comment by kenotron** [comment]
Oh great! Thanks!

**Comment by kenotron** [comment]
Okay I'm gonna put this in the backlog for discussion then.

**Comment by xugao** [comment]
Looking at this issue, i am not sure I agree clicking prefix/suffix should give the input the focus here. 
see others:
https://ant.design/components/input/
https://getbootstrap.com/docs/4.0/components/input-group/

@redoz - this issue has been open for a while now. can you confirm if you still need this to be address? if so, pls let me know the reason behind the request

**Comment by redoz** [comment]
@xugao Well, I'm no longer involved in the project that required me to develop on the front-end so for me this has no priority. 

However, the samples you provided draw the Focus around the part of the text box you can actually input things into, whereas OUFR draws the focus around the whole component.

I think either OUFR should then only treat the "input" part as focusable, and not the whole control, or ensure that focus is provided when the prefix/suffix is pressed as they currently sit inside the focusable area.

OUFR:
![image](https://user-images.githubusercontent.com/1670030/73076583-afa8b900-3ebe-11ea-9f28-0b1f4ea6f4cf.png)

Your example:
![image](https://user-images.githubusercontent.com/1670030/73076652-d2d36880-3ebe-11ea-9e84-600cedbaecc7.png)

**Comment by xugao** [comment]
@betrue-final-final - could you provide guidance on desired experience here?

**Comment by betrue-final-final** [comment]
This isn't a usability issue, and it is coded per the original design.
