### ISSUE TITLE
Proposal: Deprecate floatingPickerProps & selectedItemListProps in ExtendedPeoplePicker

### ISSUE THREAD

**Issue by Adjective-Object** [microsoft/fluentui#7941]
**Describe the feature that you would like added**

In BaseExtendedPicker, we have this weird non-idiomatic pattern of accepting a separate props object and a rendering method, and then rendering the component in the child.

https://github.com/OfficeDev/office-ui-fabric-react/blob/900176501c2744491375d31ed46deec0e99e9abb/packages/office-ui-fabric-react/src/components/ExtendedPicker/BaseExtendedPicker.tsx#L155-L175

I'd like to propose deprecating this property and passing off responsibility for binding these props to the consumer (since they're already rendering with a render method).

The work associated with this would mostly be updating the examples and adding the `@deprecated` annotation + a cleanup task for the next major version bump.

Related to #7871 

**What component or utility would this be added to**

ExtendedPeoplePicker

**Have you discussed this feature with our team, and if so, who**

n

**Additional context/screenshots**

**Comment by micahgodbolt** [comment]
@Adjective-Object Are you interested/considering doing this work?

**Comment by Adjective-Object** [comment]
Yep! I spent some time working on an implementation on my side but ran into issues making the typing of it legal because of the componentRef's typing on props. I'm going to give it another try and open up an RFC.
