### ISSUE TITLE
API surface for Tooltip/Callout doesn't allow proper position of beak even with DirectionalHint.bottomLeftEdge

### ISSUE THREAD

**Issue by cliffkoh** [microsoft/fluentui#7970]
### Environment Information 
 
- __Package version(s)__:  6.138
- __Browser and OS versions__:  all browsers/os

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/cliffkoh/pen/OdEqNE?editors=0010

#### Actual behavior:
 
![image](https://user-images.githubusercontent.com/1003246/52672287-49f03680-2ed2-11e9-9e73-15653eb2acd9.png)

 
#### Expected behavior:
 
![image](https://user-images.githubusercontent.com/1003246/52672408-a5babf80-2ed2-11e9-9464-cd894da928ac.png)

**Comment by JasonGore** [comment]
This is a feature request regarding beak position in certain scenarios where the beak's current positioning doesn't particularly align with the target. [This CodePen](https://codepen.io/jasongore/pen/daKxvg) highlights the ask a bit more clearly with a list of Checkboxes with varying content width:

![image](https://user-images.githubusercontent.com/26070760/52809619-8db77d00-3045-11e9-8f2d-355896bc5cfb.png)

This seems to be exacerbated by the amount of `Tooltip` content, which appears to push the beak even further out:

![image](https://user-images.githubusercontent.com/26070760/52809540-62349280-3045-11e9-8954-53b210c306e3.png)

**Comment by cliffkoh** [comment]
Thanks, very good illustration of the existing limitations.

**Comment by JasonGore** [comment]
One potential solution is providing an optional target id for either the callout or the beak.

**Comment by JasonGore** [comment]
[This Codepen](https://codepen.io/jasongore/pen/VgEZVZ) offers a couple of fixes making use of Callout's `target` prop while this issue is investigated.

**Comment by brandonthomas** [comment]
Sort of tangential to this, I'm not able to get the beak to slide in the way that I want when I override the width of a Callout when using TeachingBubble. Here I have tried setting width and max width both through CalloutProps and through styles and get the same result. Note that the directional hint is BottomLeftEdge so I'd expect the beak to by on the left side of the callout with the callout slid over to the right a bit.
![image](https://user-images.githubusercontent.com/7529639/57897287-f4952f80-7808-11e9-8996-c79a25fae205.png)

without width props or styles (or any combination thereof) you'll note that the beak is in the same spot:
![image](https://user-images.githubusercontent.com/7529639/57897354-3920cb00-7809-11e9-8ac4-3ef46346c9b6.png)


I'm also pretty sure calloutWidth and calloutMaxWidth are no-op on TeachingBubble.

**Comment by brandonthomas** [comment]
I've worked around this with negative margins...so...gross but works.

**Comment by brandonthomas** [comment]
Actually that work around isn't stable. If the positional css rules are in certain places margins can cause the beak to visually disconnect. So that's not a great solution either.
