### ISSUE TITLE
ColorPicker sliders should work on touchscreens

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#8013]
**Describe the feature that you would like added**
On a touchscreen device, it should be possible to "grab" any of the sliders within the ColorPicker and drag them around. This doesn't work today (try it on [the example](https://developer.microsoft.com/en-us/fabric#/components/colorpicker)).

**What component or utility would this be added to**
ColorRectangle and ColorSlider

**Have you discussed this feature with our team, and if so, who**
me? :)

**Additional context/screenshots**
Similarly to #8012 (about ColorPicker keyboard accessibility), it's possible that the ColorSlider touch handling could be fixed by using a re-styled regular Slider, but ColorRectangle would need to be fixed separately.

(Also similar to #8012, this is probably out of scope for shield, so I added the backlog review tag.)

**Comment by JasonGore** [comment]
Mobile / touch scenarios is something we should definitely have a documented story on. This is somewhat similar to #5734 but this issue may not be styling-related.

**Comment by ecraig12345** [comment]
This one isn’t (primarily) styling-related. The fix will involve adding touch event handling.
