### ISSUE TITLE
DetailsList: UI bug when selecting many items quickly with selectionMode.single on mobile Safari

### ISSUE THREAD

**Issue by hxltinh** [microsoft/fluentui#8027]
### Environment Information 
 
- __Package version(s)__: 6.138.0 
- __Browser and OS versions__: Mobile Safari (IOS version 12.1.4)

### Please provide a reproduction of the bug in a codepen:
 [codepen](https://codepen.io/hxltinh/pen/XOoBPx)

 
#### Actual behavior:
When selecting items many time very quickly with selectionMode.single:
![img_0020](https://user-images.githubusercontent.com/8114730/52943775-76a7c080-33a0-11e9-964d-f713c02d420a.jpg)

 
#### Expected behavior: 
It should not display grey background on none selected item 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal

**Comment by aneeshack4** [comment]
@hxltinh I just tried to repro this on an iPhone XS with iOS 12.1.4 and it doesn't repro. When I move really quickly touching the different items there's no lag that produces a grey background on an unselected item. What version of iOS are you using? The only thing I can think of that could you get this behavior is perhaps you have started selecting another item but not fully - Apple supports different pressures in touch sensitivity so if you didn't apply full pressure to the newly selected item, the old one stays selected while the new one that you haven't fully selected gets the gray background.

**Comment by hxltinh** [comment]
@aneeshack4 Please have a look at this gif, hope it helps :) 
![uifabricdetailslistbug](https://user-images.githubusercontent.com/8114730/53143408-6a06b080-35ca-11e9-8275-6a3b7b70fda8.gif)

**Comment by KevinTCoughlin** [comment]
@hxltinh I appreciate the report. This is most likely visual lag in the browser repainting given the mobile hardware and current cost of re-rendering items in the DetailsList. We are making optimizations there currently, but I'm unaware of a "quick fix" for this specific bug and hardware combination.

@hxltinh, if can point to a particularly computationally expensive function resulting in this lag perhaps by using the DevTools "Performance" tab, then we can try to address that issue in particular.

**Comment by hxltinh** [comment]
@KevinTCoughlin Thanks for your feed back, I already done some test that you mentioned, I need to discuss with my team about the result. May be I'm wrong but I did not see anything strange with the result.

**Comment by dzearing** [comment]
I believe this is hover related. In IOS if you tap on something it can stick the hover state on a thing, I believe. So even though there is one item selected, the hover state is appearing.

You can see people asking about it here:
https://stackoverflow.com/questions/17233804/how-to-prevent-sticky-hover-effects-for-buttons-on-touch-devices

I would *not* suggest going with the recommended solution though... hooking up an event hander to touch end of every hoverable entity and remove/adding the node? That's terrible.

This is rather complicated, but perhaps a better approach might be to treat this how we treat focus treatments: if a touch event is detected, disable hovers. if a mouse event is detected, enable. Do it through a global class flag like `ms-Fabric--isHoverVisible`.

**Comment by hxltinh** [comment]
@dzearing I think you are right :) 
![img_0022](https://user-images.githubusercontent.com/8114730/53219367-4313b180-3692-11e9-9c0d-05451c159063.PNG)
![screen shot 2019-02-22 at 10 55 05](https://user-images.githubusercontent.com/8114730/53219383-4e66dd00-3692-11e9-93d0-0c4cab992c62.png)

**Comment by KevinTCoughlin** [comment]
> I believe this is hover related. In IOS if you tap on something it can stick the hover state on a thing, I believe. So even though there is one item selected, the hover state is appearing.
> 
> You can see people asking about it here:
> https://stackoverflow.com/questions/17233804/how-to-prevent-sticky-hover-effects-for-buttons-on-touch-devices
> 
> I would _not_ suggest going with the recommended solution though... hooking up an event hander to touch end of every hoverable entity and remove/adding the node? That's terrible.
> 
> This is rather complicated, but perhaps a better approach might be to conditionally show hover state like how we conditionally render focus treatments: if a touch event is detected, disable hovers. if a mouse event is detected, enable. Do it through a global class flag like `ms-Fabric--isHoverVisible`.

TIL. Thanks @dzearing!

**Comment by aneeshack4** [comment]
Seems like a solution was found that could be done on @hxltinh's end so I'm going to close this - feel free to reopen if it persists/there's follow up.

**Comment by hxltinh** [comment]
@aneeshack4 If you don't mind, please tell us if this fix will be applied to your repository? because we really don't like to apply the work-around solution for this bug.

**Comment by aneeshack4** [comment]
@hxltinh Ah sorry I thought this was resolved as a fix on your end. I'll see if it's a quick fix I can make while I'm on shield but if it's more involved, it'll need to go onto the backlog. Touch behavior on mobile safari is a pretty limited use case so this is low pri.

**Comment by hxltinh** [comment]
@aneeshack4 thanks for your feedback, we would like to have it fixed on the repo. We can wait because it's not a serious problem, please take your time :)

**Comment by aneeshack4** [comment]
Looked into fixing this for a bit and couldn't find anything straightforward so it'll take longer than shield time - putting this into our backlog.
