### ISSUE TITLE
Type Safety for the 'as' prop

### ISSUE THREAD

**Issue by natalieethell** [microsoft/fluentui#8069]
**Describe the feature that you would like added**

It would be great for the `as` prop across the repo to have type safety. So, for example, rendering an element as an anchor tag should allow anchor-tag-specific props like `href`, while rendering it as a 'div' should make `href` invalid.

This request requires upgrading to TypeScript 2.9 and potentially making changes to `createComponent`.

Here is a snippet of something that @ThomasMichon proposed to me and @KevinTCoughlin:

```tsx
import * as React from 'react';

type HTMLPropsOf<TFactory> = TFactory extends React.DetailedHTMLFactory<infer P, infer T> ? P : never;

type IAsProps<TAs extends keyof React.ReactHTML> = {
  as: TAs;
} & (HTMLPropsOf<React.ReactHTML[TAs]>);

interface ITextProps {
  text: string;
}

interface IGenericComponentClass<P = {}, S = {}> {
  new <TAs extends keyof React.ReactHTML>(props: P & IAsProps<TAs>): React.Component<P & IAsProps<TAs>, S>;
}

class Text extends React.PureComponent<ITextProps> {
  public render(): null {
    return null;
  }
}

declare function createComponent<P>(componentType: React.ComponentType<P>): IGenericComponentClass<P>;

const Foo = createComponent(Text);

const test = <Foo as='a' href='bar' text='test' />;
```

The `& HTMLPropsOf<React.ReactHTML[TAs]>` ensures that the additional props come directly from the props for the element type.

I discussed this briefly with @JasonGore, who said that this implementation might not quite match up with Text and `createComponent`, so there may be more to discuss there. The return type for `createComponent` may not be able to coexist with non-HTML types and we should make sure that this solution works even for components that do not have an `as` prop.

**Comment by JustSlone** [comment]
No longer relevant with slots support going forward
