### ISSUE TITLE
Shimmer creator

### ISSUE THREAD

**Issue by prabirshrestha** [microsoft/fluentui#8075]
**Describe the feature that you would like added**
Add a page in fabric website to auto-generate shimmer react code based on drag and drop.

**What component or utility would this be added to**
Shimmer

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**
http://danilowoz.com/create-content-loader/
![image](https://user-images.githubusercontent.com/287744/53216765-80ccf780-360a-11e9-967a-c9f79dd86953.png)

**Comment by Jahnp** [comment]
This is really cool @prabirshrestha ! I bet something like this would be helpful. Adding @atneik and @Vitalius1 who own Shimmer. We can discuss this at the next backlog review.

**Comment by Vitalius1** [comment]
I am completely on board with this and it looks amazing use of SVGs and the online tool is great.

**Comment by Vitalius1** [comment]
If only I knew more about SVGs at the time of building Shimmer 😞 ... The library looks really slim and the only functionality it does not have in comparison to Shimmer is that we can wrap a line of content and have it swapped when the content loads through a fade in and fade out animation...
With that said I do think this worths to be reviewed and consider how we can make use of it. Thanks @prabirshrestha for filing the feature request.

**Comment by clechner77** [comment]
I full support this.  I love Shimmer but it seriously takes as long for me to create a shimmer as it does the rest of most projects.  Really.  My head just cannot wrap itself around how to create Shimmer elements/groups unless it's super simple.  No joke.  "Ok, you just created something with 50 components, thousands of lines of code, with a performant global state, and it's gorgeous... and it took you 3 days to create a shimmer?"  I'm not complicating things either....

So yes, it'd be wonderful to have a tool or some general tips/guidance on how things fit together.  Maybe I'm the only one here......
