### ISSUE TITLE
Should <Pivot /> set the size of its `tabpanel` div relative to the size of the control?

### ISSUE THREAD

**Issue by ceszare** [microsoft/fluentui#8153]
Hi!

I am using the <Pivot /> control to lay out content within a page. I would like to be able to set the dimensions to the Pivot control explicitly (for instance, by providing a height), and would like to be able to also customize the content properties based on the size of the parent.

If my child component sets its height to 100%, I would expect that this would be set relative to the space provided by the Pivot Item's viewport.

You can see an example of what I am thinking to achieve here (look at styles.css):

https://codesandbox.io/s/xolo79qxp4

In the example above, I set my tab content to 100%, and I make the Pivot control grow to the full size of the viewport.

I can achieve what I would like if I peer into the styles provided by the Pivot control as follows (on styles.css again):

https://codesandbox.io/s/jvx163k03y

Here, I am explicitly setting styles and layout on the items created by the Pivot control. I don't like this approach because it requires me to know the implementation details of the Pivot control itself. If the Pivot changes its implementation, my workaround could break.

What is the recommended way to do this?

**Comment by micahgodbolt** [comment]
I don't think this is currently possible outside of pretty specific CSS overrides. The best bet would be wrapping with flex and allowing flex-grow on the content. This isn't currently possible with existing IPivotStyles

**Comment by tomasro27** [comment]
My use case is the following:
I have a react grid that requires height and width to be set as props. This height and width is usually retrieved from the parent div. However, PivotItem sets its height and width based on the child (or wraps the child). This set up turns in no rendering of the child, because both the pivotItem and the item itself depend on each other for the height and width. 

I ended up setting the Pivot component to flex, and chanding the PivotItem height and the divs inside PivotItem to be 100% of its parent. It would be good to have the option through IPivotStyles, or just default TabItem to fill up to the size of its parent (Pivot).

**Comment by dapinitial** [comment]
I added to the shared component in my app:

```
import React from 'react';
import './tabbed-panel.css';
import { Pivot, PivotItem } from 'office-ui-fabric-react/lib/Pivot';
/**
 * @typedef TabPanelItem
 * @property {string} title
 * @property {(React.Component|string)} content
 */
/**
 * @param {object} props
 * @param {Array<TabPanelItem>} props.tabs
 * @param {object} props.customStyle
 */

export function TabbedPanel(props, fillHeight) {
  fillHeight = true;
  const listTabs = props.tabs;
  if (listTabs && listTabs.length > 0) {
    const customStyle = props.customStyle;
    return (
      <Pivot aria-label="Tabbed Panel" styles={customStyle} className={`${fillHeight ? "stretch-tabs" : ""}`}>
        {listTabs.map((tab) => {
          return (<PivotItem key={tab.title.toLowerCase()} headerText={tab.title}>
              {tab.content}       
          </PivotItem>)
        })}
      </Pivot>);
  }
  else {
    return <></>;
  }
}

```

then created some CSS:

```
/**
  * If fillHeight is set to true
  */
.stretch-tabs,
.stretch-tabs [role='tabpanel'],
.stretch-tabs [role='tabpanel'] > div,
.stretch-tabs [role='tabpanel'] > div > div {
  height: 100%;
}

```

Is there a better way to handle this now?

**Comment by dapinitial** [comment]
I defined my shared component like this:

`<Pivot aria-label="Tabbed Panel" styles={customStyle} className={`${props.fillHeight ? "stretch-tabs" : ""}`}>
`

and imported a CSS file like this:

```
.stretch-tabs,
.stretch-tabs [role='tabpanel'],
.stretch-tabs [role='tabpanel'] > div,
.stretch-tabs [role='tabpanel'] > div > div {
  height: 100%;
}
```
and my implementation looks like this:

`<TabbedPanel tabs={tabs} customStyle={customStyleForTheTabPanel} fillHeight={true} />`

Is this an acceptable solution or do you recommend another way? Should I do my CSS in JS in my customStyleForTheTabPanel?

**Comment by dapinitial** [comment]
I defined my shared component like this:

```
return (<>
  <CustomBreadcrumb items={breadcrumbItems} />
  <TabbedPanel tabs={tabs} customStyle={customStyleForTheTabPannel} fillHeight={true} />
</>);
````

and imported a CSS file like this:

```
.stretch-tabs,
.stretch-tabs [role='tabpanel'],
.stretch-tabs [role='tabpanel'] > div,
.stretch-tabs [role='tabpanel'] > div > div {
  height: 100%;
}
```
and my implementation looks like this:

`<TabbedPanel tabs={tabs} customStyle={customStyleForTheTabPanel} fillHeight={true} />`

Is this an acceptable solution or do you recommend another way? Should I do my CSS in JS in my customStyleForTheTabPanel?
