### ISSUE TITLE
HoverCard: card jump on expansion on Safari

### ISSUE THREAD

**Issue by gggjtgxing** [microsoft/fluentui#8255]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: Safari

#### Actual behavior:
 
see attached gif, the first time hover on a card, it jumps on expansion

Here is the PR in Fabric which introduced the regression. The bug is present since Fabric 6.129.4 (January 25): https://github.com/OfficeDev/office-ui-fabric-react/pull/7778
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
Products/sites affected: (if applicable)
https://developer.microsoft.com/en-us/fabric#/components/hovercard
![2019-03-05 12 16 40](https://user-images.githubusercontent.com/17696563/54148072-c4887500-43f0-11e9-834e-92856ce5a062.gif)

**Comment by KevinTCoughlin** [comment]
Thanks for the report @gggjtgxing. I need to verify for myself using Safari.

Meanwhile tagging @lorejoh12 and @joschect regarding #7778 perhaps introducing his behavior.

**Comment by Jahnp** [comment]
Also flagging @Vitalius1 and @atneik as FYI given HoverCard context.

**Comment by micahgodbolt** [comment]
I know this is marked priority 'high', but it has no affect on the user being able to accomplish their tasks, and only affects a single browser. If there is a clear fix for this, we can certainly apply it, but I wouldn't want to regress 7778 entirely for this. Is there any other way 7778 could be done?

**Comment by KevinTCoughlin** [comment]
> Is there any other way 7778 could be done?

I defer to @lorejoh12 regarding the above as author of the PR.

**Comment by Vitalius1** [comment]
#8370 is making a fix for something introduced in #7778 ... it might be the same issue or at least giving some directions where to look
