### ISSUE TITLE
Searchbox: Add a contextual menu as an Implementation example

### ISSUE THREAD

**Issue by betrue-final-final** [microsoft/fluentui#8269]
It is difficult to understand how the Searchbox works, especially keyboard behavior, after text is entered. 

This request is to add in an example with a simple context menu that will simulate suggestions. Ideally it could draw from a simple list of items, but it could also just show a generic contextual menu with title "Suggestions" and items reading "Suggestion 1, Suggestion 2..." etc. This will enable people to close the understanding gap between the entering suggestions, exiting them, and it's effects on the box.

**Comment by KevinTCoughlin** [comment]
Seems reasonable @betrue-final-final! I'll take a pass at it as part of SHIELD this week :).

**Comment by KevinTCoughlin** [comment]
@natalieethell, do you think this proposed `Searchbox` example would be a good opportunity to cross-promote `Announced`?

**Comment by Xannic** [comment]
Any progress on this? I would love to use the searchbox with suggestions in my project but I don't get how those suggestions can be rendered.

**Comment by sjs334** [comment]
@KevinTCoughlin did you ever get around to this? I am running into the same issue.

**Comment by Giuseppetm** [comment]
This is a great idea.
