### ISSUE TITLE
Support Custom Scrollbars

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#8302]
**Describe the feature that you would like added**
Support custom styleable scrollbars that are able to overlap the content but dissapear when not used. 

**What component or utility would this be added to**

Scrollable pane or custom control

**Have you discussed this feature with our team, and if so, who**
Teams is very interested in this scenario.

**Additional context/screenshots**

![image](https://user-images.githubusercontent.com/1434956/54302966-270f7b80-457f-11e9-8057-b778596cdc92.png)

**Comment by KevinTCoughlin** [comment]
Something to keep in mind regarding implementation of this is that custom scrollbars are often a performance bottleneck. It will be important to setup guardrails or advocate best practices when introducing this.

**Comment by micahgodbolt** [comment]
yeah, this isn't a "someone go and do this tomorrow". it's going to be a process to validate approach and implement

**Comment by pavinthan** [comment]
Guys, is there any idea to add custom scrollbar to "ScrollablePane" ? 🤔

**Comment by JustSlone** [comment]
Keeping this open for future consideration, but making it clear it's not currently on our [roadmap](https://github.com/microsoft/fluentui/wiki/Fluent-UI-React-Roadmap)
