### ISSUE TITLE
Sticky Perf: footer is getting rendered multiple times

### ISSUE THREAD

**Issue by tharshada** [microsoft/fluentui#8316]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 

[ Repro in CodePen](https://codepen.io/anon/pen/moXyBz)
#### Actual behavior:
 
Whenever distanceFromTop is changed, sticky component is forceUpdated. 
 In the [example](https://microsoft-my.sharepoint.com/:v:/p/hatrived/EXCRAAk4EdJLlYG2HHUvnvkBHN_mHplPo3eN2dor18JOdw?e=DMdmfR), if user expands/collapses a group, sticky footer is re-rendered. Expanding/Collapsing a group is a good way to change distanceFromTop, but it is not the only way which could change distanceFromTop. Consider, a non-grouped list which is loaded based on some paging logic. As the new pages are loaded, distanceFromTop would change, causing forceUpdate of the sticky component( in this case, it is footer).
 
#### Expected behavior: 
When a group is expanded or collapsed, re-rendering of sticky component(footer) should not happen. The same thing holds for a non-grouped list too.
 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, **High**, Normal, Low) 
 
Products/sites affected: **Yes**

**Comment by KevinTCoughlin** [comment]
I believe we saw similar performance concerns while profiling the usage of Sticky on some document libraries. 

IIRC @tharshada you have contributed to the control as well as @RupamSarkar & @leddie24. 

Would you be willing to take up this investigation and fix?

**Comment by tharshada** [comment]
> I believe we saw similar performance concerns while profiling the usage of Sticky on some document libraries.
> IIRC @tharshada you have contributed to the control as well as @RupamSarkar & @leddie24.
> Would you be willing to take up this investigation and fix?

@KevinTCoughlin I can take it up, but I would also like @leddie24 to share his views as [this change](https://github.com/OfficeDev/office-ui-fabric-react/commit/a336f17aaadf2598f6d0a824c13727a5b5fa15c5#diff-dea478649983c81b96e8c9a83285a146
) was made by him.

**Comment by KevinTCoughlin** [comment]
I spoke with @tharshada offline. They'll take up this work in a sprint or two perhaps with collaboration with @leddie24. There are some additional perf findings while @tharshada was performing initial analysis that I think would be meaningful to share here as we address document library performance wholesale.

Meanwhile, I will assign to @tharshada, but keep myself to track as I work in *List* areas.
