### ISSUE TITLE
Panel onDismiss called when you blur of it. We would hope a way is provided to disable that trigger.

### ISSUE THREAD

**Issue by vasilevach** [microsoft/fluentui#8339]
### Environment Information 
 
- "version": "6.135.1"
- OSX High Sierra

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/chris-panayotova/pen/rRdYar
 
#### Actual behavior:
 
So if you click on the "loader", which needs to be with a higher z-index (because, for example, you make a request of some sort), the panel gets its onDismiss called.
 
#### Expected behavior:
 
We should have a way to provide custom function for onBlur, or at least onDismiss should not be triggered on the Panel loosing its focus.

#### Priorities and help requested:

Help request
 
Are you willing to submit a PR to fix? (Yes, No)
No
 
Requested priority: (Blocking, High, Normal, Low) 
Normal priority
 
Products/sites affected: (if applicable)

**Comment by KevinTCoughlin** [comment]
I need to take a pass at a modified Codepen here. I imagine that the top-most layer (the spinner) when loading could intercept click events and stop propagation. That should then stop the `Panel` from dismissing below.

This approach seems reasonable given past experiences, let me take some time to put a repro together from yours.

**Comment by vasilevach** [comment]
The problem is that we sometimes open dialog from the panel as well. So as you can imagine, every time we start typing in the panel, the blur event gets triggered and thus the dismiss is called. So your suggestion would definitely help in a small example as the one I provided, but it does not help in the more complicate I outlined. Isn't there anything we can do to prevent that action from tking place?

**Comment by KevinTCoughlin** [comment]
@vasilevach, it looks like you _may_ be able to achieve the behavior you want by utilizing `Panel`'s `isBlocking?: boolean` prop. Specifically `isBlocking={false}` while the overlay is shown. See:

https://codepen.io/kevintcoughlin/pen/pYZgEV?editors=0010

There are likely alternative solutions if this doesn't match your needs, but I'd ask to have a repro closer to your application scenario if that's the case.

**Comment by vasilevach** [comment]
Ok, our use case is the following:
You have a form, and on button click, you open additional form in the Panel to enter some additional data. This panel needs to be blocking and the user should not be able to interact with anything else except the additional form.

Inside the Panel UI you have some asynchronous actions which need to block the whole app until they are finished. During that async calls we show overlay with spinner. We need both the panel to be in blocking mode, and to be able to block the whole UI for some time to show the loader. But if you happen to click on the loader, we do not want to close our Panel. Here is an updated codepen:

https://codepen.io/anon/pen/ywqKJa
1. Click "Open additional info"
2. Click "Check availability"
3. Click on the loader

**Comment by KevinTCoughlin** [comment]
> Ok, our use case is the following:
> You have a form, and on button click, you open additional form in the Panel to enter some additional data. This panel needs to be blocking and the user should not be able to interact with anything else except the additional form.
> 
> Inside the Panel UI you have some asynchronous actions which need to block the whole app until they are finished. During that async calls we show overlay with spinner. We need both the panel to be in blocking mode, and to be able to block the whole UI for some time to show the loader. But if you happen to click on the loader, we do not want to close our Panel. Here is an updated codepen:
> 
> https://codepen.io/anon/pen/ywqKJa
> 
> 1. Click "Open additional info"
> 2. Click "Check availability"
> 3. Click on the loader

Thanks, this is helpful. I will try to modify the above Codepen to achieve the desired behavior.

**Comment by ArrayKnight** [comment]
This seems related to:
https://github.com/OfficeDev/office-ui-fabric-react/issues/8470

Would it be sufficient to simply not close the panel on blur if the isLightDismiss equals false?

**Comment by stephenkjohnston** [comment]
We were having this issue occur when toast notifications; from `react-toastify`, appeared over the top of the panel, and were clicked on, `onOuterClick` would be called, and the panel would go away. For our application this was undesirable, and after reading the other proposed fixes, we just implemented the following solution:

```javascript
  const onOuterClicked = useCallback(() => {
    if (onOuterClick) {
      onOuterClick();
    }
  }, [onOuterClick]);

 return (<Panel {...props} onOuterClick={onOuterClicked}>{children}</Panel>);
```
