### ISSUE TITLE
mergeStyleSets: Typing Issue

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#8428]
### Environment Information 
 
- __Package version(s)__: 6.158.0
- __Browser and OS versions__: n/a

### Please provide a reproduction of the bug in a codepen:
 
https://codesandbox.io/s/kwx97q4yr5 (It can take a bit for typing to load.)

#### Actual behavior:
 
`mergeStyleSets` can't handle styles functions. It should generate a typing error when passed an `IStyleFunctionOrObject`, such as the `styles` prop of `IDialogContentProps`, such as in this example:

```tsx
const test = (
  dialogContentProps?: IDialogContentProps
): Partial<IDialogContentStyles> => {
  return dialogContentProps ? mergeStyleSets(dialogContentProps.styles) : {};
};
```

However, as the [CodeSandbox](https://codesandbox.io/s/kwx97q4yr5) shows, a typing error is not generated in this case. The second example shows how the generic can be specified to generate the expected error.

This issue was found in https://github.com/OfficeDev/office-ui-fabric-react/pull/8426#discussion_r267972298

(CodeSandbox is set to run against 6.107 to get around a CodeSandbox import error on newer versions of OUFR, but issue repros locally for 6.158 as well.)

#### Expected behavior:
 
Typing error generated when `IStyleFunctionOrObject` is passed as argument to `mergeStyleSets`.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by JasonGore** [comment]
I didn't think of this when writing up the issue, but it may be worth checking to see if TS3.x catches this issue on our `fabric-7` branch. If so, that's probably an acceptable enough resolution.

**Comment by khmakoto** [comment]
Just checked and TS3.3 in the fabric 7 branch does not catch this issue.

**Comment by khmakoto** [comment]
Same error is still occurring on TS3.5.1.
