### ISSUE TITLE
Integrate puppeteer into the tests

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#8434]
# Problem

Because we rely on jest and jsdom, we are unable to effectively test complex browser scenarios such as focus management (FocusZone tests) and scroll/virtualization related scenarios (DetailsList, List.)

# Investigation

Investigate integrating https://github.com/GoogleChrome/puppeteer into our workflows. 

Is it a replacement for jsdom?
Will it slow down test runs?
Should we separate puppeteer tests from jsdom tests?
How does a dev debug?

# Outcomes

The above questions are answered, and we at least have a test that can validate some basic FocusZone and/or FocusTrapZone scenarios in a real browser.

Also there is a wiki page if necessary describing the above.

**Comment by JustSlone** [comment]
Closing out old issues. 
If this is still a need, reopen, or file an updated issue. Thanks!
