### ISSUE TITLE
GetNativeProps "missing" on some components

### ISSUE THREAD

**Issue by fildahui** [microsoft/fluentui#8471]
Some components (for example the `DatePicker`, or `Button`) use the `getNativeProps` function which basically allows me to pass down native props (like the `id`) and have them rendered in the final html (even though there's no reference in the documentation).

On the other hand, some components do not use `getNativeProps` function (`Dialog`, for example) so if I set one of the props on these components I do not get them in the rendered html.

I was wondering why `getNativeProps` is used with some components and why it's not on some others. 
Maybe there's a specific reason for that but since I cannot find anything in the documentation I'd like to know what the reason is.

Thanks

**Comment by Vitalius1** [comment]
I would defer to what @dzearing or @micahgodbolt can answer to this question.

**Comment by micahgodbolt** [comment]
I agree this should be more consistent and intuative. One challenge specifically with Dialog is: what do you consider the outermost part of the control? Is it the visable modal? Or is it the wrapping divs that give it position.

One of our current goals is to propagate the idea of "slots" to all of our controls. This will establish a root slot for each control which WILL allow any component to take in valid HTML attributes. 

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Stack/Stack.types.ts#L23

**Comment by XuYan** [comment]
Do we change anything since the thread starts?
I would prefer to be able to add custom attribute to the visible modal. One common use case is supporting hotkey inside dialog, if we can allow tabindex = -1 to the outermost dialog element, it'll be quite convenient.

**Comment by natalieethell** [comment]
Just did a bit of investigation into what adding `getNativeProps` to Dialog would involve. It looks like there are a couple native attributes that can be specified on Dialog, like `aria-labelledby` and `aria-describedby`, that are passed into modalProps as `titleAriaId` and `subtitleAriaId`. Modal then passes these native props into Popup. 

So, it seems like the best place to pass in native properties would be where Dialog (rendered by Modal) renders Popup: 

https://github.com/OfficeDev/office-ui-fabric-react/blob/e9522b9fd7928c9ab40cdb9548084ff013f83a0d/packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx#L222-L228

Would that work for your scenario, @XuYan?

Additionally, I'm wondering if it would be best to clean these `titleAriaId` and `subtitleAriaId` properties up (mark them as deprecated) at the same time we move over to native properties. Just some thoughts.

**Comment by XuYan** [comment]
Thanks for the reply, @natalieethell.
I'm not sure I understand. For my use case, I just want to add a tabindex = -1 to the outermost element of the modal. Could you give an example if there is a way to achieve that?

**Comment by natalieethell** [comment]
@XuYan Sorry should have been more clear, so there isn't a way to achieve that at the moment, but I'm wondering if what I'm proposing above will work for you! It would place any native props you pass in to Dialog on the highlighted element below (`<div role="dialog" ... />`)

![image](https://user-images.githubusercontent.com/14134000/64656714-1e401b00-d3e5-11e9-8ef6-7f9a6034f6cf.png)

**Comment by JustSlone** [comment]
Closing out, will be covered as part of Dialog convergence and slots support
