### ISSUE TITLE
Highlight multiple dates at once.

### ISSUE THREAD

**Issue by paddymccallan** [microsoft/fluentui#8494]
**Describe the feature that you would like added**
Property like "highlightMultipleDates" and it accepts a value of array[] - The use case for this is to highlight a timeline of dates where a specific highlighted date may indicate a past event via different colour highlight.

**What component or utility would this be added to**
Calendar

**Have you discussed this feature with our team, and if so, who**
No

**Comment by Vitalius1** [comment]
@lorejoh12 is this a feature that was ever discussed or implemented in Calendar?

**Comment by jacksonv1lle** [comment]
This would be a nice feature. I am currently using the calendar as a search filter where the user can select a date range. I am using minDate and maxDate to specify the range but I would also like to highlight the min and max dates after the user has selected them.

**Comment by rohit-cyclotron** [comment]
Is this feature implemented ?

**Comment by alekkowalczyk** [comment]
Yup, would be general useful to somehow style provided days or highlight them.

**Comment by mokshithpyla** [comment]
Is this being prioritised? I would really appreciate a response as this issue seems to be in Backlog for a while.

**Comment by JustSlone** [comment]
This is not currently being worked on, but it's clear there is some demand for this feature. 

@lorejoh12, would this be a reasonable feature for someone to contribute to the Calendar control?
