### ISSUE TITLE
Dropdown and ComboBox in multi-select mode option keyboard navigation not aligning to designs

### ISSUE THREAD

**Issue by Vitalius1** [microsoft/fluentui#8584]
### Environment Information 
 
- __Package version(s)__: latest
- __Browser and OS versions__: all

### Bug description
Dropdown: https://developer.microsoft.com/en-us/fabric#/components/dropdown
When navigating inside a Dropdown callout when in multi-select mode (with checkboxes) we have the focus rectangle rendering just around the checkbox and its label.
![2019-04-02 17 01 26](https://user-images.githubusercontent.com/29514833/55444728-a4218580-556c-11e9-9c4c-02a03ab5d745.gif)

ComboBox: https://developer.microsoft.com/en-us/fabric#/components/ComboBox
When navigating inside a ComboBox callout when in multi-select mode (with checkboxes) we have no focus rectangle rendering and only the input changes. 
![2019-04-02 17 00 58](https://user-images.githubusercontent.com/29514833/55444730-a5eb4900-556c-11e9-93ce-5cdd756b2bfd.gif)

Confirmed with @betrue-final-final that this behavior is wrong and we need to align to design specs below:
![Screen Shot 2019-04-02 at 5 28 53 PM](https://user-images.githubusercontent.com/29514833/55444776-dc28c880-556c-11e9-9c75-2e746525bdc1.png)

#### Actual behavior:
 
- Dropdown: focus rectangle in wrong place
- ComboBox: no focus rectangle
 
#### Expected behavior:

 - Align to design specs

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Might be something to consider with Dropdown/ComboBox refactor
 
Requested priority: (Blocking, High, Normal, Low) Normal (because this behavior is in the code for some time and it looks like it's not filed by anyone else which means it's not of a high priority)

**Comment by kkjeer** [comment]
This could be added to the work involved in #6030

**Comment by sonimishra** [comment]
Any update on below bug?

**Comment by Vitalius1** [comment]
@micahgodbolt could you pass this issue to whoever is going to do the combobox/dropdown refactor. Thanks!

**Comment by micahgodbolt** [comment]
we're working on some cleanup around #4992. Once that is in, it'll be good to look at multi-select states
