### ISSUE TITLE
DetailsList Locked Header: List does not scroll to the top with up arrow

### ISSUE THREAD

**Issue by mathisGilliot** [microsoft/fluentui#8620]
### Environment Information 
 
- __Package version(s)__: **6.164.2**
- __Browser and OS versions__: **Chrome v73.0.3683.86**

### Repro steps:
 
From the **DetailsList Locked Header** example described here: https://developer.microsoft.com/en-us/fabric#/components/scrollablepane

You can export it to _CodePen_.

Scroll down to hide first element.

Set focus on a visible element in the list.
**Use keyboard navigation (arrow keys)**
Press up arrow to scroll up to the beginning of the list.
 
#### Actual behavior:
 
The scrolling stops before the top.
The focus goes to the header.
Some elements remain hidden.
 
#### Expected behavior:
 
The scrolling must go on till the first element.
Then go to header.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No.
 
Requested priority: Normal

**Comment by KevinTCoughlin** [comment]
Definitely looks like a bug with how `ScrollablePane` is handling scroll position in the nested `DetailsList` scenario. The behavior is unpredictable. Sometimes scroll is kept in-sync (slightly delayed) with row focus navigation, but more often scroll is behind by a step or two by the time focus shifts to the sticky header. 

cc: @leddie24

**Comment by KevinTCoughlin** [comment]
It looks like there's a disparity between when `Sticky` thinks the container has reached the top of the container and where the container's scroll position currently is. See below where on `syncScroll` I'm printing the `container.scrollTop` value:

```shell
Sticky.tsx:19 syncScroll 10
14:22:28.823 Sticky.tsx:19 syncScroll 10
14:22:28.823 Sticky.tsx:19 syncScroll 10
14:22:28.823 Sticky.tsx:19 syncScroll 10
14:22:32.353 Sticky.tsx:19 syncScroll 38
14:22:32.354 Sticky.tsx:19 syncScroll 38
14:22:32.354 Sticky.tsx:19 syncScroll 38
14:22:32.354 Sticky.tsx:19 syncScroll 38
14:22:32.514 Sticky.tsx:19 syncScroll 483
14:22:32.515 Sticky.tsx:19 syncScroll 483
14:22:32.515 Sticky.tsx:19 syncScroll 483
14:22:32.515 Sticky.tsx:19 syncScroll 483
14:22:34.257 Sticky.tsx:19 syncScroll 511
14:22:34.257 Sticky.tsx:19 syncScroll 511
14:22:34.258 Sticky.tsx:19 syncScroll 511
14:22:34.258 Sticky.tsx:19 syncScroll 511
14:22:34.431 Sticky.tsx:19 syncScroll 956
14:22:34.431 Sticky.tsx:19 syncScroll 956
14:22:34.431 Sticky.tsx:19 syncScroll 956
14:22:34.431 Sticky.tsx:19 syncScroll 956
14:22:36.443 Sticky.tsx:19 syncScroll 984
14:22:36.443 Sticky.tsx:19 syncScroll 984
14:22:36.443 Sticky.tsx:19 syncScroll 984
14:22:36.443 Sticky.tsx:19 syncScroll 984
14:22:37.880 Sticky.tsx:19 syncScroll 970
14:22:37.880 Sticky.tsx:19 syncScroll 970
14:22:37.880 Sticky.tsx:19 syncScroll 970
14:22:37.880 Sticky.tsx:19 syncScroll 970
14:22:37.913 Sticky.tsx:19 syncScroll 526
14:22:37.913 Sticky.tsx:19 syncScroll 526
14:22:37.913 Sticky.tsx:19 syncScroll 526
14:22:37.913 Sticky.tsx:19 syncScroll 526
14:22:38.938 Sticky.tsx:19 syncScroll 497
14:22:38.938 Sticky.tsx:19 syncScroll 497
14:22:38.938 Sticky.tsx:19 syncScroll 497
14:22:38.939 Sticky.tsx:19 syncScroll 497
14:22:39.439 Sticky.tsx:19 syncScroll 53
14:22:39.440 Sticky.tsx:19 syncScroll 53
14:22:39.440 Sticky.tsx:19 syncScroll 53
```

Initially it is `10px` off, later `53px`, etc. Sometimes, if you scroll slowly via keyboard the focus will traverse properly to the fixed header. However, it'll still be `10px` from the top, not `0px` which is what I would think it should be.

**Comment by leddie24** [comment]
@mathisGilliot, thanks for submitting this issue.  After some investigation, it looks like this is an issue with FocusZone and ScrollablePane not being able to scroll the content container further than it should.  @kkjeer, this will probably take some digging into with FocusZone and/or ScrollablePane to solve; not sure if I have the bandwidth at the moment, should we put this on backlog review in the interim?

**Comment by kkjeer** [comment]
@leddie24 thanks for investigating! I can add this to backlog review (@micahgodbolt fyi).
