### ISSUE TITLE
Calendar tab focus does not start on current date

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#8677]
**Describe the feature that you would like added**

When tabbing into the date region of the calendar, focus starts at the top left date of the month. I'm suggesting we change this behavior to start initial focus on the current date. This is the current experience in the DatePicker, so I don't see any reason why the calendar should be different.

__Calendar__

![date](https://user-images.githubusercontent.com/1434956/55835931-e9483900-5ad1-11e9-9dd8-14b24d50edb4.gif)

__DatePicker__

![date](https://user-images.githubusercontent.com/1434956/55893085-6e802c00-5b6c-11e9-9e12-ab4892a4acbc.gif)

**What component or utility would this be added to**
Calendar
**Have you discussed this feature with our team, and if so, who**
@lorejoh12 @dzearing 
**Additional context/screenshots**

**Comment by cristighr1995** [comment]
Are there any plans on getting this feature in soon?
