### ISSUE TITLE
Merge-styles: Ability to add plugin-like functionality to override css selector rules

### ISSUE THREAD

**Issue by frikkf** [microsoft/fluentui#8691]
Hoping to use Fabric React on Sharepoint 2013 and Sharepoint 2016 on premises, we see there is a specificity issue when Fabric css is added alongside the corev15.css provided by default by sharepoint.

The issue resolves in css selectors that look like this: input[type="text"], input[type="search"] {...}

We have been using Material UI with success, but as Fabric gives us a more complete styling in the Sharepoint/Office 365 world, we really want to migrate as this would create a better user experience for our users.

The solution when using Material UI was to add a JSS plugin/middleware which increases all css selectors specificity globally. Furthermore, incorporating it into a HOC applied at the root app component
```
function withRoot(Component: React.ComponentType) {
  function WithRoot(props: any) {
    const jss = createJss(jssPreset())
    jss.use(increaseSpecificity())
    return (
      <JssProvider jss={jss}>
        <MuiThemeProvider theme={theme}>
            <Component {...props} />
        </MuiThemeProvider>
      </JssProvider>
    );
  }
  return WithRoot;
}

const increaseSpecificity = (): any => {
  const selector = ':not(#\\20)';

  const options = { repeat: 1 };
  const prefix = Array(options.repeat + 1).join(selector);

  function onProcessRule(rule: any, sheet: any): any {
    var parent = rule.options.parent;

    if (
      sheet.options.increaseSpecificity === false ||
      rule.type !== 'style' ||
      (parent && parent.type === 'keyframes')
    ) return;

    rule.selectorText = prefix + rule.selectorText;
  }

  return { onProcessRule: onProcessRule };
};
```
**Describe the feature that you would like added**
Can we add a feature to the global theme, or maybe scopedSettings where one can provide a middleware function that receives appropriate merge-style props and outputs the selectorrule?

Something like this would be nice:
```
const MyCustomTheme = {
  settings: {
    theme: createTheme(),
    onProcessRule: (rule, stylesheet) => {
      const newRule = //something
      return newRule;
    }
  }
};

function withRoot(Component: React.ComponentType) {
  function WithRoot(props: any) {
    return (
        <Customizer {...MyCustomTheme}>
          <Component {...props} />
        </Customizer>
    );
  }
  return WithRoot;
}
export default withRoot;
```

**What component or utility would this be added to**
Merge-styles(?)

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**
If there is a way to achieve this using the mergeStylesSet or similar with $ and & selectors, maybe that would resolve my issue, but as far as I am concerned, there is currently no way to do it.

Cheers!

**Comment by joschect** [comment]
@frikkf Thanks for your request. Let me clarify the use case of this feature request. It sounds like you want to increase the specificity of the inline styles classnames/selectors so that they will take precedence over global styles, is that correct?

**Comment by frikkf** [comment]
@joschect yes. 
AS per now I cannot find a way to increase the specificity using the css in js feature fabric provides. When working with Sharepoint 2013 which has a lot of high specificity styles, it would be more clean to increase the specificity of all css in jss styles instead of providing css overrides in an extra css stylesheet. Material UI supports it due to JSS.
