### ISSUE TITLE
List: Window as scrollable container causes reflow due to cache miss

### ISSUE THREAD

**Issue by KevinTCoughlin** [microsoft/fluentui#8740]
### Environment Information 
 
- __Package version(s)__: Since https://github.com/OfficeDev/office-ui-fabric-react/pull/1866/
- __Browser and OS versions__: All

### Please provide a reproduction of the bug in a codepen:
 
Local dev example at http://localhost:4322/#/tests/detailslistbasicexample
 
#### Actual behavior:
 
When the scrollable element is the `Window`, the List's `measurePage` cache misses all but _once_ and indefinitely recalculates height on scroll by calling the following LoC:

https://github.com/OfficeDev/office-ui-fabric-react/blob/970839834096da3b74aa676a4462cce7c798adbb/packages/office-ui-fabric-react/src/components/List/List.tsx#L684

This is because the `measureVersion` counters are never in-sync due to the following conditional always succeeding:

https://github.com/OfficeDev/office-ui-fabric-react/blob/970839834096da3b74aa676a4462cce7c798adbb/packages/office-ui-fabric-react/src/components/List/List.tsx#L945 

The conditional always succeeds because `scrollHeight` is `undefined` when the element is the Window. Window does not have a `scrollHeight` nor `scrollTop` property.
 
#### Expected behavior:
 
The List's `measurePage` should not recalculate its height causing browser reflow for pages that are cached.

#### The Fix

This could be caught via type-safety by typing `private _scrollElement: Window | HTMLElement;`.

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/List/List.tsx#L106

#### Priorities and help requested:
 
This should be fixed, but I'm not sure how common having the `Window` be the scrollable element for `List` is regarding prioritization.

Scenarios where an element is the scrollable container are not impacted by this.

Are you willing to submit a PR to fix? Yes
 
Requested priority: Low
 
Products/sites affected: N/A

#### Screengrabs

**Before on scroll w/ cache filled**

![image](https://user-images.githubusercontent.com/706967/56245504-6cc6d480-6054-11e9-9ec7-1e20f5e9e35c.png)

![image](https://user-images.githubusercontent.com/706967/56245444-486af800-6054-11e9-9049-b4b2ff2ea24d.png)

**After "fix" on scroll w/ cache filled**
 
![image](https://user-images.githubusercontent.com/706967/56245492-65073000-6054-11e9-9d8b-7e26e9e175c4.png)

![image](https://user-images.githubusercontent.com/706967/56245482-5e78b880-6054-11e9-95f5-8a459e3d7742.png)

cc: @dzearing @aditima

**Comment by KevinTCoughlin** [comment]
The larger problem here is that `findScrollableParent`'s return type is not correct. It can return `Window | HTMLElement | null`, but is currently being cast:

https://github.com/OfficeDev/office-ui-fabric-react/blob/970839834096da3b74aa676a4462cce7c798adbb/packages/utilities/src/scroll.ts#L184

**Comment by chce** [comment]
Is there any progress on this? Are you accepting pull requests?

**Comment by chce** [comment]
Could we retrieve window alternatively by using document.scrollingElement?
Here's a polyfill that will ensure it works on IE11
https://github.com/mathiasbynens/document.scrollingElement

**Comment by KevinTCoughlin** [comment]
> Is there any progress on this? Are you accepting pull requests?

I would be open to reviewing a PR which fixes this in a backwards-compatible non-breaking way. Note that the problem only occurs when `Window` is the scrollable element.

**Comment by chce** [comment]
> > Is there any progress on this? Are you accepting pull requests?
> 
> I would be open to reviewing a PR which fixes this in a backwards-compatible non-breaking way. Note that the problem only occurs when `Window` is the scrollable element cc: @ThomasMichon.

My first idea is to simply try to provide the ownerDocument's scrollingElement of the element, before falling back to window. This doesn't solve the performance issue on non-compliant browsers that don't provide scrollingElement, such as IE11. What's your policy on adding dependencies to a polyfill? Should I try to rewrite the source code of the polyfill into a function that retrieves the element instead?
