### ISSUE TITLE
Dropdown renders a scrollbar in high contrast mode

### ISSUE THREAD

**Issue by sachin9996** [microsoft/fluentui#8745]
### Bug Report

- __Package version(s)__: office-ui-fabric-react 6.124.2
- __Browser and OS versions__: Windows 10/Edge 44.17763.1.0

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: Power Query Online

#### Describe the issue:

In high contrast mode, the Dropdown component renders an unnecessary scrollbar when navigating to the last element via keyboard.

#### Actual behavior:

A scrollbar is rendered when focus is on the last element.

#### Expected behavior:

No scrollbar should be rendered, just like normal (non high contrast) mode.

### Repro steps:

This repros on any single select Dropdown on https://developer.microsoft.com/en-us/fabric#/components/dropdown. In high contrast mode, navigate to the last element on the dropdown:

**Normal mode**
![image](https://user-images.githubusercontent.com/11214177/56254625-5cbfec80-6076-11e9-8ffb-2ce46263adab.png)

**High contrast mode**
![image](https://user-images.githubusercontent.com/11214177/56254663-82e58c80-6076-11e9-9cab-bc37ec4b33dc.png)

Here's a minimal codepen: https://codepen.io/sachin9996/pen/QPaYBY

**Comment by micahgodbolt** [comment]
It appears to only happen when focusing on the last item, which means it's probably the additional border/outline that is pushing the child to be larger than the parent, causing scrollbars.

**Comment by micahgodbolt** [comment]
Adding overflow: hidden to the ms-Callout-main appears to resolve this.

**Comment by micahgodbolt** [comment]
Yeah, this still happens when you place hover/focus on the last item in the dropdown. It appears the size of the item extends past the bottom of the dropdown. Either need to see where that added size is coming from or consider hiding hoverflow.
