### ISSUE TITLE
New component: Microfeedback

### ISSUE THREAD

**Issue by memichail** [microsoft/fluentui#8763]
## Component details
Micro-feedback is meant to be a new type of in-app feedback that is quick, easy to use, lightweight and most importantly contextual. Micro-feedback is about collecting small bits of information at specific points in your customer interaction within your product, service, retail environment or web experience. It will allow us to collect more frequent and relevant feedback at every interaction point with customers.

### Description
The Microfeedback control consists of an icon set of two (thumbs up and thumbs down). Taken together this set appears somewhere in your app where you want to collect feedback. Upon clicking any of the icon, it gets selected and can show a follow up question if desired. The control is flexible in terms of showing follow up question on either thumbs up or thumbs down, both or none. It is recommended to ask one question with up to 3 possible options to choose from. The followup question is a Fabric Callout component and is lightly dismissed upon selection or scolling/clicking away. 
Upon selecting the intended like/dislike button, a callback is available to be called to log this response if so desired. The callback could be used to log this in a database or send it to some service. Another callback is available to log the answer to a follow up question. The callbacks need to be implemented by the app that is using the control. 

### Which product teams/scenarios need this control

Many Office teams want this asap and are waiting. Please ask for details from us if a list of names is required. 

### Component ownership

Yes, Meher Michail will help maintain this component. 

## Component composition
The component is simple with a state and a base class that renders. Upon an icon being selected, it changes the state of the component and can send a signal thru the callback. 

### Imports/Dependencies

It uses Fabric icons, Fabric Default Button, Fabric Callout, Fabric Stack, Fabric Text and Fabric List. 

## Component code
This is in a pull request under Experiments. 

### Example code

```

```

### Public methods
| Name      | Type     | Description |
|-----------|----------|-------------|
| focus | () => void   | Sets focus on the control |

### Slots
| Name      | Type     |  Description |
|-----------|----------|-------------|
| root | div   | The outermost element |

### Tokens

| Name      | Type     | Default Value | Description |
|-----------|----------|---------------|-------------|
| textColor | color   | theme.white | text color for the control |

### Props
| Name      | Type     | Default Value | Description |
|-----------|----------|---------------|-------------|
| className | string   |               | Optional class name to be added to the root |

## Component Progress
In code review

### Current state 
Code review iteration 3

### Todos

- [ ] Add Todos
Unit and visual tests
Documentation
RTL Support - to check

### Steps

- [ ] Themable
- [ ] Unit tests
- [ ] Visual tests
- [ ] Documentation and examples
- [ ] Keyboard Accessible
- [ ] High Constrast Support
- [ ] RTL Support
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by JustSlone** [comment]
Closing this older issue. If it's still relevant and someone is available to work on it, let us know
