### ISSUE TITLE
MessageBar: focusing an element that is hidden hides the rest of the content

### ISSUE THREAD

**Issue by Vitalius1** [microsoft/fluentui#8776]
### Environment Information 
 
- __Package version(s)__: latest
- __Browser and OS versions__: all

### Please provide a reproduction of the bug in a codepen:
 The issue can be seen on the Fabric web site and also isolated here: https://codepen.io/vitalius1/pen/vMjBpG
 
#### Actual behavior:
 When tabbing with the keyboard on a collapsed MessageBar that has a focusable element hidden in the overflow, the focus goes to that element without showing it and also hides the rest of the content, similar to this demo:
![2019-04-18 16 17 36](https://user-images.githubusercontent.com/29514833/56396980-67a18b00-61f6-11e9-8901-176cbed5ebbf.gif)
... after that, there is no possible way to make the content show again in a collapsed state even if you focus anything else.
 
#### Expected behavior:
 The content should not disappear.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low)

**Comment by ecraig12345** [comment]
@Vitalius1 Just to clarify, are you planning to fix this or just reporting it?

**Comment by Vitalius1** [comment]
@ecraig12345 just reporting it because I have a deadline to meet on some fluent work. I honestly have no idea how to fix this. A link will be always focusable so how would you ever know if that link is in the overflow or not? Or even better why the browser is focusing on something that is not on the screen?

**Comment by ecraig12345** [comment]
That's fine. First idea that comes to mind is that when any child of the MessageBar receives focus, it should expand if collapsed. Would have to look into whether that's practical.

**Comment by Vitalius1** [comment]
Interesting approach... but what if the user does not want to have it expanded without him activating the expand button. Maybe he just wants to tab through the elements but never expand the full message. A very interesting accessibility question that maybe @betrue-final-final can have some input to share: do we automatically expand the collapsed MessageBar when having some focusable elements hidden in the overflow... or the user should be able to first navigate to the expand button and then expand it? What would be the tab order then?

**Comment by ecraig12345** [comment]
Good point. Changing the tab order so the expand button (if available) comes first sounds reasonable to me--though I'd want to get input from someone more familiar with these type of issues on the best way to do it. (I vaguely remember hearing that it's best to avoid messing with tabindex manually if possible?)

**Comment by micahgodbolt** [comment]
I've got it worked so that messagebar opens when focus is put into it, though if you close the message bar again the content is hidden again. Been messing with scrollTop without much success. 
![message-bar-expand](https://user-images.githubusercontent.com/1434956/69371193-2c67ae80-0c54-11ea-98bd-6c6c98f0fc98.gif)
