### ISSUE TITLE
There's no way to configure SearchBox to not remove icon when focused

### ISSUE THREAD

**Issue by yajiex** [microsoft/fluentui#8782]
**Describe the feature that you would like added**

We don't want to remove the search icon when focusing on the search box, however when digging into the code, I find the `width` of the icon is hard coded to be `4` when focusing and we have no way to configure that.

**What component or utility would this be added to**

SearchBox

**Have you discussed this feature with our team, and if so, who**

No

**Additional context/screenshots**

**Comment by joschect** [comment]
@yajiex thanks for submitting this! You can currently do this although it's not ideal. Here's a [codpen example](https://codepen.io/pen/) as a workaround. I'll look into possibly making it easier to do this.

**Comment by yajiex** [comment]
Sorry @joschect but seems the link your provided didn't contain the path...

**Comment by joschect** [comment]
@yajiex Sorry about that! [this one](https://codepen.io/slimemold/pen/wZjjBZ) should work!

**Comment by yajiex** [comment]
Thanks @joschect , the workaround looks good to me, looking forward to a better way like exposing a property in the near future!

**Comment by invot** [comment]
My client is demanding this functionality. Instead of implementing this manually, I'd love to see this as an option native to fabric.

**Comment by devrsi0n** [comment]
@joschect Thank you for your work, but your example is broken when input something with mouse hover, I record a GIF. 

[GIF](https://gfycat.com/heartydampandeancat)

Please add a prop to support fixed icon or a good solid workaround.

**Comment by JiahaoShan** [comment]
> @joschect Thank you for your work, but your example is broken when input something with mouse hover, I record a GIF.
> 
> [GIF](https://gfycat.com/heartydampandeancat)
> 
> Please add a prop to support fixed icon or a good solid workaround.

A working workaround is to add the nuclear bomb `!important` to the css width. I know it is hacky but works.

**Comment by Jimit09** [comment]
Is there any update to when will this change be released? This is really important for us and component. We should have some handle to always show icon.

**Comment by khmakoto** [comment]
Hi everyone, sorry for the long time it took before we got back to you. [Here](https://codepen.io/khmakoto/pen/PopwPqo?editors=0010) is a workaround that also works on mouse hover. We might explore a more robust solution in the future but this should work in the meantime.

**Comment by ecraig12345** [comment]
In addition to the styling workaround, I think it would be reasonable to add a prop to handle this case. Given our team's other ongoing work, we're not likely to get to this any time soon, but I'd be happy to review a PR--if anyone would like to help, please comment and we can figure out what the prop ought to be called (and I can provide more detailed implementation guidance if needed).
