### ISSUE TITLE
Dropdown `selectedKey` and `selectedKeys` confusion

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#8883]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/PatoBeltran/pen/YMMaex

 
#### Actual behavior:
 
The `Dropdown` control currently has both `selectedKey` and `selectedKeys` in its props bag, with `selectedKey` working correctly in single selection scenarios and incorrectly in multi selection scenarios, and `selectedKeys` working correctly for multi selection scenarios and incorrectly for single selection scenarios.
 
#### Expected behavior:
 
The fuctionality of these props should be consistent across them so that the same prop could be used in both scenarios instead of having to change between them depending on which scenario we're facing. Additionally, `selectedKey` accepts an array of keys, which seems misleading given that it doesn't work for multi select scenarios.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Maybe later
 
Requested priority: (Blocking, High, Normal, Low) Low
 
Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
I'm marking this as needing backlog review because it needs thought as to the right design, and might not even be fixable apart from the complete Dropdown/ComboBox rewrite #6030.

(Just to be clear for whoever reviews the backlog, this is not something I have active plans to fix, and I don't think Mak does either.)

**Comment by khmakoto** [comment]
Echoing @ecraig12345's sentiment, I think this will need to be fixed as part of the rewrite. This issue serves more as a way to track down how this needs to be fixed.

**Comment by cliffkoh** [comment]
Removing `Type: Bug` since this isn't really per se a bug but more like weird API surface.
