### ISSUE TITLE
Command Bar should not collapse if one one item present

### ISSUE THREAD

**Issue by PatoBeltran** [microsoft/fluentui#8897]
This is more of a DCR. 

It seems to be a weird interaction to collapse to an overflow menu the items in an Action Bar on small screens when the action bar only has one item.

In my case, I have an action bar with only one item that is set to `iconOnly` on small screens. When the action bar reaches a certain size, the item is collapsed to an overflow menu even though the overflow button is the same size as the original item, therefore it doesn't make sense to be collapsed.

**Comment by micahgodbolt** [comment]
having only a single icon only button isn't very common. If you don't want the resizing logic to run you can always set the following:

`onReduceData={() => undefined}`

**Comment by PatoBeltran** [comment]
Thanks for your response! I agree that this is an edge case and that there are workarounds for this. I wanted to surface this as a piece of feedback for the default experience of the component.

**Comment by micahgodbolt** [comment]
We could always add a test to ensure that commandbars with single, iconOnly items never collapse, though I wouldn't consider that high priority enough to put cycles into now. @PatoBeltran if you're interested in adding that check we'd love to see a PR. I'm happy to review.

**Comment by atneik** [comment]
The will be a great addition to the `ResizeGroup`; I remember `Breadcrumb` faces similar issue (which we use in SharePoint property panel to display file paths).

**Comment by micahgodbolt** [comment]
What if the one item had a label? Collapsing to a overflow button would save space. Anyway, pretty easy from a consumer standpoint to remove the resizing if the array length is 1

**Comment by micahgodbolt** [comment]
@atneik would SharePoint be able to change the `onReduceData` if the breadcrumb array is length of 1? We can add a prop that does that automatically, but it doesn't seem necessary.

**Comment by atneik** [comment]
@micahgodbolt I now realize that SP scenario is a little different. It collapses if FileName is too long, resulting in everything hidden behind a triple dot (we are working with 320px of width). As a solution we can truncate the name before sending it to the component. 

In both cases I think consumers can easily have a solution on their end.

**Comment by micahgodbolt** [comment]
hmmm, both cases sound like they might benefit from minimum items prop. it'd be mixed into the shrinking logic to not reduce under a given threshold. 

Suffice to say, this is totally doable with the existing interface, but I could see improvements to make. We'll be put into our backlog.

**Comment by Narvalex** [comment]
Can anyone explain me, please, how can I make a breadcrumb "commandBar-and-resize-friendly"? I face the same issues described is this thread, and as a consumer I can not find the right way to do it with the existing interface. Hopefully I am not asking too much...
