### ISSUE TITLE
Clearable prop for either Dropdown or Combobox

### ISSUE THREAD

**Issue by justinmwarner** [microsoft/fluentui#8976]
**Describe the feature that you would like added**
In some dropdowns, you have the option of clearing the selection by clicking a button. ie: https://codesandbox.io/s/91381468ko?module=/example.js

Is this planned or something we can prioritize?

**What component or utility would this be added to**
ComboBox and/or Dropdown

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**

**Comment by jdhuntington** [comment]
This is a great idea, and I don't believe it is presently reflected in the backlog. Happy to accept PRs that add this functionality. I also believe someone is planning to address some technical debt in the combobox, so this could possibly be reviewed then. Unfortunately I don't have a definite timeline at the moment.

**Comment by joschect** [comment]
@justinmwarner Here's a workaround in the short term that's pretty easy to implement! https://codepen.io/slimemold/pen/gJgrXB

**Comment by joschect** [comment]
It's not ideal but for prototyping or something similar it's not a bad idea. You can also achieve similar behavior if you make a fairly simple controlled component.

**Comment by JustSlone** [comment]
This should be easily solved by controlling the Dropdown Component, linking this to epic issue for future consideration, but closing this particular issue.
