### ISSUE TITLE
DetailsList thumbnails don't render on implementation page.

### ISSUE THREAD

**Issue by noon-otter** [microsoft/fluentui#8997]
On the implementation of customgroupheaders, the thumbnails don't render and instead only show their text links (ie. //placehold.it/221x221). 

https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/customgroupheaders

I'm using Chrome Version 74.0.3729.131 (Official Build) (32-bit) on Windows 10.

**Comment by KevinTCoughlin** [comment]
Thanks for the report @noon-otter. That example doesn't have a custom cell render function for the thumbnail column so it is just rendering text. Perhaps we should explore rendering an `<Image/>` in that column.

I agree that it is a bit confusing. The thumbnail comes from our test data function: https://github.com/OfficeDev/office-ui-fabric-react/blob/d266b15cab701e34a5c2212207e4334662fb4ead/packages/office-ui-fabric-react/src/utilities/exampleData.ts#L38

I'm unsure of the history of this example off-hand.

**Comment by jdhuntington** [comment]
Thanks @noon-otter - I will update this example. I believe the intent is to continue to show text in the details list, but the fact that it shows a thumbnail URL is strange.

**Comment by noon-otter** [comment]
Thanks, didn't realize the intent was to show a text link.

**Comment by KevinTCoughlin** [comment]
Not sure this is a bug so removing the label, it is by design. If we want to clarify the documentation then perhaps we can pursue #9005 or we can add this to our backlog. Unless @noon-otter is willing to address.
