### ISSUE TITLE
Fonts are always fetched even if they are present locally

### ISSUE THREAD

**Issue by adhithyar** [microsoft/fluentui#9118]
*I did go through a ton of issues to see if there is a known issue and didn't see this one. If this is a dupe, please close it. Thanks!!!*

### Environment Information 
 
- __Package version(s)__: Latest
- __Browser and OS versions__: All browsers, Windows 10

### Repro Steps

I am not able to reproduce this on Codepen. But, you can see it for yourself by visiting **project.microsoft.com** and looking at the network tab. Even though **Segoe UI** and **Segoe UI Semibold** are both present in my OS, it still tries to go and download it. Since this font is used everywhere is fabric, this is a high priority resource and rendering is partially blocked on it. 

Browser trying to download **Segoe UI" font
![image](https://user-images.githubusercontent.com/43848996/57836152-f9a89f00-7774-11e9-9dd0-9041825e9735.png)

Brower blocking on downloading **Segoe UI Semibold"* font
![image](https://user-images.githubusercontent.com/43848996/57836238-23fa5c80-7775-11e9-8627-bdd4ccf9ef75.png)

This repros on all the browsers.

I created a simple HTML page to see if `local` is somehow broken. Here is the test html snippet
```
<html>
<head>
<style type="text/css">
@font-face {
    font-family:'Segoe UI Web (West European)';
    src:local("Segoe UI Light"),
        url('https://static2.sharepointonline.com/files/fabric/assets/fonts/segoeui-westeuropean/segoeui-light.woff2') format('woff2'),
        url('https://static2.sharepointonline.com/files/fabric/assets/fonts/segoeui-westeuropean/segoeui-light.woff') format('woff');
    font-weight:100;
    font-style:normal;
}
div {
    font-family: 'Segoe UI Web (West European)'
}
</style>
</head>
<body>
<div>
    Test Test
</div>
</body>
</html>
```
The bug continues to repro locally in Chrome

![image](https://user-images.githubusercontent.com/43848996/57836494-af73ed80-7775-11e9-8e1a-dd3d535250cc.png)

But, other browsers are just fine. Here is Edge for example

![image](https://user-images.githubusercontent.com/43848996/57836615-efd36b80-7775-11e9-8907-3e2b2d975002.png)

Firefox

![image](https://user-images.githubusercontent.com/43848996/57836654-0a0d4980-7776-11e9-8081-4e1aa56e55ca.png)
 
#### Actual behavior:
 
Browser is always fetching locally installed fonts
 
#### Expected behavior:
 
Browser should only fetch fonts that are not locally installed

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? I don't know how to fix this one. I am happy to contribute with the help of someone from the team. 
 
Requested priority: Normal
 
Products/sites affected: Project

**Comment by JasonGore** [comment]
For reference [this is the PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/4206) that originally introduced this change.

**Comment by JasonGore** [comment]
Ok, this is interesting. I verified the behavior in the example you mentioned, did some digging around, and found this chromium issue: [@font-face src: local() should take *font face* name, not *family* name](https://bugs.chromium.org/p/chromium/issues/detail?id=627143)

So I made just one change to your example:
`src:local("Segoe UI Light"),` => `src:local("Segoe UI"),`

Which no longer generates a network request and appears to use local font correctly:

![image](https://user-images.githubusercontent.com/26070760/57954684-76886580-78a8-11e9-9ec7-a6b705d09755.png)

I think this is the chromium bug I linked above. Would you agree?

**Comment by JasonGore** [comment]
Regarding Fabric and fonts, when I look at a [sample CodePen](https://codepen.io/jasongore/pen/GaEMKZ), I don't see the Segoe fonts getting fetched in Edge and Firefox and `Segoe UI` is still showing up correctly. I'm not sure what the fix would be from the Fabric side here.

![image](https://user-images.githubusercontent.com/26070760/57956068-9457c980-78ac-11e9-84a2-1101247e74f5.png)

**Comment by adhithyar** [comment]
Hello @JasonGore! Thanks for triaging this bug really quickly. I really appreciate it. 

I took a deeper look into why the calls to register these fonts are showing up in Project's network trace. To use icons in our code base, we are making a call to `initializeIcons` in our app. The `initializeIcons` call results in fetching all these fonts. If I remove the `initializeIcons` call, the font fetches go away. I am not able to modify your codepen for some reason. Can you update the codepen and add a call to `initializeIcons` and it should repro. 

Thanks for digging up the chromium issue. It was driving me insane. Is there a plan to provide a workaround until Chromium issue is fixed?

**Comment by aneeshack4** [comment]
@adhithyar If you remove the "Light" it won't download the font. The OS doesn't have this font already which is why it's downloading it. I took your html and put it into this [codesandbox](https://codesandbox.io/s/html-x9qsm) and removed the Light - if you pop out the browser in it and monitor the font section of the network tab as you refresh the page you'll see that it doesn't download.

**Comment by adhithyar** [comment]
Hello

I am currently on vacation. I haven’t had a chance to look at the latest from the thread. I will respond back once I am back on Monday 6/17. I apologize for the delay.

Adhithya

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by aneeshack4** [comment]
@adhithyar Sounds good Adhithya - I removed the needs author feedback label so this won't get marked as stale & closed.

**Comment by adhithyar** [comment]
@aneeshack4 Hey Aneesha!!! Sorry it took a long time for me to get back to this. I really appreciate your patience. I also really appreciate the fact that both @JasonGore and you are jumping in to help. 

An update to my original bug report - Firefox is now not loading these fonts anymore. But, Chrome, Edge and IE are still loading these fonts everytime and these fonts are render blocking. 

Regarding whether these fonts are present in the OS or not - I double checked my OS and a few of my colleagues' laptop OSes as well. We all have Microsoft Office installed. So, by default the following three fonts should be available

* Segoe UI
* Segoe UI Light
* Segoe UI Semilight
* Segoe UI Semibold

You can actually see this in Word

![image](https://user-images.githubusercontent.com/43848996/60418214-37338100-9b97-11e9-9b12-71597c209317.png)

So, none of these fonts need to be downloaded again. But, that's not what we see in Project when I take a look at the network tab. 

![image](https://user-images.githubusercontent.com/43848996/60418290-69dd7980-9b97-11e9-9fb9-447b5d0f4c97.png)

In fact, I notice the exact same problem when I visit one of the other Office apps as well. Here is OneDrive trying to load Segoe UI Semilight even though I already have it in my OS

![image](https://user-images.githubusercontent.com/43848996/60418445-c8a2f300-9b97-11e9-8a85-1e35ab2be71c.png)

I believe there is something going on in initializeIcons. But, I am not an expert in that code. I am happy to work together with both of you to fix this issue and unlock some perf wins for our customers. Please let me know on how I can help.
