### ISSUE TITLE
Discussion / Question: using stylesheets vs inline styles

### ISSUE THREAD

**Issue by j-te** [microsoft/fluentui#9174]
`IStyle` is good in its current state but it becomes a mess when trying to customise sub-components. You end up having to override css classes with a combination of using onRender() prop functions. It feels like with styling, you ping-pong while deciding the best way to stylise your base component.

**An example of what could be done:**
```ts
<TextField
  className="my-wrapper-classname" // this wraps every sub-component
  borderless={true} // we want to maintain our own styling
  disabled={disabled}
  type="number"
  value={fieldValue}
  onChange={(_handler, _value) => onChange(_value, field)}
  style={{ textAlign: "right" }}
  styles={
    disabled
      ? {
        fieldGroup: { border: "1px solid #c8c8c8 !important" },
        prefix: { background: "none" },
        suffix: { background: "none" }
      }
      : null }
  prefix="£"
  suffix="pence"
  description="a description that is a sub-component"
  errorMessage="an error message that is a sub-component"
  />
```

**Dirty styling override as alternative to in-line styling (may also require `!important`):**
```scss
.ms-TextField-prefix,
.ms-TextField-suffix {
  background: pink
}
```

of-course messy... but what if we want to apply the hovered or another JS state like readonly? Should I use css selectors? Conditional JS?

**What I would like to do:**
```ts
<TextField
  borderless={true} // we want to maintain our own styling
  disabled={disabled}
  type="number"
  value={fieldValue}
  onChange={(_handler, _value) => onChange(_value, field)}
  styles={{  // or new prop subComponentClassNames
    classNames: {
      fieldGroup: disabled ? "mywrapper-fieldgroup" : "mywrapper-fieldgroup-disabled",
      prefix: disabled ? "mywrapper-prefix" : "mywrapper-prefix-disabled",
      suffix: "mywrapper-suffix"
    }
  }}
  prefix="£"
  suffix="pence"
  description="a description that is a sub-component"
  errorMessage="an error message that is a sub-component"
  />
```

**Describe the feature that you would like added**
_Either:_

1. add "className**s**" subprop to styles and map its sub-props to every sub-component
2. it may make more sense to add new prop called "subComponentClassNames"
    - consider the new prop to ignore prop "styles" if "subComponentClassNames" is specified, to encourage consistent styling (avoid bad design)

**What component or utility would this be added to**
`<TextField>` to begin with but potentially every base component (?)

**Note:** currently I'm having difficulty adding a className to `fieldGroup`.  I don't see in the documentation an easy way to insert this <= so assuming there isn't.

**Comment by kenotron** [comment]
Your timing is great. We're in the middle of discussing how to move forward with subcomponent styling. The thing that we're working on is called Tokens. TextField has not been converted to use this concept yet. 

One workaround that you may not know about here is that the "fieldGroup" key can take in a string which would be interpreted as classname. I've created a codepen that illustrates this:

https://codepen.io/anon/pen/PvEQmv?editors=1111

**Comment by kenotron** [comment]
If this addressed your issue, please close this bug.

**Comment by j-te** [comment]
@kenotron Thank you for the quick response. The new feature you're describing would greatly improve the customisation :)

A string value instead of an object is neat. I'm not sure if I agree with the terminology of Tokens (maybe there's more to it than styles). If it's style-exclusive then what about classToken ?

Can you advise which version/roadmap we can expect this feature for tracking please? 

I'm sure the team is thinking about purging the default styles to minimise css/prevent double-styling. Maybe an **optional prop to remove default className** for those who want minimal components? I find there are many layered styles IE `background` which has to be removed for full styling... Should I replace the stylesheet instead? Probably. Maybe a new tool for 'building a fabric css template'. 

Have a look at this flow-map. I'm not encouraging stylesheet-only design, just highlighting 95% of styling should be achievable by stylesheets:
![styling - take a road](https://user-images.githubusercontent.com/34647206/58199696-fbb8b380-7cc8-11e9-9374-c9ca8164ef82.png)

**Comment by cliffkoh** [comment]
cc @dzearing, @JasonGore

**Comment by kenotron** [comment]
Thanks! I'm marking this as a not an issue at this point because it's more a question / discussion. 

@JasonGore might know more about timing here. But we are internally discussing options for how to do styling.

**Comment by cliffkoh** [comment]
Changing the label to more accurately reflect @kenotron's intent, and to give @dzearing and @JasonGore a chance to chime in.
