### ISSUE TITLE
MessageBar - Fluent Updates

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#9184]
New fluent messagebar styles use the default button instead of the custom gray button we currently use

![image](https://user-images.githubusercontent.com/1434956/58212826-f34e8180-7ca4-11e9-8f7c-8b95bd07fd43.png)

Awaiting responsive design revision

**Comment by Vitalius1** [comment]
@betrue-final-final I see that the button height is 32px now in the toolkit as opposed to 22 I got from Jenna's specs when I styled the `MessageBar` for `fabric-7` branch. Let me know if the final designs are what we have today in the toolkit so I can go and adjust. Or perhaps @GitHubMaxwell can tackle this for fabric-7... 😄

**Comment by micahgodbolt** [comment]
hmm, i'm not sure. looking again at figma and our design they seemed to be pretty well aligned

Us:

![image](https://user-images.githubusercontent.com/1434956/63124660-a2c38900-bf60-11e9-832d-1b32be015fb1.png)


Figma:

![image](https://user-images.githubusercontent.com/1434956/63124681-ad7e1e00-bf60-11e9-84d5-386e174d538f.png)

**Comment by micahgodbolt** [comment]
height appears to match up as well. we might be able to close this. @Vitalius1  anything you can think of we need here

**Comment by Vitalius1** [comment]
I would defer this to @betrue-final-final decision because when I did some fluent updates on this the specs I got were in different abstract toolkit I got for a designer on another team and not sure if  they are up to date with the fluent toolkit. He has the final decision.

**Comment by marygans** [comment]
Current UI has a border color of neutralTertiaryAlt(#c8c6c4) while in both toolkits its neutralSecondaryAlt (#8a8886).
<img width="1294" alt="Screen Shot 2019-08-15 at 2 24 16 PM" src="https://user-images.githubusercontent.com/38991459/63128033-d30f2580-bf68-11e9-998c-321829912564.png">

I will check with Ben for the correct value

**Comment by khmakoto** [comment]
@marygans is there any update on this?
