### ISSUE TITLE
LineChart does not display properly in FireFox browser when ILineChartPoints.data.x is Date type 

### ISSUE THREAD

**Issue by luckyrass** [microsoft/fluentui#9357]
### Environment Information 
 
- __Package version(s)__: (@uifabric/charting 0.30.0) 
- __Browser and OS versions__: (FireFox browser 68.0 Beta 6)

#### Actual behavior:
 

![image](https://user-images.githubusercontent.com/12230173/59013397-73134900-886c-11e9-9ad6-b5f698cced9c.png)

 
#### Expected behavior:
 

![image](https://user-images.githubusercontent.com/12230173/59013448-8cb49080-886c-11e9-8ae8-57f41ddde94b.png)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
It looks like the x and y coordinates are "NaN" for some reason on Firefox but on Chrome they are numerical values... I have no idea why browser would impact these values still looking into that but thought I'd update with at least the info I have so far:
Firefox
![image](https://user-images.githubusercontent.com/4161791/59134731-14fc6980-8931-11e9-94b2-6d94debf4322.png)
Chrome
![image](https://user-images.githubusercontent.com/4161791/59134725-0ca42e80-8931-11e9-9654-f94034c27709.png)

**Comment by aneeshack4** [comment]
Spoke with @Raghurk offline and the fix to this isn't obvious so handing it off to him & his charting team.

**Comment by RajeshGoriga** [comment]
Fix issue and raised a PR https://github.com/OfficeDev/office-ui-fabric-react/pull/9389
