### ISSUE TITLE
VerticalBarChart should show the X-axis descriptor

### ISSUE THREAD

**Issue by luckyrass** [microsoft/fluentui#9359]
### Environment Information 
 
- __Package version(s)__: (@uifabric/charting 0.30.0)
- __Browser and OS versions__: (Chrome 74.0.3729.169, FireFox browser 68.0 Beta 6, IE)

#### Actual behavior:
 

![image](https://user-images.githubusercontent.com/12230173/59014657-bb803600-886f-11e9-9c53-9bb28867927a.png)
 
#### Expected behavior:
 

![image](https://user-images.githubusercontent.com/12230173/59014645-b4f1be80-886f-11e9-8de1-54022e180c9a.png)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) 
 
Requested priority: (Blocking, High, Normal, Low) High
 
Products/sites affected: (if applicable) 
We're going to add verticalBarChart in Reports Modern Workplace Index homepage.
https://portal.office.com/adminportal/#/workplaceindex

**Comment by aneeshack4** [comment]
I debugged through the create xAxis method call and everything seems to be working fine - the xAxis value in the end doesn't seem to be missing anything that the yAxis has: 
![image](https://user-images.githubusercontent.com/4161791/59135191-e7b0bb00-8932-11e9-9b98-30281d5ff1f8.png)

And the each "tick" has a value actually if you Inspect the axis: 
![image](https://user-images.githubusercontent.com/4161791/59135216-fdbe7b80-8932-11e9-9c92-71c15812d32f.png)

So I believe they're just being cut off.

**Comment by aneeshack4** [comment]
Handing it off to @Raghurk & his charting team.

**Comment by RajeshGoriga** [comment]
Fix issue and raised a PR https://github.com/OfficeDev/office-ui-fabric-react/pull/9388
