### ISSUE TITLE
Missing icons from Fabric MDL2 external icon font

### ISSUE THREAD

**Issue by bramdejager** [microsoft/fluentui#9444]
### Bug Report

- __Package version(s)__: WebFluentFonts_1905 (download from https://aka.ms/WebFluentFonts)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal 

Products/sites affected: Windows Fonts directly impacting Office Apps on Desktop

#### Describe the issue:

After downloading the fonts from https://aka.ms/WebFluentFonts I installed them into Windows Fonts. This way I can use them in Office Apps (Word, PowerPoint,...). When trying to add the following icons "TFVCLogo" and "WorkforceManagement" they are not showing up. 

#### Actual behavior:

In PowerPoint, insert a symbol. In the Character code textbox set the unicode value to either F44D or EE0F. Both will not show the related icon symbol. 

#### Expected behavior:

After entering the unicode in the character code textbox, the actual related icon should be shown. This behavior does work for a lot of the icons, like friendly name: CityNext with unicode: EC06.

![image](https://user-images.githubusercontent.com/13313123/59440184-d2d29c80-8df6-11e9-9534-503adf69326d.png)

**Comment by Toonshorty** [comment]
The Fabric UI icons website (https://uifabricicons.azurewebsites.net) indicates the current web font version is FabMDL2 v3.35, while the desktop font is on v2.48i.

![image](https://user-images.githubusercontent.com/7429318/59441675-de22c980-8df0-11e9-9941-40d2c0add996.png)

I don't know if these two numbers both represent the font version, but if so would likely explain why a number of icons are missing.

**Comment by Jahnp** [comment]
Hey @bramdejager , thanks for reporting this. Indeed, the installable Fabric External MDL2 file isn't updated as frequently as the Fabric icons tool that @Toonshorty linked. There's a manual code-signing process that means we only make updates occasionally.

However, as you can see, quite a few icons have been added since the last update of the font, so we'll get the update process started. I'll keep this issue open until we've updated aka.ms/WebFluentFonts.

**Comment by bramdejager** [comment]
Thanks to both of you @Toonshorty and @Jahnp. Great that this is picked up! Any indication on when we can expect this?

**Comment by Jahnp** [comment]
I've reached out to the designers who help us with this, but they're OOF on vacation until next Tuesday. I'd expect end of next week at the earliest, possibly into the following week, but likely no later than that.

**Comment by chryw** [comment]
@Jahnp You've probably told me before, but which one reflects what's available in the latest public package?
1. https://developer.microsoft.com/en-us/fabric#/styles/web/icons
2. https://uifabricicons.azurewebsites.net
3. https://fabricicons.azurewebsites.net

Thanks!

**Comment by Jahnp** [comment]
Ok @bramdejager , good news! We got a new cut of the installable icon font early, and I've updated https://aka.ms/WebFluentFonts with it. You should be able to access it now—please give it a try and let me know what you think.

@chryw , 2 and 3 are near-identical; 2 is public and 3 is internal MS. Both represent the most up-to-date icon sets that we update each week, but don't reflect what's available in @uifabric/icons, which is the public installable package that we update once every month or two.

**Comment by bramdejager** [comment]
@Jahnp I have downloaded the new package 1906. I have good and bad news. I see new icons popping up like the unicode EE0F. That's the good news! 
![image](https://user-images.githubusercontent.com/13313123/60004550-2356bf00-966d-11e9-91bc-24269ec8761e.png)
Sadly I have some bad news too, it looks it is missing icons (at least 1 specific icon). The unicode F44D is missing from the font set. The unicode F44A is there, but nothing afterwards... :-(

**Comment by bramdejager** [comment]
@Jahnp I was wondering if you have an update on this? I'm still missing some icons in the new update. Thanks.

**Comment by Toonshorty** [comment]
@Jahnp I am also seeing some strange behaviour with the latest font. The WaffleOffice365 icon (U+F4E0) doesn't appear to be in the latest font package but I am fairly sure this icon predates the current font version (3.36).

**Comment by AliciaaaRo** [comment]
I found it :) Have a loot to the new font version that solve the problem of the missing icons.

[Fabric External MDL2.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/4032140/Fabric.External.MDL2.zip)

**Comment by khmakoto** [comment]
@bramdejager does @AliciaaaRo's answer help with your issue?

**Comment by bramdejager** [comment]
@khmakoto, @AliciaaaRo just validated the newest package via [https://aka.ms/WebFluentFonts](https://aka.ms/WebFluentFonts). The version is 3.36 as displayed in Windows>Settings>Fonts. 

After validating in Office, still no unicode F44D icon available. Still missing some pieces... 

@Jahnp can you verify the Windows Font is not up to par with the latest icons available in Fabric React or Fabric Core? 

Screenshot of Font settings in Windows 10:
![image](https://user-images.githubusercontent.com/13313123/74380154-5959d680-4de9-11ea-8d3e-ba88b6df17e3.png)

**Comment by Jahnp** [comment]
Oof... 3.36 is *super* old. The latest is v3.68; we'll likely get a 3.69 this week as well. I can work on an update.

**Comment by Jahnp** [comment]
@bramdejager, can you give the assets at [this link ](https://static2.sharepointonline.com/files/fabric/files/webfluentfonts_2002.zip) a try?

**Comment by bramdejager** [comment]
@Jahnp installed the updated version. Still no F44D icon available.

The link [https://aka.ms/WebFluentFonts](https://aka.ms/WebFluentFonts) is pointing to the 3.36 version. You might want to update that to the most recent version? ;-)

Screenshot of Font settings in Windows 10:
![image](https://user-images.githubusercontent.com/13313123/74526179-1d2a9100-4f23-11ea-9281-06c450d0080b.png)

**Comment by Jahnp** [comment]
I'll have to look into why that particular unicode is missing. Sorry, that seems an odd omission.

As for updating the aka.ms link, I was hoping to get everything up to date and verified before pointing everyone to the new fonts 🙂

**Comment by Toonshorty** [comment]
I've installed 3.68 but noticed that the WaffleOffice365 icon is also missing (F4E0) so it may be more than just one.

**Comment by darkriderdesign** [comment]
honestly I'm almost ready to ditch the Fabric Icons... because of this kind of stuff. @Microsoft can't seem to get it together enough to carry on a stable icon set.  It sounds harsh but, good grief  I feel like every time I use Office Fabric, Azure Fluent WHATEVER the set is called In my Designs... in the end, I'm missing some referenced icon.  At this point I'm recommending Font Awesome Pro - Light.

**Comment by Toonshorty** [comment]
@bramdejager I've found a workaround to get the latest version of the icon fonts, although it may be a bit of a grey area license wise.

If you go to the site https://uifabricicons.azurewebsites.net and open the console, you should be able to see the web font in the network tab (you might need to refresh the page first). This is in a .woff format which can't be installed to Windows, but it's fairly easy to convert this to TTF using web or desktop apps.

Would be good to get something official sorted though @Jahnp
