### ISSUE TITLE
LineChart does not show the last point 

### ISSUE THREAD

**Issue by luckyrass** [microsoft/fluentui#9463]
### Environment Information 
 
- __Package version(s)__: (@uifabric/charting 0.131.1) 
- __Browser and OS versions__: (All browsers)

#### Actual behavior:
 

![image](https://user-images.githubusercontent.com/12230173/59496072-42ae5900-8ec3-11e9-946f-d2b56bab6674.png)
 
#### Expected behavior:
 

LineChart shows all data points

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)

**Comment by natalieethell** [comment]
Thanks for reporting this issue, @luckyrass! @Raghurk will take a look.

**Comment by natalieethell** [comment]
I'll just note that it looks like all the points are being plotted, but the Callout values for the last data point are wrong.

**Comment by dzearing** [comment]
@Raghurk this has gone idle for a while; have any update?

**Comment by Raghurk** [comment]
We are looking at this. We had other priorities

**Comment by dzearing** [comment]
@Raghurk I'm going to assume this is a bug. I will remove the needs triage flag and replace with the right labeling. Feel free to adjust as needed.

**Comment by Raghurk** [comment]
@luckyrass this was by design the way charting works today.
