### ISSUE TITLE
Web DatePicker: Time selection

### ISSUE THREAD

**Issue by gavinbarron** [microsoft/fluentui#9545]
I would like a web implementation of a time picker. 

I believe that this would be an expansion of the current web DatePicker as the iOS and Android controls are DateTimePickers.
https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker

No, I have not discussed this with the team.

**Additional context/screenshots**
https://developer.microsoft.com/en-us/fabric#/controls/ios/date-time-picker 
https://developer.microsoft.com/en-us/fabric#/controls/android/date-time-picker

**Comment by aftab-hassan** [comment]
@gavinbarron thank you for submitting a feature request. `TimePicker` is an ask we have been receiving recently. We will add it to our backlog review, and discuss it within the team. Please feel free to check back here or post a comment. 

cc: @micahgodbolt @lorejoh12 (coming from the Teams thread where we discussed a _Calendar input with time input included_ : FYI

**Comment by chriskuech** [comment]
> `TimePicker` is an ask we have been receiving recently

What about `DateTimePicker` ?

**Comment by htryggva** [comment]
We would also welcome an official UI Fabric time picker component to use in our product. Preferably independent of the Calendar or DatePicker components.

**Comment by gavinbarron** [comment]
In my opinion there are use cases for both a time picker and datetime
picker in addition to the DatePicker.

The MWF Datetime picker control can be configured in Date Picker, DateTime
Picker, and Time Picker modes.

Given the current state of the UI Fabric Web controls library I'd suggest
that an independent TimePicker control be shipped initially as this would
not imply or need any interface change to DatePicker. If a consumer needs a
Date Time Picker it should be trivial to compose one with these two
controls. A future update could deliver a composite control as part of the
library.

Heck, I'd even be happy to put my hand up and write the composed control.

**Comment by micahgodbolt** [comment]
Most teams I talk to say that if they need date and time picking that they will create an HOC that combines a date picker and some sort of time picking (dropdowns usually). This is how outlook is currently doing it, so I don't think design is content with that solution and isn't investing in something different. 

If it ain't broke, don't fix it.

**Comment by chriskuech** [comment]
>If it ain't broke, don't fix it.

Makes sense not to change the existing component--but why not merge the HOC back into Fabric?  It's a generic enough requirement that HTML even supports datetime inputs natively.

**Comment by micahgodbolt** [comment]
The HTML version is quite similar to ours in the picking experience. 

![image](https://user-images.githubusercontent.com/1434956/61073935-561de880-a3cb-11e9-8c05-875ea9c56259.png)

The main difference is that they place the time picking inside of the input rather than separate controls. 

![image](https://user-images.githubusercontent.com/1434956/61074074-bf056080-a3cb-11e9-8e06-e16b1c5a4cc6.png)


As far as canonizing something in Fabric, it's possible we'll get there eventually. But its not a huge priority due to the ability to easily create a usable control yourself.....which also gives you flexibility to suit it to your application needs.

**Comment by tomasro27** [comment]
Also interested in a DateTime picker control.
Is this already planned?
Just wondering whether I should find an alternative time picker in the mean time.

Thanks!

**Comment by msdehoward** [comment]
Would love to see a DateTime control as well. Or even a separate TimePicker.
Is this work on the backlog?

**Comment by alxHenry** [comment]
Yammer is also interested in either a combined DateTimePicker, or a separate TimePicker component.

**Comment by georginaso** [comment]
It would be great to have a TimePicker component

**Comment by agnihotriketan** [comment]
I am using web version of Fluent UI react version 7 in my web application.

I am not able to find time picker control yet. Are you planning to release this timepicker component?

**Comment by natashajaved** [comment]
What's the update on timePicker? Is there a plan for it to be developed in near future? I and my team have chosen fabric and so far find it great,  just a catch that we get to have a timePicker which is a requirement from our client. Will really appreciate if its added soon.

**Comment by natashajaved** [comment]
What's the update on timePicker? Is there a plan for it to be developed in near future? I and my team have chosen fabric and so far find it great,  just a catch that we get to have a timePicker which is a requirement from our client. Will really appreciate if its added soon.

**Comment by kamil7x** [comment]
Hey guys, any updates on this? This is really needed feature

**Comment by vixeven** [comment]
Is this a work in progress component? Any updates?

**Comment by KatieProchilo** [comment]
Interested in an update as well

**Comment by Shraddha-113** [comment]
We are using fluent-ui in our project. We needed **Timepicker control with Datepicker**. Is there any updates on this? We are really looking forward it. If no updates then what can be used instead of it?

**Comment by ecraig12345** [comment]
I don't think this is something we currently have on our roadmap, but @JustSlone or @paulgildea (or @lorejoh12 who worked on the DatePicker a lot) should confirm.

**Comment by DigitalMystery** [comment]
For now, our team is using the Date Picker and then a TextField next to it with the type="time".  This is similar to miacahgodbolt's suggestion above.  It would be nice to have one control, but it works at least.  Happy coding!

**Comment by JustSlone** [comment]
Yeah, sorry this is not on our roadmap. 

As for alternatives, one possibility is the interaction used in Outlook Web, which is an editable field with an expandable menu
![image](https://user-images.githubusercontent.com/40304143/103607629-3dae6180-4ece-11eb-9477-b8c131fe929e.png)

**Comment by gregdegruy** [comment]
@JustSlone is there sample code we can see for the editable field with an expandable menu used in Outlook Web?

**Comment by FabioNgo** [comment]
any update about this component. I am considering using fluent UI cuz professional design. it will be great if we have the time-picker component

**Comment by JustSlone** [comment]
@FabioNgo planning is actually starting internally by a partner team on this component. We are only in the early planning and scheduling phase right now so I don't have a concrete timeline (and the work may not end up getting scheduled). Will try to update this when we get more information

**Comment by CheerfulSatchel** [comment]
Greetings, I hope you are all doing well!

For those that are still interested in this control, <a href="https://github.com/microsoft/fluentui/pull/18556">this PR</a> creates the preliminary TimePicker control. 

Thank you and have a wonderful day!

**Comment by yunicz** [comment]
I just tested this new component and it's impossible to set default value for the time picker which makes it unusable for any edit form

**Comment by ecraig12345** [comment]
@yunicz That's a known limitation of the initial implementation. Can you please make a feature request?
