### ISSUE TITLE
Need for component isolation via ShadowDOM or iFrame.

### ISSUE THREAD

**Issue by wkuna** [microsoft/fluentui#9591]
**Problem faced**

We have conflicting styles when loading a fabric UI component from a content script.
When using components such as Callout, Compound Button, etc., we see global styles being inherited, thus we are facing unpredictable style rendering across websites.

**Proposed solution**

We need component isolation in order to incapsulate all the style definitions.
We've identified two possible approaches to solve the underlying issue:
1. Instantiating the Fabric UI compoennt inside a Shadow DOM. We believe this is the desired solution we should pursue.
2. Wrapping the react component inside an iframe. This looks more like a mitigation, although we've found notable examples where developers used iframes for style isolation.

**Shadow DOM limitations**:
1.	Layering creates some unexpected behavior in the way components are rendered. We also have relative positioning issues inside the shadow DOM.
2.	Fabric defined styles are not accessible from within a shadow DOM. Hence, we need a way to pass style information across boundaries.
3.	Icons are undefined inside the shadow DOM.

We've already discussed this issue with Kevin Coughlin, Rajeev Karunakaran and Micah Godbolt

**Comment by KevinTCoughlin** [comment]
@Rajeev-K is doing some exploration here regarding any limitations faced in using Fabric components within ShadowDOM. We'll circle-back at the conclusion of that work with next steps.

**Comment by brion-fuller** [comment]
Interested in this issue too.

**Comment by taurheim** [comment]
Also interested in this, has there been any progress?

**Comment by chuanqisun** [comment]
+1 on this issue. We are migrating a project to UI Fluent with a per-component strategy. However, the existing project has a lot of global style rules that conflicts with UI Fluent. Using the shadow dom would be a great way to isolate UI Fluent components from the existing global styles.

**Comment by krishna-babu** [comment]
+1 on the issue. Any progress here?

**Comment by johnmcase** [comment]
@KevinTCoughlin @Rajeev-K What was the result of the exploration?

It has been over a year since there has been any meaningful update on this issue.  Is there a different issue we should be following instead?

**Comment by PhilippSonntagORGADATA** [comment]
+1 on the issue. Any progress here?

**Comment by tonianelope** [comment]
+ 1 on the issue.
