### ISSUE TITLE
Narrator sometimes stops on invisible element on DetailsList header

### ISSUE THREAD

**Issue by cnamal** [microsoft/fluentui#9658]
Go to https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist
**Export to CodePen**
In scan mode, navigate through the DetailsList's header.

Narrator stops on something:
![image](https://user-images.githubusercontent.com/9625284/60508190-39e2c300-9cca-11e9-8b5f-4ff1b107f602.png)

Looking with Inspect, I suspect it stops on the [label used for sorting](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx#L240), though I'm not sure since I can't repro on the official website directly, and the DOM is identical to the codepen one at first glance.

**Comment by khmakoto** [comment]
Hi @cnamal! Thanks for filing this issue! I can confirm that this is indeed happening. I'll check if we can do something about it or if it is a Narrator issue, as scan mode's inherent function is to break out of author's intent when it comes to navigation and dictation.

**Comment by KevinTCoughlin** [comment]
_I think_ @natalieethell recently investigated something similar with `DetailsList`

**Comment by natalieethell** [comment]
Ah yes, this is because of the label elements. I recently added aria-hidden to the checkbox header label here: https://github.com/OfficeDev/office-ui-fabric-react/pull/9504. We could probably do the same thing for the other header labels!

**Comment by khmakoto** [comment]
Sounds good @natalieethell, I'll try a similar approach here. Thanks!

**Comment by khmakoto** [comment]
Hi @cnamal this behavior is no longer reproducing for me. Is it still reproducing for you?

**Comment by cnamal** [comment]
@khmakoto it is 😥

**Comment by khmakoto** [comment]
@cnamal could you tell me what browser are you using?

**Comment by cnamal** [comment]
On Edge (legacy, not chromium)
Win version: 1909
Edge:
Microsoft Edge 44.18362.387.0
Microsoft EdgeHTML 18.18363
