### ISSUE TITLE
Generic form field

### ISSUE THREAD

**Issue by chriskuech** [microsoft/fluentui#9695]
**Describe the feature that you would like added**
I want all my components to have `label` and `description` props.  Many components support `label` but not `description` (ex: `DatePicker`).  I would assume `Label` exists to circumvent this issue, but `Label` lacks a `description` field. 

**What component or utility would this be added to**
Perhaps add a `description` prop to `Label`

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**

**Comment by khmakoto** [comment]
Hi @chriskuech, thanks for requesting this feature!

@micahgodbolt and @cliffkoh, do you think it makes sense to add a `description` prop to the `Label` component? It is an easy PR to make but I'd definitely want your approval before making it.

**Comment by dzearing** [comment]
I don't understand the use case. What is meant by "description" exactly? Are we talking about an aria label? Or a second line of visible text with specific css styling in mind? 

Other than a few experiment components, I do not see a single component which takes `description`.

**Comment by chriskuech** [comment]
Most of my form components are [`TextField`s](https://developer.microsoft.com/en-us/fabric#/controls/web/textfield) which have both `label` and `description` props.  I would like all my form components to have a consistent look and feel, using the `description` to provide more information to the user about what data to enter.  Currently my `TextField`s effectively provide this information, but my other components awkwardly lack that extra text.

**Comment by micahgodbolt** [comment]
I believe our approach is going to be creating an abstraction to wrap around our existing form fields to give them consistent labels, descriptions, error text etc. I agree our form fields are inconsistent. This work is already being tracked in #5582.

**Comment by chriskuech** [comment]
While I like the idea of a `Form` component, I think this proposal is substantially simpler and could just be done by adding a `description` field to the existing `Label` component.  I believe the `Label` component already exists for this scenario (adding form-field-like styling to a component ad hoc).  Is there any issue with that approach?  I would even imagine a `Form` component implementation might leverage this feature from `Label` to map and wrap components.

**Comment by micahgodbolt** [comment]
We'd like to do a pass over all of the inputs and make them more consistent, but I'd rather do that entire body of work, rather than a single patch that might cause more debt in the future. 

@chriskuech - which controls are you wanting to add description to? Can you simply create your own form wrapper that renders label, description and the form element?

**Comment by micahgodbolt** [comment]
@betrue-final-final we'd really like to make fabric inputs more form friendly. Is there any work done to create consistency regarding labels, descriptions, error states etc? We've got the basic scenarios covered, but what if a checkbox is required? We don't have error states for that.

**Comment by chriskuech** [comment]
Ya I'm not blocked--just requesting a feature enhancement.
