### ISSUE TITLE
Allow rendering modals and other components in another document

### ISSUE THREAD

**Issue by thomasgassmann** [microsoft/fluentui#9742]
**Describe the feature that you would like added**
Office UI Fabric currently renders Modals and all other components in the [current document](https://github.com/OfficeDev/office-ui-fabric-react/blob/6ff7873e60436513ce7c3e4f39982a461fa5c86f/packages/utilities/src/dom/getDocument.ts). In some cases you might want to render a modal dialog not in the current document, but in another one. For example, if the main React component is within an iframe and a modal should be rendered outside of this iframe.
In these cases, it would be nice to have an option to either specify the document or render it in the top-most document.

**What component or utility would this be added to**
`Layer` currently defaults to the document of the root element and renders it using React Portals. All components using `Layer` would be affected (e.g. `Modal`). 

**Have you discussed this feature with our team, and if so, who**
No.

**Comment by JustSlone** [comment]
Closing this out, if this concern remains or there is renewed interest in fixing this feel free to reopen
