### ISSUE TITLE
Dialog: title section rendered in a <p></p> tag

### ISSUE THREAD

**Issue by AndrewCraswell** [microsoft/fluentui#9852]
#### Actual behavior:
 
The contents of the Dialog `title` are rendered in a `<p>` tag, making it impossible to implement more advanced designs where we may need a component or `<div>` to render inside the `title` area.

At the least, there should be a way to use the `Modal` component with some new component such as `DialogHeader` that allows us to reuse some of the Dialog header design and functionality (such as the close button)  in much the same way as the `DialogFooter` is reusable. This could solve the problem and continue the constraint of only allowing a `string` to be rendered in the `Dialog` component header.
 
#### Expected behavior:
 
I would like to be able to render a component inside the `title` area. In the example here, the `Persona` would be expected to be rendered in the header area

``` jsx
<Dialog
     hidden={!show}
     onDismiss={this.props.dismissModalHandler}
     dialogContentProps={{
       title: <Persona text={name} secondaryText={email} size={PersonaSize.size48} 
       hidePersonaDetails={false} />,
       subText: 'Are you sure you want to link this account?'
     }}
     ...
```
![](https://i.imgur.com/lOqim3R.png)

#### Actual behavior:

This throws the following error in the console:
`Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.`

And the actual markup is rendered as:
``` html
<p class="ms-Dialog-title title-117" id="Dialog17-title" role="heading" aria-level="2">
   <div class="ms-Persona ms-Persona--size48 root-119">
      ...
   </div>
</p>
```

#### Are you willing to submit a PR to fix? (Yes, No)
If it's acceptable to just render the title content inside a `<div>` instead of a `<p>`, I can submit the PR. Otherwise, PR to allow reusability of the Dialog header functionality will be more complex and someone with more familiarity should take it.

**Comment by joschect** [comment]
@AndrewCraswell Thanks for the submission! I think there is definitely cause to make this more flexible and you provide a good use case for doing so. 

@kkjeer Do you have a preference for splitting it out or just allowing the title to be rendered as a div?

**Comment by AndrewCraswell** [comment]
@kkjeer, any update on this work item? Thanks!

**Comment by kkjeer** [comment]
@joschect I'd be fine with changing the `<p>` to a `<div>` (of course being careful not to break existing styling).

**Comment by hatpick** [comment]
This is still an issue, what's the status on it?
