### ISSUE TITLE
[Build] Components relying on CDN assets can break CI

### ISSUE THREAD

**Issue by KevinTCoughlin** [microsoft/fluentui#9856]
### Environment Information 
 
CI, specifically Screener visual regression testing

### Please provide a reproduction of the bug in a codepen:
 
PR https://github.com/OfficeDev/office-ui-fabric-react/pull/9853 brought to our attention that some components rely on CDN assets that can change which in turn breaks CI, see:

https://screener.io/v2/states/ryQqxfIYZ.OfficeDev-office-ui-fabric-react/screener-package-bump

The asset in question being:

https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_thumbnail.svg
 
Another example: https://screener.io/v2/states/ryQqxfIYZ.OfficeDev-office-ui-fabric-react/fast-icon

The visual regression tests should be more robust and rely on static assets so a CDN deployment doesn't break Fabric CI.

As part of this work, we should consider whether or not the components themselves should rely on static assets requiring a manual bump to include new assets.

#### Actual behavior:
 
Fabric visual regression tests as part of CI can break due to SharePoint CDN deployment(s).
 
#### Expected behavior:
 
Fabric visual regression tests should be independent of SharePoint CDN deployment(s).

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Low
 
Products/sites affected: Fabric CI

**Comment by JustSlone** [comment]
Closing out older issues, if this is still an issue feel free to reopen
