### ISSUE TITLE
Add useTheme hook

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#9858]
**Describe the feature that you would like added**
We'd like to be able to access the theme via a hook like [Material](https://material-ui.com/styles/advanced/#accessing-the-theme-in-a-component)

**Have you discussed this feature with our team, and if so, who**
Chatted with @JasonGore a bit

**Additional context/screenshots**
We need to be careful and not add confusion here. Most users only care about global theme, and `getTheme` may be good enough for the majority of cases.

The primary value that `useTheme` adds is that it gives access to contextual theming as well. 

Need to consider whether `useTheme` should fall back to global theme in the same manner as `styled`. If `useTheme` only rerenders when contextual theming changes, is it more intuitive to require users to use both `useTheme` and `getTheme` and be explicit with which theme is used?

If `useTheme` does fall back to global theme, a caveat that should be documented with this approach is that changing the global theme won't trigger an automatic rerender for anybody using the `useTheme` hook, similar to `getTheme`. There are multiple benefits to using the `styled` HOC that users would lose when using a `useTheme` hook, such as automatically rerendering when the global theme changes. (This all assumes there's no way to trigger a rerender from a hook via global theme changes, which may be incorrect.)

**Comment by mltejera** [comment]
I will politely disagree that getTheme would works for the majority of cases. If I'm correct, it doesn't get updated when a new theme is loaded, so users (or developers on behalf of users) would have to refresh to get a newly loaded theme, resulting in a clunky end user experience.

At least, that was our experience when taking it for a test spin in the example app. This was our big reason for creating the themed HOC.

**Comment by JasonGore** [comment]
My point was only that for users who use global theming only, `useTheme` provides no additional benefit.

**Comment by Pangamma** [comment]
@micahgodbolt 


/**
 * Adds the "theme" property to a component by extracting it from the value set
 * by fabric's Customizer component. If no scope is given, or scope is not found,
 * the default current global theme set by customizer will be used. If no customizer
 * has been called, the global default fabric theme will be used to fill in blanks.
 * @param Component The component you are wrapping
 * @param scope An optional string like 'PrimaryButton' or 'ArrowNavButton'.
 */
export const withThemeHeavy = <P extends object>(ComposedComponent: React.ComponentType<P>, scope?: string) => {
  return customizable(scope, ['theme', 'styles'], true)(ComposedComponent);
};

**Comment by JasonGore** [comment]
Please note that `customizable` does not support `styles` functions, only `styles` objects.

**Comment by jalo-ms** [comment]
I've currently been using the following successfully. I've tested it with global and local themes, and it responds to both global and local theme changes correctly.

```tsx
/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 */

import * as React from 'react';

import { ITheme } from 'office-ui-fabric-react/lib/Styling';
import { Customizations, CustomizerContext, ICustomizerContext } from 'office-ui-fabric-react/lib/Utilities';
import useForceUpdate from '../react/useForceUpdate';

/**
 * A hook that provides the currently accessible Office Fabric Theme instance.
 * This hook handles both global theming, as well as local Customizer contexts.
 */
export default function useTheme(): ITheme {
  // We need the ability to force a re-render if the global Customizations
  // pushes a change, as it lives outside of the React life-cycle
  const forceUpdate = useForceUpdate();

  // Well actually, we only care about changes to global Customizations
  // if we're not within a local CustomizerContext
  const inCustomizerContext = React.useRef(false);

  React.useEffect(() => {
    if (!inCustomizerContext.current) {
      Customizations.observe(forceUpdate);
    }

    return () => {
      if (!inCustomizerContext.current) {
        Customizations.unobserve(forceUpdate);
      }
    };
  }, [forceUpdate, inCustomizerContext]);

  // Check if we are in a local CustomizerContext
  const customizerContext: ICustomizerContext = React.useContext(CustomizerContext);
  inCustomizerContext.current = !!customizerContext.customizations.inCustomizerContext;

  // Customizations.getSettings will get the global theme by default,
  // or get the locally-scoped theme if present
  const customizationSettings = Customizations.getSettings(['theme'], '', customizerContext.customizations);

  return customizationSettings.theme;
}
```

Sandbox demonstrating its usage: https://codesandbox.io/s/fabric-themes-testing-yvqko

**Comment by Pangamma** [comment]
Scope is kind of important. Would be nice to pass in scope in a way that updates based on the context's values for that scope.

**Comment by aappddeevv** [comment]
Do you need to memoize customizationSettings?
