### ISSUE TITLE
Tooltips in overflows

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#9873]
We want to have a consistent way to add `Tooltips` in components that can overflow. Those components right now are `Breadcrumb`, `OverflowSet` and `CommandBar`, with the potential for `Pivot` to also have the ability to overflow later.

__Current state:__
`OverflowSet` and `Pivot` do not currently have any kind of `Tooltip` implementation in them, while `Breadcrumb` and `Commandbar` do have one (via the `tooltipHostProps` prop), but it is not used in the overflow part of the component, and instead using it for the regular items.

**Comment by shpraka** [comment]
I am facing one similar issue where on focus of regular items, tooltip is visible but when some elements go inside "More options" on page resize(250%-300%), the tooltips are not visible. Does this issue also track the similar behavior or should I file another issue for that?

**Comment by khmakoto** [comment]
@shpraka I think that should be a separate issue, it would be amazing if you could file another issue for that :)

**Comment by brandonthomas** [comment]
@khmakoto as part of this work can we look at ensuring we spread props or expose props for sub components so future improvements are carried over?

**Comment by khmakoto** [comment]
Hi @brandonthomas, I think a critical part here, like you said, is how to expose the `TooltipHost` props to the end user, so it's definitely something that we are taking into consideration.

**Comment by JustSlone** [comment]
Reopening as this continues to be an issue for folks
