### ISSUE TITLE
Pickers lack labels

### ISSUE THREAD

**Issue by myokha** [microsoft/fluentui#9935]
**A feature**: I'm aware of the fact that I can implement a component which will be essentially a `<Picker />` and a `<Label />`.
But at least for the sake of consistency (for example, `<TextField />` and a `<Dropdown />` have it), please add a `label` prop to all the `<Picker />`s.

**Component or utility would this be added to**: Pickers

**Comment by ecraig12345** [comment]
@joschect What do you think about this idea?

**Comment by joschect** [comment]
@ecraig12345 I think that it's a reasonable thing to add. I might suggest creating a composite component that implements the label with the picker which would help us avoid adding more props. It would also make it easier in the future to switch out the picker with a new one if someone wants to switch to the floating pickers.

**Comment by kevinvangelder** [comment]
This change would be helpful for the Learn Student Ambassadors site.
