### ISSUE TITLE
There is a "+" missing in one of the icons in Fabric UI icon library

### ISSUE THREAD

**Issue by meredithxie** [microsoft/fluentui#9938]
### Bug Report
I am a designer using [Fabric UI Icon library](https://uifabricicons.azurewebsites.net/), and I am using a pair of "add favorites": AddFavoriteFill F0C9. 
![Screen Shot 2019-07-25 at 10 06 56 AM](https://user-images.githubusercontent.com/22843278/61894684-d8c39f00-aec5-11e9-814c-bb1ccecfa2a6.png)

#### Describe the issue:

There seem to be missing a "+" on the filled version of AddFavoriteFill F0C9.

If it is not by design, do you mind updating it? If it is by design, it is a bit confusing. Thanks!

**Comment by ecraig12345** [comment]
I agree, that doesn't look right... @Jahnp Do you know what needs to happen to get an icon fixed?

**Comment by Jahnp** [comment]
Thanks for pointing this out @meredithxie . I can follow up with the icons team to verify the design and any mitigation steps needed. Will follow up when I learn more. Thanks!
