### ISSUE TITLE
Absolute paths in sourcemap.

### ISSUE THREAD

**Issue by halfnibble** [microsoft/fluentui#9952]
### Environment Information 
 
- 7.0.0: (fill this out) 
- Mac OS: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

yarn build

 
#### Actual behavior:
 
Absolute paths are in sourcemap output (e.g. /Users/Joshua/workspace/…)
```
{"version":3,"file":"office-ui-fabric-react.js","sources":["webpack://Fabric/webpack/bootstrap","webpack://Fabric/../src/index.ts","webpack://Fabric//Users/joshua/workspace/office-ui-fabric-react/node_modules/tslib/tslib.es6.js","webpack://Fabric/(webpack)/buildin/global.js",
```

#### Expected behavior:

I’ve been trying to debug why webpack produces inconsistent content hashes, and my efforts have led me to believe something about office-ui-fabric-react’s build process may be the culprit. Specifically, I’ve found absolute paths in the src sent to update webpack chunk hashes. Please note: the problem may lie in one of our apps that uses office-ui-fabric-react, so I’m just trying to verify that a production build of this tool will not generate any distributable content with absolute path components.  **Edit: our problem was somewhere else.**

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Low
 
Products/sites affected: sp-client

**Comment by dzearing** [comment]
Paging @kenotron

**Comment by dzearing** [comment]
I am not sure what causes this or if we need some secondary scrub on it.

**Comment by halfnibble** [comment]
After investigating, it appears that this is not blocking us. Our webpack hash will include the absolute path, but it includes the absolute path from the build in our package repo, which is constant for a version number. 

You might want to set “remove absolute path from the production sourcemap” as a low priority task though.

**Comment by kenotron** [comment]
chatted offline... thanks for looking, @halfnibble

**Comment by khmakoto** [comment]
@kenotron, what is the output of this? Is there any actionable item or should we close this?
