### ISSUE TITLE
DocumentCardPreview: make the item limit number an optional prop

### ISSUE THREAD

**Issue by olfilato** [microsoft/fluentui#9991]
**Describe the feature that you would like added**: DocumentCardPreview with multiple documents currently has a hard limit of 3 items displayed before it kicks-in the overflow logic. I propose to make the limit number an optional prop to be passed in, with the default being 3 (the current value).

**What component or utility would this be added to**: DocumentCard

**Have you discussed this feature with our team, and if so, who**: no

**Additional context/screenshots**
![image](https://user-images.githubusercontent.com/1832418/62167380-f2a31e80-b2d7-11e9-90c1-1a3b23f83e0b.png)
![image](https://user-images.githubusercontent.com/1832418/62167407-03539480-b2d8-11e9-9c1f-66bfd23b8246.png)

**Comment by marygans** [comment]
Hi @olfilato! thanks for submitting this feature request. @yiminwu, as codeowner of DocumentCard what are your thoughts on this?
